{100}{}{It's a biker.}
{101}{}{You see a tough biker. He doesn't care about anything.}

#Attempt to talk
{110}{}{Dude, there are no strangers here!}
{111}{}{Ouch, get lost!}
{112}{}{Get lost, ye nugget, I don't have time for this.}
{113}{}{What are you staring at?}
{114}{}{Wanna bite me?}
{115}{}{::burps::}
{116}{}{Damn, I'm in a bad mood today.}
{117}{}{Just open you mouth and I'm gonna shoot you dead!}
{118}{}{Fucking great, guys. Another one!}
{119}{}{Don't come across us in bars, we love to make a hassle there.}
{120}{}{I haven't seen Jay Kukish for a long time.}

#Pop-up dialogue
{200}{}{Take one ride on the chopper and you'll never want to trample the Wasteland with your boots again...}
{201}{}{The car carries the body, but the bike carries the soul...}
{202}{}{The Lord did not fail, swapping the steel bird for the iron horse...}
{203}{}{Live to ride, ride to live...}
{204}{}{We are the devils on wheels!}
{205}{}{The best music is the roar of our engines.}
{206}{}{Gasoline has long since replaced the blood in our veins...}
{207}{}{Our essence is brutality, our God is tech.}

#Female character:
{1110}{}{Gal, there are no strangers here !}
{1111}{}{Ouch, get lost!}
{1112}{}{Get lost, ye horse, I don't have time for this.}
{1113}{}{What are you staring at?}
{1114}{}{Wanna suck on me?}
{1115}{}{::burps::}
{1116}{}{Damn, I'm in a bad mood today.}
{1117}{}{Just open you mouth and I'm gonna shoot you dead!}
{1118}{}{Fucking great, guys. Another one!}
{1119}{}{Don't come across us in bars, we love to make a hassle there.}
{1120}{}{I haven't seen Jay Kukish for a long time.}