{100}{}{You see a very strong man.}
{101}{}{You see Mike.}
{102}{}{You see a large, very muscular man.}

#Before the brawl
{110}{}{[He raises one eyebrow] You ever held a golf ball, boy? With just one hit, you can take a 90-pound midget's head clean off from 300 yards...}
{111}{}{Uh, why would I want to do that?}
{112}{}{That sounds like quite a sight. Maybe I'll try it on you.}

{113}{}{[He rolls his eyes] I'm bored with you, boy. Leave.}
{114}{}{Well, that conversation didn't last long.}

{115}{}{You should mind your own business... [signs] Fine. I was banned for chem use. "Unfair advantage", the boss said. He'd never have known if I wasn't caught with that fucknut dealer. They chased him out of town, too.}

{116}{}{[He throws back his head and laughs] Finally, someone with a sense of humor in this shithole! Name's Mike. I was one of the best fighters in Reno 'til they kicked me out. Now I'm stuck in this hole. Fuck, there's no way to get the blood pumping out here, except hunting.}
{117}{}{I can spar with you, if that's what you want.}
{118}{}{You know, I don't like fighting... I don't think we have much to talk about. I'd better go.}

{119}{}{[Looks you up and down appraisingly] I don't think so, shrimpy. Let me drink in peace.}
{120}{}{Relax, I only want to know what you're doing here.}
{121}{}{Fine. I was just leaving, anyway.}

{122}{}{What am I doing here? I'm trying to get wasted... The name's Mike, by the way. Ever heard of me? I was one of the best fighters in Reno 'til they kicked me out. Now I'm dying of boredom up here. Fuck, there's no way to get the blood pumping out here, except hunting.}

{123}{}{Hell yeah! I'm going to love breaking your face!}
{124}{}{That's all you think about, isn't it?}
{125}{}{I'll have your head ringing so hard you'll think the bombs are dropping again! But before we start, let's lay down the rules.}
{126}{}{Rules?}

{127}{}{This ain't some fucking street brawl, it's an *art*. The game's called "Stay away from Mike". We tie our left hands together so you can't run off, and take turns hitting each other in the face. Break the rules, and you can go fuck yourself.}
{128}{}{We're not fighting to the death, are we?}
{129}{}{Why are you so desperate to hit somebody in the face?}
{130}{}{What do you think of my chances?}
{131}{}{Enough talk, let's do this!}
{132}{}{I need some time to prepare.}

{133}{}{Nah, this ain't like that. Back in the ring, death was just something that happened, but here I don't want people to say, "Oh, there's Mike, he beats people to death for talking to him."}
{134}{}{I'm losing my goddamn mind sitting around doing nothing. I've got to keep myself in shape, you know? My coach always told me, "Mike, you need to practice. Just having muscles won't do the job!"}
{135}{}{[He looks you up and down] Not bad. I may have to bring my A-game.}
{136}{}{[He looks you up and down] Between slim and none, and slim just left town. But I could be wrong.}
{137}{}{[Smirks and cracks his knuckles] See you outside, small fry!}
{138}{}{Better go take a picture of your face so you can remember how it used to look.}

{139}{}{No hard feelings, small fry!}

{140}{}{[Shields his face] Enough! Enough! You win! Here's a hundred bucks, take it. Damn! I need a drink... Or several...}
{141}{}{If only more people would pay me to beat them up. See you, Mike.}
{142}{}{Ha! You know, there's easier ways to commit suicide! Alright, enough of this, I'm going to the bar. Maybe if you ask lightly, someone will help you look for your teeth.}
{143}{}{This is a cruel game, Mike...}

{144}{}{If you were that good, they wouldn't have kicked you out. Unless... You did something you shouldn't have.}
{145}{}{Shit, you're a bit too clever. I was kicked out for chem use. "Unfair advantage", the boss said. He'd never have known if I wasn't caught with that fucknut dealer. They chased him out of town, too.}
{146}{}{Let's fight! That's what you want, right?}

#After the brawl
{150}{}{Next time, we fight to the death.}
{151}{}{Then you'd better get your affairs in order.}
{152}{}{I hope there isn't a next time, then.}

{153}{}{[He smirks] We'll see.}
{154}{}{You said something about fighting in Reno. Tell me more about that.}
{155}{}{I want to ask you something else.}
{156}{}{You really know how to throw a punch. Can you teach me how to fight?}
{157}{}{See you around.}

{158}{}{More questions? I'm not hanging around here for conversation, you know.}
{159}{}{Don't yell in my ear. My reflexes may get the better of me.}

{160}{}{Where do I start? The chems, the whores, the gangsters? Look, there's a boxing scene in New Reno. If you're good enough, you can fight to the death in the ring and make a lot of money on bets. I used to do it, but I got banned... Whatever, it's a long story.}
{161}{}{New Reno? Where's that?}
{162}{}{You've never been to Reno? Just go south on the highway. But keep your gun ready, there's a lot of bandits on the way.}

#Teaching
{163}{}{Teach you? [he shakes his head] Maybe if you were some little guy I would help you out, but you don't need it.}
{164}{}{Teach you? [he shakes his head] I would, but what if you're some raider or other scumbag? I don't deal with those types.}
{165}{}{Teach you? [he shakes his head] I would, but the locals aren't too fond of me already. Sorry, nothing personal.}
{166}{}{Teach you? Hell, why not? I'm no coach, but I can show you a few moves. I won't do it for free, though.}
{167}{}{Teach you? Hell, why not? I'm no coach, but I can show you a few moves. No charge, just 'cuz I like you. [he winks and grins]}

{168}{}{Would two hundred dollars be enough?}
{169}{}{You're a good guy, Mike! Let's not waste any more time...}
{170}{}{That'll do. Give me the money and I'll spend a couple of hours showing you the basics.}
{171}{}{Good. Let's do this...}
{172}{}{Not today.}
{173}{}{Mike raised your unarmed skill by 3%.}

#Ñèëîâîé êóëàê
{180}{}{Something tells me you didn't travel all the way here with just your bare hands.}
{181}{}{Right. Even I can't fight my way up the highway with just my boxing gloves. Thankfully, I knew a guy who knew a guy who could get me a power fist before I left. Best unarmed weapon you'll ever see, but there's a catch - you can't get batteries for it here. Now that I'm here, it's useless.}
{182}{}{I want to buy that power fist from you.}
{183}{}{Right. Well, good luck then.}

{184}{}{Hmm. It's not doing me much good here. But it cost me a fortune! I won't sell it cheap.}
{185}{}{How much?}
{186}{}{3500 bucks ought to cover it.}
{187}{}{Are you out of your mind? Who's going to pay that kind of money? I'll give you 2500 dollars, and that's out of respect.}
{188}{}{It's pricey, but I'll take it!}
{189}{}{Too rich for my blood. Some other time maybe.}

{190}{}{Money up front, wanderer. No offense, but I don't trust easy.}
{191}{}{I'll be back with the cash.}

{192}{}{What, are you going to offer me some colored beads next? Try that shit in Lovelock, not on me. I'm from the city, I know how much this shit is worth.}
{193}{}{Fine. Here, 3500 dollars.}
{194}{}{Suit yourself. Good luck finding a buyer up here.}

{195}{}{Hmm... That's still a lot of money. You've got a deal.}
{196}{}{Great, I've got the cash.}
{197}{}{Maybe not today.}

{198}{}{[He looks at the power fist and takes your money] Farewell, my friend. We've been through a lot together...}
{199}{}{Stop crying and give it me!}
{200}{}{You'll feel better in the morning.}

#Female character:
{1110}{}{[He raises one eyebrow] You ever held a golf ball, girl? With one hit, you can take a 90-pound midget's head clean off from 300 yards...}
{1113}{}{[He rolls his eyes] I'm bored with you, girl. Leave.}
{1133}{}{Nah, this ain't like that. Back in the ring, death was just something that happened, but here I don't want people to say, "Oh, there's Mike, he beats people to death for talking to him."}
{1163}{}{Teach you? [he shakes his head] Maybe, if you were some little snot, I would help you out, but you don't need it.}
{1190}{}{Money up front, girl. No offense, but I don't trust easy.}
