{100}{}{You see a guard.}
{101}{}{You see a caravan guard.}

#После спасения
{110}{}{Is it really over? I can't believe it!}
{111}{}{I thought I was going to die in that cave for sure!}
{112}{}{You saved our asses! Thank you!}

#До спасения
{120}{}{We're trapped here, but they can't get to us. A real stand-off.}
{121}{}{We've never been in a situation like this before.}
{122}{}{We shouldn't have come this far because of those goddamn pelts!}
{123}{}{Those bandits fucked up - they had us trapped, but can't do shit with it.}
{124}{}{We came to buy pelts. Now we're going to pay with ours.}
{125}{}{Geez, how many people the raiders are going to trap in here?}
{126}{}{Things aren't looking good. We just ate our last spare brahmin.}
{127}{}{If we ever get out of here, we'll need to buy more brahmin in Black Rock.}

{130}{}{RAIDER! They're here!}
{131}{}{What? I'm not a raider!}
{132}{}{Raider? Where?!}
{133}{}{You don't have to shout. I'm right here.}

{134}{}{Wait, you're not one of them. What are you doing here?}
{135}{}{I just want to talk.}
{136}{}{Is this some kind of trick? Ah, fuck it - we've got nothing to lose anyway. Whoever you are, you should talk to the boss. He's right behind me.}
{137}{}{Not a bad start...}
