{100}{}{You see a caravan merchant.}
{101}{}{You see a caravan leader.}
{102}{}{Thanks, stranger. I'll see you in Black Rock!}
{103}{}{Keep it tight! They're close!}

{110}{}{Didn't expect to see anyone else here. Let me guess - you were walking along minding your own business when some ugly, brainless raiding bastard with a face like a gecko, a voice like a wet rat, and the smell of both combined popped out of nowhere with half a dozen of his raiding buddies, put a gun to your head, and told you to come in here and lure us out. Am I close?}
{111}{}{More or less, yeah.}
{112}{}{Raiders? There are no raiders out there!}

{113}{}{Those sneaking, spineless sons of bitches! Welcome to the trap, stranger.}
{114}{}{Trap?}

{115}{}{Is that so? You were just passing by and decided to walk into some dank cave for no reason at all, huh?}
{116}{}{I've been on my feet all day. I just looked for a place to take a nap.}
{117}{}{I was being sarcastic. The raiders are right outside.}

{118}{}{Excuse me if I find that pretty goddamn unlikely! But alright - here's what we're gonna do. We're gonna walk outside, you right here beside me, and we'll see what happens. And if you're doing anything funny, well - what I do to you then is gonna be *hilarious*. Come and get me when you're ready to go.}
{119}{}{Fine, I'll be back.}
{120}{}{First, tell me what happened here.}

{121}{}{What we've got here is a goddamn clusterfuck. The other exit's blocked off, we're running low on supplies, and worst of all, I'm behind schedule. I fucking HATE showing up late! It's do or die time, now, and I don't plan on dying. How do we get the fuck out of here?}
{122}{}{How did this happen?}
{123}{}{Let me think.}

{124}{}{Come up with any ideas yet, stranger?}
{125}{}{We were coming up from Reno to pick up some gecko pelts. Were going through the mountains, but something didn't feel right. We busted out the binoculars to look around, and lo and behold, the raiders hadn't even put out their campfires. Pure amateur hour, I said to myself. Fortunately, I knew a cave that cut right through the side of the mountain. We'd just have to take the caravan through it and out the other side, and the raiders would never even know we were there. Clever me, huh?}
{126}{}{What happened next?}
{127}{}{Turns out they knew about the cave too. Fuck, we walked right into their trap! Just after we passed through, they detonated the cave behind us and sealed off the tunnel. There's no way in hell we're getting through that rubble. I don't know if they planned it from the beginning or they just got lucky, but it doesn't really matter now. There's only one exit - all they gotta do is wait. Either we come out and they shoot us or we sit here and starve.}
{128}{}{That's an unpleasant story.}
{129}{}{The raiders are all dead. You can come out now.}

{130}{}{Alright, let's take a look. But if you're fucking with me...}
{131}{}{[Wait]}
{132}{}{God DAMN, son! You did all that? Motherfucking masterful work! Now we can finally get out of this place. Find me in Black Rock - the beer's on me!}
{133}{}{I'll see you there.}

{134}{}{The raiders must have run off. We should leave before they come back.}
{135}{}{Sure, let's go.}
{136}{}{I just need to, uh, take a leak first. You go on ahead.}

#Female character
{1102}{}{Thanks, stranger. I'll see you in Black Rock!}
{1115}{}{Is that so? You were just passing by and decided to walk into some dank cave for no reason at all, huh?}
{1132}{}{God DAMN, girl! You did all that? Motherfucking masterful work! Now we can finally get out of this place. Find me in Black Rock - the beer's on me!}
