{100}{}{You see a girl with a short mohawk.}
{101}{}{At the first glance this girl looks like a very wild (and a very sexy) animal.}

{110}{}{Howdy, cowboy.}
{111}{}{}
{112}{}{Who are you folks?}
{113}{}{Why are you here alone in men's company?}
{114}{}{Howdy. And bye.}

#who are bikers answer
{115}{}{[She makes a very surprised face expression] They're bikers. Can't you see that?!}
{116}{}{I just don't know who bikers are. Tell me about your gang.}
{117}{}{I see. Forget it.}
{118}{}{Ha-ha! What hole did you crawl out of if you don't know about bikers? Okay, I guess I can tell you... Our guys ride around the wasteland looking for tech stuff that works. And then sell them in the cities. Because of their passion for technology, they know their way around repairs, so a lot of important mobsters stop by from time to time to offer us a good deal.}
{119}{}{Pre-war technology? Curious. Where do they get it?}
{120}{}{Abandoned city districts or military bases. It's a pretty dangerous life, if you ask me.}
{121}{}{What's so dangerous in digging through junk lying around for some old wires and dirty toasters?}
{122}{}{Ya know, wastes are filled to the brim with strange creatures, especially in the desert regions. Not a lot of folks who spend their life in cities even know 'bout them. And we run into them all the time! Besides, all those old buildings in abandoned city districts can fall right on your head if you're not careful enough. So yeah, it's pretty dangerous.}
{123}{}{I get it. How long have you been doing this?}
{124}{}{Me? Like, my whole life! And the others - twice as much!}
{125}{}{Twice as much? How old are you then?}
{126}{}{Fifteen. What about it?}
{127}{}{Woah! Well... I... Hmm... All right, never mind.}
{128}{}{Yea-ah. Where do the likes of you even come from... Forget it.}
{129}{}{Okay. See you.}

#answer - what is she doing here
{130}{}{Well, I'm here 'cause it's more fun with those guys than anywhere else. And much safer.}
{131}{}{They don't look like defenders of the innocent to me. More like someone who likes to get rowdy and kick ass.}
{132}{}{Okay, I get it. Let me ask you something else.}
{133}{}{Well, yeah! But it's cool! And besides, what's the problem? They can get a little bit drunk, yeah, and then you better stay out of their way, but people love them! 'Cause they're cool!}
{134}{}{Yeah, right. Kicking asses in the bar is not that cool, especially if you are the bar owner.}
{135}{}{Bullshit! Bar owners *always* appreciate the company of bikers, and we *always* are on good terms with them.}
{136}{}{Is that so? Interesting. What about the mayhem they cause? What about the damages?}
{137}{}{Other clients pay for the damages. Do you understand how many people visit those places just to watch some ass-beating? Owners profit from that, their place gets only better after such brawls.}
{138}{}{An interesting point... Are you serious?}
{139}{}{Uh, yeah. Is that so surprising?}
{140}{}{Well, yes.}
{141}{}{Not really.}

{142}{}{Ew. What hole did ya crawl from, cowboy?}
{144}{}{From the vault to the west.}
{145}{}{I didn't crawl from anywhere. I just want to live my life like an adequate person, not a scum like you are.}
{146}{}{I didn't crawl from anywhere... You know what, actually it is true to some extent.}
{147}{}{I'm from a normal post-apocalyptic society.}
{148}{}{Have you ever considered the fact that "post-apocalyptic society" is not a normal thing by default?}
{149}{}{Uh... You may be right, I guess.}
{150}{}{That's right.}
{151}{}{Okay, forget it.}

{152}{}{What?! Guys, this skunk dares to talk shit 'bout us!}
{153}{}{}
{154}{}{Hey! Wait a minute! She didn't understand what I was saying! Me neither, to be honest...}
{155}{}{Oh, is that so? Protect yourself, you freaking anarchists!}
{156}{}{Our guys won't let you get away with this bullshit. Shut the fuck up and don't even try to squeak about our brotherhood. We're *free* and independent. You'll never get it.}
{157}{}{All right, you're the boss...}

{158}{}{Really?!}
{159}{}{Yeah. I even have my passport. Here, take a look.}
{160}{}{Yeah. I can even show you the coordinates.}
{161}{}{Yeah. I'm serious.}
{162}{}{That's wicked! If that's true... Ya know, you should tell our leader about it. He loves tech and would be *very* glad to visit your vault.}
{163}{}{I'll think about it.}

#where are you from?
{170}{}{Where are you from?}
{171}{}{Vegas. Why do you ask?}
{172}{}{You've gotten yourself quite far away from home...}
{173}{}{Don't worry about it.}

{174}{}{I wouldn't mind to go anywhere in America as long as I'm with Phil and his fellas!}
{175}{}{Did your parents allow you to loiter around the desert with those guys?}
{176}{}{Are they reliable?}
{177}{}{Okay.}

{178}{}{I didn't ask for their permission.}
{179}{}{Those bikers - are they reliable?}
{180}{}{We'll talk later.}
{181}{}{They rule! You can really feel that you are free when you stick around them. They won't judge you or anything, you can just be yourself, you know?}
{182}{}{All right. Let me ask you about something else.}
{183}{}{How do they treat you?}
{184}{}{Can't be better. Only they can provide me with all the happiness in the world. I don't even hesitate to chug a couple of beers with them. If I were "home" my parents would hand my ass over to me for even thinking about drinking beer. }
{185}{}{Ha! So, they are just drunks?}
{186}{}{No, but they always enjoy a good beer... Still, they like tinkering with some dirty tech more. But if you combine these... Oh, that's a real holiday!}

#Vegas Family quest
{200}{}{Hey, was it you who ran away from your parents in Vegas? They have been searching for you everywhere...}
{201}{}{[Sighs] Let 'em be. I'm not coming back to them.}
{202}{}{You're making a mistake. They supported you for all those 15 years of your life...}
{203}{}{I don't want to hear your bullshit! Pack your stuff and get ready for the trip home!}
{204}{}{Why did you run away from them?}
{205}{}{Whatever. Suit yourself.}

{206}{}{Look at this Mr. Goodie Two-Shoes! Ugh, I can't even stand your face. Listen, buddy, I love my freedom too much to give it up because of someone's principles.}
{207}{}{Would you look at this little rebel! Go home, NOW!}
{208}{}{What a drag. Go away, mind your own business.}
{209}{}{You little... I'll find a way to get you back to your parents!}
{210}{}{Okay, maybe you'll change your mind sometime.}

{211}{}{Like hell they did. They only forced me to do boring shit all the time. "Behave, learn to write, blah-blah-blah". If I hadn't met Phil and his boys, I would have died of boredom in that shining shithole of a city.}
{212}{}{"Shining shithole"? Vegas? Really?}
{213}{}{What? The Vegas looks nice, but it's built on lies, cemented in frauds... 'Aight! Stop bothering me with those fucking questions! I won't come back there anyway.}
{214}{}{Why not? I feel like I'm behind bars there. Go to work in the morning, come back from work at the evening. Who could ever appreciate such kind of life?}
{215}{}{So you were simply exploited, right?}
{216}{}{Well, well, so you just don't want to work for a living, right?}
{217}{}{You should listen to your parents, you little brat. Pack up and go home to your family!}
{218}{}{That's right! I'm only fifteen! I used to party at "Hard Rock Cafe" every Saturday night. That's where I met those bikers. As soon as my parents found out about it, my dad forbid me to visit these parties again. He's such a dork, he only cares about his work and nothing else.}
{219}{}{Why's that? Was he afraid that bikers might get you in trouble?}
{220}{}{And I agree with his decision. Kids shouldn't ever participate in such shady parties.}
{221}{}{Well, we're from Clear City! My dad holds on so tightly to his chair at City Hall that he won't even leave the city limits to try to find me! I don't want to be so clean and act like I'm above everyone else. Bikers are my best friends, and I will never leave them!}
{222}{}{You know, you're right about your friends. You should have just convinced your father that it was possible to combine a free life and a job in a prestigious place. That's all.}
{223}{}{I don't think so. Your family is more important, don't you see? They're your parents and they worry about you. They even hired me to find you. Isn't that the best proof they love you?}
{224}{}{All right, quit this childish nonsense! You should have received a good spanking a long time ago! Pack your shit and get ready to go home, NOW!}
{225}{}{Damn, I don't know. I need to think about it.}
{226}{}{My *family* is nothing but a pair of wardens in this prison of mine called "home". Can't even visit the toilet without being supervised. One step outside and there it is - a voice in my ear asking "Where are you going?". So yeah, family is family, that's right, but my freedom is more important to me. I won't miss them...}
{227}{}{Really? You don't sound confident enough for me. I can see your uneasiness.}
{228}{}{Hmm, well, you may be right. But you should know that your family worries about you very much. Remember that.}
{229}{}{Oh, shut up, for fuck's sake! I know my parents better than you!}
{230}{}{Maybe. But I know better what happened to them after you left.}
{231}{}{[Her eyes widen] Wh... What happened?!}
{232}{}{See! You are worried. You do care about them, don't you?}
{233}{}{Damn! Do you understand what I can do to you for a joke like this?...}
{234}{}{Don't worry, your parents are fine, except for being extremely stressed out.}
{235}{}{Yeah-yeah, come on, make up more stories.}
{236}{}{I'm serious! Your father looked terrible. Tired, black circles under his eyes. Can't sleep because he doesn't know where you are. I think you'll get him to the grave with your recklessness.}
{237}{}{Is that true?... [The girl stumbles for a second, them tries to pull herself together] but... I...}
{238}{}{Don't hesitate. They will always be glad to see you, even if you want to stay with your friends. Just pay them a visit from time to time, so they wouldn't worry too much.}
{239}{}{Well... No promises. We'll see.}
{240}{}{I don't know what to do... I... Uh, damn. Okay! When Phil goes to Vegas next week, I'll go with him, hope I won't bother him too much... I'll see how they're doing and come back.}
{241}{}{That's something. All right then. See you.}

{242}{}{Looks like you managed to persuade the girl to come back to her parents, at least temporary.}

{243}{}{[The girl shudders] I think you'd fit the mayor's office in Vegas quite nicely, together with those bastards wearing suits. Get away from me!}
{244}{}{Okay, all right, all right. As you wish...}
{245}{}{But what would I tell your parents?}
{246}{}{Whatever, I don't care anymore.}
{247}{}{So I can tell them that you're dead?}
{248}{}{Hmm. If you don't want to go, maybe you'd like for me to pass something to your parents?}
{249}{}{All right, I won't bother you anymore.}
{250}{}{Hey, that's actually a good idea! Maybe they'll stop sending mercenaries for me... And babysitters like you.}
{251}{}{We're going to need a proof that you are okay. How about a personal item?}
{252}{}{You know, I think that's a bit too much. I won't participate in this.}

{253}{}{I have this locket with my photo inside. That's the only thing I have from my previous life.}
{254}{}{Give me that locket. I'll take it to your parents.}
{255}{}{You know, I think that's a bit too much. I won't participate in this.}
{256}{}{[Takes off the locket and looks at it with nostalgia in her eyes] Wait... Let me look at it one last time...}
{257}{}{Quit screwing around and give me the locket, I've got other business to do.}

#Female lines:
{1110}{}{What's up, girl.}
{1118}{}{Ha-ha! What hole did you crawl out of if you don't know about bikers? Okay, I guess I can tell you... Our guys ride around the wasteland looking for tech stuff that works. And then sell them in the cities. Because of their passion for technology, they know their way around repairs, so a lot of important mobsters stop by from time to time to offer us a good deal.}
{1142}{}{Ew. What hole did ya crawl from, cowgirl?}
{1152}{}{What?! Guys, this bitch is asking for a good ass-whooping!}
{1206}{}{Look at this Mrs. Goodie Two-Shoes! Ugh, I can't even stand your face. Listen, miss, I love my freedom too much to give it up because of someone's principles.}
{1239}{}{Well... No promises. We'll see.}
