{100}{}{You see a girl with a short mohawk.}
{101}{}{At the first glance this girl looks like a very wild (and very sexy) animal.}

{110}{}{Howdy, cowboy.}
{111}{}{}
{112}{}{Who are you folks?}
{113}{}{Why are you here alone in men's company?}
{114}{}{Howdy. And bye.}

#who are bikers answer
{115}{}{[She makes a very surprised face expression] They're bikers. Can't you see that?!}
{116}{}{I just don't know who bikers are. Tell me about your gang.}
{117}{}{I see. Forget it.}
{118}{}{Ha-ha! What hole did you crawl from if you don't know about bikers? All right, I guess... Our guys drive around the wasteland and search for working technological stuff. And then sell them in towns. 'Cause of their technology passion they know a lot about repairing stuff, so lots of important mobsters visit us from time to time to offer a profitable deal.}
{119}{}{Pre-war technology? Curious. Where do they find it?}
{120}{}{Abandoned city districts or random bases. It's a pretty dangerous life, if you ask me.}
{121}{}{What's so dangerous in digging through junk to find old wires and dirty toasters lying around?}
{122}{}{Ya know, Wastes are filled with strange creatures, especially in the middle of the desert. Not a lot of folks who spend their life in cities know 'bout them. And we're facing them all the time! Besides, all those old buildings in abandoned city districts can fall right on your head when you don't expect it. So it's pretty dangerous.}
{123}{}{I get it. How long have you been doing this?}
{124}{}{Me? Like, my whole life! And the others - twice as much!}
{125}{}{Twice as much? How old are you then?}
{126}{}{Fifteen. What about it?}
{127}{}{Woah! Well... I... Hmm... All right, never mind.}
{128}{}{Yea-ah. Lookin' at you know and still wondering where did you crawl from... Uh, okay then.}
{129}{}{Forget it. See you.}

#answer - what is she doing here
{130}{}{Well, I'm here 'cause it's more fun with those guys. And much safer.}
{131}{}{They don't look like policemen to me, more like the opposite - someone who likes to rumble and kick some ass.}
{132}{}{Okay, I get it. Let me ask you something else.}
{133}{}{Well, yeah! But it's cool! And what's the problem? They can get a little bit drunk, and then you better stay out of their way. But people love them for *that*! 'Cause they're *cool*!}
{134}{}{Yeah, right. Kicking ass is not that cool, especially for the bar owner.}
{135}{}{Bullshit! They *always* appreciate the bikers company and we *always* had a good relationship with them.}
{136}{}{Is that so? Very interesting. What about the damages they inflict to the owner's place?}
{137}{}{Other barflies pay for those damages. Do you understand how many people visit those places just to watch some ass-beating? Owners profit from that, and the place gets only better after the fight.}
{138}{}{Really?}
{139}{}{Uh, yeah. Is that's so surprising?}
{140}{}{Well, yes.}
{141}{}{Not really.}

{142}{}{Ew. What hole did ya crawl from, cowboy?}
{144}{}{From the vault to the west.}
{145}{}{I didn't crawl from anywhere. I just want to live my life like an adequate person, not a scum like you are.}
{146}{}{I didn't crawl from anywhere. Actually, it is true to some extent, though.}
{147}{}{I'm from a normal post-apocalyptic society.}
{148}{}{Have you ever considered the fact that "post-apocalyptic society" is not even a normal thing by default?}
{149}{}{Uh... You may be right, I guess.}
{150}{}{That's right.}
{151}{}{Okay, forget it.}

{152}{}{What?! Guys, this skunk dares to talk shit 'bout us!}
{153}{}{}
{154}{}{Hey! Folks! Wait a minute! She didn't understand what I was saying! Me either, to be honest...}
{155}{}{Oh, is that so? Protect yourself, freaking anarchists!}
{156}{}{Our boys won't forgive you for this bullshit. Shut the fuck up and don't even squeak about our brotherhood. We're *free* and independent. You can't dig that.}
{157}{}{All right, you're the boss...}

{158}{}{Really?!}
{159}{}{Yeah. I've got my passport on me. Here, take a look.}
{160}{}{Yeah. I can even show you the coordinates.}
{161}{}{Yeah. I'm serious.}
{162}{}{That's wicked! If that's true... Ya know, you should tell about it to our leader. He loves any tech and would be *very* glad to visit your vault.}
{163}{}{I'll think about it.}

#where are you from?
{170}{}{Where are you from?}
{171}{}{From Vegas. Why do you ask?}
{172}{}{You've gotten yourself quite far away from home...}
{173}{}{Don't worry about it.}

{174}{}{I wouldn't mind to go anywhere in America as long as I'm with Phil and his boys!}
{175}{}{Did your parents allow you to loiter around the desert with those guys?}
{176}{}{Are they dependable enough?}
{177}{}{Okay.}

{178}{}{I didn't ask for their permission.}
{179}{}{Those bikers - are they dependable enough?}
{180}{}{We'll talk later.}
{181}{}{They rule! You can really feel free when you stick around them. They won't judge you or anything, you can just be yourself, you know?}
{182}{}{All right. Let me ask you about something else.}
{183}{}{How do they treat you?}
{184}{}{Can't be better. Only they can provide me with all the happiness in the world. I don't even hesitate to chug a couple of beers here. If I were "home" my parents would hand my ass over to me for even thinking about drinking beer. }
{185}{}{Ha! Are the others all drunkards?}
{186}{}{No, but they always enjoy a good beer... Still, they like tinkering with some dirty tech more. But if you combine both of these... Oh, that's a real holiday!}

#Vegas Family quest
{200}{}{Hey, was it you who ran away from your parents in Vegas? They have been searching you everywhere...}
{201}{}{[Sighs] Let 'em be. I'm not coming back to them.}
{202}{}{You're making a mistake. They supported you all of those 15 years you've been alive...}
{203}{}{I don't want to hear your bullshit! Pack your stuff and get ready for the trip home!}
{204}{}{Why did you ran away from them?}
{205}{}{Well, whatever. Suit yourself.}

{206}{}{Look at this Mr. Goodie Two-Shoes! Ugh, I can't even stand your face. You know, buddy, I love my freedom too much and I won't give it up because of some principles.}
{207}{}{Look at this little rebel! Go home, NOW!}
{208}{}{What a drag. Go away, mind your own business.}
{209}{}{You little... I'll find a way to get you back to your parents!}
{210}{}{Okay, maybe you'll change your mind sometime.}

{211}{}{They *never* supported me. They only forced me to do boring shit, always told me: "behave, learn to write, blah-blah-blah". If I didn't meet Phil with his boys I'd die from boredom in this shining shithole of a city.}
{212}{}{"Shining shithole" Vegas? Really?}
{213}{}{What's wrong? The Vegas is build out of lies, cemented in frauds... 'Aight! Stop bothering me with those fucking questions! I won't come back there anyway.}
{214}{}{Any why not? I feel like I'm behind bars out there. Go to work in the morning, come back from work at the evening. Who would ever appreciate a life like that?}
{215}{}{So you were simply exploited, right?}
{216}{}{Well-well, don't want to go to work, aren't we?}
{217}{}{You should listen to your parents, you little brat. Pack up and go home to your family!}
{218}{}{That's right! I'm only fifteen! I used to party at "Hard Rock Cafe" every Saturday night. That's where I met those bikers. As soon as my parents found out about it, my dad forbid me to visit those parties again. He's such a dork, he can only see his work in front of his eyes and nothing else.}
{219}{}{Why's that? Was he afraid you might get in trouble with them?}
{220}{}{And I agree with his decision. Kids shouldn't ever participate in such shady parties.}
{221}{}{Well, we're from the Clean City! My dad clings onto his chair in mayor's office so tightly, he won't even leave the city limits to try and find me! I don't want to be so clean and act like I'm superior to everyone else. Bikers are my best friends, and I will never leave them!}
{222}{}{You know, I think you're right about friendship. I just think you should have tried to persuade your father that you can spend your leisure time at parties and work at a prestigious position at the same time.}
{223}{}{I don't think so. Your family is more important, don't you think? They're your parents and they worry about you. They even hired me to find you. Isn't that the best proof they love you?}
{224}{}{All right, quit this childish nonsense! You should have received a good beating a long time ago! Pack your shit and get ready to go home, NOW!}
{225}{}{Damn, I don't know. Need to think about it.}
{226}{}{My *family* is nothing but a pair of wardens in this prison of mine called "home". Can't even visit the john without any supervision. One step outside - and you hear a voice from behind, asking "Where are you going?". So yeah, family is family, that's all right, but my freedom is more important to me. I won't miss them...}
{227}{}{Really? You don't sound confident enough for me. I can see you're feeling uneasy...}
{228}{}{Hmm, well, you may be right. But you have to understand that your family worries about you a lot. Remember that.}
{229}{}{Oh, shut up, for fuck's sake! I know my parents better than you are!}
{230}{}{Maybe. But I know better what happened to them after you left.}
{231}{}{[Her eyes widen] Wh... What happened?!}
{232}{}{See! You're worried. You care about them, don't you?}
{233}{}{Damn you! Do you understand what I can do to you for these kind of jokes?..}
{234}{}{Don't worry, your parents are fine, only extremely stressed out.}
{235}{}{Yeah-yeah, come on, make up some more stories for me.}
{236}{}{I'm serious! Your father looked terrible. Tired, black circles under his eyes. Can't sleep properly because you're gone. I think you'll bring him to the grave with your recklessness.}
{237}{}{Is that true?.. [The girl stops for a second, remembering her past actions and trying to gather herself] but... I...}
{238}{}{Don't hesitate. They still wait you for dinner. Even if you don't want to leave your friends. Just don't forget about them and pay them a visit so they could stop worrying about you.}
{239}{}{Well, I can't be sure. We'll see.}
{240}{}{I don't know what to do... I... Uh, damn. Okay! When Phil goes to Vegas on the next week, I'll go with him, hope I won't bother him too much... I'll see how they're hanging and come back.}
{241}{}{That's something. All right then. See you.}

{242}{}{Looks like you managed to persuade the girl to come back to her parents, at least temporary.}

{243}{}{[The girl shuddered] I think you'll fit the mayor's office in Vegas quite nicely together with those bastards in suits. Get away from me!}
{244}{}{Okay, all right, all right. As you say...}
{245}{}{Wait, but what should I tell you to your parents?}
{246}{}{Whatever, I don't care anymore.}
{247}{}{So I can tell them that you're dead?}
{248}{}{Hmm. If you don't want to go, maybe you'll pass something to your parents?}
{249}{}{All right, I won't bother you anymore.}
{250}{}{Hey, that's a good idea! Maybe they'll stop sending mercenaries... And babysitters like you.}
{251}{}{We're going to need a proof for this. How about a personal item?}
{252}{}{You know, I think that's a bit too much. I won't participate in this.}

{253}{}{I have this locket with my photo inside. That's the last thing I have left from my previous life.}
{254}{}{Give me that locket. I'll take it to your parents.}
{255}{}{You know, I think that's a bit too much. I won't participate in this.}
{256}{}{[Takes off the locket and looks at it with nostalgia in her eyes] Wait... Let me look one last time...}
{257}{}{Quit screwing around and give me the locket, I've got other business to do.}

#Female lines:
{1110}{}{What's up, girl.}
{1118}{}{Ha-ha! What hole did you crawl from if you don't know about bikers? All right, I guess... Our guys drive around the wasteland and search for working technologies. And then sell them in towns. 'Cause of their techonology passion they know a lot about repairing stuff, so lots of important mobsters visit us from time to time to offer a profitable deal.}
{1142}{}{Ew. What hole did ya crawl from, cowgirl?}
{1152}{}{What?! Guys, this bitch is asking for a good ass whooping!}
{1206}{}{Look at this Mrs. Goodie Two-Shoes! Ugh, I can't even stand your face. You know, sister, I love my freedom too much and I won't give it up because of some principles.}
{1239}{}{Well, I can't be sure. We'll see.}
