{100}{}{You see gravedigger Bob.}
{101}{}{You see a dirty hairy man in old tattered clothes.}

#Starting conversation
{110}{}{[You see a dirty villager, reeking of sweat and alcohol. His head, barely covered with long thin locks of hair, looks oddly shaped; it's as if, when being born, he was pulled out by the skull with forceps, and, when he saw the world he'd have to live in, he grabbed onto whatever he could to keep himself from it.]}
{111}{}{Um, excuse me, who are you?}
{112}{}{Don't just stand there, hairy! Are you going to say hi, or what?}

{113}{}{[He jumps and whirls his dirty face to you, opening his mouth wide, showing the yellow tooth, probably, the only one he has.] Oh, my golly gosh! W-why'd you have to go and sh-care me like that?}
{114}{}{I'm sorry, I didn't mean to! It won't happen again.}
{115}{}{Quit shaking, coward. I asked you a question.}

{116}{}{Uh, erm... I'm Bob, the local gravedigger and c-carpenter. I'm n-nobody sh-peshial.}
{117}{}{My name is }
{118}{}{. Nice to meet you, gravedigger Bob.}
{119}{}{I disagree, you're very special. Of all the freaks in this village, you're easily the freakiest.}

{120}{}{[For a couple of seconds, he numbly glares at you, then extends his muddy hand, smiling wide with his toothless dirty mouth] O-o-oh, it's sho g-good to meet a n-nice pershon! [he looks around with shame in his eyes] S-shorry for the messh. I don't usually h-have visitorsh.}
{121}{}{Don't worry about it. Can you answer a few questions?}

{122}{}{[He mumbles something inaudible under his nose] ...like everyone. Why would they... Dish-gushting little... }
{123}{}{Don't mumble at me. I need answers, and it's unpleasant enough talking to you as it is.}

{124}{}{I - I don't know anyshing. I only make c-coffinsh. And - and dig g-gravesh... }
{125}{}{Then I'm wasting my time. I'm getting out of here.}
{126}{}{Then you must have time to talk, right?}

#Reaction when digging the graves
{130}{}{H-hey! Are... A-are you the one who'sh been r-robbing the gravesh?}
{131}{}{Who, me? No, I'd never do that.}
{132}{}{If you tell anyone, I'll be looting your corpse next. Got it?}

#Second conversation
{150}{}{Huh, what?}
{151}{}{Nothing, calm down.}

{152}{}{What's that awful smell?}
{153}{}{Don't you feel lonely all the way out here by yourself?}
{154}{}{Tell me about Black Rock.}
{155}{}{[He looks around, then sniffs his dirty clothes] Oh... It'sh... Me, I guessh... }
{156}{}{I... I d-don't like crowd-sh, and, uh... And people don't like to be around a g-gravedigger. That's j-jusht... Jusht how it ish... }
{157}{}{Uh... I don't know... It's p-peasheful. Jushtin doeshn't want to - to let anybody in, but... But that'sh how we all got here.}

#About Jed
{160}{}{Who is that coffin outside for?}
{161}{}{[He sighs shakily] It'sh for... It'sh for Jed. He s-shaid he'sh going to... To d-die shoon. But he'sh been sh-aying that for a long time. Ushually, when shomeone d-diesh, we jusht wrap them in rag-sh, but Sh-mith is... Sh-mith is sh-pecial.}
{162}{}{LetТs talk about something else.}

{163}{}{Smith, you traveled a long way to come here, and now you will stay here forever.}
{164}{}{This place hurt you, but... }
{165}{}{... But you conquered it. And... Started new life here.}
{166}{}{We will never forget you.}
{167}{}{Rest in peace. You earned it. Amen.}

{168}{}{Now let's hit the bar!}
{169}{}{It looks like Jed is dead.}
{170}{}{What happened to Smith?}
{171}{}{It wazh... It wazh a normal day. Uzhual weazher. He wazh outshide, l-looking up at the shky, and... And jusht... He jusht fell ash-leep. [he wipes his eyes with a dirty sleeve] Oh, man, he... He wazh the only man I've ever sheen that died by natural caushes.}

#ѕро ∆асмин
{180}{}{How do you feel about Jasmine?}
{181}{}{[He smiles crookedly] She... Well, she's a... S-she'sh a good girl. I'd talk to her, but... But I'm afraid to. She's infectioush. What would p-people shay? No, I'm... I'm fine being alone.}
{182}{}{Would you like to live with her?}

{183}{}{Me?! Oh, yesh! Yesh, I'd love to!}
{184}{}{I'll keep that in mind.}

{185}{}{I want to talk to you about Jasmine.}
{186}{}{I told you, it... It would be pos-shible, if she w-weren't shick.}
{187}{}{Really? Ohh, that's awkward. She told me she thinks your mother shat herself while giving birth and kept the wrong pile, that you rape the corpses you get and eat what remains, and that they made her fuck dogs in Reno but you helped her get over it, because the thought of touching you puts it all in perspective.}
{188}{}{I cured her infection. She wants to start a family, Bob. Are you interested?}
{189}{}{Alright, forget it.}

{190}{}{What?! [his voice raises to a shriek] Why?! Why me?! What did I ever do? Sho, maybe I shtink a little and I have bad teesh - well who doeshn't around here? What a tramp she turned out to be... She hershelf looksh like she crawled out from shome dumpshter. I'll never talk to her again!}
{191}{}{Should I go tell her that?}
{192}{}{Yesh! Oh, golly-golly! N-no, I can't shcrew this up. I'll do it! It'sh my l-lasht chance. Ahh, I - I have to get ready, really good!}
{193}{}{Think about it. I'll go talk to her.}

{194}{}{Bob, I can help you with her... }
{195}{}{Uhh... No, I don't, uh, really kn-know you. You're j-jusht shome guy, why should I t-trusht you? What did you do here?}
{196}{}{You donТt trust me? Well, fine.}

#√робокопатель
{200}{}{Hey Bob, is it true you "play around" with the corpses you bury?}

{201}{}{No! They're lying! They're all lying, it'sh not true! It'sh NOT!}
{202}{}{Hey, you can tell me, Bob. One gravedigger to another.}
{203}{}{Fine, forget it.}

{204}{}{N-nobody trusht-sh you around here, you know that. Why should I?}
{205}{}{Fine, forget it.}
{206}{}{}
{207}{}{[He sighs] I... It only happened a c-couple of timesh... Look at me! I never had a girlfriend! I - I have needsh, you know?! Sho, I have to take care of myshelf!}
{208}{}{I don't know what you're talking about! Jusht - jusht leave me alone!!}
{209}{}{Fine, I'm leaving.}
{210}{}{Calm down, or you're going to lose your last tooth.}
{211}{}{Needs?}
{212}{}{I guessh I have noshing to hide now... Here. [he puts an old magazine out of his pocket] T-take it. It hazh helped me to go though a lot of yearsh, but thanksh to you, I don't n-need it anymore. I have another life now.}
{213}{}{What an unusual magazine... }
{214}{}{You earned some experience for using your speech skill.}
{215}{}{Wh-what'sh the point of hiding it now? After what J-Jasmine shaid, I can't even l-look at a woman... Here. [he puts an old magazine out of his pocket] T-take it. It hazh helped me to go through a lot of yearsh, but I don't n-need it anymore.}
{216}{}{If I tell you, I'll have n-noshing left. I'm all alone in my life... }
{217}{}{Fine, forget it.}

#The main quest of this location
{250}{}{Hmm. You have some nice boots there. Where did you get them?}
{251}{}{Uh... T-they were on sh-ome dead man I buried. Jush-t a pair of old boot-sh... }
{252}{}{Any old boots from any old corpse? Show me the soles!}
{253}{}{[He looks nervous] Wh-wh-what for? They're just b-b-boot-sh!}
{254}{}{Buh-buh-buh-because if there's a star there, I'll know they're Milo's buh-buh-buh-boots, asshole!}
{255}{}{Just show me. If there's a star on the soles, then we'll talk about what happens next.}

{256}{}{[He looks around frantically] Wait, I - I, uh, I have to go shee Jushtin - }
{257}{}{So Justin's a part of this? Tell me what you know about Milo, or the next one buried out here will be you!}
{258}{}{Bob, you have to come clean with me. After all I did for Black Rock, don't you think you can do that?}
{259}{}{All I want is the truth, Bob. Just tell me what happened. I promise you won't be punished for it.}
{260}{}{No, *I'll* go see him. Stay here until I get back.}

{261}{}{You - you promishe? Lishten, I didn't want to! They m-made me do it!}
{262}{}{Well, well. Tell me everything.}
{263}{}{How can I trush-t you?! I don't even know you! Leave me alone! Go away!}
{264}{}{I'll be right back. Stay here, don't move.}
{265}{}{You won't tell anyone? P-pleazhe, Jushtin and William shouldn't know about thish! They'll kill me!}
{266}{}{I promise. Just tell me what happened.}
{267}{}{No, no, no! [he covers his face with his arms] Don't touch me, pleazhe! I'll t-tell you everyshing!}
{268}{}{Let's hear it.}
{269}{}{[Frantically waves his hand around] Don't - don't touch me! I'll fight you!}
{270}{}{I'll give you time to think about your options. Maybe you'll be smarter about this when I come back.}

{271}{}{It'sh - it'sh Jushtin's sh-on! It'sh all his fault! Him and hizh gang, they - they killed Milo, took hizh shtuff and made me b-bury his body! It wazhn't my fault! I didn't have anyshing to d-do with it! I jusht dug the grave and buried the body, that'sh all!}
{272}{}{I have questions for you.}
{273}{}{Enough of this. I'm going to get to the bottom of this.}
{274}{}{I have more questions about Milo.}

{275}{}{J-jusht don't tell anyone!}
{276}{}{Who attacked Milo?}
{277}{}{Why'd they make you dig Milo's grave?}
{278}{}{Why did you take Milo's boots?}
{279}{}{What happened to Milo's delivery?}
{280}{}{Why didn't you tell anyone?}
{281}{}{I have another question.}

{282}{}{[He gulps dryly and his voice drops to a whisper] The... The "Moleratsh" gang. Jushtin'sh shon, he'sh - he'sh one of them... }
{283}{}{They had to h-hide hizh body, and... [he shrugs helplessly] ...where elshe could they do it, if not here?}
{284}{}{I jusht wanted to wear shomeshing n-nice! If I knew thish would happen, I wouldn't have t-taken them!}
{285}{}{They t-took it. He had a whole shack of g-gecko sh-kinsh, and they took it all!}
{286}{}{[He looks around nervously] Jushtin wouldn't hurt me, but hizh - hizh shon... He told me to k-keep my moush shut, sho... Sho I kept it shut! You won't... T-tell him I talked to you, r-right?}
{287}{}{No! I don't believe you! You'll r-rat me out! You're jusht like them! Like everyone!}
{288}{}{Okay, I'm sick and tired of this. You give me the truth right now, or I'm telling everything to William!}
{289}{}{You're - no, no! Thish ish b-blackmailing! Everyone will hate you for thish!}
{290}{}{Not nearly as much as they'll hate you, when I tell William you killed Milo... }
{291}{}{Fine, I'll deal with this myself. You wait here.}

#∆енские реплики
{1195}{}{Uhh... No, I don't, uh, really kn-know you. You're j-jusht shome woman, why should I t-trusht you? What did you do here?}
{1207}{}{[He sighs] I... It only happened a c-couple of timesh... Look at me! I never had a girlfriend! I - I have need-sh, you know?! Sho, I have to take care of myshelf!}
{1260}{}{No, *I'll* go see him. Stay here until I get back.}
{1287}{}{No! I don't believe you! You'll r-rat me out! You're jusht like them! Like everyone!}
{1291}{}{Fine, I'll deal with this myself. You wait here.}
