{100}{}{You see Justin.}
{101}{}{You see always frowned man with awfully dirty, hairy hands. Apparently, he likes to dig into tech.}

{107}{}{Hey, I saw your fight with Mike. And you know what? I loved it! Man, it took me back to when I was young... And you know, Mike was looking for it for a while now. So, thanks for the show.}
{108}{}{Er, you're welcome... }

#Starting conversation
{110}{}{Yeah?}
{111}{}{Do you have any work for me?}
{112}{}{Bye.}

{113}{}{Who's in charge here?}
{114}{}{Apparently, me and William. But lately he's done more harm than good, because of his increased trustworthiness and friendliness to outsiders. Sooner or later his "welcome mat" policy's gonna bite us in the ass. So, I have to make sure we don't fill up with useless mouths to feed.}
{115}{}{Right. Another question.}
{116}{}{Right. That would be all.}

#Quest - rid the community of filth
{120}{}{Did you hear what happened to Jasmine?}

{121}{}{What have you done?! Now this filth is never gonna leave! What was the point of curing her? Believe me, everyone would be better off with her gone!}
{122}{}{You promised you'd pay me!}
{123}{}{But why?!}
{124}{}{I see you're not happy. I'll go then, to not make you nervous any further.}
{125}{}{Hey, maybe this felt all warm and fuzzy for you, but *I*, on the other hand, have to *live* here! And I don't want some dirty whore as a neighbor, who had who-knows-what diseases in her! And her flirty manners - they are making me sick!}
{126}{}{Like hell! I promised a hundred bucks to you for getting *rid* of her! You made things worse! If you want to hold hands and hug over your random acts of kindness, go to William, because I don't tolerate that shit!}
{127}{}{Sorry, I misunderstood you. Now she's dead. You can go and see for yourself.}
{128}{}{Really?}
{129}{}{Holy shit, you're something else, aren't you? First you save her life, then you choke it out. Did you decide to grab the devil by both balls at once? Fine, fine, the job's done, have to pay. A hundred bucks, just as we agreed. Now leave me.}
{130}{}{With pleasure.}

{131}{}{So you're the one that finally sent that bitch to hell? Beautiful work, and not a moment too soon. Let me give you a token of my appreciation - after all, we may need more "help" in the future. [he gives you 100 dollars]}
{132}{}{Thanks, I'll see you around.}
{133}{}{You're happy about this?}
{134}{}{Damn right I am. This is my home, dammit. I don't need diseased whores walking my streets. That bitch would have poisoned the whole town, if not in body, then in mind. And her flirty manners - makes me sick just to think of it.}
{135}{}{Harsh rules... Reminds me of home. See you.}

{136}{}{So we won't be seeing her again? Finally! That's a relief. Thanks, stranger. Let me give you a token of my appreciation - after all, we may need more "help" in the future. [he gives you 100 dollars]}
{137}{}{What happened to her? "Nothing good" would be a great answer.}
{138}{}{Er, nothing yet.}
{139}{}{It's just so happens that she's dead.}
{140}{}{[He smiles] Is that right? I've been waiting a long time for this. I'll have to break out the whiskey to celebrate! Let me give you a token of my appreciation - after all, we may need more "help" in the future. [he gives you 100 dollars]}

{150}{}{You want to be useful? Go strangle that whore in her sleep. It's the best thing you could do for this place. Just make sure to wash your hands afterwards.}
{151}{}{What whore?}
{152}{}{Is there a less violent option?}
{153}{}{Why do you need to get rid of her?}
{154}{}{I'll do it.}
{155}{}{I don't like the sound of that. I won't do it.}
{156}{}{I will think about it. Later.}
{157}{}{}
{158}{}{There's no work for you here. Not from me, anyway..}
{159}{}{Fine.}

{160}{}{Jasmine, that used-up bitch from Reno. Her father decided to take her out of her natural habitat and brought her here. Yuck!}
{161}{}{No, there's not. I'd have done it long ago myself, if it weren't for William - the graveyard is nearby anyway. But he wants us all to join hands and sing happy songs until everything works itself out. Weakling. He's got no sense of reality. He still thinks she can be cured!}
{162}{}{She's infectious. She hasn't spread it yet, luckily, but why would we want this pathetic whore here anyway? This is a decent community. She's poisoning everything we've built just by being here.}
{163}{}{Good. I'll pay you a hundred bucks to get rid of her. Kill her, chase her out - I don't care, just get that cum dumpster out of Black Rock! And don't fall for William's bleeding heart bullshit!}
{164}{}{It's your choice. But I'd pay a hundred bucks to get her out of here.}
{165}{}{A hundred bucks? Okay, I'm in.}
{166}{}{Give me some time to think.}

{167}{}{What's in it for me, if I make her disappear?}
{168}{}{Respect and a hundred bucks from me, personally.}

{169}{}{Do you have a fuse for a water pump?}
{170}{}{Oh, I get it. Our neighbor Gerlach sent you, right? Well, I don't give handouts. And anyway, I don't have a spare. Maybe the bigger cities have something. Like Reno - it had a lot of repair shops before the war.}

#Quest - fugitive slaves
{180}{}{What do you think of the escaped slaves?}

{181}{}{I think they should keep on escaping in the other direction. Don't get me wrong, but we don't need people like that here. They're nothing but trouble for us.}
{182}{}{Trouble? How?}
{183}{}{First, we've got plenty of mouths to feed already. Yeah, we're not short of food right now - not between the geckos we hunt, the plants and the brahmin William bought - but that's not gonna last forever. Sooner or later, there's gonna be lean times, and we'll regret taking in every straggler that wanders into town then. We are alive and well here only because of my water pump, sucking the underground water from depths below.}
{184}{}{And second?}
{185}{}{And second, they're fugitive slaves! Look at the collars on their necks! Everyone that comes to Black Rock is going to know what they are, and word's gonna get back to their owner eventually. He'll send slavers to take them back, and all of us along with them! Yeah, maybe that doesn't mean anything to you, but you don't have to live here. I don't want me or my son to spend the rest of our lives waiting for this to catch up with us.}
{186}{}{I can get rid of them, if you want.}
{187}{}{I'll think about this.}
{188}{}{Get them out of here, I don't care how. But I can't do anything myself - I don't want William to get all self-righteous on me again.}
{189}{}{}
{190}{}{About those slaves... }
{191}{}{What can you tell me about them?}
{192}{}{You don't have to worry anymore. They're dead.}
{193}{}{You don't have to worry anymore. They're gone.}
{194}{}{Great! That's a load off my mind. Here - a hundred bucks. You earned it.}
{195}{}{Great deal.}
{196}{}{We already discussed this. They do not belong here, end of story.}
{197}{}{William and I decided to have them clean the brahmin pen, so get used to seeing them around.}
{198}{}{[He throws up his hands in frustration] After everything I've done! All the years I've spent building this place, and outsiders like you just swarm it like flies on brahmin shit! You are all the same! You think they're going to do *half* of what I've done for this place? Why do you think they even came here?}
{199}{}{Wait... }
{200}{}{[He ignores you] Why do you think they were in collars in the first place? You think it's the best and brightest that become slaves? No! They're slaves because that's all they're good for, cleaning up shit! They were probably sold into slavery because they're criminals or neck-deep in debt or they fucked up their life in some other way - and now they're going to fuck up ours! And William wants to let them! FUCK!.. why am I even bothering to explain this to you? You're not even listening. Just get the fuck out of my house. And don't come back!}
{201}{}{As you wish. I did what I had to.}
{202}{}{Great! That's a load off my mind! [he hesitates] But... What if they come back? Look, here's fifty bucks. I just hope I don't see them any more. I'm getting too old for this kind of stress.}

#Quest - missing brahmin
{210}{}{What do you know about William's missing brahmin?}
{211}{}{Only that snotty William's brat lost his horned two-headed friend while sleeping on the job. He'll deny it, sure, but how else do explain a half-ton of meat disappearing from right under his nose?}
{212}{}{You almost sound happy about what happened.}
{213}{}{How do I know you didn't do it? Weren't you seen around the stables?}
{214}{}{Who do you think could have done it?}
{215}{}{Do you know who uses shotgun shells filled with pieces of nails?}
{216}{}{Sure I do. I've got the only workshop in town - if you need to make anything more complex than a club, you come to me. But ammo's hard. Only Bolt made some shotgun shells for himself once.}
{217}{}{I *will* be happy if William learns something from this. It was probably stolen by one of the outsiders he let in. Maybe he'll be a little less trusting now.}
{218}{}{Look how close the toilet is to the stables! Anyone could be there, at any time. Even me.}
{219}{}{Hey, I don't want to blame anyone without evidence, but you and I both know - it was one of William's outsiders. Hey, how about you? Where were *you*, when the brahmin went missing?}
{220}{}{No more questions.}
{221}{}{Have you heard that story about the missing brahmin?}
{222}{}{...Shit. I knew it. Shit! I knew Bolt was mixed up in some dirty business, but this? I never thought he'd do this.}
{223}{}{He was forced to do it by members of a gang he used to belong to.}
{224}{}{Goddammit! You see? You see what William's done? If it weren't for him taking in everyone he could find, we wouldn't have this problem! First the whore, now the slaves, now a retired raider! What next? A bankrupt pimp? A fucking cultist, maybe?}
{225}{}{Doesn't Bolt deserve a second chance? William wants to help people. You just want to cast them away.}
{226}{}{Don't. Don't you fucking dare talk to me like that. Me and Bolt have had good times together! He helped clean the windmill, he helped dig the well, he helped with all the different machinery around here... But this doesn't make him innocent. And it doesn't give William the right to make everyone else suffer due to his bad decisions, either.}
{227}{}{You won't find any saints in this world. You should appreciate what you've got. But for now, I'm leaving.}
{228}{}{Think what you want. I'm not arguing this with you.}
{229}{}{You're right. For this community to prosper, you need to cut out everyone who can't contribute.}
{230}{}{No, not cutting them out. We need to keep them out in the first place. We should turn away all the garbage when they first arrive, and anyone good enough to keep, we should educate like our children. But none of us know how to do that.}
{231}{}{That's right. I'm glad you admitted it. Now, I have to go.}

#About Black Rock
{250}{}{Can I ask you some questions about this place?}
{251}{}{Can't stop you. But don't think I'm gonna chat with you until my tongue swells.}
{252}{}{How did all this start?}
{253}{}{How do you manage to live in such a dry and exposed environment?}
{254}{}{}
{255}{}{Ask Jed. He was here before any of us, running away from "civilization". He was alone until William and I settled down here. But then William started gathering every shiftless vagabond he could find. Look, I get it - I couldn't have done everything without help, but the types he's bringing in now? Diseased whores and runaway slaves? I didn't sign up for this shit.}
{256}{}{Because of me, that's how. If it hadn't set up the electricity and the water pump, no one would be living here, but Jed. We got lucky - there were some sort of metal sculptures here. Now they're the buildings we're sleeping in. And as for exposure? That just means we can see any attackers coming. We've got cover and they don't. I don't fear any attacks from outside - it's the dangers inside that I'm worried about.}

#Quest - searching of a delivery man
{260}{}{Do you know anything about the missing courier?}
#So now William's got you on this? Fuck, I knew he wouldn't let it rest.
#Do you have a problem with my search?
#That courier's got gecko skins. William wants to use them to set up a caravan route. Fuck... I've got nothing against Milo, but we'd all be better off if he was sleeping drunk under a bush or something.
#What's the problem? Tell me the details. Maybe you'll change my mind.
{261}{}{What's to know? He's just a couple of days late. It's nothing.}
{262}{}{Are you sure? You're always looking for ways to get rid of people, aren't you?}
{263}{}{Fine, I believe you.}
{264}{}{Oh, you think I did something, huh? Mean old Justin's just looking for reasons to kill someone, is that what you think? You don't know a fucking thing about me. Anyway, I've been here all along, ask anyone. Your courier's probably drunk in a ditch somewhere.}
{265}{}{I don't believe you. I'm watching you.}
{266}{}{What about your son - where he was at the day of Milo's murd... Err, disappearance?}
{267}{}{}
{268}{}{}
{269}{}{[Immediately lunges forward] DON'T YOU FUCKING DARE!! Don't you dare blame my son! He'd never! NEVER! I've sheltered him from this since the day he was born! I forced him out of that fucking gang! And now you come in and undo everything I've worked for? Get out! Get out before I tear out your lying fucking tongue!!}
{270}{}{Milo's corpse is in the graveyard. See for yourself.}
{271}{}{Oh, I'll go. I'll see. And then, you'll see! You'll see he had nothing to do with this! He... He couldn't have... }
{272}{}{Let's go, then.}
{273}{}{Fine, I'm going, jeez... }
{274}{}{[You leave to the cemetery and come back after Justin sees the truth. He collapses onto a chair and grabs his head, letting out a long, miserable groan.}
{275}{}{Oh, I'm sorry, World's Best Dad, I didn't catch that. Can you repeat it?}
{276}{}{[Let him recover.]}
{277}{}{[His voice is barely above a mumble] Fuck you. You have no right to judge me.}
{278}{}{Oh?}
{279}{}{Now, do you understand why I always fought newcomers? How can we be responsible for them if we can't deal with our own problems? God, Eugene... How did it ever go this far?}
{280}{}{You knew about this?!}

{281}{}{No! I mean... Fuck... I never wanted this. When I heard William wanted to set up a caravan route with Reno, I got pissed. My son offered to scare off the caravan with a few warning shots from the mountains. I said no, but... I guess he told his new friends. I never meant for this to happen! All I wanted was a peaceful, quiet life.}
{282}{}{It seems you just weren't meant to have one. What now?}
{283}{}{I'm sorry I put you through this, but now we have to do something.}
{284}{}{Now? [he shakes his head sadly] This gang, the "Molerats" - they must already have a plan to attack the caravan. There's no way to stop them now. If you want to try, I won't interfere, but I can't help you.}
{285}{}{There's always a way. The next time I see you, there'll be a caravan here.}
{286}{}{Then we have nothing to talk about. Bye.}
{287}{}{I won't try to stop you. But mark my words - if this caravan does go through, raiders will come with it. And where there's caravaneers, there's whores, thieves, and con artists. Our community will be just another cesspool like Reno. And it'll all be on you.}
{288}{}{Goodbye, Justin.}

{290}{}{So we've got you to thank for the caravan, huh? Did you even think about what'll happen to Black Rock, now? They'll bring more people here. Whores, drug addicts, criminals. You don't even give a shit, do you? You don't even live here. You're just some stranger who blew in from the wastes, and you've decided all of our futures. How fucked up is that?}
{291}{}{Yeah, I get it. And now it's time for this stranger to make more history somewhere else. Bye.}
{292}{}{I don't see that caravan around. I won't lie - I'm glad. So it would have brought so more money - so what? Let that money stay in Reno with the whores, the drug addicts, and the gang lords. William was *this* close to destroying everything we've built... And the only thing that saved us is some stranger from the wastes. Isn't that crazy?}

#Female character
{1121}{}{What have you done?! Now this filth is never gonna leave! What was the point of curing her? Believe me, everyone would be better off with her gone!}
{1127}{}{Sorry, I misunderstood you. Now she's dead. You can go and see for yourself.}
{1129}{}{Holy shit, you're something else, aren't you? First you save her life, then you choke it out. Did you decide to grab the devil by both balls at once? Fine, fine, the job's done, have to pay. A hundred bucks, just as we agreed. Now leave me.}
{1131}{}{So you're the one that finally sent that bitch to hell? Beautiful work, and not a moment too soon. Let me give you a token of my appreciation - after all, we may need more "help" in the future. [he gives you 100 dollars]}
{1201}{}{As you wish. I did what I had to.}
{1219}{}{Hey, I don't want to blame anyone without evidence, but you and I both know - it was one of William's outsiders. Hey, how about you? Where were you when the brahmin went missing?}
{1283}{}{I'm sorry I put you through this, but now we have to do something.}
{1290}{}{So we've got you to thank for the caravan, huh? Did you even think about what'll happen to Black Rock, now? They'll bring more people here. Whores, drug addicts, criminals. You don't even give a shit, do you? You don't even live here. You're just some stranger who blew in from the wastes, and you've decided all of our futures. How fucked up is that?}
{1291}{}{Yeah, I get it. And now it's time for this stranger to make more history somewhere else. Bye.}
{1292}{}{I don't see that caravan around. I won't lie - I'm glad. So it would have brought so more money - so what? Let that money stay in Reno with the whores, the drug addicts, and the gang lords. William was *this* close to destroying everything we've built... And the only thing that saved us is some stranger from the wastes. Isn't that crazy?}
