{100}{}{You see Eugene.}
{101}{}{You see a scruffy young man in a leather jacket. He looks like he hasn't showered in a long time.}
{102}{}{We don't need all sorts of scum around here.}

#Разговор у загона по поводу беглых рабов
{110}{}{Oh, look. An outsider from the wasteland now decides how our community should be run. You know what I think?}
{111}{}{I couldn't care less wha- }
{112}{}{What do you- }
{113}{}{[He ignores you] That my old man's right! The only thing we ought to give you, newcomers, is two loads of buckshot! You think I don't have the guts to do that? Huh? Try me. TRY ME!}
{114}{}{With what, dumbass, your invisible shotgun?}
{115}{}{Why do you want to shoot us? No one did anything wrong.}
{116}{}{Oh yeah? Well, uh... Fuck! [he angrily kicks the fence so hard that the beams begin to shake] I'm warning you - don't fuck with us! [he turns around and storms off, mumbling something under his breath]}
{117}{}{Us? Who's us?...}
{118}{}{[He ignores you] That my old man's right! The only thing we ought to give newcomers is two loads of buckshot! And I can tell you're thinking the same thing. }
{119}{}{But don't think that makes us friends. Watch yourself and don't piss us off. [he turns around and walks away]}

#Разговор о ситуации с Майло
{120}{}{Yeah, what?}
{121}{}{Nothing.}
{122}{}{I want to talk about your raider gang.}

{123}{}{[He laughs] Oh, my raider gang? Where did I get that?}
{124}{}{Stop lying. I know you killed Milo, so you'd better start talking.}
{125}{}{You know I'm telling the truth, even if no one else does. It's only a matter of time until I get the evidence to prove it. I'll be back when I do.}

{126}{}{Who, me? [he looks around with an unconvincing expression of utter dismay] And why should I believe that?}
{127}{}{Gravedigger Bob is wearing Milo's boots. He told me everything.}
{128}{}{I have evidence from Gerlach. You were seen talking to Milo there, for example. Give me the truth and I won't have to go to William, or your father.}

{129}{}{Bob told you? [he looks around anxiously before he leans in] Fine, newcomer, you got me. What now?}
{130}{}{[He looks around anxiously before he leans in] Fine, newcomer, you got me. What now?}
{131}{}{I want details. Tell me exactly what happened to Milo.}

{132}{}{That's it? You'll leave me alone after this?}
{133}{}{Why Milo?}
{134}{}{How did you know about the delivery?}
{135}{}{What did you do with the package?}
{136}{}{Tell me about your gang.}
{137}{}{Didn't you think you'd be caught eventually?}
{138}{}{Let's talk about your punishment.}

{139}{}{Milo had an agreement with the gang back when we were big. He'd give us information, and we'd keep him from being attacked. That's how he managed to make all his deliveries. There was a time when we controlled the whole valley.}
{140}{}{William wanted gecko pelts from Gerlach to set up some crazy caravan deal. My father said he'd ruin everything. I went to Milo, told him to lose the pelts, but he told me to fuck off. That's when the gang decided to get rid of him. I didn't want this to happen, I swear! But I couldn't stop them.}
{141}{}{I didn't take any of it, but the rest of the gang took the pelts. What they did with them, I don't know.}
{142}{}{We're the Molerats! You've never heard of us? Most of us came from Reno, a few from Salt Lake City. Thieves, killers, pimps - we were everything a gang could be, back when we were big. Hey, don't look at me like that! We were just trying to survive.}
{143}{}{Ohh, scary. Do you have any idea what you're talking about? We're a GANG! We've killed more people than you've ever met! And you won't be a problem either, got it?}

{144}{}{You think I'm scared of you? The Molerats aren't what we used to be, but we're still a hell of a lot tougher than you.}
{145}{}{Maybe, but right now you'd better answer my questions.}
{146}{}{Think what you want, but I'll find a way to bring you to justice. Now get the fuck out of here.}
{147}{}{Maybe, maybe not. See you around, Eugene.}

{148}{}{How has the gang lasted this long?}
{149}{}{Huh? Why?}
{150}{}{Because I can help you guys. Seriously.}
{151}{}{Because you need to leave this gang behind and go straight.}
{152}{}{Because it will be the last day of your life.}
{153}{}{Think what you want. I have more questions.}

{154}{}{You? You think you're Molerat material? This isn't some fucking boy scout troop. How many people have you killed, huh?}
{155}{}{You're talking to the vilest raider on this side of the continent. Pay some fucking respect.}
{156}{}{More than everyone in this anthill of a village.}
{157}{}{"Cursed" is written on my face. And it's like this everywhere I go.}
{158}{}{I kill anyone and everyone, children included. You think your gang are hard as shit? If you've never heard the death rattle of a disemboweled toddler, you don't deserve to even talk to me.}
{159}{}{Forget it, let's talk about something else.}

{160}{}{[He pauses for a moment] You know, I think you just might be the real deal. Maybe there's something you can do for us, after all.}
{161}{}{Great. Let's hear it.}

{162}{}{Yeah, I've heard that before. From Milo, for example. Now look at him.}
{163}{}{Not very convincing, huh? Okay, let's talk about it...}
{164}{}{Fuck, you're right. After what happened to Milo... Shit, I don't know what to do. Maybe I should walk away. The gang's on the ropes anyway... }
{165}{}{Tell me what they're planning. I'll take care of everything.}

{166}{}{You'll have to hurry. They're going to ambush the caravan when it gets to the mountains. They'll kill everyone and take everything - it'll be like the whole caravan just disappeared. Here, take this radio and these frequencies. It's the only way you'll be able to find them.}
{167}{}{I'll keep this in mind.}

{168}{}{What, you can't wait to stick your nose into the gang?}
{169}{}{I heard what happened. Well... No going back now.}
{170}{}{Well well.}

#Female character
{1110}{}{Oh, look. An outsider from the wasteland now decides how our community should be run. You know what I think?}
{1129}{}{Bob told you? [he looks around anxiously before he leans in] Fine, newcomer, you got me. What now?}
{1130}{}{[He looks around anxiously before he leans in] Fine, newcomer, you got me. What now?}
{1154}{}{You? You think you're Molerat material? These aren't the fucking girl guides. How many people have you killed, huh?}
