{100}{}{You see the big biker Phil.}
{101}{}{You see Phil Pritchett, perhaps, the largest biker from the local gang.}

#Òàéìåðíûå ñöåíû
{102}{}{Hey! These bikers turned out to be a really cool guys!}
{103}{}{Wake up, mate! You slept for a long time.}
{104}{}{Don't piss me off!}
{105}{}{Did you see that?! Ha-ha-ha!}
{106}{}{Erm... How did you do that?}
{107}{}{What was that? Magic?!}

#ÍStarting conversation
{110}{}{[Doesn't pay any attention to you]}
{111}{}{[Examines the skull on your jumpsuit and grins]}
{112}{}{What's up, wanderer. Have a sit, let's talk!}
{113}{}{[Looks at your hands and laughs] What is it?}

#About ghost train
{120}{}{Maybe you have heard a train passing by?}
{121}{}{I did. Have seen it many times. But we were unable to catch up.}
{122}{}{Who could be driving it, what do you think?}
{123}{}{No one, of course. This is a ghost train. What, never heard of it?}
{124}{}{Nah. I didn't.}
{125}{}{So, I will tell you about it only once, so listen carefully. A couple of automatic trains were launched before the war, just for a test. To see how it will do. So they drove all over Nevada. And then pow! - something broke in automatic systems.}
{126}{}{And it crashed?}
{127}{}{No! These idiots from the railway stations tried to stop it, but all in vain. While they were trying, the war began. So, to this day it drives up and down the rails of Nevada.}
{128}{}{Hmm. Funny tale.}

#About archivarius's runaway daughter
{140}{}{Look, isn't that the chaser of runaway girls? You won't meet your kind of people often in the wasteland. Give yourself a medal, so everyone could instantly recognize you.}
{141}{}{You're upset that the girl left your company?}
{142}{}{Upset? Me? Ha! Maybe I should lock myself in the toilet and cry on top of that? No, I don't really care. It was fun with her, but on the other side... Anyway, you did an act of kindness and all that crap - returned a daughter to her father. I think that's admirable.}
{143}{}{Phew, then that means no hard feelings? Great. Let's talk about something else then.}

#Starting dialogue options
{150}{}{Can I buy some metal stuff from you?}
{151}{}{Guys, who are you anyway?}
{152}{}{About those repairs.}
{153}{}{Hey, guys! How about a beer? I have enough for everybody!}
{154}{}{I have to open those gates to the station. Can you help?}
{155}{}{[Leave him alone]}

#Who are you:
{160}{}{[They look at each other, exchanging laughs at your expense] Have you ever heard about bikers?}
{161}{}{Maybe I did. You're something like a gang right?}
{162}{}{Gang? Well, if you have the balls, you can call us a gang.}
{163}{}{What are you doing?}
{164}{}{Let me make it simple: everything concerning metal stuff is our specialty.}
{165}{}{Metal stuff?}
{166}{}{We ride around the wasteland collecting pre-war technology. If you need repairs or parts - just tell us, don't be shy! Though we have other means of income, this passion never faded over the years.}
{167}{}{Ah, I see.}

#Upgrades, main menu:
{170}{}{I'm listening.}
{171}{}{I want to improve my weapon.}
{172}{}{I need to repair this controller for the Nuka-Cola plant.}
{173}{}{I see you are doing great with machinery. Wanna take a look at my pickup?}
{174}{}{I have a serious proposition - need to repair the train control computer.}
{175}{}{}
{176}{}{Forget it, I changed my mind.}

{177}{}{Hey guys, look - free booze! Come, sit down and relax! We don't scare guys like you. [He hugs you by the shoulder and sits down next to you, the others also begin to gather around]}
{178}{}{[You drink for half a day, until everyone drop flat on their faces...]}

#Opening the station gates
{202}{}{[He seems to pay no attention to you]}
{203}{}{[He still doesn't pay any attention to you and continues to drink his beer]}
{204}{}{Hey pal, do you hear me?}
{205}{}{[Spits on the ground and takes another sip from the bottle]}
{206}{}{You ignore me?! Will you ignore my fist in your face?!}
{207}{}{I got it. What do you want in return?}
{208}{}{That's it! I had enough of you! Open the gates or I'll...}
{209}{}{[Grins and laughs] Aren't you the fast one, huh? I can do it. But what can you offer me for that?}
{210}{}{Open the gates!}
{211}{}{I'll come back later.}
{212}{}{Hey, look, another smart-ass wants to pass! Gates, you say? Easy! Not even moving from where I stand.}
{213}{}{Not moving? Bullshit!}
{214}{}{You don't think I'll do it? Word of a biker - let my balls be cut if I won't open the gates from where I'm standing.}
{215}{}{Wait, you're up to something...}
{216}{}{It's simple. I'm actually not so sure myself, so - wanna bet?}
{217}{}{No way! Just open the gate.}
{218}{}{No problem, I'll do it. Look and be amazed!}
{219}{}{Yeah right, who would believe, that you can open them from a distance... Well, let's see.}
{220}{}{Wait, I need to concentrate...}
{221}{}{Uh-huh...}

#Cutscene of gates opening
{222}{}{*he struggles so hard that turns red*}
{223}{}{URRRRGGHH!!!}
{224}{}{What! He did it!}
{225}{}{Yeah! Did you see that, fellas!?}
{226}{}{I can't believe it...}
{227}{}{Ha-ha-ha!}

#Upgrading guns and stuff
{230}{}{Let me see your toy.}
{231}{}{Can you reinforce my leather armor?}
{232}{}{Here is a worn metal armor. Can you restore it?}
{233}{}{}
{234}{}{I changed my mind. Not needed.}
{235}{}{I don't have so much money...}
{236}{}{Easy-peasy. I'll do it for }
{237}{}{ bucks.}
{238}{}{Fine. Here's the money. I'm waiting...}
{239}{}{[After a couple of hours biker brings you improved brahmin skin armor with metal fortifications. He's really good!]}
{240}{}{[A few hours later biker brings you shiny and reinforced metal armor. It looks like just off the assembly line!]}
{241}{}{Now that's what I'm talking about!}

{242}{}{Hey! I'm not going to pick your shit!}
{243}{}{It fell by accident, I'll pick it up...}

{244}{}{What? Show me it.}
{245}{}{Rifle.}
{246}{}{Pistol.}
{247}{}{Another weapon.}
{248}{}{Back.}
{249}{}{What else ya got?}

{250}{}{Do you have a scope for hunting rifle?}
{251}{}{Can you increase the power of the plasma rifle?}
{252}{}{Make a sawed-off of this shotgun.}
{253}{}{I want to decrease energy consumption on the laser rifle.}
{254}{}{Hey, now that's more like it! Just my kind of work. Okay. I will make a discount - just because I'm enjoying this. For }
{255}{}{Wow! Where did you get that beauty? Fuck me demon, if I don't make a masterpiece out of it! For }
{256}{}{Assault rifle, what can you do with it?}
{257}{}{I can expand the mag. For }
{258}{}{}
{259}{}{[An hour later the biker brings you the weapon. Nothing to complain about. It looks like perfect work!]}

{260}{}{Laser pistol - what do you think, what can be done?}
{261}{}{Can you make this brutal "Desert eagle" more brutal?}
{262}{}{Here's a plasma pistol. What do you say?}
{263}{}{Can you increase the loading speed of Magnum?}
{264}{}{Hmm. Nice toy. Yeah. I have a few ideas how to make it more flashy. For }

{270}{}{I have a dynamite. Can you make dynamite sticks out of it?}
{271}{}{Can you make Molotov cocktail?}
{272}{}{I'm thinking about what to make out of this brahmin poke-stick...}
{273}{}{This power fist is kinda weak, I can beat a man to death with my bare fists faster...}
{274}{}{Easier than slidin' a pair of panties off. I'll do it for }
{275}{}{}
{276}{}{What about the standard flamethrower?}

#Hitching a ride
{280}{}{Tell me, what's the closest civilized city nearby?}
{281}{}{Civilized? The fuck you'll find *civilized*.}
{282}{}{You know what I mean.}
{283}{}{Fine, give me that map of yours, I'll show. Here is New Reno. Great place, just how we like it - anarchy, freedom and independence. Sometimes we come there to hang out at the casino. Here lies Salt Lake - a boring city. But still peaceful. More or less. And here is the best part - Las Vegas. Perhaps, the main spot in Nevada. Although, it's far.}
{284}{}{Right. Thanks for the info.}
{285}{}{You have transport. Can you give me a ride to the city?}
{286}{}{Right now?}
{287}{}{I need to get to New Reno. [700$]}
{288}{}{No, later. I'll tell, when.}
{289}{}{I need to get to Salt Lake. [700$]}
{290}{}{I need to get to Lovelock. [400$]}
{291}{}{I need to get to Wendover. [400$]}
{292}{}{Someone doesn't have enough bucks. So, I'm too tired to drive there. Got it?}
{293}{}{Okay.}

#About surroundings
{294}{}{And what is this place around?}
{295}{}{Military radar station. To the south you'll find the ruins of pre-war settlement and around them there are mountains and desert. If you wish to wander on the outskirts, don't forget to grab a thick stick, or better yet, something that kicks with electric charge.}
{296}{}{Why?}
{297}{}{There is a lot of wild dogs in the ruins. they usually stay away - afraid of us. But outsiders like you will be stripped to the bone.}
{298}{}{About something with "electric charge" - what is that for?}
{299}{}{In the mountains, to the north-east from here, you can run into some flying robots. We were unable to find out where they come from or what's their purpose. But we know for sure that they kill all humanoid creatures they meet. You have been warned.}

#Train repairing
{300}{}{[Heavy breathing, he studies the computer, turning it around] Like shooting fish in a barrel. I bet it lacks a capacitor and one chip. It can be restored, easy.}
{301}{}{How much for you work?}
{302}{}{1500. I would take more, but you're cool, so I will make a discount.}
{303}{}{Great, I'm fine with the price. Here is the payment, waiting for results.}
{304}{}{What's this, money? Pfft... But what else could you offer? Fine. Give me 3000, and I'll try to fix it.}
{305}{}{Harsh prices, but I need it. I'm waiting for results.}
{306}{}{I'll think about your proposition.}

{307}{}{You found a way to repair the train.}

#PLC
{310}{}{So little and so annoying. But I'll manage. What can you give in return? Ah, you have nothing to give, besides money. Okay. Here is my price - 1000 bucks.}
{311}{}{Here is the device and the money.}
{312}{}{No need.}
{313}{}{Biker skillfully did his favorite job. All that's left is to take the unit back to the factory.}

#Pickup 
{320}{}{Wow, for a baby like that I'll pay you myself!}
{321}{}{Erm... I need that car.}
{322}{}{Hey, no problem. We love driving bikes more than shaking around in a stuffy car anyway.}
{323}{}{Good then. So what about an upgrade? Would you look at what can be done?}
{324}{}{Well, let's see...}
{325}{}{Okay.}
{326}{}{Yes, I have few ideas. Do you know why the acceleration and speed is so lame? Because the contacts are weak, lots of junk between the parts, oil is dried up to nothing... In addition, I could put in some special stuff. The thing will fly!}
{327}{}{Good. And how much do you want for this overhaul?}

{328}{}{Two grands. Just for fun. Really. But it will take a couple of days, I'm telling you.}
{329}{}{Fine, I'll wait. Here is 2000$.}
{330}{}{No, that's too much and too long. Perhaps later.}

{331}{}{Hey, bro, wake up!}
{332}{}{Huh!? What!? Where!?..}
{333}{}{Don't sweat it! Your car is fucked.}
{334}{}{WHAT?!!}
{335}{}{That's it, I'm telling you, it's done for. Raiders, that scum, rolled in, while a was taking a piss.}
{336}{}{NO! NO FUCKING WAY!!!}
{337}{}{So, your car has been stolen. You should've kept an eye out.}
{338}{}{WHAT THE ACTUAL FUCK!!!}
{339}{}{Ha-ha-ha!!!}
{340}{}{Why the fuck are you laughing!? Don't you understand - it's the most valuable thing I had!}
{341}{}{Hahah! [wipes his tears] You're really funny, you know!}
{342}{}{What?.. Uh... Was that, like, a joke?}
{343}{}{There's your car, standing right where it should be. Everything is normal. I'm saying - I finished my work, you know? Everything is fine, the engine is a beast, acceleration - just awesome!}
{344}{}{Grhmm... This your biker humor...}
{345}{}{Don't be a wuss! If you need anything else - stop by, we'll help.}
{346}{}{Yeah... Maybe. Take care.}

{347}{}{Biker improved the pickup's engine systems. Now the car will go much faster than before.}

#Alien blaster
{400}{}{This blaster won't shoot...}
{401}{}{Indeed... It seems that inside has been triggered some kind of safety system, installed by the previous owner. Judging by the marks of a screwdriver, someone tried to remove it. Hmm... Give me some time, perhaps, I can figure out how to fix that. But I'll need some money for a beer... Just 3000 bucks.}
{402}{}{This is too much!}
{403}{}{Leave it for now, look at the other weapon I have.}
{404}{}{Believe me, such technology is hard to come by. Can you see the mark of Area 51? Only God knows, what was going on there, but I can tell you for sure - it's worth it.}
{405}{}{Okay, deal.}
{406}{}{Great. So, as I said, I'll take the job only for 3000 bucks.}
{407}{}{Take everything, you need!}
{408}{}{Not now.}
{409}{}{No, no deal.}
{410}{}{Whatever, I will figure it out on my own!}
{411}{}{Uh, I will have to look.}
{412}{}{Oh, yes! This baby girl deserves a good owner. Treasure it, there won't be another. Still, I don't know, where you can get the "batteries" for it. If I were you, I would look where it came from - in Area 51.}
{413}{}{Thanks.}

#Station gates - additional dialogue
{420}{}{I can pay.}

{421}{}{[Disappointed] Money... I don't like money. Turn out your pockets - do you have any drugs? I would appreciate some psycho. A stimpak is fine too.}
{422}{}{Stimpak.}
{423}{}{Mentats.}
{424}{}{Buffout.}
{425}{}{Psycho.}
{426}{}{Anti-smoker.}
{427}{}{Painkiller.}
{428}{}{}
{429}{}{Nothing...}

{430}{}{[Only shrugs in response and turns away]}
{431}{}{[Takes the dose, examines it, smells it and puts in his pocket] Not bad.}
{432}{}{Hey, we had a deal - open the door!}

#Power armor info
{450}{}{Tell me about your armor. I'm very interested.}

{451}{}{You're interested? Really? The old tech is the topic I can talk about for hours. But to do that I need something to keep my throat wet, you know?}
{452}{}{Here's a beer, go ahead!}
{453}{}{Ah, right. When I find some beverage, I'll come back.}
{454}{}{Then some other time, if you still be interested.}

{455}{}{I already told you. Bad memory?}
{456}{}{I just need to clarify something.}
{457}{}{That's another story. But what do you want to know?}
{458}{}{Fine. What do you want to know?}

{459}{}{Where did you get this armor?}
{460}{}{What kind of armor is it?}
{461}{}{Would you sell it or trade it for something?}
{462}{}{Could you make one like this?}

{463}{}{If I tell you, I'll have to kill you. Ha-ha, kidding. Actually, this story is really not for your ears.}
{464}{}{That is all I wanted to know.}
{465}{}{Power armor T-51b, pre-war build. But I'm not as lucky as it seems. Some parts of it aren't working, although it fulfills all its basic functions - protects me from bullets, radiation, and also boosts my strength. There is a microfusion cell inside, powering the module that increases the strength of my every move. For your information - Americans would win shit in Anchorage, if not for T-51.}
{466}{}{No way. This armor became my second skin. You can remove it only off my dead body, so that's not gonna happen soon. But if there ever should appear such an idiot, who's capable of killing me, know this - it's impossible to strip the armor intact. In order to take it off its dead owner, you have to, for a start, seriously damage the external plating.}
{467}{}{You think I'll pull out a soldering iron and easily make what the Americans have been developing for years? Before the war, hundreds of specialists worked on it with the help of their precise tech, and all I have is my guys here - right one to punch faces and left one to hold the steering, while the right one is doing his job. Although, I would gladly started the mass production - I even found some of the original blueprints - but in current conditions it is just impossible.}
{468}{}{Wait, blueprints?! You have them?! Why didn't you say so from the start!}
{469}{}{You really need it? Hmm. You proved yourself well with these prematures in Reno and deserve our respect. So be it - I will share them with you. You're good kid.}
{470}{}{Damn right!}
{471}{}{You have acquired a power armor blueprints.}
{472}{}{You really need it? Hmm. I don't think I want to share something with you.}
{473}{}{I can buy it.}
{474}{}{I can work for it.}
{475}{}{That's more like it. Solve the problem in Reno and the stuff is yours.}
{476}{}{Maybe, you can just sell them to me?}
{477}{}{Oh, that...}
{478}{}{You seem like a capable fella, if you managed to get here and question me. There is one job, for which I'm willing to pay.}
{479}{}{Tell me more.}
{480}{}{[Scratches his chin, thinking] Forget it. We don't like money.}
{481}{}{Maybe I can work for it then?}
{482}{}{I'm ready to pay. Here's 5000.}
{483}{}{This is too expensive. So, no, for now.}
{484}{}{When some scoundrel tries to screw me over, I usually get really angry. And believe me - it always ends bad... For him.}
{485}{}{...}

#############################################################################
#
#        Quest - set up for bikers
#
#############################################################################

#Quest obtaining - NOT USED, except couple of lines
{500}{}{Î âàñ íå ÷àñ'î óñëûøèøü â Íåâàäå...}
{501}{}{Ïîæàëóé, ìíå ý'î íå èí'åðåñíî. Èçâèíè è - ïîêà.}
{502}{}{Ý'î âåðíî. Òî, ÷'î ïðîèñõîäè' âíó'ðè áàíäû, îñ'àå'ñÿ âíó'ðè áàíäû. Ìû äîñ'à'î÷íî ñàìîñ'îÿ'åëüíû, ÷'îáû íå âìåøèâà'üñÿ â ìåñ'íûå ðàçáîðêè â ãîðîäàõ è ïîñåëåíèÿõ. È êîå-ê'î ý'èì ïîëüçóå'ñÿ.}
{503}{}{Î ÷åì 'û?}
{504}{}{Îáû÷íî ïîñëå íàñ îñ'àþ'ñÿ 'îëüêî ôååðè÷åñêèå ðàññêàçû î õìåëüíûõ äðàêàõ, íî ïîñëåäíåå âðåìÿ çëûå ÿçûêè øåï÷ó' ïëîõèå íîâîñ'è.}
{505}{}{×'î 'û èìååøü â âèäó?}
{506}{}{Ê'î-'î ïîð'è' íàøó ðåïó'àöèþ â ø'à'å, ñîçäàâàÿ ïðîáëåìû â ïîñåëåíèÿõ è ãîðîäàõ íà çàïàäå. Ìû, êîíå÷íî, 'îæå íå ïðî÷ü íàøàëè'ü, íî 'î, ÷åì çàíèìàþ'ñÿ ý'è óáëþäêè ïîä íàøèì èìåíåì, ãðàíè÷è' ñ ðàçáîåì. À áàéêåðû Íåâàäû - íå ðàçáîéíèêè.}
{507}{}{Ìîæå', ÿ ñìîãó ïîìî÷ü?}
{508}{}{Õì, ý'î íåïëîõàÿ èäåÿ. Òîãäà ðàñêèíü óøè ïîøèðå è ñëóøàé, âåäü ÿ ïëà÷ó çà ðàáî'ó.}
{509}{}{Îê, ÷'î ìíå íóæíî ñäåëà'ü?}
{510}{}{Íå õî÷ó ñâÿçûâà'üñÿ ñ 'àêèìè îïàñíûìè ëþäüìè. Òàê ÷'î - áåç ìåíÿ.}

{511}{}{Íóæíî íàé'è è íàêàçà'ü ý'èõ óáëþäêîâ. Êàê èìåííî - ìíå âñå ðàâíî. À â çíàê 'îãî, ÷'î äåëî ñäåëàíî, ïðèíåñè êóð'êè, êî'îðûìè îíè ñ'ðàùàþ' íàñåëåíèå. Íèê'î, êðîìå íàñ, íå ìîæå' èõ íîñè'ü. Ê 'îìó æå, îíè áûëè ñíÿ'û ñ 'åë óáè'ûõ áàéêåðîâ, ÷'î äëÿ íàñ íå ìåíåå âàæíî.}
{512}{}{ß â äåëå.}
{513}{}{Î'ëè÷íî. Æäó âåñ'åé. Åñëè õî÷åøü, ÿ î'âåçó 'åáÿ â Ðèíî è âûñàæó íà îêðàèíå, ÷'îáû ñàìîìó íå ñïàëè'üñÿ. Ìû íå ìîæåì íàé'è ãàäîâ, 'àê êàê ê'î-'î ïðåäóïðåæäàå' èõ î íàøåì ïðèáëèæåíèè ïî ðàöèè. Îíè âñåãäà óñïåâàþ' ñêðû'üñÿ.}
{514}{}{Let's go!}
{515}{}{Thanks, but not now. I'll go on my own.}

{516}{}{À ìíå êàçàëîñü, âû è åñ'ü ðàçáîéíèêè.}
{517}{}{Êîãäà íàäî, ìû âûïóñ'èì êèøêè ëþáîìó ñóêèíó ñûíó. Íî ìû íå äåëàåì ý'îãî íè ðàäè åäû, íè ðàäè óäîâîëüñ'âèÿ.}
{518}{}{Yeah. So?}
{519}{}{}

#Quest done - NOT USED, OLD
{520}{}{Ïî ïîâîäó çàäàíèÿ.}
{521}{}{×'î, âñå åùå 'óïèøü?}
{522}{}{Íå', óìíèê, äåëî ñäåëàíî - êóð'êè ïðè ìíå.}
{523}{}{Ïî÷åìó âû íå ìîæå'å ñïðàâè'üñÿ ñ óáëþäêàìè ñàìè?}
{524}{}{}
{525}{}{You promised to give me a ride to Reno...}
{526}{}{Ïî÷'è... Ëàäíî, ïðîåõàëè.}
{527}{}{Ðàäè 'àêîãî äåëà - î'âåçó, íå âîïðîñ. Âûäâèãàåìñÿ ñåé÷àñ?}
{528}{}{Äà.}
{529}{}{Íå', ïîäîæäè.}
{530}{}{Ìû íå ìîæåì ïîäæèäà'ü âîçëå Ðèíî öåëûå ñó'êè, âåäü íèê'î íå çíàå', êîãäà è ãäå ý'è ãàäû ïîÿâÿ'ñÿ âíîâü. Äî íàñ 'àêæå äîõîäèëè ñëóõè î' áàðìåíîâ, ÷'î ê'î-'î ïðåäóïðåæäàå' óáëþäêîâ ïî ðàöèè î íàøåì ïðèáëèæåíèè. Îíè âñåãäà óñïåâàþ' ñêðû'üñÿ. Òû æå íå ïîõîæ íà îäíîãî èç íàñ, à ïî'îìó 'åáå ïðîùå çàñ'à'ü èõ âðàñïëîõ.}
{531}{}{Ïîíÿ'íî.}
{532}{}{Î'ëè÷íàÿ ðàáî'à. Òû íàì îêàçàë áîëüøóþ óñëóãó. Î íàñ è 'àê â Íåâàäå íå ëó÷øåãî ìíåíèÿ, à êîãäà ý'è ïîäîíêè ñ'àëè áóéñ'âîâà'ü î' íàøåãî èìåíè... 'àêîãî íå ïðîùàþ'. Íàäåþñü, îíè ïîëó÷èëè ïî ïîëíîé ïðîãðàììå?}
{533}{}{Ý, äà, ÿ ñäåëàë 'àê, êàê áûëî íóæíî.}
{534}{}{Î'ëè÷íî. Âî' 'âîÿ îïëà'à. Äóìàþ, 'åïåðü íàì ñ 'îáîé íóæíî âèäå'üñÿ ÷àùå - 'û íàì íðàâèøüñÿ.}
{535}{}{Ïðîíèêñÿ íàêîíåö óâàæåíèåì? Òî-'î æå.}
{536}{}{Ïîñ'îé. Î 'åáå ãîâîðÿ' ìíîãî õîðîøåãî. ß çíàþ, êàê ý'î 'ðóäíî - ïû'à'üñÿ âñåãäà áû'ü ÷åñ'íûì è ïðàâèëüíûì. Ó ìåíÿ âî' íå ïîëó÷àå'ñÿ, à 'û... (äîñ'àå' ðåâîëüâåð) Âîçüìè. Òåáå íàäî áû'ü âñåãäà çàùèùåííûì î' ïîäîíêîâ.}
{537}{}{À âî' çà ý'î ñïàñèáî!}

{538}{}{Êàê 'û äóìàåøü, ê'î ý'è ëþäè, êî'îðûå âàñ ïîäñ'àâëÿþ'?}
{539}{}{Íàâåðíÿêà ìåñ'íûå óëè÷íûå õóëèãàíû â Íüþ-Ðèíî. Ñàìîçâàíöû, ïî'åðÿâøèå èíñ'èíê' ñàìîñîõðàíåíèÿ. Âïðî÷åì, è âðàãîâ ó íàñ íå ìàëî. Òàê ÷'î ý'î ìîæå' áû'ü ê'î óãîäíî.}

#quest: stagecoach robbery - NOT USED 
{540}{}{Òû ñëûøàë ÷'î-íèáóäü îá îãðàáëåíèè äèëèæàíñà âîçëå Áëýê-Ðîê?}
{541}{}{Ìåñ'íûå ÷'î-'î ãîâîðèëè, íî ìíå ý'î íåèí'åðåñíî. Íàâåðíÿêà ý'î áûëè ðåéäåðû.}
{542}{}{Íåêî'îðûå ñ÷è'àþ', ÷'î ý'î ñäåëàëè áàéêåðû.}
{543}{}{Âî' êàê? Íå âåðü çëûì ÿçûêàì. Òû äàæå íå ïðåäñ'àâëÿåøü, ñêîëüêî íåäîáðîæåëà'åëåé è çàâèñ'íèêîâ âîçíèêëî âîêðóã íàøåé áàíäû. Íî ìû íå áàíäè'û è äèëèæàíñû íå ãðàáèì. Ìû çäåñü íå ïðè ÷åì.}
{544}{}{Ëàäíî.}

#The first quest of Phil - the Reno investigation
{550}{}{One does not hear much about you guys in Nevada...}
{551}{}{}
{552}{}{That's right. Everything that happens in the gang stays within the gang. We are self-sufficient enough to not get involved in the local conflicts of cities and settlements. And apparently someone is taking advantage of that.}
{553}{}{What are you talking about?}
{554}{}{It's weird. Suddenly, all the caravan merchants in the region around New Reno started avoiding us. We used to be on good terms, and now they're very suspicious, holding their guns tight every time they see us, like they are afraid of something. I would look into it myself, but no one wants to even talk to us. But they would talk to you.}
{555}{}{What do I need to do?}
{556}{}{For a start - find out how our reputation got so bad, what is being said about us and who spreads those rumors. Any info is important.}
{557}{}{Sounds simple. I'll take the job.}
{558}{}{I don't think I'm interested. Sorry and goodbye.}
{559}{}{Great. Come back when you learn something. If you want, I can drive you to Reno and leave you at the outskirts so I don't draw attention to myself.}

{560}{}{About the job.}
{561}{}{What's happening, damn it?}
{562}{}{The rumor is that you attacked the stagecoach and robbed it. It happened near Black Rock.}
{563}{}{Erm, I'm still looking into it.}
{564}{}{Then don't waste time.}
{565}{}{Fine.}
{566}{}{Us? Robbed a stagecoach?! Bullshit! Who told you that?}
{567}{}{The "Nevada Express" employees told me that themselves.}

{568}{}{Hmm. I don't know why they would think that. We have to look into this, investigate deeper. Will you do this for us?}
{569}{}{Already done. I've been to the site and found some clues - this DVR log from the robot.}
{570}{}{I've been to the site and found some clues - this DVR log from the robot.}
{571}{}{I'm still working on that.}
{572}{}{Why should we believe that?}
{573}{}{Good question. Why should we trust you? Fine, if you don't want to help - we'll handle it out ourselves...without you.}
{574}{}{I'll think about it.}
{575}{}{Fine, I'll look into your problem. Wait for news.}
{576}{}{You promised to take me to Reno...}

{580}{}{Is this what's needed?}
{581}{}{Although I can't decipher the data on it...}
{582}{}{Yes, I already deciphered the data from it.}

{583}{}{You can't? Ha, of course you can't, baby! This job is for people with big smart brains. Let a real professional handle that, don't waste your time.}
{584}{}{[Wait]}
{585}{}{Wait, I better try this myself. The experience won't hurt.}
{586}{}{So, the bird is singing a new tune...}
{587}{}{What are you talking about?}
{588}{}{The guys who configured the robot were no idiots. They set it to watch not just the perimeter, but also the whole crew. Those bastards robbed their own stagecoach and didn't even know they were being recorded. Hey, this will be enough not only to clear our name, but to also damage the credibility of the "Nevada Express", don't you think?}
{589}{}{They deserve it! They'll think twice next time.}
{590}{}{Only two assholes are guilty, it's not fair to ruin everyone else's reputation with this.}
{591}{}{Tuco will not be happy to hear this news, but they will stop treating us with hatred. And if we just dealt with it silently, people still wouldn't trust us. Our interest is obvious.}
{592}{}{Right. I'll see what can be done.}
{593}{}{We are counting on you.}
{594}{}{Bye.}
{595}{}{}

{596}{}{Your problem in Reno has been solved. Now everyone thinks the attack was carried out by unknown raiders, and you were accused by mistake.}
{597}{}{I'm afraid that your problem cannot be solved. Those bastards from "Nevada Express" took the evidence.}
{598}{}{Your problem is settled in Reno. Tuco looked at the evidence and made a public statement. Now everyone knows the attack was carried out by some of their own.}
{599}{}{Great job! Just what we need. I'd never thought of throwing fake clues at them, and you... You're clever.}
{600}{}{Thanks.}
{601}{}{Okay, don't just stand there. I remember about the reward. Here, take it [gives you laser pistol]. It's yours.}
{602}{}{Not bad.}
{603}{}{Good job! Of course, it's a shame the company's rep is damaged because of two idiots, but why should we care, right?}
{604}{}{Yeah.}
{605}{}{Damn, these assholes still won't calm down?! I had enough! If they think that rep is more important, let them choke on it, when I draw my plasma gun upon meeting them!}
{606}{}{Whoa, it's not that bad...}
{607}{}{Sure - for *us* it's not that bad... Fine, let's deal with you first. I remember about the reward. But you were not so useful as I had hoped. How much for your service? I think, 200 is enough. And that's it.}
{608}{}{At least something.}

#Female character
{1103}{}{Wake up, sis! You slept for a long time.}
{1112}{}{What's up, wanderer. Have a sit, let's talk!}
{1123}{}{No one of course. This is a ghost train. What, never heard of it?}
{1140}{}{Look, isn't that the chaser of runaway girls? You won't meet your kind of people often in the wasteland. Give yourself a medal, so everyone could instantly recognize you.}
{1142}{}{Upset? Me? Ha! Maybe I should lock myself in the toilet and cry on top of that? No, I don't really care. It was fun with her, but on the other side... Anyway, you did the act of goodness and all that crap - returned the daughter to her father. I think, it's admirable.}
{1160}{}{[They look at each other, exchanging laughs about you] Have you ever heard about bikers?}
{1161}{}{Maybe I did. You're something like a gang right?}
{1176}{}{Forget it, I changed my mind.}
{1207}{}{I got it. What do you want in return?}
{1234}{}{I changed my mind. Not needed.}
{1321}{}{Erm... I need that car.}
{1331}{}{Hey, sis, wake up!}
{1341}{}{Hahah! [wipes his tears] You're really funny, you know!}
{1405}{}{Okay, deal.}
{1469}{}{You really need it? Hmm. You proved yourself well with these prematures in Reno and deserve our respect. So be it - I will share them with you. You're good gal.}
{1478}{}{You seem like a capable gal, if you managed to get here and question me. There is one job, for which I'm willing to pay.}
{1530}{}{Ìû íå ìîæåì ïîäæèäà'ü âîçëå Ðèíî öåëûå ñó'êè, âåäü íèê'î íå çíàå', êîãäà è ãäå ý'è ãàäû ïîÿâÿ'ñÿ âíîâü. Äî íàñ 'àêæå äîõîäèëè ñëóõè î' áàðìåíîâ, ÷'î ê'î-'î ïðåäóïðåæäàå' óáëþäêîâ ïî ðàöèè î íàøåì ïðèáëèæåíèè. Îíè âñåãäà óñïåâàþ' ñêðû'üñÿ. Òû æå íå ïîõîæà íà îäíîãî èç íàñ, à ïî'îìó 'åáå ïðîùå çàñ'à'ü èõ âðàñïëîõ.}
{1532}{}{Î'ëè÷íàÿ ðàáî'à. Òû íàì îêàçàëà áîëüøóþ óñëóãó. Î íàñ è 'àê â Íåâàäå íå ëó÷øåãî ìíåíèÿ, à êîãäà ý'è ïîäîíêè ñ'àëè áóéñ'âîâà'ü î' íàøåãî èìåíè... 'àêîãî íå ïðîùàþ'. Íàäåþñü, îíè ïîëó÷èëè ïî ïîëíîé ïðîãðàììå?}
{1533}{}{Ý, äà, ÿ ñäåëàëà 'àê, êàê áûëî íóæíî.}
{1563}{}{Erm, I'm still looking into it.}
{1582}{}{Yes, I already have the data from it.}
