{100}{}{You see Jasmine.}
{101}{}{You see a girl wearing a red scarf on her neck.}
{102}{}{Thanks for the cash. First chance I get, I'm out of here.}
{103}{}{I don't feel good... }

#Starting converstaion
{109}{}{. And yours?}
{110}{}{[You see a girl with beautiful hair and a red scarf around her neck. As soon as she makes eye contact with you, she gives a flirty smile.] Well, hello, handsome. New in town? I'd do *anything* for some conversation around here. Are you just passing by, or are you here to stay?}
{111}{}{Nice to meet you. My name is }
{112}{}{Who are you?}
{113}{}{Can't you converse with the people here?}
{114}{}{Isn't it hot in that scarf?}

{115}{}{Baby? Why'd you call me "baby"?}
{116}{}{Why am I "baby"?}
{117}{}{Don't worry, baby. It's just 'cuz I like you.}

{120}{}{What a nice name! I'm Jasmine. Good to meet you.}
{121}{}{Hmm, how do I say this... I used to work in the fields, now I'm resting. Is that good enough, baby?}
{122}{}{[She crosses her arms and scowls] Hmph! It's no good talking to the people here. Don't ask, baby, I have my reasons.}

{123}{}{Oh, my! [she smiles slyly, then begins to unbutton her shirt] I can take it all off if you want, baby.}
{124}{}{Uh... Why?}
{125}{}{Really? You'd do that?}
{126}{}{[She laughs] Are you serious? You really don't know? [she puts a finger under your chin and winks] Don't worry, baby. I'm a great teacher.}
{127}{}{[She places her hand on your shoulder] Baby, I'll do a lot more than that. Just put your hand here... }
{128}{}{Woah! What's that under your scarf?!}
{129}{}{[The flirty expression drops off her face and she pushes you away, turning her back on you] Every fuckin' time! It starts good, but you get one look and... [she sighs] Just... Go.}
{130}{}{Jasmine?}

#Second dialogue
{150}{}{[She gives you a dead, silent stare, waiting for you to leave.]}
{151}{}{[Leave silently]}

{152}{}{Can I ask you few questions about Black Rock?}
{153}{}{[She frowns] You think I know anything? Go ask at the bar, they never shut up. They won't even let me inside.}
{154}{}{Bye.}

{155}{}{How did you end up here?}
{156}{}{Daddy - my real Daddy - made me leave Reno. He thought he could save me from my life there. Then he got eaten by a pack of geckos, and now I'm gonna starve to death all alone. Ain't that ironic?}
{157}{}{What where you doing there?}
{158}{}{Oh my god, you really don't get it? I'm a whore, a cheap fucking whore! Any motherfucker could have me for fifty bucks, and that's before my pimp's cut.}
{159}{}{I'm sorry. I didn't mean to upset you.}
{160}{}{Let's talk about something else.}
{161}{}{About what?}
{162}{}{Work is work. That doesn't bother me.}
{163}{}{So... What's a "whore"?}
{164}{}{[She stares at you with wide eyes] Are you fuckin' with me? Oh my god, I think you're really serious. Holy shit... A virgin, at your age.}
{165}{}{What?}
{166}{}{If I weren't sick, baby, I'd show you... For fifty bucks. But right now, no one should touch me.}

{170}{}{Jasmine, what's happening to your skin?}
{171}{}{[She sighs] You really wanna know? I've got this horrible shit on my skin - just a few places right now, but nobody knows what'll happen next. People stared and talked behind my back... I gotta wear this scarf so they don't see.}
{172}{}{May I see?}
{173}{}{Wow, I think I'm going to be sick. I better go.}
{174}{}{[She hesitates, then silently unwraps the scarf. On the side of her neck you see a large mound of swollen and painful-looking blisters.]}
{175}{}{This is definitely an infection, probably sexually transmitted. I think it can be cured, but you'll need antibacterial medication.}
{176}{}{Really? I thought it'd just get worse and worse my whole life! But I can't buy any medicine. Even if I had the money, where the hell would I get it?}
{177}{}{You earned 100 experience point for making the right diagnosis.}
{178}{}{That's pretty nasty. Do you know what it is?}
{179}{}{[She shrugs sadly] No, except that it's bad.}
{180}{}{From me. [give her a bottle of Blood-purifier]}
{181}{}{Where did you get this?}
{182}{}{Probably some junkie in Reno, or another one of the girls. You couldn't even imagine the types I had to sleep with... }
{183}{}{You've known other people with this?}
{184}{}{Yeah. Something like every tenth whore in Reno's got it. No one lives for long with it - usually they take poison and die, so it's quicker.}
{185}{}{If I'm ever in Reno, I'll remember that. Take care.}

{186}{}{I'll get you the medicine, don't worry.}
{187}{}{}
{188}{}{}
{189}{}{I'll try to find you the cure.}
{190}{}{I know this is unpleasant, but we have to talk about your skin.}

{191}{}{Haven't you tried going to a doctor?}
{192}{}{Show me your skin condition.}
{193}{}{You see any fuckin' doctors around here? Even in Reno you gotta keep buying anaesthetic from chem dealers to keep it from getting too bad. I think Jed, the old man that lives next to Justin, told me they managed to cure it in Reno a long time ago with some kinda plant, but that's it. I don't even know if it's true.}
{194}{}{No shit? You're really gonna help me? [she smiles] Thank you! I didn't think anyone even cared! Try talking to Jed - he said he knew of some medicine made out of a plant or something, but he didn't remember how to make it. Maybe you can get something more out of him.}
{195}{}{Fine.}

#Let's talk about your cure
{200}{}{Let's talk about your cure.}
{201}{}{Yeah?}
{202}{}{I have this medicine for you. [give her the flask of Blood-purifier]}
{203}{}{I have this medicine for you. [give her the flask of poison]}
{204}{}{Sorry, nothing yet.}

{205}{}{Oh my god! Thank you, thank you, thank you! [she grabs the medicine] I didn't think there were actually people like you in the world! You're my guardian fuckin' angel, you gave me my life back! I swear, I'll never fuck anyone for money again!}
{206}{}{I hope it helps.}
{207}{}{Make sure you drink it all.}
{208}{}{One way or another, you removed the infection from the community.}
{209}{}{Thanks to you, Jasmine is on the road to recovery.}
{210}{}{What do you think could heal you?}
{211}{}{[She shrugs helplessly] How the fuck should I know? Old man Jed might know something - he told me there was this plant that could cure it, but he doesn't remember anything else.}

#Banish her
{220}{}{Someone told me they don't want your infection in this town. Nothing personal, Jasmine.}
{221}{}{[She sighs] So they finally decided? God dammit, I knew this would happen. But I hoped they'd at least come here themselves so I could spit in their faces.}
{222}{}{You'll have to move somewhere else. For your own sake.}
{223}{}{I'm not here to talk. Get out now, or die!}
{224}{}{We'll discuss this later.}
{225}{}{You think I don't belong here? You're probably right... But the caravan said I'd have to pay a hundred bucks to go with them! I don't have any money!}
{226}{}{Here's a hundred dollars.}
{227}{}{[She looks stunned] You're... You're serious? I didn't think anyone would pay to get rid of me. Okay, I understand. I promise I'll go with the next caravan.}
{228}{}{You'd better. I'll be watching.}
{229}{}{}

{230}{}{But - but I can't!}
{231}{}{I warned you. [attack]}
{232}{}{And why not?}
{233}{}{You can stay for now, but we will talk about this later.}
{234}{}{I have no money for a caravan! No one will help me, and I can't even sell myself! I can't even go back to Reno, Daddy sold our house! I'll be left in the street!}
{235}{}{No, you'll be in the ground. [attack]}
{236}{}{Yeah, that's really sad. But the locals don't want you here anymore. You have to leave.}

#After curing her
{250}{}{My guardian angel!}
{251}{}{How do you feel?}
{252}{}{Let's talk about your sickness again. How did you get infected?}
{253}{}{Where else? Reno. Every whore there got some kind of disease. It's just one of the million ways the big city tries to kill you.}
{254}{}{Great! There are still marks on my skin, but I feel strong and healthy. And it's all because of you!}
{255}{}{Rest now.}

{260}{}{Now that you're cured, will you be alright in this town?}
{261}{}{Well... [she sighs] I'm... Lonely. No one's gonna try to make me leave or kill me now, but everyone still knows what I did in Reno. I've... I've always wanted a family, but... [she shakes her head] Never gonna happen.}
{262}{}{No one here will make a family with you?}
{263}{}{Who would want me? No normal guy is going to want some used-up whore.}
{264}{}{Does he have to be normal? How about Gravedigger Bob?}
{265}{}{Well, you never know. There's always hope.}
{266}{}{Oh, stop this nonsense.}

{267}{}{[She laughs] Bob?! That weird goofball? He's old! I mean, not too old for kids, but... Look at his head, and that tooth! He's so ugly, he... He wouldn't even be disgusted by a used up woman like me! And he's got that stutter, which is, y'know, kinda cute in a way, but... He lives alone, like I had to... And... And he's a hard worker, and really sort of sweet, and he doesn't smell *that* bad, compared to some of the guys in Reno, and... Hmmm. I mean... But, you know... That one thing.}
{268}{}{What thing?}
{269}{}{}

{270}{}{He, uh... How should I put it? People say he, err... "defiles" the corpses. If that's true, he's a maniac! I don't want to live with a psycho! Do you think I can trust him?}
{271}{}{You trust me, right? I'm telling you - don't listen to those rumors.}
{272}{}{You're right, you'd better stay away from him.}
{273}{}{Wait here. I'll learn more and come back.}

{274}{}{You're the only one I trust. Okay, I'll do it! You'll ask him about the date, right? I can't go myself. With my reputation, I don't want him to, you know... Misunderstand me?}
{275}{}{I'll set you up.}
{276}{}{I'll go see what can be done.}

{277}{}{This is great!}
{278}{}{See you.}
{279}{}{You see?}

{280}{}{I convinced Bob to go on a date with you. He's a little rough, but he is what he is.}
{281}{}{Oh, you're amazing! [she hugs you] No one's ever been so good to me. Thank you so much! Now I've got to get ready for my date. Oh, I'm so excited!}
{282}{}{Good luck.}
{283}{}{Ex-prostitute and necrophiliac are united at the cemetery. You've never seen anything so heartwarming and sweet.}

{284}{}{Bob said no. Actually, that's not quite true. He said your body will be the first he burns instead of buries, because you're so sick and filthy that he doesn't want to contaminate the groundwater, and that he'd rather fuck corpses than you because they stink less and have more charming personalities.}
{285}{}{He said that? He... That... [she starts to cry] That bastard! He was my last chance... Thank you for trying, anyway. It's not your fault. After everything I've done, maybe I deserve to be alone... }
{286}{}{Sorry, Jasmine.}
{287}{}{Yeah, probably.}
{288}{}{You snuffed out the last bit of hope in two damaged people. That's on you now.}

#About missing brahmin
{290}{}{What do you know about the missing brahmin?}
{291}{}{William's boy says he was watching the brahmin all night, but I saw him sleeping. He was even snoring. Ahh... Cute kid.}
{292}{}{Did anything unusual happen that night?}
{293}{}{Hmm, not really. Bolt used the toilet at night, and Justin used it in the morning. William woke me up when he was yelling at his boy for losing the brahmin.}
{294}{}{Right.}

#Female character
{1110}{}{[You see a girl with a beautiful hair and red scarf around her neck. As soon as she makes eye contact with you, she gives a flirty smile.] Well, hello, beautiful. New in town? I'd do *anything* for some conversation around here. Are you just passing by, or are you here to stay?}
{1126}{}{[She laughs] Are you serious? You really don't know? [she puts a finger under your chin and winks] Don't worry, baby. I'm a great teacher.}
{1159}{}{I'm sorry. I didn't mean to upset you.}
{1164}{}{[She stares at you with wide eyes] Are you fuckin' with me? Oh my god, I think you're really serious. Holy shit... A virgin, at your age.}
{1178}{}{That's pretty nasty. Do you know what it is?}
{1227}{}{[She looks stunned] You're... You're serious? I didn't think anyone would pay to get rid of me. Okay, I understand. I promise I'll go with the next caravan.}
{1250}{}{My guardian angel!}
{1274}{}{You're the only one I trust. Okay, I'll do it! You'll ask him about the date, right? I can't go myself. With my reputation, I don't want him to, you know... Misunderstand me?}
