{100}{}{You see a gang leader.}
{101}{}{You see the leader of the "Ferocious Molerats".}
{102}{}{We have a lot of work to do. Stay out of our way.}
{103}{}{Quiet! I hear them, they're close!}

{110}{}{Hey, you! Yeah, you! You fucked up now, kiddo! Don't you even dare to move - I'll drill you six times before you can turn around!}
{111}{}{Woah, hold on! I'm here to help you.}
{112}{}{Calm down. Tell me what you want, and I'll hear you out.}

{113}{}{You're the one who needs help, fucknut! But it's your lucky day! I need some live bait to deal with a pain in my ass, so I'm gonna offer you a deal!}
{114}{}{Uh-oh, guys, the big scary hero of the wastes is giving us one chance to explain ourselves! I'm shaking in my fuckin' boots over here! [he sneers] You're already dead, you cum-guzzling limpdick, you just don't know it yet. If you want to earn your life back, you'd better do exactly what I fucking say.}
{115}{}{And what's that?}
{116}{}{You know, I've changed my mind. I think the world will be better off without you in it. [attack]}

{117}{}{You see this cave? [he motions with his head towards a very obvious cave entrance] There's a bunch of pussies in there shitting themselves, too scared to come out and face us.}
{118}{}{And you want me to smoke them out.}

{119}{}{Oooh, did you figure that out all by yourself, numbnuts? Get the fuck in there. Don't come out unless you're bringing them with you. Got it?}
{120}{}{Fine, I'll see what I can do.}
{121}{}{[He whistles to the others] Clear a path! This one's going in! [he leans in close and snarls in your ear] Remember, don't even think of coming out without that caravan. Trust me, you'd rather starve to death in there than piss us off.}
{122}{}{[Go inside]}
{123}{}{[Resist]}
{124}{}{I don't like any of those options. I'll be on my way now.}

{125}{}{[He readies his weapon] Halt, motherfucker!}
{126}{}{Alright, man, relax, I'll do whatever you want.}
{127}{}{[Ignore]}

{128}{}{What the... Do you have a death wish, asshole?! Get the fuck back in there! And don't come out without that caravan next time!}
{129}{}{They're already dead. You can go in and get them.}
{130}{}{I just wanted some fresh air. I'm going back in now.}
{131}{}{This has gone on far enough. [attack]}

{132}{}{ARE YOU FUCKING WITH ME?! [he readies his weapon] You think this is funny?! Because you're gonna look fucking HILARIOUS when I blow your fucking head open, you understand?! The last thing you'll ever see is me eye-fucking your goddamn skull, you shit-eating prick!}
{133}{}{You should calm down. You'll live longer.}
{134}{}{[The raiders draw their weapons.]}
{135}{}{[Draw yours.]}
{136}{}{You'd better have good fucking news for me, or I'll bury you alive!}
{137}{}{[He starts screaming in rage, his face turning red and his eyes almost popping out of their sockets] Who the FUCK do you FUCKING think you're fucking FUCKING with, you ass-gobbling dogfucker?! WE'RE THE FEROCIOUS FUCKING MOLERATS!!! We're the most vicious motherfucking killers in the wasteland, do you hear me?! We fucking OWN everyone in sight of these mountains, they live and die because WE say so! NOBODY fucks with us! NOBODY!!!}

{138}{}{Oh really? Then we'll go check it out - right after you. Gear up, guys!}
{139}{}{Here we go...}

#Female character
{1114}{}{Uh-oh, guys, the big, tough bitch of the wastes is giving us one chance to explain ourselves! I'm shaking in my fuckin' boots over here! [he sneers] You're already dead, you pus-dripping cunt, you just don't know it yet. If you want to earn your life back, you'd better do exactly what I fucking say.}
{1119}{}{Oooh, did you figure that out all by yourself, sugar tits? Get the fuck in there. Don't come out unless you're bringing them with you. Got it?}
{1128}{}{What the... Do you have a death wish, bitch?! Get the fuck back in there! And don't come out without that caravan next time!}
{1132}{}{ARE YOU FUCKING WITH ME?! [he readies his weapon] You think this is funny?! Because you're gonna look fucking HILARIOUS when I blow your fucking head open, you understand?! The last thing you'll ever see is me eye-fucking your goddamn skull, you dumb fucking whore!}
{1137}{}{[He starts screaming in rage, his face turning red and his eyes almost popping out of their sockets] Who the FUCK do you FUCKING think you're fucking FUCKING with, you dog-sucking cumguzzler?! WE'RE THE FEROCIOUS FUCKING MOLERATS!!! We're the most vicious motherfucking killers in the wasteland, do you hear me?! We fucking OWN everyone in sight of these mountains, they live and die because WE say so! NOBODY fucks with us! NOBODY!!!}
