{100}{}{You see a prospector.}
{101}{}{You see a young man with a look of despair in his eyes.}
{102}{}{}

#Starting conversation
{110}{}{Hello. And goodbye.}
{111}{}{Hi, who are you?}
{112}{}{}
{113}{}{Look, sorry, but I don't want to talk to anyone right now. Just let me sit here in peace.}
{114}{}{Fine.}
{115}{}{Can you tell me anything interesting?}
{116}{}{Bye.}
{117}{}{Um, no. I don't think so. I don't know anything "interesting".}
{118}{}{You're not much fun to talk to.}
{119}{}{Mm-hmm. Yeah. You too.}

#ÊQuest about missing prospectors
{150}{}{Someone told me a prospector from Reno is hiding in Black Rock. Do you know anything about that?}
{151}{}{Er... Well, there's people here from all over Nevada. Why?}
{152}{}{No reason... It just so happens I have something from Mr. Wright.}
{153}{}{[Furtively draws his head into shoulders] Mr. Who? N-never heard of him. Er... Why, who is he looking for?}
{154}{}{Well, well. I never said he was looking for anyone.}

{155}{}{[He looks around agitatedly] Mister Wright put a hit on me, didn't he?}
{156}{}{That's right. A thousand bucks. And believe me, someone's gonna collect it.}
{157}{}{I'm not here on Wright's behalf. Someone else sent me.}

{158}{}{What, right here, in front of everybody? No, they- wait, did you say *thousand*? No, it can't be! Listen, Wright's not going to pay that. He's lying, don't you get it?}
{159}{}{There's nothing to get. I just want that money.}
{160}{}{That's interesting to hear. What's the deal between you and Wright?}
{161}{}{Uh, just - just wait! Wright's not going to see my body anyway, right? How about this: I give you my contract with him and you get off me. You'll show him the contract and tell him you took it off my dead body. He'll never see me again. And I'll even give you my metal detector, I'm sure you can get some cash for it! Can... Can we make a deal?}
{162}{}{Why not? Give me the contract and the metal detector. I'll take care of everything else.}
{163}{}{First, tell me what happened between you and Wright.}
{164}{}{Lying is a nasty habit, but in this case, a profitable one.}

{165}{}{[He sighs in relief] Oh, thank god... Look, if it's another competing prospectors - good luck to them. I could never finish the contract anyway.}
{166}{}{Tell me more.}

{167}{}{Where do I even start? My partner and I were supposed to get the explosives from Hawthorne, but it turned out to be not so easy. Robert died by the hands of some rival prospectors, and I alone couldn't get the job done. I snuck back into Reno to talk with my family, and we all decided it'll be better for me to leave the city, before Wright's sons kill me. That's the short version.}
{168}{}{Why does Wright need explosives?}
{169}{}{How did Robert die?}
{170}{}{Why didn't you say anything to Robert's family?}
{171}{}{Why do you think Wright would kill you?}
{172}{}{Why all the secrecy?}

{173}{}{Wright controls the electricity business in Reno. He used to make good money off it before, but now he's barely scraping by. There's a village south of Reno built around an old uranium mine, and he needs that uranium to make power. I don't know exactly where the explosives come in, but my guess is that he's expanding the mine.}
{174}{}{I was coming back from a exploration run, when I saw rival competitors in our camp. I hid, but Robert... [he sighs] I wanted to help, but it was one against four. It's pure luck I survived at all.}
{175}{}{How?! You want me to look in their eyes and tell them I just left their son to die? God, I can't even look myself in the mirror. How can I possibly face them?}
{176}{}{Because that's what he fucking does! He's a gangster, like every other boss in Reno! He'd make an example of me. Honestly, I can't even blame him - I messed up, and my family already owes him a lot of money.}
{177}{}{Wright didn't want the competition. Every boss in Reno is fighting for more territory and influence.}
{178}{}{Tell me more about these explosives.}
{179}{}{Wright wanted five crates of C-4. Hawthorne's the only place likely to have it, but we couldn't get past the defense systems. Robert wanted to repair a robot to take out the mines, but, in any case, you can't sneak past the turrets with those crates in hands. We figured the warehouse would have a car or something, but we didn't even have a plan for getting the C-4 to the mines. God, what a stupid plan that was.}
{180}{}{You know what I think about all of this?}
{181}{}{What?}
{182}{}{I'll just kill you and tell Wright the job is done. What do you say to that?}
{183}{}{You abandoned your family and left Robert's family to suffer. You have to help them.}
{184}{}{}

{185}{}{Wait, I know, what you need! Wright's not going to see my body anyway, right? How about this: I give you my contract with him and you get off me. You'll show him the contract and tell him you took it off my dead body. He'll never see me again. And I'll even give you my metal detector, I'm sure you can get some cash for it! Can... Can we make a deal?}
{186}{}{Give me the contract and the metal detector. I'll take care of everything else.}
{187}{}{No. You have to pay your debt to your and Robert's family.}
{188}{}{BUT HOW!? Wright needs a lot of explosives, and I can't get it from Hawthorne by myself.}
{189}{}{Then I'll just kill you and tell Wright the job is done. What do you say to that?}
{190}{}{I'll get the explosives and complete the contract for you. Trust me.}

{193}{}{Really? But... Oh, what choice do I have? Here's the contract. And take this metal detector - it'll get you past the mines in Hawthorne. I'll go to Reno and wait for you. I'm counting on you, okay? Both of our families are depend on that contract.}
{194}{}{Stay safe.}
