{100}{}{You see a refugee.}
{101}{}{You see a very thin man.}
{102}{}{We shouldn't have run away. We were safe, at least.}

{110}{}{[He looks at the ground] Yes, sir?}
{111}{}{So you're the fugitive slaves, right?}
{112}{}{Just passing by.}

{113}{}{[They look at each other, then back at the ground] Er... Yes, sir. There's no point hiding it now. We're runaway slaves.}
{114}{}{I need to know what happened to you before I can decide if you can stay.}
{115}{}{That's all I need to know. You have to get out of here.}
{116}{}{Wait here for now.}
{117}{}{Why don't you get rid of those collars?}

{120}{}{Yes, sir. Anything you say, sir.}
{121}{}{Where are you from?}
{122}{}{From Reno, sir. We were captured when we were young, and have been slaves since then.}
{123}{}{How did you escape?}
{124}{}{We spent weeks digging a tunnel, then knocked out a guard one night and escaped. Our friend spent a year planning it, but he only figured out how to get out. We didn't know how to survive outside or how to remove these collars. Walking around with these on our necks is... [they glance at each other anxiously] ...very dangerous.}
{125}{}{Why did you run away?}
{126}{}{Mister Luciano is having trouble in Reno, so he gave us less food and made us work every day. We understand why he needed to do that, but it was too much. It was better to take the risks than stay there.}
{127}{}{How many of you escaped?}
{128}{}{There were five of us. One starved to death. The second drank from a puddle and died of sickness. The third was eaten by a gecko. It was... [they look at each other sadly] ...a hard journey.}
{129}{}{Do you think they're looking for you?}
{130}{}{Mister Luciano will be angry, but we are not special. He won't pay anyone to look for us outside the city.}
{131}{}{I've heard enough to make a decision.}

{132}{}{[The two men watch you nervously.]}
{133}{}{You seem harmless. You can stay. Let's get you a job at the stables...}
{134}{}{You can't stay here. You have to leave.}
{135}{}{I need to think about this. I'll be back with my answer.}
{136}{}{[Their shoulders sag] Y-yes, sir. We understand. But we have nowhere to go. We won't survive another journey in the desert, sir! We can't leave.}
{137}{}{Your master needs slaves, right? He'll accept you back if you return to Reno. You'll have food and a roof over your head again.}
{138}{}{Why don't you return to your master?}
{139}{}{Mister Luciano?! [he looks you in the eyes for the first time, terrified] He'll skin us alive!}
{140}{}{I will think about this. Stay here.}
{141}{}{I didn't think of that. [he thinks for a moment] We can't survive on our own. Mister Luciano may still forgive us... [he turns to his friend] What do you think? [his friend nods, and he looks back at the ground in front of you] If we can't stay here, other towns won't accept us either. Our only chance is to go back to Reno. We'll leave as soon as we can.}
{142}{}{Stay safe!}
{143}{}{The sooner the better. I don't want to see you around here again.}

{144}{}{I'm not asking, I'm telling. Get out. One more word, and I'll feed you to the geckos, feet-first. Alive.}
{145}{}{N-no sir, please don't sir! We'll leave, sir, just please don't hurt us!}
{146}{}{That was a hell of a lot more than one word. Start running.}
{147}{}{Just walk away. Leave these people, this food, this water, this whole settlement, and I'll spare your lives. Just walk away.}

{148}{}{Okay, we're going. We don't want any violence. We're going.}
{149}{}{Hey, I'm not finished! [end]}

#Collar
{150}{}{That would be very helpful. People wouldn't be able to tell we're slaves, then. But it's not easy to take them off.}
{151}{}{I'll try. Let me see.}
{152}{}{Tell me about yourselves.}
{153}{}{[These collars are specifically designed to resist being removed without proper authorization. Unless you know what you're doing, tampering with them will cause them to electrocute the wearer, killing them instantly.]}
{154}{}{I think I see how to disable these. I'll get them off now.}
{155}{}{Whoops! [deliberately activate both collars]}
{156}{}{I can't help you.}

{157}{}{We're free! [he laughs in joy] I can't believe it! You saved us! [he moves his head around, stretching his neck like it's the first time he's ever doing it] Oh, this is... Amazing!}
{158}{}{Enjoy, guys.}

#Female character
{1110}{}{[He looks at the ground] Yes, ma'am?}
{1113}{}{[They look at each other, then back at the ground] Er... Yes, ma'am. There's no point hiding it now. We're fugitive slaves.}
{1120}{}{Yes, ma'am. Anything you say, ma'am.}
{1122}{}{From Reno, ma'am. We were captured when we were young, and have been slaves since then.}
{1131}{}{I've heard enough to make a decision.}
{1136}{}{[Their shoulders sag] Y-yes, ma'am. We understand. But we have nowhere to go. We won't survive another journey in the desert, ma'am! We can't leave.}
{1145}{}{N-no ma'am, please don't ma'am! We'll leave, ma'am, just please don't hurt us!}
