{100}{}{You see an old man.}
{101}{}{You see an old man Jed.}
{102}{}{You see an old man with gray curls on his head, dressed in old pajamas.}
{103}{}{You see Jedediah Smith, probably the oldest resident of Black Rock.}

#Meeting him
{110}{}{I always say "it's nice to meet you", even when it isn't nice at all. But if you want to coexist with people, you have to compromise. Remember that.}
{111}{}{Uh, sure. And you are?...}
{112}{}{What?}

{113}{}{Hmm? Oh, just thinking out loud is all. My name is Jedediah Smith. Nice to meet you. I'm a local heirloom, you could say... Perhaps, the oldest man in Nevada. Among those who are still humans, that is.}
{114}{}{My name is }
{115}{}{. It's an honor to meet you, Mister Smith.}
{116}{}{Oh, okay.}
{117}{}{You're as old as the wasteland, and just as fucked up. I get it.}

{118}{}{Oh, manners! [he smiles] A rarity in these parts.}
{119}{}{Why, thank you.}
{120}{}{[He sighs] I was rude when I was young, too. Now I see how unnecessary that is.}
{121}{}{I wanted to ask you something.}
{122}{}{[He looks at you with lidded eyes, then shakes his head in disapproval] You don't seem to be dangerous, so I'll continue talking to you.}
{123}{}{Uh, good.}

#Starting converstaion
{130}{}{What do you want from me, young man?}
{131}{}{Nothing right now. Goodbye.}

#Replies
{132}{}{Oh, I think about this a lot... }
{133}{}{Hmm, perhaps... }
{134}{}{Why not?..}
{135}{}{Maybe... }
{136}{}{Well, listen... }
{137}{}{I wanted to tell this for a long time... }
{138}{}{With pleasure! How about that?}
{139}{}{Just a second... }

#Wise phrases
{140}{}{You must have seen a lot in your time. Can you give me some advice?}

{141}{}{The weak eats the weaker to get stronger. This is the basis of all our lives.}
{142}{}{One day, you'll have to decide where to go. And when you decide, go without even a second of hesitation.}
{143}{}{People try to plan everything ahead, but it is pointless. No one can really know what is there to come.}
{144}{}{People don't change between the ages of ten and twenty... Nor between ten and eighty.}
{145}{}{An immature man thinks he should die for what is right. A mature man knows he must live for what is right.}
{146}{}{If someone pushes you around, the worst thing you can do is to pretend he doesn't bother you at all.}
{147}{}{You must laugh at what tortures you, or you will lose the perspective. And then the world will be lost to you.}
{148}{}{You can only notice change in a man after not seeing him for some time. If you see him every day, you won't notice anything, because a man changes slowly.}
{149}{}{True strength is to see a funny side in everything.}
{150}{}{If you aren't careful, people will control you. You will either do what they want, or you will devote yourself to doing what they don't want.}
{151}{}{When I die, send me to the heavens.}

{152}{}{Hmm... Can you tell me something else?}
{153}{}{I think that's enough wisdom for today.}

#Black Rock good deeds prize
{160}{}{I'm happy to see you, my boy. You've done a lot of good for Black Rock, especially for those who needed it most. I would like to thank you. Please, take the healing powder from that shelf. You may need it.}
{161}{}{Thanks... }

#About himself and Nevada
{170}{}{Tell me about yourself.}
{171}{}{I am Jedediah Smith. You might say, I founded this place. I was a traveler in my youth... As my legs became old, I began looking for a place to rest in my final years. I chose this beautiful valley.}
{172}{}{Can I ask you something else?}
{173}{}{Did you travel a lot?}
{174}{}{Oh, yes, a long time ago. I wanted to find a good place for people to live, but it seemed that there were no such places left on Earth. As I got older, I got tired of searching and went east, inland. That's how I found Reno. At the time it was like a heaven to me, but when it got too... Hmm... Loud, I suppose, I left for a small place where I could be alone. It turns out I couldn't, even here.}
{175}{}{Can you tell me of any interesting places in Nevada?}
{176}{}{To the south you'll have the Cheyenne tribe, further - New Reno. Gerlach is to the west. I don't think there is anything else worth mentioning around here. Far to the east is Salt Lake City, but I've never been there, so I can't tell you more.}
{177}{}{Thank you. Can I ask another question?}

{178}{}{How did this community get started?}
{179}{}{When I got tired of the excitement in New Reno, I chose to live my last years in isolation. A caravan took me to this valley, but others followed my footsteps. William and Justin were the first ones, and rumors about good life brought others. If not for me, there would be no life here. [He smiles] It is... A different sort of excitement, isn't it?}
{180}{}{What do you think of William?}
{181}{}{What do you think of Justin?}
{182}{}{You can tell he came from a good family. He's friendly and generous, but too trusting of strangers. It had hurt him in the past, but it's because of him we have so many good people here.}
{183}{}{Hard and venomous, like a radscorpion. But that's how radscorpions keep their nests safe. His mistrust is useful in its own way.}
{184}{}{How do William and Justin influence the community?}
{185}{}{Directly and radically. William tries to make the community open by letting everyone in and establishing trade routes with other settlements. Justin wants to keep us safe by isolating us. They're both acting for the good of the community, and they're both right. If we removed either of them, Black Rock would fall.}

{186}{}{Smith marks the locations on your map.}

#About prostitute
{190}{}{Let's talk about Jasmine.}
{191}{}{Jasmine? Oh, be careful with her, she's quite the character. But her coarse tongue is not the real problem. No... The sin in her blood and on her skin - that is the real problem.}
{192}{}{What are you talking about?}
{193}{}{You probably already know she is sick. A skin disease - I've seen it before, and believe me, it ends badly.}
{194}{}{You've seen it before? When and where?}
{195}{}{Does anyone else here have this disease?}
{196}{}{Can she be cured?}
{197}{}{In Reno, after the war. People were too busy with fighting, to bother with hygiene, and where the streets weren't slick with blood, they were littered with garbage, swarmed with rats and stray dogs... It's no surprise the plague started. If they hadn't found the cure, then, maybe, there would not be a Reno today.}
{198}{}{No, not for now. It was already inside her when she got here, and although she was hiding it, we found out before anything happened. Thankfully, I don't think it spreads except by, ah, physical contact. In the biblical sense.}
{199}{}{They cured it in Reno a long time ago. Perhaps Jasmine can be cured too, but it's hard to tell.}
{200}{}{What was the cure?}
{201}{}{A tincture of nightshade and some other ingredients. I don't remember exactly what - it's been too long. But a man with the right skills could figure it out.}
{202}{}{Nightshade? A plant?}
{203}{}{Exactly. Its poisonous berries were used in medicine since long before the war, but it is hard to find in the dry Nevada desert. And even if you did find some, would you know what to do with it?}
{204}{}{The berries are poisonous, right? They probably contain alkaloids. They're known to cause severe intoxication and could have an antibacterial effect.}
{205}{}{It's worth a try. If I find some nightshade, maybe I can do something with it.}
{206}{}{Hmm? Well, if you say so, then you can try your luck by making the medicine yourself. You only have to find the plant. Ask the Cheyenne tribe to the south - if anyone knew better, it would be then.}
{207}{}{Just remember, don't try making the medicine if you don't know what you're doing. Nightshade is better known for taking life than for restoring it.}
{208}{}{Thank you for the information.}

{210}{}{We talked about nightshade earlier. Are these the berries?}
{211}{}{Yes, that's the ones! But the berries alone are simply poison. If you combine them with healing herbs, the poison will heal the body, but reinforced with scorpion poison, it will be an extremely lethal toxin. If you want to make medicine of it, you'll need to learn how.}
{212}{}{How can I learn it?}
{213}{}{Hmm... I remember the tincture was boiled in clean water with some xander root and broc flower, but I don't remember the temperature and exact conditions. If you want to experiment, you can use the campfire just outside.}
{214}{}{I'll go try right now.}

#Main quest of the location
{250}{}{I need your advice regarding Milo.}
{251}{}{My advice? Oh, no one has asked my advice in a very long time. Please, tell me everything.}
{252}{}{[Tell him the full story.]}
{253}{}{Actually, I'll just figure it out myself.}
{254}{}{[He listens carefully, but at some point you think he falls asleep.]}
{255}{}{Um... }
{256}{}{[He jerks upright] Hmm! Yes, very complicated indeed. Here is what I'll tell you: William and Justin always argue over what to do with the community, but they complete each other. Each has the strengths to compensate for each other's weaknesses. Without this balance, the Black Rock will fall.}
{257}{}{Then what should I do with Eugene and the others?}
{258}{}{Try not to involve William or Justin. Convince Eugene yourself - he is not as bad as he looks. He is a young man trying to prove himself, like all young men. Proving himself to raiders is a mistake, but mistakes can be corrected.}
{259}{}{That doesn't sound easy.}
{260}{}{And yes - William's deal to trade gecko pelts to caravans will change the future of our community, if the caravans choose to come here. Raiders, slaves, prostitutes, murders - all these can scare caravans off.}
{261}{}{Thank you, Mister Smith. You've been a huge help.}
{262}{}{That's it?! I could have figured that out myself!}

#Female character
{1122}{}{[He looks at you with lidded eyes, then shakes his head in disapproval] You don't seem to be dangerous, so I'll continue talking to you.}
{1130}{}{What do you want from me, young lady?}
{1160}{}{I'm happy to see you, my girl. You did a lot of good for Black Rock, especially for those who needed it most. I would like to thank you. Please, take the healing powder from that shelf. You may need it.}
{1262}{}{That's it?! I could have figured that out myself!}
