{100}{}{You see a local.}
{101}{}{You see one of Black Rock's citizens.}

###############################################################
#
#              Pop-ups
#
###############################################################

#Jed died
{102}{}{I knew Jed would die soon.}
{103}{}{Jed's done so much for us. I hope he's in a better place.}
{104}{}{Not many people get to die of old age nowadays.}
{105}{}{Jed always said, "When I die, send me to the heavens." Whatever that means.}
{106}{}{I had a dream that Smith was in heaven, but it was full of tribals. Bad luck.}

#Jed's alive
{107}{}{Jed doesn't have much time left. I can feel it.}
{108}{}{If Jed dies, I might cry. You know... Just a little bit.}
{109}{}{The heavens are waiting for Jed... Ah, whatever.}

#Robbed graves reactions
{110}{}{They say someone is digging up the graves, but I still think it's Bob.}
{111}{}{If I wake up to find one more defiled grave... Bob's gonna get it.}
{112}{}{Bob is a good guy, but he needs to learn to control himself.}
{113}{}{}
{114}{}{}

{115}{}{When I die, I hope the geckos get to my body before Bob does.}
{116}{}{We have to bring Bob to justice! How many times will he desecrate our dead?}
{117}{}{Bob is a good guy, but he needs to learn to control himself.}
{118}{}{}
{119}{}{}

#Mike's outcomes
{120}{}{Mike was one of our best hunters! Why did you do that?!}
{121}{}{You really had to kill Mike?!}
{122}{}{How could you have killed Mike?!}
{123}{}{I liked Mike, but I knew it would happen sooner or later.}
{124}{}{}

{125}{}{Mike sure loves to fight.}
{126}{}{If there's one guy in town you shouldn't mess with, it's Mike.}
{127}{}{Mike will get drunk and go looking for a fight again.}
{128}{}{That Mike really needs an ass-kicking.}
{129}{}{}

{130}{}{Oh, Mike beat you? Ha! That must have been fun.}
{131}{}{Shit, Mike really kicked your ass, huh?}
{132}{}{Man, I was really hoping someone would kick Mike's ass. That's too bad.}
{133}{}{Don't give up. Mike hasn't been beaten since... Hmm, a couple days ago, maybe.}
{134}{}{}

{135}{}{You beat up Mike? It's an honor!}
{136}{}{So you beat up Mike, huh? That's impressive.}
{137}{}{Hey, good job on Mike!}
{138}{}{This should keep Mike from looking for a fight for a while.}
{139}{}{Hahaha!!!You kicked Mike's ass! High five!}

#When character is a raider
{140}{}{There's been more raiders around lately. Hmm, how do I know you're not one of them?}
{141}{}{Raiders aren't welcome here.}
{142}{}{Raiding is not a life that ends well.}
{143}{}{God strike me if I don't kill at least one raider this month.}
{144}{}{}
{145}{}{If the raiders attack the next caravan, we won't get another one.}
{146}{}{There were more raiders this morning. How long will this go on?}
{147}{}{I wish those raiders would just die.}
{148}{}{}
{149}{}{}

#Pop-ups
{150}{}{Uh, hi.}
{151}{}{What a shitty day. Just like any other.}
{152}{}{Don't shake my hand. I was just in the toilet.}
{153}{}{It's getting crowded in here.}
{154}{}{You're not going to settle down here, I hope?}
{155}{}{Have you met William? He's a good guy. Not very bright, though.}
{156}{}{You talked to Justin yet? He's tough, but he's irreplaceable.}

#Brahmin
{157}{}{How could a whole brahmin just disappear?}
{158}{}{If I were William, I'd kick his boy's ass.}
{159}{}{Only in Black Rock could a whole brahmin just disappear.}

#Fugitive slaves
{160}{}{Those slaves are nothing but trouble.}
{161}{}{Slaves belong with their master, not in Black Rock!}
{162}{}{The slaves are finally gone? That's good to hear.}
{163}{}{If we get any more fugitive slaves, we'll do the same.}
{164}{}{William's lost his mind? We don't want runaway slaves hiding out here!}
{165}{}{William took these slaves? He's too soft.}
{166}{}{Well, I think there is no danger if the collars of these slaves are gone.}
{167}{}{These slaves shouldn't be a problem anymore, but who knows?}
{168}{}{}
{169}{}{}

#Main quest of Black Rock
{170}{}{Damn it! William was counting on this caravan... }
{171}{}{It's a pity the caravan deal fell through.}
{172}{}{I too had hoped to buy something new from that caravan... }
{173}{}{I guess we won't be getting mail from Reno anytime soon.}

{174}{}{Whoever saved that caravan must be one bad motherf...}
{175}{}{Finally, things are getting better!}
{176}{}{I'm sick of all these caravans.}

{177}{}{I heard William is waiting for Milo. Usually he's not this late.}
{178}{}{I wouldn't be surprised if Milo just ran away from his wife. Ha!}
{179}{}{I haven’t seen Milo in a long time.}


###############################################################
#
#              Talk with Dave about pistol
#
###############################################################

{199}{}{You see Dave.}

{200}{}{[He smiles and nods] Welcome! Always happy to see people like you in this shithole.}
{201}{}{[He peers at you suspiciously] New in town? Interesting... What do you want from me?}
{202}{}{Are you Dave?}
{203}{}{Nothing.}
{204}{}{You caught me! I won't hide the fact that I'm Dave anymore. Strictly speaking, everyone knew it before, and now you know it too. Damn, it's hard to hide in a town this small.}
{205}{}{Cut the jokes. Do you know anything about this pistol?}
{206}{}{Ah, yeah... My trusty partner, Smiley, used to go hunting with it. He was a lucky guy, but not lucky enough to survive an encounter with raiders. Smiley's stuff was sold off, and, of course, that damn peddler William took the best things, including this gun. But he made a mistake.}
{207}{}{What mistake?}
{208}{}{He forgot that it needs batteries! No one's going to buy a plasma pistol you can't power. Also, it's not as good as it seems. Smiley had to fix it up constantly just to keep it working.}
{209}{}{Do you know how to fix it up?}
{210}{}{Hmm... [he rubs his chin] Well, I saw him do it... So, I must be the only one who knows how to clean and calibrate this baby. No one even tried it after Smiley died. I'll be honest, that thing's never going to be a real killer, but with a bit of work you might get more "oomph" out of it.}
{211}{}{That sounds great. Can you do that?}
{212}{}{Sure... But it's gonna cost you.}
{213}{}{What do you want?}
{214}{}{William on my back about gecko pelts, but hunting's been really lousy lately. Get me about, oh, 250 bucks' worth of pelts and I'll clean that baby right up.}
{215}{}{Let's talk about the pistol again.}
{216}{}{What types of gecko pelts does William want?}
{217}{}{I'll go, then.}

{218}{}{Golden gecko pelts are more valuable than silver ones, but any will do. I just need to get William off my back.}
{219}{}{Here's a silver gecko pelt.}
{220}{}{Take a golden gecko pelt.}
{221}{}{Look! I have an acid gecko pelt.}

{222}{}{Great! That would do it. Give me the pistol and I'll fix it up right away.}
{223}{}{Here you go. It better be worth it.}
{224}{}{Good, but this is not enough. Bring me more.}

{225}{}{[Dave carefully disassembles, cleans and calibrates the weapon. Sometimes it seems like he doesn't know what he's doing, but finally he assembles the pistol back and hands it to you.] Well, what did I tell you? Only I can fix it!}
{226}{}{Good work, Dave. Nevada is about to get a lot emptier.}
{227}{}{Thanks, Dave. You really helped me out.}
{228}{}{No, this won’t cut it.}
{229}{}{Don't mention it. It was nothing.}

#{230}{}{Dave, what do you know about energy weapons?}
#{231}{}{Not much. You might find some pre-war magazines about them in big cities though.}
#{232}{}{Tell me about Smiley and raiders. What happened?}
#{233}{}{We were on our way back from a hunt in Lovelock. The raiders ambushed us and demanded food. They looked tired and hungry, and there weren't many of them, so we just shot them. Smiley was badly wounded in the fight. Sucks, huh?}
#{234}{}{Lovelock? Where is that?}

{235}{}{What now?}
{236}{}{I'll see you later, when I have the pistol.}
{237}{}{I'll do it as soon as you bring the pistol.}
{238}{}{I already told you, William's on my ass about gecko pelts. Bring me about }
{239}{}{ dollars' worth of pelts, and I'll fix up that pistol for you.}

###############################################################
#
#              Talk with Bolt
#
###############################################################

{250}{}{You see Bolt.}
{251}{}{[He glares at you] What?}
{252}{}{Uh, nothing. Nothing at all.}
{253}{}{Are you Bolt?}

{254}{}{That's what they call me. What do you want?}
{255}{}{Why do they call you Bolt?}
{256}{}{What were you doing the night the brahmin disappeared?}
{257}{}{[He smirks] Maybe it's because I have a metallic spark in my eyes.}
{258}{}{Sleeping, as I was supposed to. Don't try using this psychological crap on me - I have nothing to do with that fucking brahmin. Nothing.}
{259}{}{Bolt, can I see your shotgun shells?}
{260}{}{Eh, my shotgun shells? Why?}
{261}{}{I want to compare them with the ones left in the body of the stolen brahmin.}
{262}{}{[He looks around and whispers] How the fuck... Dammit! I knew I'd get in trouble for this shit!}
{263}{}{Interesting. What do you have to say in your defense?}

{264}{}{Fuck it, I won't even try! I'm not that kind of person. Do you know what kind of person I am? I'm one of the "Molerats" gang, that's what! Well, I *was* a Molerat. I'm retired... At least, that's what I thought.}
{265}{}{Tell me about the gang.}
{266}{}{You left the gang?}
{267}{}{How is this connected to the missing brahmin?}
{268}{}{What are you going to do now?}
{269}{}{I have to decide what to do next.}
{270}{}{A bunch of scumbags that couldn't hack it in Gerlach or Black Rock, but have enough ammo to feed themselves in the mountains. Not very glamorous, but you gotta eat.}
{271}{}{Yeah. We used to control this whole valley, but by the time I left, we were shaking random travelers for crumbs. I settled here, and until you figured me out, no one knew about my past.}
{272}{}{The guys hadn't eaten in a while, so one night they came to me. I couldn't say no - they are not as menacing as before, but still strong enough to kill me! I stirred the xander root powder in the water and gave it to that kid to put him to sleep. Then I pulled the boards off the fence to get the brahmin out without too much hassle.}
{273}{}{Nothing. If they're going to throw me out, so be it. I'll go to Big Louie and join him. It won't be as good as here, but at least I won't starve to death like the Molerats. They don't have much time left.}
{274}{}{Not much time left? Why not to get rid of them right now?}
{275}{}{I know what you're thinking - get a posse and take these guys down, right? Not a chance, buddy - that only happened in old movies. The gang is well hidden in the mountains, you won't get to them that easily. But I'll tell you this - if William gets that caravan route going, it'll bring the gang back to life.}
{276}{}{I'm going to tell everyone the truth, unless you convince me not to.}
{277}{}{Oh, lah-dee-dah! Fuck that. William won't kill me, he'll just cast me out. So, I'm breathing freely. See? [he inhales deeply] I smell adventure!}

{280}{}{I talked to William. He forgives you and says you can stay.}
{281}{}{William's furious. You have to leave Black Rock.}
{282}{}{He forgives me? After all I've done? I... Hmm. I didn't expect that. But if he says so... Look, thanks. You did a good thing for me, better than I deserve.}
{283}{}{Yeah, I won't say I don't deserve it. I'll pack up and go. I tried to go straight, but I couldn't - and that's fine. Tell William that whether I'm here or not, the gang will be back. He'd better be ready.}
{284}{}{Enjoy your life here.}
{285}{}{Just shut up and go.}

{286}{}{I have to do what I can to fix this.}
{287}{}{You won't see me around here again.}

#Female character
{1101}{}{You see one of Black Rock's citizens.}
{1275}{}{I know what you're thinking - get a posse and take these guys down, right? Not a chance, baby - that only happened in old movies. The gang is well hidden in the mountains, you won't get to them that easily. But I'll tell you this - if William gets that caravan route going, it'll bring the gang back to life.}
{1280}{}{I talked to William. He forgives you and says you can stay.}