{100}{}{You see William.}
{101}{}{You see the eatery owner.}

#Conversation
{107}{}{[Make a bully face] Hey, didn't your mother ever tell you it's rude to stare? Stop it!}
{108}{}{Woah, there! Don't mind the rabble, you're safe here. How about you take a sandwich on the house and we'll forget about this misunderstanding, huh?}
{109}{}{What the... Are you serious? [you hear someone laughing behind you] Hey, knock that off back there! Look, friend: If I have something you need and you have something I need, maybe we can negotiate a deal that's good for both of us. That's called barter. Get it?}
{110}{}{Hey there, friend! It's been a while since we had a new face here. Want to barter? Don't be shy! I'm always happy to help travelers, as long as they don't cause trouble.}
{111}{}{Barter? What's that?}
{112}{}{Really? Well... Trading. If I have something you need and you have something I need, maybe we can negotiate a deal that's good for both of us. That's called barter. Get it?}
{113}{}{Makes sense. Let's trade.}
{114}{}{Not yet. I want to ask you about this place.}

{115}{}{Yeah, selection ain't great, I know. I'll have more next time... I hope.}
{116}{}{Well, hey, friend! So happy to see ya!}
{117}{}{Let's talk.}
{118}{}{What do you have for trade?}
{119}{}{That's enough for today. Bye.}

{120}{}{What's that strange pistol?}
{121}{}{Can we talk about that strange pistol I bought from you?}
{122}{}{That's a jen-yoo-yine plasma pistol of a very old model. One of the first to hit the civilian market before the war. It's a little banged up, but it gets the job done. Why?}
{123}{}{Tell me more about that pistol.}
{124}{}{That's all.}

{125}{}{Belonged to one of the locals, God rest his soul. Can't say I know much more about it, but Dave might. Me, I'm just the salesman.}
{126}{}{How did you get it?}
{127}{}{After the raiders killed the owner, Dave and I split what was left in his tent. It wasn't much, I'll tell you that.}
{128}{}{Interesting. Now let's trade.}
{129}{}{That's all I wanted. I'll be going now.}
{130}{}{Let's talk about something else.}

{131}{}{I want to ask you a few things about this place.}
{132}{}{Such as?}

{133}{}{Do you have a water pump fuse?}
{134}{}{No, there's nothing like that here. I'm in charge of food and drink mostly. Justin handles all the complicated tech.}
{135}{}{Right.}
{136}{}{Something else?}
{137}{}{That's enough.}
{138}{}{Do you have any raiders around?}
{139}{}{Yeah, some local gang of scumbags. They live somewhere up in the mountains. No one knows anything about 'em.}

#About Black Rock
{140}{}{Sure! I'm always happy to talk about our lovely commune Black Rock!}
{141}{}{What can you tell me about this place's history?}
{142}{}{Who's in charge? I'm new here and want to impress the right people.}
{143}{}{Do you have any *serious* work for me here?}
{144}{}{Hey, it's all serious! But if you want something big, a caravan merchant told me that "Nevada Express" needs an investigator, though it was a while ago. You can find them in Reno. Work around here is a little more laid back... But at least you'll have friendly coworkers!}

{145}{}{Who's that quiet guy in the leather jacket?}
{146}{}{Don't know. He came with the caravan some time ago, hardly says anything, except to buy food and drink. I think he'll move on soon.}
{147}{}{That'd be me and Justin! I take care of the food and Justin keeps the water and electricity running. Justin is, uh... A lot less welcomin' than I am, but we can always find a common ground when it's about the good of the community.}

{148}{}{What are you talking about then?}
{149}{}{Whatever you say.}

#About bikers
{150}{}{Do you know anything about bikers?}
{151}{}{They pass through here from time to time. What do you want to know?}
{152}{}{Who are they?}
{153}{}{Do they have some sort of base?}
{154}{}{What do you think of them?}
{155}{}{What do you know about the attack on "Nevada Express"?}
{156}{}{That'd be enough. Thank you.}

{157}{}{Tell me, did a biker named Jay Kukish come through here recently?}
{158}{}{Yeah, he did! Stocked up on food and left in a hurry.}
{159}{}{Do you have any idea where he went?}

{160}{}{Good question. Hmmm... I've heard of bikers riding around Nevada and California on their bikes, living freely by their own philosophy and making their own destiny. That's not the case with these guys. The ones riding here are just a bunch of not-so-bad guys who don't give two shits about anything but themselves. Does that answer your question?}
{161}{}{Beats me! If they do, they don't tell anyone. I know they usually come from the east and south, but there's a helluva lot of space in the Great Nevada Ring to hide a base.}
{162}{}{Great Nevada what?}
{163}{}{That's what we call the highway between Salt Lake City, Vegas, and Reno. There are a lot of travelers on these roads, which also means there are a lot of bandits. If you stay off the roads, you'll avoid most of them, but you'll have to deal with the wilderness of the wasteland in this case.}
{164}{}{They're not bad people. They got a lot of spirit and don't make trouble, so I like 'em. I make 'em pay up front though, if you know what I mean.}
{165}{}{I heard someone attacked a "Nevada Express" transport east of here. It could have been raiders, but "Express" blames the bikers. I don't know the details, but it's a strange story.}
{166}{}{Can you show me where the attack took place?}
{167}{}{Sure! [he shows you the location on your map]}
{168}{}{I could, but I'm not sure I should. Why should I trust you?}
{169}{}{What if I pay you?}
{170}{}{Give me fifty bucks and I'll point you to it.}
{171}{}{Sounds great! [He takes your money and shows the location on your map]}
{172}{}{He was heading south when he left. Wherever he's going, he'll definitely make a stop off in Reno.}
{173}{}{Thanks for your help.}

#Gecko's eggs
{180}{}{I have gecko's balls... I mean eggs.}
{181}{}{Hey, that's great! I'll give you fifty bucks a pop for 'em!}
{182}{}{Why are you buying them?}
{183}{}{Then take everything I have.}
{184}{}{I'll think about it.}
{185}{}{Well, I hope you think fast... }
{186}{}{Because caravan merchants from Reno will pay me more. They pay top dollar for 'em, because they're hard to get. That's why I buy and resell. Fortunately, they are easy to keep for a long time.}
{187}{}{A fair deal! Thanks.}
{188}{}{Hey, didn't your mother ever tell you it's mean to fool people?}
{189}{}{I don't remember that... }

#History
{190}{}{}
{191}{}{There's not much to tell. Before the war, Black Rock had been something of a huge junkyard. At least, we assumed it was a junkyard. It was full of these weird metal shapes and structures. They looked like they had been made by a junkie.}
{192}{}{[More]}
{193}{}{We heard a rumor that someone settled here, and realized we could build ourselves a community away from "civilization". Life was pretty shitty in big cities back then. We wanted a fresh start.}
{194}{}{[More]}
{195}{}{So we came here, busted down these strange structures, and built our houses out of them. More people came, with brahmins and tents. So we eventually became a place to stop for travelers and caravan traders.}
{196}{}{Thanks.}
{197}{}{Don't mention it!}
{198}{}{Sounds more like it was a collection of sculptures than a junkyard, don't you think?}
{199}{}{You mean, like an art expo? Hmm... You know, you just might be right!}

#Help Jas
{200}{}{It seems like things don't go well around here. Can I help you with anything?}
{201}{}{[He raises an eyebrow] Well, I don't know what you have in mind, but if you want to help, I'd love if you could do something about Jasmine.}
{202}{}{Who?}
{203}{}{Nevermind then.}
{204}{}{Hmm.}

{205}{}{[He sighs] That poor, poor girl. Her father brought her here from Reno. Would have been a great fresh start, but he died in a gecko hunt, and Jasmine got these nasty blisters on her skin. Some kind of disease.}
{206}{}{And?}
{207}{}{Justin says we should burn her alive to keep anyone else getting sick, just like in the old days. But he doesn't have the guts to do it. Me? I think we are better than that. Don't want to have evil gossips about our little town spreading around.}
{208}{}{What can I do?}
{209}{}{Well, let me be clear: we can't do much for her. Not only do we lack a doctor, but we don't even have a proper medicine. But if you find a way to cure her, I will pay you for your trouble.}
{210}{}{I'll see what I can do.}
{211}{}{I'm afraid I can't help you.}
{212}{}{I understand. Just forget it.}
{213}{}{I'm happy to hear that! Just don't say anything to Justin. He hates Jasmine.}

{220}{}{About Jasmine... }
{221}{}{Yeah?}
{222}{}{She's dead.}
{223}{}{Oh, nothing.}
{224}{}{I managed to cure her. She's not infectious anymore.}
{225}{}{Dead?! She didn't deserve that! [he sighs] Well, at least there's no risk of gettin' sick now. I bet Justin will be happy to hear this.}
{226}{}{Didn't you promise me a reward?}
{227}{}{Bye.}
{228}{}{Yeah, for curing her! You think I'm happy to learn about her death? She didn't ask to be sick. If you want a reward for what you did to a vulnerable girl, ask Justin. You'll get nothing from me.}
{229}{}{Fine.}
{230}{}{Hot damn! You have no idea how thankful I am to hear that. Here, take this for your expenses [he gives you fifty dollars] - and here's some food and drink. It's on the house. You earned it!}
{231}{}{You're welcome.}
{232}{}{Fine.}

{233}{}{William, I'm sorry, but it cost me a little more than that... }
{234}{}{I'm sorry too, but I'm not rich. I gave you as much as I could.}
{235}{}{Fine.}
{236}{}{Oh... That's awkward. Hmm... I think I can spare another fifty bucks. Don't worry, I'll make that back. But I can't give you more, sorry.}
{237}{}{Thank you.}
{238}{}{You earned 50 experience points for a successful use of trading skill.}
{239}{}{She left.}
{240}{}{Without even saying goodbye? Hmm... I guess that's not surprising, considering how she was treated here. Gravedigger Bob might have been the only one who cared about her... Well, nothing can be done about it, I suppose.}

#Quest - fugitive slaves
{250}{}{Is there anything else I can do to help out?}
{251}{}{Yeah, actually. We could use a fresh look on one matter.}
{252}{}{Tell me more.}
{253}{}{A couple of fugitive slaves have recently appeared in town. The poor fellows must have come a long and difficult journey to get away from whoever was their owner. But we don't know if they can be useful here, or if they can be trusted. Justin thinks it's dangerous to even have them here. We need a neutral party to see if we should let them stay or send them away.}
{254}{}{I'll do it.}
{255}{}{No thanks. Fugitive slaves aren't my thing.}

{256}{}{About those fugitive slaves... }
{257}{}{What do you think?}
{258}{}{They'll work for almost nothing, besides food and a roof over their heads. They'll be very useful to Black Rock.}
{259}{}{They're dead. It's better for everyone this way, believe me.}
{260}{}{}
{261}{}{I've sent them away. They would have brought slavers here.}
{262}{}{I'm still working on it.}

{263}{}{That's just what I wanted to hear! And it's not about cheap labor - we're all equal here. It's about safety. And if you're telling me they're trustworthy and won't attract slavers, then I'm more than happy.}
{264}{}{Good.}
{265}{}{Dead?! Goddamn... You didn't do it, did you? No, don't tell me. I don't want to know. [he sighs] Well, at least Justin will be happy... }
{266}{}{Didn't I earn anything for my trouble?}
{267}{}{}
{268}{}{}
{269}{}{If you think about it... Yeah, there is a chance that slavers could pick up their trail and make their way to Black Rock. That wouldn't be good, even if we can defend ourselves. Looks like we are better off without slaves. And I'm especially glad it was solved peacefully.}
{270}{}{Great.}

{271}{}{Thank you for your deep understanding of the situation, it's much appreciated. Have a sandwich - you must be hungry after all that running around.}
{272}{}{Thanks.}
{273}{}{At least it's something.}

{274}{}{Great! You'll find them huddled near the camp fire in front of Jed's house. Just don't say anything to Justin - he just wants them gone.}
{275}{}{We'll see.}
{276}{}{Yeah, no. Sorry, but I didn't ask for anyone to end up dead! What will people think of what we do to visitors? I suppose Justin will be glad to hear it from you though.}
{277}{}{Geez... }

{278}{}{Thanks for doing such a good job. Take a sandwich and a beer - you must be hungry after all that running around.}

#Quest - missing brahmin
{300}{}{Is there anything else I can do?}
{301}{}{About that missing brahmin... }
{302}{}{}
{303}{}{I won't lie - that business with the slaves didn't do much for your reputation. But I think I've got something for you.}
{304}{}{I was hoping you'd ask that! After how you dealt with those escaped slaves, I've got something right up your alley.}
{305}{}{What is it?}

{306}{}{So here's the deal: my boy usually watches the brahmin at night, but a few days ago I noticed that we're missing one. Justin says it's my son's fault, but I don't think so. I need someone to get to the bottom of this.}
{307}{}{I think I can handle that.}
{308}{}{Sorry, pal, but I have other problems right now.}
{309}{}{Great! I'll make it worth your while, believe me! The brahmin pen's right out behind the eatery. My son's out there now.}
{310}{}{Just wait, I will go talk to him.}

{311}{}{Any news?}
{312}{}{Nothing yet.}

{313}{}{Does anyone in Black Rock make shotgun shells with rusty nails?}
{314}{}{Hmm, that's a good question... It's hard to get ammunition here, so we usually keep it for special occasions. If anyone's making ammo, Justin would know. He has all the town's tools and machinery.}
{315}{}{That's all the information I needed.}
{316}{}{I found the thief.}
{317}{}{Who?! Who did it?}
{318}{}{[Tell him the whole story.]}
{319}{}{...And he poisoned my son?! That bastard! I took him in, I trusted him like family! How could that backstabbing son of a bitch do this to me?!}
{320}{}{}
{321}{}{You should consider they'd have killed him if he hadn't done what they said. It's hard to do things your way when you have a shotgun pointed at you. He was a prisoner of the situation, can't you see?}
{322}{}{He's dangerous. Even his presence attracts raiders. We have to get rid of him.}
{323}{}{You mean I should forgive him? After all that he's done? [he puts a hand on his chin and frowns] Well... He was forced to do it. And this gang, the Molerats - they don't fuck around. No, he's as much a victim as I am... I forgive him, he can stay. And about the brahmin - I think he'll make up for it.}
{324}{}{Good. I'll go tell him the good news.}
{325}{}{Yes... Yes, you're right. Maybe he left the gang, but the gang didn't leave him. I don't like it, but... We have to make him leave.}
{326}{}{Remember, it was your decision. I'll go tell him now.}
{327}{}{Wait! I promised you a reward. Take some money, a sandwich and a beer. It's on the house. Thanks for your hard work, friend.}
{328}{}{You're welcome.}

#Delivery
{350}{}{Any more work?}
{351}{}{About that courier... }
{352}{}{You're a machine, ain'tcha? Okay, there's one more thing. It's a little more complicated than the last ones, but after Bolt and the slaves I'm pretty sure you can handle it.}
{353}{}{Don't worry. I can do it.}
{354}{}{Great! A courier is scheduled to make a delivery, but he's a couple days late. Someone needs to find him and the packages he was carrying. He can't be too far. What do you say?}
{355}{}{I'll do my best.}
{356}{}{Run around the desert looking for a delivery boy? Not today.}

{357}{}{Excellent! The courier's name is Milo. He's from Gerlach, so I'd start looking there. Ask around and see if anyone knows anything.}
{358}{}{I have more questions about this job.}
{359}{}{I'll see what I can do.}

#Delivery - questions
{360}{}{Ask away.}
{361}{}{[Sighs] I heard Evan had an accident. That's bad news, but the package should still be on its way.}
{362}{}{Tell me more about this courier.}
{363}{}{The name's Milo. He lives in Gerlach, but makes deliveries here. Not a lot to say about him - quiet, professional... That's about it. Pretty much what a courier should be.}
{364}{}{What was he delivering?}
{365}{}{Gecko pelts from Evan. Before you ask - yes, we got our own hunters, but Evan is a real master. His skins are better than anyone else's in these parts.}
{366}{}{Tell me about Gerlach.}
{367}{}{It's to the west from here. A small settlement, kind of like ours - though a hell of a lot more strict. It's named after its founder, Mr. Gerlach. He's still in charge, from what I hear.}
{368}{}{What's my reward?}
{369}{}{Look, I get that you want a reward for this, but a man's life is at stake here! Find him first, then we'll talk about payment, alright?}
{370}{}{Okay, I'll go look for him.}

{371}{}{Still can't find an elephant in the desert? Sorry, bad joke.}
{372}{}{I found the courier... Or rather, what's left of him.}
{373}{}{He's dead? Damn, poor Milo. What happened?}
{374}{}{Hit on the head with a shovel, that's what happened. He was murdered by Eugene and the Molerats gang.}
{375}{}{He was, uh, eaten by geckos. Bob and I already buried him.}

{376}{}{You already told me about that. Wanna say something new?}
{377}{}{Actually, I lied before.}
{378}{}{No, nothing.}

{379}{}{Milo was a good man - too good to go down like that. I hope his wife is holding up alright. [he sighs] Well, thanks for lettin' me know. Here's a hundred bucks. I'd love to give you more, but without Milo's delivery I'm gonna be pretty lean on cash for a little while. Sorry.}
{380}{}{At least it's something.}
{381}{}{What do you mean?}
{382}{}{Milo has been murdered by Eugene and the Molerats gang. Killed with a shovel.}
{383}{}{I'm going to gather more evidence and come back. See you.}

{384}{}{Oh my god! I had no idea! Look, we can't waste any time, let's go talk to Justin and Eugene right now.}
{385}{}{If you're so sure about that... }
{386}{}{[After a huge scandal, you and William return to the bar] That fucking family, I swear! One day I'm gonna... Look, forget about them for now. We have a caravan from Reno on the way, and Eugene's gang is planning an ambush. They must be stopped, but we can't do it alone. There's maybe something we might do though... }
{387}{}{What can we do to save the caravan?}

{388}{}{I took Eugene's walkie-talkie. Here. If you can get the right frequency, you can overhear these bastards talking about their plans and warn the caravan. The range is quite short, so you'll have to be quick and careful.}
{389}{}{Hey, I never said I want to be a part of this!}
{390}{}{I'll do my best.}

{391}{}{I'm not asking you to fight them! Just warn the caravan before the gang gets to them. No one but you can do it. We'll discuss your reward later.}
{392}{}{I'll think about it.}
{393}{}{I'm going. I'll be back as soon as I can.}
{394}{}{I managed to beat the code names and frequencies of the Molerats out of Eugene. Take them. You can eavesdrop on their conversations and warn the caravan. The range isn't great, so be quick and careful. Good luck.}

#Final converstaion about saved caravan
{395}{}{Hey, it's you! The caravan merchants told me everything! You're a goddamn miracle worker, you know that?! Great job!}
{396}{}{Such kind words would go perfectly with a reward.}
{397}{}{I'm glad I could help.}
{398}{}{You're not even asking for a reward? That's noble! Look, from now on you get a 20% discount on my goods. You're welcomed here any time, remember that!}
{399}{}{You know, you could give me something more for my troubles... }
{400}{}{Thanks for the discount. I wish you the best!}
{401}{}{Without pelts from Evan, I don't have much. I can give you two hundred bucks and a 20% discount in my eatery. Keep it in mind when nearby!}
{402}{}{What if you give me that old energy pistol instead?}
{403}{}{I need money. Give me all you can.}
{404}{}{Keep the money, I don't need it.}

{405}{}{You already bought it, remember? Do you think I have two? Well, sorry, but I don't.}
{406}{}{Take care.}
{407}{}{Now that's a damn fine idea. Who else would want this piece of junk around here? Take it and enjoy.}
{408}{}{That's all I can do. Sorry it's not much.}
{409}{}{Well, at least it's something. Take care!}
{410}{}{I knew you'd say that! Heroes don't need money, right? Okay, okay, that's a joke. But I'm serious about that discount!}
{411}{}{I will remember that. Now I have to go.}

{412}{}{Well, that's it. The caravan's not coming. All my efforts were for nothing. [He sighs] Maybe Justin was right.}
{413}{}{Maybe you'll learn something from this. Don't trust anyone. I'll be on my way.}
{414}{}{I don't care, this is your problem.}
{415}{}{Yeah... Yeah. But we tried, right?}
{416}{}{Right. I came for business.}
{417}{}{Whatever. I have to go.}

{420}{}{Oh, yeah... Here's a hundred bucks for finding Milo. I'm sorry it's not much, but without pelts from Evan I don't have much to spare.}
{421}{}{Fine.}

###########################################################################
#
#    Pop-ups - wasteland news
#
###########################################################################

#Starting onws
{500}{}{News? Let me think.}
{501}{}{Well, what's new?}
{502}{}{Let's see, what else is new... }
{503}{}{A traveler told me something yesterday... }
{504}{}{I've got news from the wasteland! Who wants to hear?}
{505}{}{The scariest thing in the desert is sandstorms.}
{506}{}{We need some better booze up in here... }
{507}{}{That iguana-hunting wanderer's been missing for a while. We should look for him.}

#Raiders destiny
{510}{}{Finally, someone's brought the Molerats to justice!}
{511}{}{We won't have to worry about the Molerats anymore.}
{512}{}{It's about time someone took care of those Molerats.}

{513}{}{That damn Molerats. It's only going to get worse.}
{514}{}{After what they did to the caravan, the Molerats are capable of anything.}

{516}{}{The Molerats still control the south of our valley.}
{517}{}{Some say there's not much left of the Molerats, but they're still dangerous.}

#Cheyenne's
{520}{}{They say the Cheyenne won't last long. Soon they will be just a memory.}
{521}{}{If Big Louie's Dogs beat the Cheyenne, what will they do to us?}
{522}{}{We'd have more caravans around here if not for Big Louie's Dogs.}
{523}{}{It's a good idea to steer clear of the Cheyenne these days.}
{524}{}{If you don't like raiders, give Lovelock a wide berth.}
{525}{}{Who wanted to go to Cheyenne here? You might want to rethink that. The raiders have gone completely berserk.}

{526}{}{Who wanted to go to Cheyenne? Good news, the raiders are no longer a problem!}
{527}{}{Finally, Big Louie's Dogs are dead. That should make the roads a lot safer.}
{528}{}{Lovelock is a lot more peaceful with Big Louie out of the picture.}

#About Gerlach
{529}{}{They say Gerlach's still going strong. That guy is tough!}
{530}{}{Anyone heading to our neighbors to the west?}

{531}{}{Gerlach... It's sad to hear that our neighbors are gone.}
{532}{}{Gerlach's gone real quiet. There's something shady going on, if you ask me.}
{533}{}{Gerlach's practically abandoned. Everyone went somewhere else, but no one knows where.}

#Stagecoach quest in Reno
{540}{}{Did you hear about the "Nevada Express" incident? Don't come near the place - it's very dangerous!}
{541}{}{I didn't think anyone could attack the "Nevada Express" and win.}
{542}{}{I wouldn't be surprised if the "Nevada Express" was set up.}

#About Reno in general
{550}{}{They say Reno's pretty unsettled now. But then, when wasn't it?}
{551}{}{Better stay away from Reno. There's some real shit going on, as I hear.}
{552}{}{They say Reno hasn't been this bad since the war.}

{553}{}{They say Reno's really settled down lately. Maybe we should go back?}
{554}{}{It sounds like Reno is finally getting better.}
{555}{}{I heard the gang war in Reno is finally over!}

#About the Oasis City
{560}{}{A traveler told me there's some sort of oasis in the mountains. Interesting.}
{561}{}{You get some really crazy stories in here. How could there be a city up north in the mountains?}
{562}{}{They say there is a city in the mountains, like the ones before the war. That can't be true.}
{563}{}{Did you hear about that Oasis City, where everyone wears blue jumpsuits? Yeah, I don't believe that either.}

#Local stuff
{570}{}{Did anyone catch Mike's fight? It must have been a hell of a show!}
{571}{}{Bob says someone's been digging up the graves. I'm worried about him... }

{572}{}{Fugitive slaves? So? They are people too! Just give them a chance!}
{573}{}{Fugitive slaves? Well, there is not much to talk about now.}

{574}{}{Yeah, that brahmin situation was awkward.}

###########################################################################

#Female character
{1116}{}{Hey, friend! So happy to see ya!}
{1261}{}{I've sent them away. They would have brought slavers here.}
{1271}{}{Thank you for your deep understanding of the situation, it's much appreciated. Have a sandwich - you must be hungry after all that running around.}
{1278}{}{Thanks for doing such a good job. Take a sandwich and a beer - you must be hungry after all that running around.}
{1376}{}{You already told me about that. Wanna say something new?}
{1377}{}{Actually, I lied before.}
{1389}{}{Hey, I never said I want to be a part of this!}
{1397}{}{I'm glad I could help.}
{1405}{}{You already bought it, remember? Do you think I have two? Well, sorry, but I don't.}
{1407}{}{Now that's a damn fine idea. Who else would want this piece of junk around here? Take it and enjoy.}
