{100}{}{You see a young boy.}
{101}{}{You see a cute young boy. He stinks of manure.}

{110}{}{Yes, sir?}
{111}{}{I'm just passing by.}

#Missing brahmin
{120}{}{Your father asked me to look for a missing brahmin. What can you say in your defense?}
{121}{}{Let's talk about the missing brahmin.}
{122}{}{I didn't do anything wrong! Really! It's like she never existed - she was here in the night and gone in the morning! She just disappeared! I'm telling the truth!}

{123}{}{What the brahmin looked like?}
{124}{}{Like any normal brahmin. Four hoofs, two heads, one tail... And smelly...}
{125}{}{Where did you last see it?}
{126}{}{She was right there, in that corner! And in the morning, she was gone! Just disappeared!}
{127}{}{Was anyone else around that night?}
{128}{}{No! I'm sure! Because... Because I didn't sleep, and I tied the gate shut with a special knot! If someone unties the rope, I'll know, because they won't tie it in the same way! No one could have taken it! Even the toilet and that lady from Reno aren't close enough to steal brahmin without me seeing!}
{129}{}{Look, kid, I can tell you're lying to me. Tell me the truth, or else.}
{130}{}{You... You won't tell my father, will you? I fell asleep... I'm sorry! I don't usually sleep in the night! But as soon as I drank some water, I just... I don't know! I don't even remember feeling tired, but I didn't wake up until morning. And then the brahmin was gone! It must have been some kind of... Of radiation, or a brahmin-stealing mutant with special powers!}
{131}{}{It's a mystery, all right.}

{132}{}{You'll find it, right? My father will be mad if you don't!}
{133}{}{Maybe, maybe not. I might get lucky.}
{134}{}{I'll do everything I can.}
{135}{}{I told you everything! Honest!}
{136}{}{Fine, wait here.}

{140}{}{Did anyone come by with a shotgun that night?}
{141}{}{I didn't see anyone, but... People come by the toilet all the time. I don't remember, too many of them.}
{142}{}{Right. I'll continue to search for a man with a shotgun then...}

#Questioning
{152}{}{I just want to ask you something.}
{153}{}{What?}
{154}{}{Nothing.}
{155}{}{What are you doing here?}
{156}{}{What are those animals?}
{157}{}{What can you tell me about Black Rock?}
{158}{}{That's enough.}

{159}{}{My father made this corral a couple of years ago, and my job is to watch the brahmin so nobody steals them!}
{160}{}{[He looks incredulous] You don't know what a brahmin is?! I didn't know that was possible! Well... They are animals. We grow them, then slaughter them, and my father makes the meat soup out of them. It's really good!}
{161}{}{I live here! I've never been anywhere else, except for Gerlach one time, and it doesn't really count because I didn't talk to anyone.}
{162}{}{Gerlach?}
{163}{}{Yeah. It's that way. [he points to the west]}
{164}{}{Don't you get bored here?}
{165}{}{Yeah, it's REALLY boring. Sometimes I just want to leave and go home, but my father won't let me. But when the brahmin are sleeping, at night, you can play with them. You sneak up quietly and hit them in the belly, then run away! And then they look around like "Wha??? What's going on???" Hahahaha!}

#Female character
{1110}{}{Yes, ma'am?}
