{100}{}{You see a generator.}

{101}{}{The generator is in power saving mode. You can restore normal mode for a short time.}
{102}{}{The generator is operational. The power supply is fully restored.}

{103}{}{Watts Electronics generators use a different power source.}
{104}{}{Generator is operational.}
{105}{}{You restore the generator's operating mode. The radar station power supply is restored.}
{106}{}{[Done]}
{107}{}{This is no longer required.}
