{100}{}{Hey, kid, what the fuck do you want there?!}
{101}{}{It's locked - but you can't see any locks.}
{102}{}{The gate does not have a visible lock. Perhaps is can be opened differently.}
{103}{}{The door is trapped.}
{104}{}{It does nothing.}
{105}{}{The gate is broken.}
{106}{}{There's no keyhole. Strange. Maybe it works differently?}
{107}{}{The gate opens somehow differently, skills are useless here.}
