{100}{}{You see a terminal.}
{101}{}{You see a working terminal.}

{102}{}{The computer does not turn on. Apparently it doesn't have enough power.}
{103}{}{[Shutdown]}
{104}{}{All indicators on the terminal light up, then go out, and the main monitor turns on. It's amazing that this thing still works.}
{105}{}{[Follow the tracker signal from the Overseer's Pip-Boy]}
{106}{}{[Check the radio]}
{107}{}{You only hear "white noise".}

{110}{}{There's a signal! The green dot is near Salt Lake City, moving quickly to the northeast. You won't be able to catch up with the kidnappers even with a car. The signal will soon be out of radar range.}
{111}{}{Looks like you'll have to find some kind of railroad transport to chase them. Maybe there's something in Salt Lake City?}
