{100}{}{You see a terminal.}
{101}{}{You see a working terminal.}

{102}{}{The computer does not turn on. Apparently it doesn't have enough power.}
{103}{}{[Shutdown]}
{104}{}{All the lights on the terminal light up, then they go out and the main monitor turns on. It's amazing how well this tech still works.}
{105}{}{[Follow the tracker signal from Overseer's Pip-Boy]}
{106}{}{[Check radio]}
{107}{}{You only hear "white noise".}

{110}{}{There's a signal! The green dot is quickly moving to the northeast of Salt Lake. You will not be able to catch up with the kidnappers even using a car. The signal will soon be out of radar range.}
{111}{}{Looks like you'll have to find some kind of railroad transport to chase them. Maybe there's something suitable in Salt Lake?}
