{100}{}{Not surprisingly, the brahmin is as dead as when you last saw him.}
{101}{}{You've found the missing brahmin - or, rather, what's left of it. Nothing remained, but the head and the hooves. They already stink of rot.}
{102}{}{[Examine carefully]}
{103}{}{Enduring the nauseating stench, you discover that both skulls have jagged holes ringed with gunshot marks. Inside the skulls are pieces of nails, probably from homemade shotgun cartridges.}
{104}{}{Interesting...}
