{100}{}{You see a client.}
{101}{}{You see Madison.}

#О'ладка
{105}{}{Ave, goddess!}
{106}{}{You come with me, asshole.}
{107}{}{Stay here, moron.}

#######################################################
#
#           Диалог - наличие в команде
#
#######################################################

#======================================================
# Когда с'ои' и жде' героиню
#======================================================

{110}{}{Oh! My baby came back for me! I knew it, that you need me! Where shall we go this time? Maybe, to my home?}
{111}{}{Come on, I need you.}
{112}{}{Never mind.}

#======================================================
# Когда ходи' за героиней - первая диалоговая ве'ка
#======================================================

{120}{}{What do you want, baby?}
{121}{}{Anything you want, beautiful!}
{122}{}{Well, what an old fart can do for a such a little girl like you?}
{123}{}{Hey, you know who to call when you need to! Yes, I'm your man.}
{124}{}{I can't wait, when you're going to say it.}
{125}{}{Come on! Make up your mind! Tell me you want *that*?}
{126}{}{Oh, I'm sorry for the stains on the pants... Will try harder to conceal them.}
{127}{}{What? Want it harder?}
{128}{}{[Looks at you and pulls his hands out of his pockets] Oh, uh... It all right. Honestly.}
{129}{}{[Hums something about last kiss] ...Oh, sorry, got distracted again.}

{130}{}{Let's chat.}
{131}{}{Let's change the distance between us.}
{132}{}{Hide you weapon away.}
{133}{}{Take off your armor.}
{134}{}{Stay here and wait for me.}
{135}{}{Tell me about your weapon skills.}
{136}{}{}
{137}{}{}

{138}{}{Anything you wish, baby!}
{139}{}{Great.}

#Удержание дис'анции:
{140}{}{Oh, my baby wants to be closer! I've been waiting for this...}
{141}{}{Stay away from me as far as possible, maniac.}
{142}{}{Stay at a medium distance.}
{143}{}{Stay close, honey.}
{144}{}{I think this distance is enough.}

{145}{}{Ah! Okay, okay... I will stay away. But will see who will last longer!}
{146}{}{Not a good start for our relationship, baby. Believe me, I know it.}
{147}{}{Ow! Baby, you're driving me crazy! I'll be a human shield for your firm butt!}

{148}{}{Oh! Baby, I can even dance striptease! Just say a word!}
{149}{}{Uh... Not today, Playboy. The armor is enough.}

#Освобождение персонажа:
{150}{}{Oh, no! [grabs his head] Has this day has come!? }
{151}{}{Yes, you dog, I dump you. Forever.}
{152}{}{Calm down, just wait for me, I'll be right back.}
{153}{}{Well, okay, you can stay. I'll tolerate your arrogant mug some more.}

{154}{}{Phew! [defiantly grabs his heart] Oh! How my heart is relieved!}
{155}{}{Oh, well, well.}
{156}{}{Okay! Well!!! The old dog will have to wait... As always. Uh... But you're coming back are you? You won't leave this faithful servant here right?}
{157}{}{You just wait.}
{158}{}{NO! NOOO!!! How could I! How could I leave my pussycat without attention and care! I'll be punished! I'm going to hell! But just give me one more chance! Please! I'm all yours!}
{159}{}{Just wait, you moron. I'll be back.}
{160}{}{Yes! YES, dear, I don't need you. Go away and don't come back!}
{161}{}{Oh, those words cut me to pieces! What a pain! Mmm... WHAT a PAIN!!! [squeals] I can't STAND it! I'll kill myself!}
{162}{}{What do I care...}
{163}{}{[Breathing heavily, grabs his chest] What an idiot I am! Well, I'll wait... I hope that you come back... I believe it will happen! Believe me, I'll be good! Honestly!}
{164}{}{Wait, as long as you want to.}

{165}{}{For you would master anything. But except the shotgun and a revolver never had to use anything else.}
{166}{}{Ok.}


#######################################################
#
#                  Расспросы
#
#######################################################

#О'ве'ы напарника на просьбу побол'а'ь:

{200}{}{Again? Don't you want to go straight to the fun?}
{201}{}{I saw in a store those rubber things... If you that is what you mean.}
{202}{}{Oh, yeah, let's see, where to settle down...}
{203}{}{I suggest in position 26.}
{204}{}{Oh, itching, right? [smiling]}
{205}{}{Well, of course! Mature a little, right?}
{206}{}{I feel the most desired thing is coming!}
{207}{}{I've waited so long! Tell me, how shall we do it?}
{208}{}{How you prefer - with a beer or on an empty stomach?}
{209}{}{I'm not talking about that, you fool, don't get excited ahead of time.}

#Список вопросов:

{210}{}{Damn, as always...}
{211}{}{What do you know about this place?}
{212}{}{Look at my backpack, see something familiar?}
{213}{}{Who can make poison in Reno?}
{214}{}{Do you know who is Oliver?}
{215}{}{}
{216}{}{}
{217}{}{}
{218}{}{}
{219}{}{Okay, enough talking.}
{220}{}{Another question.}
{221}{}{This is enough for today.}

{230}{}{Oh, you're really dangerous, baby! I don't envy the one that you decided to kill. OK, I know where to do it. Striker, he lives in bowling stadium. Local gangster and manufacturer of drugs. Recommend.}
{231}{}{What else?}

#Про города и кар'ы:
{300}{}{Wasteland. Just a Wasteland.}
{301}{}{Wasteland. Just a Wasteland.}
{302}{}{Wasteland. Just a Wasteland.}
{303}{}{Huh? And where am I? Oh, sorry, I was did too many pills and now I hallucinated about some beautiful city... Oh what a beautiful hallucination!}
{304}{}{Huh? And where am I? Oh, sorry, I was did too many pills and now I hallucinated about some beautiful city... Oh what a beautiful hallucination!}
{305}{}{Desert and the railroad. What else you want to know my curious one? Oh, there's a hut of some sort, certainly it has a bed...}
{306}{}{Never been here before, but heard about it. They say that the local military have not seen a female body in a long... Oops, I shouldn't have said.}
{307}{}{Some dirty bunker. Yes, I am a lover of exotic places to receive oral pleasure in, but not in such a dirty place.}
{308}{}{Ruins, ruins, ruins everywhere. Hey, looks like we're not alone!}
{309}{}{MAP_KLAMATH_1}
{310}{}{MAP_KLAMATH_MALL}
{311}{}{MAP_KLAMATH_RATCAVES}
{312}{}{Baby, it's a perfect place for lovers of brahmin ass. But I prefer the other kind of asses.}
{313}{}{MAP_KLAMATH_TRAPCAVES}
{314}{}{MAP_KLAMATH_GRAZE}
{315}{}{MAP_VAULTCITY_COURTYARD}
{316}{}{MAP_VAULTCITY_DOWNTOWN}
{317}{}{MAP_VAULTCITY_COUNCIL}
{318}{}{Savages? The baby wants exotics? Ah, I can relate - pure nature and no drugs, I guess they do *it* long and voluptuous.}
{319}{}{[Looks around] I remember, just like in the good old days, before I broke in New Reno. Let's move - local rough stuff even for such a dangerous girl will be hard to survive through, believe me.}
{320}{}{MAP_SHAIEM_RAIDERS_BASA}
{321}{}{Dark, damp, quiet, cool... A great place to dance on the mattress.}
{322}{}{MAP_MODOC_DOWNTHESHITTER}
{323}{}{MAP_HOWTHORNE_POLIGON}
{324}{}{MAP_BATTL_OWL}
{325}{}{MAP_BATTL_BAIKERS}
{326}{}{MAP_GHOST_LAKE}
{327}{}{MAP_ZONA51_Toplivo}
{328}{}{MAP_ZONA51_KASARMS}
{329}{}{MAP_ZONA51_ANGAR}
{330}{}{MAP_VAULT_8_DESTROYVAULT}
{331}{}{MAP_GECKO_SETTLEMENT}
{332}{}{MAP_GECKO_POWER_PLANT}
{333}{}{MAP_GECKO_JUNKYARD}
{334}{}{MAP_GECKO_ACCESS_TUNNELS}
{335}{}{MAP_VAULT_8_CITY_DESTROY}
{336}{}{MAP_VAULT_15}
{337}{}{MAP_THE_SQUAT_A}
{338}{}{MAP_THE_SQUAT_B}
{339}{}{MAP_VAULT_15_EAST_ENTRANCE}
{340}{}{MAP_VAULT_13}
{341}{}{MAP_VAULT_13_ENTRANCE}
{342}{}{MAP_VEGAS_STRIP}
{343}{}{MAP_VEGAS_HARD_ROCK}
{344}{}{MAP_VEGAS_SLAVERTOWN}
{345}{}{MAP_VEGAS_GHOULTOWN}
{346}{}{MAP_VEGAS_SIGN}
{347}{}{MAP_VEGAS_DAMBA}
{348}{}{MAP_KLAMATH_CANYON}
{349}{}{MAP_HOWTHORNE_DEPOTS}
{350}{}{MAP_HOWTHORNE_TRAIN_DEPO}
{351}{}{I don't know what we're doing here, but I would prefer to do it in the hotel "Silver" in the sixth room.}
{352}{}{MAP_DEN_SLAVE_RUN}
{353}{}{MAP_CAR_DESERT}
{354}{}{MAP_RENO_SILVER}
{355}{}{MAP_RENO_ELDORADO}
{356}{}{MAP_RENO_BILLRD}
{357}{}{MAP_RENO_TRAINDEPO}
{358}{}{MAP_RENO_OLIVER}
{359}{}{MAP_PEPGAZ}
{360}{}{MAP_VEGAS_STABLES}
{361}{}{Oh, baby! Baby! Now I'm not going out of here, even for someone's ass. Hey, dwarf, five bucks for that one from Wendover! Five bucks!!!}
{362}{}{MAP_REDDING_WANAMINGO_ENT}
{363}{}{MAP_REDDING_WANAMINGO_12}
{364}{}{MAP_REDDING_WANAMINGO_12}
{365}{}{MAP_REDDING_MINE_ENT}
{366}{}{MAP_REDDING_DTOWN_TUNNEL}
{367}{}{MAP_REDDING_MINE_TUNNEL}
{368}{}{Ruins. Just ruins.}
{369}{}{Wasteland. Just a Wasteland.}
{370}{}{Wasteland. Just a Wasteland.}
{371}{}{Wasteland. Just a Wasteland.}
{372}{}{Wasteland. Just a Wasteland.}
{373}{}{Wasteland. Just a Wasteland.}
{374}{}{Wasteland. Just a Wasteland.}
{375}{}{Wasteland. Just a Wasteland.}
{376}{}{Wasteland. Just a Wasteland.}
{377}{}{Wasteland. Just a Wasteland.}
{378}{}{MAP_BROKEN_HILLS1}
{379}{}{MAP_BROKEN_HILLS2}
{380}{}{Wasteland. Just a Wasteland.}
{381}{}{Wasteland. Just a Wasteland.}
{382}{}{Wasteland. Just a Wasteland.}
{383}{}{Wasteland. Just a Wasteland.}
{384}{}{Wasteland. Just a Wasteland.}
{385}{}{Wasteland. Just a Wasteland.}
{386}{}{Wasteland. Just a Wasteland.}
{387}{}{Wasteland. Just a Wasteland.}
{388}{}{Wasteland. Just a Wasteland.}
{389}{}{Wasteland. Just a Wasteland.}
{390}{}{Wasteland. Just a Wasteland.}
{391}{}{Wasteland. Just a Wasteland.}
{392}{}{MAP_RAIDERS_CAMP1}
{393}{}{MAP_RAIDERS_CAMP2}
{394}{}{Wasteland. Just a Wasteland.}
{395}{}{Wasteland. Just a Wasteland.}
{396}{}{MAP_SPECIAL_RND_WHALE}
{397}{}{This opening reminds me of something. I've seen it somewhere before.}
{398}{}{Watch your feet, baby, I would not want to collect such a beauty as you piece by piece.}
{399}{}{Wasteland. Just a Wasteland. Somehow highlighted.}
{400}{}{Wasteland. Just a Wasteland. And some beautiful building. Probably there inside of elegant bed and a telephone to order corporate striptease.}
{401}{}{MAP_SPECIAL_RND_BRIDGE}
{402}{}{Oh, this is some sort of cafe?. Want to go in have some fun?}
{403}{}{MAP_SPECIAL_RND_HOLY1}
{404}{}{MAP_SPECIAL_RND_HOLY2}
{405}{}{MAP_SPECIAL_RND_GUARDIAN}
{406}{}{Wasteland. Just A Wasteland.}
{407}{}{MAP_SPECIAL_RND_PARIAH}
{408}{}{MAP_SPECIAL_RND_MAD_COW}
{409}{}{MAP_NAVARRO_ENTRANCE}
{410}{}{Wasteland. Just a Wasteland.}
{411}{}{Wasteland. Just a Wasteland.}
{412}{}{Wasteland. Just a Wasteland.}
{413}{}{Wasteland. Just a Wasteland.}
{414}{}{Wasteland. Just a Wasteland.}
{415}{}{Wasteland. Just a Wasteland.}
{416}{}{Wasteland. Just a Wasteland.}
{417}{}{Wasteland. Just a Wasteland.}
{418}{}{Wasteland. Just a Wasteland.}
{419}{}{Wasteland. Just a Wasteland.}
{420}{}{Wasteland. Just a Wasteland.}
{421}{}{Wasteland. Just a Wasteland.}
{422}{}{Wasteland. Just a Wasteland.}
{423}{}{Wasteland. Just a Wasteland.}
{424}{}{Wasteland. Just a Wasteland.}
{425}{}{Ruins. Just ruins.}
{426}{}{Wasteland. Just A Wasteland.}
{427}{}{Ruins. Just ruins.}
{428}{}{Gorgeous place. Fresh beds, clean water and a lot of free donuts from the machine. How about stop and relax in the double beds?}
{429}{}{Mountains and cold wind. We have nothing to do here.}
{430}{}{Why is it so dark? How will we find each other... That is, I wanted to say on each other.}
{431}{}{Wasteland. Just A Wasteland. Somewhere not far from Salt Lake. I can't wait to get to the soft beds in "the Sixth bullet"...}
{432}{}{Baby, you know better what to do. Honestly. I just follow.}
{433}{}{Never mind. Some dirty rogues from Reno migrated here and admire brahmin ass in the evenings.}
{434}{}{MAP_ENCLAVE_TRAP_ROOM}
{435}{}{MAP_SALT_TRAIN}
{436}{}{Some retarded residential area, beautiful. Can't we find a place to sleep that is more solid?}
{437}{}{Salt Lake City, the most fucked up town in the Wasteland, but a place you with one bed will be provided to us for sure.}
{438}{}{Whew! While you are here to solve all your big tasks, I'll stand here and look at your body.}
{439}{}{Some church... Hey, how about marriage?}
{440}{}{The Slums. It's so wild and exciting...}
{441}{}{Ruins. Just ruins.}
{442}{}{Ruins. Just ruins.}
{443}{}{Ruins. Just ruins.}
{444}{}{Ruins. Just ruins.}
{445}{}{Ruins. Just ruins.}
{446}{}{Ruins. Just ruins.}
{447}{}{Ruins. Just ruins.}
{448}{}{Great. Never thought I would ever see this manufacturer of the universal urine, which eclipsed all trade in the Wastes.}
{449}{}{Wasteland. Just A Wasteland.}

#######################################################
#
#                  Плавающие фразы
#
#######################################################

#======================================================
# Плавающие фразы при попы'ке 'олкну'ь
#======================================================

{1000}{}{Here?}
{1001}{}{That's better, pussycat?}
{1002}{}{What about here?}
{1003}{}{Yes, kitty.}
{1004}{}{What?}
{1005}{}{Where are we going?}
{1006}{}{We're leaving, honey?}
{1007}{}{I go where you say}
{1008}{}{Sorry, honey.}
{1009}{}{Better?}
{1010}{}{Uh...}
{1011}{}{Well, how am I in this light?}
{1012}{}{Are you taking me on stage?}
{1013}{}{I'll just go here.}

#А'ака на героя
{1020}{}{I think I've had enough!}

#======================================================
# Таймерные рэндомные фразы
#======================================================

#Когда не здоров:
{1100}{}{Oh my goddess, have mercy! I don't feel good!}
{1101}{}{I need a doctor, baby.}
{1102}{}{Oh, boy. Ow, that hurt.}
{1103}{}{Ow!}
{1104}{}{Oh...}
{1105}{}{Damn...}
{1106}{}{Doctor?}
{1107}{}{Holding on... Barely...}
{1108}{}{Soon I will be dead...}

#Когда ГГ ос'авила напарника о'дыха'ь:
{1200}{}{Oh La La...}
{1201}{}{Very well}
{1202}{}{I wait my beauty...}
{1203}{}{I'm waiting on my goddess}
{1204}{}{Just waiting for her}
{1205}{}{She won't cheat on me that's for sure...}
{1206}{}{Oh, these women's stuff...}
{1207}{}{Women are like that - you always have to wait}
{1208}{}{She's is shopping again...}
{1209}{}{That, again, carry this stuff?}
{1210}{}{Hey, I'm here! And I'm bored!}
{1211}{}{They always are like this, always have to wait for them.}
{1212}{}{Uh... Well, I at least have Cola, I'm too exhausted.}
{1213}{}{I need to lay off the women... Nothing but trouble from them}
{1214}{}{I'd rather watched a fight in the ring in "Eldorado"}
{1215}{}{So what? There won't be sex?}

#======================================================
# Использование предме'ов на напарнике
#======================================================

#С'имуля'ор или вода
{1300}{}{Whew! My rocket again fueled and ready for action!}
{1301}{}{Now I am full of energy for a scene on the mattress.}
{1302}{}{That's right!}
{1303}{}{Great, now I'm in line}
{1304}{}{About time}
{1305}{}{And I really thought that was my end}
{1306}{}{Ah so good!}

#Другие медикамен'ы
{1310}{}{You're right - I don't want to vomit}
{1311}{}{That stink so much of smoke from the mouth? Hell...}
{1312}{}{Oh, the famous "furious"! A hundred years have not seen.}
{1313}{}{Not so fast, dearest. If we die, we do it together!}
{1314}{}{Oh, right, baby values me too much}
{1315}{}{Well, I'm not a fan of candies, but they say with it...}
{1316}{}{I will never say no to a glass of bloody Mary!}
{1317}{}{This stuff I just will not eat! Yes, I for you.}
{1318}{}{What is this shit? Well, if we have nothing else...}
{1319}{}{Just like in the good old days when I was held in the... Uh, doesn't matter}
{1320}{}{Just like before. I remember Doc Gray with his experiments on... Well, forget it.}

#Иные предме'ы
{1330}{}{Uh, thanks, honey.}
{1331}{}{Thanks}
{1332}{}{Baby, you know what you are doing?}
{1333}{}{Can't we just slee... Rest?}
{1334}{}{Maybe we just sleep together?}
{1335}{}{What, I got the worst of it?}
{1336}{}{Not too helpful.}
{1337}{}{Well, if you insist, my goddess.}
{1338}{}{Beautiful, my head won't explode, right?}
{1339}{}{Looks like it's starting to grow on me.}
{1340}{}{I feel a bit strange.}
{1341}{}{Uh, sure you don't want to? Why don't you try it?}
{1342}{}{Sure, baby. I'll take some.}
{1343}{}{Thanks, kitty}
{1344}{}{Not bad}

#О'ве'ы про инвен'арь:
{1998}{}{[Looks at the object}
{1999}{}{] }
{2000}{}{Nothing interesting. I've seen those rubber things in the store near the "Silver legacy"...}

{2053}{}{A real rarity. They say, it not just heals, but also strengthens the immunity.}
{2097}{}{Hmm, yeah you test my observation, baby! Of course, I can see that this must be placed somewhere.}
{2120}{}{Effortless power and brutality. The real gold amongst all the shit that can be found in the Wasteland. The only minus is the heavy barrel. However, there are technicians that could give it a fix.}
{2164}{}{Familiar! Recognize the work of Striker. However, many brake on this stuff in the ring. You're not going to try it, right?}
{2222}{}{It glows? Baby, these things are valued simply for what they are.}
{2237}{}{Newspapers? Well, you don't want to force me to read it do you? Okay... Advertising "Pretty & Glamour" I've heard it before. Yes that's right, vending machine in "Silver Legacy".}
{2239}{}{Little weak. Honestly.}
{2255}{}{I can say - only a nerd botanist can fix this.}
{2278}{}{Mickey... Same horny male, just like me.}
{2281}{}{Well, ok. Come on, baby, I won't tell anyone how many locks were unable to stand under your sensitive fingers.}
{2301}{}{This is from the company 'Pretty & Glamour'. There is a vending machine in "Silver Legacy" hotel... Hey wait, are you trying to tell me I stink?}
{2310}{}{The only thing in this world that with time only gets better.}
{2311}{}{These poor people in Salt Lake are alive only thanks to vocas. A handful in your mouth and consider your problem solved with radiation.}
{2324}{}{An expensive thing. As we reach the well, try it.}
{2333}{}{You think in the wasteland there are those who need it?}
{2337}{}{Famous pre-war drug, which improves your mental abilities. You're not going to try it? Smart girls is like a trap in the dark forest.}
{2388}{}{Hmm, I remember around the Salt Lake they saw geckos, spitting acid.}
{2413}{}{And I remember her! Worked in a strip club. real hottie, but after Ted Bundy he was gone. I bet a hundred coins on that she ran away to another city.}
{2417}{}{Like a helmet from power armor. But of course it's not... Well, I seen them in a magazine.}
{2430}{}{Ehh, if we could shoot some aliens in Area 51 with this, huh?!}
{2433}{}{Effective! You are desired without it, but in the cap you just Magadesired!}
{2441}{}{Hey, it has the name of the owner here. Although, what do we care, right?}
{2471}{}{Some nutty professor wrote this. You don't want to be the same are you? And yet, in a doctor's coat and a miniskirt you'd be quite sexy.}
{2499}{}{There was one nerd who was pushing this poison from a warehouse around Reno. I once ate a little and almost died. After a couple of broken bones never saw that asshole again.}
{2516}{}{'Pretty & Glamour' collection!? Oh, now you can forget about feminine odor.}
{2525}{}{Oh, the famous "furious"! Remember. There was a scientist in Reno who developed the methamphetamine lab, but then it was finished by the junkies, which he himself tamed to this stuff. I do not advise to even try it.}
{2551}{}{Oh come on!}
{2552}{}{The main thing is - not to abuse it.}
{2554}{}{Almost like a regular coin to the touch and cannot be distinguished.}
{2556}{}{Is this an emulator of a dick? I mean, my too small? Hell, I will have to do augmentation.}
{2557}{}{This is an emulator of a dick? I mean, my too small? Hell, I will have to do augmentation.}
{2558}{}{Th-that's not m-mine! Honestly! Yes, I would have that man killed, if I saw him... Maybe...}
{2560}{}{Rare thing. But you're not going to carry this on you? In the vault suit you look sexier!}
{2561}{}{Rare thing. But you're not going to carry this on you? In the vault suit you look sexier!}
{2562}{}{Again junk from 'Pretty & Glamour'...}
{2563}{}{Again junk from 'Pretty & Glamour'...}
{2564}{}{Again junk from 'Pretty & Glamour'...}
{2565}{}{I saw this in California. That was long time ago.}
{2566}{}{Again junk from 'Pretty & Glamour'...}
{2573}{}{You're a fan of the extreme kind of pleasure!}
{2577}{}{Again junk from 'Pretty & Glamour'...}
{2593}{}{Uh, look, this Hal Wallace, must be, a sensible man. I'd work for him. But hardly I can pull it off.}
{2595}{}{Uh, look, this Hal Wallace, must be, a sensible man. I'd work for him. But hardly I can pull it off.}
{2596}{}{You now have the hots for corrupt Mexicans cops? Almost extreme!}
{2597}{}{Surely, this Deputy did not get any time in the crotch.}
{2626}{}{Lucky! Good weapons and rare ammo. Under other circumstances, you would not be able to find it.}
{2627}{}{Lucky! Great gun and rare ammunition. Under other circumstances, you would not be able to find it.}
{2628}{}{Lucky! Awesome gun and rare ammunition. Under other circumstances, you would not be able to find it.}
