{100}{}{You see a bandit.}
{101}{}{You see a marauder.}
{102}{}{You see a robber.}
{103}{}{You see a convict.}
{104}{}{You see a rogue.}
{105}{}{You see a runaway prisoner in gear stolen from the guard.}

{200}{}{Surrender!}
{201}{}{Your money or your life.}
{202}{}{This is a stick-up.}
{203}{}{Give me all your valuables.}
{204}{}{I'll get you!}
{205}{}{Put yer hands up.}
{206}{}{Stick 'em up.}
{207}{}{Don't panic - this is gonna be over in a minute.}
{208}{}{Let me see those hands there.}
{209}{}{Cover me, fellas.}

{210}{}{Don't make this hard for yourself.}
{211}{}{Hand over the loot.}
{212}{}{Get 'em, boys.}
{213}{}{Kill these ones.}
{214}{}{I can promise you a quick death.}
{215}{}{Reach for the sky.}
{216}{}{Don't move.}
