{100}{}{You see Bobby.}
{101}{}{You see old pal Bobby.}

{110}{}{Hello, stranger! Be my guest. Everyone is always in a hurry, running somewhere... Are you in a hurry too? Why don't you stay for a chat with an old man? Time flows slowly, telling interesting stories, but are you ready for them?}
{111}{}{Only smoke goes to the sky irrevocably, but a man is free to choose his path in any direction... Would you like a story about that?}
{112}{}{Uh, okay, I'll listen.}
{113}{}{And you seem to be an expert on wasteland weed? This is going to be fun.}
{114}{}{Wow, easy! I'm only here to look around. Don't strain yourself too hard.}

{115}{}{Anyway, there were two brothers. Their names were... Well, let's say Dick and Tom. One of them, Tom, was always helping the poorest... or even richest. He was a humble man at heart, unique. And his brother couldn't resist taking advantage of someone. He even conned his own mother out of her money.}
{116}{}{[Next]}
{117}{}{And then came the day when God, as many believed, gave everyone what they deserved. Tommy, who had driven a crowd of clowns to their circus, was eaten by those same clowns, without salt and pepper... But Dick died, too. In his sleep...After earning his way to the pharmaceutical warehouse and amassing wealth through skillful speculation. That's the story.}
{118}{}{Tell me it's not so. I really need to hear it from you. Hey, I'm talking to you!}
{119}{}{Excellent! I was ready for some snotty sermon, and how well you turned it around!}
{120}{}{You're so stoned, I literally have nothing to say. I'll come back when you're normal... If that's even possible.}

{121}{}{I also remembered this one: about an old writer from Denver. What an extremely positive person he was - always tried to find the positive side to any situation. Lost his leg after a run-in with a stoned cola truck driver - said "now I can finish writing my book without being distracted by pointless running around."}
{122}{}{In the vault during the bombing of 2077, where his relatives complained about their fate to no end, he was happy that everyone finally came together. In the end, he was kicked out and became a ghoul... And said that it's great, now that the radiation is not an issue there are so many places to visit!}
{123}{}{Some crazy sectarians crucified him somewhere at Great Plains - good! That means... U-ugh... Well, to be honest, I don't see anything positive in this case. But he'd think of something, rest assured. Don't worry, be happy.}
{124}{}{I hope you don't tell stories like this to your children. Wait, you're not done yet?}
{125}{}{One story is better than the other! Give me a nickel bag!}
{126}{}{I'm not in the mood to listen about your tripping. Good luck.}

{127}{}{So... Loyalty is a good word, isn't it? That was also the opinion of one dog who made his way to his master through the devastation of the nuclear holocaust. But when that dog found him...}
{128}{}{Stop! Lemme guess - someone ate someone.}
{129}{}{Yeah-yeah, go on. I'm eager for more.}
{130}{}{That's it, I'm done. Bye, fabler!}

{131}{}{Hmm... I think I'd better tell the story of the lonely wanderer from some vault. How do you think I would end this tale?}
{132}{}{I think it's up to wanderer how the story ends.}
{133}{}{What's the catch? Why do you keep telling me these stories? Is this some kind of test?}
{134}{}{I don't fuckin' care! I'm tired of you already. I'm gonna leave.}
{135}{}{Wanderer killed some stoned old man for loot. How do you like that? [Attack]}

{136}{}{No catch, nope. After all, we're not on bridge of death, ha-ha! I just want to stir your mind a little. To turn it in the right direction.}
{137}{}{Thoughts are nothing, it's deeds that matter. And no matter what anyone says, I will do what I think is right.}
{138}{}{So far my thoughts are all about beating you up for my wasted time. Get out of my sight, junkie.}
{139}{}{Well said! Let it go as it is... You never know what's around the corner, but that's no reason to be gloomy. Don't worry, be happy!}
{140}{}{Amen. So long, philosopher.}
{141}{}{Whatever is hiding around the corner had better run in fear. Stay healthy, don't smoke too much.}
{142}{}{Thank you, wise one, for the opportunity to partake of your font of knowledge. Well, I need to go.}

#Ñëó÷àéíûå ôðàçû
{150}{}{Why didn't anyone think of selling empty cigs?}
{151}{}{In this wilderness, there's no one to smoke a joint with...}
{152}{}{Life is way simpler than everyone thinks.}
{153}{}{You were allowed to start everything from scratch - how did you manage to ruin everything?}
{154}{}{Like hell - lots of killer vinyls and not a single gramophone.}
{155}{}{Be happy, for Pete's sake!}
{156}{}{Don't worry!}

#Æåíñêèå ðåïëèêè
{1110}{}{Hello, stranger! Be my guest. Everyone is always in a hurry, running somewhere... Are you one of them? Why don't you stay for a chat with an old man? Time flows slowly, telling interesting stories, but are you ready for them?}
{1114}{}{Wow, easy! I only here to look around. Don't strain yourself too soon.}
{1119}{}{Excellent! I was ready for some snotty sermon, and how well you turned it around!}
{1129}{}{Yeah-yeah, go on. I'm eager for more.}
