{100}{}{You see Bobby.}
{101}{}{You see old pal Bobby.}

{110}{}{Hello wanderer! Be my guest. Everyone is always in haste, running somewhere... You're one of the kind? Wouldn't you stay for a little chat with the old man? Time flows slowly with interesting stories, but are you ready for them?}
{111}{}{Only smokes goes into sky irretrievably, human is free on his way in any direction... Do you want a story about it?}
{112}{}{Eh, okay, I'll listen.}
{113}{}{And you seems to be an wasteland weed expert? It's gonna be fun.}
{114}{}{Wow easy! I only here to look around. Don't strain so soon.}

{115}{}{Anyway, there were two brothers. Called... Well, let's say Dick and Tom. One of them named Tom always help closest one... And even distant. He was a humble man of heart, a unique one. And his brother couldn't restrain himself from benefiting on someone. He sued his own mother for money she owned him.}
{116}{}{[Next]}
{117}{}{And there came Black Saturday, when God, as many believed, gave everyone what they deserved. Tommy, who drove a bunch of clowns to their circus, got eaten by the very same clowns without even salt and pepper... Fun and tasty, ta-ta-ta! But Dick also died... In a slumber. After he had taken a warehouse with medicines and acquired wealth with skillful speculation. That's the story.}
{118}{}{Tell me it's just a fiction. I really need to hear it from you. Hey, I'm talking to you!}
{119}{}{Excellent! I was ready for some snotty sermon, and how well you turned it around!}
{120}{}{You're so stoned, I've got nothing to say. I'll return when you'll be normal... If it's possible.}

{121}{}{I also remembered this one: about old writer from Denver. Extremely positive person he was - always tried to find positive things in any situation. Lost his leg after meeting with stoned cola truck driver - he said now he can finish writing his book without being distracted with meaningless running around.}
{122}{}{In the vault during bombing in 2077, where his relatives complained about their fate to no end, he was happy that everyone finally came together at one table. In the end he was kicked out and became a ghoul - it's great, now radiation is not an issue, so many places to visit!}
{123}{}{Some crazy sectarians crucified him somewhere at Great Plains - good! That means... U-ugh... Well, to be honest, I see no positives in this case. But he'd think something out, rest assured. Don't worry, be happy.}
{124}{}{I hope you didn't tell such stories your children? Wait, you're not finished?}
{125}{}{One story is more killing than other! Would you give me a nickel bag?}
{126}{}{I'm not in the right mood to listen about your trips. Good luck.}

{127}{}{So... Devotion - nice word, isn't it? Same opinion had one dog, which made it's way to the owner through the devastation of a nuclear holocaust and scratch along  with the surviving cats and rats. But when that dog found him...}
{128}{}{Stop! Lemme guess - someone ate someone.}
{129}{}{Yeah-yeah, go on. I'm eager for more.}
{130}{}{That's it, I'm done. Bye, fabler!}

{131}{}{Hm... I think I better tell a story about some lone wanderer from some vault. How you'd think I end this tale?}
{132}{}{I think it's up to wanderer how the story ends.}
{133}{}{What's the catch? Why did you keep telling me these stories? Is this some kind of test?}
{134}{}{I don't fuckin' care! I'm tired of you already. I'm gonna leave you.}
{135}{}{Wanderer killed some stoned old man for loot. Do you like this tale? [Attack]}

{136}{}{No catch, nope. After all, we're not on bridge of death, ha-ha! Just wanna stir your mind to some determinate thoughts.}
{137}{}{Thoughts is nothing, deeds matter. And whoever says anything, I will do whatever I think is necessary.}
{138}{}{So far my thoughts are about beating you for time spent ineptly with you. Disappear from horizon, junkie.}
{139}{}{Well said! Let it go as it is... You never know what's hiding behind the corner, but it's not a good reason for grim thoughts. Don't worry, be happy!}
{140}{}{Amen. So long, philosopher.}
{141}{}{Whatever hides behind the corner, it's better flee from the way in fear. Be healthy, don't smoke too much.}
{142}{}{Thank you, the wisest one, for the opportunity to joint to the source knowledge. Well, I need to go.}

#Случайные фразы
{150}{}{Why did no one thought of selling empty cigs?}
{151}{}{In this wilderness, can't even smoke a joint with no one...}
{152}{}{Life is way simpler than everyone thinks}
{153}{}{You were allowed to start everything from scratch - and how did you manage to ruin everything?}
{154}{}{Like in hell - lots of killing vynils and not a single gramophone.}
{155}{}{Be happy, for Pete's sake!}
{156}{}{Don't worry!}

#Женские реплики
{1110}{}{Hello wanderer! Be my guest. Everyone is in haste, to somewhere... You're one of the kind? Wouldn't you stay for a little chat with the old man? Time flows slowly with interesting stories, but are you ready for them?}
{1114}{}{Wow easy! I only here to look around. Don't strain so soon.}
{1119}{}{Excellent! I was ready for some snotty sermon, and how well you turned it around!}
{1129}{}{Yeah-yeah, go on. I'm eager for more.}