{100}{}{The leader of the Coyote tribe.}
{101}{}{You're looking at one hell of a person who is as attractive as she is rude.}

{110}{}{You will burn on the sacrificial pyre!}
{111}{}{I'll eat your heart to become stronger!}
{112}{}{Attack, my children!}
{113}{}{Kill! Kill!}
{114}{}{My hungry children, take the most delicious parts!}
{115}{}{The flesh of strangers is so delicious...}
{116}{}{I like you. Especially your sirloin.}
{117}{}{Come on, run! You're only gonna make my children mad!}
{118}{}{No one will be forgiven if this prey gets away!}
{119}{}{A glorious dinner tonight, my children! Rejoice!}