{100}{}{You see a feral ghoul.}
{101}{}{You see an agent of now defunct patrol unit. Seems like he is not going to retire anytime soon.}

{110}{}{Let me introduce myself - Michael Dixon, patrol unit.}
{111}{}{Show me the papers before I use force.}
{112}{}{Get out of the car and touch your nose with a finger.}
{113}{}{Looks like you're drunk. You are fined with the amputation of both hands.}
{114}{}{I won't be surprised if you are involved in smuggling of Mexican illegals.}
{115}{}{Surrender your weapon, before I call reinforcements.}
{116}{}{I'm forced to take extreme measures.}
{117}{}{I'm going to ask you only once...}
{118}{}{I'm confiscating your vehicle.}
{119}{}{Resistance is futile.}