{100}{}{You see John.}
{101}{}{You see an athletic man. The only piece of clothes he's wearing is a cowboy hat.}

{102}{}{You delivered the passenger to the destination.}

{103}{}{Quiet! Not a place for chitchat - let's just get out of here as fast as we can.}
{104}{}{Thanks for the ride! If only there would be more people like you.}
{105}{}{   }

{106}{}{I won't make a step until we go away from this region.}

####################################################
#
#    Типовые действия с нпс
#
####################################################

#Стандартные диалоговые опции
{120}{}{Stay here until we go.}
{121}{}{Yeah, I want you back in company, it's always more fun to travel with fellow travelers.}

{122}{}{Let's roll then?}
{123}{}{I have a feeling, that we should hurry up and leave.}

{124}{}{Go back to the car, you're not needed.}
{125}{}{Okay, man.}
{126}{}{I need your help. Follow me.}
{127}{}{Hey, no jokes - time is running out. Don't know what you want from me, but I'm not going to go far from the car.}
{128}{}{Just follow me.}
{129}{}{Stay here, then.}

#Попытка толкнуть [авторы текста BalckDeigner и Kerb]
{130}{}{Hey-hey! Hands off!}
{131}{}{I can handle myself, mind you.}
{132}{}{You wanna touch me?}
{133}{}{Hey, I'm not so sweaty!}
{134}{}{Do I smell bad?}
{135}{}{Where? There? Okay. But then to Vegas!}
{136}{}{I don't mind... For now.}
{137}{}{Don't get so excited.}
{138}{}{}
{139}{}{}
#--- Для женского перса:
{140}{}{If you decided to touch it - try lower, baby.}
{141}{}{You have such soft hands!}
{142}{}{Want me to play your guitar, baby?}
{143}{}{Oh, do you like it rough?}
{144}{}{Could just ask, I can't resist.}
#--- Для мужского:
{145}{}{Oh, man, keep your hands to yourself!}
{146}{}{Hey, don't push! I almost stepped in a shit.}
{147}{}{Okay, already gone.}
{148}{}{Okay, you're the boss.}
{149}{}{I prefer to keep a distance too.}

#Первый диалог
{150}{}{[You see a naked guy of athletic build, with definitive "six-pack" on his belly] Hey, man, can you give me a ride to Vegas? I'll pay, I promise.}
{151}{}{How are you gonna pay, if you don't even have a pants?}
{152}{}{You don't look like a hitchhiker. So - what's the catch?}
{153}{}{No problem! Sit down, man, I'll drop you off.}
{154}{}{I don't need inadequate travel companions.}

{155}{}{I said I'll pay - it means I'll pay! Trust me, okay?}
{156}{}{[He throws his hands in the air, to the sides, showing the absence of any items on him whatsoever] Man, I'm clean as Russian vodka! No strings attached! Absolutely!}
{157}{}{Really?! Wow, man, you are saving the day! Do you know where "Hard Rock" cafe in Vegas is? That's where I should be. And the sooner, the better.}
{158}{}{Well, now scram! [desperately shows the middle finger]}
{159}{}{[Leave]}

{160}{}{We're gonna move soon, but for now - wait.}

{161}{}{Before moving out, answer a few questions.}
{162}{}{Let's go.}

{163}{}{Wasting time, man.}
{164}{}{Where are you going?}
{165}{}{To Vegas, man. They say there, in the "Hard Rock" cafe, nobody heard an excellent country for a long time already - and that's where I have to be... To SHOW these rednecks, that the real music is still left in Nevada.}
{166}{}{I think you're late, cowboy. The scene in "Hard Rock" is already filled with excellent jazz.}
{167}{}{What?! No!! Are you sure? But, damn, these niggas already there and made it! That's why you need to hurry, man. Let's go!}
{168}{}{Why are you naked?}
{169}{}{I'm just hot.}
{170}{}{-??}
{171}{}{Yeah! What's the matter? Am I embarrassing you? Dude, calm down, get me to Vegas, I'll make up to all expenses.}
{172}{}{Let me get you some clothes.}
{173}{}{Clothes? Fuck clothes, man!! There's a bigger question at stake! We're on a mission to save Vegas, the last sanctuary of American fucking culture, and you are telling me about the clothes?! Let's go! To Vegas! Not a moment to lose!}
{174}{}{You won't, uh... Hit on me or anything, will you?}
{175}{}{Wh-... EW!! I hate fags! No, I'm not like that, certainly.}
{176}{}{Baby, not tonight - handsome John is busy, I'm sorry.}

{177}{}{The conversation is finished. Wait, until we move out.}
{178}{}{}
{179}{}{}

#Инсценировка
{180}{}{Hey, you! The fuck, nigga, what the fuck do you think you're doing!?}
{181}{}{YOU!? But... HOW!?}
{182}{}{That was easy. No one's gonna interfere with us now!}
{183}{}{Uh, buddy, it wasn't me, who rat you out to those thugs, honestly!..}
{184}{}{Fuck the thugs, and my jacket! Fuck this shit!}
{185}{}{Uh... John, let me explain...}
{186}{}{Save it, you son of a bitch! You've already spent enough of my time!}
{187}{}{You are breaking my heart, John. We're companions!}
{188}{}{Exactly! If you go out on this stage alone, I'm going to smear your guts all over it!}
{189}{}{That was just a misunderstanding. Of course, we will go together. I did not even think...}
{190}{}{Great. We still have time to prepare. Now - get the hell out!}
{191}{}{Whatever you say... Partner.}
{192}{}{}
{193}{}{}
{194}{}{}

{195}{}{Damn you, you ungrateful scum! I spent so many batteries on you...}
{196}{}{Don't sweat it, man, but we need to part ways. Thanks for the ride and stuff. And I remember that I promised to pay... Shit, listen, I lied. I have nothing to pay with, but someday I'll find a way and pay you back. Honestly, no bullshit. My partner and I will try to play at a local eatery, and if we're lucky, it will be plenty of money.}
{197}{}{Didn't you understand, man? He ditched you! And after that you still want to deal with him?}
{198}{}{Of course! Tear me a new one, if I betray my friends, man.}
{199}{}{Uh... It's your business. Okay, take care.}

####################################################
#
#    Вступительные реплики при заходе на карту
#
####################################################

#Рэндомные типовые фразы при загрузке любых карт [авторы текста BalckDeigner и Kerb]
{200}{}{Where the hell are we?!}
{201}{}{It's not like Vegas!}
{202}{}{Agree with me - we are not where we wanted to be.}
{203}{}{Hey, why are we stopping here?}
{204}{}{Don't tell me we're lost, 'kay?}
{205}{}{We're cowboys, we're cowboys, we are brave and we are two!}
{206}{}{Uh... If the seat cover wasn't sticking to my butt so hard...}
{207}{}{Don't look at me like that! At least my tan is even.}
{208}{}{I'd rather live is Vegas toilets, than here.}
{209}{}{Only in Vegas I'll find peace.}
{210}{}{I'm gonna look around - maybe find some food.}
{211}{}{Don't worry, I will be looking out for the car.}
{212}{}{Ugh! I want to enter Vegas as effectively as this.}
{213}{}{Fresh air... Are you gonna put climate-control in that?}
{214}{}{[Sings]}

#Контекстные фразы для отдельных карт
#--- дамба Гувера
{250}{}{Why don't you just hitch me straight to the "Hard Rock"? It would be faster.}
{251}{}{There is nothing to do at the dam. To "Hard Rock", while we still can!}
#--- оригинальная карта встречи
{255}{}{Don't you think we been here before?}
{256}{}{This place reminds me something...}
{257}{}{I bet we're going in circles!}
#--- Мертвый отель
{260}{}{What is this area? Maybe you'll take me to the "Hard Rock", before I got lost?}
{261}{}{This isn't Vegas, but some kind of hole. Where is "Hard Rock", do you know?}
#--- Работорговцы Вегаса
{265}{}{Why are we stopping here?! Uh, look, let's get out of here?}
{266}{}{No-no-no! Just don't do stops here!}
{267}{}{I won't stay in this area! Do what you want - I'll be near the car, no matter what.}
#--- Чистый Город
{268}{}{Now I'm thinking about clothes. Maybe we should take a drive to "Hard Rock"?}
{269}{}{Wow! It's Vegas.}
{270}{}{Yes, so I imagined. Now let's look at the "Hard Rock".}
#--- стоянка караванов в Вегасе
{275}{}{It's just a suburbs. Where is the "Hard Rock"?}
{276}{}{I'm sooo stoked. Do you know where to go?}
{277}{}{We're almost there! All that remains is to find the cafe.}

#Женские вариант
{1104}{}{Thanks for the ride! If only there would be more people like you.}
{1125}{}{Okay, baby.}
{1150}{}{[You see a naked guy of athletic build, with definitive "six-pack" on his belly] Hey, babe, can you give me a ride to Vegas? I'll pay, I promise.}
{1156}{}{[He throws his hands in the air, to the sides, showing the absence of any items on him whatsoever] Baby, I'm clean as Russian vodka! No strings attached! Absolutely!}
{1157}{}{Really?! Wow, baby, you are saving the day! Do you know where "Hard Rock" cafe in Vegas is? That's where I should be. And the sooner, the better.}
{1163}{}{Wasting time, baby.}
{1165}{}{To Vegas, baby. They say there, in the "Hard Rock" cafe, nobody heard an excellent country for a long time already - and that's where I have to be... To SHOW these rednecks, that the real music is still left in Nevada.}
{1167}{}{What?! No!! Are you sure? But, damn, these niggas already there and made it! That's why you need to hurry, baby. Let's go!}
{1171}{}{Yeah! What's the matter? Am I embarrassing you? Doll, calm down, get me to Vegas, I'll make up to all expenses.}
{1173}{}{Clothes? Fuck clothes, baby!! There's a bigger question at stake! We're on a mission to save Vegas, the last sanctuary of American fucking culture, and you are telling me about the clothes?! Let's go! To Vegas! Not a moment to lose!}
{1196}{}{Don't sweat it, baby, but we need to part ways. Thanks for the ride and stuff. And I remember that I promised to pay... Shit, listen, I lied. I have nothing to pay with, but someday I'll find a way and pay you back. Honestly, no bullshit. My partner and I will try to play at a local eatery, and if we're lucky, it will be plenty of money.}
{1198}{}{Of course! Tear me a new one, if I betray my friends, baby.}
