{100}{}{You see a guard.}
{101}{}{You see one of the guards. They guard the caravan with you.}

{200}{}{You see a caravan merchant.}
{201}{}{You see one of your fellow travelers.}

{300}{}{I hope we don't meet anyone else on the road.}
{301}{}{It will be nice to get my pay at the end.}
{302}{}{I hope the bar will still be open when we get there.}
{303}{}{It will be good to finally eat some real food.}
{304}{}{I always wanted to travel. I think it's the closest thing to traveling.}
{305}{}{My feet are killing me. Why these stupid brahmin walk so slow?}
{306}{}{It feels like we're not very far from our destination.}