{100}{}{You see a lean, tanned man.}
{200}{}{You see a lean, tanned woman.}
# male
{101}{}{You see a farmer.}
# female
{201}{}{You see a farmer.}
{102}{}{You notice that he has a farmer's tan.}
{202}{}{You notice that she has a farmer's tan.}
{103}{}{You showed up just in time. If you hadn't come... Well, we'd appreciate your coming. We don't have much, but I'd like you to take this as a reward for your help. [he hands something to you]
{104}{}{Thank you.}
{105}{}{Ugh.}
{106}{}{Thanks again for helping us.}
{107}{}{}
{108}{}{}
{109}{}{You, keep your hands where I can see them. We've been plagued by bandits lately, you might be one of them. What do you want?}
{110}{}{I just want to trade for supplies.}
{111}{}{I'm just passing through. I'll be on my way.}
{112}{}{Ugh.}
{113}{}{Well, I guess there's no harm in that. Here's what I got to trade.}
{114}{}{[Barter]}
{115}{}{OK, now git!}
{116}{}{[Barter]}
{117}{}{I said git!}
{118}{}{}
{119}{}{[He relaxes a bit.] You're too stupid to be a bandit. Do you need supplies?}
{120}{}{Uh-huh.}
{121}{}{Eh-eh.}
{122}{}{Then we got no business. Just keep moving.}
{123}{}{[END]}
{124}{}{Leave my farm!}
{125}{}{Nobody is going to take my home from me.}
{126}{}{Filthy bandits.}
{127}{}{Get off my land.}
{128}{}{Can't trust anyone these days.}
{129}{}{Damn bandits.}
{130}{}{I've worked too hard to give up now.}
{131}{}{Maybe I'll farm elsewhere.}
{132}{}{I'm just a poor farmer.}
{133}{}{Please, don't burn my farm down.}
{134}{}{I didn't like farming anyway.}
{135}{}{I'll be back.}
{136}{}{Please, take my wife...}