{100}{}{You see your pursuer.} 
{101}{}{You see a mercenary. He is hunting you for the filter you are trying to deliver to Salt Lake.}

{110}{}{Give me that filter immediately!}
{111}{}{You won't get away from me! Give me the filter!}
{112}{}{This thing in your backpack is mine!}
{113}{}{Heading over to Salt Lake? May I carry your stuff?}
{114}{}{Salt Lake will surely pay a lot of money for this filter.}
{115}{}{Shut up and give me the filter!}
{116}{}{Sorry, but I need this filter more than you.}
{117}{}{"Stand still!" - Is that what you're supposed to say in a robbery?}
{118}{}{This thing is too heavy and the city is very far. Give it to me.}
{119}{}{Walking around with this filter is quite dangerous, don't you think?}
{120}{}{Even though I'm a caravaneer, I love easy money.}
{121}{}{Filter or your life?}