{100}{}{You see a scarred traveler.}
{101}{}{You see the merchant's guard.}

{200}{}{No drawn weapons near the boss.}
{201}{}{No one comes to the boss armed.}
{202}{}{Put your weapon away before we shoot you.}
{203}{}{Put 'em away or get away.}

{250}{}{You were warned - now you will pay.}

{300}{}{Talk to the boss, he'll set it up.}
{301}{}{I take my job seriously. You mess with the boss, you die.}
{302}{}{The boss is a good guy for the most part.}
{303}{}{Don't even think about stealing from the boss.}