{100}{}{You see Harrelson.}
{101}{}{You see the paranoid ghoul named Damon Harrelson. It's hard to tell what's in his head.}

{102}{}{[When you look around the corner, you suddenly stumble upon the ghoul, dressed in a shabby robe with the Nuka-Cola company logo on it. When he sees you he immediately grabs his weapon, but you manage to step back into shadow just in time.]}
{103}{}{[Next]}

{104}{}{Hey, you scrounger! Come out! I'll make it quick and quiet. Though I ain't makin' any promises!}
{105}{}{Don't rush things, handsome... Harrelson, right?}
{106}{}{You are the scrounger here!}
{107}{}{[Go out and get into the fight]}
{108}{}{[Attempt to escape]}

{109}{}{What did you say!? Sons of bitches, this is MY shack! And it's YOU who came here for my hard-earned goods! Yeah, you'll suffer extra for saying that!}
{110}{}{[Fight]}
{111}{}{Huh? What are you mumbling about, you petty thief!? I know all your tricks! Do not even try to play me, otherwise your death will be VERY painful!}
{112}{}{Never expected to hear a sensible speech from an old ghoul. How did you end up like this?}

{113}{}{I'll tell you... When I catch you and put you in a cage! I've already caught a few dozen like you. Every one of them wanted a piece of me, wanted my things. But my traps aren't just for show! What about you? Isn't that what you came here for?}
{114}{}{I'm here to stop your madness.}
{115}{}{True - I'm just here to steal all your belongings and sell them to the Quok brothers.}

{116}{}{Then stop talking!}
{117}{}{Who's crazy?! You jump in front of a gun, knowing in advance how it's going to end, and I... I'm defending my home!}
{118}{}{You may have protected your belongings, but at the cost of the lives of ordinary prospectors. What about your conscience, doesn't it torment you?}
{119}{}{Tell me, where did you get all this stuff? Take it off corpses?}
{120}{}{Aren't those too many words for a creature who has lost his human form?}
{121}{}{So you only care about your things and don't give a damn about others?}
{122}{}{I'm getting tired of it. I want to end you once and for all.}

{123}{}{Conscience? I haven't heard that word in seventy years... It couldn't save any of those who died from nuclear explosions. I have since forgotten what "conscience" means.}
{124}{}{Nuclear explosions? Does it mean you witnessed the Great War?}
{125}{}{People got what they deserved. When I was delivering bottles, no one recognized me as a human being. Only when I went outside the big city did I manage to find peace in my car. When I saw the flashes... I was filled with joy. I thought I was the only person left in the world... Until bastards like you showed up! They came after me, wanted to take my supplies, wanted to kill me! No, I don't feel guilty about killing animals. And people are animals!}
{126}{}{I think you just had bad luck with people, which made you angry at the whole world.}
{127}{}{[Pause] Shut up and get where I can see you. My past will soon cease to worry you. As I said - people are animals. They are not worthy to be called human anymore.}

{128}{}{A small compensation for the inconveniences caused to me. It's only fair.}
{129}{}{So why all these sacrifices? Your seclusion and rumors of bloody violence just attracts more attention to you. Everyone thinks that you have untold riches here.}
{130}{}{That's what they think about me? That is to be expected. You, animals, smell money like flies smell rotten meat. Am I not right? Would swatting a fly make the world worse?}
{131}{}{Such an interesting comparison. But the prospectors were just looking for a way to survive... Such times.}
{132}{}{You still have the guts to talk about it, you monkey? It's just what these animals do. They take the lives of their own to feed themselves. But, yeah... These days... In this world... [remembering something from his past he dramatically raises his voice] But before the War it was just the same! People didn't kill each other like now, but bullied each other at school, bullied the weak ones in the army... People haven't changed a bit.}
{133}{}{Greed and ego - that's what you're talking about, I get it. But do you treat people differently?}
{134}{}{Shut up! Shut up! I'm tired of your nonsense. Come out and meet your fate, you thieving brat!}

{135}{}{Oh, you're not the only thief that I had a chance to talk to... But I'll enjoy our conversation more when [he raises his voice] you're in a cage with your guts ripped out!!!}
{136}{}{That's harsh.}
{137}{}{You know, you pretend to be a kind son of a bitch, but if you get pinned down to a wall with a sharp blade at your throat, what would you say? Yeah, I've seen all this bullshit before the War. When you're grabbed by the throat, your whole essence will come out. And, believe me, it stinks no better than a piece of human shit.}
{138}{}{I think there's more to my essence than this.}
{139}{}{Come out and we will see. You're neither the first, nor last. However, I like you. With you I'm gonna have a "conversation" longer than usual.}

{200}{}{You get a large dose of radioactive contamination from the ghoul.}
{201}{}{Oh, I feel your cells dying!}
{202}{}{Oh, I feel the radiation piercing you!}
{203}{}{Your body is going to like the radiation!}
{204}{}{Ghoulification is not what you should worry about, you're gonna be dead before that!}

#Female character
{1109}{}{What did you say!? You bitch, this is MY shack! And it's YOU who came here for my hard-earned goods! Yeah, you'll suffer extra for saying that!}
{1112}{}{Never expected to hear a sensible speech from the old ghoul. How did you end up like this?}
{1113}{}{I'll tell you... When I catch you and put you in a cage! I've already caught a few dozen like you. Every one of them wanted a piece of me, wanted my things. But my traps aren't just for show! What about you? Isn't that what you came here for?}
{1137}{}{You know, you pretend to be a kind bitch and all that, but if you get pinned down to a wall with a sharp blade at your throat, what would you say? Yeah, I've seen all this bullshit before the War. When you are grabbed by the throat, your whole essence will come out. And, believe me, it stinks no better than a piece of human shit.}
{1139}{}{Come out and we will see. You're neither the first, nor last. However, I like you. With you I'm gonna have a "conversation" longer than usual.}
