{100}{}{You see Harrelson.}
{101}{}{You see the paranoid - Damon Harrelson. Hard to say what he's thinking.}

{102}{}{[When you look around the corner, you suddenly stumble upon the ghoul, dressed in a shabby robe with the Nuka-Cola company logo on it. When he sees you he immediately grabs his weapon, but you manage to step back into shadow just in time.]}
{103}{}{[Next]}

{104}{}{Hey, you scrounger! Come out! Maybe then your death is going to be quick and quiet. Although, I can't promise that!}
{105}{}{Don't rush things, handsome... Harrelson, right?}
{106}{}{You are the scrounger here!}
{107}{}{[Go out and get into the fight]}
{108}{}{[Attempt to escape]}

{109}{}{What did you say!? Sons of bitches, this is MY shack! And it's YOU who came here for my hard-earned goods! Yeah, you'll suffer extra for saying that!}
{110}{}{[Fight]}
{111}{}{Huh? What are you mumbling about, you petty thief!? I know all your tricks! Do not even try to play me, otherwise your death will be VERY painful!}
{112}{}{Never expected to hear a sensible speech from an old ghoul. How did you end up like this?}

{113}{}{I'll tell you... When I catch you and put you in a cage! I've already caught a few dozen like you. Every one of them wanted a piece of me, wanted my things. But my traps aren't just for show! What about you? Isn't that what you came here for?}
{114}{}{I'm here to stop your madness.}
{115}{}{True - I'm just here to steal all your belongings and sell them to the Quok brothers.}

{116}{}{Then, stop talking!}
{117}{}{Who's crazy?! You climb under the barrel, knowing it will all end, and I... I defend my place!}
{118}{}{You may have protected your belongings, but still at the cost of life of ordinary prospectors. What about conscience, doesn't it torment you?}
{119}{}{Tell me where did you get all these things? Took it off corpses?}
{120}{}{Is it not too many words for a creature, who has lost his human form?}
{121}{}{So, for you, your possessions are more important, than to care about the others?}
{122}{}{I'm tired of it. I want to end you once and for all.}

{123}{}{Conscience? I haven't heard these word in seventy years... It couldn't save any of those, who were bent on nuclear explosions. Since then, I have forgotten what "conscience" means.}
{124}{}{Nuclear explosions? So, you witnessed the Great War?}
{125}{}{People got what they deserved. When I carried bottles, I was not recognized as a human being. Only when I traveled outside of the big city in my car I was able to find peace. When I saw the flash... I felt joy. I thought I was alone in the world... Until the bastards like you appeared! They came to me, wanted to take my supplies and kill me... No, conscience may not torment me for killing animals. And the people are animals!}
{126}{}{I think you just had bad luck with people, which got you angry at the whole world.}
{127}{}{[Pause] Shut up and get where I can see you. My past will soon cease to be the reason of your worries. As I said - people are animals. They are not worthy to be called human beings.}

{128}{}{A small recompense for the inconvenience caused to me. This is true.}
{129}{}{So why do all these sacrifices? Its seclusion and bloody violence only attracts more attention to you. Everyone thinks that you have untold wealth.}
{130}{}{Such glorious stories - about me? I was expecting something like this. You, animals, feel the smell of money, like flies smell the rotten meat. Am I not right? And if to kill a fly - will the world be any worse than it is?}
{131}{}{Such an original comparison. But the prospectors were just looking for a way to survive in our time... In our world.}
{132}{}{You still have the guts to talk about it, you monkey? It's just what these animals do. They take lives of their own relatives to feed themselves. But yeah... Such times... Such world. [remembering something from his past he dramatically increases voice] But before the War it was just the same! People didn't kill each other like now, but bullied each other at school, bullied the weak ones in the army... Inside of people themselves, nothing has changed.}
{133}{}{Greed and ego. Are you talking about this? But do you act differently?}
{134}{}{Shut up! Shut up! I'm tired of your nonsense. Come out from hiding and meet your fate, thieving brat!}

{135}{}{Oh, you're not the only thief with whom I had a chance to talk... But I'll like the conversation more, when [raises his voice] you're in the cage with guts ripped out!!!}
{136}{}{That's harsh.}
{137}{}{You know, you pretend to be pious son of a bitch, but If you are pressed to the wall with the sharp blade at your throat, you would sing another song. Yes, I remember this folly before the War. All your essence will come out, one has only to grab it by the throat. And believe me, it smells no better than a piece of human shit.}
{138}{}{Hmm. How do you know there may be more content in my essence?}
{139}{}{Come out of hiding and we will see. You're neither the first, nor last. However, I like you. With you I'm gonna have a "conversation" longer than usual.}

{200}{}{You get a large dose of radioactive contamination from the ghoul.}
{201}{}{Oh, I feel your cells dying!}
{202}{}{Oh, I feel the radiation piercing you!}
{203}{}{Your body will like the radiation!}
{204}{}{Ghoulification is not what you should worry about, you will die before that!}

#Female character
{1109}{}{What did you say!? Bitch, that's *my* shack! And it's *you* that are coming here for my honestly acquired goods! Yes, for those words you will suffer extra!}
{1112}{}{Never expected to hear a sensible speech from the old ghoul. How did you end up like this?}
{1113}{}{I'll tell you... When I catch and put you in a cage! I have caught a few dozens like you. Every one of them wanted a piece of me, wanted to get my things. But my traps are not just for show! And you? Isn't it the same thing you came here for?}
{1137}{}{You know, you pretend to be pious son of a bitch, but If you are pressed to the wall with the sharp blade at your throat, you woud sing another song. Yes, I remember this folly before the War. All your essence will come out, one has only to grab it by the throat. And believe me, it smells no better than a piece of human shit.}
{1139}{}{So come out of hiding and we will see. You're neither the first, nor last. However, I like you. With you, I'm gonna have a "conversation" longer than usual.}
