{100}{}{This is Hardy, a ghoul merchant.}
{101}{}{You see a merchant with a scorched skin.} 
{102}{}{Don't hurt ghouls, you damn racist!} 
{103}{}{Welcome... Hold on, was that you people told me about in Reno? Now, any sudden move and I will order to shoot you!} 

#Торговля
{110}{}{Wanderer? In these parts? [coughs] Interesting. You probably need new knickers for the trip. Think about it - maybe I'll find something for you among these items.}
{111}{}{Yeah, show me what you have.}
{112}{}{I guess I won't buy anything right now.}

{113}{}{More?}
{114}{}{Yeah, let's look at your thing again.}
{115}{}{No, that will be enough.}

{116}{}{Enough talk, let's trade.}
{117}{}{Another question, if I may.}
{118}{}{This will be enough. Take care.}

{119}{}{Hey, smoothskin, you're just in time! Why? Because couple more trades - and I quit. Yes, old Hardy finally decided to retire and hide somewhere. So don't be stingy - buy all my junk, there may not be another such opportunity!}

#Расспросы
{120}{}{Can I ask few questions?}
{121}{}{Make it fast - I have to rest.}
{122}{}{Where are you from?}
{123}{}{From The Hub. It is far to the South. Or rather, not so far, but to walk this distance is really hard. Between the Hub and Reno there are almost no settlements, no roads. Besides, most of the way we have to eke out in a barren desert. This route is pretty tough to walk, even without the load. Probably, my caravan is the only one.}
{124}{}{How is business?}
{125}{}{Not very good, actually. Each journey makes us good money, but everything is spent on the costs - security, water, brahmin... I think I'm gonna shut it down soon. So bear in mind - we may never meet again. Trade while you can.}
{126}{}{Tell me about yourself.}
{127}{}{Do you really care? What if I tell you, how I got out of my hiding place in the days of the Big Bang and got irradiated to the point my mother did not recognize me? Or how my kind smoothskin friends died from old age, right in front of my eyes? Or, maybe, you want to know how it feels - to carve the dirt and pus out of your body every day? No, I'd rather refrain from talking about myself.}

{128}{}{If you are going to leave the business, perhaps you would do me a discount?}
{129}{}{Makes sense - the sooner you get rid of this stuff, the faster I will get to Reno, to my white-titted girls.}
{130}{}{Oh no - these tricks won't work with me, I didn't drag all this across the desert for nothing!}
{131}{}{Fine, forget it. Let's trade on your stubborn prices.}
{132}{}{Then I refuse to buy anything. Stay with your stuff.}
{133}{}{Do you remember, how it was, before the Great War?}
{134}{}{Same as now. Just little cleaner and more pleasant.}

#Посылка от Берча
{140}{}{I'm from Lewis Birch. He asked to take this to the Hub.}
{141}{}{Birch asked? Then no problem... Yeah, I recognize his holodisks. Okay, I'll take them. When I return to the Hub, will visit this chumps' office. And oh they will be glad to see me!}
{142}{}{Well, my job is done.}
{143}{}{You've completed the task of Lewis Birch.}

#Female character
{1110}{}{Wanderer? In these parts? [coughs] Interesting. You  probably need new knickers for the trip. Think about it - maybe I'll find something for you among these items.}
{1119}{}{Hey, smoothskin, you're just in time! Why? Because couple more trades - and I quit. Yes, old Hardy finally decided to retire and hide somewhere. So don't be stingy - buy all my junk, there may not be another such opportunity!}
