{100}{}{You see a trapper of lizards.} 
{101}{}{You see a tanned to the point of blackness desert lizards trapper. He must be long engaged in his art.}

{110}{}{(Approaching the fire you notice a tanned man, dressed in leather. At first glance he looks like a retard, as if waiting for something to instantly grab. Seeing you, he only looks around with curiosity)}
{111}{}{May I?}
{112}{}{I don't mind... [his voice seems dull and stiff, like in his life this man rarely had to communicate with people] You must have a good reason to wander through these barren lands.}
{113}{}{Yeah, I had to go on a long journey... But, judging by the look of your inventory, this land is not so barren.}

{114}{}{[Frowns a little] You can stop looking, there are only desert lizards. My catch of the day.}
{115}{}{So you're a lizard trapper?}

{116}{}{Well, yes. I've been doing this for half of my life. I can't really do anything else.}
{117}{}{Are there other people around here, besides you?}
{118}{}{And what kind of lizards?}
{119}{}{You must be doing a great job, surviving in the wastes.}
{120}{}{Yes. I was destined to dwell the wasteland. I don't like being around people. Here I have all I need.}
{121}{}{Well, uh, it was an interesting conversation, but I gotta go my way now. Farewell.}

{122}{}{Yeah. There are a couple of small settlements nearby. To the south, they say, there are more, but I didn't go there. To the east is the peace and quiet. Rarely you meet settlers there.}
{123}{}{Can you show me how to reach them?}
{124}{}{[Draws in the sand] Here is the Black Rock, and there's a community of Gerlach. As for me, I prefer the desert than to live there.}

#Про игуан
{125}{}{Iguanas - desert lizards. Crawling here and there. You catch them and put them on fire. Nothing more to do.}
{126}{}{Can you make some iguanas for me?}
{127}{}{Well, yes. And what will you give me for it?}
{128}{}{Actually, I don't know... Let's see what we can trade.}
{129}{}{Hey, tell me better how to cook them. It would be useful in my journey!}
{130}{}{You know, I'd better look for other food.}
{131}{}{It's easy. Bring me some water, or money - and I'll teach.}
{132}{}{Yeah.}
{133}{}{Here's $50.}
{134}{}{Here is a flask of clean water.}
{135}{}{Oh, come on! Two good people will be able to understand each other, aren't they?}
{136}{}{Then you'll *have* to tell, otherwise you won't leave this desert alive.}
{137}{}{[Slowly turns his head] Nah, that won't work.}
{138}{}{[With pouty lips, his face doesn't look so evil, more as childish] Yes, I'll tell... Ugh...}
{139}{}{[Next]}
{140}{}{[Trapper taught you how to make kebabs from the iguanas] ...And, most importantly, don't forget to remove this part, otherwise - hold on to your stomach.}
{141}{}{Heh, it turns out, it's not so simple. Well, thank you, hunter, you helped me a lot.}
{142}{}{Were you taught to speak only one-word sentences? Well, at least I got something useful out of you.}
