{100}{}{You see a stranger.}
{101}{}{You see a strange creepy man.}
{102}{}{A real giant, he probably eats people like you for breakfast.}
{103}{}{?}
{104}{}{Who the hell are you people?!}
{105}{}{I won't answer your questions, wanderer. I've come to warn you.}
{106}{}{Warn me? About what?}
{107}{}{Damn! How did you... From such a distance...}
{108}{}{There will be no other warning. Abandon your quest, or you will share the fate of other pure souls.}
{109}{}{Looks like it was an ambush!}
{110}{}{"Pure souls"? What the hell are you babbling about?!}
{1105}{}{I won't answer your questions, wanderer. I've come to warn you.}