{100}{}{You see Rekrut.}
{101}{}{You see an apathetic man who looks like a doctor or engineer. He's constantly adjusting his glasses.}

{110}{}{How many times has the wanderer made poor Sam blush?}
{111}{}{Don't you think it's easier to play with a female character?}

{112}{}{Please, speak proper English.}
{113}{}{It's "you're", not "your".}
{114}{}{It's "their", not "there".}
{115}{}{You guessed it, I can be a nerd sometimes.}
{116}{}{Did you expect to find a dog here? Sorry, no dogs allowed.}
{117}{}{I like to criticize other people's suggestions.}
{118}{}{Why not help a good person?}
{119}{}{I always said it was a good idea!}
{120}{}{Nothing is impossible for a man who doesn't have to do it himself.}