{100}{}{You see Kerb.}
{101}{}{You see none other than Kerb!}

#Если ГГ бухой или обколотый:
{110}{}{This junkie have to save the world? Well... Why the hell not. Like priest, like people.}

#Обычные ответные реплики:
{111}{}{2.5 megabytes... 2.5 megabytes!!!}
{112}{}{When I look at you, all I see is endless lines of dialog...}
{113}{}{Non-commercial project, huh? At least there's no need to worry about [censored] censorship!}
{114}{}{Wait, what the flying shitty fuck?  Oh, nevermind, it's working...}
{115}{}{And to hell with political correctness!}
{116}{}{War. War never changes... Come on, somebody has to say it!}
{117}{}{Don't lose the spirit, comrade! 2077 is coming closer with every minute!}
{118}{}{I can't help but wonder what's going on in what used to be USSR.}
{119}{}{I'd have Lynette's liver with a glass of Chianti now... Or at least Morpheus' heart with some beer.}

#При применении воровства:
{130}{}{Hey! Get your filthy claws off me!!}
#При применении науки:
{131}{}{Sociopath with manic depressive disorder, you say? Look at yourself!}
#При применении бухла:
{132}{}{Better decant me a glass of sweet blood instead.}
#При применении drug-предметов:
{133}{}{Hey! Maybe I would also like to poke you with something! Like, with a knife! But you don't see me doing it, do you?}
