{100}{}{You see a king.}
{101}{}{You see one of the members of the "Kings" gang.}

{110}{}{You shouldn't have come into this area.}
{111}{}{We are the kings here!}
{112}{}{You will have to pay to pass through our territory.}
{113}{}{Uh, the racketeering becomes harder lately.}
{114}{}{I'm not actually a gangster - but the gang decided otherwise.}
{115}{}{Give us the money and get the fuck out!}
{116}{}{What, the lights of Vegas beckon to you too?}
{117}{}{The boss will be happy if I take a few coins from you.}
{118}{}{*We* are the kings here, so behave!}
