{100}{}{You see a feral robot butler.}
{101}{}{You see a "Mr. Handy" series robot butler. This one probably lost its owners many years ago.}
{102}{}{ }

{110}{}{Would you like to hear a joke, Mr. McClennan?}
{111}{}{Good morning, Mrs. McClennan.}
{112}{}{Scum like you killed Mrs. McClennan!}
{113}{}{Get away from the home of the McClennan family!}
{114}{}{Save yourself, Mr. McClennan! Go to the basement and take the children with you!}
{115}{}{I won't let you hurt my masters!}
{116}{}{No one may interrupt the morning dog walk. You should pay a fine.}
{117}{}{I see a thief! Master, stay in your room and lock the door!}
{118}{}{You shouldn't have kidnapped my master's dog!}
{119}{}{What a blinding flash! Mr. McClennan? What's wrong? Mr. McClennan!}
{120}{}{I can't cause harm to the McClennan family members, but you're not one of them!}
{121}{}{I was programmed to obey orders, but only from McClennan family members!}
{122}{}{I must protect, because I am the property of the McClennan family.}
{123}{}{It will be a gentle rain!!!}
{124}{}{Your blood is a great lubricant, -error!}
{125}{}{Activating "deep cleaning" mode.}
{126}{}{Want me to place the skull of this primate next to your other trophies, Mr. McClennan?}
{127}{}{Do you want me to serve the intruder with garlic, or with a mustard sauce, Mrs. McClennan?}
