{100}{}{You see a man who has seen a lot in his life.}
{101}{}{You see a trader.}
{102}{}{Wow, there aren't that many people in these parts.}
{103}{}{Hey! Wait! I've got goods you might need!}
{104}{}{Hey! Do you have anything to trade?}
{105}{}{I guess it's my lucky day. Look what I have for sale.}

{200}{}{Hello, traveler! People are rare on this route, but I always welcome new customers. Shall we trade?}
{201}{}{Hey there! Good that you stopped by. Most people on this route just keep on going. Do you want to trade?}
{202}{}{Want to see my merchandise?}

{250}{}{That would be nice.}
{251}{}{I'm sorry. Need to go.}
{252}{}{Yes. Me have goods!}
{253}{}{Me go.}

{260}{}{Glad doing business with you. Good luck with your travels.}
{261}{}{Bye.}

{270}{}{Good, you're back. May I offer you something else?}
