{100}{}{This is Neon Gangster.}
{101}{}{You see a bandit known as Neon Gangster.}

{110}{}{My motto is "Live bright and die bright!"}
{111}{}{Get ready to become a shadow in this light show!}
{112}{}{Lights of Vegas, reincarnated in me, will burn you into ashes!}
{113}{}{This city will tremble in fear hearing my name. This is what I call a "bright personality"!}
{114}{}{Want to hit me? It's like trying to hit a sun!}
{115}{}{The moon will illuminate your body on the roadside at night.}
{116}{}{My weapon was made to enforce law and order. I'm enforcing chaos with it.}
{117}{}{I hate to kill cowards. So you have to act brave, c'mon!}
{118}{}{Do you know what "homocentric beam of light" means? You will find out...}
{119}{}{It's simple: You'll be killed by the induced emission of an optical quantum generator.}
