{100}{}{A cannibal hunter.}
{101}{}{A hunter from the Coyote tribe. He hunts you and other animals from the outside world.}

{110}{}{Fresssh meeeat!}
{111}{}{Bones and meeeat!}
{112}{}{Outlander will diiie!}
{113}{}{I will feed my family with you!}
{114}{}{This one is resisting!}
{115}{}{Good catch!}
{116}{}{The savages of the outside world are becoming more and more appetizing!}
{117}{}{Get the savage!}
{118}{}{You, savages, are only good for being eaten!}
{119}{}{A new sacrifice to the God of windmills!}
