{100}{}{You see a redneck.}
{101}{}{You see a redneck who, out of desperation, has taken the path of robbery and burglary.}

{110}{}{Halt! This is a robbery!}
{111}{}{Don't you dare resist, or else... Or else!..}
{112}{}{I don't want to kill... but I have to!}
{113}{}{I have to kill someone to feed my family!}
{114}{}{Don't be greedy, share with the poor, you rich bastard!}
{115}{}{You pretend to be poor, but your soft hands give you away!}
{116}{}{I can smell a rich scum like you a mile away!}
{117}{}{Money! Now!}
{118}{}{This year has been bad. You'll cover the losses.}
{119}{}{I'm not going to work from morning till evening with people carrying a fat wallets walk past me.}