{100}{}{You see a prisoner.}
{101}{}{You see a badly tortured prisoner.}

{102}{}{H-help me! P-please! Don't leave me here!}
{103}{}{I'm all w-wounded... I won't last long... Do you have a stimpak or something?}

{104}{}{Thanks, friend! I'll return to the city and tell everyone about the one who saved me.}
{105}{}{How did you end up here?}
{106}{}{What Harrelson did to you?}
{107}{}{What do you know about Harrelson?}
{108}{}{Bye.}

{109}{}{I'm from Salt Lake. When I lost my job, the Quok brothers advised me to go here. They said "there's a frail old man with good belongings". And I took the bait. At the entrance I fell into the trap, then Harrelson raked me in the cave.}
{110}{}{It was damn creepy with him. It seems that he didn't do anything, really, but he got on my nerves so much that I almost lost my mind! Sometimes he would sit by me with a calm face and yelp about my nature. That son of a bitch! Peeped straight into my soul... I'm glad he's dead!}
{111}{}{This bastard is hundred years old. He survived the nuclear war. He didn't talk much about himself, but I didn't ask. All I wanted is to get out of here.}

#Женские реплики
{1104}{}{Thanks, friend! I'll return to the city and tell everyone about the one who saved me.}