{100}{}{These ones will sell for a good price on the market.}
{101}{}{Try not to damage the merchandise.}
{102}{}{You'll make a spirited slave.}
{103}{}{This is not good.}
{104}{}{Retreat!}
{105}{}{Maybe I'll sell furniture instead.}
{106}{}{Fellow slavers should not attack one another.}
{107}{}{The guild will hear of this!}
{108}{}{What are you doing?}
{109}{}{Any luck?}
{110}{}{Find any good slaves?}
{111}{}{We're looking for a new stock.}
{112}{}{This is our territory.}