{100}{}{A very deep hole. It still reeks strongly of excrement, but it's no longer throbbing.}
{101}{}{Before you, you see something that defies common sense! You can't tell if it's alive or not, but it's pulsating and emitting toxic fumes.}
{102}{}{This does nothing.}
{103}{}{The hole is pulsating and emitting toxic fumes. You don't want to go in there.}
{104}{}{If you intend to descend into that stinky hole, you'll need a rope to get down.}
{105}{}{You already lowered a rope down this hole. You don't need another one.}
{106}{}{The rope is fastened and lowered down.}
{107}{}{It's still too dangerous to go down there... And why would you want to do that? Come to your senses!}
