{100}{}{You see a monster.}
{101}{}{You see an ugly mutant. It appears to have been formed by the fusion of several humans and dogs.}
{102}{}{We... See... Light...}

{110}{}{Long time no dinner with the guests!}
{111}{}{We avenge the puppies!}
{112}{}{The Master was right about one thing!}
{113}{}{We hate hummies!}
{114}{}{The Master will swallow up mankind just like he consumed us!}
{115}{}{No one will escape the Master's retribution!}
{116}{}{Cursed be the Master for what he did to us!}
{117}{}{Kill us!}
{118}{}{We hear your thoughts!}
