{100}{}{You see a nomad.}
{101}{}{you see an experienced nomad of Great Basin.}

{110}{}{[Frowns, seeing you] You shouldn't come so close. It's already too hot in here.}
{111}{}{[Curiously looks at you] Hi! Are you traveling too?}
{112}{}{[Gives you a blank look] Just traveling? Or running from someone?}

{113}{}{I'd like to buy provisions for the journey. Could you trade some?}
{114}{}{I wonder what people like you are doing in these uninhabited lands.}
{115}{}{I've been on the road for a while already. Tell me, where is the nearest town?}
{116}{}{I should probably continue my journey. Farewell.}
{117}{}{That's all I can exchange. If it's not enough, you'll have to go to the city.}
{118}{}{Speaking of the city. Tell me, where I can find one?}
{119}{}{We wander from valley to valley in search of a suitable place to live. We originate from the Northeast. There was a series of war conflicts, so many fled from there. You will surely meet other nomads like us.}
{120}{}{Salt Lake is in the North. Go along the highway and you'll walk straight into the city near a large lake.}
