{100}{}{I must warn sergeant Graves!}
{101}{}{I must warn the city guards!}

{102}{}{Outworld scum...}
{103}{}{Degenerate filth...}
{104}{}{Die, outsider!}

{110}{}{Can we help you, citizen?}
{111}{}{Greetings, citizen. It's good to see you.}
{112}{}{We worried that you could be hurt, citizen.}
{113}{}{You have to stay vigilant in these parts of the wasteland. Watch out for roads, citizen.}
{114}{}{That's it? Not the most useful advice you can give me.}

{120}{}{I need medical assistance!}
{121}{}{Could you escort me to the Vault?}
{122}{}{Could you escort me to Gerlach?}
{123}{}{Could you escort me to Black Rock?}
{124}{}{Any news from recent patrols?}
{125}{}{}
{126}{}{I'll be on my way.}
{127}{}{Can you give me an advice about surviving in the wastes?}
{128}{}{Only one - stay away from highways. Going off-road may take more time, but it is safer - less chance meeting people.}

#Лечение
{129}{}{You don't have any serious injuries. If you do not feel well, the doctor in the vault will help you.}
{130}{}{Hold on, citizen, we will help you!}
{131}{}{[Wait]}
{132}{}{You should be fine now.}
{133}{}{Thank you.}

#Перемещение в поселения
{134}{}{Yes, of course.}
{135}{}{Let's get going then!}
{136}{}{I think I'll go without you.}
{137}{}{Yes, of course. We will escort and leave you near the town.}
{138}{}{Yes, of course. We will escort and leave you near the town.}

#О патрулировании
{140}{}{This is dangerous place to travel alone without any protection.}
{141}{}{This is safe place, you don't meet outsiders too often. Usually they are loners - fugitives or treasure hunters.}

{142}{}{Raiders in south-east are very active lately. This is clearly not a good sign.}
{143}{}{We rarely meet raiders these days. It seems like something is keeping them away from the south-east.}

{144}{}{We haven't seen any folks from Gerlach in a long time. No smoke, no fires. It seems that people abandoned these lands. This is good news.}
{145}{}{Not long ago, we saw a train heading to the east.}
{146}{}{Also some bastard killed }
{147}{}{our people on patrol. I don't know who it was, but he's sure one tough son of a bitch.}
{148}{}{}

{149}{}{ I have nothing more to tell you.}
{150}{}{}
