{100}{}{You see a young soldier.}
{101}{}{You see a rookie from the Wind of War. It is clear that he is not happy with this duties.}

#О'ве'ные реплики, когда еще ни один из рейдеров не уби':
{110}{}{Not now! Danger from all sides!}
{111}{}{It's dangerous! Don't move out of the cover!}
{112}{}{Hey, you're not one of those raiders? If you can't help, don't bother!}
{113}{}{No time to explain, the enemies are everywhere!}
{114}{}{Hey, you got a gun? Then shoot, for your life!}

#Разговор, когда рейдеры уби'ы, но не силами ГГ:
{120}{}{Phew... [breathing heavily, grabs his chest and sits on the ground leaning on his arms] Hey, you're lucky that I didn't took you for a raider, or you would lie down on the ground, like the others.}
{121}{}{Yeah, sure. Anyway, what happened?}
{122}{}{There were three of us, we patrolled the area, when the raiders attacked us from their cover. I was quick to fight back and run, but they continued to follow me. Hell, just a little more time and I would have been roasted hard.}
{123}{}{Hmm. Show me your clip... Oh, I see.}

{124}{}{Damn, because I'm a rookie, I was given little ammunition. What were they thinking, dammit! And you? At least you could help!}
{125}{}{I have to save ammo, ha-ha.}
{126}{}{Sorry, it was difficult for me to understand what's going on.}
{127}{}{Oh, really? Well then, don't be angry if someone *mistakenly* just kicks you up the ass from the Wind of War. And now I have to go join my brothers in arms and tell them the whole story. You go your own way, wanderer.}
{128}{}{Yeah.}
{129}{}{That so? Hmm. Sounds plausible. Anyway, now I should go join my brothers in arms in the Wind of War and tell them the whole story. You go your own way, wanderer.}
{130}{}{Wait, can you show where the Wind of War is?}
{131}{}{Take care.}
{132}{}{Open your map. Go along the road, then turn North then so and so. Here is the station, where caravans stop, this is just the place for visitors like you. Now I gotta go.}
{133}{}{Thanks.}
{134}{}{You got the exact coordinates of the Wind of War.}

#Разговор, когда рейдеры уби'ы все или неко'орые силами ГГ:
{140}{}{Phew... [breathing heavily, grabs his chest and sits on the ground leaning on his arms] Thank you, wanderer, if not for you, I would be burning in hell.}
{141}{}{What happened?}
{142}{}{I see, your ammo is almost gone.}
{143}{}{Damn, right, as a rookie I was given a very few rounds. What were they thinking, dammit! I was lucky to meet you along the way.}
{144}{}{Yeah...}
{145}{}{Look, I will get back to my brothers in arms in the Wind of War, I will tell them about your help. Surely they will appreciate it. But now I have to go. Thanks again.}
{146}{}{Take care.}
{147}{}{Your help to the recruit increased your reputation in the Wind of War.}

#Female character:
{1124}{}{Damn, because I'm a rookie, I was given little ammunition. What were they thinking, dammit! And you? At least you could help!}
{1127}{}{Oh, really? Well then, don't be angry if someone *mistakenly* just kick you up the ass from the Wind of War. And now I have to go join my brothers in arms and tell them the whole story. You go your own way, wanderer.}
{1129}{}{That so? Hmm. Sounds plausible. Anyway, now I should go join my brothers in arms in the Wind of War and tell them the whole story. You go your own way, wanderer.}
{1140}{}{Phew... [breathing heavily, grabs his chest and sits on the ground leaning on his arms] Thank you, wanderer, if not for you, I would be burning in hell.}
