{100}{}{You see a young soldier.}
{101}{}{You see a rookie from Wind of War. It is clear that he is not very happy with this duties.}

#О'ве'ные реплики, когда еще ни один из рейдеров не уби':
{110}{}{Not now! They are still around!}
{111}{}{It's dangerous! Take cover!}
{112}{}{Hey, you're not one of those raiders! If you can't help, don't bother!}
{113}{}{No time to explain, the enemies are everywhere!}
{114}{}{Hey, you got a gun? Then defend your life!}

#Разговор, когда рейдеры уби'ы, но не силами ГГ:
{120}{}{Phew... [Breathing heavily, he grabs his chest and sits on the ground, leaning on his hand] Hey, you're lucky I didn't take you for a raider, or you'd be lying dead on the ground like the others.}
{121}{}{Yeah, sure. Anyway, what happened?}
{122}{}{There were three of us patrolling the area when the raiders ambushed us. I quickly fought back and ran away, but they kept chasing me. Hell, a little more time and I would have been toasted.}
{123}{}{Hmm. Show me your clip... Oh, I see.}

{124}{}{Damn, since I'm a rookie, they gave me little ammunition. What were they thinking, dammit! And you? At least you could help!}
{125}{}{I need to conserve ammo, ha-ha.}
{126}{}{Sorry, it was difficult for me to understand what's going on.}
{127}{}{Oh, really? Well then, don't be angry if someone *mistakenly* just kicks you up your ass from the Wind of War. And now I have to go join my brothers in arms and tell them the whole story. You go your own way, wanderer.}
{128}{}{Yeah.}
{129}{}{Really? Hmm. Sounds plausible. Anyway, now I should go join my brothers in arms in the Wind of War and tell them the whole story. You go your own way, wanderer.}
{130}{}{Wait, can you show where the Wind of War is?}
{131}{}{Take care.}
{132}{}{Open your map. Go along the road, then turn here and here. You'll see the station where caravans stop, that is the place for visitors like you. Now I gotta go.}
{133}{}{Thanks.}
{134}{}{You got the coordinates of Wind of War.}

#Разговор, когда рейдеры уби'ы все или неко'орые силами ГГ:
{140}{}{Phew... [Breathing heavily, he grabs his chest and sits on the ground, leaning on his hand] Thank you, wanderer, if not for you, I would have burned in hell by now.}
{141}{}{What happened?}
{142}{}{I see your ammo is almost gone.}
{143}{}{Damn, right, as a rookie I was given a very few. What were they thinking, dammit! I was lucky to have you around.}
{144}{}{Yeah...}
{145}{}{Look, I will get back to my brothers in arms in the Wind of War, I will tell them about your help. Surely they will appreciate it. But now I have to go. Thanks again.}
{146}{}{Take care.}
{147}{}{Helping the recruit increased your reputation in the Wind of War.}

#Female character:
{1124}{}{Damn, since I'm a rookie, they gave me little ammunition. What were they thinking, dammit! And you? At least you could help!}
{1127}{}{Oh, really? Well then, don't be angry if someone *mistakenly* just kick you up your ass from the Wind of War. And now I have to go join my brothers in arms and tell them the whole story. You go your own way, wanderer.}
{1129}{}{Really? Hmm. Sounds plausible. Anyway, now I should go join my brothers in arms in the Wind of War and tell them the whole story. You go your own way, wanderer.}
{1140}{}{Phew... [Breathing heavily, he grabs his chest and sits on the ground, leaning on his hand] Thank you, wanderer, if not for you, I would have burned in hell by now.}
