{100}{}{You see a robot.}
{101}{}{You see a robot. You have a feelings it might be hostile.}
{102}{}{Welcome.}

#Выкрики при нападении
{110}{}{Alarm! Trespasser is in sight!}
{111}{}{Activate security systems!}
{112}{}{Activating the protocol of eliminating trespassers! Engaging.}

#Попытка заговорить
{120}{}{Welcome to "Poseidon Oil" Power Plant! Please do not disrupt public order and keep facility grounds clean.}
{121}{}{We apologize for any further inconvenience. We hope no such incident occurs again.}
{122}{}{Welcome, visitor.}
{123}{}{Welcome, visitor. We are always glad to see you.}

#Попытка отключения
{130}{}{Robot is disabled.}
{131}{}{This one is done for.}

{132}{}{You fail to make sense of the robot's systems and only draw unwanted attention.}
{133}{}{Unauthorized personnel shouldn't do this.}
{134}{}{Don't make me use force.}
{135}{}{Trespasser detected! Eliminate immediately!}

{136}{}{You lack the repair skill to successfully disable the robot.}
