#Комп в АЭС - часть первая
{100}{}{You see a working terminal.}
{101}{}{You see a reactor control terminal.}

#Применение наркоты на криттере, который за это нападает на ГГ:
{126}{}{Shouldn't have done that!}
{127}{}{}
{128}{}{I don't need that!}
{129}{}{Not a chance! That's forbidden.}
{130}{}{Don't even think of doing it again!}
{131}{}{We are not allowed to try this.}


#Для кола-продаж
{150}{}{You've closed a Nuka-Cola deal. Congratulations!}
{151}{}{You received a new achievement.}
{152}{}{The deal of the Nuka-Cola sale in this establishment is no longer valid.}
{153}{}{Looks like this place's revenue is about to plummet.}

#Комп в АЭС - часть вторая
{160}{}{You succeeded in breaking into the system. Judging from documents inside, this plant wasn't used solely for peaceful purposes by the government.}
{161}{}{Look at reports on uranium ore supply.}
{162}{}{Look at "Lovelock" radio station project.}
{163}{}{Look at "Lovelock" radio station coordinates.}
{164}{}{Look at PoseidonNet debugging report.}
{165}{}{As uranium ore was used by the military, its mining and distribution was under strict governmental control. So "Poseidon Oil" power plant had to undergo regular inspections and maintain impeccable accounting. According to these records, at the time of the power plant shutdown there was enough uranium in stock to keep the plant running for another 250 years straight in economy mode.}
{166}{}{By special decree a separate power branch was provided to supply a radio tower near Lovelock settlement. The facility was marked as of critical significance and was supervised by the military. The nuclear power plant should have supplied the station with enough power.}
{167}{}{You download the station coordinates to your Pip-Boy.}
{168}{}{Apparently this station is located in the same spot as the Cheyenne tribe.}
{169}{}{You have already downloaded the coordinates. The station is located in the South.}
{170}{}{It's a computer network designed for long-distance communication. It's purpose is to connect different military and governmental facilities of the United States. The network is offline now, which isn't particularly surprising.}
{171}{}{[Finish]}
{172}{}{You download the station coordinates to your Pip-Boy. Apparently this station is located in the same spot as the Cheyenne tribe.}
{173}{}{Evidently it's that station by the Cheyenne tribe settlement you have already visited.}

#########################################################################
#
# Стандартные фразы для компьютеров и терминалов
#
#   Внимание ! Этот раздел текста используется по умолчанию в большинстве компьютеров и терминалов Невады.
#     То есть этот текст используется в целом ряде скриптов.
#
#########################################################################

{200}{}{You cannot use the computer during combat.}
{201}{}{Your science skill is too low for this operation.}
{202}{}{Science skill is needed in order to use this computer.}

#########################################################################



#########################################################################
#
#            Реакция нпс на крики и ловушки
#
#########################################################################

#-------------- Начало реплик

#Тест для охотничьего свистка Эвана
{388}{}{Who's been shouting?!}
{389}{}{Damn tourists!}
{390}{}{I won't fall for it again!}

{391}{}{?!}
{392}{}{!!}
{393}{}{ }

#Для трудяг, фермеров, горожан
{400}{}{Who's been shouting?}
{401}{}{Why would you be shouting like that?}
{402}{}{Are you talking to me?}
{403}{}{I can hear just fine!}
{404}{}{Can you keep it down a little?}
{405}{}{Lunatics roam freely...}
{406}{}{Something's wrong?!}
{407}{}{What's the matter?!}
{408}{}{Never a cop around when you need one}

{450}{}{I won't fall for it again!}
{451}{}{Here we go again, some more psychos!}
{452}{}{No way, I better stay where I'm at...}
{453}{}{What? Again?!}
{454}{}{How many more times!}
{455}{}{Settle down already!}

{460}{}{Is this a prank or something?}
{461}{}{So, what happened?}
{462}{}{Who was screaming?}
{463}{}{I don't get who's been shouting}
{464}{}{Wasn't somebody shouting here?}
{465}{}{Damn tourists! They really getting on my nerves!}
{466}{}{That's it, I'm not acting on it anymore!}
{467}{}{Uh... What was that?}

{470}{}{WHAT? WHAT HAPPENED?!}
{471}{}{Did somebody get stabbed?!}
{472}{}{Goddammit!?}
{473}{}{What's the ruckus!!?}
{474}{}{Uh... What was that?}
{475}{}{}
{476}{}{}
{477}{}{}

#Для примитивных существ:
{500}{}{Who be screaming?}
{501}{}{Why you shouting?}
{502}{}{You hollering at me?}
{503}{}{Me hear, yes yes...}
{504}{}{Hey you! You too loud!}
{505}{}{Evil spirits took your mind}
{506}{}{What be wrong?!}
{507}{}{You step on a spike?!}

{550}{}{No, me only go when evil spirits scream no more}
{551}{}{Spirits be playing tricks again!}
{552}{}{No, me better not go...}
{553}{}{What? Again?!}
{554}{}{Not again!?}
{555}{}{You too wild, should give you some sleeping herbs}

{560}{}{Your joke bad!}
{561}{}{Eh?!}
{562}{}{Where the shouting at?!}
{563}{}{Me no understand, where evil spirits be?}
{564}{}{Phew... Should smoke less herbs...}
{565}{}{Me having visions?}
{566}{}{No, me only go when evil spirits scream no more}
{567}{}{Eh...}

{570}{}{WHAT?! WHAT HAPPENED?!}
{571}{}{Fight!? Who be fighting!?}
{572}{}{Oh!? Evil spirits!!!}
{573}{}{Me no understand, who be screaming?}
{574}{}{Eh?}
{575}{}{}
{576}{}{}
{577}{}{}

#Для агрессивно настроенных существ и крутых парней (рейдеры, бандиты, охранники):
{600}{}{Why the hell are you screaming like a lunatic?!}
{601}{}{Hey, dipshit! Stop shouting!}
{602}{}{Are you shouting at me, motherfucker?}
{603}{}{Hey, I can hear just fine, cut it out!}
{604}{}{What the hell are you trying to do here?}
{605}{}{Looks like we got another loon here...}
{606}{}{Did someone tear something off of you? Why are you screaming like that?}
{607}{}{God damn it, shut up already!}
{608}{}{Go to hell!!}
{609}{}{God-fucking-damn it, shut the hell up already!}

{650}{}{Don't mind this one, clearly out of his mind}
{651}{}{Fuck it!}
{652}{}{I better just look at what's going on from a distance...}
{653}{}{What? Again?!}
{654}{}{How many more times?!}
{655}{}{Look, another dimwit}

{660}{}{Damn, missed the most interesting part!}
{661}{}{Damn, late for the show again!}
{662}{}{Wasn't somebody getting stabbed here?}
{663}{}{Can someone tell me where the hell did the screaming come from?}
{664}{}{Damn, there was a fight and now it's gone! Wonders!}
{665}{}{Shit, am I hearing things?!}
{666}{}{Err... Was it just my imagination acting up?}
{667}{}{To hell with it, I'ma take a nap}

{670}{}{WHAT? WHAT HAPPENED?!}
{671}{}{Yeah! Someone's having their ass kicked!!}
{672}{}{Finally a rumble!!}
{673}{}{A brawl? I should go have a look!}
{674}{}{Dammit, what was that?}

#Для браминов
{700}{}{Moo!}
{701}{}{Moo-o!}
{702}{}{Mooo!}
{703}{}{Moo?}
{704}{}{Moo-moo?}

#-------------- Конец реплик