{100}{}{You see the security console.}
{101}{}{You see the console for controlling the station's security system.}
{102}{}{The scientific method is required to activate the console.}

{103}{}{You have already disabled security system.}
{104}{}{It won't work.}
{105}{}{You have hacked and disabled the security system.}
{106}{}{Your scientific knowledge is not enough to hack this console.}
{107}{}{I can't.}
{108}{}{That's better!}
{109}{}{You failed to hack the security system this time.}
{110}{}{Fail.}
{111}{}{}
{112}{}{Security system does not respond.}
{113}{}{No signal.}