{100}{}{You see a crane.}
{101}{}{You see a rusted crane. You shouldn't expect much.}
{102}{}{The chain is in no condition to be used. You need to replace it with something.}
{103}{}{This crane could probably be useful to you, but it doesn't have a chain.}
{104}{}{You replaced the chain with a rope. Should be enough for light weights.}
{105}{}{You've already replaced the chain.}
{106}{}{You don't need it anymore. Leave it to rust in peace.}
{107}{}{Using a crane, you erected a pyramid of debris near the wall of the garage.}
