{100}{}{}
{101}{}{You see a working computer. Now it is in "sleep" mode.}

#Общие реплики
{110}{}{This computer is still running in power saving mode. The only thing visible on the main terminal is a recording - a request sent via an internal network.}
{111}{}{[Read the message]}
{112}{}{[End]}
{113}{}{[More]}
{114}{}{I'm corporal Dickens and I write this entry for those who will get into the garrison after us. Today is the 25 of october, 2077. Yesterday the city of Hawthorne was subjected to a massive nuclear attack from the damnable Reds. Our security system was barely able to divert the missiles away from the city and garrison. Several dozen of nuclear explosions occured in the vicinity. Hawthorne became a zone of strong irradiation, because of the huge amounts of radioactive dust raised by the explosions. And the level is constantly increasing.}
{115}{}{We have launched an automated unit for cleaning the area from radiation, but, apparently, it's too late. The population of the city does not know where to hide from this invisible threat. The only local shelter was destroyed during the bombings. Most of the civilians left to Reno and Las Vegas, those who stayed are dying from radiation in their homes. The city is under curfew. We don't know what happened to the rest of the world. Communications to other military bases and Washington are lost. Perhaps, this is the worst case scenario, and the whole country is in ruins.}
{116}{}{Staying in Hawthorne is impossible, I took over command and decided to leave the base together with the remnants of the garrison. We'll take the transport, supplies, provisions and arms, and then, with our families, will go inland. Probably, it's safer this way than to stay here. We will activate the permanent security system to prevent looting. You can disable it from only one place - the V9 hangar. God help us. God help you.}