{100}{}{You see a guest.}
{101}{}{You see a traveling merchant. He is now resting from the road and gaining strength for the long journey.}
{102}{}{Thank you for your help.}

{110}{}{Yes? What do you want?}
{111}{}{Just to chat a little, if you don't mind.}
{112}{}{Nothing. Wrong door.}
{113}{}{That's great, of course, but I'd like to get some rest from the road after all the hustle and bustle. You know, sometimes you have to run around to figure things out. Also, my purse got stolen! I can't get enough of thieves in this town.}
{114}{}{Your purse got stolen? Tell me more about it.}
{115}{}{Then I won't be distracting you from your melancholy. Goodbye.}
{116}{}{It was an old leather purse with a bunch of papers and notes. There was no money in it. The last time I used it was at the caravan merchants' office. Then I came back here, and the purse was gone! I don't even know who could have robbed me and when, it's a pretty short walk from the office to here.}
{117}{}{So, on the way from the caravaneers to the hotel... I'll remember it.}
{118}{}{If you find it, I'll pay.}
{119}{}{Good.}
{120}{}{Yes?}
{121}{}{Tell me again about your stolen purse.}
{122}{}{Nothing, nevermind.}
{123}{}{Your purse was found. Don't ask where. I have my own professional secrets.}
{124}{}{What a relief! If it hadn't turned up, you can't imagine how much time and effort I would have spent recovering the papers. Thank you very much. I promised you a reward. Here's $100.}
{125}{}{You don't need to pay. Taking rewards for other's belongings isn't really fair.}
{126}{}{You're welcome. Be careful in this town. Now I need to go.}
{127}{}{You're a wonderful person! Thank you again.}
{128}{}{You're welcome. Be careful in this town. Now I need to go.}

#Женские реплики
{1112}{}{Nothing. Wrong door.}