{100}{}{You see a raider.}
{101}{}{One of Big Louie's vultures, chaperoning you to Hawthorne.}
{102}{}{Oh my god! They killed Kenny!}

#Êîãäà ïî íàïàðíèêó ïîïàäàå' 'óðåëü (äëÿ ãåðîÿ-ìóæ÷èíû):
{104}{}{Goddammit!}
{105}{}{Where the hell are you leading us?!}
{106}{}{You little... I warned you!}
{107}{}{Fuck this! I'm not your fucking bodyguard!}
{108}{}{When I'm done with him, you're next on my list, motherfucker!}
{109}{}{You asshole! I'll remember this!}

#Äèàëîã:
{110}{}{So? Are you just gonna keep talking?}
{111}{}{Stay here while I check things out.}
{112}{}{I found a safe passage. Come with me.}
{113}{}{Wait here, I have some scouting to do.}
{114}{}{Forget it.}

{115}{}{Don't bug me, I'm resting.}
{116}{}{Give me a boost over the fence.}

#Ñäà÷à êâåñ'à
{130}{}{The security systems are down! It's safe to search the storage rooms... What?}
{131}{}{I'll be damned... I thought you'd be useless, but the boss was right about you. Good job. Anyway, I got shit to do. You get back to the base.}
{132}{}{Right. See you.}

{133}{}{Those turrets look nasty. Can you think of a way to get past them?}
{134}{}{Look, those turrets gotta run on electricity or something, right? Unplug the generator and that'll do it. I dunno, you figure it out.}
{135}{}{Right.}

{136}{}{Don't you want to come with me? Before, you wouldn't take your eyes off me.}
{137}{}{Nah. I'm gonna wait here until you get the job done. It'll be safer alone. Anyway, if you try running off - it's your funeral.}
{138}{}{Right.}

#Ïåðâûé ðàçãîâîð
{140}{}{This is the place. Here's the plan: Boss wants us to find a way into the military base so we can get some of those guns and ammo in storage. Actually, he wants YOU to find a way into the base, because I ain't risking my ass for this. And no funny stuff, or you can consider yourself dead. You got that?}
{141}{}{I got that. Where are the guns and ammo stored?}
{142}{}{Yeah, yeah, cut the attitude. And stay close, so I don't have to save your sorry ass every time there's trouble.}
{143}{}{We're at the edge of a dead city. We gotta cut through it to get to the base. It's guarded by turrets, so watch your ass.}
{144}{}{I've got it. Let's do this.}
{145}{}{You're right. Let's talk for a minute.}

#Âîïðîñû
{150}{}{What? Something else?}
{151}{}{What is this place?}
{152}{}{What's our mission?}
{153}{}{Where are the warehouses?}
{154}{}{Another question.}
{155}{}{Enough chitchat. Let's go.}
{156}{}{Hawthorne, a dead city. Everyone that lived here died in the Great War. Now it's full of nothing but rats, turrets, lowlifes, and every other type of shit you can imagine.}
{157}{}{Are you deaf? We have to get the guns and ammo in the base, and to do that, we need to take out those turrets. As long as they're around, we can't get in.}
{158}{}{Somewhere north. Inside the base.}
{159}{}{Here. Right behind the fence.}
{160}{}{Does anyone live here?}
{161}{}{There's no one here but prospectors, and only the desperate ones. They fight for any piece of a copper wire. The radiation wiped out everyone that actually lived in this place - all that's left of them are bones in the streets.}


#Female character (Èâàí):
{1104}{}{Goddammit!}
{1105}{}{Where the hell are you leading us?!}
{1106}{}{You little... I warned you!}
{1107}{}{Shit! I'm not your fucking bodyguard!}
{1108}{}{When I'm done with him, you're next on my list, you bitch!}
{1109}{}{You bitch! I'll remember this!}

{1112}{}{I found a safe passage. Come with me.}
{1114}{}{Forget it.}
{1115}{}{Don't bug me, I'm resting.}
