{100}{}{You see a minesweeper bot.}
{101}{}{A standard issue robot, modified for mine-sweeping operations.}
{102}{}{System check... No errors... Waiting for instructions...}

{103}{}{(The robot is waiting for direct instructions)}
{104}{}{[Send the robot on a mine-sweep run around the garrison's perimeter and storage facilities]}
{105}{}{[Leave]}
{106}{}{Execute "search and disarm" protocol... Loading...}
{107}{}{Go on, move it!}
{108}{}{Begin.}