{100}{}{Security turret.}
{101}{}{You see a security turret armed with pair of miniguns.}

#Попытка обезвредить ремонтом
{102}{}{You can't do that during combat!}
{103}{}{You can't make heads or tails in this complicated system.}
{104}{}{You short-circuit the wires and the turret bursts into flames.}
{105}{}{It won't do any good now.}

#Фразки партнеров-рейдеров
{110}{}{Hey! Quit your whining, let's go!}
{111}{}{That was awesome. Now what?}
{112}{}{Eh, I'd rather not say anything about that.}
{113}{}{Wrap it up already!}
{114}{}{Leave the turret, we gotta go!}
{115}{}{Stop wasting time, I'm getting hungry!}