{100}{}{A warehouse door.}
{101}{}{It's a huge metal door of the warehouse.}
{102}{}{Looks like the door is blocked from the other side. It can't be opened from here.}
{103}{}{Even blow this strong didn't make the door budge.}

{104}{}{The door is jammed from the inside, it can't be opened from here.}
{105}{}{Jammed from the inside.}
{106}{}{With great effort, you finally manage to open the door.}
{107}{}{The door is jammed for good now, it's not going to open.}
{108}{}{The door won't budge.}

