{100}{}{You see a slot machine.}
{101}{}{This slot machine isn't working. You wonder if there i still change left inside.}

#Использование навыков и пр. на автомате:
{102}{}{You can't do anything with your bare hands.}
{103}{}{This slot machine isn't working. Did you expect to gamble?}
{104}{}{}
{105}{}{You couldn't pick the lock of this slot machine.}
{106}{}{You take a good swing and bash the rusted casing off. Now all the change belongs to you.}
{107}{}{Using the proper tools, you easily open the machine and take the change.}
{108}{}{You were unable to kick the lid off this thing. Too weak.}
{109}{}{The rusty lock on this machine poses no challenge. Now all the change belongs to you.}

#Когда взломал автомат:
{110}{}{Yeah, just like that!}
{111}{}{Shake it, baby!}
{112}{}{Shake it, baby!}
{113}{}{Ha-ha!}
{114}{}{Some pocket money.}
{115}{}{Hey, there's still some change left in here!}
{116}{}{Boy, isn't it satisfying!}
{117}{}{That's better!}
{118}{}{Kiss my ass, slot machine! I did it!}
{119}{}{Now I'm rich!}

{120}{}{You've already forced this slot machine open and cleared it of all change. There's nothing left inside.}
{121}{}{No use.}
{122}{}{This slot machine has been broken for a long time. You won't get anything from it with just your bare hands.}
{123}{}{You can't do anything with this.}
{124}{}{You found }
{125}{}{ bucks.}

#Female character:
{1110}{}{Yeah, that's it!}
{1111}{}{Shake it, baby!}
{1112}{}{Shake it, baby!}
{1113}{}{Ha-ha!}
{1114}{}{Some pocket money.}
{1115}{}{Hey, there's still some change left in here!}
{1116}{}{Way to go, girl!}
{1117}{}{That's better!}
{1118}{}{Kiss my ass slot machine! I did it!}
{1119}{}{Now I'm rich!}
