{100}{}{You see a minesweeping robot.}
{101}{}{This recon robot was programmed to defuse mines. You can hardly expect more from it. Looks like the control program contains errors.}
{102}{}{You cannot do that while in combat.}
{103}{}{You need to use your head here, not your hands.}

#Навыки
{110}{}{You fail to fix the program's code - which is unsurprising, considering your skills...}
{111}{}{To assemble the robot is pretty easy. But to make it work you'll have to fix errors in its control program.}
