{100}{}{It's a switch.}
{101}{}{You see the switch that switches on the lights in the hangar... Or switches off, whichever you prefer.}
{102}{}{You switch on the hangar lights.}
{103}{}{You switch off the hangar lights.}
{104}{}{The electric field hurts you!}
{105}{}{Nothing happens. It seems that the hangar has no power.}

{110}{}{Ugh... I hope I get to the light switch before I break my legs here.}
{111}{}{It looks like this underground hangar was used for maintenance of pre-war equipment.}