{100}{}{It's a switchboard.}
{101}{}{The switchboard is buzzing, which means that the electricity is still going somewhere.}
{102}{}{The switchboard is out of order. Permanently.}

{103}{}{This won't help here.}
{104}{}{You were unable to de-energize the turrets with this switchboard.}
{105}{}{The short-circuit shuts down the shield, and suddenly the turrets outside freeze.}
{106}{}{This skill is useless here.}
{107}{}{The switchboard is no longer supplying power to the turrets. However, it doesn't matter now.}
{108}{}{You don't have enough strength to rip these wires.}

{109}{}{A little bit more, and you'd have been electrocuted.}
{110}{}{You were electrocuted, but your armor absorbed the shock.}
{111}{}{You were electrocuted! The boots partially absorbed the shock.}
{112}{}{You were electrocuted!}