{100}{}{You see the service computer.}
{101}{}{You see an ordinary service computer.}

{110}{}{System loaded.}
{111}{}{[Sort documents by date]}
{112}{}{[Quit]}

{113}{}{Done.}
{114}{}{Transcript of the last commission meeting.}
{115}{}{The commission's resolution on the case of desertions.}
{116}{}{Tests of the new radio signal jamming system.}
{117}{}{Acceptance act of the "dirty bombs".}
{118}{}{Monitoring data on the Vault 8.}
{119}{}{Information about the military radio station in Lovelock.}

{120}{}{[Back]}
{121}{}{}
{122}{}{Due to the case of mass desertions, a commission was organized. The commission provided a report, which was handed over to the garrison commander.}
{123}{}{The order to test a line of signal jammer of the next generation came through today. Tests are scheduled for October 17, 2077. The beginning of test scheduled at 18:28, the end at 21:02. Location: Hawthorne test site. All units must be fully operational. To the engineering department: prepare the device for testing, conduct an off-schedule inspection of the computer security systems from failures. Transfer the device from the warehouse to the hangar V9 under the receipt of the responsible quartermaster.}
{124}{}{A cargo of 5 containers with a radioactive isotope arrived at the V9 hangar for temporary storage in army warehouses.}
{125}{}{As it turned out, the military in Hawthorne kept the Vault 8 under constant monitoring. They mostly collected the computer and automated system's data and were engaged in wiretapping communications. Hawthorne was given the responsibility for the security of the Vault in case of the invasion of the enemy's army or natural disasters. The observation object is assigned with a high priority level.}
{126}{}{The military radio station at Lovelock provided communications and engaged in surveillance on Vault 8.}
{127}{}{Write down the Lovelock's coordinates.}
{128}{}{Hmm. It is where Cheyennes live now. Maybe some of the locals know where this station is located.}
{129}{}{I have been there already.}
