{100}{}{You see the service computer.}
{101}{}{You see an ordinary service computer.}

{110}{}{System loaded.}
{111}{}{[Sort documents by date]}
{112}{}{[Quit]}

{113}{}{Done.}
{114}{}{Transcript of the last commission meeting.}
{115}{}{The commission's resolution on the case of desertions.}
{116}{}{Tests of the new radio signal jamming system.}
{117}{}{Acceptance act of the "dirty bombs".}
{118}{}{Monitoring data on the Vault 8.}
{119}{}{Information about the military radio station in Lovelock.}

{120}{}{[Back]}
{121}{}{}
{122}{}{Due to the case of mass desertions, a commission was organized. The commission submitted a report to the head of the garrison.}
{123}{}{"Today the order for testing a line of next-generation signal jammers came in. Tests are scheduled for October 17, 2077. Tests will start at 6:28 p.m. and end at 9:02 p.m. Location: Hawthorne Test Site. All units must be fully operational. To the Engineering Department: prepare device for testing, conduct unscheduled computer security checks to prevent malfunctions. Transfer the device from the warehouse to the V9 hangar upon receipt of the responsible quartermaster."}
{124}{}{A shipment of 5 containers with a radioactive isotope was delivered at the V9 hangar for temporary storage.}
{125}{}{As it turned out, the military at Hawthorne kept Vault 8 under constant surveillance. They mainly collected data from computer and automated systems and tapped communications. Hawthorne was charged with the responsibility of keeping the Vault safe in case of enemy invasion or natural disasters. The object of surveillance was assigned a highest priority level.}
{126}{}{The military radio station at Lovelock served as a point of contact for communications and surveillance of Vault 8.}
{127}{}{Write down Lovelock's coordinates.}
{128}{}{Hmm. It is where Cheyennes live. Maybe some of the locals know where this station is located.}
{129}{}{I have been there already.}
