{100}{}{You see a biker.}
{101}{}{You see Jay Kukish. Yes, the one.}
{102}{}{I don't trust you, but you can be helpful in battle.}

{110}{}{Stay calm. The paralyzing agent may give you a little headache, but you'll be back to normal in no time.}
{111}{}{So it was a trap. Let me out of here, you bastard! Immediately!}
{112}{}{Why to hide behind armored glass? Come over here, let's talk like real men.}
{113}{}{I see you planned it all out. Paralyzed me and locked me in here. Smart. Guess I don't have much of a choice now.}
{114}{}{Let's not waste time. Get to the point. Why did you do all this?}

{115}{}{[You wake up in a bright, closed room. You see a biker watching you through thick glass.]}
{116}{}{You...}

{120}{}{Threats won't help you. You can't get out of here unless I let you. So just sit tight and don't move.}
{121}{}{Or what, you'll knock me out again? Wait till I get my hands on you!}
{122}{}{Okay, I'm not going to resist for now. Let's talk.}
{123}{}{You're pretty sneaky for a biker. Luring me into a trap in a place like this... Are you afraid of someone?}

{124}{}{Maybe you'll get that chance. But for now you're going to stay locked up. I wanted to ensure the safeness of our conversation.}
{125}{}{Safeness?! You're just a pussy! Hiding behind glass because you're afraid of me.}
{126}{}{Right. Let's cut to the chase.}
{127}{}{This is reasonable. At least this way we don't shoot each other.}
{128}{}{Your attempts to piss me off are ridiculous and pathetic. The kind of the reaction I expected from the residents of the vault. You're like children suffering from teenage problems and delusions far beyond your age. I'll wait until you calm down. After all, there's nothing preventing me from leaving. Unlike you.}
{129}{}{You're not leaving until you spit out the truth! Tell me, bitch, tell me everything you know!}
{130}{}{All right, I'll try to calm down. In the meantime, tell me how you tracked me down.}
{131}{}{That's more like it.}
{132}{}{Tell me how you managed to track me down.}
{133}{}{Don't even think about it. I won't give you the satisfaction.}
{134}{}{We'll see about that!}
{135}{}{Okay. But now tell me how you managed to track me down.}

{136}{}{[Sneers] How cute. Did you pick this up in the wasteland? I see these travels have left their mark... But let's not waste time on useless chitchat. You can't get out of here unless I let you.}
{137}{}{Oh, really? And if I try, you'll knock me out again? Wait till I get my hands on you!}
{138}{}{Exactly. You can't get out of here unless I let you. So don't waste your time with idle chitchat.}
{139}{}{Okay! Enough talk, let's settle this for real! With fists!}
{140}{}{Finally, I hear the voice of reason in your childish babble. Notice that I'm not threatening you yet. The stun trap went off after the radio jammer was turned on. I brought you here to ensure the safeness of our conversation.}
{141}{}{[Grimly nods] You can't trust anyone in this world. You want to talk to me, you'll have to stick to my rules. Note that I'm not threatening you. The stun trap went off after the radio jammer was turned on. I brought you here to ensure the safeness of our conversation.}

{142}{}{There has been a bug planted in your Pip-Boy. It is most likely present in all Pip-Boys that were issued to the dwellers of vault 8. I used it to track you down, but so could someone else. The signal jammer temporarily solved that problem. Don't worry, I've already dismantled the bug, just in case.}
{143}{}{Who else knew about this? Your friends, the bikers from Bridgeport?}
{144}{}{Bullshit! You already warned those Bridgeport bikers, didn't you?}
{145}{}{No. I have a strained relationship with my brothers. We have different paths. Though admittedly, I was the one who started the rumor that something big is going to happen in Hawthorne.}
{146}{}{}
{147}{}{Is something really going to happen here?}
{148}{}{You're hiding on this base for a reason, aren't you? Doors, monitors, traps - an arsenal of a true coward.}

{149}{}{Hawthorne was a military base before the great war. The military themselves mothballed it and left, the small local population gradually died out. Many prospectors tried to reach the resources of this base... But it would have been better for them to stay away. Anyway, I'm here for another reason. The whole vault 8 thing is clearly military and government related. I came here looking for information.}
{150}{}{Okay, wait. So you don't actually know anything? Why then did you steal the device from the vault then?}
{151}{}{I don't understand. You have to start from the beginning of all these events.}
{152}{}{Oh yeah... You don't remember, right? The employer warned me...}
{153}{}{Dr. Willmouth works wonders! He restored my memory and he can treat radiation poisoning. Yes, he is a real wizard. And he has an Autodoc.}
{154}{}{Doctor at the vault got me my memory back with an Autodoc. And when I get out of here, you're going to regret that he did it.}
{155}{}{You seem to be properly informed, but did not consider the possibility of memory recovery with the help of the Autodoc in the vault.}

{156}{}{Do you really believe that? Autodoc is unable to conduct such a serious operation. I've seen more sophisticated devices, but even they were not able to replace the consciousness of the patient. And to erase someone's memory... [he suddenly chuckles] You don't need an Autodoc for that. Most likely, there's something else going on in your vault that you don't know about. Something that slipped out of your mind while Doc was doing his "experiments" on you.}
{157}{}{I suppose... Wait a minute! Don't bullshit me, you son of a bitch! It's because of you I lost my memory!}
{158}{}{I believe in Dr. Willmouth's honesty! Your stupid smirk just shows that you're lying and not telling me something. Didn't you have a hand in my amnesia?}
{159}{}{It doesn't matter anymore. Past is past. What I'm interested in now is what you did with the stolen device.}

{160}{}{It was my employer who deprived you of your memory. I only used your body as an excuse to enter the vault.}
{161}{}{So, what happened in the vault?}
{162}{}{Should have known you're just a pathetic mercenary. And what was your job in there?}

{163}{}{My job was to get into the vault, knock out the guards and steal the device. You don't need me to tell you that.}
{164}{}{What were you talking about with the Overseer before you knocked him out?}
{165}{}{What is the purpose of the device you stole?}
{166}{}{Who's that employer you mentioned?}
{167}{}{Okay, this part of the story is clear now.}

{168}{}{It was a long conversation. Basically, the old man was interested in my life outside of the city, and I asked about the vaults and its technologies. I'm not gonna repeat it all.}
{169}{}{At first I couldn't understand it myself. It was only in Area 51 that I managed to figure it out. There were the most advanced technologies that I had never seen anywhere else.}
{170}{}{I would like to know it too. Who he is, where he got your body, why he needed a device from the vault - I don't know any of this. But it doesn't interfere with my interests.}
{171}{}{}
{172}{}{What do you mean?}
{173}{}{The crystal-based information storage module is a very rare and breakthrough technology at the time of the War. Why the hell did it end up in such a miserable place as a bomb vault? I couldn't find the means of reading the data, but my guess is that the disk contains programs to coordinate the automatic control systems of the vault... And probably something else, not so obvious.}
{174}{}{Why didn't you deliver the device to your employer?}
{175}{}{When it comes to sophisticated pre-war technology, I don't care about employers. I decided to figure out what it is first. Such an opportunity with this kind of tech rarely presents itself.}

{176}{}{If it's clear to you, why the hell did you go to so much trouble to find me?}
{177}{}{Sorry, but without the device the vault will fall to the threats of the wasteland. I can't let that happen.}
{178}{}{Because of your technological ambitions, they kicked me out of the vault and forced me to return the device.}
{179}{}{At this point, I don't care about the vault or the device. I want revenge on the people who started all this. And you are one of them.}
{180}{}{I was just given an assignment. The rest is none of my business.}
{181}{}{I see. You can have the device, I don't care what happens to it now. I'll drop it here. I've got something else to worry about now. Although, if you want to know more about such tech, I suggest you to visit Area 51 - a lot of beautiful things there, even better than you have already seen. [Looks at the monitors next to him] Oh, shit...}
{182}{}{What?}
{183}{}{We have company. And they will have to be dealt with.}
{184}{}{Wait, I want to fight too! Together it will be easier.}
{185}{}{Yeah, go straight to them. I hope they'll torture you slowly and painfully.}
{186}{}{Hey, don't leave me here! I'm going to starve to death!}
{187}{}{If you have any brains at all, you will find a way out. Farewell.}
{188}{}{So you've already familiarized yourself with the vault and its inhabitants. What do you think of my home?}
{189}{}{You are like children. It's funny to explain to people like you that Santa Claus isn't real.}
{190}{}{[End dialogue]}
{191}{}{[He just chuckles back and walks away to the elevator.]}
{192}{}{Not a chance. I can't trust you after this conversation. There's too much ambiguity in what you say - first you play tough, then you beg. Either your head is a mess, or you think I'm an idiot. That won't work.}
{193}{}{Well, fuck you! I wish you'd die out there!}
{194}{}{That's okay. Maybe we'll get even. Try to not get in my way.}
{195}{}{I'm just offering. Don't regret it later if you refuse.}
{196}{}{Wait! I just don't know how to talk to you. Believe me, all I want is to better understand all this.}
{197}{}{[He looks at you, then at the monitor, then back at you.] Okay. But once we're out of the danger zone, we'll part ways. If you want to get out of here without risk, try to sneak to the back door. It is located right near the railway gate of the hangar. A little room to the right. Try not to miss it.}
{198}{}{All right, thanks!}

{1157}{}{I suppose... Wait a minute! Don't bullshit me, you son of a bitch! It's because of you I lost my memory!}
