{100}{}{You see Doctor Willmouth.}
{101}{}{You see Ian Willmouth. People usually call him Doc.}

#Хохма при подробном осмо'ре
{102}{}{Why are you staring at me like that?}
{103}{}{I feel like I'm being watched... }

#Сообщения в консоль:
{104}{}{You get 100 experience points for learning more about Harold and his background.}

####################################################
#
#         Самый первый диалог
#
####################################################

{110}{}{I'm glad to see you're awake, }
{111}{}{. You're probably confused, aren't you? Yes, you probably have a lot of questions, especially about your amnesia. I would have preferred the Overseer to wait longer before sending you outside, but nonetheless, I am glad to see that your brain is recovering. Oh, and if you don't remember, my name is Dr. Willmouth.}
{112}{}{I can't remember anything, Doc. What happened to me?}
{113}{}{That is to be expected. Your brain has been exposed to the destructive influence of the outside world. I won't go into detail, but the important thing is that we were able to restore it. Unfortunately, part of your memory was lost forever.}
{114}{}{How did this happen?}
{115}{}{You were brought to us by a stranger, calling himself a biker, tied up in the back of his two-wheeled vehicle. You can ask Sergeant Graves about him. When you were brought to me, you had limited mobility and were not aware of your surroundings. I diagnosed brain damage and severe memory loss.}
{116}{}{I'll talk to Graves. Can I count on your medical help in the future?}
{117}{}{Of course. If you need medical attention, I will do everything I can to help. The Overseer himself has ordered it.}
{118}{}{Can you give me any advice before I leave the city?}
{119}{}{Watch out for radiation and avoid physical contact with dead or living organisms.}

{120}{}{I appreciate your help, Doc, but it would be easier to treat myself in the field, instead of trying to get to you every time I get hurt.}
{121}{}{You're right. Your body is still very weak and your immune system has not yet recovered.}
{122}{}{I need something for emergency situations. Is there anything you can do to help me?}
{123}{}{I can give you a stimpak or one first aid kit. The first is a chemical that increases the regeneration rate of damaged cells. The second is a set of various medicines and tools for more serious procedures. A stimpak does not require medical knowledge, while a first aid kit certainly does.}
{124}{}{I'll take a stimpak.}
{125}{}{I'll take the first aid kit.}
{126}{}{This is all I can do. Anything else would be noticed, and I may be called before the committee. That's the last thing I want right now.}
{127}{}{Thanks, Doc.}
{128}{}{Maybe, but self-treatment is very dangerous for an amateur. You can overdose on chemicals or get the bandage wrong. It's best to avoid these situations altogether.}
{129}{}{I understand, Doc.}

{130}{}{You lied to me! You didn't restore my memory, you overwrote it with a new one!}
{131}{}{How did you- did you break into my computer? How extraordinary! I should be angry, but I'm actually proud. I've never performed such a successful personality transfer. Granted, with you it was easier.}
{132}{}{You've done this to someone else?!}
{133}{}{Only a couple of times, usually due to accidental brain traumas. But your case was unique. Your brain was damaged in a very precise, very specific way. Whoever did this to you obviously wanted you to survive it.}
{134}{}{Is it even possible to do something like that?}
{135}{}{It would have required an advanced lab and a very skilled surgeon. Even I couldn't perform such an operation. It definitely happened outside of Vault City. Before you showed up, you were officially missing for a few months... Which explains a lot.}
{136}{}{Then I'll have to look for answers somewhere else. I'm sure that biker knows something... And doctor, don't mention it to anyone until I get to the bottom of this.}

{140}{}{I recently had a dream about being a part of the first team to go outside the vault. What does that mean, Doc?}
{141}{}{Dreams are a rare occurrence among our citizens, I can't tell you much about them. Given the amount of time that has passed since the first expedition outside the vault, I can tell you that it's probably nothing special. Could it be something subconscious? I'm sure you'll find an explanation later.}
{142}{}{Okay, Doc.}

{143}{}{Then I must speak to him. Take care, Doctor Willmouth.}
{144}{}{That's useful advice. I need to see Sergeant Graves.}

{306}{}{Can you tell me more about radiation?}

{307}{}{Sure. What do you want to know?}
{308}{}{Are there any specific areas I should avoid?}
{309}{}{How can I treat my radiation poisoning?}
{310}{}{How high the level of radiation poisoning must be to be dangerous?}
{311}{}{What effect does prolonged exposure to radiation have on the body?}
{312}{}{I think that's about it. See you later.}

{313}{}{I already knew that. Goodbye.}
{314}{}{Obviously, it's better to avoid places with high radiation levels. But sometimes individual objects emit radiation too. Especially large metal objects, such as old cars.}
{315}{}{Rad-X pills will boost your body's natural resistance against radiation. They should be taken before entering contaminated areas. If you are already exposed, RadAway will remove the radiation from your body. There might be other chemicals that could be of help, but I'm not aware of any.}
{316}{}{Keep your radiation levels below 100 rad. Anything exceeding that needs to be treated.}
{317}{}{Long-term radiation exposure will have negative effects on your body, such as weakness, clumsiness and loss of stamina. You will recover with treatment, but it will take time.}
{318}{}{Take care, citizen }
{319}{}{. And long live Vault City!}
{320}{}{Long live Vault City!}
{321}{}{Yeah, I'll see you around, Doc.}

####################################################
#
#         Основной диалог
#
####################################################

#Первая реплика дока:
{400}{}{Hello, our savior. I'm doing my best, despite all the mess. How can I help you, }
{401}{}{?}
{402}{}{You don't look very good! Believe me, taking this crap won't make your problems go away.}
{403}{}{Yes, }
{404}{}{? How can I help?}
{405}{}{Helping everyone in the city is difficult sometimes. But they are worthy people.}

{406}{}{Well, I'll go.}
{407}{}{You look terrible! You should have come by earlier.}

#Мед. помощь:
{410}{}{I need medical attention.}
{411}{}{Take a seat. This won't hurt at all.}
{412}{}{Okay, Doc, I trust you... }
{413}{}{Better answer couple of questions for me.}
{414}{}{No, I can take care of it myself.}
{415}{}{Done. Next!}
{416}{}{Thanks, Doc, but I have some more questions.}
{417}{}{Thanks, Doc.}

{418}{}{I have a fever, a headache and internal bleeding. What is happening to me?}
{419}{}{Let's find out. Sit in the Auto-Doc, please... }
{420}{}{Heal me, Doc!}
{421}{}{I have some things to do first. I'll be right back.}
{422}{}{What, again? Was the last treatment ineffective? Well, let's try again shall we.}
{423}{}{[Doctor Willmouth examines you and finds a viral infection] I gave you some antivirals to help with the infection. You should be fine now, but I can't guarantee that the virus won't come back. Be more careful next time.}
{424}{}{How could I get infected anyway?}
{425}{}{What would have happened if you hadn't treated me?}
{426}{}{Thanks, Doc, I feel a lot better now.}
{427}{}{Well... Honestly, the immune system of our citizens is weaker than of those who live in the wasteland. Any creature you came into contact with could have infected you. Try to remember... Maybe you were bitten by something, like a dog or an insect, or touched something. You could get an infection from someone or something that looks perfectly healthy.}
{428}{}{It's hard to say for sure, but an infection like this won't go away easily. If you can adapt to it, you won't suffer from symptoms, but it could hurt your body in other ways.}

####################################################
#
#         Вопрос о клонах
#
####################################################

{480}{}{Doc, you knew that we're clones, didn't you?}

{481}{}{Honestly speaking - yes, I knew that.}
{482}{}{Then why didn't you say anything?}
{483}{}{Is every person in the city a clone?}
{484}{}{Are you a clone too?}
{485}{}{What do you think about Vault 8's mission?}
{486}{}{Would you sacrifice yourself in favor of your "prototype"?}
{487}{}{I don't even want to talk about it.}
{488}{}{}
{489}{}{}
{490}{}{}
{491}{}{}

{492}{}{To tell the truth was unacceptable. Otherwise, we'd have to lock everyone up.}
{493}{}{Not everyone. Vault management consisted of native vault dwellers. But many of them got old and died, because they couldn't produce their own clones, or it would lead to disarray, and eventually - riots in the city.}
{494}{}{Yes. I was created "from a test tube" shortly after the vault closed its doors. But after the original doctor, Richard Moreau, disappeared, our government needed another reliable person on the medical staff, so I was told some truth and put in this position. But there was a lot I didn't know!}
{495}{}{Hmm. Perhaps it was cruel of the government to create a whole city as a lab for their own selfish purposes. But our bodies helped saving lives of many people... I don't know how I feel about it. I need to think it over, before I judge anyone.}
{496}{}{You know, perhaps to be someone's clone isn't so bad. I mean, look at you - in the vault we were happy, educated, protected. How many places like this exist in the wasteland? To happily live half a life to then save someone else's... It's not so bad, the way I see it. People outside the city are far less lucky.}
{497}{}{}
{498}{}{}
{499}{}{}

####################################################
#
#     Вопрос о Гарольде и квес' о му'ациях
#
####################################################

{500}{}{Did you see that mutant guy in the cells?}
{501}{}{Let's talk about mutations.}

#Про Гарольда и му'ации
{510}{}{The mutant? He was exposed to some sort of unknown virus, but radiation could have played a part too. On the other hand, the virus extends his lifetime. Along with his sufferings.}
{511}{}{Could he infect us?}
{512}{}{What do you think of Harold's mental abilities?}
{513}{}{Tell me about Richard Grey.}
{514}{}{Tell me about the mutations.}
{515}{}{I think that's enough about that.}

{521}{}{Not likely. He himself is not a source of radiation, nor is he a viral carrier.}
{522}{}{Despite his mutation and age, this mutant is... Like a teenager. He likes to fool around, but understands everything perfectly. He retained the will to live... At least, for now. Who knows, maybe being able to live unnaturally long life will someday change him.}
{523}{}{Richard Grey? We have never had any citizens by that name. Perhaps you are referring to Richard Moreau. He mysteriously disappeared during the first expedition to the outside world. That was a long time ago.}
{524}{}{Harold said he knew Richard Grey from Vault 8.}
{525}{}{I wouldn't take him seriously. Who knows what's going on in his head? Richard Moreau theoretically could change his name, of course. But I doubt it's the case.}

{530}{}{There are three types of mutations I'm aware of, if we classify them by genesis factor: from toxins, radiation and viruses. The first two are usually very unstable and lead to various forms of death. But viral mutation is... Special. Unfortunately, I have little knowledge in this field. I simply have no material to conduct the research.} 
{531}{}{You need a mutant for your research?}
{532}{}{No, not a living one. I'd like to compare Harold's blood samples with those of the various mutated creatures in the wasteland. I've tried to organize a research team to collect samples several times, but the committee always denies me. They say the patrols risk their lives enough without having to worry about my research.}
{533}{}{I can get those samples for you.}
{534}{}{You can? I didn't think of that! Take this set of sterile syringes and collect samples of animal blood from the wastes. I'm interested in pig rats, coyotes and geckos. Or their kind, at least. Write it down to remember. And be careful! If something happens, I can provide you with medical assistance.}
{535}{}{Where can I find those animals?}
{536}{}{Good. But I have another question.}
{537}{}{I'll see what I can do.}
{538}{}{Pig rats can be found in the west ruins. For coyotes you'll have to look elsewhere, but patrol reports suggest you can find them in the desert to the south-east. Geckos are all over the place, but usually congregate near the mountains.}

#Квес' на му'ации
{540}{}{Did you get the samples?}
{541}{}{I have a sample of pig rat blood.}
{542}{}{I have a sample of coyote blood.}
{543}{}{I haven't managed to get coyote blood. How about dog or wolf?}
{544}{}{I have a sample of gecko blood.}
{545}{}{Not yet. I wanted to talk about something else.}
{546}{}{Not yet. I'll go and take care of it right now.}

{550}{}{Excellent! We should freeze the sample immediately...  [He takes the sample from you]}
{551}{}{[Next]}
{552}{}{Oh yeah, if you gather more samples, bring them to me.}
{553}{}{Okay, Doc.}
{554}{}{Oh yeah. I think that's all I needed. These samples would be enough for a couple weeks of research. I'm very grateful, thank you.}
{555}{}{You're welcome, but... Doc, after I interacted with those dead mutants, I feel kinda strange... Nauseous, feverish, my head hurts... What's happening to me?}
{556}{}{Quick, sit down so I can examine you... }
{557}{}{[Next]}
{558}{}{You're fine now. It was just an infection.}
{559}{}{Inn-feck-shin?}
{560}{}{I think I understand what you're talking about - microorganisms and viruses invading the body, leading to an immune reaction.}
{561}{}{I see you've managed to learn the basics. Good job! Very impressive for a person that just got out of a coma.}
{562}{}{But how could such a tiny thing cause such a strong reaction?}
{563}{}{Heterogeneous microorganisms and viruses invade the body, leading to an immune reaction. The symptoms you described are how your body is fighting the invasion.}
{564}{}{I'm afraid, this is a common problem for vault citizens. You see, our bodies are used to sterile and clean habitat. The wasteland, on the other hand, is anything but that. An organism can adapt to an infection only if it often receives it in small doses, and due to our clean living environment, our immune systems are not exposed to many infections. That's why you got sick so easily.}
{565}{}{What will happen, if it don't treat it in time?}
{566}{}{That depends on the severity of the infection. Some will go away with your noticing them. Stronger infections will cause nausea, fever and other unpleasant symptoms. The strongest ones can lead to your death. Keep yourself healthy so you won't end up looking like Harold. But as I said before, after some time of exposing to infections, your body will adapt to them.}
{567}{}{How can I treat it on my own?}
{568}{}{You should see a doctor if possible, but if you find yourself infected in the middle of the desert, try to mix antibiotics with xander root. The mixture needs to be heated, so you'll need a fire. Not perfect, but in an emergency situations it'll do. Clean water will help too, if you can find a thing like that in the wasteland.}
{569}{}{Willmouth taught you how to treat infection using wild plants and a camp fire.}
{570}{}{How long can the sickness last?}
{571}{}{Your body will fight as hard as it can, depending on your endurance. If you isolate yourself from the outside environment, your body will eventually clear the infection entirely. If you're constantly exposed to a hostile environment however, your infection will spread much faster.}
{572}{}{Thanks for the explanation, Doc. It will come in handy outside the city.}

####################################################
#
#     Про слуг из Джерлака
#
####################################################

{600}{}{Have you met our new servants yet?}

{601}{}{Yes. Very interesting material to study.}
{602}{}{Did you examine them?}
{603}{}{Are they dangerous to us?}
{604}{}{What do you think about their mental abilities?}
{605}{}{Don't you think is unethical to stuff them with pills?}
{606}{}{}
{607}{}{}
{608}{}{I'm interested in something else.}
{609}{}{That's all, I wanted to know.}

{610}{}{Yes, otherwise they would not be released from the isolation block.}
{611}{}{Well, it depends on what you mean by that. In terms of viruses or infections - no.}
{612}{}{They're a miserable lot. But they can carry on a conversation and even be train... Err, educated.}
{613}{}{No, I don't. We give them medication twice a day to suppress their wills and urges, so they work instead of causing trouble. Believe me, this is in our best interest.}

####################################################
#
#             Жен реплики
#
####################################################

{1115}{}{You were brought to us by a stranger, calling himself a biker, tied up in the back of his two-wheeled vehicle. You can ask Sergeant Graves about him. When you were brought to me, you had limited mobility and were not aware of your surroundings. I diagnosed brain damage and severe memory loss.}
{1318}{}{Take care, citizen }
{1400}{}{Hello, our savior. I'm doing my best, despite all the mess. How can I help you, }
{1407}{}{You look terrible! You should have come by earlier.}
{1424}{}{How could I get infected anyway?}
