{100}{}{You see Sergeant Graves.}
{101}{}{You see Peter Graves, head of Vault City security.}
{102}{}{What happened here?!}
{103}{}{Shortly before you returned, the city was attacked.}

#Îáùàÿ âå'âü äèàëîãà âíå êâåñ'îâ:
{110}{}{There's nothing else to report. From now on, you'll have to act on your own.}
{111}{}{Take care.}
{112}{}{Who is that strange guy in the cell?}

{113}{}{I had a dream that I'm part of the first team to go outside of the vault. Has anything like this ever happened to you?}
{114}{}{No. Like all normal citizens, I've never had any dreams. I know that Doctor Willmouth has encountered this anomaly a few times, but never paid any attention to it. Neither should you. It's probably nothing.}
{115}{}{Okay.}

#Äèïëîìà' èç Ëàâëîê:
{140}{}{I came across some interesting documents at Lovelock radio station. I thought they might be of interest to you.}
{141}{}{[Carefully studies the documents] Hmm. According to this papers, our vault has been under surveillance for quite a long time. The station provided a means of communication between our vault's computer systems and a certain governmental vault. Consider this information classified! We have to do a thorough check of all systems and try to rule out outside control altogether. Thank you for this valuable find. Carry on with your mission.}
{142}{}{Of course.}

#Ñ'àð'îâûé äèàëîã:
{150}{}{I see you are feeling better. Doctor Willmouth did a great job with getting you back on your feet. He recommended not to give you any assignments, but we have no choice. Something terrible has happened - something we should have expected an outsider might do.}
{151}{}{What are you talking about?}
{152}{}{It seems that the man who brought you back to Vault City did it only to break into the vault. He stole a device critical to the vault's safety and prosperity. We cannot catch up with his vehicle on foot. Being the only citizen who has traveled well beyond the city limits, you are the only one we can trust with this assignment. Find the device and bring it back.}
{153}{}{I understand what you're saying, but I can't remember anything. I need to know more about what happened.}
{154}{}{Of course. Doctor Willmouth warned us about your amnesia. Ask away.}
{155}{}{Tell me everything.}
{156}{}{A man calling himself a "biker" brought your senseless body to the city. You've been missing for quite some time. The man introduced himself as Jay Kukish and demanded to see the Overseer. They had a long talk while Dr. Willmouth tended to you. After some time, the biker used some kind of neutralizing weapon to render the guards and the Overseer unconscious. He then stole the device from the vault and fought his way out of town. Do you have any more questions?}

{157}{}{Yes, I have other questions.}
{158}{}{No more questions.}

{159}{}{Good. What do you want to ask about?}
{160}{}{Tell me everything you know about Jay Kukish.}
{161}{}{Tell me more about that stolen device.}
{162}{}{How do I find that biker?}
{163}{}{Will I get any gear for my travels?}
{164}{}{What should I expect in the outside world?}
{165}{}{What if I refuse to help?}
{166}{}{}
{167}{}{}
{168}{}{Okay. Another question.}
{169}{}{I think that's all I wanted to know.}

{170}{}{He's wearing a dirty leather jacket with a flaming skull symbol on the back. He may have changed his clothes, but my guess is that he doesn't do that very often. He's rude, aggressive, and, apparently, is only interested in technologies. He arrived and left on his two-wheeling speed vehicle. That's all I can tell you about him.}
{171}{}{I don't know neither the name of this device nor its exact purpose. Judging by the reports, it was vital to some of our automated systems, including security. Without it, we are vulnerable to external attacks.}
{172}{}{I recommend following his tire tracks. Our patrols report that they may lead to a place called "Black Rock". It is located south-east from here. Surely the locals must know something.}
{173}{}{The Overseer did not assign you any equipment, but everything you had when you were brought here is in the Warehouse. Perhaps other citizens can lend you something.}
{174}{}{I don't have much information for you. We have had reports from our scouts about settlements located nearby... If you can call them settlements. Sometimes we make contact with travelers in the wasteland, but we usually try to scare them away. They don't belong here.}
{175}{}{You don't have a choice. Your citizenship has been suspended until you return the device. There are only a few standard procedures available to you, reduced medical care is among them.}
{176}{}{He says he's a caravan merchant, traveling between Nevada and California. Our patrol apprehended him while he was scouting our perimeter. He says he was searching for a nuclear plant. Looks like he's telling the truth. Still, we must be careful with outsiders, so we'll keep him locked down for a while. Doctor Willmouth says he was exposed to some sort of virus, poor guy. But you don't need to worry about him. Get back to your duties.}

{186}{}{Well, good luck. Stop by the warehouse to pick up your belongings. And remember - be careful when interacting to the people in the wasteland. Do not mention the existence of this city to anyone. That would be all.}
{187}{}{Consider it done, sir!}
{188}{}{You received new quest. Open your Pip-Boy to check its status.}

#Fuse
{200}{}{I need a replacement fuse for a water pump, but I've been denied. Can you help me?}
{201}{}{You'd better have a good reason for this.}
{202}{}{Gerlach needs a replacement part for their water pump. I want to help them.}
{203}{}{[Lie] I have a contact outside the city. He wants the fuse in exchange for information.}
{204}{}{I don't have any good reasons, but I'll find them!}
{205}{}{}
{206}{}{}

{207}{}{I hope you know what you're doing. We can't just hand out our technology to everyone around. I will put in an order to the warehouse for you. Now go.}
{208}{}{Thanks.}

{209}{}{Gerlach? The community to the south? Why would we give them anything? Anyway, Sergeant Stark is responsible for the south sector. You can find him in the building across the street.}
{210}{}{Thank you. I'll go find the sergeant.}

#Ïðî íàïàäåíèå Ñîáèðà'åëÿ Äóø
{300}{}{What a strange coincidence - just when our city is in trouble again, you show up.}
{301}{}{What happened here?}
{302}{}{We were attacked. Everything happened very quickly. The attackers seized the Overseer and dragged him outside the city's perimeter.}
{303}{}{I have a bad feeling about this. Too good to be a coincidence.}
{304}{}{Tell me everything.}
{305}{}{I managed to track down the biker and retrieve the stolen device. We were attacked by mysterious people. My Pip-Boy was bugged. Someone's been operating behind our backs, Sergeant. And they've been doing it for a long time.}

{306}{}{Hmm... The Overseer used to say similar things, but I didn't understand him then. He said a change was coming, and we had to be ready. That was off the record.}
{307}{}{Tell me more about the attack.}
{308}{}{We were assaulted by a group of men in combat armor, led by a hooded figure. They infiltrated the city using some kind of paralyzing agent that we were unable to counter. While the guards and other citizens were incapacitated, the enemies seized the Overseer and left the city perimeter. Some of the guards were able to recover and tried to apprehend the invaders, but were immediately killed.}
{309}{}{What do they need the Overseer for?}
{310}{}{I assume it has something to do with the stolen device and the Overseer's knowledge. He knows something about the vault that none of the guards or ordinary citizens do. In any case, the Overseer was taken beyond our surveillance area - that is, too far away for us to reach. This means that it is unlikely that the kidnappers intend to bring him back.}
{311}{}{I have the device. Here.}
{312}{}{I see. That's good. Still, only the Overseer knows how to use it.}
{313}{}{What are you suggesting?}
{314}{}{The Overseer knows information about the vault that no one else does. Information that would be extremely dangerous if used in a wrong way. That's why it cannot fall into the hands of the kidnappers. At any cost. Do you *understand* me, citizen?}
{315}{}{Looks like I have a new mission.}

{316}{}{Good. There is no one else I can trust with this. No one else has such knowledge and experience as you do.}
{317}{}{Any more clues?}
{318}{}{We've managed to determine that the kidnappers are traveling using train. Our radar tracked the Overseer's Pip-Boy until it got out of range. Perhaps this information will be useful if you find another radio station.}
{319}{}{Understood. I'll see what I can do.}
{320}{}{You are our last hope, citizen.}
{321}{}{Yeah, sure. First you suspend my citizenship and kick me out of the city, and now suddenly I'm your last hope! Great, whatever, I'll take care of everything. Again.}
{322}{}{I understand. I hope, when this is over, everything goes back to the way it was. See you soon, Sergeant.}
{323}{}{}
{324}{}{You're implying I should kill the Overseer?! Are you out of your mind?!}
{325}{}{We have no choice. His knowledge is a weapon that can kill us all.}

#Female character:
{1314}{}{The Overseer knows information about the vault that no one else does. Information that would be extremely dangerous if used in a wrong way. That's why it cannot fall into the hands of the kidnappers. At any cost. Do you *understand* me, citizen?}
{1320}{}{You are our last hope, citizen.}
