{100}{}{The ruins of this old settlement give out the feeling of oblivion. Time has stood still here since the end of the Great War.}
{101}{}{You enter the outskirts of Hawthorne. It's pretty quiet here.}
{102}{}{You enter a garrison territory. The silence here makes you nervous.}
{103}{}{}
{104}{}{Marauders have already been here.}
{105}{}{This military store was looted by prospectors a long time ago.}
{106}{}{}
{107}{}{Hey, looks like this generator still works...}
{108}{}{It seems that the stupid and greedy prospectors accidentally activated the local security systems. Now the city is flooded with hostile robots.}
{109}{}{A message from Jay Kukish pops up on your Pip-Boy screen.}
{110}{}{Wha... How is this possible?!}
{111}{}{This building is in a state of emergency. Apparently, no one set foot here in years.}