{100}{}{You see old man Vernon.}
{101}{}{You see Vernon, an old city dweller and an opinionated bookworm.}
{102}{}{I may be old, but I still have some life in me!}

#Диалог про Диогена:
{119}{}{Still looking for answers? Well, I may have some for you.}

{120}{}{Welcome to my humble dwelling!}
{121}{}{Greetings! How can a lonely old man be of help to you?}
{122}{}{Diogenes would surely find the "humble dwelling" part funny.}
{123}{}{Ha! If you knew more about him, young man, you'd understand that that "humble dwelling" of Diogenes was quite *sufficient* for him and the conditions he lived in: after all, the climate, the scenery, the company...}
{124}{}{But there are other reasons for his living in a barrel. For him it was about rebellion and self-expression.}
{125}{}{Sure, sure, but... What are you getting at?}
{126}{}{The point is, you shouldn't belittle yourself when you have quite a decent place to live in and comprise the active part of the city's population.}
{127}{}{But I am the poorest man in this city!}
{128}{}{There you go again.}
{129}{}{Well... Okay, let's change it to "I am the poorest among the 'active part of the city's population'" then.}
{130}{}{Do you mean to say that the tramps on the streets are not a part of this city?}
{131}{}{Indeed, they are not. The city is bigger and beggars only work to disgrace it.}
{132}{}{But the beggars are a direct result of the city's activity, they were begot by the city and the will also be consumed by it, if the situation changes for the better.}
{133}{}{They are on the same level as polluting emissions. Like smoke coming out of a plant's chimney - it's not a part of the city anymore.}
{134}{}{So you say that beggars are also not a part of the city? That is absurd.}
{135}{}{How so?}
{136}{}{Don't you think that if a part of the whole becomes something big and independent, it stops being a part, and thus, becomes another whole, but the whole, which it's not a part of anymore, does not depend on it?}
{137}{}{Hmm... Yes. You are right.}
{138}{}{So, we have just learned that...}
{139}{}{[For the last few hours, you have been having a visionary discussion with the bookworm about dividing a whole into parts and assembling parts into a whole.]}
{140}{}{...and thus, the whole, still being a part of the lesser whole, continues to be a whole, while, at the same time, being a part of the other whole, as the other whole remains a part of that whole.}
{141}{}{An excellent conclusion! I see your deduction skills are unparalleled.}
{142}{}{Quite so! It was a pleasure arguing with you. Goodbye!}

#Диалог про историю города:
{150}{}{You seem way more intelligent than other people in this city. Perhaps you know the history of the place?}
{151}{}{I sure do. I'll be happy to tell you about the city and the history of its establishment. If you have time, of course, as it is quite a long story.}
{152}{}{Please, tell me about it.}
{153}{}{Unfortunately, I don't have time for long stories.}
{154}{}{Here it goes, then. [He acts as if reading a fairy tale to children near a fireplace.] This is a tale of great people and their hard every day work.}
{155}{}{[More.]}
{156}{}{Salt Lake City was built before the war. It was a big city by American standards. Many people were scurrying about here, trains were moving up and down the railroad, and factories were steaming with smoke. The city was buzzing and was always in motion.}
{157}{}{After a while, a small gambling zone was set up, with not very expensive casinos and restaurants, which had big signs and shining corbels...}
{158}{}{The city was by no means clean, as it was still an industrial center. It produced electricity, plants were operating, salt and copper were mined... There was even a military base with its own airfield in the north of here...}
{159}{}{And then...}
{160}{}{God save us! The radios began crying about an impending nuclear threat! In panic, the residents were signing up for queues to enter large underground vaults, safe shelters constructed by the Vault-Tec Corporation. Small companies that had been engaged in the pool construction business started to make private mini-vaults, designed to hold families. There are hundreds of them in Salt Lake, scattered around the basements of various buildings.}
{161}{}{Then everything calmed down. Armed conflicts subsided and people started to forget about the bombs. Nobody knows who had fired first. It may have been the Russians, or the Chinese, or even us. It doesn't matter now. The past is dead and gone.}
{162}{}{The most astute ones hid inside the big vault in the Wasatch Range east of here, while the rest sheltered in their family vaults and in basements. Those who lived in this part of Salt Lake City were luckier, as the bombs mostly fell in the northern area, where the military base was situated. The local climate smoothed the consequences of the blasts, washing off the nuclear fallout with autumn rains then weighing it down with snow.}
{163}{}{People didn't begin to emerge from the vaults until 10 to 30 years after the war. At the end of the day, nobody liked to spend their life confined within metal walls.}
{164}{}{Those who were brave were the first to come out, while others took their time. The last of the remaining vault dwellers saw the sun only a few years ago.}
{165}{}{Those first to emerge saw at once that the outside world was not safe anymore. Radiation and mutated animals frightened the citizens. Some of the people also didn't have the cleanest of hands. So, a council was called and a sheriff elected, with the task of building a new society on the ruins of the old city.}
{166}{}{The Sheriff set about fighting crime. He gathered a team of determined people around him and helped many enterprises and organizations gain ground... It was not an easy task, of course.}
{167}{}{The city is... Fragile, so to speak. Every prominent figure here is a pillar on which it stands. Should one of the pillars collapse, the whole city will follow.}
{168}{}{I hope you find my story interesting. Would you be so kind as to offer me a cup of tea for the effort?}
{169}{}{Gladly! Here are 10 bucks as a tip. Thanks!}
{170}{}{Oh, no, I don't have money with me.}
{171}{}{Oh well. It is a pity, because I'm hungry.}
{172}{}{Goodbye.}

#Прово
{180}{}{Do you know anything about Provo's population?}
{181}{}{Oh yes. It's an old story. The inhabitants of Provo were like the Ku Klux Klan from before the war. At first, the Sheriff used their bigotry and extremism for his own cause. He employed them to deal with certain undesirables, and when things improved he got rid of them. Since then, those rednecks hate the city and its citizens. They consider us crooks. After a while, they turned to brigandage, with criminals of all sorts joining their ranks.}
{182}{}{The Sheriff asked me to deal with those criminals...}
{183}{}{Oh? Well, it's no surprise. The rednecks has already robbed several caravans and even tried to sabotage the city. But the Sheriff doesn't want to openly wage war against them. You see, nobody knows much about Provo. There are bound to be a lot of traps scattered around the place waiting for an unwary target to set them off. The tactical situation is against the Sheriff, that's for sure. Anyway, if you decide to venture into the area, be on your guard and pay full attention to your surroundings.}
{184}{}{Understood.}

#Библиотека
{190}{}{I haven't seen such a large collection of books anywhere else. Where do the books in your library come from?}
{191}{}{Well, I gathered these books from around the ruins with my own hands, believe it or not.}
{192}{}{What a great example of selfless devotion to culture and education! You're a remarkable person.}
{193}{}{A weird fetish to have for a resident of a destroyed city. Collecting knives would be a more useful occupation.}
{194}{}{What benefit is that to you?}
{195}{}{[Vernon chuckles.] That's rather an overstatement. Besides, it wasn't until later in my life that I began craving for literature. It took me several years to be able to see thoughts and ideas in writings, instead of viewing books purely as entertainment.}
{196}{}{So collecting books wasn't originally your own idea?}
{197}{}{[Vernon chuckles.] There might be some benefits to hoarding knives, but it just gives off that odor of vanity and showing off. In my case, it wasn't like that at all. It wasn't because of enthusiasm that I started collecting books, I assure you. It took me several years to be able to see thoughts and ideas in writings, instead of viewing books purely as entertainment.}
{198}{}{It was a task given by our Mormon community. The Salt Lake City Public Library was destroyed during the nuclear attack. The fires that followed burned down many of the private libraries as well. The Mormons decided it was important to preserve the surviving remains of the pre-war wisdom. Nowadays, the main bulk of the archives is kept within the Mormon Church, and the books you see here are a private collection, for internal use only, so to speak.}
{199}{}{I see.}

#Продажа книжек
{200}{}{Do you have any books or magazines for sale?}
{201}{}{Yes, I may have some, if you're interested.}
{202}{}{Tell me more.}
{203}{}{No, thanks.}

{204}{}{I happen to have a rare book on medicine - namely, on neurosurgery. Even if you don't practice medicine yourself, it will most likely be of interest to any professional doctor. I've never seen a more informational practical guide.}
{205}{}{How much for the book?}
{206}{}{Not interested.}
{207}{}{You know, at this stage of my life I don't value money as much as my own health. I have a heart condition and need a specific medication for it, which is nowhere to be found in the city. And I wasn't able to found it anywhere else myself.}
{208}{}{You say you need a cardiac medication? Alright, if I find some, I'll bring it to you.}
{209}{}{You're in luck. I happen to have a vial of just the thing. Let's barter.}
{210}{}{I have the heart medication you wanted. I'll give it to you in exchange for the book on neurosurgery.}
{211}{}{Thank you for giving me a chance to live longer!}
{212}{}{You're welcome.}

{213}{}{You're going to like it, I'm sure! A fun little comic book from before the war. Get it, you won't regret it!}
{214}{}{What do you want in exchange for it?}
{215}{}{Not money. Money can't buy you health. I hope you've heard about the situation with clean water in the city? The chemist very rarely has water purification tablets for sale. Bring me the tablets and you can have the comic book. It's worth all the effort.}
{216}{}{I just happen to have the tablets. Let's barter.}
{217}{}{Give me some time to think about it.}
{218}{}{I have water purification tablets. I'll give them to you in exchange for the book on neurosurgery.}

{219}{}{Since recently, I've had an automobile in my possession. Can you offer me anything on the topic?}
{220}{}{Oh, really? That's very, very interesting. Working automobiles are a great rarity these days. Well, I have a Chryslus Motors catalog. It's a very thick magazine, with many different articles and useful tips. But I will only sell such a rarity for a special price.}
{221}{}{What's the price?}
{222}{}{Forget it, then.}
{223}{}{The same is ever. Heart medications. You know.}
{224}{}{More pills for your heart? Phew! A second pack will be even harder to find than the first.}
{225}{}{Here are the heart pills. Now about that Chryslus Motors catalog you promised...}

{230}{}{Do you accept rare books and magazines?}
{231}{}{I think I've found what you were looking for - a bundle of pre-war newspapers.}
{232}{}{I have more than enough books, but can't say the same about serials. You see, I'd like to know more details about the last few months before the Great War. If you find something on the topic, I'll happily exchange it for one of my books.}
{233}{}{Hmm... It'll take a bit of work to find something like that.}

{234}{}{Hmm... [Vernon takes a good look at the articles.] Ah! Denver Post, isn't it! Goodness, it's been more than 50 years and they are still readable! Alright, you can pick something from my library in exchange for this, something valuable.}
{235}{}{I need a guide on surviving in the wilderness.}
{236}{}{I'll give you the newspapers in exchange for the book on electronics.}
{237}{}{Give me the manual of first aid - and the newspapers are yours.}
{238}{}{How about some scientific books?}
{239}{}{Do you have anything dealing with traps?}
{240}{}{I'm interested in works about firearms.}
{241}{}{I've been looking for something on energy weapons...}
{242}{}{I want to read these newspapers first. I'll bring them to you when I'm finished.}

{243}{}{Teach you something? Well, I taught writing and mathematics to many residents of the city, but people usually stopped there. These days people are more practical and prefer not to waste their time on something of dubious benefit.}
{244}{}{Public speaking.}
{245}{}{Secrets of gambling.}
{246}{}{No, thanks.}

{247}{}{Perhaps, you'll find the "Scout Handbook" useful? You should definitely give it a read: much helpful information on surviving in the wilderness can be found here.}
{248}{}{"Dean's Electronics". I happen to have the last remaining copy shelved. These days, study books like this sell like hotcakes.}
{249}{}{Yes, I have one last book on theory and practice of first aid, itching to be traded for a decent pack of newspapers.}
{250}{}{Alright, I'll gather the most interesting scientific publications for you.}
{251}{}{"Maddock's Tricks & Traps" is what you need. A *very* rare exemplar, but you're in luck, because I have it.}
{252}{}{Then "Guns and Bullets" would be the thing you're looking for. And I have it.}
{253}{}{No, I'm interested in something else.}
{254}{}{Yes, this will work. Let's trade.}

{255}{}{Thank you, wonderer, it was a pleasure dealing with you.}
{256}{}{Likewise. Goodbye.}
{257}{}{}
{258}{}{}
{259}{}{[Nods sarcastically.] Shame on you!}
{260}{}{I see you're not easy to fool.}

{261}{}{I wonder - was it really so hard to find newspapers in this city?}
{262}{}{It sure was. Firstly, before the war Salt Lake was a huge city with socially-minded citizens, so newspapers were in high demand. Secondly, newspapers degrade quickly, especially in a humid climate like the one here. I've already gone through all the dispensers in the area, barring those in radioactive zones and uninhabited districts. I most likely wasn't the first to do so, because I couldn't find anything of value. Alack and alas.}
{263}{}{I see. Well, goodbye.}

{264}{}{Oh, I see. There aren't many of them left nowadays, are there? And not much in terms of detailed information about it, either. And to think that once there was a whole magazine series about that exact topic called "Super Science". Indeed, I'm parting with the only issue I have here.}

{265}{}{Well, you obviously don't have anything more "valuable" than books here. Okay, let's see what you have.}
{266}{}{Hmm, what about a lesson? Surely you can teach me something.}
{267}{}{My library is the biggest in the city. Tell me what you need and I'll try to find it.}
{268}{}{What are you talking about?}
{269}{}{Anyway, I have other interests.}
{270}{}{A good topic for a lecture. Or even a series of lectures. But, as with books, the more you already know, the less I can teach you. So, what do you say? Shall we start?}
{271}{}{Please start, Professor.}
{272}{}{...And that's about it for today. Do you have any questions?}
{273}{}{That was very insightful. I only have one question: was it really so hard to find newspapers in this city?}
{274}{}{Thanks for the lesson. No questions. I have to go - find ways to use the newly acquired knowledge.}
{275}{}{I'm not exactly sure that I can teach you anything you don't already know.}

#Случайные фразки:
{300}{}{Youth these days...}
{301}{}{No, that's not it, not it...}
{302}{}{No, really, this comedian should've been hanged at once.}
{303}{}{Nothing interesting about this.}
{304}{}{Another dime novel.}
{305}{}{This is nonsense! Oh... It's a book on psychiatry...}
{306}{}{My God, if only I was born in 19th century!}
{307}{}{Civilization has become... Free, yes.}
{308}{}{You can't really be strong until you see a funny side to things.}
{309}{}{You have to laugh at the things that hurt you to keep the world from running you plumb crazy.}
{310}{}{He who marches out of line hears another drum.}
{311}{}{Whoever comes in the door is usually somebody disappointing.}
{312}{}{Every minute spent brooding alone only increases your separation.}
{313}{}{It's the truth, even if it didn't happen.}
{314}{}{It's really too bad that so much crumby stuff is a lot of fun sometimes.}
{315}{}{Nobody who's really using his real ego has any time for any goddamn hobbies.}
{316}{}{It's better for certain things to stay the way they are.}
{317}{}{I wish I knew why people think it's so important to be emotional.}
{318}{}{Do cats eat bats? Do bats eat cats?}
{319}{}{Why is a raven like a writing desk?}
{320}{}{If you don't know where you are going, any road will get you there.}
{321}{}{Everything has sense in it, only you should find it.}
{322}{}{I'm older than you and must know better.}
{323}{}{Begin at the beginning and go on till you come to the end, then stop.}

#Female character:
{1123}{}{Well now! If you knew more about him, young lady, you'd understand that that "humble dwelling" of Diogenes was quite *sufficient* for him and the conditions he lived in: after all, the climate, the scenery, the company...}
{1255}{}{Thank you, wanderer, it was a pleasure dealing with you.}
