{100}{}{You see a skinny boy.}
{101}{}{It's just an ordinary boy.}
{102}{}{My mommy doesn't let me talk to strangers.}
{103}{}{ }

#Ôèíàëüíûå ðåïëèêè
{110}{}{Thank you, at least now I won't worry so much. But I still feel sorry for my dog...}
{111}{}{Thank you, I now know what happened to my dog... My dad's gonna kill the guy! Honestly!}
{112}{}{[Frowning, looking away from you]}
{113}{}{Okay, boy, it's over now.}

#Ïîëó÷åíèå êâåñòà:
{120}{}{[You see a boy walking among the leaves.]}
{121}{}{Hey, what are you doing in this deserted place?}
{122}{}{[Leave him]}
{123}{}{I'm looking for my doggie... Have you seen her? She has a collar and a white tag...}
{124}{}{No, I haven't. Tell me more, maybe I'll see her!}
{125}{}{No, I haven't.}
{126}{}{She is medium-sized, gray, with a white spot on her chest. We always had her on a chain, but she got loose and ran off somewhere. She's wearing a collar with a tag attached that says her name. I miss her so much... Please find her! Please!!}
{127}{}{Alright, alright, I'll do my best. Do you have any idea where she might have run off to??}
{128}{}{Alright, alright, I'll try. No promises though.}
{129}{}{I don't know... I'm afraid they ate her! Those filthy people from the slums! They're always eating dogs! Could it be them? Find her, please! She's been gone for two days already! Please! I'm so scared!}
{130}{}{Nevermind, I'll look for her.}

#Ñëó÷àéíûå ôðàçû ïðè õîæäåíèè ïî ëèñòâå
{131}{}{Where did you go?...}
{132}{}{Hey doggie, come here!}
{133}{}{::Whistles::}
{134}{}{Please, come back!}
{135}{}{Get home, please!}
{136}{}{I miss you so much, please come back!}
{137}{}{::wipes tears::}

#Ñäà÷à êâåñòà:
{150}{}{Did you find her?!!}
{151}{}{I'm sorry, kid, but your dog got mad and attacked me. I had to kill her.}
{152}{}{I'm sorry, but your dog is dead. Someone in the slums has already digested her in his stomach.}
{153}{}{Sorry, no luck so far.}

{154}{}{[The kid's face changes] But... that can't be! [Seems like he's about to cry]}
{155}{}{You see, some of the most unfortunate are forced to survive somehow. Maybe he didn't want to eat your dog, but he had to. I'm sorry, kid, but there's nothing more I can do for you.}
{156}{}{WHAT?! No way!!! My doggie was normal! It could not be! It wasn't her! No!}
{157}{}{Unfortunately, it was her. She must have wandered into the pack, and her wild instincts kicked in. Here's the tag from her collar. That's her tag, right?}
{158}{}{Apparently, you're right. It might be some other dog. I'll continue search.}
{159}{}{Yes... It's... [He sobs and begins to cry silently]}
{160}{}{Come on, pull yourself together! I'm sorry about the dog, but if she ran away, she must have been better off there. Maybe she was tired of being on a chain. Can you imagine how much she would have suffered if she had continued to live on a chain?}
{161}{}{[Leave him]}
{162}{}{Uh... Really?... [wipes tears with hand] Well, I hope she has a better life in heavens then!}
{163}{}{Yes, in the great kennel in heavens! She's all right there. And you should stay firm in front of your problems, not get soft! Understand? Now go, wash your face, and don't cry anymore.}
{164}{}{Thanks...}
{165}{}{Don't mention it! Bye!}
{166}{}{[Looks like your words didn't help much, and the kid keeps crying even more.]}
{167}{}{[Leave him with his pain and loneliness]}

#Female character:
{1124}{}{No, I haven't. Tell me more, maybe I'll see her!}
{1125}{}{No, I haven't.}
{1153}{}{Sorry, no luck so far.}
