{100}{}{You see a skinny boy.}
{101}{}{It's just an ordinary boy.}
{102}{}{My mommy doesn't let me talk to strangers.}
{103}{}{ }

#Финальные реплики
{110}{}{Thank you, at least I now won't be so worried. But still I feel sorry for my dog...}
{111}{}{Thank you, I now know what happened to my dog... My dad will *kill* him! Honestly!}
{112}{}{[Frowning, looking away from you]}
{113}{}{Okay, boy, it's all over.}

#Получение квеста:
{120}{}{(You see a boy walking among the leaves)}
{121}{}{Hey, what are you doing in such a dubious deserted place?}
{122}{}{[Leave him]}
{123}{}{I'm looking for my doggy... Have you seen her? She has a collar and a white tag...}
{124}{}{No, I haven't. Tell me more, maybe I'll see her!}
{125}{}{No, I haven't.}
{126}{}{She's medium-sized, gray, with white spot on her chest. We always kept her chained, but she broke up and ran away somewhere. She wears a collar with attached tag that has her name. I miss her so much... Find her please! Please!!!}
{127}{}{Alright-alright, I'll try. Do you have any ideas where did she run to?}
{128}{}{Alright-alright, I'll try but can't promise anything.}
{129}{}{I don't know... I afraid if she's got eaten! These are those dirty men from the slums! They always eat dogs! Maybe it's them? Look for her! Please! She's gone for two days! Please! I'm so afraid!}
{130}{}{Nevermind, I'll look for her.}

#Случайные фразы при хождении по листве
{131}{}{Where are you...}
{132}{}{Hey doggie, come!}
{133}{}{*Whistles*}
{134}{}{Please come back!}
{135}{}{I want you to return so much!}
{136}{}{I'm missing you so much, please come back!}
{137}{}{*wipes tears*}

#Сдача квеста:
{150}{}{Did you find her?!!}
{151}{}{Sorry kid, but your dog went wild and attacked me. I had to kill her.}
{152}{}{Sorry but your dog is dead. Someone in the slums have already digested her in his stomachs.}
{153}{}{Sorry, didn't find her so far.}

{154}{}{[Kid has changed in his face] But... It cannot be! [it seems like he's about to cry]}
{155}{}{You see, some of the most unfortunate, have to survive somehow. He maybe didn't want to eat your dog, but he had to. Sorry kid, but there's nothing more I can help you with.}
{156}{}{WHAT?! No way!!! My doggy was normal! It could not be her! It wasn't her! No!}
{157}{}{Unfortunately, it was her. Apparently, she sniffed with the pack, and wild instincts leaped into her. Here's dog tag from her collar. Is it her tag?}
{158}{}{Apparently, you're right. It might be other dog. I'll continue the searching.}
{159}{}{[Kid has changed in his face] Yes... It's... Hers... [sobs and begins to cry silently]}
{160}{}{COme on now, pull yourself together! Sorry about the dog, but if she ran away, then she was happy there. Maybe she was tired of sitting on a chain. Imagine, how much she would suffer, if she continued to live chained?}
{161}{}{[Leave him]}
{162}{}{Yes?.. Really?.. [wipes tears with hand] Well, it's better for her to live in heavens then!}
{163}{}{Yes, the great kennel in heavens! She's alright there. And you stay firm before the problems, and not dissolve! Understood? Now go, wash your face and don't cry no more.}
{164}{}{Thanks...}
{165}{}{Hey, nevermind! Bye!}
{166}{}{[It seems that your words didn't help much and the kid keeps crying more]}
{167}{}{[Leave him in pain and loneliness]}

#Female character:
{1124}{}{No, I haven't. Tell me more, maybe I'll see her!}
{1125}{}{No, I haven't.}
{1153}{}{Sorry, didn't find her so far.}