{100}{}{You see a child.}
{101}{}{You see a local child - perhaps the seed of this city's bright future. Or its desolation.}
{102}{}{You did a bad thing offering drugs to a child. Your soul became a bit blacker.}
{103}{}{Hello.}

{110}{}{Hi.}
{111}{}{This purse, sticking out of your pocket, is it yours?}
{112}{}{Bye.}
{113}{}{Yup. What?}
{114}{}{Really? Maybe some trader lost it and you accidentally "found" it?}
{115}{}{So? What's in it to you? If you want, you can buy it. 10 bucks.}
{116}{}{That's fair. Here's 10 bucks, now give me the purse.}
{117}{}{Wow! That's great!}
{118}{}{Where did you find it?}
{119}{}{Yeah. Take care.}
{120}{}{Alright, nevermind.}
{121}{}{One of our guys found it. I don't know who. Then it changed hands. }
{122}{}{Right. Now all ties are lost.}
{123}{}{Keep talking, you little thief.}
{124}{}{You'd better stop lying to adults. It could end badly. Give me the purse before the real owner shows up.}
{125}{}{No way!}
{126}{}{Uh... Okay, take it, just don't tell anyone about me!}
{127}{}{Okay.}
{128}{}{If you argue with me, I'll take you by the throat right to the sheriff, understood? Now, give me that thing!}
{129}{}{But it wasn't me, I swear! Here, take it, just don't tell anyone about me! Please!}
{130}{}{And I'll call the cops right now and tell them you are molesting me!}