{100}{}{You see a storekeeper.}
{101}{}{You see the manager of the factory warehouse.}

{110}{}{H-hey! You are not allowed to go in there! This is a service room. Get out! Move, move!!!}
{111}{}{Alright, I'll leave.}
{112}{}{I'll leave for now, but know that next time I might punch you in the teeth.}

{113}{}{Calm down, I'm here about buying a batch of product.}
{114}{}{We're not a shop!... Wait, so that's what this is about? Sorry, but I haven't see you before. Care to show me your license? There are many people pretending to be couriers lately.}
{115}{}{Here, look.}
{116}{}{Uh, I don't have it with me right now.}

{117}{}{Stop with this nonsense! Get a license or get out! Bloody beggars, I'm so sick of you...}
{118}{}{[Leave]}
{119}{}{That's better! Sorry for being rude, there are always some beggars bothering me. I've been telling those fools at the factory for a long time to just implement an accounting system. But they are always busy... So, how many bottles do you need today?}
{120}{}{How many bottles can I order?}
{121}{}{Ah yes, you're new here. Okay, listen, I'll explain this once. First, I'll roll these boxes up to the entrance and put a lock on them for you. Then everything goes according to the standard procedure, you fill out the application and leave it in the boxes. We don't even have to see or hear each other. You pay for the amount, I replenish your supply. It's up to you how and where to utilize them. Is that clear?}
{122}{}{Perfectly clear.}
{123}{}{And since you're going to ask anyway - we can produce not more than }
{124}{}{ product units per month for your needs. The factory is not yet able to make more.}
{125}{}{Good. No more questions.}
{126}{}{Alright then. Now I'm gonna pull out those damn boxes. Move aside!}
{127}{}{[Leave]}

{130}{}{Huh, isn't it our courier... How sweet. But I'm busy now, don't bother me.}
{131}{}{Okay.}
