{100}{}{You see Simon.}
{101}{}{A keen eye, a strong-willed chin, and a proud posture give this man the look of an informal leader.}
{102}{}{Fucking locker! Close, damn it!}
{103}{}{The fuck are you looking at? Want to be punched in the teeth?}
{104}{}{ }
{105}{}{I'm not in the mood right now...}
{106}{}{How are you? Do these niggas bother you? Good.}

{110}{}{Stranger? What's the matter? I'm trying to take a break from all those idiots in the factory. I really don't want to talk.}
{111}{}{Do you know anything about the lady manager's missing keys?}
{112}{}{Did you know that black man in the dining room wants to kill you?}
{113}{}{Then I'm not going to bother you.}

{114}{}{Fuck me gecko! Yes, I have already turned out all my drawers and my pockets! I have NO fucking keys and never had!}
{115}{}{What? Again? Can I have a break from all these stupid questions?}
{116}{}{[Simon listens to the story with his mouth agape] That son of a bitch! This nigga's too tricky! You know what I gonna do now? Oh, no, I'm not going to punch him in the face! He tried to outsmart me, so now I will outsmart him.}
{117}{}{What do you have in mind?}
{118}{}{Well, let's say, I need a man who would plant the keys in that nigga's pocket, then tell about it to that old woman. I'll pay! Of course, I could do it myself, but in my case it's not safe - it might arouse suspicion. And you're a new man, nobody will suspect a thing. What do you say?}
{119}{}{If you pay - I'm in.}
{120}{}{No, I don't like it.}
{121}{}{That's great. Waiting for the news, partner!}
{122}{}{All right.}
{123}{}{Sure, you can just leave. All good. But think about it - I would pay good money and, perhaps, can even sneak something off the factory for you. What can this old woman and fat nigger offer? I'm not in a hurry. Think about it. Do it when you're ready.}
{124}{}{I have to think about it...}

{125}{}{Your black rival is dead.}
{126}{}{I ratted the negro out, as we agreed. Now he is fired.}
{127}{}{It so damn good when people are brilliantly doing their job! Oh yeah... I always keep my word. 250 bucks, here. Of course, this is not the biggest money in the world, so I can only offer gas protection suit in addition. It can be sold for good money on the market. Believe me, that nigga wouldn't give you more than that.}
{128}{}{That's right! Well, let's split up, as if we never met. Take care.}
{129}{}{Don't come near me until you solve the problem.}

#Æåíñêèå ðåïëèêè
{1110}{}{Stranger? What's the matter? I'm trying to take a break from all those idiots in the factory. I really don't want to talk.}
{1121}{}{That's great. Waiting for the news, partner!}
{1126}{}{I ratted the negro out, as we agreed. Now he is fired.}
