{100}{}{You see Tom.}
{101}{}{The big white eyes on this black man's face seem to shine with light sadness.}
{102}{}{Praise be to you! Don't stray from the right path.}
{103}{}{Oh God... You are still here...}

#Первый диалог
{110}{}{Just as I was about to swallow the first spoonful of soup, the flies flew in. You know, it's quite unpleasant, but you have to deal with it.}
{111}{}{Hello. Beautiful day today, isn't it?}
{112}{}{Fine, go on, eat. I won't bother you.}
{113}{}{Right. I better go get some fresh air outside.}

{114}{}{Who are you?}
{115}{}{I'm Tom, a simple worker.}
{116}{}{Nice to meet you. Maybe we will talk next time.}

{117}{}{Why are they treating you like this, Tom?}
{118}{}{Everybody treats me like that. Blacks and whites. Maybe it's something about my character thet triggers them... But it's not a big deal, they're just fooling around, they don't mean any harm. Although, of course, there are some who will break your face if you won't be careful. Fortunately, there aren't many left around.}
{119}{}{Not many? But there are some, aren't there?}
{120}{}{Too bad, Tom. I have to go now.}
{121}{}{I'd laugh at you, too, but I don't have time. Breathe for now.}

{122}{}{[He warily looks around] Look, I don't want to speak ill of anyone, I'm a peaceful man!}
{123}{}{All right, suit yourself.}
{124}{}{What were you looking at? That white guy over there by the lockers, right?}
{125}{}{Simon... Uh, don't, err... I don't want to talk about him... Neither bad nor good.}
{126}{}{I can help you deal with him, if you want.}
{127}{}{I can help you deal with him if you tell me who stole the keys from the administrator.}
{128}{}{Oh, my God! I'm a peaceful man, leave me alone! Simon's a scumbag, of course, and I'd appreciate it if he were somewhere else, but I won't take the sin of bloodshed on my soul. Besides, I don't have anything to pay anyway.}
{129}{}{Bloodshed? You said "bloodshed"?! Tom, I didn't mean to kill him! Scaring him a little would be enough.}
{130}{}{Frankly, I don't trust you. They don't hear much good about you in Salt Lake City. I'm sorry.}
{131}{}{Puny beggar, I don't even want to talk to you.}
{132}{}{Fine, Tom, I won't insist.}
{133}{}{Damn coward, I don't even want to talk to you.}
{134}{}{[Ponders for a while, looking around] Look, let's go somewhere more private, okay?}
{135}{}{Sure, let's go...}
{136}{}{[Whispers] Please understand. This Simon is an arrogant bastard. He'll slice anyone his size and position will allow. He is a very violent man. God must not allow the likes of him to rise to power!}
{137}{}{Exactly. And that's why I want to help.}
{138}{}{I hear you, but don't think it matters.}
{139}{}{And I have a great plan, a peaceful one. [He sighs] I stole the keys from the administrator and hid them in the restroom. Yes, that was really me.}
{140}{}{Hmm, go on.}
{141}{}{I thought it would cause a panic at the factory, and when the investigation started, I would plant them on Simon. But that turned out to be above my principles. I can' t set a man up, not even an animal like Simon. Besides, in my position it's very risky.}
{142}{}{Well...}
{143}{}{Now I don't know what to do. I thought about confessing and giving the keys back, but then they'd fire me. And I can't lie, as you can see...}
{144}{}{All right, Tom, listen: sit tight, keep quiet, and I'll think of something.}
{145}{}{Ha, now you've confessed it yourself! That's it, wait for my decision and mercy and pray that I wouldn't rat on you.}
{146}{}{May the God bless you!}
{147}{}{Great. Now it's time to say goodbye to each other.}
{148}{}{Yes, I guess I deserve it... Please think about it, think about it very carefully.}
{149}{}{As I decide, so shall it be. Now get away from me.}

{150}{}{About Simon...}
{151}{}{What about him?}
{152}{}{He's dead. And don't ask me how it happened - it doesn't matter.}
{153}{}{Rejoice - he was fired! For... Stealing keys. Who'd have thought, right?}
{154}{}{I wanted to ask something, but I forgot.}
{155}{}{Oh, God, what have you done! It seems that nothing in this world can be resolved peacefully. Now his death is on me! Oh, my God...}
{156}{}{Hey, old man, shut your mouth. I helped you - solved the problem. Have some respect and repay me with something. Things like this aren't worth a simple sandwich!}
{157}{}{Repay you how? I'm a simple worker, I don't make much money. I can only give you my gas suit. You can sell it.}
{158}{}{Fine, give me the suit. It's better than nothing.}
{159}{}{Here. And no more shit alright? I'm upset as it is. Enough is enough!}
{160}{}{Your problem. Bye.}
{161}{}{[Smiles] Wow, you really did it! Thank you for everything. And most of all, for your kindness and understanding. Something that is sorely lacking in this world.}
{162}{}{Yes. It's a shame that saving the world can't be put in your pocket...}
{163}{}{Glad to help.}
{164}{}{Uhh, I have nothing to give you. I'm a simple worker, I don't make much money. I can only give you my gas suit. You can sell it.}
{165}{}{Here. I hope this helps you in some way. Take care.}
{166}{}{Bye. And don't let anyone else bully you.}

{167}{}{Tom, somebody stole the keys from the administrator, and I'm going to find the thief. Whoever did this won't get away. You don't want to be suspected, do you?}
{168}{}{About Simon - I'll help you get rid of him if you tell me who stole the keys.}
{169}{}{Cold sweat, wide pupils, rapid heartbeat... My detective experience tells me you're hiding something.}
{170}{}{You're a bad liar, Tom. I see you know more than you're telling.}
{171}{}{[He looks shocked] A private detective? Is that even a thing these days? Wow...}
{172}{}{It's just a hobby, not a job...}
{173}{}{I have the keys. Remind me again what you wanted to do with them?}
{174}{}{*sniff* I can smell a thief a mile away! [take a deep breath] YES, THAT'S YOU!}
{175}{}{Umm... You're not serious, aren't you?.. Heh... I mean, how can you detect the thief by smell...}
{176}{}{[Stare at him seriously]}

#Плавающие издевки от товарищей в столовой
{180}{}{Hey, old man, want some... *milk*? Ha-ha!}
{181}{}{Tom is staring again. Look away, dumbass!}
{182}{}{Don't want me to call you words? Sorry, I can't!}
{183}{}{Tom, wanna hear a joke about Africa?}
{184}{}{Hey, Tom, you can't get a black eye, can you?}
{185}{}{How come there are so many black people here? Tom, did you get everyone?}

#Female character
{1116}{}{Nice to meet you. Maybe we will talk next time.}
{1121}{}{I'd laugh at you, too, but I don't have time. Breathe for now.}
{1156}{}{Hey, old man, shut your mouth. I helped you - solved the problem. Have some respect and repay me with something. Things like this aren't worth a simple sandwich!}
{1161}{}{[Smiles] Wow, you really did it! Thank you for everything. And most of all, for your kindness and understanding. Something that is sorely lacking in this world.}
{1163}{}{Glad to help.}
