{100}{}{You see Arrogant Larry.}
{101}{}{You see the main chief of the lousy dining.}
{102}{}{*Script execution error*}

#Первый разговор
{110}{}{[The cook, without paying any attention to you, continues to knead the dough and whistling some stupid song]}
{111}{}{Give me a menu, dear man.}
{112}{}{[Leave]}

{113}{}{[The cook stops and lifts the eyelids a bit] Look above.}
{114}{}{Eh... There's nothing here.}
{115}{}{Pffft-ha-ha-ha!!! Of course, because this dining room is only for factory workers. And the simple crooks are not served here. If you want to eat - go to Jolly Joe.}
{116}{}{But I am a factory worker.}
{117}{}{Oh, got it. Then I won't stay here any longer.}

{118}{}{Is that so? Well then, welcome to the most lousy diner around the city. So, what's the order - worms, mold or boots with mayonnaise?}
{119}{}{I choose worms. M-m, yum!}
{120}{}{Perhaps I'll take the mold.}
{121}{}{Hmm, let's try these boots.}
{122}{}{Are you fooling me?! Where's the normal grub?}
{123}{}{I'm not hungry. Eat your worms or whatever you got there. I'm leaving.}

{124}{}{Yeah, just about time.}
{125}{}{[Leave]}
{126}{}{Boo-hoo-hoo! High five! Seeing fresh meat at the factory is such a joy! And now seriously. You want grub, I have it right here. But you'll have to bring your tokens.}
{127}{}{My what?}
{128}{}{Tokens. They are issued by the head of the department for two weeks in advance. One token means one meal. Your manager *had* to tell you this! Bloody bastards, they didn't bother again...}
{129}{}{Ah, so that's what they need for... I have them right here.}
{130}{}{Right. I'll go and, uh, deal with my manager.}
{131}{}{Hey, don't be so hasty! It's just that you manager should've explained it to you. Tokens are issued by the head of the department for two weeks in advance. One token means one meal. You want grub, I have it right here. Just bring your tokens.}
{132}{}{So, did you get your manager's ass kicked? Or you'll keep snotting while looking at the last bowl of soup?}
{133}{}{Yes, here's tokens. It's alright.}
{134}{}{Nope, not yet.}
{135}{}{Oh, to see a customer for a second time in this hole is a rarity. Haha, just kidding!}
{136}{}{Stop with the jokes. Where's menu?}
{137}{}{Then you just got lucky, because I'm leaving.}
{138}{}{Well, what's this time?}
{139}{}{Standard dinner. Here's tokens.}

#Выдача обеда
{140}{}{Good. Then you know everything you need, which means you won't rip my brain apart with stupid questions. Well, how many boogers do you want today?}
{141}{}{Don't need anything, I've changed my mind.}
{142}{}{Will do it. How many rations?}

{143}{}{One ration. Here's token.}
{144}{}{Two rations.}
{145}{}{Three rations.}
{146}{}{Four rations.}
{147}{}{Five rations.}
{148}{}{I want to exchange all my tokens.}
{149}{}{}

{150}{}{Wow, such a strong appetite!}
{151}{}{It's none of your business. Pile on more, and I'll see what to do with all this.}
{152}{}{Perhaps, I'll think a little more before I choose.}
{153}{}{Here. One ration contains fruit, sandwich and bottle of Nuka-Cola. Bon appetit, and... Give some space to the others, don't occupy the window!}
{154}{}{Thanks.}
{155}{}{I would say "thank you", but not for service like this.}
{156}{}{You deceived the simple-minded cook and, in fact, robbed the factory. What a shame!}

#Застал за передвижением по кухне
{160}{}{Hey, it's not a checkpoint in here! Throw yourself out of kitchen and fast!}
{161}{}{Don't hustle...}

#Female character
{1122}{}{Are you fooling me?! Where's the normal grub?}
{1132}{}{So, did you get your manager's ass kicked? Or you'll keep snotting while looking at the last bowl of soup?}
{1141}{}{Don't need anything, I've changed my mind.}
{1151}{}{It's none of your business. Pile on more, and I'll see what to do with all this.}
{1155}{}{I would say "thank you", but not for service like this.}
