{100}{}{You see a worker.}
{101}{}{This is just another ordinary laborer in the factory.}
{102}{}{I'm busy, let's talk after work}
{103}{}{I'm not used to talking with my mouth full}

{112}{}{Hey, buddy! Outsiders are not allowed near the tanks, it's a closed area of the factory. So turn around!}
{113}{}{Outsiders are not allowed near the tanks, it's a closed area of the factory. So turn around!}
{114}{}{Ugh...}

###################################################
#
#     èãÄÇÄûôàÖ îêÄáõ
#     Ä‚ÚÓ: ÄÎÂÍÒ‡Ì‰ Ä„‡ÙÓÌˆÂ‚
#
###################################################

#All's good
{250}{}{At this rate, I will make enough money to open my own factory!}
{251}{}{Now I'm gonna have a lot of booze!}
{252}{}{Today I'll get the best chick in the city!}
{253}{}{And they were telling me that honest work will get you nowhere! Bah!}
{254}{}{With these conditions, I will work for days!}
{255}{}{Let's praise our Lord, brothers!}
{256}{}{Everybody to the "Tin angel" today! I'm buying!}
{257}{}{Finally, my old woman will cease to nag me...}
{258}{}{Yes! Yes! Who said we are losers? Ha-ha!}
{259}{}{::happily hums something about a priest and 10 whores::}
{260}{}{It was worth to pick through all the cogs and screws of that fucking machines!}
{261}{}{I'm ready to buy the one that helped us the best booze in Salt Lake for a week!}
{262}{}{Can't believe someone actually helped us! Let's make a monument of empty bottles to honor him!}
{263}{}{My lucky cap of Nuka-Cola has finally helped me!}
{264}{}{I am now a successful man! Call me "sir"!}
{265}{}{Nuka-Cola! The taste of victory!}
{266}{}{Nuka-Cola! Obey your thirst!}
{267}{}{Nuka-Cola! Now 5 rad/h less!}
{268}{}{Life is good!}
{269}{}{No more brahmin shit for dinner!}

#all's ok
{300}{}{Here comes another day, but the shit remains the same...}
{301}{}{Another pitiful day...}
{302}{}{Machine number 3 isn't working again...}
{303}{}{Ow, the hangover...}
{304}{}{Who pissed into the concentrate again?!}
{305}{}{How are the things? Same, same...}
{306}{}{To work? Why?}
{307}{}{Working overtime again...}
{308}{}{I'd better be herding brahmin...}
{309}{}{Just hold out until the evening...}
{310}{}{Who took my beer?!!}
{311}{}{I'm sick of staring at this Nuka-Cola!}
{312}{}{Who worked today on the third machine? It's messed up again!}
{313}{}{Where can I lie down for an hour?}
{314}{}{::looks back grimly, kicking some part from the machine::}
{315}{}{If only I would be put in charge! I would have brought order!}
{316}{}{Instead of this shit they would be better making beer!}
{317}{}{They should make moonshine - we would be bathed in gold...}
{318}{}{If only someone could help us...}
{319}{}{Didn't work and will not work!}

#all's bad
{350}{}{Oh, crap... No, not like the usual shit - much worse...}
{351}{}{Time to change my job...}
{352}{}{I have a raider brother... Maybe I should go join him?}
{353}{}{What shitty prank could I pull on the manager before quitting?}
{354}{}{I'd rather be in slavery, than working here!}
{355}{}{Work in two shifts, no weekends, and here is the result...}
{356}{}{Don't even have any poison to kill myself... But wait, there is Nuka-Cola! Beats arsenic any day!}
{357}{}{Nuka-Cola! The taste of victory? Is it? Hmm...}
{358}{}{Will drown the foreman in the concentrate tank - and to Vegas!}
{359}{}{The payment is bigger even for cleaning brahmin shit!}
{360}{}{Gonna have to sell my kidney...}
{361}{}{Will wait for the Ghost Train and just throw myself under its wheels...}
{362}{}{I told them - they should put more money into advertisement!}
{363}{}{I quit... I heard Vegas needs sewage workers...}
{364}{}{Shoot myself first, or kill my wife with the kids?}
{365}{}{What should I eat? Brahmin gum dish with the rat shit on the side?}
{366}{}{Let's dismantle the machines! Maybe the scrap is worth something...}
{367}{}{Today, everyone to the "Tin angel"! We'll celebrate my funeral!}
{368}{}{Honest hard worker in our time will achieve nothing...}
{369}{}{Maybe I would do better at the Hoover dam?}
