{100}{}{You see a waitress.}
{101}{}{You see a very occupied woman with a rather rude expression. What a hag.}

#Первая фразка:
{102}{}{What?}
{103}{}{What do you want?}
{104}{}{Well, just say it.}
{105}{}{Another face! Well, what do you want?!}
{106}{}{What to bring you?}
{107}{}{What? How 'bout a beer? You'll get less diarrhea from it.}
{108}{}{Oh! A new client! What do you want?}
{109}{}{If you break the dishes, I will fine you. Now, what do you want?}

#Реплики для блужданий между с'оликами:
{110}{}{If you are going to puke, do it outside.}
{111}{}{Hey! No fighting!}
{112}{}{Eat, sweetie.}
{113}{}{That'll be 50 bucks.}
{114}{}{Come on, sleepyhead.}
{115}{}{Well, for how long do I have to wait?}
{116}{}{You want more? Are you serious?}
{117}{}{Iguana? Maybe you'd like a roasted dick on a silver platter?}
{118}{}{What is it, you ask? It's a pie... With meat.}
{119}{}{Who do we have here so hungry?}
{120}{}{You're hungry aren't you! Well? Well??}
{121}{}{A towel? Come on! Look at this one here, people.}
{122}{}{Wipe the table? Couldn't do it yourself?}
{123}{}{Well, what a pig.}
{124}{}{If you break something, I will be pissed.}
{125}{}{Sure, mommy will clean after everybody...}
{126}{}{::grumbles::}
{127}{}{Here, chug.}
{128}{}{Five bucks. Come on, come on!}
{129}{}{Move it, you're not the only one here.}

#Диалог
{150}{}{Let me see the menu.}
{151}{}{I'm leaving.}
{152}{}{Why so rude?}
{153}{}{What else?}
{154}{}{[Menu]}
{155}{}{Never mind.}
{156}{}{[Makes amazed face] You've got some nerve, don't you! So, an old woman is trying hard here, wipes up after all of you, and he is still unhappy! Where did you come from, fancy-pants? Surely, from Vegas, right? You came here to eat - so eat! I'm not your mother to groom you. What's your order?}

#Извинения
{157}{}{Damn, I'm out of your fucking place! At first I was insulted by an old hag, and now by a bald jerk!}
{158}{}{I'm sorry I got rude. I won't do this again. Sorry.}
{159}{}{Well, my friend, calmed down?}
{160}{}{Why don't you get out of here, buddy.}
{161}{}{[Smiles all over her face and waves her hand] Oh! Come on! Worse things have happened here! You won't believe what the old woman have seen in her life! Do not worry! Everything's good!}
{162}{}{Phew, relieved from the heart...}
{163}{}{Oh, you pathetic idiot! [almost crying, threatens with her fists] If I was younger, I would have shown you! Hey, boys, throw him out!}
{164}{}{Oh, you hag!!!}

#Если Джо мер'в
{200}{}{The place is closed, don't you see? We have... A tragedy here.}

#Female character:
{1156}{}{[Makes amazed face] You've got some nerve, don't you! So, an old woman is trying hard here, wipes up after all of you, and he is still unhappy! Where did you come from, fancy-pants? Surely, from Vegas, right? You came here to eat - so eat! I'm not your mother to groom you. What's your order?}
{1158}{}{I'm sorry I got rude. I won't do this again. Sorry.}
{1159}{}{Well, my friend calmed down?}
{1160}{}{Why don't you get out of here, you brat!}
{1163}{}{Oh, you pathetic idiot! [almost crying, threatens with her fists] If I was younger, I would have shown you! Hey, boys, throw her out!}
