{100}{}{You see Arrogant Larry.}
{101}{}{You see the head chef of this lousy canteen.}
{102}{}{*Script execution error*}

#Ïåðâûé ðàçãîâîð
{110}{}{[Without paying any attention to you, the cook continues to knead dough and whistle some silly song.]}
{111}{}{Give me a menu, dear man.}
{112}{}{[Leave]}

{113}{}{[The cook stops and looks up at you] Look above.}
{114}{}{Eh... There's nothing there.}
{115}{}{Pffft-ha-ha-ha!!! Of course, there's nothing there, because this canteen is only for factory workers. They don't serve ordinary crooks here. If you want to eat, go to Jolly Joe's.}
{116}{}{But I am a factory worker.}
{117}{}{Oh, got it. Then I won't stay here any longer.}

{118}{}{Is that so? Well then, welcome to the most lousy diner around the city. So, what's the order - worms, mold or boots with mayonnaise?}
{119}{}{I choose worms. M-m, yummy!}
{120}{}{Maybe I'll take the mold.}
{121}{}{Hmm, let's try these boots.}
{122}{}{Are you fooling me?! Where's the normal grub?}
{123}{}{I'm not hungry. Eat your worms or whatever you got there. I'm leaving.}

{124}{}{Yeah, just about time.}
{125}{}{[Leave]}
{126}{}{Baa-hah! High five! Seeing fresh meat at the factory is such a joy! Now seriously. If you want food, I have it right here. But you'll have to bring your tokens.}
{127}{}{My what?}
{128}{}{Tokens. They are issued by the head of the department for two weeks in advance. One token means one meal. Your manager *had* to tell you this! Bloody bastards, they don't even bother anymore...}
{129}{}{Ah, so that's what they need for... I have them right here.}
{130}{}{Right. I'll go and, uh, deal with my manager.}
{131}{}{Hey, don't be so hasty! It's just that your manager should've explained it to you. Tokens are issued by the head of the department for two weeks in advance. One token means one meal. You want grub, I have it right here. Just bring your tokens.}
{132}{}{So, did you kick your manager's ass? Or are you going to keep drooling over last bowl of soup here?}
{133}{}{Yes, here are the tokens. It's alright.}
{134}{}{Nope, not yet.}
{135}{}{Oh, to see a client a second time in this hole is very rare. Haha, just kidding!}
{136}{}{Enough with the jokes. Where's menu?}
{137}{}{Then you just got lucky, because I'm leaving.}
{138}{}{Well, what's this time?}
{139}{}{A usual dinner. Here are the tokens.}

#Âûäà÷à îáåäà
{140}{}{Good. Then you know everything you need, which means you won't rip my brain apart with stupid questions. So, how many boogers do you want today?}
{141}{}{Don't need anything, I've changed my mind.}
{142}{}{Will do it. How many rations?}

{143}{}{One ration. Here's token.}
{144}{}{Two rations.}
{145}{}{Three rations.}
{146}{}{Four rations.}
{147}{}{Five rations.}
{148}{}{I want to exchange all my tokens.}
{149}{}{}

{150}{}{Wow, what an appetite!}
{151}{}{Shut up. Pile on some more, and see what I can do with it.}
{152}{}{Perhaps, I'll think a little more before I choose.}
{153}{}{Here. One ration contains fruit, sandwich and bottle of Nuka-Cola. Bon appetit, and... Give some space to the others, don't hog the window!}
{154}{}{Thanks.}
{155}{}{I would say "thank you", but not for this kind of service.}
{156}{}{You deceived the simple-minded cook and, in fact, robbed the factory. What a shame!}

#Çàñòàë çà ïåðåäâèæåíèåì ïî êóõíå
{160}{}{Hey, it's not a checkpoint in here! Throw yourself out of my kitchen, chop-chop!}
{161}{}{What a hustle...}

#Female character
{1122}{}{Are you fooling me?! Where's the normal grub?}
{1132}{}{So, did you kick your manager's ass? Or are you going to keep drooling over last bowl of soup here?}
{1141}{}{Don't need anything, I've changed my mind.}
{1151}{}{Shut up. Pile on some more, and see what I can do with it.}
{1155}{}{I would say "thank yo", but not for this kind of service.}
