{100}{}{You see an administrator.}
{101}{}{You see an elderly woman with disheveled hair sticking out in all directions. We can only say that her appeal was left far in the past.}
{102}{}{Help! Crazies are here!!!}
{103}{}{Thanks for the help}

#Äèàëîã äî ïîëó÷åíèÿ êâåñòà
{110}{}{Yes, what?}
{111}{}{Can I go inside?}
{112}{}{Nothing.}

{113}{}{No. The entrance to the plant is for personnel only.}
{114}{}{I am just one of them!}
{115}{}{Uh... Ma'am, you look tired. Did something happen?}
{116}{}{Nevermind then.}

{117}{}{That so? I think I would know about it.}
{118}{}{Oh, well, at least someone noticed! There are so many men at this factory, and not one can help an old woman... And recently I've been even robbed, you know? They took my bunch of keys right from under my nose!}
{119}{}{How did this happened?}
{120}{}{This is stupid. Keys are not money, why would someone steal them?}
{121}{}{You suspect anyone?}
{122}{}{Sorry. And now I have to go. Goodbye.}

{123}{}{I want to ask about those keys that have been stolen.}
{124}{}{I don't know what those thieves wanted, but it will do them hardly any good.}
{125}{}{I see. Well, I gotta go.}
{126}{}{If you want, I can look for the thief.}
{127}{}{I had a whole crowd of workers here the day my bundle of keys went missing. Usual gathering, accounting and administrative workers. Anyone could have done it.}
{128}{}{I don't know. It's generally difficult to steal something at this plant, crowds of people everywhere, it's easy to get caught. And those keys are nothing important. Whatever the thief expected, he won't get it.}
{129}{}{There was a whole crowd. It's probably someone new, others would have realized that my keys won't get them anything valuable.}
{130}{}{How can you be sure that you simply have not lost them?}
{131}{}{I am an old woman, but my memory is still good!}
{132}{}{I'd be very grateful to you. Ask around, preferably during lunch when the workers are in the dining hall. But don't expect anybody to confess!}
{133}{}{I'll still try to get to the bottom of this. I won't tolerate scum that steal from women!}

#Çàâåðøåíèå êâåñòà
{150}{}{Your keys were found.}
{151}{}{Really?! That's great! Where are they?}
{152}{}{I have the keys. I accidentally found them in the toilet - someone decided to hide them there.}
{153}{}{I was able to return the keys. It turned out, the black guy Tom stole them.}
{154}{}{That black guy Tom has them. It's time to take him down!}
{155}{}{That nosy Simon has them. It's time to take him down!}
{156}{}{Simon left the keys in his locker in the diner. Hurry while they are still there.}

{157}{}{Oh, you're very observant! Sorry, now we'll never know who did it. But I have the keys, so it's not important.}
{158}{}{Yeah...}
{159}{}{Oh that scoundrel! I knew it I should be careful with him! In appearance, it would seem that he's such a simple-minded, but you know, I never trusted the blacks, to me they even look scary! With their white pupils! Oh, the horror...}
{160}{}{That's right. And he also turned out to be a thief...}
{161}{}{Don't jump to conclusions. He stole the keys to punish his old enemy - this white bastard Simon.}
{162}{}{Hmm... It's was about time to throw that bastard out from the factory! And you know what, maybe this black guy isn't as stupid as it seems... I don't think I'm going to tell anything, let them slit each other's throats. In any case, on this matter, I know this only from your words, so I'll have to leave it as it is. Because I have the keys now anyway.}
{163}{}{Great.}
{164}{}{This nosy bastard, I never liked him. I'm happy to cut him loose from the factory! And let him try to come back...}
{165}{}{He deserves it!}
{166}{}{That's your concern.}

{167}{}{Oh, thank you very much! Saved the old lady from the problems. Well how can you not be thankful? Here, take $100 and cherry Nuka-Cola it's our new flavor, not even for sale yet.}
{168}{}{Is that all? Okay, at least something...}
{169}{}{Thanks anyway!}
{170}{}{I think you will need the money more than me. But I'll take that Cola won't hurt to refresh myself.}
{171}{}{I never thought that in our time we still have good Samaritans! Thank you very much.}
{172}{}{You're welcome. And don't let them treat you this way again.}
{173}{}{You're welcome.}

#Female character
{1152}{}{I have the keys. I accidentally found them in the toilet - someone decided to hide them there.}
