{100}{}{You see a storekeeper.}
{101}{}{You see the manager of the factory warehouse.}

{110}{}{H-hey! You are not allowed to go in there! This is a service room. Get out! Move, move!!!}
{111}{}{Alright, I'll leave.}
{112}{}{I will leave this time, but know that I might punch you in teeth next time.}

{113}{}{Calm down, I'm here about buying a batch of product.}
{114}{}{We are not a shop!... Wait, so that's what it's about. Sorry, but I haven't see you before. Can you show me your license? There are many people who pretend to be couriers lately.}
{115}{}{Here, look.}
{116}{}{Uh, I don't have it with me right now.}

{117}{}{So free my ears from your drivel! Get a license or get out! Bloody beggars, I'm so sick of you...}
{118}{}{[Leave]}
{119}{}{That's better! Sorry for being rude, there are always some beggars bothering me. I've been telling those fools at the factory for a long time to just make an accounting system. But they are always busy... So, how many bottles do you need for today?}
{120}{}{How many bottles can I order?}
{121}{}{Ah yes, you're new here. Okay, listen, I'll explain this once. First, I roll these boxes to the entrance and put a lock on it for you. Then everything goes according to the standard application process, we won't even have to see and hear each other. You pay the wholesale price, I replenish the stock. It's up to you how and where to utilize them. Is that clear?}
{122}{}{Perfectly clear.}
{123}{}{And since you're going to ask anyway - we can produce not more than }
{124}{}{ product units per month specifically for your needs. The factory can't make more than that yet.}
{125}{}{Good. No more questions.}
{126}{}{Alright then. And now I'll pull out those damn boxes. Move aside!}
{127}{}{[Leave]}

{130}{}{A-ah, isn't it our courier... How sweet. But I'm busy now, don't bother me.}
{131}{}{Okay.}
