{100}{}{You see a waitress.}
{101}{}{You see a very occupied woman with a rather rude expression. What a hag.}

#Ïåðâàÿ ôðàçêà:
{102}{}{What?}
{103}{}{What do you want?}
{104}{}{Just say it.}
{105}{}{Another face! What do you want?}
{106}{}{What would you like me to bring you?}
{107}{}{What? How 'bout a beer? You'll get less diarrhea from it.}
{108}{}{Oh! A new client! What do you want?}
{109}{}{If you break the dishes, I will fine you. Now, what do you want?}

#Ðåïëèêè äëÿ áëóæäàíèé ìåæäó ñ'îëèêàìè:
{110}{}{If you are going to puke, do it outside.}
{111}{}{Hey! No fighting!}
{112}{}{Eat, sweetie.}
{113}{}{That'll be 50 bucks.}
{114}{}{Come on, sleepyhead.}
{115}{}{How long do I have to wait?}
{116}{}{You want another one? Are you serious?}
{117}{}{Iguana? Maybe you'd also like a roasted dick on a silver platter?}
{118}{}{What is it, you ask? It's a pie... With meat.}
{119}{}{Who do we have here so hungry?}
{120}{}{You're hungry aren't you! Well? Well??}
{121}{}{A towel? Come on! Look at this one here, people.}
{122}{}{Wipe the table? Couldn't do it yourself?}
{123}{}{What a pig.}
{124}{}{If you break something, I will be pissed.}
{125}{}{Sure, mommy will clean after everybody...}
{126}{}{::grumbles::}
{127}{}{Here, chug.}
{128}{}{Five bucks. Come on, come on!}
{129}{}{Move it, you're not the only one here.}

#Äèàëîã
{150}{}{Let me see the menu.}
{151}{}{I'm leaving.}
{152}{}{Why so rude?}
{153}{}{What else?}
{154}{}{[Menu]}
{155}{}{Never mind.}
{156}{}{[Makes an amazed face] You've got some nerve, don't you! So the old woman tries hard, wipes up everybody's messes here, and he's still not happy! Where did you come from, fancy pants? I bet you're from Vegas, aren't you? You came here to eat, so eat! I'm not your mother to groom you. What's your order?}

#Èçâèíåíèÿ
{157}{}{Damn, I'm out of your fucking place! At first I was insulted by an old hag, then by a bald jerk!}
{158}{}{I'm sorry I was rude. It won't happen again. Sorry.}
{159}{}{Well, my friend, have you calmed down?}
{160}{}{Why don't you get out of here, buddy.}
{161}{}{[Smiles all over her face and waves her hand] Îh! Come on! Worse things have happened here! You wouldn't believe what the old lady has seen in her life! Don't you worry! It's okay!}
{162}{}{Phew, that's a relief...}
{163}{}{Oh, you pathetic idiot! [Almost crying, she threatens with her fists] If I was younger, I would have shown you! Hey, boys, throw him out!}
{164}{}{Oh, you hag!!!}

#Åñëè Äæî ìåð'â
{200}{}{The place is closed, don't you see? We have... A tragedy here.}

#Female character:
{1156}{}{[Makes an amazed face] You've got some nerve, don't you! So the old woman tries hard, wipes up everybody's messes here, and he's still not happy! Where did you come from, fancy pants? I bet you're from Vegas, aren't you? You came here to eat, so eat! I'm not your mother to groom you. What's your order?}
{1158}{}{I'm sorry I was rude. It won't happen again. Sorry.}
{1159}{}{Well, my friend, have you calmed down?}
{1160}{}{Why don't you get out of here, you brat!}
{1163}{}{Oh, you pathetic idiot! [Almost crying, she threatens with her fists] If I was younger, I would have shown you! Hey, boys, throw her out!}
