{100}{}{You see Harry the clerk.}
{101}{}{You see a fussy, ever-smiling clerk.}

#Âîïðîñû
{110}{}{Yes-yes? How can I help?}
{111}{}{See you.}
{112}{}{Can I find a job here?}
{113}{}{I don't know that. Talk to our director, he usually checks every worker himself. Mr. Skinner is in his office, right behind me.}
{114}{}{Thanks, I'll go to him.}
{115}{}{I have a part that will allow to launch artesian tower. Who should I speak to about the price?}
{116}{}{Oh, yes! Sure, the factory's in need of repairing this tower! Speak to our director immediately. He's in his office, right behind me.}
{117}{}{Oh, it's you! We have heard about your courier achievements. We are very glad that you are working with us.}

#Ïëàâàþùèå íîòàöèè:
{150}{}{Ladies and gentlemen! This is how we should work!}
{151}{}{No slacking.}
{152}{}{A clerk is the basis of any enterprise.}
{153}{}{A clerk is like a God... Yes, exactly.}
{154}{}{I can save the factory or bring it down. Do you understand how important I am?}
{155}{}{The most important thing is to gain the trust of the client.}
{156}{}{What is the most important thing for a client? That's right, to be kissed on the butt.}
{157}{}{We'll have many customers if you work hard.}
{158}{}{Don't even think about slacking!}
{159}{}{So? Where are our dear clients?!}
{160}{}{There are no customers here because you are lazy!}
{161}{}{If you weren't so lazy and worked like me...}
{162}{}{There is no such thing as a career development! A person is either promoted, or not.}
{163}{}{Don't confuse marketing and management! They're not the same.}
{164}{}{We need a decent designer.}
{165}{}{I knew a designer once...}
{166}{}{Our enterprise is either good, or... No, there's no "or".}
{167}{}{Well? Are you done with being lazy?}
{168}{}{Wake up! Customers!}
{169}{}{Oh, look - a customer!}
{170}{}{Watch how I make this sale!}
{171}{}{Five percents! FIVE PERCENTS!!!}
{172}{}{A man-clerk should be moderately unmarried.}
{173}{}{All thumbs - that's about you!}
{174}{}{When's the lunch?}
{175}{}{I'm starving here... Oooh...}
{176}{}{Is anyone going to take a bite? I want some jerky...}
{177}{}{The most important thing in management is to work with people.}
{178}{}{The clerk is the coolest job ever! Don't believe me? Too bad!}
{179}{}{Did you write everything down? I'll check!}

#Òîðãîâåö äîâîåííîé êîëîé íà ñòîÿíêå
{180}{}{Why don't you want to hire that caravan merchant with the pre-war cola?}
{181}{}{Oh, I remember him, yes-yes. It's our rival with some very shady business, right? We don't need people of such... Uh, origin. You know, peasants with tanned skin and working hands aren't going to win people's affection.}
{182}{}{I think you're wrong. You should not fend off such a good worker.}
{183}{}{Could I change your mind? Unlikely... Fine, see you around.}
{184}{}{Oh, really? And what could make me change my mind?}
{185}{}{My recommendation as an experienced courier.}
{186}{}{My recommendation as an experienced trader.}
{187}{}{This... Okay. So, what's so good about him?}
{188}{}{You focus on his appearance instead of his skills and experience. This is, of course, important in an urban environment, but it's different with the villagers. He will be accepted as one of their own, which will make it easier for him to negotiate.}
{189}{}{Hmm. I never thought of it that way. Now I understand why our couriers mostly fail in the settlements. Perhaps we should reconsider our approach. Please, tell this merchant that we would like to conclude an agreement with him - provided that he gives us his remaining Nuka-Cola stock.}
{190}{}{You made the right choice, Harry.}

#Ïðî ëèöåíçèþ
{200}{}{How about a joint business?}
{201}{}{You want to sell cola in other cities, right?}
{202}{}{Maybe!}
{203}{}{If so, then I am at your service! Welcome to the office of the real *operating* Nuka-Cola factory! The only one in this region - and possibly in the world. You can make a deal with us at any time to supply the beverage to any locality and for any institution. But I should warn you right away - we only sell the product, you have to deal with the deliveries yourself.}
{204}{}{In other words, you'll just give the license to trade the soft drink?}
{205}{}{We make the drink and sell it in large wholesale batches. Of course, you can just buy a lot of cola every time and supply it to your companions. But for those who buy a license, we provide a discount and a reserve option.}
{206}{}{Reserve?}
{207}{}{Yes. When we learn the volume of your order, we just store it and wait for your caravan. Otherwise, we distribute the order to incoming customers. And then your caravan is at least doomed to wait several days until we produce the required quantity again.}
{208}{}{So, by purchasing a license, I get a guarantee that my goods will stay in place, right?}
{209}{}{Correct! But I have to point out one more thing. Currently, there are rumors circulating in the wastelands about... Low-quality goods. This undermines the reputation of the factory. If you have proof that you work with us directly, your customers will have more incentive to make a deal with you, and your credibility will be much higher.}
{210}{}{Does that mean I can make transactions without a license?}
{211}{}{Maybe, if you look trustworthy enough. But believe me, most traders already learned their lesson and tend to work only with licensed distributors... With our license.}
{212}{}{How much do you want for this license?}
{213}{}{We will sell it you for }
{214}{}{ bucks. A very good price, considering your future profits.}
{215}{}{Sounds tempting. What do I do with it?}
{216}{}{It's for you to decide. You can buy a large shipment of cola. Finding a client and delivering it - that's on you. We recommend talking to the caravan merchants. Of course, they will take a percentage for their services, but they can transport a large amount of bottles very fast very far.}
{217}{}{How many couriers are there right now? Will I be able to actually make money in this business?}
{218}{}{I think so! You see, for a while, the factory worked mainly on the inner city market. The wastelands are poorly acquainted with our products. They're still consuming the pre-war reserves.}

{219}{}{I want to purchase a license! How much do you want for it?}
{220}{}{Thank you for explaining, I will think about it. Take care.}
{221}{}{ bucks. That's the director's price, his orders are not to haggle for it.}
{222}{}{I'm buying!}
{223}{}{Oh, I can't afford that. See you.}
{224}{}{Don't drop your money! It's the most horrific thing I ever seen!}
{225}{}{Oops, sorry.}
{226}{}{[You sign a pile of papers and shake hands] Good luck with your business, courier! We wish you and your humble cause prosperity and success!}
{227}{}{Back at you!}
{228}{}{You became an official representative of the Nuka-Cola factory. Congratulations on your prestigious position!}
