{100}{}{You see an administrator.}
{101}{}{You see an elderly woman with disheveled hair, sticking out in all directions. you can only assume that in the distant past she was quite attractive.}
{102}{}{Help! Crazy people here!}
{103}{}{Thanks for the help.}

#Диалог до получения квеста
{110}{}{Yes? What?}
{111}{}{Can I go inside?}
{112}{}{Nothing.}

{113}{}{No. The factory is for personnel only.}
{114}{}{But I am one of them!}
{115}{}{Ma'am, you look tired. Is something wrong?}
{116}{}{Nevermind then.}

{117}{}{Are you? I think I would know about it.}
{118}{}{Oh, finally someone has noticed! So many men in this factory, and not one of them cares about an old woman... And recently I was even robbed, can you imagine? Someone stole my keychain right out from under my nose...}
{119}{}{How did this happen?}
{120}{}{This is silly. Keys are not money, why would anyone steal them?}
{121}{}{Are you suspecting someone?}
{122}{}{I'm sorry. I have to go. Goodbye.}

{123}{}{I want to ask about the stolen keys.}
{124}{}{I don't know what these thieves wanted, but it's not likely to do them any good.}
{125}{}{I see. Well, I gotta go.}
{126}{}{I can look for the thief if you want.}
{127}{}{I had a whole bunch of employees here. The usual meetings, bookkeeping, and other administrative work. That day my keychain went missing. Anyone could have done that.}
{128}{}{I don't know. It's hard to steal anything in a factory, there's crowds of people everywhere, it's easy to get caught. And these keys, they're not very important. Whatever the thief is expecting, he's not going to get it.}
{129}{}{There was a whole crowd there. Perhaps it was someone new; others would have realized that my keys wouldn't bring them anything of value.}
{130}{}{How can you be sure you just didn't lose them?}
{131}{}{I'm an old woman, but I still have a good memory!}
{132}{}{I would be very grateful to you. Ask the workers around, preferably at lunchtime, when they go to the canteen. But I don't think anyone would admit it!}
{133}{}{I'll still try to get to the bottom of it. I will not tolerate scumbags who steal from women!}

#Завершение квеста
{150}{}{Your keys have been found.}
{151}{}{Really?! That's great! Where?}
{152}{}{I accidentally found them in the toilet - someone decided to hide them there.}
{153}{}{Turns out the black guy Tom stole your keys.}
{154}{}{That black guy Tom has them. Time to get him punished!}
{155}{}{That nosy Simon has them. Time to get him punished!}
{156}{}{Simon left the keys in the locker in the diner. Better hurry while they're still there.}

{157}{}{Oh, you are very observant! Too bad, now we'll never know who did it. But I have the keys now, so it doesn't matter.}
{158}{}{Yeah...}
{159}{}{What a rascal! I knew I had to be careful with him! From the looks of it, he seemed so simple-minded, but you know, I've never trusted black people, they even look scary to me! With their white pupils! Oh, the horror...}
{160}{}{That's right. And he also turned out to be a thief.}
{161}{}{Don't jump to conclusions. He stole the keys to punish his old enemy, that white bastard Simon.}
{162}{}{Hmm... That prick should have been kicked out of the factory a long time ago! And you know what, maybe that black man isn't as stupid as he looks... I don't think I'm going to say anything to anybody, let them figure it out for themselves. Anyway, on this matter, I only know it from your word, so I'll have to leave it at that. Because I've got the keys now anyway.}
{163}{}{Okay then.}
{164}{}{That nosy bugger, I never liked him! I'll gladly fire him from the factory! And let him try to come back...}
{165}{}{He deserves it!}
{166}{}{That's your decision.}

{167}{}{Oh, thank you so much! You saved an old lady a lot of trouble. How can I not thank you for that? Here, take $100 and a Cherry Nuka-Cola, it's our new flavor, not even on sale yet.}
{168}{}{That's it? Okay, at least it's something...}
{169}{}{Thanks!}
{170}{}{I think you need the money more than I do. But I'll take a Coke, it's good to freshen up.}
{171}{}{I never thought there were still good Samaritans these days! Thank you very much.}
{172}{}{You're welcome. And don't get into situations like this again.}
{173}{}{You're welcome.}

#Female character
{1152}{}{I accidentally found them in the toilet - someone decided to hide them there.}
