{100}{}{You see Principal Skinner.}
{101}{}{You see the managing director of the Nuka-Cola factory. He's got his business face on.}

#Начало разговора
{110}{}{Good day. What is your business here?}
{111}{}{Sorry to bother you.}
{112}{}{Anything else?}

#Автоматы колы:
{120}{}{I've heard your Nuka-Cola vending machines are constantly being robbed. Have you managed to catch the thief yet?}
{121}{}{No! That's some elusive operator. Sheriff Burton's been running off his feet. The only thing we know is *how* he performs his robberies. Sadly, we have been unable to come up with a good means of security yet. I'm afraid that eventually we'll have to resort to the hands-on sales practice and stop using vending machines. Our products will become more expensive. Alas. If you see anything suspicious, please report it to the Sheriff. We must catch the robber at all costs!}
{122}{}{I confess, It is me who's been robbing you. Now I feel bad about it.}
{123}{}{That's a pity, err... I hope you'll find the perpetrator.}
{124}{}{Come on! Don't make me laugh! It was probably some juvie from Salt Lake's outskirts or those bastards from Provo.}
{125}{}{Provo?}
{126}{}{Oh... My, my...}
{127}{}{Yes, I am more inclined to think it was them. Don't you know? It's a settlement to the south of here, homing criminals that were exiled out of the city by Burton. Now they hate the whole of Salt Lake for that. They once were the kings of the city's underworld, having free rein over whom to destroy and whom to spare. Fortunately, that time is in the past now. You'd better stay away from the area, just like we do.}
{128}{}{Got it.}

#Продажа фильтра
{140}{}{I managed to find the part which is needed to start the artesian tower.}
{141}{}{My God! You don't say! Is that really so?! And it works?}
{142}{}{I'm not completely sure, but it looks well-fitting.}
{143}{}{You know, I won't be asking any questions! I've been trying to find the part for several years! Please, sell it to me!}
{144}{}{Why should I sell it to you, exactly? From what I gather, the citizens also need water...}
{145}{}{It's in everyone's interest that the tower works properly. Water is the basis of life... And of our production. The cleaner it is - the bigger our income, and the more grateful clients we have. The factory will attracts rows of caravans to Salt Lake! It will cause a real uproar!}
{146}{}{Is that all?}
{147}{}{I would also like to note that our factory is the wealthiest enterprise in the city. No one will be able to offer you more for this thing than us. Do you understand?}
{148}{}{I do. How much do you offer?}

{149}{}{20,000 bucks. That is all we can allow right now. Keep in mind that our accounts are in the constant state of flux, the profits fluctuate, so tomorrow the price I mentioned may be different.}
{150}{}{I agree. Here's the part.}
{151}{}{No, I'd rather look for other buyers.}
{152}{}{Oh... Well then. I'm one hundred percent sure you'll come back though, because *nobody* in the city can offer you more money. Trust me on that.}
{153}{}{We'll see...}
{154}{}{You have delivered the water filter for the use in the artesian tower and with that improved the quality of life in the area.}
{155}{}{[The factory manager is fixated on the part, ignoring your presence.]}
{156}{}{Goodbye.}
{157}{}{[You drop the part on the floor, making the factory manager's hair stand on end.] WHAT ARE YOU DOING!!!}
{158}{}{Oh, don't worry, it's alright. Let me pick this back up...}

#Про артезианскую башню
{160}{}{Lately, I wandered into the artesian tower... Why don't you get it working?}
{161}{}{Yeah, I know. The whole city's been talking about it for ages. But alas, so far the talks remained just that - talks.}
{162}{}{What's the trouble?}
{163}{}{We have no filter to clean the water and remove impurities like sand and pebble. If we start the turbines without the thing, they will be rendered inoperable in a matter of hours.}
{164}{}{Is that filter so hard to find?}
{165}{}{You bet! There aren't many cities in the region that possess artesian towers of such size. We've tried to send caravans to so many places! Nobody could find the parts needed, not in New Reno, not in Denver, not even in Vegas - the city that is so huge and has lots of much cleaner water - not even there could we find the filter. We've lost all hope.}
{166}{}{Can't this filter be replaced by something else?}
{167}{}{I'm afraid it can't. No equivalent parts in the region.}
{168}{}{Well, too bad. It would be nice to find the part...}
{169}{}{}

#Третий квест - починка ПЛК:
{170}{}{What will be the next task?}
{171}{}{I'm afraid, you'll have to go on a business trip. That is, if you want to make some money, of course.}
{172}{}{Please, tell me more.}
{173}{}{Not interested.}
{174}{}{If we want our enterprise to be efficient, we'll have to set up some automation again. The main problem right now is the programmable logic controller. The rest our technicians can handle, but I don't think I've ever seen a single programmer here in Salt Lake. You'll have to find a specialist like that in another city and get that thing working again. This is a very important task. Do you think you'll be able to do it?}
{175}{}{I'll do it.}
{176}{}{Then please go visit our chief technician, he's in the nearby building. He'll give you all the details. I will cover your expenses after the job is done. Oh, and here's a ticket for a stagecoach. You may find it useful.}
{177}{}{Okay.}
{178}{}{The job is done. Here's a working controller.}
{179}{}{It pleases me greatly when everything works as intended! You have my thanks. Here's your payment: }
{180}{}{. Pleasure working with you.}
{181}{}{Goodbye.}

#Общие вопросы
{200}{}{Are you the director here?}
{201}{}{Could you tell me about the factory?}
{202}{}{How's business at the factory?}

{203}{}{That's right. My name is Skinner. Principal Skinner.}
{204}{}{How did you obtain your position?}
{205}{}{I'm a hereditary owner of the enterprise.}
{206}{}{Really?! No mob wars, no dumping dead bodies of competitors, blackmailing or intimidating, nothing?}
{207}{}{Hmm... Are you from Reno, perchance? They seem to like to deal with problems by smashing them with big sticks there. Here, everyone knows that no wannabe would be able to head an enterprise: they won't have the knowledge, nor the skills, nor the support of the community.}
{208}{}{I see. May I ask another question?}
{209}{}{Okay, that's enough.}
{210}{}{As far as I'm concerned, that's impossible - I think you've walked over many dead bodies to reach your goals.}
{211}{}{My ancestor was the owner of the factory before the war, but they were making quite different drinks here back then. Ten years ago, I started to actively work on re-establishing the factory: I found Nuka-Cola recipes and gathered necessary people, while the laborers were provided by the local forced-labor camp. Repairing old machinery was a much harder task, though. We spent many years to get it all to work.}
{212}{}{What is this nonsense?! Well... We did have forced laborers working for us, that is true. Those were some hard times, indeed.}

{213}{}{The factory hasn't been doing well lately. Production has been declining, our income is low and people lose motivation to work.}
{214}{}{The factory has been doing rather well lately. We have so many contracts now that we sometimes run short of hands able to work on them! Our income is high and people are as motivated as ever. We must strike it while it's hot and get the most out of the situation.}
{215}{}{Everything as usual: the people are lazy, the income isn't encouraging, but we have enough to keep our heads above water for now... Not sure how long we'll last, though.}
{216}{}{Some asshole has also sabotaged our production. We haven't been able to find out who it was. It must have been some tricky son of a bitch!}
{217}{}{Oh, and some bastard has been robbing our Nuka-Cola vending machines. That sly punk leaves no evidence behind and acts very carefully. I've already talked to the Sheriff regarding this matter. I'm sure mr. Burton will promptly deal with the problem.}
{218}{}{I see.}
{219}{}{Where do you get ingredients for production?}
{220}{}{There are several Mormon farms located in the Salt Lake City area. They grow all the necessary plants there. Salt and alkali are extracted from the Great Salt Lake's deposits. So we had no problems with that.}

#Второй квест - деталь у караванщика
{230}{}{What will be the next task?}
{231}{}{There's one caravaner out there who wants to take advantage of our troubles. We had a deal that he would find a new encoder for us to replace the broken one. We agreed on the price of $300. Now that he has the encoder, he asks for $1,000!}
{232}{}{[More.]}
{233}{}{That caravaner has a lot of nerve! Each day he raises the price even more, and we have no hope of buying it from another seller. The Sheriff decided to stay away from this conflict of interest of ours. Therefore, I'm offering you a deal: you get the encoder from him using *any* means that you may deem necessary, and I'll buy it from you for a reasonable price of $300. This way we'll resolve several issues at once: I'll get the part for a fair price, you'll make some money, and the caravaner will get what he deserves for his greediness.}
{234}{}{Sound good. Where do I find the caravaner?}
{235}{}{This crooked stuff is not for me. Sorry.}
{236}{}{Great. The caravaner is lodging at The 6'th Bullet.}
{237}{}{Got it.}
{238}{}{I have the encoder.}
{239}{}{Great. Just like we agreed - here is your $300.}
{240}{}{Piece of cake. Do you have other tasks?}
{241}{}{Thank you, but our cooperation will have to be put on hold. I'll come back when I'm ready to continue.}

#Первый квест - продавец довоенной колы
{250}{}{I'm looking for work. Maybe you can find a position for me?}
{251}{}{I have enough workers for now... On second thought, are you from around here?}
{252}{}{Oh, no, I'm just passing through.}
{253}{}{Passing through, you say? Then I may have something for you. You could do me a few favors then be on your way.}
{254}{}{Sounds good. What kind of favors are we talking here?}

{255}{}{Recently, some shady type has shown up in the business center. He dares to sell Nuka-Cola in this city, even though he has nothing to do with my factory. We have enough problems as it is, and he's just making things worse. If you rid the city of him, I'll pay you 300 bucks.}
{256}{}{Let me ask you something first.}
{257}{}{Rid the city of the shady Nuka-Cola salesman? I'll do it.}
{258}{}{You know, I don't think it's fair to do business like that. I refuse.}

{259}{}{Hmm... Make sure to shut the door on your way out.}
{260}{}{Er, okay.}
{261}{}{Thank you for your time. But please remember: I'm not asking you to do anything illegal, but I don't care how you deal with the guy. In any case, I will deny my involvement in any misconduct, and the Sheriff trusts me much more than he trusts you.}
{262}{}{I'll keep in mind your... Loyalty. The job's as good as done.}

{263}{}{Certainly. What would you like to know?}
{264}{}{Where do I find this salesman?}
{265}{}{How does a small retail outlet like that affects your enterprise?}
{266}{}{Is it your Nuka-Cola that the salesman trades?}
{267}{}{Why not ask the police for help?}
{268}{}{I see. I have other questions.}
{269}{}{As I told you: at the caravan camp.}
{270}{}{You think it's a "small retail outlet". But think about it, how can a random flashman have so many goods to sell? I don't know where he gets his Nuka-Cola, but it certainly doesn't come from us. Nobody knows how he got so many bottles for his stock. He may even have a full storage somewhere. What's worse is that his goods also cost less. Such competition may negatively affect the factory's reputation in the future.}
{271}{}{No, his stock does not come from our storages. We have already checked. It looks like he managed to stumble upon a pre-war Nuka-Cola cache. Some abandoned truck or a big warehouse, I don't know.}
{272}{}{I've already talked to the Sheriff about it. He doesn't see anything criminal in the salesman's activities. Thus, legally, his business is clean.}
{273}{}{Thanks for your answers.}
{274}{}{I have some questions about the job.}
{275}{}{About that "shady" salesman.}
{276}{}{Yes?}
{277}{}{The salesman won't be troubling this city anymore. Ever. He had a certain... "Accident" happen to him.}
{278}{}{The salesman is left without his goods, so he now has nothing to sell.}
{279}{}{The salesman handed in his goods and was hired to work for you by your manager upon my recommendation.}
{280}{}{Very good. It's good to see something done in a proper manner.}
{281}{}{Thanks.}

{282}{}{May I ask you a question? Why does you Nuka-Cola tastes different from the one sold by that salesman?}
{283}{}{[He frowns, showing his discontent with this conversation.] Firstly, the pre-war drink has been kept in closed bottles for more than 70 years. In that time, like wine, it has changed its properties, gaining new ones. The Nuka-Cola that you can find in pre-war stocks is already quite different than it once was. And secondly... I don't like to talk about it, but we don't know how the drink was made in the past. We managed to attain a more-or-less similar tasting qualities, thanks to the information from the labels and our own laboratory research. Of course, it's not a complete match. That's why our Nuka-Cola is somewhat different from the pre-war one, but people still like it.}
{284}{}{Thanks for your answer. Now the things are much clearer.}

#Female character
{1120}{}{I've heard your Nuka-Cola vending machines are constantly being robbed. Have you managed to catch the thief yet?}
{1122}{}{I confess, It is me who's been robbing you. Now I feel bad about it.}
{1150}{}{I agree. Here's the part.}
{1160}{}{I once wandered into the artesian tower... Why don't you get it working?}
{1251}{}{I have enough workers for now... On second thought, are you from around here?}
