{100}{}{You see Simon.}
{101}{}{Sharp glance, volitional chin and proud posture give this white worker a look of informal leader.}
{102}{}{Fucking locker! Close, damn it!}
{103}{}{The fuck are you looking at? Want to be punched in the teeth?}
{104}{}{ }
{105}{}{I'm not in the mood right now...}
{106}{}{How are you? Do these niggas bother you? Good.}

{110}{}{Stranger? What's the matter? I'm trying to rest from all those idiots in the factory. So I really don't want to hear anyone out.}
{111}{}{Do you know anything about the missing keys of the manageress?}
{112}{}{Do you know that this black man in the dining room wanted to kill you?..}
{113}{}{Then I'm not going to bother you.}

{114}{}{Fuck me gecko! Yes, I have already gutted all the drawers and pockets! I have NO fucking keys and never had!}
{115}{}{What? Again? Can't I fucking rest from all these stupid questions?}
{116}{}{[Simon listens to the story with his mouth open] That son of a bitch! This nigga's too tricky to have the right to live on this planet! And you know what I gonna do now? Oh, no, I'm not going to punch him in the face! He tried to outsmart me, and now I will outsmart him.}
{117}{}{What do you have in mind?}
{118}{}{Well, let's say. I need a man who would throw the keys to that nigga's pocket, and then tell about it to that old woman. I'll pay! Of course, I could have done that myself, but, in my case, it is unsafe - can arouse suspicion. And you're a new man, nobody will suspect a thing. Well, what do you say?}
{119}{}{If you pay - I'm in.}
{120}{}{No, I don't like it.}
{121}{}{That's great. Waiting for news, partner!}
{122}{}{All right.}
{123}{}{Sure, you can just leave. All good. But think about it - I would pay good money and, perhaps, could sneak something off the factory for you. What can this old woman and fat nigger offer? I'm not in a hurry. Think about it. When you're ready - act.}
{124}{}{I have to think about it...}

{125}{}{Your black rival is dead.}
{126}{}{I snitched the negro, as we agreed. Now he is fired.}
{127}{}{It feels damn nice, when people are brilliantly doing their job! Oh yeah... I always keep my word. 250 bucks for this. Of course, this is not the best money in the world, so I can only offer gas protection suit in addition. It can be sold for good money on the market. Believe me, that nigga would not give you more than that.}
{128}{}{That's right! Well, let's split up, as if we never met. Take care.}
{129}{}{Don't come near me until you will solve all the problems.}

#Женские реплики
{1110}{}{Stranger? What's the matter? I'm trying to rest from all those idiots in the factory. So I really don't want to hear anyone out.}
{1121}{}{That's great. Waiting for news, partner!}
{1126}{}{I snitched the negro, as we agreed. Now he is fired.}
