{100}{}{You see a merchant.}
{101}{}{You see a caravan leader. Judging by his tanned skin, he travels a lot.}
{102}{}{Move away from me!}
{103}{}{All my merchandise is destroyed! I'm ruined! I'm broke!!!}
{104}{}{Tomorrow we won't be here.}
{105}{}{Enjoy the marvelous taste of Nuka-Cola!}
{106}{}{Oh...}
{107}{}{Thanks to you our future is finally a little bit brighter. Thanks.}
{108}{}{The goods in the wagon had been completely destroyed.}

{110}{}{Hey, do your feet burn from the road? Here, have a bottle for refreshment. It will cost you only 3 bucks.}
{111}{}{Tempting, but what is this drink and where it came from?}
{112}{}{Thank you, but no.}
{113}{}{Well, I was lucky to find a few boxes of pre-war Nuka-Cola. I've tried it myself - and it's an absolutely clean and quality product! And, by the way, much better than at the local factory.}
{114}{}{So you have nothing to do with the local Nuka-Cola factory?}
{115}{}{Oh, no. I'm not local myself, and I was surprised, when I learned that there is a whole factory here. So I have to sell cola cheaper, to sell it faster before the factory thugs come to find out... Although I'm probably exaggerating, heh. Why such a large factory would care about some small seller from the wasteland?}
{116}{}{Maybe. I bet the factory wouldn't like it for sure.}

{117}{}{Fortunately, in this town there is a Sheriff that honors law and justice. So I can sell you a few bottles. That is what you standing here for, right?}
{118}{}{Yeah.}

{119}{}{Come. Only 3 bucks a bottle!}
{120}{}{Give me a bottle of pre-war Nuka-Cola.}
{121}{}{Give me three bottles of pre-war Nuka-Cola.}
{122}{}{Did you know that your Cola reeks of radiation a mile away?}
{123}{}{I was asked by the factory to eliminate your annoying ass. But I can consider peaceful alternatives.}
{124}{}{Hey, don't be stupid! The Sheriff himself gave the permission to sell here... Though threatening to throw me out of the city, if I cause any fuss. Besides, the local caravan won't approve. And finally, it's not fair! I honestly earned my goods and dragged them here on my own back. And now it turns out that I'm a criminal! All because the factory does not want to recognize the most important thing - that their product is much worse than pre-war one. Just try it and you will immediately feel the difference! Want some?}
{125}{}{Unlike your goods, the products of the factory do not stink radiation a mile away.}
{126}{}{Really? Wow, what a surprise... Well, I'll have to... Uh... Smash it all somewhere on the outskirts of the city.}
{127}{}{You're a bad actor. You knew that the bottles are irradiated, but still brought them to sell to the local population. Isn't your conscience tormenting you?}
{128}{}{[He starts to look tired] Maybe... But listen. In the village where my son and I are from, there's no one left because it had become impossible to live there. One day I found out about an abandoned Nuka-Cola truck. The batch in my wagon is all that was there. Honestly. I just wanted to make a quick buck and get out of town. Me and my son are left without shelter and food, we need something to buy supplements and ammunition with. In other circumstances, I wouldn't have to climb into irradiated truck. Besides, bottles not so irradiated for anyone to notice.}
{129}{}{Then I can buy all your cola.}
{130}{}{Then I will report you to the police.}
{131}{}{Drop the shit until the police have you arrested and get you out of town.}
{132}{}{I need to think about it.}
{133}{}{Don't even dare! We put so much work to get those bottles and bring them here! Please, have mercy on me and my son! We have nowhere to go, our village is empty. I promise we'll leave once we get some supplies and ammo for the road.}
{134}{}{Eh... Even so, we have no choice. We have nowhere to go, our village is empty. I promise we'll leave once we get some supplies and ammo for the road.}
{135}{}{Well, no. You'll HAVE to leave NOW!}
{136}{}{I want to buy this drink.}
{137}{}{GREAT! How many bottles?}
{138}{}{}
{139}{}{ for }
{140}{}{ buck[s].}
{141}{}{All }
{142}{}{Thanks! If you want more - come again.}
{143}{}{Okay.}
{144}{}{Thanks... Hey, look! The last box is empty, which cannot be said about my pockets. Hehe, it's finally over and we can leave. Thank you, your help was very handy!}
{145}{}{This is good.}
{146}{}{Why not to work for the factory as an official courier? You have all the necessary qualities.}
{147}{}{That'd be great, but they don't think we're suited for them. For some reason I couldn't reach an agreement with these guys. They think the courier has to have a good look and smell. Although I know the region well and know my hunting rifle well, and that's more important than good looks. And I know the mentality of the locals much better than these city snobs. But the managers at the factory don't think so.}
{148}{}{Hmm. I see.}

{149}{}{I was able to make a deal with the manager. They are willing to accept your caravan as an official courier.}
{150}{}{Wow, you must have a great reputation in these parts! Thanks for the help, I would never get this job by myself. Here, have some Nuka-Cola as a gift.}
{151}{}{Yeah, take care.}
