{100}{}{You see the clerk Harry.}
{101}{}{You see a fussy, ever smiling clerk.}

#Вопросы
{110}{}{Yes-yes? How can I help?}
{111}{}{See you.}
{112}{}{Can I find a job here?}
{113}{}{I don't know that. Talk to our director, he usually checks every worker himself. Director Skinner is in his office, behind me.}
{114}{}{Thanks, I'll go to him.}
{115}{}{I have a part that will allow to launch artesian tower. Who should I speak to, about the price?}
{116}{}{Oh, yes! Sure, the factory's in need of repairing this tower! Speak to our director immediately. He's in his office, behind me.}
{117}{}{Oh, it's you! We have heard about your courier achievements, and are glad that you want to work with us.}

#Плавающие нотации:
{150}{}{Ladies and gentlemen! That's how we should work!}
{151}{}{No slacking.}
{152}{}{Clerk is a basis of any enterprise.}
{153}{}{Clerk is like a God... Yes, exactly.}
{154}{}{I can save the factory or bring it down. Do you understand how important I am?}
{155}{}{The most important thing is to gain the trust of the client.}
{156}{}{What is the most important for the client? Right, to be kissed in the ass.}
{157}{}{We'll have a lot of customers, if you work hard.}
{158}{}{Don't even think of slacking!}
{159}{}{Well, and where are our active clients?!}
{160}{}{There's no customers because you are lazy!}
{161}{}{If you wouldn't be lazy and worked like me...}
{162}{}{No career progression! One either progresses, or doesn't.}
{163}{}{Don't confuse marketing and management! It's not the same.}
{164}{}{We need a decent designer...}
{165}{}{I knew a designer once...}
{166}{}{Our enterprise either good, or... Oops, no or.}
{167}{}{Well? Are you done being lazy?}
{168}{}{Wake up! There's customers!}
{169}{}{Oh! Look - a customer!}
{170}{}{Watch how I'll sell to him!}
{171}{}{Five percents! FIVE PERCENTS!!!}
{172}{}{A man-clerk should be moderately unmarried.}
{173}{}{Hands-out-of-ass - that's about you!}
{174}{}{When's lunch?}
{175}{}{I'm starving here... Oooh...}
{176}{}{Is anyone going to the market? I want some jerky...}
{177}{}{The most important thing in management is to work with people.}
{178}{}{The clerk is the coolest job! You don't believe it? Too bad!}
{179}{}{Did you write everything? I will check!}

#Торговец довоенной колой на стоянке
{180}{}{Why don't you want to hire the caravan merchant that sells pre-war cola?}
{181}{}{Oh, I remember, yes-yes. It's our rival with a very shady business, right? We don't need people of such... Uh, origin. Well, you know, peasants with tanned skin and working hands will not get people's affection.}
{182}{}{I think you're wrong. You should not throw away such a good worker.}
{183}{}{Could I change your mind? No, not likely... Fine, see you.}
{184}{}{Oh, really? And what should change my mind?}
{185}{}{My recommendation as an experienced courier.}
{186}{}{My recommendation as an experienced trader.}
{187}{}{This changes things. So what is so good about him?}
{188}{}{You focus on communication and appearance, instead of real skills and experience. It's good in the urban environment, but with the villagers it's different. This trader will be accepted with them as his own, that makes it easier for him to negotiate.}
{189}{}{Hmm. I had never thought about this like that. Now I understand, why our couriers fail assignments in settlements. Perhaps we will have to reconsider the approach. Please, tell this merchant that we would like to conclude an agreement with him - provided that he will give us the remaining Nuka-Cola.}
{190}{}{You made the right choice, Harry.}

#Про лицензию
{200}{}{How about a joint business?}
{201}{}{You want to sell cola in other cities, right?}
{202}{}{Maybe!}
{203}{}{If so, then I am at your service! Welcome to the office of the *operating* Nuka-Cola factory! The only one in this region, and possibly the whole world. With us, you can at any time make a deal on the delivery of the drink to any locality and for any institution. But I warn you right away - we just accept the orders, you must deal with deliveries yourself.}
{204}{}{In other words, you just give the license to trade the soft drink?}
{205}{}{We produce the drink and give it in the form of a large wholesale batches. Of course, you can simply buy a lot of cola every time and deliver it to your companions. But for those who buy a license, we give a discount and reserve an order.}
{206}{}{Reserve?}
{207}{}{Yes. When we know the volume of your order, we just store it and wait for your caravan. Otherwise, we distribute the order to any incoming customers. And then your caravan is at least doomed to wait a few days until we again produce the required quantity.}
{208}{}{So, by purchasing a license, I get a guarantee that my goods will stay in place, right?}
{209}{}{Correct! But we need to make one more remark. Now in the wastelands there are rumors of a low-quality commodity. This undermines the reputation of the factory. If you have proof that you work with us directly, your customers will have more incentive to make a deal with you and give you much more trust.}
{210}{}{That is, I can enter into transactions without a license?}
{211}{}{Perhaps! If you look trustworthy enough. But believe me, most of the traders already learned the lesson and try to work only with those who have a license.}
{212}{}{How much for this license?}
{213}{}{We will sell it you for }
{214}{}{ bucks. Very good price, if we count, how much you gain by selling.}
{215}{}{It's tempting. And what to do after?}
{216}{}{Only you can decide. You can buy a large shipment of cola. How to find a client and how to deliver it - is your job. We recommend talking to caravan merchants. Of course, they will take some percentage for their services, but they can transport a lot of bottles very fast.}
{217}{}{How many couriers are there right now? Will I be able to make money on such business?}
{218}{}{I think yes! You see, for a while, the factory worked mainly on the inner city market. The wastelands are poorly acquainted with our products, still consuming the reserves from a pre-war times.}

{219}{}{I want to purchase a license! How much?}
{220}{}{Thank you, for explaining, I will think about it. Take care.}
{221}{}{ bucks. That is director's price, he ordered not to haggle for it.}
{222}{}{I'm buying!}
{223}{}{Oh, I can't afford that. See you.}
{224}{}{Don't drop your money! It's the most horrific thing I ever seen!}
{225}{}{Oops, sorry.}
{226}{}{[You sign a pile of papers and shake hands] Good luck in business, courier! We wish you and your humble cause prosperity and every success!}
{227}{}{Same to you!}
{228}{}{You became the official representative of the Nuka-Cola factory. Congratulations on your prestigious position!}
