{100}{}{You see Tom.}
{101}{}{Big white eyes on the face of this black man seem to shine with bright sadness.}
{102}{}{Praise to you! Don't stir from the right path.}
{103}{}{Oh God... You are still here...}

#Ïåðâûé äèàëîã
{110}{}{Just as I was going to swallow the first spoon of my soup, a fly flew in. You know, it's pretty unpleasant, but you have to deal with it.}
{111}{}{Hello. Such a good day today, isn't it?}
{112}{}{Fine, eat, I won't bother you.}
{113}{}{Right. I better go get some fresh air outside.}

{114}{}{Who are you?}
{115}{}{I'm Tom, simple worker.}
{116}{}{Nice to meet you. Perhaps, we can talk next time.}

{117}{}{Why are they treating you this way, Tom?}
{118}{}{Everybody is treating me like this. Blacks and whites. Maybe, it's something with my nature. But don't pay any attention - they just fool around, they don't mean harm. Though, of course, there are those who would just break your face, if you'll allow them to. Fortunately, not many of that kind left here - the community doesn't like them.}
{119}{}{For example?}
{120}{}{Too bad, Tom, but I will have to leave you.}
{121}{}{I would make fun of you myself if I could right now, but I have no time. Breathe for now.}

{122}{}{[Looks around] Uh, listen, I don't want to talk about anyone, I'm a peaceful man!}
{123}{}{Fine, as you wish.}
{124}{}{Where are you looking at? It was the white guy standing near the lockers, wasn't it?}
{125}{}{Simon... Uh, don't ask me about him... I don't want to talk about it... Neither bad, nor good.}
{126}{}{I can help you get rid of him, if you want.}
{127}{}{I can help you get rid of him, if you'll tell me, who stole the keys from the administrator.}
{128}{}{Oh Lord! I'm a peaceful man, Leave me alone! Simon is a scumbag for sure, I would appreciate him to be somewhere else, but I won't be carrying bloodshed on my soul. Plus, I don't have anything to pay anyway.}
{129}{}{Bloodshed? You said "bloodshed"?! Tom, I didn't mean to kill him! Scaring him a little would be enough.}
{130}{}{Honestly speaking, I don't trust you. Not many good things are heard about you in Salt Lake. Sorry.}
{131}{}{Puny beggar, I don't even want to talk to you.}
{132}{}{Fine, Tom, I won't insist.}
{133}{}{Damn coward, I don't even want to talk to you.}
{134}{}{[Thinks a while, looking around] Listen, let's step into somewhere more private, okay?}
{135}{}{Sure, I'm listening...}
{136}{}{[Whispers] Please understand. That Simon - he's an arrogant bastard. He will slice anyone his complexion and position allows him to. He's a very cruel man. God forbids people like that gaining such power!}
{137}{}{Sure. And that's why I want to help.}
{138}{}{I hear, but this doesn't matter to me.}
{139}{}{And I have a great plan, but peaceful. [sighs] I stole the keys from the administrator and hid them in the toilet. Yes, it was really me.}
{140}{}{Hmm, continue.}
{141}{}{I thought that will create some panic in the factory, and when the investigation started, I would plant them on Simon. But, this went against my principles. I can't frame a person, even an animal like Simon. Besides, it would be very risky in my position.}
{142}{}{Well well...}
{143}{}{Now I don't know what to do. I thought about confessing and returning the keys, but then they would fire me. And, as you can see, I can't lie...}
{144}{}{Well, Tom, listen: Sit still, keep quiet, and I will think of something.}
{145}{}{Ha, confessed it yourself! That's it, wait for my decision and mercy, so I don't tell on you.}
{146}{}{May the God bless you!}
{147}{}{Er, fine. Now we must say farewell to each other.}
{148}{}{Yes, it seems I deserve it... Please - think about it, think about it good.}
{149}{}{Whatever I decide - that's how it will be. Now get away from me.}

{150}{}{About Simon...}
{151}{}{What about him?}
{152}{}{He's dead. And don't ask how it happened - it's not important.}
{153}{}{Rejoice - he got fired! For... The key theft. Who would have thought, right?}
{154}{}{I wanted to ask something, but forget it.}
{155}{}{Oh, God, what have you done! It seems nothing in this world can be solved peacefully. Now his death is on me! Oh, God...}
{156}{}{Hey old man, shut your mouth. I helped you solve the problem. Have some respect. And give me something. These things don't cost a sandwich!}
{157}{}{How can I? I'm a simple worker. I don't make much money. I can only give you my gas suit. You can sell it.}
{158}{}{Give me the suit. Better, than nothing.}
{159}{}{Here. And no more shit alright? I'm pissed of already. Enough is enough!}
{160}{}{This is you problem. Bye.}
{161}{}{[Smiles] Damn that was good! You actually did it! Thank you, for everything you did. And most importantly - for you kindness and understanding. Something that is really missing in this world.}
{162}{}{Yeah. It's a shame that saving the world can't be placed in one's pocket...}
{163}{}{Glad to be of help.}
{164}{}{Uh, I have nothing to give you. I'm a simple worker. I don't make much money. I can only give you my gas suit. You can sell it.}
{165}{}{Here. I hope, it will help you somehow. Take care.}
{166}{}{Bye. And don't leave anyone bully you again.}

{167}{}{Tom, someone stole the keys from the administrator, and I'm going to find the thief. Whoever did this - he won't get away. You don't want the suspicion to fall on you, right?}
{168}{}{About Simon. I will help you to get rid of him, if you tell me who stole the keys.}
{169}{}{Cold sweat, wide pupils, increased heart rate... My detective experience tells me that you are hiding something.}
{170}{}{You're not a good liar, Tom. I see you know more than you're telling me.}
{171}{}{[In shock] Private detective? Is this a thing in our times? Wow...}
{172}{}{For me it's just hobby, not my duty...}
{173}{}{I have the keys. Remind me what you wanted to do with them?}
{174}{}{*smell* I can sense a thief from a mile away! [take a deep breath] YES, IT'S YOU!}
{175}{}{Umm... You're not serious, aren't you?.. Heh... I mean, how can you sense the thief...}
{176}{}{[Stare at him seriously]}

#Ïëàâàþùèå èçäåâêè îò òîâàðèùåé â ñòîëîâîé
{180}{}{Hey, old man, want some... *milk*? Ha-ha!}
{181}{}{Tom stares again. Don't look away, dumbass!}
{182}{}{Don't call you a nigger? Sorry, I can't!}
{183}{}{Tom, how about a joke about Africa?}
{184}{}{Hey, Tom, you can't get a black eye, can you?}
{185}{}{How did it happened, to have so many blacks in here? Tom did you gather everyone?}

#Female character
{1116}{}{Nice to meet you. Perhaps, we can talk next time.}
{1121}{}{I would make fun of you myself if I could right now, but I have no time. Breathe for now.}
{1156}{}{Hey old man, shut your mouth. I helped you - solved the problem. Have some respect. And give me something. Such things don't cost a sandwich!}
{1161}{}{[Smiles] Damn that was good! You actually did it! Thank you, for everything you did. And most importantly - for you kindness and understanding. Something that is really missing in this world.}
{1163}{}{Glad to be of help.}
