{100}{}{You see a policeman.}
{101}{}{You see a policeman in combat armor. He watches the streets.}
{102}{}{Move along.}
{103}{}{Hey, you! Put your weapon away!}
{104}{}{I'm watching you. Don't even think about trying anything funny.}

{110}{}{What happened?}
{111}{}{I just witnessed a thief sneaking into the mall!}
{112}{}{It's nothing, I'm just bored.}
{113}{}{You just gave away your partner!}

{114}{}{Stop, don't move! I have you in my sight!}
{115}{}{NO!!! CHIEF!!!}
{116}{}{Too late, my friend. Step into the light.}
{117}{}{Policeman: "We caught the asshole. You did a good thing, turning him in. When you have time, talk to Sheriff Burton. He'll give you something for your trouble."}

#Женские реплики
{1117}{}{Policeman: "We caught the asshole. You did a good thing, turning him in. When you have time, talk to Sheriff Burton. He'll give you something for your trouble."}
