{100}{}{You see a sick city dweller.}
{101}{}{You see a sick citizen. Sweat drips off his forehead. He must be having a fever.}
{102}{}{You see a citizen. His face looks brighter. He must be feeling pretty good.}

{103}{}{Hello. What are you doing in my house?}
{104}{}{Get away! I feel so bad! O-Oh...}
{105}{}{Here's my savior! Hats off!}
{106}{}{Hey, it's okay. I'm done with these injections.}
{107}{}{I'm fine, really... Thanks for the concern.}
{108}{}{Oh, thank you! I feel better already!}
{109}{}{You gave the patient an antidote. Soon he will recover.}
{110}{}{What the hell are you doing!?}
{111}{}{This will not help him.}
{112}{}{Are you out of your mind? Get away from me with that stuff!}
{113}{}{This will not help him. You need the antidote.}
{114}{}{This man doesn't need treatment.}
{115}{}{Medicines are needed.}
{116}{}{The patient has dysentery. He needs medication, using skills alone is not enough.}
{117}{}{Are you sure you know what to do?}
{118}{}{You fail the treatment.}
{119}{}{You have successfully treated the patient. Now he definitely feels better.}
{120}{}{You see a citizen.}

#Женские реплики:
{1105}{}{Here's my savior! Hats off!}
