{100}{}{You see a passerby.}
{101}{}{You see an ordinary Salt Lake City citizen.}
{102}{}{Sorry, I'm in a hurry.}
{103}{}{Oh, Mister Hickok! Glad to see you!}

#Наем машиниста:
{300}{}{Hi. How are you?}
{301}{}{I'm looking for a trainman. There is a long road ahead...}
{302}{}{Fine.}
{303}{}{You're nuts! No one in this city will even go near the train station. The sheriff won't let you! If anyone would go with you, it certainly wouldn't be a local. Enough of this. I don't want to get in trouble.}
{304}{}{Too bad.}
