{100}{}{You see a citizen.}
{101}{}{You see a citizen.}
{102}{}{You see a common citizen of Salt Lake City.}
{103}{}{Don't bother me.}
{104}{}{Don't bother Robert, please. He's yet to cut fruit for dinner because of that stupid puzzle of his.}

#Состояние санитарии: отличное
{120}{}{It's been a while since somebody threw up in front of the house.}
{121}{}{I'm so worked up today!}
{122}{}{I haven't had so much energy since forever.}
{123}{}{It's like I'm ten years younger!}
{124}{}{I'm ready to show my power!}
{125}{}{I got an immense appetite today.}
{126}{}{Actually, I'm hungry as hell.}
{127}{}{I'd eat a full roasted gecko... Or a half of it, at least.}
{128}{}{I should start running in the morning. Running away from stray dogs or something.}
{129}{}{Don't wanna sleep at all.}

#Состояние санитарии: плохое либо нейтральное
{130}{}{Somebody vomited in front of the house again...}
{131}{}{I'd better start stocking up vocas till the next growing season.}
{132}{}{The drug store is empty.}
{133}{}{Something has to be done about this bloody flux.}
{134}{}{A whole evening of shitting bricks awaits me.}
{135}{}{I need to find a restroom... Oh, shit... Not anymore...}
{136}{}{I don't feel so good... I need... Some rest...}
{137}{}{They say drinking beer helps with diarrhea.}
{138}{}{Such a big turd came out of me yesterday! You won't believe it!}
{139}{}{It's better to drink Nuka-Cola than water.}

#Состояние завода: диверсия или плохое состояние
{140}{}{I heard that the factory's been sabotaged.}
{141}{}{The sabotage was clearly done at the hands of those bastards from Provo.}
{142}{}{Damn. If the factory shuts down, it won't be good for anyone.}
{143}{}{I hope the factory holds out...}
{144}{}{Be strong, Salt Lake, the factory will soon become history.}
{145}{}{There's some real crap going on at the factory, man.}
{146}{}{My sib is going to quit his job at the factory.}
{147}{}{The factory is cursed.}
{148}{}{Remember how great the factory once was?..}
{149}{}{When will the factory director sort it out already?}

#Состояние завода: отличное состояние
{150}{}{There's never been so many caravans coming in for Nuka-Cola.}
{151}{}{Nuka-Cola is in great demand.}
{152}{}{Wow, so much fuss around the factory!}
{153}{}{So many people near the factory, like there's some sort of performance.}
{154}{}{Never thought I'd see something like this.}
{155}{}{Hail, the Nuka-Cola factory director! The king of all directors!}
{156}{}{It seems they hired some good clerks at the factory.}
{157}{}{The factory is back on its feet all of a sudden.}
{158}{}{What? Another Nuka-Cola caravan? How many can there be...}
{159}{}{They only go to Salt Lake for Nuka-Cola...}

#Если Прово уничтожен / Гилмор повешан
{160}{}{In my opinion, those rednecks from Provo deserved it.}
{161}{}{It wasn't easy, I reckon - Gilmore was one hell of a moosey.}
{162}{}{Provo won't come anywhere near here.}
{163}{}{That's how you deal with Provo, should've done so from the start!}
{164}{}{The Sheriff used his cunning on that one, founding someone to deal with Provo.}
{165}{}{I wonder, who did they hire to deal with Provo? Burton surely didn't soil his own hands.}
{166}{}{Nah, the Sheriff wouldn't get his hands dirty, not even for those assholes.}
{167}{}{Gilmore, you sonovabitch, burn in Hell!}
{168}{}{That's more like it! A proper response!}
{169}{}{Those Provo jerks have long had it coming!}

#Состояние завода: среднее состояние
{170}{}{Something odd's going on at the factory.}
{171}{}{The factory could use a capable manager.}
{172}{}{When will the factory start working to its full capacity?}

#Ворюга пойман
{180}{}{That thief has finally been caught! Serves him right.}
{181}{}{Hail, the Sheriff of Salt Lake, Burton the Whip! A menace to all thieves!}
{182}{}{That thief's fate will be an example to all other thieves.}
{183}{}{That thief had it coming!}
{184}{}{That's right! He deserves time in the clink!}
{185}{}{Now, the criminal activity here will die down for sure.}
{186}{}{I hope there'll be less robberies in the city now.}
{187}{}{With that thief caught, I feel kinda better.}
{188}{}{Thievery will not be tolerated!}
{189}{}{Be scared, thieves of Salt Lake!}

#Автоматы колы взломаны
{200}{}{When will they get that thief?}
{201}{}{Did they catch the person who was robbing the vending machines?}
{202}{}{The Nuka-Cola vending machines may be discontinued because of the thefts.}
{203}{}{Somebody's been persistently robbing the vending machines.}
{204}{}{Some slickster has robbed half the Nuka-Cola vending machines in the city.}
{205}{}{Have you noticed that the Nuka-Cola vending machines have been emptied?}

#Состояние города: отличное состояние
{210}{}{I'm not moving anywhere from this city!}
{211}{}{The city is now awesom-er than it was.}
{212}{}{I can't believe my own eyes! Is this really the Salt Lake City?}
{213}{}{I would never have thought that Salt Lake would become like this.}
{214}{}{Remember how we started? Those bad times are in the past now...}
{215}{}{Is this Salt Lake? It's like only yesterday it was a completely different place.}
{216}{}{The city is growing, that's a fact.}
{217}{}{Perhaps, I should move closer to the downtown.}
{218}{}{The city's become more interesting. Much better than before.}
{219}{}{Hail, great Salt Lake!}

#Состояние города: плохое состояние
{220}{}{I feel sad.}
{221}{}{I wish I had been born in New Reno.}
{222}{}{I can't believe my own eyes! Goddamned Salt Lake City!..}
{223}{}{It seems there are fewer and fewer caravans these days.}
{224}{}{Remember how we started? And now it all has come to this...}
{225}{}{Is this Salt Lake? It's like only yesterday it was blossoming...}
{226}{}{The city is in a decline, even more so than before.}
{227}{}{Damn it all to hell!}
{228}{}{I'd better relocate to Vegas.}
{229}{}{No, no, I must find my way out of this place.}

#Про поезд-призрак
{230}{}{They say that the ghost train has recently run through the city.}
{231}{}{The neighbors say they heard the ghost train again.}
{232}{}{I wonder for how low will that ghost train keep rumbling around here.}
{233}{}{Did anyone hear wheels rumbling yesterday at night?}
{234}{}{I swear to God, I saw it running from 30 feet away!}
{235}{}{It exists, I swear it!}
{236}{}{Everyone's already heard it!}
{237}{}{The ghost train was collecting souls in the wasteland again.}
{238}{}{So it happens - you live a life and then the ghost train takes you away.}
{239}{}{The ghost train is collecting souls again.}
{240}{}{I wouldn't want to cross paths with the ghost train.}
{241}{}{Oh, we all are going to board the ghost train at some point.}

#Наем машиниста:
{300}{}{Hey, how's it going?}
{301}{}{I'm looking for a train driver. A long journey is ahead.}
{302}{}{Everything's fine.}
{303}{}{You must be crazy! Nobody in the city will even dare to come close to the railway station. The Sheriff won't let it slide just like that! You won't find any here willing to go with you. Let's not talk about it anymore. I have enough problems as it is.}
{304}{}{Shame.}
