{100}{}{You see a pharmacist.}
{101}{}{It's a pharmacist, though he may even be a doctor... But now he acts as a pharmacist.}

{102}{}{It must be an interesting task if you're a doctor or a chemist... But thank you for telling me.}
{103}{}{Well, it seems the issue has been resolved. It also means that I will have something to do sitting by the campfire in my free time. Goodbye, colleague!}
{104}{}{Thief! Help!}
{105}{}{I wonder, which?}

{110}{}{I'm listening.}
{111}{}{Show me the goods.}
{112}{}{Do you need a worker for a modest fee? There is one poor guy that can't find a job.}
{113}{}{No. I can barely earn for a livelihood myself. Paying the workers is too much for me... Maybe the Sheriff needs someone. There are always people doing something around him.}
{114}{}{Okay.}
{115}{}{Well, I've helped as much as I could. I have nothing more to offer.}
{116}{}{One more time.}
{117}{}{Su-u-ure. Goodbye.}
{118}{}{Goodbye.}
{119}{}{Let's go back.}

#About the filter for the tower:
{120}{}{About the healthcare in the city...}
{121}{}{What do you want to talk about?}
{122}{}{About the filter for the artesian water tower. I've found it! But how to start the tower? Is there anyone I can discuss this issue with?}
{123}{}{Well, with me, of course! Because all people here come to me with a damn dysentery. I would have ensured that the tower is running.}
{124}{}{And what will you do afterwards? Sell water?}
{125}{}{If I had it my way, I would give the water away for free. But, in our circumstances, I will have to act differently. First, it is necessary to pay a considerable amount to the guys who will fix everything and prepare the area for work. Then I need to hire guys for protection. Maybe I can ask the Sheriff, we'll see. At least I wouldn't be jacking up prices, unlike the Nuka-Cola factory. For them, it's all about commerce.}
{126}{}{So, the factory is also interested in buying this filter?}
{127}{}{Well, of course! But mark my words, if the factory becomes the sole owner of clean water, it will be even worse than without any clean water at all!}
{128}{}{Why?}
{129}{}{A sanitary catastrophe is looming around the city. I can see that. No one can be sure that they will wake up the next day after sleeping. If the city has clean water, people will start at each other's throats. There will be serious conflicts.}
{130}{}{Sounds complicated. And how much you can pay me for the filter?}
{131}{}{5 thousand, as well as a 30% discount at my pharmacy for you. I can't offer more.}
{132}{}{It's a deal!}
{133}{}{After listening to this heartbreaking story, I'll give you the filter for free.}
{134}{}{I'll think about your offer.}
{135}{}{Thank you! This is the real salvation of our city!}
{136}{}{I understand. Goodbye.}
{137}{}{You delivered the filter for artesian water tower and significantly improved the living conditions of the local population.}

#About artesian water tower:
{138}{}{I visited the artesian water tower in the slums. Has anyone tried to fix it? That would give a ton of clean water for the city!}
{139}{}{It would, of course. This tower has been attracting everyone's attention for a long time. Nuka-Cola factory hired some people, the Sheriff tried to find someone to repair it, there were even couriers sent to other cities. But all in vain.}
{140}{}{What's the problem?}
{141}{}{In general, the tower is in working order. Only one piece of equipment is not working - the purification machine. To fix it, we need a new filter. But no one knows where to get it. You can't buy such things in a convenience store. However, there was a rumor that someone in Vegas found a suitable part. But that's just a story, or they would have brought it here a long time ago.}
{142}{}{Hmm, sounds like a serious problem. I hope I come across such a filter.}
{143}{}{Doubtful, but if you often move around the Wasteland, ask around in the cities. Better to start from Vegas.}
{144}{}{Vegas then... I'll remember that.}
{145}{}{You got the Las Vegas coordinates.}

#About radiation in the city
{154}{}{How can you live in such a humid and smelly climate? Perhaps visitors have respiratory problems?}
{155}{}{That's right. One does need to get used to to local conditions. But the body adapts over time. Most importantly, do not stick your nose where it doesn't belong.}
{156}{}{And where doesn't it belong?}
{157}{}{In the North there is a large radioactive area, a real cemetery. That was the part of the Salt Lake City metropolitan district on which nuclear bombs were dropped during the war. Rains periodically wash out the radioactive dirt into the Great Salt Lake. Fortunately, we are lucky with the climate.}
{158}{}{How so?}
{159}{}{Our landscape prevents most of the dangers. There are no harsh winds like in the deserts, and no fumes from heat. In addition, in local conditions, one plant has mutated. The water lily. It grows on the banks of the Great Salt Lake. In other cities it is just a plant, but this one gives you a special kind of nutritious nut.}
{160}{}{Oh, that's why on the way here I saw people constantly chewing something...}
{161}{}{These are Vocas nuts. They are very dense, you have to chew them hard, otherwise the effect will be small.}
{162}{}{What is the effect, exactly?}
{163}{}{These nuts remove radioactive elements from the body. Of course, this does not happen immediately. Radiation is excreted with sweat and urine during the day. The effect is not very strong, but if you use Vocas regularly, the exposure level will come back to normal... More or less.}
{164}{}{Sounds like a very useful plant. Where can I find them?}
{165}{}{You can buy nuts from me or in the "Tin angel". And if you want to collect them yourself, I suggest you wander through the uninhabited areas with a lot of dirty water. Vocas grow in rather unpleasant conditions. Just keep in mind that it ripens twice a year - in spring and fall. At those times of year there are buckets of them lying on shelves.}
{166}{}{Okay. Thank you for telling me this.}
{167}{}{Okay. Maybe you can clarify something on the subject?}

#Recipe of the nut extract
{168}{}{I think I know how to solve the problem. Fortunately, my experience of survival has saved my life quite often during travels between cities.}
{169}{}{...So, basically, you're saying that we need to produce an extract from the nuts and take it intravenously, not orally? Brilliant! Just brilliant!}
{170}{}{It seems that the nuts with the radioprotective effect are in widespread here, but people are still suffering. Why is it so?}
{171}{}{Vocas has a weak effect, especially compared to pre-war drugs. The benefits will come only when people take them by the handfuls and regularly. But even then there are limitations.}
{172}{}{What stops the regular prophylactic?}
{173}{}{Well, nuts only ripen twice a year, so regularity of application is difficult to achieve. Also, the body is not very happy with such a harsh food. I've noticed recently that the more often people eat vocas, the less beneficial this plant is. The body becomes oversaturated and a natural blockage kicks in. This is not a panacea for us, alas.}
{174}{}{I think I know how to solve this problem. Fortunately, I have plenty of scientific knowledge in chemistry.}
{175}{}{Are you serious? Oh, I'd love to chat with you over the lab table. So... What do you want to propose, colleague?}
{176}{}{My professional secrets are expensive. I will tell you for a reward of $350.}
{177}{}{I'll be very happy to share my knowledge with those who will be able to use it for the benefit of the people.}
{178}{}{Sorry, but I can't right now - I have work to do.}
{179}{}{Together with the pharmacist you have developed a drug for the prevention of radiation sickness. This will be very useful for the entire city.}

#About the current sanitary conditions
{180}{}{About the sanitary conditions in the city, can you tell me what they are now?}
{181}{}{Now it's calm. The pestilence seems to be over, but it is too early to draw final conclusions. People are less likely to get sick and suffer from intestinal infections. I hope it will continue like this.}
{182}{}{Terrible. The pestilence is all over the city. People die from intestinal diseases and there is nothing to do to help them. My supplies are meager and not everyone can afford to buy them. I don't know for how long it's going to last.}
{183}{}{Everything is just as it used to be. There are still pockets of intestinal diseases in the city, but so far there have been very few deaths.}
{184}{}{What can I say... Every city in the Wasteland has problems with healthcare. But the people manage to deal with them somehow, so most of them survive. What's happening In Salt Lake is complicated: on the one hand, the nature has given us a lot of water and a wonderful Vocas plant, on the other - we are afraid to even approach the Great Salt Lake because of the danger of intoxication and irradiation. In addition, the Nuka-Cola factory obviously adds to the problem. A complicated case.}

#Selling Niskigwan's backpack 
{185}{}{I have a set of different medicaster's accessories. Interested?}
{186}{}{Actually, I try to stick to civilized medicine. But in our time you will be glad to have any additional means. Let's see, maybe there will be something useful.}
{187}{}{Look.}
{188}{}{Yeah, some trinkets can be useful, especially that ones. It seems that the medic who used it was quite experienced. I'll give you $1000 for this bag.}
{189}{}{That's a deal then.}
{190}{}{I'm going to look for more generous customers. Goodbye.}
{191}{}{Yeah, some trinkets can be useful, especially that ones. It seems that the medic who used it was quite experienced. But now since the city has not so many problems with diseases as before, I don't have a need in these tools. So I can give you only $500 for this.}
{192}{}{[Nods and gives you the money, taking the accessories away]}

{193}{}{I think I know how to solve this problem. Fortunately, I have lots of medical experience.}
{194}{}{I think I know how to solve this problem. Fortunately, I have plenty of scientific knowledge in chemistry.}

#About the increased amount of goods when there is a good environmental situation
{195}{}{With pleasure! It's timely, as the goods started stocking up after the city got rid of the problems with diseases. So keep in mind - now coming to me you won't see an empty shelf.}
{196}{}{It's good... I mean, good for me, of course. Well, let's see what you have.}
{197}{}{Thanks to the improved ecological situation in the city, the goods in the pharmacy will be updated twice as often.}

#Manufacture of medicine
{200}{}{Do you make medicaments?}
{201}{}{I can make healing powders, antidotes, stimulants and the "blood-purifier". But I need your own components, for mine are scarce. So, what do you need?}
{202}{}{Antidote.}
{203}{}{Stimpak.}
{204}{}{"Blood-purifier".}
{205}{}{Healing powder.}

{209}{}{Let's change the subject.}
{210}{}{Nothing. Let's go back.}

{211}{}{I'll make it if you bring me the tail of a radscorpion. It will cost }
{212}{}{I'll make it if you bring me an empty syringe, a Xander root and a Broc flower. It will cost }
{213}{}{I'll make it if you bring me a Xander root, a Broc flower and two handfuls of nightshade berries. It will cost }
{214}{}{I'll make it if you bring me a Xander root and a Broc flower. It will cost }

{218}{}{Again, what can you produce?}
{219}{}{ bucks a dose.}

{220}{}{Make one dose.}
{221}{}{Make two doses.}
{222}{}{Make three doses.}
{223}{}{Make four doses.}
{224}{}{Make five doses.}
{225}{}{Make ten doses.}
{226}{}{Make as many doses as possible.}

{230}{}{[The pharmacist mockingly shakes his head as he watches at you nervously digging through your empty pockets, looking for things that aren't there]}
{231}{}{Oops...}
{232}{}{Done. Anything else?}
{233}{}{Another medicament, please.}
{234}{}{Now, let's talk, if you don't mind.}
{235}{}{That's all I needed. See you.}

#The achievement of the medicaster
{240}{}{Can you teach me how to make medicine?}
{241}{}{Alas, no. It takes at least a little bit of knowledge about the properties of medicinal herbs of the modern wasteland.}
{242}{}{A pity. I wanted to learn this skill very much...}

{243}{}{Well, I wouldn't mind a little extra income. But how do I know what you are going to use your knowledge for? What if you decide to become my competitor, or even start producing drugs? And I don't want to have any problems with the Sheriff.}
{244}{}{Well, I wouldn't mind some extra income. I am ready to trust my knowledge to such a good person as you. But I hope to get something in return, okay?}
{245}{}{I'll pay $ 1,000 for tuition.}
{246}{}{We will decide on that question another time.}

{247}{}{Since you have returned clean water to the city, I will help you with pleasure.}
{248}{}{Great. Shall we begin?}
{249}{}{Not now, I have other things to do.}

{250}{}{Hey, that's my stuff!}
{251}{}{But I acquired these things in an honest way. So if you want them, you have to pay.}
{252}{}{Grr...}

#Artesian water filter, addition
{260}{}{Thanks! Our city is saved now. But I can't let you go without a little reward. Here you go. [He gives you a superstimpak and an ultra-antidote] These are very expensive medicaments. I could sell them to the rich, but you may need them more.}
{261}{}{I won't say no to that.}

{262}{}{Do you have heart disease medicine in stock?}
{263}{}{Unfortunately, I don't. And I would not advise you to resort to it. Who knows what side effects they might have acquired in the years after the Great War? Anyway, you have to look for them in bigger, cleaner cities like Las Vegas.}
{264}{}{Understood.}

#Treatment of infection
{265}{}{I feel feverish and the cough is killing me... Is there any cure for such disease?}
{266}{}{Let me examine you... This is an infection. It can be handled quite well with nightshade berries mixed with alcohol. But that treatment is still much less effective than the properly produced medicine based on the same berries. You can buy the latter from me, it's called "Blood-purifier"... If it's still available.}
{267}{}{So let's see if you have something effective available for sale.}
{268}{}{Oh, thanks for the tip! Now when I set up a camp in the Wasteland and feel sick, there will be a chance for me to get cured on the spot, near the campfire.}
{269}{}{Pharmacist taught you to treat the infection at the campfire with wild plants and alcohol.}

#Treatment
{270}{}{I need healing.}
{271}{}{Sure. But you will have to pay.}
{272}{}{[The full treatment: }
{273}{}{[Treat wounds: }
{274}{}{[Treat intoxication: }
{275}{}{[Cure a mutilation: }
{276}{}{[Treat irradiation: }
{277}{}{That's enough for today. Let's talk.}
{278}{}{Goodbye, Doc.}
{279}{}{$]}
{280}{}{Those money won't be enough to cover the costs of the treatment.}
{281}{}{Now everything is alright.}
{282}{}{Thanks, Doc. I'll better go.}
{283}{}{[Treat the infection: }

#PLC
{290}{}{I'm doing some work for the Nuka-Cola factory. And I was told not to discuss it with you. Why?}
{291}{}{[Smiles sadly] I and various activists have had conflicts with the management of the factory. For example, because of the fact that the liquid waste from the plant makes the already ruined nature in the city even more ruinous. This problem affects everyone in Salt Lake..}
{292}{}{So that's what happening...}
{293}{}{So, what kind of work you do for the factory?}
{294}{}{I got the contract to restore the controller that allows to use automatic equipment.}
{295}{}{I can't say. Goodbye.}
{296}{}{Oh my God! I hope you are not going to carry out the contract?}
{297}{}{Why?}
{298}{}{If the factory restores the automation it will be bad for everyone, except a handful of the lead managers of the company! Now there is a lot being done manually. But if the conveyors start to work without human involvement, many workers will be kicked out on the street. In addition, it would greatly increase the factory's production rate, which will cause it to pollute the city with its waste even more.}
{299}{}{Hmm. What a strange irony - it's bad for the city without the factory, and isn't good with it either. So, what are you proposing?}
{300}{}{Give me that controller, I will destroy it. And in return I'll pay 350 bucks, I can't offer more. But you will do a good deed! And as for the factory, it won't make the situation WORSE for them.}
{301}{}{Okay then, take this device. Even if it's less money, I will save on the associated costs and would feel better doing good.}
{302}{}{Give me time to think about it.}
{303}{}{Few will sacrifice potential earnings for the well-being of not their city. Thanks.}
{304}{}{You're welcome.}

#Women's replies:
{1122}{}{About the filter for the artesian water tower. I've found it! But how to start the tower? Is there anyone I can discuss this issue with?}
{1138}{}{I visited the artesian water tower in the slums. Has anyone tried to fix it? That would give a ton of clean water for the city!}
{1160}{}{Oh, that's why on the way here I saw people constantly chewing something...}
{1177}{}{I'll be very happy to share my knowledge with those who will be able to use it for the benefit of the people.}
