{100}{}{You see a pharmacist.}
{101}{}{It's a pharmacist, though he may be a doctor... But now he is a pharmacist.}

{102}{}{It must be an interesting task if you're a doctor or a chemist... But thank you for telling me.}
{103}{}{Well, it seems the issue has been resolved. It also means that I will have something to do sitting by the campfire in my free time. Goodbye, colleague!}
{104}{}{Thief! Help!}
{105}{}{I wonder, which?}

{110}{}{I'm listening.}
{111}{}{Show me the goods.}
{112}{}{Do you need a worker for a modest fee? There is one poor guy that can't find a job.}
{113}{}{No. I can barely earn for a livelihood. Paying the workers is too much for me... Maybe the Sheriff needs someone. There are always people doing something around him.}
{114}{}{Okay.}
{115}{}{Well, I've helped as much as I could. I have nothing more to offer.}
{116}{}{One more time.}
{117}{}{Su-u-ure. Goodbye.}
{118}{}{Goodbye.}
{119}{}{Let's go back.}

#About the filter for the tower:
{120}{}{About the healthcare in the city...}
{121}{}{What do you want to talk about?}
{122}{}{About the filter for the artesian water tower. I've found it! But how to run the tower? Is there anyone I can discuss this issue with?}
{123}{}{Well. with me, of course! Because all people here come to me with a damn dysentery. I would have ensured that the tower is running.}
{124}{}{And what will you do afterwards? Sell water?}
{125}{}{If I had my way, I would give it away for free. But, in our circumstances, I will have to act differently. First, it is necessary to pay a considerable amount to the guys who will fix everything and prepare the working area. Then I need to hire guys to protect it. Maybe I can ask the Sheriff for them, we'll see. At least, I wouldn't ask to high a price, unlike the Nuka-Cola factory. For them it is just business.}
{126}{}{So, the factory is also interested in buying this filter?}
{127}{}{Well, of course! But mark my words. If the factory becomes the sole owner of clean water, it will be even worse than if there were no clean water at all!}
{128}{}{Why?}
{129}{}{The sanitary catastrophe is looming in the city. I can see that. Nobody can be sure that after going to sleep one will wake up the next day. If there is clean water in the city, the people will start gnawing through the throats of each other. There will be serious conflicts.}
{130}{}{How complicated. And how much you offer for the filter?}
{131}{}{5 thousands and a 30% discount at my pharmacy for you personally. I can't offer more.}
{132}{}{It's a deal!}
{133}{}{After listening to this heartbreaking story, I'll give the filter for free.}
{134}{}{I'll think about your offer.}
{135}{}{Thank you! It's the real salvation of our city!}
{136}{}{I understand. Goodbye.}
{137}{}{You delivered the filter for artesian water tower and significantly improved local living conditions.}

#About artesian water tower:
{138}{}{I visited the artesian water tower in the slums. Has anybody tried to fix it? It would provide a loads of clean water for the city!}
{139}{}{It would, of course. This tower has been attracting everyone's attention for a long time. Nuka-Cola factory hired some people, the Sheriff tried to find repairers and even sent couriers to search for it in other cities. But all in vain.}
{140}{}{What's the problem?}
{141}{}{Overall, the tower is in working condition. Only one thing doesn't work - the cleaning machine. A new filter is needed to fix this. But where one can be found - nobody knows. Things like this are not available in a local store. However, there were rumors that someone in Vegas has found a suitable one. But it's just a story, otherwise it would have been brought here long time ago.}
{142}{}{Hmm, a serious problem. I hope I come across such a filter.}
{143}{}{Doubtful, but if you often move around the Wasteland, ask around the cities. Better to start from Vegas.}
{144}{}{So, Vegas... I need to make a notch.}
{145}{}{You got the Las Vegas coordinates.}

#About radiation in the city
{154}{}{How can you live in such a wet and smelly climate? The visitors, perhaps, have breathing problems?}
{155}{}{That's right. One need to get used to to local conditions. But the body gradually adapts. Most importantly, do not stick your nose where it doesn't belong.}
{156}{}{And where it does not?}
{157}{}{In the North there is a large radioactive area, a real cemetery. That was the part of the Salt Lake city agglomeration on which a nuclear bomb was dropped during the war. Periodically rains wash out radioactive dirt, which flows into the Great Salt Lake. Fortunately, we were lucky with the climate.}
{158}{}{How so?}
{159}{}{Our landscape holds back any dirt. There are no harsh winds like in the deserts, and no fumes from heat. In addition, in local conditions one plant has mutated, the water lily. It grows on the banks of the Great Salt Lake. In other cities it is just a plant, but this one gives you a special kind of nutritious nuts.}
{160}{}{Oh, that's why on the way here I saw people constantly chewing something...}
{161}{}{These are Vocas nuts. They are very dense, you have to chew them hard, otherwise the effect will be small.}
{162}{}{What is the effect, exactly?}
{163}{}{These nuts remove radioactive elements from the body. Of course, this does not happen immediately. Radiation is excreted with sweat and urine during the day. The effect is not that strong, but if you use Vocas regularly, the degree of irradiation will come back to normal... More or less.}
{164}{}{Apparently, a very useful plant. How to find it?}
{165}{}{You can buy them from me or in the "Tin angel". And if you want to collect them yourself, I suggest you to wander through the uninhabited areas with a lot of dirty water. Vocas grows in rather unpleasant conditions. Just keep in mind that it ripens twice a year - in spring and in fall. At those times of the year there are buckets of them lying on shelves.}
{166}{}{Okay. Thank you for telling me.}
{167}{}{Okay. Maybe you can clarify something on the subject?}

#Recipe of the nut extract
{168}{}{I think I know how to solve this problem. Fortunately, my experience of survival in the wild has saved my life during travels between cities.}
{169}{}{...So, you're saying, we need to extract compounds from nuts and infuse them intravenously, and not orally? Brilliant! Just brilliant!}
{170}{}{It seems that the nuts with the radioprotective effect are in widespread here, but people are still suffering. Why is it so?}
{171}{}{Vocas has a weak effect, especially compared to pre-war drugs. The benefits will come only when people take them by handfuls and regularly. But even in this case there are limitations.}
{172}{}{What stops the regular prophylactic?}
{173}{}{Well, the nuts ripen only twice a year, so the regularity is difficult to achieve. In addition, the body is not very happy with such a tough food. I noticed recently, that the more often people eat Vocas, the smaller the useful effect of this plant. Organism becomes oversaturated and triggers a natural blocker. It's not a panacea, alas.}
{174}{}{I think I know how to solve this problem. Fortunately, I have plenty of scientific knowledge in chemistry.}
{175}{}{Are you serious? Oh, I'd love to chat with you over the lab table. And... What do you want to propose, colleague?}
{176}{}{My professional secrets are expensive. I will tell you for a reward of $350.}
{177}{}{I'll be very happy to share my knowledge with those who will be able to use it for the benefit of the people.}
{178}{}{Sorry, but I can't right now - I have the work to do.}
{179}{}{Together with the pharmacist you have developed a drug for the prevention of radiation sickness. This will be very useful for the entire city.}

#About the current sanitary conditions
{180}{}{About the sanitary conditions in the city. What are they now, can you tell?}
{181}{}{Now it's calm. The pestilence seems to be over, but it is too early to draw final conclusions. People are less likely to get sick and suffer from intestinal infections. I hope it will continue like this.}
{182}{}{Terrible conditions. Pestilence is in the city. People die from intestinal diseases and there is nothing to help them. My supplies are meager, and not everyone can afford to buy them. I don't know for how long will these conditions last.}
{183}{}{All as before. There are still pockets of intestinal diseases in the city, but so far very few deaths.}
{184}{}{What can I tell... Every city of the Wastelands has problems with health. But the people manage to cope somehow, and most of them survive. What's happening In Salt Lake is complicated: on the one hand, nature has given us a lot of water and a wonderful plant Vocas, on the other, we are afraid even to approach the Great Salt Lake because of the danger of intoxication and irradiation. In addition, the Nuka-Cola factory obviously adds it's own share of dirt to the problem. A complicated case.}

#Selling Niskigwan's backpack 
{185}{}{I have a set of different medicaster's accessories. Interested?}
{186}{}{Actually, I try to stick to civilized medicine. But in our time you will be glad to have any additional means. Let's see, maybe there will be something useful.}
{187}{}{Look.}
{188}{}{Yeah, some trinkets can be useful, especially this one and this one. It seems that the medic who used it was quite experienced. I'll give you $1000 for this bag.}
{189}{}{That's a deal then.}
{190}{}{I'm going to look for more generous customers. Goodbye.}
{191}{}{Yeah, some trinkets can be useful, especially this one and this one. It seems that the medic who used it, was quite experienced. But now since the city has not as much problems with diseases as before, I don't have much need in these tools. So I can give you only $500 for this.}
{192}{}{[Nods and gives you the money, taking the accessories away]}

{193}{}{I think I know how to solve this problem. Fortunately, I have lots of medical experience.}
{194}{}{I think I know how to solve this problem. Fortunately, I have plenty of scientific knowledge in chemistry.}

#About the increased amount of goods when there is a good environmental situation
{195}{}{With pleasure! It's timely, as the goods started stocking up after the city got rid of the problems with diseases. So keep in mind - now, coming to me, you won't see an empty shelf.}
{196}{}{It's good... I mean. good for me, of course. Well, let's see what you have.}
{197}{}{Thanks to the improved ecological situation in the city, the goods in the pharmacy will be updated twice as often now.}

#Manufacture of medicine
{200}{}{Do you make medicaments?}
{201}{}{I can make healing powders, antidotes, stimulants and the "blood-purifier". But I need your own components as mine are scarce. So what do you need?}
{202}{}{Antidote.}
{203}{}{Stimulator.}
{204}{}{"Blood-purifier".}
{205}{}{Healing powder.}

{209}{}{Let's change the subject.}
{210}{}{Nothing. Let's go back.}

{211}{}{I'll do if you bring me the tail of a radscorpion. It will cost }
{212}{}{I'll do if you bring me an empty Great Salt Lake, a Xander root and a Broc flower. It will cost }
{213}{}{I'll do if you bring me a Xander root, a Broc flower and two handfuls of nightshade berries. It will cost }
{214}{}{I'll do if you bring me a Xander root and a Broc flower. It will cost }

{218}{}{Again, what can you produce?}
{219}{}{ bucks a dose.}

{220}{}{Make one dose.}
{221}{}{Make two doses.}
{222}{}{Make three doses.}
{223}{}{Make four doses.}
{224}{}{Make five doses.}
{225}{}{Make ten doses.}
{226}{}{Make the as many as possible.}

{230}{}{[The pharmacist mockingly shakes his head as he watches at you nervously digging into empty pockets looking for the things that aren't there]}
{231}{}{Oops...}
{232}{}{Ready. Anything else?}
{233}{}{Another medicament, please.}
{234}{}{Now let's talk, if you don't mind.}
{235}{}{That's all I needed. See you.}

#The achievement of the medicaster
{240}{}{Can you teach me how to do medicine?}
{241}{}{Alas, no. It takes at least a little bit of knowledge about the properties of medicinal herbs of the modern Wasteland.}
{242}{}{A pity. I very much wanted to learn this skill...}

{243}{}{Well, I wouldn't mind extra income. But how would I know what are you going to use your knowledge for? At one moment you may decide to become a competitor or even to produce drugs? And I don't want to have any problems with the Sheriff.}
{244}{}{Well, I wouldn't mind extra income. For such a good person like you I am ready to trust my knowledge. But I hope to get something in return, okay?}
{245}{}{I'll pay $ 1,000 for tuition.}
{246}{}{We will decide on that question another time.}

{247}{}{Since you have returned clean water to the city, I will help you with pleasure.}
{248}{}{Great. Shall we?}
{249}{}{Not now, I have other things to do.}

{250}{}{Hey, that's my stuff!}
{251}{}{But I acquired these things in an honest way. Therefore, if you want to take this you have to pay for it.}
{252}{}{Grr...}

#Artesian water filter, addition
{260}{}{Thanks! Our city is saved now. But I can't let you go without a little reward. Here you go. [gives you a superstimpak and an ultra-antidote] These are very expensive medicaments. I could sell them to the rich, but you may need them more.}
{261}{}{I won't refuse.}

{262}{}{Do you have heart disease medicine in stock?}
{263}{}{Unfortunately, I don't. And I would not advise you to resort to such medicine. Who knows what side effects they might acquire in the years after the great War. You need to look for them in larger and cleaner cities such as Las Vegas.}
{264}{}{Understood.}

#Treatment of infection
{265}{}{I feel feverish and the cough is killing me... Is there any cure for such disease?}
{266}{}{Let me examine you... This is the infectious disease. It can be handled quite well with nightshade berries mixed with alcohol. But that treatment is still much less effective than the properly made medicine based on the same berries. You can buy the latter from me, it's called "Blood-purifier"... If it's still available.}
{267}{}{So let's see if you have something effective available for sale.}
{268}{}{Oh, thanks for the tip! When I will set up a camp in the Wasteland and feel sick, there will be a chance to get cured on the spot, near the campfire.}
{269}{}{Pharmacist taught you to treat the infection at the campfire with wild plants and alcohol.}

#Treatment
{270}{}{I need healing.}
{271}{}{Sure. But you will have to pay.}
{272}{}{[The full treatment: }
{273}{}{[Treat wounds: }
{274}{}{[Treat intoxication: }
{275}{}{[Cure a mutilation: }
{276}{}{[Treat irradiation: }
{277}{}{That's enough for today. Let's talk.}
{278}{}{Goodbye, Doc.}
{279}{}{$]}
{280}{}{Those money won't be enough to recoup the costs of the treatment.}
{281}{}{Now everything is alright.}
{282}{}{Thanks, Doc. I'll better go.}
{283}{}{[Treat the infection: }

#PLC
{290}{}{I'm doing some work for the Cola factory. And I was told not to discuss it with you. Why so?}
{291}{}{[Smiles sadly] I and various other activists had conflicts with the management of the factory in the past. Simply because the liquid wastes of the factory make the situation with already ruined nature in the city even more perilous. This issue affects all residents of the Salt Lake.}
{292}{}{So that's what happening...}
{293}{}{So what kind of work you do for the factory?}
{294}{}{I got the contract to restore the controller that allows to use automatic equipment.}
{295}{}{I can't say. Goodbye.}
{296}{}{Oh my God! I hope you are not going to carry out the contract?}
{297}{}{Why?}
{298}{}{If the factory restores the automation, it will be bad for everyone, except a handful of the lead managers of this company! Now there is a lot being done manually. But if the conveyors start to work without human involvement, a lot of the workers will be kicked out to the street. In addition, it'll greatly increase the speed of operation of the factory, which will lead to the factory polluting the city with their wastes much more.}
{299}{}{Hmm. What a strange irony - it's bad for the city without the factory, and isn't good with it either. So, what are you proposing?}
{300}{}{Give me that controller, I will destroy it. And in return I'll pay 350 bucks, I can offer no more. But you will do a good deed! And as for the factory, it won't make the situation WORSE for them.}
{301}{}{Okay then, take this device. Even if it's less money, I will save on the associated costs and would feel better doing good.}
{302}{}{Give me time to think about it.}
{303}{}{Few will sacrifice potential earnings for the well being of the alien city. Thanks.}
{304}{}{You're welcome.}

#Women's replics:
{1122}{}{About the filter for the artesian water tower. I've found it! But how to run the tower? Is there anyone I can discuss this issue with?}
{1138}{}{I visited the artesian water tower in the slums. Has anybody tried to fix it? It would provide a loads of clean water for the city!}
{1160}{}{Oh, that's why on the way here I saw people constantly chewing something...}
{1177}{}{I'll be very happy to share my knowledge with those who will be able to use it for the benefit of the people.}
