{100}{}{You see a drunkard.}
{101}{}{You see a dirty and very rude man, he definitely drinks too much alcohol.}
{102}{}{The family issue have been solved.}
{103}{}{Shit! This cretin killed his wife!}
{104}{}{What have you done?!}
{105}{}{This cretin is unredeemable. Your conversation with him only made his self-convictions stronger.}
{106}{}{You solved the family issue without blood and violence.}
{107}{}{The drunkard is so scared that he will remember this lesson for long.}
{108}{}{Mark is scared of you so much that he won't dare to be rude to his wife.}

{109}{}{ }

{110}{}{Who the hell are you?!}
{111}{}{Noooo! What have I done!?}
{112}{}{::cries hysterically::}
{113}{}{NO!!! Bitch, how could you do this to me!?}
{114}{}{Not this! How could I?!!}
{115}{}{ALL OF THIS BECAUSE OF YOU!!!}

{116}{}{Leave me alone!}
{117}{}{Well, hi, I guess...}

#Старый диалог, используется частично:
{118}{}{You're right man, we need to help each other... Maybe a glass of moonshine?}
{119}{}{You're right man. You want to freshen up with "Bloody Mary" with me?}

{120}{}{I don't get it! Who the hell are you?! And what the fuck do you want with my wife?!}

{121}{}{She just told me that it's difficult for her to communicate with you. A woman must let the pain off her chest, right?}
{122}{}{With her - nothing. But she wants you dead. Say goodbye now!}
{123}{}{Well, maybe... Bitches always complain, if they don't like something...}
{124}{}{And what's the thing you don't like?}
{125}{}{Well you're not right. You must be kind and gentle to your wife.}
{126}{}{I will wreck you for this!.. [punch him in the face]}
{127}{}{Whaaa?! Do I look like a child to you? You want to teach me about life? Why everyone hates me?! What did I do?! I just wanted to relax, have some beer, but everyone is lashing out on me! You, my wife, everyone!}
{128}{}{Strange to hear this from a man who is busy doing nothing. Bye.}
{129}{}{You ego is too big. I'm gonna cut it shorter... Together with your life!}
{130}{}{*Me*? I don't like everything! I try to explain it to her - a man has his lows, yes, doesn't have a job, yadda-yadda. And what does she say?! She's not being kind, or gentle, or feeding me something! If a man has his lows - he needs help!}
{131}{}{You're right, man, we should help each other...}
{132}{}{You're right, man, we should help each other... Want some beer?}
{133}{}{And why don't you help yourself, if you're so smart? Why someone should save you?}
{134}{}{That's what I tell her... Ahh! You won't understand.}
{135}{}{Won't understand? Hmm...}
{136}{}{[You had a heartfelt time with this cretin, using your knowledge in psychology. Something's changed in his mind. Hopefully, everything will be okay from now on.]}
{137}{}{Well, I gotta go. Take care!}
{138}{}{[You had a heartfelt time with this cretin. He poured a ton of spiritual shit into you, but after a couple of weeks he'll have even more, no doubt...]}

#Новый диалог:
{150}{}{We just know each other, don't pay any attention.}
{151}{}{I'm her consciousness. I let her cry into my shoulder, when the need comes.}
{152}{}{I... Er... Your new neighbor, wanted to say hi.}
{153}{}{From her - nothing. She wants you dead. Say goodbye!}

{154}{}{Who do you take me for?! *I* - am the man in this house! If you want to talk to my wife - first you ask my permission!}
{155}{}{Is she your property? Is that what you're saying?}
{156}{}{Here I am, in front of you. Calm down, man.}
{157}{}{You scum! Don't you dare treat her like this!}
{158}{}{Why is that? [makes silly sarcastic face] Oooh! Will you beat me up for this?}
{159}{}{Do not get so upset, we can solve this peacefully!}
{160}{}{Yes, it will be one more enemy in your life. Is this what you want?}
{161}{}{That's right, and you will believe it very soon!}

{162}{}{You're just a piece of shit! Piss off!}
{163}{}{Hey, easy!}
{164}{}{How dare you! Take this, you fuck!}
{165}{}{[Looks at you with stoned look, opening his mouth] To insult me in my own house! You are such a bitch!}
{166}{}{[Grab his arm pin it behind him]}
{167}{}{Hey! Hey! Take it easy! I didn't do anything!}
{168}{}{A minute ago you was such a tough man. What happened?}
{169}{}{What the hell do you want from me!?}
{170}{}{Do not pretend to be a fool, filth! Your wife can't stand you!}
{171}{}{Nothing. Dry, you drunk.}
{172}{}{This is *my* wife! Who the fuck are you to...}
{173}{}{Shut up and listen to me!}
{174}{}{You're right. She's your wife, I won't get between you.}
{175}{}{Ugh...}
{176}{}{If I'll see that you hit your wife one more time - it will be the last day of your life!}
{177}{}{Okay, okay, I get it... I... I'll restrain myself, no problem!}
{178}{}{We'll see, I'll check on your miserable family.}
{179}{}{I get it, okay!}
{180}{}{Good. Now get sober, you drunk!}
{181}{}{Do you know how many people I've killed while wandering the wastes?}
{182}{}{[It seems this drunk is getting sober!] Er... }
{183}{}{?}
{184}{}{. And you can become }
{185}{}{-th.}
{186}{}{Wha... No! Noo! Why!? Why!?}
{187}{}{Do not pretend to be a fool, you know why.}
{188}{}{Let's stop here. The hands are already reaching for the gun!}
{189}{}{Just because I want to. And now - piss off.}

{190}{}{Just like that? Kill a man, because he let some steam off!?}
{191}{}{Shut up, scum! There is not a single city were things like this are forgiven.}
{192}{}{[Swallows] Am I really that low? That's why she hired you - to finish me? }
{193}{}{I'm doing this out of my good will.}
{194}{}{That's right, she paid a decent amount of money.}
{195}{}{To be honest, she gave me poison, but I decided you don't deserve that.}
{196}{}{That's enough! You have the right for the last word! After which you die!}

{197}{}{Hell NO! I do not want to die! [Falls to his knees] Forgive me! Sorry! I realized my mistakes! I will behave! I swear! Just give me one more chance! A-ah!!!}
{198}{}{You don't deserve a second chance. You should have thought about it earlier. Now - die!}
{199}{}{Well, okay. You will get your second chance. And it will be the last.}
{200}{}{I will change! I swear!!!}
{201}{}{I'll check that. Now get dry, drunk.}
{202}{}{I am a MAN! A man, not a rag!}
{203}{}{Okay, okay, macho, calm down!}
{204}{}{A real man shouldn't beat women.}
{205}{}{Now let's see what a man you are! Come out to fight, scum!}
{206}{}{I am a MAN! A man, not a rag! This is my house! And you?! Who are YOU in my house?}

{207}{}{Sure, here's a bottle of Rotgut.}
{208}{}{Sure, here's a bottle of "Bloody Mary".}
{209}{}{Sure, here's a bottle of beer.}

{210}{}{Oh, these bitches are always dropping tears. It's already pissing me off! Hey, you, come here, bitch! I want to eat! And I don't care there is nothing to eat!..}
{211}{}{Ah! Neighbors are good. Hey, idiot! Bring something to eat, we have guests! What? Oh, you whore, I said BRING FOOD! And some booze.}
{212}{}{Forget it pal, I have some on me. Bottoms up, yes?}
{213}{}{Ohh!!! My kind of guy! You should've started with this! Don't pay any attention to this bitch, let her cry... Well, what was it? A drink, huh?}
{214}{}{[Pour poisoned moonshine]}
{215}{}{Of course, here's a bottle of moonshine.}
{216}{}{Leave it, I will not drink with such a boor. I'm leaving.}
{217}{}{Oh, hell, I'm sorry, I need to go! Bye!}

{218}{}{Ha! We need neighbors like you. Always welcome, so to speak.}
{219}{}{[Next]}
{220}{}{[Drinks a glass of moonshine] Urgh! Good, damn!.. Hey, neighbor, why do you not drinking? That's not right! Come on, for my health!}
{221}{}{Aha! For your health, neighbor!}
{222}{}{Ugghh! Oh, that's was good one! You have a decent moonshine, neighbor... Why don't you drink? I don't get it.}
{223}{}{Weak kidneys.}
{224}{}{Ahh... I even sweat a little! You know, when I worked in the police, me and my partner were on a lead on a whorehouse once. Well, you know, we had to get drug dealers trust, so we took a few doses... Uh...}
{225}{}{What is it?}
{226}{}{My partner had the bad stuff... He died after two days. Nobody could save him. And I... [cries]}
{227}{}{My friend, it seems you two were close?}
{228}{}{We were almost like *brothers*! I still can't forget... Damn, give me another one! Drink with me this time, okay? At least a couple of sips.}
{229}{}{Yeah, er, sure.}
{230}{}{[Drinks] Ughrr! Oh, it's so hot in here... Where did you get that stuff? Is this from Harry the Pigrat?}
{231}{}{Err, no, it's from a bar.}
{232}{}{[Grabs the edge of the table and falls on his knee] Ohhhh... Got me good... [laughs] Even with Russian vodka it's not like that! Oh... What did you gave me?}
{233}{}{...Uh, so what was it about Harry the Pigrat?}
{234}{}{...Lives nearby, makes moonshine and sells it at the bar... [crawls on the floor tries to lay down] Listen... Sit here, while I... Uhh... Tell me... About yourself...}
{235}{}{About me? You know, that doesn't matter.}
{236}{}{Why?..}
{237}{}{You sleep, just sleep, and when you wake up - I'll tell you everything.}
{238}{}{...About yourself?}
{239}{}{About myself, about wandering around the wastes - I'll tell you about everything. Do not worry, sleep.}
{240}{}{...You... Promise... You don't... Try to mess with... Me...}
{241}{}{[Keep silent]}
{242}{}{So... I... Want... To hear it...}
{243}{}{[This was his last breath]}

{244}{}{You acted low, poisoning this drunkard, but all the better for the world.}
{245}{}{Why do you treat her like she's your property?}

#Female character
{1104}{}{What have you done?!}
{1152}{}{I... Err... Your new neighbor, wanted to say hi.}
{1172}{}{This is *my* wife! Who the fuck are you to...}
{1181}{}{Do you know how many people I've killed while wandering the wastes?}
{1195}{}{To be honest, she gave me poison, but I decided you don't deserve that.}
{1206}{}{I am a MAN! A man, not a rag! This is my house! And you?! Who are YOU in my house?}
{1220}{}{[Drinks a glass of moonshine] Urgh! Good, damn!.. Hey, neighbor, why do you not drinking? That's not right! Come on, for my health!}
{1222}{}{Ugghh! Oh, that's was good one! You have a decent moonshine, neighbor... Why don't you drink? I don't get it.}
{1232}{}{[Grabs the edge of the table and falls on his knee] Ohhhh... Got me good... [laughs] Even with Russian vodka it's not like that! Oh... What did you gave me?}