{100}{}{You see a citizen.}
{101}{}{Before you is a middle-aged woman. She seems to have been crying all day.}
{102}{}{ }

#Ïîñëå óáèéñòâà ìóæà
{110}{}{::sighs heavily::}
{111}{}{Thank you for saving me from this...}
{112}{}{Get out!}

#Äèàëîã ñ ìóæåì
{150}{}{Stop shouting at me!}
{151}{}{You bitch! You don't even try to listen!!!}
{152}{}{Why should I listen to you?! I've heard that before...}
{153}{}{I don't care what you heard! Are you going to listen to me or not?!}
{154}{}{No, I'm not!}
{155}{}{Why?! Why do I have to humiliate myself in front of my wife?!}
{156}{}{You humiliate yourself?! No, you humiliate your wife!}
{157}{}{You bitch! Why do you hate me?! What did I ever do to you?!}
{158}{}{You yell at me every day without a break!}
{159}{}{Bitch... You bitch...}
{160}{}{During *each* of your drinking celebrations! How much longer?!}
{161}{}{Yes, I'm drunk! So?! Does it mean I can be treated this way?!}
{162}{}{Nobody is treating you "this way"! Stop it!}
{163}{}{Yes you do! Instead of love and care I get this...}
{164}{}{How can I take care of you when you beat and insult me?!}
{165}{}{YOU WHORE!!! I'll kill you someday!}
{166}{}{And you'll burn in hell for it. Where you belong.}
{167}{}{Me?! In hell?! Bitch! I do so much for you!...}
{168}{}{What do you do?! Don't flatter yourself...}
{169}{}{Who took out the trash yesterday? Why it's ME who has to take out the trash?}
{170}{}{Yeah, don't work yourself too hard, poor thing...}
{171}{}{What?! You whore, I said it already! I WILL get a job!}
{172}{}{Well, when you do, come and brag about it. But for now, this household rests on my shoulders.}
{173}{}{What are you even talking about, you stupid?! You only crap around the house, while I repair and fix everything!}
{174}{}{I see you appreciate my work very much, don't you?}
{175}{}{Why don't you appreciate mine, huh?!}
{176}{}{What *yours*? What have you done in the last year?}
{177}{}{If not for me!...}
{178}{}{"Me, me, me", all the time. Nothing else...}
{179}{}{YOU BITCH!!! YOU WHORE!!! I'LL KILL YOU!!!}

#Äèàëîã ñ íåé
{200}{}{[The woman is in tears] Why are you here?}
{201}{}{Why are you crying?}
{202}{}{Don't be so upset, it's going to be okay!}
{203}{}{I just want to make fun of a crying chick.}
{204}{}{Uh, not my business, I'm leaving.}

{205}{}{Leave, before I call my husband!}
{206}{}{Is he really going to protect you?}
{207}{}{Go on, bitch, call your prick!}
{208}{}{Okay, okay, I'm leaving.}

{209}{}{Don't provoke me! Merck is very dangerous, especially when drunk. And now he is drunk.}
{210}{}{Drunk and dangerous? Woman, this makes no sense.}
{211}{}{Whatever! Ill go make fun of him.}

{212}{}{You just can't help yourself, can you? Merck will be glad to punch your face, believe me!}
{213}{}{No, I just want to know, would he really protect you?}
{214}{}{I just want to know why are you crying.}
{215}{}{Fine, I won't bother you.}
{216}{}{Oh yes! Trouble, here I come!}

{217}{}{Yes. What a paradox. Men...}
{218}{}{Who made you cry?}
{219}{}{Then everything is okay, right?}

{220}{}{Aren't you're an optimist? Unfortunately, that doesn't help anyone nowadays...}
{221}{}{It will this time!}
{222}{}{Why are you crying then?}
{223}{}{Does that mean you cry for no reason? You are so dumb!}
{224}{}{Maybe we have nothing to talk about.}

{225}{}{I don't think so.}
{226}{}{Then at least tell me who upset you?}
{227}{}{Ha, you cry without reason? You are so dumb!}
{228}{}{Well, I won't bother you anymore then.}
{229}{}{Do not defraud the male right of primacy, bitch!}

{230}{}{It's Merck. He's always yelling at me. That bastard... I've done so much for him... And he... All he thinks about is himself! All "me" and "me" all the time...}
{231}{}{And you, of course, give him a reason to yell at you?}
{232}{}{Why does he do this?}
{233}{}{Is he always so aggressive?}
{234}{}{You are so dumb! Tears won't help you!}
{235}{}{Have you tried to ask for help?}
{236}{}{Okay, I don't want to listen to you anymore.}
{237}{}{}
{238}{}{[After your next insult, the woman falls into tears; She won't speak to you anymore.]}
{239}{}{Dumb idiot, this will not help you!}

{240}{}{Why you...}
{241}{}{Yes, sure... Have a nice day.}
{242}{}{Take care.}
{243}{}{Yes, I know. I hope you are done with the questions.}
{244}{}{Yes, it's nice to see a woman crying and realize that I have nothing to do with it.}
{245}{}{Yes, sure, sorry.}

{250}{}{Obviously, you're not the kind of person who spends a lot of time with drunks. People like Merck don't need a reason - they just find one. It doesn't matter what I do.}
{251}{}{A typical guy with big balls. And he wants everyone to know it. He thinks he's a master and a big man. When in fact he can't even fix the closet door.}
{252}{}{No, only when he's drunk. And that happens almost every day. When he's sober, it's even pleasant to talk to him. He can make jokes and say some kind words...}
{253}{}{Who in this town will help a person in need? The Sheriff doesn't want to get involved in family affairs, and the neighbors don't want to make enemies. Besides, what can they do? Take a gun and shoot him in the head? That's extreme. And dangerous.}
{254}{}{I'll help you then!}

{255}{}{Why? Why do you want to get involved?}
{256}{}{I want to make a profit out of it.}
{257}{}{I just want to help - I can't stand women's tears.}
{258}{}{You need help, don't you? Why do you care about my motives?}
{259}{}{What am I even saying! I can't help you. Sorry.}
{260}{}{If I'd known any mercenary, I would have hired him already.}
{261}{}{How noble of you. Unfortunately, I lost trust in strangers a long time ago.}
{262}{}{Hmm, you know... Okay.}
{263}{}{Do you have any idea what to do?}
{264}{}{Maybe, but I don't want to help you anymore. Bye.}
{265}{}{How noble of you. I hope you have the heart for it.}
{266}{}{Don't worry! Do you have any idea what to do?}
{267}{}{An idea? I was hoping you'd come up with one yourself. All right... I have a bottle of poisoned moonshine. But I can't do it. Besides, he might see through it, because I've never given him such a drink.}
{268}{}{Give me that.}
{269}{}{Something else?}
{270}{}{Forget it, I'll figure it out myself.}
{271}{}{Okay, good luck.}
{272}{}{[Exit]}
{273}{}{Well, the local police are unlikely to interfere in our family's affairs. If it comes to a fight, you don't need to worry about them. Just so you'd know.}
{274}{}{[She pulls out a bottle from a hidden stash] Here. By the way, the local police are unlikely to interfere in our family's affairs. If it comes to a fight, you don't need to worry about them. Just so you'd know.}
{275}{}{[She pulls out a bottle from a hidden stash] Here. I hope you have the guts to do it.}
{276}{}{You know, clean this shit yourself! I'm out of here!}
{277}{}{I do not need anything, I'll deal with it as I see fit.}
{278}{}{That's enough. I'll figure it out myself.}
{279}{}{I'll figure it out myself.}

#Female character
{1220}{}{Aren't you're an optimist? Unfortunately, that doesn't help anyone nowadays...}
{1244}{}{Yes, it's nice to see a woman crying and realize that I have nothing to do with it.}
{1278}{}{That's enough. I'll figure it out myself.}
