{100}{}{You see a citizen.}
{101}{}{Before you is a middle-aged woman, it seems she cried all day.}
{102}{}{ }

#После убийства мужа
{110}{}{::sighs heavily::}
{111}{}{Thank you for saving me from this scourge...}
{112}{}{Get out!}

#Диалог с мужем
{150}{}{Stop shouting at me!}
{151}{}{Bitch! You don't even want to listen!!!}
{152}{}{Why should I listen to something?! I already heard you before...}
{153}{}{I don't care what you heard! Can you listen to me again or not?!}
{154}{}{No, I can't!}
{155}{}{Why?! Why I must humiliate myself in front of my wife?!}
{156}{}{You, humiliating yourself?! No, you humiliate your wife!}
{157}{}{Bitch! Why do you hate me?! What I've done?!}
{158}{}{You give me a headache every day and don't let me rest!}
{159}{}{Bitch... Bitch...}
{160}{}{During your *every* drinking festival! How many times?!}
{161}{}{Yes, yes, I'm a drunk! And what?! Does that mean I can be treated like this?!}
{162}{}{Nobody is treating you wrong! Enough of this!}
{163}{}{Yes you do! Instead of love and care I get this...}
{164}{}{How can I take care of you, when you beat and insult me?!}
{165}{}{WHORE!!! I'll kill you someday!}
{166}{}{And you'll burn in hell. Where you belong.}
{167}{}{Me?! In hell?! Bitch! I did so much!..}
{168}{}{What did you do?! Don't flatter yourself...}
{169}{}{And who took out the garbage yesterday? Why I should take the trash out?}
{170}{}{Yeah, don't work yourself too hard, poor thing...}
{171}{}{What?! Whore, I *will* work!}
{172}{}{Well when you'll work, come and cry about it, for now the house is on my shoulders.}
{173}{}{And what have you done, idiot?! You only do crap around the house, while I repair and fix everything!}
{174}{}{I can see you really appreciate my work, do you?}
{175}{}{Why don't you appreciate mine, huh?!}
{176}{}{What *yours*? What have you done in the last year?}
{177}{}{If not for me!..}
{178}{}{Only "me, me, me". I don't hear anything else from you...}
{179}{}{BITCH!!! WHORE!!! I'LL KILL YOU!!!}

#Диалог с ней
{200}{}{[The woman is all in tears] Why are you here?}
{201}{}{Why are you crying?}
{202}{}{Don't be so upset, it's going to be okay!}
{203}{}{I just want to make fun of a crying chick.}
{204}{}{Uh, not my business, I'm leaving.}

{205}{}{Leave, before I call my husband!}
{206}{}{Is he really going to protect you?}
{207}{}{Go on, bitch, call for your prick!}
{208}{}{Okay, okay, I'm leaving.}

{209}{}{Don't push me! Merck is very dangerous, especially when drunk. And he is drunk.}
{210}{}{Drunk and dangerous? Woman, this makes no sense.}
{211}{}{Whatever! Ill go make fun of him.}

{212}{}{You just can't help it, do you? Merck will be glad to fight, believe me!}
{213}{}{No, I just want to understand, will he really protect you?}
{214}{}{I just want to know, why you cry.}
{215}{}{Fine, I won't bother you.}
{216}{}{Oh yes! Trouble, here I come!}

{217}{}{Yes. A paradox. Men...}
{218}{}{Who made you cry?}
{219}{}{Then everything is okay, right?}

{220}{}{And you are an optimist, you know? Unfortunately, this hasn't saved anyone in our world...}
{221}{}{It will this time!}
{222}{}{Why are you crying then?}
{223}{}{Means, you cry without reason? Idiot!}
{224}{}{Perhaps, we have nothing to talk about.}

{225}{}{I don't think so.}
{226}{}{Then tell me at least, who upset you?}
{227}{}{Ha, you cry without reason? Idiot!}
{228}{}{Well, I won't bother you anymore then.}
{229}{}{Do not defraud the male right of primacy, bitch!}

{230}{}{It's Merck. He's always yelling at me. That bastard... Did so much for him... And he... Only thinks about himself! All "me" and "me"...}
{231}{}{And you, of course, give him a reason to yell on you?}
{232}{}{Why he does this?}
{233}{}{Is he always so aggressive?}
{234}{}{You idiot, tears won't help you!}
{235}{}{Haven't you tried to call for help?}
{236}{}{Perhaps I do not want to listen to this anymore.}
{237}{}{}
{238}{}{[After your next insult, the woman fell into tears; She will not speak to you any more]}
{239}{}{Dumb idiot, this will not help you!}

{240}{}{Why you...}
{241}{}{Yes, sure... Have a nice day.}
{242}{}{Take care.}
{243}{}{Yes, I know. I hope, you are finished with questions?}
{244}{}{Yeah, it's nice to see a tear-stained woman and understand that it's not me!}
{245}{}{Yes, sure, sorry.}

{250}{}{It's immediately evident that you are not a fun of drunks. Such men as Merck don't need a reason - they find it themselves, if they want. No matter how I behave - it does not matter.}
{251}{}{A typical guy with big balls. And he wants everyone to know this. Thinks of himself a master and the big man. Although in fact, can't even repair a door at the closet.}
{252}{}{No, only when he's drunk. And this happens almost every day. When he is sober, he is even pleasant to talk with, he can joke and say a few nice words...}
{253}{}{Who in this town will help a person in need? The Sheriff does not want to interfere with family problems, and neighbors and acquaintances do not want to make enemies. And what can they do? Come with a gun and shoot him in the head? It's cruel and dangerous.}
{254}{}{I'll help you then!}

{255}{}{Why! Why do you need these problems?}
{256}{}{I'm looking to benefit from this.}
{257}{}{I just want to help - I do not tolerate women's tears.}
{258}{}{You need help, don't you? Why do you care about my motives?}
{259}{}{What am I saying! can't help. Sorry.}
{260}{}{If I had a mercenary, I would have hired him long time ago.}
{261}{}{How noble of you. To my regret, I have long lost trust in strangers.}
{262}{}{Hmm, and you know - you're right!}
{263}{}{Do you have any plan?}
{264}{}{Maybe, but I don't want to help you anymore. Bye.}
{265}{}{How noble of you. I hope you have enough heart for it.}
{266}{}{Don't worry! Do you have any plan?}
{267}{}{Plan? And I hoped that you will come up with it yourself. Okay. I have a bottle of poisoned moonshine. But I don't have the heart to do it. Besides, he might suspect me, because I never gave him a drink like that.}
{268}{}{Give me that poison.}
{269}{}{Something else?}
{270}{}{No need, I'll figure out the rest myself.}
{271}{}{Okay, good luck.}
{272}{}{[Exit]}
{273}{}{Well, the local police are unlikely to interfere with our family, if it comes to a fight don't worry you know? Just so you know.}
{274}{}{[Takes out a bottle from a secret place] Here. By the way, the local police are unlikely to interfere with our family, if it comes to a fight don't worry you know? Just so you know.}
{275}{}{[Takes out a bottle from a secret place] Here. I hope, you'll do what you must.}
{276}{}{You know, shovel this shit yourself! I pass!}
{277}{}{I do not need anything else, I'll go further with my own methods.}
{278}{}{That's enough. I'll figure out the rest myself.}
{279}{}{I'll figure out the rest myself.}

#Female character
{1220}{}{And you are an optimist, you know? Unfortunately, this hasn't saved anyone in our world...}
{1244}{}{Yeah, it's nice to see a tear-stained woman and understand that it's not me!}
{1278}{}{That's enough. I'll figure out the rest myself.}
