{100}{}{You see a drunkard.}
{101}{}{You see a dirty and very rude man, he definitely drinks too much alcohol.}
{102}{}{The family issue have been solved.}
{103}{}{Shit! This cretin killed his wife!}
{104}{}{What have you done?!}
{105}{}{This cretin is unredeemable. Your conversation with him only reinforced his beliefs.}
{106}{}{You solved the family issue without blood and violence.}
{107}{}{The drunkard is so scared that he will remember this lesson for long.}
{108}{}{Merck is scared of you so much that he won't dare to be rude to his wife.}

{109}{}{ }

{110}{}{Who the hell are you?!}
{111}{}{Noooo! What have I done!?}
{112}{}{::cries hysterically::}
{113}{}{NO!!! Bitch, how could you do this to me!?}
{114}{}{Not this! How could I?!!}
{115}{}{ALL OF THIS BECAUSE OF YOU!!!}

{116}{}{Leave me alone!}
{117}{}{Well, hi, I guess...}

#Старый диалог, используется частично:
{118}{}{You're right man, we need to help each other... Want a glass of moonshine?}
{119}{}{You're right man. You want to share a "Bloody Mary" with me?}

{120}{}{I don't get it! Who the hell are you?! And what the fuck do you want from my wife?!}

{121}{}{She just told me that it's difficult for her to communicate with you. A woman has to vent, right?}
{122}{}{With her - nothing. But she wants you dead. Say goodbye now!}
{123}{}{Well, maybe... Bitches always complain when they don't like something...}
{124}{}{So, what's wrong about it?}
{125}{}{You're wrong. You must be kinded and gentler to your wife.}
{126}{}{I will wreck you for this!... [punch him in the face]}
{127}{}{Whaaa?! Do I look like a child to you? You want to teach me about life? Why everyone hates me?! What did I do?! I just wanted to relax, have some beer, but everyone is lashing out on me! You, my wife, everyone!}
{128}{}{Strange to hear this from a man who is busy doing nothing. Bye.}
{129}{}{You ego is too big. I'm gonna cut it shorter... Together with your life!}
{130}{}{Everything! I try to explain it to her - a man has his lows, yes, doesn't have a job, yadda-yadda. And what does she do?! She doesn't want to cuddle me, warm me up, give me something to eat! After all, if a man is in trouble, he needs help!}
{131}{}{You're right, man, we should help each other...}
{132}{}{You're right, man, we should help each other... Want some beer?}
{133}{}{So why don't you help yourself, if you're so smart? Why someone should help you?}
{134}{}{That's what I tell her... Ahh! You won't understand.}
{135}{}{Won't understand? Hmm...}
{136}{}{[You had a heartfelt time with this cretin, using your knowledge in psychology. Something's changed in his mind. Hopefully, everything will be okay from now on.]}
{137}{}{Well, I gotta go. Take care!}
{138}{}{[You had a heartfelt time with this cretin. He poured a ton of spiritual shit into you, but after a couple of weeks he'll have even more of it, no doubt...]}

#Новый диалог:
{150}{}{We just know each other from before, don't pay any attention.}
{151}{}{I'm her consciousness. I let her cry on my shoulder when she has the need.}
{152}{}{I... Er... Your new neighbor, I just wanted to say hi.}
{153}{}{From her - nothing. She wants you dead. Say goodbye!}

{154}{}{Who do you take me for?! *I* am the man in this house! If you want to talk to my wife, ask my permission first!}
{155}{}{Is she your property? Is that what you're saying?}
{156}{}{Here I am, in front of you. Calm down, man.}
{157}{}{You scum! Don't you dare to treat her like this!}
{158}{}{Why is that? [He makes silly face] Oooh! Will you beat me up for this?}
{159}{}{Do not get so upset, we can solve this peacefully!}
{160}{}{Yes, you'll get one more enemy. Is that what you want?}
{161}{}{That's right, and you're going to get it right now!}

{162}{}{You're just a piece of shit! Piss off!}
{163}{}{Hey, easy!}
{164}{}{How dare you! Take this, you fuck!}
{165}{}{[Looks at you with stoned look, opening his mouth] To insult me in my own house! What an asshole you are!}
{166}{}{[Grab his arm and pin it behind him]}
{167}{}{Hey! Hey! Take it easy! I didn't do anything!}
{168}{}{A minute ago you were acting so tough. What happened?}
{169}{}{What the hell do you want from me!?}
{170}{}{Do not pretend to be a fool, you filth! Your wife can't stand you!}
{171}{}{Nothing. Get sober, you fucking drunkard.}
{172}{}{This is *my* wife! Who the fuck are you to...}
{173}{}{Shut up and listen to me!}
{174}{}{You're right. She's your wife, I won't get between you.}
{175}{}{Ugh...}
{176}{}{If I'll see you hitting your wife one more time, it will be the last day of your life!}
{177}{}{Okay, okay, I get it... I... I get it! No problem!}
{178}{}{We'll see, I'll be checking on your miserable family.}
{179}{}{I get it, okay!}
{180}{}{Good. Now get sober, you fucking drunkard!}
{181}{}{Do you know how many people I've killed while wandering the wastes?}
{182}{}{[It seems this drunk is getting sober] Er... }
{183}{}{?}
{184}{}{. And you can become }
{185}{}{-th.}
{186}{}{Wha... No! Noo! Why!? Why!?}
{187}{}{Do not pretend to be a fool, you know why.}
{188}{}{You'd better stop. My hands are already itching.}
{189}{}{Just because I want to. And now - piss off.}

{190}{}{Just like that? You'd kill a man because he vented some steam off!?}
{191}{}{Shut up, scum! I don't know a single city were things like this are forgiven.}
{192}{}{[Gulps] Am I really that bad? That's why she hired you? To finish me off? }
{193}{}{I'm doing this out of my good will.}
{194}{}{That's right, she paid a decent amount of money.}
{195}{}{To be honest, she gave me the poison, but I decided you don't deserve that.}
{196}{}{That's enough! You have the right for the last word! After which you die!}

{197}{}{Hell NO! I do not want to die! [Falls to his knees] Forgive me! I'm sorry! I realized my mistakes! I will behave! I swear! Just give me one more chance! A-ah!!!}
{198}{}{You don't deserve a second chance. You should have thought about it earlier. Now die!}
{199}{}{Okay. You get your second chance. But it will also be the last.}
{200}{}{I will change! I swear!!!}
{201}{}{I'll check that. Now get sober, you fucking drunkard.}
{202}{}{I am a MAN! A man, not a rag!}
{203}{}{Okay, okay, macho, calm down!}
{204}{}{A real man shouldn't beat women.}
{205}{}{Now let's see what a man you are! Come out and fight, scum!}
{206}{}{I am a MAN! A man, not a rag! This is my house! And you?! Who are YOU?}

{207}{}{Sure, here's a bottle of Rotgut.}
{208}{}{Sure, here's a bottle of "Bloody Mary".}
{209}{}{Sure, here's a bottle of beer.}

{210}{}{Oh, these bitches are always dropping tears. It always pisses me off! Hey, you, come here, bitch! Get me food! And I don't care that we don't have anything!...}
{211}{}{Ah! Neighbors are good. Hey, idiot! Get me food, we have guests! What? You whore, I said GET ME FOOD! And some booze.}
{212}{}{Forget it pal, I have some on me. Bottoms up, yes?}
{213}{}{Ohh!!! My kind of guy! You should've started with this! Don't mind that bitch, let her cry... Where were we? Right! A drink right?}
{214}{}{[Pour poisoned moonshine]}
{215}{}{Of course, here's a bottle of moonshine.}
{216}{}{Leave it, I'm not drinking with such a boor. I'm leaving.}
{217}{}{Oh, I'm sorry, I need to go! Bye!}

{218}{}{Ha! We need neighbors like you. Always welcome, so to speak.}
{219}{}{[Next]}
{220}{}{[Drinks the glass of moonshine] Urgh! Goddamn!... Hey, neighbor, why aren't you drinking? You can't do that! Come on, here! Cheers!}
{221}{}{Right! Cheers, neighbor!}
{222}{}{Ugghh! Oh, that's was good one! You have a decent moonshine, neighbor... why aren't you drinking? I don't get it.}
{223}{}{Weak kidneys.}
{224}{}{Ahh... I even broke a little sweat! You know, when I was on the force, my partner and I once got a tip on a brothel. You know, we had to gain the trust of the drug dealers, so we took a few doses.... Uh...}
{225}{}{What is it?}
{226}{}{My partner had the bad stuff... He died after two days. Nobody could save him. And I... [cries]}
{227}{}{My friend, it seems you two were close?}
{228}{}{We were almost like *brothers*! I still can't... Damn, give me another one! Drink with me this time, okay? At least a couple of sips.}
{229}{}{Yeah, er, sure.}
{230}{}{[Drinks] Ughrr! Oh, it's so hot in here... Where did you get that stuff? Is this from Harry the Pigrat?}
{231}{}{Err, no, it's from a bar.}
{232}{}{[Grabs the edge of the table and falls on his knee] Ohhhh... Got me good... [laughs] Even Russian vodka it's not like that! Oh... What did you gave me?}
{233}{}{...Uh, so what was it about Harry the Pigrat?}
{234}{}{...He lives nearby, makes moonshine and sells it at the bar... [crawls on the floor tries to lay down] Listen... Sit here, while I... Uhh... Tell me... About yourself...}
{235}{}{About me? You know, that doesn't matter.}
{236}{}{Why?..}
{237}{}{Sleep, just sleep. When you wake up, I'll tell you everything.}
{238}{}{...About yourself?}
{239}{}{About myself, about wandering around the wastes - I'll tell you everything. Do not worry, sleep.}
{240}{}{...You... Promise... You're not... Messing with... Me...}
{241}{}{[Keep silent]}
{242}{}{So... I... Want... To hear it...}
{243}{}{[This was his last breath]}

{244}{}{You acted low, poisoning this drunkard. But it's all for the better.}
{245}{}{Why do you treat her like she's your property?}

#Female character
{1104}{}{What have you done?!}
{1152}{}{I... Err... Your new neighbor. Just wanted to say hi.}
{1172}{}{This is *my* wife! Who the fuck are you to...}
{1181}{}{Do you know how many people I've killed while wandering the wastes?}
{1195}{}{To be honest, she gave me the poison, but I decided you don't deserve that.}
{1206}{}{I am a MAN! A man, not a rag! This is my house! And you?! Who are YOU?}
{1220}{}{[Drinks the glass of moonshine] Urgh! Goddamn!... Hey, neighbor, why aren't you drinking? You can't do that! Come on, here! Cheers!}
{1222}{}{Ugghh! Oh, that's was good one! You have a decent moonshine, neighbor... why aren't you drinking? I don't get it.}
{1232}{}{[Grabs the edge of the table and falls on his knee] Ohhhh... Got me good... [laughs] Even Russian vodka it's not like that! Oh... What did you gave me?}
