{100}{}{You see a machinist.}
{101}{}{It is your partner that you hired to accompany you to the train as the driver.}
{102}{}{You are left without a driver. You have to look for a replacement.}

#Диалог
{110}{}{Hello. I can go anytime, just tell me when, okay? And, you know, the locals got a little wary when I started talking about trains. Something scares them. None of my business, of course, I'm just warning you.}
{111}{}{I'll be careful, thank you. We should hit the road. Pack your things and go to the station.}
{112}{}{Don't worry, I will deal with everything, you just wait here.}

{113}{}{At last! I'm tired to hang around this crummy diner. But we had a deal - I work for you as long as you pay.}
{114}{}{I know the deal. We agreed on 1000$. Here is the money. Now go to the station.}

{115}{}{How's it going with the train? All set? I can go anytime, just let me know.}
{116}{}{I was just gonna say it. Get ready and go to the station.}
{117}{}{Not all preparations are completed. Wait here until I'm finished.}

{118}{}{I think we agreed on 1000$. Wait a little while I will bring the money.}

#Если персонаж был куплен у работорговцев в Вегасе:
{210}{}{Hello, master. I can go anytime, just tell me when.  And the locals got a little wary when I started talking about trains. Something scares them. None of my business, of course, I'm just warning you.}
{213}{}{Whatever you say, master!}
{214}{}{You're a pretty good slave. Go to the station.}
{215}{}{Should I go to the station? Anytime, master. Just say the word.}
{216}{}{I was just going to. Get ready and go to the station.}
{217}{}{Not all preparations are completed. Wait here until I'm finished.}

{218}{}{Wait, I have something else to do. Wait here.}
