{100}{}{You see the Manager.}
{101}{}{You see the hotel Manager. He's busy with blowing the dust off his suit.}
{102}{}{Put the gun down, then we'll talk.}

#Starting replicas
{109}{}{What?}
{110}{}{Want to book a room?}
{111}{}{Yes? What do you want?}

{112}{}{Let's chat, I'm interested in the situation in the city. What's the news?}
{113}{}{Tell me about the city. What's there and where one can go to hang out?}
{114}{}{It's quite boring in here. No music, no magazines.}
{115}{}{I need a room to rest. How much is it?}
{116}{}{Continue.}
{117}{}{I don't want anything, I'll go.}
{118}{}{One more question, if I may...}
{119}{}{All right, thanks.}

#About the hotel and the city:
{120}{}{Well, what can I tell... [Relaxes himself in the chair crossing his fingers on the belly] It's not the coolest place in the region. I'm talking about Vegas and Reno... Although, I've not been there actually, but... Well, I have not much to tell to be honest.}
{121}{}{Well, the hotel you are in, that's easy and obvious. Across the road from here, the cafe-club "Tin Angel" is shining. It has one cool feature about it - it's Gothic! People love gathering there on holidays, then vomiting at the entrance after a dozen bottles of beer.}
{122}{}{On the other side of the street there is a trading hall, you can get weapons and other stuff there. Although, if you need medication you should find a pharmacist. He lives to the north, quite close. But the choice of goods there [he makes a vile gesture and shows a wrinkled face] - yuck...}
{123}{}{There is also the office of our Sheriff Burton nearby. He's in charge of almost everything, he is the chief here. So be cool and don't make troubles - he doesn't like that. It wasn't easy to calm the city down, but he succeeded. Damn, I shudder to think what could have happened without him...}
{124}{}{There is also the Director at the Nuka-Cola factory, though. He is an enterprising man, if not for him, like hell we'd have some clean water, lighting and all other technical stuff now. Some even got domestic robots. Isn't that cool? [winks]}
{125}{}{And the factory is quite a thing. It's near here, east on the road. It's only thanks to the factory that the people still know about Salt Lake's existence. All caravans come here mainly for for this liquid joy they produce.}
{126}{}{By the way, the caravaneers have settled themselves down the street across the square.}
{127}{}{I don't know what else to add. Well, except that the cafe has a couple of slot machines. Have fun. [winks]}
{128}{}{Ugh. On the square near the entrance there is a gallows stationed. If you like performances you can wait until 4 PM and see a cxomedy. It's not real. It's a sort of amusement - someone plays the role of the hangman, he is accused in complete bollocks and then hung on the rope. Everyone's having fun and till the end of the day people feel great.}
{129}{}{I already told you everything. There's nothing interesting left.}

#Comic magazines
{130}{}{[Raises an eyebrow blankly] It's not an entertaining venue. We need peace and quiet in here. And yet... I know, back then, in good hotels, there were coffee tables, for those who have nothing to do during their stay. But the situation with paper publications in Salt Lake fared poorly. The magazines either burned during a nuclear bombing, or decayed from damp climate and poor care. What survived was taken by the Mormons for their library.}
{131}{}{[More]}
{132}{}{Look, you travel often, right? Can you search for these magazines on behalf of me? I can't pay a lot, but you wouldn't be encumbered much by the task to get some magazines, right?}
{133}{}{I'll try not to forget your request. Now let's change the subject.}
{134}{}{If I run across anything like that, I'll remember about you. Goodbye.}
{135}{}{I have a comic book.}
{136}{}{It's about the coffee table.}
{137}{}{Managed to find something suitable?}
{138}{}{Here's a great comic magazine.}
{139}{}{I have the issue of the erotic magazine "Cat's paw".}
{140}{}{Not yet, but I wanted to clarify: what kind of magazines are you interested in?}
{141}{}{Not yet. I shouldn't have asked, let's change the subject.}
{142}{}{No. Got to get going.}
{143}{}{Entertaining or erotic. What else can you read before bed... Do you have something like that?}
{144}{}{Exactly what I need! I'll pay for this edition 40$. Agreed?}
{145}{}{Sure, give the money, now this mag is yours.}
{146}{}{Let me have a think, and you tell me something else.}
{147}{}{Sounds good, but I have to think about it, see you.}
{148}{}{You gain experience for the delivery of the promised to the customer.}
{149}{}{}

#To rent a room for a day
{150}{}{Room is for renting for a day. For you it will cost }
{151}{}{I'll take the room, here is money.}
{152}{}{I don't have enough money, I will come later.}
{153}{}{Very well. I'll take you to your room.}
{154}{}{[Follow him]}
{155}{}{You vomited all over the floor! Now who's going to clean this up?!!}
{156}{}{You're well rested and feeling recuperated.}
{157}{}{ bucks. The next day you can pay again and continue to rest.}

#About the city
{200}{}{Well, what's the news... What's the news...}
{201}{}{Recently the thief was caught. They tried to catch him for a long time, but he's turned out to be quite a weasel. The Sheriff tried to track him down for two years, but could not. At first, everyone thought that the gang from Provo is doing its dirty work, but they are harsh people, they will rather hit you in the face straight away, and they afraid to enter the city, too. Well, now everything fell into place. Our Sheriff is awesome! Well done, real man!}
{202}{}{It was recently revealed that some creep robs the machines with Nuka-Cola. Can you imagine? No one understands how. Come on! They come to the machine, and it's just empty! And no traces of tampering visible. How does he do it, I wonder...}
{203}{}{Terrible things are happening. They say, Whip hired a mercenary who massacred a settlement of that trash in Provo. Completely, [makes cutting motion] to the root. It must have been pretty damn difficult. The Sheriff doesn't admit it was done by his order, but it doesn't matter - everyone felt relief when they heard the news.}
{204}{}{Gilmore was executed. Quite a bastard he was. It was high time to do it, but nobody wanted to go to Provo where he holed up. Now his redneck cronies should calm down.}
{205}{}{The Nuka-Cola Factory is blooming! There are more and more caravans and the factory opened new vacancies. I can't get enough of it, I lived to see this moment!}
{206}{}{Whether it was a sabotage, or the clerks of the Nuka-Cola Factory just suck. Well, you see, the Factory has been put on halt. It will be hard without it for the city, I hope that things there will return to normal someday...}
{207}{}{Now we have a lot more clean water, someone launched an artesian water tower. This is a real sensation!}
{208}{}{Situation with water getting worse and worse. And nobody knows what to do. Every day the visitors foul the toiled, there are sprays even on the walls! I'm so tired of it!}

{209}{}{Overall, the city blooms, becoming more beautiful and cleaner. Never thought I'd see this. Caravans come more often, more and more people are moving here to live. Salt Lake becomes a really cool city.}
{210}{}{Overall, the city languishes. People are leaving, the caravans come less often. It sucks. And I'm still lucky because at least I have a job.}
{211}{}{Overall, the situation in the city is the same as before - not good. It's a boring, sleepy place. You can find better.}
