{100}{}{You see a caravaneer.}
{101}{}{You see a cunning caravaneer. His face clearly expresses his motto: "I know a price of everything".}
{102}{}{Hi.}
{103}{}{Stealing an object for your own benefit negatively affects your karma.}
{104}{}{Cheeky cheater!}

{110}{}{What do you want?}
{111}{}{Word is that you have an encoder, which a Nuka-Cola factory needs.}
{112}{}{Nothing.}

{113}{}{Have one. I'll sell it for 1000$.}
{114}{}{But the factory negotiated for 300$.}
{115}{}{I have nothing to say against such a price. I'll just pay and take the encoder to the factory.}
{116}{}{I advise you not to be so stubborn with me. Otherwise it might end badly.}
{117}{}{And I'm not buying. Bye.}
{118}{}{I don't care what the factory wants. I own the thing, I set the price. And the factory should be happy if I don't raise it another five hundred next week.}
{119}{}{Trying to threaten me? Ha-ha, it's not going to work. }
{120}{}{I understand, but you should go back to the initial price if you don't want to lose your opportunity to make profit.}
{121}{}{No shit? Give me at least one reason why I should lower the price for the huge factory with a huge income.}
{122}{}{I've been in the merchant business in Nevada for a long time. I've seen a lot. Do you really want to take that risk? Then go ahead, don't sell it, I'm only here to give you a friendly warning as a fellow caravaneer.}
{123}{}{Hmm... You have a point. I wanted to get more money out of them, but the longer I keep this thing, the faster they'll find a replacement... Okay, you got me sober. I agree to go back to the starting price of $300.}
{124}{}{I see through the likes of you. I'm more experienced.}
{125}{}{Have your 300$ and give me the encoder.}
{126}{}{Good, but I don't have money to pay. I'll be back later, with cash.}
{127}{}{Good decision. Do you have 1000$?}
{128}{}{Take the money and give me the encoder.}
{129}{}{I still have doubts about whether I'm doing the right thing. Don't get me wrong - it's not just about me, it's about my guys too. We have to work hard to feed ourselves. But let's not talk about that.}
{130}{}{Bye.}
{131}{}{That's what I was counting on! And I don't even doubt that I did the right thing by inflating the price after the contract was signed. Don't get me wrong - it's not just about me, it's about my guys too. We have to work hard to feed ourselves. But let's not talk about that.}
{132}{}{Bye then.}