{100}{}{You see a caravaneer.}
{101}{}{You see a cunning caravaneer. His face makes his creed clear: "I know a price for everything".}
{102}{}{Hi}
{103}{}{Stealing an object for your own benefit negatively affects your karma.}
{104}{}{Cheeky cheater!}

{110}{}{What do you want?}
{111}{}{Word on a street that you have an encoder, which is needed on a Nuka-Cola factory.}
{112}{}{Nothing.}

{113}{}{Have one. I'll sell it for 1000$.}
{114}{}{But the factory negotiated for 300$.}
{115}{}{I have nothing to say against such a price. Let me just pay and take the encoder to the factory.}
{116}{}{I advise you not go so stubborn on me. Otherwise, it may end badly.}
{117}{}{And I'm not buying. Bye.}
{118}{}{And I do not care what's expected at the factory. I own the thing, I acquired it, so it is me, who sets the price. And factory should be happy, if I won't raise the price by another five hundred next week.}
{119}{}{Trying to threaten me? Ha-ha, won't work here. }
{120}{}{I get it, but you should return to the initial price, if you don't want to lose the opportunity to earn.}
{121}{}{No shit? Give me at least one reason why I should lower the price for the huge factory with a huge income.}
{122}{}{I'm in trading business of Nevada for a long time. During this, I had to see a lot. Do you really want to take the risk? Then go, don't sell it, I'm only here to warn you in a friendly manner, like a fellow caravaneer.}
{123}{}{Hm... You have a point. I wanted to scratch more money out of them, but the longer I'm holding this thing, the sooner they'll find a replacement... Okay, you made me sober. I agree to return to initial price of 300$.}
{124}{}{I see through the likes of you. I'm more experienced.}
{125}{}{Have your 300$ and give me the encoder.}
{126}{}{Good, but I don't have money to pay. I'll be back later, with cash.}
{127}{}{Right decision. Do you have 1000$?}
{128}{}{I've got it. Take them and give me the encoder.}
{129}{}{I still doubt if I'm doing the right thing. Understand me correctly - It's not only about me, but for my guys too. We need to work hard to feed themselves. But let's not talk about this.}
{130}{}{Bye.}
{131}{}{This is what I was counting on! And I don't even doubt that I did the right thing by inflating the price after the contract. Understand me correctly - It's not only about me, but for my guys too. We need to work hard to feed themselves. But let's not talk about this.}
{132}{}{Bye then.}