{100}{}{You see a manager.}
{101}{}{You see the hotel manager. He's busy with blowing the dust off his suit.}
{102}{}{Put the gun down, then we'll talk.}

#Starting replicas
{109}{}{What?}
{110}{}{Want to book a room?}
{111}{}{Yes? What do you want?}

{112}{}{Let's chat a little? I'm interested in the situation in the city. What's the latest news?}
{113}{}{Tell me about the city. What is there to see and where can you hang out?}
{114}{}{It's quite boring here. No music, no magazines.}
{115}{}{I need a room to rest. How much would it cost me?}
{116}{}{Go on.}
{117}{}{I don't want anything, I'll go.}
{118}{}{One more question, if I may...}
{119}{}{All right, thanks.}

#About the hotel and the city:
{120}{}{Well, what can I say... [He relaxes in his chair with his fingers crossed on his stomach] It's not the best place in the region. I mean, there's also Vegas and Reno... Although I haven't actually been there, but... Well, to be honest, I don't have much to say.}
{121}{}{Well, the hotel you're in, obviously. Across the street from it shines the sign of a "Tin Angel" Cafe. It has one distinct feature - gothic style! People like to gather there on holidays and then throw up at the entrance after a dozen beers.}
{122}{}{Down the street you can find a trading hall, you can buy weapons and other stuff there. Although, if you need medications, you'd better pay a visit to a local pharmacist. He lives to the north, near the Renaissance square. It's not very far from here. But his assortment... [he makes a gesture and wrinkles face] Meh.}
{123}{}{There is also the office of our Sheriff Burton. He's in charge of almost everything here. So be cool and don't make any trouble - he doesn't like that. It wasn't easy to bring order to the city, but he succeeded. Damn, I don't even want to think what could have happened without him...}
{124}{}{You can also come by the Nuka-Cola plant and have a chat with its director. If it weren't for him, like hell we'd have clean water, electricity and other conveniences. Some of us even have pet robots. Isn't that cool? [winks]}
{125}{}{And the factory is quite a thing, really. It's not far from here, to the east. It is only thanks to this factory that people still know of the existence of the Salt Lake. All caravans come here mainly for the liquid joy they produce.}
{126}{}{By the way, the caravaneers themselves can be found down the street, across the square.}
{127}{}{I don't know what else to say. Well, except maybe that the cafe has a couple of slot machines. Have fun. [He winks]}
{128}{}{Ugh. There is a gallows in the square near the entrance. If you want to, you can wait until 4:00 p.m. to see the show. It's not real. It's a kind of a local entertainment - someone plays the role of the executioner and someone is accused of complete nonsense and then "hanged". Everyone has fun, and people feel great for the rest of the day.}
{129}{}{I told you everything. There's nothing else of interest.}

#Comic magazines
{130}{}{[He raises an eyebrow] This is not an entertainment venue. We need peace and quiet here. And yet... I know that in the old days good hotels had coffee tables, for those who had nothing to do during their stay. But the paper publishing situation in Salt Lake hasn't been great lately. Magazines either burned up in the nuclear bombing or decayed from the damp climate and poor storage. What remained was taken by the Mormons for their library.}
{131}{}{[More]}
{132}{}{Look, you travel often, right? Can you search for some magazines for me? I can't pay a lot, but you wouldn't be encumbered much by a request to get some magazines, right?}
{133}{}{I'll try not to forget about it. Now let's change the subject.}
{134}{}{If I run across anything like that, I'll remember about you. Goodbye.}
{135}{}{I have a comic book magazine.}
{136}{}{About the coffee table...}
{137}{}{Managed to find something suitable?}
{138}{}{Here's a great comic book magazine.}
{139}{}{I have the issue of the erotic magazine named "Cat's paw".}
{140}{}{Not yet, I just wanted to clarify: what kind of magazines are you interested in?}
{141}{}{Not yet. I shouldn't have asked, let's change the subject.}
{142}{}{No. Got to get going.}
{143}{}{Entertaining or erotic. Anything you can read before bed... Do you have something like that?}
{144}{}{Exactly what I need! I'll pay $40 for it. Agreed?}
{145}{}{Sure. Give the money, now it's yours.}
{146}{}{Let me think a little, while you telling me something else.}
{147}{}{Sounds good, but I have to think about it. See you.}
{148}{}{You gain some experience for the delivery.}
{149}{}{}

#To rent a room for a day
{150}{}{The room is rented for a day. For you it will cost }
{151}{}{I'll take the room, here is money.}
{152}{}{I don't have enough money, I will come later.}
{153}{}{Very well. I'll take you to your room.}
{154}{}{[Follow him]}
{155}{}{You vomited all over the floor! Who's going to clean this up?!}
{156}{}{You feel well rested and recovered.}
{157}{}{ bucks. To prolong your stay, pay again the next day.}

#About the city
{200}{}{Well, what's the news... What's the news...}
{201}{}{Recently a thief was caught. It took a while, he turned out to be quite a weasel. The sheriff had been trying to track him down for two years, but failed. At first everyone thought it was the Provo gang, but they're too tough, they'd rather punch you in the face right away than do the thievery. And they're afraid to come into town lately. Well, at least now it all makes sense. And our sheriff is awesome! What a great job!}
{202}{}{It was recently revealed that some creep robs the Nuka-Cola machines. Can you imagine? No one understands how. They come to the machine, and it's just empty! And no traces of tampering. How does he do it, I wonder...}
{203}{}{There are some disturbing rumors. Some say, Whip hired a mercenary who massacred everyone in Provo settlement. [He makes a cutting motion with his hand] Everyone. It must have been pretty damn difficult. The Sheriff won't admit that it was done on his orders, but it doesn't matter - though it's pretty scary, everyone was relieved to hear the news.}
{204}{}{Gilmore was executed. What a bastard he was... It was long overdue, but no one wanted to get him out of Provo, where he was hiding. Now his redneck cronies should calm down.}
{205}{}{The Nuka-Cola factory is blooming! There are more and more caravans around here, and the factory has a lot of job openings. I can't get enough of it, I lived to see this moment!}
{206}{}{Either it was a diversion or the clerks at the Nuka-Cola factory just suck, but, you see, the factory recently stopped working. It's going to be hard for the city without it. I hope the situation there will get better someday...}
{207}{}{Now we have a lot more clean water. Someone launched an artesian water tower. This is sensational!}
{208}{}{Situation with water is getting worse and worse. Nobody knows what to do. Every day the visitors foul the toiled, there are sprays even on the walls! I'm so tired of it!}

{209}{}{Overall, the city blooms, becoming more beautiful and cleaner. Never thought I'd live to see this. Caravans come more often, people are moving here to live. Salt Lake becomes a really cool place.}
{210}{}{Overall, the city languishes. People are leaving, the caravans come less often. It just sucks. And I'm still lucky, because at least I have a job.}
{211}{}{Overall, the situation in the city is the same as before - not good. It's a boring, sleepy place. You can find better.}
