{10}{}{ }
{100}{}{You see a hobo.}
{101}{}{You see a messy and uncombed man.}
{102}{}{Eh... Thanks, but don't do this again.}
{103}{}{Thank you, kind person!}
{104}{}{Uh... Do you have a sandwich? I have troubles with winds with this one...}
{105}{}{You drove the annoying beggar from the city.}
{106}{}{You helped the hobo rise on his feet.}

#Eсли видит ГГ:
{150}{}{Hey, kind person!}
{151}{}{Help please!}
{152}{}{Give food! I haven't eaten two days!}
{153}{}{Spare some change?}
{154}{}{Lend till the salary?}
{155}{}{I need medicines! Really!}
{156}{}{Do not leave a person in trouble!}
{157}{}{Please, give some to eat!}
{158}{}{I know you'll help unhealthy one.}
{159}{}{Sorry, would you any spare change?}
{160}{}{Where you go, kind person?! What about me?!}

#Диалог:
{200}{}{Could kind person help crippled one in his unhappy life? Please, with a bun at least...}
{201}{}{Well then! Come on, let's dine in this cafe like normal people. Let's go!}
{202}{}{[Give sandwich]}
{203}{}{[Give fruit]}
{204}{}{[Give iguana-on-a-stick]}
{205}{}{Scram, filth!}
{206}{}{[Give dry meal]}
{207}{}{[Give 10$]}
{208}{}{Sorry, don't have money right now.}

{209}{}{Oh! Kind! Kind! Kind person! Thanks! Thank you! I'll never forget you!}
{210}{}{You're welcome, pal!}
{211}{}{Oh! Kind! Kind! Kind person! Thanks! Thank you for everything! You're so kind, I don't even know how to express it! [you see tears of joy in the beggar's eyes]}
{212}{}{No problem, pal! See, life's getting better. Bye.}
{213}{}{Give up on this life, pal! Sheriff offers you a job. Sure, payment's not much, but enough to live. You just go to him and chat. Say that I've sent you. Okay?}
{214}{}{Give up on this life, pal! I've got stable and easy job for you. You can do it. See that shop? They need a man to work in a storeroom. Say that I've sent you. Okay?}
{215}{}{What? Sheriff himself? [The beggar opens his mouth in amazement] Oh! Mister Whip wants to hire me! Kind! Kind person! I'm so happy! So happy!}
{216}{}{Come on, it was easy...}
{217}{}{Sheriff - he's fair one. He won't left me bullied! Not like some others!}
{218}{}{And who's bullying you?}
{219}{}{No one! Just saying... There was one bandit wandered around the cafe. If you stumble upon him, don't even talk. Well, I'm off to sheriff, yes?}
{220}{}{Yeah, now go. Take care.}
{221}{}{Really?! They'll feed me? Oh! Kind! Kind person! I'm happy! So happy! Thank you! Thanks!}
{222}{}{Come on, it was easy... Take care.}
{223}{}{(Just think about how people can change! You washed, brushed, fed and amused this beggar, after which he even changed his face. If he were given a push to evolve, he would become a respectable citizen in the town.)}
{224}{}{[Leave]}

#Выгоняем из города
{225}{}{[Beggar continues to stand by and wait, apparently insults are usual thing for him]}
{226}{}{Alright, trash-humper, leave this place until I hit you right in the eye!}
{227}{}{Uh, okay sorry, just came out that way... So what did you want?}
{228}{}{[Ignore him and go about your business]}
{229}{}{Good person, could you find at least a slice of bread?}
{230}{}{Hm, you know what - just get out of my way!}
{231}{}{[Beggar continues to stay with lowered look]}
{232}{}{Well then, I've got enough of you! You want to fight, yes? You want it? Come on! Come here! Heya!!!}
{233}{}{Sorry, good person, I... I just wanted to ask...}
{234}{}{You deaf, right? I'll explain one last time - get out of town or I'll cut your throat!}
{235}{}{Hell, maybe I need to give some grub, so you could get away?}
{236}{}{Uh, okay, buddy, let's not argue, there's enough room in the city. Bye.}
{237}{}{Oh, yes, good person... Kind person won't ever see me, I get you...}
{238}{}{If you enter the town again - *no one* will ever see you besides rats on the junkyard! Well then, get out of here!}
{239}{}{That's better. Now I'm the sheriff here so don't argue and leave the town already.}
{240}{}{Yes, the sheriff says - so be it... Sheriff won't see me and I won't interfere with sheriff, I'll go.}
{241}{}{Move your ass, miserable fuck!}
{242}{}{Yes, okay, Sometimes I get angry, but then I get back to normal. You can stay in town, but do not come across my eyes!}
{243}{}{Yeah, bye.}

#Female character
{1211}{}{Oh! Kind! Kind! Kind lady! Thanks! Thank you for everything! You're so kind, I don't even know how to express it! [you see tears of joy in the beggar's eyes]}
