{100}{}{You see Chip.}
{101}{}{You see an untidy beggar who sneaks a glance at you.}
{102}{}{*Makes an insistent calling sign to you to approach him*}
{103}{}{There won't be a conversation here.}

#Первый диалог
{110}{}{Hey, psst! Kid, come here, we need to talk.}
{111}{}{Hey, psst! Brusher, come here, we need to talk.}
{112}{}{Hey, psst! Cowboy, come here, we need to talk.}
{113}{}{Hey, psst! Pretty boy, come here, we need to talk.}

{1110}{}{Hey, psst! Wench, come here, we need to talk.}
{1111}{}{Hey, psst! Momma, come here, we need to talk.}
{1112}{}{Hey, psst! Muchacha, come here, we need to talk.}
{1113}{}{Hey, psst! Babe, come here, we need to talk.}

{120}{}{Maybe, but not with such a degraded drunkard like you.}
{121}{}{If it's a business talk, then why not.}
{122}{}{It's your business, I don't dare to insist. But I would listen if I were you.}
{123}{}{Yeah, don't care. I don't want any conversations with you. Get lost to the junkyard you scum!}
{124}{}{Maybe later. Now I have important business to attend to.}
{125}{}{Yes, business. And I could say that our business crosses somewhere, he-he.}
{126}{}{What do you mean}
{127}{}{You didn't get it the first time? Get lost, filth!}
{128}{}{If I change my mind, then I come back and then we will continue the conversation. But now I have to go.}
{129}{}{Changed your mind? Then you're smart after all.}
{1129}{}{Changed your mind? Then you're smart after all.}
{130}{}{It all depends on what you want to discuss with me.}
{131}{}{No, it just seemed like you're another beggar, not the one I need.}
{132}{}{Well, that's the biker you were looking for, right?}
{133}{}{A biker? Wait a minute, where... Okay, so you know something.}
{134}{}{Yup. But it's a private conversation. Do you know where one-eyed outcast Stapleton lives? It's in the slums in the east, directly opposite the artesian tower. We shall meet there. And do not forget to grab a meal for me and some change. I like to talk on a full stomach.}
{135}{}{[Puzzlingly follow the hurrying beggar with your eyes.]}