{100}{}{It's Roger Quok.}
{101}{}{Before you stands the trader - Roger Quok.}

{109}{}{What now?}
{110}{}{Hello, wanderer! The Quok brothers always have a lot of useful stuff for the road. Choose, you won't regret it!}
{111}{}{Oh! Good choice! Though, I'm sorry, I had to raise prices, because some kind of scoundrel robbed us...}
{112}{}{[Trade]}
{113}{}{Hey! I just saw someone jumping to our yard! I think it was a thief!}
{114}{}{There is one poor guy that can't find a job. Maybe you could put him somewhere in the back room? He does not need much...}
{115}{}{Thanks, but no.}
{116}{}{Work, you say? Well, if you think about it, there is something. Not for the soft handed. You tell him, to come to us, we'll talk.}
{117}{}{Okay!}

{118}{}{Are you sure you don't need anything?}
{119}{}{Let's see what you have one more time...}
{120}{}{No, bye.}

{129}{}{Shit! I'll show him!!..}
{130}{}{[Look as they catch the thief]}
{131}{}{You ratted your partner!}
{132}{}{Hey, wanderer! Come here, I have a question.}
{133}{}{Hold it right there! I have a shotgun!}
{134}{}{NO!!! NOT THIS!!!}
{135}{}{You should've thought earlier! Now come out.}

{136}{}{You did the right thing to tell us. The sheriff was looking for him for a long time. Now the city will become more calm. You know, in our time people usually don't do something for the sake of good. I do not know why you did it, but I consider myself obligated to repay you. Here's 500 bucks for honesty and one of my favorite guns. I hope you like it.}
{137}{}{This gun is amazing!}

#Харрельсон
{138}{}{[Next]}
{139}{}{No competitors, my friend, I promise. And my word in these parts means something.}
{140}{}{Sorry, but with such products and prices, I can only get out. Although, wait, maybe you know how to make money around here?}
{141}{}{Hmm, I know of one place where you can make good money. But I'm not sure about you - you may run to competitors!}
{142}{}{Not sure? Hey, I'm not a trader! I see - you won't change your mind...}
{143}{}{I see you're really a person of action... I'll give you the coordinates of that place. Get inside, take everything that you see, and bring it to me. Then we will trade.}
{144}{}{Great. What is the place?}
{145}{}{It's in the mountains, on the other side of the salt valley. Some unusual person lives there since the Great War. It is said that it is an eerie sight to see, and that bullets don't hurt him. And his name is Harrelson. But most importantly - he supposedly has untold riches, which he collected after the War. Many went hunting after him, but few returned. His den is about here. [Shows on the map]}
{146}{}{Fine, I'll think about it.}
{147}{}{It's pretty silly to miss this chance.}

{148}{}{No, that won't do.}
{149}{}{Come on, all the caravans know me as a reliable partner.}

{150}{}{Hey, those are mine!}
{151}{}{Really?! In any case, it's not my problem - I got these things in an honest fair way. Therefore, if you want something - buy it.}
{152}{}{Grm...}

#Бонус для бартера
{161}{}{Yes I do need something, but you don't have it. Actually, you don't have a lot of things.}
{162}{}{Be thankful that we have what we have. It's not the times to ask for a lot.}
{163}{}{Yeah... But it seemed to me that in such a large city the assortment should be many times more diverse, than in the settlements. There is something you're not telling me.}
{164}{}{Well, it's not that it's a secret. It's just... Usually, no one understands where the goods come from and how hard it is to get it. Why do you care?}
{165}{}{You see, I also do business from time to time, trading in different cities. So I'm interested in the local market.}
{166}{}{Just curious. Don't mind me.}
{167}{}{Hmm, you seem like someone I can trust. Okay, listen. Salt Lake was destroyed in 2077 by thirteen nuclear explosions. Almost the entire northern half of the city was burnt. Add to this "troubled times" and unsanitary conditions - and you will have a beautiful picture of our current situation.}
{168}{}{[Next]}
{169}{}{Things are worn out, factories are destroyed, medicines are all used up... But on the other hand, we have a lot of equipment left from the old city. Unlike Vegas or Reno. They have other crafts there, and we have ours. Caravans bring machinery for repair or purchase some parts, and in exchange they trade medicines and other important things.}
{170}{}{And what about marauders? Don't they try to loot the northern ruins?}

{171}{}{Marauders? Perhaps you are talking about prospectors? We usually call them that. But the sheriff does not like them. He strictly forbids anyone to go to the northern part of the city. And those who dare are punished rather harshly, including pillars of shame, fines and even short-term hard labor. True, this is not the only prospectors problem, more often you have to deal with people from Denver.}
{172}{}{Do you even check things that you get?}
{173}{}{Tell me about Denver.}
{174}{}{Why does the sheriff prohibit such a "practice" in the ruins of Salt Lake?}
{175}{}{Thanks for the review. I will now keep it in mind. See you.}
{176}{}{Well, of course! I have a Geiger counter in the back room, I often use it to check the goods.}
{177}{}{This city was also unlucky. It was partially destroyed and held some pre-war riches. The difference is, there is much more in Denver, than here. Those are the riches the prospectors are trying to find. As far as I know, they have a full blown turf wars going on there. Sometimes a caravans come from there with decent loot, but it's sometimes radioactive or in poor condition. In any way, it is better than nothing.}
{178}{}{He says it's dangerous and that any thing from there can be contaminated with radiation or some kind of fatal infection. I'll tell you how it is - it really happened, though not often. But I think he's more afraid that someone would find something special. Something from the army past of Salt Lake City. Here in fact there was a large military base in the north. It was bombed seventy years ago.}
{179}{}{You got 200 experience points for successfully applying the trade skill in talking about business processes in Salt Lake.}
{180}{}{Right.}

#Female character:
{1110}{}{Hello, wanderer! The Quok brothers always have a lot of useful stuff for the road. Choose, you won't regret it!}
{1113}{}{Hey! I just saw someone jumping to our yard! I think, it was a thief!}
{1132}{}{Hey, wanderer! Come here, I have a question.}
{1136}{}{You did the right thing to tell us. The sheriff was looking for him long ago. Now the city will become calmer. You know, in our time people usually don't do something for the sake of good. I do not know why you did it, but I consider myself obligated to repay you. Here's 500 bucks for honesty and one of my favorite guns. I hope you like it.}
