{100}{}{This is Steven Quok.}
{101}{}{You see a weapon trader Steven Quok.}

{109}{}{Is there something else?}
{110}{}{Hello wanderer! Don't pass by Quok's family business! We always happy with new visitors and won't let you go without some excellent goodies! Check out my new weapon stock. Maybe you'll find something fitting your holster.}
{111}{}{What a cold-blooded move! But sorry, I have to raise the price since some bastard just robbed us...}
{112}{}{[Buy weapon]}
{113}{}{Hey! I just saw someone jumping into your yard! I think that was the thief!}
{114}{}{There's some poor fellow who can't find a job. Maybe you could make use of him somewhere in a storeroom? He won't ask much...}
{115}{}{Don't need it, thanks.}
{116}{}{Job you say? Well, I can think something out. Not for kid-gloves.  Tell him to visit me, we'll talk.}
{117}{}{Alright!}

{118}{}{You *sure* you don't need anything else?}
{119}{}{Let's take a look again...}
{120}{}{No, bye.}

{129}{}{Dammit! When I get him!!..}
{130}{}{[Look at capture scene from the outside]}
{131}{}{You have betrayed your partner!}
{132}{}{Hey wanderer! Wouldn't mind coming in, there's one question to resolve.}
{133}{}{Stay where you are! I've got a shotgun!}
{134}{}{NO!!! GODDAMMIT!!!}
{135}{}{You should've think twice before! Now come out.}

{136}{}{You did the right thing telling me about him. Sheriff looked for this wriggler for a long time. Now the town will be safer. You know, people these days don't help each other just because. I don't know *why* you sold him out but I just have to thank you. Here's 500 bucks and my favorite gun. Hope you like it.}
{137}{}{Thanks! It's a worthy gun!}
{138}{}{You came in just in time! Prospectors found an excellent weapon - heavy machine gun, which fires rifle rounds. I was think about selling it someone. Sheriff would gladly buy it but for a small price. Maybe your money are more willing? Anyway, I'll just leave it here and you think about the offer.}

#Бонус для тагнутых тяжелым оружием
{140}{}{You know, your assortment lacks something serious - something that shoots... EXPLOSIVES! Might come in handy for me.}
{141}{}{I see you value some heavy army weaponry. Such things are not for self defense. Anyway, the Sheriff instantly buys any serious weapon I find... For a cheap price, of course.}
{142}{}{Cheap? You know, I can offer more than Sheriff. Let me know when you have something in stock.}
{143}{}{[Smiles and nods] Why yes, there's grenade launcher and 40mm ammunition packs for it. If you want, you can buy it before Sheriff beats you. But don't tell the cops where did you get this baby.}
{144}{}{No problem!}

#Машинист
{150}{}{Tell me, kind man, who'd ride with me on a train?}
{151}{}{Hm? Hardly any of the local will decide on this. Only newcomer in the city, or absolutely desperate, who would also want to catch a bullet from the sheriff at the railway depot. It's forbidden not only to go there, but even to speak publicly about it.}
{152}{}{Eh, thanks for the tip.}

#Про оружие в городе
{160}{}{To say honestly, you weapon stock is shit.}
{161}{}{[He throws up his hands in grief] Why everyone says the same to me?! A-ah, now I get it. You're from these regions where bombs did not send half of the town to hell and where civil war wasn't an issue. So now you know, we were much less fortunate. Have to appreciate what's left.}
{162}{}{Maybe you can advice someone with better stock?}
{163}{}{No one besides me... And police with mormons. But these ones won't be traded with, rather opposite - they buy all the good guns and give me away any kind of pipe trash. [he sniffs] And then they are surprised that I can't sell a damn thing...}
{164}{}{Understood, will keep in mind.}

#Гаусс-патроны
{170}{}{Do you know anything about Sheriff Burton's weapon?}
{171}{}{I know something. Mostly from an article in "Super-science". It describes such systems.}
{172}{}{What systems?}
{173}{}{With the principle of electromagnetic acceleration. The bullet accelerates due to a stepped magnetic repulsion. Such weapons were only available to large military bases and military engineering laboratories. The sheriff Burton's gun, apparently, is from the northern military base, which was bombed in the year of 2077.}
{174}{}{You've said something about bullets. It's just a cartridge, right?}
{175}{}{Oh no, it's a 2mm metal needle. Sounds simple, but you must really know what to do, to make them.}
{176}{}{What's so difficult?}
{177}{}{The magnetic properties of metals, aerodynamics, mass balance... To be clear, it's pure physics and mathematics. If you want to learn, the article had all the necessary explanations. Just pay 200 bucks for the information.}
{178}{}{All right, here's the money.}
{179}{}{Let's change the topic.}
{180}{}{[You carefully study the excellent article about the Gauss system from the "Super-science" magazine. It seems that with the proper repairing skills, you could easily manufacture ammunition for weapons with electromagnetic acceleration.]}
{181}{}{[End]}

#Female character:
{1110}{}{Hello wanderer! Don't pass by Quok's family business! We always happy with new visitors and won't let you go without some excellent goodies! Check out my new weapon stock. Maybe you'll find something fitting your holster.}
{1113}{}{Hey! I just saw someone jumping into your yard! I think that was the thief!}
{1132}{}{Hey wanderer! Wouldn't mind coming in, there's one question to resolve.}
{1136}{}{You did the right thing telling me about him. Sheriff looked for this wriggler for a long time. Now the town will be safer place. You know, people these days don't help each other just because. I don't know *why* you sold him out but I just have to thank you. Here's 500 bucks and my favorite gun. Hope you like it.}
