{100}{}{It's Roger Quok.}
{101}{}{Before you stands the trader named Roger Quok.}

{109}{}{What now?}
{110}{}{Hello, wanderer! The Quok brothers always have a lot of useful stuff for you. Choose and buy, you won't regret it!}
{111}{}{Oh! Good choice! Sorry, I had to raise the prices because some rascal robbed us...}
{112}{}{[Trade]}
{113}{}{Hey! I just saw someone climbing into your yard! I think it was a thief!}
{114}{}{There is one poor guy that can't find a job. Maybe you could put him somewhere in the back room? He does not need much...}
{115}{}{Thanks, but no.}
{116}{}{Work, you say? Well, if you think about it, there is something. Not for the soft-handed. Tell him to come to us, we'll talk.}
{117}{}{Okay!}

{118}{}{Are you sure you don't need anything?}
{119}{}{Let's see what you have one more time...}
{120}{}{No, bye.}

{129}{}{Shit! We'll show him!}
{130}{}{[Look as they catch the thief]}
{131}{}{You ratted out your partner!}
{132}{}{Hey, wanderer! Come here, I have a question.}
{133}{}{Hold it right there! I have a shotgun!}
{134}{}{NO!!! NOT AGAIN!!!}
{135}{}{You should've thought earlier! Now come out.}

{136}{}{You did the right thing by telling us. The sheriff has been looking for him for a long time. Now the city will become calmer. You know, in our time people usually don't do something just for the sake of good. I don't know why you did it, but I want to pay you for it. Here's 500 bucks, and here's one of my favorite guns. I hope you like it.}
{137}{}{This gun is amazing!}

#Харрельсон
{138}{}{[Next]}
{139}{}{No competitors, my friend, I promise. And my word in these parts means something.}
{140}{}{Sorry, but with such products and prices I can only get out. Although, maybe you know how to make some money around here?}
{141}{}{Hmm, I know of one place where you can make a good profit. But I'm not sure about you... What if you go to out competitors?}
{142}{}{Not sure? Hey, I'm not even a trader... Looks like you are not going to change your mind.}
{143}{}{I see that you really are a man of action... I'll give you the coordinates. Go there, get inside, take whatever you see. Then we'll trade.}
{144}{}{Great. What is that place?}
{145}{}{It is in the mountains, on the other side of the Salt Lake Valley. An unusual man has been living there since the Great War. It is said that he is a ghastly sight, and that bullets do him no harm. And his name is Harrelson. But most importantly, he allegedly has untold riches that he amassed after the war. Many have been after him, but few have returned. His lair is around here. [He points the location on your map]}
{146}{}{Fine, I'll think about it.}
{147}{}{It's pretty silly to pass on this opportunity.}

{148}{}{No, that won't do.}
{149}{}{Come on, all the caravan traders know me as a reliable partner.}

{150}{}{Hey, those are my things!}
{151}{}{Really? In any case, that's not my problem - I got these things in an honest and fair way. Therefore, if you want something - buy it.}
{152}{}{Grrm...}

#Бонус для бартера
{161}{}{Yes I do need something, but you don't have it. Actually, you don't have a lot of things.}
{162}{}{Be thankful that we have what we have. You can't ask for more in times like this.}
{163}{}{Yeah... But it seemed to me that in such a big city the assortment should be many times more diverse than in the villages. There's something you're not telling me.}
{164}{}{Well, it's not that it's a secret. It's just... Usually, no one understands where the goods come from and how hard it is to get them. Why do you care?}
{165}{}{You see, I also do trading from time to time. So I'm interested in the local market.}
{166}{}{Just curious. Don't mind me.}
{167}{}{Hmm, you look like someone I can trust. Okay, listen. Salt Lake was destroyed in 2077 by thirteen nuclear explosions. Almost the entire northern half of the city was burned to the ground. Add to this the "troubled times" that came after, unsanitary conditions, and you get a perfect picture of our current situation.}
{168}{}{[Next]}
{169}{}{Things are worn out, factories are destroyed, medicines are used... But on the other hand, after the war we were left with a lot of working machinery. Not like Vegas or Reno. These cities have developed industry in other areas, and we try to benefit from that. Caravans bring us equipment to be repaired, or buy parts from us, and in exchange they supply us with medicine and other essential things.}
{170}{}{And what about marauders? Don't they try to loot the northern ruins?}

{171}{}{Marauders? You must be talking about prospectors. That's what we used to call them. But the sheriff doesn't like them. He strictly forbids anyone to come to the north side of the city. And if they do, he punishes them severely, including pillars of shame, fines, and even a short-term hard labor. It is true that this is not the only prospector's site; sometimes we trade with people from Denver.}
{172}{}{Do you even check things that you get?}
{173}{}{Tell me about Denver.}
{174}{}{Why does the sheriff prohibit such a "practice" in the ruins of Salt Lake?}
{175}{}{Thanks for the overview. I will keep it in mind. See you.}
{176}{}{Of course! I have a Geiger counter in the back room, I often use it to check the goods.}
{177}{}{That city was also unlucky. It was also partially destroyed and also retained some pre-war riches. The difference is that there is much more of them in Denver than here. And that's what attracts the prospectors. As far as I know, they have a full-blown turf wars going on. From time to time, a caravans come from there, carrying a decent loot, but it's sometimes radioactive or in poor condition. In any way, it is better than nothing, so we are not complaining.}
{178}{}{He says it's dangerous and that anything from there could be contaminated with radiation or some deadly infection. And, in fact, he is not very wrong - incidents did happen, though not very often. But I think he's more afraid of somebody finding something special. Something from Salt Lake City's military past. There was a big military base up north. That's why that part of the city was bombed seventy years ago.}
{179}{}{You get 200 experience points for successfully applying the trading skill in talking about business processes in Salt Lake.}
{180}{}{Right.}

#Female character:
{1110}{}{Hello, wanderer! The Quok brothers always have a lot of useful stuff for you. Choose and buy, you won't regret it!}
{1113}{}{Hey! I just saw someone climbing into your yard! I think it was a thief!}
{1132}{}{Hey, wanderer! Come here, I have a question.}
{1136}{}{You did the right thing by telling us. The sheriff has been looking for him for a long time. Now the city will become calmer. You know, in our time people usually don't do something just for the sake of good. I don't know why you did it, but I want to pay you for it. Here's 500 bucks, and here's one of my favorite guns. I hope you like it.}
