{100}{}{This is Steven Quok.}
{101}{}{You see a weapon trader Steven Quok.}

{109}{}{Is there something else you need?}
{110}{}{Hello wanderer! Don't pass by Quok's family business! We are always happy to see the new customers and won't let you go without some excellent goodies! Check out my new weapon stock. Maybe you'll find something fitting your holster.}
{111}{}{Great choice! Sorry I had to raise the price - some bastard robbed us recently...}
{112}{}{[Buy weapon]}
{113}{}{Hey! I just saw someone climbing into your yard! I think it was a thief!}
{114}{}{There's some poor fellow who can't find a job. Maybe you could make use of him in your storeroom? He won't ask much...}
{115}{}{Don't need it, thanks.}
{116}{}{Job you say? Well, I can think something out. Not for kids. Tell him to visit me, we'll talk.}
{117}{}{Alright!}

{118}{}{Are you sure you don't need anything else?}
{119}{}{Let's take a look again...}
{120}{}{No, bye.}

{129}{}{Dammit! When I get him!!...}
{130}{}{[Look at capture scene outside]}
{131}{}{You have betrayed your partner!}
{132}{}{Hey, wanderer! Feel free to stop by, there's a question that needs to be solved.}
{133}{}{Stay where you are! I've got a shotgun!}
{134}{}{NO!!! GODDAMMIT!!!}
{135}{}{You should've thought twice! Now come out.}

{136}{}{You did the right thing by telling me about him. The sheriff's been looking for that weasel for a long time. The town will be safer now. You know, these days people don't help each other for nothing. I don't know why you turned him in, but I'm still grateful. Here's 500 bucks and my favorite gun. Hope you like it.}
{137}{}{Thanks!}
{138}{}{You came just in time! Prospectors have brought me an excellent weapon - a heavy machine gun, which fires rifle rounds. I was thinking of selling it to someone. Sheriff would gladly buy it, but maybe you are willing to pay more? Anyway, I'll just leave it here and let you think about the offer.}

#Бонус для тагнутых тяжелым оружием
{140}{}{You know, your assortment lacks something serious - something that shoots... EXPLOSIVES! Might come in handy for me.}
{141}{}{I see you value some heavy army weaponry. Such things are not for self-defense. Anyway, the Sheriff instantly buys any serious weapon I find... For a cheap price, of course.}
{142}{}{Cheap? You know, I can offer more than Sheriff. Let me know when you have something in stock.}
{143}{}{[Smiles and nods] Why yes, there's grenade launcher and 40mm ammunition packs for it. If you want, you can buy it before Sheriff. But don't tell the cops where you got this baby.}
{144}{}{No problem!}

#Машинист
{150}{}{Tell me, kind man, who'd ride with me on a train?}
{151}{}{Hm? Hardly any local, that's for sure. Only maybe some newcomer, or someone absolutely desperate, willing to catch a bullet from the sheriff at the railway depot. It's forbidden not only to go there, but to even speak publicly about it.}
{152}{}{Eh, thanks for the tip.}

#Про оружие в городе
{160}{}{To be honest, you weapon stock is quite shitty.}
{161}{}{[He throws his hands up] Why does everybody keep telling me the same thing?! Ahhhh, now I get it. You're from those places where bombs didn't send half the city to hell and where the civil war wasn't a problem. You know, we were much less fortunate. We should appreciate what's left.}
{162}{}{Maybe you can recommend me someone with better stock?}
{163}{}{No one besides me... And police with mormons. But these ones won't be traded with, rather opposite - they buy all the good guns and give me away any kind of pipe trash. [he sniffs] And then they are surprised that I can't sell a damn thing...}
{164}{}{Understood, will keep in mind.}

#Гаусс-патроны
{170}{}{Do you know anything about Sheriff Burton's weapon?}
{171}{}{I know a little. Mostly from an article in "Super-science" magazine. It describes such weapon types.}
{172}{}{What types?}
{173}{}{Operating on the principles of electromagnetic acceleration. The bullet is accelerated by stepwise magnetic repulsion. Such weapons were available only on large military bases and in military engineering laboratories. The sheriff Burton's gun, apparently, is from the military base to the north, which was bombed in 2077.}
{174}{}{About its ammunition - it's just a usual bullet, right?}
{175}{}{Oh no, it's a 2mm metal needle. Sounds simple, but you must really know what to do to make them.}
{176}{}{What's so difficult?}
{177}{}{The magnetic properties of metal, aerodynamics, mass balance... To be clear, it's pure physics and mathematics. If you want to learn, the article has all the necessary info. Just pay 200 bucks for the information.}
{178}{}{All right, here's the money.}
{179}{}{Let's change the topic.}
{180}{}{[You carefully study the excellent article about the Gauss system from the "Super-science" magazine. It seems that with the proper repairing skills, you could easily manufacture ammunition for weapons with electromagnetic acceleration.]}
{181}{}{[End]}

#Female character:
{1110}{}{Hello wanderer! Don't pass by Quok's family business! We are always happy to see new visitors and won't let you go without some excellent goodies! Check out my new weapon stock. Maybe you'll find something fitting your holster.}
{1113}{}{Hey! I just saw someone jumping into your yard! I think it is a thief!}
{1132}{}{Hey, wanderer! Feel free to stop by, there's a question that needs to be solved.}
{1136}{}{You did the right thing by telling me about him. The sheriff's been looking for that weasel for a long time. The town will be safer now. You know, these days people don't help each other for nothing. I don't know why you turned him in, but I'm still grateful. Here's 500 bucks and my favorite gun. Hope you like it.}
