{100}{}{You see a mechanic.}
{101}{}{You see Francis, the mechanic.}
{102}{}{In front of you stands the mechanic of the Nuka-Cola factory.}

{104}{}{Leave me alone!}
{105}{}{Yeah baby! No wonder I'm the best mechanic at the factory!}
{106}{}{Technician was able to restore the on-board computer.}

################################################################
#
# The starting dialogue thread
#
################################################################

{110}{}{A new face? Haven't seen you here before. Well, so many people are passing by here, you can't remember everyone. What do you want?}
{111}{}{I would like to know who you are, for a start.}
{112}{}{Say something already. What is it?}
{113}{}{My name is Francis. I'm a mechanic, everything here is under my service... I mean the Nuka-Cola factory. And there is no need to be formal, I'm a simple man.}
{114}{}{You must be a skillful specialist. Perhaps I have a few questions.}
{115}{}{That's all I wanted to know. Bye.}

{118}{}{Well, well. Wasn't you the one seen around here the day my welder disappeared? I don't want to accuse anyone without evidence, but... (points to one of his eyes, squinting the other) henceforth this eye of mine will follow every step of any visitor in the room. Keep that in mind, just in case.}
{119}{}{Uh...}

#Rejects to repair weapons
{120}{}{Can you upgrade my weapons?}
{121}{}{[Waving his arms] No, no and no again! I have nothing to do with arms and don't want to have! That's a risky business.}
{122}{}{Okay, let's talk about something else then.}
{123}{}{Then you lost a customer. Bye.}

#Vault-Tec devices for the Vault City warehouse
{125}{}{Are you familiar with something from this list of the Vault-Tec technologies?}
{126}{}{Vault-Tec you say? Let me see... I guess all this has something to do with the technology of vaults, that the Vault-Tec company has been building before the war. But in Salt Lake there is only one such vault, deep in the mountains, and it is still locked. However, you don't have to look there. I've also been running across Gas sensors in family shelters built by the Preiser Incorporated.}
{127}{}{Preiser... What?}
{128}{}{Well, you know, before the war, there was another company building vaults for this city, but those were not as large, rather family-oriented, for a few people. There are two hundreds left around the Salt Lake, or maybe more, but almost all got looted or flooded. So, in 60 years after the war, there's almost nothing left in them, except rats and dampness. Still, some of the technology there remain to be found. I remember seeing that some had the Vault-Tec logo. Perhaps the company subcontracted for the technologies it couldn't develop itself.}
{129}{}{All right.}

################################################################
#
# Artesian water filter
#
################################################################

{130}{}{I was wondering, why the artesian water tower is not working? The city doesn't need clean water?}
{131}{}{You are not the only one who has thoughts like this. But, alas - there's a problem with one detail that no one can find. The water cleaning filter. Without it the turbine becomes clogged with sand and will eventually halt. The Factory already tried to order it from the caravans. Probably everyone in Nevada knows about this problem by now, but so far no one has found the suitable part.}
{132}{}{So you are simply need to find this detail?}
{133}{}{Simply? Well, not quite. Even if someone will be able to find it, a feud bordering a civil war might erupt in the city over the right to possess the tower. We all need clean water: the Nuka-Cola factory, municipal government, population, local rich. And everyone will pursue their own goals. So the problem is broader than just finding some part. Talk about it with my boss, Director Skinner.}
{134}{}{Well, thanks for the clarification.}
{135}{}{You was of little use, but thanks anyway.}

################################################################
#
# Reloading Press for ammunition
#
################################################################

#The question about the possibility of creating
{150}{}{Can you make a press for ammo manufacturing?}
{151}{}{Hmm, to made this thing, you see, would be very time-consuming. Perhaps, I would do this, but only for a very good payment. Let's say, 10,000 bucks.}
{152}{}{I'll give 5,000 as a deposit and the rest when the press is ready. Okay?}
{153}{}{It's too expensive!}
{154}{}{I'll be fine without a press for now.}
{155}{}{Well, we're not getting anywhere like this.}

{156}{}{That's fair. But it will take a week, you will have to wait.}
{157}{}{Fine by me. Here is the deposit.}

{158}{}{What?! I'm not going to make a discount over such a time-consuming process!}
{159}{}{I see...}

{160}{}{Very well! Come back in a week with the rest of the money.}
{161}{}{Okay.}

#After the creation
{170}{}{Did you finished it? My press for ammo manufacturing??}

{171}{}{Of course, as promised. But the bucks go first!}
{172}{}{The residual sum, $ 5,000, as agreed.}
{173}{}{Wait, I'll get the money.}
{174}{}{Don't you think that 10,000 is too much? What if I refuse?}

{175}{}{Well, considering your past services to the city, why not?! I will make a discount of 500 bucks, just out of respect.}
{176}{}{Oh, with your other orders I have a lot of opportunities to make profit. You will have your discount, 500 bucks off.}
{177}{}{The connection with such a forward-thinking merchant like you will make me good profits in the future. I will make a discount of 500 bucks, so be it.}
{178}{}{The price is all right. Anyway, you're not the kind of a Salt Lake resident I am willing to do any discounts to.}
{179}{}{Thanks, that's $ 4,500.}
{180}{}{A pity. Then here are $ 5,000, as agreed.}

################################################################
#
# Armor
#
################################################################

#Armor upgrades:
{200}{}{Can you upgrade my armor?}

{201}{}{Oh, in that regard I am a true handyman! With a great pleasure. What kind this time?}
{202}{}{}
{203}{}{Metal armor.}
{204}{}{Leather armor.}
{205}{}{Leather jacket.}

{209}{}{Nothing special today.}

#Leather jacket:
{210}{}{It won't make a good armor, but I can attach armor plates in order to improve protection from mechanical damage. The only drawback is that you won't be able to run as fast anymore.}
{211}{}{Sure. If you bring me the jacket.}
{212}{}{Never mind then.}

{213}{}{}
{214}{}{[Attach armor plates]}
{215}{}{Nothing.}

{216}{}{That will cost you }
{217}{}{ bucks.}
{218}{}{Here is the money and a fortified leather jacket.}
{219}{}{Here is the money and a regular leather jacket.}

#Leather armor
{230}{}{A good choice for the novice traveler, such suit is often requested by the caravaneers. I can add multiple levels of additional protection. The armor will better protect from damage.}
{231}{}{[Strengthen the protection]}
{232}{}{Sure. If you bring the armor.}
{233}{}{Here is the money and leather armor.}

#Metal armor
{240}{}{Yeah, I worked with such armor, too. I may replace some worn out plates and polish it. Will look almost as good as new!}
{241}{}{[Reinforce metal armor]}
{242}{}{[Put extra strengthening on M2]}
{243}{}{[Mirror coating for M2]}

{244}{}{Here is the money and normal metal armor.}
{245}{}{Here is the money and M2 metal armor.}
{246}{}{Here is the money and metal armor M2 with mirror surface.}
{247}{}{Here is the money and reinforced metal armor M2.}

#The end
{290}{}{(After the long work the master brings the finished item and nods approvingly to himself) Good work.}
{291}{}{Well, It's only requires to conduct a practical test.}
{292}{}{Are you sure? Count accurately...}
{293}{}{Something is missing?..}

{294}{}{Take off your armor.}
{295}{}{Oh, sure...}

################################################################
#
# Tokens for Cola vending machines
#
################################################################

#Questions - tokens to cheat with Cola machines:
{300}{}{They say you can stamp round metal plates?}
{301}{}{Sure. Only I can do. What's the diameter?}
{302}{}{As a normal coin.}
{303}{}{Easy, like a  piece of ca... Wait! You think this is cool, smartass!? You'll pay if I catch you doing this! Skinner even appointed a reward for the thieves like that...}
{304}{}{Hey, hey, I didn't do anything wrong yet!}
{305}{}{Yet... Luckily for you. Otherwise me, Skinner and the Sheriff would have schooled you right away! And don't show me these innocent eyes! I know, where these chips will end up. Then the factory technicians get all this rubbish from the machines, and the chief starts questioning me when and for whom I made them. I've had enough! I won't be involved in such "orders" any more.}
{306}{}{Uh, well, do as you wish, old man...}

################################################################
#
# Factory quest on PLC
#
################################################################

{310}{}{The Director gave me the task to repair something called PLC.}
{311}{}{Oh, yes, I've been informed. Here, take this. It's a pretty complicated thing. None of us are good in programming, and that is kind of experience that required here.}
{312}{}{How to fix this?}
{313}{}{Well, you should know better, you are the one getting paid for it, heh. But actually, there are several options. The first is a technician in Las Vegas, which we were told about by the caravaneers. Also the bikers. These guys are crazy about old technology. And if you have the necessary skills yourself - then the entire fee is yours. If anything, the workbench is in the building in front of the office.}
{314}{}{Tell me more about this device. Why is it necessary?}
{315}{}{About the technician in Vegas. Who is he?}
{316}{}{Bikers. How to contact them?}
{317}{}{Okay, going to do the job.}
{318}{}{Great. Wait, there is one more thing - do not tell the locals about the controller. There are some people in Salt Lake, who better off not knowing, that we are restoring automatic systems.}
{319}{}{Why?}
{320}{}{Well, if you want to become a living target, then go ahead. However, in addition to those, who just want to get a profitable order, there are people like our pharmacist, who believe that fixing the factory would worsen already crappy environmental situation in the city. Oh yeah, and the people at the factory wouldn't be as needed as before - at least not as many - since the robots will work in their stead. Understand the subtlety? Then keep your mouth shut, if you don't want to lose the opportunity to earn some.}
{321}{}{All right.}
{322}{}{The Programmable Logic Controller. It is needed for the automatic control of different appliances. Imagine, we can connect to it all the conveyors, actuators, manipulators, sensors, loading cranes and all-everything you need for autonomous work of the factory. People will only walk between the machines, monitor and supervise them in order to avoid accidents.}
{323}{}{Caravaneers told me that there's a guy at the Hoover dam in Vegas, who has exceptional talent in electronics. If true, he is the one who can repair the controller.}
{324}{}{I don't know about this. They usually don't inform you when they are going to the city. Their base is somewhere in another place. Surely, the Sheriff should know, he would've found out everything he could about the guys like them.}
{325}{}{Tell me again about the PLC.}
{326}{}{I managed to fix the controller.}
{327}{}{Really? [run some checks] It really works! Wonderful. Now get it to the Director Skinner.}
{328}{}{All right.}
{329}{}{But wouldn't that mean that part of the workforce will not be needed any more?}
{330}{}{You sound like that nerdy pharmacist. Of course, the Director will be able to fire a few slackers. But not even a half! Even automated machines need monitoring and care. And for this task people are needed. Novadays you can't trust tech much.}

################################################################
#
# Train
#
################################################################

{350}{}{I need to fix this computer. Will you do it?}

{351}{}{[After seeing the device Francis stops and quietly looks at you for some time, not knowing how to answer] What is it? The computer from the train, right? OK, I'll tell it like it is. Locals, including myself, are intimidated by the train depot. Sheriff, Mormons, ghost train, service robots... I have many reasons not to even think about it. My skin is more important than any amount of money.}
{352}{}{What does the Sheriff say?}
{353}{}{The Mormons? How are they related?}
{354}{}{The ghost train? What kind of a fairy-tale it is?}
{355}{}{Robots? At the station?}
{356}{}{Okay, forget my offer, I'll deal without you.}

{357}{}{Sheriff forbade us to go there. He says it is very dangerous. And not without a reason. Once in a while a new rumor appears about the brave men who left there and never came back. I don't know what is happening there and I don't want to know.}
{358}{}{Sheriff has entrusted them with the surveillance of the dangerous territory. Better ask them themselves. They live in the North, near the destroyed part of the city.}
{359}{}{A fairy-tale!? You call it a fairy-tale?! There were the brave ones who tried to ride the train, like on a rodeo, you know. And to what avail? Should one touch its black body and he will immediately be electrocuted to ash! It's not a fairy-tale. Although there are very few of those who actually saw it... And for sure I'm not one of them.}
{360}{}{Service robots, they are repairing the road and the station since the times even before the war. It is difficult to say who or what controls them, but they act together. Those who tried to interfere with them or to go into the danger zone received a portion of plasma in the ass. So they are a real fact, more real than any ghost train.}

{361}{}{You seem to have no trust in me, Francis, why?}
{362}{}{What did you do to earn it? I can't recall you having particularly credible reputation in the city. So if you want to fix the device - go to some other place.}
{363}{}{No, no it's not about you. People say good things about you, some even claim you're a hero. But I'm scared of the Mormons and the Sheriff.}
{364}{}{You shouldn't think that. I have all the right connections to protect both of us. So, will you help me?}
{365}{}{No, wait, don't push me, let me think... You, of course, is able to organize this, but why would I want to expose myself to such risks? Here is the deal, bring me $ 1,000, then we'll quietly try to settle this problem.}
{366}{}{Here's the money and the computer. Get to work, I need the results as soon as possible.}
{367}{}{Well, you know how to gain the trust. Here, take it and don't let anyone see. I don't want any problems hanging over my head.}
{368}{}{Okay.}

################################################################
#
# The car
#
################################################################

{400}{}{Would you believe it, I have my own car! You jealous?}
{401}{}{So, what improvements you can do to my pickup truck?}

{402}{}{[Snorts haughty] And I have my own factory producing Cola. But... Shit, you weren't kidding!? Unbelievable! Let me see, just one look! Nowadays it's a rare thing to find...}
{403}{}{Rare? Hey, wait a minute! So I'm not the only one with the wheels!?}
{404}{}{Of course, you are not! In the past the city was an industrial center, there are lots of working machinery, but it has fallen into disrepair because of the climate and the bombing of the Northern part of the city. From time to time someone finds cars in old garages, launches them and...}
{405}{}{And?!}
{406}{}{And nothing. It's quite a challenge to find proper tires nowadays. After half a century they fell into disrepair. But the main problem is all these kinds of chips and regulators. Even before the war it was difficult to find them, and now it's almost impossible.}
{407}{}{And how many of such lucky guys are in Salt Lake City?!}
{408}{}{Let me count... Hmm... For the past twenty years I've met about a dozen working cars, also the bikes the bikers ride. But we also have other self-propelled machines. For example, cars at the factory.}
{409}{}{I see you have some experience with handling vehicles, so - can you say something about my baby?}
{410}{}{Would love to, just let me touch her sides!}
{411}{}{Let's go, I'll show it to you.}
{412}{}{You should wait until I drive her to the entrance.}

{413}{}{Oh, my God! [clutches his head] It's the ultimate creation of "Chryslus motors"! The most passable all-terrain car I've ever heard of! Damn, now I'm really jealous.}
{414}{}{Yeah! As I said!}
{415}{}{Well, of course, in our times one can be happy to own any working car, but even tech like this has some flaws, which can be worked on.}

{416}{}{Flaws? I see, apparently, you decided to make some money on me!}
{417}{}{I'm curious, what do you suggest?}
{418}{}{Allowing someone to meddle with my car? Hands off! That's my car!}

{419}{}{Of course, of course! As you say. It's just an offer.}
{420}{}{What do you want to offer?}
{421}{}{I'm still not interested in what you were going to offer. I'm leaving.}

{422}{}{Well, although I am a fan of hardware gizmos, I haven't learned to eat them for lunch yet...}
{423}{}{So what's your offer?}
{424}{}{}

{425}{}{Exclusively practical solution: firstly, to cut out the excess metal to reduce the weight of the machine, then to build a new, sturdy frame over the trunk. I have all I need to do this.}
{426}{}{Increasing the capacity of the trunk? That would be great. How much is the costs?}
{427}{}{Well, I'm not interested. I'll be back if I change my mind.}

{428}{}{ And this smelly tent - oh man, yuck! - to the dump!}

{430}{}{Counting with some charge for works it's about }
{431}{}{ bucks.}

{432}{}{I like the price. Here is the money. Now to the work!}
{433}{}{Give me time to think. In case I find somewhere a cheaper solution...}

{434}{}{Francis improved the trunk of your pickup. Now you can place 20% more stuff there.}
{435}{}{Francis improved the trunk of your pickup. Now you can place 40% more stuff there.}

{436}{}{Well, then drive the car to the entrance of the factory, and I will start working.}
{437}{}{I'll go get the car.}

################################################################
#
# Power armor
#
################################################################

{500}{}{What's all that junk on your desk?}
{501}{}{Oh, that's a damn pile of polymers, metals and ceramics with which I can't do a damn thing for a few months already... Why do you ask?}
{502}{}{It looks like parts of a robot...}
{503}{}{In some way, this is a robot. In fact, you're looking at the glory of the former American army - the suit of T-51b power armor. Or rather what's left of it. It was found in the north, among the ruins of the bombed part of the city. Something caused disintegration of the internal power module, which in the end exploded almost entire armor. Little is left in working condition.}
{504}{}{But can it be fixed?}

{505}{}{If someone finds the suitable replacement parts and original blueprints, then of course. But finding them is nearly impossible.}
{506}{}{Hypothetically - where can I get the necessary parts?}
{507}{}{What exactly needs replacing?}
{508}{}{I want to buy the armor in working condition.}

{509}{}{About the power armor. Is it still possible to repair?}
{510}{}{About the power armor.}
{511}{}{We'll talk more about it. Later.}

{512}{}{Hmm, I think on military bases, where else? But all I know about them is only by hearsay. Except there was one to the North, but it has been destroyed by a direct hit of a nuclear bomb.}
{513}{}{So, let me think... First thing - you need blueprints. Next, we need to replace some parts... To be precise, it's the CPU, power module, new helmet, and in addition - new layerы of radiation and gas protection.}
{514}{}{I want it even more! Here's the deal - you will find details, and I'll fix the armor and give it to you. Of course, I would like to get something for myself, in exchange.}
{515}{}{That's the deal then!}
{516}{}{I'll think about it.}

{517}{}{Great. I need to get the blueprints. I don't know where to get them, but I know that one of those bikers from the west has the *working* power armor suit. Perhaps he could share some information with you. Again, I have no idea where those bikers reside. But the Sheriff knows for sure.}
{518}{}{Bikers? How interesting.}

{519}{}{Oh, this is just what was needed! A lot of troubles ahead with finding replacements for the damaged areas of the armored hull, but now, thanks to the blueprints, it will be much easier. This is a great find! Too bad it's useful only for external reconstruction.}

{520}{}{What exactly?}
{521}{}{Let's discuss the first phase of the repairing. What needs to be done?}
{522}{}{Nothing.}
{523}{}{Let's discuss the second phase of the repairing.}
{524}{}{Let's discuss the third phase of the repairing.}

{525}{}{With pleasure! The first thing that needs recovering is the armor's hull. It is not that easy. High quality polymers, cermets and special fasteners were used. I need the blueprints to understand how all of it was previously assembled. The situation with materials is tight, but finding them is still possible.}
{526}{}{I have a broken power armor. Will it be enough to restore the hull?}
{527}{}{I have blueprints of the frame structure!}
{528}{}{Where I can find them?}
{529}{}{The blueprints are needed... Got it. Went to look.}

{530}{}{If I knew, I would have fixed this scrap long ago. But there is one guess, sometimes the bikers come here from the west. One of them is wearing a suit of power armor. Perhaps he could share information.}
{531}{}{I see. Get to go on further searches.}

{532}{}{Oh, this is just what was needed! I could not only use the armor as an archetype to base the restored parts upon, but I can also take the missing parts of the armored layer from it. This is a great find! Too bad it's useful only for external reconstruction.}
{533}{}{Do at least that for now.}

{534}{}{Ready! Looks spectacular, doesn't it? Oh, of course, it's still just a pile of metal. Without the power module there is no sense to try wearing it - too heavy. Let it lay on the table for now, It won't go anywhere.}
{535}{}{Very well. What is next?}
{536}{}{Great. Will continue this another time.}

{537}{}{Now you need to restore the impermeability of the hull. The layers of radiation and gas protections are burned out and the helmet is completely smashed to pieces. I have to replace all of it with something improvised. Write it down, in case your memory fails you. I need: a sealed helmet, a gas-protection suit and an anti-radiation jumpsuit.}
{538}{}{I have a anti-radiation jumpsuit.}
{539}{}{I have a gas-protection suit.}
{540}{}{I have a lab helmet.}
{541}{}{ We have already integrated }
{542}{}{radiation protection}
{543}{}{gas protection}
{544}{}{sealed helmet}
{545}{}{ and }
{546}{}{.}

{547}{}{Ready! We have moved another step forward!}
{548}{}{That's good.}
{549}{}{Great news! The hull is restored. Would be great to celebrate this with a bottle of "Bloody Mary", and yet the most difficult part of work is still ahead. So it's too early to rejoice.}
{550}{}{Good to hear it. And what else remains to be done?}
{551}{}{Great, but let's continue later.}
{552}{}{The most difficult part is recovering an autonomous system. This kind of armor is distinguished by the inclusion of power module, which provides the mobility of the exoskeleton and increases the strength of the wearer. The systems were powered by the internal mini-reactor and controlled by a central processor. All of it was destroyed. We will have to look for replacements, since it's not possible for us to produce things like that from scratch. In addition, I will need the blueprints of the internal structure, otherwise it'll take years to do the analysis on disassembling. Now write down what's needed: an autonomous system, the CPU and blueprints.}
{553}{}{I have the CPU.}
{554}{}{I have an autonomous system.}
{555}{}{I have blueprints of the internal structure of the armor.}
{556}{}{I have a broken power armor. Can it be used?}
{557}{}{I see. Will look for it.}

{558}{}{Oh, yes, this is just what's needed! But I will also need blueprints and an autonomous system.}
{559}{}{Oh, yes, this is just what's needed! But I also need the blueprints and the CPU.}
{560}{}{Oh, yes, this is just what's needed! But I also need an autonomous system and the CPU.}
{561}{}{Oh, yes, this is just what's needed! And I won't even need the blueprints.}

{562}{}{I've got everything you need. So don't be lazy, please - the final stage is ahead!}
{563}{}{So, we have everything needed to finish the work!}

{564}{}{Oh, great! I'm ready to begin the last phase of reconstruction, but there is one controversial point - in fact, until now I worked for free, while you were searching for the necessary parts. So which of us owns the armor now? Admit it, the one who would own it should compensate the efforts of the other.}
{565}{}{How big is this compensation for your services?}
{566}{}{I'll just kill you and finish the armor myself.}
{567}{}{That's a good question. I have to think over it.}

{568} {} {I assess my part of work in a sum of $10,000. Although we can do the opposite - I'll pay $10,000 to you and leave the armor for myself. I will be able to sell it for the better price.}
{569}{}{That's fair. Here are $10,000. Now make an effort and FINISH your work!}
{570}{}{This sum is unaffordable for me. We can discuss this another time.}

{571}{}{Well, I almost envy you, although I got tons of fun and money myself off that work. Things like these are not lying around every corner and you most likely will never come across anything like that anymore... You know, if I were in your place, I'd have given the armor its own name. Like, for example, "Grizzly". What do you think? As for me, it suits well.}
{572}{}{"Grizzly" power armor? That's a great name!}
{573}{}{Shitty name. Its main function is to protect from bullets, the rest doesn't matter.}

{574}{}{But this is none of my business. I would love to see the armor in action. Come on - put it on!}
{575}{}{...}
{576}{}{Hell, it works! It's a miracle!}

{577}{}{I like your offer - I'll take the money and you take your armor.}
{578}{}{Well, I'm already jealous of myself! Looking forward to make big bucks, and I've never had so much fun doing my work. Hmm, you know what I thought - what if I give the armor its own name? Like "Grizzly", for example. What do you think? As for me, it suits well.}
{579}{}{"Grizzly" power armor? That's a great name!}
{580}{}{Shitty name, smartass.}
{581}{}{Hmm... But in any way - thank you, partner. I hope this isn't our last "enterprise" together [he smiles and shakes your hand]. Good luck!}
{582}{}{You too.}

#Womens replica
{1303}{}{Easy, like a  piece of ca... Wait! You think this is cool, smartass!? You'll pay if I catch you doing this! Skinner even appointed a reward for the thieves like that...}
{1304}{}{Hey, hey, I didn't do anything wrong yet!}
{1403}{}{Rare? Hey, wait a minute! So I'm not the only one with the wheels!?}
{1414}{}{Yeah! As I said!}
{1564}{}{Oh, great! I'm ready to begin the last phase of reconstruction, but there is one controversial point - in fact, until now I worked for free, while you were searching for the necessary parts. So which of us owns the armor now? Admit it, the one who would own it should compensate the efforts of the other.}
{1566}{}{I'll just kill you and finish the armor myself.}
