{100}{}{You see a mechanic.}
{101}{}{You see Francis, the mechanic.}
{102}{}{In front of you stands the mechanic of the Nuka-Cola factory.}

{104}{}{Leave me alone!}
{105}{}{Yeah baby! No wonder I'm the best mechanic at the factory!}
{106}{}{Technician was able to restore the on-board computer.}

################################################################
#
# The starting dialogue thread
#
################################################################

{110}{}{A new face? Haven't seen you here before. Well, so many people pass by here, you can't remember everyone. What do you want?}
{111}{}{I would like to know who you are, for a start.}
{112}{}{Say something already. What is it?}
{113}{}{My name is Francis. I'm a mechanic, everything here is under my service... I mean the Nuka-Cola factory. And there is no need to be formal, I'm a simple man.}
{114}{}{You must be a skilled specialist, I might have a few questions.}
{115}{}{That's all I wanted to know. Bye.}

{118}{}{Well, well. Wasn't you the one seen around here the day my welder disappeared? I don't want to accuse anyone without evidence, but... [He points to one of his eyes, squinting the other] from now on this eye of mine will follow every step of any visitor in the room. Keep that in mind.}
{119}{}{Uh...}

#Rejects to repair weapons
{120}{}{Can you upgrade my weapons?}
{121}{}{[Waving his arms] No, no and no again! I have nothing to do with arms and don't want to! That's risky business.}
{122}{}{Okay, let's talk about something else then.}
{123}{}{Then you lost a customer. Bye.}

#Vault-Tec devices for the Vault City warehouse
{125}{}{Are you familiar with anythng on this list of Vault-Tec technologies?}
{126}{}{Vault-Tec you say? Let me see... I guess all this has something to do with the technology that the Vault-Tec company was building before the war. But in Salt Lake there is only one such vault, deep in the mountains, and it's still locked. But you don't have to look there. I've also been running across Gas Sensors in family shelters built by Preiser Incorporated.}
{127}{}{Preiser... What?}
{128}{}{Well, you know, before the war, there was another company building vaults for this city, but those weren't as large, but were rather family-oriented, for a few people. There were two hundred or maybe more in the Salt Lake area, but almost all were looted or flooded. But in the 60 years since the war, almost nothing is left in them except rats and damp. Nevertheless, some technology can still be found there. I remember seeing the Vault-Tec logo in some of them. Perhaps the company subcontracted for technologies it couldn't develop itself.}
{129}{}{All right.}

################################################################
#
# Artesian water filter
#
################################################################

{130}{}{I was wondering why the artesian water tower doesn't work? The city doesn't need clean water?}
{131}{}{You're not the only one who wonders that. But, alas - there is a problem with one part no one can find. The water filter. Without it, the turbine gets clogged with sand and eventually stops. The factory has already tried ordering it from caravans. Probably everyone in Nevada knows about the problem by now, but no one has found the right part yet.}
{132}{}{So you simply need to find this filter part?}
{133}{}{Simply? Well, not quite. Even if someone succeeds in finding it, a feud bordering on civil war could erupt in the city over the right to possess the tower. We all need clean water: the Nuka-Cola factory, the municipal government, the population, the local wealthy. And everyone will pursue their own goals. So the problem is broader than just finding some part. Talk to my boss, Director Skinner, about it.}
{134}{}{Well, thanks for the clarification.}
{135}{}{You weren't much help, but thanks anyway.}

################################################################
#
# Reloading Press for ammunition
#
################################################################

#The question about the possibility of creating
{150}{}{Can you make a press for ammo manufacturing?}
{151}{}{Hmm...You see, making this thing would be very time-consuming. I might do it, but only for a very large fee. Let's say, 10,000 bucks.}
{152}{}{I'll give 5,000 as a deposit and the rest when the press is ready. Okay?}
{153}{}{That's too expensive!}
{154}{}{I'll be fine without a press for now.}
{155}{}{Well, we're not getting anywhere like this.}

{156}{}{That's fair. But it will take a week, you'll have to wait.}
{157}{}{Fine by me. Here's the deposit.}

{158}{}{What?! I'm not going to give a discount for such a time-consuming process!}
{159}{}{I see...}

{160}{}{Very well! Come back in a week with the rest of the money.}
{161}{}{Okay.}

#After the creation
{170}{}{Did you finish it? My ammo manufacturing press??}

{171}{}{Of course, as promised. But the bucks go first!}
{172}{}{The remaining amount, $5,000, as agreed.}
{173}{}{Wait, I'll get the money.}
{174}{}{Don't you think 10,000 is a bit much? What if I refuse?}

{175}{}{Well, considering your services to the city, why not? I'll make a discount of 500 bucks, just out of respect.}
{176}{}{Oh, with your other orders I have a lot of opportunities to make profit. You will have your discount, 500 bucks off.}
{177}{}{A connection with a shrewd merchant like yourself will bring me good profits in the future. I'll give you a $500 discount, all right.}
{178}{}{The price is fine. And you're not one of those Salt Lake City residents I'm willing to give a discount to.}
{179}{}{Thanks, that's $4,500.}
{180}{}{A pity. Then here are $5,000, as agreed.}

################################################################
#
# Armor
#
################################################################

#Armor upgrades:
{200}{}{Can you upgrade my armor?}

{201}{}{Oh, I'm a real handyman in that regard! With great pleasure. What kind is it this time?}
{202}{}{}
{203}{}{Metal armor.}
{204}{}{Leather armor.}
{205}{}{Leather jacket.}

{209}{}{Nothing special today.}

#Leather jacket:
{210}{}{It won't make good armor, but I can attach armor plates in order to improve protection from mechanical damage. The only drawback is that you won't be able to run as fast anymore.}
{211}{}{Sure. If you bring me the jacket.}
{212}{}{Nevermind then.}

{213}{}{}
{214}{}{[Attach armor plates]}
{215}{}{Nothing.}

{216}{}{That will cost you }
{217}{}{ bucks.}
{218}{}{Here's the money and a fortified leather jacket.}
{219}{}{Here's the money and a regular leather jacket.}

#Leather armor
{230}{}{A good choice for the novice traveler, a suit like this is often requested by caravaners. I can add a few extra levels of protection. The armor will better protect against damage.}
{231}{}{[Strengthen the armor's protection]}
{232}{}{Sure. If you bring the armor.}
{233}{}{Here's the money and leather armor.}

#Metal armor
{240}{}{Yeah, I've worked with that armor type, too. I may replace some worn out plates and polish it. Will look almost as good as new!}
{241}{}{[Reinforce metal armor]}
{242}{}{[Put extra strengthening on M2]}
{243}{}{[Mirror coating for M2]}

{244}{}{Here is the money and the metal armor.}
{245}{}{Here is the money and the M2 metal armor.}
{246}{}{Here's the money and the M2 metal armor with a mirrored surface.}
{247}{}{Here is the money and the reinforced metal armor M2.}

#The end
{290}{}{[After long work the master brings the finished item, approvingly nodding to himself] Good work.}
{291}{}{Well, it only requires a practical test.}
{292}{}{Are you sure? Count accurately...}
{293}{}{Something is missing?...}

{294}{}{Take off your armor.}
{295}{}{Oh, sure...}

################################################################
#
# Tokens for Cola vending machines
#
################################################################

#Questions - tokens to cheat with Cola machines:
{300}{}{They say you can stamp round metal plates?}
{301}{}{Sure. What's the diameter?}
{302}{}{As a normal coin.}
{303}{}{Easy, like a piece of ca... Wait a second! You think that's cool, smartass!? You'll pay if I catch you doing this! Skinner even announced a reward for thieves like you...}
{304}{}{Hey, easy! I didn't do anything wrong yet!}
{305}{}{Yet! Lucky for you. Otherwise, me and Skinner and the sheriff would have put you right down! And don't give me those innocent eyes! I know where those chips go. Then the factory techs take all that junk from the machines, and the chief starts questioning me about when and for whom I made them. I'm done! I won't take part in such "orders" anymore.}
{306}{}{Uh, okay, as you wish, old man...}

################################################################
#
# Factory quest on PLC
#
################################################################

{310}{}{The Director tasked me with repairing something called a PLC.}
{311}{}{Oh, yes, I've been informed. Here, take this. It's quite a complicated thing. None of us are good at programming, and that's the kind of experience required here.}
{312}{}{How would I fix this?}
{313}{}{Well, you should know better, you're the one getting paid for it, heh. But actually, there are several options. The first is a technician in Las Vegas, which we were told about by the caravaneers. Also, the bikers. Those guys are crazy about old tech. And if you have the necessary skills yourself - then the entire fee is yours. The workbench is in the building in front of the office.}
{314}{}{Tell me more about this device. What does it do?}
{315}{}{About that technician in Vegas. Who is he?}
{316}{}{Bikers. How do I contact them?}
{317}{}{Okay, going to do the job.}
{318}{}{Great. Wait, there's one more thing - don't tell the locals about the controller. There are people in Salt Lake City who better not know that we are restoring automatic systems.}
{319}{}{Why?}
{320}{}{Well, if you want to become a walking target, go ahead. In addition to those who just want to make a profit off their order, there are people, like our pharmacist, who believe fixing the factory would worsen an already crappy environmental situation in the city. Oh yeah, and the people at the factory wouldn't be as needed as before - at least not as many - since the robots will work in their stead. Do you understand how delicate this matter is? Then keep your mouth shut, if you don't want to lose an opportunity to make some money.}
{321}{}{All right.}
{322}{}{The Programmable Logic Controller, or PLC, is necessary for automatic control of different appliances. Imagine, we connect it to all the conveyors, drives, manipulators, sensors, loading cranes - everything we need for autonomous factory operation. People would only have to walk between the machines, and control and monitor them to avoid accidents.}
{323}{}{The caravan merchants told me that there's a guy at Hoover Dam in Vegas who has an exceptional talent for electronics. If that's true, he can fix the controller.}
{324}{}{I don't know about that. They don't usually tell you when they're going into the city. Their base is somewhere else. Of course the sheriff must know, he'd find out all he could about people like them.}
{325}{}{Tell me about the PLC again.}
{326}{}{I managed to fix the controller.}
{327}{}{Really? [He runs some tests on it] It really works! Wonderful. Now get it to Director Skinner.}
{328}{}{All right.}
{329}{}{But doesn't that mean part of the workforce won't be needed any more?}
{330}{}{You sound like that nerdy pharmacist. Of course, the Director will be able to fire a few slackers. But that's less than half! Even automated machines need control and maintenance. And that requires people. These days, you can't really trust technology.}

################################################################
#
# Train
#
################################################################

{350}{}{I need to fix this computer. Will you do it?}

{351}{}{[After seeing the device Francis stops and quietly looks at you for some time] What's that? The computer from the train, right? Okay, I'll tell it like it is. The locals, myself included, are terrified of the train depot. The Sheriff, the Mormons, the ghost train, the service robots... I have many reasons not to think about it. My skin is more important than any amount of money.}
{352}{}{What does the Sheriff say?}
{353}{}{The Mormons? How are they related?}
{354}{}{A ghost train? What kind of fairy tale is this?}
{355}{}{Robots? At the station?}
{356}{}{Okay, forget my offer, I'll deal without you.}

{357}{}{Sheriff forbade us to go there. He says it's very dangerous. And not without reason. From time to time there are new rumors about brave men who went there and didn't come back. I don't know what's going on there, and I don't want to know.}
{358}{}{Sheriff has entrusted them with the surveillance of some dangerous territory. Better ask them yourself. They live in the North, near the destroyed part of the city.}
{359}{}{A fairy tale!? You call it a fairy tale?! There were brave ones who tried to ride the train, like on a rodeo, you know. And to what avail? Anyone who touches its black body will immediately be electrocuted to ash! It's not a fairy tale. Although there are very few who actually saw it... And for sure I'm not one of them.}
{360}{}{Service robots, they've been repairing the road and the station since the times before the war. It's difficult to say who or what controls them, but they act together. Those who've tried to interfere with them or gone into the danger zone got a helping of plasma up the ass. So they are, in fact, real. More real than any ghost train.}

{361}{}{You don't seem to trust me, Francis. Why?}
{362}{}{What did you do to earn it? I don't recall you having a particularly credible reputation in the city. If you want to fix the device - go somewhere else.}
{363}{}{No, no it's not you. People say good things about you, some even claim you're a hero. But I'm scared of the Mormons and the Sheriff.}
{364}{}{You shouldn't worry about that. I have all the right connections to protect both of us. So, will you help me?}
{365}{}{No, wait, don't push me, let me think... You, of course, are able to organize this, but why would I want to expose myself to these risks? Here's the deal, bring me $1,000, and we'll try to settle this problem...quietly.}
{366}{}{Here's the money and the computer. Get to work, I need the results as soon as possible.}
{367}{}{Well, you know how to gain my trust. Here, take it and don't let anyone see. I don't want any problems hanging over my head.}
{368}{}{Okay.}

################################################################
#
# The car
#
################################################################

{400}{}{Would you believe it, I have my own car! You jealous?}
{401}{}{So, what improvements can you do to my pickup truck?}

{402}{}{[Snorts haughtily] Right. And I have my own Cola factory... Wait, you're not kidding!? Unbelievable! Let me see, just one look! It's a rare find these days...}
{403}{}{Rare? Hey, wait a minute! I'm not the only one with wheels!?}
{404}{}{Of course not! In the past the city was an industrial center, there is a lot of working machinery, but it has fallen into disrepair because of the climate and the bombing in the northern part. Every now and then someone finds a car in an old garage, starts it up and...}
{405}{}{And?!}
{406}{}{And nothing. It's quite a challenge to find the right size tires nowadays. After half a century they fell into disrepair. But the main problem is all these chips and regulators. Even before the war it was difficult to find them, and now it's almost impossible.}
{407}{}{And how many of these lucky guys are in Salt Lake City?!}
{408}{}{Let me count... Hmm... For the past twenty years I've seen about a dozen working cars, also the bikes the bikers ride. But we also have other self-propelled machines. Cars at the factory, for example.}
{409}{}{I see you have some experience handling vehicles, so - can you do something with my baby?}
{410}{}{Would love to, just let me touch her sides!}
{411}{}{Let's go, I'll show it to you.}
{412}{}{You should wait until I drive her to the entrance.}

{413}{}{Oh, my God! [He grabs his head] It's the ultimate creation of "Chryslus motors"! The most passable all-terrain car I've ever heard of! Damn, now I'm really jealous.}
{414}{}{Yeah! As I said!}
{415}{}{Of course, nowadays you should be happy if you own any working car, but even a vehicle like this has some flaws that can be ironed out.}

{416}{}{Flaws? I see! Seems you've decided to make some money off me!}
{417}{}{I'm curious, what do you suggest?}
{418}{}{Allowing someone to meddle with my car? Hands off! That's my car!}

{419}{}{Of course, of course! As you say. It's just an offer.}
{420}{}{What do you want to offer?}
{421}{}{I'm still not interested in what you were going to offer. I'm leaving.}

{422}{}{Well, although I am a fan of hardware gizmos, I haven't learned to eat them for lunch yet...}
{423}{}{So what's your offer?}
{424}{}{}

{425}{}{An extremely practical solution: First cut out the extra metal to reduce the weight of the car, then build a new, sturdy frame over the trunk. I have everything I need to do this.}
{426}{}{Increasing the capacity of the trunk? That would be great. How much would it cost me?}
{427}{}{Well, I'm not interested. I'll be back if I change my mind.}

{428}{}{ And this smelly tent - oh man, yuck! Let's throw it into the dump!}

{430}{}{Together with the fee for my work that's about }
{431}{}{ bucks.}

{432}{}{I like the price. Here's the money. Now, let's do this!}
{433}{}{Give me time to think. In case I find a cheaper solution...}

{434}{}{Francis improved the trunk of your pickup. Now you can place 20% more stuff there.}
{435}{}{Francis improved the trunk of your pickup. Now you can place 40% more stuff there.}

{436}{}{Well then, drive to the entrance of the factory and I'll start working.}
{437}{}{I'll go get the car.}

################################################################
#
# Power armor
#
################################################################

{500}{}{What's all that junk on your desk?}
{501}{}{Oh, it's a damn pile of polymers, metals, and ceramics that I haven't been able to do anything with for months... Why do you ask?}
{502}{}{It looks like parts of a robot...}
{503}{}{In some ways, it is a robot. In fact, you're looking at the glory of the former American army - a suit of T-51b power armor. Or rather what's left of it. This one was found in the north, among the ruins of the bombed out part of the city. Something caused the internal power module to disintegrate, which ended up blowing up almost all the armor. Little was left in working order.}
{504}{}{Can it be repaired?}

{505}{}{If someone finds suitable replacement parts and original blueprints - of course. But finding them is nearly impossible.}
{506}{}{Hypothetically - where could I get the necessary parts?}
{507}{}{What exactly needs replacing?}
{508}{}{I want to buy the armor in working condition.}

{509}{}{About the power armor. Is it still possible to repair it?}
{510}{}{About the power armor.}
{511}{}{We'll talk more about it... Later.}

{512}{}{Hmm, I guess on military bases, where else? But I only know about them from hearsay. Except that there was one in the north, but it was destroyed by the direct hit of a nuclear bomb.}
{513}{}{Let me think... First, we need blueprints. Next, we need to replace some parts... The CPU, the power module, and a new helmet, to be exact. And besides, we'll have to find something somewhere to restore the radiation and gas protection.}
{514}{}{I want it even more! Here's the deal - you find the parts, and I'll fix the armor and give it to you. Of course, I would like to get something for myself in exchange.}
{515}{}{That's the deal then!}
{516}{}{I'll think about it.}

{517}{}{Great. I need the blueprints. I don't know where to get them, but I do know that one of the bikers from the west has a *working* power armor suit. Maybe he will share the information with you. Again, I have no idea where these bikers live. But the Sheriff knows for sure.}
{518}{}{Bikers? How interesting.}

{519}{}{Oh, that's just what I needed! There's a lot of hassle ahead with rebuilding the damaged sections of the armored hull, but now, thanks to the blueprints, it will be much easier. This is a great find! Too bad it's useful only for external reconstruction.}

{520}{}{What exactly?}
{521}{}{Let's discuss the first phase of the repair. What needs to be done?}
{522}{}{Nothing.}
{523}{}{Let's discuss the second phase of the repair.}
{524}{}{Let's discuss the third phase of the repair.}

{525}{}{My pleasure! The first thing that needs restoring is the armor's hull. It's not easy. The construction used high quality polymers, cermets, and special fasteners. I need blueprints to see how it was all assembled before. The materials situation is tight, but it is still possible to find them.}
{526}{}{I have a broken power armor. Will it be enough to restore the hull?}
{527}{}{I have blueprints of the frame structure!}
{528}{}{Where I can find them?}
{529}{}{The blueprints then... Got it. Already looking for them.}

{530}{}{If I had known, I would have fixed this scrap a long time ago. But here's a suggestion: sometimes bikers come here from the west. One of them is wearing power armor. Maybe he will share some information.}
{531}{}{I see. Get to go on further searches.}

{532}{}{Oh, that's just what was needed! Not only can I use the armor as a base, but I can also take the missing pieces of the armor layer from it. This is a great find! Too bad it's only useful for external reconstruction.}
{533}{}{Do at least that for now.}

{534}{}{Done! Looks spectacular, doesn't it? Of course, it's still just a pile of metal. There's no point trying to wear it without the power module - it's too heavy. Let it sit on the table for now, it won't go anywhere.}
{535}{}{Very well. What is next?}
{536}{}{Great. Will continue this another time.}

{537}{}{Now we have to restore the hull's impermeability. The radiation and gas protection layers are burned out, and the helmet is in pieces. We need to replace it all with something improvised. Make a note in case your memory fails you. I need: A sealed helmet, a gas-protection suit, and an anti-radiation jumpsuit.}
{538}{}{I have an anti-radiation jumpsuit.}
{539}{}{I have a gas-protection suit.}
{540}{}{I have a lab helmet.}
{541}{}{ We have already integrated }
{542}{}{radiation protection}
{543}{}{gas protection}
{544}{}{sealed helmet}
{545}{}{ and }
{546}{}{.}

{547}{}{Ready! We've moved one more step forward!}
{548}{}{That's good.}
{549}{}{Great news! The hull is restored. It would be great to celebrate with a bottle of "Bloody Mary", but the hardest part of the job is yet to come. So it's too early to get excited.}
{550}{}{Good to hear it. What else needs to be done?}
{551}{}{Great, but let's get back to it later.}
{552}{}{The hardest part is restoring the autonomous system. This type of armor is distinguished by the inclusion of a power module, which provides mobility to the exoskeleton and increases the strength of the wearer. The systems were powered by an internal mini-reactor and controlled by a central processor. All of this has been destroyed. We will have to look for replacements, since we cannot manufacture them from scratch. In addition, I will need blueprints of the internal structure, otherwise it will take years to do the disassembly analysis. Now write down what I need: an autonomous system, a CPU, and blueprints.}
{553}{}{I have the CPU.}
{554}{}{I have an autonomous system.}
{555}{}{I have blueprints of the internal structure of the armor.}
{556}{}{I have a broken power armor. Can it be used?}
{557}{}{I see. Will look for it.}

{558}{}{Oh, yes, this is just what's needed! But I will also need blueprints and an autonomous system.}
{559}{}{Oh, yes, this is just what's needed! But I also need the blueprints and the CPU.}
{560}{}{Oh, yes, this is just what's needed! But I also need an autonomous system and the CPU.}
{561}{}{Oh, yes, this is just what's needed! And I don't even need the blueprints in this case.}

{562}{}{I've got everything you need. So don't be lazy, please - the final stage is ahead!}
{563}{}{So, we have everything needed to finish the work!}

{564}{}{Great! I'm ready to start the last phase of the reconstruction, but there is one controversial point. So far, I've been working for free while you've been looking for the necessary parts. So which one of us now owns the armor? Admit it, whoever owns it should compensate the other for their efforts.}
{565}{}{How much compensation are you asking for your services?}
{566}{}{I'll just kill you and finish the armor myself.}
{567}{}{That's a good question. I have to think about it.}

{568}{}{I estimate my part of the job at $10,000. We could do the opposite, though - I'll pay you $10,000 and keep the armor. I could sell it for a better price.}
{569}{}{That's fair enough. Here's $10,000. Now put in the effort and complete the work!}
{570}{}{This sum is unaffordable for me. We can discuss this another time.}

{571}{}{Well, I almost envy you, though I've had a lot of fun and made a lot of money from this job myself. You can't find things like that around every corner, and you'll probably never see anything like it again... You know, if I were you, I'd give the armor a name. Like "Grizzly", for example. What do you think? I think it fits nicely.}
{572}{}{"Grizzly" power armor? That's a great name!}
{573}{}{What a shitty name. Its main function is to protect against bullets, the rest is irrelevant.}

{574}{}{Anyway, it's none of my business. I would love to see the armor in action. Come on - put it on!}
{575}{}{...}
{576}{}{Hell, it works! It's a miracle!}

{577}{}{I like your offer - I'll take the money and you take the armor.}
{578}{}{Well, I'm already jealous of myself! Looking forward to make big bucks! Also, I've never had so much fun doing my job. Hmm, you know what I think? What if I give this armor its own name? Like "Grizzly", for example. What do you think? As for me, it fits nicely.}
{579}{}{"Grizzly" power armor? That's a great name!}
{580}{}{That's a shitty name, smartass.}
{581}{}{Hmm... Anyway - thank you, partner. I hope this isn't our last "enterprise" together. [He smiles and shakes your hand] Good luck!}
{582}{}{You too.}

#Women's replica
{1303}{}{Easy, like a piece of ca... Wait a second! You think this is cool, smartass!? You'll pay if I catch you doing this! Skinner even appointed a reward for thieves like you...}
{1304}{}{Hey, easy! I didn't do anything wrong yet!}
{1403}{}{Rare? Hey, wait a minute! So I'm not the only one with the wheels!?}
{1414}{}{Yeah! As I said!}
{1564}{}{Great! I'm ready to start the last phase of the reconstruction, but there is one controversial point. So far, I've been working for free while you've been looking for the necessary parts. So which one of us now owns the armor? Admit it, whoever owns it should compensate for the other's efforts.}
{1566}{}{I'll just kill you and finish the armor myself.}
