{100}{}{You see a boy.}
{101}{}{You see a local boy named Robin.}
{102}{}{You are committing a very low deed by offering a drug to a child. Your soul has become a little darker.}
{103}{}{You're a mean man! You are *very* bad!}
{104}{}{You're a mean woman! You are *very* bad!}
{105}{}{Don't bother me! I'm trying to solve the most difficult puzzle!}

{106}{}{You taught the child to count by proportion. Bravo!}
{107}{}{Stealing a child's personal belongings negatively affects your karma.}

{110}{}{[The boy is thinking hard about something and does not pay attention to you]}
{111}{}{Hey! What are you doing?}
{112}{}{[Leave him]}

{113}{}{[The boy quietly scratches his shoulder and does not pay attention to you]}
{114}{}{Listen here, you little shit! Disrespecting the adults?! I'll beat your ass!}
{115}{}{[Shake him by the shoulder] Hello, young man, do you hear me?...}

{116}{}{Oh! I'm sorry! I got lost in thought! I have a puzzle that makes my brain boil.}
{117}{}{Seriously? Maybe I'll open your skull and take a look?}
{118}{}{Tell me about this puzzle.}
{119}{}{Puzzle? I don't care. Deal with it yourself.}

{120}{}{[Mumbles something] How smart...}
{121}{}{Disrespecting the adults, you brat? Shut your mouth!}
{122}{}{Uh, fine, I'll go.}

{123}{}{Don't yell at me, you started it! Okay?! And you're in *my* house, so - bye-bye! [points at the door]}
{124}{}{Ah, you little smartass shit! Where in the post-apocalyptic world do smart little assholes like you come from...}

{125}{}{You want to solve it too?}
{126}{}{Yeah, tell me about the puzzle!}
{127}{}{No, dummy, I want to prove that I'm cooler than some little shit.}
{128}{}{No, I don't. Bye.}

{129}{}{Well, all right, listen. A caravan trader passed through three cities. In the first, he was charged a quarter of the value of his goods for renting the parking lot. In the second city he was also charged a quarter of what was left on him. In the third city - a quarter of the rest. When he got home, he only had 1,728 bucks, but he couldn't sell anything. So how much did he have at the beginning?}
{130}{}{Well this is easy! I can answer right now.}
{131}{}{Stupid puzzle! Don't they teach you to count? Do you even know how to walk?}
{132}{}{Hmm... You know, I don't care about that right now, so I will stop by later. Bye!}

{133}{}{I knew it - you can't do it...}

{134}{}{Really!? So how much is it?!}
{135}{}{4096}
{136}{}{3840}
{137}{}{3456}
{138}{}{3110}
{139}{}{3024}
{140}{}{Er... I don't now, actually. Let's solve it later...}

{141}{}{[It seems he doesn't believe you] What?! No! That can't be right! It must be 3375!!!}
{142}{}{Is it? No, little one, you're counting it wrong. Does the truth hurts? Looooser!!!}
{143}{}{Are you sure? Well, you probably know better. I'll just leave you alone...}
{144}{}{Hmm, how do you know?}
{145}{}{You must have cheated! Boo!}

{146}{}{That's it! You can't count yourself, so stop talking! I can do it without you! Meeeeh! [He shows you his tongue]}
{147}{}{You little shit, being rude to grown-ups?! I'll teach you some manners, you brat!}
{148}{}{Fine, sorry, I didn't want to upset you. Solve your puzzle. Bye.}

{149}{}{[The boy runs away] Dad! A stranger in the house! Dad!}
{150}{}{Ha, chicken...}

{151}{}{[Mumbles] Ha! Exactly! I finally got it! And look - even better than grown-ups! And I told them! I told them I can!}
{152}{}{You can, you can. Bye.}

{153}{}{That's not true! That's wrong! Caravan merchants gave me this puzzle! So yeah, I will do it without you! Pfffft! [shows you his tongue, spitting]}
{154}{}{Do it then, I need to go save my people. See ya.}

{155}{}{Well, that's what I thought, a quarter equals 0.25, right? So you have to multiply the sum by a quarter and add the remainder. Then you get the second number. That, too, is multiplied by a quarter and then added again. That makes 3375. Isn't that right??}
{156}{}{Nah, you made a mistake. You are counting a quarter from a smaller number, but it first counts from a larger number. There will be a difference, so count through the proportion.}
{157}{}{Not the slightest idea! Perhaps this is too difficult for me...}
{158}{}{You and your tiny brain can not understand this. We'll talk when you grow some balls and stop acting like a girl.}

{159}{}{What do you mean - proportion?!}
{160}{}{Let me teach you...}
{161}{}{Well, you know, this is too hard for you and I don't have time.}

{162}{}{You're lying to me!!!}
{163}{}{No... Uh, fine, let me teach you.}
{164}{}{Think what you want, I don't care. You're just wrong.}

{165}{}{[You explain how to count with variables and calculate proportions - that's a good lesson for a boy.] Thank you, mister! I'm so happy! Now I'm going to be cooler than Jolly Joe! He can't even count his own income. Wait a minute... Here are the vocal nuts - it's like paying for a lesson!}
{166}{}{Thank you. Now live and learn.}
{167}{}{[You explain how to count with variables and calculate proportions - that's a good lesson for a boy.] Thank you, mister! I'm so happy! Now I'm going to be cooler than Jolly Joe! He can't even count his own income. Wait a minute... Here are some pills for cleaning water - it's like paying for a lesson! We don't need them anymore after the city started to get clean water.}

#Æåíñêèå ðåïëèêè:
{1123}{}{Don't yell at me, you started it, not me! Okay?! And you're in *my* house, so - buh-bye! [shows you the door]}
{1148}{}{Fine, sorry, I didn't want to upset you. Solve your puzzle. Bye.}
{1149}{}{[The boy runs away] Dad! A stranger in the house! Dad!}
{1153}{}{That's not true! That's wrong! Caravan merchants gave me this puzzle! So yeah, I will do it without you! Pfffft! [shows you his tongue, spitting]}
{1165}{}{[You explain how to count with variables and calculate proportions - that's a good lesson for a boy.] Thank you, miss! I'm so happy! Now I'm going to be cooler than Jolly Joe! He can't even count his own income. Wait a minute... Here are the vocal nuts - it's like paying for a lesson!}
{1167}{}{[You explain how to count with variables and calculate proportions - that's a good lesson for a boy.] Thank you, miss! I'm so happy! Now I'm going to be cooler than Jolly Joe! He can't even count his own income. Wait a minute... Here are some pills for cleaning water - it's like paying for a lesson! We don't need them anymore after the city started to get clean water.}
