{100}{}{You see a boy.}
{101}{}{You see a local boy named Robin.}
{102}{}{You are committing a very low deed by offering a drug to a child. Your soul has become a bit darker.}
{103}{}{You're mean man! You're *very* bad!}
{104}{}{You're a mean woman! You're *very* bad!}
{105}{}{Don't bother me! I'm trying to solve the most difficult puzzle!}

{106}{}{You taught the child to count by proportion. Bravo!}
{107}{}{Theft of a child's personal belongings negatively affects your karma.}

{110}{}{[The boy is thinking hard about something and does not pay attention to you]}
{111}{}{Hey! What are you doing?}
{112}{}{[Leave him]}

{113}{}{[The boy nervously pulls his shoulder and does not pay attention to you]}
{114}{}{Now listen, you little brat! Disrespecting the adults?! I'll beat your ass!}
{115}{}{[Shake him by the shoulder] Hello, young man, do you hear me?..}

{116}{}{Oh! Sorry! I was stuck in thoughts! I have a puzzle that makes my brain boil!}
{117}{}{Seriously? Maybe I'll open your skull and take a look?}
{118}{}{Hmm, what is this puzzle?}
{119}{}{Puzzle? Hmm, I don't care. Deal with it.}

{120}{}{[Mumbles something] How smart...}
{121}{}{Disrespecting the adults, you brat? Shut your mouth!}
{122}{}{Er, fine, I'll go.}

{123}{}{Don't yell at me, you started it! Okay?! And you're in *my* house, so - bye-bye! [points at the door]}
{124}{}{Ah, you little smartass shit! Where exactly do clever little assholes like you come from in the post-apocalyptic world...}

{125}{}{And you, you want to solve it too?}
{126}{}{Yeah, tell me about the puzzle!}
{127}{}{No, dummy, I want to prove, that I'm cooler than some little shit.}
{128}{}{No, I don't. Bye.}

{129}{}{Well, okay, listen. One caravan merchant walked three cities. In the first he was charged with renting a parking lot for a quarter of the cost of goods. And in the second city they also sought a quarter of what was left on him. In the third city - a quarter of the remainder. When he returned home, he had only 1728 bucks, but he could not sell anything. So, how much did he have at the very beginning?}
{130}{}{But this is easy! I can answer right now.}
{131}{}{Stupid puzzle! Didn't they teach you to count? Figures - do you even know how to walk, at least?..}
{132}{}{Hmm... You know, I don't care about it right now, so I will stop by later. Bye!}

{133}{}{I knew - you can't do it...}

{134}{}{Really!? So how much is it?!}
{135}{}{4096}
{136}{}{3840}
{137}{}{3456}
{138}{}{3110}
{139}{}{3024}
{140}{}{Er... I don't now, actually. Let's solve it later...}

{141}{}{[It seems he doesn't believe you] What?! No! This is not right! It must be 3375!!!}
{142}{}{Is it? No, little one, you're counting wrong. Does the truth hurts? Looooser!!!}
{143}{}{Are you sure? Well, you know better. I'll just leave you alone...}
{144}{}{Hmm, how do you know?}
{145}{}{Well-well, you must've cheated! Boo!}

{146}{}{Like that! You can't count yourself, so stop talking! I will figure it out without you! Booo! [shows you his tongue]}
{147}{}{Oh you little shithead, being rude to adults?! I will teach you some manners, you brat!}
{148}{}{Fine, sorry, I didn't want to upset you. Solve your puzzle. Bye.}

{149}{}{[The boy runs away] Dad! Stranger in the house! Dad!}
{150}{}{Ha, chicken...}

{151}{}{[Mumbles] Ha! Exactly! Finally I understand! And look - better than adults! And I've told them before! I've told them, that I can!}
{152}{}{You can, you can. Bye.}

{153}{}{Not true! There is no answer! Caravan merchants gave me this puzzle! So yeah, I will do it without you! [shows you his tongue, spitting]}
{154}{}{Do it then, I need to go save my people. See ya.}

{155}{}{Well, I thought so, a quarter is 0.25, right? So you have to multiply the amount by a quarter and plus the remainder. Then I will get the second number. That, too, multiply by a quarter and add again. That turns out - 3375. Is it not??}
{156}{}{Nah, you make one mistake. You count a quarter of a smaller number, although at first it counts from the larger. There will be a difference, so count through the proportion.}
{157}{}{Not the slightest idea! Perhaps this is too difficult for me...}
{158}{}{You and your tiny brain can not understand this. We'll talk when you grow your balls and stop being like a girl.}

{159}{}{What do you mean - proportion?!}
{160}{}{Let me teach you...}
{161}{}{Well, you know, this is too hard for you, and I don't have time.}

{162}{}{You're lying to me!!!}
{163}{}{No... Uh, fine, let me teach you.}
{164}{}{Think what you want, I do not care - you're just not right.}

{165}{}{[You are doing a lesson on operations with variables and calculating in proportion - this is a good lesson for the boy] Thank you, mister! I'm so happy! Now I'll be steeper than Jolly Joe! He can not even calculate his own revenue. Wait... Here are some vocas nuts - it's like paying for a lesson!}
{166}{}{Thank you. Now live and learn.}
{167}{}{[You are doing a lesson on operations with variables and calculating in proportion - this is a good lesson for the boy] Thank you, mister! I'm so happy! Now I'll be steeper than Jolly Joe! He can not even calculate his own revenue. Wait... Here are some tablets for cleaning water - it's like paying for a lesson! We do not need them anymore after the city began to make clean water.}

#Женские реплики:
{1123}{}{Don't yell at me, you started it, not me! Okay?! And you're in *my* house, so - bye-bye! [shows you the door]}
{1148}{}{Fine, sorry, I didn't want to upset you. Solve your puzzle. Bye.}
{1149}{}{[The boy runs away] Dad! Stranger in the house! Dad!}
{1153}{}{Not true! There is no answer! Caravan merchants gave me this puzzle! So, yeah, I will do it without you! [shows you his tongue, spitting]}
{1165}{}{[You are doing a lesson on operations with variables and calculating in proportion - this is a good lesson for the boy] Thank you, miss! I'm so happy! Now I'll be steeper than Jolly Joe! He can not even calculate his own revenue. Wait... Here are some vocas nuts - it's like paying for a lesson!}
{1167}{}{[You are doing a lesson on operations with variables and calculating in proportion - this is a good lesson for the boy] Thank you, mister! I'm so happy! Now I'll be steeper than Jolly Joe! He can not even calculate his own revenue. Wait... Here are some tablets for cleaning water - it's like paying for a lesson! We do not need them anymore after the city began to make clean water.}
