{100}{}{You see Beagle.}
{101}{}{You see the sheriff's senior assistant.}

{102}{}{If you are looking for sheriff, he's away on business.}

{110}{}{What brings you here? If you came to see sheriff, he's in his office.}
{111}{}{God, who's this?! Why don't we just shoot him?}
{112}{}{You did the right thing with that thief! Good job!}
{113}{}{The Provo should have been destroyed a long time ago!}
{114}{}{About Gilmore - good job!}
{115}{}{Put away your weapon! Now!}
