{100}{}{You see the sheriff.}
{101}{}{You see Burton "Whip" Hickok, the sheriff of Salt Lake City.}

{102}{}{Excuse me, what is this place?}
{103}{}{I really should do something with education around here if people can't even read the "Sheriff" sign at the entrance...}
{104}{}{Oh, so it's the sheriff's office? And you are...}
{105}{}{I'm the sheriff himself. My name is Burton Hickok, but people sometimes call me "Whip". And to immediately answer the next question: Yes, my ancestor is *that* Hickok. And yes, I bring order with a whip... And a pistol, if necessary.}
{106}{}{Okay, Sheriff Burton, everything is clear.}

#Dialogue start:
{110}{}{So it was you who caught that thief in downtown, at the Quok brothers? You did the right thing. It took me a long time to clean up the city's filth, but still there are bastards trying to turn Salt Lake into a dump. That's why we appreciate every victory of fair justice over lawlessness. On behalf of all of Salt Lake, I thank you for your help. I don't know what your motives were, but I appreciate it nonetheless. By custom I am to give you a fee. $3000 is the amount the merchants would have lost if it had not been for you. Thank you again.}
{111}{}{Wow! That is quite a fee!}
{112}{}{Okay. Take this one to the cell, and we'll let this one go. [He turns to you.] This is my first and last warning, because you're new in town. I don't know what made you do such a dirty thing, but from now on no one is going to be nice to you. [He puts his hand on his gun] Now get out.}
{113}{}{Damn, that was really messed up...}
{114}{}{So you are the elusive ghost? Yes, we've already heard rumors about your "exploits". I don't know why they're looking for you all over the wasteland, but if you make trouble in my town, I'll be the one to rid the world of you. For now, that was just a warning. First and last.}
{115}{}{I understand, sheriff. You don't need to repeat it.}
{116}{}{Talk.}
{117}{}{How's it going, Sheriff?}
{118}{}{I have to tell you something important.}
{119}{}{I need to get going.}
{120}{}{Really? What is it?}
{121}{}{Nevermind, it's actually not that important.}

#Question answer
{122}{}{I was able to get a filter for the artesian tower. Can you tell me who would be the best option to sell it to?}
{123}{}{Could you find an open job position for one particular hobo? No, not me.}
{124}{}{Sheriff, I need some *serious* work. You know what I mean.}
{125}{}{}
{126}{}{Sheriff, there is some nasty business about some dog...}
{127}{}{You know that Merck beats his wife? I can attest to that!}
{128}{}{Merck killed his wife! I saw it with my own eyes!}

#About the tower filter:
{130}{}{To me.}
{131}{}{Uh... May I ask why? I thought the Nuka-Cola factory needed it more, for example.}
{132}{}{That's right. Our city already has problems with healthcare and clean water. The ability to generate a lot of clean water could become a real scourge for the city and provoke a lot of conflicts, if put in the wrong hands.}
{133}{}{What conflicts? Between whom?}
{134}{}{For example, between the general population and the factory. If we give the filter to the city, the factory will suffer a serious loss of profits, which will also affect the jobs. Given that the factory is the industrial base for the city and the main local enterprise, nothing good will come of it. The worse the situation at the factory, the worse the situation for the population.}
{135}{}{Then why not to give the filter to the factory?}
{136}{}{Because the factory will seize the water supply, using it for business and not for the benefit of the population. Many would be outraged by that. I suggest to find a neutral side that would equalize the situation. I'm the sheriff - I'm that side. Sell the filter to me and such problems will be avoided.}
{137}{}{And what price would you pay?}
{138}{}{Ten thousand, I can't get more from the treasury, our city is not that rich. The factory will probably offer you more, but I've already told you how it could end. Think about it.}
{139}{}{Deal.}
{140}{}{I'll think about it and make a decision later.}
{141}{}{It's up to you. But you'd better consider my words.}
{142}{}{Okay.}
{143}{}{Well, you made a wise decision. Here is your money. And... Thank you. Your help to our city will be appreciated.}
{144}{}{No problem, Sheriff!}
{145}{}{You delivered the filter for the artesian tower and it significantly improved the local living conditions.}

#Cola Merchant
{146}{}{I want to report a crime! The merchant in the parking lot sold me irradiated Nuka-Cola.}
{147}{}{Damn, I could smell that something is fishy about that trader! It never occurred to me to check his merchandise for radiation exposure. He probably has serious mental issues, carrying irradiated things around. Well, we have to confiscate and destroy the goods... Thank you for your testimony. This was a timely decision, someone could get hurt.}
{148}{}{You're welcome, Sheriff.}

#About the cleaned up hobo:
{150}{}{For a hobo, huh? Is this about the one that wanders around the trading area? Was about time for him to get himself out of the gutter... Very well, I can give him some job. Not for the soft-handed though, but it will be hard and honest work. Tell him to come to me and we'll talk about it.}
{151}{}{Will do.}

#Gary Gilmore Quest:
{152}{}{There is actually something I'm not capable of doing myself, but I am not sure you would be capable either.}
{153}{}{}

{154}{}{There is actually something I'm not capable of doing myself.}
{155}{}{Interesting. Tell me.}
{156}{}{First a bit of history, so you'd know what hole you're about to stick your nose in. Once there was a civil war in Salt Lake, and the criminal underworld thrived in it. It was a difficult time for the city. I decided not to stand it any longer and deal with the bastards.}
{157}{}{And?}
{158}{}{I knew the approximate number of the perps. So, I took a squad of loyal boys with me and we raided all their hot spots. The captives cracked out and gave away their accomplices. As it turned out, sometimes it is useful to cross the line.}
{159}{}{And?}
{160}{}{We caught every member of the gang and put them on public display in the square. The city learned the lesson well. Most scumbags hung on the gallows for three days. Those who were involved, but did not deserve to die, were exiled from the city. We haven't heard from them in a long time... Until recently.}
{161}{}{So what did they do now?}
{162}{}{We managed to nearly forget that they exist, not counting some occasional deaths on the road southwards. But in the last couple of years we have been hearing more and more about the Provo area - especially the attacks on caravans and travelers. Sometimes these attacks don't make any sense. I think they're trying to get back at us.}
{163}{}{But they don't come to the city?}
{164}{}{They are still too afraid, I think. But apparently they got bored with farming. The gang occasionally does small raids and robberies on the outskirts of the city. But there is a guy who holds the gang together.}
{165}{}{Who?}
{166}{}{Gary Gilmore. The "records" of this offender are so diverse it makes you wonder. For me it is obvious that he is clearly not right in the head. He deserves to die like no other, but - and this is important to me - our city folks must witness his death.}
{167}{}{And what stops you?}
{168}{}{A dozen thugs in the unfamiliar ruins of Provo, where there are traps everywhere. We would lose a lot of men trying to assault them in there. It is much easier to slip in alone. But I need my men here, so I've been looking for a mercenary brave and experienced enough to bring Gilmore back, if not alive, at least to deliver his head.}
{169}{}{A serious job. Is there a serious payment involved?}
{170}{}{For our city, a bounty of $3000 per head is pretty serious. For the living criminal I'll pay twice as much. I advise you to take your time and think carefully about it. Evaluate the situation first, then make a decision.}
{171}{}{Okay, I will do this job.}
{172}{}{I have to think about the offer.}
{173}{}{Enough of this. I'm not actually a mercenary... [leave]}

{177}{}{Gilmore refuses to go back to Salt Lake. Maybe it'll be better if I just put him down?}
{178}{}{I'll be glad of any opportunity to show the city some form of justice, but public hanging is preferable.}
{179}{}{Well, you certainly know better.}
{180}{}{Gilmore is dead. It was the only thing that could be done.}
{181}{}{You think, I will rejoice just by hearing it from you? I need proof, strong and unambiguous. Can you present some?}
{182}{}{Here's his head. You're not going to deny that it's *his* body part, right?}
{183}{}{Unfortunately, no.}
{184}{}{Evidently. And you can be sure the city won't take your word for it. People will whisper, make up stories... Get out from the office and come back only with some evidence!}
{185}{}{[Leave]}
{186}{}{Excellent work! Look at him - so frail in appearance, but so much trouble... We'll put the head on the main square, so the whole city could see and admire the inevitability of fair retribution. As promised, here's $3000 for the job. Thank you, I won't forget this.}
{187}{}{You're welcome.}

{188}{}{So, what's with Gilmore? When is the trial?}
{189}{}{This bastard will get what he deserves, but not immediately. We still have to interrogate him on a lot of issues. Then we'll drag him through the streets of the city, so everyone can see how people like him end up.}
{190}{}{Understood.}
{191}{}{Gary Gilmore and his life of crime is over.}
{192}{}{Excellent work! Many would envy your skills. You didn't just work hard, you saved a lot of potential victims of this maniac. That' s worth double the fee. Here. [hands you $6000]}
{193}{}{Glad to help, Sheriff.}

{197}{}{Sheriff, now that we've dealt with that maniac, do you have any more assignments for me?}
{198}{}{So you think you are tough? Or you just like to take someone else's life for hard cash? Anyway, it's not my business. I am willing to pay a bounty for every head of the rest of the Provo gang. Do not even think to deceive me - we keep a dossier on each of them, with photos and detailed descriptions.}
{199}{}{Okay. I'll think about your offer. See you later.}

#About the dog
{200}{}{As if I don't have enough other problems here... I'm listening.}
{201}{}{A boy who lives across the street here lost his dog and asked me to find her. But... the dog died.}
{202}{}{Let me guess - by your hand, right?}
{203}{}{Yes. But I had to do it! She clearly contracted rabies and attacked me.}
{204}{}{No, the outcast who lives near the artesian tower did it.}
{205}{}{I understand. The city always had rabid dogs. Relax, I will talk with the boy and explain the situation to him. You just stay here and wait.}
{206}{}{To be honest, I am not so sure. I should go and check.}
{207}{}{Excellent!}
{208}{}{No, I'll do it. Since it's my fault, I'd better tell him myself.}
{209}{}{Are you sure? Well, it's up to you.}
{210}{}{I talked to the kid and his family. Everything is fine. You can forget about that incident.}
{211}{}{Thank you, Sheriff!}
{212}{}{And why did he do it?}
{213}{}{Because he eats them!!!}
{214}{}{That's what I thought. To be honest, I'm even grateful. Although we all dislike him, he is ridding the city of stray dogs. However, without direct evidence, there's nothing I can do about it.}
{215}{}{I have the dog tag. I found it outside of his house.}
{216}{}{I have no proof.}
{217}{}{I have no proof, but I witnessed it myself! Isn't this enough?!}
{218}{}{What do you suggest me to do about it? Punish a person on someone else's words? And what if it turns out not to be true and the dog goes back to its owners? How would I look? "The sheriff punishes the innocent!" I don't deal with things this way.}
{219}{}{Then I will go look for evidence.}
{220}{}{Good enough for me. I'll talk to them. Relax.}

# Additional dialogue about Gilmore
{232}{}{Look, sheriff. You're a smart man. If you need someone for some "wet work", this is your chance. I have more than  }
{233}{}{ notches on my gun. You think I can't handle a little local problem?}
{234}{}{Well, you know better.}
{235}{}{You doubt my abilities? Then I don't need your stinking job.}
{236}{}{Sheriff, I have seen a lot during my wanderings and got myself out of a lot of sticky situations. I would really like to help you.}
{237}{}{Hmm. You do look pretty sharp, I don't know about the rest. Well, it's your decision. If you die, don't come screaming at me.}
{238}{}{Hmm, if you really are an excellent shooter, you might be able to stand up for yourself....}
{239}{}{That's great. What is that problem that needs to be solved?}
{240}{}{Sheriff, I do not advise to reject my proposal, if you need "wet work" done. I have }
{241}{}{ dead aliens from Area 51 on my tab, for example.}

#About bikers
{250}{}{Sheriff, they say you know the location of the biker base. Is that true?}
{251}{}{Yes, it's true. And I'm not going to share that information for nothing. First, prove your worth to this city.}
{252}{}{I could give you some cash for the information.}
{253}{}{Don't you think I've already done enough?}
{254}{}{I will consider your words.}
{255}{}{Money? Do I look like a merchant to you?  However... You can make a donation to the city. Around $3000, for instance, would help a lot around here.}
{256}{}{Great, here is my donation.}
{257}{}{Well, now I see you're not one to spit on law and order. Now, as to your problem: Here are the coordinates of Battle Mountain, where one of the biker camps is located. I have not been there myself, so I can only share this information.}
{258}{}{Thank you.}
{259}{}{Hmm. Let me think. Given your reputation in my city, I... }
{260}{}{...am pleased to share the information with you.}
{261}{}{...will not help you.}

# About Merck and family problems
{262}{}{I had suspicions about this for a long time, but I never found any direct evidence. His wife says nothing. Perhaps she is afraid. Still, I can't interfere - it's their private life.}
{263}{}{Really? What if it'll be too late?}
{264}{}{What could I do? If his wife had confessed and asked for help herself... Even so, I don't like to punish a person for someone else's words. It's a small city, there's a lot of gossip and family grudges. Better to stay away from it, believe me. I hope life teaches them to appreciate each other.}
{265}{}{Hmm. Well, if you're so sure about this...}
{266}{}{What?! Damn it! I suspected that it would end badly. But if I had intervened, the problem wouldn't got resolved. You can't simply change people like Merck. Now we bust his ass. Hey guys! Get ready! You wait here until we get back.}
{267}{}{[Wait]}

{268}{}{I got the bastard! He was so hysterical that he didn't even bother to resist and asked for the gallows himself. I suppose, when he sobers up and sleep it off, he will talk differently. What do you think, what to do with him?}
{269}{}{Public hanging! An edification, so to speak.}
{270}{}{Hang him, but not in public. Let this shameful case remain a secret. Nothing could be done about Merck, unfortunately.}
{271}{}{He no longer has roots in the city, maybe it's better to exile him?}
{272}{}{Sentence him to community service under a strict security regime. He needs discipline.}
{273}{}{I do not know, it's up to you.}
{274}{}{You're right. I'll think about the punishment.}
{275}{}{Oh! Thank you for the money!}
{276}{}{Yes, you're right. He lacks discipline. It is a pity that it has come down to this, because he was a promising man. His wounded pride is his doing.}
{277}{}{Well, thank you for reporting it to me. Here's 200 bucks. I hope you will continue to abide order in Salt Lake. All the best.}
{278}{}{Banish him? I already went through this once with the bastards who are now settled in the Provo area. Now they won't ever step a foot in here. I hope Merck will also understand this lesson. }
{279}{}{I agree. This is his personal problem, let it go with him to the grave.}
{280}{}{We have not had a public execution in a long time... Well, it may be worth it to shake up the public a little and to remind everyone how it all began...}

{281}{}{Uh... Sheriff, I already took care of it. Merck is dead.}
{282}{}{Oh, that's how it is! Maybe you also want the sheriff's badge?! Turn around and leave my offices. We don't need the likes of you in our city.}
{283}{}{Uh...}

# Answers about the city
{310}{}{Anything specific?}
{311}{}{Forget it, there's another question.}
{312}{}{Thanks for your answer. Bye.}
{313}{}{More or less alright I guess.}

{350}{}{Some sneak is raiding all the Nuka-Cola vending machines around here. Everyone at the factory is in panic, and we have not a single clue who could do that.}
{351}{}{About Provo. People still don't believe everyone there is dead. News has spread among the caravan traders, but no one wants to go there and check. I hope those damn bastards are really dead.}
{352}{}{Gary Gilmore got what he deserved. May he burn in hell!}
{353}{}{Well, the Nuka-Cola factory got an unprecedented growth. Things are getting better. Though, the better the factory works, the worse the ecology in the city because of all the produced waste. It's a damn unfair situation.}
{354}{}{It seems that the Nuka-Cola factory will soon fall apart. We have to do something about it, eventually. Workers flee in every direction, the production rate drops. However, the people are getting better, since lower emissions from the factory means less harmful substances thrown into the lake. The city becomes cleaner.}
{355}{}{We all noticed that the health matters in the city are getting better. We got way fewer diseases and there is no such crowds in front of toilets anymore. This makes me happy.}
{356}{}{The health care situation in the city has become very bad. It's a real plague. I advise you to beware of direct contact with people and drink cola instead of water.}
{357}{}{All in all, the city is booming. I've never seen such an influx of newcomers before. Apparently, word is already spreading in the wasteland that the city is on its feet - it's a place to make money and have a good time. I hope it stays that way.}
{358}{}{The whole city has gone mad. I barely manage to hold the situation together. People can get feral any moment and tear up me, you or anyone else in their path. We must do something... I don't know what. I do hope we'll figure something out...}
{359}{}{The city lives its ordinary life. The population does not complain, everyone knows their place and somehow get along.}
{360}{}{With the situation in Provo resolved, the city is calm again. Thanks to you, the citizens are no longer afraid to go out at night.}


#Additions about Gilmore and Provo
{370}{}{Here is the batch of heads from Provo, as agreed.}
{371}{}{Well, let's look at them...}
{372}{}{[Next]}
{373}{}{What- are you trying to mock me?}
{374}{}{Oh, come on! What's the big deal, head rolled on the floor...}
{375}{}{Another problem of the city solved. Thank you on behalf of all citizens. Here's your reward, }
{376}{}{ dollars.}
{377}{}{To think how much money one can get for an ordinary head...}

#Reaction to the sheriff of Uranium City
{380}{}{[Seeing your sheriff's badge, he skeptically raises eyebrow] Where did you get that?}
{381}{}{I am the elected sheriff of Uranium City.}
{382}{}{Well, you see, they just gave it to me. I had no desire to take it, but they insisted...}
{383}{}{I heard something about this town from the caravaneers... They mine uranium ore for power plants there, right? Well, it's nice to see that other settlements keep to maintain order by the law. Sit down sheriff, for you I am willing to find more time than usual.}
{384}{}{It is nice to see a friendly representative of the law. Well, let's talk, Sheriff.}
{385}{}{Mm... Well then, hide this trinket in a pocket, until I take it away. *I* am the sheriff here, and nobody except *me* will carry that title within my city.}
{386}{}{Uhm, sure, Sheriff.}

# Ghost Train
{400}{}{Are there any working trains riding through the city lately?}
{401}{}{Ha! Why do you want to know? Are you willing to die that badly? Then you better go to the gallows in the evening. More often then not, there is someone to bid this life farewell.}
{402}{}{Still, there are trains coming through here, right?}
{403}{}{Yes, there is one. Comes in the middle of the night. Rushes through at half speed without stopping, vanishes heading west. They say that sometimes you can hear the soul of the driver playing harmonica. Those who saw the "Ghost Train" silhouette are afraid to cross the tracks. What if it suddenly appears out of nowhere and runs you over?}
{404}{}{Are you serious?}
{405}{}{Quite. Some even tried to jump onto the roof of the wagon, but were burned to ashes by the infernal flames.}
{406}{}{Wow! How often does it drive by?}
{407}{}{Several times per season, heading back and forth. It clearly has a very long track. Must be in need to collect a lot of souls on the road.}
{408}{}{Uh okay, skip the horror part... Do you know its final destination?}
{409}{}{I don't. Some believe that this train makes no stops or turns. Some even swear it can be in different places at the same time.}
{410}{}{Sounds like some drunken nonsense.}
{411}{}{Nevertheless, it exists, whatever it actually is. Half the city has seen it.}
{412}{}{Thanks for the story, but I have to go.}
{413}{}{Sheriff, enough with the fairy tales. You and I both know that the "Ghost Train" is quite material and not much different from an ordinary train...}
{414}{}{Someone sometimes rides the train in the north and west direction. Some people have also seen robots that still maintain the railroad in working order. But who needs it and why, no one knows.}
{415}{}{That clearly means it is real.}

#About Reaper of Souls
{450}{}{Halt! Not one step further!}
{451}{}{Sheriff? Uh... I didn't do anything!}
{452}{}{Look at this, the honesty itself stands in front of me. Answer me, why are you going to the station?}
{453}{}{I've got business there, Sheriff. But it does not concern you.}
{454}{}{And what is it?}
{455}{}{I'm going by train far beyond the city. }
{456}{}{Answer me, damn you! Answer before it's too late!}
{457}{}{Get out of my way! I will not say anything!}
{458}{}{Before it's too late? What are you talking about?!}
{459}{}{Hell, you don't understand what you're getting yourself into! You can't stop him even if you raise your lousy vault against him.}

{460}{}{Have it your way. You will never tell anything to anybody. [Sheriff pulls out his gun]}
{461}{}{(Oops, time to mosey along...)}

{462}{}{What are you talking about?}
{463}{}{No need to act stupid, smart-ass. You know. The Reaper of Souls.}
{464}{}{The Reaper of Souls?}
{465}{}{You heard me right, don't pretend like you didn't. The man in robes.}
{466}{}{Who the hell is he? What does he have to do with me?}
{467}{}{Listen here, stubborn boy. He asked me to stop you, but I don't want to deal with other people's problems. This is my last warning - go back to your city and forget all this. The Reaper won't come for you.}
{468}{}{Heh, I knew it, Sheriff. You're just his bitch!}
{469}{}{Why are you so sure he won't come for me?}
{470}{}{The Reaper is only interested in pure souls. I don't know why. He's been collecting them for a long time.}
{471}{}{Uh... "Pure souls"? Sounds like a bedtime story for kids.}
{472}{}{Ha-ha-ha! Here's our Sheriff and his scary stories! That's hilarious!}
{473}{}{"Pure souls"? You mean people who have not been subjected to mutations, am I right?}
{474}{}{He needs the descendants of those who managed to keep their purity by surviving the Great War in the safe vaults. Our city can no longer provide him with what he wants.}
{475}{}{What does it have to do with your city?}
{476}{}{Why would he need genetically pure bodies?}
{477}{}{Why would he abduct people?}
{478}{}{During the War, Salt Lake survived because of the family vaults. The population emerged from them gradually throughout the decades. But over time, all people here lost their purity.}
{479}{}{Hmm. Apparently, the local ecology in combination with radiation and mutations affected the genetics of population.}
{480}{}{Well, of course. You've got quite a cesspool here. What else could you expect?}
{481}{}{Yes, this city cannot be called clean...}

{482}{}{I do not know what he does with the abducted, but they do not come back.}
{483}{}{Why not to finish off this viper once and for all?}
{484}{}{We have to reckon with his power. He is not just a human, he's a miracle of genetic mutations combined with bionics. He may even be capable of reading your mind.}
{485}{}{Are you seriously saying there is no way to stop him?}
{486}{}{Not in your case. So I warn you for the last time: turn around and go away. The survival of this city is more important to me than your stupid mission.}
{487}{}{Like hell! I will go to the station, whether you want it or not.}
{488}{}{Okay, I'm going back to the city... For now.}
{489}{}{You're wrong. The Reaper of Souls will continue to rampage throughout the wastes. You don't even know his true intentions. How many "pure soul" does he need to reap? What if he won't ever stop?}
{490}{}{I'm sorry, but I *have* to stop you. [The Sheriff pulls out his gun]}
{491}{}{(Oops, time to mosey along...)}
{492}{}{I don't know, and don't want to know. Now turn around and don't come back.}
{493}{}{Hold on, Sheriff! Maybe he's trying to create an army of soldiers to seize the whole wasteland? Your city has already suffered enough, it's time to end this!}
{494}{}{Don't be a fool! What can *you* do against him?}
{495}{}{I'm not so easily intimidated, I've already met him. Believe me, he has a weakness and I'm going to find it.}
{496}{}{You are so naive it dazzles me. Even I had to make a deal with him. There was a time when I had to make a choice to save Salt Lake. Everyone has to pay the price sooner or later. Maybe you'll understand it too, eventually.}
{497}{}{This is a difficult confession to make. But the city is getting up on its feet, isn't it? And the Reaper of Souls will continue to suck its blood until it's dry.}
{498}{}{How are you even going to catch up with him? He's moving on a black superspeed train. You can't even track him or his destination.}
{499}{}{I have the coordinates of the vault where he is stationed. He has the Overseer from my city taken hostage; the Overseer's Pip-Boy has a tracking device in it. I can pinpoint the train's whereabouts. Besides, I already have working transport and I'm armed. The surprise element is on my side, along with my wits and courage. I am fully prepared for it, sheriff!}
{500}{}{I see you are serious... I'm afraid this decision will haunt me for the rest of my life. Go.}
{501}{}{I will not let you down, Sheriff!}
{502}{}{...And I will not put my city in danger by trusting a wimp like you. Don't make me laugh and get out, for all our sakes!}
{503}{}{The path is clear!}
{504}{}{I won't warn you twice.}

#Reaper dead
{505}{}{The Reaper of Souls is dead!}
{506}{}{Dead? I can't believe it... I guess we'll see that in the meantime.}
{507}{}{So what was the deal you concluded with him?}
{508}{}{There was once a very unstable social situation in the city. Criminal parasites flooded the city, even during the day no one felt safe. It was practically a civil war. Then he came along, offered to help bring order. It wasn't an easy decision for me to make.}
{509}{}{What did he demand in return?}
{510}{}{Pure souls. As much as he wanted. At first he demanded them twice a year, then more and more often.}
{511}{}{And you did not try to resist?}
{512}{}{My men have always feared the Reaper of Souls. We just couldn't.}
{513}{}{That decision was so immoral that I will execute judgment upon you by myself. RIGHT NOW!}
{514}{}{Don't blame yourself. Such decision was better than long and bloody struggle with the criminal underworld.}
{515}{}{You're right, everyone has to pay their price eventually.}

# Women's replica:
{1112}{}{Okay. Take this one to the cell, and we'll let this one go. [He turns to you.] This is my first and last warning, because you're new in town. I don't know what made you do such a dirty thing, but from now on no one is going to be nice to you. [He puts his hand on his gun] Now get out.}
{1128}{}{Merck killed his wife! I saw it with my own eyes!}
{1173}{}{Enough of this. I'm not actually a mercenary... [leave]}
{1184}{}{Evidently. And you can be sure the city won't take your word for it. People will whisper, make up stories... Get out from the office and come back only with some evidence!}
{1193}{}{Glad to help, Sheriff.}
{1198}{}{So you think you are tough? Or you just like to take someone else's life for hard cash? Anyway, it's not my business. I am willing to pay a bounty for every head of the rest of the Provo gang. Do not even think to deceive me - we keep a dossier on each of them, with photos and detailed descriptions.}
{1208}{}{No, I'll do it. Since it's my fault, I'd better tell him myself.}
{1215}{}{I have the dog tag. I found it just outside of his house.}
{1236}{}{Sheriff, I have seen a lot during my wanderings and got myself out of a lot of sticky situations. I would really like to help you.}
{1253}{}{Don't you think that I have already tried?}
{1410}{}{Sounds like some drunken nonsense.}
{1451}{}{Sheriff? Uh... I didn't do anything!}
{1463}{}{No need to act stupid, clever-girl. You know. The Reaper of Souls.}
{1467}{}{Listen here, stubborn girl. He asked me to stop you, but I don't want to deal with other people's problems. This is my last warning - go back to your city and forget all this. The Reaper won't come for you.}
{1468}{}{Heh, I knew it, sheriff. You're just his bitch!}
{1494}{}{Don't be a fool! What can *you* do against him?}
{1513}{}{That decision was so immoral that I will execute judgment upon you by myself. RIGHT NOW!}