{100}{}{You see an outcast.}
{101}{}{You see Stapleton.}
{102}{}{You see a lonely one-eyed resident of the slums.}
{103}{}{You see a lone and mysterious Stapleton... Though he mostly resembles a typical beggar.}

#Общие фразы - Common description
{110}{}{[The man you see is of a strong build, with an ugly face, that is missing an eye] That's my home, and here I live. Are you sure you came to the right place?}
{111}{}{Well, usually nobody stops by here...}
{112}{}{Okay, I'm leaving.}
{113}{}{I see...}

#Кто таков - Who are you
{120}{}{May I ask who I am talking to?}
{121}{}{Why'd you need to know? Usually, everybody just turn away from me. And if they do want to get acquainted, it spells trouble. Better just go do your thing.}
{122}{}{But still. Your name is not a secret, is it?}
{123}{}{Wow, you sure are one unsociable fella...}
{124}{}{[For a bit, the outcast is just staring at you with his one eye] They used to call me Mr. Stapleton. Now though, nobody calls me nothing. All they do is telling me to get lost, that's why I just sit here alone and don't go out to town anymore. Nobody comes to visit me either.}
{125}{}{So you did it to yourself, right... Hiding I mean?}
{126}{}{[He seems to think long and hard about the answer] I guess... It's hard to talk to people when they already have a certain opinion of you without ever exchanging a single word.}
{127}{}{Why do they treat you like that?}
{128}{}{Reputation of a former criminal. It was long time ago, when the Nuka-Cola factory had just been opened. I was doing maintenance, and during one unfortunate accident my face had been badly disfigured. That's why people began to avoid me. I fell into a bad pattern of heavy drinking, got involved with a small-time gang and stole a bunch of stuff from that same factory. It was an unstable time for the city, when you could've been jumped by a thug from each and every corner. You know, what's done is done, but people still remember the bad old me. Only the sheriff learned not to judge the others by their past.}
{129}{}{So, the sheriff was able to accept even a former criminal?}
{130}{}{That's right. He's a fair guy.}

{131}{}{Fair guy - cause he tolerates a former felon walking around? It makes me think twice about him.}
{132}{}{It's sad that your life turned out so badly. I'm sorry for making you relive it again.}
{133}{}{Well, I'm just a stranger passing by. Don't have an opinion either way. See ya, Stapleton.}

{134}{}{I'm used to people provoking me like that. So, your attempts are no good here. It's pointless, and I think you should just go and take care of your own business.}
{135}{}{Don't know what makes you say that but thanks for your kind words.}
{136}{}{Sure. Later... Wanderer.}
{137}{}{Bye.}

#Про башню - about the tower
{150}{}{What is this noticeable tower over there?}
{151}{}{A water tower made by pre-war company "Rain Soft". There's a giant tank inside, where artesian water was gathered by submerged pump, to then be dispersed by pressure system to clients, using water pipeline.}
{152}{}{But now it's not used?}
{153}{}{No. All the water was depleted before the Great War. There are lots of people willing to run it, but so far no one succeeded.}
{154}{}{What's stopping them?}
{155}{}{The pump turbine, which pumps the water from the underground, requires a new cleaning filter. No one knows where to get it. So, this gigantic towers stands still and useless. But even if filter would be found, one would have to spend a lot of time to set everything up. Even more than that...}
{156}{}{More than what?}
{157}{}{I'm afraid to imagine the storm rising in a city, about who has right to run the tower. Everyone needs clean water - ordinary people, Nuka-cola facility, various cunning businessmen... Every resident even.}
{158}{}{A tough decision it'll be, for sure. So, where could I find the part?}
{159}{}{[Shrugs] I know Las Vegas has a dam built on Colorado river. I don't know how it functions, but there are plenty of clean water for sure. Even then, if they had the filter, caravaneers would deliver it already.}

#Про собак - about the dogs
{160}{}{How's dog meat?}
{161}{}{Well... Better than tough gecko meat or stinky molerat's.}
{162}{}{And their owners don't mind?}
{163}{}{They don't have owners. It's a stray meat.}
{164}{}{You sure?}
{165}{}{A dog wouldn't run away from a good master. Also, they don't have dog-tags and collars. In Salt Lake, every domestic dog gets one, to prevent accidents. Once upon a time, there was a big trouble with homeless dogs in the city.}
{166}{}{How did it got resolved?}
{167}{}{The Sheriff arranged a raid on them. Big crowd gathered, and also there were no problems with ammo and traps supply. Dogs were used as food then. Everyone got a profit, and also cleaned the city.}
{168}{}{...And so, you're keeping the habit?}
{169}{}{Alright, let's not continue on this.}
{170}{}{Sheriff knows. He's glad I do. He even leaves some ammo for shooting.}
{171}{}{Well, if Sheriff himself encouraged dog-eating, then the situation in city was really crappy. Bye.}
{172}{}{Okay, I believe.}

#Квест на собак - Dog quest
{180}{}{All dogs in the area are dead.}
{181}{}{What, really? Nicely done! Hm... Guess you had to spend some ammo, eh? Here, I've got some spare gunpowder. It's all I can pay with. Now I can sleep at night. Really glad you helped.}
{182}{}{Well, take care then.}

{183}{}{How do you live all alone in such a wild district?}
{184}{}{Living fine. No one crosses me, I don't cross anyone... Except for dog pack. They can be a pain in the ass. Especially at night, when they won't let me sleep. But I go along with them better than with the men...}
{185}{}{Dogs bother you? I can get rid of them.}
{186}{}{You just need to open yourself to the world. Bye.}
{187}{}{That... That would be great. But I kinda have nothing to pay with.}
{188}{}{Can't pay? No problem. I can still help.}
{189}{}{Can't pay? Then I won't bother.}

{190}{}{The whole place is dog cemetery!}
{191}{}{You've found out that the local outcast is a dog eater.}
{192}{}{Ew! What's with that smell?}
{193}{}{The house reeks with dog meat.}
{194}{}{And how should I get it?}

#Починка поезда - repairing the train
{200}{}{You did work on a facility. Can you also handle the train computer systems?}
{201}{}{[Looks back at the door, then he gets up, blocking the window with his back] Where did you get that? From the train depot?}
{202}{}{Well... Yes.}
{203}{}{Do you really care?}

{204}{}{If the Sheriff finds out, you'll get hell of a problems. Depot is a no-go zone, not even talking about bringing anything from there.}
{205}{}{Why such prohibitions?}
{206}{}{I don't care for prohibitions. I just need to repair this device.}

{207}{}{I myself don't know much. But a lot of people died there. Some of them turned into a plasma goo. But I didn't tell you that.}
{208}{}{So do you know how to fix the computer?}
{209}{}{You shouldn't take this too light-headed. You need to be careful, when you talk about the railway. Creepy stuff's going on there.}
{210}{}{Maybe I could fix that computer. But I won't help you. I don't need any more problems for myself in this tight city.}
{211}{}{Hm.}
{212}{}{So you can help me to fix that on-board computer?}
{213}{}{Maybe I could fix that computer. But I wouldn't want crossing the sheriff.}
{214}{}{Trust me, I know what I'm doing.}
{215}{}{Alright, I'll think about it.}

{216}{}{Yes? Hm... I can probably trust you. Okay, listen. Most likely, some not very important but still necessary to function part was taken out of the computer. The sheriff is not a fool to destroy old technologies. If you get the tools for me, I'll try to fix it.}
{217}{}{ And... If you don't mind, a bottle of "Bloody Mary", okay?}
{218}{}{Here's a bottle from Jolly Joe.}
{219}{}{Oh, what a delight! Thanks.}
{220}{}{An ordinary tool is enough, right? Here it is.}
{221}{}{Here's a super tool kit. Take it if you need.}
{222}{}{You're welcome.}
{223}{}{That's alright, thanks. Anything is better than scavenging in ruins.}
{224}{}{Now, can you fix the computer please?}
{225}{}{If I promised, can't go back on my word. Give me the thing, I'll try.}
{226}{}{Here. Don't let me down!}
{227}{}{I'll return with the computer.}

{228}{}{You find they way to fix the train.}

{229}{}{It wasn't an easy task, but device works now. Here, try. [Stares at you for some time silently] It's not just curiosity, right? Where are you heading, if it's not a secret?}
{230}{}{I'm going far. A few days of travel to the north.}
{231}{}{The north? It's a dangerous path. Different nature there, much meanier. Strong winds, cold, the radiation, people don't live there for long. Though, traveling by a train, probably, won't be as dangerous.}
{232}{}{How do you know all this?}
{233}{}{I've rode from north. But in fact, it was a long time ago.}
{234}{}{Rode? On, like, a vehicle?}
{235}{}{Yes, a train. I was a kid. [Something from the memories made him stop in mid-sentence] Though, it's uninteresting stuff. And I don't remember much myself. 'Twas too long time ago. Maybe, everything had changed since then.}
{236}{}{Okay, so long.}

{240}{}{You said your name is Stapleton and you came from the north. Where did you live - in the house or bunker?}
{241}{}{I think it was a bunker. With metal walls. A lot of light and music... Also, red flowers... And a terrible siren.}
{242}{}{Flowers? Probably flowers did grow there...}
{243}{}{Probably?! [he brightens up] So you did find the bunker!?}
{244}{}{Not even a bunker, but a whole big vault. It was hell of a terrible trip, but I managed to survive.}
{245}{}{No, uh, no. Just recalled.}
{246}{}{It is no wonder that these places are well guarded. But what has become of this place now??}
{247}{}{The population left the vault when you were a child. I have a diary of a certain Stapleton. Perhaps, it's your ancestor.}

{248}{}{My god! So many years have passed! I'm starting to remember... Yes! I'm starting to remember! Leave these writings to me! It's very personal!}
{249}{}{How do you pay for the finding?}
{250}{}{Take.}
{251}{}{No! I need them too.}

{252}{}{But I don't have anything... Wait, I can make shotgun ammo or give the components. It's not much... Please, it's so important to me!}

{253}{}{Alright, take it. I give up them for free.}
{254}{}{Good. Give me the components and we're even.}
{255}{}{Craft some ammo and I'll give you the diary.}

{256}{}{It's my memories! That's why I hope you'll change your mind.}
{257}{}{I can't. So long.}

{258}{}{No! Can't drop them!}
{259}{}{Alright-alright, don't worry so much.}

{260}{}{You uncover the secret of the origin of this poor fellow.}
{261}{}{Thank you! It's my memories, and I'll spend time scrutinizing these diaries.}
{262}{}{You're welcome.}

#Female character:
{1110}{}{[The man you see is of a strong build, with an ugly face, that is missing an eye] That's my home, and here I live. Are you sure you came to the right place?}
{1132}{}{It's sad that your life turned out so badly. I'm sorry for making you relive it again.}
{1136}{}{Sure. Later... Wanderer.}
{1243}{}{Probably?! [he brightens up] So you did find the bunker!?}
