{100}{}{You see a labourer.}
{101}{}{You see a dodgy kid. As you continue looking him over, he narrows his eyes and looks back at you.}
{102}{}{Leave me alone!}
{103}{}{Shush!! Wait until I'm back...}
{104}{}{ }
{105}{}{Well, time to get outta here!}

#First dialogue:
{120}{}{What do you need?}
{121}{}{Tell me who you are and what you do here.}
{122}{}{Just looking for someone to talk to. How do you live in this city?}
{123}{}{Hey, do you know what's the problem with Gilmore? And what this Provo is?}
{124}{}{}
{125}{}{I think I confused you with someone else. I'll be going now.}

#####################################################################
#
# First dialogue [before theft]
#
#####################################################################

{136}{}{Ah... You'll like it here then. We've had problems before, but now the city's beginning to get back to its feet. People are getting richer... [winks] So I would suggest sticking around a little.}
{137}{}{Ah... Well I'd get outta here if I were you. To Vegas maybe. To be honest, things here are shit. The only reason I'm still here is because I can't stand the wastes even more.}
{138}{}{Ah... Just a city, I guess. Nothing special. People are just living here, that's all. Still better than in Reno, that's for sure. I ran away from there, and think I've made the right choice.}
{139}{}{Alright, forget it.}
{140}{}{Well, everyone calls me Incorrigible Ned. Don't ask me why. I'm just a worker, like many others. Help people out with their junk, earning the odd dime here and there. Although there are times when I do rather... "profitable" jobs... [winks] Either way, I'm not complaining.}
{141}{}{Provo's a shithole that nobody in their right mind should visit. That's where all the exiles that the sheriff booted out of town live. Most of the people here will tell you they're all criminals, but it's more than that. I hear that they helped Burton sort things out during the civil war. And then he showed them the door, when they were no longer needed. Now they don't show their faces in Salt Lake, but I wouldn't put it past them to hold a grudge against the whole world. And Gilmore's just a bastard. Murderer, rapist and thief. Whip wants to send people after him, but I think he's scared that they'll get iced on the way there.}
{142}{}{Well, everyone calls me Incorrigible Ned. Don't ask me why. If you want to know, I'm looking for... "enterprising" individuals for some easy work. Hm, you don't quite look the type.}
{143}{}{Well, everyone calls me Incorrigible Ned. Don't ask me why. If you want to know, I'm looking for... "enterprising" individuals for some easy work. Don't think you need it though - you got yourself a good place in this city already.}

#####################################################################
#
# Getting convinced to steal
#
#####################################################################

{149}{}{Hold on! You know, you look like quite the sly bastard. You know what I'm talking about? [winks]}
{150}{}{[Open your eyes in surprise] I have no idea what you're talking about!}
{151}{}{Oh, so you noticed my hidden talents. Then we could find a... Common interest, don't you think?}
{152}{}{Err, you know what, I don't like what you're implying. I think I'm just going to go now...}

{153}{}{Okay, no problem. Forget I said anything.}
{154}{}{Wait, *what* did you want to say?}
{155}{}{Much better.}
{156}{}{}

{157}{}{Is that so? What about this? [pulls a coin out of your pocket that you're seeing for the first time in your life] I saw you! You just tried to pickpocket me!}
{158}{}{What the... This is a fucking setup!}
{159}{}{Shit, you got me man. Yeah, I'm a thief. Question is, what do we do now?}
{160}{}{Yeah, yeah. I get it. But you know... I don't blame you.}
{161}{}{Oh, how honest! But you know... I don't blame you.}
{162}{}{What, seriously?}
{163}{}{Fucking swindler! Get out of my way!}

{164}{}{You see, I'm also... Opportunistic, like you. [winks again]}
{165}{}{Well... Perhaps.}
{166}{}{Of course, I think we could easily find a common interest.}
{167}{}{Great.}
{168}{}{I knew it! We're masters of the same art. And, speaking of art... Anything on your mind?}
{169}{}{No-no, forget it! I quit and all that. Bye.}
{170}{}{Hmm, I'm interested. Tell me more.}

{171}{}{[Without a word, he nods at the building across the street]}
{172}{}{You're crazy!}
{173}{}{Good choice!}
{174}{}{There's an inner yard. I wonder why the traders piled it with junk? I think it's to stop thieves from getting in. What do you think... Could a *thief* get in?}
{175}{}{Hm. What's the catch?}
{176}{}{Maybe... I don't know.}
{177}{}{Straight to the point? I like it. Let me explain everything.}
{178}{}{Of course.}
{179}{}{Hmph... You newbies always need the basics explained. I'll try and make it quick.}
{180}{}{Who're you calling a newbie? Although... I'd better hear you out.}

{181}{}{First of all, getting inside alone will be very hard, we'll need to get in over the fence and then drag stuff across the other side. That means we need another person to support and keep a lookout.}
{182}{}{Right. And secondly?}
{183}{}{The road across is always patrolled by a damn cop. We'll need to figure out when we're out of his sight. That's why two people are needed.}
{184}{}{Got it...}
{185}{}{There's another problem. We'll need to act at night, but the street is lit up by the lamps. A huge risk, if you include the cop. Something should be done about that.}
{186}{}{What do I need to do?}
{187}{}{Try and do something about that street-light. Meanwhile, I'll keep an eye out on the situation and work out the finer details of the plan.}
{188}{}{I like the way you're thinking! I'm with you!}
{189}{}{Great. See you in the evening.}
{190}{}{Bye.}

#Heist beginning
{191}{}{Shh! There's still to many people in the streets. Too dangerous.}
{192}{}{Alright, I'll come later.}
{193}{}{Looks like a good time to make our move. What do you think?}
{194}{}{I'm ready! Let's show these fat cats what's what!}
{195}{}{Not yet, we should wait a bit longer.}
{196}{}{You decided to take the thieving job. Your first objective - get to the trading center courtyard.}

{197}{}{Hold on, I wanna grab a smoke.}
{198}{}{You arrived to the potential thieving spot.}

#####################################################################
#
# Doing the deed
#
#####################################################################

#Floating dialogue when trying to talk during the job:
{200}{}{Slow down. Act like you're coming home after work.}
{201}{}{Relax, the cops feel it when you're tense.}
{202}{}{Just watch the road, partner}

#Traders are dead
{205}{}{What a coincidence, the traders got geeked just when we decided to... You know.}
{206}{}{Err... I have no idea! Must be a coincidence.}
{207}{}{I thought it'd be easier if they weren't around.}
{208}{}{What the hell is wrong with you!? Oh god! We're doomed now. I want nothing to do with you anymore. That's it [crosses arms across chest] - I don't know you.}
{209}{}{You're acting like you ever did. Now, out of my way, loser.}

#Floats when waiting for PC in the courtyard [male char]?
{210}{}{Ah shit! Where's that asshole!!!}
{211}{}{If he doesn't come out...}
{212}{}{Come on! Come out already!}
{213}{}{What is this - a setup?}
{214}{}{Argh! Where's that fucker!?}
{215}{}{Is this a setup?}
{216}{}{Well, shit!}
{217}{}{Where'd he go?!}
{218}{}{I knew I couldn't trust him!}
{219}{}{Hey you! I don't wanna go to prison!}

#Getting boosted over the fence:
{220}{}{Stop wasting time! I need you to boost me over the fence. Got it?}
{221}{}{Let's go.}
{222}{}{Not yet, we could be seen.}
{223}{}{Okay. Wait for me. I'll be back.}

{230}{}{Let me know when we can go, okay?}

#####################################################################
#
# Finishing the job
#
#####################################################################

#Finishing the job, when standing near the fence
{300}{}{It's done. Help me outta here!}
{301}{}{Are you sure? What if I just leave you here?}
{302}{}{Of course, let's book it.}
{303}{}{No, hold on, too dangerous.}
{304}{}{You're bluffing! Don't forget that I have all the loot. Leave me here and you're getting *nothing!*}
{305}{}{You're right, let's get out of here.}
{306}{}{And yet I'm going now...}
{307}{}{Ughh... Alright, hold on. What do you want?}
{308}{}{I want 75%.}
{309}{}{What!? Pfft! Fuck right off! I'll get out without your help! You won't even have time to call anyone and I'll be gone!}
{310}{}{Right. We'll see about that.}
{311}{}{You know, I think I feel pity for you. Let's get out of here.}
{312}{}{Ugh you... Want to skin me and keep your hands clean? Shit, you can choke on your extra cut, just help me out!}
{313}{}{That's much better. Let's go.}
{314}{}{You'll have to wait. It's dangerous.}
{315}{}{I'm leaving anyway. Bye.}
{316}{}{Yeah, well fuck off! I can handle myself without your punk-ass!}
{317}{}{We'll see...}

#End of quest
{320}{}{Phew! I thought I was gonna get caught there. What about you? Nothing happened? Great. Shit, I think it's about time to finish with this business... Alright, let's share this stuff and go our ways. Now, the money, your share - }
{321}{}{ percent. What about the goods?}
{322}{}{Let's see what Lady Fortune gave us.}
{323}{}{You pulled off a grand heist in the middle of the city.}
{324}{}{Good, I agree. I doubt the traders will figure out they've been hit any time soon. Although I'd suggest laying low anyway. Oh yes - we don't know each other and were in different places this evening. Got it?}
{325}{}{Got it. Take care, partner.}

#Thief's floats inside the store
{330}{}{Oh my god!}
{331}{}{O-o!!!}
{332}{}{And all this! For me!}
{333}{}{Heh-heh-heh!}
{334}{}{Fucking tight-asses!}
{335}{}{Learn to share!}
{336}{}{What was yours is now ours}
{337}{}{So much stuff!}
{338}{}{Mhmm!}
{339}{}{Well-well! What have we here!?}
{340}{}{Right... Don't need this... That's not it...}

#Caught by cop
{350}{}{You failed the grand heist!}
{351}{}{Well-well, back to the old stuff?}
{352}{}{Err, whoops chief! Sorry we didn't invite you...}
{353}{}{You can apologize to the sheriff.}
{354}{}{Why did I decide to do this!?}

#Splitting profits
{360}{}{Show me what you got.}
{361}{}{[Continue]}
{362}{}{WHAT!? Don't you think it's a bit much? What happened to percentages?! Right, hand it over! Now! I didn't risk my ass for nothing...}
{363}{}{[Continue]}
{364}{}{Yeah, this seems fair to me. I can live with this.}
{365}{}{Then it is decided. Pleasure working with you.}
{366}{}{No, hold on, I need to think this through.}
{367}{}{Take it all. I don't need any of that junk.}

#####################################################################
#
# After theft
#
#####################################################################

#First dialogue after success:
{400}{}{[You see your old acquaintance, he's barely standing thanks to so much drink] He-e-e-e-y! Partner! Sit down!}
{401}{}{[Join him]}

{402}{}{Well, partner? WE DID IT! You hear me!? WE DID IT, ha-ha!}
{403}{}{Yeah, I hear you. Do you want everyone else to hear you too?}
{404}{}{Uh-huh. And I see you already managed to blow half of your share.}
{405}{}{Now what?}
{406}{}{Big deal. Take care, partner.}

{407}{}{[He's still a little drunk] Ah, partner. Hey, everyone, this is my partner! We did such THINGS together!}
{408}{}{You want everyone to hear?}

{409}{}{Chill, everything's fine! [moves his fingers across his lips] Silent as a grave. Tee-hee.}
{410}{}{I see you managed to blow everything here...}
{411}{}{What are you planning to do now?}
{412}{}{Well, take care.}

{413}{}{Who, me? Not a chance! Unlike someone, I chose the smart option. I stashed mine away for a rainy day. This? Just a little change to calm the nerves. Heh-heh...}
{414}{}{Stash? You sure nobody will find it?}
{415}{}{[Makes a stoically calm face and moves his hand] NOBODY!}

{416}{}{Ah, sounds like the right thing to do. What're you gonna do now?}

{417}{}{[Wipes droplets of beer from his chin] Err... You see, it's not safe in the city. They could... You know? [winks] Hickok's quite the scumbag. He'll shake everyone up if he needs to. So, I don't even know, I'll lie low for a while - the money should make me last. I'll figure things out later. Not to mention I've always had a good income from the glassware "business". Get me? [winks]}
{418}{}{Glassware?! Are you serious?!}
{419}{}{Well, I'm not interested. Tell someone else, I'm out.}

{420}{}{Hell yeah!}
{421}{}{Bullshit! You? Glassware?! How?}
{422}{}{How? Ah, you know, there's many ways. For example, walk up to a Nuka-Cola vending machine...}
{423}{}{Err... Why the vending machine? I don't think I get you...}
{424}{}{No-no, listen here! Nobody else will teach you!}
{425}{}{Uh, sorry. Keep talking, I'm interested.}
{426}{}{So, you go, all quiet-like. Almost like you're hungover so nobody suspects a thing. Then, just reach into you pocket and... Pull out this... Err... Round thing and stick it into the slot.}
{427}{}{Don't you put coins there...}
{428}{}{Yeah! That's the thing! Instead of a coin... [looks around, making sure nobody's listening] take the metal thing, stick it into the machine and, voila! A free bottle just for you!}
{429}{}{Sneaky! Where can I get these "things"?.}
{430}{}{Well, that's your problem. I already used most of mine. Actually, any tech whose hands aren't growing from his ass can stamp out a thousand for you. Unless he figures out what they're for. Although... There's another method.}
{431}{}{Another?! Speak then!}
{432}{}{Heh! Just like that?}
{433}{}{Come on, don't hold back from your partner. You were gonna tell me anyway. So spill it!}
{434}{}{[Gulps down beer] Hrmm... Fine, I'll tell you. Actually, no, I won't. [pulls something out of his pocket] Here.}
{435}{}{What?! A coin with a hole and some rope? Are you serious?}
{436}{}{Uhuh. Stick the coin in the slot. The machine works, you grab the bottle and then pull the coin right back up! [grins like he was just appointed governor of the state]}
{437}{}{What if it gets stuck?}
{438}{}{Eh, it happens. But it's not like it's a huge loss.}
{439}{}{You're like a walking goldmine, friend!}
{440}{}{Oh yeah, I am... Speaking of, you can keep it! I'll make more. Now, I think I need to land face-first into this salad and get a few hours of sleep.}
{441}{}{Thanks for sharing your experience.}
{442}{}{Heh, bye now, idiot. Shouldn't be throwing experience around just like that. Heh.}

#Female version:
{1122}{}{Just looking for someone to talk to since I'm new in town. How do you live in this city?}
{1125}{}{I think I confused you with someone else. I'll be going now.}
{1149}{}{Hold on! You know, you look like quite the sly bitch. You know what I'm talking about? [winks]}
{1157}{}{Is that so? What about this? [pulls a coin out of your pocket that you're seeing for the first time in your life] I saw you! You just tried to pickpocket me!}
{1159}{}{Shit, you got me man. Yeah, I'm a thief. Question is, what do we do now?}
{1169}{}{No-no, forget it! I quit and all that. Bye.}
{1220}{}{Quit wasting time. I need you to boost me over that fence. Understood?}
{1360}{}{Well-well, let's see what you've got.}

#Floating dialogue when thief waits in courtyard [fem char]
{1210}{}{Ah shit! Where's that bitch!!!}
{1211}{}{If she doesn't come out...}
{1212}{}{Come on! Come out already!}
{1213}{}{What is this - a setup?}
{1214}{}{Argh! Where's this bitch!?}
{1215}{}{What's this, a setup?}
{1216}{}{Well, shit!}
{1217}{}{Where's she gone?!}
{1218}{}{I knew I couldn't trust her!}
{1219}{}{Hey, you! I don't wanna go behind the bars!}

{1354}{}{Why did I decide to do this!?}
