{100}{}{You see the organizer.}
{101}{}{You see the organizer of hanging events.}

{102}{}{I'm busy now. Let's talk after the event.}
{103}{}{You have been... Hanged.}
{104}{}{You gain a new achievement.}

#Ñòàäèÿ 1: Îáúÿâëåíèå ïðåñòóïëåíèÿ
{110}{}{Ladies and gentlemen!}
{111}{}{Today something exciting will take place here!}
{112}{}{Right before your eyes... Justice will be done!}
{113}{}{This person stole grandma's apple pie!}
{114}{}{Such a crime is unforgivable!}
{115}{}{A grieving grandmother caught the criminal, and now he's HERE!}
{116}{}{We'll see what happens to people who steal grandma's pies!}
{117}{}{He'll twitch in agony, suspended 30 inches above the ground!}
{118}{}{He should remember this lesson and will never do such things again!}
{119}{}{Do you want that?!}
{120}{}{Do you REALLY WANT that, dammit?!}
{121}{}{For grandma!}
{122}{}{For the pie!}
{123}{}{For justice in Salt Lake City!!!}
{124}{}{Long live the Sheriff. And long live Salt Lake!}
{125}{}{But first, let's hear the criminal's last words...}

#Ñòàäèÿ 2: Ñëîâî âèñåëüíèêà
{150}{}{Well, what can I say!}
{151}{}{Yes, I am a bad man, I stole grandma's pie...}
{152}{}{I confess!}
{153}{}{I'm glad that our city never sleeps and no criminal will avoid its justice!}
{154}{}{But honestly! I admit my mistakes! I won't do it again!}
{155}{}{Yes, I used to steal grandma's pies in the past...}
{156}{}{... And not just pies!}
{157}{}{I even stole... Oh! I'm ashamed to admit...}
{158}{}{No! I won't hide it!}
{159}{}{I stole her heel massager and hid it far away from the city!}
{160}{}{Now I repent!}
{161}{}{I'm ready to surrender to justice, because it's true!}
{162}{}{I believe in our Sheriff!}
{163}{}{After the hanging I'll *never* walk this path again!}
{164}{}{I swear!}
{165}{}{And I hope no one else will.}
{166}{}{::nods to the executioner to start::}

{200}{}{Did you hear that? How will he live after what he said?}
{201}{}{Now we *must* put an end to his suffering!}
{202}{}{String him up!}
{203}{}{mommy}
{204}{}{Thank you all, you're free to go.}
{205}{}{Actually, it was awesome! We should do it again.}
{206}{}{Still, I've been hanged! I knew this would happen.}

{210}{}{Did you hear that? How could she live after what she said?}
{211}{}{Now we *must* end her suffering!}
{212}{}{Hang her!}

#Äèàëîã
{300}{}{What do you want?}
{301}{}{What the hell is going on here?!}
{302}{}{Oh, apparently you're a stranger. Relax. That's how our folks have fun.}
{303}{}{Fun?!}
{304}{}{Yes. We used to actually hang criminals here. Just a while ago. But since Sheriff Burton dealt with the criminal underworld and kicked all those bastards out of town, the gallows was empty and the folks in town got bored.}
{305}{}{And? Couldn't you come up with anything better?}
{306}{}{That's the point! The city is generally pretty boring. And the gallows is a real outlet.}
{307}{}{And who plays the role of the hanged man?}
{308}{}{The folks themselves step up onto "the podium". They think it's fun. Sheriff Burton says that confession for crimes they did not commit helps to clear the mind from dirty thoughts.}
{309}{}{And? Does it?}
{310}{}{I guess. The more I live in this town, the less I worry about crime. But the credit for this goes, of course, not to our performances, but to the Sheriff himself.}
{311}{}{But doesn't it scare the newcomers?}
{312}{}{It does. And that's good. The city stays calmer without any "unwanted elements".}
{313}{}{Hmm. Can I play the role of the hanged man?}
{314}{}{This is all strange somehow. I have to go.}
{315}{}{What?}
{316}{}{Yes! I want to be on your show!}
{317}{}{Nevermind... Nothing.}
{318}{}{Hmm. Interesting. YOU want to be hanged? Fine. The more shows, the better. But we hold only one show per person. So you won't be able to do this again.}
{319}{}{Great! Let's start!!!}
{320}{}{Actually, I changed my mind... Uh... I can do without hangings.}
{321}{}{[to the executioner] Okay here, take this one to the podium. He's new in town, so don't go easy on him.}
{322}{}{WHA... Ow! Let me go!!!}

#Female character:
{1206}{}{Still, I've been hanged! I knew this would happen.}
{1320}{}{Actually, I changed my mind... Uh... I can do without hangings.}
{1321}{}{[to the executioner] Okay here, take this one to the podium. She is new in town, so don't go easy on her.}
