{100}{}{You see a spectator.}
{101}{}{You see a simple spectator.}
{102}{}{Wait, the fun has just begun!}

{110}{}{Yes, hang him already!}
{111}{}{Enough!}
{112}{}{Give us some meat!}
{113}{}{Brutal justice...}
{114}{}{End it!}
{115}{}{Hahaha!}
{116}{}{Get on with it!}
{117}{}{Well? How much longer!?}
{118}{}{Let's begin!}
{119}{}{We heard this already.}
{120}{}{I would come up with something new.}