{100}{}{You see a manhole.}
{101}{}{You see an automated manhole.}
{102}{}{You see an automated manhole with a grate that prevents anyone from going inside.}

{103}{}{Alas, the manhole is jammed, you won't open it the usual way.}
{104}{}{Needs repair.}
{105}{}{There's no lock to pick.}
{106}{}{This manhole does not need repairs.}
{107}{}{With your bare hands you will not be able to repair this installation.}
{108}{}{You need a specific tool.}

{109}{}{Your skills are insufficient for repair.}
{110}{}{Yes!}
{111}{}{Something went wrong. Maybe next time.}
