{100}{}{Vending machine is out of order.}
{101}{}{}
{102}{}{You can't get anything out of this machine only with bare hands.}
{103}{}{It's empty.}
{104}{}{You've already ransacked this vending machine and taken all the change out of it.}
{105}{}{Can't do anything here.}
{106}{}{Good thinking, but you won't be able to break the register of such a sturdy machine only with your bare hands.}
{107}{}{You managed to pick the lock and open the back cover of the machine. Now all the change is yours!}
{108}{}{Yes!}
{109}{}{You failed to pick the lock.}
{110}{}{Using tools, you managed to open the back cover of the machine. Now all the change is yours!}
{111}{}{You've acquired }
{112}{}{ bucks.}