{100}{}{Not in combat!}
{101}{}{You look up doubtfully, to where the water drips and the sky faintly shines through the small windows. The spiraling staircase goes into darkness, and you can't even see the end of it. It's a heck of an artesian tower! Climbing to the top of it will take a lot of energy.}
{102}{}{I'll fall powerless if I don't rest.}
{103}{}{Climb up, risking your health.}
{104}{}{Exit.}

{105}{}{Ugh! What a view! Is Salt Lake really so dirty?!}
{106}{}{You are on top of an inoperable artesian tower. The view from here is spectacular.}
{107}{}{Panoramic view from the top of the tower temporarily sharpens your perception.}