{100}{}{You see an empty newspaper vending machine.}
{101}{}{You see a newspaper vending machine. It has something in it.}
{102}{}{Nothing here.}
{103}{}{There is something inside, but the cover is too tight to open with your bare hands.}

{104}{}{You swing wasn't strong enough to remove the cover.}
{105}{}{You swing was good enough to bash the cover off.}
{106}{}{Done.}
{107}{}{Using the tools you unscrewed the cover.}
{108}{}{Done;}
{109}{}{Using the master key, you open the lock on the cover.}
{110}{}{Done}
{111}{}{Alas, you could not open the lock.}
{112}{}{Alas, you cannot open the lid.}
{113}{}{It won't help here.}
{114}{}{Useless.}
{115}{}{No use - the lid is already open.}
{116}{}{You find 50 bucks and take them.}
{117}{}{It's amazing it still has money in it...}