{100}{}{You see tanks.}
{101}{}{You see large tanks with a smelly concoction that will soon become Nuka-Cola.}
{102}{}{You committed a dangerous act of sabotage at the Nuka-Cola factory.}
{103}{}{The Nuka-Cola factory has been sabotaged! Not without your help.}

{104}{}{This liquid has already been poisoned, re-injection will do nothing.}
{105}{}{You have poisoned the tank with liquid, but it's not enough. Poison another one.}
{106}{}{You see large tanks with a smelly concoction that could have been Nuka Cola if you hadn't poisoned it.}
{107}{}{You've already poisoned enough liquid, don't waste the poison.}
{108}{}{Done!}
{109}{}{This one is done.}