{103}{}{Not during combat!}

{110}{}{Here you can conduct trading operations on the purchase and distribution of Nuka-Cola.}
{111}{}{Buy a new batch of Cola.}
{112}{}{Unload Nuka-Cola from your backpack to the warehouse.}
{113}{}{Take Nuka-Cola from the warehouse.}
{114}{}{[Check how many bottles are left in stock]}
{115}{}{[Leave]}

{120}{}{There are currently no items left in stock.}
{121}{}{There are currently }
{122}{}{ bottles of your Nuka-Cola in the warehouse.}
{123}{}{[Back]}
{124}{}{[Leave]}
{125}{}{Your products are out of stock.}

#Покупка колы
{130}{}{You have exceeded your limit for this month. Wait for the factory to produce the next batch of items for you.}
{131}{}{This month you can buy no more than }
{132}{}{ bottles of Nuka-Cola.}
{133}{}{Buy 4,000 bottles (costs $8,000).}
{134}{}{Buy 3,000 bottles (costs $6,000).}
{135}{}{Buy 2,000 bottles (costs $4,000).}
{136}{}{Buy 1,000 bottles (costs $2,000).}
{137}{}{Buy 500 bottles (costs $1,000).}
{138}{}{Buy 100 bottles (costs $200).}
{139}{}{You have placed an order at the warehouse and received the required number of bottles at the wholesale price. Your Nuka-Cola has been deposited in the warehouse.}

#Загрузить колу
{140}{}{Load the Nuka-Cola into the container.}
{141}{}{5 bottles.}
{142}{}{10 bottles.}
{143}{}{20 bottles.}
{144}{}{30 bottles.}
{145}{}{50 bottles.}
{146}{}{100 bottles.}
{147}{}{Load all bottles.}
{148}{}{[Leave]}
{149}{}{[Done]}

#Выгрузить колу
{150}{}{There are currently }
{151}{}{ bottles of your Nuka-Cola in the warehouse.}
{152}{}{}
{153}{}{Take 5 bottles.}
{154}{}{Take 10 bottles.}
{155}{}{Take 20 bottles.}
{156}{}{Take 30 bottles.}
{157}{}{Take 50 bottles.}
{158}{}{Take 100 bottles.}
{159}{}{Take all the bottles.}
{160}{}{[Leave]}
{161}{}{[Done]}
{162}{}{There is nothing left in the warehouse.}
{163}{}{Sorry, you can't carry so much.}
{164}{}{[Take everything I can carry]}
