{102}{}{You can't use this during combat.}
{103}{}{You don't need this terminal anymore.}

{190}{}{The barrels are in place. One spark - and the hangar door will be blown to pieces!}
{191}{}{This terminal is designed to control the hangar crane. Too bad it doesn't work, as there is no power going to it.}
{192}{}{This terminal is designed to control the hangar crane. However, your attempts to somehow influence the crane with it are unsuccessful. There must be a break somewhere in the hangar's electrical circuit.}
{193}{}{[Leave]}
{194}{}{The terminal lights up several indicator lights. Brushing off the dust and sand from the toggle switches, you can make out some inscriptions. Yes, you can use it.}
{195}{}{[Use a crane to move the fuel barrels to the gate]}
