#! Not used in 1.0
{100}{}{This is hatch.}
{101}{}{A powerful door with a powerful lock. You can open it only with a specific key.}
{102}{}{It's locked. You can open it only with a specific key.}
{103}{}{Locked, need a key.}
{104}{}{This door will stand even a small nuclear explosion. Or maybe not.}

{110}{}{You unlock this huge hatch.}
{111}{}{Done!}
{112}{}{This is useless here.}
{113}{}{The door is already open.}
{114}{}{Useless}
{115}{}{It will not help. Look for the key.}