{100}{}{You see a terminal.}
{101}{}{This terminal is responsible for the operation the subsystems of the sump.}
{102}{}{}
{103}{}{This terminal is now useless.}

{106}{}{Floodgates: closed. Pressure: normal. Emergency drain terminal: blocked.}
{107}{}{Emergency drain terminal? This is probably the one that hangs in the front. No thanks, it’s easier from here. Now, open the floodgates!}
{108}{}{[Leave]}