{100}{}{You see a door.}
{101}{}{You see a very powerful door with a heavy lock. Even a dynamite won’t do much!}

{102}{}{The door is locked.}
{103}{}{It won't help you here. You need a key.}
{104}{}{The door is already open}
{105}{}{You've opened this mighty door.}

{106}{}{Hey, you! Get away from it!}
{107}{}{What the hell is- hey! A thief! I'll show you!}
{108}{}{Hey! Don't go in there. Don't even think about it.}
{109}{}{Haa! Bad move, you thieving scum!}
