{100}{}{}
{101}{}{}
{102}{}{All of this belongs to the mechanic, which is somewhere nearby.}
{103}{}{During the combat you won't need it.}
{104}{}{This is now useless.}
{105}{}{What an interesting thing.}

{110}{}{On the table are parts of the dilapidated power armor.}
{111}{}{[Inspect the damages closely]}
{112}{}{[Conduct an initial analysis of the possibility of repair]}
{113}{}{[Leave the parts alone]}

#Первый этап починки
{114}{}{Apparently, this exemplar of rare military equipment was especially unlucky during the Great War: the helmet is almost destroyed, the back part is mangled, including the power module. And, of course, the most "spicy" part - the processor - is also missing. To rebuild THIS, you'd need a whole factory... Or at least a lot of spare parts.}
{115}{}{To restore the armor, you need not only to replace some parts, but also to have a very high skills in system engineering (that is, to put it simply, repair and science.)}
{116}{}{}
{117}{}{Begin the first phase of repairing - restoring the supporting structure.}

{118}{}{Working "blindly" will be difficult.}
{119}{}{[Use the broken armor]}
{120}{}{[Use the blueprints for the supporting structure]}
{121}{}{[Do nothing and leave the parts on the table]}

{122}{}{After working all day on the armor, you got a positive result - the supporting structure is restored! This is a big step forward. But that's not enough for full repair.}
{123}{}{Ugh, it's really hard...}

#Второй этап починки
{130}{}{Begin the second stage of repairing - the restoration of hull's integrity.}
{131}{}{There is nothing left of the old power armor that could be used to restore integrity. Will have to look for a replacement for layers of gas and radiation protection, together with a hermetic helmet.}
{132}{}{[Use anti-radiation suit]}
{133}{}{[Use gas-protection suit]}
{134}{}{[Use the lab helmet]}
{135}{}{[Do nothing and leave the parts on the table]}

{136}{}{You successfully completed this part of the repair.}
{137}{}{Great!}

{138}{}{The second stage of power armor repair is complete! Integrity of the armor's hull is restored.}
{139}{}{Finally!}

#Третий этап починки
{150}{}{Begin the third stage of repairing - the restoration of the power system.}
{151}{}{The situation is more complicated than expected. The armor's complex internal structure is nearly destroyed, particularly the autonomous system and CPU. You need to replace them with the usage of corresponding blueprints.}
{152}{}{[Use the blueprints and parts for repair]}
{153}{}{[Use the blueprints and a broken power armor for repair]}
{154}{}{Oh, this is too difficult for me.}
{155}{}{Spinning the last screw in the armor, you watch in awe at the complete suit on the table. You walk a couple steps back, stopping motionless, like a connoisseur of art in front of antique painting.}
{156}{}{It's beautiful!}
