{100}{}{}
{101}{}{}
{102}{}{All of this belongs to the mechanic, which is somewhere nearby.}
{103}{}{During the combat you won't need it.}
{104}{}{This is now useless.}
{105}{}{What an interesting thing}

{110}{}{There are parts of dilapidated power armor on the table.}
{111}{}{Inspect the damages closely.}
{112}{}{Conduct an initial analysis of the possibility to repair.}
{113}{}{Leave the parts on the table.}

#Первый этап починки
{114}{}{Apparently, this exemplar of rare battle equipment had a little to no luck during the Great War: the helmet is almost destroyed, the back is mangled, together with the power module, and, of course, the most "spicy" part - the CPU - is done too. To restore THIS, you will need a whole factory... Or at least spare parts for replacement.}
{115}{}{To restore the armor, you require not only replacements for some parts, but also very high skills in system engineering (that is, to put it simply, repair and science.)}
{116}{}{}
{117}{}{Begin the first phase of repairing - restore supporting structure.}

{118}{}{Working "blindly" will be difficult.}
{119}{}{Use the broken armor.}
{120}{}{Use the blueprints for the supporting structure.}
{121}{}{Do nothing and leave the parts on the table.}

{122}{}{After working all day on the armor, you still got a positive result - supporting structure is restored! This is a big step forward. But that's not enough for full repair.}
{123}{}{Ugh, it's a really hard work...}

#Второй этап починки
{130}{}{Begin the second stage of repairing - the restoration of integrity.}
{131}{}{There is nothing left of the old power armor that could be used to restore integrity. Will have to look for a replacement for layers of gas and radiation protection, and a hermetic helmet.}
{132}{}{Use anti-radiation suit.}
{133}{}{Use gas-protection suit.}
{134}{}{Install lab helmet from Area 51.}
{135}{}{Do nothing and leave the parts on the table.}

{136}{}{You successfully completed this part of the repair.}
{137}{}{Great.}

{138}{}{The second stage of power armor repair is over! Integrity of the armor is restored.}
{139}{}{Finally!}

#Третий этап починки
{150}{}{Begin the third stage of repairing - the restoration of the power system.}
{151}{}{The situation is more complicated than expected. The armor is nearly destroyed with the most complex internal structure, in particular the autonomous system and CPU. You need to replace them, with the usage of corresponding blueprints as well.}
{152}{}{I have the blueprints and parts. Use them for repair.}
{153}{}{I have the blueprints and a broken power armor. Use them for repair.}
{154}{}{Oh, this is difficult for me.}
{155}{}{Spinning the last screw in the armor, you look in awe at the finished armor on the table. You walk a couple steps back, stopping motionless, like a connoisseur of art in front of antique painting.}
{156}{}{It's beautiful!}
