{100}{}{You see a train.}
{101}{}{This train will not move - its last journey came to an end.}

{110}{}{The train is well preserved under the roof of the hangar.}
{111}{}{[Start the train]}
{112}{}{[Assess the situation]}
{113}{}{[Check train systems]}
{114}{}{[Leave]}

{120}{}{Looks like the train is operational and ready to go.}
{121}{}{The train seems to be fine, but the onboard computer doesn't work. It's hard to say why. Qualified maintenance is required.}
{122}{}{[Dismantle an inoperable onboard computer]}
{123}{}{[Install the functional onboard computer]}
{124}{}{Done.}
{125}{}{You install the onboard computer and press the button in anticipation. The screen turns bright green. You stare at the message "system check..." for a few minutes, then the screen finally notifies you that the train status is operational.}
{126}{}{This train is built with modern pre-war technology. The interface is quite simple, but even if you manage to run the train, it will be difficult to keep an eye on the complex reactor system and other important parameters and metrics at the same time. You will have to find an assistant.}

{130}{}{The train is ready to go, but you can't handle it alone. You will have to find assistant.}
{131}{}{The train is ready to go, but you can't speed it up to break the hangar gate. You must find a way to open the gate.}
{132}{}{The train is ready to move, but where?}
{133}{}{The train is ready to dispatch.}
{134}{}{Go!}
{135}{}{The train is non-functional.}
