{100}{}{You see a drunkard.}
{101}{}{You see an ordinary passerby who has had a little too much to drink at the bar.}
{102}{}{Stealing from the drunk has a negative effect on your karma.}

#Attempt at shoving
{103}{}{Hey you! I'll get ya!...}
{104}{}{Get... Out of the way...}
{105}{}{Woah, the ground's moving!}

{110}{}{::hurrgh::}
{111}{}{This drunkard can barely stand. You don't matter much to him. Nothing does.}