{100}{}{You see Myers.}
{101}{}{You see the head of the restaurant. He smiles, even though he's very busy.}
{102}{}{I have a feeling like I'm being watched... [he shakes his head] It's all in my head, probably.}

#Оружие в руках
{102}{}{Hey, when you're in here, the weapon stays in its holster.}
{103}{}{I know we say the customer with a knife is always right... But there's a limit!}

####################################################################
#              Случайные плавающие фразы
####################################################################

{110}{}{One sandwich and beer...}
{111}{}{Who ordered gecko steak?}
{112}{}{Forty-five bucks.}
{113}{}{You want a take-out?}
{114}{}{Special order from Avellone on the way...}
{115}{}{No, no, no tabs.}
{116}{}{One "dive bomb" with ice, coming right up.}
{117}{}{Keep it down, this ain't a casino!}
{118}{}{Who didn't pay for his sandwich?!}
{119}{}{Still waiting on that order of brahmin meat...}
{120}{}{[Whistles]}

####################################################################
#              Скупка яиц
####################################################################

{130}{}{Are you interested in gecko eggs?}
{131}{}{Hell yeah! It's a delicacy around here. I'll pay you }
{132}{}{ bucks apiece!}
{133}{}{Do you have regular suppliers?}
{134}{}{Nah. Sometimes the hunters bring these eggs in from the north and northeast, but more often caravans buy 'em there, then sell 'em here at a profit. Hunters get money, caravans get money, and once I'm done with 'em, I get money. Everybody wins.}
{135}{}{I'll sell all the eggs I have.}
{136}{}{}
{137}{}{I'll think about it.}
{138}{}{Thanks! Here's your money.}
{139}{}{You're welcome.}

{140}{}{Okay. Where's the eggs?}
{141}{}{Uh, just a second...}
{142}{}{What? You're practically robbing me! Can I get another 10 dollars each?}
{143}{}{}
{144}{}{That'd be robbing *me!* No deal!}
{145}{}{Fine, I'll sell them at your price.}
{146}{}{Then I'll take my eggs elsewhere.}
{147}{}{[He frowns and grumbles] These eggs have been hard to get lately, so... Fine. Another ten bucks. My customers will have to deal with the price hike.}

####################################################################
#              Диалог
####################################################################

{149}{}{[He glares at you] Are you going to order something?}
{150}{}{Hey, you hungry? What are you looking for?}
{151}{}{Yes?}
{152}{}{Show me the menu.}
{153}{}{}
{154}{}{Thanks, that's all.}

{155}{}{Shit! [he recoils] Look, I'll make you whatever you want, but you gotta get right out after. And... Just don't touch anything!}
{156}{}{Mrs. Clover told me what you did for her. Look, any friend of the community's a friend of mine. Next time you're in here, it's 5% off on me. It's the least I can do!}
{157}{}{You? It's you! Please, ma'am, sit down, sit down! What can I make you? And don't worry about payment - I'm just happy to have you here.}
{158}{}{Hey, thanks for stopping by! The whole town's talking about you, you know. For you, I'm cutting the prices by a quarter. What goes around, comes around, am I right?}
{159}{}{Oh, uh, hey! You're the talk of the town. Hey, just so you know, I had to, uh, raise my prices by 25%. Nothing to do with you, of course... Just business.}
{160}{}{You? It's you! Please, sir, sit down, sit down! What can I make you? And don't worry about payment - I'm just happy to have you here.}
{161}{}{You have received a discount in the restaurant.}

####################################################################
#              Расспросы
####################################################################

{170}{}{Who's that little urchin running around?}
{171}{}{Billy? I picked him up off the street to wash the floors and clean the tables. Don't worry about him, he's happy as long as he's fed. So, what would you like to eat?}

{172}{}{Anything else?}
{173}{}{}

{174}{}{Have you seen the girl in this photo?}
{175}{}{Maybe? She looks familiar. Wait, that's right! She lived across from the restaurant, on 75 Virginia Street. Ask around in the slums, they can probably help you.}

{176}{}{Please, help... I'm so hungry...}
{177}{}{No handouts. Show me some money or get out.}

{178}{}{Please... I'm dying... I need food...}
{179}{}{And I need to pay the rent! I'm running business here, I can't just give away food. Sorry.}
{180}{}{[He sighs] Fine, here's *one* sandwich. Now get out! You're disturbing my customers.}

{181}{}{Do bikers come by here?}
{182}{}{Not since that thing with the stagecoach. They used to come by the city before that, but even then they weren't welcome here.}
{183}{}{What's the story with the stagecoach?}
{184}{}{You haven't heard? They hit one of the "Nevada Express"'s transports, dumb bastards. Once the Express figures out where they're hiding, they're gonna feed them their own ass. Good riddance, I say - they've been nothing but trouble every time I've seen 'em.}

{185}{}{Wow, you've got a whole mountain of meat on the street!}
{186}{}{Yeah, I managed to cut a deal with Mr. Luciano. He's got the best meat in the city... Most expensive, too. [he frowns]}
{187}{}{The best? How do you know?}
{188}{}{Mr. Luciano's always on time and his brahmin are always healthy. A lot of the smaller farmers I've worked were a lot less reliable, but I've never had a problem with Luciano's product.}
{189}{}{Right.}

{190}{}{How long has it been since Mr. Mordino visited you?}
{191}{}{[He stops what he's doing, then peers at you with narrowed eyes] Long. And it better be a long time before you ask me that again. Mordino's business is his own. I won't say anything more about it.}
{192}{}{Who will, then?}
{193}{}{Look. [he points one finger towards you] My lips are sealed, you get that? You really want to find out? Go ask someone else, somewhere else. You get me?}
{194}{}{Yeah, I get you.}

####################################################################
#              Продажа ядер-колы
####################################################################

{300}{}{Hey, you want a steady supply of Nuka-Cola? Why not set up a contract with Salt Lake!}

{301}{}{[He looks you up and down] And *you're* the one offering the contract? Sorry, I don't even know you. I can't trust my customers' health to you!}
{302}{}{That's a shame...}
{303}{}{Do you really work for the Nuka-Cola factory? You don't look like the type.}
{304}{}{You don't believe me? Just look at my license!}
{305}{}{What's that supposed to me? Oh, forget it.}

{306}{}{Uh-huh. [he crosses his arms] How do I know you didn't steal it? Thanks, but no thanks.}
{307}{}{Rude!}
{308}{}{I'll find a way to gain your trust.}

{309}{}{Nuka-Cola? Hmm. Maybe. It depends on the price.}
{310}{}{The price is reasonable - I'm working directly with the Nuka-Cola factory.}
{311}{}{You still don't strike me as the business type, but hey, who am I to argue? What's it gonna cost me?}

{312}{}{Oh yeah? Who's going to transport it?}
{313}{}{Why does that matter?}

{314}{}{This kind of stuff comes by caravan, usually by a lot of them. That means I've got to cut more deals and spend more money. I can't pay so much for a product that costs a few bucks to people, you know?}
{315}{}{Don't worry about the delivery. I can line up cheap and effective deliveries. All you'll have to do is sell it.}
{316}{}{Hmm... I'll think about it and come back with a solution.}

{317}{}{Well, if you can deal with all that yourself, then I'm in. Why not?}
{318}{}{So we have a deal?}
{319}{}{Sure. I'll fix up one of those drink machines and sell it there. You can automatically calculate and take your cut of the profits right on it. You'll just have to make sure the product gets here, and pick up your money.}
{320}{}{Then let's get to work!}

{321}{}{Great! A deal's a deal!}
{322}{}{Let's do this...}

{323}{}{Great deal! Thanks!}
{324}{}{See you.}

#Female character
{1176}{}{Please, help... I'm so hungry...}
