{100}{}{There he is! Get him! Let's show that asshole what it's like to mess with us!}
{101}{}{There she is! Get her! Let's show that bitch what it's like to mess with us!}

{106}{}{There he is! Get him! Let's show that asshole what it's like to mess with us!}
{107}{}{There she is! Get her! Let's show that bitch what it's like to mess with us!}
{108}{}{Your actions have earned you many enemies in the slums of Reno.}