{100}{}{You see a "shady man".}
{101}{}{You see a completely ordinary man from the streets who doesn't look suspicious at all.}
{102}{}{Don't worry.}

{110}{}{Wow, look at those clothes! You aren't from around here, huh?}
{111}{}{Hey, didn't I see you in that other part of Reno with the serious looking fellow? It's... Surprising to see you among decent people.}
{112}{}{Well, well, do my eyes deceive me? If it isn't another inhabitant of these beautiful slums? My regards!}
{113}{}{And who are you?}

{114}{}{Just another bum, sir, like any other. I'm just trying to warm myself up. Hope you don't mind.}
{115}{}{Quit bullshitting me! Who are you and what do you need in Wright's territory?}
{116}{}{My boss said you need to leave. You can do that either on your own, or in a box.}
{117}{}{I don't know who you are, but you aren't meant to be here. I'll pay you 300 bucks if you disappear, okay?}
{118}{}{I don't mind. Stay... For now.}

{119}{}{What are you talking about, sir?! I'm just an ordinary bum, you must be confusing me with someone!}
{120}{}{Your skin is far too smooth for someone from the streets. Still going to play innocent?}
{121}{}{Me?! What for?! I didn't do nothing! Just keeping warm next to a barrel! Please sir, all I want is a single look at these magnificent slums and I'll leave.}
{122}{}{[Press him against a wall] Listen up, shithead. I don't know who sent you, but while I'm working for Wright, I won't let trash like you to slip by. Understood? Now get the fuck out!}
{123}{}{Oh wow, you are so generous, sir! For that kind of money, I'd... Actually, if I think about it, this might be the best way.}
{124}{}{Here's your money, I don't want to see you again.}
{125}{}{Don't care.}
{126}{}{Stay here, I'll be back.}
{127}{}{[You notice the scared faces of citizens peeking from windows and street corners] S-sure, s-sir, I won't disturb you again...}
{128}{}{Damn right! Now get out.}
{129}{}{[He scowls at you] You think you see everything? Bet you've got eyes on the back of your head too.}
{130}{}{You really think I'll fall for that?}
{131}{}{Haha! You're blind like the rest of them. These... Bosses know a lot, but fail to notice simple things. You know what I'm talking about. They're confident, arrogant, knowing everything. But you're just a tool. They're using you, and you... You're probably using them too, but differently.}
{132}{}{What are you talking about?}
{133}{}{I've had enough! I'm gonna put you back in the trash where you belong! [Attack]}
{134}{}{You can beat me to a pulp. Right here on the streets. But you'll only prove you're a piece of shit just like your boss. You do that and in under an hour everyone here will know about it. How does that sound? Yeah, I'll leave... Quietly.}
{135}{}{Good, now scram.}

#Female version
{1114}{}{Just another bum, ma'am, like any other. I'm just trying to warm myself up. Hope you don't mind.}
{1119}{}{What are you talking about, ma'am?! I'm just an ordinary bum, you must be confusing me with someone!}
{1121}{}{Me?! What for?! I didn't do nothing! Just keeping warm next to a barrel! Please ma'am, all I want is a single look at these magnificent slums and I'll leave.}
{1123}{}{Oh wow, you are so generous, ma'am! For that kind of money, I'd... Actually, if I think about it, this might be the best way.}
{1127}{}{[You notice the scared faces of citizens peeking from windows and street corners] S-sure, m-ma'am, I won't disturb you again...}
{1131}{}{Haha! You're blind like the rest of them. These... Bosses know a lot, but fail to notice simple things. You know what I'm talking about. They're confident, arrogant, knowing everything. But you're just a tool. They're using you, and you... You're probably using them too, but differently.}