{100}{}{You see Wright's guard.}
{101}{}{You see one of Mr. Wright's guards.}

{102}{}{You here to see Mr. Wright? He's in his office.}
{103}{}{Mr. Wright's sleeping now. Come back in the morning.}
{104}{}{The entrance is right up the street.}
{105}{}{I've got my eye on you.}
{106}{}{Mr. Wright's asleep. Keep moving.}

{107}{}{You see one of Mr. Wright's guards. The resemblance to Wright himself is uncanny.}

{108}{}{The boss is... He's not here. Just get out!}

#Floating dialogue between Chuck and Wright's wife:
{109}{}{ }
{110}{}{Hey, did you miss me?}
{111}{}{Oh, Chuck, it's you again...}
{112}{}{I'm just here to say hi. What's the problem?}
{113}{}{Stop it, Chuck. We've talked about this.}
{114}{}{Come on! What does he need so many wives for, anyway?}
{115}{}{Status, Chuck. Status, and a desire to continue his bloodline.}
{116}{}{A bloodline?! What's wrong with any of us?! I have brothers all over Reno, and -}
{117}{}{Don't you dare!}
{118}{}{- and he's got more wives than any man could need!}
{119}{}{You really won't understand. He cares for this family. You just care about yourself.}
{120}{}{Oh, yeah, so noble. That's dad, for sure! All heart!}
{121}{}{You have no right to judge him. He gave you life and a job.}
{122}{}{I... All he gives me is money. I want more. I want you!}
{123}{}{No, Chuck. I've told you this before.}
{124}{}{You're breaking my heart!}
{125}{}{I never asked for your heart. Don't blame its condition on me.}
{126}{}{Why are you so loyal to him? You're all less than half his age!}
{127}{}{If you have to ask this question, you have no idea what loyalty means. But you've shown that already.}
{128}{}{Why are you cruel to me?}
{129}{}{Why are you here at all? Aren't you on duty?}
{130}{}{What's gonna happen? Dad's asleep, and the doors are guarded.}
{131}{}{Anything can happen in this city.}
{132}{}{I'm only a few feet from the door! No one's getting in.}
{133}{}{Maybe. But if Wright finds out you're in here...}
{134}{}{Be reasonable. I can't just stand next to his bedroom door all night!}
{135}{}{Try explaining it to your father... Maybe he'll give you a chair. Tee-hee!}
{136}{}{Grr! Yeah, laugh it up. I'll try to forget your cruelty over a bottle of whiskey.}
{137}{}{Heh-hee...}
{138}{}{::sniff:: What's that, apple pie for my father?}
{139}{}{Yes, made with love.}
{140}{}{It sure would be nice to have some...}
{141}{}{There's the door. Go and find someone to make it for you.}
{142}{}{::sigh::}

#Forcing PC from home
{150}{}{Hey, what the fuck are you doing here?! You can't come here at night! Get the fuck out of here!}
{151}{}{[Leave.]}

#Caught entering bedroom
{152}{}{Die, thief!!}
{153}{}{Don't you dare come here! I'll paint the ceiling with your brains!}

{154}{}{Hey, who let you in here? People are trying to sleep! Get the fuck out!}
{155}{}{No one get in today. Come back in a week.}

{156}{}{Want to meet Mr. Wright? Lose the guns first.}