{100}{}{You see a beggar.}
{101}{}{You see a disgraced old man digging through scraps. He looks like he's having a rough time.}

{102}{}{You're just a pair of cunt flaps waving in the breeze. Get the fuck away from me.}
{103}{}{I don't need anybody's help!}

#Floating Dialogue
{109}{}{ }
{110}{}{I saw the way you looked at me! Don't you fucking dare to look down on me, you sack of shit!}
{111}{}{Fuck off, old man.}
{112}{}{Shut up! You're nothing! I was here before your daddy was even born!}
{113}{}{And look at what you've become. Practically a role model!}
{114}{}{Fucking kids! Let me tell you, back in the day...}
{115}{}{...When dinosaurs roamed the earth...}
{116}{}{...The mayor was putting everybody in their place. We'd send shits like you straight to Golgotha!}
{117}{}{Those days are long gone, old man.}
{118}{}{I was a respectable man once! But now I'm living on the streets, digging through trash, and you... Look at you!}
{119}{}{Ha-ha-ha!}
{120}{}{You're laughing in the face of death!}
{121}{}{Took the words right out of my mouth, you old fossil. You look exactly like that.}