{100}{}{You see Theodore Wright.}
{101}{}{You see the rich owner of the local slums and a major authority in Reno.}

{102}{}{Give me a chance to get to my table, you troglodyte!}
{103}{}{*Zzzzzz...*}
{104}{}{Better not wake him right now.}
{105}{}{Come back at a civilized hour.}
{106}{}{Thief! Guards! Thiiief!!!}

{107}{}{Huh?! Wha... *mumbles*}

#Пробуждение от хождений ГГ по комнате
{110}{}{::stretches::}
{111}{}{...hey! What the...}
{112}{}{::rolls over::}
{113}{}{Hrrmf...}

{115}{}{One more good day in hell.}
{116}{}{Maybe tonight I'll actually sleep...}

#Первый разговор
{130}{}{Keep your distance. I don't know what's wrong with your face, but even if it's not contagious, I don't want it anywhere near me.}
{131}{}{I understand, Mr. Wright. We can talk from here.}
{132}{}{[Sneeze in his direction] Oh, Mr. Wright, I've always wanted to shake your hand.}

{133}{}{I'm surprised such an... Important person has the time to see me. How can I "help" the only officer of the law around, Sheriff?}
{134}{}{Everyone needs something from me... What brings you here?}
{135}{}{Have you completed my... Errand?}
{136}{}{I'm glad to see you. But don't forget your place.}
{137}{}{Nothing.}
{138}{}{I just wanted to say hello.}
{139}{}{I should be on my way.}

#Попытка напроситься на работу
{140}{}{Mr. Wright, I'm looking for work. I've heard a lot about you. Maybe we can help each other?}
{141}{}{[He looks you up and down, thinking] Do you know what's more important in this city than a fat wallet or a quick gun?}
{142}{}{What, Mr. Wright?}
{143}{}{I'm not in the mood for riddles. Do you have work, yes or no?}
{144}{}{Yes, Mr. Wright. It's reputation, isn't it?}

{145}{}{Wilful ignorance. [he scoffs] Get out.}
{146}{}{[Get out]}

{147}{}{Reputation. And regardless of your wallet or gun, reputation is something you don't have. In my slums, no one knows you and no one recommends you. And I trust my people. If you want a job, show me the results of your work... Which can be evaluated.}
{148}{}{You really haven't heard of me, Mr. Wright? I've done a lot in Reno.}
{149}{}{Okay, Mr. Wright.}

{150}{}{Tch. I could care less how others in New Reno see you. My empire is here, in the slums.}
{151}{}{Hmm... [he studies you again, as if he's seeing something new, then nods] Perhaps you have some potential. My people speak highly of you.}
{152}{}{Does that mean you you have work for me?}
{153}{}{[He raises an eyebrow] You think faster than most in this city. And yes, I'm speaking of reputation. Tell me, who can recommend you as a reliable employee?}
{154}{}{People in the slums have a lot of good things to say about me.}
{155}{}{I've been active in other parts of town. Surely you've heard of me already.}
{156}{}{Uh, well, I'm kind of new in town, and...}
{157}{}{Then we have nothing to discuss. The door is over there.}
{158}{}{[Walk away]}
{159}{}{[He nods] Perhaps you have some potential.}

{160}{}{I'll make one thing clear. The Wrights are a family with a dignity. Don't think this occasion makes you one of us. Keep in mind - you work for us, you don't *help* us. Don't you even dare to use that word. We're not beggars, we don't need charity. Do you understand me?}
{161}{}{I understand, Mr. Wright.}
{162}{}{Very well. [he leans back in his chair, interlacing his fingers on his stomach] I have some errands for a man like you... For someone not from around. I pay well - as long as the work is done correctly.}
{163}{}{I'm listening.}

{164}{}{I heard of your prospectors' contract. You're not satisfied with their results, am I right?}
{165}{}{I am not. They disappear for months, miss their deadlines - and think they can get away with it? No, they're done. I'm looking for a professional. Someone reliable. Someone... Loyal.}
{166}{}{I can be that professional.}
{167}{}{Er, good luck with that. Bye.}

{168}{}{Don't forget your place here! Hrm... [he rubs the back of his neck]}

{169}{}{I'm glad we met, sheriff. But don't forget who you work for.}

{170}{}{Go to Uranium City. I want a full report on the situation with the mine... MY mine.}
{171}{}{I'll investigate and return, Mr. Wright.}
{172}{}{You'll be paid when the job is done. You can go now.}
{173}{}{[Walk away.]}

{174}{}{About that job...}
{175}{}{Why didn't you send your people there earlier?}
{176}{}{I need my people here... But that's not your concern.}
{177}{}{I understand.}

{180}{}{I'm listening.}
{181}{}{Uh... Actually, nothing.}
{182}{}{Then get back to work! Don't test my patience. I could have a line of people wanting your job from my door all the way to Luciano's ranch!}
{183}{}{[Walk away]}

{184}{}{I'm back from Uranium City.}
{185}{}{Tell me everything.}
{186}{}{A local named Nelson is in charge now. He's trying to take your mine.}
{187}{}{A shady guy from the Hub is trying to seize your mine. He seems serious... And dangerous.}
{188}{}{All work has stopped and most of the miners have fled the town. People are questioning who really owns the mine and who's going to get it running again.}
{189}{}{Some sort of dangerous mutant in the mine has scared off the workers. Most of them have left the town.}
{190}{}{What else do you know?}
{191}{}{That's all for now. I'll be back when I learn more.}

{192}{}{Enough. I know enough to plan my next steps. I can't afford to lose the mine... But first, here's your payment: $200.}
{193}{}{That's it? Mr. Wright, be honest with me: you are broke, aren't you?}
{194}{}{Thank you, Mr. Wright! I appreciate it!}

{195}{}{There'll be more coming, if you last long enough. You've shown that you can be trusted with more work.}
{196}{}{I understand, Mr. Wright. What was that about more work?}

{197}{}{Watch your tongue! This mob war has strained New Reno's economy to the breaking point! It's robbed my family of almost everything we've earned! I worked years for what I have. I *will not* allow it to be taken from me!}
{198}{}{I need leverage to ensure that mine remains MINE. The mine needs many resources, but most of all - explosives. The stores there must be exhausted by now.}
{199}{}{Where will you get explosives?}
{200}{}{I contracted a couple of prospectors to retrieve some explosives from an old military base. They... Disappeared. Which is very disappointing. Now I have to deal with their families. Do you understand the... Subtlety of the situation?}
{201}{}{What should I do, Mr. Wright?}
{202}{}{I don't care how, but I want that contract fulfilled. Find out what happened to my prospectors.}
{203}{}{I'm on it, Mr. Wright.}
{204}{}{Well, I'll see what I can do.}
{205}{}{First, talk to the Gate family. They must know something. They live in the slums in front of the hotel.}
{206}{}{I'm on my way.}

{207}{}{[He drills you with a stare of contempt and disgust] I don't employ rapists and child-killers. I can't decide whether to have my guards shoot you, or to have the pleasure of doing it myself. You better leave before I make up my mind.}
{208}{}{[Walk away silently]}

#Квест на возврат шахты
{210}{}{About those prospectors...}
{211}{}{Where are my explosives?}
{212}{}{In Uranium City. Nelson has them.}
{213}{}{I have them right here, Mr. Wright.}
{214}{}{I don't know. But I found the prospectors.}
{215}{}{Stop wasting my time! All I care about are those explosives. It doesn't matter who gets them, as long as they are brought to *me*!}
{216}{}{I'll do it, then.}
{217}{}{They're what?! You imbecile! Those explosives are my leverage *against* that town! Get them back at any cost! If you have to kill this Nelson, do it. Now go. The next time I see you, you'd better have my explosives.}
{218}{}{[Walk away.]}
{219}{}{Finally. So long as I have these, I can dictate my terms to the miners there. [he hands the explosives to a guard] Now to the matter of payment. Who retrieved these explosives from the military base?}
{220}{}{The prospectors, Mr. Wright. They're the ones that retrieved the explosives. They only asked me to deliver it, because they're afraid of you.}
{221}{}{I had to do everything myself, Mr. Wright. I even have the contract here. It'll be fair if you pay me.}
{222}{}{Hmm. You could have lied, telling me you retrieved them from that base, but you didn't. I appreciate honesty. Anyway, here's your pay for the assignment.}
{223}{}{Thank you, Mr. Wright.}
{224}{}{That doesn't surprise me. I'm surrounded by incompetence. I have to take measures against the prospectors' families. You'll be paid appropriately for your work.}
{225}{}{I had to do everything, Mr. Wright. It'll be fair if you pay me.}
{226}{}{You could be lying. Perhaps they retrieved the explosives and you only delivered them to me. But the job is done, you are here and they are not, so the reward goes to you.}
{227}{}{I'll need more explosives than this to wrest my mine back from the usurpers in Uranium City. Tell me, who's in charge of the mine now?}
{228}{}{Some guy from the Hub named Lewis Birch. He seems like a tough customer.}
{229}{}{Nelson, one of the locals.}
{230}{}{All work has stopped and most of the miners have fled the town. People are questioning who really owns the mine and who's going to get it running again.}
{231}{}{Then get rid of him. That mine belongs to me and only me. Everything it is now is due to my patronage.}
{232}{}{I'll get it done.}
{233}{}{You'll be paid upon completion. We're done here.}
{234}{}{[Walk away]}
{235}{}{In that case, you must remind Uranium City why it even exists. Everyone there is there because of my investments. You mentioned Nelson... I remember him. He was a good worker in the mine. Now he's the one trying to take it from me. I want him removed.}
{236}{}{There's no one left to challenge your ownership of the mine, Mr. Wright.}
{237}{}{Good. Here's your payment. If you lied to me, you'd better never return to this city.}
{238}{}{No lies, Mr. Wright.}

#Рабочие из Уран-Сити
{250}{}{I'm looking for the lost miners from Uranium City.}
{251}{}{I'd advise you start checking trash heaps, where they belong.}
{252}{}{I'm looking for Joseph. He managed the mine crews.}
{253}{}{I'm looking for Carl. He manned the workbench.}
{254}{}{I'm looking for Michael, a supplier.}
{255}{}{Thanks, that's all I need to know.}

{256}{}{That useless dullard had no business managing anyone. I sold him into slavery to Oliver's ranch. Maybe he'll finally learn something about leadership when he's on the receiving end.}
{257}{}{That half-witted nigger doesn't know how lucky he is. I can't punish him until I find a suitable replacement... And it's not easy. Until then, he's living with his family in my slums in front of the Silver Legacy hotel.}
{258}{}{That man redefines the word "useless". He had nothing I could take from him. Even the slavers didn't want him. I kicked him to the streets - he's probably been eaten by dogs or his fellow beggars by now.}
{259}{}{[Leave]}

#Проблема с миссис Кловер
{260}{}{A resident in your slums, Mrs. Clover, has become the victim of another person's debts. What is your position on this?}
{261}{}{Another headache. Mrs. Clover is a a reliable cash cow due to her restaurant's income, so it's in my best interests to keep her solvent. On the other hand, it's not in my best interests to forgive debts... I'm taking my share, regardless of who pays it. I will be observing this matter from a distance with great care.}
{262}{}{I understand. Let's talk about something else.}
{263}{}{That's all I needed. Goodbye, Mr. Wright.}

#Квест на странного типа в трущобах
{270}{}{Your work in Uranium City is done. My sons will take it from here... When we're ready. You have another job.}
{271}{}{I'm listening.}
{272}{}{I've been told of a strange man sniffing around my slums. I do not know him, but there can be no secrets from me in my domain. Go the east side of the slums and deal with him. Avoid causing a ruckus if possible, but do whatever you need to get the job done.}
{273}{}{I'm on my way, Mr. Wright.}
{274}{}{I've dealt with the stranger. It seems like he was watching the slums, but I couldn't find out more.}

{275}{}{I figured he would be around sooner or later. This explains the reports I've been receiving.}
{276}{}{You expected someone to be spying in the slums?}
{277}{}{I'm being watched. I know that. I just wanted to see how you handled the situation. [his lips curl into a small, but very self-satisfied grin] You were also being watched.}
{278}{}{Everyone's watching everyone... So what now?}
{279}{}{Now, your payment. [he counts out the money] This was your last job. From here on, I need someone smarter than you. Don't bother me again.}
{280}{}{Now, your payment. [he counts out the money] This was your last job. Your reputation in the slums makes it clear I can't rely on you. The door is over there.}
{281}{}{Now, your payment. [he counts out the money] You did well on this job. You've proven that you're trustworthy. You are ready for more... Delicate jobs.}
{282}{}{I'm listening, Mr. Wright.}
{283}{}{At this point, you should know there's a war going on in Reno. It's quiet now, which benefits me, but my sons and I are being watched. It will be too dangerous for me to act alone. I have no other choice but to unite with my old enemy - Oliver Luciano.}
{284}{}{[Next]}
{285}{}{Go to his ranch and relay my offer of alliance. *Politely.*}
{286}{}{May I ask a few questions, Mr. Wright?}
{287}{}{On my way, Mr. Wright.}

{288}{}{I don't deal with gangsters. I have no use for employees of mixed loyalties.}
{289}{}{Wow, word travels fast...}

{290}{}{If you must.}
{291}{}{Another question, if I may.}
{292}{}{Thank you, Mr. Wright. That's all I needed.}
{293}{}{Why did you secure the Uranium City mine if you're not going to restore it?}
{294}{}{I will... Eventually. For now, it's enough to know I have it under control. I have greater concerns at this moment, but I cannot allow it to fall into anyone else's hands.}
{295}{}{You're broke, aren't you?}
{296}{}{That's a blunt question, but businessmen value straight talking. My family is not as wealthy as it was before, but we have... Enough.}
{297}{}{How did Oliver Luciano become your enemy?}
{298}{}{It was in a different Reno than this one. During its golden age, over ten years ago, we had peace here. But the city grew beyond its resources and we were forced to turn on each other. That gave Big Louie his chance to devastate us all and leave his dogs to pick over what was left. Now I have to join my enemy to survive someone else's war. A bitter irony, isn't it?}
{299}{}{May I ask a few questions about current situation, Mr. Wright?}

{300}{}{I have bad news. Oliver Luciano is dead.}
{301}{}{I've relayed your offer to Luciano. He's ready to hear you out - in person.}
{302}{}{Whose side are you on in this war?}
{303}{}{My own. I have no stake nor interest in politics, but these gangsters won't stop until they own all of Reno... Or die.}
{304}{}{I relayed your offer to Luciano, and he refused. I'm very sorry, Mr. Wright.}
{305}{}{I relayed your offer to Luciano, and he refused.}

#Коллекция
{308}{}{The museum is closed for the foreseeable future. I was robbed recently, and I will not allow the relics of a greater age to be fenced for some gutter trash's drug money.}
{309}{}{That's a shame.}
{310}{}{Mr. Wright, I've heard a lot about your collection of pre-war things. Could you tell me more about it?}
{311}{}{I collect relics of the old America. They are my monument to the rich culture of the country that was... The place that my family should have been born in, rather than the ash heap we're in today. The collection includes a jazz trumpet, a deck of playing cards, photos from different eras and four full cabinets of assorted Americana...}
{312}{}{but you don't need to worry about that. It would be lost on you anyway.}
{313}{}{My museum's doors is closed to the local boors who wouldn't recognize culture if it paved over their hovels and built an art gallery in their place. But you've served me well. Perhaps you may be enlightened by a tour.}
{314}{}{No? Well, maybe you'll change your mind later.}
{315}{}{You'd be surprised how interested I am in pre-war things, Mr. Wright. I'd love to see your collection.}
{316}{}{I would be happy for a tour, but not right now. Sorry to disturb you.}
{317}{}{Look, but don't touch anything. Follow me. [he groans and rises from his chair, walking to the bedroom door]}
{318}{}{[Take a tour.]}
{319}{}{...Do you see now, how much we've lost? This was a great country, our city on a hill... And it could be still, were it not for the avarice and selfishness of its people.}
{320}{}{Thank you for the tour, Mr. Wright. It was very educational!}

#Труба джазовая
{321}{}{Word on the streets is you own a jazz trumpet, Mr. Wright.}
{322}{}{Remember that jazz trumpet in your museum?}
{323}{}{It's a centerpiece of my collection of pre-war Americana. It is very dear to me.}
{324}{}{Why is it so important?}
{325}{}{Is it for sale?}
{326}{}{Mr. Wright, it is very important that I retrieve it for its former owner.}
{327}{}{I can tell it's very important to you. I won't bother you about it again.}
{328}{}{It belonged to a musician who played in the club ten years ago. His band is a part of Reno's history. It was where Big Louie "started" his career - yes, the same one who's brought so much suffering to this city. His band was a rare source of art and culture for Reno... But it was crushed by the civil war.}
{329}{}{I wouldn't want to let it go... But everything has a price. $1000.}
{330}{}{As noble as that sounds, I can't hand away a piece of Reno's history just for one person's feelings.}
{331}{}{Then I'll buy it right now.}
{332}{}{Mr. Wright, you know me better than that. This relic can bring about life and culture again! I plan to form a new jazz band and bring art to the people!}
{333}{}{The deal is done. [he pockets the money, enters his bedroom and emerges shortly with the trumpet] Appreciate your good timing. At any other time, I'd have refused to sell it for any price.}
{334}{}{Thanks.}
{335}{}{It's been a long time since I've felt this inspired. Alright...I'll trust you. You can have the trumpet. For the sake of the future.}

#Встреча с Лучиано
{350}{}{I'm surprised. I thought he was one of the most protected men in... Well, it doesn't matter. Thank you for being a reliable employee, but I have no more work for you. My sons can handle everything for the foreseeable future. }
{351}{}{Farewell.}
{352}{}{Good... Perhaps Reno has a hope after all. Here's your pay. From now on everything depends on me. I have no need for your services anymore. Perhaps Luciano will have some work for you - I expect him to be busy in the future. }
{353}{}{I see. That is unfortunate, but I don't blame you. Luciano is a careful man and doesn't trust people easily. In any case, I have no more work for you. My sons can handle everything for the foreseeable future. }
{354}{}{Wait! Maybe I could convince him?}
{355}{}{You've already had your chance. I don't expect another will make a difference. Nonetheless, I have nothing to lose, so you may as well try. }
{356}{}{You're right, it's just not going to happen. Let's put the matter to rest.}
{357}{}{This time I won't let you down, Mr. Wright.}
{358}{}{Fine. }
{359}{}{Not surprising, considering your ignorance and arrogance. }
{360}{}{[After some thought, he hands you $100] You're free to go.}

#Квест Патрика
{370}{}{Mr. Wright, on Patrick's behalf, I request permission to show a night time movie.}
{371}{}{[He speaks wistfully, sharpening every syllable] Night-time-moo-vie... I didn't expect Patrick to be cunning enough to send someone in his stead. I already told him his bullshit religion wasn't welcome in my domain. Tell Patrick I won't tolerate his attempts to undermine me.}
{372}{}{Mr. Wright, listen...}
{373}{}{No, YOU listen! He's lucky he still has the chance to walk out on his legs after his actions against me! He instills MY tenants with hope for things they can't have! He gives MY tenants a false belief that they are strong, that they deserve better than what I provide them! Why should I turn a blind eye to this?}
{374}{}{Can't we discuss this like businessmen? What if you were compensated for your patience?}
{375}{}{Patrick doesn't want to encourage a revolt. He just wants to show people a movie. Trust me.}
{376}{}{I have no answer to that, Mr. Wright.}
{377}{}{Finally, we're talking sense. If I can profit off his parasitism, then it puts things in a different light... And he *have* to keep quiet. Maybe he can even stem the spread of that STD that's sweeping through Reno's prostitutes. Very well, I will grant him permission for a nominal fee of $1000.}
{378}{}{Here's the money.}
{379}{}{I'll go collect the money.}
{380}{}{Then we're done. But tell Patrick that I only promise to not interfere with his show. I won't provide any security.}
{381}{}{You're... Trustworthy enough that I may let him hold this event. But security is up to you - all I promise is that I will not interfere myself. Now go.}
{382}{}{I appreciate that, boss.}
{383}{}{I do not trust this Patrick, but you have a good reputation in my slums. Fine, I will not interfere in his show. But I take no responsibility for his safety - that's up to you and him.}
{384}{}{Thanks.}
{385}{}{And why should I trust you? You're nothing in this district.}
{386}{}{I guess I can't argue with that.}
{387}{}{Mr. Wright, this could be a great opportunity for you. Let me explain...}
{388}{}{[He listens carefully to your explanation, and finally nods] I see, I see. That preacher should use you for all his deals - you're a much better speaker than him. Fine, tell him I agree. But I won't provide any security - that's up to you and him.}

#Крыша для концерта в Коттон-клубе
{390}{}{I represent the Cotton club. We want to negotiate protection for a concert.}
{391}{}{Excellent. Your boss should know I've always been interested in collaborating. We are neighbors, after all. Tell him I'll contribute to the concert, but I want 30% of the daily revenue.}
{392}{}{We agree to those conditions.}
{393}{}{We will consider your offer get back to you.}
{394}{}{A wise decision. I'll send my men to work out the details.}
{395}{}{Thank you. That will be all.}

#Female character
{1135}{}{Have you completed my... Errand?}
{1138}{}{I just wanted to say hello.}
{1147}{}{Reputation. And regardless of your wallet or gun, reputation is something you don't have. In my slums, no one knows you and no one recommends you. And I trust my people. If you want a job, show me the results of your work... Which can be evaluated.}
{1148}{}{You really haven't heard of me, Mr. Wright? I've done a lot in Reno.}
{1162}{}{Very well. [he leans back in his chair, interlacing his fingers on his stomach] I have some errands for a woman like you... For someone not from around. I pay well - as long as the work is done correctly.}
{1184}{}{I'm back from Uranium City.}
{1210}{}{About those prospectors...}
{1215}{}{Stop wasting my time! All I care about are those explosives. It doesn't matter who gets them, as long as they are brought to *me*!}
{1217}{}{They're what?! You imbecile! Those explosives are my leverage *against* that town! Get them back at any cost! If you have to kill this Nelson, do it. Now go. The next time I see you, you better have my explosives.}
{1220}{}{The prospectors, Mr. Wright. They're the ones that retrieved the explosives. They only asked me to deliver it because they're afraid of you.}
{1222}{}{Hmm. You could have lied, telling me you retrieved them from that base, but you didn't. I appreciate honesty. Anyway, here's your pay for the assignment.}
{1226}{}{You could be lying. Perhaps they retrieved the explosives and you only delivered them to me. But the job is done, you are here and they are not, so the reward goes to you.}
{1237}{}{Good. Here's your payment. If you lied to me, you'd better never return to this city.}
{1270}{}{Your work in Uranium City is done. My sons will take it from here... When we're ready. You have another job.}
{1274}{}{I've dealt with the stranger. It seems like he was watching the slums, but I couldn't find out more.}
{1279}{}{Now, your payment. [he counts out the money] This was your last job. From here on, I need someone smarter than you. Don't bother me again.}
{1281}{}{Now, your payment. [he counts out the money] You did well on this job. You've proven you're trustworthy. You're ready for more... Delicate jobs.}
{1282}{}{I'm listening, Mr. Wright.}
{1301}{}{I've relayed your offer to Luciano. He's ready to hear you out - in person.}
{1304}{}{I relayed your offer to Luciano, and he refused. I'm very sorry, Mr. Wright.}
{1305}{}{I relayed your offer to Luciano, and he refused.}
{1310}{}{Mr. Wright, I've heard a lot about your collection of pre-war things. Could you tell me more about it?}
{1312}{}{But you don't need to worry about that. It would be lost on you, anyway.}
{1313}{}{My museum is closed to the local boors who wouldn't recognize culture if it paved over their hovels and built an art gallery in their place. But you've served me well. Perhaps you may be enlightened by a tour.}
{1316}{}{I would be happy for a tour, but not right now. Sorry to disturb you.}
{1350}{}{I'm surprised. I thought he was one of the most protected men in... Well, it doesn't matter. Thank you for being a reliable employee, but I have no more work for you. My sons can handle everything for the foreseeable future. }
{1352}{}{Good... Perhaps Reno has a hope after all. Here's your pay. From now on everything depends on me. I have no need for your services anymore. Perhaps Luciano will have some work for you - I expect him to be busy in the future. }
{1353}{}{I see. That is unfortunate, but I don't blame you. Luciano is a careful man and doesn't trust people easily. In any case, I have no more work for you. My sons can handle everything for the foreseeable future. }
{1355}{}{You've already had your chance. I don't expect another will make a difference. Nonetheless, I have nothing to lose, so you may as well try. }
{1360}{}{[After some thought, he hands you $100] You're free to go.}
{1381}{}{You're... Trustworthy enough that I may let him hold this event. But security is up to you - all I promise is that I will not interfere myself. Now go.}
{1387}{}{Mr. Wright, this could be a great opportunity for you. Let me explain...}