{100}{}{You see a rabid fan.}

#Случайное подробное описание
{101}{}{You see a wild-looking man. He is yelling his head off.}
{102}{}{You see a rabid martial arts fan. He is screaming for blood.}
{103}{}{You see a wild-looking woman. She is screaming her head off.}
{104}{}{You see a rabid cage fighting fan. She is screaming for blood.}

#Попы'ка разговора
{110}{}{Ye-e-e-e-e-ah!}
{111}{}{Hit me! Hit me! I will tell stories to my kids!}
{112}{}{Give 'em hell!}
{113}{}{Our kind of guy!}
{114}{}{::yells:: ::whistles:: ::screams::}
{115}{}{::hysteria::}
{116}{}{Ye-e-e-e-e-ah!}
{117}{}{A-a-a-a-a-ah!}
{118}{}{::squeals:: ::shouts::}
{119}{}{::whistles:: ::screams:: ::whistles::}
{120}{}{Kill him!}
{121}{}{Kill the bastard!}
{122}{}{You're the best!}
{123}{}{You're the best, gangster!}
{124}{}{Show that son of a bitch!}
{125}{}{Yeah! Show him!}
{126}{}{THE BEST! THE BEST!!!}
{127}{}{YEEEAH!!!}
{128}{}{You're the best fighter I've ever seen.}
{129}{}{Did you see that, ha!? Did you see!?}
{130}{}{Oh yeah, this one knows how to hurt somebody really bad.}
{131}{}{This slave just came from the wastes, but he fights like a king! Unbelievable!}
{132}{}{Oh, my God!}
{133}{}{Is this even allowed?!}

#Когда фан сделал с'авку во время боя на ГГ (для муж. героя)
{150}{}{! I bet 3 bucks on you!}
{151}{}{ will win, I bet on him!}
{152}{}{! 10 bucks on your victory!}
{153}{}{! You're the best!}
{154}{}{, I believe in you!}
{155}{}{, you must win!}
{156}{}{, you're gonna win!}
{157}{}{, you're awesome!}
{158}{}{, I will make a fortune out of you!}

#Когда фан сделал с'авку во время боя НЕ на ГГ, а на его про'ивника
{160}{}{, I won't bet a penny on you!}
{161}{}{ will lose!}
{162}{}{ sucks!}
{163}{}{ is just a piece of shit, not a fighter!}
{164}{}{, don't embarrass yourself on the ring!!!}
{165}{}{, he'll have your ass for breakfast!!!}
{166}{}{, quit fooling around!}
{167}{}{, you suck!}
{168}{}{, not a penny on you!}

#Female character:

#Когда фан сделал с'авку во время боя на ГГ (для жен. героя)
{1150}{}{! I bet 3 bucks on you!}
{1151}{}{ she wins, I bet on her!}
{1152}{}{! 10 bucks on your victory!}
{1153}{}{! You're the best!}
{1154}{}{, I believe in you!}
{1155}{}{, you have to win!}
{1156}{}{, you're gonna win!}
{1157}{}{, you're awesome!}
{1158}{}{, I will make a fortune out of you!}

#Когда фан сделал с'авку во время боя НЕ на ГГ, а на его про'ивника
{1160}{}{, I won't bet a penny on you!}
{1161}{}{ will lose!}
{1162}{}{ - you suck!}
{1163}{}{ is just a piece of shit, not a fighter!}
{1164}{}{, don't embarrass yourself on the ring!!!}
{1165}{}{, she'll have your ass for breakfast!!!}
{1166}{}{, quit fooling around!}
{1167}{}{, you suck!}
{1168}{}{, not a penny on you!}
