{100}{}{You see a strong man.}
{101}{}{You see a big strong man with ripped muscles.}

{110}{}{*grins at you toothlessly*}
{111}{}{*scratches his head*}
{112}{}{*does sit-ups*}
{113}{}{*roars*}
{114}{}{Hfff}
{115}{}{Grrr}
{116}{}{*Warms up his hands*}
{117}{}{Ugh-mf.}
{118}{}{Beat it!}
{119}{}{I'm so hungry I could eat a whole deathclaw right now...}
{120}{}{*Scratches*}
{121}{}{*Mumbles*}
{122}{}{Errr}
{123}{}{Ughf}
{124}{}{Hrrr}
{125}{}{Ehhh}
{126}{}{Grrr}
{127}{}{Hoopla}

{128}{}{You'd better leave me alone.}
{129}{}{*eyes your head like a punching bag*}
{130}{}{I'm lishinin'?}
{131}{}{Need a coach?}
{132}{}{*Nods stupidly at everything you say*}

# boxing boxers messages

# punch
# hit noise
{300}{}{Ernhhh}
{301}{}{Unfff}
{302}{}{Hrghhh}
{303}{}{Nfff}
{304}{}{Hrggg}
{305}{}{Ooof}

# dodge
{310}{}{Too slow!}
{311}{}{Not the face!}
{312}{}{You fight like my grandmother!}
{313}{}{No hitting below the belt!}
{314}{}{You ain't bad.}
{315}{}{Dat all you got?}

# knock down
{320}{}{And stay down!}
{321}{}{Knock-out!}
{322}{}{Get down, now!}
{323}{}{If he dies, he dies.}

{330}{}{Coulda been a champ!}
{331}{}{How could such a... Geggghhh...}
{332}{}{*Huuuuurrrrllllll*}
{333}{}{Ooo, care bears...}
{334}{}{I think I'll just lay here for a little while.}
{335}{}{No pain, no pain, no pain...}

# punching
{340}{}{Eat this!}
{341}{}{You want some of this?!}
{342}{}{Bitch!}
{343}{}{Now you're mine.}
{344}{}{I eat the likes of you for breakfast.}
{345}{}{Haadookin.}
{346}{}{Now you DIE.}
{347}{}{SUPER... NUCLEAR... TORNADO... FIST...}

# taunt
{350}{}{Adrian! Adrian!}
{351}{}{This is where you fall down.}
{352}{}{Gonna make you my bitch...}
{353}{}{I will break you.}
{354}{}{You're fighting like a fat brahmin!}
{355}{}{You've got no guts!}
{356}{}{You're a bum! A bum!}
{357}{}{Gonna beat you like a dog...}

# corner
{360}{}{Ain't gonna be no rematch!}
{361}{}{Hit like a butterfly...}
{362}{}{Keep your hands up...}
{363}{}{Stay sharp!}
{364}{}{Fight past that shit!}
{365}{}{Get critical!}
{366}{}{Cut me, Mick.}
{367}{}{Remember, stick the jab!}
{368}{}{I see all three of 'em!}