{100}{}{You see a casino patron.}
{101}{}{I don't usually drink, nor getting high with strangers }

#Сообщения в консоль при выполнении квеста Лучиано
{102}{}{This client drops unconscious after a sip of "strange" drink.}
{103}{}{Your diversion at the bar was successful.}
{104}{}{Ugh... What was that??}

# examines
{150}{}{You see one of the casino patrons. He looks tired.}
{151}{}{You see one of the casino patrons. He has a golden gleam in his eye.}
{152}{}{You see one of the casino patrons. He is cupping his face in his hands.}
{153}{}{You see one of the casino patrons. He looks a little tipsy.}
{154}{}{You see one of the casino patrons. He gives you a broad wink, then staggers off.}
{155}{}{You see one of the casino patrons. He is trying to get the waitress's attention.}
{156}{}{You see one of the casino patrons. She looks tired.}
{157}{}{You see one of the casino patrons. She has a golden gleam in her eye.}
{158}{}{You see one of the casino patrons. She is cupping her face in her hands.}
{159}{}{You see one of the casino patrons. She looks a little tipsy.}
{160}{}{You see one of the casino patrons. She gives you a broad wink, then staggers off.}
{161}{}{You see one of the casino patrons. She is trying to get the waiter's attention.}

#Для суперброни:
{207}{}{Just looking at him... Her... It... *whatever* it is, gives me the shivers.}
{208}{}{Think that thing's looking to cap anyone?}
{209}{}{It's hell's fury given flesh. Uh, underneath the armor, that is.}
{210}{}{Stay outta that thing's path.}
{211}{}{Talk about dangerous-looking... }
{212}{}{*Gulp*}
{213}{}{I think that Mr. Roboto dude was scanning me.}
{214}{}{I think that walking tank just gave me the stare of death. I'm outta here.}
{215}{}{I heard that thing fragged three hitmen just yesterday.}

#Для берсерка:
{216}{}{Just looking at him gives me the shivers.}
{217}{}{Think he's looking to cap anyone?}
{218}{}{Stay outta that man's path.}
{219}{}{I think he was looking at me.}
{220}{}{I think he just gave me the stare of death. I'm outta here.}
{221}{}{I heard he shot down three hitmen just yesterday.}
{222}{}{Uh-oh. Get out of the way.}
{223}{}{It's hell's fury given flesh.}
{224}{}{Talk about dangerous-looking... }
{225}{}{*Gulp*}

#(!!! заменить) Для пресфингера:
{226}{}{La Femme Nikita, then some.}
{227}{}{Just looking at her gives me the shivers.}
{228}{}{Think she's looking to cap anyone?}
{229}{}{I think she was looking at me.}
{230}{}{I think she just gave me the stare of death. I'm outta here.}
{231}{}{I heard she shot down three hitmen just yesterday.}
{232}{}{What an ass! Uh, bad ass, that is.}
{233}{}{You don't look so tough, Mr. Prizefighter.}
{234}{}{I got 20 chips riding on ye!}
{235}{}{Hey, champ! That last fight was great!}
{236}{}{Saw you fight in the ring. Damn good right hook you throw.}
{237}{}{You gonna take the fall? I got 30 chips riding on you.}
{238}{}{How much you bench?}
{239}{}{Where do you work out?}
{240}{}{Watch out for the Masticator. He has a taste for ears.}
{241}{}{I'd get you a drink if I hadn't blown all my money betting on your opponent.}
{242}{}{You don't look so tough, Ms. Left Hook.}
{243}{}{Can I see your abdominal muscles flex?}

#(!!! заменить)Для порностар:
{244}{}{Whoa. Check that out.}
{245}{}{Would you look at *that*?}
{246}{}{::Mouths the word 'damn.'::}
{247}{}{I KNEW I should have shaved today.}
{248}{}{Come chat with me for a sec, honey-tits.}
{249}{}{Tribals got them tits! Damn!}
{250}{}{Check out the rack on that tribal.}
{251}{}{That there's the main filly of my herd.}
{252}{}{I'd bathe for that woman.}
{253}{}{I got your mother lode right here.}
{254}{}{Shake it!}
{255}{}{Work it!}
{256}{}{::Whistles::}
{257}{}{Them legs go all the way up?}
{258}{}{Daaaaaamn.}
{259}{}{You got fries to go with that shake, beautiful?}
{260}{}{Maybe she'll dance tonight.}
{261}{}{Did you see her latest film? Red hot, man, red HOT.}
{262}{}{Excuse me. I have to go to the bathroom and er, comb my hair for a sec.}
{263}{}{I'd like to be her underpants.}
{264}{}{I'd like to be her underwear.}
{265}{}{I'd like to smell her shorts.}
{266}{}{That is one foxy bitch.}
{267}{}{Damn. All them curves and me with no brakes.}
{268}{}{Well, hellloooo stud.}
{269}{}{A stallion like you in need of a saddle? I'm free tomorrow night.}
{270}{}{What you doing later, sailor?}
{271}{}{Can I feel your muscles?}
{272}{}{How come you don't pass out when you get erect?}
{273}{}{Wanna come over to my place for a drink?}
{274}{}{I want to eat my dinner off your chest.}
{275}{}{Need a partner for your next film?}
{276}{}{::Stares at your biceps.::}

#Игорные реплики:
{280}{}{Lady Luck, don't fail me now.}
{281}{}{Roll the bones.}
{282}{}{Baby needs a new pair of shoes...}
{283}{}{Damn lowrolling tourists... }
{284}{}{Dammit! I was up *53* chips, then... }
{285}{}{Of all the rotten luck... }
{286}{}{So close!}
{287}{}{I'm making bank.}
{288}{}{Me? I'm making bank. Watch me go.}
{289}{}{House was against me.}
{290}{}{Fortune's against me.}
{291}{}{Is anyone going to be at my funeral?}
{292}{}{The House ha'mercy on me.}
{293}{}{Between tips and these drunken spending sprees... }
{294}{}{Keep betting like that, and you're going to be calling Golgotha home... }
{295}{}{Waitress, another drink!}
{296}{}{Waiter, another drink!}
{297}{}{These drinks taste... Odd.}
{298}{}{I got the fever!}
{299}{}{Are all my chips gone already?}
{300}{}{Luck's a fickle bitch, and so is my mother-in-law.}
{301}{}{Well well...}
{302}{}{Ehh, don't fail me!}
{303}{}{Come on, sweetheart!}
{304}{}{Damned crossroaders all over the place...}
{305}{}{Great, another low roller.}
{306}{}{I am SO money.}
{307}{}{I'll sleep when I'm dead.}
{308}{}{Man, I gotta piss. My teeth are swimming.}
{309}{}{Man, I gotta drain the snake.}
{310}{}{Damn, they'll let anyone in here.}
{311}{}{C'mon 7!}
{312}{}{You've got moxy, baby.}
{313}{}{Who's the big winner tonight? Mikey!}
{314}{}{Don't crap out... C'mon... }
{315}{}{I've gotta 'jet'... If you know what I mean.}
{316}{}{This is SUCH bullshit.}
{317}{}{I lost only 60 chips. In the first five minutes, that is.}
{318}{}{Red 23! Red 23! C'mon... Red 23... }
{319}{}{50 chips on Black 15... }
{320}{}{Round and round it goes... Where it stops, nobody knows... }

#Выиграл
{321}{}{I'm a *powerful* player!}
{322}{}{No shit! Where is the cashier!}
{323}{}{Shit, did I really win? WON, yeah!?}
{324}{}{Now this is MINE! Ha-ha-ha!}
{325}{}{Dickheads, I won!}
{326}{}{And they would say, this is all a hoax!}
{327}{}{::dances in joy::}
{328}{}{::clamps his hands::}
{329}{}{My turn!!!}

#Проиграл
{330}{}{Motherfucker!}
{331}{}{Fucking luck}
{332}{}{I lost *again*!}
{333}{}{That's okay, I have some change left}
{334}{}{Ahh shit, when this is going to end!}
{335}{}{I'm gonna tear her to pieces now!}
{336}{}{Not my day... Fuck...}
{337}{}{Am I such a loser?}
{338}{}{It's time to quit this shit...}
{339}{}{Fucking hell, what a bad luck.}
{340}{}{Soon I'll be left with nothing.}
