{100}{}{You see a casino bouncer.}

{101}{}{You see a casino bouncer. He's HUGE.}
{102}{}{You see a casino bouncer. He looks big. And angry.}
{103}{}{You see a casino bouncer. He's looking at you suspiciously.}
{104}{}{You see a casino bouncer. You thought only mutants could be that big.}

{105}{}{I'm warning you - no weapons in the casino.}
{106}{}{Take that head gear off, if you want to go inside.}

#Оружие в руках
{110}{}{Hey, you! Take that weapon away!}
{111}{}{I'm warning you - take the weapon away!}
{112}{}{No guns in the casino!}
{113}{}{Hide the weapon!}
{114}{}{You're not allowed with that weapon!}
{115}{}{Hey, hide the weapon!}

{116}{}{One more time - hide the weapon!}
{117}{}{I repeat - no weapons!}
{118}{}{I repeat - no weapons in the casino!}
{119}{}{Take that weapon away AT ONCE!}
{120}{}{Weapons not allowed in the casino!}

{121}{}{Hey, the gun. I won't going to repeat myself!}
{122}{}{Hmm, looks like, someone looking for trouble.}
{123}{}{I'm warning you for the last time.}
{124}{}{You didn't hear me? I can make gestures!}
{125}{}{Looks like it's time to neutralize someone.}
{126}{}{Hide the weapon, and nobody going to get hurt.}

{127}{}{That's it, dickhead, you're up!}
{128}{}{Now, I warned you!}
{129}{}{Tough guy? We'll see about that!}
{130}{}{We'll have to teach you some manners!}
{131}{}{That's it - you're in deep shit!}
{132}{}{You asked for it, dickhead!}
{133}{}{ALARM! WE GOT HOSTILES IN THE CASINO!}

#Попы'ка заговори'ь
{150}{}{Good evening}
{151}{}{I'm not allowed talking to clients}
{152}{}{Problems?}
{153}{}{What do you want?}
{154}{}{Sorry, not my problem}
{155}{}{Ask the administrator}
{156}{}{I can't get distracted for talking}

#Наркоман:
{160}{}{Hey you! We don't need addicts in here. Get out. Have your withdraw somewhere else. You hear me?}
{161}{}{Don't even think touching me, you're gonna feel the nerd rage otherwise! Hi-i-a-a-h!!!}
{162}{}{Right, I hear you...}

{163}{}{Are you high? I don't recommend you being in here}
{164}{}{What's up with your skin? Is this contagious?}

#Балаклава:
{170}{}{Hey! If you want to go around in the casino - show your face. We have to see, who are you.}
{171}{}{[Leave silently]}

#Female character:
{1127}{}{That's it, you bitch, you asked for it!}
{1128}{}{Now, I warned you, you cheap whore!}
{1129}{}{Tough, huh? We'll see about that!}
{1130}{}{We'll have to teach you some manners!}
{1131}{}{That's it - you're fucked!}
{1132}{}{You asked for it, you slut!}
{1133}{}{ALARM! WE GOT HOSTILES IN THE CASINO!}
