{100}{}{You see a townsperson.}
{101}{}{You see a rather sketchy looking man.}

{110}{}{[He is hurriedly shooing you away] Keep moving, we're having an important conversation with my partner.}
{111}{}{Cut the shit. I'm going to give you the chemist and his friend. In return, I need your recommendation for Stryker.}
{112}{}{You're interfering with an important business here. I'll pay you $1,000 for both of you if you get off the street.}
{113}{}{I know why you're here. Here's my offer - either you get off the street, or me and Mr. Thompson will take care of you.}
{114}{}{You need to get out of here. Immediately.}
{115}{}{Fine, I'm going.}

{116}{}{Good decision. Lead the way, we'll be right behind you.}
{117}{}{Ugh, I didn't want to become involved in this shit anyway. Give us the money and we're out of here.}
{118}{}{Thompson's at the hotel already? Shit, I didn't sign up for this. We're leaving.}
{119}{}{Oh really?}
{120}{}{I'm serious. Uh, Devereaux made a bomb and he's ready to blow this whole building to hell. He's got the balls for it. The man's cornered, you know? He's desperate now, ready to do the hardest thing. Don't make him do it.}
{121}{}{Hell, I knew he was that crazy. Look, you want to run, that's your problem. You're going to get caught anyway. But let the others die, not me. I'll go wait it out somewhere else.}
{122}{}{Good.}
{123}{}{Here's the cash.}
{124}{}{What the hell are you doing here? I'm Stryker's personal consigliere, and you're interfering with my secret deal. Now get out!}
{125}{}{Oh, I'm sorry, we didn't get it right away. We didn't understand the chief's orders that way... No problem, we won't interfere.}
{126}{}{Go.}