{100}{}{You see Nick Hauer.}
{101}{}{You see a man in dark sunglasses and a dusty robe. It looks like he's been through a lot of traveling in the desert.}
{102}{}{They're close...}
{103}{}{Thank you, friend. We couldn't have done it without you.}
{104}{}{Thanks for the help. All that's left is to bury the dead and head off to San Francisco. This is gonna be a tough one to forget.}
{105}{}{What? What's he saying, Terry?}

{110}{}{Stop! Do you hear that?}
{111}{}{They're closing in on us, Nick. This is not good.}
{112}{}{Dammit! Deveraux's family slowed us down. We've got no choice, friend. We can't slip away in this moonlight without being seen. Got any ideas? Maybe we should hide in this house and hope its walls will protect us.}
{113}{}{That thing will go up like a candle. You run, I'll hold them off.}
{114}{}{If we take a stand in here, we might make it.}
{115}{}{Still playing the hero, friend? Well, good luck - it'd be a terrible waste for a man like you to die for strangers.}
{116}{}{Just go. We're running out of time.}
{117}{}{I can can take of myself. You should focus on keeping them safe.}
{118}{}{You're right. This is gonna be a shitty night.}
{119}{}{Let's go!}

#Female version
{1103}{}{Thank you, friend. We couldn't have done this without you.}
{1115}{}{Still playing the hero, friend? Well, good luck - it'd be a terrible waste for a woman like you to die for strangers.}
