{100}{}{You see a child.}
{101}{}{You see an ordinary, snotty kid.}
{102}{}{}
{103}{}{Hey! Give that back!}
{104}{}{Give me back my game or... Or I'll get angry!}
{105}{}{That's right, none of your business!}
{106}{}{You affected the outcome of a dispute. Let's hope you made the right choice.}

#Dialogue:
{110}{}{[The two kids are in a heated argument over who gets the game] NO! IT'S MINE! Woah - who are you?}
{111}{}{I'm just wondering what you're fighting over.}
{112}{}{[The first kid:] Well, I found this game in an old building, but HE took it and won't get it back! [Second:] I said we should go to the building! If it weren't for me, we wouldn't have found it!}
{113}{}{Hey, calm down, now...}
{114}{}{[First:] But I found it! That means it's mine! [Second:] But I'm a year older than you! That means I get to decide who gets it!}
{115}{}{Hey! Cool it off already!}

{116}{}{[First:] Yeah, what do you think? I should get it, right? [Second:] No, I should! Tell him!}
{117}{}{All this for a game? I couldn't care less.}
{118}{}{[Talk to the first kid] You need to respect your elders. They're smarter and more mature. Listen to your older brother.}
{119}{}{[Talk to the second kid] He's the one that found it. You can't just take it because you're older than him. Give it back.}
{120}{}{Why can't you share it? You're brothers, after all.}
{121}{}{Well, why don't you play for it? Winner gets the game.}

{130}{}{[First:] Ha! I knew the grown-ups wouldn't care. I'm taking it! [Second:] You even try and I'll knock your block off! You little...}
{131}{}{See you later, kids. Well, one of you, at least, at the rate this is going.}
{132}{}{[First:] What?! Aw... [Second:] Yeah, that's right! I'm more mature, so I get the game! [he turns and waves his butt at the first kid while making a farting noise with his lips] Suck on it!}
{133}{}{Well, have fun...}
{134}{}{[First:] Ha! Even the grown-ups think you're a jerk! Now give me that game! [Second:] Fine, keep it! I don't even want this stupid game! It's for babies anyway!!}
{135}{}{Well, have fun...}
{136}{}{[First:] Because he's a jerk! [Second:] Because he's a stupid baby!}
{137}{}{You both sound like stupid jerk babies from where I'm standing. Neither of you even want to listen to each other! Why don't you try and learn something from playing this game together?!}
{138}{}{[First:] Hmph... Okay. We'll share. [Second:] Yeah, fine... It takes two people to play it anyway.}
{139}{}{Great! Let this be a valuable lesson. It'll come in handy someday.}
{140}{}{Your powers of persuasion have earned you 100 experience.}
{141}{}{[First:] Yeah, that's a great idea! That's fair, let's play! [Second:] Sure! And when I win, you'll know I deserved it all along!}
{142}{}{I'll play.}
{143}{}{I'll watch.}
{144}{}{ ... [First:] Hey, that's not fair! You won because you're a grown-up! [Second:] Yeah, we shouldn't have let you play at all!}
{145}{}{But you did! And now, you have nothing to fight over! Problem solved. Hahahahahaha! [take the game]}
{146}{}{ ... [First:] Ha! I won! Take that! It's mine! Mine!!! [Second:] Yeah, well, you can take it! It's a baby game anyway! I don't care!}
{147}{}{ ... [First:] Aw, no! I lost! Man... [Second:] HA! Now you don't get to complain anymore. It's mine now, all mine, and I'll NEVER let you touch it again!}
{148}{}{Well, fair's fair.}
{149}{}{The little children were no match for your hustling skills. You earn 100 experience.}