{100}{}{You see a boy.}
{101}{}{You see a sad, confused child.}

{102}{}{Thank you so much! Now I can go home!}

#Before sorting things out with barman
{110}{}{Please, sir, I really need your help! Please, just a little change. As much as you can spare! I don't ask for much...}
{111}{}{Maybe I should bring you some food instead?}
{112}{}{Where are your parents, kid?}
{113}{}{Sure thing, kid, here's a tenner. Enjoy a hot meal.}
{114}{}{Scram, kid, you're not getting anything off of me!}
{115}{}{Sorry, not today.}

{116}{}{No, sir, I'm not hungry. It's not even for me.}
{117}{}{Then why are you begging?}
{118}{}{At home, waiting for me... I have to bring home everything I earn at the cafe, but the bartender only paid me half! That's a whole 100 bucks! If I go home without that money, they'll beat me until I can't sit down!}
{119}{}{Wait, he only gave you half? How could he?!}

{120}{}{Yes, sir! That's it! Maybe I'm not the best worker, but I worked hard for the whole week! Greedy asshole, that's who he is!}
{121}{}{Whoa, calm down, kid. Let me talk to him.}
{122}{}{Look, kid, I've got bigger problems. You're on your own.}
{123}{}{How much did you say it was? 100 bucks? How about I give you that myself and you go on your way?}

{124}{}{Thank you, sir! Thank you very much! Now I only need 90 bucks so my parents don't beat me. Awesome!}
{125}{}{Heh, you're pretty sharp for beggar, you know that? First 10 bucks, now 90...}
{126}{}{That would be great!}
{127}{}{I don't think so.}
{128}{}{But sir...}
{129}{}{Welcome to reality, kiddo. Get used to it.}
{130}{}{[His jaw drops open] What, really?!}
{131}{}{Of course, here's the rest of your pay.}
{132}{}{Oh... Sorry, I don't have that kind of money on me right now. Hold on a second.}
{133}{}{Oh wow! You're the best person I ever met! Really, really! I wanna be just like you!}
{134}{}{No problem, kid. See you.}

#Second dialogue
{140}{}{[This kid is still standing, begging]}
{141}{}{}
{142}{}{Here's the money.}
{143}{}{Milton wants you out of here, so he gave me the money... And I'm keeping it, sucker! Now get the hell out of here before I kick your ass!}
{144}{}{[Keep walking.]}

{145}{}{[Scared, the kid runs away from you, but, after retreating to a safe distance, turns around and flips you the bird.]}
{146}{}{You better hope I don't see you again, you little bastard!}

#After end of game
{150}{}{Hold up, mister! You remember me, right? You helped me out at the cafe...}
{151}{}{You were the kid from the Cotton Club, right? The bartender didn't want to pay you for your work, so I helped you out.}
{152}{}{That's right. You really saved my butt!}
{153}{}{Wait, you don't need money again, do you?}
{154}{}{No-no! I only wanted to thank you again. [he pulls out a plasma grenade] I found this while digging through the trash. You probably need it more. Buh-bye!}
{155}{}{Wow, the things people throw away... Thanks, kid!}

#Female version
{1110}{}{Please, ma'am, I really need your help! Please, just a little change. As much as you can spare! I don't ask for much...}
{1116}{}{No, ma'am, I'm not hungry. It's not even for me.}
{1120}{}{Yes, ma'am! That's it! Maybe I'm not the best worker, but I worked hard for the whole week! Greedy asshole, that's who he is!}
{1124}{}{Thank you, ma'am! Thank you very much! Now I only need 90 bucks so my parents don't beat me. Awesome!}
{1128}{}{But ma'am...}
{1133}{}{Oh wow! You're the best person I ever met! Really, really! I wanna be just like you!}
{1142}{}{Here's the money.}
{1143}{}{Milton wants you out of here, so he gave me the money... And I'm keeping it, sucker! Now get the hell out of here before I kick your ass!}

{1150}{}{Hold up, miss! You remember me, right? You helped me out at the cafe...}