{100}{}{You see Nick Hauer.}
{101}{}{You see a man in dark shades and an old duster, which obviously seen many miles of wasteland. He holds a walking cane in both hands.}
{102}{}{I'll wait here.}
{103}{}{Greetings!}

#First talk
{110}{}{So, we finally meet. You weren't followed, right?}
{111}{}{Me? Followed? Why would I be?}
{112}{}{I didn't notice anything. What's up?}
{113}{}{You stand out in a crowd, and these gangsters have eyes and ears everywhere. Hell, one spy could be working for both sides. That's just how it is around here. So, you definitely attracted some attention.}

{114}{}{A little birdie told me you've been in Stryker's lab, and I thought you just *might* listen to the voice of reason. See, Stryker's holding my friend Terry against his will. I'd like to help him, but I can't get into the lab. Stryker keeps everyone out... Everyone but you, it seems.}
{115}{}{No. I'm a mercenary, but I'm not crazy.}
{116}{}{What are you offering?}
{117}{}{I'll be happy to help cleanse this world of slavery.}

{118}{}{I hear you. I'm not asking you to storm the place, that would be crazy. I mean something with more... Finesse. Also, I've got to say - I haven't spoke with Terry for a long time, I don't know if he has changed over these ten years. But I have a feeling that he needs help.}
{119}{}{Well... While traveling, I've managed to save 350 bucks. Not a whole lot for such a risky job, I understand, but it's all I've got.}
{120}{}{You got no idea how happy I am to hear that, friend. I haven't talked to Terry in years, but I know he'd never want to be locked up, no matter what they're doing for him.}
{121}{}{What's your plan?}
{122}{}{I'm out. This job isn't for me.}
{123}{}{Hmm... That's not what I expected from you. Well, keep me in mind, anyway.}
{124}{}{First step? You gotta get a message to him. I'm offering him to make a run to San Francisco. It's way, way west of here - they're never find us. The hard part is getting him out.}
{125}{}{If you want my help, I need to know more about you and Terry.}
{126}{}{I'll see what I can do.}

{127}{}{Now is not the best time for such a long story. The short version is, we grew up together, went into business together. Then the civil war had separated us, ten years ago. I ended up in San Francisco. Now I'm back, to ask him to escape together.}
{128}{}{What happened ten years ago?}
{129}{}{What kind of business did you have?}
{130}{}{How did you end up in San Francisco?}
{131}{}{You were gone for ten years and are just expecting to pick up where you left off with this guy?}
{132}{}{I've heard enough. Take care.}

{133}{}{Businessmen around the city went into full-on war. My house burned down with my family with it, I got blind, Terry got snatched up, and it looks like he's been passed around from one leader to another ever since.}
{134}{}{We dealt with booze, mostly. We were not half-bad - our stuff found its way into the local bars. Not pre-war quality, but better than the moonshine other people were churning out. Problem was, some of those moonshiners didn't appreciate the comparison. Some tough guys they were... Oh, and also, we lent some alcohol for medicinal purposes - obviously, health care in that times was not so good.}
{135}{}{[He sighs] Alright, so, someone set my house on fire. I ran in to find my family. I did, but not fast enough. Then a burning piece of wood fell on me and I got blind. Days of me being suicidal mood went by, until a caravan from San Francisco arrived. They said the doctors there could treat me. Funny sort people. Had funny kind of morals too - made me their lab rat. It was... I don't like to remember it. But I can see again. Better than ever, actually.}
{136}{}{I couldn't do it until now. It took me a long time to get out of San Francisco, and when I did, I was... I'll say it, I was scared. But I worked up the nerve, and I've worked out a plan. I've finally got the chance to help an old friend out... If he wants it.}
{137}{}{Don't wait too long. This city could explode any day.}
{138}{}{Good luck.}

#Оружие
{140}{}{Are you planning to go all the way to San Francisco with just a cane to defend yourself?}
{141}{}{[He shrugs with a sly smile] You think I'd need more than a cane to handle a few geckos? I'm tougher than I look, you know. I wouldn't suggest you test that.}
{142}{}{I don't think that stick of yours can kill a gecko, and I've swung a few in my time. There's something special about it, right?}
{143}{}{Hmm... You're pretty sharp, kid. [in one fluid motion, he pulls a blade from the cane; it looks a little dull, but perfectly balanced] It was made by my special inquiry, in San Francisco. I don't like to use it if I can avoid it, but sometimes, I don't have a choice. You tend to look like a target when you've got "just a cane". I still try to stay off the roads and away from settlements, if I can.}
{144}{}{I'll be sure not to make that mistake. See you around.}
{145}{}{You received }
{146}{}{ experience for correctly identifying the weapon.}

#Second talk
{150}{}{Thanks for the help, but we're not done yet. I've seen a couple serious-looking types checking us out. I think we're being watched.}
{151}{}{How do they know what we're up to? And why aren't they attacking?}
{152}{}{I think they're just watching the exit until there's less people around. I don't think they'll wait around much longer, though.}
{153}{}{[Next]}
{154}{}{We need a way to slip past them.}
{155}{}{How about the window?}
{156}{}{Good idea, but we'll need rope. The shop across the road should have some. Hurry! They'll smell something soon enough.}
{157}{}{I have some rope right here, actually.}
{158}{}{I'll see what I can do.}
{159}{}{Did you get the rope?}
{160}{}{Yeah, here you go.}
{161}{}{Not yet, just wait a little longer.}
{162}{}{Thanks, friend. Listen - you've already done a lot for us, so if you want to leave now, I understand. But it would really help us out if you could escort us out of here. What do you say?}
{163}{}{I say yes. You can count on me to cover your backs.}
{164}{}{I sorted out the thugs. The entrance is clear.}
{165}{}{You what?! You are one mad dog, friend! Thanks! Listen - you've already done a lot, so if you want to leave now, I understand. But it would really help us out if you could escort us out of here. What do you say?}
{166}{}{I say no. The less people in your group, the easier it will be for you to slip out unnoticed.}
{167}{}{I guess that makes this goodbye. Good luck, friend. Come on, Terry!}
{168}{}{Good luck.}
{169}{}{Before leaving, Nick gave you all his money - 350$.}

#Female version
{1112}{}{I didn't notice anything. what's up?}
{1114}{}{A little birdie told me you've been in Stryker's lab, and I thought you just *might* listen to the voice of reason. See, Stryker's holding my friend Terry against his will. I'd like to help him, but I can't get into the lab. Stryker keeps everyone out... Everyone but you, it seems.}
{1115}{}{No. I'm a mercenary, but I'm not crazy.}
{1117}{}{I'll be happy to help cleanse this world of slavery.}
{1123}{}{Hmm... That's not what I expected from you. Well, keep me in mind, anyway.}
{1125}{}{If you want my help, I need to know more about you and Terry.}
{1150}{}{Thanks for the help, but we're not done yet. I've seen a couple serious-looking types checking us out. I think we're being watched.}
{1159}{}{Did you get the rope?}
{1162}{}{Thanks, friend. Listen - you've already done a lot, so if you want to leave now, I understand. But it would really help us out if you could escort us out of here. What do you say?}
{1165}{}{You what?! You are one crazy girl, friend! Thanks! Listen - you've already done a lot for us, so if you want to leave now, I understand. But it would really help us out if you could escort us out of here. What do you say?}
{1167}{}{I guess that makes this goodbye. Good luck, friend. Come on, Terry!}