{100}{}{You see the pursuer.}
{101}{}{You see a brutal-looking thug. He looks like a man on a mission.}
{102}{}{The pursuit is over.}

{110}{}{Hey, Deveraux! Why are you running from us?}
{111}{}{Have we not been good to you? Have we not been really nice?}
{112}{}{Stryker respected you. Protected you. Don't you remember?}
{113}{}{And then you stabbed him in the back. Not good, Deveraux. Dirty move.}
{114}{}{Do you want to come out and talk about it like adults?}
{115}{}{About this, or about your friend you snitched to another gang tome time ago?}
{116}{}{That was a mistake, Terry. We get that.}
{117}{}{You can still play this smart. You can still go back.}
{118}{}{It'll be like nothing ever happened!...}
{119}{}{As long as it doesn't happen again.}
{120}{}{We'll even let your friends go! I swear on my mother's life!}
{121}{}{What do you say, Deveraux? Do you want to make this easier for you?}
{122}{}{::waits::}
{123}{}{::sneers::}
{124}{}{Have it your way, Deveraux! We'll do it the hard way!}
{125}{}{Get the fuck out here, you little bitch!}
{126}{}{If you don't come out, we'll poke the place with more holes than in my dad's condom!}
{127}{}{...Fuck it. Lay it on him, boys!}
