{100}{}{You see a stranger.}
{101}{}{You see Maxson.}
{102}{}{You see Balder.}

{103}{}{You see completely bald man. He keeps pulling on his collar.}
{104}{}{You see Maxson. He seems to want to hide his neck under his collar.}
{105}{}{You see Balder, the man that betrayed Big Louie and sneak out of town.}

{106}{}{Big Louie's dirty business is done. You earn 1000 experience points.}
{107}{}{Maxson is trying to escape!}

#Пов'орный приход после первого диалога без опознания
{110}{}{Maxson is in front of you once again, showing off his dreams of Las Vegas. He's miming a cowboy swinging a lasso while trying to ride a bull.}
{111}{}{You still want to go to Vegas?}
{112}{}{Oh. Yes. Have a happy stay.}

#Первый диалог, до опознания
{120}{}{Hello, partner! You're waiting, too?}
{121}{}{No, I'm not. Are you going somewhere?}
{122}{}{No, I'm just passing through.}

{123}{}{Ah, fine then. Take care.}
{124}{}{[Leave]}

{125}{}{Yes, I'm getting a ride to Vegas. They say there's nowhere better in the wasteland to try your luck!}
{126}{}{Las Vegas?}
{127}{}{And what's wrong with Reno?}
{128}{}{Why not go right now?}
{129}{}{And who are you, by the way?}
{130}{}{Fine. Bye.}

{131}{}{The city that never sleeps! They say the bombs barely touched it. Now THAT'S true civilization, brother! Casinos, hotels, and caravans from everywhere in Nevada! Vegas, baby, Vegas! I'M COMING TO YOU, BABY!!! [he dances in place, hooting joyfully]}
{132}{}{In Reno you're either lucky, or dead. I like to have more options.}
{133}{}{Ah, these guys, you know - they're punctual, like clockwork. Too punctual! They won't change their schedule just for one passenger.}
{134}{}{My name? It's... Maxson. Just Maxson.}
{135}{}{Fine... Just Maxson. Maybe we'll meet again.}
{136}{}{You said that very strangely.}
{137}{}{Just a sore throat. Forget it.}

#Распознание
{150}{}{Maxson, right? Have you ever been called Balder?}
{151}{}{You earn 100 experience points for recognizing Maxson.}

{152}{}{[The smile doesn't leave his lips, but it disappears from his eyes] Hey, that's just low! I happen to think the bald look is good on me!}
{153}{}{I'm not talking about your head, idiot. Why don't we we step away and talk privately?}
{154}{}{Yeah? How about I show it to Big Louie and get a second opinion?}

{155}{}{[He fixes you with a hard stare for a moment] Now... Listen. [he looks around and leans in towards you] I just want out. Out of that gang, out of that life. You want my advice, you'll do the same. I just want to disappear. Okay?}
{156}{}{I don't think so. I didn't come all the way here just to walk away.}
{157}{}{Maybe. Why?}

{158}{}{Hmm. I have a VERY lucrative deal lined up in Vegas, and I'm not going to miss it. So what are you going to do? Kill a valuable client of the "Nevada Express" right here in public? Go on, let's see it. Or did you shit your pants already?}
{159}{}{No, shithead, you're coming into the slums with me. I have you in my sights.}
{160}{}{No, shithead, you're coming into the slums with me. Don't even think of running.}
{161}{}{Damn right I will. I don't give a fuck! Just watch me!}
{162}{}{Honestly, I don't really care. I'm leaving.}

#Приня'ие решений - обмен на оружие
{163}{}{If you want out, I can help you.}
{164}{}{You really think I'm going to believe that?}
{165}{}{Why not? You think I want to spend the rest of my life with Big Louie? No, I'd rather have a good friend in Vegas.}
{166}{}{Suit yourself. You're coming to the slums with me. I have you in my sights.}
{167}{}{Suit yourself. You're coming to the slums with me. Don't even think of running.}
{168}{}{Then I have my orders. You think I won't do it? Just watch me.}
{169}{}{Honestly, I don't really care. I'm leaving.}

{170}{}{I don't believe you. What will you tell Big Louie? That you let me go?}
{171}{}{I need to give him your shotgun as evidence.}
{172}{}{I don't know yet. I'll come back when I think of something.}

{173}{}{Nice try. I'm not giving you my only weapon that easily.}
{174}{}{You want to trade for it?}
{175}{}{What, tough choice?}
{176}{}{Let's try again.}
{177}{}{Have you changed your decision?}
{178}{}{Make your decision.}
{179}{}{Naw. I'm only interested in shotguns and rifles.}
{180}{}{I'll come back when I find a solution for this.}
{181}{}{You have found a peaceful solution to the Maxson dilemma.}
{182}{}{Great. I'm sure everyone will be happy now.}
{183}{}{Yes, perhaps.}

#Приня'ие решений - бой в 'рущобах:
{184}{}{[He grits his teeth] Fine... Not like I have a choice. Let's get this over with... }
{185}{}{[Follow him]}
{186}{}{[He grits his teeth] Fine... This is the way it always ends... }
{187}{}{[Follow him, before he escapes.]}
{188}{}{Hey, guys, I've got some business to take care of. I'll be back.}

{191}{}{Ha! You trying to scare me, sugar tits? Your job is to open your legs, not swing your little fists. Fuck off!}
{192}{}{That's it! Watch what my little fists do to your jaw!}
{193}{}{Fine, asshole, wait here. I'll be back!}
{194}{}{Don't even have the balls to go around the corner where we can settle this, huh? Too much of a sissy to face me like a man?}
{195}{}{[His eyes flare] Sissy?! You just fucked up, whore!}
{196}{}{Don't try to run. I'm watching you.}
{197}{}{Nice try. But you can't trick me that easily, lady.}
{198}{}{Suit yourself. Then we'll do it right here.}
{199}{}{Fine, shithead, wait here. I'll be back.}
{200}{}{And leave me without a weapon? No, you can't pull that shit on me.}

#Плавающие фразы:
{201}{}{Let's get this over with.}
{202}{}{Well, well... }
{203}{}{Wait, this won't take long... }
{204}{}{You're making a mistake. A big mistake.}
{205}{}{This won't take long.}
{206}{}{What did I do to deserve this?!}
{207}{}{Oh shit, what the fuck... }
{208}{}{And the day started so well... }
{209}{}{We could solve this peacefully... }
{210}{}{Too late, you know... }

{220}{}{And... RUN!}
{221}{}{Time to get the fuck away!}
{222}{}{Feet, don't fail me now!}
{223}{}{Time to run!}
{224}{}{Full speed!}
{225}{}{As long as I'm not seen, I can escape... }

{228}{}{Yes, I'm coming! I'm coming!}
{229}{}{We could make a deal... }
{230}{}{It's your move! Just leave me alone!}

{231}{}{Well, well, what do we have here?}
{232}{}{[Next]}

#Female character
{1120}{}{Hey, little lady! You're waiting, too?}
{1131}{}{The city that never sleeps! They say the bombs barely touched it. Now THAT'S true civilization, sister! Casinos, hotels, and caravans from everywhere in Nevada! Vegas, baby, Vegas! I'M COMING TO YOU, BABY!!! [he dances in place, hooting joyfully]}
{1156}{}{I don't think so. I didn't come all the way here just to walk away.}
{1158}{}{Hmm. I have a VERY lucrative deal lined up in Vegas, and I'm not going to miss it. So what are you going to do? Kill a valuable client of the "Nevada Express" right here in public? Go on, let's see it. Or did you piss your panties already?}
{1170}{}{I don't believe you. What will you tell Big Louie? That you let me go?}
{1204}{}{You're making a mistake. A big mistake.}
{1230}{}{It's your move! Just leave me alone!}
