{100}{}{You see a caravan merchant.}
{101}{}{You see an ordinary caravan guard. He's eating right now.}

#Попытка заговорить при отрицательной репутации у караванщиков
{110}{}{I've heard a lot of things about someone that looks like you. And none of it was good.}
{111}{}{Uh...I'm busy. Talk to someone else.}
{112}{}{Er...no thanks, I don't need anyone to talk to.}
{113}{}{Look, can you just leave me alone?}

#Диалог
{120}{}{Hello.}
{121}{}{Is this table free?}
{122}{}{Bye.}

{123}{}{I'm not buying you anything, if that's what you want. But I won't say no to a little chat.}
{124}{}{Yes, let's chat. You're with the caravan right?}
{125}{}{Bye, then.}

{126}{}{Yeah, I'm one of the guards. You want to talk to my boss, he's in the parking lot. Look for the guy in metal armor.}
{127}{}{Tell me about the caravan business.}

{128}{}{Reno's got about a dozen independent caravans, but they only work the local market - small-time stuff. There's only two inter-city caravans with branches in Reno - one based in Las Vegas, and the other in Salt Lake City. Sometimes you get a caravan from the east, but that's rare. You've also got the "Nevada Express", but they only move people, not goods.}
{129}{}{You mentioned caravans going east and west. What about north and south?}
{130}{}{Why doesn't the "Nevada Express" transport goods?}
{131}{}{Tell me about the local independent caravans.}
{132}{}{Why doesn't Reno have its own inter-city caravan?}
{133}{}{This was very informative, but I have to go.}

{140}{}{The north doesn't have anything more than a few small settlements. They've never got enough to make the trip worth it.}
{141}{}{ I've heard someone set up a route to Black Rock recently, though, so maybe that's changing.}
{142}{}{[Next]}
{143}{}{And the south? Forget it. The barren desert's bad enough, but once you get past that, the land's been scorched with nuclear bombs. The further you go, the worse it gets. They say there's a city once you get far enough, but it can't be worth the trouble. I've heard only of one caravan, who made the trip up from there. I've never seen him, but I've heard he's a real mess.}
{144}{}{I see. What else can you tell me about the caravan business?}

{145}{}{They've actually managed to fix up some old buses from before the war. They're great for moving a lot of people fast, but they're a hell of a lot less robust than our brahmin-driven carts, and, after 70 years, those highways aren't what they used to be. They can't afford to risk their machines by taking on that weight.}
{146}{}{Not much to tell, really. They deal with farms and other people on the outskirts of the city. A few of the braver ones even deal for food with the Cheyenne, but I hear they don't have much to offer recently.}
{147}{}{There's way too much fighting in Reno to start up a new business. Anyway, it's not easy - or cheap - to go on such a long and dangerous journey. Vegas and Salt Lake City are a bit better off and can afford to equip their own caravans, but Reno's in no state for something like that.}
