{100}{}{You see Barton the trader.}
{101}{}{You see a tired trader, lazily picking through his stock on a table.}

#Barter:
{110}{}{Looking for something, friend?}
{111}{}{Yeah, show me what you've got.}
{112}{}{Don't think I am. Goodbye.}

{113}{}{Pleasure doing business with you. Anything else?}
{114}{}{Show me what you have again. I think I forgot something.}
{115}{}{Yeah, I think that's it. Goodbye.}

{116}{}{Look who it is! Always happy to see you. Good must be answered with good, right? I think I can make you a little discount on you-know-who's recommendation. I don't give prices like that to everyone!}
{117}{}{Let's get to it then.}
{118}{}{Appreciate it, but I'm not here to buy.}

{119}{}{I talked to some caravaneers recently. They say a lot of good things about you. I think you deserve a little discount.}
{120}{}{I talked to some caravaneers recently. They don't have many nice things to say about you. And I value their opinion. So, from now on, this place will be more expensive to you. And don't even try to argue, you know what you did.}
{121}{}{Everyone in the local slums is talking about you. I appreciate what you do for these poor people. If you're going to buy from me, I'll make sure to give you a nice discount.}
{122}{}{Everyone in the local slums is talking about you. And not in the best of ways. You know what happens to people who act like that in this city? Their prices get raised so they get the hell out of here. But, I don't want to fight, unlike some of the others. Just know that my prices for you are now higher.}
{123}{}{You received a 10% discount at Barton's store.}
{124}{}{You received a 5% discount at Barton's store.}
{125}{}{Sheriff? You're the new Sheriff of Uranium City? Amazing! It's an honor to see you in my store. By the way, I saved up a little something for a special client. A .44 revolver and some ammo! I think it will fit your holster quite well. I'll sell it at a discount.} 
{126}{}{[Noticing your shady appearance, he scowls before shaking his head] Don't even think about it. I see your types from a mile away. Keep your hands where I can see them!}
{127}{}{Barton has recognized your thieving tendencies and raised his prices by 10%.}
{128}{}{Hey, would you look at that. A bunch of marauders recently cracked open the Hawthorne base. Dragged out anything that wasn't nailed down. Got some sweet new toys. Take a look, maybe you'll find something you like.}

{130}{}{What's that on the counter? Stagecoach tickets?}
{131}{}{Yeah. The stagecoach only takes cash, so I buy a few tickets from the "Nevada Express" for those who want to barter other things. Feel free to get one, it's easier than waiting until your wallet fills up.}
{132}{}{What's the catch?}
{133}{}{Great, let's trade.}
{134}{}{There is none. You see, the stagecoach only takes cash, so I... Wait, I already said that. Otherwise, it's all up to you. Feel free to buy from the "Nevada Express" administrator if you have the cash.}
{135}{}{And I still smell rat. You wouldn't have done this if you didn't see profits along with the deal.}
{136}{}{[Twists his lips in a grim smirk] Well, you got me. Yeah, I do get a profit. Buying tickets from me is much more expensive. But I think that's fair, considering I need to process the bartered goods later.}
{137}{}{Thanks, but I was here for something else.}

#About Jay
{140}{}{I'm looking for Jay Kukish, a biker. Seen him?}
{141}{}{Well, not like I know the bikers by name. Although, there have been a lot of them recently, seemed like they were planning something. Saw one go over to stay the night at the Silver Legacy. Ask the guy at the front desk for more info.}
{142}{}{Thanks.}

##############################################################################
#
#                            Questions
#
##############################################################################

#Questions
{250}{}{I have a question.}
{251}{}{Shoot.}
{252}{}{Nothing else for now.}
{253}{}{Thanks, but I have another question.}
{254}{}{That's enough for now.}

#Suggestions
{255}{}{I'm new here. Mind helping out with some advice?}
{256}{}{Well, I wouldn't suggest going anywhere further than El Dorado. The city is dangerous for newcomers. Street thugs, dealers, just scum and, finally, revolutionaries from both sides - it's easier than ever to find trouble. Our little district around the hotel is the safest and most cultured place. You know what - just go talk to the receptionist at the hotel. He'll tell you a lot more about the city than me.}
{257}{}{Why are there so many caravaneers here?}
{258}{}{This place is the only caravan stop in town. Good place to rest before a new route. All the better for me - they tend to have some great wares. That's why most of the trade in the city is centered here.}

#Slaves
{260}{}{I'm looking for a slave... Well, a particular slave.}
{261}{}{Hey, listen, I don't deal in slaves. Not like they're popular around here. The residents aren't living any better - except they don't wear collars.}
{262}{}{Well, let's suppose I need a slave. Where would I get one?}
{263}{}{Hm, usually, those who need slaves either form a special squad or order from Vegas. But that rarely happens. The biggest slave owner around here is Mister Oliver Luciano. You could try and buy a slave from him. Wright also used to buy slaves, before he closed his mines.}
{264}{}{So, Luciano then. Thank you for the advice.}

#Bikers
{265}{}{What do you know about the bikers?}
{266}{}{Not much. They don't like to talk about their lives and don't tend to stick around for long. Most consider them an ordinary gang - wanderers with good guns and an intolerable attitude. But the "Nevada Express" is talking about bikers hitting one of their stagecoaches. Sounds rather convincing. Ask Tuco, if you want to hear more about the attack.}

#B.Lou's Traitor
{270}{}{Did you see a fat man with a scar on his neck?}
{271}{}{You know who the bald guy at the entrance is?}
{272}{}{Where's that bald guy at the entrance now?}

{273}{}{Yeah, saw someone like that. Hung around the caravaneers, wanted to go somewhere. Ask them, they might tell you more.}
{274}{}{Shady guy. Speaks like a bandit but his clothes are fine and tries to keep a high tone. Definitely just visiting, especially when he's trying to cut a deal with the caravaneers. They aren't stupid either, can smell something's off. Don't know anything else.}
{275}{}{Think he left for Vegas with a caravan, if my memory serves me right.}

#About Nuka-Cola
{276}{}{We could organize a deal about Nuka-Cola sales.}
{277}{}{But I don't sell food. The caravaneers buy from the Silver restaurant. Or, in the worst case, that small cafe near El Dorado. Perhaps they'd be more interested.}
{278}{}{Restaurant or cafe? I'll go see if they're interested.}

#About weapon sales
{282}{}{What's with the scant weapon stock?}
{283}{}{[Surprised] You're kidding?! In this city, you're lucky if you find a good rifle just being traded, and if for a reasonable price - double lucky!}
{284}{}{Why?}
{285}{}{Hm, good question. Let me try and explain why I think it's so.}
{286}{}{Go ahead, I'm curious to hear it.}
{287}{}{Not now.}
{288}{}{First of all, this city never had much military presence before the Great War, so there's only civilian weapons here. And, as soon as a good gun appears on the market, it's bought by some rich gangster. Even ancient pieces are getting used, like by the El Dorado guards, for example.}
{289}{}{[Continue]}
{290}{}{You're probably wondering where the military arms are, the most powerful and reliable. My best bet would be that there's some left on the army bases, since nobody managed to get in yet. I heard talk of three bases around Nevada. Those brave enough to try and return told about deadly defense turrets and even of terrible mutants. Those are all rumors, but they seem to carry some weight. How else would you explain such a lack of military-grade arms in a country with such a militaristic past? Although, if anyone around has great arms, then it's Wind of War. They store everything they could loot or trade at their base.}
{291}{}{What is that weapon you mentioned the El Dorado guards carrying?}
{292}{}{Tommy guns? They're pretty damn ancient, belong in a damn museum. I'm pretty sure the owner bought them just for the sake of style. Showing off and nothing else. I think he managed to buy every Tommy gun in the state. At the very least, I didn't see any outside of El Dorado.}
{293}{}{Thanks for explaining.}

#Bundy's photo
{294}{}{This girl from the photo, has she ever shown her face here?}
{295}{}{Cute, but her type doesn't tend to come around here.}
{296}{}{What about the name Ted Bundy. Does it mean anything to you?}
{297}{}{Nothing. I sell goods here, if you want info - ask a bartender. Heh, they like that kind of thing - it's their job.}
{298}{}{Got it.}

#Affiliate
{300}{}{Is this the only normal shop in Reno?}
{301}{}{Well, how should I put it... I have the biggest shop in Reno - that's true. All thanks to the caravan stop and their personal trust. But I have an affiliate down south. And he tends to have some fancier stock.}
{302}{}{Tell me more about this associate.}
{303}{}{Well, I've got a helper of sorts. The type of risky fella who trades down south. The only normal town down there is the Hub. Although the road there is long and hard. You'll need to comb through most of the southern roads. His name's Hardy, by the way. You won't confuse him with anyone else - ghouls are rare in these parts.}
{304}{}{Hm. The costs of such a dangerous trip should cover themselves twice. That means the south has something special. Why only one caravan then?}
{305}{}{Hey, you seem to know a thing or two about trade! You know, our region got really lucky - most of the city was left undamaged by the Great War and the radiation was lower. But, in the south, any decently sized city was reduced to radioactive rubble. But it's much easier to find weapons and ammo. That's why the biggest branch of trade we've got is our meds and supplies for their guns. And the reason it's just one caravan is because there aren't really enough people willing to risk their lives.}
{306}{}{Is there a caravan going to the Hub anywhere?}
{307}{}{About Hardy. I need to send a note to the Hub through him.}
{308}{}{You received 100 exp for successfully using your barter skill to learn about a caravan route.}

{310}{}{I need to send a note with him to the Hub.}
{311}{}{No problem, I'll pass him the letter. But I'm expecting a tip, understand?}
{312}{}{Considering your reputation, I'll do it. No problem.}
{313}{}{Great. Here it is and a hundred bucks for your troubles.}
{314}{}{Great. Here it is.}
{315}{}{No thanks, I think I'll try and find Hardy to give the letter personally... }
{316}{}{Then I wish you luck. Oh, how you'll need it. The route to the south is difficult for a caravan, and there almost no settlements. So the search could take quite a while.}
{317}{}{Understood.}
{318}{}{You completed Lewis Birch's task.}
{319}{}{The package fell out of your bag while you were talking to the trader.}

#Female version:
{1110}{}{Looking for something, beautiful?}
{1114}{}{Show me what you have again. I think I forgot something.}
{1136}{}{[Twists his lips in a grim smirk] Well, you got me. Yeah, I do get a profit. Buying tickets from me is much more expensive. But I think that's fair considering I need to process the bartered goods later.}
