{100}{}{You see a caravan merchant.}
{101}{}{You see an ordinary caravan guard. He's eating.}

#Ïîïûòêà çàãîâîðèòü ïðè îòðèöàòåëüíîé ðåïóòàöèè ó êàðàâàíùèêîâ
{110}{}{I've heard a lot of things about someone that looks like you. And none of it was good.}
{111}{}{Uh... I'm busy. Talk to someone else.}
{112}{}{Er... no thanks, I don't need anyone to talk to.}
{113}{}{Look, can you just leave me alone?}

#Äèàëîã
{120}{}{Hello.}
{121}{}{Is this table free?}
{122}{}{Bye.}

{123}{}{I'm not buying you anything, if that's what you want. But I won't say no to a little chat.}
{124}{}{Let's chat then. You are with the caravan right?}
{125}{}{Bye, then.}

{126}{}{Yeah, I'm one of the guards. If you are looking for my boss, he's in the parking lot. The guy in metal armor.}
{127}{}{Tell me about the caravan business.}

{128}{}{Reno's got about a dozen independent caravans, but they only work the local market - small-time stuff. There's only two inter-city caravans with branches in Reno - one based in Las Vegas, and the other in Salt Lake City. Sometimes you get a caravan from the east, but that's rare. You've also got the "Nevada Express", but they only move people, not goods.}
{129}{}{You mentioned caravans going east and west. What about north and south?}
{130}{}{Why doesn't the "Nevada Express" transport goods?}
{131}{}{Tell me about the local independent caravans.}
{132}{}{Why doesn't Reno have its own inter-city caravan?}
{133}{}{This was very informative, but I have to go.}

{140}{}{The north doesn't have anything except a few small settlements. They never have enough to make the trip worth it.}
{141}{}{ I've heard someone set up a route to Black Rock recently, so maybe that's changing.}
{142}{}{[Next]}
{143}{}{And the south? Forget it. The barren desert is bad enough, but once you get past that, there's a land scorched with nuclear bombs. The further you go, the worse it gets. They say there's a city, if you get far enough, but it can't be worth the trouble. I've heard about only one caravaneer who made the trip up from there. I've never seen him, but I've heard he's a real mess.}
{144}{}{I see. What else can you tell me about the caravan business?}

{145}{}{They've actually managed to fix up some old buses from before the war. They're great for moving a lot of people fast, but they're a hell of a lot less robust than our brahmin-driven carts, and, after 70 years, those highways aren't what they used to be. They can't afford to risk their vehicles by taking more weight.}
{146}{}{Not much to tell, really. They deal with farms and other people on the outskirts of the city. A few of the bolder ones even trade food with the Cheyenne, but I hear they don't have much to offer lately.}
{147}{}{There's way too much struggle to start up a new business in Reno. And it's not easy - or cheap - to go on such a long and dangerous journey. Vegas and Salt Lake City are a bit better off and can afford to equip their own caravans, but Reno's in no condition for something like that.}
