{100}{}{You see Milton.}
{101}{}{You see a tanned, aging man behind a bar counter. He's trying to look friendly.}

####################################################################
#              Writing name
####################################################################

{110}{}{I've decided on a name for my band.}
{111}{}{Sounds great. Write it down on this paper so I don't forget.}
{112}{}{Actually, maybe later.}
{113}{}{[Start writing.]}

{114}{}{[Using a pencil, you write... "}
{115}{}{".]}
{116}{}{[Choose English alphabet]}
{117}{}{[Choose Russian alphabet]}
{118}{}{[Confirm name]}
{119}{}{[Stop writing]}

{120}{}{[You need at least two letters in your band's name.]}
{121}{}{[Keep writing]}
{122}{}{[On the paper, you have written the name "}
{123}{}{[Back]}
{124}{}{[Next letters]}
{125}{}{[Previous letters]}
{126}{}{[Erase the last letter]}
{127}{}{Perfect!}
{128}{}{Actually, no, let me change that...}
{129}{}{Okay.}

####################################################################
#              Sale of eggs
####################################################################

{130}{}{Are you interested in buying gecko eggs?}
{131}{}{Hell yeah! People can't get enough of those things! I'll buy them for }
{132}{}{ bucks each.}
{133}{}{Do you have a regular supplier of eggs?}
{134}{}{Nah. They come from hunters up north and northeast. Sometimes the hunters bring them down themselves, but usually they sell them to caravans right on the spot, who sell them to me. Everyone wins - the hunters can get back to hunting, the caravans make a few extra bucks, and I don't need to get tied down to any contracts.}
{135}{}{I'll sell you all the eggs I've got.}
{136}{}{}
{137}{}{I'll think about the offer.}
{138}{}{Thanks. Here's the money.}
{139}{}{You're welcome.}

{140}{}{Uh... Do you actually *have* any eggs?}
{141}{}{What? They were right here a second ago...}
{142}{}{Hey, I worked hard for these! How about another $10 per egg?}
{143}{}{}
{144}{}{Hey, we're all working hard! I have to run a business here, you know? Take it or leave it.}
{145}{}{Fine, I'll sell the eggs for your price.}
{146}{}{In that case, I'm leaving.}
{147}{}{Hmm... Well, those eggs have been hard to come by, lately. I think my customers will pay a little more for them.}

####################################################################
#              Dialogue
####################################################################

#Barman's greetings:
{150}{}{You going to order something?}
{151}{}{Anything else?}
{152}{}{Glad to see you! How can I help?}
{153}{}{}
{154}{}{}

{155}{}{Show me the menu.}
{156}{}{See you around.}
{157}{}{Got it. Another question, please.}
{158}{}{That would be all, thanks.}

#Bundy's photo
{160}{}{I'm looking for the girl from this photo.}
{161}{}{Hmm... Nope. Never seen girls with holes for eyes around here. Ha!}

#Question about club name
{164}{}{Why'd you call this place the Cotton Club?}
{165}{}{Huh... I'm not really sure. I think I read it on a poster somewhere and liked the sound of it.}

#Question about bikers
{166}{}{Seen any bikers lately?}
{167}{}{I wish I didn't! Those pricks are really out of control. They got kicked out of most places around here, so they decided to start to shit in my club! Would be nice to get rid of them. Weird, though - I didn't see any bikes. What kind of bikers have no bikes? Weird...}

####################################################################
#              Comedian Quest
####################################################################

# !! Only avaliable for female PC

{170}{}{Got any work?}
{171}{}{Well, I have something in mind, but it's a bit risky.}
{172}{}{Nah, I don't need risk.}
{173}{}{Sounds good. Lay it out.}
{174}{}{One of the "Nevada Express" workers told me about a comedian in Vegas. Apparently, he's looking for work, but he doesn't have enough money to leave. And frankly, I don't have that kind of money either.}
{175}{}{So...?}
{176}{}{So I'll pay $1500 if you deliver him. Not all at once, though - I'll need a couple of shows to build up that kind of cash. But think about it, you'll be the sponsor for the hottest show in Reno!}
{177}{}{I'll see what I can do. Vegas, right?}
{178}{}{Doesn't sound worth my time.}
{179}{}{That's right. I'll be waiting.}
{180}{}{Later.}

{181}{}{Hey, there you are! I was starting to worry you wouldn't be back. I bet you're itching to get that comedian off your hands, huh?}
{182}{}{That's an understatement! Take the bugger before I throttle him!}
{183}{}{You know, I think I'll miss him... Just a little.}
{184}{}{Well, you got him here, which means... We are gonna get rich! Ha! I bet $500 will make you feel better. I'll have the rest of it in a week. Sorry about such delays.}
{185}{}{You'd better have it by then!}
{186}{}{I'll wait, no problems.}
{187}{}{I'm here for the payment.}
{188}{}{Of course, here's $1000, like we agreed. This guy's sharper than a razor, the money's rolling in quick. Not sure how long he'll last, though, with all his... Quirks... And habits.}
{189}{}{What quirks?}
{190}{}{He's tried literally everything here, everything he could anyway! Drugs, sex, gambling, he even set his hair on fire while freebasing. Shit, this guy ain't right in the head, but he knows his job and the crowd loves him. All that's left for me is to rake in the dough... While it's still possible.}
{191}{}{How could you! This is a man's life we're talking about, and you are just milking him like brahmin? Damn, if I knew, I wouldn't have brought him here.}
{192}{}{Yeah, something tells me he won't end well. Anyway, you have fun.}

####################################################################
#              Sweeping the floor
# !!! Not used in 1.0 contact me if you want this translated - TC1
####################################################################

{200}{}{I want to eat... Help... I'm hungry...}
{201}{}{We don't serve beggars. I will ask you to leave.}
{202}{}{[Looks at you, then lowers his head] Ughh...}
{203}{}{Pleeease! I haven't eaten in 3 days!}
{204}{}{Yes I understand, pal, I understand...}
{205}{}{Pleeease!}
{206}{}{Okay. Here how it goes: You want something to eat - work for it. It's a bit of a mess here, you have to sweep, fix the chairs, clean the tables. When you do that, I will feed you. Ok?}
{207}{}{Yes! Yes! Yes!!!}
{208}{}{Greedy bastard! I better just go away from here!}
{209}{}{Oh! So you want it all for free! Dont even think coming to me with complains about, how pitiful you are. Got that?}
{210}{}{[Proudly lift the chest and exit]}

{211}{}{Well, then start right now. There is the rags, and there is the mop. Later I will show you where is the toilet.}
{212}{}{Let's go!}
{213}{}{For cleaning of the room, you get 200 experience points. Janitor - it sounds good!}
{214}{}{(You easily deal with cleaning. A satisfied owner generously rewarded with a tasty sandwich, juicy fruit and a bottle of cold beer!) Hey, you want to stay for a while? Have some beer, huh?}
{215}{}{Beer? This is great!}
{216}{}{No, someone is waiting for me, I'll stop by later. Bye!}
{217}{}{(for some time you sit with this man and talk about Reno and the problems of the caf?. The man pours his soul to you, talks about how he was fed up and and just wants to say, fuck it all in the ass and be done with it, to everything)}
{218}{}{Well, we can always abandon everything, but how to regain it after - this is what we should aim for!}
{219}{}{Yeah, an ass - is an ass. Thats right! And there is nothing you can do about it!}

{220}{}{Yeah... Ah, easy to say. You try to establish your business when there are so many extortionists and druggies!}
{221}{}{Yeah... And and the worst part is - there are no alternatives! Circle of junkies, drug dealers, racketeers! I sometimes just want to give up....}
{222}{}{Have you thought to move to another location, more quieter?}
{223}{}{Why opening your business and suffer? You would be better working for someone, less responsibility!}

{224}{}{Ha! Where is a quiet place here? Around "Silver", but there is already all spots are occupied! The hotel itself has a restaurant, and the caravan has its own merchant, he is the first all profit comes to... But actually, it's an idea, friend! Move that way a little bit, and maybe, I will be able to find something better!}
{225}{}{Ha! Where is a normal workplace here? Except that hotel or casino, but there is already all positions are taken. It's not that nice and dandy there - there is always some shit going on, better to own your own business... But, it's a thought - maybe I need another way to do business?}
{226}{}{Yeah, and make an advertisement so people could find the place, you literaly just sit in the most inconspicuous place! Who will find you here, away from the main street?}
{227}{}{Hmm. Well maybe.}
{228}{}{Well, friend, sorry to bore you with all this crap, I don't even have no one to talk to here. Tale care of yourself! Stop by someday someday.}
{229}{}{Good luck.}

####################################################################
#              Nuka-Cola sales
####################################################################

{300}{}{Hey, hey! I don't see any Nuka-Cola around here. I'm offering to fix this mistake!}

{301}{}{Ha! If you think I'm buying from you, either you're crazy or you think I am! There are more reliable suppliers in this city.}
{302}{}{Ouch! I guess my bad reputation is catching up with me...}
{303}{}{Interesting. Nuka-Cola, eh? Yeah, I've heard about it... Drove, like, a hundred people to the grave this year. It's possible that a factory in Salt Lake City is still maintains quality of its product, but you don't look like a professional trader. Trying to get over humble bartender, are you?}
{304}{}{It's okay. I am *really* working for the factory. Here's my license.}
{305}{}{What, I don't bargain well enough for you? Man, it's not easy breaking into this business...}

{306}{}{...and nobody knows where you actually got it. You won't fool me!}
{307}{}{What the...}
{308}{}{}

{309}{}{Nuka-Cola from the factory! That's a good product... As long as it's legit! What's the price?}
{310}{}{Don't worry, the best one. I work directly with the factory in Salt Lake City.}

{311}{}{Curious. And who delivers it?}
{312}{}{Does it matter?}

{313}{}{Eh, not really, as long as it's not my problem. I'm happy to sell the stock. I'll leave the deliveries up to you.}
{314}{}{I'll handle it, don't worry.}
{315}{}{Good, I'll be back when I decide what to do.}

{316}{}{Great. Then I'll order the vending machine. I think that corner is a good place for it. Just load the product in and collect your share, when the time comes. Sounds fair, right?}
{317}{}{Now, we only need to sign the contract...}

####################################################################
#              Worker child quest
####################################################################

{350}{}{Hey, why didn't you pay that kid outside? Do you know what his parents will do to him?!}
{351}{}{Aw, don't tell me you fell for that crap! The kid just wants some extra cash. He's just another street urchin, just a bit smarter than most.}
{352}{}{You're *sure* you don't owe him anything?}
{353}{}{Uh, yeah, that's right...}
{354}{}{So he never worked at this place?}
{355}{}{Uh, yeah... Okay, I hired him, but I wouldn't say he worked! Look at this mess! I need someone who get the job done right and on time. That kid couldn't even lift a bucket, and you want me to pay him? I gave him half, and he's lucky to get that.}

{356}{}{About that kid...}
{357}{}{I already told you! He should be happy I gave him half. It's more than he deserved.}
{358}{}{Then I'll leave that on your conscience... For now.}
{359}{}{I don't think so. He did his best. No matter how little, he worked hard!}
{360}{}{Pay him! Now! Or it's going to cost a lot more to fix this place up after I'm done with it!}

#Using speech
{361}{}{What about me? How hard am I working? I'm here day and night. This is my livelihood, not a charity!}
{362}{}{So that's how you want it, huh...}
{363}{}{[He sighs] Fine, fine! Just lay off. Here's the money, go give it to him. Goddamn, buddy, you really know how to take a guy on a guilt trip...}
{364}{}{Much better!}

#Intimidation through strength, level or connections
{365}{}{Oh yeah? Just fucking try it. I'll dump your ass in the street like the other trash out back! You don't scare me!}
{366}{}{Wha-a-at?..}
{367}{}{}
{368}{}{Damn right! Just try that again...}

{369}{}{I get it. Bye.}
{370}{}{You bully the weak, thinking no one will stand up for them. But today I'm going to prove you wrong.}
{371}{}{If you don't want problems with my boss, I suggest you pay the kid.}

{372}{}{Wait, don't touch anything! Just, don't! }
{373}{}{Dammit... Fine, here's the hundred bucks. Give it to the kid, please, just leave me alone.}

####################################################################
#              Quest for starting a band
####################################################################

# !! Male characters only

#Beginning quest
{400}{}{Has this stage been empty for long?}
{401}{}{A few years now. I think the last show was before Big Louie and his gang showed up, but that was before I even owned the club. I only reopened the place last year. I've been thinking of dismantling the stage to make room for more tables.}
{402}{}{What's the problem with organizing new performances?}
{403}{}{There's no one left. With the civil war, all of Reno's talent has died, left, or drunk themselves stupid. There are only a few people left and they don't perform anymore.}
{404}{}{Who are they?}
{405}{}{We've had a jazz band a while back, but there's only three members left and they're all old. Why are you so interested, anyway?}
{406}{}{I think I could start a band. I don't think I could perform on my own, but in a band? That's a whole other question.}
{407}{}{Just curious, let's leave it at that.}
{408}{}{Ah, that would be great... But it's probably more trouble than it's worth.}
{409}{}{I can handle it, I've gone through worse.}
{410}{}{I want to try anyway.}
{411}{}{Fine, fine. Just don't expect help from me. I've got my own problems.}
{412}{}{Any suggestions?}
{413}{}{Well, I've seen Ornette around. Used to play the trombone with the old band. Talk to him, he lives in Wright's slums across from the casino.}
{414}{}{Okay.}

{415}{}{About the band...}
{416}{}{Anything on your mind?}
{417}{}{Tell me about the trombone player again. Who is he and where is he?}
{418}{}{Ornette is ready to come back on stage.}
{419}{}{I've found an, uh, "underappreciated" drummer. A little training and he'll be perfect.}
{420}{}{Got us a guitarist. His name's Richard.}
{421}{}{Looks like we've got a band: guitar, drums and trombone. I think I can handle the vocals.}
{422}{}{Don't worry.}

{423}{}{Ornette, he used to play the trombone, but that was a long time ago. You'll find him in Wright's slums across from the El Dorado.}
{424}{}{You managed to convince him?! Huh... I was sure he sold his instrument... Oh well. But one trombone won't be enough. You'll need more - drums, vocals, probably a guitar. Can't help you there though. Maybe Ornette knows someone else? Ask him.}
{425}{}{Good news. Another one or two and we can consider some concerts.}
{426}{}{Richard? Isn't that the drunk I kicked out? I'm surprised you managed to convince him. One guitar won't be enough, though.}
{427}{}{[His mouth drops open] Are you serious?! I didn't think you'd actually do it! Call everyone in, let's see what you've got.}
{428}{}{Got it.}
{429}{}{That's all for now. Wait for the news.}

#First hearing
{430}{}{Looks like everyone's here.}
{431}{}{That's right. We're ready when you are.}
{432}{}{[Continue]}
{433}{}{Can't do that now, can you wait a little.}
{434}{}{Amazing! How do you all manage to handle it so well? Should be better than to peel a potato, right?.. Now, come here, cap, we've got a serious discussion ahead.}
{435}{}{Something happened?}
{436}{}{Not yet. But, you see, nothing is quite that easy. I didn't mention it before because... Well, I didn't think you'd pull it off anyway. But now, seeing how serious you are, it looks like I'll have to tell you. My place is in Mr. Thompson's territory. I have to give him a part of my profits as protection money. But, honestly, it's just robbery, not protection! I'd have more luck with my double-barrel. Anyway, now interest in the club is going to rise.}
{437}{}{So, you think he's going to crack down on you?}
{438}{}{Thompson will want to increase payments. That, and advertising costs - we'll need posters, advertisers, tickets, food, drink. I'm gonna go bankrupt just on that. And I'm not even sure we're gonna turn a profit. So, i need you to do me a favor and talk to Thompson to sort things out. If you are still in, that is.}
{439}{}{I get it. I'll do my best...}

{440}{}{Well, that would be great. But I think that's going to be more problems than it's worth...that's not the point, though. No offence, but this just isn't for you. The audience just isn't going to appreciate your, uh... Unique charisma.}
{441}{}{Oh well, up to you.}

#Finding the gangster
{442}{}{Let's talk about the gangsters.}
{443}{}{Like I said: Thompson's bleeding me dry for protection money. To run the event, I'll need to hand him over a sizeable chunk of the earnings.}
{444}{}{I talked to Thompson. Everything will be fine.}
{445}{}{Mister Thompson has left the business. For good.}
{446}{}{What if we switch sides?}
{447}{}{Could we run the whole thing without gang involvement?}
{448}{}{I'll get back to you about that.}

{449}{}{Dead? You sure? Oh... I thought that was just Stryker spreading rumors. Anyway, it doesn't change anything. We can't do this without proper protection. We'll have to cut a deal with one of the other gangs. Luciano, Bertolini, Wright, anyone will do as long as they can provide the proper security. You might even manage to work out a better deal than what we've had with Thompson.}
{450}{}{What if we WHAT?! These guys aren't the forgiving types! Maybe if Thompson left the scene... But that's not gonna happen any time soon.}
{451}{}{No, too risky. Everyone's gonna want a piece of the action - thieves, punks, you know the types. We need to protect ourselves and our customers. And for that, we need help of influential people.}
{452}{}{Great news! They'll probably send someone over to discuss the details.}
{453}{}{[Next]}
{454}{}{Alright, time to get ready for the concert.}
{455}{}{Anything I should do?}
{456}{}{First off, we need to hang up posters. Try and hire some kids from the slums, the more the better, it'll look good on our rep. Speaking of, here are the posters, already sorted out the printing. They're all black and white, but it's probably for the best. After all, so is your band. Heh-heh-heh!}
{457}{}{Okay. What next?}
{458}{}{Next comes the concert. It's planned for }
{459}{}{You've still got time until 10 p.m., we won't start any sooner.}
{460}{}{Okay, wouldn't want to miss it. See you!}
{461}{}{Let's begin the concert.}
{462}{}{It's time already?}
{463}{}{[Next]}
{464}{}{I get it! You must be kidding. The concert will be on }

#The concert
{465}{}{Are you serious?! Where were you? We've finished the first performance without you. We did great, by the way, not that you'd know!}
{466}{}{I was busy.}
{467}{}{People showed up expecting a four-man band. They expected singing! We disappointed some powerful people tonight. The music was still a hit, but I don't like surprises. Sorry friendo, but you're out of the band. We'll do well enough without you.}
{468}{}{But this is my band!}
{469}{}{[Leave]}
{470}{}{There's more people than you in this band, and you let them down. Sorry pal, you're outvoted.}
{471}{}{Give me one chance!}
{472}{}{NO! NO! And NO!!!!}
{473}{}{Hmm... Looks like the members don't mind. Come in on }

{476}{}{I had to cancel the concert because our protection is gone. You probably already know these people can't help us. We need new arrangement. And as quickly as possible.}
{477}{}{That's not bad.}
{478}{}{ at 10 p.m.. Don't be late.}
{479}{}{Since we've dealt with the security issue, I'll set up the show on a new date. Come in on }
{480}{}{Good!}

{481}{}{Great show! We've completely sold out. It's like the old days - entertainment, community, powerful people spending money... The thing i've been dreaming about for the last ten years. Keep this up and we'll be rich!}
{482}{}{[Next]}
{483}{}{Here's your cut. Listen, we've got to put on another show! Come in on }
{484}{}{Great!}
{485}{}{That's good, but I had to cancel the concert.}
{486}{}{What?! Why?!}
{487}{}{I was told that if I don't stop, then I'm dead. I love music, but not enough to die for it. I don't think the others want to die for it either. Sorry.}
{488}{}{Tell me the details.}
{489}{}{Hm, I don't like this. Let's hope your protection sorts this out.}

{490}{}{Don't know much more. Two guys in masks showed up and stuck some peashooter in my face. I was lucky Ornette was around and scared them off. That's about it.}
{491}{}{Hmm, well, good luck. I'll come in from time to time, don't worry.}
{492}{}{I doubt that. To honest, I don't trust them. They're the types to grab some poor suckers from the streets and say that they're the ones.}
{493}{}{I sorted it out. There's this guy Martin... [explain the details]}
{494}{}{...what the hell is that all about? Jazz is only for blacks? I mean, it's the twenty-second century, I thought we were past that shit already.}
{495}{}{[Next]}
{496}{}{Anyway, since Martin's not a problem anymore, let's set up another show. Come in on }
{497}{}{Here's your cut. Sorry, but that's the last one.}
{498}{}{Ornette and the rest are worried about the situation with Martin and want to part ways. I couldn't convince them otherwise and letting the whole band go just because of one vocalist isn't in my best interests. You get it, right?}
{499}{}{This was one wild ride, friend. It was a pleasure. I'll tell you what, you've got a 50% discount in my club for life. And anyway, you're a celebrity in Reno now. You're somebody. Isn't that worth something?}

####################################################################
#              Naming the band (beginning: 110-129)
####################################################################

{500}{}{À}
{501}{}{Á}
{502}{}{Â}
{503}{}{Ã}
{504}{}{Ä}
{505}{}{Å}
{506}{}{Æ}
{507}{}{Ç}
{508}{}{È}
{509}{}{É}
{510}{}{Ê}
{511}{}{Ë}
{512}{}{Ì}
{513}{}{Í}
{514}{}{Î}
{515}{}{Ï}
{516}{}{Ð}
{517}{}{Ñ}
{518}{}{Ò}
{519}{}{Ó}
{520}{}{Ô}
{521}{}{Õ}
{522}{}{Ö}
{523}{}{×}
{524}{}{Ø}
{525}{}{Ù}
{526}{}{Ú}
{527}{}{Û}
{528}{}{Ü}
{529}{}{Ý}
{530}{}{Þ}
{531}{}{ß}
{532}{}{-}
{533}{}{ }
{534}{}{!}
{535}{}{$}

{600}{}{A}
{601}{}{B}
{602}{}{C}
{603}{}{D}
{604}{}{E}
{605}{}{F}
{606}{}{G}
{607}{}{H}
{608}{}{I}
{609}{}{J}
{610}{}{K}
{611}{}{L}
{612}{}{M}
{613}{}{N}
{614}{}{O}
{615}{}{P}
{616}{}{Q}
{617}{}{R}
{618}{}{S}
{619}{}{T}
{620}{}{U}
{621}{}{V}
{622}{}{W}
{623}{}{X}
{624}{}{Y}
{625}{}{Z}
{626}{}{-}
{627}{}{ }
{628}{}{!}
{629}{}{$}

#Female version
{1355}{}{Uh, well... Okay, I hired him, but I wouldn't say he worked! Look at this mess! I need someone who get the job done right and on time. That kid couldn't even lift a bucket, and you want me to pay him? I gave him half, and he's lucky to get that.}
{1363}{}{[He sighs] Fine! Fine, just lay off. Here's the money, go give it to him. Goddamn, lady, you really know how to take a guy on a guilt trip...}