{100}{}{You see a client.}
{101}{}{You see a dirty wanderer with a pathetic-looking remnants of a bow-tie hanging around his neck.}
{102}{}{[Wipes tears] Thank you, friend, I am eternally grateful!}
{103}{}{Need to get outta here before the "retribution" arrives.}

#Story about grandma
{110}{}{Oh, I see a respectable gentleman has graced this city with his presence! Yes-yes, I'm talking to you, sir. May I say how hard it is to meet a man with good manners these days? ...Would you care to share a glass of Orvietto Classico Campogrande? - but wait! Oh dear! It seems I have left my wallet at home. That's rather unfortunate...}
{111}{}{Don't worry, err, sir. Bartender! A beer for this noble trash of society.}
{112}{}{The things people come up with to grab a free beer. Fuck off, drunk.}

{113}{}{Did you change your mind and decide to keep me company, sir?}
{114}{}{Alright, grab yourself a beer from the bar. My treat.}
{115}{}{Even if, the stench coming off you is more than enough to change my mind. Bye.}

{120}{}{[He downs the bottle almost instantly, loudly belching as he wipes his mouth with the back of his hand] Ugh... You really shouldn't drink this swill. You're far too aristocratic for it, heh-heh... Thank you, just what I needed.}
{121}{}{Looks like that really put a damper on your politeness, eh?}
{122}{}{Well, usually I'm very polite, but sometimes I'm tired of it... Are you really interested? Alright, I'll tell you, not like it's a secret. It's all thanks to my grandma, god bless her. Built herself up to be a prim and proper lady, dressed like she robbed a museum. Lace, junk around her neck... Quite the eckza... Exalted lady. And I lived with it. Even had this thing around my neck. You know why?}
{123}{}{I hope it's not because you were... Too close. Why?}
{124}{}{I'm almost yawning. Anything interesting coming up?}
{125}{}{Apple pie! The way she cooked it... I'd not drink for a week, if only I could taste it. But, this world isn't for grandmothers like her. They made plenty of pies from her when times were tough, fifteen bucks a piece. Now, all that's left is this pendant. Even then, I lost it in the slums somewhere. It was quite the...  exquisite thing.}
{126}{}{Sad story...}
{127}{}{You weren't the one who made her into pies, were you? I'm kidding, I'm kidding.}
{128}{}{Shit, that's not funny! I really loved her. In a good way. But this damn swill from the bar that's swirling in my stomach every day. It's poisoning my life. Gran held me up, gave instructions, slapped my wrist when I drank too much. But, after I lost the pendant...}
{129}{}{Everyone thinks that something else is always to blame. As long as it isn't them.}
{130}{}{Well, that's life.}
{131}{}{Either way, thanks for hearing me out. And an extra thanks for the beer. Come around sometime, I'll be happy to see you.}
{132}{}{Alright, bye.}
{133}{}{You listened to a sad drunk's story and were rewarded with 100 exp.}

#Talking after drink
{140}{}{[He bows clumsily] Happy to see you, so to say.}
{141}{}{I got my hands on an antique piece. You don't recognize it, do you?}
{142}{}{Likewise.}

{143}{}{That's... No way! You really are a noble gentleman! And here I thought that only happened in Gran's stories. Thank you, thank you and thank you once again!}
{144}{}{Happy to help. Here you go, pie-lover.}
{145}{}{Hey, hands off! I don't work for "thanks".}
{146}{}{But... It's just a trinket! Barely worth a bottle cap! Gran would turn in her grave at your words! [he sobs, blowing his nose into his bow-tie]}
{147}{}{Yeah, yeah, same old song and dance... You going to pay or what?}
{148}{}{Fine, you can have it. Just quit whining, granny's boy.}
{149}{}{[He takes his time, digging through his stinking rags. Finally, he turns around, throwing everyone else in the room cautious looks before handing you a handful of dirty coins. You definitely don't want to know where those came from.] All I have... Bloodsucker.}
{150}{}{That's much better. You can have your little trinket now.}
{151}{}{You returned the drunkard's family heirloom and restored his hopes. Perhaps he'll be more confident from now on.}
{152}{}{You returned the drunkard's family heirloom and proved, once again, that this world is no place for the weak of will.}

#Female version
{1102}{}{[Wipes tears] Thank you, friend, I am eternally grateful!}
{1110}{}{Oh, I see a respectable lady has graced this city! Yes-yes, I'm talking to you, miss. May I say how hard it is to meet a woman with good manners these days? ...Would you care to share a glass of Orvietto Classico Campogrande? - but wait! Oh dear! It seems I have left my wallet at home. That's rather unfortunate...}
{1113}{}{Did you change your mind and decide to keep me company, ma'am?}
{1120}{}{[He downs the bottle almost instantly, loudly belching as he wipes his mouth with the back of his hand] Ugh... You really shouldn't drink this swill. You're far too aristocratic for it, heh-heh... Thank you, just what I needed.}
{1131}{}{Either way, thanks for hearing me out. And an extra thanks for the beer. Come around sometime, I'll be happy to see you.}
{1143}{}{That's... No way! You really are a noble lady! And here I thought that only happened in Gran's stories. Thank you, thank you and thank you once again!}
{1144}{}{Happy to help. Here you go, pie-lover.}
