{100}{}{You see a client.}
{101}{}{Before you is a ragged tramp with a pathetic semblance of a bow tie around his neck.}
{102}{}{[Wipes tears] Thank you, friend, I am eternally grateful!}
{103}{}{Need to get outta here before the "retribution" arrives.}

#Story about grandma
{110}{}{Oh, I see the respectable gentleman has graced this city with his presence! Yes, yes, I'm talking to you, sir. May I say how hard it is to meet a man of good manners these days?... Would you care to share a glass of Orvietto Classico Campogrande with me? - but wait! Oh dear! It seems I left my wallet at home. That's rather unfortunate...}
{111}{}{Don't worry, err, sir. Bartender! A beer for this noble cast-off.}
{112}{}{Of all the things people would come up with to grab a free beer... Fuck off, drunk.}

{113}{}{Have you changed your mind and decided to keep me company, sir?}
{114}{}{Alright, grab yourself a beer from the bar. It's on me.}
{115}{}{Even if I would, the stench coming from you is more than enough to change my mind back. Bye.}

{120}{}{[He downs the bottle almost instantly, loudly belching as he wipes his mouth with the back of his hand] Ugh... You really shouldn't drink this swill. You're far too aristocratic for it, heh-heh... Thank you, just what I needed.}
{121}{}{Looks like that really put a damper on your politeness, eh?}
{122}{}{Well, usually I'm very polite, but sometimes I'm getting tired of it... Are you really interested why I'm like this? Alright, I'll tell you, it's not a big secret. All thanks to my grandma, god bless her. Built herself up to be a prim and proper lady, dressed like she robbed a museum. Lace, junk around her neck... Quite the eckza... Exalted lady. And I had to live with it. Even had this thing around my neck. You know why?}
{123}{}{I hope it's not because you were... Too close. Why?}
{124}{}{I'm almost yawning. I hope anything interesting is coming up.}
{125}{}{Apple pie! The way she cooked it... I wouldn't drink for a week, if only I could taste it again. But this world is not for grandmothers like her. When times were tough, she went into pies herself, fifteen bucks a pop. All I was left with was her pendant... But even that I lost it somewhere in the slums. It was a pretty... exquisite thing.}
{126}{}{What a story...}
{127}{}{You didn't make those pies, did you? Just kidding.}
{128}{}{That's not funny! I really loved her. In a good way. But this damn swill from the bar that's swirling in my stomach every day - it's poisoning my life. Gran supported me, helped me to cope, slapped my wrist when I drank too much. But then I lost the pendant...}
{129}{}{Everyone thinks that there's something to blame. As long as it isn't them.}
{130}{}{Well, that's life.}
{131}{}{Either way, thanks for hearing me out. And an extra thanks for the beer. Come around sometime, I'll be happy to see you.}
{132}{}{Alright, bye.}
{133}{}{You listened to a sad drunk's story and were rewarded with 100 exp.}

#Talking after drink
{140}{}{[He bows clumsily] A delight to see you again, so to say.}
{141}{}{I got my hands on an antique piece. Do you recognize it?}
{142}{}{Likewise.}

{143}{}{That's... No way! You really are a noble gentleman! And I thought it only happened in my gran's fairy tales. Thank you, thank you, and thank you again!}
{144}{}{Happy to help. Here you go, pie-lover.}
{145}{}{Hey, hands off! I don't work just for "thanks".}
{146}{}{But... It's just a trinket! It's barely worth a bottle cap! Grandma would be spinning in her grave from your words! [he sobs, blowing his nose into his bow-tie]}
{147}{}{Yeah, yeah, same old song and dance... Are you going to pay or what?}
{148}{}{Fine, you can have it. Just quit whining, granny's boy.}
{149}{}{[He takes his time, digging through his stinking rags. Finally, he turns back to you, giving everyone else in the room a wary look, and hands you a handful of dirty coins. You definitely don't want to know where they came from.] All I have... You bloodsucker.}
{150}{}{Much better. You can have your little trinket now.}
{151}{}{You returned the drunkard's family heirloom and gave him back hope. Perhaps he will be more confident from now on.}
{152}{}{You returned the drunkard's family heirloom and proved once again that this world is no place for the weak-minded.}

#Female version
{1102}{}{[Wipes tears] Thank you, friend, I am eternally grateful!}
{1110}{}{Oh, I see the respectable lady has graced this city with her presence! Yes-yes, I'm talking to you, miss. May I say how hard it is to meet a woman of good manners these days?... Would you care to share a glass of Orvietto Classico Campogrande with me? - but wait! Oh dear! It seems I left my wallet at home. That's rather unfortunate...}
{1113}{}{Have you changed your mind and decided to keep me company, ma'am?}
{1120}{}{[He downs the bottle almost instantly, loudly belching as he wipes his mouth with the back of his hand] Ugh... You really shouldn't drink this swill. You're far too aristocratic for it, heh-heh... Thank you, just what I needed.}
{1131}{}{Either way, thanks for hearing me out. And an extra thanks for the beer. Come around sometime, I'll be happy to see you.}
{1143}{}{That's... No way! You really are a noble lady! And I thought it only happened in my gran's fairy tales. Thank you, thank you, and thank you again!}
{1144}{}{Happy to help. Here you go, pie-lover.}
