{100}{}{You see a visitor.}
{101}{}{You see a visitor, intensely studying a glass of Nuka-Cola.}
{102}{}{Hey! You're the one supplying this swill? Good job! Keep it up!}

{110}{}{Mind pouring me another glass?}
{111}{}{I hope I don't get gasses...}
{112}{}{Hmm... What an odd smell...}
{113}{}{I wonder what it's made of.}
{114}{}{You know, the pre-war stuff was better...}
{115}{}{...But it's all fizzled out, while this stuff is fresh!}
{116}{}{Tell me the truth, have you picked this off a corpse, or just stole it?}
{117}{}{Salt Lake City? Never heard of it.}
{118}{}{If they make Nuka-Cola there, then I'll definitely visit the place!}
{119}{}{Who's your delivery partner? Must be quite an expert.}
{120}{}{This is exactly what I needed!}
{121}{}{I think I'll take a bottle for the road.}
{122}{}{As long as I don't get addicted...}