{100}{}{You see a stranger.}
{101}{}{You see Solomon.}
{102}{}{You see a strange-looking man with a short beard and black sunglasses.}
{103}{}{You see an experienced chem dealer. His eyes are hidden behind black sunglasses.}
{104}{}{It's done. All that remains is to return the ring to Big Louie.}

#Имя рекомендатора
{105}{}{Racer}
{106}{}{Stryker}
{107}{}{A man with a brain tumor from the slums}
{108}{}{That dealer by the hotel}
{109}{}{Stay cool. You were recommended by a mutual friend. [Name him.]}

#Начало разговора и знакомство
{110}{}{[The man watches you intently. His eyes are hidden by black sunglasses, but you still sense coldness behind them.] The hell do you need, stranger?}
{111}{}{Hello... Solomon.}
{112}{}{I'm looking to buy some... Specialty goods. I think you know what I'm talking about.}
{113}{}{Just exploring, sorry for the trouble.}

{114}{}{You again? You're starting to piss me off!}
{115}{}{You want to make some money or not? Show me the goods.}
{116}{}{You again?}
{117}{}{I'm looking to buy. What do you got?}
{118}{}{Just looking around.}

{119}{}{There's nothing like that around here. And even if - IF - there was, you're just some asshole off the street. What makes you worth the time?}
{120}{}{More than you'd think... Solomon.}
{121}{}{I'm not like some street trash looking for a fix. You have a real opportunity here. Are you going to take it, or am I wasting my time?}
{122}{}{Enough of this, I'm going.}

{123}{}{[He stiffens and nervously adjusts his sunglasses] Solomon? Never heard of him. Who the hell is he, anyway?}
{124}{}{ Stay calm. }
{125}{}{ gave me your name.}
{126}{}{Shut the hell up. Your only chance of surviving this is if I like you.}
{127}{}{Hey, chill out. I'm just here to talk. You're making Big Louie nervous.}
{128}{}{Oh? My mistake, sorry.}
{129}{}{I guess I don't have much to offer right now. I'll be back with more.}

{130}{}{[He seems torn. Eventually, his greed wins out over his caution.] Alright. What's up? I don't do small time shit, but for the right price I can solve all your problems... Eh, most of them.}
{131}{}{I've always been interested in chemistry, medicine, that sort of thing.}
{132}{}{Why don't you introduce yourself? I want to know who I'm dealing with.}
{133}{}{You want chems? I've got the best shit in Reno. You're talking to the one and only Solomon, baby. I'm THE master of chems in this city.}
{134}{}{Actually, I've got something for you, courtesy of Big Louie.}
{135}{}{That's S-O-L-O-M-O-N, right? Good. I want to make sure you're headstone's spelled right.}
{136}{}{That's what I'm here for. Let's see what you've got for me.}
{137}{}{What for? [he eyes you nervously] I don't need this sketchy shit. Get out of here.}
{138}{}{Fine, I'm going.}
{139}{}{[He backs up fast] Big Louie? Hold on, just wait a minute, let's talk about this! I didn't mean for what happened! I can make it up to him!}
{140}{}{I'm listening, but this had better be VERY convincing.}
{141}{}{Talk to who? Big Louie's not here. All you have is me. And I'm not listening.}

#Удаление пальца
{142}{}{Okay, first, things are more complicated here, alright? This is Reno, not Louie's bumfuck Indian village. You gotta play a different game here, get it?}
{143}{}{Yeah, I got it. Someone told you to give the poison to Fatso. Who?}
{144}{}{What's complicated about it? I cut off your filthy head, bring it back to Louie, and go on with my life. Simple.}
{145}{}{ Look, Louie wants you dead. Even if I don't kill you, you'll be looking over your shoulder for the rest of your life. But if I give him that ring on your finger, he won't ever think about you again. Do you understand what I'm saying?}
{146}{}{Fuck off!}

{147}{}{[He glances out the door, but no one is coming to save him] I can't tell you who my boss is. But I can say this - he says he won't be working for Big Louie anymore. It'll be like he's going on strike, you know? A man who will be STRIKING against Big Louie? [he glares at you over the tops of his sunglasses] You could say he STRIKES out against a lot of people. Like the ones that kill his best chem pushers, understand?}
{148}{}{I've heard enough. }
{149}{}{Fuck this. Get out of here!}
{150}{}{You earn experience for getting Solomon's admission.}
{151}{}{But... [He starts pulling on the ring, but it's stuck fast on his finger. You can see how tightly the metal grips his flesh.] I can't just give it to you! I haven't been able to take it off for years!}
{152}{}{I'm planning to kill you and take your ring. Do I have to draw you a diagram?}
{153}{}{We could cut off the finger. Better than your head, isn't it?}

{154}{}{ Oh, simple as that, huh? [he starts sweating profusely] It's a part of me! You think I can just... Chop-chop, here you go?!}
{155}{}{You won't have to do a thing. I'll just cut it off myself.}
{156}{}{Either you lose the finger or you lose your life. This is your last chance, Solomon.}
{157}{}{Don't worry, Solomon, I'm a doctor. I can amputate it quickly and cleanly... Well, as cleanly as amputations get, anyway.}
{158}{}{This is a lot to take in. I'll give you some time to think about it.}

{159}{}{[He hems and haws anxiously. Just as you start losing your patience, he turns his head away and extends his hand to you.] Fine. Take the finger! There's no other choice, anyway. Just... Make it quick!}
{160}{}{Then shut up and don't distract me.}
{161}{}{[He looks down at his hand in a panic, then shakes his head] No. No, no, this is - this is some kind of trick! You conniving fucking bastard - get out! You can't touch me. Get the fuck out, I'm protected!}
{162}{}{[He hems and haws anxiously. Just as you start losing your patience, he slams his hand down on a table and pulls out a knife.] Fuck! You win! Okay, Solomon, you can do this... You'd better get this ring back to Louie, you fucker! You fuck me, and I'll find you! I can hire ten mercenaries to track you down with what I make in a day!}
{163}{}{Yeah, yeah, get to work. I have other things to do today.}
{164}{}{Oh, the drama. If this is so much trouble, I'll cut it off for you.}
{165}{}{Your hands are shaking so badly you'll probably slit your wrists! Give me the knife, Solomon, I'll get it done safely.}
{166}{}{You know what, Solomon? Do it yourself. I'm already going out of my way not to kill you, I'm not going to cut off your finger for you.}
{167}{}{[He perks up] Are you really a doctor? Oh, god, thank you! This ring has gotten so painful I can't sleep at night! If you can do this right, then... When can we get started? I want to get this done as soon as possible!}
{168}{}{We can do it now. Take these painkillers and we'll get started.}
{169}{}{We can't perform surgery with you thrashing around. We'll need anaesthetic. Wait here.}
{170}{}{[He perks up] Can you? This ring has gotten so painful, lately... But you know, you don't seem like a doctor to me. There haven't been any doctors in Reno for a long time.}
{171}{}{That's it, you've exhausted my patience. Take the knife and cut off your own damn finger. How does that sound??}
{172}{}{ My patience is nearing its end. Just like Louie's. Cut your finger off if you want to live.}
{173}{}{Fine, wait here until I come up with something.}
{174}{}{[The dull knife grinds into the bone. This is a bit more laborious than you had expected. Solomon screams and stamps his feet in agony.] AAAAAUUGHHH! FUCKING SHIT, IT HURTS, FUCK! WHAT'S TAKING SO LONG?! AAAAAUUUGHHH!}
{175}{}{Success!}
{176}{}{[The knife barely touches Solomon's skin before he starts squealing in pain. He sweats and writhes in agony, but he fears death more strongly than the pain. Meanwhile, your ears start to ring from his nonstop screaming.] FUCK! FUCKING GODDAMN! HOW DO THOSE FUCKING CHINESE DO THIS? Okay, okay, Sol, you can do this... FUCK! GOD, WON'T THIS FUCKING FINGER EVER COME OFF?!}
{177}{}{Is that all? You got the whole finger, right?}
{178}{}{[The routine amputation isn't even a challenge. The only challenge is enduring Solomon's nonstop talking. Before long, you start to wish you'd given him more sedatives.] So the whore pours the booze on her head and lights it up, running around and screaming "I'm a light bulb! I'm a light bulb!" That's when I stopped mixing Mentats with Med-X... }
{179}{}{All done.}

{180}{}{[You've got the finger and the ring. Solomon nurtures his bandaged hand, pale and clammy.] God, you fucked me up, you bastard. My vision's getting dark... Well, what are you waiting for? Get back to Big Louie! I've got to sleep this off... }
{181}{}{You got lucky today. Don't forget that.}

{182}{}{[You've got the finger and the ring. Solomon doesn't look too happy, but he's already experimenting with his bandaged hand.] Good work, doc. Don't think this'll get you a discount or anything. Now get that ring back to Big Louie. I'm sick of looking over my shoulder.}
{183}{}{Wow, the gratitude is overwhelming. See you around, Solomon.}

{184}{}{Huh. Good for something, at least. So, what do you need from the great Solomon?}
{185}{}{I want to know about the man with the brain tumor from the slums. You don't give him chems out of the goodness of your heart, do you?}
{186}{}{You gain experience points for performing a successful surgery.}
{187}{}{So you're Solomon? Big Louie's told me so much about you.}
{188}{}{Tell me about your wares.}
{189}{}{Nothing right now. See you.}
{190}{}{Not as good as you think. I'm going to enjoy playing with your guts.}

{191}{}{What the fuck do you expect? I risk my life everyday and you want me to give my product out for free? This is Reno. Everything has a price here. If this guy didn't want to pay he could have died peacefully long ago, but he said he wanted to live for his family. Well, if it weren't for me he wouldn't even have that choice! So yeah, I take his money. Why the fuck wouldn't I?}
{192}{}{You have no compassion. You disgust me.}
{193}{}{Just wondering is all. Onto other matters, then.}
{194}{}{Yeah, they're lucky to have you. That's all, I'll be going now.}

{195}{}{Time to cut off that finger of yours.}
{196}{}{I'll give you more, but not for free. Pay up.}
{197}{}{That's not enough. I need more!}
{198}{}{No more for you. You need to learn your limits.}
{199}{}{}

#Трупак
{200}{}{You're a pox on society. It's hard to imagine people letting you do this. How many people have died because of you?}
{201}{}{Hey, fuck off! People die because they're greedy and stupid, not because of me. Everyone who buys from me knows exactly what they're getting. If they can't handle it... Not my problem.}
{202}{}{ How many innocent people due to the addicts you've created?}
{203}{}{Who do you think you're fucking with? This smells funny. You ought to know better than to try this!}
{204}{}{Alright, I'll check until the first irritation.}

{205}{}{Fuck you, motherfucker! Anyone who buys from me made their own fucking choice! And wherever they get their money, that's their fucking choice too! You think if it weren't for the chems they'd be angels? No, fuck you! They're dumb motherfuckers who make dumb motherfucking choices, and they were dumb motherfuckers before they ever met me! And you're the dumbest motherfucker of them all if you don't get that! Now get the fuck out of here before I air out that empty fucking head of yours!}
{206}{}{[Leave.]}
{207}{}{Heh. [he grins slyly] Wanna hear an interesting story?}
{208}{}{Sure.}
{209}{}{You're up to something, and I don't want to be part of it. Goodbye.}
{210}{}{The guy who lived here before I moved in? He wasn't a bad guy, but he smelled like shit. You knew he was coming before you saw him. When he died, dogs ate his body and freaked out. Ran up and down the street all night long. You think there was something in the meat they ate?}
{211}{}{What are you implying?}
{212}{}{We should dig him up and make a nice chem soup out of him. What do you think?}
{213}{}{I've done worse than dig up corpses, but what am I going to get for it?}
{214}{}{I'll share a hit or two if it works out. Interested?}
{215}{}{Why don't you do it yourself?}
{216}{}{I got a reputation. I can't be seen digging up graves and I can't pay a bum to do it because they'll spread the word. You're from out of town, though. No one's gonna care what you get up to.}
{217}{}{I'll do it. Where'd they bury him?}
{218}{}{No, I'm done with the grave-robbing game.}
{219}{}{Near the railroad station to the south. Look for the crest of the sewer tubes.}
{220}{}{Sounds great.}
{221}{}{Just an offer. No hard feelings.}
{222}{}{Alright.}
{223}{}{Here's what's left of him. Take it and get it away from here.}

{224}{}{Shit, that time in the ground sure didn't help his smell! Let's hurry this up, huh? Take this knife and cut the meat off the bone.}
{225}{}{I did my part of the deal. You cut him up.}
{226}{}{Fine.}
{227}{}{[He glares at you] You want your fix or not? Take the knife and get cutting! Until you're done, no fix. You think I fucking owe you anything? You're lucky I'm even giving you this chance, you useless little bitch.}
{228}{}{Fuck you too.}
{229}{}{Fine, I'll do it if you can't handle it.}
{230}{}{[He gives you a look of smug contempt] Hurry up little junkie. Gotta get that fix!}
{231}{}{Right away, sir.}
{232}{}{As soon as I get my fix, I'm going to fuck you up... }
{233}{}{What was that?}
{234}{}{Uh, nothing. Just talking to myself.}
{235}{}{[Having finally prepared the corpse, you give the necessary remains to Solomon] Alright, wait a couple of hours. I'll refine this shit and get you your cut.}
{236}{}{[Sit and wait.]}
{237}{}{[After several delightful hours of watching cockroaches scurry across the floor, Solomon returns with your pay] Fuck, this smell's never going to come out! Take this and go. I got shit to do.}
{238}{}{See you. Try not to end up like your friend here.}
{239}{}{Now I don't need you anymore. [Attack!]}

#При наличии зависимости, пока не знакомы:
{250}{}{I need a fix so bad. Please. I'll do anything... }
{251}{}{Anything? [he puts a hand on your buttocks and smiles sadistically] Wow, you're shaking all over. How long has it been since your last hit? You really don't have anywhere else to go, do you?}
{252}{}{Anything... Just give me another hit... }
{253}{}{[He pulls down your pants and slides into your rectum in one movement] Ohh, that's good... What else you got, huh? Give me everything you have, any maybe that's enough.}
{254}{}{[Search your inventory for something of worth.]}
{255}{}{[He grunts harshly, then pulls out of you] Alright, we're done here. You can go on your way.}
{256}{}{What can you pay?}
{257}{}{Alright... }

#Дополнение к 143
{258}{}{Why did you give Fatso the poison?}
{259}{}{Does it matter? You don't need to know that, anyway.}

#Female character
{1119}{}{There's nothing like that around here. And even if - IF - there was, you're just some bitch off the street. What makes you worth the time?}
{1123}{}{[He stiffens and nervously adjusts his sunglasses] Solomon? Never heard of him. Who the hell is he, anyway?}
{1128}{}{Oh? My mistake, sorry.}
{1132}{}{Why don't you introduce yourself? I want to know who I'm dealing with.}
{1151}{}{But... [He starts pulling on the ring, but it's stuck fast on his finger. You can see how tightly the metal grips his flesh.] I can't just give it to you! I haven't been able to take it off for years!}
{1161}{}{[He looks down at his hand in a panic, then shakes his head] No. No, no, this is - this is some kind of trick! You conniving fucking bitch - get out! You can't touch me. Get the fuck out, I'm protected!}
{1170}{}{[He perks up] Can you? This ring has gotten so painful, lately... But you know, you don't seem like a doctor to me. There haven't been any doctors in Reno for a long time.}
{1180}{}{[You've got the finger and the ring. Solomon nurtures his bandaged hand, pale and clammy.] God, you fucked me up, you bitch. My vision's getting dark... Well, what are you waiting for? Get back to Big Louie! I've got to sleep this off... }
{1218}{}{No, I'm done with the grave-robbing game.}
{1227}{}{[He glares at you] You want your fix or not? Take the knife and get cutting! Until you're done, no fix. You think I fucking owe you anything? You're lucky I'm even giving you this chance, you dumb fucking whore.}
