{100}{}{You see recruits' mentor.}
{101}{}{You see Edward Benson, the mentor of recruits for "Nevada Express".}
{102}{}{I'm busy right now, please don't waste my time.}
{103}{}{This was the right decision, thanks. Now, back to work... }

{110}{}{I'm doing paperwork. If this isn't about business, then please don't distract me.}
{111}{}{What is it? Can't you see I'm trying to work?}
{112}{}{Alright, I'm going.}
{113}{}{Fine, I won't bother you.}
{114}{}{We'll talk later.}

#About the attack
{116}{}{Well, if the boss said so... Yeah, that happened. [he takes on a very formal look] We were sent to investigate a distress signal. Halfway there, we meet the survivors. If not for us, they'd have been goners. If they'd kept going, they'd have run straight into the Cheyennes.}
{117}{}{What, again? Sh... Long story short - we were sent to investigate a distress signal and halfway there we picked up two of the survivors. After that, we returned to New Reno.}

{118}{}{Who were the survivors?}
{119}{}{Did you investigate the attack site?}
{120}{}{What do you know about the attack?}
{121}{}{Can you give me the coordinates for the attack site?}

{130}{}{Two of our guards. Good boys. Showed themselves quite well in previous missions. Excellent shooters with steel nerves - just what we need. I think they passed by recently, headed off towards the restaurant.}
{131}{}{Err... We didn't. It was still a long way to go and the survivors told us everything we needed to know.}
{132}{}{Our boys said that the attack was carried out by bikers. I trust them. Nobody else would have the firepower or balls to crack our convoy.}

{133}{}{Eh? What?! Maybe you'd like me to bend over for you as well?}
{134}{}{But Tuco said I could!}
{135}{}{Knock it off, Tuco gave the go-ahead.}
{136}{}{[Mockingly] "But Tuco said I could!"... Of course, he's the boss. Here are the coordinates. More than likely, the stagecoach was looted by Black Rock locals. Won't even wish you luck with that. Hah!}
{137}{}{[He mutters something inaudible to himself] ...of course, he's the boss. Here are the coordinates. More than likely, the stagecoach was looted by Black Rock locals. Won't even wish you luck with that. Hah!}

{138}{}{Tuco said you led the rescue operation on the stagecoach?}
{139}{}{Tell me about the rescue operation again.}

#General questions
{140}{}{Who are you?}
{141}{}{Did you hear anything about the bikers around here?}
{142}{}{[Grumbling] This city has too many rude assholes these days... I'm Edward. I'm the "Nevada Express" recruits mentor.}
{143}{}{Bikers? I *hate* them! They're a plague on Nevada! Goddamn troglodytes, covered in jangles and other crap, thinking they can stir up bars and hit our stagecoaches. Those sons of bitches should stay as far away from me as possible!}

#Evidence against "Nevada Express"
{150}{}{Now, sit down and look at this. I want to see your face as you see the data here.}
{151}{}{[Studies the data-disk] What the... Hold on... No! Everything is gone!}
{152}{}{What are you talking about?}
{153}{}{I'm talking about how this evidence needs to rust along with the rest of the stagecoach.}
{154}{}{Looks like you know more than you let out, right?}
{155}{}{There are forces bigger than us. I'll explain.}
{156}{}{I don't want explanations. Just profit.}
{157}{}{Of course, I'd like to know what made you do that.}
{158}{}{Personal interest? It could end with a bullet from a dark alley if you don't listen to my words.}
{159}{}{Alright, I'm listening.}
{160}{}{Some businessman went into Salt Lake, to sort out Nuka-Cola sales in Reno, and was on his way back. Another guy in Reno wanted to prevent this deal, and it just so happened, that two of our guards owed him money.}
{161}{}{And you knew?}
{162}{}{No, I found out later. The guys told me everything eventually. When I learned the truth, I had to go along with it. After all, we can't change the past and we don't need problems with the local mob.}
{163}{}{As you can see, the plan didn't work.}
{164}{}{Hold on! Whatever happened, please understand - the "Nevada Express" has nothing to do with this. The blame can be laid on those two, but if Tuco or anyone outside the company finds out that there are criminals in our ranks? Our reputation would take a huge hit. It would be bad for everyone. Should we really risk so much just for the truth's sake?}
{165}{}{Do you have any ideas?}
{166}{}{Perhaps... I could just destroy the chip. The guards would've done the same.}
{167}{}{But your actions damaged the biker's reputation. If you continue sending heat their way, the might starting raiding the "Nevada Express" for real.}

{168}{}{Shit, I didn't think of that... What are we going to do then?}
{169}{}{I'll try and think something up. Not now.}
{170}{}{Fine, I'll just destroy the evidence.}
{171}{}{Fine, I'll just destroy the evidence. But I demand a reward - $2000.}
{172}{}{Your ideas are shit. I'll find another use for the chip.}

{173}{}{I *really* hope you will.}
{174}{}{Goodbye.}
{175}{}{I didn't expect your conscience to get in the way. Thank you. I hope we won't return to this question again. And here, something for your troubles.}
{176}{}{Bye.}
{177}{}{Is that the price of your silence? Hmm... Well, I think it would be safer than risking the company's reputation. Here's the money, but I don't think I'll be happy to see you again.}
{178}{}{Bye.}
{179}{}{It's not too late to reconsider!}
{180}{}{See you.}

{181}{}{I have an idea. I'll reprogram the disk and give it to Tuco. Everyone will think that the attack was carried out by some raider gang.}
{182}{}{Genius! And you think you can do that?}
{183}{}{Of course, I have plenty of knowledge about programming robots.}
{184}{}{Pfft, how hard could it be? It's just ones and zeroes, right?}
{185}{}{Uhh... Maybe we shouldn't risk it. If anyone finds evidence that the disk was tampered with, then the whole plan will be for nothing.}
{186}{}{Then I'm gonna think about it a little more.}
{187}{}{All that's left is to do it then, eh?}
{188}{}{Let's do it!}
{189}{}{I have other things to do. I'll be back when I'm ready.}
{190}{}{[You finished writing and compiling the code before testing it a few times. It works like a charm!] Zzzzzz... Huh? Wha-? It's done? Oh, let's see... Perfect! We'll tell Tuco that we mistakenly identified the attackers as bikers. He'll be angry for a bit, but after we make an apology, the bikers themselves should calm down. Thank you, I won't forget it.}
{191}{}{Anytime.}

#Female version
{1189}{}{I have other things to do. I'll be back when I'm ready.}
