{100}{}{You see a drug dealer.}
{101}{}{You see a man in rumpled clothes. He rubs his nose.}
{102}{}{You see a drug dealer. His eyes scan the area for customers.}

#Скидки
{110}{}{Oh, I know you. Uh... Out of respect for your boss, how about I'll give you a discount? Say... Thirty percent. Sounds fair?}
{111}{}{Yeah, sounds fair. What do you have today?}
{112}{}{I don't need anything today, but I'll remember that discount for next time.}
{113}{}{What can I do for my favorite customer?}
{114}{}{Were you the one who fucked up Wright's slums? That asshole always made it hard for a dealer to earn an honest buck. The more problems his kids have, the better my life gets. You just earned yourself a discount... Keep up the good work.}
{115}{}{[As he looks at you, his eyes light up in recognition] Oh, hey! What can I do for you?}

#Подзывающие фразы
{200}{}{Hey, look who it is! Come, take a look at what I've got!}
{201}{}{Check out my candy!}
{202}{}{Come on, I can give you a good price!}
{203}{}{::whistles::}
{204}{}{Nothing better than a hit after a hard day, am I right?}
{205}{}{I got shit that'll make you kiss the sky!}
{206}{}{I got what you need!}
{207}{}{I like your face! I'll give you the family price!}
{208}{}{I have what you're looking for! You just don't know it yet!}
{209}{}{Why walk when you can FLY?}
{210}{}{I got the purest shit! Give it a try and you'll never go for another!}
{211}{}{You wanna fly? You got money? You talk to ME!}
{212}{}{Feeling low? I'll get you high!}
{213}{}{I got stuff and more stuff. Let's talk.}

#Когда товара нет
{220}{}{Sorry, I'm out of stock. Come by later.}
{221}{}{I've got nothing right now. Stop by tomorrow.}
{222}{}{I'm all out. I'll have more tomorrow.}

#Отравленное пиво для казино
{230}{}{I need a batch of mildly poisoned beer. Non-lethal. Don't ask why.}
{231}{}{Hey, it's not my job to ask questions. 300 bucks and it's yours.}
{232}{}{Here's the money. Make it quick.}
{233}{}{Not now.}
{234}{}{Hey, there's not enough here! Come back when you've got it all!}
{235}{}{Fine.}
{236}{}{[After some time, the dealer returns] I had to scrounge up some things, but it's done. Here.}
{237}{}{Just what I need.}

#Соломон:
{250}{}{I'm looking for a dealer named Solomon. Do you know where he is?}
{251}{}{Hey, listen, my stuff's way better Solomon's. But if you need him, specifically, then maaaaybe I can set you up. It's gonna cost you $1000.}
{252}{}{[Pay $1000]}
{253}{}{I have a better idea. I knock out one of your tooth after another until you tell me where he is. You want to start with the left or the right side?}
{254}{}{Here's $100. Consider it a gift from my boss, along with your life. In return, you tell me where Solomon is, and we never had this conversation.}
{255}{}{I'll think about it.}
{256}{}{I said $1000.}
{257}{}{What a stingy motherfucker...}
{258}{}{Now we're talking. Solomon slings his shit behind the El Dorado at night. Tell him I sent you.}
{259}{}{[Leave]}
{260}{}{And here I thought you are being serious.}
{261}{}{Shut up! I just miscalculated, that's all. Happens to everyone.}
{262}{}{[He looks at you, then smiles confidently] Sounds like bullshit. Go fuck yourself.}
{263}{}{[Attack]}
{264}{}{[Leave quietly]}
{265}{}{Hey, hey, let's take it easy! Look, just go behind the El Dorado at night. Solomon will be there. Tell him I sent you.}
{266}{}{[Leave quietly]}

#Компоненты для Страйкера
{270}{}{I came for Stryker's components.}
{271}{}{Money up front.}
{272}{}{[Pay in full]}
{273}{}{How much did you want? $1000? I think it would cost much less to kill you. What do you think?}
{274}{}{I'll come back with the money, wait here.}
{275}{}{You know, I'll just kill you! [attack]}
{276}{}{You're threatening me? In front of everyone? Nah, I don't think so. Your boss wanted to keep this in secret. What if I go talk to Thompson, huh? You didn't think of that, did you? Watch your fucking mouth. These are the streets, we have our own laws here.}
{277}{}{You're threatening me? I could just walk away, you know that? I took a big risk getting these components! ...Look, how about you take $100 off the price and we just close the deal, okay?}
{278}{}{[Pay 900$]}
{279}{}{Take it. Now get out of here.}
{280}{}{Okay.}
{281}{}{What is this?}
{282}{}{Not enough? Too bad...}

#Квест Томпсона
{290}{}{I heard a rumor that Thompson's team was shot here. You know anything about it?}
{291}{}{I saw it myself! They were here yelling about some shit, gathering people around... I guess it attracted some unwanted attention. One of them guys got shot so hard it knocked him right off his feet! I've never seen a weapon that could do that from such a distance! It was fucking awesome!}
{292}{}{Where were they were shooting from?}
{293}{}{Hell if I know. I'd say the casino or Wright's slums, but then I figured that someone would see the shooter, and, as far as I know, no one did. Weird, huh?}
{294}{}{Thanks.}

#Остальной диалог
{300}{}{Tell me what you need, and I'll give you the best price in Reno!}
{301}{}{You want a good time after a bad day? You came to the right place!}
{302}{}{I got the best product! Maybe we can even work out a deal! Whaddya say?}
{303}{}{I got the best shit in the city!}
{304}{}{Ooh, a client! What'll it be this time?}
{305}{}{Hey, I got a lot of things! Whatever you need, come to me!}
{306}{}{Check it out! I just got some new stock! How about we make a deal, huh?}

{307}{}{What do you have?}
{308}{}{Not this time.}
{309}{}{I'll see you again, I hope.}
{310}{}{Maybe later. Bye.}

{311}{}{Do you have a strong poison for sale?}
{312}{}{You mean, a deadly kind? All my shit's safe, you hear? Believe it or not, I like my clients ALIVE!}
{313}{}{Well... Hmm. You know, I know a couple of guys that can give you poison... Err, product. Gangsters. One's selling behind the El Dorado, the other one is at the bowling alley. You didn't hear that from me, okay? Anyway, why buy something that can kill you when my stuff will give you the time of your life, am I right?}

#Female character
{1261}{}{Shut up! I just miscalculated, that's all. Happens to everyone.}
