{100}{}{You see a casino administrator.}
{101}{}{You see a man in a fine suit with finer posture. You can tell he works hard to maintain both.}

{110}{}{A word of advice: you do not belong here, and you'd best leave, before someone does something about it!}
{111}{}{Welcome to our casino! I am the administrator. Can I do something to help?}
{112}{}{Did you want something?}

{113}{}{How does this place keep running now that Bertolini's gone?}
{114}{}{It's been a lot a difficult transition, but we have things well in hand. Please, don't be worried - we will not allow this tragedy to disrupt the casino's operations. Now, if you'll excuse me, I have a lot to do.}
{115}{}{You seem evasive. Oh, well...}

{116}{}{Let's talk about Mrs. Clover.}
{117}{}{Oh, yes. Her case has certainly been a nuisance for us, but the rules are clear. Mrs. Clover will have to pay her debt of 1000 dollars.}
{118}{}{As I informed you previously, the rules apply to everyone. No exceptions.}
{119}{}{Goodbye.}
{120}{}{What can you tell me about this debt?}

{121}{}{If it will help resolve this issue, then I'll tell you everything. Mrs. Clover's late husband owed our casino a rather large debt. After his death, his debt fell to his next of kin - in this case, Mrs. Clover. She must repay it in cash - 1000 dollars, to be exact - or arrange for alternative compensation.}
{122}{}{Could someone else pay her debt?}
{123}{}{Of course! This is business, not a personal vendetta. If anyone were to repay the debt in her name, then the matter will be concluded.}
{124}{}{Then I'll pay the debt.}
{125}{}{Very well. Will you pay the full 1000 dollars now?}
{126}{}{Yup. Here you go.}
{127}{}{A pleasure doing business! Please deliver this receipt to Mrs. Clover and inform her that her debt has been paid. We will be happy to see her at our casino any time!}
{128}{}{That's great. See you.}
{129}{}{No, I'll have to come back later.}
{130}{}{Of course. [his head tilts almost imperceptibly downward] Please be aware that the El Dorado will continue to attempt to redeem Mrs. Clover's debt, regardless of any verbal assurances on her behalf, until it is paid.}

{131}{}{}
{132}{}{I have more questions about Mrs. Clover's debt.}

{133}{}{Mrs. Clover didn't run up this debt. Why should she have to pay?}
{134}{}{With her husband's death, Mrs. Clover inherited all of his assets. So did she inherit his liabilities. This is known as a "family guarantee". You may disagree, but with no formal authority figures in Reno, the responsibility falls to us to decide the obligations and consequences of our financial dealings.}
{135}{}{You shouldn't worry about me disagreeing. You should worry about my boss. You may know him as Reno's informal authority figure.}
{136}{}{Your... [he pales] ...your boss?}
{137}{}{Yes, he's disappointed with your casino's treatment of this woman. Very, very disappointed.}
{138}{}{Well, I, ah... [he swallows] ...we would not want to disappoint such a... Respected figure. Of course, we can forgive Mrs. Clover's debts... If he thinks that's best.}
{139}{}{He does.}
{140}{}{I don't know, I'll have to ask him.}

{141}{}{That's a lot of cash. Is there any other way to pay off the debt?}
{142}{}{Hmm. [he studies you carefully] It's possible an accounting error could cause Mrs. Clover's debt to fall between the cracks. But such errors are usually the result of other, more *esoteric* errors. I could discuss such details with you, but it would have to remain between us...}
{143}{}{Go on.}

{144}{}{I could wipe Mrs. Clover's debt clean, but you'd have to get something for me. Specifically, a copper cigarette case, such as the type in Mr. Wright's collection.}
{145}{}{Of all the things you could want in Reno, why a cigarette case?}
{146}{}{In this case, a cigarette is not just a cigarette. Symbols of pre-war society are a sign of status. In my particular situation, such things are more powerful than guns or even money.}
{147}{}{Who is Mr. Wright, and what's this about a collection?}
{148}{}{You don't know Mr. Wright? You should. He owns the slums opposite this casino and the Silver Legacy. He was once a very powerful man, but he's but a shadow of that now. Nonetheless, he retains his collection of pre-war memorabilia. He is a... Traditional man, and appreciates the America that was. He collects artifacts of that time, and sometimes shows his collection to those that would appreciate it. Like me.}
{149}{}{What if your boss finds out about this?}
{150}{}{Well, he won't, will he? [he narrows his eyes] And as a matter of fact, I don't think he'd believe it anyway.}
{151}{}{I'll think about your proposal.}
{152}{}{It's your lucky day, because I just so happen to have this cigarette case. Take it.}
{153}{}{I got your cigarette case. Let's get this over with.}

{154}{}{Just a moment! I imagine Mr. Bertolini would appreciate the employ of such a resourceful person. If you're interested, pay him a visit and tell him I recommended you for a job. If not, well, good luck.}
{155}{}{I'll keep that in mind. Thank you and goodbye.}

#Кий Бертолини
{165}{}{It was Mr. Bertolini's personal cue. Without him, we have no reason to pay for its repair. You may keep it - I'm sure you'll manage to sell it to someone.}
{166}{}{Hey, we had a deal!}
{167}{}{I see. Well, I'll go then.}
{168}{}{The conditions of the deal no longer apply. I'm sure you understand. If not, then understand that our security will not hesitate to remove unruly guests from the premises, without said cue.}
{169}{}{Maybe they will, but they won't get here in time to save you. [Attack.]}

{170}{}{Do you have any work for me?}
{171}{}{The casino is not currently looking for domestic workers, but thank you for your interest. Feel free to check back any time in case something changes.}
{172}{}{The casino is not currently looking for domestic workers, but try talking to the owner, Mr. Bertolini. He's looking for talented individuals for, er, special assignments.}
{173}{}{Okay.}
{174}{}{Actually... [he holds up one finger] ...there is one task you may be able to help with. Nothing elaborate, but it pays 200 dollars.}
{175}{}{What is it?}
{176}{}{Too bad, I'm only looking for elaborate work.}
{177}{}{[He reaches under his desk and pulls out a carrying case. He opens it to reveal a folding pool cue that has been snapped along its shaft.] This is Mr. Bertolini's favorite cue. Yesterday he became very angry about some bad news and broke it over a knee. The messenger's knee, specifically. We will pay 200 dollars for its repair.}
{178}{}{Bertolini broke his *favorite* cue?}
{179}{}{One of Mr. Chase's bugs has been cleverly hidden among Bertolini's belongings.}
{180}{}{No problem. I'll see to it.}
{181}{}{That's not really my thing.}

{182}{}{Indeed. Mr. Bertolini is a man of conviction. He acts decisively, even concerning which is he attached to.}
{183}{}{[He gives you a sly look] But you already know that, don't you?}
{184}{}{But you don't need to know anything about that.}
{185}{}{Neither is it mine. But the job must be done sooner or later, by someone or other. We are focused on results, here - so long as you return the cue in approprite condition, you will receive your pay, whether or not you carried out the repairs yourself.}
{186}{}{I'm happy to hear it. [he hands over the carrying case] I'd appreciate it if you could return it as quickly as possible. Oh, and the case itself is worn out, particularly at the bottom - please see to that as well.}
{187}{}{Remember, appreciation is best expressed in money. I'll be going.}
{188}{}{Goodbye.}
{189}{}{Is the pool cue job still available?}
{190}{}{For the time being. I was just about to pay the cleaning boy to run it to the mechanic out at the train yard. Want to stay ahead of the competition?}
{191}{}{Yes. Give me the cue, I'll fix it.}
{192}{}{No, give it to him.}
{193}{}{About the pool cue...}
{194}{}{Is it ready?}
{195}{}{I don't understand, why did Bertolini break his favorite cue?}
{196}{}{Yes, here it is.}
{197}{}{Not yet. I'll bring it later.}
{198}{}{Sorry, I lost it.}
{199}{}{[He removes the cue from the case and carefully appraises the quality of the work] Hmm. The balance is even, and the length and curvature are intact. An excellent job! Here is your payment, thank you.}

#Female character
{1168}{}{The conditions of the deal no longer apply. I'm sure you understand. If not, then understand that our security will not hesitate to remove unruly guests from the premises, without said cue.}
