{100}{}{You see Huey.}
{101}{}{You see a young man with messy hair and a scowl on his face.}
{102}{}{Who are you? Take that off so I could see you.}
{103}{}{I've got nothing to say to you. Leave me.}

{110}{}{Ah, another one of my dad's goons. What do you need?}
{111}{}{So you're Ricardo Bertolini's son? Where's your mother, I wonder?}
{112}{}{Nothing.}

#Chatter
{113}{}{Do you really care? Died giving birth.}
{114}{}{Sorry I asked.}
{115}{}{I don't give a shit about your apologies. It's God who should apologize, if he exists.}
{116}{}{Are you on your period right now, or you are always this pissed off?}
{117}{}{Listen, I just want to be left alone. Shit, what I *really* want is for Reno to be nice and quiet, like when I was a kid. But it's a fucking hellhole now, and my father's loving it. And he's trying to show me the "right" way to be just like him. It makes me sick. The world doesn't have to be this shit, you know. But no one wants to fix it.}
{118}{}{You don't approve of your father's ways?}
{119}{}{I don't approve of many things in this world. Now leave me alone before I get worked up enough to hang myself.}
{120}{}{We'll talk later.}
{121}{}{Fine, don't worry.}

#Quest
{130}{}{Your father sent me to sort some things out. Explain.}
{131}{}{[Sighs theatrically] Stryker's put a mole in our staff. Now father wants me to end him. The mole doesn't know he's been found. And you're here to... Listen, I'm not stupid, I know why you're here.}
{132}{}{Is that a problem?}
{133}{}{This isn't about whether he deserves to die. The problem is that it meant for me to prove something to someone that way. I don't want that.}
{134}{}{Oh boo-hoo, we don't always get what we want. Load your gun, wipe the snot off your nose and lead me to the place. Got it?}
{135}{}{Just trust me, we'll take care of it out when we get there.}
{136}{}{[He narrows his eyes, thinking] Fine, let's get this over with. We're doing this on the railroad station where no one will see us. I'll let everyone know we're moving out. Wait here...}
{137}{}{[Wait]}

#After quest
{140}{}{Thanks for your help. }
{141}{}{Can you help me out with another job?}
{142}{}{Go ahead.}

{143}{}{Talk.}
{144}{}{Well, I want one of those funny-looking guns the security here uses.}
{145}{}{They're called Tommy guns. Father raided museums for them as part of the casino's pre-war image. Stupid, if you ask me, but I it doesn't matter. What matters is they're all locked up on the second floor. The only key's on that big guy in the blue suit, and they see you try to crack the lock, they'll cut you down.}
{146}{}{Well, I need some cash.}
{147}{}{You're not getting it from me. Father doesn't give me money without a good reason. But he's got 20 grand in his safe! All of it made off the backs of better people. It'd serve him right if someone took it, but you'll never get in there alive.}
{148}{}{Do you know the safe combination?}
{149}{}{Sure. 9-7-5-3-1. You still won't get to it without a fight.}
{150}{}{I'm sure there's another way.}
{151}{}{Well, if you're gonna try it either way, you should do it at night. The guards get careless around then - playing pool, snoozing in the chairs, that kind of thing. I guess you could cut the lights too. That would stir them up.}

#Female replica
{1114}{}{Sorry I asked.}