{100}{}{You see Mr. Bertolini.}
{101}{}{You see a delicate casino manager. Seems like he enjoyed a little bit of his wine stock.}
{102}{}{Another businessman bites the dust.}
{103}{}{Do me a favor - DIE!}
{104}{}{What's happening?! Where's the lights?!}

##########################################################################
#
#                      Разное
#
##########################################################################

#Когда мертв Томпсон
{105}{}{Wait, stop! Wasn't it you who has been seen next to Mr. Thompson when he was killed? You'd better not stay here for long - I don't need you causing more problems. Guards, show this nuisance the door!}
{106}{}{[Walk away peacefully.]}
{107}{}{[Resist.]}
{108}{}{This appointment is over.}
{109}{}{This appointment is over - as is our partnership.}

#Начало разговора
{110}{}{What do you need in my office?}
{111}{}{I haven't seen ghouls in this casino for a long time... But - wait a minute. Ha! I took you for a ghoul... Hmm, but don't think I'll apologize.}
{112}{}{I've heard about you from Thompson's men. His friends are my friends. How can I help?}
{113}{}{Come, partner, have a seat. I'm ready to hear you out.}
{114}{}{Always glad to see you in my casino. Make yourself comfortable and feel at home.}
{115}{}{I, uh, will be back soon.}
{116}{}{My name is Ricardo Bertolini - I'm the owner of this place, and this is my apartment. Usually I do not accept clients... Unless they have a business proposal for me.}

{117}{}{Word on the streets is that you were seen with that old ranch fellow - Oliver. If that's the path you choose, I won't stop you. But - if that's the case - from now on there will be no business relations between us. If you want to keep working for me - prove that you're still trustworthy.}
{118}{}{It's just a deceptive maneuver. I will prove my worth}
{119}{}{Is it so unpleasant that I talk with your competitor? That's understandable.}

#Про колу
{120}{}{I have a proposal. We could arrange a mutually beneficial deal, regarding the sale of Nuka-Cola... }
{121}{}{The offer is tempting, but my bar only serves alcohol drinks. No one will buy Cola here. If we were some sort of a cafe, I would probably agree.}
{122}{}{Ah, got it.}

#Кловер
{123}{}{Boss, I know a lady who's forced to pay her debts to the casino after the death of her husband. Could you help to resolve this issue?}
{124}{}{I've heard this story... Mrs. Clover, correct? As a courtesy to you, I am willing to forgive these debts - moreover, the total sum is not much for this casino. Inform the administrator about my wish.}
{125}{}{Thank you, Mr. Bertolini!}

#Про враждебность Томпсона
{130}{}{I heard rumors that you've offended Mr. Thompson. What can you say about this?}
{131}{}{He was asking for it!}
{132}{}{I'm not going to make excuses. The matter is between him and me only.}
{133}{}{And why does that matter?}

{134}{}{That seems like an obvious lie, although, since we are partners and share common interests, I'll close my eyes to it. But bear in mind, that the mutual respect of Mr. Thompson and his team is more important for me than your services.}
{135}{}{That's a fair statement. I have no objections, but bear in mind that the mutual respect of Mr. Thompson and his team is more important than your services.}
{136}{}{If you are looking for conflicts, do it elsewhere. I respect Mr. Thompson and intend to continue our... Mutual business with him. We will not turn a blind eye if you continue to cross our paths.}
{137}{}{Understood.}

{138}{}{What kind of masquerade is this?}
{139}{}{Come, sit down. Do you need something?}

#Попытка напроситься на работу
{140}{}{Mr. Bertolini, I want to work for you.}
{141}{}{Work... What do you mean?}
{142}{}{I need a *real* job. Not like a croupier or floor washer. I can do *more*, you see.}
{143}{}{What, no vacancies in the casino?}
{144}{}{Our people cope well with everyday tasks. Laborers are not hard to come by in Reno. It's much more difficult to find good partners for conducting mutual business.}
{145}{}{Manning tables and sweeping floors is petty work. I can take *more* responsibility, you know?}
{146}{}{No jobs? That's too bad. I'll have to look elsewhere.}
{147}{}{For serious work you need a serious cause or recommendation. Which of these can you offer me?}
{148}{}{Don't you need someone to sweep the floors or something like that?}
{149}{}{Well, I really have nothing to impress you right now. I'll be back when I do.}
{150}{}{For serious work you need a serious cause or recommendation. Wait... [Bertolini takes one of his guards aside for a private conversation, then returns to you] There is reason to believe that your communications within the town are... Questionable. Now leave.}
{151}{}{Communications? With whom... ?}

{152}{}{Jordan Bishop recommended me to work for you.}
{153}{}{But your administrator advised me to speak with you.}
{154}{}{Listen, I wasn't born yesterday. I've handled a lot of jobs in my time...}
{155}{}{What about this package that I have for you from Vegas?}
{156}{}{What about my help with the Chase case? Isn't that worth anything?}

{157}{}{Well, that's enough. I can trust you with one simple task to see how you handle it.}
{158}{}{Excellent. How can I help, Mr. Bertolini?}
{159}{}{As long as I get paid, I'm in.}

{160}{}{In this case, go to the Luciano's ranch on the southern outskirts of the town. There you will find a local beggar, who is known as "The Canary". Tell him "The gilding is gone from our century" and return to me with his answer.}
{161}{}{Sounds easy. I'll think about it.}
{162}{}{Okay.}
{163}{}{Payment will be received upon the job's completion. But act quietly, so no one from Oliver's commune would suspect anything.}
{164}{}{Understood.}

#Посылка из Вегаса
{165}{}{I have a package for you from Vegas.}
{166}{}{I've been waiting for it. What's the matter?}
{167}{}{I'm having difficulties... }
{168}{}{Difficulties?! I have paid good money for this product, and now you come to me and say you're "having difficulties"?! I should have resorted to more effective delivery service... I hope, for your own sake, that this was the last screw up, courier.}
{169}{}{Of course, uh, Mr. Bertolini. No more misfires.}

{170}{}{I've been waiting for it, but... How did it come into *your* possession!?}
{171}{}{It's a long story, boss. The short is, I have good connections, and your associates aren't so good at keeping secrets. So - are you interested in package? Or should I throw it out?}
{172}{}{Hold your tongue, and pray to the gods that I won't shoot you where you stand. This product is too valuable. Many in Reno would sell their souls for the sake of it. I'm clever enough to pay in cash instead. Here's your fee for delivery. Now leave the briefcase and get out.}
{173}{}{Alright.}

{175}{}{I have reliable information regarding espionage within this place. Interested?}
{176}{}{I will listen very carefully, and then decide whether the information is worthy of even a drop of my patience.}
{177}{}{[Tell him about Chase]}
{178}{}{Come on, I just wanted to make an impression on you... }
{179}{}{[Gives a signal to the guard] Do you understand what to do? Go and deal with Chase. [Turns back to you] And you... Hmm. Perhaps you'll be useful. Here, take this as a small payment. Now leave me.}

##########################################################################
#
#                      Квесты
#
##########################################################################

#Первый квест
{180}{}{I'm here to talk about my task.}
{181}{}{Did you meet the contact?}
{182}{}{Yes, I found him at Oliver's ranch.}
{183}{}{Apparently, he was a shitty contact. Otherwise, he would still be alive.}
{184}{}{No, I haven't find him yet.}
{185}{}{I don't pay people to loiter around my casino - they pay me. Don't come back until you've carried out the assignment.}
{186}{}{Alright.}
{187}{}{[He looks attentively at you, then pulls out a single fifty-dollar bill, crumples it up and throws it at your feet] Get out.}
{188}{}{Hey, I completed the job!}
{189}{}{What did he say?}
{190}{}{He said: "It went into our pockets".}
{191}{}{He said: "It went into our pockets". What could that mean?}
{192}{}{You can get a bullet in the forehead for asking too many questions, remember that.}
{193}{}{Uh, alright. What about the job?}
{194}{}{That explains a lot. So, it's time to act decisively... But first, tell me what you know about Oliver Luciano.}
{195}{}{Isn't that the old man from the ranch who recently died?}
{196}{}{[He raises his eyebrows and looks at the guard, who nods, then takes out a fifty-dollar bill, crumples it up and throws it under your feet] I no longer need your services. Go away.}
{197}{}{I'm guessing that's the end of that relationship... }
{198}{}{An old man who owns a local ranch and provides a major share of food on Reno's market.}
{199}{}{Some kind of old fogie who lives in a shack on the ranch and farts himself to sleep.}
{200}{}{Watch your tongue, ignorant pig! Although we and Oliver are at odds, I have respect for his business.}
{201}{}{Oh, that's how it is... I'll try.}
{202}{}{Oliver and I used to get along well, but ten years ago a conflict emerged. When civil war broke out in the town, we stood on opposite sides of the barricades. Now, when those, who at the helm, are completely different people, I want to put an end to this story. You will help me. Here's something to instill your confidence - your payment.}
{203}{}{Can you tell me a little more about this story?}
{204}{}{I'm in.}
{205}{}{I'll return when the job's done.}

{206}{}{Perhaps... It will help you to better navigate the situation. In this case, I will be able to answer some questions.}
{207}{}{I need to know about that civil war.}
{208}{}{Why did you end up on different sides?}
{209}{}{What prevents you from making peace and becoming partners?}
{210}{}{Do you wish for... Luciano's death?}
{211}{}{May I ask another question?}

{212}{}{It happened around six years ago. Local businessmen couldn't get along because of the division in spheres of influence. Competing in conditions of increased population and lack of resources led many to ruin: poverty in homes, gangsters on the streets, sabotage within enterprises. Then the clans began to kill each other. All of this stopped when the "big daddy" of the wasteland came with his crew, as they told "to carry out some order", and ended up outsmarting everyone here with his own hidden agenda. Since then, the town had no rest.}
{213}{}{It's a long conversation. Let's just say we have different views on how the town should develop. I like the ideas offered by Mr. Thompson. Oliver's opinions are radically opposite.}
{214}{}{Good question. Probably the overall situation in the town, and... How should I put it... This old man's stubbornness. I can not dissuade Oliver from his ideas, but they directly contradict my ideas on this town's future.}
{215}{}{No way! The death of this man would only ruin his ranch. It would lose workers, slaves, and its resources would be stolen. I have other thoughts on his account, but it's still too early for you to be aware of them.}
{216}{}{Occasionally, Luciano ships food to the the Silver Legacy's restaurant. I need you to undermine his reputation when he'll do it next time. Go to the restaurant, wait for the convoy and sabotage the deal. How you'll do it - I don't know and don't want to know. But it must be done so that it looked like a an oversight from Luciano's men.}
{217}{}{I'm on my way.}
{218}{}{Can I learn more about the situation that has caused tension with Luciano?}
{219}{}{Did you manage do what I asked?}
{220}{}{I'm still working on it.}
{221}{}{Mission accomplished, Luciano's reputation was undermined.}
{222}{}{This is good news. Did you do it... Quietly as I asked?}
{223}{}{Thank you, Mr. Bertolini. Will there be any new jobs?}
{224}{}{I have just been informed that Oliver Luciano has passed away. This defeats the purpose of my plan, and concerning your service... Well, I have no further orders for you. You may leave.}
{225}{}{Oh, Oliver, why did you let me down... }
{226}{}{Yes, you've proven yourself, so I can trust you with a more serious mission. Your payment will also correspond with the significance of each task.}
{227}{}{What do I need to do?}
{228}{}{I need you to destroy Luciano's enterprise. He has to be knocked out of the rut, so that later I could dictate my conditions to him. And Oliver should not die under any circumstances.}
{229}{}{To destroy his whole enterprise? How should I do it?!}
{230}{}{The objective is accepted. Wait for the results, Mr. Bertolini.}
{231}{}{Who's paying who, for gecko's sake?! This is *your* headache, so you should decide, what to do. But, if I were you, I'd first studied closely the central facilities of the ranch - the hangar, brahmin corral or paddock with slaves. The more losses you arrange, the better.}
{232}{}{Maybe this is a risky question - but still - why is this necessary at all? After all, it provides the main Reno market with food... }
{233}{}{I'm not going to discuss my plans with you. But I will say that Luciano is not as simple as you think. This is no ordinary rancher, whose head is stuck in a brahmin's ass. And he is not some kind of trader, who sell the screw nuts to regressive savages. He is the driving force. One of the most powerful in the town today. People are rallying around him; he dictates his conditions, and he also has some sort of plan. Hmm... I don't know, maybe you're from one of those places where food is just another product. But, here and now, it's what the life in this desert is gathering around. Now, do you understand?}

{234}{}{What did you manage to accomplish?}
{235}{}{Nothing right now, but I'll handle it later.}
{236}{}{I'm sorry, but completing the task without a violent resolution wasn't an option. Believe me, it was the only possible solution.}
{237}{}{Oh yes, just like you wanted. No one suspects anything.}

{238}{}{In this case, it's fair to cut your payment by half. You did only half of the job and broke our agreement. I appreciate your efforts, but am yet to close my eyes on this... Misunderstanding.}
{239}{}{I am pleased by your diligence - you truly adapt well.}
{240}{}{My informants tell a different story. You're trying to fool me, and that's usually not forgivable. You are lucky I do not want to make a shooting spree in this operating casino, as it would harm its reputation. Now get out.}
{241}{}{[Leave peacefully.]}
{242}{}{In some ways we are alike - I don't forgive those who refuse to pay me for the work. Now you die!}
{243}{}{[Head to the ranch.]}

{244}{}{I need your advice on how to do the job better. Can a murder solve the problem?}
{245}{}{If you ever speak with such folly again, it will be our last conversation. I pay you for your own clever ideas... But, if you are really struggling with the job, then try to poison the supplies, or at least plant some explosives into them.}
{246}{}{I thank you, Mr. Bertolini, You've helped me alot.}
{247}{}{Alright, I'll try.}

{250}{}{Reception is over for now. Come back after eight in the morning.}
{251}{}{Thief! Guards! A thief!}

#Квест на диверсию на ранчо
{252}{}{All of a *sudden* a fire broke out in the Luciano's food hangar, and a large part of the goods have been destroyed. }
{253}{}{The ranch had a *incidental* cattle plague, soon after my *coincidental* visit there. }
{254}{}{I did not count on this; and you knew about it. Now Oliver won't be able to be pushed to an agreement, solving our disputes with minimal bloodshed. After this news, our cooperation has come to an end. Get out of my casino.}
{255}{}{[Leave]}

{256}{}{Great job! With such losses, Oliver will be much more malleable. Here is the payment for your services.}
{257}{}{Thanks, boss.}
{258}{}{From now on you can forget about him and his ranch. I will speak to him personally to offer help to rebuild his business. Now negotiations depend on me.}
{259}{}{So, you don't need my services?}

{260}{}{Well, you did all that I asked for. But, there is one last business. I will not insist if you refuse, nor will I ask twice. This is my personal request... Some family drama, so to speak.}
{261}{}{It is an honor to help you and your family.}
{262}{}{Oh, I don't interfere with domestic proceedings. I'm sorry, boss.}
{263}{}{I do not blame you. All of this work must have exhausted you. Well, head to the bar and unwind yourself at my expense. I won't keep you any longer.}
{264}{}{[Leave.]}
{265}{}{My son, Huey, must conduct a family affair. The problem is that the he has always been distinguished with... Superfluous pity. He has to kill a scoundrel, and your task is to make sure that everything goes *successfully*. After that, you will tell me how it went. Now get down to the first floor; there, you will find Huey.}
{266}{}{I will not fail you, Mr. Bertolini.}
{267}{}{And that's not everything. }
{268}{}{In addition, all of the slaves *accidentally* triggered their shock collars. The ranch was left without any slave labor. }

#Квест на Хьюи
{270}{}{As far as I know, you and Huey have returned from the scene. What happened there?}
{271}{}{I made Huey shoot a snitch. He himself would have failed to do so.}
{272}{}{I had to personally deal with the informer. Huey just stood aside and bellowed like a child.}
{273}{}{Huey had the courage to finish the matter.}
{274}{}{Huey allowed the victim to escape. I was unable to stop them.}

{275}{}{That sounds plausible. I know Huey very well - he lacks guts to do so. Strictly speaking, I knew that you have to do it, so accept my thanks along with payment.}
{276}{}{Thanks, Mr. Betrolini.}
{277}{}{You're lying. I know Huey very well. He lacks the guts to do so. I had hoped that you would do the work for him, but in the end you're lying to defend him. I don't know what you expect, but the job is done, and I am obliged to pay. From now on, I don't need your services. You may leave.}
{278}{}{Whatever you say, boss.}
{279}{}{And why am I not surprised by this? [he raises his voice] However - only one thing has surprised me - that you have come here, looking me in the eye, talking about the failure of the task. [he raises his voice even further] I don't pay you for night walks, you moron! Now our cooperation is over. Get out.}
{280}{}{[Leave.]}
{281}{}{[Attack.]}
{282}{}{Your reputation is well justified - you did a great service for me. For this, I declare you as my consigliere. My name means a lot in this town, and my associates usually arranged with good prices and easier concessions.}
{283}{}{Thanks. I appreciate it.}
{284}{}{Your help was very useful. I'll take care of any further matters myself. I have no additional jobs for you. You are free to go.}
{285}{}{Whatever you say, boss.}

{286}{}{I heard rumors that the one whom my son had to kill, still walks free. I guessed that Huey lacked the guts to do it, which is why I put you to watch over the situation. Instead, you just just shat in front of my house. I'm not going to tolerate this! Security - eliminate him!}
{287}{}{Oops... }
{288}{}{Wait a minute! I let you down, but I had my reasons. Think about it - what will my death get you, besides more heat from Stryker's gang and a fight in your casino?}
{289}{}{[He strokes his cheekbones, pondering your words] Get out of the casino. Stick your head in here again and I won't think twice.}
{290}{}{[Leave.]}
{291}{}{Wait a minute. I told Mr. Thompson about you. He was interested. Talk to him, and perhaps he will offer you some job.}
{292}{}{You gain }
{293}{}{ experience for achieving the status of consigliere.}

#Крыша для концерта в Коттон-клубе
{300}{}{I represent the "Cotton" Club. We'd like to negotiate a deal about protection during a concert.}
{301}{}{Good idea; I've been offering such a deal for a long time. After all, we are neighbors. Tell the owner of the club that I am willing to contribute to the concert, but with the condition of sharing revenue for each day of it. 35% of the revenue should be delivered to my desk in cash.}
{302}{}{We agree to these terms.}
{303}{}{We need to think about this proposal.}
{304}{}{Right decision. I will send my men to clarify the contract.}
{305}{}{Thanks, that's all.}

#Female character
{1123}{}{Boss, I know a lady who's forced to pay her debts to the casino after the death of her husband. Could you help to resolve this issue?}
{1151}{}{Communications? With whom... ?}
{1154}{}{Listen, I wasn't born yesterday. I've handled a lot of jobs in my time... }
{1178}{}{Come on, I just wanted to make an impression on you... }
{1181}{}{Did you meet the contact?}
{1182}{}{Yes, I found him at Oliver's ranch.}
{1184}{}{No, I haven't found him yet.}
{1188}{}{Hey, I completed the job!}
{1202}{}{Oliver and I used to get along well, but ten years ago a conflict emerged. When civil war broke out in the town, we stood on opposite sides of the barricades. Now, when those, who at the helm, are completely different people, I want to put an end to this story. You will help me. Here's something to instill your confidence - your payment.}
{1222}{}{This is good news. Did you do it... Quietly as I asked?}
{1224}{}{I have just been informed that Oliver Luciano has passed away. This destroys the purpose of my plan, and concerning your service... Well, I have no further orders for you. You may leave.}
{1226}{}{Yes, you've proven yourself, so I can trust you with a more serious mission. Your payment will also correspond with the significance of each task.}
{1228}{}{I need you to destroy Luciano's enterprise. He has to be knocked out of the rut, so that later I could dictate my conditions to him. And Oliver should not die under any circumstances.}
{1238}{}{In this case, it's fair to cut your payment by half. You did only half of the job and broke our agreement. I appreciate your efforts, but am yet to close my eyes on this... Misunderstanding.}
{1254}{}{I did not count on this; and you knew about it. Now Oliver will not be able to be pushed to an agreement, solving our disputes with minimal bloodshed. After this news, our cooperation has come to an end. Get out of my casino.}
{1260}{}{Well, you did all that I asked for. But, there is one last thing. I will not insist if you refuse, nor will I ask twice. This is my personal request...  some family drama, so to speak.}
{1271}{}{I made Huey shoot a snitch. He himself would have failed to do so.}
{1277}{}{You're lying. I know Huey very well. He lacks the guts to do so. I had hoped that you would do the work for him, but in the end you're lying to defend him. I don't know what you expect, but the job is done, and I am obliged to pay. From now on, I don't need your services. You may leave.}
{1279}{}{And why am I not surprised by this? [he raises his voice] However - only one thing has surprised me - that you have come here, looking me in the eye, talking about the failure of the task. [he raises his voice even further] I don't pay you for night walks, you moron! Now our cooperation is over. Get out.}
{1282}{}{Your reputation is well justified - you did great service for me. For this, I declare you as my consigliere. My name means a lot in this town, and my associates usually arranged with good prices and easier concessions.}
{1284}{}{Your help was very useful. I'll take care of any further matters myself. I have no additional jobs for you. You are free to go.}
{1286}{}{I heard rumors that the one whom my son had to kill, still walks free. I guessed that Huey lacked the guts to do it, which is why I put you to watch over the situation. Instead, you just just shat in front of my house. I'm not going to tolerate this! Security - eliminate this bitch!}
{1288}{}{Wait a minute! I let you down, but I had my reasons. Think about it - what will my death get you, besides fight in your casino and more heat from Stryker's gang?}

###################################################################
#
#   Разводка на секс
#
###################################################################

{310}{}{You're such a famous person in Reno. I always wanted to get to know you closer... }
{311}{}{[He grins lewdly] Sometimes I get bored in this town. All of these silly girls from the streets don't even know the rules of etiquette, and there's never much to talk about with them. Are you one of them, or just giving in to temptation?}
{312}{}{What are you saying?! Yuck! How could you! I would never lower myself to that level.}
{313}{}{Is it really so important to you on who to sleep with? Because you can afford anyone. Even several ones at the same time.}
{314}{}{My rose doesn't bloom for just anyone - and surely not for street rags.}
{315}{}{Methinks I've started with the wrong topic. Excuse me; I need a restroom.}

#-типаж: куртизанка
{316}{}{Many have claimed the same. Some lied, while others were genuinely convinced that they themselves make their own life decisions... What do you count on - to remain innocent and undamaged in this town?}
{317}{}{And why not? I'm counting on finding someone who I'll like. I have all the chances to choose, not to be chosen.}
{318}{}{Hmm. [he skeptically narrows his eyes and slowly blows cigarette smoke] A courtesan? You wield your tongue well. Are you a longtime resident in this town?}
{319}{}{No. Is this really important?}
{320}{}{Nevermind. I just want to understand how soiled you are in this dirty world. Here in Reno, people are changing as time passes. Urban life makes them sophisticated, vile and sly.}
{321}{}{Yeah. [make a bored look] I noticed.}
{322}{}{[He raises his brows] Did I bore you?}
{323}{}{Mr. Bertolini - you know... You're boring. VERY boring.}
{324}{}{Yes. You're telling the truth... Look, I'm busy right now. Put yourself in order if you want to continue this conversation. You look... Like a rural girl who spent all day digging potatoes.}
{325}{}{What impudence! Fine, Mr. Bertolini, I'll put myself in order. I'm just not sure, if it'll be for you, or someone else.}
{326}{}{Yes. You're telling the truth... [he claps his hands] I know what we'll do. We'll take a bottle of wine and retire to my office. You drink wine, right?}
{327}{}{I would prefer a martini, Mr. Bertolini.}
{328}{}{Now I look forward to only one thing - to get out of this room.}
{329}{}{No one is holding you here.}

{330}{}{[He chuckles] Whatever you say, darling. Whatever you say.}
{331}{}{[Leave.]}

#-типаж: ветреная шлюха
{340}{}{I'm not counting on anything. I'm just too bored in this town.}
{341}{}{It's been ages; and during that time, I never found a worthy partner.}
{342}{}{[He shrugs] You won't find anything neatly and innocent here.}
{343}{}{Yes, overall I'm bored with life. Can we have a drink? It will be more fun this way.}
{344}{}{[He raises his index finger] Exactly! I can afford anyone. I can buy any street whore for whatever entertainment I want. And she would be bound to me till death... But only as long as the money flows. And what do you count on? To remain innocent and undamaged in this town?}
{345}{}{Hmm... [he skeptically narrows his eyes and slowly blows cigarette smoke] I can feel it. Are you a longtime resident in this town?}
{346}{}{Really? You know, you have high requirements. But you're right. Living in a dirty world it's hard not to get underwear dirty. I do not know if you feel it, but many of those who came to Reno from the outside, have changed over time. Among them were those with a pure soul and body. All of them were ruined by city life.}
{347}{}{True. But there are those who retain their family traditions. Like Mr. Wright, for example. Although we hold from each other at a distance, I'm sympathetic to family values... Methinks I've bored you with my chatter?}
{348}{}{Yeah. It's the only thing left to do. Bye, Mr. Bertolini. See you around, maybe.}
{349}{}{[He grins with the edges of the mouth while changing posture, carefully assessing your hips when you rise from a chair and walk towards the exit]}

#-типаж: дорогая эгоцентричная дамочка
{350}{}{Mr. Bertolini, are you trying to insult me?}
{351}{}{Oh, no! I won't tolerate any insults towards women in my casino. But I'm really interested in you. What are you holding out for? After all, it's impossible to remain innocent and undamaged in this town.}
{352}{}{What I'm holding out for will remain with me. I don't like when someone digs through my underwear for dirty spots.}
{353}{}{[He raises his eyebrows, then breaks into a smile and actively shakes his head] Of course, of course. I like you. Specifically, your character. Are you a longtime resident in this town?}
{354}{}{No, not so long. I came from the north; it was a long and difficult journey.}
{355}{}{From the north... Hmm. Not many settlements there. Interesting. You see, in Reno, people are changing as time passes. You may still not understand this, but you can feel it. Urban life makes them sophisticated, vile and sly.}
{356}{}{So what? That's none of my concern. I don't even think about it.}
{357}{}{[He gazes at you enthusiastically] A strong woman... But you know, in Reno there are those who remain faithful to the family tradition. [he sighs, remembering something] You remind me of... Well, forget it. I think I'm starting to bother you. Or not?}
{358}{}{When you start to bother me, I'll just get up and leave.}
{359}{}{[Stare at him in astonishment, then turn from him and quietly walk away.]}

#-итог
{360}{}{[He sighs as you go, examining your hips] Don't worry, mommy. I won't run away.}
{361}{}{Is there anything more exciting?}
{362}{}{I'll pick it myself; don't worry.}

{363}{}{Oh, you are a strong and expensive woman. I'm looking forward to your sweetness paired with a good wine and delicate exposure. Please, come to my bedroom. [he makes a sign to the guards to not disturb]}
{364}{}{Now I can't let you get bored. Consider myself as your daddy for the entire evening. Let's go. [he makes a sign to the guards to not disturb]}
{365}{}{Whatever you say, mommy. Now I'll be your naughty son. You may spank me for the entire evening. [he makes a sign to the guards to not disturb]}
{366}{}{Very well. And now, let's not waste any time. Follow me. [he makes a sign to the guards to not disturb]}
{367}{}{[Follow him.]}

{368}{}{Sorry, Mr. Bertolini, I need to visit the restroom for a moment. See you later.}
{369}{}{About the evening for two of us. Have you changed your mind yet?}
{370}{}{I'm busy right now. [he looks you over, evaluating] Put yourself in order if you want to continue this conversation. You look... Like a rural girl who spent all day digging potatoes.}
{371}{}{[He claps his hands] Good! Let's take out a bottle of wine and retire to my office. You drink wine, right?}

{372}{}{Z-z-z... Gentle... Mommy...}
{373}{}{[He grins lewdly] Sometimes I get bored in this town. All of these silly girls from the streets don't even know the rules of etiquette, and there's not much to talk about with them... [suddenly he notices something in your behavior, then his face becomes stale] A drug addict? I should have guessed. Get out. In this state, don't you dare even try to touch me.}
{374}{}{[Leave.]}
{375}{}{You spend the whole evening in the Bertolini's arms. In bed he turned out to be an extremely tedious and garrulous partner.}