{100}{}{You see the mole.}
{101}{}{He looks like a shifty fella to you, but Bertolini has a special interest in him.}

{110}{}{That kid doesn't have what it takes, I get that. But what's stopping you?}
{111}{}{I've got an nose for opportunity, and your boss reeks of it. How about we do each other a favor?}
{112}{}{Nothing. I just wanted to see if you had any final words.}
{113}{}{I'm no murderer. I'm here to tell you you've got to lay low for a while. Change your hair, grow a beard, maybe.}
{114}{}{Do I have a choice? Alright, I'll put in a good word. I can't promise anything, but, heh, I think he could use someone like you.}
{115}{}{Actually, I just wanted to see how desperate he was for recruits. He's about to need one more. [Kill him]}
{116}{}{Good. Get out of here.}
{117}{}{You're not from around here, are you? That attitude's a good way to end up dead in the gutter... Look, you don't want to work for Bertolini. He's just a greedy businessman who thinks he's a gangster. If you want to make a real difference, I can put in a good word for you with my boss. No promises, but I think he'd want a man like you.}
{118}{}{I'll keep that in mind. Now go, before someone notices.}
{119}{}{I was willing to tolerate your actions. I will not tolerate insults to Mr. Bertolini. [Kill him]}

#Женские реплики
{1113}{}{I'm no murderer. I'm here to tell you you've got to lay low for a while. Change your hair, grow a beard, maybe.}
{1117}{}{You're not from around here, are you? That attitude's a good way to end up dead in the gutter... Look, you don't want to work for Bertolini. He's just a greedy businessman who thinks he's a gangster. If you want to make a real difference, I can put in a good word with my boss. No promises, but I think he'd want a woman like you.}
