{100}{}{You see Huey.}
{101}{}{You see Huey. He's the same as before.}
{102}{}{Do what you want.}

{110}{}{[Speaking to the victim] That's far enough. Here we should part ways. My father wanted to kill you, but I won't. And beg my partner to do the same.}
{111}{}{[Next]}
{112}{}{[The victim looks up at you both and speaks] Now I see why your father despises you. He always did... You are saying that I can go? I guess I ought to be thankful. I'll tell Stryker's people about what happened here.}
{113}{}{Whoa-whoa, stop. Huey, what are you doing?}
{114}{}{Calm down, partner. Go back and tell your father I finished the job. If he learns the truth, he'll kill us both. Do you understand what I'm saying?}
{115}{}{Hmm...}
{116}{}{Are you crazy or just stupid? Sooner or later, someone's going to see him walking around *not dead*. What's your plan then?}
{117}{}{I'm not going to be part of mess that my father and the other crime bosses make in this city. I don't care what he says. I don't care what he thinks. I'm not doing it.}
{118}{}{Again with this angsty rebellion bullshit? Grow up! Take your gun and do what you have to!}
{119}{}{Don't push me! I don't owe you anything! I don't owe anyone!}
{120}{}{You're weak! Pathetic! Get yourself together, this is your last chance to save your relationship with your father! Did you forget what happened to the others? Do you want that? Huh? Look at me! Face reality for once!}
{121}{}{Suit yourself. It's your life.}
{122}{}{Shut up! [he draws his head into shoulders and turns away from you] Kill him yourself then! I won't do it! I... I won't!}
{123}{}{[Take Huey's hand and point his weapon at the victim] Just pull the trigger, Huey. Just once. That's all it takes, and then you're free.}
{124}{}{[Huey trembles, becomes pale and turns his face away from the victim] Forgive me...}
{125}{}{[Next]}
{126}{}{[Huey's gun fires once, then again and again, as crimson blossoms on the twitching victim's clothes. An artery is torn open as he falls, a fine thick red mist sprays around, settling on your and Huey. Finally, Huey's weapon clicks empty, and the victim's body lies still.]}
{127}{}{It's over, Huey. Wasn't so hard as it seemed, was it?}
{128}{}{It's done Huey. You can turn your head now.}
{129}{}{[Huey, breathing heavily, struggles to turn his head towards the victim. He rubs his hand across his face and gags in horror seeing blood smears across it. He breaks free from your hands] Leave me! Leave me alone!..}
{130}{}{Don't worry, boy. It gets easier. Soon, you won't feel anything at all.}

#Женские реплики
{1110}{}{[Speaking to the victim] That's far enough. Here we should part ways. My father wanted to kill you, but I won't. And beg my partner to do the same.}
{1122}{}{Shut up! [he draws his head into shoulders and turns away from you] Kill him yourself then! I won't do it! I... I won't!}
