{100}{}{You see a guard.}
{101}{}{You see a hefty bodyguard.}

#Тема освещения
{102}{}{I'll go see what happened.}
{103}{}{Hey, you! If you see someone sneak in here, tear off his hands, clear?}
{104}{}{Something's not right. We should warn the others.}
{105}{}{Uh... Okay.}
{106}{}{I'm gonna find who did that and show him a *real* blackout.}
{107}{}{Well, if it isn't our saboteur!}
{108}{}{Again?! I lost patience with this the first time...}

{110}{}{Put your weapon away.}
{111}{}{I SAID, put your weapon away!}
{112}{}{Assassin! Protect Bertolini!}
{113}{}{A thief!}

{120}{}{Get out of here, you damn junkie!}
{121}{}{Don't even touch the boss. I've got my eye on you.}
{122}{}{Be happy. The boss is all the right things about you to all the right people.}
{123}{}{Office hours are over. Come back in the morning.}

#Разговор ночью с напарником
#! важно: пустые сроки не удалять - это паузы перед новым циклом реплик
{150}{}{Hey, anyone want to arm wrestle?}
{151}{}{No thanks, Duke. We like our arms attached to our bodies.}
{152}{}{Ha-ha-ha! You're damn right to fear me! Back in the ring, everyone did!}
{153}{}{Yeah, yeah, we know, you were a champion.}
{154}{}{Champion my ass, motherfucker! I was KING!}
{155}{}{A king, huh? You'd think a king could afford some new teeth.}
{156}{}{Ha! As if I care about the feeble insults of jealous plebeians.}
{157}{}{What did he just call us?}
{158}{}{Read a book, boy. There's no need to be physically AND mentally inferior.}
{159}{}{Hey, Duke. Why'd you leave the ring, again?}
{160}{}{...never mind that. Politics, that's all. The downfall of all kings.}
{161}{}{They used you, Duke. Like all the others.}
{162}{}{What did you just say?! You want me to crush your skull?}
{163}{}{Woah, what did I say?}
{164}{}{Watch your tongue, boy, or someone may someday make you eat it.}
{165}{}{Woah, I'm sorry, man. Respect. Look... Let's just calm down and start over, okay?}
{166}{}{ }
{167}{}{ }
{168}{}{ }
{169}{}{ }
