{100}{}{You see Huey.}
{101}{}{You see Huey. He's the same as before.}
{102}{}{Do what you want.}

{110}{}{[Speaking to the victim] That's far enough. Here we should part ways. My father wanted to kill you, but I won't. Beg my partner to do the same.}
{111}{}{[Next]}
{112}{}{[The victim looks up at you both and speaks] Now I understand why your father despises you. He always did... Are you saying I can go? I guess I should be grateful. I'll tell Stryker's men what happened here.}
{113}{}{Whoa, wait a second. Huey, what are you doing?}
{114}{}{Calm down, partner. Go back and tell your father I finished the job. If he learns the truth, he'll kill us both. Do you understand what I'm saying?}
{115}{}{Hmm...}
{116}{}{Are you crazy or just stupid? Sooner or later, someone's going to see him walking around *not dead*. What's your plan for that?}
{117}{}{I'm not going to participate in the mess my father and the other crime bosses are making in this town. I don't care what he says. I don't care what he thinks. I'm not going to do it.}
{118}{}{What a rebellious nonsense. Grow up! Take your gun and do what you have to do!}
{119}{}{Don't push me! I don't owe you anything! I don't owe anyone anything!}
{120}{}{You are weak! Pathetic! Pull yourself together, this is your last chance to save your relationship with your father! Have you forgotten what happened to the others? Is that what you want? А? Look at me! Face the reality for once!}
{121}{}{Suit yourself. It's your life.}
{122}{}{Shut up! [he draws his head into shoulders and turns away from you] Kill him yourself then! I won't do it! I... I won't!}
{123}{}{[Take Huey's hand and point his weapon at the victim] Just pull the trigger, Huey. Just once. That's all it takes. It will make you free.}
{124}{}{[Huey trembles, becomes pale and turns his face away from the victim] Forgive me...}
{125}{}{[Next]}
{126}{}{[Huey's gun fires once, then again and again, as crimson flowers blossom on the twitching victim's clothes. An artery bursts as he falls down, a thick red mist spreads around, settling on you and Huey. Finally, Huey's weapon clicks empty. The victim's body lies motionless.]}
{127}{}{It's over, Huey. It wasn't so hard, was it?}
{128}{}{It's done Huey. You can turn your head now.}
{129}{}{[Huey, breathing heavily, struggles to turn his head towards the victim. He rubs his hand across his face and gags in horror seeing blood smears across it. He pushes your hands away] Leave me! Leave me alone!...}
{130}{}{Don't worry, boy. It gets easier. Soon you won't feel anything at all.}

#∆енские реплики
{1110}{}{[Speaking to the victim] That's far enough. Here we should part ways. My father wanted to kill you, but I won't. Beg my partner to do the same.}
{1122}{}{Shut up! [he draws his head into shoulders and turns away from you] Kill him yourself then! I won't do it! I... I won't!}
