{100}{}{You see a bartender.}
{101}{}{You see a short, fat man behind a bar counter. He gives you a slight nod.}
{102}{}{ }
{103}{}{I don't serve childkillers.}

#Casual floats:
{200}{}{One rotgut coming right up... }
{201}{}{That'll be three bucks... }
{202}{}{Another one, friend?}
{203}{}{Here's your medicine if you want it!}
{204}{}{You can't barf here! Go outside and barf there!}
{205}{}{Two half-ounce bags or a tin?}
{206}{}{Special order for Tim Cain... }
{207}{}{Let me guess: put it on your tab?}
{208}{}{One "dive bomb" with ice, coming right up.}
{209}{}{Hey, you can't just shoot that shit here!}
{210}{}{You know why we need to hang these actors? 'Cause the theater begins with the hanger... Ha-ha-ha!}

#Dialogue start
{229}{}{How can I help you?}

{230}{}{Need something, chummer?}
{231}{}{Drink. Show me what you've got.}
{232}{}{No thanks.}
{233}{}{Anything else?}
{234}{}{I'll have another one.}
{235}{}{No thanks. I need to ask you something.}

{236}{}{Of course, of course. I think you'd like to know we have special prices for those who are *with us*}
{237}{}{Glad to hear.}
{238}{}{You received a big discount at the bar.}

#If PC has a weapon
{240}{}{Sir! This is a casino, not a firing range!}

#Bertolini died
{241}{}{Speaking of, where's your boss? I need to, err, talk to him.}
{242}{}{I haven't seen him in a while. No one has any idea where he is. It's a shame, too - I wanted to ask for a raise... }
{243}{}{How are you handling things without him?}
{244}{}{Administration never rests. We can handle ourselves without Mister Bertolini... For a while, at least.}
{245}{}{Alright... }

#About Ted Bundy:
{251}{}{Mom mentioned some guy named Ted Bundy. Heard of him?}
{252}{}{Ugh. Yeah, I have. Not much though. Would've been better off if I didn't. He's a maniac. Ambushed some of our girls and carved them up with some mechanical knife. Fucking animal. Nobody knows where he lives or how to deal with him. But, as long as you're careful, you should be fine.}
{253}{}{Do you know anything about the girl in this picture?}
{254}{}{Well, she's probably one of the previous dancers. But if that is so, she worked here before me. So, I probably can't help you there... Hold on... "Virginia 75"? I'm not sure, but I think that's somewhere around here.}
{255}{}{I'm new here. Mind telling me what working here is like?}
{256}{}{Well, you know, the collective's nice. But the clients cause problems from time to time. Something you should get used to. Might throw a bottle, or try to get across the railing to the dance floor. And there are complete retards like that pussy from the slums. Harding I think. Locked himself in the toilets and started crying like a little bitch. Had to carry him out in the streets, heh-heh... Point is, best to always keep an eye out.}

#About Racer's shades
{260}{}{Do you know anything about someone named Racer starting a fight?}
{261}{}{Yeah, I do. He didn't get far. We kicked his ass to the curb where he belonged. If only he'd gone down the drain, like the hobo piss he is. Hopefully he'll know better than to show his mug here again.}
{262}{}{You really don't like him, do you?}
{263}{}{Did you see his mirrored shades anywhere?}
{264}{}{Nevermind.}
{265}{}{He's one of the bandits that always hangs around Stryker. They think themselves as revolutionaries or something, but bandit's the right word. What the hell are they even revolting against? Other tyrants like themselves? Although, I think I got carried away a little. Just can't bring myself to imagine what will happen if Stryker comes to power. Business isn't doing too well as it is.}
{266}{}{Got 'em right under the counter. Still thinking if I should throw them out or sell them. Compensation for injured feelings and the such.}
{267}{}{I wouldn't do that if I were you. I think you should give them to me so I can return them to Racer.}
{268}{}{I want them. How much do you need?}
{269}{}{Throw them out for all I care.}

{270}{}{What? And why is that?}
{271}{}{Why do you think? You're dealing with another man's property like it's your own. Sooner or later, he'll find out, and he's already on edge - just think about it!}
{272}{}{True, true. Who knows what to expect from his type. Wouldn't want to wake up in a dumpster with a bullet in my gut after an evening walk home. Here you go, don't even mention me. If he asks, just say someone picked them up.}
{273}{}{Wise choice.}
{274}{}{Alright, I'll just put them down. If you have something valuable to trade, I'll be more than happy.}
{275}{}{Let's trade then.}
{276}{}{We'll talk about it sometime later.}
{277}{}{Trust me, I know what I'm talking about.}

#Question about Chase and work in Reno
{280}{}{I'm looking for a place to earn a few bucks. Mind pointing me in the right direction?}
{281}{}{Hmm... You're new in town, right? No friends, no connections... I doubt you have much chance. Unless... }
{282}{}{Unless?}
{283}{}{Well, I'd suggest finding a common interest with a few... Influential people. [he looks around the room] Take that gentleman by the pool table, for example. Regular client. Respectable man! Always has money and always orders expensive drinks. I don't know who he works for, but those are the types of people you should look into meeting.}
{284}{}{Thanks for the tip.}
{285}{}{Of course, any time... I hope you won't forget about me? [he smiles and winks]}
{286}{}{Oh yeah, here's a fiver. Thanks.}
{287}{}{Sorry, but I really am empty today. Some other time.}
{288}{}{A pleasure serving you!}
{289}{}{Of course.}

#About Mom
{300}{}{Say, why do they call Mom that?}
{301}{}{Well, as far as I know, she doesn't have kids of her own. But she really cares for those who work for her. And if you consider most of the girls here are orphans - Rose really became their mother.}
{302}{}{So, her name is Rose?}
{303}{}{Well, obviously it's not Mom! Her real name is Rose Lee. But nobody cares for that unless they're close.}
{304}{}{Understood.}

#Female version:
{1202}{}{Another one, friend?}
{1209}{}{Hey, you can't just shoot that shit here!}
{1230}{}{Need something, chummer?}
{1240}{}{Ma'am! This is a casino, not a firing range!}
{1241}{}{I don't get it. Why is there such a panic in the casino?}
{1244}{}{Chummer, even our boss can't handle money like *that!*}
{1261}{}{We don't stock dope for the casino. Although, the one you're talking about did appear here. More than once. Our boys threw him straight into the streets. Didn't see him since then. And speaking of [he leans in] we're a *respectable casino* - not some hole. I'd keep the topic to myself if I were you. Okay?}
{1262}{}{Got it.}
