{100}{}{You see a janitor.}
{101}{}{You see a child cleaning the halls.}

{110}{}{Can I help you, sir?}
{111}{}{Tell me what you do here.}
{112}{}{Nothing yet.}

{113}{}{I'm just a janitor, sir. I make sure the hallways and rooms are clean.}
{114}{}{But... You're just a kid.}
{115}{}{}
{116}{}{[He furrows his brow] Everybody says that! Then they go outside and get shot, or die from overdose laying in trash. I get my money without lying or hurting anyone. That's better than most of the grown-ups I've met.}
{117}{}{Tell me honestly, are you *forced* to work?}
{118}{}{Hmm, does your boss treat you well?}
{119}{}{Hey, do you know who cleans Bertolini's office?}
{120}{}{I see. I'll let you get back to work.}
{121}{}{Oh no, sir! Well... I have to work to get money. Even if I'm dead tired at the end of shift. No one will feed me, but myself.}
{122}{}{He... Well... Yes. He doesn't beat me, but... He's scary... And rude sometimes. But I'm still glad I got the job. It's an honor.}

{123}{}{[He looks worried] That would be me, sir... Is Mr. Bertolini unhappy? He's... He's not angry, is he?}
{124}{}{Something tells me this is a tough job. How about we make a deal?}
{125}{}{No, err, just wanted to say you did a great job.}
{126}{}{A deal? Is that when you pay me for something special and then Mr. Bertolini takes half?}
{127}{}{Not this time. In fact, you shouldn't tell him about it. I'll pay you to install these bugs in his study.}
{128}{}{Bu-gs? What are these?}
{129}{}{Don't worry. Just remember - nobody should ever find them, understood?!}
{130}{}{I... I think so. But if Mr. Bertolini finds out, he'll kill me!}
{131}{}{In that case, forget everything I said.}
{132}{}{Then make sure he doesn't. Do this and you get paid. Deal?}
{133}{}{Ugh, listen kid, if you keep your mouth shut and don't screw up, I'll pay you so much you can forget about work for a month!}
{134}{}{[He thinks about it, looking at you with doubt in his eyes] No... No, sir, this is too dangerous!}
{135}{}{I knew it! Never send a child to do a man's job. I'll handle it without you.}
{136}{}{Hmm, looks like I'll have to try something else.}
{137}{}{Really?! [he thinks hard for a moment] Uh, give me... $500, and I'll hide your bugs in Mr. Bertolini's office.}
{138}{}{Here's the money and the bugs. I'll be waiting. And remember - not a word to anyone!}
{139}{}{Wait up, I'll be back.}
{140}{}{Bertolini's study is now wired.}

#Женские реплики
{1110}{}{Can I help you, ma'am?}
{1113}{}{I'm just a janitor, ma'am. I make sure the hallways and rooms are clean.}
{1121}{}{Oh no, ma'am! Well... I have to work to get money. Even if I'm dead tired at the end of shift. No one will feed me, but myself.}
{1123}{}{[He looks worried] That would be me, ma'am... Is Mr. Bertolini unhappy? He's... He's not angry, is he?}
{1131}{}{In that case, forget everything I said.}
{1134}{}{[He thinks about it, looking at you with doubt in his eyes] No... No, ma'am, this is too dangerous!}
{1135}{}{I knew it! Never send a child to do a woman's job. I'll handle it without you.}