{100}{}{You see a ruffian.}
{101}{}{You see a ruffian by the name of Basketball Buddy.}

{110}{}{Oh, no, no. If someone as handsome as me just let people stop and stare, then no one would get any work done. So unless you have business, keep walking.}
{111}{}{Oh, it's you... Um, salutations.}
{112}{}{Oh, it's you... Um, salutations! Please, tell your boss I wish him the most pleasant of days.}
{113}{}{}
{114}{}{[Keep walking.]}

#Набор отмычек
{120}{}{I'm looking for something special.}
{121}{}{Do you still have that lockpick set?}
{122}{}{Special? Why, I just happen to have a set of picks right here. You could be the proud owner of a picks owned by Basketball Buddy, the most beloved rogue on the Reno streets!}
{123}{}{Picks?}

{124}{}{Try to keep up, would you? I've got a full set of lockpicks and tension wrenches for you. Irreplaceable and invaluable tools for the best of the best.}
{125}{}{How much?}

{126}{}{"How much." [he rolls his eyes theatrically] Look, buddy, the brain-dead common rabble may think Reno is ruled by money, but I know better. Reno's ruled by a reliable gun in your hand.}
{127}{}{You need a gun?}

{128}{}{Not just anything. I need a pistol in a common caliber. I'll trade these picks, and believe me, they're worth it. If not, would I even be carrying them?}
{129}{}{I'll think about it.}
{130}{}{You really shouldn't have told me you don't have a gun. [Attack.]}

{131}{}{}
{132}{}{A successful deal! Time for Basketball Buddy to find his place in Reno...if you need anything else, come find me.}
{133}{}{Bye.}

{140}{}{I have a 10mm pistol. Calibers don't get more common than that.}
{141}{}{I have a 10mm pistol. It even has an extended magazine.}
{142}{}{I have a 10mm pistol. It's an older model, but, uh, that just makes it classier.}
{143}{}{I have a 10mm pistol with an attached flashlight.}
{144}{}{I have a Magnum revolver.}
{145}{}{I have a Magnum revolver. I'll even throw in this speed loader.}
{146}{}{I have a Desert Eagle.}
{147}{}{I have a beautiful gold-plated Desert Eagle.}
{148}{}{I have a Desert Eagle with a sight.}
{149}{}{I have a Desert Eagle. It even has an extended magazine.}
{150}{}{I have a "Detective special".}
{151}{}{I have this premium 10mm pistol. Isn't she a beauty?}

#Коктейль Молотова
{200}{}{Why not? But I'm not going to go digging through trash for components. Bring me a bottle of beer, a pinch of Rotgut and a signal flare, and I'll mix you up a cocktail for }
{201}{}{ bucks.}

{202}{}{Make one.}
{203}{}{Make two.}
{204}{}{Make three.}
{205}{}{Make five.}
{206}{}{Make ten.}
{207}{}{Not now.}

{208}{}{I see you have a firebomb. Will you make one for me?}
{209}{}{I need a firebomb.}

{210}{}{Take it. And... Be careful out there. I wouldn't want to lose such a client.}
{211}{}{Okay.}
{212}{}{Of course! Anything for you! All I need is a bottle of beer, a pinch of Rotgut, and a signal flare to set it off. And, uh...}
{213}{}{ dollars. That's the special price for you and your boss.}

#Female character
{1126}{}{"How much." [he rolls his eyes theatrically] Look, beautiful, the brain-dead common rabble may think Reno is ruled by money, but I know better. Reno's ruled by a reliable gun in your hand.}
