{100}{}{You see a lowlife.}
{101}{}{You see a lowlife nicknamed Sammy the Rascal. He is carefully looking up and down the street.}

#Starting dialogue
{109}{}{Hey, hotshot! Got a light?}
{110}{}{Hey, wanderer! Got a light?}
{111}{}{Speaking of light. I see you've got a firebomb. I might need one. Could you help me out?}
{112}{}{You again. What is it this time?}
{113}{}{I need a firebomb.}
{114}{}{Light? No I don't.}
{115}{}{Nothing right now.}

#Dog food scam
{150}{}{Hey, hold on! How about a gourmet meal? Interested?}
{151}{}{What?}
{152}{}{Well you see... I've got a pre-war meal-in-a-can, a dietary meat supplement. Better than in the finest restaurant of Reno!}
{153}{}{Really? What kind of meal?}
{154}{}{Meat, friend. Just meat. Well... Meat mixed with bread and soaked in Nuka-Cola is as good now as it was the day it was canned. No one had refused yet. Everyone was satisfied.}
{155}{}{How much do you want for it?}
{156}{}{100 bucks and the whole can is yours.}
{157}{}{100 bucks? Good price for a *quality* product these days.}
{158}{}{Hey, listen. It's a sealed can. Some of that pre-war magic! Haven't you ever tried Dandy Boy Apples or Fancy Lad Snack Cakes? It's like that, but *gourmet*.}
{159}{}{Not the most convincing pitch. But I think I'll take one. Here's your hundred.} 
{160}{}{Not the most convincing pitch. I think I'll decline.}
{161}{}{Up to you. Just don't come whining to me when I'm all out!}
{162}{}{We'll see.}
{163}{}{Don't worry, friend! My customers are always satisfied!}
{164}{}{Yeah.}

{165}{}{Hey, you still got that meal-in-a-can you were talking about?}

#Dogfood – attempt to get money back
{180}{}{You lied to me! That wasn't real food! Give me back my money!}
{181}{}{Friend, I have no idea what you're talking about.}
{182}{}{I'm talking about this can of rotten mush you sold to me!}
{183}{}{Hey, you must've confused me with someone! I don't sell food.}
{184}{}{What?! You really gonna play innocent?!}
{185}{}{Shit, you need to lay off the chems.}
{186}{}{You piece of shit! Give me my money back or I'll take it off your corpse!!!}
{187}{}{Is that so?! Fine, just know that one day, I'll be back and will have my revenge.}
{188}{}{Lesson learned. Now I know what kind of trash lives in this city. But, I'll leave you in peace.}

{190}{}{Hey-hey, easy there. Let's solve this without violence...}
{191}{}{Don't even think about feeding me any more of your shit. I can see right through you...}
{192}{}{Fine, fine... Whew... Sorry about that little misunderstanding. Here's your hundred and another one on top, for the trouble. Just chill.}
{193}{}{That's better!}
{194}{}{You receive experience for serving justice.}
{195}{}{Yes, life can be unfair. Nevertheless, bad experience is experience all the same.}
{196}{}{You want to talk to my boss about this? Just so you know, he has a special distaste for smart-asses like you.}

#Molotov 
{200}{}{Molotov Cocktail? No problem. But you need to bring me the raw materials and, oh... }
{201}{}{ bucks. Lemme see... I need a bottle of beer, a bottle of Rot Gut and a bit of oxidizer from those signal flares.}

{202}{}{Make me one.}
{203}{}{Make me two.}
{204}{}{Make me three.}
{205}{}{Make me five.}
{206}{}{Make me ten.}
{207}{}{Hold on, I'll grab some components.}

{210}{}{Here you go. And... Try not to set yourself on fire. Who's going to buy more if that happens?}
{211}{}{Okay.}
{212}{}{No problem. All I need is a beer, rotgut, a signal flare, and }
{213}{}{ bucks. That's a special price, out of respect for your boss.}

#Making fun of metal detector
{300}{}{Oh-ho! Lookie here, a weirdo with a stick!}
{301}{}{Look, look! What's that in his hands?}
{302}{}{Hey, what's he doing there?}
{303}{}{Am I tripping? Or is there really a guy walking around with a stick?}
{304}{}{Hey, wanderer, no treasure here, don't bother looking.}
{305}{}{Looking for something? Maybe I can help?}
{306}{}{Tell me if you find anything, okay?}
{307}{}{Looking for coins in the gutter... What a life!}
{308}{}{Yeah! I think I see something shiny in there!}
{309}{}{We need people like you... When they find something valuable.}

#Female version:
{1109}{}{Hey hotshot! Got a light?}
{1110}{}{Hey wanderer! Got a light?}
{1150}{}{Hey, hold on! How about a gourmet meal? Interested?} 
{1154}{}{Meat, friend. Just meat. Well... Meat mixed with bread and soaked in Nuka-Cola is as good now as it was the day it was canned. No one had refused yet. Everyone was satisfied.}
{1163}{}{Don't worry, cutie! My customers are always satisfied!}
{1181}{}{Sister, I have no idea what you're on about.}
{1183}{}{Sister, you got me confused with someone. I don't sell food at all.}

{1300}{}{Oh-ho! Lookie here, a weirdo with a stick!}
{1301}{}{Look, look! What's that in her hands?}
{1302}{}{Hey, what's she holding there?}
{1303}{}{Am I tripping? Or is there really a guy walking around with a stick?}
{1304}{}{Hey, baby, no treasure here so don't bother looking.}
{1305}{}{How about you come here and I give you something else to hold?}
{1306}{}{Hey, tell me if you find anything, okay?}
{1307}{}{Looking for coins in the gutter... What a life!}
{1308}{}{Yeah! I think I see something shiny in there!}
{1309}{}{We need people like you... When they find something valuable.}
