{100}{}{You see hoodlum.}
{101}{}{You see a hoodlum nicknamed Stinkin' Grizzly, carefully looking around.}

#Not the robbery
{102}{}{This is *our* territory.}
{103}{}{Who do we have here? Oh, look, it's Mr. Nobody from yesterday!}
{104}{}{Uh, I'll just go...}

#Thompson's quest
{110}{}{Right, shut the fuck up and listen. You roughed up one of Mr. Thompson's girls. I'll listen to your excuse and then geek you like it's usually done.}
{111}{}{W-what!? How was I meant to know?! They didn't tell me anything about that!}
{112}{}{They? Tell me about this... Third party and I *might* let you go.}
{113}{}{I don't give a fuck who hired you. I'm here to deal with you.}
{114}{}{I don't know who they are! They looked like they're from out of town. Walk like they got a pole shoved up their ass, talk in orders. Paid me to rough up that girl and then left. That's it, honest!}
{115}{}{Uh-huh, you didn't spend the money yet, did you? Hand it over.}
{116}{}{Sure, sure! Here it is, just, err, let's forget about it, okay? I'll send my apologies to Mr. Thompson and then disappear from the streets. I promise!}
{117}{}{Fine by me. Get the fuck out now.}
{118}{}{I don't think so. I changed my mind!}

{119}{}{Enough! Please, stop!}
{120}{}{This is enough to make Stinkin' Grizzly disappear from this hood.}

{121}{}{Ah? Noo! I'm not afraid! Bite me, you corporate cog!}
{122}{}{[Fight]}

#Robbery
{150}{}{Hey you! Hold on a sec!}
{151}{}{[Approach]}
{152}{}{[Ignore]}

{153}{}{Hey friend, mind helping me out with a few bucks?}
{154}{}{Sure thing, here's 2 bucks.}
{155}{}{Here's 10, now leave me alone.}
{156}{}{Why would I give you anything?}

{157}{}{What, that's it?}
{158}{}{You did ask for a few bucks!}
{159}{}{Ugh, here's another 10, just let me go.}

{160}{}{Ah, yeah, sorry friend. You're free to go. [he grabs the money and walks off, smirking]}
{161}{}{[Leave]}
{162}{}{And I said - not enough! Cash in! Now! Or I'll spread you across the asphalt!}
{163}{}{Like hell! You're not getting one dollar from me!}

{164}{}{Good enough. Keep moving. [he grabs the money and walks off, chuckling]}
{165}{}{[Leave]}

{170}{}{[He runs up and grabs your shoulder] Hey! I'm talking to you! I don't stand for that disrespect. Give me your money before I get pissed, hear me?}

{171}{}{Can't spare a few bucks? Maybe me and my boys can change your mind. Why don't you come over and we'll talk it out?}
{172}{}{What, that's it? My boys are tougher. I'll just go and get 'em...}

{173}{}{Ha! I know everyone around here, you can't fool me. Come on, turn out those pockets! Quick! [he grabs your sleeve]}
{174}{}{[Resist]}
{175}{}{[Comply]}
{176}{}{[Your pockets are emptied of all of your cash] Wasn't someone rich?! Now *off* my street! I don't wanna see you again!}
{177}{}{[Leave]}
{178}{}{I'll paint this street with your blood!}

#making fun of the metal detector
{300}{}{Hah! Lookie here! A weirdo with a stick.}
{301}{}{Look, look! The hell is he carrying?}
{302}{}{Look at that! A guy with a stick.}
{303}{}{Am I tripping or is this guy just carrying around a stick?}
{304}{}{Hey you, there's no treasure here, don't even look.}
{305}{}{Looking for something? Need help?}
{306}{}{Hey, tell me if you find something, kay?}
{307}{}{Looking for coins in the gutters, what a life...}
{308}{}{Yeah, find some money!}
{309}{}{We need people like you... When you find something useful.}

#Женские реплики
{1103}{}{Who have we here?}
{1153}{}{Hey girlfriend, mind helping me out with a few bucks?}
{1160}{}{Ah, yeah, sorry girlfriend. You're free to go. [he grabs the money and walks off, smirking]}
{1170}{}{[He runs up and grabs your shoulder] Bitch! I'm talking to you! I don't stand for that disrespect. Give me your money before I get pissed, hear me?}
{1171}{}{Can't spare a few bucks? Maybe me and my boys can change your mind. Why don't you come over and we'll talk it out?}
{1176}{}{[Your pockets are emptied of all of your cash] Wasn't someone rich?! Now *off* my street! I don't wanna see you again!}

{1300}{}{Hah! Lookie here! A weirdo with a stick.}
{1301}{}{Look, look! The hell is she carrying?}
{1302}{}{Look at that! A girl with a stick.}
{1303}{}{Am I tripping or is this girl just carrying around a stick?}
{1304}{}{Hey you, there's no treasure here, don't even look.}
{1305}{}{Looking for something? Need help?}
{1306}{}{Hey, tell me if you find something, kay?}
{1307}{}{Looking for coins in the gutters, what a life...}
{1308}{}{Yeah, find some money!}
{1309}{}{We need people like you...when you find something useful.}
