{100}{}{You see a teenager.}
{101}{}{You see a long haired teenager. There are many like him wandering the streets of Reno.}
{102}{}{Behold! Before you is a talented graffiti artist, engrossed in his craft.}

{105}{}{I don't talk to strangers.}
{106}{}{Don't even ask.}
{107}{}{Touch me and my dad will tear your head off!}
{108}{}{Don't even think of touching me! My gang will paint the walls with your blood!}
{109}{}{Leave me alone!}

#Night and evening
{150}{}{[Upon noticing you, the kid looks around nervously] Leave me alone!}
{151}{}{What are you doing out here so late?!}
{152}{}{With pleasure!}

{153}{}{I?... I... I'm coming home from a party!}
{154}{}{Really? Well, go on then! And don't let me catch you around here again.}

{155}{}{I'M JUST GOING HOME!!!}
{156}{}{Fine, fine, don't freak out...}

#When caught
{200}{}{[Quietly, you sneak up on the vandal and grab his wrist] AAAAAH!!! SHIIIT!!!}
{201}{}{I knew it! You're the one vandalizing the hotel walls! I've got you, you little brat!}
{202}{}{SO WHAT?! THEY'RE JUST WALLS! LET ME GO, MAN!!!}
{203}{}{This is your one warning. If I see you again, I'm selling you to the slavers. Understood?}
{204}{}{Too late, kid! Should've thought of this sooner. Now march your butt into the hotel and we'll see how they feel about your work on their "just walls". Move it!}
{205}{}{Thank you! Thank you! I won't tag these walls anymore! Promise!}
{206}{}{You'd better not! I'll be watching. Now, scram!}

{207}{}{You solved the problem peacefully, but there is no guarantee that the kid will stop.}
{208}{}{Congratulations! You caught the elusive miscreant.}
{209}{}{}

{210}{}{I think I shit my pants. Can I go home?}
{211}{}{So this is the little bastard vandalizing our hotel! You've been a real pain in my ass, kid, you know that?}
{212}{}{I won't do it again!}
{213}{}{Yeah, right. Why'd you go and mess up our walls in the first place?}
{214}{}{Well... Everyone does...}
{215}{}{So you might as well, too, huh? All the cool kids are doing it!}
{216}{}{I... Just... I just wanted to paint.}
{217}{}{What?}
{218}{}{Hmm.}

{250}{}{Well, we got the little punk. What do you think we should do with him?}
{251}{}{He'll only remember one kind of lesson - flog him!}
{252}{}{I think he's had enough. I doubt he'll do it again.}
{253}{}{Make him clean the walls. That should teach him a lesson.}
{254}{}{Why not put him to work? Pay him to paint something nice on the wall. That'll bring in the tourists, won't it?}

{255}{}{I guess you're right. We'll deal with him ourselves, thanks for your help. Oh yeah, and 100 bucks for a job well done. All the best!}
{256}{}{[Leave.]}
{257}{}{Hmm... I hope you're right. Thanks for your help. Oh yeah, and 100 bucks for a job well done. All the best!}
{258}{}{I like the way you think! We'll teach him a lesson and get some work done at the same time! Thank you for your help. Oh yeah, and 100 bucks for a job well done. All the best!}
{259}{}{Hey, I think you're on to something there! The kid's not half-bad with a spray-can, you know... I'll have to talk to my boss, but I think the kid's got a job. Thanks for your help! Oh yeah, and 100 bucks for a job well done. All the best!}
{260}{}{You found a wise means of dealing with the graffiti artist.}

#Женские реплики:
{1201}{}{I knew it! You're the one vandalizing the hotel walls! I've got you, you little brat!}
{1202}{}{SO WHAT?! THEY'RE JUST WALLS! LET ME GO, LADY!!!}
{1205}{}{Thank you, lady! I won't tag these walls anymore! Promise!}
{1206}{}{You'd better not! I'll be watching. Now, scram!}