{100}{}{You see a street kid.}
{101}{}{You see an elusive graffiti artist.}
{102}{}{Your old beater has been transformed into one slick ride!}
{103}{}{That looks amazing!}
{104}{}{Help!}

{110}{}{You again?! I'm not doing anything wrong, I swear!}
{111}{}{Yeah? Looks like you're up to your old tricks. If I catch you one more time...}
{112}{}{I hope you've learned your lesson. See you around.}
{113}{}{Hey, man, are you open to a mutually beneficial partnership? I think my car needs a new coat of paint.}
{114}{}{R-really? I can paint a *working* car?! I'll do it!!! What do you want on it? I can do anything!}
{115}{}{Just repaint the whole thing so it looks new again. And... Put a Sheriff's star on the door. It's going to be very... Conceptual.}

{116}{}{It'll be perfect, I swear! But, uh... How much are you going to pay for it?}
{117}{}{I'll give you a hundred dollars.}
{118}{}{Nothing.}

{119}{}{Pfft, a hundred for all that? Give me, uh... Two hundred.}
{120}{}{You little bloodsucker! Fine, two hundred. And not a penny more!}
{121}{}{Sorry, kid. You're getting a hundred.}
{122}{}{Two hundred, or nothing!}
{123}{}{Fine! Here's two hundred dollars. Get to work!}
{124}{}{Then nothing. Bye, little bloodsucker.}
{125}{}{Hmph! Okay, okay, you convinced me. Oh, boy... A real car! Give me the money, I'll be quick.}
{126}{}{Here's your hundred. Let's see your magic.}
{127}{}{On second thought, I think I like the beaten-up look. Never mind, kid.}