{100}{}{You see a citizen of Reno.}
{101}{}{You see Harding.}
{102}{}{You see a resident of the slums. You'd want to say he's seen better days, but actually he looks like he's never seen a good day in his life.}

{103}{}{Thank you, I really do feel a lot better. Although these pills make me feel kinda limp.}
{104}{}{Thank you for the support, friend. You're an example to live by.}

#First dialogue
{110}{}{[You notice a few tears glistening on his cheeks.] Huh? Who are you?}
{111}{}{My name is }
{112}{}{. What happened to you?}
{113}{}{I'm a bandit. You'd better hand over all your cash, pronto!}
{114}{}{Santa Claus. I'm outta here.}
{115}{}{This seems like a bad time. I'll be back when you're feeling better.}

{116}{}{Yeah? That's funny, 'cuz I don't have anything. Look! There's nothing here. Wright's men already took everything I had!}
{117}{}{Relax, it was just a joke. By the way, I'm }
{118}{}{Then sit tight. And not a peep. Got it?}
{119}{}{Shucks, I'm going then. You can relax.}

{120}{}{Sorry, it's just depression, nothing serious. I'm Harding, your local handyman. How can I help ya?}
{121}{}{Boo-hoo, would you look at those tears! Are you a man or a rag, Harding?!}
{122}{}{It sure looks serious, Harding. Can I do anything to help?}
{123}{}{So long, Harding.}

{124}{}{Hello there. I've pretty much recovered now. How can I help ya?}
{125}{}{You're right - I'm nothing but a rag. My neighbors laugh at me and I'm forced to do everyone's dirty work because I'm a pushover. No, I won't make any excuses. That's how the world works. They're wolves and I'm a sheep. That's just how it is.}
{126}{}{Help? How? With the depression? I seriously doubt it. I often get the feeling of utter insignificance. I'm nothing but a rag. My neighbors laugh at me and I'm forced to do everyone's dirty work because I'm a pushover. No, I won't make any excuses. That's how the world works. They're wolves and I'm a sheep. That's just how it is.}
{127}{}{Maybe your neighbors ought to be taught a lesson.}
{128}{}{Well, I don't think I can help here. I'll be off.}
{129}{}{God no! Not at all! They can't be helped, nor it's needed. Everything is as it should be. Society is putting me in my place, I suppose.}
{130}{}{Why are you giving up so easily?}
{131}{}{Well, I had to try. Bye, Harding, I'll see you later. Maybe.}
{132}{}{One good man is teaching me how to live among people. He says that I can survive if I submit. It's not always easy.}
{133}{}{Hmm. Alright, I'm going now.}

#About mormons and the club
{140}{}{What did your neighbors say about the anonymous club?}
{141}{}{They told you about that place, huh? You see? I didn't do anything to them and they're already pouring a ton of swill into my chipped pot.}
{142}{}{Er, chipped pot?}

{143}{}{Yeah. All of us who go to the club - we're humanity's chipped pots. Thrown out into the trash but we're still trying to stay alive. And people like to see that - after all, who doesn't enjoy a good show?}
{144}{}{Tell me about this club.}
{145}{}{So who leads the club, anyway?}
{146}{}{Who are the other "pots" in this club of yours?}
{147}{}{}
{148}{}{}
{149}{}{That's enough for now. I'll see you later.}

{150}{}{Nobody cares about it except for us. It's a small gathering of people who want to find the strength to live on. We get together and talk about our problems and such. You wouldn't be interested... }
{151}{}{Patrick put it all together. He's a good man, preaches the word of God and always listens to those in need. But he just knows what needs to be done. Other than that, we have no leader.}
{152}{}{I won't say anything about that. We can't talk behind each other's backs.}

#Choice of healing
{160}{}{Listen, I talked to Patrick about your club... }
{161}{}{What?! How dare he?! He promised not to discuss anything behind our backs! And you... What did you talk about? He told you about us, didn't he? Did you laugh at us? Please, go away! I don't want to see any of you anymore!}
{162}{}{Please, go away! I don't want to see any of you anymore!}
{163}{}{No, no, calm down! I'm here to help you. We can trust each other, can't we?}
{164}{}{Well fuck you too, you pathetic imbecile!}
{165}{}{Fine, I'm going.}
{166}{}{Is that so? Can I really be helped? Is there someone who can mend the crack in my pot?}
{167}{}{Perhaps nobody can, but you can't keep suffering. I have anti-smoker tablets that dampen emotions. You'll feel better, trust me.}
{168}{}{Of course! Your problems stem from your feelings of inferiority. If we resolve that, you'll be able to fix your other problems.}
{169}{}{Hmm, I'll need to think about it. I'll be back soon.}
{170}{}{I don't know how to fix your inferiority complex. Especially since it's so richly deserved.}
{171}{}{Here's a ticket to Mom's nightclub. You should go there and relax.}
{172}{}{You can't keep suffering. I have anti-smoker tablets that dampen emotions. You'll feel better, trust me.}
{173}{}{Maybe you're right. I'll try. If they can make me relax, then they'd do nicely with my next bout of depression.}
{174}{}{Here, go out and enjoy your life, Harding.}
{175}{}{I was afraid to go there my entire life, let alone see a naked body! And now I'm holding my ticket to happiness... It's a strange feeling. You know, once, I thought the flagellation that society subjects itself to is the only thing leading to madness. But, you're making me rethink that theory. I'll try and change myself. No, I *will* change myself. Yes! I'll do it! Thank you.}

{176}{}{You found a solution for Harding's depression.}

#Female
{1104}{}{Thank you for the support, friend. You're an example to live by.}
{1128}{}{Well, I don't think I can help here. I'll be on my way.}
{1160}{}{Listen, I talked to Patrick about your club... }
{1161}{}{What?! How dare he?! He promised not to discuss anything behind our backs! And you... What did you talk about? He told you about us, didn't he? Did you laugh at us? Please, go away! I don't want to see any of you anymore!}
