{100}{}{You see Shelley.}
{101}{}{You see a citizen.}
{102}{}{You see a pretty woman. She might be prettier if she brushed her hair.}
{103}{}{Women! You never know what they're going to do next.}

{110}{}{Thank you so much... No matter what happened to him, I still love him.}
{111}{}{Why, why?! To find him after so long, and then...!}
{112}{}{[Her head snaps to look at you] What did you say to Colin?! Tell me!}

#Диалог
{120}{}{[She frowns] You again? If you want to waste someone's time, can't you find a beggar in the street? At least they have nothing better to do.}
{121}{}{[She hurriedly stands up] Y-you? You work for... I mean, ah, what a nice surprise... If I'd known you were coming, I'd have cleaned up! And my hair's not usually such a mess, I promise! Ha-ha... Uh, how can I help you?}
{122}{}{Good afternoon. New in town? I can tell.}
{123}{}{Good evening. New in town? I can tell.}
{124}{}{Good afternoon. So, you run around, bothering people with questions? I guess everyone needs a hobby.}
{125}{}{Good evening. So, you run around, bothering people with questions? I guess everyone needs a hobby.}
{126}{}{Bye.}

{130}{}{Who are you?}
{131}{}{How long have you lived here?}
{132}{}{Can you tell me anything interesting about the city?}
{133}{}{I'm Shelley, and this is my husband Colin. We pay our bills doing whatever we can, wherever we can. And we have nothing worth to bother us about, so don't.}
{134}{}{Oh, all my life. My husband used to live in another part of Reno, but he moved her after we married.}
{135}{}{It's a city like any other. Caravan merchants only talk about the horrible parts, but anyone can find their place here. People do actually live here, you know - it's not just constant shooting in the streets.}

{140}{}{Say, Shelley, your husband... He's not the first man in your life, is he?}
{141}{}{[Her eyes narrow] Just what are you trying to say? Colin and I are happily married! Don't you *dare* to imply I'm anything but a wife! What do you think I am, one of those whores in the street?}
{142}{}{I'm sorry, I'm not trying to offend you. But you had husband before Colin, didn't you?}
{143}{}{Woman, are you deaf, or just stupid? You had another husband, right?}
{144}{}{Oooh, touchy subject. I'll go let you cool off.}

{145}{}{We... Don't like to talk about Chris. He passed away a long time ago. Let's leave it at that.}
{146}{}{Funny, he seemed pretty alive to me.}
{147}{}{Fine. I'm going, then.}

{148}{}{You... You saw him? [she goes very pale and sits down]}
{149}{}{[Wait for her to come to her senses.]}
{150}{}{What's the matter, bitch? Your guilty conscience giving you trouble?}

{151}{}{Chris... My Chris... [she looks up at you] But - it's been ten years! What happened? Where is he?}
{152}{}{Ask Colin. He pushed your husband into the sewer and closed the lid behind him. Chris has been trapped there ever since, eating rats to survive.}
{153}{}{He's been trapped for ten years in the sewers beneath us.}
{154}{}{The sewers? You mean, all this time... [she suddenly stands up and slaps Colin across the face] You bastard! You rotten, fucking bastard! You told me he was dead! He was your friend, you - you - oh god, Chris! Chris!!! [she runs outside]}
{155}{}{Hey, wait just a - }

#Female character
{1122}{}{Good afternoon. New in town? I can tell.}
{1123}{}{Good evening. New in town? I can tell.}
{1142}{}{I'm sorry, I'm not trying to offend you. But you had husband before Colin, didn't you?}