{100}{}{You see Martin.}
{101}{}{You see a hardened old black man.}
{102}{}{No, I'm not going to shoot the breeze with you about the good weather and shit.}

#Примечание: Персонаж доступен только при игре за мужского ГГ

{110}{}{[When he notices you, his lips curl into a grin. It seems he was waiting for you.] Oh, look who it is. What's the matter? Did I hurt your precious feelings? Does it just twist you up inside to know a lowly *black* man got the better of you? Hmph... For you, jazz is just business, a way to make a quick buck off the locals. You don't understand. *I* should be in your place. ME! Jazz was my *life!*}
{111}{}{That's funny. Now, it's your time to die.}
{112}{}{You really shouldn't have done that, Martin.}

{113}{}{Ha! You hurt one hair on my head, and you're done with us, Ornette most of all. We're a *people*. You're not one of us - you'll NEVER be one of us. Think about it.}
{114}{}{I've thought it over. Fuck the band. I just want you dead.}
{115}{}{Fine, but don't get too comfortable. You never know when I'll change my mind.}

{116}{}{Oh, you're back? Just couldn't stay away, huh?}
{117}{}{As far as I know, jazz music is about happiness and love for others. It seems to me that you're the one that doesn't belong.}
{118}{}{Your pride has cost Reno's people their last chance at having actual culture. If you really care about the music, you need to step aside.}
{119}{}{What the fuck do you know about... About... Shit. Maybe I've gone too far. But I stand by my principles. You should not... You *can* not play jazz! This is our culture, not yours!}
{120}{}{What a joke! Music - ha! Jazz isn't just music, it's a culture - our culture! You couldn't ever understand.}

{121}{}{Fine, then. Take my place. They say your vocals are much better anyway.}
{122}{}{Calm down so we can talk like adults.}
{123}{}{You here to waste my time again? I'm not your minstrel, you know, I've got better things to do than entertain you.}
{124}{}{Tell me about your old band.}
{125}{}{What are you so interested for? You wouldn't get it, anyway. You organized your band for - what? Fame? Money? But we had heart. It was the "golden age" of New Reno. The city was in balance, and even people like us could go on stage and play for the good of everyone - black and white.}
{126}{}{Our main man was Big Louie. We called him that because the true Louie was short, and this guy couldn't get in the club without hitting his head against the door jamb. Heh... [he smiles nostalgically, looking into the distance] At first, only our people came to us. Then, the influential whites started to show... But not for the jazz, really. They wanted to show how "tolerant" they are. To them, we were... Zoo animals.}
{127}{}{And we were free. Money, power, politics - free of all of it. But that didn't last. Soon the "golden age" was over and the problems began. Big Louie moved to the wasteland. Me and Ornette are the only ones left... [he shakes himself free of his reverie] But don't think I told that to satisfy your curiosity! I wanted to give you a glimpse of what those times were like. But I don't expect you to understand.}
{128}{}{[Next.]}

{129}{}{What?! You mean it? I've... I've dreamed of this for a long time... [his expression hardens] But I'm just supposed to give you want you want? No way. First, I want an apology. Then, maybe I'll take your place.}
{130}{}{That's it, I'm sick of this from you. Get your goddamn head out of your ass, or there won't *be* any band! Ever!}
{131}{}{What kind of apology?}
{132}{}{I'm done. Have fun dying alone. You'll be happy to know Reno's jazz culture will die with you.}
{133}{}{Blackmail? Heh... I knew it. You just can't stand to give the black man his due.}
{134}{}{Oh, an ultimatum, is it? [his eyes alight with fire] I'll show you. I'll show all your kind what real jazz is! Now get the hell out. I need to rehearse in privacy.}
{135}{}{Fine.}

{136}{}{[He pulls his pants down and turns around] Kiss my ass, and I'll forget anything.}
{137}{}{Uh...}
{138}{}{Come on! [he shakes his ass and smirks over his shoulder] Do it! And not just a peck on the cheek - I want every square inch of my ass moist from your lips! That, and only that, will be enough!}
{139}{}{Well... In the name of art... [Do it.]}
{140}{}{Not now, not ever. Pull your pants up before I stick a chair leg in your colon.}
{141}{}{That's the last straw. The deal is off. You can wither away alone and forgotten for all I care.}
{142}{}{Oh, yes! That's enough. Consider the hatchet buried. Now... Give me time to rehearse in privacy.}
