#Guitarist
{100}{}{You see Charles.}
{101}{}{You see Charles, a black man from the ghetto.}
{102}{}{I'm on it.}

{103}{}{White. W. H. I. T. E. White.}
{104}{}{Person of color. That's an important phrase.}
{105}{}{Once upon a time, we had our own hoods. Whites never went there.}
{106}{}{My grandma wouldn't have been against what I'm doing.}

{108}{}{You know, you're one of the best whites I ever met.}
{109}{}{Good idea, but I doubt it's that easy.}

#Dialogue
{110}{}{[You see a black man in strange clothes decorated with studs and delicate patches on the collar and sleeves. He's concentrated on tuning the strings on his guitar.] You're distracting me. And when I'm distracted, I'm pissed. What do you need, whitey boy?}
{111}{}{Why'd you call me "whitey boy"?}
{112}{}{Cause you're the whitest white bastard I've ever seen! Look at your skin, it's so white like it has never seen the sun! Where are you from, a dungeon? Did you grow up in a basement? Whatever, I don't care. What do you need?}
{113}{}{I'm forming a jazz band for the Cotton Club. Wanna join?}
{114}{}{Never mind.}

{115}{}{Jazz is good. The voice of my people. [his voice goes hard] *My* people.}
{116}{}{Your people, my people - we're all the same color on the inside, aren't we? Why not break down the barriers and play jazz for everyone?}
{117}{}{You see, we have a family, everyone's helping everyone. And then you come here and try to barge into this family, acting as leader. Either you're feeding me a line, or you really don't get it. And I don't know what pisses me off more.}
{118}{}{Does it matter? We could do great things if we work together, trust me.}
{119}{}{Yeeeaaah... I can be sure about that, but not about you. I live music, I don't sell it, you get that? And, to share this passion, I need to be sure about my partner. Some things still matter in this world, now maybe more than ever. And, on top of all, you're white. Look, prove to our family that you can be trusted - and I'll go with you.}
{120}{}{By family, you mean the slums, right? I need to think about it.}

{121}{}{I've already said everything. I won't work with you until the hood has something good to say about you.}
{122}{}{Alright.}
{123}{}{Do you play on stage?}
{124}{}{I play only for our own. Well, unless you count Wright's parties, but he hasn't organized those in a while. As for playing on stage solo - I'm not sure. Wrong times.}

{125}{}{Have I done enough for the neighborhood for you to trust me?}
{126}{}{You know, you're not bad. For a whitey. Fine, count me in. But I don't want to work alone - it's dangerous in this town. There's a war going on, after all.}
{127}{}{It's a deal!}

#Женские реплики
{1108}{}{You know, you're one of the good ones.}
{1110}{}{[You see a black man in strange clothes decorated with studs and delicate patches on the collar and sleeves. He's concentrating on tuning the strings on his guitar.] You're distracting me. And when I'm distracted, I'm pissed. What do you need, whitey girl?}
{1111}{}{Why'd you call me "whitey girl"?}
{1112}{}{Cause you're the whitest white bitch I've ever seen! Look at your skin, it's so white like it has never seen the sun! Where are you from, a dungeon? Did you grow up in a basement? Whatever, I don't care. What do you need?}
{1115}{}{Jazz is good. The voice of my people. [his voice goes hard] *My* people.}
{1119}{}{Yeeeaaah... I can be sure about that, but not about you. I live music, I don't sell it, you get that? And, to share this passion, I need to be sure about my partner. Some things still matter in this world, now maybe more than ever. And, on top of all, you're white. Look, prove to our family that you can be trusted - and I'll go with you.}
{1125}{}{Have I done enough for the neighborhood for you to trust me?}
{1126}{}{You know, you're not bad. For a whitey. Fine, count me in. But I don't want to work alone - it's dangerous in this town. There's a war going on, after all.}