#Trumpetist
{100}{}{You see Ornette.}
{101}{}{You see Ornette, a dark-skinned resident of the ghetto.}
{103}{}{Nothing to talk about, to be honest.}
{104}{}{See you around, friend.}

{110}{}{[You see an aged black man with spots and blemishes on his hands. As you walk up, he looks up and carefully looks you over.] Looking for something?}
{111}{}{I'm looking for Ornette, the trumpet player. Is that you?}
{112}{}{Alas, Ornette is no longer a trumpet player. This city didn't need my trumpet or my music. Everyone's too busy trying to survive and get rich. Why are you asking, anyway?}
{113}{}{Well, me and the owner of the "Cotton Club" want to organize a few performances. A trumpet would do perfectly... }
{114}{}{[Perks up] Old stuff. I've also wanted to resurrect my band, after it fell apart. But what could I do? I sold my trumpet to Wright for three bucks. No way to get it back, since Wright will probably charge out the ass for it. And I'm no trumpeter without a trumpet.}
{115}{}{And if I get it back?}
{116}{}{Then goodbye, trumpetless trumpeteer.}
{117}{}{[He thinks silently for a long while before answering] I'm too old for big performances, but I think I can handle a few gigs.}
{118}{}{I'll take care of it then.}
{119}{}{We'll see what I can do.}

{120}{}{How's it coming along?}
{121}{}{I forgot, what happened to your instrument?}
{122}{}{Ornette, I need to know. Are there any other people who would help us?}
{123}{}{I'd like to know more about your old jazz band.}
{124}{}{I have your trumpet. Ready to come now?}
{125}{}{Ehh, not so much. Got a whole lot more things to take care of. Speaking of... }
{126}{}{As soon as I have updates, I'll be back.}
{127}{}{I sold it to Wright. I suspect he still has it.}
{128}{}{There's only two left from the old group. Charles, a guitarist, lives in the slums to the west. He's picked up a real foul temper, last I heard - finding common ground with him will be difficult. And Martin... What a voice! He was the second man in our band after Lou, but he's a huge racist and we've long cut ties. I've also heard of a homeless black man entertaining people on the streets. I've never met him, but he could be useful.}
{129}{}{It was a long time ago. Big, tight-knit collective, instruments, stage. Big Louie himself led us. But he cut ties with us just before the civil war and sold his honor to raider ideals. Without him, we fell apart. Better off that way... He thought too much of himself.}
{130}{}{[Carefully examines the instrument, wrinkled fingers tracing the smooth metal] I haven't held her for years now... I need some time to practice and remember everything. Thank you.}
{131}{}{Alright, see you around.}

#After returning the Trumpet
{140}{}{Thank you for doing this. Very honorable... For a white man.}
{141}{}{Know anyone who'll be of any use to us?}
{142}{}{I want to hear about that old jazz-band.}
{143}{}{No problem.}

{144}{}{Looks like we've got everyone. Who didn't you find?}
{145}{}{I've got one guy in mind. Charles, a guitarist, lives in the slums to the west. He's picked up a real foul temper, last I heard - finding common ground with him will be difficult.}
{146}{}{I've got one guy in mind. I've heard of a homeless black man entertaining people on the streets. I've never met him, but he could be useful.}

#After the first concerts
{147}{}{Milton said you witnessed the attack. Tell me what you know.}
{148}{}{Oh... Listen, can we talk alone? Don't want anyone else to hear. You see, I think I know who paid for the hit. It's more than likely to be Martin. It was his handwriting on that note.}
{149}{}{Who's that?}
{150}{}{We played in Big Louie's band. He left after the collective fell apart. That's why he has a bone to pick with us. And he isn't too fond of whites playing in a jazz-band.}
{151}{}{And that's enough for him to try and shut down these concerts?}
{152}{}{Oh, don't underestimate the stubbornness of an old, black man. His ambitions won't stop him from turning this place upside down.}
{153}{}{So, what do we do?}
{154}{}{Well, first of all, don't tell Milton. If he finds out, then he'll try and get rid of the old guy. Then try and talk things out with Martin yourself. I know it won't be easy. But if the old man has any problems 'cuz of you, don't expect me to talk to you.}
{155}{}{Got it. Where does he live?}
{156}{}{On the railroad, in one of the houses opposite Frank Cochran's. Good luck.}
{157}{}{Well, I'm off.}

#End of concerts
{160}{}{[Approaching the stage, you notice all the band members gathering around you to shake your hand.]}
{161}{}{I guess that means we won't be performing together again?}
{162}{}{Yes. We got word that Martin is dead. We don't know who did it, but we do know that he was jealous of this band and you specifically. And you knew too. Sorry, but the story is too suspicious... Martin, as envious as he was, was still one of us. We did well together, before you appeared. That's why we think it would be best to break up. Thanks for everything.}
{163}{}{Yeah, I did get him out of the way. Just like he tried with me. What's the difference?}
{164}{}{Well, take care, fellas! Good luck with your new band.}
{165}{}{[Ornette shakes his head as everyone looks down] Looks like whites never change. You wouldn't understand, don't worry about it.}
{166}{}{Well, goodbye. Not like I needed your shitty band. I'll take care of things on my own!}
{167}{}{Yes. That's what you agreed with Martin. Besides, sorry to be blunt, but he's much better at vocals than you. He was born for it. In part, he's right - jazz is for blacks. No discrimination, just how events turn out. Better we all go our ways. Thank you for everything. Especially for gathering us back together. We won't forget it.}
