{100}{}{You see an beggar.}
{101}{}{You see a homeless person.}
{102}{}{You see a tramp.}
{103}{}{You see the poor.}

{104}{}{You see a wasted-looking junkie.}

{105}{}{A poor man that sleeps under the open sky.}
{106}{}{A poor woman that sleeps under the open sky.}
{107}{}{You see a dirty and stinky junkie.}

#После подаяния
{110}{}{You're... You're a saint... [he sobs in joy]}
{111}{}{Thank you, thank you, thank you... [he sobs in joy]}

{112}{}{Thanks to you, I will live at least a couple more days...}
{113}{}{The shakes will come back, but you gave me a chance!}

#Применение предметов
{120}{}{This poor person is no longer hungry, at least for now.}
{121}{}{This junkie does not need another dose.}
{122}{}{This junkie needs something different.}
{123}{}{This junkie needs something different.}
{124}{}{This man needs something different.}
{125}{}{This woman needs something different.}

#Попытка заговорить с нищим
{150}{}{Please, help the homeless!}
{151}{}{Help us, please!}
{152}{}{Give us food! I haven't eaten in two days!}
{153}{}{Any spare change?}
{154}{}{Can I borrow some money until I get paid?}
{155}{}{I'm starving... Do you have anything?}
{156}{}{Excuse me, can you spare some change?}
{157}{}{Please, give me something to buy a piece of bread!}
{158}{}{You'd help a blind man, wouldn't you?}
{159}{}{}

#Попытка заговорить с наркоманом
{170}{}{Please... I need a fix...}
{171}{}{I feel so bad...}
{172}{}{What time is it? It doesn't matter...}
{173}{}{Am I dying?}
{174}{}{Oh, my head...}
{175}{}{Oh, my liver...}
{176}{}{Everything aches...}
{177}{}{[Stares at nothing]}
{178}{}{You! Stop spinning the sky!}
{179}{}{Hey, why so loud?}
{180}{}{Look how big my foot is. I could squash a midget with it.}
{181}{}{How did I end up in the forest?}
{182}{}{Everything is so sweet... Why is it sweet?}
{183}{}{Do you want to see me fly?}

#Произвольные плавающие фразы (авторы Kerb и BlackDesigner)
{200}{}{It would have been better if I died in the womb...}
{201}{}{How did I end up like this?}
{202}{}{I feel terrible...}
{203}{}{I'm so hungry I'd eat a boot.}
{204}{}{Oh...}
{205}{}{:: sigh ::}
{206}{}{Reno... Reno...}
{207}{}{I'm going to die today.}
{208}{}{I was a respectable man once...}
{209}{}{Wait... Ah, no, nothing.}
{210}{}{[Adjusts torn clothes]}

{211}{}{At least poverty is honest, right? [sobs]}
{212}{}{Why should I fear dying? I'm already in hell...}
{213}{}{Life is not all black and white... It's all black, that's it.}
{214}{}{How many times can one drink his piss?}
{215}{}{If only I could find a cat... Mmm, delicious...}
{216}{}{I used to catch pigeons before the war... Where have they gone?}
{217}{}{At least every day is a day off...}
{218}{}{Wait, wait, wait...}