{100}{}{You see a street urchin.}
{101}{}{You see a street kid dressed in rags. It seems he intends to talk to you.}
{102}{}{Good day.}

{110}{}{Mister, wait! Hear me out!}
{111}{}{Sure, what do you want?}
{112}{}{Go away, I'm not a charity.}

{113}{}{No, I don't want anything! A man sent me to talk to you! I didn't see his face, but he said he wanted to meet you at the Silver Legacy hotel!}
{114}{}{A secret meeting at the hotel... How intriguing. Where can I find him?}
{115}{}{I've got a bad feeling about this. If you want to set me up, I'll find you and pull your guts out of your ass, got it?}
{116}{}{He said he'll be at the Silver Legacy hotel, middle room on the second floor. He said you should come alone.}
{117}{}{Thanks, kid. Here's two bucks. Get yourself something to eat.}
{118}{}{Thanks, kid. You're free to go.}
{119}{}{Maybe I'll show up and maybe I won't. Now - scram! I'm busy.}

#Female version
{1110}{}{Miss, wait! Hear me out!}
{1113}{}{No, I don't want anything! A man sent me to talk to you! I didn't see his face, but he said he wanted to meet you at the Silver Legacy hotel!}
{1116}{}{He said he'll be at the Silver Legacy hotel, middle room on the second floor. He said you should come alone.}
{1118}{}{Thanks, kid. You're free to go.}