{100}{}{You see a shifty looking guy.}
{101}{}{You see... A killer!}
{102}{}{You see a suspicious guy with a familiar tattoo on his neck.}
{103}{}{You see a killer that really wants to shoot you.}
{104}{}{I'll see you in hell, bitch!!!}
{105}{}{Big Louie sends his regards! Eat the lead, bitch!!!}

{110}{}{You played with the wrong motherfuckers, bitch! Now, it's game over!}
{111}{}{Hey, what's this about?!}
{112}{}{Don't play innocent with me, bitch! I saw you kill my boys in Lovelock! Without the gang, I'm nobody! No one will take me with this tattoo on my neck! My life's over - but I'm taking you with me! [he points his gun, crooked teeth bared in an animal snarl]}
{113}{}{Wait, we can talk about this!}
{114}{}{I guess I missed one. Let's finish this, then.}

{115}{}{You got something to say, bitch?!}
{116}{}{Actually, never mind. It'll be easier just to kill you.}

{117}{}{You don't really think you can beat me, do you?}
{118}{}{Goddamn right I do, bitch! Your luck just ran out!}
{119}{}{Just hear me out!}

{120}{}{Uh... Well... Oh, shit, what was I thinking? You're a goddamn killing machine! Fuck this - let's just forget the whole thing. I want to live!}
{121}{}{Oh, that's not going to happen. I just wanted you to die knowing how stupid you were.}
{122}{}{Good. Let's just go our separate ways.}

{123}{}{All of your buddies are dead, but fate spared you. Isn't this a sign from above?}
{124}{}{Bitch, the only one fate's coming for today is YOU!}
{125}{}{[He hesitates] Uh... What do you mean?}
{126}{}{This is your chance for a fresh start. Do you really want to start your new life with another murder?}
{127}{}{That's... That's bullshit! I even believed you for a second, but no, you're just a bitch begging for mercy. But... Maybe, if they're dead, and I'm alive... Maybe that is a sign. Like, that they were just holding me back. Yeah... And you, bitch, always remember this as *your* sign from fate. Remember the day *I* let *you* live. You better pray we never meet again.}

{128}{}{Even if you do kill me, my bosses in Reno won't rest until they find you.}
{129}{}{HA-HA-HA! You think I'm that stupid, bitch? How do you think I even found you? I asked around - and none of the leaders in Reno want anything to do with you! Goddamn, you've just pissed me off even MORE!}
{130}{}{...Oh fuck. Uh, let's just forget this happened, yeah? No harm done?}

{131}{}{People only know of that tattoo in Reno. People won't recognize it if you go to another city.}
{132}{}{HA! That's the best you've got, bitch? Too bad! It's time to air out the empty head of yours!}
{133}{}{Uh... [he lowers the gun and looks at you cautiously] You know... You *did* take out the rest of our gang... Maybe I should cut my losses. Fuck it! I'm out of here!}
{134}{}{I'll pay you $1000 for the inconvenience.}
{135}{}{Don't try to fool me, bitch! You got nothing! I can smell money like a rat smells meat!}
{136}{}{Hmm... Maybe that's a better deal than risking my life. Okay, throw me the money and I'll consider it even.}
{137}{}{Here's the money. Take it, and we'll go our separate ways.}

{138}{}{You gain experience for solving the problem without violence.}

#Женские реплики
{1110}{}{You played with the wrong motherfuckers, bitch! Now, it's game over!}
{1112}{}{Don't play innocent with me, bitch! I saw you kill my boys in Lovelock! Without the gang, I'm nobody! No one will take me with this tattoo on my neck! My life's over - but I'm taking you with me! [he points his gun, crooked teeth bared in an animal snarl]}
{1121}{}{Oh, that's not going to happen. I just wanted you to die knowing how stupid you were.}
{1133}{}{Uh... [he lowers the gun and looks at you cautiously] You know...you *did* take out the rest of our gang... Maybe I should cut my losses. Fuck it! I'm out of here!}


