{100}{}{You see Machete.}
{101}{}{You see a powerful-looking bodyguard. Just one look at him makes you want to bury your head in the sand.}

#Îñíîâíàÿ ÷àñòü äèàëîãà è ïðîïóñê ê áîññó
{105}{}{Boss is dead! It's all over!}

{110}{}{Hold it! You're standing in the house of Mr. Luciano. What do you want with the boss?}
{111}{}{I need to talk to him.}
{112}{}{[He nods in greeting] Boss is waiting for you.}
{113}{}{Nothing, actually, I'm here for something else.}

{114}{}{About what?}
{115}{}{I'm looking for work.}
{116}{}{Uh, nothing. I just want to chat.}
{117}{}{[He waves his hand dismissively] Boss doesn't handle those little details. We have an administrator for that.}
{118}{}{Mr. Chase said I could find *serious* work here.}
{119}{}{Wait here. [he knocks, steps into another room, and returns after a moment] Boss is ready for you. Be quiet and courteous. Mr. Luciano deserves respect, you get that?}
{120}{}{Johnny Chase? That changes things. }
{121}{}{I don't handle "little details" either. I'm here for... *serious* work.}
{122}{}{Oh, is that so? [he crosses his arms and looks you up and down] You *look* serious... Maybe you're the real deal.}
{123}{}{I talked to her. She said I could get some *serious* work.}
{124}{}{That's all I wanted to know. Bye.}
{125}{}{Okay.}

#Ñòóêà÷
{126}{}{Do you know you have a spy hanging around?}
{127}{}{Oh yeah? Who?}
{128}{}{A man outside named Canary. He responds to the code phrase "The gilding has gone from our age."}
{129}{}{Uh, no one, I'm just making sure you're paying attention. Good work!}
{130}{}{We checked it out, and you were right. Boss said to give you this. }
{131}{}{Thanks for the cash.}
{132}{}{That's not all. Boss wants to talk to you. Go on in.}
{133}{}{Great.}

{134}{}{I have a message from Mr. Wright.}
{135}{}{I almost believed that you were with us... }
{136}{}{Boss is waiting. Go on in.}
{137}{}{Great.}

#Ðàá èç Óðàí-Ñèòè
{138}{}{It'll cost you 1000 dollars. Of course, unless you have a special deal with Mr. Luciano.}
{139}{}{Hey, this is a good slave you're talking about! He works hard, knows his place, and the cattle listens to him. Slaves like this are hard to find.}
{140}{}{I want to purchase a specific slave: Joseph from Uranium City.}
{141}{}{We paid 250 dollars for this slave. Unless you have a deal with Mr. Luciano, why would we sell him?}
{142}{}{I'll double the price.}
{143}{}{Hmm. Okay. 500 dollars and he's all yours.}
{144}{}{Here, take the money.}
{145}{}{I'll think about it.}
{146}{}{It's done. I'll radio the guards and tell them you'll be picking up your goods from the paddock.}
{147}{}{Okay.}

{148}{}{You have a slave from Uranium City. I want to buy him.}
{149}{}{You have a slave from the Cheyenne tribe. I want to buy him.}

#Ïðî èìÿ Ìà÷åòå è åãî îðóæèå
{150}{}{I'm afraid to ask, but who are you?}
{151}{}{My name is Machete Rodriguez. Remember it. I'm Boss's personal bodyguard and head of security at the ranch.}
{152}{}{You have a strange name... Machete.}
{153}{}{You're not too bright, are you? It's a nickname. Guess how I got it.}
{154}{}{It's a nickname. Want to know how I got it?}
{155}{}{Well, nice to meet you... }
{156}{}{Well, you don't have a machete, so... }
{157}{}{Hmm... Name, too?}
{158}{}{No. My parents called me that. They came to Reno after the bombs.}
{159}{}{Never mind.}
{160}{}{Where did they live before that?}
{161}{}{Mexico. It's far to the south. They say everyone was starving there, so everyone went north. Everyone who could.}
{162}{}{Back to your name. I still don't understand... }
{163}{}{[He scowls] Not anymore. I lost her fighting the dogs at the railway station south of Reno. I looked everywhere, but I couldn't find her! She was the best weapon I ever owned!}
{164}{}{Maybe I can help with search?}
{165}{}{I'm guessing you have a weapon to go with your name?}
{166}{}{Hey, you find her, you'll be my new best friend! I'll pay to have her back in my hands. But after that storm blew through a while back, she's gotta be under the sand by now.}
{167}{}{I'll bring your machete back to you. Wait here.}
{168}{}{I found your machete! It's pretty rusty, but it still seems fit for use.}
{169}{}{I found your machete! I even refinished it for you.}
{170}{}{You found her! I can't believe it! I promised to pay, and I always keep my word. Thank you.}
{171}{}{It wasn't hard.}
{172}{}{Yeah? She doesn't give out many recommendations. }

#Î ìåñòíîñòè
{180}{}{What is this place?}
{181}{}{[He narrows his eyes suspiciously] This is Oliver Luciano's ranch, the greatest businessman in Reno. You should show respect. This is the office. The ranch is behind the building.}
{182}{}{Is one ranch really such a big deal?}

{183}{}{Fifty slaves, two dozen guards, tons of living brahmin meat - yeah, it's huge.}
{184}{}{Slaves?}
{185}{}{You mentioned brahmin meat. Can I get some?}
{186}{}{Sounds impressive. Can I take a look?}
{187}{}{}
{188}{}{Don't you think it's wrong to imprison people and force them to work?}
{189}{}{}
{190}{}{Did I stutter? Yes, slaves.}
{191}{}{I don't handle that. Talk to the administrator. Her office is the building to the west out back.}
{192}{}{No. [he crosses his arms] Only workers and friends of Mr. Luciano get to walk around the ranch.}
{193}{}{}
{194}{}{[He raises an eyebrow in surprise, then throws his head back and laughs] You're funny! These slaves aren't people like you and me. They're *lucky* Boss gives them food and safety for their work! He took them from slums and villages where they couldn't control their own lives anyway. To them, Boss is a *god*! And why not? If not for him, they'd already be dead.}
{195}{}{So they're not abused here?}
{196}{}{[He gives you a funny look] Were you raised in a vault, or something? I told you, they're not fit to run their own lives, so we have to show them who's boss or they might get *stupid* ideas. Sometimes we need to remind them.}
{197}{}{Can I ask you again about the ranch?}

{200}{}{Do you need any more slave collars?}
{201}{}{You have collars? That's good! We always need more. I'll pay 100 dollars for every one you bring me.}
{202}{}{Then I have collars for sale.}
{203}{}{I think I'll hold on to my collars for now.}
{204}{}{How many you have?}
{205}{}{[One collar]}
{206}{}{[Two collars]}
{207}{}{[Three collars]}
{208}{}{[Five collars]}
{209}{}{[Everything: }
{210}{}{]}
{211}{}{[He takes the collars and gives you $100 for each] Good deal. If you find any more, I'll pay.}
{212}{}{Good.}

#Êâåñò Îëèâåðà ïî äèâåðñèè â êàçèíî
{220}{}{Mr. Luciano said I should discuss the casino job with you.}
{221}{}{[He looks around, then leans in, speaking quietly] Boss chose you? I was hoping for some more... Rough. I've been planning this a long time, I want someone who knows the business.}
{222}{}{Whether you trust me or not, Mr. Luciano chose me, so let's get started.}

{223}{}{Okay, we've got two choices of diversions. Do both if you can. First, slip the El Dorado visitors some poisoned beer, so they'll be unhappy with the casino. That'll get Ricardo's attention. Where you get the poison is up to you.}
{224}{}{What's the second choice?}
{225}{}{You saw the El Dorado security uses Tommy guns, right? Bertolini bought every one he could find ten years ago. Whenever someone sees a Tommy gun, they think El Dorado.}
{226}{}{I understand. Keep going.}
{227}{}{You have to get your hands on a Tommy gun and attack some civilians. You don't have to kill anyone, just make sure everyone knows it was an attack. Hit someone like a hooker or a slum dweller. People will think the El Dorado workers are roughing people up. Ricardo will *have* to investigate.}
{228}{}{Gee, that's all? You don't have any other pointless complications to throw in there? Alright, I'd better get to work. Have fun sitting on your ass doing nothing.}
{229}{}{I've got it. Time to get down to business.}

{230}{}{I need to discuss the casino job.}
{231}{}{What, more questions?}
{232}{}{Explain the plan again.}
{233}{}{Forget it, I'll figure it out myself.}

{234}{}{You want people to see me shooting civilians with a Tommy gun, but if they see my face, won't they know I'm not working for the casino? They might even trace it back to you.}
{235}{}{Hmm, good point. Okay, I got this. [he hands you a balaclava] You can hide your face. Just make sure you're not wearing anything people will recognize.}
{236}{}{Fine.}

#Âçëîì ñåéôà ó Áåðòîëèíè
{237}{}{Do you know anyone who can help with safe-cracking?}
{238}{}{I know a guy downtown called Basketball Buddy. He used to pick locks, until he got the stuffing beat out of him, heh heh. But he probably won't help with Bertolini's safe. You need someone with real skills, and there's not many people like that in the city.}
{239}{}{Thanks.}

#Êâåñò Îëèâåðà ïî äèâåðñèè ó ãàíãñòåðîâ
{240}{}{Mr. Luciano wants me to discuss the job with you.}
{241}{}{Let's discuss Mr. Luciano's job again.}
{242}{}{You need my help, don't you? Just admit it. And yes, I have a plan.}
{243}{}{Tell me. I really need your... Help.}
{244}{}{I'll figure it out myself. I don't want you getting a big head.}
{245}{}{[He becomes serious] We already talked about this. I can't help with a short memory.}
{246}{}{[He becomes serious] Hmm. You got the last job done. Okay, maybe you can handle this.}
{247}{}{[Next]}
{248}{}{We need to get Thompson and Stryker angry enough to start a war between them.}
#Old version:
#Òåïåðü êàê ýòî ñäåëàòü. ß ïðåäëàãàþ äèâåðñèþ ñî âçðûâ÷àòêîé. Çàìèíèðóé ïàðàäíûå äâåðè â îáåèõ øòàáàõ.
#Åñëè íå ñìîæåøü ýòî ñäåëàòü, òîãäà åñòü åùå âàðèàíò ñ çàæèãàòåëüíûìè ãðàíàòàìè -
#çàêèäàé èìè îõðàííèêîâ è òóò æå óáåãàé, ïîêà òåáÿ íå çàñåêëè.
#È òî, è äðóãîå ñîçäàñò ìíîãî øóìà, à äàëüøå íà÷íóòñÿ ðàçáîðêè, êòî íà êîãî çàðûïàåòñÿ.
#Ýòî ïîçâîëèò âûèãðàòü âðåìÿ.
{249}{}{You want the best way, wire explosives to the front door of both headquarters. That'll make some noise. If you can't do that, kill someone at each headquarters without them knowing it was you. They'll blame each other and it'll give us more time.}
{250}{}{What if they recognize me?}
{251}{}{Where can I get incendiary grenades?}
{252}{}{Where can I get explosives?}
{253}{}{That's enough. I will take it from here.}
{254}{}{Finally, I'm getting some use out of you. Now I'm off to do all the work. Again.}
{255}{}{Hey, I didn't give you that face mask for party tricks, you know. Use your head, rookie!}
{256}{}{If you can't do it yourself, find someone who will do it. That's your problem, not mine.}
{257}{}{That's your problem, not mine. Start with the mechanic at the station.}
{258}{}{Take this. [he hands you a balaclava] Put it on before you do the job, and they won't see your face.}

#Êâåñò Îëèâåðà íà ñäåëêó ñ êàðàâàíùèêàìè
{260}{}{Mr. Luciano wants me to take care of some deals. He said I should talk to you.}
{261}{}{You? Huh, Boss must see something in you. Okay, but remember, this is *delicate*.}
{262}{}{How delicate?}
{263}{}{Ugh, don't tell me I have to wear a tie!}
{264}{}{Thanks to the bugs you put in Bertolini's room, we learned about a secret deal outside of Reno. Ricardo wants to get weapons. Right now, he just wants to protect himself during the fighting, but he'll come for us sooner or later.}
{265}{}{So that's what he had that money full of suitcase for... }
{266}{}{Yeah, and that's what we'll use it for. You'll pretend to be from the casino and complete the deal. Boss wants to keep friendly the caravan for the future... If we can. But the most important thing is to get the weapons. The better you do, the better *everyone* will do, you get it?}
{267}{}{Got it.}
{268}{}{Trust me, anything you "get", I'll get.}
{269}{}{Deal's taking place at night outside Reno. When you're ready, talk to me.}
{270}{}{I'm ready now.}
{271}{}{Well, I'll come back when I'm ready.}

{272}{}{Well, how are the weapons?}
{273}{}{There's less than we thought there'd be. Bertolini must be a lousy barterer, heh-heh! Anyway, we got enough weapons to fight off an attack. Boss is happy. He doesn't act like it... Ever... But I can tell.}
{274}{}{That's a lot of weapons for one ranch, isn't it?}
{275}{}{Boss doesn't want to rely on anyone. These weapons are just one part of that. Anyway, it's not just for the ranch, but convoys too. We have a lot of things to protect, not just here.}
{276}{}{I see. Well, I'll be going.}

#Æåíñêàÿ ðåïëèêà
{1113}{}{Nothing, actually, I'm here for something else.}
{1118}{}{Mr. Chase said I could find *serious* work here.}
{1130}{}{We checked it out, and you were right. Boss said to give you this. }
{1153}{}{You're not too bright, huh? It's a nickname. Guess how I got it.}
{1181}{}{[He narrows his eyes suspiciously] This is ranch of Oliver Luciano, the greatest businessman in Reno. You should show respect. This is the office. The ranch is behind the building.}
{1225}{}{You saw the El Dorado security uses Tommy guns, right? Bertolini bought every one he could find ten years ago. Whenever someone sees a Tommy gun, they think El Dorado.}
{1258}{}{Take this. [he hands you a balaclava] Put it on before you do the job, and they won't see your face.}
{1264}{}{Thanks to the bugs you put in Bertolini's room, we learned about a secret deal outside of Reno. Ricardo wants to get weapons. Right now, he just wants to protect himself during the fighting, but he'll come for us sooner or later.}
{1269}{}{Deal's taking place at night outside Reno. When you're ready, talk to me.}
{1270}{}{I'm ready now.}
