{100}{}{You see a sick resident.}
{101}{}{You see a slum dweller. His eyes are sunken, his body is thin and bony, and his face looks mired in depression.}
{102}{}{You earn experience for giving the correct diagnosis.}

#До определения болезни
{110}{}{[He barely even looks up] ...you want something?}
{111}{}{You look unhealthy. What's wrong with you?}
{112}{}{No, nothing.}

{113}{}{Your guess is as good as mine. Sometimes I get a pounding headache for no reason, even at night. I get tired easily, but I can't sleep, and sometimes I get the weirdest feeling that I'm at looking at myself from *outside* myself.}
{114}{}{Have you ever seen a doctor?}
{115}{}{That sounds awful. I'll stop talking about it.}
{116}{}{Huh. Well, I can't help you. Bye.}

#Определение болезни
{117}{}{Doctor? Ha! Welcome to Reno... The only city without a real doctor, I think. Sometimes Patrick helps sick people, but he's never heard of anything like this. I'm just trying to do as much as I can for my family with the time I have left.}
{118}{}{I have some medical experience. Let me examine you.}
{119}{}{I won't waste any more of your time, then.}
{120}{}{[You examine the patient, but you have no idea what's wrong with him.]}
{121}{}{I can't do anything else here. I'll have to leave you for now.}

{122}{}{[After a series of questions, you realize the patient is suffering from an incurable brain tumor] So what do you say, Doc? How much I have - a month, a year?}
{123}{}{Not long. The only way to save your life is to remove parts of your brain, but you'd be left with the intelligence of a brahmin. I'm sorry.}
{124}{}{I'll give it to you straight. You have a couple more months left before your terminal symptoms begin. Your brain will turn to slush, and you'll suffer hallucinations and loss of vision. Then comes impotence, refusal of food, and exhaustion... Leading to death.}

{125}{}{I see. Somehow, I knew I was close to the end. Thanks for making it clear to me, Doc.}
{126}{}{Take care.}

{127}{}{Oh my god! I didn't think it would be so bad! I thought I'd just go to sleep one night and not wake up... What am I going to do? Once I'm not able to walk to the toilet, I should just kill myself. Or ask someone else..}
{128}{}{Well, that's your decision, not mine.}

{130}{}{You couldn't have lived this long without medication. Where do you get it?}
{131}{}{It doesn't matter. I can get what I need. Why do you care?}
{132}{}{Because I bet your dealer is making a lot of money off of your condition, and you might not be getting what you need.}
{133}{}{Fine.}

{134}{}{Heh... It's not like I think he's doing it out of the goodness of his heart. What does it matter, anyway, as long as my pain goes away? His name's Solomon. He deals out back of the El Dorado. You be careful if you're going to talk to him. He's twitchy... And dangerous.}
{135}{}{I'll be careful.}

{136}{}{How can there be no doctor in such a big city?}
{137}{}{Don't get me wrong, there were plenty ten years ago. But after the civil war started, they were all recruited by one side or another, sometimes by force. They've all died in the tug-of-war since then. There was an Auto-Doc below the City Hall, but with so many people using it, it didn't last long. Now, the only medicine we get is from chem dealers, and they're killing us as much as they're helping us. I think the caravans import more chems than anything else.}

#Female character
{1119}{}{I won't waste any more of your time, then.}