{100}{}{You see Essie Gate.}
{101}{}{You see a woman with sad, far-away look in her eyes.}
{102}{}{Thank you! Thank you for everything!}
{103}{}{Thank you for your efforts, but we still have to go.}

#Первый разговор и 'иповые фразы
{110}{}{[The woman looks up quickly when you enter the room, but when she sees you, only gives you a look of empty disappointment] Oh... If you're selling something, we're not buying. Or joining.}
{111}{}{No, I just wanted to ask a local a few questions.}
{112}{}{Then you and I have nothing to talk about. [Leave]}

{113}{}{Oh, you're not local? Sorry for my poor welcome, but you don't meet friendly strangers very often in Reno. What do you want?}
{114}{}{Yes?}
{115}{}{Who are you?}
{116}{}{Can you tell me about the city?}
{117}{}{Sorry, we'll talk some other time.}
{118}{}{Let's talk about something else.}
{119}{}{}

{120}{}{Essie Gate. I'm just a housewife... So don't get any ideas.}
{121}{}{What's there to tell? Walk around Reno and see everything you need to know. There's not much worth, and what little there is, everyone's already fighting over. But it's still better than the rest of Nevada, so what choice do we have?}
{122}{}{}
{123}{}{}
{124}{}{What's the story with your husband, again?}
{125}{}{About the situation with your husband... }
{126}{}{I'm new here. Can you tell me how to get settled in this town?}
{127}{}{I have a note from a certain Robert that lived here. Do these mean anything to you?}
{128}{}{}
{129}{}{}

#До получения квес'а
{130}{}{I'm new here. Can you tell me how to get settled in this town?}
{131}{}{I can't help you. But... If you don't mind... Oh, never mind. I have nothing to pay you anyway.}
{132}{}{Can't pay? Well, then we have nothing to talk about.}
{133}{}{If you have nothing to pay, then pay me nothing. Tell me what you need.}
{134}{}{Just spit it and *I'll* decide whether I want to do it, okay?}
{135}{}{[The woman sighs heavily, closing her eyes] I overheard Robert talking to Mark about going to some military base. I can only guess what happened to him. I didn't want to let him go, but how could I stop him? Mr. Wright gave the order himself!}
{136}{}{Okay, wait, wait, wait, now slow down and tell me exactly what happened!}

{137}{}{Oh, sorry... }
{138}{}{Who's Robert?}
{139}{}{Who's Mark?}
{140}{}{Who is this Mr. Wright?}
{141}{}{What kind of order?}
{142}{}{What kind of military base?}
{143}{}{Do you think something happened to Robert?}
{144}{}{That's all I need.}

{145}{}{Robert is my husband. He's a... A prospector, is what they call them. He looks for useful pre-war things in old ruins, then sells them to merchants.}
{146}{}{He was my husband's partner. A prospector, like Robert, just less experienced.}
{147}{}{Be happy you don't know who Mr. Wright is. He's one of Reno's business leaders. He owns these slums, meaning he owns us.}
{148}{}{I don't know. Mr. Wright needed something from the military base, but no one's ever gotten in. He hired Robert and his partner to be the first.}
{149}{}{Hawthorne, I think it's called. I don't know much about it, but they say no one's been inside since the War. Robert knew more.}
{150}{}{Robert always sent us messages while he was out in the wasteland. But we... We haven't heard anything in a long time... }

{151}{}{So you will help us to find Robert?}
{152}{}{First I need more information.}
{153}{}{Oh, of course... }
{154}{}{I'll be glad to help you.}
{155}{}{No, I don't have time to do it. [Leave]}
{156}{}{Oh, thank you! Robert left these coordinates behind. I don't know what they mean, but I'm sure you'll understand. Please, be careful..}
{157}{}{Okay. Let's see what's what.}

{158}{}{[Her eyes momentarily light up with hope, but it immediately disappears] Yes?}
{159}{}{I need more information.}

#Лис'овка о' мужа из Хо'орна
{160}{}{What?! What is this?! Show me, now!}
{161}{}{Not so fast, woman. This delivery is worth money... }
{162}{}{Of course. Take it.}
{163}{}{Uh, shoot, I left it somewhere. I'll be right back.}

{164}{}{[She snaps up her last stash of money and shakes out }
{165}{}{ dollars] Here! It's all we have. Now give me that note!}
{166}{}{Is that all?! Hell, I risked my own life! Give me that picture, that pile of books and a fresh sandwich from the table, and *then* I'll give you the note.}
{167}{}{Sure.}
{168}{}{[He lowers her head, looking at you] I'll pay it. Every last crust of bread we have! Just give me the note!}
{169}{}{[She silently reads the text, then wearily closes her eyes] I knew it... I knew it would end like this... }
{170}{}{What?}
{171}{}{I don't really care... }
{172}{}{[She doesn't seem to hear you] Sooner or later it had to happen. Robert was good, but a military base? No, it was too dangerous... Too, too dangerous... }
{173}{}{You can say that again.}
{174}{}{But wait, where's Mark?!}
{175}{}{Who?}
{176}{}{Robert's partner! He should know what happened there... If he's still alive.}
{177}{}{There was no second body. But why do you need him?}
{178}{}{Listen... It's complicated. Our family lived off their work. They paid the rent and electricity by prospecting for Mr. Wright. Without them, our debts... We'll be lucky if he don't sell us into slavery. If Mark is alive, he could finish the job.}
{179}{}{What cruel laws you have here... }

{180}{}{Oh, yes. Mr. Wright is a heartless man. But you can't blame him. We are really in debt to him.}
{181}{}{What if I talk to Wright?}
{182}{}{Maybe Mark's family knows something?}
{183}{}{I'll try to find Mark and solve the situation.}
{184}{}{I've fulfilled my part of the deal. This isn't my concern.}

{185}{}{To Mr. Wright? He's not someone you can just... "talk" to. If you are going to step into his house, I can only give you this advice: choose your words carefully.}
{186}{}{Maybe, but they won't talk to us. They got so angry... I don't know why.}
{187}{}{Oh, thank you. Please, bring us news soon.}
{188}{}{Bye.}
{189}{}{Yes, we understand... }
{190}{}{Bye.}

#Завершение квес'а
{200}{}{About Mark.}
{201}{}{You learned something?}
{202}{}{Mark left the city and ran north somewhere. I don't think you'll ever see him again.}
{203}{}{No, not yet.}
{204}{}{So he cut and run? He could have at least told us what happened to Robert! That bastard! That... No, I can't think about that now. We have to leave. If no one completes that contract, then Mr. Wright will come for us. And you... Thank you for trying to help us.}
{205}{}{We'll see. Maybe there's still hope... }
{206}{}{Is that all? Hell, not even fed after the road... }
{207}{}{Mark fled the city, but I talked him into coming back. That's not going to solve your problem, though... }
{208}{}{}
{209}{}{}

{210}{}{You won't have to worry about your debts anymore. Wright is dead.}
{211}{}{I have good news. Someone fulfilled your husband's contract, so Wright's called off your debt.}
{212}{}{Oh my God! You think *this* is a solution?! What will happen to the slums now?! His sons will fight each other for them - and kill us all in the crossfire! We have to leave. At least, thank you for warning us. It gives us time to figure something out.}
{213}{}{You're welcome.}
{214}{}{What?! But how? ...it was you, wasn't it? Thank you, thank you! No one else would have done this for us! Wait... In Reno, everything has a price. If you don't know that yet - learn. [she holds out some sort of round device with wires sticking out of it] Robert wanted to improve his metal detector with this. We don't need it anymore, but maybe you can find a use for it. Again, thank you for everything! You've saved our lives!}
{215}{}{Take care.}

#Female character
{1166}{}{Is that all?! Hell, I risked my own life! Give me that picture, that pile of books and a fresh sandwich from the table, and *then* I'll give you the note.}
