{100}{}{You see Mrs. Clover.}
{101}{}{You see Mrs. Clover. She's not quite elderly, but is beginning to "dry".}

#First talk
{110}{}{You! Again!? Leave me alone! I gave you all I've had! If you come again, why - I might just show you what this old lady can do!}
{111}{}{I think you got me confused with someone.}
{112}{}{Shut it, hag! I don't give a shit about your problems.}

{113}{}{Oh... Sorry! I thought you were from the casino. Those bouncers have such cold hearts that they aren't afraid of putting some force on someone like me!}
{114}{}{The bouncers? What's going on?}
{115}{}{What happened?}
{116}{}{I'm not interested. I think I'll go now.}

{117}{}{You... I thought it was the bouncers again.}
{118}{}{I'm so glad to see a friendly face...}

#Receiving quest
{119}{}{Misfortune struck me. My husband passed away, and then it turned out he had debts to the casino. Now I'll either be evicted or sold into slavery.}
{120}{}{Sorry, but who are you?}
{121}{}{If they're your husband's debts, why are you being punished?}
{122}{}{How did your husband die?}
{123}{}{How much does your husband owe?}
{124}{}{And nobody came to your defense?}
{125}{}{I'd like to help you with that debt.}
{126}{}{This is none of my business. I think I'll be going now.}

{127}{}{Tell me what happened again.}
{128}{}{That's nice, I need to go now.}
{129}{}{Goodbye.}

{130}{}{Mrs. Clover, if you want to know. I work at a kitchen in a local restaurant.}
{131}{}{The bouncers don't care. They just want their money. With my husband dead, they settle on getting it from me. Such are the injustices of this world.}
{132}{}{Street kids jumped him when he was drunk. Must've been easy prey for them.}
{133}{}{I have a thousand left to pay. Even if I didn't need to pay rent, it would take a few weeks to earn that much. And with the way things are going, I doubt I'll have that long.}
{134}{}{While I'm here, Mr. Wright won't let anything happen to me. I'm one of his most reliable tenants. But I doubt this will be able to go on any longer. He won't go against the casinos just for my rent. He'll just evict me and give this room to somebody else. And as soon as that happens... I'm easy prey for the bouncers. I think they'll sell me into slavery.}
{135}{}{You want to help? That's wonderful! But I have nothing to repay you with.}
{136}{}{Single time payouts aren't the best prospect in Reno. I hope my help will be a long-term investment.}
{137}{}{Then why am I wasting me time here? I'm leaving.}
{138}{}{I need to know more about the problem before we continue.}
{139}{}{Got it. Well, enough of this sad talk - I need to go now.}
{140}{}{Thank you for your honesty, I didn't expect any more. But listen - my house belongs to Mister Wright and I work for the Silver Legacy hotel. Perhaps helping me will improve your reputation in this area. All that's left for me is to hope for your help. Talk to the administrator in El Dorado - he has all the ledgers.}
{141}{}{I'll see the administrator.}

#Handing in the quest
{150}{}{Glad to see you.}
{151}{}{Here's the administrator's ledger. You owe them nothing now.}
{152}{}{Goodbye.}
{153}{}{You did it!? Incredible! I don't know how to thank you. Just know that this won't be left unnoticed by the other residents of these slums. Thank you. Here, take this at least. Something to eat before the road. Special recipe, nobody else makes it!}
{154}{}{Thank you and goodbye.}
{155}{}{Speaking of, your husband was quite a good player. How did someone like him lose that much money?}
{156}{}{I can tell you, can't I? Those cunning bastards at the casino cheat with weighted dice. The house always wins, right? He knew, but continued testing his luck. He thought he could beat their system and get lucky... [she sighs] He didn't.}
{157}{}{Yeah, the gambling is like that. Well, see you, Mrs. Clover.}

#Questions about other quests
{160}{}{I'm looking for workers from Uranium City. Do you know anything about that?}
{161}{}{Yes, of course. Talk like that spreads quickly around here. Carl is a neighbour of mine. Michael got tossed out into the streets by Wright's men and Joseph was sold into slavery. Seeing a man of such high status suddenly reduced to nothing... It was terrifying.}
{162}{}{Did you hear anything about Ted Bundy?}
{163}{}{No. Who is he? If he lived here before I moved in, my neighbours might know. They were here for much longer than me.}
{164}{}{What can you tell me about Harding?}
{165}{}{Quiet fella. A little slow, I think. That's why he's always tossed around. From one angle, it's sad. But from the other, it's his own fault that he can't find his own place in society. If you want to know what I think - he didn't get enough human attention in his life. Especially from girls. [she winks] You know what I'm talking about.}
{166}{}{What do you know about the missing prospectors? Mark and Gate.}
{167}{}{I heard about that. Both of them, just gone. Not surprising, considering their job isn't the safest - walking around ruins with those things. I remember Mark returned though, caught a glimpse of him through the window late in the evening. I have no idea what happened though.}
{168}{}{Another question.}
{169}{}{That's all I wanted to know.}

#??????? ???????
{1136}{}{Did I say anything about pay? I want to deal with this situation because it isn't fair!}
