{100}{}{You see Colin.}
{101}{}{You see a citizen. You get the feeling his mother never taught him proper manners.}
{102}{}{Most people don't consider the ability to piss everyone off a talent, but it definitely worked for you.}

{110}{}{[Pulls on his hair in rage] Kill! I'll kill them both! And you at the same time! I'll light the whole world on fire! I'll... [he suddenly goes weak and falls to his knees] I loved her! I gave her everything! The best years of my life! And she goes back to HIM? Why, why...? He could never love her like I did...}
{111}{}{[Leave as quietly as you can.]}

{112}{}{I know what I did sounds horrible... But one can do anything for the woman he loves.}
{113}{}{Do you barge into everyone's houses, or are we a special case? Oh, and while we're at it - stay away from my wife.}
{114}{}{I would kill anyone to protect my family!}

{120}{}{Who the hell are you? You'd better have a good fucking reason to come into my house!}
{121}{}{Watch your mouth! [punch him in the jaw]}
{122}{}{I'm not important. Your friend in the sewers, though...}
{123}{}{Hey, don't freak out on me! I'll leave.}
{124}{}{How rude! If you're going to act that way, then I have no interest in talking to you. Goodbye.}
{125}{}{And who exactly are you?}
{126}{}{Who am I?! I'm Colin - the head of this fucking house! And this is my wife, Shelley. We pay our rent and we mind our own business! You ought to do the same!}
{127}{}{I wouldn't care myself, but you have business with a man in the sewers...}

{130}{}{[Colin falls flat on his back as his wife screams] Arrrgh! What the hell is wrong with you?!}
{131}{}{That was for that ghoul who's lived ten years in the sewers, you son of a bitch!}
{132}{}{Chris?! Oh god, he's alive?!}
{133}{}{Better than ever. And he's back for revenge!}
{134}{}{No thanks to you. He spent a decade trapped in the sewers eating rat meat because of what you've done.}

{140}{}{I wouldn't care, personally. The man you trapped, though...}
{141}{}{[He suddenly goes very quiet and very still] Wh... What man? I didn't trap any man.}
{142}{}{Shelley's first husband. You pushed him into the sewers and sealed him up forever. He's been eating rats to survive for years!}
{143}{}{You didn't? Hmm, maybe I made a mistake. Sorry.}
{144}{}{[He whispers to himself] Chris is alive? No... No, he can't be...}
{145}{}{He can and he is. So what are you going to do now?}

{146}{}{What do I do? Ha-ha... [he grins nervously] ...what else can I do? There's only one option now. Ha-ha!}
{147}{}{Okay, that's one idea. But what if - just hear me out - you *don't* kill him?}
{148}{}{You mean killing him? Well, I think you can guess where he is. Good luck.}

{149}{}{I don't give a shit what you think. This isn't your problem, this isn't your family, this isn't your life. You've got no right to tell me what to do!}
{150}{}{Think what you want. It won't do you much good without knowing where he is.}
{151}{}{Hmm... You make a good point. Okay, he's in the sewers. Good luck.}

{152}{}{Oh, I get it. Nothing's free, right? Fine, have it your way. I'll give you 300 bucks to show me where that bastard lives.}
{153}{}{This is a man's life! It's worth far more than your miserable money.}
{154}{}{Finally, you're talking sense. Or cents, heh-heh. Give me the money and I'll show you where he lives..}

{155}{}{If you pay, I'll show you where Chris is now.}

{156}{}{Are you going to show me where he lives already? I've got to kill him before he destroys my family!}
{157}{}{Pay me and I'll show you.}
{158}{}{Alright, come on. I want to see this.}
{159}{}{Nah, I'm not telling. I just wanted to see you angry and helpless again.}

#Женские реплики
{1143}{}{You didn't? Hmm, maybe I made a mistake. Sorry.}
{1156}{}{Are you going to show me where he lives already? I've got to kill him before he destroys my family!}
{1159}{}{Nah, I'm not telling. I just wanted to see you angry and helpless again.}