{100}{}{You see a city dweller.}
{101}{}{You see an ordinary resident of this slum.}

{109}{}{Uh, hello. We're happy to have visitors, of course, but...}
{110}{}{Uh, hello. We're certainly glad to have visitors... Unlike our neighbors...}
{111}{}{Yes, your neighbors aren't very talkative.}
{112}{}{Goodbye.}
{113}{}{They're not. But they weren't always like that. Ever since Mark disappeared, they've been waiting for the consequences.}
{114}{}{Uh, consequences?}
{115}{}{Mr. Wright doesn't like people who let him down. And Mark let him down. Now someone has to pay, you see? I pity the old geezers, but their days are numbered.}
{116}{}{Do you know what happened to Mark?}
{117}{}{Well... Let's just say I heard something the other night, but I can hardly remember it now. I'm sure there's something to help me remember... If you know what I mean.}
{118}{}{Of course I do. Would a hundred bucks be enough for the information?}
{119}{}{Do you know who I am? Who my boss is? You don't want to know, I'll tell you that. He usually gets the information out of people way faster than I do.}
{120}{}{I know one trick I can do with your fingers that might refresh your memory. Want me to show you?}
{121}{}{A hundr- oh yeah, sure...}
{122}{}{Here's the cash.}
{123}{}{Oh, thank you sir. [he sticks the money into his pocket] It's good that you came to see us.}
{124}{}{Now, tell me everything.}
{125}{}{It was late at night. Mark came home, exhausted, covered in road dust. He had an heated argument with his family about something, we could hear them even through the wall... They wanted Mark to run out of town somewhere north. And that is what he bloody well did! Abandoned his family, that goddamn pussy! All because something had happened during Mr. Wright's request and now he just couldn't finish what he'd started. Yeah, bad luck for the guy.}
{126}{}{That information might be useful. You keep your mouth shut about our conversation, and I'll go and do some research.}
{127}{}{Looks like Mark left town. He was heading north.}
{128}{}{Oh, I see. Uh, I'll be glad to help you and your boss... In any way I can. Uh, no problem.}
{129}{}{W-Wait, take your time... I'm, uh, always happy to help anyone I meet.}
{130}{}{Don't be ridiculous. There's somebody in this slum that won't let strangers hurt us. I'm talking about Mr. Wright. He's interested in having us in his pocket, so you'd better keep your tricks to yourself.}
{131}{}{You are lucky this time.}

#Женские реплики
{1123}{}{Oh, thank you ma'am. [he sticks the money into his pocket] It's good that you came to see us.}