{100}{}{You see Mrs. Clover.}
{101}{}{You see Mrs. Clover. She's not quite old yet, but she's already starting to "dry up".}

#First talk
{110}{}{You? Again!? Leave me alone! I gave you everything I had! If you come again, I'll show you what this old woman is capable of!}
{111}{}{I think you have me confused with someone else.}
{112}{}{Shut it, hag! I don't give a shit about your problems.}

{113}{}{Oh... Sorry! I thought you were from the casino. These bouncers have such cold hearts that they're not afraid to use force on someone like me!}
{114}{}{These bouncers? What's going on?}
{115}{}{What happened?}
{116}{}{I'm not interested in any of it. I think I'll go now.}

{117}{}{You... I thought it was the bouncers again.}
{118}{}{I'm so glad to see a friendly face...}

#Receiving quest
{119}{}{Misfortune struck me. My husband passed away, and then it turned out that he had debts to the casino. Now I'll either be evicted or sold into slavery.}
{120}{}{Sorry, but who are you?}
{121}{}{If these are your husband's debts, why are you being punished for them?}
{122}{}{How did your husband die?}
{123}{}{How much does your husband owe?}
{124}{}{And no one stood up for you?}
{125}{}{I'd like to help you with that debt.}
{126}{}{This is none of my business. I think I'll be going now.}

{127}{}{Tell me what happened again.}
{128}{}{That's nice, I need to go now.}
{129}{}{Goodbye.}

{130}{}{Mrs. Clover, if you must know. I work in the kitchen at a local restaurant.}
{131}{}{The bouncers don't care. They just want their money. Since my husband is dead, they are determined to get it from me. That's how the world works.}
{132}{}{Street kids jumped him when he was drunk. Must have been easy prey for them.}
{133}{}{I have a thousand left to pay. Even if I didn't have to pay my rent, it would take a few weeks to make that much. And with the way things are going, I doubt I'd have that much time.}
{134}{}{As long as I'm here, Mr. Wright won't let anything happen to me. I'm one of his most reliable tenants. But I doubt it will go on like this. He won't turn against the casino just for my rent. He'll just evict me and give that room to somebody else. And once that happens... I'll be easy prey for the bouncers. I think they'll sell me into slavery.}
{135}{}{You want to help? That's wonderful! But I have nothing to pay you with.}
{136}{}{One-time payments are not the best prospect in Reno. I hope that my help will be a long-term investment.}
{137}{}{Then why am I wasting me time here? I'm leaving.}
{138}{}{I need to know more about the problem before we continue.}
{139}{}{Got it. Well, enough of this sad talk - I need to go now.}
{140}{}{Thank you for your honesty, I couldn't expect more. But listen - my house belongs to Mr. Wright, and I work at the "Silver Legacy" Hotel. Maybe helping me would improve your reputation in the area? Anyway, your help is all I have now. Talk to the receptionist at "El Dorado" - he has all the ledgers.}
{141}{}{I'll see the administrator.}

#Handing in the quest
{150}{}{Glad to see you.}
{151}{}{Here's the administrator's ledger. You owe them nothing now.}
{152}{}{Goodbye.}
{153}{}{You did it!? Unbelievable! I don't know how to thank you. Just know that this will not go unnoticed by the other residents of these slums. Thank you. Here, at least take this. Something to eat before you go on your way. A special recipe, no one else makes it!}
{154}{}{Thank you. And goodbye.}
{155}{}{Speaking of it, your husband was quite a good player. How did someone like him lose that much money?}
{156}{}{I can tell you, can't I? Those sneaky bastards in the casino cheat with weighted dice. The house always wins, right? He knew, but he kept trying his luck. He thought he could beat their system and get lucky... [she sighs] He didn't.}
{157}{}{Yeah, that's exactly how gambling works. Well, see you, Mrs. Clover.}

#Questions about other quests
{160}{}{I'm looking for workers from Uranium City. Do you know anything about that?}
{161}{}{Yes, of course. Rumors like that spread quickly around here. Carl is a neighbour of mine. Michael got tossed out into the streets by Wright's men and Joseph was sold into slavery. Seeing a man of such high status suddenly reduced to nothing... It's terrifying.}
{162}{}{Do you know something about Ted Bundy?}
{163}{}{No. Who is he? If he lived here before I moved in, my neighbours might know. They were here for much longer than me.}
{164}{}{What can you tell me about Harding?}
{165}{}{Quiet guy. A little slow, I guess. That's why he gets humiliated all the time. On the one hand, it's sad. But on the other, it's his own fault that he can't find his place in society. If you want to know what I think, he just hasn't had enough attention from people in his life. Especially from girls. [she winks] You know what I'm talking about.}
{166}{}{What do you know about the missing prospectors, Mark and Robert?}
{167}{}{I heard about that. They both just disappeared. Not surprising, considering it's not the safest job to walk through the ruins with those metal detecting things... I remember that Mark came by, I saw him through the window late at night. But I have no idea what he was doing here.}
{168}{}{Another question.}
{169}{}{That's all I wanted to know.}

#??????? ???????
{1136}{}{Did I say anything about pay? I want to deal with this situation because it isn't fair!}
