{100}{}{You see a citizen.}
{101}{}{You see a gloomy citizen. He doesn't look particularly friendly.}
{102}{}{We don't need strangers here! Get out!}
{103}{}{If you'll show your face to our home one more time, I'm gonna break your legs! Don't look us being ramshackle as an old potato...}
{104}{}{Please, forgive me for being so rude before.}

{110}{}{You're not welcome here! Beat it!}
{111}{}{Wait - I just want to know if the prospector Mark lives here.}
{112}{}{Sorry, I didn't mean to bother you. [leave]}
{113}{}{You're lucky I'm in a good mood, or there'd be a beating, alright. [leave]}

{114}{}{[He grits his teeth] Here? Not anymore. It's just us two old farts now. That's all I have to say - now get out of our home!}
{115}{}{This couple clearly knows something, but refuses to talk.}
{116}{}{This home might not be yours for much longer...}
{117}{}{You think we don't know that?! Or do you just have nothing better to do, than antagonize an elderly couple?}
{118}{}{I know about Mark and Robert. I could tell Mr. Wright everything. But I didn't. And won't, unless you want me to.}
{119}{}{You're not look like one of Wright's men, I give you that...}
{120}{}{After everything I've done for the people in this city, you'd think you'd want my help. But if you insist...}
{121}{}{Wait, you're him? The hero of the slums? No, please - don't go, I'm sorry. We just wanted to protect our son. Mark screwed up, but he's still family. Wright will throw us to the wolves - we know that. But we've accepted that, if it'll keep Mark safe.}
{122}{}{So what happened after Hawthorne?}
{123}{}{You earned 300 experience points for convincing the elderly couple.}
{124}{}{Mark came home, told us what happened to his partner and said he wouldn't be able to do Wright's job. What could we do? We gave him all the money and sent him north with a caravan. We don't know where he went - we thought it would be best if no one could find him, not even us. Wherever he is, he can get a second chance there.}
{125}{}{I see. Well, that's all I needed. Goodbye.}

{126}{}{That's all. You can calm down. [leave]}
{127}{}{It's okay, I'll deal with this. Trust me.}

#Женские реплики
{1112}{}{Sorry, I didn't mean to bother you. [leave]}
{1113}{}{You're lucky I'm in a good mood, or there'd be a beating, alright. [leave]}
{1114}{}{[He grits his teeth] Here? Not anymore. It's just us two old farts now. That's all I have to say - now get out of our home!}
{1118}{}{I know about Mark and Robert. I could tell Mr. Wright everything. But I didn't. And won't, unless you want me to.}
{1119}{}{You could be working for Wright...but, no. You're your own woman, aren't you? Maybe you can help.}
{1120}{}{After everything I've done for the people in this city, you'd think you'd want my help. But if you insist...}
{1121}{}{Wait, you're her? The angel of the slums? No, please - don't go, I'm sorry. We just wanted to protect our son. Mark screwed up, but he's still family. Wright will throw us to the wolves - we know that. But we've accepted that, if it'll keep Mark safe.}