{100}{}{You see Patrick.}
{101}{}{You see Patrick He looks neat and clean, as always.}
{102}{}{The audience scatters in terror!}
{103}{}{Watch them, not me.}
{104}{}{All this effort for nothing...}
{105}{}{Thank you for your help.}

#On loading map
{110}{}{Most of the people are here. The rest should show up as I start my speech.}
{111}{}{Got it. What do you need from me?}
{112}{}{You will be my bodyguard. Although it may sound too pompous... In any case, your job is to provide security. No doubt someone here is an assassin or a protester. We have to make sure everyone can enjoy the show without getting hurt.}
{113}{}{Don't you think that you are too suspicious? No one here looks like a threat.}
{114}{}{Alright. You go read your speech, I'll keep a close...-er eye on the crowd.}
{115}{}{Alright, I'll keep an eye out. Maybe even two.}
{116}{}{Let's pray everything goes to plan.}

#Πεχό
{200}{}{Ahem... [adjusts collar]}
{201}{}{All right, let's begin...}
{202}{}{We are gathered here, guided by the hand of God.}
{203}{}{Led through a helpless, doomed world.}
{204}{}{We are all victims of greed and ruthlessness of our ancestors.}
{205}{}{When, out of lack of resources, man turned to war...}
{206}{}{...the Great War.}
{207}{}{Nothing has changed since then. People continue to destroy the last bits of humanity within them.}
{208}{}{Forgetting that we are all brothers and sisters. We are all... God's children.}
{209}{}{This film will tell us how it all happened, so that we avoid the mistakes of our past.}
{210}{}{Well, let's get started!}