{100}{}{You see Patrick.}
{101}{}{You see a young man with a cute old-style beard.}

#Первый разговор
{110}{}{[The young man smiles at you, but you see sadness in his eyes] Welcome, wanderer. My name is Patrick. Can I ask you a few questions?}
{111}{}{That depends on the question.}
{112}{}{Sure, I have nothing to hide.}
{113}{}{Hell no, I ask the questions around here!}

{114}{}{No-no. I do not insist. If you don't want to talk, we can peacefully go our separate ways. But your opinion is of value to me, as the ones of folks living around here.}
{115}{}{But I'm not from around here...}
{116}{}{Well, okay. Go, ask your questions.}
{117}{}{I don't want you asking something of me.}

{118}{}{That doesn't matter. We all walk the same earth.}
{119}{}{Nonetheless. The decision is yours.}
{120}{}{Fine, then.}

###########################################################################
#
#                  TEST
#
###########################################################################

{122}{}{Your words inspire confidence. Tell me, do you believe in God?}
{123}{}{I only believe in smooth barrel of my gun.}
{124}{}{Yes, I believe in Him!}
{125}{}{No, I don't. Just don't.}
{126}{}{Are you serious? You might as well ask if I believe in Santa.}
{127}{}{I don't even know who that is.}

{128}{}{What guides you in your decisions? The word of God, your personal experiences, or something else?}
{129}{}{My Pip-Boy 2009 guides me along the path of logic and reason.}
{130}{}{I believe that without the Lord we are wandering blindly in the dark, and only He can guide our path.}
{131}{}{I have no need in anyone's advices and instructions to make important decisions in life.}
{132}{}{I'm being led by bottle of booze mixed with iguana-on-a-stick, country-style.}
{133}{}{I don't know. The question is beyond me.}

{134}{}{Are you willing to sacrifice your life to save other people?}
{135}{}{I need to know what kind of people they are first. If they're worthy and there's no other choice - then yes.}
{136}{}{I want to devote my life to help people, willing to sacrifice myself saving them.}
{137}{}{Most people in the world aren't worth my kind of sacrifice.}
{138}{}{I can sacrifice my left boot. That should be difficult, but I can try.}
{139}{}{I don't know. I could only answer that in the moment.}

{140}{}{What do you want most in this life? Wealth, glory, family... Or, maybe, to save the world?}
{141}{}{My first priority is always to survive. Everything else comes after that.}
{142}{}{I want to save everyone I can.}
{143}{}{I don't need to make up some higher goals for my life.}
{144}{}{Can I have all of the above? No? Then, I suppose, I'll get... Something jazzy. And some popcorn to go with it.}
{145}{}{The choice is tough.}

{146}{}{In your opinion, what's the worst of all human vices?}
{147}{}{Greed.}
{148}{}{Pride.}
{149}{}{Betrayal.}
{150}{}{The proximity of having the belly button.}
{151}{}{Well, they're all pretty bad in their own way.}

{154}{}{How can I help you?}
{155}{}{Nothing for today.}
{156}{}{You wanted to ask me some questions, right?}
{157}{}{Oh, yes. If you don't mind.}
{158}{}{Good. Let's get started.}
{159}{}{I've changed my mind.}

{160}{}{[He nods approvingly] You know the price of things. You know the path you walk. But not everything in this world has a number. Be ready for a puzzle that cannot be solved.}
{161}{}{[He nods approvingly] You've devoted your life to your fellow man. Many of them won't do you the same courtesy. Some day it might kill you... Or save you.}
{162}{}{[He nods approvingly] You know your worth. And when the right time comes, you'll make the world earn it.}
{163}{}{[He nods approvingly] You believe in tomorrow. And it will come, with us or without us.}
{164}{}{[He nods approvingly] It's hard to make a choice ahead of time, isn't it? You must prefer to choose on a case-by-case basis. Many people think the world is black and white, but the truth is that there is no truth. You can't know the right answer until you've seen the question for yourself.}
{165}{}{Sorry if that was tiresome. I just wanted to know what kind of person you are.}
{166}{}{Ugh, that's fine.}

###########################################################################
#
#                  Обыденные разговоры: о себе, о клубе и пр
#
###########################################################################

#О себе
{170}{}{I want to know more about you. Care to tell?}

{171}{}{Sure. My name is Patrick, I'm from Salt Lake City - a big city far to the east. Our Mormon community has sent me here to preach the word of God. It's been hard, but I'm not going to give up.}
{172}{}{I've seen that type of jumpsuit before. Are you from a vault?}
{173}{}{}
{174}{}{Why would your community send you to such a dangerous city?}
{175}{}{Do you preach to those prostitutes downstairs, too?}
{176}{}{What are you doing here, exactly?}
{177}{}{Sure.}
{178}{}{}
{179}{}{Another question, please.}
{180}{}{Enough about you and your missionary work. Let's change the subject.}
{181}{}{Right. But I have to go.}

{182}{}{No, no, I was born after our people left the shelter. There is a vault on city's outskirts, but no one has been there in years. This jumpsuit is a... Keepsake from my grandfather. He served the vault, but when the bombs came, he refused to hide away from God's world. He said he wouldn't, or couldn't, bear the gray walls and enclosed space without a single ray of God's light. That's all I know about him - he was dead long before I was born.}
{183}{}{}
{184}{}{This is our tradition. Every one of us must spend two years preaching the gospel of God. I could have chosen another path or denied it entirely, but I didn't. The people here need salvation as much as anyone else.}
{185}{}{Do not blame the people here. They are surviving the only way they know how. That's why I'm here - to open their eyes. You may not believe it, but some of them have converted already.}
{186}{}{Oh, many things. Besides praying, preaching, and gathering old books, I teach children to write, lead an anonymous support group, and just help whoever I can.}

#Пожер'вование
{190}{}{I want to donate $100 to your cause.}
{191}{}{That's very generous of you! Every dollar goes to help people in need, and may just save someone's life. Thank you from the bottom of my heart!}
{192}{}{You're welcome.}
{193}{}{That's enough trouble out of you!}

###########################################################################
#
#                  Хардинг
#
###########################################################################

{200}{}{I'm interested in your support group.}
{201}{}{I understand your curiosity, but you don't need it, believe me. This group is to help people who cannot help themselves. [he smiles] I don't know much about you, but I can tell you're the farthest thing from that.}
{202}{}{Is Harding in your group?}
{203}{}{I... See. I suppose if you know, there's no point in denying it. But I won't say another word about it. Rule number one is: what happens in the group, stays in the group. This is a sensitive matter. If we violate each other's trust, many of our members will be left with nothing.}
{204}{}{Perhaps we can talk about something else?}
{205}{}{Tell me about these group meetings. What are you trying to do?}
{206}{}{I'm sorry, but I don't think you'd understand. Do you know what psychiatry is?}
{207}{}{Let me guess - group psychotherapy, right? You sit around in circle and start brainwashing each other.}
{208}{}{That's... Not far from the truth. I'm surprised! How do you... I suppose I should be happy to have a colleague in front of me. Medical knowledge is hard to find in this city. Where did you learn this?}
{209}{}{Life experience, Patrick. Life experience.}
{210}{}{Amazing! May God bless you. Your gift can do great things in the wasteland!}
{211}{}{Maybe. But about your support group...}

{212}{}{Of course. I'm always ready to share experience with my colleague.}
{213}{}{How many people come to this support group?}
{214}{}{Just a few. Even three is enough for our group therapy. Some come only once and never visit again. Right now there's about ten permanent members.}
{215}{}{Another question.}
{216}{}{What's wrong with these people?}
{217}{}{These people can't handle the stresses of society. Most of them suffer from anxiety or similar conditions, and society preys on them. The most common metaphor in our group is of rabbits living in a world of wolves.}

{218}{}{How are trying to "cure" Harding?}
{219}{}{I'm trying to teach him to deal with his insecurities. Society won't accept him, so he must learn to accept himself.}
{220}{}{Has Harding always been like this?}
{221}{}{From childhood, I think. He won't talk about it, but I suspect sexual abuse by his parents. I know he's always been an outcast and found refuge in books. It hasn't been good for his social development.}
{222}{}{How has Harding survived with this condition?}
{223}{}{He thinks he's the lowest of society, so he takes the lowest jobs - watching brahmin, cleaning toilets, that sort of thing. Any community, even Reno, needs people to do these things.}

{224}{}{I don't agree with your choice of Harding's treatment.}
{225}{}{What do you mean?}
{226}{}{You're trying to suppress his phobia by making him comfortable as an outcast, but I think he needs more attention and communication.}
{227}{}{This could be dangerous. Society's bullied him for a long time - no one knows what could be buried within his scarred conscience. I wanted to give him peace instead of exposing him to more stress.}
{228}{}{What about medication?}
{229}{}{I still thinking about it. For now, I have another question.}

{230}{}{I've been thinking about that lately. He need something to calm his nerves and suppress the worries.}
{231}{}{Pre-war anti-smoker was used to suppress anxiety. Maybe that will help.}
{232}{}{I still think he has to improve his social confidence.}

{233}{}{I'm not an expert, so I'll trust in your knowledge and the will of God. But I don't have any chems. The local dealers might be able to help, but they'll undoubtedly demand a high price.}
{234}{}{I'll see what I can do.}
{235}{}{I'm not an expert, so I'll trust in your knowledge and the will of God. If Harding is going to conquer his fears, he'll have to overcome his sexual trauma... I don't like the idea, but maybe the sex workers in Reno can help you.}
{236}{}{I don't agree. I don't know why.}
{237}{}{It's useful to follow your instincts sometimes, but we can't take risks in this case. Don't forget, we're talking about the well-being of another man's soul.}
{238}{}{I'll think about it and get back to you.}

###########################################################################
#
#                  Квес'ы
#
###########################################################################

#О си'уации в городе
{240}{}{What can you tell me about the situation in the city?}
{241}{}{As we speak, the Satan lures people of this city deeper in his cobwebs of civil war.}
{242}{}{In your opinion, why can't the people here live peacefully?}
{243}{}{That's a good question. The most part of my home, Salt Lake City, was destroyed by the thirteen nuclear strikes, so it took a lot of time and a lot of work to rebuild. But Reno and its people retained all of the gifts of the old world.}
{244}{}{The irony is, the devastation of Salt Lake City built strong families and communities, as people had to work together. Here, people fell victim to their own selfishness.}
{245}{}{Everyone tried to take from each other, caring only about themselves. AS a result, you won't find bright doctors, educators, or other people here. And because of that, this society has no future. The people can only fight for what's left over from earlier years.}
{246}{}{[Next]}

{247}{}{If the local gangs go to war, which of them will you support?}
{248}{}{Gangs? That isn't just about gangs, my friend. There are people behind them with their own politics and ideas of how to lead the city. They know that, even in this place, they can't just take what they want. There's only so many resources, and if they become too greedy today, there won't be anything for them tomorrow. That's why the people choose sides - they see them as having a plan for the future. But I don't think either of them are on the right path.}
{249}{}{Thank you for explanation.}

#Квес' на больного
{250}{}{Can I help your mission in some way?}
{251}{}{Are you serious? It brings joy to my soul to know someone wants to help.}
{252}{}{ Right now, I have two problems. Itchie has a serious arm injury, and I can't get my long-waited package from home.}
{253}{}{ Right now, the biggest problem is Itchie's bullet wound. I can't do anything for him.}
{254}{}{ Right now my main concern is that I can't get my long-waited package from home.}
{255}{}{I will take care of him.}
{256}{}{I will look into your package.}
{257}{}{ But no, that's alright. I don't need anything right now.}

{258}{}{He was rummaging through some trash bin when a firefight broke out around him. He was shot in the arm and it's become infected. All I could do is give him all painkillers I had. If you are a doctor, can you help?}
{259}{}{I'll help.}
{260}{}{I can help, but medication costs money.}
{261}{}{Ah, I'm sorry. I thought you were offering charity, not paid services. Let's see... I only have 100 dollars. Will that be enough?}
{262}{}{I'll deal with the patient and get back to you.}
{263}{}{That's very good! I hope for the best.}
{264}{}{Good news! I've treated Itchie's injury.}
{265}{}{}
{266}{}{That's great news! This is the last of my money, but it's worth it to help him.}
{267}{}{No, you need the money more than I do.}
{268}{}{Hand it over.}
{269}{}{That's great news! Thank you for your kindness. May the Lord bless you.}
{270}{}{You're welcome.}
{271}{}{That's great news! Thank you for your kindness. May the Lord bless you.}
{272}{}{Hey, who's going to pay me? This cost me 100 bucks!}
{273}{}{Oh, I'm sorry. I thought you were offering charity, not paid services. Alright, I have 100 dollars left. I hope it's enough, for it's all I have.}
{274}{}{Give it to me.}
{275}{}{Glad to help.}

#Квес' на посылку
{280}{}{Every month, my brothers in Salt Lake City send me a package via the Nevada Express containing a message and supplies. This time, the courier - a boy from the slums - never arrived. The Nevada Express employee told me that they gave it to him, and they have no reason to risk their reputation for whatever supplies were in the package.}
{281}{}{[Next]}
{282}{}{I figure the supplies are gone. I don't blame the people in the slums for that; given their circumstances, I can only hope they got to someone in need. But the message... It's important to me. Please, try to find it.}
{283}{}{I'll see what I can do.}

{284}{}{About your message...}
{285}{}{Did you find it? I really need it.}
{286}{}{Here you go.}
{287}{}{How did you lose it again?}
{288}{}{Every month, my brothers in Salt Lake City send me a package via the Nevada Express containing a message and supplies. This time, the courier - a boy from the slums - never arrived. All I need is the message. Talk to the Nevada Express employee or the courier.}
{289}{}{You really did it! That's amazing! I'm afraid I can't pay you, but I thank you from the bottom of my heart. You don't know how important these instructions are for my work here.}
{290}{}{What is this message, anyway?}
{291}{}{I wish you the best. Good luck.}
{292}{}{Yeah, bye.}
{293}{}{[He reads the message] Hmm. The Community offers me to return to Salt Lake City. But I can't! The people of Reno need me more now than ever. I have to stay.}
{294}{}{That's very honorable of you. Well, good luck.}
{295}{}{If you say so. As for me, it's time to move on. Goodbye.}

#Квес' на кинопоказ
{296}{}{Yes, I have a delicate request. The message you brought to me included an old movie on holodisk. I want to organize film screening for the locals at night, but I'm afraid Mr. Wright will not allow me. Would you convince him to allow me a showing?}
{297}{}{I'll do it. I'll talk to Wright.}
{298}{}{Thank you. I will await his answer.}
{299}{}{Later.}
{300}{}{I would like to know more about that movie first.}

{301}{}{Of course! What do you want to know?}
{302}{}{I need to talk to you about the movie.}
{303}{}{What kind of movie is it?}
{304}{}{What's so important about it?}
{305}{}{Why are you so concerned about Wright's opinion?}
{306}{}{That's all.}
{307}{}{It's a pre-war movie about the greed and vice of humanity. The mail idea is that the sins of the world brought about its destruction... I know it won't mean anything for a lot of people, but if it will allow me to save one soul, it will have been worth it. Mormons have been using it for this purpose since before the war, and missionaries like myself always show it at the end of their mission. No one in Reno has seen it yet, or so I assume.}
{308}{}{The people in Reno have no awareness of their past and no hope for their future. This movie could give that to them. Besides, most locals have never seen any sort of movie at all before. This may help them understand our faith more and drive them to the path of God.}
{309}{}{He owns the slums, and in essence, the people within them. If Wright doesn't approve of the movie, he may shut it down or take even more drastic action. It simply can't happen without his permission.}
{310}{}{Wright gave you permission to show the movie, but he said he won't be responsible for your security.}
{311}{}{I see... I understand. I had hoped we would have his protection, but I don't blame him.}
{312}{}{Would this be dangerous? Why would someone attack a movie showing?}
{313}{}{I'm afraid some people in the city do not approve of my preaching. They could be disruptive... Or perhaps, violent. Listen, I may be asking too much, but... Would you help me?}
{314}{}{I'll get prepared and let you know when I'm ready.}
{315}{}{You don't have to worry about Wright anymore - he's dead.}
{316}{}{That is sad news. I fear what may happen to the slums now, but that means we are needed now more than ever before. It will make the movie showing more dangerous, too.}
{317}{}{We can show the movie now. }
{318}{}{Are you sure you're ready? We'll have to show it outside the city, and won't have time to go back if we forget anything. Take anything you might need.}
{319}{}{Let's go.}
{320}{}{Actually, you're right. I'll be back soon.}

{321}{}{It's good to see you well after our big night.}
{322}{}{You're still in one piece! How was the movie?}
{323}{}{Everyone was in awe! Women cried, men were happy. Although, I don't think it was the movie itself that did it so much as the opportunity to enjoy something they'd never seen before. They have so few pleasures here, and even fewer with no dangerous consequences following them. I think they'll talk about this for a long time. Thank you! None of this would have been possible if not for you!}
{324}{}{All's well that ends well.}
{325}{}{From here, these people must walk the path of God themselves. Again, thank you for everything. I hope you will continue to help the people here... They need it.}
{326}{}{Good luck, Patrick.}
{327}{}{Helping the Mormon missionary has improved your karma and your reputation in the slums.}

#Квес' Томпсона
{330}{}{Say, you don't have a sniper rifle, do you?}
{331}{}{Me?! No, I'm a peaceful person. The only weapon I carry is for self-defense.}
{332}{}{Then how do you explain the ammo shell on your balcony? It seems to line up with the recent shooting on the street.}
{333}{}{Oh... I see. Listen, that day a family asked to stay here. They looked like they were from out of town and the husband had a strange-looking briefcase with him. I had no idea they were assassins! Do you think Stryker hired them?}
{334}{}{Hard to say, but your story sounds convincing. And you really don't have a rifle. Thanks for the information.}

#Female character
{1110}{}{[The young man smiles at you, but you see sadness in his eyes] Welcome, wanderer. My name is Patrick. Can I ask you a few questions?}
{1115}{}{I'm not from around here. I might not know how to answer your questions.}
{1134}{}{Are you willing to sacrifice your life to save other people?}
{1136}{}{Yes. If I can't help others, what's the point of living at all?}
{1158}{}{Good. Let's get started.}
{1159}{}{I've changed my mind.}
{1160}{}{[He nods approvingly] You know the price of things. You know your path. But not everything in this world has a number. Be ready for a puzzle that cannot be solved.}
{1208}{}{That's... Not far from the truth. I'm surprised! I suppose I should be happy to have a colleague in front of me. Medical knowledge is hard to find in this city. Where did you learn this?}
{1210}{}{Amazing! May God bless you. Your gift can do great things in the wasteland!}
{1236}{}{I don't agree. I don't know why.}
{1266}{}{That's great news! This is the last of my money, but it's worth it to help him.}
{1275}{}{Glad to help.}
{1314}{}{I'll get prepared and let you know when I'm ready.}
{1318}{}{Are you sure you're ready? We'll have to show it outside the city, and won't have time to go back if we forget anything. Take anything you might need.}
{1320}{}{Actually, you're right. I'll be back soon.}
