{100}{}{You see an audience member.}
{101}{}{You see an excited member of the audience.}

{102}{}{The spectators scatter in terror!}
{103}{}{This is the worst day of my life... For the last year.}

#Реплика для детей
{105}{}{Can you believe it? A real movie, like the old days!}

#Реплика для взрослых
{110}{}{You're here for the movie too?}
{111}{}{We brought the whole family. I hope it's worth it!}
{112}{}{I've never seen a movie. Maybe I won't see another one ever again!}
{113}{}{We have a beautiful view of the sunset from here...}
{114}{}{This Patrick guy is amazing!}
{115}{}{Not many people get this opportunity nowadays...}
{116}{}{I wonder if it's a horror film.}

#Подробные описания
{120}{}{You see an fleeing audience member. You don't think this show will get good reviews.}
{121}{}{You see an audience member, shivering in anticipation.}
{122}{}{You see a happy couple. Here they don't have to hide their relationship.}
{123}{}{You see a happy father. He's entertaining his children so they don't get bored.}
{124}{}{You see an older man. He's talking with his son about the days of the past.}
{125}{}{You see a child. He's listening intently to his father.}
{126}{}{You see a man in ragged clothes. He's chattering with his wife like he has a time of his life.}
{127}{}{You see a woman in shabby clothes. She's relaxing and laughing with her husband.}