{100}{}{You see an audience member.}
{101}{}{You see a member of the audience. He waits for the show.}
{102}{}{The spectators scatter in terror!}
{103}{}{What the hell?! Shit, better get out of here...}
{104}{}{The situation is safe now.}
{105}{}{Don't you dare touching me!}
{106}{}{Ah geez... *hic* I drank too much again... Maybe I should *hic* lie down for a few minutes...}
{107}{}{Ooh... I shouldn't have had that drink... I've got to lie down.}

{108}{}{Yeah, so... Justice can prevail, and stuff.}
{109}{}{You got the audience member drunk.}

{110}{}{Uh, hi.}

{111}{}{[The man pulls his ballcap lower and tries to avoid eye contact.]}
{112}{}{Where are you going?}
{113}{}{Enjoy the show.}
{114}{}{None of your business.}
{115}{}{Actually, it is my business. I'm Patrick's bodyguard. If you have something to say to him, say it to me.}
{116}{}{Oh, I've got something to say to him, asshole, just not with you around. Now get the fuck out of my way.}
{117}{}{What did you just call me?! You'd better leave before I get angry. You wouldn't like me when I'm angry.}
{118}{}{I'll let "asshole" slide this one time, for Patrick. Now go take your place. Or leave.}
{119}{}{You know what? I don't care. Do whatever you want.}
{120}{}{Oh yeah, *asshole*? What are you going to do, kneel down and pray at me? [he pulls aside his jacket to reveal a pistol] Yeah, that's right. You and your boy don't belong in Reno. Now get your ass out of my way, before I reach down your throat, pull out your guts, and hang you with them.}
{121}{}{Now I'm going to take that gun from you and march you into the desert. Every time you slow down, I'm going to put a bullet in your body part, somewhere, that won't kill you. Just enough to hurt you bad enough to get you marching again. You're going to walk further than you ever walked in your life, because when you finally stop and you *can't* move any more, that's when I'm going to put a bullet in your head and walk back. No one here will even notice we're gone. In fact, I bet no one in the city will ever miss you. What do you think?}
{122}{}{You say violent things. I do violent things. Last warning - this is your chance to leave.}
{123}{}{[He freezes up, eyes wide, then closes his jacket] You'd better hope I never catch you in a dark alley, asshole! [he gives you the middle finger and turns away]}
{124}{}{[Attack.]}
{125}{}{[Let him go.]}
{126}{}{He's too far.}

#Женские реплики
{1116}{}{Oh, I've got something to say to him, bitch, just not with you around. Now get the fuck out of my way.}
{1118}{}{I'll let "bitch" slide this one time, for Patrick. Now go take your place. Or leave.}
{1120}{}{Oh yeah, *bitch*? What are you going to do, kneel down and pray at me? [he pulls aside his jacket to reveal a pistol] Yeah, that's right. You and your boy don't belong in Reno. Now get your ass out of my way, before I reach down your throat, pull out your guts, and hang you with them.}
{1123}{}{[He hesitates for a second, watching you, then steps back] You'd better hope I never catch you in a dark alley, bitch! [he gives you the middle finger and turns away]}