{100}{}{You see a homeless boy.}
{101}{}{You see a poor dirty child watching you.}
{102}{}{Hey, mister, I know how to help you!}
{103}{}{Hey, miss, I know how to help you!}

####################################################################
#              Первый разговор
####################################################################

{110}{}{Hello, mister! Welcome to the great Reno!}

{111}{}{Thanks, kid! I had no idea Reno was such a friendly city!}
{112}{}{Get away from me, you beggar!}
{113}{}{Why are you so friendly? You want something, don't you?}
{114}{}{Yeah, hi. And bye.}

{115}{}{[The boy doesn't even blink] Okay, mister. I won't bother you anymore.}
{116}{}{Good. Now, what do you want?}
{117}{}{Make sure you don't. I don't want to talk to you again.}

{118}{}{Oh, no, mister! I'm just helping the newly arrived in the great Reno, so they don't get lost.}
{119}{}{Hmm. That's a weird way to earn a living... }
{120}{}{I thought you were a beggar.}
{121}{}{Then I don't need you.}

{122}{}{I'm not just begging for money! I'll make every dollar of yours worth being spent!}
{123}{}{Hmm, here's 5 bucks. What can you tell me about your town?}
{124}{}{Do you know any secrets?}
{125}{}{Tell me, have you seen a man named Balder?}
{126}{}{Hmm... You look small enough to get through that window... }
{127}{}{}
{128}{}{Well, let's see if you can help.}
{129}{}{I guess I don't need anything.}

{130}{}{Oh no, it can be very dangerous for the newly arrived! For just a little money, I can tell you how to stay safe!}
{131}{}{I was being sarcastic, you filthy piece of shit. Look somewhere else for your handouts.}
{132}{}{Oh, so you're a beggar, huh?}
{133}{}{Whatever you say. What are you doing here?}
{134}{}{Still, you can't help me. I'm leaving.}

{135}{}{Whatever you say, mister. I won't bother you any more.}
{136}{}{I'm helping newcomers in the great Reno, so they don't get lost and don't get in trouble.}

{137}{}{[The boy gives you an exaggerated smile] Hello, mister! How can I help you?!}
{138}{}{You are familiar with the city well enough, right?}
{139}{}{Hmm... You look small enough to get through that window... }
{140}{}{Nothing right now.}

{141}{}{That's why I'm here! I'm always happy to help! ...for just a *little* money!}
{142}{}{[He cocks his head to the side] Hmm? What do you mean?}
{143}{}{I'm looking for a man they call Balder Maxson. He has stretch marks on his neck. Have you seen him?}
{144}{}{Do you know who's painting the hotel's walls?}

{145}{}{Do you stand here often?}
{146}{}{Yes, I've lived half my life here!}
{147}{}{Fine, let's talk about something else.}

####################################################################
#              Покупка информации о тайнике:
####################################################################

{148}{}{I'm trying to get into a, er, "abandoned" room. Want to help?}
{149}{}{Hmm... Well, I do have one. What will you pay for it?}
{150}{}{I'll give you 20 bucks.}
{151}{}{I'll give you 10 bucks.}
{152}{}{I'll give you 5 bucks.}
{153}{}{Never mind, let's talk about something else.}

{154}{}{Nah, it'll make you a lot more money than that... If you pay for it, I mean.}
{155}{}{What if I just start breaking your fingers?}
{156}{}{Uh... But you wouldn't do that. Would you?}
{157}{}{You bet I would! I'm the devil himself! I love breaking little boys' fingers!}
{158}{}{I don't believe you! No way, you wouldn't do that! Not for a little secret!}
{159}{}{[Grab a finger and bend it back firmly] Last chance, kid!}
{160}{}{Fine, you're right. But I still want to know the secret.}
{161}{}{Wait, don't! I'll tell you! Don't hurt me, please!}
{162}{}{Start talking, brat! What's the secret?}
{163}{}{Forget it, I won't hurt you. So will you tell me the secret?}
{164}{}{Aaah! Let me go! Let me go and I'll tell you!}
{165}{}{Tell me first!}
{166}{}{[Let go] That was a warning. Next time, I won't stop.}
{167}{}{[Caravaneers start yelling at you from the parking lot] Hey! Leave the kid alone, asshole!}
{168}{}{You got lucky, kid... This time. I'll see you again later.}
{169}{}{[Look the kid straight in the eye and push harder on the finger]}
{170}{}{[He scowls at you silently]}
{171}{}{[You feel the finger shift in your grip as the bones dislocate from their socket] AAAAAAH!!! IT HURTS!!! AAAAAAH!!!}
{172}{}{Oops... }
{173}{}{No, please don't! I'll tell!}
{174}{}{I'm all ears!}

{175}{}{Whew... [he tries to catch his breath] I wanted to say that I heard some caravan merchants talking about a thief, that took some of their things and managed to hide them before they caught him. I don't know where he hid it, but it has to be close to the parking lot!}
{176}{}{Is that it? Because if you lied to me... }
{177}{}{It's true! They said it was dark and they ran around a lot of the buildings nearby, so they don't know where he hid them. The thief's too scared to come back, so they must still be hidden there... }
{178}{}{We'll see.}
{179}{}{You learned of a hidden stash of supplies near the parking lot without paying for it by threatening a child with violence. You must be very proud of yourself.}
{180}{}{I heard one of the caravan merchants saying a thief took some of their things and managed to hide them before they caught him. I don't know where he hid it, but it has to be close to the parking lot!}

{181}{}{Okay, that's fine.}
{182}{}{Let's talk about something else.}
{183}{}{Here is the money.}

{184}{}{I'll give you 15 bucks.}
{185}{}{You learned of a hidden stash of supplies near the parking lot.}
{186}{}{[He quickly pockets the money somewhere in his rags] I heard one of the caravan merchants saying a thief took some of their things and managed to hide them before they caught him. I don't know where he hid it, but it has to be close to the parking lot!}

####################################################################
#                    О городе
####################################################################

{187}{}{I'll tell you what I know, but I need the money up front.}
{188}{}{Okay, here's 5 bucks.}
{189}{}{Not now.}

{190}{}{What do you want to know?}
{191}{}{Where can I buy and sell supplies?}
{192}{}{How can I make some money around here?}
{193}{}{What kind of entertainment is there in this town?}
{194}{}{Is there anywhere I should avoid?}
{195}{}{Is there anyone in charge here?}
{196}{}{I'm looking for biker named Jay Kukish.}
{197}{}{}
{198}{}{}
{199}{}{[Next.]}
{200}{}{You can buy things at the caravan shop on the other side of the parking lot. There's two restaurants close by. The Silver Legacy's restaurant is right over there and has good food, but it's expensive. The Cotton Club is next to the El Dorado - its food is terrible, but it's 15 percent cheaper.}
{201}{}{If you want to work for a powerful boss, you have to have a good reputation, or have someone recommend you. It's not easy for people to get work here. [he narrows his eyes, examining you] But... Maybe you're different.}
{202}{}{The Silver Legacy and the El Dorado both have casinos, and the El Dorado has a boxing ring in the basement. There's a nightclub with lot of beautiful ladies, but you have to pay or have an invitation to get in, so caravaneers usually use services a women off the street at night. Uh... And if you want to just talk to someone, there's Ricky in the tall building next to the El Dorado. He used to be a caravan merchant, and if you give him a drink, he'll talk for hours!}
{203}{}{First, there's Thompson - he took over the old town hall building. The second one is Stryker, he and his men are located in a ex-bowling club. There's a lot of small-fry criminals in Reno, but it's usually okay if you stay on the main street. Anyway, try to watch your step.}
{204}{}{No one's in charge, but all of the bosses want to be. Thompson and Stryker are the most dangerous - they're big and they don't play around.}
{205}{}{A biker? Sometimes bikers go into the Silver Legacy hotel. You should ask there.}

####################################################################
#                    О граффити
####################################################################

{210}{}{Oh... That's a pretty big secret. You'll have to pay a lot for that.}
{211}{}{How does 50 dollars sound?}
{212}{}{[Grab one of his fingers and bend it back until it becomes painful] You're the one who's going to pay if you don't tell me, boy!}
{213}{}{I've changed my mind. Let me ask something else.}

{214}{}{Take down another street kid for 50 bucks? No way! I want 200 bucks, no less!}
{215}{}{You run a hard bargain, kid! Fine, here's 200 dollars.}
{216}{}{Like I told you, he only does it in the early morning when everyone is asleep. You should watch for him then.}
{217}{}{I see. Let me ask another question.}
{218}{}{Okay, I've never talked to him, but I've seen him painting the casino walls. There's usually a lot of people around during the day and most of the night, so he only works in the early morning, close to the sunrise. That's the only time when most of the city is asleep.}

{219}{}{Aaah! Let me go! Let me go and I'll tell you!}
{220}{}{Tell me first!}
{221}{}{[Let go] That was a warning. Next time, I won't stop.}

{222}{}{[Caravan merchants start yelling at you from the parking lot] Hey! Leave the kid alone, asshole!}
{223}{}{You got lucky, kid... This time. I'll see you again later.}
{224}{}{[Look the kid straight in the eye and push harder on the finger]}

{225}{}{[You feel the finger shift in your grip as the bones dislocate from their socket] AAAAAAH!!! IT HURTS!!! AAAAAAH!!!}
{226}{}{Oops... }

{227}{}{No, please don't! I'll tell!}
{228}{}{Phew! [he tries to catch him breath] I've never talked to him, but I've seen him painting the casino walls. There's usually a lot of people around during the day and most of the night, so he only works in the early morning, close to the sunrise. That's the only time when most of the city is asleep.}
{229}{}{We'll see.}

####################################################################
#                    О Лысом Максоне
####################################################################

{230}{}{I think I've seen someone like that. But if you want to know where... }
{231}{}{I'll pay you.}
{232}{}{Oh believe me, I want to. [grab one of his fingers and bend it back until it becomes painful] How badly do you want to keep your fingers intact?}

{233}{}{I'll tell you for 50 bucks.}
{234}{}{That's fair. Here's the money.}
{235}{}{[He nods towards the caravan store]}
{236}{}{Is that it? That was easy... }
{237}{}{Phew! [he tries to breath] I saw him go into the caravan store. He should still be close!}

####################################################################
#              Окно в коморку швейцара
####################################################################

{238}{}{Uh... [he glances around] ... Help how?}
{239}{}{The only way in is a window. It's too small for me, but I think you'll fit.}
{240}{}{Oh, forget it.}
{241}{}{Why do you need to get inside?}
{242}{}{Because I want to know what's in there.}

{243}{}{[He glances around again] What's the catch, mister?}
{244}{}{Okay, fine! I want you to take whatever's in that room and bring it back to me.}
{245}{}{Is it dangerous?}
{246}{}{No! Not at all.}
{247}{}{I need to think. What's in it for me?}
{248}{}{We'll split the money.}
{249}{}{Are you sure there is money there?}
{250}{}{Actually, no, but I'm sure there's *something* valuable inside.}
{251}{}{But what if there isn't?}
{252}{}{What do you have to lose?}
{253}{}{Nothing, but... Something feels fishy about this.}
{254}{}{Calm down! Everything is fine. All it'll take is ten minutes of your time, and then you'll get half of whatever we find.}
{255}{}{Hmm... That could help me eat tonight... }
{256}{}{So are you in or out?}

{257}{}{No, I'm out. This doesn't feel right.}
{258}{}{No, I'm out. I've heard about you. People say you're not trustworthy.}
{259}{}{I'm in. When do we start?}
{260}{}{Right now.}
{261}{}{I'll be back when the time comes.}
{262}{}{Well, maybe you'll change your mind. I'll try again later.}
{263}{}{No, I'm out. I don't feel safe with you. I don't think any child should.}
{264}{}{No. I've heard the caravan merchants saying really bad things about you.}
{265}{}{Introducing this child to a life of crime won't be good for your karma.}

####################################################################
#              У окна, таймерное событие
####################################################################

{270}{}{Here we are.}
{271}{}{This place isn't abandoned! This is the hotel!}
{272}{}{Calm down, the room's empty.}
{273}{}{I don't like this... }
{274}{}{Just get through the window, fast!}
{275}{}{Okay, okay... }
{276}{}{There are some things here, should I take them?}
{277}{}{Yes! Grab everything!}
{278}{}{Oh! Not bad!}
{279}{}{I'm done.}
{280}{}{Here's everything I could find.}
{281}{}{All right, take the junk and the change and get out of here.}
{282}{}{For a successful burglary you earn 100 experience points.}
{283}{}{   }

####################################################################
#              О байкерах
####################################################################

{290}{}{Hey, have you seen any bikers here?}
{291}{}{Oh, yes, mister! Their machines are so cool! Sometimes they get drunk and get into fights in the street and stuff. They're always fun to watch!}
{292}{}{Sounds like a blast. Where can I find them now?}
{293}{}{Oh, they're not here now. I don't think they'll come back for a long time. If the Nevada Express people see them, they'll probably shoot them on sight.}
{294}{}{I see. Another question.}
{295}{}{I see. That's all.}
{296}{}{Why would the Nevada Express shoot them?}
{297}{}{The bikers robbed a bus going to Black Rock. That was really crazy, even for bikers. The guy in the combat armor, Tuco, told me to watch out for them. He's in charge of the Nevada Express in Reno.}

####################################################################
#              Фича для машины
####################################################################

{300}{}{Woah, mister! I've never seen a working car in my life! You know, they say Reno was famous for its car workshops, once. I don't think there's anything left... Except... }
{301}{}{Yeah, yeah, I get it. Here's 20 bucks. What is it?}
{302}{}{Oh, you just happen to know of something for my car? I smell a setup.}
{303}{}{Hold that thought. We'll talk later.}

{304}{}{No way, mister! I'd never lie to a client! I have to be trustworthy, or I won't eat!}
{305}{}{If you say so... }
{306}{}{See you.}
{307}{}{Thanks! Someone came by selling on old box a few days ago, but no one wanted to buy it. I don't know what it is, but it's definitely something for a car. I don't know where he is now, though.}
{308}{}{Thanks. I'll keep an eye out for him.}
{309}{}{That's what I get for 20 bucks? What a rip-off... }
{310}{}{What were you saying about my car, before?}
{311}{}{If you pay, I'll tell you!}

{312}{}{Hey, what the hell did you make me buy?! It's just paint for tires, and it's all dried up anyway!}
{313}{}{Made you?! All I did was tell you what I heard! I didn't know it was useless!}
{314}{}{Now what am I supposed to do with it?!}
{315}{}{Do you have any idea what I can do with this stuff?}

{316}{}{Well, if you can't use it, and you can't sell it back... Nothing, I guess. Just... Throw it away.}
{317}{}{You little brat! Next time I see you, I swear... }
{318}{}{I guess it's my own fault. Sorry I yelled at you, kid.}
{319}{}{Well, you can't win them all. Buyer beware, I suppose.}
{320}{}{It's okay, people yell at me all the time. Sorry the stuff is no good... I was hoping your car would get something cool.}
{321}{}{That makes two of us. See you around, kid.}

#Female character:
{1110}{}{Hello, miss! Welcome to the great Reno!}
{1115}{}{[The boy doesn't even blink] Okay, miss. I won't bother you anymore.}
{1118}{}{Oh, no, miss! I'm just helping the newly arrived in the great Reno, so they don't get lost.}
{1135}{}{Whatever you say, miss. I won't bother you any more.}
{1137}{}{[The boy gives you an exaggerated smile] Hello, miss! How can I help you?}
{1157}{}{You bet I would! I'm the wicked witch of the wasteland! I love breaking little boys' fingers!}
{1158}{}{I don't believe you! No way, you wouldn't do that! Not for a little secret!}
{1174}{}{I'm all years!}
{1243}{}{[He glances around again] What's the catch, miss?}
{1291}{}{Oh, yes, miss! Their machines are so cool! Sometimes they get drunk and get into fights in the street and stuff. They're always fun to watch!}
{1300}{}{Woah, miss! I've never seen a working car in my life! You know, they say Reno was famous for its car workshops, once. I don't think there's anything left... Except... }
{1304}{}{No way, miss! I'd never lie to a client! I have to be trustworthy, or I won't eat!}
{1305}{}{If you say so... }
{1307}{}{Thanks! Someone came by selling on old box a few days ago, but no one wanted to buy it. I don't know what it is, but it's definitely something for a car. I don't know where he is now, though.}
{1318}{}{I guess it's my own fault. Sorry I yelled at you, kid.}
