{100}{}{You see the stagecoach guard.}
{101}{}{Before you is the stagecoach guard.}

#Ответные реплики до первого разговора
{105}{}{Hey, get me a drink!}
{106}{}{Hey, what's taking so... Oh, I thought you were the waiter.}
{107}{}{If you're looking for friends, you came to the wrong place.}
{108}{}{If this is about a job, talk to Tuco.}
{109}{}{I'm just the guard. Talk to Tuco.}

#Первый разговор после приобретения квеста
{110}{}{Unless you're selling whores and booze, keep walking.}
{111}{}{Who are you?}
{112}{}{What are you doing here?}
{113}{}{Maybe I do have whores and booze. Who's buying?}
{114}{}{You're that unlucky guards of "Nevada Express", right?}
{115}{}{Then we have nothing to talk about.}
{116}{}{Bye.}

{120}{}{Customers, obviously! Why?}
{121}{}{Tuco put us on "leave" after the last clusterfuck of a job. Says he wants us at our best or not at all. But he says we'll get our jobs back once our nerves settle down.}
{122}{}{Uh, we made good money working for the Nevada Express. Why?}
{123}{}{Ah, damn... People are already talking about it, huh? Christ, you'd think it wouldn't be so hard to stay hidden in such a big city...}
{124}{}{So it's you. I want to know about the raided bus.}
{125}{}{Oh, just bugger off, alright? I'm trying to forget about that shit, not dredge it up again.}
{126}{}{Sorry, but you don't have a choice. I'm investigating on Tuco's orders.}
{127}{}{What? [they look at each other] Uh... Sure, whatever. But, you know, I wouldn't dig into this if I were you. These bikers, they're dangerous. They're not good enemies to have.}
{128}{}{Okay, give me the details.}

{129}{}{We were north of Lovelock when it happened. We were driving on the highway, as usual, when those bikers ambushed us at the turn. We were going so fast, that by the time we could stop the bus, they were shooting at us from all sides. They destroyed the robot immediately, and didn't take much longer for the rest of us.}
{130}{}{How'd they manage to destroy the robot?}
{131}{}{Can you show me where the raid took place?}
{132}{}{Why didn't you fight back?}
{133}{}{How did you survive?}
{134}{}{That's enough for now.}

{135}{}{They had energy weapons. They probably got them from military bases.}
{136}{}{Hey, I can't tell you that! That's classified! If Tuco trusts you, then maybe he'll give you the coordinates.}
{137}{}{No one expected this from the bikers. We've never fought each other before. Something's probably got them desperate if they're resorting to this.}
{138}{}{They took everything we had and let us go. They wanted us to tell everyone in Reno what happened, can you believe that? Bastards! We got picked up by a rescue patrol after about a day.}
{139}{}{You're lying!}
{140}{}{What the fuck?! [he stands up] You want to talk shit, motherfucker?! I'll kick your ass right out onto the street!}
{141}{}{You should be very careful what you say next. I have proof - the records from robot.}
{142}{}{Don't take it personally, I just wanted to make sure...}
{143}{}{I know you attacked the bus yourselves.}
{144}{}{What do you know, then? Get away from me!}
{145}{}{Okay, okay...}
{146}{}{You what? Fuck! We were so careful... [he leans in close] So what's the plan now, huh? What makes you think we won't kill you? What's one more body, huh?}
{147}{}{Right here, in front of everybody? I don't think so.}

{148}{}{Damn it... Alright, how about we buy that records off you? 2000 dollars - that's all we've got. It's more than you'll make from Tuco, believe me.}
{149}{}{First, tell me why you did it.}
{150}{}{It's a deal. Pleasure doing business with you.}
{151}{}{Hmm. I'll think about.}
{152}{}{Be smart about this. When you come to the right decision, I'll be here.}
{153}{}{Uh-huh.}

{154}{}{[He gives you the money, then puts the holodisk under the leg of his chair and jumps down on it, crushing it] That could have been you, you know. Be happy you took the smart option.}
{155}{}{Don't go looking for trouble. That could have been you, too.}
{156}{}{Yeah, yeah, whatever you say. I'm just here for the money.}

{157}{}{What do you care? Ah, hell... We were old paying old debts. We used to be mercenaries, and one of our old bosses gave the order to kill one of the passengers. We couldn't refuse - they'd have killed us.}
{158}{}{Who did you have to kill?}
{159}{}{Local businessman. He was coming back from Salt Lake City to arrange regular shipments of Nuka-Cola. Some people here weren't happy about it... You've got to watch your ass when you do business in Reno.}
{160}{}{Who wanted him killed?}
{161}{}{Are you crazy? I can't tell you that! It'd get me killed... You, too. Of course, I can't go back to the Nevada Express now. And I wanted to get out of the mercenary business...}

#Ответные реплики после принятия решений
{170}{}{Thanks for not giving us away. It was the right decision.}
{171}{}{Not a smart choice. I wouldn't stick around if I were you. People like you tend to have accidents around here.}
{172}{}{Well? Have you decided yet?}

#Female character
{1142}{}{Don't take it personally, I just wanted to make sure...}
{1154}{}{[He gives you the money, then puts the holodisk under the leg of his chair and jumps down on it, crushing it] That could have been you, you know. Be happy you took the smart option.}
{1170}{}{Thanks for not giving us away. It was the right decision.}
