{100}{}{You see a slave.}
{101}{}{You see a slave. Judging by his rough, dirty skin, he's been like this for a long time.}

{102}{}{After Master's death, the ranch's going to get deserted.}
{103}{}{What do we do without Master?}
{104}{}{How should I live if Master is gone?}

{105}{}{I don't know... I can't live any other way.}
{106}{}{Master is fair, but very cruel.}
{107}{}{Sometimes Master gets very angry. It's best to keep quiet then.}
{108}{}{I'd stay away from Master today.}