{100}{}{You see Mr. Chase.}
{101}{}{You see a distinguishly looking man. He eyes you like he's choosing a hat in a store.}
{102}{}{Score: }

###################################################################
#
# Getting acquainted
#
###################################################################

{110}{}{[You see a well-groomed, sharp-dressed man. His nice looks and demeanor contrast with the scar on his neck and ice in his eyes.] Hello there. Fancy a game of pool? I'm not looking to bet, just want a worthy partner.}
{111}{}{Can I ask you some questions about this city?}
{112}{}{Sure, I could go for a game.}
{113}{}{Sorry, I'm just here to admire the tables. Good luck.}

{114}{}{It seems suspicious to hang around the tables but not to be interested in a game, don't you think?}
{115}{}{Who says I'm not interested? Set up the balls, let's play!}
{116}{}{Well, if you feel so strongly about it, then I'll leave.}

{117}{}{I'm not in the mood to satisfy every passing onlooker's curiosity. But I do like to talk to the sound of balls colliding.}
{118}{}{Suit yourself, I'll play. Where's the chalk?}
{119}{}{And I'm not in the mood for that. Good luck, then.}

###################################################################
#
# The game
#
###################################################################

{120}{}{[He slowly chalks his cue] Some people think conversation distracts from a good game, but I think a person's true nature comes out at the table, whether they like it or not. Thus, one should watch themselves, even when playing for fun. [he nods at you] Go ahead and break. You are the guest, after all.}
{121}{}{One should always watch themselves.}
{122}{}{What are you trying to say?}

{123}{}{What a break! Joe Davis himself could scarcely have done better. Perhaps this game will be more interesting than I'd expected.}
{124}{}{[Continue]}
{125}{}{Just thinking out loud, that's all. Better to concentrate on the game - that's a poor break.}
{126}{}{[Continue]}

{127}{}{[He aims at the nearest ball] Well, here we are - in Reno, the city spared by Lady Luck. There's satisfaction for every kind of thirst here. Have you broken the bank at any of the casinos yet? Or are you the type that refuses to risk anything on a game of chance?}
{128}{}{I might gamble, but I only bet what I can afford.}
{129}{}{Gambling is too dangerous for me. It's a good way to lose everything you've got.}
{130}{}{I don't have anything against gambling, but I'd rather stay out of it.}
{131}{}{Easy money! Isn't it great? You get the thrill of victory *and* you get paid for it!}
{132}{}{That's a good approach. A gentleman should not have to borrow money for his vices, whether it is before the game or after. Good shot, by the way - I should have asked for a handicap. Do you mind if I smoke? Good... }
{133}{}{A decent answer. It's better to be overcautious, than the alternative. Interesting move, by the way - you've put me in a tricky position. Perhaps I should fancy a cigar, while I think about my move... }
{134}{}{Strange words. You don't strike me as someone that averse to risk. [he gives you an inscrutable look out of the corner of his eye] My turn... But first, I have to light up my cigar.}
{135}{}{Reno's furnaces run on the bodies of those who came seeking quick wins. The locals have learned not to deal with them, fearing they'll be drawn down... Say, that reminds me. How about a smoke?}

{136}{}{[He lights up a cigar, looking out the window at the prostitutes outside] There they are, always on duty. Well, I suppose some people are interested in that sort of game too, and there's no pleasure Reno won't turn into profit.}
{137}{}{We don't have them where I come from, but I sure wish we did!}
{138}{}{Wait... I could have sex *and* get paid for it? Why didn't anyone tell me?!}
{139}{}{A dangerous game. I wouldn't touch those girls even if I was wearing power armor.}
{140}{}{I don't know who's more degenerate - the whores, or the people who use them.}
{141}{}{Some people have no other choice. But personally, I'd rather steer clear of it.}
{142}{}{[He sighs] One has to be careful with women. Barker, Dillinger... A lot of great men have been laid low by this sort of thing. [he shoots] Ha! I learned that trick shot from... Well, it doesn't matter. He's just another one of Reno's beggars now.}
{143}{}{[He sighs] I'm no prude, but it's unseemly to offer oneself so cheaply. [he shoots] Ha! I learned that trick shot from... Well, it doesn't matter. He's just another one of Reno's beggars now.}
{144}{}{Hey, slow down, would you? Just kidding, well played. A good move.}
{145}{}{Really? Hmm. Hey, slow down, would you? Just kidding, good move. You had better options, though... Maybe you should have a drink to calm down.}
{146}{}{I suppose you're right. Not everyone can maintain themselves as skilled at profession as I could. Or you could. [he shoots] Bah, how did I miss?}
{147}{}{You should keep such thoughts to yourself. However legitimate they may be, coming from you they sound like sour grapes... Don't wag that cue, it's not a tail. Look, you fouled again.}
{148}{}{With such an attitude, you may earn more than you bargained for... Don't wag that cue, it's not a tail. Look, you fouled again.}
{149}{}{}
{150}{}{Don't you judge me. At least I earn my money honestly.}
{151}{}{[He raises his eyebrows in surprise] Hmm! You're right, I apologize.}

{152}{}{By the way, how about a drink after the game? Though, if you'd prefer to shoot a vein, this venue doesn't cater to those tastes. At the current rate, however, that will change sooner, rather than later.}
{153}{}{Chems are how life's losers pretend they're winners. I don't need them.}
{154}{}{Do I look like a junkie to you? Even if I do, well, you still shouldn't make assumptions.}
{155}{}{Chems can brighten up a dreary life, and it doesn't get much drearier than Reno.}
{156}{}{Whoa, what? I'll join you for a drink, but not more than that!}
{157}{}{[He nods in understanding] Well said. In this time and place, minds like ours are hard to find.}
{158}{}{There may be bright junkies, but I haven't met one yet. You're not high now, I hope? Otherwise I'd feel I have an unfair advantage.}
{159}{}{No, nothing like that. All I'm offering is a good drink in a decent bar. [he shoots, then scoffs] How embarrassing! How did I miss that shot?}
{160}{}{Hmm. Are you cold? I see you shaking. It's even affecting the game - how could you have missed that last shot?}

{161}{}{I do enjoy the sound of balls knocking together. Far better than the crack of gunshots, especially if the latter are meant for you. It's a shame that in Reno, quick hands are in higher demand than those who prefer... Alternative methods of solving problems.}
{162}{}{A quick wit and quick hands are more effective than a quick wit alone. Violence was the first standard of diplomacy, and often, it's the last.}
{163}{}{I try not to get into fights. When I do, I try to get out of them as soon as possible.}
{164}{}{Diplomacy is underrated. Why die for a cause when you can get someone else to die for you, and be grateful to do it?}
{165}{}{There's always demand for my methods. The only problem is, they're so quiet, it's hard to prove you have them.}
{166}{}{Yes, I think that weapon on your belt is not just for show. My money's on you, if you're up against one of the local rabble.}
{167}{}{An expert like yourself will never be without opportunity in Reno. Certainly, you'd rank above the local cannon fodder... }
{168}{}{Hmm. You don't look like Annie Oakley to me. If you're putting on airs, I'd suggest you file the front sight off your gun, in case the locals decide to shove it where you're speaking out of. They don't care for empty boasts.}
{169}{}{You can't run from all your problems, especially in Reno. There's a bullet waiting around every corner, and I doubt you can outrun them all.}
{170}{}{[He chuckles slightly] Diplomacy... I hadn't expected to hear that from you. You don't seem the type to rely on it.}
{171}{}{[He grins slightly, giving you a sidelong look] Sounds serious... But believe me, I've seen my share.}
{172}{}{[He listens carefully, moving the cue in his hand] By the way, the local gangs seem quiet today. Many of the locals think that throwing in with either of the two bosses will keep their heads above water. Well, I suppose bodies do float, if you're sitting on enough of them.}
{173}{}{It's survival of the fittest. If I have to, I'll throw in with one too.}
{174}{}{Everyone's looking at one or the other. A third party could swoop in before anyone knew what was happening.}
{175}{}{I'm waiting for someone who seems to know what they're talking about. Someone like you, for example.}
{176}{}{Anyone who could conquer Reno must be someone special. That's worth following.}
{177}{}{Hmm. You are determined, I'll say that. I don't approve of such methods, but I certainly respect your... Focus.}
{178}{}{[He chuckles] I want to see how you'd deal with this. Step aside, please... You'd have better results in this game if you used more finesse.}
{179}{}{You're awfully perceptive for one who's just arrived, aren't you? I'm not complaining... But I wonder how you do it.}
{180}{}{A very superficial assessment of the situation. That may impress the crowd, but not me... [he takes aim and deftly sinks the ball into a corner pocket] Ha! Today is my day, isn't it?}

{181}{}{It looks like we're approaching the endgame. Thank you for the fair play, I'm not used to it around here. In Reno, deceit and betrayal are the nature of things. Any loyalty is born of fear, and most people are waiting for their chance to flop over to someone stronger. [he sighs wistfully] But maybe my principles have become archaic in this modern world.}
{182}{}{The world has moved on. You should do the same, before you're left behind.}
{183}{}{My word is my bond. My reputation depends on my honesty.}
{184}{}{Partnerships can be more than the sum of their parts. It's easier said than done, but if the opportunity's there... Why not?}
{185}{}{It's true, my principles have cost me. This scar is just the most obvious evidence. But I'd rather die, standing by my principles, than live without them.}
{186}{}{Do you really think I'm so interested in your opinion? The weight of an individual is in their actions, not their words.}
{187}{}{It's a pleasure to deal with those such as yourself. It's a pity that so few nowadays know the value of values.}
{188}{}{Maybe your words are inspiring to the hopeless in the slums. But you'll find me a more demanding subject.}

{189}{}{[He comes around the table to shake hands with you] That was an excellent game! I may have lost, but I met one of the few worthy people in this city. It would be a pity if this were our only joint endeavor... }
{190}{}{Is that an offer?}
{191}{}{For now, you'll have to be happy with just the game. See you around.}
{192}{}{Game and match! I've still got it! ...Oh, you're still here? Thanks for the game, it was fun, but I think you've given all you have to offer. I suggest we not waste each other's time any further. Still, perhaps we'll meet again someday. People can surprise you from time to time... Anyway, good luck.}
{193}{}{[Leave.]}

{194}{}{Indeed... But this isn't the best place to talk. Follow me to somewhere more private.}
{195}{}{[Follow him.]}
{196}{}{Thanks for the game. See you around.}

###################################################################
#
# The quest
#
###################################################################

{200}{}{Let's cut to the point. Someone would like to listen in on the El Dorado owner's room. Of course, someone would want this done discreetly, so the owner could not learn of this.}
{201}{}{And who is this someone?}
{202}{}{No problem. Your money, my time. It'll get done.}
{203}{}{Uh, I'm having second thoughts. Bye now!}

{204}{}{We meet again.}
{205}{}{Hello. How about a game at the tables downstairs?}
{206}{}{Tell me about your proposal.}
{207}{}{And again we part.}
{208}{}{Remind me, what did you want again?}

{209}{}{So far as you're concerned, it's me.}
{210}{}{Good enough. I'm in.}
{211}{}{I don't work blind, sorry.}
{212}{}{Here are two bugs. One should be in his office itself, and the other should be in his bedroom. Place them somewhere they won't be discovered. Once you're done, return here. Good luck.}
{213}{}{[Leave.]}

{214}{}{I'm not here to play games. I've been told to deal with your problem.}
{215}{}{Yes, I've been told of you. I trust Mr. Luciano's judgment in you, but... I should know your character. And I've found the true nature of a person reveals itself at the pool table.}
{216}{}{I don't have time for this. Just tell me the job.}
{217}{}{If you say so. I suppose I have time for a game.}
{218}{}{We'll have to discuss this later. I have to go.}
{219}{}{Luciano sent me to deal with your problem.}
{220}{}{Interesting that fate continues to bring us together. This is what I wanted to talk to you about last time. I hope this time you'll be more accommodating.}
{221}{}{Things are different now. Let's get to it.}

{230}{}{[His hand brushes against its holster, seemingly by chance] I assume you're here to bring me good news?}
{231}{}{Yes, it's done. The bugs are planted.}
{232}{}{I've been thinking... You're being awfully careful about this. How much is my silence worth to you?}
{233}{}{No, I'm just checking in to make sure you're okay.}
{234}{}{[For some time, he tinkers with a radio receiver, listening to a pair of headphones. Finally he looks at you and nods.] My friend, I'm glad I was not wrong about you. And now, you'll be glad as well. [he slowly counts out your money] If you're interested in more work for the right man, seek out Oliver Luciano. He has an impressive ranch on the edge of town. Tell them Johnny Chase sent you.}
{235}{}{It's been a pleasure working with you, Mr. Chase.}
{236}{}{I thought you were an honest businessman, not some... Extorter! But I suppose this is my own fault, for not discussing the price beforehand.}
{237}{}{Thank you, Mr. Chase. I'll consider it.}
{238}{}{I agree. A small misunderstanding, but easy to fix. And don't forget to visit Mr. Luciano.}
{239}{}{Hmm. I suppose I misjudged you. But not so badly as you have misjudged me. [he grabs his gun]}
{240}{}{[Fight!]}
{241}{}{I have questions about the job.}
{242}{}{I'm not going to do your job for you. Leave, and don't test my finite patience.}
{243}{}{[Leave.]}
{244}{}{Bertolini is already dead. Is there any point to this?}
{245}{}{He is? Hmm, that's a surprise, but I suppose it explains the workers' behavior. Nevertheless, the job stands. Someone else will take his place, and it's only more important we are aware of this new person's new deals.}
{246}{}{There's no getting out of this job.}

#Women's replics
{1111}{}{Can I ask you some questions about this city?}
{1113}{}{Sorry, I'm just here to admire the tables. Good luck.}
{1119}{}{And I'm not in the mood for that. Good luck, then.}
{1123}{}{What a break! Joe Davis himself could scarcely have done better. Perhaps this game will be more interesting than I'd expected.}
{1125}{}{Just thinking out loud, that's all. Better to concentrate on the game - that's a poor break.}
{1127}{}{[He aims at the nearest ball] Well, here we are in Reno, the city spared by Lady Luck. There's satisfaction for every type of thirst here. Have you broken the bank at any of the casinos yet? Or are you the type that refuses to risk anything on a game of chance?}
{1130}{}{I don't have anything against gambling, but I'd rather stay out of it.}
{1132}{}{That's a good approach. A lady should not have to borrow money for her vices, whether it is before the game or after. Good shot, by the way - I should have asked for a handicap. Do you mind if I smoke? Good... }
{1141}{}{Some people have no other choice. But personally, I'd rather steer clear of it.}
{1144}{}{Hey, slow down, would you? Just kidding, well played. A good move.}
{1145}{}{Really? Hmm. Hey, slow down, would you? Just kidding, good move. You had better options, though... Maybe you should have a drink to calm down.}
{1154}{}{Do I look like a junkie to you? Hmm, maybe. Well, you still shouldn't make assumptions.}
{1157}{}{[He nods in understanding] Well said. In this time and place, minds like ours are hard to find.}
{1166}{}{Yes, I think that weapon on your belt is not just for show. My money's on you, if you're up against one of the local rabble.}
{1168}{}{Hmm. You don't look like Annie Oakley to me. If you're putting on airs, I'd suggest you file the front sight off your gun, in case the locals decide to shove it where you're speaking out of. They don't care for empty boasts.}
{1177}{}{Hmm. You are determined, I'll say that. I don't approve of such methods, but I certainly respect your... Focus.}
{1179}{}{You're awfully perceptive for one who's just arrived, aren't you? I'm not complaining... But I wonder how you do it.}
{1189}{}{[He comes around the table to shake hands with you] That was an excellent game! I may have lost, but I met one of the few worthy people in this city. It would be a pity if this were our only joint endeavor... }
{1190}{}{Is that an offer?}
{1192}{}{Game and match! I've still got it! ...Oh, you're still here? Thanks for the game, it was fun, but I think you've given all you have to offer. I suggest we not waste each other's time any further. Still, perhaps we'll meet again someday. People can surprise you from time to time... Anyway, good luck.}
{1220}{}{Interesting that fate continues to bring us together. This is what I wanted to talk to you about last time. I hope this time you'll be more accommodating.}
{1232}{}{I've been thinking... You're being awfully careful about this. How much is my silence worth to you?}
{1233}{}{No, I'm just checking in to make sure you're okay.}
{1234}{}{[For some time, he tinkers with a radio receiver, listening to a pair of headphones. Finally he looks at you and nods.] My friend, I'm glad I was not wrong about you. And now, you'll be glad as well. [he slowly counts out your money] If you're interested in more work for the right man, seek out Oliver Luciano. He has an impressive ranch on the edge of town. Tell them Johnny Chase sent you.}
{1236}{}{I thought you were an honest businesswoman, not some... Extorter! But I suppose this is my own fault, for not discussing the price beforehand.}
