{100}{}{You see a slave.}
{101}{}{This tough, tanned slave looks strikingly different from the others.}
{102}{}{Thank you, wanderer.}

{110}{}{Me no be knowing you, paleface.}
{111}{}{I don't know you either. Er, that is what you meant to say, right?}
{112}{}{Paleface? That's what the Cheyenne called me. Are you from there?}
{113}{}{I can't be bothered to try to decipher that. Bye.}

{114}{}{Me be Gishiyash the Quiet River, of the Cheyenne to the north. Me be slave of evil men, who took me when me be returning from hunting. Now they be making me watch brahmin. Me be hating it! Me being hunter, not shepherd!}
{115}{}{I have good news. Your brother Acabidab asked me to free you.}
{116}{}{Is it really so bad here?}
{117}{}{Would you like to go back home?}
{118}{}{We'll talk later.}
{119}{}{What if I helped you escape?}

{120}{}{Hmm, not be bad for every slave. Many here be happy with master telling them what to be doing. But me be born free! Me be proud! Me be Cheyenne, not slave!}
{121}{}{Cheyenne be waiting for me. Me be knowing this. Me be carrying Cheyenne in me soul. If... If me could find Cheyenne, we all be celebrating. But me be trapped in this cage instead.}

{122}{}{Mountain air be cold... But also be bringing rain. If you be wanting help me and Cheyenne, thank you. But it will not be easy. The guards be keeping me here, and me cannot be free while me be wearing this [he points to a shock collar around his neck]. Can you be helping?}
{123}{}{First, I'll talk to your master and ask him to let you go.}
{124}{}{I'll take care of the collar, then we'll fight our way out. How does that sound?}
{125}{}{Tell me about yourself again.}
{126}{}{Elder in the big house be smart. Maybe free me if he be getting more in return. But me be thinking he be wanting to own the sky itself.}
{127}{}{Other slaves be saying small house next to barn be controlling collars. Slaves be saying small house has "generator". Me no be knowing what be happening in there. But maybe you be knowing how to be stopping it.}
{128}{}{I have good news. You're free!}
{129}{}{[You go through the formalities of freeing the man and proceeding to the exit. He warily looks back at the guards, rubbing his hand over his now bare neck.] }
{130}{}{So, will you go back to the Cheyenne now?}
{131}{}{Me be going alone. Me be knowing how to be finding food and water on the way. If you be traveling to Cheyenne, please be finding me.}
{132}{}{Good luck on the road, Gishiyash.}
{133}{}{That's a pretty dumb idea, but it's your choice. If you get to your tribe in one piece, maybe we'll meet again. Goodbye.}
{134}{}{Before leaving, Gishiyash points out his tribe's location on your Pip-boy map.}

{140}{}{The guards are dead. Get out of here, faster.}
{141}{}{Me no be leaving. This collar be killing me if me be going too far.}
{142}{}{I turned off the collars. Take it off and climb over the fence.}
{143}{}{I'll help you get it off.}
{144}{}{This be changing things.}
{145}{}{[You easily disarm the collar.] }
{146}{}{[The slave defiantly tears off the collar.] }
{147}{}{Me be thanking you, but me must be asking you for another favor.}
{148}{}{[You carefully inspect the device. You come to the realization that it is well beyond your abilities.]}
{149}{}{Sorry, I need to check something out first. I'll be back.}

#Clothes for the escape
{150}{}{You be saving me, wanderer! When me be returning to Cheyenne, me be telling them of your help. Thank you!}
{151}{}{What do you need?}
{152}{}{Me must be going through Reno to escape. When me be hiding from gecko, gecko must not be seeing me. But when me be hiding from people, people must not be noticing me. Me be needing clothes like Reno people be wearing, so no one be knowing me be escaped from slave's cage.}
{153}{}{Let's see what I've got.}
{154}{}{I'll see what I can find. Hold on for a bit.}
{155}{}{Me be needing clothes that be making me look like Reno people. Do you be having that?}
{156}{}{[Give: }
{157}{}{]}
{158}{}{[Next]}
{159}{}{[Back]}
{160}{}{Hold on for a bit. I'll try and find something to help you.}

#Female version
{1102}{}{Thank you, wanderer.}
{1110}{}{Me no be knowing you, paleface.}
{1142}{}{I turned off the collars. Take it off and climb over the fence.}
{1150}{}{You be saving me, wanderer! When me be returning to Cheyenne, me be telling them of your help. Thank you!}