{100}{}{You see a butcher.}
{101}{}{You see a very strong man. He looks like he was born to be a butcher.}
{102}{}{Mr. Luciano's dead. Dead, you hear?! How are we going to run this place without him?}
{103}{}{You earn 100 experience points for learning about Mr. Luciano and his ranch.}

{110}{}{[You see a bald man with thick, strong hands. He tries to light a cigarette from the campfire and swears as he burns his fingers.]}
{111}{}{Heh, you could have guessed that would happen.}
{112}{}{Hey, take this lighter. It's a gift.}
{113}{}{[Keep walking]}

{114}{}{One more word, and you'll be lighting my cigarettes for life.}
{115}{}{Geez, sorry...}
{116}{}{[He deliberates for a moment, but decides to take your gift] Thanks. You're new around here, right?}
{117}{}{Uh, yes. I wanted to see the ranch from the inside.}

{118}{}{Yeah, I get that. It's pretty impressive, ain't it?}
{119}{}{Can I ask you some questions about the ranch?}
{120}{}{That it is. I'm going to keep looking around.}

{121}{}{Go ahead. Maybe I can tell you something.}

{122}{}{Tell me about this ranch.}
{123}{}{What can I say? It's not just our job, it's our home. We're all family here. And no one leaves the family... Mr. Luciano sees that as betrayal, and, heh, you don't want him to be mad at you. Not that you'd want to leave, but anyway. Reno will never stop needing food-and we have plenty. Now that we use the slaves for harvest, things are even better. Anything we can't use, we feed to the bramin until they're fit for slaughter. It always takes time for newcomers to get used to something, but for us it's a routine.}
{124}{}{So you supply food to the entire city?}
{125}{}{No, of course not. There are other farmers around Reno, and people say there is a tribe of Indians in the northeast that grows good crops. But Mr. Luciano is by far the biggest producer around. He is reliable and honest, and his ranch is the largest in the county.}
{126}{}{How is it even possible to run such a large ranch?}
{127}{}{It ain't easy.The land still remembers what mankind did to it sixty tears ago. Even today we have to deal with sick animals and crop failures. They say that for the first twenty years after the war there was no harvest at all, but I don't know how it really was. Mr. Luciano is the only one left here from those days. Word is that he and his wife, Maureen, were farming this land before the bombs even fell. I don't know how true these rumors are, but I'm sure in one thing: nobody knows farming better than Mr. Luciano. He was one of the first to use water exclusively from wells and not from open sources. He was one of the first to use slaves rather than hired laborers. This man's will is indestructible. He never gave up the ranch, even after his wife passed away.}

{128}{}{What can you tell me about Mr. Luciano?}
{129}{}{He's the head of the ranch. And I don't just mean that he pays us, I mean that he's the one who gives life to the place. Sure, he's old now, but he's still a man to respect. He's still standing, even after everything.}
{130}{}{"Even after everything"? What do you mean?}
{131}{}{He lived for his family, but now everyone from his family is gone. He's the last Luciano.}
{132}{}{Tell me his story.}
{133}{}{Tell me Mr. Luciano's story.}

{134}{}{I don't know if I am allowed to tell you much, but I will tell you what I think is important. He was one of five children in a poor family. Many of his kin died soon after the bombings - some in street shootings, some from radiation, some simply from starvation. At the time, Mr. Luciano was only about ten years old, but I'm sure he remembers those times well. He wanted a better life. He knew he was made for something greater.}
{135}{}{[Next]}
{136}{}{He worked hard all his life. It's amazing that he's alive now. He had heart attacks, hemorrhoids, hell, he even went blind on one eye - but his spirit is still like fire, even after losing his entire family. His wife died of cancer about two years ago, rest her soul. His first son died in childbirth. Doctors said it was due to the radiation he and his wife got from the soil while farming it. His second son was in his early twenties when he mysteriously died during the turf wars ten years ago. The killer was never found.}
{137}{}{[Next]}
{138}{}{Not many people could keep going after all that. But look at this ranch - it's a goddamn miracle, that's what it is! And Mr. Luciano made it happen. His food gave so much life to Reno. There's a lot of people that wouldn't be alive today if it weren't for him.}
{139}{}{What a grim story. I'm sure Luciano will stop at nothing for his business to thrive. What do you know about his involvement in the current war in Reno?}
{140}{}{Is this really a war? It's just some bandits from the wasteland trying to steal what we built. It's disgusting that someone in Reno is taking their side. Mr. Luciano is really standing up for something. He's fighting for his ranch, and that's more important than any power struggle going on in town. I don't know what he's up to, but the way I see it, we'd all be better off if those gangsters got out of town and never came back.}
{141}{}{Well, thanks for the story. It gave me food for thought.}
{142}{}{Sure. Take care.}
{143}{}{Take care.}