{100}{}{You see a guard.}
{101}{}{You see a guard of the ranch.}
{102}{}{Just give me a reason. I dare you.}
{103}{}{It's good to see you.}
{104}{}{Watch yourself on Mr. Luciano's property.}

#Для охранников на территории ранчо
{110}{}{Stop! I don't know you. What are you doing on Mr. Luciano's ranch?}
{111}{}{I'm, uh, the new guy. See, they gave me this jacket and everything!}
{112}{}{I work for Mr. Luciano.}
{113}{}{Who do you think you're talking to? I'm Oliver's new right hand! I go where I want!}
{114}{}{Ranch?! Wow, did I get turned around! Sorry, I'll just go back to the gate now.}
{115}{}{I've got my eye on you.}
{116}{}{Uh, sure.}
{117}{}{Sorry, no witnesses. [Attack]}
{118}{}{Fresh meat, huh? Okay, get to work. Just don't bother anyone - things are busy right now and we don't have time for questions.}
{119}{}{Uh, sure.}
{120}{}{Oh, I heard about you. Okay, go on. Just don't bother anyone - things are busy right now and we don't have time for questions.}
{121}{}{Oh... Right. My mistake. Sorry to have bothered you.}
{122}{}{Yeah, that's right!}
{123}{}{Many people work for the boss, but that doesn't give them the right to be here. Now turn around. Don't come back until Mr. Luciano gives you permission to be here.}
{124}{}{I don't know you. Around here, that means you'd better mind your manners. Now get the hell out of here!}

{125}{}{Okay, that's it! Get him!}
{126}{}{You'll have to catch me first!}

#Для внутренней охраны у кабинета Оливера
{150}{}{What the - THIEF! Everyone get in here!}
{151}{}{[Attack]}
{152}{}{[His hand goes for his gun] Sir, you can't be here. Leave the corridor, now.}
{153}{}{I just wanted to see your boss...}
{154}{}{Okay, whatever you say.}
{155}{}{You should've shot first. [Attack]}
{156}{}{You don't have an appointment. I would know. If you must see Mr. Luciano, speak to Machete. Now, please leave.}

#Female character
{1111}{}{I'm, uh, the new girl. See, they gave me this jacket and everything!}
{1114}{}{Ranch?! Wow, did I get turned around! Sorry, I'll just go back to the gate now.}
{1124}{}{I don't know you. Around here, that means you'd better mind your manners. Now get the hell out of here!}
{1125}{}{Okay, that's it! Get her!}
{1152}{}{[His hand goes for his gun] Ma'am, you can't be here. Leave the corridor, now.}
{1153}{}{I just wanted to see your boss...}