{100}{}{You see Oliver Luciano.}
{101}{}{You see a mature man wearing pajamas and soft slippers.}
{102}{}{Guards! Why is there an outsider in my office?!}
{103}{}{Another businessman down.}
{104}{}{Get out!}

{105}{}{My... Heart... How... Painful... }
{106}{}{Ugh... Marin... }
{107}{}{A-a-arrgh!!!}
{108}{}{*cough*... *cough*... }
{109}{}{A quiet and painful death caught up to the businessman near his bed.}

{110}{}{Machete said you wanted to see me. I'm ready to hear you out.}
{111}{}{I apologize for bothering you, Mr. Luciano. I'll come back when I have something that's worth your time, if you let me... }
{112}{}{I'm not in this best mood, so this had better be good.}
{113}{}{Come in, make yourself comfortable. I can find a spare minute for you.}

{114}{}{[Entering the room, your first impression is of cleanliness, order and silence. Suddenly, you hear a dull clang of jostled wine glasses and catch the faint scent of antiseptic in the air. A man in an old bathrobe stands with his back to you. He throws you a short, indifferent glance over his shoulder, slowly pours himself a glass of clean water from a jug, and then, gently holding the glass, he sits down at his desk.]}
{115}{}{Mister Oliver Luciano?}

{116}{}{You're fighting soon, right? You should know that I bet a lot of money on you and I intend to win.}
{117}{}{Thanks boss.}
{118}{}{I won't let you down, boss.}
{119}{}{You don't understand, blockhead. I just want to win.}

#Встреча с Райтом
{120}{}{Mr. Luciano, Theodore Wright offered you a meeting for - }
{121}{}{I don't want to have anything to do with him.}
{122}{}{But sir! Mr. Wright is offering you a very good deal.}
{123}{}{Well, I can see you've made up your mind.}

{124}{}{Perhaps. And under other circumstances I'd consider it, but not from the devil's errand-boy.}
{125}{}{What do you mean? Mr. Wright's a businessman, not the devil!}
{126}{}{Don't play dumb. I'm not talking about him. You know exactly who I'm referring to.}
{127}{}{Do you have a problem with my second boss?}
{128}{}{I find your hypocrisy repulsive. Leave. Now. Before I do something you'll regret.}
{129}{}{Well, you've made yourself clear, sir. I won't bother you again.}

{130}{}{I thought you worked for *me*. You'd better not have any more surprises like this one up your sleeve. I'm disappointed, but our relations with Wright have been tense for far too long. Tell him I'm ready to arrange a meeting... Solely because I trust you.}
{131}{}{Thanks, boss.}
{132}{}{That's great.}

{133}{}{Well, our relations with Wright have been tense for far too long. But I don't understand, why did he send me such a... Dubious little lickspittle rather than a member of his family?}
{134}{}{Because, unlike his people, I'm not being watched. Mr. Luciano, you know how dangerous it is to operate out in the open. Mr. Wright chose me for my discretion.}
{135}{}{Yes, I may not be a member of the family, but Mr. Wright felt comfortable entrusting me with such a sensitive task based on my sterling reputation in town.}
{136}{}{So will you agree to the meeting?}

{137}{}{Who wrote this persuasive speech? I doubt it was you. Tell Wright that such fine words sound ridiculous coming out of your lips.}
{138}{}{Well, I'll pass your rejection on to Mr. Wright.}
{139}{}{I'll admit, you think things through better than most underlings. Perhaps that's why Wright picked you for this job, instead of a family member. After all, his sons together have less brains, than a one-headed Brahmin. Okay, you win. Tell Theodore that I'm ready to meet.}

{140}{}{You reputation isn't worth a bucket of brahmin piss to me. Leave and tell Wright that he should send a better intermediary next time.}
{141}{}{Because, unlike his people, I'm not being watched. Mr. Luciano, you know how dangerous it is to operate out in the open. Mr. Wright chose me for my discretion.}
{142}{}{No. I'm not interested in negotiating with a businessman who's fallen so low that he sends some pathetic flunky instead of his own sons.}
{143}{}{You're refusing because of me? Well, at least I tried... }
{144}{}{Hey, easy there! I'll have you know I've got a bright future waiting for me here in Reno.}
{145}{}{I already told you my decision. You've done nothing to change my opinion.}
{146}{}{With all due respect, sir, that's a mistake. Believe me, Mr. Wright's offering you an excellent deal.}
{147}{}{I'll send your answer to Mr. Wright. Thanks for your time.}
{148}{}{Alright. Well, I need to go.}

#Попытка напроситься на работу
{150}{}{Mr. Luciano, I want to work for you.}
{151}{}{Lots of people *say* that. But when it comes to actually doing work, most of them are are about as useful as brahmin shit. And just like brahmin shit, the ones who are all talk end up in the compost heap... If you catch my drift.}
{152}{}{I hear you. So what about the job?}
{153}{}{Listen, I don't accept just anybody. I need someone with impeccable credentials. The question is, do you have them?}
{154}{}{Well, now that you and Mr. Wright are working together, I think I can work for you too, without dividing my loyalties.}
{155}{}{I'm convinced. I'll hire you, but know this: I am not a forgiving man. And if you fail me, my people will nail your ass to the wall, even if they have to chase you into the depths of hell to do it.}
{156}{}{Of course. No problem.}
{157}{}{I already helped you out with Canary. Isn't that enough?}
{158}{}{Mr. Chase told me to come speak to you about a job. I'm sure he wouldn't do that without good reason.}
{159}{}{I don't know anyone in Reno who can vouch for me.}
{160}{}{[Raises his voice] Then FIND SOMEONE, you dolt! Get off your lazy backside and do some work. I appreciate people who earn a living by the sweat of their own labor. Now get out of my house.}
{161}{}{[Leave.]}
{162}{}{I don't need someone like you. I can't stand political whores who move from one master to another. I need LOYALTY! Not just to me, but to my ideals. Now get the hell out.}
{163}{}{[Leave.]}
{164}{}{I've got work that needs doing, but I can't stand political whores who move from one master to another. I need LOYALTY! Not just to me, but to my ideals. Remember that and get the hell out.}
{165}{}{Not necessary. Just look at me - I've got enough experience that I don't need any recommendations.}
{166}{}{So, my old friend Johnny Chase needs help in a very delicate matter. Find him at the El Dorado casino and help him get the job done quickly.}
{167}{}{I'm heading for Mr. Chase now.}
{168}{}{Alright, I'll see what I can do.}
{169}{}{Stop. I'm not done. This is important: be polite with Chase and don't you dare lie to him. We don't tolerate political whores who flirt with anyone they meet for their meal ticket. That's all. [he makes a hand gesture for you to leave]}
{170}{}{[Leave.]}
{171}{}{I've got something to tell you about the job.}
{172}{}{Did you complete your task?}
{173}{}{Eh, I just wanted to clarify something... }
{174}{}{[Raises his voice] I told you, ENOUGH! Now start using your few remaining brain cells and do the goddamn job!}
{175}{}{[Leave.]}
{176}{}{That's it, job done.}
{177}{}{[He sighs] Perhaps it is. But I've heard that Chase happened to have an "accident". I don't believe in "accidents" and you didn't even bother to give me an explanation. Guards!}
{178}{}{[Fight.]}
{179}{}{[Leave quietly.]}
{180}{}{[He nods] I hope you were paid in full. I want an honest partnership.}
{181}{}{Yes, Mr. Luciano. Pretty much.}
{182}{}{Well, since you helped my old friend Chase, we can talk about more "serious" matters.}
{183}{}{I'm listening.}
{184}{}{I've got bad news: Chase happened to run into an "accident", and I... }
{185}{}{I don't believe in "accidents" and you didn't even bother to give me an explanation. Guards!}
{186}{}{I believe you. I can see you're all about business. You don't need to suck up to the powerful to seek "friendship." I like it. I'll hire you, but know this: I am not a forgiving man. And if you fail me my people will nail your ass to the wall, even if they have to chase you into the depths of hell to do it.}
{187}{}{The ranch's administrator will give you the details.)}

#Раб из Уран-Сити
{190}{}{Mr. Luciano, I want to buy one of your slaves - the name's Joseph.}
{191}{}{That's it? Speak to Machete, he handles the little things.}
{192}{}{Ugh... }
{193}{}{I'm a man of my word. I promised to give you my assistance in exchange for your help. And this time it won't be just words. You can take this slave, I'll give the order. Go to the paddock and tell the guards that Joseph is yours.}
{194}{}{Thank you, Mr. Luciano.}

{195}{}{Mr. Luciano, I know there's a Cheyenne slave in your possession. I'd like to buy him.}

#Первый квест
{200}{}{That information you helped us gather was useful. But I still don't know how trustworthy you are, so you'll have to work a bit to gain my confidence.}
{201}{}{What do I need to do?}
{202}{}{Your main objective: steal the money stockpiled in Bertolini's safe. This is a difficult task, but I think you can handle it. After all, you've already managed to install bugs in his office, so I'm sure you'll find a way to the safe.}
{203}{}{Uh, rob a casino? You low on money or something?}
{204}{}{Understood. Something else?}
{205}{}{[He frowns] I'm not a thief! I work for a living. But perhaps you're confused by my request... Well, to clear any doubts, I'll explain myself. I don't need the money itself as much as I need Bertolini to go broke. He collected this sum for a reason.}
{206}{}{Understood. You said that this is the main goal. There are secondary objectives?}
{207}{}{Once Bertolini loses his savings, it will still take some time for his business to unravel. When that happens all his people will boil up like ants running out of a devastated anthill. We must postpone this moment of crisis as long as possible.}
{208}{}{Can you advise something specific?}
{209}{}{Talk with Machete about it. These details are beneath me.}
{210}{}{Alright. Steal the money and sabotage a casino. Got it.}
{211}{}{You'll be paid upon completion. Now get it done.}
{212}{}{[Leave.]}
{213}{}{The job's done - I've stolen Bertolini's money from his safe. Here's the suitcase.}
{214}{}{Excellent work! Since you've done the job quietly, I'll pay you more than I intended. [he gives you $2000] }
{215}{}{Good job! But I heard that Bertolini had an unfortunate "accident". That's not what I wanted. You got the job done, though, so here's your payment, $1000. But I have no more work for you.}
{216}{}{[Leave.]}
{217}{}{Appreciate that, boss.}

{218}{}{But this doesn't cancel your secondary objective - ruin the casino's reputation. Did you handle that?}
{219}{}{Yes, I've sabotaged the casino.}
{220}{}{Yes, I was able to shame a casino in front of ordinary citizens.}
{221}{}{Not yet, I'm working on it.}

{222}{}{This is good news. That means I have time to prepare... So, time for you to get paid.}
{223}{}{Thank you.}
{224}{}{}
{225}{}{[He counts $350] I would continue to use your services, but I hear that you've chosen to fight on the other side of the barricade, so I no longer want anything to do with you. Get the hell out.}
{226}{}{[He counts $350] I'm not happy. Sure, you managed to steal the money and cover your tracks, but you made a huge mistake: Bertolini wasn't supposed to die. I can't have someone so reckless on my payroll. Get the hell out.}
{227}{}{[He counts $500, hands you the money and nods to Bertolini's suitcase] Good pay for good work. Now, I have another plan and I need you to make it happen.}
{228}{}{[Leave.]}
{229}{}{What's next?}
{230}{}{I want you to start a war between Stryker and Thompson. Sabotage their territory so they blame each other. Machete will give you the details.}
{231}{}{That's all?}
{232}{}{Yes, all... You're still here?}
{233}{}{Already leaving, Mr. Luciano.}

{234}{}{Good work! Also, I heard about some "commotion" at the casino. I don't know if you had anything to do with it, but I'll warn you once - be careful while you're working for me. Since you got the job done, though, I'll pay you what I'd planned to. [he gives you $1000]}

#Второй квест
{240}{}{Strangely enough, it appears that Thompson is dead, so there's no more need to complete the job.}
{241}{}{Strangely enough, it appears that Stryker is dead, so there's no more need to complete the job.}
{242}{}{Mission accomplished. Stryker and Thompson won't discover the truth any time soon.}
{243}{}{Well, it means that your service was less significant than I expected. Therefore, you'll receive only half the pay. And don't you dare try to argue with me. Stryker and Thompson were an important force in this town. Without them, Reno will fall into chaos, and we're not prepared for that yet.}
{244}{}{What do you mean?}
{245}{}{[He counts your payment] Striker and Thompson were an important force in this town. Without them, Reno will fall into chaos, and we're not prepared for that yet.}
{246}{}{What are you talking about?}
{247}{}{Until now, my ranch has been self-sufficient. But recent years have drained our resources. We don't have a lot of money for the exchange and we're being watched. The powers that be are oppressing us from all sides. They won't allow us to develop further.}
{248}{}{Further?}
{249}{}{I've used your services in order to regain my former influence in the city. There are two ways to do this - weaken your rivals or become stronger yourself. You've done the first part, it's time to take care of the second.}
{250}{}{What do I need to do?}
{251}{}{Your task is to make a deal with a caravan on the outskirts of the town. Machete has all the details.}
{252}{}{I'll talk to him.}

#Завершение всей линейки квестов
{260}{}{Come in, from now on you're a welcomed guest in my home. I've already heard how the meeting went. I'm glad you managed not only to get the goods, but also to save my reputation. After all, perhaps, these merchants will be useful to me in the future. Here's your payment for a job well done.}
{261}{}{Good.}
{262}{}{Come in, there's something we need to discuss. Technically, you got the job done - I received the goods and Bertolini's casino was left without equipment. But I was hoping that you could get this done without bloodshed. After all, these suppliers could've been useful to me in future. However, I won't reproach you for the violence since you were the man on the ground and it was your call. You could have done better, but you still earned your pay.}
{263}{}{Good.}
{264}{}{Come in, there's something we need to talk about: your cowardice and stupidity! You think you can come in here with your head bowed and receive charity? You show your face here after blowing such an important transaction? Your idiocy is astonishing. Just thank God that I haven't shot you already! [he is consumed by mad coughing and choking, clutching his chest, before he recovers] Fortunately for you, my people have frightened off the convoy, and they fled into the the wasteland. The goods remained with me. Out of respect for what you've done before, I'll let you go in peace. New get out!}
{265}{}{[Leave.]}
{266}{}{Perhaps someday I'll help you, if you have problems. And finally, I'd like to make you my consigliere, if you don't mind. This is a prestigious position, very respectable. I recommend that you not refuse.}
{267}{}{Thank you, Mr. Luciano, I would be honored.}
{268}{}{Thank you, boss, but that's too much responsibility for me. I have to turn you down.}
{269}{}{[He nods] I understand. Not everyone takes to such work with ease. If you honestly think you're unsuitable, I can respect that. I won't insist. You can go.}
{270}{}{Goodbye, Mr. Luciano.}
{271}{}{I'll tell the news to all of my men on the ranch and in town. My name will give you certain privileges in Reno. Talk to Machete first, he'll help you out.}
{272}{}{Thanks, Mr. Luciano. Goodbye.}
{273}{}{And I appreciate your help. But recently I found out that you're playing a double game. Obviously you're not driven by faith in man or his ideas, but by the smell of money. My competitor must have paid you well. Now you can meet your old age in comfort... But I've talked too much. You know where the door is. From now on there's nothing tying you to this place.}

#Крыша для концерта в Коттон-клубе
{300}{}{I'm a representative of the Cotton Club. We'd like to make a deal with you to protect concerts at the club.}
{301}{}{A concert? This is inspiring news. If the club needs security, I can offer some. But I'd like to receive more benefits in exchange. Tell the owner that I'll help him if he'll pay me 15% of the revenue from each day of the concert and also give me the sole contract to supply the club with food. He'll also have to stop paying protection money to Thompson.}
{302}{}{We agree to these conditions.}
{303}{}{We need to think about that offer.}
{304}{}{You made the right decision. I'll send my men to work out the details.}
{305}{}{Thanks, that's all.}

#Female character
{1110}{}{Machete said you wanted to see me. I'm ready to hear you out.}
{1119}{}{You don't understand, you dolt. I just want to win.}
{1130}{}{I assumed that you worked for *me*. How many more unpleasant surprises do you have up your sleeves? While I'm disappointed, the truth is that our relations with Wright have been tense for far too long. Tell him I'm ready to arrange a meeting... Solely because I trust you.}
{1143}{}{You're refusing because of me? Well, at least I tried... .}
{1157}{}{I already helped you out with Canary. Why don't you do me a favor in return?}
{1158}{}{Mr. Chase recommended that I speak with you about a job. I'm sure he wouldn't have done that without a reason.}
{1160}{}{[He raises his voice] Then FIND SOMEONE, you dolt! Get off your lazy backside and do some work. I appreciate people who earn a living by the sweat of their own labor. Now get out of my house.}
{1169}{}{Stop. I'm not finished. This is important: be polite with him and don't you dare lie to him. We don't tolerate political whores who flirt with anyone they meet for their meal ticket. That's all. [he makes a hand gesture for you to leave]}
{1172}{}{Did you complete the job?}
{1182}{}{Well, since you helped my old friend Chase, we can proceed to a more "serious" conversation.}
{1195}{}{Mr. Luciano, there's an Cheyenne slave in your possession. I'd like to buy him.}
{1215}{}{Good job! But I heard that Bertolini ran into an "accident". I didn't ask you to kill him. Look, you got the job done, so here's your payment, $1000. But I have no more work for someone so reckless.}
{1218}{}{But what about your secondary objective - ruin the casino's reputation? Did you handle that, too?}
{1225}{}{[He counts $350] I would like to keep using your services, but I hear that you've chosen to fight on the other side of the barricade. So there's nothing else for us to talk about. Get the hell out.}
{1226}{}{[He counts $350] Despite the fact that you managed to steal the money and cover your tracks, you made a big mistake. You weren't supposed to kill Bertolini! I can't have his murderer associated with my organization, so I want nothing more to do with you. Leave.} 
{1249}{}{I've used your services in order to regain my former influence in the city. There are two ways to do this - weaken your rivals or become stronger yourself. The first part you've done, now it's time has come to take care about the second... }
{1264}{}{Come in, there's something we need to talk about: your cowardice and stupidity! You think you can come in here with your head bowed and receive charity? You show your face here after blowing such an important transaction? Your idiocy is astonishing. Just thank God that I haven't shot you already! [he is consumed by mad coughing and choking, clutching his chest, before he recovers] Fortunately for you, my people have frightened off the convoy, and they fled into the the wasteland. The goods remained with me. Out of respect for what you've done before, I'll let you go in peace. New get out!}
{1268}{}{Thank you, boss, but that's too much responsibility for me. I have to refuse.}