{100}{}{You see the butcher.}
{101}{}{You see a very strong man. He looks like he was born to a butcher.}
{102}{}{Mr. Luciano's dead. Dead, you hear that?! How are we going to run this place ourselves?}
{103}{}{You earn 100 experience points for learning about Mr. Luciano and his ranch.}

{110}{}{[You see a bald man with thick, strong arms. He tries to light his cigarette with the campfire and swears when he burns his fingers.]}
{111}{}{Heh, you could have guessed that would happen.}
{112}{}{Hey, take this lighter. It's a gift.}
{113}{}{[Keep walking.]}

{114}{}{One more word, and you'll be lighting my cigarettes for life.}
{115}{}{Geez, sorry...}
{116}{}{[He deliberates for a moment, but decides to take your gift] Thanks. You're new around here, right?}
{117}{}{Uh, yes. I wanted to see the ranch from the inside.}

{118}{}{Yeah, I get that. It's pretty impressive, ain't it?}
{119}{}{Can I ask you some questions about the ranch?}
{120}{}{That it is. I'm going to keep looking around.}

{121}{}{Go ahead. Maybe I can tell you something.}

{122}{}{Tell me about this ranch.}
{123}{}{What can I say? It's not just our job, it's our home. We're family here. No one leaves from family ties... Mr. Luciano sees that as betrayal, and, heh, you don't want him mad at you. Now that you'd want to, anyway. Reno's never gonna stop needing food, and we've got plenty of it. Things are even better now that we're using slaves to harvest crops. Whatever we can't use, we feed to the brahmin, until they're good to slaughter. It always takes the newbies some time to get used to things, but for us it's just ordinary.}
{124}{}{So you make food for the entire city?}
{125}{}{No, of course not. There's other farmers around Reno, and they say there's a tribe of Indians to the north-east that grows good harvest. But Mr. Luciano's definitely the biggest producer around here. He's reliable and honest, and his ranch is the biggest around.}
{126}{}{How is it possible to run such a large ranch?}
{127}{}{It ain't easy. The land still remembers what humanity did to it sixty tears ago. Even today we've got to deal with sick animals and crop failures. They say the first twenty years after the war, there were no crops at all, but I wouldn't know. Mr. Luciano's the only one who's been here since those times. They say he and his wife Marin worked this land since before the bombs fell. I don't know how much of that is true, but I'll tell you this - no one knows the farming business like Mr. Luciano. He was one of the first to use water exclusively from wells rather than open sources. He was one of the first to use slaves, too, instead of hired hands. The man's will is unbreakable. He never gave up on this ranch, even after his wife passed away.}

{128}{}{What can you tell me about Mr. Luciano?}
{129}{}{He's the head of the ranch. And I don't just mean he pays us, I mean he's the one that gives life to this place. He's old now, of course, but he's still a man to be respected. He's still standing, even after everything.}
{130}{}{"Even after everything"? What do you mean?}
{131}{}{He lived for his family, but everyone from his family is gone. He's the last Luciano.}
{132}{}{Tell me his story.}
{133}{}{Tell me Mr. Luciano's story.}

{134}{}{I don't know much I'm allowed to tell you, but I'll give you what I think is important. He was one of five children in a poor family. A lot of his family died soon after the bombs - some from street fighting, some from radiation, some just from hunger. Mr. Luciano was only about ten at the time, but he remembers those times. He swore he'd rise above that life. He knew he was made for something more.}
{135}{}{[Next]}
{136}{}{He worked hard all his life. It's amazing he's alive now - he's had heart attacks, hemorrhoids, hell, he's even going blind - but he's got spirit like fire, even after losing all his family. His wife died of cancer about two years ago, rest her soul. His first son died in childbirth. Doctors said that was due to the radiation he and his wife picked up from the soil when they worked the soil. His second son was about twenty when he died mysteriously during the war between businesses a decade back. No one ever found the murderer.}
{137}{}{[Next]}
{138}{}{Not many people could keep going after all that. But look at this ranch - it's a goddamn miracle, is what it is! And Mr. Luciano made it happen. His food has given so much life to Reno. There's a lot of people that wouldn't be alive today if it weren't for him.}
{139}{}{What a grim story. I can tell Luciano stops at nothing for his business. What do you know about his participation in the current war in Reno?}
{140}{}{Is it war, really? It's just some gangsters from the wasteland trying to steal what we've built. It's disgusting that anyone in Reno takes their side. Mr. Luciano actually stands for something. He fights for his ranch, and that's more important than whatever struggle for power that is going on in the city. I don't know what he's up to, but if you ask me, we'd all be better off if those gangsters got out of the city and never came back.}
{141}{}{Well, thanks for the story. It's given me food for thought.}
{142}{}{Sure. Take care.}
{143}{}{Take care.}