{100}{}{You see the administrator.}
{101}{}{You see a stern-faced manager. She has a clear answer to everything.}
{102}{}{I'm here for business, not chitchat. If you don't have anything important to say, then leave.}
{103}{}{Are you deaf or just simple? For as long as you work for Mr. Luciano, you will answer when I speak to you.}
{104}{}{Without Oliver, it'll be harsh times for the ranch. But we've prepared for this.}

#Приобретение квеста
{110}{}{I'm guessing this isn't the helpdesk. What do you do here?}
{111}{}{Well then, I'll just leave.}
{112}{}{I handle the day-to-day administration, paperwork, and other business that Mr. Luciano does not have time for. In practice, that means I handle all negotiations with our usual traders and vendors. Contracts, payments, everything. As you can imagine, that's a lot of work, I would *really* like to get back to it.}
{113}{}{What if I would help you? Maybe I'd make a great negotiator, myself.}
{114}{}{Hmm. [she raises one eyebrow] Maybe you could... You understand there's more to the market than just supply and demand, right?}
{115}{}{Yes, and right now, the Reno market is in a bad state.}
{116}{}{Reno was a great place to do business, once. But then the businesses went to war, followed by the criminals. What we have today doesn't even compare to the old times.}
{117}{}{Before the bombs, you mean?}
{118}{}{No, no. [she waves her hand] I'm talking about the "Golden Age" of Reno. It wasn't so long ago... But that's not the point. I need information. Are you interested?}
{119}{}{What's the job?}
{120}{}{[She sighs in exasperation] Whatever sort of trader you are, we're not looking for new contracts. We're already selling off all of our product, except for that which we keep for ourselves.}
{121}{}{Find out where Thompson and Stryker are getting their food supply. It's almost certainly from vendors that work with us, but we'll pay 300 bucks for details.}
{122}{}{ And I'll recommend you to Mr. Luciano, too, if you want to work for him.}
{123}{}{Sounds reasonable. I'll do it.}
{124}{}{I don't think I can do it.}
{125}{}{Good. Hurry up and let me get back to work.}
{126}{}{Fine.}
{127}{}{You'll be paid when you bring us the information. Until then, let me concentrate on my work.}

{128}{}{Why can't you find this information yourself?}
{129}{}{It's none of your concern, but most businesses in Reno keep their deals secret. We can't just ask who's selling to whom.}

#Диверсия у ресторана
{140}{}{I, uh, overheard a conversation in a restaurant. They say something's wrong with your meat!}
{141}{}{Tch! Do you honestly think I don't know about this already, or are you just trying to piss me off? I'm sure it's baseless rumors from either the restaurant owner or our political enemies. Too bad Oliver now thinks there's a problem on the ranch. Or maybe he doesn't think that, and he just wants an excuse to discipline us. Either way, we already got a good beating.}
{142}{}{Hmm, shady business. Well then, see you around.}

#Сдача квеста
{150}{}{I have a list of Thompson and Stryker's transactions. It should contain the information you need.}
{151}{}{Well don't waste my time, give it to me!}
{152}{}{[Hand it over.]}
{153}{}{Hmm... Dates, suppliers, locations, transactions... I'm impressed. I didn't think gangsters had the brainpower for such meticulous record-keeping. Good work. Here's 300 dollars, as we agreed. If you're looking for more work, I'll put in a good word with Mr. Luciano.}
{154}{}{[Next]}
{155}{}{I have another proposition for you. According to this data, both gangs get some of their food from local businessmen and caravans. I don't know anything about these suppliers - find out who they are and why they're so devoted to these... Revolutionaries.}

#Female character
{1140}{}{I, uh, overheard a conversation in a restaurant. They say something's wrong with your meat!}
