{100}{}{You see a Reno local.}

#Временные плавающие реплики
{110}{}{This day in Reno is marked by the hand of Devil.}
{111}{}{We're all in this together. Don't we understand that?}
{112}{}{Someone's going to die tonight. I can feel it.}
{113}{}{I'm so sick of the noises at night...}
{114}{}{If I ever the chance, I'll move to hell. It has to be better than this.}
{115}{}{I can't stop thinking these are Reno's last days.}
{116}{}{We have no collars, but we still live like slaves.}
{117}{}{Damn this war!}
{118}{}{}
{119}{}{}

#Попы'ка 'олкну'ь, когда нпс с'ои' на с'ар'овом гексе
{120}{}{This is my home! Stop pushing me around or you will regret it!}
{121}{}{If I spill a one drop of my soup because of you...}
{122}{}{Find somewhere else to do that sort of thing!}
{123}{}{Don't do that!}

#Попы'ка заговори'ь
{129}{}{I miss my husband... *sobs* after that drug dealer died, he had nowhere else to buy his medicine...}
{130}{}{Don't mind them, they're always fighting. Just give them a reason.}
{131}{}{How would you like it if I barged into YOUR home and started asking questions?}
{132}{}{I have nothing to tell you.}

{133}{}{I'd love to chat, but I'm already late to the night club...}
{134}{}{It's... You! Wow! I'm a big fan - I catch your dances whenever I can!}
{135}{}{Huh? Don't bother me. I lost my ticket to the night club, and I'm looking for it.}
{136}{}{Hey, good performance! I caught it at Mom's club. Nice place...}

{137}{}{Do you mind? I'm having my breakfast.}
{138}{}{Leave me alone. I'm eating lunch.}
{139}{}{Don't interrupt my dinner.}

{140}{}{You're not welcome here.}
{141}{}{I don't even want to touch the doorknobs in this place! Also, I dropped my bobby pin in the washroom sink. Ew!}
{142}{}{Oh, how nice of you! Thanks!}
{143}{}{This lady definitely likes you.}

#Звезда сцены
{145}{}{I must a dreaming! A celebrity, here, in my home?!}
{146}{}{My god, it's you! Can I have your autograph?}
{147}{}{It's an honor, seeing you!}
{148}{}{I saw your latest performance. Amazing!}
{149}{}{}

# 1. LOOK, MALE (WTG)
{150}{}{You see a ragged-looking man. He looks bored.}
{151}{}{You see a ragged-looking man. His eyes are dull.}
{152}{}{You see a ragged-looking man. He looks hung over.}
{153}{}{You see a ragged-looking man. He looks a little tipsy.}
{154}{}{You see a ragged-looking man. He gives you an irritated glance, and then ignores you.}
{155}{}{You see a ragged-looking man. He looks angry.}

# 2. LOOK, FEMALE (WTG)
{160}{}{You see a ragged-looking woman. She looks bored.}
{161}{}{You see a ragged-looking woman. Her eyes are dull.}
{162}{}{You see a ragged-looking woman. She's staring a thousand miles away.}
{163}{}{You see a ragged-looking woman. She looks a little drunk.}
{164}{}{You see a ragged-looking woman. She gives you an irritated glance, and then ignores you.}
{165}{}{You see a ragged-looking woman. When she catches your eye, she sneers.}

#Сладкая парочка в номере Сильвер, о'ве'ные реплики
{200}{}{We're busy.}
{201}{}{What are you, blind? Get out!}
{202}{}{Leave us alone or we'll call security!}
{203}{}{Watch yourself. I'm a very respected customer here.}
{204}{}{Don't watch me, you freak!}
{205}{}{I don't do gang-bangs, okay?}
{206}{}{Get out of my room!}
{207}{}{What the hell are you doing here?}
{208}{}{Rude!}
{209}{}{Stop it!}
{210}{}{What are you looking at?}
{211}{}{Do you mind?}
{212}{}{Get out of our room!}
{213}{}{You looking to start up a threesome?}
{214}{}{Get the fuck out, pervert!}
{215}{}{What is your problem?}

{216}{}{I'm busy.}
{217}{}{I'm too tired...}
{218}{}{Get out before I get *really* pissed!}
{219}{}{Find yourself another one.}
{220}{}{She's mine.}

#Female character
{1214}{}{Get the fuck out, bitch!}
