{100}{}{You see a madam.}
{101}{}{You see a madam named Betty Paige.}
{102}{}{You successfully changed the contraceptive.}
{103}{}{You enjoy an entire hour of passionate, tireless sex. The whore teaches you everything she knows.}
{104}{}{It's not until the lights turn on that you see a vicious skin disease affecting the prostitute's genitals. You can only hope you didn't catch it.}
{105}{}{It's not until the lights turn on that you see a vicious skin disease affecting the prostitute's genitals. Hopefully, your protection worked.}
{106}{}{It's not until the lights turn on that you see a vicious skin disease affecting the prostitute's genitals. But today, you got lucky.}
{107}{}{Soon, streets will talk of the madam who tragically met her end to a sudden, mysterious "disease".}

#Починка фонаря
{110}{}{Thanks for the light. I'm sick of the darkness - at some nights you can't tell customers from thugs...}
{111}{}{ If you want one of my girls, I'll give you a small discount for your trouble.}
{112}{}{ Hmm. You're still here, even after your illness? I've lost a lot of my own girls to it. Here, take a bit of money. Treat yourself to something nice.}
{113}{}{Thanks.}

{114}{}{You sure know how to bring in a customer. Let's see what you've got in "stock".}
{115}{}{Thank you, but not today.}

{116}{}{Hey, baby, get the hell out of here! No one would fuck your ugly ass. Even whores have limits!}
{117}{}{Have you made up your mind?}
{118}{}{I'm looking. Do you have any suggestions?}
{119}{}{Not today.}

#Заказ
{120}{}{If you've got the money, we have whatever you need. My girls will give you any kind of sex you want.}
{121}{}{How much?}
{122}{}{What kinds of sex are there?}
{123}{}{Thank you, but I'm not interested.}

{124}{}{Uh... [she gives you a quizzical look] ...you don't know? Listen, hire my girls and you can find out. Actions speak louder than words, yeah?}
{125}{}{Is it... Safe?}
{126}{}{Oh yeah, yeah! Of course! Perfectly safe... The same-sex option is the safest... Anyway, I'm not talking about that whores near the nightclub. Gonna catch something nasty with those girls.}
{127}{}{Nasty? Why?}
{128}{}{Oh, they don't even wash, dear. They'll get you sick, they're *crawling* with it. But not my girls - they're all clean.}

{129}{}{ dollars. Best price in the city.}
{130}{}{For us girls, I can knock a bit off the price. Just for you, honey. Let's say...}
{131}{}{ dollars. That's a special price, just for you and your boss.}
{132}{}{Here's the money. It had better be worth it.}
{133}{}{It'll be worth every penny. Who do you want? They're yours for an hour.}
{134}{}{[Choose a prostitute and head up to a room.]}

{135}{}{You seem to get a lot of business. What's your secret?}
{136}{}{Locals know we're the best in the city. It's a status thing, really, to come here. And out-of-towners, well, they need someone that'll treat them right after a long journey. But you know, it's core, it's just the way people are. *Everybody* wants what we're selling. It's just human instinct.}
{137}{}{I see.}
{138}{}{I'll go then.}
{139}{}{They say you have a good relationship with Thompson. Is that true?}
{140}{}{Oh, Thompson... You know, he's gonna make me his wife after he wins this war... Wait, why am I telling you this? Never mind, it's personal.}

{141}{}{Hey, you just looking or... Oh, wow, it's you! You came to the right place. Someone like you deserves only the best.}

#Квест Томпсона
{150}{}{Mr. Thompson sent me to look into the attacks on your employees.}
{151}{}{[Her smile disappears] Really? It used to be good here, until those fucking cocksuckers moved in. Roughing up my girls, threatening me - ME! I was here first! You ought to show them who really owns this street.}
{152}{}{What do you know about them?}
{153}{}{Why do you think they're doing it?}
{154}{}{You want me to kill them?}
{155}{}{And why should Mr. Thompson solve your problems for free?}
{156}{}{Okay. I'll get it done.}

{157}{}{I know one of those boys... He's named Stinky Grizzly. I don't know if they're local or not, but they started hanging around here recently. They think they're such hot shit... They've got no idea the shit they've stepped in.}
{158}{}{Do you really care? Did Mr. Thompson send you to deal with this problem or to just ask a lot of stupid questions?}
{159}{}{I don't care what you do to them, I just don't want to see them interrupting with my business anymore.}
{160}{}{[She smirks] Oh, let me guess. He didn't pay you, huh? And he's not going to, is he? Damn, a sucker really is born every minute! I pay him weekly for protection, right on time, and when I finally need him he sends an idiot like you. Why am I not surprised? Listen, if you want to make some money, don't try to shake me down. Grow a spine and do your fucking *job* instead!}
{161}{}{I don't like your tone. Give me the money, or I'll show you what real trouble looks like.}
{162}{}{Or what? Whattaya gonna do, huh? I'm your boss's top bitch. Touch one hair on my head, and you'll wish you'd never been born.}
{163}{}{I'm the one solving this problem. I'll decide what information is important or not.}
{164}{}{Yeah? Fine, I'll tell you what I think. They probably thought they could take some territory for themselves while all the big boys are fighting. Fucking stupid. But I guess they don't know how things work around here, since I've never seen them in the neighborhood before this.}

{165}{}{I've solved your problem.}
{166}{}{Already? I guess you're good for something after all. Tell Thompson I'm pleased with your work.}

#Female character
{1117}{}{Have you made up your mind?}
{1161}{}{I don't like your tone. Give me the money, or I'll show you what real trouble looks like.}
{1163}{}{I'm the one solving this problem. I'll decide what information is important or not.}
