{100}{}{You see a madam.}
{101}{}{You see a relaxed older woman named Lilly st. Cyr.}
{102}{}{You'll never meet another like the busty wonder Nanny! Her third breast, swollen with milk, just drives you wild!}
{103}{}{You gently and passionately fuck for an entire hour. It is a very... Educational experience.}
{104}{}{Under the dim lamplight, you see that a vicious skin disease has affected the prostitute's genitals. You can only hope you weren't infected.}
{105}{}{Under the dim lamplight, you see that a vicious skin disease has affected the prostitute's genitals. Hopefully, the condom provided adequate protection.}
{106}{}{Under the dim lamplight, you see that a vicious skin disease has affected the prostitute's genitals. Nonetheless, you do the deed and everyone is satisfied in the end.}

{110}{}{Sorry, honey. I thought nothing was too much for my girls, but one look at your face proves me wrong.}
{111}{}{Hello there, honey. You like my girls? They'll like you too, for the right price.}
{112}{}{Just looking around. What do you have to offer?}
{113}{}{Nothing for today.}

{114}{}{Are there any others like you in the city?}
{115}{}{Oh, you stay away from those girls next to the Cotton Club. It breaks my heart, I feel so sorry for them - that old woman works them terribly, makes them take any awful, dirty man that comes by and doesn't even give them time to wash after. It's like she's hell bent on putting them in an grave early... And her customers too. You want nothing to do with them, trust me.}
{116}{}{I see. Can I ask you something else?}
{117}{}{Thanks for the heads up, but I have to go.}

#Order
{120}{}{On, don't you worry about that. For the right price, my girls will give you any sort of pleasure you want.}
{121}{}{And what is that price?}
{122}{}{What sorts of pleasure are there?}
{123}{}{Thank you, but I don't need anything right now.}

{124}{}{[She looks at you quizzically] You... Really don't know? Well... My girls will be happy to teach you. And don't worry... Learning's the best part.}
{125}{}{Is it... Safe?}
{126}{}{Of course, honey! All my girls are clean! Not like those girls down by the Cotton Club... [shudders]}
{127}{}{What's wrong with the girls by the Cotton Club?}
{128}{}{Honey, they don't even wash! You have to stay away from them if you don't want to get sick. But you don't have to worry about that from my girls - we're careful to always stay clean and prevent any... Baby trouble. You understand?}

{129}{}{ dollars. You won't find a better price for service this fine.}
{130}{}{You're in luck, honey. There's a special deal on lesbian sex: }
{131}{}{ dollars. And, of course, we have a special price for you and your boss.}
{132}{}{Here's the money. This had better be worth it.}
{133}{}{I promise it won't, honey - it'll be worth much more. Who would you like? The blond Susie, the brunette Charlotte, the unforgettable Melanie, or our one-of-a-kind nanny, Stephanie?}
{134}{}{}
{135}{}{Susie.}
{136}{}{Charlotte.}
{137}{}{Melanie.}
{138}{}{Stephanie, the nanny.}
{139}{}{Can I get them all at once?}
{140}{}{Tell me, which of them would you recommend?}

{141}{}{I knew it the second I laid eyes on you. Good choice, honey.}
{142}{}{[You go to a small apartment.]}
{143}{}{Now, you understand she's a *special* treat for *special* tastes. That'll be an extra 75 dollars. Or do you want to choose one of the others?}
{144}{}{She'll be worth it. I'm sure of it.}
{145}{}{A gangbang? Sure, honey, but you understand it won't be cheap. You'll have to pay for all four, so that's an extra }
{146}{}{ dollars. Are you alright with that?}
{147}{}{I'm sure it's worth it. Here's the money.}
{148}{}{You won't regret it!}
{149}{}{Well, all my girls are good. But you'll never meet another woman like the busty wonder nanny Stephanie. Trust me, honey, all the men go crazy for her!}
{150}{}{What's so special about her?}
{151}{}{[Winks] Why don't you find out?}

# Quest Thompson
{160}{}{I hear there was an attack around here. Did you see anything?}
{161}{}{Sorry, but we just ran for the night club when it all started. Some poor fella was shot, but I didn't know him. Funny, though, I never saw a shooter or even heard any shots. Maybe someone else around here can tell you more.}
{162}{}{Thanks for the help.}
