{100}{}{You see a courier.}
{101}{}{You see a secret courier from Las Vegas.}

{102}{}{The courier has been neutralized. All that remains is to bring the package to Big Louie.}
{103}{}{The raiders are waiting in ambush.}
{104}{}{Get ready! The courier's coming!}
{105}{}{The courier is approaching. If you don't want to scare him off, you'd better hide.}
{106}{}{You see the courier's guard.}
{107}{}{You see a brutal guard.}
{108}{}{You see a fellow raider.}
{109}{}{You see your partner.}
{110}{}{Hmm... Better to be careful.}
{111}{}{I don't like it here - it's a perfect place for an ambush...}
{112}{}{What? Ambush? Where?}
{113}{}{The courier escaped with the package! You've failed your mission!}

#—ообщени€ над рейдерами перед нападением на курьера
{120}{}{Bleed them out!}
{121}{}{Get him!}
{122}{}{He's mine!}
{123}{}{Now we're talking!}
{124}{}{Stop! This is a robbery!}

#—ерые сообщени€ над спр€тавшимис€ рейдерами
{130}{}{Quiet! Not yet!}
{131}{}{Everyone get ready!}
{132}{}{They're close...}
{133}{}{Just don't scare them off!}
{134}{}{Keep your ass down!}
{135}{}{Everyone hide!}
{136}{}{Watch it, he's coming!}
{137}{}{Wait for it...}
{138}{}{Don't even breathe!}
{139}{}{Stay sharp!}
