{100}{}{You see Frank Cochran.}
{101}{}{You see frowned working man in clothes stained with engine oil and soot.}

###############################################################################
#
#           Начало диалога
#
###############################################################################

{108}{}{I have another question.}
{109}{}{Thanks.}
{110}{}{Yeah, what?}
{111}{}{I have more questions.}
{112}{}{Can you upgrade my armor?}
{113}{}{Can you modify weapons?}
{114}{}{Nothing.}
{115}{}{Alright, forget it.}

#Первый разговор
{120}{}{[Entering dim-lit room, you see its dirty-faced goggles-wearing inhabitant. He looks busy and tired at the same time. He stops working when notices you] Huh? Are you a customer, or just lost? You'll never know who's going to wander in here... But hey, maybe I'm lucky this time. What can I do for ya?}
{121}{}{Hi. May I ask who I stumbled upon in these slums?}
{122}{}{Frank Cochran, at your service. I'm mechanic and electrician, and also a little bit of a gunsmith. I often have to deal with just about anything that has something to do with repairing. As for slums - no offense taken, I like it that way. If I had more trust in people, I would've already moved somewhere closer to the central streets.}
{123}{}{I see. So if I need something repaired, I can talk to you?}
{124}{}{Yup, I'm always ready to do my favorite job, as long as you pay. What do you need?}
{125}{}{How about some trade?}
{126}{}{This ain't a store, if that's what you mean. But I guess it can't hurt to offload some of this crap.}
{127}{}{Let's take a look at your junk.}

###############################################################################
#
#           Вопросы и ответы
#
###############################################################################

{129}{}{Do you know where can I find pre-war vault technology around here?}
{130}{}{I'm not saying I'm glad to see you, but still, I have someone to talk to.}

#Про Теда Банди
{131}{}{Isn't it dangerous, living alone out here?}
{132}{}{Of course not. Central streets are more dangerous. In Reno, the less time you spend with others, the safer you'll be. Also, sometimes other people, who don't appreciate crowds, come to live out here too. There was one guy, Ted, just a little while ago. Kept to himself, didn't talk much - my kind of guy. Hasn't been around in a while, though. Don't know why.}
{133}{}{Ted, huh? I'll have to remember that.}

#Про охрану в подвале
{134}{}{You have some weird neighbors in the basement, do you know that?}
{135}{}{Yeah, they showed up recently. Know nothing about them, and don't really want to. They are sitting there quietly, not bothering me, and I'm pretty much okay with that. I have a feeling that they are guarding something in there.}
{136}{}{I see.}

#Термит
{140}{}{I have to open an, uh, abandoned safe. Can you help me?}
{141}{}{Don't know nothing about safecracking. Plenty of thieves in Reno, if you want to ask about that. But I've got some military-grade thermite. Not much, though. Also, it ain't cheap, so get the money ready, if you want it.}
{142}{}{Tell me about this thermite.}
{143}{}{Let's trade, then.}
{144}{}{I don't think I need that.}
{145}{}{Got it from some prospectors coming back from an army base. They thought it was an explosive. So, I ran some tests. Turned out, this stuff consists of some mixture of different oxydes, peroxydes, and some chemicals I couldn't understand. Looks like a common thermite, but there's a catch: it produces no flames, but a fuckton of heat. It'll burn through pretty much anything, including metal, and it does it silently. Perfect for getting into an "abandoned" safe.}
{146}{}{Do you only have the one package?}
{147}{}{[He squints at you for a second, then shrugs] Actually, I've got another. I was keeping it for a rainy day, but eh, what the hell. I know you mean business, so I'll sell it to you.}
{148}{}{Yup, that's it. I didn't make it myself, you know. Once it's gone, it's gone.}

#Волт-Тек
{149}{}{Like the pre-war bomb shelters? We've got two in Reno. One under the town hall, which Thompson's using as his headquarters, and one under the city park, near the old bowling alley. Stryker's got it locked up, though.}

###############################################################################
#
#           Пресс для снаряжения патронов
#
###############################################################################

#Пресс патронов
{150}{}{Can you make ammunition?}
{151}{}{Nah, I don't do that. It's not hard though, but you'd need an ammo press.}
{152}{}{Can you make me an ammo press then? I'll pay.}
{153}{}{Nevermind.}
{154}{}{Hmm... Yeah, I can do that. I'll need 10,000 bucks and several days to work on it.}
{155}{}{That's a fair price. I'll give you 5000 dollars up front, and the rest when the tool is done.}
{156}{}{See you later.}

{157}{}{Wow, that's expensive! Can we negotiate?}
{158}{}{I wouldn't have to charge so much if I had decent tools. Mine are all worn out, it's a pain in the ass to work with these. Get me something like "Snap-Off" super tool kit, and I'll get it done in less time and only charge you 2000 bucks. Deal?}
{159}{}{I just happen to have one right here! So, deal?}

{160}{}{Are you trying to fucking cheat? I'm not blind, you know.}
{161}{}{Not enough? Let me come back later.}

{162}{}{You're the boss. Come back in a few days for the press.}
{163}{}{I'll see you then.}

{170}{}{How's my ammo press coming along?}
{171}{}{It's done. I've got it hidden away, just in case. Give me the money first, then I'll get it for you.}
{172}{}{Here it is, 5000 bucks.}
{173}{}{It'll be easier to kill you and find it myself! [Attack]}
{174}{}{Wait here, I'll be back with the money.}
{175}{}{I don't have the cash on me, but maybe you'll be interested in this super tool kit?}

#Обновление пресса патронов
{180}{}{I can't make some calibers with this ammo press.}
{181}{}{Yeah, you can't have it all with just one of those. But now that I think about it, I can improve it for you.}
{182}{}{Improve it? How?}
{183}{}{Forget it, it's fine as it is.}
{184}{}{I can add more attachments and bits. You'll be able to make more calibers and even press armor-piercing rounds. It'll be heavier, but it'll be worth it. Let's say...}
{185}{}{ bucks.}
{186}{}{Here's the money. Get started.}
{187}{}{Done! Always good to see a masterpiece come together.}
{188}{}{Thanks!}

#Починка бортового компьютера
{190}{}{Can you fix this on-board computer?}
{191}{}{[He picks up the computer, looking at it as if he had never seen anything like it before. He twirls it in his hands for a while, runs his finger thoughtfully over the dusty circuit board, inhales the smell of capacitors, and then scratches the back of his head] Yeah, I can do that. Why not? Looks like some parts are missing. Not a big problem though. I could look into it for a buck. 2000 will do just fine.}
{192}{}{Here's the money, but be careful. It can't be replaced and I *really* need it to work. No second chances.}
{193}{}{I'll think about it.}
{194}{}{You found a way to repair the train in Salt Lake City.}

#Починка кия Бертолини
{195}{}{I, uh, broke my favorite pool cue. Can it be repaired?}
{196}{}{Yeah, no problem. It's easy enough to assemble. You have to make the metal joint and cut the cue to shape. The hardest part is the balance. You have to consider the right weight, length, and bend. Lucky for you, I used to be a pretty good pool player, even played with Mr. Chase once or twice, and he's a real master of the game. I hope my skills aren't that rusty yet. I'll fix it for 200 bucks.}
{197}{}{It's a deal. Here's the money and the cue.}
{198}{}{Well, if it's more important to be a good player than a mechanic, then I'll try to fix it myself. Goodbye.}
{199}{}{It's done! You won't even know the difference.}

###############################################################################
#
#           Заказы на ремонт
#
###############################################################################

#Имитаторы монет для автоматов ядер-колы
{200}{}{I need metal plates the size and shape of coins.}
{201}{}{Easy. How many?}
{202}{}{500}
{203}{}{400}
{204}{}{300}
{205}{}{200}
{206}{}{100}
{207}{}{Actually, never mind.}

{208}{}{Sure. I'll do it for }
{209}{}{Here's the money.}
{210}{}{No thanks.}
{211}{}{[An hour later, exhausted mechanic drags in a sack full of plates] Uh... We have a little problem. I busted my drill working on these, so can't produce more. All I managed to make is here.}
{212}{}{Well, at least it's something.}
{213}{}{ bucks.}

#Шайенский водосборник
{220}{}{Can you fix the Cheyenne's water tank in Lovelock?}

{221}{}{Fuck me sideways! Are you serious? You'll have to try very, very hard to motivate me. I'm a great mechanic after all, I've fixed half this city. I don't need to bust my ass hiking up the mountain to patch up some dirty rainwater collector for a bunch of savages.}
{222}{}{ bucks.}
{223}{}{Jeez, I was just asking. Never mind.}
{226}{}{Would }
{227}{}{dollars be worth your time?}

{228}{}{[He scratches one unshaven cheek] Yeah... Alright, fine. But I want the cash up front.}
{229}{}{Here, take it. Don't try anything funny!}
{230}{}{Actually, I changed my mind. You can go back to doing nothing.}
{231}{}{[Carefully counts the money, then nods] Yeah, yeah. I'll get it done. No worries.}
{232}{}{Good.}

{233}{}{I don't work for free.}
{234}{}{You're busting my balls here!}
{235}{}{Keep dreaming.}

#Предохранитель для насоса в Джерлаке
{240}{}{I need a fuse for a water pump.}
{241}{}{Easy. Got one tucked away in my stash. [He squints] It's yours for 300 bucks.}
{242}{}{Are you out of your mind?! So much money for such a little thing?}
{243}{}{Here's the money. Give me the fuse.}
{244}{}{I'll keep looking.}

{245}{}{[He shrugs] Nothing is free nowadays. But I've got an alternative option, if you are interested.}
{246}{}{I'm listening.}
{247}{}{No, I'll pay. Here's the money.}
{248}{}{There have been a lot of dogs around here lately. I think it's breeding season, they're horny and vicious. The mutts from all over Reno seem to be gathering here for a party, so I'm afraid to even go out at night to take a piss. You kill the bitches, and the fuse is yours.}
{249}{}{It's a deal.}
{250}{}{Good.}
{251}{}{Thanks for the fuse.}

{252}{}{About that fuse...}
{253}{}{Three hundred bucks. And don't bother trying to rob me, it's hidden where you'll never find it.}
{254}{}{That's pretty expensive. Is there anything I can do to lower the price?}
{255}{}{I killed the female dogs. Where's my reward?}
{256}{}{I'll pay. Here's the money.}
{257}{}{Was worth it. Thanks for the help.}
{258}{}{You're welcome.}
{259}{}{Great.}
{260}{}{Well, I'm just gonna go, then.}
{261}{}{How about I spend one bullet instead?}
{262}{}{Ha! I don't fucking think so. You'll never find my stash without me.}
{263}{}{Hmm...}

#Апгрейд пикапа:
{270}{}{Have you ever worked on a functional car?}
{271}{}{Like every mechanic, I worked on cars. And by that I mean disassembled a lot of them understanding nothing about how they work. Also, It's almost impossible to find parts in a working condition.}
{272}{}{Do you have any of that parts?}
{273}{}{That's all I wanted to know.}

{274}{}{Yeah, I got one good thing - a fuel regulator. If you had a working car, I could try to install it. It's supposed to lower battery consumption, as I recall.}
{275}{}{Good idea. Because I just so happened to have a working car.}

{276}{}{[His eyes go wide] Really?! You got a working car? Can I see it?}
{277}{}{It's right outside. So, about that part...}
{278}{}{It's not here. Maybe I'll drive it by later.}

{279}{}{Sure! What else am I gonna use this thing for? I'll install it for, let's say... 1000 bucks.}
{280}{}{Here's the money. Get to work.}
{281}{}{Not right now.}
{282}{}{I think I'll kill you and install the part myself!}
{283}{}{Fuel regulator. Install it in a car engine and it'll double your battery life. I'll sell and install it for 1000 bucks.}

{284}{}{What was that thing you said about a car part?}
{285}{}{[He smirks] Nah, you are joking. I don't think you will. And you not only won't find it without me, but also could never figure out how to install it properly. *I'm* the mechanic here, if you didn't understand it by now.}
{286}{}{I'm dead serious. And guess what, here I go! [Attack]}
{287}{}{Hmm. I see. Fine, here's the money. I'll wait for you to finish.}
{288}{}{Hmm. I see. I'll go get the money, then.}

{289}{}{Now your car's fuel consumption will be much more effective than before!}

#Часть от машины
{290}{}{What can you tell me about this part?}
{291}{}{Hmm... That's a fuel controller. Used in car engines. It's irreplaceable, car won't start without it. Y'know, a caravan merchant from Wind of War was asking about this part a while ago. You might be able to do something with it there.}
{292}{}{Wind of War? I should remember that.}

###############################################################################
#
#           Улучшения
#
###############################################################################

#Апгрейд оружия
{300}{}{[He scratches his unshaven cheek] Eh. I'm not good with just any weapon, but when it comes to standard stuff - pistols, rifles, shotguns - it's all pretty straightforward to me. Don't expect much though.}

{301}{}{[Show magnum revolver]}
{302}{}{[Show desert eagle]}
{303}{}{[Show hunting rifle]}
{304}{}{[Show shotgun]}
{305}{}{[Show electric prod]}
{306}{}{[Show sledgehammer]}
{307}{}{[Show spear]}
{308}{}{}
{309}{}{Never mind.}
{310}{}{ bucks.}
{311}{}{I got some ideas. Give me }
{312}{}{ bucks, and I'll improve it for you.}
{313}{}{Here is the payment, start working.}
{314}{}{I'm just offering.}
{315}{}{I have another weapon I'd like you to work on.}
{316}{}{Let's talk about something else.}
{317}{}{See you.}
{318}{}{What is that, a joke?}
{319}{}{Uh, never mind...}

{320}{}{I can whip up a speed loader for you. It'll run you }
{321}{}{Damn, that's a slick looking gun! I think I can extend its magazine for you. That'll be }
{322}{}{Yeah, I've worked on these. I can put a scope on it, if you are interested. Just for }
{323}{}{I bet you want it sawed-off, huh? That's what I usually asked to do. It'll reduce the weight and make it possible to shoot with one hand. You'll get more power out of it, but don't expect to hit anything further than arm's reach. If you're interested, it'll be }
{324}{}{Yeah, I remember fixing these for farmers, when they still were around near Reno. I can rewire it to give a stronger shock for }
{325}{}{This thing has seen better days... It'll take some work, but I can restore it. It'll cost you }
{326}{}{Need a sharpened blade? No problem. I'll do it for }
{327}{}{Well, shit. Can't do nothing here... Come to think of it, I can make a bandolier. It is pretty easy, will cost you only }
{328}{}{It's a fucking sledgehammer, what do you want? Hmm... I guess I can put spikes on it. Interested? It'll cost you }
{329}{}{}

{330}{}{[After a couple of hours, the mechanic finishes his work and hands your newly improved weapon back to you]}
{331}{}{Thanks. I have another weapon for you, if you're interested.}
{332}{}{Thanks.}

{335}{}{[Show "Savage"]}
{336}{}{[Show Nelson's broken shotgun]}

#Динамит
{350}{}{Do you work with explosives?}
{351}{}{I can do some basic work. What do you have in mind?}
{352}{}{Can you dismantle a bundle of dynamite into separate sticks?}
{353}{}{Can you combine sticks of dynamite into one bundle and add a timer?}
{354}{}{No, just asking.}
{355}{}{Done.}
{356}{}{Thanks.}
{357}{}{Sure. I'll need the dynamite and }
{358}{}{Sure. I'll need 5 sticks and }
{359}{}{ bucks.}

#Апгрейд брони
{400}{}{Sure. I whip up a lot of armor for caravan merchants. I've only worked with leather, but I wouldn't mind trying something else. Just bring it to me and let's see what I can do.}
{401}{}{I'll think about it.}
{402}{}{I'd like to show you another set of armor.}
{403}{}{I'll be here.}
{404}{}{You'll have to take it off before I can do anything with it.}
{405}{}{Oh, right, of course...}
{406}{}{[After some time, the mechanic brings back your newly upgraded armor, nodding to himself] Damn, I'm good.}
{407}{}{That's some fine work!}

{410}{}{Can you do anything with this leather jacket?}
{411}{}{Can you improve leather armor?}
{412}{}{How about metal armor?}
{413}{}{I have the armor and some plates for it. Can you do anything with this?}

{420}{}{I can add a steel plate. It won't be comfortable - or light - but it'll protect you. Unless you're playing with electricity, heh. That'll cost you }
{421}{}{Yeah. I can incorporate some steel plates, add some reinforcement here... It'll make fine armor. I'll charge you }
{422}{}{Fuck yeah, I know metal. I'll polish it 'till shine, patch the holes, even the manufacturer won't recognize it! That'll run you }
{423}{}{Doesn't seem too complicated. I'll do it for }

#Female character
{1141}{}{Don't know nothing about safecracking. Plenty of thieves in Reno, if you want to ask about that. But I've got some military-grade thermite. Not much, though. Also, it ain't cheap, so get the money ready, if you want it.}
{1230}{}{Actually, I changed my mind. You can go back to doing nothing.}
{1262}{}{Ha! I don't fucking think so. You'll never find my stash without me.}
