{100}{}{You see the ring promoter.}
{101}{}{You see a promoter in the ring taking bets during a match.}

###########################################################################
#
#          Floating dialogue during PCs fight
#
###########################################################################

{102}{}{ dollars for }
{103}{}{! Any more?!}
{104}{}{! Taking bets!}

{110}{}{Ladies and Gentlemen! Make your bets!}
{111}{}{Make your bets here!}
{112}{}{Don't dawdle, make a bet!}
{113}{}{Who's gonna win today?!}
{114}{}{Hey! Who hasn't bet on the winner yet?!}
{115}{}{The minimum bet is ten dollars!}
{116}{}{More bets! More bets!}
{117}{}{Come on! Hurry up! Faster!}
{118}{}{Look at that heat!}
{119}{}{This is intense!}
{120}{}{Who hasn't bet yet?}
{121}{}{Come on! Bet on the winner!}

###########################################################################
#
#           Dialogue with PC
#
###########################################################################

#Ïðèâåòñòâèÿ:
#----- after all the fights [fem.]
{200}{}{Hey, champion! Such a shame that you're done with the career... }
{201}{}{Those fights were a sight to see! Too bad it's all over... }
{202}{}{Ring's not gonna be the same without you... }
{203}{}{You have a great talent!}
{204}{}{I hope you'll be back one day!}
{205}{}{You have not left the ring forever, right? Right!?}

#----- after all fights [mal.]
{210}{}{Hey, champion! Such a shame that you're done with the career... }
{211}{}{Those fights were a sight to see! Too bad it's all over... }
{212}{}{Ring's not gonna be the same without you... }
{213}{}{You've got a great talent!}
{214}{}{I hope you'll be back one day!}
{215}{}{You have not left the ring forever, right? Right!?}

#Main dialogue:
{219}{}{Bye.}
{220}{}{Hey.}
{221}{}{Can I make a bet?}
{222}{}{Not now. We only accept bets during the fights.}
{223}{}{What the hell is going on right now then?}
{224}{}{They're just warming up. We let them out to dance for the crowd. I'm not sure how soon the real fight will start.}
{225}{}{Got it.}

{226}{}{Hey, fighter! There are a lot of big bets on you!}
{227}{}{Oh? That's great. See you.}

{228}{}{Hey, champion! How are you feeling after the fight? That was quite a show! The crowd was fucking wild! I thought they were gonna tear the fence apart! Superb! Just superb!}
{229}{}{Uh-huh, it was fun. See you.}

#About Solomon
{230}{}{Hey, these fights are fair, right? No doping or anything?}
{240}{}{What the hell are you implying?! Bishop was pretty damn clear about it - no chems before the fight. He kicked all the dealers out the door to keep his reputation clean. At least I don't know anything about that.}
{241}{}{Is that so? I guess that means I can't get a little steam before the fight?}
{242}{}{Well, unless you want some bad rep and a boot, that's a no.}
{243}{}{Oh yeah, except that's a lie. See this note? Still gonna deny that dealers are selling here?}
{244}{}{Got it. Still hard to believe.}
{245}{}{Wha... Hold up, chum, don't judge too quick! This ain't a deal with the ring, you dig? Some strangers came in and made some deals with each other in the corner. It had nothing to do with the ring! Get it?}
{246}{}{Okay, so the ring is out of it. But that didn't stop someone from catching a glimpse of those two, right?}

{247}{}{Hmm. Why should I even bother talking to you? Maybe I should just call security and have you thrown out?}
{248}{}{I'm sure two people could find something to agree on. [quietly hand him $100]}
{249}{}{I wonder who the boss is more likely to believe - some midget, or the champion of the ring with hard evidence?}
{250}{}{Forget it.}

{251}{}{[With a sly smile, he pulls you over to the side, acting like nothing is going on] Hard to argue with that. I think we could find a common ground.}
{252}{}{Great, now tell me everything you know.}
{253}{}{Enough with the conspiracy! Tell me everything! And don't even think of lying!}

{254}{}{Shit, that's hard to argue with.}
{255}{}{Quit whining and tell me what you know!}
{256}{}{I want to know everything you do. And then we might part peacefully.}

{257}{}{Like I said, the ring has nothing to do with this. But that filth is crawling out of every hole and we can't do much about it. Dealers try to slip drugs to our fighters, it's a gold mine for them. And the fighters want to win, so they buy this shit like candy. Those of them who were smarter refused, realizing how serious it was... At first. And then they came here to find *proper* dealers, with *quality* product. Our boys don't hold back, if they're gonna buy, they're gonna *buy*.}
{258}{}{And this dealer mentioned in the note, does he come here often?}
{259}{}{You know, dealing with Solomon is not the best decision... In any case, you won't find him in this place. Bishop said he can't show his face here. So, free advice for you - if you want him, find those who work with him, so they would introduce you.}
{260}{}{And who might that be?}
{261}{}{Well, a lot of people know him. Ask Racer at the bowling club, he's one of them. Although, I'm not sure how close they are now... Oh, and if anybody asks, I didn't say anything. Talked about fights, betting, that's all. Dig?}
{262}{}{Alright... }
{263}{}{[Sniffs the note, making face like it's stronger than any drug]}
{264}{}{[Rubs the $100 note affectionately] }
{265}{}{You found another lead on the elusive drug dealer.}

{266}{}{So that's how the fighters get the glory around here?! What about this dealer? Do you know anything? [show Fatso's note]}

#Fighter's stimulator
{270}{}{Listen, I've got some tough fights ahead. Any suggestions?}

#--- Dialogue tree in case PC didn't get the info earlier
{271}{}{How are you feeling after your last fight? You know, I heard that... we got a successful fighter coming in. A lot tougher than the one you fought. I'm not implying anything, but you might want to prepare a little better, if you catch my drift. [he winks]}
{272}{}{What fighter?}
{273}{}{It's going to be a tough few days. I have to train even harder... }
{274}{}{Mhm, I hear you. What do you have in mind?}

{275}{}{I don't know much. I heard that this monster was bred on human meat. A huge beast with no brains. He was born a killing machine.}
{276}{}{Train? Are you kidding me?! Err... Seriously? Don't you get a little "pump" before the fight? You know what I'm talking about, don't you?}
{277}{}{Well, no, I don't. Is that a problem?}
{278}{}{Well... Maybe... A little. Sometimes. Just in case.}

{279}{}{[He gets closer] I'll say this, champion. You know Stryker, right? He's got a man who cooks chems. You need to talk to him about improving your skills. But that's only between us.}

#--- Dialogue tree in case the PC wants to dope up faster
{280}{}{}
{281}{}{Why are you telling me this? For free, I mean.}
{282}{}{Thank you for that. I'll be going now.}
{283}{}{Connections - they're as valuable as cash, maybe even more, chum. Never forget that. That's why I help everyone here and there.}

{284}{}{What are you implying? If you're talking about chems, then I'll say this - Bishop doesn't like them. If he learns about you using, you can kiss this place goodbye.}
{285}{}{Like that's stopping anyone... }
{286}{}{Well, forget about it then.}
{287}{}{Listen, talk like that never ends well. All I want is to work and earn money. I've got to feed my family and help my sick mother, got it?}
{288}{}{Of course. But look what I have here - 1000 bucks. Just enough to buy some medicine for your sick mother.}
{289}{}{Uhmm. Not a bad amount, but still not worth the risk I'm taking by dealing with you. No offense, but everyone in this town knows it's safer to avoid you.}
{290}{}{[He hungrily grabs the cash] Just in time, friendo. I appreciate the... Err, help. So, I heard you wanted to know who sells the dope on this ring? Well, I know a secret that I'll be happy to share with you.}
{291}{}{Talk.}

#Female version:
{1228}{}{Hey, champion! How are you feeling after the fight? That was quite a show! The crowd was fucking wild! I thought they were gonna tear the fence apart! Superb! Just superb!}
{1271}{}{How are you feeling after your last fight? You know, I heard that... we got a successful fighter coming in. A lot tougher than the one you fought. I'm not implying anything, but you might want to prepare a little better, if you catch my drift. [he winks]}
{1245}{}{Wha... Hold up, chum, don't judge too quick! This ain't a deal with the ring, you dig? Some strangers came in and made some deals with each other in the corner. It had nothing to do with the ring! Get it?}
{1279}{}{[He gets closer] I'll say this, champion. You know Stryker, right? He's got a man who cooks chems. You need to talk to him about improving your skills. But that's only between us.}
{1283}{}{Connections - they're as valuable as cash, maybe even more, babe. Never forget that. That's why I help everyone here and there.}
{1290}{}{[He hungrily grabs the cash] Just in time, girl. I appreciate the... Err, help. So, I heard you wanted to know who sells the dope on this ring? Well, I know a secret that I'll be happy to share with you.}
