{100}{}{You see coach.}
{101}{}{You see a veteran of many fights. Looks like he loves giving orders.}

{105}{}{I've taught you everything I know. I have nothing else for you.}
{106}{}{I'm proud to have been a part of your journey!}
{107}{}{Keep it up! You're unstoppable!}
{108}{}{You're the best butcher on the ring!}

#Beginning dialogue
{110}{}{Drop and give me twenty!}
{111}{}{Who are you?}
{112}{}{Are you a coach? Could you train me?}
{113}{}{Not now, goodbye.}

{114}{}{Who the hell gave you permission to talk, maggot?! You will only refer to me as SIR, am I clear?! I'm the coach! I turn whelps like you into real men! If I say jump, you jump! If I say run, you run! If I say kill, then you will most certainly kill!}
{115}{}{I'm the coach! I turn whelps like you into real men! If I say jump, you jump! If I say run, you run! If I say kill, then you will most certainly kill!}

{116}{}{Like hell! I don't waste my time on spineless wimps like you!}
{117}{}{What's in it for me?}
{118}{}{Chummer, your skills are brighter than the El Dorado lights! I don't have much to teach you. But, we could work a little, if you make it worth my while.}
{119}{}{I don't need it, anyway...}

{120}{}{Err... Cash, sir!}
{121}{}{That's right! I take 1000 bucks per session. No questions!}
{122}{}{Sure thing. Here's the money. When do we begin?}
{123}{}{Understood. I'll come back with the money.}

{124}{}{Right now! Hit the showers! MOVE!!!}
{125}{}{Yes, sir!}
{126}{}{Your right hook is on point! The rest is up to you. Come again when you've got a serious fight - we'll warm up!}
{127}{}{Great. Warmed up, let's get to work!}
{128}{}{After an intensive session with the coach, your unarmed skill has increased by 5%.}
{129}{}{A lot of this coaching is old hat to you, but you've still increased your skills by 3%.}

{130}{}{If I'm going to be all I can be, I'll need to use everything I can use, right? How about a little chemical help?}
{131}{}{Is that some joke?! That's off limits around here! We ran all the dealers off! Don't even think of asking again!}
{132}{}{But I have a note!}
{133}{}{Fine.}
{134}{}{Right, that's it! Either you shut up and get the fuck out of here, or I beat your face to a pulp!}
{135}{}{You can try, old man!}
{136}{}{Fine, I'm going.}

#Female version:
{1105}{}{I've taught you everything I know. I have nothing else for you.}
{1106}{}{I'm proud to have been a part of your journey!}
{1107}{}{Keep it up! You're unstoppable!}
{1108}{}{You're the best butcher on the ring!}

{1110}{}{Drop and give me twenty!}
{1114}{}{Who the hell gave you permission to talk, maggot?! You will only refer to me as SIR, am I clear?! I'm the coach! I turn pretenders like you into real fighters! If I say jump, you jump! If I say run, you run! If I say kill, then you will most certainly kill!}
{1115}{}{I'm the coach! I turn pretenders like you into real fighters! If I say jump, you jump! If I say run, you run! If I say kill, then you will most certainly kill!}
{1118}{}{Chummer, your skills are brighter than the El Dorado lights! I don't have much to teach you. But, we could work a little, if you make it worth my while.}
{1124}{}{Right now! Hit the showers! MOVE!!!}
{1126}{}{Your right hook is on point! The rest is up to you. Come again when you've got a serious fight - we'll warm up!}
{1131}{}{Is that some joke?! That's off limits around here! We ran all the dealers off! Don't even think of asking again!}