{100}{}{You see the match instigator.}
{101}{}{You see the ring instigator who accepts bets during a match.}

###########################################################################
#
#          Floating dialogue during PCs fight
#
###########################################################################

{102}{}{ dollars for }
{103}{}{! Any more?!}
{104}{}{! Taking bets!}

{110}{}{Ladies and Gentlemen! Taking bets!}
{111}{}{Make your bets here!}
{112}{}{Don't dawdle, make a bet!}
{113}{}{Who's gonna win today?!}
{114}{}{Hey! Who hasn't bet on the winner yet?!}
{115}{}{Bets are a minimum of ten dollars!}
{116}{}{More bets! More bets!}
{117}{}{Come on! Faster! Faster!}
{118}{}{Look at that heat!}
{119}{}{This is intense!}
{120}{}{Who didn't bet yet?}
{121}{}{Come on! Bet on the winner!}

###########################################################################
#
#           Dialogue with PC
#
###########################################################################

#Приветствия:
#----- after all the fights [fem.]
{200}{}{Hey, champion! Such a shame that you're out of the ring now... }
{201}{}{Those fights were a sight to see! Too bad it's all over... }
{202}{}{Ring's not gonna be the same without you... }
{203}{}{You've got great talent!}
{204}{}{I hope you'll be back one day!}
{205}{}{You're not out of the ring forever, right? Right!?}

#----- after all fights [mal.]
{210}{}{Hey, champion! Such a shame that you're out of the ring now... }
{211}{}{Those fights were a sight to see! Too bad it's all over... }
{212}{}{Ring's not gonna be the same without you... }
{213}{}{You've got great talent!}
{214}{}{I hope you'll be back one day!}
{215}{}{You're not out of the ring forever, right? Right!?}

#Main dialogue:
{219}{}{Bye.}
{220}{}{Hey.}
{221}{}{Can I make a bet?}
{222}{}{Not now. We only make bets during a fight.}
{223}{}{What the hell is going on right now then?}
{224}{}{They're just sparring. We let them out to dance for the crowd. I'm not sure when we'll next have a proper fight.}
{225}{}{Got it.}

{226}{}{Hey, fighter! You've got great bets going for you!}
{227}{}{Oh? That's great. See you.}

{228}{}{Hey, champion! How are you feeling after the fight? That was quite a show! The crowd was fucking wild! I thought they were gonna tear the fence apart! Super! Super! Super!}
{229}{}{Uh-huh, it was fun. See you.}

#About Solomon
{230}{}{Hey, these fights are fair, right? No doping or anything?}
{240}{}{Hey, what the hell are you implying?! Bishop was fucking crystal clear - no chems before a fight. He even sent all the dealers out the door to keep his rep. At least I don't know anything about that.}
{241}{}{Is that so? I guess that means I can't steam up a little before the fight?}
{242}{}{Well, unless you want some bad rep and a boot out the door, that's a no.}
{243}{}{Oh yeah, except that's a lie. See this note? You still gonna deny that dealers are selling here?}
{244}{}{Got it. Still hard to believe.}
{245}{}{Wha... Hold up, chum, don't judge too quick! This ain't a deal with the ring, you dig? Some strangers came in and did some deals between themselves, in the corner. The ring has nothing to do with this, got it?}
{246}{}{No problem, the ring is out of it. But that didn't stop a certain someone from catching a glimpse of those two, right?}

{247}{}{Hmm. Why should I even bother talking to you? Maybe I should just call security and have you thrown out?}
{248}{}{I'm sure two people could find something to agree on. [quietly hand him $100]}
{249}{}{I wonder who the boss is more likely to believe - some midget, or the champion of the ring with hard evidence?}
{250}{}{Forget it.}

{251}{}{[With a sly smile, he pulls you over to the side, acting like nothing is going on] Hard to argue with that. I think we could find a common ground.}
{252}{}{Great, now tell me everything you know.}
{253}{}{Quit it with the conspiracy! Tell me everything, and don't even think of lying to me!}

{254}{}{Shit, that's hard to argue with.}
{255}{}{Quit whining and talk what you know!}
{256}{}{I want to know everything you do. And then we might part peacefully.}

{257}{}{Like I said, the ring has nothing to do with this. But that filth crawls out of every hole and we can't do much about it. The dealers want to sling dope to our fighters, they quickly figured that's goldmine. And the fighters want to win, so they buy the shit like candy. The smarter ones refused, realizing how serious the whole thing is. And then they came here to find *proper* dealers, with *quality* product. Our boys don't hold back, if they're gonna buy, they're gonna *buy*.}
{258}{}{And this dealer from the note, he comes here often?}
{259}{}{You know, dealing with Solomon isn't exactly the best decision. But, if you need him, you're at the wrong place. Bishop said he can't show his face around here. If you still wanna find him, I'll give you some free advice - find those who work with him to get an introduction.}
{260}{}{And who might that be?}
{261}{}{Well, he's had lots of people working with him. Ask Racer at the bowling club, he worked with him. Although, I'm not sure how close they are now... Oh, and, if anyone asks - I didn't say nothing. Talked about fights, bets - that's it. Dig?}
{262}{}{Alright... }
{263}{}{[Sniffs the note, making face like it's stronger than any drug]}
{264}{}{[Rubs the $100 note affectionately] }
{265}{}{You have a second lead to finding the illusive drug dealer.}

{266}{}{So that's how the fighters get the glory around here?! And you don't know anything about this dealer? [show Fatso's note]}

#Fighter's stimulator
{270}{}{Listen, I've got some tough fights ahead. Any suggestions?}

#--- Dialogue tree in case PC didn't get the info earlier
{271}{}{Hold on, how are you feeling after that last fight? You see, I heard that a... Successful fighter is coming over. Much tougher than the last one you fought. I didn't say anything, but you might wanna prepare a bit more, if you catch my drift. [he winks]}
{272}{}{What fighter?}
{273}{}{Gonna be a tough few days. I'll need to train even harder... }
{274}{}{Mhm, I get you. What've you got in mind?}

{275}{}{I don't know that much. I heard that this monster was brought up on human meat. A huge brute without any brains. He was *born* a killing machine.}
{276}{}{Train? Are you kidding me?! Err... Seriously? You don't get a little "pump" before a fight? You know what I'm talking about. Do you?}
{277}{}{Well, no, I don't. Is that a problem?}
{278}{}{Well... Maybe from time to time... A little, just in case.}

{279}{}{[He motions you closer] I'll say this, champion. You know Stryker, right? He's got a man who cooks chems. You need to talk with him about how to improve your skills. But that's only between us.}

#--- Dialogue tree in case the PC wants to dope up faster
{280}{}{}
{281}{}{Why are you telling me this? For free, I mean.}
{282}{}{Thanks for that. I'll be going now.}
{283}{}{Connections - they're as valuable as cash, even more, chum. Never forget that. That's why I help everyone here and there.}

{284}{}{What are you implying? If you're talking about chems, then I'll say this - Bishop doesn't like it. If he gets word of this, you can kiss this place goodbye.}
{285}{}{Like that's stopping anyone... }
{286}{}{Well, forget about it then.}
{287}{}{Listen, talks like this never end well. All I want is to work and earn money. I've got to feed my family and help my sick mother, got it?}
{288}{}{Of course. But look what I have here - 1000 bucks. Just enough to buy medicine for your sick mother.}
{289}{}{Uhmm. Not a bad sum. Still not worth the risk I'm putting myself in by dealing with you. No offense, but everyone in this town knows that it's safer to avoid you.}
{290}{}{[He hungrily grasps the cash] Just in time, friendo. I appreciate the... Err, help. So, I heard you wanted to know who does the dirty on this ring? Well, I know one secret that I'll be happy to share with you.}
{291}{}{Talk.}

#Female version:
{1228}{}{Hey, champion! How are you feeling after the fight? That was quite a show! The crowd was fucking wild! I thought they were gonna tear the fence apart! Super! Super! Super!}
{1271}{}{Hold on, how are you feeling after that last fight? You see, I heard that a... Successful fighter is coming over. Much tougher than the last one you fought. I didn't say anything, but you might wanna prepare a bit more, if you catch my drift. [he winks]}
{1245}{}{Wha... Hold up, chum, don't judge too quick! This ain't a deal with the ring, you dig? Some strangers came in and did some deals between themselves, in the corner. The ring has nothing to do with this, got it?}
{1279}{}{[He motions you closer] I'll say this, champion. You know Stryker, right? He's got a man who cooks chems. You need to talk with him about how to improve your skills. But that's only between us.}
{1283}{}{Connections - they're as valuable as cash, even more, baby. Never forget that. That's why I help everyone here and there.}
{1290}{}{[He hungrily grasps the cash] Just in time, girl. I appreciate the... Err, help. So, I heard you wanted to know who does the dirty on this ring? Well, I know one secret that I'll be happy to share with you.}