{100}{}{You see Michael, the bartender.}
{101}{}{This is Michael. His name is written on a worn-out badge on his shirt.}

{102}{}{Want a drink before the fight?}
{103}{}{Speaking of fights, can I place a bet?}
{104}{}{Speaking of fights, can I participate?}
{105}{}{Sure, show me what you've got.}
{106}{}{Nope, I need to go.}
{107}{}{That's it?}
{108}{}{Another question.}
{109}{}{Bye.}

{110}{}{We have a guy for that. See him before the fight starts.}
{111}{}{I really doubt it... But it's not up to me. Take the hall to your right, then head up to the boss's office. Talk to him.}
{112}{}{Who's in the ring right now?}
{113}{}{Hell if I know. Some tribals from the wasteland. Slavers bring them in from time to time. They are replaced so fast that I don't even try to remember their names. And why should I? They're just meat. [he shrugs indifferently]}
{114}{}{I'm looking for the girl in this picture. Ever seen her around here?}
{115}{}{Nope, don't think I have, but her body seems familiar... Weird, how could a body be familiar? [he wrinkles his face, scratching his head] Maybe she is from the night club? Oh yeah! I'm not really sure, but I think I saw her dancing there. A body like that... Yeeeah... [looks like he's about to start drooling]}

{116}{}{I've heard that some dealers sell dope here. I really need some, you dig?}
{117}{}{Are you out of your mind? Which dealers are you talking about?}
{118}{}{Those ones. [Show him the note]}
{119}{}{Hmm... You're right, I don't even know. Jackson must be wrong about it.}
{120}{}{Ah, yeah, THOSE ones. Shady guys, they used to hang around. But Mr. Bishop kicked them all out.}
{121}{}{Got it.}

{122}{}{Good to see you, champion.}

#Female version:
{1102}{}{Want a drink before the fight?}
{1122}{}{Good to see you, champion.}
