{100}{}{You see Bishop.}
{101}{}{You see an entrepreneur with a very serious expression on his face.}

#Читерство:
{102}{}{Stop cheating, you bastard! I swear, this is better be the last time... }
{103}{}{[Start combat.]}
{104}{}{[Exit.]}

#Первый разговор:
{110}{}{[He looks at you appraisingly] Hmm. What do you need, sport?}
{111}{}{So you're the one who organizes these fights?}
{112}{}{Nothing. See you later.}

{113}{}{Indeed I am. If you're looking to see men bash each other's faces into a pulp, you've come to the right place. My name is Jordan Bishop. I'm the manager of the ring and nothing happens here without my permission. So what business do you have with me?}
{114}{}{Tell me about the rules of the ring. I'm thinking I might want to participate.}
{115}{}{I want to bet on a fighter.}
{116}{}{Where did you get those fighters that are in the ring right now?}
{117}{}{Business? I just wanted to talk. Well, if you're so busy, I'd better just go... }

{118}{}{I run this ring, and I don't have time for stupid questions. I hope you've come to do business this time?}

{120}{}{Oh, that. I'm not the one who takes the bets. We have another guy in the hall dealing with that kinda stuff, look for him.}
{121}{}{Just some ordinary slaves. They're not really cut out for the heavyweights. So they just dance a bit, it isn't a serious fight. Why do you ask?}
{122}{}{You?! Listen, our conditions aren't right for you, they're too... Harsh. We have only one rule of battle here - no weapons. Opponents fight to the death, until their final fucking breath. Of course, the fighter can be kept alive, but no one ever gives such a mercy in the ring. If you want to participate, you'd better be ready for this sort of thing.}
{123}{}{So what? I don't match up? That's a shame... }
{124}{}{[He studies you closely] Hmm. It's hard to get a good look at you under that clothing... But I'm willing to give you a try. But I warn you - our fights don't have any restrictions! No one is gonna pull punches, people can and often do die in this ring. The only string attached to these fights is: no weapons. I can advise you to go warm up in the gym, there is a hell of a coach there to help you out.}
{125}{}{How much will I earn for winning?}
{126}{}{It depends on how much money the betting audience loses. Bids happen during the fight. After the staff gets their cut, we pass the remainder on to you.}
{127}{}{Who will be my opponents?}
{128}{}{To start off, let's see how you deal with the slaves. If the audience likes what you got... Well, we do have some professionals, but you'll still need to grow in order to fight them. Dont worry, they'll give you hell if you ever get in the ring with them!}
{129}{}{Tempting offer!}
{130}{}{Then get ready for a fight. Usually our serious fights are in the evening, at 21:00.}
{131}{}{Can't wait!}

#Подготовка к бою и вознаграждение
{132}{}{Hey, ready to fight, sport?}
{133}{}{Hell yeah!}
{134}{}{Not now.}

{135}{}{Excellent! The coach will warm you up. Give 'em hell!}
{136}{}{[Wait until 21:00 and enter the ring.]}

{137}{}{Hey, where the hell is our champion? Oh, there you are! Here's your money. [he gives you your winnings] When you're ready for the next fight, let me know.}
{138}{}{Okay.}

{139}{}{Hey, sport! You came for your next pump of adrenaline?}
{140}{}{You bet I am! I'm ready to fight.}
{141}{}{No, I just came to watch the slaves fight.}

{142}{}{Sorry, sport, we're not ready for the next battle. Come tomorrow, okay?}
{143}{}{Such determination, I like it! Well, go on then!}
{144}{}{You probably noticed we're increasing the pressure in the ring, giving you some stronger opponents. But this time it's gonna be a *real* challenge for you. For this fight I pay a higher fee. You'd better come out swinging!}
{145}{}{I paid a top fee for your opponent tonight. I guess they've heard of you all the way down to Vegas, because this one came from there specifically to fight you. Be warned - this one is serious business. My advice is to remember *all* your weaknesses in combat. They will become a major issue in the ring this time.}
{146}{}{If only you could have seen yourself! That was the best left hook that's ever been swung in my ring! Tricks like that are what makes us a lot of money. The audience was ecstatic, the whole city was trying to get in to watch! Anyway, here's your money. [he gives you your winnings] When you're ready, come by and we'll arrange another fight... IN YOUR HONOR!}
{147}{}{I'm exhausted just from watching that amazing fight! It was... It was crazy! Our ring's the hottest spot in town, sport, and it's all thanks to you. [he gives you your winnings] ...But now let's talk about the bad news.}
{148}{}{What is it? Give it to me straight!}
{149}{}{Audience loves you so much they bet the bank on you... And they win! You see where I'm going with this?}
{150}{}{Uh-oh... }
{151}{}{You're so good, we can't make money on you. Every fight is a sure bet. You're bleeding us dry, sport! We can't earn money on this kind of situation.}
{152}{}{Wait a minute, so the ring lives on lost bets?}
{153}{}{Well, of course! What else? Well, there's the bar, but that's barely a pittance compared to what we get from bets. And some of the fans go on to gamble in the casino, but that only goes so far.}
{154}{}{Someone doesn't have enough marketers!}

{155}{}{Yeah, well... I've seen some real pain in the ring, but nothing more painful than this. You made us, but you'll ruin us. I'm sorry. You're the best... And you have to leave.}
{156}{}{And it all went so well... }

{157}{}{Sorry, sport. Some fights you just can't win.}

#Уточнение, чего не хватает для участия на ринге:
{158}{}{Why can't I participate?}
{159}{}{First, your arms are like noodles. The audience doesn't like a short fight, which is what you'd be. Secondly, just from the way you move I see you don't know a thing about boxing. Do you understand what I'm putting down, Noodle Arms?}
{160}{}{Maybe you've got the technique of unarmed combat down, but we choose strong opponents, and you don't look strong enough. Whether you win or lose, it'll be a short fight. Our fans don't like that.}
{161}{}{You look strong enough, but that doesn't mean you know how to fight. This isn't a drunken brawl here. Talk to our coach, he'll show you the ropes.}
{162}{}{Right, thanks.}

{163}{}{Wait a minute. I heard Mr. Bertolini was looking for someone for a "special task". I don't know what the hell he's up to, but if you want to earn money and reputation in this city, go to him. Tell him I sent you, he'll understand.}
{164}{}{Thank you, Mr. Bishop. I'll think about it.}

#Бой на ринге:
{200}{}{LET THE BATTLE BEGIN!}
{201}{}{You won! It was awesome!}

{202}{}{I'LL BITE YOUR EARS OFF!!!}
{203}{}{BANZAI!!!}
{204}{}{GRRR!!!}
{205}{}{IT'S TIME TO END YOU!!!}
{206}{}{HRRR!!!}
{207}{}{BEG FOR MERCY, WHELP!!!}
{208}{}{ONLY ONE OF US WALKS AWAY!!!}
{209}{}{YOU ARE ALREADY DEAD!!!}
{210}{}{I'M THE POWER!!!}
{211}{}{WELL WELL!!!}
{212}{}{TREMBLE, SCUM!!!}
{213}{}{I WILL HANG YOUR TEETH AROUND MY NECK!!!}
{214}{}{I WILL MAKE A TALISMAN OUT OF YOUR BONES!!!}
{215}{}{YOU'RE NOBODY!!!}
{216}{}{FACE DOWN!!!}
{217}{}{ASS UP!!!}
{218}{}{ANOTHER WUSSY!!!}
{219}{}{ANOTHER ASSHOLE!!!}
{220}{}{DROP DEAD, FILTH!!!}
{221}{}{I'LL KILL YOU ALL!!!}
{222}{}{IT'S TIME FOR YOU TO RETIRE!!!}
{223}{}{THAT'S IT!!! THE PARTY HAS STARTED!!!}
{224}{}{DRY YOUR PANTS, PIECE OF SHIT!!!}
{225}{}{DON'T PANIC!!!}
{226}{}{EAT SHIT!!!}
{227}{}{KAMIKAZE!!!}
{228}{}{ARGHHH!!!}

{250}{}{You won!}
{251}{}{You won! It was awesome!}
{252}{}{You have won against a very formidable opponent! It was an amazing experience!}
{253}{}{You have won against a very dangerous opponent! The room pulses with euphoric energy. The crowd looks upon you like a god!}

{254}{}{Can you buy chems here?}
{255}{}{No. Absolutely not. I have nothing against chems, but it harms the reputation of my place. And reputation is worth a lot in Reno.}
{256}{}{Then what's this? [show Fatso's receipt]}
{257}{}{Right.}
{258}{}{Huh. Well, we can't watch over everything. In any case, we have nothing to do with this.}
{259}{}{Hmm.}

#Female character:
{1117}{}{Business? I just wanted to talk. Well, if you're so busy, I'd better just go... }
{1132}{}{Hey, ready to fight, sport?}
{1137}{}{Hey, where the hell is our champion? Oh, there you are! Here's your money. [he gives you your winnings] When you're ready for the next fight, let me know.}
{1139}{}{Hey, sport! You came for your next pump of adrenaline?}
{1140}{}{You bet I am! I'm ready to fight.}
{1141}{}{No, I just came to watch the slaves fight.}
{1142}{}{Sorry, sport, we're not ready for the next battle. Come tomorrow, okay?}
{1144}{}{You probably noticed we're increasing the pressure in the ring, giving you some stronger opponents. But this time it's gonna be a *real* challenge for you. For this fight I paid a higher fee. You'd better come out swinging!}
{1146}{}{If only you could have seen yourself! That was the best left hook that's ever been swung in my ring! Tricks like that are what makes us a lot of money, the audience was ecstatic, the whole city was trying to get in to watch! Anyway, here's your money. [he gives you your winnings] When you're ready, come by and we'll arrange another fight... IN YOUR HONOR!}