{100}{}{You see a strong man.}
{101}{}{You see a strong man. He craves for your blood!}
{102}{}{You see a strong woman.}
{103}{}{You see a strong woman. She craves for your blood!}

{110}{}{You won!}
{111}{}{You won! It feels awesome!}
{112}{}{You defeated a formidable opponent. What a feeling!}
{113}{}{You defeated an extremely dangerous opponent. You are on top of the world!}
{114}{}{You get the "Legend of the New Reno ring" achievement.}
{115}{}{You get the "Legend of the Las Vegas ring" achievement.}
{116}{}{Surviving so many grueling fights has improved your endurance.}