{100}{}{You see a drunkard.}
{101}{}{You see just a harmless drunk.}

#Bonus for kindness:
{102}{}{Thanks for the bottle... You know, I think, soon I won't even need it. I'm old. Bloody caravaneer's work brought me to my knees and a bottle has bent me completely... You know, you're a good person. I see it in your eyes. And I always wanted to be someone like you. But I was always missing something. Maybe I was selfish, thought only about myself... Look, let me once in my life help someone else. Here is my caravaneer's jumpsuit. Great for travel in the wastes. Take it, don't be shy. I don't need it anyway. And thank you for everything.}
{103}{}{Wow, this was unexpected. And thank you, too, man.}

#Start of the dialogue
{110}{}{[You try in vain to wake the drunk. Today he is clearly incapacitated.]}
{111}{}{[Leave him alone]}

{112}{}{[Two bulging, yellowed eyes covered with a net of swollen capillaries stare up at you. You struggle to determine whether this creature is truly alive.] Hey, buddy?! What do you want from the old Ricky the Drover?}
{113}{}{You must have been living in Reno for a long time. Can you help a newcomer with some advice?}
{114}{}{Well, enough chit-chat for today.}
{115}{}{That's right, what would I want from a sorry drunk? I'd better get going.}

{120}{}{Ha! Yeah, I know Reno as good as my tool, I've studied it along and across! But, ya see, I need to wet my throat, it's very dry... }
{121}{}{Ha! Yeah, I know Reno as good as my tool, I've studied it along and across! Ask what you need!}
{122}{}{Here's a bottle of beer, rejoice.}
{123}{}{Here's a bottle of moonshine, relax.}
{124}{}{Here's a bottle of rot gut, cheer up.}
{125}{}{Then I'll go get you a bottle.}
{126}{}{Dat's another matter! Dat's what I'm talking 'bout! [happily gulps down the bottle] What can Ricky the Drover tell you about? Ask, don't be shy.}
{127}{}{I'm not interested in that. Let's go back a bit.}
{128}{}{Here's a bottle of whiskey, enjoy.}

#########################################################################
#
# Cluster of questions
#
#########################################################################

#Categories
{130}{}{Tell me a little about New Reno.}
{131}{}{Tell me something interesting about the local authorities.}
{132}{}{Could you tell me about the drugs in Reno?}
{133}{}{Tell me about the caravans, you must know a lot about them.}
{134}{}{I don't suppose you could tell me the history of New Reno?}
{135}{}{Nothing, I'm leaving... }

#About the city
{140}{}{Tell me about the "Silver" hotel.}
{141}{}{Tell me about the "El Dorado" casino.}
{142}{}{Tell me about the night club.}
{143}{}{Tell me about the ring.}
{144}{}{Tell me about the suburbs.}
{145}{}{Tell me about this building.}
{146}{}{I heard there was an evacuation bunker?}

#About the local authorities
{150}{}{I witnessed a racket in the hotel. Is this a common thing here?}
{151}{}{Tell me about the situation pulling this city apart.}
{152}{}{What does Stryker offer?}
{153}{}{What does Thompson offer?}
{154}{}{Tell about the entrepreneurs.}

#About drugs
{160}{}{What kinds of drugs can be found in the city?}
{161}{}{Who makes drugs in Reno?}
{162}{}{Who benefits from this?}
{163}{}{Do you know anything about this suspicious candy?}
{164}{}{I heard this meth gum came from Reno... }

#About caravans
{170}{}{There are a lot of the caravaneers around the hotel. Why is that?}
{171}{}{What cities is New Reno trading with?}
{172}{}{Have you ever found anywhere interesting while traveling?}
{173}{}{Are there any places I should avoid?}

#About the history of Reno
{180}{}{Tell me about the time of the Great War.}
{181}{}{Tell me about the reign of the City Hall.}
{182}{}{Tell me about the "great redistribution".}
{183}{}{Tell me about the "Golden age" of Reno.}
{184}{}{Tell me about the civil war.}

#Output in the console:
{190}{}{Your Pip-Boy has been updated with Las Vegas's coordinates.}
{191}{}{Your Pip-Boy has been updated with NPP Poseidon Oil's coordinates.}
{192}{}{Your Pip-Boy has been updated with Lovelock's coordinates.}
{193}{}{Your Pip-Boy has been updated with Uranium City's coordinates.}
{194}{}{Your Pip-Boy has been updated with Hawthorne's coordinates.}

#########################################################################
#
# Block of answers
#
#########################################################################

{200}{}{Hmm, Reno is big... As big as the ass of a brahmin. And smells the same, but I still remember it being a true oasis in the middle of a scorched desert. There was no Great War here, the city was spared from the nuclear bombing. But to what use? Those petty people, damn them, tore it to pieces anyway. Oh, they blew the most precious thing left in the wastes.}
{201}{}{Well, ya know, dat's like a hippie before the Great War. Doesn't want to listen to anyone, wants to live independently. And their boss is the kind of man that would rather have the company of good people than higher profits. That's why caravans choose to stay there, and not somewhere else. So, the place is the most cultural in the city and also the safest. That's mind boggling that they managed to achieve this. Their restaurant's great, by the way. Real expensive, though.}
{202}{}{[Spreads his hands out] Oh, the huge casino with card tables, roulettes, machines, humor and a sparkling sign. But the most important thing is, of course, the bar! If I were richer I would visit them more often... Though, I'm getting carried away. Not everything is good, for many the smell of easy money ruins their life. Some debtors were even sold as slaves. [he bends towards you] I'll tell you a secret, my friend, some people think that casino is not as clean as it looks. But nobody ever proved something. People are winning there, so everything must be alright.}
{203}{}{Oh, miss Momsy knows a lot about girls and about people's interactions. Once I tried to hit on her, but to no avail. We, caravaneers, you know, don't mind having a good time after the hard and winding road, especially if it's the first paycheck. That's 'cause while going through the wasteland for several weeks one can only comfort himself if you know what I mean [winks]. However, the club is expensive and unsafe. There are also rumors about a maniac no one was able to catch. I hope you'll avoid meeting him.}
{204}{}{Fights! [waving his fists] Blood! Wow! If I was young, I would certainly try my luck there. Now I can't even make a bet. At least the entrance is still free. [sighs] Many perished there, by the way. Some were broken in the ring, others were hung because of money. Brutal.}
{205}{}{And what about suburbs? There are some ranches, some gangs settled down in the ruins, some rats and, well, and the poor, of course. Oh, in former times we were buying brahmin skins at the Mr. Luciano ranch. Those were the good times... Sincere ones.}
{206}{}{[Waving his hands] Building among buildings. Mr. Wright owns it, but no one wants to live 'ere, 'cause the casino is across the street. But all the local whores do their work here and pay rent to Wright. And a bunch of junkies hang around there too. Also, Patrick and I live here - seems no one else claims this floor.}
{207}{}{That's right, there is one. Military boneheads, before the Big Boom, decided that such an important institution should be located in the most unexpected place. And so they placed it... Under the city park. [taps his forehead with the index finger] You don't you dare, the entrance is guarded by the Striker's guys, it's their territory. You can't go inside, he won't allow others in. You know why? There's a big smelly basement with the rats and some trash, but also there are two heavy iron doors. And what's behind them - nobody knows. They say the former government sits there, and waits.}

{210}{}{There is no local government any more. There was, however, long ago, when the mayor installed the himself as a dictatorship. Some still remember this and even now they tell horror stories to their children at nights about that time... No, Reno is different now. Now it's torn into pieces, each to his own, and they are doing it with a straight face.}
{211}{}{They are pressing Lewis little by little, but what can you do? Everyone wants to skim the cream off the area, but the man remains faithful to neutrality. It's not in his character to be someone's doormat. But, someday that will happen, it seems.}
{212}{}{Stryker and Thompson are two of a kind. Both started as raiders, now they practice "election" rhetoric. Each one pushes his own agenda, and the population, with mouths agape, eats their crap up. So they split the locals and now cannot settle them down. It is getting bad. Such things can only lead to a civil war, and it has been smoldering for several years already.}
{213}{}{He's got the idea to make a center that would control everything. Something like a trade union, only with the president who has all the executive power. Well, of course, no one wants it, except for ordinary people. To share their hard earnings with everyone? Huh, who of the local entrepreneurs will agree to that!?}
{214}{}{His idea is to bring back the old town hall. To make everyone ruled by it, only the mayor would be the chief and would decide everything. Undivided, with iron order, police forces, and strict reporting on everything. And you know, it would work! There are still those who remember how it was before, when after the Big Boom the mayor ruled the city. What a strict order was imposed, ooh! But is a former raider suited for this post?}
{215}{}{Each of them is busy doing his own business and isn't going to share it with anyone. In their own way they can be understood, but they can't agree among themselves. They began bickering about ten years ago. And they can't find a common language to date. Maybe they would have found one already, if not for those two - Thompson and Stryker. Who knows, who knows... }

{220}{}{Hmm, a dark matter. But if you're going to, like, set me up or wring drugs out of me, then... *hicc*!... Here what I say: Ricky the Drover has *never* dealt with drugs, and that's while the rest of the city sticks needles! But you decide for yourself, without me. It's your business.}
{221}{}{Different kinds, it seems! Everything your heart desires! There are combat drugs that came from military bases brought here by prospectors. There is some yuck from local handicraft producers. Also psychedelic drugs from Vegas that come here with caravans. And the dealers standing on all of the corners in the shade are not afraid of anything - because there are is no one to stop them.}
{222}{}{Well, some are brought, others are produced here. Small-scale producers are numerous, notable ones are exceptional and usually no one will talk about them. All of them, like property, belong to someone. They are kept, probably in the basements, supplied with the food and components, and not even allowed to go into the city. At least that's what I reckon. And of course, it isn't possible without the involvement of the most influential people of the city.}
{223}{}{Here, ya see, is the deal. It happened so that in Reno all the doctors got exhausted, and their medicine ran out a long time ago, due to all the visitors the city received, over the last sixty years since the Big Boom. Also drugs work as painkillers, and components for folk medicine, and in general allow people to not to have to pay attention to the local shit. So this problem has two sides to it. And the truth is as usual somewhere in between.}
{224}{}{The most innocuous sweet in Reno! It was made to help you relax after a hard day's work, there are many of those who really need it. After ten minutes of ingestion you won't care about anything. But there are also cons. It works something like pre-war Mentats. If you swallow them too often, you get migraines, it's almost guaranteed.}
{225}{}{Wow, it's meth from the Dirty Hurst himself! Evil genius - that's how he was called. He was a brilliant chemist, but was spending all the time on drugs, he even used slaves. Seems he crossed someone's road, big time, and was removed. Or maybe he was killed just for drugs. Because in fact, there was nothing else left in his shack. And thank God. After all, his stuff was horrible, honest!}

{230}{}{I can prattle about that for days. How many paths I came through, how many boots I have trodden, that's enough for me. Did my time. But those were the days, yeah! I even keep my old map with me, to remember... }
{231}{}{It just happened so. A hotel with a good boss, a restaurant, a shop nearby. What else is needed? So it turned out to be the only one with caravan parking in the entire Reno. That's how Mr. Mordino is able to do his business: no one is fighting there, it's always crowded around there, free trade, you know. Although, come to think of it, now are hard times for Lewis. It seems he can no longer maintain his independence and that's bad.}
{232}{}{They are few, Vegas in the East and Salt Lake City further to the North. Let me show you on the map... But there are others, too, little places on the way. Also, old Harold became quite a rare guest from the South now. You'd better ask around about him in the store at the parking lot.}
{233}{}{Well, dead cities in the wastes are not that rare, and there are plenty of strange places too. What's interesting that I can recall? Well, there's a military base not far from Reno. But I don't advise you to go there: rats everywhere, and turrets piercing you through and through. Also looters are wandering around the base, they want to clean out the warehouses, but it never really works out. You want to know where? Well, if you want to die - go boldly. [he points out the location on his map]}
{234}{}{You bet, there is! [begins counting on his fingers] Well, military bases in the first place. And then toxic waste dumps. There are oodles of them here, the whole state is fucked up by those pre-war assholes! And also in the north... You know, I heard rumors that in the North, in the mountains, there is an oasis town. It's all bright with lights in every house, the streets are lit with lamps, people are walking around in blue pajamas. Some daredevils went there once to look for it, but instead of oasis there is the worst place to be found: it is called NPP Poseidon Oil. They say that the radiation there is off the charts so you will glow at night without any light. I even have this point on my map, to avoid it! Can show you if you want.}

{240}{}{Well, in sixty years much has changed here. Usually they talk about four periods. The first is the time after the Great War when the city was ruled by the mayor. The second is after the death of the mayor the great division of the city began. The third is the "Golden age" when everything became stable, and the fourth is the current civil war that's going on on the streets for last ten years. About which one do you want me to tell you?}
{241}{}{I didn't catch that moment, was still very tiny, understood very little. I was told that when the rest of America was burning in the nuclear flame, the riots erupted in Reno, so severe you've never imagined. There are still areas where you can see the traces of those events. After all, not a single atomic bomb had fallen near the city, and, by the way, more than half a million people lived there back then! And what they did when they learned that the world is burning in hellfire? Well, some took shelter in the emergency bunkers, while others enclosed themselves in their houses, but the majority took to the streets to do evil and anarchy. The city went empty, most of the people had died from radiation, diseases and starvation.}
{242}{}{After the Great War, the town hall tried to establish order here, but managing such a crowd was impossible. At first, they just sat and waited till everything calmed down by itself, then grasped power by the iron hand of the local mayor. He was such a tyrant! He didn't spare anyone - he shot, hanged, tortured, and dispersed dissenters by gunfire. On the other hand, this allowed the city to survive, and even gain some sense of order. So the mayor was an ambiguous character... }
{243}{}{When the mayor died, the town hall couldn't do a damn thing by itself. It was no longer feared by anyone. And who even needed it? Farmers? Or owners of the restaurants? Of course they wanted a free life, but of course the markets and the power supply needed to be divided somehow among everyone by someone. And then the fun began... Some owners entered into alliances with other, then they broke up, some declared each other hostile. Of course, competition was pressured, sometimes the hard way. All kinds of things happened. However, when everything settled down and everyone had found his place - people started to get along and live normally again.}
{244}{}{Oh, this is the sweetest time you can imagine. It didn't last long though, just six years! Back then everyone was content with everything [passionately waving his arms]: neon signs sparkled around, people ordered music in restaurants, jazz bands and comedians were giving performances, the trading with other settlements was at full swing! During this time so many people moved here that there was no enough place to walk! But that was exactly what would become the problem. The resources of the city quickly depleted, there were too many people. And so the problems, we are still busy disentangling, started to appear. Greed - that's the bitch who made it all happen.}
{245}{}{It's not to be confused with the Great War! Nothing compares to that. And the current war is the flaccid, long and boring local showdown. It was started by someone called Big Louie. He was invited by a local businessman, he hoped that Big would pave his way to omnipotence, but no way, Big fooled everyone. He removed the unnecessary people, subdued local entrepreneurs to his "Committee", divided the city into sectors and appointed his men to each sector. So he ruled here for a year, and damn well, I must say. He solved the problems with water, started distributing food, but something went wrong and he went back to where he came from - to the wasteland. Since then no one has heard from him in Reno. But his minions have had quite a ride - now one stands for the City Hall, the other for the congress. But what's the good of it, their forces won't be enough to control everything. Even more so, if they keep bickering among themselves... So it's been like that for five years in a row.}

#Women's replics
{1112}{}{[Two bulging, yellowed eyes covered with a net of swollen capillaries stare up at you. You struggle to determine whether this creature is truly alive.] Hey, buddy?! What do you want from the old Ricky the Drover?}
{1202}{}{[Spreads his hands out] Oh, the huge casino with card tables, roulettes, machines, humor and a sparkling sign. But the most important thing is, of course, the bar! If I were richer I would visit them more often... Though, I'm getting carried away. Not everything is good, for many the smell of easy money ruins their life. Some debtors were even sold as slaves. [he bends towards you] I'll tell you a secret, my friend, some people think that casino is not as clean as it looks. But nobody ever proved something. People are winning there, so everything must be alright.}
