{100}{}{You see a slave.}
{101}{}{You see a slave. He looks cleaner than the others.}

{110}{}{[This slave looks soft and scared. He carries himself like a prisoner who may one day be freed, rather than a slave who will die in chains.]}
{111}{}{You seem to be having a tough time in here.}
{112}{}{[Leave]}

{113}{}{[He frowns, carefully thinking about his answer, as if afraid of being beaten for saying the wrong thing] Yes... I'm not used to this way of living. I was a pretty important man not so long ago.}
{114}{}{Important? What do you mean?}
{115}{}{I worked for Mr. Wright, managing his business in Uranium City. But all the workers left the town after people and cattle started going missing, so Wright got mad and sold me into slavery. [he sadly shrugs] That's how it works in Reno. One day you're a made man, the next one you are... This.}
{116}{}{I see. That explains a lot. Well, I should let you get back to your work.}
{117}{}{Yeah, that's a real shame. But hey, not my problem. See ya.}

{118}{}{[Wistfully] How is it out there? Outside the walls?}
{119}{}{Tell me your story again.}
{120}{}{Marilyn sent for you. You need to return to Uranium City.}
{121}{}{I shouldn't have asked. Never mind.}
{122}{}{Same old, same old. Not much to tell.}

{123}{}{Really?! Oh, Marilyn... Damn, she's really something. Can't say I'm surprised. But... See this collar? If I try to escape, it'll kill me. And if I do escape, they'll find me - and then I'm gonna regret it hadn't killed me! The only way I'm getting out of here is if Luciano agrees to let me go... Will you help me? For Uranium City? And... For Marilyn?}
{124}{}{What about Wright, your former boss?}
{125}{}{I'll talk to Luciano. Let's see what can be done.}
{126}{}{I will organize an escape.}
{127}{}{Luciano decided to let you go. You're free now.}
{128}{}{I'll think about it.}
{129}{}{Wright? Even if he wanted to help, he doesn't have any money. He sold me into slavery just to wring a little profit out of a bad situation.}
{130}{}{With Luciano himself? Uh... Well, if you're good with him, you might have a chance, but actually, the one in charge of the slaves is Machete.}
{131}{}{Oh... Okay... That sounds, uh, great, except for the armed security all over the place and my ten-thousand-volt necklace. You do remember all that, right?}
{132}{}{The security is dead. Only one problem remains: the collar.}
{133}{}{The guards are dead and the collars have been remotely disabled. You can simply take it off now.}
{134}{}{[At first he hesitates, then cautiously puts his hands on the collar. Beads of sweat stand out on his head and his eyes bulge in their sockets before, hyperventilating, he tears off the collar and throws it on the floor. He stares down at it for a moment, his hands feeling at his exposed neck, before he breaks into frantic laughter] Ha! Ha-ha, ha-ha-ha-ha!! That's it! I'm free! [he giggles in relief] I'm finally free!}
{135}{}{Uranium City awaits.}
{136}{}{Uh... How should I say this... I can't get there on foot. I'll have to pay someone to bring me there, and I don't have any money, so... I don't think you can spare a few bucks, can you?}
{137}{}{Here's $300. Take the first available stagecoach.}
{138}{}{I'll do you one better. I'll drive you myself... In the trunk, maybe. Heh-heh.}
{139}{}{I'll think of something. Wait here.}

{140}{}{Hey there. I'm still here, trying to think of a way to get to Uranium City. Any ideas?}
{141}{}{No, not yet.}
{142}{}{[When the collar is finally removed, he breathes a sigh of relief] Just smell that air. That's the smell of freedom! I'm never letting someone put that thing on me again!}
{143}{}{A worker will be waiting for you inside the car. Don't worry about him.}
{144}{}{Holy shit, you just don't stop delivering, do you? Thank you so much! You're a goddamn miracle! I'll see you in Uranium City!}
{145}{}{Have a good journey.}
{146}{}{You have a car?! Awesome! I've never seen a working car before, let alone ride in one! We can leave right now!}
{147}{}{Let's go.}
{148}{}{Dead?! How? Actually, don't answer that - I don't want to know. But the real problem is this collar. If I try to step off the property, I'm a crispy critter. I know these collars are controlled from some building on the property. If you know anything about technology, can you deactivate this thing?}
{149}{}{I know, but I can't leave. The collar will kill me if I try, and if it doesn't, I'm sure they'll find me eventually. We have to settle things with the management.}
{150}{}{Let me have a look at this collar. I think I can disable it.}
{151}{}{Uh... [he starts to shrink, but the thirst for freedom brings him back] Just... Don't push any buttons unless you know what they do, okay?}
{152}{}{[Disable the collar]}
{153}{}{I can't do it. I have to find another way.}

{154}{}{Luciano is dead. You can leave this place at any time.}
{155}{}{[When the collar is finally removed, he sighs in relief] Just smell that air. That's the smell of freedom! I'm never letting someone put that thing on me again!}
