{100}{}{You see Carl.}
{101}{}{You see a man with big, calloused hands.}
{102}{}{Can't wait!}

{110}{}{Hello. Uh, do you need something?}
{111}{}{I was told that a certain Carl lived here. He used to work in Uranium City.}
{112}{}{Nothing really, just looking around.}
{113}{}{Ah, well, that's me. Why? Did Wright send you?}
{114}{}{No, Marilyn did. She's getting the workers back together.}
{115}{}{What? Did they finally sort everything out? No, what am I saying? If they'd sorted things out, Wright would've sent me back.}
{116}{}{The mutants are dead. All three of them. The mine can work again, but we need workers.}
{117}{}{Hm. I'll see what I can do about those problems then.}

{118}{}{Hi again.}
{119}{}{Marilyn sent me. How about returning to Uranium City?}
{120}{}{See ya.}

{121}{}{Hey, that's a good news! I'd be happy to come back, but... Listen, I can't leave my family just like that.}
{122}{}{What do you need then?}
{123}{}{I'll need to leave my wife all the money, and it's a long trip to the mine. Mind throwing me 300 bucks for the stagecoach? I'll return it as soon as I get my pay. Honestly!}
{124}{}{What, is there no other way?}
{125}{}{Okay, here's 300 bucks. Pack your bags.}
{126}{}{Wait right here, I'll be back.}

{127}{}{Well, unless you can drive me. But I doubt that you have any transport, ha-ha.}
{128}{}{I'll drive you to Uranium City in my car, free of charge.}
{129}{}{You have a car?! Really?! Oh, wow, that's awesome! I'll pack my bags right away. I've always wanted to ride a car...}
{130}{}{Go to the car and wait for me there. You'll ride in the trunk.}
{131}{}{Thank you, friend! See you in Uranium City.}
{132}{}{Goodbye.}

{133}{}{Do you know what happened to Joseph?}
{134}{}{Honestly, I haven't seen him for a while. After seeing Mr. Wright, he looked very down. Maybe you should ask Mr. Wright about what happened.}
{135}{}{Can you tell me where I can find Michael?}
{136}{}{That I can - Michael is living on the streets. Wright kicked him to the curb, and he stayed there. When he was the quartermaster, everyone wanted to be his friend. And now nobody needs him. Crazy how it turns around, huh?}
{137}{}{The worker will wait in your car. Don't worry about him.}

#Женские реплики
{1131}{}{Thank you, friend! See you in Uranium City.}