{100}{}{You see unlucky bum.}
{101}{}{You see a dirty homeless man. He looks a little neater and cleaner than others sharing his fate.}

{110}{}{[This beggar looks strangely neat.]}
{111}{}{How did you end up like this?}
{112}{}{[Leave]}
{113}{}{You wouldn't believe it. Not so long ago, I used to be the quartermaster of a successful mine! I could have anything I wanted! Money, food, weapons - I could afford it all. And then, just like that, I was fired. [he sadly smiles] That's how it happens, you know - You have everything, and then in a single moment, nothing.}
{114}{}{[Leave]}
{115}{}{So you're the quartermaster from Uranium City Wright threw into the streets?}
{116}{}{Yeah, I'm the one. He just up and sacked me, then told everyone in the city not to give me a job. So, nobody did. And I can do nothing except that.}
{117}{}{I can help you get your old job back.}
{118}{}{[He looks up, surprised] Really? Well... Great!.. except, what's the point? The mines went to hell. I'd still have nothing to do there.}
{119}{}{The mine is clear. You can return.}
{120}{}{Return? Ha... Hahaa! [he throws his head back and laughs hysterically] How can I return?! My wallet and stomach are empty. I'll never make it there alive! Bandits will cut me down before I get ten miles out of the city.}
{121}{}{Fine. Let's see if I've got anything...}
{122}{}{Here's $50 for provisions.}
{123}{}{Alright, I'll think about sorting that out.}
{124}{}{Thank you very much! That'll keep me fed, but walking to the mines is still suicide.}
{125}{}{Got it. Here's $300 for a stagecoach.}
{126}{}{Let me think, how would I get you to Uranium City with less costs.}
{127}{}{No problem. I'll drive you there in my car. Find it and wait for me there.}
{128}{}{[His mouth falls open, staring at the money] Just like that?! You're a real saint! I'll leave as soon as I can. Thank you very much!}
{129}{}{This isn't for you, this is for the future of Uranium City. Now go, I'll meet you there.}
{130}{}{CAR?! Haven't seen anything like that in a while! I'll go right away. Thank you very much!}

{131}{}{[He shifts from leg to leg as you look through your bag.]}
{132}{}{You know what? Here's $50, go buy your own provisions.}
{133}{}{Looks like I've got nothing. Wait up a little.}

{137}{}{The worker will wait in the car. Don't worry about him.}

#Женские реплики
{1128}{}{[His mouth falls open, staring at the money] Just like that?! You're a real saint! I'll leave as soon as I can. Thank you very much!}