{100}{}{You see an unlucky bum.}
{101}{}{You see a dirty homeless man. He looks a little neater and cleaner than the others who shared his fate.}

{110}{}{[This beggar looks oddly tidy.]}
{111}{}{How did you end up like this?}
{112}{}{[Leave]}
{113}{}{You wouldn't believe it. Not so long ago I was the boss of a successful mine! I could have anything I wanted! Money, food, guns - I could afford it all. And then, just like that, I got fired. [He sadly smiles] That's how it is, you know - you have everything, and then in an instant you have nothing.}
{114}{}{[Leave]}
{115}{}{So, you're the quartermaster from Uranium City that Wright threw out on the street.}
{116}{}{Yeah, I'm the one. He just fired me on the spot, then told everyone in the city not to give me a job. So, nobody did. And I could do nothing about it.}
{117}{}{I can help you get your old job back.}
{118}{}{[He looks up, surprised] Really? Well... Great! Except, what's the point? The mines have turned to hell. There's nothing for me to do there anyway.}
{119}{}{The mine is clear. You can return.}
{120}{}{Return? Ha... Hahaa! [he throws his head back and laughs hysterically] How can I return?! My wallet and stomach are empty. I'll never get there alive! The bandits will cut me down before I'm ten miles out of town.}
{121}{}{Fine. Let's see if I have anything for you...}
{122}{}{Here's $50 for provisions.}
{123}{}{Alright, I'll think about sorting that out.}
{124}{}{Thank you very much! That'll keep me fed, but walking from here to the mines by foot is still a suicide.}
{125}{}{Got it. Here's $300 for a stagecoach.}
{126}{}{Let me think a little more about getting you to Uranium City with less costs.}
{127}{}{No problem. I'll drive you there in my car. Find it and wait for me there.}
{128}{}{[With his mouth wide open, he looks at the money] Just like that?! You're a real saint! I'll leave as soon as I can. Thank you very much!}
{129}{}{This isn't for you, this is for the future of Uranium City. Go, I'll meet you there.}
{130}{}{A CAR?! Haven't seen anything like that in a while! I'll go right away. Thank you very much!}

{131}{}{[He wriggles from foot to foot as you go through your bag.]}
{132}{}{You know what? Here's $50, go buy your own provisions.}
{133}{}{Looks like I've got nothing. Wait up a little.}

{137}{}{The worker will wait in the car. Don't worry about him.}

#Женские реплики
{1128}{}{[With his mouth wide open, he looks at the money] Just like that?! You're a real saint! I'll leave as soon as I can. Thank you very much!}