{100}{}{You see Mark.}
{101}{}{You see your old pal, prospector Mark. He's back in Reno.}
{102}{}{You have acquired the metal detector the long, hard, but honest way.}

{103}{}{Thank you for everything you've done for us!}
{104}{}{Someone killed Wright! Must have been one desperate bastard. He's done us all a great favor.}
{105}{}{Hey, how are the things going? I'm still holding, but this won't last forever...}
