{100}{}{You see a gambler.}
{101}{}{You see a gambling addict.}
{102}{}{Hey there, friend!}
{103}{}{Stop bugging me! This is the moment of truth!}
{104}{}{}

#Плавающие реплики при игре и ударе рукой по автомату
{110}{}{Come on!}
{111}{}{Ahh, dammit... }
{112}{}{You fucking... I'll fuck you up for this!}
{113}{}{Motherfucker!}
{114}{}{When's this shit going to stop already?!}
{115}{}{I'll be broke in a second if I keep this up... }
{116}{}{I've really gotta quit this stuff}
{117}{}{Hopeless!}
{118}{}{All I need is a lousy win! Come on!}
{119}{}{::grabs his head in fear::}

######################################################################
#
#             Диалог об игре, автор Kerb
#
######################################################################

#Первый разговор
{200}{}{Piss off! I'm in the zone! Just a little more... Come on, baby... God, fuck, you mechanical piece of shit! Gypped me again! Agh, calm down... Deep breath... How can I help?}
{201}{}{Oh, it's you again. What, you want me to help you find the exit?}
{202}{}{You're the one that needs help here. I mean, look at you, you're a total crackhead!}
{203}{}{Well, I wouldn't mind some information.}
{204}{}{Err... I probably shouldn't bother you.}

{205}{}{What? What are you talking about? I've never touched a chem in my life! I've got my shit together... Kinda... Maybe I don't, but I've at least stayed clean and far away from that smack that infests the streets of Reno! But... I do need help, you got that right. Can you hear me out?}
{206}{}{Let me guess. You want some money for your next fix... I mean, for another round in the game?}
{207}{}{No money, you fucking gambler! Go panhandle if you want a handout!}

{208}{}{Information? Actually, I've been spending more and more time here lately. I don't really keep up with rumors. But, maybe, you want to know more about my system? If so, I'm sorry to disappoint you. However... You can help me "study", you get me?}
{209}{}{Well... Sure. How much do you need for your "studies"?}
{210}{}{Err, sorry, I don't understand what you're talking about.}
{211}{}{No, I don't. And I don't think I care to. Goodbye.}

{212}{}{Ugh, listen, pal, this is a casino. It's obvious what kind of study is going on here... Only one kind of study COULD be going on here... Do you get it yet?... "Study". [he winks at you]}
{213}{}{Hmm? You trying to beat the house? How much would you need?}
{214}{}{I don't care anymore. Bye.}

{215}{}{It's good to see a person who understands! We are talking about a very small amount - only 50 bucks. I'll return the money first thing tomorrow, as soon as you see me, A.S.A.P. Whaddya say?}
{216}{}{Alright, I mean, if it's just for one day... Then here, take it.}
{217}{}{No, I can't help right now.}

{218}{}{Thank you! That's it, I won't hold you up any longer - come back tomorrow and you'll be greeting a different man. A rich man!}
{219}{}{Sure, good luck.}

#Второй разговор
{250}{}{Good day... I think. Um... Do you need something?}
{251}{}{My 50. Fast.}
{252}{}{What happened? Did you fail your "studies"?}
{253}{}{Never mind, just passing through.}

{254}{}{Well... I won... Almost. I almost hit the bank, man, I swear! I just needed a little more... Now, if you would've just given me 100 yesterday... }
{255}{}{Fucking scumbag! Not only do you go and blow my 50, you ask for more?!}
{256}{}{How do I know you won't just lose this 50 too?}
{257}{}{That's it. I've had enough of this bullshit.}

{258}{}{Hey, what's the matter with you? This is a for-sure deal, no joke! I'm begging you, friend - just an eensy-weensy, miserable 50 bucks! One more time! And then we're good! I'll return the money and... You know what, even toss a little extra on top! Just because I like you! I won't just win your... Our money back, I'll hit the fucking jackpot! You just gotta trust me!}
{259}{}{Fine, take it. Is that it? You don't need anything else, right?}
{260}{}{How about "Fuck you", you fucking degenerate?!}
{261}{}{No, I can't help you right now.}

{262}{}{Of course, I've got you! Everything will be okay, I promise!}
{263}{}{You've been warned... }

#Третий разговор
{300}{}{[He looks at you timidly, while simultaneously trying to hide his face. However, his eyes become attracted to the machine yet again.]}
{301}{}{Well... I'm waiting.}
{302}{}{[Walk by.]}

{303}{}{Look, I can explain everything! I got distracted... Slightly messed up my calculations... And... Um... I lost... }
{304}{}{[Smack him on the head] This is just the beginning... }
{305}{}{Enough of your bullshit! Money on the table - fast!}
{306}{}{I see. Don't move, I'll go for a drink and think about what to do with you.}

{307}{}{[He drops to his knees] No... Not on the head... I... I'll fix everything... But... I'm broke... Honestly! If someone would buy this lousy kidney, I'd sell it on the spot! But... I'll win everything back... Just give me another 50 - I'll return it all to you and pay you extra! And you've been so good to me, god bless you, I'll throw another extra on top of that! I used to win big on slot machines! I just got unlucky, brother... }
{308}{}{I must be crazy, but... Here, take it. It's becoming kind of funny to watch at this point.}
{309}{}{[Knee him in the face] Get lost! And pray, pray on your fucking life that I won't find you!}

{310}{}{You... Fuck, you're the only one who helps me... Ahhh, fuck! This fucker on the other side is winning again! How does he keep doing it?!}
{311}{}{[Leave.]}
{312}{}{Hmm... Is something funny going on, or am I just dealing with a complete idiot?}

#Четвертый разговор
{350}{}{[He drops on the floor and smacks his head into the machine] Forgive me, brother! I'm scum, nothing but scum! I'm a piece of shit! Shoot me, do the world a favor!}
{351}{}{Not before you pay your debt.}
{352}{}{Simmer down, man. Lower your voice and tell me what happened. Quietly.}
{353}{}{Not a bad idea. Let me think about it.}

{354}{}{[He gets up, coming back to his senses] I lost everything again... [he starts sobbing] I don't even know what I'm going to do now... }
{355}{}{Me and luck used to be best friends... }
{356}{}{Why do you cling to that machine like that? Maybe you'd get luckier on a different one?}
{357}{}{Have you ever won here before? Even once?}
{358}{}{And how do the other gamblers strike it big? Perhaps you can get advice from them?}
{359}{}{Shut up and take another 100. Play with me by your side. I'm getting to the bottom of this.}
{360}{}{Well, think about it then, I'll be back.}

{361}{}{Because I'm hooked, okay? I can't earn shit... The first time was a fluke! Fuck those mechanics, I hope they become impotent. I hope their dicks stay limp until the day they die!}
{362}{}{Yeah, that's harsh... Let's try something else?}
{363}{}{Worse things could happen. Especially when you owe money to someone like me. Now think.}

{364}{}{Just a few times, and very little! And when I just start feeling the game - that's it, I lose every single time from there.}
{365}{}{Hmm, I see. Another question.}
{366}{}{Soon, you won't even have the change in your pockets. You feel me?}

{367}{}{Ha, nice joke! These gamblers wouldn't piss on you if you were on fire! But they're getting lucky anyway, some even manage to hit the jackpot... I'm really the only loser here.}
{368}{}{Hey! Stop whining. Better tell me something else.}
{369}{}{Man, if I get a hold of you, you'll look back at these times with a smile on your face. For now, see ya.}

{370}{}{Got it! I, of course, wanted to quit, but if you insist... }
{371}{}{Come on, let's see.}
{372}{}{Oh, that was awesome... }
{373}{}{Shit, where's my money... }

{374}{}{[You watch as the gambler loses more of your money. Soon, you identify the pattern: the machine feeds a few small wins to the player, then gives nothing but losses thereafter. You can tell this is not random; the pattern is fairly regular and was clearly calibrated to maximize the player's emotional investment in their "winning streak" before it starts giving nothing but losses.]}
{375}{}{[You watch as the gambler loses more of your money. Soon, you identify the pattern: the machine feeds a few small wins to the player, then gives nothing but losses thereafter.]}
{376}{}{If only we could figure out how this happens... I'll deal with this, wait here.}

#Плавающие фразы после предпоследнего проигрыша
{380}{}{I wish I could just hang myself - but I can't even afford a rope... }
{381}{}{Luck failed me again... }
{382}{}{I'm a worthless, miserable person... }
{383}{}{Just bury me with this fucking machine... }
{384}{}{This piece of metal is killing me!}
{385}{}{Its all your fault, you stupid box with lights!}
{386}{}{Fucking machine!}

#После выяснения проблем с автоматом
{400}{}{Hey, friend... Decided to shoot me? I don't blame you. I wouldn't expect anything better.}
{401}{}{I've got good news, and bad news. The good news is your luck has nothing to do with this. The bad news is you won't be winning on this machine anytime soon. It's rigged.}
{402}{}{Yeah, or slice you up... I haven't exactly made up my mind yet, just wait and pray.}

{403}{}{What? You mean... I... Fucking cheating sons of bitches! I'll tear their fucking teeth out for this!}
{404}{}{Relax there, my little dentist friend. First you repay me. Listen here - there are a few options.}

{405}{}{Yeah sure, whatever you say... I can't believe it, those sneaky fuckers... May they all be fucked by crazed brahmin.}
{406}{}{I've been thinking about some things in the context of game theory... [write down your calculations to play on this machine]}
{407}{}{Stand here, and try not to attract attention. I'll talk to the supervisors here.}
{408}{}{I need my money, so let's go, move to the next machine.}
{409}{}{I haven't decided yet. But don't think I'll forget your debt to me.}

{410}{}{Wow! You're a magician, my friend! No, a mathematician! You're the motherfucking reincarnation of John Nash! A true genius! Just a few days, brother, and then you and I are both rich! For real this time! We'll fuck these scum with their own weapons!}
{411}{}{Just don't have a heart attack out of excitement. See you later.}
{412}{}{[Give this poor a man few more days in order to win back the money.]}

{413}{}{Ehh... This is the only option left for me... Well, thank you anyway. I'll try to repay in a week by any means.}
{414}{}{Yeah, you do that.}
{415}{}{[Give this poor a man few more days in order to win back the money.]}

{416}{}{My friend! Where have you been? I was thinking about sending someone after you! Let me cut to the chase - I did it! I cleaned this fucking casino dry... Though, I won't be allowed to play here anymore. Once again I thank you - here is your money... And here's that extra I promised you. That's it, I don't need to sit in this shithouse for a minute longer! The lights of Vegas await me!}
{417}{}{Well, good luck. Try to keep yourself out of situations like this next time, high roller.}

{418}{}{I don't have anything! I'm still broke... }
{419}{}{Relax. Change of plans.}
{420}{}{Then I will come back later.}

{421}{}{You know, I saw how that mechanic removed the counter from the machine. I guess you really scared those fuckers upstairs good! This is great, I can win my money back for sure now... Though, not right away, of course.}
{422}{}{Can't wait.}

#Female character
{1212}{}{Ugh, listen, girl, this is a casino. It's obvious what kind of study is going on here... Only one kind of study COULD be going on here... Do you get it yet?... "Study". [he winks at you]}
{1253}{}{Never mind, just passing through.}
{1258}{}{Hey, what's the matter with you? This is a for-sure deal, no joke! I'm begging you, girl - just an eensy-weensy, miserable 50 bucks! One more time! And then we're good! I'll return the money and... You know what, even toss a little extra on top! Just because I like you! I won't just win your... Our money back, I'll hit the fucking jackpot! You just gotta trust me!}
{1307}{}{he drops to his knees] No... Not on the head... I... I'll fix everything... But... I'm broke... Honestly! If someone would buy this lousy kidney, I'd sell it on the spot! But... I'll win everything back... Just give me another 50 - I'll return it all to you and pay you extra! And you've been so good to me, god bless you, I'll throw another extra on top of that! I used to win big on slot machines! I just got unlucky, sister... }
{1308}{}{I must be crazy, but... Here, take it. It's becoming kind of funny to watch at this point.}
{1309}{}{[Knee him in the face] Get lost! And pray, pray on your fucking life that I won't find you!}
{1310}{}{You... Fuck, you're the only one who helps me... Ahhh, fuck! This fucker on the other side is winning again! How does he keep doing it?!}
{1350}{}{[He drops on the floor and smacks his head into the machine] Forgive me, sister! I'm scum, nothing but scum! I'm a piece of shit! Shoot me, do the world a favor!}
{1400}{}{Hey, friend... Decided to shoot me? I don't blame you. I wouldn't expect anything better.}
{1402}{}{Yeah, or slice you up... I haven't exactly made up my mind yet, just wait and pray.}
{1406}{}{I've been thinking about some things in the context of game theory... [write down your calculations to play on this machine]}
{1409}{}{I haven't decided yet. But don't think I'll forget your debt to me.}
{1410}{}{Wow! You're a magician, my friend! No, a mathematician! You're the motherfucking reincarnation of John Nash! A true genius! Just a few days, brother, and then you and I are both rich! For real this time! We'll fuck these scum with their own weapons!}
{1416}{}{My angel! Where have you been? I was thinking about sending someone after you! Let me cut to the chase - I did it! I cleaned this fucking casino dry... Though, I won't be allowed to play here anymore. Once again I thank you - here is your money... And here's that extra I promised you. That's it, I don't need to sit in this shithouse for a minute longer! The lights of Vegas await me!}
{1421}{}{You know, I saw how that mechanic removed the counter from the machine. I guess you really scared those fuckers upstairs good! This is great, I can win my money back for sure now... Though, not right away, of course.}
