{100}{}{You see an excited visitor.}
{101}{}{You see a visitor with a slightly inadequate look.}
{102}{}{Where did it go?! It was just here a minute ago!}
{103}{}{This isn't funny. Shit! Goddamn motherfucking shit!}
{104}{}{Uhh - ! This isn't a good time! Get out of my room!}

#Применение алкоголя
{105}{}{Hey, I won't complain! That hits the spot!}
{106}{}{::hic::}
{107}{}{That... Don't... Ohh...}
{108}{}{He's had enough.}

#Плавающие фразы при наличии журнала
{110}{}{Shit! I've got to keep these pages clean...}
{111}{}{Mine... All mine...}
{112}{}{It's hard to turn the pages with my left hand...}
{113}{}{Yeah, girl... Show it to me...}
{114}{}{I never knew women like this existed.}
{115}{}{Is this really what they look like, when...?}
{116}{}{If only these weren't just photos...}
{117}{}{A dream come true!}
{118}{}{Beautiful!}
{119}{}{What I wouldn't give to have lived then...}

#Плавающие фразы без журнала
{120}{}{Where is it?!}
{121}{}{It was right here!}
{122}{}{How could it have disappeared like that?!}
{123}{}{Could someone have stolen it when I had my eyes closed?}
{124}{}{I should have locked the door! Why didn't I lock the fucking door?}
{125}{}{[Grabs his head and groans]}
{126}{}{I had it and I lost it!}
{127}{}{What am I going to do now?}
{128}{}{I'll have to buy another.}
{129}{}{Here, girls! Come back to daddy!}

#Диалог при поимке
{130}{}{Hey, you stop right there! You took my magazine, I know it. Don't even lie to me! Show me what you're carrying!}
{131}{}{But I didn't...}
{132}{}{Okay, here you go. Sorry for trying to steal from you.}
{133}{}{Put a hand on me and you'll lose more than your magazine.}
{134}{}{Alright, search me. You won't find anything.}

{135}{}{I mean it! Show me everything you've got, or else!}
{136}{}{I knew it! I knew you took it! Don't you try that again, or... Or else!}
{137}{}{Well, well, well.}
{138}{}{Hey, get back here!}
{139}{}{[Run!]}

{140}{}{Shit, you really don't have it...what the hell? Who else could have...?}
{141}{}{You're lucky I let you try that. Next time, I'll give you one of my magazines... One bullet at a time.}
{142}{}{Okay, okay, jeez. I'm sorry, alright?}

{143}{}{Okay, I'm sorry. But... What are you doing here?}
{144}{}{Uh, this isn't my room? Oh, sorry. Too much drinking, I guess.}
{145}{}{None of your business. I go where I want. You'd better stay out of my way.}
{146}{}{Uh-huh. I'm watching you.}
{147}{}{Whatever.}

{148}{}{I knew! I goddamn knew it! If I see you one more time, I'll chop your thieving hands off! Now give me that fucking magazine!}
{149}{}{I hope you choke on it!}
{150}{}{Look, I really want that magazine. How about I buy it off you?}
{151}{}{Okay, you got me fair and square.}

{152}{}{So now you want to cut a deal huh? Uh... Okay, 50 bucks and it's yours. I don't want to give it up, but I need the money.}
{153}{}{Fifty?! I can buy another in any shop for five!}
{154}{}{It's a deal. Here's the money.}
{155}{}{On second thought, I'll be fine without it.}

{156}{}{Don't tell me you got lost again!}
{157}{}{}
{158}{}{Hey, can I buy that magazine off you?}
{159}{}{Aw man, I was sure this was my room this time! Sorry!}
{160}{}{Well... Money's more important than pleasure. Okay. Just be careful not to tear it or... You know.}
{161}{}{See you.}

{162}{}{Fine, fine! I'll take 35 bucks, but you're killing me here! At least then I can eat a decent meal for once...}
{163}{}{Fine, I'll pay 35 dollars.}
{164}{}{Still too rich for my blood. Keep it.}

{165}{}{What?! I bartered a 10mm pistol for this! Is it really only 5 bucks? Fuck! Goddamn it... But I still need to make up for my lost gun, so 50 bucks. No less.}

#Female character
{1132}{}{Okay, here you go. Sorry for trying to steal from you.}
{1134}{}{Alright, search me. You won't find anything.}
{1144}{}{Uh, this isn't my room? Oh, sorry. Too much drinking, I guess.}
{1156}{}{Don't tell me you got lost again!}