{100}{}{You see a receptionist.}
{101}{}{You see elegantly dressed receptionist. He gives you a welcoming smile.}
{102}{}{Sorry, but you'll have to holster that.}

#Начало диалога:
{109}{}{Tell me about this hotel.}
{110}{}{Welcome to the Silver Legacy, the greatest hotel in Reno! It's also the only hotel in Reno, so you might as well book a room now. And while you're here, why not check out the casino? It's been a long road, you should treat yourself!}
{111}{}{What can I do for you?}

{112}{}{I need to talk to the owner. Where is he?}
{113}{}{Did you see that two thugs? One has dreadlocks and the other one carries a crowbar. Where did they go? Please, be honest!}
{114}{}{Why do you let people paint all over your walls outside?}
{115}{}{Okay, but first, tell me about the hotel.}
{116}{}{I need a room.}
{117}{}{I don't need anything right now. I'll just be going.}
{118}{}{I have another question...}
{119}{}{I see. Thanks.}

#Про рэкетиров:
{125}{}{[The receptionist's smile slips off his face, and he glances nervously out the door] Uh... They, uh... The El Dorado, just down Virginia Street... }

#Про граффити-хулигана:
{126}{}{"Let"? Ha! We've tried to stop those doing it, believe me. But we can never catch them in the act. Whoever it is, they're careful.}
{127}{}{Maybe I can catch this artist for you.}
{128}{}{Maybe. Probably not, but it's worth a try. I'll pay you 100 bucks if you can nab them on their crime.}
{129}{}{I'll remember that.}

#Об отеле и о городе:
{130}{}{You are in the one, the only, Silver Legacy! This building's is Reno's main resting place for travelers from the wasteland. Before the war, we were famous for our hospitality and the beauty of our surroundings. We were the gem of the city! Reno's a lot rougher nowadays, but we're fighting to remain the diamond in it.}
{131}{}{The world now is very different from those days. How can the hotel still attract customers?}
{132}{}{People do need to sleep, don't they? Reno still gets people from out of town. Most of our customers are caravan workers, but there's also some refugees from other settlements that want to try their luck in the big city.}
{133}{}{Why do people come to Reno?}
{134}{}{Besides business? Hmm. I'd say the biggest reason is freedom. There's no mayor or sheriff here. Control is in the hands of the common people! And yeah, that can get dangerous, but it's also very appealing to a lot of people, myself included. Anyway, even if you don't want to stay in here, it's a great place to visit. Reno's always been a great place for tourists.}
{135}{}{Tourists? We're living in a wasteland, how much tourism can there be?}
{136}{}{You'd be surprised! Reno was barely touched by the bombs, so a lot of the old entertainment ventures is still intact. If you want a good time, well, just look down the hall to the casino! Or, you can go down Virginia Street and check out the El Dorado. They've got booze, a night club, and even fights in the basement! And don't forget - if you need to rest your head, we're the best in the city.}
{137}{}{What about food and supplies?}
{138}{}{The Silver Legacy has a wonderful restaurant just across the street. You won't find any better food in Reno, that's for sure! And there's a shop next to the caravan parking lot. Whatever you need for the road, you can get it there.}

#Про Теда Банди:
{139}{}{Do you know where 75 Virginia Street is?}
{140}{}{Hmm. Most of the houses don't have numbers up, but that should be somewhere around here. I'd check out the slums on the other side of the street.}
{141}{}{Thanks.}
{142}{}{Do you know of any quiet parts of the city where someone could live safely?}
{143}{}{There's not a lot of safe places in Reno, and even fewer quiet ones! You'd have to find a place without any people. Hmm...if I had to choose somewhere quiet and safe, I'd go to the airport or train station. They don't work anymore, obviously, so no one has a reason to go out there.}

#Снять комнату на сутки:
{149}{}{A room will run you }
{150}{}{ dollars for 24 hours. We only rent by the day, nothing longer.}
{151}{}{I'll take a room, thank you. Here's the money.}
{152}{}{I don't have that kind of money right now. I'll come back later.}
{153}{}{Great! Let me show you your room. When was the last night you slept in a real bed, huh?}
{154}{}{[Follow him.]}
{155}{}{You puked all over the floor! Now who's going to clean this up?}
{156}{}{You feel rested.}

#Джей Кукиш
{160}{}{Were there any bikers staying here? I'm looking for one named Jay Kukish.}
{161}{}{A bunch of bikers came through town recently. They don't usually stay at the hotel, although Mr. Mordino likes to meet them. He used to ride the bike, you know. If you have questions about bikers, you should probably talk to him.}

#Починка вытяжки
{170}{}{Do you have any jobs for me?}
{171}{}{I fixed the vent fan.}
{172}{}{Nah... Well, wait. Do you know anything about technology? There's an empty room on the second floor with a busted air vent fan. I think one of the prior guests was messing with it. If you can fix it, I'll pay.}
{173}{}{I'll take a look.}
{174}{}{Thanks, that takes care of one headache. Here's 100 bucks for your trouble. All the best!}
{175}{}{You're welcome!}

#Семья босса
{180}{}{I'm impressed that your boss can keep this place by himself. He must have no family if he's able to devote this much time to his work.}
{181}{}{Oh no, no, he has a family. He has a wife and a beautiful baby girl. I remember the night he proposed to her at the hotel restaurant. Ah... Romantic. They still eat there sometimes.}
{182}{}{At the restaurant, you say. Good to know.}
