{100}{}{You see Lewis Mordino.}
{101}{}{You see a tired owner of "Silver" hotel.}
{102}{}{Look, I have suffered enough, just leave me alone.}

#Äèàëîã:
{106}{}{I'm listening.}
{107}{}{You're the owner here? Tell me how it all started, please.}
{108}{}{You've gotta know a lot about this city, right? Please, tell me about it.}
{109}{}{Bye.}

#Ïðî ðýêåò
{110}{}{What did those guys want?}
{111}{}{Forget it, it is none of your concern.}
{112}{}{Oh no, you called me your bodyguard. That makes me involved, from where I'm standing.}
{113}{}{Hmm, is that so? Fine. Let's start from the beginning.}
{114}{}{Hmm. My apologies. But please understand, there is a war going in the city. You won't be affected by it, as long as you keep to yourself and steer clear of it. Do you understand?}
{115}{}{War? Tell me about it!}

{116}{}{This war between business leaders has been going on for about ten years. About six years ago, the conflict got a lot bloodier. Some idiot brought in gangs of raiders to put an end to it. But the raiders made their own deal - and shifted the authority.}
{117}{}{[Next]}
{118}{}{The problem is that these raiders could not agree even among themselves. As a result, the city fell into a deep coma for several years. An economic and social crisis ensued - street robberies, food shortages, and a whole heap of other problems. God alone knows what was in the mind of whoever started it, but the present government is clearly incapable of dealing with any of this.}
{119}{}{Which side are you on?}
{120}{}{On my own. As everybody in this city is, really. There are some who think it is easier to join some gang, but I'm trying to stay away from all the conflict and to live a simple businessman's life. Therefore, I do not care who is at the helm. As long as he doesn't put pressure on my way of living, he can sail as he likes.}
{121}{}{Right. Thanks for the clarification.}

#Î ãîðîäå
{130}{}{Well then, welcome to Reno! A truly breathing and bustling city, the Babylon of this hellscape we live in. If you'd like to stay longer, you can have a room. Talk to the receptionist, he's far more talkative when it comes to city's history.}
{131}{}{Well, I got this place by inheritance, but for a long time the building remained empty. When New Reno became a center of active trade with all the other settlements, there was an influx of caravan merchants. This created the problem of having a large number of visiting merchants who had nowhere to sleep for the night. Since I like to learn more about good people from other parts of the wasteland, I was happy to open the doors of this hotel, and the rest, as they say, is history.}
{132}{}{Let's talk about something else.}

#Äæåé Êóêèø
{140}{}{I heard a rumor that you and the bikers are old friends. With one biker in particular, named Jay, for example.}
{141}{}{I've never made a secret of the fact that I like these guys. We often share beers and stories when they're in town. But Jay is not like other bikers. He's fixated on technology and isn't very talkative. Even among his own, he's considered an odd one.}
{142}{}{They say Jay was passing through Reno recently. Is that true?}
{143}{}{Yes, stayed for the night and left in the morning. He seemed to be in a big hurry. He had this peculiar sparkle in his eyes... Most likely, he found something special, but he didn't tell me jack shit about what it was.}
{144}{}{I know what that sparkle is about. I need to contact him immediately, before it's too late!}
{145}{}{Are you sure? These are not the kind of people who will talk to you if they don't like you. Not that it matters much... The bikers, as far as I know, are migrating somewhere to the southeast. They haven't explained why or where. So there's only one way to find out where they are now - to contact them using very good radio equipment. And there's good news and bad news here; the good news is that there is one suitable station in Reno that you could use. The bad news is that it's in an old bunker under the Stryker building, and the entrance is locked.}
{146}{}{That won't stop me. Do you know the call signs and channels I could use to contact the bikers?}
{147}{}{I never knew that. Bikers use their own call signs and communication channels so no one can track them down.}
{148}{}{Maybe they are written down somewhere. Thank you, and goodbye.}
{149}{}{I need to contact Jay before it's too late!}

#Øàíòàæ:
{160}{}{My boss, Mr. Thompson, is losing patience with your stupidity.}
{161}{}{I said all I wanted to say the last time we spoke. I'm my own boss. You'll have to find a very good reason to change my mind about that.}
{162}{}{Give me time to think.}
{163}{}{Perhaps we can make a deal? What are you afraid of?}
{164}{}{After all the intimidation and threats - diplomacy? If Thompson had decided to change his approach to a more delicate one earlier, we might have reached an agreement. But I will never abandon my core beliefs. I am a *free* businessman. Now... prove to me that an alliance with Thompson is more beneficial to me than with Stryker or anyone else.}
{165}{}{I managed to get a recording of one Stryker's meetings. He called you a stubborn fool and plans to replace you, after he seizes power.}
{166}{}{So, what's your final answer to my boss?}
{168}{}{}
{169}{}{}

{170}{}{Hey, Daddy-o! They say that your little wife's titties aren't that bad, eh? Heh-heh...}
{171}{}{[Mordino remains silent for some time, eyes lowered] Wh-what... Do you want...}
{172}{}{Nothing much. Mr. Thompson wants protection money, for you to cut all ties with Stryker, and to use the rooms on the second floor for surveillance. Now take your pick.}
{173}{}{[Long pause] I... Agree...}
{174}{}{Finally. I'll pass that on to him. He'll want to meet you, so be ready.}
{175}{}{[Show him Mrs. Mordino's finger] You know what this is?}
{176}{}{My boss is fed up with you. Either you cooperate, or you go the same way as Stryker. No more warnings.}
{177}{}{Stryker is dead? Hmm... I had thought this fight would never end. Well, then I don't really have a choice.}
{178}{}{Now choose.}

#Íàáîð äëÿ óõîäà
{180}{}{Would a distinguished gentleman like yourself be interested in some fine personal grooming products?}
{181}{}{[He curiously examines your things] Oh my God, that's a full "Pretty & Glamour" body care kit! Impressive. I've given many of these kits over the years, but when supplies ran low I had to keep them for the hotel. This kit could really help me out!}
{182}{}{[Next]}
{183}{}{I'll be happy to buy this from you. How much do you want for it?}
{184}{}{$2000}
{185}{}{$1500}
{186}{}{$1000}
{187}{}{Hmm, I haven't really thought about it. Give me a hot minute to think it over and I'll discuss the price with you.}
{188}{}{That's far too much for just one kit! You'll have to lower the price.}
{189}{}{Uh, no, I'll just find customers who can afford it. Bye.}
{190}{}{Well, that price seems about right. It's worth it. I'll take it.}
{191}{}{Excellent! Let's trade.}
{192}{}{You know, I've changed my mind. Bye.}
{193}{}{I don't need jokes right now. No.}
{194}{}{Sorry, won't happen again.}

#Ëîõîòðîí â êàçèíî
{200}{}{Did you know that someone is rigging the machines in the casino?}
{201}{}{What the hell did you just say! Our casino is the most honest one in the whole city.}
{202}{}{Maybe. But there is evidence that one of the machines has an additional counter. Strange, ain't it?}
{203}{}{Hmm. Well, I'll have to have one of my assistants check the machines. Just so our conscience stays clean.}
{204}{}{And what about the money lost by players?}
{205}{}{Nonsense! We won't give anyone their money back, even if you *prove* that one of the casino employees is a fraud. We don't know who lost money because of him, and even if we did, it would be impossible to prove that they lost because of that and not because of bad luck. Now let me give instructions to my employees.}
{206}{}{Okay then...}

#Female character
{1187}{}{Hmm, I haven't really thought about it. Give me a hot minute to think it over and discuss the price with you.}
{1192}{}{You know, I've changed my mind. Bye.}
