{110}{}{Our boss says hello.}
{111}{}{You again?! I'm sick of you!}
{112}{}{Now, now, calm down. There are people trying to sleep around here.}
{113}{}{Heh-heh... Yeah! You get too excited, and we might just-}
{114}{}{Hold on a second. Who the hell is this?}
{115}{}{Huh?}
{116}{}{This is my bodyguard. I suggest you go tell your boss the answer is still no.}
{117}{}{Fine... Fine. But we will be back.}
{118}{}{Yeah! We'll be back!}
{119}{}{And you, boy... Find a new job. Heroes don't live long in this city.}
{120}{}{What just happened?}
{121}{}{Forget it. This is not your business, don't get involved.}

{122}{}{You think you've just interrupted a shakedown.}

{1115}{}{Who, me?}
{1119}{}{And you, girl... Find a new job. Heroes don't live long in this city.}