{100}{}{You see a sad visitor.}
{101}{}{You see a restaurant patron with a depressed expression on his face.}
{102}{}{Hello again.}
{103}{}{Leave me alone.}

#Beginning of dialogue
{110}{}{[This ordinary-looking man quietly sips from a bottle. He looks lost in his melancholic thoughts.]}
{111}{}{Hey, man, why the long face?}
{112}{}{Hey, you wanna share a drink?}
{113}{}{You know, trying to drink your sorrows away only delays the inevitable.}
{114}{}{Hello, who are you?}
{115}{}{[Leave him.]}

{120}{}{What? [the man slowly looks up] Ah, no, don't worry.}
{121}{}{But I want to know!}
{122}{}{Are you always so reserved?}
{123}{}{}
{124}{}{Well, if you say so.}

{125}{}{Thank you, but I'm not looking to cry on anyone's shoulder.}
{126}{}{If I said I wanted to hear you out, then it's best you start talking.}
{127}{}{Just tell me already.}
{128}{}{You know, you really need to talk it out. Helps much better than alcohol.}
{129}{}{Well, if you say so.}

{130}{}{What?! [he hisses through his teeth] What do you know? Who the hell are you, anyway? Just someone who wandered in from the wastes! [he waves his hand] Leave me alone!}
{131}{}{Fine, chill out... }

{132}{}{Hm? [he gives you an irritated look] None of your business, leave me alone.}
{133}{}{How dare you?! Get on your knees and apologize!}
{134}{}{Sorry, it's probably none of my business... But did something happen?}
{135}{}{Alright, if you say so.}

{136}{}{[He jerks angrily but, at the last moment, stops himself. It seems he isn't prone to violence.] Listen, just leave me alone!}
{137}{}{Ha!}

{150}{}{Hm? [the man looks you over before looking back to his bottle] No, I don't.}
{151}{}{Alright, how about a drink on me?}
{152}{}{Be honest - is it because you don't respect me?}
{153}{}{And if I take it myself?}
{154}{}{Are you always so rude?}
{155}{}{Fine, I'll leave you alone if you're not inclined to talk.}

{156}{}{Ugh, I can stand up for myself, don't worry.}
{157}{}{You? Hah, learn to get your nose out of the bottle first. Ciao, loser.}
{158}{}{Oh, sorry, I didn't mean anything by it... }
{159}{}{Chill out, I'm going.}
{160}{}{Yeah... Of course. Everyone needs to blow off steam from time to time.}
{161}{}{Great. Seems like something happened to you. What's up?}

{162}{}{Yeah, because you come up to me minding my own business and try to... Forget it. Yeah, it's because I don't respect you. You ought to watch your tongue in this town.}
{163}{}{[He raises an eyebrow] Good luck finding a pal around here. I don't make friends over drinks.}
{164}{}{So, you don't respect me?}
{165}{}{Ha! Another product of egocentrism.}
{166}{}{Who? Me?!}
{167}{}{Why? I still won't tell you anything important. I'm an ordinary worker... Just trying to unwind. And you're winding me back up. So... [he waves his hand] ...leave me alone, wanderer.}
{168}{}{Only when wanderers like you pester me. Goddammit, can't I get a quiet drink around here?!}

{169}{}{Yeah, probably. But it's been a while since I've seen people here who I can be open with. [he carefully looks you over] But... You know what the clutches of a snake entail.}
{170}{}{Yeah, probably. But it's been a while since I've seen people here who I can be open with. [he carefully looks you over] But... Where are you from, if you don't mind me asking?}
{171}{}{I'm from Reno.}
{172}{}{I'm from a small settlement up north.}
{173}{}{None of your business.}
{174}{}{Wha-?... }

{175}{}{In that case, my problems are none of yours. All the best, wanderer.}
{176}{}{Is that so... }
{177}{}{Ah... Well, it was nice chatting.}
{178}{}{So that's how it will be... }

{179}{}{Really? I thought there were no settlements apart from some Indians and raiders. It's nice to hear that the wastes have someone with a human face.}
{180}{}{So, what's troubling you?}
{181}{}{Just blowing off steam after a long day.}
{182}{}{Oh, I know the feeling - having to make a choice... Between what and what this time?}
{183}{}{Between hunger with an honest face and selfish satiety. You see, I have a dog, but it got hard to feed her, and now she had a litter of puppies. Wife had a rant that I didn't do anything about it, and we need to feed them and our earnings aren't too good... I had to crush their heads with a sledgehammer. My hands are still shaking at the memories... }
{184}{}{I thought Reno was full of tough people who wouldn't worry about pups.}
{185}{}{Ha! Wastelanders... This might be a tough city, but each man has his own complicated story. If you still haven't understood that, then you will with time.}
{186}{}{Hm. I'll need to think about this.}
{187}{}{Yeah, of course, think. And... You know... Thank you for hearing me out.}
{188}{}{Of course! Any time.}
{189}{}{Pfft! Ha-ha! A man crying about some dead dogs! What a story!}
{190}{}{What the hell do you know?! You think you're some big man? [he hisses through his teeth] You're just some lowlife from the wastes, thinking he's great because he's the biggest animal around. [he waves his hand] Leave me alone. I don't need your "wisdom". Oh, and take these - [he throws a few condoms at your feet] - so the next generation doesn't have to deal with more of you.}
{191}{}{Ha-ha-ha! Bye, loser.}
{192}{}{That must have been awful. I'm sorry you had to go through it.}
{193}{}{Don't worry about - I'll get over it. And... You know... Thank you for hearing me out. Hold on - hey, barkeep! A beer for my friend! I'll pay!}
{194}{}{Oh, thanks for that.}
{195}{}{Enjoy! This city needs people like you. You'll see, with time, Reno will be better thanks to people like you and me.}
{196}{}{Sure, take care.}

#Female version
{1126}{}{If I said I wanted to hear you out, then it's best you start talking.}
{1153}{}{And if I take it myself?}
{1158}{}{Oh, sorry, I didn't mean anything by it... }
{1162}{}{Yeah, because you come up to me minding my own business and try to... Forget it. Yeah, it's because I don't respect you. You ought to watch your tongue in this town.}
{1167}{}{Why? I still won't tell you anything important. I'm an ordinary worker... Just trying to unwind. And you're winding me back up. So... [he waves his hand] ...leave me alone, wanderer.}
{1175}{}{In that case, my problems are none of yours. All the best, wanderer.}
{1185}{}{Ha! Wastelanders... This might be a tough city, but each man has his own complicated story. If you still haven't understood that, then you will with time.}
{1187}{}{Yeah, of course, think. And... You know... Thank you for hearing me out.}
{1190}{}{What the hell do you know?! You think you're some tough bitch? [he hisses through his teeth] You're just some lowlife from the wastes, thinking she's great because she's the meanest animal around. [he waves his hand] Leave me alone. I don't need your "wisdom". Oh, and take these - [he throws a few condoms at your feet] - so the next generation doesn't have to deal with more of you.}
{1193}{}{Don't worry about - I'll get over it. And... You know... Thank you for hearing me out. Hold on - hey, barkeep! A beer for my friend! I'll pay!}
