{100}{}{You see a ghoul.}
{101}{}{You see a mutated sewer dweller.}

#Первый диалог

{110}{}{What? A person?! Are you real? You can't be real... [he reaches out with both hands, shuffling towards you]}
{111}{}{Calm down, I'm definitely real. I think.}
{112}{}{Hands off, zombie! Don't you dare touch me!}

{113}{}{You... [he puts his hands gently on your chest] ...You're real! [he suddenly jumps back, as if his hands were scalded with boiling water] Ahh! Oh my god! When was... How long has it been since I saw a real person?!}
{114}{}{Calm down, I won't hurt you.}
{115}{}{That's right, mutant! Fear me!}

{116}{}{[He jumps back, holding his hands to his chest] No, don't! I just... I just wanted to make sure I wasn't imagining you. It's been so long... Oh my god, how long has it been?!}
{117}{}{Calm down, I won't hurt you.}
{118}{}{That's right, mutant! Fear me!}

{119}{}{But... [he looks around wildly, almost suspiciously] ...But how are you here?! I've never found a way out, and I've been here ten years... Or was it twenty? Without the sun, I can't tell one day from the next...}
{120}{}{Yeah, yeah, you've been here a long time. I get it. Can we move on?}
{121}{}{Oh, right... Yes... Please, tell me, how do I get out?}
{122}{}{Same way I got in. I left a rope leading back up to the street.}
{123}{}{Just think, moron. There's not a lot of space to move around down here. I'm sure you'll figure it out.}
{124}{}{Oh, right, right. Finally... Ten years, twenty years? And now... [he hugs himself, looking scared at the thought of leaving]}

{125}{}{How did you end up down here, anyway?}
{126}{}{It was so long ago. It's hard to remember...}
{127}{}{You again! I'm so glad to see you!}

#Список вопросов
{130}{}{What's your name?}
{131}{}{How did you get here?}
{132}{}{What happened to your skin?}
{133}{}{Where did you live before you end up here?}
{134}{}{Have you tried to get back to the surface?}
{135}{}{So are you going to leave?}
{136}{}{}
{137}{}{}
{138}{}{}
{139}{}{Stay here, I need go somewhere.}

{140}{}{It's... Cruz, I think. No, Crusoe. Or something like that...}
{141}{}{Colin. It was Colin. We'd been drinking and were walking home late at night. Then, he stopped, grabbed me by the shoulders, and... And he tossed me into the sewer hole, saying Shelley would be his! That bastard, I thought we were friends! Friends... Oh, when I had friends...}
{142}{}{My skin? [he looks down at himself] Oh... Right... It wasn't always like this, was it? It was soft, like yours... When did this happen? It was itchy when I first got down here. Then it was hard to breathe, and I got so sick... But that was a long, long time ago.}
{143}{}{Above. Right above... Almost, I think. I hear wheels above sometimes... I think a lot of caravans come through here. And my house was close to the restaurant. Ah, my home... What does it look like now? Is Shelley still there? Is... Is Colin...}
{144}{}{Did I try? Oh, did I try! But the hole I used to get in - it had no ladder, no rope. I tried so hard to climb the wall, but even if I could, how could I open the lid? And so long I tried to squeeze between the bars, but I couldn't. The rats could... So I ate them. That's how I've lived, for years... Sometimes I tried to scream for help, but no one heard me.}
{145}{}{I... I don't know... I'm afraid. It's been so long, I've missed so much... My face, I'm afraid when I see myself in the water. What if they beat me, like those half-wits from the uranium mines? And Shelley! No, Shelley can't know what I'm like now. She must think I died. If she saw me... No, I can't leave now. I'll... I'll come up with something. Somehow.}

{146}{}{Do you want me to talk to Shelley for you?}
{147}{}{Would... Would you do that? For me? [he puts a hand to his mouth, eyes bugging out in intense thought] Be careful, okay? Don't talk to Colin, if he's still there.}
{148}{}{Okay, wait here. I'll bring back news.}
{149}{}{}

#Завершение квеста
{150}{}{Shelley is too beautiful for these sewers, too beautiful for me... And yet she's here. Thank you again.}
{151}{}{WHY?! After all this, everything was as it was before, and now...}
{152}{}{I'm so happy to see you! Shelley and I are together again, like nothing ever happened. Even like this, she remembers me. Even like this, she loves me! What did I ever do to deserve such a wonderful, perfect woman?}
{153}{}{I'm glad everything turned out well. Good luck, both of you.}
{154}{}{Yeesh, I'm going to be sick. Good thing I'm in a sewer.}
{155}{}{Wait, before you go... Take this lighter. I think someone dropped it down the drain. It's all I have to give you. Thank you again. I'll always be grateful to you.}
{156}{}{Thank you. I'll find a good use for it.}
{157}{}{You're giving me something from the sewer? Eww...}

#Female character
{1111}{}{Calm down, I'm definitely real. I think.}
{1113}{}{You... [he puts his hands gently on your chest] ...You're real! [he suddenly jumps back, as if his hands were scalded with boiling water] Ahh! Oh my god! When was... How long has it been since I saw a real person?!}
{1119}{}{But... [he looks around wildly, almost suspiciously] ...But how are you here?! I've never found a way out, and I've been here ten years... Or was it twenty? Without the sun, I can't tell one day from the next...}