{100}{}{You see Billy.}
{101}{}{You see a strange creature that crawled from some stinky hole. It seems to be in a happy mood.}
{102}{}{}
{103}{}{Light... Mother... I'm... Coming...}
{104}{}{I'm just a janitor. Ask that man, he's the owner.}

{105}{}{Z-z-Z-z...}
{106}{}{Finally, the day's over.}

{110}{}{Stop looking at me like that!}
{111}{}{I *know* no one wants me around! You don't need to keep telling me!}
{112}{}{I'M HUMAN TOO!}
{113}{}{All everyone does is laugh at me! Just stop!}
{114}{}{::sniff::}

#Mordino family
{120}{}{I'm at your service, sir!}
{121}{}{Do you know where the Mordino family went? I heard they used to come here often before they disappeared. Why's that?}
{122}{}{Don't worry about it.}

{123}{}{[The boy looks around carefully] Why... Why do you wanna know?}
{124}{}{Well, I'm worried about them. We used to know each other...}
{125}{}{Look what I've got, Billy - a sweet candy. *More* than sweet. You know what I mean, don't you?}
{126}{}{Just tell me what you know and I'll give you something nice.}
{127}{}{Forget it, I'll figure everything out on my own.}

{128}{}{[He narrows his eyes] Are you lying to me? I'd remember if they knew you and I don't think I ever saw you with them.}
{129}{}{Don't worry about it.}
{130}{}{You... You look friendly. Not like those gangsters around town. They make me shiver when they look at me...}
{131}{}{So, can you tell me what happened to the family?}
{132}{}{[Billy quickly glances around the room, then looks up at you with a very unchild-like expression] Yes... Yes, sir. Thank you, sir. This is exactly what I need.}
{133}{}{Err, no thank you, sir. I've seen people like you before. I don't need your "something nice", unless it's... Something important to me.}
{134}{}{They're okay, sir. They sometimes get colds because it's damp down there, but they always get better.}
{135}{}{"Damp down there"? Are they living in a cave or something?}
{136}{}{Oh no, sir! It's just the basement at the train station. It's very nice, sir!}
{137}{}{Alright, that's enough. You can go.}
{138}{}{You found out that the Mordino family is being held in a basement at the train station.}

#Walking the tables
{150}{}{Ugh, it's smeared everywhere...this is so hard to clean...}
{151}{}{Oh boy, someone dropped a candy! Lemme get it...}
{152}{}{Mister businessman is hungry? I'll be quick!}
{153}{}{Mister businessman isn't here again. That's a shame...}
{154}{}{Sirs wanted to eat? Right away! I'll be quick!!!}

{155}{}{* Ahh, sweet loo! My sweetest loo... *}
{156}{}{Maybe someone left something nice here...}
{157}{}{Oh! Someone dropped half a stick of gum! Lemme get it!}
{158}{}{Wow! Someone left a sandwich!}
{159}{}{Someone didn't finish their beer! Mine now.}
{160}{}{::picks through the urinal::}
{161}{}{::quietly pulls a piece of bread from the urinal and quickly sticks it into his mouth::}
{162}{}{A piece of paper! I can wipe with this!}
{163}{}{Chief, this egg is rotten, right? Can I eat it?}
{164}{}{Nothing interesting...}
{165}{}{::glances around nervously::}

{180}{}{Could I bring you something? What do you mean no thank you? You're good as it is? Well, that's odd!}
{181}{}{Chief, can I go take a crap?}
{182}{}{Chief, that egg in the urinal is rotten, right? Can I eat it?}
{183}{}{Chief, I want to sleep...}
{184}{}{Chief, why is your fly down?}
{185}{}{Chief, can I have my candy?}
{186}{}{I wonder if Chief will give me candy today...}
{187}{}{Chief is nice!}

#Female version
{1120}{}{I'm at your service, ma'am!}
{1128}{}{[He narrows his eyes] Are you lying to me? I'd remember if they knew you and I don't think I ever saw you with them.}
{1132}{}{[Billy quickly glances around the room, then looks up at you with a very unchild-like expression] Yes...yes, ma'am. Thank you, ma'am. This is exactly what I need.}
{1133}{}{Err, no thank you, ma'am. I've seen people like you before. I don't need your "something nice", unless it's...something important to me.}
{1134}{}{They're okay, ma'am. They sometimes get colds because it's damp down there, but they always get better.}
{1136}{}{Oh no, ma'am! It's just the basement at the train station. It's very nice, ma'am!}