0. QUICK LOOK (NORMAL)
{100}{}{You see a slot machine.}
1. QUICK LOOK (HIGH-ROLLER)
{101}{}{You see a shiny slot machine.}

0. LOOK (NORMAL)
{150}{}{You see a slot machine. You could swear it's looking at you.}
{151}{}{You see a slot machine. Its body and gilded lever shine seductively at you. reflecting the lights of New Reno's glowing signs.}
{152}{}{You see a shiny slot machine. Minimum bet is }
{153}{}{ coins.}
{154}{}{You see a shiny slot machine.}

2. FLOAT DIALOGUE (PLAYER = DRUNK OR HIGH) (WTG)
{160}{}{*Play with me, cowboy.*}
{161}{}{*Hey, hello, sailor.*}
{162}{}{*Throw a coin, pull the lever. I won't disappoint.*}
{163}{}{*Click... Click... Cliiick... *}
{164}{}{*Hey, beautiful. Come closer, play with me.*}
{165}{}{*Hello, beautiful.*}
{166}{}{*You're cute. Why not play with me?*}

3. FLOAT DIALOGUE (NORMAL) (WTG)
{175}{}{*Ding*}
{176}{}{*Zing*}
{177}{}{*Trrr-pow*}
{178}{}{*Ch-ch-ch-ch*}
{179}{}{*Ding-dong*}
{180}{}{*Blamm*}

4. RETARD (WTG)
{185}{}{You see strange gilded metal box with three eyes and one hand. It's the most beautiful thing you've ever seen.}
{186}{}{Me }
{187}{}{ who you}
{188}{}{Me miss mama. }
{189}{}{ miss Volt. Me want home.}
{190}{}{Shake his hand.}
{191}{}{You strange mutant.}
{192}{}{Bless Volt! Volt!}
{193}{}{You water chip?}
{194}{}{Go look for other shiny things.}
{195}{}{Leave.}

5.  RETARD TALKS TO SLOT MACHINE (4, 5)
{205}{}{The beautiful, three-eyed, one-armed gilded metal box does not respond.}
{206}{}{ME }
{207}{}{ ANSWER ME }
{208}{}{Shake its hand.}
{209}{}{Me from Volt, you speak to me right now.}
{210}{}{You strange mutant.}
{211}{}{You water chip?}
{212}{}{Go look for other shiny things.}
{213}{}{Leave.}

6.  RETARD PULLS HANDLE (4, 5)
{220}{}{You grab its hand and shake it warmly. You hear a *bzzzzzz*and the box starts to talk! "Please... Come on... Give me money."}
{221}{}{Ayyyyyyy! Robot! Bad! Ruuun!}
{222}{}{Leave.}

7.  NO MONEY (WTG, 9)
{225}{}{Ugh, I don't even have money for slot machines. Well, maybe some other time... }
{226}{}{Leave.}

8.  PLAY. . . ? (WTG, 14, 15)
{230}{}{You see a slot machine. Its body and gilded lever shine seductively at you in light of New Reno's glowing signs. The coin slot beckons you, and you feel your face light up in anticipation.}
{231}{}{[Your hand trembles when you dig through your pocket for money. The machine continues to whisper to you.] *Come on, my sweet... Please... Do not tease me... *}
{232}{}{[Your hand trembles when you dig through your pocket for money. The machine continues to whisper to you.] *Well, well, sweet... Like this... Grab the lever... Squeeze it tighter... Come on... *}
{233}{}{You have }
{234}{}{ coins. Risk everything?}
{235}{}{You have }
{236}{}{ coins. Bet }
{237}{}{ coin?}
{238}{}{Bet }
{239}{}{ coins?}
{240}{}{Thats enough for the night.}
{241}{}{Thats enough for the day.}

9.  LOOOOOOSER (8)
{245}{}{The wheel spins, aaand... Nothing.}
{246}{}{NOTHING. NOTHING! You hear how this filthy machine mocks you, and you become overwhelmed by rage... Bouncers are forced to pull your screaming body from the machine.}
{247}{}{[The machine giggles.] *Sorry, honey, but nothing lasts forever. Don't let the door hit your ass on the way out. Ha-ha-ha-ha-ha-ha!*}
{248}{}{You have }
{249}{}{ more coins. Make up for the loss and continue playing?}
{250}{}{You have }
{251}{}{ coins. Risk everything?}
{252}{}{You lost. The party's over for tonight, whether you like it or not.}
{253}{}{You lost. The party's over for today, whether you like it or not.}
{254}{}{Thats enough for tonight.}
{255}{}{Thats enough for today.}

10.  WIN x1 (8)
{260}{}{Three blades. You made your money back.}
{261}{}{[The machine continues whispering.] *Well, dear... This all happens at least once... More... Please try... *}
{262}{}{[The machine continues whispering.] *Well, well, sweet... Try more... Grab the lever... Squeeze it tighter... Come on... *}
{263}{}{You have }
{264}{}{ coins. Continue playing?}
{265}{}{You still have }
{266}{}{ coins. Continue playing?}
{267}{}{Thats enough for tonight.}
{268}{}{Thats enough for today.}

11.  WIN x2 (8)
{275}{}{Three bullets! You have doubled your money!}
{276}{}{[The machine is breathy with pleasure.] *So, dear... Keep pulling the handle... Faster, stronger, faster, come on... *}
{277}{}{[The machine is breathy with pleasure.] *So, dear... Keep pulling the handle... Faster, stronger, faster, come on... *}
{278}{}{You have }
{279}{}{ coins. Continue playing?}
{280}{}{Thats enough for tonight.}
{281}{}{Thats enough for today.}

12.  WIN x3 (8)
{290}{}{Three grenades! Wow! You tripled your money!}
{291}{}{[The machine squeals in pleasure as money spills into your tray.] *Oh, yes! God, yes! Yes! Faster! Stronger! What are you waiting for?! More!*}
{292}{}{[The machine squeals in pleasure as money spills into your tray.] *Ohh! Who's your Daddy?! Who's your Daddy?! Do it again! At this time, pull it harder! Harder!*}
{293}{}{Leap for joy, then take a deep breath and continue.}
{294}{}{Come on, grenades! I need new shoes! [Keep playing.]}
{295}{}{You have }
{296}{}{ coins. Continue playing?}
{297}{}{Thats enough for tonight.}
{298}{}{Thats enough for today.}

13. DRUNK, HIGH OR OTHERWISE FUCKED UP (WTG)
{305}{}{[You see a slot machine. Its body and gilded lever shine seductively at you in light of New Reno's glowing signs. The coin slot beckons you, and you feel your face light up in anticipation. Looking at it, you see one of the windows winks at you and hear a female voice.] *Well, hello, sugar. Spend some time with me?*}
{306}{}{[You see a slot machine. Its body and gilded lever shine seductively at you in light of New Reno's glowing signs. The coin slot beckons you, and you feel your face light up in anticipation. Looking at it, you see one of the windows winks at you and hear a male voice.] *I'd remember a girl like you around here. Where have you been all my life, beautiful?*}
{307}{}{[Pinch yourself.]}
{308}{}{Er... Hello?}
{309}{}{[Take a deep breath, turn around, and leave.]}

14. DRUNK CONVERSATION 1 (13)
{315}{}{*I'm still here, baby... Don't be shy. You want to play, don't you?*}
{316}{}{*Here I am, sugar. Just waiting for a handsome many like you to fill me up... *}
{317}{}{Whoo are yooou?}
{318}{}{Yeah, I waaant... }
{319}{}{Maybe I should leave before I do something I regret.}
{320}{}{[Take a deep breath, turn around, and leave.]}

15. DRUNK 2 (14)
{325}{}{*Looking for something, baby? I can satisfy you in a way you've never known. You'll never know a greater rush... *}
{326}{}{*I'm your dreams come true, sugar. I just need a bit of attention. Just a coin or two for the ride of your life!*}
{327}{}{Can I jussst plaay?}
{328}{}{Yeah, I waaant... }
{329}{}{Maybe I should leave before I do something I regret.}
{330}{}{[Take a deep breath, turn around, and leave.]}

16. DRUNK 3 (15)
{335}{}{*Of course, baby, I'm here. [you feel compassion radiating off the machine] Let daddy make the pain go away.*}
{336}{}{*Of course, sugar, I'm here. [you feel compassion radiating off the machine] Let mommy make the pain go away.*}
{337}{}{I'm on this quest, but I don't know where to find it, and they won't let me back in the vault and... And... [sob]}
{338}{}{I'm on this quest, but I don't know where to find it, and they won't let me back in the vault and... And... [sob]}
{339}{}{I'm on this quest, but I don't know where to find it, and they won't let me back in the vault and... And... [sob]}
{340}{}{I finished the game, and I took the Tirelessness perk, but there's only so much content and... And... [sob]}
{341}{}{Now Fallout's in 3D, and they took out skills, and the protagonist has voice acting and... And... [sob]}
{342}{}{I wanted to make a good character, so I took Gifted, but now everything needs skills and I don't have any points and... And... [sob]}
{343}{}{Now I'm talking to a slot machine! I'm a *loser*!}
{344}{}{[Take a deep breath, turn around, and leave.]}

17. DRUNK 4 (16)
{350}{}{*It's okay, baby... Everything's going to be alright. Just come here and let me take care of everything. Let it out, baby... *}
{351}{}{*Don't worry, sugar. Just hold me. You're going to be okay. Lean on me, sugar... *}
{352}{}{Thanks, slot machine. [sob] You're my only friend.}
{353}{}{I don't know where to go and I don't know what to do and everyone keeps taking my money and... Oh, god... }
{354}{}{[Take a deep breath, turn around, and leave.]}

18. DRUNK 5 (17)
{360}{}{[You rest your weary head on the machine.]}
{361}{}{*Are you okay, baby? I don't want to let you go in such a state.*}
{362}{}{*Are you okay, sugar? I don't want to let you go in such a state.*}
{363}{}{You're the only one who understands me, slot machine. I love you.}

19. DRUNK 6 (18)
{370}{}{[In one of the windows, you see something that just might be a single tear.]}
{371}{}{*This world's full of scoundrels and thieves, but you stay true to yourself, you hear me, }
{372}{}{? Even if it hurts, don't like them change you. Now... You get out of here, you hear me. A woman shouldn't see... Shouldn't see a big, strong slot machine cry.*}
{373}{}{*You're the only real hero in this world of scoundrels and thieves, you hear me, }
{374}{}{. You stay a hero. Don't let this world drag you down. Now get out of here, before I burst into tears.*}
{375}{}{Bye... }

20.  PLAY, HIGH-ROLLING MACHINE. . . ? (WTG, 14, 15, 21, 22, 23, 24)
{380}{}{You see a high-stakes slot machine. The minimum bet is }
{381}{}{ coins. The shining body and gilded lever glint seductively in the light of Reno's flashing lights. The coin slot beckons you, and your heart races in anticipation.}
{382}{}{[Your hand trembles as you count the money. The machine calls to you with faint whispers no one else seems to hear.] *Come on, sugar... Don't tease me, I need it... *}
{383}{}{[Your hand trembles as you count the money. The machine calls to you with faint whispers no one else seems to hear.] *Come on, baby... Grab my handle. Grip it tight, and pull!*}
{384}{}{You have }
{385}{}{ coins. Risk everything?}
{386}{}{You have }
{387}{}{ coins. Bet }
{388}{}{ coins?}
{389}{}{Bet }
{390}{}{ coins?}
{391}{}{Thats enough for tonight.}
{392}{}{Thats enough for today.}

21.  LOOOOOOSER, HIGH-ROLLING (20)
{400}{}{The wheel spins, aaand... Nothing.}
{401}{}{NOTHING. NOTHING! You hear how this filthy machine mocks you, and you become overwhelmed by rage... Bouncers are forced to pull your screaming body from the machine.}
{402}{}{[The machine giggles.] *Sorry, honey, but nothing lasts forever. Don't let the door hit your ass on the way out. Ha-ha-ha-ha-ha-ha!*}
{403}{}{You have }
{404}{}{ coins. Try to make up the loss?}
{405}{}{You have }
{406}{}{ coin. Risk everything?}
{407}{}{No more money. This just isn't your night.}
{408}{}{No more money. This just isn't your day.}
{409}{}{Thats enough for tonight.}
{410}{}{Thats enough for today.}

22.  WIN x1, HIGH-ROLLING (20)
{415}{}{Three bombs. You made your money back.}
{416}{}{[The machine continues whispering.] *Well, dear... This all happens at least once... More... Please try... *}
{417}{}{[The machine continues whispering.] *Well, well, sweet... Try more... Grab the lever... Squeeze it tighter... Come on... *}
{418}{}{You have }
{419}{}{ coins. Continue playing?}
{420}{}{Thats enough for tonight.}
{421}{}{Thats enough for today.}

23.  WIN x2, HIGH-ROLLING (20)
{425}{}{Three nukes! You doubled your money!}
{426}{}{[The machine is breathy with pleasure.] *So, dear... Keep pulling the handle... Faster, stronger, faster, come on... *}
{427}{}{[The machine is breathy with pleasure.] *So, dear... Keep pulling the handle... Faster, stronger, faster, come on... *}
{428}{}{You have }
{429}{}{ coins. Continue playing?}
{430}{}{Thats enough for tonight.}
{431}{}{Thats enough for today.}

24.  WIN x3, HIGH-ROLLING (8)
{435}{}{Three mushroom clouds! You tripled your money!}
{436}{}{[The machine squeals in pleasure as money spills into your tray.] *Oh, yes! God, yes! Yes! Faster! Stronger! What are you waiting for?! More!*}
{437}{}{[The machine squeals in pleasure as money spills into your tray.] *Ohh! Who's your Daddy?! Who's your Daddy?! Do it again! At this time, pull it harder! Harder!*}
{438}{}{Leap for joy, then take a deep breath and continue.}
{439}{}{Come on, mushrooms! I need new shoes! [Keep playing.]}
{440}{}{You have }
{441}{}{ coins. Continue playing?}
{442}{}{Thats enough for tonight.}
{443}{}{Thats enough for today.}

# use gambling skill on table, the +1 is for high roller tables
# critical failures
{1000}{}{These odds don't even out. Something's fishy here... }
{1001}{}{Everything looks on the straight and narrow. They steal your money honestly here.}
# failures
{1005}{}{These odds don't even out. Something's fishy here... }
{1006}{}{Everything looks on the straight and narrow. They steal your money honestly here.}
# success
{1010}{}{Everything looks on the straight and narrow. They steal your money honestly here.}
{1011}{}{These odds don't even out. Something's fishy here... }
# critical success
{1015}{}{Everything looks on the straight and narrow. They steal your money honestly here.}
{1016}{}{These odds don't even out. Something's fishy here... }
