{100}{}{You see Lewis Mordino.}
{101}{}{You see a tired owner of "Silver" hotel.}
{102}{}{Look, I have suffered enough, just leave me alone.}

#Диалог:
{106}{}{I'm listening.}
{107}{}{You're the owner here? Tell me how it all started, please.}
{108}{}{You've gotta know a lot about this city, right? Please, tell me about it.}
{109}{}{Bye.}

#Про рэкет
{110}{}{What did those guys want?}
{111}{}{Forget it, it does not concern you.}
{112}{}{Oh no, you called me your bodyguard. That makes me involved, from where I'm standing.}
{113}{}{Hmm, is that so? Fine. Let's start from the beginning.}
{114}{}{Hmm. My apologies. But please understand, there is a war waging in the city. You won't be affected by it, as long as you keep to yourself and steer clear of it. Do you understand?}
{115}{}{War? Tell me about it!}

{116}{}{There's a war between the business leaders, for about ten years now. The conflict got a lot bloodier about six years ago. Some idiot invited gangs of raiders to bring an end to it all. But the raiders made their own deal - and shifted the authority.}
{117}{}{[Next]}
{118}{}{The problem is that these raiders cannot even agree amongst themselves. As a result, the city fell into a deep coma for a few years - the crisis is economic and social: street robbery, lack of food and a whole heap of problems. Only God knows what was on the mind of the person who started it all, but the current government is clearly unable to deal with any of things going on.}
{119}{}{Which side are you on?}
{120}{}{On my own. As everybody in this city is, really. Yet some do think it is easier to join some gang. I'm trying to stay away from all the conflict and to live a simple businessman's life. Therefore, I do not care who is at the helm of it all. As long as he doesn't put pressure on my way of living, he can sail as he likes.}
{121}{}{Right. Thanks for the clarification.}

#О городе
{130}{}{Well then, welcome to Reno! A truly breathing and bustling city, the Babylon of this hellscape we live in. If you'd like to stay longer, you can have a room. Talk to the receptionist, he's far more talkative when it comes to city's history.}
{131}{}{Well, I got this hotel through my inheritance, but for a long time the building was empty. When New Reno became an active trade center with all the other settlements, there was an influx of caravan merchants. This created the problem of the rowdy and displaced caravan merchants with no place to spend the night. Since I like to learn more about the good people from other parts of the wasteland, I gladly opened the doors of this here hotel, and the rest is, as they say, history.}
{132}{}{Let's talk about something else.}

#Джей Кукиш
{140}{}{Hey. Ya know, I've heard some rumors that you and the bikers are old friends. Like, say, Jay Kukish?}
{141}{}{I do not hide that I like those guys. We often share a few beers and stories when they're in town. But Jay is not like the other bikers. He's fixated on technology and not at all talkative. Even among his own, he is considered an odd one.}
{142}{}{They say Jay rode through Reno recently. Is this true?}
{143}{}{He stayed for the night and left in the morning. Obviously, he was in a real hurry. His eyes had this sparkle in them. Most likely, he found something special, but he didn't tell me jack shit about what it was.}
{144}{}{I know what's that sparkle is about. I need to contact him immediately, before it's too late!}
{145}{}{Are you sure? These are not kind of people, who would listen to you if they don't like you. Not that it matters now. The bikers, last I checked, were migrating to the south-east. They didn't explain why or where they were going. Therefore, there is only one way to find out where they are now - contacting them through a very good radio equipment. Which is where I give you good and bad news; good news is that the city does have one suitable station you could use. The bad news - it is located in an old bunker under Stryker building, and the entrance to it is locked.}
{146}{}{That won't stop me. Do you know the call signs and channels I could use to contact them?}
{147}{}{That, I've never known. Bikers use their own call signs and communication channels, so that no one can track them down.}
{148}{}{I think I may have come across those codes before. Thank you, and good bye.}
{149}{}{I need to contact Jay before it's too late!}

#Шантаж:
{160}{}{My boss, Mr. Thompson, is losing patience with your stupidity.}
{161}{}{I said all I needed to say the last time we spoke, I'm my own boss. You're gonna find a very good reason to change my mind on that fact.}
{162}{}{Give me time to think.}
{163}{}{Perhaps we can make a deal? What are you afraid of?}
{164}{}{Wow - the diplomatic approach after all the intimidation and thugs? If Thompson decided to change the approach to a more delicate one, we could eventually come to a mutual understanding. But I'll never change my core beliefs. I'm a *free* businessman. Now, prove to me that aligning with Thompson is more beneficial to me than with Stryker or anyone else.}
{165}{}{I managed to get a recording of one Stryker's meetings. He called you a stubborn fool and plans to replace you, after he seizes power.}
{166}{}{[Frowns] Stubborn - that's right. But with the rest I can not agree. Besides, Thompson has more chances to seize power in the city. Hmm...}
{167}{}{So what is the final answer to my boss?}
{168}{}{}
{169}{}{}

{170}{}{Hey, Daddy-o! They say that your little wife's titties aren't that bad, eh? Heh-heh...}
{171}{}{[Mordino remains silent for some time, eyes lowered] Wh-what... Do you want...}
{172}{}{Nothing much. Mr. Thompson wants protection money, for you to cut any ties with Stryker, and use of the second-floor rooms for surveillance. Now choose.}
{173}{}{[Long silence] I... Agree...}
{174}{}{Finally. I'll pass that on to him. He'll want to meet you, so be ready.}
{175}{}{[Show him Mrs. Mordino's finger] You know what this means?}
{176}{}{My boss is fed up with you. Either you cooperate, or you go the same way as Stryker. No more warnings.}
{177}{}{Stryker is dead? Hmm... I had thought this fight would never end. Well, then I don't really have a choice.}
{178}{}{Now choose.}

#Набор для ухода
{180}{}{Would a distinguished gentleman like yourself be interested in some fine personal grooming products?}
{181}{}{[He curiously examines your things] Oh my God, that's a full "Pretty & Glamour" body care kit! Impressive. I've given many of these kits over the years, but when supplies ran low I had to keep them for the hotel. This kit could really help me out!}
{182}{}{[Next]}
{183}{}{I'll be happy to buy this collection. How much do you want for it?}
{184}{}{$2000}
{185}{}{$1500}
{186}{}{$1000}
{187}{}{Hmm, I haven't really thought about it. Give me a hot minute to think it over and I'll discuss the price with you.}
{188}{}{That's far too much for just one kit! You'll have to lower the price.}
{189}{}{Uh, no, I'll just find customers who can afford it. Bye.}
{190}{}{Well, that price seems about right. It's worth it. I'll take it.}
{191}{}{Excellent! Let's trade.}
{192}{}{You know, I've changed my mind. Bye.}
{193}{}{I don't need jokes right now. No.}
{194}{}{Sorry, won't happen again.}

#Лохотрон в казино
{200}{}{Did you know that someone is rigging the machines in the casino?}
{201}{}{What the hell did you just say! Our casino is the most honest one in the whole city.}
{202}{}{Maybe so. But there is evidence that one of the machines has an additional counter. Strange, ain't it?}
{203}{}{Hmm. Well, I'll have to have one of my assistants check the machines. Just so our conscience stays clean.}
{204}{}{And what about the money lost by players?}
{205}{}{Nonsense! We will not return the money to anyone, even if you *do* find that one of the workers at the casino really is a swindler. We do won't know who lost money because of him, or even if we did, how much they lost was due to him. Now let me now go give instructions to my workers.}
{206}{}{Is that, so...}

#Female character
{1187}{}{Hmm, I haven't really thought about it. Give me a hot minute to think it over and discuss the price with you.}
{1192}{}{You know, I've changed my mind. Bye.}
