{100}{}{You see a starving hobo.}
{101}{}{You see a homeless man. He looks hungry.}
{102}{}{Not the face! Anywhere but the face!}

#Before feeding him
{110}{}{I'm sorry to bother you sir, but can you spare some bread for a poor man? I'm hungry, you'd be saving a life for sure...}
{111}{}{You have a good view of the hotel from here. I'll give you some food if you can tell me who keeps painting the walls.}
{112}{}{Sure, let's see what I have in my backpack.}
{113}{}{Sorry, I can't help you.}
{114}{}{Get lost, you filthy beggar!}

{115}{}{Oh thank you sir, you're so kind! It's enough to bring tears to my eyes!}
{116}{}{Here you go!}

{117}{}{[He watches you intently as you rummage through your inventory.]}
{118}{}{Here, have some ripe fruit.}
{119}{}{How about some jerky?}
{120}{}{Here's some roasted iguana. Don't swallow it all at once!}
{121}{}{I've got iguana-on-a-stick. Delicious!}
{122}{}{A delicious sandwich should fill you up!}
{123}{}{I can spare some brahmin milk, if you want.}
{124}{}{}

#After feeding him
{150}{}{So, what can you tell me about the graffiti artist?}
{151}{}{Oh, sir, you have no idea how grateful I am for your help! [he wipes tears from his unshaven cheeks]}
{152}{}{Tell me about the vandal painting the Silver Legacy's walls, and I can give you some more food.}
{153}{}{Cheer up, someone else will help you.}
{154}{}{Think nothing of it. I was glad to help.}

{155}{}{Oh, sir, I would do anything for a bite to eat! Anything!}
{156}{}{Hold on, I don't have any food on me at the moment.}
{157}{}{[The beggar savours every bite of your handout, moaning in pleasure] Oh, thank you, sir...he's a boy they call Street Dog. He only works at night, when no one's looking. He's tricky, but not a fighter - he wouldn't dare do anything in the daylight!}
{158}{}{You're lying to me! How could he paint in the dark?!}
{159}{}{Those paintings are too good to be done in the dark. What are you not telling me?}
{160}{}{Oh no, sir, I'd never lie to you after what you've done for me! He comes in the early morning, you see, when it's not so dark. That's the only time there's no people around.}
{161}{}{I see...that's all I wanted to know. I'll be seeing you.}

{162}{}{Like hell! Tell me now, or I'll be feeding you your own ass!}
{163}{}{No, don't! [he throws his arms over his head and cowers] They call him Street Dog! He comes in the early morning, when there's enough light to see but everyone's asleep! That's when he paints the walls! That's all I know, I swear!}
{164}{}{I'll let you live, for now. If you lied to me, I'll be back.}
{165}{}{Now, was that so hard? And to think, you actually wanted to be paid for that...}

#Female Player Copy
{1110}{}{I'm sorry to bother you ma'am, but can you spare some bread for a poor man? I'm hungry, you'd be saving a life for sure...}
{1115}{}{Oh thank you ma'am, you're so kind! It's enough to bring tears to my eyes!}
{1151}{}{Oh, ma'am, you have no idea how grateful I am for your help! [he wipes tears from his unshaven cheeks]}
{1156}{}{Hold on, I don't have any food on me at the moment.}
{1157}{}{[The beggar savours every bite of your handout, moaning in pleasure] Oh, thank you, ma'am...he's a boy they call Street Dog. He only works at night, when no one's looking. He's tricky, but not a fighter - he wouldn't dare do anything in the daylight!}
{1160}{}{Oh no, ma'am, I'd never lie to you after what you've done for me! He comes in the early morning, you see, when it's not so dark. That's the only time there's no people around.}
{1163}{}{No, don't! [he throws his arms over his head and cowers] They call him Street Dog! He comes in the early morning, when there's enough light to see but everyone's asleep! That's when he paints the walls! That's all I know, I swear!}