{100}{}{You see a visitor.}
{101}{}{You see a visitor of the club. He's trying to charm one of the dancers.}
{102}{}{This visitor doesn't want to talk to you.}
{103}{}{ }

{110}{}{She knows how to wear it!}
{111}{}{This eye candy is sweet!}
{112}{}{::hoots::}
{113}{}{::screams::}
{114}{}{::applauds::}
{115}{}{::hysteria::}
{116}{}{Yeaaaah!}
{117}{}{Aaaaaah!}
{118}{}{::squeals::}
{119}{}{Kill me, girl!}
{120}{}{You're the best!}
{121}{}{You're the best, love!}
{122}{}{I need more beer.}
{123}{}{YOU'RE THE BEST. THE BEST!}
{124}{}{Yeee!!!}
{125}{}{TIIITS!!!}
{126}{}{I've never seen anything like this in my life!}
{127}{}{Did you see that, huh?! Did you!?}
{128}{}{Hurt me, beautiful!}
{129}{}{Oh my God!}
{130}{}{I'm your biggest fan, beauty!}
{131}{}{Baby, come to me! Forget that pole!}
{132}{}{Show us your ass!}
{133}{}{Oh, the temptation!}
