{100}{}{You see Terry Deveraux.}
{101}{}{You see a slightly misshapen man. By the look of his face, you'd guess he was born with deformities and life only went downhill from there.}
{102}{}{Now's not a good time.}

{108}{}{Don't worry, I'm going.}
{109}{}{What is it now? You want chems, or bullshit small talk?}
{110}{}{Again?! I'm busy goddammit, how many times do I... Wait a minute, I don't know you. Who are you?! Guards!}
{111}{}{Calm down, I'm here to talk business.}
{112}{}{If you call the guards, you won't live long enough to see them.}

{113}{}{What is it? You need chems?}
{114}{}{Relax. I just want to know who you are and what you're doing.}
{115}{}{Yes. Stryker says you can help me win in the ring.}
{116}{}{You could say that. I need chemicals on an industrial scale.}

#О себе и лаборатории
{117}{}{That's it? Huh, you're more curious than most of these goons. I'm a chemist. [he cocks an eyebrow at you] Funny that Stryker didn't tell you that.}
{118}{}{Yes, but what are you doing *exactly?*}
{119}{}{How long have you been working here?}
{120}{}{How did you got involved with Stryker?}
{121}{}{What does Stryker need with a chemist?}
{122}{}{Forget it, let's talk about something else.}

{123}{}{[He rolls his eyes, exasperated] Chemistry! I'm not going to explain it to you. You wouldn't understand anyway.}
{124}{}{This doesn't look like much of a chemistry laboratory. I don't see any minerals, non-organic substances, or even tools for studying colloid systems. I don't see how that Shroedinger equation on the chalkboard helps, either. If I had to guess, I'd say you want to study quantum theory but are stuck mixing chemicals instead.}
{125}{}{Curiosity killed the cat. Stryker's not a guy that likes to hear questions.}
{126}{}{Fine then, let's talk about something else.}
{127}{}{Holy shit! [his eyes go wide in shock and he actually recoils in surprise] You're the first, the fucking first person I've ever met that knew that! I... Shit! I don't even know what to say! Where'd you learn that?}
{128}{}{A lot of books and even more spare time.}
{129}{}{You too? Hey, you and me, we're a dying breed, you know that? Stryker, you know, he's smarter than he looks, but he's in it for the money. Not you and me, though, we're in it for the *science!* Listen, you ever need to use my lab, I'll give you a friendly discount.}
{130}{}{Thank you, but I have a few more questions.}
{131}{}{Okay, but let's make them snappy. I've got a busy schedule.}
{132}{}{In Reno? More than ten years. I used to distill alcohol for the casinos, back when we had real leaders in charge. Then everything went to shit and it turned out there was more money in chems. I should have gotten out when I had the chance, but... Too late now.}
{133}{}{I have another question.}
{134}{}{That's all. You can get back to work.}
{135}{}{[He scowls] That's a long story, and old story, and a real fucking nasty story. The short version is I've been property to a lot of people, and Stryker's just the last of them.}
{136}{}{What doesn't he? Chems help in a fight, help *after* a fight, and of course, keep the common people weak, dependent, and paying their last dollar to Stryker. [he taps his chin thoughtfully] But you know, sometimes I think he's got something else up his sleeve, too.}

{137}{}{So you're a prisoner?}
{138}{}{Eh... Yeah, but really more a prisoner of circumstances than of Stryker. Chems are so important to Reno, there's no way I could ever be free. Everyone, who's anyone, wants me in their pocket... Or dead, if they can't have me. Freedom's just not an option.}

#Медикаменты для ринга
{140}{}{That's a bad fucking idea, but it's your heart that's gonna explode, not mine.}
{141}{}{How much for a dose?}
{142}{}{What is this stuff, anyway?}
{143}{}{Has this stuff really killed people?}
{144}{}{It'll cost you 720 bucks a pop, but keep in mind: I've got five and only five shots left. When they're gone, they're gone. They need very specialized ingredients that you just can't get anymore. }
{145}{}{The short answer is methamphetamine. The long answer is a complicated chemical compound that's not worth the time to describe. If you're lucky, it'll numb pain and keep you going long after you should have collapsed. If you're unlucky, you'll die. Just another day in Reno.}
{146}{}{Fuck yeah, it has! But let me tell you, they died because of themselves, not me. Those meatheads didn't know their limits. Then again, if people knew their limits, I'd be out of a job. Wouldn't that be a treat?}
{147}{}{Then I don't want it. Let's talk about something else.}
{148}{}{I'll take it.}
{149}{}{How many doses do you want?}
{150}{}{One dose.}
{151}{}{Two doses.}
{152}{}{Three doses.}
{153}{}{Four doses.}
{154}{}{Give me five doses.}
{155}{}{Those were the last I had. You're carrying the last doses in the whole world.}
{156}{}{Pleasure doing business with you. Well, no it wasn't, but you know what I mean.}
{157}{}{That's not all I wanted.}
{158}{}{See you.}

#Производство наркоты
{160}{}{I don't think so. Not unless Stryker says so.}
{161}{}{Can you answer some questions, at least?}
{162}{}{Then I don't need anything from you.}

{163}{}{Strykers says I can only make drugs for our own people, and no discounts. You'll need to supply the components, too.}
{164}{}{Make healing powder.}
{165}{}{Make antidote.}
{166}{}{Make a stimpak.}
{167}{}{Make a super stimpak.}
{168}{}{Make "Horsekiller" poison.}
{169}{}{Make like a canary and answer some questions.}
{170}{}{I don't need anything.}

{171}{}{I'll need }
{172}{}{ dollars, a broc flower, and a xander root.}
{173}{}{ dollars, a flower, a xander root, and an empty syringe.}
{174}{}{ dollars, a stimpak, a Nuka-Cola and a mutafruit.}
{175}{}{ dollars and a radscorpion tail.}
{176}{}{[Make one dose.]}
{177}{}{[Make two doses.]}
{178}{}{[Make three doses.]}
{179}{}{[Make four doses.]}
{180}{}{[Make five doses.]}
{181}{}{[Make ten doses!]}

{182}{}{Okay, I'm done.}
{183}{}{That's not enough. Make more.}
{184}{}{Bye.}
{185}{}{I need more supplies.}

#Про Соломона
{190}{}{Doesn't Stryker work for Big Louie? Why is Louie buying chems from Solomon and not you?}
{191}{}{[He raises an eyebrow] Wait - did Big Louie send you here? Stryker didn't want him to know about this lab! No one outside this building is supposed to know! [he laughs] Serves him right!}
{192}{}{Where does Solomon fit into this?}
{193}{}{Solomon? [he snorts] He's just a useful idiot. Stryker used to buy from him until he put this excuse for a laboratory together. Now he and Big Louie are just loose ends. [he shrugs with a smirk] You know what people like Stryker do with loose ends?}
{194}{}{You mean, Stryker told Solomon to give that poison to Fatso on purpose?}
{195}{}{Sure! Well, I don't know for sure. But that's my best guess. Smart move - either Solomon kills off the whole gang or Big Louie kills off Solomon. Stryker comes out ahead either way.}
{196}{}{Now everything make sense.}

#Поправки текста когда Страйкер мертв
{200}{}{Who the hell are you? I thought everyone ran off when Stryker was killed.}
{201}{}{I could ask you the same question.}
{202}{}{Yeah, you could. [he shrugs] I guess I'm free, huh? Haven't been *that* for a long time. What am I going to do now?}
{203}{}{Maybe, just maybe, you can do something useful with your life.}
{204}{}{Just maybe. I dunno, it's hard to imagine anything useful getting done around here. The city was a lot different the last time I was a free man. Will I even survive? [he sighs] Well. I'll think about it. In the meantime, do you need any chemistry done?}
{205}{}{Curiosity won't do you much good around here. I do chemistry. Mostly.}
{206}{}{Chems have a lot of uses. They can help your soldiers in battle or speed up their recovery after. And just look at the people on the streets - loyal customers. Still... I feel like there's more to it.}
{207}{}{Sure. Stryker's gone, so I can make whatever for whoever. It'll cost you, though, and I'm out of components, so you'll need to supply that too.}

#Побег
{210}{}{Nick Hauer says hi.}
{211}{}{[He freezes in place, then slowly turns to look at you] Nick... Nick is here? He's alive?!}
{212}{}{Yes. He wants to free you and escape to San Francisco.}

{213}{}{Escape?! But he's blind as a bat! How can he... Something happened, didn't it? Ten years - even people who can see are lucky to live that long. Holy shit... He's alive. I can't believe it. Look, I'd leave right now if it weren't for my son and the guards. I'm a prisoner, you get that?}
{214}{}{Can we get past the guards quietly?}
{215}{}{What's the deal with your family?}
{216}{}{Nick seems pretty important to you.}
{217}{}{Give me some time to think.}

{218}{}{Look, I'd leave right now if it weren't for my son and the guards. I'm a prisoner, you get that?}
{219}{}{We could go out the back door, but it's locked. You probably saw my guard when you came in, right? He won't let us walk out. Hmm... He drinks, you know - can you use that?}
{220}{}{I can't go without them. When Stryker finds out I'm gone, he'll find them and he'll make them suffer. I have to bring them with me.}
{221}{}{He... [he covers his eyes] All these years, I've felt so guilty... I was a coward. I can't say I've changed much, but... If he's alive... Maybe I can make things right. I've got to.}
{222}{}{I took care of the guard. Let's get out of here.}
{223}{}{Great! And the back door?}
{224}{}{Just a second, I'll take care of it.}
{225}{}{Forget the back door. No one will stop us, because they're all dead.}
{226}{}{The door's unlocked. We can go.}
{227}{}{Let's go then!}
{228}{}{Forward.}

{229}{}{Escape?! But he's blind as a bat! How can he... Something happened, didn't it? Ten years - even people who can see are lucky to live that long. Holy shit... He's alive. I can't believe it. We just need to get my family and we can go. Better be careful... Even if Stryker's dead, someone in Reno might follow us. The animals on the street can smell hope and desperation.}
{230}{}{Then let's not waste time. Let's go to hotel.}
{231}{}{Give me some time to get ready.}

#Female character
{1112}{}{If you call the guards, you won't live long enough to see them.}
{1117}{}{That's it? Huh, you're more curious than most of these goons. I'm a chemist. [he cocks an eyebrow at you] Funny that Stryker didn't tell you that.}
{1131}{}{Okay, but let's make them snappy. I've got a busy schedule.}
