{100}{}{You see Mom.}
{101}{}{You see the owner of the night club.}

#После изнасилования 'олпой фана'ов
{102}{}{Oh God! What have they done to you?!}

#В момен' убийс'ва Мамаши
{103}{}{After this the club will be closed to you forever.}

################################################################3
#
# С'ар'овые диалоги
#
################################################################3

#Для ГГ-мужчины:
{110}{}{[Looks you up and down] Young man, this is a staff only room. I only allow visitors here to do business, so if you have no business with me, then I have to ask you to leave.}
{111}{}{I need to talk to you.}
{112}{}{No, I have no business with you... }

{113}{}{About what?}
{114}{}{Err, forget it.}
{115}{}{Sure. What do you want to talk about?}

{116}{}{Every girl has potential, you are no exception. But you'll have to bring yourself together. Girls with a look like yours will have trouble turning the crowd on.}

#Для ГГ-женщины
{120}{}{[Studies you from the legs up] What is it, girl?}
{121}{}{I would like to perform in the club.}
{122}{}{I don't even know, I just walked into the wrong room.}

{123}{}{[Studies you from legs up] Oh my, what legs! How can I help you, doll?}
{124}{}{You really think I'm a "doll"? What about a dancing job then? Can I do it?}
{125}{}{I'm glad that you like my legs, but I just walked into the wrong room.}
{126}{}{I understand, but I have to talk to you about something else.}

{127}{}{Mmm... You see, dancing is all about grace and flexibility, and you're lacking that. Just a pretty face won't be enough to turn on the crowd. So, my sweet, we will have to do without you.}
{128}{}{Please! Just let me try!}
{129}{}{Shame... Well, I'll go then.}

{130}{}{I like your dedication. But I know what I am talking about. You have to practice in front of a mirror first.}

{131}{}{What dedication! You look very cute. I think if you really try, you will do very well with the crowd. Oh, yes - what's your name, sweetie?}
{132}{}{.}
{133}{}{You can call me Mom - like everyone does. So, you want to try? Let's see how you move, okay?}
{134}{}{Okay!}
{135}{}{Maybe later. I have some things to do.}

#Первые смо'рины в каморке
{136}{}{What confidence! Okay, show me what you got. }
{137}{}{[Change clothes and show your potential]}

{138}{}{Not bad for the first time. You do have talent. I think you'll manage!}
{139}{}{This is great! Can I know more about the job?}

{140}{}{With pleasure! Babes like you earn $100 a night at the beginning. We will put you in the morning show first - the club is usually almost empty at this time - so we can see you in action and make a final decision.}
{141}{}{And if you decide to keep me?}
{142}{}{If you're really good, you will perform in the afternoon, when the club is full. It's the most profitable time, so I pay $500 an hour. By the way, kitty cat, I don't advise you perform at this time for the first few days.}
{143}{}{Why?}
{144}{}{You know, not every client is well behaved in businesses like ours. Sometimes they are a bit... Troublesome. You have to learn to work with them.}
{145}{}{This sounds a little scary!}
{146}{}{Don't worry about it. Keep yourself together, no matter what the clients do. They may fight in the middle of the show, but you'll have to ignore it and keep dancing. There are some that throw food at you. But believe me baby, this is not an insult, it's the opposite - this means they like you!}
{147}{}{That's nothing! I'll be fine! Honest!}
{148}{}{Ugh! I don't want to deal with such creeps. Take care, sorry to bother you... }
{149}{}{Shame, baby, that's a shame. I hope you will find your courage. We could do good with legs like yours.}
{150}{}{Well, maybe... }

{151}{}{Mmm! I believe in you. Well, then come back in the morning any day you're ready, and we'll put you on the stage.}
{152}{}{Thank you! I will come! Be sure of that!}

#Для де'оубийц
{160}{}{Just like me, all of my girls are very caring towards children. We've seen your face on wanted posters all over the city. Get out of my club.}
{161}{}{[Leave quietly.]}
{162}{}{[Lie] I will explain! This is a setup from my rivals... }
{163}{}{Oh, I understand. If this is true, it explains a lot. I'm not sure I can trust you, but at least you can stay at the club.}
{164}{}{Better than nothing.}

#Для де'оубийц
{170}{}{You had a drunken fight here recently. Do you know anything about it?}
{171}{}{Yes, one of Stryker's men started bothering the girls. When the guards tried to calm him down, he started a fight and injured one of the guards with a broken glass. Our boys threw him out onto the street.}
{172}{}{You do know that Stryker is one of the most powerful people in the city, right? One think you'd be more careful with his men.}
{173}{}{}
{174}{}{Did he wear shades?}
{175}{}{Thanks, that's all I wanted to know.}
{176}{}{Typically we tolerate drunken antics. But with this guy it was different. He thinks too much of himself because of his relationship with Stryker. He thought it would make him invincible. We needed to show that even people like him should follow the rules and behave. If not, then they know that they will receive a baton to the head and be out on the street.}
{177}{}{I don't know anything about it. There was a fight, I didn't care about shades or anything.}

################################################################3
#
# Выс'упления ГГ на 'анцполе
#
################################################################3

#Общая с'ар'овая реплика
{200}{}{Here is our sweet girl! How are you feeling?}
{201}{}{Here is our sweet girl! How are you?}
{202}{}{Here is our sweet girl! You came to conquer the dancefloor?}
{203}{}{Here is our sweet girl! Are you missing the dancefloor already?}

{204}{}{Here is our queen!}

{210}{}{I want to perform!}
{211}{}{Just came by to say hi.}

#Попы'ка напроси'ься на следующее выс'упление
{219}{}{Have you missed the dancefloor? But it's not the time yet. Come around 9 to 10 pm.}
{220}{}{Very good, but this is not a good time. Come by in the morning before lunch, between 8 and 12 am.}
{221}{}{Okay.}
{222}{}{Just in time! Let's go... }
{223}{}{[Change your clothes and get on stage.]}

{224}{}{Come around 6 to 8 pm.}
{225}{}{Fine.}
{226}{}{Have you missed the dancefloor? You're just in time!}
{227}{}{I'm ready!}
{228}{}{Wait, I'm not ready.}
{229}{}{Can't believe you missed the dancefloor so much, right? But it's not the time yet. Come by at 1 am tonight.}
{230}{}{Oh, I like your passion! Well, it's the right time to entertain the audience.}
{231}{}{Wait... [her face changes] You know... I want to say... I'm glad that you still do this. Now is a very tough time for everyone in the city, and to make a whole club work is even harder. But you'll see... Just don't be scared! I didn't mention troublesome clients just for show. There is one really nasty guy. Stay away from him. I wish I could find that son of a bitch. The things I would do to him... He appears from nowhere and does such horrible things to our girls! Look out for... Ted Bundy. Remember this name and avoid it. Okay? Now go to the dancefloor. You've got this, sweetie!}
{232}{}{I'm not afraid of any Ted Bundy. Let's go!}
{233}{}{Great! Let's not waste time - change your clothes and go to your audience. They are waiting for you.}

{234}{}{[Looks at the door, thinking] Mmm. You know, there is a lot of clients out there right now, and they are very excited. Listen! This is a big responsibility - a full club, a whole crowd. Are you really ready, sweetie? Think. I don't want to discourage you, I just want to know if you're in the mood. You can refuse and come some other day.}
{235}{}{You just turned on my appetite! I love risk! I'm ready!}
{236}{}{You're frightening me! I don't want to do it. What if I'm raped right on the stage!?}
{237}{}{Sure, I understand. Come some other time.}
{238}{}{See you.}

{239}{}{Honey, please, sit down, don't be scared! I'm begging you, don't panic, okay? You did amazing today! But a little too amazing!}
{240}{}{Did something happen?}
{241}{}{Nothing yet, but... Oh... Did you see what is happening outside? Your popularity backfired! Just outside the front door there is a whole horny crowd. They want you! The security can barely hold them back. Quick, you have to escape out the back door! We only use it for emergencies, there shouldn't be anyone there. Don't risk your health for your fame!}
{242}{}{I'm getting out of here!}

{243}{}{Please, hurry! They are looking for you!}

{244}{}{It was interesting to work with you, but everything has to end. I hope you're not too upset.}
{245}{}{Fine.}
{246}{}{It's a shame, but I can't risk you or my place. Reno has too many maniacs. It's in your own best interest to stay off the stage.}
{247}{}{I understand... }
{248}{}{I remember our talk, but now is not the best time for dancing. Come by as usual - 9 to 10 pm.}
{249}{}{Everything is ready. The audience is waiting! Come on, baby, make me proud! This is your chance to shine!!!}

#Завершение выс'уплений и получение гонорара
{250}{}{Honey, you'll make it, if you work on yourself. Here is your first payment. I hope you will come again. Come at earlier in the afternoon, we'll see how you do when there are more customers.}
{251}{}{My first payment! Thanks!}
{252}{}{Not bad for the first performance! Girls like you have a future. Come by at the later at the same time and we'll make another show. Oh, yes, here is your money [winks and whispers in your ear] - You did good!}
{253}{}{Thanks.}
{254}{}{You're getting better! Way to go. I've been thinking about it and decided to pay you more - you've earned it! It's time to step up your game. Come from 9 to 10 pm. There'll be more customers, and that means more pay!}
{255}{}{Thank you!}
{256}{}{You know, the crowd was very pleased with your performance. You did good! If you keep improving, our clients will go broke! Ha-ha, just kidding. But you really did it, so here's your well earned money. Rest and come back at the same time. We'll be waiting!}

{257}{}{I'll pay you in a minute! You had an amazing show tonight! The customers were going wild and we made a fortune! You're an idol to every bachelor in Reno! Be careful on the streets from now on, okay? Here is your money. Good girl! And now... Farewell, sweetie.}
{258}{}{Goodbye, Mom! [hug her and leave]}

{259}{}{You earn an achievement for mastering the art of burlesque.}

#Прокаженный
{260}{}{I'm so sorry, but I can't let you in looking like this. Look at you - not one spot left untouched by illness. Nobody will look at your performance, even under a layers of makeup. Sorry.}
{261}{}{Oh no... }

#Плавающие фразы Мамаши во время выс'уплений ГГ
{270}{}{What a body!}
{271}{}{Good girl!}
{272}{}{Yes, slower, honey, slower!}
{273}{}{Yes, come on... Lift that leg a little higher!}

{280}{}{Dear gentlemen! Presenting to you!}
{281}{}{Our new Miss Burlesque!}
{282}{}{You'll *love* her! }
{283}{}{!}
{284}{}{Don't disappoint, baby.}

{292}{}{Gentlemen!}
{293}{}{Meet our most charming }
{294}{}{...Your favorite girl!}
{295}{}{This is her final performance!}
{296}{}{Before you for the last time... }
{297}{}{!}
{298}{}{Oh!}
{299}{}{Rock them sweetie! MUSIC!!!}

################################################################3
#
# Расспросы по линейке квес'ов клуба
#
################################################################3

#Про убийс'во Банди
{300}{}{I have to tell you something about Ted Bundy.}

{302}{}{[Her eyes widen in shock] My God, baby, you saw him?!}
{303}{}{You bet! He came at me with a terrible electric knife shouting he would carve my eyes out! I had no other choice, I had to kill him!}
{304}{}{[She looks even more surprised] My God, baby, you should look at yourself! On one hand, this was probably terrifying, but on the other - you did this city a big favor!}
{305}{}{Are you sure?}
{306}{}{Yes! I... I didn't tell you the whole truth about him. I didn't want you to be scared before you get on stage. You see, he's not just a man, he's a merciless murderer! He used to be our guard, but I started to notice him looking strangely at our girls. It was... Evil!}
{307}{}{Evil?}
{308}{}{After some time he became unbearable, always bothering girls with strange questions, frightening them before they got on stage, the situation just kept escalating... In the end I fired him.}
{309}{}{So he was angry at you?}
{310}{}{I don't know. Maybe. But six months later, in the courtyard next to the back door we found body of one of our dancers. She was so beautiful, so many people loved her performances. There were other attacks after that, always lethal. In three years he took the lives of twelve of our girls!}
{311}{}{But why did he do that?}
{312}{}{I don't think we will ever find out what he was thinking. I don't think we want to.}
{313}{}{Probably not.}

{314}{}{Now life will be easier! You did very good deed. Thank you. If you want, you can have one more night. We will put up a show in your honor! We'll gather a full house! We'll post announcements all over the city! It will be a show of the grandest proportions! Everyone will make a lot of money!}
{315}{}{Great idea!}
{316}{}{You know, I think I've had enough. See you.}

{317}{}{Well then. Get ready and come back in a couple of days, in the afternoon!}
{318}{}{See you later then!}

{319}{}{Of course, as you wish. But if you change your mind - remember, the proposition still stands.}
{320}{}{I will think about it.}

#Про фо'ографию с 'ела Банди
{350}{}{I found a photo on that freak. Do you know who is she?}
{351}{}{Oh, yes. That's Susie, she had such a great body. But she disappeared a long time ago. Pretty girls, like her, don't live long in Reno... [she sighs sadly] You know, this is a very sad story. I don't want to talk about it.}
{352}{}{I understand... }
{353}{}{I told you already and I have nothing more to say. Susie disappeared six months before Ted started his attacks. I don't know what happened to her. But I don't think it was something good.}
{354}{}{Right... }

#Девушка найдена в Вегасе
{360}{}{That girl from the photo - Susie. I found her in Vegas!}
{361}{}{Oh God! It's been so long. It means she survived, did she escape Ted?}
{362}{}{It seems she was the reason Ted lost his mind. Susie couldn't satisfy his sexual desires and they broke up. Then Ted began taking revenge on beautiful women. He cut out their eyes because he always loved to kiss Susie's eyelashes.}
{363}{}{Eww! That's disgusting! I would run away from a man like that too... }
{364}{}{She's in Vegas now, she's a waitress. She is afraid of men, but it seems everything else is very good for her.}
{365}{}{Poor girl! Her whole life was ruined. But I'm happy she found her place. In Reno pretty girls don't have many options.}
{366}{}{Yes, she will be happier there.}
{367}{}{Thank you for telling me this. Now everything makes sense. Don't forget us and stop by sometimes!}
{368}{}{Well of course! See you!}

################################################################3
#
# Прочее
#
################################################################3

#Биле' для Хардинга
{380}{}{I would like to talk to you about a... Troublesome person. His name is Harding.}
{381}{}{Harding? I can't remember anyone by that name.}
{382}{}{He visits the anonymous club for the mentally ill.}
{383}{}{Oh, now I understand. It's not surprising that they don't come to us. Poor people... }
{384}{}{Do you feel sorry for these people? Perhaps you could help Harding then, he is suffering from childhood memories of sexual harassment.}
{385}{}{You feel sorry for these people? Then you and I have nothing more to talk about.}
{386}{}{Perhaps we can discuss this later, but I have to go now.}
{387}{}{You know people change when they are in our club. Everyone's different - sometimes they change for the worse, sometimes for the better. But Harding obviously just doesn't get any attention or care in his life. Our girls could help him, but not beyond the limits of decency.}
{388}{}{Great! Does this mean I can bring him in the club?}
{389}{}{You know, I think I will manage by myself.}

{390}{}{Let's be honest - I can't be sure it isn't a hoax and that the ticket will not go to someone else. So I'll write a complimentary ticket for half price, so that will be... 50 bucks.}
{391}{}{No problem, here is the payment.}
{392}{}{Then no, I will find another way.}

{393}{}{Here's the ticket. And tell Harding that we are waiting for him.}
{394}{}{Thanks!}
{395}{}{Oh, I can trust you. I will get the ticket to the poor guy right away. Tell him that we are waiting for him.}
{396}{}{Thanks, Mom!}

#Female character
{1389}{}{You know, I think I will manage by myself.}
