{100}{}{You see Stryker.}
{101}{}{You see a powerfully-built black man. He looks like someone you don't want to mess with.}

#########################################################################
#
#             Основная часть диалога - квесты
#
#########################################################################

#Первый разговор:
{110}{}{[This man looks like he never stops frowning. He studies you through narrowed eyes.] I'm Stryker. What are you doing here?}
{111}{}{I was just passing by when I saw the place. I thought we might be able to help each other.}
{112}{}{I want one thing: to work for you.}
{113}{}{I just love to learn, you know? I want to know more about you.}

#Допуск к квестам
{114}{}{I'm a busy man. If you don't have anything for me, stop wasting my time.}
{115}{}{[He turns his head to listen to a henchman who whispers something in his ear, then looks back at you] Get the fuck out of here. Tell your boss his next spy goes home in a bag.}
{116}{}{Ah, yes... My boss... }
{117}{}{Yeah? Maybe. But... }
{118}{}{But?}
{119}{}{Right to the point. Good. But how do I know you mean it?}
{120}{}{I want to work for you. I'm serious.}
{121}{}{I need good people, especially from out of town. But how do I know you're good? You got anyone that can vouch for you?}
{122}{}{I can tell it's not a good idea to waste your time, so I'll just go.}
{123}{}{Well... No.}
{124}{}{That runt from the ring said you could find a place for me.}
{125}{}{Yeah - Big Louie himself. Remember where you came from.}
{126}{}{I already helped you with the Devero situation. Just ask your goons.}
{127}{}{I saved one of your people from Bertolini.}
{128}{}{I have nothing to prove to you. My actions speak for themselves.}
{129}{}{Give me a chance! I'm sick of playing the small game - I want to move on to the big leagues!}
{130}{}{Yeah... You've got potential. And more importantly, Thompson doesn't know you. That's good.}
{131}{}{I'm ready for serious work, just as long as there's serious pay at the end of it.}
{132}{}{I'll do everything I can.}
{133}{}{I'm putting you on a practice run first. Don't fuck it up, and you'll get paid when the job's done.}
{134}{}{Of course. What is it?}
{135}{}{There's a guy named Patrick, making a lot of friends in the slums. Whatever he's planning, I don't need it. Deal with him.}
{136}{}{You mean you want me to kill him?}
{137}{}{Consider it done.}
{138}{}{What, are you afraid to get your hands dirty? I don't need pussies here! You got a problem, you can walk out that fucking door!}
{139}{}{Okay, okay, I get it. I'm going.}
{140}{}{I'll do the job. I just wanted to make sure.}

#Мормонский квест
{141}{}{I think it's better to keep him alive.}
{142}{}{Yeah? Why?}
{143}{}{You're making a mistake... }
{144}{}{Patrick spreads the word of God. He's convincing people to be peaceful. Isn't that helpful to you? Kill him, and the people in the slums won't just become angry, they'll become violent.}
{145}{}{Actually, never mind. You'd know best.}
{146}{}{A mistake? A MISTAKE?! Who the fuck are you?! I'm the boss here - when I tell you to do something, you get it fucking DONE! Now get the fuck out! Next time I see you, you'd better have that preachers fucking HEART in your hand!}
{147}{}{Hmm... That makes sense. Okay, the job's off. Of course, that means no pay.}
{148}{}{It can't be helped.}
{149}{}{}

{150}{}{About that job... }
{151}{}{What about it?}
{152}{}{It's totally taken care of. Nothing to worry about at all.}
{153}{}{I think it would be better to leave Patrick alive.}
{154}{}{That Mormon missionary is out of the picture.}
{155}{}{Good. Now I know you're serious about me... Or my money. Either one's good if you get the job done. Here's your pay.}
{156}{}{Thanks.}

#Квест на поставку компонентов
{160}{}{I need a courier whose face isn't associated with me. That means you. Here's 1000 bucks - that's for the job, not you. You steal from me, and it won't matter where you run, we'll find you.}
{161}{}{What's the money for?}
{162}{}{There's a guy near the nightclub holding some chemicals for me. I want a long relationship with him, so I want this to go smooth. And I don't want anyone to know I'm stocking up on chemicals, so don't let on this is for me. Got it?}
{163}{}{Got it. I'll go pick up the shipment.}
{164}{}{Okay, enough bullshit. Time for somre real work. [he places a camera on the table] I want pictures of Thompson's headquarters under the old city hall. Get every corridor and inner door. Thompson doesn't know you, so you should be able to get in, but don't let them see you taking pictures.}
{165}{}{No problem.}
{166}{}{I've got the chemicals.}
{167}{}{[He checks the package's contents, then hands it to a henchman] Take this to the lab. I want results tomorrow. [he turns to you] Basic job. You get 100 bucks.}
{168}{}{I understand. No problem.}
{169}{}{Not much, but it's something.}

#Квест на фотосъемку
{170}{}{What do I need to photograph, again?}
{171}{}{I've finished the job. Here's the camera and the photos.}
{172}{}{[He glowers at you] Listen this time. I want pictures of the corridors in Thompson's headquarters so we can understand its layout. Small rooms like bathrooms don't matter to me, but I want all the hallways and corridors. And for fuck's sake, don't let anyone see you doing it!}
{173}{}{Good. [he peers at the photos] Hnnh... Looks defensible... Gonna be tough... }
{174}{}{What's going to be tough?}
{175}{}{Ahem. My payment?}
{176}{}{[He glances at you] Not now. Anyway, here's your money. [without looking, he reaches into a drawer and hands you a wad of bills]}
{177}{}{Alright. Got any more jobs?}
{178}{}{[He points a finger at you without looking up from the photos] Don't interrupt me again. Last warning. [he reaches into a drawer and hands you a wad of bills] Here's your money.}
{179}{}{Got any more jobs?}
{180}{}{Yeah, I got something in... [suddenly, a henchman leans over and whispers something in his ear] ...You're sure? Hmm... Didn't see that coming. [he turns to you] No, nothing. You can go.}
{181}{}{Uh, okay... }
{182}{}{Yeah, I got something in mind for you. [he crosses his arms and gives you a very serious look] So you've probably figured out I'm trying to get rid of Thompson, yeah? He thinks this city needs a dictator to straighten it out, but he's wrong. You can't just *make* a businessman give you the shirt off his back. A brahmin won't make any milk if you don't feed it, get it? [he leans forward slightly] You undertand, right? This isn't just about money or power. What we're doing here... It's about the city. The future of everyone in Reno depends on us. I want you to know this.}
{183}{}{I understand. What do you need me to do?}

{184}{}{[He pulls out a little box and carefully places it on the table] We did some good things with those chemicals you delivered. This contains one of them. Here are poisoned contraceptives. You need to slip it to Betty Paige and her whores. Understand?}
{185}{}{Yes... Actually, no. What do a bunch of prostitutes have to do with your plans?}
{186}{}{I don't care who you want killed, if the money's good enough.}
{187}{}{I don't wan't to know the details. Let it be on someone else's conscience. I'll do the job and take my money when it's done.}
{188}{}{No... I can't. I can't simply murder a woman like this.}
{189}{}{It's time to take the fight to Thompson. Betty Paige is his madam, his lover... His Achilles' heel. Her death will put him off-balance and give me the edge I need. History shows how women can be the downfall of great men. That's why I'm a bachelor.}
{190}{}{[He studies you silently for a while, then nods] I understand. You can leave... But never come back.}
{191}{}{[Leave.]}
{192}{}{[Nods] You've got your orders. You'll be paid after Paige's... Tragic accident. And that better be how it looks, by the way - I don't want this getting traced back to me.}
{193}{}{Got it.}
{194}{}{There's clearly more to this story. What's this about, really?}

{195}{}{...I can tell you what this is all about, but it's a long story. You don't need to hear it if you're just in it for the money.}
{196}{}{Give me the details.}
{197}{}{Actually, I don't have time. See you.}
{198}{}{Thompson and I were in the same gang. About five years ago, one of the Reno locals asked our boss, Big Louie, to help him in the civil war. Boss stepped in and then decided he'd rather rule the city himself. Once he had everything he wanted though, something changed in him.}
{199}{}{What changed?}
{200}{}{Louie, he was from Reno himself. He wanted to bring back the "Golden Age" when everyone had enough, but he realized he couldn't do it. Reno's just not the same place it was back then. Big Louie couldn't take it and fucked off to the wasteland, leaving Thompson and me in charge. Thompson was supposed to hold the mayor's office and I was in charge of the local defense. We were supposed to be partners, but it didn't work out.}
{201}{}{Why?}
{202}{}{Because running a city ain't like the gang shit we were doing before, you get it? You can't keep this many people in line with just violence. You need to *lead* them. You need an *idea* that makes them *want* you in charge. And Thompson and I have different ideas. Thompson just wants to enslave everyone, like just after the Great War, when the mayor forced people to work and crushed any resistance. But those were different times. It won't work now.}
{203}{}{So what's your idea?}
{204}{}{Once Thompson's out of the way, I'll lead a militia strong enough to keep order. Then I'll organize the business leaders into a guild that make decisions for the town as a group. The militia will protect the guild and get a percentage of their profits in return. [he snaps his fingers] Simple as that.}
{205}{}{Do you really think the business leaders will be willing to share power?}
{206}{}{Yeah, yeah, they'll bitch and moan, but the truth is they've been fighting forever and it's only caused them trouble. How long can this go on? They'll come around, especially when they figure out what'll happen if they're the only ones *without* the militia's help.}
{207}{}{Don't you want to be something greater than just the head of the militia?}
{208}{}{What else can I do, now that I'm neck-deep in this city's shit?! I told you, the old gang tactics won't work here. This isn't the wasteland, it's a city. The people here are smart and organized. But there's a good side to that - this city could do great things once I straighten it out. Once that happens... Being head of the militia will be enough for any man.}
{209}{}{Now I get it. Well, gotta go mind my own business. Thanks for explaining.}
{210}{}{Betty Paige is dead.}
{211}{}{[He gives you a cunning look, then pulls out 100 dollars] That's all. Not enough? Then I'm sure you can find another job, since you've been working so many angles in this town. At this point, I need people who are fighting for more than just money. Take your payment and go - I don't need you anymore.}
{212}{}{[Leave.]}
{213}{}{It was an easy job, so there's not much pay. But if we pull this next job off, we're golden.}
{214}{}{Thanks for the cash, but what are you up to?}
{215}{}{Finally! So, what do I have to do to get rich?}
{216}{}{It's time to go for Thompson's throat. We've got to take the town hall, and you're gonna help us.}
{217}{}{Wait, you want me to attack Thompson's headquarters? I'm not much of a fighter, you know... }
{218}{}{Wait, you want me to attack Thompson's headquarters? This is going to be awesome!}
{219}{}{Your photos show he's got video feeds in his bunker, and I know he's got reinforcements on radio. You're gonna take out the power in his bunker so we can catch him by surprise. Once you've done that, give the signal to my men. They'll be waiting near the town hall.}

#О политике
{220}{}{Hmm... I wonder what Big Louie would say if he knew what you were doing?}
{221}{}{[His eyes narrow] Watch yourself. He already knows... Not that I care. I don't live to do his bitch work.}
{222}{}{Isn't he your boss?}

{223}{}{He's useful right now, so I keep him happy with a Christmas present here and there. But I'm more than able to do business without him.}
{224}{}{Christmas presents? Seriously?}
{225}{}{What are your plans for this war?}
{226}{}{Thompson and you are from the same gang, right?}
{227}{}{Why can't you work together with Thompson? Together, you could control the whole city.}
{228}{}{Forget it, I don't want to dig into your life.}

{229}{}{Yeah, seriously! You delivered the last one, didn't you? Big Louie needs chems, guns and ammo for his gang. He's practically begging. I need them too, but I can spare enough to maintain our relationship.}
{230}{}{No one really knew what was coming when Big Louie took Reno. I didn't think it would be this goddamn *complicated*. You can't control Reno because *no one* controls Reno - the whole city's a bunch of small parts, every one with their own people and rules. We didn't have enough men to manage it all, especially since people were demanding changes from day one. It was chaos. Fuck, it still is!}
{231}{}{[Leave.]}
{232}{}{The only choice is to set up a central authority and get everyone to fall in line. But the business leaders wouldn't want that, and they're the ones we need on our side. So, I'll have to make friends, make deals... Make it worth their while. They'll come around eventually. As soon as I get one in, they'll see the benefits and the others will follow.}
{233}{}{The boss left each of us in charge of different parts of the city. But Thompson's a dreamer - he wants absolute power over everything in Reno. That includes me, and I don't like that idea. But even if he wanted to share power... We just couldn't. We're too goddamn different.}
{234}{}{I live in the real world, he doesn't. He basically wants to be Reno's dictator. You wouldn't think that's a good way to make friends, but he's got a lot of support. It took me a while to figure out why - the common people here have *never* been free. Everyone's a slave, even if they don't call them that - to their employers, or their pimps, or their landlords, or their drug dealers. They don't know any other way to live, and Thompson uses that. But you know, the common people don't really matter. It's the business leaders you need on your side, and they don't want a dictator, which means it's *never* going to happen. We can't just wipe out our opponents in one night and put our own people in place - not in a city this size, with this many leaders. That gang war shit doesn't cut it on this scale. I've spent the last five years learning that.}

#Финальный квест
{240}{}{Once you're done your part, you can go. I don't need you to fight. I won't say no if you want to help, though. In the meantime, I'll get my people ready.}
{241}{}{We've taken the town hall. Thompson is dead.}

{242}{}{Finally! [he sighs in relief] Reno's going to remember this day. It's the first day of the future! Makes me want to crack open a bottle of whiskey... But you deserve a lot more than that.}
{243}{}{[Next.]}
{244}{}{[He counts out your payment] You know, I don't think anyone else in this place could have done what you did for me. I won't forget that. I'm telling everyone I work with to give you a discount, and if you ever need to use the lab, it's yours. If anyone in this city gives you shit, give them my name. It's about to get a lot more respected.}
{245}{}{Thank you. And I'll try not to tarnish your good name.}
{246}{}{I can help in the fight, but I'll need a weapon.}
{247}{}{[He makes a gesture, and a henchman gives you a submachine gun in surprisingly good condition] You get the job done, and that's yours to keep. Take two stimpaks, too - Thompson won't go down easy.}
{248}{}{Thanks, boss.}
{249}{}{[He nods] Good to see you.}
{250}{}{Now, we got to get to work. I gotta get the business leaders under me while they're still off-balance over Thompson. It's not your kind of work, so I hope you can find something to keep you busy. I won't have any jobs for you for a long time.}
{251}{}{No problem, boss.}

#Постразговоры
{260}{}{I'm curious - where'd you get the weapons for the assualt on Thompson's headquarters?}
{261}{}{I traded some of the medicine we cooked to the Wind of War for weapons. You picked up some of the chemicals I used for that, remember?}
{262}{}{I see.}

#########################################################################
#
#             Вторичная часть диалога - расспросы и сторонние квесты
#
#########################################################################

#Квест Большого Луи:
{300}{}{One phrase: "Dogs should remember who is at each end of the leash."}
{301}{}{[His frown tightens as his eyes narrow... And then crumbles into a bemused smirk] What?}

{302}{}{What do you mean, what? Big Louie said this would remind you.}
{303}{}{Don't play stupid. Big Louie wants his tribute.}
{304}{}{Uh, maybe I got that wrong. Let me go check with Big Louie and get back to you.}

{305}{}{[He crosses his arms and continues smirking] Oh, yeah?}
{306}{}{[Chuckles] Hey everyone, check out this bad motherfucker! Oh, Louie must be *really* mad! [everyone looks at you and snickers]}
{307}{}{You're testing Big Louie's patience. That's a bad idea. You're also testing mine. That's worse.}
{308}{}{Yeah, yeah, you're a big man. Just give me the tribute so I can get out of here.}

{309}{}{And what if I just throw you out? What then?}
{310}{}{Then I pull my weapon and go from room to room, killing everyone I find, until I get what I came for.}
{311}{}{I'll put my foot up your ass for starters. I'll play it by ear from there.}
{312}{}{I'll go back to Big Louie, tell him you refused, and wait for his judgment.}
{313}{}{What's with the twenty questions?! Just give me the tribute already!}
{314}{}{Let me think about it... }

{315}{}{[He shakes his head] That wasteland raider shit don't work in the city. You'd better figure that out, fast. [he motions to his henchmen] Bring this goon the tribute. And you, tell Big Louie I didn't forget anything. And I won't forget *this*, either. [he laughs, and you're not sure whether he's laughing at you or Big Louie]}
{316}{}{I thought you'd take your boss more seriously.}
{317}{}{I'll bring him the package, but I'll think about what happened here. Ciao.}
{318}{}{[He suddenly frowns] The "boss" ran away with his tail between his legs, and left us here to do business. I keep in touch because he might be useful, not because I *have* to. Now get out. You've got what you want.}
{319}{}{Listen, I don't exactly like his gang. Maybe I can work for you instead?}

#Подготовка к рингу:
{330}{}{I need some chems for fighting in the ring. The ringleader said I should talk to you.}
{331}{}{Hmm. My little man knows his business. If he sent you to me, you must be legit.}
{332}{}{Then, will you help me?}
{333}{}{If you've got the cash, then you can use my lab. But no one knows it came from me, got it?}
{334}{}{I'm off to the lab, then.}

#Проникновение в бункер
{340}{}{Can you get me into the fallout shelter behind your building?}

{341}{}{Why should I? I'm the one that locked it up. What the hell do you want in there?}
{342}{}{I'm, uh, interested in the Vaults. I think I can learn more there.}
{343}{}{[He rolls his eyes] It's just an old evacuation shelter. There's nothing there but rats and rot. If there's anything, it's in the control room, and *no one* can get that open.}
{344}{}{If there's nothing in there, then why'd you lock it up?}
{345}{}{I'd like to try anyway. Can you unlock it for me?}
{346}{}{Fine, for now. We'll discuss this again later.}
{347}{}{[He leans forward, glowering] BECAUSE, if we do ever get into that control room, it could be useful for us - thick walls, a radio station, maybe electricity. But people like you would just steal shit or fuck up the place. It would be stupid to just leave it open.}

{348}{}{Why the fuck would I have put a lock on if I was just gonna give the key to anyone who asks?}
{349}{}{Stryker, you know you can trust me. I won't disappoint you.}
{350}{}{I can make it worth your while. Say... $1000?}
{351}{}{What would Big Louie say if he knew you were treating his right-hand man like this?}
{352}{}{Stryker, please, you're too stressed out about this. I can see it in your handsome face. Would it change your mind if I helped you... Relax?}
{353}{}{No, I *don't* know I can trust you. You haven't earned that yet.}
{354}{}{Fine, take the key. Don't waste my time with this again.}
{355}{}{No problem.}
{356}{}{[He raises an eyebrow] Fine, but no refunds when you realize there's nothing down there.}
{357}{}{Take the money.}
{358}{}{[He looks you up and down] Yeah... I've been working too hard lately. Come with me... }
{359}{}{Fuck off! This is my headquarters, not a whorehouse! People do *real* work here! And believe me, bitch - I can do a hell of a lot better than you!}
{360}{}{[He is neither generous nor gentle. When he's finally finished, your body aches in several places.]}
{361}{}{... So will you let me into the bunker?}
{362}{}{[Follow him.]}

#Крыша для концерта в Коттон-клубе
{370}{}{I represent the Cotton Club. We'd like to make a deal for you to provide protection at an upcoming concert.}
{371}{}{Hmm, reminds me of the old days... Good idea, coming to me with this. Okay, but I want 25% of the concert's proceeds, jurisdiction over the club, and use of its walls for my campaigns.}
{372}{}{We agree to these conditions.}
{373}{}{We'll consider your conditions.}
{374}{}{Good. I'll send someone to work out the details.}
{375}{}{That's all.}

#Female character
{1111}{}{I was just passing by when I saw the place. I thought we might be able to help each other.}
{1112}{}{I want one thing: to work for you.}
{1113}{}{I just love to learn, you know? I want to know more about you.}
{1126}{}{I already helped you with the Devero situation. Just ask your goons.}
{1127}{}{I saved one of your people from Bertolini.}
{1131}{}{I'm ready for serious work, just as long as there's serious pay at the end of it.}
{1147}{}{Hmm... That makes sense. Okay, the job's off. Of course, that means no pay.}
{1153}{}{I think it would be better to leave Patrick alive.}
{1155}{}{Good. Now I know you're serious about me... Or my money. Either one's good if you get the job done. Here's your pay.}
{1175}{}{Ahem. My payment?}
{1178}{}{[He points a finger at you without looking up from the photos] Don't interrupt me again. Only warning. [he reaches into a drawer and hands you a wad of bills] Here's your money.}
{1180}{}{Yeah, I got something in... [suddenly, a henchman leans over and whispers something in his ear] ... You're sure? Hmm... Didn't see that coming. [he turns to you] No, nothing. You can go.}
{1182}{}{Yeah, I got something in mind for you. [he crosses his arms and gives you a very serious look] So you've probably figured out I'm trying to get rid of Thompson, yeah? He thinks this city needs a dictator to straighten it out, but he's wrong. You can't just *make* a businessman give you the shirt off his back. A brahmin won't make any milk if you don't feed it, get it? [he leans forward slightly] You undertand, right? This isn't just about money or power. What we're doing here... It's about the city. The future of everyone in Reno depends on us. I want you to know this.}
{1184}{}{[He pulls out a little box and carefully places it on the table] We did some good things with those chemicals you delivered. This is one of them. They're poisoned contraceptives. You need to slip it to Betty Paige and her whores. Understand?}
{1192}{}{[Nods] You've got your orders. You'll be paid after Paige's... Tragic accident. And that better be how it looks, by the way - I don't want this getting traced back to me.}
{1211}{}{[He gives you a cunning look, then pulls out $100] That's all. Not enough? Then I'm sure you can find another job, since you've been working so many angles in this town. At this point, I need people who are fighting for more than just money. Take your payment and go - I don't need you anymore.}
{1215}{}{Finally! So, what do I have to do to get rich?}
{1229}{}{Yeah, seriously! You delivered the last one, didn't you? Big Louie needs chems, guns and ammo for his gang. He's practically begging. I need them too, but I can spare enough to maintain our relationship.}
{1261}{}{I traded some of the medicine we cooked to the Wind of War for weapons. You picked up some of the chemicals I used for that, remember?}
{1301}{}{[His frown tightens as his eyes narrow... And then crumbles into a bemused smirk] What?}
{1305}{}{[He crosses his arms and continues smirking] Oh, yeah?}
{1310}{}{Then I pull my weapon and go room to room, killing everyone I find, until I get what I came for.}
{1318}{}{[He suddenly frowns] The "boss" ran away with his tail between his legs, and left us here to do business. I keep in touch because he might be useful, not because I *have* to. Now get out. You've got what you want.}
{1347}{}{[He leans forward, glowering] BECAUSE, if we do ever get into that control room, it could be useful for us - thick walls, a radio station, maybe electricity. But people like you would just steal shit or fuck up the place. It would be stupid to just leave it open.}
{1351}{}{What would Big Louie say if he knew you were treating me this way?}
{1353}{}{No, I *don't* know I can trust you. You haven't earned that yet.}