{100}{}{You see the commander.}
{101}{}{You see the assault team's commander.}
{102}{}{Tell Stryker what happened.}
{103}{}{The building is in our hands. Go tell Stryker the good news.}

{104}{}{You see a team member.}
{105}{}{You see a member of the assault team.}

{110}{}{Talk. Did you sabotage the defenses?}
{111}{}{The bunker has no power. It's as vulnerable as it can be.}
{112}{}{Then it's time to strike. Are you with us or not?}
{113}{}{Of course. I wouldn't miss a fight like this!}
{114}{}{I'm not. You'll have to do this without me.}

{115}{}{Right. Let's move!}
{116}{}{[Begin the assault]}
{117}{}{Then stay out of the way. Better yet, report back to Stryker and tell him we are taking over the bunker.}
{118}{}{[Go to Stryker's headquarters]}
{119}{}{Actually, I changed my mind. I want to help capture the bunker.}

#Женские реплики
{1119}{}{Actually, I changed my mind. I want to help capture the bunker.}