{100}{}{You see a mother.}
{101}{}{You see a child.}
{102}{}{You see one of the Mordinos.}
{103}{}{Guards! Guards!!!}

#Диалог
{110}{}{Please don't kill us!!!}
{111}{}{Well, well, well. Isn't that the sweet Mordino family. You should have hid from Mr. Thompson.}
{112}{}{Stay here and don't move until I come back.}

{114}{}{[She holds her daughter tighter] Wait - we'll go peacefully! Just don't hurt us!}
{115}{}{We'll see. Now move it!}
{116}{}{You have captured the Mordino family.}

{117}{}{Who were those guys? Stryker's security?}
{118}{}{I don't know! My husband hired them! They're just mercenaries, they only serve money!}