{100}{}{You see a bodyguard.}
{101}{}{You see a grim bodyguard. You can tell he's really good at his job.}
{102}{}{You can enter.}

{103}{}{Stop right there! What do you want?}
{104}{}{I need to see the courier about a deal.}
{105}{}{Nothing.}
{106}{}{Go on in. If I see a weapon, I shoot. No warnings.}
{107}{}{Okay...}
{108}{}{Go on in... But put away the weapon. If I see it again, I'll shoot you.}