{100}{}{You see a representative.}
{101}{}{You see a man with a serious look, sent on someone's behalf.}
{102}{}{We're done here.}

{103}{}{Who are you?}
{104}{}{I represent Mr. Thompson. We know about your deal with Stryker's gang and would like to present you a counter-offer.}
{105}{}{I know about your arrangement with Stryker. I suggest you to reconsider.}
{106}{}{I'm here to prevent your business with Stryker. Permanently. [Attack]}

{107}{}{I like my terms with Stryker. Why should I back on them?}
{108}{}{Stryker is dead. His gang can't do it without him. Even the fact that I could get close to you proves they don't know what they're doing.}
{109}{}{Because Thompson's going to win this war. And when he does, he'll take all drug dealers under his control. Do you really think one chemist on Stryker's side is going to make a difference?}
{110}{}{You make a good point. Alright, I'm in. Let Thompson send someone to hash out the details.}
{111}{}{Good. I hope you're not planning on playing both sides...}
{112}{}{Really?}
{113}{}{Just a warning, that's all. I'm leaving.}
{114}{}{If you do, Mr. Thompson won't forget it. Believe me, he's a much more formidable enemy than Stryker. One chemist on Stryker's side won't give him the strength to provide a good defense.}
{115}{}{Uh... Well, Thompson's just way cooler than Stryker, don't you think?}
{116}{}{This is childish. Leave.}
{117}{}{Well, I warned you.}

#Женские реплики
{1106}{}{I'm here to prevent your business with Stryker. Permanently. [Attack]}
{1113}{}{Just a warning, that's all. I'm leaving.}
{1117}{}{Well, I warned you.}
