{100}{}{You see your contact.}
{101}{}{You see the man Thompson was talking about.}

{109}{}{Go look somewhere else. After Stryker's death, the people here are on edge. If you eat a bullet, it's your own fault.}

{110}{}{Hold it! What are you doing here?}
{111}{}{Looking for you.}
{112}{}{Just looking around.}
{113}{}{Go look somewhere else. Stryker doesn't like people poking around his territory.}
{114}{}{Fine.}
{115}{}{[He glances around] Really?}
{116}{}{"You're as small as a bug..."}
{117}{}{"...or huge, like a whale..." Right, we need to talk. Now.}
{118}{}{What happened?}

#Old text:
{119}{}{Страйкер собирается заключить сделку по поставкам оружия. Я расскажу все, что знаю, но у меня есть условие - я хочу перейти к Томпсону и побыстрее.}
{120}{}{В рядах Томпсона презирают перебежчиков. После разборки со Страйкером тебе спуску не дадут, даже не надейся. Тебе лучше убраться отсюда, и подальше.}
{121}{}{Запахло жаренным? Это верно - грядет расправа над всей бандой Страйкера. И ты окажешься под огнем, если вовремя отсюда не сорвешься. Я передам Томпсону твое пожелание.}
{122}{}{Так вот оно как - решил продать себя подороже? Это называют "политической проституцией". Тьфу! Но так и быть - возможно... *возможно* Томпсон тебя примет.}
{123}{}{Правда? Я пропал! Ты говоришь, мне лучше бежать... Что ж, у меня выхода нет. Придется залечь в одной из этих мелких деревушек, заняться фермерством или охотой. Наверное, надо сразу так и сделать.}
{124}{}{Вау, меня примут, правда? Круто! Давно мечтал перейти к нему, честно! Но не так-то это просто, ну ты ведь понимаешь?}
{125}{}{Что ты! Просто раньше я, э, иначе думал. А потом узнал об идеях Томпсона и, э, прозрел! Честно! Но я буду стараться, от меня будет прок, только дайте шанс!}
{126}{}{Да-да, а теперь поговорим о сделке Страйкера.}
{127}{}{}
{128}{}{}
{129}{}{Э, вот этого я не смог выяснить... Но знаю, что данные хранятся в терминале в комнате с генератором. Пройти туда можно через черный ход, но двери заперты.}

#New text:
{130}{}{Stryker's men are about to cut a big deal. I know when and where, but before I tell you, I want a thousand dollars, cash.}
{131}{}{Is that money worth more than your life?}

{132}{}{Fuck off with that. I'm taking a huge risk here. I need that money to... Look, it doesn't matter. No money, no info.}
{133}{}{Hmm, that's the cost of a Nevada Express ride to Salt Lake City, isn't it? Better git while the getting's good, am I right?}
{134}{}{Alright, here's the money. Now tell me everything you know.}
{135}{}{I'll find the information without you. So... Say goodbye, snitch!}
{136}{}{I don't need you - I'll find everything out on my own. Now get out of my way.}
{137}{}{I'll bring in what you need.}
{138}{}{So, where's the money?}
{139}{}{Goddamn it, of course I get the one person on Thompson's payroll with half a brain! Fine, you're right - I'm fucking sick of this place. Day after day it's just more fighting, assassinations, patrols, raids - they say it's all for a bright future, but it's bullshit! It doesn't matter who's in charge, they're all going to look the same when their boots are stomping down on your face. I'm not letting this be my fucking life.}
{140}{}{Does it have to be cash? I can cut out the middleman and get you a ticket instead.}
{141}{}{I understand.}
{142}{}{I don't care as long as I'm on that bus.}
{143}{}{I got you a Nevada Express ticket.}
{144}{}{Come to papa! That's just what I need. And don't even think of following me - I'll be watching.}
{145}{}{I held up my end of the bargain. Tell me about Stryker's deal.}
{146}{}{Great. That should be enough. And don't even think of following me - I'll be watching.}
{147}{}{Okay, listen. Stryker's cutting a deal with a Wind of War to get munitions and medical supplies. They're signing the contract soon. The actual shipments will come later.}
{148}{}{When and where are they signing the contract?}
{149}{}{They're meeting on the second floor of the Silver Legacy hotel. The room is reserved already. Stryker's men are just securing the place.}
{150}{}{Got it. That should be enough. Now, get out of here.}
{151}{}{Thanks for the info. Now I don't need you anymore. [Attack.]}
