{100}{}{You see your contact.}
{101}{}{You see the man Thompson was talking about.}

{109}{}{Go look somewhere else. After Stryker's death, the people here are on edge. If you eat a bullet, it's your own fault.}

{110}{}{Hold it! What are you doing here?}
{111}{}{Looking for you.}
{112}{}{Just looking around.}
{113}{}{Go look somewhere else. Stryker doesn't like people poking around his territory.}
{114}{}{Fine.}
{115}{}{[He glances around] Really?}
{116}{}{"You're as small as a bug..."}
{117}{}{"...or huge like a whale..." Right, we need to talk. Now.}
{118}{}{What's going on?}

#Old text:
{119}{}{Ñòðàéêåð ñîáèðàåòñÿ çàêëþ÷èòü ñäåëêó ïî ïîñòàâêàì îðóæèÿ. ß ðàññêàæó âñå, ÷òî çíàþ, íî ó ìåíÿ åñòü óñëîâèå - ÿ õî÷ó ïåðåéòè ê Òîìïñîíó è ïîáûñòðåå.}
{120}{}{Â ðÿäàõ Òîìïñîíà ïðåçèðàþò ïåðåáåæ÷èêîâ. Ïîñëå ðàçáîðêè ñî Ñòðàéêåðîì òåáå ñïóñêó íå äàäóò, äàæå íå íàäåéñÿ. Òåáå ëó÷øå óáðàòüñÿ îòñþäà, è ïîäàëüøå.}
{121}{}{Çàïàõëî æàðåííûì? Ýòî âåðíî - ãðÿäåò ðàñïðàâà íàä âñåé áàíäîé Ñòðàéêåðà. È òû îêàæåøüñÿ ïîä îãíåì, åñëè âîâðåìÿ îòñþäà íå ñîðâåøüñÿ. ß ïåðåäàì Òîìïñîíó òâîå ïîæåëàíèå.}
{122}{}{Òàê âîò îíî êàê - ðåøèë ïðîäàòü ñåáÿ ïîäîðîæå? Ýòî íàçûâàþò "ïîëèòè÷åñêîé ïðîñòèòóöèåé". Òüôó! Íî òàê è áûòü - âîçìîæíî... *âîçìîæíî* Òîìïñîí òåáÿ ïðèìåò.}
{123}{}{Ïðàâäà? ß ïðîïàë! Òû ãîâîðèøü, ìíå ëó÷øå áåæàòü... ×òî æ, ó ìåíÿ âûõîäà íåò. Ïðèäåòñÿ çàëå÷ü â îäíîé èç ýòèõ ìåëêèõ äåðåâóøåê, çàíÿòüñÿ ôåðìåðñòâîì èëè îõîòîé. Íàâåðíîå, íàäî ñðàçó òàê è ñäåëàòü.}
{124}{}{Âàó, ìåíÿ ïðèìóò, ïðàâäà? Êðóòî! Äàâíî ìå÷òàë ïåðåéòè ê íåìó, ÷åñòíî! Íî íå òàê-òî ýòî ïðîñòî, íó òû âåäü ïîíèìàåøü?}
{125}{}{×òî òû! Ïðîñòî ðàíüøå ÿ, ý, èíà÷å äóìàë. À ïîòîì óçíàë îá èäåÿõ Òîìïñîíà è, ý, ïðîçðåë! ×åñòíî! Íî ÿ áóäó ñòàðàòüñÿ, îò ìåíÿ áóäåò ïðîê, òîëüêî äàéòå øàíñ!}
{126}{}{Äà-äà, à òåïåðü ïîãîâîðèì î ñäåëêå Ñòðàéêåðà.}
{127}{}{}
{128}{}{}
{129}{}{Ý, âîò ýòîãî ÿ íå ñìîã âûÿñíèòü... Íî çíàþ, ÷òî äàííûå õðàíÿòñÿ â òåðìèíàëå â êîìíàòå ñ ãåíåðàòîðîì. Ïðîéòè òóäà ìîæíî ÷åðåç ÷åðíûé õîä, íî äâåðè çàïåðòû.}

#New text:
{130}{}{Stryker's men are about to cut a big deal. I know when and where, but before I tell you, I want a thousand dollars, cash.}
{131}{}{Is that money worth more than your life?}

{132}{}{Fuck off. I'm taking a huge risk here. I need that money to... Look, it doesn't matter. No money, no info.}
{133}{}{Hmm, that's the cost of a Nevada Express ride to Salt Lake City, isn't it? Better git while the getting's good, am I right?}
{134}{}{Alright, here's the money. Now tell me everything you know.}
{135}{}{I'll get this information without your help. So... Say goodbye, snitch!}
{136}{}{I don't need you - I'll find everything out on my own. Now get out of my way.}
{137}{}{I'll bring what you need.}
{138}{}{So, where's the money?}
{139}{}{Goddamn it, of course I get the one person on Thompson's payroll with half a brain! Fine, you're right - I'm fucking sick of this place. Day after day it's just more fighting, assassinations, patrols, raids - they say it's all for a better future, but it's bullshit! It doesn't matter who's in charge, they're all look the same when their boots stomps down your face. I'm not going to let this become my fucking life.}
{140}{}{Does it have to be cash? I can cut out the middleman and get you a ticket instead.}
{141}{}{I understand.}
{142}{}{I don't care as long as I'm on that bus.}
{143}{}{I got you a Nevada Express ticket.}
{144}{}{Come to papa! That's just what I need. And don't even think of following me - I'll be watching.}
{145}{}{I held up my end of the bargain. Tell me about Stryker's deal.}
{146}{}{Great. That should be enough. And don't even think of following me - I'll be watching.}
{147}{}{Okay, listen. Stryker's cutting a deal with Wind of War to get munitions and medical supplies. They're signing the contract soon. The actual shipments will come in later.}
{148}{}{When and where are they signing the contract?}
{149}{}{They're meeting on the second floor of the Silver Legacy hotel. The room is already reserved. Stryker's men are securing the place.}
{150}{}{Got it. That should be enough. Now, get out of here.}
{151}{}{Thanks for the info. Now I don't need you anymore. [Attack.]}
