{100}{}{You see a mercenary.}
{101}{}{You see a suspicious man. He doesn't look very friendly.}
{102}{}{Talk to the boss, not to me.}

################################################################
#          Диалог
################################################################

{110}{}{Hey! This is our turf, get out.}
{111}{}{You look like a bunch of dogs off their leash. What are you up to?}
{112}{}{Fine, I'm leaving.}

{113}{}{[His hand gradually moves to his holster, and his eyes flit erratically between you and the others] We're not playing games. Get out, or you'll have to deal with all of us. And that'll just be the beginning for you.}
{114}{}{Who do you work for?}
{115}{}{Let's cut to the chase. I'm here for the Mordinos, and I'm taking them one way or the other.}
{116}{}{We work for ourselves. Where the money is good. Now fuck off!}
{117}{}{I don't know you. Whoever sent you, tell them to send someone I know or Mordino himself. No one else gets near them.}
{118}{}{No, you don't get it. I'm going to kill you, then take them by force. [Attack]}
{119}{}{Uh... Sure. I'll do that.}

################################################################
#          Разное
################################################################

{130}{}{This door is locked with a key.}
{131}{}{It's some strange type of lock you haven't seen before. You'll need the key to open it... Or just smash the door down.}
{132}{}{Locked.}
{133}{}{Unlocked.}
{134}{}{That made a lot of noise.}

################################################################
#
#        Переговоры (авторы текста: Kerb и BlackDesigner)
#
################################################################

{200}{}{ }
{201}{}{Hey, how are you today?}
{202}{}{I'm good.}
{203}{}{Great! You know what that means?}
{204}{}{What?}
{205}{}{You're good enough to go fuck yourself! Ha-ha-ha!}
{206}{}{That's the worst joke I've ever heard.}
{207}{}{Then you should feel right at home! Ha-ha-ha!}
{208}{}{ }
{209}{}{Hey, cheer up, man! What's the matter?}
{210}{}{Did you hear? Another one of Mom's girls was found with her eyes carved out.}
{211}{}{Again?! Man, who the fuck is this guy?}
{212}{}{I know, right? What a psychopath.}
{213}{}{I mean, I'd cut out the tongue and ears. But eyes? What a nut!}
{214}{}{ }
{215}{}{So I've been buying from that ugly son of a bitch with a ring, recently.}
{216}{}{Risky. How's it been going?}
{217}{}{It's been good so far. I think he's legit.}
{218}{}{Yeah, well, I've heard things. I'd be careful.}
{219}{}{Anyway, I've started writing a list of people I ought to kill.}
{220}{}{Yeah? How many?}
{221}{}{Uh, around 20, I think?}
{222}{}{Ha! Small fry! Mine's at least 50!}
{223}{}{Oh yeah?}
{224}{}{Yeah!}
{225}{}{You know, I think I just found number 21!}
{226}{}{Hey, cool down there, buddy. Don't push yourself too hard!}
{227}{}{Why not? It's not like there's anything else to do!}
{228}{}{ }
{229}{}{Look, you know I never complain about anything.}
{230}{}{And?}
{231}{}{So I want to get some things off my chest now.}
{232}{}{Like what?}
{233}{}{Just a lot of things that piss me off...}
{234}{}{Go on, then.}
{235}{}{Now, I'm not talking about things that just annoy me...}
{236}{}{Get to the point already, for fuck's sake!}
{237}{}{...but stuff that just makes me want to kill!}
{238}{}{ }
{239}{}{First, it's the security in the casino. I'm tired of this shit!}
{240}{}{You're not the only one.}
{241}{}{These guys just go through all my stuff, for no fucking reason!}
{242}{}{Yeah?}
{243}{}{They say it's to protect the casino, but you know what?}
{244}{}{What?}
{245}{}{You order food at the bar, and they'll give you the knife themselves!}
{246}{}{This is really what pisses you off?}
{247}{}{Where's the logic, right? They give the fucking knife!}
{248}{}{What can I say? You're right.}
{249}{}{Just a bottle of whiskey's enough to kill someone!}
{250}{}{You're not wrong!}
{251}{}{What if I was a boxer or something, huh? What if I could kill with my fists?}
{252}{}{Not like they can take those away.}
{253}{}{So this whole security thing - it's stupid!}
{254}{}{Yeah, it doesn't make much sense.}
{255}{}{But you know what REALLY pisses me off?}
{256}{}{You're not done?}
{257}{}{These fuckers in the casino with their cigars!}
{258}{}{What's wrong with cigars?}
{259}{}{When's it going to fucking end?!}
{260}{}{ }
{261}{}{These rich motherfuckers always have to smoke...}
{262}{}{ }
{263}{}{...smoking a big brown dick!}
{264}{}{Ha!}
{265}{}{Yeah, that's right! A big brown dick in their mouth!}
{266}{}{Ha! You tell 'em!}
{267}{}{Oh, and another thing that pisses me off...}
{268}{}{Yeah?}
{269}{}{These fuckers with a barbed wire tattoo on their arm.}
{270}{}{Like they think it makes them a tough guy, right?}
{271}{}{Yeah. Those need their fucking asses kicked!}
{272}{}{ }
{273}{}{Man, I'd love to knocking their fucking teeth out...}
{274}{}{That's all?}
{275}{}{You know what would happen if you smacked them over the head with a baton a few times?}
{276}{}{What?}
{277}{}{They'd go down like a fucking rock!}
{278}{}{ }

#Female character
{1115}{}{Let's cut to the chase. I'm here for the Mordinos, and I'm taking them one way or the other.}