{100}{}{You see a militiaman.}
{101}{}{You see a member of Thompson's assault team. He is waiting for your instructions.}
{102}{}{Watch out. These bastards could be anywhere.}

{110}{}{Do you have something for us?}
{111}{}{Surveillance is down, you're good to go.}
{112}{}{Remind me, what do you need?}
{113}{}{Nothing to report yet, I'm still working on the diversion.}
{114}{}{The HQ is monitoring the area. Disable or destroy their surveillance system.}
{115}{}{Okay.}
{116}{}{Good, then let's get down to business. If you don't have the guts, you can go report back to Thompson. If not, we could use an extra gun. It's gonna be a hell of a fight.}
{117}{}{I'm with you! I wouldn't miss it for the world!}
{118}{}{My work here is done. You'll have to do this without me.}

{119}{}{I like your attitude. Let's show these punks where they belong!}
{120}{}{[Begin the assault]}
{121}{}{Then stay out of our way. It's time for the real men to get to work.}
{122}{}{[Go to Thompson's headquarters]}
{123}{}{Wait, I changed my mind. I want to help you fight.}

#Женские реплики
{1123}{}{Wait, I changed my mind. I want to help you fight.}