{100}{}{You see a bodyguard.}
{101}{}{You see a bodyguard and he sees you.}
{102}{}{You have completed Luciano's task.}

{103}{}{You're right, I *have* been working too hard.}
{104}{}{At least someone understands me... Friend.}
{105}{}{::snores::}
{106}{}{The guard dozes off. He probably won't be out for long, so it's best to hurry.}
{107}{}{The hell is this? You expect me to drink this swill? Just get me some beer.}

#Floating dialogue on talking (male char)
{110}{}{Don't distract me.}
{111}{}{Hold it! What do you want?}
{112}{}{Stryker said I could pass.}
{113}{}{I can't go in there?}
{114}{}{[He speaks with a mocking tone] No, you *can't* go in there! No one does unless Stryker says so, and I don't remember him saying anything about you.}
{115}{}{No problem.}
{116}{}{Fine, just don't distract the egghead for too long.}
{117}{}{No problem.}
{118}{}{I'll be quick. I have a message from his wife. She's worried, you know?}
{119}{}{Why didn't you say so? Come right through.}
{120}{}{I'm not falling for that. Stryker gives the order, I let you through.}
{121}{}{[Hand over $100] I understand, Stryker is very... Strict. Won't even let a man see his wife. How would you like it if that was you?}
{122}{}{Hmm... Fine, ten minutes.}
{123}{}{Thanks.}

#Female version
{1104}{}{At least someone understands me... Friend.}
{1118}{}{They won't let his own wife see him?! What kind of people are you?! Let me through!}	