{100}{}{You see a revolutionary.}
{101}{}{You see one of Stryker's supporters.}
{102}{}{You completed Luciano's task.}

{103}{}{Good to see you.}
{104}{}{How's the boss?}
{105}{}{Ah, if only I was this close to the boss...}
{106}{}{You and Stryker are great friends.}

#Floats while attempting to talk
{110}{}{I've got nothing to say to you.}
{111}{}{Stryker's the boss here, talk to him.}
{112}{}{Keep moving. Stryker doesn't tolerate loitering.}
{113}{}{Uh-huh. What else?}
{114}{}{No one to talk to? Eh, I feel you...}
{115}{}{I'm not here to chat.}