{100}{}{You see a crazed fan.}
{101}{}{You see an admirer who is mad with lust. Looks like he is going to tear you apart!}

{102}{}{Open the door!}
{103}{}{Hey!}
{104}{}{Where are you, baby?!}
{105}{}{I'm talking to you!}
{106}{}{Come out, sweetness!}
{107}{}{No more hiding!}
{108}{}{We'll drag you out of there if we have to!}
{109}{}{Where are you?! WHERE?!}
{110}{}{Stop hiding!}
{111}{}{You can't stop us! We'll find you!}
{112}{}{I've wanted you for so long!}
{113}{}{I've got some candy for you, girl!}
{114}{}{I need you!}
{115}{}{We know you're in there!}

{120}{}{ }

{150}{}{[The crowd is upon you before you can reach for your weapon. Dozens of strong hands pull off your clothes and grope every inch of your body. The noise and chaos is overwhelming. You are forced to the ground in the middle of the street and held there with an immovable weight. You cannot move or even breathe.]}
{151}{}{[Endure]}
{152}{}{You were brutally raped by the crowd!}
