{100}{}{You see a hardened militiaman.}
{101}{}{You see the Racer.}
{102}{}{You see one of Stryker's minions.}

#Обычные реплики
{110}{}{Yeah?}
{111}{}{What next?}
{112}{}{Nothing, just wanted to say hi.}
{113}{}{Nothing. Bye.}
{114}{}{This was a nice chat, but I have to go.}

#Знакомс'во:
{120}{}{What the fuck do you want? [he groans] Oh god... After the party last night my head's killing me.}

{121}{}{Headache? Then your hero has arrived! [give moonshine]}
{122}{}{Headache? Then your hero has arrived! [give beer]}
{123}{}{Headache? Then your hero has arrived! [give "Bloody Mary"]}
{124}{}{Headache? Then your hero has arrived! [give "Rot Gut"]}

{125}{}{Who are you?}
{126}{}{I just have some questions... }
{127}{}{Okay, okay, I'm leaving.}

{130}{}{Would you just fuck off? [he rubs his temples] I'm not in the mood to answer any questions. I can't even think right now.}
{131}{}{In all my time working for Stryker, this is the first time I've seen someone like you here.}
{132}{}{That's right. They don't call me the Racer for nothing. When I get going, I don't like to slow down.}
{133}{}{Racer, huh? Well, nice to meet you.}

{134}{}{Really? You're a lifesaver. Hey, sit down and talk for a bit - I don't like to drink alone.}
{135}{}{[Next]}
{136}{}{...so, like I tell all the rookies, get a spare and strike will happen by itself!}
{137}{}{You must a knowledgeable player.}

#Расспросы
{140}{}{Tell me about your boss.}
{141}{}{What are you all doing here?}
{142}{}{You people seem like the real deal. Can I join?}
{143}{}{Someone's trying to put pressure on the owner of the Silver Legacy hotel. Do you know anything about that?}
{144}{}{Are Stryker's people living in the railway station basement?}

{145}{}{Stryker's dead. Why are you still hanging around here?}

{150}{}{Stryker? Big Louie left him in charge of the city five years ago. Stryker's a man with a plan - things are about to change around here, and he's going to be in the center of it.}
{151}{}{This is Stryker's headquarters. It used to be a bowling club, if you can believe that. Stryker's trying to rebuild it, but that's a long way off. When that day comes though - man! This place, full of games and drinks and people having a good time? Just imagine it!}
{152}{}{You'll have to ask Stryker, but he doesn't take just anybody. You'll need someone to vouch for you. And, uh, if you do get in... Just a word of advice. Never, *ever* contradict him.}
{153}{}{Probably that prick Thompson again. He really wants that place, but the owner's dead-set on staying independent. He can't hold out forever, though... It's just a matter of who finally gets through to him.}
{154}{}{Beats me. Stryker only tells us what we need to know. But they could be - we've got a lot of sticks in the fire, if you know what I mean.}

{155}{}{I... I don't know. At first I thought we could make it without him, but... Some of us have taken off, others have been killed by Thompson's gang. If this keeps up, I'm going to have to leave the city.}

#Соломон
{160}{}{Do you know Solomon?}
{161}{}{Mmmmmaybe. Why?}
{162}{}{Someone in the El Dorado basement recommended him to me. He said you could help me find him.}
{163}{}{You mean the little guy? Okay, that changes things. Yeah, I can hook you up. We don't need him anymore, but we're still in touch.}
{164}{}{We?}
{165}{}{Uh... Never mind that. Not important. I can set you up with Solomon, but you have to do me a favor first.}
{166}{}{What do you need?}
{167}{}{Alright, here goes. Our last party was at Mom's nightclub. I got drunk and, uh... I might have got a little rowdy. See, I don't *exactly* remember what happened. The point is, I'm now banned. Unfortunately, I left my mirrored sunglasses there, and I want them back. I need you to take my ticket, go to the club, and get my sunglasses back.}
{168}{}{I'll think about it.}
{169}{}{About that favor... }
{170}{}{Yeah?}
{171}{}{Why are you asking me and not your boss?}
{172}{}{Oh, okay, I'll manage, somehow.}
{173}{}{[He winces] Oooh... That's kind of a sensitive matter. Stryker wants the club and is trying to negotiate with Mom, so he's not happy with my, uh, whatever I did. I'd prefer not to remind him. You see what I'm getting at?}
{174}{}{Yeah, I see. Well, back to work.}
{175}{}{I've got your sunglasses.}
{176}{}{Fuckin' A! [he puts on the glasses and looks around] A deal's a deal. I'll get in touch with Solomon and let him know you're trustworthy. He works in a building out behind the El Dorado, next to the Cotton Club. Tell him I sent you.}
{177}{}{Great.}

#Бункер
{180}{}{What's that bunker entrance across the street, in the park?}
{181}{}{Some pre-war bomb shelter. A few hundred people could probably live there for a few days at a time, but there's not much need for it now.}
{182}{}{Why's it locked?}
{183}{}{I don't know. Stryker's idea. He probably thinks he can find someone that can crack the door code.}
{184}{}{Door code?}
{185}{}{Yeah, there's some door hooked up to a terminal that we just can't crack. Thing's like a fucking vault. It's probably the command center for the shelter - you know what that means?}
{186}{}{What?}
{187}{}{It means it'd have a radio station, a power source, surveillance systems, medical supplies, all that stuff. Those pre-war folks didn't fuck around when it came to their shelters. But we'll never know for sure until Stryker finds someone that can either crack the terminal or blow the door down.}
{188}{}{It looks like you scavenged some things from there already.}
{189}{}{Yeah, Stryker pulled out all the surveillance systems we could get to and wired them up around the headquarters. They work great, though the guys get tired of staring at monitors all day. Honestly, we don't really need them, but sometimes Stryker keeps a record of his meetings in case he needs dirt on someone. But, uh, don't tell anyone I said that.}
{190}{}{How can I get the key to the bunker?}
{191}{}{Talk to Stryker. He'll probably give it to you for a few bucks. After all, if we can't get into the command center, it's not like you're going to be able to.}
{192}{}{Okay.}

#Female character
{1130}{}{Would you just fuck off? [he rubs his temples] I'm not in the mood to answer any questions. I can't even think right now.}
{1133}{}{Racer, huh? Well, nice to meet you.}
{1175}{}{I've got your sunglasses.}
