{100}{}{You see a citizen.}
{101}{}{You see an ordinary resident of the slums.}

{102}{}{Whatever you want, I'm not in the mood.}
{103}{}{Fine, maybe I'll come back later.}
{104}{}{I'll make this quick.}

{105}{}{My husband does the talking in this house.}

#Про Хардинга
{110}{}{Someone is badmouthing Harding. I want to know who and why.}
{111}{}{[He raises his eyebrows in surprise] You're seriously here on *his* behalf? Alright, here's what I've got to say: }
{112}{}{FUCK that sack of shit! And FUCK you, too! }
{113}{}{Harding doesn't deserve to have someone like you looking out for him. }
{114}{}{Harding's a weak little bitch and he deserves everything he gets. Maybe if he wasn't so pathetic, he'd get more respect. But instead of fighting for respect like a man, he'd rather mope and whine and whatever he does at that secret club he goes to every Friday. Guys like him just won't ever improve themselves. }
{115}{}{Now get out of my house, you simpering, bleeding-heart pussy!}
{116}{}{Now, with all due respect, please leave my house.}
{117}{}{What secret club?}
{118}{}{Some weird out-of-towner is gathering up all the local rejects and holding weekly meetings. He says he just wants to help them out of the goodness of his heart, which is always a good sign someone's up to no good.}
{119}{}{I should discuss this with Harding.}

#Потерянная посылка Патрика
{120}{}{Hey, did you know your son lost Patrick's mail?}
{121}{}{Oh, so that holier-than-thou shitbird didn't get his mama's cookies? Cry me a fucking river. Not so high and mighty anymore, is he?}
{122}{}{Don't be rude. I'm leaving.}
{123}{}{Watch your mouth! Do you know who I work for?}
{124}{}{All I need is a letter. I'll pay money for it.}
{125}{}{You're playing with fire, you know. Patrick can only be so patient.}

{126}{}{[He pales] Uhh - I'm sorry! I'm sorry! I just got a little carried away. Look, there's no package here. We never saw a package. All we have is this letter, see? Here, you take it! I'm cooperating, see?}
{127}{}{Don't let this happen again. Remember, in this city there's two types of people - those with guns, and those that work for them. Now get out of my way.}
{128}{}{Money? I like money. How much money are we talking?}
{129}{}{I'll give you 100 dollars for the letter.}
{130}{}{Heh! Easiest hundred bucks I ever made! Here's the letter. Don't bother looking for the rest of the package, it's long gone.}
{131}{}{I'm not surprised. Give me the letter.}
{132}{}{Ha-ha-ha! Shut the fuck up. I've heard him talk - "oh, please, thank you, God bless you!" Spineless little prick. He'll never survive here.}
{133}{}{He's lasted this long. Even though he has no weapons, even though he's from out of town, even though he's interfering with the local politics, he's still alive. In fact, he doesn't look like he's even broken a sweat. And someone's sending him packages from out of town. What does that tell you?}
{134}{}{It - uh - [he suddenly looks very agitated] That package... Someone's spending a *lot* of money on him... Uh, hey, listen. The package is gone. I have this letter, though. Why don't you give it to him? Tell him, uh, I'm sorry for the delay. Really, really sorry.}
{135}{}{I'll give him this letter and you're apology. Watch yourself from now on - you won't be the only one.}
{136}{}{Forget it, I'm leaving.}

#Подробное описание
{150}{}{You see a ragged man. He clearly misses someone.}
{151}{}{You see a ragged man. His eyes are dull with booze.}
{152}{}{You see a ragged man. He looks like he's suffering a crushing hangover.}
{153}{}{You see a ragged man. He's obviously drunk.}
{154}{}{You see a ragged man. He gives you an annoyed look, then loses interest.}
{155}{}{You see a ragged man. He looks pissed off about something, or maybe everything.}

{160}{}{You see a ragged woman. She clearly misses someone.}
{161}{}{You see a ragged woman. You'd say she looks lost in thought, but on second thought, you think she's just lost.}
{162}{}{You see a ragged woman. She's looking at something a thousand miles away.}
{163}{}{You see a ragged woman. She looks a little drunk.}
{164}{}{You see a ragged woman. She gives you an annoyed look, then loses interest.}
{165}{}{You see a ragged woman. She gives a disdainful snort when she makes eye contact.}

# Разговор
{200}{}{Do you know what they do to people who bust into people's homes to ask questions around here?}
{201}{}{I'm looking for 75 Virginia Street. Is this it?}

{202}{}{Yeah, this is it. So what?}
{203}{}{Have you ever seen the girl in this picture? This address is written on the back.}

{204}{}{I don't know and I don't want to know! Get out of my house and quit wasting my time!}
{205}{}{I think hunger is making you cranky. How about 100 dollars for a warm meal?}
{206}{}{Well, that's a bust. I'm leaving.}

{207}{}{What?!}
{208}{}{How about $200?}
{209}{}{Well, that's a bust. I'm leaving.}

{210}{}{Hey hey hey! Wait a minute! I'm, uh, starting to remember already... }
{211}{}{[Give him the money.]}
{212}{}{[Leave.]}

{213}{}{No, wait! Give me 100 bucks and I'll tell you everything. Everything I know!}
{214}{}{Okay, here's 100 dollars. What do you know about this girl?}
{215}{}{No, I don't believe you. Better luck next time.}

{216}{}{Okay, I don't know anything about this girl. But there was a creepy guy living in this house before us. I got a look at his things when he was moving out. There was an album full of pictures of girls, and every one of them had holes burnt in their eyes!}
{217}{}{What was his name?}
{218}{}{All I got was Ted. I don't know his last name.}
{219}{}{Where did he go?}
{220}{}{I don't know exactly, but he said he was going somewhere quieter than here, so he's probably not in the city center. I also remember he carried his things south of here.}
{221}{}{Did he leave anything behind?}
{222}{}{Nah, just some old newspapers. We burned them long ago.}
{223}{}{Okay. So Ted moved to someplace quiet in the south. What could that mean... ?}
{224}{}{By the way, why do you ask? Who is this guy?}
{225}{}{He's a homicidal maniac who cuts up dancers from the local club and cuts their eyes out before killing them. You and your family are lucky to be alive.}

{226}{}{[His eyes go wide] He... That's... Oh, shit. Really?}
{227}{}{I'll leave you to think about that. Bye now.}

{228}{}{You uncovered some of the mystery behind Ted Bundy's photo.}

#Female character
{1112}{}{FUCK that sack of shit! And FUCK you, too! }