{100}{}{You see a wounded militiaman.}
{101}{}{You see one of Thompson's men with a bandaged shoulder.}
{102}{}{You have completed part of Luciano's task.}
{103}{}{You shouldn't have come here!}
{104}{}{This room is occupied!}

{109}{}{What is that about?}
{110}{}{[You see the young revolutionary; so young, that his armor is almost falling of his narrow shoulders.] I don't remember hearing about someone else booking a bed here. Who are you?}
{111}{}{Thompson sent me. You have to tell me, what happened to your group, in detail.}
{112}{}{[Ignore him.]}

{113}{}{The boss takes care of us. It's great, right? But I've already told everything... Maybe the rest don't have the brains for this. I'll tell you everything.}
{114}{}{Go ahead.}
{115}{}{The boss ordered us to hold a demonstration near a night club to get the word out to the public. It's the busiest street in the city. Just as he ordered, we assembled a group at the crossroads. But around the time a crowd started to gather, I was hit by a bullet. The shot was silent, and I couldn't tell where it came from. The crowd fled immediately while our guys hunkered down. Strange, I know, but it's the truth. Ask people around on the street, they'll confirm it.}
{116}{}{Can you tell what weapon you were shot with?}
{117}{}{I'm afraid not. The bullet went through. But, if it helps, I was standing near the street lamp at the crossroads, next to the home of Mr. Wright.}
{118}{}{That's enough for now.}

{119}{}{Sorry, but, uh, how old are you?}
{120}{}{Fifteen, why?}
{121}{}{Aren't you a little young for politics and revolution?}
{122}{}{I'm just the right age, damn it! Look at how wise the "adults" in this city are, before you tell me I'm "too young". Fuck them, I trust Thompson as I would my own father - he knows where to go and what to do.}

#Медицинская помощь
{123}{}{I see you had a hard time. Still hurts?}
{124}{}{[Gently adjusts his bandages] Yes, it hurts like hell sometimes! It's better now, but I don't know for how long. If the pain doesn't subside soon, I'll have to go get another dose from the drug dealers. And I don't like it much.}
{125}{}{Have a stimpak, it will help.}
{126}{}{Have some painkillers. They're just what you need.}
{127}{}{I managed to fix the autodoc. You can use it.}
{128}{}{I'll find you some meds, don't worry.}
{129}{}{Then I won't bother you any longer.}
{130}{}{That would be great. I've just about to reach my limit here. Thompson promised to help with meds, but I still haven't received anything.}
{131}{}{Why not use the autodoc?}
{132}{}{I asked, but Thompson said it doesn't work. Everyone in the city used it after the old City Hall was disbanded, I was told. So, no wonder it went broke. And there's no one to repair it now.}
{133}{}{Right, let's talk about something else.}
{134}{}{I'll go then. Business, you know.}
{135}{}{What is that about?}
{136}{}{Oh!.. o-oh... So nice! The pain is gone... Thanks! I had lost all hopes that someone would help. But you're better than those idiots. Now I can tell that dealer where to shove it, ha-ha!}
{137}{}{You're welcome. But I still want to talk to you about something else.}
{138}{}{Enjoy it! I've got other things to do.}
