{100}{}{You see a gunsmith.}
{101}{}{You see Mr. Thompson's personal gunsmith.}
{102}{}{You have completed part of Mr. Luciano's assignment.}
{103}{}{You should know better than to be here!}

{110}{}{[He scratches at his neck as he looks at you] Who the hell are you?}
{111}{}{Mr. Thompson's newest recruit. He told me to introduce myself to everyone.}
{112}{}{None of your business.}

{113}{}{Did he? [he sounds skeptical] Alright... Recruit.}
{114}{}{You have a lot of empty cartridges on that table. Why?}

{115}{}{I repack them with fresh bullets and propellant. Boring as shit, but I don't want anyone else doing it. Pack it wrong and someone's likely to get their fingers blown off.}
{116}{}{Why don't just use new ammo?}
{117}{}{How much does Thompson pay you for this?}
{118}{}{Can you make ammunition for me?}
{119}{}{I should let you get back to it. Bye.}
{120}{}{Hey. Still making ammo here. Still gonna be making it for a long, long time.}

{121}{}{Oh yeah, just get some fresh ammo off the ammo tree! Why didn't I think of that? [he rolls his eyes] Reno's police went through all of its ammunition in the first years after the war. Anything we've found since then has been fired off over the last ten years of civil war. It's hard enough getting a working gun anymore, let alone ammo. We buy what we can from prospectors and caravans, but we still have to make every bullet count.}
{122}{}{You think this is about money?! [he gives you a sharp look] I don't know if you noticed, but shit's fucked up in this city! We're here because we're the only ones trying to fix it! Back when Reno's old mayor was around, things were different. People were safe and things *worked*. We're gonna bring that back. That's worth a lot more than *money*.}
{123}{}{Sure! Can't fight the good fight without bullets. Bring me the right components, and I'll press some new ammo for you here and now.}
{124}{}{[He peers at you suspiciously] Thompson didn't say you'd be coming by, so I don't have anything for you. These components aren't easy to come by. If you want me to make ammo for you, you'll need to bring the supplies yourself.}
{125}{}{I have powder, casings, and metal. What can you make with these?}
{126}{}{I can pack 24 rounds of 10mm, or 20 rounds of .30 at a time.}
{127}{}{ I think you've got enough here for that.}
{128}{}{ But I don't think you've got enough components for that.}
{129}{}{ I'll just need 100 bucks for operating expenses.}

{130}{}{What caliber you want?}
{134}{}{Done!}
{135}{}{I need more ammo.}
{136}{}{Thank you, that's enough.}
{137}{}{I'll be back when I need more.}

{140}{}{[Caliber 10 mm: 24 Rounds remains]}
{141}{}{[Caliber .30: 20 Rounds remains]}
{142}{}{}
{143}{}{[Caliber 9mm: 20 Rounds remains]}
{144}{}{[Caliber 0.45: 20 Rounds remains ]}

{145}{}{[Caliber 10 mm: $100 and 24 Rounds remains]}
{146}{}{[Caliber .30: $100 and 20 Rounds remains]}
{147}{}{}
{148}{}{[Caliber 9 mm: $100 and 20 Rounds remains]}
{149}{}{[Caliber 0.45: $100 and 20 Rounds remains]}

#Расширение
{150}{}{Why only those calibers?}
{151}{}{That's all I have the equipment for. Those are the most common calibers we have around here, so that's what we developed our tools for.}
{152}{}{What about 9mm or .45? They're pretty similar to what you're making now.}
{153}{}{Let's back up a bit...}

{154}{}{You seriously can't make anything but that? Just what kind of munitions expert are you?}
{155}{}{Look, I'm not here to explain this to you, alright? Just trust me, that's all we're equipped to make here. Take 'em or leave 'em.}
{156}{}{[He scratched his chin] Eh...I'll have to jury-rig the tools a bit, but I can manage that. Okay, I can whip up some 9mm and .45 for you.}
{157}{}{That wasn't necessary. Give me a moment and I'll explain how to make 9mm and .45 rounds.}
{158}{}{Too bad. I have another question.}

{159}{}{[He listens attentively] Hmm. Well, that's good and all, but I don't have time to run around the city looking for the necessary parts.}
{160}{}{Fine. I'll bring you the supplies and you can pick and choose what you need.}
{161}{}{Alright, deal.}
{162}{}{In fact, I have some supplies right here. Take a look.}
{163}{}{I'll be back soon.}
{164}{}{I've got some scrap metal for you. Come on, take a look.}
{165}{}{[He digs through the scrap, picks some bits out and nods] Hey, you were right! This was a good idea! Maybe when this is all over, I can expand to even more calibers. Look, I owe you. Next time you come by, I'll make your ammo for free.}
{166}{}{Thanks. I'll keep that in mind.}
{167}{}{This gunsmith can now create a wider variety of ammunition, including 9mm and 0.45 rounds.}

#Оружие Томпсона (эта часть диалога вырезана из 1.0., так как удалено оружие Томпсона)
{180}{}{I noticed Thompson's carrying an unusual weapon. Do you know anything about it?}
{181}{}{Oh, that. Yeah, energy weapons aren't common around here. I can tell you a bit about it, if you're interested.}
{182}{}{Where did he get it?}
{183}{}{What does it shoot?}
{184}{}{How effective is it?}
{185}{}{Is this pre-war tech?}
{186}{}{Tell me again about Thompson's gun.}
{187}{}{He got it about three years ago, when he found out his old gunsmith - the one before me - was dealing on both sides of the table. He ordered the guys to teach him a lesson, but the fucker was tough - he made his last stand in his house and they had to ventilate him. Only the gun remained.}
{188}{}{Plasma bolt. It's complicated. Just know that it melts through flesh and bone like... Uh, well, nothing else comes close, really.}
{189}{}{Very. It hits like a high-caliber round and it'll go through anything you'll find around here, though some pre-war armor was built to stop it. I've heard it's not the best when it comes to energy weapons, though, but it's not like I'd know for myself.}
{190}{}{Yes and no. The gunsmith grafted parts from a plasma pistol to the frame of a Tommy gun. I think he hoped to add more parts to increase the power supply, or at least make it more accurate. But as it is, it works pretty much like any other Glock-86.}
{191}{}{Glock?}
{192}{}{Yeah, that's the company that made the plasma pistol. Designed by a computer that thinks like a man, or maybe a man that put his brain in a computer, or something. I don't know, I wasn't there.}
{193}{}{That's enough about guns for now. Let's chat about it later.}

#Female character
{1110}{}{[He scratches at his neck as he looks at you] Who the hell are you?}
{1111}{}{Mr. Thompson's newest recruit. He told me to introduce myself to everyone.}
