{100}{}{You see a militiaman.}
{101}{}{You see one of Thompson's supporters.}
{102}{}{You have completed a part of Luciano's task.}

{103}{}{Want to join? Mr. Thompson might be interested in you.}
{104}{}{We keep this place safe.}
{105}{}{Don't make trouble if you want to leave this place alive.}

{110}{}{Are you taking pictures? [he reaches for his gun] I'll show you what we do to spies!}
{111}{}{No, I'm not a spy! Here, take the camera. That'll prove it.}
{112}{}{Bad move. Now I'm going to be a spy and a murderer.}

#Женские реплики
{1105}{}{Don't make trouble if you want to leave this place alive.}
{1110}{}{Are you taking pictures? [he reaches for his gun] I'll show you what we do to spies!}