{100}{}{You see Canary.}
{101}{}{You see a completely ordinary bum... Or so he appears.}
{102}{}{Er, hello.}

{109}{}{Oh, and what could a poor old hobo like myself do for you, sir?}
{110}{}{Oh, gracious sir, could you spare just a bit to help a poor old hobo down on his luck?}
{111}{}{Who are you?}
{112}{}{Of course, here's 10 bucks for food.}
{113}{}{I have a question.}
{114}{}{Not today.}
{115}{}{I only have one thing to say: "The gilding is gone from our century."}
{116}{}{The name's Canary, sir. Just a small, wandering hobo in a large world.}
{117}{}{Hello, Canary. And goodbye.}
{118}{}{It came down into our pockets, amigo.}
{119}{}{Is that all you have to say?}
{120}{}{I'm just a simple hobo. What more could you want from me? I've already said more than my mind can handle.}
{121}{}{If you say so...}
{122}{}{Err... [as you turn to leave, he taps his pocket and looks at you expectantly]}
{123}{}{Sure, here's 10 bucks, philosopher.}
{124}{}{Sorry, I'm all out.}
{125}{}{Piss off, you're not getting anything from me!}
{126}{}{[He scowls and angrily adjusts his rags] Get away from my fire! This is my spot!}
{127}{}{Fine, here's 10 bucks.}
{128}{}{Ha! There's no arguing with that, is there?}
{129}{}{Thank you, sir!}
{130}{}{You're welcome.}
{131}{}{Now, can you answer a few questions?}
{132}{}{I would, I would, but ohh... The hunger, it makes it hard to think...}
{133}{}{Here's 10 bucks to sate those hunger pangs.}
{134}{}{Wait up, I'll be back.}

{135}{}{Of course, sir, happy to help.}
{136}{}{What do you know about this place?}
{137}{}{What's behind that fence?}
{138}{}{Have you ever seen the owner of this ranch?}
{139}{}{How did you end up like this?}
{140}{}{I've heard enough.}

{141}{}{[He draws a big circle with his hands] A ranch! It's enormous! They make food here - the most important thing in this world.}
{142}{}{This is the home of a great man. He owns this ranch and lives here with his family, guards, slaves, and brahmin. Oh, he guards it carefully... Step inside, and they'll shoot you on sight, unless you're one of their own!}
{143}{}{Ohh, there's not many like him in Reno. A tough nut, for sure - but do you know how nuts spoil? Not from the outside, no, but from within!}
{144}{}{Me? Oh, wanderer, what could interest you in an old hobo like me? I was born from dust, I live by dust, and one day soon I will return to dust. They'll forget me then, but not yet - sometimes the guards come by and ask me to bring something into or out of the city. Easier than sending a slave or a guard, yes?}
{145}{}{I see. Let me ask you something else.}
{146}{}{No more questions for now.}

#Женские реплики
{1109}{}{Oh, and what could a poor old hobo like myself do for you, madam?}
{1110}{}{Oh, heavenly madam, could you spare just a bit to help a poor old hobo down on his luck?}
{1118}{}{It came down into our pockets, amiga.}
{1121}{}{If you say so...}
{1129}{}{Thank you, madam!}
{1135}{}{Of course, madam, happy to help.}