{100}{}{You see Thompson.}
{101}{}{You see a formidable man. He oozes with authority.}
{102}{}{He looks disheveled and depressed.}
{103}{}{I'll give you one minute.}

#Îòêàç â ñîòðóäíè÷åñòâå:
{110}{}{You have the nerve to show your face here? I had high hopes in you. We could have done so much together. We could have turned this town around! But no, you're a political prostitute like all others! I don't need you. Get out!}
{111}{}{I'll just go, before I spoil your good mood.}
{112}{}{I won't leave until I kill you!}

#Ïåðâûé ðàçãîâîð:
{115}{}{[He looks you up and down carefully] You obviously didn't wander in here by accident. What are you doing in my headquarters?}
{116}{}{*Your* headquarters? And who declared you mayor?}
{117}{}{You've got a lot of armed men around here. I want to know more about you.}
{118}{}{I've seen your posters. I'm interested. Can you tell me about your movement?}

{119}{}{Look around. I'm the people's choice. They'd vote for me, if they had the opportunity.}
{120}{}{It would be my pleasure to tell you, but I don't have much time. The idea is simple: we re-establish the City Hall and bring back the mayor's position, just like it was right after the Great War. Why, you ask? Because the problems of this city began when we lost the rule of law. Without a central authority, power shifted to the city's business moguls, who tried to take complete control for themselves. This is what turned neighbor against neighbor and kicked off the civil war. I want to bring things back to the way they were 40 years ago - and the majority of Reno's citizens agree with me.}
{121}{}{We're very busy here. If you don't have business to discuss, don't distract people from their work.}
{122}{}{I'd like to know more about your movement.}
{123}{}{Understood.}
{124}{}{I won't take up any more of your time.}

#Íàïðîñèòüñÿ íà ñëóæáó:
{130}{}{[A man leans over and whispers in his ear. After a minute, he turns to you, his eyes are narrowed] We have nothing to discuss.}
{131}{}{Alright, then I'll just go.}
{132}{}{Let's make one thing clear: every single man here is devoted to the cause. I have no place for mercenaries or "political prostitutes". If you want to be one of us, you have to convince me you're trustworthy and committed.}
{133}{}{I have nothing to prove. I work for whatever person I think is right. Either you trust me, or I walk.}
{134}{}{Ask anyone at Mr. Bertolini's casino. My reputation speaks for itself.}
{135}{}{I have connections with Big Louie. Think about it. You want him as your friend. You *don't* want him as your enemy.}
{136}{}{Give me a chance! I'm sick of playing the small game - I want to move on to the big leagues!}
{137}{}{}
{138}{}{I'm listening.}
{139}{}{I guess I can't prove that.}

{140}{}{Heh. If we were tribals in the desert, I'd have pulled your guts out for that kind of talk. But here in Reno, I need people with your... Gumption. Anyway, first I want to test you.}
{141}{}{Yes, I've heard of you. I think we can do business together. But first - I want to test you.}
{142}{}{The Big One and I don't have the... Relationships... We used to. But the last thing I want is his interference, especially with that new hardware he's toting. Fine, but first - I want to test you.}
{143}{}{About the job... }
{144}{}{Is it done?}
{145}{}{I'm on it, boss.}

{146}{}{[Raises his voice] Then what the hell are you doing here?! Don't waste my time! The next time I see you, that job is better be done!}
{147}{}{[Leave]}
{148}{}{Hmm. You speak with confidence and I know you have... Skills... That could be useful to me. But first, I want to see if you're suitable.}

#Ïåðâûé êâåñò:
{150}{}{A couple of lowlifes dared to abuse my girls near the casino. I was going to send Billy, but I want to see you in action. Deal with them and report back with the results.}
{151}{}{What's the pay?}
{152}{}{Alright, I'll do it.}
{153}{}{I'll check it out.}
{154}{}{I want to save Reno from itself, and all you care about is money?! Maybe - maybe! - Paige can help you with money, if you're polite. Now, enough chatter. Next time I see you, I want results.}
{155}{}{I gave those thugs what they deserved. Now they know who's the boss around here.}
{156}{}{Bad news, boss - Betty Paige is dead.}
{157}{}{[Slams his fists on the table] DAMMIT! This wouldn't have happened if my boys had kept an eye on things! I'm gonna have to lay down the law on my enforcers.}
{158}{}{That's good. I hope you were on your best behavior with Paige. Even to her, we can't show any weakness.}
{159}{}{[Next]}

#Äèàëîã áóäó÷è ïðèáëèæåííûì Á.Ëóè:
{160}{}{Even in that suit, you still look like a raider.}
{161}{}{Maybe to an out-of-towner like you, but around here I fit right in. The people trust me.}
{162}{}{But you lie to them.}
{163}{}{Of course I lie to them! Power doesn't come from weapons or badges. It comes from lies. The more you lie, the more powerful you get - and I'm very good at lying. No one wants the truth! They'd rather pretend they're something they're not. I tell them what they want to hear, and I bend that just enough to get what I want. That's the real power.}
{164}{}{Hmm, what an interesting opinion.}
{165}{}{Do you know anything about the attack on the courier from Las Vegas?}
{166}{}{The Big One is still trying to play me. He knows I have to be involved in that, because of my relationship with Ricardo Bertolini. It's just one more move in the game we're playing.}
{167}{}{Let's talk like one raider to another.}
{168}{}{What?! Oh, that's right. Sometimes I forget who I'm talking to. You don't look like a raider, you know. But the Big One has a good eye for people.}
{169}{}{Then let's not delve into the past.}
{170}{}{How did you and Stryker end up like this?}
{171}{}{I'll give you the short version. Five years ago the Big One took over Reno. After ruling it for a year, he went back to the wasteland and left me and Stryker in charge. But then Stryker got started on his own idiotic politics, so we split up. Reno's business owners took advantage of the conflict and tried to get rid of us. Now we're on the edge - either one of us wins, or Reno pushes us out completely.}
{172}{}{That explains things.}

{180}{}{What is this place?}
{181}{}{This building was Reno's old town hall, and down here was the bomb shelter for its employees. It's been a long time since there was any authority around. Once they threw out the mayor, the business owners tried to set up shop here, but it didn't last long.}
{182}{}{What happened?}
{183}{}{Civil war. First it was the businessmen fighting over the town, then it was just riots. That was until the Big One came in and put his own people, like me, in charge.}
{184}{}{Why did Big Louie leave town?}
{185}{}{He's not as "big" as everyone thinks, alright? I think you've already got an idea what happened.}
{186}{}{[Next]}
{187}{}{I'm not going to discuss it with you. It's a personal matter, just between us. You don't want to get involved.}
{188}{}{Alright.}
{189}{}{He had money, power, the whole town in the palm of his hand, so why'd he leave? I know why. He didn't want any of those things. He was chasing a dream... Or a memory. He grew up in Reno during its "Golden Age", when people had what they needed and weren't fighting with each other. I guess he thought he could bring that back. But it was a load of crap. Reno couldn't be like that anymore - hell, maybe what he remembered never really existed. And when he realized that, he ran back to the wasteland. He'd rather live in isolation than with the result of everything he worked for.}
{190}{}{And what about you? What are you working for?}
{191}{}{That's very interesting. I need some time to think about that.}
{192}{}{Heh. I want to be in charge. Don't look at me like that - this isn't just another racket. I know a little about Reno's history.}
{193}{}{What part of Reno's history?}
{194}{}{Just after the Great War. Look around! Do you know what this city is? It's a monument to an old idea. Back then, Reno was ruled by a dictator called the mayor. His retinue crawled at his feet and begged for his mercy, his objectors were dealt with by the firing squad, and all the useless dreamers were sent to the slave cells. That history still lives in this city. We can still bring back the old days!}
{195}{}{Is that the only way to bring back the old days? They had other ways of living, before the war.}
{196}{}{Not an option. It's been three generations since the Great War. It's hard to find anyone who remembers the world before. People live... Differently now. They've fallen too low. Most people would rather submit to the strong, and the few strong people in this town have gone to civil war. That's human nature now. We're not *ready* to go back to those ways. Until we are, we need a strong leader. We need a mayor. We need *me*.}
{197}{}{That's a lot of food for thought. I need to reflect on it.}

#Âòîðîå çàäàíèå:
{200}{}{We need to get to the bottom of this. Those lowlifes would have to be pretty stupid to attack my girls. There might be another force pulling the strings. Something's happened to some of my men - I think it might be connected.}
{201}{}{What happened?}
{202}{}{Some of our soldiers got under fire on the street. I want you to investigate it. The survivor's down the hall, start with him. You'll be paid when the investigation's complete.}
{203}{}{I'll handle it, Mr. Thompson.}
{204}{}{I've figured out the details of the attack on your people.}
{205}{}{Tell me everything.}
{206}{}{According to the evidence I found, the shooter used a sniper rifle with a silencer from the balcony of an non-residential building across from the casino entrance. The sniper was working alone and must have been disguised as an ordinary citizen, otherwise he would have been spotted leaving the building.}
{207}{}{[He nods] Before the Great War, they called these "false flag" operations. Now it's clear: there's a third party in the city trying to push Stryker and me into open warfare. Whoever they are, they're clever, and almost certainly not from around here. I'd know about sniper rifles in these parts.}
{208}{}{Makes sense. These might be mercenaries from another town.}
{209}{}{Many of the local business moguls are afraid of us. If they hired mercenaries for sabotage, I'll have to put up my surveillance all over the town. The only problem is the caravan parking lot... But before we get into that, we need to deal with your payment. [He places a wad of money on the table, then slides it towards you.] For your cooperation, and in expectation of more in the future.}
{210}{}{What was that about the parking lot?}
{211}{}{Most of the town has been claimed by either Stryker or me. The only neutral land left is the caravan parking lot... The main entrance into town. The second floor of the local hotel would be perfect for surveillance. Your job is to persuade the hotel owner, Mr. Mordino, to cooperate.}
{212}{}{How... Delicately should I behave during this job?}
{213}{}{That's up to you. My control over this territory comes first. Use any method necessary. But before you make a decision, assess your options - blackmail, business proposal... Many things can persuade a willful man.}
{214}{}{I understand, Mr. Thompson. I'll do this as clean as possible.}
{215}{}{Hm, that won't be easy. I'll see what I can do.}

{220}{}{Mordino is dead. Now you can put your man in charge of the hotel.}
{221}{}{Hmm. That's not the solution I wanted. It'll be difficult to find someone capable of managing the hotel. But that's a concern for another day - now I can take over that territory and establish order.}
{222}{}{[Next]}
{223}{}{Good job. Mordino doesn't like to risk, so I'm sure he'll be easy to deal with, while his family is in our pocket. Now, go finish the job.}
{224}{}{I'll do it.}
{225}{}{The job's done. Here's your payment: one thousand dollars, your cut of the hotel's income.}
{226}{}{Thank you, Mr. Thompson.}
{227}{}{I was able to reach an agreement with Mordino. He's willing to negotiate.}

{228}{}{Good work. I'll meet with Mordino personally, but first I'll have my men check all the rooms and hotel staff. I'll need your service.}
{229}{}{I feel as if this could have been handled another way... }
{230}{}{Justice always requires sacrifice. In our times especially. Hmm... A year ago I wouldn't have said that. Reno changes people. It changed you too, didn't it?}
{231}{}{Maybe... }
{232}{}{Of course, but we haven't dealt with our current task yet.}
{233}{}{I'll handle it myself. This new territory will give me an advantage, but we must drive out all traces of Stryker's influence - that means all the snitches and dealers working for him.}
{234}{}{What do I need to do?}
{235}{}{The others will handle the details. For you, I have important work. I've heard Stryker has a big deal set up, but I don't know the details. Talk to our new scout - he used to patrol the southern wall of Stryker's headquarters. But be careful - he may be a double agent. Give him the code phrase "You're as small as a bug," and do whatever you need to do from there on. Whatever Stryker has planned, you have to stop it.}
{236}{}{I'll do it.}

{237}{}{Stryker's deal has been dealt with.}
{238}{}{That's another step forward for us and another step backward for him. His men are already abandoning him, which is good for us and for Reno. [he hands you a stack of bills] You've earned this.}
{239}{}{What's next?}
{240}{}{Only one thing remains: the final attack on his headquarters. You don't need to get involved in the fight, my strike team will handle it. Your job is to penetrate their headquarters and disable their monitoring system. This will make them vulnerable and prevent them from calling for backup. Once their defenses are down, meet the head of the strike group in the city park in front of Stryker's headquarters. All clear? I'm not going to repeat it. Get to work!}
{241}{}{Will do.}
{242}{}{Stryker is dead. It's time to celebrate your victory!}
{243}{}{[Breathes loudly] This day will go down in the history of New Reno! In this honor, let's open a bottle of good old whiskey. Drink with me! You're the man I can trust.}
{244}{}{Thanks.}
{245}{}{From now on, you can openly call yourself my right hand. That's going to mean something in Reno. Everyone under my authority will be happy to work with you, or give you discounts for their services. Keep that in mind.}
{246}{}{Great!}
{247}{}{From here on, it's grunt stuff, not the sort of work I'd give to you. You can relax.}
{248}{}{And what will you do now?}
{249}{}{Right. Goodbye, Mr. Thompson!}
{250}{}{Diplomacy, economy, all the work of restoring Reno's old glory. We'll have to rebuild the town hall and recruit more men. Remnants of Stryker's gang will probably keep making trouble - sabotage, assassinations, or just joining the thugs on the street. There's a lot of work to do for me.}

#Îðóæåéíûé áîíóñ
{251}{}{I can help in the coming fight, but I need a better weapon.}
{252}{}{Alright. What do you want?}
{253}{}{[9mm machine gun and 40 rounds]}
{254}{}{[Photon pistol]}
{255}{}{[8 frag grenades and a combat knife]}
{256}{}{}
{257}{}{I don't have much hardware. I can't risk giving it out to someone who doesn't know how to use it. I have faith in my strike force, so they get the best equipment.}
{258}{}{Alright.}
{259}{}{I'm counting on your help. Take a stimpak, just in case.}
{260}{}{No problem.}

#Êðûøà äëÿ êîíöåðòà â Êîòòîí-êëóáå
{300}{}{I represent the Cotton Club. The owner would like to pay you to provide protection for an upcoming concert.}
{301}{}{Is that right? That bum can't even pay his fees on time, and now he's throwing a show? Hmm... This would be good to get everything he owes us. Fine, I'll put people on it, but I want half of his earnings for the show.}
{302}{}{I'll tell him.}
{303}{}{Mr. Thompson, we've known each other for a long time. Listen to me: these conditions will bankrupt him. You might get your money now, but if this puts him out of business, you'll never get anything from him again.}
{304}{}{You can set your own price, but think about it: do you want to put pressure a business that's already on the edge? Sure you can set your own price, but think about it - Does it make sense to oppress the almost already bankrupt?}
{305}{}{You make a good point. Fine, I'll take only a quarter of the earnings, but I'm keeping my eye on him.}
{306}{}{Thanks, Mr. Thompson.}

#Female character
{1110}{}{You have the nerve to show your face here? I had high hopes for you. We could have done so much together. We could have turned this town around! But no, you're a political prostitute, like all others! I don't need you. Get out!}
{1111}{}{I'll just go, before I spoil your good mood.}
{1117}{}{You've got a lot of armed men around here. I want to know more about you.}
{1118}{}{I've seen your posters. I'm interested. Can you tell me about your movement?}
{1144}{}{Is it done?}
{1158}{}{That's good. I hope you were on your best behavior with Paige. Even to her, we can't show any weakness.}
{1230}{}{Justice always requires sacrifice. In our times especially. Hmm... A year ago I wouldn't have said that. Reno changes people. It changed you too, didn't it?}
{1243}{}{[Breathes loudly] This day will go down in the history of New Reno! In this honor, let's open a bottle of good old whiskey. Drink with me! You're the one I can trust.}
