{100}{}{You see a traveler.}
{101}{}{You see an exhausted traveler.}

#Плавающие фразы при отказе разговаривать:
{105}{}{Please, I'm tired. Let me rest.}
{106}{}{I can still stand on my own feet!}
{107}{}{Not now. I just want to sleep.}

#Разговор о дороге между Уэндовером и Рино:
{110}{}{Sorry, but I'm too tired to talk. It was a long trip.}
{111}{}{Tough times on the road? I can relate.}
{112}{}{We'll talk later, then.}

{113}{}{Hmm? ...Oh, no, not like that. The travel was fine, but I had to hurry to get here before nightfall.}
{114}{}{I know what you mean. I'd never spend a night outside the city!}
{115}{}{Yes, the wasteland can be very dangerous at night.}
{116}{}{Ha! What, are you afraid of the dark?}

{117}{}{Mmm. Look, I'm too exhausted to care right now. Come back in the morning and maybe I'll get offended then, okay?}
{118}{}{Aww, poor baby. Go have your nap in your crib.}
{119}{}{Fine. Sorry to keep you up.}

{120}{}{I should be going.}
{121}{}{Where are you traveling from?}
{122}{}{Bye.}

{123}{}{I'm not so concerned with the wasteland as I am with the people in it, to be honest. It's usually easier to "negotiate" with a gecko, if you know what I mean.}
{124}{}{Are you serious?}
{125}{}{Oh, yes. People don't stay around for long where I come from, so they don't respect anyone - not neighbors, nor visitors.}
{126}{}{Where do you come from?}
{127}{}{Interesting. Well, see you around.}

{128}{}{Wendover... Oh, right, you've probably never heard of it. Uh, it's a seasonal hunting village near Salt Lake.}
{129}{}{What made you come here?}
{130}{}{Can you show me where it's located?}
{131}{}{That's all I wanted to know. Bye.}

{132}{}{Tell me again, where did you came from?}
{133}{}{Yeah, sure.}

{134}{}{Eh, I'm no good with maps. If you're ever in Salt Lake, ask a local. They'll probably be able to point it out for you.}
{135}{}{Is there anything I should know if I'm ever in Wendover?}
{136}{}{That's all, thanks.}
{137}{}{[He sighs] That's a long story. You don't need to worry about it, it's my problem.}
{138}{}{If you say so. See you around.}
{139}{}{It's mostly hunters and their families. Men hunt for geckos while women and children tend to their huts. It has everything you need - a tavern, a shop, a hunting guild - but other than that there's not much to it. Also... A lot of people only live there for the hunting season, so they think they can do whatever they want without being punished for it.}
{140}{}{No punishment? Sounds like my kind of town! Where is it?}
{141}{}{What are you planing to do in Reno?}
{142}{}{I don't know. It's easy to catch a bullet here, if you don't watch yourself. Or the people around you, come to think of it. I'll have to strive hard to survive here.}

#Female character
{1114}{}{I know what you mean. I'd never spend a night outside the city!}
{1116}{}{Ha! What, are you afraid of the dark?}
{1130}{}{Can you show me where it's located?}