{100}{}{You see an old autodoc.}
{101}{}{You see a worn out autodoc.}
{102}{}{You cannot do that in combat.}

#Первичный осмотр
{110}{}{[This autodoc is in a terrible condition, as if someone tried to treat an army of deathclaws with it. It had clearly been in use for a long time.]}
{111}{}{[Inspect the machine closely.]}
{112}{}{[The machine is still being supplied with power and medicine. If the damaged components were repaired, it could still be used for healing.]}
{113}{}{[Next]}
{114}{}{[The medicine supply is located deep inside the nearby wall and seems to be inaccessible, probably to discourage looting. According to the computer, however, the reserves are almost exhausted.]}
{115}{}{[Leave.]}
{116}{}{[This autodoc is awaiting commands.]}
{117}{}{[Look over the machine again.]}
{118}{}{[Finish your inspection.]}
{119}{}{}

#Починка и диагностика
{120}{}{Run check-up diagnostics of the surgical module.}
{121}{}{Run check-up diagnostics of the diagnostic module.}
{122}{}{Run check-up diagnostics of the sensor module.}
{123}{}{Run check-up diagnostics of the radiometric module.}
{124}{}{Conduct a system-wide scan.}

{130}{}{[Try to fix this module.]}
{131}{}{[Leave.]}
{132}{}{So, even if one tiny error occurs, the healing can cause injury. Should try to fix this...}

{140}{}{Starting diagnostics. Manipulators... Calibration required. Tools... No signal from instrument(s): B2, B7, B18. Sterilization system... Feed error. 3D scanner... Error code 402. Software... No errors found. Diagnosis complete: module is not functional.}
{141}{}{Starting diagnostics. Tools... No signal from instrument(s): A1, A3. 3D scanner... Error code 408. Software... Diagnostic programs offline; reinstallation required. Diagnosis complete: module is not functional.}
{142}{}{Starting diagnostics. Stereo-units... Calibration required. 3D scanner... Error code 411. Software... Unrecoverable crash on startup; reinstallation required. Diagnosis complete: module is not functional.}
{143}{}{Starting diagnostics. No response from module. Diagnostics complete: module is not functional.}
{144}{}{Starting diagnostics. Multiple recoverable faults detected throughout system. Recommend thorough repairs by licensed professional at first opportunity. Diagnosis: system is functional.}

{145}{}{Rebooting... Surgical module is functional.}
{146}{}{Rebooting... Diagnostic module is functional.}
{147}{}{Rebooting... Sensor module is functional.}
{148}{}{Rebooting... Radiometric module is functional.}
{149}{}{Rebooting... System is fully functional.}
{150}{}{Rebooting... System error.}
{151}{}{I must have made a mistake somewhere...}
{152}{}{[Leave.]}
{153}{}{[Continue.]}

#Лечение
{160}{}{Command: surgical diagnosis.}
{161}{}{Command: treatment of physical trauma.}
{162}{}{Command: treatment of foreign toxins.}
{163}{}{Command: treatment of radiation sickness.}
{164}{}{Command: treatment of foreign infections.}
{165}{}{Command: amputation of sixth finger.}
{166}{}{Run a general system diagnosis.}

{167}{}{Operation complete. Alert! Medicinal supply is low. There are only }
{168}{}{ doses of stimulant remaining.}
{169}{}{Attention! Autodoc has run out of medical supplies that are needed for the operation.}
{170}{}{ doses of antitoxin remaining.}
{171}{}{ doses of RadAway remaining.}
{172}{}{Operation complete.}
{173}{}{Operation complete. Finger has been amputated and wound treated.}
{174}{}{ doses of antimicrobial remaining.}

{175}{}{Diagnosis complete. Current level of health: }
{176}{}{/}
{177}{}{. Current level of poisoning: }
{178}{}{. Current level of infection: }
{179}{}{. Current level of radiation sickness: }
{180}{}{.}
{181}{}{The autodoc malfunctioned during treatment, inflicting a serious injury.}
