{100}{}{This is Chris Avellone.}
{101}{}{You see Chris Avellone himself!}
{102}{}{This is Feargus Urquhart.}
{103}{}{You see Feargus Urquhart himself!}

{110}{}{Chris, what the hell!? Who did this!?}
{111}{}{Mmm... What's wrong THIS time?}
{112}{}{What's wrong!? The thing is full of bugs - that's what's wrong! Beta testers are ripping their hair out!}
{113}{}{That's okay, boss, we'll fix that.}
{114}{}{Grr... Let's assume I believe you. And what about the car?! Why does it disappear all the time?!}
{115}{}{Err, the engine is a little rough...}
{116}{}{Ooh, the engine! Fix it then, you goddamn nerds!}
{117}{}{At least we have a car in the game. That's cool...}
{118}{}{Cool, yeah. Especially considering the fact that it doesn't actually drive!}
{119}{}{Well, the engine has its limits. The programmers insisted.}
{120}{}{Damn right they did! So much work, and half of our scripts is broken!}
{121}{}{Anything else?}
{122}{}{ELSE? Yes, I have a whole novel of your unfilled plot holes!}
{123}{}{Such as?}
{124}{}{For example, what's all this nonsense about Myron? When did he become a key figure in the Reno drug business?}
{125}{}{Well, he, uh, he's a genius...}
{126}{}{Uh-huh, yeah, yeah. That explains everything. Okay, that actually counts as an excuse.}
{127}{}{No, he is really a genius, I mean it.}
{128}{}{Also, there's, like, five more locations not completed!}
{129}{}{Mhm... Which is the fifth one, boss?}
{130}{}{Err... What are the first four?}
{131}{}{That's what I'm asking, which ones...}
{132}{}{Fine, forget it. Also, don't write something about EPA or Sulik's village, if they don't exist!}
{133}{}{Come on, boss, the players are gonna love it! They'll be encouraged to mod the game!}
{134}{}{Then throw the mapper at them, together with some tools. And what about the intro!? Nonsense!}
{135}{}{A boy coming out of vault? Yeah, we should remake that.}
{136}{}{Exactly!}
{137}{}{On the other hand, we have Armstrong, and also implemented sex.}
{138}{}{[Rolls his eyes] ...Implemented sex...}
{139}{}{Uh?...}
{140}{}{What? Oh, yes. Stop being lazy!}
{141}{}{Okay. Anyway, what do you think about the game in general?}
{142}{}{Well, you know, despite the bugs, I think that Fallout 2... Will live forever.}
{143}{}{Only until the era of 3D comes, and then...}
{144}{}{What an interesting thought! Develop it further.}
{145}{}{Develop?}
{146}{}{Well, put more dialogue somewhere. To the dwarf in the New Reno boxing ring, for example.}
{147}{}{Oh. Yeah, he conveniently has a dialogue branch with bullying...}
{148}{}{Great, get to work.}
{149}{}{Any more stupid instructions, boss?}
{150}{}{Let me have a look. A-ha, here! Here!}
{151}{}{What? What is it?}