{100}{}{You put the balaclava on your head.}
{101}{}{You take the balaclava off your head.}
{102}{}{You are not wearing the balaclava.}
{103}{}{Your balaclava is in your bag because it is incompatible with your other currently equipped items.}
{104}{}{You cannot put the balaclava on. It is incompatible with your other equipped items.}
{105}{}{Your balaclava won't be very effective at its job while you're wearing a Luciano ranch guard jacket.}
{106}{}{That mask won't fool me! I know who you are!}
{107}{}{You've caused a ruckus with one of the casino's Tommy guns. Luciano will be pleased.}
