{100}{}{You see the surveillance computers.}
{101}{}{You see the surveillance computers with access to the local database.}

{111}{}{[Look up any information about Mr. Mordino]}
{112}{}{[Finish]}
{113}{}{You find transcripts of a committee's decisions regarding Mr. Mordino and his hotel. They weren't in his favor.}
{114}{}{You can't figure out how to do that.}
{115}{}{[Search for information about the Stryker's deal]}
{116}{}{You find notes regarding a secret meeting of Stryker and representatives from Wind of War. Stryker intends to trade chems from his lab for weapons, armor and ammunition. The deal is scheduled at the Silver Legacy Hotel, in one of the rooms on the second floor. Stryker's men have already booked a room and tightened up security.}
{117}{}{This was informative...}
{118}{}{[Disable the tracking system and change the password]}
{119}{}{[Done]}
{120}{}{Now all that's left is to tell the assault team that they can begin the operation.}

{121}{}{[Copy the accounting ledgers]}
{122}{}{You copy the accounting details. These will be very useful for Luciano's administrator.}
{123}{}{[Back]}
