{100}{}{You open the fridge to see several hanging condoms. Inside of each one you see a human eye.}
{101}{}{[Close the terrible fridge.]}
{102}{}{The fridge is as ghastly as ever.}

{200}{}{[Steel yourself and look through the fridge]}

{201}{}{The eyes have been preserved with salt. Some still have the remains of eyelids and eyelashes, suggesting that they belonged to women. Some have lost all color with time, indicating that they have possibly been here for over a year.}
{202}{}{[Collect intact condoms.]}

{300}{}{[Open the freezer.]}
{301}{}{The freezer is full of severed fingers. They likely came from the same source as the hanging eyes.}
{302}{}{[Study the fingers.]}
{303}{}{Only a few of the fingers have rings from the Reno Club. Maybe not all of the victims were Mom's dancers.}

{400}{}{[Look at the fridge door.]}
{401}{}{The fridge door has some unopened bottles of beer and a spare small energy cell.}
{402}{}{The fridge door has nothing interesting.}
{403}{}{[Take the beer and the small energy cell.]}

{500}{}{[Search the lower shelf.]}
{501}{}{You find a spoiled can of meat and a dried-up omelette of indeterminate age. You don't need to try any of that.}

{600}{}{[Pull out the vegetable crisper.]}
{601}{}{You feel the weight of something inside. What could it be?}
{602}{}{[Open the crisper.]}
{603}{}{Nothing too bad, just a few more fingers and photos. The fingers are carefully wrapped in a clear bag. Most of them are missing nails.}
{604}{}{[Study the photos.]}
{605}{}{You see pictures of Mom's dancers. All of them have holes burned where their eyes should be... Except one. In one group photo, you see the girl from the picture you found on the maniac's body, with her eyes intact. She may still be alive!}
{606}{}{It's unlikely she could get away from Ted in this city... Nothing's left to search here.}
{607}{}{You found new evidence for the Ted Bundy case.}