{100}{}{Welcome to New Reno, the biggest little city in the world. Barrel fires and neon signs light the streets in a hellish glow.}
{101}{}{This area of Reno looks rough. You should watch yourself around here.}
{102}{}{That local vault is located somewhere around here.}
{103}{}{You're in Reno's business district. Here luxury sits side by side with poverty.}
{104}{}{You come upon a deserted railway station on the outskirts of Reno.}
{105}{}{You feel a sense of chaos in the air of this musty basement.}