{100}{}{A console.}
{101}{}{A computer console to open the sealed bunker doors.}

{102}{}{You don't need to use this console right now.}
{103}{}{That doesn't help.}
{104}{}{This console requires a VERY complex password.}
{105}{}{Verified. Depressurizing antechamber...}
{106}{}{Done}
{107}{}{Password is required}
{108}{}{This console requires a dizzyingly complex alphanumeric password. Maybe it's written down somewhere?}
{109}{}{So that's what this paper is for!}
