{100}{}{You see a hatch.}
{101}{}{Thick, heavy, armored hatch that can only be opened with a key card.}
{102}{}{You need a keycard.}
{103}{}{This door can only be unlocked with a keycard. It is most likely located somewhere in this bunker.}
{104}{}{Your skills are useless here. You need a keycard. No doubt it's somewhere around here.}
{105}{}{That's not going to work.}
{106}{}{That didn't even scratch it.}
{107}{}{This won't help.}
{108}{}{It's no use.}
{109}{}{It's open.}
{110}{}{You unlock the mechanism.}
{111}{}{You lock the mechanism.}
{112}{}{It's locked.}