{100}{}{This switchboard seems to control the power to the entire second floor of the casino.}

#Ремонт
{101}{}{The lid of the electrical panel is padlocked.}
{102}{}{There's a lot of current running through those wires. You probably shouldn't touch them with your bare hands.}
{103}{}{The second floor's lighting has been turned off.}
{104}{}{The second floor's lighting has been turned on.}
{105}{}{You can stand here all day, but this panel won't open itself.}

#Взлом
{110}{}{The lock has already been broken.}
{111}{}{The lock holding firm against you.}
{112}{}{You easily break the lock.}
{113}{}{This keyhole lock is locked.}
{114}{}{Locked with a key.}
{115}{}{The lock is open.}
{116}{}{You have unlocked the lock.}
