{0}{}{}
{100}{}{You see a vending machine.}
{101}{}{You see a pre-war vending machine.}
{102}{}{You have more pressing matters than reading advertisements right now!}
{103}{}{That won't do anything useful.}

{110}{}{This vending machine was cleaned out long ago. Only the product list and a few empty packages remain.}
{111}{}{[Read the advertisement on the side of the machine.]}
{112}{}{[Read the product list.]}
{113}{}{[Leave.]}
{114}{}{Pretty & Glamour is America's number one choice for hygiene and grooming. We provide everything you need to be confident, stylish and attractive! Buy Pretty & Glamour to be the best you can be!}

{115}{}{You're currently carrying }
{116}{}{ of Pretty & Glamour's seven products. You have }
{117}{}{[Gather everything into one box.]}
{118}{}{, }
{119}{}{.}

{120}{}{thorium toothpaste}
{121}{}{radium-enriched healing water}
{122}{}{radon bath salts}
{123}{}{"Atomic Blades" razors}
{124}{}{smart towel}
{125}{}{aromatic soap}
{126}{}{wet wipes}
{127}{}{}
{128}{}{}
{129}{}{}

{130}{}{You carefully collect all the items into one box. You have collected a genuine, complete Pretty & Glamour body care kit! You'll be the envy of every cultured socialite in a modern-day Nevada!}
{131}{}{I'm ready to hit the town!}
{132}{}{You're missing something.}
{133}{}{Damn...}
{134}{}{Nothing on the product list looks like anything in your inventory.}
