{100}{}{You see a slot machine.}
{101}{}{You see a slot machine with flashing lights.}
{102}{}{This slot machine is currently occupied.}
{103}{}{You get nothing from this machine.}
{104}{}{This machine is fine and working.}
{105}{}{Nothing.}
{106}{}{An ordinary slot machine. Looks like any other one in this room.}

{107}{}{You examine the machine and find the reason for the high loss rate: someone misplaced the spinners, reducing the chances of winning.}
{108}{}{This explains everything!}