{100}{}{You see documents on a table.}
{101}{}{You see various maps and other documents scattered across a table.}
{102}{}{You can't read while in combat!}

{150}{}{These documents belong to the recruitment officer. He probably won't appreciate you looking through them.}
{151}{}{These documents contain reports for the Nevada Express administrator, as well as up-to-date maps of Nevada.}
{152}{}{[Look for any locations you haven't discovered yet]}
{153}{}{Leave.}

{154}{}{You look through the documents, but you don't find anything new.}
{155}{}{You've found something interesting.}
{156}{}{Copy the raided stagecoach's coordinates into your Pip-Boy.}
{157}{}{Copy Las Vegas coordinates into your Pip-Boy.}
{158}{}{Copy Salt Lake City coordinates into your Pip-Boy.}
{159}{}{Copy Lovelock coordinates into your Pip-Boy.}
{160}{}{Copy Wind of War coordinates into your Pip-Boy.}
{161}{}{Copy Hawthorne coordinates into your Pip-Boy.}
{162}{}{Copy Black Rock coordinates into your Pip-Boy.}
{163}{}{Copy Wendover coordinates into your Pip-Boy.}
{164}{}{[Search more]}
{165}{}{[Done]}
{166}{}{You look for new locations on the map.}
{167}{}{You find nothing of interest.}
{168}{}{[Step away from the maps]}
{169}{}{Copy Uranium City coordinates into your Pip-Boy.}