{100}{}{You see the leader.}
{101}{}{You see the leader of the convoy.}

{102}{}{See you around... Partner.}

{110}{}{Who the hell are you?}
{111}{}{I'm just passing by. What are you carrying?}
{112}{}{I'm, uh, here to collect the product.}
{113}{}{I know why you're here. I present a better offer: sell the weapons to me and walk away alive.}
{114}{}{Oh, I'm just out for a walk. Bye.}

{120}{}{Passing by? All the way out here? At night? ...you just keep on passing, then. Nothing to see here.}
{121}{}{Oh yeah? [he eyes you suspiciously] I was told to wait for someone to call on the radio, but I haven't heard anything. What's going on?}
{122}{}{}
{123}{}{Uh...}
{124}{}{We ran into technical problems with the radio. Do you have the product or not?}
{125}{}{}
{126}{}{Tell me the password.}
{127}{}{Err... "sons of bitches"?}
{128}{}{Password? No one told me about a password.}

{129}{}{[The caravaneers ready their rifles and look around warily] Alright, what the hell's going on?! If you're not from Bertolini, who are you?}
{130}{}{Bertolini's dead. You came all this way for nothing. But I know about your deal and I'm ready to make a counter-offer.}
{131}{}{I represent Bertolini's competitors. We're a lot more powerful than he is. It's in your best interest to work with us.}

{132}{}{Hmm. Well, we came all the way from the Boneyard with these. We're sure as hell not going to take them back. Fine, I'll sell them to you, but don't think you're getting a discount.}
{133}{}{I'll sell it to you for $}
{134}{}{My boss would like to conduct business with you in the future, but these prices are unreasonable. If you want to take advantage of this opportunity, you will lower them.}
{135}{}{Your loss. My boss would like to conduct business with you in the future...}
{136}{}{I have another idea: leave the product and walk away, and I'll allow you to keep your lives.}
{137}{}{I don't like that price. I think I'd prefer to take the product and your lives. [Attack.]}
{138}{}{Hold on, I'll get the money.}

{139}{}{[The guards count the money and allow you to check the weapons in the boxes] Alright, we're done. Tell your boss this isn't going to happen again. We'd wanted to set up a long-term thing, but this is way too sketchy. We're leaving now.}
{140}{}{[Next]}
{141}{}{Sounds good... For now. But if there's trouble next time, it'll be the last. Clear?}
{142}{}{You managed to knock $500 off the price per order. The savings made its way back into your pockets.}
{143}{}{Are you kidding me? Sit down, kiddo, I've been trading since before you were alive and that's just about the worst deal I've ever heard. That's the price, take it or leave it.}
{144}{}{Oh, is that right? [he puts his hands on his hips and narrows his eyes] Is this your first shakedown, kid? Because it sure as hell ain't mine. I don't care what kind of backup you've got, we don't scare easy. So, tell your friends to go home, so we could talk like adults.}

#Ётот разговор не используетс€:
{150}{}{Where do you get the weapons?}
{151}{}{From a workshop in the Boneyard. They're putting together guns using pre-war blueprints. Tough cookies, the lot of 'em. They've been in business about ten years, but outside of some commission work, they mostly make guns for themselves.}
{152}{}{Are you one of them?}
{153}{}{Nah, those guys barely ever leave the workshop. We're the Far Go Traders, from the Hub. We don't usually come all the way out here.}
{154}{}{So what are they? Weapons fanatics?}
{155}{}{Not quite. It's just the only thing they know how to do... Not including their criminal pasts. They came to Boneyard some time ago hoping to settle down. They holed up in an old weapons factory and dug a moat full of radioactive goo. I guess the old blueprints must have been kicking around in there. At first, they didn't talk to anyone, but eventually they started selling guns and ammo for food. Basically, the weapons are the only thing keeping them afloat.}

#∆енские реплики
{1110}{}{Who the hell are you?}
{1112}{}{I'm, uh, here to collect the product.}
{1130}{}{Bertolini's dead. You came all this way for nothing. But I know about your deal and I'm ready to make a counter-offer.}
{1153}{}{Nah, those guys barely ever leave the workshop. We're the Far Go Traders, from the Hub. We don't usually come all the way out here.}