{100}{}{You probably shouldn't touch anything. Especially that big red button... Or that other one.}
{101}{}{You can't use this in combat.}
{102}{}{This console has no further use.}

{104}{}{You see a radio transmission control terminal. It looks like the guards use the radio to communicate, but you can find out about other commands using the console.}
{105}{}{[Use your computing skills to deactivate all slave collars]}
{106}{}{[Activate self-destruction on all the collars]}
{107}{}{[Leave]}
{108}{}{You can't figure out how to do this.}
{109}{}{Command initiated.}
{110}{}{[Exit]}
{111}{}{[Try and deactivate the system using your technical skills]}
{112}{}{The control system is deactivated.}
{113}{}{[End]}
{114}{}{You just can't figure it out.}
{115}{}{[Back]}