{100}{}{This is a usual durable door.}
{101}{}{This door is bolted shut and can only be opened from inside.}
{102}{}{This door is bolted shut and cannot be opened from this side.}
{103}{}{Bolted from inside.}
{104}{}{You remove the bolts and open the door.}
{105}{}{Locked from the other side.}
{106}{}{Opened.}
{107}{}{Not a scratch.}
{108}{}{The explosion rips the door off its hinges. It falls on the floor with a loud thud.}