{100}{}{You see a shabby poster.}
{101}{}{You see an old battered poster. In the center of it you can see a strange bump protruding from the wall.}
{102}{}{This poster is a relic. You don't think its owner would appreciate you damaging it.}
{103}{}{Under the poster you find a safe filled with valuables.}
{104}{}{Wow, there's a lot in here!}
{105}{}{I'm just curious about the movie.}
{106}{}{A classic drama about a gangster with principles. In the post-nuclear wasteland it looks very naive.}