{100}{}{You see an air vent.}
{101}{}{You see the ventilation system. It doesn't work, which is not very surprising.}
{102}{}{You see the ventilation system. Surprisingly, it still works.}
{103}{}{You hear the equipment come to life, but one of the fans is still not spinning.}
{104}{}{Busted.}
{105}{}{This fan is working properly.}

#Repair attempts (skill or tools)
{106}{}{You are not skilled enough to fix this problem.}
{107}{}{I can't do it.}
{108}{}{You've already fixed the system. You don't have to do it twice.}
{109}{}{If it's not broken, don't fix it!}
{110}{}{You fixed the vents.}
{111}{}{Done!}