{100}{}{The front door.}
{101}{}{A door leading to the night club. It looks well-guarded.}
{102}{}{No use.}
{103}{}{The reinforced door withstands your feeble blows.}
{104}{}{ dollars.}

#For male PC
{105}{}{Good day, sir. Here to relax? The entrance fee is }
{106}{}{No problem. Here's the money.}
{107}{}{I've changed my mind. Sorry to bother you.}
{108}{}{I'm a bit short on cash. Maybe another time.}

{109}{}{Uh... Are you sure you're in the right place, ma'am? This is a *gentleman's* club.}
{110}{}{What's the problem? Maybe I'd like to see a dance too!}
{111}{}{Actually, I want to talk to your boss. Maybe I'd have a chance working for her?}
{112}{}{Oh, I had no idea! I'll just go.}

{113}{}{Suit yourself, ma'am. The entrance fee is }
{114}{}{Hmm... Come in then. Mom's office is on the left.}
{115}{}{Thanks.}
{116}{}{I've changed my mind. Sorry to bother you.}

{117}{}{Don't worry, I have an invitation.}
{118}{}{Come right through, sir.}
{119}{}{Come right through, ma'am.}
{120}{}{ Good day.}
{121}{}{ Have a good night.}

#If the PC is an enemy of the club
{130}{}{This door is locked from inside. It doesn't sound like anyone's hurrying to open it.}
{131}{}{Hey, what's this!? What happened to "the customer is always right"?}