{100}{}{A small generator. If you have more time, you can enjoy looking at it a little more.}
{101}{}{You examine the generator, but fail to learn anything interesting.}
{102}{}{This generator does not need repairs.}
{103}{}{After examining the generator, you determine that it was moved here from another location. The rest of the computer equipment probably too.}
{104}{}{Interesting info - but hase no use to me...}
