{100}{}{}
{101}{}{}

#Типовые реплики
{139}{}{All this radon makes your backpack feel warm.}
{140}{}{You did not trick the target.} #If this exclusively refers to traps, I'd prefer "The target evades your trap."
{141}{}{The device successfully affects the target.} #If this exclusively refers to traps, I'd prefer "You catch the target in your trap."

{142}{}{Proceeding}
{143}{}{Done}

{150}{}{}
{151}{}{}
{152}{}{You should hold onto that until the job is done.}
{153}{}{This thief is too experienced to fall for your trick.}
{154}{}{You have been disqualified from the darts game for cheating.}
{155}{}{This ghoul is watching you very closely. Don't even try to trick him.}
{156}{}{No}

####################################################################
#              Установка ловушек
####################################################################

{158}{}{There's already a trap there.}
{159}{}{There is no space for this trap.}

{160}{}{Proceeding...}
{161}{}{Just a minute...}
{162}{}{Easy!}
{163}{}{I'm doing it...}
{164}{}{They won't suspect a thing.}
{165}{}{Kiss my ass, baby!}
{166}{}{This should clean up the gene pool.}
{167}{}{One hot surprise, coming up!}
{168}{}{One hell of an Easter egg...}
{169}{}{Heh-heh-heh...}
{170}{}{Just a moment}
{171}{}{Before someone sees me...}

{180}{}{You've been spotted!}
{181}{}{Hey! What are you doing there?!}
{182}{}{You cannot set traps during combat.}

####################################################################
#              Достижения
####################################################################

{183}{}{Your chem abuse has caused you permanent harm.}
{184}{}{Ooohhhh, dude, I'm wasted... Totally wasted...}

{185}{}{Word gets around. You've developed a good reputation among caravan merchants.}
{186}{}{Word gets around. You've lost your good reputation among caravan merchants.}
{187}{}{You've earned a new achievement and increased your Intelligence score for solving so many detective mysteries.}
{188}{}{You have learned how to craft healing powder and poison antidote.}
{189}{}{Much better now!}
{190}{}{Your dedicated physical conditioning has made you more appealing!}
{191}{}{You've earned the achievement "Safecracker" for picking a large amount of locks.}

#Счетчик вируса
{192}{}{You feel light chills that just won't go away.}
{193}{}{*cough-cough*}
{194}{}{*Unghh*}
{195}{}{Congratulations! Your disease has developed into a full-blown leprosy.}
{196}{}{You feel feverish and nauseous.}
{197}{}{You keep coughing up blood. You need medical attention!}
{198}{}{You are suffering from an infectious disease.}
{199}{}{You feel less sick than before.}

#Дополнительно:
{200}{}{Your Pip-Boy indicates the degree of your radiation poisoning: }
{202}{}{You are now known as the "Hero of the slums".}
{203}{}{How soon they forget. You are no longer known as the "Hero of the slums".}
{204}{}{You have learned how to craft healing powder and poison antidotes.}
{205}{}{You have learned how to craft "Blood-purifier" medicine and "Horsekiller" poison.}
{206}{}{You have learned how to craft "Blood-purifier" medicine, "Horsekiller" poison, healing powder and poison antidotes.}
{207}{}{You have earned the "Sycophant" reputation. Of course, it doesn't work if you tell them that.}
