{100}{}{You see Gerlach.}
{101}{}{You see Gerlach's community patriarch, Mr. Gerlach.}
{102}{}{ }

#Самоубийс'во
{103}{}{They all left me... }
{104}{}{... Left me for a mouthful of bread.}
{105}{}{That's what I get for trying to beat human nature.}
{106}{}{Well. Now nothing is keeping me in this damned place.}
{107}{}{ }

#Плавающие реплики перед поджогом
{110}{}{You stupid son of a bitch!}
{111}{}{We took you in, and this is how you repay us?!}
{112}{}{You put in danger the whole community!}
{113}{}{Did you forget the first rule? "Protect what's ours"!}
{114}{}{But you let your weaknesses to win over you!}
{115}{}{You think only about yourself!}
{116}{}{And now we're all paying the price!}
{117}{}{... The price of your selfishness!}
{118}{}{We won't stand for it!}
{119}{}{Now you'll see what happens when you betray the community!}

#Разговор перед казнью:
{120}{}{Not now, outsider. We'll talk after we deal with this - [spits in disgust] - piece of shit.}
{121}{}{Tell me what's going on here first.}
{122}{}{I won't let you execute this man!}
{123}{}{As you wish.}

{124}{}{I said later! Stay out of our affairs!}
{125}{}{Wait... }

{126}{}{[Someone yells from the crowd] Gerlach, let him speak! He should know why we're doing this!}
{127}{}{Exactly!}

{128}{}{[He growls in frustration] Fine! Listen, outsider. This bastard - [he points at the prisoner] - was supposed to watch the community's water pump. But when it overheated and had to be shut down, his dumb ass was asleep! Now we're all gonna die of thirst thanks to his carelessness! [he grabs the prisoner's hair and violently shakes his head back and forth]}
{129}{}{I can fix the water pump, if you give me time.}
{130}{}{This bastard deserves what he gets! Hang him!!!}
{131}{}{}
{132}{}{Gerlach, this is low - to lay your hands on those who are weaker.}
{133}{}{What if I buy his life?}
{134}{}{This really isn't any of my business. Do as you will.}

{135}{}{[His eyes blaze with anger] What?! What did you just say to me? Shut your mouth! Nobody asked you!}
{136}{}{Hey, calm down... }

{137}{}{You can? Do you know anything about technology?}
{138}{}{Yes, I'm a decent mechanic.}
{139}{}{No, but I have connections. This is going to be easy.}
{140}{}{Hmm... [he looks over at the crowd] Why should we trust you, outsider?}
{141}{}{Do you have a choice?}

{142}{}{No, we don't... Fine. We won't kill him, at least for now. But he's not going anywhere until you fix the pump. And if you don't, I'll take care of him myself.}
{143}{}{What if I buy him out?}
{144}{}{Actually, I changed my mind. I don't care about that guy. Burn him!}
{145}{}{Fine, we have a deal. I'll come back for him when the pump is fixed.}

{146}{}{[The prisoner is untied from the pole and dragged into a nearby house. The spectators disappointedly disperse.]}
{147}{}{[End]}
{148}{}{You've given the man a few more days of life.}

{149}{}{The money have little value in our community. But we could buy some things we need in Reno... Fine, a thousand bucks for this scum's hide, and don't even try dickering with me.}
{150}{}{A man's life is far more valuable. Here's the money.}
{151}{}{You saved a life of a complete stranger.}
{152}{}{I don't have that kind of money. Can I pay you later?}
{153}{}{[The prisoner is untied from the pole and dragged into a nearby house. The spectators disappointedly disperse.]}
{154}{}{[End]}

{155}{}{We'll keep him here until you bring the money. He's not going anywhere until you do.}
{156}{}{So be it. I'll come back when I have the money.}
{157}{}{Actually, I have a thousand dollars right here. Here you go.}

{158}{}{[He frowns at you] What are you saying?}
{159}{}{Look at yourselves! Now that you're all in trouble, you're going to turn on each other? What kind of people would do this to their neighbor?}
{160}{}{You got a way with words, I'll give you that. Maybe we did go a little overboard. [he turns to the crowd] What do you think, people?! [some of the villagers nod approvingly]}
{161}{}{Let him go. Killing him won't help anyone.}
{162}{}{Fine, goddammit... Fine. This kid's lucky for your silver tongue. [leans in close] But I catch you doing anything dirty, anything at all, you're not walking out of here. Get it?}
{163}{}{Okay, Gerlach. I got it.}
{164}{}{[He gives you a wild stare and hisses] Who the hell are you to know? You're going to give me - ME! - a lecture about life?! To a caravan guard with ten years of experience? Stop messing with me or get the hell away from here!}

{165}{}{You watched a man be executed right in front of your eyes.}
{166}{}{[Pulls the man's head back by his hair and screams into his face] You hear that, scum?! Even some stranger from the wastes wants you dead! Take one last look at the people you betrayed, before we send you to hell.}
{167}{}{[End]}
{168}{}{You got what you deserved.}
{169}{}{NOOOOOO!!!}

#Разговор после казни
{170}{}{Ah, wanderer, come in! How can I help you?}
{171}{}{Oh, it's you, outsider. You're still here?}
{172}{}{About the pump... }
{173}{}{Can I speak to the prisoner?}
{174}{}{I want to buy the prisoner's life.}
{175}{}{}
{176}{}{I'll come back later.}
{177}{}{After all that's happened, I didn't even think we'd meet again.}

{180}{}{What the hell for? You got a good reason, or are you just trying to help him escape?}
{181}{}{No way... }
{182}{}{I want to talk to him about the repairing the pump.}
{183}{}{Hmm. Fine, have it your way. You can talk to him. Rico's watching him in the next building.}
{184}{}{Thanks.}
{185}{}{I don't think so. His dumb ass broke the pump in the first place, and now you want his advice? Go ask a real mechanic and don't bother me with this crap.}
{186}{}{Nice try, Mister Fixit. I know a working man's hands when I see them - you'll do just fine without that dumbass's help.}
{187}{}{Well, that didn't work.}

{188}{}{We'll wait. For now, he's our prisoner.}
{189}{}{Fair deal. [he hides the money in his pocket] He's free to go. But I can't figure why you give a damn about that idiot.}
{190}{}{You can't understand everything just with your mind, Gerlach. I'll see you around.}

#Насос:
{191}{}{Without the pump, we'll have no water. We'll have to leave this place.}
{192}{}{What can be done?}
{193}{}{I'm no mechanic, but some part of the pump seems to have broken. We've got two choices: find someone to repair it, or replace the part.}
{194}{}{What will I get in return if I fix the pump?}
{195}{}{I'll get the pump working for you.}
{196}{}{I'll make it worth your while. I've got connections in... Well, it doesn't matter what kind of connections. I can get you a good weapon, if you're interested.}
{197}{}{I'll do it!}
{198}{}{Not interested.}

{199}{}{Well, think of something. Or have you forgotten what you saw when you first arrived here? That was that idiot's last chance. Now think about the rest of the community - how long will they last without water?}
{200}{}{Of course, I'll try to help you.}
{201}{}{You know, I don't care anymore. Deal with it yourself.}
{202}{}{Good! I look forward to any news from you. No one else here can deal with this.}
{203}{}{Too bad, but I've got to go.}

{204}{}{The pump is working again.}
{205}{}{Really? We can drink fresh water again? I was starting to lose hope! Thank you. These dumbasses couldn't have done it on their own.}
{206}{}{What about my reward?}
{207}{}{Don't mention it.}

{208}{}{I'll get you a decent weapon of your choice. What would you prefer?}
{209}{}{10mm pistol and some ammo.}
{210}{}{10mm SMG with fully loaded clip.}
{211}{}{Cattle prod with some batteries.}
{212}{}{7 frag grenades.}
{213}{}{A double-barreled shotgun and 20 shells.}
{214}{}{I think I'm good. Free that guy, it's all that matters.}
{215}{}{I don't want anything. I'm leaving.}

{216}{}{Are you serious? I've never seen anything like that. I won't make this offer a second time.}
{217}{}{You're right, there must be something wrong with me! I need a weapon.}
{218}{}{Let that guy go.}
{219}{}{I'm sure. I don't need anything. Take care.}

{220}{}{Fine, I'll let Steve go.}
{221}{}{Excellent!}

{222}{}{Hmm... Let me think. Yes, I can get you that SMG.}
{223}{}{Sounds good.}
{224}{}{Yeah, yeah. He'd just better stay the hell out of my sight.}
{225}{}{No problem.}

{226}{}{Good choice! But you'll have to wait a day or two for my courier to pick up the package.}
{227}{}{I'll wait then.}

{228}{}{My courier's not back yet. Just wait a little longer.}
{229}{}{Okay.}
{230}{}{Here's your payment! It may not look like much, but it's the best I can give you. You take care of yourself, now.}
{231}{}{Fine.}

{232}{}{You got 7 fragmentation grenades.}
{233}{}{You got a 10mm SMG.}
{234}{}{You got a shotgun with 20 shells.}
{235}{}{You got 10mm pistol with 48 10mm rounds.}

{236}{}{So, what about my reward?}
{237}{}{You got a cattle rod with some batteries.}
{238}{}{Cattle rod and some batteries for it.}

#Про казненного
{250}{}{Do you always execute people when they screw up?}
{251}{}{His "screw up" threatened all of our lives. It was too much to forgive. Everyone must know our community won't tolerate this kind of carelessness.}
{252}{}{Tough town. But I'll risk asking just one more question.}
{253}{}{What are you, some kid fresh out of the vault, wanting to save the world? Ha! Don't make the old man laugh. If not for my rules, everyone here would be lost in the sands of the wasteland.}

#Про кражу из 'айника
{254}{}{Hey outsider, wait. Was that you sneaking around my house? No? Well, watch yourself - I don't want to see any bullshit from you. We solve those kinds of problems fast around here. Clear?}
{255}{}{Uh, sure, clear. Whatever you say.}

#Переселение в убежище 8
{270}{}{It sure is quiet around here lately, isn't it Gerlach?}
{271}{}{[He laughs bitterly] I didn't expect anything else from those idiots. A collective community... Where the fuck did I even get that bullshit? Every animal just wants to eat. But here, at least, they owned their meals. There? They'll just be someone's slaves. They paid for their food with their freedom.}
{272}{}{Hmm, that's not far from the truth. But they made their choice.}

{273}{}{Well, Gerlach, your community is about to leave you. Are you aware of that?}
{274}{}{Idiots! I should have known. A collective community... Where the fuck did I even get that horseshit? Every animal just wants to eat. That's why they're leaving, so they'll know where their next meal is coming from. A utopia, in times like these.}
{275}{}{Hmm, you may be right. Time will tell.}

{276}{}{As a representative of Vault 8, I propose that you come work for us in exchange for food, shelter and protection.}
{277}{}{Vault, you say? Hmm... I can't make that kind of decision. You can ask the people here yourself. But I'm not going anywhere!}
{278}{}{I'll go talk to the community then.}

#Ис'ория поселения
{280}{}{Can you tell me the history of this place?}
{281}{}{[He nods] With pleasure. You want the long or the short version?}
{282}{}{Short.}
{283}{}{Tell me everything.}
{284}{}{Forget it, I changed my mind.}

{285}{}{Few years back, I offered the people I knew in Reno the chance to create our own community. Crazy enough, a few of them agreed, and we founded this place. After the first few raider attacks, we earned a good name for ourselves, and more people came. Now we're totally self-sufficient.}
{286}{}{Tell me more!}
{287}{}{I think I've heard enough. Let's talk about something important now.}

{288}{}{Well, the real story goes back long before I actually came to this place. It started a long time back, probably about ten years ago.}
{289}{}{I'm listening.}
{290}{}{Oh no, is it too late to get the short version?}
{291}{}{Maybe we should end it at that. Take care.}

{292}{}{I worked as a caravan guard back then. We wandered all over California - or what was left of her. Bad as it is now, it was worse then. Every town and village had at least one gang waiting to fuck you.}
{293}{}{More?}
{294}{}{Caravan fell on hard times - our own people betraying us, or just walking away. Didn't do much for my opinion of people, let me tell you. But then... }
{295}{}{We found a small village, all one big family. Inbred as all hell - you could see their kids were fucked up. But they protected their own, didn't even let us close to them.}
{296}{}{Each of them would give their last drop of blood to protect their children. It surprised me. I was an orphan - I couldn't understand it.}
{297}{}{I thought about it for a long time. In the end, I realized, that's what we needed - a collective community where people don't just live for themselves, but for the common good. A small community where everyone would know each other, where everyone would be responsible for their work, where everyone would be *unified*. And anyone who couldn't pull their weight would be cast out.}
{298}{}{I talked to people in Reno about this. A lot of them laughed. But some of the others... They saw what I was saying.}
{299}{}{Together, we found this place and actually made it livable! Now, most of them were killed by raiders early on, but we managed to fend them off. Once word got out, new people came.}
{300}{}{Now we have everything we need. We're pretty much independent. And I hope it stays that way!}
{301}{}{Thanks. I have no more questions, Mister Gerlach.}

#Пропавший с'ара'ель из Рино
{310}{}{Has anyone from New Reno come here recently? His name's Mark. He was a prospector.}
{311}{}{We haven't had new settlers in quite some time. Anyone coming to these parts probably went to Black Rock. They're taking in a lot of new people.}
{312}{}{Thanks, that will be all.}

#Пропавший посыльный
{313}{}{Do you know anything about Milo's disappearance?}
{314}{}{No. Why should I? The desert's a dangerous place. Geckos, radscorpions, even raiders. If he doesn't come back, it's going to be hard on his wife. You understand.}
{315}{}{Milo is married? Maybe I should talk to her.}

{316}{}{Hmm... [looks at everybody] Perhaps... There is something about you, wanderer.}

#Female character
{1120}{}{Not now, outsider. We'll talk after we deal with this - [spits in disgust] - piece of shit.}
{1126}{}{[Someone yells from the crowd] Gerlach, let her speak! She should know why we're doing this!}
{1128}{}{[He growls in frustration] Fine! Listen, outsider. This bastard - [he points at the prisoner] - was supposed to watch the community's water pump. But when it overheated and had to be shut down, his dumb ass was asleep! Now we're all gonna die of thirst thanks to his carelessness! [he grabs the prisoner's hair and violently shakes his head back and forth]}
{1135}{}{[His eyes blaze with anger] What?! What did you just say to me? Shut your mouth! Nobody asked you!}
{1140}{}{Hmm... [he looks over at the crowd] Why should we trust you, outsider?}
{1144}{}{Actually, I changed my mind. I don't care about that guy. Burn him!}
{1163}{}{Okay, Gerlach. I got it.}
{1170}{}{Ah, wanderer, come in! How can I help you?}
{1171}{}{Oh, it's you, outsider. You're still here?}
{1185}{}{I don't think so. His dumb ass broke the pump in the first place, and now you want his advice? Go ask a real mechanic and don't bother me with this crap.}
{1186}{}{Nice try, Miss Fixit. I know a working woman's hands when I see them - you'll do just fine without that dumbass's help.}
{1217}{}{You're right, there must be something wrong with me! I need a weapon.}
{1254}{}{Hey outsider, wait. Was that you sneaking around my house? No? Well, watch yourself - I don't want to see any bullshit from you. We solve those kinds of problems fast around here. Clear?}
{1284}{}{Forget it, I changed my mind.}
{1316}{}{Hmm... [looks at everybody] Perhaps... There is something about you, wanderer.}
