{100}{}{You see Rico.}
{101}{}{You see a muscular bouncer named Rico.}

{102}{}{Don't interfere. This doesn't concern you.}
{103}{}{::nods respectfully::}
{104}{}{We need more people like you around here.}

{110}{}{Are you looking for trouble in my house?}
{111}{}{Yes, and I just found one. I'm going to solve it now.}
{112}{}{I need to see the guy.}
{113}{}{Just popping in to say hi. See you later.}

{120}{}{[He cracks his knuckles] That's it, you asked for it.}
{121}{}{Wait, wait, I'm sorry! It won't happen again!}
{122}{}{Wait, I just want to see the guy!}
{123}{}{Bring it on, you meat sack!}

{124}{}{[He slowly exhales through his nostrils] Today's your lucky day. Next time, you'll be pissing blood.}
{125}{}{Ehh...}

{126}{}{You again? Get the fuck out of here. This is your last warning.}
{127}{}{Okay, okay, I get it.}
{128}{}{That's it. Your ass is mine!}
{129}{}{Come and get it.}

{130}{}{You're not allowed there. If you want to see the prisoner, talk to Gerlach.}
{131}{}{I go where I want. Back off before I'll get angry.}
{132}{}{Gerlach said I can talk to him.}
{133}{}{Okay, I'll go see your boss.}

{134}{}{[He mutters something under his breath] ...Fine. Don't try anything funny in there.}
{135}{}{Of course!}

{136}{}{Fix the pump first. You can see the prisoner when you're done.}
{137}{}{You should think about being nicer to me. You don't have daddy Gerlach watching out for you anymore.}
{138}{}{Fine, but I'll be back.}

#Æåíñêèå ðåïëèêè
{1127}{}{Okay, okay, I get it.}
{1129}{}{Come and get it.}
