{100}{}{You see Steve.}
{101}{}{You see a scrawny guy. His clothes are dirty with rust flakes.}

#Плавающие о'ве'ы
{102}{}{Help! They're gonna kill me!}
{103}{}{You bastard!!! She was all I had!}
{104}{}{Oh, god! She was all I had left!}

#########################################################
#
#  Разговор в 'юряге
#
#########################################################

{110}{}{You saved my life! For how long, I don't know, but before you showed up, I didn't have a chance!}

{111}{}{Gerlach is dead. You're free now.}
{112}{}{What happened?}
{113}{}{About that water pump... }
{114}{}{Any ideas of how to get out of this basement?}
{115}{}{I'll be back. Don't go anywhere.}

#########################################################
#
#  Разговор НЕ в 'юряге
#
#########################################################

{120}{}{You saved my life, man! But the people here will never forgive me. Damn it.}
{121}{}{It's you! Good to see you, man. Not a lot of guys like you left in the wastes.}

{122}{}{Can you fix the water tank in Lovelock?}
{123}{}{About that water pump.}
{124}{}{How can you pay me for my help?}
{125}{}{What really happened, anyway?}
{126}{}{Why don't you leave this place?}
{127}{}{Tell me about you and your sister.}
{128}{}{Tell me about this place.}
{129}{}{Take care.}

#########################################################
#
#  О'ве'ы при разговоре в 'юряге
#
#########################################################

{130}{}{[He grabs his head] I didn't mean for this to happen! Now the community is doomed for sure! [suddenly looks up] Where's Susie? Is she okay?!}
{131}{}{Uh, yeah, sure. I'll just see you outside.}

{137}{}{No way, I can't leave my sister. And where would I go? Black-Rock would never take me, and Reno... No, I'll never go back to Reno.}

{139}{}{I fixed the water pump. It's running smoothly now.}
{140}{}{I have this fuse. Will this help?}
{141}{}{Holy shit, this is perfect! Where'd you get it? Go show it to Gerlach, and he might let me go!}
{142}{}{This one? Looks like that part I blew up.Please, install it into the pump... Uh, carefully. I'd do it myself, but Gerlach won't let me outside.}

{143}{}{I can free you, if you pay.}
{144}{}{I don't have anything... But I know where to find a stash of good stuff. But I won't tell you until I'm out of here!}
{145}{}{We'll see.}
{146}{}{Oh, I almost forgot. If you need any help, just talk to me. I can improve a leather jacket for you - not just stronger, but optimized to carry more stuff.}
{147}{}{I'll think about it. Bye.}
{148}{}{You have freed the prisoner from his captivity.}

#########################################################
#
#  О'ве'ы при разговоре НЕ в 'юряге
#
#########################################################

{149}{}{People here are from all over. Gerlach thinks we can survive if we all stick together and take responsibility for ourselves. I've never seen a place like this before, but I really believed in it, even though it almost got me killed. Now, I don't know what to think.}
{150}{}{People here are from all over. Gerlach thinks we can survive if we all stick together and take responsibility for ourselves. I've never seen a place like this before, but I really believe in it, even if it almost got me killed.}
{151}{}{I'm just a guy from New Reno. I do this and that, but my sister's the skilled one. Everyone loves her cooking.}
{152}{}{I have nowhere to go. Me and my sister aren't going back to Reno, and there's nothing in the wastes but geckos and radscorpions. This is all we've got.}

{153}{}{They had me watch the water pump. It's the only source of water out here.}
{154}{}{Go on.}
{155}{}{But it's old, and you've got to keep an eye on it. I fell asleep on the job and the fuse burned out... I think that's what it's called. Whatever it is, the pump won't work without it.}
{156}{}{Long story short, we've got no water. So, everyone was going to have me for it. That's when you came along.}
{157}{}{It's all my fault. I nearly got myself killed, I nearly left my sister all alone, I nearly destroyed the whole community... This is heavy. Makes you rethink everything. I feel like a different man... I've got to start taking responsibility.}

{158}{}{It works great, all thanks to you. You didn't just save me, you saved the whole community.}
{159}{}{The fuse burned out and I don't have a slightest clue how to fix it. You'll need to find a new one, or make one yourself, if you know how.}

{160}{}{Will this fuse do the job?}
{161}{}{That's all.}
{162}{}{Only one way to find out! Hurry, we need that water yesterday!}
{163}{}{Fine.}

{164}{}{Reno? How far is it?}
{165}{}{Not that far. I'll show you on your map. But it gets more dangerous the closer you get, so try to stay off the roads.}
{166}{}{Thanks.}

#########################################################
#
#  Водосборник в Лавлоке
#
#########################################################

{170}{}{Hell yeah, I'll do it! I owe you my life! I'll go get it done right now!}
{171}{}{Please do.}
{172}{}{No, wait. I'll figure it out myself. And if I can't, I'll come back and ask for your help.}
{173}{}{Well, okay. But I'm always ready to work!}
{174}{}{Perhaps you're right. Head to Lovelock.}
{175}{}{Stay here. I'll come get you if I need you.}

{176}{}{Leave it up to me! I won't blow this up!}
{177}{}{Great.}

{178}{}{I would, but if I try to leave before the pump is fixed, they'll probably try to kill me again.}
{179}{}{Right.}

{180}{}{You found an easy way to fix Lovelock's water shortage.}

#########################################################
#
#  Чем помочь
#
#########################################################

{181}{}{Let me think... I don't have much. But I can improve your leather jacket or do any sort of handyman work. }
{183}{}{Uh, sure.}
{184}{}{I'll come back if I need your help.}
{185}{}{Oh, wait! [he gives you some weapon parts] It's not much, but I'm sure you can use these for something. That, or sell them.}

{190}{}{I have a leather jacket for you to fix up.}
{191}{}{This leather jacket's seen better days. Can you restore it?}
{192}{}{Sure! Give it here.}
{194}{}{What jacket? I don't see it.}
{195}{}{Oops... }
{196}{}{Done! Try it out!}
{197}{}{Okay.}

#########################################################
#
#  Про переселение
#
#########################################################

{200}{}{What do you think about moving from here?}
{201}{}{This place isn't safe without Gerlach. If we get the chance to move, we'd better take it.}
{202}{}{After that situation with the pump, it's only a matter of time before Gerlach finds some reason to get rid of me. If I get the chance to move, I'll take it.}

{203}{}{You said something about a stash earlier.}
{204}{}{Oh, yeah, well... I don't actually know where it is, but my sister told me about it once. Ask her and she'll tell you.}
{205}{}{It's the same one my sister told you about.}
{206}{}{Oh, is that how it is?}
{207}{}{[His smile fades] Didn't my sister already tell you about Gerlach's stash? What else do you want?}
{208}{}{Okay!}

#########################################################
#
#  Женский вариан' реплик
#
#########################################################

{1110}{}{You saved my life! For how long, I don't know, but before you showed up, I didn't have a chance!}
{1120}{}{You saved my life! Thank you. But the people here will never forgive me. Damn it.}
{1121}{}{It's you! Good to see you again. Not a lot of girls like you left in the wastes.}
