{100}{}{You see a villager.}
{101}{}{You see a very sad woman.}

#Попытка заговорить во время казни
{102}{}{I can't watch this...}
{103}{}{I'm not coming out until it's over.}
{104}{}{Run! As far as you can! They're all crazy!}
{105}{}{How can they do this?}

#Попытка заговорить после казни:
{110}{}{You... You're not from Black Rock, are you?}
{111}{}{No. Can we chat anyway?}
{112}{}{[She sadly sighs] I'm sorry. I am not in the mood to talk right now. Maybe someone else can help you...}
{113}{}{That's probably a good idea.}
{114}{}{You? But... I don't think I can help you with anything.}
{115}{}{No, but I bet you need help.}
{116}{}{Goodbye.}
{117}{}{Sorry, I don't trust strangers. Unless you're from Black Rock, we have nothing to talk about. Please, just leave me alone.}
{118}{}{Okay.}
{119}{}{No worries, I just came from there. Are you Milo's wife?}
{120}{}{Milo?! You know Milo?! Where is he?!}
{121}{}{Wow, calm down. That's what I was about to ask you...}
{122}{}{This will be hard to hear, but... Your husband is dead. He's buried in Black Rock cemetery.}
{123}{}{He's at peace, in a better place. Specifically, a nice quiet grave where he doesn't have to listen to your whining and moaning anymore. I bet the gravedigger in Black Rock gave him a better fuck than you ever did, too.}
{124}{}{No, I don't know anything! Calm down!}
{125}{}{Oh, Milo... No one have seen him since he took those damn pelts to Black Rock! Neither here, nor there! He couldn't just disappear in the middle of the desert, could he?! I miss him so much...}
{126}{}{What was he doing before he left?}
{127}{}{How did he look when he left?}
{128}{}{Nothing unusual... But wait a second. The day before he left, some young man I've never seen before came to see him. He had a leather jacket and looked scruffy, like some New Reno thug. I don't know what they talked about, but Milo kicked him out pretty quickly.}
{129}{}{Brown hair, very tanned, average height for a man... Oh, but he had his good leather boots! Milo always said that if you walk for a living, you need good boots. He made them himself, from brahmin leather. They have a star on the sole and a knife sheath on the right boot. I still remember watching him make them... He has such beautiful hands...}
{130}{}{So Milo had an argument with a young punk before leaving to Black Rock, while wearing his leather boots with a star on the sole. I should remember that.}

{131}{}{Th-thank you... [she starts to sob] ...Now I know...}
{132}{}{I'll leave you alone.}
{133}{}{[She recoils as if struck, then starts to cry] You - you *monster*! GET OUT!}
{134}{}{Whatever.}
{135}{}{Please, leave me. We have nothing more to talk about anyway.}

{136}{}{Oh, it's you again.}
{137}{}{Can I ask you some questions about Milo?}
{138}{}{Something wrong?}
{139}{}{I think we should stop here.}
{140}{}{That helps explain things.}

{141}{}{Aww, boo-hoo. Lucky Milo, at least he doesn't have to deal with this anymore.}
