{100}{}{You see a villager.}
{101}{}{You see a gloomy citizen of Gerlach wearing dirty clothes.}

#Попы'ка заговори'ь во время казни
{102}{}{You don't belong here.}
{103}{}{This doesn't concern you.}
{104}{}{Keep moving.}
{105}{}{This is none of your business.}
{106}{}{Don't get in the way.}
{107}{}{Kill him!}
{108}{}{What are you doing here?}
{109}{}{}

#Попы'ка заговори'ь после казни:
{110}{}{I've got nothing to say to you, outsider. Talk to Gerlach, he's in charge here.}
{111}{}{What can you tell be about this place?}
{112}{}{Where and who is Gerlach?}
{113}{}{What do you think about the executions?}
{114}{}{Great, I'll talk to him.}

{115}{}{We look out for each other here. If you're not with us, you'd best be moving on.}
{116}{}{He founded this place. He lives in that house to the south-west.}
{117}{}{I'm not in the mood to talk about that. If you must know, then no, I don't like seeing them, but we don't have a choice. The wasteland's a cruel place.}
{118}{}{He's dead. I don't know if we'll make it without him.}

{119}{}{Oh, it's you! It's good to see you around here again. Can I help you with something?}
{120}{}{I'm just passing by.}

#Джерлак мер'в
{121}{}{Gerlach's gone. We'll probably be following him soon enough.}
{122}{}{That was so stupid!! How are we going to live without our leader? Get the hell out of here!}
{123}{}{Fine, I'm going.}

#Предложение о' Города Убежища
{124}{}{Would you like to move somewhere safer?}
{125}{}{Safer than this? In a heartbeat. Why?}
{126}{}{Then congratulations on being the first to move to our vault!}
{127}{}{Oh, no reason. Just thinking out loud.}
{128}{}{Vault? As in, Vault-Tec? Where?}
{129}{}{Just a few days north.}
{130}{}{[You notice other villagers gathering around you] And we can just live there? What's the catch?}
{131}{}{The catch is, if you accept, you can never come back.}

{132}{}{[The villagers look at each other] Why should we believe you?}
{133}{}{I fixed your water pump. The vault has far more advanced technology.}
{134}{}{Without Gerlach, it's your only chance.}
{135}{}{If I helped Steve, why wouldn't I help you?}
{136}{}{Uh... Well, I can't really prove it, but it really is better than this place! I pinky swear!}

{137}{}{Prove it. We've got no reason to trust you.}
{138}{}{Take a look at by Pip-Boy. These were only given to vault dwellers.}
{139}{}{Then I've got no reason to help you. Your loss.}

{140}{}{He did earn a little respect, didn't he? [the crowd shouts in agreement] Okay, we'll do it. We've got nothing to lose, anyway. This place can't hold out forever.}
{141}{}{Great!}
{142}{}{How do we know you didn't take it off a body? Better yet, why shouldn't we take it off yours?}
{143}{}{Come on, would I lie to you? Fine, maybe you'll change your mind later.}
{144}{}{I've heard of these, but I've never seen one. If these are given to everyone in the vault, then I agree! [the rest of the crowd mumbles in approval]}
{145}{}{Of course!}

{146}{}{We have plenty of food and water. You'll never go hungry or thirsty again.}
{147}{}{I've heard enough! You've got yourself a new neighbor, buddy!}
{148}{}{Great!}
{149}{}{Oh, food and water, I've never heard *that* one before. Yeah, right! I don't buy it.}
{150}{}{Don't believe me? That's too bad. Take care.}

{151}{}{He's right! [everyone nods] Yes, we could try. You've shown you can be trusted.}
{152}{}{Great!}
{153}{}{You may have fixed the pump, but that doesn't prove you can be trusted. What if this is all a big trick?}
{154}{}{Well, think about it. Maybe you'll change your mind later.}

{155}{}{Who knows? Steve hasn't been here long, we don't know him too well. Maybe you saved him for some reason we don't know about. Why should we trust you?}
{156}{}{You don't trust me? Ouch. Maybe I can do something to fix that.}

{157}{}{Yeah, and you killed him! How do we know you won't do the same to us?}
{158}{}{It's true. Without Gerlach, this place won't survive. [villagers whisper to each other in agreement] I believe you, outsider. What other choice is there?}
{159}{}{We're all adults here, we can survive without Gerlach. But you, outsider - you haven't given us much reason to trust you yet.}

{160}{}{When we are heading out?}
{161}{}{I'll go back to the vault and tell them you're ready. Wait for someone to come get you.}
{162}{}{You've convinced the community to move to Vault. All that's left is to report to Sergeant Stark.}
{163}{}{We'll wait. But don't even think of betraying our trust. We can still hold guns in our hands.}
{164}{}{Of course, just wait!}
{165}{}{We've been waiting for your people. Where the hell are they? We're not going to sit around forever.}

#Female character
{1120}{}{I'm just passing by.}
{1128}{}{Vault? As in, Vault-Tec? Where?}
{1133}{}{I fixed your water pump. The vault has far more advanced technology.}
{1135}{}{If I helped Steve, why wouldn't I help you?}
{1140}{}{She did earn a little respect, didn't she? [the crowd shouts in agreement] Okay, we'll do it. We've got nothing to lose, anyway. This place can't hold out forever.}
{1147}{}{I've heard enough! You've got yourself a new neighbor, missy!}
{1150}{}{Don't believe me? That's too bad. Take care.}
{1151}{}{She's right! [everyone nods] Yes, we could try. You've shown you can be trusted.}
{1153}{}{You may have fixed the pump, but that doesn't prove you can be trusted. What if this is all a big trick?}
{1158}{}{It's true. Without Gerlach, this place won't survive. [this villagers whisper to each other in agreement] I believe you, outsider. What other choice is there?}
{1159}{}{We're all adults here, we can survive without Gerlach. But you, outsider - you haven't given us much reason to trust you yet.}
