{100}{}{You see Susie.}
{101}{}{You see a very attractive girl. She seems bothered by something.}
{102}{}{You see a very attractive girl.}

#Åñëè ïîãóáëåí åå áðàòà:
{103}{}{You heartless bastard! How could you?!}
{104}{}{Please, help! They'll kill him!!!}
{105}{}{My brother... Why...?}

#################################################
#
#  Ñòàðò äèàëîãà è âîïðîñû
#
#################################################

{109}{}{Thank you for helping my brother! But what will happen to our community now?}
{110}{}{Thank you, but my brother is still in danger. If we can't fix that pump, they'll kill him for sure!}
{111}{}{Thank you for helping my brother!}

{112}{}{What are you going to do now?}
{113}{}{Tell me about yourself and your brother.}
{114}{}{Why is everyone so angry at your brother?}
{115}{}{How can we free your brother?}
{116}{}{I'm going to need more than a "thank you" for my help.}
{117}{}{You don't think I did this for free, do you?}
{118}{}{Can you tell me about this settlement?}

{119}{}{Maybe later. I'll come back.}
{120}{}{Don't mention it.}

{121}{}{Is Reno far from here?}
{122}{}{How do you feel about moving away from here?}

#################################################
#
#  Îòâåòû íà âîïðîñû
#
#################################################

{150}{}{What *can* we do? We can't leave. There's nothing but desert, dust and death out here. We have to stay here until we find someplace better.}
{151}{}{We lived in Reno. It wasn't always so bad, but by the time we left people were dying every day. We heard about Gerlach from some caravaneer and thought, why not?}
{152}{}{About a week on foot. [she points south] But it's a bad place to be nowadays. People like you should stay away from there.}
{153}{}{Steve was watching the water pump when it broke, and everyone went crazy! It's our only source of water, but they still shouldn't have tried to kill him!}
{154}{}{That meathead from Reno is keeping him in his basement. Gerlach won't touch Steve as long as you have a deal with him, or if we've got water left in the tank. Our only hope is for you to fix the pump... You won't leave us like this, will you?}
{155}{}{Me and my brother only got here a short time ago, so I don't know much. A caravan merchant told us that everyone here works together to support the community, and we wanted to be part of that. I wish he'd told us that they'll kill you if you make a mistake!}
{156}{}{Gerlach's dead, so Steve's free. But what's the point? When no water will be left in the tank, they kill us anyway.}

{157}{}{I've thought about it, but I won't leave without my brother. He's all I've got.}
{158}{}{We'll have to find somewhere else to go. We don't have a choice - without Gerlach, this place will fall apart.}
{159}{}{I'll go if everyone else goes.}

{160}{}{Me and my brother only got here a short time ago, so I don't know much. A caravan merchant told us that everyone here works together to support the community, and we wanted to be part of that. I wish he'd told us that they'll kill you if you make a mistake!}

#################################################
#
#  Öåíà çà âîçíàãðàæäåíèå
#
#################################################

{200}{}{And for once I thought someone just wanted to help. Well, I don't have anything valuable, but I know where Gerlach has his good stuff hidden. If you help my brother, I'll show you.}
{201}{}{And for once I thought someone just wanted to help. Well, I don't have anything valuable, but I know where Gerlach has his good stuff hidden.}
{202}{}{If this stuff is so good, why haven't you taken it yet?}
{203}{}{Food, water, shelter and family is important to me. Money isn't. Anyway, Gerlach would figure it out pretty quick if someone in the community had his stuff. You don't have that problem.}

{204}{}{Show me the damn stash! I want everything in there!}
{205}{}{Susie said the stash is somewhere around here.}

#Ïëàâàþùèå ôðàçû äëÿ òàéìåðà, êîãäà áðàò ìåðòâ (ëþáûì ñïîñîáîì)
{300}{}{::cries::}
{301}{}{::sighs::}
{302}{}{Ohhh...}
{303}{}{::wipes her tears::}
{304}{}{What do I do now?..}
{305}{}{::mumbles something::}
{306}{}{I can't stay here...}
{307}{}{Who will protect me now?}
{308}{}{Where can I go?}
{309}{}{I have no one left now...}

#Female character
{1116}{}{I'm going to need more than a "thank you" for my help.}
{1117}{}{You don't think I did this for free, do you?}
