{100}{}{You see Evan.}
{101}{}{You see Evan, a hardened trapper.}
{102}{}{}
{103}{}{Head back to the village, I'll catch up.}

{110}{}{There's a gecko nest in this cave, one of a few in the area. It'll be swarming with them, so be careful. If you're quick and quiet, you shouldn't have too much trouble.}
{111}{}{My job is to collect the eggs, right?}
{112}{}{...without wiping out gecko's population, yeah. Keep at least half of them alive, or we won't have anything to eat next season.}
{113}{}{You can count on me.}
{114}{}{I'll be waiting for you by the exit at the other side of a cave. Be careful and try not to run off in fear. You'll be shamed all over settlement. Won't lend you a helping hand then.}
{115}{}{I'll see you.}

{120}{}{That was quick. How's the hunt? Any luck?}
{121}{}{I'm just getting some fresh air. I'll be right back with the eggs.}
{122}{}{I heard screams! What the hell is going on in there?}
{123}{}{Things got messy, but I managed to get the eggs.}
{124}{}{I'll explain later. Right now, I have to go back inside.}
{125}{}{I got the eggs. Are these enough?}

{126}{}{What?! Aww, I knew I shouldn't have trusted this to a rookie! We should be okay if you only killed a few, but if you wiped out more than half the pack...}
{127}{}{Um, and the eggs?}
{128}{}{Show me.}
{129}{}{[Open the backpack]}
{130}{}{I can get more. Wait here.}
{131}{}{That's it? Listen, they won't send a caravan unless we have at least ten eggs. Any less than that, and we're wasting our time.}
{132}{}{Right...}

{135}{}{That's enough, give them to me. Time to hurry back to village, before we get noticed.}
{136}{}{[Give him all eggs]}
{137}{}{Wait, hold on. I'm the one who risked my skin for these eggs. Why shouldn't I just take them and sell them myself?}
{138}{}{I'll try to get more, then.}

{139}{}{Hey, careful with those! They're fragile!}
{140}{}{Okay, fine...}

{141}{}{[Evan carefully wraps the eggs and packs them in skins and reeds for protection] Okay, done. We can go back now.}
{142}{}{[Return to the settlement]}

{143}{}{[He frowns] I made all this way here not to quarrel with you at the last moment. I've been teaching, you, you've been learning. Consider this as a payment for my work.}
{144}{}{Fuck you, old man. These eggs are mine!}
{145}{}{That's fair. Take them.}

{146}{}{You - !! [he grits his teeth] Keep the damn eggs. I don't want to see your face again!}
{147}{}{The feeling's mutual. Get your ass out of here.}
{148}{}{Hey, don't get upset, I'll walk peacefully...}
{149}{}{The hunt is over.}

{150}{}{You left Evan in the middle of the hunt. This won't be good for your reputation in Gerlach.}
{151}{}{[He looks at you thoughtfully] ...you know, you did a damn good job today. I think you've earned a reward. [he counts out ten eggs, then hands you the rest] Remember, they'll pay a lot more for these in Reno, than you can get here.}
{152}{}{How many eggs should I bring?}
{153}{}{At least ten. No less!}

#Женские реплики
{1125}{}{I got the eggs. Are these enough?}
{1128}{}{Show me.}
{1137}{}{Wait, hold on. I'm the one who risked my skin for these eggs. Why shouldn't I just take them and sell them myself?}
