{100}{}{You see Evan.}
{101}{}{You see Evan, a hardened gecko hunter.}
{102}{}{Not now!}
{103}{}{Go back to the village. I'll catch up.}

########################################################
#
#                Первые реплики диалога
#
########################################################

{110}{}{Hi, stranger! Always nice to see a new face around here. If it's not hostile, that is.}
{111}{}{Want to chat?}

{112}{}{Excuse me, but who are you?}
{113}{}{I want to ask you about this settlement.}
{114}{}{I want to ask you about hunting.}
{115}{}{I have an ammunition press.}
{116}{}{Will you make some ammo for me?}
{117}{}{Will you make some ammo for me?}
{118}{}{Do you know anything about modifying weapons?}
{119}{}{Bye.}

{120}{}{Usually, it's the one who starts the conversation that introduces themselves.}
{121}{}{Really? Is some hillbilly giving me etiquette lessons now?}
{122}{}{Nah, *you* are going to be the one telling the name first.}
{123}{}{Oh, I'm sorry. My name is }
{124}{}{.}
{125}{}{If you're going to be that way, then fine, I'll leave.}

{126}{}{Oh, so you are the one who jumps to conclusions right off the bat, yeah? You don't know my story, yet you call me "hillbilly". So childish... Now, are you going to tell me your name, or are we going to be stubborn about it?}
{127}{}{Oh, I am, am I? Don't be so sure about that. [he crosses his arms and looks at you silently]}
{128}{}{I'm sorry, I didn't mean to offend you. My name is }
{129}{}{. Can we put this behind us?}

{130}{}{Good to meetcha! The name's Evan, the local gecko hunter. [he extends his hand to you] Now let's ditch the formalities and just talk like pals.}
{131}{}{That's better. Okay, all forgiven. I'm Evan, the local gecko hunter. [he extends his hand to you] Now let's ditch the formalities and just talk like pals.}
{132}{}{[Shake his hand]}
{133}{}{I'm not shaking hands!}

{134}{}{It seems you came from some shady place, full of thieves. Well, have it your way. But things work differently here. Sooner or later, you'll have to accept that or leave.}
{135}{}{We'll see.}

########################################################
#
#                Вопросы о поселении
#
########################################################

{140}{}{This isn't just a settlement, it's a family. Gerlach's from Reno, but we've got people here from all over Nevada.}

{141}{}{Who is Gerlach?}
{142}{}{How do you feel about relocating ?}
{143}{}{How do you feel about the executions?}
{144}{}{Why did they want to execute that guy?}
{145}{}{What's wrong with the pump?}
{146}{}{Right, let's talk about something else.}
{147}{}{That'll be enough, see you.}
{150}{}{Tell me again about this community.}

{151}{}{Gerlach is in charge here, kind of a spiritual leader. He is also the founder of this place. He lives in the house across the street.}
{152}{}{I'm good with the kind of life I live. I sleep where I want and I do what I want. But I'm starting to feel my years. I'm thinking of finding someplace safer to settle down.}
{153}{}{Gerlach knows a thing or two about organizing people - he was a caravan guard for years, should have seen a lot of different communities, so I trust him. Still...sometimes, you know, I can't help feeling like he's hiding something.}
{154}{}{For being irresponsible and failing at his job. He was supposed to watch the water pump, but he fell asleep and now it's not working. I feel for him, but he put the whole community at risk. We can't survive without water.}
{155}{}{I think something burned out? I'm not a machine guy. If you've got a replacement, we'd be awfully grateful!}
{156}{}{Gerlach was the leader and founder of this place.}

{157}{}{Why didn't you go with everyone else?}
{158}{}{It turns out these old bones aren't ready to settle down yet. Thanks for the offer, but it's not for me.}
{159}{}{Well, it's up to you.}

########################################################
#
#       Апгрейды и починка оружия
#
########################################################

{160}{}{I've fixed up some hunting weapons in my time. Shotguns, mostly.}
{161}{}{Can you saw off this double shotgun?}
{162}{}{}
{163}{}{}
{164}{}{Let's get back to the other questions.}
{165}{}{Another time.}
{166}{}{This "Savage" has to be reloaded after each shot. Can you do something with it?}

{170}{}{For you? Pro bono. [he winks at you] Your money's no good here.}
{171}{}{I could do that. Give me, oh...120 bucks for my time, and I'll get it done.}
{172}{}{Sure, but not for free. Water's valuable right now. I'll do it for three bottles.}
{173}{}{Sure, but not for free. Water's valuable right now. I'll do it for two bottles.}

{174}{}{Let's talk about another weapon.}

{176}{}{Here's the weapon. Let's go!}
{177}{}{Here's 120 bucks and the weapon. Let's go!}
{178}{}{Here are three flasks of water and the weapon. Let's go!}
{179}{}{Here are two flasks of water and the weapon. Let's go!}

{181}{}{[After one hour he returns with the weapon] Here you go, my man. Have fun!}
{182}{}{Thanks.}

{183}{}{Yes, I can do that.}
{184}{}{Hmm. I can put a bandolier on the rifle butt. Seen other hunters doing that. I even have some gecko leather for it.}

{187}{}{Let me ask you something else.}
{188}{}{No, not now.}
{189}{}{Oh, no, that won't work.}
{190}{}{Is something missing?}

########################################################
#
#                Про охо'у
#
########################################################

{199}{}{Well, I can talk about hunting for hours... But not with you.}
{200}{}{Well, I can talk about hunting for hours.}
{201}{}{Can I hunt with you?}
{202}{}{Tell me about geckos.}
{203}{}{You said something about gecko pelts?}
{204}{}{Where do you get your hunting supplies?}
{205}{}{How far have you traveled in the Wasteland?}
{206}{}{Not now.}
{207}{}{One more question.}
{208}{}{That's enough.}
{209}{}{Reno? Two weeks on foot, straight south. Following the highways is faster, but dangerous. If you really want to know, ask someone who came from there.}
{210}{}{Mutant lizards. From what I've seen, they come in silver and gold. The silver ones are short and kind of twitchy, but easy enough to handle. The golden ones are more of a challenge - they're bigger, tougher, and have jaws that'll bite through your hand like... [he thinks] ...like a knife through brahmin shit! But you get more meat for your trouble, and traders pay top dollar for their pelts.}
{211}{}{Gecko pelts make for good leather, but you need a special touch to get it off them. If you don't know how, you'll just ruin the hide and waste your time.}
{212}{}{Can you teach me?}
{213}{}{Sure! I'll teach you everything I know. A traveler like you should find it handy.}
{214}{}{Teach me, oh great trapper!}
{215}{}{Not now. First, let's talk about something else.}
{216}{}{Maybe later, I'm busy. I'll see you around.}
{217}{}{Evan taught you how to properly skin geckos.}
{218}{}{I'm not popular here as it is, but you're even less. I can't be seen helping you out.}
{219}{}{Oh shit, do they hate me that much? Well, can you at least answer some more questions?}
{220}{}{I could, but I don't want to waste my time on some greenhorn. You need to be patient and have an eye for detail. We've never hunted together, so I don't know if you've got the right stuff.}
{221}{}{Too bad.}
{222}{}{I trade my meat and pelts for supplies in Black Rock, but they never have enough ammo and I'm getting too old to use my spear. Years back, I used to hand-press my own ammunition, but I don't have the equipment for that anymore.}
{223}{}{I could, but I don't know if you have what it takes. Sorry, but that hunt in the canyon wasn't enough to tell if you have the right stuff or not.}
{224}{}{}
{225}{}{I'm no explorer, but I've climbed just about every mountain north of Reno. Besides us, you've got New Reno, Black Rock, and the savages in Lovelock. If you're going to travel, be careful on the highways. There's always someone waiting to jump you. I stay off the roads if I can help it, or go along with a caravan if I can't.}
{226}{}{Where is New Reno?}
{227}{}{Where is Lovelock?}
{228}{}{Where is Black Rock?}
{229}{}{You're not from around here, huh? That's okay, I'll show you. [he points out its location on your map]}
{230}{}{Thanks, but I want to ask you about hunting.}
{231}{}{Thanks, I think that's all I needed.}

########################################################
#
#                Квес' - поиск посыльного
#
########################################################

{290}{}{I'm looking for Milo. Do you know where he is?}
{291}{}{Milo? I haven't seen him since he took my pelts to William in Black Rock. Are you sure he's not still there?}
{292}{}{Why would William need your pelts?}
{293}{}{I've got the best pelts around. William thinks he can trade them to caravan merchants going between Reno and Salt Lake City. It's a pipe dream, if you ask me, but good luck to him.}
{294}{}{Did Milo say anything before he left?}
{295}{}{Hmm... I can't remember anything in particular. Have you talked to his wife yet?}
{296}{}{Would anyone want Milo to disappear?}
{297}{}{Not really, he's just a courier. Maybe he just got drunk. Or, in the worst case, eaten by geckos.}

########################################################
#
#                Учас'ие в охо'е
#
########################################################

#Охо'а  - первый разговор
{300}{}{You, with me? Hmm... I *could* use some help, but I think you'd just get in the way. No offense, but I need someone who knows a thing or two about hunting and surviving.}
{301}{}{You, with me? No offense, but you're just some stranger. How do I know this isn't a trap? We'll be all alone out there, and I didn't get this old by being careless.}
{302}{}{You, with me? Hmm... I *could* use some help. I'm getting too old to run around to run around with a spear and do everything myself. An extra pair of hands is just what I need right now.}
{303}{}{I'm ready to start. What are the details?}
{304}{}{I'll keep that in mind. I have some other questions first.}

{305}{}{New Reno wants some gecko eggs. I get a good price for them because I'm the only one who can get them out of a nest without a fight.}
{306}{}{Without a fight? It can't be that hard to kill a bunch of geckos.}
{307}{}{Ha! Rookie mistake. We need that gecko meat to survive around here. If we kill them all now, we'll starve later. We need to leave enough geckos alive for the nest to recover and give us more meat and eggs next season.}
{308}{}{I see. How do we get the eggs out of the nest without killing anything?}

{309}{}{First, I'm going to teach you how to set traps and not get noticed. You'd better pay attention, because I don't need an assistant that can't follow instructions. Clear?}
{310}{}{Clear. I promise I'll pay attention.}
{311}{}{No thanks. That's not my style.}
{312}{}{Great. I'll give you the details when we get there. But you'll have to leave your stuff here, including your weapons. You'll get everything back when we're done.}
{313}{}{We're going hunting unarmed?!}
{314}{}{Damn right. You won't learn anything if you just shoot them all. One day that gun will jam or your ammo will run out, and on that day, you'd better be able to get by with the basics. A hunter has to know how to prepare for the worst, only carry what he needs, and always leave enough for the nest to survive. Do you see what I'm getting at?}
{315}{}{I understand, master! I'm ready to hunt.}
{316}{}{I'll come back when I'm ready.}

{317}{}{I'm ready to go on the hunt.}

{318}{}{Where do all these geckos come from, anyway?}
{319}{}{They're all over California and Nevada, but I've heard they tend to pop up around radiation. We probably owe all the geckos around here to the nuclear power plant to the north. At least, I've been told it's a nuclear power plant - I've never been crazy enough to go up and check. Even I don't want to deal with *that* many geckos, and even if I did, I'd rather not puke my guts out and die of radiation poisoning.}

#Охо'а - в'орой разговор
{320}{}{That wasn't the real hunt, was it?}
{321}{}{No. The last hunt showed that you know how to avoid a few lizards. Now you're going to have to avoid a whole lot of them.}
{322}{}{Sounds serious. What's the plan?}
{323}{}{I don't like the sound of that. Maybe later.}

{324}{}{Ah, now this is the part I'm getting a bit old for. I'll tell you more when we get there. And remember, we absolutely can't afford to wipe out the nest.}
{325}{}{Let me guess - I'll leave my weapons behind again?}
{326}{}{This time, I'll give you my spear. A gun would be too noisy, and anyway, I don't want you to be tempted to wipe them all out.}
{327}{}{I'm ready. Let's do this!}
{328}{}{I have to take care of some things first. I'll see you later.}

{329}{}{We're here. Beautiful canyon, isn't it? [he looks around and breathes deeply] Okay, let's focus. I laid some bait in those rocks. Take these traps and set them in the passages, where the geckos will have to pass to get to the bait. When you're ready, blow this whistle and they'll come running. Did you get all that?}
{330}{}{Got it.}
{331}{}{Great. One more thing - I'm teaching you this way for a reason. Follow my instructions, or this is the last time we go hunting together.}
{332}{}{Fine.}

{333}{}{How's it going? My bait's still there, isn't it?}
{334}{}{I think I've managed to trap all them all.}
{335}{}{Tell me again what I have to do.}
{336}{}{I'm still planning. I'll go set the traps...}

{337}{}{Did you forget already? Set the traps in a passage where the geckos will have to pass, then call them with the whistle. It's that simple!}
{338}{}{Let's see...}
{339}{}{[Follow the master]}
{340}{}{Hey, you're a natural! You got them all! Alright, head back to the village while I take care of the skins. Next time, it's the real deal. Oh, and keep the whistle. I have a spare.}
{341}{}{Okay, I'll see you back in the village.}
{342}{}{What the hell is this? You were supposed to use the traps! Did you even listen to a thing I said? [he sighs] Look, this isn't going to work. You can keep the whistle, but we're not doing this again. Get out of here.}
{343}{}{I already told you, I'm not hunting with you again.}
{344}{}{If you don't want to, then so be it. I'm out of here.}
{345}{}{To be honest, I'm not good with traps. Can you teach me how to use them?}
{346}{}{Right this second? Fine, but I hope the pack doesn't leave while I give you the basics. Listen up...}
{347}{}{[Next]}
{348}{}{Now? No, this isn't the time. Just figure it out.}
{349}{}{Master Evan raised your traps skill by 5%.}
{351}{}{You run off in the middle of a hunt, and now you show up like nothing ever happened? I don't know how they do it where you come from, but that doesn't work around here. Don't expect me to take you hunting again.}
{352}{}{Hey, you missed one. Well, that's okay, it's your first time. The next hunt will be more serious. You go back to the village while I harvest these skins. And keep the whistle, I have a spare.}
{353}{}{You left the hunting ground in the middle of the hunt. Somehow you think this isn't what Evan had in mind.}

{354}{}{Well, well, here comes our lost hunter. Did you lose your nerve or what? We don't like people that can't keep their word around here. Don't expect any warm welcomes.}
{355}{}{I can't argue with that...}
{356}{}{You've got a lot of goddamn nerve coming back here after what you did. I'll be the better man and deal with you, but you can forget about any more freebies. You got that?}
{357}{}{Fine, whatever...}

{358}{}{So... How do I set a trap?}
{359}{}{Use it on yourself. Ha! Old hunter's joke. It'll be placed in front of you, so remember to face the right direction when you do it. And if you get the chance, try to pick up and reuse any traps you can.}

{360}{}{I'm itching for another hunt. What do you think?}
{361}{}{I've got all the skins and meat I need for now. But if you're that antsy, I have heard of something...}
{362}{}{What is it?}
{363}{}{Trappers from the north-east have told me there's the granddaddy of all radscorpions up there. It's ten times the size of your average radscorpion and its shell is so thick that spears can't pierce it. I don't know if it's true, but you can try your luck. Might make a good story if you can kill it.}
{364}{}{Just what I wanted to hear! I'll find and kill that monster. It won't get away from me!}
{365}{}{A legendary scorpion, huh? I'll keep it in mind, but I have more important things right now.}
{366}{}{Hey, that's the spirit! You remind me of myself when I was younger. Just be careful.}
{367}{}{Thanks. Any tips?}
{368}{}{You'll need something with some punch... Like a machine gun, heh. Traps won't cut it, that's for sure. If you can, try to aim for something vital instead of pounding at its shell. I don't care how big it is, a broken leg will still ruin its day. It might be hard to get through its shell with blunt attacks, but energy will go right through it. I think one of the Black Rock residents has a plasma pistol. Ask William about it.}
{369}{}{Anything else?}
{370}{}{Take some antidote with you. Usually, a radscorpion's poison gets weaker as it ages, but a sting from something this size will still kill you. Here, take some from my personal inventory.}
{371}{}{That will come in handy. Where is this scorpion?}
{372}{}{They said it was somewhere to the north-east. I'll mark the area on your map. Good luck!}
{373}{}{Thanks! When I get some free time, I'll go find it. I'll be seeing you around, Evan!}

########################################################
#
#                Скорпион Легенда
#
########################################################
{400}{}{I hunted down the legendary scorpion!}
{401}{}{Well, anyone can talk. Do you have any proof of your words?}
{402}{}{Here, look at this carapace, it belonged to the beast. I ripped it off its corpse with my own hands.}
{403}{}{Here, look at this armor, I made it myself from the scorpion's carapace.}
{404}{}{You can not believe me if you want, but I sure know I killed it.}
{405}{}{That's great! Congratulations, now you are a real hunter. You have my deepest respect.}
{406}{}{Thanks Evan, this means a lot to me.}
{407}{}{Maybe you can become one too, if you'll practice enough.}
{408}{}{You get 100 experience points.}

#Female character
{1134}{}{Trust issues, huh? Oh well, have it your way. But things work differently here. Sooner or later, you'll have to accept that or leave.}
{1181}{}{[After one hour he returns with the weapon] Your weapon, madam. Enjoy!}
{1229}{}{You're not from around here, huh? That's okay, I'll show you. [he points out its location on your map]}
{1302}{}{You, with me? Hmm... I *could* use some help. I'm getting too old to run around to run around with a spear and do everything myself. An extra pair of hands is just what I need right now.}
{1310}{}{Clear. I promise I'll pay attention.}
{1315}{}{I understand, master! I'm ready to hunt.}
{1342}{}{hat the hell is this? You were supposed to use the traps! Did you even listen to a thing I said? [he sighs] Look, this isn't going to work. You can keep the whistle, but we're not doing this again. Get out of here.}
{1345}{}{To be honest, I'm not good with traps. Can you teach me how to use them?}
{1354}{}{Well, well, here comes our lost hunter. Did you lose your nerve or what? We don't like people that can't keep their word around here. Don't expect any warm welcomes.}
{1356}{}{You've got a lot of goddamn nerve coming back here after what you did. I'll be the better man and deal with you, but you can forget about any more freebies. You got that?}
{1373}{}{Thanks! When I get some free time, I'll go find it. I'll be seeing you around, Evan!}

{4400}{}{I hunted down the legendary scorpion!}
{4402}{}{Here, look at this carapace, it belonged to the beast. I ripped it off its corpse with my own hands.}
{4403}{}{Here, look at this armor, I made it myself from the scorpion's carapace.}
{4404}{}{You can not believe me if you want, but I sure know I killed it.}
{4405}{}{That's great! Congratulations, now you are a real huntress. You have my deepest respect.}
