{100}{}{You see a water pump.}
{101}{}{The pump is currently filling the tank with water from underground.}
{102}{}{The pump is not working. It seems to be broken.}

{103}{}{The pump is working.}
{104}{}{The pump is fine now.}
{105}{}{The fuse is blown.}
{106}{}{The fuse must be replaced.}

{107}{}{The pump can't get any more repaired.}
{108}{}{Useless.}
{109}{}{This won't help. The fuse is blown and must be replaced.}
{110}{}{It needs a new fuse.}
{111}{}{You replace the fuse and start up the pump. Over the rumble of the machinery, you can hear water sloshing in the tank.}
{112}{}{Done.}

{113}{}{Looking through the junk, you find a thin wire and carefully solder it into place, replacing the fuse.}
{114}{}{You lack the mechanical knowledge to figure out what's wrong with the pump.}
{115}{}{I can't.}

{116}{}{Not that.}

{117}{}{The pump is working normally... Until the next time it breaks.}
{118}{}{The pump is working.}
{119}{}{The fuse is blown. The pump won't work without it.}
{120}{}{The fuse must be replaced.}
{121}{}{That won't help you figure this problem out.}
{122}{}{I don't understand.}

{123}{}{You fixed the pump. Too bad no one needs it anymore.}
{124}{}{This pump is in working order, but hasn't been used for some time.}

{125}{}{There's nowhere to pour the poison here.}
{126}{}{Useless.}
{127}{}{This is a water pump. It seems to be in decent condition, but isn't working.}
