{100}{}{You see a pile of ordinary looking rocks. The pile itself, however, looks unusual, as if someone arranged it by hand.}
{101}{}{You'll need a shovel to clear this pile of rocks.}
{102}{}{I need a shovel.}
{103}{}{Just an ordinary pile of rocks. There's hardly anything useful in it.}
{104}{}{There's nothing here.}
{105}{}{These rocks are just minding their own business. You have no reason to push them around.}
{106}{}{What is the point?}
{107}{}{This is pointless.}
{108}{}{Now that’s a find!}
{109}{}{You find a very cleverly hidden stash of valuables.}
{110}{}{This isn't necessary.}
{111}{}{Blowing the rocks to gravel won't do you any good.}
{112}{}{This doesn't make sense.}