{100}{}{}
{101}{}{This is a personal letter! You need permission to read it.}
{102}{}{You cannot read this in combat.}

{103}{}{On the table you see a pencil and a letter with a trembling hand. It is addressed to Milo.}
{104}{}{[Read the letter.]}
{105}{}{[Leave.]}

{106}{}{"Forgive me, Milo, I couldn't wait any longer. I had to leave this place. Ask Gerlach about what happened. I'm sorry."}
{107}{}{There's a note addressed to travelers here.}
{108}{}{Leave.}
{109}{}{"If you're reading this, please give this letter to Milo. He's 32 years old, has brown hair and is very tanned. He wears leather boots with a knife sheath and a star on the sole. He went to Black Rock and never came back. If you meet him, please, bring him back home!"}
{110}{}{Well, at least it's a clue...}
{111}{}{With this description it'll be easier to find Milo.}
{112}{}{On the table you see a pencil and some old paper. Nothing interesting.}
{113}{}{"Forgive me, Milo, I couldn't bear to wait any longer. I am going to look for you by myself. I will come back every five days for food, if I won't - I am dead. I would rather die in the wastes than live without you."}
