{100}{}{You see a water tank.}
{101}{}{You see a water tank. There's a rumbling echo coming from inside. Apparently it's not full.}
{102}{}{You see a water tank. It has plenty of water, but judging from the smell, the water is not suitable for drinking.}
{103}{}{It looks like this basement was built to contain only one person.}
{104}{}{This village is deserted. Now only the desert wind wanders here.}
{105}{}{You see a tank. You hear the splashing sound of water inside.}
{106}{}{There's no point. The water is already poisoned.}
{107}{}{The water is already poisoned.}
{108}{}{This should be enough for the whole settlement. Come back later to see the results.}
{109}{}{The water is poisoned.}
{110}{}{Why do you need it?}