{100}{}{You see Derry.}
{101}{}{You see Bruce Derry, the leader of the bikers.}
{102}{}{Your report on the Hawthorne situation caused quite a stir. Apparently, the bikers will soon leave Bridgeport, to the delight of the rednecks.}
{103}{}{Piss off.}
{104}{}{Hello.}

{110}{}{What is it?}
{111}{}{Nothing.}

{112}{}{I'm looking for Jay Kukish.}
{113}{}{You won’t find him here. I think he's already in Hawthorne.}
{114}{}{Why are you telling me that so easily?}
{115}{}{Because our gang has a special relationship with Jay. He's always been a lone wolf, on his own. If you have business with him, go ahead, feel free to catch up with him. As for me, I'm more worried about what we're all going to do now. He's made some fuss at Hawthorne, and we've responded to his call and gathered here, and now we're idle.}
{116}{}{So, you're waiting for a message from Hawthorne?}
{117}{}{Why did Jay need to go to Hawthorne?}
{118}{}{The garrison in Hawthorne got jacked - its automatic defense systems no longer work. You might want to pay a visit there.}
{119}{}{Tell me about yourself. How did you join a biker gang?}
{120}{}{Tell me about your gang.}
{121}{}{Bye.}

{122}{}{Well, yeah. We could smell something's changing. Jay was spreading rumors that we'd better stay close to Hawthorne, that something was going to happen there. So we got together in Bridgeport - given that it was dangerous to stay in Hawthorne itself.}
{123}{}{Jay became interested in a governmental vault. According to him, it is located somewhere in Nevada. He wanted to look for the coordinates on a military base.}
{124}{}{Oh really? Jay haven’t contacted us yet. We've been waiting for this news for quite a long time. Also, frankly speaking, the rednecks around here are starting to get on our nerves. We'll move to the base as soon as everybody's ready.}
{125}{}{I am a veteran of the New Reno Civil War. Back then local businessmen used to involve bikers in their shady deals. We were mercenaries, a strike force, until the situation got to the point where we were no longer needed. Turns out, we were just being used. So we decided to spit in the face of the whole town. I wanted to be free.}
{126}{}{We are the people who couldn't find their place in modern society. Look at Bigfoot - he's a veteran from Wind of War. When he realized that the local military was worse than the raiders, he left to live by his own principles. And there's Whiner - his settlement has been destroyed by raiders. He had no choice, but to seek revenge. Our gang helped him and gave him a new purpose in life.}
