{100}{}{You see a farmer.}
{101}{}{You see a respected resident of Bridgeport, the head of a family.}
{102}{}{My son is dead... This means war! From now on, any biker I see is a dead man.}
{103}{}{Just give me a reason!}
{104}{}{Hello.}

{110}{}{Stop right there! Who are you? If you're one of the bikers, then get the fuck out! This is my house and I'm not going to share it, you freeloader scum!}
{111}{}{Calm down. I'm not a biker, I'm just a traveler.}
{112}{}{[Skeptically looking at you] Is that so? Fine, we can talk for now. Just watch yourself, or you're gonna be running away from here like a bitten brahmin.}
{113}{}{Okay, okay.}
{114}{}{Well? What is it?}
{115}{}{Nothing, I just didn't have anyone to talk to. Bye.}

{116}{}{Tell me about bikers.}
{117}{}{Why do you hate bikers so much?}
{118}{}{I'm interested to know, how do you survive in this wilderness?}
{119}{}{They didn't come here in such large numbers before. We never had a problem with them. And now they just come here in packs. I can't figure out what brings them here. And it doesn't matter - I just want them to go away. My wife and I can't even sleep at night with them outside.}
{120}{}{Why should I like them? I'm working my ass off to feed my family. And these marauders just got themselves some shiny motorcycles and guns, and now they're acting all tough. I would like to see them try to stay here and work on crops for a few years! Of course, this is not my main issue with them. They can live their life as they please, I just want them to stay away from me. And away from Bridgeport.}
{121}{}{As you can see, we work all day long. Only constant work helps us forget about our problems. It's really interesting how we live here, but ask someone else, I'm not in the mood. My neighbour loves to run his mouth, for example.}
{122}{}{I think that's enough talk for today. I have to go, see you.}

{123}{}{Bikers are my family now, so watch your mouth, daddy-o, before you get punched in the face.}
{124}{}{So that's how it is! You fucking brat, go wipe the breast milk off your lips! Just give me a reason and I'll blow your brains out.}
{125}{}{Hey now, take a breath. If I wanted to fight, then I'd start shooting without warning, don't you doubt it.}

{126}{}{And that guy at the entrance with the working hands - is he a biker, too?}
{127}{}{Looks like your son is going to do all it takes to become a biker.}
{128}{}{Some might have been happy. Your son was glad to leave this place with the bikers.}
{129}{}{[Through gritted teeth] My son is a fool! He is too naive, he doesn't understand what he's getting into. How I raised him to end up like this...}
{130}{}{It will be hard to change his mind.}
{131}{}{He just doesn't understand it yet. Having your own place - what could be better? He decided to trade his family for the highway. Stupid fool... By the time he realizes it's a waste of his life, it'll be too late. He needs to get some sense knocked into him before that scum takes him out of the house. Can you help?}
{132}{}{I don't know... How do I do that?}
{133}{}{I have no idea. Maybe you need to humiliate the bikers in his eyes. Find something against them, show that it's dangerous to deal with them. It would be even better if they were all dead. But that's too big a risk. The only hope I have is that the bikers will leave without letting him join their ranks. Can you help make that happen?}
{134}{}{Okay, I'll try to get rid of bikers and save your son.}
{135}{}{Thanks. We need all the help we can get.}
{136}{}{[Leave]}
{137}{}{Sorry, but I won't get involved in a family matter. If the guy wants to be a biker, it's his choice. Bye.}
{138}{}{Dante left with the bikers. It was impossible to stop him.}
{139}{}{I know. I won't wait for him to come back. It was his biggest mistake. If only I could have stopped him... If only...}
{140}{}{[Leave]}
{141}{}{Now, with the bikers gone, your son won't go anywhere.}
{142}{}{Most importantly, the bikers showed themselves to be weak; they couldn't even deal with us. This will serve as a good lesson for my son. Especially after I beat the crap out of him.}
{143}{}{Great. Well, I will leave you two alone then.}
{144}{}{I managed to convince Dante to stay home.}
{145}{}{Unbelievable! He used to be convinced only by hitting him on the back with a stick, and you managed to do it with words? How unexpected. I hope he's learned his lesson. Thank you for your help. Consider yourself a guest in my house from now on.}
{146}{}{Thank you for getting rid of those two-wheeled gorillas. Sure, they might come back. But the most important thing is that they abandoned Dante and left him behind. This will be a good lesson. Especially after I beat the crap out of him.}
{147}{}{Well, I will leave you two alone then.}

{150}{}{I can help you get rid of the bikers.}
{151}{}{You? Alone? Against several well-armed bandits? It won't be that easy. [He squints in disbelief] Besides, why would you help us? We are not relatives or even neighbors, and we have nothing to pay. But, to think about it, you can loot many good stuff off their corpses.}
{152}{}{There can be other options, beside murder. I will have to think about this.}
{153}{}{Just as I promised, the bikers will no longer cause problems in Bridgeport.}
{154}{}{Thank you so much. It's nice to hear those words after all this. I hope you'll stay around for a little longer.}
{155}{}{}
{156}{}{Bye.}
