{100}{}{You see a farmer.}
{101}{}{You see a respected resident of Bridgeport, the head of a family.}
{102}{}{My son was killed... This means war! From now on, any biker I see is a deadman.}
{103}{}{Just give me a reason!}
{104}{}{Hello}

{110}{}{Stop there! Who are you? If you're one of the bikers, then get the fuck back outside! This is my house, and I'm not going to share it, you freeloader scum!}
{111}{}{Calm down. I'm not a biker, I'm just a traveler.}
{112}{}{[Skeptically looking] Is that so? Fine, you can stay here for now if you want. Just watch yourself - otherwise, you'll be running away from here like a bitten brahmin.}
{113}{}{Okay, okay.}
{114}{}{Well? What is it?}
{115}{}{Nothing, I just didn't have anyone to talk to. Bye.}

{116}{}{Tell me about the bikers.}
{117}{}{Why do you hate bikers so much?}
{118}{}{I'm interested, how do you survive in this wilderness?}
{119}{}{They never came here in large numbers before. We never had any problems with them. And now they just come here in packs. I can't understand what drives them here. And it doesn't matter - I just want them to leave. My wife and I can't even sleep at night with them outside.}
{120}{}{Why should I like them? I'm working my ass off to feed my family. And these marauders just got themselves some bikes and guns to play the tough guys. I would like to see them try to stay here and work on the crops for a few years! Although, of course, this is not my main gripe with them. They can live as they want to, I just want them to stay away from me and away from Bridgeport.}
{121}{}{As you can see - we work all day. Only constant work helps us forget about our problems. It is really interesting how we live here, but ask someone else, I'm not in the mood. My neighbour loves to run his mouth.}
{122}{}{Perhaps that's enough talk for today. I have to go, see you.}

{123}{}{Bikers are my family, so watch your mouth, daddy, before you get kicked in the face.}
{124}{}{So that's how it's going to be! You fucking brat, go wipe the breast milk from your lips! Just give me a reason - and I will blow your brains out.}
{125}{}{Hey now, take a breath. If I wanted to fight, then I'd start shooting without warning, don't you doubt it.}

{126}{}{And that guy at the entrance with working hands is a biker too?}
{127}{}{Looks like your son is going to do all it takes to become a biker.}
{128}{}{Some could only be glad. Your son was happy to leave this place with bikers.}
{129}{}{[Through gritted teeth] My son is a fool! He is too naive, he doesn't understand what he's getting into. How did I raise him for him to end up like this...}
{130}{}{It will be hard to change his mind.}
{131}{}{He just doesn't understands yet. Having your own home - what can be better? He decided to exchange his family for the highway. Dtupid fool... By the time he understands that this is a waste of his life, it will be too late. He needs to have some sense beaten into him, before that scum take him away from home. Can you help?}
{132}{}{I don't know... How do we do that?}
{133}{}{I have no idea. But I'm sure that we must humiliate the bikers in his eyes. Find something against them, show that dealing with them is dangerous. It would be even better if they all were dead. But it would be dangerous to risk it. Only one hope is left to me - that the bikers will leave, without letting him join their ranks. Can you help make that happen?}
{134}{}{Okay, I'll try to get rid of bikers and save your son.}
{135}{}{Thanks. Now we will need any help we can get.}
{136}{}{[Leave]}
{137}{}{Sorry, but I won't get involved in a family matter. If the guy wants to be a biker - it's his choice. Bye.}
{138}{}{Dante left with the bikers. It was impossible to stop him.}
{139}{}{I know. I won't wait for him to come back. It was his biggest mistake. If only I could have stopped him... If only...}
{140}{}{[Leave]}
{141}{}{Now, with the bikers gone, your son has nowhere to go.}
{142}{}{The most important thing is - the bikers proved themselves weak they could not even handle us. This will serve as a good lesson for my son. Especially after I beat the shit out of him.}
{143}{}{Great. Well, I will leave you two alone then.}
{144}{}{I managed to convince Dante to stay home.}
{145}{}{Unbelievable! Only a beating his back with a stick would convince him before, and you managed to do this with only words? How unexpected. I hope that he learned his lesson. Thank you for your help. Consider yourself a guest at my house from now on.}
{146}{}{Thank you for getting rid of those two-wheeled gorillas. Sure, they may come back. But the most important thing is - they abandoned Dante and left him behind. This will be a good lesson. Especially after I beat the shit out of him.}
{147}{}{Well, I will leave you two alone then.}

{150}{}{I can help get rid of the bikers.}
{151}{}{You? Alone, against several well-armed bandits - it would not be easy. [squinting in disbelief] And why would you help us? We are not relatives or even neighbors, and we have nothing to pay. But, to think about it, you can loot many good stuff off their corpses.}
{152}{}{There can be other options, beside murder. I will have to think about this.}
{153}{}{Just as I promised, the bikers will no longer cause problems in Bridgeport.}
{154}{}{Thank you so much. Nice to hear those words after all this. I hope you'll stay around for a little longer.}
{155}{}{}
{156}{}{Bye.}
