{100}{}{You see a farmer.}
{101}{}{You see a respected resident of Bridgeport, the head of a family.}
{102}{}{}
{103}{}{Another step, and you'll get a taste of my pitchfork!}
{104}{}{I am a peaceful farmer, I'm not going to talk to you like this. Put your weapon away!}

{110}{}{What do you want?}
{111}{}{Nothing, relax.}

{112}{}{I am interested in this village. Tell me the history of this place.}
{113}{}{Well, it's going to be a very short and boring story. Bridgeport was uninhabited since the war, until our families settled here about six years ago. We are all from Reno. We left the place when life there became very bad and the only solution was to move away. Then we came across this wonderful place and decided to stay.}
{114}{}{Go on.}
{115}{}{We repaired the houses, cultivated the crops, even bred our own stock - you know, just settled down. Honestly, it's a lot better than in Reno, although sometimes I miss the luxuries of the big city. For example, so far we have been unable to fully restore the electricity in Bridgeport, and sometimes we need medications. Also, our houses are deteriorating.}
{116}{}{If you want, I can bring you something from Reno.}
{117}{}{How do you manage to feed yourselves?}
{118}{}{It's pretty cold in here.}
{119}{}{Are you alone in these parts?}
{120}{}{This is interesting, but let's change the subject.}
{121}{}{Thanks, that will be enough.}

{130}{}{}
{131}{}{At first we lived on pre-war food stocks, which were well-preserved, thanks to the cold climate. It's all gone now, the local stores are looted. But in the meantime we learned to grow crops and breed brahmin. Sometimes Jacob brings something from the hunt. Everyone is contributing in any way they can.}
{132}{}{Yes, but fortunately we have brahmin hides. They provide better protection from the cold than pre-war clothes, even better than the skins of these giant lizards. Judging from old photographs, there were ski resorts here, with entire mountains completely covered with snow. The climate has probably changed a lot, because we have never seen such a large amount of snow in our lives. But, instead of the snow, we now have clean water that fills the lakes. There's even fish in there! In any case, the cold mountains are better than the hot deserts of Nevada.}
{133}{}{We rarely have travelers here. I have heard about a tribe of savages in the mountains to the south. If you are interested, talk to our prospector Jacob about it.}
{134}{}{}
{135}{}{You said something about problems with the electricity?}
{136}{}{You mentioned needing medications. Is someone sick in your community?}
{137}{}{If the community needs supplies, why don't you establish a trade route with other settlements?}
{138}{}{There is none. Jacob tried to run the generator to light the streets and houses, but so far no results.}
{139}{}{Maybe I can help?}
{140}{}{That would be great. Talk to Jacob about it.}
{141}{}{Okay.}
{142}{}{Let's talk about something else.}
{143}{}{That's not interesting. Bye.}
{144}{}{I'll talk to him later, tell me something else please.}

{145}{}{My daughter needs help. Are you a doctor? It would be a great help if you were a doctor, or at least had a standard first aid kit, to help with the fever.}
{146}{}{I have some medical experience. Will you allow me to examine the patient?}
{147}{}{You're in luck - I have a first aid kit.}
{148}{}{You're in luck - I have a doctor's bag.}
{149}{}{Sure, I'll be glad to help!}
{150}{}{I'll take a look later, for now tell me something else.}
{151}{}{I'll go do my job then.}
{152}{}{Thank you! It will help not only my daughter, but everyone. There's always some health issues around here.}
{153}{}{You're welcome.}
{154}{}{Your daughter is fine now.}
{155}{}{Thank you! You have brought joy to our house. We don't forget something like this around here.}
{156}{}{Take care.}
{157}{}{Don't you dare touching my daughter! I can feel something repulsive about you.}
{158}{}{Well, I do have a special relationship with children, you're right about that...}
{159}{}{}

{160}{}{I thought about it, but we are so far away from major settlements that we can't contact anyone to offer trade. Sometimes we really need it - for example, medicines and equipment are always appreciated.}
{161}{}{If I ever get to the big city I will convey your offer to the caravan merchants.}
{162}{}{That's not my kind of problem. Let's talk about something else.}
{163}{}{Not interested. Bye.}
{164}{}{That is a really good idea. I will make a list of things that we need. We can trade a small amount of food, clean water and hides. Tell that to the caravan merchants, please.}
{165}{}{Okay, but that's not everything I wanted to know about.}
{166}{}{No problem. I'll go right now.}
{167}{}{Regarding the patient - here's a first aid kit, treat her yourself.}
{168}{}{Regarding the patient - here is a doctor's bag, treat her yourself.}
{169}{}{}

{170}{}{You were talking about the lack of urban comforts. Is your child in need of something here?}
{171}{}{Here, take a Nuka-Cola for your daughter. It's a gift.}
{172}{}{We provide her with everything she needs, but... Before we moved out of Reno, she used to like Nuka-Cola. But local stocks ran out a long time ago, and there is nowhere to get more.}
{173}{}{Bringing a tenth Nuka-Cola bottle, you have earned a better reputation from local residents.}
{174}{}{A gift? Well, thanks. Such care for children is a rare thing these days.}
{175}{}{You are always welcome.}
{176}{}{We don't need anything from you. You better get out of here, while you are still breathing.}
{177}{}{Perhaps you guessed my special relationship with children...}
{178}{}{Apparently, the locals have low opinion of me...}

{180}{}{What is it? Did you manage to repair the power grid? Terrific! Thank you so much. Now life here will be much easier, especially in the cold winter. Here, take some fruit from the plate, help yourself. As soon we get electric oven going, the first thing I'll ask my wife is to cook an apple pie.}
{181}{}{You are always welcome.}

{182}{}{What is that smell?}
{183}{}{As I said, my wife cooked an apple pie. You deserve a little, for your good deeds.}
{184}{}{Thanks.}

{190}{}{Tell me about the bikers.}
{191}{}{We didn't call them here. In the past bikers sometimes came to us, but never so many. They seem somewhat anxious, as if they are waiting for something. I don't know what. But our family is already tired of these guys. It would be better for us all if they'd just leave.}
{192}{}{Okay.}
