{100}{}{You see Dante.}
{101}{}{You see a young inhabitant of Bridgeport. Although he tries to imitate the bikers, he still looks like a farmer.}
{102}{}{}
{103}{}{Wanna fight? I'll show you!.. I mean, WE will show you!}
{104}{}{Damn! They left! WITHOUT ME! And I had such high hopes...}
{105}{}{They're all dead... But... How? I thought, they were the toughest!}
{106}{}{I'm staying. Perhaps, I will have to leave some day. But for now... I'm staying.}

{110}{}{}
{111}{}{Hello.}
{112}{}{And who are you? You're not a biker, right? If not, then we have nothing to talk about. And tell my dad, that I'm in a gang now.}
{113}{}{You're tired of being a farmer?}
{114}{}{That's right! I've hated this shithole for a long time. The fuck?! I can do better than that! Let my parents dig the dirt if they want, but I want to be free.}
{115}{}{[Next]}
{116}{}{Bikers became my idols when they first came here. They know so many things, so they have seen so much! When I'll join their ranks - that's when I'll be really happy.}
{117}{}{Okay. Well, good luck to you.}
{118}{}{You again? Don't mess with me, I'll become a BIKER soon! Yeah!}
{119}{}{Right, whatever you say.}

{120}{}{Wouldn't your parents disagree with that?}
{121}{}{What do you know about the bikers?}
{122}{}{How are you going to join bikers?}
{123}{}{Of course they would. But I won't ask them. Living here is boring. I want to be with the bikers.}
{124}{}{They will test me. Perhaps, it won't be easy.}
{125}{}{Not easy? But you're confident right?}
{126}{}{Yes... Damn it, I'm willing to die trying! Listen, Can you help me? There are two challenges I have to complete, and I may not be up to it. First is shooting a pistol. I don't even have one, not even talking about shooting skills. The second one is a fistfight. The chief said, that no one's gonna beat me to death, I just have to stay on my feet, while I'm being beaten. How will I get through the pain? This is not some game.}
{127}{}{Fine, I'll help you. It seems you have no choice other than to join the bikers. Okay, I will get you a pistol and some painkillers.}
{128}{}{I won't help you.}
{129}{}{Then get the fuck out of here! [hysterically] I'll manage without you! I can... I'm a man... I'm a man... [It seems this guy desperately wants to join the bikers.]}
{130}{}{[Leave]}
{131}{}{You will? Awesome. Just hurry before they leave. Otherwise I will be left alone, and I will have to wait until the next time they come.}
{132}{}{I'll keep that in mind. Especially if I had some personal incentive.}
{133}{}{Hi. Do you remember your promise to help me? Hurry the bikers could leave at any moment.}
{134}{}{[Hits his forehead] How could I! Of course! I know a place, where my dad keeps his cash. I don't know how much money there is, to be honest, I never asked - because I didn't need any money in this shithole. If you help me I'll tell you where the stash is.}
{135}{}{Great.}
{136}{}{I know enough, to make the decision to join the gang. The rest doesn't matter. Where they live, what they eat - what's the difference? What's more important, they don't belong to anyone and they do whatever they feel is right. Now that's a life!}
{137}{}{Hello.}

{140}{}{Let's talk about you joining the gang.}
{141}{}{They want to give me some tests. There are few, but I'm worried only about two. First is shooting a pistol. Second is a fistfight. The chief said, that no one's gonna beat me to death, I just have to stay on my feet, while I'm being beaten.}
{142}{}{This pistol will be just right for your test [give }
{143}{}{].}
{144}{}{Take a painkiller.}
{145}{}{Take a painkiller from this kit.}
{146}{}{Take a painkiller from this doctor bag.}
{147}{}{Take this gun [give 10mm pistol].}
{148}{}{Take this gun [give 10mm pistol with ext. mag].}
{149}{}{Take this gun [give 10mm pistol model ¹80].}
{150}{}{Take this gun [give 10mm pistol with a flashlight].}
{151}{}{Take this gun [give a premium 10mm pistol].}
{152}{}{I can't help right now.}

{153}{}{Wow! A real gun? Does it work? Superb! Now I have to learn how to use it. Can you teach me?}
{154}{}{Sure, I have enough experience to teach you.}
{155}{}{Honestly, my shooting skills are below average. You'll have to do it without me.}
{156}{}{No. You have the pistol, teach yourself.}
{157}{}{Fine, I'll ask that old prospector from the farm house. He shoots good and probably won't tell my dad about it. Thanks for the help.}
{158}{}{You're welcome.}
{159}{}{[Outside of the town, you set up a shooting range and teach boy the basics of shooting. He was a quick learner.] Awesome! Thanks for the help. Just don't tell my dad, he will lock me up and won't let me out, until the bikers are gone.}
{160}{}{Fine.}
{161}{}{Will this help with the pain? Great, just what I need! Thanks.}
{162}{}{You're welcome.}
{163}{}{Now I'm ready! I'll have to practice a little and then go to the chief. Thank you, this day will change my life you understand? Remember that stash I told you about.}
{164}{}{Yes, tell me.}

{165}{}{Your father does not want you to go with bikers.}
{166}{}{I did not ask him. To live in a hole like Bridgeport is not for me. I'm better off with bikers.}
{167}{}{I don't wanna know about it. I wouldn't steal from a farmer. Let's just leave that stash a secret.}
{168}{}{Okay, it's in the bathroom under the tub. You just have to move the planks from the floor.}
{169}{}{Under the tub? Great, I will check it out.}
{170}{}{You don't impress me. Fine, if you don't want it I won't make you.}
{171}{}{Good.}

{172}{}{You're making a mistake. You have a home and a family that needs you. The bikers are just a bunch of strangers.}
{173}{}{So? I'm sick of this place. You're telling me to just stay here? I'd rather die!}
{174}{}{Look at yourself. You have nothing in common with the bikers. Even if you pass all the tests, you won't be able to live like they do. Eventually, you'll become only a burden to them. Think about your family - not many have the luxury to live in a place like this.}
{175}{}{It seems I cant change your mind. I'll try some other time. Bye.}
{176}{}{I didn't think about that... I thought I would learn everything in my time. But you're right - am I like them? I won't pass the tests. And my home... As much as I don't want to rot here, I can see your point - this is the only place where I'm really needed... Man, I'm confused.}
{177}{}{Come back to your father and tell him you'll stay with him. It will be best for everyone.}
{178}{}{The thing is, you're not ready. So give me some time too, so I can answer.}
{179}{}{Okay. I'll do that.}
{180}{}{Great.}
