{100}{}{You see a farmer.}
{101}{}{You see a tanned resident of Bridgeport. Obviously, he spends the whole day watching brahmin.}
{102}{}{}
{103}{}{You should leave this town as fast as you can.}
{104}{}{Thanks for the help.}
{105}{}{Oh no, not this! How we'll survive without brahmin?!}
{106}{}{Well...}

{110}{}{Hey. What do you want?}
{111}{}{Tell me about the bikers.}
{112}{}{I will help gather the herd into the pen.}
{113}{}{So, you watch brahmin here?}
{114}{}{Tell me about this settlement.}
{115}{}{Bye.}

{116}{}{Hey, you're not one of these bikers right? If not, then get out of here as soon as possible! These friggin' bikers have made so much noise here, that my poor brahmin fled around the city. Now I can't drive them back to the corral...}
{117}{}{Are you still here? Better go away before these bikers begin to brawl.}
{118}{}{Ah, it's so peaceful without the bikers... That's how our little rural town should be. Wait, do you need something?}
{119}{}{Thanks for the help with the brahmin. If not for you I would have to chase them myself. They are unpredictable when scared.}

{120}{}{They came here from the north. At first one, then another - and now so many came, as if they planned this. I don't know what they have forgotten in our small settlement, but we don't want to ask. I hope they leave soon, they only make trouble.}
{121}{}{You can help? That's great. Remember - they are very stubborn when frightened, which will make it difficult to catch them.}
{122}{}{Yes, pretty much I do look after brahmin. But we have very few people, that's why everyone sometimes has to do a little of everything.}
{123}{}{Our lovely Bridgeport. When our families moved here from the clutches of war in Reno, there was no one here. Only the old dilapidated houses covered with sand and dirt. We worked long and hard to turn this place into a something more-or-less fit to live.}
{124}{}{You're welcome.}
