{100}{}{You see Jacob.}
{101}{}{You see a resident of Bridgeport. Judging by his appearance, he is not one of the local farmers.}
{102}{}{}
{103}{}{Get out of here before we break your legs.}

{110}{}{What do you want?}
{111}{}{You don't look like a farmer. Tell me about yourself.}
{112}{}{What do you think about the bikers?}
{113}{}{Enough about geography. Better tell me about bikers.}
{114}{}{Bye.}
{115}{}{Enough about bikers. Tell me about yourself. You don't look like a farmer.}
{116}{}{}
{117}{}{}
{118}{}{}
{119}{}{You don't look like a biker. If you just wandered in to rest, then you better pack up and leave. You don't want trouble with the bikers.}

{120}{}{No, I'm not a farmer. Sometimes, of course, I have to help with the harvest or at the slaughterhouse. But my main task is to dig through the ruins in search of anything useful. I'm also good with firearms and a little bit with mechanics. So, my skills are needed in Bridgeport.}
{121}{}{You've been to the different places in the vicinity, right? Anything interesting?}
{122}{}{Well, there are several places of interest - Uranium City, New Reno, Hawthorne. Surely you already know about them.}
{123}{}{Tell me about Uranium City.}
{124}{}{Tell me about Hawthorne.}
{125}{}{Besides the ruins and these cities, is there anything else noteworthy in these parts?}
{126}{}{An old mining town in the northwest. It was supported by one of the bosses in Reno, with the ore being used to fuel the power plant. But something bad happened there and now Uranium City is dying.}
{127}{}{It's a military base in the northeast. I once spent a lot of time rummaging through the old houses there. Dangerous place. It has always been a little dangerous due to the rodents and robots. Doubly dangerous now, because of the prospectors, who are ravaging the army reserves for more than a year now. There are always wars between different gangs marauding the place.}
{128}{}{In the south-east is a highway, but the nearest village in the direction is a long way off. Some particularly desperate caravans are trying to master this trade route and travel between Las Vegas and New Reno, but not many manage to survive the journey.}
{129}{}{What else?}
{130}{}{To the south and southwest of the mountains there is only desert. It's a harsh place. It's impossible to live there, let alone travel, nobody even tries anymore. I don't remember a single case of anyone ever making it from the south. Could there be any life beyond the desert? I doubt it.}
{131}{}{Between us and the desert in the south, there are some highlands. Sometimes I go there for hunting, but never far in the mountains - I do not want to meet the local tribe that lives there.}
{132}{}{Tell me about the tribe in the south.}
{133}{}{Those savages have almost forgotten how to speak. The entire tribe has probably been isolated  from the outside world since the days of the Great War. So, they have forced to inbreed with their relatives. I also know that they are cannibals. The shaking syndrome and gnawed human bones in the parking lots can prove that. How do I know? It happened. I saw it. A couple of times I even had to fight with them. They fight like animals, but what can they do with their clubs and spears against my rifle?}

{140}{}{I have nothing against their way of life, but they shouldn't impose their laws on ordinary people! We didn't call them here. When there was only a couple of bikers in Bridgeport, it did not create any problems, but now they are starting to push us. A little more - and our lovely town will quickly become a war zone.}
{141}{}{What do they want here?}
{142}{}{That's what I have no idea about. I have heard them talking and they seem to only have a vague idea themselves. They probably smelled trouble, they just don't know what.}
{143}{}{They say you're trying to fix the electricity in the city. How is it going so far?}
{144}{}{I lack the skills and time to deal with this issue. Why? You can help? Mind you, we have nothing to pay for your services.}
{145}{}{I just want to be helpful.}
{146}{}{Damn, if you have nothing then don't try and deal with me.}
{147}{}{Listen. In the garage across the street there is a backup generator. It's in working condition, but I was not able to establish the supply of electricity to houses. Apparently, I'm a bad electrician. How to fix it? I don't know. You have to look all over the town, check the switchboards, dig into the transformer, and deal with corrosion. If you're a good technician and smart enough, you'll fix it in no time.}
{148}{}{Isn't there a power station here?}
{149}{}{No. The power source is not here, Bridgeport gets its energy from somewhere on the power lines.}
{150}{}{I'll see what I can do.}
{151}{}{How much longer will the generator last, if we fix it?}
{152}{}{We have a little needs - light, heating, kitchen utilities. We would have enough stored energy to last our families at least ten years.}
{153}{}{I see you have managed to fix electricity! Thank you. You really helped us. I do not know how to repay you. Here, take this whiskey. I found it in an old house and kept in case of a holiday. But it is better to share it with a good person.}
{154}{}{Always welcome.}
