{100}{}{You see Jacob.}
{101}{}{You see a resident of Bridgeport. Judging by his appearance, he is not one of the local farmers.}
{102}{}{}
{103}{}{Get out of here before we break your legs.}

{110}{}{What do you want?}
{111}{}{You don't look like a farmer. Tell me about yourself.}
{112}{}{What do you think about the bikers?}
{113}{}{Enough about geography. Better tell me about bikers.}
{114}{}{Bye.}
{115}{}{Enough about bikers. Tell me about yourself. You don't look like a farmer.}
{116}{}{}
{117}{}{}
{118}{}{}
{119}{}{You don't look like a biker. If you just came in to rest, you'd better pack your things and leave. You don't want to get in trouble with those bikers.}

{120}{}{No, I'm not a farmer. Sure, sometimes I help with the harvest or at the slaughterhouse. But my main task is to dig through the ruins in search of anything useful. I'm also good with firearms, and a little bit with mechanics. So, my skills are needed in Bridgeport.}
{121}{}{You've been to the different places in the vicinity, right? Anything interesting around?}
{122}{}{Well, there are several places of interest - Uranium City, New Reno, Hawthorne. Surely you already know about them.}
{123}{}{Tell me about Uranium City.}
{124}{}{Tell me about Hawthorne.}
{125}{}{Besides the ruins and these cities, is there anything else noteworthy in these parts?}
{126}{}{An old mining town in the northwest. It was maintained by one of the bosses in Reno, and the ore was used to fuel the power plant. But something bad happened there, and now Uranium City is dying out.}
{127}{}{It's a military base in the northeast. I once spent a lot of time rummaging through the old houses there. Dangerous place. And it has always been, due to the rodents and robots, but now it's even more dangerous, because of the prospectors, who are ravaging the premises. There are always wars between different gangs marauding the place.}
{128}{}{There is a highway to the southeast, but the nearest village in that direction is very far away. Some particularly desperate caravans try to master this trade route and drive between Las Vegas and New Reno, but not many manage to survive the journey.}
{129}{}{What else?}
{130}{}{To the south and southwest of the mountains is only desert. It is a harsh place. It's impossible to live there, let alone travel. No one even tries. I don't remember a single instance of anyone making it from the south. Can there be anything beyond the desert? I doubt it.}
{131}{}{There are some highlands between us and the desert to the south. Sometimes I hunt there, but never far into the mountains - I don't want to meet the local tribe who inhabits that place.}
{132}{}{Tell me about that tribe in the south.}
{133}{}{These savages had almost forgotten how to speak. The whole tribe has probably been isolated from the outside world since the Great War, so they are forced to inbreed with their relatives. I also know that they are cannibals. The shaky body syndrome and the gnawed human bones in the parking lots are proof of that. How do I know? I've seen it. I even had to confront them a couple of times. They fight like animals, but what can they do with their clubs and spears against my rifle?}

{140}{}{I have nothing against their way of life, but they should not impose their laws on ordinary people! We didn't call them here. When there were only a few bikers in Bridgeport, it wasn't a problem, but now they're starting to pressure us. A bit more and our beautiful town will quickly become a war zone.}
{141}{}{What do they want here?}
{142}{}{No idea. I've heard them talk, but they seem to have only a vague idea themselves. Perhaps they have smelled trouble, they just don't know what it is.}
{143}{}{They say you're trying to fix the electricity in the city. How is it going so far?}
{144}{}{I lack the skills and time to deal with this issue. Why? Wanna help? Mind you, we have nothing to pay for your services.}
{145}{}{I just want to be helpful.}
{146}{}{Damn, if you have nothing to pay with, then no deal.}
{147}{}{Listen. There is a backup generator in the garage across the street. It's working, but I haven't been able to get power to the houses. Apparently, I'm a bad electrician. How do you fix it? I don't know. You have to look all over town, check switchboards, dig into the transformer, deal with corrosion. If you're a good technician and smart enough, you'll fix it in no time.}
{148}{}{Isn't there a power station here?}
{149}{}{No. The power source is not here, Bridgeport gets its power from somewhere else through the power lines.}
{150}{}{I'll see what I can do.}
{151}{}{How much longer will the generator last, if we fix it?}
{152}{}{We have small needs - light, heating, kitchen utilities. We would have enough stored energy to provide for our families for at least ten years.
{153}{}{I see that you were able to fix the electricity! Thank you. You've been a great help. I don't know how to repay you. Here, take this whiskey. I found it in the old house and was saving it for the holiday. But it's better to share it with a good man.}
{154}{}{You're welcome.}
