{101}{}{The books, pamphlets and writing on these shelves can tell you more about the history of Bridgeport.}
{102}{}{You cannot read while in combat.}
{103}{}{With your erudition it would be too difficult and boring to dig through so many papers.}
{104}{}{The use of this computer requires scientific methods.}
{105}{}{You will need not only your hands, but also your head to study the publications on these shelves.}

{110}{}{These shelves are lined with a variety of pre-war pamphlets and books, as well as the personal records of the last owner. In general, these materials cover the history of Bridgeport.}
{111}{}{Read the section on the pre-war history of the settlement.}
{112}{}{Read the section on the year 2077.}
{113}{}{Read the section on the postwar history of the settlement.}
{114}{}{Leave.}

{115}{}{It was a small town, inhabited mainly by two types of people - rich families and spa workers. Bridgeport was famous for its mountain resorts with lakes full of trout and pristine snowy slopes. A quiet place, almost a paradise, suitable for a carefree life. Partly because of this, many wealthy residents of Nevada and California set up their vacation homes here for various holidays and weekends.}
{116}{}{According to bits and pieces of information, the village was completely wiped out during the Great War. Locals had nowhere to hide from the radioactive fallout blown by the winds from the nuclear devastation wrought in Los Angeles to the south and Area 51 to the northeast. Realizing their doom, many residents threw a farewell party on the streets of the city, determined to meet death with a smile on their face.}
{117}{}{The village has probably been uninhabited since that day when the population was wiped out in 2077. Less than a decade ago the first settlers, refugees from Reno, brought life back to the village.}
