{100}{}{You see Birch.}
{101}{}{Before you is a pretentious looking man with a straight, broom-like posture.}
{102}{}{}

#Первый разговор
{110}{}{Wait, I already paid for this barn and do not want to pay extra for some questionable bonuses! You can tell this to Marilyn - and shall she bring some warm water to me already? I want to wash my feet.}
{111}{}{What are you talking about?}
{112}{}{Oh, I thought you, like that snotty brat, came to promote her meat salads... The name's Lewis Birch and I arrived here recently... Although, nevermind.}
{113}{}{Relax, I just want to ask some questions, as you're luckily not busy...}
{114}{}{I will. Goodbye.}

{115}{}{Questions? Apparently, the only thing you can do in this shithole is chat. Why not, though? If people ask an advice from me, that... That means something.}
{116}{}{Hm?}
{117}{}{Eh, you asked something?}

{118}{}{No, nothing. Let's talk later.}
{119}{}{Let's change the subject.}
{120}{}{Let's stop at this, perhaps. We'll continue another time.}
{121}{}{You asked something, sheriff?}

#О себе
{130}{}{Why don't we talk about you?}
{131}{}{About me? Oh, we can talk about it for hours.}
{132}{}{Who're you?}
{133}{}{Lewis Birch. But my position will hardly tell you something. Let's just say - I'm, in some ways, a scientist, researcher and inventor.}
{134}{}{You're not local? Then where did you came from?}
{135}{}{How perceptive... I'm from the south, from the city called The Hub. It's quite far from here, and I don't want to talk about that region. Though, I must say, the trip was horrible - no comfort, no logistics. Hardy's caravan was walking sideways, mostly in dry places, right under the sun. After such experience you start to appreciate a simple pleasures, like hot bath and a glass of cold brahmin milk... Yeah. So I don't recommend travel in that direction.}
{136}{}{Who's Hardy?}
{137}{}{[Indifferently waves his hand] Some not-so-witty Hub caravaneer. He's the only one who trades between Reno and Hub. If I were him, I'd stop this long time ago, but what one ghoul has on his mind - it's a complicated question.}
{138}{}{What brought you here?}
{139}{}{Well, let's just say, my mission is simply gathering information about this... Godforsaken place. We've heard rumors of the still running local uranium ore mine. So, I was assigned to examine the situation. But what I see here is... Very depressing. The only option left for me is to return back, full of bewilderment and disappointment..}
{140}{}{What kind of organization do you represent?}
{141}{}{The Union of Atomic Workers? Oh, it's rather old company. We're not what we were in the past, I admit, but we still in the lead in Hub... Wait, you don't even know *that*? Ugh, unsurprising.}
{142}{}{What does your organization do?}
{143}{}{Well, let's say, without exaggeration and embellishment - basically, we are trying to revive the world. At least in the form which we once knew it - with the trade, economy, manufacturing, and all that is necessary for normal life of a society. But all of this is limited to Hub so far.}

#О поселении
{150}{}{I want to know you opinion on this settlement.}
{151}{}{Uranium City? Perhaps, some time ago it was "city", but now only "uranium" left. Unrefined even.}
{152}{}{Do you know anything about history of this settlement?}
{153}{}{Good question! After all, I'm here for exactly that - for information gathering. And here's what I know. Ahem. It's a pre-war settlement. Here the ore was mined, put through the simple refining, and then - exported to other places for further processing and usage.}
{154}{}{[Next]}
{155}{}{Actually, the ore deposits are rather small. So, it's no surprise that locals lived here in conditions worse than slaves - they didn't even have carts for ore transportation, not to mention benches. The only ore processor is in the hangar, near the mine - and it was terribly outdated even before the war. All of it lied meaningless since 2077, until some important person from New Reno decided to try extracting ore for the city power station. That's when the slaves began to be transported here and the flow of people poured in for easy earnings. Heh, silly people, I must say - most of them stayed here forever. Well, you know what I mean.}
{156}{}{[Next]}
{157}{}{Now here's only silence remains. Why, you'd ask? And I know the answer. Because, according to local rumors, some kind of mutant creatures, appearing out of the ground, settled near the mine. My God, what a load of crap! I'll say how it is - local workers became tired of inhuman working conditions and fled to other towns. Someone should kick the Reno gangster's ass for his poor organizing work.}
{158}{}{I'd like to know more about this settlement.}
{159}{}{Thanks for the story. That's enough.}

{160}{}{What do you know about the mine?}
{161}{}{There are several small mines in the district, many were milked out dry before the war. In fact, the ore deposits are not so big at all. That mine tunnel, near the village, leads straight to not depleted vein of rough uraninite. When it is fully worked out, there will be nothing left to do there. So this settlement will eventually die out. If not now, then ten years after, that's for sure.}
{162}{}{How did the locals managed to work here, if the ore from the mine is radioactive?}

{163}{}{Hmm. I asked myself the same. I have a few suggestions. Want to listen?}
{164}{}{Yes, please.}
{165}{}{Nah, some other time. I have another question about this settlement.}
{166}{}{First - is because of local guild's work regulations. Seems like people were smart enough to take into account the effects of radiation exposure. Anyway, the local equipment was not enough for everyone.}
{167}{}{Second - cynical administration. Members of the guild themselves never even came close to the ore - they only supervised the process. But they exploited the staff ruthlessly. Who did overtime - was promised percentage bonuses. The more you work, the more you get paid per hour! Brilliant! How better to motivate employees in a situation like this? Of course, because of that, many ignored the regulations and worked in the mine for 14 hours a day. And when such stupid workaholic, greedy for money, dies from exposure, he is then burned in incinerator and his earned money split in the office. Brilliant!}
{168}{}{What else?}
{169}{}{But this does not explain why some worked here for a long time and didn't get radiation sickness.}
{170}{}{[Frowns in displeasure] Yes... But there were quite a few of them. I can't consider Nelson - there's different, shady story behind him. I suspect that this is somehow related to the local ration. I haven't yet, uh, studied this question.}
{171}{}{Enough of this crap! Tell me straight then - you don't know shit about chemistry.}
{172}{}{What!? H... How dare you! I'm the best scientist among the all Hub! But y-yeah, chemistry is not my strong suit. So what? If you're so educated, perhaps, you can share you thought on this matter, huh?}
{173}{}{How curious. Could you find out what exactly? You seem to be a man of science... }
{174}{}{Uh, well, I'm one of the top scientists in the Hub... And one of the few, of course. But chemistry, especially organic - it's not my profile. However, I'd love to hear someone's hypothesis. But you yourself don't know, right?}

{175}{}{Does this town have a future?}
{176}{}{I'm sure it doesn't! When the local mine will be completely worked out, no one will care for the local ruins. However, before the war, it could still have a chance to be a some kind of open-air museum of mining, but now there's no one to attract.}

{177}{}{About radiation sickness of the locals.}
{178}{}{Well, got any suggestions?}
{179}{}{No, let's talk about something else.}
{180}{}{I have one. Marilyn said miners consumed a lot of alcohol...}
{181}{}{Ha! This is the same anti-scientific heresy as the belief that the brahmin were once one-headed! Nonsense. Alcohol is not a cure. We have already tested it at the Hub, local brew did show some effect, but very weak. To use a rot gut as a medicine against radiation sickness - don't make the scientist laugh!}
{182}{}{Unlike other drinks, local "rot gut" traditionally contains a lot of ethanol.}
{183}{}{Uhh, I don't understand how...}
{184}{}{Its radio-protective properties can improve the radiation resistance due to, for example, the reduction of oxygen in tissues, due to the easy oxidizability of alcohol compounds.}
{185}{}{Ehh, let me ret... }
{186}{}{However, alcohol does not really have a special anti-radiation effect. But inhibits the activity of nerve cells which means that any stressor, including radiation, is less harmful to the organism.}
{187}{}{Well... Ugh... Okay, if you really think about it, then there is some bits of common sense. However, I am sure that ethanol will be effective only with strong and brief irradiation, when the body receives a dose of radiation over a short period of time!.. On the other hand, if those workers were regulating their time in the mine... But... If... It is still unknown, what this booze contains, which can enhance the effect so much, you know!..}
{188}{}{Uh-huh...}
{189}{}{[Straightens the hair and makes academic look] Well, the idea is certainly deserves attention. When I get back to the Hub, I'll try to conduct a series of experiments, it's worth to test this hypothesis.}
{190}{}{See...}
{191}{}{I must say, it was an enlightening conversation, but a bigger surprise for me is to meet a chemistry connoisseur in such a shithole. If you'll come to the Hub - be sure to visit us.}
{192}{}{I'll consider it.}
{193}{}{You have gained experience for using scientific knowledge.}
{194}{}{I'll think about it, now let's chat about something else.}

#Владение шахтой
{200}{}{Have you thought about getting the mine under your lead?}
{201}{}{Manage the mine from the Hub?! Well... To say honestly, this would be perfect, if not for local problems. We don't want to deal with the former owner, local mutants and these rude workers.}
{202}{}{You want to have everything nice and ready? Could you at least move your finger to not miss the opportunity for once?}
{203}{}{In that case I have good news - mine is cleaned from the mutants.}
{204}{}{I've said everything already.}
{205}{}{Oh, it makes all the difference! I would gladly buy the mine, but I need the approval of the members of our union. There is one hitch - I can't leave the settlement now, and the only communication is through the Hardy caravan which doesn't even have a regular schedule. Someone will have to send my report through the caravan.}
{206}{}{Then I'll send the report.}
{207}{}{Really? That makes all the difference! If so, then I will send the information to the Hub at the first opportunity. I think the members of our union will approve this decision. Yes, and tell the news to Marilyn. Thank you.}
{208}{}{You're welcome.}
{209}{}{Not me, that's for sure. Bye.}

{210}{}{Well, you can be trusted. Here is a copy of the report. Find the Hardy's caravan. This ghoul travels between Reno and Hub. He has an agreement in Reno with a store at caravan parking lot, so he doesn't stay in the town for long.}
{211}{}{Okay.}

{212}{}{We already agreed on everything. Deliver the report, then our organization will take Uranium City under it's wing.}
{213}{}{Report delivered.}
{214}{}{That report? Got it.}

#Обучение энергооружию
{250}{}{This pistol - it's energy weapon, right?}
{251}{}{[Grins joyfully] Noticeable thingie, isn't it? And even not so much noticeable as repelling for those who know what it is. Glock 86 Plasma pistol - serious business.}
{252}{}{How interesting. Would you teach me to use one?}
{253}{}{Ah, perhaps I'll skip this little detail past my mind.}
{254}{}{Hm. On the one hand, our Union is all for the principle of democracy and the information sharing. On the other, I have no desire to share such knowledge upon the Wasteland. Well, let's say - for your service, I can teach you the basics of such weapons, but nothing extra.}
{255}{}{One good turn deserves another? That's fair.}
{256}{}{No, such option doesn't satisfy me.}
{257}{}{Don't take me for barbarian, but I haven't had a bath yet, and this lady behind the bar, who runs this place, didn't give me the water. I don't ask much - 30 pounds at least, to fill the washbowl. Would you be so kind to provide me with water? And then we'll discuss what to do next.}
{258}{}{I'll think about it.}
{259}{}{I have clean water.}
{260}{}{I've got you clean water.}
{261}{}{I hope, there'll be at least 30 POUNDS of water?}
{262}{}{Yes, 15 flasks, 2 pounds each.}
{263}{}{No, I don't have such amount.}
{264}{}{That's better! And Marilyn didn't want to share... Now leave me for an hour. Perhaps, I'll ask you about another one later.}
{265}{}{[Wait outside]}
{266}{}{You're still dirty, under the ear...}
{267}{}{Well-well. I don't like lavatory humor much. But still - thanks. Walking unwashed since the Hub itself - what a "pleasure".}
{268}{}{How can you even spend so much scarce water on washing your body?! It's foolish!}
{269}{}{I don't care. I did my part of a deal and now I want the bonus.}
{270}{}{That's right - it was foolish to waste so much water on one person. Ha! Now who's more foolish, eh?}
{271}{}{Have to leave it on your conscience. Now I want to get my bonus.}
{272}{}{Ah yes. I remember what I promised. But there's one more important thing.}
{273}{}{Wha-at!? What the hell!}
{274}{}{Alright. I'll do your thing.}
{275}{}{This is too important to trust to simple adventurer. The story with the water was a test of your motivation and interest. In fact, I gave part of the water to Marilyn for the needs of the motel. Our Union bequeathed to share knowledge and experience with people, if they deserve it. Now I'm sure that we have a common interest, no matter what drives you - greed or the desire to help people.}
{276}{}{And what do you need?}
{277}{}{I prepared a report for my comrades in the Hub, and I need an intermediary to transfer it there. I understand that the Hub is far away and you will not go there, but this is a concern of one of caravans.}
{278}{}{I'll do it.}
{279}{}{I don't want to do this.}
{280}{}{I remember you wanted to give me a task?}
{281}{}{Ah yes. I remember what I promised. But first you need to do some post delivery.}
{282}{}{Got it.}
{283}{}{Ah yes. I remember what I promised. Since you have already sent the report, I can only lay down my gloves in honest and share my knowledge.}
{284}{}{Then let's start now!}
{285}{}{I'll come back later when I'm ready.}
{286}{}{You know, I'm sick of it, so I refuse.}
{287}{}{[Oddly enough, Birch was a good teacher, he systematically and consistently explained to you the principles of plasma weapons and some properties of using it.]}
{288}{}{[Walk outside on fresh air]}
{289}{}{Birch increased your energy weapon skill by 5%.}
{290}{}{What about payment?}
{291}{}{What is this? Money? Good... For these underdeveloped parts. We have already introduced a new currency in our Hub, for a long time. Wait ten years - and this fashion will reach you too. But no, I don't need money as much as anything else.}

#Female character
{1260}{}{I got the water.}
{1269}{}{I don't care. I did my part of a deal and now I want the bonus.}