{100}{}{You see Betty.}
{101}{}{You see the usual horned cattle. Apparently, the only one in this settlement.}

{110}{}{Mo-o-o.}
{111}{}{[Lead the brahmin]}
{112}{}{[Leave the brahmin here]}
{113}{}{[Do nothing]}

{114}{}{Moo!}
{115}{}{That's better.}
{116}{}{Moo?}

{117}{}{[Mine brahmin with Dynamite]}
{118}{}{[Mine brahmin with Plastic explosives]}
{119}{}{You're free, Betty. Mutants are dead, I don't need you anymore.}
{120}{}{Betty's free now.}

{121}{}{(This is not a suitable place to place a bait.)}
{122}{}{You lured the mutants into a trap and blew the mine.}
{123}{}{Brahmin is stalling, refusing to go any further.}
{124}{}{Move your ass you fucking animal!}

#Попытка толкать (фразы при низкой карме)
{130}{}{Move, stupid fat cattle!}
{131}{}{Move yourself, you animal!}
{132}{}{Go, or 'll smack you with a whip!}
{133}{}{If you keep stalling, you'll get it!}
{134}{}{You're making me mad, you animal. O-oh, how mad I am!}
{135}{}{Hrm, stupid brahmin...}
{136}{}{You'll get some for your stubbornness!}
{137}{}{Alright, one more time and my patience is done.}
{138}{}{Move!}
{139}{}{Come on, Betty, dear, move... Or I'M GONNA BLOW YOUR BRAINS OUT!}