{100}{}{You see Zhu Shi.}
{101}{}{You see a woman with unusual skin color and slanted eyes.}
{102}{}{You see Zian Shi.}
{103}{}{You see a man with unusual skin color and slanted eyes.}

{110}{}{Greetings, sir.}
{111}{}{Greetings, sheriff.}
{112}{}{Best regards.}

{113}{}{I'd like to know how you ended up here.}
{114}{}{What do you do in this little town?}
{115}{}{Why don't you go somewhere where life is better?}

{116}{}{Me and my husband Zian are from San-Francisco. Emperor decided that we are useless to the community and banished us. Sometimes he's a little too harsh, but we didn't mind.}
{117}{}{Me and my wife Zhu are from San-Francisco. Emperor decided that we are useless to the community and banished us. Sometimes he's a little too harsh, but we didn't mind.}
{118}{}{Who's Emperor?}
{119}{}{Tell me about San-Francisco.}
{120}{}{Why didn't you mind?}
{121}{}{No one saw Emperor since the founding of Palace. And it was a long time ago. We only know that he lives in the palace, and no one but his First Advisor can see him.}
{122}{}{Ruins and more ruins - this is what awaits any traveler. But Shi are trying hard to restore the city with their labor. The palace has already been rebuilt, the clan has settled in the suburbs, other neighborhoods are waiting their turn.}
{123}{}{We dare not oppose the Emperor's will. He has decided so - and we will obey. But we like living like farmers, I must say. The land smells of life and is soothing, while the ruins of the city only make us feared and angered.}

{124}{}{We cultivate maize and breed Brahmin. We are peasants, we are born to do this.}
{125}{}{But we live well here. We grow crops, breed cattle, we are not hampered by the noise and bustle of the big city. Now this is our home. And we do not want to leave, even if the earth dragons devour all our brahmin.}
{126}{}{Earth dragons?}
{127}{}{Oh, Nelson hasn't told you yet? The greed of the men who worked in the mine has awakened the earth dragons. They want to punish the people as Gods once punished them with a hellfire that wiped out entire cities.}
{128}{}{Let's suppose I want to meet them. What do I need for this?}
{129}{}{Well, there's nothing better than to make noise. We even had to put away a noisemaker made of cans that guarded our herd at night. It's on the shelves.}

#Брамин
{150}{}{I apologize, but I need your brahmin to save this settlement.}
{151}{}{Betty? She's the only one left. We can not give it away just like that.}
{152}{}{Betty? Do you give names to all your Brahmin?}
{153}{}{Think about it - someday these underground creatures not only will eat miners, but will get to you and Betty.}
{154}{}{I can buy this brahmin. Will 1000 bucks satisfy you?}
{155}{}{You think about the offer, while I walk around.}
{156}{}{Actually, it's not us who called her like that, but old Nelson. He called all our brahmin with such name, sometimes muttering, as if in jest: "Betty, my beauty, you want a ride in my car?" Seems like a long life without women is affecting him, tee-hee.}
{157}{}{[They whisper with each other for a while] We agree.}
{158}{}{Here's the money.}
{159}{}{I'll return with money.}
{160}{}{It's so sad to part with Betty...}
{161}{}{It does not matter anymore. Now she's mine!}
{162}{}{I understand. But nothing lasts forever.}
{163}{}{[They whispers with each other for a while] We understand. It's sad to part with Betty, but your words sounds so wise that we can't refuse.}
{164}{}{[They shake their heads] The greedy miners are to blame themselves. Dragons will not touch those who live in peace, like us. All our possessions are the shack and Betty, what can make up for her loss?}
{165}{}{Thanks, you did the right thing.}

#Женские реплики
{1110}{}{Greetings, ma'am.}