{100}{}{You see Zhu Shi.}
{101}{}{You see a woman with unusual skin color and slanted eyes.}
{102}{}{You see Zian Shi.}
{103}{}{You see a man with unusual skin color and slanted eyes.}

{110}{}{My respect, sir.}
{111}{}{My respect, sheriff.}
{112}{}{Best regards.}

{113}{}{I'd like to know how you ended up here.}
{114}{}{What do you do in this little town?}
{115}{}{Why don't you leave to somewhere where life is better?}

{116}{}{Me and my husband Zian are from San-Francisco. Emperor decided that we are useless to the community and banished us. Well, sometimes he's a little too harsh, but we didn't mind.}
{117}{}{Me and my wife Zhu are from San-Francisco. Emperor decided that we are useless to the community and banished us. Well, sometimes he's a little too harsh, but we didn't mind.}
{118}{}{Who's Emperor?}
{119}{}{Tell me about San-Francisco.}
{120}{}{Why didn't you mind?}
{121}{}{No one saw Emperor since the founding of Palace. And it was a long time ago. We only know that he lives in the Palace, and no one, except his First Advisor, can go see him.}
{122}{}{Ruins and ruins again - that is what awaits any traveler. But Shi are trying to restore the city with the hard labor. Palace is already rebuilt, clan already settled in dormitory suburbs, other areas are waiting for their turn.}
{123}{}{We do not dare resisting the will of the Emperor. He decided that - so we must obey. But we like living as farmers, I must say. The soil smells of life and soothes - and city ruins only set anguish and anger upon us.}

{124}{}{We cultivate maize and breed Brahmin. We are peasants, we are born to do this.}
{125}{}{But we live here well. We grow crops, breed cattle, we are not hampered by the noise and bustle of the big city. Now this is our home. And we do not want to leave, even if the earth dragons devour all our brahmin.}
{126}{}{Earth dragons?}
{127}{}{Oh, Nelson hasn't told yet? The greed of people that worked at the mine awakened the earth dragons. They want to punish people, as God once punished them with an infernal flame that wiped out entire cities.}
{128}{}{Let's suppose I want to meet them. What do I need for this?}
{129}{}{Well, then there is nothing easier than to create more noise. We even had to remove the noisemaker made from cans, that guarded our herd at night. It's on the shelves.}

#Брамин
{150}{}{I apologize, but your brahmin is needed to save this settlement.}
{151}{}{Betty? She's the only one left. We can not give it away just like that.}
{152}{}{Betty? Do you give names to all your Brahmin?}
{153}{}{Think about it - someday these underground creatures not only will eat miners, but will get to you and Betty.}
{154}{}{I can buy this brahmin. Will 1000 bucks satisfy you?}
{155}{}{You think about the offer, while I walk around.}
{156}{}{Actually, it's not us who called her like that, but the old Nelson. He called all our brahmin with such name, sometimes muttering, as if in jest: "Betty, my beauty, you want a ride in my car?" Seems like a long life without women is affecting him, tee-hee.}
{157}{}{[They whisper with each other for a while] We agree.}
{158}{}{Here's the money.}
{159}{}{I'll return with money.}
{160}{}{We'll be sorry to part with Betty...}
{161}{}{It does not matter anymore. Now she's mine!}
{162}{}{I understand. But nothing lasts forever.}
{163}{}{[They whispers with each other for a while] We understand. We'll be sorry to part with Betty, but your words sounds so wise that we can't refuse.}
{164}{}{[They shake their heads] The greedy miners are to blame themselves. Dragons will not touch those who live in peace, like us. All our property is a shack and Betty, so what can make up for loosimg her?}
{165}{}{Thanks, you did the right thing.}

#Женские реплики
{1110}{}{My respect, ma'am.}