{100}{}{You see Marilyn.}
{101}{}{You see the owner of the local saloon, a proud and strong woman.}
{102}{}{If you don't stop, you will regret it!}
{103}{}{You are now deprived of the rank of Sheriff of Uranium City.}

{109}{}{Be quick about it, or go away.}
{110}{}{[As you enter the saloon, you encounter the stern gaze of a pretty woman] Oh, a new man in Uranium City? Great. I hope you're not going to start bar fights or drag uranium ore in here... And yes, clean your boots before you come in so you get less dirt in. And no guns. And that's just part of the rules. If you don't like it, stay outside.}
{111}{}{Erm, I will keep your rules...in mind.}
{112}{}{You know, you have an intolerable personality.}
{113}{}{Okay then. So, what can I help you with?}
{114}{}{Yes. I know. And you're just a wanderer passing by. So, what can I help you with?}
{115}{}{With some answers, I think.}
{116}{}{Did you want something?}
{117}{}{See you.}
{118}{}{Hmm...}
{119}{}{How can I help the sheriff?}

#Î ìåñòíûõ æèòåëÿõ
{120}{}{You have quite the company around here.}
# 121 Oh Yes. Lousy Indian, Ghoul-paranoid, poor Chinese gangsters and a strutting Turkey from the south. But I already used. Perhaps this is the fate of many mining towns. Here are flocking to work from across the region. And, of course, nothing but their mercantile interests they replace the village did not want to give. Well, instead remaining at least can agree among themselves. It is already an achievement, isn't it?
{121}{}{Oh yeah. A lousy Indian, a paranoid ghoul, poor Chinese, bandits, and some arrogant asshole from the South - but I'm used to it by now. I guess that's the fate of all small mining towns. A lot of people flock here from all over the region to work. And - obviously - they don't want to give society anything but their own mercantile interests. But those who stay, at least, can agree with each other. Already an achievement, isn't it?}
{122}{}{Tell me about the "arrogant asshole".}
{123}{}{Paranoid ghoul?}
{124}{}{Poor Chinese, who is that?}
{125}{}{I am interested in the Indian.}
{126}{}{I would like to know more about the "bandits".}
{127}{}{Let's talk about something else.}
{128}{}{You know, it's boring. So bye.}
{129}{}{Hmm. Such as?}
{130}{}{Okay. Well, see you.}

{131}{}{Lewis Birch? He's... How can I put it, he's quite a character. I don't know how they live in the South, but he just won't shut up! You won't find such self-righteous and arrogant jerks anywhere. But he could be useful - in other circumstances.}
{132}{}{Nelson. He's a local. Nobody knows his past, and I doubt it was any good. Otherwise he wouldn't be saying all this crazy shit all the time.}
{133}{}{A family of farmers. They came from San Francisco a couple of years ago, and they're doing just fine here. They're very hard working people. One thing I don't understand is why the hell they left the big city. You should ask them yourself.}
{134}{}{I liked this hairy redskin immediately. He's from Cheyenne. He was a slave for many years, until he finally ended up here. Now it is his home.}
#puberty problems?
{135}{}{Well, you can count them on your fingers. Tony is a typical guy with puberty problems. He's sick and can't seem to get well. Kelly is a good shot, but it feels like his soul is just... empty. Juan is a guy so brutal that sometimes you want to kick him in the balls. That's all. Not that they're real thugs, but if this keeps up, they're going to have to earn their bread the dishonest way.}
#--Còàðûé âàðèàíò: Íó, èõ íàäî ïåðå÷èñëÿòü ïî ïàëüöàì. Òîíè - îáû÷íûé òàêîé ïàðåíü ñ íåîêîí÷åííûì ïîäðîñòêîâûì êðèçèñîì.
#Áîëåí è âðîäå áû íåèçëå÷èìî. Êåëëè - õîðîøèé ñòðåëîê, íî òàêîå îùóùåíèå, ÷òî çà äóøîé ó íåãî ñîâñåì ïóñòî.
#Õóàí - âåñü òàêîé êðóòîé áðóòàë, ÷òî ïîðîé òàê è õî÷åòñÿ ïíóòü åìó ïî ÿéöàì.
#È, íàêîíåö, Ðîìàíòèê - ñàìûé áåñïîëåçíûé êóñîê ìÿñà âî âñåì Óðàí-Ñèòè. Âîò òàêîé íàáîð øïèíàòà.
{136}{}{About the sick one.}
{137}{}{This brat thinks he's going to get in my pants eventually. And, of course, that's not going to happen... But *perhaps* I've been too hard on him. Given his illness... Yeah. It wasn't very nice.}
{138}{}{No that's okay - he is not with us anymore. He's dead.}
{139}{}{Already? Oh... [She sighs] I'm used to such news. I will throw a farewell party later.}

{140}{}{Tell me about other settlers.}
{141}{}{Who do you want to talk about this time?}
{142}{}{Let's talk about something else.}

{143}{}{A farewell party? But he was trying to get you into bed!}
{144}{}{But that doesn't mean I have to treat him like crap now. You have to put up with all kinds of things these days. I've had worse.}

{145}{}{Is it true that Birch gave you clean water?}
{146}{}{Yes! Surprising, isn't it? But I think he's just trying to make an impression. The man needs the feeling of importance, you know?}

#Àðñåíàë Ìýðèëèí
{150}{}{Nice arsenal you have in that closet there...}
{151}{}{Yeah. Uranium City has seen many "cowboys" that chase wealth, and when the time comes to pay the dues, many have nothing but a gun on them. That's where this collection comes from. Not the best choice, but at least we always have something to protect ourselves from nasty visitors.}
{152}{}{I want to buy this collection.}

{153}{}{Not a bad idea. In the past we had no problem disposing of the arsenal. We took the best ones with a caravan to Reno, the rest were picked up by miners with payment. But now there's none of that. So, you know what? [She thoughtfully scratches her ear] I will sell everything for 1500 bucks.}
{154}{}{I'm buying it! Here is the money.}
{155}{}{[She gets lively] What, really? Great! It's open, you can take everything you see in there.}
{156}{}{Outstanding.}
{157}{}{Too expensive! For this junk I will pay 300 tops.}
{158}{}{Is that so? That won't even cover the damages the previous owners caused. 1500 is almost a gift! No-o, no deal.}
{159}{}{Think. New workers won't be here anytime soon, and there is no more trading with Reno. This way you will at least get something out of this junk.}
{160}{}{[Sights heavily] You're right. Even if I hire a caravan or take the weapons there myself, I will lose more money on transportation... Okay, let it be 300.}
{161}{}{Smart choice. Here 300 bucks.}
{162}{}{Oh, easy! You've done so much for us, that I won't regret a bit giving all this to you. Take it! The closet is open.}
{163}{}{Thanks!}
{164}{}{Not that fast! You shouldn't have swung your fists around the bar. Now you won't get anything for just like that. We're done.}
{165}{}{Oh, easy, sheriff! You need it more anyway. Take it! It's open.}

#Ìÿñî äðàêîíîâ
{169}{}{You're welcome. Anything else?}
{170}{}{I see your menu got bigger?}
{171}{}{Well, we found the remains of the earth dragons and thought that it would be a shame for them to go to waste.}
{172}{}{And... How is it?}
{173}{}{Nobody has been poisoned yet. And the meat is much more nutrient than brahmin's. Besides, we are sick of eating the same stuff all the time.}
{174}{}{It seems this is not just meat. Can you tell me the recipe?}
{175}{}{It's all simple - [She gets excited] the meat is mixed with pepper and salt, then poured over with brahmin milk. Then the cutlets are cooked in maize oil and wrapped up in maize bread with greens. Sounds tasty, isn't it?}
{176}{}{Well, worms, of course, are edible too. Especially when there is nothing else to eat. Can I, uh, have some?}
{177}{}{Eww, disguising! These worms could crawl anywhere, and you eat them! Ew! Ew! Ew!}
{178}{}{Sure! Here, have a plate, free of charge.}
{179}{}{Oh no! This is really delicious. Here, try some. It's on the house.}

#Óñëóãè
{180}{}{Can I rent a room?}
{181}{}{Yes. 50 bucks and you can have a room for the night.}
{182}{}{Do you have anything to eat?}
{183}{}{I only can offer meat and Rot Gut. I keep clean water for myself, sorry.}
{184}{}{Okay, let's trade.}
{185}{}{Nothing I need.}
{186}{}{That's all? One can starve like this.}
{187}{}{Indeed, I want more.}
{188}{}{That's enough. let's talk about something else.}
{189}{}{That will be enough. Now excuse me - I have things to do.}

#Î ãîðîäå
{199}{}{No big crowds of customers or tourists, which is damn great. Where do I start, sheriff?}
{200}{}{Would you mind to talk about this settlement?}
{201}{}{No big crowds of customers or tourists, which is damn great. Where do I start?}
{202}{}{Enough about the town, I need something.}
{203}{}{Will continue another time.}

{204}{}{Is there something to do around here to have fun?}
{205}{}{No.}
{206}{}{Nothing at all? No slot machines, no shooting, no...}
{207}{}{Erm, okay.}
{208}{}{Anything else?}
{209}{}{Hmm. I don't understand - are you fooling around or trying to make an impression? Okay, never mind. Look, this is a *working* settlement. People came here to mine ore, and many of them died because they were greedy or stupid. And now you come here and ask if there's anything to do for fun. I suppose you've had much better luck in life.}
{210}{}{Great, how about if I find something to entertain myself?}
{211}{}{Fine. forget it.}
{212}{}{Now hold it right there! No fighting or shooting in my establishment! This is a decent venue. Anybody who doesn't agree with that, I'll throw out myself. Go fight somewhere else.}
{213}{}{You? Throw me outside? Ha-ha-ha! Be careful not to hurt yourself, little girl.}
{214}{}{Don't worry, it still won't stop me. I've been beating boys since I was a teenager.}
{215}{}{Uh, you fought boys?}
{216}{}{Damn right! They all thought strength could solve any problem. And? A couple of moves and even if I don't have a ton of muscle, the end is always the same: tears, whining and crying in front of my mom. Ha, those were the days!}
{217}{}{This changes things. Let's leave everything as it is.}
{218}{}{I don't give a shit - I do whatever I want. You are just a mere annoyance to me!}
{219}{}{You! I should've thrown you outside as soon as you started. Fucking imbeciles, all you do is brawl muscles around! Do you know what? Any of my stuff will cost twice as much for you now. Is that clear? Damn right!}

{220}{}{What is that building across the street?}
{221}{}{Another question.}
{222}{}{The office of the miners' guild. It's locked, it's dark, and there are rats inside. There's nothing to do there. It used to be the busiest place in Uranium City, not counting the mine. Now the people are gone and no one goes there.}
{223}{}{Tell me about the neighborhood.}
{224}{}{You can say we are on the edge of civilization. And, honestly speaking, I like it. In the best-case scenario a caravan from Hub will pass through, but mostly we are cut off. Everyone tries to get to new Reno... Or away from it.}
{225}{}{Tell me about the mine.}
{226}{}{We have one mine here. It's from before the war. We had been mining uranium ore for Mr. Wright in New Reno for over a year when those mutants came and destroyed everything. As a result, the settlement is mostly abandoned, the ore hasn't been processed, and we're trying to do something more profitable. Farming, for example.}
{227}{}{How did it all start here?}
{228}{}{From Mr. Wright and his sons. He decided to revive the city's power plant in New Reno and sent his sons to the mines. They liked Uranium City because there was at least some, albeit rudimentary, technical equipment. Then a guild of miners was formed. At first the main workforce were slaves, but it turned out to be more expensive than hiring workers. That's how we lived for more than a year. And lived well.}
{229}{}{I don't get one thing - how people worked while being constantly radiated?}
{230}{}{Good question. Nelson sometimes even glowed at night after the mine. You could save money on electricity with him, haha!}
{231}{}{Is the mine really that radioactive?}
{232}{}{Well, not as much as you might think. There's no purified uranium, just ore. The real radiation was where the ore was processed. And yet it's a sore point for Uranium City. When everything was under Wright, slaves and free laborers worked here. They were prone to... casualties. After all, being irradiated, one could still work for more than a year until the disease took its toll. And in that time, one could gather enough to feed one's family - or live one's short life bright and interesting. That's not so bad these days.}
{233}{}{Bright and interesting?}
{234}{}{Oh, so much happened here! But it's all in the past now, when the settlement was full of people.}
{235}{}{And how did they manage to keep the radiation sickness at bay for so long?}
{236}{}{Well, the guild wasn't stupid, you know. They had a schedule and rules. You had to work in rubber gloves and boots, wear a mask, take off all the metal before you came in. And, of course, there were working hours standards. And those who were ready to sacrifice their health for money were responsible for the result. The typical schedule was 14 hours, then everyone went to my bar for a drink. The Rot Gut was flowing in rivers!}
{237}{}{Right.}
{238}{}{Hmm. Strange, that's what the stranger from the south asked me. He's in his room, I think. Talk to him if you're interested.}
{239}{}{Great, at least now I know a little more.}

#Òåêóùàÿ ñèòóàöèÿ
{250}{}{We need to discuss the current situation in Uranium City.}
{251}{}{I'm listening.}
{252}{}{What really happened here?}
{253}{}{People began to disappear in the mines, and soon we found deep ditches in the ground and remnants of clothing. Then rumors of carnivorous worms began to spread, but only a few, like Nelson, assured us that they had actually seen them..}
{254}{}{That's it?}
{255}{}{Then the workers scattered. They didn't so much believe in mutants as they thought it was the guild's way of getting rid of workers to cut costs. When the miners became scarce, Wright went ballistic. Everyone scattered, no one came back - the rumors did the rest.}
{256}{}{Right. Now tell me about something else.}
{257}{}{Tell me once more about what happened here.}
{258}{}{}
{259}{}{Why don't you move to Reno or somewhere else? Somewhere better?}
{260}{}{Everyone says that - if it's bad here, then we should leave and go someplace better. But this is my home! And you know what? If it smells bad here, I'll just clean the shit up.}
{261}{}{Okay. But that's not all.}
{262}{}{What must be done to restore the place?}
{263}{}{Oh, it's not going to be easy. First, we have to get rid of the monsters, whoever they are. Second, we need to determine the ownership of the mine. Third, we have to get at least some of the workforce back. It's all complicated.}
{264}{}{Complications don't scare me. I'll deal with it!}
{265}{}{Really? That's great. I don't know what you have in mind, but the mine needs a lot of work, believe me.}
{266}{}{I will manage it somehow. Now let's make something more clear.}
{267}{}{Who should I talk to about the monsters?}
{268}{}{What is the problem with the mine ownership?}
{269}{}{What kind of workers do we need to bring back to get started?}
{270}{}{That's not all that interest me.}
{271}{}{Nelson tracks them down for a long time. If anyone knows something about them, then he's your man. I've heard that there are three monsters and they navigate by sound.}
{272}{}{I heard, that Wright went bankrupt because of the problems with the mine, he can't even hire a caravan to our city. Raises the question, how will he manage the production. Now, Nelson, even being a strange fella, at least knows the mine like the back of his hand. Wright decided to get rid of him and his gang to have less problems. Only that didn't help him.}
{273}{}{Let me tell you about everybody.}
{274}{}{The mutants are finished! All three corpses lay dead near the entrance to the mine.}
{275}{}{This gives hope! I don't even know how to thank you. Can only give you some Rot Gut on the house. Here [Gives you the bottle and some beef jerky]}
{276}{}{Somehow I don't see you too much excited.}
{277}{}{Ahh, sorry. So much stuff to do, even without the monsters, that the head goes spinning.}
{278}{}{Thanks, see you later.}
{279}{}{Joseph is one of the most competent administrators of the guild. He is the only one who can organize production, not let it slip away. The difficulty is that no one can find him after the trouble with the mine. He seems to be hiding from Mr. Wright, or maybe he's already been found.}
{280}{}{The others?}
{281}{}{Carl is the operator of refinement ore machine. Some said that he went to Reno. His family is somewhere in the slums. It seems to me that his wife doesn't want him to come back here.}
{282}{}{Michael - a guild supplier. He too decided to go back to Reno to give apologies to Wright. I don't know what happened to him.}
{283}{}{You know, it's enough for now.}
{284}{}{Then let's talk about something else.}
{285}{}{Seems like everyone's here?}
{286}{}{Oh, that's right! Things are getting better. Just like in good old times.}
{287}{}{Great. Let's talk about something else.}
{288}{}{But now Nelson is dead and no one is here to give me advice.}
{289}{}{Yes, I heard. Sad story. Hmm... Oh, I think Nelson proposed to tie dynamite to Lewis Birch and send him into the mine. Doubt that will work.}
{290}{}{Monsters won't bother you anymore... [tell the details]}
{291}{}{Now that's good news! And you did that all alone? You're a great person. Too bad there is nothing to reward you with. And there is still a lot of work ahead of us. But I can share some of my savings. Here, 300 bucks, I hope they will at least somehow compensate you work.}
{292}{}{"Thanks" will be enough. No money needed - you need them more than me.}
{293}{}{Money - it's everything I ever need!}
{294}{}{What, really? Just like that? You refuse? Great! But let me at least give you a drink on the house.}
{295}{}{Thanks.}
{296}{}{I knew, you will say that.}
{297}{}{Yeah. Bye.}

{298}{}{Wait! you did so much, would you leave us like this? Perhaps, this won't sound that great, but I would like to see you as our sheriff. I even have a badge for this case.}
{299}{}{I will be honored to be a sheriff of this town. Thank you for your trust, Marilyn.}
{300}{}{Thank you, Marilyn, but I already serve another city and I can't betray it. Leave this badge to yourself - you've earned it.}
{301}{}{[Marilyn takes the badge and pins it on your chest] Let it remind you of good deeds and order! By itself this title doesn't require anything, but when you will be in our parts - don't forget to stop by and ask how the things are going. Okay, sheriff?}
{302}{}{Okay, Marilyn. I won't let you down.}
{303}{}{Wow, so shiny!}
{304}{}{Me?! I was a local sheriff all this time, dammit. But - I understand. No harsh feelings.}
{305}{}{None. Farewell.}

#Ìóçûêàëüíûé àâòîìàò
{310}{}{Is this furniture with lights here for decoration?}
{311}{}{A jukebox? Workers once became bored and dragged this junk from the warehouse. I warned them that the machine doesn't work. Nobody managed to fix it, so it's just sits there.}
{312}{}{Can I look at it?}
{313}{}{Well, if you know what you're doing, yes.}
{314}{}{Okay.}
{315}{}{Jukebox is now working.}
{316}{}{Oh, wonderful! It was rather boring here. Thank you. Here, take some. On the house.}
{317}{}{Take care.}

#Êâåñò íà âëàäåëüöà øàõòû
{318}{}{Now Nelson owns the mine. Are you happy?}
{319}{}{The mine got back to Wright, he will restore it soon.}
{320}{}{Birch decided to take over the mine. What do you think?}
{321}{}{Of course! At least I know what to expect from him, we've known each other for so long. And given his experience in mining, Uranium City has every chance of recovering. But on the other hand, Nelson isn't very reliable, for example, he doesn't know how to negotiate with people. So someone should take over some of his work. In the end, it's better than nothing.}
{322}{}{No wonder. He has money, connections, and potential customers. It's a profitable decision. On the other hand, though, he'll make new calls here and change the workforce. Hopefully it won't have anything to do with me. Nevertheless, I like the fact that things have started to move.}
{323}{}{Birch? This one can do a lot of things, if he wants to. I mean, not him, but the organization he represents. They will bring some order here. I'm just worried about one thing - it's not in their interest to restore the city. They will come here with their guns and resources, take all the ore - and then pack things and leave, leaving us with nothing. But, sooner or later, the city will die anyway. I just want it to last a little longer.}
{324}{}{Your opinion is clear. See you.}

#Weapons in hand
{400}{}{I told you, no weapons.}
{401}{}{Oh, sorry, I forgot. [remove the weapon]}
{402}{}{My weapons are always with me!}

#Female character
{1114}{}{Yes. I know. And you're just a wanderer passing by. So, what can I help you with?}
{1401}{}{Oh, sorry, I forgot. [remove the weapon]}
