{100}{}{You see Marilyn.}
{101}{}{You see a mistress of the local saloon - proud and strong woman.}
{102}{}{If you don't stop, you will regret it!}
{103}{}{Now you are deprived from the rank of sheriff of Uranium City.}

{109}{}{Be quick about it, or go away.}
{110}{}{[Entering the saloon you come across a strict look of a pretty woman] Oh, a new person in Uranium City? Great. I hope you aren't going to put up fights in the bar or drag uranium ore in here... And yes, clean your boots before entering, to bring less dirt... And - no weapons. And it is only part of the rules. If you don't like it - stay outside.}
{111}{}{Erm, I will keep in mind... Your conditions.}
{112}{}{You know, you have an intolerable character.}
{113}{}{Okay then. So can I help you with?}
{114}{}{Yes. I know. And you're just a wanderer passing by. So what can I help you with?}
{115}{}{Some answers, I think.}
{116}{}{You wanted something?}
{117}{}{See you.}
{118}{}{Hmm...}
{119}{}{How can I help the sheriff?}

#О местных жителях
{120} {} {You have quite a company around here.}
# 121 Oh Yes. Lousy Indian, Ghoul-paranoid, poor Chinese gangsters and a strutting Turkey from the south. But I already used. Perhaps this is the fate of many mining towns. Here are flocking to work from across the region. And, of course, nothing but their mercantile interests they replace the village did not want to give. Well, instead remaining at least can agree among themselves. It is already an achievement, isn't it?
{121} {} {Yes. Lousy Indian, paranoid ghoul, poor Chinese, bandits and some arrogant asshole from the south - but I already got used to it. Perhaps, this is the fate of all small mining towns. Many are flocking here for work, from all of the region. And - obviously - they are willing to give to the community nothing, except their mercantile interests. But the ones who stay at least can reach an agreement with each other. Already an achievement, isn't it?}
{122} {} {Tell me about the "arrogant asshole".}
{123} {} {Paranoid ghoul?}
{124} {} {Poor Chinese who is that?}
{125} {} {I am interested in the Indian.}
{126} {} {I would like to know more about the "bandits".}
{127} {} {Let's talk about something else.}
{128} {} {You know, it's boring. So bye.}
{129} {} {Hmm. Such as?}
{130} {} {Okay. Well, see you.}

{131}{}{Lewis Birch? He's... How do I say it, is out of it. I don't know how they are down there, I mean south, how they live, but this one just doesn't stop talking! You won't find such self-righteous and arrogant assholes anywhere. But he could be useful - in other conditions.}
{132}{}{Nelson. He's local. Nobody knows his past and I doubt it was of any good. Otherwise he wouldn't say all this crazy shit all the time.}
{133}{}{Family of farmers. They came from San Francisco a couple of years ago and have settled here just fine. They are very hard working. I don't understand only one thing - why they hell they left the big city. You should ask them yourself about that.}
{134}{}{I liked this hairy redskin immediately. He's from Cheyenne. He was a slave for many years, until he finally ended up here. Now it is his home.}
{135}{}{Well, you can count them on your fingers. Tony - usual guy with some puberty issues. He's sick and seemingly cannot be cured. Kelly - a good shooter, but it feels like his soul is just... empty. Huan - the fella so brutal I sometimes want to kick him in the balls. That's all of them. Not like they are really bandits, but if this continues, then they will be forced to earn their bread in a dishonest way.}
#--Cтарый вариант: Ну, их надо перечислять по пальцам. Тони - обычный такой парень с неоконченным подростковым кризисом.
#Болен и вроде бы неизлечимо. Келли - хороший стрелок, но такое ощущение, что за душой у него совсем пусто.
#Хуан - весь такой крутой брутал, что порой так и хочется пнуть ему по яйцам.
#И, наконец, Романтик - самый бесполезный кусок мяса во всем Уран-Сити. Вот такой набор шпината.
{136}{}{About the sick one.}
{137}{}{This punk thinks that he will eventually get in my pants. And, of course, that's not going to happen... But *maybe* I was little too harsh on him. Considering his sickness... Yeah. It wasn't very nice.}
{138}{}{No that's okay - he is not with us anymore. He's dead.}
{139}{}{Already? Oh... [sights] I got used to such news. I will make a goodbye party later.}

{140}{}{Okay, now tell me about other settlers.}
{141}{}{Who do you want to talk about this time?}
{142}{}{Let's talk about something else.}

{143}{}{Goodbye party? But he was trying to get you into bed!}
{144}{}{That doesn't mean I should treat him like shit now. In our time you have to bear a lot of different stuff. I've had worse things happening.}

{145}{}{Is it true that Birch gave you clean water?}
{146}{}{Yes! Surprising, isn't it? But I think he's just trying to make an impression. The man needs the feeling of importance, you know?}

#Арсенал Мэрилин
{150}{}{Nice arsenal you have in that closet there...}
{151}{}{Yeah. Uranium City has seen many "cowboys" that chase wealth, and when the time comes to pay the dues, many have nothing but a gun on them. That's where the collection comes from. Not the best selection, but at least we always have something to protect ourself with, from unpleasant visitors.}
{152}{}{I want to buy this collection.}

{153}{}{Not a bad idea. We didn't have problems disposing of the arsenal in the past. We would take the best ones with a caravan to Reno, the rest was picked by the miners with the payment. But now - none of that. So, you know what, [scratches ear in thought] I will sell all these goods for 1500 bucks.}
{154}{}{I'll buy! Here is the money.}
{155}{}{[Lively] What, really? Great! It's open, you can take everything you see there.}
{156}{}{Outstanding.}
{157}{}{Too expensive! For this junk I will pay 300 tops.}
{158}{}{Is that so? That won't even cover the damages the previous owners caused. 1500 is almost a gift! No-o, no deal.}
{159}{}{Think. New workers won't be here anytime soon, and there is no more trading with Reno. This way you will at least get something out of this junk.}
{160}{}{[Sights heavily] You're right. Even if I hire a caravan or take the weapons myself, I will lose more money on transportation... Okay, let it be 300.}
{161}{}{Smart choice. Here 300 bucks.}
{162}{}{Oh, easy! You've done so much for us, that I won't regret a bit giving all this to you. Take it! The closet is open.}
{163}{}{Thanks!}
{164}{}{Not that fast! You shouldn't have swung your fists around the bar. Now you won't get anything for just like that. We're done.}
{165}{}{Oh, easy, sheriff! You need it more anyway. Take it! It's open.}

#Мясо драконов
{169}{}{You're welcome. Anything else?}
{170}{}{I see your menu got bigger?}
{171}{}{Well, we found the remains of the earth dragons and thought that it would be a shame for them to go to waste.}
{172}{}{And... How is it?}
{173}{}{Nobody has been poisoned yet. And the meat is much more nutrient than brahmin's. Besides, we are sick of eating the same stuff all the time.}
{174}{}{It seems this is not just meat. Can you tell me the recipe?}
{175}{}{It's all simple - [tells with excitement] the meat is mixed with pepper and salt, then is poured over with bramin milk. Then the cutlets are cooked in maize oil and wrapped up in maize bread with greens. Sounds tasty, isn't it?}
{176}{}{Well, worms, of course, are edible too. Especially when there is nothing else to eat. Can I, uh, have some?}
{177}{}{Eww, disguising! These worms could crawl anywhere, and you eat them! Ew! Ew! Ew!}
{178}{}{Sure! Here have a plate, no charge.}
{179}{}{Oh no! This is really delicious. Here, try some on the house.}

#Услуги
{180}{}{Can I rent a room?}
{181}{}{Yes. 50 bucks and you can have a room for the night.}
{182}{}{Do you have anything to eat?}
{183}{}{I only can offer meat and Rot Gut. I keep clean water for myself, sorry.}
{184}{}{Okay, let's trade.}
{185}{}{Nothing I need.}
{186}{}{That's all? One can starve like this.}
{187}{}{Indeed, I want more.}
{188}{}{That's enough. let's talk about something else.}
{189}{}{That will be enough. Now excuse me - I have things to do.}

#О городе
{199}{}{No big crowds of customers or tourists, which is damn great. Where do I start, sheriff?}
{200}{}{Would you mind to talk about this settlement?}
{201}{}{No big crowds of customers or tourists, which is damn great. Where do I start?}
{202}{}{Enough about the town, I need something.}
{203}{}{Will continue another time.}

{204}{}{Where can I have fun here?}
{205}{}{No.}
{206}{}{Nothing at all? No slot machines, no shooting, no...}
{207}{}{Erm, okay.}
{208}{}{Anything else?}
{209}{}{Hmm. I don't get it - are you fooling around or trying to make an impression? Fine, doesn't matter. Look around - this is *working* settlement. People came here to mine ore and many of them died of their greed or stupidity. And now you come here and ask if there is anything to do here for fun. I suppose, you were much luckier in your life.}
{210}{}{Fine, what if I find something myself for entertainment?}
{211}{}{Fine. forget it.}
{212}{}{Now hold it right there! No rivalry or shooting in my place! This is a decent establishment. Anyone that doesn't agree with it I will throw outside myself. Go fight somewhere else.}
{213}{}{You - throw me outside? Ha-ha-ha! Be careful not to hurt yourself, little girl.}
{214}{}{Don't worry, it still won't stop me. I've been beating boys since I was a teenager.}
{215}{}{Uh, you fought boys?}
{216}{}{Damn right! They all thought that strength could solve every problem. And? Couple of moves - and even if I don't carry a ton of muscle, the end is always the same: tears, whining, and crying to mommy. Ha, those were the times!}
{217}{}{This changes things. Let's leave everything as it is.}
{218}{}{I don't give a shit - I do whatever I want. you are just a mere annoyance to me!}
{219}{}{You! I should've thrown you outside as soon as you started. Fucking imbeciles, all you do is brawl muscles around! Do you know what? Any of my stuff will cost twice as much for you. Is that clear? Damn right!}

{220}{}{What is that building across the street?}
{221}{}{Another question.}
{222}{}{Miner's guild office. Locked, it's dark and there are rats inside. Nothing to do there. In the past it was the most lively place in Uranium City, not counting the mine. Now people are gone and nobody goes there.}
{223}{}{Tell me about the outskirts.}
{224}{}{You can say we are on the edge of the civilization. And, honestly speaking, I like it. In the best-case scenario a caravan from Hub will pass through, but mostly we are cut off. Everyone tries to get to new Reno... Or away from it.}
{225}{}{Tell me about the mine.}
{226}{}{We have one mine here. From pre-war times. We have been mining uranium ore for Mr. Wright in New Reno for more than a year, when these mutants came and ruined everything. As a result - the settlement is mostly abandoned, the ore is unrefined, and we try to do something more profitable. Farming, for example.}
{227}{}{How did it all started here?}
{228}{}{From Mr. Wright and his sons. He decided to revive the town's power plant in New Reno and sent his sons to the mines. They liked Uranium City, because there was some, albeit primitive, technical equipment. Then the miners guild was created. Slaves were the workforce at first, but it turned out to be more expensive than to hire workers. So we lived more than a year like this. And lived well.}
{229}{}{I don't get one thing - how people worked here under constant radiation?}
{230}{}{Good question. Nelson would even glow at night after the mines. You could save some money on electricity with him, ha-ha!}
{231}{}{Is the mine so radioactive?}
{232}{}{Well, not as much as you can think. There is no refined uranium there, only ore. The real radiation was where the ore was processed. And yet it's a sore point for Uranium City. When everything were under Wright, the slaves and free mercenaries worked here. They were prone to make... sacrifices. After all, while being irradiated, you can explore more than a year, until the disease takes its toll. And during this time you can put together enough to feed one's family - or burn your short life out bright and interesting. That's not too bad in our time.}
{233}{}{Bright and interesting?}
{234}{}{Oh, so much happened here! But it's all in the past now, when the settlement was full of people.}
{235}{}{And how they managed to restrain the radiation sickness for so long?}
{236}{}{Well, the guild weren't stupid you know, they made schedule and rules. You should've worked in rubber gloves and boots, wore mask, removed all metal off you before entering. And of course, there were normatives of working hours. And those that would forsake their health for the money were responsible for the outcome. Typical schedule was 14 hours, then everyone came to my bar for drink. The Rot Gut was flowing in rivers!}
{237}{}{Right.}
{238}{}{Hmm. Strange, the same thing the stranger from the south asked me. He, I think, is in his room. Talk to him if you're interested.}
{239}{}{Great, at least I know something now.}

#Текущая ситуация
{250}{}{We need to discuss the current situation in Uranium City.}
{251}{}{I'm listening.}
{252}{}{What really happened here?}
{253}{}{People started to go missing in the mines, soon we discovered deep loosening in the sandstones and remnants of clothing. Then the rumors about flesh-eating worms started to spread around, but only few, like Nelson, assured they really have seen them.}
{254}{}{That's it?}
{255}{}{Well, then the workers scattered. They didn't believe so much in the mutants, but thought this is how the guild gets rid of workers in order to cut costs. When the miners became few, Wright got furious. Everyone ran away, no one came back - the rumors did the rest.}
{256}{}{Right. Now about something else.}
{257}{}{Tell me once more about what happened here.}
{258}{}{}
{259}{}{Why don't you move to Reno or somewhere else, somewhere better?}
{260}{}{Everyone says that - if it's bad here, then we should get out of here to where it's better. But this is my home! And you know what? If it smells bad here, then I myself will clean the shit up.}
{261}{}{Okay. But that's not all.}
{262}{}{What must be done to restore the place?}
{263}{}{Oh, it won't be simple. First, we need to get rid of the monsters, whoever they are. Second, need to decide the mine ownership. Third - to bring back at least some working force. It's all complicated.}
{264}{}{Complications does not scare me. I will deal with it!}
{265}{}{Really? That's great. I don't know what you have in mind, but the mine will need a lot of work, believe me.}
{266}{}{I will manage it somehow. Now let's make something more clear.}
{267}{}{Who should I talk to about the monsters?}
{268}{}{What is the problem with the mine ownership?}
{269}{}{What kind of workers we need to bring back to get started?}
{270}{}{That's not all that interest me.}
{271}{}{Nelson tracks them down for a long time. If anyone knows something about them, then that's the man. I've heard that there are three monsters and they navigate by sound.}
{272}{}{I heard, that Wright went bankrupt because of the problems with the mine, he can't even hire a caravan to our city. Raises the question, how will he manage the production. Now Nelson, even little strange, at least knows the mine like the back of his hand. Wright decided to get rid of him and his gang to have less problems. Only that didn't help him.}
{273}{}{Let me tell you about everybody.}
{274}{}{The mutants are finished! All three corpses lay dead near the entrance to the mine.}
{275}{}{This gives hope! I don't even know how to thank you. Only to give you some Rot Gut on the house. Here [Gives you the bottle and some beef jerky]}
{276}{}{Somehow I don't see you too much excited.}
{277}{}{Ahh, sorry. So much stuff to do, even without the monsters, that the head goes spinning.}
{278}{}{Thanks, see you later.}
{279}{}{Joseph - the one of the most adequate guild administrators. He's the only one that can organize the production instead of letting it loose. The tough part is that after the trouble with the mine no one can find him. It seems he hides from Mr. Wright, or, perhaps, he was already found by him.}
{280}{}{The others?}
{281}{}{Carl - the operator of refinement ore machine. Some said that he went to Reno to live, somewhere in the slums. It seems to me that his wife doesn't want him to come back here.}
{282}{}{Michael - a guild supplier. He too decided to go back to Reno to give apologies to Wright. I don't know what happened to him.}
{283}{}{You know, those will be enough for now.}
{284}{}{Then let's talk about something else.}
{285}{}{It seems everyone s here?}
{286}{}{Oh, that's right! Things are getting better. Just like in good old times.}
{287}{}{Great. Let's talk about something else.}
{288}{}{But now Nelson is dead and no one is here to help with an advise.}
{289}{}{Yes, I heard, sad story. Hmm. Oh, I think Nelson proposed to tie dynamite to Lewis Birch and send him into the mine. Doubt that will work.}
{290}{}{Monsters won't bother you anymore... [tell the details]}
{291}{}{Now that's the good news! And you did that all alone? You're a great person. Too bad there is nothing to reward you with. And there is still a lot of work ahead of us. But I can share some of my savings. Here, 300 bucks, I hope they will at least somehow compensate you work.}
{292}{}{"Thanks" will be enough. No money needed - you need them more than me.}
{293}{}{Money - it's everything I need!}
{294}{}{What, really? just like that - you refuse? Great! But let me at least give you a drink on the house.}
{295}{}{Thanks.}
{296}{}{I knew, you will say that.}
{297}{}{Yeah. Bye.}

{298}{}{Wait! you did so much, would you leave us like this? Perhaps, this won't sound that great, but I would like to see you as our sheriff. I even have a badge for this case.}
{299}{}{I will be honored to be a sheriff of this town. Thank you for the trust, Marilyn.}
{300}{}{Thank you, Marilyn, but I already serve another city and I can't betray it. Leave this badge to yourself - you've earned it.}
{301}{}{[Marilyn takes the badge and pins it on your chest] Let it remind you of good deeds and order! By itself this title doesn't require anything, but when you will be in our parts - don't forget to stop by and ask, how the things are going. Okay, sheriff?}
{302}{}{Okay, Marilyn. I won't let you down.}
{303}{}{Wow, so shiny!}
{304}{}{Me?! I'm a local sheriff for all this time, damn it. But - I understand. No harsh feelings.}
{305}{}{None. Farewell.}

#Музыкальный автомат
{310}{}{Is this furniture with lights here for decoration?}
{311}{}{A jukebox? Workers once became bored and dragged this junk from the warehouse. I warned them that the machine doesn't work. Nobody managed to fix it, so it's just sits there.}
{312}{}{Can I look at it?}
{313}{}{Well, if you know what you're doing, then yes.}
{314}{}{Okay.}
{315}{}{Jukebox is now working.}
{316}{}{Oh, wonderful! We would get very bored here. Now it will be easier. Thanks. Here, take some on the house.}
{317}{}{Take care.}

#Квест на владельца шахты
{318}{}{Now Nelson owns the mine. Are you happy?}
{319}{}{The mine got back to Wright, and he will restore it soon.}
{320}{}{Birch decided to take over the mine. What do you think?}
{321}{}{Of course! At least I know what to expect of him, we know each other for so long. And considering his mining experience, Uranium city has good chance to recover. But on the other side, Nelson is not too reliable, for example, he can't make deal with people. So - someone must take part of his work. In the end it is better than nothing.}
{322}{}{Not surprised. he got money, connections and place to sell to. This is a profitable decision. On the other hand though, he will make new calls in here and will change the working force. Oh, I hope it won't have anything to do with me. Still, I like that the things started moving.}
{323}{}{Birch? This one can do a lot of things, if he wants to. I mean, not him, but the organization he represents. They will bring some order here. I'm just worried about one thing - it's not in their interest to restore the city. They will come here with their guns and resources, take all the ore - and then pack things and leave, leaving us with nothing. But, sooner or later, the city will die anyway. I just want for it to last a little longer.}
{324}{}{Your opinion is clear. See you.}

#Weapons in hand
{400}{}{I told you, no weapons.}
{401}{}{Oh, sorry, I forgot. [remove the weapon]}
{402}{}{My weapons are always with me!}

#Female character
{1114}{}{Yes. I know. And you're just a wanderer passing by. So how can I help you with?}
{4401}{}{Oh, sorry, I forgot. [remove the weapon]}
