{100}{}{You see Nelson.}
{101}{}{You see a ghoul, burned through with hellish mixture of radiation, Rot gut and huge ambitions to big earnings.}

#Ïåðâûé äèàëîã
{110}{}{[An old ghoul stands in the doorway, looking at you, pretending to be a cowboy from a movie] Who are you? if Wright sent you for negotiations - then get the hell out of here, while I'm in a good mood.}

{111}{}{Easy, I have no interest in your beef with some Wright.}
{112}{}{Then what the hell are you doing here?}
{113}{}{I'm just traveling and looking for a place to stay the night.}
{114}{}{Is that so? Fine, you can enter. But keep in mind - I'll be watching you. And don't think that I'm so blind, as I may seem in this ghoul skin.}
{115}{}{Uh, right. Whatever you say.}

{116}{}{No negotiations. I'm the boss here, until I find out what is what.}
{117}{}{[Opens widely one of his eyes, which makes him look even more crazier, than before] Hmm... Say whatever you want, it won't solve the problem. The big daddy from the big city won't deal with local problems, even with his loads of money. So, if you want to try that - go on ahead.}
{118}{}{Well, then you're no problem to me. Take care for now.}
{119}{}{You confuse me with someone, I don't know any Wright.}

#Ïðè ïîñåùåíèè êàðòû íà ìàøèíå
{150}{}{What is this? Corvega? Meh - a pickup, 72' model. Shitty car.}
{151}{}{Well, better than nothing...}
{152}{}{What would you know about cars, rotting corpse?}
{153}{}{Don't you dare insulting the best car in Nevada!}
{154}{}{[Mumbles] If today were 77th, I would show you what a real car is. But yeah, in our times even a piece of junk with wheels is good enough.}
{155}{}{Do not exaggerate. Many have underestimated me in the past. And I'm still alive. And I must say, this doesn't change the facts... Alas, I forget sometimes, the times we live in. If there would be 77th, I would show you then, what is a real car. But yeah, in our times even a junk on wheels is good enough.}
{156}{}{Oh yeah, I forget sometimes, the times we live in. If today were 77th, I would show you, what a real car is. But yeah, in our times even a junk with wheels is considered good enough.}
{157}{}{I would prefer it instead of walking anytime, be sure.}

#Îñîáàÿ âåòêà äëÿ æåí. ÃÃ
{170}{}{Boop? Is that you? Baby, let me give you a ride on my wheels! Oh... Nevermind, forget it...}
{171}{}{Who is Boop?}
{172}{}{Hey, can we have some privacy?! It's not your business!}
{173}{}{Er, whatever...}

#Ïðî Áåð÷à
{180}{}{You know, Lewis Birch is up to something.}
{181}{}{Amazing - how can you and I think the same things about him! Although, why would you talk about it?}
{182}{}{He asked me to deliver some encoded message to Hub. That bastard is sly. We should throw him out of the City.}
{183}{}{You know, I will check it again first.}
{184}{}{Secret message? Ha! I got this piece of shit! He won't get away this time. Hey, guys, settle up, there is an idiot that needs to be thrown out of Uranium City!}
{185}{}{Tee-hee. Be careful.}
{186}{}{Ha-ha! We drove him away. He was in such a hurry, that left his stuff in the room. Such a cretin!}
{187}{}{Aha. That was fun, but it's time for me to go.}
{188}{}{It should be useful for you to know, that he send a report to Hub with a request of people to come here to take over the City. I've seen the report with my own eyes.}

#Îñíîâíîé äèàëîã
{200}{}{What do you want?}
{201}{}{Tell me about the problem with Wright. What happened?}
{202}{}{I want to know more about you - you're interesting to me.}
{203}{}{What can you tell about Uranium City?}
{204}{}{Why are there so few people living here?}
{205}{}{Nothing, everything is good.}
{206}{}{Between us? The damn swarm of worms shat between us. And each has shat so much, that me or Wright can't even approach. Though, I think sometimes, he's just disgusted by my looks.}
{207}{}{Yes. I'm Nelson. Remember that.}
{208}{}{This is my home, and that's it. Lived here almost my entire life. I don't want to travel anymore, not even to go back south.}
{209}{}{You really want to know? What if I tell you they don't belong here? Though yes, most of the locals simply died... Not because of me, don't look at me like that.}

{210}{}{Tony lays lifeless in your room.}
{211}{}{I don't like bad news... Yes I knew, he hasn't much time left. I hoped, he will go through ghoulification, like me. But no!}
{212}{}{Let's leave it for now, there are other subjects.}
{213}{}{That is all I wanted to know.}

{214}{}{Everything's good, sheriff?}

{220}{}{Tell me about the mutants in the mines.}
{221}{}{What will you do with the mine now?}
{222}{}{And what are you going to do with it?}

{223}{}{My little slippery worms. I dream to catch at least one, to cook it on fire. But they are so sneaky that it's not easy. Difficult task, definitely.}
{224}{}{How many of them are there?}
{225}{}{Where did they came from?}
{226}{}{Where are they located?}
{227}{}{How can I attract them to surface?}
{228}{}{What are you going to do with them?}

{229}{}{I know how many. Three. Surprised? Yes, I learned a lot about them.}
{230}{}{Straight from hell. The entrance there have been dug by miners, at the far end of the mine.}
{231}{}{That's what I think - they live underground, meaning they can move around only in friable soil. And, for some reason, they always stick close to the mine. I know, it may sound strange, but look at me - I'm alive, because I eat uranium dust for breakfast. I'm sure, they do the same.}
{232}{}{Use your brain or whatever you have there. Maybe perfume? Of course not - they can't smell anything down there. Perhaps, nice dress? Oh, didn't guess it - they have no eyes. Then by dancing around with tambourine and maracas? And I will tell you - yes!}
{233}{}{I wanted to befriend them, but they steer clear of me, no matter how much I tried. I don't know why. The only option is to put someone in the middle of the field with a dynamite, but for some reason everyone refused. Hmm, you know, you could do pretty well.}
{234}{}{I placed something to make sound and vibration and attract the mutants. I wouldn't mind few more guns for the fight.}
{235}{}{Do you know where to get dynamite? I want to make a brahmin to go inside with it.}
{236}{}{I want to hunt the mutants. I wouldn't mind few more guns for the fight.}

{237}{}{How about something stronger? I'm sure you have some dynamite for mining purposes.}
{238}{}{In the mine there is a storage with dynamite, and I have the key for it, but I myself won't go there. If someone brings it here, then I could make a dynamite pack, but... [thinks]}

{239}{}{Right. See you.}
{240}{}{Just a few simple questions.}
{241}{}{Such as?}

{242}{}{Funny idea. The only one that has a decent firepower here is Kelly. talk to him, perhaps, he will agree to go with you.}
{243}{}{I know. It's in the mine, and I have the key from the storage room, but I won't go there myself. I can assemble a whole dynamite pack. Oh, I see, you have a brahmin... Damn, why it has to be Betty!? Ah, fine. Nothing that can be done.}
{244}{}{Give me the key, I will get the dynamite.}
{245}{}{Not so fast, monster! I spent the best years of my life in this mine. And you want to blow it all up? I don't want to dig it back afterwards. The most important - there is not much dynamite left. This is the last supply. What can you say about that?}
{246}{}{I'm a demolition expert. You can trust me.}
{247}{}{Yes, it's a risk. But understand, while mutants are here, you have nothing to be so concerned about anyway. Who wants your dynamite, if even you are afraid to go get it? At least we have a chance.}
{248}{}{I have nothing to assure you.}
{249}{}{Fine, I believe you. Here is the key. And... Be careful there. Bring me the dynamite sticks, I will assemble them, to be sure in the results. You can never know...}
{250}{}{That was the right decision, Nelson.}

{251}{}{I managed to get few dynamite sticks. Can you assemble it?}
{252}{}{Sure. Easy. I need five dynamite sticks, then the force of the blow will be enough to bring down the mine right on those worms.}
{253}{}{Here five sticks.}
{254}{}{Wait. it won't take long.}
{255}{}{[Wait]}
{256}{}{Here, done. I hope, you know, what you're doing.}
{257}{}{Good job, Nelson.}
{258}{}{I'll talk to him later, for now answer some questions.}
{259}{}{You know, Tony would trust me...}
{260}{}{If I even managed to beat that brawler at the bar three times, then to go get the dynamite is pretty easy.}
{261}{}{I did what you couldn't do all this time - killed the monsters.}
{262}{}{Hmm. Such irony, just when I started to like them. It's always hard to say goodbye to your loved ones. But I cannot but thank you. Good job.}
{263}{}{Good!? You should praise me for it!}

{270}{}{While the worms are mangle at our feet, nothing good will come out of the mine.}
{271}{}{}
{272}{}{}
{273}{}{Listen this one, from the south, how is his name... Birch. He promised to bring a shipment of dynamite and he's interested in the restoration of the mine, so now we have a future... I think.}
{274}{}{Me - nothing. This mobster from big city found a way to threaten us with big explosives. Resisting is useless. I, think, I will move from here, while I'm still in one piece. That mobster memory - you know... Doesn't forget.}
{275}{}{Well, Now we have nothing to fear, with so many explosives in our hands. So everything will be okay... At least, while I'm in charge.}

{276}{}{Now, when the worms are dealt with, all that remains is to gather new team. I... We will have to work very hard.}
{277}{}{ The most important thing needed right now is explosives. A lot of it. If we have it, we will keep our independence from the big daddy from the City.}
{278}{}{What kind of explosives do you need?}
{279}{}{About the team - who do you have in mind?}
{280}{}{It seems you have everything that is necessary. So - will you restore the Uranium City?}
{281}{}{Hey, you're right! We have people, tools too. First we must refine some ore and sell it to Wright. Then we will restore our connection with south and the east. We must earn some money to start, and attract workers. Now, everyone to their places! Get to work!}
{282}{}{Damn, little bossy huh...}
{283}{}{Three people first. talk about it with Marilyn, she knows better how to find them.}
{284}{}{I think Wright hired a group of prospectors, to get C-4 box from the military base. It will be enough for now. The question is who are they and where is the base.}
{285}{}{It happens, that I have everything, you need. Here.}
{286}{}{What - just like that you will give it away? Interesting. Listen, I've learned in my life, that nobody works for free. I'll give you a 1000 bucks for your trouble.}
{287}{}{Thanks for the money. See you, Nelson.}

#Female character
{1188}{}{It should be useful for you to know, that he send a report to Hub with a request of people to come here to take over the City. I've seen the report with my own eyes.}
{1232}{}{Use your brain or whatever you have there. Maybe perfume? of course not - they can't smell anything down there. Perhaps, nice dress? Oh, didn't guess it - they have no eyes. Then by dancing with tambourine and maracas? And I will tell you - yes!}
{1233}{}{I wanted to befriend them, but they steer clear of me, no matter how much I tried. I don't know why. The only option is to put someone in the middle of the field with a dynamite, but for some reason everyone refused. Hmm, you know, you could do pretty well.}
{1234}{}{I placed something to make sound and vibration and attract the mutants. I wouldn't mind few more guns for the fight.}
{1249}{}{Fine, I believe you. Here is the key. And... Be careful there. Bring me the dynamite sticks, I will assemble them, to be sure in the results. You can never know...}
{1261}{}{I did what you couldn't do all this time - killed the monsters.}
