{100}{}{You see Kelly.}
{101}{}{You see a miner armed with a rifle. His look is cold and piercing.}

{110}{}{Sheriff?}
{111}{}{Yes?}
{112}{}{Bye.}

{113}{}{I hasten to break the news of Tony's death.}
{114}{}{[Kelly didn't even flinch] Thanks, I'll keep it in mind.}
{115}{}{Aren't you a cold-blooded guy. Okay, I'll go tell everyone else.}

{116}{}{I'm going to finish off the mutants in the mine. Are you with me?}
{117}{}{Do you really know what to do? I'm not sure I should help you.}
{118}{}{So, will you help me?}

{119}{}{Maybe you can advise something in terms of weapons to fight mutants?}
{120}{}{If you're not good with a gun, stay away from the mine. Worms are a serious threat, you can't take them down with a single bullet. Ask Marilyn for access to the arsenal, Nelson for dynamite, or just crack the damn safe in that office. Oh yeah, Nelson should have some ammo left.}
{121}{}{Marylin has an arsenal?}
{122}{}{Nelson holds dynamite in reserve?}
{123}{}{What safe you were talking about?}
{124}{}{Could you tell me about ammo, please?}
{125}{}{The cabinet in the bar, easy to see. Only she wouldn't give it all away just like that. However, there's nothing really powerful.}
{126}{}{Yes, the mine has a room where Nelson pulled the last stocks of dynamite. Very little of that left. }
{127}{}{He carries the key to the doors with him, on his neck. So you have to negotiate somehow.}
{128}{}{Safe in the guild's building. We've had our eyes on it for a long time, but who would open it? The irony is that everyone knows about the contents. The owner died safely in the mine when the mutants first appeared. He didn't yet know what had happened underground, thought it was another drunken prank by the workers, so he left the submachine gun and ammo in the safe and went downstairs. That was it.}
{129}{}{I saw Nelson making ammo when he still had a sawed-off shotgun, surely he hid them somewhere at home. If I had the skills and the bench, I could make coin shot ammo for a shotgun. Just what you need for shooting worms.}
{130}{}{Thanks for the help, this should be enough.}

{131}{}{You can use me as a bait and shoot the mutants yourself.}
{132}{}{I have a brahmin as a bait.}

{140}{}{Look, two of us could handle it better. I'll be a bait, and you'll be shooting from afar.}
{141}{}{Good thinking. But keep in mind - if these creatures start to chew you, I'll just watch the show to the end and go back. I don't want to waste ammunition in vain.}
{142}{}{Go to the place, I'll be right after you.}
{143}{}{I'll tell you when to move. Just stand here for now.}

{144}{}{Don't get distracted, they're somewhere nearby.}
{145}{}{You need ammo?}
{146}{}{Good.}
{147}{}{Nicely done. Three corpses - this is the amount Nelson told us about.}
{148}{}{If you have a .30-caliber ammo, put it in my backpack. It'll be very useful.}
{149}{}{We talked. That's enough. Let's get busy.}

{150}{}{I'm just wondering how someone like you ended up in this place.}
{151}{}{Almost by accident. I had to find a quiet place for living. But this is none of your concern.}
{152}{}{I'll tell you how it is - it's weird. You have a good weapon, ammunition, excellent marksmanship and a cold calculating mind - and still you are rotting in a half-destroyed settlement. What gives?}
{153}{}{I never thought I would meet a detective here. Well, you already guessed that I'm hiding. Someone put a hit on someone, and I took the job. Now I need a quiet place to sit tight. But don't try to fish the details out of me - I won't say anything.}
{154}{}{You have gained experience for applying the methods of investigation, justifying the deserved reputation of a private detective.}
{155}{}{Alright, whatever you say.}
{156}{}{Maybe we'd talk about something else?}

{157}{}{You are good with rifles, am I right? The gun you have is quite unusual.}
{158}{}{What's your opinion on Nelson?}
{159}{}{Why didn't you leave, like everyone else?}
{160}{}{An old, but reliable rifle. I bought it in Wind of War. They usually keep good guns for themselves and sell whatever junk is left. I was lucky enough to catch one of the better ones they had in stock. This one, however, has flaws, too. As for skills... I have to count every shot because bullets don't come cheap. That's how I trained.}
{161}{}{I try to stay away from crazy ones, but this one seems smart. At least I don't see anyone better at organizing things here.}
{162}{}{I need a quiet place to live. I do not like big cities.}
{163}{}{Wind of War? Can you show me where it is?}
{164}{}{Only if you have a map... It's here, in the east, right in the middle of the ruins of the old town.}
{165}{}{Thanks.}
{166}{}{I try to stay away from crazy ones, but this one seemed smart. At least I don't see anyone better at organizing things here. But is it important now?}

{167}{}{"Flaws", you say? What's the problem?}
{168}{}{Misfires have been occurring more often lately. Probably a problem with the bolt. I'm periodically cleaning the rifle, but it doesn't help much. Do you know anything about guns?}
{169}{}{I have some experience. Let me take a look, let's see if I can fix it.}
{170}{}{If the problem is the mechanics, it is on my part. Just give me a screwdriver and I'll get down to business.}
{171}{}{Too bad it's not my profile. Let's change the subject.}
{172}{}{[Disassembling the receiver, you found and fixed the malfunction of the trigger mechanism] Thanks, hope it helps.}
{173}{}{My pleasure. Let's talk about something else.}
{174}{}{You're always welcome. And now I must go.}

{1153}{}{I never thought I would meet a detective here. Well, you already guessed that I'm hiding. Someone put a hit on someone, and I took the job. Now I need a quiet place to sit tight. But don't try to fish the details out of me - I won't say anything.}
