{100}{}{You see Juan.}
{101}{}{You see a strong miner with large exposed muscles.}
{102}{}{Leave me alone! I'll drink myself to death without Nelson.}
{103}{}{It's a test, yo!}

#Äèàëîã
{107}{}{Make yourself at home.}
{108}{}{Somehow you don't look particularly friendly. As if your hands itching for a fight.}
{109}{}{Would the sheriff waste his time on empty talk?}

{110}{}{[Scratching his long unshaved chin with a hairy hand] You will call me Juan. And I don't give a shit what you think about it. And if you want to argue, I'm always at your service.}
{111}{}{I see you're a skilled debater.}

{112}{}{[Examines his thick palms] These hands handled so many arguments that yours will be a piece of cake. [He folds his arms and looks at you dismissively and sharply] Don't believe me? You have a right not to. It's never too late for some proof.}
{113}{}{Good. I accept the challenge! Where would you like me to beat your face?}
{114}{}{I do not want anyone to prove anything to me right now. Let's just talk?}
{115}{}{I don't like this chat, so I leave.}

{116}{}{If you want to say something, don't mumble, speak loud and clear. We don't like windbags here.}
{117}{}{I recall you wanted to argue who's stronger. So, did you change your mind yet?}
{118}{}{Who are you?}
{119}{}{How did you end up here?}
{120}{}{How do you feel about Nelson?}
{121}{}{Enough chatter for today.}

{122}{}{You're hard of hearing? Juan, I told you already. I worked at the mine until it closed. I could still work now, but there's no one to pay me.}
{123}{}{I came from Vegas, right after they stopped giving me jobs. They said that I have a bad temper. Ha! For real?! They should regret that they got rid of me.}
{124}{}{G-great fellow. I immediately loved him as a brother. Just try to touch him and you're dead, hear me? And then - who else but him can organize everything here?}
{125}{}{[Scratches his chest with his thick fingers and assesses you] I'm not a masochist. It's not for me to get into fights for no reason. But if you want to try to beat me in arm wrestling, I'm at your service. Right now, on Marilyn's desk. Whoever loses pays 100 bucks. How do you like that proposition?}
{126}{}{Excellent! I place my bet and accept the challenge!}
{127}{}{I first ask a few questions.}
{128}{}{Can't do right now. Later.}

{129}{}{[Whistles] Hey, everyone in the bar! Look! I'm about to give someone hell.}
{130}{}{[Go to the bar, sit at a table and start a match]}
{131}{}{Wouldn't Marylin mind it?}
{132}{}{Probably she would. But I didn't ask her.}

{133}{}{Well? Suckers don't get along here, and you seem to want to prove you're not one of them.}
{134}{}{I'm not healthy, cough-cough, maybe next time.}
{135}{}{I just changed my mind. And I don't care what you think about it.}

#Ïðî Òîíè
{140}{}{Tony passed out.}
{141}{}{It must've happened someday. I hope he gets a place in hell. Somewhere near the exit.}
{142}{}{Let's change the topic.}
{143}{}{That's all.}

#Ñîñòÿçàíèå
{150}{}{*Ar-r-rg!*}
{151}{}{*Hmmm-m!*}
{152}{}{*Hy-y-y-a*}
{153}{}{A-ARG, YOU FUCKER!!}

{154}{}{You won the arm wrestling match.}
{155}{}{You lost the arm wrestling match.}
{156}{}{Phew... No one could beat me in this for a long time, then you just showed up! Where did you come from? Okay it doesn't matter. Here are your winnings.}
{157}{}{Here, you'll think twice before messing with me.}
{158}{}{Ha! I thought you're a serious opponent. [Takes your money] Yeah, even geckos give me more trouble.}
{159}{}{It's definitely not my lucky day.}
{160}{}{And you just can't get enough, can you? Well, let's rematch. Here and now, on Marilyn's table. Same bet - $100. Satisfied?}

{161}{}{What the hell! Again! That's it, I will no longer challenge you, enough of this. Take your winnings and don't even talk about it, okay?}

#Female character
{1135}{}{I just changed my mind. And I don't care what you think about it.}
{1156}{}{Phew... No one could beat me in this for a long time, then you just showed up! Where did you come from? Okay it doesn't matter. Here are your winnings.}
