{100}{}{You see Romantic.}
{101}{}{You see a miner. Everybody call him Romantic for some reason.}

{110}{}{A nice weather today. Good for a good cause, isn't it, Sheriff?}
{111}{}{How are you, wanderer?}
{112}{}{Bye.}
{113}{}{I have news - Tony passed away.}
{114}{}{Sad news. But we all knew he's going to die someday. Wasn't expecting it so soon though.}
{115}{}{That's all.}

{1111}{}{How are you, wanderer?}