{100}{}{You see Juan.}
{101}{}{You see a strong miner with large exposed muscles.}
{102}{}{Leave me alone! I'll drink myself to death without Nelson.}
{103}{}{It's a test, yo!}

#Диалог
{107}{}{Make yourself at home.}
{108}{}{Somehow you don't look particularly friendly. As if your hands itching for a fight.}
{109}{}{Would the sheriff waste his time on empty talk?}

{110}{}{[Scratching his long unshaved chin with hairy hand] You will call me Juan. And I don't give a shit what do your think about it. And if you want to argue, I'm always at your service.}
{111}{}{I see you're a skilled debater.}

{112}{}{[Examines his thick palms] These hands handled so many arguments that yours will be a piece of cake. [He folds his arms and looks at you dismissively and sharply] Don't believe me? You're right for not believing. It's never too late to prove.}
{113}{}{Good. I accept the challenge! Where it will be more convenient to beat your face?}
{114}{}{I do not want anyone to prove anything to me right now. Let's just talk?}
{115}{}{I don't like this chat, so I leave.}

{116}{}{If you want to say something, don't mumble, speak loud and clear. We don't like windbags here.}
{117}{}{I recall you wanted to argue who's stronger. So, did you change your mind yet?}
{118}{}{Who are you?}
{119}{}{How did you end up here?}
{120}{}{How do you feel about Nelson?}
{121}{}{Enough chatter for today.}

{122}{}{You're hard on hearing? Juan, told you already. I worked in the mine until it closed. I could work even now, but there's nobody to pay me.}
{123}{}{I came from Vegas, right after they stopped giving me jobs. They said that I have a bad temper. Ha! For real?! They should regret that they got rid of me.}
{124}{}{G-great fellow. I immediately loved him as a brother. So just touch him - and you're dead, alright? And then - who else, but him, could organize everything in here?}
{125}{}{[Scratches the chest with thick fingers and assesses you] I'm no masochist. To scuffle without the reason is not for me. If you want to beat me in arm wrestling, then I'm at your service. Right now, on the table at Marilyn's. Who loses, pays 100 bucks. How do you like this option?}
{126}{}{Excellent! I place my bet and accept the challenge!}
{127}{}{I first ask a few questions.}
{128}{}{Can't do right now. Later.}

{129}{}{[Whistles] Hey, everyone in the bar! Now I'll make someone hell.}
{130}{}{[Go to the bar, sit at a table and start a match]}
{131}{}{Wouldn't Marylin mind it?}
{132}{}{Probably she would. But I didn't ask her.}

{133}{}{Well? Suckers aren't getting along here, and you seem to want to prove you're not one.}
{134}{}{I'm not healthy, cough-cough, maybe next time.}
{135}{}{And I just changed my mind. And I don't care what you think about it.}

#Про Тони
{140}{}{Tony passed out.}
{141}{}{It must've happened someday. I hope he gets a place in hell somewhere near the exit.}
{142}{}{Let's change the topic.}
{143}{}{That's all.}

#Состязание
{150}{}{*Ar-r-rg!*}
{151}{}{*Hmmm-m!*}
{152}{}{*Hy-y-y-a*}
{153}{}{A-ARG, YOU FUCKER!!}

{154}{}{You won the arm wrestling match.}
{155}{}{You lost the arm wrestling match.}
{156}{}{Phew... No one could beat me in this for a long time, then you just showed up! Where did you come from? Okay it doesn't matter. Here is my bet.}
{157}{}{Here, you'll think twice before messing with me.}
{158}{}{Ha! I thought you're a serious opponent. [Takes your bet] Yeah, even geckos give me more trouble.}
{159}{}{Probably not my lucky day.}
{160}{}{And you are just got not enough, are you? Well, let's have a rematch. Here and now, on the table at Marilyn's. The bet is the same - $ 100. Satisfies you?}

{161}{}{What the hell! Again! That's it, I will no longer challenge you, enough of this. Take the bet and do not even mention it, you got it?}

#Female character
{1135}{}{And I just changed my mind. And I don't care what you think about it.}
{1156}{}{Phew... No one could beat me in this for a long time, then you just showed up! Where did you come from? Okay it doesn't matter. Here is my bet.}