{100}{}{You see Tony.}
{101}{}{You see on of the Nelson's men. And he's clearly in a bad shape.}
{102}{}{You see on of the Nelson's men.}
{103}{}{  }

{110}{}{*Heavy coughs gushing around*}
{111}{}{The sick one is not quite sure about your actions.}
{112}{}{Do you even know what are you doing?}

{113}{}{Hey doc, I've never felt better! Thank you, goddammit. When I stand on my feet, the first thing I'll do is drink booze 'til I fall down again!}
{114}{}{Excellent, now share some information please.}
{115}{}{That's alright. Take rest.}

{116}{}{Huh? What's that?}
{117}{}{Huh? What's that? I'll do fine without it.}
{118}{}{Nothing.}

{119}{}{Tell me about Nelson. Who he really is?}
{120}{}{[Looks around] Don't want to talk about it. He's paranoid, but who else, if not him, could gain a foothold here and run the mine properly? Sometimes he behaves strangely, talks some nonsense, and then you think: "What's on his mind?". Don't know what to say. Some said he's from somewhere to the south, but no one really knows for sure, because he's been here for a long time. Longer than any of us.}
{121}{}{What do you know about local mutants?}
{122}{}{About what? Marylin? Ha-ha, joking, these creatures underground are just worms - that is, really big ones. One old miner said that the larvae were in the rock. When they were dug up, they started to grow and gain weight. Probably, radiation has something to do with it. But who the hell cares now?}

{123}{}{This miner suffers from the two diseases in a row - irradiation and tuberculosis.}
{124}{}{Tough case, can't do much without special medications.}
{125}{}{Symptoms of various diseases... I don't get it!}
{126}{}{You can't grasp the essence of the patient's sickness.}
{127}{}{Hardly a fitting solution.}
{128}{}{This skill won't help here.}
{129}{}{You managed to heal the patient. After a few more weeks of rehabilitation period, he should fully recover.}
{130}{}{I'm still alive, doc? So, I still have chances to get Marylin laid...}
{131}{}{You intravenously inject the drug into the patient's arm. Soon he will surely feel better.}
{132}{}{You intravenously inject the poison into the gullible patient's arm.}
{133}{}{You have already injected that drug. Second dose won't do anything here.}
{134}{}{It's now useless.}
{135}{}{Doc, you know what you're doing, right? I'm trusting you...}
{136}{}{Doc, I'm feeling so bad... Is this normal?}
{137}{}{Coughs... Was this really... A medicine... Doc?}
{138}{}{Looks like as if death took the patient naturally.}
{139}{}{Now rest.}
