{100}{}{You see Tony.}
{101}{}{You see on of the Nelson's men. And he's clearly in a bad shape.}
{102}{}{You see on of the Nelson's men.}
{103}{}{  }

{110}{}{*Coughs violently, splashing blood all over the place.*}
{111}{}{The patient is not quite sure about your actions.}
{112}{}{Do you even know what are you doing?}

{113}{}{Hey doc, I've never felt better! Thank you, I mean it. When I get back on my feet, the first thing I'll do is drink 'til I fall again!}
{114}{}{Excellent, now share some information, please.}
{115}{}{That's alright. Get some rest.}

{116}{}{Huh? What's that?}
{117}{}{Huh? What's that? I'll do fine without it.}
{118}{}{Nothing.}

{119}{}{Tell me about Nelson. Who is he really?}
{120}{}{[Looks around] I don't want to talk about it. He's paranoid, but who else but him could get a foothold here and run the mine properly? Sometimes he acts strange, says some nonsense, and then you think, "What's on his mind?" Some people say he's from down south somewhere, but nobody knows for sure, because he's been here a long time. Longer than any of us.}
{121}{}{What do you know about local mutants?}
{122}{}{About what? Marylin? Ha-ha, joking, these creatures underground are just worms. I mean, really big worms. One old miner said that the larvae were in the rock. When they were dug up, they started to grow and gain weight. Probably, radiation has something to do with it. But who the hell cares now?}

{123}{}{This miner suffers from two diseases simultaneously - radiation and tuberculosis.}
{124}{}{Tough case, can't do much without special medications.}
{125}{}{Symptoms of various diseases... I don't get it!}
{126}{}{You can't grasp the essence of the patient's sickness.}
{127}{}{Hardly a fitting solution.}
{128}{}{This skill won't help here.}
{129}{}{You managed to heal the patient. After a few more weeks of rehabilitation period, he should fully recover.}
{130}{}{Am I still alive, doc? Then I still have some chances to get Marylin laid...}
{131}{}{You intravenously inject the drug into the patient's arm. Soon he will surely feel better.}
{132}{}{You intravenously inject the poison into the gullible patient's arm.}
{133}{}{You have already injected that drug. Second dose won't do anything here.}
{134}{}{It's now useless.}
{135}{}{Doc, you know what you're doing, right? I trust you...}
{136}{}{Doc, I'm feeling so bad... Is this normal?}
{137}{}{Coughs... Was this really... A medicine... Doc?}
{138}{}{It looks like his death occurred by natural causes.}
{139}{}{Now rest.}
