{100}{}{You see Joseph.}
{101}{}{You see the administrator of the miners' guild.}

{110}{}{Thanks, you gave me hope, Sheriff!}
{111}{}{Thanks, you gave me hope!}
{112}{}{[You see the guild administrator. He looks much better and cleaner than before.] Oh, look who we have here! Someone who I'm always glad to see. I'm going to use this opportunity to sincerely thank you for giving me the chance to get back to a normal life. You gave us hope for the future. It's not often things like this happen in our lives. Thank you. I mean it.}
{113}{}{You're welcome.}
{114}{}{Well, I'm going to go clean up the office. There's an awful mess...}
{115}{}{See you around then.}
{116}{}{Oh, by the way, there is a weapon of the previous administrator in the safe. You can take it - a little reward for your efforts.}
