{100}{}{You see Carl.}
{101}{}{You see the operator of the ore processing machine.}

{110}{}{Hey, hey! What brings you here?}
{111}{}{I have a similar question - how was the trip?}
{112}{}{I wanted to ask how things are going.}
{113}{}{Bye.}

{114}{}{Well, my wife didn't even want me to leave the house, but I persuaded her and left her all my money. Pretty risky move, but you gave me new hope for life in this town. So I fully expect to get 'em back, even if I die from radiation after a year.}
{115}{}{Uh, a year?}
{116}{}{Well, people don't live long around here. And I have to work with the ore processing machine, you know.}
{117}{}{Tell me about your job.}

{118}{}{Yeah, not very good, really. The machine's automated computer broke down, Now I have to manually manage this hulking thing. It takes a lot of time, and I'm more exposed to radiation that way. I have to normalize my schedule and work only four times a day, with long breaks. If we had a supplier, he could probably find a part to fix the machine.}
{119}{}{Yeah, not very good, really. The machine's automated computer broke down, Now I have to manually manage this hulking thing. It takes a lot of time, and I'm more exposed to radiation that way. I have to normalize my schedule and work only four times a day, with long breaks. I ordered the needed part from our supplier, but the search will take some time.}
{120}{}{Now everything is just fine! The computer on the machine does all the work for me, and I don't have to sit in an irradiated room all the time. Thanks for your help, }
{121}{}{sheriff.}
{122}{}{wanderer.}
{123}{}{What kind of part is needed to fix the machine?}
{124}{}{There is a blown fuse. Not that it's such a rarity, but we still don't have one.}
{125}{}{I've got a fuse. Will this do?}
{126}{}{Exactly what I need! Listen, I can't pay for this thing now, but when the supplier shows up, he'll pay, he really will! Without this part I'm doing everything by hand.}
{127}{}{Exactly what I need! Look, I still can't pay for this thing, but our supplier can. Without this part I'm doing everything by hand.}
{128}{}{Then take it.}
{129}{}{I'll think about it.}
{130}{}{Thanks! Now I'm gonna work to the fullest. When the supplier shows up, he will repay your money. As for me - I owe you some rotgut.}
{131}{}{Thanks! Now I'm gonna work to the fullest. Ask the supplier in his office, he will repay your money. As for me - I owe you some rotgut.}
{132}{}{Goodbye.}
{133}{}{The operator looks worried, as you search for the item in your pockets.}

{134}{}{Near the mine stands a big mechanical machine for ore processing. You put raw ore in one side and get purified uranium and mountains of slag out the other. I'm in charge of that machine. The maintenance is more complicated than it seems. Besides, this job happens near irradiated ore.}
{135}{}{So why are you working there, if you're constantly being exposed?}
{136}{}{Because it's the only honest way to feed my family. Of course, I will die in a year - two at best, if I don't exceed the rate of exposure. But during this time my family will be supplied with money for several years ahead.}

#Female character
{1122}{}{wanderer.}
