{100}{}{You see Michael.}
{101}{}{You see the supplier of the miners' guild.}

{110}{}{(you see a supplier; he's had a surprising change since being beggar in Reno) Oh, is that you?! Finally I can express my gratitude to my savior. It's not every day one can meet people like you.}
{111}{}{Gratitude is good, but let's get down to business.}
{112}{}{How can I help you?}
{113}{}{Can I help you, Sheriff?}

{114}{}{What do you do here?}
{115}{}{Nothing today.}
{116}{}{Trying to negotiate with different people and a caravan to deliver us some supplies.}
{117}{}{You're buying something?}
{118}{}{Yes, our workers need equipment and tools to work in the mine - shovels, boots, explosives, medicine. In general, anything that can help. Prices are listed on the board.}
{119}{}{That's all I need.}

{120}{}{The machine operator said that I could collect my fee.}
{121}{}{It was the fuse, right? Very glad that we managed to solve this issue so fast. Here's the reward - 300 bucks.}
{122}{}{Thanks.}


{123}{}{[Sell Rad-X, }
{124}{}{[Sell Rad-away }
{125}{}{[Sell the shovel, }
{126}{}{[Sell a sledgehammer, }
{127}{}{[Sell the mount, }
{128}{}{[Sell the flare, }

{129}{}{[Sell boots }
{130}{}{[Sell dynamite, }
{131}{}{[Sell a stick of dynamite, }
{132}{}{[Sell plastic explosives, }
{133}{}{[Sell a Molotov cocktail, }
{134}{}{[Sell rope, }
{135}{}{}
{136}{}{}
{137}{}{}
{138}{}{}
{139}{}{$]}

{140}{}{Next list.}
{141}{}{Previous list.}
{142}{}{How much are you going to sell?}
{143}{}{One.}
{144}{}{Two.}
{145}{}{Three.}
{146}{}{Four.}
{147}{}{Five.}
{148}{}{Ten.}
{149}{}{Need to take another look at the list.}
{150}{}{Nothing.}
{151}{}{Everything, I got (}
{152}{}{ pieces.).}

{153}{}{Good deal.}
{154}{}{Now try the same with the other item.}
{155}{}{That's it for today.}
