{100}{}{You see a firearms closet.}
{101}{}{You're looking at a regular closet set up to store firearms.}

{102}{}{The owner wouldn't like you rummaging without permission.}
{103}{}{Well, well! Won't even ask permission, will you? }
{104}{}{Next time you try to take anything without asking, I'll kick your ass.}
{105}{}{I've had enough!}

{106}{}{You drove the guild administrator to his destination in your car.}
{107}{}{You drove the operator to his destination in your car.}
{108}{}{You drove the guild supplier to his destination in your car.}