{100}{}{Selecting a song, you press the button in anticipation, but all you hear in response is a slight static hiss from the speaker.}
{101}{}{Selecting a song, you press the button in anticipation. Inside the jukebox, the turntable rattles to life.}
{102}{}{The machine doesn't need repair.}
{103}{}{Repair fails.}
{104}{}{You have loaded new songs into the machine.}
{105}{}{Your incompetence cause the wires in the dispenser to melt and the chips to burn out. Obviously, the music player cannot be repaired now.}
{106}{}{This machine is burned out and cannot be repaired.}
{107}{}{This machine is not working.}
{108}{}{You can't load new songs because music player doesn't work.}
{109}{}{Done}