{100}{}{You see Avanigizhig the Foggy Day, the Cheyenne shaman.}
{101}{}{You see a gray-haired man in dirty clothes with a faraway look in his eye.}
{102}{}{What is this? Potions for the body? Thank you, but I have my own.}

#Плавающие фразы
#Когда ГГ под кайфом:
{110}{}{Spirits do not speak to the one who has the breath of fire in their nose. Neither do I.}
{111}{}{These substances allow the Devourer into your body and mind! I will not speak to you while you are under their power.}
#Когда у ГГ в руках оружие
{112}{}{This is a place of peace, not war. We will not speak with weapons in hand.}
{113}{}{The Ruler of Life advises us to solve our problems with words, not weapons.}
#Когда ГГ открыл секретную ветку диалога
{114}{}{May happiness come to you. My days are limited, but the road is long ahead of you. Thank you for everything.}
{115}{}{May you walk with the spirit that sheltered me and Ogima all these years!}
{116}{}{Good luck to you. And don't visit Canada. Ever.}

#Плавающие сообщения при ранении (в 1.0. не используется):
{120}{}{Bad deeds!}
{121}{}{By doing evil to me, you have brought evil upon yourself!}
{122}{}{What is your tribe?}
{123}{}{I see the gaze of the Devourer in your eyes!}
{124}{}{My curse will follow you forever! Not even death will release you!}
{125}{}{You're just a worm in the Devourer's leavings!}
{126}{}{Your tribe can be respected.}

##################################################
#
#      Первый диалог
#
##################################################

#ГГ с низкой репутацией, стал налетчиком или имеет достижение работорговца:
{130}{}{Stop, wanderer! I am only an old man, and I have nothing. Do not let evil spirits guide you... }
{131}{}{I don't. Why would you say that?}
{132}{}{Those are the only spirits I respect! You got a problem with that?}
{133}{}{Fine, I'll be on my way then.}

{134}{}{I see darkness deeper than the night inside of you. Just to look at it hurts me. [he sighs] Well, perhaps a wanderer must walk in darkness these days, after the Devourer spilled from his insides withering fire across the world... }
{135}{}{Exactly. Now, will you answer my questions?}
{136}{}{Uh-huh. I think your brain's past its expiration date.}
{137}{}{Let's just leave it at that.}

{138}{}{Everything has its time. Mine is coming soon.}
{139}{}{You're not easy to piss off, huh? Forget it, I'm going.}

{140}{}{Good. I'm glad to hear it.}
{141}{}{I want to ask you something.}
{142}{}{In that case, I'll see you later.}

{143}{}{Hmm... I see a child of the Devourer and, at the same time, a friend of the Cheyenne. I hope you continue to walk the bright path, wanderer... }

{144}{}{Our humble camp is open to you, wanderer, so long as you come in peace.}
{145}{}{It is a happy day when you come to our camp, wanderer. How can an old shaman help you?}

##################################################
#
#      Второй диалог - до уничтожения рейдеров
#
##################################################

{150}{}{[The old man looks like a ghost among the graves. His hollow eyes stare hopelessly into emptiness.] Wh... Who's there?}
{151}{}{What are you doing here, old man? Planning to dig someone up? Or do you just like to hang around corpses?}
{152}{}{I'm just out for a walk. What are you doing among the graves?}
{153}{}{Look out, I'm the Devourer! Boo-oo-oo! [leave]}
{154}{}{I was just going. [exit]}

{155}{}{[He looks at you for some time. You notice tears in his eyes.] Leave me!}
{156}{}{Shut your mouth, while you still have some teeth left!}
{157}{}{Easy, easy. I'm leaving.}

{158}{}{[He looks at you for some time. You notice tears in his eyes.] What am I doing?... I don't know... }
{159}{}{Memory problems, old man?}
{160}{}{Maybe I shouldn't ask. Forgive me.}
{161}{}{Actually, I don't really want to know. See you.}

{162}{}{Leave me! Leave!}
{163}{}{I shouldn't have asked, forgive me. Did something happen?}
{164}{}{Nothing. It's me that needs forgiveness... I gave myself to oblivion, and because of it, I lost my sight... }
{165}{}{What happened?}
{166}{}{Gladly.}

#Получение квеста на ликвидацию рейдеров
{170}{}{Nothing... I always come here at night, and I can never remember why. Something inside me is tearing my soul to pieces. I know the Ruler of Life cares for our dead, but... How much suffering must we endure as a result of the white man's greed?}

{171}{}{Are you talking about raiders?}
{172}{}{"White man's greed"? What are you talking about?}
{173}{}{What problems have you had with the white man?}
{174}{}{Show us proper respect, you scum! We are the dogs protecting your flock. Without us, you'd have been eaten by wolves a long time ago.}
{175}{}{Why don't you get rid of them?}
{176}{}{I'm not interested in this right now.}

{177}{}{Yes, Ogima thinks so, too. This is truth... The truth in captivity.}
{178}{}{Raiders, may the Devourer damn them. One day, they came for another raid and never left.}
{179}{}{}

{180}{}{Our ancestors told us that our people were always persecuted, even when gold ruled these lands. That's why, when the Last Day came, our people hid in the mountains. But even though the times have changed, the people remain the same.}
{181}{}{The truth is, the Devourer will always make more children. They will come and replace the ones he has lost. We cannot defeat this truth by ourselves. We can only hope for the Ruler of Life's mercy.}
{182}{}{You don't have to wait much longer. I am that mercy.}

{183}{}{[His eyes blaze] So Ogima made that decision, did he? The one I couldn't make? Then, good! Do it for us, wipe them off the face of the earth! Take blood for blood!}
{184}{}{Fine. But I could use some help.}
{185}{}{I'll go think about my strategy then.}

{186}{}{Do my ears deceive me? Or... Does the big raider's right hand seek to test me? Then tell him we are taught to be careful.}
{187}{}{From me? I'm old. But our warrior Gekek, who watches the entrance, can show you the way to their camp. I can only give you wisdom: do not attack them directly. They are strong fighters. But even the greatest warrior's throat may be cut if caught unaware.}
{188}{}{I understand... I think. I'll talk to Gekek.}
{189}{}{Be careful, wanderer.}
{190}{}{Of course.}
{191}{}{Is that so? I've never seen an outsider help our people without reward. Perhaps the time has come... }

{192}{}{[The old man is clearly depressed. He looks like a ghost among the graves.]}
{193}{}{[Leave]}

{194}{}{How can you live with raiders?}
{195}{}{Ogima is a cunning speaker. To keep the axe of war locked away, we give the raiders tribute and leave us in peace. Mostly. It is not pleasant, but if we break the deal, it will be much worse.}

{196}{}{(mumbles something) And our paths cross once again... }
{197}{}{I would like to ask you something.}
{198}{}{...and once again, diverge.}

{199}{}{Shh! Now is not the time to talk, wanderer. I must complete my daily ritual.}
{200}{}{Some other time then.}

##################################################
#
#      Второй диалог - после уничтожения рейдеров
#
##################################################

{201}{}{I have never seen anything like this - a child of the Devourer, helping people like us. You give me much to think about, wanderer.}
{202}{}{Everyone! Our hero returns!}
{203}{}{Our paths cross again. What will this bring today?}
{204}{}{I should go. Take care.}
{205}{}{Do you know? The raiders are no more!}
{206}{}{What will you do now that the raiders are gone?}
{207}{}{There should be a radio station near here. Where is it?}
{208}{}{}
{209}{}{}

#Спрос про радиостанцию
{210}{}{Hmm... That place is normally forbidden to outsiders. Only there, may we be alone to perform our most sacred worship. But you deserve our trust, wanderer. I cannot take you, but I will tell you where it is.}
{211}{}{Fine, I'll find it myself.}
{212}{}{}
{213}{}{}
{214}{}{}

#Об уничтожении рейдеров
{215}{}{Word of it is spreading throughout the wasteland! Thank you! I am finally ready for my final journey, when I will go to the spirits of my loved ones and leave the tribe to the young.}
{216}{}{}
{217}{}{Speaking of the young, do you think they'll make it?}
{218}{}{I'm glad to see you're doing well. Stay healthy.}
{219}{}{They have a lot to learn. Like walking through a mine field, some make it through by luck, and some avoid it altogether, but we, the old ones, have led them safely through these years. But when I meet my ancestors, I will tell them our young will find their path, as they taught us to.}
{220}{}{You're a shaman. You know more than most of your fellow tribesman. Can you tell me the history of this place?}
{221}{}{Can you tell me the history of this place again?}

#История поселения
{230}{}{We lived far to the north-east, in the mountains. Our tribe survived there afer the Last Day.}
{231}{}{How did you made such a long journey?}

{232}{}{We came most of the way on a train, but the rails were not strong enough. It left its tracks on the borders of Nevada, near Salt Lake City.}
{233}{}{Tell me more about those times.}
{234}{}{Why did you leave your lands?}
{235}{}{Salt Lake City? Where is that?}
{236}{}{That's all, thank you.}

{237}{}{I will show you on your map. It was a big city in times that gold ruled these lands. It's lost its glory since then, but people still live there.}
{238}{}{You got the coordinates of Salt Lake City.}
{239}{}{That was more than thirty years ago. When the Devourer took his tribute across the world, the old ones hid our people in the mountains. We lived through the Last Day there. Many died afterwards, when huge clouds of burning dust hid us from the Ruler of Life. I don't remember that time very well, as I was very young, but... It was horrible.}
{240}{}{The lands themselves stood against us. The mountains made us think of hope, fire and food, but we feared the vicious mutants the most. They attacked settlements and killed everyone. All the remained of people were smashed bodies and torn clothing.}

#Female character:
{1130}{}{Stop, wanderer! I am only an old man, and I have nothing. Do not let evil spirits guide you... }
{1143}{}{Hmm... I see a child of the Devourer and at the same time, a person who loves our people. I hope you continue to walk the bright path, wanderer... }
{1144}{}{Our humble camp is open to you, wanderer, so long as you come in peace.}
{1145}{}{It is a happy day when you come to our camp, wanderer. How can an old shaman help you?}
{1152}{}{I'm just out for a walk. What are you doing among the graves?}
{1154}{}{I was just going. [exit]}
{1189}{}{Be careful, wanderer.}
{1199}{}{Shh! Now is not the time to talk, wanderer. I must complete my daily ritual.}
{1202}{}{Everyone! Our hero returns!}
{1210}{}{Hmm... That place is normally forbidden to outsiders. Only there, may we be alone to perform our most sacred worship. But you deserve our trust, wanderer. I cannot take you, but I will tell you where it is.}
{1211}{}{Fine, I'll find it myself.}
