{100}{}{You see a child.}
{101}{}{You see lovely and cheerful child of the Cheyenne tribe.}

{102}{}{Why outsider look at me so strange?}
{103}{}{Your eyes look like the Devourer's.}
{104}{}{Is something wrong, outsider?}
{105}{}{Mom! Mom! Outsider has filth!}
{106}{}{I know you ate filth!}
{107}{}{You's scary!}
{108}{}{Niskigvan would teach you not to eat filth! He taught us!}

{109}{}{Stranger!}
{110}{}{Mama!}
{111}{}{Who are you?}
{112}{}{We can't talk to outsiders!}
{113}{}{Outsider!}
{114}{}{I'll scream!}
{115}{}{I'll bite!}
{116}{}{Don't touch me!}
{117}{}{Get away!}

{118}{}{We can't talk to outsiders.}
{119}{}{Outsiders do bad.}
{120}{}{Ha-ha-ha!}
{121}{}{:: sticks his tongue out at you ::}
{122}{}{Did you walk a long way?}
{123}{}{I feel tired...}
{124}{}{Mom wants us to work!}
{125}{}{Eat those bad people and turn into a wendigo!!!}
{126}{}{Is you bad?}
{127}{}{Is you good?}
{128}{}{Do you tell stories?}
{129}{}{Niskigvan made us dolls, and then... Ouch!}
{130}{}{Do you know Niskigvan? He is good.}
{131}{}{Today we have roasted mice. Mm-mm!}
{132}{}{Outsider ever tried salted gecko? It's yummy!}
{133}{}{Hunters come at lunch, then leave.}
{134}{}{Do outsiders hunt?}
{135}{}{One flew east, one flew west, one flew over the cuckoo's nest!}

{141}{}{Mm... Mama?..}
{142}{}{:: snkkrk ::}
{143}{}{Zzzz}
{144}{}{Who's here? Oh... It's...}
{145}{}{Shaman has a pis... Pisto...}
{146}{}{D... Don... Hrrr...}
{147}{}{...Mommy...}
{148}{}{I'm sleeping...}
{149}{}{Morning...}

{150}{}{Giving drugs to children has darkened your soul and brought the curse of the tribe upon you. Shame on you.}

{151}{}{Shh! I'm listening!}

#Женский вариант реплик
{1118}{}{We can't talk to outsiders.}
{1119}{}{Outsiders do bad.}
{1120}{}{Ha-ha-ha!}
{1121}{}{:: sticks his tongue out at you ::}
{1122}{}{Did you walk a long way?}
{1123}{}{I feel tired...}
{1124}{}{Mom wants us to work!}
{1125}{}{Eat those bad people and turn into a wendigo!!!}
{1126}{}{Are you bad?}
{1127}{}{Are you good?}
{1128}{}{Do you tell stories?}
{1129}{}{Niskigvan made us dolls, and then... Ouch!}
{1130}{}{Do you know Niskigvan? He is good.}
{1131}{}{Today we have roasted mice. Mm-mm!}
{1132}{}{Outsider ever tried salted gecko? It's yummy!}
{1133}{}{Hunters come at lunch, then leave.}
{1134}{}{Do outsiders hunt?}
{1135}{}{One flew east, one flew west, one flew over the cuckoo's nest!}
