{100}{}{A tribal woman.}
{101}{}{A Cheyenne woman working in the field.}

#Толкание
{102}{}{Awrite.}
{103}{}{Me move.}
{104}{}{You rude!}
{105}{}{Sky Mother protect me!}
{106}{}{No push!}
{107}{}{You is glad me husband no see!}
{108}{}{Go push gecko!}
{109}{}{Push me again - you regret!}
{110}{}{Me scratch out you eyes!}
{111}{}{Help!!!}

#Попытка заговорить
{112}{}{Me no talk.}
{113}{}{Me watch crops and kids.}
{114}{}{Uh... Me no chat.}
{115}{}{Go talk Ogima Black Cloud.}

#Попытка заговорить под действием химии или алкоголя
{116}{}{What you eat?}
{117}{}{You awrite friend?}
{118}{}{You look what?}
{119}{}{Me no like. Go!}