{100}{}{You see Afterburner.}
{101}{}{You see a raider nicknamed Afterburner. He's shuffling a deck of cards.}

{105}{}{I'm beat. I gotta hit the hay.}

#############################################################################
#
#           Äèàëîã
#
#############################################################################

{110}{}{[He glances up at you and deftly continues to shuffle the cards in his hands without looking] Yeah?}
{111}{}{Bye.}
{112}{}{Never mind, I'm leaving.}
{113}{}{Let's go back to what we were talking about before.}
{114}{}{Forget it. Let's go back to what we were talking about before.}
{115}{}{I'm leaving.}

{120}{}{How's the gang?}
{121}{}{Right now? It's been pretty boring lately. Outside of fucking around with the locals, all we do is sit around playing poker.}

#Î ñåáå
{122}{}{Tell me about yourself. How did you end up in the gang?}
{123}{}{Me? [he chuckles] It wasn't my first choice, let me tell you. Back in Reno, I was known as one hell of a gambler. One day I was a little *too* good and ended up with a bounty on my head. I figured that the only way to survive at that point would be to join a gang.}
{124}{}{What's your job here? You don't really look like a raider.}
{125}{}{Smart choice. What do you do around here?}
{126}{}{Look who's talking. Anyway, most of the guys here aren't good for anything but starting fights. I'm the one that deals with our clients and the local tribe.}
{127}{}{You need more than thugs in an operation like this. For dealing with clients and the locals, they need someone with an appreciation for subtlety. [he jerks a thumb towards himself] That's me.}
{128}{}{Clients?}
{129}{}{Hey, we do more than push around Indians, you know. The revolution in Reno? That was us. Sometimes people ask us for help in business, and... Er, maybe the boss wouldn't like me talking about that. Never mind.}

#############################################################################
#
#           Ðàäèîñòàíöèÿ
#
#############################################################################

{130}{}{There should be a radio station around here. Have you heard anything about that?}
{131}{}{[He stops shuffling and looks at you out of the corner of his eye] Radio... What? Dunno. If it's here, it's pretty hard to find. Only ruins around us, besides that camp to the south.}
{132}{}{Would 300 dollars jog your memory?}
{133}{}{Oh yeah, it's all coming back now. Give me the money and I might just remember enough to take you to where you need.}
{134}{}{Take it. Now, where's the station?}
{135}{}{I'll think about it. Let's talk about something else.}
{136}{}{I'll keep that in mind. I have to go now.}

#############################################################################
#
#           Âåùè Íèñêèãâàíà
#
#############################################################################

#Íà÷àëî ðàçãîâîðà
{140}{}{The healer from the tribe said someone took his things. Do you know anything about that?}
{141}{}{Yeah, that was me. I was bored. [he raises an eyebrow] Why?}

{150}{}{I see you like playing cards. Wanna gamble?}
{151}{}{Forget it, I'm leaving.}
{152}{}{I have some plans for that stuff. But that's none of your concern.}
{153}{}{He needs that stuff. I want to give it back to him.}
{154}{}{You don't care anyway. Just tell me what you want for it.}
{155}{}{Just curious. Let's change the subject.}

{156}{}{Oh, isn't it? [he smirks] I'm concerned with how much it's worth to you.}
{157}{}{Aww, aren't you good Samaritan. Cut the shit. Whatever you're getting out of this, you're not getting it for free. Understand?}
{158}{}{[He leans forward] Oooh, aren't we businesslike! I think I'm gonna like having you around here.}
{159}{}{What do you want for it?}

#Âûáîð ðåøåíèÿ
{160}{}{Hmm! [he rubs his chin exaggeratedly] Let me think! I've got a lot of options here. I want money. I want to gamble. I want to fuck. What do you have to offer?}
{161}{}{I'll pay you }
{162}{}{ dollars for it.}
{163}{}{If you want sex, I'm right here. Interested?}
{164}{}{Put a deck of cards on the table and I'll win that stuff for sure.}
{165}{}{I won't offer anything.}
{166}{}{Let me think. I'll come back when I make up my mind.}

#Îïëàòà äåíüãàìè
{167}{}{Sounds good to me. When you get that money, come back here.}
{168}{}{What else were you interested in, again?}
{169}{}{[He pockets the money and gives you the healer's things] Not bad. I didn't even think I'd get anything out of that crap.}

#Îòðàáîòêà ñåêñîì
{170}{}{[He sneers in disgust] What are you, kidding? I'd rather fuck one of the scorpions outside.}
{171}{}{Fuck you... }
{172}{}{Suit yourself.}
{173}{}{[He licks his lips] Damn, am I still drunk from yesterday? No time like the present, baby! Hope you like it hot!}
{174}{}{How tempting. Let's go, hot guy, before I cool down.}
{175}{}{Eugh, really? How about no.}
{176}{}{What the hell, baby? [he stands in your way] Where you going, huh? You can't say something like that and then take it back!}
{177}{}{Relax, I'm just fucking around. Let's do it!}
{178}{}{Touch me and I'll give you your own vagina to play with, you festering sack of gecko shit. But in return, I get to take your balls with me.}
{179}{}{I said no. Leave me alone.}
{180}{}{[He backs up, holding up his hands] Woah, I got it. I got it.}
{181}{}{That's better.}
{182}{}{[He imitates you in a high voice] "I toooold you, leave me aloooone." Get the fuck out of here.}
{183}{}{Fucker... }
{184}{}{Fine.}

{185}{}{After some rough, wild, and very loud sex, you get the healer's things.}

#Âûèãðàòü ðþêçàê çíàõàðÿ:
{190}{}{I usually play for money. I won't go below 100 bucks. What do you say?}
{191}{}{I'll bet 100 bucks.}
{192}{}{I don't want to play.}

#############################################################################
#
#           Èãðà
#
#############################################################################

{200}{}{Leave me alone. I'm not playing with you again.}
{201}{}{Well, if you say so.}
{202}{}{Not today. Someone stole my cards, and I won't play with someone else's. What if they're marked?}
{203}{}{Let's talk about something else, then.}
{204}{}{Well, well.}
{205}{}{Not until I figure out which of these cards are mine. Someone's fucking with me - I found another deck of cards in my pocket. They're probably marked.}

{210}{}{I want money. I bet drugs, you bet cash. Deal?}
{211}{}{Yes. What will you bet this time?}
{212}{}{No deal. I have questions, instead.}
{213}{}{No deal. I'm leaving.}

{214}{}{Healing powder. Don't worry, it works and it's safe. Fatso knows what he's doing. You put up 50 bucks.}
{215}{}{Here's the money. Let's play.}
{216}{}{Tempting, but I don't have enough cash.}
{217}{}{I only play for money.}
{218}{}{Super stimpak, against 100 bucks.}
{219}{}{Psycho, against 300 bucks. You ever tried this shit? You should be happy I'm even risking it for that bet.}
{220}{}{Shit, you're starting to piss me off. Alright, I bet my gun and ammo against 500 bucks.}
{221}{}{Fucking hell, alright, this is my last bet. If I don't win this, I'm out for good. You put up 700 bucks, and I'll put up *this*. [he shows you a viscose substance rolled up in a newspaper] This is amphetamine gum, made in Reno. When they caught up with the guy, they made him dig his own grave, then cut off his arms and legs and lit him on fire. Not because of the gum, but... You know what, it's a long story. The point is, there's never gonna be any more. This is all there'll ever be. Do we have a deal?}
{222}{}{I'll just leave.}

{230}{}{Heh. Prepare to learn some humility. [he takes the cards out and the game begins]}
{231}{}{Quit the bullshit. Let's play already.}
{232}{}{[Afterburner deals the cards. So far, everything is fair.]}
{233}{}{[Next]}
{234}{}{Ha-ha, what is this? You lost your ace and king! I'll kick your ass in the next hand.}
{235}{}{Woah! Where did you get that ace from? It was... Ah, yeah, that's right. Let's keep going.}
{236}{}{[The game is all but finished. Time to count the points.]}
{237}{}{[Show your cards.]}

#êîíåö èãðû
{240}{}{God fucking damn it! [he throws the bet down on the table]}
{241}{}{You want to play again?}
{242}{}{How dare you yell at me! I'm going to teach you some manners. [Attack]}
{243}{}{Hey, relax. I'll just go.}

{244}{}{Draw! Damn, you're pretty good. I should be more careful.}
{245}{}{Let's finish up and go our separate ways.}
{246}{}{Read 'em and weep. What's yours is now mine. Go cry about your loss.}
{247}{}{[Unbelievably, you win] Fuck! Fine, take it! [he throws the healer's stuff on the table] Never fucking talk to me again!}

#Female character
{1234}{}{Ha-ha, what is this? You lost ace and queen! I'll kick your ass in the next hand.}
