{100}{}{You see Gekek the Hawk.}
{101}{}{You see a muscular, grim-faced warrior of the Cheyenne tribe.}

{102}{}{No! Bad! Punish, punish!}
{103}{}{You earned 100 experience points for use of your charisma.}

{107}{}{Me no speak.}
{108}{}{Me guard entrance.}
{109}{}{[He shakes his head slowly] No talk.}
{110}{}{Me make tribe safe.}

{111}{}{What you eat?}
{112}{}{You okay?}
{113}{}{Where you look?}
{114}{}{[He frowns] No good. Leave!}

{115}{}{[He sniffs] Bad smell.}
{116}{}{This not right.}
{117}{}{Me no want, but you make me.}
{118}{}{Bad outsider! Sit!}
{119}{}{What your tribe?}
{120}{}{Cheyenne no forget!}
{121}{}{You child of Devourer!}

{122}{}{You strong, me weak.}
{123}{}{Outsider good! Or...not?}
{124}{}{You of good tribe.}
{125}{}{Me no ask that!}

{147}{}{Ruler of Life, make me strong!}
{148}{}{Me speak!}
{149}{}{Mmm! Me inhale magic smoke!}
{150}{}{Me walk on roof.}
{151}{}{Me no die! Me NEVER die!}
{152}{}{[Mutters something in another language]}
{153}{}{We clear clouds... See? They gone!}
{154}{}{Ha-ha-ha-ha!}

#О'правка к рейдерам
{155}{}{Run to bush!}

{156}{}{Me no speak outsider.}
{157}{}{You can talk with me, Gekek. Your chief said it's okay. You've been to the raiders' base, right? Can you bring me there?}
{158}{}{[Gekek's eyes go wide] Me... You... Hmm! Why you need raider?}
{159}{}{Because I can solve your problem with them, Gekek. Will you show me their base?}
{160}{}{Hmm... Yes. Me show, when you ready. But no is late - Gekek have many duty!}
{161}{}{I'm ready. Take me there, oh feathered warrior!}
{162}{}{Lay down your wings, Hawk, I'm not ready yet.}

{163}{}{Oof! Good we escape. Very bad when raider see. Oooh!}
{164}{}{Tell me about their locations... Err... Where is everybody?}
{165}{}{Tell me about the ruins. Is there anything interesting around here?}
{166}{}{Tell me about the raiders.}
{167}{}{Tell me about their boss.}

{168}{}{Bad men sit inside house. Leader sit on top. Two-legged dogs outside, looking. Careful! Must hide!}
{169}{}{Right.}
{170}{}{Fine. I'll go scout the area.}
{171}{}{Old village. Sand, dirt, garbage. Niskigvan and Avanigizhig search Datura-grass here. But be careful in bushes! Big danger! Hmm... Behind house is water tank, like Cheyenne's. And can go into house from behind. This is all.}
{172}{}{A water tank? Maybe the raiders drink from it...}
{173}{}{[He scowls] Raider bad. Raider evil! Raider stupid. Love fight, but bad guard! [he shakes his head] Big stupid. Most raiders sit in house. Three watch outside. Raiders make fire water, drink fire water. No good! Drink fire water, head hurt. Want sleep. [his lip curls in distaste] Stupid.}
{174}{}{Boss big. MUCH big. Wear hat and is black and evil, like Devourer. Stay alone. Boss sits on house top.}
{175}{}{Datura-grass?}
{176}{}{Yes! Datura-grass... [he strains to think of the right word] ...Xander root and broc flower. To shaman, Datura-grass smoke pipe, to healer, Datura-grass medicine! Look bushes. Find Datura-grass, bring Niskigvan. Make happy! But you no mix grass, is danger.}
{177}{}{I see bad raiders' pain. Me so happy! So happy!}
{178}{}{Your oppressors are dead. That's over. Let's get out of here.}
{179}{}{I poisoned their drinking water. Let's hope it works. We should see the results in a day or two.}

{180}{}{Me like here! Me no like there!}
{181}{}{Yes, the raider base isn't a very pleasant place. Bye.}
{182}{}{Oof! [he looks relieved] When raider move you behind house, me think you meet Ruler of Life!}
{183}{}{Gekek, take me to the raider base again. I have to see if the poison worked.}

#На кар'е рейдеров, когда ГГ с ними снюхался
{184}{}{Me see! You traitor!!!}
{185}{}{Wait, Gekek! I'm not a traitor! I just lied to gain their trust!}
{186}{}{Yes. So?}
{187}{}{Yes. And now I will go and tell the gang all about you.}
{188}{}{Nobody asked your opinion. You're free to go! [leave]}

{189}{}{Me no believe! You traitor!}
{190}{}{Why me trust you?!}

{191}{}{Because I'm your tribe's only hope... And because you're still alive. Isn't that enough?}
{192}{}{I don't know. You figure it out.}

{193}{}{[He narrows his eyes, then slowly nods and slyly nods] Yes... You smart. Cunning! Me believe.}
{194}{}{That's good. Trust me. Bye.}

#Тес'овые сообщения
{200}{}{All raiders alive and well.}
{201}{}{One dead!}
{202}{}{Second dead!}
{203}{}{Three raiders sent Devourer!}
{204}{}{Four - dead!}
{205}{}{Raider five follow raider four!}
{206}{}{Hahaha! All raiders dead!}
{207}{}{Not until all raiders are dead.}
{208}{}{All of the raiders have been neatly and quietly dispatched.} #This seems to be message box text to me. If Gekek is saying this, then it should be changed.

#Female character
{1161}{}{I'm ready. Take me there, oh feathered warrior!}
{1162}{}{Lay down your wings, Hawk, I'm not ready yet.}
{1170}{}{Fine. I'll go scout the area.}
{1179}{}{I poisoned their drinking water. Let's hope it works. We should see the results in a day or two.}
{1185}{}{Wait, Gekek! I'm not a traitor! I just lied to gain their trust!}
