{100}{}{You see Fatso Jackson.}
{101}{}{You see a rather fat man.}

#Пошел в 'уале'
{102}{}{Gotta take a leak.}
{103}{}{Gotta take a dump.}
{104}{}{Now, where's Jackson junior?}
{105}{}{Again! The explosive diarrhea!!}
{106}{}{I'm gonna go drop the kids off at the pool.}
{107}{}{I'm going to the shitter, don't touch anything.}
{108}{}{Fuck, I'm gonna piss my pants!}
{109}{}{::farts so hard the tables are shaking::}
{110}{}{My ass is gonna explode... }

#Уходи' из 'уале'а
{111}{}{Fuck it, I don't need to wash my hands.}
{112}{}{Damn, that was one for the books.}
{113}{}{::farts so hard the walls are trembling::}
{114}{}{Ohhhhh, that feels good.}
{115}{}{Time to put the dick away and get cooking.}
{116}{}{Gonna go spit in the soup... }
{117}{}{Heh, who drew all this on the wall here? It's pretty good. For being drawn in shit.}
{118}{}{Phew, it's gonna be a while before that clears out.}
{119}{}{No paper? No problem.}
{120}{}{Whoops, forgot to wipe. All good.}
{121}{}{Gotta change my underwear again. Wait, what underwear?}

#Попы'ка заговори'ь, когда он в 'уале'е
{122}{}{I'm not gonna be done for a while.}
{123}{}{Hold on, goddamn it!}
{124}{}{I'm busy here!}
{125}{}{Don't piss yourself, I'm almost done... }
{126}{}{::farts so loud that others turn their heads away::}
{127}{}{Feels! So! Good!}
{128}{}{Wait, here it comes... Hhnnnrrgg!!!}
{129}{}{Here I stand, broken-hearted... }

#Диалог:
{130}{}{Hey, look who it is! The circus left a clown behind. What's up?}
{131}{}{How's life, Jackson?}
{132}{}{I need chems.}
{133}{}{}
{134}{}{I've heard there's a radio station around here.}
{135}{}{I want to buy some supplies.}
{136}{}{Forget it, I'm leaving.}

{137}{}{Radio station? What's that?}
{138}{}{It would probably look like a big building with antennas.}
{139}{}{Never mind. Let's start over.}
{140}{}{Hmm, I've seen some big metal thingy somewhere, around three floors high. I don't remember where though, and you can't see it from here. Go bug the savages to the south. One of them ought to know.}

#Заказ нарко'ы
{141}{}{I can make them. Just bring me the right ingredients and my pay.}
{142}{}{Make me a healing powder.}
{143}{}{Make me a poison antidote.}
{144}{}{Make me a stimpak.}
{145}{}{I need a very strong poison.}

{146}{}{I need xander root and broc flower. You gotta pay by the dose - }
{147}{}{ bucks.}

{148}{}{Make one dose.}
{149}{}{Make two.}
{150}{}{Make three.}
{151}{}{Make five.}
{152}{}{Make ten.}

{153}{}{I don't have enough money... }
{154}{}{I don't have the ingredients... }
{155}{}{Here it is. Show me your magic.}
{156}{}{I need something else.}

{157}{}{I've got most of what I need here. Just bring me a radscorpion tail and the money for each dose. }
{158}{}{I need two empty syringes, xander root and broc flower. I have everything else I need right here. Each one will run you }

{161}{}{None of your business.}
{162}{}{Why the hell do you care? I live, I breathe. That means it's all good.}
{163}{}{It's... [he waves a hand dismissively] ...Complicated. I need the right stuff and I don't have it all here.}
{164}{}{}
{165}{}{I don't have enough here for that. Ask around Reno, you'll find plenty.}

#Яд, производс'во:
{168}{}{Poison? [he gives you a funny look, then shrugs] Whatever, business is business. Get me three radscorpion tails, two handfuls of nightshade berries and an empty syringe. After that I'll just need a day to work on it and }
{169}{}{Alright, I'll get to work. Come back tomorrow and I'll have it ready.}
{170}{}{This is good stuff! Just, uh, don't mix it up with your stimpaks. [he gives you a syringe of very strong poison]}
{171}{}{Your order's not ready yet.}
{172}{}{It's done. You still want it?}
{173}{}{Give it to me.}

{210}{}{Hey, Mold! If you're gonna die, you mind crawling outside first?}

#Дело о наркодилере
{211}{}{Tell me about the dealer that gave you bad ingredients.}
{212}{}{[He waves a hand dismissively] Don't bother. Our guys already looked. You're not going to find him.}
{213}{}{I don't have the same reputation in Reno as your "guys".}
{214}{}{Hmm... I didn't think of that. Fine, listen up. He hung around the center of town and dealt with us in the El Dorado basement. Here's the list of shit we got from him. Last deal, he gave us poison instead.}
{215}{}{What basement?}
{216}{}{The basement under the El Dorado casino. That's where they've got the fight ring. We usually make deals in crowds like that to keep everyone honest, but I guess it didn't work. Fucking guy.}
{217}{}{How will I know when I see him?}
{218}{}{We call him Solomon. He's got a ring, shaped like a skull, on his middle finger. He uses it like a brass knuckle.}
{219}{}{Can you tell me anything else to help me find him?}
{220}{}{I don't think he's from Reno. We asked the local dealers and nobody knows him. He must have blown into town for some reason, I just don't know which.}
{221}{}{That'll do.}
{222}{}{You got another clue about the dealer.}

#Получение дос'ижения "Знахарь"
{223}{}{Could you teach me how to make chems?}
{224}{}{For you, friend, any time... For 500 bucks.}
{225}{}{500 bucks?! You'd better be one hell of a teacher. [pay him]}
{226}{}{500 bucks?! I don't have that kind of money!}
{227}{}{Maybe next time, then.}
{228}{}{Anything you want, partner. No charge.}
{229}{}{That's what I like to hear! Go on, tell me your secrets... }
{230}{}{Not right now. I'll come back later.}

#Разговор по душам
{235}{}{Fine, forget it.}
{236}{}{What are you doing?}
{237}{}{How is the gang doing?}
{238}{}{What is that tribe to the south?}
{239}{}{What is that, a trick question? I cook and make booze for the gang. What does it look like?}
{240}{}{What, the boss giving you the silent treatment? It's bad out there. People are traveling in groups now, and everyone's got a gun. Raiding's getting tough. I've really got to work to keep a place in the gang. If it weren't for those fucking Indians, we'd really be in trouble.}
{241}{}{It's bad. People are traveling in groups now, and everyone's got a gun. Raiding's getting tough. I've really got to work to keep a place in the gang. If it weren't for those fucking Indians, we'd really be in trouble.}
{242}{}{Our brahmin. Any time we need food or girls, we head down south and help ourselves. But Big Louie has some other deal going on with them. He says we can't take too much or they'll starve or whatever, and then we get anything from them. So, we try not to get too greedy.}
{243}{}{Quit pushing me, motherfucker!}
{244}{}{Push me and I'll piss on you! I'm fucking serious.}
{245}{}{Has the gang been here for long?}
{246}{}{I dunno, I've only been here two years. But they say it's the oldest gang in the region. Everyone knows us and fears us.}
{247}{}{Can you tell me anything about these parts?}
{248}{}{You trying to piss me off? Forget it, just listen. This is our base, but we're all over. We've even got our own people in Reno - Stryker and Thompson. If you're ever down there, stay away from them unless you're with us. Along the way there's that village full of Indians. We get some good shit from them - they're too scared to fight us but they don't want to leave, so they pretty much have to do what we say.}
{249}{}{What can you tell me about Big Louie?}
{250}{}{Know any local secrets?}
{251}{}{The boss? People like him are to be feared and respected. That means you don't talk about them.}

{252}{}{Yeah, I got one. For 100 bucks I'll tell it to you.}
{253}{}{Take it, brother. You have my attention!}
{254}{}{I don't think I want to know that badly.}
{255}{}{Yeah, I got one. For 50 bucks I'll tell it to you.}
{256}{}{Uh-huh... [he sniffs the paper and crumples the edge of the dollar to see if it's fake] We found some dipshit in the wastes and brought him here to have fun in the ring. We locked him in the basement, but he somehow broke the lock, took some dynamite out of the storage and got out through the tunnels, while we were running around looking for him. Our lookout eventually saw him in the north ruins and shot him a couple of times. We've never found the body, though, so if you happen to come across it, everything he's got on him is yours.}
{257}{}{Fine, we'll see.}

{260}{}{What do you know about Balder?}
{261}{}{He's fucking scum. He was our contact in Reno, but our last meeting was a setup. He led our guys into an ambush and got a lot of good men killed. Why, I don't know - I don't think it was just money. But no one's seen him since. Some guys say he's still holed up in Reno, but I dunno. Where else would he go?}
{262}{}{Right.}

#Female character
{1155}{}{Here it is. Show me your magic.}
{1161}{}{None of your business.}
{1170}{}{This is good stuff! Just, uh, don't mix it up with your stimpaks. [he gives you a syringe of very strong poison]}
{1224}{}{For you, friend, any time... For 500 bucks.}
{1240}{}{What, the boss giving you the silent treatment? It's bad out there. People are traveling in groups now, and everyone's got a gun. Raiding's getting tough. I've really got to work to keep a place in the gang. If it weren't for those fucking Indians, we'd really be in trouble.}
{1241}{}{It's bad. People are traveling in groups now, and everyone's got a gun. Raiding's getting tough. I've really got to work to keep a place in the gang. If it weren't for those fucking Indians, we'd really be in trouble.}
