{100}{}{You see Makkon.}
{101}{}{You see a little Cheyenne boy named Makkon the Little Bear.}

{102}{}{That won't work. This boy needs extensive surgery.}
{103}{}{He needs surgery.}

#После операции
{110}{}{Hey, mister!}
{111}{}{How do you feel, Makkon?}
{112}{}{It's good to see you.}
{113}{}{I can even run now! No one believes it! You are a great shaman, like Avanigizhig! Thank you, thank you!}
{114}{}{That's good. I hope you get better.}
{115}{}{Sad, that I can't run like before. But I'm happy that my legs are not in pain anymore! Thank you! May the Ruler walk your path forever!}
{116}{}{I walk strange now, but anything is better than before. It was so scary... I saw evil spirits around me, waiting for me to die, like when I drank Avanigizhig's potion by mistake. Thank you for saving me from that.}

#Лежит в беcсознании
{120}{}{This poor child is unconscious. His bloody, swollen legs are wrapped in cloth and herbs, and intoxicating smoke wafts from a nearby bowl. But without surgery, these procedures only delay the inevitable.}
{121}{}{[Leave him alone]}

{122}{}{Perform a medical examination.}
{123}{}{Even through the swelling and inflammation, you can see that his bones and muscles have been broken and torn. He would need extensive surgery to recover.}
{124}{}{Determine how long the patient will live in this condition.}
{125}{}{Determine the odds of recovery.}
{126}{}{Examine the boy in detail.}

{127}{}{It is difficult to say how long the patient will live - most likely from a few weeks to six months. But without timely medical care, death is inevitable.}
{128}{}{You don't have the medical skill for this. You'll need a more experienced doctor to help you.}
{129}{}{After the examination, you have confidence that you can save this boy's life. Although it is difficult to predict how fully he will recover.}
{130}{}{You can't even determine where the fractures are located. This is clearly beyond your skill level.}
{131}{}{This patient is treated with traditional medicine, such as decoctions of roots, flowers, mouse feces, and soot. Although such treatment has an analgesic, sedative, antiseptic, and regenerative effect, it is only sufficient to delay death, not to facilitate recovery. He is locked in a painful state between life and death.}
{132}{}{Evaluate the available surgical instruments.}
{133}{}{There are some primitive tools in the healer's tent, but they are not enough. To treat the boy you will need painkillers, a stimpak to speed up tissue repair, a first aid kit or doctor's kit, a scalpel or other sharp blade, and, of course, an impressive set of medical skills.}
{134}{}{Prepare the patient for surgery.}
{135}{}{Leave the patient alone.}

{136}{}{The healer will probably not appreciate your proactiveness. You can't carry out the operation with him around.}
{137}{}{The healer is telling stories to children around the campfire. You'll have about an hour to perform the operation, which should be enough.}
{138}{}{I'm ready. Let's begin!}
{139}{}{Looking at the swollen limb, you realize you can't even tell where the fractures are located. Don't even think of carrying out this surgery on your own.}
{140}{}{Makozid is still following you throughout the village. Unless you get permission, you can't perform the surgery with him around.}

#Проверка медицинского снаряжения
{141}{}{Makkon may regain consciousness during surgery, but you have painkillers to sedate him.}
{142}{}{Makkon may regain consciousness during surgery and you have nothing to relieve his pain.}
{143}{}{[Next]}
{144}{}{[Leave]}
{145}{}{You need gauze and bandages. Luckily, you have them in your doctor's bag.}
{146}{}{You need gauze and bandages. Luckily, you have them in your first aid kit.}
{147}{}{You need gauze and bandages, but you don't have any.}
{148}{}{After surgery is complete, you should inject a stimpak into his legs to kickstart the healing process.}
{149}{}{You need a stimpak to speed up the healing process after surgery, but you don't have any.}
{150}{}{You need a blade to start the surgery. Fortunately, you just so happen to have one in your backpack.}
{151}{}{Stay strong, Makkon. Once I set your bones, they can start growing back together.}
{152}{}{All you need now is a blade for the surgery.}
{153}{}{You have everything you need for the surgery. No one can see you. It's the perfect time to start!}
{154}{}{During and after the operation you will need clean water to wash Makkon's wounds and your own hands.}
{155}{}{You still don't have everything you need for the operation.}
{156}{}{}
{157}{}{}

#Удачная операция
{170}{}{Who... Who are you? Are you a savior, sent by Heavenly Mother?}
{171}{}{Er, it's complicated...}
{172}{}{What's happening in... By the Ruler! Outsider, what have you done?!}
{173}{}{It's a miracle, Ruffled Feathers! Outsider is sent by Heavenly Mother to heal me! I feel... I feel better!}
{174}{}{Let me see you, Makkon... It's... It's... Oh, Heavenly Mother! It's a miracle!}
{175}{}{You earn 10000 experience points and the Cheyenne tribe's eternal love for healing Makkon.}

#Неудачная операция
{180}{}{What's happening in... By the Ruler! Outsider, what have you done?!}
{181}{}{I wanted to help him, but his condition was too severe. I did everything I could.}
{182}{}{Did I allow you?! Did I ask you?!}
{183}{}{He was dying! I was trying to help!}
{184}{}{Your "help" killed this child! Get out!}
{185}{}{Leave this village and never return!}
{186}{}{If your path ever crosses the Cheyenne again, turn around! You will be hated by the Cheyenne from this day forward!}
{187}{}{You could not cure Makkon, but it was a great learning experience. You earn 5000 experience points and gain +10 to your Doctor skill.}

#Female character
{1110}{}{Hey, miss!}
{1112}{}{It's good to see you.}
{1113}{}{I can even run now! No one believes it! You are a great shaman, like Avanigizhig! Thank you, thank you!}
