{100}{}{You see Makozid the Bear's Paw.}
{101}{}{You see a broad-shouldered and heavily scarred warrior.}
{102}{}{You is bad! Punish!}

#Нанесение героем урона
{114}{}{Ugh. Bad smell.}
{115}{}{You no do good.}
{116}{}{Me no want. You fault!}
{117}{}{Evil outsider! Yuck!}
{118}{}{Of what you tribe?}
{119}{}{Heavenly Father punish you!}
{120}{}{No!}
{121}{}{Me STRONG!}
{122}{}{Good... For outsider.}
{123}{}{You tribe is honor.}
{124}{}{Me never forgive!}

#Устаревший диалог про шкуры гекко - не используется!
{141}{}{You must have skinned a lot of geckos, right?}
{143}{}{[He nods once] Yes. Me skins good. Very good! All Cheyenne use me skins!}
{144}{}{Can you teach me? I always wanted to know how to do it.}
{145}{}{[He smiles with his black teeth] Me teach! Me teach! [you spend some time learning about geckos, their habits and place in the local ecosystem, then - finally - about how to properly skin them]}
{146}{}{Thank you, Makozid! I feel like I've learned from the best. Can I ask you something else?}
{147}{}{Thank you, Makozid! I feel like I've learned from the best. But now I have to go.}
{148}{}{Makozid Pear's Paw taught you how to skin geckos. You earn 750 experience points.}

#Плавающие предупреждения - не используется, так как опция перенесена тригеру с другим скриптом:
{161}{}{You no go here!}
{162}{}{Go away from here!}
{163}{}{No yours!}
{164}{}{Leave here!}
{165}{}{You go where?}
{166}{}{Ogima, other way!}

{167}{}{Why you go trees?}
{168}{}{What you want trees?!}
{169}{}{What you think?}
{170}{}{You come back!}
{171}{}{You annoy Makozid.}

{172}{}{Not you home, outsider!}
{173}{}{Go away tent, outsider.}
{174}{}{Ogima not here, outsider. Go big tent.}
{175}{}{No go here, outsider. Forbidden.}

{176}{}{Where hide, outsider? Go here!}


##########################################################
#
#          Џервый диалог
#
##########################################################

{300}{}{Stop, paleface! Me - Makozid the Bear's Paw, guard Cheyenne. Me watch you. You finish business quick. You leave.}
{301}{}{Finish business or leave.}
{302}{}{Who's in charge here?}
{303}{}{Paleface? Is that what you call outsiders?}
{304}{}{Watch your tone, or else...}
{305}{}{Fine.}
{306}{}{Don't worry, I won't make trouble.}
{307}{}{Good talk, paleface.}
{308}{}{Fine.}
{309}{}{}

{310}{}{Chief Ogima Black Cloud. Home tent behind water tank.}
{311}{}{[He chuckles] Much outsiders see Cheyenne, you no different. Face look like you fear sunlight.}
{312}{}{Wasteland eat much you kind. Wasteland eat you too, now or later.}
{313}{}{Are you threatening me? You want to fight?}
{314}{}{Fine, I get the point. Let's resolve this peacefully.}
{315}{}{Perhaps, when you'll be ready, we'll fight. But not now.}
{316}{}{Fine, we'll see about that.}

##########################################################
#
#          Второй диалог
#
##########################################################

#Основные ветки

{320}{}{Paleface!}
{321}{}{Paleface!... Hmm. You eyes... Children of Devourer's eyes.}
{322}{}{What do you know about the raiders?}
{323}{}{Tell me about your tribe.}
{324}{}{Do you know anything about a local radio station?}
{325}{}{You're called Bear's Paw for a reason, right? Let's see who's stronger!}
{326}{}{See you.}
{327}{}{}
{328}{}{}
{329}{}{}

{330}{}{You to question about this?}
{331}{}{Right.}
{332}{}{Evil men. Children of Devourer. Nothing else matters.}
{333}{}{If you hate them so much, why won't you get rid of them?}
{334}{}{Right.}

{335}{}{Hmph. Ogima know Devourer's children bad, but stop other Devourer's children. Cheyenne kill raiders - others come. Evil begin again.}
{336}{}{That's a tough situation.}

{337}{}{Cheyenne come here big time ago. Much moons pass since. Now - home. Ogima chief, hunters hunt prey, women take crops, guards stop Devourer's evil children.}
{338}{}{Ogima?}
{339}{}{Bad people?}
{340}{}{Hunters?}
{341}{}{}
{342}{}{That's all I wanted to know.}
{343}{}{Ogima big smart. Water spirits, fire spirits protect him. Ogima find camp, talk bad people. Ogima talk you - me no talk good.}
{344}{}{Kill animal, take animal, eat animal. Feed Cheyenne.}
{345}{}{Were you a hunter?}
{346}{}{Before guard? No. Makozid no hunter, Makozid scout, theb Ogima make Makozid guard.}
{347}{}{Do you still remember how to scout? Can you teach me?}

#Обучение

{350}{}{No, paleface. Me no teach. Find teacher in camp.}
{351}{}{No chance? Oh well.}
{352}{}{No, paleface. You outsider. Outsider dangerous. Cheyenne no help dangerous outsider.}
{353}{}{You don't trust me? Oh well.}
{354}{}{Yes, paleface, you loyal. But do favor before me teach.}
{355}{}{Sure, what do you need?}
{356}{}{The demands never stop, do they?}

{357}{}{Long talk. Bring sandwich, bring milk. Me hungry.}
{358}{}{Sandwich and brahmin milk. I'll be right back!}
{359}{}{I'll think about it.}
{360}{}{Here's the sandwich and brahmin milk.}
{361}{}{Ha! You see, good have two sides, bright side, dark side. Sometimes, dark side give more knowledge.}
{362}{}{What do you need?}
{363}{}{Will you teach me how to scout now?}
{364}{}{Yes. You earn knowledge. You use for good.}
{365}{}{Great! Let's get started.}
{366}{}{I'll be back later. Right now I have things to do.}

{367}{}{Can you teach me about scouting now?}
{368}{}{After everything I've done for you!}

{369}{}{You learn how to survive in the wild. You have received +3 to your Outdoorsman skill.}
{370}{}{You learn how to survive in the wild. You have received +5 to your Outdoorsman skill.}

##########################################################
#
#       Состязание
#
##########################################################

#Диалог для состязания:

{371}{}{Fine, paleface. Be your way.}
{372}{}{Give me some time. I'll be back for the fight later.}
{373}{}{Let's get started!}
{374}{}{No, paleface. Fight only with honor when fighters equal. You strength only equal children.}
{375}{}{Don't make excuses. You're just too cowardly to fight me!}
{376}{}{Wait until I get my strength back then.}
{377}{}{Good warrior not only strong. Good warrior patient.}
{378}{}{Whatever.}
{379}{}{So be it. Go in circle. Step out - lose. Ask mercy - lose. Leave things in chest, then we begin.}
{380}{}{Let's go.}

#Плавающие фразы при состязании

{381}{}{Warrior step outside circle, lose!}
{382}{}{I lost!}
{383}{}{I won!}
{384}{}{It's a draw!}

{385}{}{You big weak. You want fight - you crazy. I hope pain teach you new wisdom.}
{386}{}{You big strong! You win. Thank you, outsider.}
{387}{}{Tie! Big surprise! Thank you, outsider.}
{388}{}{Fine, let's rest.}

{392}{}{No, paleface. You stranger, me stranger. No fight.}
{393}{}{You don't trust me? Fine...}
{394}{}{Maybe later, then.}

##########################################################
#
#       Радиостанция
#
##########################################################

{400}{}{[He scratches his head and frowns] Hmm... Strange talk. Ray-dee-oh?}
{401}{}{Don't give me that shit. You understand me just fine. Tell me where it is, now!}
{402}{}{It would look like an old house from before the war. Has a big bowl on it.}
{403}{}{I'll find it without you then.}

{404}{}{NO!!! Sacred place! Outsiders forbidden!}
{405}{}{Tell me, you scum, or I'll bury everyone in this village!}
{406}{}{Even me? I've proven I can be trusted, haven't I?}
{407}{}{[He sighs] Holy place... Me no decide. Talk chief.}
{408}{}{I'll go talk to Ogima, then.}

{409}{}{You no scare me! Me Bear's Paw! Leave!}
{410}{}{Well, look at you. How tough.}

{411}{}{Fine. We go, paleface.}
{412}{}{[Follow him.]}
{413}{}{Hold on, I have to do something first.}

#Female character
{1300}{}{Stop, paleface! Me - Makozid Bear's Paw, guard Cheyenne. Me watch you. You finish business quick. You leave.}
{1307}{}{Good talk, paleface.}
{1320}{}{Paleface!}
{1321}{}{Paleface!... Hmm. You eyes... Children of Devourer's eyes.}
{1350}{}{No, paleface. Me no teach. Find teacher in camp.}
{1352}{}{No, paleface. You outsider. Outsider dangerous. Cheyenne no help dangerous outsider.}
{1354}{}{Yes, paleface, you loyal. But do favor before me teach.}
{1364}{}{Yes. You earn knowledge. You use for good.}
{1368}{}{After everything I've done for you!}
{1371}{}{Fine, paleface. You get wish.}
{1374}{}{No, paleface. Fight only honor when fighters equal. You strength only equal children.}
{1385}{}{You big weak. You want fight - you crazy. I hope pain teach you new wisdom.}
{1392}{}{No, paleface. You stranger, me stranger. No fight.}
{1406}{}{Even me? I've proven I can be trusted, haven't I?}
{1411}{}{Fine. We go, paleface.}
