{100}{}{Ogima the Black Cloud, the chief of the tribe.}
{101}{}{You see an old Cheyenne tribal chief.}
{102}{}{You should not have done it, outsider.}
{103}{}{You betrayed our trust, and for what? I have nothing you'd want anyway.}

###############################################################
#
#  Начало диалога
#
###############################################################

#Требование убра'ь оружие из рук
{110}{}{We're a peaceful tribe, outsider. We will not talk with weapons in hand.}
{111}{}{Your tent, your rules. [put your weapon away]}
{112}{}{Then we will not talk.}
{113}{}{Outsider will put his weapon away if he wants to speak.}

#Про могилы
{115}{}{And so appears the man whose greed is more important than the peace of our dead...}
{116}{}{What are you talking about?}
{117}{}{Someone disturbed our graves. It wasn't animals and it wasn't raiders. It's obvious to us both, but let our opinions stay with us. It can't be undone now, can it?}
{118}{}{Er... Okay, I guess. But I wanted to talk to you.}
{119}{}{Oh... Uh, I'll go fill in the graves, then.}

#С'ар' диалога
{120}{}{Greetings, outsider. What guided your path to our village?}
{121}{}{Can I ask you about this area?}
{122}{}{I want to talk about that sick boy, at the healer.}
{123}{}{Why is Makozid following me?}
{124}{}{Your tribe doesn't have much interest in civilization, does it?}
{125}{}{I'm looking for a radio station around here. Do you know where it is?}
{126}{}{Let's talk about the raiders.}
{127}{}{Nothing. I'm leaving.}
{128}{}{The raiders are gone. What will happen to your tribe now?}

###############################################################
#
#  Про мес'нос'ь
#
###############################################################

#Список вопросов
{130}{}{The gods rarely touch these lands with their sights. There is nothing special here. When the wasteland devours our valley, this will go, too.}
{131}{}{Tell me more about your tribe.}
{132}{}{Tell me more about this settlement.}
{133}{}{Tell me more about the raiders.}
{134}{}{What's around the camp?}
{135}{}{Does anyone else live around here?}
{136}{}{That's all.}

#О'ве'ы
#140 We honor our gods and don't rebel against other people's, wishing only to live in peace and prosperity.
#But the thing is that in the nest of the World Devourer's kids - Reno! The tribe had other opinion back then...
#We hoped to trade and buy those amazing things... Er... Yes, technology.
#But in result we were discovered by dark hearted raiders under the leadership of Big Louie.
#That's how he is called now. And now we don't welcome outsiders.

{140}{}{Our tribe is growing crops and herding brahmin. It's the only things that the Heavenly Mother left to us. But even the last of what we have are now being taken from us by the parasites - those you'd call "raiders". Sometimes I wonder if we have angered the Ruler of Life, to bring such dark times to our people...}
{141}{}{Our village is unwelcoming, but wanderers may always find food and rest here... For payment, of course. Also, the healer Niskigvan, with the help of Heavenly Mother, can heal wounds and pull poison from your body.}
{142}{}{Children of the World Devourer. Their dark lair lays to the north. Don't go there unless you have a reason to, for not all who go there return.}
{143}{}{The valley, the mountains, and our tribe - that is what wanderers will find here. But do not approach the World Devourer's children in their nest to the north.}
{144}{}{Few choose to live close to the Devourer's children. The brave ones had left this place many moons ago, now it is many days long to go to the nearest camp. Reno, Gerlach, and Poseidon Oil are all that eye of Cheyenne saw... Well, besides the legends.}
{145}{}{I have another question.}
{146}{}{That's enough.}

#Про поселения
{150}{}{Where is Reno?}
{151}{}{What's Gerlach?}
{152}{}{Poseidon Oil? What is that?}
{153}{}{Legends?}
{154}{}{I already know of those. Let's talk about something else.}
{155}{}{Reno, a city cursed by the gods. Evil spirits in the forms of men wander in those canyons of metal, glass and concrete. If you are wise, you will stay away from there.}
{156}{}{A camp of those desperate, who ran away from Reno. May the Heavenly Mother give them her blessing.}
{157}{}{A city of the dead to the north. We call it Gecko due to the fierce animals that live there with their large packs, but "NPP Poseidon Oil" is what's written on the largest building. Be careful if you go there - the hunters that first explored it were poisoned by spirits they could not see. Niskigvan the Ruffled Feathers fought two whole moons to save their lives!}
{158}{}{Well... Our shepherd, who went far to the north, claims that there is a wondrous city in the mountains made of white stone and eternal light, protected by warriors in green armor who never rest. But he is the only one who saw it, and many think he is... Unreliable.}

###############################################################
#
#  Про лечение Маконса
#
###############################################################

{200}{}{Niskigvan does everything he can, but I'm afraid it is hopeless. Makkon the Little Bear is doomed to be crippled forever... If he even survives.}
{201}{}{Leave it. Niskigvan fights to save him, but I'm afraid it is hopeless. Makkon the Little Bear is doomed to be crippled forever... If he even survives.}

#Не' дос'ижения де'оубийцы
{202}{}{I'm a doctor, I can fix this. Makkon will be dancing and chasing girls before you know it!}
{203}{}{Let's talk about something more pleasant.}
{204}{}{Never mind, then...}

#Переход к выбору способов
{205}{}{You? [he shakes his head] Your hands and eyes speak the truth that your words do not. Don't fool yourself, outsider. You are no healer.}
{206}{}{Hmm. Niskigvan will not trust an outsider's medicine easily. How the outsider is going to heal the child?}
{207}{}{With chems. Trust me, your kid won't even remember he was crippled!}
{208}{}{Pre-war medicine. What else?}
{209}{}{With my hands, of course. We won't need anything else.}
{210}{}{I'll take him somewhere with functional medical equipment, and will perform a surgery.}
{211}{}{This requires complex reconstructive surgery. Niskigvan and I will do it together.}

{212}{}{Chems?! By the name of the Heavenly Mother, I forbid you from even touching this boy! This poison is only fit for the World Devourer's children!}
{213}{}{Let me explain...}
{214}{}{There will be no discussion! Poisoning yourself with chems is like giving away your soul to the Devourer, while still being alive.}
{215}{}{What does that even have to do with... Oh, forget it.}

{216}{}{No! Our tribe has suffered from this pre-war poison before. By the will of Heavenly Mother, we will never allow to sicken our boy with it.}
{217}{}{Fine, we can find another way.}
{218}{}{Even one blessed by the Heavenly Mother can not heal such an injury only with hands.}
{219}{}{No way!}
{220}{}{Please understand, he needs extensive and complex treatment and surgery.}

{221}{}{Can you explain what your foreign treatment will do what Niskigvan's cannot?}
{222}{}{You see, your healer uses herbs to treat injuries, but the effect is too slow, and not powerful enough to reduce the swelling, or to heal the bones together. So, the injury will start to swell again in some time. It's a loop. Makkon needs alternative treatment.}
{223}{}{Your herbal medicine is too slow. Makkon's condition will progress to gangrene soon. If we don't start proper treatment right now, then Niskigvan will have to amputate the boy's legs, or worse!}

{224}{}{Hm, I hope Niskigvan will understand you better than old chief... But what treatment outsider is offering?}
{225}{}{Clean out the pus, bleed out the injury, reduce the inflammation, and then set the bones.}
{226}{}{You're going to cut him while he's still alive?!}
{227}{}{Under herbal anesthesia.}
{228}{}{Under alcoholic anesthesia.}
{229}{}{Under pre-war medicinal anesthesia.}
{230}{}{Yes. He'll have to endure it.}

{231}{}{Unacceptable! By the name of the Heavenly Mother, I forbid you from even touching this boy! This treatment is only fit for the World Devourer's children!}
{232}{}{Let me explain...}

{233}{}{Gods, to even think of it is sickening! But... Perhaps you're right. Niskigvan has struggled for three moons already, and it has only prolonged the boy's suffering. Your ways may be necessary. But... I... Tell me, how many bones have you mended in your life, outsider?}
{234}{}{[Make assuring gesture] Enough.}
{235}{}{Gods, to even think of it is sickening! Bleed him out?! What are you saying!!! Oh Heavenly Mother...}
{236}{}{I'm not sound convincing enough? Well, maybe you'll change your mind later.}

{237}{}{This answer soothes me. I give you my permission. But if something happens to the boy, then the Cheyenne's hate will go down upon you! Our gods will exact their punishment, and the path to our lands will be closed to you forever! As for now, go to Niskigvan, and may the Heavenly Mother guide your hands!}
{238}{}{[Leave.]}
{239}{}{You got permission to cure Makkon.}

{240}{}{I'm sorry. Let's talk about something more pleasant.}
{241}{}{I really shouldn't get involved. Let's talk about something more pleasant.}
{242}{}{Not convinced, huh? Let's talk about something else.}

#Ес'ь дос'ижение де'оубийцы
{250}{}{[He leans forward, peering into your eyes] ...children have died at your hands before, haven't they?}
{251}{}{That was an accident, chief! You have to believe me! That kid was just in the wrong place at the wrong time!}
{252}{}{Yes, they have. But I want to help here.}
{253}{}{Uh, no. Honest.}
{254}{}{What?! Don't fuck with me, old man, or I'll cook every kid in the tribe over your campfire!}

{255}{}{[He studies your face, then nods] I believe you. This evil not typical of a man who has done so much good. You can count on my trust.}
{256}{}{Good.}
{257}{}{You cannot be trusted even by yourself, until you redeem yourself with good deeds.}
{258}{}{Do I have sign saying "karma devil" on me? Okay, I'll go do some good deeds in the world and be right back.}
{259}{}{As if I care about your opinion. Your loss, old man.}
{260}{}{Oh, no, wanderer. You cannot lie to me. I can see the stain upon your soul.}
{261}{}{Fine, you're right. He wasn't the first victim of mine. But I still want to help.}
{262}{}{No, outsider. We do not need, nor want your kind of help.}
{263}{}{We'll see about that, chief!}
{264}{}{As you wish.}

{265}{}{The evil of your actions still outweighs the good you have done, wanderer. The death of any child is greater than a thousand good deeds.}
{266}{}{Jeez, you murder one child and no one ever forgets it. Fine, I'll keep trying.}
{267}{}{}
{268}{}{Is that a no? You really could be more clear about this.}
{269}{}{You got a problem with child-killers, old man?}

{270}{}{[He shakes his head] Why do you threatening an old man? Will this solve anything?}
{271}{}{No. But it'll make me feel a lot better! [punch him in the face]}
{272}{}{I suppose you're right. I'll go peacefully.}

{273}{}{Get out! May your path never cross that of the Cheyenne again. May even the coyotes shun your remains!}
{274}{}{Fine, I'll go peacefully.}
{275}{}{That was a bad idea, chief. [punch him in the face]}

###############################################################
#
#  Мини-квес'ы
#
###############################################################

#Квес' на очис'ку план'аций
{300}{}{When playing with a snake, don't let her come too close. This is a dangerous world.}
{301}{}{In other words, you don't trust outsiders.}
{302}{}{[He nods] Many outsiders come to the Cheyenne with beautiful words and ugly thoughts. Makozid the Bear Paw watches outsiders, so that they do not do evil in our tribe.}
{303}{}{Do you need help with anything?}
{304}{}{I see. Let's talk about something else.}
{305}{}{I can take a hint. I'll go.}

{306}{}{We need nothing from outsiders. But if you look to earn your food and shelter, then we have work for you.}
{307}{}{If the reward's worth it, then sure.}
{308}{}{You don't need to give me anything. I'm happy to help anyway.}
{309}{}{What is it?}
{310}{}{Maybe later. Let's talk about something else.}

{311}{}{The Devourer has dropped his seed among our crops. From it grows plants that crave flesh. They keep our women from collecting crops, but I cannot spare the men to kill them. Clear the plantation, and we will reward you.}
{312}{}{How much will you pay?}
{313}{}{Here's my counter-offer: I clear the plantation, and you don't pay me a dime.}
{314}{}{Fighting plants? No, I don't think so. Take care.}

{315}{}{We can give you 300 dollars for this. Do you agree?}
{316}{}{Sounds great. I'll be back when the job's done.}
{317}{}{Keep the money. I'll do it for free.}
{318}{}{Very good. The crops are to the west. We await good news, outsider.}
{319}{}{I'm going.}

{320}{}{About those killer plants...}
{321}{}{Yes, outsider?}
{322}{}{Where are they, again?}
{323}{}{How many are there?}
{324}{}{They're all dead.}
{325}{}{Nothing.}
{326}{}{}
{327}{}{To the west, outsider. On the other side of the camp.}
{328}{}{Five. Look carefully, for they hide well from the eyes of their victims.}
{329}{}{This news will warm the hearts of our women. We thank you, wanderer.}
{330}{}{What about my reward?}
{331}{}{Your gratitude is rewarding enough. I don't need anything.}
{332}{}{That fight really wore me out. Can I get some food instead of the money?}
{333}{}{Here is your 300 dollars, outsider. May our paths cross again, someday.}
{334}{}{It's not much, but it's something. Bye, chief.}
{335}{}{Not bad! I'll see you around, chief.}
{336}{}{This is very surprising, outsider. The Cheyenne thank you for your kindness. But I cannot let you leave empty handed. Take this sandwich, so you may have the strength to help others.}
{337}{}{Thank you.}
{338}{}{That is fair. Wait here for a moment. [the chief goes outside for a minute and returns with five sandwiches, which he hands to you]}
{339}{}{Yes!}

#Квес' на водосборник
{350}{}{To replace the earth with concrete and the tree with iron is to forget the truth of one's self. The people of the cities lost their spirit. Our ancestors lived in harmony with nature, paying honor to the Heavenly Mother and Ruler of Life, and were spared the folly that destroyed the world.}
{351}{}{But on the other hand, you still use leftover technology.}
{352}{}{...yes. But only when there is no other choice. But even what is left will soon turn to ash.}
{353}{}{Something is broken?}
{354}{}{I see. I have another question.}

{355}{}{Rust has taken the water tank we use for our crops. To fix it, we need parts and knowledge, and we have neither.}
{356}{}{I can help you.}
{357}{}{That's a shame. Let's talk about something else.}
{358}{}{Help us? Thank you, outsider, but we have nothing to offer in return.}
{359}{}{Let's make a deal: I repair the water tank, and get regular meals in return.}
{360}{}{Too bad. Good luck with that, then.}
{361}{}{You don't need to pay. I just want to help.}
{362}{}{Well, no repairs then.}

{363}{}{[He nods] We accept. Our cook will treat you as our own... But only after the work is complete.}
{364}{}{I'll do it.}
{365}{}{Actually, I changed my mind. No deal.}
{366}{}{You've made an old man happy, outsider. And remember, if this task proves too difficult, perhaps another out there in the wasteland can help you. May the Ruler of Life guide your path.}
{367}{}{I'll be back with good news.}
{368}{}{[He nods in understanding.]}
{369}{}{Wow, not much for haggling, huh?}
{370}{}{You've made an old man happy, outsider. All of the Cheyenne will be grateful. Remember, if this task proves too difficult, perhaps another out there in the wasteland can help you. May the Ruler of Life guide your path.}
{371}{}{I'll be back with good news.}

{372}{}{So, how's the water tank?}
{373}{}{No longer will nature's tears be wasted on the barren earth. Every drop's gift of life will now bless our crops. We are grateful, outsider. How can we repay you?}
{374}{}{I want to get sandwiches regularly.}
{375}{}{I want a whole bunch of sandwiches right now!}
{376}{}{Repay me by making good use of the water. That's all.}

{377}{}{}
{378}{}{That is fine.}
{379}{}{Thirty sandwiches is all we can make right now. May they fill your belly for many days.}
{380}{}{Great! That's all I needed.}
{381}{}{The Cheyenne will not forget your kindness. Few outsiders come to us with such pure intentions. May the others in this world pay the same kindness to you for as long as you walk your path.}
{382}{}{Don't mention it, chief!}

{383}{}{That is fair. Omakaki will put five sandwiches aside in a box for you. But remember, sandwiches don't last forever. If you don't get here in time, they will feed only our crops.}
{384}{}{Deal!}
{385}{}{Actually, I changed my mind. Give me all the sandwiches you've got right now, and we'll call it even.}
{386}{}{Don't bother, I don't need a reward. Consider this an act of good will.}
{387}{}{May the Heavenly Mother protect you in the Wasteland.}
{388}{}{Uh, yeah. You too.}

###############################################################
#
#  Радиос'анция
#
###############################################################

{400}{}{Radio... What? I know nothing of this.}
{401}{}{We have nothing to hide from the one who saved us from the Devourer's children. I will show you our place of worship.}
{402}{}{Let's go.}
{403}{}{This is a sacred place, but I feel I can trust one with your pure heart. I will take you there.}
{404}{}{We will never forget what you did for Makkon. We protect this place from outsiders, but I feel we have nothing to fear from you. I will bring you there.}
{405}{}{I have other questions first.}
{406}{}{Not now, I'll come back later.}

###############################################################
#
#  Си'уация с рейдерами
#
###############################################################

#Информация о рейдерах
{500}{}{The grief and pain of this land.}

{501}{}{I have news for you.}
{502}{}{Why don't you fight back?}
{503}{}{Tell me about these raiders.}
{504}{}{Where are they located?}
{505}{}{Don't you want to get rid of them?}
{506}{}{Let's talk about something else.}
{507}{}{That's all I want to know. Bye.}
{508}{}{Right.}
{509}{}{}

{510}{}{Why would I tell you? Should not you be telling me?}
{511}{}{Watch your mouth, chief.}

{512}{}{They are the children of the World Devourer. }
{513}{}{They sleep to the north. Don't go there unless you have to, for not all who go there return.}
{514}{}{If the predator steps away from his prey, then other predators will come for the meal. We can only pray for our gods to protect us.}
{515}{}{We have had enough of war. And besides, what can a man with a spear do against demons with guns and sturdy armor?}
{516}{}{You don't have to do everything yourself. You can hire someone to get rid of them for you.}
{517}{}{And put our life in a stranger's hands? If the stranger fails, it will bring the anger of the Devourer to us. We cannot take that risk.}
{518}{}{What if we could get rid of them in a quieter way?}
{519}{}{[He narrows his eyes thoughtfully] What are you thinking of, outsider?}
{520}{}{They have just one source of water. If we poison it...}
{521}{}{Not yet, but if you bring me to their camp, I'm sure I can think of something.}
{522}{}{No, not yet.}
{523}{}{This is cunning, outsider. But you will have to go elsewhere to find this poison. We have nothing like that here.}

{524}{}{[He studies your face and nods] The gods tell me you may do great things for the Cheyenne. Fine, then. I can only bless your path. Gekek the Hawk, the warrior guarding the entrance to our camp, will show you the way.}
{525}{}{Before I go, can you tell me more about the raiders?}
{526}{}{Fine, I'll go talk to Gekek.}
{527}{}{[He studies your face and frowns] The gods whisper to me of caution. I cannot trust you with this, outsider.}
{528}{}{As you wish. Can you tell me more about the raiders?}
{529}{}{Then we have nothing to discuss. Bye.}

#Сдача квес'ов на рейдеров
{530}{}{You have news, outsider?}
{531}{}{The raiders are dead. Instead of moonshine, they're drowning in their own blood.}
{532}{}{The raiders are dead. Poison is a dirty method...but very effective!}
{533}{}{You don't have to worry about the gang's leader. He went to Vegas and he's not coming back.}
{534}{}{The gang's leader is dead.}
{535}{}{Oh, sorry. I wanted to tell you something else...}
{536}{}{Not right now. I'll talk to you later.}

{540}{}{More children of the Devourer will come. We will break the cycle before it begins again. These lands have fed the Cheyenne for many years, but now it is time to leave them.}
{541}{}{You're leaving? Why didn't you just do that before?}
{542}{}{We have children, eldery, brahmin, and everything we must carry. We would have been noticed. But now, no one will stop us.}
{543}{}{Where will you go now?}
{544}{}{West, to where the sun drowns in a sea of tears. Our ancestors spoke of it.}
{545}{}{Are you sure other children of the Devourer will come?}
{546}{}{There will always be more of them. But now, our tribe is wiser. We will protect ourselves.}
{547}{}{It's a little sad to leave after all this, isn't it?}
{548}{}{The earth remembers. The earth will remember for many years. So will we.}

{549}{}{How can Makkon the Little Bear make this trip?}
{550}{}{[He sighs] Only Heavenly Mother knows.}
{551}{}{If I can operate on him before you leave, he might just make it. But I need your permission, first.}
{552}{}{Of course. We trust you.}
{553}{}{Thanks.}
{554}{}{How soon will you get head out?}
{555}{}{Oh, not soon. It will be many moons before we are ready.}
{556}{}{}
{557}{}{}
{558}{}{Before you leave, I want to ask you something.}
{559}{}{Well, stay safe.}

{560}{}{The gods warn me that the danger remains. Did you check? Maybe the Devourer has gifted some with life beyond death.}
{561}{}{I'll check it out and come back.}

{562}{}{[The chief nods and smiles] Even the heavens must have heard the screams from that dark camp! You have brought joy to an old man, outsider. The Cheyenne are now free! Not even the Devourer can challenge your canniness and strength. Our legends will remember you as Vabigagosh - the White Fox!}
{563}{}{Not bad.}
{564}{}{[The chief nods in satisfaction] Even the predator has its hunter. The gods themselves have blessed this battle!}
{565}{}{Maybe.}
{566}{}{Even the Devourer will not leave his last and most beloved child.}
{567}{}{You mean Big Louie? Right, we have to deal with him somehow.}
{568}{}{But Big Louie is not the only child in the Wasteland.}
{569}{}{I'll see what I can do.}
{570}{}{This begins a new era for the Cheyenne! We will remember you always as Vabimakvu - the White Bear! Please, take this amulet. Remember our people when you wear it, and may it bring light to your path forever.}
{571}{}{Not bad.}

#Female character
{1115}{}{And so appears the woman, whose greed is more important, than the peace of our dead...}
{1118}{}{Er...okay, I guess. But I wanted to talk to you.}
{1120}{}{Greetings, outsider. What guides your path to our village?}
{1205}{}{You? Your hands and eyes speak the truth that your words do not. Don't fool yourself, outsider. You are no healer.}
{1206}{}{Hmm. Niskigvan will not trust an outsider's medicine easily. How will you heal the child?}
{1214}{}{There will be no discussion! Poisoning yourself with chems is as offering your soul to the Devourer while still alive.}
{1221}{}{Can you explain how your foreign treatment will do what Niskigvan cannot?}
{1224}{}{What treatment can you offer?}
{1237}{}{Then I give you my permission. But if something happens to the boy, then the Cheyenne will be closed to you forever! Go to Niskigvan, and may the Heavenly Mother guide your hands!}
{1252}{}{Yes, I have. But I want to help here.}
{1255}{}{[He studies your face, then nods] I believe you. This evil not typical of a woman who has done so much good.}
{1257}{}{You cannot be trusted until you redeem yourself with good deeds.}
{1260}{}{Oh, no, wanderer. You cannot lie to me. I can see the stain upon your soul.}
{1265}{}{The evil of your actions still outweighs the good you have done, wanderer. The death of a child is greater than a thousand good deeds.}
{1303}{}{Do you need help with anything?}
{1306}{}{We need nothing from outsiders. But if you would earn your food and shelter, then we have work for you.}
{1308}{}{You don't need to give me anything. I'm happy to help anyway.}
{1318}{}{Very good. The crops are to the west. We await good news, outsider.}
{1324}{}{They're all dead.}
{1327}{}{To the west, on the other side of the camp.}
{1329}{}{The women will be glad. Thank you, wanderer.}
{1336}{}{This is very surprising, outsider. The Cheyenne thank you for your kindness. But I cannot let you leave empty handed. Take this sandwich, so you may have the strength to help others.}
{1358}{}{Help us? Thank you, outsider, but we have nothing to offer in return.}
{1365}{}{Actually, I changed my mind. No deal.}
{1366}{}{You've made an old man happy, outsider. And remember, if this task proves too difficult, perhaps another out there in the wasteland can help you. May the Ruler of Life guide your path.}
{1370}{}{You've made an old man happy, outsider. All of the Cheyenne will be grateful. Remember, if this task proves too difficult, perhaps another out there in the wasteland can help you. May the Ruler of Life guide your path.}
{1385}{}{Actually, I changed my mind. Give me all the sandwiches you've got right now, and we'll call it even.}
{1514}{}{If the predator steps away from his prey, then other predators will come for the meal. We can only pray for our gods to protect us.}
{1519}{}{[He narrows his eyes thoughtfully] What are you thinking of, outsider?}
{1523}{}{This is cunning, outsider. But we have nothing like that here.}
{1524}{}{[He studies your face and nods] The gods tell me you may do great things for the Cheyenne. Fine, then. I can only bless your path, but Gekek the Hawk will show you the way. He is guarding the entrance to the camp.}
{1530}{}{You have news, outsider?}
{1531}{}{The raiders are dead. Instead of moonshine, they're drowning in their own blood.}
{1560}{}{The gods warn me that the danger remains. Did you check? Maybe the Devourer has gifted some with life beyond death.}
{1562}{}{[The chief nods and smiles] Even the heavens must have heard the screams from that dark camp! You have brought joy to an old man, outsider. The Cheyenne are now free! Not even the Devourer can challenge your canniness and strength. Our legends will remember you as Bensy - Thunder Bird!}
{1570}{}{This begins a new era for the Cheyenne! We will remember you always as Bensy - Thunder Bird! Please, take this amulet. Remember our people when you wear it, and may it bring light to your path forever.}
