{100}{}{You see Omakaki, the cook.}

##############################################################
#               Описания
##############################################################

{101}{}{It's one of the tribe's cooks. She's currently preparing fried gecko.}
{102}{}{It's one of the tribe's cooks. She's currently preparing a stew gecko.}
{103}{}{It's one of the tribe's cooks. She's currently preparing smoked lizard.}
{104}{}{It's one of the tribe's cooks. She's currently preparing brahmin steak.}
{105}{}{It's one of the tribe's cooks. She's currently preparing a salad.}
{106}{}{It's one of the tribe's cooks. She's currently preparing a sandwich.}
{107}{}{It's one of the tribe's cooks, but right now, she's just resting.}

##############################################################
#               Плавающие сообщения
##############################################################

{108}{}{Who walks here?}
{109}{}{They say, outsider walks here.}
{110}{}{Oh!}
{111}{}{It better in shadow.}
{112}{}{It most important that children like me food.}
{113}{}{Hunters always hungry! Eat many food and water!}
{114}{}{All tribe eats me food. It makes me happy when me see.}

{115}{}{Bad smell.}
{116}{}{That not right!}
{117}{}{Me not wants, but you makes me.}
{118}{}{Heavenly Mother could take you man power!}
{119}{}{What tribe you from?}
{120}{}{Cheyenne will remember that forever!}
{121}{}{Traitor.}

{122}{}{Help!!!}

{123}{}{Hmph. Me not speaks to one like you.}
{124}{}{Outsider, no eats that!}
{125}{}{What you eat?}
{126}{}{Who you eat?}
{127}{}{No, outsider! No eats that! That filthy!}
{128}{}{Ugh! Eat filth makes you sick!}
{129}{}{No, me not likes that. Go away.}

{130}{}{Me not knows you.}
{131}{}{Me not feeds you.}
{132}{}{You not Cheyenne.}
{133}{}{Oh...}
{134}{}{What you wants, outsider?}
{135}{}{Me cooks. Only cooks.}
{136}{}{Talk Ogima. Not speak me.}
{137}{}{Me not Ogima.}
{138}{}{Ogima not here. You go, talk Ogima.}
{139}{}{Me not know. Me not help.}

{140}{}{[She watches you in silent terror]}

##############################################################
#               Диалог
##############################################################

#Начало диалога:
{150}{}{Oh! You wants talk me?}

{151}{}{Can you tell me a little about your tribe?}
{152}{}{I'm just curious. What are you doing?}
{153}{}{Come here, woman! I want to feel your juicy "apples"!}
{154}{}{I'm hungry. Feed me, woman!}
{155}{}{I need supplies. Can we trade?}
{156}{}{Actually, I changed my mind. Don't mind me.}
{157}{}{[Leave.]}

#Приз за рейдеров:
{158}{}{Oh, you come get reward! [she smiles] You wait! Me make reward. Many many food! Eat lo-o-ong time!}
{159}{}{Excellent!}

#Шантаж на жратву
{160}{}{No! Not touch me! Not touch me!!!}
{161}{}{Shut up, bitch! I'm hungry! Feed me, or I'll water the crops with your tribe's blood!}
{162}{}{Fine, dry your pants. I feel generous today. [leave]}
{163}{}{Me give food!!! Me give food!!! [she frantically gathers as much food as her shaking hands can carry]}
{164}{}{That's more like it! You'd better be that fast every time. Remember, our gang knows what to do with uppity whores. [leave]}

#Трах:
{165}{}{HELP!!! HELP!!! HELP!!!}
{166}{}{You bitch! Those hunters won't help you!!!}
{167}{}{Wrong answer, whore. [continue pulling off her clothes] If you fight me, our gang will shoot your men, hang your women, and force your children to fight each other to the death. And I'll put you on a spike on the top of the water tower so you can watch every single moment of what you did.}
{168}{}{Fine, fucking savage. You should be flattered... [leave]}
{169}{}{Scum! Nobody will save you!}
{170}{}{[Sobs hysterically and stops moving]}
{171}{}{Good girl. [push her to the ground] Think of your children and don't move.}
{172}{}{YEAH!!! [remove the last of her clothing]}
{173}{}{[Rape.]}
{174}{}{::sob::}

#Неудачный шантаж на жратву
{175}{}{You rude!}
{176}{}{Err...I want to ask something else.}
{177}{}{What a bitch! I'm out of here!}
{178}{}{Fine, I'm leaving.}

#Разговор про еду
{180}{}{Oh! [she smiles] Me cook! Me feeds all tribe. Food good, fresh and delicious. Everyone loves it!}
{181}{}{Yes, I can see people licking their fingers! Can you make me some for the road?}
{182}{}{Yes, I can see people licking their fingers! It smells so good, I have to try some!}
{183}{}{Euugh! [spit] This food stinks like shit! And it looks like it, too! And the cook - well, you get it!}

{184}{}{You wants food? Then, we trade!}
{185}{}{[Trade.]}

{186}{}{[She blushes and smiles even wider] Yes, you wants try? Okay, okay! Me give you one meal!}
{187}{}{Are you serious? I'd love to try some of your food!}
{188}{}{I'm sorry, but I don't have time. Maybe later.}
{189}{}{[She prepares you a sandwich with vegetables, meat, and beans for flavor. You put it in your pack for later.]}
{190}{}{Thank you so much! I'd like to ask you something else.}
{191}{}{[She looks like she's about to cry. You don't think she'll talk to you again.]}

{192}{}{Eh...Ogima says no give outsiders free food.}
{193}{}{Then let's trade.}
{194}{}{Ogima's not greedy, he won't mind. It smells so good!}
{195}{}{Er...Ogima chief. He says...}
{196}{}{You don't seem to understand what I'm saying. Well, see you around.}

##############################################################
#               Ответы на вопросы
##############################################################

{200}{}{Yes. Me give answer.}

{201}{}{Let's talk about something else.}
{202}{}{Tell me about the tribe.}
{203}{}{Tell me about the Black Cloud.}
{204}{}{Tell me about your hunters.}
{205}{}{Nothing. I'm leaving.}

{206}{}{Tribe family. Life good. Hunters finds food. Me makes food. Others works fields. Children helps everywhere. Niskigvan heals. Avanigizhig talks spirits. Ogima chief - helps everybody.}
{207}{}{This Ogima sounds important. Tell me about him.}
{208}{}{Fine. Bye.}
{209}{}{I want to ask something else.}
{210}{}{Ogima Black Cloud very important. He speaks outsiders. He makes important decisions. He calms bad people. Ogima very good, very wise.}
{211}{}{Bad people? Who are those?}
{212}{}{Oh... [she shakes her head] Bad people. Sleeps old building close by. At night, takes food. Rapes women. Beats men. They very, very bad.}
{213}{}{Doesn't anyone protect you? What about your hunters?}
{214}{}{Hunters brings fresh meat. Hunter finds animals, then BOOM! [she drives one fist into her palm] Then brings me dead animal. Me cooks animal, makes food. Everyone needs food. Makes strong body. Hunters eats food, makes strong, go hunts animal again.}
{215}{}{Speaking of food, can I buy or trade some off of you?}

##############################################################
#               Сообщения на инфоокне
##############################################################

{300}{}{You earn 200 experience points for a small raid.}
{301}{}{The cook is hysterical. You scared her too much.}
{302}{}{You earn 500 experience points for assaulting a harmless woman.}

##############################################################
#               Крики при краже качана капусты 
##############################################################

{310}{}{Me food! Not touch!}
{311}{}{Me warns!}
{312}{}{THIEF! Thief, thief, thief!!!}

##############################################################
#               Female character
##############################################################

{1156}{}{Actually, I changed my mind. Don't mind me.}
{1190}{}{Thank you so much! I'd like to ask you something else.}
