{100}{}{You see a lookout.}
{101}{}{You see a raider on patrol.}

# Когда подбегает, чтобы арестовать:
{110}{}{Stop right there!}
{111}{}{You move, you die!}
{112}{}{Hold it, punk!}
{113}{}{Don't move!}
{114}{}{I said don't move!}
{115}{}{You're not getting away!}
{116}{}{You're mine!}

#Если ГГ в одежде рейдера:
{130}{}{The watchman noticed you, but didn't see through your disguise.}
{131}{}{Mold, is that you?}
{132}{}{Hey, wait a minute! Who the hell are you?}
{133}{}{Hey, you in the jacket! Who are you?}
{134}{}{Who is that? Mold, is that you?}
{135}{}{Out to puke again, huh, Mold? You gotta pull it together, man.}

#Когда поймал ГГ:
{150}{}{Freeze! You move, you die!}
{151}{}{Hey, hey! Easy! I'm not moving, see?}
{152}{}{If you put your hand on me, you won't get it back.}
{153}{}{And I thought this would be boring. Let's see what the boss says about you...}
{154}{}{Fine, bring me to your boss. I won't fight.}
{155}{}{[Attack the raider]}
{156}{}{Shut up! You try anything, and there won't be enough of you left to bury.}
{157}{}{Fine, I won't move.}
{158}{}{No, YOU shut up!}
{159}{}{}

#Когда Плесень сдох:
{160}{}{Great.}
{161}{}{Did you know there's a body in those ruins across from the base?}
{162}{}{See you around.}
{163}{}{Yeah, that's Mold. He OD'd, so we threw him out before he started to smell. Weirdest thing is, we can't figure out where he got the shit. Fatso swears he cut him off.}
{164}{}{I see...}

# Когда враждебен, видит и нападает:
{200}{}{Hey, you!}
{201}{}{Waste this bitch!}
{202}{}{I'm gonna fuck you up!}
{203}{}{Do you wanna be gutted or flayed?!}
{204}{}{Let's dance, baby!}
{205}{}{Time to make you cry.}
{206}{}{Hold still while I gut you, will ya?}

# Разговаривает сам с собой:
{207}{}{Nobody...}
{208}{}{This is boring.}
{209}{}{I'm so sick of walking in circles...}
{210}{}{Will this patrol ever end?}
{211}{}{Why am I even doing this?}

# Когда не враждебен: 
{212}{}{Great.}
{213}{}{All's quiet.}
{214}{}{Ain't seen nobody.}
{215}{}{Ain't nobody comin' through here!}
{216}{}{Nothing to say, really.}
{217}{}{I'm on watch.}
