{100}{}{A watchman.}
{101}{}{You see a raider on patrol.}

# Когда поймал ГГ: 
{110}{}{Freeze! You move, you die!}
{111}{}{Hey, hey! Easy! I'm not moving, see?}
{112}{}{If you put your hand on me, you won't get it back.}
{113}{}{And I thought this would be boring. Let's see what the boss says about you...}
{114}{}{[The guard handcuffs you and takes you to a two-story building.]}

# Когда подбегает, чтобы арестовать:
{115}{}{Stop right there!}
{116}{}{You move, you die!}
{117}{}{Hold it, punk!}
{118}{}{Don't move!}
{119}{}{I said don't move!}
{120}{}{You're not getting away!}
{121}{}{You're mine!}

# Когда Плесень сдох:
{122}{}{Did you know there's a body in that ruins across from the base?}
{123}{}{See you around.}
{124}{}{Yeah, that's Mold. He OD'd, so we threw him out before he started to smell.}
{125}{}{I see. Bye.}

#Если ГГ в одежде рейдера:
{130}{}{The watchman noticed you, but didn't see through your disguise.}
{131}{}{Mold, is that you?}
{132}{}{Hey, wait a minute! Who the hell are you?}
{133}{}{Hey, you in the jacket! Who are you?}
{134}{}{Who is that? Mold, is that you?}
{135}{}{Out to puke again, huh, Mold? You gotta pull it together, man.}

# Когда враждебен, видит и нападает:
{200}{}{Hey, you!}
{201}{}{Waste this bitch!}
{202}{}{I'm gonna fuck you up!}
{203}{}{Do you wanna be gutted or flayed?!}
{204}{}{Let's dance, baby!}
{205}{}{Time to make you cry.}
{206}{}{Hold still while I gut you, will ya?}

# Разговаривает сам с собой:
{207}{}{Nobody's there...}
{208}{}{This is boring.}
{209}{}{I'm so sick of walking in circles...}
{210}{}{Will this patrol ever end?}
{211}{}{Why am I even doing this?}

# Когда не враждебен: 
{212}{}{Hey there.}
{213}{}{All's quiet.}
{214}{}{Ain't seen nobody.}
{215}{}{Ain't nobody comin' through here!}
{216}{}{Nothing to say, really.}
{217}{}{I'm on watch.}
{218}{}{Man, this is boring...}

{219}{}{Oh! It's you!}
{220}{}{All quiet. Nothing to worry about.}
{221}{}{Ain't seen nobody.}
{222}{}{No one gets through me!}
{223}{}{Nothing to report.}
{224}{}{How's the boss?}
{225}{}{Boss seems to like you. Respect...}

#Female character
{1110}{}{Freeze! You move, you die!}