{100}{}{You see a shepherd.}
{101}{}{You see a shepherd of the Cheyenne tribe.}

#Первая ветка
{200}{}{Haw!}
{201}{}{Hello. Who are you and what are you doing here?}
{202}{}{}
{203}{}{Let's trade.}
{204}{}{I'm just passing through.}
{205}{}{How much for that shiny metal box, again?}

{207}{}{You blindly purchased a seemingly useless knickknack on the off chance it might be useful someday. You feel like quite the gambler.}

#Первый вопрос, кто таков
{210}{}{I is shepherd! I live here, in field. I watch crops and guide livestock. I is alone, but that is good for me.}
{211}{}{Right. What's that big metal thing in the middle of the field?}
{212}{}{So you watch this whole field, huh? You must have found a lot of interesting things out here. Want to trade? It's a shame I don't have any glass beads... }
{213}{}{A shepherd without sheep, huh? I should be going.}
{214}{}{That big bucket full of poison fire! It fell from sky and spilled. It burned beautiful, but only I saw. Then... Plants that bite grew around it. Hmm.}
{215}{}{Fell from the sky? How interesting! I'll go have a closer look.}
{216}{}{Uh, wait, outsider! Do not go there. That filth burns feet!}
{217}{}{I'll keep that in mind.}

#Бартер
{218}{}{Mmm. I have junk. I trade junk.}
{219}{}{Let's barter.}
{220}{}{I'll come back later.}

#Бартер - тостер
{221}{}{Mmm. I have some junk... Some stuff. And... Something shiny!}
{222}{}{What is it? Will you show me?}
{223}{}{Shiny? This I gotta see!}
{224}{}{Look! [He holds out a metal box emblazoned with a multi-colored animal with big ears. You have no idea what it is, but it looks like a pre-war device. You study a few buttons in the hope that the shepherd hasn't thought to press them.]}
{225}{}{Very tempting. What do you want for it!}
{226}{}{Money! Much money! Trade for... Hmm... }
{227}{}{Deal. Here's the money.}
{228}{}{Sorry, I don't have that much. Maybe later.}
{229}{}{Good!}
{230}{}{Let's talk about something else.}

#Бартер - куртка
{233}{}{How about a leather jacket? It protects against the sun and wind.}
{234}{}{You want clothes? It must be unpleasant walking around half-naked.}
{235}{}{Nah. I is comfortable in own skin.}

{237}{}{It'll be easier just to kill you! You'll sell your junk to the worms, shithead!}

{238}{}{Ooh! [he rubs his hands together] I want that! Deal!}
{239}{}{Give me a second to take it off, then.}
{240}{}{Then remind me, what do you need?}

{241}{}{Ooh! I want that! Deal! [he takes the jacket, rubbing his fingers over the leather with a satisfied nod, and hands you the device]}

#Радиостанция
{250}{}{I'm looking for a radio station somewhere around here. You probably know where it is. Can you show me?}
{251}{}{Hmm... Nah. Chief will angry, hurt with words. Bad.}
{252}{}{Yeah, with my reputation, no one would be happy to hear you helped me. Oh well.}
{253}{}{Let's talk about something else.}
{254}{}{He won't find out. I promise. You can trust me.}
{255}{}{Hmm. [he looks around] Okay. You is good people. I show you.}
{256}{}{Great. Take me there.}
{257}{}{You can do this the easy way, or my gang can make you do it the hard way.}
{258}{}{Uhh - ! No, I show, I show!}
{259}{}{It's important. I need to find that station to find out about my past. Please, can't you help me? I know you're a good man.}
{260}{}{Hmmmm... Pretty talk. Okay. I show you.}
{261}{}{What if I give you this sharpened spear?}
{262}{}{What if I give you this leather jacket?}
{263}{}{What if I give you this cattle prod?}
{264}{}{[He nods and takes it] I show you.}

#Получение копья
{350}{}{Can I borrow your spear? I need it!}

{351}{}{No! You take spear and run away. I lose spear forever!}
{352}{}{No, no! I'll bring it back, I promise!}
{353}{}{Ogima asked me to kill the dangerous plants. I need that spear to do it!}
{354}{}{Give me the damn spear, now!}
{355}{}{Don't you think you're being selfish?}
{356}{}{Fine, fine. I'll manage without your help.}

{357}{}{[He grits his teeth and clutches his spear tighter.]}
{358}{}{[Grab the spear and pull it away from him.]}
{359}{}{Fine, have it your way.}
{360}{}{[You grab the spear and pull, but the shepherd sets his feet and pulls back, grunting in effort.]}
{361}{}{Hrrngg! [pull harder]}
{362}{}{Fine, keep the damn spear! [let go]}
{363}{}{[The shepherd falls onto his back] Ooof!}
{364}{}{Ha! Serves you right. [leave]}
{365}{}{[This shepherd's pretty strong! He pulls back on the spear, his veins standing out on his arms and neck so intensely that they look like they'll pop any second.]}
{366}{}{HRRRAAAGGHHH!! [pull with all of your strength]}
{367}{}{[Suddenly let go of the spear.]}
{368}{}{[Snatch the spear while the shepherd is stunned] Aha!}
{369}{}{Ha! Now shut up... }
{370}{}{[The shepherd overpowers you, pulling the spear back and sending you sprawling to the ground] Ha! I is strong! Outsider is weak!}
{371}{}{Do you know who you're fucking with?! Come here and I'll rip your fucking arms out!}
{372}{}{Fine, fine. No fighting.}
{373}{}{Ha-ha-ha! Outsider act bad, but no! I see in your eyes!}
{374}{}{No, I is not selfish! You is greedy!}
{375}{}{I politely asked to borrow your spear for just a little while, and you wouldn't even let me do that. YOU'RE greedy.}
{376}{}{NO!}
{377}{}{YES!}
{378}{}{No, outsider is... Is... No, no! I wanted give spear!}
{379}{}{You see? Someone asks you for help, and you can only think of yourself. The tribe will be so disappointed when I tell them!}
{380}{}{Ahhh, no! Outsider no tell! Take spear, take it! [he throws the spear down on the ground and steps back, grabbing his head in hysteria]}
{381}{}{Right choice, pal.}
{382}{}{I no trust outsiders!}
{383}{}{Why don't you try? Maybe the world isn't as bad as you think.}
{384}{}{Ha! Outsiders bring pain to tribe. Ogima say tribe should avoid outsiders!}
{385}{}{Well, not everyone, right? I'm not like the others!}
{386}{}{No, spirits say different.}
{387}{}{Hmm... Spirits not sure about you. Strange.}
{388}{}{This means you have the chance to help a good person. Isn't that right?}
{389}{}{Hmm... Ogima say must help good people. Here, take spear.}
{390}{}{Thank you, friend. I'll use it well.}
{391}{}{Ha! You're so easy to fool!}
{392}{}{Thank you. I'll bring it back once I'm done.}
{393}{}{No. I need spear to herd moo-moos. Tribe need it.}
{394}{}{You say you kill plants, but you have no spear? [he shakes his head] Stupid.}
{395}{}{So can I borrow the spear?}
{396}{}{You must promise you will bring back!}
{397}{}{Uhh... I'll try.}
{398}{}{Promise!}
{399}{}{I solemnly swear I will return the spear after killing the dangerous plants, may I be damned if I don't.}
{400}{}{I can't promise that, sorry.}
{401}{}{Then I keep spear.}
{402}{}{[The shepherd solemnly hands you the spear as if it's a holy relic] May its blade forever point forward on path of light.}
{403}{}{Uh, yeah, sure. I'll be back.}
{404}{}{Ha! What an idiot!}
{405}{}{Jeez, what a hassle. You sure you don't want to write up a contract or something?}
{406}{}{Thank you. I'll bring it back when I'm done.}
{407}{}{No. The tribe say outsider is bad.}
{408}{}{Here's your spear.}
{409}{}{[The shepherd's eyes widen in astonishment.]}
{410}{}{Yes, I'm giving it back. I'm honest.}
{411}{}{Pfft, look at your face! Nah, I'm just kidding, it's mine now.}
{412}{}{Outsider no steal? Outsider not forget about poor shepherd?}
{413}{}{Just take the damn spear!}
{414}{}{Yes, that's right. I want to be good.}
{415}{}{No, outsider just kidding. I'm keeping it.}
{416}{}{[The shepherd takes the spear and bows his head respectfully] Outsider do right thing.}
{417}{}{Yeah, I'm just that kind of guy. See you.}
{418}{}{[The shepherd pushes the spear towards you] Outsider is good. Outsider need it. Take!}
{419}{}{Thank you, friend! I do need it.}
{420}{}{The shepherd gave you his spear as a gift. It seems he trusts you.}

#Починка моста
{450}{}{I need you to carry something heavy for me.}
{451}{}{Nah. I no want to carry heavy things.}
{452}{}{I wasn't asking. That's an order!}
{453}{}{I want to fix the bridge. Don't you care about helping the tribe?}
{454}{}{Oh yeah? What if I tell your chief that you fed the brahmin that green filth in the field?}
{455}{}{Forget it. Let me ask you something else.}
{456}{}{Fine, I'll do it myself.}

{457}{}{What?! I no feed moo-moos green filth! No!}
{458}{}{Oh, I know that. But the chief doesn't. You see what I'm getting at?}
{459}{}{Grr... Bad outsider! All outsiders bad! Leave!}
{460}{}{I'm warning for the last time - help me with those planks, or I'll turn the whole tribe against you! I'm pretty sure they'll believe me, too - I bet there's a reason you live all by yourself.}
{461}{}{Fine, whatever.}
{462}{}{[He nervous] N-no! Outsider wrong! Only... I help anyway. I strong. No problem.}
{463}{}{Move your ass, already!}
{464}{}{Great! Get to work!}
{465}{}{Maybe I don't need your help after all.}

{466}{}{[He punches himself in the chest and stands up straight] I is NO SLAVE!}
{467}{}{Oh, look at the big man!}
{468}{}{[He pauses indecisively for a moment before glancing in the direction of Big Louie's base] I... No want trouble. What I carry?}
{469}{}{Move those planks to the bridge. Double time!}
{470}{}{Nothing, I can do it without you.}

{471}{}{I no trust outsider. Outsiders never do thing just to help.}
{472}{}{Fine. Maybe I can change your mind about me.}
{473}{}{Outsider wants to help? Hmm... Outsider is good people. I help.}
{474}{}{Great! We have to take those planks to the bridge... }
{475}{}{I think I can do it without you. Rest.}
{476}{}{With the shepherd's help, you assemble a drawbridge from the wooden planks.}
{477}{}{The bridge is complete.}

#Female character
{1204}{}{I'm just passing through.}
{1212}{}{So you watch this whole field, huh? You must have found a lot of interesting things out here. Want to trade? It's a shame I don't have any glass beads... }
{1227}{}{Deal. Here's the money.}
{1375}{}{I politely asked to borrow your spear for just a little while, and you wouldn't even let me do that. YOU'RE greedy.}
{1385}{}{Well, not everyone, right? I'm not like the others!}
{1410}{}{Yes, I'm giving it back. I'm honest.}
{1414}{}{Yes, that's right. I want to be good.}
{1417}{}{Yeah, I'm just that kind of girl. See you.}
