{100}{}{You see Mold.}

{101}{}{You see a filthy junkie nicknamed Mold, probably due to his smell.}



#Плавающие фразки перед пропоем:

{102}{}{Aw, f-f-fuck... I g-got the shakes... }

{103}{}{I need more... }

{104}{}{Probably... Or maybe not... }

{105}{}{I need it bad... }

{106}{}{I think I threw up, just a little bit.}

{107}{}{::moan::}

{108}{}{::groan::}

{109}{}{Damn... }

{110}{}{You think they're looking for me?}

{111}{}{Go away!}

{112}{}{Fuck it! Fuck everything!}

{113}{}{I just need a drink to take the edge off... }

{114}{}{A beer would be great right now.}

{115}{}{I think I'm dying!}

{116}{}{I need a drink... I don't care what! Even brahmin piss, anything!}

{117}{}{Who? What? Where? Why?!}

{118}{}{You're a towel!}

{119}{}{[Points at you] You're fired!}

{120}{}{So thirsty... }

{121}{}{I wanna live... }

{122}{}{I wanna die... }

{123}{}{Who's fucked up?! YOU'RE fucked up!}

{124}{}{I just need a sip! Please, have a heart!}

{125}{}{Just one glass... }

{126}{}{If you don't get me a drink, I'll... I... Oh, never mind.}

{127}{}{I'm serious, I really need it. Get me some booze or I'll fucking die here!}

{128}{}{Who the hell?... Oh, why do I care... }

{129}{}{Please! Half a bottle!}

{130}{}{I'm not asking for much! The withdrawal's gonna kill me!}



# Когда применен на нем не тот предмет:

{131}{}{Suck it!}

{132}{}{Go to hell!}

{133}{}{I'll fucking... }

{134}{}{Get off of me!}

{135}{}{What the shit is this fuck?}

{136}{}{What are you trying for?}

{137}{}{Hey, keep your distance!}

{138}{}{I never asked for this!}

{139}{}{Trying to cheat me, huh?!}



# Когда примено бухло: 

{140}{}{Woah, what the... }

{141}{}{Daaaamn... }

{142}{}{Oh! Oh! Ohhhh! Here it comes!!!}

{143}{}{This... Isn't right... }



# Когда упал после применения бухла: 

{144}{}{I'm out, man. Wayyyy out... }

{145}{}{::snores::}

{146}{}{Either I just shit myself or... Nope, right the first time.}

{147}{}{::unconscious::}

{148}{}{::zzzzzz::}

{149}{}{Maybe no one will notice the smell... }



# Диалог

{150}{}{Hey, your booze was real swill! I was puking up shit I'd never eaten! Can you get me something decent? I'm starting to feel the shakes... }

{151}{}{There's a still in the next room. Can't you get it yourself?}

{152}{}{I really couldn't care less. Bye.}

{153}{}{You shouldn't drink so much.}


{154}{}{Fatso said he's had enough of me. He won't give me any more. And no one else will help me, so... Please? They might share with you... }

{155}{}{Fine, I'll get you something to drink. Try not to die in the meantime.}


{156}{}{You got the booze?}

{157}{}{Here's some beer.}

{158}{}{Here's some booze.}

{159}{}{Here's some Rot Gut.}

{160}{}{Here's a Bloody Mary.}

{161}{}{I knew I forgot something. I'll be right back.}


{162}{}{Damn! Thanks, friend... [he eagerly chugs the alcohol, finishing with a loud burp] Ohhhh, that's good... Man, you... I'm just... Wow! Listen, in this gang it's, you know... Complicated. You're new, but you'll understand. Hey, listen... Can you get me another one? I'm kinda fucked up... I need some of Fatso's healing powder. It just takes the pain away, you know? Could you get me some? I'm dying here... }
{163}{}{You get experience for the "delivery".}

{164}{}{I'll try.}


{165}{}{I'm falling apart here... I need medicine... Like, healing herbs, man... Ohhh... }

{166}{}{Here you go. Heal up.}

{167}{}{Well, good luck with that.}
{168}{}{Are you serious? Oh, my guardian angel! Thank you! Thank you! Come on, give me a hug!}

{169}{}{You got the junkie another fix.}


{170}{}{[He convulses on the floor, his eyes wide and staring at the ceiling] Ah, f-f-fuck! It's bad! I need... I need a fix... Acid, painkillers, anti-smoking chems, anything! Just h-h-help me!}

{171}{}{}

{172}{}{Just hold on! I'll give you what you need!}

{173}{}{Do I look like a dealer to you? Why should I take responsibility for your withdrawals?}


{174}{}{[He looks a bit better.]}

{175}{}{[Leave him on the floor.]}


{176}{}{[He sobs] You heartless piece of - I'm dying here! Here, take it, just let me the fix, please... [he hands you the last of his money]}

{177}{}{You earn 250 experience points for getting the junkie another fix.}


{178}{}{[His whole body is rigid, his teeth are locked together, and spittle dribbles from the corners of his mouth] Pssss... Psssychooo... G-g-get pssssychooooo... }

{179}{}{[Inject him with psycho.]}

{180}{}{What am I, a saint? [search his clothes for valuables]}

{181}{}{[Doing your best to ignore the stench, you thoroughly search the junkie but only find an old pistol, which you take as payment for your services.}

{182}{}{[You struggle to find an intact vein on the junkie's perforated arm and finally pierce one with the needle. Mold's convulsions stop, but he remains unconscious.]}

{183}{}{[Leave him to sleep it off.]}


{185}{}{[Slip anti-smoking chems into his mouth.]}

{186}{}{[Slip painkillers into his mouth.]}



# Когда враждебен, видит и нападает:

{200}{}{Hey, you!}

{201}{}{Waste the motherfucker!}

{202}{}{Let's get it over with already, I want to shoot up!}

{203}{}{Die! Diiie!!!}

{204}{}{Let's dance, girl!}

{205}{}{God's gonna cut you down! Or maybe I will!}

{206}{}{Be a good sport and hold still!}

{207}{}{You think you're bad?!}

{208}{}{We'll get 'em!}

{209}{}{This almost makes me forget my withdrawal pains!}



# Female character

{1162}{}{Damn! Thanks, friend... [he eagerly chugs the alcohol, finishing with a loud burp] Ohhhh, that's good... Man, you... I'm just... Wow! Listen, in this gang it's, you know... Complicated. You're new, but you'll understand. Hey, listen... Can you get me another one? I'm kinda fucked up... I need some of Fatso's healing powder. It just takes the pain away, you know? Could you get me some? I'm dying here... }

{1170}{}{[He convulses on the floor, his eyes wide and staring at the ceiling] Ah, f-f-fuck! It's bad! I need... I need a fix... Acid, painkillers, anti-smoking chems, anything! Just h-h-help me!}