{100}{}{You see a raider.}
{101}{}{You see an unwashed, mean-looking thug.}

#Когда враждебен, видит и нападает:
{200}{}{Hey, you!}
{201}{}{Kill the motherfucker!}
{202}{}{Don't make it quick! I wanna see 'em squirm!}
{203}{}{Twenty bucks says I can make a headshot!}
{204}{}{Come on, let's dance!}
{205}{}{You better start digging your grave, you piece of brahmin shit!}
{206}{}{Stand still! Let's get this over with!}
{207}{}{Get over here! I'ma fuck you like I did your mother!}
{208}{}{KILL 'EM ALL!}

#Когда не враждебен:
{210}{}{::spit::}
{211}{}{I'm not looking for friends.}
{212}{}{Piss off.}
{213}{}{I'm bored. Hey, you! Entertain me.}
{214}{}{You looking at me? Get out of here, then.}
{215}{}{I like your boots. Take 'em off.}
{216}{}{Big Daddy says you're alright. For now.}

{217}{}{Hey. What's up?}
{218}{}{Just doing my own thing.}
{219}{}{If you see a fight, call me.}

{220}{}{You're pretty tight with the boss, huh?}
{221}{}{How's the boss? All good?}
{222}{}{Everything's quiet. The boss can sleep easy.}
{223}{}{You need anything, just ask.}
{224}{}{Boss really likes you. I wonder how it feels...}
