{100}{}{You see Ripper.}
{101}{}{You see a raider nicknamed Ripper.}

################################################################################
#
#      Таймерные плавающие реплики
#
################################################################################

{110}{}{Who hasn't heard the story yet? You? Alright, listen up... }
{111}{}{We find those bastards at a bar in Reno... }
{112}{}{We grab our guns, they grab their guns, we all start shit-talking like there's no tomorrow... }
{113}{}{Mexican standoff, motherfuckers. If anyone shoots, everyone's dead.}
{114}{}{In times like these, you gotta keep your head straight and think about every move you make.}
{115}{}{So I throw away my gun... And jump on their boss!}
{116}{}{I popped his eyes with my thumbs and took a bite right out of his neck!}
{117}{}{You should have seen them! They had faces like a brahmin's ass!}
{118}{}{One lost his lunch right then and there. Another ran for the exit! Now that was fun! Haha!}
{119}{}{What the fuck's the matter with you? You don't think it's funny? I'll repeat it for you. Maybe this time, you'll get it... }

################################################################################
#
#      Плавающие реплики при попытке заговорить после квеста
#
################################################################################

{120}{}{... Hmm... Two teams, one from the east, one from the north... }
{121}{}{... Who made these maps?... }
{122}{}{... If we join those dealers for now... But... }
{123}{}{... Hmm... They won't be easy to take down... }
{124}{}{Ivan the 1st - the king of the wasteland. Yeah... Now that's a name.}
{125}{}{It's like having bugs under my skin... Haven't killed anyone in three days already... }
{126}{}{Too bad I didn't send Big Daddy to hell myself. I just didn't get the chance.}

################################################################################
#
#      Разговор на первом этаже
#
################################################################################

{200}{}{Yeah, you've got some backbone taking that job, I'll give you that. Just don't get a big head, or I'll cut it off. I've done it before! Remember that one, guys? We couldn't get his blood out for a week! Hey, why's everyone hiding their eyes? Haha!}
{201}{}{We'll see who still has their head when this is over. I think Louie would be okay with not seeing your face around here anymore.}
{202}{}{I've done tougher jobs. I want to ask you something.}
{203}{}{I was just leaving.}

{205}{}{Oh, Louie sent me another toy! What should I do - skin you like a gecko, or beat you to death with my bare hands? Haha! Quit shaking, boy, I'm kidding... Hmm. You're not shaking at all. Interesting.}
{206}{}{I've got nothing to shake about. I just started, and I can already tell I'm the baddest one here.}
{207}{}{I just need to ask you a few things.}
{208}{}{I should go.}
{209}{}{}

{210}{}{Hey there, wanderer. Anything to say?}
{211}{}{I have questions. Do you have answers?}
{212}{}{Not yet.}

{213}{}{Still trying your luck, huh? Don't take it personally. I'm here to keep everyone in line, so I gotta make sure everyone knows their place. Isn't that right, assholes?}
{214}{}{Just make sure you know your own place. I don't need or want to listen to you.}
{215}{}{That's good. Everything would fall apart without discipline. Can you answer some questions for me?}
{216}{}{Sounds fulfilling. I'll just be on my way.}

{220}{}{Oh, really? [his smile vanishes and he leans in close] You may think you're hot shit, but there's people you can fuck with and people you can't. Me, you can't. Everyone does what I say in this place. EVERYONE. You try to pull shit on me, and it's going to go very fucking badly for you. You got it?}
{221}{}{So you're in charge, then?}
{222}{}{Got it. I have another question, though.}
{223}{}{[Walk away.]}

{225}{}{Well, ask. This better be good, because I don't waste time on bullshit.}
{226}{}{I want to know more about you all.}
{227}{}{Tell me about yourself.}
{228}{}{In that case, never mind.}

{230}{}{I'm going to say this once. Louie's the head here, but I'm his right hand. He may like you, but that doesn't make you invincible. You threaten my authority and I will enforce it. And for years the men will remember what happens to someone who forgets their place. Any questions?}
{231}{}{A few, actually.}
{232}{}{No, I'm good.}

{240}{}{You can see for yourself! We keep the locals in line, and if any of them try shit, we organize some group funerals. I love it when they try shit, haha! I just wish the big man would have us expand, instead of just sitting around on our asses... }
{241}{}{Right. How about another question?}
{242}{}{You have an important job. Take care.}
{243}{}{We keep the locals on a leash. For now, that's all you need to know.}
{244}{}{Good enough. Another question, then.}
{245}{}{That's all. I'll see you around.}

{250}{}{Oh, me? I grew up poor and hungry in Reno... My family didn't have much, but we had love... But just before my mother died, she told me a secret. Come closer. [he glances from side to side] Don't tell this to anyone, but my real father... Is the last president! That's why I had to escape before Chinese assassins could find me, and mix in with these scumbags.}
{251}{}{Oh, I didn't know I was in the presence of royalty! Let me guess, you were really kicked out of Reno for some petty crime, right?}
{252}{}{Oh, well now... I have another question. Give this one a straight answer, okay?}
{253}{}{I'm not here for jokes. Bullshit someone else, I have more important things to do.}
{254}{}{And who the fuck are you? You think I'm gonna hand out my life story to every dipshit that wanders down from the mountains? Prove you're someone worth talking to, and then you can ask questions.}
{255}{}{Let's change the subject.}
{256}{}{Whatever. See you around, tough guy.}

{257}{}{You want to talk shit, asshole? You see these scars? I didn't get them from some hot whore in Reno, ohh no! You wouldn't last five minutes in the shithole I was born in. I had nothing! I ate dirt and drank piss to survive! And if the people there spat on me, I was lucky! But they couldn't spit on the raiders that came one day. They killed the whole village, every one of them, and took me with them because they knew I had fire in me. Those motherfuckers are lucky the raiders killed them before I got the chance! I'd have tortured them for weeks, and that's just the ones who didn't piss me off in particular! I crawled out of dirt and shit and got where I am today because I am always, ALWAYS ready to rip the fucking heart out of any unlucky cocksucker that stands in my way. And if I were in charge? I'd take these retards and make them a gang that would OWN everything between the western coast and Vegas itself!}
{258}{}{[Listen]}
{259}{}{Fuck it, it's not like you even care anyway... Don't stick your nose into my past, or I'll show you everything my childhood neighbors were lucky not to experience.}
{260}{}{Whatever you say.}
{261}{}{You earn 100 experience points for convincing the raider to tell you his dark story.}

################################################################################
#
#      Разговор на втором этаже
#
################################################################################

{300}{}{As the locals say - how! Come in, come in. You need anything? We help our own, here.}
{301}{}{Since when are you so friendly? Don't tell me you're getting soft.}
{302}{}{Thank you for your kind words. Has anything happened around here?}
{303}{}{It's all good. I just stopped by to say hello.}

{305}{}{Well, everything's quiet. I'm planning a job to keep the boys sharp, but there's a little problem... More like a distraction, really. You get it?}
{306}{}{Of course I do. You really can't do anything without me, huh?}
{307}{}{To be honest, I don't really care about whatever you're talking about. I have more important things to do.}

{310}{}{I like that attitude! Right to business. It's Big Louie - he's become a problem.}
{311}{}{Uh, how? Isn't he still in Vegas?}
{312}{}{Stop. I don't want to hear it.}

{313}{}{The assholes here don't like doing real work. Some of them want to bring Louie back. I ought to bleed them out and hang up their skins as an example to the others, but I can't do that right before a big job. I'll deal with them after, but in the meantime... Even if that fucker Louie's out of the business, he's still causing me problems. He needs to be out of the picture completely.}
{314}{}{Keep talking.}
{315}{}{I wasn't here, I didn't hear anything, you didn't say anything. Goodbye.}

{320}{}{We didn't get along even when he was in charge, but I kept my mouth shut for the sake of the gang. Well, now the gang needs to know I'm their leader - no arguments. Louie will understand. It's just business.}
{321}{}{Vegas is a long trip. What do I get for doing this?}
{322}{}{I have to think about this. I'll be in touch.}

{323}{}{You'll be a member in good standing... Really? Nothing? Fine, I'll pay cash. My word is bond, don't you worry about that.}
{324}{}{Deal. Consider him dead.}
{325}{}{Maybe. I'll think about it. See you later.}

#После принятия квеста
{350}{}{You better have good news. People who bring me bad news get fed to the dogs.}
{351}{}{Big Louie made me a better offer. You understand. It's just business.}
{352}{}{Big Louie's playing jazz for the devil in hell. Time to pay.}
{353}{}{Nothing right now.}

{354}{}{Yes, I heard. News like this travels fast. Great job, brother - here's your reward. Now, I've got to think about my next move. I'll see around.}
{355}{}{That's it?! Not good, brother - this wasn't some Reno junkie. Big Louie's worth a lot more than that!}
{356}{}{Good luck.}
{357}{}{You're right. For work like this, I can give you another }
{358}{}{ bucks, but don't get greedy.}
{359}{}{Now we're talking!}
{360}{}{Uh-huh... I get it. I get it. But we're not a bank, damn it. Here, the guys brought me this from the last raid. It's yours.}
{361}{}{That's the best you can do? Thanks, I guess.}

#Female character
{1202}{}{I've done tougher jobs. I want to ask you something.}
{1205}{}{Oh, Louie sent me another bitch! Decisions, decisions - do I choke you to death before, after, or while I fuck every one of your holes? Haha! Quit shaking, girl, I'm kidding... Hmm. You're not shaking at all. Interesting.}
{1208}{}{I should go.}
{1210}{}{Hey there, wanderer. Anything to say?}
{1216}{}{Sounds fulfilling. I'll just be on my way.}
{1240}{}{You can see for yourself! We keep the locals in line, and if any of them try shit, we organize some group funerals. I love it when they try shit, haha! I just wish the big man would have us expand, instead of just sitting around on our asses... }
{1253}{}{I'm not here for jokes. Bullshit someone else, I have more important things to do.}
{1254}{}{And who the fuck are you? You think I'm gonna hand out my life story to every cunt that wanders down from the mountains? Prove you're someone worth talking to, and then you can ask questions.}
{1257}{}{You want to talk shit, bitch? You see these scars? I didn't get them from some hot whore in Reno, ohh no! You wouldn't last five minutes in the shithole I was born in. I had nothing! I ate dirt and drank piss to survive! And if the people there spat on me, I was lucky! But they couldn't spit on the raiders that came one day. They killed the whole village, every one of them, and took me with them because they knew I had fire in me. Those motherfuckers are lucky the raiders killed them before I got the chance! I'd have tortured them for weeks, and that's just the ones who didn't piss me off in particular! I crawled out of dirt and shit and got where I am today because I am always, ALWAYS ready to rip the fucking heart out of any unlucky cocksucker that stands in my way. And if I were in charge? I'd take these retards and make them a gang that would OWN everything between the western coast and Vegas itself!}
{1259}{}{Fuck it, it's not like you even care anyway... Don't stick your nose into my past, or I'll show you everything my childhood neighbors were lucky not to experience.}
{1303}{}{It's all good. I just stopped by to say hello.}
{1315}{}{I wasn't here, I didn't hear anything, you didn't say anything. Goodbye.}
{1350}{}{You better have good news. People who bring me bad news get fed to the dogs.}
{1354}{}{Yes, I heard. News like this travels fast. Great job, sister - here's your reward. Now, I've got to think about my next move. I'll see around.}
