{100}{}{A frenzied raider.}
{101}{}{This is your first opponent in the raiders' ring.}

{102}{}{AHHH!!! SWEET PAIN!}
{103}{}{Is that all you got?!}
{104}{}{You're my bitch! You're my bitch!}
{105}{}{I'm gonna fuck you like I fucked your mother last night!}
{106}{}{Let it bleed! HRAAUGH!!!}
{107}{}{Somebody, hold down this piece of shit! I'm gonna make it fast!}
{108}{}{You're not sick, are you, boyo? 'CUZ I'M GONNA EAT YOUR LIVER AND WASH IT DOWN WITH YOUR BLOOD!}
{109}{}{Goddamn...}
{110}{}{I'LL SEE YOU IN HELL!!!}

{113}{}{Get ready, bitch! I'm gonna enjoy this!}
{114}{}{I'll tear you apart!}

#Импорт, общее: ловушки:

{200}{}{Hey! What the hell are you doing over there?!}
{201}{}{You've been spotted.}

{202}{}{Mommy! Mommy!}
{203}{}{Shoo!}
{204}{}{Faster!}
{205}{}{Help!!!}
{206}{}{Aaaah!!!}
{207}{}{Oh shit, a bomb!}
{208}{}{Goddamn lowlife!}

{210}{}{Children disperse at the sight of your dubious trinkets.}
#Женские реплики
{1108}{}{You're not sick, are you, girl? 'CUZ I'M GONNA EAT YOUR LIVER AND WASH IT DOWN WITH YOUR BLOOD!}