{100}{}{You see a spectator.}
{101}{}{You see a drunk and high raider, who needs only this spectacle to feel complete.}

#Выкрики при получении урона
{102}{}{Dammit!}
{103}{}{Do you want to die that badly?}
{104}{}{Come on, you people!}
{105}{}{A-a-ah!}
{106}{}{Ah, pain is beautiful!}
{107}{}{Pain, sweet pain!}
{108}{}{Goddammit!}
{109}{}{You little...}
{110}{}{Guess what I did to your mom!}
{111}{}{God fucking...}
{112}{}{Wait 'till I get to you...}
{113}{}{Just you wait!!!}

#Выкрики во время боя ГГ на ринге
{114}{}{Drop that clown!}
{115}{}{Oh, come on!}
{116}{}{Waste this punk!}
{117}{}{::yells::}
{118}{}{Move away from it!}
{119}{}{Punch him in the ear! In the ear!}
{120}{}{Punch him! Right in the jaw!}
{121}{}{What is happening!!!}
{122}{}{Wow, have you seen that?}
{123}{}{This was rough!!!}
{124}{}{::yells::}
