{100}{}{You see slave.}
{101}{}{You see number 18-22.}

{102}{}{You see tired slave.}
{103}{}{You see tired slave with number "18-22" on his forehead.}

{104}{}{Please don't hurt me!}
{105}{}{What? I'm free now? That's news! Thanks, friend!}

{110}{}{[At the sight of you, the exhausted slave looks down and continues to sweep the floor]}
{111}{}{Hey, you! Where's you manners!?}
{112}{}{Uh, hi. Who're you?}
{113}{}{Stay here and keep your mouth shut.}

{114}{}{Sorry, my name's number 18-22, I'm here, sorta like, slave...}
{115}{}{Err... My name's number 18-22, I'm here, sorta like, slave...}

{116}{}{18-22? That's some stupid name right here...}
{117}{}{How long they keep you here?}
{118}{}{How did you got here?}
{119}{}{Do you want to get out of here?}
{120}{}{Look, I'm here for investigation. Help me with directions.}
{121}{}{I need to discuss the situation here. Well, you remember what we talked about..}
{122}{}{Well... My real name is Smiley, but every slave here is called by the number... Yeah.}
{123}{}{Two... Months... I guess... Or six... Or a year... I don't really know. Nobody keeps track of time here. No one really cares.}
{124}{}{Well, I was captured by raiders when I was reaching Vegas in search for happy life... Ha, that's funny... But I was lucky, unlike others, - I'm not the one they conduct experiments on... Only beaten and forced to work... Yeah.}
{125}{}{Freedom? Well, with this... [shows the number burned on his forehead] The put a stigma to anyone. And it sticks for the rest of the life. So if I'd be free, no one will consider me for a human, everyone will drive me away, no one would offer me a job... So yeah.}

{126}{}{So you're here... Sneaking or what? Wow! No one ever got here like this, yeah. Then I'll tell you this - here's not a bad place for me, actually. But food here is, like, really crappy... Maybe you have something to eat? I'd tell everything for pizza!}
{127}{}{Alright, I'll get you some good food, but later. In the meantime, sit and wait.}
{128}{}{Here, look and choose from these.}
{129}{}{Don't even count on it! I won't get you anything. Sit here tight.}

{130}{}{Ugh... You've got, like, nothing to choose from!}
{131}{}{Yes, the choice is small. So, today you're out of luck. Bye.}

{132}{}{Wow, what a feast! [points at meal: }
{133}{}{] Give me this, please!}
{134}{}{Of course, treat yourself.}
{135}{}{Hey, don't even touch! I won't give you this!}

{136}{}{Thanks! Thank you, kind person! I haven't eaten like this for a long time! That brahmin manure is only good for making winds from it, but this.. O-oh...}
{137}{}{Uh, don't mention it... Now, let's talk about the lab.}

{138}{}{Well, this is the Pound - Here they make various drugs, then test them on slaves - on us... Yeah.}
{139}{}{Who runs the Pound?}
{140}{}{What is this opposite building behind the paddock?}
{141}{}{Is it possible to enter the main building undetected?}
{142}{}{I don't need anything from you now. You can carry on.}

{143}{}{Well, it's... Nobody knows... He is a secretive person, no one sees how he enters and how quits. But I can tell you a secret - there's a secret passage in his office! Yup. But anyway - no one knows who he is.}
{144}{}{Production lab. They make all their drugs there, that's it.}
{145}{}{Hm... 18-22 says: yes, if quietly! Yup. The patrolman walks around, so you can avoid him, and those at the door probably won't see if you go at night. Yeah. Still, it's, like, a big risk. But if you get to the office of the chief, then you can exit through secret passage. But I don't know where is it, and how to use it...}

{150}{}{Now shut up and listen to me, pathetic slug: Either you'll tell me everything, or I'll smash you to the wall!}
{151}{}{No-no-no! 18-22 don't want to be smashed to the wall! I'll tell! Tell everything! [starts crying]}
{152}{}{Stop crying, snot! Now pull yourself together and share everything valuable you know.}

#Жен реплики
{1105}{}{What? I'm free now? That's news! Thanks, friend!}