{100}{}{You see a slave.}
{101}{}{You see "number 18-22".}

{102}{}{You see a tired slave.}
{103}{}{You see a tired slave with number "18-22" on his forehead.}

{104}{}{Please don't hurt me!}
{105}{}{What? I'm free now? That's great news! Thanks, friend!}

{110}{}{[Seeing you, the exhausted slave looks down and continues to sweep the floor]}
{111}{}{Hey, you! Where's you manners!?}
{112}{}{Uh, hi. Who're you?}
{113}{}{Stay here and keep your mouth shut.}

{114}{}{Sorry, my name's number 18-22, I'm here, sorta like, slave...}
{115}{}{Err... My name's number 18-22, I'm here, sorta like, slave...}

{116}{}{18-22? That's some stupid name right here...}
{117}{}{How long they keep you here?}
{118}{}{How did you get here?}
{119}{}{Do you want to get out of here?}
{120}{}{Look, I'm here for investigation. Help me with directions.}
{121}{}{I need to discuss the situation here. Well, you remember what we talked about..}
{122}{}{Well... My real name is Smiley, but every slave here is called by the number... Yeah.}
{123}{}{Two... Months... I guess... Or six... Or a year... I don't really know. Nobody keeps track of time here. No one really cares.}
{124}{}{Well, I was captured by raiders when I was going to Vegas in search of a happy life... Ha, that's funny... But I was lucky, unlike others, - I'm not the one they conduct experiments on... Only beaten and forced to work... Yeah.}
{125}{}{Freedom? Well, not with this... [shows the number burned on his forehead] They put a stigma on anyone, and it sticks for the rest of your life. So if I'd be free, no one will consider me human, everyone will drive me away, no one would offer me a job... So yeah.}

{126}{}{So you're, like, breaking in, or what? Whoa. No one ever got here this way, yeah. Then I'll tell you this - here's not so bad. At least, for me. But food here is, like, really crappy... Maybe you have something to eat? I'd give everything for pizza!}
{127}{}{Alright, I'll get you some good food, but later. In the meantime, sit and wait.}
{128}{}{Here, look and choose from what I have.}
{129}{}{Don't even count on it! I won't get you anything. Sit here tight.}

{130}{}{Ugh... You've got, like, nothing to choose from!}
{131}{}{Yes, the choice is small. So, today you're out of luck. Bye.}

{132}{}{Wow, what a feast! [points at a meal: }
{133}{}{] Give me this, please!}
{134}{}{Of course, treat yourself.}
{135}{}{Hey, don't touch! I'm not giving you this!}

{136}{}{Thanks! Thank you, kind person! I haven't eaten like this for a long time! That brahmin manure is only good for breaking wind, but this.. O-oh...}
{137}{}{Uh, don't mention it... Now, let's talk about the lab.}

{138}{}{Well, this is the Pound. Here they make drugs, then test them on slaves - on us... Yeah.}
{139}{}{Who runs the Pound?}
{140}{}{What is that building across from the paddock?}
{141}{}{Is it possible to enter the main building undetected?}
{142}{}{I don't need anything from you for now. You can carry on.}

{143}{}{Well, it's... Nobody knows... He is a secretive person, no one ever sees him entering or leaving. But I can tell you this - I've heard there's a secret passage in his office! Yup. But still, no one knows who he is.}
{144}{}{That's the production facility. They make all their drugs there, yeah.}
{145}{}{Hm... 18-22 says: yes, if quietly! Yup. The patrolman walks in circles, so you can avoid him. And those fellas at the door probably won't see if you try it at night. Yeah. Still, it's, like, a big risk. But if you get to the chief's office, you can exit through secret passage. But I don't know where it is or how to use it...}

{150}{}{Now shut up and listen to me, you pathetic slug: Either you tell me everything, or I'll smash you against the wall!}
{151}{}{No, no! 18-22 don't want to be smashed against the wall! I'll tell! Tell everything! [starts crying]}
{152}{}{Stop crying, you snot! Now, pull yourself together and tell me everything you know.}

#Æåí ðåïëèêè
{1105}{}{What? I'm free now? That's great news! Thanks, lady!}
