{100}{}{You see Gizhiyash.}
{101}{}{You see Gizhiyash the Silent River, the slave you helped in Reno.}
{102}{}{Me be thinking you be friend! Me be wrong!}
{103}{}{Greetings, wanderer! May Midnight Watcher be blessing you.}
{104}{}{Old rivers, long ago, be leaving canyon where geckos now live.}

#Первый разговор на кар'е Лавлок
{110}{}{Me be happy to be seeing you again! Me be home, thanks to you. Me no be knowing how to thank you. Here, you be taking these - me be making them on way back. [he gives you two bags of healing powder]}
{111}{}{Thanks.}
{112}{}{That's it? What a rip-off!}
{113}{}{Me brother Acabidab also be wanting to thank you. He be wanting to be coming to Reno for me, but chief be saying no. You be helping me, so Acabidab be helping you.}
{114}{}{Okay, I'll go talk to him.}

#Получение мини-квес'а на охо'у
{115}{}{We be meeting again. How me can be repaying you?}
{116}{}{What are you doing now?}
{117}{}{Nothing. Just enjoy your freedom.}

{118}{}{Me be preparing for walking in shadows. Cheyenne be hungry, and me be hunter.}
{119}{}{You're going to go on a hunt? What are you hunting?}
{120}{}{You're going to do some killing? Anyone I know?}
{121}{}{Good luck! Let me know how it all turns out.}

{122}{}{Acabidab be seeing geckos in canyon. They be lost, broken away from pack. They be good food and skins. Me be hunting them before they be finding way out of canyon.}
{123}{}{Take me with you! I want to hunt too.}
{124}{}{That doesn't sound like my thing, but good luck to you.}

{125}{}{Paleface and Cheyenne be hunting together. Ha! It be funny thought. You be leaving everything here, except for a spear. This be true hunting, as Midnight Watcher be teaching us.}
{126}{}{Good, I'm ready.}
{127}{}{Are you sure I can't take a gun?}
{128}{}{Just a spear? I changed my mind, you'll have to go without me.}

{129}{}{[He shakes his head] No. The hunter's strength be his cunning, not be his firestick. To be having Midnight Watcher's blessing, hunter must be honest with wasteland. Hunter must be honest with self.}
{130}{}{Fine, let's do it.}
{131}{}{No, I won't hunt with a spear. Go without me.}
{132}{}{A woman hunter? This be very strange. But you be cunning and brave, so... Take this spear. You be leaving everything else behind. This be true hunting, as Midnight Watcher be teaching us.}

#После завершения охо'ы
{140}{}{They be close! We be careful!}
{141}{}{Another gecko!}
{142}{}{I be taking skins. You be going. I be meeting you in the camp.}
{143}{}{We not be done! Not all geckos be dead!}

#После завершения охо'ы
{150}{}{Wait, friend. After what you be doing for me... Me cannot be believing you would be abandoning me! Me just be forgetting about it. Yes. Me be trying to forget.}
{151}{}{Forgive me, Gizhiyash, I did a bad thing.}
{152}{}{Don't be mad, Gizhiyash, it happens.}
{153}{}{Whatever. I've already forgotten you.}

{154}{}{Me not be angry at you. Be at peace.}
{155}{}{You said something about skins before the hunt, didn't you?}
{156}{}{Goodbye.}

{157}{}{My friend! You be enjoying the hunt? You be learning anything new?}
{158}{}{You said something about skins before the hunt, didn't you?}
{159}{}{Yes, good hunt.}

{160}{}{Gecko skins be good for clothing, tents, bags... Many things. Me be showing you how to be taking them, if you be wanting.}
{161}{}{Yes, I'd love to learn how to skin geckos!}
{162}{}{Thanks, but no.}

{163}{}{You not be sure what you say. Me be hearing it.}
{164}{}{[Gizhiyash taught you how to skin geckos. You're confident you can skin them yourself from now on.]}
{165}{}{Thank you, Gizhiyash.}
{166}{}{You have earned the "Gecko skinning" achievement.}

#Female character
{1103}{}{Greetings, wanderer! May Midnight Watcher be blessing you.}
{1113}{}{Me brother Acabidab also be wanting to thank you. He be wanting to be coming to Reno for me, but chief be saying no. You be helping me, so Acabidab be helping you.}
{1126}{}{Good, I'm ready.}
{1128}{}{Just a spear? I changed my mind, you'll have to go without me.}
{1129}{}{[He shakes his head] No. The hunter's strength be his cunning, not be his firestick. To be having Midnight Watcher's blessing, hunter must be honest with wasteland. Hunter must be honest with self.}
{1151}{}{Forgive me, Gizhiyash, I did a bad thing.}
{1161}{}{Yes, I'd love to learn how to skin geckos!}
