{100}{}{You see a hunter.}
{101}{}{You see a tanned hunter of the Cheyenne tribe.}
{102}{}{Me resting, outsider.}
{103}{}{You said you is us friend!}

#Диалог до квес'а:

#Первый разговор
{110}{}{Greetings, outsider... You is not Cheyenne, but all look as brothers in shadow of night. Me hope you never is blinded from right path by the shining golden coin that crawls across the sky... }
{111}{}{Did you say gold? Where is this golden coin?}
{112}{}{Uh... Hello, brother. Who are you, exactly?}
{113}{}{Ohhh-kay. I'm going to leave now.}

{114}{}{[He points upward with one finger] When the shadows hide under tents and trees and stones, look to the sky and you is see it. A cursed metal that burns the eyes and dazzles the mind. Even the strongest spirits step off the true path to follow it west.}
{115}{}{Oh, right... The sun. And who are you?}

{116}{}{Everything in this world ends, but even the ending ends. Again, you come to Acabidab... }
{117}{}{Tell me about yourself.}
{118}{}{What can you tell me about your tribe?}
{119}{}{Do you know anything about the local raiders?}
{120}{}{I'm leaving again.}
{121}{}{Yes?}

{122}{}{Greetings, brother! The joy of seeing you is second only to the joy of a brother's return... }
{123}{}{Perhaps, but I have to go.}
{124}{}{I have to go.}

#Если выполнен квес' по рейдерам пу'ем о'равления воды
{125}{}{Truly, the Midnight Watcher walks the path through you! Cheyenne will sing of you in sacred songs and remember you as Ghost Asp, who poisoned even the black blood of the Devourer!}
{126}{}{You honor me, brother!}
{127}{}{Well, at least it's better than Thick Snake, I guess.}
{128}{}{Greetings, Ghost Asp! What do you need of me?}
{129}{}{I was just in the neighborhood and wanted to say hi.}

#О себе и Тихой реке
{130}{}{Me is Acabidab the Tall Bison. Me is humble servant of those who walk in night's shadow.}
{131}{}{Those who... Shadow... Hmm, does that mean you talk to spirits?}
{132}{}{I see. I have other questions.}
{133}{}{You think me is a shaman? Ha-ha, no! Me is not nearly so wise. Me only walk the path of shadows, as the Midnight Watcher showed me. It is a difficult path to follow, and more difficult when alone... Silent River, dear brother... .}
{134}{}{Tell me the path of shadows and this "Midnight Watcher".}
{135}{}{Silent River? Is that another one of your gods?}
{136}{}{Ah, yes... In the past, when the blessed lands knew eternal daylight, the Soul Devourer battled the Fireborn Father to steal the Heavenly Mother and all her lands, seas, and mountains. But Midnight Water, who had long hid under the earth in the shadows, cast a black cloak over the battlefield to create night, allowing the Fireborn Father to strike the Soul Devourer down with one blow. This defeated him for many years, until he took up his flaming axe of war again... }
{137}{}{You seem like a master of wilderness survival. Could you share some secrets with me?}
{138}{}{You're alone here, right? Or is there someone else hiding in the shadows?}
{139}{}{I should go.}
{140}{}{[He sighs] Silent River... Me brother, not by blood, but by soul. Only he and me hear the Midnight Watcher and walk the path of shaodws. He and me are the tips of the Midnight Watcher's blades. Me is skilled with any weapon that grants quick and silent death, but Cheyenne have no better scout than Silent River. He is quieter than the dead in the night... And now he is gone in the vast wasteland... }
{141}{}{What happened?}
{142}{}{You're skilled? Can you teach me a few tricks?}
{143}{}{I'm sorry to hear that. Let's talk about something else.}
{144}{}{[He gives you a sidelong look] The Midnight Watcher only give this knowledge to Cheyenne. But as me say before, in the night, all are brothers. Maybe, if one can walk the path of shadows... Guide Silent River back to his tribe... }
{145}{}{I'm sure getting asked to find a lot of missing people, nowadays. Fine, I'll look for him. I just hope the river hasn't dried up yet.}
{146}{}{Tell me more about Silent River.}
{147}{}{Sure, sure. I help you, you help me, we're all brothers... }
{148}{}{Cheyenne have not seen Silent River since he walk into the wastes. But caravan merchants say they see him in the city of the Devourer - the one they call "Reno". They say he is held in chains by an evil man. Me want to go find him, but Ogima the Black Cloud says no, because if Cheyenne lose any more hunters, it will bring death to us all.}
{149}{}{If I'm ever in Reno, I'll try to find him.}
{150}{}{I don't have time to look for missing Indians. Sorry, pal.}
{151}{}{You think me is a shaman? Ha-ha, no! Me is not nearly so wise. Me only walk the path of shadows, as the Midnight Watcher showed me. It is a difficult path.}
{152}{}{We follow the Midnight Watcher's path. Night is us guardian, shadows us allies. Us feet is silent, and us weapons, deadly... }
{153}{}{Right.}
{154}{}{What were you saying about Silent River, before?}
{155}{}{Me thank you, outsider. May the Midnight Watcher draw his cloak over you.}
{156}{}{I'll look for him. I have another question, though.}
{157}{}{I'll go look for him right now.}
{158}{}{Can I ask you a few more questions?}

#О рейдерах
{175}{}{Raiders! They are the Devourer's children. They bring us suffering, and they will bring more in the future.}
{176}{}{Let's talk about something else.}
{177}{}{Why not make them suffer instead?}
{178}{}{Times are tough all over. Well, see you.}
{179}{}{Me could... There are not many of us, but the Midnight Watcher knows the path to victory in these times. And he values those that honor him more than those that mindlessly charge the enemy... But no. This is not the right time, yet.}
{180}{}{Me could... There are not many of us, but the Midnight Watcher knows the path to victory in these times. And he values those that honor him more than those that mindlessly charge the enemy... But without Silent River, me is not enough to take revenge... }
{181}{}{Silent River? Who's that?}
{182}{}{Midnight what? Do you mean yourself, or some kind of spirit?}
{183}{}{Yes, it's hard to do things without help. Speaking of which, can you help answer some more questions?}
{184}{}{If you say so. I have to go.}

#О племени
{200}{}{Shadows is everywhere, and they know many secrets... But they can't say everything to an outsider.}
{201}{}{Shadows is everywhere, and they know many secrets. [he winks slyly] A friend can learn a lot from them... }
{202}{}{What can you tell me about your chief?}
{203}{}{Do you have a healer here?}
{204}{}{Tell me about your shaman.}
{205}{}{You seem to have a lot of hunters and warriors. Does anyone stand out from the rest?}
{206}{}{Actually, I want to ask something else.}

{207}{}{Ogima the Black Cloud is a wise chief. He leads Cheyenne with the strength of a bison... And though he forbids us from destroying those "raiders" that torture us, me understands his cunning plan.}
{208}{}{Ahh, the Heavenly Mother was very generous when she gave her gift to Niskigvan. Even spirits who have left to the great hunting grounds may be called back to their bodies by him! But, even he is helpless sometimes... Poor Makkon... }
{209}{}{Hmph. Avanigizhig is wise in some ways, but he is blind to deny our god. He even says that our god is only another form of the Devourer!... We do not want quarrels within Cheyenne, so we pretend we do not notice each other.}
{210}{}{Hmm... Makozid the Bear's Paw is the mightiest warrior of the tribe. Gekek is strong in body and spirit and could follow the Midnight Watcher's path, but he only fights in ways as straight as his spear. Our shepherd was once a glorious warrior, but after he was wounded by a fire stick, he spends his time outside of the camp, away from Cheyenne.}
{211}{}{Interesting. Let me ask something else.}

#Квес' на поиск Гижияша
{250}{}{But didn't Gizhiyash already tell you how he returned to Cheyenne?}
{251}{}{Tell me again about Silent River.}

{252}{}{[He sighs] It hurts to talk about my brother, but me will do anything to help you find him.}
{253}{}{How did he go missing, again?}
{254}{}{Can you tell me about him again?}
{255}{}{That's all. I will continue my search.}
{256}{}{Cheyenne have not seen Silent River since he walk into the wastes. But caravan merchants say they see him in the city of the Devourer - the one they call "Reno". They say he is held in chains by an evil man. Me want to go find him, but Ogima Black Cloud says no, because if Cheyenne lose any more hunters, it will bring death to us all.}
{257}{}{Silent River... Me brother, not by blood, but by soul. Only he and me hear the Midnight Watcher and walk the path of shadows. He and me are the tips of the Midnight Watcher's blades. Me is skilled with any weapon that grants quick and silent death, but Cheyenne have no better scout than Silent River. He is quieter than the dead in the night... }
{258}{}{I don't need to know anything else.}

{259}{}{Outsider! You are truly blessed by the Midnight Watcher! The road was hard for him, but Gizhiyash the Silent River has returned to Cheyenne!}
{260}{}{Yeah, yeah, whatever. How about some blessings that actually matter? Like a reward?}
{261}{}{I'm happy for you both. Good friends are hard to find. I hope you watch out for each other.}
{262}{}{The sun has blinded you, and now you know only your own thirst. But you helped me, so me help you.}
{263}{}{Enough of this crap. Let's get down to business!}
{264}{}{Yes, you is right... And me understand your path is as difficult as the path of shadows. Many trials approach you, brother. Me is do everything to help you face them.}
{265}{}{I'm grateful, brother!}
{266}{}{Forget it, I have no time for training.}
{267}{}{Acabidab has raised your melee and throwing skills by 5%.}
{268}{}{[For hours, Acabidab shows you various tricks, such as throwing knives silently or striking where an enemy is vulnerable. Afterward, you feel more confident in your skills.]}
{269}{}{[Next]}
{270}{}{You is a very good student... Please, take this knife as a gift. But remember, a spear will defeat it. Bring me a spear, and me is sharpen it... But me is almost out of flint.}
{271}{}{Thank you, Acabidab. I will remember this.}

#За'очка копья
{300}{}{You said something about spear sharpening?}
{301}{}{Bring a spear, and me can sharpen it. But me is almost out of flint.}
{302}{}{I have a spear with me. Sharpen it, please.}
{303}{}{I'll keep that in mind. Right now, I have another question.}
{304}{}{I don't need that right now. Bye.}
{305}{}{Hmm... Everything in this world ends, even stone. Me have no more flint. Me cannot sharpen that spear anymore.}
{306}{}{That's too bad. I was just getting the hang of it.}

{307}{}{Outsider is joking?}
{308}{}{How could the spear disappear?}
{309}{}{Done, outsider.}
{310}{}{Done, Ghost Asp.}
{311}{}{Thank you.}
{312}{}{Thank you. I have a couple of questions.}
{313}{}{Done, outsider. But everything in this world ends, even stone. Me have no more flint. Me can sharpen no more spears.}
{314}{}{Done, Ghost Asp. But everything in this world ends, even stone. Me have no more flint. Me can sharpen no more spears.}

#Female character
{1110}{}{Greetings, outsider... You is not Cheyenne, but all look as brothers in shadow of night. Me hope you never is blinded from right path by the shining golden coin that crawls across the sky... }
{1116}{}{Everything in this world ends, but even the ending ends. Again, you come to Acabidab... }
{1122}{}{Greetings, sister! The joy of seeing you is second only to the joy of a brother's return... }
{1125}{}{Truly, the Midnight Watcher walks the path through you! Cheyenne will sing of you in sacred songs and remember you as White Shadow, who poisoned even the black blood of the Devourer!}
{1128}{}{Greetings, White Shadow! What do you need of me?}
{1129}{}{I was just in the neighborhood and wanted to say hi.}
{1155}{}{Me thank you, outsider. May the Midnight Watcher draw his cloak over you.}
{1200}{}{Shadows is everywhere, and they know many secrets... But they can't say everything to an outsider.}
{1201}{}{Shadows is everywhere, and they know many secrets. [he winks slyly] A friend can learn a lot from them... }
{1259}{}{Outsider! You are truly blessed by the Midnight Watcher! The road was hard for him, but Gizhiyash the Silent River has returned to Cheyenne!}
{1261}{}{I'm happy for you both. Good friends are hard to find. I hope you watch out for each other.}
{1262}{}{The sun has blinded you, and now you know only your own thirst. But you helped us, so me help you.}
{1264}{}{Yes, you is right... And me understand your path is as difficult as the path of shadows. Many trials approach you, sister. Me is do everything to help you face them.}
{1265}{}{I'm grateful, brother!}
{1270}{}{You is a very good student... Please, take this knife as a gift. But remember, a spear will defeat it. Bring me a spear, and me is sharpen it... But me is almost out of flint.}
{1306}{}{That's too bad. I was just getting the hang of it.}
{1309}{}{Done, outsider.}
{1310}{}{Done, White Shadow.}
{1313}{}{Done, outsider. But everything in this world ends, even stone. Me have no more flint. Me can sharpen no more spears.}
{1314}{}{Done, Ghost Asp. But everything in this world ends, even stone. Me have no more flint. Me can sharpen no more spears.}
