{100}{}{A hunter.}
{101}{}{A seasoned and experienced hunter of the Cheyenne tribe.}

#Попытаться подвинуть
{102}{}{Me move.}
{103}{}{We go.}
{104}{}{Go slow, outsider.}
{105}{}{Hmm. Me go.}
{106}{}{Okay.}

#Попытка заговорить
{107}{}{No. Me no do you talk.}
{108}{}{Mmm! Me want eat!}
{109}{}{Me no talk.}
{110}{}{Me no want.}


#Попытка заговорить при зависимости от наркоты
{111}{}{Outsider eat magic potion?}
{112}{}{Hmm... Outsider soul go from body?}
{113}{}{Why outsider look?}
{114}{}{Me no like.}

{115}{}{No. Smell bad.}
{116}{}{Outsider do bad.}
{117}{}{We no want, but outsider make.}
{118}{}{Bad outsider! Shoo!}
{119}{}{What you tribe?}
{120}{}{Cheyenne remember forever!}
{121}{}{Son of Devourer must die!}

{122}{}{}
{123}{}{Bad outsider! Bad!}
{124}{}{You good tribe. Cheyenne friend.}
{125}{}{Me no forgive!}
{126}{}{Ooh! Baby boy so big already!}
{127}{}{Me child.}
{128}{}{You do good?}
{129}{}{Child look like me.}
{130}{}{Me make this child.}
{131}{}{Child happy make me happy.}
{132}{}{We good family, child. Be good.}
{133}{}{You be good, child?}
{134}{}{Me hungry!}
{135}{}{Me go to roof!}
{136}{}{Mmm! Magic herb tea!}
{137}{}{Mmm! Gecko stew and shrooms!}
{138}{}{Mmm! Kitchen smell big good!}

{139}{}{Who here?}
{140}{}{Who you?}
{141}{}{Cheyenne know you?}
{142}{}{Outsider want trade?}
{143}{}{Outsider want gecko skin?}
{144}{}{Outsider buy gecko skin?}
{145}{}{Cheyenne no like outsiders.}
{146}{}{Cheyenne want outsider go soon.}