{100}{}{You see Big Louie.}
{101}{}{The mountain of muscles, the kingpin of cutthroats, the wolf of the wasteland. Is this not enough?}
{102}{}{You see your boss. His word is absolute.}

################################################################################
#
#      Первый диалог
#
################################################################################

{103}{}{Search this one! Put everything into the locker. [he turns to you] You, dead meat! What are you sniffing in my territory?}
{104}{}{Whoa, slow down, man...}
{105}{}{You will call me Boss! Or you gonna puke your guts out!}
{106}{}{Okay, boss. I've been looking for your base hoping to join you.}
{107}{}{I'm here to drain the blood from your corpse, skin your men for leather and burn this building to the ground!}
{108}{}{Funny, your mother called me that last night. But it wasn't answers she had in her mouth.}

{109}{}{HA-HA-HA! Aren't you the tough one? Okay, now you are meeting the dogs. Let's see just how brave you are!}
{110}{}{[He growls] You arrogant PIG! I HATE smug assholes like you! Bring him to the dogs. We haven't had a fight in a long time!}
{111}{}{Wha... [you are forcibly escorted to the ruins near the base of the building]}

{112}{}{[He crosses two enormous arms] Is that so?}
{113}{}{I'm sick of running with two-bit gangster wannabes. I'm the real deal! I want some SERIOUS action!}
{114}{}{You think I'm idiot, don't you?}
{115}{}{No.}
{116}{}{Yes you do. Do you?}
{117}{}{Yes.}
{118}{}{No.}

{119}{}{[He studies you carefully] Okay, pretty boy. Why would I want you?}
{120}{}{[He studies you carefully] Okay, macho. Why would I want you?}
{121}{}{[He studies you carefully] Okay. Why would I want you?}
{122}{}{I'm strong. And not like your men downstairs - they are not exactly tough, like you. Or even me.}
{123}{}{I'm a cat in the night. Anyone can kick in a door, but I can be miles away before my victims even know I was there.}
{124}{}{I'm a master of explosives. You want someone dead? I'll wipe out their whole family. You want something wrecked? You'll think it never even existed. I can get things done on a whole other level than the men you have now.}
{125}{}{I can open any lock, mechanical or electric. You must have a use for that.}
{126}{}{I know these wastes like the back of my hand. No one is better than me when it comes to wilderness survival.}
{127}{}{Just look at me. I've been everywhere, I've done everything, I've met everyone. Whatever you need, I'll get it done.}

{128}{}{Okay, pretty boy. }
{129}{}{Okay, macho. }
{130}{}{Okay. }
{131}{}{I'm convinced. But I warn you - this is for life. You are either with me, or gone. [he pounds one fist into his palm] Permanently!}
{132}{}{Hey, I didn't sign up for this! I'm out of here!}
{133}{}{Not a problem. Now, can I have my things back?}

{134}{}{[He roots through your things for some time before he's satisfied] You can take your things. But don't be so happy. I want to see you in action. You get the job done, you're in the gang. If you don't... Well, you'll understand it on your way there. We won't even have to get our hands dirty.}
{135}{}{I'm listening.}
{136}{}{[He nods] Good. The guns we're using now are good enough for scaring small villages, but we need some real army equipment to be serious. And I know just the place to get it from.}
{137}{}{[Listen]}
{138}{}{There's a pre-war army base to the south of here. My dogs tried to get in, but the turrets are still on. To get around them - that's your headache now. I'll send a couple of my boys to help out, but they won't risk their necks for you. This is YOUR job. Got it?}
{139}{}{Got it. When do we leave?}
{140}{}{I'll give you some time to gather up. Talk to me when ready, I'll organize the convoy.}
{141}{}{I'll be back soon.}
{142}{}{I'm ready to go to the base right now.}
{143}{}{Time is money, macho. Don't keep me waiting. If I have to go looking for you, you'd better already be dead.}
{144}{}{[Exit]}
{145}{}{Ha, the macho's trying to impress me! Good. Be ready to move out in an hour.}
{146}{}{[You wait for the team to get ready, then finally head out into the wastes.]}

{147}{}{[He studies you carefully] Yes, Yes... I can tell someone like you would have a place here. But tell me, boy - what *exactly* do you bring to me?}

{148}{}{Speak.}
{149}{}{}

{150}{}{You managed to steal something off a raider while you were being escorted downstairs.}
{151}{}{The scourge of the wasteland is dead. You earn 500 experience points.}
{152}{}{For defeating the scourge of the wasteland in fair combat, you earn 2000 experience points.}
{153}{}{Ma... Ma...}
{154}{}{Grrr... Once again, I have to do everything myself!}

################################################################################
#
#     Общие реплики
#
################################################################################

# Когда на нем поюзана нарко'а
{155}{}{I'll string you up by your own entrails for this!}

# Когда рейдеры унич'ожены о'равлением водосборника
{156}{}{Get up, you inbreds! Do I have to do everything myself?!}
{157}{}{::mutter::}
{158}{}{Useless idiots...}
{159}{}{On your feet, you worthless dogs!}
{160}{}{When I find who's done this...}
{161}{}{I'll tear those Indians apart for this!}
{162}{}{I'll show you what happens when you disobey Big Louie!}
{163}{}{::growl::}
{164}{}{Aaaagh!}
{165}{}{Rnnmf...}
{166}{}{NO ONE DOES THIS TO BIG LOUIE!}
{167}{}{You're dead! I've seen what you've done!}

# Проверка инвен'аря:
{170}{}{No. I want a look at it first.}
{171}{}{[Wait for him to finish searching your gear.]}
{172}{}{[Try to break loose.]}
{173}{}{[He goes through your things and throws what he doesn't want at your feet] Ah, shiny presents for Big Louie! I'll take that. [he takes your money]}
{180}{}{[He silently, almost reverently, places your Elvis Presley portrait on his shelf]}
{181}{}{[He takes your lighter and turns it over in his hand, flipping it open and gazing at the flame] I'll take that.}
{182}{}{[He shudders at the sight of your sniper rifle and carefully places it in his locker]}
{183}{}{}
{184}{}{Hello... [he holds up your Salt Lake City map] I've been looking this for a long time. [he carefully folds it and places it in his locker]}
{185}{}{Dog meat? [he shakes his head with a smirk] I'll try that exotic stuff later...}
{186}{}{Some of Vegas's pride and joy? [he slips your drug from Vegas into his pocket] Hmm... You, macho - I think you'll be useful.}

################################################################################
#
#      Квес'ы
#
################################################################################

#Сдача первого квес'а:
{200}{}{Aren't you the capable one! My pack is now fully equipped. You've earned some respect. Consider yourself one of us. So, for starters, go grab a beer or something from Fatso, relax, and when you're done - come see me. We'll have real talk. Big plans.}
{201}{}{See you.}

#В'орой квес' (дань С'райкера)
{202}{}{About our plans...}
{203}{}{Nothing right now. Bugger off.}
{204}{}{The business's good, get it? Still - one player forgets to pay his cut. Name's Stryker, lays in Reno. You should remind him about which hand is holding the leash. That's the password, by the way. He'll understand. Go get me my share.}
{205}{}{[His knuckles crack as his hands tighten into fists] I see you here, but I don't see my cut. Get your ass on your feet and go to Reno, or I'll rip your fingers out!}

{206}{}{There's a problem. Stryker isn't forgetful, he's dead.}
{207}{}{Here's Stryker's share.}
{208}{}{Here's Stryker's share. That gangster's way too full of himself...}
{209}{}{I'll bring it later.}
{210}{}{Good... I'm glad to know his memory's improved. Here. [he gives you 500 dollars and a stimpak] To keep your memory sharp too. Now begone.}

#Тре'ий квес' (Лысый преда'ель)
{211}{}{There is a problem. [he cracks his knuckles] There's a man hiding somewhere in Reno. Goes by the name "Balder". He has a bald head, obviously, and a scars on his neck - some time ago someone tried to hang him. He... Let's say, tried to fool me. Find him and put him down. Show everyone what happens to the scum that betrays Big Louie. Now go! Full speed to Reno!}
{212}{}{Sorry, assassinations aren't my style.}
{213}{}{[He stares down at you, his eyes narrowing to pinpricks] What was that? It sounded like you said, "I want to die in the ring, boss." But you're going to be too busy in Reno killing Balder, aren't you?}
{214}{}{What is it? Is Balder dead yet?}
{215}{}{I found him! He's waiting for a caravan in Reno! He's trying to escape to Vegas!}
{216}{}{[He stares at you in stunned silence for a moment before his hands curl into fists] Then WHAT are you doing HERE?! GET OUT THERE AND KILL HIM BEFORE HE ESCAPES!!! Go, or you'll see what REAL anger looks like! Move!}
{217}{}{Balder's dead, boss. I killed him with my own hands.}
{218}{}{Good work, macho! Let's arm wrestle! Oh, you don't want to? Ha-ha!! I knew it from the start - you're worth two of those mindless apes, jerking off to each other downstairs... [he suddenly interrupts himself] Here. [he holds out 1000 dollars, but pulls it back out of your reach as you go to grab it] Next time, bring back evidence. Because if you're lying to me... [he waits for a few seconds, watching you, before handing over the money]}
{219}{}{Balder's escaped Reno. We'll never find him now.}
{220}{}{[Big Louie's jaw clenches. His narrowed eyes smolder with rage.] I'll only say one thing about this. You are *almost* a deadman, macho.}

#Че'вер'ый квес' (курьер из Вегаса)
{221}{}{I have another job for you, and it has to be done *now*. Get the boys. There's a courier taking a valuable package to Reno...}
{222}{}{Who's the delivery man?}
{223}{}{What's the package?}
{224}{}{I'm ready to go.}
{225}{}{The term is *courier*. Don't underestimate him. They make them tough up in Vegas. He knows what he's doing and he knows what the package is worth. I want you to hit him hard and fast. Bring me the package. As for the courier... Well, you understand.}
{226}{}{The package is from Vegas. They say someone is cooking up some new chem there. It hasn't hit Reno yet. I want the first look... And I want those bloated rats in Reno to remember who Big Louie is.}
{227}{}{Bloated rats? What do you mean?}
{228}{}{You are wasting time! But I'll tell you. This is important. Reno is forgetting Big Louie. My boys, Stryker and Thompson, are going their own ways, and the local dealers are gaining more power. The situation gets worse every day. I can't allow anyone in Reno become stronger without the control of my people. Now go, time is money!}
{229}{}{Hey, you! Get up, you dogs! Move!!!}
{230}{}{Everyone's always in such a big rush...}

{231}{}{You better have the package, or you are dead.}
{232}{}{It must be your birthday, boss! Here it is!}
{233}{}{I didn't find the package, but the courier is dead.}
{234}{}{Damn, I knew I forgot something! I'll be right back.}
{235}{}{YOU - ! [he closes his eyes and takes a deep breath] Forget it. With the courier dead, they won't send another package. Get the hell out. [mumbles] ...Surrounded by dumb assholes...}
{236}{}{Hey, it wasn't easy! He had some serious security! All that work for nothing...}
{237}{}{[His eyes seem to sparkle as he opens the package] Well, well, what a big boy I am now! And there's something here for you, too! [he gives you 3000 dollars and two stimpaks] Now kick back. There's no more work right now.}
{238}{}{Wow! That's a lot of money!}
{239}{}{Do better next time. Don't forget who you're working for.}

#Квес' на наркодилера
{240}{}{One more scumbag that doesn't know his place.}
{241}{}{Who, me?}
{242}{}{Not long ago, one of Fatso Jackson's suppliers sold him bad product. A couple of our boys kicked the bucket.}
{243}{}{This supplier must have a death wish.}
{244}{}{[He frowns] He should pay in blood! It's not even about the boys - we'll bury them, and they'll stop stinking. It's about Reno itself. The city had... Forgotten who Big Louie is. Stryker and Thompson are off the leash, two-bit pushers are scamming Fatso... We have to send a message. You *have* to do this for *me*... And for the gang. Reno has to remember.}
{245}{}{Where do I find this supplier?}
{246}{}{Ask Fatso. He's the one who dealt with him. All I know is he always wore some ring. Bring it to me when the job is done.}
{247}{}{Fine, I'll talk to Fatso.}
{248}{}{What are you talking about?}
{249}{}{I found the supplier. I made him measure the length of his guts with his steps. Here's the ring... Uh, I had to get a little creative taking it off of him.}
{250}{}{Nothing.}

################################################################################
#
#      Бонусный квес'
#
################################################################################

#после всех квес'ов
{251}{}{Good. Very good. [he gives you 3000 dollars]}
{252}{}{You don't look very happy.}
{253}{}{[He sighs deeply] Honestly, brother, I'm tired. I'm getting sick of all this... Oh, forget it. The season's over, nothing to do but milk the tribe and rob caravans. You can go on your way. I'm not holding you here any longer.}
{254}{}{What? I'm out of the gang?}
{255}{}{It's not like that. You'll always have a place here. But the rest of the boys can take it from here, and I can tell you have other things to do than sit around and hassle Indians. There's nothing left for you to do anyway.}
{256}{}{This is unexpected. Perhaps we'll see each other again.}

{260}{}{How do I find that supplier, again?}
{261}{}{I don't know. Ask Fatso.}
{262}{}{It's done. Here's that supplier's ring.}
{263}{}{It's done. I brought his shotgun as evidence.}
{264}{}{Ha! None of those geezers downstairs could have pulled this off. Great job! [he gives you 1000 dollars] And keep the sawed-off. You earned it.}
{265}{}{Reno's getting out of hand. That's why I need to send a reminder... Hey, you know what's in here? A little bit of happiness for everyone! And that means you, too. [he gives you 500 dollars and a stimpak]}
{266}{}{ARRGGGHH!!! [he smashes the table with his fists, you hear wood crusting] YOU WORTHLESS SLUGS! HOW COULD YOU FAIL SUCH A... YOU!!! [he points at you] GET OUT!}
{267}{}{[Exit]}
{268}{}{I have a better idea: stick that base up your ass. Find someone else for this job. I'm not doing it.}
{269}{}{}

#Про ис'орию Большого Луи и Армс'ронга:
{270}{}{Interesting. Who is Armstrong?}

{276}{}{[He shoots you a severe look] Do I look like a librarian? Get lost!}
{277}{}{Calm down, I'm just asking.}

{278}{}{Louie's an idol. That's all I'm going to say about that. Now, get lost!}
{279}{}{Relax, it was a simple question, that's all.}

{280}{}{[He studies you for a moment, thinking] Louie Armstrong was... A man, truly worthy of respect. Now, get lost!}
{281}{}{I was just curious, that's all.}

{282}{}{Hmmm... He was a childhood hero of mine. But that was a long time ago... Forget it. I'm not going to talk about it.}
{283}{}{Alright, fine. Maybe later, then.}

{284}{}{[He sighs] Louie Armstrong... Now, there was a man. He was my hero, my role model. He died a hundred years before I was born, but no one in this trash dump of a world could be closer to me... Look, forget it. It doesn't matter now.}
{285}{}{Tell me your story.}
{286}{}{You don't want to remember?}
{287}{}{Who is this Armstrong anyway?}
{288}{}{Fine, whatever you say.}

{289}{}{It was a long time ago. I'd bring those days back if I could, but I can't.}
{290}{}{[Next]}
{291}{}{After the war, the gangs tore Reno apart. In the end, the elites won, mainly with the police heading them. They made the city safe - I mean, safer than before. You could walk around without a gun.}
{292}{}{I was young then. I used to sneak to the local bar at night to listen to the music. I wasn't allowed inside, but the sounds always found their way out to me. There were a lot of musicians, but I loved the Great Louie's songs the most. Somehow, he just made the world seem... Wonderful. Like something worth living in.}
{293}{}{After a few years, the law broke down and Reno became a hellhole again. No more Armstrong after that.}

{294}{}{You weren't always the top dog around here?}
{295}{}{You mean a vicious killer, leading mindless thugs to prey on the weak and abandoned? No. I was educated, sophisticated. A *man*, not one of these animals. I even started my own jazz band, but the life made me choose between it and a mob gang. I'd never have survived otherwise. Anyway, now I look back on things and I see them differently. That Indian shaman - he's a wise man. He told me the truth about people. About my people. [he motions towards the floor] The ones downstairs... And the ones up here.}
{296}{}{Would you ever want to play jazz again?}
{297}{}{I'd kill to have that chance again! But with my reputation...}
{298}{}{Jazz is the only good memory I've got left.}
{299}{}{Armstrong's voice was the only one on this cursed planet worth listening to. Such people should never die - they should live forever. I learned every song by heart. I can even sing them now... But I won't. Not for this wastes downstairs.}

#Большой Луи как музыкан'
{300}{}{No work right now. This place is as quiet as a church.}
{301}{}{I found a job opening for a singer in a band, if you're interested.}
{302}{}{Bye, then.}
{303}{}{Is this some kind of joke, boy?}
{304}{}{No joke. It's in Vegas... [tell him about the cafe]}
{305}{}{Wait... Are you saying... I'll be able to to tour between Vegas and Reno? I can't believe it! I'll do it! HA-HA! I'll never forget you, brother! You've given me another chance at the only thing I ever loved! Let's arm wrestle for goodbye!}
{306}{}{Don't mention it. See you in Vegas!}
{307}{}{Holy crap! Big Louie believed you and went to Vegas to perform on stage!}

{310}{}{I managed to get into Hawthorne and gain access to the storage. The guys should arrive with the weapons any minute now.}
{311}{}{I managed to get into Hawthorne and gain access to the storage. The guys stayed behind... Forever.}
{312}{}{I managed to get into Hawthorne and gain access to the storage. But your guys didn't make it.}

#Female character
{1103}{}{Search her! Put everything into the locker. [he turns to you] You, dead meat! What are you sniffing in my territory?}
{1106}{}{Okay, boss. I came here to join you.}
{1107}{}{I'm here to drain the blood from your corpse, skin your men for leather, and burn this building to the ground!}
{1108}{}{Funny, your mother called me that last night. But she had better things to do with her tongue than talk.}
{1110}{}{[He growls] You arrogant COW! I HATE smug bitches like you! Bring her to the dogs. We haven't had a fight in a long time!}
{1119}{}{[He studies you carefully] Okay, prom queen. Why would I want you?}
{1120}{}{[He studies you carefully] Okay, marimacho. Why would I want you?}
{1121}{}{[He studies you carefully] Okay. Why would I want you?}
{1126}{}{I know these wastes like the back of my hand. No one is better than me when it comes to wilderness survival.}
{1127}{}{Just look at me. I've been everywhere, I've done everything, I've met everyone. Whatever you need, I'll get it done.}
{1128}{}{Okay, prom queen. }
{1129}{}{Okay, marimacho. }
{1131}{}{I'm convinced. But I warn you - this is for life. You are either with me, or gone. [he pounds one fist into his palm] Permanently!}
{1132}{}{Hey, I didn't sign up for this! I'm out of here!}
{1143}{}{Just remember, time is money. Don't keep me waiting. [his knuckles crack as his hands curl into fists] If I have to go looking for you, you'd better already be dead.}
{1145}{}{Ahh, a go-getter! Great. The men will be ready to move out in an hour.}
{1147}{}{[He studies you carefully] Yes. Yes, I can tell someone like you would have a place here. But tell me, girl - what *exactly* do you bring to me?}
{1186}{}{Some of Vegas's pride and joy? [he slips your drug from Vegas into his pocket] Hmm... You, girl - I think you'll be useful.}
{1200}{}{Aren't you the capable one! My pack is now fully equipped. You've earned some respect. Consider yourself one of us. So, for starters, go grab a beer or something from Fatso and relax, and when you're done, come see me. We'll have real talk. Big plans.}
{1214}{}{What is it? Is Balder dead yet?}
{1215}{}{I found him! He's waiting for a caravan in Reno! He's trying to escape to Vegas!}
{1216}{}{[He stares at you in stunned silence for a moment before his hands curl into fists] Then WHAT are you doing HERE?! GET OUT THERE AND KILL HIM BEFORE HE ESCAPES!!! Get out, or I'll show you what REAL anger looks like!}
{1217}{}{Balder's dead, boss. I killed him with my own hands.}
{1218}{}{Good work, girl! Let's arm wrestle! Oh, you don't want to? Ha-ha!! I knew it from the start - you're worth two of those mindless apes, jerking off to each other downstairs... [he suddenly interrupts himself] Here. [he holds out 1000 dollars, but pulls it back out of your reach as you go to grab it] Next time, bring back evidence. Because if you're lying to me... [he waits for a few seconds, watching you, before handing over the money]}
{1220}{}{[Big Louie's jaw clenches. His narrowed eyes smolder with rage.] I'll only say one thing about this. You are *almost* a deadmeat, marimacho.}
{1233}{}{I didn't find the package, but the courier is dead.}
{1237}{}{[His eyes seem to sparkle as he opens the package] Well, well, what a big boy I am now! And there's something here for you, too! [he gives you 3000 dollars and two stimpaks] Now kick back. There's no more work right now.}
{1244}{}{[He frowns] He should pay in blood! It's not even about the boys - we'll bury them, and they'll stop stinking. It's about Reno itself. The city had... Forgotten who Big Louie is. Stryker and Thompson are off the leash, two-bit pushers are scamming Fatso... We have to send a message. You *have* to do this for *me*... And for the gang. Reno has to remember.}
{1249}{}{I found the supplier. I made him measure the length of his guts with his steps. Here's the ring...uh, I had to get a little creative taking it off of him.}
{1251}{}{Good. Very good. [he gives you 3000 dollars]}
{1253}{}{[He sighs deeply] Honestly, sister, I'm tired. I'm getting sick of all this... Oh, forget it. The season's over, nothing to do but milk the tribe and rob caravans. You can go on your way. I'm not holding you here any longer.}
{1266}{}{ARRGGGHH!!! [he smashes the table with his fist, you hear wood crusting] YOU WORTHLESS SLUGS! HOW COULD YOU FAIL SUCH A... YOU!!! [he points at you] GET OUT!}
{1277}{}{Calm down, I'm just asking.}
{1303}{}{Is this some kind of joke, girl?}
{1305}{}{Wait... Are you saying... I'll be able to to tour between Vegas and Reno? I can't believe it! I'll do it! HA-HA! I'll could kiss you, baby! You've given me another chance at the only thing I ever loved!}
