#Стартовые сообщения районов Солт-Лейка:
{100}{}{You enter a gloomy and unhappy-looking town. It smells of damp and rotting foliage.}
{101}{}{You enter Salt Lake City's residential area. Seeing children play in the streets without a care in the world makes your eyes moist.}
{102}{}{You walk into abandoned locomotive depot.}
{103}{}{This derelict slum has long been deserted. But you notice some fairly fresh footprints in the sand.}
{104}{}{This place still screams of blood and suffering. Looks like the vault's inhabitants had a quarrel and beaten each other to death.}