{100}{}{You see a Provo resident.}
{101}{}{You see Gary Gilmore.}
{102}{}{You see a very unpleasant looking man.}
{103}{}{You see that Gilmore, one and only. But you wish you didn't.}
{104}{}{Gary Gilmore is dead. May his soul be condemned to torments of hell!}

#Реплики, когда квест от шерифа на него не получен
{110}{}{And who the hell are you?!}
{111}{}{I'm here for business, so sit quietly and don't fuck with me.}
{112}{}{Well! Look who is here!}

#Решение квеста шерифа
{113}{}{Well, well, look who is here. Looking for trouble? You came into right place.}
{114}{}{Keep quiet, I have business here.}
{115}{}{[Force the justice on this fucker]}
{116}{}{By the authority of Salt Lake Sheriff, you are sentenced to be hanged. Do you have anything to say in your defense?}

{117}{}{Yes, goddamn it! The Sheriff can kiss my ass, and you...}
{118}{}{And about your sentence?}
{119}{}{Shut the fuck up, scum! [attack]}
{120}{}{Relax, I don't want any trouble.}

{121}{}{Those worthless idiots brought it to themselves. I *helped* the city, I cleansed it, something that that coward with a badge could never do.}
{122}{}{Coward with a badge? You mean the Sheriff?}
{123}{}{Who do you think I am - the public library?! Yes, I mean the Sheriff!}
{124}{}{So, I guess, you really did something bad in the city?}
{125}{}{Do you really want to know? Fine, I'll tell you. Not one son of a bitch wants to hear me on this, let alone understand! But all I ever needed was a little human appreciation. I suffered for my whole life because of someone else's stupidity. So, I decided to have my revenge on everybody and rid this city from bad people while doing it.}
{126}{}{That's why you made so many people suffer?}
{127}{}{Suffer? No, they didn't suffer for long. I still have a soul, you know, something you can't say about them. Just think about it: I wouldn't just be easily executed in Salt Lake, would I? I would be tortured first, for the whole day. So, it turns out I was even kind, unlike them.}
{128}{}{Funny, a maniac that is talking about kindness...}
{129}{}{W-what?! How dare you! I... I... [starts to tremble hysterically and make all kind of faces] Do you even imagine how it feels - to slice a throat of some bitch with a blunt knife? Or to pull out intestines through the belly button with bare hands? That's UNBEARABLE! Every time I have a seizure at the end. I can't take it anymore!}

{130}{}{I should rip your guts out right here, but no one in the city would believe me. You're coming with me and you will be hanged publicly.}
{131}{}{Then have your sentence! Executed, right now!}
{132}{}{What a heartbreaking story. I hope you will understand what you did someday.}

{133}{}{What? To die, just like that? Suck it, all of you!}
{134}{}{Well, that's it, I had enough! I will execute you right now!}
{135}{}{Think about what you did, and I'll come back later.}

{136}{}{You bring Gilmore to the Salt Lake, to face justice. The city will be happy about this.}
{137}{}{Publicly? This means... I will be remembered, right? Yes, I will go and die, just like they all want! And you'll be the one to execute me! YOU!}
{138}{}{Let's go, you piece of shit...}

{139}{}{Before you went to the city you took all of Gilmore's belongings.}
{140}{}{This is not enough. Let's bring you to justice right now! [attack]}
