{100}{}{You see a redneck.}
{101}{}{You see one of the few Provo residents.}
{102}{}{An outsider!}
{103}{}{I'm not in the mood to chat with you}

###################################################
#
#  Floating dialog between Vulvee and Garry
#
#  Markers:
#         v - Vulvee's line
#         g - Garry's line
#
###################################################

{200}{v}{I want attention!!! I'm bored!!!}
{201}{g}{...Stop complaining! I'm trying to concentrate here.}
{202}{v}{Who's this? Ah, it's you, brother...}
{203}{g}{Of course me, who else... You think you are the only one who suffers here?}
{204}{g}{The Boss does not pay any attention to me at all...}
{205}{v}{You're just an ass' hole. And I'm his main thinker!!}
{206}{v}{I NEED STIMULATION!}
{207}{g}{Ass' hole needs stimulation too.}
{208}{g}{I wanna travel! See the blazing Vegas!}
{209}{g}{I want to puke in bars and shit with weed seeds at the casino entrances...}
{210}{g}{...But I'm stuck in this stinky motel instead.}
{211}{v}{Now-now, buddy, we'll get what we want. We'll see the sparks of Vegas.}
{212}{g}{No shit? And how would we do that?}
{213}{v}{I have a plan...}
{214}{v}{::looks around::}
{215}{v}{Shit! I'll tell you later, my meat is burning.}
{216}{v}{Yours is burning all the time...}
{217}{v}{That's better...}
{218}{v}{A little clean from the soot and bon appetit.}
{219}{v}{And why Boss would not make a normal kitchen?}
{220}{v}{I'm always in these stupid pants and I need an apron.}
{221}{v}{What's the deal - go raid a caravan and that's it...}
{222}{v}{::thinks about something::}
{223}{v}{Is he terrified by this Salt Lake sheriff?}
{224}{v}{This asshole won't ever set a foot in this place!}
{225}{v}{They both hate and fear each other...}
{226}{v}{What a drivel, huh!?}
{227}{v}{I had so many great ideas, but Boss just flushed everything down to toilet!}
{228}{v}{Why am I living then? Why?!}
{229}{v}{To fry meat with manure on a pan?!}
{230}{v}{What? Want to give me medal for services? No, cause I overslept!}
{231}{v}{What? I want a holiday in Reno? But the lads have not had their breakfast!}
{232}{v}{No-ope! No rewards! I did not deserve any damn thing.}
{233}{v}{O-oh! I'm so high!}
{234}{v}{I'm full of ideas! My brain explodes from the flow of genius ideas!}
{235}{v}{I could make the gang rise, if not for that... Boss!}
{236}{v}{Again, why all this if I can not even get an apron?!!}
{237}{v}{The Boss only threw all my ideas out of the window...}
{238}{v}{...And I was so serious...}
{239}{v}{::almost cries::}
{240}{v}{...I just wanted to be helpful...}
{241}{v}{...and he won't even thank me!}
{242}{v}{And won't even pat my head!}
{243}{v}{And I'm VULVEE, for Gecko's fuck sake! Not an ass' hole!}