{100}{}{You see a redneck.}
{101}{}{You see one of the few Provo residents.}
{102}{}{An outsider!}
{103}{}{I'm not in the mood to chat.}

###################################################
#
#  Floating dialog between Vulvee and Garry
#
#  Markers:
#         v - Vulvee's line
#         g - Garry's line
#
###################################################

{200}{v}{I want attention!!! I'm bored!!!}
{201}{g}{...Stop complaining! I'm trying to concentrate here.}
{202}{v}{Who's this? Ah, it's just you, my brother...}
{203}{g}{Of course it's me, who else... You think you are the only one who suffers here?}
{204}{g}{The Boss does not pay any attention to me at all...}
{205}{v}{You're just an asshole. And I'm his main thinker!!}
{206}{v}{I NEED STIMULATION!}
{207}{g}{Asshole needs stimulation too.}
{208}{g}{I wanna travel! See the blazing Vegas!}
{209}{g}{I want to puke in bars and shit with weed seeds in front of casino entrances...}
{210}{g}{...But I'm stuck in this stinky motel instead.}
{211}{v}{Now-now, buddy, we'll get what we want. We'll see the sparks of Vegas.}
{212}{g}{No shit? And how would we do that?}
{213}{v}{I have a plan...}
{214}{v}{::looks around::}
{215}{v}{Shit! I'll tell you later, my meat is burning.}
{216}{v}{Your meat is burning all the time...}
{217}{v}{That's better...}
{218}{v}{Brush off a little soot and bon appetit.}
{219}{v}{And why wouldn't Boss make a normal kitchen?}
{220}{v}{I'm always wearing these stupid pants. I need an apron.}
{221}{v}{What's the problem then? Go raid a caravan and that's it...}
{222}{v}{::thinks about something::}
{223}{v}{Is he terrified by this Salt Lake sheriff?}
{224}{v}{This asshole won't ever set a foot in this place!}
{225}{v}{They both hate and fear each other...}
{226}{v}{What a drivel, huh!?}
{227}{v}{I had so many great ideas, but the boss just flushed everything down the toilet!}
{228}{v}{Why am I living then? What's my purpose?!}
{229}{v}{To fry the meat with manure on a pan?!}
{230}{v}{What? To give me a medal of merit? No, because I overslept!}
{231}{v}{What? I want to take a day off in Reno? But the guys haven't had breakfast yet!}
{232}{v}{No-ope! No rewards! I don't deserve any damn thing.}
{233}{v}{O-oh! I'm so high!}
{234}{v}{I'm so full of ideas! My brain explodes from the flow of my genius thoughts!}
{235}{v}{I could make the gang great again, if it weren't for that... Boss!}
{236}{v}{Again, why all this if I can't even get an apron?!!}
{237}{v}{The Boss threw all my ideas out of the window...}
{238}{v}{...And I was so serious...}
{239}{v}{::almost cries::}
{240}{v}{...I just wanted to be helpful...}
{241}{v}{...and he won't even thank me!}
{242}{v}{And won't even pat my head!}
{243}{v}{And I'm VULVEE, for gecko fuck's sake! Not an asshole!}