{100}{}{Rusty door.}
{101}{}{A very rusty, but still very sturdy door. These doors were often installed in prisons. It's impossible to kick out!}
{102}{}{It can't be opened without a key.}
{103}{}{It can't be opened without a key.}
{104}{}{The door is open!}
{105}{}{No luck.}
{106}{}{The lock doesn't give in.}
{107}{}{You successfully open a complicated lock and earn 100 exp. points.}
{108}{}{The lock is mechanical.}
{109}{}{You need a key. Or a lockpick, at least.}
{110}{}{The door is too sturdy for that.}
{111}{}{Dammit!}
{112}{}{You lock the door with the key.}
{113}{}{The door is locked.}
{114}{}{The lock is already picked.}
{115}{}{The lock has already been picked. It can't be double-picked.}
