{100}{}{A water cooler with water in it.}
{101}{}{An empty water cooler.}

{102}{}{You see a cooler filled with clean spring water.}
{103}{}{You see an empty cooler. Someone has chugged all the water.}

{104}{}{Not even a single drop of water is left in this cooler.}
{105}{}{You fill a flask with pure spring water.}
{106}{}{}

{107}{}{There's some water left in this cooler. You'll need a vessel if you want to collect it.}
{108}{}{You need a bottle.}
