{100}{}{It's a lever.}
{101}{}{You see the bridge control lever.}
{102}{}{Thanks to you, this old bridge will serve the tribe for many years to come.}

#Использование рукой
{110}{}{This lever doesn't appear to be connected to anything.}
{111}{}{Something tells you that this lever wasn't always used for decoration.}
{112}{}{Hmm...}
{113}{}{Something tells you that the bridge is gone.}
{114}{}{You don't need that anymore.}

#Использование предметов и навыков
{120}{}{No, this won't help here.}
{121}{}{There's already a rope.}
{122}{}{Good thinking. But with your science skills it will never work.}
{123}{}{Good thinking. But with your repair skills it will never work.}
{124}{}{You use the rope to connect the upper shaft to the lever to make a hoist - but there's nothing to hoist with it.}
{125}{}{The lever is working, but it's not connected to anything.}
{126}{}{The lever is connected to the upper shaft by a rope.}
