{100}{}{}
{101}{}{}

{110}{}{These wood planks can still be used for construction.}
{111}{}{You don't need these planks anymore.}
{112}{}{With your physique, carrying such weights can result in trauma.}
{113}{}{Oomph...}
{114}{}{This will hardly be of any use here.}
{115}{}{Construction completed.}
{116}{}{You've built the hinged part of the bridge.}
{117}{}{These wood planks can be used for construction.}
{118}{}{Just some wooden planks.}
