{0}{}{}
{100}{}{You see a console.}
{101}{}{You see the password console. Looks like it controls a nearby door.}
{102}{}{You have already used this console, you don't need it anymore.}
{103}{}{I don't need this.}
{104}{}{This console has no power supply.}
{105}{}{No power.}

#Начало диалога:
{110}{}{Welcome. Please, enter password.}
{111}{}{[Try to hack the password]}
{112}{}{[Type in the password]}
{113}{}{[Exit]}

{114}{}{Password accepted. Welcome!}
{115}{}{[Finish]}
{116}{}{You hack the security system and gain }
{117}{}{ exp. points.}
{118}{}{Incorrect password.}
{119}{}{Wow, it worked! It's time to enjoy the comforts of someone's office.}

#Процесс подбора пароля
{120}{}{The system only accepts passwords consisting of letters of the English alphabet. All you need to do is cycle through variants.}
{121}{}{Enter the password.}
{122}{}{You are entering: }
{123}{}{?}
{124}{}{Clear last letter.}
{125}{}{Clear everything and start over.}
{126}{}{Password incorrect.}
{127}{}{Password accepted. Welcome!}
{128}{}{Well, time to enjoy the comforts of someone's office.}
{129}{}{This riddle is far beyond me at this point.}
{130}{}{}

{150}{}{A}
{151}{}{B}
{152}{}{C}
{153}{}{D}
{154}{}{E}
{155}{}{F}
{156}{}{G}
{157}{}{H}
{158}{}{I}
{159}{}{J}
{160}{}{K}
{161}{}{L}
{162}{}{M}
{163}{}{N}
{164}{}{O}
{165}{}{P}
{166}{}{Q}
{167}{}{R}
{168}{}{S}
{169}{}{T}
{170}{}{U}
{171}{}{V}
{172}{}{W}
{173}{}{X}
{174}{}{Y}
{175}{}{Z}
{176}{}{-more-}
{177}{}{Finish entering the password.}
{178}{}{To the beginning of the alphabet.}
{179}{}{Back.}
