{100}{}{You see a working terminal.}
{101}{}{You see a functional computer terminal.}

#Запуск компьютера:
{110}{}{You cannot use this terminal until you restore power.}
{111}{}{No power}
{112}{}{This terminal is working, but cannot connect to the station's server, which is located in a different part of the bunker.}
{113}{}{[Exit.]}
{114}{}{You lack the scientific knowledge to effectively use this kind of software.}

#Главное меню:
{115}{}{Welcome to the Lovelock information channel broadcasting network.}
{116}{}{[Look for any record of past broadcasts.]}
{117}{}{[Scan every frequency for a signal.]}
{118}{}{}
{119}{}{}
{120}{}{}
{121}{}{[Read the mission statement for this station.]}
{122}{}{[End.]}
{123}{}{[Return to main menu.]}
{124}{}{[End.]}

#Функции станции
{150}{}{Access granted. Searching... Search complete. The Lovelock radio station is designated for top-secret government and military broadcasting. All workers must sign a non-disclosure agreement related to any information obtained during the course of receiving, processing, and transmitting messages via the Lovelock radio station. Current primary functions include: Production, processing and transmission of radio signals between military installations, top-secret laboratories, the Vault network and government staff within the state of Nevada.}

#История трансляций
{151}{}{Access granted. Searching... Search complete.}
{152}{}{[Determine the the station's signal coverage.]}
{153}{}{[Scan every frequency for a signal.]}
{154}{}{}

#Попытка трансляции
{155}{}{Access granted. Initializing program... [you hear nothing but white noise on all channels]}
{156}{}{[Examine the archive of previous communication contacts.]}
{157}{}{}
{158}{}{[Under normal conditions, the station's range would include the entire state of Nevada. When running on emergency power, however, the station's signal barely reaches Vault City.]}
{159}{}{[Scan every frequency for a signal.]}
{160}{}{[Broadcast a message.]}
{161}{}{[No one responds.]}
{162}{}{[You hear nothing but static.]}
{163}{}{[Scan every frequency again.]}
{164}{}{}
{165}{}{}
{166}{}{}
{167}{}{}
{168}{}{Searching... Search complete. [The list is mostly made up of various settlements where wiretapping was conducted before the war. Additional contacts include three military bases (Sierra, Hawthorne, and Area 51), several vaults (8, 13, and 15), and private laboratories. All of these contacts are located within or close to Nevada borders, but their exact locations are not listed. Radio operators don't need a contact's exact location - they just work within their channels.]}
{169}{}{The Lovelock radio station receives and transmits signals on a predetermined range of communication channels designated within Project }
{170}{}{. Wiretapping programs are not currently in effect.}
{171}{}{[Find information on this project.]}
{172}{}{Project }
{173}{}{ is a communication system used for encrypted communication between top-level military and government personnel. It incorporates signal encoding, fixed communication channels not available for civilian use, and a nation-wide network of relay stations capable of operating autonomously for 100 years. This system will guarantee that top-priority communication between departments is uninterrupted even in emergency conditions.}
{174}{}{Hmm, this name is... Familiar?}
{175}{}{Project }
{176}{}{ is named in honor of one of the most powerful nuclear tests in American history.}
{177}{}{That's all the information I need.}

#Пароли:
{301}{}{HIROSHIMA}
{302}{}{NAGASAKI}
{303}{}{TRINITY}
{304}{}{CASTLE}
{305}{}{BRAVO}
{306}{}{EASY}
{307}{}{RANGER}
{308}{}{YOKE}
{309}{}{BAKER}
{310}{}{FATMAN}
{311}{}{LITTLEBOY}
