{100}{}{You see a generator.}
{101}{}{You see an ordinary generator. Judging by the labels, it is responsible for powering the central equipment.}

{102}{}{Looks like the ants have damaged this generator, but it can still be repaired.}
{103}{}{Repairs needed.}
{104}{}{}
{105}{}{The generator is operational and supplies power to the station.}
{106}{}{No use.}
{107}{}{Generator works and does not need repair.}
{108}{}{You've repaired the generator. It is now powering the server.}
{109}{}{Done.}
{110}{}{It won't do any good here. The generator needs to be repaired.}
{111}{}{You fail to repair the generator.}