{100}{}{You see a generator.}
{101}{}{You see an ordinary generator. Judging from the markings, its responsible for the station's lights.}

{102}{}{The generator was damaged by the explosion. You will need to replace some parts to repair it.}
{103}{}{Parts are missing.}
{104}{}{The generator is functional and is powering the station.}
{105}{}{This generator is in working order}
{106}{}{This generator need parts, not fuel.}
{107}{}{Useless.}
{108}{}{This won’t help here.}
{109}{}{Done.}
{110}{}{You replace the damaged parts. The generator is in working condition.}
{111}{}{Without replacing some parts, the generator won’t work.}