{100}{}{It's a switch.}
{101}{}{You see a light switch. It's in the "on" position.}
{102}{}{You see a light switch. It's in the "off" position.}
{103}{}{This switch turns on the lights in the underground level of the station.}

{110}{}{You switch the lights off. The underground level of the station sinks into darkness.}
{111}{}{You turn on the lights in the underground level of the station.}
{112}{}{Hmm, the flick of the switch didn't seem to have any effect. Maybe the power went out?}
{113}{}{Done.}
{114}{}{Let there be darkness!}
{115}{}{Let there be light!}
{116}{}{Nothing happens.}
