{100}{}{A cabbage.}
{101}{}{A huge head of cabbage to make a nice salad out of.}

{102}{}{Delicious greens! Add some brahmin meat and you have a healthy dinner.}
{103}{}{This vegetable would make a good dinner if it had meat to go with it. But its owner will hardly like this idea of yours.}
{104}{}{Just like that!}
{105}{}{You ravage the vegetable to make yourself a sandwich. Its owner probably won't like it. You dirty thief!}
