{100}{}{You see lab computer terminal.}
{101}{}{You see an old lab computer terminal, stuffed to the brim with research data.}

#Ãëàâíîå ìåíþ 
{110}{}{This computer coordinates the work of all departments of the laboratory. There is a lot of interesting information. Select a topic.}
{111}{}{Production reports.}
{112}{}{Experiments.}
{113}{}{Goals for the next year.}
{114}{}{}
{115}{}{}
{116}{}{}
{117}{}{[Go back]}
{118}{}{[Main Menu]}
{119}{}{[Shut down]}

#Îò÷åòû î ïðîèçâîäñòâå
{120}{}{Select product name.}
{121}{}{Steroids.}
{122}{}{Psychedelics.}
{123}{}{Methamphetamines.}
{124}{}{Medications.}
{125}{}{Special order from the Clean City.}

{130}{}{This lab unsuccessfully tried to develop drugs like buffout, but it was too difficult with the local working conditions. Test samples were issued, each of which was later recognized as defective. However, the samples were spread among dealers (possibly at the cost of a few customers' lives).}
{131}{}{This is one of the main products of the Pound. Various kinds of psychedelics were produced, including LSD, mescaline and psilocybin. The main focus was on hallucinogenic mushroom-based chemicals. These products were successful not only with the locals, but also outside of Vegas. Looks like a lot of people in this world want to escape reality...}
{132}{}{Data purged.}
{133}{}{Medication pool is small. It includes stimulants, some pain killers, therapeutic powders made out of plants and a number of low-value drugs. All batches were produced relatively recently, meaning that the laboratory had not previously worked with such products.}
{134}{}{Some influential person from the Clean City made an order through intermediaries to manufacture light drugs with minor addictive effects. Even though no names are listed, it's clear the Pound has its own people in Clean City.}

#Ýêñïåðèìåíòû
{140}{}{The Pound held a series of experiments, both in recreating old drugs and medicines and creating completely new ones. It seems some smart people worked here.}
{141}{}{Experiment "Psycho".}
{142}{}{Experiment "Buffout".}
{143}{}{Experiment "Mentats".}
{144}{}{Psychedelics experiments.}
{145}{}{Other experiments.}

{150}{}{This old military drug has become a real panacea for management. For some time the lab was engaged exclusively in attempting the independent re-creation of psycho. Such a product would bring big profits to the Pound. But local conditions, equipment, and the lack of necessary components have only led to shutting down research.}
{151}{}{Similar to "Psycho", the project was closed due to an inability to manufacture it in local conditions.}
{152}{}{Unlike the "Buffout" and "Psycho" experiments, "Mentats" could go into mass production... But the drug appeared to be unprofitable. Considering the large labor and resource costs, the Pound couldn't compete with pre-war reserves in the region. In addition, the current demand for this product was clearly less than for a number of other drugs.}
{153}{}{Psychedelics long held a priority place in production... Until they flooded the market so much that the Pound itself ran into distribution problems. As a result, the management ordered a series of experiments on LSD and other psychedelic substances in order to make them more broadly useful. For example, a "Bromine-LSD" project designed to create LSD without psychedelic effects, could have been useful for people with various brain disorders, for example, cluster pains. Too bad the Clean City decided they have to uproot psychedelics from the market completely.}
{154}{}{In order to stop attacks from the police and remove the conspiracy factor, the management of the Pound sought to legalize business in the Clean City. To do this the Pound tried to take up production of various "peaceful" medications such as stimpaks and painkillers.}

#Öåëè íà ñëåäóþùèé ãîä
{160}{}{The highest priority goals: 1. Complete "Bromine-LSD"; 2. Organize a stable delivery line to New Reno; 3. Reduce the death rate among the slaves by 15% or more; 4. Replicate a fighting stimulant recipe from Reno.}

#Äîñòèæåíèå "Çíàõàðü"
{170}{}{See more about medicinal herbs.}
{171}{}{Here lies the knowledge database of the beneficial properties of various medicinal herbs: Xander root, Broc flowers, Nightshade and many others. Local scientist gathered information from every corner of the region, studied plants and conducted experiments with the creation of drugs and narcotics. Not many who were curious could understand this research.}
{172}{}{[Examine the data]}
{173}{}{[Leave and proceed to the next section]}
