{100}{}{You see lab computer terminal.}
{101}{}{You see an old lab computer terminal, stuffed with research data.}

#Главное меню 
{110}{}{This computer coordinates the work of all departments of the laboratory. There is a lot of interesting information. Select a topic.}
{111}{}{Production reports.}
{112}{}{Experiments.}
{113}{}{Goals for the next year.}
{114}{}{}
{115}{}{}
{116}{}{}
{117}{}{[Go back]}
{118}{}{[Main Menu]}
{119}{}{[Shut down]}

#Отчеты о производстве
{120}{}{Select product name.}
{121}{}{Steroids.}
{122}{}{Psychedelics.}
{123}{}{Methamphetamines.}
{124}{}{Medications.}
{125}{}{Special order from the Clean City.}

{130}{}{This lab unsuccessfully tried to develop drugs like buffout, but it was too difficult with local working conditions. Test samples were issued, each of which was later recognized as a defective. However, samples were spread among dealers (possibly at a cost of customers' lives).}
{131}{}{This is one of the main products of the Pound. Here were created various kinds of psychedelics, including LSD, mescaline and psilocybin. The main focus was chemicals based on hallucinogenic mushrooms. Products were successful not only among locals, but also outside of Vegas. Looks like many people in this world want to escape reality...}
{132}{}{Data purged.}
{133}{}{Medication pool is small. It includes stimulants, some pain killers, therapeutic powders made out of plants and a number of low-value drugs. All batches were produced relatively recently, meaning that the laboratory had not previously worked with such products.}
{134}{}{Some influential person from the Clean City has made an order through intermediaries to manufacture light drugs with a small addiction effect. Even though the names are not listed, it becomes clear that the Pound has its own people in Clean City.}

#Эксперименты
{140}{}{The Pound held a series of experiments, both in recreating old drugs and medicines and creating completely new ones. It seems that smart people worked here.}
{141}{}{Experiment "Psycho".}
{142}{}{Experiment "Buffout".}
{143}{}{Experiment "Mentats".}
{144}{}{Psychedelics experiments.}
{145}{}{Other experiments.}

{150}{}{This old drug of military origin has become a real panacea for management. For some time the lab was engaged exclusively in attempts of independent creation of psycho. Such product would bring big profits to the Pound. But local conditions, equipment and the lack of the necessary components have only led to shutting down the research.}
{151}{}{Similar with "Psycho", the project was closed due to inability to manufacture it in local conditions.}
{152}{}{Unlike "Buffout" and "Psycho" experiments, "Mentats" could go into mass production... But the drug appeared to be unprofitable. Considering the large labor and resource costs, the Pound couldn't compete with pre-war reserves in the region. In addition, the current need for this product was clearly less than for a number of other drugs.}
{153}{}{Psychedelics long held a priority place in the production... Until they filled the market so much that the Pound itself ran into distribution problem. As a result, the management appointed a series of experiments on LSD and other psychedelic substances in order to make them more demanded. For example, "Bromine-LSD" project designed to create LSD without psychedelic effect, which could be useful for people with various brain disorders, for example, cluster pains. Too bad the Clean City decided that psychedelics have to uproot from the market completely.}
{154}{}{The management of the Pound sought to legalize itself in the Clean City, in order to stop attacks from the police and remove the conspiracy factor. To do this, the Pound tried to take up the production of various "peaceful" medications, such as stimulants and painkillers.}

#Цели на следующий год
{160}{}{The highest priority goals: 1. Complete "Bromine-LSD"; 2. Organize a stable delivery line to New Reno; 3. Reduce the death rate among the slaves by 15% and more; 4. Replicate the recipe of a fighting stimulant from Reno.}

#Достижение "Знахарь"
{170}{}{See more about medicinal herbs.}
{171}{}{Here lies the knowledge database about beneficial properties of various medicinal herbs: Xander, Broc, Nightshade and many others. Local scientist gathered information from every corner of the region, Studied plants and conducted experiments on the creation of drugs and narcotic substances. Not every single curious one could understand these scientific researches.}
{172}{}{[Examine the data]}
{173}{}{[Leave and proceed to the next section]}
