{100}{}{You see a water tank.}
{101}{}{You see a huge tank full of fetid rainwater. It's rusted through and leaking in several spots.}
{102}{}{You see a huge water tank. It has seen better days, but it is still watertight.}
{103}{}{You can't examine the water tank in combat!}

#Описание при юзанье или использовании навыков
{110}{}{It's just a huge water tank.}
{111}{}{You see a huge water tank. It's almost empty.}
{112}{}{Good as new!}
{113}{}{All the leaks in the water tank have been patched. The tribe will be happy to hear about this.}

#Описание в режиме диалоге
{120}{}{You see the tribe's leaking water tank.}
{121}{}{[Examine the tank more thoroughly]}
{122}{}{[Attempt to repair the tank]}
{123}{}{[Leave it be]}

{124}{}{The tank has rusted through in several spots and leaks constantly. It can be repaired, but you'll need a lot of scrap metal.}
{125}{}{You'll need more scrap to fix this.}
{126}{}{(I don't have the skill to fix this.)}
{127}{}{[Repair the water tank.]}
{128}{}{Repairing this tank will be a long, difficult, and resource-intensive effort.}
{129}{}{It takes some careful thought and a skilled hand, but you manage to patch the tank's leaks using several pieces of scrap metal. This tank should continue to serve the tribe for many years to come.}
{130}{}{Great!}
