{100}{}{The old wall completely crumbles into dust.}

{101}{}{You examine the water tank and find some murky water in it. It looks like that's what the raiders are drinking, unless they can get something stronger. They're probably suffering from dysentery. And if you mess up the water a little more, it'll be deadly even to them.}
{102}{}{[Leave]}
{103}{}{You have some poison, but it is not enough for so much water.}
{104}{}{You have enough poison to lethally intoxicate all the raiders.}
{105}{}{Release poison into the water tank.}
{106}{}{You've released deadly poison into the water tank. Now whoever who drinks this water will die... At least, that's what you're counting on. It's worth going back in a day to test this hypothesis.}
{107}{}{}
{108}{}{Water is still undrinkable.}
{109}{}{It looks like that's what the raiders were drinking, if they couldn't get something stronger. They must be suffering from dysentery.}
{110}{}{The water is still poisoned.}
{111}{}{One dose of poison won't be enough, you'll need at least two more. [Leave]}
{112}{}{Two doses of poison are not enough. If someone is left alive, they'll realize what happened. If only you could get another dose... [Leave]}
{113}{}{Looks like the poison worked. The raiders are all dead. And from the looks of it, their deaths were not easy or painless.}

{114}{}{Not during combat!}
{115}{}{Raiders used to drink this muddy water. but now no one wants it.}
{116}{}{This water is poisoned.}
