{100}{}{Better not to go in there}
{101}{}{You can't go in there}
{102}{}{Get away from there!}
{103}{}{You shouldn't go there}
{104}{}{Hey, I'm still watching you!}
{105}{}{Where do you think you're going?}
{106}{}{The Chief's hut is the other way, outsider}
{107}{}{What are you going there for?}
{108}{}{What do you want there?}
{109}{}{What do you have in mind?}
{110}{}{Get back here now!}
{111}{}{Looking for trouble?}

{112}{}{Outsider, this is not your hut!}
{113}{}{Outsider, get out of this hut!}
{114}{}{Outsider, the Chief lives in the other hut.}
{115}{}{You weren't invited}

{116}{}{Where are you hiding, outsider? Come out, you're just making it worse for yourself!}