{100}{}{Body.}
{101}{}{The body is chest-deep in the nest, but what's sticking out still seems to be breathing!}

#Диалог:
{102}{}{Uhh... Mghhhh...}
{103}{}{Hey! Can you hear me? Do you understand what I'm saying?}

{104}{}{Maaaahh...}
{105}{}{You don't look too good. Maybe I should pull you out of the nest?}
{106}{}{[Leave him be]}

{107}{}{Ugghh... Help...}
{108}{}{[Try to pull him out]}
{109}{}{[Leave him be]}

#Таймерная сцена:
{110}{}{Hey, get up before we get eaten!}
{111}{}{Come on!}
{112}{}{Holy shit!...}
{113}{}{You're lucky to be alive!}
{114}{}{What the... Wait a second, I feel a little weird...}
{115}{}{What?}
{116}{}{A-A-A-A-A-A-AH!!!}

{117}{}{What the hell was that?}
{118}{}{This poor fellow's end was sealed.}

#Таймерные плавающие реплики
{120}{}{::moan::}
{121}{}{::whizz::}
{122}{}{Ooh...}
{123}{}{Hurr...}
{124}{}{Mmmph...}
{125}{}{Help...}

#После выпуска газа
{200}{}{This ghoul is a goner. It appears he didn't die while being sucked into this biomass, but when biomass died from gas, this man died together with it.}
{201}{}{[Search the corpse for valuables]}
{202}{}{[Leave the corpse]}
{203}{}{These remains are of no interest to you now.}
{204}{}{You unexpectedly find a red keycard within the remains.}
{205}{}{Nothing else here.}
