{100}{}{You see a punching bag.}
{101}{}{You see a punching bag. You feel like it's inviting you to try it out. You almost hear "Don't miss the opportunity!" in your head.}
{102}{}{You can warm up your fists and try out new fighting techniques on this bag.}
{103}{}{Hmm, why not?}
{104}{}{The bag is so weathered from your training that it's become unusable.}
{105}{}{This bag is useless.}
{106}{}{This bag could be useful for your skills, but they are already too high.}
{107}{}{Training? I don't need this anymore...}
{108}{}{You spend about an hour training and increase your unarmed skill by 5%.}
{109}{}{Nice.}

{110}{}{You should not practice while there are enemies nearby..}
{111}{}{You can't take any chances - aliens are everywhere.}