{100}{}{You see a controller.}
{101}{}{You see a controller feeding power from the substation to the base buildings. It's damaged.}
{102}{}{You see the power controller from the substation to the base buildings. It's buzzing and delivering current.}

{103}{}{The controller has burned out parts and torn wires. You need to replace them.}
{104}{}{Need to replace the parts.}
{105}{}{This equipment is in working condition and doesn't need repair.}
{106}{}{Everything is in order.}

{107}{}{It is hardly appropriate here.}
{108}{}{It's useless}

{109}{}{This generators doesn't need recharging, it needs replacement parts.}
{110}{}{Done.}
{111}{}{Without replacing some parts, you won't be able to fix the generator.}

{112}{}{You replace the damaged parts of the generator. Now the nearest buildings are getting powered with electricity.}

{114}{}{Your repair skills are not good enough.}
{115}{}{Can't do that.}
