#Аварийный выключатель в ремсекторе:
{100}{}{Emergency lights switch.}
{101}{}{You see the switch for emergency lights on this floor.}
{102}{}{You switch on the lights in all corridors on the floor.}
{103}{}{You switch off the lights in all corridors on the floor.}

#Обычный выключатель света в лаборатории:
{110}{}{It's a light switch.}
{111}{}{You see an ordinary lab light switch.}
{112}{}{You switch on the light in the laboratory.}
{113}{}{You switch off the light in the laboratory.}

#Обычный включатель света в лаборатории:
{120}{}{This is a switch.}
{121}{}{You see a normal switch for the projectors in the hangar.}
{122}{}{You turn on the lights.}
{123}{}{You turn off the lights.}
