{100}{}{You see a computer.}
{101}{}{You see a common office computer. The only thing that separates it from the rest is that it still works.}

#Òèïîâûå ôðàçû:
{110}{}{The system is ready to work. Enter a command.}
{111}{}{[Log out]}

{113}{}{[Back]}
{114}{}{[Back to the list]}
{115}{}{Read the next note.}

#Ñïèñîê ñëóæåáîê:
{120}{}{Look at a list of notes.}
{121}{}{Check out the hangar zone layouts.}

{122}{}{Reports on malfunctions in the turret control program.}
{123}{}{Reports on errors in the force fields functionality.}
{124}{}{Look for any mention of Vault 8.}

#Ñõåìû ïîìåùåíèé:
{130}{}{It turns out that the hangar extends many floors down. Some floors cannot be viewed because of a lack of access rights. Almost every floor is a laboratory or technical workshop. Apparently, the local military had a very busy schedule.}
{131}{}{Watch the first underground floor.}
{132}{}{The first underground floor is also a large laboratory. In addition, the control center for the external line of defense is located here (obviously, it means the turrets and surveillance cameras), as well as the emergency generator, the force field control systems, and external ventilation. It's impossible to get below the first underground level due to strict security regulations.}
#Ñëóæåáêè:
{140}{}{Memos for the last available month have been sorted by topic. They are mostly the usual production and delivery reports, but you see a few interesting notes.}
{141}{}{Select a note to read.}

{142}{}{"About an error in the turrets control program"}
{143}{}{"Proposal to install a SoS kit"}
{144}{}{"Receipt of delivery of the SoS kit"}
{145}{}{"Report on SoS kit installation"}

{146}{}{This is a notification from a security officer stating that there was some kind of bug in the turret control program. The program glitched regularly which, in turn, led to frequent restarts. Each restart would disable the turrets for 10 to 20 seconds. Despite attempts to fix the program, the engineers could not solve the problem. In their opinion, it was caused by experiments on the lower levels of the hangar, which resulted in strong electromagnetic waves.}
{147}{}{This is a suggestion by some security employee, to install a more advanced "System of Security" kit in place of the control turrets program. This would fix the problem of restarts and significantly improve the effectiveness of the hangar's security systems. The response memo indicates the approval of it. You are not sure, but looks a system like this is used in your Vault.}
{148}{}{As listed on the receipt, the security service employee received a complete and working SoS kit. The kit was brought from Hawthorne after field tests, then further upgraded by local engineers based on the feedback. The security service was ordered to connect the kit to the security systems and check if it worked as intended.}
{149}{}{The report indicates the installation of Hawthorne's SoS kit did not produce the expected results. The kit, for some unknown reason, didn't work. The manufacturer sent a statement about the need to retest the kit, but no response was given. Apparently, the military had no time to deal with the matter due to the outbreak of the Great War. In the end, the hangar was left without any external protection - the turrets were temporarily disabled.}
{150}{}{"Order on scheduled testing of force fields"}
{151}{}{"A proposal to tighten the access rights"}
{152}{}{"A notification about the start of force fields reprogramming procedure"}

{153}{}{An order to carry out systematic and routine inspections of the force fields. The inspector must inform the head of security and management of the laboratories about each cause of malfunction.}
{154}{}{The Department of Security proposed putting in use personal key cards to separately control the force fields. As it stands now, any staff member with intermediate access can enable or disable them all, which obviously did not meet security standards. Command ordered that the force fields must be reprogrammed and that sets of magnetic key cards with high levels of encryption must be produced. The order was sent to the maintenance sector, which resulted in adjustments to the force fields' mode of operation.}
{155}{}{The maintenance sector's worker informed command that the force field would be temporarily disabled due to reprogramming. Downtime was up to three days.}
{156}{}{"A report on the results of force field's reprogramming"}
{157}{}{Maintenance sector reported positive results from the power field reprogramming. A list of all personnel provided with magnetic key cards had been prepared. In addition, a new mode of operation had been enabled for the force fields.}
{158}{}{"A notification about force field's working mode changes"}
{159}{}{The maintenance sector reported the activation of an enhanced operation mode for the force fields. Specifically, it says that due to the high utilization rate of the equipment generating the force fields, periodic two-hour shutdowns were implemented. In the absence of a control check procedure, which must be performed every 60 days and recorded in the computer on the first underground level, the force fields will automatically shut down for fire safety purposes, pending forced activation (i.e. until the next control check procedure).}

{160}{}{Read order 1123.}
{161}{}{Summarize data about Project Vault 8.}
{162}{}{Information is scattered, but some documents are marked with a "Project Vault 8" label.}
{163}{}{This order was to set up a transmit point of surveillance for monitoring Vault 8. The station itself did not store any data - only relayed data to the top of the chain of command: the Hawthorne military base. After that, the processed data was transmitted in the form of reports to Area 51.}
{164}{}{Although the vault network was not part of Area 51's area of responsibility, Vault 8 was an exception. The reason for this was that the vault was given a Governmental Facility status. In an emergency, Area 51 was supposed to contribute to the protection of the vault, but not to interfere in internal affairs. There was even an initiative to install a force field barrier around the area, but there was not enough time or funding, as too many resources had already been allocated for the project. The function of guarding the vault was by default assigned to the Hawthorne military base, but in case of its inability to perform this duty, the task was to be delegated to Area 51.}
