{100}{}{You see a computer.}
{101}{}{You see the maintenance computer. It coordinates the operation of the force fields.}

#Диалог
{110}{}{This computer controls the force fields and doors on this level of the hangar.}
{111}{}{[Get access to all doors on this hangar level]}
{112}{}{[Force field control]}
{113}{}{[Leave the computer]}

{114}{}{Done.}

{120}{}{Force field are disabled by automatic fire suppression systems. You can change the current force field protocol from this terminal.}
{121}{}{From this terminal you can change the current working mode of the force fields.}
{122}{}{[Restore the force fields]}

{127}{}{[Set the mode of the force fields]}
{128}{}{Apparently, there are two modes. Cold mode completely prevents objects from passing through the force field. The thermal mode forms a field of increased heat. It is probably very dangerous.}
{129}{}{[Set cold mode]}
{130}{}{[Set thermal mode]}
{131}{}{Done. The cold mode is selected.}
{132}{}{Done. The thermal mode is selected.}