{100}{}{You see a computer.}
{101}{}{You see a powerful security service computer.}

{102}{}{You see a security service computer.}
{103}{}{[Cancel]}
{104}{}{[Next]}

#Àêòèâàöèÿ áîìáû:
{105}{}{Hm... Self-destruct protocol - what's this?}

{109}{}{As you would expect, this command initiates the self-destruction of the hangar along with the underground levels below it. The command activates a nuclear warhead with a 0.3 kiloton plutonium charge, which is walled up in the lower levels. If you activate it, you will have to run like hell to avoid being hit by the blast wave.}
{110}{}{Try to break into the system and activate the protocol}
{111}{}{[Leave this section]}

{112}{}{To crack this protection system, you have to almost be a computer genius. This is clearly beyond your skill.}
{113}{}{}
{114}{}{You find a way to circumvent the protection system and activate the hangar's self-destruct protocol.}
{115}{}{Well, it's time to do it!}
{116}{}{No way, leave this thing as it is.}
{117}{}{Select the time delay for the protocol activation.}

{119}{}{You set the time and boldly press the red button. It's time to think about your future, if you don't want to become the part of the background radiation...}
{120}{}{[Run like hell]}

{121}{}{1 minute.}
{122}{}{2 minutes.}
{123}{}{3 minutes.}
{124}{}{4 minutes.}
{125}{}{5 minutes.}
{126}{}{Refuse to activate and leave.}
{127}{}{[Return to main menu]}
{128}{}{Cancel. Return to main menu.}

{129}{}{You find the assembly schematics. However, the process looks too intricate for you, so without special knowledge in the field of subversive matters these schematics won't help you.}

{131}{}{Doesn't work}
{132}{}{Terminal is offline.}

#Àêòèâàöèÿ òóðåëåé:
{200}{}{Examine the turret operational program.}
{201}{}{Run the turret operational program.}
{202}{}{Return to main menu.}
{203}{}{Shut down.}
{204}{}{It seems the program doesn't work.}
{205}{}{Search for reports.}
{206}{}{The computer has an unfinished bug report, but no clear algorithm for fixing the program is found.}
{207}{}{Look into the source code.}
{208}{}{It's too difficult for you.}
{209}{}{Spending six hours on analyzing the code, you find that the error was in a cyclic subroutine checking the signal variables of the turrets. But since the signal and the cycle were out of sync, the program took it as a malfunction in the computer and restarted. You could reset the cycle to get rid of this problem and to make the program work again.}
{210}{}{Rewrite the code to complete the extermination of aliens, then recompile.}
{211}{}{Ready. Start the program?}
{212}{}{Yes.}
{213}{}{No, leave it offline.}
{214}{}{Done! The program is up and running. On the surveillance monitors you can see turrets shooting aliens crawling behind the hangar walls.}
{215}{}{Not with your intelligence.}
{216}{}{With your education, there is *absolutely* nothing to do.}
{217}{}{If you were more educated, perhaps you could've read the code.}
{218}{}{Perhaps you could've understand the code if you were more educated.}
