{100}{}{You see a computer.}
{101}{}{You see a common office computer. The only thing that separates it from the rest is that it still works.}

#Типовые фразы:
{110}{}{The system is ready to work. Enter the following command.}
{111}{}{[Log out]}

{113}{}{[Back]}
{114}{}{[Back to the list]}
{115}{}{Read the next note.}

#Список служебок:
{120}{}{Look at list of notes.}
{121}{}{Check out the hangar zone layouts.}

{122}{}{Reports on malfunctions in the turret control program.}
{123}{}{Reports on errors in the force fields functionality.}
{124}{}{Look for any mention of Vault 8.}

#Схемы помещений:
{130}{}{It turns out that the hangar extends many floors down. Some floors cannot be viewed because of the lack of access rights. Almost every floor is a laboratory or technical workshop. Apparently, the local military had a very busy schedule.}
{131}{}{Watch the first underground floor.}
{132}{}{The first underground floor is also a large laboratory. In addition, here is located the control center of the external line of defense (obviously, it means the turrets and surveillance cameras), as well as the emergency generator and the control systems of the force fields and external ventilation. It is impossible to get below the first underground level due to strict security regulations.}
#Служебки:
{140}{}{Memos for the last available month have been sorted by topic. They are mostly usual production and nutrition reports, but you see a few interesting notes.}
{141}{}{Select a note to read.}

{142}{}{"About an error in the turrets control program"}
{143}{}{"Proposal to install a SoS kit"}
{144}{}{"Receipt of delivery of the SoS kit"}
{145}{}{"Report on SoS kit installation"}

{146}{}{This is a notification from a security officer stating that there was some kind of bug in the turret control program. The program glitched regularly, which, in turn, led to frequent restarts. Each restart would disable the turrets for 10 to 20 seconds. Despite attempts to fix the program, the engineers could not solve the problem. In their opinion, it was caused by experiments on the lower levels of the hangar, which resulted in strong electromagnetic waves.}
{147}{}{This is a suggestion of some security employee, to install more advanced "System of Security" kit in place of the control turrets program. This would fix the problem of restarts and significantly improve the effectiveness of the hangar's security systems. The response memo indicates the approval of it. You are not sure, but looks like system like this is used in your Vault.}
{148}{}{As listed on the receipt, the employee of security service has received complete and working SoS kit. The kit was brought from Hawthorne after field tests, then further upgraded by local engineers, based on the feedback. The security service ordered to connect the kit to the security systems and check if it works as intended.}
{149}{}{As the report indicates, the installation of Hawthorne's SoS kit did not produce expected results. The kit, for an unknown reason, didn't work. The manufacturer sent a statement about the need to retest the kit, but no response was given. Apparently, the military had no time to deal with the matter due to the outbreak of Great War. In the end, the hangar was left without any external protection - the turrets were temporarily disabled.}
{150}{}{"Order on scheduled testing of force fields"}
{151}{}{"A proposal to tighten the access rights"}
{152}{}{"A notification about the start of force fields reprogramming procedure"}

{153}{}{An order on carrying out systematic routine inspection of the force fields. The inspector must inform the head of security and management of the laboratories about each case of malfunction.}
{154}{}{The Department of Security proposes putting in use personal key cards to separately control the force fields. As it stands now, any staff member with intermediate access can enable or disable them all, which obviously does not meet security standards. Command ordered that the force fields must be reprogrammed and that sets of magnetic key cards with high levels of encryption must be produced. The order was sent to the maintenance sector, which resulted in adjustments to the force fields' mode of operation.}
{155}{}{The maintenance sector's worker informs that the force field will be temporarily disabled due to reprogramming. Downtime is up to three days.}
{156}{}{"A report on the results of force fields reprogramming"}
{157}{}{Maintenance sector reports positive results of power field reprogramming. A list of all personnel provided with magnetic key cards has been prepared. In addition, a new mode of operation has been enabled for the force fields.}
{158}{}{"A notification about force fields working mode changes"}
{159}{}{The maintenance sector reports the activation of enhanced operation mode for the force fields. Specifically, it says that due to the high utilization rate of the equipment generating the force fields, periodic two-hour shutdowns are implemented. In the absence of a control check procedure, which must be performed every 60 days and recorded in the computer on the first underground level, the force fields will automatically shut down for fire safety purposes, pending forced activation (i.e. until the next control check procedure).}

{160}{}{Read the order 1123.}
{161}{}{Summarize data about the project Vault 8.}
{162}{}{Information is scarce and scattered, but each document is marked by a special mark "Project Vault 8".}
{163}{}{The order was to set up a transit point of surveillance to monitor Vault 8. The station itself did not store any data - only relayed them to the top of the chain: the Hawthorne military base. After that, the processed data was transmitted in the form of reports to Area 51.}
{164}{}{Although the vault network was not part of the Area 51 area of responsibility, Vault 8 was an exception. The reason for this was that, for some reason, the vault had a status of governmental facility. In an emergency, Area 51 was supposed to contribute to the protection of the vault, but not to interfere in internal affairs. There was even an initiative to install a force field barrier around the area, but there was not enough time and funding, as too many resources had already been allocated for the project. The function of guarding the vault was by default assigned to the Hawthorne military base, but in case of its inability to perform such functions, the task was to be delegated to Area 51.}
