{100}{}{You see a lab computer.}
{101}{}{You see a lab computer. In working condition.}

#После взлома, изучение архивов:
{200}{}{Access granted. You are at the main menu and have the opportunity to explore the archives with reports and calculations on various projects.}
{201}{}{See the documentation.}
{202}{}{Select a category.}
{203}{}{[Exit]}

{204}{}{Reports on "aliens" experimentations.}
{205}{}{Documentation on the gas protection system.}
{206}{}{Documentation for the "Ghost F-31" project.}
{207}{}{[Back]}
{208}{}{Select a document to read.}

{209}{}{"Acts about experiments for the last five quarters"}
{210}{}{"Report about the weaknesses of aliens"}
{211}{}{"Report on thermal vision of aliens"}
{212}{}{"The report about the incident in winter of 2077"}
{213}{}{"The order to enhance the security level"}

{214}{}{The aliens were humiliated in full. They were tested every week with various kinds of physical and biological impacts. As it turned out, the aliens are strong animals with huge military potential - one of them is capable to deal with a whole squad. Scientists tried to tame them for later use as a living weapon against enemies. However, while their combat potential was never in doubt, the taming part had failed.}
{215}{}{Looks like they have no known weaknesses. The only damage type proven to be better than the others is fire. The only things that is somehow calming is that for reproduction these creatures require a special conditions: high radiation level, heated, moist environment, lack of light. Besides, females of the species are born one in a thousand, so the probability of the continuation of their kind is extremely small, and, sooner or later, the species should die out. Sounds good, except the life cycle of aliens is more than 70 years.}
{216}{}{That explains why the aliens are met across the wasteland usually in the dark: they see in heat vision, with focus on the speed of victim's movement. During the day they hibernate, as heated environment interrupts with the thermal sight, leading to aliens having harder time to navigate themselves. Considering this information, researchers undertook the development of a unique equipment piece - a corset, which could hide a thermal radiation of a human.}
{217}{}{In the winter of 2077, some incident happened in the lab, when, due to the negligence of the employees, the experiment on female alien got out of control. Test subject slipped into the corridor. Apparently, these creatures are not stupid, as the mutant quickly assessed the environment and escaped through the vents into the desert. The military found traces in caves in the C sector, but didn't risk the soldiers and blew up all exits. Six months later, the creature has reminded of itself again.}
{218}{}{The order of implementing of the force field system came after the incident in the winter of 2077. The military tried to maximize the protection from a test subjects. Apparently, they understood how they underestimated the capabilities of aliens. Further process was supervised by the commanding officers of A5 sector, together with maintenance department. So, maybe there's some information on the first level, about what happened to force fields and if they work now. In any case, it is known that the force barriers are impenetrable by aliens.}
{219}{}{}

{220}{}{"A memo with a suggestion"}
{221}{}{"Acts of project completion"}
{222}{}{"A report on the work performed"}
{223}{}{"Service passwords"}

{224}{}{As it turned out, scientists were pretty worried by the incident in the winter of 2077, when one of the aliens got loose. They made a decision to develop a powerful protection system for the time of experimentation. The key points in this system were a force fields and a gas protection. Deadly gas, that should have been used in extreme cases, was to be distributed throughout the whole levels, including the top of the hangar, through the vent. The management considered this decision reasonable, but very dangerous, therefore, requiring a multi-stage system of turning it.}
{225}{}{According to the documents, all necessary works were successfully completed and tested. The gas device is in the surveillance room (the room to the south of lab). And, apparently, it wasn't in use yet.}
{226}{}{Report consistently describes the full technical and service regulations of the gas device usage. So, the installation is located in surveillance rooms, the password is required to turn it on. Also, all three gas canisters must be full and mounted.}
{227}{}{[More]}
{228}{}{Gas canisters are kept in three different areas of the base: one in the staff room on the ground level of the hangar, the other one in the barracks in A2 sector, and the third is in the laboratory. Canisters are stored in special safes, locked by passwords. Passwords are given to certain individuals by personal orders.}
{229}{}{After connecting the canisters, a very strong gas is released to the ventilation system. It reacts with acid in the circulatory system of the aliens and they literally get slimed into biomass. The gas also has the devastating effect on humans, forcing them to painfully die in several minutes. Therefore, the use of gas attack must be considered and agreed by all... Blah-blah-blah. The rest is not interesting.}
{230}{}{Passwords from gas stations and safes. First: 153-648-987. Second: 045-896-509. Third: 987-469-876. Fourth: 013-486-498.}

{231}{}{"The order of evaluational procedures"}
{232}{}{"A report on the prototype's development"}
{233}{}{"Prototype's test report"}
{234}{}{"The order on relocation of a pulse phasing device"}

{235}{}{Upon the initiative of the department of scientific research, the order on the development of the "Ghost" project was executed, which included the creation of special corset, engaged in the shielding of the infrared spectrum around the carrier. A similar pattern would make the wearers invisible to the aliens and some automated systems.}
{236}{}{Report on completion of the work on the F-31 prototype of the "Ghost" series. That is, there was quite a lot of versions - unfortunately, unsuccessful. The work took several months. The only thing left was only large-scale testing.}
{237}{}{Laboratory testing of the "Ghost F-31", gave positive results. However, field tests did not show a sufficient effect, as device was able to completely isolate the heat waves of only a small creature - like a dog, for example. The summary: "Ghost F-31" needs to undergo additional work on increasing polarization of the central cylinder. And it can be done only with special pulse phasing device.}
{238}{}{According to the order, the technical sector received order to prepare for the delivery of a pulse phasing device, which was supposed to arrive from Hawthorne to Area 51. However, the act of receiving is not present, which can only mean one thing - the package didn't reach its destination.}
