{100}{}{You see a lab computer.}
{101}{}{You see a lab computer. It's in working condition.}

#После взлома, изучение архивов:
{200}{}{Access granted. You are in the main menu. From here it is possible to browse through archive reports and calculations for various projects.}
{201}{}{See the documentation.}
{202}{}{Select a category.}
{203}{}{[Exit]}

{204}{}{Reports on "aliens" experimentations.}
{205}{}{Documentation on the gas protection system.}
{206}{}{Documentation for the "Ghost F-31" project.}
{207}{}{[Back]}
{208}{}{Select a document to read.}

{209}{}{"Experimentation reports for the last five quarters"}
{210}{}{"Report about the weaknesses of aliens"}
{211}{}{"Report on thermal vision of aliens"}
{212}{}{"Winter 2077 incident report"}
{213}{}{"The order to enhance the security level"}

{214}{}{The aliens were humiliated to the fullest. They were tested every week with various kinds of physical and biological impact. As it turned out, the aliens are strong animals with enormous military potential: one of them can take out an entire squad. Scientists tried to tame them for later use as living weapons. However, although their combat potential was never in doubt, the taming part failed.}
{215}{}{They seem to have no known weaknesses. The only kind of damage that turned out to be better than the others is fire. The only thing that is at least somewhat reassuring is that these creatures require special conditions to reproduce: high levels of radiation, a heated, humid environment, and no light. In addition, females of this species are born one in a thousand, so the probability of reproduction is extremely low, and, sooner or later, the species will die out. Sounds good, except that the life cycle of aliens lasts more than 70 years.}
{216}{}{This explains why aliens encounter the wastelands usually in darkness: they see with thermal vision, orienting themselves to the speed of their prey. During the day, they hibernate, as the heated environment interferes with thermal vision, making it harder for the aliens to navigate. With this information in mind, researchers set out to develop a unique piece of equipment - a corset that could conceal a person's heat.}
{217}{}{In the winter of 2077 there was an incident in the laboratory when, due to the negligence of the staff, an experiment on an alien female went out of control. The subject slipped out into the corridor. Apparently these creatures are not stupid, as the mutant quickly assessed the situation and escaped through the vents into the desert. The military found traces in the caves in Sector C, but did not risk the soldiers and blew up all the exits. Six months later, the creature resurfaced again.}
{218}{}{The order to implement the force field system came after an incident in the winter of 2077. The military tried to maximize protection against the test subjects. Apparently, they realized how much they had underestimated the aliens' capabilities. Sector A5 commanders, along with the maintenance department, supervised the further process. There may be some information on the first level about what happened to the forcefields and whether they are working now. In any case, the force fields are known to be impenetrable to aliens.}
{219}{}{}

{220}{}{"A memo with a suggestion"}
{221}{}{"Acts of project completion"}
{222}{}{"A report on the work performed"}
{223}{}{"Service passwords"}

{224}{}{As it turned out, scientists were very concerned about an incident in the winter of 2077, when one of the aliens got loose. It was decided to develop a powerful protection system for the duration of the experiments. Key points in this system were force fields and gas protection. Lethal gas, which was to be used only in extreme cases, could be spread throughout all levels, including the upper part of the hangar, through the ventilation system. Management thought this solution was reasonable but very dangerous, so a multi-stage launch system was installed.}
{225}{}{According to the documents, all the necessary work has been successfully completed, as have the tests. The gas device is in the observation room, south of the lab. And, apparently, it has not yet been used.}
{226}{}{The report consistently describes the technical process and service rules for the use of the gas device. The distribution unit is located in the observation room, and a password is required to turn it on. In addition, all three gas cylinders must be installed.}
{227}{}{[More]}
{228}{}{Gas canisters are kept in three different areas of the base: one in the staff room on the ground level of the hangar, the other one in the barracks in A2 sector, and the third is in the laboratory. Canisters are stored in special safes, locked by passwords. Passwords are given to certain individuals by personal orders.}
{229}{}{After connecting the canisters, a very strong gas is released to the ventilation system. It reacts with acid in the circulatory system of the aliens and they literally get slimed into biomass. The gas also has the devastating effect on humans, forcing them to die in agony within minutes. Therefore, the use of gas attack must be considered and approved by every... Blah-blah-blah. The rest is boring.}
{230}{}{Passwords from gas stations and safes. First: 153-648-987. Second: 045-896-509. Third: 987-469-876. Fourth: 013-486-498.}

{231}{}{"Order on evaluation procedures"}
{232}{}{"Prototype development report"}
{233}{}{"Prototype test report"}
{234}{}{"The order on relocation of a pulse phasing device"}

{235}{}{The Scientific Research Department initiated the "Ghost" project, which involved the creation of a special corset to shield the infrared spectrum around the wearer. Such a model would have made the wearers invisible to aliens and some automated systems.}
{236}{}{Completion report on the F-31 "Ghost" series prototype. That is, there were quite a few versions - unfortunately, unsuccessful. The work took several months. All that was left was large-scale testing.}
{237}{}{Laboratory tests of the "Ghost F-31" gave positive results. However, field testing did not show a sufficient effect, as the device was able to completely isolate only the heat waves of a small creature - a dog, for example. Summary: "Ghost F-31" needs additional work to increase the polarization of the central cylinder. And this can only be done with a special pulse phasing device.}
{238}{}{According to the order, the technical sector was ordered to prepare for the delivery of the impulse phasing device, which was to arrive from Hawthorne to Area 51. However, there is no acceptance report, which can only mean one thing: the package did not reach its destination.}
