{100}{}{You see a computer.}
{101}{}{You see a usual office computer. The only thing that separates it from the rest is that it still works.}

#Типовые фразы:
{110}{}{The system is ready to work. Enter the following command.}
{111}{}{[End log]}

{113}{}{[Back]}
{114}{}{[Back to the list]}
{115}{}{The next note.}

#Список служебок:
{120}{}{Look at list of notes.}
{121}{}{Look at area schemes of the hangar.}

{122}{}{Reports on malfunctions in the turret control program.}
{123}{}{Reports on errors in the force fields functionality.}
{124}{}{Look for any mention of Vault 8.}

#Схемы помещений:
{130}{}{It turns out that the hangar stretches on many floors down. Some floors cannot be viewed due to the lack of access rights. Almost every floor is a laboratory or technical workshop. Apparently, the local military had very dense schedule.}
{131}{}{Watch the first underground floor.}
{132}{}{The first underground floor is also a large laboratory. In addition, the control center of external defence line is located there (apparently, we are talking about the turrets and security cameras), along with emergency generator and control systems of force fields and outer ventilation. You fail to get access lower than the first underground level because of the strict security regulations.}
#Служебки:
{140}{}{Memos for the last available month have been sorted by topic. They are mostly usual production and nutrition reports, but you see a few interesting notes.}
{141}{}{Select a note to read.}

{142}{}{"About an error in the turrets control program"}
{143}{}{"Proposal to install a SoS kit"}
{144}{}{"Receipt of delivery of the SoS kit"}
{145}{}{"Report on SoS kit installation"}

{146}{}{Notification from the employee of security service, which tells about some error in the control program of turrets. The program regularly glitched, which, in turn, led to frequent reboots. Every restart turned turrets off for a time period of 10 to 20 seconds. Despite the attempts to fix the program, engineers were unable to solve the issue. By their point of view, the blame was on the experiments at the hangar's lower levels, resulting in a strong electromagnetic waves.}
{147}{}{The main proposition of some security employee is to install more advanced System of Security kit in place of the control turrets program. This would fix the problem of restarts and significantly improve the effectiveness of the hangar's protection systems. The response memo indicates approve of this. You are not sure, but looks like system like this is used in your Vault.}
{148}{}{As listed on the receipt, the employee of security service has received complete and working SoS kit. The kit was brought from Hawthorne after field tests, then further upgraded by local engineers, based on the reports from these tests. The security service ordered to connect the kit to the security systems and see if it works as intended.}
{149}{}{As listed in the report, the installation of SoS kit from Hawthorne did not produce expected results. The kit, for an unknown reason, didn't work. The manufacturer sent a statement about the need to retest the kit, but no response was given. Apparently, the military had no time to continue due to the outbreak of Great War. In the end, the hangar was left without any external protection - turrets were temporarily disabled.}
{150}{}{"Order for routine testing of force fields"}
{151}{}{"A proposal to tighten control over force fields"}
{152}{}{"A notification about the start of force fields reprogramming procedure"}

{153}{}{An order on carrying out systematic routine inspection of the force fields. The inspector must inform the head of security and management of the laboratories about each case of malfunction.}
{154}{}{Department of the security service proposes to put into use personal key cards for controlling force fields separately. In the current state any worker with the average level of access could enable or disable all of them, which is, obviously, doesn't meet the security standards. The command gave order to reprogram the force fields and to produce sets of magnetic key cards with high encryption level. The order was directed to the maintenance sector, leading to correction on operating mode of force fields.}
{155}{}{The maintenance sector's worker informs that the force field will be temporarily disabled due to reprogramming. Downtime is up to three days.}
{156}{}{"A report on the results of force fields reprogramming"}
{157}{}{Maintenance sector reports on positive results of the reprogramming of force fields. The list of all personnel provided with magnetic key cards is prepared. Also, new operating mode is enabled for the force fields.}
{158}{}{A notification about regime of work of the force fields"}
{159}{}{Maintenance sector reports on enabling enhanced operating mode of force fields. In particular, it is said that due to the strong usage factor for equipment generating the force fields, a periodic 2 hour shutdowns are implemented. In the absence of control inspection procedure, which should be conducted every 60 days and recorded in the computer on the first underground level, the force fields will be automatically shut down for fire safety purposes, until forced turning (i.e. until the next control check).}

{160}{}{Read the order 1123.}
{161}{}{Summarize data about the project Vault 8.}
{162}{}{Information is scarce and scattered, but each document is marked by a special mark "Project Vault 8".}
{163}{}{The order is about organizing transitional surveillance point for monitoring Vault 8. The station itself did not store any data - only relayed it to the upper link in chain: Hawthorne military base. Further, processed data in the form of reports was transmitted to Area 51.}
{164}{}{Although the vaults network was not in the Area 51's responsibility, the vault 8 became an exception. The reason for this was assigned to the vault status of the governmental facility. In an emergency situation Area 51 should have contributed to the protection of the vault, but not intervene in internal affairs. There was even some initiative to set force field barrier around the territory, but the time and funding were not enough, since the project already had too many resources allocated to it. The vault's security functions by default were assigned to Hawthorne military base, however, in case of its inability to perform such functions, the task should have been passed to Area 51.}
