{100}{}{You see a computer.}
{101}{}{You see a communication operator computer with a fairly unique interface.}

{103}{}{You learned about the existence of a large radio station halfway between Reno and Vault 8.}

#После включения
{110}{}{Welcome to the operating system of the communication terminal.}

{111}{}{Download a list of points of radio communication.}
{112}{}{Download the broadcasts report.}
{121}{}{[Exit]}

{122}{}{The list of stations is loaded.}
{123}{}{Sort the list by status.}
{124}{}{Sort the list by location in the state of Nevada.}
{125}{}{Sort by date of radio broadcasts.}
{126}{}{[Back]}

{127}{}{Done. [You have noticed that the status of military-government stations is assigned to only a few units in Nevada. And they are located in remote places - in the heart of the deserts, in the mountains, etc. - where the greatest coverage is provided, and the station itself is quite difficult to locate.]}
{128}{}{Apparently, these points of radio communication were very important for the military.}
{129}{}{There are quite a few communication points in the state, but one of the military-government stations is located southeast of your vault, near the prewar town of Lovelock (probably only ruins there now).}
{130}{}{The last sessions were carried out... A couple of years ago! More precisely, someone outside of the state tried to send a signal to Area 51, but, apparently, no one responded. However, it could be some automated message. The source of the signal is encrypted.}

{131}{}{Report loaded.}
{132}{}{Study the content.}
{133}{}{(Until the last days before the great War, reports had been pretty sparse. Shortly before the War, the number of broadcasts has increased dramatically. They were mostly between military headquarters and field labs, with strong encryption. It seems pretty suspicious to you. Did the elites know of the impending war, and even its timing? Curiously, some broadcasting happened *after* the war. However, it could be some automated message.)}
{134}{}{Check the last broadcast.}
{135}{}{In addition to the standard automation procedures, someone, using this terminal, had been tracking a variable source of the radio signal. After a little digging in the parameter values, you suddenly find out that this point is... You. Looks like someone watched your movements, thanks to a bug planted into your Pip-Boy.}
{136}{}{What a surprise...}

{137}{}{There are quite a few communication points in the state, but one of the military-government stations is located southeast of your vault, near the prewar town of Lovelock. It seems it's in the same place where the village of Cheyenne is located. Maybe it's worth asking the locals about it.}
