{100}{}{Force-field generator.}
{101}{}{You see a force-field generator.}

{110}{}{The force-field inflicts heavy damage.}

#Просто поюзать (рука, предметы,скиллы):
{111}{}{Access denied.}
{112}{}{The force-field will not turn on unless you have highest level access.}
{113}{}{This does nothing.}
{114}{}{No use.}
{115}{}{A different approach is needed.}

#Включение и выключение поля:
{116}{}{You switch off the force-field.}
{117}{}{You switch on the force-field.}
{118}{}{Done}

#Взлом системы защиты:
{120}{}{You fail to bypass the protection.}
{121}{}{Fail.}

{122}{}{You successfully hack this complicated electronic mechanism and force-field reappears.}
{123}{}{You successfully hack this complicated electronic mechanism and force-field disappears.}
{124}{}{Done!}
