{100}{}{You enter a vast area where military planes used to land. You can see some buildings to the west.}
{101}{}{You are trespassing on federal property. Before the war you would have been shot for that.}
{102}{}{You've entered some kind of special hangar. Maybe you are gazing upon something seen only by few.}
{103}{}{A violent explosion rips the hangar's insides apart. The structure itself, however, miraculously doesn't cave in.}
{104}{}{Goddammit!!!}

{105}{}{This place looks like an aircraft refuelling station. There must be some aviation fuel left in those tanks.}
{106}{}{}
{107}{}{The stench is almost unbearable...}
{108}{}{The poison gas is still present in the hangar air.}