{100}{}{You see a citizen.}
{101}{}{You see a fellow citizen of Vault 8.}
{102}{}{No! Leave me alone! I'm not going out there!}
{103}{}{M-maybe we should just go back down?}
{104}{}{Can't we hurry up and get this over with?!}

{110}{}{I'm not going... I'm not going... I'm not going...}
{111}{}{What's wrong with you? Pull yourself together, we have to go!}
{112}{}{Suit yourself. We'll do just fine without you.}

{113}{}{NO! NO! I'M NOT GOING!!!}
{114}{}{Come on, it's not that scary.}
{115}{}{[Slap his face] Snap out of it, you coward!}
{116}{}{Leave me alone! I... I can't... Why me? Why does it have to be me?}
{117}{}{It's strange that the Overseer assigned you to this job. But we need you, so pull yourself together.}
{118}{}{Ow! Ow, stop! Leave me alone! Why are you doing this to me!}
{119}{}{Whatever you're afraid of out there, you should be more afraid of *me*.}
{120}{}{[He stops whining. He looks afraid, but his eyes are clear] Okay... Okay... I'm fine, really. Just give me a second... I'm ready to go now.}
{121}{}{Good. Follow me.}
{122}{}{How can you be so calm? The Overseer always told us it's forbidden to go out there. What's going to happen to us? Why is this happening now? Why does it have to be me?!}
{123}{}{I don't know why you were chosen, but we can't go without you. If we're quick and careful, everything will be fine. You'll have me, doctor Moreau and an armed guard by your side. You have nothing to worry about.}
{124}{}{Really? Will you keep me safe? [he grabs you by the suit] Please, just don't leave me... I'm so scared...}
{125}{}{Don't be. I'm here.}
