{100}{}{You see a vault security guard.}
{101}{}{You see a member of the Vault 8 security forces.}
{102}{}{Move, move, move!}

#Первый диалог
{110}{}{Greetings, citizen. I'm the team's security detail for this mission. The rest is waiting for you in the medical bay. Let me know when they're ready.}
{111}{}{Right...}
{112}{}{One more thing: take these flares. They can come in handy if there's too dark outside. Turn around the upper part to light one up.}
{113}{}{Okay.}

{114}{}{What's the order?}
{115}{}{What do you know about our mission?}
{116}{}{Aren't you afraid to go outside?}
{117}{}{Do I get anything to defend myself?}
{118}{}{Follow me, we're ready to start the mission.}
{119}{}{Wait here. I’ll go get our team ready.}

{120}{}{Doctor Richard Moreau is supervising the operation, he will brief you. I'm only providing security.}
{121}{}{No. I've spent years training for this. I was taught to suppress my fears of outside world. This team can count on me.}
{122}{}{No. Vault security regulations forbid any citizens besides the Overseer and security personnel from carrying weapons. But don't worry, I'll keep you safe.}
{123}{}{Affirmative. When the team is ready, use the terminal to open the door.}
{124}{}{Got it.}

#На поверхности
{150}{}{[Ignores you and watches for potental threats.]}
{151}{}{[Leave him]}
{152}{}{Do you know where the monitors are located?}
{153}{}{No. Doctor Moreau should have marked the locations on your map scanner. Stay focused!}
{154}{}{Fine.}

{160}{}{He's dead! [his head snaps back and forth, peering into the darkness] What happened? Where is doctor Moreau?!... It doesn't matter now. Get back into the vault!}
{161}{}{What about Dr. Moreau?}
{162}{}{Move, citizen! You have the data. This mission is over!}
{163}{}{We can't leave without doctor Moreau! He might still be somewhere around...}
{164}{}{[His eyes flare. He grits his teeth] I said MOVE! Doctor Moreau is gone. Get into the vault, NOW!}
{165}{}{No, Sergeant. Take the holodisk and return. I'm going after Dr. Moreau.}
{166}{}{You're right, Sergeant. We've got to get out of here! Let's go!}
{167}{}{Citizen! [he points his weapon at you] Don't you dare to go out there! Get into the vault right now, that's an order!}
{168}{}{[Turn around and start walking away]}
{169}{}{Yes, Sergeant, you're right. We have to leave Dr. Moreau. Let's go back!}
{170}{}{Citizen! Citizen, stop! [pause] Stop or I'll fire! [after a few seconds of silence, you hear footsteps accelerating toward the vault]}
{171}{}{Goodbye, Sergeant. This is where our paths diverge...}