{100}{}{You see a control panel.}
{101}{}{It is a door control panel. The door is controlled from here.}
{102}{}{The security system allows only one surface access door to be opened at a time.}
{103}{}{You cannot do that in combat!}
{104}{}{The door is already open.}
{105}{}{Wait, where is your holodisk?!}
{106}{}{You must gather your party before venturing forth.}
{107}{}{The Overseer won't open the vault door until you complete your mission.}
{108}{}{You must wait for your team.}
