{100}{}{You see Moreau.}
{101}{}{You see Richard Moreau, head doctor of Vault 8.}
{102}{}{Hurry up with the data, we'll talk later.}

{110}{}{[You see Dr. Moreau. He looks angry.] Finally. I was thinking about sending a guard after you.}
{111}{}{That's not necessary. Why are you so worked up?}
{112}{}{What?... Forget it. To the task at hand: you already know we're going outside. I can't tell you exactly what's waiting for us beyond the main gate, so prepare for the worst. If we act according to plan, everything should go smoothly.}
{113}{}{What's our mission?}
{114}{}{We recently stopped getting information from our surface surveillance monitors. But they still should record data to the local backup. Your job is to get the data from the monitors, if that is possible.}
{115}{}{How would I do that?}
{116}{}{Take this empty holodisk. Each monitor has a slot on them, just plug the disk in and press "copy". The monitor will take care of the rest - if it still works, of course. Now, give me your sensor. I'll mark the positions of the monitors on your map, so it would be easier for you to find them.}
{117}{}{Okay, doctor Moreau, we're good to go. Follow me.}
{118}{}{Understood. I'll tell you when we're ready to leave.}
{119}{}{Yes?}

{120}{}{When the team is ready, type the activation code into the access panel. And don't lose the holodisk!}
{121}{}{Fine.}
{122}{}{I'll tell you when we're ready to leave.}

{123}{}{Wait, what are the rest of you going to do?}
{124}{}{I'm responsible for medical assistance in case someone needs it. The guard will provide security. The other citizen will gather surface data with his portable monitor.}
{125}{}{Doctor, are you sure you're alright? You look stressed...}
{126}{}{You'd better keep your mouth shut. The Overseer gave you an order - that's all you should worry about.}
{127}{}{}
{128}{}{}
{129}{}{Look, I don't want to go! Maybe I'll just go back inside?}
{130}{}{We can't go without you. It's too risky.}
{131}{}{It's too risky to go at all! It can't be a coincidence that all the monitors stopped sending data at once. Who knows what's going on out there!?}
{132}{}{Hmm... It might actually be better if you don't go. You could compromise the mission. Go back in the vault. I'll find someone to replace you.}
{133}{}{Whew, thank you. You just saved my ass... [Abandon your mission]}
{134}{}{No... No, wait. I think I just needed to let that out. I'll go, I can do it. You can count on me.}
