{100}{}{You see a landslide.}
{101}{}{Before you lies a pile of heavy rocks that have fallen from above. It would be too dangerous to climb over them. You have to find a way to throw them down.}
{102}{}{These rocks are too heavy to move with bare hands. You'll need some kind of lever.}

{110}{}{Your set the lever and strain. You manage to roll the smaller boulders a couple of feet, before your arms give out.}
{111}{}{*Hn-ngg...*}
{112}{}{You throw your body weight onto the lever and shift some medium-sized rocks. You've almost cleared enough space to pass.}
{113}{}{*HH-HHRGG!*}
{114}{}{Using the sign as an Archimedes' lever, you slowly shift the largest boulders until they roll over the edge, crashing onto the ledge below. The passage is clear.}
{115}{}{Whew!}