{100}{}{You see: Sergeant Stark.}
{101}{}{You see Sergeant Stark, the head of the south patrolling sector.}

#Íà÷àëî äèàëîãà
{110}{}{Yes, citizen }
{111}{}{Yes, citizen }
{112}{}{? Looking for something to do?}
{113}{}{I'll think about it. Take care.}

#Âûõîä èç äèàëîãà
{120}{}{Long live Vault City!}
{121}{}{Yeah, uh, long live Vault City, officer!}
{122}{}{If you say so, officer.}

#Î ïàòðóëÿõ
{200}{}{Excuse me, but what are you doing here?}

{201}{}{I command the south sector patrols. But right now, I'm off duty.}
{202}{}{What can you tell me about the patrols?}
{203}{}{Can you tell me anything about the south sector?}
{204}{}{Have you ever met any outsiders?}
{205}{}{How do you deal with outsiders?}
{206}{}{}
{207}{}{}
{208}{}{I have another question.}
{209}{}{Thanks, that will be all.}

{210}{}{The patrols keep watch on the local area. The mountains make it easy for us to see and not be seen. Anything we find, we record in our databases.}
{211}{}{It's mostly uninhabitable, so outsiders or wild animals are rare. We know of two settlements, Gerlach and Black Rock, but I can't tell you much about them. We've always kept our distance.}
{212}{}{Of course! Most of them are psychos. Stay away from anyone in the wastes. Only talk to people in communities - they're usually safer and more civilized.}
{213}{}{We keep them away from the city. Usually we just keep tabs on where they're going, but if necessary we'll stop them and turn them around. With our weapons and armor not many try to argue. The rest can be scared off with a few warning shots.}

{214}{}{Can you show me where Gerlach is on the map?}
{215}{}{Hmm... I have another proposition, if you're interested.}
{216}{}{Understood.}
{217}{}{Oh yeah, I almost forgot. Our patrols know of your mission, so if you meet them outside you can ask for medical help or safe escort.}
{218}{}{How can I help?}
{219}{}{You already know where it is. It's to the south.}
{220}{}{Can I help you in any way?}
{221}{}{Do you have any assignments for me?}

{222}{}{It sounds like an important job. Not as important as mine, though.}
{223}{}{If you want to think that, that's your problem. Our city needs patrols to keep outsiders from finding us. We both keep Vault City safe. Isn't that enough?}
{224}{}{}
{225}{}{}
{226}{}{}
{227}{}{}
{228}{}{}

#Î Ãàðîëüäå
{230}{}{Have you seen that green man in the cell?}
{231}{}{That walking corpse? When we captured him, he was driving a caravan. I've never seen anything so disgusting. If that's what the wastes are turning into, then we'd better be more careful with outsiders.}
{232}{}{Right.}

{250}{}{Can you give me any advice for surviving the wastes?}
{251}{}{My best piece of advice is to stay away from the highways. It might take longer, going off-road, but it'll be safer. Less chance of meeting outsiders that way.}
{252}{}{Well, it's better than nothing, so thanks.}

#Èññëåäîâàíèå Äæåðëàêà
{300}{}{We need someone that can get intelligence on Gerlach without raising suspicion. You're just the right one for the job.}
{301}{}{Go to Gerlach and come back? No problem!}
{302}{}{No, you'll have to do that without me.}

{303}{}{No, not just "go to Gerlach". We need detailed information on their community. Social structure, laws, problems - a full picture of our neighbors.}
{304}{}{Got it. I'll learn everything I can.}
{305}{}{No, do it without me.}

{306}{}{Good! I'll mark it on your map. We're looking forward to your report!}
{307}{}{Consider it done!}

{308}{}{About Gerlach... }
{309}{}{What do you know about Gerlach?}
{310}{}{It's one of the two communities we know of. We've always kept our distance, so I can't tell you anything useful.}
{311}{}{Maybe I can get there?}
{312}{}{You can't help me, then.}
{313}{}{I've just returned from there.}

{314}{}{You've been there? Did you learn anything useful?}
{315}{}{They're savages, they'll slit each other throats over an argument!}
{316}{}{They're a strong-willed community with strict laws.}
{317}{}{I'm afraid, no. I'll tell if I learn anything.}

#Îòðàâëåíèå Äæåðëàêà
{318}{}{Can't say I'm surprised. We can't allow such wild and miserable brutes near our city! We need to... Take care of them, for our own safety.}
{319}{}{But how?}
{320}{}{I don't want to be a part of this.}

{321}{}{I've been there already. I'll tell you everything I know.}
{322}{}{Thank you citizen, that's very useful! We mostly need information on their social structure - what kind of people they are, what they want, how they treat themselves and others.}
{323}{}{Sorry, I can't give you that kind of information yet.}

{324}{}{You said the town has just the one water tank? By poisoning it, we can kill everybody in town. This poison, of course, will be provided to you.}
{325}{}{Sounds like a good plan!}
{326}{}{That might not work - the community's water pump isn't working.}
{327}{}{No way! This is genocide!}

{328}{}{No problem. We'll give you everything you need.}
{329}{}{[Wait]}

{330}{}{We are looking forward for your report, citizen! Long live Vault City!}
{331}{}{Uh, yeah... Long live Vault City.}

{332}{}{You've been there, you tell me.}
{333}{}{Then we'll have to watch them more closely.}

{334}{}{Is it done?}
{335}{}{I refuse to do this!}
{336}{}{Yes, I poisoned their water supply. They're dead.}
{337}{}{No, not yet.}

{338}{}{[Looks disappointed] I understand, it's not easy. Well, we'll find someone. You can go now... Citizen.}
{339}{}{[Leave]}

{340}{}{[Looks pleased] I knew you had the stomach for it. You really are something special, just as the Overseer said. We're all grateful to you.}
{341}{}{[Leave]}

{342}{}{The outsiders are a good workforce. We're still trying to find a way to fit them into our society, but I'm sure we'll get them working soon enough.}
{343}{}{It is done, for once and for all. Vault City can sleep safely at night.}
{344}{}{It is done. Let's hope that's the last we hear about them.}

#Ïåðåñåëåíèå Äæåðëàêà
{350}{}{Really? Hmm... Now that I think about it, that's not so surprising. They try to live as a small, tight-knit community. Maybe that's why they left big cities. Maybe we should get acquainted more closely.}
{351}{}{More closely? What do you mean?}
{352}{}{I'll let you handle that without me.}

{353}{}{Please understand - to keep Vault City going, we have to risk our citizens doing dangerous tasks, such as decontaminating radioactive areas. We need an external workforce, so we don't have to risk our own citizens.}
{354}{}{Slaves? Are you serious?!}
{355}{}{Hired workers? This makes sense!}
{356}{}{I don't want to hear about this. Do it without me.}
{357}{}{We're not bandits, citizen. We're talking about mutual benefit: we give them food, shelter, and medicine, and in exchange they give us free labor for life. It's a fair deal, don't you think?}
{358}{}{That's right. Everybody wins: we give them food, shelter, and medicine, and in exchange they give us free labor for life. It's a fair deal, don't you think?} 
{359}{}{Yes, it's fair, if the slaves... Er, hired workers are given the same rights as citizens.}
{360}{}{No, I don't! This is slavery and a disgrace to our city! I'm out of here!}

{361}{}{I'm glad to hear that. We've discussed this with the committee, but they haven't made a decision yet. Now we have you. Give Gerlach our proposal, but don't tell them our location until you make the deal.}
{362}{}{I'm happy to help the city! I'll do it!}
{363}{}{No, I won't do this.}

{364}{}{I hope this isn't a mistake. Good luck! And long live Vault City!}
{365}{}{Yeah... Long live!}

{366}{}{Did you tell them our offer?}
{367}{}{I'm not going to do this. Find someone else.}
{368}{}{Yes, they were happy to accept. They're waiting to start.}
{369}{}{Not yet. I'm working on it.}

{370}{}{So be it. In time, I hope we'll find someone to replace you. Now get out.}
{371}{}{[Leave]}
{372}{}{Excellent news! I'll send a team as soon as possible. Vault City owes you a great debt, citizen!}
{373}{}{[Leave]}

{374}{}{You've decided the fate of the entire community.}

{375}{}{We'll have to fix Gerlach's water pump before they trust us.}
{376}{}{No problem. I'll put in a request with the warehouse right now.}
{377}{}{Excellent!}

#Female character:
{1313}{}{I've just returned from there.}
{1321}{}{I've been there already. I'll tell you everything I know.}
{1322}{}{Thank you citizen, that's very useful! We mostly need information on their social structure - what kind of people they are, what they want, how they treat themselves and others.}
{1327}{}{No way! This is genocide!}
{1330}{}{We are looking forward for your report, citizen! Long live Vault City!}
{1338}{}{(looks disappointed) I understand, it's not easy. Well, we'll find someone. You can go now... Citizen.}
{1340}{}{(looks pleased) I knew you had the stomach for it. You really are something special, just as the Overseer said. We're all grateful to you.}
{1357}{}{We're not bandits, citizen. We're talking about mutual benefit: we give them food, shelter, and medicine, and in exchange they give us free labor for life. It's a fair deal, don't you think?}
{1358}{}{That's right. Everybody wins: we give them food, shelter, and medicine, and in exchange they give us free labor for life. It's a fair deal, don't you think?}
{1360}{}{No, I don't! This is slavery and a disgrace to our city! I'm out of here!}
{1362}{}{I'm happy to help the city! I'll do it!}
