{100}{}{You see: a citizen of Vault 8.}
{101}{}{You see: a citizen of Vault 8.}
{102}{}{You see: your fellow citizens.}

#Плавающие сообщения при враждебности:
{103}{}{ }
{104}{}{ }
{105}{}{ }
{106}{}{ }
{107}{}{ }
{108}{}{ }
{109}{}{ }

#Диалог:
{110}{}{Long live Vault City, citizen!}
{111}{}{It's a fine day, isn't it, citizen?}
{112}{}{Where can I get some more gear?}
{113}{}{Do you know anything about the outside world?}
{114}{}{Did you see that freak in the security cell?}
{115}{}{Want to go for a walk in the wilderness?}
{116}{}{It was nice seeing you. I have to go.}

{117}{}{Right, citizen!}
{118}{}{Can I ask you another question?}
{119}{}{Thanks. Take care.}
{120}{}{Yes, citizen?}
{121}{}{Uh... Talk to Sam in the warehouse. You'll have to make a request and wait until it's processed... Which usually doesn't happen until it's not needed anymore.}
{122}{}{Me? No, nothing! Common citizens like me aren't allowed outside.}
{123}{}{I can't wait until he's thrown out of the city. I hope he isn't contagious... And the guards took all the necessary precautions.}
{124}{}{We're not allowed outside of the city. It's dangerous.}

{125}{}{Did you see that freak in the cell?}

#Приветствие Сэма (только для блуждающих граждан)
{165}{}{How it's going, Sam?}
{166}{}{How's my order for those transistors coming along, Sam?}
{167}{}{Sam, how much longer before request gets processed?!}
{168}{}{Sam, do you have... What, no? What a surprise.}
{169}{}{Sam, do you have a three-step transformer?}

#Приветствие начальника охраны (только для блуждающих граждан)
{170}{}{Sergeant Graves, are we in any danger from raiders?}
{171}{}{Sergeant Graves, you're looking very... Bulletproof today!}
{172}{}{Sergeant Graves, tell me, how did you get outside of the vault for the first time?}
{173}{}{Sergeant Graves, I see you've tightened up city's security!}
{174}{}{Sergeant Graves, our hero! I'm happy to see you!}
{175}{}{Long live Vault City, Sergeant Graves!}

#Приветствие Джошуа (только для блуждающих граждан)
{180}{}{Joshua, is there any radiation in the city?}
{181}{}{Joshua, did you find anything interesting?}
{182}{}{Joshua, did you investigate ruins to the west?}

{204}{}{Oh no! Please don't do that!}

#Female character
{1110}{}{Long live Vault City, citizen!}
{1111}{}{It's a fine day, isn't it, citizen?}
{1117}{}{Right, citizen!}
{1120}{}{Yes, citizen?}
