{100}{}{You see: a citizen.}
{101}{}{You see a citizen watching a darts game.}
{102}{}{ }
{103}{}{Long live Vault City!}
{104}{}{Come on, you can do it!}
{105}{}{Your throwing skill has increased by 5%.}

#Перед соревнованием
{110}{}{Hello, citizen. Nice weather today, isn't it?}
{111}{}{What are you doing?}
{112}{}{I have to go. Bye.}

{113}{}{Just throwing darts. We were told to find something to do in our free time, so we're doing something fun.}
{114}{}{How do you play this game?}
{115}{}{It looks interesting, can I try?}
{116}{}{Okay, I'll leave you to it then.}

{117}{}{The target is divided into circles worth a different number of points. Each player throws five darts and adds up their score based on the circles they hit. The one with the highest score wins.}
{118}{}{Sure.}
{119}{}{I'm ready to begin.}
{120}{}{Later then.}

{121}{}{Okay. Here's five darts. Aim and throw. Just don't move from the set position, or you'll be disqualified!}
{122}{}{Well then, let's begin...}
{123}{}{Moving from your preset position is against the rules of the game.}

#Конец соревнования
{150}{}{}
{151}{}{}
{152}{}{ points out of 50. You'll get better with practice. I can give you some pointers, if you want.}
{153}{}{Yes! Teach me, how to throw darts better!}
{154}{}{No, thanks. I'll figure it out on my own.}

{155}{}{ points out of 50. That's, uh... Really bad. Maybe it's just not your day. But I can't give you any more darts.}
{156}{}{Well up yours, buddy! Who wants to throw some stupid darts at some stupid circles, anyway!}
{157}{}{Yeah, it's just not my day.}

{158}{}{ points out of 50! You're a natural! I haven't seen throwing like in a long time. You're even better than me!}
{159}{}{Hey, thanks! That was pretty fun!}
{160}{}{}

{161}{}{[You take turns throwing darts, as he gives you advice] Now, you see what you've been doing wrong?}
{162}{}{Yes, I do. Thanks for the lesson, citizen!}
{163}{}{You're welcome. Long live Vault City!}
{164}{}{Er... Yeah, sure.}

{173}{}{No, that's not fair. Rules are rules. You lost, deal with it.}
{174}{}{[Exit]}

#Female character
{1110}{}{Hello, citizen. Nice weather today, isn't it?}
