{100}{}{You see: citizen Jeremy.}
{101}{}{You see: citizen Jesse.}
{102}{}{You see Jeremy, the medical bay nurse.}
{103}{}{You see Jesse, the medical bay nurse.}
{104}{}{Please, don't!}
{105}{}{I'm glad to see you!}
{106}{}{I'm glad to see you!}

#Первый диалог

{110}{}{[You see a cute, quiet girl] Oh, it's you... It's so nice to see you. So many people are afraid to go outside, but not you, you're so...}
{111}{}{What are you doing here?}
{112}{}{Aren't you sick of this tiny vault already?}
{113}{}{It's simple! Go outside, get some fresh air.}
{114}{}{I'll leave you to your work.}

{115}{}{Me? Oh, don't mind me. I just keep the place clean. Dr. Willmouth himself asked me to.}
{116}{}{Oh, no! Everything is so familiar in here, I have thick walls and familiar people. As for outside, I - I'm afraid to even think about it.}

{117}{}{It's simple for you. You're so strong and brave. And me, people like me... Oh, never mind, forget it.}
{118}{}{No, wait. You're just afraid to go into the wastes, right?}
{119}{}{Pfft, what are you afraid of - the wastes? Ha-ha-ha-ha!}
{120}{}{Yeah, good luck to you... Thank you for not being a stranger. Come around sometime.}
{121}{}{Bye.}

{122}{}{I don't go outside... Ever. Not even into the city.}
{123}{}{People like you? What do you mean?}
{124}{}{You've never even left the vault?!}

{125}{}{No, I have, of course, a couple of times. I just... Stood near the exit, looking out into the desert and... I couldn't take the burning sun... The constantly changing sky... And the space! So much open, empty space! It's scary and dangerous! If I could, I'd rather stay in the vault forever.}
{126}{}{Forget your fears, it's better in the city. And it is as safe, as the vault.}
{127}{}{Well, it's your life. It doesn't make a difference to me.}
{128}{}{Fine! Sit here in your little cage until your teeth fall out.}

{129}{}{Oh... I'm sorry... Maybe I'm not an interesting person to talk to. I will leave you alone. Forgive me, please.}
{130}{}{What?...}
{131}{}{Oh yes, yes, of course. You have a lot of important things to do. But I'm still glad I have seen you.}
{132}{}{Good. I'll go then.}
{133}{}{Well, if you say so...}
{134}{}{Come on! Face your fears and go out into the city. Walk on the streets, and then you'll see how amazing the outside world is.}
{135}{}{Fine, I'll try. Thank you for your support.}
{136}{}{Don't mention it. I'll see you around.}

{137}{}{I'm sorry, but... Do I know you?}
{138}{}{Oh, yes, you don't remember anything... I remember how you were dragged here to Doctor Willmouth. He told me you forgot almost everything. I'm sorry.}

#В'орой диалог

{150}{}{I'm glad to see you.}
{151}{}{I recall you were impossible to pull out from the vault. Even by force.}
{152}{}{Yes, thanks to you I'm not afraid to go outside anymore. Thank you so much for this!}
{153}{}{Doctor Willmouth says there's only one way to overcome your fears, and that's to face them. So here I am, trying. Every day I get more used to being outside. Doctor Willmouth is so smart!}
{154}{}{Right. Can you tell me what happened while I was away?}
{155}{}{I... Don't know what to say. I rarely speak to anyone, but... I feel like something isn't right. But maybe it's just my imagination.}
{156}{}{What are you talking about?}
{157}{}{I've heard that people are going missing. Not like you did - they're just... Gone. The Overseer and the guards don't tell us anything. Maybe they just don't want people to panic, but they're supposed to protect us. Keeping us completely in the dark is... Strange.}
{158}{}{Yeah, I think you're right.}
{159}{}{I'm afraid I don't know anything else.}
{160}{}{I'll see you later then.}
{161}{}{Thank you for coming to talk to me!}
{162}{}{Bye.}

#Тре'ий диалог
{200}{}{[You see Jesse. She has a knife in her chest and won't last long. As you get closer, you realize, that she thrust that knife into her chest herself.]}
{201}{}{Don't move! Save your strength!}
{202}{}{[Pushes you away] No! Now I know the truth... I'm just a... A doll, pretending to be human... Why?! I don't want to... Live... With that... [wheezes one final time and goes limp]}
{203}{}{[Leave]}

#Вариан' реплик при игре женщиной (персонаж - мужчина)

#Первый диалог

{1110}{}{[The shy young man smiles at you] Hello, citizen! It's so good to see you. Not everyone is brave enough to leave the vault, but you, you're so... Special...}
{1117}{}{For you, it is simple. You're so strong and brave. And me, people like me...  Oh, never mind, forget it.}
{1124}{}{You've never even left the vault?!}
{1125}{}{No, I have, of course, a couple of times. I just... Stood near the exit, looking out into the desert and... I couldn't take the burning sun... The constantly changing sky... And the space! So much open, empty space! It's terrifying! If I could, I'd rather stay in the vault forever.}
{1129}{}{Oh... I'm sorry... Maybe I'm not interesting person to talk to. I will leave you alone. Forgive me, please.}
{1131}{}{Yes, of course. You have a lot of important things to do. But I'm still happy to see you!}

#В'орой диалог

{1150}{}{I'm glad to see you.}
{1152}{}{Yes, thanks to you I'm not afraid to go outside anymore. Thank you so much for this!}
{1157}{}{I've heard that people are going missing. Not like you did - they're just... Gone. The Overseer and the guards don't tell us anything. Maybe they just don't want people to panic, but they're supposed to protect us. Keeping us completely in the dark is... Strange.}

{1159}{}{I don't know anything else unfortunately.}
{1161}{}{Thank you, for talking to me!}

#Тре'ий диалог
{1200}{}{[You see Jeremy. He's bleeding from several bullet wounds. From the position of his injuries you can tell he let himself be shot on purpose.]}
{1202}{}{[Pushes you away] Leave me... Now I know! I was just a set of... Spare organs... A backup copy... Heh. Well, they won't... Get anything from me now. That's my revenge... [wheezes one final time and goes limp]}
