{100}{}{Oh, my God! A living corpse!}
{101}{}{You see: a ghoul named Harold.}
{102}{}{You see Harold.}

{106}{}{I'll talk to him. See you.}
{107}{}{Hmm. Sergeant Graves says that you're the victim of some special virus.}
{108}{}{Did he figure that out on his own? He's a clever one! [laughs, then coughs] Or maybe he talked that doctor in your vault. You should do that too. He's smart... Smart and cunning.}

#С'ар'овая ве'ка
{109}{}{That's it, I've seen enough. I'm out of here.}
{110}{}{Hey, smoothskin! You ever seen the walking dead before? BOO! Ha-ha-ha! [laughing turns to coughing] Scary, huh? Maybe I should take a couple of bucks for the show.}
{111}{}{No. I'm not scared.}
{112}{}{Is that what passes for a show out in the wastes?}
{113}{}{Eww! I think I'm going to be sick!}

#Ис'ория Гарольда
{114}{}{Heh! Tough guy, huh? Sergeant Friendly out front wasn't scared of me either... Until I told him what's happening out in the wastes, that is.}
{115}{}{You look like you've been around. Who are you?}
{116}{}{Name's Harold, friend. I was a trader once, used to run a caravan to the south. Retired now, though.}
{117}{}{How did you end up here?}
{118}{}{Looking for someplace me and other ghouls could live. We went to Las Vegas, but the locals weren't happy to see us. Then we tried New Reno, but they didn't like us either. A fellow caravaneer told me about a nuclear plant up around here, but I found one of your friendly patrols instead [coughs]. If I hadn't played dead - deader than I already look, I mean, heh-heh - I don't know what they'd have done. Ask your commander. He's the one that put me up in this classy apartment.}
{119}{}{I see. See you later then.}
{120}{}{See you, friend. I'll just be here, mutating... }
{121}{}{Uh... Sure.}

{122}{}{But still - where did you get infected?}
{123}{}{The same place Richard Grey did. He was a doctor in the Hub, when I was still... Smooth, like infant's butt cheeks. I'd known him for, oh... About ten years then. We put together an expedition to find where source was.}
{124}{}{The source? You mean, the source of all the mutated animals? You found it?}
{125}{}{We found something, all right. Wasn't a lot left of us by the time we got inside. [cough] It was just Grey and me, who made it to the core - and then a couple of robotic cranes got the drop on us. Last I saw of Grey, he was falling into some sort of giant acid tank. Me, I passed out... I don't know what happened next. Woke up in the wasteland, and then lookie that - it's not me anymore, but some corpse, ha-ha-ha!}
{126}{}{Robot cranes? Acid tanks? Bullshit, I don't buy it!}
{127}{}{Uh, hold on. When did this happen?}
{128}{}{Oh, this was long ago, friend. I don't even remember where the place was. All I can remember is that it is somewhere in the desert.}
{129}{}{The desert? That narrows it down to a pretty much the whole continent... }
{130}{}{[Laughs] You know, you're not that bad, for a smoothskin.}
{131}{}{Hmm... Still, when did this happen?}
{132}{}{I'd say about fifty years ago. I know, I look too young and handsome for that, right? [laughs, then coughs] I'm not as pretty as I used to be, but I'm pretty well preserved. Tends to spook people, though. That's why I left the Hub - figured I'd rather walk out than get thrown out.}
{133}{}{How far away is this Hub?}
{134}{}{Far. Don't even think about going there.}
{135}{}{Let's talk about your friend... Richard Grey, right?}
{136}{}{Little older than me, and, oh boy, was he smart. A doctor and a philosopher. We knew each other for about ten years. [sighs] Once he got drunk and told me he came from Vault 8. Funny, huh?}
{137}{}{Wait, he came from here? How? What happened to him, where is he now?!}
{138}{}{I don't know exactly what happened to him. But I know, that not far from the Hub cultists are building some sort of cathedral. I've been there, and I know who's behind it.}
{139}{}{How did you find out?}
{140}{}{I can't explain it to you. But soon you'll understand. Things in the wastes are changing fast.}
{141}{}{Why are you telling me about it then? Did you talk to anyone in the Hub about it?}
{142}{}{Because when I saw the number on your vault, I remembered Richard. And your doctor believed me right away. Ask him why. Everyone in the Hub just called me crazy. And, to be honest, they're right! Ha-ha...}
{143}{}{Whatever. I won't get anything useful from you anyway. Just a bunch of crazy stuff.}

#Разговор о Пус'ошах
{200}{}{Yeesh. I don't want to be rude, but I didn't get here just for kicks.}
{201}{}{What are you doing here then?}
{202}{}{You tell me! It's your brave guys stopped my caravan, when we came too close. Looks like they had an order to capture someone like me for the info about outside world... Or maybe just to poke me with your damn needles.}
{203}{}{Oh, Doctor Willmouth must be looking for subjects for his studies... What's a caravan, anyway?}
{204}{}{It means I travel around looking for junk to buy and sell, kiddo, and maybe make enough profit to eat once in a while. You don't even know that? You're a funny bunch. I've never met anyone like you in the wastes, and I've been working for a *long* time.}
{205}{}{Good, because I want to know everything about the outside world.}
{206}{}{What? Don't take this the wrong way, friend, but you people don't belong out there. The outside world is cruel. The Hub or Necropolis would eat you alive. You're lucky, living in a place like this, with all this technology. Most fellas can't even dream of such life.}
{207}{}{[Next]}
{208}{}{It's uglier out there than I am. Ha! The closest city, New Reno, is in the middle of a civil war. And in Vegas, the local royalty are at each other's throats, while everyone else is begging for their crumbs. To the south from that is just emptyness. Burned with nuclear fire... Cities in ashes... Radioactive, twisted forms of life... }
{209}{}{It must be horrible.}
{210}{}{Nevada and California to the west might be all that's left. At least those cities are just old, not destroyed. You should appreciate it, friend.}
{211}{}{Interesting. But I have to go.}

{220}{}{Ha! Judging from your face, you found the place, didn't you?}
{221}{}{And what did you find?}
{222}{}{This sounds like it was a long time ago.}
{223}{}{What do you think I am, an idiot? Coordinates! Fast!}
{224}{}{I'd love to, but when you're my age, you start to forget that kind of thing. [laughs, then coughs]}
{225}{}{Fine. Do you even remember when this happened?}
{226}{}{A crazy old story from a crazy old geezer. Do you even remember when this happened?}
{227}{}{Hub? Bullshit! There's no such place!}
{228}{}{Uh-huh. Likely story. You got any proof?}
{229}{}{That sounds pretty hard to believe. Are you sure? You might have had sunstroke or something... }
{230}{}{I don't believe you! You're trying to hypnotize me! Back! Back, foul demon!!!}
{231}{}{This is awfully hard to believe, don't you think?}
{232}{}{I understand. But your doctor - he believed me. Ask him about it. Everyone in the Hub just called me crazy. And, to be honest, they're right! Ha-ha...}
{233}{}{You don't want to believe it, that's your problem. I don't need this crap.}

##########################################################
#
#    Песня Луи Армс'ронга
#    в переводе на русский
#    (плавающие реплики над Гарольдом)
#
##########################################################

{300}{}{::tries to dance::}
{301}{}{* Give me, a kiss to build a dream on... *}
{302}{}{*...and my imagination, will thrive upon that kiss... *}

{303}{}{Hm-m-m... }

{304}{}{* Sweetheart... *}
{305}{}{*...I ask no more than this... *}
{306}{}{*...a kiss, to build a dream on... *}

{307}{}{::moans in rhythm::}

{308}{}{* Give me, a kiss, before you leave me... *}
{309}{}{*...and my imagination... *}
{310}{}{*...will feed my hungry heart... *}

{311}{}{::hums a few notes::}

{312}{}{*...leave me, one thing before we part... *}
{313}{}{*...a kiss to build a dream on *}
{314}{}{::hums a few more notes::}

{315}{}{Hey, smoothskins! Join in any time!}

{316}{}{*...When I'm alone, with my fantasies... *}
{317}{}{*...I'll, be with you... *}
{318}{}{*...weaving... Romances... *}
{319}{}{*...making believe they're true... *}

{320}{}{::takes a deep breath::}

{321}{}{* Oh! Give me, your lips for just a moment... *}
{322}{}{*...and my imagination, will make that moment live... *}
{323}{}{*...mmm, give me, what you alone can give... *}
{324}{}{*...a kiss to build a dream on! *}

{325}{}{And here the trumpet plays!}

#Female character:
{1110}{}{Hey, smoothskin! You ever seen the walking dead before? BOO! Ha-ha-ha! [laughing turns to coughing] Scary, huh? Maybe I should take a couple of bucks for the show.}
{1114}{}{Heh! Tough girl, huh? Sergeant Friendly out front wasn't scared of me either... Until I told him what's happening out in the wastes, that is.}
{1130}{}{[Laughs] You know, you're not that bad, for a smoothskin.}
{1140}{}{I can't explain it to you. But soon you'll understand. Things in the wastes are changing fast.}
