{100}{}{You see: Joshua.}
{101}{}{Poor Joshua seems to have a lot of work. He's carefully analyzing data on the monitor.}

##############################################
#
#    Начало диалога
#
##############################################

{200}{}{Hello, citizen }
{201}{}{. What do you want?}
{202}{}{What is this place?}
{203}{}{What are you doing?}
{204}{}{Can I use this computer?}
{205}{}{Anything else?}
{206}{}{}
{207}{}{About that robot... }
{208}{}{I found this holodisk in the west ruins, but I can't read it. Can you help?}
{209}{}{Nothing.}

##############################################
#
#    Вопрос про радиосвязь (в 1.00 не используе'ся!)
#
##############################################

{210}{}{Yes, we use the radio to communicate with the security patrols, so we're experienced in this field.}
{211}{}{Can you tell me anything about these papers from NPP "Poseidon Oil"?}

{212}{}{Radio transmission points? Hmm... It seems that there's a radio station in the wastes that supports smaller stations by rebroadcasting their signals at higher power. That's just a theory, though. We've never gotten a signal before, just white noise. I've never seen any other reports about this. And what's stranger is that these recordings were at the Poseidon Oil power plant.}
{213}{}{What is "white noise"?}
{214}{}{Can we listen to those frequencies?}
{215}{}{Can we learn the coordinates of those stations?}

{216}{}{And the second station?}
{217}{}{It's to the south-east. I'll mark the coordinates on your Pip-Boy.}
{218}{}{Hmm, that's where Cheyenne is located. Maybe they can show me where the station is.}
{219}{}{Thanks. I'll take it from here.}

{220}{}{It's nothing. Just background noise on the radio.}
{221}{}{Our station isn't strong enough. It has range about a couple of miles. We'll need a more powerful station.}
{222}{}{Oh, I... Shouldn't have said that. I was told not to tell that to common citizens. But I guess you're an exception, right?}
{223}{}{Sure, you can trust me.}
{224}{}{Then you'll have to wait while I study the signal.}
{225}{}{Sure. You're the scientific expert here.}
{226}{}{Then no. I'll try to figure it out myself.}
{227}{}{Here's what I've got. With some of our system data I managed to find the coordinates of the supporting stations, but two of them are too far away to reach. One is located at NPP, probably so it can use the plant's power.}

{228}{}{No, no-no-no-no. That's strictly forbidden by our unit supervisor.}
{229}{}{I saved your ass, remember?}
{230}{}{Fine, I won't force you to it.}
{231}{}{Aw, jeez... Fine, just this time. I've already broke the law once. Oh, this is going to haunt me...}
{232}{}{Don't worry, I'll be careful.}

{233}{}{Joshua showed you the coordinates of a previously unknown location in the South-East.}

##############################################
#
#    Прос'ые вопросы и поиск разведробо'а
#
##############################################

{250}{}{This is the technical service office. We maintain electronic equipment.}
{251}{}{Right.}
{252}{}{Right now I'm monitoring the scouting robots.}
{253}{}{What kind of robots do you use?}
{254}{}{What are scouting robots used for?}
{255}{}{They won't work without you?}
{256}{}{Is that difficult?}
{257}{}{Everything running smoothly?}
{258}{}{Self-guiding, multi-functional systems, from flying scouts to heavy duty mining ones. Every one is irreplaceable, and we never have enough of them, so they're in constant use. Still, the work's being done very slowly.}
{259}{}{Mostly, the scouting robots are used to study the topography, seismography, and radioactivity of the surrounding areas.}
{260}{}{Uh, yes and no. They have complex A.I. systems, but they need a human controller in case of unexpected situations.}
{261}{}{It depends on the task. Sometimes it can be very difficult. But I wouldn't rely just on robots. They need a human telling them what to do. Without that, they're just useless machines.}
{262}{}{My supervisor wouldn't allow it. Even if he would, to do that I'd have to pull a huge amount of data off the server. None of us can spare that kind of time.}
{263}{}{Can I see the scouting reports?}
{264}{}{Uh... [glances at a monitor with one red flashing light] W-we manage.}
{265}{}{Really? Because that indicator says "Robot's not responding"!}

{266}{}{Woah-woah-woah, just - just keep it down, okay? I'll bring him back, okay? I can fix this, just... Don't tell my supervisor, alright?}
{267}{}{Wait just a second. What are you talking about?}
{268}{}{Wait, what is it?}
{269}{}{I won't tell anyone. Just calm down and tell me what's happening.}

{270}{}{Okay, so... I lost track of one of the robots doing research in the ruins, and now it's not responding. If my supervisor finds out, he's going to nail me to the wall. If I just knew what went wrong, or could get that information back, then maybe I can dodge the worst of it.}
{271}{}{You know, that's just the sort of problem I'm here to solve. Just ask, and I can make your problem go away!}
{272}{}{I'll find your robot, if you give me something for it.}
{273}{}{Wow, sounds like you really need some help. Well, see ya.}
{274}{}{Oh, yes please, thank you! It got lost somewhere around the west ruins. I'd have snuck out myself, but... It's dangerous there.}
{275}{}{Don't worry about me, I'll handle it.}
{276}{}{Something? Like what? I don't have anything... Wait, I have this water flask! Please, help me!}
{277}{}{Okay, deal. I'll do it.}
{278}{}{That's it? Do it yourself, I'm out of here.}
{279}{}{Thank you, }
{280}{}{! You're really helping me out here. Just don't say anything to my superiors, or I'm toasted.}
{281}{}{I'll remember that... Anyway, I've got to go.}
{282}{}{Of course, don't worry. No one will ever find out.}

{289}{}{Not yet.}
{290}{}{Did you find the robot yet?!}
{291}{}{Where did you lose contact with it?}
{292}{}{Go outside and up the street to the "Dangerous Area" sign. There'll be a guard standing there. Turn west and you'll be in the ruins.}
{293}{}{That's all.}
{294}{}{I found the robot. The data's on this holodisk. Here, take it.}
{295}{}{I found the robot this holodisk, but are you going to give me something for it?}
{296}{}{Oh, thank you }
{297}{}{! This is exactly what I need. You've really saved my ass!}
{298}{}{Okay, I have some more questions.}
{299}{}{Take care, Joshua.}

##############################################
#
#    На 'ему голодисков
#
##############################################

{300}{}{What is it? A story from the wastes? How interesting! Wait here while I try to load them onto the computer.}
{301}{}{Go on, try. This is very interesting.}
{302}{}{I don't have time for this.}
{303}{}{Yes! [pumps his fist in the air] I did it!}
{304}{}{What's on there? Show me!}
{305}{}{These notes were encrypted. I had to go digging through some old archives to find the right code. I saved the decrypted file to the holodisk so you can read it.}
{306}{}{Great! How do I read it from the holodisk?}
{307}{}{Good, give it to me. I'll read it when I have the time.}
{308}{}{Easy. Select "use" on the holodisk, and the information will be copied to your Pip-Boy. Then open it and go into your notes list on the right. Select the file and read.}
{309}{}{Thanks, I'll give it a try.}
{310}{}{Joshua deciphered the information on the holodisk. This information should be very useful.}

{313}{}{How could you! I trusted you!}

##############################################
#
#    Кар'а памя'и робо'а - разби'ый дилижанс
#
##############################################

{330}{}{Can you decipher it? [show him the recordings from the robot]}
{331}{}{Sure, this is all pretty standard. But I'll need some time.}
{332}{}{I'll wait. Do your thing.}
{333}{}{Then forget it. Don't waste time.}
{334}{}{That took a while. There's a lot of data in here, that robot was not well optimized.}
{335}{}{Thank you. This is what I needed.}

##############################################
#
#    Починка бор'ового компью'ера поезда
#
##############################################

{340}{}{I need to repair this on-board computer.}
{341}{}{Hmm... [carefully and even cautiously studies the unfamiliar device]}
{342}{}{Uh, do you even know what that is?}
{343}{}{Honestly - no. I've never seen anything like this before, but I think I can figure it out. I just need permission from my supervisor. This is going to take a while and if he sees me doing unsanctioned work, he's gonna be pissed.}
{344}{}{I'll talk to your supervisor.}

##############################################
#
#    Female character
#
##############################################

{1200}{}{Hello, citizen }
{1208}{}{I found this holodisk in the west ruins, but I can't read it. Can you help?}
{1229}{}{I saved your ass, remember?}
{1294}{}{I found the robot. The data's on this holodisk. Here, take it.}
{1295}{}{I found the robot this holodisk, but are you going to give me something for it?}
