{100}{}{You see a terminal.}
{101}{}{You see an emergency medical terminal.}
{102}{}{You cannot do that in combat!}
{103}{}{Your science skill is not high enough to break into this terminal.}
{104}{}{To access this computer you need to use a scientific approach.}
{105}{}{Science skill is needed.}
{106}{}{You already broke into this computer.}
{107}{}{Nothing interesting.}
{108}{}{You hacked into the emergency terminal, forcing it to dispense one stimpak.}
{109}{}{Yes!}
