{100}{}{You see: Sam.}
{101}{}{You see Sam, a young man responsible for warehouse operations.}
{102}{}{If I see you trying one more time... }

#######################################################
#
#        Начало диалога и рядовые фразы
#
#######################################################

{110}{}{Hi, citizen }
{112}{}{. How can I help you?}
{113}{}{You? After that business with Joshua, I thought they would isolate you. Strange to still see you here.}
{114}{}{I wanted to say goodbye before I leave. So... Goodbye.}
{115}{}{Anything else?}

#######################################################
#
#        Супербонус
#
#######################################################

{118}{}{I don't recognize any of this stuff.}
{119}{}{That's none of my business, I just take inventory. I heard you lost your memory, so I'm not surprised you don't remember any of it. Probably, those things belonged to the outsider that brought you here. They're definitely not from Vault City.}
{120}{}{I came to get my things.}

{121}{}{I was told to assemble everything you had on you when you came in. They're in the locker on the left. They include... [checks his list] ...One pistol, one switchblade, one water flask, one paper note, and 128 dollars. Please check if everything is in order and sign... Here.}
{122}{}{What if I need anything else?}
{123}{}{Good. Thank you.}

{124}{}{I wasn't told to supply you with anything else.}
{125}{}{You mean I can't request anything from the warehouse!?}
{126}{}{I can't do anything for you, unless I receive an order from my superiors. But you could complete an assignment for the warehouse.}
{127}{}{And how can I put in an order?}
{128}{}{Assignment for the warehouse? What do you mean?}
{129}{}{Fine, forget it.}

{130}{}{Can you give me something out of the warehouse?}
{131}{}{If it's important, ask someone with authority to put in a request to the warehouse. They'll fill out the form for you.}
{132}{}{You said something about an assignment for the warehouse?}
{133}{}{You said something about requesting an order from your superiors?}
{134}{}{We've got some requests for equipment we don't have in stock. There's special procedures in place for trading items with outsiders, if they can give us something valuable.}
{135}{}{What will I get if I bring you those items?}
{136}{}{You'll be able to request high-value items from the warehouse, like sniper rifles and armor. But it's a long list, and you'll need to get everything on it.}
{137}{}{Great. Can I have that list?}
{138}{}{Sure. I'll put it into your Pip-Boy.}
{139}{}{[Next]}
{140}{}{Done. All of those items are Vault-Tec, so you should know where to look.}
{141}{}{I'll keep that in mind.}

{150}{}{I want to talk to you about that special assignment.}
{151}{}{You've got the list in your Pip-Boy. Did you manage to find anything?}
{152}{}{No, not yet.}
{153}{}{Yes. }
{154}{}{.}
{155}{}{The item seems to be missing.}
{156}{}{}
{157}{}{}
{158}{}{}
{159}{}{}

{160}{}{Hmm. Looks functional. Thanks, citizen. Do you have anything else?}
{161}{}{That's everything on the list. All that's left is the reward.}
{162}{}{I'll come back when I find the rest of the items.}
{163}{}{Really? Oh, you're serious! To be honest, this has never happened before. Well, the Overseer's orders were clear, you now have high-level access to the warehouse.}
{164}{}{Let's see what you've got.}
{165}{}{I want to receive my reward.}
{166}{}{Yes, I remember. Let's get this over with.}
{167}{}{Before I decide, I want to ask you about something else.}
{168}{}{You know, I can't decide yet. Let's do this later, okay?}
{169}{}{I can't decide yet. We'll do this later.}

{170}{}{You can choose only one thing out of the list.}
{171}{}{[Power fist]}
{172}{}{[Super sledge]}
{173}{}{[Pancor Jackhammer shotgun]}
{174}{}{[Sniper rifle]}
{175}{}{[Laser rifle]}
{176}{}{[Plasma rifle]}
{177}{}{[Grenade launcher]}
{178}{}{[Electronic lock pick Mk II]}
{179}{}{[Super tool kit]}
{180}{}{[Combat armor]}
{181}{}{[Automatic rifle m2041]}
{182}{}{[20 stimpaks]}
{183}{}{[]}
{184}{}{[]}
{185}{}{[]}
{186}{}{[]}
{187}{}{[]}
{188}{}{Next list.}
{189}{}{Previous list.}

{190}{}{This? Are you sure? Wait here, I'll fill out the paperwork and get it from storage.}
{191}{}{That's my choice. Hurry it up, please.}
{192}{}{Wait, I changed my mind! I need something else.}
{193}{}{Thank you for your help, }
{194}{}{. Here's you go.}
{195}{}{If this were New Reno, I'd even tip you, heh heh.}
{196}{}{Finally, some use out of your stingy warehouse!}

#######################################################
#
#        Журналы
#
#######################################################

{200}{}{Well, well, well, what do we have here? Where'd you get this magazine, Sam? These women have lost all of their clothes!}
{201}{}{What - how - [looks around wildly] D-don't tell anyone! Please! It's not even mine... }

{202}{}{Yeah, yeah, likely story.}
{203}{}{If not yours, then whose?}
{204}{}{It's true! It's not mine. It belonged to that prisoner in the cells. They sent it here for storage, and... I was just looking, that's all. That's not against the rules, right?}
{205}{}{Maybe not. But you know about the physical contact restrictions. Of course, this is just visual contact, but you might still get in trouble for it.}
{206}{}{[Hangs his head] I know... It's just so, so *new* to me. They never showed this to us, how other people look... You know, under their clothes. Maybe the doctors know. Even looking at these pictures, it's so... Weird and confusing... }
{207}{}{Would you like to see... The real thing? You know what I mean.}
{208}{}{The rules apply to everyone. Such an act, even if they're just pictures, is unforgivable.}
{209}{}{I don't care if you're curious about what people look like under their clothes, Sam. It's your problem and you'll have to deal with it yourself.}
{210}{}{Yes... Indeed. There's no rules against reading magazines, only physical contact. The committee can give me a hard time, but they can't punish me too badly. Let's just keep this between you and me, okay?}
{211}{}{You can trust me, but I'll take the magazine. I might need it in my travels.}
{212}{}{Give me the magazine, and you can sleep peacefully. But I won't go so easy on you next time.}
{213}{}{You think? Oh crap, I'm in big trouble... Look, just take it! Take it out of the city and... And just get it out of here! I'll delete it from the records, so no one will ever know!}
{214}{}{You're making the right choice, Sam. Maybe I'll find use for it out there in the wastes.}
{215}{}{I don't need your permission, you abhorrent pervert. Just pray I keep this a secret.}
{216}{}{But it's forbidden... I mean, it's not forbidden to look, but... }
{217}{}{Come on, Sam, don't be shy. We'll lock the door and be all by ourselves... }
{218}{}{You uncovered Sam's voyeuristic fantasies. Strange as it sounds, Vault City residents do not have any sexual experiences.}

#######################################################
#
#        Совращение
#
#######################################################

{234}{}{[Mouth hangs open in shock] I... I, er... Uh... }
{235}{}{Don't just stand there, Sam. Be honest, you *want* to look, don't you?}
{236}{}{Oh, you look so cute when you're flustered, Sam. You don't just want to look, do you? What if I sit in your lap so you can *touch* it?}
{237}{}{Well then stay there standing, while I get out of here.}

{238}{}{[Swallows] Y-yes... I mean, no! I mean... Why are you doing this?}
{239}{}{Why? You're so sweet, Sam. You're curious about this, aren't you? [sit in his lap and wrap your arms around his neck]}
{240}{}{Goddamn it, you're boring. I'm out of here.}

{241}{}{[Tries to push you away] No, stop! What are you doing? We, we can't... The rules... The Overseer... [breathes heavily] ...l-leave me alone, don't touch me. We can't... Physical contact is forbidden, remember?}
{242}{}{Oh man... }
{243}{}{[Swallows] Wha... No, don't, wait... Why?}

{244}{}{D-don't... }
{245}{}{It's not what you expected, is it, Sam? [hug him tighter] Do you feel that? It's soft, isn't it?... }
{246}{}{Okay, that's enough. No more, alright?}

{247}{}{[As you get out of his lap, Sam instinctively tries to hold on to you and falls to the floor] What are you... No, no, we can't! It's forbidden! Get... Get out of here! GET OUT OF HERE!}
{248}{}{Okay, okay, I'm going.}
{249}{}{[Sam slowly slides his hands down your body, silently looking at you, but then looks down at his lap in panic] Ohh, what is this? What's happening to me?! [shoves you off him in panic] WHAT IS HAPPENING TO ME?! [stumbles to the corner, holding his crotch, and looks at you with wide eyes] Leave! Get out! GET THE HELL OUT OF HERE!}

{250}{}{I can't stop thinking out it. Listen, don't do that again, okay?}
{251}{}{That was so weird... Let's not do it again.}

#######################################################
#
#             Плавающие случайные фразы
#
#######################################################

#Фразы после истечения первого срока игры (GAME_TIME_IN_DAYS > TIME_LIMIT_1):

{270}{}{Without well-armed guards, we're taking a big risk.}
{271}{}{Sergeant Graves is acting strange lately.}
{272}{}{They've increased the patrols outside the city.}
{273}{}{We heard screaming outside the city last night.}
{274}{}{Did you hear something?}
{275}{}{I think I'd rather keep the door closed... }
{276}{}{I want to go back into the vault.}
{277}{}{Ugh... }
{278}{}{Great, now I'm imagining things... }
{279}{}{Sergeant Stark asked for a lot of ammo.}

#Обычные фразы:

{280}{}{This thing is crap.}
{281}{}{I'm sweating already.}
{282}{}{The guards have me running nonstop.}
{283}{}{Did the last patrol finally come back? Good!}
{284}{}{Don't hold up the line.}
{285}{}{It's not my business, but... }
{286}{}{Give me this, give me that... I'm sick of it.}
{287}{}{Just garbage.}
{288}{}{I need to write up another report.}
{289}{}{No, I can't "lose" something for you.}

#######################################################
#
#        Выдача снаряжения
#
#######################################################

#Предохранитель для Джерлака
{300}{}{I need a fuse for a water pump.}

{301}{}{Oh yeah, I got that order. Just a minute.}
{302}{}{Good.}
{303}{}{I haven't received any orders for that. Ask Sergeant Graves to put in an order.}
{304}{}{Are you kidding me? So much running around for such a little thing?}
{305}{}{Fine, I'll go find him.}

{306}{}{Those are the rules.}
{307}{}{Rules, huh? Strange, I remember some rules against physical contact... }
{308}{}{Okay, I'll go ask for permission.}

{309}{}{You... You wouldn't. [wipes sweat from his forehead] Look, I'll give it to you, just don't tell anyone, okay?}
{310}{}{Smart decision, Sam. Now give me the fuse!}
{311}{}{Relax, I'm kidding.}

{312}{}{And where do naked magazines fit into those rules?}
{313}{}{Done. Sign here.}
{314}{}{Whatever you say.}

#Поезд
{320}{}{Is there anyone in the city that could repair a train?}
{321}{}{Uh, maybe someone from the technical services could help you out. Why are you asking me?}
{322}{}{Okay.}

#Female character
{1110}{}{Hi, citizen }
{1120}{}{I came to get my stuff.}
{1160}{}{Hmm. Looks functional. Thanks, citizen. Do you have anything else?}
{1192}{}{Wait, I changed my mind! I need something else.}
{1195}{}{If this were New Reno, I'd even tip you, heh-heh.}
{1207}{}{I understand, Sam. I'm curious too. Would you like to see... The real thing? You know what I mean.}
{1212}{}{Give me the magazine, and you can sleep peacefully. But I won't go so easy on you next time.}
