{100}{}{You see a gamer.}
{101}{}{You see a gamer, she's very passionately playing a game.}
{102}{}{Hi.}

{110}{}{(This girl is glued to the arcade machine; a win is all she cares about right now)}
{111}{}{What are you doing?}
{112}{}{[Leave]}

{113}{}{What? Oh, this arcade machine... [she talks, without taking her attention off the screen] I'm stuck on this level... I tried so many times, but the last boss - it's something special. Always losing on him. But you know, every other game I can beat on the first try. I choose the most difficult ones - and always win. Can you imagine? In such moments, I have this strange feeling... Like when the whole world freezes in time just for you.}
{114}{}{And if you win, then what? Do you get some reward, like money?}
{115}{}{No, here you're the one that pays in order to play, not the other way around. It's not like a casino. If you win here, the best you can count on is a bottle of beer from bartender. Like, you know, a token of appreciation.}
{116}{}{How long have you been playing on such machines?}

{117}{}{Very... Damn it! [she twitches as she tries to dodge an attack on her character] Oh man, I lost again... Listen, you're distracting me!}
{118}{}{Sorry, I didn't mean to! I didn't think winning some game was that important for you.}
{119}{}{Not my problem, who cares? Maybe I would care more, if winning got you, like, a hundred bucks or something.}
{120}{}{Not your first loss eh? Tell me, why is it so important to you?}
{121}{}{Important? Of course, it's important! }
{122}{}{Then why not go play at the casino? Although, I suppose it's different. }
{123}{}{}
{124}{}{[Sighs] Oh, I don't know if you would understand... I'm always in control here, right? Avoid, shoot, kill... Everything is simple, I know the rules. Sure it gets boring sometimes, but it's better than the old slums I live in.  And... [sighs again] It just feels good that, at least for a moment, to grasp that feeling that the world revolves around me. Know what I mean?}
{125}{}{Yeah... I guess. What about that machine over there, is it not working?}
{126}{}{No. It couldn't handle me! I was getting to the tenth level boss on one life, and somehow that fried the board. They all break now and then, usually getting fixed up in a day or so. I guess that one shorted real bad.}
{127}{}{Hmm. Got it. Well, see you.}
{128}{}{I guess you're right. Anyway, I won't be distracting you anymore. Bye.}

{1118}{}{Sorry, I didn't mean to! I didn't think it's that important for you, to win at some game.}
