{100}{}{You see bartender Tony.}
{101}{}{You see a chubby man behind the bar. He smiles to each visitor.}

#Attempt to talk wearing a balaclava
{102}{}{Show your face first, I want to see who I'm serving.}

{126}{}{It won't take long for you to get punched in the face doing that!}

#Rumors:
{130}{}{Hey, bartender, keep this $10 as a tip.}
{131}{}{[Smiles immediately in response to you] Thank you for your generosity, sir.}
{132}{}{Can you tell something interesting, if you're not too busy?}
{133}{}{I've heard there's a real treasure buried somewhere in Vegas. If you find it, you'll become truly rich. I don't know if it's true, so far no one's found it yet.}
{134}{}{Want me to tell you about the gun Mr. Hal Wallace has? It is a real rarity! Taking a bullet from this gun isn't to be envied. And the engraving on it, m-m! Something with Indian accents, real classy.}
{135}{}{Barney Hill is a strange person. There he is, standing next to the treadmill. Wears this stupid hat, says some awkward and stupid things. On the other hand, who cares when he's paying, right? Heh! Our boss said that good clients have to receive discounts, that's how Barney became a resident and settled in his own room. He doesn't allow even room service to go in there. No one at all. How does an ordinary prospector have so much money? Beats me... }
{136}{}{Oh, no biggie. Here was a guy, Sam Riley, our employee, went on a business trip to the west with the caravan. The caravan returned, but Sam didn't. No one's heard of him since. Looks like it's time to throw him a memorial service and get really drunk.}
{137}{}{Tibbett sells great guns, but usually keeps them away from prying eyes. It is more important for him to trade with the police, although they pay him much less than ordinary buyers. They are pressing an honest man, that pigs... Oh, excuse me, that was inappropriate.}
{138}{}{Thanks.}
{139}{}{Anything else, sir?}
{140}{}{My pleasure.}
{141}{}{Alas, nothing interesting.}

#About alcohol poisoning
{150}{}{I heard someone got poisoned having a drink from the bar. What can you say about this?}
{151}{}{[Raises an eyebrow skeptically] Competitors, damn them. They spread stories, or even try to mix some stuff into customer's drinks when they aren't looking. Why would we poison our own customers? It's too expensive.}
{152}{}{Sure, sure... }
{153}{}{Innocent till proved guilty, right? Sitting pretty, aren't you... }
{154}{}{That sounds quite logical and convincing.}

#Random remarks:
{200}{}{One serving of Rot Gut is on the way... }
{201}{}{That'll be three coins... }
{202}{}{Another one for you, buddy?}
{203}{}{Here's the cure if you want.}
{204}{}{It is not allowed to vomit in here! Get out and puke on the streets!}
{205}{}{Two packets by half an ounce or a can?}
{206}{}{A special request from Tim Cain is on the way... }
{207}{}{Let me guess: put it on your tab?}
{208}{}{One "dive bomb" with ice, coming right up.}
{209}{}{We don't allow customers to get high in here, pal.}
{210}{}{Do you know why those theater guys have to be hanged? Because the theater begins with a hanger... Ha-ha-ha!!!}

#Starting replics
{230}{}{What do you want, buddy?}
{231}{}{Booze. Show me what do you have.}
{232}{}{No thanks.}
{233}{}{Want more?}
{234}{}{Give me more.}
{235}{}{Can I book a room?}

{239}{}{Uh... Hey, slow down mug, are you sure you came to the right venue?}

#Try to speak with weapons in hand
{240}{}{Sir, I won't serve you until you put away this... Self-defense tool.}

#Questions
{241}{}{Who's that shabby guy to the left of the bar counter?}
{242}{}{Who's that weirdo with the wig to the right of the bar counter?}
{243}{}{That's a regular. He hadn't been here for a while, got lost somewhere. He says he was seized by the military, but managed to escape. Ha! He's such a windbag.}
{244}{}{That is an associate of my boss. The only thing he does is sleep during the day and throw money at the casino at night. He's a bit [twists a finger at his temple] cuckoo.}
{245}{}{Room's on the third floor, here are the keys... }
{246}{}{Okay, thanks.}
{247}{}{Here are the keys, your room is on the third floor. Have a nice stay!}
{248}{}{Thanks.}
{249}{}{You're well rested and gained strength.}
{250}{}{Damn! You vomited all over the floor! Now who is going to clean it?!!}
{251}{}{Tell me, who lives in room 26 on the third floor?}
{252}{}{Oh, that's Barney Hill. I hope he didn't cause any inconvenience for you? I understand that his somewhat eccentric appearance may be... Off-putting, but he doesn't do any harm. He claims that he was abducted by aliens from outer space, can you imagine? Heh. He was even waving around some pre-war toy, stylized as an alien blaster. Apparently, he's obsessed with the theory of an alien invasion. A strange person, but always amusing nonetheless.}
{253}{}{I see. Would you answer another question?}
{254}{}{Hmm, how curious. Thanks for the tip and bye.}
{255}{}{I'm doing the direct delivery of Nuka-Cola. We could cooperate with you.}
{256}{}{Can't you see that we *already* sell Nuka-Cola? And anticipating the follow-up question - yes, we have our own supply line from Salt Lake.}
{257}{}{So I was beaten by competitors? Bad luck... }

{258}{}{Yes, of course. The room costs }
{259}{}{ bucks a day.}
{260}{}{[Go into your room]}

#Women's replics
{1131}{}{[Smiles immediately in response to you] Thank you for your generosity, miss.}
{1139}{}{Anything else, ma'am?}
{1230}{}{What do you want, friend?}
{1239}{}{Uh... Hey, slow down mug, are you sure you came to the right venue?}
{1240}{}{Ma'am, I won't serve you until you put away this... Self-defense tool.}
