{100}{}{You see bartender Tony.}
{101}{}{You see a chubby man behind the bar. He smiles to each visitor.}

#Attempt to talk wearing a balaclava
{102}{}{Show your face first, I want to see who I'm serving.}

{126}{}{It won't take long for you to get punched in the face doing that!}

#Rumors:
{130}{}{Hey, bartender, keep this $10 as a tip.}
{131}{}{[He immediately smiles to you] Thank you for your generosity, sir.}
{132}{}{Can you tell something interesting, if you're not too busy?}
{133}{}{I've heard there's a real treasure buried somewhere in Vegas. If you find it, you'll become tremendously rich. I don't know if it's true, so far no one's found it yet.}
{134}{}{Would you like me to tell you about a gun Mr. Hal Wallace has? It's a real rarity! It's hard to envy a man who takes a bullet from a gun like that. And what an engraving it has! Something with an Indian theme, very classy.}
{135}{}{Barney Hill is a strange person. There he is, standing next to the gecko races. Wears this stupid hat, says some awkward and stupid things. On the other hand, who cares about that if he's paying, right? Heh! Our boss said that good customers should get discounts, so Barney became a resident and got his own room. But he won't even let the room service staff in. Or anyone at all. How does an ordinary prospector have so much money? Beats me... }
{136}{}{Oh, sure, no biggie. There was a guy, Sam Riley, our employee. He went on a business trip to the west with the caravan. The caravan returned, but Sam didn't. No one's heard of him since. Looks like it's time to throw him a memorial service and get really drunk.}
{137}{}{Tibbett has some great guns, but usually keeps them away from prying eyes. It is more important for him to trade with the police, although they pay him much less than ordinary buyers. They are pressing an honest man, that pigs... Oh, excuse me, that was inappropriate.}
{138}{}{Thanks.}
{139}{}{Anything else, sir?}
{140}{}{My pleasure.}
{141}{}{Alas, nothing interesting.}

#About alcohol poisoning
{150}{}{I heard someone got poisoned having a drink from the bar. What can you say about this?}
{151}{}{[Raises an eyebrow skeptically] Damn competitors. They spread false rumors, or maybe it's them who try to put some stuff into our client's drinks, when no one's looking. Why would we poison our own customers? It makes no sense.}
{152}{}{Sure, sure... }
{153}{}{Innocent till proved guilty? That's pretty convenient... }
{154}{}{That sounds quite logical and convincing.}

#Random remarks:
{200}{}{One serving of Rot Gut is on the way... }
{201}{}{That'll be three bucks... }
{202}{}{Another one for you, buddy?}
{203}{}{Here's the cure, if you want.}
{204}{}{No vomiting in here! Get out and puke on the streets!}
{205}{}{Two half-ounce packs or a can?}
{206}{}{A special request from Tim Cain is on the way... }
{207}{}{Let me guess: put it on your tab?}
{208}{}{One "dive bomb" with ice, coming right up.}
{209}{}{We don't allow customers to get high in here, pal.}
{210}{}{Do you know why those theater guys have to be hanged? Because the theater begins with a hanger... Ha-ha-ha!!!}

#Starting replies
{230}{}{What do you want, buddy?}
{231}{}{Booze. Show me what do you have.}
{232}{}{No thanks.}
{233}{}{Want more?}
{234}{}{Give me more.}
{235}{}{Can I book a room?}

{239}{}{Uh... Hey, slow down, mug. Are you sure you came to the right venue?}

#Try to speak with weapons in hand
{240}{}{Sir, I won't serve you until you put away this... Self-defense tool.}

#Questions
{241}{}{Who's that shabby guy to the left of the bar counter?}
{242}{}{Who's that weirdo with the wig to the right of the bar counter?}
{243}{}{That's a regular customer. He hasn't been here in a long time, been wandering around somewhere. He says the military grabbed him, but he managed to escape. Ha! He's such a windbag.}
{244}{}{That is an associate of my boss. The only thing he does is sleeps during the day and throw money at the casino at night. He's a bit [twists a finger at his temple] cuckoo.}
{245}{}{Room's on the third floor, here are the keys... }
{246}{}{Okay, thanks.}
{247}{}{Here are the keys, your room is on the third floor. Have a pleasant stay!}
{248}{}{Thanks.}
{249}{}{You're well rested and gained strength.}
{250}{}{Damn! You vomited all over the floor! Now who is going to clean it?!!}
{251}{}{Tell me, who lives in room 26 on the third floor?}
{252}{}{Oh, that's Barney Hill. I hope he hasn't caused any inconvenience? I understand that his somewhat eccentric appearance may be... off-putting, but he doesn't do any harm. He claims that he was abducted by aliens from outer space, can you imagine? Heh. He was even waving some pre-war toy around, stylized as an alien blaster. Apparently, he's obsessed with the theory of an alien invasion. A strange person, but always amusing nonetheless.}
{253}{}{I see. Would you answer another question?}
{254}{}{Hmm, how curious. Thanks for the tip and bye.}
{255}{}{I'm dealing with Nuka-Cola. We could make a joint business.}
{256}{}{Can't you see that we *already* sell Nuka-Cola? And anticipating the follow-up question - yes, we have our own supply line from Salt Lake.}
{257}{}{So I was beaten by competitors? Bad luck... }

{258}{}{Yes, of course. The room costs }
{259}{}{ bucks a day.}
{260}{}{[Go into your room]}

#Women's replies
{1131}{}{[He immediately smiles to you] Thank you for your generosity, ma'am.}
{1139}{}{Anything else, ma'am?}
{1230}{}{What do you want, friend?}
{1239}{}{Uh... Hey, slow down, mug. Are you sure you came to the right venue?}
{1240}{}{Ma'am, I won't serve you until you put away this... Self-defense tool.}
