{100}{}{You see Andy Hawk.}
{101}{}{You see Randy Hawk.}
{102}{}{You see a tired shabby caravan merchant. Apparently, his last journey was rough.}

{105}{}{Hello, friend! We were just talking about you!}
{106}{}{Ah, wanderer, hello. How are you doing? As you can see, we don't do so well.}
{107}{}{What do you want?}

#Диалог с теми, кто на ногах
{149}{}{You will have to tell me. I'm not one of those that can be easily pushed away.}
{150}{}{I just wanted to say hi.}
{151}{}{Nothing.}
{152}{}{What happened to your group?}

{153}{}{We had a shitty journey, that's what. 20 miles from the Wind of War we have reached the gas station and stopped to rest. It was at night, and we were ambushed by that raiders scum. We barely made it out alive, but all the goods were left there.}
{154}{}{The goods, you say, huh? Heh-heh. Perhaps, you can show me, where's this place?}
{155}{}{Did everyone made it out alive?}
{156}{}{Well, tough luck. Bye.}

#Агрессивная попытка узнать место рейда
{157}{}{What?! Oh, you bastard! We lost half of our men, and all you think about is looting the goods? Like hell I'll show you the location!!!}
{158}{}{[Grab him by the collar] Where is the merchandise?! Where?!}
{159}{}{Damn, okay. I will find it out anyway!}
{160}{}{Wow, sorry, it's just my goddamn greed.}

{161}{}{Ah, shit! Okay, fuck it, I'll show you, but keep in mind - if you get killed, it's not my fault! Got it?! Although, you know... Listen, yeah, seriously, go there, okay? If you see some of our guys from "Speed Hawk" made it out alive, tell them that four of us got to Vegas... But I really doubt that anyone left there, except dead bodies... Goddamn raiders! May they burn in hell!}
{162}{}{Come on already, give me the coordinates!}
{163}{}{The location of the attack by raiders on the caravan have been marked on your Pip-Boy.}

#Координаты Ветра Войны
{164}{}{What Wind of War?}
{165}{}{Lush place between Reno and Vegas. Most caravans stop there to rest and get some water.}
{166}{}{Can you show me the location on the map?}
{167}{}{Yes, here [He enters the coordinates into your Pip-Boy]. But be careful there, don't talk to soldiers, it's better sometimes to avoid them altogether.}
{168}{}{Okay. Thanks.}
{169}{}{So, you are saying you abandoned the goods? Perhaps, you can show me where this place is?}
{170}{}{What about your problem? Did everyone made it out alive?}

#Положительная попытка узнать место рейда
{171}{}{Thank you, wanderer, for being so sympathetic. Others would want to know where we left the goods instead... But when we were running away it was dark, and I don't even know who may be alive. I'm afraid that only four of us survived.}
{172}{}{How many people were in your group?}
{173}{}{Sorry. We'll talk about it later.}
{174}{}{Eight. Raiders did everything smart and we didn't even heard them coming. I didn't even think, they can be so cunning. Usually raiders just attack head-on. And here we had a good planned assault...}
{175}{}{So you just abandoned everything and started running? And didn't even think of coming back?}
{176}{}{Yes, damn it! It's raiders, no one wants to deal with them. They cannot be negotiated with. Just look what they did to my guys. [points at those, who is laying on mattresses] The fact that we made it to Vegas was a miracle by itself.}
{177}{}{Right. Maybe, you need help?}
{178}{}{Sad story. But I have to go.}
{179}{}{So, you are saying you abandoned the goods? Heh-heh. Maybe you can show me the location?}

#Получение квеста
{180}{}{Are you saying that you'll just go there? Damn you must be desperate. Fine, wanderer, let me show you the place.}
{181}{}{Show me.}
{182}{}{Here. Raiders already took everything valuable for sure. But probably they left some things they didn't care about. There is a filter there. Useful thingy. Return it, okay? And you can take everything else.}
{183}{}{We'll see.}
{184}{}{And one more thing. If you see any of our guys, tell them, that we have made it to Vegas. And if they are dead, then... Please, don't let them rot under the sun, bury them like human beings, okay? There was a shovel in one of the wagons, I don't think raiders would take it.}
{185}{}{I'll see what I can do.}

#Промежуточный базар
{186}{}{About the raid. Are you sure it was raiders?}
{187}{}{Who else?! But if I think about how they ambushed us... Damn, sneaky bastards!}
{188}{}{Hmm...}
{189}{}{I know who did this. It wasn't raiders, it was soldiers from the Wind of War.}
{190}{}{Are you sure? We knew it. They worked too professional! Fine, forget it then. This is getting way more dangerous.}
{191}{}{Well, we'll see about that.}

#Завершение квеста и раздача добра
{192}{}{Your problem is solved. Turns out, the attack was done by the Wind of War soldiers.}
{193}{}{So that's how it is! We knew it. They worked too professional... But how did you managed to find out? What about our merchandise?}
{194}{}{The goods are still at a gas station. You can go take it, but most valuables are long gone.}
{195}{}{Damn... I knew it. Hopeless.}
{196}{}{Not quite. During my investigation I managed to find the ones that did the attack.}
{197}{}{Not quite. The Wind of War got what it deserved.}
{198}{}{Well, it's too soon to tell... Let me check a few more things and I'll be back.}
{199}{}{[Opens his eyes in surprise] How did that happen?}
{200}{}{[Tell the details]}
{201}{}{[Sighs] It won't bring our guys back. What about the stolen goods?}
{202}{}{I managed to return only the money - $1500 bucks.}
{203}{}{I managed to get the filter.}
{204}{}{I managed to get the money and the filter - $1500.}
{205}{}{Sorry, everything is lost.}
{206}{}{[Opens his eyes in surprise] I see, they respect you there, since you're still alive. What did you manage to find out?}

{207}{}{Curse to them! You know, I don't care about the goods. The most important thing we carried is a cleaning filter for Salt Lake City. People there are waiting for it, like the second coming of Jesus. Damn my luck... Fine, thank you for at least learning the truth. We won't ever come through the Wind of War again. We will change our route.}
{208}{}{Well, I gotta go, erm, there is a thing I must attend to... In another city. Take care!}
{209}{}{Thank you so much! You're a good person, since you didn't abandon us. Let me share the money with you? [gives 750 dollars] You earned it.}
{210}{}{What will you do now?}

{211}{}{We won't come to Wind of War again. And probably will change our route. You know, I don't care about the goods as much. The most important thing we carried is a cleaning filter for Salt Lake City. People there are waiting for it like the second coming of Jesus. Damn my luck...}
{212}{}{Right. Well, take care of yourself now.}
{213}{}{Yes, it was the most important! Salt Lake City is waiting for it, like the second coming of Jesus. It is needed to start the artesian tower pump and supply people with clean water. It's just - I don't know how we'll be able to take this thing to the city in our current state...}
{214}{}{I can do it. Who must I give the filter to?}
{215}{}{Uhh... You're right. We won't be able to take it there. Not just because of our condition. You see, how the other is looking at us? I'm sure some of them already know what we are talking about, we won't make it out of the city. But you have the chance. Take it. We wanted to sell it to the Nuka-Cola factory, but you certainly will judge better to whom it is more necessary.}
{216}{}{You're right! Well, I have to go. Good luck to you.}

{217}{}{Amazing! I was getting desperate... But, thanks to you, we now have money to rest and gather our strength. Now about the other problem. Filter - that's the most important thing we carried. Salt Lake City is waiting for it, like the second coming of Jesus. It is needed, to start the artesian water pump and supply people with clean water. I don't know how we'll be able to take this thing to the city in our current state...}
{218}{}{Wait! The journey to Salt Lake is long... Here, take this. It was made specifically for the desert conditions. Take it, take it, I insist!}
{219}{}{Thank you.}

#Поиск выживших караванщиков:
{242}{}{I found a survivor. Sadly, only one...}
{243}{}{Then the others died? [sighs] I knew it. Thank you, for finding Bibbit. We'll wait for him here, he'll surely will come with some caravan from the Wind of War.}
{244}{}{You're welcome.}
{245}{}{Sorry, we have nothing to pay you. We are broke after the raid.}
{246}{}{Forget it, friend, I'll manage without rewards.}
{247}{}{Then why did I do all that!?}
{248}{}{It's done. Old friends are reunited, thanks to you.}

{249}{}{Oh, friend, I would make you rich, if I had something, you know?! We are starving ourselves. We have nothing, please understand!}
{250}{}{Fuck you!!!}
{251}{}{Shit, fine, never mind.}
{252}{}{But wait! [puts out something shiny] I don't know, perhaps, you'll need it. Because I don't.}
{253}{}{Lighter? Useful, thanks.}
{254}{}{Wow! Shiny toy!}

#Зона 51, поиск координат
{255}{}{Were you driving caravans between Vegas and Reno? have you seen a military base, called Area 51?}
{256}{}{Erm... No, uhh... I haven't.}
{257}{}{Damn, too bad.}
{258}{}{Erm... No, uhh... I haven't. And I'm glad I didn't. Especially after that story at the Wind of War.}
{259}{}{Glad? Why is that?}
{260}{}{Well, I honestly never been there, but more experienced caravaneers know about it and steer clear away.}
{261}{}{Is it so dangerous?}
{262}{}{It's a hellish place. Those, those who seek their fortune of ancient technologies and super weapons there - never come back.}
{263}{}{Interesting...}
{264}{}{They say there is a nest of horrid creatures there, that sometimes attack caravans. Luckily, they rarely go so far. I never seen one, but, by descriptions it's a nightmare, trust me.}
{265}{}{If you say so.}
{266}{}{I'm serious! Instead of hands they have four tentacles, they grab the prey and rip it apart [actively gesticulating with hands]. Damn! Huge beasts, three times bigger than man! They say they hunt only on night. And that they have no eyes, but they can see through darkness.}
{267}{}{Dangerous and cunning foe. But that's okay - I'll find a way to deal with that beasts. Where is the nest, you say?}
{268}{}{Area 51. 80 miles from Vegas. Let me show you the approximate location. [points into your Pip-Boy some coordinates]}
{269}{}{Thanks, friend, that's what I needed.}
{270}{}{Remember what I told you! Even though I never met them, I knew those, who wasn't that lucky. I showed you the place so you can avoid it. Stay away from that valley, okay?}
{271}{}{We'll see.}
{272}{}{Okay.}
{273}{}{No! No way! Tell me you won't go there! I don't want people like you get hurt.}
{274}{}{Okay-okay, nothing will happen to me. You better watch over you and your guys.}

#Плавающие реплики самого говорливого
{300}{}{Told ya! We should not walk at daytime!}
{301}{}{Now the "Speed Hawk" has its wings cut. Shame.}
{302}{}{What kind of a caravaneers are we now?!}
{303}{}{Dammit! We always get in some trouble!}
{304}{}{We are the most unlucky caravan in the world.}
{305}{}{Why didn't you listen to me!}
{306}{}{I told ya, we should've walked to the north!}
{307}{}{Let this be a lesson for you!}
{308}{}{You don't listen to me again, do you?}
{309}{}{No, we should only make stops in abandoned places!}
{310}{}{We must go back and take the goods!}
{311}{}{I insist! We must go back!}
{312}{}{They already left, they won't be waiting for us there!}
{313}{}{They are already got drunk on Rot Gut and forgot about us!}
{314}{}{"Speed Hawk"! Get yourself together!}
{315}{}{Everything will be alright, don't worry!}
{316}{}{I can feel it - something is not right.}
{317}{}{All of this is very suspicious...}
{318}{}{I think we have been set up.}
{319}{}{How did they know? Did they follow us?}
{320}{}{Hmm... I don't know. All of this is strange.}

#Про Черный Караван
{350}{}{Maybe you have met... Hmm... Any *dangerous* caravans that should be avoided?}
{351}{}{I don't know. And I don't want to know.}
{352}{}{Tell me, you son of a bitch!!! Or I will *make* you speak!!!}
{353}{}{Right.}

{354}{}{Why do I get all of this! Raiders, junkies, you! No life for honest worker! Ahem... [lowers his voice] Listen, we call them "Black Caravan". It's a few guys, rather quiet. They make a stop at a backyard behind this building, push the product to someone and silently leave at night. That is all I know, so leave me alone.}
{355}{}{That's better! Instead of "don't know", "don't wanna know", blah-blah-blah...}

{356}{}{Why do you need them for?! Ugh, fine, it's your business. But we don't deal with them. I only know that they make a stop behind this building, push the product to someone and leave. We call them "Black Caravan". I don't know anything else about them, we don't have business with such kind...}
{357}{}{Right.}

#Female character
{1105}{}{Hello, sis! We were just talking about you!}
{1106}{}{Ah, wanderer, hello. How are you doing? As you can see, we don't do so well.}
{1150}{}{I just wanted to say hi.}
{1157}{}{What?! Oh, you bitch! We lost half of our men, and all you think about is looting the goods? Like hell I'll show you the location!!!}
{1171}{}{Thank you, wanderer, for being so sympathetic. Others would want to know where we left the goods instead... But when we were running away, it was dark and I don't even know, who may be alive. I'm afraid only four of us survived.}
{1180}{}{Are you saying that you'll just go there? Damn you must be desperate. Fine, wanderer, let me show you the place.}
{1207}{}{Curse to them! You know, I don't care about the goods. The most important thing we carried is a cleaning filter for Salt Lake City. People there are waiting for it, like the second coming of Jesus. Damn my luck... Fine, thank you for at least learning the truth. We won't ever come through the Wind of War again. We will change our route.}
{1242}{}{I found a survivor. Sadly, only one...}
{1243}{}{Then, the others died? [sighs] I knew it. Thank you, for finding Bibbit. We'll wait for him here, he'll surely will come with some caravan from the Wind of War.}
{1247}{}{Then why did I do all that!?}
{1249}{}{Oh, friend, I would make you rich, if I had something, you know?! We are starving ourselves. We have nothing, please understand!}
{1270}{}{Remember what I told you! Even though I never met them, but I knew those, who wasn't that lucky. I showed you the place so you can avoid it. Stay away from that valley, okay?}
