{100}{}{Tired caravan merchant.}
{101}{}{You see battered and tired caravan merchant.}
{102}{}{This caravan merchant needs first aid.}
{103}{}{This caravan merchant doesn't need healing.}
{104}{}{You have failed to heal.}
{105}{}{You successfully completed healing, receiving 150 experience points.}
{106}{}{Oh, what a relief! Thanks, friend!}
{107}{}{Hey, perhaps, you will ask me first?}

#попы'ка заговори'ь, пока персонаж не вылечен
{110}{}{Sorry, feels really bad...}
{111}{}{(he feels bad)}
{112}{}{(he won't talk to you, he feels bad)}
{113}{}{(this caravan merchant lays weakened)}
{114}{}{Leave me be, I had a rough day.}
{115}{}{What do you want?! Don't you see my condition?}
{116}{}{Can't breathe...}
{117}{}{Right in the face!.. O-oh...}
{118}{}{Everything hurts... Shit...}
{119}{}{So painful!}
{120}{}{Why did I deserve this?!}
{121}{}{Others were luckier than me.}
{122}{}{Another run? After this?! Hell no!}
{123}{}{I will be sick for a week.}
{124}{}{After such beatings, the only desire I have is to go to casino and spend everything. Only I have nothing left.}
{125}{}{Sorry, can't think right now...}
{126}{}{Talk to the others, I'm barely standing.}

{128}{}{Thanks for the help, wanderer!}
{129}{}{[Examine the patient]}
{130}{}{leave.}

{131}{}{(Bruises, cuts... This caravan merchant could use some first aid.)}
{132}{}{[Use First Aid kit]}
{133}{}{[Use Doctor's Bag]}
{134}{}{[Use Military First Aid Kit]}
{135}{}{[Use Paramedic Set]}
{136}{}{[Try to help in with your own skill]}
{137}{}{Leave.}
{138}{}{(You did it! Caravan merchant feels a lot better)}
{139}{}{(Because of the lack of your skills you hurt the caravan merchant and he pushed you away)}
{140}{}{Shit, need to be careful.}

#Жен реплики
{1106}{}{Oh, what a relief! Thanks, friend!}
{1128}{}{Thanks for the help, wanderer!}
