{100}{}{You see a waitress.}
{101}{}{You see a very busy and quite a pretty girl with a tray in her hands.}

#Starting dialogue branch:
{102}{}{[The girl keeps her eyes down, not looking at you] Would you like to... Order...  Something?}
{103}{}{Oh! It's you! Do you want me to bring you our trademark pizza?}
{104}{}{You see Susie.}
{105}{}{You see the girl from the Ted Bundy photo. She is found!}

#Starting greetings replic:
{106}{}{Yes? What do you want?}
{107}{}{What can I get you?}
{108}{}{Do you want to order something?}
{109}{}{Yes?}

#Dialogue:
{150}{}{Let me see your menu.}
{151}{}{Nothing, I'm leaving.}
{152}{}{Do you want anything else?}
{153}{}{Menu.}
{154}{}{No, nothing.}
{155}{}{What a beauty like you is doing in a place like this?}
{156}{}{Wait a minute! Your face looks familiar...}

#The completion of the epic Ted Bundy story from New Reno [only for female chars]:
{157}{}{Of course! I've been working here for more than a year.}
{158}{}{More than a year? Hmm... Are you a local?}
{159}{}{Hmm... Well, okay then.}

{160}{}{[It's weird, but the girl hesitated a little] Yes, I'm a local.}
{161}{}{Oh, don't play the fox dear! I can see right through you! Tell the truth!}
{162}{}{Sweetheart, you're not telling me something. I can see it. But you can not tell me, if you don't want to...}

{163}{}{[She blushes, then smiles] Ma'am, you are right. I came from New Reno, but it's a very sad story, so I don't tell it to anyone.}
{164}{}{A sad story? Usually all the sad stories involving beautiful girls from New Reno are associated with that night club...}

{165}{}{[The security guard approaches you] Hey! What's going on here?! The girl is working, stop harassing her. I have to ask you to leave the cafe. Yes, get out!}
{166}{}{Ow! How rude!}

{167}{}{[The girl clearly doesn't like this conversation] Excuse me, I have to get working.}
{168}{}{Uh, no! You're not going anywhere until you tell me the truth!}
{169}{}{Wait! Is it your photo?!}
{170}{}{Well, of course. Go on then.}

{171}{}{Oh My!.. [pale girl sits down on a chair to come to her senses]}
{172}{}{[Let her cool off]}
{173}{}{So, is that a confession?! Now tell me, how are you related to Ted Bundy!}

{174}{}{Oh... If Ted finds out I'm here...}
{175}{}{So, you're hiding from him?}
{176}{}{I ran away from New Reno to live a normal life. But the nightmares still haunt me.}
{177}{}{Nightmares? What did he do to you?}
{178}{}{Nothing seemingly wrong, but I understood that something... Not good was going on. And when I left him, when those girls started to appear in the backyard...}
{179}{}{Dead girls? With their eyes gouged out, right? So you could see their brains through the sockets?}
{180}{}{I understand who you're talking about. Why did he do it? Was it because of you?!}
{181}{}{My God! Why are you so heartless!? Leave me alone!}
{182}{}{Too late, honey! You will confess about everything!}
{183}{}{Then let it be so.}
{184}{}{Yes... Well, I think it was because of me. He had a certain habit - he liked to kiss my eyelids and squeeze the back of my neck... If I hadn't left him, those girls would still be alive... You... Won't tell him, right?}
{185}{}{I will, you fool! Those dancers died because of you! I'll tell everyone about this!}
{186}{}{No, my dear. And he won't be able to hurt anyone anymore. You can forget about his existence. For good.}
{187}{}{No, I won't tell anyone about you. Goodbye and take care.}
{188}{}{What?! He was punished?! That's some news!}
{189}{}{Yes, the world is now free from this maniac. And you're free too.}
{190}{}{Thank you for telling me! This is wonderful news! And could you...}
{191}{}{What?}
{192}{}{If you meet with the owner of that night club again, could you tell her that I'm still alive and just moved away? She's such a good person... She was a mother to all of us... To all the lost girls of New Reno.}
{193}{}{Well, if I get there, then maybe...}
{194}{}{I will tell her, of course.}
{195}{}{Thank you very much! Thank you!.. Oh, I should get back to work.}
{196}{}{Sure. You are welcome.}

#Info messages
{197}{}{You found the girl from the Ted Bundy photo and solved the mystery of the maniac.}
{198}{}{You found the girl from the Ted Bundy photo, although it is still not clear how it's all connected.}
