{100}{}{You see Woody the bartender.}
{101}{}{This man could pass for an ordinary bartender if not for the patches and bits of metal sewn into his business suit.}

#Attempt to talk with weapon
{102}{}{I'd be happy to serve you, but that thing in your hands is making me nervous.}

#Attempt to talk with a balaclava
{103}{}{We don't judge, but... It'd be nice to know who we're dealing with.}

#Pizza delivery
{110}{}{Where can I find a job around here?}
{111}{}{We need representatives for a courier service. The job isn't hard, but delicate. [Looks you over] Doubt you'll fit the bill.}
{112}{}{Well, not like I needed it that much.}
{113}{}{Well, I won't waste your time then.}
{114}{}{We need representatives for a courier service. The job isn't hard, but delicate. [Looks you over] You could stand to earn quite a bit.}
{115}{}{Great, what needs to be done?}
{116}{}{I'll need to think about it. Hopefully you won't find anyone beforehand.}

{117}{}{There are a few clients who need pizza to be delivered to them. They pay on the spot - the cost is 10$ and a little extra for the delivery service. Keep in mind - whatever happens, you must show yourself in the best light. There are times when you can't stand your client. That's where the delicacy is required.}
{118}{}{Alright. I'm ready.}
{119}{}{I can't do it right now. But I'll keep it in mind.}
{120}{}{Here, this is for the clients. Now write this down. One pizza needs to be delivered to the "Monte" casino, room 15, on the second floor. Another order is by a trader at the caravan stop, named Tibbett. And another one for mister Farber, the administrator of the Slavertown ring. Now come on - get to work!}
{121}{}{Alright.}
{122}{}{Oh yeah, almost forgot. You've got an hour. Keep an eye on the time.}
{123}{}{Okay.}

{124}{}{About the pizza delivery.}
{125}{}{What about pizza? You already missed all the possible deadlines. Have you got anything to say in your defense?}
{126}{}{Did you finish the job yet?}
{127}{}{All the clients have received their order.}
{128}{}{I'm still working on it.}
{129}{}{Unfortunately, err, I wasn't able to finish the job. The clients are lost, the time is up and I'm out of pizza.}
{130}{}{[Through his teeth] Moron!! [quickly gets a hold of himself] So, you lost }
{131}{}{$ of profit. Who's is going to get them back?}
{132}{}{No problem, I'll pay it out of my own wallet. Here: }
{133}{}{$.}
{134}{}{I'm not gonna pay for anything!}
{135}{}{I don't have that kind of money!}
{136}{}{Yeah, I can see that! How could I even think you were right for the job?! Ugh... Get out!}
{137}{}{You don't...}
{138}{}{Really? Is that honesty or stupidity? Well, if you're gonna pay for your screw-up, then I've got no problems. [counts the money] I should also get extra from you for crippling our reputation, but since you were honest, I'll let you off the hook.}
{139}{}{Security! Security! Pat this motherfucker down for money and throw him out on the streets! Come on! Quickly, before he gets away!}
{140}{}{Uh-oh...}
{141}{}{Great. You delivered three pizzas. That's }
{142}{}{30$ for the cafe. Hand over the money. Keep the tip, of course.}
{143}{}{[Hand over the profits]}
{144}{}{I, err, I'll bring them right now.}
{145}{}{A fine job, courier! You know, there were some positive reviews of your work. Someone even hired our kitchen for a party, talking about your service. So, other than thanking you, I should pay you 10$ extra. You can rest for now, there are no more orders... Oh yeah, since you're one of our own, you'll get a 20% discount any time you eat here.}
{146}{}{Good job, courier! Good job. You know, you even got some good reviews. Unfortunately we don't have any more orders, so there's nothing to keep you busy. You can go now, thanks.}
{147}{}{I'd congratulate you on a job well done, but some of the clients left a negative review. I warned you that being a courier is a delicate job. You are the face of the company, not just two legs running. I mean, I get it - to the clients you are nobody, no one takes you seriously, they try to mock you. Happens all the time. But we need couriers who can keep to the standards, even in the face of mockery. Now, let me work.}
{148}{}{Take care.}

#Arcade Machine:
{150}{}{One of the arcade machines doesn't work.}
{151}{}{Yeah, I know. We're looking for someone to repair it, but haven't found anyone yet. The machines break pretty often, and we can usually fix them pretty quick. But, as far as I'm aware, that one's fried. Big time.}
{152}{}{Why do they break so often?}
{153}{}{The players tend to push them to the limit. The old tech just can't handle it - the machines overheat, the wiring burns, something gets jammed. Seems to me, that they were like that even before the war.}
{154}{}{Maybe I could fix it?}
{155}{}{Maybe. See what you can do. If you fix it, there's 300 bucks in it for you.}
{156}{}{Alright, I'll go see what I can do.}
{157}{}{Alright, enough about the machines.}
{158}{}{I managed to repair the machine. It wasn't easy.}
{159}{}{Great! Work like that deserves a reward. Here, as promised, 300$}

#Random floating dialogue:
{200}{}{One rot gut, coming right up...}
{201}{}{That will be three bucks...}
{202}{}{Another one, friend?}
{203}{}{Don't touch Suzie!}
{204}{}{Hey, you can't belch here! Belches and other gasses go outside!}
{205}{}{Two half-ounce bags or a tin?}
{206}{}{Special order for a Chris right here...}
{207}{}{Let me guess, you want me to put it on your tab?}
{208}{}{One "dive bomb" with ice.}

#Starting tree
{230}{}{How about a hot pizza?}
{231}{}{Let me see that menu.}
{232}{}{No thanks.}

#Dialogue
{233}{}{What's that plant?}
{234}{}{Desert lily. I bought it from some caravaneers. I'm hoping it's gonna bear fruit, but someone keeps picking it clean before I can get anything. So, really, just keeping it for decoration.}
{235}{}{Got it.}
{236}{}{Oh! This is pizza?! I haven't seen that before.}
{237}{}{Yes, it's our special dish. Pizza with mushrooms and gecko meat. Goes really well with Nuka-Cola. I'll certainly recommend trying some, you won't regret it!}
{238}{}{I guess I'll try some.}
{239}{}{I've got another question.}
{240}{}{Cute waitress! Bet she has no problems with the guys.}
{241}{}{She's precious. The kid had a hard childhood. She... How should I put it, is afraid of representatives of the... Stronger gender.}
{242}{}{Is that so? Any reason?}
{243}{}{[Shrugs] I have no idea. But we need to be gentle with her.}
{244}{}{Alright, I've got a few more questions.}

#Bikers
{245}{}{Hey friend, tell me, do bikers come around often?}
{246}{}{Depends. At times, you don't see 'em for months, and other times they don't leave the city for weeks. They're free people and don't follow a schedule.}
{247}{}{Do you know how I can find them?}
{248}{}{Well, caravaneers from Salt Lake say that they often see them on this highway. I think their base is somewhere up north.}
{249}{}{What does Salt Lake City have to do with this?}
{250}{}{They're fanatics for technology. Particularly stuff on wheels. Salt Lake had lots of factories, it was a huge industrial center before the War, I think.}
{251}{}{Other than tech, they like young girls, don't they?}
{252}{}{Well of course. And girls are crazy for leather-clad men with shiny guns and motorcycles... Especially young ones.}
{253}{}{Well, thanks for nothing! Guess I'll have to figure things out on my own.}
{254}{}{Thanks for the help! Might be useful.}

#About the stage
{255}{}{Why's the stage so empty?}
{256}{}{It's hard to find musicians in our times - people don't have time for music. We usually just put on the jukebox.}
{257}{}{What if I find a musician for you?}
{258}{}{You know, if Sam Phillips was here, you'd have to take a long time trying to convince him - he's totally disappointed in musicians today. But, the boss isn't here anymore, so bring your friend and we can hear him out. No promises - it all depends on how good he is.}
{259}{}{Of course, I'll do exactly that.}
{260}{}{If you have a suggestion, talk to Sam Phillips. But, I'll tell you now - he doesn't trust those who want to perform on stage after a series of unfortunate events. He even *personally* checked every worker of this cafe.}
{261}{}{Got it.}

#Cola Sale
{262}{}{I'm an official Nuka-Cola supplier...}
{263}{}{Err, no! Don't even start! We've got fooled by your "product" more than once.}
{264}{}{What do you mean?!}
{265}{}{I've no idea who sells that shit, but after anyone tries to drink it, their stomach starts doing backflips all day.}
{266}{}{That's exactly why we need to work together!}
{267}{}{Why's that?}
{268}{}{Because I'm a courier from a Nuka-Cola factory in Salt Lake. No middlemen! The real stuff! Here's my documents.}
{269}{}{Because I work without middlemen. The real stuff!}
{270}{}{Because my product is the cleanest. The real deal.}
{271}{}{Because nobody can compare to me in trading skill! Only the best for my clients!}
{272}{}{I heard that already. No thanks.}
{273}{}{I've got proof - here's my official documents.}
{274}{}{What a shame.}
{275}{}{Well that changes things! Great, but I can't make decisions like that. Come, I'll show you to my boss.}
{276}{}{Alright.}

{277}{}{Yes, I remember. I'd be happy to sign the agreement, but Sam Phillips, my boss, likes to make decisions like that personally.}
{278}{}{Understood.}

{279}{}{Yes, I remember but... Sam isn't with us anymore, so I'll risk making the deal without him.}
{280}{}{So you agree?!}
{281}{}{Absolutely! I always told Phillips that we should, but he always said something about it being too hard to get deliveries from Salt Lake. But the competition doesn't sleep - they've got reliable supplies.}
{282}{}{Well, now we can sign the agreement...}
{283}{}{Exactly! You know, I remember the "Monte" casino has a vending machine. It would be sweet to get one set up, so we can sell the product without bothering each other. I'll try and figure that out in the next few days, while you handle the deliveries.}
{284}{}{Perfect, a pleasure doing business with you!}
{285}{}{Hm, Sam isn't with us anymore, and I wouldn't risk such a deal without him.}

#Asking to see Phillips
{290}{}{I need to see your boss.}
{291}{}{Of course. Follow me.}
{292}{}{Thank you.}

{293}{}{Sam Phillips is in his office. I can show you to him through the kitchen if you really need to see my boss.}
{294}{}{Yes I do. Take me to him, please.}
{295}{}{Not yet, I'll be back later.}

{296}{}{How's the new addition to the cultural programme?}
{297}{}{Wonderful. Your man didn't lose his touch. We had a few problems at first, but everything's fine now. He brings in good money, enticing some rather rich clients.}
{298}{}{Does he play here all the time?}
{299}{}{Of course not. He usually comes in during evenings, when some of the more well-off clients come with their wives after work, so they can unwind for a bit. That's when our new, shining star appears on stage... And everyone gets ecstatic!}

#Female version
{1236}{}{Whoah! This is pizza? I haven't seen this before.}	