{100}{}{You see Bob.}
{101}{}{You see a caravan merchant with a very important look. He obviously thinks too much of himself.}

#Стартовая ветка
{110}{}{What do you want?}
{111}{}{Are you that Bob, who delivers the goods for "Monte" and "Hard Rock"?}
{112}{}{Nothing.}
{113}{}{I only do wholesale, sorry, pal.}
{114}{}{Dickhead, I'm not here to buy! Tell me, why did you snitch on the cafe owner?!}
{115}{}{I'm not here to buy. Have you heard that the police tries to imprison the cafe owner?}
{116}{}{Well, bye then.}

#Получение эмульгатора
{117}{}{Snitch?! How dare you to accuse me! Me and Sam are old pals!}
{118}{}{You're lying! Answer, you son of a bitch!}
{119}{}{Whoa, okay, maybe I made a mistake. Do you know anything about what happened?}
{120}{}{That's it cowboy! Piss off, or me and my guys will throw you out of the parking lot!}
{121}{}{Why so nervous? Are you involved in this after all? Maybe you will think faster without oxygen. [grab him by the throat]}
{122}{}{Ha, some fight in this one! Fine, I will leave you alone for now.}
{123}{}{I don't know anything! Now piss off or me and my guys will throw you off the parking lot!}

{124}{}{Phillips - to prison?! Damn... I didn't know. For what?}
{125}{}{You lie! Confess, why did you rat on him!?}
{126}{}{For spreading a poison, from which people died.}
{127}{}{Bullshit! He would never do that!.. Wait, if by "poison" they mean additive supplement emulsifier E30, then...}
{128}{}{Aha! I knew it! Go on, spit it out, you did rat him out didn't you!?}
{129}{}{What is this? Looks like some chemical component.}
{130}{}{Sam uses this emulsifier in cooking. Probably, he knows what he's doing. But not me. I only deliver the substance from Salt Lake - they extract this stuff from the bottom of lake, enriching it with something in the process... Hell, I have an agreement with him on the supply of this thing for the next six months!}
{131}{}{What agreement? Do you have the contract?}
{132}{}{Can you die from it?}
{133}{}{Yeah. It seems you won't help. Bye.}
{134}{}{Well, no, the worst case scenario is explosion of your butt on the toilet for a day, if you eat too much. But honestly, this stuff stinks worse than stale Nuka-Cola. We even fend off geckos with it.}
{135}{}{No, of course. Why? Sam just gives me a list of what he needs, and I try to supply it. That's all.}
{136}{}{Can you give me some to take a look?}
{137}{}{Well, you know... It's not so easy to get... Look...}
{138}{}{Oh, come on! Just a small piece! You won't lose much, will you?}
{139}{}{Fine. How much for a small piece? 10 bucks is enough?}
{140}{}{What a stingy one! I think I'll get out of here.}

{141}{}{Well, just one small piece... Okay, here, take it. [he pulls out the bag something yellow and crumbling, wraps it in paper and gives to you.]}
{142}{}{Thanks. It really does stink, worse than brahmin shit...}
{143}{}{You know, it may be cheap, but I don't do hand-outs. Give me 10 bucks and everyone's happy.}
{144}{}{Here, take your 10 bucks.}
{145}{}{You got evidence against Sam Phillips. Or proof of his innocence. Or maybe just a piece of junk, who knows.}

#Female character
{1113}{}{I only do wholesale, sorry gal.}
{1119}{}{Whoa, okay, maybe I made a mistake. Do you know anything about what happened?}
{1120}{}{Okay! That's it cowgirl! Piss off, or me and my guys will throw you out of the parking lot!}
{1128}{}{Aha! I knew it! Go on, spit it out! You did rat on him, didn't you!?}
