{100}{}{You see a bored visitor.}
{101}{}{You see a visitor with a sad look.}

{110}{}{Hello. Are you here for some booze, too?}
{111}{}{Maybe. What are you doing here?}
{112}{}{Why do you look sour?}
{113}{}{Yeah, why do you care?}
{114}{}{No, I was just passing by.}

{115}{}{Well, I thought maybe you'd join my company, but since you don't want to...}
{116}{}{Ah, that. Sure, here's five bucks for a beer.}
{117}{}{Not this time.}
{118}{}{Let me see... Uh... Oh, I guess I'm just sad and don't have anyone to drink with.}
{119}{}{I see. Well, I'll leave you to it.}
{120}{}{I'm trying to get drunk and forget everything and everybody, can't you see?}
{121}{}{Let me get you a drink. Hey, bartender! Here's 10 bucks for a beer for my friend!}
{122}{}{Here is a beer, help yourself.}
{123}{}{Then let me get you a beer from my supply.}
{124}{}{Well, then have a beer from my supply.}

{125}{}{Thanks, buddy. It's nice to see such friendly people in this place.}
{126}{}{What's with the sour look?}
{127}{}{You could at least try to look happy.}
{128}{}{I'm sorry, I'm just sad. Sometimes I come here to honor my best friend.}
{129}{}{What happened to him?}
{130}{}{He was quite the athlete, moved by the idea of a healthy lifestyle! Day after day he trained hard, wore clean underwear, and even brushed his teeth.}
{131}{}{He must be a good guy.}
{132}{}{He didn't have anything else to do, did he?}
{133}{}{Well, it would be all nice if one day he didn't read the poster with the pre-war advertising. It said that the use of radium water is good for the body. Here it is. [gives you a small bottle with clear liquid] He found a whole box of this filth and drank 3 bottles a day... Until he died from poisoning.}
{134}{}{How sad and strange...}
{135}{}{What a ridiculous death!}
{136}{}{Yes, it is. It turned out that radium water is quite a toxic thing. Poor Byers, who could have known that people before the war were so stupid....}
{137}{}{It's a sad story, my friend. I'm sorry.}
{138}{}{Damn right they were. A big crowd of idiots.}
{139}{}{Let's drink for the deceased, that is all we can do now.}
{140}{}{Sure, let's drink!}
{141}{}{Okay, I'm probably boring you already. Thank you for listening. And for the beer too. You're a good person.}
{142}{}{Okay, I'm probably boring you already. Thank you for listening. And for the beer too. Don't know what you have in mind, but I like you.}
{143}{}{Yeah, bye.}

#Жен реплики
{1110}{}{Hello. Are you here for some booze, too?}
{1114}{}{No, I was just passing by.}
{1115}{}{Well, I thought maybe you'd join my company, but since you don't want to...}
{1125}{}{Thanks, girl. Nice to see such friendly people in this place.}
{1141}{}{Okay, I'm probably boring you already. Thank you for listening. And for the beer too. You're a good person.}
{1142}{}{Okay, I'm probably boring you already. Thank you for listening. And for the beer too. Don't know what you have in mind, but I like you.}