{100}{}{You see a visitor.}
{101}{}{You see a cafe client.}
{102}{}{Don't you see that I'm eating?}

#Random floating phrases when the scene is empty:
{110}{}{Vegas is a mad city.}
{111}{}{I was lucky to settle here.}
{112}{}{A few days more and I'm broke.}
{113}{}{Finding a job in the city is like skinning a Gecko alive.}
{114}{}{Whew! So much pepper...}
{115}{}{Your pizza is nuclear!}
{116}{}{Is this toilet paper?.. Oh, the bill...}
{117}{}{When's the next show, chief?}
{118}{}{Hey chief! Come on, we need music!}
{119}{}{The stage's been empty for a long time.}
{120}{}{Waiter! The bill!}
{121}{}{Waiter! Beer! Come on, move it!}
{122}{}{Waiter! Menu!}
{123}{}{Service is much better at "Monte".}
{124}{}{Caravaneers became frequent visitors in here.}
{125}{}{The city gets larger and larger.}
{126}{}{The city has nowhere to grow, but people are still arriving.}
{127}{}{I'm not going anywhere while they still sell pizza here !}
{128}{}{I only come here for the pizza.}
{129}{}{I would like to see a good gig.}

#Random floating phrases when there's performance at the scene:
{150}{}{Vegas is a mad city.}
{151}{}{I was lucky to settle here.}
{152}{}{A few more days and I'm broke.}
{153}{}{Finding a job in the city is like skinning a Gecko alive.}
{154}{}{Whew! So much pepper...}
{155}{}{Your pizza is nuclear!}
{156}{}{Is this a toilet paper?.. Oh, this is a bill.}
{157}{}{This big guy is a real man!}
{158}{}{I'm yet to hear a more delirious thing than this.}
{159}{}{What's he singing about?}
{160}{}{Waiter! The bill!}
{161}{}{Waiter! Beer! Come on, move it!}
{162}{}{Waiter! Menu!}
{163}{}{Service is much better at "Monte".}
{164}{}{I don't understand, what is this black guy singing about?!}
{165}{}{The city gets larger and larger.}
{166}{}{The city has nowhere to grow, but people are still arriving.}
{167}{}{While the stage is occupied I'm not going anywhere!}
{168}{}{I came here just for the concert.}
{169}{}{I don't mind the money spent on this concert one bit.}
{170}{}{I think this goon has no ear for music... But I like it!}
{171}{}{Hey, on the stage! Start the party!}
{172}{}{Hey, on the stage! Give us our favorite!}
{173}{}{Man, I'd dance while you sing!}
{174}{}{::burp::}
{175}{}{Yahoo!}
{176}{}{C'mon!}
{177}{}{Rock on, big boy!}

#Indignation of the audience when the char appears on the stage during the performance of Big Louie 
{180}{}{Hey, we actually came to listen to Louie!}
{181}{}{And who is this?}
{182}{}{I thought Louie performs solo?}
{183}{}{Hey, who let the clown on stage?}
{184}{}{So, is it jazz or porn?}
{185}{}{The cracker and the nigger on the same stage? Wild.}
