{100}{}{You see a guard.}
{101}{}{You see a guard. He looks exactly like the other ones.}
{102}{}{}
{103}{}{He's waiting for you.}
{104}{}{Alarm!}

#Äèàëîã, êîãäà Óáåæèùå çàõâà÷åíî Àíêëàâîì
{110}{}{Stop! Colonel wants to see you. Follow me and don't try anything stupid.}
{111}{}{How dare you try and stop me! I will wreck you for this!}
{112}{}{Fine, I'll go talk to this... Colonel.}
{113}{}{I have a few questions first.}
{114}{}{The Colonel will answer them, if he considers it necessary. Follow me.}
{115}{}{No way! You won't fool me this time! GO FUCK YOURSELF!}

#Äèàëîã, êîãäà Óáåæèùå çàõâà÷åíî Ñîáèðà'åëåì èëè èì æå â 'åëå Ñìî'ðè'åëÿ
{120}{}{Stop! Boss wants to see you. Follow me and don't try anything stupid.}
{121}{}{Damn clone, How dare you try to stop me! I will wreck you for this!}
{122}{}{Fine, I'll go talk to your boss...}
{123}{}{I have some questions first.}
{124}{}{He will answer them himself. Follow me.}
{125}{}{No way! You won't fool me this time! GO FUCK YOURSELF!}

#Ïîâ'îðíûé äèàëîã
{130}{}{Stop! You have no business in the vault until you bring back the device.}
{131}{}{I'll return with it then.}
{132}{}{Take me to your boss. I need to speak to him.}
{133}{}{I didn't ask your permission. I go wherever I want to go! [Attack]}
