{100}{}{You see: a guard.}
{101}{}{You see: a guard of your city. He wears shades.}

#Первые реплики
{110}{}{You're too late! Do you even realize it?! What are we going to do now?!}
{111}{}{Wait. Tell me exactly what happened.}
{112}{}{I'll think of something.}

#Вопросы
{113}{}{They came from the shadows, like appeared out of nowhere! Then every one of ours had this seizure, all at the same time! And then they went into the vault. Now it's under their control.}
{114}{}{What about our civilians?}
{115}{}{Where is the head of security?}
{116}{}{How many are they in the vault?}
{117}{}{Who are they?}
{118}{}{And you are just standing here doing nothing?! You're useless!}
{119}{}{Fine, I'll think of something.}

#Ответы
{120}{}{We took them to the mountains, to a safe place, far away from here. These nights will be like a nightmare for them.}
{121}{}{Right.}
{122}{}{Sergeant Graves is in the vault. He went there and never came back. He won't respond on the radio. I think, we lost him... For good.}
{123}{}{Whole squad, couple a dozens of men, I'm not sure how many exactly, but they took two floors and got to the Overseer's post. Complete disaster.}
{124}{}{And what CAN we do?! We hadn't even been taught how to shoot properly! Lot of us saw death for the first time in our life... Shit, I think I'm going to be sick!}
{125}{}{Just a big gang of raiders. that's all.}
{126}{}{I can't even tell if they are humans or not. They all look the same, just like a copy of each other. And their leader... Is some ripped off head in a jar! What is going on?!}
{127}{}{I can't even tell if they are humans or not. They all look the same, just like a copy of each other. And their leader... Looks exactly like our Overseer! I can't believe it. Could the Overseer betray us?! Why he attacked the vault?! Why?!!!}
{128}{}{I can't even tell if they are humans or not. They all look the same, just like a copy of each other. And their leader... With a bag on his head, a bunch of cables hanging out. I can't even tell, is he alive or he's a robot. You better not mess with him, believe me.}

#Female character:
{1110}{}{You're too late! Do you even realize it?! What are we going to do now?!}
