{100}{}{You see a colonel.}
{101}{}{You see a commander of the assault team. He's here not for a party.}

#Диалог
{110}{}{Well, well. Here comes the one responsible for all that happened. Just in time. It's good that we didn't have to chase you all over the state.}
{111}{}{Me? You must be mistaken. Who are you people?}
{112}{}{*I* will ask question here! I am colonel Knight. Now I'm in charge. Your action in the wastes caused quite a fuss, we'll have to do a lot of work to fix everything.}
{113}{}{Colonel... How uncommon these days.}
{114}{}{[Contemptuously] You monkey... How such a pitiful thing like you could make so much trouble? You weren't created for this. Ha, even back at the base everyone believes, that their "health insurance" does not have any ability to realize their existence, not to mention talk and think for themselves.} 
{115}{}{"Health insurance"? Is this how you people call us?}

{116}{}{Yes, we do, and this is what you are. Still have troubles believing it? How unfortunate. I started to hope that you'll say something meaningful, but your brain is too small for this.}
{117}{}{[Next]}
{118}{}{Now let's get down to business. We know that Bayham wanted to get his hands on the ACS component, but was unable to do it, thanks to you. At one hand, I'm grateful. We couldn't deal with that son of a bitch by ourselves. Anyway, he thought a hell of too much of himself. If he would seize control of the cloning facility, then Nevada would become his empire.}
{119}{}{[Next]}
{120}{}{But now he's out of the picture, you're here and you can return the component where it belongs. Hand it over. You don't have a choice anyway.}
{121}{}{There's always a choice. I can destroy the device and the whole base with it and stop the cloning process forever.}
{122}{}{I would anyway, but what are you going to do?}
{123}{}{Destroy? Ha! Your brain is not suited to handle such a complicated task. The device that you're hiding is basically a hard drive structurally based on refractory crystals. Do you even UNDERSTAND what REFRACTORY means? In order to destroy it, you need a temperature level you can get only in a lab with proper equipment. Just hand it over - and everything will be fine.}
{124}{}{Every other subject like you have been isolated, just as they should be. We'll leave some of our personnel here to control the situation in the vault. Discipline and order - that's the thing that is needed the most in your little undeveloped zoo.}
{125}{}{I don't have the component.}
{126}{}{Fine, I'll bring the component.}
{127}{}{You don't have it? Then find it and bring it to me, you stupid creature!}
{128}{}{[Leave]}
{129}{}{You made the right choice. We'll be watching you. Don't try to be a hero and disobey us - and no one is going to suffer. You don't want to SUFFER, do you?}
{130}{}{[Leave]}
{131}{}{You call yourself a colonel, but you look and talk like a hillbilly in the bar.}

{160}{}{Bring me that device, before I lose my patience entirely.}
{161}{}{I have the device. Take it and leave me alone.}
{162}{}{I brought you something better - a bullet in your stupid head. Take it and sign below!}
{163}{}{I will do as you asked.}

{164}{}{Smart choice. You just made it a little easier on yourself...}
{165}{}{[End]}

{1162}{}{I brought you something better - a bullet in your stupid head. Take it and sign below!}
