{100}{}{You see a colonel.}
{101}{}{You see a commander of the assault team. He's not here to party.}

#Диалог
{110}{}{Well, well. Here comes the one responsible for all that happened. Just in time. It's good that we didn't have to chase you all over the state.}
{111}{}{Me? You must be mistaken. Who are you people?}
{112}{}{I'm asking the questions here! I am Colonel Knight of the United States Government Armed Forces. Now I'm in charge. Your actions in the wasteland, and especially in the government vault, have caused quite a stir. We'll have to do a lot of work to fix the situation.}
{113}{}{A colonel... What an uncommon thing these days.}
{114}{}{[Contemptuously] You monkey... How could such a pitiful thing like you make so much trouble? You weren't created for this. Ha, even at the base everyone believes their "health insurance" has no ability to comprehend their existence, let alone speak and think for themselves.}
{115}{}{"Health insurance"? Is this how you call us?}

{116}{}{Yes, we do, and that's what you are. Still have trouble accepting it? That's a shame. I was beginning to hope that you would say something meaningful, but it seems that your brain is too small for that.}
{117}{}{What do you want?}
{118}{}{Right, let's get down to business. We know that Bayham tried to get his hands on the ACS component, but was unable to do it, thanks to you. On the one hand, I'm grateful. We couldn't handle the son of a bitch, despite him having a damn high opinion of himself. If he had seized the control of the cloning facility, Nevada would have become his playground.}
{119}{}{And?}
{120}{}{But now he's out of the picture, you're here and you can return the component where it belongs. Hand it over. You don't have a choice anyway.}
{121}{}{There's always a choice. I can destroy the device and the whole base with it and stop the cloning process forever.}
{122}{}{I would anyway, but what are you going to do?}
{123}{}{Destroy? Ha! Your brain is not suited to handle such a complicated task. The device that you're hiding is a hard drive structurally based on refractory crystals. Do you even UNDERSTAND what REFRACTORY means? In order to destroy it, you need a temperature level you can get only in a lab with proper equipment. Just hand it over - and everything will be fine.}
{124}{}{All other subjects like you have been isolated, as they should have been from the start. We will leave some of our personnel here to control the situation. Your Overseer is dead, which means that the deal we had with him is off... It was just a bad joke, anyway. Discipline and order - that is the thing most needed in your little underdeveloped zoo. And that's the way it's going to be from now on.}
{125}{}{I don't have the component.}
{126}{}{Fine, I'll bring the component.}
{127}{}{You don't have it? Then find it and bring it to me, you stupid creature!}
{128}{}{[Leave]}
{129}{}{You made the right choice. We will be watching you. Don't try to be a hero and disobey us, and no one will get hurt. You don't want to get hurt, do you?}
{130}{}{[Leave]}
{131}{}{You call yourself a colonel, but you look and talk like a hillbilly in the bar.}

{160}{}{Bring me that device before I completely lose my patience.}
{161}{}{I have the device. Take it and leave me alone.}
{162}{}{I brought you something better - a bullet in your stupid head. Take it and sign below!}
{163}{}{I will do what you ask.}

{164}{}{Smart Choice. You just made it a little easier for yourself...}
{165}{}{[End]}

{1162}{}{I brought you something better - a bullet in your stupid head. Take it and sign below!}
