{100}{}{You see Reaper of Souls.}
{101}{}{You see a reaper of "pure souls".}

{104}{}{Shit! This bastard grew his body parts back!}

{105}{}{Uhh... Regeneration!!!}
{106}{}{Arhhh... Regeneration!!!}
{107}{}{I'm getting weaker... Regeneration!!!}
{108}{}{How did he do that?!...}

#Äèàëîã
{109}{}{No negotiations! You are going to DIE!}
{110}{}{Stop. You'd better hear me out.}
{111}{}{You think? Previously, you wanted to kill me.}
{112}{}{I underestimated you. I think we can talk about this.}
{113}{}{Are you offering me a deal?}
{114}{}{I'm offering you a choice. You can either participate or join the rest of your herd.}
{115}{}{Okay... Start talking.}
{116}{}{You already know the truth. You all were just meat cattle for medical needs. "Health insurance products". Every person living in Vault 8 was to be used to save the life of someone important in the U.S. government. They would continue to take more and more lives from the Vault, regardless of the actions of your arbitrary little Committee.}
{117}{}{I find it hard to believe you're working for the government now.}
{118}{}{My priorities changed. From the day when the governmental vault went empty, I played my own game. [He raises his hand, made of different pieces of skin fused together] As you can see, I have been making some progress. And with the technology of this place... You can't even imagine. People are too fragile to survive in this world by themselves, and you understand that. You have seen this world and its harshness, you have witnessed what became of humanity. So tell me, what would you do to save your people? Are you capable of making hard choices without regret? Would you go against the opinion of others, if that is what's best for them?}
{119}{}{I would do whatever it takes. I'm ready to take the responsibility for every hard decision. I care about my people - and I know what to do.}
{120}{}{People can decide themselves what's best for them. It's their choice, not someone else's. I just do what I have to do.}
{121}{}{I don't give a shit about what you call "my people". I don't belong to them. All they gave me was the boot, so I could care less.}

{122}{}{Then maybe you will be able to understand what I'm trying to achieve. Seems like you have enough experience to know that the majority can be wrong, and that a single person can make a difference.}
{123}{}{Then maybe you will be able to understand what I'm trying to achieve... Although, I really doubt you are experienced enough to comprehend it. You power level is so low that you can't even compete with small-time Reno gangsters. Still, your determination is admirable.}

{124}{}{Strange... You've spent a lot of time traveling. You have seen all this suffering. You have been cast out of your own city, betrayed by your own people. And yet you have not lost your intention to help them... I expected the opposite.}
{125}{}{Don't lie to yourself. I know your hands are as dirty as those of the petty hooligan from New Reno. More than once you have taken matters into your own hands, changing the order of things, influencing people's decisions and the course of events. All for what you think is right.}

{126}{}{You sound... disappointed. It will be easier for us to come to an agreement then.}
{127}{}{It makes it even easier for us to come to an agreement then. You may not understand my intentions, but I don't really care at this point.}

{128}{}{[Next]}

{129}{}{Strange... You've spent a lot of time traveling. You have seen all this suffering. You have been cast out of your own city, betrayed by your own people. And yet you have not lost your intention to help them... I expected the opposite. Maybe I'm wrong and you haven't learned anything. Believing in illusions is all you can do.}


{130}{}{Think about it: humans are not suited for today's world. We have to adapt, evolve as a species. What if we could live longer without worrying about infection or radiation? What if we could become stronger, smarter? Rebuild the civilization anew, better than before? It can become a reality. All it takes is a few decades of research. The technology of the government vault, along with the equipment of this place, is all I need. That stolen device is not only a key component of the vital systems of your vault, including defense, but also data storage. It contains a vast amount of information about the cloning process and operating this facility.}
{131}{}{That's why you needed the biker to steal it? So you could infiltrate the vault and not become riddled with bullets from the security turrets in the process?}

#Main point 1
{132}{}{Yes. I could neither get in, nor was I able to use the device. The Overseer knew everything I needed to gain access to the device's contents. So I employed the biker. Not everything went smoothly, but in the end I got what I wanted.}
{133}{}{What does that have to do with the vault dwellers? And what are you planning to do with them?}

#Main point 2
{134}{}{The government was too simple in its intentions. They only wanted to prolong their lives instead of becoming better versions of themselves. I recognized the potential, but they didn't listen. They think it sets them apart from everyone else, think that it makes them the only true humans. It is so... Narrow-minded. The cloning facility, combined with government vault technology can be used for something greater than just the creation of substitute bodies, as you can see by my example. Unfortunately, this kind of research requires suitable... material. Bodies not tainted by radiation, sickness, or bad ecology. Pure.}
{135}{}{That's your plan?! To use my people as test subjects for years to come, while you play God in your little sandbox?}
{136}{}{Now I get what you meant by hard choices. To make humanity better at the price of countless lives... I don't know how I feel about this.}
{137}{}{How does the government fit into your plan? Something tells me they won't quite agree with you taking over the vault.}

{138}{}{Are you confused by the price? You have seen for yourself how easily the life of a whole settlement can change. How defenseless people are in the face of external threats - criminals, famine, natural disasters. Even one person can change everything. But things can be different. It's only a matter of time and effort. Any way you look at it, your people shouldn't have existed at all. They were living on borrowed time. Now, at least they will have a chance to contribute to a better future for humanity. Their lives will have meaning.}
{139}{}{Take a broader view of things. At this very moment, thousands of people are dying of starvation, disease or radiation, hundreds of slaves in pens are succumbing to the effects of deadly drugs, gangs of raiders are attacking defenseless settlements. Humanity is too fragile. It needs help. It deserves better.}
{140}{}{I can deal with them. With all the knowledge about the device, I will subdue the Vault's systems to my will. The government wouldn't dare to start a conflict with me in here - especially if I throw them a bone. A couple of bodies once in a while should provide enough for maintaining a truce between us. And when the right time comes, they will no longer be relevant. A new kind of people will march forward.}
{141}{}{[Next]}
{142}{}{This vault will become a birthplace for true humans. A better species. 70 years from now, Nevada will rise again. Trading, culture and economy will bloom. And Vault 8 will be at the center of it. Superior beings, capable of making this world a better place, a new civilization, like none other throughout history... The only thing that's left for you to do is to bring me the device. Then you can either join me, or go. I won't be looking for you.}
{143}{}{Okay, I will do what you ask.}
{144}{}{No. I will destroy the device, so the Vault could be free. My people will do just fine without you.}
{145}{}{I'll better destroy this whole laboratory. These experiments on humans are wrong.}
{146}{}{I'm going to just kill you and put an end to it.}
{147}{}{I'll be waiting.}
{148}{}{I really doubt you will be able to. Anyway, take your time. Think about it. When you are ready, bring it to me. Bring me the device.}
{149}{}{I didn't expect you to understand me right away. But you don't have a choice. Maybe you need some time to think about it. When you do, bring it to me. Bring me the device.}
{150}{}{Those are big words for a loner surrounded by a heavily armed squad. Make it easy on yourself. You die - and I'll have to reassemble your brain piece by piece to find out the location of the device. It's just silly. Do what is asked of you - and you will be free to leave.}
{151}{}{I lived the way I wanted to live. And I will die the way I want. [Attack]}
{152}{}{You are delusional. The one who stands before you will make your delusions disappear. Because I lived the way I wanted to live. And I will die the way I want. [Attack]}
{153}{}{Come to think of it, this "health insurance product" has already done more than you thought it would. Well, let this be the last thing it did. [Attack]}
{154}{}{[Leave]}

{155}{}{Where is the device?}
{156}{}{Somewhere out of your reach.}
{157}{}{It's funny to hear such questions from someone who will soon be nothing more than a corpse! [Attack]}

{160}{}{Bring me what I want while I still have patience.}
{161}{}{I have the device. Take it and leave me alone.}
{162}{}{I brought you something better - a bullet in the head. Take it and sign below!}
{163}{}{I will do what you ask.}

{164}{}{Smart choice. I will find more helpful use for this technology than a bunch of suits inside the government. Now, go. As I said - nobody will stop you.}
{165}{}{[End]}

#Female character:
{1114}{}{No. I'm offering you a choice. You're doomed. Like the rest of this herd.}
{1120}{}{I wanted to make a little peace in this world! I worked hard to give people the best I could. Look, they are desperate, can't even share a piece of bread.}
{1124}{}{Strange... You spent a lot of time traveling. You saw all that suffering. You were cast out of your own city, you were betrayed. And still, you didn't lose all that intentions to make things right? I expected the opposite.}
{1129}{}{Strange... You spent a lot of time traveling. You saw all that suffering. You were cast out of your own city, you were betrayed. And still, you didn't lose all that intentions to make things right? I expected the opposite... But this makes sense - you had very little experience. You still live in a world of illusions.}
{1162}{}{I brought you something better - a bullet in the head. Take it and sign below!}
