{100}{}{You see: reaper of souls.}
{101}{}{You see: a reaper of "pure souls".}

{104}{}{Shit! This bastard grew his body parts back!}

{105}{}{Uhh... Regeneration!!!}
{106}{}{Arhhh... Regeneration!!!}
{107}{}{I'm getting weaker... Regeneration!!!}
{108}{}{How did he do that?!..}

#Диалог
{109}{}{No negotiations! You are going to DIE!}
{110}{}{Stop. You'd better hear me out.}
{111}{}{You think? Previously, you wanted to kill me.}
{112}{}{No. I would benefit more if I had a live product. Even though it would not make a difference for you... I underestimated your mental abilities. I think we can talk about this.}
{113}{}{Are you offering me a deal?}
{114}{}{No. I'm offering you a choice. You're doomed. Like the rest of this herd.}
{115}{}{Okay... Start talking.}
{116}{}{You already know the truth. You were just a meat cattle for medical experimentation. "Pure souls" - bodies, not spoiled by radiation or dirty physical behavior, "health insurance products". Every person living in Vault 8 should have been used to save life of someone important in US government personnel. The nuclear war couldn't affect on it. The convoy kept taking more lives out of the Vault, regardless of your little arbitrary Committee's actions.}
{117}{}{And let me guess, you were a part of that convoy? It's hard to believe, that you are working for the government now.}
{118}{}{My priorities changed. From the day when the governmental vault went empty, I started to play my own little game. [Raises his hand, made of different pieces of skin stitched together] My experiments gave me great results, that could not be achieved even by all prewar medical institutions in America. Imagine the opportunities, that would be open to me, if not for your run all across the country, making trouble. That biker was obsessed with technology, he didn't care about nobody; that I understand. What drove you? The desire to earn your place among the meat cattle, or the urge to prove your true ancient nature, given to you by evolution - to dominate this world? I don't understand that. Tell me.}

{119}{}{Exactly - to dominate everyone. People can't even get organized to sit for a dinner together, if someone doesn't tell them to. They need to be controlled. And I know how to control them.}
{120}{}{I wanted to make a little peace in this world! I worked hard to give people the best I could. Look - they are desperate, can't even share a piece of bread.}
{121}{}{I don't give a shit about humanity. It will take care of itself. I only look for my personal interest.}
{122}{}{Hmm. It seems like you have much experience. I underestimated you once more.}
{123}{}{This is loud talk for a person with so little experience. You power level is so low that you can't even compete with those small-time Reno gangsters.}
{124}{}{Strange... You spent a lot of time traveling. You saw all that suffering. You were cast out of your own city, you were betrayed. And still, you didn't lose all that intentions to make things right? I expected the opposite.}
{125}{}{Perhaps, the Mormons in the Salt Lake city would be more than happy to hear this. Or some lone travelers, lives of which consist of suffering and pain. But you shouldn't lie to yourself. I see you talking about goodness, but your hands are as dirty as of New Reno's two-bit hooligan.}
{126}{}{Seems like so. You're reasonable rational person. It means it'll be possible for us to come to a consensus. You'll understand that your way is wrong.}
{127}{}{This is the words of a wise person. I could even believe you, but something tells me that you're bluffing.}
{128}{}{[Next]}
{129}{}{Strange... You spent a lot of time traveling. You saw all that suffering. You were cast out of your own city, you were betrayed. And still, you didn't lose all that intentions to make things right? I expected the opposite... But this makes sense - you had very little experience. You still live in a world of illusions.}

{130}{}{Even with all that experience, you still remain a "medical insurance product". But you can't be manipulated, unlike everybody else. Obviously, the vault's supervisors decided to let you out of the cage and make you work. The arbitrarily of your Committee had already gone too far when I started to notice changes in systems of the Vault.}
{131}{}{Is that why you needed that device? Did you want a full control over the cloning facility?}
{132}{}{Your supervisors could not only break every rule. They could cause a disaster. The stolen device was made to control all the systems. Total control program was present on it. I wanted to tweak it for my own purposes.}
{133}{}{Was that so necessary?}
{134}{}{Without a doubt. Think about your fellow citizens. They're like children. They know nothing about the outside world, they trust so easily, and they didn't even have any sexual experiences. Their self-awareness is almost non-existent, and their will is so suppressed, that any threat from the outside can wipe them off the face of the earth. Raiders, gangsters, all kinds of power-hungry people, even some biker - anyone can easily leave a mark on vault's evolution history. The local population is not ready for independent lifestyle.}
{135}{}{But there is people like me for such situations. I will teach my people how to live in this world.}
{136}{}{You're right, we should put the clones back and lock them up.}
{137}{}{Why can't we leave them alone? You and I are doing just fine without a vault.}
{138}{}{You just want to change the rules? Believe me, with your intentions it's almost impossible. Above you stands the Committee, and in the minds of citizens is implanted specific behavioral code. And even if you'll make them change, sooner or later the storming squad will come here. The government is still alive, they have army and technology to cover long distances in a short time.}
{139}{}{You're right. But there is one condition - I must have absolute control over the vault. Only I can prevent the threat from the outside and only I can provide total control of the situation inside the vault. Otherwise, the storming squad will come here to reclaim the Vault, sooner or later. The government is still alive, they have army and technology to cover long distances in a short time.}
{140}{}{I can't pass down such a fine cloning facility. I need it. People will need it in the future. I made some calculations - in 70 years from now on, the civilization of Nevada will rise again. Trading will be restored, along with the culture and economy. And the Vault 8 could be in the center of it. This is our chance for a new civilization. A civilization, like none other throughout history.}
{141}{}{[Next]}
{142}{}{The only thing you should do is to bring the device back to me. I will let you go. Your body is not needed, and you won't interfere with my plan. I won't be looking for you.}
{143}{}{Okay, I will bring you the device.}
{144}{}{No. I will destroy the device, so the Vault could be free. I will teach my people to live anew, have no doubt about it.}
{145}{}{I'll destroy the whole laboratory. Such an abominations should not exist in your so-called civilization!}
{146}{}{I'll just kill you, and that will be the end of it.}
{147}{}{When you get the device, come down to laboratory. The entrance is right behind me.}
{148}{}{Strange to hear such things from a "medical insurance product". It seems doctor Willmouth outdone himself with sticking his dirty nose inside your brain. I won't allow such.}
{149}{}{One man is nothing. It would be interesting to have a philosophical conversation about this. But not with you.}
{150}{}{This is a loud words for a lone shooter, surrounded by well-armed squad of military personnel. Make it easy on yourself. You'll die - and I will have to reassemble your brain piece by piece, in order to learn the location of the device. Think about it - this is stupid. Do, what you're asked to do - and you can leave freely.}
{151}{}{I live as I want. And I will die - as I want. [Attack]}
{152}{}{Have no doubt. Before you stands the one that will make your delusions disappear. Because I live as I want. And I will die - as I want. [Attack]}
{153}{}{Barely. One "medical insurance product" had already done more than you imagined it would. Well, let this be the last thing it did. [Attack]}
{154}{}{[Leave]}

{155}{}{Where is the device?}
{156}{}{Somewhere out of your reach.}
{157}{}{It's funny to hear such questions from the one, that'll soon be nothing more, than a corpse! [Attack]}

{160}{}{Bring the device, while I still in control of my patience.}
{161}{}{I have the device. Take it and leave me alone.}
{162}{}{I brought you something better - a bullet in the head. Take it and sign below!}
{163}{}{I will do, as you ask.}

{164}{}{Smart choice. I will find more helpful use for this technology, than a bunch of suits inside the government. Now, go. As I said - nobody will stop you.}
{165}{}{[End]}

#Female character:
{1114}{}{No. I'm offering you a choice. You're doomed. Like the rest of this herd.}
{1120}{}{I wanted to make a little peace in this world! I worked hard to give people the best I could. Look, they are desperate, can't even share a piece of bread.}
{1124}{}{Strange... You spent a lot of time traveling. You saw all that suffering. You were cast out of your own city, you were betrayed. And still, you didn't lose all that intentions to make things right? I expected the opposite.}
{1129}{}{Strange... You spent a lot of time traveling. You saw all that suffering. You were cast out of your own city, you were betrayed. And still, you didn't lose all that intentions to make things right? I expected the opposite... But this makes sense - you had very little experience. You still live in a world of illusions.}
{1162}{}{I brought you something better - a bullet in the head. Take it and sign below!}
