{100}{}{You see a teenager.}
{101}{}{You see a thief.}
{102}{}{Here is a young man about fourteen years old.}
{103}{}{ }
{104}{}{Thanks}

{110}{}{[You see a gloomy boy; he tries to be as unnoticeable as possible]}
{111}{}{Hey, boy! Come here...}
{112}{}{[The boy doesn't even look in your direction, as if he doesn't hear]}
{113}{}{Hey, I'm talking to you!}
{114}{}{[By your approach the child suddenly starts running]}
{115}{}{Hey, stop! What are doing, you silly!}
{116}{}{Stop it right there, scrub!}

{120}{}{Ahh! Let me go! You have no right!}
{121}{}{You want cops to notice? I can make that happen.}
{122}{}{[Calms down and lowers his head]}
{123}{}{Great. Now tell me, why the hell are you running from me?}
{124}{}{[Stays silent]}
{125}{}{Well?}
{126}{}{[Mumbles something lamentable]}
{127}{}{Okay. I get it. Let's go to the station...}
{128}{}{Don't worry, tell me the truth, I will try my best to help you.}
{129}{}{Well - will you speak or I should take more serious measures?}
{130}{}{I thought you came after me, that's why I ran.}
{131}{}{This means, someone watches you? Why is that?}

{132}{}{[Hesitates]}
{133}{}{Answer already, street scrub! I don't play games here!}
{134}{}{You can tell me, I don't hurt children. I have a rule, you know.}
{135}{}{You don't have much of a choice - either you tell me, or you tell it to the police.}

{136}{}{He'll kill me, if I tell! And you too. Maybe even someone else. Let me go, I will just disappear from here, I promise!}
{137}{}{Oh, no. You will have to tell me everything.}
{138}{}{I see, you didn't understand. Okay, I will have to put you behind bars.}
{139}{}{Not to the police! Please! [instinctively presses his hands on pockets]}
{140}{}{What do you have there? Oh, stolen trinkets? Now I get why you ran. You chose a dangerous spot to work, buddy.}
{141}{}{I never did this before! It's the truth! I don't want to steal, I'm local, from the Clean City... If my parent were alive... [Imitates cry]}
{142}{}{Don't even try this on me. Who were you talking about?}
{143}{}{Hey, wait. I know the underground pretty well. It doesn't look, that you're here just by your stupidity. Who makes you do this?}
{144}{}{[Looks up in surprise] So you're too... This means, you won't take me to the cops?}
{145}{}{Well, we'll see. Depends on what you'll say.}
{146}{}{It's Orris, he is one of the Kings. He'll kill me if he finds out! Maybe he has his people around. Or maybe he has a bug on me and listens through the radio. Kings are bandits. They act like they own the place, they only scared of the Clean City.}
{147}{}{Oh, bandits, how familiar. So how did you end up with them?}

{148}{}{And you let me go [busily pulls out his elbow]. I was born in the Clean City, you know... Then my family died and Orris helped me. If not for him, I would starve to death. Now I have to steal to repay my debt to him. I would never do that, if not for this...}
{149}{}{So that's how it is. And where is this Orris now?}
{150}{}{[Looks at you from the bottom up] Usually he waits for me at "Hard Rock" cafe... Don't tell me you're going to...}
{151}{}{I can defend myself if something happens.}

{152}{}{Well... What now?}
{153}{}{I will have to take you to the police, so you get your lesson.}
{154}{}{You're free to go. I won't keep any longer.}

{155}{}{[The boy ran like crazy in a second]}
{156}{}{Hey, stop!..}
{157}{}{[He speaks quietly, through clenched teeth] Thanks...}
{158}{}{Yeah.}

{159}{}{Give me everything you got stolen and get out, so my eyes didn't see anymore.}
{160}{}{[With a look of cornered calf, he pulls the money out of pockets. You greedily snatch them]}
{161}{}{Wise choice. Now get out of here.}

#После первого разговора
{170}{}{[Sullenly looking at you, looking around, searching any means to escape]}
{171}{}{[Leave]}
{172}{}{Remind me, where you and Orris meet?}
{173}{}{In the evening, in front of the "Hard Rock" cafe. He usually walks with a partner. They can be easily recognized by the leather jackets.}
{174}{}{That is all for now.}

#Завершение квеста
{175}{}{Orris died. Now you don't have to steal, to repay your "debt".}
{176}{}{Really?! Great... Did you do that? I wish I could be like you. Fearless. So I could defend myself... Thank you. I will quit stealing now. I will try to find a job. If I don't... I don't know, what I will do. But I definitely won't steal!}
{177}{}{Good boy.}
{178}{}{Orris forgive your "debt". Now you don't have to steal.}
{179}{}{Really?! Great... Did you do that? If not for you, I would do this for two more years at least, for sure. I wish I was like that - fearless, so I could decide by myself what to do... Thank you. I will quit stealing now. I will try to find a job. If I don't... I don't know, what I will do. But I definitely won't steal!}
