{100}{}{You see a teenager.}
{101}{}{You see a thief.}
{102}{}{You see a young man about fourteen years old.}
{103}{}{ }
{104}{}{Thanks.}

{110}{}{[You see a gloomy boy; he tries very hard not to draw attention to himself.]}
{111}{}{Hey, boy! Come here...}
{112}{}{[The boy doesn't even look in your direction, as if he doesn't hear you.]}
{113}{}{Hey, I'm talking to you!}
{114}{}{[As your approach him, the child suddenly starts running!]}
{115}{}{Hey, stop! What are you doing, silly!}
{116}{}{Stop it right there, runt!}

{120}{}{Ahh! Let me go! You have no right!}
{121}{}{Do you want the cops to notice? I can make that happen.}
{122}{}{[He calms down and lowers his head]}
{123}{}{Great. Now tell me, why the hell are you running from me?}
{124}{}{[The boy stays silent.]}
{125}{}{Well?}
{126}{}{[Mumbles something inaudible]}
{127}{}{Okay. I get it. Let's go to the station...}
{128}{}{Don't worry, you can tell me the truth. I will do my best to help you.}
{129}{}{Well? Are you going to talk, or should I take more serious measures?}
{130}{}{I thought you came after me, that's why I ran.}
{131}{}{Does this mean that someone is after you? Why?}

{132}{}{[He visibly hesitates]}
{133}{}{Answer already, street rat! I'm not playing games here!}
{134}{}{You can tell me, I don't hurt children. I have a rule, you know.}
{135}{}{You don't have much of a choice - either you tell me, or you tell it to the police.}

{136}{}{He'll kill me, if I tell! And you too. Maybe even someone else. Let me go, I will just disappear, I promise!}
{137}{}{Oh, no. You will have to tell me everything.}
{138}{}{I see, you didn't understand. Okay, I will have to put you behind bars.}
{139}{}{Not to the police! Please! [He instinctively puts his hands on his pockets]}
{140}{}{What do you have there? Oh, stolen trinkets? Now I get why you ran. You chose a dangerous spot to work, buddy.}
{141}{}{I never did this before! It's the truth! I didn't want to steal, I'm local, from the Clean City... If only my parent were alive... [Imitates cry]}
{142}{}{Don't even try this on me. Who were you talking about?}
{143}{}{Hey, wait. I know how these things are done. It's not like you're just here because you're stupid. Who makes you do this?}
{144}{}{[Looks up in surprise] So, you're too... Does it mean you won't take me to the cops?}
{145}{}{We'll see. Depends on what you'll say.}
{146}{}{It's Orris, he is one of the Kings. He'll kill me if he finds out! Maybe his people are watching us even now. Or maybe he has a bug on me and listens through the radio. The Kings are criminals. They act like they own the place, they only scared of the Clean City.}
{147}{}{Oh, criminals, how familiar. So how did you end up with them?}

{148}{}{And you let me go [busily pulls out his elbow]. I was born in Clean City, you know... Then my family died and Orris helped me. If not for him, I would starve to death. Now I have to steal to repay my debt to him. I would never do that, if not for this...}
{149}{}{So that's how it is. And where is this Orris now?}
{150}{}{[Looks at you from the bottom up] Usually he hangs out near "Hard Rock" cafe... Don't tell me you're going to...}
{151}{}{I can defend myself if something happens.}

{152}{}{So? What now?}
{153}{}{I have to take you to the police, so you'd get your lesson.}
{154}{}{You're free to go. I won't keep any longer.}

{155}{}{[The boy ran like crazy in a second]}
{156}{}{Hey, stop!...}
{157}{}{[He speaks quietly, through clenched teeth] Thanks...}
{158}{}{Yeah.}

{159}{}{Give me everything you stole and get out. I don't want to see you anymore.}
{160}{}{[With a look of a cornered calf, he pulls the money out of pockets. You greedily snatch them]}
{161}{}{Wise choice. Now get out of here.}

#После первого разговора
{170}{}{[Sullenly looking at you, looking around, searching any means to escape]}
{171}{}{[Leave]}
{172}{}{Remind me, where and when you and Orris usually meet?}
{173}{}{In the evening, in front of the "Hard Rock" cafe. He usually walks with a partner. They are easily recognized by their leather jackets.}
{174}{}{That is all for now.}

#Завершение квеста
{175}{}{Orris died. Now you don't have to steal, to repay your "debt".}
{176}{}{Really?! Great... Did you do that? I wish I could be like you. Fearless. So I could defend myself... Thank you. I will quit stealing now. I will try to find a job. If I won't... I don't know, what I will do. But I definitely won't steal anymore!}
{177}{}{Good boy.}
{178}{}{Orris forgive your "debt". Now you don't have to steal.}
{179}{}{Really?! Great... Did you do that? If not for you, I would do this for two more years at least, for sure. I wish I was like that - fearless, so I could decide by myself what to do... Thank you. I will quit stealing now. I will try to find a job. If I won't... I don't know, what I will do. But I definitely won't steal anymore!}
