{100}{}{You see a policeman.}
{101}{}{You see a suspiciously-looking policeman... What is he doing here?}
{102}{}{Hey, you! It seems like someone flew too high. Isn't it the time to get down to earth a little?}
{103}{}{It's finished... But why this policeman attacked you?!}
{104}{}{Eat it, damned cop!}

{110}{}{Hold it right there, damn it!}
{111}{}{Wow! A cop that is looking for trouble?}
{112}{}{Don't shoot, I didn't do anything wrong!}

{113}{}{That's what everyone says... And everyone lies. I learned that well, working as a police inspector. I have no problem putting a gun in your mouth and pulling the trigger. That's why Davis makes me do it. So - can you at least tell me what the hell is going on?}
{114}{}{He wants to kill me?! I don't know anything about that!}
{115}{}{Well, he's not the first who wanted to kill me, so I don't really care.}

{116}{}{Tough guy, huh? But in Vegas, no one would put out a hit on a man for no reason. I have orders, you know... From the chief of police himself...}
{117}{}{Don't be stupid, why would you do it? What for?!}

{118}{}{Oh... Okay, suppose, it is true. But in Vegas, no one would order a hit on a man for no reason. I have an order, you know... From the chief of the police himself...}
{119}{}{Wait, don't be stupid, why would you do it? What for?!}

{120}{}{Nothing personal, pal, I'm just doing my job.}
{121}{}{Wait, don't be stupid, why would you do it? What for?!}
{122}{}{Then it will be your last job, fool! Bring it!}

{123}{}{This is my home. And I want an outworld scum like you to go back to your caves. You only bring drugs, weapons, theft and moral corruption of this city. However, behind me lies a large corrupted system and dubious orders from the authorities. I know that Davis would like to remove me - because I often interrupt a lot of shady business practices, which shouldn't be interrupted. Maybe that's why he is trying to throw me at you. What do you think about it?}
{124}{}{I think that you're a pathetic coward. Let's finish this.}
{125}{}{I know your boss is involved in some dirty business. I'll deal with him soon, and you will no longer be in danger.}
{126}{}{I know your boss is involved in some dirty business. Soon I will bring order to this place, and you will no longer be in danger.}

{127}{}{Then farewell, stranger...}
{128}{}{[Attack]}

{129}{}{If you think about it, people like me - witnesses - are also removed when they become useless. Do you have at least some evidence against Davis?}
{130}{}{I will find some, don't you doubt about that.}
{131}{}{Fuck the evidence, I'm not even going to bother digging through that shit.}
{132}{}{I don't believe you. From the people with such reputation in Vegas, nothing good can be expected. It's time to end this useless conversation... [picks up a weapon]}
{133}{}{[Attack]}

{134}{}{I want to believe you. There's a lot of good talk about you in Vegas. Just try to deal with it quickly - the people behind it might be watching us... One more thing. I'll be patrolling the intersection near the entrance to the "Monte" Casino. But don't talk to me without a good reason. Now I have to go. Good luck.}
{135}{}{I want to believe you. No one heard anything bad about you in Vegas. Just try to deal with it quickly - the people behind it might be watching us... One more thing. I'll be patrolling the intersection near the entrance to the "Monte" Casino. But don't talk to me without a good reason. Now I have to go. Good luck.}
{136}{}{And good luck to you too, Inspector. Thanks for the warning.}
{137}{}{Don't be a pussy, everything will be okay!}

#Жен реплики
{116}{}{Tough bitch, huh? But in Vegas, no one would put out a hit on a woman for no reason. I have orders, you know... From the chief of police himself...}
{1120}{}{Nothing personal, gal, I'm just doing my job.}
{1127}{}{Then farewell, stranger...}
