{100}{}{You see Curtis.}
{101}{}{You see a mechanic with a wrench in his hand. He has quite a puzzled look.}

#Первый диалог
{110}{}{What do you want, pal?}
{111}{}{I'm just stopping by, to see how fellow hard worker is doing.}
{112}{}{Nothing.}
{113}{}{"Fellow hard worker"? Heh! Bad, as always. Do you see this big guy on the floor?}
{114}{}{Robo-cop? Funny...}
{115}{}{Yeah, it is. So many complicated stuff to fix just so he could stand somewhere for intimidation. I'd have better luck wearing this junk on me and scaring the passersby myself.}
{116}{}{Do you think there would be no benefit from it?}
{117}{}{Well, with full ammunition and in normal condition, he is, of course, a real death machine. Perhaps, the chief could use it in special operations. But in general, this piece of hardware is designed to intimidate with its look.}
{118}{}{Do you think he would be dangerous, after the activation?}
{119}{}{Who knows... The military model was not created for peaceful purposes, baby. They were made to KILL! And this robot is lied dormant for, like, 70 years, with no check-ups. Luckily, I came up with taking away his ammunition and disabling lower servomotors, to avoid being killed on the spot when he'll be turned on. But it's the other thing that scares me - not many people can understand this level of robotic tech. So, no one could really tell what's on the mind of this piece of iron. We have to rely on testing and spend a lot of time to study the blueprints. So much effort for one robot! Is it worth it? I'm not sure.}
{120}{}{Does he has any imperfections?}
{121}{}{Of course he has! It's full of electronics. One shot of pulse round - and the circuits will simply fry. It's a common problem for all pre-war build robots.}
{122}{}{Pulse weapons? And where can one find it?}
{123}{}{I suppose, only in some military depots, or in places that are associated with the old army. These things had not been released for civilian market.}

{128}{}{Fine craft. Well, I should go, bye.}
{129}{}{Yeah, see you.}
{130}{}{Good luck.}

#Вопрос о возможнос'и ремон'а
{131}{}{Can you help in repair?}
{132}{}{Listen, I work for the police. The cops won't let me do the work for outsiders, so - sorry, I don't want to lose my job here. I can only recommend a good mechanic at Hoover dam. But he specializes mainly on electronics.}
{133}{}{Okay. Well I won't bother you then.}

#Попы'ка заговори'ь после первого разговора (случайные плавающие фразы)
{150}{}{Hello!}
{151}{}{Hey!}
{152}{}{Oh, it's you...}
{153}{}{Sorry, I'm working...}
{154}{}{What? It's time for break?}

#Машина
{230}{}{Have you seen the car not far from here? My ride. Jealous?}
{231}{}{[Whistles] I would be honored to even touch it! Out of professional interest and technological engagement, so to speak. And you know, if the car is working, then maybe I can hook her up with something - gravity-plates with energocyclic chip! The car won't just ride, it will FLY! Well, figuratively speaking.}
{232}{}{And do you have this... Thing?}
{233}{}{Yeah, it's waiting for its new owner. Of course, I wouldn't mind of payment for my work. The price is 2500, deal?}
{234}{}{Okay, here is the money.}
{235}{}{I don't have cash right now. I'll come back later.}
{236}{}{Then wait for a few hours. I will do everything and come back.}
{237}{}{Okay.}
{238}{}{All done! You can now go on ahead and try it out... Damn, I'm so jealous!}
{239}{}{Oh. Thanks.}
{240}{}{After installing the gravity-plates your car can accelerate to incredible speeds and consume far less energy. Highways of Nevada, tremble!}

#Female character
{1110}{}{And what do you want, gal?}
{1111}{}{I'm just stopping by, to see how the fellow hard worker is doing.}
