{100}{}{You see a prisoner.}
{101}{}{You see a young guy with obviously rebellious disposition.}
{102}{}{The police officer here does not allow you to speak with the prisoner.}

{103}{}{Prisoner dies from the poisoned water.}
{104}{}{*takes the last breath*}

{110}{}{Who sent you?}
{111}{}{I'm here not on someone's tip. I was just wondering how a young man with such a stylish hairstyle could end up behind the bars.}

{112}{}{I was framed! They don't care about whether I stole the money or not, they just need somebody to put the blame on. Fucking pigs...}
{113}{}{Saying you are not guilty? Can you prove it?}

{114}{}{I won the money in casino, fair and square. There should have records about this, but don't think they'll share this information. So, it turns out that I can't prove anything... [lowers his voice] Hey, listen, you're not a cop, right? Can you help me out? My guys will repay you for this.}
{115}{}{Hmm, let me think...}

{116}{}{No time to think, think plenty afterwards... Listen, you need to find my buddy, his name is Orris. Usually he can be found near the "Hard Rock" cafe. Tell him that his old friend Murphy is in trouble, he will understand... He will help... [grabs his head in despair] he... Will help...}
{117}{}{Maybe I'll find and talk to this Orris. But I need to know the details of this story.}
{118}{}{[Leave him]}
{119}{}{I was framed!}
{120}{}{Calm down and tell me the details of this story.}
{121}{}{Remind me, where to find your friend Orris.}
{122}{}{Usually he can be found near the "Hard Rock" cafe. Tell him that his old friend Murphy is in trouble.}

{123}{}{It was like that: I won some in the casino. Not a lot, but you still can have a really good party with that money. When I went outside, the cops kettled me off without any explanation. Then brought me here, then this smart-ass from the mayor's office appeared and outlined how much money I have in my pockets, and in which bills. He knew it for sure, I remember him near the cash register in the casino. He followed me! Now it turns out like I stole these money from him.}
{124}{}{Who is this "smart-ass from the mayor's office"?}
{125}{}{But can't they identify you in the casino?}
{126}{}{Why should I believe you?}
{127}{}{I see. I have to go.}
{128}{}{Some Irwin guy, an employee of the City Hall. Looks like many people here know him, but I don't. I'm from the suburbs, I don't hang out with the locals.}
{129}{}{Surely they can. They write everything down in this ledger book, but the cops don't care, they tend to believe that guy from the mayor's office. And I am sure that casino won't stand up for me. It's more important for them to lick the ass of the City Hall and the cops.}
{130}{}{You? You shouldn't. Why would you care... But I'm not asking you to believe me! I'm asking to talk to Orris, he will help, he's an old friend. And you might have something from it, you understand?}

{131}{}{What's going on?!}
{132}{}{Well, apparently, the police officer in the waiting room is no longer at his duty. You should be happy.}
{133}{}{Of course! Uh, listen, I don't know what happened there, but thanks for the help. Now I'll quickly sneak out the door, and then out, through the bushes. See ya!}
{134}{}{Bye.}
{135}{}{Nothing special. Sit down and shut up.}

{136}{}{Apparently, you didn't lie. I managed to peep into the accounting entries in the casino ledger. It all fits - you've been framed.}
{137}{}{I told you! The people of the Clean City are awfully high of themselves. Listen, will you be able to bring the evidence to the cops? Orris will surely reward you for this.}
{138}{}{I'll think about it.}
{139}{}{What that cop has told you? You were talking about me, right?}
{140}{}{He said that you're free.}
{141}{}{Nothing that concerns you.}
{142}{}{Really?! I don't know how you did it, but thanks for the help. I need to quickly get out of here, before they'll change their mind. See ya!}
