{100}{}{You see a policeman.}
{101}{}{You see a policeman with a badge on his chest.}
{102}{}{Problems?}

{103}{}{Sir, }
{104}{}{Ma'am, }

####################################################################
#
#       О'ве'ные реплики на попы'ку заговори'ь
#       Ав'ор: Александр Агафонцев aka Kerb
#
####################################################################

{110}{}{We are watching you better than a Big Brother}
{111}{}{Law and Order is provided by Cruelty and Fear}
{112}{}{The Law is harsh, but it's the law}
{113}{}{Sure, you can break any law in Vegas... But first take care of your funeral.}
{114}{}{::stroking the holster, warily looks at you::}
{115}{}{We will not allow the crowd to beat you... We just don't tolerate the competition!}
{116}{}{There is no such thing as innocence, only a degrees of guilt}
{117}{}{Behave - and you will see the same response}

####################################################################
#
#       О'ве'ные реплики на попы'ку заговори'ь при дос'ижении "Прокаженный"
#
####################################################################

{120}{}{Ghouls don't belong here... Er, no, I wasn't talking to you.}
{121}{}{What!? Freak in the city!? Oops, my mistake, sorry.}
{122}{}{Don't do anything stupid, ghoul.}
{123}{}{We throw ghouls outside, so don't give us the reason to.}
{124}{}{Uh, you're not a ghoul? I would have shot you.}
{125}{}{With your, uh, face it is easy to catch the bullet. Keep in mind.}
{126}{}{Many people here don't like ghouls. Not saying anything, but keep it in mind.}
{127}{}{Come on, ghoul, keep moving. I don't want to catch this infection from you.}
{128}{}{People don't tolerate uglies in here, so watch it.}

####################################################################
#
#       Требования убра'ь оружие
#
####################################################################

#Первое предупреждение:
{200}{}{Put your weapon away!}
{201}{}{This is not a shooting range!}
{202}{}{Keep your weapon holstered!}
{203}{}{Do not provoke me, hide the weapons!}
{204}{}{Weapons are prohibited within city limits!}
{205}{}{You should remove the weapon}

#В'орое предупреждение:
{206}{}{Do you hear me?}
{207}{}{Do not push me!}
{208}{}{Don't even think of using that!}
{209}{}{We have orders to shoot to kill!}
{210}{}{Put your weapon away *immediately*!}

#Последнее предупреждение
{211}{}{Last warning!}
{212}{}{Do not force me to do the extreme!}
{213}{}{I don't want to fight!}
{214}{}{Better think about it!}
{215}{}{What are you doing?}

#Нападение:
{216}{}{You shouldn't have done this!}
{217}{}{It's *you* who instigated the fight!}
{218}{}{You asked for it!}
{219}{}{Looking for trouble?!}
{220}{}{Should have thought of that earlier!}
