{100}{}{You see Curtis.}
{101}{}{You see a mechanic with a wrench in his hand. He has quite a puzzled look.}

#Ïåðâûé äèàëîã
{110}{}{What do you want, pal?}
{111}{}{I'm just stopping by, to see how a fellow hard worker is doing.}
{112}{}{Nothing.}
{113}{}{"Fellow hard worker"? Heh! Bad, as always. Do you see this big guy on the floor?}
{114}{}{What is it, a "robo-cop"? Looks funny...}
{115}{}{Yeah, it sure does. So many complicated parts to fix just so he can stand somewhere and be intimidating. I'd have better luck wearing this junk on me and scaring passersby myself.}
{116}{}{Do you think there would be no benefit from it?}
{117}{}{Well, with full ammunition and in good condition, it's certainly a real death machine. Maybe the chief could even use it in special operations. But all in all, this thing is designed to intimidate by its appearance.}
{118}{}{Do you think activating it could be dangerous?}
{119}{}{Who knows... Military models were not created for peaceful purposes, baby. They were built to kill! And this robot's been dormant for about 70 years, with no checkups. Luckily, I figured out to strip it of its ammunition and disable the lower servo motors so I wouldn't be killed on the spot when it was turned on. But the thing that scares me is that not many people can understand this level of robotics. So no one can tell what's really in that piece of iron's mind. We have to rely on testing and spend a lot of time studying blueprints. So much effort for one robot! Is it worth it? I'm not sure.}
{120}{}{Does it have any weaknesses?}
{121}{}{Of course! It's full of electronics. One shot of an impulse weapon and the circuits just fry. This is a common problem with all pre-war robots.}
{122}{}{Pulse weapon? And where would somebody find one of those?}
{123}{}{I guess only in some military depots or places associated with the old army. These things were not produced for the civilian market.}

{128}{}{A fine job. Well, I should go, bye.}
{129}{}{Yeah, see you.}
{130}{}{Good luck.}

#Âîïðîñ î âîçìîæíîñ'è ðåìîí'à
{131}{}{Can you help me with repairs?}
{132}{}{Look, I work for the police. The cops don't let me do work for outsiders, so - sorry, I don't want to lose my job here. I can only recommend a good mechanic at the Hoover Dam. But he specializes mostly in electronics.}
{133}{}{Okay. Well I won't be bothering you then.}

#Ïîïû'êà çàãîâîðè'ü ïîñëå ïåðâîãî ðàçãîâîðà (ñëó÷àéíûå ïëàâàþùèå ôðàçû)
{150}{}{Hello!}
{151}{}{Hey!}
{152}{}{Oh, it's you...}
{153}{}{Sorry, I'm working...}
{154}{}{What? It's time for a break?}

#Ìàøèíà
{230}{}{Have you seen the car not far from here? It's my ride. You jealous?}
{231}{}{[Whistles] I would be honored to even touch it! Out of professional interest and technological curiosity, so to speak. And you know, if the car is working, then maybe I can hook her up with something - like gravity-plates with energocyclic chip! The car won't just ride, it will FLY! Well, figuratively speaking.}
{232}{}{And do you have this... Thing?}
{233}{}{Yeah, it's waiting for its new owner. Of course, I wouldn't mind of payment for my work. The price is 2500. Deal?}
{234}{}{Okay, here is the money.}
{235}{}{I don't have the cash right now. I'll come back later.}
{236}{}{Then wait for a few hours. I will do everything and come back.}
{237}{}{Okay.}
{238}{}{All done! You can now go on ahead and try it out... Damn, I'm so jealous!}
{239}{}{Oh. Thanks.}
{240}{}{After installing the gravity-plates your car can accelerate to incredible speeds and consume far less energy. Highways of Nevada, tremble!}

#Female character
{1110}{}{What do you want, gal?}
{1111}{}{I'm just stopping by, to see how a fellow hard worker is doing.}
