{100}{}{You see *that* cop.}
{101}{}{You see a familiar cop.}
{102}{}{Put away the weapon, before the patrol saw you.}
{103}{}{I knew you can't be trusted. Just give me a reason - and I'll shoot you right here.}
{104}{}{I asked you - don't talk to me! If someone sees us together, we are both finished!}
{105}{}{Glad to see you in the Clean City! Have a good time, pal.}
{106}{}{Welcome to Clean City! Have a good time.}
{107}{}{The crowd on the streets surely didn't expect this to happen in the center of the city...}
{108}{}{Something happened...}

#Сдача квеста
{110}{}{Welcome! Glad to see you. And - yes, I know everything. Now the city will be a better place, all because of you. Thank you.}
{111}{}{You're welcome. It was fun.}
{112}{}{Wait, I have been thinking about what can I reward you with. Here, take this super stimpak. It may save your life in a tough situation. Thank you again.}
{113}{}{Thank you too.}

#Жен реплики
{1105}{}{Glad to see you in the Clean City! Have a good time, gal.}
