{100}{}{You see a policeman.}
{101}{}{You see a policeman receptionist behind the desk.}
{102}{}{False evidence have been placed in Dead hotel, waiting for its time.}

{110}{}{Who are you searching for?}
{111}{}{Goodbye.}
{112}{}{Regarding the case of Sam Phillips.}

#Äåëî î Ñýìå Ôèëëèïñå
{113}{}{[The policeman's interest is suddenly sparked] This is the toughest subject... So what did you want me to tell you about Sam Phillips?}
{114}{}{I have a substance, that proves his involvement with drugs in the city! He buys this from a caravan from Salt Lake.}
{115}{}{I have a substance, that proves his innocence regarding his involvement with drugs in the city! Seems like someone mistook this food supplement for a drug.}
{116}{}{I just wanted to ask - how is the case going?}
{117}{}{Hmm, nothing, I suppose. Just asking.}
{118}{}{So that's what it is! Then I'll simply put handcuffs on you and put you in a cell, so you think next time before wasting police officer's time.}
{119}{}{Oh no, not in a cell! I'd better walk away quietly.}

{120}{}{Can I know why you are interested in this case?}
{121}{}{Sam Phillips... Er... Owes me money, and I'm worried.}
{122}{}{Sam Phillips is my friend and I don't want him to go in prison!}
{123}{}{I'm investigating the crime with order of the mayor himself.}
{124}{}{No reason. Why?}
{125}{}{Your boss has given me a civil job to snitch Phillips.}

{126}{}{Oh, then this changes things. At first we have been contacted by anonymous individual and notified that Phillips makes drugs in his cafe. We went at the site, and found there some of that yellow stinky crap. Our specialists still try to figure out what is it. But they are still struggling, so if they can't identify this substance, then I don't know, how all this is going to end.}
{127}{}{Yellow substance? Like this? [show an emulsifier]}
{128}{}{Hmm. Okay.}
{129}{}{Then you'll have to hurry, because during the search in the cafe we found a dubious yellow substance resembling one of the components for the production of drugs. Most likely, he will be sent to prison.}
{130}{}{Oh shit, is it really that bad?}
{131}{}{Oh so it's your friend! Well then, guys, you'll have to say goodbye to each other. Because soon Sam Phillips will be behind bars in prison. End of story.}
{132}{}{Damn it, is it really that bad?}
{133}{}{Drugs?! I don't believe it! You're lying!}
{134}{}{[Looks at you from head to bottom] Independent detective? How interesting. Well, here's how it is. We have been contacted by an anonymous individual, he said that Sam Phillips makes drugs. We went to the cafe, searched it and found some of that yellow stinky crap there. We're not sure yet what it is, but most likely his guilt will be proven by that thing alone.}
{135}{}{Now I see. Thanks.}

{136}{}{Yes. It is exactly the same thing we found at Phillips cafe! Where did you get that?}
{137}{}{From Bob. He is a caravan merchant from Salt Lake, from whom Sam buys this stuff.}
{138}{}{How interesting. This means, this drug is being brought from Salt lake?}
{139}{}{It's not a drug! This is a harmless food supplement for pizza. That is all.}
{140}{}{Yes! And you should as soon as possible to eliminate these supplies, so others would not be hurt!}
{141}{}{How interesting. So what is this drug?}
{142}{}{Wow... Food supplement... It doesn't look like it. But... How would I know how food supplement looks like? So that's why our specialists can't figure this stuff out. Well, I think your expertise is enough to prove Sam Phillips innocence.}
{143}{}{That's great! I'll go tell him.}
{144}{}{You, of course, are right, and we will do that immediately. Phillips will be arrested, and you, as it is being done in such cases, will be rewarded. Here, 1000$. Thank you, civilian, for your cooperation. I hope you will continue to notify us about any crimes that may be occurring.}
{145}{}{Heh, easy money.}

#Ïðî Âûñåðà
{150}{}{How is the duty, friend? Anything interesting happened lately?}
{151}{}{With the wit like yours, I have nothing to do here. But watch yourself. Because you may end up like the other one before you, which we tied to the pillar of shame for everyone to see. Try to not taking his place, with your insolent questions.}
{152}{}{Who are you talking about?}
{153}{}{Wow, sorry, to bother you, mister officer! My respects, mister officer! I'm bowing and ready to kiss your hands, mister officer!}
{154}{}{This idiot calls himself Shitposter. Underage asshole with high self-esteem. He is now hanging under the sun around welcoming console. Go have a look. It's quite a show!}
{155}{}{Fine.}

#Äæåé Êóêèø
{160}{}{I'm looking for jay Kukish, a biker. Heard anything about him?}
{161}{}{Wow - what a coincidence. We are also looking for him! We have orders to detain the offender. If you meet him - remember, he is very dangerous. Do not play around - shoot first, ask questions later.}
{162}{}{Uh, thanks for the info.}
{163}{}{Very well. It was a correct decision.}

#Äæåé Êóêèø
{170}{}{I demand that you release Murphy from his cell.}
{171}{}{You've got two options: either prove his innocence, or pay a deposit of 500$.}
{172}{}{I will pay. Here's the money.}
{173}{}{No use talking to you. See you.}
{174}{}{Prisoner Murphy! You're free to go.}
{175}{}{Thank you.}
{176}{}{The money is more important than your health? And if you get infected?}
{177}{}{Ha-ha-ha, you don't say? This trick is a hundred years old. I've heard everything: "Wasteland disease", "shakes", "Narg syndrome"... What did you come up with this time?}
{178}{}{You're telling me that, the "Wasteland disease" is not real? I'm a doctor with many years of experience, we have seen the whole villages die from that. Just like in Tonopah or Mesquite. Have you ever been there?}
{179}{}{Hmm. I heard something about Tonopah. Something about mad people, consuming their own flesh... Or it was really the whole village, which just died out there... But since you're a doctor, I have to believe you. First, write a receipt that you vouch for the diagnosis.}

#Êâåñò àðõèâàðèóñà è óëè÷íûé âîðèøêà
{180}{}{Is there any work here for a private detective?}
{181}{}{Usually we don't hire anyone and work by ourselves. But there are two cases where your help would be appreciated.}
{182}{}{Interesting. Can you say more?}
{183}{}{First, the daughter of the mayor's office archivist went missing. We haven't been able to find her. You can ask the archivist himself about his daughter. He is located on the second floor of City Hall.}
{184}{}{Okay. And what's the other one?}
{185}{}{There is an experienced pickpocket in Clean City. We received five reports of petty theft. That rascal needs to be caught as soon as possible. If you're careful you may be able to catch him in the act.}
{186}{}{Okay. The daughter of an archivist and a thief. I'll see what I can do.}

{190}{}{What can you say about Anna Clark's disappearance?}
{191}{}{Daughter disappeared without a trace. In the "Hard Rock" no one has seen her, in "Monte" she didn't appear for a long time, and there is no more places to search for girls like her. We gave up on the matter, because of absence of any clues.}
{192}{}{Okay.}

#Äåëî î âûðîäêàõ
{205}{}{Regarding freaks.}
{206}{}{I've got proof of their innocence. They have been framed!}
{207}{}{I've got proof of their guilt. This record I made during a conversation with Larry Geller.}
{208}{}{What's the problem with them at the police?}
{209}{}{Ah, the old sore problem.}

{210}{}{They produce drugs and distribute them around the city. The mayor is against that, and therefore seeks to suppress such scum, so they learn to respect the law.}
{211}{}{I see. Another question.}

{212}{}{What are you saying, freaks' favorite? How doubtful. Well, let's see what you got there...}
{213}{}{Here, I secretly picked up this pamphlet from the slavers. Direct evidence.}
{214}{}{Oh! How unexpected. I don't know what the slavers want, but we will deal with them. I'll give this evidence to the chief. Thank you, citizen. In such cases one must be rewarded. Here, take it. [Gives you 1000$]}
{215}{}{One thousand bucks!}

{216}{}{Very cunning of you. Good job! Underworld must be punished... And you should be rewarded. [Gives you $ 2000] As for those freaks - do not worry. We now arrange to round them up and they won't do any harm to anyone from now on.}
{217}{}{I want to participate! I'm sick of my gun collecting dust.}
{218}{}{Great!}
{219}{}{An additional gun won't hurt.  I think the freaks' expulsion will be easy.}
{220}{}{[You are waiting, while the police squad gets ready for a punitive operation at the Dead Hotel]}

{221}{}{I visited the freaks' hotel. They've got dope laying even in boxes! You should investigate immediately!}
{222}{}{You are just in time. Thank you for the information, on behalf of the Las Vegas police. You are entitled to a reward. Here's 1,000$. As for the freaks - you can rest assured. We are now getting ready to go on a punitive operation.}

#Óëèêè ïðîòèâ Óîëëèñà
{223}{}{Do you know that Hal Wallace is involved in dirty business? I have proof!}
{224}{}{Hal Wallace?! This great man was involved in criminal activities? Do you understand that you are responsible for your words right now?}
{225}{}{Here is a record of our conversation. He persuaded me to illegally snitch on the freaks!}
{226}{}{Here is a record of our conversation. He hired me to steal Bob Neil's gun!}
{227}{}{If everything is so serious, perhaps, I should refuse to present further evidence.}

{228}{}{I do not think that someone in the police will seriously blame Mr. Wallace in such actions. Quite the contrary. But I must give evidence to our boss. Thank you, citizen. You're now free to go.}
{229}{}{Can my anonymity be guaranteed?}
{230}{}{Okay.}
{231}{}{Yes, of course.}
{232}{}{Yes, it is a serious offense. Unfortunately, I cannot take any immediate action. I will give the evidence to our boss, and he will have to make a final decision. Thank you, citizen, for your assistance. We will take it from here.}
{233}{}{Don't I deserve some sort of a reward?}
{234}{}{What do you think, why Wallace needed the pistol?}
{235}{}{I hope your chief will figure it out.}
{236}{}{No.}
{237}{}{WHAT?! I risked my life and all was in vain! Fucking cop! Shove that evidence up your ass!}
{238}{}{Shame.}
{239}{}{I cannot say for sure. Perhaps he wanted set up Bob Neil and send him to prison. I have no idea why would he want that.}
{240}{}{Right.}

#Ëàáîðàòîðèÿ Âåãàñà
{241}{}{About the drugs that flood Vegas.}
{242}{}{Well, well, well! What do you have to tell?}
{243}{}{I know who supplies drugs to the city. They are called "black caravan".}
{244}{}{I know where the laboratory is and I can show it on the map.}
{245}{}{Uh... I see, it's an important matter to you. But I just wanted to ask how things are going.}

{246}{}{Good, smartass. And I was glad that the new clues emerged. We are still working on the case, but there's no end of it.}
{247}{}{Bad police work, officer!}
{248}{}{Too bad.}

{249}{}{*Very* good! Now we got these scum. Well, I thank you on behalf of the Clean City! You did the right thing by informing us about this. Traditionally, you deserve a reward. Here, this is for you.}
{250}{}{Now that's a reward! Oh yes!}

{251}{}{Now we got 'em! The Black Caravan will soon be reduced to ashes. Ha! Who would have thought that in our times there is such honorable people left, like you. Here, take this reward. The whole Las Vegas is thankful to you. I hope you will continue to inform us about such criminal individuals.}
{252}{}{Now that's a reward.}

{253}{}{Can I count on the reward for the disclosure of the laboratory?}
{254}{}{Er, weren't you been rewarded already?}
{255}{}{Yes, but for such an extremely important case I would like a little more.}
{256}{}{I am not authorized to deal with such issues. Refer to the police chief, Oscar Davis, he is in his office.}
{257}{}{Okay.}
{258}{}{We rarely get help in such difficult matters... I think we could reward you, but what do you want?}
{259}{}{To train my shooting skills.}
{260}{}{Nothing, sorry.}
{261}{}{Well, it is easy to arrange. But I think this will be a one time thing. So don't choose too hastily.}
{262}{}{Small weapons.}
{263}{}{Big weapons.}
{264}{}{Energy weapons.}
{265}{}{Melee weapons.}
{266}{}{Throwing.}
{267}{}{Unarmed.}
{268}{}{I'll think about it, then come back.}

#Îäèí èç êîðîëåé
{270}{}{Who is that guy behind the bars?}
{271}{}{Petty thief. He was caught stealing a large sum of money. But hard labor will teach him the consequences of such a lifestyle.}
{272}{}{Can I talk to him?}
{273}{}{Yes, it's not against the rules. You have three minutes.}
{274}{}{Thanks.}

{275}{}{Stop! Don't move! I've got you at gunpoint, you move - I kill. Now answer, what's the meaning of this?}
{276}{}{Hey, do not make hasty decisions! That bastard still got what he deserved...}
{277}{}{If I tell, I'll have to kill you, too.}
{278}{}{Well, well. So, personal matter, huh? Something does not look believable. Now tell me, who ordered his assassination? Now!}
{279}{}{It was Orris, one of the Kings gang. He wanted to shut his mouth, just in case. I don't interfere in their affairs, I only follow orders.}

{280}{}{[Hesitatingly] Really?}
{281}{}{It's the truth, chief! That bastard deserved to die. He's one of the bandits, outside the walls of this city they commit such crimes, that you never imagined of! And I... [sad] I had personal reasons.}
{282}{}{I... Uh... Look, I understand you well. But you shouldn't have done this. I will get in trouble because of you! What should I tell to the authorities? What if someone comes in now?}
{283}{}{I can just run, and you will say, that you didn't have the time to react! It is believable, no one will care about the bastard...}
{284}{}{Hrmm... Ah fuck it all to hell... Just run, before I change my mind! Now!}
{285}{}{Thanks, chief! Thanks!}
{286}{}{Wait, I remember you! I heard about you, you fucking scum. And I almost believed you... [unholsters his gun]}
{287}{}{I knew the Kings were involved! Fucking bastards! But you... Wait, you said that you're just a mercenary. Listen, I can let you go. But you'll have to do something to redeem yourself - kill Orris. That will be fair. If you won't do that, then you will get a bullet in your head as soon as you show yourself in Clean City. Got it? Now get the fuck out of here, before I change my mind!}
{288}{}{[Leave]}
{289}{}{Oh no! [Attack]}

{290}{}{Murphy is innocent. I have evidence.}
{291}{}{Very unpleasant story. City Hall employees are usually the standard of a respectable citizen. I hope you understand that this should stay private. The matter is not only in Irvine's crime, but also in the general situation. His example may be followed by others, not to mention the reputation of a Clean City. As for Murphy, we'll have to let him go. Although, I think it will bite us in the ass later.}
{292}{}{Great.}

{293}{}{I had personal grievances. It's the truth.}
{294}{}{[Through his teeth] You think it's funny? Let's see how long you'll be laughing. [Going to shoot]}
{295}{}{Hey, wait! He got what he deserved...}
{296}{}{[Defend yourself]}
{297}{}{[Your speech was unconvincing] Tell me the truth, you wasteland garbage!!!}
{298}{}{It is the truth...}
{299}{}{That's it, I had enough!}

#Female character
{1116}{}{I just wanted to see, how the case is going?}
{1117}{}{Hmm, nothing, I suppose, just asking.}
{1151}{}{With the wit like yours, I have nothing to do here. But watch yourself. Because you may end up like the other one before you, which we tied to the pillar of shame for everyone to see. Try to not taking his place, with your insolent questions.}
{1153}{}{Wow, sorry, to bother you, mister officer! My respects, mister officer! I'm bowing and ready to kiss your hands, mister officer!}
{1207}{}{I've got proof of their guilt. This record I made during a conversation with Larry Geller.}
{1213}{}{Here. I secretly picked up this pamphlet from the slavers. Direct evidence.}
{1221}{}{I visited the freaks' hotel. They've got dope laying even in boxes! You should immediately check this!}
{1226}{}{This is a record of our conversation. He hired me to steal Bob's Neil gun!}
{1237}{}{WHAT?! I risked my life and all was in vain! Fucking cop! Shove that evidence up your ass!}
{1245}{}{Er... I see, it's an important matter to you. But I just wanted to ask how things are going.}
{1246}{}{Nice one, babe, very funny. And I was glad that the new clues emerged. We are still working on the case, but there's no end of it.}
