{100}{}{You see a prisoner.}
{101}{}{You see a young guy with obviously rebellious attitude.}
{102}{}{The police officer here does not allow you to speak with the prisoner.}

{103}{}{Prisoner dies from the poisoned water.}
{104}{}{::takes the last breath::}

{110}{}{Who sent you?}
{111}{}{Nobody sent me. I was just wondering how a young man with such a stylish haircut could end up behind bars.}

{112}{}{I was framed! They don't care about whether I stole the money or not, they just need somebody to pin the blame on. Fucking pigs...}
{113}{}{So you're not guilty? Can you prove it?}

{114}{}{I won the money in the casino, fair and square. There should be records but I don't think they'll share them. So...looks like I can't prove anything... [lowers his voice] Hey, listen, you're not a cop, right? Can you help me out? My guys will pay you for this.}
{115}{}{Hmm, let me think...}

{116}{}{No time to think, plenty of time to think afterwards... Listen, you need to find my buddy, his name is Orris. Usually he can be found near the "Hard Rock" cafe. Tell him that his old friend Murphy is in trouble, he will understand... He will help... [grabs his head in despair] he... Will help...}
{117}{}{Maybe I'll find and talk to this Orris. But I need to know the details of this story.}
{118}{}{[Leave him]}
{119}{}{I was framed!}
{120}{}{Calm down and tell me the details of this story.}
{121}{}{Remind me where to find your friend Orris.}
{122}{}{Usually he can be found near the "Hard Rock" cafe. Tell him that his old friend Murphy is in trouble.}

{123}{}{It's like this: I won in the casino. Not a lot, but enough for a really good party, right? When I went outside, the cops hauled me off without any explanation. They brought me here, then this smart-ass from the mayor's office appeared and listed how much money I have in my pockets, and in what bills. He knew it in detail, I remember him near the cash register in the casino. He followed me! Now it looks like I stole the money from him.}
{124}{}{Who is this "smart-ass from the mayor's office"?}
{125}{}{But can't they identify you in the casino?}
{126}{}{Why should I believe you?}
{127}{}{I see. I have to go.}
{128}{}{Some Irwin guy, an employee of City Hall. Looks like many people here know him, but I don't. I'm from the suburbs, I don't hang out with the locals.}
{129}{}{Surely they can. They write everything down in this ledger book, but the cops don't care, they tend to believe that guy from the mayor's office. And I am sure that casino won't stand up for me. It's more convenient for them to kiss the asses of the City Hall and the cops.}
{130}{}{You? You shouldn't. Why would you care... But I'm not asking you to believe me! I'm asking you to talk to Orris, he will help, he's an old friend. And you might get something from it, you understand? You can find him at the Hard Rock Cafe.}

{131}{}{What's going on?!}
{132}{}{Well, apparently, the police officer in the waiting room is no longer at his duty. You should be happy.}
{133}{}{Of course! Uh, listen, I don't know what happened there, but thanks for the help. Now I'll quickly sneak out the door, and then out, through the bushes. See ya!}
{134}{}{Bye.}
{135}{}{Nothing special. Sit down and shut up.}

{136}{}{Apparently, you didn't lie. I managed to peep into the accounting entries in the casino ledger. It all fits - you've been framed.}
{137}{}{I told you! The people of the Clean City are awfully full of themselves. Listen, will you be able to bring the evidence to the cops? Orris will surely reward you for this.}
{138}{}{I'll think about it.}
{139}{}{What did that cop tell you? You were talking about me, right?}
{140}{}{He said that you're free.}
{141}{}{Nothing that concerns you.}
{142}{}{Really?! I don't know how you did it, but thanks for the help. I need to get out of here. Quick! Before they change their mind. See ya!}
