{100}{}{You see a policeman.}
{101}{}{You see a suspicious looking policeman... What is he doing here?}
{102}{}{Hey, you! It seems like someone flew too high. Isn't it the time to get down to earth a little?}
{103}{}{It's finished... But why this policeman attacked you?!}
{104}{}{Eat it, damned cop!}

{110}{}{Hold it right there, damn it!}
{111}{}{Wow! A cop that is looking for trouble?}
{112}{}{Don't shoot, I didn't do anything wrong!}

{113}{}{Everybody says that... And everyone lie. I learned that well, working as an inspector for cops. It won't be difficult for me to stick that gun into your mouth and pull the trigger. That's why Davis making me do this. So - can you at least tell me in the end, what the hell is going on?}
{114}{}{He wants to kill me?! I don't know anything about that!}
{115}{}{Well, he's not the first, who wanted to kill me, so I don't care.}

{116}{}{Oh... A tough guy, huh? But in Vegas, no one would order a hit on a man for no reason. I have an order, you know... From the chief of the police himself...}
{117}{}{Don't be stupid, why would you do it? What for?!}

{118}{}{Oh... Okay, suppose, it is true. But in Vegas, no one would order a hit on a man for no reason. I have an order, you know... From the chief of the police himself...}
{119}{}{Wait, don't be stupid, why would you do it? What for?!}

{120}{}{Nothing personal, pal, I'm just doing my job.}
{121}{}{Wait, don't be stupid, why would you do it? What for?!}
{122}{}{Then it will be your last job, fool! Bring it!}

{123}{}{This is my home. And I want you, alien scum, to go back to your caves. You only bring filth - drugs, weapons, theft and moral corruption of this city. However, behind me lies a large corrupted system and dubious order from the authorities. I know that Davis would like to remove me - because I often interrupting a lot of shady business practices, which shouldn't have been interrupted. Maybe that's why he is trying to throw me on you. What do you think about that?}
{124}{}{I think that you're a pathetic coward. Let's finish this.}
{125}{}{I know that your boss is involved in dirty business. I'll be done with him soon, and then nothing will threaten you any longer.}
{126}{}{I know that your boss is involved in dirty business. Soon I will bring order to this place, and then nothing will threaten you any longer.}

{127}{}{Then farewell, stranger...}
{128}{}{[Attack]}

{129}{}{If you think about it, people like me - a witnesses - are also removed, when they become useless. Do you have at least some evidence against Davis?}
{130}{}{I will find some, don't you doubt about that.}
{131}{}{Fuck the evidence, I'm not even going to bother digging through that shit.}
{132}{}{I don't believe you. From the people with such reputation in Vegas, nothing good can be expected. It's time to end this useless conversation... [picks up a weapon]}
{133}{}{[Attack]}

{134}{}{I will have to believe you. There is a lot of good word about you in Vegas. Just try to get this solved fast - those, who are behind this, may watch us... And one more thing. I'll be patrolling at an intersection near the entrance to the "Monte" Casino. But do not speak to me without a serious reason. Now I have to go. Good luck.}
{135}{}{I will have to believe you. No one heard anything bad about you in Vegas. Just try to get this solved fast - those, who are behind this, may watch us... And one more thing. I'll be patrolling at an intersection near the entrance to the "Monte" Casino. But do not speak to me without a serious reason. Now I have to go. Good luck.}
{136}{}{And good luck to you, Inspector. thanks for the warning.}
{137}{}{Don't be a pussy, everything will be okay!}

#Жен реплики
{1116}{}{Oh... A tough bitch, huh? But in Vegas, no one would order a hit on a man for no reason. I have an order, you know... From the chief of the police himself...}
{1120}{}{Nothing personal, gal, I'm just doing my job.}
{1127}{}{Then farewell, stranger...}
