{100}{}{You see: Sergeant Graves.}
{101}{}{You see: Peter Graves, head of the security service.}
{102}{}{Oww, my head.}
{103}{}{You have accessed the door, which leads to the second elevator.}
{104}{}{You have accessed the door, which leads to the warehouse.}

#Ñòàðòîâûé äèàëîã
{110}{}{[You see Sergeant Graves - brutally beaten, with arms and legs tied.]}
{111}{}{[Free him]}
{112}{}{[Leave him]}

{113}{}{Ughh... Thank you, citizen. You're just in time. These outsiders have taken over the vault. How did you manage to get in here?}
{114}{}{It wasn't that hard. More importantly, what do we do next?}
{115}{}{Right. Fighting the outsiders is pointless. There are too many of them and they're well armed. The only option left for us is to comply with their demands, or find some other, more clever way to neutralize them.}
{116}{}{Any ideas?}
{117}{}{We could try to activate the defense systems. I have access to the Automated Vault Control Systems, if we can get there and turn on the defenses. But it is probably jammed.}
{118}{}{Any other ways to deal with them?}
{119}{}{Yes, but it's lethal. According to the procedure, in case of a hostile invasion we must destroy the entire secret floor downstairs. The explosion will completely destroy the entire Vault, we won't be able to escape.}
{120}{}{That's not fair...}

{121}{}{Then we either fight them all by ourselves or comply with their demands. There's a guard robot in the next room. If we can repair it, it should give us a little edge. In any case, I can't just sit here doing nothing after all of this. The council lied to us, and these guys aren't exactly handing out cake and balloons. [He rubs his bruises]}
{122}{}{Excellent, in that case, follow me Sergeant. I need someone covering my back.}
{123}{}{Sit tight for a while, I need to scout around. We have to think about this first.}

{124}{}{What's the situation?}
{125}{}{Wait up, I need to look around.}
{126}{}{Let's move, I think I know what to do.}
{127}{}{We'll talk later.}

{1113}{}{Ughh... Thank you, citizen. You're just in time. These outsiders have taken over the vault. How did you manage to get here?}

