{100}{}{You see Phil!}
{101}{}{You see... The biker from Battle Mountain! What is he doing here?}

{109}{}{Well? Haven't decided either to go or not yet?}

#Начало диалога
{110}{}{Hello, my friend! I see they don't want to take you back?}
{111}{}{It's a long story. I think they won't be happy to see me here from now on, that's for sure.}
{112}{}{And I was kicked out of here right away, too. I didn't even do anything. I just wanted a little tour around the vault. Why are your people so stingy? I even offered to pay... Ah, fuck it.}
{113}{}{Where are you heading now?}
{114}{}{I don't know yet. We are preparing for a big trouble north of our base. So I have some business to attend. I can give you a ride, if you want.}

#Отправка в город
{115}{}{Ahh, no, I'll do it myself. Take care!}
{116}{}{To Salt Lake City then!}
{117}{}{To New Reno then!}
{118}{}{Then drop me off near Lovelock.}
{119}{}{Can you take me back to Battle Mountain?}
{120}{}{Can you drop me off near the Wind of War?}
{121}{}{Let's ride to Las Vegas, shall we?!}

#Female character:
{1109}{}{Well? Haven't decided either to go or not yet?}
{1110}{}{Hello, baby! I see they don't want to take you back?}
{1115}{}{Ahh, no, I'll do it myself. Take care!}
