{100}{}{You see a suspicious caravan merchant.}
{101}{}{One of many caravan merchants. You would not be able to separate him from others, if not for his shady looks.}
{102}{}{Piss off!}

#Стартовая ветка
{110}{}{Hey, pal, this is *our* parking spot. Walk around somewhere else, away from our wagons.}
{111}{}{Do you own the place? Come on - prove it, that it's *yours*!}
{112}{}{You are that "black" ones, are you? I need it... You understand? Very badly! Only one dose!}
{113}{}{Okay! Show me, where the laboratory is! Faster!}
{114}{}{Fine, I'll go someplace else.}

#Ответ на 111:
{115}{}{Keep it down, cop. It's in your interest, I warn you.}
{116}{}{You bad at running your mouth, pal, let me correct that jaw of yours!}
{117}{}{Woo, so scary. Fine, I will let it slide... For now.}

#Ответ на 112:
{118}{}{Just one? Not interested. There, near "Hard Rock", there is one guy. Perhaps, he can help.}
{119}{}{Just one? Not interested.}
{120}{}{You, as it seem, confessed. It's time to punish you. Right now! [Attack]}
{121}{}{Well, don't you see, I'm in bad shape?! Just one dose! I'll pay!}
{122}{}{Then I'll go look somewhere else.}

{123}{}{I told you - it's your problem! I don't deal with junkies, do you understand?!}
{124}{}{Junkie?! Me? I will fuck you up for this!}
{125}{}{I got it, sorry.}

#Ответ на 113:
{126}{}{Look at him, we have a fighter here! keep it down, gorilla, you're not alone in here.}
{127}{}{I won't keep it down, unless you tell me! Go on, spit it out, pal!}
{128}{}{Grmm, whatever you say... Baboon.}
{129}{}{Okay, one more word and even fellow caravaneers won't save you.}
{130}{}{Ooh, how scary! And who will strike first? Maybe, you?}
{131}{}{Shit, you convinced me, I should be more careful. Bye.}

{132}{}{You get nothing, you monkey, nothing! NO-THI-NG!}
{133}{}{Why is that? Maybe, I want to work there?}
{134}{}{Nothing? Okay, I'll look somewhere else then.}

{135}{}{Because for such kind of work, people are specifically found. Nobody wants you there.}
{136}{}{And I'll still come and knock at the gate.}
{137}{}{Shame. Too bad.}

{138}{}{...and you'll become a gecko breakfast. You'll be shot right at the entrance.}
{139}{}{Could you recommend me?}

{140}{}{NO, idiot! Do you even understand, who are you speaking to? I drive caravans! to whom will I recommend you? To brahmin's ass?}
{141}{}{Is this... A tricky proposition?}
{142}{}{NO, you monkey! This is a tricky warning. I transfer the goods, and I don't give a shit about anything else. I'm not here to help you, got it?}
{143}{}{Got it. And who can help me?}
{144}{}{Oh, well then I will leave you alone.}
{145}{}{You're sick, right? I told you - my job is to transfer the goods, I don't know anything else. Just fuck off.}
{146}{}{Ehh, not good.}

{147}{}{Fuck, my fingers are itching for a trigger. I can solve this very fast - just shoot you in your stupid head. My partner will help me. But I don't need attention. Go, fuck off. Don't make this bad for both of us.}
{148}{}{...}

#Female character
{1110}{}{Hey, gal, this is *our* parking spot. Walk around somewhere else, away from our wagons.}
{1125}{}{I got it, sorry.}
{1126}{}{Look at her, we have a fighter here! keep it down, gorilla, you're not alone in here.}
{1140}{}{NO, you idiot! Do you even understand, who are you speaking to? I drive caravans! Where will I recommend you? In brahmin ass?}
{1142}{}{NO, you monkey! This is a trick warning. I transfer the goods, and I don't give a fuck about anything else. I'm not here to help you, got it?}
{1145}{}{You're sick, right? I told you - my job is to transfer the goods, I don't know anything else. So just fuck off.}
