{100}{}{You see a heated caravaneer.}
{101}{}{You see one of the caravan guards.}
{102}{}{No thanks, I have had enough}
{103}{}{Hey}
{104}{}{Uh, hello... Let me first find my cards, we will talk later...}
{105}{}{Uh, hello... Let me first deal with these decks. Why there are so many of them?}

#Acquaintance
{110}{}{Hey, pal, it's obvious that you're freshly out of the wastelands. Sit down, take a break from the road.}
{111}{}{Why so much friendliness? Hey, something tells me that you're trying to put me at the card table...}
{112}{}{Oh, thank you, that's exactly what I needed.}
{113}{}{I'll decide what to do without you.}
{114}{}{You're not dumb. Honestly, I just wanted a little win in the cards, but not against those spending lives in casino since their childhood. They will leave you lying without your own skin there, like a Gecko.}
{115}{}{[Nods solemnly and goes through the cards in his hands] The best way to rest is to change activities. For example, to play in good company. Not among those kinds you can find in casino. They will leave you lying without your own skin there, like a Gecko.}
{116}{}{Okay, forget it, maybe it's for the best. Honestly, I just wanted a little win in the cards, but not against those spending lives in casino since their childhood. They will leave you lying without your own skin there, like a Gecko.}
{117}{}{So, what game do you want to play?}
{118}{}{Not interested. Bye.}
{119}{}{"Canasta", "Caravan", poker - you name it. But I have a condition, we will play with bets. Mixing, so to speak, business with pleasure.}
{120}{}{Hmm, I guess, you're trying to set this up not just out of friendliness. What happened, blew off all the money in the casino?}

{121}{}{What, do I have it written all over me? Heh, I'm not going to pretend I'm a saint, you're right, that's exactly what happened. I broke loose, hoping to win at least some money, but I didn't have much luck. Look, I have a stimpak, I'm ready to put it on the line, and your bet is 100 bucks. How do you like that?}
{122}{}{Great, let's play.}
{123}{}{Hey, why don't I just buy that stimpak?}
{124}{}{Not interested. Bye.}

#Ransom
{125}{}{You know, the huckster right opposite offered me measly $175 for the stimpak. What's the point to sell it for such pitiful money, if you can win twice as much at cards? But if you pay me $350 it will be a good deal.}
{126}{}{Then let's play.}
{127}{}{The price is suitable, here's your money.}
{128}{}{I'll think about this offer. Until next time.}

{129}{}{Oh, thank you! Take it, it's yours now.}
{130}{}{Good deal. Bye.}

#Game
{131}{}{Here's the stimpak. Now put 100 bucks on the table.}
{132}{}{Well, here's my bet. Let's start the game!}
{133}{}{I've already lost interest in the game. Let's leave it until the next time.}
{134}{}{My offer about the game still stands. I have a stimpak and I'm ready to put it on the line, and your bet is 100 bucks. You still want to play?}
{135}{}{[Becomes focused] The deck does not lie. [shuffles cards] That's why I love cards. They require *skills* and ingenuity from the player, rather than simply a random number of a dice. [deals cards] I will play to my full potential. It's not just a stimpak at stake, but also my hungry stomach. So, let's begin...}
{136}{}{Yeah, let's start...}

{137}{}{[Grabs his head in despair] What have I done...}
{138}{}{Ha-ha, if only I'd be so lucky every day! Look, as I take your... No, MY stimpak! And now I have to go. Have a good time, loser!}
{139}{}{I see, things must be really rough for you. Here, take these 100 bucks for the stimpak. You need them more. As for me, my loss is still less than the gain. Now I gotta go.}
{140}{}{Well, I was lucky and you wasn't. In another turn it could have been the other way around. But I have to go. Take care.}
{141}{}{[With a satisfied grin, leaning back in the chair] It was a fair victory. [collects the gain from the table and puts it in his pocket] }
{142}{}{Well, I had no luck. And that was fair.}
{143}{}{What? How!? This can't be!.. Don't even think to meet me on the same trail, crook! Or I'll remind you of that.}

#Women's replics
{1134}{}{My offer about the game still stands. I have a stimpak and I'm ready to put it on the line, and your bet is 100 bucks. You still want to play?}
{1110}{}{Hey, girl, it's obvious that you're freshly out of the wastelands. Sit down, take a break from the road.}
