{100}{}{Bobby the caravan merchant!}
{101}{}{This is the same caravaneer that was beaten in the Wind of War! He's here!}

#When sees the char for the first time after appearing on the map
{105}{}{Hey, friend! Would you buy a beer for the working man?}

#First dialogue
{110}{}{Buddy, I'm glad to see you! How is it going?}
{111}{}{Things are moving... Well, I think so. And how are you? Did you come back to normal after the Wind of War?}
{112}{}{[Waves his hand] Everything is fine! I won't set a foot in the Wind ever again. I will go with the caravans plying between Salt Lake and Vegas, as for the Wind - I won't make a single step in its direction! By the way, want to nibble a bit? [holds out a handful of little nuts]}
{113}{}{What is this?}
{114}{}{Vocas. The guys just returned from Salt Lake. You know they've got the great salt lake out there, where mutated water lily grows. It won't grow anywhere else. Two times a year it blooms and gives the nuts. Nibble on it, you won't regret. The taste is bitter, but they help to excrete all sorts of crap out of your body. Useful stuff, in short.}
{115}{}{Well, thank you. But where is Salt Lake?}
{116}{}{Well, thank you. Was happy to see you.}
{117}{}{What a nonsense. And no thanks whatsoever.}
{118}{}{This is in the North. About as far as New Reno from here. Let me show it on your map.}
{119}{}{Thanks. Maybe I'd wind up there someday.}
{120}{}{If you gonna get there make sure to have clean water with you in the road, there is a serious problem with it in the city. When you get to the outskirts, you'd immediately sense the smell of rot and moisture.}
{121}{}{Noted. Bye.}

#About The Black Caravan
{122}{}{Hello there, friend!}
{123}{}{Are you going to hang around there forever? What are your plans?}
{124}{}{Do you know anything about the caravans transporting dangerous products? For example, drugs?}
{125}{}{Hello. And bye.}
{126}{}{Well, what's with the plans? I have to work! Have to go with the caravan to Salt Lake. Usually I get enough in one trip to live quietly in Vegas for a couple of weeks. What other plans could a simple caravan merchant have?! That's how it is.}
{127}{}{Nevermind.}
{128}{}{I stay away from those things. I don't like all this.}
{129}{}{But you still know something, right?}
{130}{}{Damn it! Man, I'm telling you, stay away from all this dope!}
{131}{}{But I really need to know!}
{132}{}{No, friend, you *don't* need to know.}
{133}{}{Tell me, bitch! Tell me or I'll *force* you!}
{134}{}{Friend, I'm interfering not just for the sake of it. It's not just about me, you see... Nothing personal.}
{135}{}{You won't tell? Okay, then I'll have to leave.}
{136}{}{Don't get mad, chill! I... Okay. I will tell you, since you need it so much. But keep in mind, if anything happens, I'm not to blame!}
{137}{}{You'll tell me in *any* case! Understand!?}
{138}{}{You should have started from this! Tell me.}
{139}{}{Ahem... [lowers his voice] We call it the "Black Caravan". It is a few lads, they don't contact with the outsiders. They stay in the backyard behind this building, push off their stuff to someone, quietly, in silence, and then as quietly go away at night. We're doing our best to avoid them, you never know what might happen...}
{140}{}{So, they may be nearby? Got it.}
{141}{}{Yeah, and yet again - I didn't tell you this. Okay?}
{142}{}{We'll see about that.}
{143}{}{Don't worry, pal.}
{144}{}{No, I don't understand. And don't want to understand.}
{145}{}{Nevermind.}

#Women's replics
{1105}{}{Hey, friend! Would you buy a beer for the working man?}
{1110}{}{Friend, I'm glad to see you! How is it going?}
{1116}{}{Well, thank you. Was happy to see you.}
{1122}{}{Hello there, friend!}
{1130}{}{Damn it! Girl, I'm telling you, stay away from all this dope!}
{1132}{}{No, friend, you *don't* need to know.}
