{100}{}{You see a lively man.}
{101}{}{You see a thin young man in a striped shirt.}
{102}{}{Thank you very much.}

#Диалог
{110}{}{[You see a thin young man, wearily digging through the grass. He wears striped shirt that, together with long untidy hair, makes him stand out from the crowd.]}
{111}{}{Looking for something?}
{112}{}{Huh? Oh... The Kings are at it again. They took away my glasses and threw them somewhere into the grass. I've been looking for them for an hour already. If only I had a metal detector... Ugh. It seems it's not my lucky day. I better go to the cafe. Oh, if you find the glasses - please return them to me. I will be very thankful.}
{113}{}{Here they are, no need to look further.}
{114}{}{[Leave]}

{115}{}{Hi. Have you seen my glasses? That would be great.}
{116}{}{Yes, your glasses have been found.}
{117}{}{No, not yet.}
{118}{}{Oh! That's fortunate. Give them to me... Great, they didn't break. Thank you so much.}
{119}{}{Just gratitude is not enough. Pay me for my find.}
{120}{}{You're welcome.}
{121}{}{Really?... You made such a good first impression. Fine, here's five bucks. No more.}
{122}{}{Not much more to be expected from you. Bye.}
