{100}{}{You see a heated caravaneer.}
{101}{}{You see one of the caravan guards.}
{102}{}{No thanks, I have had enough of this.}
{103}{}{Hey.}
{104}{}{Uh, hello... Let me find my cards first, we will talk later...}
{105}{}{Uh, hello... Let me first deal with these decks. Why are there so many of them?}

#Acquaintance
{110}{}{Hey, pal. It's pretty much obvious that you're freshly out of the wastelands. Sit down, take a break from the road.}
{111}{}{Why such friendliness? Hey... Something tells me you're trying to put me at the card table.}
{112}{}{Oh, thank you, that's exactly what I needed.}
{113}{}{I'll decide what to do without you.}
{114}{}{You're not dumb. Honestly, I just wanted to win a little at cards, but not against those who've spent their lives in casinos since they were kids. They'll skin you like a gecko.}
{115}{}{[Nods solemnly and goes through the cards in his hands] The best way to relax is to change activities. For example, to play in good company. Just not the kind you can find in a casino. They'll skin you like a gecko.}
{116}{}{Okay, forget it, maybe it's for the best. Honestly, I just wanted to win a little at cards, but not against those who've spent their lives in casinos since they were kids. They'll skin you like a gecko.}
{117}{}{So, what game do you want to play?}
{118}{}{Not interested. Bye.}
{119}{}{"Canasta", "Caravan", poker - you name it. But I have a condition - we will make bets. Mixing business with pleasure, so to speak.}
{120}{}{Hmm, I think you're trying to set this up not just out of friendliness. What happened, blew all your money in the casino?}

{121}{}{Is that written all over me? I'm not going to pretend to be a saint. You're right, that's exactly what happened. I lost my head, hoping to win big, but ended up losing. Look, I've got a stimpak, I'm betting it against your 100 bucks. How do you like that?}
{122}{}{Great, let's play.}
{123}{}{Why don't I just buy that stimpak?}
{124}{}{Not interested. Bye.}

#Ransom
{125}{}{You know, the trader across the street offered me a measly $175 for a steampunk. What's the point of selling it for such a pittance when you can win twice as much at cards? But if you pay me $350, it's a good deal.}
{126}{}{Then let's play.}
{127}{}{The offer is good, here's your money.}
{128}{}{I'll think about it. Until next time.}

{129}{}{Oh, thank you! Take it, it's yours now.}
{130}{}{Good deal. Bye.}

#Game
{131}{}{Here's the stimpak. Now put 100 bucks on the table.}
{132}{}{Well, here's my bet. Let's start the game!}
{133}{}{I've already lost interest in the game. Let's leave it until the next time.}
{134}{}{My offer about the game still stands. I've got a stimpak, I'm betting it against your 100 bucks. Want to play?}
{135}{}{[Becomes focused] The cards don't lie. That's why I love them. They require *skill* and ingenuity from the player, rather than simply a random number of a dice. [He shuffles and deals cards] I will play to my full potential. It's not just a stimpak at stake, but also my hungry stomach. So, let's begin...}
{136}{}{Yeah, go for it...}

{137}{}{[Grabs his head in despair] What have I done...}
{138}{}{Ha-ha, if only I'd be so lucky every day! Look as I take your... No, MY stimpak! And now I have to go. Have a good time, loser!}
{139}{}{I see, things must be really rough for you. Here, take these 100 bucks for the stimpak. You need them more. As for me, my loss is still less than the gain. Now I gotta go.}
{140}{}{Well, I was lucky and you wasn't. Some other time it could have been the other way around. But now I have to go. Take care.}
{141}{}{[With a satisfied grin, he leans back in the chair] It was a fair victory. [He collects the gain from the table and puts it in his pocket] }
{142}{}{Well, I had no luck. And that was fair.}
{143}{}{What? How!? This can't be!... Don't even think about meeting me on the same trail, crook! Or I'll remind you of that.}

#Women's replies
{1110}{}{Hey, girl. It's pretty much obvious that you're freshly out of the wastelands. Sit down, take a break from the road.}
{1134}{}{My offer about the game still stands. I've got a stimpak, I'm betting it against your 100 bucks. Want to play?}
