{100}{}{Bobby the caravan merchant!}
{101}{}{This is the same caravaneer that was beaten in the Wind of War! He's here!}

#When sees the char for the first time after appearing on the map
{105}{}{Hey, friend! Would you mind buying a beer for a common worker?}

#First dialogue
{110}{}{Buddy, I'm so glad to see you! How is it going?}
{111}{}{All good... I think. And how are you? Have you recovered after Wind of War?}
{112}{}{[Waves his hand] Everything is fine! I won't set a foot in that place ever again. I will now go with the caravans between Salt Lake and Vegas, as for the Wind - not a single step in that direction! By the way, wanna have a bite? [he takes out a handful of little nuts]}
{113}{}{What is this?}
{114}{}{Vocas. The guys just got back from Salt Lake City. You know, there's a great salt lake there. A mutated water lily grows there, it doesn't grow anywhere else. Twice a year it blooms and produces nuts. Nibble them, you won't regret it. They taste bitter, but they help to flush all kinds of harmful crap out of your body. Useful stuff, in short.}
{115}{}{Thank you. But where is Salt Lake?}
{116}{}{Well, thank you. Was happy to see you.}
{117}{}{What a nonsense. And no, thanks.}
{118}{}{To the north. About as far as New Reno from here. Let me show it on your map.}
{119}{}{Thanks. Maybe I'd wind up there someday.}
{120}{}{If you are going to take a trip there, make sure to bring enough clean water with you. There is a serious problem with it in the city. When you reach the outskirts, you'll immediately get what I mean - the smell of rot and moisture is everywhere.}
{121}{}{Noted. Bye.}

#About The Black Caravan
{122}{}{Hello there, friend!}
{123}{}{Are you going to hang around there forever? What are your plans?}
{124}{}{Do you know anything about the caravans transporting dangerous products? Drugs, for example.}
{125}{}{Hello. And bye.}
{126}{}{Plans? I have to work! Took a job in the caravan to Salt Lake. Usually I get enough from one trip to rest quietly in Vegas for a couple of weeks. What other plans can a caravan merchant have?! That's as simple as that.}
{127}{}{Nevermind.}
{128}{}{I stay away from those things. Bad business.}
{129}{}{But you still know something, right?}
{130}{}{Damn it! Man, I'm telling you, stay away from this!}
{131}{}{But I really need to know!}
{132}{}{No, friend, you *don't* need to know.}
{133}{}{Tell me, you asshole! Tell me or I'll *force* you!}
{134}{}{Friend, it's not about you. There's more to it, you know... Nothing personal.}
{135}{}{You won't tell? Okay, then I'll have to leave.}
{136}{}{Hey, chill! Don't get so mad... Okay. I will tell you. But keep in mind, if anything happens, I'm not to blame!}
{137}{}{You're going to tell me in *any* case! Understand?}
{138}{}{Now we're talking! Tell me everything.}
{139}{}{Ahem... [lowers his voice] We call them "Black Caravan". A few lads, they don't talk to others much. You can find their carts behind this building. They usually hang around there, quietly pushing their stuff to someone, sometimes going away at night, just as quietly. We're doing our best to avoid them - you'll never know...}
{140}{}{Okay. Got it.}
{141}{}{Yeah, and again - I have nothing to do with this. Okay?}
{142}{}{We'll see about that.}
{143}{}{Don't worry, pal.}
{144}{}{No, I don't understand. And don't want to understand.}
{145}{}{Nevermind.}

#Women's replies
{1105}{}{Hey, friend! Would you mind buying a beer for a common worker?}
{1110}{}{Friend, I'm so glad to see you! How is it going?}
{1116}{}{Well, thank you. Was happy to see you.}
{1122}{}{Hello there, friend!}
{1130}{}{Damn it! Girl, I'm telling you, stay away from all this dope!}
{1132}{}{No, friend, you *don't* need to know.}
