{100}{}{You see a poor man.}
{101}{}{You see a slum dweller. He had almost lost hope, but still holding.}
{102}{}{Hello.}

{110}{}{Hello. [coughs] Just coming by? Or you're here for a reason?}
{111}{}{I just want to know how is the life in these slums.}
{112}{}{Just passing through. So I better get out of here.}

{113}{}{Shitty, as you can see. This is not Clean City - we have no electricity, no water, the houses crumble as we speak. I don't know how long we can last in these conditions.}
{114}{}{What is this place? A hostel?}
{115}{}{Is there anyone in charge?}
{116}{}{Why is Clean City thriving while you live in conditions like this?}
{117}{}{Tell me about the Kings.}
{118}{}{That is all, I wanted to know. Bye.}

{119}{}{Yeah, something like that. Of course, we won't tolerate just anyone in here, but we don't have strict demands either. People don't stay long anyway - often they just die. Those who don't, try to leave the place as quickly as possible.}
{120}{}{Well, we have an intendant, but he's more for show. The Kings are the ones who run these slums.}
{121}{}{Because they have money and power. We have nothing. They made their city so clean and tidy, not with their own hands, but with slavery! And they use people like us as cheap labor. It's impossible to find a job here, you have to work for almost nothing, and Clean City takes advantage of that. Greedy and arrogant.}
{122}{}{They don't play around. If they tell you to do something, you'd better gladly do it. You may meet them in other regions, they are all over the periphery. But they aren't just a gang. They watch over everything, they get water, food, hold off other gangs. In return we work for them. The weak are food for the strong, that's what they say.}

