{100}{}{You see a handyman.}
{101}{}{you see a gloomy looking guy, deep in his, obviously unhappy, thoughts.}

{102}{}{Don't touch me! I know how to fight, by the way!}
{103}{}{The siren on the dam has turned on. Surely it's the work of that cleaner from above.}
{104}{}{Just wait, you son of a bitch!}

{110}{}{[Before you stands a regular janitor with a brush in his hand, he frowns, noticing that you're approaching]}
{111}{}{Hey, mate, can I talk to you for a second?}
{112}{}{[Leave the worker]}

{113}{}{Why me? Why not someone else? Oh yeah - I'm the only one here, the rest are in a safe bunker underground. Don't think I will wet myself from excitement.}
{114}{}{I don't understand, why do you snapped at me?}
{115}{}{I think you don't like this job, right?}
{116}{}{I don't want to listen to someone's complaints. Take care.}
{117}{}{Well, sorry, I just had enough of this, the dam and all the Vegas. Only problems, no stability.}
{118}{}{Don't like? It's not the proper words! I can't stand it anymore. Recently, they cut my salary again. And the rumor has it that the Clean City will soon take the stocks, and then we are all done. They will replace us with someone cooler, and put us all under the knife to avoid sabotages. I don't want to wait for these times to come, it is better to think about the future in advance.}
{119}{}{If you're going to abandon this job, can you tell me how to get inside the station?}
{120}{}{[Looks around] You really need it, right? What if you're another spy, and then everyone finds out that I let you in?}
{121}{}{I don't know, maybe we can find a common interest?}

{122}{}{Okay, look, I know a special password for emergencies. And I'll tell it if you compensate all the money that these administrative nits have underpaid me. It is 1000 bucks. Well, a deal?}
{123}{}{The price is fine with me. Here's the money, give me the password.}
{124}{}{Not a deal. I'll just wipe you out and take your pass card.}
{125}{}{I'll think about your offer.}
{126}{}{What were you saying about the password?}
{127}{}{[Furtively looks around and quickly hides the money] Hush! No need to compromise us in such an exposed area! Okay, listen... [the worker quietly calls the password and goes away from the site of the dam]}
{128}{}{[Go your own way]}
{129}{}{Right, I have heard of people like you. Playing tough, intimidating others, but push them against the wall - and they will wet their knees with urine, right?}
{130}{}{[Nervously pull out a weapon and aim it at the worker]}
{131}{}{Then we will do it on your terms. Here's the money, give me the password.}

{132}{}{Hey, hey, take it easy! Such jokes are up to no good!!}
{133}{}{Damn it, tell me the password, bitch! Tell me before I get angry!}
{134}{}{[The knees of the worker buckle and the wet spots appear on his pants] P-please don't! I'll tell you! Just don't touch me!}
{135}{}{You should have begun from this...}
{136}{}{[The worker says the password and throws himself away after you put the gun off him]}
{137}{}{[Shoot in his back]}
{138}{}{[Let him run]}
{139}{}{[The worker, considering you a weak opponent, pushes you and you begins to fight]}
{140}{}{[Attack]}

{141}{}{Have you seen how many people I crashed on the local ring? You think I won't be able to do the same to you?}
{142}{}{Where the hell the likes of you come from!? I didn't do anything wrong, and suddenly... Um, okay, here's the password and now don't even touch me!}
{143}{}{Then you can live.}

{144}{}{You're so tense, baby, you just need to relax. Do you want me to keep you company?}
{145}{}{[Smiles from ear to ear] Speaking of, dId I stuck here for all day for nothing? Okay, let's go, I will show you the dam. Look, we have a secluded place here, also I have some beer lying around, somewhere under my bed.}
{146}{}{Ew, how vulgar... I don't want to waste my time with someone like you.}
{147}{}{Come on, baby!}
{148}{}{How would you say this mildly... You're not my type, not good enough to just abandon what I'm currently doing.}
{149}{}{Well, fuck you then, asshole!}
{150}{}{Maybe some other mutual interest can appear between us?}
{151}{}{The worker just forced you to have a hard and dirty sex, then quietly went out. You decided to no longer communicate with such selfish individuals.}
{152}{}{[While walking around the dam, the worker, who eventually got drunk from taking alcohol for courage, brought you to the toilet and pressed against the wall, then he began to pester your breasts and grab your buttocks]}
{153}{}{[Give in to him]}
{154}{}{[Rip off the bastard's throat]}
{155}{}{[Resist]}

#Women's replics
{1133}{}{Damn it, tell me the password, bitch! Tell me before I get angry!}
