{100}{}{You see Bob Neil.}
{101}{}{You see Bob Neil the substation chief.}
{102}{}{Bob Neil is dead. Imagine the bloodbath that's gonna start over Hoover Dam now...}

{300}{}{New in town? I don't remember seeing you...}
{301}{}{Yes, how can I help?}
{302}{}{Oh, it's you. What do you need?}

{305}{}{Don't worry, I'm going.}

#Question 1, meeting
{310}{}{So, who am I talking to?}
{311}{}{To me, obviously. I think I'd rather hear *your* name first.}
{312}{}{My name is }
{313}{}{. And you are...}
{314}{}{None of your business old man.}
{315}{}{In that case, I think I'd rather avoid talking to you.}

{316}{}{Oh, good manners? That's great. My name is Bob Neil, I am currently in charge of this dam. So, what brought you here?}
{317}{}{Curiosity, mostly. What can you tell me about this place?}
{318}{}{I've got a piece of advice for you: watch your words in this city, wanderer. That is very important, especially here.}
{319}{}{Uhuh, well, goodbye.}
{320}{}{Thanks for the tip. So, what's your name?}

{322}{}{If it's that important, I'm Bob Neil and I'm in charge of this dam. Any more questions?}
{323}{}{That's all for now, see you.}
{324}{}{I don't like that. It would be best if you leave.}
{325}{}{With pleasure.}
{326}{}{Good, I won't disturb you.}

#Question 2, about the dam
{330}{}{Can you tell me about this place?}
{331}{}{I think I can spare a little time for that. What would you like to know?}
{332}{}{History. How did you manage to set all this up?}
{333}{}{What is this place?}
{334}{}{Do you supply the entire city with electricity?}
{335}{}{What are all these people doing?}
{336}{}{What is your job?}
{337}{}{That's enough. I wanted to know something else.}

{340}{}{It wasn't hard to get this up and running, most of it was already automatically working since the Great War. The problems began when the equipment started to wear out. I took the matter into my hands and started selling electricity for a reasonable price to help with the upkeep. But the City Hall and the local businessmen decided to take everything for themselves. After a whole bunch of conflicts, we had to find a compromise. So, we came up with a stocks system. Although it's not perfect, but it helped avoid outright bloodshed and let me keep the dam in my hands.}
{341}{}{What about the dam?}
{342}{}{The dam worked automatically since the War. Still does. The real work is being done on substations and power lines - the places where electricity is distributed around the city.}
{343}{}{This is electric station number one. Most of the electricity produced by the dam is generated here. In the future, looking at how Vegas is growing, we'll need to launch the second station. We've got enough problems with one for the time being.}
{344}{}{Tell me the history. How did you manage to get this place running?}
{345}{}{Well, almost. A few districts and individual buildings have decided to supply themselves with their own power, using small nuclear reactors and generators. Although the main portion of the city's power comes from us.}
{346}{}{They're responsible for making sure the equipment is working and this place is tidy. We've also got a team for maintaining and repairing the power lines.}
{347}{}{Handling public relations and making sure these idiots don't do something stupid or late.}
{348}{}{Sounds like you're unhappy with how your employees are working.}
{349}{}{Now is not our best times, thanks to the administrative war for ownership of the dam. So, people are not willing to work here, and those who do - can't handle the tight schedule and shoddy pay.}
{350}{}{Strange situation for the city's main enterprise, wouldn't you say?}

#Question 3 - receiving quest to find workers
{351}{}{The damn shareholders set everything up in a way to leave us with barely any money to pay the workers. They're doing this to leave us penniless and then grab the dam for themselves. Gecko scums...}
{352}{}{If you're in short for workers, I could try and look for some new people.}
{353}{}{I already told you. We need cheap labour.}
{354}{}{Handling public relations and making sure everything works smoothly. We're doing quite well thanks to the new labour force. Thank you, wanderer.}
{355}{}{I understand. Let's go back a little.}
{356}{}{An interesting offer, but if it were that simple, I would've done it myself a long time ago. There isn't much choice. Most likely, we'll have to buy slaves. But the slavers guild is one of the stakeholders. I don't need additional pressure.}
{357}{}{What if somebody else buys slaves and sells them to you?}
{358}{}{Slaves are expensive. It's hard to find anyone capable of buying 20 slaves, and, at the same time, not having sights for the dam. It's a dead end, shortly speaking.}
{359}{}{I'll see what I can do.}
{360}{}{I can't promise anything.}

#Finding workers quest - freaks:
{370}{}{Have you thought about using the freaks as labour?}

{371}{}{Haven't you heard? The police have purged that stinking filth from our city. Even if I wanted to, there's nobody left to hire.}
{372}{}{Another question then.}
{373}{}{Hm. I don't have any more questions.}

{374}{}{Do you really think those rotting corpses are suitable for work?! Even so, their reputation in the city does not make them trustworthy.}
{375}{}{The police have vouched for them, that should count for something.}
{376}{}{You're unhappy with their reputation? I'd like another question then.}
{377}{}{Hm. I don't have any more questions.}

{378}{}{Oh? I didn't know that. Thank you for telling me. How good are they at manual labour?}
{379}{}{Enough with the prejudice! They are cheap and effective workforce, despite the outward appearances.}
{380}{}{I can tell you as a scientist, thanks to a combination of radiation and some virus, their cells were partially replaced by mineral-based analogies. Put simply, they have a whole array of physical advantages.}
{381}{}{Just trust me.}
{382}{}{I don't know. I'll look into it.}

{383}{}{Well, if you're so confident about them, then you must have reasons. Considering their current position, they won't ask for much... Alright, you've convinced me. I'll give the freaks a chance and see how it goes. Thank you wanderer.}
{384}{}{Great!}
{385}{}{You convinced Bob Neil to hire the freaks.}
{386}{}{Unconvincing. To base views on someone's inspiring speech is not the best idea. I hope you understand.}
{387}{}{Hm, I'll need to think about this.}

{388}{}{Oh, this is interesting! If they're more endurant and less affected by gas and radiation, then they'll make excellent workers. And considering their social position, they won't ask for much pay... Alright, you've convinced me. I'll work with the freaks and see how it turns out. Thank you, wanderer.}
{389}{}{Great!}

{390}{}{You know, you don't really look like a scientist...}
{391}{}{Of course, men with your reputation in Vegas deserve trust. You've convinced me. I'll work with the freaks and see how it turns out. Thank you, wanderer.}
{392}{}{Honestly, I haven't heard much good about you. Why should I trust you?}

{393}{}{Ah, here's our savior of the damned. I knew that this is how it will end, sooner or later. Well, now that the ghouls are gone, we're back to square one. We need labour force.}
{394}{}{Unfortunate to hear. I hope you find a solution.}
{395}{}{I did everything I could to help. I don't want to hear your whining.}

{396}{}{Looks like cheap labour is completely gone from the city...}
{397}{}{Yeah, that's basically it. Slavertown is empty, the mayor won't give a cent to support us. I had hope for those ghouls, despite my repulsion for them. But, unfortunately even they are gone. Looks like the only thing left is to give the fate of the dam into the hands of those snobs from the Clean City and hope they won't boot me out like a dog.}
{398}{}{That's unfortunate to hear. I guess I'll go now. My things aren't quite as bad.}

#Quest for labour force - slaves:
{400}{}{I can sell you some slaves. Interested?}

{401}{}{Hell yeah! But are you sure the slavers guild doesn't know what they're for?}
{402}{}{Yes, I am. Don't worry.}
{403}{}{Well alright. Not like I have much choice, I'll have to satisfy with your slaves. By guild prices, they costs around 10000$. I'll buy them for 15000$.}
{404}{}{I'm fine with that.}
{405}{}{20000, no less. Otherwise I'll just find a different buyer.}
{406}{}{I changed my mind. Goodbye.}

{407}{}{This is a robbery! But... Ugh... Hold on, I need them too much. Alright, I'll agree to 20000. But this is the bottom line.}
{408}{}{Great, a pleasure doing business with you.}
{409}{}{No thanks, I'd rather look for different sellers.}
{410}{}{You won't find them. My deal is guaranteed.}
{411}{}{Well fine. Let's go with 15000.}

{412}{}{Great deal! Now things will go much better.}
{413}{}{Good luck.}
{414}{}{You sold your slaves to Bob Neil.}

#Quest for labour -- finished:
{415}{}{How are those new workers?}
{416}{}{Those freaks are a treasure! They aren't pretentious, very endurant and they're not afraid of heat of radiation. Best of all, they work for nothing! And... Honestly, sometimes I like their jokes. A great bunch. I'm glad they're with us.}
{417}{}{Good, I've got another question.}
{418}{}{Great. I need to go now.}
{419}{}{I don't regret the purchase. There are a few problems with the slaves. I had to hire a chef and supervisors, but that's nothing compared to what they will do for us. I'm glad and... Thank you.}

#Hal Wallace's quest
{450}{}{Why does Hal Wallace hate you?}
{451}{}{What? What are you talking about?}
{452}{}{He, uh, was looking for someone to get you arrested.}
{453}{}{We asked me to get you out of the way.}
{454}{}{Well, there's rumors that he has something against you.}

{455}{}{Fucking son of a bitch! I've suspected him for a while now!}
{456}{}{What are you talking about?}
{457}{}{I don't care. Tell me why I shouldn't do this contract?}

{458}{}{He's ready to act openly now? Hm, did he really managed to find a few more aces up his sleeve?}
{459}{}{This city loves dark dealings behind your back. And you can bet your bottom dollar - Wallace is involved in them.}
{460}{}{What are you talking about?}
{461}{}{All the influential people in Vegas, including Hal, are trying to claim ownership of Hoover Dam. Usually, they try to do it legally, but recently, someone has been trying to sabotage my company.}
{462}{}{How was this done?}
{463}{}{First, we've started to lose important workers. Then obscene insults and lying accusations started to appear on the walls of the city. There was some mess with redistribution of stocks in Mayor's office, the police opened a few muddy cases, intended to ruin our reputation. Those who want to get us bankrupt, definitely know what they're doing.}
{464}{}{But why?}
{465}{}{If we go bankrupt, then a war for the dam will begin for real. The city will be shattered, people will die. But, anyone who wins will be the most influential man in the city. Some would consider the risk justified.}
{466}{}{What about Wallace?}

{467}{}{[Bob Neil doesn't notice you recording the conversation on your Pip-Boy.] He's a treacherous gangster. He never acts by himself, but rather sends middlemen to deal with his dirty work, so nobody could blame him.}
{468}{}{I can deal with him. Once and for all.}
{469}{}{So, why shouldn't I do the task he gave me?}
{470}{}{Well, that's your problems. I'd rather stay out of it.}
{471}{}{I'm not a fan of forceful decisions, but this has gone too far. Alright. I will pay you 5000$ to get rid of him.}
{472}{}{Alright. I'll do it.}
{473}{}{I'll think about it.}
{474}{}{I assume your interest is only in payment. In that case, I have a counter offer... You don't care who to get rid of, right? 5000$.}
{475}{}{Like hell, old man! I'm fulfilling Wallace's task!}

{476}{}{Of course. Pretty reasonable from you. Now, please leave. All the best.}
{477}{}{Goodbye.}
{478}{}{In that case, I have no choice...}
{479}{}{[Leave]}

{480}{}{Wallace won't be a problem anymore. I did my part of the deal. What about yours?}
{481}{}{Perfect! I heard all about it. Here's your payment, as promised. But we don't know anything and had no deals with each other. I hope you understand.}
{482}{}{I hope now your streak of bad luck will end?}
{483}{}{Of course, no problem.}

{484}{}{It's stupid to assume that one man was behind the whole thing. There are others. But the biggest parasite has been eliminated. That means I can sleep well at night, so as our employees.}
{485}{}{}
{486}{}{Understood.}
{487}{}{Now Wallace's shares should be redistributed among the other stakeholders, including part of it coming back to dam. This is good. The Clean City will only benefit, as everybody. I doubt anyone will ask for a recalculation.}
{488}{}{Understood. I need to go now.}
{489}{}{Explain to me first, what's going on here.}

#Female version
{1318}{}{I've got a piece of advice for you: watch your words in this city, wanderer. That is very important, especially here.}
{1354}{}{Handling public relations and making sure everything works smoothly. We're doing quite well thanks to the new labour force. Thank you, wanderer.}
{1383}{}{Well, if you're so confident about them, then you must have reasons. Considering their current position, they won't ask for much... Alright, you've convinced me. I'll give the freaks a chance and see how it goes. Thank you wanderer.}
{1388}{}{Oh, this is interesting! If they're more endurant and less affected by gas and radiation, then they'll make excellent workers. And considering their social position, they won't ask for much pay... Alright, you've convinced me. I'll work with the freaks and see how it turns out. Thank you, wanderer.}
{1391}{}{Of course, women with your reputation in Vegas deserve trust. You've convinced me. I'll work with the freaks and see how it turns out. Thank you, wanderer.}
{1393}{}{Ah, here's our savior of the damned. I knew that this is how it will end sooner or later. Well, now that the ghouls are gone, we're back to square one. We need labour force.}
{1402}{}{I'm sure. Don't worry.}
{1404}{}{I agree with the price.}
{1406}{}{I changed my mind. Take care.}
{1457}{}{I don't care. Tell me why shouldn't I do this job?}
{1469}{}{So, why shouldn't I finish his task?}
{1480}{}{Wallace won't be a problem. I did my part of the deal. What about yours?}