{100}{}{You see Bob Neil.}
{101}{}{You see Bob Neil, the substation manager.}
{102}{}{Bob Neil is dead. Imagine the bloodbath that's gonna start over Hoover Dam now...}

{300}{}{New in town? I don't remember meeting you before...}
{301}{}{Yes, how can I help?}
{302}{}{Oh, it's you. What do you need?}

{305}{}{Don't worry, I'm going.}

#Question 1, meeting
{310}{}{Sorry, who am I talking to?}
{311}{}{To me, obviously. I'd rather hear *your* name first.}
{312}{}{My name is }
{313}{}{. And you are...}
{314}{}{None of your business, old man.}
{315}{}{In that case, I think I'd rather avoid talking to you.}

{316}{}{Oh, good manners? That's great. My name is Bob Neil, I am currently in charge of the dam. So, what brought you here?}
{317}{}{Curiosity, mostly. What can you tell me about this place?}
{318}{}{I've got a piece of advice for you: watch your mouth in this city, wanderer. It's very important in general, and especially here.}
{319}{}{Uh-huh. Well, goodbye.}
{320}{}{Thanks for the tip. So, what's your name?}

{322}{}{If it's that important, I'm Bob Neil and I'm in charge of this dam. Any more questions?}
{323}{}{That's all for now, see you.}
{324}{}{I don't like this. It would be best for you to leave.}
{325}{}{With pleasure.}
{326}{}{Good, I won't be disturbing you then.}

#Question 2, about the dam
{330}{}{Can you tell me about this place?}
{331}{}{I think I can spare a little time for that. What would you like to know?}
{332}{}{Your story. How did you manage to set all this up?}
{333}{}{What is this place?}
{334}{}{Do you supply the entire city with electricity?}
{335}{}{What are all these people doing?}
{336}{}{What is your job?}
{337}{}{That's enough. I wanted to know something else.}

{340}{}{It wasn't hard to get this up and running, most of it was already running on autopilot since the Great War. The problems started when the equipment began to wear out. I took matters into my own hands and started selling electricity at a reasonable price to recoup the depreciation. But the mayor's office and local businessmen decided to take over everything. After a series of conflicts, we had to find a compromise. That's how we came up with the stock system. It may not be perfect, but it helped avoid outright bloodshed and allowed me to keep the dam in my hands.}
{341}{}{What about the dam?}
{342}{}{The dam worked automatically since the War. It still does. The real work is being done on substations and power lines - the places where electricity is distributed around the city.}
{343}{}{This is electric station number one. Most of the electricity produced by the dam is generated here. In the future, given how Vegas is growing, we will need to run a second station. For now, we have enough problems with one.}
{344}{}{Tell me your story. How did you manage to get this place running?}
{345}{}{Well, almost. A few districts and individual buildings have decided to provide themselves with their own energy, using small nuclear reactors and generators. Nevertheless, most of the energy in the city comes from us.}
{346}{}{They're responsible for making sure the equipment is working and the place is tidy. We've also got a team for maintaining and repairing the power lines.}
{347}{}{Handling public relations and making sure these idiots don't do something stupid.}
{348}{}{Sounds like you're unhappy with how your employees do their job.}
{349}{}{We're going through rough times, thanks to the administrative war for ownership of the dam. So, people don't really want to work here. And those who do, can't cope with a tough schedule and shoddy pay.}
{350}{}{Strange situation for the city's main enterprise, don't you think?}

#Question 3 - receiving quest to find workers
{351}{}{The damn shareholders set everything up in a way to leave us with barely any money to pay the workers. They're doing this to leave us penniless and then grab the dam for themselves. Gecko scums...}
{352}{}{If you're in short for workers, I could try to look for some new people.}
{353}{}{I already told you. We need a cheap labour.}
{354}{}{Handling public relations and making sure everything works smoothly. We're doing quite well thanks to the new labour force. Thank you, wanderer.}
{355}{}{I understand. Let's go back a little.}
{356}{}{Interesting suggestion, but if it were that easy, I would have done it myself a long time ago. There's not much choice. Most likely, we'll have to buy slaves. But the slave guild is one of the stakeholders. I don't need the extra pressure.}
{357}{}{What if somebody else buys slaves and sells them to you?}
{358}{}{Slaves are expensive. It's hard to find someone who can buy 20 slaves and doesn't have personal interest in this matter. In short, it's a dead end.}
{359}{}{I'll see what I can do.}
{360}{}{I can't promise anything.}

#Finding workers quest - freaks:
{370}{}{Have you thought about using freaks as a workforce?}

{371}{}{Haven't you heard? The police have purged that stinking filth out of our city. Even if I wanted to, there's nobody left to hire.}
{372}{}{Another question then.}
{373}{}{Hm. I don't have any more questions.}

{374}{}{Do you really think those rotting corpses are good for the job?! Even so, their reputation in the city does not make them trustworthy.}
{375}{}{The police vouched for them, that should count for something.}
{376}{}{You're unhappy with their reputation? I'd like another question then.}
{377}{}{Hm. I don't have any more questions.}

{378}{}{Oh? I didn't know that. Thank you for telling me. How good are they at manual labour?}
{379}{}{Enough with the prejudice! They are cheap and effective, despite their appearance.}
{380}{}{I can tell you as a scientist: thanks to a combination of radiation and some kind of virus, their cells have been partially replaced by their mineral-based counterparts. Simply put, they have a number of physical advantages for the job.}
{381}{}{Just trust me.}
{382}{}{I don't know. I'll look into it.}

{383}{}{Well, if you're so confident about them... Considering their current position, they won't ask much... Alright, you've convinced me. I'll give the freaks a chance and see how it goes. Thank you wanderer.}
{384}{}{Great!}
{385}{}{You convinced Bob Neil to hire the freaks.}
{386}{}{Unconvincing. To base views on someone's inspiring speech is not the best idea. I hope you understand.}
{387}{}{Hm, I'll need to think about this.}

{388}{}{Oh, this is interesting! If they have more endurance and are less affected by environment and radiation, then they'll make excellent workers. And considering their social position, they won't ask much... Alright, you've convinced me. I'll work with the freaks and see how it turns out. Thank you, wanderer.}
{389}{}{Great!}

{390}{}{You know, you don't really look like a scientist...}
{391}{}{Of course, a man of your reputation in Vegas deserves to be trusted. You convinced me. I'll work with the freaks and see how it turns out. Thank you, wanderer.}
{392}{}{Honestly, I haven't heard much good about you. Why should I trust you?}

{393}{}{Ah, here's our savior of the damned. I knew that this is how it will end, sooner or later. Well, now that the ghouls are gone, we're back to square one. We need labour force.}
{394}{}{Unfortunate to hear. I hope you find a solution.}
{395}{}{I did everything I could to help. I don't want to hear your whining.}

{396}{}{Looks like cheap labour is completely gone from the city...}
{397}{}{Yeah, that's basically it. Slavertown is empty, the mayor won't give a cent to support us. I had hopes for those ghouls, despite my repulsion for them. But, unfortunately even they are gone. Looks like the only thing left is to give the fate of the dam into the hands of those snobs from the Clean City and hope they won't boot me out like a dog.}
{398}{}{That's unfortunate to hear. I guess I'll go now. My things aren't going quite as bad.}

#Quest for labour force - slaves:
{400}{}{I can sell you some slaves. Interested?}

{401}{}{Hell yeah! But are you sure the slavers guild doesn't know what they're for?}
{402}{}{Yes, I am. Don't worry.}
{403}{}{Well, alright. Not like I have a choice, I will have to be satisfied with your slaves. By guild prices, they costs around $10000. I'll buy them for $15000.}
{404}{}{I'm fine with that.}
{405}{}{$20000, no less. Otherwise I'll just find a different buyer.}
{406}{}{I changed my mind. Goodbye.}

{407}{}{This is a robbery! But... Ugh... I need them too much. Alright, I'll agree to $20000. But this is the final offer.}
{408}{}{Great, a pleasure doing business with you.}
{409}{}{No thanks, I'd rather look for different sellers.}
{410}{}{You won't find them. My deal is guaranteed.}
{411}{}{Okay, fine. Let's go with $15000.}

{412}{}{Great deal! Now things will become much better.}
{413}{}{Good luck.}
{414}{}{You sold your slaves to Bob Neil.}

#Quest for labour -- finished:
{415}{}{How are those new workers?}
{416}{}{Those freaks are a treasure! They aren't pretentious, have excellent endurance and they're not afraid of heat of radiation. The best part is that they work for nothing! And... Honestly, sometimes I like their jokes. A great bunch. I'm glad they're with us.}
{417}{}{Good, I've got another question.}
{418}{}{Great. I need to go now.}
{419}{}{I don't regret the purchase. There are a few problems with the slaves. I had to hire a chef and supervisors, but that's nothing compared to what they will do for us. I'm glad and... Thank you.}

#Hal Wallace's quest
{450}{}{Why does Hal Wallace hate you?}
{451}{}{What? What are you talking about?}
{452}{}{He, uh, was looking for someone to get you arrested.}
{453}{}{We asked me to get you out of the way.}
{454}{}{Well, there's a rumor that he has something against you.}

{455}{}{That son of a bitch! I've been suspecting him for a while now!}
{456}{}{What are you talking about?}
{457}{}{I don't care. Tell me, why shouldn't I do this?}

{458}{}{Is he ready to act openly now? Hmm, did he manage to find a few more aces up his sleeve?}
{459}{}{This city loves to make shady dealings behind your back. And you can bet your bottom dollar on the fact that Wallace is involved in them.}
{460}{}{What are you talking about?}
{461}{}{All the influential people in Vegas, including Hal, are trying to take over the Hoover Dam. Usually they try to do it legally, but recently someone resorted to sabotage.}
{462}{}{How? What do you mean?}
{463}{}{First we began to lose important workers. Then obscene insults and false accusations began to appear on city walls. There was some confusion at City Hall about the redistribution of shares, and the police opened several dirty cases designed to tarnish our reputation. Those who want to make us bankrupt definitely know what they are doing.}
{464}{}{But why?}
{465}{}{If we go bankrupt, then a war for the dam will start for real. The city will be shattered, people will die. But, anyone who wins will be the most influential man in the city. Some would consider the risk justified.}
{466}{}{What about Wallace?}

{467}{}{[Bob Neil doesn't notice you recording the conversation on your Pip-Boy.] He's a treacherous gangster. He never acts by himself, but rather sends middlemen to deal with his dirty work, so nobody could blame him.}
{468}{}{I can deal with him. Once and for all.}
{469}{}{So, why shouldn't I do the task he gave me?}
{470}{}{Well, that's your problem. I'd rather stay out of it.}
{471}{}{I'm not a fan of such methods, but this has gone too far. Alright. I will pay you 5000$ to get rid of him.}
{472}{}{Alright. I'll do it.}
{473}{}{I'll think about it.}
{474}{}{I assume that you are only interested in payment. In this case, I have a counter offer... You don't care who you get rid of, do you? 5000$.}
{475}{}{Like hell, old man! I'm fulfilling Wallace's task!}

{476}{}{Of course. That's pretty reasonable. Now, please leave. All the best.}
{477}{}{Goodbye.}
{478}{}{In that case, I have no choice...}
{479}{}{[Leave]}

{480}{}{Wallace won't be a problem anymore. I did my part of the deal. What about yours?}
{481}{}{Perfect! I've heard all about it. Here's your payment, as I promised. But we don't know anything and had no deals with each other. I hope you understand.}
{482}{}{I hope now your streak of bad luck will end?}
{483}{}{Of course, no problem.}

{484}{}{It's stupid to assume that one man was behind the whole thing. There are others. But the biggest parasite has been eliminated. That means I can sleep well at night, so as my employees.}
{485}{}{}
{486}{}{Understood.}
{487}{}{Now Wallace's shares should be redistributed among the other stakeholders, which also means that some part of it will return to the dam. This is good. The Clean City will only benefit from it, as everybody else. I doubt anyone will ask for a recalculation.}
{488}{}{Understood. I need to go now.}
{489}{}{Explain to me first, what's going on here.}

#Female version
{1318}{}{I've got a piece of advice for you: watch your mouth in this city, wanderer. It's very important in general, and especially here.}
{1354}{}{Handling public relations and making sure everything works smoothly. We're doing quite well thanks to the new labour force. Thank you, wanderer.}
{1383}{}{Well, if you're so confident about them, then you must have reasons. Considering their current position, they won't ask much... Alright, you've convinced me. I'll give the freaks a chance and see how it goes. Thank you wanderer.}
{1388}{}{Oh, this is interesting! If they have more endurance and are less affected by environment and radiation, then they'll make excellent workers. And considering their social position, they won't ask much... Alright, you've convinced me. I'll work with the freaks and see how it turns out. Thank you, wanderer.}
{1391}{}{Of course, a woman of your reputation in Vegas deserves to be trusted. You convinced me. I'll work with the freaks and see how it turns out. Thank you, wanderer.}
{1393}{}{Ah, here's our savior of the damned. I knew that this is how it will end sooner or later. Well, now that the ghouls are gone, we're back to square one. We need labour force.}
{1402}{}{I'm sure. Don't worry.}
{1404}{}{I agree with the price.}
{1406}{}{I changed my mind. Take care.}
{1457}{}{I don't care. Tell me, why shouldn't I do this?}
{1469}{}{So, why shouldn't I do the task he gave me?}
{1480}{}{Wallace won't be a problem. I did my part of the deal. What about yours?}
