{100}{}{You see the quartermaster.}
{101}{}{You see a simple laborer in the warehouse. He is lazy and appears to be suffering from hemorrhoids.}
{102}{}{You can't just walk here! Go around, in through the corridor...}

{110}{}{What do you want?}
{111}{}{This is a warehouse, right? Is there anything here from this list?}
{112}{}{Nothing.}

{113}{}{We only have the pressure regulator from your list, a whole wagon of them! They just lay around, collecting dust, with no one to use them. No one to pawn them off on.}
{114}{}{So, maybe you can share one with me, if they're useless anyway?}

{115}{}{Well, not for free. I think one missing regulator won't hurt anyone, but food on the other hand is a rarity. We don't get paid much, you know. So make up your mind, I can sell it for 500$ or trade for 10 pizzas from the Phillips' cafe.}
{116}{}{What about Nuka-Cola? I do supply people with it and I can bring at least a full box.}
{117}{}{I've got just as many pizzas as you need. Here, take them.}
{118}{}{Here are 10 pizzas, as agreed.}
{119}{}{Here's the money, now give me the device.}

{120}{}{[Greedily grabs the money and hides it in his shirt, looks around and palms a pressure regulator] Here. But carefully, no one should notice.}
{121}{}{Uh-huh, okay.}
{122}{}{That's what I call service! Now I'm going to get the regulator, but when you leave with it, watch out, so no one notices.}

{123}{}{Really? Well, if you're a supplier from the factory, then why not! 250 bottles - and the regulator's yours.}
{124}{}{How strange, I have just the right number of bottles. I carry them on me just in case, you know...}
{125}{}{I have that amount in the warehouse in the city. I will bring them to you...}
{126}{}{I don't have that many in the local warehouse. You'll have to wait.}
{127}{}{I'll consider the offer. Bye.}

{128}{}{You're like a brahmin tractor! Now I have to find a place to put it all, so others won't see... Ah yes, here is the regulator. But carefully, no one should notice.}
{129}{}{Of course...}

{130}{}{As you wish. After all, you suggested it yourself.}
{131}{}{Bye.}

{132}{}{[You bring the required quantity of Nuka-Cola from the warehouse to the cafe.] }

{133}{}{Have you thought about my offer? It still stands.}
{134}{}{Remind me, what did you want in exchange?}
{135}{}{No, not yet.}
{136}{}{Choose - I can sell the thing for 500$ or trade for 10 pizzas from the Phillips' cafe.}

#Æåí ðåïëèêè
{1130}{}{As you wish. After all, you suggested it yourself.}
{1133}{}{Have you thought about my offer? It still stands.}
