{100}{}{You see a handyman.}
{101}{}{You see a gloomy guy, immersed in his obviously unhappy thoughts.}

{102}{}{Don't touch me! I know how to fight, by the way!}
{103}{}{The siren on the dam has turned on. Surely it's the work of that cleaner from above.}
{104}{}{Just you wait, you son of a bitch!}

{110}{}{[Before you stands a regular janitor with a brush in his hand, he frowns, noticing that you're approaching]}
{111}{}{Hey, mate, can I talk to you for a second?}
{112}{}{[Leave the worker alone]}

{113}{}{Why me? Why not to bother someone else? Oh yeah - I'm the only one here, the rest are in a safe bunker underground. Don't you think I'm going to wet myself in excitement.}
{114}{}{I don't understand, why are you snapping at me?}
{115}{}{I don't think you like this job, right?}
{116}{}{I don't want to listen to someone's complaints. Take care.}
{117}{}{Well, sorry. I just had enough of this - I mean, the dam and all the Vegas. Only problems, no stability.}
{118}{}{Like? I can't take it anymore! They recently cut my pay again. And there's a rumor that Clean City is going to get the majority of the stocks, and then we'll all be done for. They'll replace us with someone cooler and let us all loose to avoid sabotage. I don't want to wait for those times to come; it's better to think ahead.}
{119}{}{If you're going to abandon this job, can you tell me how to get inside the station?}
{120}{}{[Looks around] You really need it, right? What if you're another spy, and then everyone finds out that I let you in?}
{121}{}{I don't know, maybe we can find a common interest?}

{122}{}{Okay, look, I know a special password for emergencies. And I'll tell it if you compensate all the money that these administrative nits have underpaid me. It is 1000 bucks. Deal?}
{123}{}{Fine. Here's the money, give me the password.}
{124}{}{No deal. I'll just take you out and use your key card.}
{125}{}{I'll think about your offer.}
{126}{}{What were you saying about the password?}
{127}{}{[Furtively looks around and quickly hides the money] Hush! No need to compromise us in such an exposed area! Okay, listen... [the worker quietly calls the password and goes away from the site of the dam]}
{128}{}{[Go mind your business]}
{129}{}{Right, I have heard of people like you. Playing tough, intimidating others, but push them against the wall - and they will wet their knees.}
{130}{}{[Nervously pull out a weapon and aim it at the worker]}
{131}{}{Then we will do it on your terms. Here's the money, give me the password.}

{132}{}{Hey, hey, take it easy!}
{133}{}{Tell me the goddamn password, you asshole! Tell me, before I get angry!}
{134}{}{[The worker's knees buckle and wet spots appear on his pants] P-please don't! I'll tell you! Just don't touch me!}
{135}{}{You should have started with this...}
{136}{}{[The worker tells you the password and runs away after you put the gun off him]}
{137}{}{[Shoot him in the back]}
{138}{}{[Let him run]}
{139}{}{[The worker, considering you a weak opponent, pushes you away]}
{140}{}{[Attack]}

{141}{}{Have you seen how many people I've crushed in the local ring? You think I can't do the same to you?}
{142}{}{Where the hell the likes of you come from?! I didn't do anything wrong... Okay, here's the password. Don't you dare touching me!}
{143}{}{You can go now.}

{144}{}{You're so tense, baby, you just need to relax. Do you want me to keep you company?}
{145}{}{[Smiles from ear to ear] Speaking of which, why not... Have I been stuck here all day for nothing? All right, come on, I'll show you the dam. Look, here we lave a secluded spot, and I've got some beer stashed around...}
{146}{}{Ew, how vulgar... I don't want to waste my time on someone like you.}
{147}{}{Come on, baby!}
{148}{}{How would I put it... You're not my type. Not good enough to distract me from what I'm currently doing.}
{149}{}{Well then, fuck you, asshole!}
{150}{}{Could there be some other mutual interest between us?}
{151}{}{The worker just forced you to have hard and dirty sex and then calmly walked away. You decided not to communicate with such selfish individuals anymore.}
{152}{}{[While walking along the dam, a worker, who eventually became intoxicated from taking alcohol for courage, led you to the bathroom and pinned you against the wall, after which he started groping your breasts and grabbing your buttocks.]}
{153}{}{[Give in to him]}
{154}{}{[Rip off the bastard's throat]}
{155}{}{[Resist]}

#Women's replics
{1133}{}{Tell me the goddamn password, you asshole! Tell me, before I get angry!}
