{100}{}{You see the quartermaster.}
{101}{}{You see a simple laborer in the warehouse. He is lazy and appears to be suffering from hemorrhoids.}
{102}{}{You can't just walk here! Go to around in through the corridor...}

{110}{}{What do you want?}
{111}{}{It's a warehouse, right? Is there anything here from this list?}
{112}{}{Nothing.}

{113}{}{We have only the pressure regulator from the list, a whole wagon of them! They just lay around, collecting dust, with no use. No one to pawn it off to.}
{114}{}{So maybe, you can share with me, if they are useless anyway?}

{115}{}{Well, not for free. I think one missing regulator won't hurt anyone, but food on the other hand is a rarity. We don't get paid much, you know. So make up your mind, I can sell it for 500$ or trade for 10 pizzas from the Phillips' cafe.}
{116}{}{What about Nuka-Cola? I do supply people with it and I can bring at least a full box.}
{117}{}{I've got just as many pizzas as you need. Here, take it.}
{118}{}{Here are 10 pizzas, as agreed.}
{119}{}{Here's the money, now give me the device.}

{120}{}{[Greedily grabs the money and hides in the bosom, looks around and gets a pressure regulator] Here. But carefully, no one should notice.}
{121}{}{Uh-huh, okay.}
{122}{}{That's what I call service! So, now I'm going to get the regulator, but when you'll take it out, watch out, so no one notices.}

{123}{}{Really? Well, if you're a supplier of factory, then why not! 250 bottles - and the regulator's yours.}
{124}{}{How strange the number of bottles I have is just enough. I carry them on me just in case, you know...}
{125}{}{I have the right amount in the warehouses in this city. I will bring them to you...}
{126}{}{I don't have so much in a local warehouse. Will have to wait.}
{127}{}{I'll consider the offer. Bye.}

{128}{}{You're a like a brahmin tractor! Now I have to find where to put it all, so the others wouldn't see... Ah yes, here is the regulator. But carefully, no one should notice.}
{129}{}{Of course...}

{130}{}{As you want. After all, you suggested it yourself.}
{131}{}{Bye.}

{132}{}{[You bring required quantity of Nuka-Cola from warehouse to the cafe.] }

{133}{}{Have you thought about my offer? It is still stands.}
{134}{}{Remind me, what have you asked for in return?}
{135}{}{No, not yet.}
{136}{}{Choose - I can sell the thing for 500$ or trade for 10 pizzas from the Phillips' cafe.}

#Æåí ðåïëèêè
{1130}{}{As you want. After all, you suggested it yourself.}
{1133}{}{Have you thought about my offer? It is still stands.}
