{100}{}{You see a worker.}
{101}{}{You see an ordinary laborer.}

#Попытка разговора, когда он уже состоялся:
{102}{}{I'm busy. Can't you see?}

#Плавающие фразы, когда Боб Нил жив-здоров и на месте
{110}{}{Vegas is a mad city.}
{111}{}{A few more shifts and I'm rich.}
{112}{}{Where's the boss?}
{113}{}{To find a job in this city is like to steal a pelt off a gecko.}
{114}{}{I'll spend my next salary at Sam's cafe!...}
{115}{}{Philips' pizza is the shit!}
{116}{}{Is this a toilet paper?... Oh, it's the manual.}
{117}{}{Where are my tools?}
{118}{}{So tired...}
{119}{}{Covered in oil again...}
{120}{}{I'm so dirty no one recognizes me.}
{121}{}{Haven't taken a bath for a really long time.}
{122}{}{Do I stink much?}
{123}{}{Ugh... This stuff makes me dizzy.}
{124}{}{Ugh...}
{125}{}{::yawns without covering his mouth::}
{126}{}{::scratches::}
{127}{}{My whole body itches...}
{128}{}{I'm hungry.}
{129}{}{I'll starve to death soon.}

#Плавающие фразы, когда Боб Нил в тюряге или умер
{130}{}{Vegas is a disturbing city.}
{131}{}{A couple of days and I'm broke.}
{132}{}{What will we do without our boss?}
{133}{}{To find a new job? Hell, it's easier to hang myself.}
{134}{}{I'll get drunk in Sam's cafe and forget everything.}
{135}{}{Who stole my tools?}
{136}{}{So exhausted...}
{137}{}{They won't let me into my house without a paycheck.}
{138}{}{Haven't had a bath in a month!}
{139}{}{Do I stink much?}
{140}{}{Ugh... This stuff makes me dizzy.}
{141}{}{Oh...}
{142}{}{::yawns without covering his mouth::}
{143}{}{::scratches::}
{144}{}{My whole body itches...}
{145}{}{I need to eat, but have no money even for a sandwich.}
{146}{}{I'll starve to death soon.}
{147}{}{How will we be without Bob now?}
{148}{}{Bob is a good man. I don't believe he is guilty!}
{149}{}{Bob was framed! I'm sure!}

#Первый диалог
{250}{}{Don't you see I'm busy?!}
{251}{}{I was wondering, what is it you're doing?}
{252}{}{How do you cope without your boss?}
{253}{}{I think you're just a slacker. Bye.}
{254}{}{Well, if you're busy, then I'll leave you alone.}

{255}{}{You wouldn't understand. I sometimes do not understand myself, frankly speaking. But we have capable engineers, so we manage.}
{256}{}{City Hall calls the shots now. Except it's hopeless. They know nothing about electricity. They think we can manage ourselves, but without Bob we actually can't. A lot of people here want to find another job... Although that may be even harder to do.}