{100}{}{You see a dealer.}
{101}{}{You see a man in rumpled clothes. He rubs his nose and furtively looks around.}
{102}{}{Don't even dream, nothing gets into my pockets so easily.}
{103}{}{You got a hint of the existence of a drug lab somewhere around Las Vegas.}

#Dialogue mode
{110}{}{Come closer, don't expose yourself. Looking to get high? I have what you need. A lot of it. Choose, if you can pay.}
{111}{}{Bye.}
{112}{}{Wait, wait. Can I look again?}
{113}{}{Show me what you've got.}
{114}{}{I don't need anything this time.}
{115}{}{[Nods, hastily zips up his stuff gazing round] Is that all?}

#When the lab or the Black Caravan got destroyed
{120}{}{Sorry, less goods with each day passing. Choose from what is still available. And hurry, because tomorrow there may not be anything left.}
{121}{}{What happened to your stock?}
{122}{}{My relations came to an end, they shut up both the provider and the manufacturer at once. But you gotta hurry with the choice, look, there's another client coming.}
{123}{}{Yeah, let's make a deal.}
{124}{}{Leave this to him the. Bye.}

#Obtaining evidence about Sam Phillips
{130}{}{So you're the one Phillips is buying the drugs from?}
{131}{}{[Looks surprised] Sam Phillips? Really? Is he up to his old tricks again?}
{132}{}{[Quietly turn on recording on the Pip-Boy] Is it that surprising?}
{133}{}{I can see it surprises you. It means, you're not aware of the fact. Fine, worth taking note of. Bye.}

{134}{}{[Shrugs thoughtfully] People don't change. Sam had a personal problem with drugs, until he took the restoration of this cafe upon himself. Everyone thought he was done with drugs. But if this is true, I should pay him a visit.}
{135}{}{Never mind, I'm actually here for the goods. Let me see.}
{136}{}{Looks like you don't know anything else. Okay, bye.}

#Pound
{140}{}{Where did you get the goods?}
{141}{}{From reliable suppliers. That's all you need to know.}

{150}{}{You certainly know how to reassure the client. But it won't work with me.}
{151}{}{You're lying! You don't have any reliable suppliers! Only dubious statements.}
{152}{}{Actually, you're right. Let's just quietly make a deal.}
{153}{}{Either way, I'm not buying what you're selling. Bye.}

{154}{}{I'm not lying. My suppliers are reliable.}
{155}{}{But in our time the *clean* product can't be found anywhere. Who else but us knows it better, right?}
{156}{}{[Grins] One just have to know where to look. Not all chemicals in the world are from before the war.}
{157}{}{Wait, are you saying that there's exist an active chem manufacturer?!}
{158}{}{Indeed. And that's all you need to know. Are you satisfied? Now you can safely choose a product. It's clean, don't worry.}
{159}{}{And yet, tell me about the manufacturer. I need to know who and where it is.}
{160}{}{[Sternly] Are you out of your mind? Who tells such things to a complete stranger? I myself know very little. The production is delivered with a courier, I have never even been in the lab.}
{161}{}{Of course... Of course... You see, I'm interested in chems, not as a consumer but as a chemist. I would like to contact this laboratory - there can be a vacant position for me.}
{162}{}{[Raises an eyebrow skeptically] Well, tell me, weirdo, what do you know about methamphetamine from a scientific point of view.}
{163}{}{N-methyl-alpha-methylfentanyl, a derivative of amphetamine, it's a white crystalline substance, a strong psychostimulant.}
{164}{}{Quite a surprise. But I still can't help you. Like I said, I'm supplied by a delivery courier, and I myself have never been there.}
{165}{}{Well... A drug. White powder. All the junkies know that!}
{166}{}{Go to hell! If I find out you're a cop I will shoot you where you stand.}
{167}{}{Hey, easy!}
{168}{}{Maybe you know how to get in contact with them?}
{169}{}{[Looks around and starts to whisper] This place is called the Pound. They say it is far from the city, in the Mojave desert. I get their products through an intermediary, communicating in advance by the radio. The callsign is "Black Caravan". It's a couple of guys who pretend to be ordinary caravan merchants, standing in the parking lot among others. You have to look for them if you want to get in contact with the Pound. Certainly, Slavertown is also connected with them, but that's only a guess.}
{170}{}{Thanks, I'll remember that. Now show me what these guys palmed off to you. Maybe I'll buy something.}
{171}{}{That's good that you let all this talk slip from your tongue. Now is the time to kill you!}
{172}{}{This information is very useful to me. Bye.}

{173}{}{Right, cool story, tell me more. Where is the evidence? Where?!}
{174}{}{Okay, I believe you. Let's trade.}
{175}{}{Sure, of course. But I still won't buy anything from you.}
{176}{}{Your words are reassuring. Show me what you've got.}
{177}{}{I'll refrain. Bye.}
{178}{}{Of course... Of Course... You see, I'm interested in chems, not as a consumer, but as...}
{179}{}{[Furiously] Shut up, before I shoot you dead! Now get out of here.}
{180}{}{[Attack]}
{181}{}{[Go away]}
{182}{}{Well, that's enough for me. Now, let's get down to business.}
{183}{}{Anyway, still sounds not convincing. I'm leaving.}
{184}{}{I'm not going to prove you anything. Do you need a dose or not?}
{185}{}{Yeah, show me what you've got.}
{186}{}{I don't need your suspicious 'dose'. I don't need any so to speak. I'm leaving.}
{187}{}{Do you even know how much stuff was pushed on me by the likes of you?! All them dealers never bother to understand you, they only know how to line their pockets by selling crap to the living corpses...}
{188}{}{Hey, take it easy, I care about my clients. You can count on me.}
{189}{}{Really? You won't fool me? Well then, let's see what you've got.}
{190}{}{Don't lie to me! I see through you. And so I'll just leave.}
{191}{}{Right. Everyone says so, but I don't intend to die from taking what you cook!}
{192}{}{[Looks intently] You don't look like a drug addict. You work for whom? For the cops? Stay away from me!}
{193}{}{[Leave]}
{194}{}{[Looks intently] I see, you seem to have a serious problem with drugs. Even if I give you what you want It won't save you.}
{195}{}{Huh?}
{196}{}{You, addicts, are all hopeless... Although, I know how to help you.}
{197}{}{I know your kind too well but, I guess, listening won't hurt anyway.}
{198}{}{You may help only if you give me something to relieve the addiction. Show me what you're selling.}
{199}{}{I don't need your help. Will work something out without you.}
{200}{}{You may help only if you tell me where the lab is. I want to get THE purest drug!}
{201}{}{You need to contact the supplier. Sometimes they look for drug addicts. You will be glad to participate, I think.}
{202}{}{Hmm. Curious. Tell me more.}
{203}{}{If only I could count solely on myself and my skepticism. You are too good with the words.}

#Pop-up phrases
{500}{}{Look who it is! Drop in, maybe something will interest you?}
{501}{}{Hey, I have a sweet candy for the brain!}
{502}{}{Can give a discount, come here!}
{503}{}{::whistles::}
{504}{}{There's nothing better than taking a dose after a hard day. Am I right?}
{505}{}{I have something that will allow you to kiss the sky!}
{506}{}{Oh... From which lands are you from?}
{507}{}{I'll give you a discount on ALL of my stuff.}
{508}{}{I know what you are looking for and I have it. As much as you NEED.}
{509}{}{Why walk when you can *fly*?}
{510}{}{I have the purest product in the city, mind you.}
{511}{}{You wanna fly? You have money? So *I'm* the one you need.}
{512}{}{Wanna fly to a place where only the gods can be? I will help you!}
{513}{}{I have stuff, and more stuff. Let's talk.}

#Women's replics
{1158}{}{Indeed. And that's all you need to know. Are you satisfied? Now you can safely choose a product. It's clean, don't worry.}
{1192}{}{[Looks intently] You don't look like a drug addict. You work for whom? For the cops? Stay away from me!}
