{100}{}{You see a dealer.}
{101}{}{You see a man in rumpled clothes. He rubs his nose and furtively looks around.}
{102}{}{Don't even think about it. Nothing gets into my pockets so easily.}
{103}{}{You got a hint about the existence of a drug lab somewhere nearby Las Vegas.}

#Dialogue mode
{110}{}{Come closer, you're drawing too much attention just standing there. Looking to get high? I have what you need. A lot of it. Take a pick, if you can pay.}
{111}{}{Bye.}
{112}{}{Wait. Can I look again?}
{113}{}{Show me what you've got.}
{114}{}{I don't need anything this time.}
{115}{}{[Nods, hastily puts away his stuff and looks around] Is that it?}

#When the lab or the Black Caravan got destroyed
{120}{}{Sorry, less goods with each new day. Choose from what is still available. And hurry up, because tomorrow there may not be anything left.}
{121}{}{What happened to your stock?}
{122}{}{My business relations came to an end, someone shut up both the provider and the manufacturer. Look, you gotta hurry with the choice, there's another client coming.}
{123}{}{Yeah, let's make a deal.}
{124}{}{I'll leave it to him then. Bye.}

#Obtaining evidence about Sam Phillips
{130}{}{So you're the one Phillips is buying the drugs from?}
{131}{}{[Looks surprised] Sam Phillips? Really? Is he up to his old tricks again?}
{132}{}{[Quietly turn on recording on the Pip-Boy] Is it that surprising?}
{133}{}{I can see it surprises you. It means, you're not aware of the fact. Fine, worth taking note of. Bye.}

{134}{}{[Shrugs thoughtfully] People don't change. Sam had a personal problem with drugs, until he got himself into the rebuilding of this cafe. Everyone thought he was done with drugs. But if what you say is true, I should pay him a visit.}
{135}{}{Nevermind, I'm actually here for the goods. Show me what you got.}
{136}{}{Looks like you don't know anything else. Okay, bye.}

#Pound
{140}{}{Where did you get the goods?}
{141}{}{From reliable suppliers. That's all you need to know.}

{150}{}{You certainly know how to reassure the client. But it's not enough for me.}
{151}{}{You're lying! You don't have any reliable suppliers! Only dubious statements.}
{152}{}{Actually, you're right. Let's just quietly make a deal.}
{153}{}{Either way, I'm not buying what you're selling. Bye.}

{154}{}{I'm not lying. My suppliers are reliable.}
{155}{}{But these days, you can't just go and find a *pure* product. Who else but us knows better, right?}
{156}{}{[Grins] One just have to know where to look. Not all chemicals in the world are from before the war.}
{157}{}{Wait, are you saying that there is an active chem manufacturer?!}
{158}{}{Indeed. And that's all you need to know. Are you satisfied? Now you can safely choose a product. It's clean, don't worry.}
{159}{}{And still, tell me about the manufacturer. I need to know who it is and where to find it.}
{160}{}{[He gives you a stern look] Are you out of your mind? Who tells such things to a complete stranger? Besides, I know very little. The products are delivered with a courier, I have never even been in the lab.}
{161}{}{Of course... Of course... You see, I'm interested in chems, not as a consumer but as a chemist. I would like to contact this laboratory - there can be a vacant position for me.}
{162}{}{[Raises an eyebrow skeptically] Well, tell me, weirdo, what do you know about methamphetamine from a scientific point of view.}
{163}{}{N-methyl-alpha-methylfentanyl, a derivative of amphetamine, it's a white crystalline substance, a strong psychostimulant.}
{164}{}{Quite a surprise. But I still can't help you. Like I said, I'm supplied by a delivery courier, I have never been there.}
{165}{}{Well... A drug. White powder. All the junkies know that!}
{166}{}{Go to hell! If you're a cop I will shoot you where you stand.}
{167}{}{Hey, easy!}
{168}{}{Maybe you know how to get in contact with them?}
{169}{}{[Looks around and starts to whisper] The place is called the Pound. They say it is far from the city, in the Mojave desert. I get their products through an intermediary, communicating in advance over the radio. The callsign is "Black Caravan". It's a couple of guys who pretend to be ordinary caravan merchants, standing in the parking lot among others. You have to look for them if you want to get in contact with the Pound. Certainly, Slavertown is also connected with them, but that's only my guess.}
{170}{}{Thanks, I'll remember that. Now show me what these guys got you. Maybe I'll buy something.}
{171}{}{That's good that you let all this talk slip from your tongue. Now it's time to kill you!}
{172}{}{This information is very useful to me. Bye.}

{173}{}{Right, cool story, tell me more. Where is the evidence? Where?!}
{174}{}{Okay, I believe you. Let's trade.}
{175}{}{Of course. But I still won't buy anything from you.}
{176}{}{Your words are reassuring. Show me what you've got.}
{177}{}{I'll refrain. Bye.}
{178}{}{Of course... Of course... You see, I'm interested in chems, not as a consumer, but as...}
{179}{}{[Furiously] Shut up, before I shoot you dead! Now get out of here.}
{180}{}{[Attack]}
{181}{}{[Go away]}
{182}{}{Well, that's enough for me. Now, let's get down to business.}
{183}{}{Anyway, still sounds not convincing. I'm leaving.}
{184}{}{I'm not going to prove you anything. Do you need a dose or not?}
{185}{}{Yeah, show me what you've got.}
{186}{}{I don't need your suspicious 'dose'. I don't need anything from you. I'm leaving.}
{187}{}{Do you have any idea how much stuff people like you have been selling me?! All these dealers never bothered to understand you, they only know how to line their pockets by selling shit to living corpses...}
{188}{}{Hey, take it easy, I care about my clients. You can count on me.}
{189}{}{Really? You won't fool me? Well then, let's see what you've got.}
{190}{}{Don't lie to me! I can see right through you. I'm leaving.}
{191}{}{Right. Everyone says so, but I'm not going to die from what you're cooking!}
{192}{}{[Looks intently] You don't look like a drug addict. Who do you work for? The cops? Keep away from me!}
{193}{}{[Leave]}
{194}{}{[Looks intently] I see, you seem to have a serious problem with drugs. Even if I give you what you want It won't save you.}
{195}{}{Huh?}
{196}{}{You, addicts, are all hopeless... Although, I know how to help you.}
{197}{}{I know your kind too well but, I guess, listening won't hurt anyway.}
{198}{}{You can only help if you give me something to ease the addiction. Show me what you're selling.}
{199}{}{I don't need your help. Will work something out without you.}
{200}{}{You may help only if you tell me where the lab is. I want to get THE purest drug!}
{201}{}{You need to contact the supplier. Sometimes they look for drug addicts. I think you'll like it there.}
{202}{}{Hmm. Curious. Tell me more.}
{203}{}{If only I could count solely on myself and my skepticism. You are too good with the words.}

#Pop-up phrases
{500}{}{Look who it is! Drop in, maybe something will interest you?}
{501}{}{Hey, I have a sweet candy for the brain!}
{502}{}{I can give you a discount, come here!}
{503}{}{::whistles::}
{504}{}{There's nothing like a dose after a hard day. Am I right?}
{505}{}{I have something that will make you kiss the sky!}
{506}{}{Oh... What lands are you from?}
{507}{}{I will give you a discount on ALL of my products.}
{508}{}{I know what you are looking for. I have it. As much as you NEED.}
{509}{}{Why walk when you can *fly*?}
{510}{}{I have the purest product in the city, mind you.}
{511}{}{You wanna fly? You have money? So *I'm* the one you need.}
{512}{}{Wanna fly to a place where only the gods can be? I will help you!}
{513}{}{I have stuff, stuff and more stuff. Let's talk.}

#Women's replies
{1158}{}{Indeed. And that's all you need to know. Are you satisfied? Now you can safely choose a product. It's clean, don't worry.}
{1192}{}{[Looks intently] You don't look like a drug addict. Who do you work for? The cops? Keep away from me!}
