{100}{}{It's Maurice.} 
{101}{}{You see a man in shades, behind which is, barely visible, brash and cunning eyes are seen.}
{102}{}{Are you a local resident? If not, it is unlikely we have something to talk about.}
{103}{}{Don't you dare fuck with me! I can smell these tricks from a mile away...}

{110}{}{I saw you got the room on the third floor. Well, good choice - there is the tranquility and reliable protection.}
{111}{}{Are you local resident too?}

{112}{}{Well... You can say that. My name is Maurice. Nice to meet you... [looks around and starts whispering] Listen, I know why you're here. I see it in your eyes, what you want. Otherwise why would you be in this casino, right? If you need help, I'm at your service - I will get, what you came here for. Of course, for a reasonable price.}
{113}{}{What are you talking about?}
{114}{}{Eh, no, that won't do it. [calls you to the room and opens his jacket, to show the goods] All of these things will help you to ride Ms Fortune and own her in all positions. So, choose, if you have the money.}
{115}{}{[Trade]}
{116}{}{No, thanks, I prefer the honest route.}
{117}{}{[Laughs] Honest? Well okay. But when the honesty will make anal slave out of you, remember about me.}
{118}{}{Err, I'll try.}
{119}{}{}

{120}{}{I knew, you would come back. What do you need today?}
{121}{}{Nothing.}
{122}{}{Good luck, friend.}
{123}{}{[Walk away]}

#Клад
{130}{}{Listen, Maurice, you know, where I can make decent money here?}
{131}{}{Well, besides gambling, I only can think of some old story about the treasure. And, if you're good at bullshitting people, there is a chance to get to mayor's office, they pay the most there.}
{132}{}{Thanks. You said something about a treasure?}
{133}{}{It's an old story. After the war there was only one man that managed to win big at the casino. His name, I can't remember, it doesn't matter. By one theory, when he took his prize and walked outside, a group of head hunters followed him. But the son of a bitch was smart and he dropped the tail, in the darkness.}
{134}{}{Next?}
{135}{}{In the morning the man that was after him found him at a bar. He was covered in dirt, and he had only some change for the drinks in his pockets. When he knew, he could not escape, he shot himself, without telling, where he hid the treasure.}
{136}{}{So I will have to dig through the whole Vegas, to find the stash.}
{137}{}{Exactly! That's why nobody found it yet. But I won't be surprised, if its buried in a place, where everyone can see it.}
{138}{}{Hmm, thanks for telling me.}
{139}{}{[Smiles] Don't mention it. But if you find the treasure, don't forget to share with me a little, he-he.}
{140}{}{We'll see.}

#Обучение игре
{150}{}{Maurice, friend, I need to earn money as soon as possible! Can you help?}
{151}{}{Help? Ha! I could find you a ghoul for anal pleasure, but to find money... Sorry, but if you can't earn it, then you just have two ways, a robbery, or love with a whore named Fortuna.}
{152}{}{Who, with who?}
{153}{}{Stop it, you know, what I'm talking about. Come to any slot machines or croupier at the roulette table. You have a chance to become a millionaire... Or go into a deep minus. It's a risk, babe. All that can be done - is to reduce your chances of losing.}
{154}{}{How can I do that?}
{155}{}{[Sniff] Learn to play games for start. You think, it's all about math? Oh no. Gambling skill - is just like, any other skill. You should take a sober look at the situation in the game, able to assess your chances, to be able to anticipate the opponent's turn. Damn important is the memory and a lot of other shit. Well, are you is interested in that, or you're already shaking from a glance at the card table?}
{156}{}{You can teach me to play?}
{157}{}{Is there any other way more simple?}
{158}{}{Fuck, I told about the risks! Sure, you can take special cards and dice, but without certain skill you won't be able to anything with them, or even worse end up in a body bag.}
{159}{}{Sure, a tempting offer, but I will try to do without these tricks. Take care.}
{160}{}{Can I teach? Damn, I was the one, that almost managed to play this casino! Sadly, at the last moment I started losing and I was left without anything. But Mr. Wallace appreciated my talent and allowed to stay in the casino without the right to play. So ...yeah, I can teach you few things, for 1,000$. Believe me, I will quickly pay off, if you play well.}
{161}{}{Here is my last money for the lesson! I'm counting on your talent, Maurice!}
{162}{}{[Maurice takes you to his room, and you spend all day at learning the right way to play cards. Of course, Maurice always won, but in the end you still managed to get a draw] You're a good student. Pay no attention to failures. Sometimes they are sobering when success does blinds your eyes.}
{163}{}{Thanks , Maurice, it was an important lesson.}
{164}{}{Your gambling skill raised by 10%.}

#Female character
{1102}{}{Are you a local resident? If not, it is unlikely we have something to talk about.}
{1122}{}{Good luck, friend.}
{1162}{}{[Maurice takes you to his room, and you spend all day at learning the right way to play cards. Of course, Maurice always won, but in the end you still managed to get a draw] You're a good student. Pay no attention to failures. Sometimes they are sobering when success does blinds your eyes.}
