{100}{}{It's Maurice.} 
{101}{}{You see a man in shades, behind which you can barely see a pair of brash and cunning eyes.}
{102}{}{Are you a local? If not, it is unlikely we have something to talk about.}
{103}{}{Don't you dare fucking with me! I can smell your tricks a mile away...}

{110}{}{I saw you got a room on the third floor. Well, it's a good choice - it's quiet and well-protected.}
{111}{}{Are you a local too?}

{112}{}{Well... You can say that. My name is Maurice. Nice to meet you... [looks around and starts whispering] Listen, I know why you're here. I see it in your eyes, I know what you want. Otherwise, why would you be in this casino, right? If you need help, I'm at your service - I will get you what you came for. For a reasonable price, of course.}
{113}{}{What are you talking about?}
{114}{}{Eh, no, that won't do. [He gets you to the room and opens his jacket, showing you the goods] All of these things will help you to ride Miss Fortune and own her in every position. So, choose if you have the money.}
{115}{}{[Trade]}
{116}{}{No, thanks, I prefer the honest route.}
{117}{}{[Laughs] Honest? Well, okay. But when the honesty turns you into a slave, remember about me.}
{118}{}{Err, I will.}
{119}{}{}

{120}{}{I knew you would come back. What do you need today?}
{121}{}{Nothing.}
{122}{}{Good luck, friend.}
{123}{}{[Walk away]}

#Êëàä
{130}{}{Listen, Maurice, do you know where I can make some decent money?}
{131}{}{Well, besides gambling, I can only think of some old story about treasure. Or, if you're good at bullshitting people, you can get a job at City Hall, they pay very well.}
{132}{}{Thanks. You said something about a treasure. Care to tell me more?}
{133}{}{It's an old story. After the war, there was one man that managed to win big at the casino... I can't remember the name, but it doesn't really matter. According to one version, when he took his prize and went outside, a group of bounty hunters followed him. But the son of a bitch was smart and dropped the tail, disappearing in the dark alley.}
{134}{}{So?}
{135}{}{By the morning, one of the bounty hunters found him in a bar - he was covered in mud and had only change for drinks in his pockets. When he realized he couldn't get away, he shot himself without saying where he had hidden the treasure.}
{136}{}{So I have to dig through the whole Vegas to find the stash.}
{137}{}{Exactly! That's why nobody found it yet. But I wouldn't be surprised if it's buried somewhere in a plain sight.}
{138}{}{Hmm, thanks for telling me.}
{139}{}{[Smiles] Don't mention it. But if you find the treasure, don't forget to share a little, hehe.}
{140}{}{We'll see.}

#Îáó÷åíèå èãðå
{150}{}{Maurice, friend, I need to earn money as fast as possible! Can you help?}
{151}{}{Help? Ha! I could find you a ghoul for anal pleasure, but money.... Sorry, but if you can't earn it, then you just have two ways - rob someone, or make love to a whore named Fortuna.}
{152}{}{What? With who?}
{153}{}{Stop it, you know what I'm talking about. Go to any slot machines, or talk to a croupier at the roulette table. You have a chance to become a millionaire... Or to lose more than you have. It's always a risk, babe. All you can do is try to reduce your chances of losing.}
{154}{}{How?}
{155}{}{[Sniff] Learn to play the games, for a start. You think it's all about math? Oh no. Gambling skill is just like any other skill. You should be able to take a clear look at the situation in the game, assess your chances, and anticipate the opponent's turn. It's important to make use of your good memory and a lot of other shit. Are you interested? Or you shiver just at the sight of a card table?}
{156}{}{Can you teach me?}
{157}{}{Is there any other way? A simpler way?}
{158}{}{Of course, but remember what I told you about the risks! Sure, you can take special cards and dice, but without certain skills you won't be able to do anything with them, or worse, you'll end up in a body bag.}
{159}{}{Sure, a tempting offer, but I will do without these tricks. Take care.}
{160}{}{Can I teach you? Hell, I was the only one who almost managed to beat that casino! Unfortunately, at the last moment I started losing and ended up with nothing... But Mr. Wallace appreciated my talent and let me stay in the casino without the right to gamble. So -  yes, I can teach you a few things for $1,000. Believe me, you'll get it back quickly, if you play well.}
{161}{}{Here is my last money for the lesson! I'm counting on your talent, Maurice!}
{162}{}{[Maurice takes you to his room, and you spend the whole day learning how to play cards properly. Of course, Maurice always won, but in the end you still managed to get a draw] You're a good student. Don't mind the failures. Sometimes they keep you sober when success leaves you blind.}
{163}{}{Thanks, Maurice, it was an important lesson.}
{164}{}{Your gambling skill is raised by 10%.}

#Female character
{1102}{}{Are you a local resident? If not, it is unlikely we have something to talk about.}
{1122}{}{Good luck, friend.}
{1162}{}{[Maurice takes you to his room, and you spend the whole day learning how to play cards properly. Of course, Maurice always won, but in the end you still managed to get a draw] You're a good student. Don't mind the failures. Sometimes they keep you sober when success blinds your eyes.}
