{100}{}{You see Richard Pryor.}
{101}{}{You see a comedian with a bushy mustache and gambling glance. He lets everyone know with only his looks - anything can be expected from him.}

#Попы'ка заговори'ь на кар'е кафе не получив квес'а
{102}{}{All the paparazzi leave my house! I don't give out autographs today.}

#Фраза при смер'и
{103}{}{No-oo! I have not yet finished my tour around Nevada!}

#О'ве'ная реплика после выполнения квес'а на дос'авку в кафе
{104}{}{Now, when I'm standing on the stage with one leg, I can stick the other one into the Clean City's ass, and take it out through the mouth. Can you imagine how it's like!?}
{105}{}{Wild verbal itching with an abundance of vulgarity makes you constantly distracted. Because of this, you may have serious problems.}
{106}{}{While Pryor is with you, your luck will be reduced by }
{107}{}{.}
{108}{}{Freed from the comedian, you feel an incredible peace in the head.}

#Вс'упи'ельные фразы при загрузке кар'
{110}{}{What the gecko are we doing here?!}
{111}{}{ }
{112}{}{ }
{113}{}{ }
{114}{}{ }
{115}{}{ }

#Попы'ка 'олкания
{140}{}{Ah, I stepped on a thorn!}
{141}{}{Ouch}
{142}{}{Better look for *your* balls}
{143}{}{Easy! I'm special.}
{144}{}{Push me harder. I don't mind, if you know what I mean.}
{145}{}{Your hands are moist. Care to scrub my back?}

#Опции пар'ийца в диалоге
{150}{}{Hey, why are you *wandering* around so much?.. Aha-ha! Nice one!}
{151}{}{Time to move. Let's go.}
{152}{}{Don't say another word.}

{153}{}{...And I ask him - hey, is this Reno? And he says...}
{154}{}{You will have to wait me here.}
{155}{}{Let's go. Reno awaits us.}
{156}{}{Don't say another word.}

#Диалог в Вегасе
{200}{}{Fans, fans... You didn't bring paparazzi with you, did you? Good enough.}
{201}{}{So it's you I have to accompany to the Reno's stage?}
{202}{}{I didn't need you! I don't even want to talk to you.}
{203}{}{Reno's stage is calling for me, baby! But you are... By yourself... Didn't they have a security escort, or, at least, a stagecoach? Okay, okay, I'm going now, if it is time to.}
{204}{}{Let's go.}
{205}{}{Wait, I should prepare for departing.}

{210}{}{How would I put it mildly... The thing is, the club's owner died and now you're out of work.}
{211}{}{What the fuck am I doing here then!? [looks around in confusion] What a shithole! [Sees homeless men around the barrel] Hey, guys! Want some company?.. [Goes to them and gets lost in the crowd, then a collective laughter is heard in the distance, eventually falling silent.]}
{212}{}{Well, apparently, we won't see each other again, Richard Pryor.}
{213}{}{Go fuck yourself, piece of shit!}

#Обычный диалог
{250}{}{Tell me about your work.}
{251}{}{Look, I'm funny. People laugh at my jokes, like a crowd of morons. I was born for this. However, Vegas is already tired of me, so I stopped performing here. But I still have to eat, so I decided to try my luck in Reno.}
{252}{}{You don't talk like a comedian right now...}
{253}{}{Fine.}
{254}{}{Well... You know, I have some heavy shit on my heart. I tell something important to people - and they don't listen. They think it's just a joke. But they listen to *you*. Because you're serious, even though you don't have much to say. You know what I'm saying?}
{255}{}{And what would you tell to people in Reno?}
{256}{}{Just the same crap, I think. Nobody takes me seriously anyway. Besides, I can't do anything else. After all this fun on big stages for years, I can't just go back to something like digging through brahmin shit, you know what I'm saying?}

#Сцена в Рино

#Фразы в оригинале:
#What the fuck am I doing here!?
#Sick of hearing this shit about me not talking... Not true... Good days, bad days... But I still am a talkin motherfucker!
{300}{}{What the fuck am I doing here!?}
{301}{}{See No Evil, Hear No Evil}
{302}{}{Dedicated to all those who took care of my cocaine}
{303}{}{Good days, bad days... But I still am a talkin' motherfucker!}
{304}{}{Do you remember that dry fucking season 20 years ago? I survived through that shit...}
{305}{}{The first time, when I came, I fucking shit my pants, dude!}
{306}{}{And everybody starts asking: what is it?! It's Richard Pryor running down the street!}
{307}{}{I thought, this is because of the straight hair. While they are like this, the white bully me around. And I burned them.}
{308}{}{Let me zipper up, if I'm performing before an audience.}
{309}{}{60 years ago you could fuck no one, because every girl had a sickness called "virginity"}
{310}{}{Being black is cool. 'Cause being white is not cool.}
{311}{}{Kiss my black ass!}
{312}{}{Did you know, that one million bucks weights 2204,6 pounds?}
{313}{}{What is it: a cross on cross? it's a pope on a nurse.}

#Female character
{1200}{}{Fans, fans... You didn't bring paparazzi with you, did you? Good enough.}
{1254}{}{Well... You know, I have some heavy shit on my heart. I tell something important to people - and they don't listen. They think it's just a joke. But they listen to *you*. Because you're serious, even though you don't have much to say. You know what I'm saying?}
