{100}{}{You see a gambler.}
{101}{}{You see a gambler. He is excitedly waving his hands at the sound of geckos running.}

#Кричат во время бегов гекко
{110}{}{Come on! Come on!}
{111}{}{Bring me the money, gecko!}
{112}{}{Run, Toki!}
{113}{}{Please! Please!}
{114}{}{Damn!}
{115}{}{Go!}
{116}{}{What a race!}
{117}{}{Will this one win?!}
{118}{}{What?! Red is in the lead?!}
{119}{}{Too slow!}
{120}{}{Too fast!}
