{100}{}{You see a ghoul-freak.}
{101}{}{You see a man with a bag on his head, barely covering his disfigured skin.}
{102}{}{You'd better not hang out here...}

###################################################
#
# FLOATING PHRASES
# Author: Aleksandr Agafontsev
#
###################################################

#The problems aren't solved
{110}{}{No more drugs?! But that's my only joy...}
{111}{}{No health, no job, no future...}
{112}{}{I'd like to see these pigs in uniform if they had to eat handfuls of pill just to pee once!}
{113}{}{Everyone in here is so ugly... Well, except me, maybe.}
{114}{}{What's the point of this long life if you can't go neither to casino nor to hookers...}
{115}{}{Damn cops...}
{116}{}{They say we are cooking drugs? They are just jealous!}
{117}{}{Freaks? We? You should have seen those in California in 2077...}
{118}{}{I'm so weak that I can't even hang myself...}
{119}{}{I feel so bad...}
{120}{}{Life is a terribly unfair thing...}
{121}{}{In this hotel I feel like I was buried already...}
{122}{}{There was a time I could run one hundred meters in 10 seconds. And now I can't even make it to the toilet in time...}
{123}{}{I can't wait to die...}
{124}{}{I'd like to go to sleep and never wake up...}
{125}{}{And I was a racist! But now I look like a nigger myself...}
{126}{}{Instead of a hat – a smelly bag...}
{127}{}{Did my death got lost somewhere?}
{128}{}{Any job! Even tossing brahmin shit...}
{129}{}{All the smoothskins are ugly bastards...}

#Problem solved
{150}{}{Yes! We will cook the drugs again! Uh... I mean –  justice was served!}
{151}{}{I'm 90 but I feel like I'm only 89!!!}
{152}{}{The only thing left is to have a permission to visit the hookers. And the casino!}
{153}{}{Life is beautiful! And I am too!}
{154}{}{Our hotel is better than any Vegas venue!}
{155}{}{I can't wait to get back to work...}
{156}{}{I'd wear a festive bag in honor of this event!}
{157}{}{We and smoothskins - brothers forever!}
{158}{}{In honor of this would be good to increase the evening dose!}
{159}{}{Glory to the smoothskin wanderer!}
{160}{}{Our problems have been solved by a smoothskin? Life really has changed...}
{161}{}{Life is wonderful!}
{162}{}{Since we often have smoothies here, it's necessary to peel the exfoliated skin and clean the bag...}
{163}{}{::whistles a merry tune::}
{164}{}{But I'll still piss on the shoes of some policeman for last!}
{165}{}{And I even dreamed about death. Now I have a whole life ahead of me!}
{166}{}{Life is just beginning!}
{167}{}{Yes, I can't run! But I can walk further than any smoothskin!}
{168}{}{I'd have called a child in honor of that wanderer, but I forgot how the children are being made...}
{169}{}{Ha-ha! Take that, stupid pigs in uniforms!}
