{100}{}{You see a ghoul-freak.}
{101}{}{You see a man with a bag on his head, barely covering his disfigured skin.}
{102}{}{You'd better not hang out here...}

###################################################
#
# FLOATING PHRASES
# Author: Aleksandr Agafontsev
#
###################################################

#The problems aren't solved
{110}{}{No more drugs?! But that was my only joy...}
{111}{}{No health, no job, no future...}
{112}{}{I'd like to see those pigs in uniform if they had to eat handfuls of pills just to pee once...}
{113}{}{Everyone in here is so ugly... Except me, of course.}
{114}{}{What's the point of this eternal life if you can't go neither to casino nor to hookers...}
{115}{}{Damn cops...}
{116}{}{They say we are cooking drugs? They are just jealous!}
{117}{}{Freaks? We? You should have seen those guys from California in 2077...}
{118}{}{I'm so weak that I can't even hang myself...}
{119}{}{I feel so bad...}
{120}{}{Life is a terribly unfair thing...}
{121}{}{This hotel makes me feel like I've already been buried.}
{122}{}{There was a time I could run one hundred meters in 10 seconds. And now I can't even make it to the toilet in time...}
{123}{}{I can't wait to die...}
{124}{}{I'd like to go to sleep and never wake up...}
{125}{}{And I was a racist! But now I look like a nigger myself...}
{126}{}{Instead of a hat, a smelly bag.}
{127}{}{Is my death got lost on the way?}
{128}{}{Any job! Even tossing brahmin shit...}
{129}{}{All the smoothskins are ugly bastards...}

#Problem solved
{150}{}{Yes! We are cooking the drugs again! Uh... I mean –  the justice is served!}
{151}{}{I'm 90 but I feel like I'm only 89!}
{152}{}{The only thing left is to have a permission to visit the hookers. And the casino!}
{153}{}{Life is beautiful! And I am too!}
{154}{}{Our hotel is better than any Vegas venue!}
{155}{}{I can't wait to get back to work...}
{156}{}{I'd wear a festive bag to honor this event!}
{157}{}{We and smoothskins are brothers forever!}
{158}{}{In honor of this would be good to increase the evening dose!}
{159}{}{Glory to the smoothskin wanderer!}
{160}{}{Our problems have been solved by a smoothskin? Life really has changed...}
{161}{}{Life is wonderful!}
{162}{}{Since we often have smoothies here, I'd better peel the exfoliated skin and clean the bag...}
{163}{}{::whistles a merry tune::}
{164}{}{But I'm still going to piss on some cop's shoes one last time!}
{165}{}{To think I dreamed of dying. Now I have my whole life ahead of me!}
{166}{}{Life is just beginning!}
{167}{}{Yes, I can't run! But I can walk further than any smoothskin!}
{168}{}{I would have named a child after this wanderer, but I had forgotten how babies are made...}
{169}{}{Ha-ha! Take that, stupid pigs in uniforms!}
