{100}{}{You see a guard.}
{101}{}{You see a personal bodyguard of the casino owner.}
{102}{}{Come on in.}

{110}{}{Mr. Wallace is busy. What is this about?}
{111}{}{I need to talk to him. I'm... Erm... Looking for work.}
{112}{}{Busy? Too bad. I'll come later.}
{113}{}{He doesn't deal with that.}
{114}{}{I DEMAND IT! Let me in!}
{115}{}{Too bad. I'll go then.}
{116}{}{I told you... Sorry, sir? [the guard listens to something through the door] Okay, Mr. Wallace, I will throw him out of here. [talks to you] Mr. Wallace doesn't need laymen like you... Get out before I throw you out of the window!}
{117}{}{I will get to your boss anyway! Just you dare not letting me go there!!!}
{118}{}{Okay, I'll calm down and leave.}
{119}{}{I told you... Sorry, sir? [the guard listens to something through the door] Okay, Mr. Wallace. [talks to you] You can come in this time... Hmm... [contemptuously looks over you from head to toe]}
{120}{}{Finally.}
{121}{}{Remove your weapon! Now!}
{122}{}{[Remove the weapon from your hands]}
{123}{}{No way!}
{124}{}{Mr. Wallace is not here. Nobody know when he'll come back.}
{125}{}{Right.}

{126}{}{Sam Riley does not think so.}
{127}{}{Riley? This idiot now considers himself a secretary of Mr. Wallace?}
{128}{}{Yes, he definitely has a bit of megalomania.}
{129}{}{[The guard listens to something through the door] Okay, Mr. Wallace. [talks to you] You can come in this time... Hmm... [carefully and suspiciously looks at you]}
{130}{}{David, your guard at the casino, said otherwise.}
{131}{}{David? Okay, this is enough. [the guard goes inside, then comes back and speaks to you] Mr. Wallace can see you now.}
{132}{}{Thanks.}

{133}{}{Perhaps, Maxson's recommendation will help?}
{134}{}{Maxson? Hmm, boss listens to him lately. Okay, wait here. [the guard goes inside, then comes back and speaks to you] Mr. Wallace can see you now.}
{135}{}{Thanks.}

#Female character
{1116}{}{I told you... Sorry, sir? [the guard listens to something through the door] Okay, Mr. Wallace, I will throw her out of here. [talks to you] Mr. Wallace don't need girls like you... Get out before I throw you out of the window!}
