{100}{}{You see a casino bouncer.}

{101}{}{You see a casino bouncer. He is STRONG.}
{102}{}{You see a casino bouncer. He is hefty. And angry.}
{103}{}{You see a casino bouncer. He suspiciously looks at you.}
{104}{}{You see a casino bouncer. You didn't even think people could be this big.}

{105}{}{Get the hell out!}

#With weapons in the hands
{110}{}{Hey, you! Put the weapon away!}
{111}{}{I'm warning you - put the weapon away!}
{112}{}{No weapons in the casino!}
{113}{}{Put your weapon away!}
{114}{}{Weapons in the casino are forbidden!}
{115}{}{Hey, hide a weapon!}

{116}{}{Again, put the weapon away!}
{117}{}{I repeat, you can't be inside with a weapon!}
{118}{}{I repeat, no weapons in the casino!}
{119}{}{Put that weapon away IMMEDIATELY!}
{120}{}{Weapons in the casino are forbidden!}

{121}{}{Hey, holster your barrel, I will not say twice!}
{122}{}{So, it looks like someone is looking for trouble.}
{123}{}{I'm warning you for the last time.}
{124}{}{Have hearing problems? I can explain with gestures.}
{125}{}{I think someone needs to be disarmed.}
{126}{}{Put your weapon away and nobody will get hurt.}

{127}{}{That's it, bastard, you're in trouble!}
{128}{}{I warned you, asshole!}
{129}{}{You think you're tough? We'll see about that!}
{130}{}{I'm gonna have to teach you manners!}
{131}{}{That's it, consider yourself dead!}
{132}{}{You're in trouble, you bastard!}
{133}{}{WARNING! THE HOSTILE PERSON WITHIN THE CASINO!}

{150}{}{Good evening.}
{151}{}{I'm not allowed to talk with the clients, sorry.}
{152}{}{Any problems?}
{153}{}{What do you want?}
{154}{}{Sorry, I'm not the one you need.}
{155}{}{I don't talk to the clients.}
{156}{}{Better go ask the bartender.}

#Greetings
{157}{}{Good day, ma'am.}
{158}{}{Good day, sir.}
{159}{}{Sorry, I don't talk with the clients.}

#With leper
{180}{}{Hey, freak, this is a casino, not a pub.}
{181}{}{Go join the rest of the freaks, you ghoul.}
{182}{}{Great. Now we tolerate ghouls in our casino.}
{183}{}{Just give me a reason, freak, I'll personally throw you out of here.}
{184}{}{Stay away from me, you sick fuck.}
{185}{}{Don't even try to sneeze in my direction...}
{186}{}{Ghoul? Here?!}
{187}{}{What are you doing in here, freak?}

#Women's replics
{1127}{}{That's it, bitch, you're in trouble!}
{1128}{}{I warned you, bitch!}
{1129}{}{You think you're tough? We'll see about that!}
{1131}{}{That's it, consider yourself dead!}
{1132}{}{You're in trouble, bitch!}
{1162}{}{Nothing. Leave.}
