{10}{}{ }
{11}{}{ }

{100}{}{You see a casino client.}
{101}{}{You see your client.}

{102}{}{What is this, a new fashion trend? Take off that rag from your head, if you want to talk to me.}
{103}{}{I just wanted to relax. It seemed like today is a nice day for this.}

{104}{}{What do you want? [examines you from head to toe until a sudden realization hits him after he sees a pizza in your hands] Are you kidding me?! I ordered a pizza God knows when! And now, when I've already had a dinner, it is absolutely useless. Get out of here, courier, and tell your boss to *fire* you!}
{105}{}{[Go away]}
{106}{}{What do you want? [examines you from head to toe until a sudden realization hits him after he sees a pizza in your hands] Where the hell have you been, courier!? How long do I have to wait? Ten more minutes and I would have died of hunger, now give me the pizza and get out of here!}
{107}{}{It's }
{108}{}{$, sir.}
{109}{}{For what!? Your lousy service? To hell with you, here's the money, just give me the pizza. [He tosses you the money - some change and crumpled bills]}
{110}{}{The hell is wrong with you people? Maybe you should stop ordering pizza at all.}
{111}{}{Thank you, sir. Bon appetite and good day to you! Sam Phillips' cafe is always happy to open its doors to you. All the best!}
{112}{}{[Go away]}
{113}{}{[Widens eyes] I didn't expect such a wild arrogance!! Where do they find such savages in this city! I'll be damned if I'm going to use this delivery service again! Uh... Get out!}
{114}{}{[Stares at you] You are talking like some dude from TV. But... You talk nice. Okay, now leave, I don't like people watching me eat.}

{150}{}{You see one of the casino patrons. He looks tired.}
{151}{}{You see one of the casino patrons. His eyes sparkle with excitement.}
{152}{}{You see one of the casino patrons. He covers his face.}
{153}{}{You see one of the casino patrons. He looks a little tipsy.}
{154}{}{You see one of the casino patrons. He winks at you and wobbly goes away.}
{155}{}{You see one of the casino patrons. He's trying to get the waitress's attention.}
{156}{}{You see one of the casino patrons. She looks tired.}
{157}{}{You see one of the casino patrons. Her eyes sparkle with excitement.}
{158}{}{You see one of the casino patrons. She covers her face with her hands.}
{159}{}{You see one of the casino patrons. She looks a little tipsy.}
{160}{}{You see one of the casino patrons. She winks at you and wobbly goes away.}
{161}{}{You see one of the casino patrons. She is trying to attract the attention of the waiter.}

#In-game messages:
{280}{}{Lady Luck, don't let me down.}
{281}{}{Let's play dice.}
{282}{}{Baby needs a new pair of shoes...}
{283}{}{Damn poor tourists...}
{284}{}{Dammit! I was *53* chips up, but then...}
{285}{}{That's really unlucky...}
{286}{}{So close!}
{287}{}{Now I'll break the bank.}
{288}{}{Me? I'm breaking the bank. Look.}
{289}{}{Everything was against me.}
{290}{}{Lady Luck turned away from me.}
{291}{}{Will someone come to my funeral?}
{292}{}{The bank had mercy on me.}
{293}{}{Between the tips and these huge sums of money spent while being drunk...}
{294}{}{Keep betting like that and very soon you will find yourself at Golgotha...}
{295}{}{Waitress, another drink!}
{296}{}{Waiter, another drink!}
{297}{}{These drinks taste... Odd.}
{298}{}{I have a fever!}
{299}{}{I already lost all my money.}
{300}{}{Luck is a flighty bitch. So is the mother of my better half.}
{301}{}{So-so...}
{302}{}{Oh, do not disappoint me!}
{303}{}{Go, my dear!}
{304}{}{Wherever you go, everywhere are these damn scammers...}
{305}{}{Great, another beggar.}
{306}{}{I'm SO lucky.}
{307}{}{I'll get enough sleep in a coffin.}
{308}{}{Look, I need to pee. I already feel sick to my stomach.}
{309}{}{Man, I gotta drain the snake.}
{310}{}{Damn, they let anyone in here.}
{311}{}{Come on, I need seven!}
{312}{}{You've got the character, baby.}
{313}{}{Who's the big winner tonight? It's Mikey!}
{314}{}{Don't lose... Come on...}
{315}{}{If only we could negotiate...}
{316}{}{This is SUCH a bullshit.}
{317}{}{I've managed to lose only 60 chips. In the first five minutes.}
{318}{}{Red 23! Red 23! Come on... Red 23...}
{319}{}{50 chips on black 15...}
{320}{}{Ball's circling the roulette... Guess which cell...}

#Win
{321}{}{Heh!}
{322}{}{Ha! Now the bank is mine!}
{323}{}{Hey, I actually won? Hell yes!}
{324}{}{Now it's MINE! Ha-ha-ha!}
{325}{}{Damn goats, I won!}
{326}{}{And they said that it's a scam!}
{327}{}{::jumps with joy::}
{328}{}{::claps::}
{329}{}{It's my win!!!}

#Lost
{330}{}{Dammit!}
{331}{}{Fucking bad luck}
{332}{}{I lost *again*!}
{333}{}{It's okay, I still have some change.}
{334}{}{Damn, am I going to win it back?}
{335}{}{I'll tear that bastard to pieces!}
{336}{}{I lost... It sucks...}
{337}{}{Am I a loser?}
{338}{}{It's time to quit...}
{339}{}{I'm amazed I suck this bad.}
{340}{}{Soon, I will be left with nothing.}