{100}{}{You see a resident.}
{101}{}{You see a local resident. He looks somewhat unhealthy.}
{102}{}{Oh, I feel so sick... Why is there no doctor?}

{103}{}{This patient's symptoms are somewhat confusing. You are not experienced enough to understand them.}
{104}{}{It's that difficult, huh?}
{105}{}{This man appears to be suffering from intoxication.}
{106}{}{Hey, Doc, can it be cured?}
{107}{}{Thanks, Doc.}

{108}{}{You have already diagnosed this patient as suffering from drug intoxication.}

{110}{}{Are you really a doctor? Can you cure me?}
{111}{}{First, I need to know what drug you were taking.}
{112}{}{I'm afraid it will be your problem until I figure out a solution.}
{113}{}{Drugs?! From where?! All I've been consuming lately is local food from the bar downstairs. And booze, of course. They decided to poison their customers? That's pretty weird.}
{114}{}{Okay, I see. It sounds like someone added drugs to your alcohol to make you addicted. This can only be compensated by other drugs - or total withdrawal, which won't be easy to endure.}
{115}{}{Hmm, tough case. There is no other way but to use other drugs. But right now I can't think of anything specific. When I find a solution, I'll visit you.}

{116}{}{So I was drugged... How could that happen? And... What kind of drugs should I take?}
{117}{}{Psycho. Yes, I won't hide it, you can become an addict, but before you do, it will remove all the current negative effects.}
{118}{}{Anti-smoker would compensate the effects of the drug and smooth out the shakes.}
{119}{}{You'd better try to get through the withdrawal. I'm telling you this as a doctor. Drugs are too dangerous because you can develop an addiction. Or worse.}
{120}{}{Really? Hell, I'd give all my money for the dose, if that would help! But where can I get it? Doc, you don't happen to have one with you, right?}
{121}{}{Sure. But not so fast, money first. $500 will be enough.}
{122}{}{I do. And keep your money to yourself.}
{123}{}{I don't have it. Yet.}
{124}{}{Well, thank you. [takes a dose] Wow... Really... I'm starting to feel so good... All the body is getting so obedient...}
{125}{}{Yeah. Get well.}

{126}{}{Sure. But not so fast, money first. $200 will be enough.}
{127}{}{Damn, this is going to be a hot night... But since the doctor says so, I'll do it. I'll try to endure.}
{128}{}{Great. Put a moisten towel on your forehead, make a gag and put it in your mouth so you wouldn't damage your teeth. And also... Get well soon.}
