{100}{}{You see a resident.}
{101}{}{You see a local resident. He looks somewhat unhealthy.}
{102}{}{Oh, I feel so bad... Why there is no doctor?}

{103}{}{Symptoms of this patient are somewhat confusing. You are not skilled enough to make sense out of them.}
{104}{}{Everything is that bad, huh?}
{105}{}{It seems that this person suffers from intoxication.}
{106}{}{Hey, Doc, can it be cured?}
{107}{}{Thanks, Doc.}

{108}{}{You already diagnosed this patient: narcotic intoxication.}

{110}{}{Are you really a doctor? Can you cure me?}
{111}{}{Firstly I need to know what drug you have taken.}
{112}{}{I'm afraid it will remain your problem until I can figure out a solution.}
{113}{}{The drugs?! From where!? And recently I only ate some local food from the bar downstairs. Well, and booze, of course. They decided to poison their clients? This is rather strange.}
{114}{}{Okay, I see. Someone had added some drugs into your booze to cause the addiction, probably. This can be compensated only by other drugs or by withdrawal and "the shakes".}
{115}{}{Hmm, a hard case. There is no other way except using side chemicals. But nothing comes to my mind now. When I come up with a solution I'll visit you.}

{116}{}{The shakes? How could that happen! Oh... And what kind of drugs?}
{117}{}{Psycho. Yes, I won't hide it from you, you can become an addict, but before that it will remove all the current negative effects.}
{118}{}{Anti-smoker would compensate the effects of the drug and smooth out the shakes.}
{119}{}{You'd better go through 'the shakes' stage. Speaking as a medical doctor. Drugs are too dangerous because you can become an addict. Or even worse.}
{120}{}{Really? Hell, I'd give all my money for the dose, if that would help! But where can I get it? Doc, don't you have one lying around, huh?}
{121}{}{Sure. But not so fast, money in advance. $500 will be enough.}
{122}{}{I do. And keep your money to yourself.}
{123}{}{I don't have it. Yet.}
{124}{}{Well, thank you. [takes a dose] Wow... Really... I'm starting to feel so good... All the body is getting so obedient...}
{125}{}{Yeah. Get well.}

{126}{}{Sure. But not so fast, money in advance. $200 will be enough.}
{127}{}{Damn, this is going to be a hot night... But since the doctor says so, then so be it. I'll try to endure.}
{128}{}{Great. Moisten your sheet with water, make a gag and put it in your mouth so your teeth won't be damaged. And also... Be well.}
