{100}{}{You see: Supervisor}
{101}{}{You see the Vault City maintenance supervisor.}
{102}{}{What did Joshua screw up this time?}
{103}{}{Citizen? Please don't distract Joshua, he's on a tight schedule.}
{104}{}{What have I done...}
{105}{}{Don't try that again!}
{106}{}{*error executing script*}

{110}{}{Hello, }
{111}{}{. Did you want something?}
{112}{}{What can you tell me about Joshua?}
{113}{}{Did you know Joshua lost one of the scouting robots?}
{114}{}{Could you let me use your computer?}
{115}{}{Tell me about your department.}
{116}{}{I got this piece of information from the nearby nuclear power plant. What can you tell me about it?}
{117}{}{Don't worry.}

{120}{}{Absolutely. We maintain all of the city's technology, from simple lights to computers, terminals, and robots.}
{121}{}{I fixed that light your man was having trouble with.}
{122}{}{Oh, uh... Yeah, I heard. It's hard to find experienced workers these days, you know? Well, anyway, thanks for the help, }
{123}{}{.}
{124}{}{Absolutely not! The information on our servers can be dangerous to common citizens! The Overseer declared it classified. Try logging a request with the Information Bureau and they'll decide what you can and can't see.}
{125}{}{That's enough.}
{126}{}{*Another* one? No, I don't think so. If he did, he'd tell me.}
{127}{}{Here's the holodisk from the missing robot. Believe me now?}
{128}{}{[Sigh] I feel bad for him, I really do. He has a lot on his plate. But he's already lost two robots, and that puts him on thin ice. We need these robots to work in hazardous zones, and they're not easy to replace. Joshua's received a number of warnings already. If he can't be trusted, he must be isolated.}
{129}{}{That's a little harsh, don't you think?}
{130}{}{No, I don't. Rules are rules. If we can't uphold the laws written by the committee and the Overseer, then there will be chaos in the city.}
{131}{}{Joshua lied to me? That's it, no more kid gloves. I'll have the committee place Joshua in correctional isolation.}
{132}{}{That's right! He deserves no less!}
{133}{}{Well, if you say so.}
{134}{}{Thank you for telling me this, }
{135}{}{! You did the right thing, exposing this vermin! Keep it up. Oh, and long live Vault City!}
{136}{}{Of course.}

#Радио (в 1.00 не используется)
{140}{}{Hmm, interesting. It looks like a list of nearby radio stations and their broadcasting parameters. We probably won't be able to listen to them, though.}
{141}{}{Where are those stations located?}
{142}{}{Uh... I'm afraid that's classified...}
{143}{}{Then there's no way in hell you're getting this then!}
{144}{}{What?! You wouldn't... If I tell the Overseer how the wastes have changed you...}
{145}{}{What? It's just a simple request. But... I think I'll let you be, just in case.}
{146}{}{...then I'll tell him how you drove Joshua insane. How does that sound?}
{147}{}{Too bad. I think I'll go.}
{148}{}{I never thought I'd hear that from one of our own citizens. Is this really what the wastes do to a man? Fine, I won't argue, if you're capable of *that*.}
{149}{}{Perfect. We'll go our separate ways, then.}
{150}{}{I cross-compared the information with our own data. It looks like only two of these locations are somewhere nearby. One is the nuclear power plant to the north, and the other is a few days to the south-east. Here, I'll mark it on your map.}
{151}{}{You have learned of a new location in the south-east}
{152}{}{Hey, this is Cheyenne's territory! That's interesting...}
{153}{}{That will keep me busy, at least...}

#Починка поезда
{160}{}{Can you help fix this onboard computer?}
{161}{}{I can't do that for you while your citizenship is suspended. I'll need authorization from Peter Graves. If he gives the okay, I'll do my best to help you.}
{162}{}{Understood.}
{163}{}{Sure thing. Sergeant Graves gave the okay. Let me take a look at it.}
{164}{}{Here you go.}
{165}{}{Actually, I'll try and fix it myself.}
{166}{}{You found a simple way to fix the train.}

#Таймерное событие
{200}{}{Joshua! Get over here!}
{201}{}{You bastard! You ratted me out!}
{202}{}{Too late.}
{203}{}{To hell with this! You won't get me!}
{204}{}{Josh! Stop!!!}
{205}{}{Halt, citizen!}
{206}{}{Get back here, citizen!}
{207}{}{Joshua has fled the city in depression. You're pretty sure you won't be seeing him again.}

#Female character
{1103}{}{Citizen? Please don't distract Joshua, he's on a tight schedule.}
{1121}{}{I fixed that light your man was having trouble with.}
{1134}{}{Thank you for telling me this, citizen.}
{1148}{}{I never thought I'd hear that from one of our own citizens. Is this really what the wastes do to a woman? Fine, I won't argue, if you're capable of *that*.}
{1201}{}{You bitch! You ratted me out!}
