{100}{}{You see Orris.}
{101}{}{This guy does not look particularly friendly. But you must say, manners, hair and leather jacket all make him look stylish.}
{102}{}{Come closer... Time to die!}

{110}{}{What is it?}
{111}{}{Nothing.}
{112}{}{I'm on business here. What are you doing?}
{113}{}{On business... I'm on business too. And this business doesn't concern you.}
{114}{}{So you're the one who owns that thief Kevin in the Clean City?}
{115}{}{Huh? Never heard of him.}
{116}{}{He was caught in the act and spat everything out.}

{117}{}{F-fucking pussy... I don't know why you're interested in that boy, is it pity or something else? But know this - he was a thief long before I showed up.}
{118}{}{Hmm. Tell me, how did he end up owing you.}
{119}{}{Something tells me you don't do it because you like him.}
{120}{}{Let me cut to the chase: how much does he owe you?}
{121}{}{Tell me about your gang.}
{122}{}{It's time for me to go. Bye.}

{123}{}{His parents died some time ago. Only his elder sister is left. I wanted to help her, honestly. Paid for her treatment, but in the end she died too. That boy lived off my money for some time. I took care of him, supported him all this time. But now it's time for him to bring something to the table.}
{124}{}{Consider for now that I'm Kevin's brother: I take care of him, feed him, I treated his sister. What else do you want?}
{125}{}{[Laughs] Time goes - the debt grows. It's a lot of money. But listen, if you want to help him so bad, then we can make a deal. Bring me a laser pistol, a police model. It's an expensive toy, you can only get one in Clean City. Can you do it? If you do, we can consider Kevin's debt paid off.}
{126}{}{About the Kings? Well, we are quite famous. We have many nasty fellas in our gang and we are all around the city. I advise you not to get in our way. If not for the police, we would rule the whole Vegas already.}

{127}{}{Right. You tricked the boy in order to make him feel guilty. And he turned out a good pickpocket. And now you want to "milk" him infinitely.}
{128}{}{[Surprised] I sense thieves from a mile away. And I saw TALENT in Kevin. And I see that you're not so bad yourself. But that spot in Vegas is occupied. So steer clear of my turf.}

{129}{}{It just so happens I have this pistol. Here, take it. Are we done?}
{130}{}{I managed to get the pistol. Here, take it. Are we done now?}
{131}{}{[Smiles, examining the pistol] Debt? There was no debt. I tricked the boy, because even back then I knew that he would make a great pickpocket. But I was honest about his sister. We had a relationship. And I really cared about her. I just didn't have enough time to... Look. The boy is free now. Just tell him to steer clear from the outskirts of Vegas.}
{132}{}{What do you mean?}
{133}{}{Think. What will he do now? He was under my protection, there's a whole gang covering my back. At least he had a purpose in life and a stable income. And now? I don't know. He will die on the streets - then you'll remember me.}
{134}{}{Don't you count on that!}
{135}{}{Hmm. Maybe.}
{136}{}{Fine.}

#Çàêëþ÷åííûé
{150}{}{Your friend Murphy is in jail. He's asking you for help.}
{151}{}{Murphy... What did that cretin do again?}
{152}{}{Cops say he stole some money, but the story seems pretty shady.}

{153}{}{And you? Why are you running around for somebody else? What is your interest?}
{154}{}{Well, Murphy said I would get a reward...}
{155}{}{It's just what I am. I like helping people.}
{156}{}{It's hard for me to say no to people. I lose that feeling of purpose and self-esteem in life.}
{157}{}{Ha! I'm not going to pay you anything. Now, if you do me a favor and help me deal with Murphy, THEN we can talk about a reward.}
{158}{}{I don't know what the fuck you're talking about. Nobody does anything without personal gain in Vegas. You scratch my back, I scratch yours. Get it? So, maybe we can make a deal.}
{159}{}{You're the conceited type. Usually I like that... Until they start getting in my way. But we can find a common interest. Do you want to hear my offer?}
{160}{}{What do you have in mind?}

{161}{}{Murphy is dangerous. It was great dealing with him, sure. We had known each other since we were kids... But if he cracks and gives all our secrets to the cops, we'll have to leave the city.}
{162}{}{Really, the most simple thing to do is to kill him.}
{163}{}{I don't do murder, it's not really my thing.}
{164}{}{Wait, that's not my problem. My job is to deliver the message from Murphy. You figure it out on your own.}

{165}{}{You must be tough to say things like that. How about a deal? If you kill Murphy before he snitches us out, I will try to do you a favor in return. Deal?}
{166}{}{Whatever you say, I can't make you. But if you find a way to get Murphy out of trouble, you will get what you deserve. Deal?}
{167}{}{Yeah... Sure... You're useless. Go away! But if you change your mind - come up with a way to eliminate that cretin.}
{168}{}{How would I do that in a guarded area full of cops?}
{169}{}{Judging by your looks, you can't pay. What's the catch?}
{170}{}{I will think about it.}
{171}{}{I've been in jail once, when I was a kid. So, I know they don't give water to prisoners from the common tap, but from another canister. If you poison the water, every person in the cage will end up dead. Not an ideal solution, but it is better than going against a building full of cops. But maybe for you it's not. I don't know what to expect from you.}
{172}{}{I have the right connections to get some military drugs. Psycho, Buffout, that kind of thing. I will look everywhere, and I will get it, no matter the cost.}
{173}{}{What can you repay me with if I solve the...Murphy problem...?}
{174}{}{[Leave]}
{175}{}{Did you hear the news? Murphy managed to avoid the prison. Now he's free and happy.}

{180}{}{You wish is granted - Murphy is dead.}
{181}{}{You did it?! Damn, you're dangerous one... I promised to pay you. I have connections, I can get some military drugs. Interested? Psycho, Buffout, Mentats - just say a word, I will make it happen.}
{182}{}{[2 Psycho]}
{183}{}{[2 Buffout]}
{184}{}{[2 Mentats]}
{185}{}{[3 Stimpaks]}
{186}{}{Here you go, have all you need. And don't tell anyone about this. Especially in Clean City. Otherwise, our guys will find you and do the same thing you did to Murphy.}
{187}{}{No problem friend. Don't worry.}
{188}{}{Just don't threaten me. Think about your future.}
{189}{}{This means, there's no point in waiting. Let's start right now! [Attack]}

#Female character
{1153}{}{And you? Why are you running around for somebody else? What is your interest?}
{1186}{}{Here you go, have all you need. And don't tell anyone about this. Especially in Clean City. Otherwise, our guys will find you and do the same thing you did to Murphy.}
