{100}{}{You see Orris.}
{101}{}{This guy does not look particularly friendly. But must say, manners, hair and leather jacket make him look stylish.}
{102}{}{Come closer... Time to die!}

{110}{}{What is it?}
{111}{}{Nothing.}
{112}{}{I'm on business here. What are you doing?}
{113}{}{On business... I'm on business too. And it should not concern you, what business it is.}
{114}{}{So you're the one that owns thief Kevin in the Clean City?}
{115}{}{Huh? never heard of him.}
{116}{}{He was caught in action and spat everything out.}

{117}{}{F-fucking pussy... I don't know, why are you interested in that boy, perhaps, pity or something else. But you know, he was a thief long before I showed up.}
{118}{}{Hmm. Tell me, how did he ended up owing you.}
{119}{}{Something tells me, that it's not because you like him.}
{120}{}{Let me make it short: how much does he owes you?}
{121}{}{Tell me about your gang.}
{122}{}{It's time for me to go. Bye.}

{123}{}{His parents died a year ago. Only his elder sister left. I wanted to help her, honestly. Paid for her treatment, but in the end she died too. That boy lived for some time on my money. I took care of him, supported him all this time. But it's time to bring something to the table.}
{124}{}{Consider from now on, that I'm Kevin's brother: accepted him, took care of him, fed, treated his sister. What more do you want?}
{125}{}{[Laughs] Time goes - the debt grows. It's a lot of money. But listen, if you want to help him so bad, then we can make a deal. Bring me a laser pistol, police model. It's an expensive toy, you can only get one in Clean City. Can you do it? If you will, we can consider Kevin's debt paid off.}
{126}{}{Kings gang? Well, we are famous in Vegas. We have many nasty fellas all around the city. I don't advise you getting in their way. If not for the police, we would rule the whole Vegas long time ago.}

{127}{}{Right. You tricked the boy, in order to make him feel guilty. And he turned out a good pickpocket. And now you think to "milk" him infinitely?}
{128}{}{[Surprised] I sense thieves from a mile away. And I saw TALENT in Kevin. And you too, I see, not bad yourself. But the spot in Vegas is occupied. So steer clear from my turf.}

{129}{}{It just so happened that I have this pistol. Here, take it. Are we done?}
{130}{}{I managed to get the pistol. Here, take it. Are we done now?}
{131}{}{[Smiles, examining the pistol] Debt? There was no debt. I tricked the boy, because I knew even back then, that he would make a great pickpocket. But I was honest about his sister. We were in relationship. And I really looked for medicines for her. I just didn't have enough time... Look. The boy is free. Just tell him to steer clear from the outskirts of Vegas.}
{132}{}{What do you mean?}
{133}{}{Think. What will he do now? I provided him protection, and a gang have my back. He at least had purpose in life and stable income. And what now? I don't know. He will die on the streets - then you'll remember me.}
{134}{}{Don't you count on that!}
{135}{}{Hmm. Maybe.}
{136}{}{Fine.}

#Заключенный
{150}{}{Your friend Murphy is in jail. He asks you for help.}
{151}{}{Murphy... What is that cretin did now?}
{152}{}{Cops say, he stole money, but the story is pretty shady.}

{153}{}{And you? Why are you running around for somebody else? What is your interest?}
{154}{}{Well, Murphy told, I will be rewarded...}
{155}{}{It's just what I am. I like helping people.}
{156}{}{It's hard for me to say no to people. I lose the feeling of purpose and self-esteem in life.}
{157}{}{Ha! I'm not going to pay for anything. Now, if you do me a favor and help deal with Murphy - then we can think about something a reward.}
{158}{}{I don't know what the fuck are you talking about. Nobody does anything without personal gain in Vegas. You do for me, I do for you. Do you understand? So maybe, we can make a deal?}
{159}{}{You're conceited type. Usually I like such people, until they start getting in my way. But we can find a common interest. Do you want to hear my offer?}
{160}{}{What do you have in mind?}

{161}{}{Murphy is dangerous. It was great with him, sure. We know each other since we were kids... But if he breaks and gives all our secrets to cops, then it would be better for us to get out of the city.}
{162}{}{Really, the most simple thing to do is to kill him.}
{163}{}{I don't do murder, not my profile.}
{164}{}{Wait, that's not my problem. My job is to deliver the message from Murphy. From there you figure it out on your own.}

{165}{}{You must be tough, to say things like this. How about a deal? If you kill Murphy before, he snitches us out, I will try to do you a favor in return. Deal?}
{166}{}{Whatever you say, I can't make you. But if you find a way to get Murphy out of trouble, I won't make you wait for the reward. Deal?}
{167}{}{Yeah... Sure... You're useless. Go away! But if you change your mind, then think, how to eliminate that cretin.}
{168}{}{But HOW, damn it, I can do that in guarded area full of people?}
{169}{}{Judging by your looks, you can't pay. What's the catch?}
{170}{}{I will think about it.}
{171}{}{I've been in jail once, when I was a kid. So, I know they don't give water to prisoners from the common tap, but from the toilet-canister. If you poison the water, every caged would be dead. Not an ideal solution, but it is better to that going against a building full of cops. Even if I don't know, what to expect from you.}
{172}{}{I have the right connections, to get military drugs. Psycho or Buffout- your choice, I will look everywhere, but I will get it, no matter the costs.}
{173}{}{What can you repay me with, if I solve the problem with Murphy?}
{174}{}{[Leave]}
{175}{}{Did you hear the news? Murphy managed to avoid the prison. Now he's free and happy.}

{180}{}{You wish is granted - Murphy is dead.}
{181}{}{You did it?! Damn, you're dangerous one... I promised to repay you. I have connections, in order to get some military drugs. Interested? Psycho, Buffout, Mentats - just say a word, I will make it happen.}
{182}{}{[2 Psycho]}
{183}{}{[2 Buffout]}
{184}{}{[2 Mentats]}
{185}{}{[3 Stimpaks]}
{186}{}{Here you go, have all you need. And don't tell anyone about this. Especially in Clean City. Otherwise, our guys will find you and do the same thing, that you did to Murphy.}
{187}{}{No problem friend. Don't worry.}
{188}{}{Just don't threaten me. Think about your future.}
{189}{}{This means, there's no point in waiting. Let's start right now! [Attack]}

#Female character
{1153}{}{And you? Why are you caring about Murphy? The handsome guy got under your skirt?}
{1186}{}{Here you go, have all you need. And don't tell anyone about this. Especially in Clean City. Otherwise, our guys will find you and do the same thing, that you did to Murphy.}
