#Описания
{100}{}{You see a stranger.}
{101}{}{You see Maxson.}
{102}{}{You see a stranger. He looks somehow familiar. He definitely reminds you of someone.}
{103}{}{It's Bald Maxson from Big Louie's gang! It's him, for sure!}

{104}{}{Big Louie's dirty business is done. You get 1000 experience points.}
{105}{}{You found Maxson. So that's where he laid down after New Reno!}

#Диалог когда ГГ НЕ помог ему бежать из Рино
{110}{}{Huh? What? [looks at you and then quickly turns away] I do not communicate with clients, sorry. All questions to the administrators.}
{111}{}{Huh? What? [looks at you and then quickly turns away] Okay, all questions to the administrators. And I ask you to leave my office.}
{112}{}{If you're not an administrator, who are you then?}
{113}{}{Fine, I'll leave you alone.}

{114}{}{I don't work with clients in this... [He looks and you suddenly pulls himself together]... Dammit! Didn't you hear me? You want me to call security? I repeat - I don't talk to clients, I ask you to leave my office.}
{115}{}{I don't work with clients in this... [He looks and you suddenly pulls himself together]... Dammit! Didn't you hear me? You want me to call security? I repeat - I don't talk to clients, I ask you to leave me alone.}
{116}{}{Wait, why are you reacting like this? What is the problem?}
{117}{}{Okay, okay, I'll leave you alone.}
{118}{}{Okay, let's get this over with! Right here, right now! This is what you want, isn't it?}
{119}{}{Okay prepare yourself, scum! You asked for it! [attack]}
{120}{}{No, I don't want any trouble, I'll leave peacefully.}

{121}{}{Wait, I remember you...}
{122}{}{What, finally got it? Yes, it is me! A dirty raider from a gang of paranoid bastard in the past, but now a completely different person - a respectable citizen with a prestigious job in downtown Vegas. Isn't that amazing, eh?}
{123}{}{But... How?!}
{124}{}{Doesn't matter. It's time to pay, baldy. Die!}
{125}{}{The skills of the local surgeon, the fees of my new boss and my personal ability to make miracles. Now I am a different person. You have to leave me alone, or you won't get out of this casino.}
{126}{}{You think I'm scared? Let's see what you've got! [attack]}
{127}{}{Okay, Maxson, I won't bother you. Calm down.}

#Плавающие фразы при попытке заговорить после того, как ГГ его распознал
{130}{}{You're asking for it!}
{131}{}{Guys! Someone is asking for it here!}
{132}{}{Hey, guys! Throw him outside!}
{133}{}{Stay away from me, you hear?!}
{134}{}{What?! You're asking for it again?!}
{135}{}{You want to catch a bullet, huh?! Okay then!}

#Диалог когда ГГ помог ему бежать из Рино
{150}{}{I don't work with clients in this... [He looks and you suddenly pulls himself together]... Dammit! Look who is there! I didn't expect to meet my friends in this part of Nevada. What are you doing here, fuck me gecko?!}
{151}{}{Maxson... You actually made it to Vegas!}
{152}{}{Yes, it's me. A dirty raider from a gang of paranoid bastard in the past, but now a completely different person - a respectable citizen with a prestigious job in downtown Vegas. Isn't that amazing, eh?}
{153}{}{How did you change your appearance?}
{154}{}{How did you get here?}
{155}{}{Do you work for the casino now?}
{156}{}{I'm glad to see you, but I have to go.}
{157}{}{The skills of the local surgeon, the fees of my new boss and my personal ability to make miracles. Changed my hairstyle and did a little job on my nose. It was enough to make anyone from the past not recognize me.}
{158}{}{What surgeon?}
{159}{}{Who is your boss now?}
{160}{}{With a stagecoach, obviously. It's the only safe way to get across the Great Nevada ring.}
{161}{}{Not exactly for the casino, I'd say. For Hal Wallace personally. Don't ask, or I'll have to kill you. Just kidding.}
{162}{}{Rob Reiner. He sits down in the underground. No idea how to contact him. I was taken to his laboratory at night, blindfolded. And I was sedated after surgery.}
{163}{}{Hal Wallace, who else? He owns the casino and has... Some other businesses in the city. Very powerful man, someone you should stay friends with, trust me.}
{164}{}{Until recently it was Hal Wallace... But his assistants are still in the casino, so it's still going without him.}
{165}{}{I want to work for him too! Can you recommend me?}
{166}{}{Hmm... I don't know how much my word means to my boss, but I can try. Talk to his head guard and tell him Maxon sent you. Maybe he'll listen.}
{167}{}{Thanks, Maxson.}

{168}{}{What's up, old pal? How are you doing?}
{169}{}{Heard the news about big Louie?}
{170}{}{That he abandoned the gang and performs in the "Hard Rock" now? Yes, I've heard. I will have to stay in the Clean City for some time.}
{171}{}{Aren't you surprised?}
{172}{}{Honestly? I knew it would turn out like that. He was forced to become a raider, but he always dreamed to be a musician.}

#Female character
{1130}{}{You're asking for it!}
{1131}{}{Guys! Someone is asking for it here!}
{1132}{}{Hey, guys! Throw her outside!}
{1133}{}{Stay away from me, you hear?!}
{1134}{}{What?! You're asking for it again?!}
{1135}{}{You want to catch a bullet, huh?! Okay then!}
{1168}{}{What's up, gal? How are you doing?}
