#Описания
{100}{}{You see a stranger.}
{101}{}{You see Maxson.}
{102}{}{You see a stranger, looking... Familiar. He reminds you someone.}
{103}{}{It's Bald Maxson from Big Louie's gang! It's him, for sure!}

{104}{}{Big Louie's dirty business is done. You get 1000 experience points.}
{105}{}{You found Maxson. So that's where he laid down after New Reno!}

#Диалог когда ГГ НЕ помог ему бежать из Рино
{110}{}{Huh? What? [looks at you and then quickly turns away] I do not communicate with clients, sorry. All questions to the administrators.}
{111}{}{Huh? What? [looks at you and then quickly turns away] Okay, all questions to the administrators. And I'll ask you to leave my office.}
{112}{}{If you're not an administrator, who are you then?}
{113}{}{Fine, I'll leave you alone.}

{114}{}{I don't work with clients in this... [He looks and you suddenly pulls himself together]... Dammit! Didn't you hear me? You want me to call security? I repeat - I don't talk to clients, I'll ask you to leave my office.}
{115}{}{I don't work with clients in this... [He looks and you suddenly pulls himself together]... Dammit! Didn't you hear me? You want me to call security? I repeat - I don't talk to clients, I'll ask you to leave me alone.}
{116}{}{Wait, why reacting like this? What is the problem?}
{117}{}{Okay-okay, I'll leave you alone.}
{118}{}{Okay, let's get this over with. Right here right now! This is what you want, do you?}
{119}{}{Okay prepare yourself, scum! You asked for it! [attack]}
{120}{}{No, I don't want any trouble, I'll leave peacefully.}

{121}{}{Wait, I remember you...}
{122}{}{What, finally got it? Yes, it is me! A dirty raider from a paranoid bastard's gang in the past, but now totally different person - a respectable citizen with the prestigious work in downtown Vegas. Isn't that surprising, huh?}
{123}{}{But... How?!}
{124}{}{Doesn't matter. It's time to pay, baldy. Die!}
{125}{}{The skills of the local surgeon, the fees of my new boss and my personal ability to create real miracles. Now I am a different person, forget about me. Otherwise you won't get out of this casino.}
{126}{}{You think, I'm scared? Well, okay, show me what you got! [attack]}
{127}{}{Okay, Maxson, I won't bother you. Calm down.}

#Плавающие фразы при попытке заговорить после того, как ГГ его распознал
{130}{}{You're asking for it!}
{131}{}{Brothers! Someone is asking for it here!}
{132}{}{Hey, guys! Throw him outside!}
{133}{}{Stay away from me, you got that?!}
{134}{}{What?! You're asking for it again?!}
{135}{}{You want to catch a bullet, huh?! Okay then!}

#Диалог когда ГГ помог ему бежать из Рино
{150}{}{I don't work with clients in this... [He looks and you suddenly pulls himself together]... Dammit! Well who do I see! I didn't expect to meet my friends in this part of Nevada. How did you get here, fuck me gecko?!}
{151}{}{Maxson... You managed to get to Vegas.}
{152}{}{Yes, it's me. A dirty raider from a paranoid bastard's gang in the past, but now totally different person - a respectable citizen with the prestigious work in downtown Vegas. Isn't that surprising, huh?}
{153}{}{How did you managed to change your appearance?}
{154}{}{How did you get here?}
{155}{}{Now you work for the casino?}
{156}{}{I was glad to see you, but I have to go.}
{157}{}{The skills of the local surgeon, the fees of my new boss and my personal ability to create real miracles. Not much - just changed my hairstyle and did a surgery on my nose. That was enough to make anybody from the past not recognize me.}
{158}{}{What surgeon?}
{159}{}{Who is your boss now?}
{160}{}{With stagecoach, obviously. Only with these guys one can safely move along the Great Nevada ring to the other side.}
{161}{}{Not exactly in the casino, more likely for Hal Wallace personally. Don't ask. Otherwise I will have to kill you. Joking.}
{162}{}{Rob Reiner? He sits down in the underground. No idea how to contact him. I was taken to his laboratory at night, blindfolded, and brought and I was sedated after surgery.}
{163}{}{Hal Wallace, who else? He owns the casino and has... Some other business in the city. Very powerful man, someone you should stay friendly, trust me.}
{164}{}{Until recently it was Hal Wallace... But his assistants are still in the casino, so the work is still going on without him.}
{165}{}{I want to work for him too! Can you recommend me?}
{166}{}{Hmm... I don't know, how much my word means to my boss, but I can try. Talk to his main guard and tell him, that Maxson sent you. Perhaps he will listen.}
{167}{}{Thanks, Maxson.}

{168}{}{What's up, old pal. What is it now?}
{169}{}{You know the news about big Louie?}
{170}{}{That he abandoned the gang and performs in the "Hard Rock"? Yes, I heard. I will have to stay in the Clean City for some time.}
{171}{}{Aren't you surprised?}
{172}{}{Honestly? I knew he's weak. He was forced to be a raider, but he always dreamed to be a musician.}

#Female character
{1130}{}{You're asking for it!}
{1131}{}{Brothers! Someone is asking for it here!}
{1132}{}{Hey, guys! Throw her outside!}
{1133}{}{Stay away from me, you got that?!}
{1134}{}{What?! You're asking for it again?!}
{1135}{}{You want to catch a bullet, huh?! Okay then!}
{1168}{}{What's up, gal. What is it now?}
