
{100}{}{You see Damien Clark.}
{101}{}{You see an archivist. He is, probably, the most inconspicuous City Hall employee.}
{102}{}{I lost my... Although, you wouldn't be interested in that.}

#Ñëó÷àéíûå ïëàâàþùèå ôðàçêè
{110}{}{Broke my pencil again...}
{111}{}{When is the salary?}
{112}{}{With the next paycheck I'll buy a bulletproof vest.}
{113}{}{What to read? Oh, the tax declaration!}
{114}{}{Boring.}
{115}{}{Such data...}
{116}{}{Well, don't ask me.}
{117}{}{I'll never earn so much.}
{118}{}{Reports, reports, reports...}
{119}{}{Need to add that to catalogue}
{120}{}{Not so promising as it seems.}
{121}{}{Another stupid idea.}
{122}{}{Need to throw that out}
{123}{}{Another ridiculous report.}
{124}{}{When is the planning session?}
{125}{}{When is the lunch break?}
{126}{}{How long for dinner time?}
{127}{}{I'm tired.}
{128}{}{A little rest, and then - to work again}
{129}{}{My eyes hurt.}
{130}{}{To read all this? Better fire me!}
{131}{}{Just don't fire me.}

#Starting conversation
{200}{}{Hello. What did you want?}
{201}{}{Where am I? Is this an archive?}
{202}{}{Is this an archive? Can I find the coordinates of a military base called "Area 51" here?}
{203}{}{Police told me about your daughter's disappearance. I volunteered to help in the search.}
{204}{}{Wrong door, sorry.}

{205}{}{Yes, all the city's data is stored here, though it's mostly reports from City Hall. I'm a senior employee of the unit... However, our archive is for internal use only.}
{206}{}{In this case, I need the coordinates of a military base called "Area 51".}
{207}{}{Nothing like that. Another question.}
{208}{}{I think, I don't need anything.}

{209}{}{But our archive is for internal use only, I cannot give you access to any documents.}
{210}{}{Oh! Of course! After all you've done for us, I'll scour every corner of the archive to find this information...}
{211}{}{Great!}
{212}{}{...However, our archive is for internal use only. But I don't think that something will happen to the municipality if someone would obtain some coordinates...}
{213}{}{There won't be any consequences, don't worry.}
{214}{}{Yes, good to hear. But I need a little time... So, Area 51... A military base... ... ...Yeah. [he moves to the archive room]}
{215}{}{[Wait]}
{216}{}{Yes! Found it! In one of the pre-war reports... Here. And here are the geographic coordinates. Is that a Pip-Boy? Is it working? Then you can simply type in the coordinates and you'll be able to see the location on the map.}
{217}{}{Right! Thank you so much, you helped me a lot!}
{218}{}{Oh no! Thank you!}
{219}{}{Bye.}
{220}{}{}

{221}{}{You're not a stupid man and should understand that for helping me I will help you back.}
{222}{}{Then we could make a deal. What the municipality requires in exchange for this information?}
{223}{}{Okay, enough! I need the coordinates before I get really mad! Fast!}
{224}{}{Well, that's a shame.}
{225}{}{Err... Young man, don't try to threaten me... Uh... The security is right behind the door, so...}
{226}{}{Listen, shithead, I had enough of your bullshit! I'm not fucking around here! Give me the coordinates!}
{227}{}{Maybe the municipality has some procedure to get the information from the archive? Can I fill the application form?}
{228}{}{Okay, okay, I'll leave you alone.}
{229}{}{[The man fixes his glasses on his nose, his eyes are avoiding yours] Er... I repeat... Threats are useless. You won't get anything. The archive is *only* for mayor's office employees...}
{230}{}{Then maybe I can persuade someone to take the information for me?}
{231}{}{Well... I don't think, that... For you... But if you know someone already, then...}
{232}{}{Fine, I'll leave you alone for now.}
{233}{}{Okay, that's it, you four-eyed! I'm sick of you! For the last time - give me the coordinates! Or your old ass will be squashed on the spot and no security will save you!}
{234}{}{[Turns pale. Suddenly starts shouting] Guards!!! Guards!!! Intruder!!!}
{235}{}{You son of a bitch! You think that they are faster than my bullet!?}
{236}{}{Er... Honestly, I don't know... Until now, only City Hall employees had any interest for the archive, and all other citizens didn't care...}
{237}{}{Hmm. How much are you being paid for this work?}
{238}{}{Err… I'm afraid, I can't tell that either. Not much, really...}
{239}{}{Then I'll pay 100 bucks for your trouble.}
{240}{}{Then I'll pay 200 bucks for your trouble.}
{241}{}{Then I'll pay 300 bucks for your trouble.}
{242}{}{Then I'll pay 500 bucks for your trouble.}
{243}{}{Forget it then. Bye.}

{244}{}{You know, I think this is fair. I do need to look after myself after this dusty work... I will get you the coordinates for this price.}
{245}{}{Here is the money.}
{246}{}{Only I have no money on me right now. But you can look for coordinates, while I fetch them.}
{247}{}{Uh... You know, I value my job more than an opportunity to get bribed once. I really don't want to lose it.}
{248}{}{Well I, of course, will, but only when you bring the, uh, compensation. For my trouble.}
{249}{}{Shit, then wait I'll be back soon.}
{250}{}{Grrm, oh look, here is the money in another pocket. Now, do me a favor and find the coordinates!}
{251}{}{[The archivist, mumbling something, walks away to the room with archives. He returns half an hour later, with a piece of paper in his hand] That's the coordinates. I see you have a Pip-Boy. Then you could type the coordinates there and see the location on the map.}
{252}{}{Great! Thanks.}

{253}{}{What are you doing, trying to profit off my problems?!}
{254}{}{So you do have problems?! Great, then, we could make a deal.}
{255}{}{Er, no. See you.}
{256}{}{Ugh, I have a big problem, something police cannot solve. My daughter disappeared.}
{257}{}{Under what circumstances?}
{258}{}{My daughter Anna... She's missing. Before we had a long and unpleasant conversation about some new friends, whom she consorted with. I tried to convince her not to get outside the walls of the Clean City. It's not safe. Seems like she didn't listen.}
{259}{}{Is it really safer here?}
{260}{}{What friends?}
{261}{}{Of course. But those dirty hippies, riding the wasteland on their bikes - they always fool young and silly girls like Anna.}
{262}{}{It looks like we're talking about bikers...}
{263}{}{I don't know much about them, and I don't want to. She loves these guys. It's, of course, not surprising - she's only fifteen. I usually look for her in "Hard-Rock", but no one has seen her there lately... Maybe they are hiding her from me? I don't think she could decide to run away from the city at her age.}
{264}{}{You're, of course, somewhat cowardly, but I'll help you find her. Perhaps, I should start from that cafe...}
{265}{}{It's too difficult, I'm not sure I can help.}

{266}{}{It's you! I'm so happy to see you! You know, she really came back! But she looks awful. I told her not to mess with those bikers, but she didn't listen! Now she will listen to her father more. I'm so thankful to you... Ahem. You know, I was thinking, such things cannot go without reward. Here is 2000 bucks - I hope, it is enough, to at least cover your expenses on the travel.}
{267}{}{Not bad for such an easy job! Take care.}
{268}{}{That's good, but I am looking for Area 51. This is a military base, 80 miles from Vegas. Could you search the files for its coordinates?}

{269}{}{Oh, of course! I've been notified. Mr. Williamson asked for you himself! Well, let's see... What do you need to find again?}
{270}{}{Coordinates of Area 51...}
{271}{}{}
{272}{}{}
{273}{}{}
{274}{}{}
{275}{}{Nothing for now.}
{276}{}{}
{277}{}{Thanks.}

{278}{}{Mr. Clark, this pendant is your daughter's, right?}
{279}{}{[His hands are shaking] Oh, my God... It's her pendant, but... Where!? Where did you get it!? Answer me!!!}
{280}{}{That's all that's left of her. She died.}
{281}{}{She gave it to me, saying that she'll never come back to you.}
{282}{}{It was on one of the bikers. These bastards didn't tell me what they did to her.}

{283}{}{No! Nooo! [He takes the pendant to the heart and begins to cry painfully]}
{284}{}{Yeah, cry, you pussy.}
{285}{}{I'm so sorry.}
{286}{}{Oh no... [pops his eyes frantically and sits down to keep himself from falling to the ground] No... This is all my fault! I should have paid more attention to my beloved daughter! And now... Now it's too late... [He covers his face with hands and begins to cry]}
{287}{}{Oh no... [pops his eyes frantically and sits down to keep himself from falling to the ground] No... They did it. They killed her!.. Oh God... This is all my fault! I should have paid more attention to my beloved daughter! And now... Now it's too late... [He covers his face his hands and begins to cry]}
{288}{}{::cries::}
{289}{}{Today he won't talk to you.}

#Female character
{1201}{}{Where am I? Is this an archive?}
{1204}{}{Wrong door.}
{1223}{}{Okay, enough! I need the coordinates, before I get really mad! Fast!}
{1225}{}{Err... Young lady, don't try to threaten me... Uh... The security is right behind the door, so...}
{1265}{}{It's too difficult, I'm not sure I can help.}
