{100}{}{You see the record keeper.}
{101}{}{You see one of the mayor's office employees - accounting clerk named Irvin. Important person.}
{102}{}{I don't deal with such issues.}
{103}{}{If you have complains, address them to that door knob.}

{110}{}{[You see accounting clerk named Irvin, the name is written on his badge. He's busy with his routine work.]}
{111}{}{So you're Irvin, the one who gave in the police the thief Murphy?}
{112}{}{[Leave]}

{113}{}{Murphy? Is that his name? [contemptuously] What a mature name for such a petty thief.}
{114}{}{Why did you do that? He's innocent.}
{115}{}{Tell about this story, I'm interested to hear this from the victim.}
{116}{}{Well, I was walking home along the street and suddenly the robber pulled a knife on me and demanded my wallet! I, of course, had to obey, otherwise he would kill me. Luckily, a policeman was not far, I reported the crime, the thief got caught and my money returned.}
{117}{}{You're lying.}
{118}{}{Strange that he did it in the middle of a protected area with a bunch of people around. Don't you think?}
{119}{}{Thanks for telling. Bye.}
{120}{}{[Nervous] Why, do I look just like that street thug? I'm the victim, why would I lie! You probably know yourself how bold and aggressive people that live outside the city walls are. If he needed money for the dose, then I don't find anything surprising.}
{121}{}{How much did he stole from you?}
{122}{}{Don't you feel bad for a young man, that will go in prison for such petty crime?}
{123}{}{There was 458 bucks in the wallet. I usually don't have large sums of money on me and I always count, so I was able to tell the police exactly how much money I had. It was seized during the search, and that was the main evidence of guilt.}
{124}{}{Feel bad? No-oo! These wild and vulgar thugs from the periphery I don't feel sorry for. Have you ever seen him? Abominable type, I must say. I'm sure a member of some local gang. In fact we found and a knife on him. Why did he have a knife? Huh? Yeah that's right.}
{125}{}{Excuse me! what are the evidence?}
{126}{}{I have seen the entries in the book, in the casino. Murphy won exactly the amount that you said the police he had stolen. And you were in the casino at the same time and saw how Murphy received a prize at the box office.}
{1126}{}{I have seen the entries in the book, in the casino. Murphy won exactly the amount that you said the police he had stolen. And you were in the casino at the same time and saw how Murphy received a prize at the box office.}
{127}{}{I have no proof, but I'm sure they are in the casino.}
{128}{}{No one will show you that information at the casino. Everything is in secret there, in order not to give away confidential information about the clients. But I don't think, that police will look into it. They have enough evidence already.}
{129}{}{[Shocked looks around to assure no one's listening] So, that's how it is... Either you're connected in the casino, or you are a thief just like that Murphy... Fine, I will have to talk differently with you.}
{130}{}{Explain first, why to frame Murphy?}
{131}{}{You left out one nuance out - I know your secret and I can tell the police. And if not me, then someone else. What will you say about that?}
{132}{}{Well, you make more sense, than that street thug.}
{133}{}{I lost my money again at the casino. My wife and I are always fighting, because of that. I promised her that I will quit. But I could not help myself. I didn't want a scandal and to damage my reputation in the Clean City. Can you understand that? I do care, what people say about me. That's why I did all this, and this gangster just happened to be around.}
{134}{}{How could you set up another man like this? Do you have no honor?}
{135}{}{It's the opposite of that. Look at him! This street thief burns in vain his worthless life, and now finally he will give us something in return. It will help not only me, but also he'll work for the good of the city in hard labor. He deserves it anyway. Isn't that wonderful?}
{136}{}{What are you, going to tell about me? But... But listen, we can make a deal, can't we?}
{137}{}{What a joy that you think same way. But listen, you won't going to harass people with this story right? Let's make a deal!}
{138}{}{What do you have in mind?}
{139}{}{If you got to casino records, could you do this one more time? You only need to rip off the page, and give it to me. I will pay.}
{140}{}{Okay, I'll do it, don't worry. No one will find out about what you did.}
{141}{}{I won't do that. Let a man be judged by his true deeds, not made up ones.}
{142}{}{Give me time to think. This is an interesting proposition.}
{143}{}{Phew! Well then, go, and good luck.}
{144}{}{Fine.}
{145}{}{Just try! Don't even think about it! [yells at your back, when you turn around] Think about yourself! Yourself!}
{146}{}{[Leave]}
{147}{}{Sure, of course, I don't want to push you, but hurry up with a decision. [changes expression] You should think about thoroughly. Think about yourself, not Murphy. Not even about me. Most importantly - about yourself...}
{148}{}{[Leave]}
{149}{}{Let's talk about Murphy.}
{150}{}{What is it?}
{151}{}{Fine, forget it.}

{152}{}{Are you ready to buy out the evidence from the casino?}
{153}{}{[Looks aside and keeps his voice down] Sure. Is it with you?}
{154}{}{Yes, now pay, before I changed my mind.}
{1154}{}{Yes, now pay, before I changed my mind.}
{155}{}{No, I'll have to go get it.}
{156}{}{[Laughs and gives you the money] You understand, you should keep it down about this.}
{157}{}{Sure, now you hold all the cards.}
