{100}{}{You see a City Hall employee.}
{101}{}{It's one of the City Hall employees.}
{102}{}{I don't deal with such issues.}
{103}{}{If you have any complains, address it to the doorknob over there.}

#Случайные плавающие фразы
{110}{}{The pencils got blunt again.}
{111}{}{Is the paycheck coming soon?}
{112}{}{Next time I get paid, I'll buy myself a bulletproof vest.}
{113}{}{Is there something I could read? Oh, the tax declaration!}
{114}{}{Boring.}
{115}{}{With all this data...}
{116}{}{That is not my job.}
{117}{}{I'll never make so much money.}
{118}{}{Reports, reports, reports...}
{119}{}{Who to yell at?}
{120}{}{Not as prospectively as it seemed to be.}
{121}{}{Another stupid idea.}
{122}{}{Junk!}
{123}{}{Another stupid answer.}
{124}{}{When is the planning session?}
{125}{}{When is the lunch break?}
{126}{}{When's the dinner?}
{127}{}{I want to sleep.}
{128}{}{I need to rest.}
{129}{}{My eyes are tired.}
{130}{}{To read all this? Just fire me.}
{131}{}{Please, just don't fire me.}
