{100}{}{You see Irvin.}
{101}{}{You see one of the mayor's office employees - an accounting clerk named Irvin. A very important person.}
{102}{}{I don't deal with such issues.}
{103}{}{If you have complains, address them to that door knob over there.}

{110}{}{[You see an accounting clerk named Irvin. His name is written on his badge. He's busy with his routine work.]}
{111}{}{So you're Irvin, the one who gave in the police the thief Murphy?}
{112}{}{[Leave]}

{113}{}{Murphy? Is that his name? [contemptuously] What a mature name for such a petty thief.}
{114}{}{Why did you do that? He's innocent.}
{115}{}{Tell me more about this story. I want to hear it from the victim.}
{116}{}{Well, I was walking home along the street and suddenly the robber pulled a knife on me and demanded my wallet! I, of course, had to obey, otherwise he would kill me. Luckily, a policeman was not far. I reported the crime, the thief was caught, and my money was returned.}
{117}{}{You're lying.}
{118}{}{Strange that he did it in the middle of a protected area with a bunch of people around. Don't you think?}
{119}{}{Thanks for telling me this. Bye.}
{120}{}{[He looks nervous] Why, do I look just like that street thug? I'm the victim, why would I lie! You probably know yourself how bold and aggressive people that live outside the city walls are. Maybe he needed money for the dose. I'm not surprised in the least.}
{121}{}{How much did he steal from you?}
{122}{}{Don't you feel bad for a young man that will go in prison for such a petty crime?}
{123}{}{There was 458 bucks in the wallet. I usually don't have large sums of money on me and I always count them, so I was able to tell the police the exact amount I had. It was seized during the search, and that was the main evidence.}
{124}{}{Feel bad? No-oo! I don't feel sorry for these wild and vulgar thugs from the periphery. Have you even seen him? Hideous type, I must say. I'm sure he's a member of some local gang. In fact, he had a knife on him. Why would he have a knife? Hmm? Yeah that's right.}
{125}{}{Excuse me! What about the evidence?}
{126}{}{I have seen the entries in the book, in the casino. Murphy won exactly the amount that you said the police he had stolen. And you were in the casino at the same time and saw how Murphy received a prize at the box office.}
{1126}{}{I have seen the entries in the book, in the casino. Murphy won exactly the amount that you said the police he had stolen. And you were in the casino at the same time and saw how Murphy received a prize at the box office.}
{127}{}{I have no proof, but I'm sure they are in the casino.}
{128}{}{No one will show you that information at the casino. Everything is kept in secret there, to protect a confidential information about the clients. But I don't think that police will look into it. They have enough evidence already.}
{129}{}{[Shocked, he looks around to make sure no one is overhearing] So, that's how it is... Either you have connections in the casino, or you are a thief just like that Murphy... Fine, I will have to talk differently to you.}
{130}{}{Explain first, why to frame Murphy?}
{131}{}{You left out one nuance out - I know your secret and I can tell the police. And if not me, then someone else. What do you think of that?}
{132}{}{Well, you make more sense than that street thug.}
{133}{}{I lost my money again at the casino. My wife and I are always fighting because of my gambling. I promised her that I will quit, but I couldn't help myself. I didn't want a scandal and to damage my reputation in the Clean City. Can you understand that? I care what people say about me. That's why I did what I did. This gangster just happened to be around.}
{134}{}{How could you set up another man like this? Don't you have any honor?}
{135}{}{On the contrary! Look at him! This street thief burns his worthless life in vain, and now he is finally useful. It would not only help me, he would also benefit the city by doing hard labor. He deserved it anyway. Isn't that wonderful?}
{136}{}{What, are you going to tell on me? Uh... Listen, we can make a deal, can't we?}
{137}{}{What a joy that you and I think same way. But look, you're not going to harass people with this story, are you? Let's make a deal!}
{138}{}{What do you have in mind?}
{139}{}{If you got to the casino records, could you do this one more time? You only need to rip off the page and bring it to me. I will pay.}
{140}{}{Okay, I'll do it, don't worry. No one will find out about what you did.}
{141}{}{I won't do that. Let a man be judged by his true deeds, not made up ones.}
{142}{}{Give me some time to think. It is an interesting proposition.}
{143}{}{Phew! Well then, go, and good luck.}
{144}{}{Fine.}
{145}{}{Just try it! Don't even think about it! [yells at your back, when you turn around] Think about yourself! Yourself!}
{146}{}{[Leave]}
{147}{}{Of course, I don't want to push you, but hurry up with a decision. [His expression changes] You should think about it more thoroughly. Think about yourself, not Murphy. Not even about me - about yourself...}
{148}{}{[Leave]}
{149}{}{Let's talk about Murphy.}
{150}{}{What is it?}
{151}{}{Fine, forget it.}

{152}{}{Are you ready to buy out the evidence from the casino?}
{153}{}{[Looks aside and keeps his voice down] Sure. Do you have it with you?}
{154}{}{Yes. Now - pay, before I changed my mind.}
{1154}{}{Yes. Now - pay, before I changed my mind.}
{155}{}{No, I'll have to go get it.}
{156}{}{[He laughs and gives you the money] You do realize you should keep quiet about this?}
{157}{}{Sure, now you hold all the cards.}
