{100}{}{You see the secretary.}
{101}{}{You see Marion Keysker.}
{102}{}{You see a middle-aged lady with a fairly strict, even a little nervous glance.}
{103}{}{Sorry, it's not a visiting day.}
{104}{}{Do not flirt with me at my workplace.}
{105}{}{I'm sorry, but I need to see your face.}

#С'ар' диалога
{110}{}{Good afternoon. I'm Keysker Marion, secretary of our mayor. How can I help you?}
{111}{}{How can I help you?}
{112}{}{I need to see the mayor.}
{113}{}{I'm looking for the coordinates of Area 51. Is it possible the City Hall has this information?}
{114}{}{I think, you can't. Bye.}

#Получение разрешения на аудиенцию с мэром
{115}{}{Do you have an appointment?}
{116}{}{Err... Yes. We agreed for a meeting.}
{117}{}{No. How do I make an appointment?}
{118}{}{Good. I will tell Mr. Williamson. What is your name?}
{119}{}{.}
{120}{}{I mean, how to make an appointment to see him?}
{121}{}{Nobody. Write it down!}
{122}{}{You know, I'll come later.}

{123}{}{Oh, Mr. Nobody. Do you know that you are not in the list? I think you know.}
{124}{}{Hey, lady! I will see the mayor one way or another!}
{125}{}{Fine.}
{126}{}{You are not assigned. Now leave this room please.}
{127}{}{Marion, sweetheart! Please tell Mr. Mayor, that one gentleman wants to see him. And here is a caramel for your coffee to soften your beautiful face.}
{128}{}{Marion, sweetheart! Please tell Mr. Mayor, that a lady wants to talk to him about something very important!}
{129}{}{Oh, thank you, mister?..}
{130}{}{Mister }
{131}{}{. Just Mister }
{132}{}{.}
{133}{}{Okay. Tell me, tell me what is your name and I will make an appointment.}
{134}{}{Miss }
{135}{}{. Just miss }
{136}{}{.}
{137}{}{Okay, Mister }
{138}{}{. Wait I will contact Mr. Williamson.}
{139}{}{Okay. I'll wait.}
{140}{}{Okay, miss }
{141}{}{Mr. Williamson will see you. Proceed to his office.}
{142}{}{Thanks.}

{143}{}{No need to go all sweet on me. Mr. Williamson is a very busy man. If you don't have an appointment - he won't accept you.}

#Как записа'ься на прием?
{144}{}{Mr. Williamson accepts only for particularly important cases. State the purpose of your visit.}
{145}{}{I have important information, that is discrediting some of Mayor's subordinates.}
{146}{}{I just want to talk with the mayor about the city.}
{147}{}{I think, you don't understand yourself, that is not important for the mayor.}
{148}{}{I would like to get a job at mayor's office.}
{149}{}{Yes, Mr. Williamson was really looking for a specialist for some special task. You may be able to help him. I'll tell him about your visit. What is your name?}
{150}{}{You know, maybe, not now. Take care.}
{151}{}{Oh, this is a very serious accusation! I think I'll have to let you in. Tell me your name.}
{152}{}{You got a pass to Mr. Williamson office, the mayor of the city.}
{153}{}{Sorry, Mr. Williamson is not hiring more workers.}
{154}{}{As the sheriff of a small town in the west, I can find something to talk about with your mayor.}
{155}{}{Oh, this changes things. I will tell about your visit to Mr. Williamson. What is your name?}
{156}{}{I'm sure, he'll be interested in a person, that solved many of major crime cases.}

#Зона 51
{200}{}{Hmm. Perhaps, there is such record in our archives. But only the mayor's office employees can request such information.}
{201}{}{So, I need to convince someone in the mayor's office to make an inquiry?}
{202}{}{Oh, too bad.}
{203}{}{Apparently, yes. It is forbidden to give the archive files to third parties.}
{204}{}{And what about you? Can we make a deal?}
{205}{}{Right.}
{206}{}{Who could help me? Could you tell?}
{207}{}{Our mayor is too busy, perhaps, his deputy, Tom Parker, which has plenty of time to help you.}
{208}{}{Where's his office?}
{209}{}{I think no one would agree, everyone is too busy for such small matters.}
{210}{}{On the second floor, through the conference room.}
{211}{}{Thank you.}
{212}{}{You know, I'm too busy...}
{213}{}{Sweet Marion, you should not doubt so much! Believe me, we'll get along well. I'm not asking for something criminal, right? Ultimately, that's what the archive is for, so people can get the information...}
{214}{}{Your loss.}
{215}{}{Oh, fine. You convinced me. It's not a big secret anyway. So what did you need from there?}
{216}{}{Area 51, just the coordinates of the base...}
{217}{}{Oh, fine. You convinced me. But you understand that nothing is free in our world?}
{218}{}{Wow, of course. No problem. How much?}
{219}{}{Money? For some coordinates? No!}
{220}{}{No need to go all sweet on me. I know my job and won't climb to the archive for your questionable information.}
{221}{}{Too bad.}
{222}{}{Idiot! You've just lost a client!}

{223}{}{1000 bucks. We value our archives very much.}
{224}{}{What are you saying!? Is it really that expensive?! Think it over! I can leave right now and you won't get even a penny.}
{225}{}{Okay, here is 1000 bucks.}
{226}{}{Oh no, this is too expensive!}
{227}{}{Perhaps, you're right. Drop it to 500. But that's it!}
{228}{}{Here is the money.}
{229}{}{Still that's too much. No.}
{230}{}{My time is more precious. And I'm not going to make a discount on it.}
{231}{}{Well, okay, you got me for 1000. Here is the money.}
{232}{}{I can't spend so much right now.}
{233}{}{500 bucks. We value our archives very much.}
{234}{}{Perhaps, you're right. Let's drop it to 300. But that's it!}
{235}{}{Well, okay, you got me for 500. Here is the money.}
{236}{}{The price is right. Here is the money.}

{237}{}{Okay, good news - our archives are very organized. Here is the coordinates you were looking for.}
{238}{}{Thank you. (type in the coordinates into Pip-Boy and exit)}
{239}{}{Then you have to wait a little while I'll get to the archive.}
{240}{}{Sure. I'm waiting.}

#Проход к мэру -- намек про город
{242}{}{Oh no. I think the mayor needs intelligent detective. You know, a lot of suspicious events occurred in the city recently! And the police won't do anything...}
{243}{}{Yes, I heard... Mr. Williamson may want to talk to you, I remember that he did mention it many times...}
{244}{}{Then tell him that a detective is available. Perhaps, the proposal is still holds...}
{245}{}{Probably, not now. I'll be back later.}

#Female character
{1120}{}{I mean, how to make an appointment to see him?}
{1148}{}{I would like to get a job at mayor's office.}
