{100}{}{You see the minister of culture.}
{101}{}{You see a smart City Hall employee. Judging by the badge, he is holding the position of the minister of culture.}

{110}{}{What is it about?}
{111}{}{Oh, I have a lot of questions. Can you help me answer them?}
{112}{}{It depends on your position. Are you the minister of culture? What does that mean?}
{113}{}{I don't have any questions. See you.}

{114}{}{This means, that I am - the minister of culture, and you are - the foolish child of the wastes. Explaining to you what "culture" means is pointless to me, sorry.}
{115}{}{Still - be nice to clear at least something.}
{116}{}{In that case we have nothing to talk about.}
{117}{}{[Nervously sighs] My work is to develop and preserve all the cultural norms of the Clean City. My department assesses how the city should look and sound, but the main thing - how the locals should improve their intellectual abilities. It will be difficult for you to understand.}
{118}{}{It seems you're of a bad opinion on people living outside the city.}
{119}{}{What are you saying!? There are a lot of talented and knowledgeable people beyond the walls of the Clean City. Like me, for example.}
{120}{}{The situation is clear. Perhaps now you'll be able to answer some questions?}
{121}{}{Yes, I think this information is enough for my brain. See you.}

{122}{}{[Slyly grinning] What are YOU saying?! I'm actually of good opinion on the inhabitants of the Wasteland. You just have to wash them, dress, give each one of them a book, teach them some good manners - and here you have an army of decent people. The question is - how long this decency will last?}
{123}{}{I won't argue with you. Outside the walls there is really a heck of a pitiful and miserable life.}
{124}{}{With such snobbery, nothing but discrimination can be expected from you.}
{125}{}{I have every reason to believe that you have very little knowledge of the world, and that you fell victim of your own delusions. I am the direct proof of that.}
{126}{}{Let's leave this discussion on that.}

{127}{}{I don't understand - are you trying to impress me, or are you out of this world yourself? Although, given the contrast between the Clean City and the periphery, your point of view of our city is quite understandable.}
{128}{}{No, I'm talking not about that! You know, all these bandits on the streets of Reno, wild ghouls, raiders, crazy idiots - I happened to see a lot during my journey.}
{129}{}{Be careful, youngster! Do you have any idea how much work is invested in the reconstruction of this area?! For ten years we tried to establish a decent living here, with joined effort. And now any outcomer scum is capable of talking garbage here. But, in any case, I don't have the mood to prove anything to you. *You* come here and distract me from my work with your pointless conversations.}
{130}{}{You don't look like a caravaneer, or a representative of "Nevada express". This conversation is already becoming pointless.}
{131}{}{Perhaps, in this case, you can answer a few questions?}
{132}{}{Did you really acquire such rich experience from your travels? How interesting... I would like to discuss with you the life of people in other cities. You don't mind, do you?}
{133}{}{Oh, sure, with pleasure!}
{134}{}{I don't have time for this right now. Perhaps, another time.}
{135}{}{There can be no other time. But you've already decided, so let's leave it at that. Is that all you wanted?}
{136}{}{No, I had more questions about the Clean City and City Hall.}
{137}{}{Yes, it's time for me to go. Take care.}
{138}{}{Excellent. Every day I'm having dinner at the casino across the street. Meet me there, so we can talk in more cultural atmosphere.}
{139}{}{I will remember that. And now - could you answer some more questions about the city?}
{140}{}{See you.}

{141}{}{Oh no, you won't fool me. You don't shine in erudition department, that's for sure.}
{142}{}{What arrogance... But maybe I'm little off sometimes. I didn't make a single step out of Clean City for ten years. Perhaps, some things changed during that time, but I highly doubt it. You are going to say that the life became better outside, aren't you?}
{143}{}{Ten years - it's a period of Great depression. Ages. You know, things are going better in New Reno recently, and a number of new settlements rise around the federal highways... The world is changing, you should take a closer look.}
{144}{}{Great depression... Now, stop. This is from history. Aren't you a little well-educated for a wastelander?}
{145}{}{I'm just interested in studying. But how do you manage to keep the craving for cultural development in these conditions?}
{146}{}{My God! Who am I talking to? Listen, it's actually not that simple. For many years I'm trying to establish a culturally educational program here, but I constantly come across a misunderstanding on the part of other members of the mayor's office. For them, to bring direct benefits, like trade, rent, entertainment business, electricity and everything on what you can speculate on - is more important. A few can appreciate my ambitions. Fortunately, the Mayor allowed me to establish this department, though we have a low budget.}
{147}{}{So, you're having hard times here. Perhaps, I should think about this a little. Good bye.}
{148}{}{You proved the snob that outside the city walls exist some clever people.}
{149}{}{Great, but I would like to ask a few questions, not answer them.}

{150}{}{[Restrains the charity behind arrogant smile] Your curiosity is certainly worthy of respect, but I have no time for pointless talk.}
{151}{}{With pleasure, but I have little time for small talk.}
{152}{}{I'll pretend I didn't hear that, but other members of the Clean City would not. Many are proud to live here. Do you even understand, how much work has been invested in the reconstruction of this area?! For ten years we tried to establish a decent living here, with joined effort. It's hard for outcomers to understand, they think that the locals just had everything from the beginning.}
{153}{}{Even if you have great experience, I would prefer to look into more reliable sources.}
{154}{}{I am the minister of culture, not your drinking buddy in a bar! I won't answer any questions.}
{155}{}{You respond too emotionally to a simple question. Do you hate my company?}
{156}{}{Let's talk about your office, the minister of culture office.}
{157}{}{Yes, exactly. I don't see in you the qualities that I appreciate in others. Besides, I'm not obliged to communicate with you. There is a secretary for this.}
{158}{}{Fine, I'm leaving.}
{159}{}{Too bad you treat me this way. I bring profits to Vegas...}

{160}{}{Tell me about the history of the Clean City. How did you manage to restore all this?}
{161}{}{Why is there so much discrimination toward outsiders?}
{162}{}{In our time, the police and the mayor's office are unusual thing in cities. Will you be able to keep the order?}
{163}{}{Tell me about your department. How is it different from the rest?}
{164}{}{Tell me about your mayor.}

{167}{}{Another question please.}
{168}{}{What do you want to know?}
{169}{}{We have already clarified a lot. Let's stop at that.}

{170}{}{Ten years of hard work. At first, the boulevard was nothing but the same boring and uncrowded neighborhood like any other in Vegas. Then it became a central market with few wealthy families that made fortune on the trade of food and water. Soon the families increased their income and started practicing slave labor. With the help of slaves they cleared the area and put everything in order. For ten years the people here are trying to establish a decent life. A vicious circle of elites and celebrities formed. Much has changed in ten years.}
{171}{}{Would you like it if your clean and lovingly maintained house was invaded by dirty beggars that make noise and create problems? Most of them see only luxury and brights, and our hard daily work falls behind the scenes. If so, then I see no reason to treat the monkey as a person, if it is an animal and I'm a man.}
{172}{}{Of course. But only in the Clean City. We simply have no time for the whole Vegas. Therefore, outskirts are mired in poverty and crime.}
{173}{}{The department of culture is responsible fo the program of cultural events, representation of the Clean City and its inhabitants, but most important of all - for education. Recently we even started selling the surviving pre-war books using vending machines. Just imagine a man reading a book outside of the Clean City. It's almost impossible, is it not?}
{174}{}{I would prefer not to discuss the mayor with anyone, even with my acquaintances. But sometimes I just think - how the Council could choose a spineless and pliant old man to such an important post? I'm just afraid that personal interest will corrupt the mayor.}
{175}{}{Really? What is that business, allow me to know?}
{176}{}{I supply Nuka-Cola, on the agreement with the factory in the north. I can show the papers, if you don't believe me.}
{177}{}{My private business bears an independent nature. I'm not even obliged to report to the Clean City.}
{178}{}{It's confidential. I have special agreement with the mayor of the city.}
{179}{}{Hmm, sorry then. I'm obliged to send away all kind of scum, so they wouldn't bother me and interfere with my work. You know how it is.}
{180}{}{Oh yes. Maybe you can tell me about the work in the City Hall?}
{181}{}{You have made the arrogant minister of culture answer all your questions.}
{182}{}{D-don't touch me!!! Stay away! How did the security let you in here?! Leave! Leave now, ghoul, so I don't see you anymore!}
{183}{}{Hey, don't confuse skin disease with ghoulification! Ah, damn it, its pointless to explain it to you.}
{184}{}{If you'll talk about my sickness again - you will look lot worse than that. A lot worse.}
{185}{}{Security! SECURUTY!!!}
{186}{}{[Leave]}
{187}{}{Actually, it's really significant. Maybe, you can answer a few questions?}
{188}{}{Forget it, it's not important.}
{189}{}{I try to stay away from large settlements during my travels. The experience of survival in the wild is more important to me.}
{190}{}{Did you really acquire such rich experience from your travels? How interesting... I would like to have a talk with you about the life in the wasteland. You don't mind, do you?}

{200}{}{And I thought you won't come.}
{201}{}{Do you dine here often?}
{202}{}{You wanted to talk to me about the outside world. So I'm at your service.}
{203}{}{Please wait, I have something to do and then I'll come back.}
{204}{}{It's my duty to know, how are local business running. Plus, I like it here.}
{205}{}{Yes, it would be great to hear the story from a traveler directly. Let's make ourselves comfortable, order a some whiskey and talk about it.}
{206}{}{Sure, I don't mind...}
{207}{}{Sorry, but I can't right now. Please wait, I have some things to do.}
{208}{}{You have opened the eyes of the snob and showed him an amazing and diverse world outside Vegas.}
{209}{}{Good evening.}
{210}{}{Goodbye.}
