{100}{}{You see a visitor.}
{101}{}{You see Barney Hill.}
{102}{}{Tin foil hat, wild look - are you sure you want to talk to him?}
{103}{}{You see Barney Hill. He still anxiously looks around.}
{104}{}{Huh? What? Wait a minute, I do not remember you...}

{105}{}{Your evil behavior with such inadequate man makes others act more cautious towards you.}
{106}{}{Your delicate behavior with inadequate man leads to the respect from others.}

#Новая версия, автор Kerb, редакция Black Designer
{120}{}{[Pulls tin foil hat over his ears, bounces back] Ah! Stay away! You won't make fun of me again! Nor you, nor that stupid snobs, nor the aliens again!}
{121}{}{You made fun of yourself, when you pulled the foil onto your skull.}
{122}{}{Calm down, buddy! Sure, no making fun! I will look into it personally.}

{123}{}{You... I know you! Cunning, very cunning... Give me your hand – I must see which color your blood is! I won't live through another anal probing. [Pulls out a knife]}
{124}{}{Hey, you do know your stuff about perversions, right? No seriously - one more wrong move and I'll make a research on your rectum with your own knife!}
{125}{}{Wow, take it easy, we don't know each other that well... Why not to calm down? My hands are empty, maybe you can empty yours?}

{126}{}{[Shakes his head, eyes cleared] Damn... F-forgive me... It gets to me sometimes... After kidnapping... Damn aliens...}
{127}{}{Kidnapping? Aliens? What... You know, why not to listen to a story of another degenerate? Okay, start talking.}
{128}{}{Seriously? You were kidnapped by aliens? I would be very interested in hearing your story, mister.}

{129}{}{I lived in Spring Valley then. I walked back home the other night, from my friend's house. We drank a little, as usual... And then - a bright light from the sky! Blinded me - and suddenly I lost consciousness, I think these aliens stunned me with some sound. I woke up on a strange frame, bound, covered in wires...}
{130}{}{Drank a little? Oh, this explains a lot. Go on, weirdo.}
{131}{}{Not the most pleasant awakening, sorry... What happened next?}

{132}{}{[Shakes, hugging himself around shoulders] Then the most terrible things began... They did some experiments, stuck needles in me, cut off a piece here and there, forced me to swallow some nasty stuff... They opened my skull without anesthesia! Did you ever hear the crunching of your own skull?! I screamed so hard...}
{133}{}{What a creative approach! Who was it, so skillful?}
{134}{}{It is difficult even to imagine this, my friend... And "they" - who are they? Did you see them?}

{135}{}{I... I'm not sure. What I saw was - my vision was blurry - only two gray silhouettes, swaying. And I didn't hear them talking - instead, some weird cricketing... I couldn't even spit in their faces - they sewn my mouth up... But I did even better! I ran away from them! [Laughing hoarsely] Oh, that was great.}
{136}{}{Uh-huh, sure. Looks like they just threw you away after using.}
{137}{}{Really?! How did you do that? It must have been something very extraordinary!}

{138}{}{They dragged me somewhere outside... In the wasteland... Dropped me on the ground. They probably thought that a piece of meat I turned into won't be dangerous anymore. Just one of them stayed with me... I lunged at him, clung into his slimy head and crushed it like a rotten mutafruit! A fountain of green ooze sprayed me whole... And then I crawled... For a long, long time...}
{139}{}{That's it? Who would believe in this bullshit?}
{140}{}{This... Truly sounds incredible, friend.}

{141}{}{No one believes me... But I have proof! I took their weapon! You sure have never seen anything like this. It's somewhere here... Where did I put it... [He goes into unintelligible mumbling. You won't get anything else out of him]}
{142}{}{Words, words, words... 15 minutes of wasted life, no weapon, no sense. Farewell, wacko.}
{143}{}{Man, I hope you will get over all of this someday, and maybe it would be better for you to not find that weapon... For your own good.}