{100}{}{You see a visitor.}
{101}{}{You see Barney Hill.}
{102}{}{Tin foil hat, wild look - are you sure you want to talk to him?}
{103}{}{You see Barney Hill. He's still anxiously looking around.}
{104}{}{Huh? What? Wait a minute, I don't remember you...}

{105}{}{Your vile behavior with a mentally disturbed man causes others to behave more cautiously toward you.}
{106}{}{Your delicate behavior with a mentally disturbed man leads to respect from others.}

#Íîâàÿ âåðñèÿ, àâòîð Kerb, ðåäàêöèÿ Black Designer
{120}{}{[Pulls tin foil hat over his ears, then bounces back] Ah! Stay away! You won't make fun of me again! Neither you, nor those stupid snobs, nor the aliens again!}
{121}{}{You made fun of yourself when you put that foil over your skull.}
{122}{}{Calm down, buddy! No one is going to make fun of you! I will look into it personally.}

{123}{}{You... I know the likes of you! Cunning, so cunning... Give me your hand – I need to see the color of your blood! I won't live through another anal probing. [He pulls out a knife]}
{124}{}{Hey, you do know your stuff about perversions. No, seriously - one more wrong move and I'll anal probe you with your own knife.}
{125}{}{Wow, take it easy, fella... Why don't you calm down? My hands are empty, maybe you can empty yours?}

{126}{}{[Shakes his head, eyes cleared] Damn... F-forgive me... It gets me sometimes... After kidnapping... Damn aliens...}
{127}{}{Kidnapping? Aliens? What... You know, why not listen to another degenerate's story? All right, tell it.}
{128}{}{Seriously? You were kidnapped by aliens? I would be very interested in hearing your story, mister.}

{129}{}{I lived in Spring Valley then. I walked back home the other night, from my friend's house. We drank a little, as usual... And then - a bright light from the sky! It blinded me - and suddenly I lost consciousness. I think these aliens stunned me with something. I woke up on a strange frame, bound, covered in wires...}
{130}{}{Drank a little? Oh, this explains a lot. Go on, weirdo.}
{131}{}{Not the most pleasant awakening, sorry... What happened next?}

{132}{}{[He starts to shake, hugging his shoulders] Then the most terrible part began... They experimented on me, sticking needles, cutting off pieces here and there, forcing me to swallow nasty stuff... They opened my skull without anesthesia! Did you ever hear the crunching of your own skull?! I screamed so hard...}
{133}{}{What a creative story! Who has the skill to do that?}
{134}{}{It is difficult even to imagine this, my friend... And "they" - who are they? Did you see them?}

{135}{}{I... I'm not sure. My vision was blurred... I only saw two gray silhouettes. And I couldn't hear them talking - just some strange chirping... I couldn't even spit in their faces - they sewn my mouth up... But I did it! I ran away from them! [He laughs hoarsely]}
{136}{}{Uh-huh, sure. Looks like they just used you and threw you away.}
{137}{}{Really?! How did you do that? It must have been something very extraordinary!}

{138}{}{They dragged me somewhere outside... In the wasteland... Dropped me on the ground. They must have thought that the piece of meat I had turned into would no longer be dangerous. Only one of them stayed with me... And I lunged at him, clung into his slimy head and crushed it like a rotten mutfruit! A fountain of green ooze sprayed me all over... And then I crawled... For a long, long time...}
{139}{}{And that's it? Who would believe this bullshit?}
{140}{}{This... Truly sounds incredible, friend.}

{141}{}{No one believes me... But I have proof! I took their weapon! You've certainly never seen anything like it. It's here somewhere... Where did I put it... [He goes into unintelligible mumbling. You won't get anything else from him]}
{142}{}{Words, words, words... 15 minutes of wasted life, no weapon, no sense. Farewell, wacko.}
{143}{}{Man, I hope you will get over all of this someday. And perhaps it would be better for you not to find that weapon... For your own good.}
