{100}{}{You see David.}
{101}{}{You see, one of the bouncers of the casino.}

{110}{}{Look, I'm  watching for someone here, and you better not interfere.}
{111}{}{Who are you watching for?}
{112}{}{What if I find this guy before you?}
{113}{}{Okay, I will not bother you.}
{114}{}{Rude! I will complain of your administration!}

{115}{}{For unscrupulous visitors of the casino. Now, leave me.}
{116}{}{Hmm. Actually, it's not a bad idea. You see, one of our customers has debt of a really big sum of money, and now he hides from justice.}
{117}{}{What's the name of this client?}
{118}{}{How much does he owe the casino?}
{119}{}{Why don't you chase him, instead of hanging around in the lobby?}
{120}{}{What'll I get if I bring him to you?}
{121}{}{You know, sort it out without me.}
{122}{}{That's enough! I want to buy off the debt of this guy!}

{130}{}{His name is Norman.}
{131}{}{Oh, it's a reeeally big debt. What he owed to us costs on the market around approximately 3000 bucks. Pretty good, considering he wouldn't want to part with this... Item, while he is still breathing.}
{132}{}{What do you think I'm doing? I'm watching for this son of a bitch, Mr. Snoops! Yes, right here. Because the only exit is here, and running around looking for him in the crowd, up and down all the floors, is exhausting and a waste of time.}
{133}{}{Well, the honor of the administrative sector of the casino and, perhaps, 500$ from me for the capture. I'm still going to make a lot more money off him than this pitiful amount.}
{134}{}{Oh, I would be very happy. Because I don't have to dirty my hands and then wait for a suitable customer on his glan... Uh, never mind. But it is 3000 bucks - that's the price of his dept.}
{135}{}{I have the desired amount. Let's make the exchange.}
{136}{}{Great! Enjoy a good deal. Here's our receipt. He can now walk out of the casino, do not worry. I keep my word.}
{137}{}{Ok, I'll tell him.}

{150}{}{The one you looking for is dead.}
{151}{}{Is that so? First, let's check if it's true...}
{152}{}{Sure.}
{153}{}{Great! Less of a hassle. Of course, the casino is not accustomed to encourage the use of force to resolve issues, but in this case I speak as a private person, so here's 300 bucks as a tip. Thank you, wanderer.}
{154}{}{No, thank *you*!}
{155}{}{...uh, yeah, and one more thing. I heard that our boss, Hal Wallace, is looking for someone for a certain work. I think you should talk to him if you need a job.}
{156}{}{Great! Bye!}

#Æåí ðåïëèêè
{1132}{}{What do you think I am doing? I'm looking for this son of a bitch, Mrs. Snoops! Yes, right here. Because the only exit is here, and to run looking for him in the crowd, down and up of all the floors, is quite exhausting.}
{1153}{}{Great! Less of a hassle. Of course, the casino is not accustomed to encourage the use of force to resolve issues, but in this case I speak as a private person, so here's 300 bucks as a tip. Thank you, wanderer.}
