{100}{}{You see Norman.}
{101}{}{You see a very jittery casino customer. He nervously gnaws on his fingernails and rotates his head looking around the room.}
{102}{}{*Error completing script!*}

#Beginning of dialogue
{110}{}{No! I ain't going nowhere! [covers his face with hands, like expecting a blow]}
{111}{}{Calm down, I'm not here after you.}
{112}{}{Well-well! Hiding from someone, am I right?}
{113}{}{As you wish, I'm leaving.}

{114}{}{Ohh... Sorry, I thought you were after me... Er... Alright, never mind.}
{115}{}{Are you hiding from someone?}
{116}{}{Alright.}

{117}{}{Oh nah... Err... I mean yeah. [grabs you by your clothes and begins shaking hysterically] You must help me! Someone wants to kill me!!! I don't wanna to die!!! Shit, I don't fucking wanna die!!! A-a-a!!!}
{118}{}{Hands off, vermin! Get away!}
{119}{}{[Smack him across his head]}
{120}{}{Alright, alright! Calm down! No need to make a scene!}
{121}{}{Calm down and tell me everything.}
{122}{}{[Struggle out of his grip and leave]}

{123}{}{Oh yes... Of course... Sorry... I don't know what came over me... I'm alright...}
{124}{}{Let's just calmly discuss what happened right now?}
{125}{}{What the hell was that?! What's with the panic?}
{126}{}{None of my business. I'm outta here.}

{127}{}{Of course... Of course...}
{128}{}{Tell me your story.}

#Questions about the event
{129}{}{Erm, well... It's all rather stupid really. I lost a few rounds of cards to one of those skull crushers downstairs. Without anything to put on the table, I bet my adrenal gland... Shit. I'm so, so stupid!!!}
{130}{}{Hold on... You lost your adrenal gland on a bet?!}
{131}{}{Err, what the hell is that?}
{132}{}{Can you even live without it?}
{133}{}{Why does anyone even need somebody else's adrenal gland?}
{134}{}{Who did you lose to?}
{135}{}{What are you gonna do now?}
{136}{}{Can I help?}
{137}{}{Ugh, not my problem. I'm going.}
{138}{}{Stay here while I figure this out.}
{139}{}{The adrenal gland is a paired organ producing adrenaline and other hormones. You can live without one, but why would anyone even need yours?}

{140}{}{Yeah, that was about the worst decision in my life! And, looks like the last too... But the cards... I just couldn't help myself.}
{141}{}{Adrenal gland. It's the gland above the kidneys that produces adrenaline and some other stuff. A very... Expensive thing.}
{142}{}{I heard that it's survivable. But, I don't know... Most likely... I'll end up as a stiff.}
{143}{}{Oh, don't you know?! You need it for adrenochrome. It's the most... Hellish drug in the history of mankind! It takes only a few drops of extract from this gland to just keel over. First you lose control over your own muscles, the body begins burn up. You're covered with a layer of sweat. And then the hallucinations come - your head will swell up like a watermelon... You gain about two hundred pounds in two hours, grow claws, bleeding warts... And then you notice about six huge, hairy tits swelling up on your back. You'll go blind, your body turns to wax, they'll have to put you in a wheelbarrow... And when you scream for help you sound like a raccoon... That's what I was told at least. I've never tried it myself.}
{144}{}{The thug named David. He's downstairs right now, waiting for me near the exit.}
{145}{}{Oh I don't know. I think I'll just stay here until I die of hunger. I'm not leaving the casino - David and the other bouncers will be waiting for me near the exit. They'll just butcher me in the nearest room as soon as they see me! Oh... Oh god!!!}
{146}{}{I don't know what to do! The front door is watched, and the backdoor is locked! You can't slip while the guards are watching. There are no other ways out. The only thing left is to surrender to David.}

{150}{}{Oh... Whew, thank god it's you, I was scared for a moment.}
{151}{}{Tell me what happened again.}
{152}{}{I know what to do!}
{153}{}{Stay here.}

{154}{}{What, really?! What do you mean?!}
{155}{}{Get up! David will reward me for your adrenal.}
{156}{}{I'll get you through the backdoor.}
{157}{}{I'm a doctor and I can remove your adrenal without risk to your health.}
{158}{}{How was the deal made? On paper or just by word?}
{159}{}{Will David accept something other than your adrenal?}
{160}{}{I could just kill him.}
{161}{}{Nothing, sorry.}

#Making the decision
{162}{}{Oh no, guess this is the end of the road...}
{163}{}{Quit pissing yourself and get to David! I'll make sure you don't try and run.}
{164}{}{I was just kidding, you can calm down.}

{165}{}{It's going to be hard. The backdoor is always locked, and it's unlikely to break it down without causing any noise. If they were unlocked, I could quickly run outside. The cops wouldn't let anything happen to me... I hope.}
{166}{}{Get ready, we're going! I took care of the door. Move! Move!}
{167}{}{Wait here then.}
{168}{}{There's another option.}

{169}{}{Erm... If you're really a doctor, then I'd rather let you operate on me, but... You just don't look like a surgeon!}
{170}{}{Erm... If you're really a doctor, then I'd rather let you operate on me... Yeah, something about you strikes me as doctor-ish. But you won't put me under the scalpel without painkillers, will you?}
{171}{}{I've got a strong anesthetic with me. Now, let's go to a free room. Don't be scared, you'll live!}

{172}{}{On paper. We both signed it. Then he folded it up and stuck it in the back of his pants. If it wasn't for that paper, I could ask the cops for help!.. Or at least try.}
{173}{}{I got the paper. Here it is.}

{174}{}{That gland costs a huge amount of money. Not completely sure, but it's *at least* a few thousand bucks.}
{175}{}{Kill David?! Are you suicidal?! David is one of the casino employees, the whole security force will be at his back.}
{176}{}{The man you owed is dead.}
{177}{}{Oh god! How did you do it?! Actually... I don't care. I'm not stepping another foot in this place!}
{178}{}{Correct. Time to get out.}

{180}{}{David: Hah! Look who we have here! Norman! Our dear client. I was afraid we'd have to look for you in all those rooms upstairs.}
{181}{}{[Continue]}
{182}{}{Norman: Erm, of course... Err, I decided not to bother your security...}
{183}{}{David: Shut up! That was your last trick. Try and run again... I'll blow your kneecaps off!}
{184}{}{Norman: Yes... Err, yes sir...}
{185}{}{David: Thanks for your help, wanderer. This client has owed us quite a sum of money, so here's your reward - $300. And... All the best.}
{186}{}{Pleasure doing business with you.}

{187}{}{... Erm, hold on! Hm... I heard that our boss, Hal Wallace, is looking for someone for a rather lucrative job. If you're looking for profit in this city, you might want to talk to him. Tell the guard you're from me and he'll let you through.}
{188}{}{Great! Take care!}
{189}{}{}

{190}{}{Oh god, we're out! I thought I was gonna end up like a stuck pig in one of the rooms. Thank you, wanderer, I owe you my life. Unfortunately, I can't pay you back. I got into this shit because I'm broke. But, if we see each other again, maybe I could help you like you helped me.}
{191}{}{What are you gonna do now?}
{192}{}{Well, I'm not staying in this city, that's for sure! That bonehead is just gonna send his skull crushers after me and then I'll get butchered in the streets. And the law will be on his side as well. I need to disappear as soon as I can!}
{193}{}{Which way?}
{194}{}{Not sure yet, I'll need to think about it. Anything will do, as long as it's far away from here!}
{195}{}{Understood. In that case, good luck.}
{196}{}{Hold on, what did you say about drugs in the city?}
{197}{}{Not like it's a secret, but a few know. I hear that somewhere not far away from the city exists a hidden lab that makes hallucinogens and other chems. Supposedly, that's where the most part of the city's dope comes from. But I've never been there.}
{198}{}{Alright, rumors are helpful too. Good luck.}
{199}{}{}

{200}{}{David: Hah! Look who we have here! Norman! Our dear client. I was afraid we'd have to look for you in all those rooms upstairs.}
{201}{}{[Continue.]}
{202}{}{Norman: Yes, of course... But there's one thing. I want this man to operate on me.}
{203}{}{Yes, that is so.}
{204}{}{[David looks at you with an empty gaze before shrugging] I don't care who pulls my property out of you.}
{205}{}{Let us begin.}
{206}{}{Well, Norman, looks like this party is over.}
{207}{}{Ughh, you son of a bitch...}
{208}{}{Heh-heh-heh!!!}
{209}{}{You receive 1000 exp for successfully completing the operation.}

{210}{}{What's wrong David, lost something?}
{211}{}{Hah! Look who suddenly grew a pair...}
{212}{}{Don't even dare to touch me!}
{213}{}{Ugh... Fuck it. You won't get far.}
{214}{}{We'll see about that... Let's go!!!}
{215}{}{Ha-ha! We showed him, didn't we!? That was great!}
{216}{}{"We"? Heh!.. Alright, what are you gonna do now?}

#Female version
{1166}{}{Get ready, we're going! I took care of the door. Move! Move!}
{1173}{}{I got the receipt. Here you go.}
{1185}{}{David: Thanks for your help, wanderer. This client has owed us quite a sum of money, so here's your reward - $300. And... All the best.}
{1190}{}{Oh god, we're out! I thought I was gonna end up like a stuck pig in one of the rooms. Thank you, wanderer, I owe you my life. Unfortunately, I can't pay you back. I got into this shit because I'm broke. But, if we see each other again, maybe I could help you like you helped me.}
