{100}{}{You see Raul.}
{101}{}{You see an inadequate character in yellow glasses.}
{102}{}{That's okay, you will see them soon.}
{103}{}{Perhaps he'll come back when he gets his head straight.}

#Первый разговор
{110}{}{[You see a strange guy in yellow glasses and bright shirt; He frantically swings around with his flyswatter] Careful! The bats!! They are everywhere!!}
{111}{}{[Go along] Damn!! So many of them!! Let's run to the cafe, they won't get us there!}
{112}{}{Bats? There are no bats!}
{113}{}{Not all right in the head, huh?}
{114}{}{Another lunatic. [Leave]}

{115}{}{Right! [suddenly stops] Look, they fly away!}
{116}{}{Then you can relax.}
{117}{}{Wait... How did I end up in the forest?}
{118}{}{[Go along] It's the bats. They got you.}
{119}{}{Are you sure?... Oh! [stares at you with wide-eyed] And who are you?}
{120}{}{Hey, wake up! We are not in the forest!}

{121}{}{I can see that, stupid! Shit, so many junkies around lately... Oh! [stares at you wide-eyed] And who are you?}
{122}{}{Me? Er, uh... I was just passing by.}
{123}{}{My name is [name]. Nice to meet you.}
{124}{}{Not your goddamn business, you narc.}
{125}{}{[He stretches out his hand and begins to stroke the air in front of him. Apparently, the last question did not reach its destination.]}
{126}{}{Hey, do you hear me?}

{127}{}{Ah? I'm okay! I'm okay! Erm... [suddenly straightens up, strikes a formal pose, smiles, and holds out his hand for a handshake] Welcome to Vegas, my friend! A great place to visit.}
{128}{}{Can you tell me about the city?}
{129}{}{Phew, I thought you were hallucinating!}
{130}{}{Shhh! They are coming back! More of them! No! NO!!! [starts waving the flyswatter in all directions] Piss off, bloodsuckers! Fuck you, you won't have any of my blood! Away!!! [runs away]}
{131}{}{[Leave]}

{132}{}{[Without paying attention to you, he is carefully looking for something in the sky, holding a flyswatter ready.]}
{133}{}{What do you look for there?}
{134}{}{[Leave]}

{135}{}{Shhh! The bats! A whole swarm. When they come together, they'll turn into a tornado, which will take us into the sky... Oh, this is bad, friend!}
{136}{}{My name is }
{137}{}{. Nice to meet you.}

#Второй разговор
{150}{}{Oh, my head hurts... Huh? And who the hell are you?}
{151}{}{You don't remember me?}
{152}{}{I'm a bat. Tremble before me!}
{153}{}{Nobody.}

{154}{}{No... Why, do we know each other?}
{155}{}{Er, actually, no.}
{156}{}{Well yeah, I saved you from the bats!}
{157}{}{No, and I don't want to. Bye.}

{158}{}{Uh, so that's what it is... Yes, I get the sarcasm. Thanks, dammit.}
{159}{}{What are you talking about?}
{160}{}{It seems I'm in a wrong place at the wrong time again. Good thing I'm not swept by the cops! Oh... What a headache... Look, let me sit on the ground for a second, I need to calm down.}
{161}{}{Take a painkiller, it should help.}
{162}{}{Okay, die then.}
{163}{}{Okay, whatever you say.}
{164}{}{Oh, shit, I think I get, what you mean. Time to quit doing it...}
{165}{}{Oh, thanks, it's much better now!}
{166}{}{So, what happened?}
{167}{}{Let me guess, I was running around the square shouting something about butterflies with fire extinguishers, right?}
{168}{}{Almost. It was about bats.}
{169}{}{Hah, must've been fun... Well, yes, I took a psychedelic. No reason to hide it.}
{170}{}{Thank you again. At least I don't have a headache now.}
{171}{}{You're welcome and bye.}

{172}{}{Tell me, what is a "psychedelic"?}
{173}{}{I do not understand, Why do you like acting crazy?}
{174}{}{Where did you get such a strong dope?}
{175}{}{Why would they need that?}
{176}{}{I think, I'm not interested in that.}

{180}{}{Ah, so you're a stranger here... Well, then you should know that it's a medication... With some side effects. The user experiences hallucinations that cannot be invented in any science fiction world. An amazing experience!}
{181}{}{Why? To escape this damn reality! Just one drop - and you become happy and free! It's worth it... Unless you abuse it, of course.}
{182}{}{It was some dealer... I don't remember, who exactly, there is so many of them lately, and there are always new faces in the business. Looks like the police of Clean City never rests.}
{183}{}{First, not everyone likes to live beside crazy idiots. Second, the Clean City tries to establish a monopoly on everything. Perhaps, they are trying to take control of the laboratory, too...}
{184}{}{The laboratory?}
{185}{}{Oops... Yes, there is talk that such large stocks cannot remain from pre-war times, that there is some manufacturer. But that's just a rumor.}
{186}{}{Right. That is all I wanted to know.}
{187}{}{You learned about the existence of a laboratory somewhere on the outskirts of Vegas.}

#Жен реплики
{1127}{}{Ah? I'm okay! I'm okay! Erm... [suddenly straightens up, strikes a formal pose, smiles, and holds out his hand for a handshake] Welcome to Vegas, my friend! A great place to visit.}
{1129}{}{Phew, I thought you were hallucinating!}
{1135}{}{Shhh! The bats! A whole swarm. When they come together, they'll turn into a tornado, which will take us into the sky... Oh, this is bad, friend!}
{1156}{}{Well yeah, I saved you from the bats!}
{1180}{}{Ah, so you're a stranger here... Well, then you should know that it's a medication... With some side effects. The user experiences hallucinations that cannot be invented in any science fiction world. An amazing experience!}
