{100}{}{You see: Ely.}
{101}{}{You see a terribly mutilated ghoul. It's repulsive just to look at him.}

#Первый разговор
{108}{}{[You stare at each other in shock. Whoever this creature is, he hasn't seen anyone in a long time.]}
{109}{}{[Move]}

{110}{}{Aaaaah! Don't! No sudden moves, and keep your hands where I can see them. That's how this is done, right?}
{111}{}{Pretty much, but it would work better if you loaded your gun first.}
{112}{}{Hey, wait a minute! I didn't know anyone was here. How about we just go our separate ways, huh?}

{113}{}{[Looks down at his gun in panic] Ah, shit! I knew I forgot something... And I guess yours is loaded, huh? Uh... You're not a cop or anything, right? How about we just sit down and be cool?}
{114}{}{Fine, but I have some questions. Don't lie to me, and don't forget who has the loaded gun here.}
{115}{}{No, I don't think so. I'm just going to go, now.}

{116}{}{I like the sound of that. You're not going to come back with a bunch of cops, are you? Nah, you wouldn't.}
{117}{}{I'm interested in something else - how about answering some questions?}
{118}{}{I was just leaving, anyway.}

{119}{}{Questions... [you see a spark of memory in his eyes, and he look distracted for a moment] "I refuse to speak without my lawyer!" [shakes his head] Why did I say that? It just popped into my head... Alright, I don't mind talking for a bit. I haven't talked to anyone since the war.}
{120}{}{Tell me a little about yourself.}
{121}{}{What is this place?}
{122}{}{Maybe later.}

#Пов'орный разговор
{130}{}{Are you still here? What are you hanging around for?}
{131}{}{I have a few questions.}
{132}{}{I'm just on my way out.}

{133}{}{Plague?}
{134}{}{Limit 115. America testing its new superweapon on its own citizens! Oooooh! What's the matter, you don't like conspiracy theories? It was a plague that broke out in 2053. And 2063. One day you're sneezing and coughing, the next day you're sweating and hemorrhaging, and the day after - you're dead. Scary shit. Denver was the worst - the locals burned it to the ground trying to quarantine it.}

{137}{}{Have I been here so long the world's forgotten about the war? October 23, 2077... [gazes over as his notes on the wall, absorbed in his thoughts] I'd like to forget it, too. So many corpses, you couldn't walk the streets of Reno for the stench. I don't even want to know how bad it was where the bombs hit. And the silence on the radio... Silence everywhere.}
{138}{}{[Next]}
{139}{}{Let me think... Hmm, federal highways! Before the war I traveled all over Nevada in my nuclear-powered Corvega. Now she was one hell of a car. Expensive, but worth every penny. Yeah... I didn't know how good I had it.}

{140}{}{About me? Well... [scratches head] What do you want to know?}
{141}{}{How did you end up in this place?}
{142}{}{You said something about the war... }
{143}{}{I'm interested in something else.}
{144}{}{Nothing, actually. Everything seems self-explanatory.}

{145}{}{I was driving to Reno for business when some drunk black guy wandered out in front of my car. He was dead the moment I hit him. If that judge hadn't been such a racist, I'd have been in prison for sure. After that shit, I drove into the desert to clear my head, but some crazy cop attacked me and caused an accident! I managed to get here on foot, and on that day... Boom. The war.}
{146}{}{You were very lucky. Now some more questions.}
{147}{}{War? What kind of war?}
{148}{}{I see. Well, shit happens. See you around.}

{149}{}{[He suddenly remembers something] You know... You know, listen. Fuck everyone who says life was better before the war. It was crap! The war with China, Canada's annexing, the new plague... Fear and hatred everywhere. And now? Freedom! Nobody bothers me, and I don't bother nobody. If only I had my Corvega... I'd drive all over America again, and no cops to stop me.}
{150}{}{Thanks for the history lesson. I have another question.}
{151}{}{Really? I'll have to go think about that. See you.}

{152}{}{Maybe I do know. Maybe I'm the one who locked it. Maybe I even have the key.}
{153}{}{Maybe you'll give it to me?}
{154}{}{Actually, I was just making conversation. I'm really interesting in something else.}
{155}{}{Keep it. I have enough information for now.}

{156}{}{Yeah, maybe... But you'll have to do something for me first. I've got everything I need here - except alcohol. Bring me something strong? Beer, or even booze. Hell, ethanol even. I've gone through my whole stash.}
{157}{}{I've got it all right here. Take it. Now where's my key?}
{158}{}{I'll keep that in mind. Another question.}
{159}{}{Fair deal. Wait here.}

{160}{}{Take it, take it, of course! I managed to get some nice things in my time.}
{161}{}{Excellent. How about another question?}
{162}{}{It's in your best interest if I find anything useful there. Bye.}
{163}{}{Alcohol delivery! Just give me the key first.}

{164}{}{Take it... Hey, where is it? Did I drop it somewhere? Look in the toilet - I'm not used to pigrat meat yet and I'm always on there. And leave the bottles. You didn't take them all this way for nothing, right?}
{165}{}{What a loss. See you, loser.}

{166}{}{War with China?}
{167}{}{Come on, you have to know about it! "Anchorage awaits you, patriot!" "Communism is at your door!" You've really never heard of it? Strange... We fought them for quite some time in Alaska. Now I see it was just the beginning.}
{168}{}{Canada's annexing?}
{169}{}{Those beaver-loving, maple-syrup-drinking, milk-bagging idiots... When the shit hit the fan, we needed to go through them to get to Alaska. It was a good chance to get that "country's" resources. Oh, sure, there were rebels here and there... But most of them knew what side they wanted to be on.}

#Разоблачение
{170}{}{Right now, I've got nothing but one toilet. But before the war, I was a family man with two old people at my side.}
{171}{}{So you're here all alone? Where is everybody?}
{172}{}{I saw something like a warehouse outside. Do you know if it's locked?}
{173}{}{Before the war? What are you talking about?}
{174}{}{One more question... }
{175}{}{I'm happy for you, but I have to go.}
{176}{}{Corvega, huh? I've heard of this. It was mentioned in the sheriff's holodisk.}
{177}{}{Who? [looks around] Oh, them... They ran off when the war started. There's no one left. You won't even find a trace.}
{178}{}{Interesting. I found a holodisk written by a deputy sheriff. And what a coincidence! - It mentioned an Ely Gorbinsky. Do you have anything to say about that?}
{179}{}{Well, let's suppose you're not lying. But I still have more questions.}
{180}{}{Well, if they're gone, then there's nothing to talk about. Bye.}

{181}{}{[His eyes narrow and he goes silent for several seconds] You just had to go digging around, didn't you? [clutches his shotgun] For half a century, I saw them every time I closed my eyes. And here you come, tearing open the scars! Don't you at least want to hear my side of the story?}
{182}{}{You can tell it under ten feet of dirt, you murdering piece of shit! [Attack]}
{183}{}{Interesting. Don't make any sudden moves, and I'll hear your side of the story.}
{184}{}{I wouldn't have touched them, but I was in the middle of the desert with no car, no help, and a nuclear war going on! You have no idea what it was like. Look at what it did to me! Eight people, all against me because of that dirty cop and his stories. But I was smarter than all of them. They didn't even know what had happened to the world.}
{185}{}{This isn't a defense. It's a confession. And I'm the one who will carry out your sentence. [Attack]}
{186}{}{Go on... }
{187}{}{I managed to get to Reno. The bombs hadn't touched it, but the people there... It was hell. When I got back to the mine, I hid in a small cave, only coming out at night. When I ran out of food, I snuck into the kitchen through the window... But one of the workers suprised me. I had to deal with him before he could call the others. The second one got too close to my cave, but he wounded me in the fight. I cut off his head and tossed it in the washing machine, and took the medicine I needed while they were distracted. Clever, huh? But on the way back, I tripped over another worker... On and on, until in a week they were all dead. I know what you're thinking. How could I live with myself? Am I even human?... Hmm. I don't know how to answer that.}
{188}{}{Just try.}
{189}{}{You're going to answer for it, alright. With your blood. [Attack]}

{190}{}{It was like a nightmare. Everything was different. Wild. Survival of the fittest. I've been living in fear, seeing their faces for all these years... So many years.}
{191}{}{There's no statute of limitations on this crime. It's time to pay, Ely Gorbinsky. [Attack]}
{192}{}{Fine, Ely. I'll let you be for now. Who knows what I would have done in your place?}

#Полное разоблачение
{193}{}{Say, about your story... Are you sure everything happened in a week?}
{194}{}{[Grits his teeth and closes his eyes] No! Don't ask me! I can't tell... [grabs his head and falls to the ground] Shut up, scumbag! - What are you doing? Leave me alone! No, I won't tell them! - [curls up, raking fingers across his skull] - Too late, Gorbinsky! The world is on fire, and we're burning with it! We're all going to die - and you, Ely, will be the first! - Stop, no, I can fix this! NOOO!!! [the ghoul drops on the ground, shaking]}
{195}{}{Woah... }
{196}{}{It seems that this ghoul suffers from multiple personality disorder. You can't tell who he really is - Ely Gorbinsky or the deputy sheriff.}
{197}{}{What? [tenses up, suddenly nervous] You... You don't believe me? Why all these questions?}
{198}{}{The dates don't match up with this holodisk. And it was written right after it happened... }
{199}{}{Leave! Run! He'll come back! He always does... }
{200}{}{Oh, just making conversation. I have another question.}

#Female character
{1112}{}{Hey, wait a minute! I didn't know anyone was here. How about we just go our separate ways, huh?}
{1164}{}{Take it... Hey, where is it? Did I drop it somewhere? Look in the toilet - I'm not used to pigrat meat yet and I'm always on there. And leave the bottles. You didn't take them all this way for nothing, right?}
{1172}{}{I saw something like a warehouse outside. Do you know if it's locked?}
{1175}{}{I'm happy for you, but I have to go.}
{1192}{}{Fine, Ely. I'll let you be for now. Who knows what I would have done in your place?}
