{100}{}{You see a Vault City guard.}
{101}{}{You see a fellow citizen, guarding the entrance to the City.}
{102}{}{Stop! Now!}

#Если видит героя в комбинезоне с черепом
{110}{}{Are they issuing black jumpsuits now?}
{111}{}{What's with the outfit?}
{112}{}{Is that a... Skull?}
{113}{}{I never seen a jumpsuit like that before.}
{114}{}{I really hope that jumpsuit isn't from the Wasteland.}
{115}{}{I think I've seen clothes like that on outsiders.}

#Попытка заговорить
{120}{}{Remember! Service guarantees citizenship!}
{121}{}{Need help?}
{122}{}{Sorry, no talking on duty.}
{123}{}{I've got nothing to report... To you.}
{124}{}{I'm on duty.}
{125}{}{Anything wrong, citizen?}
{126}{}{Greetings, citizen.}
{127}{}{Stay vigilant!}
{128}{}{Long live Vault City!}
{129}{}{The enemy never rests. We must always be ready.}
{130}{}{Tough day, citizen?}

{200}{}{Citizen! Get back to the city! Now!}
{201}{}{Why can't I leave?}
{202}{}{You should know that ordinary citizens are not allowed to leave city walls without a permit. Do you have a permit?}
{203}{}{Uh, permit?}
{204}{}{If you really need to leave the city, talk to the Chief of Security, Peter Graves. If you have a good reason, Graves will issue you a permit.}
{205}{}{Understood.}
{206}{}{Fine, I'm going back into the city.}

#Female character
{1120}{}{Remember! Service guarantees citizenship.}
{1121}{}{You need help?}
{1122}{}{Sorry, no talking on duty.}
{1123}{}{I've got nothing to report... To you.}
{1124}{}{I'm on duty.}
{1125}{}{Anything wrong, citizen?}
{1126}{}{Greetings, citizen.}
{1127}{}{Stay vigilant!}
{1128}{}{Long live the Vault City!}
{1129}{}{The enemy never rests, we must always be ready.}
{1130}{}{Tough day, citizen?}
{1200}{}{Citizen! Go back into the city immediately!}
