{100}{}{You see: a watchful guard.}
{101}{}{You see a guard keenly peering up and down the street.}
{102}{}{Don't even try that again!}

#Разговор
{110}{}{Yes, citizen? Do you need something?}
{111}{}{Why are you looking around like that?}
{112}{}{No, nothing.}

{113}{}{In that case, don't distract me. Oh, and stay vigilant!}
{114}{}{Er... Fine, as you say.}
{115}{}{I'm watching the streets for signs of trouble.}
{116}{}{Why, has something happened?}
{117}{}{Must be a tough job.}
{118}{}{Do you see a lot of crime around here?}
{119}{}{That seems excessive. Is something going on?}
{120}{}{I'll leave you alone.}

{121}{}{Not yet, citizen. Don't worry.}
{122}{}{Uh... Yes, as you can see.}
{123}{}{Excluding some past events, the city is completely crime-free. Don't worry, citizen.}
{124}{}{I can't share this information with common citizens. Crimes and accidents are handled by a special commission.}
{125}{}{Can I be a part of that commission?}
{126}{}{Hmm... No, they wouldn't take you in. But you could still help with an ongoing investigation.}
{127}{}{Okay. A couple of citizens are acting suspicious. Their jobs require them to leave the city perimeter. When they return, they act... Strangely. Suspiciously strangely. If you really want to help, follow them and tell me what they're doing.}
{128}{}{[Nods] I'm glad you take our city's security seriously.}
{129}{}{}
{130}{}{}
{131}{}{}
{132}{}{No, I don't want to spy on anybody.}

{133}{}{Of course. Forget everything I said.}
{134}{}{Wait, I changed my mind. What about those citizens? How are they suspicious?}
{135}{}{Fine.}

{136}{}{}
{137}{}{Who are they?}
{138}{}{How often do they go outside the perimeter?}
{139}{}{How much time do they spend outside the city?}
{140}{}{What do they do outside the city?}
{141}{}{I'll come back when I learn something.}

{142}{}{They are citizen Jacob and citizen Emily. They work at the technical service department.}
{143}{}{They are tasked with checking the security systems around the perimeter twice a day.}
{144}{}{They used to spend around two hours, but recently, they've been taking much longer.}
{145}{}{They check the security systems around the perimeter. A complete check should take around two hours.}

{146}{}{I'll help with the investigation. Who knows, it may be my last chance to help the city before I leave.}
{147}{}{What's with all the rules? Look, you're wound tight due to all this bureaucracy. Just tell me what to do and I'll take care of it.}
{148}{}{That's great and all, but I'm interested in something else.}
{149}{}{No way. I think you're forgetting who needs help here. I'll let you dwell on it for a little while.}
{200}{}{You're the one who caught those two citizens breaking regulations? Good job!}
{201}{}{What will happen to them?}
{202}{}{I'll think about it.}
{203}{}{That's up to the commission, but they'll probably be sentenced to extended isolation.}
{204}{}{Okay. Well, I won't take any more of your time.}

{205}{}{I heard that you're responsible for catching those two! Good job!}
{206}{}{Any news?}
{207}{}{False alarm. Everything is fine.}
{208}{}{Are you sure? What if they saw you?}
{209}{}{They didn't even check if they were being watched. They have nothing to hide.}
{210}{}{Perhaps, but I didn't see anything wrong with them.}
{211}{}{[Nods] Good work, citizen }
{212}{}{. You carried out your duty. I, and all of Vault City, thank you.}
{213}{}{Always happy to help!}
{214}{}{Do I get anything for my trouble?}

{215}{}{You didn't work that hard. Do you really think you deserve a reward?}
{216}{}{Fine, whatever you say...}
{217}{}{Look who's talking...}

{218}{}{You did your duty, and yet you ask for a reward? [he leans in close] I think... I can do something for you.}
{219}{}{I need 9mm ammo.}
{220}{}{I need 10mm ammo.}
{221}{}{I need money from the wasteland.}
{222}{}{I don't need anything for now.}
{223}{}{Of course. Here, take it.}
{224}{}{Thanks.}
{225}{}{Have a nice day, citizen }
{226}{}{.}
{227}{}{I'm not allowed to discuss commissions affairs. If you wanted to help, you're too late anyway - the latest case is closed due to lack of evidence.}
{228}{}{Uh-huh. I'd like to ask something else.}

#Female character
{1110}{}{Yes, citizen? What do you want?}
{1121}{}{Not yet, citizen. Don't worry.}
{1123}{}{Excluding some past events, the city is completely crime-free. Don't worry, citizen.}
{1134}{}{Wait, I changed my mind. What about those citizens? How are they suspicious?}
{1209}{}{They didn't even check if they were being watched. They have nothing to hide.}
{1211}{}{[Nods] Good work, citizen }
{1213}{}{Glad to help!}
{1225}{}{Have a nice day, citizen }
