{100}{}{You see: Jacob.}
{101}{}{You see Jacob, a citizen of Vault City.}
{102}{}{Ugh, don't do that again!}

{103}{}{Err... Long live Vault City!}
{104}{}{We deserve it, I know.}
{105}{}{You see Emily.}
{106}{}{You see Emily, a citizen of Vault City.}
{107}{}{I won't say a word without Jacob!}

#Плавающие фразы
{110}{}{Listen, someone's coming...}
{111}{}{Hide it! Quick!}
{112}{}{Ohh... No one saw us, right?}
{113}{}{::sighs heavily::}
{114}{}{Just... A little more, and...}

{120}{}{Your turn.}
{121}{}{Come on, before someone sees us...}
{122}{}{Ah... Just a little more...}
{123}{}{What... Are... You... Doing...}
{124}{}{Why is my mouth producing so much saliva!?}
{125}{}{What is this?!}
{126}{}{OHH!}
{127}{}{I didn't expect that.}

#Разговор
{200}{}{[As soon as they see you, they immediately start putting their clothes back on] Oh, citizen! Uh... Are you allowed to be here?}
{201}{}{Me? Yes. Are you?}
{202}{}{We, uh, work here. We were checking the sensors...}
{203}{}{Quit pretending. I saw everything.}
{204}{}{You did? Fine, I'll pretend that it is as you say it is. Have a nice day.}

{205}{}{[Lowers his head in shame]}
{206}{}{Oh, now you're feeling guilty?}
{207}{}{Hey, don't go soft on me now. You can still make for it, can't you?}

{208}{}{As if... We both know the prohibition of physical contact... But... We just couldn't resist.}
{209}{}{How interesting. It must be a very unusual experience. Tell me about it.}
{210}{}{I had enough of your whining. I know what to do with you people.}

{211}{}{We know how bad the punishment is. We tried to control ourselves! But we just... Couldn't. Maybe... Maybe we just don't belong in a normal community.}
{212}{}{What do you know about the prohibition of physical contact?}
{213}{}{Why couldn't you control yourselves?}
{214}{}{What did you see on each other?}
{215}{}{How often have you had physical contact?}
{216}{}{How could you not realize you could have been spied on?}

{220}{}{[Stands at attention] As per directive 16/8 of the Vault 8 societal and personal communication rulebook, physical contact between two or more citizens for a period exceeding five seconds is forbidden. Any direct contact of naked skin or body parts is considered as physical. The violation of this rule is punishable by isolation from society for one year.}
{221}{}{I don't know how to explain it... We are drawn to each other. We broke the rule once, by accident. And then, we wanted more and more... And in the end, we couldn't get enough! It may be some sort of contagious disease, like radiation poisoning.}
{222}{}{It's... Strange, but under our clothes, we have... Differences. Now I understand why we must use separate showers and restrooms, and sleep in pajamas in different rooms.}
{223}{}{For the last two months, while checking the perimeter sensors. We only looked and touched! Honestly!}
{224}{}{I think one of the guards suspects us, but only specific citizens can go outside the perimeter. When we leave, nobody ever followed us... Well, until now.}

{225}{}{You'll tell the guards, and then we'll be isolated, right?}
{226}{}{No, first I want to hear how you allowed yourselves to get to this point.}
{227}{}{Yes, that's right.}
{228}{}{No, I'm letting you go... This time. Consider yourselves warned.}

{229}{}{I knew this was a mistake! We have to turn ourselves in, Emily. The guards would find out about us sooner or later.}
{230}{}{Move, I have things to do.}
{231}{}{Really!? You'll let us go? Emily, we're in luck! From now on, we have to be more careful...}
{232}{}{Exactly. The guards are always watching. Now get back to work.}
{233}{}{That's right! And don't do anything stupid...}

#Женская реплика
{1200}{}{[As soon as they see you, they immediately start putting their clothes back on] Oh, citizen! Uh... Are you allowed to be here?}
{1203}{}{Quit pretending. I saw everything.}