{100}{}{You see Ed.}
{101}{}{You see Ed - an electrician. He reeks of rubber and burned copper.}
{102}{}{Hm. What a strange feeling. Like someone's staring at me...}
{103}{}{You gained the "Empathy" perk.}

#Start tree
{110}{}{[The specialist looks up from his microchips, raising an eyebrow, as you walk in.] Wrong door?}
{111}{}{Err, maybe. What is this place?}
{112}{}{[Rises from behind the workbench, stretching out his limbs] This is my private office. I'm Ed, the chief electrician on the dam.}
{113}{}{You're just who I need! I need an electronics specialist.}
{114}{}{In that case, I did get the wrong door. All the best.}

{115}{}{[Sighs] Not a moment of rest.}
{116}{}{I won't distract you anymore.}

###############################################################
#
#                  Questioning
#
###############################################################

#General Questions
{120}{}{I wanted to ask you about the dam and your work here.}
{121}{}{Ah, I get'cha. Big place, hard to get accustomed. Alright, I can chat, but not for long. After all, I've got work, you know?}
{122}{}{Have you been working long?}
{123}{}{Yeah. Five years and four months. It's hard to find workers who stay in one spot, but there's not much I can do. This is the only place in Vegas where I can put my talents to good use. Bob Neil appreciates it, which is why he basically dragged me off the streets and sat me in this chair.}
{124}{}{How did you get into electronics?}
{125}{}{Well, I used to earn a few bucks here and there - janitor, waiter, teller, but my soul was never in it. Every time I got back home, I would find myself tinkering with a pile of broken computers. I'll never forget those days. Now I have everything I need to work I even got a welder installed. Long story short, I'm like a gecko with a nest of grubs.}
{126}{}{What do you do here?}
{127}{}{Maintenance and repair of the tech here. There's always something to do here. Sometimes people bring in tech for commission. Although, recently, I've been really into poking around energy weapons - now that's something to spend time on!}
{128}{}{How are things on the dam?}
{129}{}{Pretty bad. This place is old, but recently the workers have been leaving. Hell knows why. Probably someone in the "Clean city" decided to line their pockets. [snorts]}
{130}{}{They were pretty bad, but it seems everything is getting better. There's hopes at least.}
{131}{}{Let's talk about something else.}
{132}{}{What can you say about your boss?}
{133}{}{Bob Neil? He's an honest man. As much a fan of old tech as me. Although he works less with his hands and shouts at the workers more. He-he. Say what you want, but everybody respects him.}

#Ammo Press
{140}{}{Can you assemble an ammo press?}
{141}{}{Who, me? If I could, I'd be rich! Unfortunately, I don't have anything suitable for the job - no tools, no components. I specialize in electronics, after all.}
{142}{}{That's a shame.}
{143}{}{Well, I'll look somewhere else then.}

#PLK
{150}{}{Can you repair this Nuka-Cola factory controller?}
{151}{}{Maybe I can, maybe I can't. It all depends on my motivation. You know - 1000$ would make for good motivation.}
{152}{}{Well in that case, here is your motivation and here's the device. I expect results.}
{153}{}{I'll think about it.}
{154}{}{Ed quickly finishes the job. All that's left is to bring the device back to the factory.}

#Filter for the water tower
{160}{}{Did you manage to get your hands on a water tower pump?}
{161}{}{You're talking about the filter for the tower in Salt Lake, right? I heard this story already.}
{162}{}{Heard? Where?}
{163}{}{The caravaneers have already spread the news all across the state. First thing people do is come here. But, the dam doesn't have artesian pumps, so we shouldn't have any filters for them either.}
{164}{}{Where do you think I could find one?}
{165}{}{If I did, I would've been rolling in cash, if you know what I mean. He-he. You won't find it. Nobody will. Although, I do hear talk of some caravan riding off to try and find the filter... Without returning. But that's just rumors. Talk to the caravaneers, if you'd like to know more.}
{166}{}{Alright.}

#Repair of train's onboard computer:
{170}{}{I've got a job that should be interesting. An on-board computer from a train.}
{171}{}{[Whistles] Lovely! I've always wanted to try something unique. Let me take a closer look.}
{172}{}{Here you go}
{173}{}{Hmm... Something is missing. Probably taken out to fix something else. Looks like I'll need to tinker for a while, and my time costs money. I'll do everything I can for 2500$.}
{174}{}{For a price like that, I'm expecting the best! Here's the money.}
{175}{}{I'll think about offer.}
{176}{}{The technician managed to repair the train computer.}

#Empathetic Amplifier
{180}{}{You mentioned making repairs for commission. Do you sell any tech as well?}
{181}{}{Well, that's not very often. I usually just repair everything that is brought in, but some stuff gets left behind. Although... Looking at that Pip-Boy, I think I've got something for you.}
{182}{}{What is this something?}

{183}{}{An Empathetic Amplifier! Technically, it can analyze the emotions of surrounding people, and relay them through an ocular sensor on your right eye. But, that is assuming it's installed correctly.}
{184}{}{But Pip-Boys are given to vault dwellers. Where did you get this from?}
{185}{}{Well, Vegas also has Vaults. I know about six, but they're all sealed. But Pip-Boys weren't used exclusively by vault dwellers. They were used by businessmen before the War. It's useful after all. So, from time to time, a nice toy like this pops up.}
{186}{}{What's the difficulty with installing it?}
{187}{}{You've got the old Pip-Boy 2009. The amplifier was made for the modern 3000 model. Not sure if you've seen one, but they're vastly different. But, I think most of the work will go into modifying the program.}
{188}{}{How much will this device cost me?}
{189}{}{Well, I'll sell it for 2000$. But if you don't think you can install it yourself, I'll charge 500$ extra for the installation.}
{190}{}{I'm not interested yet.}
{191}{}{Alright, here's your 2500$ and install this thing.}
{192}{}{I'll buy it for the 2000$, I can take care of the installation.}
{193}{}{[You wait as the technician begins his work] Hm... Everything seems to be in order. Here, try for yourself. I'll give you a two week warranty.}
{194}{}{Great.}
{195}{}{Fine, here's the device. If you do need help installing it, I'll be here.}
{196}{}{Alright.}
{197}{}{Remember that amplifier for my Pip-Boy? I need you to install it.}
{198}{}{Only 500$ and everything will be take care of.}
{199}{}{Alright, here's the cash.}

###############################################################
#
#                  Upgrades
#
###############################################################

#Initial cues
{200}{}{Can I talk to you if I need technical help?}
{201}{}{Sure thing. Not for free, of course. I don't use my skill for free - it's called principles. Taught by life.}
{202}{}{Can you help with repairing a weapon?}
{203}{}{I'm an expert in electronics. If you have an energy weapon, I'll be happy to help. Otherwise, I doubt there's much I can do. You have anything?}
{204}{}{I need help with weapon maintenance.}
{205}{}{No, nothing yet.}
{206}{}{I need something else.}

#Upgrade list
{210}{}{Laser rifle.}
{211}{}{Laser pistol.}
{212}{}{Plasma rifle.}
{213}{}{Plasma pistol.}
{214}{}{Cattleprod.}
{215}{}{Power fist.}
{216}{}{Can you charge a REZ-4 cannon?}
{217}{}{}
{218}{}{Magneto-laser pistol.}

#General cues for upgrades
{230}{}{Lovely weapon. But I can make it better. It will cost }
{231}{}{ $.}
{232}{}{Here's the money and the weapon.}
{233}{}{I can't afford that yet.}
{234}{}{[The job took over an hour, but the master has finished his job]}
{235}{}{Great, this is what I needed.}

{236}{}{[Disappointedly] That's a shame, not every day I get to see a piece like that. But, my rule is singular. No money - no work.}
{237}{}{Actually, I'd like you to check out a different weapon.}
{238}{}{Let's put this off, I have another question.}
{239}{}{Goodbye.}

{240}{}{What is the meaning of this!?}
{241}{}{I don't know...}
{242}{}{Now, let's try something similar with another weapon.}
{243}{}{Here's the money, schematics and components. Now get to work.}

#Separate cues for upgrades
{250}{}{}
{251}{}{I saw a gun like this before. I think I have a recycler chip leftover from a previous contract. It'll reduce the load on the microfusion battery. Speaking simply, it'll double the ammunition capacity. I can install it for }
{252}{}{Ah, a familiar design. I can install a magnetic calibration system. It'll increase the piercing capacity of the beam. It's yours for }
{253}{}{I read in an old magazine about this trick. The plasma chamber can be insulated with a layer of thermal winding. That should let the bolt form quicker. It will add a nice punch to the gun. I can install it for }
{254}{}{I can mess around with the magnetic ammo feed. It will reduce the load on the system's battery elements, meaning that the battery will last longer. I'll do it for }
{255}{}{"Farmer's Best Friend", isn't it? Who knew that by replacing the feeds, a simple farmer's tool can be turned into a military zapper. Only for  }
{256}{}{I think I know what to do. I've got some spare parts from a high power servo-generator. It's stronger than the one here. I can replace it for }
{257}{}{[Carefully and reverently examines the weapon] Magnificent! No doubt from some shiny military base. Although, everything is possible. I can charge it for }
{258}{}{What, again!? Well... Alright. The price is still the same, }
{259}{}{Alright. I'll do it for }
{260}{}{Ah yes, I remember - the magnetic calibration system increases the intensity of the beam. You'd think that this is all that can be done, but not quite. I can replace the contacts, pick out a few fresh lenses and re-solder the control plate. That will decrease the time it takes to form a beam. But, with tech like that, an upgrade this intense won't come without consequences.}
{261}{}{What do you mean?}
{262}{}{I mean, that the quicker a beam forms, the shorter it is, thus it'll take less time to dissipate. Additionally, it'll put some strain on the batteries, so you'll need to recharge it more often. If you're happy with the tradeoff, I can set you up for }

#Alien blaster
{270}{}{Strange, inactive blaster.}
{271}{}{Hmm... [scratches his head] Curious thing. Except it's far too advanced for me. I think my mate, biker Phil can figure it out. But I don't know how to get in touch with him.}
{272}{}{Thanks for the tip.}
{273}{}{Thanks for the tip. Is there anything else that can help me find this, Phil?}
{274}{}{Well, he, like the other bikers, doesn't have a place to call home, so he pokes his head into Vegas from time to time. Although, I heard something about their base being somewhere up north. The only large city that way is Salt Lake City. Maybe someone there will know more.}

#About Jay Kukish and the bikers
{300}{}{Hm. I know another fan of tech - Jay Kukish...}
{301}{}{Well, I'm not surprised. There aren't many people in Vegas who bikers could talk to about tech. They're crazy about it. Jay was here not so long ago, he was asking about a strange device. But, I couldn't help him.}
{302}{}{What device?}
{303}{}{You know, something like a database that works based on crystals. It's got these defensive layers. I couldn't even go through the first one. But, the thing was fascinating.}
{304}{}{Why do you think Jay needs it?}
{305}{}{I don't think he knows himself. Looks like he's trying to figure out what it's for. Pre-war tech is like his life purpose. He believes that technology must be kept away from common hands, and be used only by a small and capable group of people.}
{306}{}{Understood. Thanks.}