{100}{}{You see mister Farber.}
{101}{}{You see the administrator of the slave ring.}

#Attempt to speak after the first fight
{102}{}{Sorry. Everyone has their golden age. But it always ends.}

#First dialogue:
{110}{}{[Appraises you with a glance] Betting... Or fighting?}
{111}{}{What, I can fight?}
{112}{}{Neither. Just watching.}
{113}{}{Yeah, there's an opportunity. Would you like to know more?}
{114}{}{Yeah, tell me about the ring fights.}
{115}{}{Understood.}
{116}{}{Where did you get the fighters on the ring right now?}
{117}{}{I'm going now.}

#Question about fighting - not accepting
{118}{}{So, do you ready to fight?}
{119}{}{From Slavertown, of course. The slavers guild is upstairs, and the courtyard is always full of livestock. They own the whole ring.}

#Question about fighting - accepting
{120}{}{Hmh. [Studies you closer] You know, we have a very *hardcore* ring. Real bloodsport! But you have potential. I suggest you to train a little.}
{121}{}{So, I don't fit? What a shame.}
{122}{}{[Studies you closer] What determination! But I'm warning you - we have fights *without limits*. Bloodsport! The only rule is no weapons. I suggest warming up first. We even have a coach.}
{123}{}{How much will I earn for a victory?}
{124}{}{That depends on how much everyone will lose on the bets. Betting happens during the fight and then the winnings are handed out. What is left is divided among those involved in the fight.}
{125}{}{My opponents will be slaves?}
{126}{}{At first - yes. Sometimes champions from New Reno come by. Sometimes ours come to them. It'll be one hell of a show either way.}
{127}{}{Hell? Exactly what I'm looking for!}
{128}{}{I suggest getting ready first. We usually begin the real fights in the evening, at 21:00.}
{129}{}{Alright.}
{130}{}{Can you tell me what I'm missing?}

#Preparing for fight and receiving reward
{132}{}{Hey, ready to fight?!}
{133}{}{Hell YEAH!!!}
{134}{}{Not yet.}

{135}{}{Great! You still have some time. The coach will warm you up a bit and then... THERE WILL BE BLOOD!!!}
{136}{}{[Wait until 21:00 and go into the ring]}

{137}{}{Here you are! Your prize... [hands over the winnings] Once you're ready for the next fight, just talk to me.}
{138}{}{Fine.}

{139}{}{Who do we have here! Thirsty for more bloodshed?}
{140}{}{Yes, I'm ready to fight.}
{141}{}{No, just looking at those slaves.}

{142}{}{Err, no, we're not ready. Come back tomorrow, ok?}
{143}{}{What determination! Let's go!}
{144}{}{What determination! You may have noticed we're increasing the pressure, raising the stakes slowly. But *something* just came up and this something threw you a challenge. I'm sure you'll enjoy this. Onwards!}
{145}{}{You'll get an extra reward for this fight. This time we've got a special visitor from New Reno. He himself asked for a fight with you. My warning - this will be serious, even for our ring. I'd suggest remembering all your weaknesses. They'll be your biggest problems.}
{146}{}{Bloody amazing! How didn't you tear his hand out with that hold? We get a pretty payout for fights like these, the audience is just ecstatic! Anyway, here's your reward [hands over the cash]}
{147}{}{The crowd was just crazy about that fight! That's what I call determination! Here's the coin, champion! [hands over the cash] But... Now for the bad news.}
{148}{}{What do you mean!?}
{149}{}{We have a bit of a problem. The crowd believes in you. They put big money on you and... Win! Do you get where I'm going with this?}
{150}{}{Of course! The fans love me.}
{151}{}{That's why, my friend, we can't keep making money on your victories. The crowd isn't losing their bets, which is how we're meant to make a profit. So, this was your last fight here. You have leave the ring... Keep in mind, Reno has a huge ring as well, maybe you should try your luck there.}
{152}{}{And it was going so well...}

#Explanation of what's needed for fights:
{159}{}{[Sighs, as if he hears this question every day] Well, you don't look strong enough. Lift some weights. The crowd needs something to look at. And your skills seem to be lacking - you don't look like you've been in a fight or even in a bar brawl.}
{160}{}{Well, you seem to have the skill if a skilled fighter. But you are lacking the musculature. Our fighters will knock you down in the first round, which means the viewers won't get a kick.}
{161}{}{You might look ripped, that isn't a problem. But you don't look like a very skilled fighter. I suggest getting some tips for hand-to-hand. We've got a coach for that.}
{162}{}{Alright, got it. Thank you.}

#Pizza delivery
{170}{}{[His face immediately changes as he sees the pizza in your hands] Gecko bite me! Where the fuck were you, courier!? Get this shit outta here. I'll be talking to your boss personally to make sure they throw you right the fuck out! Phillips Cafe has *never* let me down like this before. EVER!}
{171}{}{[Leave]}
{172}{}{[His face immediately changes as he sees the pizza in your hands] Gecko bite me! How did you get to this, fighter!? I won't even talk about why did you managed to join a pizza delivery service after all your glory on the ring, but to be late for such a simple delivery? Philips Cafe has *never* let me down before. You can return the pizza, I'll talk to your boss personally. Get out of my sight!}
{173}{}{[Seeing the pizza in your hands, he makes a short wave with his hand, indicating for you to wait] Hold on, courier.}
{174}{}{[Wait]}
{175}{}{[You're waiting as the administrator goes through his ledgers]}
{176}{}{Ahem...}
{177}{}{[Wait a little longer]}
{178}{}{[You wait longer as the administrator talks to someone about the weather and the latest bets]}
{179}{}{[Ignores your attempt to get his attention]}
{180}{}{Excuse me, sir, your pizza...}
{181}{}{[Keep waiting]}
{182}{}{Wait, courier! I said wait!}
{183}{}{Here's what, how about you pay, or you'll be left without your pizza?}
{184}{}{No problem, sir. I'll wait.}
{185}{}{[After a few more minutes, when you've been pushed into a corner by a crowd of onlookers, the administrator waves you over] How much?}
{186}{}{What are you mumbling there? Wait! I said wait!}
{187}{}{Either you pay for the pizza or I leave.}
{188}{}{$, sir.}
{189}{}{[Widens his eyes] Where did Phillips began hiring such rude assholes!? Just remember, this isn't the last you heard from me! Now give me that pizza, here's your pathetic pay. Take it and get the hell out of here.}
{190}{}{There isn't enough here.}
{191}{}{Thank you, sir, but I need another 10$ for the delivery.}
{192}{}{You didn't earn it! Your delivery is shit! Now get the hell out!}
{193}{}{But I thought you were a man of honor. After all, I did my part - brought the pizza on time and waited for you in this crowd. Maybe you should rethink this.}
{194}{}{[Leave]}
{195}{}{Hmm... Perhaps I was mistaken about you and Phillips hired you for a reason. Alright, here's your tip. Now get out of here.}
{196}{}{Thank you, sir.}
{197}{}{[Critically looks the pizza over before counting out the money]}
{198}{}{You didn't ear it! Your delivery is shit. While you were standing around, you managed to ruin it's look. Look: the box is crumpled, the topping is a jumble. You need to be more careful next time. Now get outta here!}
{199}{}{Don't waste my time with any of that crap! Get out.}

#Fight on the ring:
{200}{}{FIGHT!}
{201}{}{You won! That was awesome!}

{202}{}{I'LL TEAR YOUR EARS OFF!!!}
{203}{}{BANZAI!!!}
{204}{}{AGHRRR!!!}
{205}{}{TIME TO END YOU!!!}
{206}{}{UHRR!!!}
{207}{}{BEG FOR MERCY!!!}
{208}{}{THERE CAN BE ONLY ONE!!!}
{209}{}{YOU'RE DEAD!!!}
{210}{}{I AM DEATH!!!}
{211}{}{MEDIOCRE!!!}
{212}{}{TREMBLE, YOU SLIME!!!}
{213}{}{I'M GONNA WEAR YOUR TEETH AS A NECKLACE!!!}
{214}{}{I'LL MAKE A TALISMAN OUT OF YOUR BONES!!!}
{215}{}{YOU'RE NOTHING!!!}
{216}{}{I WILL BURY YOU!!!}
{217}{}{GET YOUR ASS OVER HERE!!!}
{218}{}{JUST ANOTHER MILKSOP!!!}
{219}{}{EAT THIS, DREKHEAD!!!}
{220}{}{ROTBAG! ROTBAG!!!}
{221}{}{I'LL KILL EVERYONE!!!}
{222}{}{I'LL BURY YOU INTO CONCRETE!!!}
{223}{}{NOW THE REAL FUN BEGINS!!!}
{224}{}{DRY YOUR PANTS OUT, WIMP!!!}
{225}{}{NO PANIC!!!}
{226}{}{I'LL BEAT THE SHIT OUT OF YOU!!!}
{227}{}{I'M A KAMIKA-AZAH!!!}
{228}{}{A-A-ARGH!!!}

{250}{}{You won!}
{251}{}{You won! It was a good fight!}
{252}{}{You beat a terrifying opponent! This was awesome!}
{253}{}{You beat a really powerful opponent! This was amazing! Your fans are ecstatic!}

#Female version:
{1118}{}{Well, ready to fight?}
{1132}{}{Hey, ready for the fight?!}
{1134}{}{No, not yet.}
{1137}{}{Here you are! Your prize... [hands over the winnings] Once you're ready for the next fight, just talk to me.}
{1140}{}{Yeah, I'm ready to fight.}
{1141}{}{No, just came here to watch the slaves.}
{1142}{}{Err, no, we're not ready yet. Come back tomorrow, ok?}
{1144}{}{What determination! You may have noticed we're increasing the pressure, raising the stakes slowly. But *something* just came up and this something threw you a challenge. I'm sure you'll enjoy this. Onwards!}
{1146}{}{Bloody amazing! How didn't you tear his hand out with that hold? We get a pretty payout for fights like these, the audience is just ecstatic! Anyway, here's your reward [hands over the cash}
{1147}{}{Uhm just crazy about that fight! That's what I call determination! Here's the coin, champion! [hands over the cash] But... Now for the bad news.}
{1151}{}{That's why, sister, we can't keep making money on your victories. The crowd isn't losing their bets, which is how we're meant to make a profit. So, this was your last fight here. You have leave the ring... Keep in mind, Reno has a huge ring as well, maybe you should try your luck there.}
