{100}{}{You see a coach.}
{101}{}{you see a coach. Behind his straight face you can discern some hidden bloodlust.}
{102}{}{That's good. But I gotta go.}

#Starting dialogue branch
{109}{}{[Shakes head in approval] I'm glad to see you. You are my pride.}
{110}{}{Another star? [examines you from head to toe]}
{111}{}{Speak, I'm listening.}

{112}{}{Are you a coach? Will you teach me the art of a bloody fight?}
{113}{}{I need another training session. Here's 1000 bucks.}
{114}{}{I don't need anything.}

#First workout
{115}{}{My time is money. I take $1000 for one training.}
{116}{}{I have the amount. Shall we start training right now?}
{117}{}{I see. I will return when I decide to train.}
{118}{}{Now! To the shower! Move!}
{119}{}{Sir, yes, sir!.. Uh, where's the shower?}

#Intermediate workouts
{120}{}{You shouldn't exercise so often. Come back tomorrow when you gain strength.}
{121}{}{You know better, coach.}
{122}{}{Sorry, but I have nothing left to teach you anymore. You have grown up and now on your own. Your future teacher is the ring, not the gym.}
{123}{}{Oh, well coach, if you say so...}

#Info-messages after training
{124}{}{After the fifth training session you finally made some progress. Your Unarmed skill increased by 5%!}
{125}{}{You have finished your tenth training session already, which hasn't passed without effect. Your Unarmed skill increased by 5%!}
{126}{}{Your hard work was not in vain. After the fifteenth training session your Unarmed skill increased by 5%!}
{127}{}{That was your twentieth training! Such diligence was not in vain. Your Unarmed skill increased by 5%.}
{128}{}{That was your last training. You increased the Unarmed skill by 5% and your strength by 1!}
{129}{}{You have carried out an ordinary training. But the results are not visible yet. You need to train more.}

#After the last training session
{130}{}{Great job, champion! Such diligence, such stamina... Who would have thought? Until now, no one could endure such prolonged exercises. I'm proud of you! But... You know, I taught you everything I could. Next you will have to grow on your own.}
{131}{}{Thank you, coach, for everything.}
{132}{}{Wow! What a technique! But I won't be able to help you. I have never worked with such a good fighter.}

#Floating phrases, if you stand in the middle of the small ring
{133}{}{Stop waltzing around! What kind of movement is it? It's the ring, damn you, not the dance floor!}
{134}{}{Good job, you dance nicely. Would be better if you danced like that in the ring. Ha-ha-ha!}
{135}{}{No, champion. Your place is on the big ring and not on this dance floor.}
{136}{}{Eh... Are you talking to me?}

{137}{}{Your hard work was not in vain: your Unarmed skill increased by 5%!}
{138}{}{After all those exhausting exercises you increased your Strength.}

#Women's replics
{1122}{}{Sorry, but I have nothing left to teach you anymore. You have grown up and now on your own. Your future school is the ring, not the gym.}
{1130}{}{Great job, champion! Such diligence, such stamina... Who would have thought? Until now, no one could endure such prolonged exercises. I'm proud of you! But... You know, I taught you everything I could. Next you will have to grow on your own.}
