{100}{}{You see a tired strong man.}
{101}{}{You see a man who can no longer stand on his feet from grueling workouts.}

#С'ар'овая ве'ка 
{110}{}{[You see a weary man, he breathes heavily]}
{111}{}{Hello!}

{112}{}{Hey, what's wrong with you? Broke in the ring?}
{113}{}{Listen, friend, don't you know how to, uh, sort of prepare for battle without special training? Well, you know, with amphetamines, for example.}
{114}{}{[Leave him]}

#Про 'ренировки
{115}{}{Trainer, a monster, gets off on me. See? My stamina sucks!}
{116}{}{Well, you don't look like some nerd. There's some biceps!}
{117}{}{You too? I also thought that getting buffed is enough! The two years of training! Damn! And no wins!}
{118}{}{Uh... Not one?!}
{119}{}{No stamina, you know? The first round in the ring is mine, and then I'm exhausted.}
{120}{}{Oh, so that's what it is.}

{121}{}{And this coach - he's a beast! He tries to pump my endurance. So, I'm always like this after a workout, lay on the mattress, unable to move.}
{122}{}{And how about amphetamines? Psycho, for example, it could help.}
{123}{}{Let me give you a massage! You'll feel better, you'll see.}
{124}{}{Okay. Well, then I'll leave you.}

#Массаж
{125}{}{A man to touch me? Hey, hands off!}
{126}{}{Oh, come on! My thing was to offer...}
{127}{}{[Smiling] Wow! Such beauty is going to paw me? Come on, baby! Finally, I get the glory!}
{128}{}{Great! Flip, champion!}
{129}{}{Uh... No. I'll go get... Uh... The ointment first, Yes. Look, just wait.}
{130}{}{Nah! Don't want to! You will torture me worse than the coach with your hands!}
{131}{}{Well, as you wish.}
{132}{}{Oh! What a thrill!!}
{133}{}{You massaged the fighter for an hour. The client is happy!}

#Про дурь
{134}{}{You know, I tried this stuff. The coach rightly says, it is better to push even harder in training than die.}
{135}{}{Die?}
{136}{}{Ha! And what do you expect?! Got doped and the ring is yours? You know how many of our lads went off from this stuff?}
{137}{}{How?}
{138}{}{Heart! The heart cannot stand it! It's not so simple, it's still necessary to strain after in the ring or in training. The thing is garbage, don't even think about it.}
{139}{}{And yet you know where to get the dope, right?}
{140}{}{Fine.}

{141}{}{I don't know! Get off me, you damn junkie! Fuck off! [the eyes of a fighter sparkle with fury, it seems he really doesn't like this conversation]}
{142}{}{You know! Tell me!}
{143}{}{Okay, pal, I'm not straining you. Okay, relax.}

{144}{}{I'll tell you, just because I see - you're one of us.}
{145}{}{Come on, I won't tell anyone, be sure.}
{146}{}{There is a large laboratory somewhere outside the city. The Black Caravan, as we call it, goes there every two days. Comes quietly to the parking lot in the shade of the office and pushes drugs, that's how the stuff gets to the city. I used to deal with them, but then gave up, so I don't know, maybe they are already moved to another place.}
{147}{}{Okay, thanks for telling me. This is just what I needed.}

{148}{}{Thanks in any other form would be nicer. He-he.}
{149}{}{Oh yeah, here's 50 bucks for the info.}
{150}{}{Take a beer, relax a little.}
{151}{}{Hmm. Well, here's a bottle of cola, for refreshment.}
{152}{}{Sorry, I have nothing, I'll bring some later.}

#Про расписку на подлог выродков
{153}{}{Um, listen, what do you think, why the slavers tried to frame the freaks?}
{154}{}{What was that?}
{155}{}{Yes, you see, the chief of the Slavertown hired someone to put drugs to the freaks.}
{156}{}{Oh, yeah, that's obvious.}
{157}{}{Really?}
{158}{}{You bet it is! Don't you understand? The chief wants a percentage of income from the Hoover dam. And the dam is in need of workers. I don't know exactly what the deal is, but I think the chief tries to push his slaves to the dam. Bob Neil, obviously, doesn't like that, and looks for alternatives. So, chief must've decided that the freaks should be dealt with, so the dam owner had no other choice than to accept slaves to work. Otherwise, no money for him.}
{159}{}{Where they got the dope, don't you know?}
{160}{}{Hmm. Interesting thought. I'll take note of that.}

{161}{}{Ah, so that's what it is about! Why didn't you tell that first. Why start with Bob Neil anyway?}
{162}{}{No reason... Well, to hell with them. So how about amphetamines?}