{100}{}{You see mister Farber.}
{101}{}{You see the administrator of the slave ring.}

#Attempt to speak after the first fight
{102}{}{Sorry. Everyone has their golden age. But it always ends.}

#First dialogue:
{110}{}{[He gives you an evaluating look] Betting?. Or fighting?}
{111}{}{What, I can fight?}
{112}{}{Neither. Just watching.}
{113}{}{Yeah, there's an opportunity. Would you like to know more?}
{114}{}{Yeah, tell me about the ring fights.}
{115}{}{Understood.}
{116}{}{Where did you get the fighters that on the ring right now?}
{117}{}{I'm going now.}

#Question about fighting - not accepting
{118}{}{So, are you ready to fight?}
{119}{}{From Slavertown, of course. The slavers guild is upstairs, and the courtyard is always full of livestock. They own the whole ring.}

#Question about fighting - accepting
{120}{}{Hmh. [Studies you closer] You know, we have a VERY hardcore ring. A real blood sport! But I see the potential in you. I suggest you train a little.}
{121}{}{So, I'm not fit enough? What a shame.}
{122}{}{[Studies you closer] What determination! But be warned, we have no limits. A real blood sport! The only rule is no weapons. I suggest you warm up first. We even have a coach.}
{123}{}{How much will I earn for one fight?}
{124}{}{That depends on how much everyone will lose on the bets. Betting happens during the fight and then the winnings are handed out. What is left is divided among those involved in the fight.}
{125}{}{Would my opponents be slaves?}
{126}{}{At first - yes. Sometimes champions from New Reno come by. Sometimes ours come to them. It'll be one hell of a show either way.}
{127}{}{Hell? Exactly what I'm looking for!}
{128}{}{I suggest getting ready first. We usually begin the real fights in the evening, at 21:00.}
{129}{}{Alright.}
{130}{}{Can you tell me what I lack?}

#Preparing for fight and receiving reward
{132}{}{Are you ready to fight?!}
{133}{}{Hell YEAH!!!}
{134}{}{Not yet.}

{135}{}{Great! You still have some time to prepare. The coach will help you to warm up a bit and then... THERE WILL BE BLOOD!!!}
{136}{}{[Wait until 21:00 and go into the ring]}

{137}{}{Here you are! And here's your prize... [He hands over the winnings] Once you're ready for the next fight, just talk to me.}
{138}{}{Fine.}

{139}{}{Who do we have here! Thirsty for more blood?}
{140}{}{Yes, I'm ready to fight.}
{141}{}{No, just watching the slaves.}

{142}{}{Err, no, we're not ready. Come back tomorrow, okay?}
{143}{}{What determination! Let's go!}
{144}{}{What determination! You may have noticed that we are increasing the pressure, gradually raising the stakes. But SOMETHING just showed up recently, and it has challenged you. I'm sure you're going to love it. Go!}
{145}{}{You'll get an extra reward for this fight. This time we've got a special visitor from New Reno. He specifically asked for a fight with you. This is going to be very serious, even for our ring's standards. I'd suggest remembering all your weaknesses. They'll be your biggest problems.}
{146}{}{Bloody amazing! How didn't you tear his hand out with that hold? We get a pretty payout for fights like these, the audience is just ecstatic! Anyway, here's your reward [He hands you the cash]}
{147}{}{The crowd was just crazy about that fight! That's what I call determination! Here's the coin, champion! [He hands you the cash] But... Now for the bad news.}
{148}{}{What do you mean?}
{149}{}{We have a bit of a problem. The crowd believes in you. They put big money on you and... Win! Do you get where I'm going with this?}
{150}{}{Of course! The fans love me.}
{151}{}{That's why, my friend, we can't keep making money on your victories. The crowd isn't losing their bets, which is how we're meant to make a profit. So, this was your last fight here. You have leave the ring... Keep in mind, Reno has a huge ring as well, maybe you should try your luck there.}
{152}{}{And it was going so well...}

#Explanation of what's needed for fights:
{159}{}{[Sighs, as if he hears this question every day] Well, you don't look strong enough. Lift some weights. The crowd needs something to look at. And your skills seem to be lacking - you don't look like you've been in a real fight. Or even in a bar brawl.}
{160}{}{Well, you seem to be quite an experienced fighter. But you lack the musculature. Our fighters will knock you down in the first round, which means the viewers won't get a kick out of the show.}
{161}{}{You might look ripped, that is true. But you don't look like a very experienced fighter. I suggest getting some tips for hand-to-hand combat. We've got a coach for that.}
{162}{}{Alright, got it. Thank you.}

#Pizza delivery
{170}{}{[His face immediately changes as he sees the pizza in your hands] Gecko bite me! Where the fuck have you been, courier!? Get this shit outta here. I'll be talking to your boss personally to make sure they throw you right the fuck out! Phillips' Cafe has never let me down like this before. EVER!}
{171}{}{[Leave]}
{172}{}{[His face immediately changes as he sees the pizza in your hands] Gecko bite me! How did you end up like this, fighter? I won't even talk about why, after all your fame in the ring, you took a job at a pizza delivery service, but being late for such a simple delivery? Phillips Cafe has never let me down before. You can return the pizza, I'll personally talk to your boss. Get out of my sight!}
{173}{}{[Seeing the pizza in your hands, he makes a short gesture with his hand, indicating for you to wait] Hold on, courier.}
{174}{}{[Wait]}
{175}{}{[You're waiting, while the administrator goes through his ledgers]}
{176}{}{Ahem...}
{177}{}{[Wait a little longer]}
{178}{}{[You wait longer as the administrator talks to someone about the weather and the latest bets]}
{179}{}{[Ignores your attempt to get his attention]}
{180}{}{Excuse me, sir, your pizza...}
{181}{}{[Keep waiting]}
{182}{}{Wait, courier! I said wait!}
{183}{}{Here's what, you pay, or you'll be left without your pizza.}
{184}{}{No problem, sir. I'll wait.}
{185}{}{[After a few more minutes, when you've been pushed into a corner by a crowd of onlookers, the administrator talks to you] How much?}
{186}{}{What are you mumbling there? Wait! I said wait!}
{187}{}{Either you pay for the pizza or I leave.}
{188}{}{$, sir.}
{189}{}{[Widens his eyes] Where did Phillips began hiring such rude assholes!? Just remember, this isn't the last you heard from me! Now give me that pizza, here's your pathetic pay. Take it and get the hell out of here.}
{190}{}{There isn't enough here.}
{191}{}{Thank you, sir, but I need another 10$ for the delivery.}
{192}{}{You didn't earn it! Your delivery is shit! Now get the hell out!}
{193}{}{I thought you were a man of honor. After all, I did my part - brought the pizza on time and waited for you in this crowd. Maybe you should think about it.}
{194}{}{[Leave]}
{195}{}{Hmm... Perhaps I was mistaken about you and Phillips hired you for a reason. Alright, here's your tip. Now get out of here.}
{196}{}{Thank you, sir.}
{197}{}{[Critically looks the pizza over before counting out the money]}
{198}{}{You didn't ear it! Your delivery is shit. While you were standing around, you managed to ruin it's look. Look: the box is crumpled, the topping is a jumble. You need to be more careful next time. Now get outta here!}
{199}{}{Don't waste my time with that crap! Get out.}

#Fight on the ring:
{200}{}{FIGHT!}
{201}{}{You won! That was awesome!}

{202}{}{I'LL BITE YOUR EARS OFF!!!}
{203}{}{BANZAI!!!}
{204}{}{AGHRRR!!!}
{205}{}{TIME TO END YOU!!!}
{206}{}{UHRR!!!}
{207}{}{BEG FOR MERCY!!!}
{208}{}{THERE CAN BE ONLY ONE!!!}
{209}{}{YOU'RE DEAD!!!}
{210}{}{I AM DEATH!!!}
{211}{}{MEDIOCRE!!!}
{212}{}{TREMBLE, YOU SLIME!!!}
{213}{}{I'M GONNA WEAR YOUR TEETH AS A NECKLACE!!!}
{214}{}{I'LL MAKE A TALISMAN OUT OF YOUR BONES!!!}
{215}{}{YOU'RE NOTHING!!!}
{216}{}{I WILL BURY YOU!!!}
{217}{}{GET YOUR ASS OVER HERE!!!}
{218}{}{ANOTHER MILKSOP!!!}
{219}{}{EAT THIS, DREKHEAD!!!}
{220}{}{ROTBAG! ROTBAG!!!}
{221}{}{I'LL KILL EVERYONE!!!}
{222}{}{I'LL BURY YOU INTO CONCRETE!!!}
{223}{}{NOW THE REAL FUN BEGINS!!!}
{224}{}{DRY YOUR PANTS, WIMP!!!}
{225}{}{NO PANIC!!!}
{226}{}{I'LL BEAT THE SHIT OUT OF YOU!!!}
{227}{}{KAMIKAZA-AH!!!}
{228}{}{A-A-ARGH!!!}

{250}{}{You won!}
{251}{}{You won! It was a good fight!}
{252}{}{You defeated a fearsome opponent! That was amazing!}
{253}{}{You defeated a fearsome opponent! That was amazing! Your fans are ecstatic!}

#Female version:
{1118}{}{So, are you ready to fight?}
{1132}{}{Are you ready to fight?!}
{1134}{}{No, not yet.}
{1137}{}{Here you are! And here's your prize... [He hands over the winnings] Once you're ready for the next fight, just talk to me.}
{1140}{}{Yeah, I'm ready to fight.}
{1141}{}{No, just watching the slaves.}
{1142}{}{Err, no, we're not ready yet. Come back tomorrow, okay?}
{1144}{}{What determination! You may have noticed that we are increasing the pressure, gradually raising the stakes. But SOMETHING just showed up recently, and it has challenged you. I'm sure you're going to love it. Go!}
{1146}{}{Bloody amazing! How didn't you tear his hand out with that hold? We get a pretty payout for fights like these, the audience is just ecstatic! Anyway, here's your reward [He hands you the cash]}
{1147}{}{The crowd was just crazy about that fight! That's what I call determination! Here's the coin, champion! [He hands you the cash] But... Now for the bad news.}
{1151}{}{That's why, sister, we can't keep making money on your victories. The crowd isn't losing their bets, which is how we're meant to make a profit. So, this was your last fight here. You have leave the ring... Keep in mind, Reno has a huge ring as well, maybe you should try your luck there.}
