{100}{}{You see a tired strong man.}
{101}{}{You see a man who can no longer stand on his feet due to grueling workouts.}

#Ñ'àð'îâàÿ âå'êà 
{110}{}{[You see a weary man, he breathes heavily]}
{111}{}{Hello!}

{112}{}{Hey, what's wrong with you? Did you break down in the ring?}
{113}{}{Listen, friend, don't you know how to, uh, sort of "prepare" for battle without training? Well, you know, with amphetamines, for example.}
{114}{}{[Leave him]}

#Ïðî 'ðåíèðîâêè
{115}{}{Coach is a real monster, he had me completely bent out of shape. He says my stamina sucks!}
{116}{}{Well, you don't look like a nerd. Look at those biceps!}
{117}{}{I also thought that getting buffed was all I needed! And you know what? Two years of training and no goddamn victories!}
{118}{}{Uh... Not even one?!}
{119}{}{The first round in the ring is usually mine, but then I'm just exhausted.}
{120}{}{Oh, so that's what it is.}

{121}{}{And this coach, he's a beast! He tries to pump up my stamina. So after training I'm always like this - lying on the mattress, unable to move.}
{122}{}{How about amphetamines? Psycho, for example. It could help.}
{123}{}{Let me give you a massage! You'll feel better, you'll see.}
{124}{}{Okay. Well, I'll leave you be.}

#Ìàññàæ
{125}{}{A massage from a dude? No way! Hands off!}
{126}{}{Oh, come on! I'm just asking...}
{127}{}{[Smiling] Wow! A beauty woman wants to rub me? Come on, baby! Finally!}
{128}{}{Great! Turn around, champion!}
{129}{}{Uh... No. I'll go get... Uh... The ointment first, Yes. Look, just wait.}
{130}{}{Nah! You'll torture me worse than coach with your hands!}
{131}{}{As you wish.}
{132}{}{Oh! What a thrill!!}
{133}{}{You massaged the fighter for an hour. The client is definitely happy.}

#Ïðî äóðü
{134}{}{You know, I've tried this stuff. The coach rightly says it's better to push harder in training than die of an overdose.}
{135}{}{Die?}
{136}{}{Ha! What did you expect?! Get a little dope and the ring is yours? You know how many of our lads went off from this stuff?}
{137}{}{How?}
{138}{}{The heart! It just can't take it if you overdo it in the ring or in training. This stuff is garbage, don't even think about it.}
{139}{}{And yet you know where to get some, right?}
{140}{}{Fine.}

{141}{}{I don't! Get off me, you damn junkie! Fuck off! [the eyes of the fighter sparkle with fury, looks like he really doesn't like this conversation]}
{142}{}{You do know! Tell me!}
{143}{}{Okay, pal. Relax.}

{144}{}{I'll tell you, just because I see that you're one of us.}
{145}{}{Come on, I won't tell anyone. Be sure about it.}
{146}{}{There is a large laboratory somewhere outside the city. The Black Caravan, as we call it, goes there every two days. Comes quietly to the parking lot behind the office and pushes drugs. That's how the stuff gets to the city. I used to deal with them, but then I stopped using. So, maybe they already moved to another place, I have no idea.}
{147}{}{Okay, thanks for telling me. This is just what I needed.}

{148}{}{Thanks in any other form would be nicer. He-he.}
{149}{}{Oh yeah, here's 50 bucks for the info.}
{150}{}{Take a beer, relax a little.}
{151}{}{Hmm. Well, here's a bottle of cola for refreshment.}
{152}{}{Sorry, I have nothing, I'll bring some later.}

#Ïðî ðàñïèñêó íà ïîäëîã âûðîäêîâ
{153}{}{Um, listen, why do you think the slavers tried to frame the freaks?}
{154}{}{What?}
{155}{}{You see, the chief of Slavertown hired someone to plant drugs on the freaks.}
{156}{}{Oh, yeah, that's obvious.}
{157}{}{Really?}
{158}{}{You bet it is! Don't you understand? The chief wants a percentage of the income from Hoover Dam. And the dam is in need of workers. I don't know exactly what the deal is, but I think the chief tried to sell his slaves to the dam. Bob Neil, obviously, doesn't like that, and went looking for alternatives. So, chief must've decided that the freaks should be dealt with, so the dam owner had no other choice than to accept slaves for workers. Otherwise, no money for him.}
{159}{}{Where do they get the dope? Do you know anything about it?}
{160}{}{Hmm. An interesting thought. I'll take note of that.}

{161}{}{Ah, so that's what it's about! Why didn't you say that first. Why start with Bob Neil anyway?}
{162}{}{No reason... Well, to hell with them. So, how about amphetamines?}
