{100}{}{You see a greeter.}
{101}{}{This is the greeter of the slave ring and its part-time bartender.}

{110}{}{Come in. The ring is in that hall over there.}
{111}{}{Give me something to drink.}
{112}{}{Okay.}
{113}{}{That’s enough. If you're going to throw up, go outside. Got it?}
{114}{}{I need more drink.}
{115}{}{Okay.}

{116}{}{Have you heard about the slavers?}
{117}{}{Yes. I can't imagine who would do something like that. But I'm more worried about what happens to the ring now. I suppose the owner will continue business, but without any slaves among fighters. Only free people. Which is not bad, honestly speaking.}