{100}{}{You see Big Louie!}
{101}{}{Holy crap! It's Big Louie! He actually found stardom in Vegas!}

#Ответные реплики для Ж и М
{102}{}{Hey, look who it is! Let's have a round of applause for my old friend! Without him, I wouldn't be here!}
{103}{}{We accomplished a lot together, but he has no time to tell you the details... No time, I said!}
{104}{}{Hey, look who it is! Let's have a round of applause for my old friend! Without her, I wouldn't be here!}
{105}{}{We accomplished a lot together, but she has no time to tell you the details... No time, I said!}

{106}{}{I'm happy to see you, but I'm about to go onstage. We'll talk later.}
{107}{}{The show just ended! Give me a minute.}

#Диалог
{110}{}{Hey, brother. It's good to see you! We're a long way from that Indian camp, aren't we?}
{111}{}{Big Louie! You seem to be doing well.}
{112}{}{I'm terrific! At first I almost regretted leaving that Cheyenne canyon. I was feared and respected there. But here, the elites... Accepted me. For the first time I feel *needed*... I never thought I'd achieve this. And I owe it all to you. Speaking of which, you look a little rough... }
{113}{}{I've been busy. Sometimes it feels like everyone I talk to has another job for me. Anyway, can we chat?}
{114}{}{I'll always have time for you... When I'm not on stage, that is.}
{115}{}{I have to go. We'll talk later.}
{116}{}{It was good to see you. I enjoyed this.}
{117}{}{Good luck to you.}

{118}{}{Bad news. Everyone in your gang is dead.}
{119}{}{I was wondering why they've been so quiet... Well, no turning back now. Don't worry, I'm not upset. I had no love for those dogs.}
{120}{}{Ripper is getting out of hand. What do we do, boss?}
{121}{}{The Ripper? When I was in charge, he was useful... On his place. But he can't lead them. Don't worry, they'll tear themselves apart if he tries.}
{122}{}{He wants to take your place. He says you went soft, and... }
{123}{}{Let's talk about something else.}
{124}{}{Hmm. We'll leave it at that, then.}

{125}{}{Soft? ME?! I was feeding that whole gang when he was still sucking his mother's milk! Why, he ought to...  [he cuts himself off, then takes several deep breaths]}
{126}{}{[Let him calm down.]}
{127}{}{I won't fall back down to their level. But Ripper has to go. I'll give you 1000 dollars - buy some poison from the dealer outside the cafe, or just some ammo for your gun. I won't be going back, so it's up to you how to solve this problem. Don't worry - I know you can handle this.}
{128}{}{Okay, boss.}
{129}{}{}

{130}{}{Will you ever come back?}
{131}{}{I've thought about it. But my schedule here is filled tight for the next couple of months. If I ever go back, it won't be soon.}
{132}{}{How much money do you make off your show?}
{133}{}{A lot less than I did with the gang. You can't make a lot of money like this these days. But there are... Other benefits.}
{134}{}{When's your next show?}
{135}{}{This evening, after six. You should see it. It'll be fun!}

#########################################################################
#
#   Песни Большого Луи, версия для FoN 1.0.
#
#   Автор текстов - Александр Агафонцев (Kerb)
#	So, I changed it for metalocalypse lyrics, and maybe Weird Al's. Because relevance. Sorry.
#########################################################################

{200}{}{Do you folks like coffee?~}
{201}{}{Real coffee}
{202}{}{From the Hills}
{203}{}{Of Colombia?~}

{204}{}{Hey you! Do you have some grave dug out for you or what? Dance suckers, you're in the best bar in the wasteland - cause I'm here!}

{205}{}{~The Duncan Hills will wake you~}
{206}{}{~From a thousand deaths,}
{207}{}{~A cup of blackened blood}
{208}{}{~Dying, dying... You're dying for a cup~}

{209}{}{Hey! You, asshole to the right! Put that back! My boys would chop off your hand for that, in our gan- I mean in our jazz gan- er, jazz-band. You know... }

{210}{}{~Guatemala blend, ethiopian,}
{211}{}{French vanilla roast~}
{212}{}{Dying, dying~}
{213}{}{You're dying for a cup!}

{214}{}{Prepare for ultimate flavor! You're gonna get some now... And scream - for your cream!}

{215}{}{Duncan Hills,}
{216}{}{Duncan Hills~ }
{217}{}{Duncan... Hills...}
{218}{}{Coffee! Yeeeeeeeaah!}

{219}{}{Yeah, life's great, even with your rotten faces around... Heh, JK LOL. You're the best audience I've ever had! Let's do something completely different -}

{220}{}{~Musta-Krakish, Musta - Krakish!~}
{221}{}{The time has come, to awaken him~}
{222}{}{I call upon the ancient lords of the underworld, }
{223}{}{~To bring forth this beast and -}

{224}{}{Come on, boys and girls! We've already been through the apocalypse! So, what's left to be afraid of? Sing with me!}

{225}{}{Awaken, awaken, awaken, awaken~}
{226}{}{Take the land, that must be taken~}
{227}{}{Awaken, awaken, awaken, awaken~}
{228}{}{~Devour worlds, smite forsaken!}

{229}{}{By the way, ladies, you can invite the gents to dance! If they are still capable to... }

{230}{}{~Rise up from your thousand year old sleep,}
{231}{}{~Break forth from your grave eternallyyy~ }
{232}{}{~I command you to... }
{233}{}{~Rise! Rise! Rise! Rise!~}

{234}{}{Yeah, yeah, I did my time with all kinds of inner struggles, you know... Like any other artist!}

{235}{}{~I'm the conjurer of demons,}
{236}{}{I'm the father of your death~}
{237}{}{I bring forth the ancient evil,}
{238}{}{~I control his every breath.~}

{239}{}{Once I had a... Uh... Fellow, er... Drummer, that could butcher anyone... Like a French meringue! In cards of course! Then he met a "bigger fish"... }

{240}{}{~I instigate your misfortune...~}
{241}{}{With the birth of killing trolls!!}
{242}{}{I awaken Armageddon!}
{243}{}{~Feeding on a thousand souls~}

{244}{}{Don't forget to try today's special cocktail! Two for the price of one! Goes great together with your booze! So, where were we... Oh yeah! Next song!}

{245}{}{I wanna roll with the gangsters~}
{246}{}{~But so far they all think I'm too white and nerdy~}
{247}{}{~Think I'm just too white and nerdy, yeah I'm just too white and nerdy,}
{248}{}{You see I'm white and nerdy - Look, I'm white and nerdy!~ }

{249}{}{Yes, my dear alcoholics, junkies and lovers of cheap whores! Put out your ears - here goes real skill!}

{250}{}{First in my class here at MIT, got skills of a champion at D'n'D,}
{251}{}{M.C. Escher, that's my favorite M.C. - Keep your forty, I'll just have an Earl Grey tea,}
{252}{}{My rims never spin, to the contrary, you'll find that they're quite stationary,}
{253}{}{All of my action figures are cherry, Stephen Hawking's in my library~}

{254}{}{I'd like to thank, uh, MTV, for giving me the chance... Wait a second, what? Moving on!}

{255}{}{~Get your towels ready it's about to go down~}
{256}{}{~Everybody in the place hit the fuckin' deck~}
{257}{}{~But stay on your motherfuckin' toes~}
{258}{}{Big Louie's runnin' this - let's go!~}

{259}{}{I'd very much appreciate autotune now, T-Pain style! But it's, like, post-apocalypse, so let's proceed with what we have!}

{260}{}{I'm on a boat - I'm on a boat! On a boat - I'm on a boat!}
{261}{}{Everybody look at me cause I'm sailin' on a boat!}
{262}{}{I'm on a boat - I'm on a boat! On a boat - I'm on a boat!-}
{263}{}{Take a good hard look at the motherfuckin' boat!!}

{264}{}{So, seriously, big thanks to these guys, attending us today! We are glad you were with us and will always remember you!}

{265}{}{Johny-17, Drobovik, .Pixote., Risewild, Sagez, Matt Drax,}
{266}{}{theslitherydeee, gorlomi, Vault15, dozen, xps, Muttie,}
{267}{}{heatEXTEND, Reikis, Navarrrro, RetrospectiveGaming channel on Youtube,}
{268}{}{also, TheChosen1 and 0wing - thanks guys, for being here from the start}

{269}{}{The biggest ones come to the great and unbelievable Foxx, awesome _Pyran_ and Snikers, who all did tremendous amount of work.}

{270}{}{And, of course, big shout-out to the ideologist and heart of the translation project - Dionis.}
{271}{}{Thank you, for putting like 2 years of life and passion into it.}
{272}{}{Great thanks to all players, to nma-fallout.com forum, for every playthrough and feedback on bugs.}
{273}{}{Final cut by Keyboard Gecko. Shit, I forgot the original team! Thanks, guys! And especially you, BlackDesigner. Looking out for Fallout:Sonora. Good luck with that.}

# Неиспользованный текст:

{274}{}{Твою бы мамашу, гиену брюхатую,}
{275}{}{Им бы отделать, чтоб кровью раскрасить}
{276}{}{Убогие кухню и детскую наши, где череп ее,}
{277}{}{Вместо вазы ночной, я надеюсь поставить}

{278}{}{И жаль, что папаша твой мною разрезан}
{279}{}{Кусков так на двадцать - еще б раз увидеть! -}
{280}{}{Уж год как назад и растащен шакалами,}
{281}{}{Ржавеет без крови мой "Потрошитель"... }

{282}{}{Еще твой кузен с феминисткой-женою... }
{283}{}{Вопрос о них больше пред мной не стоит... }
{284}{}{Ах, как же красиво рвало их на части!}
{285}{}{Хвала тебе, Нобель, за твой динамит!}

{286}{}{Все меньше родни у тебя и все крепче}
{287}{}{Люблю я тебя, жизнь легка и проста!}
{288}{}{Запомни, приятель, чтоб так не возиться,}
{289}{}{Сперва убедись, что она - сирота!}

#Жен реплики
{1110}{}{Hey, sister. It's good to see you! We're a long way from that Indian camp, aren't we?}
