{100}{}{You see a merchant.}
{101}{}{You see a street peddler. With her rustic look and worn out clothes she stands out among the rest of the environment.}
{102}{}{If you are here to molest me, I'll call the police!}
{103}{}{Please, don't come near me! I don't want problems with the police!}

{110}{}{[At the sight of you approaching, a street peddler makes an effort to force a smile upon her tired tanned face] Come here! Sandwiches, hot, delicious!}
{111}{}{How much is for one sandwich?}

{112}{}{$35. I only accept cash.}
{113}{}{Here is the money. Give me one.}
{114}{}{Uh, another time. Bye.}
{115}{}{Good bye.}

{116}{}{Well, that's great, but can we just chat?}
{117}{}{Would you like a sandwich? The price has not changed: $35.}

{118}{}{[Craftily assembles you a fresh sandwich] Here you go. Want more?}
{119}{}{Yes, please.}
{120}{}{But this is not enough... Look, this job is already too exhausting to give away food for free.}
{121}{}{I understand...}
{122}{}{I see. Now give me one sandwich.}

#Chatter
{150}{}{[Her look becomes especially tired] To chat... About what?}
{151}{}{On second thoughts, give me your brand sandwich. Here's $35.}
{152}{}{I'll chat with you later. Now I gotta go.}

{153}{}{You seem very tired. Must be trading for quite some time?}
{154}{}{Yes... I'm not slacking here, I'm working. I have to work for 12 hours a day just to pay for the right to trade.}
{155}{}{The right to trade... Wait, what's this?}
{156}{}{That's how it is. The Clean City takes a toll for the right to sell goods here. It's quite large... No, the truth is, it's a real robbery. But I have little choice.}
{157}{}{Why so?}
{158}{}{In the Clean City one does not have to worry about security, the order is maintained by the police. In addition, there are more people and they are richer, hence more income. But it is not even that. My father made a deal with the City Hall in order to restore the farm. And now we have to pay our part of the deal. We have to endure inhuman conditions.}

{159}{}{The deal? Tell me more. And what do these "inhuman conditions" imply?}
{160}{}{Well... [sighs] My father owned a farm, but after he went broke he appealed to the City Hall for help. He was given a loan with the condition of repayment with interest. The interest rate is just awful! And it increases with each day of the payment delay. But those chair warmers in the City Hall couldn't be more happy about it because, as one can say, now they own both: us and the farm.}

{161}{}{What an unfair matter. Maybe someone in the City Hall would give you a pass? A grace period, for example.}
{162}{}{It's unlikely. Do you know someone there? If you knew, you would understand. Those jokers haven't crawled outside of the City for like a dozen of years. They don't know how hard it is to live in the wastelands. That's besides the fact that they don't care. They are already used to push people around.}
{163}{}{What happened to the farm?}
{164}{}{At first, we were raided by the rodents, then the actual raiders came, and then the hurricane happened. The barn was blown to pieces, not to mention the crops. We barely could collect a bag of maize back then. Now we need to restore everything, the buildings and the plantation.}
{165}{}{How trading here will help you with the harvest there?}
{166}{}{We have a big and strong family. While men are busy working in the wastelands, I'm sent here to trade. We need urban goods. Sometimes it is possible to make a deal with the prospectors, but they are not quite pleasant people. They may cheat you.}

{167}{}{Let's chat a bit more?}
{168}{}{}
{169}{}{Tell me the story of your family.}
{170}{}{Well, we have a big family, live on a farm outside the city. Over the last ten years we were engaged in farming. What else is there to tell?}
{171}{}{The last ten years? But what was before that?}
{172}{}{We roamed for three or four years. We came from the South. The life there was hard, so we had to leave our homes. When we got to Vegas, the place was a real hole. Nothing remarkable - no electricity, no casino. But in ten years the city has greatly changed.}
{173}{}{Wait, how all this splendor could have been built in such a short time?}
{174}{}{With slave labour, of course. The slaves were brought here in big crowds, so they could restore the city. What a heavy work they had. But look at the result!}

{175}{}{Why do you accept only money?}
{176}{}{I need to pay for the loan, so I have to convert the food into money. They won't take the payment with sandwiches in the City Hall, right?.}

#Cart
{180}{}{What a fancy cart you have.}
{181}{}{Yep. Previously, such carts were used by the merchants selling hot dogs, and now it's my turn. My brothers found it among the ruins of the old city, repaired it and repainted. Quite a handy thing, if only not this damn wheel...}
{182}{}{Yeah, I have noticed that the cart isn't standing evenly. Maybe I can fix it?}
{183}{}{Well, you can try. If it's fixed, I'll give you a sandwich. Just don't break it completely!}
{184}{}{I'll try.}

{185}{}{Now the cart is all right.}
{186}{}{Indeed! Thank you very much. Here, take it, very hot, fresh-made.}
{187}{}{You're welcome.}

{188}{}{Let's talk about something else.}

#Main quest
{190}{}{I managed to get a reprieve for your loan.}
{191}{}{Really!? What a surprise... We needed this reprieve so bad! But I don't know how to thank you. Except, maybe I can make you a free sandwich.}
{192}{}{You don't need to worry. As about the sandwich - I'll take it.}
