{100}{}{You see Gareth.}
{101}{}{You see a seemingly ordinary passer-by.}
{102}{}{*running script error*}

{110}{}{Uh... Hello, wanderer. And... Have a good day.}
{111}{}{Wait, what are you doing here?}
{112}{}{Whatever.}

{113}{}{Uh... [looks closely at your face] You look like one of these [pointing in the direction of the slavers office]. So, sorry, but I will be on my way.}
{114}{}{Do I really look that bad...}

{115}{}{Uh... [looks closely at your face] Are you one of these [pointing in the direction of the slavers office]? What are *you* doing here?}
{116}{}{I asked first.}
{117}{}{I'm just passing by, minding my own business.}
{118}{}{I'm looking for a fresh slave.}
{119}{}{Nothing that would justify a conversation with you.}

{120}{}{Then I guess we have nothing to talk about.}
{121}{}{Uh...}
{122}{}{See, you have no confidence in me. That means I should refrain from talking with you.}
{123}{}{So you are not one of them? Phew, at least someone in this city is "just a passerby", and not a member of some nefarious organization.}
{124}{}{And you are a member of which organization?}
{125}{}{Yeah. Well, it was nice to talk to you.}

{126}{}{The member of the secret sect of Avengers... Just joking. Heh-heh.}
{127}{}{Wow, can I join your sect?}
{128}{}{Damn, you're taking me for a moron?}
{129}{}{He-he. Bye, damn joker.}

{130}{}{Well, you can't join without testing. We are literally two people. It is unlikely that you will want to be a part of it. The risks and stuff...}
{131}{}{Hey, don't get mad, I didn't do anything wrong!}
{132}{}{You've already popped up, so you'd better tell me what you're up to.}
{133}{}{I think you are in trouble. Tell me, maybe I could help.}
{134}{}{So, I'll believe you... This time. Bye.}

{135}{}{Oh, okay. Anyway, I can't do this alone.}
{136}{}{So what's your problem?}

{137}{}{The problem isn't mine, it's my brother's. Damn slavers grabbed him when he returned to the city and locked him in the corral. I want to rescue him, but it's not easy.}
{138}{}{Do you have a plan?}
{139}{}{I have a plan, yes, but first I need to contact Eric. However, one can penetrate the corral only as a slave. And it means being branded for life.}
{140}{}{How do you know he's there?}
{141}{}{This is an option, isn't it? You will become a slave, and I will redeem you.}
{142}{}{I can bring the note to your brother.}
{143}{}{Uh, today it won't be my headache, take care.}
{144}{}{One friend saw him and said that he is here. And then I found the gap in the fence and saw him among the slaves.}
{145}{}{Not an option. First, there is no guarantee that you will have time to redeem me before the others do, and second, I don't want to walk with the mark on the forehead for the rest of my life.}

{146}{}{Are you going to get in there?! Why!? Once you are there, you won't come back without a mark on the forehead!}
{147}{}{Don't worry about me, I know what to do.}
{148}{}{Well, it's up to you...}
{149}{}{I'll do it if you pay me.}
{150}{}{Right, it's too silly. Risk yourself, and I'm leaving.}

{151}{}{Oh, it's you. Hello.}
{152}{}{So what was that about the problems with your brother?}
{153}{}{Yeah, it's me, relax.}

{154}{}{Damn, that would be great. You just need to pass a note to Eric.}
{155}{}{Just a note, I'll do it.}
{156}{}{I changed my mind, sorry.}

{157}{}{Hey, wait. I can pay 200 bucks if you can do it. Would have paid more if I had more... But, of course, I'm not paying immediately, so there would be motivation for you not to cheat. You just need to pass a note to Eric, nothing more.}
{158}{}{Give me a note, I'll do it.}
{159}{}{Still am not doing it.}

{160}{}{Sure, I'll pay, but after Eric receives a note. However, I only have 200 bucks. Would pay more if I was richer...}
{161}{}{Give me a note, I'll do it.}
{162}{}{I changed my mind, sorry.}

{163}{}{Here. I'm *really* counting on you! Please, everything depends on you! If this note gets into the hands of traffickers - all would be lost.}
{164}{}{Okay, I'll think about it.}

#After getting the quest on passing the note
{200}{}{Well, how is it going, wanderer?}
{201}{}{I have some bad news - Eric is dead.}
{202}{}{Relax, Eric has got your note.}
{203}{}{I'm still working on it.}

{204}{}{What?! What the hell! You could have mistook him or... Or you are lying even... Or... I don't know what, but I don't believe you!.. Ugh, why I even got involved with you?! Get away from me!}
{205}{}{Oh, that's how you choose to act!}
{206}{}{Oh, good! Now it's easier for me to cope with them...}
{207}{}{And my reward?}
{208}{}{What? Ah, yes. But wait, how do I know you're not tricking me? No, first I'll check.}
{209}{}{WHAT?!}
{210}{}{It's very simple. We will wait for the evening and you'll see.}
{211}{}{Okay, let's wait.}
{212}{}{Hell no! Pay me now!}
{213}{}{Then I'll be back later.}
{214}{}{I have no money right now. You'll have to wait.}
{215}{}{I have an idea. You see, the bartender at the ring said that they want to take Eric to the ring. I managed to overhear the talks of the slavers, so now.}
{216}{}{Great! I think you will not be bored.}
{217}{}{Will see.}

{218}{}{The slaves are now free, nothing is keeping them.}
{219}{}{Wonderful news! And I just been thinking about what is that suspicious movement that is happening in the corral. Thank you, wanderer! Here, take 200 bucks for the risk. That's all I have.}
{220}{}{Of course, take care!}

{221}{}{Thanks for the help, wanderer. I was glad to meet such a wonderful person. Here [hands 200 bucks] - all I can give for your help.}
{222}{}{Wait, how did you know that Eric will be took to the ring?}
{223}{}{First learned from the bartender, I know him. And then overheard the talks on the radio channel of the slavers. By the way, here, take it, I don't need it anymore. Maybe you'll find a use for it.}
{224}{}{Thanks. Well, take care.}
{225}{}{It all was in vain... [grabs his head]}
