{100}{}{You see administrator Aidan.}
{101}{}{You see an administrator of the Slavertown.}
{102}{}{*running script error*}
{103}{}{Great. Let's separate on these terms.}

#Starting dialogue branch
{200}{}{Ah, fresh blood! Come, don't be afraid. This is the slaver's guild, and my name is Aidan. Are you here to discuss a business matter? Better be the case.}
{201}{}{I want to buy half a hundred of strong, healthy slaves.}
{202}{}{I want to buy half a hundred of strong, healthy slaves. Why - is none of your business.}
{203}{}{You obviously are involved in dirty affairs. Therefore, you will all die. Now!}
{204}{}{I know you're involved in the local drug business! And you will show me, where the production site is located.}
{205}{}{I need a slave. It will work as a driver on a train.}
{206}{}{Uh... No. Bye.}

#Response on 203 
{207}{}{Wow! Wow! What a belligerence! So what, will you dare, huh? Ha-ha! Come on, try it! I'm all yours!}
{208}{}{Great! Take that, scum!}
{209}{}{Damn, there's too much of your kind. I'd rather waylay you trapping somewhere around the corner.}

#Response on 204
{210}{}{What, the thing is real? Ha! If you find out anything, show *me*! I'll be the first tester of their drugs, ha-ha!}
{211}{}{You're lying! Answer me, you son of a bitch! Where is the lab?!}
{212}{}{Oh, well, if you don't know, then I'm sorry.}
{213}{}{Hey, lads! There's one prick puts an act on!}
{214}{}{Look at how I'm going to defend myself!}
{215}{}{All right, man, I'll leave you alone, chill out.}

#Response on 205
{216}{}{There is one. A sensible slave - knows how to handle various equipment, won't run away, will work hard. Right for your purposes. As to the price, I'll sell him for $3000.}
{217}{}{Consider me convinced. Here is the money. Send the slave to Salt Lake City, have him meet me at the hotel "the Sixth bullet".}
{218}{}{I'll refrain.}
{219}{}{Out of your mind? For such money I can buy a dozen of slaves for myself. Drop it to $2000.}
{220}{}{Not every day the product like that makes its way into the corral. Therefore I'm not going to reduce the price.}
{221}{}{Then, you lose a customer. I'm leaving.}
{222}{}{Not every day the product like that makes its way into the corral... However, there wasn't a buyer for it for a while. Maybe I indeed ask too high a price for it. Okay, I'll drop the price to $2000.}
{223}{}{A reasonable solution. Here is the money. Send the slave to Salt Lake City, have him meet me at the hotel "the Sixth bullet".}
{224}{}{You have found a driver for the train. You can now return to Salt Lake and continue your mission.}

#Response on 202
{237}{}{Good, I won't ask anything. The boss will, because I'm  not in charge of such big deals. Go to him, it's there, on the left down the hall.}
{238}{}{Okay, I'll look for him.}

#Cowboy
{240}{}{I want to sell a strong fighting slave. He now stands by the car, naked and defenseless.}
{241}{}{Fine. We always need good slaves, especially fighters. Their usual purchase price is $500.}
{242}{}{I like the price. You can pick him up. Oh, and... Maybe he will resist. 'Cause, you know, he is a fighting slave after all.}
{243}{}{How much? No, I'll try to find another use for him.}
{244}{}{And this one looks decent. The body is in excellent condition, have enough power to fight and not once. Good product. Here is the payment.}
{245}{}{Finally, at least some use of him...}

#Eric the slave
{250}{}{I'm looking for a certain slave named Eric.}
{251}{}{Let's see... Yes, there is such. A slave from the middle class of laborers. Those can be used to carry weights or can be send to fight in the ring.}
{252}{}{How much for him?}
{253}{}{The slaves of this class are worth 500 bucks.}
{254}{}{Okay, I'll buy him.}
{255}{}{That's too much!}
{256}{}{Thanks, I don't need it.}
{257}{}{The slaves are expensive. If only the clients knew, how much of the hard work was invested in catching and training them...}
{258}{}{I'll come back when I have enough money.}
{259}{}{Hey there! Item number A12-86. Come on, customer's waiting!..}
{260}{}{I'll wait.}

{261}{}{I can sell information about the impending escape attempt.}
{262}{}{Very interesting. And what moron decided to look for his death in our corral?}
{263}{}{Well, he isn't going to look for it in there. So, are you going to buy the information?}
{264}{}{I think yes. But the information first!}
{265}{}{Okay. Here is a note from someone named Gareth to one of the slaves.}
{266}{}{No, money up front!}
{267}{}{There will be no information, I changed my mind.}
{268}{}{I'm not a dealer, talk or walk.}
{269}{}{[Reads the note] Naive fool. So where is this Gareth?}
{270}{}{At the Eastern wall of the corral.}
{271}{}{That's it!?}
{272}{}{No man, no problem.}
{273}{}{Okay, here's 300 bucks and a gratitude on behalf of the company. Don't ask me for more.}
{274}{}{Ha, so much money for a side job...}

#Collars
{278}{}{Four.}
{279}{}{Seems like I can sell some more.}
{280}{}{I can sell slave collars.}
{281}{}{Still interested in slave collars?}
{282}{}{Oh, this accessory is very much appreciated among the slave owners. A very useful thing! I'll buy for 100 bucks each.}
{283}{}{I'm counting at 125.}
{284}{}{Okay, that's fine by me.}
{285}{}{I don't think I will accept that price. I'll come back if I change my mind.}

{286}{}{How much you say?! Not many slaves worth more than your price! I was already too generous today.}
{287}{}{All right, I'll sell for a hundred.}
{288}{}{Well, if you think about it, these collars is nothing to sneeze at. Okay, I agree to such a price.}
{289}{}{Great, that's fine by me.}
{290}{}{However, they might still be useful for me. I'll come back if I change my mind.}

{291}{}{How many collars are going to sell?}
{292}{}{One.}
{293}{}{Two.}
{294}{}{Three.}
{295}{}{Five.}
{296}{}{All I have (}
{297}{}{ items).}
{298}{}{None. I changed my mind.}

{299}{}{A good product!}

#Women's replics
{1207}{}{Wow! Wow! What a belligerence! So what, will you dare, huh? Ha-ha! Come on, try it! I'm all yours!}
{1213}{}{Hey, lads! There's one bitch puts an act on!}
{1267}{}{There will be no information, I changed my mind.}
{1298}{}{None. I changed my mind.}
