{100}{}{You see a slave.}
{101}{}{You see a slave. He is pathetic.}
{102}{}{This one has nothing to say to you.}
{103}{}{::looks at you with a blank stare::}
{104}{}{You managed to persuade the slave to leave the corral.}

#Dialogue before slaves escape from the corral
{110}{}{I want to lie down. Don't bother me.}
{111}{}{No time to lie around, you louts! The slavers are dead. You are free!}
{112}{}{Okay.}

{113}{}{Uh... Yeah, uh, good news, yes.}
{114}{}{That's news! Hey, did everyone hear that?!! Come on, guys! We are free... }
{115}{}{Hurry up!}
{116}{}{Get your asses moving, herd!}
{117}{}{And why are you so sad?}

{118}{}{Oh, you dimwit! Do you even realize, what have you done!? [grabs his head]}
{119}{}{Hey, what's the problem?! You need to get out quickly and go home!}

#Dialogue with those slaves who remained in the corral and don't want to leave
{120}{}{To go where? I have no home! Thanks, of course, you did quite a service, but they could give me work with food and water, and now I have to find them myself... You're a moron if you think that you made it better!}
{121}{}{Hmm. What an unexpected reaction. At least the majority is satisfied...}
{122}{}{[The slave looks around in bewilderment]}
{123}{}{Hey! Why are you not running? The exit from the corral is opened! You need to get out quickly and go home!}
{124}{}{Hey! Hurry up! Come on!}
{125}{}{So this is... They all are...}
{126}{}{Get up, you fool! Now! No time to lose! Forward! Go!!!}

###################################################
#
# FLOATING PHRASES
# Author: Aleksandr Agafontsev
#
###################################################

{150}{}{In this corral you eventually understand, what brahmin feels in the slaughterhouse}
{151}{}{Why did I bet on zero?}
{152}{}{Another day in this hell hole...}
{153}{}{Mama used to tell me - don't play in games of chance}
{154}{}{Let me go to casino! Only one bet, and back!}
{155}{}{And they said that the real life is in Vegas...}
{156}{}{Let me out!}
{157}{}{That's the violation of human rights! I will complain!}
{158}{}{It was cleaner even in the raiders crib...}
{159}{}{And once I had a couple of slaves myself...}
{160}{}{Freedom! Freedom!!!}
{161}{}{A bottle of beer and a cigar - and they can shoot me, for all I care...}
{162}{}{Free us!}
{163}{}{We're not animals! At least I'm...}
{164}{}{He had marked cards! I should have won!}
{165}{}{We live in a country of freedom! Let me out!}
{166}{}{I can't be here any more!}
{167}{}{Even my wife didn't feed me that bad!}
{168}{}{I require a normal toilet!}
{169}{}{Ahhh! ::bangs his head against the ground::}
{170}{}{How was it... "You will die anyway"?}

#Women's replics
{1118}{}{Oh, you dimwit! Do you even realize, what have you done!? [grabs his head]}
{1120}{}{To go where? I have no home! Thanks, of course, you did quite a service, but they could give me work with food and water, and now I have to find them myself... You're a moron if you think that you made it better!}
