{100}{}{You see a smoker.}
{101}{}{It's just a smoker. He tries to relax and just ignores everything.}

{102}{}{[Slaver is not even looking at you, he just ignores everything]}
{103}{}{Hey, you! Tell me where the lab is! I know that you guys are somehow connected to it!}
{104}{}{[Leave the smoker in his oblivion]}

{105}{}{Holy shit... Even I don't push people that hard!}
{106}{}{Speak, you son of a bitch!}
{107}{}{You're useless. I'd better go.}

{108}{}{Why are you so raged? You see I'm stoned? I'm good. So back the hell off.}
{109}{}{If you don't answer now, I'll paint all your face with bruises!}

{110}{}{Oh, screw you!}
{111}{}{[Grab him by the collar] That's it, bitch, you pissed me!}
{112}{}{Okay, I'll stop.}

{113}{}{Hey! Take it easy!..}
{114}{}{I'll *beat* the information out of you with these hands! Better tell me!}
{115}{}{Well, I'm sorry, I overreacted.}

{116}{}{Damn, where the hell such an ass even came from, huh?! I don't know of any labs!}
{117}{}{Lie!!! Here's a receipt concerning the freaks! What the fuck is going on here? Speak!}

{118}{}{Well... Damn! Some weasel from the City Hall appeared! He wanted to kick the freaks out of the city! So we hired a boy, he planted the drugs on them, I don't know anything else! I swear!}
{119}{}{Who was that weasel?!}

{120}{}{Hell knows! It was dark there! The huddle took place in the country at night...}
{121}{}{Then who was hired for the set up?}

{122}{}{Just some boy. He's already... Done...}
{123}{}{"Done" what?!}

{124}{}{He'd been taken care of, blockhead! So will be you if you keep looking for trouble!}
{125}{}{[Slap the bastard on the nape] Me, you say? Huh?!}

{126}{}{Oh, uh, asshole, my bros are in touch, so stop it, you!}
{127}{}{Your bros won't hear you here!}

{128}{}{[Tries to escape] Oh, you... The hell you need!? What do you want from me?! I'm a simple slaver!}
{129}{}{Laboratory! Where is it?! Answer me, scum!}

{130}{}{NO! Idiot! They will kill both of us, don't you understand?!}
{131}{}{I'm tired of this! [kick him in the groin with the knee]}

{132}{}{Arrrghh...}
{133}{}{[Punch in the face]}

{134}{}{Aahh!..}
{135}{}{Not enough, little bitch?! Want more?!}

{136}{}{Oh... I just went out to smoke... And now this... Damn it!}
{137}{}{[Hit him in the teeth with an elbow]}

{138}{}{TPhh... Son of a BITCH!!! MY BROS GONNA...}
{139}{}{What, still hasn't changed your mind, eh?!}

{140}{}{Lay off me, pig!..}
{141}{}{[Hit him again]}

{142}{}{Mmm... Sweet pain...}
{143}{}{Liked it? One more time then, huh?}

{144}{}{NO! Enough! I'll tell you!}
{145}{}{Go on!}

{146}{}{It's... It's outside the city... Hell, the place is a fortress! You will be shot on sight!}
{147}{}{How to get there?}

{148}{}{To the South, by the highway... When you get out of the city, I'll show you...}
{149}{}{Show me on the map!}
{150}{}{Take me there!}
{151}{}{How one can get in there unnoticed?}

{152}{}{There is a caravan... Called "Black Caravan"... They are carrying drugs for us...}
{153}{}{Where are they?}

{154}{}{In the parking lot of the caravans, next to the office... They migrate back and forth every two days...}
{155}{}{Great! So I will be able to follow them.}

{156}{}{What, learned all you wanted, bro?! Will you let me go already, huh?!}
{157}{}{Listen, sucker! If you ever tell...}

{158}{}{No need for threats, yo! I know what would happen! I know! My own people would kill me!..}
{159}{}{Excellent... [let him go]}
{160}{}{Excellent... [stab in the heart with a knife]}
{161}{}{Threats didn't work out. Apparently, you weren't considered a worthy opponent.}

#Different questions
{200}{}{Who are you?}
{201}{}{What is this place?}
{202}{}{Do you know who the freaks are?}
{203}{}{[The smoker produces a smoke ring] One of those devilish guys who watch over the slaves.}
{204}{}{What are you doing here?}
{205}{}{Just hanging out after work. Uh, what a strong joint...}
{206}{}{The sign on the roof says nothing to you? Oh, wait, that's right! The sign spoke to me only by the fifth joint... You should wait a bit.}
{207}{}{Necros. Ghouls. Call it whatever you want. Nice guys really, but many people are afraid of contacting them. Therefore, they are always-to-blame guys for any local problem.}
{208}{}{Hmm.}
{209}{}{Understood.}

#Question about smoking
{210}{}{You know, many people kicked the bucket from that stuff.}
{211}{}{You know, with these joint you remind me of the street thugs in New Reno.}
{212}{}{You know, if I were a woman, I'd not lay in bed with a smoker, you guys stink.}
{213}{}{You know, smoking causes lung cancer.}
{214}{}{You know, smoking kills.}
{215}{}{You know, heavy smokers age faster.}
{216}{}{You know, after smoking the liver turns brown.}
{217}{}{You know, after this shit you might be found speaking with a nightstand.}
{218}{}{You know, the cigarette alone does not make your appearance cool.}
{219}{}{You know, sometimes those are admixed with brahmin manure.}
{220}{}{You know, the smoke attracts flies and cockroaches.}
{221}{}{You know, they say, the cigarettes pull down the lower lip.}
{222}{}{You know, they say, the smoke prevents hairs to grow on whiskers and eyebrows.}
{223}{}{You know, nicotine causes your nails turn yellow.}
{224}{}{You know, nicotine causes teeth decay.}
{225}{}{You know stoned are not allowed in heaven.}

{250}{}{They're just doing it wrong.}
{251}{}{So?}
{252}{}{You're lucky you're not a woman.}
{253}{}{Not for me.}
{254}{}{I will hire the guards.}
{255}{}{Hell, maybe then I will not be bullied in the streets.}
{256}{}{Really? I need to find some smoker and see... Interesting!}
{257}{}{Always wanted to communicate with the inanimate world.}
{258}{}{I still have my felt hat.}
{259}{}{Nonsense! It's from mice!.. Um... Oops.}
{260}{}{Will have what to eat for lunch.}
{261}{}{The easier it will be to keep the joint in the mouth.}
{262}{}{Hmm! Saving on razors!}
{263}{}{Finally there will be a reason to do my nails.}
{264}{}{[Shows a toothless mouth] Too late.}
{265}{}{No problem - I have the right connections.}

{298}{}{Damn!!! Would you stop! Yes, I quit! I quit smoking! Just get away from me! Here [hastily puts a lighter in your hand] take it! Now I'm left without fire and will not be able to smoke whenever I want! Just fuck off! Fuck off!!}
{299}{}{All right, calm down!}

#Women's replics
{1108}{}{Why are you so raged? You see I'm stoned? I'm good. So back the hell off.}
{1115}{}{Well, I'm sorry, I overreacted.}
{1116}{}{Damn, where the hell such an bitch even came from, huh?! I don't know of any labs!}
{1130}{}{NO! Idiot! They will kill us, do you understand?!}
{1140}{}{Lay off me, pig...}
{1156}{}{What, learned all you wanted, sis?! Will you let me go already, huh?!}

{1212}{}{You know, I won't ever lay in bed with a smoker, you guys stink.}
{1252}{}{Are you sure I want to go to bed with a woman?.. Oops.}