{100}{}{You see Eric.}
{101}{}{You see a slave named Eric.}
{102}{}{What a waste. He shouldn't have taken such a risk for me.}
{103}{}{Thanks, wanderer, we will never forget it!}

{110}{}{Sorry, I've gotta get the hell out of here, right now.}
{111}{}{What?}
{112}{}{Who are you?}
{113}{}{How did you get here?}
{114}{}{You know how to get out of here?}
{115}{}{Eric, I have a letter from your brother.}
{116}{}{Eric, you can get out of here now - the slavers are dead.}
{117}{}{Nothing.}
{118}{}{Damn right! We have to get out of here, right now! Let's go!}
{119}{}{Be careful there.}
{120}{}{My name is Eric. Before getting here I was just a laborer in this city of sins.}
{121}{}{Right.}
{122}{}{It is hardly possible. Patrols guard all the exits and the lobby is always full of people. Just open the gate and the slavers will immediately grab their weapons.}
{123}{}{The postman brought me. He-he. I actually lost everything in the casino, and the owners, instead of shaking me out for debt, just sold me into slavery. It was the biggest mistake of my life. I won't ever count on luck again.}
{124}{}{Really?!}
{125}{}{Yes, here it is.}
{126}{}{I lost it somewhere, but I remember it by letter.}
{127}{}{Damn, I lost it somewhere. I'll go look for it.}

{128}{}{I find it hard to believe someone was able to go to the slave pens just to bring me a letter from my brother. Hell, playing with the feelings of the person in distress tells a lot about the one doing it.}
{129}{}{I'm telling the truth!}
{130}{}{Yeah, right.}
{131}{}{Ugh...}

{132}{}{My God! [reads the letter, then reads again] He's crazy! Damn, he just won't do it. Two guards with guns will be watching me... In any case, thank you for this. Tell him that I don't like the idea.}
{133}{}{Whatever you say.}

{134}{}{Have you heard anything interesting from the slavers?}
{135}{}{Well, some of the guards have been talking, saying, the city has a secret laboratory, where slaves are used for experiments. I wouldn't want to end up there. Although, probably slaves like me will be sent to fight in the ring.}

#Жен реплики
{1103}{}{Thanks, wanderer, we will never forget it!}



