{100}{}{You see: Servant}
{101}{}{You see a servant of Vault City.}
{102}{}{Uh, greetings... Citizen.}

{110}{}{Hey, it's you! Er, I mean... My apologies, citizen, it's good to see you, citizen. Oh, and long live Vault City!}
{111}{}{Who taught you that greeting?}
{112}{}{Enjoyed the trip?}
{113}{}{Do you like it in the city?}
{114}{}{What do you do around here?}
{115}{}{Are you treated well?}
{116}{}{What do you think about the citizens?}

{119}{}{See you.}

{120}{}{The head of servants, citizen. We must... [begins count on fingers] ...greet all citizens on sight, praise Vault City, avoid eye contact with all citizens, avoid asking questions, never use anything that citizens use, and... Something else. The head of servants explains to us every morning, how we should behave.}
{121}{}{Uh... Not exactly, citizen. We were blindfolded and placed in that prison with the energy doors. It was... Scary. First we were checked by a doctor, then interrogated by the guards. We thought we would go mad. But that's all over, and to be honest, I'm glad I ended up here.}
{122}{}{Yes, citizen! We are fed, clothed and healthy. We have a roof over our heads and don't need to fight to survive, like when we were free. Though... The work is hard. Especially after the pills we get each morning. And it's hard to think about not being allowed to leave the city, but... I'm sure I'll get used to it.}
{123}{}{I'm sorting out inventory on these shelves, citizen. The others are taken to work on constructing some sort of a building.}
{124}{}{Yes, citizen, but... There are times when I get tired of this endless rules, regulations, forms, pills and injections. I don't know what's in those shots, but afterward I can't think of anything but sitting and quietly working.}
{125}{}{I... Value... And thank the citizens. They are wonderful people... Citizen. [his eyes make it clear he's lying through his teeth]}

#Female Version
{1102}{}{Er, greetings... Citizen.}
{1110}{}{Hey, it's you! Er, I mean... My apologies, citizen, it's good to see you, citizen. Oh, and long live Vault City!}
{1120}{}{The head of servants, citizen. We must... [begins count on fingers] ...greet all citizens on sight, praise Vault City, avoid eye contact with all citizens, avoid asking questions, never use anything that citizens use, and... Something else. The head of servants explains to us every morning, how we should behave.}
{1121}{}{Er... Not exactly, citizen. We were blindfolded and placed in that prison with the energy doors. It was... Scary. First we were checked by a doctor, then interrogated by the guards. We thought we would go mad. But that's all over, and to be honest, I'm glad I ended up here.}
{1122}{}{Yes, citizen! We are fed, clothed and healthy. We have a roof over our heads and don't need to fight to survive, like when we were free. Though... The work is hard. Especially after the pills we get each morning. And it's hard to think about not being allowed to leave the city, but... I'm sure I'll get used to it.}
{1123}{}{I'm sorting out inventory on these shelves, citizen. The others are constructing some sort of building.}
{1124}{}{Yes, citizen, but... There are times when I get tired of this endless rules, regulations, forms, pills and injections. I don't know what's in those shots, but afterward I can't think of anything but sitting and quietly working.}
{1125}{}{I... Value... And thank the citizens. They are wonderful people... Citizen. [her eyes make it clear she's lying through her teeth]}
