{100}{}{You see Vortis.}
{101}{}{This is Vortis, the head of the Slavertown.}
{102}{}{What the hell is going on there, you bastards!!!}
{103}{}{Not now! I have to deal with these bastards in the lobby.}

#The starting dialogue branch:
{110}{}{Hey, I'm the boss of this establishment. What are you doing here?}
{111}{}{I need slaves, a lot of them. Twenty'll do, for a start.}
{112}{}{Can I buy one slave?}
{113}{}{I demand an explanation! How the hell are you all associated with the drug lab?}
{114}{}{To put a bullet in that head of yours! You deserve it!}
{115}{}{Seems like I got into the wrong place...}

#Ridiculous answers after the 115 phrase:
{116}{}{Another one! Just great... The entrance to the ring is from the STREET! On the other side of the building, do you hear me?!}
{117}{}{Office is in the lobby, there is an administrator you can hash out everything with him. Hear me?}
{118}{}{What are you babbling about? We do not deal with high stuff! Do you hear me? WE DON'T HAVE DRUGS!}
{119}{}{Uh, understood...}

#Answer to the question about the slave to drive the train (112):
{120}{}{I'm not dealing in retail. There is administrator in the lobby. Hash out everything with him.}
{121}{}{Got it.}

#Answer to the question about the lab (113):
{122}{}{You have a big mouth, buddy. Watch it.}
{123}{}{You want to say that it has nothing to do with you, huh? I advise you to think again, I'm here not for social calls.}
{124}{}{So it's a threat?! I guess, I will strike first then. Look!}
{125}{}{Oh, okay, I will. You know, you said that in a somewhat scary way.}

{126}{}{Huh? And why should I answer your questions?}
{127}{}{Because, by the order of the mayor, I'm investigating the recent crimes in the city.}
{128}{}{I have personal reasons.}
{129}{}{Fair enough. You need to answer with blood! So answer me, bitch!}
{130}{}{If you don't want, don't answer.}

{131}{}{Ha, my friend, well, then I have a dozen reasons to get you to shut up... [pulls out a gun and smiles as if nothing happened]}
{132}{}{Hey, hey, hey!..}

{133}{}{Which ones? Come on, tell me quick!}
{134}{}{I want to work there.}
{135}{}{I want to destroy the lab.}
{136}{}{I just want to get high! Want a lot of stuff to do it!}

{137}{}{Not this again... They are buying enough of slaves from us, so they won't need you.}
{138}{}{Uh... Wait a minute. [enable recording on the Pip-Boy] So you're saying that you are supplying the lab with slaves, right?}
{139}{}{Too bad.}

{140}{}{[Looks at your Pip-Boy] But... Nobody will know about this conversation.}
{141}{}{Hey, Hey, Hey! I'm just asking!}

{142}{}{I don't care. It's none of my business..}
{143}{}{Reeeally doubtful...}

{144}{}{Those guys don't deal that stuff in retail, so don't even think about it. There are a couple of their outlets in the city. Go to caravaneers, their couriers have settled there. Another one hangs out near "Hard Rock" cafe. That's it, get out of here. The junkies don't belong in here. We have enough of our own.}
{145}{}{Uh... Wait a minute. [enable recording on the Pip-Boy] So do you know where this lab is located, right?}
{146}{}{Okay, I will look out.}

#Answer to the question about the slaves for the Hoover dam (111):
{147}{}{Can I first know what these slaves are meant for?}
{148}{}{Heavy physical labor.}
{149}{}{Hmm... Is it possible to be more specific?}
{150}{}{I can't tell.}
{151}{}{Is that so? Then I can't sell. Ha!}
{152}{}{Stop bluffing, the money is at stake! Your job is to obtain the money in exchange for slaves, the rest does not matter. So hurry up or you'll lose a client.}
{153}{}{Well, too bad.}
{154}{}{Damn, you're well-spoken. You see, I learned that the Hoover dam lacks the workers lately. And, sooner or later, the chief of the dam will come to us... So, convince me, why should I sell the slaves to *you* rather than him.}
{155}{}{As I understand, there are people in the city fighting to control the dam...}
{156}{}{Ugh. Well, it's too complicated. I'm not going to convince you.}

{157}{}{Well, then I'll try to catch lady Luck's tits.}
{158}{}{Okay. I hope you'll change your mind.}

{159}{}{Damn, true say! Okay, by our price, for fifty slaves you will have to pay ten thousand.}
{160}{}{I have just the right amount.}
{161}{}{Not now then.}

{162}{}{About the slaves. I got 10 thousands and I'm ready to make a deal.}
{163}{}{You purchased a shipment of slaves for the Hoover dam. The only thing left is to inform Bob Neil.}
{164}{}{Great deal. The slaves will wait in our corral, it's here, nearby. Just send your employees here to pick them up. And here is the receipt, to prove that everything was fair.}
{165}{}{All right.}

{170}{}{What's going on here? Answer me!}
{171}{}{Uh, boss, we don't know what it was!}
{172}{}{What does that mean?!}
{173}{}{We don't know, boss! Nobody has run away, everything is under control!}
{174}{}{Then what's that screaming about the escape I hear over the radio!?}
{175}{}{Perhaps, one of the patrol's idea of a joke...}
{176}{}{When I find him, I'll personally bury him alive!}
{177}{}{Sure, boss.}
{178}{}{Hey, why are you still here!? Quickly find that joker!}
{179}{}{Um... Boss, but how do we find him?}
{180}{}{Uh-h, you are just a bunch of boneheads! I hate you all so much!}
{181}{}{Um... Boss...}
{182}{}{Also, count the slaves, you pecks!}
{183}{}{Whatever you say, boss.}
{184}{}{::grumbles::}

{185}{}{Anyone can lay their hands on it. Will you be able to make your deal in time? Hmm, but my coin is *guaranteed*, think about it.}
{186}{}{So what?}

#Women's replics
{1115}{}{Seems, I got into the wrong place...}
{1119}{}{Uh, understood...}
{1122}{}{You have a big mouth, gal. Watch it.}
{1131}{}{Ha, my friend, well, then I have a dozen reasons to get you to shut up... [pulls out a gun and smiles as if nothing happened]}
{1141}{}{Hey, hey, hey! I'm just asking!}
