{100}{}{You see Vortis.}
{101}{}{This is Vortis, the head of Slavertown.}
{102}{}{What the hell is going on there, you bastards!!!}
{103}{}{Not now! I have to deal with these bastards in the lobby.}

#The starting dialogue branch:
{110}{}{I'm the boss of this establishment. What are you doing here?}
{111}{}{I need slaves, a lot of them. Twenty'll do, for a start.}
{112}{}{Can I buy one slave?}
{113}{}{I demand an explanation! How the hell are you all connected to the drug lab?}
{114}{}{To put a bullet in that head of yours! You deserve it!}
{115}{}{Looks like I got into the wrong place...}

#Ridiculous answers after the 115 phrase:
{116}{}{Another one! Just great... The entrance to the ring is ANOTHER DOOR OUTSIDE! On the other side of the building, do you hear me?!}
{117}{}{Office is in the lobby, there is an administrator you can hash out everything with him. Understood?}
{118}{}{What are you babbling about? We do not deal with this stuff! Do you hear me? WE DON'T SELL DRUGS!}
{119}{}{Uh, understood...}
#118 is used as response to 115 for some reason?
#Answer to the question about the slave to drive the train (112):
{120}{}{I don't do retail. There is an administrator in the lobby. Hash out everything with him.}
{121}{}{Got it.}

#Answer to the question about the lab (113):
{122}{}{You have a big mouth, buddy. Watch it.}
{123}{}{So you're saying that it has nothing to do with you? I advise you to think again, I'm here not for taking a poll.}
{124}{}{Is that a threat?! If yes, then I will strike first. Watch me!}
{125}{}{Oh, okay, I will. You know, you talk in a somewhat scary way.}

{126}{}{Huh? And why should I answer your questions?}
{127}{}{Because, by the order of the mayor, I'm investigating recent crimes in the city.}
{128}{}{I have personal reasons.}
{129}{}{Fair enough. You need to answer with blood! So answer to me, bitch!}
{130}{}{If you don't want, you don't have to answer.}

{131}{}{Ha, my friend, then I have a dozen reasons to shut you up... [pulls out a gun and smiles as if nothing happened]}
{132}{}{Hey!...}

{133}{}{Which ones?}
{134}{}{I want to work there.}
{135}{}{I want to destroy the lab.}
{136}{}{I just want to get massively high! I need A LOT of stuff to do it!}

{137}{}{Not this again... They are buying enough slaves from us, they won't need you.}
{138}{}{Uh... Wait a minute. [enable recording on your Pip-Boy] So you're saying that you are supplying the lab with slaves?}
{139}{}{Too bad.}

{140}{}{[Looks at your Pip-Boy] But... Nobody will know about this conversation.}
{141}{}{Hey, wait a second! I'm just asking!}

{142}{}{I don't care. It's none of my business.}
{143}{}{I reeeeally doubt that...}

{144}{}{Those guys don't deal in retail, so you can stop even thinking about it. There are a couple of their outlets in the city. Check out the caravan stop, their couriers can be found there. Another one hangs out near "Hard Rock" cafe. That's it, get out of here. The junkies don't belong in here. We have enough of our own.}
{145}{}{Uh... Wait a minute. [enable recording on the Pip-Boy] So you know where the lab is located, right?}
{146}{}{Okay, I will look out.}

#Answer to the question about the slaves for the Hoover dam (111):
{147}{}{Can I first know what these slaves are meant for?}
{148}{}{Heavy physical labor.}
{149}{}{Hmm... Care to be more specific?}
{150}{}{I can't tell.}
{151}{}{Is that so? Then I can't sell. Ha!}
{152}{}{Stop bluffing, the money is at stake! Your job is to obtain the money in exchange for slaves, the rest does not matter. So hurry up or you'll lose a client.}
{153}{}{Well, too bad.}
{154}{}{Damn, you're well-spoken. You see, I learned that the Hoover dam lacks the workers lately. And, sooner or later, the chief of the dam will come to us... So, convince me, why should I sell the slaves to *you* rather than him.}
{155}{}{As I understand, there are people in the city fighting to control the dam...}
{156}{}{Ugh. It's too complicated. I'm not going to talk you into it.}

{157}{}{Well, then I'll try to catch lady Luck's tits.}
{158}{}{Okay. I hope you'll change your mind.}

{159}{}{Damn, that's true. Okay, at our rates, fifty slaves are going to cost you ten thousand.}
{160}{}{I have just the right amount.}
{161}{}{Not now then.}

{162}{}{About the slaves. I got ten thousands and I'm ready to make a deal.}
{163}{}{You purchased a shipment of slaves for the Hoover dam. The only thing left is to inform Bob Neil.}
{164}{}{Great deal. The slaves will be waiting in our corral. Just send your workers to pick them up. And this is a receipt to keep things fair.}
{165}{}{All right.}

{170}{}{What's going on here? Answer me!}
{171}{}{Uh, boss, we don't know what it was!}
{172}{}{What does that mean?!}
{173}{}{We don't know, boss! No one has escaped, everything is under control!}
{174}{}{Then what was all that yelling about running away that I heard on the radio!?}
{175}{}{Perhaps, one of the patrol's idea of a joke...}
{176}{}{When I find out who that was, I'll personally bury him alive!}
{177}{}{Sure, boss.}
{178}{}{Why the fuck are you still here!? Quickly find that joker!}
{179}{}{Uh... Boss, but how do we find him?}
{180}{}{Uh-h, you are just a bunch of boneheads! I hate you all so much!}
{181}{}{Erm... Boss...}
{182}{}{Also, count the slaves again, you pecks!}
{183}{}{Whatever you say, boss.}
{184}{}{::grumbles::}

{185}{}{It could be taken over by anyone. Will you be able to make your bargain?  And my coin is *guaranteed*. Think about it.}
{186}{}{So what?}

#Women's replies
{1115}{}{Looks like I got into the wrong place...}
{1119}{}{Uh, understood...}
{1122}{}{You have a big mouth, girl. Watch it.}
{1131}{}{Ha, my dear girl, then I have a dozen reasons to shut you up... [pulls out a gun and smiles as if nothing happened]}
{1141}{}{Hey, wait a second! I'm just asking!}
