{100}{}{You see Gareth.}
{101}{}{You see a seemingly ordinary passerby.}
{102}{}{*running script error*}

{110}{}{Uh... Hello, wanderer. And... Have a good day.}
{111}{}{Wait, what are you doing here?}
{112}{}{Whatever.}

{113}{}{Uh... [looks closely at your face] You look like one of them [pointing in the direction of the slavers office]. Sorry, but I will be on my way.}
{114}{}{Do I really look that bad...}

{115}{}{Uh... [looks closely at your face] Are you one of these [pointing in the direction of the slavers office]? What are *you* doing here?}
{116}{}{I asked first.}
{117}{}{I'm just passing by, minding my own business.}
{118}{}{I'm looking for a fresh slave.}
{119}{}{Nothing that would justify a conversation with you.}

{120}{}{Then I guess we have nothing to talk about.}
{121}{}{Uh...}
{122}{}{See, you have no confidence in me. That means I should refrain from talking to you.}
{123}{}{So you are not one of them? Phew, at least someone in this city is "just a passerby", and not a member of some nefarious organization.}
{124}{}{And you are a member of which organization?}
{125}{}{Yeah. Well, it was nice to talk to you.}

{126}{}{The member of the secret sect of Avengers... Just joking. Heh-heh.}
{127}{}{Wow, can I join your sect?}
{128}{}{Damn, you're taking me for a moron?}
{129}{}{He-he. Bye, damn joker.}

{130}{}{Well, you can't join without testing. We are literally two people. It is unlikely that you will want to be a part of it. The risks and stuff...}
{131}{}{Hey, don't get mad, I didn't do anything wrong!}
{132}{}{You'd better tell me what you're up to.}
{133}{}{I think you are in trouble. Tell me, maybe I could help.}
{134}{}{So, I'll believe you... This time. Bye.}

{135}{}{Oh, okay. Anyway, I can't do this alone.}
{136}{}{So what's your problem?}

{137}{}{The problem isn't mine, it's my brother's. Damn slavers grabbed him when he returned to the city and locked him in the corral. I want to rescue him, but it's not going to be easy.}
{138}{}{Do you have a plan?}
{139}{}{I have, yes, but first I need to contact Eric. However, one can get into the corral only as a slave. And it means being branded for life.}
{140}{}{How do you know he's there?}
{141}{}{This is an option, isn't it? You can become a slave, I will avenge you.}
{142}{}{I can get the note to your brother.}
{143}{}{Uh, today it won't be my problem, take care.}
{144}{}{A friend saw him and said he was here. Then I found a gap in the fence and spotted him among the slaves.}
{145}{}{Not an option. First, there is no guarantee that you will get me out, and second, I don't want to walk with the mark on the forehead for the rest of my life.}

{146}{}{Are you going to get in there?! Why!? Once you are there, you won't come back without a mark on the forehead!}
{147}{}{Don't worry about me, I know what to do.}
{148}{}{Well, it's up to you...}
{149}{}{I'll do it if you pay me.}
{150}{}{Right, it's too silly. Risk yourself, and I'm leaving.}

{151}{}{Oh, it's you. Hello.}
{152}{}{So what was that about the problem with your brother?}
{153}{}{Yeah, it's me, relax.}

{154}{}{Damn, that would be great. You just need to pass a note to Eric.}
{155}{}{Just a note, I'll do it.}
{156}{}{I changed my mind, sorry.}

{157}{}{Hey, wait. I can pay 200 bucks if you'll do it. Would have paid more if I had more... But, of course, I'm not paying immediately, so there would be a motivation for you not to cheat. You just need to pass a note to Eric, nothing more.}
{158}{}{Give me a note, I'll do it.}
{159}{}{Nope, I'm not doing it.}

{160}{}{Sure, I'll pay, but only after Eric receives a note. However, I only have 200 bucks. Would pay more if I was richer...}
{161}{}{Give me a note, I'll do it.}
{162}{}{I changed my mind, sorry.}

{163}{}{Here. I'm *really* counting on you! Please, everything depends on it! If this note gets into the hands of slavers - all will be for nothing.}
{164}{}{Okay, I'll think about it.}

#After getting the quest on passing the note
{200}{}{Well, how is it going, wanderer?}
{201}{}{I have some bad news - Eric is dead.}
{202}{}{Relax, Eric got your note.}
{203}{}{I'm still working on it.}

{204}{}{What?! What the hell! You could have mistook him or... Or you are lying... Or... I don't know what, but I don't believe you!... Ugh, why I did even get involved with you?! Get away from me!}
{205}{}{Oh, that's how you act now!}
{206}{}{Oh, good! Now it's going to be easier for me to deal with it...}
{207}{}{And what about my reward?}
{208}{}{What? Ah, yes. But wait, how do I know you're telling the truth? No, first I'll check.}
{209}{}{WHAT?!}
{210}{}{It'll be simple. We will wait for the evening and you'll see.}
{211}{}{Okay, let's wait.}
{212}{}{Hell no! Pay me now!}
{213}{}{Then I'll be back later.}
{214}{}{I have no money right now. You'll have to wait.}
{215}{}{I have an idea. You see, the bartender in the ring said they wanted to put Eric as a fighter. I was able to eavesdrop on the slavers' conversations.}
{216}{}{Great! I think you will not be bored.}
{217}{}{Will see.}

{218}{}{The slaves are now free. Nothing stops them from getting out.}
{219}{}{Wonderful news! And I was just pondering what that suspicious commotion in the corral was all about. Thank you, wanderer! Here, take 200 bucks for the risk. That's all I got.}
{220}{}{Of course, take care!}

{221}{}{Thanks for the help, wanderer. I was glad to meet such a wonderful person. Here [hands 200 bucks] - all I can give you for your help.}
{222}{}{Wait, how did you know that Eric is going to be taken to the ring?}
{223}{}{I learned it from the bartender, I know him. And then I overheard the talks on the radio channel of the slavers. By the way, here, take the radio, I don't need it anymore. Maybe you'll find a use for it.}
{224}{}{Thanks. Well, take care.}
{225}{}{It all was in vain... [grabs his head]}
