{100}{}{You see administrator Aidan.}
{101}{}{You see the administrator of the Slavertown.}
{102}{}{*running script error*}
{103}{}{Great. Let's part on these terms.}

#Starting dialogue branch
{200}{}{Ah, fresh blood! Come, don't be afraid. This is the slaver's guild, my name is Aidan. Are you here on a business matter? It better be.}
{201}{}{I want to buy half a hundred of strong, healthy slaves.}
{202}{}{I want to buy half a hundred of strong, healthy slaves. Why - is none of your business.}
{203}{}{You obviously are involved in dirty affairs. Therefore, you will all die. Now!}
{204}{}{I know you're involved in the local drug business! And you will show me where the production site is located.}
{205}{}{I need a slave. It will work as a driver on a train.}
{206}{}{Uh... No. Bye.}

#Response on 203 
{207}{}{Oh, wow, what a warrior! Ha-ha! Come on, try it, I'm all yours!}
{208}{}{Great! Take that, scum!}
{209}{}{Hell, there's too many of you. I'd rather ambush one of you around the corner. Bye.}

#Response on 204
{210}{}{For real? Ha! If you find out anything about it, tell me! I'll be the first in line to test their new drugs, ha-ha!}
{211}{}{You're lying! Answer me, you son of a bitch! Where is the lab?!}
{212}{}{Oh, well, if you don't know, then I'm sorry.}
{213}{}{Hey, lads! There's a prick here and he's asking for it!}
{214}{}{Look at how I'm going to defend myself!}
{215}{}{All right, man, I'll leave you alone, chill out.}

#Response on 205
{216}{}{There is one just for you. Knows how to handle tech, won't run away, will work hard. As for the price, I'll sell him for $3000.}
{217}{}{I'm convinced. Here is the money. Send the slave to Salt Lake City, have him meet me at the "Sixth bullet" hotel.}
{218}{}{I'll pass.}
{219}{}{Are you out of your mind? For that kind of money I could buy a dozen slaves. Drop it to $2000.}
{220}{}{It's not every day that a product like this hits the corral. That's why I'm not going to lower the price.}
{221}{}{Then, you lose a customer. I'm leaving.}
{222}{}{It's not every day that a product like this hits the corral... However, no one's buying him for quite a while. Maybe I indeed ask too much. Okay, I'll drop the price to $2000.}
{223}{}{A reasonable solution. Here is the money. Send the slave to Salt Lake City, have him meet me at the "Sixth bullet" hotel.}
{224}{}{You have found a driver for the train. You can now return to Salt Lake and continue your mission.}

#Response on 202
{237}{}{Okay, I won't even ask. The boss will. I'm not in charge of these big deals. Go talk to him, it's just down the hall to the left.}
{238}{}{Okay, I'll go look for him.}

#Cowboy
{240}{}{I want to sell a strong fighting slave. He now stands by the car, naked and defenseless.}
{241}{}{Fine. We always need good slaves, especially fighters. Their usual purchase price is $500.}
{242}{}{I like the price. You can pick him up. Oh, and... Maybe he will resist. 'Cause, you know, he is a fighting slave after all.}
{243}{}{How much?! No, I'll try to find another use for him.}
{244}{}{This one looks decent. The body is in excellent condition, strong enough to fight more than once. A good product. Here is the payment.}
{245}{}{Finally, some use for him...}

#Eric the slave
{250}{}{I'm looking for a certain slave named Eric.}
{251}{}{Let's see... Yes, there is one with such a name. A slave of the worker class. They may be used to carry weights or sent to fight in the ring.}
{252}{}{How much for him?}
{253}{}{The slaves of this kind are worth 500 bucks each.}
{254}{}{Okay, I'll buy him.}
{255}{}{That's too much!}
{256}{}{Thanks, I don't need it.}
{257}{}{Such slaves are expensive. If only the clients knew how much effort is put into capturing and training them...}
{258}{}{I'll come back when I have enough money.}
{259}{}{Hey there! Item number A12-86! Come here, customer's waiting!}
{260}{}{I'll wait.}

{261}{}{I can sell you some information about the impending escape attempt.}
{262}{}{Very interesting. Who is that moron, who decided to look for his death in our corral?}
{263}{}{Are you going to buy the information or not?}
{264}{}{I think yes. But you go first!}
{265}{}{Okay. Here is a note from someone named Gareth to one of your slaves.}
{266}{}{No, money up front!}
{267}{}{No information. I changed my mind.}
{268}{}{I'm not a haggler, talk or walk out.}
{269}{}{[Reads the note] What a naive fool. So, where is this Gareth now?}
{270}{}{At the eastern wall of the corral.}
{271}{}{That's it!?}
{272}{}{No man, no problem.}
{273}{}{Okay, here's 300 bucks and a gratitude on behalf of the company. Don't ask me for more.}
{274}{}{Ha, so much money for a side job...}

#Collars
{278}{}{Four.}
{279}{}{Seems like I can sell more.}
{280}{}{I have slave collars to sell.}
{281}{}{Are you still interested in slave collars?}
{282}{}{Oh, this accessory is very much appreciated among the slave owners. A very useful thing! I'll buy them for 100 bucks each.}
{283}{}{I'm counting at 125.}
{284}{}{Okay, that's fine by me.}
{285}{}{I don't think I will accept that price. I'll come back if I change my mind.}

{286}{}{How much?! Even some slaves are worth less than your price! I have been too generous today already.}
{287}{}{All right, I'll settle for a hundred.}
{288}{}{Well, if you think about it... Okay, I agree to such a price.}
{289}{}{Great.}
{290}{}{However, they might still be useful for me. I'll come back if I change my mind.}

{291}{}{How many collars are you going to sell?}
{292}{}{One.}
{293}{}{Two.}
{294}{}{Three.}
{295}{}{Five.}
{296}{}{All I have (}
{297}{}{ items).}
{298}{}{None. I changed my mind.}

{299}{}{A great deal!}

#Women's replics
{1207}{}{Oh, wow, what a warrior! Ha-ha! Come on, try it, I'm all yours!}
{1213}{}{Hey, lads! There's an arrogant bitch here and she's asking for it!}
{1267}{}{There will be no information, I changed my mind.}
{1298}{}{None. I changed my mind.}
