{100}{}{You see a citizen.}
{101}{}{You see an ordinary citizen.}
{102}{}{Sorry, I'm in a hurry.}

#–еплики при попытке заговорить, когда копа убили:
{150}{}{They say the shots came from the roof.}
{151}{}{Some mention seeing a sniper on the roof of the casino. Weird.}
{152}{}{It all happened so fast!}
{153}{}{For a long time no one was killed in the Clean City, especially the police officers.}
{154}{}{No one was expecting it here...}
{155}{}{Who could have done it?}
