{100}{}{This is Paul Tibbett.}
{101}{}{You see a little fat owner of the trade shop.}

{110}{}{Hey, come in, wanderer! I just looked for a good weapon for you. Wanna take a look?}
{111}{}{Hey, come in, wanderer! I just was looking for a solid armor for your travels in the wilderness. Would you like to try it?!}
{112}{}{Hey, come in, wanderer! I was just thinking, what would a client such as you, need? Take a look - perhaps, you'll find something useful.}

{113}{}{[Upon entering the shop, the first thing that catches your eye is the owner, who is diligently tinkering with some kind of part. He wears a baseball cap, t-shirt, faded jeans, and has a Mexican-type slightly gray beard on his face. A walking American stereotype.]}
{114}{}{Ahem...}

{116}{}{Hey, do not rush with the decision! Today I have a real sale. You just have to admire these beautiful shiny guns! Powerful energy gun straight out of Area 51. How? Well, there were some desperate miners who managed to penetrate the facility and steal everything they could carry on their feet. But it is not so important. The important thing is that now you can choose a truly excellent weapon.}
{117}{}{Doesn't sound bad.}

{118}{}{Oh! Pal, I see you've already succeeded in life if you're traveling on four wheels. What does your baby run on? Microfusion batteries? Hey, I can make additional power supplies specifically for you and your beauty.}
{119}{}{Wow, I must remember this for the future.}

{120}{}{Let me look at your stuff.}
{121}{}{I think I entered the wrong place. Bye.}
{122}{}{More or enough?}
{123}{}{Right, let's take another look.}
{124}{}{Uh, no, this is enough.}

{125}{}{Can you answer few questions, while I'm looking?}
{126}{}{I don't sell information here, as you can see. I'm not the one you need. It is hard to get a good informant in Vegas.}
{127}{}{Maybe, you can tell me about Vegas then?}
{128}{}{Let's trade then.}
{129}{}{Vegas! Sparkling New Vegas! The city that never sleeps. Uh... Maybe you need a shovel or a pack of contraception?}
{130}{}{Maybe I do, but later. And what you can do here?}
{131}{}{In Vegas, there is a slew of kinds of entertainment for all tastes. But do not expect to find work. Everything here is constructed so that the money always are pulled to the Clean City and never go out.}
{132}{}{Tel me about the Clean City.}
{133}{}{The fenced area in the north. Clean and comfortable, plenty of light, the police maintains order. You might want to look and see this beauty. Nowhere in this wasteland you can see anything like this. But the people who live there are not distinguished by generosity. These snobs look down to all and everyone.}
{134}{}{Any other areas?}
{135}{}{To the west is the "Hard Rock" cafe. The area is more or less calm, but sometimes there are clashes between local gangs and street robbers. To the south of the cafe is the Slavertown. Eerie and unpleasant place, it is being run by slavers. In the east you can walk to the Hoover Dam, but it's far. A place with spectacular views. Impressive!}
{136}{}{What else the newcomer needs to know about the city?}
{137}{}{If you're in a Clean City, do not forget to hide the weapon in the holster, and that the local police don't like strangers. also hide your weapon in the casino. But when outside, better keep the gun closer.}
{138}{}{Okay, thanks, for the help.}
{139}{}{Hey-hey-hey! I told you all, that your heart desired. And you leave without even buying anything?}
{140}{}{Yeah well.}
{141}{}{Indeed - this is not right. Have a 10$ tip.}
{142}{}{What, I'm still looking. Let's trade.}
{143}{}{[Smiles] Thanks. Come by, when you'll have time!}
{144}{}{Bye.}

{145}{}{In such case I have nothing to do here. Bye.}
{146}{}{}

{147}{}{Then get out of my shop!}
{148}{}{Your shop doesn't look like a barn anymore. Take care.}
{149}{}{I didn't want to insult you, sorry. I think I'll go.}

{150}{}{}
{151}{}{}
{152}{}{New? Isn't it a pre-war city?}
{153}{}{Yes! But the greatness of gleaming pre-war city faded soon after the Great War. Now it's a lot different. That's why I say - this is a new Vegas. The new city, an oasis in the desert. However, no one has yet realized the idea. Believe an old man, the time will come - and everyone will call it this way.}
{154}{}{You're doing the right thing, to trust me. Now let's take a look at the goods...}

#Ïðèìåíåíèå íàâûêà áàðòåð
{158}{}{You have such a wide assortment. The trade in these parts must be a very profitable business.}
{159}{}{Not quite... Hey, how much longer are you gonna watch? As far as I can see, it's time to buy something.}
{160}{}{Hmm, let me think: the shop in the most comfortable place, cops are not far, and you are selling guns. You're definitely connected, right?}
{161}{}{[Sighs] I don't want to talk about it, but you're too smart for a simple customer. The truth is, my main business was tied with guns, but then the Clean City started to seize all power and shops. Cops didn't want for the weaponry to be distributed freely. That's why I get protection and permission to work from them, and in return, I send every good weapon to Clean City's armory. Such is the agreement. But remember - I told you this only because, you put me against the wall.}
{162}{}{Really crafty bastards. You did well for yourself. Fine, bye.}
{163}{}{Thanks to your trade skill you earned 100 experience points for uncovering the secret of Tibbett business.}
{164}{}{You successfully used your trading skills and got access to a secret Tibbett selection. But be warned, this was only just for this one time.}
{165}{}{Hmm... If you share your goods with cops, then you must be collecting everything special, in some secret place.}
{166}{}{This is only for the privileged... That means for the representatives of the Clean City. I don't think that I will risk selling this to strangers. The reputation with the Clean City is more important for me.}
{167}{}{You say that, because you cannot be sure in your business partner. I can understand you very well. I have seen so many traders myself. Think over my candidacy.}
{168}{}{I knew for some reason, you'll say that.}
{169}{}{[Thinks] You're not a usual customer, right? Such skills as yours are a rare find. I respect your business - that why I'll trust you. Okay, here I stashed this for the cops. If you need some of it, you can buy it. Just don't tell anyone, that you bought it of me.}

#Êîîðäèíàòû Ñâàëêè ïîêðûøåê
{170}{}{Hey, do you have anything special for my ride?}
{171}{}{Hmm, let me think. I don't have anything, except batteries, but I'm sure you can find something at my old pal. Ex-mechanic, he used to be called Skitter, until he... Underwent ghoulification. Terrible story. The locals don't like ghouls here, that's why he lives not far from Vegas - he decided to isolate himself in a tire dump, when he became sick of people.}
{172}{}{Why didn't you say that in the first place! Great, tell me, where is your friend.}

{173}{}{It's not far from Vegas, to the north-east. Though, I can't remember the exact coordinates, getting old. But, the smell of money can bring my memory back.}
{174}{}{How about a trade? You do certainly need fresh goods...}
{175}{}{Hmm... Cash would be better, and the goods will stay on a shelf for a long time, until a buyer will come. Look - I'll write down the coordinates on holodisk, and you come, when you find something useful to exchange.}
{176}{}{Ok, let's trade then.}
{177}{}{Then I can do without your services, you extortionist.}

{178}{}{Ha! You'll break your legs running around looking for it. But, it's your business - whether you look by yourself in the whole wasteland, relying on your scouting skills, or just to pay me for the exact coordinates. Just saying.}
{179}{}{My choice is obvious. I'll manage without you.}

#Øëåì äëÿ ñèëîâóõè
{190}{}{What is that helm that you got for sale?}
{191}{}{Well, lately, strange things started to appear. They say, some brave souls began looting in the north-west - there, where the aliens come from. People are not all right in the head. But I only benefit from this.}
{192}{}{Okay. That is all I was interested in. Bye.}

#Ïèöà
{200}{}{[With amazement, he looks at the pizza in your hands, then at the clock] Boy, you're slower than a brahmin wagon, loaded with old junk. Where were you all this time? You're late. So you can carry it back to the cafe and to declare my dismissal. I'm not going to pay.}
{201}{}{[Leave]}
{202}{}{Pizza! Just in time, give it here, now I'll get even with it, he-he.}
{203}{}{Sure, sir. here. You owe }
{204}{}{$.}
{205}{}{Er, how much?}
{206}{}{$ for pizza and 10$ for delivery... Is there a problem, sir?}
{207}{}{Well, actually, when I made the order for delivery it was 5$, so... Do you mind? [gives the money and stretches to the pizza]}
{208}{}{Sure, sir. The deal was 5$, then there you have it. Have a nice day!}
{209}{}{No way. The delivery is *10$*! Either you pay, or I'll take the order.}
{210}{}{Thank you, courier! It is pleasant to deal with such executive employees, as in Phillips'. Tell him I said hello.}
{211}{}{Have a nice day!}
{212}{}{Oh, sure. I will certainly look in to it, and at the same time ask, when you have made an order... To revise the pricing policy in your respect.}
{213}{}{[Frowning and looking nervous, counts 5$] Okay, okay, just don't think, that I will forget that.}
{214}{}{[Frowning and looking nervous, counts the money] You think, I would lie, huh? You want to tell me, that I'm some thief, if I forgot about 5$? Fuck, I have the best shop in the whole Vegas! Ah, what can I say, you're just a courier.}
{215}{}{Sir, I assure you - I didn't had anything in mind like that. You look like a respectable person! I would never suspect, that you could lie. Really!}
{216}{}{[Leave]}
{217}{}{[Grins the edge of the mouth and corrects buttons at the collar] Well, yes, I know... Do not worry, I'm too nervous today, so forget it. Next time I will specify the price before ordering. Good luck, and... Take care, courier.}

#Female character
{1110}{}{Hey, come in, wanderer! I just looked for a good weapon for you. Wanna take a look?}
{1111}{}{Hey, come in, wanderer! I just was looking for a solid armor for your travels in the wilderness. Would you like to try it?!}
{1112}{}{Hey, come in, wanderer! I was just thinking, what would a client such as yourself need? Take a look - perhaps, you'll find something useful.}
{1118}{}{Oh! Lady, I see you've already succeeded in your life, if you travel on four wheels. What does your baby runs on? Microfusion battery? Look, I can make an additional power supplies specifically for you and your steel stallion.}
{1121}{}{I think I entered the wrong place. Bye.}
{1149}{}{I didn't want to insult you, sorry. I think I'll go.}
{1167}{}{You say that, because you cannot be sure in your business partner. I can understand you very well. I have seen so many traders myself. Think over my candidacy.}
{1168}{}{I knew for some reason, you'll say that.}
