{100}{}{You see: 'AVCS'.}
{101}{}{You see the Automated Vault Control Systems central unit.}

{110}{}{You see the Automated Vault Control Systems central unit. The device stolen by Jay Kukish belongs right here.}
{111}{}{[Leave]}
{112}{}{[Initiate the lab's self destruct]}
{113}{}{[Escape from this level is impossible, so you will perish together with the incubators. Are you sure?]}
{114}{}{That's the way... [initiate self destruct]}
{115}{}{Plug in the device and initiate the purge of hostiles from Vault.}
