{100}{}{This is a Shitposter.}
{101}{}{You see a wild creature, vaguely resembling a human, being tied to the pillory so that any passerby could spit at *it*.}

{110}{}{You see a dirty ugly boy. He is tied to the pillory, so that anyone who wants could kick him or spit on him. A sign nearby announces the crime: "Shitposter. Punished for inhumane treatment of others and of himself personally".}
{111}{}{[Kick him for this hard, right in the balls!]}
{112}{}{[Spit in his face, like everyone else does.]}
{113}{}{Hey, lad. Were you tied to a pole justly?}
{114}{}{Hey, hold on, chappie! I'm gonna set you free!}
{115}{}{[Leave him]}

#Spit on Shitposter
{120}{}{[The kid suddenly starts bashing his head in ecstasy] AH! AHHH! [I think he loves it when you spit on him!] A-A-Ah!!!}
{121}{}{[Spit again]}
{122}{}{Oh!!! O-o-o-oh!!! A-a-ah!!! [the kid is almost drugged by your actions, he wants more!]}
{123}{}{[Well, why not, spit one more time]}
{124}{}{Mhm!!! [the head of this insane being starts banging faster] M-m-m!!! [seems, he lost all the common sense he had]}
{125}{}{No... That's enough!.. Oh, well, I should spit one more time as a goodbye!}
{126}{}{No, enough in enough.}
{127}{}{AAARGH!!! [this insane man bashes his head against the pole so hard that the drops of blood start to drip from his forehead!]}
{128}{}{Hey! Wait! What are you doing?! Calm down!!!}
{129}{}{Serves you right! Come again! Again!}

#conversation or the kick in the nuts
{130}{}{Oh, you fucking cowboy!!! Ah!!! [it seems that his reproductive organ was the most important thing in his life; having lost his dignity, Shitposter dies, squeezing rich white foam out of his mouth]}
{131}{}{Uh... How disgusting.}
{132}{}{Fucking defenders of the innocent! I fucking hate you all! Arrgh! I'd pee on you till you're in it up your throat! Hands off the ropes! Away!}
{133}{}{Why do you react like that to the attempts of providing help? Do you consider yourself deserving the pillory?}
{134}{}{Uh, okay. No problem. Calm down.}
{135}{}{Yes! Yes!!! YES!!! I'm an animal! I'm a sneaky bitch! I done my mother and my father done me! I'm wasted! I want to be hated by everyone! EVERYONE!}
{136}{}{Hmm. You know, you don't look particularly sick in the head. I think you're just showing off, trying to make yourself look like something special.}
{137}{}{You're right, and for that I will punch you in the balls!}
{138}{}{Well, whatever, that's your business...}
{139}{}{You! You!.. You have no right! No!.. Get away from me! Get off!}
{140}{}{Yes! I was right, see? Otherwise you would have ignored me from the beginning, but you gave it some thought first, and then began to look for excuses. You're a blowhard.}
{141}{}{Grrrr! Yes, I'm a blowhard! blowhard! blowhard! blowhard!!! Are you happy?!}
{142}{}{And now you admit it just in order to gain more thrashing. In short, stop messing around and go home. Enough with embarrassing yourself in front of adults!}
{143}{}{[Sobbing] How dare you! I have done so much to be tied to a pole, to be spat by everyone, and you're pulling me back! No! NO!!!}
{144}{}{Yes, buddy, YES! You have played enough, it's time come back to your senses. Everyone had times when they were wetting themselves. This is normal.}
{145}{}{Damn! I hate you so much! [you're unbinding Shitposter and he is about to go home] Oh, I HA-TE you!!!}
{146}{}{I don't think so, you're too pretentious. If you learn not to think about yourself as someone very special, everything will be fine.}

#Women's replics
{1130}{}{Oh, you fucking cunt!!! Ah!!! [it seems that his reproductive organ was the most important thing in his life; having lost his dignity, Shitposter dies, squeezing rich white foam out of his mouth]}
{1132}{}{Fucking defenders of the innocent! I fucking hate you all! Arrgh! I'd pee on you till you're in it up your throat! Hands off the ropes! Away!}
{1140}{}{Yes! I was right, see? Otherwise you would have ignored me from the beginning, but you gave it some thought first, and then began to look for excuses. You're a blowhard.}
{1141}{}{Grrrr! Yes, I'm a blowhard! blowhard! blowhard! blowhard!!! Are you happy?!}
