{100}{}{You see an old acquaintance.}
{101}{}{You see the prisoner from the Wind of War!}

#Different things
{102}{}{You have got a hint about the existence of the secret laboratory outside the city.}
{103}{}{Hrrm... Yah... It will be the drunkest state in America... Hrrm...}
{104}{}{Hello there, friend!}

#First dialogue [booze] 
{110}{}{Heh-Hey! My man! There you are! I knew you would come here! Let me buy you a drink! Hey, bartender! Put it on my tab!}
{111}{}{So, you managed to escape from the Wind of War. Won't they look for you?}
{112}{}{No way! Those military idiots are afraid of even coming near Vegas! Don't worry, buddy! We're safe here.}
{113}{}{They're not well-liked here in Vegas?}
{114}{}{They are *hated* here. These bastards are going to be kicked out from Clean City immediately.}
{115}{}{Why?}
{116}{}{Because they think they're tough and that they can do whatever they want. So many of our guys were killed by them on the road between Vegas and The Wind... Oh... Let's drink for them! [He chugs half a bottle of beer]}
{117}{}{Hey! Isn't it too much?}
{118}{}{It's all right, mate! [He burps]}
{119}{}{You already look groggy!}
{120}{}{Ha-ha-ha! Even drunk, I'd knock down anyone! Wanna bet? You won't beat me too!}
{121}{}{Hey! Stop it!}
{122}{}{Ha-ha-ha! Don't be afraid, buddy! [He slaps your shoulder] for you, I'd slaughter everyone! Want me to knife the bartender?!}
{123}{}{Uh... No. I still need him.}
{124}{}{Well... Yeah, he gives me beer too... Yep. Ohkay.}
{125}{}{Gives? Just like that? For free?}
{126}{}{Ha! What's the matter, buddy?! Don't you know who you're talking to?! [weighty pokes himself in the chest with his thumb] Do you realize WHO is in front of you?!}
{127}{}{Yes. The crank who escaped the death penalty.}
{128}{}{Uh, no! Hal Wallace himself stands for me. Himself! Personally. He would have saved me from the prison, I'm sure.}
{129}{}{Wow! The owner of this casino?! Why is that?}
{130}{}{Ha! Right, like I'd tell you that!}
{131}{}{I won't tell anyone!}
{132}{}{No! Don't even ask!}
{133}{}{Oh, come on! I've rescued you!}
{134}{}{Damn! Right... Okay! If it's you - I'm... This, what it's called...}
{135}{}{A bodyguard?}
{136}{}{What? The hell with bodyguard! No...}
{137}{}{An administrator?}
{138}{}{Eh?! No, wait... I'm... I'll remember...}
{139}{}{Clerk? Warehouseman? Cleaner? Masseur? Who?!}
{140}{}{Hey, stop it! Let me think!... Ah, yes! A courier!}
{141}{}{A courier? Took you quite long to remember. What's so mysterious about it?}
{142}{}{Well, you know, it gets me places. You'd better not to know the details. Dangerous places. Outside the city.}
{143}{}{Now you're being cunning... As if there are people living outside the city.}
{144}{}{No, they don't live there. But they make some money there... [winks and sips the second half of beer]}
{145}{}{Oh, that's my department! Where is it? Where can I make money?}
{146}{}{[Not hearing you] Ah, hell, it's empty. Hey! Bartender! Give me beer! Now!}
{147}{}{[Continue]}
{148}{}{What are you babbling about, you?! You won't give me a beer?! I'm not asking you, I order you!}
{149}{}{Hey, calm down. Let me order you a bottle. Bartender! Put it on my tab!}
{150}{}{[Leave them alone]}

{151}{}{Pal... No - friend! Yes! Friend, you helped me out once again [hic]. This big-eared creep always refuses to serve me after the second bottle... Oh, yeah, where were we?}
{152}{}{The spot outside the city, where one can make some money...}
{153}{}{Ah, yes! There, in the lab, is so much money being made, oh my gosh! You wouldn't believe it. For one delivery... [looks like he'll falling asleep] for a single delivery I get... I... Get... Zzzz...}
{154}{}{[You won't get anything from him now]}

{200}{}{Yeah, take care.}
{201}{}{Friend, you said you work for the casino owner. Could you recommend me to him?}
{202}{}{[Nervously looks around] Uh, listen, here's my advice- go work as a janitor. At the Hoover dam, for example. There are not enough slaves. Mr. Wallace needs experienced people, you don't look like you are one.}
{203}{}{Am I that bad? Oh, well...}
{204}{}{[Nervously looks around] Look, I'll tell you - Mr. Wallace offers... a "dirty" kind of work, not for those who keeps their hands clean. You understand, right? [He strangely winks at you]}
{205}{}{I'm ready for any kind of work.}
{206}{}{Then I will refrain. Bye.}
{207}{}{Damn. Okay, on my responsibility. Mr. Wallace is on the third floor. Go to his guards and tell them [he takes an important and pompous look] that Sam Riley himself recommended you.}
{208}{}{Thanks, man!}
{209}{}{Thank you doesn't pay the bills.}
{210}{}{Right, here's 50 bucks.}
{211}{}{Say what?! I saved your ass, what else do you need?}
{212}{}{Uh, okay. But now we're even - you saved me, and I introduced you to Mr. Wallace. [He smiles and winks at you; something tells you that it won't going to be so simple.]}
{213}{}{Oh... Okay, bye.}
{214}{}{[Takes the money] Okay, we do great together. I want to warn you as a friend. Mr. Wallace does not like an empty talk. If he asks you to do something, do it, no questions. Otherwise... [moves his thumb across his throat]}
{215}{}{Understood.}

#Women's replics
{1104}{}{Hello there, friend!}
{1110}{}{Heh-Hey! My girl! There you are! I knew you would come here! Let me buy you a drink! Hey, bartender! Put it on my tab!}
{1112}{}{No way! Those military idiots are afraid of even coming near Vegas! Don't worry, baby! We're safe here.}
{1118}{}{It's all right, babe! [He burps]}
{1122}{}{Ha-ha-ha! Don't be afraid, my girl! [He slaps your shoulder] For you, I'd slaughter everyone! Want me to knife the bartender?!}
{1126}{}{Ha! What's the matter, baby girl?! Don't you know who you're talking to?! [weighty pokes himself in the chest with his thumb] Do you realize WHO is in front of you?!}
{1133}{}{Oh, come on! I've rescued you!}
{1151}{}{Friend... No - sister! Yes! Sis, you save me again. This big-eared creep always refuses to serve me after the second bottle... Oh, yeah, where were we?}
{1205}{}{I'm ready for any work.}
{1207}{}{Any work? Seriously? [estimates you from head to toe] For such legs Mr. Wallace will surely find a pair of shoes... With *killing* heels, if you know what I mean. Mr. Wallace is on the third floor. Tell his guards [makes very important and pompous look] that Sam Riley recommended you.}
{1211}{}{Say what?! I saved your ass, what else do you need?}
{1212}{}{Uh, okay. But now we're even - you saved me, and I introduced you to Mr. Wallace. [He smiles and winks at you; something tells you that it won't going to be so simple.]}
