{100}{}{You see an old acquaintance.}
{101}{}{You see the prisoner from the Wind of War!}

#Different things
{102}{}{You have got a hint of the existence of the secret laboratory outside the city.}
{103}{}{Hrrm... Yah... It will be the drunkest state in America... Hrrm...}
{104}{}{Hello there, friend!}

#First dialogue [booze] 
{110}{}{Heh-Hey! Man! Here you are! I knew you would come here! Let me get you a drink! Hey, bartender! Put it on my tab!}
{111}{}{So, you managed to escape from the Wind of War. Won't they look for you?}
{112}{}{Hey! Those troopers are afraid of even coming near Vegas! Don't worry, buddy! We're safe here.}
{113}{}{They are not very liked here in Vegas?}
{114}{}{They are *hated* here. These bastards are being kicked out from the Clean City immediately at the gates.}
{115}{}{What's the reason?}
{116}{}{That's because they think they are tough and that they can do anything. So many of our guys got killed by them on the road between Vegas and the Wind... Oh... Let's have a drink over their grave! [chugs half a bottle of beer]}
{117}{}{Hey! Isn't it too much?}
{118}{}{It's all right, mate! *burps*}
{119}{}{You already look groggy!}
{120}{}{Ha-ha-ha! Even drunk I'd knock down anyone! Wanna bet you won't stand too?!}
{121}{}{Hey! Stop!}
{122}{}{Ha-ha-ha! Don't be afraid, buddy! [taps you on the shoulder] in your honor, I'd slaughter everyone! Want me to knife the bartender?!}
{123}{}{Uh... No. I still need him.}
{124}{}{Well... Yeah, he gives me beer too... Yep.}
{125}{}{Gives? Just like that? For free?}
{126}{}{Ha! What's the matter, buddy?! You know *who* you're talking to?! [weighty pokes himself in the chest with his thumb] WHO is in front of you?!}
{127}{}{Yes. The crank who escaped the death penalty.}
{128}{}{Uh, no! Hal Wallace himself stands for me. Himself! Personally. He would have saved me from the prison, I'm sure.}
{129}{}{Wow! The owner of this casino?! Why is that?}
{130}{}{Ha! Right, like I'd tell you just like that!}
{131}{}{I won't tell anyone!}
{132}{}{No-no-no! Don't even ask!}
{133}{}{Oh, come on! I've saved you!}
{134}{}{Damn! Right, okay! If it's you, I confess - I'm... This, what it's called...}
{135}{}{Bodyguard?}
{136}{}{What? The hell with bodyguard! No...}
{137}{}{Administrator?}
{138}{}{Eh?! Hey, don't confuse me... I'll remember...}
{139}{}{Clerk? Warehouseman? Cleaner? Masseur? Who?!}
{140}{}{Hey, stop it already! Let me remember!.. Ah, Yes! A courier!}
{141}{}{Courier? Took you quite long to remember. What's so mysterious about it?}
{142}{}{Well, you know, it puts me in such places. You'd better not to know. Outside the city.}
{143}{}{Now you're being cunning... As if there are people living outside the city.}
{144}{}{No, they don't live there. But there you can make some money... [winks and sips the second half of beer]}
{145}{}{Oh, that's my department! So where is it, where can I make money?}
{146}{}{[Not hearing you] Ah, hell, it's over. Hey! Bartender! Give me beer! Now!}
{147}{}{[Continue]}
{148}{}{What are you babbling about, you?! You won't give me beer?! I'm not asking you, I order you!}
{149}{}{Hey, calm down. Let me order you a bottle. Bartender! Put it on my tab!}
{150}{}{[Leave them alone]}

{151}{}{Pal... No - friend! Yes! Friend, you save me again. This eared creep always refuses to serve me after the second bottle... Oh, yeah, where were we?}
{152}{}{On the spot outside the city, where one can make some money...}
{153}{}{Ah, yes! There, in the laboratory, such big money's being made, oh gosh! For one serving... [looks like he'll be asleep soon] for a single dose they receive... Dose... Zzzz...}
{154}{}{[You can't hook out anything from him now]}

{200}{}{Yeah, take care.}
{201}{}{Friend, you said you work for the casino owner. Could you recommend me?}
{202}{}{[Nervously looks around] Uh, listen, my advice to you - go to work as a janitor. At the Hoover dam, for example, there are not enough slaves to do the work. Mr. Wallace needs experienced people, you don't look like you have a proper level of expertise.}
{203}{}{Am I that bad? Oh, well...}
{204}{}{[Nervously looks around] Look, I'll tell you seriously - Mr. Wallace offers... *tough* work, not for those who like their hands clean. You understand, right? [strangely winks at you]}
{205}{}{Okay, I'm ready to do any work.}
{206}{}{Then I will refrain. Bye.}
{207}{}{Damn, you're taking a responsibility, you understand? Mr. Wallace is on the third floor. Visit his first guard and tell him [makes very important and pompous look] that Sam Riley recommended you.}
{208}{}{Thanks, man!}
{209}{}{Thank you doesn't pay the bills.}
{210}{}{Hmm, okay, here's 50 bucks.}
{211}{}{Say what?! I saved your ass, what else do you want?}
{212}{}{Uh, okay. But now we're even - you saved me, and I introduced you to Mr. Wallace. [smiling and winking at you somewhat slyly; something tells you that this is not good]}
{213}{}{Oh... Okay, bye.}
{214}{}{[Takes the money] Okay, we can work together. I want to warn you as a friend. Mr. Wallace does not like unnecessary talk. If he asks you to do something, don't ask any questions. Just do it, otherwise... [moves his thumb across his throat]}
{215}{}{Understood.}

#Women's replics
{1104}{}{Hello there, friend!}
{1110}{}{Heh-Hey! Gal! Here you are! I knew you would come here! Let me get you a drink! Hey, bartender! Put it on my tab!}
{1112}{}{Hey! Those troopers are afraid of even coming near Vegas! Don't worry, girl! We're safe here.}
{1118}{}{It's all right, babe! *burps*}
{1122}{}{Ha-ha-ha! Don't be afraid, girl! [taps you on the shoulder] in your honor, I'd slaughter everyone! Want me to knife the bartender?!}
{1126}{}{Ha! What's the matter, girl?! You know *who* you're talking to?! [weighty pokes himself in the chest with his thumb] WHO is in front of you?!}
{1133}{}{Oh, come on! I've saved you!}
{1151}{}{Friend... No - sister! Yes! Sis, you save me again. This eared creep always refuses to serve me after the second bottle... Oh, yeah, where were we?}
{1205}{}{Okay, I'm ready to do any work.}
{1207}{}{Any work? Seriously? [estimates you from head to toe] For such legs Mr. Wallace will find a pair of shoes... With *killing* heels, if you know what I mean. Mr. Wallace is on the third floor. Visit his first guard and tell him [makes very important and pompous look] that Sam Riley recommended you.}
{1211}{}{Say what?! I saved your ass, what else do you want?}
{1212}{}{Uh, okay. But now we're even - you saved me, and I introduced you to Mr. Wallace. [smiling and winking at you somewhat slyly; something tells you that this is not good]}
