{100}{}{You see Oscar Davis.}
{101}{}{You see Oscar Davis, chief of the police. So says the name badge on his chest.}

#Íà÷àëüíûå âîïðîñû:
{110}{}{So, citizen. I am listening.}
{111}{}{I did nothing. I'm leaving.}
{112}{}{Do you know that Hal Wallace was involved in dirty business?!}
{113}{}{Mr. Davis, I'm looking for a job. Could you help me?}
{114}{}{One of your policemen attacked me. It's outrageous!}
{115}{}{I'm looking for the coordinates of Area 51. Could you possibly know where it is?}
{116}{}{Regarding the problem with ghouls.}
{117}{}{About the "black" market chems.}
{118}{}{Regarding the problem with Sam Phillips.}
{119}{}{I'm curious - why the mayor hired *me* as a private investigator?}

#Ìýð íàíÿë ÷óçà:
{120}{}{Private investigator? I didn't think there is such thing in the wasteland.}
{121}{}{I think he doesn't trust you and thinks you're a piece of shit, not capable of doing a job well. But he recognized me as specialist!}
{122}{}{I think the mayor doesn't trust you. Don't you think so?}
{123}{}{Yes, it happens sometimes. See you later.}

{124}{}{Do not celebrate too soon, Mr. Arrogance. Let's see how much shit will fly out of you on the pillar of shame.}
{125}{}{Pillar of shame? You will not drag me there! Hell no!}
{126}{}{Whoa, okay, I get the point. It's all good, Mr. Davis. No problem.}

{127}{}{You should think about whether he trusts *you*. We, at least, have long been engaged in the maintaining order in the city...}
{128}{}{I'm investigating latest crimes in the city. The mayor believes that they are all connected. Could you tell me the details?}
{129}{}{The city has a lot going on right now. }
{130}{}{In recent years, the drug traffic has increased. There is clearly a laboratory in the city, but we have not been able to find it.}
{131}{}{}
{132}{}{Sam Phillips is charged with the production of drugs. }
{133}{}{The freaks are accused for the production and distribution of drugs. }
{134}{}{The freaks are accused for the production and distribution of drugs, but our squad has already eliminated this threat. }
{135}{}{There is also a separate problem with the lost daughter of a local archivist. }
{136}{}{I think this is all.}
{137}{}{Recently, someone has been shot from Bob Neil's pistol. Bob Neil was sent to prison.}
{138}{}{Recently, the Clean City has buried Hal Wallace. May he never be forgotten.}
{139}{}{Thanks for the info. Another question.}
{140}{}{Thanks for the info. That's all.}

#Ïðî Óîëëèñà
{150}{}{You are aware of responsibility for what you've said?}
{151}{}{Of course, he tried to convince me to set up the freaks... Er, I meant ghouls, with drugs. This conversation is recorded.}
{152}{}{Of course. I have proof - here's a record made during the conversation, when he tried to push me to commit a crime against Bob Neil.}
{153}{}{Perhaps I'm not ready. Another question.}
{154}{}{Perhaps I'm not ready to take responsibility. Take care.}

{155}{}{I will look into this recording. But I can't promise anything.}
{156}{}{I don't trust you! This is a lie! Give me back the proof, you damn cop!!!}
{157}{}{Will I be rewarded?}
{158}{}{This is good. I hope, justice will prevail.}

{159}{}{No.}
{160}{}{Shame. Too bad.}
{161}{}{This is a major proof. Well, let me have the holodisk, I need some time to study it.}
{162}{}{I don't believe you! You're lying!}
{163}{}{No, I cannot give you the original recording.}
{164}{}{Oh sure. Here's the record. I hope it will not disappear in your hands.}
{165}{}{Thank you, citizen. We will make a decision, but it will take time.}
{166}{}{Whatever you say. I only hope for the criminals to be punished.}

{167}{}{Citizen, I'm not asking you. Do you understand what I'm talking about? Think again about your refusal.}
{168}{}{You're threatening me! Well, then *try* to take the evidence from me, cop!}
{169}{}{Sorry, Mr. Davis. I did not immediately get the point. Here is the holodisk.}

#Ïðî êîïîâ-êèëëåðîâ
{170}{}{[Mockingly] Tsk, tsk, tsk. You don't say? A killer cop?! That's new.}
{171}{}{Whatever you say. Another question.}
{172}{}{Well then, I'm sorry to bother you.}
{173}{}{I'm not here to play games. Do you think it's nice to be poked in the face with the barrel of a revolver?!}
{174}{}{Perhaps it was inspector Callahan. Well, it's the specifics of his work - sometimes he goes too far. To be honest, his methods previously saved many lives, but are a bit outdated nowadays. I will raise the issue of dismissal of the inspector, and take my apology for the inconvenience.}
{175}{}{And I think that your words are not very sincere. I will say this only once - no one will stand in my way. Remember that, Davis. See you around.}
{176}{}{Okay, then I'll leave you alone.}
{177}{}{Is that all what can you say!? I'm not leaving until you confess, that you put a hit on me!}
{178}{}{Insulting a representative of authorities, defamation of the police and ignorant behavior - as for me, this is enough to apply force. [leans to you and says through clenched teeth] You want it? Just give me a reason!}
{179}{}{Oh wow, threats from the chief of police! What an irony! You would better clean the dust of your badge first, asshole, and pulled your pants up, then speak for the authorities.}
{180}{}{[Angry and turns red] Last warning!}
{181}{}{Dare to assault an unarmed person in front of everyone?! Well, go ahead! Do it! Show me what you got, you fat piece of shit in uniform!}
{182}{}{Come on! I'm just kidding...}

#Ïðî âûðîäêîâ
{183}{}{Yes, there is such a problem. Damn degenerates!}
{184}{}{I came to prove their innocence. I have evidence, that they have been set up.}
{185}{}{I managed to force Larry Geller to confess. Here is the holodisk with recorded conversation.}
{186}{}{I want to testify that they distribute drugs! You could check it now! They have whole packs of drugs laying in boxes. I can show it.}
{187}{}{Could you give me more info on this conflict?}

{188}{}{It's simple. The scums produce a powerful drug and distribute it around the city. The only problem is that we still couldn't catch them in the act. But we will. Be sure about it.}
{189}{}{Perhaps this is all I wanted to know about them.}
{190}{}{Another protector of wild animals! How are you going to do that, eh?}
{191}{}{Read this. I think, identifying the handwriting won't be that difficult.}
{192}{}{Tell your pets that they can continue to stay in this city... For now. But someday I'll get to the bottom of this. And then nothing will save them, even this miserable piece of paper! [angrily squeezes a document in the hands]}
{193}{}{What did you say about pets, eh?! I will show you a pet, fucking asshole with a badge!}
{194}{}{That's better!}
{195}{}{Come on, don't be so upset! They're good guys! You'll see.}

{196}{}{Very good news! Finally, we will end with this plague in the city. And citizens like you are usually being rewarded by more sonorous means. [hands you 2000$] Here's your payment.}
{197}{}{You are preparing a raid on them, aren't you? I want to participate!}
{198}{}{Thanks for the money.}
{199}{}{An extra gun will come in handy. I don't mind. We are heading out right now. Are you ready?}
{200}{}{Sure! Let's do it!}
{201}{}{Hell no. You'll have to go without me. Good luck!}
{202}{}{I need only trustworthy people. Sorry, citizen.}
{203}{}{Too bad.}
{204}{}{I'm so glad to hear this, that I won't even ask, how you got this. Finally, we will end with this plague in the city. And citizens like you are usually being rewarded by more sonorous means. [hands you 2000$] Here's your payment.}

#Ïðî Ñýìà Ôèëëèïñà:
{205}{}{Another splinter on the body of the city. During the search we found a yellow substance, presumably a component for drugs. Although our experts have not yet determined the exact purpose of it.}
{206}{}{Yes, this is clearly a component. Here, look. It is delivered to Phillips by a drug dealer from Salt Lake.}
{207}{}{This is a emulsifier E30 - a dietary supplement. Nothing more.}
{208}{}{Can I help in this case as a private investigator?}
{209}{}{He is not guilty! He is a good man!}
{210}{}{I hope you will solve this problem. I have to go.}
{211}{}{Why are you so sure, citizen?}
{212}{}{Erm, well I just know it. Isn't that enough?}
{213}{}{Well I'm not sure.}
{214}{}{Don't make me laugh. We will not run after Phillips just because someone out there has decided to file a complaint against him. FACTS! We need evidence!}
{215}{}{Okay.}
{216}{}{Here is an emulsifier - Is this the substance that you had found? It's just a food supplement!}

{217}{}{Very good. Maybe you, as a civilian, will be able to gain trust of Phillips and his people. Then we'll get a chance to deal with the criminal, fairly and openly.}
{218}{}{Good. I will look into the situation. Will I be rewarded for my assistance?}
{219}{}{Good. I will look into the situation.}
{220}{}{You?! To make things even worse? Mind your own business, citizen.}
{221}{}{Fine.}
{222}{}{Sure, we'll pay for good work.}
{223}{}{Okay then. I'll start working.}

{224}{}{Food supplement?! This will not work on me! It's just silly! I am not so blind, not to distinguish the drug from food!}
{225}{}{It seems that so much.}
{226}{}{Well, if you're so sure, then of course.}
{227}{}{This evidence is enough, I suppose. We will keep your incognito. And Sam Phillips will be arrested soon. Thank you for your assistance to the investigation. You earned an increased reward. [gives 2000$]}
{228}{}{Money is good.}

#Ïîèñê ðàáîòû:
{229}{}{You're not from around here? Then we could make a deal.}
{230}{}{I'm listening to your offer.}
{231}{}{You know, I changed my mind. See you.}
{232}{}{I have no suggestions for you. Also, I will say that it's generally difficult to find a job in the city.}
{233}{}{Another question then.}
{234}{}{Then forget it. See you.}
{235}{}{We do have one unresolved matter, still without a final decision. The case of Sam Phillips, head of the "Hard Rock" cafe.}
{236}{}{What did he do?}
{237}{}{He is accused of producing and distributing a monstrous drug. We know this thanks to some circumstantial evidence, but I am fully convinced that it's true. Especially after we found a very dubious substance in his cafe.}
{238}{}{You want me to investigate on the whereabouts of his laboratory?}
{239}{}{Basically, the laboratory won't last without its owner. We should deal with Sam Phillips himself.}
{240}{}{So you're asking me to find evidence on him?}
{241}{}{I don't care how, by this point, but we must stop this man! At any cost... Do you understand?}
{242}{}{Oh! I see where this is going! You should've said that in the first place - just kill the poor guy for nothing. I'll pass.}
{243}{}{Well, sometimes criminals should be punished even by unlawful means. I'll help you find the dirt on the man.}
{244}{}{Very well. I'll be waiting for good news.}
{245}{}{Well then, I'll go on my mission.}

#Çîíà 51
{246}{}{Area 51? No, I don't know. But I can tell who possess such information ... If we can make a deal.}
{247}{}{And how can we make a deal?}
{248}{}{There's something I don't like about your wickedness. Forget it.}
{249}{}{Surely no! I stay away from shady business. I pass.}
{250}{}{I would appeal to the local archive in the town hall. You can't do that yourself - you don't have the access. But the info is not for free, do you understand?}
{251}{}{Uh, sure. How much do you want for the information?}
{252}{}{Money? No, I do not have them.}
{253}{}{For 1000 I can get you the coordinates right now.}
{254}{}{Great! Here is the money. I'll wait here.}
{255}{}{I'll go get the money then.}
{256}{}{}
{257}{}{It was easy. Archivist was free and found the coordinates in a few minutes. Here is the result. [you enter the coordinates into your Pip-Boy]}
{258}{}{Thanks. That is exactly what I needed.}

{259}{}{For your assistance with the case of Sam Phillips, I will be more than happy to help. Area 51? No problem. But you have to wait a little.}
{260}{}{Sure.}
{261}{}{When you solve our problem with Phillips - then you get the desired coordinates.}
{262}{}{Damn. Can't we make a deal another way? Too bad.}

#Íàðêîäåëà â ãîðîäå
{263}{}{It's pretty bad. There is a drug laboratory operating in the city, but we are unable to locate it. Some shady business. If you find anything out - tell us, and we will take action immediately.}
{264}{}{No problem! The drug lab is done for.}
{265}{}{Oh, this is good news! Great work, Mr. Davis!}
{266}{}{I'm sorry to hear that, Mr. Davis. I hope you will figure it out.}

{267}{}{I want to help with the investigation. I accidentally learned about the existence of the Black Caravan...}
{268}{}{I can help you. It just so happened that I found a drug lab...}
{269}{}{Excellent work, citizen! You were right to tell me. The Black Caravan will be arrested immediately, our squad is on the way. Bastards will give us the location of the lab, I'm sure. Well, you earned a reward. I think I even add something from myself, for the risk. Here is, 2000$.}
{270}{}{Great payment!}
{271}{}{Great news, citizen! We will immediately send everyone who can stand on their feet. But we can't let go the likes of you... Not before rewarding. Relax, this is for you.}
{272}{}{Wow, thanks for the payment!}

#Female character
{1111}{}{I did nothing. I'm leaving.}
{1124}{}{Do not celebrate too soon, Mr. Arrogance. Let's see how much shit will fly out of you on the pillar of shame.}
{1153}{}{Perhaps I'm not ready. Another question.}
{1154}{}{Perhaps I'm not ready to take responsibility. Take care.}
{1169}{}{Sorry, Mr. Davis. I did not immediately get the point. Here is the holodisk.}
{1184}{}{I came to prove their innocence. I have evidence, that they have been set up.}
{1189}{}{Perhaps this is all I wanted to know about them.}
{1229}{}{You're not from around here? Then we could make a deal.}
{1231}{}{You know, I changed my mind. See you.}
{1238}{}{You want me to investigate on the whereabouts of his laboratory?}
{1245}{}{Well then, I'll go on my mission.}
{1267}{}{I want to help with the investigation. I accidentally learned of the existence of the Black Caravan...}
{1268}{}{I can help you. It just so happened that I found a drug lab.}
