{100}{}{You see Sam Phillips.}
{101}{}{You see Sam Phillips, the owner of "Hard Rock" cafe.}

{110}{}{[Sighs] what is it about, young man?}
{111}{}{I got here by accident, and certainly not for ceremonious talk. I'm out of here.}
{112}{}{Sorry to bother you.}

####################################################################
#              Б. Луи как джазмен
####################################################################

{113}{}{I see you have an empty stage. Why?}
{114}{}{It's quite difficult to find a good artist. You know - now is not the time for entertainment.}
{115}{}{I know a great jazzman from Reno...}
{116}{}{Have you tried to do the casting?}
{117}{}{How many people have you auditioned over the years?}
{118}{}{Yes, I understand. Well, good luck to you.}
{119}{}{Yes, no performer will stay in your shithole! Me included.}

{120}{}{We tried it a few years ago. We found some good guys then, but the fame crippled all of them... If you know what I mean.}
{121}{}{Three people each year. We don't get more than that. They mainly perform gangster songs and blues, that are the most simple and accessible for performers.}

{122}{}{Jazzman? Are you serious?! Hmm... You know, I am little scared that he's from Reno. How good is he?}
{123}{}{Honestly, I somehow missed his tour.}
{124}{}{I'm sure - he is the one you need!}
{125}{}{What's the difference? Just audition him and decide for yourself.}
{126}{}{Actually, I don't know, I'm sorry to bother you.}

{127}{}{Is that so? Listen, I do not want to waste my time on people useless for me and my place. Bye.}
{128}{}{Damn. Well, maybe you can change your mind...}
{129}{}{Hmm... We can try... Just from our respect to you.}
{130}{}{Great!}
{131}{}{It's important to me - I can only rely on those who can be trusted. All workers in this cafe are employed only by someone's recommendation. I don't want idiots on stage and hassle coming with them. Take care.}

{132}{}{Well, we can listen to your friend... Since it's *you* who recommends him.}
{133}{}{How cute. But, you see, I can only rely on those who can be trusted. All workers in this cafe are employed only by someone's recommendation. I don't want idiots on stage and hassle coming with them. So all the best to you and your acquaintance.}

{134}{}{Well, okay. Bring him to the cafe and we'll have a look. I trust you, don't disappoint me.}
{135}{}{Sure! I'll go tell him this great news.}

{136}{}{Cafe owner is ready to audition Big Louie. All left is to tell the news to musician now.}

####################################################################
#              Квест на поиск оправдания
####################################################################

{150}{}{You look upset. What happened?}
{151}{}{[Waves his hand] Sorry, I have a lot of bad things happening to me right now, but it doesn't concern you, I just can't concentrate on my work... What did you want?}
{152}{}{Let's go back.}
{153}{}{In fact, nothing.}
{154}{}{And yet - perhaps you need help?}

{155}{}{You know, certainly not from you. My situation is too uncertain and dangerous, I'm afraid, you will only make matters worse.}
{156}{}{Well whatever you say.}
{157}{}{I have no choice in my position. My friends afraid to interfere, and you're a new man, you may be able to find out, who did it... If you, of course, believe me. And if not - then join the camp of my enemies, there is plenty of space for you.}
{158}{}{I see, that you're a good man without dirt in his heart. That's why I will help you anyway.}
{159}{}{I'll pass then.}

{160}{}{[Sighs] Thank you, but I wasn't always such a good person, I have a lot of history with drugs behind me. And the past, like a nightmare, showed itself again.}
{161}{}{What happened?}
{162}{}{I was framed. Someone told the police that I buy poison from which my clients die. Cops turned the cafe upside-down, found all kind of additives and left - supposedly, for tests. But who will test them, really? These idiots won't tell sodium from marijuana! They don't realize that it's just a salt.}
{163}{}{Why are they so sure?}
{164}{}{I don't know. They have false evidence and it seems no one cares to figure it out. The last days I live under the fear of prison or the death penalty.}
{165}{}{And you really bought a batch of dope?}
{166}{}{No! I work only with a few caravans, most of them are working for "Monte". But, basically, Bob brings all needed goods.}
{167}{}{Where can I find him?}
{168}{}{Bob? He always hangs around the caravan parking lot.}
{169}{}{Who could have set you up?}
{170}{}{I don't know. I think, just any competitor. After all, there are not so many people that have been able to rebuild the old venues and get them to profit the city. I can't say anything more.}
{171}{}{All of this is very vague. Well, let's see what we can do.}

{172}{}{About your problem with the police - it's all settled. Well, at least you have been proved innocent, but who did this is still a mystery to me.}
{173}{}{It wasn't so simple, was it? I know already, by the way. The police contacted me and told me everything, with apologies. You saved me! I lost all hope and was ready to go to prison. You know, I think you earned this. Here, take it. [gives 1000 bucks]}
{174}{}{Oh! It was worth it!}
{175}{}{Regarding your enemies. It turns out that "evidence" was planted by one of the competitors - the owner of the "Monte" casino.}
{176}{}{My God! I did not think Hal is so greedy... Well, I will not grieve if he gets his due. I did not get into his business and will not do so in the future, especially for the purpose of revenge. Thanks for telling.}
{177}{}{You're welcome.}

{178}{}{What can you tell me about this substance? Caravan admitted that he delivers you to the party this rubbish...}
{179}{}{Oh, you too... Police didn't understand either. This is for pizza. In our time it is not so easy to find a handful of grain to make normal dough, so we make it from all sorts of things - from cardboard, for example. And so the dough was so tough that we had to add emulsifier E30. This particular substance is being extracted from the depths of the Salt Lake and somehow it enriches the taste... A harmless thing, but it is better not to try separately, otherwise you will be obliged with the night in the toilet.}
{180}{}{Hmm...}

####################################################################
#              Про колу - получение квеста
####################################################################

{200}{}{I'm the official courier of the Nuka-Cola factory in Salt Lake. Would you be interested in buying from us?}

{201}{}{I'd love to, but I cannot. We have big problems in the cafe. It is possible that we enter into this transaction and there will be no one to deal with soon. Let's not take chances now.}
{202}{}{May I know, what is the problem?}
{203}{}{Wow, sorry, sure no need for that.}

{204}{}{Hmm... Perhaps. My problems have been solved, so we may take the risk. But can I see your papers?}
{205}{}{Sure. Here is the license.}
{206}{}{I don't have them on me. I'll bring them later.}

{207}{}{Er... No. Don't ask, why. I have my reasons... A few of them. But still don't ask!}
{208}{}{I hope, you will change your mind.}

{209}{}{I can't take a risk, especially after all this problems I went through. It's not about you, please understand, I'm just in time of uncertainty. I need to be completely sure in you merchandise. So bring your license, then we can make a deal.}
{210}{}{Fine.}

{211}{}{[Carefully studies the papers] Very good. [nods] Very. This is what I needed - confidence in my partner. We will cooperate with you.}
{212}{}{Great!}
{213}{}{Let's do this - I will order a vending machine set for the sale of the beverage. This will simplify our business. You can monitor the process through the software in the machine. But keep in mind - we're not going to take care of your product before it is in stock. Any issues about the deliveries you figure out on your own.}
{214}{}{I'll deal with this... Are you excited about our collaboration?}
{215}{}{Excellent. Let's get strait to sealing the contract.}

{216}{}{Very! Finally, we will be able to outdo this arrogants in Clean City.}
{217}{}{Who?}
{218}{}{If you have not noticed, the "Monte" casino has signed a contract with the same factory that you work with. It is our - and your - competitor. Funny, isn't it?}
{219}{}{Funny that I'm working with my own competitors? Huh...}
{220}{}{As long as the casino functions, you'll have to share with them the market in Vegas... Where was I? Oh yeah! I suggest signing the contract, partner!}
{221}{}{Sure, partner!}

{229}{}{Great deal. We'll work well together. Come tomorrow, I think we can set up a vending machine by that time. But first, take care of the availability of goods in stock. Have a nice day.}
{230}{}{Sure! Have a nice day, Mr. Phillips!}

#Female character
{1110}{}{[Sighs] what is it about, ma'am?}
{1120}{}{His name is... Er... I don't know myself, but he's a talent, trust me.}
{1123}{}{Honestly, I somehow missed his tour.}
{1124}{}{I'm sure - he is the one you need!}
