{100}{}{You see Hal Wallace.}
{101}{}{Here is none other than the owner of "Three Card Monte" himself.}
{102}{}{Killer in the office!!!}

#С'ар'овая ве'ка:
{107}{}{You don't say...}
{108}{}{Guards! Take this trash out of the office!}
{109}{}{Who?! Me? He made a mistake! I want to get out of here.}
{110}{}{The guard said you want to see me?}
{111}{}{Yes. I want to work for you!}
{112}{}{Oh, sorry, wrong door.}
{113}{}{Where the guards are looking?! Immediately take him out into the corridor!}
{114}{}{No! Wait...}

#Квес' на выродков:
{115}{}{Yes, there is one job... Not for the faint-hearted.}
{116}{}{What is it?}
{117}{}{Oh, I'm just like that, so I'd better go away.}

{118}{}{You do know who the freaks are, don't you? These ghouls are a pain in the ass. The whole city is suffering because of them and it's uncertain for how long this will continue. We must deal with it.}
{119}{}{Hmm. Something tells me you goals are not entirely righteous.}
{120}{}{What are they guilty of?}
{121}{}{Sure. If you pay, then we must.}
{122}{}{Not ghouls! I don't mess with them!}

{123}{}{I, like the rest of the city, have my reasons, but why do you care? Better concentrate on your own interest.}
{124}{}{[Discreetly turn on the recording on a Pip-Boy] So, what was the job?}
{125}{}{So what was the job?}
{126}{}{If you don't want to be honest with me, then I refuse!}

{127}{}{Of the production and distribution of drugs. I consider their survival techniques simply monstrous. Because of their drugs people break or die. That includes my clients. So, as a respectable citizen, I would like to clean the city of this... Garbage.}
{128}{}{I'm paying 2,500 for this simple task. Big money for the majority of citizens. But so is the risk. You'll have to do it quietly.}
{129}{}{It's simple. I'll give you a drug, it is very powerful. Do not ask where me where it came from. And do not try it, it's a lethal mixture.}
{130}{}{Well, I'll try not to ask questions for now. What next?}
{131}{}{And then everything is simple - quietly and covertly penetrate the hotel of the freaks and place the drug into boxes. After you do that, go to the police station and anonymously pass the information about the evidence to the police chief. He knows what to do.}
{132}{}{Seems easy. Is it risky? Do these freaks have guards?}
{133}{}{How do I sneak inside the building?}
{134}{}{I'll pass! It's too dangerous!}

{135}{}{Well, I was wrong about you. [nods to guards]}
{136}{}{Everybody stand still! I will defend myself!!!}
{137}{}{Freaks do not usually get involved in the fight, they are sitting on a needle so long that they lost most of their health. I think you won't encounter serious resistance. Especially considering they are likely don't expect you.}
{138}{}{It's not up to me. Residents of Clean City rarely go beyond the walls. Deal with it yourself. It's your job.}
{139}{}{Well, the case seems simple. Give me your fake evidence and prepare the money, I'll be back soon.}
{140}{}{Excellent. I am a man of my word. But if you screw up...}
{141}{}{I understand you, Mr. Wallace. Work is work. I will do my job without further ado.}
{142}{}{Hell no! I will not take such shady work!!!}

{143}{}{I will wait for news, partner.}
{144}{}{Okay, Mr. Wallace.}

#Сдача квес'а на выродков:
{145}{}{I'm waiting for *good* news!}
{146}{}{It's done. Drugs are put into the boxes. What remains is only to surrender them to the police.}
{147}{}{It's done. Drugs, as agreed, were planted and the freaks were commissioned to the police.}
{148}{}{The problem with freaks was resolved without drugs. Larry Geller, their leader, is dead.}
{149}{}{I managed to find other evidence and give the freaks to the police, without faking it.}
{150}{}{Sorry, nothing yet.}

{151}{}{Yes, this is what we needed. I'll take it from here. As for you, you did your job. I suppose there's no need to make unnecessary remarks about the importance of silence?}
{152}{}{Of course, Mr. Wallace. Nobody will find out about this incident from me.}
{153}{}{This looks like a threat! It's time to strike first!}
{154}{}{Yes, this is what we need. You performed brilliantly. I suppose there's no need to make unnecessary remarks about the importance of silence?}
{155}{}{But I demanded a different solution... Although, this one will suffice. Without a leader they shouldn't be a threat... Okay, I don't mind. I suppose, there's no need to make unnecessary remarks about the importance of silence?}
{156}{}{Well, I do not mind. One way or another, you did your job. I suppose there's no need to make unnecessary remarks about the importance of silence?}
{157}{}{The reward 2500, as we agreed.}
{158}{}{The amount is good!}

#Получение квес'а на начальника ГЭС:
{159}{}{More work for you.}
{160}{}{I'm listening, Mr. Wallace.}
{161}{}{Hell no! Some dubious affairs are going on here! It's time to end it!}

{162}{}{I came to find out whether there is a "special" task for me.}
{163}{}{There is one man who insulted me greatly. I cannot get back at him openly. I need a compromising material on him.}
{164}{}{Excellent. Who is this person?}
{165}{}{Hell no! I don't do things like this!}
{166}{}{His name is Bob Neil. He is in charge of the local dam. Has very tricky personality, be careful with him.}
{167}{}{Okay. What kind of compromising material you need?}
{168}{}{I need his personal gun. But the Bob Neil must stay alive!}
{169}{}{It will not be easy. Why not to just kill him? Why such complications?}
{170}{}{Okay. I'll do everything.}
{171}{}{A lot of questions always do harm those who ask them.}
{172}{}{Okay. I'll do the job. What is the price of the risk?}
{173}{}{The same - 5000 bucks.}
{174}{}{I'll do it.}
{175}{}{Not enough. It's too dangerous an complicated. 7000, no less.}
{176}{}{You've convinced me. Let's increase the reward up to 7000. I'm not a fan of negotiating the price, but if the issue would be resolved, I am ready to pay.}
{177}{}{Excellent! Prepare the money.}
{178}{}{Greed has brought many people to the gallows. Think about it *now*, before it's too late.}
{179}{}{I got it. I'm sorry, Mr. Wallace. I will fulfill the task by *your* price.}
{180}{}{So you're threatening me!!! The dirt is waiting for *you*, scumbag!}
{181}{}{I do not forgive mistakes. I need Bob's gun, quietly.}
{182}{}{I understood. I will try.}

#Сдача квес'а на начальника ГЭС:
{183}{}{You know what to do. So why are you here?}
{184}{}{Mission accomplished. Here is the gun. Bob Neil is still alive, he knows nothing about our deal.}
{185}{}{Nothing. Just wasting time.}
{186}{}{I've come to say, that I quit this stupid work!}
{187}{}{I've come to say that I was presented with a counter-offer. And I took it.}

{188}{}{And you had the nerve to come back?! Guards!}
{189}{}{But Bob Neil is avenged!..}

{190}{}{I knew I could rely on you. Excellent work. Here's your reward, as we agreed. Well, it was nice to work with you. However, now we part ways. Stay away from the police and the mayor's office, if you do not want the hassle.}
{191}{}{So why you needed the gun? It would be easier to kill the chief...}
{192}{}{So be it.}
{193}{}{Compromising material is supposed to be used *against* Bob Neil. That says it all. How - is not your business.}

{194}{}{I do not like corridor tramps. I advise you to go about your business.}
{195}{}{[Discreetly turn on the recording on your Pip-Boy] Excellent. Who is this person?}

{196}{}{I will fulfill your every order! Are you sure there is no work for me?!}
{197}{}{Sorry, no.}
{198}{}{Shame.}
{199}{}{Why not contact the police directly?}
{200}{}{In America, when something is not in order, the best way to fix is usually the fastest.}

#Женские реплики
{1112}{}{Oh, sorry, wrong door.}
{1113}{}{Where the guards are looking?! Immediately take her out into the corridor!}
{1117}{}{Oh, I'm just like that, so I'd better go away.}
{1141}{}{I understand you, Mr. Wallace. Work is work. I will do my job without further ado.}
{1176}{}{You've convinced me. Let's increase the reward up to 7000. I'm not a fan of negotiating the price, but if the issue will be resolved, I am ready to pay.}
{1179}{}{I got it. I'm sorry, Mr. Wallace. I will fulfill the task by *your* price.}
{1182}{}{I understood. I will try.}
{1186}{}{I've come to say, that I quit this stupid work!}
{1187}{}{I've come to say that I was presented with a counter-offer. And I took it.}
