{100}{}{This is Larry Geller.}
{101}{}{This is Larry Geller, the leader of the freaks of New Vegas, their moral and spiritual support.}

{108}{}{ However, I can see from by your face that you also got beaten by a life.}
{109}{}{And here is our smooth-skinned friend... Well, for us, you're still smooth-skinned. But it's a mystery, how they don't shoot you with such a face in the Clean City.}

#Вопросы и первые реплики
{110}{}{You'd better not to wander around here. Our hotel is not that much better than the local cemetery. Ha-ha! Joking. The cemetery is way better...}
{111}{}{Why you walk with bags over your heads? Is that some kind of fashion?}
{112}{}{Do you contact with your neighbors from "Hard-Rock" cafe?}
{113}{}{Do you know anything about the substance called "Emulsifier E30"?}
{114}{}{I'm looking for a guide for the train trip. Can any of you take the job?}
{115}{}{Oops.}

#Ответы на рядовые вопросы
{116}{}{Even if someone would, he wouldn't survive the journey. The health doesn't allow it. Well, unless we drink some of your blood... Ha-ha! Don't worry, I'm joking. We only eat brains...}
{117}{}{Very funny. Another question.}
{118}{}{I think I'll go.}
{119}{}{Emulsifier - some component of a nuclear bomb. A joke. In reality, it's a food supplement. It's some kind of special salt, acid-enriched. It is mined in Salt Lake, in a local lake. Sam Phillips uses an emulsifier to make the pizza dough softer and more tender. His pizza used to be like rubber, you could not cut through it with a knife.}
{120}{}{No. But Sam and I used to be very close. He rubbed my back with a crowbar. Ha-ha-ha! Joking. But he is an unbiased person and always accepted us as we are.}
{121}{}{What can you say about his addiction to drugs? Didn't you ever notice him doing them?}
{122}{}{The city had many problems with drugs. There was a time when Phillips got into the wrong company too. But this is in the past. I'm sure that he is clean and realized his mistakes now.}

#Расспрос про то, кто они такие
{123}{}{Wait, you've never heard of us? You haven't even been warned that you should avoid us? Looks like you're new in town!}
{124}{}{Yes, I am.}

{125}{}{Then know this, they call us "fureecks". We walk with bags over our heads, so you couldn't see us chewing human flesh flesh with our rotten teeth... Ha-ha-ha!!!}
{126}{}{Flesh huh, funny guy. So what is it with your faces?}

{127}{}{With our faces? Oh, wanderer, I can't tell, otherwise you're gonna puke all over the place. Ha-ha!}
{128}{}{Stop trying to scare me, mister walking dead. I've seen worse.}
{129}{}{What?! You're trying to make fun of me, is that it? We're gonna need another bag - to bury your remains, phreek!}
{130}{}{I don't like your jokes. I better go.}

{131}{}{Oh! I see, you're tough one. You can call me Larry. Larry Geller - it's my full name.}
{132}{male}{Hey, you, Larry. What about what's in your pants, is it vomit-inducing too?}
{133}{male}{And what about I cut yours and transplant it to myself? Oh! Then I'll be 50 years younger. Ha-ha-ha!}
{134}{male}{Hold your tongue! The hell you'll cut anything! I'll rather make you eat your own one, before that happens!}
{135}{}{You must be eliminated at once, before others get hurt. Your last words, freek!}
{136}{}{That's some unhealthy humor. I better go outside for some fresh air.}
{137}{female}{Too bad that you don't like my looks, But if you like the roughness - then you're in the right place, baby!}
{138}{female}{Hold your tongue! I would never think, that I would get hit by a dead man!}

{139}{}{About the tongue - you better not say it. I can take it literally... Ha-ha-ha!!!}
{140}{}{So what is your sickness?}
{141}{}{You're very inadequate. It's time to eliminate you!}
{142}{}{Then I'd better shut up and go away.}
{143}{}{So what are you sick of?}
{144}{}{As you wish, Larry. But I will go away now.}

#Получение квеста на поиск оправданий
{145}{}{In fact, we haven't suffered from anything in a long time... Except for a small mental disorder.}
{146}{}{So what is it with your skin then?}
{147}{}{Radiation, friend, radiation. And, apparently, some other shit that flies through the air. The organism ossified, the skin became tough, and the veins lost their elasticity.}
{148}{}{Yeah, I get it. And what now, you hide your faces to not scare any kids or something?}
{149}{}{In Clean City they frighten the kids with us anyway. Like, look, if you won't behave - then a bad freak will come and carry you to Dead hotel. Sometimes, these oafs talk even worse. They think that we are contagious, so they all stay away from us... Mostly.}
{150}{}{What?}
{151}{}{Apparently, someone overdid it and now we are accused of producing drugs. The police even have some circumstantial evidence. I don't know if it's true, but it seems to me, that the police won't look for evidence. They'll just come and shoot us up. I hope that after this our ghosts will haunt them at nights.}
{152}{}{But you don't produce any drugs, right?}
{153}{}{The police is right! You need to be moved to a new place you can stay - under 10 feet of dirt!}
{154}{}{Well, this is not my business. Perhaps, I should go.}
{155}{}{Only medicines from herbs to maintaining our perishable flesh and urination. We have to make powders to expand the venous system. Alas, the police consider this a drug.}
{156}{}{So, are you in death-threatening danger?}
{157}{}{I think so too! And now I will fulfill the will of the lady of Justice!}
{158}{}{I do not know who to believe. Perhaps, I'd better just go about my business.}
{159}{}{If we don't prove our innocence, then the police will come and at best drive us out of the parking lot. And at worst - will take away the medicines and thereby deprive us of the opportunity to piss properly... Ha-ha! Although, we are increasingly arguing - whether they dare to come. Something tells us that they won't.}
{160}{}{Can you prove?}

{161}{}{No. We will never prove our innocence. Especially since we'll soon be hanged for your death as a result of the slow dismemberment... Ha-ha! We wouldn't even be able to bring the evidence to the Clean City - we just will be shot on sight, while walking to the main gate.}
{162}{}{You know, what I think? That justice must prevail! I will try to help you... If you are honest.}
{163}{}{You don't need to go there! I will shoot you all right here!}
{164}{}{Listen, thats your problem, I don't want to have anything to do with it. Thats why I leave.}

#Завершение квеста на поиск оправданий
{165}{}{How noble! So much that I don't even believe it. And that's after I threw a poisonous saprophyte mite in your pocket... Do not search your pants. It was a joke!}
{166}{}{I'm being honest with you. Be honest with me too.}
{167}{}{[Secretly start recording the conversation on your Pip-Boy] I'm being honest with you. Be honest with me too.}
{168}{}{I am also honest... And serious. As much as possible. Yes, we had bad times and once we made powders with much stronger effect. But this is in the past. You must trust us!}
{169}{}{Nobody has to do anything for you just yet, comedian. Okay, I trust you. Then who and why would someone go to police on you? And what are the evidence they have there?}
{170}{}{Not a slightest idea! The evidence is clearly indirect. The chief of police came to us, asked where we get the components, how much dope we make a month... Of course, he did not believe us. I think he is convinced of his rightness and will defend it even if you find evidence of the opposite.}
{171}{}{Well, that isn't much.}
{172}{}{I think you should talk to the police first. I think that they will listen to you. Think of a story so as not to cause unnecessary suspicion. And better kill everyone there and bring their hearts as a sacrifice to our god!!! Ha-ha-ha...}
{173}{}{We'll see.}

{174}{}{[Secretly start recording the conversation on your Pip-Boy] But you don't produce any drugs, right?}

#Оправдание найдено
{175}{}{I found a receipt from the slavers. Here, take a look.}
{176}{}{And do we have to do with it?}
{177}{}{I wanted to ask you the same thing - what do you have to do with it, and on who's orders it was all made?}
{178}{}{Made?! Well-well-well, let's see. [tries to read]}
{179}{}{Dammit! Larry, you should tell me, you can't read. Let me read it for you.}
{180}{}{Thank you. But I can read. I just can't see as well as I used to.}
{181}{}{Enough of excuses. How will you answer to that receipt?}

{182}{}{I will say that you have a direct proof of our innocence in your hands. Although I don't think that the chief of police will be fully convinced. Unless you put a red-hot poker between his legs... In general, it is necessary that someone smooth-skinned and responsible go to him, or else they won't let us into the Clean City.}
{183}{}{Stop! So, what is going on? What is the police have to do with anything?! What the hell have you done?!}
{184}{}{Who could have convince the slavers to do that? Who is your enemy?}

{185}{}{We don't have enemies. Most likely, this is just discrimination based on race.}
{186}{}{Hmmm. I doubt it. It seems to me that someone is deliberately trying to drive you out of this parking lot.}
{187}{}{Well, all right. It's time to go to the police.}

{188}{}{I don't think that we could harm anyone, since we are sitting quietly and won't even fart in our hotel. In general, we should quickly "please" the police chief. If you know what I mean.}
{189}{}{Oh, yes, the police. I'll take the evidence there.}
{190}{}{What?! Why me?! I am also afraid! Here's a flyer, take it yourself.}

{191}{}{Listen! We are not the best inhabitants of the city, we are feared. And we are afraid. But you - you are not. Even the police can't be compared to you! Don't leave us like this! And we will help you in return.}
{192}{}{Okay, okay! I'll take the evidence to the police. I hope they don't shoot me there.}
{193}{}{You wish! I'm not my own enemy! Here, take the evidence and I'm out of here. My job is done.}
{194}{}{How will you help me?}

{195}{}{Well. In the end, we should be grateful even for that. Thank you. I think someone in "Hard Rock" will agree to go to the police.}
{196}{}{Great.}
{197}{}{And what do I get for all the work?}
{198}{}{We spared your life - is that not enough? Ha-ha-ha! Here. That's all we can give you. [Stretches a pack of stimpaks]}
{199}{}{Yeah, thats not much.}

{200}{}{You, wanderer, should be getting in dangerous situation often in the wasteland. May pharmacology help you! Only today - two for the price... Yes for the usual price of course, we all want to eat.}
{201}{}{Stimpak, 5.}
{202}{}{Superstimpak, 3.}
{203}{}{Psycho, 3.}
{204}{}{Anti-smoker, 5.}
{205}{}{Nothing. I will do it for free.}

{206}{}{Okay. As you wish. Just take the evidence to the police. And we will do the rest.}
{207}{}{Great. I'm going.}

{208}{}{It's done! The evidence is delivered, you're now officially innocent.}
{209}{}{I came to tell you that you are justified and can sleep peacefully. The police won't come to you again.}

{210}{}{Thank you. We already had one cop coming here. You saved us from exile. You are a good man. Just like us. Nobody here will ever forget this.}
{211}{}{You promised to reward me for my hard work, did you forget that?}
{212}{}{"Thank you" will be enough.}

{213}{}{All in order. Do not abuse it - my advice to you. Or you'll "fly around" like we do. Ha-ha-ha!}
{214}{}{Funny. You would be good in a variety show, Larry.}

{215}{}{Thank you. We already had one cop with official apologies. Well, as you can see, justice triumphed.}
{216}{}{Right. Take care.}

{217}{}{I see someone purposely trying to remove you from the hotel.}
{218}{}{What about this receipt?}
{219}{}{The smooth-skinned wanderer is with us again! How surprising.}
{220}{}{About the evidence - I can't take it to the police. Look for another way.}

#Плавающие фразки после облавы
{221}{}{What should we do now?}
{222}{}{We won't be able to find a new place to live.}
{223}{}{We are now worse than beggars.}
{224}{}{Damn! I guess that's it...}
{225}{}{Bad luck!}
{226}{}{It's time to say goodbye to our lives.}

#Получение достижения "Знахарь"
{227}{}{How did you learn to make that healing powders?}
{228}{}{It's not that complicated. We are masters of survival. If it not for our knowledge of nature, we would die long time ago.}
{229}{}{Can you teach me making powder and stimpaks?}
{230}{}{Right.}
{231}{}{...but no one knows where this knowledge will later be applied. Don't even think about it. Pride and honor are still alive in this dead body.}
{232}{}{Well look at you talking now!}
{233}{}{With pleasure! I think you will spend this knowledge for the benefit of people.}
{234}{}{Sure. Should we begin?}
{235}{}{Not now.}
{236}{}{}

{237}{}{[Secretly start recording the conversation on your Pip-Boy] What can you tell about his addiction to drugs?}

#Рабочая проблема на дамбе
{238}{}{I see that you are not particularly welcome in this city. Where do you work?}
{239}{}{What do we do? We have no business and no work. He-he.}
{240}{}{So what do you do for a living then?}
{241}{}{Trying to survive. Manage, as we can. We have some crops not far from here, for example.}
{242}{}{What if I offer you a steady and stable job on not so safe, but still guaranteed workplace? Hoover Dam, you may have heard of it...}
{243}{}{Well, if you think about it, we are ready for any work... If they accept us. But they won't.}
{244}{}{They will accept you. Bob Neil is having a bad time now, he's ready to condescend to you... I suppose.}
{245}{}{Well, that would be an acceptable solution for us, yes. But somehow I doubt that this person will want to have business with us. Would you ask him yourself? We are ready, even starting tomorrow!}
{246}{}{Excellent! I'll talk to Bob.}
{247}{}{You persuaded the freaks to go to work for Bob Neil. Hmm... All that remains is to persuade Bob Neil himself!}

{248}{}{Seriously? Just like that, for "thank you", risking your life? Well, then I just can't let you go empty-handed. Here, take it. [gives 2 packs of some kind of colored pills] It's very good... "memory refresher". He-he. I hope you know what I mean.}
{249}{}{Not yet, but I'll figure it out. Thank you!}

#Female character
{1109}{}{And here is our smooth-skinned friend... Well, for us, you're still smooth-skinned. But it's a mystery, how they don't shoot you with such a face in the Clean City.}
{1110}{}{You'd better not to wander around here. Our hotel is not that much better than the local cemetery. Ha-ha! Joking. The cemetery is way better...}
{1123}{}{Wait, you've never heard of us? You haven't even been warned that you should avoid us? Looks like you're new in town?}
{1127}{}{With our faces? Oh, wanderer, I can't tell, otherwise you're gonna puke all over the place. Ha-ha!}
{1166}{}{I'm being honest with you. Be honest with me too.}
{1167}{}{[Secretly start recording the conversation on your Pip-Boy] I'm being honest with you. Be honest with me too.}
{1168}{}{I am also honest... And serious. As much as possible. Yes, we had bad times and once we made powders with much stronger effect. But this is in the past. You must trust us!}
{1191}{}{Listen! We are not the best inhabitants of the city, we are feared. And we are afraid. But you - you are not. Even the police can't be compared to you! Don't leave us like this! And we will help you in return.}
{1193}{}{You wish! I'm not my own enemy! Here, take the evidence and I'm out of here. My job is done.}
{1200}{}{You, wanderer, should be getting in dangerous situation often in the wasteland. May pharmacology help you! Only today - two for the price... Yes for the usual price of course, we all want to eat.}
{1209}{}{I came to tell you that you are justified and can sleep peacefully. The police won't come to you again.}
{1210}{}{Thank you. We already had one cop coming here. You saved us from exile. You are a good person. Just like us. Nobody here will ever forget this.}
{1219}{}{The smooth-skinned wanderer is with us again! How surprising.}
{1245}{}{Well, that would be an acceptable solution for us, yes. But somehow I doubt that this person will want to have business with us. Would you ask him yourself? We are ready, even starting tomorrow!}
{1248}{}{Seriously? Just like that, for "thank you", risking your life? Well, then I just can't let you go empty-handed. Here, take it. [gives 2 packs of some kind of colored pills] It's very good... "memory refresher". He-he. I hope, you know what I mean.}