{100}{}{This is Larry Geller.}
{101}{}{This is Larry Geller, the leader of the freaks of New Vegas, their moral and spiritual support.}

{108}{}{ But I can see by the look on your face that you, too, have had a rough life.}
{109}{}{Here comes our smooth-skinned friend... Well, you're still smooth-skinned to us. But it's a mystery how you, with a face like that, don't get shot in Clean City.}

#Âîïðîñû è ïåðâûå ðåïëèêè
{110}{}{You'd better not to wander around here. Our hotel is not much better than the local cemetery. Ha-ha! Joking. The cemetery is way better, of course...}
{111}{}{Why do you all wear bags on your heads? Is this some kind of fashion trend?}
{112}{}{Do you interact with your "Hard Rock" cafe neighbors?}
{113}{}{Do you know anything about the substance called "Emulsifier E30"?}
{114}{}{I'm looking for a guide for the train trip. Can any of you take the job?}
{115}{}{Oops.}

#Îòâåòû íà ðÿäîâûå âîïðîñû
{116}{}{Even if someone would, he wouldn't survive the journey. Health issues, you know. Well, unless he drinks some of your blood... Ha-ha! Don't worry, I'm joking. We only eat brains.}
{117}{}{Very funny. Another question.}
{118}{}{I think I'll go.}
{119}{}{Emulsifier, yeah... It's a common component of a nuclear bomb. Just kidding. Actually, it's a food supplement. It's some kind of special salt enriched with acid. It's mined in Salt Lake, in a local lake. Sam Phillips uses the emulsifier to make his pizza dough softer and more tender. His pizza used to be like rubber, impossible to cut with a knife.}
{120}{}{No. But Sam and I used to be very close. He used to rub my back with a crowbar. Ha-ha-ha! Just kidding. But he is an unbiased person and always accepted us as we are.}
{121}{}{What can you say about his drug addiction? Have you ever seen him using?}
{122}{}{There were a lot of drug problems in the city. There was a time when Phillips was in bad company, too. But that's all in the past. I'm sure he's clean now, and he's realized his mistakes.}

#Ðàññïðîñ ïðî òî, êòî îíè òàêèå
{123}{}{Wait, you've never heard of us? You weren't even warned that we are to be avoided? Looks like you're new in town!}
{124}{}{I actually am.}

{125}{}{Then know this - everyone here call us "fureecks". We wear bags over our heads so you won't see us chewing human flesh with our rotten teeth. Ha-ha-ha!!}
{126}{}{Flesh, huh. You're funny guy. So what's wrong with your faces?}

{127}{}{With our faces? Oh, wanderer, I can't tell you that, otherwise you're gonna puke all over the place. Ha-ha!}
{128}{}{Stop trying to scare me, Mr. Walking Dead. I've seen things worse.}
{129}{}{What?! Are you trying to make fun of me? You're gonna need another bag - to bury your remains in, you phreek!}
{130}{}{I don't like your jokes. I better go.}

{131}{}{Oh! I see you're a tough one. You can call me Larry. Larry Geller, that's my full name.}
{132}{male}{Hey, Larry. What about the stuff in your pants? Does it also cause vomiting?}
{133}{male}{So what? I can cut your "stuff" off and transplant it into myself! Then I'd feel fifty years younger. Ha-ha-ha!}
{134}{male}{The hell you will! I bet you will eat yours first!}
{135}{}{You must be eliminated at once before others are hurt. Your last words, freak!}
{136}{}{That's some unhealthy humor. I better go get some fresh air.}
{137}{female}{A pity you don't like my looks, But if you are in for the roughness, then you came to the right place, baby!}
{138}{female}{Hold your corpses, fella! I never thought a dead man would hit on me.}

{139}{}{Oh, you'd better not say that. I can take it literally... Ha-ha-ha!!!}
{140}{}{So what's your sickness?}
{141}{}{You're very inadequate. I should eliminate you!}
{142}{}{Then I'd better shut up and go away.}
{143}{}{So, what are you sick with?}
{144}{}{As you wish, Larry. I need to go now.}

#Ïîëó÷åíèå êâåñòà íà ïîèñê îïðàâäàíèé
{145}{}{In fact, we haven't suffered from anything in a long time... Except for a small mental disorder.}
{146}{}{So what is it with your skin then?}
{147}{}{Radiation, friend, radiation. And, apparently, some other crap that flies in the air. The body ossified, the skin became rigid, and the veins lost their elasticity.}
{148}{}{Yeah, I get it. So now what, are you hiding your faces so you don't scare kids or something?}
{149}{}{In Clean City, they scare the kids with us anyway. Like, look, if you don't behave, an evil freak will come and take you to the Dead Hotel, stuff like that. They think we're contagious, so everybody stays away from us... Mostly.}
{150}{}{Mostly?}
{151}{}{Apparently, someone overdosed and now we are accused of producing drugs. The police even seem to have some evidence. I don't know if that's true, but I don't think the police would want to look for evidence. They'll just come and shoot us. Hopefully, after that, our souls will haunt them at nights, heh-heh.}
{152}{}{But you don't produce any drugs, right?}
{153}{}{The police is right! You need to be transported to a new place where you can stay - ten feet under!}
{154}{}{Well, this is not my business. Perhaps, I should go.}
{155}{}{Only herbal medicines to support our perishable flesh and the ability to urinate. We have to make powders to dilate the venous system. Alas, the police consider it a drug.}
{156}{}{So, are you in death-threatening danger?}
{157}{}{I agree with them! And now I'm going to fulfill the will of the lady Justice!}
{158}{}{I do not know who to believe. Perhaps, I'd better just go about my business.}
{159}{}{If we don't prove our innocence, the police will come and, at best, chase us away from this place. And at worst, they'll take away our medication and thereby deprive us of the opportunity to take a proper piss... Ha-ha! Although, we are increasingly debating whether they will dare to come. Something tells us that they won't.}
{160}{}{Can you prove your innocence?}

{161}{}{No. We'll never prove our innocence. Especially since we'll soon be hanged for your death by slow dismemberment... Ha-ha! We won't even be able to bring evidence to the Clean City - we'll just be shot on the spot as soon as we get near the main gate.}
{162}{}{You know, what I think? That you deserve justice. I will try to help you... If you are honest.}
{163}{}{You don't need to go there! I will shoot you all right here!}
{164}{}{Listen, that's your problem, I don't want to have anything to do with it. That's why I leave.}

#Çàâåðøåíèå êâåñòà íà ïîèñê îïðàâäàíèé
{165}{}{How noble! So noble that I don't even believe it. And that's after I slipped a poisonous saprophytic tick into your pocket... Don't search your pants. It was a joke.}
{166}{}{I'm being honest with you. Be honest with me too.}
{167}{}{[Secretly start recording the conversation on your Pip-Boy] I'm being honest with you. Be honest with me too.}
{168}{}{I'm honest... And serious. As serious as I can be. Yes, we've had some bad times, and we used to make powders with much stronger effects. But that's in the past. You have to believe us.}
{169}{}{Nobody has to do anything for you just yet, comedian. Okay, lets say I do believe you. Then why? And who is setting the police on you? And what evidence do they have?}
{170}{}{I don't have the slightest idea! The evidence is clearly circumstantial. The chief of police came to us, asked where we get the ingredients, how much drugs we make per month... Of course, he didn't believe us. I think he is convinced that he is right and will defend it, even if you find evidence to the contrary.}
{171}{}{Well, that isn't much.}
{172}{}{I think you should talk to the police first. I think they will listen to you. Think your story over, so as not to arouse unnecessary suspicion. Better yet, kill everyone there and sacrifice their hearts to our god! Ha-ha-ha...}
{173}{}{We'll see.}

{174}{}{[Secretly start recording the conversation on your Pip-Boy] But you don't produce any drugs, right?}

#Îïðàâäàíèå íàéäåíî
{175}{}{I found a receipt from the slavers. Here, take a look.}
{176}{}{And what do we have to do with it?}
{177}{}{I wanted to ask you the same thing - what do you have to do with it, and on whose orders all this was done?}
{178}{}{Whose orders? Well, okay, let's see. [Makes it look like he's trying to read]}
{179}{}{Damn! Larry, you should have told me you couldn't read. Let me read it for you.}
{180}{}{Thank you. But I can read. I just can't see as well as I used to.}
{181}{}{Stop making excuses. How do you respond to this receipt?}

{182}{}{I will say that you have a direct proof of our innocence in your hands. Although I don't think that the chief of police will be fully convinced. Unless you put a red-hot poker between his legs... Anyway, we need to get someone smooth-skinned and responsible to come to him about it. They won't let us into Clean City, that's for sure.}
{183}{}{Wait a second. What is going on? What's this got to do with the police?! What the hell did you do?!}
{184}{}{Who could have convinced the slavers to do that? Who is your enemy?}

{185}{}{We don't have "enemies". It's probably just, uh, racial discrimination.}
{186}{}{Hmmm. I really doubt it. It seems to me that someone is deliberately trying to drive you out of this parking lot.}
{187}{}{Well, all right. It's time to go to the police.}

{188}{}{I don't think that we mean harm to anyone, since we are sitting quietly and won't even fart in our hotel. In general, we should quickly "please" the police chief. If you know what I mean.}
{189}{}{Oh, yes, the police. I'll take the evidence there.}
{190}{}{What?! Why me?! I am also afraid! Here's the paper, do it yourself.}

{191}{}{Listen, we're not the best people in town, I know that. We're feared. And we are afraid. But you, you're not. Even the police can't compare to you! Don't leave us like this! And we'll help you in return.}
{192}{}{Okay, okay! I'll take the evidence to the police. I hope they don't shoot me for it.}
{193}{}{You wish! I'm not my own enemy! Here, you take the evidence and I'm out of here. My job is done.}
{194}{}{How will you help me?}

{195}{}{Well. In the end, we should be grateful even for that. Thank you. I think someone in "Hard Rock" will agree to go to the police.}
{196}{}{Great.}
{197}{}{And what do I get for all the work?}
{198}{}{We spared your life - isn't that enough? Ha-ha-ha! Here. That's all we can give you. [Hands you a pack of stimpaks]}
{199}{}{Yeah, that's not much.}

{200}{}{You, wanderer, must often get into dangerous situations in the wasteland. May pharmacology help you! Only today - two for the price of... two, of course, we all need to eat.}
{201}{}{Stimpak, 5.}
{202}{}{Superstimpak, 3.}
{203}{}{Psycho, 3.}
{204}{}{Anti-smoker, 5.}
{205}{}{Nothing. I will do it for free.}

{206}{}{Okay. As you wish. Just take the evidence to the police. And we will handle the rest.}
{207}{}{Great. I'm going.}

{208}{}{It's done! The evidence is delivered, you're now officially innocent.}
{209}{}{I have come to tell you that your names are cleared. You can sleep in peace. The police won't come to you again.}

{210}{}{Thank you. We already had one cop coming here. You saved us from exile. You are a good man. Just like us. Nobody here will ever forget this.}
{211}{}{You promised to reward me for my hard work, have you forgotten that?}
{212}{}{Just a "thank you" would be enough.}

{213}{}{All in order. Do not abuse it - that's my advice to you. Or you'll get high, like we do. Ha-ha-ha!}
{214}{}{Funny. You would make a great fit for a comedy TV show, Larry.}

{215}{}{Thank you. We already had a cop coming here with official apologies. As you can see, justice triumphs.}
{216}{}{Right. Take care.}

{217}{}{I see someone purposely trying to remove you from the hotel.}
{218}{}{What about this receipt?}
{219}{}{The smooth-skinned wanderer is with us again! How surprising.}
{220}{}{About the evidence - I can't take it to the police. Look for another way.}

#Ïëàâàþùèå ôðàçêè ïîñëå îáëàâû
{221}{}{What should we do now?}
{222}{}{We won't be able to find a new place to live.}
{223}{}{We are now worse than beggars.}
{224}{}{Damn! I guess that's it...}
{225}{}{Bad luck!}
{226}{}{It's time to say goodbye to our lives.}

#Ïîëó÷åíèå äîñòèæåíèÿ "Çíàõàðü"
{227}{}{How did you learn to make these healing powders?}
{228}{}{It's not that complicated. We are masters of survival. If it not for our knowledge of nature, we would die long ago.}
{229}{}{Can you teach me to make powder and stimpaks?}
{230}{}{Right.}
{231}{}{...But no one knows where this knowledge will later be applied. Don't even think about it. This dead body still remembers pride and honor.}
{232}{}{Look how you talk now!}
{233}{}{With pleasure! I think you will spend this knowledge for the benefit of people.}
{234}{}{Sure. Should we begin?}
{235}{}{Not now.}
{236}{}{}

{237}{}{[Secretly start recording the conversation on your Pip-Boy] What can you tell about his drug addiction?}

#Ðàáî÷àÿ ïðîáëåìà íà äàìáå
{238}{}{I see that you are not particularly welcomed in this city. Where do you work?}
{239}{}{Wh- work? We have no business and no work. He-he.}
{240}{}{So what do you do for a living then?}
{241}{}{Just surviving, as we can. We have some crops not far from here, for example.}
{242}{}{What if I'd offer you a steady and stable job on not so safe, but still guaranteed workplace? I'm referring to the Hoover Dam, you may have heard of it...}
{243}{}{Well, if you think about it, we are ready for any work... If they accept us. But they won't.}
{244}{}{They will accept you. Bob Neil is having a bad time now, he is willing to consider this option... I think.}
{245}{}{It would be an acceptable solution for us, yes. But somehow I doubt that this man would agree. Why don't you ask him? We're ready, starting even tomorrow!}
{246}{}{Excellent! I'll talk to Bob.}
{247}{}{You persuaded the freaks to go to work for Bob Neil. Hmm... All that remains is to persuade Bob Neil himself.}

{248}{}{Seriously? Just like that, for "thank you", you were risking your life? Well, I just can't let you go empty-handed then. Here, take this. [He gives you 2 packs of colored pills] It's a very good... "Memory refresher". Heh-heh. I hope you know what I mean.}
{249}{}{Not yet, but I'll figure it out. Thank you!}

#Female character
{1109}{}{Here comes our smooth-skinned friend... Well, you're still smooth-skinned to us. But it's a mystery how you, with a face like that, don't get shot in Clean City.}
{1110}{}{You'd better not to wander around here. Our hotel is not much better than the local cemetery. Ha-ha! Joking. The cemetery is way better, of course...}
{1123}{}{Wait, you've never heard of us? You weren't even warned that we are to be avoided? Looks like you're new in town!}
{1127}{}{With our faces? Oh, wanderer, I can't tell you that, otherwise you're gonna puke all over the place. Ha-ha!}
{1166}{}{I'm being honest with you. Be honest with me too.}
{1167}{}{[Secretly start recording the conversation on your Pip-Boy] I'm being honest with you. Be honest with me too.}
{1168}{}{I'm honest... And serious. As serious as I can be. Yes, we've had some bad times, and we used to make powders with much stronger effects. But that's in the past. You have to believe us.}
{1191}{}{Listen, we're not the best people in town, I know that. We're feared. And we are afraid. But you, you're not. Even the police can't compare to you! Don't leave us like this! And we'll help you in return.}
{1193}{}{You wish! I'm not my own enemy! Here, you take the evidence and I'm out of here. My job is done.}
{1200}{}{You, wanderer, must often get into dangerous situations in the wasteland. May pharmacology help you! Only today - two for the price of... two, of course, we all need to eat.}
{1209}{}{I have come to tell you that your names are cleared. You can sleep in peace. The police won't come to you again.}
{1210}{}{Thank you. We already had one cop coming here. You saved us from exile. You are a good person. Just like us. Nobody here will ever forget this.}
{1219}{}{The smooth-skinned wanderer is with us again! How surprising.}
{1245}{}{It would be an acceptable solution for us, yes. But somehow I doubt that this man would agree. Why don't you ask him? We're ready, starting even tomorrow!}
{1248}{}{Seriously? Just like that, for "thank you", you were risking your life? Well, I just can't let you go empty-handed then. Here, take this. [He gives you 2 packs of colored pills] It's a very good... "Memory refresher". Heh-heh. I hope you know what I mean.}
