{100}{}{You see the Mayor.}
{101}{}{You see Mr. Williamson, the mayor of Las Vegas. Despite his high position he looks rather simple.}
{102}{}{Do you have an appointment? Please leave my office before I call the guards!}
{103}{}{Security! An intruder in the office!}

#Starting cues
{110}{}{I'm listening.}
{111}{}{Mr. Williamson, maybe I could provide some services for the city? Or even to you personally?}
{112}{}{About the investigation...}
{113}{}{Could you help me find the coordinates of Area 51?}
{114}{}{I don't have anything. Take care.}

#Area 51
{115}{}{Is that it? Please don't bother me with such minor issues. Talk to my secretary.}
{116}{}{Wait, hold on! I really need this!..}
{117}{}{Alright, I'll ask somebody else then.}
{118}{}{Well, I think you deserve access to our archive. Talk to our head archivist; he'll give you the necessary information.}
{119}{}{Thank you, Mr. Williamson!}

#Finding work
{121}{}{Yes, I think I have something for you. I ask you to take this matter as my personal request, although its resolution would greatly influence the fate of the city.}
{122}{}{Sounds intriguing.}
{123}{}{Make yourself comfortable. We have a lot to discuss.}
{124}{}{Thank you, Mr. Williamson.}

{125}{}{Would you like a cup of coffee? Caramel? Cigar?}
{126}{}{Thank you, I won't say no to a caramel.}
{127}{}{No thank you, let's get straight to the point.}

{128}{}{I'm afraid you don't look like you're fit for the job at hand. Thanks for the offer.}
{129}{}{That's unfortunate.}

{130}{}{Alright, on to business.}
{131}{}{I'm listening.}
{132}{}{As you probably know, there is a huge power plant near the Las Vegas, which, as unusual as it could be, stayed almost intact after the Great War. I'm talking, of course, about the Hoover Dam. For our city it is a very important enterprise. Thanks to it, the Las Vegas is now what it is - a major strategic point on the map and an influental global player. Naturally, such an important object cannot be owned by a single party, be it the one person or an organization. So, the city made a decision to split the rights on controlling the plant between the representatives of the city elites. A system of shares - or quotas - was introduced, to turn the decision-making process into more transparent and responsible... Unfortunately, lately, the situation became more tense.}
{133}{}{What do you mean by "more tense"?}
{134}{}{The working conditions on the plant are... Not the most pleasant. Such big enterprise as the Hoover Dam requires a lot of manpower to employ, including engineers and supporting services personnel. This is a huge financial burden for the city, so the level of salaries for low-qualified workers leaves much to be desired. Furthermore, worn-out condition of equipment, increased radiation level, poor soundproofing and other problems led to a certain difficulties with... The hiring of staff. However, you'd better talk about it with Bob Neil himself - he is the chief engineer and head manager of the Hoover Dam.}
{135}{}{Do you want me to help with searching the workforce for the power plant?}
{136}{}{...No. The thing is, when the public became aware of this problems, the level of crime in the city started to rise prominently. And, in the most cases, the victims in this crimes were plant's workers. I don't think this is a coincidence. Moreover, judging by the police reports, the majority of arrested criminals were under the influence of drugs. And that bothers me even more.}
{137}{}{What drugs are we talking about?}
{138}{}{I am no specialist in fields of medical or chemical science, but the same police reports said it's not about harmless pot, or even mushrooms - we are dealing here with psychedelics, opiates and other synthetic or partially synthetic drugs. That means this is not about some single amateur chemists, although, I wouldn't discard any possibility.}
{139}{}{That means there is a primary drug supplier to find.}
{140}{}{Correct. But my main point is this - I have grounds to believe that all is connected: the problems on the Hoover Dam, increased number of crimes and attacks on the staff of the Dam. And that means, without a doubt, that there is someone who benefits from it.}
{141}{}{So, you suspect that all of this is made to achieve some shady goal?}
{142}{}{I assume that everything that happens, happens for a reason. Someone is taking advantage of it. And that's what you are going to investigate.}
{143}{}{Why don't you assign the police on this?}
{144}{}{The police is already trying to do everything possible, but its forces are not enough to handle everything altogether. With that said, they already have some leads. They think the group of the outcast ghouls - freaks - are involved, and also have some suspicions about another major entrepreneur in the Las Vegas - mr. Sam Phillips. More details on that can be provided by the police chief, Oscar Davis. I know him as honest and responsible officer - although, he is a little too serious when it comes to following protocols.}
{145}{}{I see.}
{146}{}{So, I want you to find out, who is responsible for everything happening in the city. I'm asking you to search for evidence - documents, recordings, letters - anything that can justify your arguments.}
{147}{}{Are you assuming that there is some limited circle of persons of interest?}
{148}{}{You see, there are not so many people who can really influence upon the economical situation here. Las Vegas is, let's say, limited in powerful human assets. The possibility of upward social mobility is practically nonexistent, therefore, in our case, the one who desires more power is clearly the one who already has plenty.}
{149}{}{Do you suspect anyone specific?}
{150}{}{Yes, I do. But I don't want to give you my hypothesis prematurely. I want you to make your own perspective on events.}
{151}{}{Okay. Let's summarize then.}

{152}{}{Let's do that. Here's what your job will entail. Investigate the source of drugs invading the city. Find out the key manufacturer and supplier. And the most of all - who benefits from it. When you gather enough evidence that can be strung together, report to me. If you succeed, you will have your payment in amount of 30,000 dollars, cash.}
{153}{}{Can I see any of it in advance?}
{154}{}{Now that's a price worth working for. I'll take the job.}

{155}{}{Very well. I'll be waiting for your report. Try not to take too long, and... Be careful. By the way, I see you have a Pip-Boy. You do know about the capabilities of this device, don't you? Particularly that it includes the fuctionality of recording conversations.}
{156}{}{Yes, I'm familiar with my Pip-Boy and know how to use this function.}
{157}{}{Honestly, I didn't know about it.}
{158}{}{Then keep that in mind. I suppose the recordings could be used as evidence against some persons on their involvement in specific events.}
{159}{}{Alright, I'll make sure to remember it.}
{160}{}{Well, good luck in your investigation.}
{161}{}{I'll begin immediately, Mr. Williamson.}

{162}{}{You took on a investigation case involving drugs. The job is as dangerous as it is important.}

#Reward and deposit
{163}{}{Yes, of course. But no more than 10% of the reward. How much do you need?}
{164}{}{6000}
{165}{}{5000}
{166}{}{4000}
{167}{}{3000}
{168}{}{2000}
{169}{}{1000}
{170}{}{I think I'll collect everything upon completion.}

{171}{}{Here is your deposit. You won't be given more until you complete the task.}
{172}{}{Understood.}
{173}{}{Can I get advance payment to help myself in the investigation?}

{174}{}{On another thought, I'd rather collect everything at once.}
{175}{}{Well, time to earn it.}

#Completing the main quest
{176}{}{Do you have new clues about your investigation?}
{177}{}{I don't think I have enough.}
{178}{}{Yes, I'm sure I gathered enough evidence to explain everything.}

{179}{}{Very well. [To the secretary] Marion, don't let anyone into my office, I'm holding an important meeting! Okay, I'm listening.}
{180}{}{I suppose, I should begin by saying that our mysterious suspect has a major influence on the Las Vegas city police. Not long after I asked some questions in the department, I was met by one of the inspectors at the Clean City gates. He had an order to kill me. I didn't manage to figure out who or what made him carry that, but it is obvious that it wasn't his own initiative.}
{181}{}{So, the police is involved. No surprise though - any social institute always includes someone who dissatisfied with current state of things. Do you have some evidence, which could help to identify the person of interest? }
{182}{}{I do. According to this document here, the police had been spending additional budget funds with the goal of prioritizing the investigations connected to drug cases. But, at the same time, the police already had its key suspects - the freaks and Sam Phillips.}
{183}{}{[Mayor carefully studies Oscar Davis' receipt] Huh. The decision to go overbudget is made by Tom Parker. And it seems that he decided to take action using the chief of the police. "Prioritizing" the drug cases at the same time when the freaks and Sam Phillips are already accused... Knowing Davis, I am sure he took this matter very seriously - he wouldn't do anything without serious evidence on both ghouls and Sam. What did you manage to find out about Phillips?}
{184}{}{That he was accused of producing chems - it was reported to the police by anonymous source. During the search the cops found some substance, which, allegedly, could be used for drug manufacturing.}
{185}{}{Is he really involved in this?}
{186}{}{I have the recording of conversation with Larry Geller, the leader of the ghouls. He believes that Phillips is operating within the law.}
{187}{}{I have the recording of conversation with one of the local dealers. He said that Phillips didn't purchase any drugs or materials for producing them.}
{188}{}{He has been detained. Although, no proof of his guilt has been found, so it would seem he is innocent.}
{189}{}{I haven't found that out yet.}
{190}{}{What are you doing here then?! Go and do your job!}
{191}{}{As you wish, mr. mayor.}
{192}{}{I think so... Yes... Is there another Sam Phillips in the city?}
{193}{}{I think so, although, I don't know who is responsible.}

{194}{}{I have the recording of conversation with Larry Geller, the leader of the ghouls. He believes that Phillips is operating within the law.}
{195}{}{I talked with Larry Geller, the leader of the ghouls. He believes that Phillips is operating within the law.}
{196}{}{I still haven't managed to figure this out.}
{197}{}{I have the recording of conversation with one of the local "pushers". He said that Phillips didn't purchase any drugs or materials for producing them.}
{198}{}{I talked with one of the local "pushers". He said that Phillips didn't purchase any drugs or materials for producing them.}
{199}{}{I still haven't managed to figure this out.}
{200}{}{You're saying I should trust your word on it?}
{201}{}{Well... I didn't record the conversation.}
{202}{}{Despite the Police Department's scepticism, I've managed to convince them that the materials they have on Sam Phillips does not prove his participation in drug dealing.}

{203}{}{Okay, the situation with involvement of Sam Phillips is mostly clear. But the question still remains: where do the drugs come from? What about freaks, do they have any connections to it?}
{204}{}{Actually, I've managed to locate the entire drug laboratory on the outskirts of the city.}
{205}{}{I'm still looking into it. Don't have answer for now.}

{206}{}{An entire laboratory?! Just as I suspected. The amounts of chems were just too much, if not impossible, to make for a small operation. What did you find out about it? The main thing - do you know who is in charge of the facility?}
{207}{}{Although the lab uses slaves as a labor and as a guinea pigs for testing new products, which itself could point at the connection to the slavers guild, there are no names in the lab's records. But I think we can write the freaks off the list of suspects - here are the documents I found in the Slavertown.}
{208}{}{I haven't managed to work that out yet.}
{209}{}{Let me see. Where did you get that?}
{210}{}{In the safe belonging to Vortis, the head of the slavers guild.}
{211}{}{Judging by this, Vortis is waiting for the freaks to be set up. So we can safely say, that freaks are innocent here, although I'm still worried by this "Boss" person, who is keen on the overpriced slave deal. Do you have any clues, who that might be?}
{212}{}{I have another note from the lab, about the purchasing the shipment of chems. It contains some mentions about buyer - and it's the "Three-card Monte" casino.}
{213}{}{I know that Hal Wallace is connected to the drugs. I've recorded a conversation with him when he tried to convince me to commit a crime.}
{214}{}{Unfortunately, that is all I have proof on.}
{215}{}{The casino is a very profitable business. Why does he need to involve himself with drugs?}
{216}{}{I have no evidence, but my theory is this - there are always people willing for more than currently at the menu. Why to pass on such opportunity? He is just maximizing his profits.}
{217}{}{Let's suppose that. So, by now you've found out that the chems flooding the city were produced by a major drug lab. On its territory is widely used slave labor, additionally, testing of new products also involves using slaves. There is someone in charge of this lab. And it is not Hal Wallace - he is the buyer. At the same time, Vortis participates in the negotiations with some "Boss" about mutual benefits from slave deal after setting up ghouls - but who would have a problem with them?}
{218}{}{As far as I understand, the ghouls are perfect fit for Hoover Dam - their labor is cheap, the ghouls themselves are friendly, and also, no one else would want to work on the Dam in current situation. If there are no freaks, the only option left for the chief of the power plant is to use slaves.}
{219}{}{[Nods] I understand. It is beneficial for those who deal slaves. In our case - for slavers.}
{220}{}{Even more specific - for the same "Boss" of slavers and the owner of drug lab. I suspect he is the same person.}
{221}{}{It's not Sam Phillips - he is not involved with drugs, nor with slavers. It's not Hal Wallace - no sense in writing yourself into a document as a buyer and be exposed if it leaks out. It's not Vortis, because he received the information about the freaks from someone else. It's definitely not Bob Neil - this mysterious someone has connections or influence in the Las Vegas police. And the Oscar Davis himself is also not the culprit, because he wouldn't wait for some evidence to deal with Sam Phillips and freaks. So it leaves us with...}
{222}{}{Tom Parker. I have a document, signed by him, concerning a transfer of 6% of the municipality's shares to the head of slavers.}
{223}{}{Tom Parker. Though I have no proof of him connected to the lab or the slavers.}
{224}{}{[Takes the focument from you] Tom Parker. He is ambitious, that's for sure, but I don't understand what he wanted to achieve. If he would try to execute this transfer, it would've raised a lot of questions. And not only mine.}
{225}{}{I suppose he came up with an explanation for this.}
{226}{}{Let's say, he is our man. How the slavers and Parker are tied? What is Hal Wallace's role?}
{227}{}{I think that Wallace was needed to take care of the freaks. Without involvement of the police or the slavers.}
{228}{}{It makes sense. Parker already once tried to push the drastic measures regarding the freaks, although that didn't work with Davis - was no hard proof. If Parker would continue to accuse them of guilt, it would've raised a lot of suspicions.}
{229}{}{So he makes an alibi for himself by forcing Wallace do the job.}
{230}{}{Looks like it. Let's go to the beginning and summarize.}
{231}{}{Yes. It goes like this: Tom Parker - a boss of the slavers and owner of the drug lab. When problems with the workforce on the Dam arose, he decided to make profits on destabilized situation.}
{232}{}{He increases the volume of drug production and its supply to the city, which leads to rise of the crime rate. Probably, he even gave direct orders to carry attacks on the plant's workers.}
{233}{}{Considering that city cannot exist without the electricity, and the manpower on the Dam continues to thin, sooner or later Bob Neil would be concerned with the lacking of workers for the facility.}
{234}{}{But the social situation leads to absence of willing to take the jobs. So, eventually, there are only two options - freaks or slaves. And the second option benefits greatly for Parker.}
{235}{}{But here is the problem - the freaks are cheap, endurant, doesn't care for radiation, and, which is a paradox, many of them have vast and different experience. They are much better option for the Dam.}
{236}{}{But it would contradict the business interest of Tom. So, he decides to get rid of the freaks.}
{237}{}{Knowing working methods of Oscar Davis, Parker starts to actively campaign against drug problems and raises the funding of the police, trying to make them follow the cases he is interested in - the cases about the freaks involvement.}
{238}{}{However, Davis doesn't rush in accusing ghouls and demands a solid evidence. So, Parker makes a move.}
{239}{}{He drags Hal Wallace into the game, planning to take care of the matter while staying clean himself. I suppose, they've already had some common business running - the lab supplied casino with drugs, while the casino ensured additional profits by selling, which, in turn, contributed more to the chaos in the city.}
{240}{}{Together they make a new deal - Wallace helps to set up the freaks with producing chems, and in return he gets a promise to get his main competitor - mr. Sam Phillips - dealt with.}
{241}{}{Naturally, Tom Parker sees in it another opportunity to divert attention from himself and his attention to freaks, and openly accuses Sam Phillips in involvement with chems. }
{242}{}{Oscar Davis starts an investigation against Phillips. Wallace sets up the freaks by planting some real drugs to them.}
{243}{}{The police deals with the freaks. The power plant is forced to buy slaves to keep itself running.}
{244}{}{Parker gets an immense profits, both from the slave deal and the drug dealing in the city.}
{245}{}{He could even turn Hal Wallace to look like a primary suspect, if there was something wrong.}
{246}{}{True. But why he tried to transfer a municipality's shares to the slavers? And how he would have explained it?}
{247}{}{He would get a profit, and also inscreased his influence on the Dam - after all, the slavers' shares are his shares. I think the only thing that had been stopping him was the lack of explanation why to do so. But he would find that out eventually.}
{248}{}{Maybe. Or maybe he could persuade me in signing it somehow. Then I would look like I am involved in this. He could use the document as a leverage on me.}
{249}{}{The one who desires more power is clearly the one who already has plenty.}
{250}{}{Yes, that's what I said when we first met. I am sorry that I was right in that.}
{251}{}{Parker made only one mistake: he assigned the hit on me to the police officer.}
{252}{}{And because of this you understood that the one who is behind of this is influencing the police.}
{253}{}{Yes. This was the first lead.}
{254}{}{Well, you have performed your job admirably and did what no one else could. For the brilliant resolution of this case I express my personal gratitude to you. Thank you.}
{255}{}{Thank you, mr. Williams.}
{256}{}{I'm asking you to leave me the evidence you brought in - they will be used in prosecution. Also, I'd be grateful if you would help me to prepare the full report on this for the council.}
{257}{}{Of course. Let's summarize the results again...}
{258}{}{And here is your reward. Thank you, from the behalf of the entire Clean City!}
{259}{}{Thank you. What are you going to do now?}
{260}{}{The evidence will be handed to the court. Tom Parker will be charged with organized crime, Hal Wallace will be prosecuted as the accomplice. For the time of the court process Oscar Davis is suspended from his duties as the police chief - there is a need to check the involvement of his staff. Then I should raise an issue to the Council about the Hoover Dam... Is there someone behind the door? Marion, I asked not to let anyone in!}
{261}{}{Looks like you have visitors...}

#Floats upon completing the text
{262}{}{Tom? What is it?}
{263}{}{I see you have the legendary detective of Las Vegas with you?}
{264}{}{This is none of your concern, Tom...}
{265}{}{Oh no, I think it is. Your dog put his nose where it shouldn't have.}
{266}{}{...You wiretapped me?}
{267}{}{Of course. And I should have done one thing earlier...}
{268}{}{Thrown you out of fucking window, you old bastard.}
{269}{}{Tom! Calm down!}
{270}{}{Too late.}
{271}{}{Tom! No!!!}

{272}{}{Although the lab uses slaves as a labor and as a guinea pigs for testing new products, which itself could point at the connection to the slave guild, there are no names in the lab's records. But I think we can write the freaks off the list of suspects - I found the documents in the Slave Town, which contained the information that someone wants to set them up with drug making. I gave it to Oscar Davis.}

#Addition to being denied detective work
{273}{}{Why don you think I won't be able to handle it?}
{274}{}{Alright then.}

{275}{}{This job will require a careful approach to many people. Careful, *delicate* approach.}
{276}{}{You don't seem to be one gifted with a silver tongue. And this is a key skill in this task.}
{277}{}{Ahem, sorry if this will hurt your feelings, but your intellectual abilities seem rather... Lacking. Not what's needed for the job.}
{278}{}{You seem to be lacking the experience to undertake such an important and dangerous task.}
{279}{}{How about you take on something more suitable to your abilities.}
{280}{}{}

{281}{}{ First of all.}
{282}{}{ Secondly.}
{283}{}{ Third.}

{284}{}{That's a shame. I actually have some experience. I've already played a role in solving over five serious cases in my journey.}
{285}{}{Ahem. If you do have an experience, then, I guess, I could tell you the details.}

#Vendor's Cart
{300}{}{I'm here for a personal issue. An acquaintance of mine, a sandwich vendor, has a debt she's having trouble settling. Could you help?}
{301}{}{As a fellow human being, I am very sorry about your friend. But she has obligations which needed to be followed. Before taking the loan she should have read the agreement.}
{302}{}{But it's only thanks to the immense pays that she can't get any profits. Could the Clean City give her a few months? She could expand her business and provide more money to the budget.}

{303}{}{I'll be frank - it's not my responsibility. I can't spend my time convincing the city council to change the contract of some minor trader. She should put an application to the administration, so it could be processed according to the procedures.}
{304}{}{Is that so?.. Well, I have a business of my own here - I'm selling Nuka-Cola. I could pledge some of my own product if the layoff won't bear any results.}
{305}{}{I know about business, so I think I can convince your Council in profits from this, using real statistics.}
{306}{}{It is way better to give the trader a postponement than to loose income from her taxes forever. I think I can convince your Council.}
{307}{}{Mr. Williams, I'm asking this as a personal request.}
{308}{}{You could help with sorting this out with the Council as an experienced leader.}
{309}{}{Well, looks like you can't be convinced. In that case, I'll be going.}

{310}{}{I don't see any reason to do so. The council simply won't listen to you without some powerful arguments. If you, for instance, would have had a business in Vegas, or your name carried any weight in the city, then you might have had some hope to affect the decisions of some members.}
{311}{}{Hmm... This certainly changes things. I'll give the word and you give the documents to my secretary.}
{312}{}{Perfect.}
{313}{}{I'd like to sort some things out on my end first.}
{314}{}{Hmm... I don't think the council will listen to a small-time trader.}
{315}{}{You look like you could hold your point of view even against the hardheaded council members. I'll give the word, and my secretary will arrange the documents. Everything else depends on you.}
{316}{}{Considering your help, I'm ready to return the favor. I'll give the word, and my secretary will arrange the documents. Everything else depends on you.}
{317}{}{The council gave a layoff. Time to give the good news.}

#Female version
{1157}{}{Honestly, I didn't know about it.}
{1174}{}{On another thought, I'd rather collect everything at once.}
{1178}{}{Yes, I'm sure I gathered enough evidence to explain everything.}
{1180}{}{I suppose, I should begin by saying that our mysterious suspect has a major influence on the Las Vegas city police. Not long after I asked some questions in the department, I was met by one of the inspectors at the Clean City gates. He had an order to kill me. I didn't manage to figure out who or what made him carry that, but it is obvious that it wasn't his own initiative.}
{1205}{}{I'm still looking into it. Don't have answer for now.}
{1208}{}{I haven't managed to work that out yet.}
{1253}{}{Yes. This was the first lead.}
{1272}{}{Although the lab uses slaves as a labor and a guinea pigs for testing new products, which itself could point at the connection to the slave guild, there are no names in the lab's records. But I think we can write the freaks off the list of suspects - I found the documents in the Slave Town, which contained the information that someone wants to set them up with drug making. I gave it to Oscar Davis.}
