{100}{}{You see the deputy mayor.}
{101}{}{You see Tom Parker.}
{102}{}{You see undersized mustachioed man with a demanding expression. This man is the deputy mayor.}

#Начальные вопросы
{110}{}{Tom Parker, the deputy mayor. What is it about?}
{111}{}{What is it about?}
{112}{}{I'm looking for the coordinates of Area 51. Could you help me?}
{113}{}{Tell me, how much do you get paid?}
{114}{}{I demand an explanation why you sponsor the case of Sam Phillips!}
{115}{}{I guess I do not need anything.}

#Выход из диалога
{116}{}{Do you know *where* you are? This is not a brothel, it's the mayor's office! I demand an explanation, what are you doing here!}
{117}{}{Oh my! Oh my! And what if I don't answer? Huh?}
{118}{}{I'm here on business. I was hired by Mr. Williamson.}
{119}{}{Sorry, I just had no one to talk to.}
{120}{}{Sorry, I was looking for the toilet, but entered the wrong door.}
{121}{}{I came to drain some blood out of you.}
{122}{}{I'm looking for the archive with the coordinates of Area 51.}
{123}{}{Archive is at the end of the hallway on this floor... Although it won't be any help to you. It's only for City Hall employees.}
{124}{}{Wow, okay then.}
{125}{}{Could you help with that?}
{126}{}{Okay, citizen. Stop fooling around! You are not the first questionable fella that goes to City Hall for no reason. We don't need people like here. Get out. Now! Right now!}
{127}{}{Uh, look at him! So what are you going to do now, huh?!}
{128}{}{Okay-okay, I'll go peacefully...}
{129}{}{Guards!!! Intruder in the office!!!}
{130}{}{[Resist]}
{131}{}{[Obey and go with a guard]}
{132}{}{Hmm. In any case, I'll have to ask you to leave this office.}
{133}{}{As you wish.}

#По делу мафиозных разборок (допросы):
{134}{}{I earn enough, to keep afloat. And now, God dammit, I want explanations, why is this question arising.}
{135}{}{Hey, big guy, chill the fuck out. I ask questions here in accordance with the power that Mr. Williamson gave me. So, you deny any involvement in the recent events in the city then?}
{136}{}{I make questions here!}
{137}{}{I was just curious. Honestly.}
{138}{}{Err... What?! What is this, interrogation?}
{139}{}{What do you know about the case of Sam Phillips?}
{140}{}{What are your thoughts about the freaks?}
{141}{}{Hoover Dam. Do you own a part of this station?}
{142}{}{Have you ever been involved with narcotics?}
{143}{}{This is a warning. If I find that you were involved in these crimes - would be better if you disappear from this planet.}
{144}{}{No more questions. *For now* you're free.}
{145}{}{Oh, we got a tough guy here! Now, if you run out stupid questions, I'm asking you to get out of my office.}
{146}{}{As you wish.}
{147}{}{You know, it was fun to see the a detective that is still alive... And now I'll ask you to leave my office.}
{148}{}{As you wish.}
{149}{}{About "alive" - I will remember that. Keep that in mind, smartass.}

{150}{}{Just that he is accused of drug production and that he hasn't yet been caught in the act.}
{151}{}{The most hostile and skeptical. The Clean City has *no* place for any contagion.}
{152}{}{Yes, I do. In the past there was a lot of arguing about it, and the owner came up with the shareholders system, so no one could be left out. Every socially active person in the city aims to have at least a small percentage of shares. And the mayor's office, of course, must keep the greatest possible percentage of it.}
{153}{}{Ahem. The city grew on this, but I haven't used any for many years and have nothing to do with the drugs now.}

{154}{}{It's my job. I have to contribute to the development of the city, rather than its degradation or transformation into shooting galleries. This is enough, I hope?}
{155}{}{Oh yes, this is enough for now.}
{156}{}{Isn't that too much investment for such small matter?}
{157}{}{That doesn't concern you.}
{158}{}{Now! Wait a minute! This is serious. It's about the ruin of the city treasury.}
{159}{}{Whatever you say.}
{160}{}{Damn it! Well why I have to take the rap for the noble deeds?! Why such doubts?! Criminals must be punished, and I do not mind paying a higher fee for a thorough investigation. How much thought did you put into all of this?}
{161}{}{So you deliberately provoke the police to arrest Sam Phillips?}
{162}{}{Maybe you're right about something. We'll close this question for now.}
{163}{}{Alright, Mr. detective! Do not cheat and then twist my words. I'm not trying to put behind the bars the innocent, I am sponsoring the police to solve crimes, as I should do. This is my *direct* duty as deputy mayor!}
{164}{}{Well, let's close the issue for now.}

#Зона 51
{165}{}{Area 51? I think such information should be in our archive. For you, I am willing to take the trouble of 3000, to find it.}
{166}{}{How much?! You think, I'm crazy?! Drop it at least to 1000! Otherwise I will leave and you won't get a penny.}
{167}{}{You have to pay for everything, this is fair. Here is the money.}
{168}{}{Wow, I don't have so much right now. Maybe, later.}
{169}{}{Perhaps you're right. I drop it to 1000.}
{170}{}{Okay! Here is the money.}
{171}{}{I'll go get the money then.}
{172}{}{I make enough money, to live without your *charity*.}
{173}{}{Well okay, okay! Have it your way. Here is 3000 bucks.}
{174}{}{I'll go gather the money then.}
{175}{}{You managed to find the coordinates of Area 51. Now you can travel there.}
{176}{}{No problem. I will make a request to the archive, and you will have the information delivered.}
{177}{}{Okay, I'm leaving.}
{178}{}{It's done.}
{179}{}{[You enter the coordinates in your Pip-Boy]}

#Female character
{1120}{}{Sorry, I was looking for the toilet, but entered the wrong door.}
{1121}{}{I came to drain some blood out of you.}
{1145}{}{Oh we got a tough girl here! Now, if you run out stupid questions, I'm asking you to get out of my office.}
{1163}{}{Okay, Ms. detective! Do not cheat and then twist my words. I'm not trying to put behind the bars the innocent, I am sponsoring the police to solve crimes, as I should do. This is my *direct* duty as deputy mayor!}
{1166}{}{How much?! You think, I'm crazy?! Drop it at least to 1000! Otherwise I will leave and you won't get a penny.}
