{100}{}{You see the deputy mayor.}
{101}{}{You see Tom Parker.}
{102}{}{You see undersized mustachioed man with a demanding expression. This man is the deputy mayor.}

#Начальные вопросы
{110}{}{Tom Parker, the deputy mayor. What do you want?}
{111}{}{What do you want?}
{112}{}{I'm looking for the coordinates of Area 51. Could you help me?}
{113}{}{Tell me, how much do you get paid?}
{114}{}{I demand an explanation about why you are sponsoring the case against Sam Phillips!}
{115}{}{I guess I don't need anything.}

#Выход из диалога
{116}{}{Do you realize where you are? This is not a brothel, it's the mayor's office! I demand an explanation! What are you doing here?}
{117}{}{Oh my! And what if I don't answer? Huh?}
{118}{}{I'm here on business. I was hired by Mr. Williamson.}
{119}{}{Sorry, I just had no one to talk to.}
{120}{}{Sorry, I was looking for the toilet. I guess it's the wrong door.}
{121}{}{I came to drain some blood out of you.}
{122}{}{I'm looking for the archive with the coordinates of Area 51.}
{123}{}{Archive is at the end of the hallway on this floor... Although it won't be any help to you. It's only for City Hall employees.}
{124}{}{Wow, okay then.}
{125}{}{Could you help with that?}
{126}{}{Okay, citizen. Stop fooling around! You are not the first questionable fella that goes to City Hall for no reason. We don't need people like here. Get out. Now! Right now!}
{127}{}{Uh, look at him! So what are you going to do now, huh?!}
{128}{}{Okay, okay, I'll go peacefully...}
{129}{}{Guards!!! Intruder in the office!!!}
{130}{}{[Resist]}
{131}{}{[Obey and go with a guard]}
{132}{}{Hmm. In any case, I'll have to ask you to leave this office.}
{133}{}{As you wish.}

#По делу мафиозных разборок (допросы):
{134}{}{I earn enough, to keep afloat. And now, God dammit, I want an explanation why it's even a question.}
{135}{}{Hey, big guy, chill the fuck out. I ask questions here in accordance with the power that Mr. Williamson gave me. So, you deny any involvement in the recent events in the city then?}
{136}{}{I ask questions here!}
{137}{}{I was just curious. Honestly.}
{138}{}{Err... What?! What is this, an interrogation?}
{139}{}{What do you know about the case of Sam Phillips?}
{140}{}{What are your thoughts about the freaks?}
{141}{}{Hoover Dam. Do you own a share of this enterprise?}
{142}{}{Have you ever been involved with narcotics?}
{143}{}{This is a warning. If I find out that you are involved in these crimes, it would be better for you to disappear from this planet.}
{144}{}{No more questions. You're free. For now.}
{145}{}{Oh, we got a tough guy here! Now, if you're done with your stupid questions, I'm asking you to get out of my office.}
{146}{}{As you wish.}
{147}{}{You know, it was fun to see the a detective that is still alive... And now I ask you to leave my office.}
{148}{}{As you wish.}
{149}{}{About "alive" - I will remember it. Keep that in mind, smartass.}

{150}{}{Only that he was accused of manufacturing drugs and that he had not yet been caught in the act.}
{151}{}{The most hostile and skeptical. The Clean City has no place for any contagion.}
{152}{}{Yes, I do. In the past there was a lot of arguing about it. In the end we came up with the shareholders system, so no one could be left out. Every socially active person in the city aims to have at least a small percentage of shares. And the mayor's office, of course, must keep the greatest possible percentage of it.}
{153}{}{Ahem. The city grew on this, but I haven't used any for many years and have nothing to do with the drugs now.}

{154}{}{It's my job. I have to contribute to the development of the city, rather than its degradation or transformation into shooting galleries. This is enough, I hope?}
{155}{}{Oh yes, this is enough for now.}
{156}{}{Isn't that too much of an investment for such a small matter?}
{157}{}{That doesn't concern you.}
{158}{}{Now! Wait a minute! This is serious. It's about the toll on the city treasury.}
{159}{}{Whatever you say.}
{160}{}{Damn it! Why do I have to be accountable for noble deeds?! Why should I have any doubts at all?! The criminals must be punished, and I don't mind paying more for a thorough investigation. Don't you think that's right?}
{161}{}{So you deliberately provoke the police to arrest Sam Phillips?}
{162}{}{Maybe you're right about something. We'll put this question on hold for now.}
{163}{}{Alright, Mr. Detective! Do not twist my words. I'm not trying to put an innocent behind bars, I am sponsoring the police to solve crimes, as I should. This is my direct duty as deputy mayor!}
{164}{}{Well, let's close the issue for now.}

#Зона 51
{165}{}{Area 51? I think such information should be in our archive. I am willing to take the trouble of $3000 to find it for you.}
{166}{}{How much?! You think, I'm crazy?! Drop it at least to $1000! Otherwise I will leave and you won't get a penny.}
{167}{}{Everything has a price, it is fair. Here is the money.}
{168}{}{Wow, I don't have so much money right now. Maybe later.}
{169}{}{Perhaps you're right. I drop it to $1000.}
{170}{}{Okay! Here is the money.}
{171}{}{I'll go get the money then.}
{172}{}{I make enough money to live without your charity.}
{173}{}{Well okay, okay! Have it your way. Here is 3000 bucks.}
{174}{}{I'll go gather the money then.}
{175}{}{You managed to get the coordinates of Area 51. Now you can travel there.}
{176}{}{No problem. I will make a request to the archive, and you will have the information delivered.}
{177}{}{Okay, I'm leaving.}
{178}{}{It's done.}
{179}{}{[You enter the coordinates into your Pip-Boy]}

#Female character
{1120}{}{Sorry, I was looking for the toilet. I guess it's the wrong door.}
{1121}{}{I came to drain some blood out of you.}
{1145}{}{Oh we got a tough girl here! Now, if you're done with your stupid questions, I'm asking you to get out of my office.}
{1163}{}{Okay, Ms. Detective! Do not twist my words. I'm not trying to put an innocent behind bars, I am sponsoring the police to solve crimes, as I should. This is my direct duty as deputy mayor!}
{1166}{}{How much?! You think, I'm crazy?! Drop it at least to $1000! Otherwise I will leave and you won't get a penny.}
