{100}{}{You see a jug of water.}
{101}{}{You see a vessel for the prisoners. If's filled with rotten water. Apparently, the police keep good water for themselves.}
{102}{}{A close examination of this vessel makes it clear how the police treat prisoners. The quality of water speaks for itself.}
{103}{}{The water is of rather crappy quality. Apparently, only those who have been placed in the isolation ward drink it. If you poison this water, you could cause a sickness among the prisoners.}
{104}{}{You've poisoned the water for prisoners. This can have serious consequences.}
