{100}{}{You see an account book.}
{101}{}{You see a casino account book. The debts and customer winnings are recorded in it.}
{102}{}{These boring records doesn't matter to you.}
{103}{}{Taking the opportunity, you secretly tear out the page where Irvin and Murphy are mentioned.}
{104}{}{This account book definitely contains some information about Irvine and Murphy, but the cashier will not let you openly familiarize yourself with it.}
