#! В 1.0 не используе'ся
# Э'о рудимен' с'арой версии, когда скрип' описывал 'айник на кар'е Пикника
{100}{}{You see a pile of stones, hastily assembled by an unknown traveler.}
{101}{}{You see an unnatural pile of stones.}
{102}{}{Hey, I got here a secret stash!}
{103}{}{An unexpected find!}

#Реплики для образцов крови
{104}{}{This thing must be used on mutants.}
{105}{}{It's alive, it won't let you do that.}
{106}{}{Your blood won't help doctor Willmouth.}
{107}{}{You got a sample of blood. Bring it to doctor Willmouth for experiments.}
{108}{}{You already have a coyote blood sample.}
{109}{}{You have already collected a blood sample of creatures that are related to coyotes.}
{110}{}{You already have a gecko blood sample.}
{111}{}{You already have a pigrat blood sample.}
{112}{}{Done.}
{113}{}{This thing must be used on a mutated animal, not on a mutated plant.}
{114}{}{Hardly this robot's grease will help Dr. Willmouth.}
{115}{}{Doctor Willmouth asked for a different type of blood.}
