{100}{}{You see a whiteboard.}
{101}{}{It's just a board with old ads and price tags. You could add your own notes.}
{102}{}{You are going to read during the fight?! Not very smart, you know...}

#Dialogue branches
{103}{}{Where would you like to park you truck to next time?}
{104}{}{Park the car in the garage.}
{105}{}{Park the car next to the caravaneers.}
{106}{}{Park the car at the Clean City entrance.}
{107}{}{Leave as it is.}

#Random remark after the change of the parking location
{108}{}{Finished.}
{109}{}{Done.}
{110}{}{OK.}
{111}{}{All right.}
{112}{}{No problems.}
{113}{}{Whatever you say.}
{114}{}{However you want.}
{115}{}{No question.}
{116}{}{Will do.}
{117}{}{Sure thing, boss.}
{118}{}{You know better, boss.}
{119}{}{So be it.}

#After the change of the parking spot
{120}{}{Once again.}
{121}{}{That's better.}
{122}{}{I don't need that now}

#Information about the location of the car
{130}{}{Remember where I left the car.}
{131}{}{.}
{132}{}{Okay, now back to the question about parking.}
{133}{}{Now I remember! It's time to go get the car.}

{1130}{}{Remember where I left the car.}
{1133}{}{Now I remember! It's time to go get the car.}

#The locations where the car could be
{1499}{}{It's somewhere in the wasteland.}
#Attention! The list should be copied right from the file .../game/MAP.MSG
{1500}{}{Vault City}
{1501}{}{Wind of War}
{1502}{}{The 'Sigma' base}
{1503}{}{Lovelock}
{1504}{}{Baydie}
{1505}{}{Poseidon Oil NPP}
{1506}{}{Ailie}
{1507}{}{New Reno}
{1508}{}{Area 51}
{1509}{}{Bridgeport}
{1510}{}{Las Vegas}
{1511}{}{Provo District}
{1512}{}{Hawthorne Military Base}
{1513}{}{Wendover}
{1514}{}{Salt Lake City}
{1515}{}{Old Rabbi}
{1516}{}{Governmental Vault}
{1517}{}{Gerlach}
{1518}{}{Uranium City}
{1519}{}{The Pound}
{1520}{}{Battle Mountain}
{1521}{}{Car Outta Power}
{1522}{}{Vault City}
{1523}{}{Traffic Jam}
{1524}{}{Operation of Wind of War}
{1525}{}{Black Rock}
{1526}{}{Desert}
{1527}{}{Mountain}
{1528}{}{Ruined city}
{1529}{}{Coast}
{1530}{}{Gas Station}
{1531}{}{Crossroad}
{1532}{}{Big hole}
{1533}{}{Dump of Tires}
{1534}{}{Tanker in the desert}
{1535}{}{Abnormal place}
{1536}{}{Lost Office}
{1537}{}{'The New Hopes' cafe}
{1538}{}{Giant Egg}
{1539}{}{Bobby's Hut}
{1540}{}{House on wheels}
{1541}{}{'Furthur'}
{1542}{}{Abandoned Ranger's Station}
{1543}{}{Picnic Area}
{1544}{}{Caravan}
{1545}{}{"Dear John"}
{1546}{}{Harrelson}
{1547}{}{Random encounter}
{1548}{}{Broken stagecoach}
