{100}{}{You see a Maintenance Computer.}
{101}{}{You see the service computer that is currently displaying the password prompt.}

#Dialogue:
{120}{}{You see Joshua's personal computer with access to the maintenance service server.}
{121}{}{Read about citizen regulations.}
{122}{}{Study entries about the wasteland around the Vault.}
{123}{}{Read the requisition for servants.}
{124}{}{Research the nearby nuclear power plant.}
{125}{}{Fake a requisition for a fuse from the warehouse.}
{126}{}{[Leave]}

{130}{}{The citizen regulations are long and boring, but Joshua has highlighted some points he deemed important: 1. Citizens must avoid direct physical contact. 2. Citizens are forbidden from leaving the City without authorization. 3. Discussion of the leadership's activities is only permitted during Council meetings. 4. Communication between subdivisions is only permitted through memorandum, unless in extreme circumstances. }
{131}{}{You study the reports from patrols around Vault City. This will help you in your journey.}
{132}{}{Outdoorsman skill is increased by 3%.}
{133}{}{The report concerns an abandoned nuclear power plant north of Vault City. There is not much information, because the high background radiation of the station prevents a detailed study. You copy the plant's coordinates to your Pip-Boy.}
{134}{}{The report concerns an abandoned nuclear power plant north of Vault City. There is not much information, because the high background radiation of the station prevents a detailed study.}

{135}{}{A memo from Joshua: "Requesting that five (5) servants be assigned to technical maintenance department for field work in conditions unsafe for citizens due to radiation."}
{136}{}{Read security department's response.}
{137}{}{"In order to fulfill your request, the medical department must provide confirmation that the servants in question are suitable for the specified assignment."}
{138}{}{Read medical department's response.}
{139}{}{"The medical department doesn't have the responsibility to answer to maintenance department. Please direct your request to the security department."}
{140}{}{Read security department's response.}
{141}{}{"In order to fulfill your request, the medical department must provide confirmation that the servants in question are suitable for the specified assignment."}
{142}{}{Huh.}

{150}{}{You need Joshua's personal credentials to access this computer. Obviously you won't get it from him, so you'll have to hack the system.}
{151}{}{Let's try it...}
{152}{}{You managed to crack the code and put an order to the warehouse! Unfortunately, that exceeded the permitted requisitions limit for this division. You probably shouldn't try this again.}
{153}{}{Great!}
{154}{}{You couldn't break into the system. Looks like you don't have enough knowledge in this area.}
{155}{}{}
{156}{}{Your intellectual abilities are clearly not high enough to grasp the concept of hacking.}
