{100}{}{You see: Medical Computer}
{101}{}{You see the clinic's computer - for authorized medical personnel only!}

#Overall
{120}{}{You see the medical computer. It contains clinical information about all citizens: reproduction charts, scheduled reports and other stuff you don't really care about.}
{121}{}{Read the medical report on the servants from Gerlach.}
{122}{}{Study research on mutations.}
{123}{}{Look through the blacklist.}
{124}{}{Study information from the primary database.}
{125}{}{[Leave]}

#Gerlachtown Servants
{130}{}{It turns out they're in a quite sorry condition.}
{131}{}{General conclusion.}
{132}{}{Mutagen analysis.}
{133}{}{Psychological analysis.}
{134}{}{Prescribed treatments.}
{135}{}{Recommendation for all citizens.}
{136}{}{Back to Main Menu.}

{140}{}{Upon arrival at the vault, the medical condition of Gerlach's residents was unsatisfactory, most likely due to the environmental ecology, hectic lifestyle, lifelong lack of medical support, and malnutrition. The estimated life expectancy of the average Gerlach resident did not exceed 50 years at best. Most would have died of cardiovascular abnormalities and malignant tumors seen in them. After the initial diagnosis, the servants were isolated to undergo disinfection. All of the servants are now under the observation of Dr. Willmouth.}
{141}{}{Most mutations are genetic in nature. They cannot be transferred - except by inheritance - and are a causal factor in the observed tumors. In 94% of cases the mutations are caused by radiation, and in the remaining and 6% of cases - by some unknown, but non-transferrable virus.}
{142}{}{Servants experience an identity crisis due to a lack of self-realization. Each of them suffers from severe depression. Servants are also psychologically unstable and prone to anger. They clearly lack self-control or restraints of their aggressive actions.}
{143}{}{Recommendations: 1. Regular check-ups with focus on cells mutation dynamics. 2. Regular treatments against radiation exposure. 3. Chemical suppression of emotions, particularly self-motivation and drive for self-realization. 4. Strict work schedule.}
{144}{}{Recommendations: 1. Avoid and and all physical contact with servants. In case of contact, wash point of contact with clean water and report to medical services immediately. 2. Avoid communicating with servants, apart from direct orders concerning work. 3. Do not show emotions around the servants, especially fear. 4. Suppress any attempts by servants to act of their own volition and prevent servants from expressing self-identity.}

#MC's Condition
{160}{}{Look through your medical history.}
{161}{}{You can't make heads or tails of this medical mumbo-jumbo.}
{162}{}{[Leave]}
{163}{}{You find Dr. Willmouth's report on your condition when you were brought to the city. When you arrived, your mental capabilities were equivalent to those of a two-year-old child. You could not eat, walk, talk, or remember anything. You were diagnosed with brain damage caused by a direct electromagnetic pulse transmitted by a microchip implanted in your brain, which had been removed during surgery. It was impossible to restore your memory, so Dr. Willmouth performed a special procedure to overwrite your brain with a new, artificial personality.}
{164}{}{Holy...}