{100}{}{A covered wagon.}
{101}{}{The wagon is tightly covered so no one could see what's inside.}
{102}{}{Hmm... Are you sure you want to do that?}
{103}{}{Not in combat!}
{104}{}{You won't get anything from this wagon.}

#ïîñëå þçàíüÿ ïîâîçêè
{105}{}{You see a caravan wagon, but it doesn't carry what many would think it should!}
{106}{}{[Hide in the wagon and wait for the caravan merchants to move out]}
{107}{}{Now I know who supplies drugs to Vegas!}
{108}{}{Leave it alone.}

{109}{}{Just a wagon. What's next?}
{110}{}{You discovered a drug supplier in Vegas. Interesting...would the police be interested in that?}

{111}{}{This wagon is now just junk, because it's owners are dead and the content is stolen.}
{112}{}{}
{113}{}{Just useless junk.}
{114}{}{It seems to be junk... Why are they transporting it?}
{115}{}{Empty.}
{116}{}{Keep an eye on the wagons, just in case...}
