{100}{}{This is the access console.}
{101}{}{You see the elevator access console.}
{102}{}{Access granted.}
{103}{}{Pressing random buttons has accomplished nothing. It's some kind of tricky system.}
{104}{}{This requires a scientific approach.}
{105}{}{Mechanical lockpicks won't help with electronic equipment.}
{106}{}{The system recognizes your pass and unlocks the elevator.}
{107}{}{You dashingly bypass the logic circuits by creating yourself an alternate account. The system unlocks the elevator.}
{108}{}{You try to bypass the system, but fail.}
{109}{}{This system is too complicated for you.}