{100}{}{You see an archive terminal.}
{101}{}{You see the terminal with City Hall's archives. To use it you're gonna need access rights.}
{102}{}{Only the archive staff have the access to use this terminal.}

{103}{}{This is a terminal storing a part of the City Hall archives in digital form.}
{104}{}{[Search Area 51 coordinates]}
{105}{}{[Quit]}

{106}{}{You got the coordinates. You can now travel to Area 51.}
{107}{}{[Search complete]}
