{100}{}{You see a terminal.} 
{101}{}{You see a terminal of emergency help for City Hall workers.}
{102}{}{Not during combat.}
{103}{}{Your knowledge in computer systems is not enough to crack this terminal.}
{104}{}{Scientific methods are required in order to use this terminal.}
{105}{}{A science skill is required.}
{106}{}{This terminal no longer works.}
{107}{}{Not functional.}
{108}{}{You managed to bypass the system. The emergency terminal gave you a stimpak, then tried to reboot - and shut down.}
{109}{}{Yes!}
