{100}{}{You see a table with parts.}
{101}{}{This table is littered with junk.}
{102}{}{This workbench is now useless.}
{103}{}{You cannot examine this table during combat.}

{110}{}{Someone has turned this table into a weapon workbench. You see a strange-looking weapon and some notes around, which clearly aren't enough to fix it.}
{111}{}{[Look closer]}
{112}{}{[Leave]}

{113}{}{This pistol is very unusual. And it's clearly an energy weapon. The barely noticeable inscription on the side reads, "Property of Area 51."}
{114}{}{[Next]}
{115}{}{The weapon won't fire, even though it's charged. It seems that only someone with a lot of experience in repairing energy weapons can handle this task.}
{116}{}{[Take the blaster]}

{117}{}{You take the gun with all of its parts, including the charging energy cells.}
{118}{}{The owner won't be happy, but I need it more!}
