{110}{}{"Our vending machine is happy to offer you a wide variety of exciting and informative publications!"}
{111}{}{[Select publication]}
{112}{}{[Leave the vending machine alone]}
{113}{}{Sorry, there's currently no item in the machine.}
{114}{}{"To make a purchase, press the button with a number of the desired publication and put the required amount of money into the money slot." (The price of each item is $500)}
{115}{}{"Thank you for your purchase! We wish you a pleasant reading."}
{116}{}{[Back to the choice of publications]}
{117}{}{[Empty slot]}
{118}{}{.}
{119}{}{"Please put the required amount of money into the money slot."}
{120}{}{I obviously don't have that kind of money.}
{121}{}{[Pay]}
{122}{}{> Next list}
{123}{}{< Previous list}