{100}{}{After a few days of rest, you are released from the vault. Your mind feels clear and healthy, but you can't remember anything.} 
{101}{}{Home again... But you're not allowed inside.}

#Для финальной карты
{102}{}{Did a hurricane pass through the city, or was it just a massacre?!}
{103}{}{Looks like I missed something.}
{104}{}{The elevator is out of order.}
{105}{}{Electrical current is running through these exposed cables.}

{106}{}{Your mission is complete.}

#Женские реплики:
{1103}{}{Looks like I missed something.}
