{100}{}{You see the quartermaster.}
{101}{}{You see the quartermaster looking at you with a smirk.}

{110}{}{[Lazily sighs and crosses his fingers on his stomach] Well, I'm listening.}
{111}{}{Let's trade.}
{112}{}{As you wish. I'm leaving.}

####################################################################
# About Cola - the beginning
####################################################################

{113}{}{I am the official representative of the Nuka-Cola factory, and I have a very profitable proposition for you!}
{114}{}{Very nice, but I'm not the one to talk about it.}
{115}{}{Uh... But who is then?!}
{116}{}{General Wesker. He runs the Wind of War, that's who you should address. You will have to pass through sentries to get to the base, go north until you stop at the barricade, then enter the headquarters building to the right. Inform the guards about why you came.}
{117}{}{Okay.}

####################################################################
# About the stones with symbols
####################################################################

{118}{}{I found this stone with a coat of arms on it. You know what it is?}
{119}{}{[With eyes bulging he studies the stone for some time] You know, I won't tell you what it is, but I'll buy it. I can only say that you *definitely* can't make any use of it.}
{120}{}{Hmm, you sound pretty sure of that. And what's the price?}
{121}{}{Two hundred.}
{122}{}{I'll think about your offer.}
{123}{}{Okay. Let's exchange.}
{124}{}{What's there to think about? For you it's a useless piece of rock. And I'll even pay a little for it. Who else would buy a piece of rock?}
{125}{}{Fair enough, let's exchange.}
{126}{}{Hmm, is there a catch? Maybe I shouldn't be in a hurry to make this exchange.}
{127}{}{Careful! He might roll away into some crevice!}
{128}{}{Don't worry! I'll get it back...}
{129}{}{Here's the money. By the way, if you find the second one bring it to me, okay?}
{130}{}{Okay.}
{131}{}{I decided to sell you this stone. Here.}
{132}{}{I have found the second stone! Will you buy it?}
{133}{}{Well, thank you!}
{134}{}{You're welcome... though it's all strange somehow. I have a feeling that something very important has been hidden from me. Goodbye.}

####################################################################
# Purchasing a batch of grenades
####################################################################

{135}{}{Do you have *special* weapons for a *special* price?}
{136}{}{Heh... Funny. All the *special* weaponry is stocked in the base warehouses, here we have only the most primitive weapons. Our boss is no fool, he realizes that sold weapons could be used directly against us, so it's the other way around - he's the one buying "special weapons for special prices". Got it?}
{137}{}{As if you couldn't take something from the warehouse. [wink]}
{138}{}{Okay.}
{139}{}{Well... I can [leans towards you and lowers his voice] get some plasma grenades. Small loss, no one will notice. And as for the rest - I'll pass. It's too dangerous.}
{140}{}{I agree on the grenades. How much time do you need?}
{141}{}{No, I don't need this.}
{142}{}{Two days and 2500 bucks. It's expensive, considering the actual cost of the grenades, but the risk is on me and I have to grease some palms, you know what I'm saying?}
{143}{}{That's 1000, you'll get the rest when the product is ready.}
{144}{}{Never mind then.}
{145}{}{Don't mess with me. I don't like those kind of jokes.}
{146}{}{Okay.}
{147}{}{Very well, that's fair. I'll do it. The box will be yours, but no earlier than two days.}
{148}{}{All right.}
{149}{}{Well, what about my order?}
{150}{}{I have it... In a special place. Where no one can find it. Where's my money?}
{151}{}{Here, $1500.}
{152}{}{I'll go get the money.}
{153}{}{A good deal, but I don't dare do it again. It wasn't easy.}
{154}{}{Okay.}

####################################################################
# Quest for alcohol
####################################################################

{155}{}{You sell mainly household items. What about drinks? Is there, for instance, a bar or a cafe?}
{156}{}{No. We have the dining room but keep it for us to use, the outsiders are by themselves. Basically all we need we get with caravans. They usually stop here on the way between Vegas and Reno.}
{157}{}{Basically? So you're still missing something?}
{158}{}{Funny you ask. Our guys from the barracks sometimes come here to look for a bit of "liquid joy", but caravans usually don't transport alcohol through the Wasteland.}
{159}{}{So, the warriors need alcohol?}
{160}{}{I would take a batch of, say, 30 bottles of beer... At a higher price.}
{161}{}{30 bottles of beer... I'll write it down.}
{162}{}{I got a box of beer.}
{163}{}{That's great! Look at how it foams! [He quickly hides the box of bottles] Okay, here's the money. And one more thing - don't talk about it. We've got some pedantic bookworms here, you know. [Makes a nasty face and waves his hand in a sign of contempt]}
{164}{}{Okay.}
{165}{}{You've brought the goods to the customer.}
{166}{}{I can count! No need to lie to me!}
{167}{}{Oops, sorry.}

{168}{}{Maybe I can, but with suck-ups like you, you never know what'll happen. Maybe you'll run to the General and tell on me? I heard you're on friendly terms with him now.}
{169}{}{[Suspiciously looks around] I don't know what you're talking about. All sorts of easy riders wander through here - one wants a grenade, another wants a grenade launcher. But you won't get far in this place doing stuff like that. So don't bother me and be content with what you see on the counter.}

####################################################################
# Selling Cola
####################################################################

#End of quest dialogue:
{173}{}{About selling Nuka-Cola. Wesker gave the nod.}
{174}{}{Yeah, I know. Let's get straight to the details. I hope you have an established line of delivery?}
{175}{}{I can hire a caravan...}
{176}{}{[Interrupting] Good. I don't want to have a headache selling *your* product. My job is to turn the product into profits, not bother myself with new problems.}
{177}{}{So that's how it is...}
{178}{}{I have enough stuff to do without your Cola. It's not Las Vegas. On the other hand, I would love to add a new product to the stock, because it will be another reason for the Wasteland people to come to my shop. Moreover, I even know where to get a vending machine for drinks. This would optimize our cooperation.}
{179}{}{Op-ti-mi... Where do...}
{180}{}{So! [his eyes light up with thirst for potential profit] It's your burden to deliver the goods. You load the bottles right into the machine and pick up the revenue from it. I'll pick up my share myself. It's simple. Come back with your Cola in a day, I'll have everything prepared.}
{181}{}{I'm glad to hear it. See you.}

####################################################################
# Missing inventory
####################################################################

{216}{}{Hey, that's my stuff!}
{217}{}{Are you sure?! Anyway, it's not my problem - I've bought these things honestly. If you want to something returned you'll have to buy it.}
{218}{}{Grr...}

#Discount on the product
{220}{}{You won't believe it! We were just talking about you. I've heard a lot of good things about you. Our guys know and respect you. I've thought about it and decided it would be fair to lower my prices for you...a little.}
{221}{}{That's nice.}
{222}{}{Hey, you bought a car from my friend? Damn, you must have been saving for a year to do that. Look, I sell different things that might be useful in a trip. If you want to buy something - just choose, I'll give you a discount, out of respect!}
{223}{}{Just great!}

####################################################################
# About the shelter
####################################################################

{300}{}{Where'd you all come from?}
{301}{}{Well, we came from a small vault, and when it became too crowded... Damn, I probably shouldn't have told you that. Any way, if you want to snatch some technology from there, then I have to disappoint you - the shelter is inhabited by mutants, and the entrance is caved in. Besides, we took out everything we could from there way back then.}
{302}{}{}
{303}{}{Can you take me there?}
{304}{}{Idle curiosity, just ignore me.}

{305}{}{Hell no! Sometimes mutants are spotted around the shelter, and I don't want to meet them. However, I could show the place on a map, but certainly not just for a "thank you" in return. Say, for 300 bucks.}
{306}{}{Yeah, sure.}
{307}{}{}
{308}{}{}
{309}{}{}
{310}{}{Can you take me to the vault?}
{311}{}{Okay, I'll go to the technician.}
{312}{}{All right, have it your way. That's $300, now show it.}
{313}{}{I'll try to find another way. Bye.}

####################################################################
# Women's replies
####################################################################

{1118}{}{I found a stone with the coat of arms on it. Do you know what it is?}
{1131}{}{I decided to sell you this piece of stone. Here.}
{1132}{}{I have found the second stone! Will you buy it?}
{1140}{}{I agree on the grenades. How much time do you need?}
{1162}{}{I got a box of beer.}
