{100}{}{You see the quartermaster.}
{101}{}{You see the quartermaster looking at you with a smirk.}

{110}{}{[Lazily sighs and crosses his fingers on the stomach] Well, I'm listening.}
{111}{}{Let's trade.}
{112}{}{As you wish. I'm leaving.}

####################################################################
# About Cola - the beginning
####################################################################

{113}{}{I am the official representative of the Nuka-Cola factory, and I have a very profitable proposition for you!}
{114}{}{Very nice, but I'm not the one to talk about it.}
{115}{}{Uh... But who is then?!}
{116}{}{General Wesker. He runs the Wind of War, that's him who you should address. You will have to pass through sentries to the base, go up to the North until you stop at the barricade, then enter the headquarters building to the right. Inform the guards about why you came.}
{117}{}{Okay.}

####################################################################
# About the stones with symbols
####################################################################

{118}{}{I found a stone with the coat of arms on it. You know what is it?}
{119}{}{[With bulging eyes he explores the stone for some time] You know, I won't tell you what it is, but I'll buy it. I can only say that you *definitely* can't make any use of it.}
{120}{}{Hmm, what confidence. And what is the price?}
{121}{}{Two hundred.}
{122}{}{I'll think about your offer.}
{123}{}{Okay. Let's exchange.}
{124}{}{What is there to think about? For you it's a useless piece of stone. And I'll even pay for it a little. *Who else* will buy a piece of stone?}
{125}{}{Fair enough, let's exchange.}
{126}{}{Hmm, isn't there a catch? Perhaps, I will not hurry with the exchange.}
{127}{}{Careful! He can roll away into some crevice!}
{128}{}{Don't worry! I'll bring it back...}
{129}{}{Here is the money. By the way, if you find the second one, also carry it to me, okay?}
{130}{}{Okay.}
{131}{}{I decided to sell you this piece of stone. Here.}
{132}{}{I have found the second stone! Will you buy it?}
{133}{}{Well, thank you!}
{134}{}{You are welcome... Although it's all somehow strange. I have a feeling that something very important has been hidden from me. Goodbye.}

####################################################################
# Purchasing a batch of grenades
####################################################################

{135}{}{Do you have *special* weapons for *special* price?}
{136}{}{Heh... Funny. All the *special* weaponry is stocked in the base warehouses, and here is only the most primitive. Our boss is no fool, he realizes that sold weapons could be used directly against us, so it's the other way around - that's him who is buying "special weapons for special prices". Got it?}
{137}{}{As if you can't take something from the warehouse. [wink]}
{138}{}{Okay.}
{139}{}{Well... I can [leans towards you and lowers his voice] get some plasma grenades. Small loss, no one will notice. And as for the rest - I'll pass. It is dangerous.}
{140}{}{I agree on the grenades. How much time do you need?}
{141}{}{No, I do not need this.}
{142}{}{Two days and 2500 bucks. It's expensive, considering the actual cost of the grenades, but the risk is on me and I have to share with others, you know what I'm saying?}
{143}{}{That's 1000, you'll get the rest when the product is ready.}
{144}{}{Never mind then.}
{145}{}{Don't mess with me. I don't like this kind of jokes.}
{146}{}{Okay.}
{147}{}{Very well, that's fair. I'll do it. The box will be yours, but not earlier than in two days.}
{148}{}{All right.}
{149}{}{Well, what about my order?}
{150}{}{I have it... In a special place. No one will find. Where's my money?}
{151}{}{Here 1500.}
{152}{}{I'll go get the money.}
{153}{}{A good deal, but I won't dare to do it again. It wasn't easy.}
{154}{}{Okay.}

####################################################################
# Quest for alcohol
####################################################################

{155}{}{You sell mainly household items. What about drinks? Is there, for instance, a bar or a cafe?}
{156}{}{No. We have the dining room but keep it for us to use, the newcomers are by themselves. Basically all we need we get with caravans. They usually stop here on the way between Vegas and Reno.}
{157}{}{Basically? So you're still missing something?}
{158}{}{Funny that you're asking. Our guys from the barracks sometimes come here to look for a bit of the "liquid joy", but caravans usually don't transport such drinks through the Wasteland.}
{159}{}{So, the warriors need alcohol?}
{160}{}{I would take a batch of, say, 30 bottles of beer... At a higher price.}
{161}{}{30 bottles of beer... Will write it down to not forget.}
{162}{}{I got a box of beer.}
{163}{}{That's great! How it foams! [quickly hides the box of bottles] Okay, here's the money. And one more thing - don't talk about it. We've got some pedantic bookworms here, you know. [Makes a nasty face and waves his hand in a sign of contempt]}
{164}{}{OK.}
{165}{}{You've brought the promised to the customer.}
{166}{}{I can count! No need to lie to me!}
{167}{}{Oops, sorry.}

{168}{}{Maybe I can, but with the suck-ups like you, you never know what might happen. Maybe you will run to our General and denunciate me? I heard you're now on friendly terms with him.}
{169}{}{[Suspiciously looks around] I don't know what you're talking about. All sorts of easy riders wander here - one wants grenade, another wants a grenade launcher. But you won't go far in this town doing stuff like this. So don't bother me and be content with what you see on the counter.}

####################################################################
# Selling Cola
####################################################################

#End of quest dialogue:
{173}{}{About selling Nuka-Cola. Wesker gave the nod.}
{174}{}{Yeah, I know. Let's get straight to the details. I hope you have an established line of delivery?}
{175}{}{I can hire a caravan...}
{176}{}{[Interrupting] Good. I don't want to have a headache selling *your* product. My job is to turn the product into profits, not to bother myself with new concerns.}
{177}{}{So that's what you all about...}
{178}{}{I have enough other stuff to do without your Cola. It's not Las Vegas. On the other hand, I would love to add a new product to the stock, because it will be another reason for the Wasteland people to come to my shop. Moreover, I even know where to get a vending machine for drinks. This would optimize our cooperation.}
{179}{}{Op-ti-mi... Where do...}
{180}{}{So! [his eyes light up with thirst for potential profit] It's your burden to deliver the goods. You will load the bottles right into the machine and pick the revenue from it. I'll pick up my share myself. It's simple. Come back with Cola in a day, I'll have everything prepared.}
{181}{}{I'm glad to hear it. See you.}

####################################################################
# Missing inventory
####################################################################

{216}{}{Hey, that's my stuff!}
{217}{}{For sure?! Anyway, it's not my problem - I've bought these things in an honest way. If you want to return something you have to buy it.}
{218}{}{Grr...}

#Discount on the product
{220}{}{You just won't believe it! We were talking about you right now. I've heard a lot of good things about you. Our guys know and respect you. I've thought about it and decided it would be fair to lower my prices for you a little.}
{221}{}{That's nice.}
{222}{}{Hey, you bought a car from my friend? Damn, you must have been saving for a year to do this. Look, I sell different things that might be useful in a trip. If you want to buy something - just choose, I'll give you a discount as a sign of respect!}
{223}{}{Just great!}

####################################################################
# About the shelter
####################################################################

{300}{}{Where'd you all come from?}
{301}{}{Well, we came from a small vault, when it became crowded... Damn, I probably shouldn't have told you. In any way, if you want to snatch some technology from there, then I have to disappoint you - the shelter is inhabited by mutants, and the entrance is caved with stones. Besides, we brought out everything we could from there back then.}
{302}{}{}
{303}{}{Can you take me there?}
{304}{}{Idle curiosity, just ignore me.}

{305}{}{Hell no! Sometimes around the shelters the mutants are noticed, and I don't want to meet them. However, I could show this place on the map, but of course, not just for "thank you" in return. Let's say for 300 bucks.}
{306}{}{Yeah, sure.}
{307}{}{}
{308}{}{}
{309}{}{}
{310}{}{Can you take me to the vault?}
{311}{}{Okay, I'll go to the technician.}
{312}{}{All right, have it your way. That's $300, now show it.}
{313}{}{I'll try to find another way. Bye.}

####################################################################
# Women's replics
####################################################################

{1118}{}{I found a stone with the coat of arms on it. Do you know what it is?}
{1131}{}{I decided to sell you this piece of stone. Here.}
{1132}{}{I have found the second stone! Will you buy it?}
{1140}{}{I agree on the grenades. How much time do you need?}
{1162}{}{I got a box of beer.}
