{100}{}{Caravaneer Bibbit.}
{101}{}{You see a caravaneer, one of the many.}

{105}{}{Thank you so much!}

#Плавающие реплики:
{110}{}{I fucked up royally!}
{111}{}{How could I run up into this!}
{112}{}{18 carat run of bad luck...}
{113}{}{When will all this bad luck end?!}
{114}{}{Goodbye my friends...}
{115}{}{::sighs heavily::}
{116}{}{I won't be a caravaneer anymore!}
{117}{}{Or maybe someone's still alive? But...}
{118}{}{In the next two days - meet a new face among the poor...}
{119}{}{Hey! Help me reach the New Vegas! Please!}
{120}{}{Lose your goods - and fellow caravaneers won't even look at your direction!}
{121}{}{Or what if my pals actually reached Vegas?}
{122}{}{Damn, I'm the most ill-fated caravaneer ever!}
{123}{}{It happened the first time with us!}
{124}{}{And we were on the top in Vegas...}
{125}{}{Damned raiders took the most valuable stuff.}
{126}{}{I'm in dire straits. That's it. Put me right in the coffin.}
{127}{}{And how well it all started!}
{128}{}{We even transported some thing to Salt Lake...}
{129}{}{Why no one wants to take me to Vegas? I'm an experienced caravaneer!}

#Начальный диалог:

{200}{}{[You see a worried caravaneer] Uh... Hello, wanderer! I guess, you came to me for a reason but, believe me, I'm not in the right mood to help anyone.}
{201}{}{What does this mean?}
{202}{}{Sounds like it is you who need help.}
{203}{}{I only want to ask a few questions.}
{204}{}{I understand. I won't disturb you anymore.}

{205}{}{I should hurry to reach Vegas to meet my fellows.}
{206}{}{Bye.}

{210}{}{Questions? Well, it's not hard.}
{211}{}{Who are you?}
{212}{}{What do you do here?}
{213}{}{Tell me your story.}
{214}{}{For a second thought, I don't need anything.}

{215}{}{My name's Bibbit. I'm a caravaneer. What else to say? Cool guy and all that, but it's just by the way.}
{216}{}{Licking my wounds after a tough caravan run. Wasteland appeared to be ruthless bitch this time. If not for my survival skills, I'd be already eaten by pig rats or someone even worse.}
{217}{}{I'm in big trouble, that's it. But it's a long story, as I can't do otherwise. I'll tell for a small fee... He-he. I'm joking. But I really need money. A lot.}
{218}{}{If you need money then sell something.}
{219}{}{}

{220}{}{Well, it's not the best situation. Shit happens.}
{221}{}{That's your problems. I'm interest in different things.}
{222}{}{Could you elaborate?}
{223}{}{Help? Me?! Not that I was some wimp or piss-pants, but it's a difficult situation, you see. And in this case... I need support, so to speak.}
{224}{}{Tell me more.}
{225}{}{You are useless to me, then. Bye.}

{226}{}{What kind of support?}
{227}{}{Then tell me, what kind of help do you need.}
{228}{}{200 bucks and nothing else!}

{229}{}{Why do you need money in such a hurry?}
{230}{}{Alright, here's your 200 bucks.}
{231}{}{Two hundreds for a story? That's too much!}
{232}{}{I knew it. Another beggar!}
{233}{}{No, look for money by yourself, I'm leaving.}

{234}{}{You think I'm enjoying this?! All my peanuts in my life were honest earned, and now I'm in dire situation with no way out.}
{235}{}{How much do you need?}
{236}{}{I need to get to the Vegas badly. But caravaneers won't help for free, they ask for a prepayment. Everyone here stand for themselves. That's it.}
{237}{}{So how much do you need?}
{238}{}{You're a caravaneer?! So what's stopping you from reaching Vegas?}
{239}{}{By myself?! Oh no, I'm not that stupid. My fellows are lost, and other caravans refuse to pick me up without prepayment. Because I'm a stranger to everyone else.}

{240}{}{Too bad, the only one thing I could offer is this comic book.}
{241}{}{Just what I need. Here's your 200 bucks for a comic book.}
{242}{}{No, I don't need it.}
{243}{}{I'd better go, until you start to sell me your pants.}

{244}{}{Well, that's fair. But I don't care. Now I can pay for the escort - that's what matters. Thanks, wanderer.}
{245}{}{Now will you tell me what happened with your caravan?}
{246}{}{You're welcome. Happy trails.}

{247}{}{Seriously?! You just give me two hundreds?! You are the nicest fellow I have ever met in the wasteland! No kidding!}
{248}{}{Why not! But it's a long story.}
{249}{}{Go on.}
{250}{}{Then tell me another time.}

#История каравана
{300}{}{Now, we transported the goods from Reno to Vegas. And, like always, stopped by Wind of War to refill our water resources and sleep.}
{301}{}{What, too scared to sleep in the wastes?}
{302}{}{I understand. It is reasonable.}
{303}{}{Tell me another time, I feel it's gonna take lots of time.}

{304}{}{We're not, but why should we hand over our asses to the mutants?}
{305}{}{Well yeah, pretty reasonable. What's next?}
{306}{}{Oh well. Excuse approved. What's next?}

{307}{}{We slept here, on the railway station. By the morning, we were ready to hit the road. But suddenly some soldier comes to us and starts asking about where we a heading to and what are we transporting. And with these militaries you tend to keep your mouth shut.}
{308}{}{And why all these soldiers are so insolent?}
{309}{}{Does this story lead to something or not?}
{310}{}{Sound familiar. Oh, this militant to the bone...}

{311}{}{Well, you go and ask them. They, probably, think that they are in charge here and run the show. Did you see that guy with the broken face in the next room? Here's what it is.}
{312}{}{Of course, I told you it's gonna be a long story!}
{313}{}{Oh, these soldiers... But let's get back to your caravan.}

{314}{}{Right. But I'm not about it. So, this guy comes to us, starts to get on our nerves with his questions, all that important, so sick of him... And also drunk. We barely managed to bundle him out. It's good that we didn't get into a fistfight.}
{315}{}{And what this all about?}
{316}{}{Things may go worse. You were lucky.}
{317}{}{Wait a bit, I'm trying to recall the sequence of events...}
{318}{}{Yeah-yeah, sure.}

{319}{}{Then we moved to Vegas, we chose the path along the route. But then our leader said that raiders typically hide along the routes. Let's go through the desert, he says, off the road.}
{320}{}{Yeah-yeah, I've seen such leaders already. Any signs of danger - and...}
{321}{}{Hmm. Safer, but slower.}
{322}{}{Hey, don't start it! If you ever come into such scrapes a couple of times, you'll also become cautious.}
{323}{}{Okay-okay, go on.}

{324}{}{We then told him, go around the route - and it's a day to lose. So we reached the gas station in the evening, at nightfall.}
{325}{}{You like talking to yourself?}
{326}{}{Gas station?}
{327}{}{Go on.}

{328}{}{The old gas station. We always make a stop here on the way from Wind of War to Vegas. Convenient checkpoint. It's always nice to sleep under the roof than in the tent in the middle of desert.}
{329}{}{I'm gonna sleep because of your story myself... Eh... Go on!}
{330}{}{Of course.}

{331}{}{As we went to sleep... And then! I hear - someone's coming!}
{332}{}{Well finally, something interesting in your story begins!}
{333}{}{Wow! Who was that?}

{334}{}{While other were sleeping, I, to avoid raising a noise, got up, went outside, and right in the face - BA-A-AM!!! Shin, fucking, boot - right in the loft! I even fell on the floor! Then all the guys jumped up, grabbed the guns. Well, I thought, the fun part begins.}
{335}{}{Gunfight?!}

{336}{}{These bastards surrounded us from all sides. Two of us got shot first, others ran away somewhere. Good thing I ran away into the bu... Eh... As I said, I know a lot of tricks - disappeared in the most appropriate time.}
{337}{}{What's next?}

{338}{}{I don't know myself! Darkness surrounds, shots, bustle. Well, guys fled, and raiders there, at the gas station, took down someone and started to hammer.}
{339}{}{And that's all you story?}
{340}{}{That's it?}

{341}{}{Then I came back here. [Speaks quietly] But I don't believe one bit, that these are raiders. They don't speak like that, you know! And they are not that well organized, and not that clever. A strange situation!}
{342}{}{That's how it was...}
{343}{}{So I was left with nothing and lost contact with my fellows. Hopefully, a trip to Vegas will give me a second chance.}
{344}{}{Hmm, sad story. Well, happy trails.}
{345}{}{It happens. Well, now you are on your own.}

{346}{}{Thank you for listening! If necessary, you'll find me in Vegas.}
{347}{}{Yeah. Goodbye.}
{348}{}{And by the way, what was that caravan you worked for?}

{349}{}{Hello, wanderer!}

#Определение каравана
{350}{}{You were saying that you're a caravaneer...}
{351}{}{Yes, that's it... To be precise, was. And now I'm not so sure. Our guys ran away and I don't know if they still live.}
{352}{}{And what was that caravan?}
{353}{}{Right, bye.}

{354}{}{A small brigade. Called "Speed Hawk".}
{355}{}{I know them. Four of your friends have recently been parked in Vegas.}
{356}{}{Oh, so you don't know... Friend, be strong, all your comrades were killed. Everyone of them.}
{357}{}{Sounds familiar. I'll return if I remember.}

{358}{}{You've found the last remaining member of "Speed Hawk".}
{359}{}{It's a great news! I'll go to them as soon as possible! Thank you, wanderer, I'm so glad I met you!}
{360}{}{You don't want to add anything?}
{361}{}{So long.}

{362}{}{Are you sure? How did you know?!}
{363}{}{I... Eh... Was there and saw everything.}
{364}{}{Well, rumors are afloat. I'll check it out and come back.}
{365}{}{Ah, come on, don't worry! They're alive, your comrades are waiting for you in Vegas.}
{366}{}{Well, I was prepared for the worst... I guess lights of Vegas shine not for me. Local caravaneers won't take on the job if they'll know my story. That's a superstition, my friend. Well, I'd better head to Reno and try to improve my life there.}
{367}{}{That's up to you to decide, I've done my job.}

#Female character
{1200}{}{[You see a worried caravaneer] Uh... Hello, wanderer! I guess, you came to me for a reason but, believe me, I'm not in the right mood to help anyone.}
{1232}{}{I knew it. Another beggar!}
{1236}{}{I need to get to the Vegas badly. But caravaneers won't help for free, they ask for a prepayment. Everyone here stand for themselves. That's it.}
{1244}{}{Well, that's fair. But I don't care. Now I can pay for the escort - that's what matters. Thanks, wanderer.}
{1247}{}{Seriously?! You just give me two hundreds?! You are the nicest chick I have ever met in the wasteland! No kidding!}
{1311}{}{Well, you go and ask them. They, probably, think that they are in charge here and run the show. Did you see that guy with the broken face in the next room? Here's what it is.}
{1322}{}{Hey, don't start it! If you ever come into such scrapes a couple of times, you'll also become cautious.}
{1329}{}{I'm gonna sleep because of your story myself... Eh... Go on!}
{1346}{}{Thank you for listening! If necessary, you'll find me in Vegas.}
{1359}{}{It's a great news! I'll go to them as soon as possible! Thank you, wanderer, I'm so glad I met you!}
{1362}{}{Are you sure? How did you know?!}
{1363}{}{I... Eh... Was there and saw everything.}
{1366}{}{Well, I was prepared for the worst... I guess lights of Vegas shine not for me. Local caravaneers won't take on the job if they'll know my story. That's a superstition, my friend. Well, I'd better head to Reno and try to improve my life there.}
{1367}{}{That's up to you to decide, I've done my job.}