{100}{}{You see a caravaneer Bobby.}
{101}{}{You see a badly beaten up caravan merchant.}

#Ñëó÷àéíûå ôðàçû:
{110}{}{::moans::}
{111}{}{Oh, my teeth hurt...}
{112}{}{Time to quit this job.}
{113}{}{It's the first time in my career!}
{114}{}{They should all be court-martialed!}
{115}{}{How could anyone do that!}
{116}{}{Damn, I feel like shit...}
{117}{}{Just like that, in front of everyone!}
{118}{}{Bastards! Bastards!}
{119}{}{They're worse than raiders!}
{120}{}{Even the Reno thugs are not that fierce!}
{121}{}{How did I ever get in such a mess?}
{122}{}{As soon as I'm on my feet, I'll go straight to Vegas. Right away!}
{123}{}{Just started talking - and got punched right in the face!}
{124}{}{Why me?!}
{125}{}{I'm going to avoid this settlement from now on.}

#Íà÷àëî äèàëîãà
{200}{}{[You see a beaten up man. He's hurt, he groans, but no one helps him for some reason.]}
{201}{}{Don't twitch, I'll heal you. I'm a doctor.}
{202}{}{Hold on, I'll call the doctor to help.}
{203}{}{Well, I have nothing to do with, and I don't care.}

{204}{}{[Pulls your hand away] What kind of doctor are you?! Don't bother, you'll make everything worse.}
{205}{}{Then, you'll continue to suffer.}
{206}{}{[Angrily pulls your hand away] I don't accept handouts from military favorites. Leave me alone!}
{207}{}{If that's what you want...}

{208}{}{Thanks for the help.}
{209}{}{See you in Vegas, maybe.}

#Ïîñëå îêàçàíèÿ ìåäïîìîùè
{210}{}{Oh... That's so much better. Thanks for the help.}
{211}{}{Now tell me, who beat you up like this?}

{212}{}{A couple of soldiers from the garrison! Who else?}
{213}{}{I bet you provoked them. Am I right?}
{214}{}{For real? How could they! They didn't have any reason to do that, right?}
{215}{}{Pretty strange behavior for a paramilitary settlement. Aren't they supposed to protect the caravan merchants here? }

{216}{}{Are you crazy?! Why would I do that?! No matter what you do, you'll still get a boot in your face...and for no reason.}
{217}{}{You're a good person, but you still don't get it. They don't need a *reason*. They'll come up with something if necessary.}
{218}{}{Yes, many still share this common misconception. But the truth is, they are no longer people who care about your safety. Just give them a reason, and they'll rob you blind.}
{219}{}{Why are the locals so fierce?}
{220}{}{Because they can be. They think they're better than everyone. Whoever has better weapons and thicker armor is the hero of the wasteland, get it? So, they act like they own these parts.}
{221}{}{So, why did they do this to you?}

{222}{}{For my gun and my money. I shouldn't have shown it off. Somebody told the military, and soon this Jimmy and his gang showed up. They demanded I hand over my gun. I refused, and this is the result.}
{223}{}{Tell me about your gun.}
{224}{}{Who's this Jimmy and where do I find him?}
{225}{}{Is it forbidden to carry a gun in these parts?}
{226}{}{Now I get it. Okay, bye.}
{227}{}{A "Desert Eagle" with a leather grip and improved barrel. Mutated ant drops dead from a single shot. Great gun.}
{228}{}{One of the privates. He always hangs around the checkpoint. Young and brassy bastard.}
{229}{}{No! Not exactly. It's forbidden only within their garrison. They'll shoot you up for this. But this is the parking area, the same rules don't apply here. But does Jimmy care?}

#Çàâåðøåíèå êâåñòà
{230}{}{Hey, thanks for the help. Soon I'll leave this place and try to not come back.}
{231}{}{Hey, thanks for the help. Soon I'll leave this place and try to not come back. I miss my gun, though. It's not reasonable to walk around the wasteland without a gun.}
{232}{}{Right. Bye.}

{233}{}{That Jimmy got what he deserved and now wants to send his apologies.}
{234}{}{That Jimmy got what he deserved. We had a... Explanatory conversation.}
{235}{}{Tell me again, why did they beat you up.}

{236}{}{For real? You're a tough one! Who else could dare to nail a soldier to the wall... Oh, by the way, did you get my stuff back?}

{237}{}{Here's your 200 bucks and a handgun.}
{238}{}{Here's your 200 bucks, but he didn't give the pistol.}
{239}{}{Here's your handgun, but money weren't part of the deal.}
{240}{}{Too bad, it's too late - I couldn't retrieve nothing.}

{241}{}{My "Desert Eagle"?! Thank you! I'm so glad I met you! By the way, keep the money. Consider it my appreciation for you help.}
{242}{}{Thanks. Take care.}
{243}{}{I knew it! They *already* managed to spend all the money. Though, I didn't have much cash. I'll earn twice as much on the next run. More importantly, my beloved "Desert Eagle" returned to me! You just saved me from depression! Thanks.}
{244}{}{Yeah. Take care.}
{245}{}{Well, I have to say goodbye to my "Desert Eagle"... That's pretty depressing. You know, whatever happened there, I guess they got what they deserved. Here, take the half. [gives 100 bucks] You earned it. Thank you for everything! See you in Vegas, maybe.}
{246}{}{Maybe so. Goodbye.}
{247}{}{Uh, bad luck. At least I'm at peace, knowing that they got what they deserved. Thank you for everything! Others would've just passed by. See you in Vegas, maybe.}
{248}{}{You're welcome.}
