{100}{}{You see a caravaneer Bobby.}
{101}{}{You see a badly beaten up caravan merchant.}

#Случайные фразы:
{110}{}{::moans::}
{111}{}{Oh, my teeth hurt...}
{112}{}{Time to quit this job}
{113}{}{It's the first time in my career}
{114}{}{All of them should be put under tribunal!}
{115}{}{How can you do that!}
{116}{}{Damn, I feel like shit...}
{117}{}{Just like that - in front of everyone!}
{118}{}{Bastards! Bastards!}
{119}{}{They're worse than raiders}
{120}{}{Even the Reno thugs are not that fierce}
{121}{}{How did I ever get plunged so hard}
{122}{}{As soon as I stand on my feet - I'll go straight to Vegas immediately. Immediately!}
{123}{}{Just started talking - and got one right in the face!}
{124}{}{Why me?!}
{125}{}{From now on I should sidestep this settlement}

#Начало диалога
{200}{}{[You see a beaten up man; he's hurt, he groans, but no one helps him for some reason]}
{201}{}{Don't twitch, I'll heal you. I'm a doctor.}
{202}{}{Hold on, I'll call the doctor to help.}
{203}{}{Well, I have nothing to do with, and I don't care.}

{204}{}{[Pulls your hand away] What kind of doctor are you?! Don't bother, you'll make everything worse.}
{205}{}{Then, you'll continue to suffer.}
{206}{}{[Angrily pulls your hand away] I don't accept handouts for militaries' favorites. Leave me alone!}
{207}{}{So this is what you like...}

{208}{}{Thanks for the help}
{209}{}{See ya at Vegas, maybe.}

#После оказания медпомощи
{210}{}{Oh... That's so much better. Thanks for the help.}
{211}{}{Now tell me, who painted you like this?}

{212}{}{A couple of soldiers from the garrison! Who else?}
{213}{}{I bet you yourself provoked them. Isn't that right?}
{214}{}{For real? How could they! They didn't have the reason to do that, right?}
{215}{}{Pretty strange discipline for militarized settlement.}

{216}{}{Are you out of your mind?! Why should I do that?! It doesn't matter how you act, you'll still get a boot in the face for just like that.}
{217}{}{You're a good person, and still don't get it. They don't need a *reason*. They'll come up with something when needed.}
{218}{}{Yes, and many are still pretty delusional. But the truth is that it's already in the past. Those are not people who think about your safety. Just give them a reason - they'll rob you to the skin.}
{219}{}{Why are the locals so fierce?}
{220}{}{Because of disorder. And they think high about themselves. Who has better gun and thicker armor is the hero of wasteland. Get it? So, they behave like masters in these parts.}
{221}{}{So why did they do this to you?}

{222}{}{For my pistol and some change. I shouldn't have shown it before them. Someone ratted to militaries, and soon came that Jimmy with his gang. Requested to hand over the gun. I refused - and here's what happened.}
{223}{}{Tell me about your gun.}
{224}{}{Who's that Jimmy and where to find him?}
{225}{}{Is this forbidden to carry a gun in these parts?}
{226}{}{Now I get it. Okay, bye.}
{227}{}{"Desert Eagle" with leather grip and improved barrel. Mutated ant falls dead from one shot. Great gun.}
{228}{}{One of privates. He always hangs around the checkpoint. Young and brassy bastard.}
{229}{}{No! You can't walk around carrying weapons only within their garrison. They'll shoot you up for this. As this is free parking, no such rules applied here. But does Jimmy care?}

#Завершение квеста
{230}{}{Hey, thanks for the help. Soon I'll leave this place and try to not come back.}
{231}{}{Hey, thanks for the help. Soon I'll leave this place and try to not come back. I miss my gun, though. It's not reasonable to walk in the wastes without a gun.}
{232}{}{Right. Bye.}

{233}{}{That Jimmy got what he deserved and now wants to send his apologies.}
{234}{}{That Jimmy got what he deserved. We had a... Explanatory conversation.}
{235}{}{Tell me again, why did they beat you up.}

{236}{}{For real? You're tough one! Who else could crank this out and press the soldier to the wall... Oh, by the way - did you manage to get back my belongings?}

{237}{}{Here's your 200 bucks and a handgun.}
{238}{}{Here's your 200 bucks, but he didn't give the pistol.}
{239}{}{Here's your handgun, but money weren't part of the deal.}
{240}{}{Too bad, it's too late - couldn't retrieve nothing.}

{241}{}{My "Desert Eagle"?! Thank you! I'm so glad I met you! By the way, keep the money, consider it my appreciation for you help.}
{242}{}{Thanks. Take care.}
{243}{}{I knew it! They *already* managed to spend all the money. Though, I didn't have much cash. I'll earn twice as much from the first run. More importantly, my beloved "Desert Eagle" returned to me! You just saved me from depression! Thanks.}
{244}{}{Yeah. Take care.}
{245}{}{Well, I have to say goodbye to my "Desert Eagle"... I think, I'll fall into depression soon enough... You know, whatever happened there, I guess they got what they deserved. Here, take the half. [gives 100 bucks] You earned it. Thank you for everything! See you in Vegas, maybe.}
{246}{}{Maybe so. Goodbye.}
{247}{}{Uh, bad luck. At least I'm in peace knowing that they got what they deserved. Thank you for everything! Other would've just passed by. See you in Vegas, maybe.}
{248}{}{You're welcome.}