{100}{}{Caravaneer Biggie.}
{101}{}{You see a gloomy caravaneer.}
{102}{}{I was waiting for you at the fence, but you never came. After a "prank" like this, I don't want to talk to you.}
{103}{}{Hi.}

#About Hawk
{120}{}{Yeah, there's one here. But I don't think you will find him useful. The guy's tragedy is that his caravan was ambushed by raiders. He is the only one survived.}
{121}{}{I still need to talk to him. Tell me, where can I find him?}
{122}{}{Do you know anything about that attack?}
{123}{}{I don't know where exactly he is now, but surely it's somewhere around the station. Just ask around.}
{124}{}{Just what I heard from the survivor. The raiders attacked at night, shooting everyone. He managed to escape. What kind of raiders they were, he couldn't say. That's it.}
{125}{}{}
{126}{}{I see. No more questions.}
{127}{}{Have you met someone from the "Speed Hawk" caravan?}

#Main replies
{250}{}{Great, another wanderer. What do you want from a simple worker?}
{251}{}{Can you tell me about this settlement?}
{252}{}{You said you wanted to get back at the technician for the broken wagon.}
{253}{}{Nothing. You don't need to be so aggressive.}
{254}{}{Nothing.}

#About the Wind of War
{255}{}{A shitty place. We made a stop here only to get some water. If not for other caravaneers, like hell I would be here.}
{256}{}{Why?}
{257}{}{The local military are notorious bastards, they have problems in their own community. Despite acting like they protect people and shit, some of them can jam you in a corner and rob you blind. And you won't be able to prove anything. That's why the caravanners here always keep their company, even to the toilets.}
{258}{}{It's that bad? Okay, I'll keep that in mind.}
{259}{}{And you shouldn't tell me what to do!... Okay, I'm sorry. I'm a little on edge after a recent story.}
{260}{}{Care to tell me about it?}
{261}{}{There's this local idiot. He's praised as a tech-savvy guy around here, and we were told he was building some kind of complicated transportation thing in his garage, so maybe he knows his stuff, we thought. So we pay him to fix the wagon. And you know what? He hits the wagon with a hammer, and the wagon falls apart. And then he just throws his hands up - "not my problem," he said, "the wagon was old, it couldn't stand the treatment". Can you imagine?}
{262}{}{But you have to agree - the equipment is really old. You knew there was a risk.}
{263}{}{What a bastard! He should have been punched in the face for this.}
{264}{}{It's hard to say who is right and who is not.}
{265}{}{Come on! He could pass on the offer, or maybe even fix what he broke. But no - he just said "screw you" and threatened us with his friends from the garrison. What an asshole...}
{266}{}{That's what I think, too! But it's not the case. Instead of fixing what he broke, he just said "screw you" and threatened us with his friends from the garrison. What an asshole...}
{267}{}{Well, yeah. Everyone says that, until something like that happens to them. But you know what he did? Instead of fixing what he broke, he just said "screw you" and threatened us with his friends from the garrison. What an asshole...}
{268}{}{What did you do?}
{269}{}{We had to deal with it ourselves. We fixed the wagon as best we could. As for the technician, it would be great to get back at him somehow, as a goodbye present. Some kind of a sabotage, or something.}
{270}{}{Sabotage is a dangerous thing. Although, perhaps, maybe he deserves that. Good luck.}
{271}{}{Okay, the story is clear. Bye.}

#Robbery
{275}{}{As long as I don't get punched in the face, I'm in. Do you have any suggestions?}
{276}{}{Of course. I want to rob this son of a bitch. Will you help me climb over the fence to his garage?}
{277}{}{Are you afraid of a little fighting? Nevermind then.}

{278}{}{Are you out of your mind? Stealing is risky business!}
{279}{}{If you want to get some revenge, this is your only chance.}
{280}{}{Trust me, I know what to do.}
{281}{}{Then the deal is off.}
{282}{}{Yes... You're right. Okay, I agree.}
{283}{}{Maybe, but this just won't do. I won't participate in the theft. Too much of a risk.}
{284}{}{I understand your doubts, but you should trust me. I know what to do.}
{285}{}{Then let's not waste any more time. We have a perfect opportunity now.}
{286}{}{Stay here while I scout the situation.}
{287}{}{Why would I trust some stranger? Forget it. If I'm to trust someone, then it would be the caravaneers and those who help them.}
{288}{}{Do you even want revenge? Or you are only good for talking? Think about it - it's your only chance.}

{290}{}{You convinced the caravaneer to commit robbery. He will wait for you near the fence next to the garage.}
{291}{}{Yeah, it would be very good...}

{292}{}{This is the best place to climb over the fence. It looks like there are stairs on the other side, so it should be easy to get back.}
{293}{}{Help me to climb up and get back to the tent. You saw nothing and heard nothing.}
{294}{}{It is too early to commit sabotage. I'll tell you when we start.}
{295}{}{For your actions, you lose karma, but increase your sneak skill by 2%.}
{296}{}{Calm down, don't panic. We're just walking around...}

#Women's replies
{1250}{}{Great, another wanderer. What do you want from a simple worker?}
{1278}{}{Are you out of your mind? Stealing is a risky business!}
