{100}{}{Caravaneer Bibbit.}
{101}{}{You see a caravaneer, one of many.}

{105}{}{Thank you so much!}

#Ïëàâàþùèå ðåïëèêè:
{110}{}{I fucked up royally!}
{111}{}{How could I get myself into this!}
{112}{}{18 carat run of bad luck...}
{113}{}{When will all this bad luck end?!}
{114}{}{Goodbye, my friends...}
{115}{}{::sighs heavily::}
{116}{}{I'm not even a caravaneer anymore!}
{117}{}{Maybe someone's still alive? But...}
{118}{}{In the next two days greet a new face among the poor...}
{119}{}{Hey! Help me reach New Vegas! Please!}
{120}{}{Lose your goods - and fellow caravaneers won't even look at you!}
{121}{}{But what if my pals actually reached Vegas?}
{122}{}{Damn, I'm the most ill-fated caravaneer ever!}
{123}{}{This is the first time such a thing has happened to us!}
{124}{}{We have been on the top in Vegas...}
{125}{}{Damned raiders took the most valuable.}
{126}{}{I'm in dire straits. That's it. Put me in the coffin.}
{127}{}{To think it all started so well!}
{128}{}{We were transporting that thing to Salt Lake...}
{129}{}{Why does no one want to take me to Vegas? I'm an experienced caravaneer!}

#Íà÷àëüíûé äèàëîã:

{200}{}{[You see a worried caravaneer] Uh... Hello, wanderer! I guess you came to me for a reason, but believe me, I'm not in the mood to help anybody.}
{201}{}{What do you mean?}
{202}{}{Sounds like it is you who needs help.}
{203}{}{I only want to ask a few questions.}
{204}{}{I understand. I won't disturb you anymore.}

{205}{}{I have to hurry to get to Vegas to meet my fellows.}
{206}{}{Bye.}

{210}{}{Questions? Well, it's okay then.}
{211}{}{Who are you?}
{212}{}{What are you doing here?}
{213}{}{Tell me your story.}
{214}{}{On a second thought, I don't need anything.}

{215}{}{My name's Bibbit. I'm a caravaneer. What else is there to say? Cool guy and all, but that's beside the point.}
{216}{}{Licking my wounds after a tough caravan run. Wasteland turned out to be a ruthless bitch this time. If not for my survival skills, I'd be already eaten by pig rats or something worse.}
{217}{}{I'm in big trouble, that's my story. If you want details, it's gonna take a while, as I'm unable to tell it any other way. It'll cost you only a small fee... Hehe. I'm just kidding. But I really need the money. A lot.}
{218}{}{If you need money, sell something.}
{219}{}{}

{220}{}{Sounds like a tough situation. Shit happens, I guess?}
{221}{}{That's your problem. I'm interested in something else.}
{222}{}{Could you elaborate?}
{223}{}{Help? Me?! Not that I am a wimp or piss-pants, but it's a difficult situation, you see. And in this case... I do need a little support, so to speak.}
{224}{}{Tell me more.}
{225}{}{You are useless. Bye.}

{226}{}{What kind of support?}
{227}{}{Then tell me what kind of help do you need.}
{228}{}{200 bucks! That's it!}

{229}{}{Why do you need money for?}
{230}{}{Alright, here's your 200 bucks.}
{231}{}{Two hundred for a story? That's too much!}
{232}{}{I knew it. Another beggar!}
{233}{}{No, look for the money yourself, I'm leaving.}

{234}{}{You think I'm enjoying this?! Every peanut in my life was honestly earned, and now I'm in a dire situation with no obvious way out.}
{235}{}{How much do you need?}
{236}{}{I need to get to Vegas very badly. But the caravaneers won't help for free, they ask for payment in advance. Here it's every man for himself. That's how it is.}
{237}{}{How much do you need?}
{238}{}{You're a caravaneer, right? So, what's stopping you from reaching Vegas?}
{239}{}{By myself?! Oh no, I'm not that stupid. My fellows are lost, and other caravans refuse to pick me up without pre-paying, because I'm a stranger to everyone else.}

{240}{}{Too bad, the only one thing I could offer is this comic book.}
{241}{}{Just what I need. Here's your 200 bucks for a comic book.}
{242}{}{No, I don't need it.}
{243}{}{I'd better go, until you start to sell me your pants.}

{244}{}{Okay, that's fair. Now I can pay for the escort - that's what really matters. Thanks, wanderer.}
{245}{}{Now, are you going to tell me what happened to your caravan?}
{246}{}{You're welcome. Happy trails.}

{247}{}{Seriously?! You just give me two hundred?! You are the nicest fellow I have ever met in the wasteland! No kidding!}
{248}{}{Why not! But it's a long story.}
{249}{}{Go on.}
{250}{}{Then tell me another time.}

#Èñòîðèÿ êàðàâàíà
{300}{}{So, we were transporting goods from Reno to Vegas. And, as always, we stopped at Wind of War to refill our water supply and get some sleep.}
{301}{}{What, too scared to sleep in the wasteland?}
{302}{}{I understand. It is a smart move.}
{303}{}{Tell me about it some other time. I have a feeling it's gonna be very long.}

{304}{}{We're not, but why should we hand our asses over to the mutants just like that?}
{305}{}{Okay, pretty reasonable. What's next?}
{306}{}{Good excuse. What's next?}

{307}{}{We spent the night here at the train station. By morning we were ready to leave. But suddenly a soldier comes up to us and starts asking us where we're going and what we're transporting. And you should keep your mouth shut with this military.}
{308}{}{Why are these soldiers so insolent?}
{309}{}{Does this story go somewhere or not?}
{310}{}{Sounds familiar. Oh, those militants to the bone...}

{311}{}{Ask them. They probably think they're in charge here and run the show. Did you see that guy with the broken face in the next room? That's how it is.}
{312}{}{Of course, I told you it's gonna be a long story!}
{313}{}{Oh, those soldiers... But let's get back to your caravan.}

{314}{}{Right. So, this guy comes to us, starts to get on our nerves with his questions, all self important, ugh... And he was also drunk. We barely managed to fend him off. It's a good thing we didn't get into a fistfight.}
{315}{}{So?}
{316}{}{Things could become worse right there. You were lucky.}
{317}{}{Wait a moment, I'm trying to recall the sequence of events...}
{318}{}{Sure.}

{319}{}{Then we moved on to Vegas, taking the route along the highway. But then our leader said that's where the raiders usually set up ambushes. Let's go through the desert, he said, off-road, he said.}
{320}{}{Yeah-yeah, I've seen such leaders. Any signs of danger - and...}
{321}{}{Hmm. Safer, but slower.}
{322}{}{Hey, don't start! If you get into that kind of trouble more than once, you'ld be cautious, too.}
{323}{}{Okay-okay, go on.}

{324}{}{We told him that changing the route meant losing a day. So we got to the gas station in the evening, by dusk.}
{325}{}{You really like talking to yourself, don't you?}
{326}{}{Gas station?}
{327}{}{Go on.}

{328}{}{An old gas station. We always make a stop there on the way from Wind of War to Vegas. A convenient checkpoint. It's always nice to sleep under a roof than in a tent in the middle of the desert.}
{329}{}{I'm gonna fall asleep because of your story... Eh... Go on!}
{330}{}{Of course.}

{331}{}{So, we went to sleep... When suddenly I hear - someone coming!}
{332}{}{Finally, something interesting in your story!}
{333}{}{And? Who was it?}

{334}{}{While the others were asleep, I got up, went outside, and suddenly got it right in the face - BA-AAM!!! The shin of a fucking boot! And I'm falling on the floor! All the guys jumped up and grabbed their guns. Well, I thought, here comes the fun part.}
{335}{}{A shootout?}

{336}{}{These bastards surrounded us on all sides. Two of ours were shot immediately, the rest started running away. Good thing I made it into the bushe- Uhh, as I said, I know many tricks, so I disappeared at the most appropriate moment.}
{337}{}{What happened next?}

{338}{}{I don't know! Darkness, shots, bustle. The raiders at the gas station were still kicking the shit out of someone when I left.}
{339}{}{And that's all you story?}
{340}{}{That's it?}

{341}{}{Then I made it back here. [He speaks quietly] But I don't believe they were raiders one bit. They don't talk like that, you know! And they're not as well organized, nor as smart. It's too strange!}
{342}{}{So that's what happened...}
{343}{}{So I was left with nothing and lost contact with my fellows. Hopefully, a trip to Vegas would give me a second chance.}
{344}{}{Quite a story. Happy trails then.}
{345}{}{Things happen. Well, now you are on your own.}

{346}{}{Thank you for listening! If you ever need me, you can find me in Vegas.}
{347}{}{Yeah. Goodbye.}
{348}{}{By the way, what was that caravan you worked for?}

{349}{}{Hello, wanderer!}

#Îïðåäåëåíèå êàðàâàíà
{350}{}{You were saying that you're a caravaneer...}
{351}{}{Yes, that's it... I mean, I was. Now I'm not so sure. Our guys ran away and I don't know if they are still live.}
{352}{}{And what was that caravan called?}
{353}{}{Right, bye.}

{354}{}{"Speed Hawk". A pretty small team.}
{355}{}{I know them. Four of your friends were parked in Vegas recently.}
{356}{}{Oh, so you don't know... Friend, be strong, all your comrades were killed. Everyone.}
{357}{}{Sounds familiar. I'll return if I remember something about it.}

{358}{}{You've found the last remaining member of "Speed Hawk".}
{359}{}{Great news! I'll go to them as soon as possible! Thank you, wanderer. I'm so glad I met you!}
{360}{}{You don't want to add anything?}
{361}{}{So long.}

{362}{}{Are you sure? How do you know that?!}
{363}{}{I... Eh... Have been there. I saw everything that's left.}
{364}{}{Well, rumors are afloat. I'll check it out and come back.}
{365}{}{Ah, come on, don't worry! They're alive. Your comrades are waiting for you in Vegas.}
{366}{}{Well, I was prepared for the worst... I guess lights of Vegas shine not for me. Local caravaneers won't take on the job if they'll know my story. That's a superstition, my friend. Well, I'd better head to Reno and try to improve my life there.}
{367}{}{That's up to you to decide, I did my job.}

#Female character
{1200}{}{[You see a worried caravaneer] Uh... Hello, wanderer! I guess you came to me for a reason, but believe me, I'm not in the mood to help anybody.}
{1232}{}{I knew it. Another beggar!}
{1236}{}{I need to get to Vegas very badly. But caravaneers don't help for free, they ask for a prepayment. Here it's every man for himself. That's how it is.}
{1244}{}{Okay, that's fair. But now I can pay for the escort - that's what really matters. Thanks, wanderer.}
{1247}{}{Seriously?! You just give me two hundred?! You are the nicest fellow I have ever met in the wasteland! No kidding!}
{1311}{}{Ask them. They probably think that they are in charge here and run the show. Did you see that guy with the broken face in the next room? Here's how it is.}
{1322}{}{Hey, don't start! If you get into that kind of trouble a couple of times, you'll become cautious, too.}
{1329}{}{I'm gonna fall asleep because of your story... Eh... Go on!}
{1346}{}{Thank you for listening! If you ever need me, you can find me in Vegas.}
{1359}{}{Great news! I'll go to them as soon as possible! Thank you, wanderer, I'm so glad I've met you!}
{1362}{}{Are you sure? How did you know?!}
{1363}{}{I... Eh... Have been there. I saw everything that's left.}
{1366}{}{Well, I was prepared for the worst... I guess lights of Vegas shine not for me. Local caravaneers won't take on the job if they'll know my story. That's a superstition, my friend. Well, I'd better head to Reno and try to improve my life there.}
{1367}{}{That's up to you to decide, I did my job.}
