{100}{}{Caravan merchant Billy.}
{101}{}{You see a bored caravan merchant. He fiddles something in his hands.}
{102}{}{Hi}

#Разговор
{110}{}{[Caravaneer curiously examines the round sanded rock with an emblem on it]}
{111}{}{What is this?}
{112}{}{[Leave it]}

{113}{}{[Shrugs] I don't know. I found in the ruins.}
{114}{}{Then just give it to me. You don't need it anyway.}
{115}{}{Oh, I get it: a junk collector, ha-ha. How long do you earn for living with this?}
{116}{}{Well, forget it.}

{117}{}{[Instinctively puts the rock away from you] I don't... And why you do?}
{118}{}{Don't know too. But I'll think something out, rest assured.}
{119}{}{[Instinctively puts the rock away from you and pronounces articulately] I am caravan guard.}
{120}{}{Ooh, look how proud are we. Can't even give up on a piece of rock.}
{121}{}{Sorry for touching your pride. So will you give me this useless rock?}

{122}{}{Okay then. Beat me at cards, and the rock is yours.}
{123}{}{Aren't you too attached to junk?  You looked like a normal guy...}
{124}{}{I can just buy it. Will 50 bucks be sufficient?}
{125}{}{Alright, let's play.}
{126}{}{Maybe next time. And now I need to go.}
{127}{}{I'd give it, but not to someone like you.}
{128}{}{Well, I'm sorry. I'm not in the right mood. Usually I get along well with caravaneers.}
{129}{}{Ah yes, it's you... Other caravaneers told me about you. They say, you helped someone of us. Alright. Here's the rock, take it. I don't need it anyway.}
{130}{}{Thanks, friend.}
{131}{}{That's better. Without wasting more words it'd be even better.}
{132}{}{[Sceptically raises his brow] Doesn't seem like.}
{133}{}{Alright, forget it. Will you give me the rock or not?}

{134}{}{You serious? How surprising... Okay, let's do it this way.}
{135}{}{Here's the money. Now give me the rock.}
{136}{}{Pay money for this garbage?! Nah, probably some blackout... We'll talk later, when I come back to normal.}
{137}{}{And you really believed that? What kind of idiot would buy this worthless piece of junk? Think about it and hand it over peacefully.}
{138}{}{[Squeezes the rock in his fist] Forget it. And why are you so fond of this rock all of a sudden? I don't like it.}
{139}{}{Alright, you convinced me. Here's your 50 bucks for the rock.}
{140}{}{Okay-okay, so be it. I'll play cards with you for this junk.}
{141}{}{Well then, watch and wonder how nice amount of money walks away from you, loser. [walk away]}
{142}{}{Actually I lied about the money. Maybe, we'll play cards?}

{143}{}{[Pulls cards out of his pocket, thinks a bit looking at you frowningly, then still puts a pack on the table] We'll play fair. If I find out that you are cheating - your loss.}
{144}{}{Okay. Let's do it...}
{145}{}{Hey, why don't I just buy a rock for 50 bucks?}
{146}{}{Not so fast. Place your bet of first 5 bucks or I won't play.}
{147}{}{Okay-okay. I'll win anyway.}
{148}{}{You know, I'd jump right into a card game any time, but I need to do some things first. We'll play later.}
{149}{}{Beating you is as easy as a child. Wanna try again?}
{150}{}{Yes, I'll achieve what I want! Let's do it again...}
{151}{}{Phew... It was a good game. I'm even exhausted a bit, from stress. Here's your fair prize.}
{152}{}{Take care.}
{153}{}{No, I had enough of these cards today.}

{154}{}{Take it. I don't need it anyway.}
{155}{}{Bye.}

{156}{}{I see you have unhealthy craving for hoarding. I should go away, in case you'll turn out to be aggressive, all of a sudden.}
{157}{}{Then I don't need it. Good luck.}
{158}{}{Whatever you say. Guard. We'll leave it at that and part ways.}
{159}{}{I don't ask you about what it looks like. Though, can't expect anything different from you. Bye.}
{160}{}{Think whatever you want. I don't care. Bye.}
{161}{}{Me too. So let's just end this meaningless chat.}
{162}{}{[Blushes from anger] I AM - A CARAVAN - GUARD!!! I'm not a hobo! And not the junk collector! You want this rock, yes? You want?! Then TAKE IT! [throws it in the far end of the room]}
{163}{}{Hey, easy! Oh man... Now I have to look everywhere...}