{100}{}{Caravaneer Biggie.}
{101}{}{You see a gloomy caravaneer.}
{102}{}{I was waiting for you at the fence, but you never came. After such a "prank" I don't want even to talk to you.}
{103}{}{Hi.}

#About Hawk
{120}{}{Yeah, there's one here. But I don't think you will find him useful. The guy's tragedy is that his caravan was ambushed by raiders. He is the only one survived.}
{121}{}{I still need to talk to him. Tell me where is he?}
{122}{}{Do you know anything about this attack?}
{123}{}{I don't know exactly where he is now, but surely somewhere in the station. Ask around among the caravaneers.}
{124}{}{Only what I heard from the survivor. Raiders attacked at night, shot everyone, and he managed to escape. What kind of raider he couldn't say. That's all.}
{125}{}{}
{126}{}{I see. No more questions.}
{127}{}{Have you met someone from the "Speed Hawk" caravan ?}

#Main replics
{250}{}{That's great, wanderer. What do you want from a simple worker?}
{251}{}{Can you tell me about this place?}
{252}{}{You said you wanted to take revenge from the technician for the broken vehicle.}
{253}{}{Nothing. But you need to hold back the voice.}
{254}{}{Nothing.}

#About the Wind of War
{255}{}{A shitty place. We came here only to have a little water gain. If not for other caravaneers, like hell I would be here by myself.}
{256}{}{Why?}
{257}{}{Local military men are known bastards. They have discord in their community. They can trap you in the corner and rob you to the bone. And you can prove nothing. So the caravaneers here always go in company, even to the toilet.}
{258}{}{Is it all that bad? Okay, I'll take a note of this.}
{259}{}{Hey, look how clever we are!.. Okay, I'm sorry. I was on edge after one story.}
{260}{}{Can you tell?}
{261}{}{There is one local idiot. He was praised as a person versed in tech, we were told that he was building some thing of the complexity of Vertibird in his garage. So we paid him to fix the wagon. And what? He hits the wagon with a sledgehammer, and the wagon collapses. Then he throws his hands up - not my problems, he says, the wagon was old, it could not stand handling. Can you imagine?!}
{262}{}{But you have to agree - the equipment is really old. You did know that there was a risk.}
{263}{}{What a bastard! He should have been punched to the face for this.}
{264}{}{It's hard to say who is right and who is not.}
{265}{}{Come on! He could reject the offer or rebuild what he broke. But no - he just said "screw you" and threatened us with his friends from the garrison. Such a bitch...}
{266}{}{That's what I think, too! But it's not the case. Instead of fixing what was broken, he just said 'screw you' and threatened us with his friends from the garrison. Such a bitch...}
{267}{}{Well, Yes. Everyone says that, until something like that happens to them. But you know what he did? Instead of fixing what was broken, he just said 'screw you' and threatened us with his friends from the garrison. Such a bitch...}
{268}{}{What did you do?}
{269}{}{We had to deal with it on our own. We fixed the wagon somehow, as for the technician, that would be great to sabotage him somehow, as a goodbye present.}
{270}{}{Sabotage is a dangerous thing. Although perhaps in some ways you're right. Good luck.}
{271}{}{Okay, the story is clear. Bye.}

#Robbery
{275}{}{If I don't get punched in the face, I would be happy. Do you have any suggestions?}
{276}{}{Exactly. I want to rob the son of a bitch. Will you help me climb over the fence to his garage?}
{277}{}{You're afraid of fighting? Nevermind then.}

{278}{}{Are you out of your mind? Stealing is a risky business!}
{279}{}{If you want to avenge him, then this is your only chance.}
{280}{}{Trust me, I know what to do.}
{281}{}{Then the offer is canceled.}
{282}{}{Yes... You're right. OK, I agree.}
{283}{}{Maybe so, but those things will not work. I won't participate in the theft. And I won't take any risks}
{284}{}{I understand your doubts, but trust me. I know what to do.}
{285}{}{Then let's not waste time. The conditions now are suitable for plunder.}
{286}{}{You should stay here while I scout out the situation.}
{287}{}{How will I be able to trust a passing stranger? Forget it. If I'm to trust someone, then it would be the caravaneers and those who help them.}
{288}{}{Do you even want that revenge? Or you're only full of big talk? Think about it - it's your only chance.}

{290}{}{You convinced the caravaneer to commit robbery. He will wait for you near the fence next to the garage.}
{291}{}{Yeah, it would be so pleasant...}

{292}{}{This is the best place to climb over the fence. It seems that on the other side there are stairs, so it will not be difficult to go back.}
{293}{}{Help me to climb up and get back to the tent. You saw nothing and heard nothing.}
{294}{}{It is too early to commit sabotage. I'll tell you when you can begin.}
{295}{}{For your actions, you lose karma, but increase sneak skill by 2%.}
{296}{}{Calm, don't give yourself away. We're just walking around...}

#Women's replics
{1250}{}{That's great, wanderer. What do you want from a simple worker?}
{1278}{}{Are you out of your mind? Stealing is a risky business!}
