{100}{}{You see Freckles.}
{101}{}{You see a body. You're not sure if it's dead or alive.}
{102}{}{I told 'em! I told 'em countless times! Bun no one would listen...}
{103}{}{Dang it! How did this happen?!}

#Плавающие фразы
{110}{}{Oh! My knee!}
{111}{}{Asleep at the wheel or something?! Don't text and drive, hot damn you!}
{112}{}{Hey, you! It's your fault, so help me now!}
{113}{}{What if it was a little kid, not just me?}
{114}{}{Get me out of here immediately!}
{115}{}{Well... Please...}
{116}{}{Are you just going to stand there and stare?!}
{117}{}{Maybe it's time you did something already?}

#Диалог
{150}{}{Damn tourists! What's the rush? Someone's about to give birth or something?!}
{151}{}{Oh, I'm sorry, pal, let me help you.}
{152}{}{Why don't YOU watch where you're going!}

{153}{}{Nah, don't fret! I still got some good bones left.}
{154}{}{Good to hear that.}
{155}{}{I told 'em as far as 50 years ago - put some traffic lights or at least put road markings, damn you, but no! No one would listen to old Freckles. Damn pencil pushers!}
{156}{}{Uhh...}
{157}{}{And this is not even the last time! How many more will fall victims to these bad roads?}
{158}{}{But...}
{159}{}{All it takes is a can of paint... But no! They're too busy. So much for the "Capital Wasteland" they call themselves. Gosh!}
{160}{}{Easy, old man. I don't think what you're saying is still relevant.}
{161}{}{Huh? What? [Shakes his head] You'll see, another half a century and you'll remember my words. I got to go now. Take care and don't run over any more old men!}
{162}{}{Yeah.}

{170}{}{Hey, where did you get your license, cut it out of a cereal box? Remember that the pedestrian is always right. Don't they teach kids that nowadays? This world has gone to shit...}
{171}{}{So, are you going to just lie there on the road?}
{172}{}{Nah, it's okay! I still got some good bones left. Thanks for not hitting my head.}
{173}{}{You're welcome...}

#†ен реплики
{1170}{}{Hey, where did you get your license, cut it out of a cereal box? Remember that the pedestrian is always right. Don't they teach kids that nowadays? This world has gone to shit...}
