{100}{}{You see a private.}
{101}{}{You see an ordinary private... Although with face like this he looks more like a common criminal.}

#Когда видит и бежит к чузу
{102}{}{There he is! Freeze! I said stop right there!!!}

#Пытаются запрятать за решетку
{110}{}{Hey you! Put your hands in the air! You're under arrest!}
{111}{}{Hey, easy, man! I didn't do anything!}
{112}{}{Bullshit!}

{113}{}{We'll see about that...}
{114}{}{[You are taken to the local prison cell and stripped of all belongings.]}
{115}{}{Looks like you were not only arrested, but outright robbed!}

#Female character
{1102}{}{There she is! Freeze! I said stop right there!!!}
{1110}{}{Hey you! Put your hands in the air! You're under arrest! }
{1111}{}{Hey, easy, man! II didn't do anything!}