{100}{}{You see Jessica's brother.}
{101}{}{You see a Wind of War citizen.}
{102}{}{You're not so bad for an outsider.}
{103}{}{Go back to the wasteland, ape! This is no place for you!}
{104}{}{What are we going to do now without our sister?!}
{105}{}{*Script error*}

{108}{}{It's not like I advocate violent measures, it just... happened, you know. Look, outsider, here's $1,000 to keep your mouth shut, all right?}
{109}{}{I know how to keep my mouth shut when the money's right...}

#Äèàëîã
{110}{}{Well, well. What do we have here? Another radiated bonebag. He-he... Like, a bag with bones in it! [talks to his brother] Did you hear that, brother!? A bonebag! Pft-ha-ha-ha-ha!}
{111}{}{You can laugh all you want, funny guys. When Robert takes away your sister, you won't be laughing anymore.}
{112}{}{If my presence amuses you so much, then I'll just get out of here.}
{113}{}{Yeah, right. I better go before I have to hear any more of your "jokes".}

{114}{}{Huh. I don't get it. Robert? That mongrel is at it again?!}
{115}{}{Yup. Where do you think the keys to your house went?}
{116}{}{Robert? What Robert? You must have misheard something.}

{117}{}{Ha! [talks to his brother] Hey, bro! Looks like it's time to empty somebody's pockets! That scum of the earth is asking for it again! [He turns to you] But mark my words, stranger. If we don't find the keys on him, it'll be your last joke.}
{118}{}{Way to go, fighters! Off to war!}

#Ñêðèïòîâàÿ ñöåíà
{120}{}{Where do you think you're going, you piece of brahmin dung?}
{121}{}{Hey... What do you want, guys?}
{122}{}{To go through your pockets, in case some stray keys wandered in there!}
{123}{}{I... Don't have your keys...}
{124}{}{Shut up!}
{125}{}{ }
{126}{}{Take this, dweeb!}
{127}{}{Oh shit! What have we done?!}
{128}{}{Let's split before we get busted!}

#Female character
{1108}{}{It's not like I advocate violent measures, it just... happened, you know. Look, outsider, here's $1,000 to keep your mouth shut, all right?}
{1117}{}{Ha! [talks to brother] Hey, bro! Looks like it's time to empty somebody's pockets! That scum of the earth is asking for it again! [He turns to you] But mark my words, stranger. If we don't find the keys on him, it'll be your last joke.}
