{100}{}{You see Jessica.}
{101}{}{You see an inhabitant of the Wind of War.}
{102}{}{Good day to you, wanderer.}
{103}{}{What have they done!? I don't want to see them anymore!}

#Brothers see the char when s/he tries to speak with Jessica
{110}{}{Hey, you! Stay away from my sister!}
{111}{}{Uh, sorry... They don't like it when I talk to strangers}
{112}{}{Hey! We didn't let you talk to her! Get away from her!}

#If the char is a male
{120}{}{Oh, you shouldn't talk to me. My brothers went really crazy after that story with Robert. Now I'm not allowed to talk to strangers.}
{121}{}{I just wanted to say that Robert prepares the escape. Be ready!}
{122}{}{}
{123}{}{So, who are you, a prisoner?}
{124}{}{Well, I'm not going to insist.}
{125}{}{What? But... [whispering] He really decided to do it? Ah, that would be great, I'm so desperate to sit in four walls.}
{126}{}{Rather a slave. Brothers keep me locked up and not allow to talk to other men, except of "purebred" military. And it's hard to argue with them. Oh, stop it, or they will kick you out of the house.}
{127}{}{That's great. Wait.}
{128}{}{Quite strict morals...}

#If char is a female
{130}{}{Hello, stranger. Glad to see you, my brothers went really crazy after that story with Robert. They let me speak only with women and "purebred" military, and those, believe me, are not the best company.}
{131}{}{I just wanted to say that Robert prepares the escape. Be ready!}
{132}{}{"Purebred"? How do they define it?}
{133}{}{So who are you, a prisoner?}
{134}{}{Who's Robert?}
{135}{}{I'll talk to you later.}

{140}{}{What? But... [whispering] He really decided to do it? Ah, that would be great, I'm so desperate to sit in four walls.}
{141}{}{You will have to sit a little longer. Just wait.}
{142}{}{Well, judging by the number of relatives who came from the Wasteland, we are one of the most pure-blooded families around - all members of our family are direct descendants of the first settlers. And on this stupid basis brothers created the idea of the "pure breed".}
{143}{}{Rather a slave. Brothers keep me locked up and not allow to talk with other men, except of "purebred" military. And it's hard to argue.}
{144}{}{[Folds her hands and narrows the eyes] Oh, he is my symbol of hope. Although because of him my brothers are no longer allow me to communicate with outsiders, I've not been satisfied with the local life. I want freedom and love. Robert is the man who gave me all this. But don't tell my brothers, they can't stand him.}

#Women's replics
{1102}{}{Well, hello, wanderer.}
