{100}{}{You see Robert.}
{101}{}{You see a resident of the Wind of War.}
{102}{}{::grabs his head:: My life is meaningless...}
{103}{}{Please don't let us down, it's our only chance}

#Acquaintance
{110}{}{Thank you, wanderer. Thank you for everything!}
{111}{}{You are welcome.}

{120}{}{Oh, I'm surprised to see a kindred soul in the closed area.}
{121}{}{What are you talking about?}
{122}{}{Well, not often you meet here people from behind the perimeter. I'm one of the few who... Uh, I got a lucky chance to live here.}
{123}{}{I see. Can I ask you about Wind of War?}
{124}{}{Well, then nice to meet you. Maybe I'll stop by sometime to visit.}

{125}{}{Of course! Really looking forward to - there's always something to talk about with strangers.}
{126}{}{Uh, okay.}

{130}{}{Well, shall we sit down and talk?}
{131}{}{I'd like to know more about the settlement. Tell me, please.}
{132}{}{Tell me about yourself. As I see, you are not the local, right?}
{133}{}{}
{134}{}{Thanks for the hospitality, but I gotta go.}

{140}{}{Now we are in a closed community. Only the military and their families live here. Outside you'll find nothing except ruins. Oh, and also, the caravan camp at the train station.}
{141}{}{Why do you call yourself "military"?}
{142}{}{How did this community arose, and who are all these people?}
{143}{}{What the locals are doing?}

{148}{}{Tell me about yourself.}
{149}{}{I guess that's all I wanted to know.}

{150}{}{The ancestors, those who founded the Wind of War, were calling themselves such. They were the military, they served the United States. At least, so we were told. Now it is difficult to say. General Wesker believes in the revival of the country, so he's trying to keep the spirit of the nation. And sometimes it even looks stupid.}
{151}{}{The bulk of the population are direct descendants of the people from the local vault. Ancestors survived the Great War underground, and when it became impossible to live there, they left the vault and established a settlement on the ruins of the old town of Pahrump. Then, gradually, wanderers of the Wasteland started to join the ranks of the settlers, but there were few of lucky ones. Looking at people from the outside world, the General became horrified and... Enclosed the area with a fence. Now random people are not allowed here.}
{152}{}{In fact, there are three types of people. First, the military. They protect us, explore the area around, and engage in major hunts. Second, those, who sit in the office and do the brainwork. And finally, the commoners, such as I, whose destiny is to cook porridge, iron clothes and maintain the housing.}
{153}{}{Vault? Where is it?}
{154}{}{I don't even know. It's somewhere in the North-West mountains. Better ask the radio operators at the headquarters - they know everything about the outskirts of the settlement.}

{160}{}{I'm here for three or four years. I was accepted because I did good work for the benefit of the Wind of War - helped them with contacting the outside world. But if not for Jessica, I would have go back to the Wasteland.}
{161}{}{Who's Jessica?}
{162}{}{Sounds like you're dissatisfied with life in the Wind of War.}
{163}{}{What's stopping you to leave the settlement?}
{164}{}{Then tell me some more about the settlement.}

{170}{}{Oh, this is my first and only love! Before I always thought only about myself until I met her. She lives in the house nearby.}
{171}{}{Hmm. Can I trust you? Because I'm a wanderer like you... You know, it's not so bad here, if you find common ground with the "purebred" population. And I used to live in a different environment... But who am I kidding? Me, as a "half-breed" here have no respect, I'm not even allowed to have a family. But I'd be a good husband, damn it!}
{172}{}{Eh... Actually I can leave at any time. But they won't let Jessica do the same. Moreover, they even forbid me to talk to her! After I've proposed to her, her brothers called me a half-breed and kicked out of the house. And without her I see no reason to leave.}

{173}{}{Whoa! What's the problem, Romeo? Run out of the settlement together!}
{174}{}{Are you serious? Damn, I thought about it so many times. Do you really think that it would be wise?}
{175}{}{Hell, Yes! Ignore the brothers, do what you both want! Who are they to decide for you?}
{176}{}{You know, that's not so smart. The Wasteland is dangerous, here at least you are protected.}

#Get the quest
{177}{}{[Sighs] That's right. Well, thanks for the visit.}
{178}{}{Yeah, don't worry! I'm kidding. In fact, you must escape!}
{179}{}{Yeah, bye.}
{180}{}{Yes! Yes!! Thank you, friend! For the support and all. The only thing left is to put out a plan. I have been thinking about running away together for a very long time, but it's hard to do.}
{181}{}{I'll help. What do you need?}
{182}{}{Well, you should figure it out yourself. I have other things to do.}

{183}{}{It will not be easy. The brothers keep Jessica locked up and will not release her without supervision. We can run away only at night, when they sleep. But there's the problem - only the brothers have the keys to the door.}
{184}{}{So, you need to get the keys to the door?}
{185}{}{But keep in mind, they shouldn't suspect anything. If both brothers lose the keys, it will raise suspicions, but if they lose only one of them, they will explain the loss by their own confusion, or so I think.}
{186}{}{All right. I'll see what I can do.}

{190}{}{There you are, friend. Well, how's it going?}
{191}{}{I have the key!}
{192}{}{All easier. No brothers - no problems with the door.}
{193}{}{There is nothing to make you happy with, at least yet. Wait for the news.}

{194}{}{Wait a minute, you snatched both keys? Oh no! What are you doing?! Bring back one of the keys until they come to their senses! Now!}
{195}{}{Okay, okay...}
{196}{}{Great! Good job, now the most important thing is to find a suitable time to mount the barricades.}
{197}{}{The barricades?}
{198}{}{Well, of course. They won't allow us to pass through the gates, thus we have to climb over the piles of junk on the perimeter.}
{199}{}{You will need a rope.}

{200}{}{Exactly! I know that the technician had one, if he hasn't sold it already. Please get us a rope!}
{201}{}{Okay, but I need something in exchange for it.}
{202}{}{Okay, you'll get the rope.}
{203}{}{Hell, I've risked my life enough already, now it's up to you to get out of here, and I'm leaving.}

{204}{}{Yes, I... Understand. Thank you anyway. Although without your help we cannot escape, but - thanks.}
{205}{}{Yeah. Goodbye.}

{206}{}{Oh, sure, I'm sorry. But I don't have a shop here. I have little to offer except these flasks. They would've been useful in the Wasteland, but we need the rope more.}
{207}{}{Are you insane?! Why the technician would need damn flasks? Give money! And more!}
{208}{}{Great, It suits me.}
{209}{}{I changed my mind. You need these things more, so I'll look for something out of my pocket.}

{210}{}{Uh... Money is more important to us. Well, here's 100 bucks. It's just enough for the rope, and for the efforts.}
{211}{}{Well, that's another matter. Now wait for me.}
{212}{}{[Gives 3 empty soldier flasks] I hope it's enough.}
{213}{}{Hope and wait for me.}
{214}{}{Thanks, friend!}
{215}{}{It's nothing. Wait, when I get the rope.}
{216}{}{About the purchase of the rope - I need something to exchange for it.}

#Rope
{220}{}{Hello. I'm sorry it's a mess...}
{221}{}{I got you the rope.}
{222}{}{Nevermind, I'm leaving.}

{223}{}{Really? Oh, that's great. Give it to me...}
{224}{}{Not so fast! Tell me, why should I help you? Why can't I just give away you?}
{225}{}{Here you go. I hope this will help you.}
{226}{}{Sorry, I left it in another place.}

{227}{}{I understand. Well, I know how to "thank" you for trying. But only after you help us. If you want to be exact - I'll tell you about a cache of very useful things. In any case, you won't come off a loser.}
{228}{}{That's fine with me. Well, then hold the rope.}
{229}{}{Sorry, but no. I'll be back if I change my mind.}

{230}{}{Hmm, I think that's enough. Well, there is only one thing left. We should escape at night, otherwise we can easily be detected and caught. But the barricades to the North of the Jessica's house are lit by the street lamp. I'm afraid, someone will have to stay and turn off electricity, while we go to the other side.}
{231}{}{Ha, don't pretend that you've just realized this, I see when the emotions are staged. Well, I got the hint. I will be the switch that turns the electricity off. Who else but me!}
{232}{}{Look for another fool, I did my job and am out of here.}

{233}{}{Well, then it's time to begin the active phase! All you need to do is wait until night and turn off the lighting on the street.}
{234}{}{Sure. Let's get started!}
{235}{}{Probably, but I'm not ready yet. You will have to wait.}

{236}{}{You haven't changed your mind yet?}
{237}{}{I will be the switch that turns the electricity off. Who else but me!}
{238}{}{Unfortunately for you - I'll pass.}

{239}{}{}

#Brothers are dead
{240}{}{What?! Damn! How did you manage to do this? However, it is not necessary to explain, I don't want to know. The main thing now is to seize the moment to climb the barricades.}

#Women's replics
{1110}{}{Thank you, wanderer. Thank you for everything!}
{1177}{}{[Sigh] That's right. Well, thanks for the visit.}
{1180}{}{Yes! Yes!! Thank you, friend! For the support and all. It's only left to figure out a plan. I have been thinking about running away together for a very long time, but it's hard to do.}
{1190}{}{There you are, friend. Well, how's it going?}
{1194}{}{Wait a minute, you snatched both keys? Oh no! What are you doing?! Bring back one of the keys until they come to their senses! Now!}
{1203}{}{Hell, I've risked my life enough already, now it's up to you to get out of here, and I'm leaving.}
{1209}{}{I changed my mind. You need these things more, so I'll look for something out of my pocket.}
{1214}{}{Thanks, friend!}
{1221}{}{I got you a rope.}
{1226}{}{Sorry, I left it in another place.}
{1231}{}{Ha, don't pretend that you've just realized this, I see when the emotions are staged. Well, I got the hint. I will be the switch that turns the electricity off. Who else but me!}
{1232}{}{Look for another fool, I did my job and am out of here.}
{1235}{}{Probably, but I'm not ready yet. You will have to wait.}
{1236}{}{You haven't changed your mind yet?}
