{100}{}{You see Robert.}
{101}{}{You see a resident of the Wind of War.}
{102}{}{::grabs his head:: My life is meaningless...}
{103}{}{Please don't let us down, it's our only chance.}

#Acquaintance
{110}{}{Thank you, wanderer. Thank you for everything!}
{111}{}{You are welcome.}

{120}{}{Oh, I'm surprised to see a kindred soul in this closed area.}
{121}{}{What are you talking about?}
{122}{}{You don't meet many people from outside the perimeter here. I'm one of the few people who... Uh, got a lucky chance to live here.}
{123}{}{I see. Can I ask you about Wind of War?}
{124}{}{Well, then nice to meet you. Maybe I'll stop by sometime to visit.}

{125}{}{Of course! Really looking forward to - there's always something to talk about with strangers.}
{126}{}{Uh, okay.}

{130}{}{Shall we sit down and talk?}
{131}{}{I'd like to know more about this place. Care to share?}
{132}{}{Tell me about yourself. I see you're not from around here, right?}
{133}{}{}
{134}{}{Thanks for the hospitality, but I gotta go.}

{140}{}{Now we are in a closed settlement. Only the military and their families live here. Outside you will find nothing but ruins. And then there's the caravan camp at the railroad station.}
{141}{}{Why do you call yourself "military"?}
{142}{}{How did this community came to be and who are all these people?}
{143}{}{What are the locals doing?}

{148}{}{Tell me about yourself.}
{149}{}{I guess that's all I wanted to know.}

{150}{}{Our ancestors, those who founded the Winds of War, called themselves that. They were military, they served the United States. At least that's what we were told. We don't know for sure. General Wesker believes in the rebirth of the country, so he tries to keep the spirit of the nation alive. And sometimes it ends up looking silly.}
{151}{}{The bulk of the population are direct descendants of people from the local vault. Our ancestors survived the Great War underground, and when it became impossible to live there, they went outside and established a settlement on the ruins of the old city of Pahrump. Then, gradually, wasteland wanderers  began to visit, but not many of them were allowed to join. Seeing the people from the outside world, the general was horrified... and fenced off the area. Now random people are not allowed here.}
{152}{}{In fact, there are three types of people. First, the military. They protect us, explore the area around and engage in major hunts. Second, those, who sit in the office and do the brainwork. And finally, the commoners, such as myself, whose destiny is to cook porridge, iron clothing and maintain the housing.}
{153}{}{Vault? Where is it?}
{154}{}{I don't even know. It's somewhere in the mountains in the northwest. Better ask the radio operators at the headquarters - they know everything about the outskirts of the settlement.}

{160}{}{I've been here for three or four years. I was accepted because I did a good job for Wind of War - helped them with some dealings with the outside world. But if it hadn't been for Jessica, I would have gone back to the wasteland.}
{161}{}{Who's Jessica?}
{162}{}{Sounds like you're not very satisfied with your life in the Wind of War.}
{163}{}{What's stopping you from leaving the settlement?}
{164}{}{Then tell me more about the place.}

{170}{}{Oh, she is my first and only love! I used to think only about myself...until I met her. She lives in the house nearby.}
{171}{}{Hmm. Can I trust you? Because I'm a wanderer like you... You know, it's not so bad here, if you find common ground with the "purebred" population. I used to live in a different environment... But who am I kidding? Me, as a "half-breed" here can't get no respect, I'm not even allowed to have a family. But I'd be a good husband, damn it!}
{172}{}{Eh... Actually I can leave at any time. But they won't let Jessica do the same. They even forbid me from talking to her! After I proposed to her, her brothers called me a half-breed and kicked me out of the house. Without her I see no reason to leave.}

{173}{}{Whoa! What's the problem, Romeo? Run out of the settlement together!}
{174}{}{Are you serious? Damn, I thought about that so many times. Do you really think that that would work?}
{175}{}{Hell yes! Ignore her brothers, do what you both want! Who are they to decide for you?}
{176}{}{You know, that's not so smart. The wasteland is dangerous, at least here you are protected.}

#Get the quest
{177}{}{[Sighs] That's right. Well, thanks for the visit.}
{178}{}{Yeah, don't worry! I'm kidding. In fact, I think you must escape!}
{179}{}{Yeah, bye.}
{180}{}{Yes! Yes!! Thank you, friend! For helping us escape. All that's left is to come up with a plan. I have been thinking about us running away together for a very long time, but it's easier said than done.}
{181}{}{I'll help. What do you need?}
{182}{}{Well, figure it out yourself. I have other things to do.}

{183}{}{So the brothers keep Jessica locked up and don't let her out unsupervised. The only way to escape is at night, when they are asleep. But there is a problem - only the brothers have the keys to the door.}
{184}{}{So, you need to get the keys to the door?}
{185}{}{But keep in mind, they shouldn't suspect anything. If both brothers lose their keys, it will make them suspicious, but if they lose only one of them, they should blame the loss to their own carelessness...I think.}
{186}{}{All right. I'll see what I can do.}

{190}{}{There you are, friend. How's it going?}
{191}{}{I have the key!}
{192}{}{All became much easier. No brothers - no problems with the door.}
{193}{}{There is nothing to make you happy with, or at least, yet. Wait for the news.}

{194}{}{Wait a minute, you snatched both keys? Oh no! What have you done?! Bring one of the keys back until they notice! Hurry!}
{195}{}{Okay, okay...}
{196}{}{Great! Good job, now the most important thing is to find the right time to set up the barricades.}
{197}{}{The barricades?}
{198}{}{Well, of course! They won't let us through the gate, so we have to climb over the piles of junk on the perimeter.}
{199}{}{You will need a rope.}

{200}{}{Exactly! I know that the technician had one, if he hasn't sold it already. Please, get us a rope!}
{201}{}{Okay, but I need something in exchange for it.}
{202}{}{Okay, you'll get the rope.}
{203}{}{Hell, I've risked my life enough already, now it's up to you to get out of here. I'm leaving.}

{204}{}{Yes, I... Understand. Thank you anyway. Although without your help we cannot escape, but still - thanks.}
{205}{}{Yeah. Goodbye.}

{206}{}{Oh, sure, I'm sorry. But I don't have a shop here. I have little to offer except these flasks. We could really use them in the wasteland, but we need the rope more.}
{207}{}{Are you insane?! Why the technician would need damn flasks? Give me money! The more the better!}
{208}{}{Great, It suits me.}
{209}{}{I changed my mind. You need these things, so I'll look for something out of my pocket.}

{210}{}{Uh... Money is more important to us. Okay, here's 100 bucks. It's just enough for the rope and for your efforts.}
{211}{}{Now we're talking. Wait for me.}
{212}{}{[Gives you 3 empty army flasks] I hope it's enough.}
{213}{}{Hope and wait for me.}
{214}{}{Thanks, friend!}
{215}{}{It's nothing. Wait, when I get the rope.}
{216}{}{About the purchase of the rope - I need something to exchange for it.}

#Rope
{220}{}{Hello. I'm sorry it's a mess...}
{221}{}{I got you the rope.}
{222}{}{Nevermind, I'm leaving.}

{223}{}{Really? Oh, that's great. Give it to me...}
{224}{}{Not so fast! Tell me, why should I help you? Why don't I just turn you in?}
{225}{}{Here you go. I hope this will help you.}
{226}{}{Sorry, I left it in another place.}

{227}{}{I understand. I know how to thank you. But only after you help us. I can tell you about a stash of very useful things. In any case, you will not be left on the losing end.}
{228}{}{That's fine with me. Well, then hold the rope.}
{229}{}{Sorry, but no. I'll be back if I change my mind.}

{230}{}{That's enough. Now there is only one thing left to do. We must make our run at night, or we'll be easily spotted and caught. But the barricades north of Jessica's house are lit by a street lamp. I'm afraid someone will have to stay and cut the power while we get to the other side.}
{231}{}{Ha, don't pretend that you just thought of this, I can see your ham-fisted acting. Alright, I got the hint. I'll be your electrical switch flipper. Who else but me!}
{232}{}{Look for another fool, I did my job. I'm outta here.}

{233}{}{Well, then it's time to get to it! All you need to do is wait until night and turn off the lighting on the street.}
{234}{}{Sure. Let's get started!}
{235}{}{Probably, but I'm not ready yet. You will have to wait.}

{236}{}{You haven't changed your mind yet?}
{237}{}{I'll be your electrical switch flipper. Who else but me!}
{238}{}{Unfortunately for you - I'll pass.}

{239}{}{}

#Brothers are dead
{240}{}{What?! Damn! How did you manage to pull this off? No need explain, I don't want to know. What matters now is to seize the right moment to climb the barricades.}

#Women's replies
{1110}{}{Thank you, wanderer. Thank you for everything!}
{1177}{}{[Sighs] That's right. Well, thanks for the visit.}
{1180}{}{Yes! Yes!! Thank you, friend! For the support and all. All that's left is to come up with a plan. I have been thinking about us running away together for a very long time, but it's not an easy thing to do.}
{1190}{}{There you are, friend. How's it going?}
{1194}{}{Wait a minute, you snatched both keys? Oh no! What have you done?! Bring one of the keys back until they notice! Hurry!}
{1203}{}{Hell, I've risked my life enough already, now it's up to you to get out of here. I'm leaving.}
{1209}{}{I changed my mind. You need these things, so I'll look for something out of my pocket.}
{1214}{}{Thanks, friend!}
{1221}{}{I got you a rope.}
{1226}{}{Sorry, I left it in another place.}
{1231}{}{Ha, don't pretend that you've just realized this, I see when the emotions are staged. Well, I got the hint. I will be the switch that turns the electricity off. Who else but me!}
{1232}{}{Look for another fool, I did my job. I'm outta here.}
{1235}{}{Probably, but I'm not ready yet. You will have to wait.}
{1236}{}{You haven't changed your mind yet?}
