{100}{}{You see a medic.}
{101}{}{You see a very cunning old man. Better not to fool around with him!}

#Start of the dialogue
{110}{}{Yes?}
{111}{}{I don't need anything}
{112}{}{Do you sell drugs?}
{113}{}{Do you make drugs?}

#Selling Niskigwan's backpack
{120}{}{I found an excellent kit for healers, it's a set of tools and such. Want to see?}
{121}{}{Kit for healers, you say? Funny. And what's in it? Some petals-flowers? He-he...}
{122}{}{No. There are all sorts of things to produce simple medicine in the field. You'd better look at it yourself!}
{123}{}{Hmm... Interesting. Apparently, the owner was not a bad healer. Well. I'll buy the kit for 1000, no more.}
{124}{}{Okay, I agree.}
{125}{}{No, I will find more serious customers.}
{126}{}{Oh, well, as you wish.}
{127}{}{[More]}
{128}{}{Very well, I could use that.}
{129}{}{You did it on purpose, right? Now pick it up. Come on, come on!}
{130}{}{Uh, sorry! Won't happen again!}
{131}{}{How's it going with the water? I've been to Salt Lake, and there...}

#Consultation on the Salt Lake's problem
{132}{}{With water things aren't that good everywhere. But we are not a very large settlement, and aren't wronged by nature. We get away with it.}
{133}{}{How do you get clean water?}
{134}{}{Digging a deeper well and taking water from it in a smart way. It needs to be stilled, boiled, then exposed to the sun. And a pinch of disinfectant will get the job done.}
{135}{}{A water disinfectant? Where do you get it?}
{136}{}{We still had a good supply from the place we came from, but now it is almost used up.}
{137}{}{So, you won't sell me this chemical?}
{138}{}{No. Water is more valuable than your money, even if you'd offer a lot.}
{139}{}{How are you going to handle the water purification then?}
{140}{}{Buying all the disinfection available, building cisterns, and setting up the means of water purification. I think one can find generators and filters somewhere, in the cities like Vegas especially...}
{141}{}{What else? You seem to be thinking about something.}
{142}{}{Oh, nothing. It would just be terribly convenient to pump water from the ground, it's clean there. It would require a lot of special equipment to be found. And, apparently, a lot of such equipment already exist in Salt Lake.}
{143}{}{Why do you think so?}
{144}{}{Because we already had a few caravans coming here and asking if we have a filter for underground water treatment.}
{145}{}{And? Do you have one?}
{146}{}{Of course, not! Where would we take it?! And even if we had one, we would already have adapted it to use. Well, you know.}
{147}{}{Ah, yes. Sad case.}

#Medical care of the char
{180}{}{I need healing.}
{181}{}{It's nothing serious, will heal fast. Let's see...}
{182}{}{Come on, doc! I'm dying!}
{183}{}{Now, now, don't get so excited!}
{184}{}{DOCTOR!!!}
{185}{}{Ah, now everything is clear. It's }
{186}{}{ bucks and you will be be like new.}
{187}{}{What?! I can die, but you think about money?!}
{188}{}{Do as you wish, but I'm not working for free.}
{189}{}{Here is the money. Treat me.}
{190}{}{I can do without your stupid medicine. Good luck.}
{191}{}{Look at you! And there's no reason to scream anymore.}
{192}{}{Well, at least thanks for not allowing me to die!}

{195}{}{But wait! Your body is so healthy you could be sent to the Wasteland right away.}
{196}{}{Glad to hear it.}

#The production of medicine:
{200}{}{If you bring in the necessary components. I can make stimpaks, superstimpaks, antidotes and healing powder.}
{201}{}{I don't need it then. Another question.}
{202}{}{Could you teach me this?}
{203}{}{So you can become my competitor? No, earning money is already hard enough.}
{204}{}{No, for the other reason - so I wouldn't go to Wesker and say him that you have a drug lab. Proving this would be easy.}
{205}{}{Too bad.}
{206}{}{Wha... Oh, you scoundrel! So that's how you pay for the good!}
{207}{}{Old man, don't yell, they'll hear and it'll be bad for you. I won't say it twice. You have the last word.}
{208}{}{Uh...}
{209}{}{Old man, I'm waiting. Come on! Make up your mind already!}

{210}{}{Oh, that's how you speak now! Wesker wouldn't know so GET OUT OF HERE!}
{211}{}{Consider, you've been subscribed. Wait for the news.}

{212}{}{Uh... Well. I'll tell you all, in the end, it's not such a big secret.}
{213}{}{You should have said so from the beginning. Start talking.}

{214}{}{[You spend some time doing unsuccessful experiments, but in the end you've managed to learn this craft, so you are now able to make antidotes and healing powders through the first aid kit]}
{215}{}{Good day.}

#The production of medicine:
{216}{}{Make a stimpak.}
{217}{}{Make a superstimpak.}
{218}{}{Make an antidote.}
{219}{}{Make healing powder.}

{220}{}{I'll do it if you bring me the tail of a radscorpion. }
{221}{}{I'll do it if you bring me an empty syringe, a Xander root and a Broc flower. }
{222}{}{I'll do it if you bring me a Xander root and a Broc flower. }
{223}{}{I'll do it if you bring a normal stimpak, Nuka-Cola and a mutafruit. }
{224}{}{ bucks a dose.}
{225}{}{...Although, why do you need such a primitive drug? You should have bought a stimpak...}

{226}{}{One.}
{227}{}{Two.}
{228}{}{Three.}
{229}{}{Five.}
{230}{}{Ten.}
{231}{}{Nothing.}
{232}{}{Oops. I have no money.}

{233}{}{Well, what do you offer me in return?}
{234}{}{Oops. I have no money.}

#Medical aid to the beaten up caravaneer
{250}{}{Urgent! One of the caravaneers needs medical help!}

{251}{}{Uh... [shakes his head] Another one was painted, right? It often happens here.}
{252}{}{Here's $ 100. Help him!}
{253}{}{}
{254}{}{I'll paint you worse, if you don't help him. Hurry up, old fart!}
{255}{}{Well, you shouldn't be so heartless!}

{256}{}{Thinking about it - why not...}
{257}{}{That's right. Come on! Come on!}

#Women's replics
{1120}{}{I found an excellent kit for healers, it's a set of tools and such. Want to see?}
{1124}{}{Okay, I agree.}
{1131}{}{How's it going with the water? I've been to Salt Lake, and there...}
{1180}{}{Help! I'm hurt!}
{1186}{}{ bucks and you will be like new.}
{1204}{}{No, for the other reason - so I wouldn't go on to Wesker and say him that you have a drug lab. Proving this would be easy.}
{1206}{}{Wha... Oh, you scoundrel! So that's how you pay for the good!}
{1210}{}{Oh, that's how you speak now! Wesker wouldn't know so GET OUT OF HERE!}
