{100}{}{You see a sentry.}
{101}{}{So, who is here? As you can guess, this is a sentry!}

#If you received the permission to go into the settlement
{102}{}{Come in, come in, don't worry.}
{103}{}{First I'll chop your hands off, then legs, and after that you can start asking questions!}

#Dialogue, when the character has a weapon in hands
{110}{}{Wait! Holster your weapon! Discharge the rifle and put it to the belt! Now!}
{111}{}{Why is this necessary? You afraid that I'll start the fourth world war?}
{112}{}{Okay, I'll put it away.}
{113}{}{Last warning! Put the gun down! Fast!}
{114}{}{Still, why do you need it? It's an unsafe place?..}
{115}{}{All right, see? I putting it away.}

#Attempts to go to the territory of the settlement
{116}{}{This is the territory of a military garrison. Outsiders without permission are forbidden here.}
{117}{}{I've got business there.}
{118}{}{How can I get permission?}
{119}{}{You mean I can't get through? Well, I'm leaving.}
{120}{}{You CAN'T, you idiot! You have nothing to do there. Turn around if you don't want a bullet in the forehead.}
{121}{}{Now listen to me, you filth, if you're still...}
{122}{}{Permission, huh? [darkly grins and squints at the neighbors] Well, we can discuss your problem, if you're interested...}
{123}{}{Of course, you *can* [wink and take $100 out of the pocket].}
{124}{}{Hmm... I think this is a hint to something?}
{125}{}{[His face becomes very unhappy] Go here! Come on!}
{126}{}{Oh... That's how you speak?}
{127}{}{Okay. Finally.}
{128}{}{Bye.}
{129}{}{How? Well... It's a serious place. The passage is worth 300 bucks.}
{130}{}{300? Why one has to pay for the passage to a residential area? Who decides it, dammit?!}
{131}{}{All right, here is the money.}
{132}{}{Be careful out there... The locals do not favor outsiders.}
{133}{}{Bye!}

#Dialogue after the phrase "I've got business there"
{134}{}{Yeah? What kind of?}
{135}{}{I need to go to the bathroom... Although, I'd rather do it elsewhere. Bye.}
{136}{}{I deal with Nuka-Cola supplies, I think, the Wind of War will not refuse to trade.}
{137}{}{I traveled to Hawthorne and found interesting information about your settlement.}
{138}{}{I have a box of large-caliber ammunition for machine guns. Maybe we could make a deal.}
{139}{}{I'm looking for the instigators of the raid on the caravan from Vegas.}
{140}{}{I need to see General Wesker for a personal matter.}
{141}{}{Wesker?.. Well. You can pass. But we need to check your belongings on the presence of dangerous objects.}
{142}{}{Finally.}
{143}{}{Wesker? And why should I buy into this nonsense?}
{144}{}{I don't know...}
{145}{}{[Sarcastic] What a surprise. Now turn around and go back to the Wasteland. Here is a military garrison, we don't have any raiders here. Do you understand? Great. And if you insist - one less impudent person would wander the earth.}
{146}{}{Grr...}
{147}{}{Oh... Well, then I'll allow you to pass. But we need to check your belongings on the presence of dangerous objects.}
{148}{}{Okay, thanks.}
{149}{}{It's forbidden to bring drugs and alcohol in here. Keep the weapon in the holster. If we see you armed... Blame yourself. All is clear? About Wesker: up the street until it ends, then enter the building on the right.}
{150}{}{Then check.}
{151}{}{No way!}
{152}{}{}
{153}{}{Okay. I'll lay out these things and come back.}
{154}{}{This ain't a store, you dimwit, but a military base! Shop's there! [waving at the building behind you]}
{155}{}{I know, but the shopkeeper refuses to bargain without the permission of Wesker.}
{156}{}{Right, I will go to him.}
{157}{}{Because he personally gave me a job in Hawthorne. Don't believe me? Then contact him by the radio!}
{158}{}{Because I found the important documents in Hawthorne that will be of interest to General.}
{159}{}{}
{160}{}{No, it is forbidden to bring drugs and alcohol in here. You'll have to leave. [Shows on the subject: }
{161}{}{]}
{162}{}{Okay, I'll be back.}

{163}{}{This case is confidential and isn't of your concern.}
{164}{}{Hold your tongue. If you really have business here, then why I have no orders on your account?}
{165}{}{Because your office is a mess. So stop wasting time, your General is waiting for me.}
{166}{}{I don't know. So you don't let me in? Okay, but I'll be back...}

#After obtaining permission to enter
{170}{}{Come in, come in, don't just stay in there.}
{171}{}{Wait, let me piss on your leg first. That's how we act friendly in the Wasteland.}
{172}{}{Okay.}

{173}{}{Eh?! What a savagery! Move away from me!}
{174}{}{Ha, a big muscular guy with a big gun afraid to dirty himself a bit in the urine!}
{175}{}{I will not insist, as you wish.}

{176}{}{So, running into troubles? You want to get into our jail for a couple of days? Well, we'll organize it fast!}
{177}{}{For such a loser like you to threaten me with jail? [spit under the feet] You have run up on the wrong person!}
{178}{}{Okay, sure, I'll just go quietly and peacefully.}

{179}{}{[Speaking through clenched teeth] That's it, scum, hold on, I've had enough of these jokes! [aims a gun at you]}
{180}{}{Okay, really, enough with the jokes.}
{181}{}{Shut up! Hands behind your head! Now! Now you'll go and sit in jail a full day!}
{182}{}{Whatever, I won't resist...}
{183}{}{In jail?! Me?! Fuck you!}

{184}{}{Oh, will I get a lunch there? It would be nice.}
{185}{}{It's rubber tire with sauce of sulfur and concrete crumbs for lunch in our jail. Want to try out? Always at your service!}

#Rednecks
{190}{}{The General was talking about some incident with a couple of rednecks on this post. Tell me more.}
{191}{}{[Shrugs indifferently] Some old man from the Wasteland was trying to break the fence. Got punched in the cheek and a kicked in the ass, then was sent back. Perhaps, now he's at the train station, licking his bruises. There was the girl with him. And what a fool she is.}
{192}{}{Yeah.}

#Women's replics
{1137}{}{I traveled to Hawthorne and found interesting information about your settlement.}
{1145}{}{[Sarcastic] What a surprise. Now turn around and go back to the Wasteland. Here is a military garrison, we don't have any raiders here. Do you understand? Great. And if you insist - one less impudent person would wander the earth.}
{1158}{}{Because I found the important documents in Hawthorne that will be of interest to General.}
