{100}{}{You see a sentry.}
{101}{}{As you can guess, this is a sentry.}

#If you received the permission to go into the settlement
{102}{}{Come in, come in, don't worry.}
{103}{}{First I'll chop your hands off, then legs, and after that you can start asking questions!}

#Dialogue, when the character has a weapon in hands
{110}{}{Wait! Holster your weapon! Unload the gun and put it down! Now!}
{111}{}{Why is this necessary? Are you afraid that I'll start the fourth world war?}
{112}{}{Okay, I'll put it away.}
{113}{}{Last warning! Put the gun down! Fast!}
{114}{}{Still, why do you need it? Is it so unsafe here?}
{115}{}{All right, see? I'm putting it away.}

#Attempts to go to the territory of the settlement
{116}{}{This is the territory of a military garrison. Outsiders without permission are not allowed here.}
{117}{}{I've got business there.}
{118}{}{How can I get permission?}
{119}{}{You mean I can't get in? Okay, I'm leaving.}
{120}{}{You CAN'T, you dumbass! You have nothing to do there. Turn around and go, if you don't want a bullet in the forehead.}
{121}{}{Now listen to me, you filth, if you'll talk to me like this one more time...}
{122}{}{Permission, huh? [He grins and squints, looking at the other soldiers] Well, we can discuss your problem, if you're interested...}
{123}{}{Of course. [Wink and take $100 out of your pocket].}
{124}{}{Hmm... Is this a hint to something?}
{125}{}{[His face becomes unhappy] Turn around and walk away! Chop-chop!}
{126}{}{What the hell was that?...}
{127}{}{Okay. Finally.}
{128}{}{Bye.}
{129}{}{How? Well... It's a serious place. The passage costs 300 bucks.}
{130}{}{300? Why should I pay for the passage to a residential area?!}
{131}{}{All right, here is the money.}
{132}{}{Be careful out there... The locals do not favor the outsiders.}
{133}{}{Bye!}

#Dialogue after the phrase "I've got business there"
{134}{}{Yeah? What kind?}
{135}{}{I'm looking for a toilet... Although, I'd rather do it elsewhere. Bye.}
{136}{}{I deal with Nuka-Cola. I think the Wind of War won't pass on a good deal.}
{137}{}{I traveled to Hawthorne and found interesting information about your settlement.}
{138}{}{I have a box of large-caliber ammunition for machine guns. Maybe we could make a deal.}
{139}{}{I'm looking for the instigators of the Vegas caravan raid.}
{140}{}{I need to see General Wesker about a personal matter.}
{141}{}{Wesker? Well... Okay, you can pass. But we need to check your belongings on the presence of dangerous objects.}
{142}{}{Finally.}
{143}{}{Wesker? And why should I buy this nonsense?}
{144}{}{I don't know...}
{145}{}{What a surprise! Now turn around and go back into the Wasteland. This is a military garrison, we don't have any raiders here. Do you understand? Great. And if you'll insist, there's going to be one less impudent person.}
{146}{}{Grr...}
{147}{}{Oh... Well, then I'll let you through. But we have to check your belongings for dangerous objects.}
{148}{}{Okay, thanks.}
{149}{}{It's forbidden to bring drugs and alcohol in here. Keep the weapon in the holster. If we catch you armed... Blame yourself. Clear? About Wesker: Up the street until it ends, then enter the building on the right.}
{150}{}{Then check.}
{151}{}{No way!}
{152}{}{}
{153}{}{Okay. I'll take care of these things and come back.}
{154}{}{This ain't a store, you dimwit, this is a military base! Shop's there! [He points at the building behind you]}
{155}{}{I know, but the shopkeeper refuses to bargain without the permission of Wesker.}
{156}{}{Right, I will go to him.}
{157}{}{Because he personally gave me a job in Hawthorne. Don't believe me? Then contact him by the radio!}
{158}{}{Because I found some important documents in Hawthorne that will be of interest to General.}
{159}{}{}
{160}{}{No, it is forbidden to bring drugs and alcohol in here. You have to ditch this. [He points to: }
{161}{}{]}
{162}{}{Okay, I'll be back.}

{163}{}{This case is confidential and isn't of your concern.}
{164}{}{Hold your tongue. If you really have business here, then why don't I have orders on your behalf?}
{165}{}{Because your office is a mess. So stop wasting time, your General is waiting for me.}
{166}{}{I don't know. Okay, I'll be back later...}

#After obtaining permission to enter
{170}{}{Come in, come in, don't just stay in there.}
{171}{}{Wait, let me piss on your leg first. It's the local custom in the wasteland.}
{172}{}{Okay.}

{173}{}{Eh?! Ew! Get away from me!}
{174}{}{Ha, a tough guy with a big gun is afraid of some urine!}
{175}{}{I'm not going to insist.}

{176}{}{So, that's how it is? I guess, you are looking for trouble! Want to spend a couple of days in our jail? We'll make it happen very fast!}
{177}{}{A loser like you threatens me with jail? [Spit on his feet]You've picked the wrong guy to mess with!}
{178}{}{Okay, sure, I'll just go. Quietly and peacefully.}

{179}{}{[He speaks through his clenched teeth] That's it, you scum, I've had enough of your jokes. [He points his gun at you]}
{180}{}{Okay, I agree. Enough with the jokes.}
{181}{}{Shut up! Put your hands on your head! Move it! Now you're gonna spend the day in jail!}
{182}{}{Whatever you say, I won't even resist...}
{183}{}{In jail?! Me?! Fuck you!}

{184}{}{Oh, am I going to get a lunch there? Would be nice.}
{185}{}{Yeah, your lunch is going to be a rubber tire with the sauce of sulfur and concrete crumbs. Feel free to try it!}

#Rednecks
{190}{}{The General was talking about some incident with a couple of rednecks on this post. Tell me more.}
{191}{}{[Shrugs indifferently] Some old man from the wasteland was trying to break through. Got punched in the face and kicked in the ass, then left. He is probably at the station right now, licking his wounds. There was the girl with him. She looked stupid.}
{192}{}{Yeah.}

#Women's replies
{1137}{}{I traveled to Hawthorne and found interesting information about your settlement.}
{1145}{}{What a surprise! Now turn around and go back into the Wasteland. This is a military garrison, we don't have any raiders here. Do you understand? Great. And if you'll insist, there's going to be one less impudent person.}
{1158}{}{Because I found some important documents in Hawthorne that will be of interest to General.}
