{100}{}{You see an inmate.}
{101}{}{It's a criminal put behind the bars by the military.}

{102}{}{You saved the prisoner from death penalty.}
{103}{}{Dayum! That was neat! We did it! Ha-ha! I'm free! Thanks for your help, I owe you one. I'll be all right now. By the way, if you're ever in Vegas, come find me. [winks]}
{104}{}{In Vegas? Okay.}
{105}{}{Shush! Not now!}
{106}{}{Don't sweat it. I'll be nearby.}

{110}{}{A new face, huh? Sweet!}
{111}{}{What are you in for?}
{112}{}{Nothing really.}
{113}{}{Really?}
{114}{}{Yes! Goddamit, of course! What do you think? Here in Wind of War, the military is worse than raiders. They want everything for themselves, they take your money and weapons, and then they just lock you up, those bastards! Ughhh! [shouts at the door] You will fucking pay for this, you scumbags!!!}
{115}{}{So you're saying that they just stopped you and robbed you at gunpoint? Is that how it was?}
{116}{}{No... Well, yes, but... I mean... Look, I'm here because I resisted. Now they're preparing an execution. They want to make a show out of it. Motherfuckers! I hate those pigs!}
{117}{}{Hmm, I'm not sure if I believe you.}
{118}{}{Whatever! Use your fucking head! They just took your stuff and put you in here. To them, you're just dirt under their feet. Think about it, you still have time. While I'm being executed in a few days...}
{119}{}{Hmm...}

{120}{}{So, what do you think?}
{121}{}{I don't know, really. Have to gather my thoughts.}
{122}{}{You know, I'm in no position to ask anything, but here's what I'd do. [whispers] When they're about to let you out, stand in the convenient spot and ask a stupid question, so that I could grab this fucker's throat when he comes in, alright? Then all that's left is to get around the corner, to the fence, unnoticed...}
{123}{}{I'll think about it...}
{124}{}{Yeah, you think about it, while we still have time. I'll be by the door, if you decide something.}
{125}{}{Yeah... That's a tough situation to be in.}

{126}{}{By the way, I'm getting executed tomorrow, in case you were interested.}
{127}{}{The way is clear. Let's get out of here.}
{128}{}{You'll have to wait.}