{100}{}{You see a tired military man.}
{101}{}{You see a military man, dressed in a dusty outfit.}
{102}{}{You convinced the military to show you the hiding place of the loot.}
{103}{}{You are not appreciated around here...}

{110}{}{[Waves his hands] Civilian, stop flickering before my eyes, I'm already tired.}
{111}{}{I see. Judging by the condition of your gear, you've just returned?}
{112}{}{Okay, I won't interfere.}

{113}{}{Well, yes, I patrolled the territory. Why do you care?}
{114}{}{Patrolled, right... Hmm. And you know, I heard they saw the military not far from the place where the "Speed Hawk"'s stagecoach has been crushed...}
{115}{}{Never mind.}

{116}{}{Well, and what we have to do with this? Wait, so, you want to put the blame for some robbery in the desert on honest military men? On us - the people who all these years tried to maintain order in southern Nevada?!}
{117}{}{I have evidence. So don't thwart me. Better think about it, do you have any suggestions?}
{118}{}{Maybe I can find a direct proof, and then...}

{119}{}{Then talk, Mr. inspector. Bring it right here. We, too, will find a claim to make. Ha!}
{120}{}{Actually, I already have a proof that those were you who raided the caravan. What can you say?}
{121}{}{Sure.}

{122}{}{[Looking around] Damn. You're too cunning for the wanderer. You almost had us cornered... Only a small question - where and how we should pay you. That's what you want, right? You want a percentage for your silence? Well, then let's go outside of the base and divide the loot.}
{123}{}{Your ingenuousness is a bit suspicious, but... Okay, lead the way to your hiding place. I'm watching you.}
{124}{}{Interesting proposal. I need to think over it. I'll come back when I decide.}

#Womens replica
{1110}{}{[Waves his hands] Civilian, stop flickering before my eyes, I'm already tired.}
{1119}{}{Then talk, Mrs. inspector. Bring it right here. We, too, will find a claim to make. Ha!}
{1122}{}{[Looking around] Damn. You're too cunning for the wanderer. You almost had us cornered... Only a small question - where and how we should pay you. That's what you want, right? You want a percentage for your silence? Well, then let's go outside of the base and divide the loot.}
