{100}{}{You see a private.}
{101}{}{It's a private, a soldier of the lowest rank.}

{102}{}{Alarm! We're under attack!}
{103}{}{I warned you! Someone's gonna get punished!}

#Стартовая ветка
{110}{}{Hold it! You're not allowed to be in the barracks. Get out. Move!}
{111}{}{I walk wherever I want! Do you understand me, grunt? Or shall I show it to you in pantomime?}
{112}{}{Barracks? I thought it was a hotel of some sort...}
{113}{}{What? You again?! That's it - if I see you in the barracks again, I will *personally* tear you apart, limb by limb! Understood?}