{100}{}{You see a soldier.}
{101}{}{You see Jim.}
{102}{}{You see a soldier, one of many. He holds a custom-made handgun in his hand.}
{103}{}{You see that guy Jimmy.}

{104}{}{The fight is over. To leave the ring, you have to move the barrier on the passage.}
{105}{}{You ran into a fight with the bastard. Show him who's the boss!}
{106}{}{*Inhospitably looks at you from under his eyebrows* Stop, no more...}

#======================================================
# Åñëè èãðîê íå ïîëó÷èë êâåñò îò êàðàâàíùèêà
#======================================================

{110}{}{[The man looks at you inhospitably from under his eyebrows as he continues to carefully clean his "Desert Eagle" with a piece of cloth.] What do you want? If it's about that caravaneer again, you'd better be passing by. Today I can't stand civilians especially hard.}
{111}{}{Calm down, I AM passing by.}

#======================================================
# Åñëè èãðîê çàâåðøèë êâåñò êàðàâàíùèêà
#======================================================

{115}{}{Huh? You want something?}
{116}{}{Calm down, I don't need you.}

#======================================================
# Åñëè èãðîê ïîëó÷èë êâåñò îò êàðàâàíùèêà
#======================================================

#Ðàçãîâîð äî îïîçíàíèÿ âîÿêè
{120}{}{[The man looks at you inhospitably from under his eyebrows as he continues to carefully clean the "Desert Eagle" with a piece of cloth.] What do you want? If it's about that caravaneer again, you'd better be passing by. Today I can't stand the civilians especially hard.}
{121}{}{And what if it's about him? Rumor has it that the military was involved.}
{122}{}{Just wanted to take a closer look at your gun. You don't see a good weapon often these days.}
{123}{}{Why are you so nervous? Okay, I'm leaving... Bye.}

{124}{}{Yeah, it's a cool gun... Got it for honorable service. You civilians don't understand what a gun can mean to a soldier! On the battlefield, separately, we are useless. But together we are a walking death factory! That's right, you bastards!!!}
{125}{}{You don't say? For what honorable services? Wasn't it for the recent cleanup at the train station? Well, don't worry - I'll ask Wesker over a glass of whiskey.}
{126}{}{So you value your personal weapon? Can you even remember its ID?}
{127}{}{Then I'll leave you with *your* piece... Ahem... Anyway, bye.}

{128}{}{Eh... 20... Hey, what are you trying to sniff out here? That's my trophy, okay?! The enemy can attack at any time, and guns should be in the hands of someone who knows how to use them! And that idiot in the caravan didn't even take the safety off... Oh, fuck...}
{129}{}{Here comes the truth, eh? Have something to add?}
{130}{}{Interesting information... We'll talk later, a threat-of-foes-and-caravaneers.}

{131}{}{Are you a little slow on the uptake? I don't know anything about this caravan! Shit, I need to change the recoil spring...}
{132}{}{Caravaneer recognized you, Jimmy. And you even showed up here with a stolen gun.}
{133}{}{Another question then.}
{134}{}{Nah, everything's clear as day... So long.}

{135}{}{[He looks at you with a frown from under his eyebrows] Because of people like you, reds will eventually take over the States.}
{136}{}{What reds? Don't play riddles with me. You have nothing more to say?}
{137}{}{Think about it. I'll back.}

{138}{}{[He looks at you with a frown] That's none of your business.}
{139}{}{}

{140}{}{He looks at you inhospitably from under his eyebrows as he continues to carefully clean the "Desert Eagle" with a piece of cloth.] Is there a problem, civilian ape?}
{141}{}{About that assault on the caravan - do you know something? Rumor has it the military was involved.}
{142}{}{Just wanted to take a closer look on your gun. You don't see a good weapon often these days.}
{143}{}{Is there a reason for such an out-burst? Okay, I'll go... Bye.}

{150}{}{What would you know about honor, you desert hobo?! If it weren't for us, you all would have been slaves long ago. And what thanks do we get? These hagglers from the wastelands rip us off every time! So it's only fair to take what's ours, even by force.}
{151}{}{You did the right thing, letting it slip. Now back to the point.}
{152}{}{You go on – I'll be back soon.}
{153}{}{What are you babbling about? Watch yourself - one kick to the jaw and you won't be able to speak for a week.}
{154}{}{...And on top of that - abandoning your military unit. What was that talk about the "untarnished honor of the uniform"?}
{155}{}{Just like that, in full view of everyone? Aren't you afraid of the general's spies?}
{156}{}{[He looks around] They won't turn in one of their own.}
{157}{}{You say "won't turn in"? You are fighting for values of the old America! Where's your honor!? What about your conscience!?}
{158}{}{Hm... Tough place. I think I should get out of here soon.}
{159}{}{}

#Ðàçãîâîð ïîñëå îïîçíàíèÿ âîÿêè
{160}{}{[Spits under your feet] You think some civilian rat can push me against the wall? Don't forget who's turf you're standing on!}
{161}{}{You can only babble while surrounded by your friends! Let's go out of the perimeter, you and me!}
{162}{}{It's a good gun, of course, but it's not suitable for large-scale combat. Maybe you could trade it in for something better?}
{163}{}{Let's go ask Wesker? Let him explain why he sold the territory to marauders and deserters.}
{164}{}{Take it easy - I'm leaving.}

{165}{}{Ha! Someone's got a death wish? Alright, I'm always ready to beat the shit out of some pesky civilian!}
{166}{}{Well, move your ass out of the perimeter. It's time to find out who's right.}
{167}{}{A bit later, Jimmy, a bit later...}

{169}{}{Yeah, you're right. Okay, $1000 - and you got yourself a "Desert Eagle". [mutters to himself] It's time to get rid of this junk...}
{170}{}{Alright, here. And enough with the raids - the enemy doesn't rest.}
{171}{}{What about trading for other weapon?}
{172}{}{Damn, I'm not ready for that kind of help to our glorious army.}

{173}{}{[Takes the money, counts them and gives the gun] Great deal. Now I can buy myself something good.}
{174}{}{See, there's always a peaceful solution. Take care.}

{180}{}{Huh. What can I say? Of course! With pleasure! But I prefer rifles and submachine guns - now that is the weapons worthy of a soldier. If you find anything like it, I'll be glad to swap this pop gun.}
{181}{}{Assault rifle - Is this what you need?}
{182}{}{Will combat shotgun suffice?}
{183}{}{What about a hunting rifle?}
{184}{}{I have... What did you want, again}
{185}{}{I have a powerful civil rifle, interested?}
{186}{}{}
{187}{}{}
{188}{}{}
{189}{}{I'll think about your proposal.}

{190}{}{[You make the exchange, he takes a long time to evaluate the new weapon.] Not bad for a wanderer. If I met more people like you, I would have been a local rich man long ago.}
{191}{}{See, there's always a peaceful solution. We're done here.}

{192}{}{Ah yes... General... Um, I wouldn't want a bad relationship with my boss, you know. Let's settle this amicably - I'll give you the gun, and you give it back to that caravanner with an apology. I don't have to go there myself, do I?}
{193}{}{Alright. Give me the gun. And don't you forget - Big Brother's watching.}
{194}{}{You, bogey, should speak from the stage in Vegas, rather than scare people with you imaginary connections. Do you think I'll work on me? Hell no!}
{195}{}{Well, maybe you'll grow up someday...}
{196}{}{Nah, I still want to beat you up. You should know your place, bastard.}
{197}{}{I'll think about it and return back later.}
{198}{}{Here's the gun. And... Don't forget about apologies and all that.}
{199}{}{See, there's always a peaceful solution.}

#======================================================
# Floating strings before the first conversation [unused!]
#======================================================

{200}{}{...Íå áûë òðóñîì Äæèì è ãåðîåì íå áûë}
{201}{}{Âîèíñêàÿ ñëóæáà øëà ñâîèì ÷åðåäîì:}
{202}{}{Äæèììè ïîïàäàë èç âèíòîâêè â íåáî -}
{203}{}{Ðàíåíîå íåáî îòçûâàëîñü äîæäåì.}
{204}{}{Ïåðâûì íà âîéíå ïîãèáàåò ñëàáûé,}
{205}{}{Àðìèÿ ïî æèçíè – âîë÷üÿ òðîïà}
{206}{}{Ïîìèðàåò Äæèììè ãäå-òî â Ãóàíäóíå:}
{207}{}{Äæèììè ïðîìàõíóëñÿ, íó à êðàñíûé ïîïàë...}
{208}{}{}
{209}{}{}

#======================================================
# Îêîí÷àíèå áîÿ
#======================================================

{210}{}{[Spitting blood, rubbing his jaw] You're good... For a civilian. I lost, time to pay. Will my bet suffice? I've got nothing else valuable with me now.}
{211}{}{Then give me the pistol - while I'm trying to forget your part in this story.}
{212}{}{No way, you have to die on this ring! We'll fight to the end!}

#======================================================
# Female character
#======================================================

{1172}{}{Damn, I'm not ready for that kind of help to our glorious army.}
{1210}{}{[Spitting blood, rubbing his jaw] You're good... For a woman. I lost, time to pay. Will my bet suffice? I've got nothing else valuable with me now.}
