{100}{}{You see a radio operator.}
{101}{}{You see a clerk of the General staff.}
{102}{}{You have problems, civilian?}

#Getting sympathy of the NPC:
{110}{}{This place if for staff only, as a civilian you cannot be here without permission.}
{111}{}{Sorry, what do you do?}
{112}{}{Uh... I have a permit... I'd better go.}
{113}{}{It's none of your business. I advise you to leave the room before I get angry!}
{114}{}{Are you some kind of a radio operator?}
{115}{}{Hmm, how rude. Okay, I'll go.}
{116}{}{[Opens eyes in amazement] Wow, what a knowledge. And who am I talking to?}
{117}{}{Oh, I'm called "Your Highness", and they usually bend the knee, addressing me.}
{118}{}{Okay...}
{119}{}{I'm here on a personal matter to General Wesker.}
{120}{}{I was just passing by.}
{121}{}{You scum, get out of here! Or should I make you?}
{122}{}{No, I'll go by myself.}
{123}{}{[Narrows his eyes incredulously] Well, if so, what do you want from *me*?}
{124}{}{[Narrows his eyes incredulously] Hmm? And my sources say that you are nothing more than a piece of shit to Wesker. Get out of here!}
{125}{}{I wanted to ask about this settlement, if you don't mind.}
{126}{}{Nothing already. Bye.}

{127}{}{Really? Usually all those interested end up beyond the gate... So what do you want?}
{128}{}{To learn the history of this place.}
{129}{}{What do you do, if it's not a secret?}
{130}{}{The Wind of War has a bad reputation with non-residents. Why?}
{131}{}{I'm interested in the General Wesker. How is he treated in this town?}
{132}{}{Nothing already. Bye.}

{133}{}{The General is a strong and charismatic man, he rallied the people to build these huts on the ruins of pre-war town of Pahrump. Without him we would have disappeared in history. Everyone here loves and appreciate Wesker, even when he... [short nervous pause with a choice of answer follows] is punishing the guilty, hmm.}
{134}{}{Guilty? There are such people?}
{135}{}{Soldiers are soldiers. Sometimes breakdowns happen, this job is nervous... But why am I so talkative with you! Now, civvy, watch your mouth!}
{136}{}{Uh, yes, of course, sorry...}
{137}{}{Well, we'll see.}

{138}{}{[Contemptuously snorts on your words] We are trying here to establish a normal life in harsh and unbearable conditions, we have no time to drop tears. Outsiders misunderstand it. We are protecting ourselves from the Wasteland, not terrorizing it.}
{139}{}{Okay.}

{140}{}{You, wanderers of the Wasteland, won't understand it with your wild and primitive conceptions. And you don't need to, just believe me.}
{141}{}{You are operating radar equipment, managing radio transmissions, right?}
{142}{}{Well, then another question.}

#Questions:
{143}{}{[Opens his eyes in amazement] Uh-hmm... Yes, that's correct. And how would *you* know that?}
{144}{}{You know, not all in the Wasteland are as wild and uncivilized as you think.}
{145}{}{Hmm, I've been doing surveillance of our territory thanks to this tech.}
{146}{}{}
{147}{}{Did you find the Area 51?}
{148}{}{Is this equipment remained in working condition since pre-war times?}
{149}{}{I have information that there is a vault somewhere. Can you tell me more?}
{150}{}{Okay, but I have another question.}
{151}{}{You know, I think that's all I wanted to know. Bye.}

{160}{}{Yeah, it still works. We brought the equipment from a military base, where it was securely stored in warehouses. And now even the mouse does not slip without our knowledge! Keep that in mind, civilian.}
{161}{}{Uh, sure.}

#Mini-shelter of the WoW:
{162}{}{Uh, well, it's not a secret. However, I won't advise you to go there - the place is already occupied. Unlike us, the mutants, will not negotiate. They have something like a nest there.}
{163}{}{A nest of the mutants? Are they bothering you?}
{164}{}{Okay, I'll keep in mind.}
{165}{}{Yes, periodically patrols stumble upon these creatures, sometimes we have to fend off the attacks even here, in the settlement. Fortunately, they walk in small packs; on the other hand, they usually attack at night, when they are hard to see, because of the dark. My job is to catch the signal of the approaching threats in time, through the infrared and speed detectors.}
{166}{}{Wow, cool! What if I clean out their nest?}
{167}{}{Do what you want. You need to talk about this with the General Wesker.}
{168}{}{Okay. But before I go, I want to ask another question.}
{169}{}{Then I'll go to the General.}

#Coordinates of the Area 51:
{170}{}{[Leans over to you with a very cunning and dangerous look] I am not allowed to share this information. So I advise you to *think*, before you ask...}
{171}{}{Oh yeah, right, let me think now, yes. [put $300 into the pocket of the employee]}
{172}{}{Oh, okay, I will consider it for the future. And you - don't forget about the mysterious wanderer with his full pockets...}
{173}{}{I don't need it anymore. I want to ask about something else.}
{174}{}{Then I'll go while my body parts are still intact.}

{175}{}{[Takes your hand and leans in] listen, wanderer, I have no doubt in your pockets, and I can legally check them out, without any mention of the secret base.}
{176}{}{Wow, uh, okay, buddy, relax, you are too nervous. [put $300 into his pocket]}
{177}{}{Uh, I was kidding, how could the simple wanderer line up his pockets? Uh... Let's talk about something else.}
{178}{}{Hey-hey-hey, let me go! No need to check my pockets, there's nothing in them, I was joking!}

{179}{}{That's another story! I think we understand each other, and this is so rare today. Wait one minute.}
{180}{}{All right.}

{181}{}{Yes, with such reputation as yours I wouldn't show my face here at all. Think of it as a compensation for spending my time. Now go away!!!}
{182}{}{Uh, okay, okay, I understand, uh, good night.}
{183}{}{You bastard! Give my money back!}

{184}{}{What!? What is this?! To offer such thing to a person on duty, who is responsible for the safety of this town? That's outrageous!}
{185}{}{Oh, sorry, sorry! Here's another hundred to compensate the stress of your hard work. Long live the Wind of War!}
{186}{}{[Looks in his pocket, biting his lips] Hmm, well, sometimes you have to relax. Now let's see how I will be able to... "thank" you. One minute!}
{187}{}{[After some time the clerk tells you the coordinates of the Area 51] And not a word to anyone! Or else... [makes a motion with his thumb crossing his throat]}
{188}{}{Sure, I understand! Thank you!}
{189}{}{You got the coordinates of the Area 51.}

#The history of the settlement:
{190}{}{No one has ever asked me about the history of the Wind of War. Yes, there is a great deal to tell about. I myself know only what I was told by my seniors.}
{191}{}{Continue.}
{192}{}{All of us are the descendants of people who made it through the war in safe vault. Our ancestors were of elite military unit from Hawthorne military base. At least, that's what they told us.}
{193}{}{When there were no one left to save in Nevada, they took shelter in prototype vault not far from here. The vault had codename "Wind of War", it was built specifically for testing purposes of the materials and technologies of vaults network.}
{194}{}{Time has passed, then we were born, still sealed inside the vault. When its resources ran out, we had to go outside and start a new life, struggling for a place under the sun.}
{195}{}{General Wesker took the situation under control. We settled in this ruins, rebuilt them, brought some weapons and tech from Hawthorne. Then blew up the vault and started to live here.}
{196}{}{But, turned out, we are not very much suitable for agricultural farming, yet we needed to survive. So, for the most part, we lived off the hunt. This area is mostly desert, so providing ourselves with food was not that easy.}
{197}{}{Then the "aliens" came, and it became especially hard. So, general resorted to different source of income - we became protectors for small settlements and transit point for caravans. Albeit slowly, our life started to come together.}
{198}{}{That was informative. Thanks for the story!}

{199}{}{I'm listening.}

#Women's replics:
{1120}{}{I was just passing by.}
{1121}{}{You scum, get out of here! Or should I make you?}
{1122}{}{No, I'll quit by myself.}
{1125}{}{I wanted to ask about this settlement, if you don't mind.}
{1151}{}{You know, I think that's all I wanted to know. Bye.}
{1154}{}{Well, uh, I read in some magazine...}
{1172}{}{Oh, okay, I will consider it for the future. And you - don't forget about the mysterious wanderer with his full pockets...}
{1175}{}{[Takes your hand and leans in] Listen, wanderer, I have no doubt in your pockets, and can legally check them out, without any mention of the secret base.}
{1177}{}{Uh, I was kidding, How could the simple wanderer line his pockets? Uh... Let's talk about something else.}
{1178}{}{Hey-hey-hey, let me go! You don't need to check my pockets there's nothing in them, I was joking!}
