{100}{}{You see a soldier.}
{101}{}{You see Jim.}
{102}{}{You see a soldier, one of the many. He holds some custom-made handgun in his hand.}
{103}{}{You see that guy Jimmy.}

{104}{}{Fight's over. To exit the ring, you should move the barrier on the passage.}
{105}{}{You ran into a fight with the bastard. Show him who's the boss!}
{106}{}{*Inhospitably looks from under his eyebrows* Stop, no more...}

#======================================================
# Если игрок не получил квест от караванщика
#======================================================

{110}{}{[Inhospitably looks from under his eyebrows, continuing to gently clean "Desert Eagle" with a piece of rag] What do you want? If it's again about that caravaneer, you'd better be passing by. Today I can't stand the civilians especially hard.}
{111}{}{Calm down, I AM passing by.}

#======================================================
# Если игрок завершил квест караванщика
#======================================================

{115}{}{Huh? You asked me?}
{116}{}{Calm down, I don't need you.}

#======================================================
# Если игрок получил квест от караванщика
#======================================================

#Разговор до опознания вояки
{120}{}{[Inhospitably looks from under his eyebrows, continuing to gently clean "Desert Eagle" with a piece of rag] What do you want? If it's again about that caravaneer, you'd better be passing by. Today I can't stand the civilians especially hard.}
{121}{}{And if about him - so what? Got information? The talk is there were some militaries spotted nearby.}
{122}{}{Just wanted to take a closer look on your gun. You don't see a good weapon very often these days.}
{123}{}{And why are you so nervous? Okay, I'm leaving... Bye.}

{124}{}{Yeah, it's a cool gun... Got it for honorable service. You, civilians, won't understand, what can weapon mean to a soldier! On a battlefield, individually, we are useless. But together we are walking factory of death! That's right, motherfuckers!!!}
{125}{}{An award, you say? For what services? Wasn't it for recent cleaning at the railway station? Alright, don't bother – I'll ask Wesker over a glass of whiskey.}
{126}{}{So you value that personal weapon? Can you ever remember its ID?}
{127}{}{Then I'll leave you with *your* piece... Ahem... Anyway, bye.}

{128}{}{Eh... 20... Hey, what are you sniffing here? It's my trophy, understood?! You can expect enemy assaulting us anytime - and the weapon should be in hands of someone who can use it! And this caravan moron didn't even put the safety off... Oh, fuck...}
{129}{}{So, the truth is out there, eh? Don't you want to add anything?}
{130}{}{Interesting information... We'll talk later, a threat-of-foes-and-caravaneers.}

{131}{}{You're a little slow on understanding? I don't know anything about this caravan! Damn, I should look for a recoil spring...}
{132}{}{Caravaneer recognized you, Jimmy. And you even showed up here with a stolen gun.}
{133}{}{Another question then.}
{134}{}{Nah, everything's clear as day... So long.}

{135}{}{[Looking at you from under his eyebrows glumly] Because of people like you, reds will eventually take over the States.}
{136}{}{What reds? Don't play riddles with me. Have nothing more to say?}
{137}{}{Think about it. I'll back.}

{138}{}{[Looking at you from under his eyebrows glumly] For my own. Not your business.}
{139}{}{}

{140}{}{[Looks from under his eyebrows, continuing to gently clean "Desert Eagle" with a piece of rag] Is there a problem, civilian ape?}
{141}{}{About that caravan - do you have information? The talk is there were some militaries spotted nearby.}
{142}{}{Just wanted to take a closer look on your gun. You don't see a good weapon very often these days.}
{143}{}{Is there a reason for such hate burst? Okay, I'll go... Bye.}

{150}{}{What could you know about honor, you desert hobo?! If not for us, you all would have been slaves for a long time. And what kind of appreciation do we get? These wasteland hagglers rob us to skin for each delivery! So it would be fair to take what's ours, even if by force.}
{151}{}{You did the right thing, letting it slip. Now back to the point.}
{152}{}{You go on – I'll back soon.}
{153}{}{What are you babbling about? Watch yourself - one kick to the jaw and you won't be able to speak for week.}
{154}{}{...And on top of that - unauthorized abandonment of military unit. What was with that talk about "untarnished honor of the uniform", or something?}
{155}{}{Just like that, for everyone to see? You're not afraid of general's spies?}
{156}{}{[Look around with open eyes] They won't turn in one of their own.}
{157}{}{You say "won't turn in"? You are fighting for the restoration of the old America! Where's your honor!? Where is your conscience!?}
{158}{}{Hm... Tough place. I think I should get out of here soon.}
{159}{}{}

#Разговор после опознания вояки
{160}{}{[Spits under your feet] You think, a civilian rat can press me against the wall? Don't forget which turf you're standing on!}
{161}{}{You can only babble while surrounded by your friends! Let's go out of the perimeter, you and me!}
{162}{}{It's a good gun, for sure, but not suitable for mass battle. Maybe you could exchange it for something better?}
{163}{}{Let's go ask Wesker? Let him explain, when he traded the territory for marauders and deserters.}
{164}{}{Take it easy -  I'm leaving.}

{165}{}{Ha! Someone's got a death wish? Alright, I'm always ready to beat some shit out of civilians!}
{166}{}{Well, move your ass out of perimeter. Time to decide, who's got the match.}
{167}{}{A bit later, Jimmy, later...}

{169}{}{Yeah, you're right. Okay, 1000$ - and you got yourself a "Desert Eagle". [mutters to himself] Time to get rid of this junk...}
{170}{}{Alright, here. And stop with the raids - the enemy doesn't sleep.}
{171}{}{What about some other weapon?}
{172}{}{Damn, I'm not ready to that kind of help for our glorious army.}

{173}{}{[Takes the money, counts them and gives the gun] Great deal. Now I can find myself something good.}
{174}{}{See, there's always a peaceful solution. Take care.}

{180}{}{Huh. What can I say? Of course! With pleasure! But I prefer rifles and submachine guns - now that is the weapons worthy of a soldier. If you find anything akin to it - I'll be glad to swap this pop gun.}
{181}{}{Assault rifle - Is this what you need?}
{182}{}{Will combat shotgun suffice?}
{183}{}{What about hunting rifle?}
{184}{}{I have... What do you say?}
{185}{}{A powerful civil rifle, interested?}
{186}{}{}
{187}{}{}
{188}{}{}
{189}{}{I'll think about that proposal.}

{190}{}{[You make trade, he evaluates new weapon for a long time] Not bad for a wanderer. If I met more people like you, I'd have become the local richman long ago.}
{191}{}{See, there's always a peaceful solution. We're done here.}

{192}{}{Ah yes... General... Hm, I wouldn't want bad relations with my boss, you know. Let's resolve this in amicable way - I'll give you the gun and you return it to that caravaneer with apologies. I shouldn't go there myself, right?}
{193}{}{Alright. Give me the gun. And don't you forget - Big Brother's watching you.}
{194}{}{You, bogey, should rather speak from the stage in Vegas, not scare people with you imaginary connections. Do you think I'll take it? Hell no!}
{195}{}{Well, maybe you'll grow up someday...}
{196}{}{Nah, I still want to beat you up, you should know your place, bastard.}
{197}{}{I'll think about it and return back later.}
{198}{}{Here's the gun. And... Don't forget about apologies and all that.}
{199}{}{See, there's always a peaceful solution.}

#======================================================
# Floating strings before the first conversation [unused!]
#======================================================

{200}{}{...Не был трусом Джим и героем не был}
{201}{}{Воинская служба шла своим чередом:}
{202}{}{Джимми попадал из винтовки в небо -}
{203}{}{Раненое небо отзывалось дождем.}
{204}{}{Первым на войне погибает слабый,}
{205}{}{Армия по жизни – волчья тропа}
{206}{}{Помирает Джимми где-то в Гуандуне:}
{207}{}{Джимми промахнулся, ну а красный попал...}
{208}{}{}
{209}{}{}

#======================================================
# Окончание боя
#======================================================

{210}{}{[Spitting blood, rubbing his jaw] You're good... For a civilian. I lost, time to pay. Will my bet suffice? I've got nothing more precious on me now.}
{211}{}{Then give me the pistol - While I'm trying to forget your involvement in this story.}
{212}{}{No way, you have to die on this ring! We'll fight to the end!}

#======================================================
# Female character
#======================================================

{1172}{}{Damn, I'm not ready for that kind of help for our glorious army.}
{1210}{}{[Spitting blood, rubbing his jaw] You're good... For a woman. I lost, time to pay. Will my bet suffice? I've got nothing more precious on me now.}