{100}{}{You see a tired military man.}
{101}{}{You see a military man in a dusty outfit.}
{102}{}{You persuaded the military to show you the stash with loot.}
{103}{}{You are the last person we want to see around here...}

{110}{}{[Waves his hands] Civilian, stop flickering before my eyes, I've had enough of you for one day.}
{111}{}{I see. Judging by the condition of your gear, you just returned from the wasteland, right?}
{112}{}{Okay, I'll get out of the way.}

{113}{}{Yeah, we were patrolling the area like we were supposed to. Why do you care?}
{114}{}{Patrolled, right... You know, some say there was some military men near the place where the "Speed Hawk" stagecoach got cut up...}
{115}{}{Never mind.}

{116}{}{Well, what's that got to do with us? Wait a minute - do you want to blame us, honest military men, for a robbery in the middle of the desert? Us, the people who have been trying to keep order in Southern Nevada all these years?!}
{117}{}{I have proof, so drop this attitude. Better think about what you could do about it.}
{118}{}{Maybe I can find some evidence first...}

{119}{}{Then we'll talk, Mr. Inspector. Bring it right here. We will see what to do about it together. Ha!}
{120}{}{In fact, I already have proof that you did the raid. What do you say?}
{121}{}{Sure.}

{122}{}{[Looking around] Damn. You are very sly for a wanderer. You had us pinned down... Then there's only one little question left - where and how we should pay you for your silence. That's what you want, right? A cut? Let's go outside of the base and you'll get it.}
{123}{}{Your simple-mindedness is a bit suspicious, but... Okay, lead the way to your stash. I'm watching you.}
{124}{}{What an interesting proposal. I need to think it over. I'll come back when I do.}

#Womens replica
{1110}{}{[Waves his hands] Civilian, stop flickering before my eyes, I've had enough of you for one day.}
{1119}{}{Then we'll talk, Mr. Inspector. Bring it right here. We will see what to do about it together. Ha!}
{1122}{}{[Looking around] Damn. You are very sly for a wanderer. You had us pinned down... Then there's only one little question left - where and how we should pay you for your silence. That's what you want, right? A cut? Let's go outside of the base and you'll get it.}
