{100}{}{You see a drill sergeant.}
{101}{}{You see a platoon commander, instructor and mentor.}

#Ïîïûòêà çàãîâîðèòü
{102}{}{Civilians?! I don't have time for this.}

#Êîãäà áîéöû îòæèìàþòñÿ
{110}{}{Come on, ladies!}
{111}{}{Good!}
{112}{}{One-two! One-two!}
{113}{}{Cut the whining!}
{114}{}{I'll make men out of you, even if you die in the process!}
{115}{}{Now with one hand!}
{116}{}{Now with no hands!}
{117}{}{No slacking, private!}
{118}{}{That's not how you do push-ups!}
{119}{}{Hey, bone bags! You'll be cleaning latrines for the rest of the day if you don't put some effort right now!}
{120}{}{Move it, move it!}

#Êîãäà áîéöû äåðóòñÿ
{130}{}{Yes! With the left! Left!}
{131}{}{The enemy is right in front of you!}
{132}{}{Anger! I don't see anger in your eyes!}
{133}{}{Grin! Show me your grin!!!}
#Grin?
{134}{}{Come on!!!}
{135}{}{Some of you still have a chance to become men!}
{136}{}{Talk about green berets!}
{137}{}{Arrrgh!!!}
{138}{}{Just like that!}
{139}{}{That's what I call a swing!}
{140}{}{Learn, while I'm still around!}
{141}{}{*These* guys? Warriors?!}
{142}{}{*Tsk-tsk-tsk*}
{143}{}{*You'll take my life but I'll take yours too*}
