{100}{}{You see Anders.}
{101}{}{You see a technician in dirty working clothes with numerous prints of fingers and... Bare feet!}

#Pulls you up, if you're trying to get into the garage
{108}{}{Thief! A thief in my garage!}
{109}{}{Damn, I was caught...}
{110}{}{Hey! Stop! You can't go there!}
{111}{}{Oops, I thought it's a bathroom...}
{112}{}{I warned you! You *cannot* go there! Do this again and someone gets hurt, get it?!}
{113}{}{Okay.}
{114}{}{That's it, you're screwed!}
{115}{}{What?! But I did nothing!..}

###############################################################
#
# The beginning of the conversation and the answers to the questions
#
###############################################################

#Starting dialogue branch:
{116}{}{What?}
{117}{}{About repair.}
{118}{}{I'm looking for one particular thing.}
{119}{}{I heard you have something awesome in the garage, with engine and lights. Wroom-Wroom! Is that true?!}
{120}{}{Well, what about my order?}
{121}{}{Oh, nevermind.}

#Search for items:
{130}{}{Well, I don't have the most extensive choice... What do you want?}
{131}{}{}
{132}{}{Ammo press. You'll be able to make one, right?}
{133}{}{I heard there's a high-tech vault somewhere nearby?}
{134}{}{Cleaning filter for the artesian water tower in Salt Lake.}
{135}{}{Do you have gunpowder in stock, by any chance?}
{136}{}{Maybe you've got something useful to trade?}
{137}{}{Nothing really.}

#Purchasing gunpowder:
{140}{}{Correct!}
{141}{}{What? I will not crawl into someone else's warehouse! Forget it.}
{142}{}{I might maybe arrange a deal with someone, but it will take a whole day, and I have to pay the soldier who guards the warehouse. So, 1000 bucks - and in two days you will receive a package with gunpowder.}
{143}{}{Here is 500 for deposit, you'll get the rest when the package is ready.}
{144}{}{Nevermind then.}
{145}{}{Don't mess with me. I have no sense of humour.}
{146}{}{Got it.}
{147}{}{Okay, that's fair. I'll do it. The box will be yours, but not earlier than in two days.}
{148}{}{Okay.}
{149}{}{Well, what about my order?}
{150}{}{I have the box. Where's my money?}
{151}{}{Here's $500.}
{152}{}{I'll go get it.}
{153}{}{An excellent deal, but I can't get you more gunpowder, otherwise the loss will be detected and they begin ransacking people.}
{154}{}{Wow! This will be enough for a whole platoon.}

{155}{}{Gunpowder? Wesker forbids us to take away such valuable resources. I will sell no powder to you.}
{156}{}{To think you can't take a little bit from the warehouse... [wink]}
{157}{}{Okay.}
{158}{}{Warehouse? Me? I won't be even allowed to enter! But... [leans over to you and talks quietly] on the other hand, it's not necessarily should me, right? [winks at you]}

#Artesian water filter
{159}{}{Oh, yes, I've heard about the thing from the caravaneers. Frankly, I would have already found it and transported to Salt Lake myself. But I have no idea where to get one!}
{160}{}{What a pity.}

#Reloading press
{161}{}{I can't make it. And if I sell the one I work with - Wesker will bolt me to the fence, like some deserter. So, no, no and no again.}

#About the shelter
{167}{}{High-tech, you say? Ha! I would look at you after several years of living in that shithole. We got out of there, when it became impossible to live in. That vault was not expected to be used at all. It was an experimental facility, to test materials and technologies. Nothing more. And how do you know about it anyway?}
{168}{}{Have read about it on the old holodisk.}
{169}{}{Uh... Just the rumors.}

{170}{}{Old holodisk? That's very interesting!}
{171}{}{I can show you the entry on my Pip-Boy.}
{172}{}{Uh, I don't have the holodisk with me. It was lying in the office in Hawthorne.}
{173}{}{None of your business, old man.}
{174}{}{None of my business, you say? When our guys will hang you by your feet over a burning barrel, you'll think otherwise.}
{175}{}{Damn, look, I want to warn you - there are those in our community who must not see this tape. This... Could lead to unpleasant consequences. [menacingly approaches you] Do you understand me, outlander? Unpleasant *for us all* and for you in particular. Don't do anything stupid.}
{176}{}{Oh, it's that serious...}
{177}{}{Don't threaten me. I'll just leave.}
{178}{}{Apparently, not everyone in this city will be pleased to learn that they are descendants of deserters.}
{179}{}{Well, I suppose. However, it doesn't matter now. After all, we blew up the vault when the mutants have settled in it.}
{180}{}{Is it dangerous in there?}
{181}{}{Sure. So no one will guide a tour for you.}

###############################################################
#
# About repairing
#
###############################################################

{200}{}{That's my department! What do you want?}
{201}{}{Can you upgrade my armor?}
{202}{}{Can you upgrade my weapons?}
{203}{}{}
{204}{}{Nothing.}

{205}{}{Not enough. Strange, isn't it?}
{206}{}{Hmm.}
{207}{}{Then you'll have to take off your armor. Or do you want me to work on it with a blowtorch, while it's still on you? Not a problem, I mean, for me, hehe.}
{208}{}{Let's do it without risks to health. I'm taking it off...}

{228}{}{Uh... What now, what now... Now I need }
{229}{}{ bucks to go to the train, also the train coordinates and other information about how to get there and where to find what.}

{230}{}{Only metal and leather ones. Those I already know how to handle.}
{231}{}{Leather armor.}
{232}{}{The old metal armor.}
{233}{}{Metal MK2 armor.}
{234}{}{I changed my mind. It is not necessary.}
{235}{}{Oh, I don't have so much money...}
{236}{}{No questions. Will do it for }
{237}{}{ bucks.}
{238}{}{Here's the payment, I'll wait.}
{239}{}{(Right in front of you the technician turns the armor into something new!)}
{240}{}{(Right in front of you the technician turns the armor into something new and shiny!)}
{241}{}{That's what I call service!}

{242}{}{Hey! I'm not going to pick up *your* stuff!}
{243}{}{Oh, I'll pick it up now...}

{244}{}{I'm sick with firearms already. Mostly, I work with weapons all the time - "fix me this", "attach this to that"... Basically we are talking about military firearms - rifles, shotguns, even rocket launchers, and other pleasures of a good soldier.}
{245}{}{}
{246}{}{The charging accelerator for a Magnum revolver.}
{247}{}{Assemble dynamite from 5 sticks of dynamite.}
{248}{}{Disassemble dynamite into dynamite sticks.}
{249}{}{Back.}
{250}{}{}
{251}{}{I don't care, I like it. Fix it!}
{252}{}{So, it's not worth it? Forget it, then.}
{253}{}{}
{254}{}{}
{255}{}{Increase the clip capacity of the assault rifle.}
{256}{}{No problem. Will do for }
{257}{}{ bucks.}
{258}{}{Ready!}

#Fixing the train
{260}{}{I have the order. I need to fix the on-board computer of the train.}
{261}{}{Train's computer? Curious. [pompously touches the computer with fingertips] It seems to be missing something. Need to look more into it. For }
{262}{}{ I'll puzzle it out.}
{263}{}{OK, I'll pay. But I will ask on it painstakingly!}
{264}{}{I'll come back when I'm ready for such expenses.}

{265}{}{Hey-hey-hey! No need to scatter money on the floor!}
{266}{}{Fair point.}
{267}{}{Ah, now everything is clear to me. A couple of days will be spent on preparations, and while I'm there it won't take long... Maybe.}
{268}{}{That's good. I'll check the work.}
{269}{}{You have found a way to fix the train. Congratulations!}

###############################################################
#
# The car
#
###############################################################

#Questioning about the car:
{270}{}{Wait a minute! How do *you* know what's going on in my garage, huh? Answer me!}
{271}{}{Calm down! It's just some people heard a definitive sounds near it, that's all.}
{272}{}{Hmm... Sounds logical. Well, of course, I have some tech in there... And almost working one.}
{273}{}{So, the rumors were true. And if not a secret - what is it? Can I look at it? Can I purchase it?}
{274}{}{I'm busy repairing a really cool piece of technology, but you'll have to save money for the rest of your life to be able to buy it.}
{275}{}{Oh, come on! Not for me to tell you this...}
{276}{}{All right. But money alone won't be enough anyway...}
{277}{}{Hey, stop tormenting me! Tell me what do you have in the garage?! What?! A generator? A cart? A bike? A helicopter?.. or a CAR?!!}
{278}{}{A pickup truck. Almost as good as brand new. But, as I said, it doesn't run.}
{279}{}{Oh, that would be great to see a real working car. Yes, it's the coolest thing you can find to explore the Wasteland!}

{280}{}{That's right. Pickup is best suited for our landscapes, so I took it for repairing. But the work stopped because of a single part. I need a fuel controller, otherwise the car won't move itself.}
{281}{}{Very interesting. Hey, tell me about these cars in more details.}
{282}{}{I travel a lot and can find the missing piece.}
{283}{}{If I find this item, I will try to return fast.}

{284}{}{I've seen a lot of broken cars. Why they were abandoned?}
{285}{}{How did you manage to buy your truck?}
{286}{}{What's the problem with the controller?}
{287}{}{Why is it so hard to fix the car?}

{288}{}{Actually, there are several reasons. Imagine how it was during the Great War. The bombs mainly fell on cities, where the most of the cars were. Those that stayed mostly intact, being away from explosions, simply had no place to get repaired and refueled anymore. These pre-war cars, powered by nuclear batteries, were complex in terms of technology and maintenance, they required good care and constant monitoring. In addition, they were very expensive, and not everyone could afford to buy them. Also, add to the picture the horrors, that came after the War: the mass deaths, criminals everywhere, traffic jams on the streets... Loads of cars were left abandoned under the open sky, so in 70 years they just fell apart from aging. And these are just the few reasons.}
{289}{}{It remained in the garage of one of the houses in Pahrump. But the former owner used this car to the fullest, so I had a lot of trouble putting back parts and interior. The only problem left unsolved now is having a fuel controller.}
{290}{}{}
{291}{}{Controller is a chip which controls the distribution of power in the electric engine of the vehicle. These chips burned out fast, if the car hasn't been properly maintained. Mostly, it used to happen due to the fact, that the cars were too often pulled off with high-speed right from the start, in a sharp manner. While it's necessary to accelerate smoothly, from low levels. It is difficult to explain why this was happening. Anyway, in all of the few cars I managed to find in the neighborhoods, there were no working chip, that could be used for that kind of pickup truck.}
{292}{}{It's a really complex technology. More complex than computers, or even a radar station, believe me. Can you imagine how many electronics is in there? And the engine is literally a bomb! It took me a few years to roughly understand the structure of this car.}

{293}{}{Then look carefully. It hardly makes sense to search among the scrap metal abandoned under the open sky. I would start with the places, where cars stayed locked-in - garages and repair shops. And I should say, that I placed an order with the caravaneers in Vegas and Reno, but they all failed. Perhaps, you should look even further from civilization.}
{294}{}{We can talk about it for hours.}

#When you got the controller
{295}{}{Here it is - the fuel controller!}
{296}{}{Looks like a working one... Ohh, I'm so excited that my hands are sweaty.}
{297}{}{Not so fast! What do I get for this chip?}
{298}{}{That's a good question. Look, let's do like this: I'll buy this chip for 2000 in cash from you, then I'll fix the car - it will take some time - and then you can buy the whole truck. If you want to, of course.}
{299}{}{Hmm. And for how much?}
{300}{}{Great idea, here is the controller.}
{301}{}{No way. I'll keep this thing for a while.}
{302}{}{I was counting on a price of $35,000. And only in cash! And don't waste time on persuading me, I want to fix this car first.}
{303}{}{Let's talk again about cars.}

{308}{}{Here is the money. I think, one day should be enough to finish the work. Come back tomorrow, then we can discuss a purchase, if you're still interested.}
{309}{}{All right.}
{310}{}{}
{311}{}{}
{312}{}{[Goggles at you in horror] What are you doing, you idiot?!! It's a very fragile thing!!!}
{313}{}{Don't worry, it didn't break...}
{314}{}{Well, how's my truck?}

{315}{}{Yours? It's still *my* truck, weirdo! And, you know - it's just gorgeous! All my life I have been dreaming of thing like this, and I don't know if I'm ready to sell it to a complete stranger.}
{316}{}{I understand. What amount will comfort the bitterness of your loss?}
{317}{}{. And only in cash!}
{318}{}{Here's the full desired amount.}
{319}{}{Are you sure?}
{320}{}{What? Not enough money? Hmm, strange...}

{321}{}{Give me time to think.}
#Women dialogue branch
{322}{}{This is a large sum. Tell me, are there any ways to make good money in this town, with a body like mine?}
{323}{}{This body is, at best, could work as a floor mat at the station's entrance. Tidy yourself up first. Maybe then those willing with tight purses appear.}
{324}{}{Oh, this changes everything! For the legs like this I wouldn't mind paying myself, I can invite my friends, too.}

###############################################################
#
# Other
#
###############################################################

{325}{}{Lighten the grenade launcher.}
{326}{}{Strengthen the power of the flamethrower.}
{327}{}{Knapsack fuel tank for the flamethrower.}
{328}{}{Increase magazine capacity of the "Desert eagle".}
{329}{}{Put a sight on the hunting rifle.}

{330}{}{}
{331}{}{Oh, piss off, you boor!}
{332}{}{As you wish. We suggest, you decide.}

{333}{}{Then remind me the price.}
{334}{}{This is too much. To acquire that amount of money, the whole caravan will have to work for a year. Think again, if you don't want to lose a client.}
{335}{}{Well, it's worth it. Where we shall fall in, tough guy?}
{336}{}{No, I don't like it. Goodbye.}

{337}{}{Uh, strong argument... Okay, you win. I am willing to reduce the price by }
{338}{}{. But that's my final offer.}
{339}{}{I understand. so now it's...}
{340}{}{Oh, okay. Let's go back to the previous price...}
{341}{}{No, I've put too much work into this.}

{342}{}{You have earned 1000 bucks giving in to the technician. He was a cruel pervert. Bruises all over your body will hurt for some time.}
{343}{}{On second thought, I will collect the money by other means.}
{344}{}{Baby, the money you gave me won't be enough even to compensate the treatment of bruises. I recall, you said something about your friends?}
{345}{}{To make a sewed shotgun from a hunting shotgun.}
{346}{}{I'll come back later.}
{347}{}{Are you sure you want this? Our guys from the garrison are exceptionally persistent, if allowed they may turn you into a pulp.}
{348}{}{Yes... I... Have to go through it for money.}
{349}{}{Simultaneous sex with five military men is a tough thing. You are happy to be alive. Nevertheless, you have earned 5000 bucks.}

###############################################################
#
# Power armor
#
###############################################################

# Question about a helmet
{371}{}{Have you ever seen the armor with such a helmet?}
{372}{}{[Carefully examines the helmet] actually it's not from armor, but from a sealed suit. I think it was used before the war in some laboratory.}
{373}{}{Is there a way to restore the main part?}
{374}{}{The whole suit? Of course not! For the task like this I have neither tools, nor machines, nor materials. Ask mechanics in large industrial cities. In Salt Lake City, for example. The don't have such problems with equipment and components.}
{375}{}{Okay.}

# Asking about the armor and the blueprints
{376}{}{Do you know anything about power armor?}
{377}{}{About the power armor blueprints.}
{378}{}{Hmm...}
{379}{}{}

{380}{}{A little bit. And all I know isn't worth a dime without high-tech machines and materials. But you can still see one working armor in Nevada. Wesker never takes one off, he will stay in it till he dies, I think...}
{381}{}{Wesker wears a working one?}
{382}{}{Not exactly. It has no helmet, it can't be fully sealed and some features are not working. Servicemen brought this junk from the test site in Hawthorne. It was used for durability testing there - so now it's made of holes, which are made of holes.}
{383}{}{And how this remnants were repaired?}
{384}{}{They were not. It is what it is. There is no components, no tools, let alone the production machines. But why the hell are you interrogating me?!}
{385}{}{Obviously, I would like the armor like this for my personal use.}
{386}{}{Just out of curiosity. Thank you for explaining everything I wanted to know.}
{387}{}{Of course... Who wouldn't... But it doesn't matter. Wesker will not part with the armor, and we don't have another one. Even with all the blueprints on hand, we won't be able to arrange the production, it's too complicated and time-consuming. Before the war, the entire production facilities were up on producing them, there have been hundreds of specialists, high-precision machines, the prototypes took years to mature, and now you come here and say "I want one of these". Ha!}
{388}{}{So no working suit has survived up to the present day except the one on Wesker?}
{389}{}{All you can get are useless blueprints. Power armors were in possession of military units, and even back then they were in shortage. What do you think, where are they now? Of course, whether on military bases where we can't reach them, or destroyed over time. I say - head to the East, to Washington, and who knows, maybe you can find one among the ruins of the capital. Heh, good luck with that.}
{390}{}{I see... Wait, blueprints? Do you have the blueprints?!}

{391}{}{Damn, I finally blurted out, didn't I? I don't know why you need them, but this sort of things is not handed out to complete strangers. There are blueprints of the frame structure at the headquarters, but that's only a part of the whole documentation. And, of course, no one will hand it to you.}
{392}{}{I am able to buy it.}
{393}{}{*You're* going to get me the blueprints.}
{394}{}{I'll try. The headquarters, you say? Okay, I'll go see what's this all about.}
{395}{}{To BUY!? You won't have the amount enough to pay for such a rare documentation!}
{396}{}{I thought you said they are worthless?}
{397}{}{When there is a buyer, everything gets a price. Okay, so be it, I'll get you the blueprints. For 3000 bucks.}
{398}{}{Okay, I need those blueprints. Here is the payment.}
{399}{}{That much!? I thought the huckster is sitting in the next room, but this... I'd rather find another way.}

{400}{}{[You wistfully wait behind the locked doors while the technician goes out somewhere on the territory of the headquarters; finally he returns with the holodisk in his hand, warily looking around] If I'd have been paid for this stuff routinely, I would have bought the whole Vegas by now. Don't say a word to anyone!}
{401}{}{No problem.}

{402}{}{Is that so? And why would I do that?}
{403}{}{Because I'll pay.}
{404}{}{Because if you don't, I'll report you to Wesker.}
{405}{}{If you don't need it, I will not insist.}

{406}{}{Buddy, look at my kind and sympathetic face. How could I do something bad to the wanderer of the Wasteland?}
{407}{}{You gave yourself away - you tried to kill me, but I got your note from the body of a mercenary.}
{408}{}{[Looks like he considers to shoot you on the spot, but suddenly changes in face] As you wish. It's easy for me to get the blueprints. But when I do, you'll give the note back and I will destroy it.}
{409}{}{Sure, let's do it.}
{410}{}{Don't rush things, I need to think this over.}

{411}{}{Where?}
{412}{}{Uh...}

{413}{}{[You wistfully wait behind the locked doors while the technician goes out somewhere on the territory of the headquarters; finally he returns with the holodisk in his hand, warily looking around] I got what you wanted. Now it's your turn.}
{414}{}{All right. We will part ways peacefully and quietly.}
{415}{}{It failed...}

#Women's replics
{1111}{}{Oops, I thought it's a toilet...}
{1114}{}{That's it, you're screwed!}
{1115}{}{What?! But I did nothing!..}
{1146}{}{Got it.}
{1168}{}{Have read on the old holodisk.}
{1175}{}{Damn, look, I want to warn you - there are those in our community who must not see this tape. This... Could lead to unpleasant consequences. [menacingly approaches you] Do you understand me, outlander? Unpleasant *for us all* and for you in particular. Don't do anything stupid.}
{1234}{}{I changed my mind. It is not necessary.}
{1312}{}{[Goggles in horror at you] What are you doing, you idiot?!! It's a very fragile thing!!!}
{1315}{}{Yours? It's still *my* truck, weirdo! And, you know - it's just gorgeous! All my life I have been dreaming of thing like this, and I don't know if I'm ready to sell it to a complete stranger.}
{1407}{}{You gave yourself away - you tried to kill me, but I got your note from the body of a mercenary.}
