{100}{}{You see private Derren.}
{101}{}{You see young private Derren. Not a lot could be said about him.}
{102}{}{My, uh, orders don't allow me to talk to you.}
{103}{}{"Thank you" very much. Now I won't be able to get rid of them in my lifetime. Though the girl's nice, maybe we'll get along.}

{110}{}{I'm on my duty and can't fool around.}
{111}{}{So you're the private that old redneck's looking for?}
{112}{}{Bye.}

{113}{}{Well, heh, ugh... They told you too? Oh, shame on me... Wait, who are you? I saw you with Wesker, but you're not from the garrison. Who are you?! Name yourself!}
{114}{}{A freelancer, doing odd jobs for Wesker. And don't even think of dodging the question.}
{115}{}{I didn't! I just don't know what to do... These rednecks won't go away that easy. And I wouldn't want rumors about me to spread around the garrison.}
{116}{}{Which means what pops said was true? You bonked his daughter, didn't you?}

{117}{}{[Scratches his head] Yeah, it's true... I did. But I'm not some kind of barbarian! While the quartermaster was with the locals, I went patrolling around the barn - and there she was. And she didn't even have to be asked. She practically fell on her back - Woo-hoo, if only it worked like that every time!}
{118}{}{So, now you have a box for a lifetime.}
{119}{}{Do you think Wesker would approve of your behavior?}
{120}{}{Why not go to them to negotiate and to confess?}
{121}{}{}
{122}{}{I can get rid of them. But not for free.}
{123}{}{Hey, who brewed up all this mess? Clean up after yourself! And I'll go mind my own business.}

{124}{}{What? Hey, you're not saying that... What the hell!? So this cretin wants to drop a fiancee on my lap!? Oh...}
{125}{}{Aren't you handsome? Apparently its mandatory to look after oneself in the garrison. No surprise this country girl gave herself to you so easily.}
{126}{}{Huh? Did you see her?! The face is all freckled, the muzzle is square-shaped. But yeah, there aren't many girls around here, it's true. Of course, it's better than nothing. But not with that family! I saw those villagers, it's far better to pass as coward than enroll in their family.}
{127}{}{Certainly not! In his case it's better to keep your mouth shut. Do you, uh, understand that? If not, then, uh... Look, just know that it's better to leave the General out of this.}
{128}{}{Are you crazy!? Did you see that family! The girl might be cute, and there's not much to choose from in these parts, but to interact with her family? I'd rather hang myself. I didn't spend all those years in the garrison to live the rest of my life surrounded by rednecks.}
{129}{}{Well, that's an exaggeration. More like pops just wants to drop his daughter on you to feed fewer mouths.}
{130}{}{Maybe so. But imagine what kind of rumors about me would spread through the garrison. It's the villagers. Although we protect them from bandits, nobody cuddles with them.}
{131}{}{What a fool. A coward's fame is no better.}
{132}{}{Until I'm forced to - I won't go to them. And I don't care what anyone says.}
{133}{}{Really? Uh, look, I'm not asking anything extreme, just make them leave Wind of War. Okay? I will pay you all the money I have in my stash - 300 bucks. They have no reason to hang around here. Let them just go back to farming.}
{134}{}{Deal.}

{135}{}{Rednecks won't bother you again. You can check it, if you want.}
{136}{}{Really? Phew, what a relief! You're not trying to deceive me, aren't you? Of course not, why would you... I promised 300 bucks. Here, now they're yours. But don't tell anything to general.}
{137}{}{Not bad. Look, just don't get caught another time. You'll be on your own.}
{138}{}{You again? Want to talk about these rednecks?}

#Æåíñêèå ðåïëèêè
{1113}{}{Well, heh, ugh... They told you too? Oh, shame on me... Wait, who are you? I saw you with Wesker but you're not from the garrison. Who're you?! Name yourself!}
{1128}{}{Are you crazy!? Did you see that family! The girl might be cute, and there's not much to choose from in these parts, but to interact with her family? I'd rather hang myself. I didn't spend all those years in the garrison to live the rest of my life surrounded by rednecks.}
