{100}{}{You see private Derren.}
{101}{}{You see young private Derren. Not a lot could be said about him.}
{102}{}{My, uh, orders doesn't allow to speak with you.}
{103}{}{"Thank you" very much. Now I won't be able to get rid of them in my lifetime. Though girl's nice, maybe we'll get along.}

{110}{}{I'm on my duty and can't fool around.}
{111}{}{So you're the private for whose soul that old redneck came for?}
{112}{}{Bye.}

{113}{}{Well, heh, ugh... They told you too? Oh, shame on me... Wait, who are you? I saw you with Wesker, but you're not from the garrison. Who are you?! Name yourself!}
{114}{}{A freelancer, doing odd jobs for Wesker. And don't you think to dodge the question.}
{115}{}{I didn't! I just don't know, what to do... These rednecks aren't easy to fall behind. And I wouldn't want the rumors about me to spread around the garrison.}
{116}{}{Which means, what pops said was true? You did his daughter, didn't you?}

{117}{}{[Scratches his head] Yeah, it's true... I did. But I'm not some kind of barbarian! While quartermaster have been with the locals, I was patrolling around the barn, and - there she is. And she weren't in need of any asking. She herself fell on her back - woo-hoo, if only it worked like that every time!}
{118}{}{So, now you have a box for a lifetime.}
{119}{}{Do you think Wesker would approve your behavior?}
{120}{}{Why not go to them for negotiations and to confess?}
{121}{}{}
{122}{}{I can get rid of them. But not for free.}
{123}{}{Hey, who brewed all this mess? Clean up after yourself! And I'll go mind my own business.}

{124}{}{What? Hey, you're not saying that... What the hell!? So this cretin wants to drop a fiancee on my neck!? Oh...}
{125}{}{Aren't you a handsome. Apparently, it is mandatory to look after oneself in the garrison. No surprise this country girl gave herself to you so easily.}
{126}{}{Huh? Did you see her?! All face is freckled and square-shaped muzzle. But yeah, there aren't many girls around here, it's true. Of course, it's better than nothing. But not with such a family! I saw these villagers, it's far better to pass as coward than enroll in their family.}
{127}{}{Certainly not! In his case it's better to keep your mouth shut. Do you, eh, understand that? If not, then eh... Look, just know that it's better leave general out of this.}
{128}{}{Are you crazy!? Did you see that family! The girl might be cute, and there's not much to choose in these parts, but interacting with her family - I'd rather hang up myself. I didn't live so many years in garrison only to be left around rednecks for my entire life.}
{129}{}{Well, that's an exaggeration. More like pops just wants to drop his daughter on you to feed fewer mouths.}
{130}{}{Maybe so. But imagine what kind of fame about me will be spread among ourselves. It's the villagers. Although we protect them from bandits, nobody rushes to cuddle with them.}
{131}{}{What a fool. A coward's fame is no better.}
{132}{}{Until I'll be forced to - I won't go to them. And I don't care what are talking about.}
{133}{}{Really? Eh, look, I'm not asking anything extreme, just make them leave Wind of War. Okay? I will pay you all the money I had in the stash - 300 bucks. They have no reason to hang around here. Let them just go back to farming.}
{134}{}{Deal.}

{135}{}{Rednecks won't bother you again. You can go check now.}
{136}{}{Really? Phew, what a relief! You're not deceiving me? Of course, who could, everyone knows each other... I promised 300 bucks. Here, now they're yours. But don't reveal anything to general.}
{137}{}{Not bad. Look, just don't get caught second time. You'll be on your own.}
{138}{}{You again, to talk about these rednecks?}

#Женские реплики
{1113}{}{Well, heh, ugh... They told you too? Oh, shame on me... Wait, who are you? I saw you with Wesker but you're not from the garrison. Who're you?! Name yourself!}
{1128}{}{Are you crazy!? Did you see that family! The girl might be cute, and there's not much to choose in these parts, but interacting with her family - I'd rather hang up myself. I didn't live so many years in garrison only to hang around rednecks for my entire life.}