{100}{}{You see a redneck.}
{101}{}{You see a rough and chatty redneck. About these usually said "shuts up any blabbers".}
{102}{}{Hey, you! You're not one of the militaries, are ye? Oh, I'd beat you up reel hard if you were!}
{103}{}{Hey, It's you who managed to stir up the conscience o' thugs from the garrison? Thanks!}

{110}{}{[It seems that this weirdo likes to talk much and loud] Hey, you! Howdy! Come on, come to us! Come, I say! Aye-aye, I'm talkin' to ye! Won't refuse to keep us company, will ya? Don't just stand there, what am I, some wasteland nipper?! I've seen some stuff ye wouldn't believe!}
{111}{}{Wait a minute, not so fast. Who are you exactly?}
{112}{}{Ah yeh, forgive a redneck. Our people are plain. What else we have to do, while waitin' fer crops to grow, or at the evenin', when it's dark at the yard? Only to chat and swing with fists. But I'm talkin' too much. Meet my daughter, Christine. Good girl, don't pay attention to her freckles [makes a sweet muzzle]. She's re-e-a-ally lovely, aren't she? Just look at her [Christine mutters under her breath with nasal voice, "da-a-ad!"]! Silence! Or I'll bash yer head and you'll shuddup reel fast!}
{113}{}{Eh...}
{114}{}{Ahem. So I'm an ol' redneck. Name's Festus. Should be called John, would be more militant, but alright - Festus' fine too. Everyone around knows me! Ask any redneck in villages nearby - everyone tell good about Festus. Well, sometimes good, sometimes bad... But no' one treats me without respect. Aside from those thugs on the other side of the fence. Oh, I would beat them up reel hard, damn them all!}
{115}{}{Eh, can you elaborate? How did these militaries angered you, Festus?}
{116}{}{Straight to business - I like that! We'll get along well, son. Just keep your powder dry, as I always say, heh-heh!..}
{117}{}{About those militaries...}
{118}{}{Don't interrupt me! I almost gathered my thoughts... So, these militaries provoked us. O-oh, they provoked us so hard! They came to collect taxes, then one of them got a crush on my girl and dragged her right into the bushes! If I were nearby, I'd beat him reel hard! Only later we found out. We searched for our Christy everywhere, 'cuz she ran away to hide her disgrace. But you know, we, rednecks, care for each other! It's not the first time! Found her, warmed her up, and situation became clear. Now I'm lookin' for justice. I want to not just hammer private's face, but to make him answer before the family! But we couldn't get past the checkpoint. I got angry, beat up the guard, they chased me away. Now I don't even know what to do.}
{119}{}{Ugh. Finally, at least something cleared up. So, one of privates raped your daughter, you angered and started the conflict at the checkpoint. Right?}
{120}{}{What else I could do? We weren't allowed inside, so I flamed up a bit. Anyway, they probably calmed down. And I'm also tired too. I'll sleep this night and go back to hittin' faces. You be sure about it.}
{121}{}{Could you tell me more?}

#Вопросы
{122}{}{Huh? What's that? Now tell, don't be shy. Speak louder, it's rude to whisper among us.}

{123}{}{Sorry for a question, but how old is your daughter?}
{124}{}{Sixteen! So what!?}
{125}{}{Don't be so nervous. It's just - that difference in age...}
{126}{}{What the hell are ye implyin'!? Although, I know what ye talkin' about, these habits among ya cityfolks. We're different. Families are big. Do ya know how many kids I have? Seven! I swear! Every year my wife fires off a child, like there's a cannon between her legs  - bam! Bam! But Christine is our last, we won't handle any more. And you'd better ask, how old is my WIFE! Ha-ha-ha-ha-hah!}
{127}{}{Eh, I'd rather not.}

{128}{}{You said something about taxes?}
{129}{}{[Scratches his unshaven cheek, expressing absence of interest to this topic] Our village's small, just a few families, though big. And militaries are our guard. If somethin' happens - we can call for a help. In exchange we give them some grub. [Spits in between] No big deal.}
{130}{}{Who raped your daughter?}
{131}{}{A private, his name's Derren. Stupid name and pimly lad. But for us even this is enough. I saw him - sticks to the post, doesn't go anywhere. Ugh, when I get to him!}
{132}{}{And how the rape exactly happened?}
{133}{}{I will tell ya, but ye'll have to wash your ears with soap! We all gathered at the center of our village. Militaries rolled in, all so important, placed their watchers everywhere. And when there was time to leave, they lost their Derren - he just disappeared! Then I see him - he, asshole, exits the barn. At first I didn't understand what happened. He receives a reprimand and goes away with the others. As for Christine - she's nowhere in sights! We found her hour later, far away, sittin' on a cliff, I had never seen her like that. Bruises, blood and tears? No, not in our folk. She only said that she was with Derren in the barn. And then everythin' became obvious! The wife examines her and says that after 9 months we'll get another one in the family. Well, look, this is not how things are done, right? So I came for justice!}
{134}{}{Perhaps I have enough information. Take care.}

{135}{}{Hm, listen, Festus. If she hadn't been beaten, tortured and she didn't call for help, then it's not considered rape. It's a... An innocent teenagers' stuff. I'm talking from experience.}
{136}{}{WHAT!? Whatever you call this, but I'll do everythin' so this Derren came out of his dig and married my beautiful Christine!!!}

{137}{}{You don't mind another couple of questions?}

{138}{}{Wait a second, so, she hadn't been beaten, she didn't call for help and even asked his name and rank?}
{139}{}{Well... That's right... Doesn't matter!!! I'll do everythin' so this Derren came out of his dig and married my beautiful Christine!!!}

{140}{}{Festus, I think, you and your daughter should get out of here, as far away as you can.}
{141}{}{Why?!}
{142}{}{Just a feeling. Better answer a couple of questions.}
{143}{}{Well, eh, Derren set up the whole garrison against you. Even general Wesker is in. They'll stand for each other, rest assured.}
{144}{}{Because otherwise I'll end you right here.}
{145}{}{Because I'll call my friends from the garrison, and they'll beat you up real hard.}

{146}{}{Ugh, you're right... Nothin' will come out. How can we deal with them? And even the caravaneers won't be of help, if the military shows up. We'll have to go back to the village.}
{147}{}{Happy trails.}
{148}{}{That's nothin', son! I'll show 'em! I've got powder fer everyone!}
{149}{}{In that case I'll end you right here.}
{150}{}{Well, I'm here to warn you, next time you're on your own.}
{151}{}{You know so much about all these militaries for a reason! What a scum you are! And your skin is so white, like yer hands never dig into the ground. Alright-alright, I get ye. We won't test our luck anymore, we'll go back to the village. But If I only get you on my way! Come on, Christine, we'll find you a man somewhere else.}
{152}{}{You just stop this! I won't go anywhere until I make Derren marry my Christine! I WON'T LEAVE!}
{153}{}{Then you're askin' for it. So long, old fella. [attack]}

#Female character
{1116}{}{Straight to business - I like that! We'll get along well, girl. Just keep your powder dry, as I always say, heh-heh!..}
{1148}{}{That's nothin', girlie! I'll show 'em! I've got powder fer everyone!}