{100}{}{You see a traveler.}
{101}{}{You see a spy.}
{102}{}{You see an ordinary looking traveler. It is difficult to suspect him in being a spy or something like it.}

{104}{}{I've already paid you. There is nothing else to talk about.}

{110}{}{Looking for something, wanderer?}
{111}{}{Yes. Have any bikers passed by?}
{112}{}{So you have a trained eye for recognizing my kind?}
{113}{}{I wonder, what are *you* doing here?}
{114}{}{Bye.}

{115}{}{Bikers? I've heard of them, but I haven't seen them in person. If the rumors are to be believed, these guys would be especially out of place here. I don't think that the local military men would be friendly to marauders.}
{116}{}{Marauders?}
{117}{}{Well, I heard that bikers looted most of their gear and cool weapons from military bases. Which sounds quite logical. Except that the locals aren't likely to look on with indifference. They feel that all the property of the military bases should belong to them by birthright. After all, their ancestors came from these places.}
{118}{}{I see you know the history of the local population very well. How so?}
{119}{}{Well... Rumors slip in little by little from different places. It doesn't matter.}
{120}{}{I don't think you're here just for the sake of rumors.}
{121}{}{I needed a place to sleep. I'm just a traveler, nothing special.}
{122}{}{Huh. Usually no one leaves their homes without a good reason. Believe me, I know.}
{123}{}{Heh. True. I have my reasons... But I'd still like to know what a person like you is doing in this troubled place?}
{124}{}{Well, not that... You know, you don't look particularly distrustful. I think it would be possible to do joint business with you.}
{125}{}{My interests in this place are purely temporary. My goal is located somewhere far away from here. I don't even know where.}
{126}{}{Business? Like what?}
{127}{}{Oh, a fellow wastelander? This is interesting... You know, you don't look particularly distrustful. I think it would be possible to do joint business with you.}

{128}{}{Don't be in a rush, I want to know more about you. What can you say about this place?}
{129}{}{A lousy dump with lousy residents. I wouldn't linger here for long.}
{130}{}{Something tells me that somewhere deep down inside they have a noble goal. But perhaps time and conditions are working against them.}
{131}{}{Hey, I'm not going to gossip with you! Let's finish this.}

{132}{}{Then I'll ask maybe a strange question. Tell me: Stealing from a thief - is it fair?}
{133}{}{I don't care whose pockets get picked. I don't ask them.}
{134}{}{But don't the residents of Wind of War offer their patronage and protection in exchange for resources? Then they're not thieves.}
{135}{}{Theft is a rotten business. You can cover it up, but it still stinks.}
{136}{}{Let's get this over with. I see you have a grudge against the residents of this place. Make it simple, what do you need?}
{137}{}{Look, I don't want to know what you're up to. Let's end this conversation.}

{138}{}{You look like a man with the necessary qualities.}
{139}{}{Heh, say what you want, but you can't hide your true nature. I'm afraid I was wrong about you. Good luck, wanderer.}
{140}{}{I'm sick of your attitude! I don't care about your ambitions, I'm only interested in personal gain. Tell me what you need and how much you'll pay for it - and I'm in.}
{141}{}{Hey, easy! However... There's some truth in your words. After all, who else needs my ambitions, but me?}
{142}{}{Exactly.}

{143}{}{Actually, I'm interested in something. If you help me to get it, I'll pay you 500 bucks.}
{144}{}{A tempting offer.}
{145}{}{I need a list of the common radio frequencies used by the patrols. This information should be in the computer used by the radio operators at headquarters. But I can't get to it. Can you?}
{146}{}{Whoa, wait a second! Why would an ordinary traveler want to wiretap the patrols? There's something you're not telling me.}
{147}{}{I'll do it. But for 1000 bucks.}
{148}{}{Okay, I accept the task.}
{149}{}{You're crazy! I won't take this task even for five thousand!}
{150}{}{Does it really matter to you? If I were you, I wouldn't care... Yes, you guessed right, I am a mercenary myself. But don't ask me about the client - I don't know anything about him anyway. We'll just split the fee, that's all. That doesn't mean I have no ambition, though.}
{151}{}{You can raise the price all you want, I have no more money to offer.}
{152}{}{What other interests do you pursue, besides greed?}
{153}{}{I HATE this town! I once lived in a small settlement not far from here. The military offered their protection in exchange for resources. But when the slavers came, a group of "protectors" turned out to be too far to help. Since then, I just want to get some revenge on these bastards.}
{154}{}{Uh... It leaves me almost with nothing, but this is too tempting. Okay, I'll pay 1000, just do it quietly.}
{155}{}{That means I was wrong about you. But believe me, you can't make such easy money somewhere else around here.}
{156}{}{Very well. I will repeat our plan just in case. You need to get to the computer room at headquarters. Which in itself is not a difficult task - the radio operators are busy with their own business and almost never get distracted, and the computer room is rumored to be often empty. The problem is how to access the information without giving yourself away. That's where your skills and wit come in.}
{157}{}{Okay, I'll be back when it's done.}
{158}{}{Yeah, and don't you dare get caught! If anything happens - I had nothing to do with it. I'm just a passing wanderer who asked for a bed, got it?}
{159}{}{Okay.}

#After receiving the quest
{160}{}{So, how are you doing, wanderer?}
{161}{}{Not bad...}
{162}{}{Don't be silly, you know what I mean!}
{163}{}{Uh, it hasn't been done yet. Wait for a little longer.}
{164}{}{I have the information you need.}
{165}{}{Wait, I'll compare it with what I managed to get before you.. Right... Hmm... It seems that this is exactly what I needed. Well, just as I promised, here's your money. Thank you for your assistance, without you I'd be stuck here for another week.}
{166}{}{Bye.}

#Women's replies
{1110}{}{Looking for something, wanderer? Never mind, I was just asking.}
{1127}{}{Oh, a fellow wastelander? This is interesting... You know, you don't look particularly distrustful. I think it would be possible to do joint business with you.}
{1139}{}{Heh, say what you want, but you can't hide your true nature. I'm afraid I was wrong about you. Good luck, wanderer.}
{1160}{}{So, how are you doing, wanderer?}
