{100}{}{You see a traveler.}
{101}{}{You see a spy.}
{102}{}{You see an ordinary looking traveler. It is difficult to suspect him in being a spy or something like it.}

{104}{}{I've already paid you. And there is nothing to talk about.}

{110}{}{Looking for something, wanderer? Never mind, I was just asking.}
{111}{}{Yes. Were there any bikers passing by?}
{112}{}{So you have a trained eye on recognizing my kind?}
{113}{}{I wonder what are *you* doing here?}
{114}{}{Bye.}

{115}{}{Bikers? I've heard about them, but have not seen them personally. If you believe the rumors, these guys would be especially out of place here. I don't think that the local military men would be friendly to marauders.}
{116}{}{Marauders?}
{117}{}{Well, I heard that the bikers looted most of their gear and cool guns from military bases. Which is quite logical. Only it is unlikely, that local people will look at it with indifference. They think that all the property of military bases should belong to them by the birthright. Because their ancestors were from these places.}
{118}{}{I see you know the history of the local population. Where such awareness comes from?}
{119}{}{Well... Rumors slip by little from different places. Nevermind.}
{120}{}{I don't think you're here just for the sake of rumors.}
{121}{}{I needed a place to sleep. I'm just a traveler, nothing special.}
{122}{}{Well, well. Usually no one leaves their homes for no reason. I know it well, believe me.}
{123}{}{Heh. True. I have my reasons... But I'd still like to know what a person like you is doing in this troubled place?}
{124}{}{Well, not that... You know, you don't cause any special mistrust. It would be possible to do joint business with you.}
{125}{}{My interests to this place are solely temporary. My goal is located somewhere far away from here. I don't even know where.}
{126}{}{Business? Like what?}
{127}{}{Oh, brother-in-the-Wasteland? This is encouraging... You know, you do not cause any special mistrust. It would be possible to do joint business with you.}

{128}{}{Don't rush, I want to know more about you. What can you say about this place?}
{129}{}{The lousy dump with lousy residents. I wouldn't linger here for long.}
{130}{}{Something tells me that they have a noble goal, somewhere inside. But perhaps now the time is working against them.}
{131}{}{Hey, I'm not going to gossip with you! Let's finish this.}

{132}{}{Then I'll ask maybe a strange question. But tell me: stealing from the thief - is that a fair act?}
{133}{}{I don't care whose pockets get cleaned out. I don't ask them.}
{134}{}{But don't the residents of the Wind of War offer their patronage and protection in exchange for resources? Then they're not thieves.}
{135}{}{Theft is a rotten business. You can cover it up, but it still stinks.}
{136}{}{Finish up this haggle. I see you have a grudge against the residents of the Wind. Make it simple, just say what do you need?}
{137}{}{Look, I don't want to know what you're up to. Let's end this conversation right now.}

{138}{}{You look like a man with the necessary qualities.}
{139}{}{Heh, say what you want, but you can't hide your true nature. I'm afraid I was wrong. Good luck, wanderer.}
{140}{}{You bored me with your attitude! I don't care about your ambitions, I'm only interested in personal gain. Tell me what you need and how much you will pay for it - then I'm in.}
{141}{}{Oh, take it easy! However... There's truth in your words. After all, who else but me needs my ambitions?}
{142}{}{Exactly.}

{143}{}{Actually, I'm interested in something. If you help me to get it, I'll pay you 500 bucks.}
{144}{}{A tempting offer.}
{145}{}{I need a list of regular radio frequencies used by patrols. This information should be in the computer that stands by the radio-operators in the headquarters. But I am not able to approach it. Maybe you can do that?}
{146}{}{Whoa, stop right here! Why would the ordinary traveler want to wiretap patrols? There's something you're not telling me.}
{147}{}{I'll do it. But for 1000 bucks.}
{148}{}{Okay, I accept the task.}
{149}{}{You're crazy! I won't take this task even for five thousand!}
{150}{}{Does it really matter to you? As for me, I don't care why that cuss would need them. Yes, you've guessed correctly, I'm a mercenary myself. But don't ask me about the customer - I still know nothing about him. We'll just split the fee, that's all. Although this does not mean that I have no ambitions.}
{151}{}{You can raise the price all you want, but I have no more money to offer.}
{152}{}{Which other interests you pursue, besides greed?}
{153}{}{I HATE this town! I once lived in a small settlement not far from here. The military offered protection in exchange for resources. But when the slavers came, a group of "protectors" turned out to be too far to help. Since then, I just want to spite these bastards.}
{154}{}{Uh... Almost nothing left for me, but this thing is too tempting. Okay, I'll pay 1000, just do it quietly.}
{155}{}{That means that I was wrong about you. But trust me, you won't coin money here easily.}
{156}{}{Very well. I repeat our plan just in case. You need to get into the room with the computer in the headquarters. That the task itself is not difficult - radio operators are busy with their estimates and almost never get distracted, and the room with the computer is often empty. The problem is how to access information not giving yourself away. This is where your skills and wit come in handy.}
{157}{}{Okay, I'll be back when it's done.}
{158}{}{Yeah, and don't you get caught doing it! If anything happens - I have nothing to do with it. I'm just a wanderer who just passed by and asked for a bed, get it?}
{159}{}{Okay.}

#After receiving the quest
{160}{}{So, how are you doing, wanderer?}
{161}{}{Not bad...}
{162}{}{Don't be silly, you know what I mean!}
{163}{}{Uh, it hasn't been done yet. Wait a little longer.}
{164}{}{The information is with me.}
{165}{}{Wait, I'll compare it with what I managed to get before you.. Right... Hmm... It seems that this is what was needed. Well, as promised - here's your money. Thank you for your assistance, without you I'd be stuck here for another week.}
{166}{}{Bye.}

#Women's replics
{1110}{}{Looking for something, wanderer? Never mind, I was just asking.}
{1127}{}{Oh, sister-in-the-Wasteland? This is encouraging... You know, you do not cause any special mistrust. It would be possible to do joint business with you.}
{1139}{}{Heh, say what you want, but you can't hide your true nature. I'm afraid I was wrong. Good luck, wanderer.}
{1160}{}{So, how are you doing, wanderer?}
