{100}{}{You see a general.}
{101}{}{Attention! It's General Wesker!}

###################################################################
#
#  Common starting cues
#
###################################################################

{110}{}{Civilian?! What do you want?}
{111}{}{Report!}
{112}{}{I'm going, sir.}
{113}{}{I have a complaint about your subordinates.}
{114}{}{I need to discuss an important question with you.}
{115}{}{Do you have a job for me?}
{116}{}{I'm listening.}
{117}{}{Nevermind.}

###################################################################
#
#  Hawthorne Quest
#
###################################################################

{118}{}{Don't rush your decision. Think about it, my skills and knowledge of the outside world could be useful.}
{119}{}{Who do you call a greenhorn?! Many of your soldiers could learn a lot from my survival skills.}
{120}{}{I don't have any jobs for a greenhorn. Grow up and we'll talk.}
{121}{}{Let me ask another question then.}
{122}{}{Too bad.}
{123}{}{Hm... There's one assignment. I don't think it'll be too hard for you.}
{124}{}{I'm listening.}
{125}{}{I need a smart person who is capable of getting into Hawthorne Base and bringing some things back. Interested?}
{126}{}{Yes! Tell me the details.}
{127}{}{Depends on my risks. How dangerous is it?}
{128}{}{I don't engage myself in such matters. Hire someone else.}

{129}{}{If you don't want to risk - I don't need you. Get out.}
{130}{}{Uh, okay...}
{131}{}{Hawthorne? I've never heard of it. What is it?}
{132}{}{An abandoned military base, not far to the west of New Reno. I'll tell the details if we cooperate. Are you interested in this job?}
{133}{}{Then I have to explain the situation. We are descendants of people who served at Hawthorne more than 70 years ago. Those who knew the secret of our lineage are already worm food. But that's beside the point...}
{134}{}{Okay...}

{135}{}{There should still be some commemorative evidence of our ancestors - personal belongings, information in databases, something like that. Collect everything you find and bring it here for a reward. Got any questions?}
{136}{}{Yes, I need to know something before I go.}
{137}{}{No more questions, sir.}

{138}{}{Good. I'll be waiting for the good news then. And here's some advice. Hawthorne is still protected by an active automated defense system. Be careful when you enter the garrison territory. Another problem are the raiders which you can sometimes encounter in the vicinity of the base. These are not petty criminals, they carry far better equipment. That's all. Good luck.}
{139}{}{[Leave]}

{140}{}{Why don't you give this assignment to your people?}
{141}{}{Firstly, I don't want to risk my people. It's easier for me to hire a scavenger. Secondly, I need my men here to carry out their duties, and assembling an expedition under these conditions is rather troublesome. Finally, not all of my people can be trusted with this matter. I need... A person with a slightly different mindset.}
{142}{}{This is all sounds like ancient history. What do you need from this base?}
{143}{}{I expect that some evidence of the former merits of our ancestors will help lift the spirits of our soldiers. It all depends on what you find.}
{144}{}{If your ancestors are from Hawthorne, why are you here and not at the base?}
{145}{}{I have the same question. They didn't live in the garrison after the Great War, they hid in a nearby vault. Perhaps, Hawthorne was the target of nuclear bombs, so staying there would be dangerous. We also couldn't return to the base for a number of reasons. Dilapidated buildings, mal-functioning security system, matters of our current settlement and many more reasons.}
{146}{}{What do I get for this?}
{147}{}{I pay in cash. My word is cast in iron, just like me. You can trust the integrity of our deal.}
{148}{}{Okay, what exactly?}
{149}{}{}

{150}{}{About the task in Hawthorne.}
{151}{}{Report, I'm listening.}
{152}{}{Nothing much, just wanted to clarify something.}
{153}{}{Still nothing to report.}

{154}{}{I was able to find a pre-war full dress uniform in Hawthorne.}
{155}{}{I was able to find information about your ancestors, a group of deserters who had settled in this place.}

{156}{}{I've never seen anything like it! If I show up in this uniform at the next flag raising, I will have the desired effect on my men. This is what I was talking about! Keep it up, private! Uh... I mean, good job, civilian!}
{157}{}{Then my part of assignment is done. What about the payment?}
{158}{}{Deserters? Damn it... I thought that our old men were hiding something from us, but this... This information should not leak out - neither to the ranks nor to common people. It seems that there is nothing left in the remains of Hawthorne for us. We'll have to sort this out on our own.}

{159}{}{You didn't disappoint, maybe we'll make a real soldier out of you. *chuckles* Here's your money.}
{160}{}{Great.}
{161}{}{What can be done to boost the spirit of your soldiers?}

###################################################################
#
#  The "Speed hawk" Case
#
###################################################################

{180}{}{Did you know that some of your subordinates attacked one of the Vegas caravans?}

{181}{}{I've heard the rumors. I wonder who is spreading this misinformation and why.}
{182}{}{Misinformation? So you straight out deny that possibility? I happened to have a chance to visit the site of the attack and found a personal tag from one of your soldiers. What do you say to that?}
{183}{}{[Pauses] I should have known. My men are not the same as before.}
{184}{}{What does it mean? I thought Wind of War is known as a defender of the offended and helpless...}
{185}{}{It is. But its hard work keeping order in our region. And sometimes the guys need to let off some steam. Apparently, they smelled easy money and succumbed to temptation.}
{186}{}{It's not the first time, right? Does it mean that your men are gradually turning into raiders?}
{187}{}{I have to admit that this is partly true. I try to restrain them, put worthy ideas in their heads, give them something to look up to, but the level of motivation and discipline keeps dropping. This problem didn't start yesterday.}
{188}{}{Right. So what about the stolen goods?}
{189}{}{Let me see what I can do about that.}
{190}{}{I'll wait...}
{191}{}{The boys cracked and showed me the stash. Here, that's all they had in it, $1,500 and some sort of technical device.}
{192}{}{Well, at least it's something. What are do you going to do with these creeps?}
{193}{}{Those who committed the robbery will have to answer... Doing hard labor. That will be a good lesson for the others.}
{194}{}{It is good that at least criminals will be punished.}
{195}{}{Okay, that's your business.}

###################################################################
#
#  Complain about subordinates
#
###################################################################

{200}{}{You are not an exception.}
{201}{}{However... Looking like you want to beat me up any second, I don't really feel like complaining anymore... [leave]}
{202}{}{Enough of this! Let's see how you think about things tomorrow. Throw him in the cell!}
{203}{}{No! Let me go! Not a prison!}
{204}{}{Oh, well then, that explains a lot of things. Thanks for the warning, goodbye.}

###################################################################
#
#  About Alcohol
#
###################################################################

{210}{}{Do you allow your guys to drink alcohol?}

{211}{}{It is strictly forbidden. Those who violate the order will face correctional labor.}
{212}{}{So you have to know this then: Your Quartermaster at the station bought a whole case of alcohol from me! Can you imagine that?}
{213}{}{A case of alcohol? I'll go and check that out immediately. But if he doesn't have it... You know what I do with false informants?}
{214}{}{He had the stock. He tried to explain that it was for resale to caravaneers, but I didn't buy his crap. He is punished by couple of days of hard labor. Thank you for your help, we'll take it from here.}
{215}{}{Yeah, you're welcome. I didn't do it for personal gain you know, but, for the sake of justice, so to speak... See you, general.}
{216}{}{That will not do, because he had enough time to dispose of his stock. I don't think I will risk that.}
{217}{}{So be it. I know that the truth is on my side.}
{218}{}{Ahem... Ahem!}
{219}{}{What? Ah yes, it's fair to pay for the information, otherwise you may not give me good info in the future. Here's $100.}

###################################################################
#
#  Military Muggers
#
###################################################################

{220}{}{Two of your privates attacked and wanted to rob me!}

{221}{}{How interesting. I want to hear the details.}
{222}{}{So, it started like this...}
{223}{}{I... Apologize on behalf of the general staff of the Wind of War. Is that enough for you?}
{224}{}{Well... NOPE! You think I'm an idiot!? On your knees! ON YOUR KNEES I SAY!}
{225}{}{Chief, tell me... You are keeping a blind eye to the faults of your people, aren't you?}
{226}{}{An apology is enough. It's not every day you get to hear them from such important people.}
{227}{}{This answer does not satisfy me, but I'll have to settle for it. Bye.}
{228}{}{Exactly. It's a hard time for everyone. I need to deal with it.}
{229}{}{See? Your own behavior is the reason. Even if the guys were just trying to blow off steam, you still don't deserve to be treated any better.}
{230}{}{Actually, you're wrong. I've never laid a finger on anyone before these guys. And now two of them... Uh... It's hard to take.}
{231}{}{You are greatly mistaken about me. But I prefer not to talk about myself too much, to avoid feelings of arrogance.}
{232}{}{Yeah-yeah. More bullshit.}
{233}{}{Well, I guess I do need to [lowers his voice and speaks through clenched teeth] apologize... The wastelanders don't usually deserve to be treated well. They act like a bunch of cattle. Maybe I really was wrong about you. Or maybe I wasn't, it's not for me to judge. But what my boys did was wrong, so for that I apologize..}
{234}{}{Oh, those words seem sincere. I accept your apology.}

###################################################################
#
#  About Drugs
#
###################################################################

{240}{}{I know that your physician brews some shit for visitors.}
{241}{}{I had a suspicion that he is involved in some shady business. We'll check it. You just wait here. If I find out that you misinformed me... Well, you'll see that I'm going to do.}
{242}{}{Um, seems like I have no choice...}
{243}{}{We caught that snake! Ha! Now the boys will calm down. We're going to destroy the lab for show. Here, in Wind of War, we don't tolerate drugs. I offer you my official thanks for providing the information, although I don't like the spirit of this discovery. You are free to go.}
{244}{}{That's it? I don't get anything? What a bummer.}

###################################################################
#
#  Assaulters in Vegas
#
###################################################################

{250}{}{Your technician hired assassins to kill me! But they should have thought twice before choosing the wrong target.}

{251}{}{What? A poor technician ordered an assassination of a wanderer? If that's some kind of joke, you will go to jail.}
{252}{}{You wish! Your technician is not poor anymore. He's richer than the owner of "Three-card Monte"!}
{253}{}{If one considers that the local mafia... Wait! Is that a hint?}
{254}{}{No. I bought the pickup from him for a heap of money. A great car, among other things.}
{255}{}{A pickup? The one from the garage? He told me he couldn't fix it.}
{256}{}{He couldn't, until I helped him. The purchase was fair, but when I arrived in Vegas, two grunts with assault rifles were waiting for me there.}
{257}{}{Are you stupid? Every single street punk would want to cut your throat for that pickup. Why the hell did you decide that it's our technician who sent "killers" after you?}
{258}{}{I have a proof. [Show the note from the killer's corpse]}
{259}{}{Well... Who else could do this?!}
{260}{}{Civilian, if you are still *able* to use you brain, remember what I said a minute ago. And if you'll continue... You will be sent to jail for slander. Is that clear?}
{261}{}{Clear. I'll try to find proof.}
{262}{}{Dammit... That's very bad.}
{263}{}{What, feel ashamed? How do you keep an eye on your men if they do such things?!}
{264}{}{Don't be so conceited. You're right, the boys got out of hand. I'm trying to deal with this problem, but so far there are no visible results.}
{265}{}{And what will you do about the technician?}
{266}{}{Grrm... I will put him for questioning, issue a warning, make him labor his ass off... And for you - just a bit of advice: to stay away from his shop.}
{267}{}{Isn't that too light a punishment?}
{268}{}{I'm afraid I cannot lose someone so useful for the whole settlement. He maintains the automation and power supply, he repairs weapons, makes ammo... Without him, our settlement would go to hell soon. A replacement will be very difficult to find. And you... Your problem has been solved, isn't it? So you have nothing to worry about.}
{269}{}{What a hell of a disappointment... But as I won't get anything with you, I'll go on about my business.}

###################################################################
#
#  About the beaten up Caravaneer
#
###################################################################

{270}{}{I demand justice! Two of your privates beat up a caravaneer.}

{271}{}{That is correct. We have to maintain the law, sometimes by force. All to keep order.}
{272}{}{But he didn't do anything! They just beat him up for no reason!}
{273}{}{That's what everyone says. And usually it's a lie. How do I know that the caravaneer is innocent?}
{274}{}{They took away his gun and money. Their goals were clear. In the wasteland it's called a "robbery".}
{275}{}{Hmm... We can shake the guys, but if they don't have the gun, *you* will go to jail for insulting my soldiers!}
{276}{}{You know, it's not even my problem, which means it's also not my responsibility. So long.}
{277}{}{That's fair, let's do it your way. If I'm lying, then I'll go to jail.}
{278}{}{The boys cracked and returned the loot. Here's the gun and $200. But we're not going to apologize.}
{279}{}{Why so?!}
{280}{}{Think. Try to imagine the reaction of the caravaneers when we'll show up again after what happened.}
{281}{}{Hmm, right, that could lead to a conflict.}
{282}{}{So I ask *you* to convey the money and weapon, along with our apologies.}
{283}{}{Well, in that case...}
{284}{}{So, that's it, the guy was still armed? A shady business, huh?}
{285}{}{Um, actually... Now I understand why you are avoiding any proceedings. Maybe I can convince you in the future. Or not. Let's talk about it later.}

###################################################################
#
#  Spy
#
###################################################################

{290}{}{Did you know someone at the station is involved in espionage?}

{291}{}{Is that so?}
{292}{}{He has asked me to copy the data on the patrol radio frequencies. I hope this information would be useful.}
{293}{}{This information would help us a lot... But you have to play along so that we can be sure that you are not lying.}
{294}{}{Err... Of course...}
{295}{}{Thank you for your help. My people will appreciate what you did, but don't think too much of it.}
{296}{}{Very well, but what was this guy shouting when you tied him up? Something about revenge for his brothers...}
{297}{}{Certainly, no problem.}
{298}{}{I don't know what exactly my men did to offend him, but there were occasions when our troops were unable to protect the settlements from aggressors. Some fell victim to raiders, others were captured by slavers. We must take care of the whole region, we cannot save everyone! It takes too many resources and manpower to maintain outposts and organize patrols.}
{299}{}{So, you did all you could? Well, in any case, it will remain on your conscience. Goodbye.}

###################################################################
#
#  I need to discuss with you an important question
#
###################################################################

#Bomb
{300}{}{}
{301}{}{}
{302}{}{Deal.}
{303}{}{My answer is NO!}
{304}{}{Lift!}
{305}{}{Sorry, sir! Yes, sir!}

#Heavy munitions
{306}{}{I can sell you heavy machine gun ammunition from Hawthorne.}
{307}{}{That is our caliber! These bullets were meant for heavy machine guns from a small speedboat fleet. We got a couple of them dragged from Hawthorne a few years ago. Now we can load them. An excellent find! I will buy a box for $750.}

#Pistol
{308}{}{I managed to find an ceremonial gun in Hawthorne. It looks impressive...}
{309}{}{Well, let's take a look... Wait, that's the personal sidearm of my ancestor! The man who saved our people during the Great War. And here I am holding in my hands a piece of his past, a testimony of long-forgotten deeds. I will buy this weapon for $1,000.}

#Selling Nuka
{320}{}{I am an official representative from Salt Lake City's Nuka-Cola factory and I have a mutually beneficial offer for you.}
{321}{}{We have a quartermaster at the entrance. You should resolve such questions with him.}
{322}{}{A trader in the old station? Okay, I'll talk to him.}
{323}{}{He said he wouldn't commit to such deals without your permission.}
{324}{}{And he did the right thing. Where is the guarantee that you are who you claim to be? How can we trust you?}
{325}{}{In that case, my license might convince you.}
{326}{}{You're not very welcoming to a rare trade partners. Well, your loss...}
{327}{}{...And no one knows where you got it. Prove that you can be trusted. As for paper, there are better uses for it in the toilet.}
{328}{}{Hmm, you don't look like a charlatan. At least your actions say otherwise. I think we'll give you a chance. I will contact the quartermaster by the radio. You go and talk to him about the details of the deal.}
{329}{}{Yes, sir!}
{330}{}{Wait, let me explain it for you using numbers and charts...}
{331}{}{[listens carefully and looks interested] Hmm, talented traders are rare these days. I don't want to miss out on a profitable partner, whoever that may be... I think we'll give you a chance. I'll contact the quartermaster by the radio, and you go and talk to him about the details of the deal.}

###################################################################
#
#  About the Rednecks
#
###################################################################

{400}{}{Wait a minute. I have another request, if you do not mind.}
{401}{}{Yes?}
{402}{}{I got reports about a couple of rednecks making some fuss at the checkpoint. But the reports have some issues, so I could use your help to clarify the situation.}
{403}{}{I will be glad to help you. What should I do?}
{404}{}{You know, scavengers like me don't know the word "help". Goodbye.}
{405}{}{I would be glad to help, but I've got to leave this place, too much trouble here. You will have to sort things out without me.}

{406}{}{Talk to the guards at the checkpoint, then go down to the station and find the rednecks who stirred things up. Talk to them, get their version of the incident. They will be more willing to talk to you than to the military from the garrison.}
{407}{}{Sounds easy.}
{408}{}{I look forward to the report. The guards will help you.}
{409}{}{[Leave]}

{410}{}{Regarding the incident at the checkpoint.}
{411}{}{So, what's the story?}
{412}{}{Funny, really. It turns out that Private Derren had intercourse with the villager's daughter during tax collection. The father came here for justice, but was denied entry.}
{413}{}{I can't say for sure. These rednecks went back to the village, and the guards have no more problems with them.}
{414}{}{I'm afraid it's impossible to figure out. Because there was a commotion among the newcomers at the station And the rednecks happened to be in the line of fire.}
{415}{}{I still haven't been able to find out the details. I'll come back when I know something.}
{416}{}{Okay, I believe you. In any case, I am glad that I wasn't disappointed in my men once again.}
{417}{}{Yes, that's alright.}
{418}{}{Private Derren is a good guy. It's strange that he got himself into such situation. However, it can be easily understood, since very few women live in the garrison. If he had a "crush" on the village girl, it's not a bad thing. Tell me, is she still at the station?}
{419}{}{I'm afraid not.}
{420}{}{Yes, she is still there with her dad.}
{421}{}{Too bad. I could have given him and the others an exemplary hearing as a lesson. But I will have to confine myself to an explanatory talk. Thank you for your intelligence on the matter.}
{422}{}{You're welcome.}
{423}{}{Perhaps the old man hoped he could send his daughter to the garrison. I don't think my people would be happy about that. But that's exactly what I need! I will make Derren marry her and take the girl to live with him. It will set an example to others and should make the soldiers treat the inhabitants of the wasteland better. Thank you for your help.}
{424}{}{Take the 100 bucks for what I made you run around. Don't hurry to leave, your continued assistance in external relations would be very useful.}
{425}{}{What do you need me to do?}
{426}{}{Thank you, but I must continue my journey. I can't stay here for long. Goodbye.}
{427}{}{We have problems with the meat supply from one of the farmers. There is a reason to believe that farmer just doesn't trust us. It can be understood, given the reputation of the garrison. We need your help to restore confidence in us and re-establish contact with the farmer. Speak to the quartermaster if you decide to take the job.}
{428}{}{I'll talk to him.}
{429}{}{Take the 100 bucks for making you run around. Sorry to see you leave, your assistance would be useful in external relations. But so far I have no more assignment for you. Farewell.}

###################################################################
#
#   вест по зачистке убежища
#
###################################################################
{500}{}{It has become known to me that the nearby vault is crawling with mutants. I could deal with that.}
{501}{}{Hmm. So, our operators are chitchatting again... Although, such situation is indeed the reason of our concern. I wouldn't take risks of dispatching my people, but if you know the location and willing to do everything by yourself - you're welcome to try. Report to me if it's done.}
{502}{}{I had a change of plans. It's your mess to deal with.}
{503}{}{Good, I'll come by later.}
{504}{}{The mutants are all dead. They won't be a problem anymore.}
{505}{}{Our patrols are already confirmed that. Now we could fix the place up and find some usage for it... Oh, and here's your reward [hands you $2000].}
{506}{}{Glad to help.}
{507}{}{You could not be so cheap at least for once...}
###################################################################
#
#  Female 
#
###################################################################

{1202}{}{Enough of this! Let's see how you think about things tomorrow. Throw her in the cell!}
{1230}{}{Actually, you're wrong. I've never laid a finger on anyone before these guys. And now two of them... Uh... It's hard to take.}
{1251}{}{What? A poor technician ordered an assassination of a wanderer? If that's some kind of joke, you will go to jail.}
{1254}{}{No. I bought the pickup from him for a heap of money. A great car, among other things.}
{1256}{}{He couldn't, until I helped him. The purchase was fair, but when I arrived in Vegas, two grunts with assault rifles were waiting for me there.}
{1257}{}{Are you stupid? Every single street punk will want to cut your throat for that pickup. Why the fuck you decided that it's our technician who sent "killers" after you?}
{1260}{}{Civilian, if you are still *able* to use you brain, remember what I said a minute ago. And if you continue... You will be sent to jail for slander. Is that clear?}
{1324}{}{And he did the right thing. Where is the guarantee that you are who you claim to be? How can we trust you?}
{1403}{}{I will be glad to help you. What should I do?}
{1405}{}{I would be glad to help, but I've got to leave this place, too much testosterone in the air. You will have to sort things out without me.}

{5004}{}{The mutants are all dead. They won't be a problem anymore.}
{5006}{}{Glad to help.}
