{100}{}{You see a general.}
{101}{}{Attention! It's General Wesker!}

###################################################################
#
#  Common starting cues
#
###################################################################

{110}{}{Civilian?! What do you want?}
{111}{}{Report!}
{112}{}{I'm going, sir.}
{113}{}{I have a complaint about your subordinates.}
{114}{}{I need to discuss an important question with you.}
{115}{}{Do you have a job for me?}
{116}{}{I'm listening.}
{117}{}{Nevermind.}

###################################################################
#
#  Hawthorne Quest
#
###################################################################

{118}{}{Don't rush your decision. Think about it, my skills and knowledge of the outside world could be useful.}
{119}{}{Who do you call a greenhorn?! Many of your soldiers could learn a lot from my survival skills.}
{120}{}{I don't have any jobs for a greenhorn. Grow up and then we'll talk.}
{121}{}{Let me ask another question then.}
{122}{}{Too bad.}
{123}{}{Hm... There's one assignment. I don't think it'll be too hard for you.}
{124}{}{I'm listening.}
{125}{}{I need a smart person capable to get in Hawthorne Base and bring some things back from there. Interested?}
{126}{}{Yes! Tell me the details.}
{127}{}{Well, it depends on my risks. How dangerous it is?}
{128}{}{I don't engage myself in such matters. Hire someone else.}

{129}{}{Well, if you don't want to risk - I don't need you. Get out.}
{130}{}{Well okay...}
{131}{}{Hawthorne? I don't know such place. What kind of base is it?}
{132}{}{An abandoned military base, not far to the west of New Reno. I'll tell the details if we cooperate. Still interested in this job?}
{133}{}{Then I have to explain the situation. We are descendants of those who served in Hawthorne more than 70 years ago. Those who knew the secret of our lineage are already feeding the worms. But that's beside the point...}
{134}{}{So...}

{135}{}{There should still be some commemorative evidence of our ancestors left - personal belongings, information in databases, something like that. Collect everything you find and bring it here for a reward. Got any questions?}
{136}{}{Yes, I need to know something before I go.}
{137}{}{No more questions, sir.}

{138}{}{Good. I am waiting for good news then. And here's some advice. Hawthorne is still protected by an active automated defense system. Be careful when you enter the garrison territory. Another problem are the raiders which are sometimes found in the vicinity of Hawthorne. These are not ordinary criminals, they carry far better equipment. That's all. Good luck.}
{139}{}{[Leave]}

{140}{}{Why don't you give this assignment to some of your people?}
{141}{}{For starters I don't want to risk my people, it's far simpler for me to hire a scavenger. Secondly they're busy and gathering an expedition is quite troublesome. Finally, not all my people can be trusted with this matter. I need... A person with a slightly different mindset.}
{142}{}{It's all old history. Why do you need it?}
{143}{}{I expect that some evidence of bygone merits of our ancestors will help lift the spirits of our soldiers. It all depends on what you find.}
{144}{}{If you ancestors came from Hawthorne, then why are you here and not at the base?}
{145}{}{I have the same question. They didn't live in the garrison after the Great War, they hid in a nearby vault. Perhaps, Hawthorne were to become the target of nuclear bombs, so staying there would be dangerous. We also couldn't return on base for a number of reasons. Crumbling buildings, working security system, matters of our current settlement and many other ones.}
{146}{}{What I'll get for this?}
{147}{}{I'll pay cash. Like me, my word is cast in iron. You can trust the integrity of our deal.}
{148}{}{Okay, what exactly?}
{149}{}{}

{150}{}{About the task in Hawthorne.}
{151}{}{Report, I'm listening.}
{152}{}{Nothing much, just wanted to clarify something.}
{153}{}{Still nothing to report.}

{154}{}{I was able to find a pre-war full dress uniform in Hawthorne.}
{155}{}{I was able to find information about your ancestors, a group of deserters who had settled in this place.}

{156}{}{Never saw anything like it! If I show up dressed in this uniform on the next flag raising, then I make a desirable effect on my men. This is what I was talking about! Keep it up, private! Uh... I mean, good job, civilian!}
{157}{}{Then my part of assignment is done. What about the payment?}
{158}{}{Deserters? Damn it... I thought that the old men were hiding something from us, but this... This information should not leak into the ranks of ordinary people and privates. It seems that there is nothing in the remains of Hawthorne for us. We'll have to sort this out on our own.}

{159}{}{You didn't disappoint, maybe we'll make a real soldier out of you. *chuckles* Here's your money.}
{160}{}{Great.}
{161}{}{What can be done to boost the spirit of your soldiers?}

###################################################################
#
#  The "Speed hawk" Case
#
###################################################################

{180}{}{Did you know that some of your subordinates attacked one of the Vegas caravans?}

{181}{}{I've heard the rumors. I wonder who is spreading this misinformation and why.}
{182}{}{Misinformation? So you straight out deny that possibility? I happened to had a chance to visit the site of the attack and found a personal tag of one of your soldiers. What do you say to that?}
{183}{}{[Pauses] I should have known. My men are not the same as before.}
{184}{}{What does it mean? I thought Wind of War was known as a defender of the offended and helpless...}
{185}{}{It is. But to keep order in our region is hard work. And sometimes the guys need to let off some steam. Apparently, they smelled some easy money to get and succumbed to temptation.}
{186}{}{It's not the first time, right? So, your men are gradually turning into raiders?}
{187}{}{I have to admit that this is partially true. I try to constrain them, give them more worthy ideas to think of, but the level of motivation and discipline is still falling constantly. This problem appeared not just yesterday.}
{188}{}{Right. So what about the stolen goods?}
{189}{}{Let me see, what I can do about that.}
{190}{}{I'll wait...}
{191}{}{The boys have split and showed me the stash. Here, that's all they have left, $ 1,500 and some sort of technical device.}
{192}{}{Well, at least something survived. What are do you going to do with these creeps?}
{193}{}{Those who committed the robbery will have to answer... Doing hard labor. That will be a good lesson for the others.}
{194}{}{It is good that at least criminals will be punished.}
{195}{}{Okay, that's your business.}

###################################################################
#
#  Complain about subordinates
#
###################################################################

{200}{}{You are not an exception.}
{201}{}{However... Looking like you want to beat me up any second, I don't really feel like complaining anymore... [leave]}
{202}{}{Enough of this! Let's see how you think about things tomorrow. Throw him in the cell!}
{203}{}{No! Let me go! Not in the prison!}
{204}{}{Oh, well then, that explains a lot of things. Thanks for the warning, goodbye.}

###################################################################
#
#  About Alcohol
#
###################################################################

{210}{}{Do you allow your guys to drink alcohol?}

{211}{}{It's strictly forbidden. For those, who violate the order, awaits some corrective labor.}
{212}{}{So you have to know this then: Your Quartermaster at the station bought a whole case of alcohol from me! Can you imagine that?}
{213}{}{A case of alcohol? I'll go right now and check that out. If he doesn't have it... You know what I do with false informers?}
{214}{}{He got the stock. He tried to explain that it is for resale to caravaneers, but I don't buy this crap. He is punished by couple of days of hard labor. Thank you for your help, we'll take it from here.}
{215}{}{Yeah, you're welcome. I didn't do it for personal gain you know, but, for the sake of justice, so to speak... See you, general.}
{216}{}{That will not do, because he could have time to dispose of his stock. I don't think I will risk that.}
{217}{}{So be it. I know that the truth is on my side.}
{218}{}{Ahem... Ahem!}
{219}{}{What? Ah yes, it's fair to pay for the information, otherwise you may not give me good info in the future. Here's $100.}

###################################################################
#
#  Military Muggers
#
###################################################################

{220}{}{Two of your privates attacked and wanted to rob me!}

{221}{}{How interesting. I want to hear the details.}
{222}{}{So, it started like this...}
{223}{}{I... Apologize on behalf of the general staff of the Wind of War. Is that enough for you?}
{224}{}{Well... NOPE! You think I'm an idiot!? On your knees! ON YOUR KNEES I SAY!}
{225}{}{Chief, tell me... You are keepeng a blind eye to the faults of your people, aren't you?}
{226}{}{An apology is enough. Not every day it's possible to hear them from such important people.}
{227}{}{This answer does not satisfy me, but I'll have to settle for it. Bye.}
{228}{}{Exactly. It's a hard time for everyone. I need to deal with it.}
{229}{}{You see? Your own conduct is the reason for it. Even if the guys were trying to let off some steam - you still don't deserve better treatment.}
{230}{}{In fact, you are wrong. I have never touched anyone of them in a lifetime. And then two of them in a row... Ugh... That's hard to bear.}
{231}{}{You are largely mistaken by my account. But I prefer not to talk about myself too much, to prevent a feeling of arrogance.}
{232}{}{Yeah-yeah. Even more bullshit.}
{233}{}{Well, I guess I really need [lowers his voice and says through clenched teeth] to apologize... Usually wastelanders are not worthy of good treatment. They are the same cattle as the rest. Maybe I really made a mistake about you. And maybe not, I'm not to judge. But my guys were doing the wrong thing, so for this - I am sorry.}
{234}{}{Oh, those words seem sincere. I accept your apology.}

###################################################################
#
#  About Drugs
#
###################################################################

{240}{}{I know that your physician brews some shit for visitors.}
{241}{}{I had a suspicion that he had some dark business. Now we'll check it. You just wait here. If I find out that you misinformed me... Well, you'll see that I will do.}
{242}{}{Um, it seems I have no choice...}
{243}{}{We caught that snake! Ha! Now the boys will quiet down. We will destroy the lab as a precedent. Here in Wind of War we do not tolerate drugs. I express to you an official gratitude for providing the information, even though I don't like the spirit of this discovery. You are free to go.}
{244}{}{That's it? I don't get anything? What a bummer.}

###################################################################
#
#  Assaulters in Vegas
#
###################################################################

{250}{}{That technician from railway station hired killers for my assassination! But they needed to think twice before choosing the wrong target.}

{251}{}{What? A poor technician ordered an assassination of a wanderer? If that's some kind of joke, you will go to jail.}
{252}{}{You wish! Your technician is not poor anymore. He's richer than the owner of "Three-card Monte"!}
{253}{}{If one considers that the local mafia... Wait! Is that a hint?}
{254}{}{No. I bought the pickup from him for a heap of money. A great car, among other things.}
{255}{}{Pickup? The one from the garage? He told me he couldn't fix it.}
{256}{}{He couldn't, until I helped him. The purchase was fair, but when I arrived in Vegas, two grunts with assault rifles were waiting for me there.}
{257}{}{Are you stupid? Every single street punk would want to cut your throat for that pickup. Why the hell did you decide that it's our technician who sent "killers" after you?}
{258}{}{I have a proof. [Show a receipt from a killer's corpse]}
{259}{}{Well... Who else might do this?!}
{260}{}{Civilian, if you are still *able* to use you brain, remember what I said a minute ago. And if you'll continue... You will be sent to jail for slander. Is that clear?}
{261}{}{Clear. I'll try to find proof.}
{262}{}{Dammit... That's very bad.}
{263}{}{What, feel ashamed? How do you watch for your men, if they are doing such things?!}
{264}{}{Don't be so conceited. You're right, the boys got out of hand. I'm trying to deal with this problem, but so far there are no visible results.}
{265}{}{And what will do about the technician?}
{266}{}{Grrm... I will put him for questioning, issue a warning, make him labor his ass off... And for you - just a bit of advice: to circumvent his shop.}
{267}{}{Is that not a too lenient punishment?}
{268}{}{I'm afraid I cannot lose a man so useful for the whole settlement. He maintains the automation and power supply, he repairs weapons, makes ammo... Without him, our settlement will go to hell soon, and a replacement will be very difficult to find. And you... Your problem has been solved, isn't it? So you have nothing to worry about.}
{269}{}{What a hell of a disappointment... But as I won't achieve anything with you, I'll go on about my business.}

###################################################################
#
#  About the beaten up Caravaneer
#
###################################################################

{270}{}{I demand justice! Two of your privates beat up a caravaneer.}

{271}{}{That is correct. We have to maintain the law, occasionally - by force. It's all for keeping order.}
{272}{}{But he didn't do anything! They just beat him up for no reason!}
{273}{}{That's what everyone says. And usually it's a lie. How do I know that the caravaneer is innocent?}
{274}{}{They took away his handgun and money. Their goals were clear. In the wasteland it's called "robbery".}
{275}{}{Hmm... We can shake the guys, but if they don't have the gun, *you* will go to jail for insulting my soldiers!}
{276}{}{You know, it's not even my problem, which means also not my responsibility. So long.}
{277}{}{That's fair, let's do it this way. If I'm lying, then I'll go to jail.}
{278}{}{The boys cracked and returned the loot. Here's the gun and $200. But we're not going to apologize.}
{279}{}{Why so?!}
{280}{}{Think. Try to imagine the reaction of the caravaneers when we'll show up again after what happened.}
{281}{}{Hmm, right, it may start a conflict.}
{282}{}{So I ask *you* to convey the money and weapon, along with our apologies.}
{283}{}{Well, in that case...}
{284}{}{So, that's it, the guy was still armed? A shady business, huh?}
{285}{}{Um, actually... Now I understand why you are avoiding any proceedings. Maybe I can convince you in the future. Or not. Let's talk about it later.}

###################################################################
#
#  Spy
#
###################################################################

{290}{}{Did you know someone at the station is involved in espionage?}

{291}{}{Is that so?}
{292}{}{He has asked me to copy the data on the patrol radio frequencies. I hope this information will help you?}
{293}{}{This information would *really* help us... But you have to play along, so we are sure that you're not lying.}
{294}{}{Err... Of course...}
{295}{}{Thanks for the help. My people will appreciate your deed, but don't think too much about it.}
{296}{}{Very well, but what was this guy shouting when you were tying him? Something about revenge for his brethren...}
{297}{}{Certainly, no problem.}
{298}{}{I do not know exactly how my men offended him, but there were cases when our troops were unable to protect settlements in need against aggressors. Some fell victim to raiders, others were captured by slavers. We can't take care of the whole region! The resource and manpower demand for the maintenance of outposts and organizing patrols is too heavy.}
{299}{}{So, you did all you could? Well, in any case, it will remain on your conscience. Goodbye.}

###################################################################
#
#  I need to discuss with you an important question
#
###################################################################

#Bomb
{300}{}{}
{301}{}{}
{302}{}{Deal.}
{303}{}{My answer is NO!}
{304}{}{Lift!}
{305}{}{Sorry, sir! Yes, sir!}

#Heavy munitions
{306}{}{I can sell heavy machine gun ammunition from Hawthorne.}
{307}{}{That is our caliber! These bullets were meant for heavy machine guns from a small speedboat fleet. We got a couple of them, dragged them from Hawthorne a few years ago. Now we can load them. An excellent find! I will buy a box for $ 750.}

#Pistol
{308}{}{In Hawthorne I managed to find an ceremonial gun. It looks impressive...}
{309}{}{Well, let's take a look... Wait, that's the personal sidearm of my ancestor! The man who saved our people during the Great War. And here I am, holding a piece of his past, a certificate of deeds long forgotten. I will buy this weapon for $ 1,000.}

#Selling Nuka
{320}{}{I am an official representative from Salt Lake City's Nuka-Cola factory and I have a mutually beneficial offer for you.}
{321}{}{We have a quartermaster at the entrance. You should resolve such questions with him.}
{322}{}{A trader in the old station? Okay, I'll talk to him.}
{323}{}{He said he wouldn't commit such deals without your permission.}
{324}{}{And he did the right thing. Where is the guarantee that you are who you're representing? And how can we trust you?}
{325}{}{In that case my license can convince you.}
{326}{}{You're not welcoming to such rare trade partners. Your loss...}
{327}{}{...And no one knows where did you get that. Prove yourself that you can be trusted. As for paper, there are better uses for them at the toilet.}
{328}{}{Hmm, you don't look like a charlatan. At least your actions say otherwise. I think we can give you a chance. I will contact the quartermaster by  radio, and you go and talk to him about the details of the deal.}
{329}{}{Yes, sir!}
{330}{}{Wait, let me explain it for you using my figures and diagrams....}
{331}{}{[listens carefully and looks interested] Hmm, talented traders are rare to be seen nowadays, I don't want to miss a profitable partner, whoever he is... I think we will give you a chance. I'll contact the quartermaster by the radio, and you go and talk to him about the details of the deal.}

###################################################################
#
#  About the Rednecks
#
###################################################################

{400}{}{Wait a minute. I have a further request, if you do not mind.}
{401}{}{Yes?}
{402}{}{I got reports about a couple of rednecks making some fuss at the checkpoint. But the reports have some issues, so I could use your help to clarify the situation.}
{403}{}{I will be glad to help you. What should I do?}
{404}{}{You know, scavengers like me don't know the word "help". Goodbye.}
{405}{}{I would be glad to help, but I've got to leave this place, too much trouble here. You will somehow sort things out without me.}

{406}{}{Talk with the guards at the checkpoint, then go down to the station and find those rednecks who stirred up everything. Talk to them, find out their version of the incident. They'll be more willing to talk with you than with military of the garrison.}
{407}{}{Sounds easy.}
{408}{}{I look forward to the report. The guards will help you.}
{409}{}{[Leave]}

{410}{}{Regarding the incident at the checkpoint.}
{411}{}{So, what happened?}
{412}{}{Funny story. It turned out, Private Derren committed intercourse with the redneck's daughter while collecting taxes. Father came here for justice and was denied to enter.}
{413}{}{Can't say exactly. These rednecks have gone back to the village, and the guards don't care about them.}
{414}{}{I'm afraid it's impossible to figure out. Because at the station was a commotion among newcomers. And the rednecks happened to be in the firing line.}
{415}{}{I still have not managed to find out the details. I'll be back when I hear anything.}
{416}{}{Okay, I believe you. In any case, I am glad that I wasn't disappointed in my men once again.}
{417}{}{Yes, that's alright.}
{418}{}{Private Derren is a good guy. It's strange that he got into such situation. However, it can be easily understood, since very few women live in the garrison. If he had a "crush" on the village girl, it's not a bad thing itself. Tell me, is she still at the station?}
{419}{}{I'm afraid not.}
{420}{}{Yes, she is still there with her dad.}
{421}{}{It's a pity. I could give him and the rest of the men an indicative hearing as a lesson. But have to confine with some explanatory conversation. Thank you for your intelligence on the matter.}
{422}{}{You're welcome.}
{423}{}{Perhaps the old man hoped that he would be able to send his daughter to the garrison. I don't think that my people would be pleased by that. But this is exactly what I need! *I* will make Derren marry her and take the girl to live with him. This will be an example to others and should make soldiers to treat people of the wasteland better. Thanks for the help.}
{424}{}{Take the 100 bucks for what I made you run around. Don't hurry to leave, your continued assistance in external relations would be very useful.}
{425}{}{What I need to do?}
{426}{}{Thank you, but I must continue my journey. I can't stay here for long. Goodbye.}
{427}{}{We have problems with the meat supply from one of the farmers. There is a reason to believe that farmer just doesn't trust us. It can be understood, given the reputation of the garrison. We need your help to restore confidence in us and re-establish contact with the farmer. Speak to the quartermaster, if you'll decide to take the job.}
{428}{}{I'll talk to him.}
{429}{}{Take the 100 bucks for making you run around. Sorry to see you leave, your assistance would be useful in external relations. But so far I have no more assignment for you. Farewell.}

###################################################################
#
#   вест по зачистке убежища
#
###################################################################
{500}{}{It has become known to me that the nearby vault is crawling with mutants. I could deal with that.}
{501}{}{Hmm. So, our operators are chitchatting again... Although, such situation is indeed the reason of our concern. I wouldn't take risks of dispatching my people, but if you know the location and willing to do everything by yourself - you're welcome to try. Report to me if it's done.}
{502}{}{I had a change of plans. Deal with it yourself.}
{503}{}{Good, I'll come by later.}
{504}{}{The mutants are all dead. They won't be a problem anymore.}
{505}{}{Our patrols are already confirmed that. Now we could fix the place up and find some usage for it... Oh, and here's your reward [hands you 2000$].}
{506}{}{Glad to help.}
{507}{}{You cound not be so cheap at least for once...}
###################################################################
#
#  Female Copy
#
###################################################################

{1202}{}{Enough of this! Let's see how you think about things tomorrow. Throw her in the cell!}
{1230}{}{In fact, you are wrong. I have never touched anyone of them in a lifetime. And then two of them in a row... Ugh... That's hard to bear.}
{1251}{}{What? A poor technician ordered an assassination of a wanderer? If that's some kind of joke, you will go to jail.}
{1254}{}{No. I bought the pickup from him for a heap of money. A great car, among other things.}
{1256}{}{He didn't until I helped him. The purchase was fair, but when I arrived in Vegas two grunts with assault rifles waited for me.}
{1257}{}{Are you stupid? Every single street punk will want to cut your throat for that pickup. Why the fuck you decided that it's our technician who sent "killers" after you?}
{1260}{}{Civilian, if you still are *able* to use you brain, remember what I said a minute ago. And if you continue... You will be sent to jail for slander. Is that clear?}
{1324}{}{And he did the right thing. Where is the guarantee that you are who you're representing? And how can we trust you?}
{1403}{}{I will be glad to help you. What should I do?}
{1405}{}{I would be glad to help, but I've got to leave this place, too much unspend testosterone. You will somehow sort things out without me.}

{5004}{}{The mutants are all dead. They won't be a problem anymore.}
{5006}{}{Glad to help.}
