{100}{}{Cell door.}
{101}{}{A heavy cell door.}

#Манипуляции с дверью камеры
{103}{}{The cell is locked.}
{104}{}{The cell door is locked with a huge lock. It's not possible to kick it open.}
{105}{}{The lock has already been picked.}
{106}{}{Well, that wasn't hard at all!}
{107}{}{You pick the cell door lock.}
{108}{}{You fail to pick the lock.}
{109}{}{Fail.}

#Диалог с тюремным надзирателем после заточения
{110}{}{Hey, you! Be quiet! Don't give me trouble, do your 24 hours and you'll be out just fine.}
{111}{}{Can you at least tell me what I'm in for?!}
{112}{}{How the hell am I supposed to know?}
{113}{}{Shit...}

{114}{}{There you go, 24 hours. Get out. Your stuff is in that locker.}
{115}{}{Wait a second, buddy, I want to ask you something... [Prepare to attack]}
{116}{}{Finally!}

#Прочее
{117}{}{You can't unlock the door from this side.}
{118}{}{Can't reach.}

#Female character:
{1115}{}{Wait a second, buddy, I want to ask you something... [Prepare to attack]}
