{100}{}{You see the main computer.}
{101}{}{You see the central computer of the headquarters.}

{102}{}{Inserting the key into the port, you hear a weak signal, which is accompanied by a dim picture greeting you on the monitor.}
{103}{}{Access granted}

#List of questions
{110}{}{Access granted. Select the directory.}
{111}{}{Select the directory.}
{112}{}{"Our enemies"}
{113}{}{Local disposition.}
{114}{}{Archive of the engineering service.}
{115}{}{Reports of the prison warden.}
{116}{}{The order for search of the Constitution.}
{117}{}{Works on the tracking system creation.}
{118}{}{}
{119}{}{[Close the session]}

{123}{}{[Back to the list]}

#Enemies
{130}{}{Enemies of the Wind of War are plenty, but mostly raiders and gangs, as well as loads of mutants - tarantulas and aliens.}
{131}{}{Read about raiders.}
{132}{}{Read about tarantulas.}
{133}{}{Read about aliens.}
{134}{}{Squads of raiders and other bandits, with which the Wind of War is fighting for influence over the region, usually are few in numbers, from 5 to 15 people. Some thugs hold power over smaller settlements, whose residents are tired of their oppression and asking for help.}
{135}{}{Predatory mutants of enormous size, living in dark damp places underground. Usually they come to the surface at night. Occasionally, their raids bring casualties among Wind of War population, but more often - among outsiders and merchants, staying in the suburbs. The creatures are intensively fought by Wind of War forces, but their numbers seems to be recovering after each encounter. It is noticed that the highest activity of the mutants observed in the area of the destroyed local vault, but with each new year they are encountered at a greater distance from it.}
{136}{}{Predatory mutants with infrared vision. Like tarantulas, they do not like sunlight, preferring to come to the surface at night and sleep during the day in dark dungeons. We know for sure, that the main nest of aliens is a military base to the north, the so-called "Area 51".}

#Disposition
{137}{}{Around the Wind of War, mostly along the slopes, there are small settlements, usually two or three families, that are not of interest. To the north, the military base called "Area 51" is located. To the west - the "Hawthorne" military base. Also, among other geographical locations provided, there is a vault in the mountains in the north-west. Apparently, this is the vault from which the local population came.}
{138}{}{Record the coordinates of the shelter and go to the area.}
{139}{}{Record the coordinates of the Area 51 base.}
{140}{}{Write down the coordinates of Hawthorne.}
{141}{}{Coordinates listed in your Pip-Boy.}

{142}{}{The "Super 8" incident.}
{143}{}{The incident occurred during the transportation of the dangerous cargo designated as "Super 8". The contents of the cargo are not disclosed in documents. It is known that due to the "oversight of the convoy" cargo disappeared, and the convoy was killed. Soon came a report about the residents of a small village nearby disappearing. The remains of their bodies were found in the caves not far off. It is not clear how these events are connected, but one thing is almost certain - the "Super 8" is no ordinary cargo.}

#Reports of the warden
{150}{}{The Wind of War is not alien to punitive measures. Many raiders and other criminals were executed here, to threaten residents of the Southern Nevada.}
{151}{}{Look the report on current inmates.}
{152}{}{Sam Riley, 24 years, male, resident of Las Vegas. The order of execution: cut off the hands, feet, then hang in public on a fence, barely alive. Cause of the execution: received information from our secret agent in Vegas about the intentions of the prisoner - he was engaged in espionage on behalf of one of the reputable inhabitants of the city. The command, as usual, chose the simplest way - to eliminate the enemy spy.}

#Constitution
{160}{}{It seems that the command of the base really believes in the Old America and its values. For example, the order to caravans was made, about the delivery of a copy of Constitution from the museum in Reno, along with US flags, posters, and various military paraphernalia of the pre-war USA. It is difficult to say, whether it's worth the efforts.}

#Blueprints
{170}{}{The computer gave a list of various blueprints, specifications and other technical documentation. Most of them useless to you, but something interesting can be selected.}
{171}{}{Look for the blueprints of the power armor.}
{172}{}{Database contains only blueprints of the frame structure. There were no blueprints of the internal modules of the armor.}
{173}{}{Go back.}

{174}{}{Alas, access to blueprints is limited by a very complicated password.}
{175}{}{Try to hack.}
{176}{}{Access granted.}
{177}{}{Yes! That's how it's done!}
{178}{}{You gained 350 XP for hacking the complex password.}
{179}{}{Apparently, it is beyond your current capabilities.}
{180}{}{[Back to the main menu]}
{181}{}{Copy all the available information to the disk.}
{182}{}{It's done.}

{190}{}{Copy the data on regular radio frequencies.}
