{100}{}{You see the main computer.}
{101}{}{You see the central computer of the headquarters.}

{102}{}{Inserting the key into the port, you hear a weak signal, which is accompanied by a dim picture greeting you on the monitor.}
{103}{}{Access granted.}

#List of questions
{110}{}{Access granted. Select the directory.}
{111}{}{Select the directory.}
{112}{}{"Our enemies"}
{113}{}{Local disposition.}
{114}{}{Engineering service archive .}
{115}{}{Prison warden reports .}
{116}{}{An order to search for the Constitution.}
{117}{}{Works on the tracking system creation.}
{118}{}{}
{119}{}{[End session]}

{123}{}{[Back to the list]}

#Enemies
{130}{}{Enemies of the Wind of War are plenty, but mostly they are raider gangs and loads of mutants - tarantulas and aliens.}
{131}{}{Read about the raiders.}
{132}{}{Read about the tarantulas.}
{133}{}{Read about the aliens.}
{134}{}{The bands of raiders and other bandits with whom Wind of War fight for influence over the region are usually small, from 5 to 15 men. Some bandits hold power over small settlements, whose inhabitants are tired of their oppression and ask for help.}
{135}{}{Predatory mutants of enormous size, living in dark damp places underground. These mutants usually come to the surface at night. Occasionally their raids result in casualties among Wind of War's population, but more often among outsiders and merchants staying in the suburbs. Wind of War forces fight these creatures intensively, but their numbers seem to recover after each encounter. The highest area of mutant activity was observed around the destroyed local vault, but with each passing year they are encountered farther from it.}
{136}{}{Predatory mutants with infrared vision. Like tarantulas, they do not like the sunlight, preferring to come to the surface at night and sleep in dark caves during the day. The main nest of aliens was verified to be a military base to the north, so-called "Area 51".}

#Disposition
{137}{}{Around the Wind of War, mostly along the slopes, there are small settlements, usually of two or three families, which are of no interest. The military base called "Area 51" is located to the north. To the west - the "Hawthorne" military base. Among other geographical locations is a vault in the mountains to the northwest. Apparently, this is the vault from which the local population arrived.}
{138}{}{Record the coordinates of the vault and go to the area.}
{139}{}{Record the coordinates of the Area 51 base.}
{140}{}{Write down the coordinates of Hawthorne.}
{141}{}{Coordinates are listed in your Pip-Boy.}

{142}{}{The "Super 8" incident.}
{143}{}{This incident occurred during the transportation of some dangerous cargo designated "Super 8". The contents of the cargo are not disclosed in the documents, but it is known that due to some "oversight by the convoy" the cargo disappeared and the convoy was killed. Soon after the residents of a small nearby village were reported to have also disappeared. The remains of their bodies were found in some caves not far off. It is not clear how these events are connected, but one thing is almost certain - this "Super 8" is no ordinary cargo.}

#Reports of the warden
{150}{}{The Wind of War is no stranger to punitive measures. Many raiders and other criminals were executed here, to serve as a lesson to the residents of Southern Nevada.}
{151}{}{Look at the report on current inmates.}
{152}{}{Sam Riley, 24 years, male, resident of Las Vegas. The order of execution: cut off the hands, feet, hang on a fence, alive. Cause of the execution: received information from our secret agent in Vegas about the intentions of the prisoner - he was engaged in espionage on behalf of one of the reputable inhabitants of the city. The command, as usual, chose the simplest way - to eliminate the enemy spy.}

#Constitution
{160}{}{It seems that the base high command really believes in the Old America and its values. For example, a caravan order was made to deliver of a copy of the Constitution from the museum in Reno, along with US flags, posters, and various military paraphernalia from pre-war USA. It's difficult to say if it was worth the efforts.}

#Blueprints
{170}{}{The computer returns a list of various blueprints, specifications and other technical documentation. Most of them are useless to you, but something interesting can be selected.}
{171}{}{[Look at the power armor blueprints]}
{172}{}{Database contains only blueprints of the frame structure. There are no blueprints of the internal modules of the armor.}
{173}{}{[Go back]}

{174}{}{Alas, access to the blueprints is restricted by a very complex password.}
{175}{}{[Try to hack it]}
{176}{}{Access granted.}
{177}{}{Yes! That's how it's done!}
{178}{}{You gained 350 XP for hacking the complex password.}
{179}{}{Apparently, it is beyond your current abilities.}
{180}{}{[Back to the main menu]}
{181}{}{Copy all the available information to the disk.}
{182}{}{Done.}

{190}{}{Copy the data on regular radio frequencies.}
