{100}{}{You see power distribution unit.}
{101}{}{You see a distributor by means of which the barracks is supplied with electricity.}
{102}{}{You see an idle power distributor.}

{103}{}{This distributor is buzzing, supplying the barracks with power.}
{104}{}{This distributor is already switched off.}
{105}{}{You flip the switch, and the barracks is no longer supplied with electricity.}
{106}{}{You lack technical knowledge to switch off the distributor.}
{107}{}{Scientific approach should be used on computers, rather than distributors.}
{108}{}{This won't help, you need to get technical.}
{109}{}{This won't help.}

{110}{}{Hey, who turned the lights off!?}
{111}{}{Damn fuses blew again...}
{112}{}{I'm afraid of the dark... Just kidding.}

{113}{}{The time is inappropriate for sabotage.}
{114}{}{*Script error*}
{115}{}{Move it, Jesse!}
{116}{}{This is the key for a cache in the ruins, you might find some use for it. Bye!}
