{100}{}{A nasty-looking settlement. Staying alert would probably be a good idea.}
{110}{}{Hey, you! No weapons allowed!}
{111}{}{Can you hear me? Put your weapon away!}
{112}{}{You're asking for it, aren't you?!}
{113}{}{This is your final warning! Put away your weapon, or I'll shoot!}
{114}{}{ALARM! WE'RE UNDER ATTACK!}

{115}{}{That was unexpected!}
{116}{}{Now you understand why the local mechanic guards the garage entrance so zealously.}

{117}{}{What's that!?}
{118}{}{Hey! Looks like the sound of a running engine is coming from the station garage!}
