{100}{}{You see a trainman.}
{101}{}{You see your trainman.}

#Таймер, плавающие реплики
{105}{}{We need to slow down a little, otherwise turbine can overheat and we'd have to walk.}
{106}{}{Alright. Let's rest.}
{107}{}{I'll go find a toilet.}
{108}{}{Well then, I guess I'll look around in these buildings.}
{109}{}{::Fellows, respond. A bird is in a cage. Time to sing along::}
{110}{}{::First, copy. Preparing::}
{111}{}{::Second, copy. Preparing::}
{112}{}{::First sings::}
{113}{}{::Second's ready::}
{114}{}{::Copy. Wait for the bird. I'm returning::}

#Во время боя
{115}{}{Ah! Damn! Die already!}
{116}{}{You just wanted it, right?}
{117}{}{Idiot! They won't leave you alone!}
{118}{}{What are you talking about?!}
{119}{}{The government know everything about us!! They'll find you!}
{120}{}{They already did, as you can see...}
{121}{}{You think you're cool?! Just die!}
{122}{}{Hell no!}
{123}{}{I wouldn't do that, but they made me!}
{124}{}{You're lying!}
{125}{}{Speak! Who gave an order?}
{126}{}{I won't tell you!}

#Отладка
{150}{}{1}
{151}{}{2}
{152}{}{3}
{153}{}{4}
{154}{}{5}
{155}{}{6}