{100}{}{}
{101}{}{You see your trainman.}
{102}{}{You see your trainman.}

{103}{}{I'll be here if I needed.}
{104}{}{Wait for me.}
{105}{}{Oh, shit! You? What the hell?! What have you gotten me into?}
{106}{}{Calm down. We don't time to sort things out. Let's get back to the train.}
{107}{}{We'll deal with this later. For now just be here.}

{108}{}{If I ever do this again!...}

{110}{}{Hey! Anybody!}
{111}{}{Get me outta here!}
{112}{}{Oh shit...}
{113}{}{Damn it, what did I get myself into...}
{114}{}{Where is my partner?...}
{115}{}{Hey! Anybody, save me!!}
{116}{}{Am I here all alone?}
{117}{}{Am I really going to be left in here?}

#Женские реплики
{1105}{}{Oh, shit! You? What the hell?! What have you gotten me into?}
