{100}{}{}
{101}{}{You see: Reaper of Souls!}
{102}{}{You see: the mysterious "Reaper of pure souls".}
{103}{}{Well, shit! Looks you've got ambushed!}

#Damage regen
{104}{}{Oh damn! That bugger somehow grew back his injured limbs!}
{105}{}{Hm... Regeneration!!!}
{106}{}{Waaagh... Regeneration!!!}
{107}{}{My strength is fading... Regeneration!!!}
{108}{}{How did he do that!?...}

#Dialogue between Reaper and the Train Operator
{110}{}{Shit! I knew this job smelled fishy! Are you gonna kill me?}
{111}{}{You are of no interest to me. Where's the Wanderer?}
{112}{}{I'll talk! I'll talk! He went towards that vault on the other side of the bridge! Just let me go!}
{113}{}{Lock him up!}
{114}{}{But I told you everything!}
{115}{}{Move!}

{116}{}{This is the only way out. Cover all access points.}
{117}{}{He's not getting away this time. Men! Get in position!}
{118}{}{Go! Go! Go! Double time!!!}
{119}{}{She's not getting away this time. Men! Get in position!}

#Dialogue between Reaper and MC
{120}{}{Citizen, you have trespassed on governmental property. Walk out with your hands up or we'll open fire.}
{121}{}{Who the hell are you, anyway!?}
{122}{}{I repeat. Resistance is futile. All exits have been cut off. We will let you live if you lay down your arms and come out with your hands up.}
{123}{}{(Talk about bad luck...)}

{124}{}{Hey, hold up big guy! Let's talk this out!}
{125}{}{I've said everything.}
{126}{}{Oh no, you didn't say why I should surrender *alive*. I guess it has something to do with that shiny device from my vault. You want it, don't you? And you think I have it on me. What if I don't? If you kill me, you'll never find it.}
{127}{}{Damn, I need to think...}

{128}{}{Hm. You're bluffing. I can hear it in your head.}
{129}{}{Hear? Somehow, I doubt that...}

{130}{}{Surrender peacefully. It'll be better for everyone. A bullet in your body won't prevent me from getting the information I need from you. Will just make it... Messier.}
{131}{}{Surrender peacefully. It'll be better for everyone. A bullet in your body won't prevent me from getting the information I need from you. Will just make it... Messier.}
{132}{}{First, I want answers... Reaper. That's your codename, isn't it?}
{133}{}{Is that a threat? Looks like you're going to kill me anyway. Fine, I'll think about it...}

{134}{}{[He snorts at your pathetic bad-assery] Ask.}
{135}{}{Who are you?}
{136}{}{What are you doing to so-called "pure bodies"?}
{137}{}{Why did you need the Overseer?}
{138}{}{Why do you need the device for?}

{139}{}{My callsign is Reaper of Souls. My real name is Jason Bayham. As you can see, the answers gave you nothing.}
{140}{}{I take the most valuable. The rest goes towards guard rations.}
{141}{}{He knew how to use the device. Now I do. He did his job, and you're here. There's only one thing I need now, and you're going to give it to me.}
{142}{}{I need the data to make bodies. This world is drowning in filth. The humanity needs to evolve.}
{143}{}{So, you need a supply of pure bodies. For what? To keep experimenting? To "shape" humans as you see fit? You think it's for you to decide?}
{144}{}{Look at me. I've lived far longer than anyone. I enhanced myself beyond what you are able to comprehend. I am the future. The owners of this vault didn't understand... But their reasoning meant nothing to me. So as yours. Now stop wasting my time.}

{165}{}{You're pathetic. Time to end this.}
{166}{}{Hey, we've only just began!...}
{167}{}{You know what, I don't care. Just go fuck yourself.}
{168}{}{Stop wasting my time.}

{169}{}{I don't get it. Maybe I should ask another question.}
{170}{}{That sounds rational... Mind telling me something else?}
{171}{}{Do you really think you know better? Look at what you've become!}
{172}{}{Damn, that actually sounds almost convincing. I need to know more.}
{173}{}{What was that about souls?...}

{174}{}{You are unable to understand. You... You could have a purpose. Until you were thrown out of your vault.}
{175}{}{What purpose? To become a soup for your goons?}
{176}{}{No. Pathetic, worthless life clings to your body. It means nothing. You could have made a difference. You could have helped make the world a better place, save the lives of future generations. But now you are worthless. The Overseer, the government, the biker, even you - all of you have only delayed the inevitable. A grave mistake. Time's up. Let's get this over with.}
{177}{}{What? What does that mean!?}
{178}{}{It's time.}
{179}{}{What are you even talking about!?}

#Female version:
{1112}{}{I'll talk! I'll talk! She went towards that vault on the other side of the bridge! Just let me go!}
{1120}{}{Citizen, you have trespassed on governmental property. Walk out with your hands up or we'll open fire.}
{1126}{}{Oh no, you didn't say why I should surrender *alive*. I guess it has something to do with that shiny device from my vault. You want it, don't you? And you think I have it on me. What if I don't? If you kill me, you'll never find it.}
