{100}{}{}
{101}{}{You see: Reaper of Souls!}
{102}{}{You see: the mysterious "reaper of pure souls".}
{103}{}{Well, shit! Looks you've got ambushed!}

#Damage regen
{104}{}{Oh damn! That bugger somehow grew back his injured limbs!}
{105}{}{Hm... Regeneration!!!}
{106}{}{Waaagh... Regeneration!!!}
{107}{}{My strength is fading... Regeneration!!!}
{108}{}{How did he do that!?...}

#Dialogue between Reaper and the Train Operator
{110}{}{Shit! I knew this job smelled fishy! Are you gonna kill me?}
{111}{}{You are of no interest to me. Where's the Wanderer?}
{112}{}{I'll talk! I'll talk! He went towards that vault on the other side of the bridge! Just let me go!}
{113}{}{Lock him up!}
{114}{}{But I've helped you!}
{115}{}{Move!}

{116}{}{This is the only way out. Cover all the access points.}
{117}{}{He won't get away this time... Men! In position!}
{118}{}{Go! Go! Go! Double time!!!}
{119}{}{She's not getting away this time... Men! In position!}

#Dialogue between Reaper and MC
{120}{}{Citizen, you have trespassed on governmental property. Walk out with your hands up or we'll open fire.}
{121}{}{And who are you!?}
{122}{}{I repeat. Resistance is futile. All exits have been cut off. We will let you live if you lay down your arms and come out with your hands up..}
{123}{}{(Talk about bad luck...)}

{124}{}{Hey, hold up big guy! Let's talk this out?}
{125}{}{I've said everything.}
{126}{}{Oh no, you didn't tell me why I need to surrender *alive.* A bullet in my skull isn't part of your plan for my body, is it?}
{127}{}{Damn, I need to think...}

{128}{}{Hm. You're bluffing. I can hear it in your head.}
{129}{}{Hear? Somehow, I doubt that...}

{130}{}{Surrender peacefully. It'll be best for everyone. A bullet between your eyes will only make my job easier.}
{131}{}{Surrender peacefully. It'll be best for everyone. A bullet between your eyes will only make my job easier.}
{132}{}{First, I want answers... Reaper. That's your codename, isn't it?}
{133}{}{Is that a threat? Well, looks like you'll kill me either way. Fine, I'll think about it...}

{134}{}{[Snorts at your pathetic bad-assery] Ask.}
{135}{}{Who are you?}
{136}{}{What are you doing to my fellow citizens?}
{137}{}{Why did you need the Overseer?}
{138}{}{What is this vault?}

{139}{}{My callsign is Reaper of Souls. My real name is Jason Bayham. As you can see, the answer gave you nothing.}
{140}{}{I take the most valuable - what saves lives of others. The rest goes towards guard rations.}
{141}{}{He became a burden in my plans. Just like you. But he did his job - after all, you're here. He was only a bait.}
{142}{}{The true owners of America lived here. So as I. But... That is in the past now.}
{143}{}{Don't like bad memories, eh? Looks like you didn't completely lose your humanity.}
{144}{}{I've lived far longer than anyone. Your reasoning means nothing to me. Now stop wasting time.}

{165}{}{You're pathetic, let's end this!}
{166}{}{Hey, we've only just began!..}
{167}{}{You know what, I don't care. So just go fuck yourself..}
{168}{}{Stop wasting my time.}

{169}{}{What are you talking about? A bit strange, don't you think? Maybe you should answer something else.}
{170}{}{That sounds rational... Mind telling me something else?}
{171}{}{Do you really have some kind of a mission? Interesting... Maybe you could tell me a little more?}
{172}{}{So, you're not the only one? Damn, I need to know more!}
{173}{}{What was that about souls?..}

{174}{}{You can't understand. You purpose... Your true mission was in this.}
{175}{}{In what? Becoming soup for your goons?}
{176}{}{No. Pathetic, worthless life clings to your body. It means nothing. It could save the life of a worthy man, but now it's too late. The Overseer, biker and you - you all broke the rules. A grave mistake. But your soul... I'm going to keep it until a worthy purpose is found.}
{177}{}{What? What does that mean!?}
{178}{}{It's time.}
{179}{}{Hey, what are you even on!?}

#Female version:
{1112}{}{I'll talk! I'll talk! She went towards that Vault on the other end of the bridge!.. Just let me go!..}
{1120}{}{Citizen, you have trespassed on governmental property. Walk out with your hands up or we'll open fire.}
{1126}{}{Oh no, you didn't tell me why I need to surrender *alive.* A bullet in my skull isn't part of your plan for my body, is it?}
