{100}{}{You see a vessel filled with liquid.}
{101}{}{You see a vessel containing the severed head inside.}
{102}{}{You see a tank with the severed head of the former President of the United States of America. Surprised?}

{103}{}{Away from my precious, you!}

{104}{}{*Zzzzz*}
{105}{}{Something is blocking the console!}
{106}{}{Nothing useful.}
{107}{}{You are victorious!}
{108}{}{Better hurry up and get out of here.}
{109}{}{What the...}
{110}{}{Shit!!!}

#Второй диалог после победы над турелями:
{111}{}{[In front of you is a head with wires sticking out of its upper jaw. It silently stares at you with one eye, in expectation.]}
{112}{}{You promised you wouldn't hurt me. Why didn't you keep your word? I trusted you!}
{113}{}{[The head is silent.]}
{114}{}{Hey, don't pretend you can't hear me!}
{115}{}{We... [crying] Mister is wrong!}
{116}{}{Is that so? Why?!}
{117}{}{My precious and I have always meant well and fought for justice. We didn't want to! We swear it! It was an accident! It won't happen again!}
{118}{}{Of course it won't happen again, because the turrets are destroyed.}
{119}{}{We didn't want it! We didn't mean to!! Let Mister forgive us! I demand that Mister forgive us!}
{120}{}{That's a good idea. But how do I know you won't kill me when I walk out that door, where the turrets still work?}
{121}{}{They're on their own! It is not us! Honest presidential word!}
{122}{}{Yeah?}
{123}{}{Yes! Yes! They wanted to kill Mister themselves! And we didn't want to!}
{124}{}{Cut it. You WERE going to kill me, weren't you?}

{125}{}{Mister should forgive us! We were just kidding! We wouldn't really do that! Somehow the others don't like our jokes. They never did! Why...}
{126}{}{All right, I forgive you. Let's forget the past, shall we?}
{127}{}{I don't believe you. Now open the big door so I could get the hell outta here!}
{128}{}{I need to think. I'll be back soon and tell you my decision.}
{129}{}{}

#ПОЛОЖИТЕЛЬНЫЕ РЕПЛИКИ [после ответа 126]:
{130}{}{What's he saying, precious? Ohhhh... Mister is very wise and very polite! Mister President likes Mister! Ah! If only all subordinates were like that, right, precious?!}
{131}{}{Whay do you mean? You've been mistreated?}
{132}{}{Mr. President does not want to remember the past. It's a bad memory. But precious remembers how cruelly the president was treated last time! They made him cry in public! In front of all his subordinates! Mister has never seen such a pitiful sight!}

#ПОЛОЖИТЕЛЬНЫЕ РЕПЛИКИ, первая фраза, история [после 132]:
{133}{}{Can precious tell about why Mister President is here, and not on his legitimate post?}
{134}{}{Precious, aren't you going to tell Mister? Yes, Mister doesn't need to know. But perhaps Mister would like a cup of tea? No, my precious, we don't have time to deal with the tea party. Do you remember how everyone abused Cola? Everyone's tongues turned blue. It was so ugly!}
{135}{}{What does Nuka-Cola have to do with anything?}

{136}{}{Quiet! The Mister must not interrupt the president's speech! Where are the Mister's manners?!}
{137}{}{That's it, skull, enough of this nonsense! Open the damn door!!}
{138}{}{Oh, I'm sorry. Keep going.}

{139}{}{They didn't know how dangerous this liquid was! They thought they were just troubled by bad memories and doubts, but it was something different. They thought they were in control of everything! Hahaha! Precious remembers how we laughed at their naivety.}
{140}{}{Naivety? Why? What was about that liquid?}
{141}{}{Оh! Mister wants to know! But can we tell him? Yes, now that all those silly people have left our apartment, perhaps we can tell Mister the truth.}
{142}{}{Of course. I'm listening.}
{143}{}{They thought Cola was harmless. But their supply was special. This supply... um... This supply was intended to enhance their central nervous system and brain activity. Yes.}
{144}{}{Interesting. So, the Cola made them more anxious?}
{145}{}{Oooh, yes! Mister guessed right. But Cola didn't just intensify their emotional state, it intensified it *selectively*. It took a while, but when the poison seeped deeper inside, they couldn't stop... They went crazy! They were fighting, screaming, hitting each other with chairs, and after we restricted access to Cola, they freaked out even more and started killing each other.}
{146}{}{Did they hurt you? Did they beat the president?}
{147}{}{[Plaintively] Mister President does not want to remember how he was beaten.}
{148}{}{So, they did. Is that why you're like this?}
{149}{}{Yeees. We've been like this ever since. Precious has been with us since that day, too. We were deemed too important to be thrown in the trash can. We have been reassembled and revived by the doctor, our good friend.}
{150}{}{Probably for a reason. And why, you say, did you laugh at their naivety? Because you knew in advance that the occupants of the vault were test subjects?}
{151}{}{They thought they were the ones doing the experiments. But in fact, they were also being experimented on.}
{152}{}{They were doing the experiments... Does this mean that other vaults were also subjected to some kind of experimentation?}
{153}{}{How did Mister find out about this, precious? Is Mister somehow connected to secret governmental circles?}
{154}{}{What? No. Consider this a lucky guess. There's something unusual going on in my vault, too.}
{155}{}{Once again, Mr. President, was not notified! How is it even possible to work with such subordinates?!}
{156}{}{Right. So, how about I go punish your subordinates now so that they behave in the future?}
{157}{}{Oh, Mister wants to leave our apartment? So soon? Why so soon?}
{158}{}{Because my family and fellow citizens are waiting for me. I have to get back to them, or my home will fall victim to the attacks of the many mutant animals and raiders. It is my civic duty. After all, Mr. President is supposed to take care of his people. He's not going to let them die, is he?}
{159}{}{No, no, no!!! Precious says Mister's trying to confuse us! Make Mister shut up!!! Make him stop!!!}
{160}{}{Come on! I NEED to go! The well-being of my people depends on it, as well as yours and mine.}
{161}{}{SHUT UP!!! I DON'T WANT IT!!! KEEP IT QUIET!!! [sobbing] Mister is very cruel! Let Mister leave our apartment. We don't want to listen to him anymore!}
{162}{}{All right then.}

#ПОЛОЖИТЕЛЬНЫЕ РЕПЛИКИ, вторая фраза, хочет уйти [после 132]:
{163}{}{Mister doesn't want to see. Mister just wants to get out of here.}
{164}{}{But... [looks like is confused] But... Is Mister bored with our company? Why does Mister want to leave so quickly?}
{165}{}{Because my people are waiting for me - my family, my fellow citizens. I have to get back to them, or my home will fall victim to the attacks of the many mutant animals and raiders. It is my civic duty.}
{166}{}{Civic duty? Mister President has already forgotten what civic duty is... Oh...}
{167}{}{Does President remembers his national anthem?}
{168}{}{No. Mister President doesn't remember! He doesn't remember!!!}
{169}{}{What is painted on America's national flag?}
{170}{}{Mister President DOES NOT REMEMBER!!!}
{171}{}{Yes, Mr. President has forgotten many things. Maybe it's time to come out and look at the world as it is now?}
{172}{}{NO, NO, NO!!! It's dangerous outside! Precious says Mister is trying to confuse us! Make Mister shut up!!! We're not coming out, Mister is not coming out! It's dangerous out there!!! Dangerous!!!}
{173}{}{Yes, Yes, Yes!!! Mr. President wants to go outside! He wants to see it! Yes! Mister will help Mr. President, right?}
{174}{}{Does Mr. President want to remember? Maybe we can look up the lyrics of the anthem on the vault network and sing it together?}
{175}{}{NO, NO, NO!!! Precious says Mister is trying to confuse us! Make Mister shut up!!! Shut up!!!}
{176}{}{Yes, Yes, Yes!!! Mister President wants to remember! Attention!! Rise up! Raise heads! Homeland!! Make America!! Great again!! But... What?.. No!! Precious says Mister is trying to confuse us! Make Mister shut up!!! Shut up!!!}
{177}{}{But you do remember the days when you were human. You have not completely lost your humanity, even after your tragedy. Remember your responsibilities, let me go, for the sake of your country, your people. For whom you fought and for whom you suffered.}
{178}{}{SHUT UP!!! I DON'T WANT IT!!! KEEP IT QUIET!!! [sobbing] Mister is very cruel! Let Mister leave our apartment. We don't want to listen to him anymore!}
{179}{}{All right then.}
{180}{}{Well, maybe Mr. President will remember his presidential duty and let his servant go?}
{181}{}{Mr. President remembers honor... Freedom... Independence...}
{182}{}{Well?}
{183}{}{NO, NO, NO!!! Precious says Mister is trying to confuse us! Make Mister shut up!!! Shut up!!!}
{184}{}{SHUT UP!!! I DON'T WANT IT!!! KEEP IT QUIET!!! [sobbing] Mister is very cruel! Let Mister leave our apartment. We don't want to listen to him anymore!}
{185}{}{All right then.}

#НЕГАТИВНЫЕ РЕПЛИКИ, начало:
{186}{}{What's he saying, precious? Oooh... Mister doesn't want to accept our hospitality. And how would Mister feel about a little boom in Korea? What, precious? Ah, yes... We're out of bombs... Oh, well. We're petitioning the Council to lock the doors and leave rude Mister here, with us... FOREVER!!! [crying] We want to smoke a Cuban cigar so badly... Don't we, precious? Let someone get us a cigar!}
{187}{}{So that's how it is? What if I just kill you?}
{188}{}{Ugh!!! Hahaha! Mister made a joke! We certainly liked it, didn't we, precious?!}
{189}{}{Mister is furious with your mumbling! Open the gate or I'll break this glass!}
{190}{}{Wow! Mister is furious! We always liked such stubborn Misters.}
{191}{}{Stop your raving, you skull!}
{192}{}{AH-ha-HA-HAH!!!}
{193}{}{[He won't just let you go. You need a strong argument.]}

#НЕГАТИВНЫЕ РЕПЛИКИ, первая возможность - динамит:
{194}{}{Enough!!! I'll put the dynamite right here, and you'll finally get some fresh air!}
{195}{}{Ack? [his lonely eye stares at your dynamite in fear.] Mister is joking, right? Mister is joking! It's not a real bomb! Let Mister blow it elsewhere! We order him! We impose a veto on Mister's decision!}
{196}{}{Stupid head, you can't veto anything. Not anymore. [continue planting the dynamite]}
{197}{}{But... Precious, what are we going to do? Mister is not joking! Mister is ordered to assassinate us! Maybe Mister will accept a counter-offer? 50% more over the amount! We're not joking too, Mister.}
{198}{}{Hmm. Sounds interesting.}
{199}{}{We have money. We'll pay mister if he puts that red thing in this container.}
{200}{}{I will do it if you pay me 1,000,000.}
{201}{}{I will do it if you'll pay me 500,000.}
{202}{}{I will do it if you pay me 50,000.}
{203}{}{I will do it if you pay me 5,000.}
{204}{}{Yeeee-haaaw! We have tricked Mister! Ha-ha!!! Mister is a patsy! Perhaps Mister is from Canada? Oh, well. Guards! Show our guest to the door!}
{205}{}{Hey! I was really fooled by a severed head!}
{206}{}{I'm sick of your nonsense. I'm setting the bomb off.}
{207}{}{No! Let Mister not hurry! We need to think! Precious wants to think too!}
{208}{}{You have no time. Make your decision: either you open this door, or I'll blow you up and you'll stop controlling it.}
{209}{}{[Ignore the head and start the timer]}
{210}{}{Okay. We make a decision. We, with precious, order the door to be opened. Yes. Let Mister take his red thing and go away... [groans]}
{211}{}{That's it, I'm going.}

#НЕГАТИВНЫЕ РЕПЛИКИ, вторая возможность - провода:
{212}{}{I'm going to do something simpler - open this box and pull out some wires.}
{213}{}{What? But... But... Precious, is Mister authorized to get into that box with wires?}
{214}{}{No. But, as you can see, I do it anyway.}
{215}{}{Mister can't hurt us! Mister has no right!}
{216}{}{Maybe. But I don't care.}
{217}{}{Arrgh... We are the president! We are not allowed to be hurt!}
{218}{}{Yeah. [open the controller]}
{219}{}{Precious, Mister is not subjected to our laws! What do we do?!}
{220}{}{[Rip out a few insignificantly-looking wires]}
{221}{}{Ow-ow-ow-ow!!! Mister can't do this!}
{222}{}{[Short a couple of wires]}
{223}{}{Ughh!! Mister hurts us very much!}
{224}{}{[Do it again]}
{225}{}{No! Mister must stop!}
{226}{}{[Do it again]}
{227}{}{AHHH! Make Mister stop! Stop!!!}
{228}{}{[Rip out the hose with a nutrient liquid]}
{229}{}{[Short circuit harder]}
{230}{}{If you won't open the door, I will continue to torment you.}
{231}{}{Mister is very cruel! We have done so much good, but Mister hurts us! Precious, that's not fair! [crying]}
{232}{}{Shut up and open the door!}
{233}{}{[Short circuit again, this time stronger]}
{234}{}{NO!!! NO!!! MOTHERF-!!!... [it seems that the poor fellow's brain couldn't take it.]}

#НЕГАТИВНЫЕ РЕПЛИКИ, третья возможность - кукла:
{235}{}{No! The President is against aggressive actions! The President insists on a peaceful solution to the issue!}
{236}{}{I also insist on a peaceful solution. So, maybe you'll let me go peacefully?}
{237}{}{No, Mister has not yet fulfilled his duties as a citizen. Mister can't just walk away. Mister President is not in the mood. No.}
{238}{}{Now I'm gonna tear off his left leg.}
{239}{}{NOOO!!! The President misses the precious one! No need to hurt precious! My precious! My precious! Hang in there! The police is on its way!}
{240}{}{You idiot, soon the leg of your precious will fly into the far corner of the room!}
{241}{}{NOOOO!!! Why Mister is so cruel! Why?!! For many years precious and I have been close! No one has ever been so close! May Mister be sensible and bring back precious! The President would even get down on his knees if he had them! Honestly!}
{242}{}{[Tear up the doll and throw it in all directions]}
{243}{}{NO!!! NO!!! MOTHERF-!!!... [it seems that the poor fellow's brain couldn't take it.]}
{244}{}{So, what decision does the President make in such a difficult situation? Isn't it better to give up a guest for his own benefit?}
{245}{}{Yes!!! Mister is right!! We'll let Mister go, but precious must stay here!!!}
{246}{}{}
{247}{}{[Stand back and watch]}
{248}{}{I think it's Mr. President's doll. What if I tear off a few limbs?}
{249}{}{}

{250}{}{AAAAHHHA-HA-HA-HA!!! Welcome to our apartments, Mister! Sorry that we are not in uniform, there's nothing to put it on! Maybe Mister could tickle us with a feather, hmm?}
{251}{}{What the... A talking head?! Are you... Alive?}
{252}{}{Mister is IDIOT!!! I'm not just a talking head! Before you is Mr. President himself! Where did this Mister crawled from, if he can't distinguish the president from everyone else?!... What, my precious? Out of ass?!!! My precious, you should learn some manners!}
{253}{}{Well, that's new.}
{254}{}{What are you saying, my precious?! Yes, we agree. Such Misters should be quartered. All who come out of ass must be exterminated!!!}
{255}{}{Are you sure about that?}
{256}{}{What? What does he say? He wants to scare us? Alright then. Let this citizen come out and lean on my ringer... I mean... I mean, my finger. What, my precious? I don't have a finger? Well... Then lean on my something. Let Mister come out. We won't hurt him.}
{257}{}{Do you promise? Can I trust you?}
{258}{}{Yes, Yes, YES!!! We'll be good! Just let Mister come closer! We haven't seen anyone in so long! We want to see Mister!}
{259}{}{Hmm...}

{260}{}{You were severely electrocuted! It's the shenanigans of the head!}
{261}{}{Ah! Damn!!!}
{262}{}{And you still managed to do what you were trying to do!}
{263}{}{A broken tank.}
{264}{}{All that remains of the former President - little green pieces of brain and meat.}

{270}{}{Mr. President, life on the surface is now quite normal. There is no threat of bombs falling, and radiation levels are quite tolerable. You have nothing to fear!}
{271}{}{You spoiled little...}
{272}{}{But... How can we trust these doubtful words?!}
{273}{}{Simply because of the fact that there is a person from the outside world standing in front of you, who entered easily through the front door. Isn't that proof?}
{274}{}{Oh, right... But we're still not sure. And... Why do we have to go out?}
{275}{}{Don't you want to take a look at the outside world? Just once? Listen, you can always go back if you don't like it. It's so easy!}
{276}{}{Hahaha!! Mister is right! And you, precious, what do you say? Precious also wants to see the outside world? Yes, we will do it!! We will see, we will be brave!!}
{277}{}{What determination!}
{278}{}{All right! Counselors! WE SOLEMNLY ANNOUNCE THE OPENING OF THE GOVERNMENT VAULT AND THE BEGINNING OF THE PROCESS OF REBUILDING AMERICAN SOCIETY AFTER NUCLEAR WAR! Initiate the procedures of the Sarcophagus Directive!}
{279}{}{Sounds cool. Better to step aside and watch...}

{280}{}{Ladies and gentleman! It's time to get our asses off the monitors! IN THE NAME OF AMERICA!!!}
{281}{}{You manage to convince the head to go out to the surface! Where will it go now?}
{282}{}{All right!! Now I'll put this cordex in here and you'll get some fresh air!!!}

#Female character
{1108}{}{Better hurry up and get out of here.}
{1112}{}{You promised you wouldn't hurt me. Why didn't you keep your word? I trusted you!}
{1115}{}{We... [crying] Miss is not right!}
{1119}{}{We didn't want it! We didn't mean to!! Let Miss forgive us! I demand that Miss forgive us!}
{1123}{}{Yes! Yes! They wanted to kill Miss themselves! And we didn't want to!}
{1125}{}{Miss should forgive us! We were just kidding! We wouldn't really do that! Somehow the others don't like our jokes. They never did! Why...}
{1127}{}{I don't believe you. Now open the big door so I could get the hell outta here!}
{1130}{}{What's she saying, precious? Ohhhh... Miss is very wise and very polite! Mister President likes Miss! Ah! If only all subordinates were like that, right, precious?!}
{1132}{}{Mr. President does not want to remember the past. It's a bad memory. But precious remembers how cruelly the president was treated last time! They made him cry in public! In front of all his subordinates! Miss has never seen such a pitiful sight!}

#YOU ARE HERE


{1134}{}{Precious, you're not gonna tell? Yes, Miss don't need to know. But maybe Miss wants a cup of tea? No, precious, we have no time to deal with the tea party. Remember how everyone abused cola? Everyone got their tongues blue. It was so ugly!}
{1136}{}{Quiet! Let miss not interrupt the President's speech! Where is her manners?!}
{1141}{}{Oh! Miss wants to know? But can we tell her? Yes, now, when all these stupid people left our apartment, we *can* tell Miss the truth.}
{1145}{}{Ooo, yes! Miss guessed it. But Cola doesn't just intensified their emotional state, it intensified it *selectively*. Some time passed, and when the poison has seeped deep inside, they were not able to stop. ... They went crazy! They fought, they shouted, beat each other with chairs, and after we restricted access to Cola, they freaked out even more and began to fight to the death.}
{1153}{}{How did miss know all these secrets, precious? Is miss related to the secret government circles?}
{1157}{}{Oh, miss want to leave our apartment? So fast? Why so fast?}
{1159}{}{No no no!!! Precious said that miss wants to confuse us! Make miss shut up!!! Make her stop!!!}
{1161}{}{SHUT UP! I DON'T WANT!!! KEEP IT QUIET!!! [sobbing] Miss is very strict! Let miss leave our apartment. We don't want to hear it!}
{1163}{}{Miss don't want to see us. Miss just wants to get out of here.}
{1164}{}{But... [looks like he is confused] But... Is miss bored with our company? Why miss wants to leave so quickly?}
{1172}{}{No no no!!! It's dangerous outside! Precious said that miss wants to confuse us! Make miss shut up!!! We're not getting out, this won't work! It's dangerous!!! Dangerous!!!}
{1173}{}{Yes, Yes, Yes!!! Mister President wants to go outside! He wants to watch! Yes! Miss will help us, right?}
{1175}{}{No no no!!! Precious said that miss wants to confuse us! Make miss shut up!!! Shut up!!!}
{1176}{}{Yes, Yes, Yes!!! Mister President wants to remember! Attention!! Rise up! Raise heads! Homeland!! Make America!! Great again!! But... What?.. no! Precious said that miss wants to confuse us! Make miss shut up!!! Shut up!!!}
{1178}{}{SHUT UP! I! I DON'T WANT!!! KEEP IT QUIET!!! [sobbing] Miss is very strict! Let miss leave our apartment. We don't want to hear her anymore!}
{1183}{}{No no no!!! Precious said that miss wants to confuse us! Let miss shut up!!! Shut up!!!}
{1184}{}{SHUT UP! I! I DON'T WANT!!! KEEP IT QUIET!!! [sobbing] Miss is very strict! Let miss leave our apartment. We don't want to hear her anymore!}
{1186}{}{What she says, precious? Ooo... Miss did not want to accept our hospitality. And how miss will feel about little boom in Korea? What, precious? Ah, yes... We've ran out of bombs... Oh well. We put forward a petition to the Council, to lock doors and not to give access to inhospitable miss... FOREVER!!! [crying] We want to smoke a cuban cigar so badly... Don't we, precious? Let someone bring a cigar!}
{1188}{}{Ugh!!! Hahaha! Miss decided to make a joke! We like it, don't we, precious?!}
{1189}{}{The miss is just furious from your mumblings! Open the gate or I'll break this glass!}
{1190}{}{Wow! Miss is furious! We always loved the stubborn misses.}
{1195}{}{Arch? [his eye looks on your dynamite in fear] Miss is joking, right? Miss is joking? It's not a real bomb! Let miss blow it elsewhere! We order her! We impose a veto on the decision of miss!}
{1197}{}{But... Precious, what are we going to do? Miss is not kidding! Miss is ordered to assassinate us! Maybe miss will accept a counter-offer? 50% more over the amount you will be paid for the assassination! We're not kidding, miss.}
{1199}{}{We got the money. We will pay Miss if she puts the red thing in that container.}
{1204}{}{Weeeeeee-haaaa! We have tricked miss! Ha-ha!!! Miss is stupid! Perhaps miss came from Canada? Well. Guards! Walk our guest to the door!}
{1207}{}{No! Let miss not hurry. We need to think! The precious also wants to think!}
{1210}{}{Okay. We make a decision. We, with the precious, command to open the door. Yes. Let miss take his red thing and go away... [groans]}
{1213}{}{What? But... But... The precious, is miss authorized to go into that box with wires?}
{1215}{}{Miss can't cause us pain! Miss has no right!}
{1219}{}{But precious, miss is not subjected to our laws! What do we do?}
{1221}{}{Ow-ow-ow-ow!!! Miss can't do this!}
{1223}{}{Uhh!! Miss hurts us very much!}
{1225}{}{No! Miss must stop!}
{1227}{}{AHHH! Make miss stop! Stop!!!}
{1231}{}{Miss is very cruel! We have done so much good, but miss is hurting us! Precious, it's not fair! [crying]}
{1237}{}{No, miss has not yet fulfilled her duties as a citizen. Miss can't just walk away. Mister President is not in the mood, but...}
{1241}{}{NOOOO!!! Why miss is so cruel! Why?!! For years we've been with the precious in a good relationship! No one has ever been so close! Let miss be sensible and bring back the precious! The President would even stand up to his knees if he had ones! Honestly!}
{1244}{}{So what is the decision the President will make in such a difficult situation? Isn't it better to give up the guest for your own benefit?}
{1245}{}{Yes!!! Miss is right! We let miss go, but the precious must stay here!!!}
{1250}{}{AAAHHHHHH-HA-HA-HA!!! Welcome to our apartment, miss! Sorry we are not in uniform, nothing to wear it on! Maybe miss could tickle us with a feather, m?}
{1252}{}{Miss is IDIOT!!! Mister President is alive! Where did this miss crawled from if she can't distinguish alive head from dead skull?!... What, my precious? Out of ass?!!! My precious, you should learn some manners!}
{1253}{}{Well, that's not what I meant...}
{1254}{}{What you say precious?! Yes, we agree. Such misses should be decimated. Everyone who has come out of ass - all of them must be DESTROYED!!!}
{1256}{}{What? What is she saying, precious? She wants to scare us? Well. Let the citizen come out and cling to my eyeglasses... I mean... I wanted to say, to my finger. What, my precious? I have no finger? Well, then... Then to my something. Let miss come out. We won't touch her.}
{1258}{}{Yes, Yes, YES!!! We'll be nice! Just let miss come closer! We haven't seen anyone for a long time! We want to see the miss!}
{1276}{}{Hahaha! Miss is correct! And you, precious, what do you say? The precious also wants to see the outside world? Yes, we'll do it! We'll see, we will be brave!}
