{100}{}{You see a vessel filled with liquid.}
{101}{}{You see a vessel containing the severed head inside.}
{102}{}{You see a vessel with the severed head of former President of United States of America inside. Surprised?}

{103}{}{Away from my precious, you!}

{104}{}{*Zzzzz*}
{105}{}{Something is blocking the console!}
{106}{}{Nothing useful.}
{107}{}{You got your victory!}
{108}{}{Better hurry up and get out of here.}
{109}{}{What the...}
{110}{}{Aw shit!!!}

#Второй диалог после победы над турелями:
{111}{}{[Before you is a head with wires sticking out of the upper jaw. It silently looks at you, with one eye, in expectation]}
{112}{}{You promised you wouldn't hurt me? Why didn't you keep your word? I believed you!}
{113}{}{[The head is silent]}
{114}{}{Hey, don't pretend you can't hear me!}
{115}{}{We... [crying] Mister is wrong!}
{116}{}{Is that so? Why?!}
{117}{}{We with my precious always wanted good and fought for justice. We didn't want! We swear! It was an accident! This will happen no more!}
{118}{}{Sure it won't happen, because the turrets are now destroyed.}
{119}{}{We didn't want! We didn't mean to!!! Let the mister forgive us! I demand that mister forgave us!}
{120}{}{That's an idea. But how would I know that you won't kill me if I step out of that door, where the turrets are still working?}
{121}{}{They themselves! It's not us! Honest presidential word!}
{122}{}{Yeah?}
{123}{}{Yes! Yes! They wanted to kill mister themselves! But we didn't!}
{124}{}{But you first said that you would kill me. How to understand this?}

{125}{}{Mister have to forgive us! We were just joking! We wouldn't do it! For some reason, the others don't like our jokes. Never did! Why...}
{126}{}{All right. I forgive you. Let's forget the past?}
{127}{}{I don't believe you. Now open the big door so I can get the hell outta here!}
{128}{}{I need to think. I'll be back soon and tell you my decision.}
{129}{}{}

#ПОЛОЖИТЕЛЬНЫЕ РЕПЛИКИ [после ответа 126]:
{130}{}{What does he say, precious? Oooh... Mister is very wise and very courteous! Mister President likes mister! Ah! If all subordinates were like that, right, precious?!}
{131}{}{You've been mistreated?}
{132}{}{Mister President doesn't want to remember the past. It's a bad memory. But the precious may recall how cruelly the President was treated the last time! They made him cry in public! In front of all subordinates! Mister had never seen such a pitiful sight!}

#ПОЛОЖИТЕЛЬНЫЕ РЕПЛИКИ, первая фраза, история [после 132]:
{133}{}{Can precious tell about why mister President is here, and not on his legitimate post?}
{134}{}{Precious, you're not gonna tell mister? Yes, mister don't need to know. But maybe mister wants a cup of tea? No, my precious, we have no time to deal with the tea party. Remember, how everyone abused cola? Everyone got their tongues blue. It was so ugly!}
{135}{}{And what does Nuka-Cola has to with everything?}

{136}{}{Quiet! Mister should not interrupt the President's speech! Where is the mister's manners?!}
{137}{}{That's it, skull, enough nonsense! Open the damn door!!!}
{138}{}{Oh, I'm sorry. Keep going.}

{139}{}{They did not know how dangerous this liquid was! They thought that they were just worried about the bad memories and doubts, but this was something different. They thought they control everything, that they control *everything*! Heh-heh-heh! The precious remembers, how we laughed at their naivety.}
{140}{}{Naivety? And what was in this liquid, that made it such a threat?}
{141}{}{Oh! mister wants to know? But can we tell him? Yes, now, when all these stupid people left our apartment, we *can* tell mister the truth.}
{142}{}{Sure. I'm listening.}
{143}{}{They thought that Cola is harmless. But they were delivered with a *special* supply. This supply... Hmm... Supply was intended to enhance the activity of their central nervous system and brain. Yes.}
{144}{}{Interesting. So, Cola caused greater anxiety?}
{145}{}{Ooo, yes! Mister guessed right. But Cola doesn't just intensified their emotional state, it intensified it *selectively*. Some time passed, and when the poison has seeped deep inside, they were not able to stop. ... They went crazy! They fought, they shouted, beat each other with chairs, and after we restricted access to Cola, they freaked out even more and began to fight to the death.}
{146}{}{They even beat the President?}
{147}{}{[Plaintively] Mister President does not want to remember how he was beaten.}
{148}{}{So they did. Which is probably why you are here?}
{149}{}{Yees. Since that time we are here. The precious is also with us since that day. We were considered too important to throw out into the trash can. We were re-assembled and revived.}
{150}{}{Probably, for a good reason. And why, you say, you laughed at their naivety? Because you knew in advance, that the vault dwellers were test subjects?}
{151}{}{Not everyone knew that they are experimented upon. On the contrary, they thought it's them who made experiments.}
{152}{}{You mean the experiment with the vaults?}
{153}{}{How did mister know all these secrets, precious? Is mister somehow related to the secret government circles?}
{154}{}{What circles? No, I don't belong to them. But I know about the vault project. It has been known for a long time.}
{155}{}{Oh... And again, mister President, was not notified! How is it possible, to work with such subordinates!?}
{156}{}{That's for sure. So, maybe I will go now to punish your subordinates, so they knew how to behave in future?!}
{157}{}{Oh, mister want to leave our apartment? So fast? Why so fast?}
{158}{}{Because my family and fellow citizens are waiting for me. I need to get to them, otherwise the place will become the victim of numerous mutated animals and raiders. This is my civic duty. Mister President, after all, should care about his people. He would not gonna let them die, would he?}
{159}{}{No no no!!! Precious said that mister wants to confuse us! Let mister shut up!!! Make him stop!!!}
{160}{}{Come on! I *need* to go! The well-being of our people, so as yours and mine, depends on it.}
{161}{}{SHUT UP! I DON'T WANT!!! KEEP IT QUIET!!! [sobbing] Mister is very strict! Let mister leave our apartment. We don't want to hear him anymore!}
{162}{}{That's right.}

#ПОЛОЖИТЕЛЬНЫЕ РЕПЛИКИ, вторая фраза, хочет уйти [после 132]:
{163}{}{Mister doesn't want to see. Mister just wants to get out of here.}
{164}{}{But... [looks like is confused] But... Is mister bored with our company? Why mister wants to leave so quickly?}
{165}{}{Because my people are waiting for me - my family, my fellow citizens. I need to get to them, otherwise the place will become the victim of numerous mutated animals and raiders. This is my civic duty.}
{166}{}{Civic duty? Mister President has already forgotten what civic duty is... Oh...}
{167}{}{Does President remembers his national anthem?}
{168}{}{No. mister President doesn't remember! Doesn't remember!!!}
{169}{}{What's painted on the national emblem of America?}
{170}{}{Mister President does NOT REMEMBER!!!}
{171}{}{Yes, mister President have forgotten many things. Maybe it's time to get out and see the world for what it is now?}
{172}{}{NO, NO, NO!!! It's dangerous outside! Precious said that mister wants to confuse us! Make mister shut up!!! We're not getting out, mister is not getting out! There's dangerous!!! Dangerous!!!}
{173}{}{Yes, Yes, Yes!!! Mister President wants to go outside! He wants to watch! Yes! mister will help us, right?}
{174}{}{Mister President wants to remember? Maybe we will look for the anthem's lyrics in the in the network of the vault, and sing it together?}
{175}{}{NO, NO, NO!!! Precious said that mister wants to confuse us! Make mister shut up!!! Shut up!!!}
{176}{}{Yes, Yes, Yes!!! Mister President wants to remember! Attention!! Rise up! Raise heads! Homeland!! Make America!! Great again!! But... What?.. no! Precious said that mister wants to confuse us! Make mister shut up!!! Shut up!!!}
{177}{}{But you do remember the days when you were human. You cannot lose your humanity, even after your tragedy. Remember about the responsibility, let me go, for the sake of your people for which you fought and for which you suffered.}
{178}{}{SHUT UP! I! I DON'T WANT!!! KEEP IT QUIET!!! [sobbing] Mister is very strict! Let mister leave our apartment. We don't want to hear him anymore!}
{179}{}{That's right.}
{180}{}{Well, maybe mister President will remember *his* presidential duty and let go of his servant - the one, thanks to which he was put to this post.}
{181}{}{Mister President remembers, honor... Freedom... Independence...}
{182}{}{Well?}
{183}{}{NO, NO, NO!!! Precious said that mister wants to confuse us! Make mister shut up!!! Shut up!!!}
{184}{}{SHUT UP! I! I DON'T WANT!!! KEEP IT QUIET!!! [sobbing] Mister is very strict! Let mister leave our apartment. We don't want to hear him anymore!}
{185}{}{That's right.}

#НЕГАТИВНЫЕ РЕПЛИКИ, начало:
{186}{}{What he says, precious? Oooh... Mister didn't want to accept our hospitality. And how mister will feel about little boom in Korea? What, precious? Ah, yes... We've ran out of bombs... Oh well. We put forward a petition to the Council, to lock the doors and to not let go of inhospitable mister.. FOREVER!!! [crying] We want to smoke a cuban cigar so badly... Don't we, precious? Let someone bring a cigar!}
{187}{}{That so? What if I just kill you?}
{188}{}{Ugh!!! Hahaha! Mister decided to make a joke! We like it, don't we, precious?!}
{189}{}{Mister became furious from your mumblings! Open the gate or I'll break this glass!}
{190}{}{Wow! Mister is furious! We always liked misters this stubborn.}
{191}{}{Stop raving, you, skull!}
{192}{}{AH-ha-HA-HAH!!!}
{193}{}{[He won't just release you, you need a strong argument]}

#НЕГАТИВНЫЕ РЕПЛИКИ, первая возможность - динамит:
{194}{}{Enough of it!!! I'll put the dynamite here, and you will finally get some fresh air!}
{195}{}{Arch? [his eye looks on your dynamite in fear] Mister is joking, right? Mister is joking? It's not a real bomb! Let mister blow it elsewhere! We order him! We impose a veto on mister's decision!}
{196}{}{You stupid, you can't veto anything. Not anymore. [continue placing the dynamite]}
{197}{}{But... Precious, what are we going to do? Mister is not kidding! Mister is ordered to assassinate us! Maybe mister will accept a counter-offer? 50% more over the amount! We're not kidding, mister.}
{198}{}{Hmm. It would be interesting.}
{199}{}{We got the money. We will pay to mister if he put the red thing in that container.}
{200}{}{I will, if you pay me 1.000.000}
{201}{}{I will, if you'll pay me 500,000}
{202}{}{I will, if you pay me 50,000}
{203}{}{I will, if you pay me 5.000}
{204}{}{Weeee-haaa! We have tricked mister! Ha-ha!!! Mister is a patsy! Perhaps mister came from Canada? Well. Guards! Walk our guest to the door!}
{205}{}{Hey! I was really fooled by severed head!}
{206}{}{I'm sick of your nonsense. I start the bomb.}
{207}{}{No! Let mister not hurry. We need to think! The precious also wants to think!}
{208}{}{You don't have time. You decide - either you open that door, or I will blow you up and you'll stop to control it.}
{209}{}{[Ignore and run the clockwork]}
{210}{}{Okay. We make a decision. We, with the precious, command to open the door. Yes. Let mister take his red thing and go away... [groans]}
{211}{}{That's it, I'm going.}

#НЕГАТИВНЫЕ РЕПЛИКИ, вторая возможность - провода:
{212}{}{I'll do something simpler - open this box and pull out some wires.}
{213}{}{What? But... But... The precious, is mister authorized to go into that box with wires?}
{214}{}{No. But as you can see, I still do.}
{215}{}{Mister can't cause us pain! Mister has no right!}
{216}{}{I don't. But I don't care.}
{217}{}{Arrgh... We were President! We *cannot* be hurt!}
{218}{}{Yeah. [open the controller]}
{219}{}{But precious, mister is not subjected to our laws! What do we do?!}
{220}{}{[Snatch a few inconsequential wires]}
{221}{}{Ow-ow-ow-ow!!! Mister can't do this!}
{222}{}{[Short a couple of wires]}
{223}{}{Ughh!! Mister hurts us very much!}
{224}{}{[Do it again]}
{225}{}{No! Mister must stop!}
{226}{}{[And again]}
{227}{}{AHHH! Make mister stop! Stop!!!}
{228}{}{[Rip out the main hose containing a nutrient liquid]}
{229}{}{[Short circuiting harder for control]}
{230}{}{If you don't open the door, I will continue to torment you.}
{231}{}{Mister is very cruel! We have done so much good, but mister is hurting us! Precious, it's not fair! [crying]}
{232}{}{Shut up and open the door!}
{233}{}{[Short circuiting again, this time stronger]}
{234}{}{NO!!! NO!!! MOTHER F!!!.. [looks like the brain of the poor fellow could not stand it]}

#НЕГАТИВНЫЕ РЕПЛИКИ, третья возможность - кукла:
{235}{}{No! Uh... The President is against the aggressive actions! The President insists on a peaceful solution to the issue!}
{236}{}{I also insist on a peaceful solution. So, maybe, you'll let me go peacefully?}
{237}{}{No, mister has not yet fulfilled his duties as a citizen. Mister can't just walk away. Mister President is not in the mood, but...}
{238}{}{Now I tear off his left leg.}
{239}{}{NOOO!!! The President will miss the precious! It is not necessary to hurt precious! My precious! My precious! Hang in there! The police is on its way!}
{240}{}{You idiot, soon the leg of your precious will fly into the far corner of the room!}
{241}{}{NOOOO!!! Why mister is so cruel! Why?!! For years we've been with the precious in a good relationship! No one has ever been so close! Let mister be sensible and bring back the precious! The President would even stand up to his knees if he had ones! Honestly!}
{242}{}{[Tear the doll and throw it in all the sides]}
{243}{}{NO!!! NO!!! MOTHER F!!!.. [looks like the brain of the poor fellow could not stand it]}
{244}{}{So, what is the decision the President makes in such a difficult situation? Isn't it better to give up the guest for your own benefit?}
{245}{}{Yes!!! Mister is right! We let mister go, but the precious must stay here!!!}
{246}{}{}
{247}{}{[Stand back and watch]}
{248}{}{I think that's mister President's doll. What if I tear off a few limbs?}
{249}{}{}

{250}{}{AAAHHHHHH-HA-HA-HA!!! Welcome to our apartment, mister! Sorry we are not in uniform, nothing to wear it on! Maybe mister could tickle us with a feather, m?}
{251}{}{Uh... A talking head?! Is it real?! And you... You're alive?}
{252}{}{Mister is IDIOT!!! Mister President is alive! Where did this mister crawled from, if he can't distinguish alive head from dead skull?!.. What, my precious? Out of ass?!!! My precious, you should learn some manners!}
{253}{}{Well, that's not what I meant...}
{254}{}{What do you say, precious?! Yes, we agree. Such misters should be decimated. Everyone, who has come out of ass - all of them must be DESTROYED!!!}
{255}{}{Are you sure this is a good idea?}
{256}{}{What? What is he saying, precious? He wants to scare us? Well. Let the citizen come out and cling to my eyeglasses... I mean... I wanted to say, to my finger. What, my precious? I have no finger? Well, then... Then to my something. Let mister come out. We won't touch him.}
{257}{}{Do you promise? Can I trust you?}
{258}{}{Yes, Yes, YES!!! We'll be nice! Just let mister come closer! We haven't seen anyone for a long time! We want to see the mister!}
{259}{}{Hmm...}

{260}{}{You were severely electrocuted while disabling!!! This is the work of the head!}
{261}{}{Ah! Damn!!!}
{262}{}{And you still managed to do what you tried to!}
{263}{}{Broken tank}
{264}{}{All that remains of the former President - the pieces of green brain and a little of meat.}

{270}{}{Mister President! On the surface now established quite a normal life. There is no threat of falling bombs, and quite tolerable level of radiation. You have nothing to fear!}
{271}{}{You spoilsport...}
{272}{}{But... How we can trust these doubtful words?!}
{273}{}{Just for the fact, that before you stands a person from the outside world, who easily entered through the front door. Isn't that the evidence?}
{274}{}{Oh, that's right... But we're not sure yet. And... And why should we go out?}
{275}{}{Don't you want to look at the outside world? Well, at least once? Look, you can come back, if you won't like it. It's so easy!}
{276}{}{Hahaha! Mister is right! And you, precious, what do you say? The precious also wants to see the outside world? Yes, we'll do it! We'll see, we will be brave!}
{277}{}{What determination!}
{278}{}{Okay!  Advisors! WE SOLEMNLY ANNOUNCE THE OPENING OF OUR VAULT AND START OF THE PROCESS OF REBUILDING AMERICAN SOCIETY AFTER A NUCLEAR WAR! Begin the procedure of "Sarcophagus" directive!}
{279}{}{Wow! Sounds cool! It is better to step aside and see...}

{280}{}{*Ladies and gentleman! It's time to get our asses off the monitors! IN THE NAME OF AMERICA!!!*}
{281}{}{You manage to convince the head to come to the surface! And where will it go now?}
{282}{}{All right!!! Now I'll place this Cordex here, and you'll find yourself getting some fresh air!}

#Female character
{1108}{}{And for this I made such a long way?!}
{1112}{}{You promised you wouldn't hurt me? Why didn't you keep your word? I believed you!}
{1115}{}{We... [crying] Miss is not right!}
{1119}{}{We didn't want! We didn't mean to!!! Let the miss forgive us! I demand that miss forgave us!}
{1123}{}{Yes! Yes! They wanted to kill miss! But we didn't!}
{1125}{}{Miss have to forgive us! We were just joking! We wouldn't do it! For some reason, the others don't like our jokes. Never did! Why...}
{1127}{}{I don't believe you. Now open the big door so I can get the hell outta here!}
{1130}{}{What does she say, precious? Oooh... Miss is very wise and very courteous! Mister President likes Miss! Ah! If all subordinates were like that, right, precious?!}
{1132}{}{Mister President doesn't want to remember the past. It's a bad memory. But the precious may recall how cruelly they treated the President last time! They made him cry in public! In front of all subordinates! Miss had never seen such a pitiful sight!}
{1134}{}{Precious, you're not gonna tell? Yes, Miss don't need to know. But maybe Miss wants a cup of tea? No, precious, we have no time to deal with the tea party. Remember how everyone abused cola? Everyone got their tongues blue. It was so ugly!}
{1136}{}{Quiet! Let miss not interrupt the President's speech! Where is her manners?!}
{1141}{}{Oh! Miss wants to know? But can we tell her? Yes, now, when all these stupid people left our apartment, we *can* tell Miss the truth.}
{1145}{}{Ooo, yes! Miss guessed it. But Cola doesn't just intensified their emotional state, it intensified it *selectively*. Some time passed, and when the poison has seeped deep inside, they were not able to stop. ... They went crazy! They fought, they shouted, beat each other with chairs, and after we restricted access to Cola, they freaked out even more and began to fight to the death.}
{1153}{}{How did miss know all these secrets, precious? Is miss related to the secret government circles?}
{1157}{}{Oh, miss want to leave our apartment? So fast? Why so fast?}
{1159}{}{No no no!!! Precious said that miss wants to confuse us! Make miss shut up!!! Make her stop!!!}
{1161}{}{SHUT UP! I DON'T WANT!!! KEEP IT QUIET!!! [sobbing] Miss is very strict! Let miss leave our apartment. We don't want to hear it!}
{1163}{}{Miss don't want to see us. Miss just wants to get out of here.}
{1164}{}{But... [looks like he is confused] But... Is miss bored with our company? Why miss wants to leave so quickly?}
{1172}{}{No no no!!! It's dangerous outside! Precious said that miss wants to confuse us! Make miss shut up!!! We're not getting out, this won't work! It's dangerous!!! Dangerous!!!}
{1173}{}{Yes, Yes, Yes!!! mister President wants to go outside! He wants to watch! Yes! Miss will help us, right?}
{1175}{}{No no no!!! Precious said that miss wants to confuse us! Make miss shut up!!! Shut up!!!}
{1176}{}{Yes, Yes, Yes!!! Mister President wants to remember! Attention!! Rise up! Raise heads! Homeland!! Make America!! Great again!! But... What?.. no! Precious said that miss wants to confuse us! Make miss shut up!!! Shut up!!!}
{1178}{}{SHUT UP! I! I DON'T WANT!!! KEEP IT QUIET!!! [sobbing] Miss is very strict! Let miss leave our apartment. We don't want to hear her anymore!}
{1183}{}{No no no!!! Precious said that miss wants to confuse us! Let miss shut up!!! Shut up!!!}
{1184}{}{SHUT UP! I! I DON'T WANT!!! KEEP IT QUIET!!! [sobbing] Miss is very strict! Let miss leave our apartment. We don't want to hear her anymore!}
{1186}{}{What she says, precious? Ooo... Miss did not want to accept our hospitality. And how miss will feel about little boom in Korea? What, precious? Ah, yes... We've ran out of bombs... Oh well. We put forward a petition to the Council, to lock doors and not to give access to inhospitable miss... FOREVER!!! [crying] We want to smoke a cuban cigar so badly... Don't we, precious? Let someone bring a cigar!}
{1188}{}{Ugh!!! Hahaha! Miss decided to make a joke! We like it, don't we, precious?!}
{1189}{}{The miss is just furious from your mumblings! Open the gate or I'll break this glass!}
{1190}{}{Wow! Miss is furious! We always loved the stubborn misses.}
{1195}{}{Arch? [his eye looks on your dynamite in fear] Miss is joking, right? Miss is joking? It's not a real bomb! Let miss blow it elsewhere! We order her! We impose a veto on the decision of miss!}
{1197}{}{But... Precious, what are we going to do? Miss is not kidding! Miss is ordered to assassinate us! Maybe miss will accept a counter-offer? 50% more over the amount you will be paid for the assassination! We're not kidding, miss.}
{1199}{}{We got the money. We will pay Miss if she puts the red thing in that container.}
{1204}{}{Weeeeeee-haaaa! We have tricked miss! Ha-ha!!! Miss is stupid! Perhaps miss came from Canada? Well. Guards! Walk our guest to the door!}
{1207}{}{No! Let miss not hurry. We need to think! The precious also wants to think!}
{1210}{}{Okay. We make a decision. We, with the precious, command to open the door. Yes. Let miss take his red thing and go away... [groans]}
{1213}{}{What? But... But... The precious, is miss authorized to go into that box with wires?}
{1215}{}{Miss can't cause us pain! Miss has no right!}
{1219}{}{But precious, miss is not subjected to our laws! What do we do?}
{1221}{}{Ow-ow-ow-ow!!! Miss can't do this!}
{1223}{}{Uhh!! Miss hurts us very much!}
{1225}{}{No! Miss must stop!}
{1227}{}{AHHH! Make miss stop! Stop!!!}
{1231}{}{Miss is very cruel! We have done so much good, but miss is hurting us! Precious, it's not fair! [crying]}
{1237}{}{No, miss has not yet fulfilled her duties as a citizen. Miss can't just walk away. Mister President is not in the mood, but...}
{1241}{}{NOOOO!!! Why miss is so cruel! Why?!! For years we've been with the precious in a good relationship! No one has ever been so close! Let miss be sensible and bring back the precious! The President would even stand up to his knees if he had ones! Honestly!}
{1244}{}{So what is the decision the President will make in such a difficult situation? Isn't it better to give up the guest for your own benefit?}
{1245}{}{Yes!!! Miss is right! We let miss go, but the precious must stay here!!!}
{1250}{}{AAAHHHHHH-HA-HA-HA!!! Welcome to our apartment, miss! Sorry we are not in uniform, nothing to wear it on! Maybe miss could tickle us with a feather, m?}
{1252}{}{Miss is IDIOT!!! Mister President is alive! Where did this Miss crawled from if she can't distinguish alive head from dead skull?!.. What, my precious? Out of ass?!!! My precious, you should learn some manners!}
{1253}{}{Well, that's not what I meant...}
{1254}{}{What you say precious?! Yes, we agree. Such misses should be decimated. Everyone who has come out of ass - all of them must be DESTROYED!!!}
{1256}{}{What? What is she saying, precious? She wants to scare us? Well. Let the citizen come out and cling to my eyeglasses... I mean... I wanted to say, to my finger. What, my precious? I have no finger? Well, then... Then to my something. Let miss come out. We won't touch her.}
{1258}{}{Yes, Yes, YES!!! We'll be nice! Just let miss come closer! We haven't seen anyone for a long time! We want to see the miss!}
{1276}{}{Hahaha! Miss is correct! And you, precious, what do you say? The precious also wants to see the outside world? Yes, we'll do it! We'll see, we will be brave!}
