{100}{}{It's the Overseer!}
{101}{}{You see the Overseer of your Vault! You've finally found him! But he is unconscious.}

{102}{}{So bright... I... see... Light...}
{103}{}{Ughhh...}

{104}{}{You see the Overseer of your Vault. A sorry sight to see. He's probably pumped full of drugs - or even something worse. He's unconscious and can't hear you. It may take more than just your intention to bring him back to his senses.}
{105}{}{Try to wake him up.}
{106}{}{Inject three stimpacks. Should be enough.}
{107}{}{Sergeant Graves' words come to mind...}
{108}{}{That's hopeless. What should I do now?}

{109}{}{How could you drop meds in a moment like this?!}
{110}{}{Shit, gotta pick them up.}
{111}{}{You barely manage to find a vein on the wrinkly hand and inject the stimpacks. Looks like it's working...}
{112}{}{[Wait a little longer]}

{113}{}{[The Overseer's blind eyes crack open] I... I can't see... Who is this...}
{114}{}{I'm a citizen of Vault City. My name is }
{115}{}{. I came to get you out of here.}

{116}{}{? I remember you... Remember everything. He knows... Everything. He got into... My head... But didn't wipe... My memory... Yet.}
{117}{}{Wipe your memory? Who? Why?! What did they want from you?}
{118}{}{[Coughs and twitches on the floor] I... Ughh...}
{119}{}{Come on, talk!}
{120}{}{Don't die on me, old man!}
{121}{}{They needed pure bodies...}
{122}{}{Pure bodies? Like, not touched by radiation or mutation, right?}
{123}{}{"Pure bodies"? The hell are you talking about?}
{124}{}{You don't understand... They needed them... To... Live...}
{125}{}{So they could stay alive, right?}
{126}{}{I'd appreciate it if you'd start making sense. Please.}
{127}{}{They needed flesh to replace their own...}
{128}{}{Whoever they are, they must be very strange-looking then.}

{129}{}{Gnhhh... [Overseer's eyes roll back, froth begins to drip out of his mouth]}
{130}{}{Hey!!! [shake his shoulder] Old man!? Wake up!}
{131}{}{Oh god! Overseer! Don't die on me, please!}

{132}{}{[With great effort, the Overseer hisses through clenched teeth] Doesn't... Matter. They are... Gone. Now here's... Only... Two of them. This is... A governmental vault.}
{133}{}{Yeah, I got that. Who are these two?}

{134}{}{One was... The president... The other one... Reaper of Souls...}
{135}{}{Yeah, that Reaper - he's quite a character.}
{136}{}{He was... The doctor. He... Enhanced himself. He knows that... You are here...}
{137}{}{Well shit! So he's waiting for me?}
{138}{}{He's here... He's... Here... [looks like the Overseer lost consciousness again]}
{139}{}{Hey! You're crazy, old man! There's no one here! We have to go!}
{140}{}{You don't... Understand...}
{141}{}{Understand what?!}
{142}{}{He is not... Evil. He is... Wrong.}
{143}{}{But he kills people! Those who are "pure"! And our citizens!}
{144}{}{You don't... Understand... You're all... An experiment. Clones... Grown... For this.}
{145}{}{What?! Grown for what? Born so that this guy could live forever?! Bullshit!}
{146}{}{No... So that the government... Could live.}
{147}{}{Government of the United States? Does it still exist?!}
{148}{}{It... Endures...}
{149}{}{So they had our City built just to have a supply? To regain their strength?}
{150}{}{...If one dies... They take the body... And... Switch... The mind...}
{151}{}{To prolong one life for the price of another? That's horrible!}
{152}{}{So those who are important could live longer? Seems rational.}
{153}{}{It was... Always... Like this. It was planned... Long before... Unghh... The Great War...}
{154}{}{And nobody knew? Not even you?}
{155}{}{I... Knew...}
{156}{}{And didn't do anything?! You piece of shit!!}
{157}{}{Don't blame yourself. There's nothing you could do. But, thanks to you, the City still goes on.}
{158}{}{I had no choice... I tried... I wanted... Out... But failed. [He coughs] Then... Reaper got... Involved. Now... We are doomed...}
{159}{}{But he won't just end us, right?}
{160}{}{They aren't stupid enough to kill us!}
{161}{}{Everyone... Who resists...}
{162}{}{Shit. What do we do? You know more than me! What do we do?!}

{163}{}{...There... Ugh...}
{164}{}{Hey, hey, hey! Not now! Answer me, dammit! WHAT DO WE DO?!}
{165}{}{Come on, Overseer! Please! Wake up!}

{166}{}{Computer... Lower level...}
{167}{}{Right, computer. What about it?}

{168}{}{You... Will understand... Who they are. Who is... the Reaper...}
{169}{}{I have a feeling that he will be a problem. What's next?}

{170}{}{There is... The president... On the lower... Kept alive... As a... Database...}
{171}{}{Alright, consider it done. What about you?}

{172}{}{I'm... A threat... Know too much...}
{173}{}{No! No, Overseer! Don't even ask!}
{174}{}{You're right, you have to die. I'll make it quick and painless.}
{175}{}{Shit, I need to think about this.}

{176}{}{Too... Late. Far too... Late... [the old man's eyes roll back and he loses consciousness once again.]}
{177}{}{Well... Fuck.} #BRILLIANT, LAUGHED SO HARD
{178}{}{Not now, Overseer! Stay with me!!!}
{179}{}{Oh, Overseer. What do I do now?}

{180}{}{Well, it's not like you had a choice.}
{181}{}{Looks like it's beyond your abilities.}

#Female versions
{1114}{}{I'm a citizen of Vault City. My name is }
{1115}{}{. I came to get you out of here.}