{100}{}{It's the Overseer!}
{101}{}{You see the Overseer of your Vault! You've finally found him! But he is unconscious.}

{102}{}{Bright... I feel... Light...}
{103}{}{Ughhh...}

{104}{}{You see the Overseer of your Vault. A sorry sight to see. He was probably pumped with loads of meds or something worse. He's unconscious now and can't hear you. It might take a little more than wishes to make him come to senses.}
{105}{}{Try and wake him.}
{106}{}{Inject three stims. Should be enough.}
{107}{}{Sergeant Graves' words come to mind...}
{108}{}{Well, that's hopeless. What should I do now?}

{109}{}{How could you drop meds in a moment like this?!}
{110}{}{Shit, gotta pick them up.}
{111}{}{You barely manage to find a vein on the wrinkly hand and inject the stims. Looks like it's working...}
{112}{}{(Wait a little longer)}

{113}{}{[The Overseer's blind eyes crack open] I... I can't see... Oh God... Who is this...}
{114}{}{I'm a citizen of Vault City. My name is }
{115}{}{. I came to get you out of here.}

{116}{}{? I remember you... I remember... Everything... They didn't wipe my memory yet...}
{117}{}{Wipe your memory? Why would they do that?! What did they need from you?}
{118}{}{[Coughs and twitches on the floor] I... Ughh...}
{119}{}{Come on, old man, think quick!}
{120}{}{Don't die on me, old man!}
{121}{}{They need pure bodies...}
{122}{}{Pure bodies? Like, not touched by radiation or mutation, right?}
{123}{}{"Pure bodies"? The hell are you talking about?}
{124}{}{You won't understand... They need... Regeneration...}
{125}{}{So they stay alive that way, right?}
{126}{}{I'd appreciate it if you started making sense sometime soon.}
{127}{}{They need flesh to replace theirs...}
{128}{}{They must be ancient. How old are they?}

{129}{}{Gnhhh... [the Overseer's eyes roll back, foam begins to drip out of his mouth]}
{130}{}{Hey!!! [shake his shoulder] Old man!? Wake up!}
{131}{}{Oh god! Overseer! Don't die, please!}

{132}{}{[With great effort, the Overseer hisses through clenched teeth] There are... Two... This is... A government Vault...}
{133}{}{Yeah, I got that. Who are these two?}

{134}{}{One was... The president... The other... Reaper of Souls...}
{135}{}{Yeah, that Reaper - he's quite a character.}
{136}{}{He can... Read minds... He knew of... Your arrival...}
{137}{}{Well shit! So he's waiting for me?}
{138}{}{... He's here... I can... Hear his... [looks like the Overseer lost consciousness again]}
{139}{}{Hey! You're talking crazy, old man! There's no one here! We have to go!}
{140}{}{You don't... Understand...}
{141}{}{Understand what?!}
{142}{}{They are not... Evil... Victims... Both of them...}
{143}{}{But they are killing "pure" people!}
{144}{}{You don't... Understand... You're all an experiment... Clones... Grown... For this...}
{145}{}{What?!!! Born so that those two can live forever?! Bullshit!}
{146}{}{No... So that the government... Could live.}
{147}{}{Government of the United States?! It still exists?!}
{148}{}{It... Endures...}
{149}{}{So they had our City built just to have a supply? To regain their strength?}
{150}{}{...If one dies... They take a body... And... Switch... The mind...}
{151}{}{And he'll come back to life? That's horrible!}
{152}{}{To live again? Seems rational.}
{153}{}{It was... Always... Like this. Long before... Unghh... The Great War...}
{154}{}{And nobody knew? Not even you?}
{155}{}{I... Knew...}
{156}{}{And didn't do anything?! You piece of shit!!}
{157}{}{Don't blame yourself. Nothing you could do. But, thanks to you, the City still goes on.}
{158}{}{Had no choice... We're... All... Doomed...}
{159}{}{But they won't just end us, right?}
{160}{}{They aren't stupid enough to kill us!}
{161}{}{...Everyone... Who resists...}
{162}{}{Shit. What do we do? You know more than me! What do we do?!}

{163}{}{...There... Ugh...}
{164}{}{Hey-hey-hey! Not now! Answer me, dammit! WHAT DO WE DO?!}
{165}{}{Come on, Overseer! Please! Wake up!}

{166}{}{Computer... Second level...}
{167}{}{Right, computer. What next?}

{168}{}{Wipe... The drives... Won't find us... Only the Reaper...}
{169}{}{Yeah, the Reaper will be a problem.}

{170}{}{There is also... The president... On the lower... Knows too much... Kept alive...  For it...}
{171}{}{Alright, consider it done. What about you?}

{172}{}{I'm... A threat... Know too much... Pure body...}
{173}{}{No! No, Overseer! Don't even ask!}
{174}{}{You're right, you'll have to die. I'll make it quick and painless.}
{175}{}{Shit, I need to think about this.}

{176}{}{Late... Far too... Late... [the old man's eyes roll back and he loses consciousness once more]}
{177}{}{Well... Fuck.} #BRILLIANT, LAUGHED SO HARD
{178}{}{Not now, Overseer! Stay with me!!!}
{179}{}{Oh, Overseer. What do I do now?}

{180}{}{Well, it's not like you had a choice.}
{181}{}{Looks like it's beyond your abilities.}

#Female versions
{1114}{}{I'm a citizen of Vault City. My name is }
{1115}{}{. I came to get you out of here.}