{100}{}{Oxygen supply cylinders.}
{101}{}{Emergency oxygen supply cylinders. Each has the word "EXPLOSIVE!" written on it in large letters.}
{102}{}{You could prepare the cart to explode and push it in the direction of turrets.}
{103}{}{Emergency oxygen supply cylinders. They can be pushed to the turrets, but how to blow them up from a distance?}
{104}{}{Here comes the boom!}
{105}{}{Nothing.}
{106}{}{You cannot do that during combat!}
{107}{}{You put the dynamite into the cart. All that's left is to set the timer and give a little push.}
{108}{}{Mined.}
{109}{}{You already mined the cart, additional charges are not required.}
{110}{}{That is unnecessary.}
{111}{}{You attached the cable to the gas cylinders and pushed the cart. All that's left is to give it a little charge.}
