{100}{}{}
{101}{}{You can't run the train during combat!}
{102}{}{Your mission here is not over yet!}

{103}{}{You can start the train and go back. Want to go back?}
{104}{}{You can start the train and go back, but your driver is not here. Are you ready to leave him to his fate and go back?}
{105}{}{Warm up the turbine and return.}
{106}{}{Cancel.}

{107}{}{Would you like to go to Salt Lake?}
{108}{}{Let's go!}
{109}{}{Cancel.}
