{100}{}{You see a tightly locked door.}
{101}{}{Looks like this door is closed by an electromagnetic mechanism.}
{102}{}{It appears to be the emergency exit, it only opens when you turn on the alarm.}
{103}{}{Looks like that door has electromagnetic mechanism with a secure control system.}

{110}{}{The door opens only with a special code that you do not know.}
{111}{}{Needs a key card.}
{112}{}{This is an emergency door to the lower level, it only opens when you turn on the alarm.}
{113}{}{Locked.}
{114}{}{The door is jammed. You'll have to use brute force to open it.}
{115}{}{Ugh!...}
{116}{}{Loudly creaking, the door yields to your impact and opens.}
{117}{}{Yes!}
{118}{}{This door is already open.}
{119}{}{Useless.}
{120}{}{You open the door with the key card.}
{121}{}{Open.}
{122}{}{This key card is not valid.}
{123}{}{The door is locked, you need a key card.}
{124}{}{The skill of hacking will not help. Need a key card.}
{125}{}{The door opens only in an emergency. There's not even a lock to crack.}
{126}{}{The door is actually opened. It's just stuck.}
{127}{}{Not even a scratch.}
{128}{}{Wrong.}
{129}{}{This key card is not suitable for this type of doors.}
{130}{}{Impossible.}
{131}{}{Access granted.}
