{110}{}{You see a device for distributing energy to the upper levels. Without it, there will be no power in the vault.}
{111}{}{The device doesn't work - and it's your fault!}
{112}{}{You've already disconnected power from this distributor.}
{113}{}{You disable this distributor and hear the hum of the wires in the vault getting quieter.}
{114}{}{You have very little time left before the backup generators turn on.}
{115}{}{**WARNING! BACKUP GENERATORS ACTIVATED!*}
{116}{}{You will not be able to shut down the distributor, your technical skills are not good enough.}
{117}{}{That won't do anything.}

{118}{}{The device does not work.}
{119}{}{This is a very important thing.}
{120}{}{Done.}
{121}{}{Unclear.}
{122}{}{That won't work here.}
{123}{}{The explosives should be placed *under* the device.}
{124}{}{Not working.}