{100}{}{You see a computer.}
{101}{}{You see a powerful computer terminal. It monitors your movement with several microcams.}

#Íà÷àëüíûå ðåïëèêè äèàëîãà
{104}{}{Welcome to the central terminal of the Vault Network, equipped with a voice-recognition module. To enter a request, simply announce it verbally.}
{105}{}{Who inhabited this vault?}
{106}{}{When did the population leave this vault?}
{107}{}{What do you know about vault 8?}
{108}{}{What? This means you understand my words, right?}
{109}{}{Leave.}

#Î'âå' - Ê'î áûë çàïå÷à'àí â ý'îì óáåæèùå:
{110}{}{Processing query. Please wait... The vault was intended for the president of the United States of America, his retinue and attendants.}
{111}{}{Are the remnants of the former government still alive?}
{112}{}{No reliable information is available on the subject. According to surveillance data, during the mass exodus of the population from the vault, 22% of the inhabitants died, while the rest managed to make it to the outside world. Indirect evidence suggests that the rest of the population may have survived and redeployed to another government base.}
{113}{}{What base? Tell me more about the surveillance data.}
{114}{}{According to the communication system's logs, before the mass exodus, negotiations between the command center and a base in the Pacific ocean took place. This base, also known as the "Poseidon Oil Rig," seems to be the most suitable place for the relocation of the vault's inhabitants. Remote requests on the status of the government vault are periodically received from there.}
{115}{}{Hmm. No one in the wasteland knows that the government is still around. Why all the secrecy?}
{116}{}{Processing query. Please wait... Information about the government's objectives is not available. Government program is not available.}
{117}{}{I see.}
{118}{}{[You get the holodisk with the data.]}

#Î'âå' - Êîãäà áûëî ðàñïå÷à'àíî ý'î óáåæèùå
{130}{}{Processing query. Please wait... The first opening of the main doors occurred 34 days after sealing. Subsequently, the doors were opened multiple times. The last instance occurred in 2090, followed by a mass exodus of vault dwellers.}
{131}{}{What was the cause of the mass exodus?}
{132}{}{Processing query. Please wait... The exodus was caused by increased social tension among the vault's residents. In particular, the year before this event there had been riots and attempts to overthrow the government. However, the main reason was the purposeful escalation of the situation by the president's head, which has become a threat to the life and health of the population.}
{133}{}{"The president's head"? What is that, some kind of code name?}
{134}{}{The president's head is the common name for the body part of Mr. Fredericks, at the time of his assassination - acting president of the United States. The head was recognized as an inanimate object and was used as an artificial intelligence and database. However, it retained consciousness and the ability to make rational decisions.}
{135}{}{Where is the president's head now?}
{136}{}{According to the latest reports, it is on the lower floor of the vault in a computer-controlled tank.}
{137}{}{How interesting... A living head!}

#Î'âå' - Âû ðàçóìíûé
{150}{}{Negative. My artificial intelligence functionality was removed by presidential order. I can't make meaningful decisions or initiate data analysis. My purpose is only to search for solutions to user requests.}
{151}{}{Where does the information come from then?}
{152}{}{The database is constantly updated by the surveillance system, robotic tracking modules, and data inputs from the outside.}
{153}{}{Outside?}
{154}{}{There is currently a working line of external communication with other government institutions outside the vault.}
{155}{}{}
{156}{}{Back.}

#Î'âå' - Âàì ÷'î-íèáóäü èçâåñ'íî îá óáåæèùå 8
{160}{}{According to available data, Vault 8 is being used by a private company under government control as a base for growing "insurance products". Note: this information may be outdated and no longer relevant.}
{161}{}{Wait, what "insurance products"?! What's that?}
{162}{}{According to the available data, the insurance product is a bodily organism devoid of intelligence. The structure of the organism allows it to be used as a donor for organ transplantation. The new organs quickly adapt to the characteristics of the new host. This makes it possible to prolong a person's life or relieve him from a serious illness, in case any of his organs ceases to function normally.}
{163}{}{But I don't look like an "insurance product"! Is this information accurate?}
{164}{}{, this information is based on available data and may not be relevant. More details can be found in the database.}
{165}{}{It's all a lie! I don't believe you, you tin can with no intelligence! Yeah, looks like the problems of my vault are a lot bigger than it seemed before.}

{166}{}{Sir}
{167}{}{Ma'am}
