{100}{}{You see a computer.}
{101}{}{You see a powerful computer with voice control module. He watches you with a few micro-cameras.}

#Начальные реплики диалога
{104}{}{Welcome to the central terminal of vault the network. To enter a query, just to announce it orally.}
{105}{}{Who inhabited this vault?}
{106}{}{When the population left this vault?}
{107}{}{What do you know about vault 8?}
{108}{}{What? This means you understand my words, right?}
{109}{}{Leave.}

#О'ве' - К'о был запеча'ан в э'ом убежище:
{110}{}{Query processing. Please wait... The vault was intended for the President of the United States of America, his retinue and attendants.}
{111}{}{These remnants of the former government are still alive?}
{112}{}{No reliable data. According to the surveillance, during a mass escape of the population from the vault, 22% of the inhabitants were killed, the rest managed to reach the outside world. Indirect evidences suggest that the population could survive and relocate to another government base.}
{113}{}{What kind of data and what base?}
{114}{}{According to the communication system's logs, before the mass escape, negotiations from the command center with a base in the Pacific ocean took place. This base, known as "Poseidon oil rig", seems to be the most suitable place to relocate to, for the dwellers of this vault. Periodically, there are remote requests for status information to a government vault from there.}
{115}{}{Hmm. In the outside world nothing of this government is known. Why all the secrecy?}
{116}{}{Query processing. Please wait... Information on the objectives of the government is closed. A government program is not available.}
{117}{}{I see.}
{118}{}{You got the holodisk with the data.}

#О'ве' - Когда было распеча'ано э'о убежище
{130}{}{Query processing. Please wait... After sealing, the first opening of the large doors occurred 34 days after. Subsequently, the doors were opened repeatedly. The latest case happened at 2090, followed by massive escape of dwellers.}
{131}{}{What was the cause of the mass escape?}
{132}{}{Increased social instability among the residents of the shelter. In particular, a year before this event was recorded rebellious riots and attempts at regime change. However, the main reason is a deliberate escalation of the situation by the head of the President, which threatened the life and health of the population.}
{133}{}{"The head of the President"? What is it, some kind of a name?}
{134}{}{The President's head - established brand name parts of the body of Mr. Fredericks, who was the current President of the United States at the time of his murder. The head was recognized as an inanimate object and used as artificial intelligence and database. However, it retained a part of consciousness and was able to intelligently make decisions.}
{135}{}{Where is the President's head now?}
{136}{}{According to recent reports, it is on the bottom floor of the vault in a special, computer-controlled tank.}
{137}{}{How interesting... A living head!}

#О'ве' - Вы разумный
{150}{}{Negative. My artificial intelligence was removed by the order of the President. I can't make meaningful decisions and initiate data analysis. My task is only to find solutions to user requests.}
{151}{}{Where does the information come from then?}
{152}{}{Vault database is constantly updated by robotic tracking system and data inputs from the outside.}
{153}{}{Outside?}
{154}{}{There is currently a working line of external communication with other government institutions outside the vault.}
{155}{}{}
{156}{}{Back.}

#О'ве' - Вам ч'о-нибудь извес'но об убежище 8
{160}{}{According to official data, vault number 8 is used by a private company under government control as a base for growing of "insurance products". Note: this information may be outdated and no longer relevant.}
{161}{}{Wait, what "insurance products"?! What's that?}
{162}{}{According to official data, the insurance product is the body organism, devoid of intelligence. The structure of this organism allows to transplant its organs to a human. New organs quickly adapt to a specific features of new host. This allows to extend the life of a person or to deprive him of a serious illness, if any of the organs ceases to function properly.}
{163}{}{But I don't look like "insurance product"! Is this information reliable?}
{164}{}{, this information is based on official data and may not be relevant. More details can be found in the locked database.}
{165}{}{It's all a lie! It's not up to you to tell, a tin can with no intelligence! Yeah, looks like the problems of my vault are a lot bigger than it seemed before.}

{166}{}{Sir}
{167}{}{Ma'am}
