#Кажется, текст не используется в 1.0., но не уверен полностью
{100}{}{There is only bundles of high-voltage cables here.}
{101}{}{Just some wires.}
{102}{}{There's nothing here but empty boxes from the cables.}
{103}{}{Empty.}
{104}{}{There are cables and connectors in this box. Why would you need them?}
{105}{}{What a cunning plan!}
{106}{}{Really, leave the box alone.}
{107}{}{This is gonna be a glorious victory over the turrets! You tie the cable with one end to the trolley with the cylinders, and put the other into the switchgear in the hallway. Then you slightly open the cylinder valves and push the cart. All that's left is to give it a little charge.}
{108}{}{Perform these simple actions.}
{109}{}{Leave.}
{110}{}{You attach the cable to the gas cylinders. All that's left is to give it a little charge.}