{100}{}{This skill won't help you here - this lock is beyond difficult.}
{101}{}{It seems that ordinary explosives won't open this door.}
{102}{}{You see a very strong hermetic doors with electronic locks. Access card is required.}
{103}{}{Phew! Lucky save!}
{104}{}{Something blocks the lock.}
{105}{}{You see hermetic doors.}
{106}{}{Picking locks won't help you this time.}

{110}{}{AAAAHHHA-HA-HA-HA!!! Welcome to our apartments, mister! Sorry that we are not in uniform, there's nothing to put it on! Maybe mister could tickle us with a feather, hmm?}
{111}{}{What the... A talking head?! Are you... Alive?}
{112}{}{Mister is IDIOT!!! I'm not just a talking head! Before you is Mr. President himself! Where did this mister crawled from, if he can't distinguish the president from everyone else?!.. What, my precious? Out of ass?!!! My precious, you should learn some manners!}
{113}{}{Well, that's new.}
{114}{}{What are you saying, my precious?! Yes, we agree. Such misters should be quartered. All who come out of ass must be exterminated!!!}
{115}{}{Are you sure about that?}
{116}{}{What? What does he say? He wants to scare us? Alright then. Let this citizen come out and lean on my ringer... I mean... I mean, my finger. What, my precious? I don't have a finger? Well... Then lean on my something. Let mister come out. We won't hurt him.}
{117}{}{You promise? Can I trust you?}
{118}{}{YES, YES, YES!!! We'll be good! Just let mister come closer! We haven't seen anyone in so long! We want to see mister!}
{119}{}{Hm...}

{120}{}{This door activates only in an emergency situations.}
{121}{}{Emergency back door. Obviously, activates only in an emergency situations.}
{122}{}{No use.}

{123}{}{This key card is not for this door.}
{124}{}{Not that.}
{125}{}{You can't do it during combat!}

#Женские реплики
{1110}{}{AAAAHHHA-HA-HA-HA!!! Welcome to our apartments, mister! Sorry that we are not in uniform, there's nothing to put it on! Maybe mister could tickle us with a feather, hmm?}
{1112}{}{Miss is IDIOT!!! I'm not just a talking head! Before you is Mr. President himself! Where did this miss crawled from, if she can't distinguish the president from everyone else?!.. What, my precious? Out of ass?!!! My precious, you should learn some manners!}
{1113}{}{Well, that's not what I meant...}
{1114}{}{What are you saying, my precious?! Yes, we agree. Such misses should be quartered. All who come out of ass must be exterminated!!!}
{1116}{}{What? What does she say? She wants to scare us? Alright. Let this citizen come out and lean on my ringer... I mean... I mean, my finger. What, my precious? I don't have a finger? Well... Then lean on my something. Let miss come out. We won't hurt her.}
{1118}{}{YES, YES, YES!!! We'll be good! Just let miss come closer! We haven't seen anyone in so long! We want to see miss!}
