{100}{}{This is the dripping tap.}
{101}{}{You see an ordinary sink. Drops of water are rarely falling from the tap. Looking at them somehow makes you want to sing.}
{102}{}{There's no more water in there!}

{103}{}{You turn the tap and fill the flask with clean water.}
{104}{}{After rigorous scientific analysis, you have come to the conclusion that you just need to turn the tap and fill the flask with water.}
{105}{}{You quietly turn the tap on and gather a flask of water, like you are about to be caught in the act.}
{106}{}{Demonstrating the wonders of lockpicking, you turn the tap and get the flask of water, although you can just turn the damn valve.}
{107}{}{Well, what the hell do you want from an ordinary sink?!}

{110}{}{Hey, that tap is leaking! Boo-hoo!}

#Новые тексты
{111}{}{Pure water is flowing in this tap, with virtually no restrictions on the amount.}
{112}{}{You fill a flask full of clean water.}