{100}{}{You see a punching bag.}
{101}{}{You see a punching bag. It's as if it invites you to try it out. You can almost hear "Don't miss the opportunity!" in your head.}
{102}{}{You can warm up your fists and try out new fighting techniques on this bag.}
{103}{}{Hmm, why not?}
{104}{}{The bag is so dilapidated that it's unusable after your training.}
{105}{}{This punching bag is useless.}
{106}{}{This punching bag could be useful for training your skills, but they are already too high.}
{107}{}{Training? I don't need it anymore...}
{108}{}{You spend two hours training and increase your unarmed skill by 5%.}
{109}{}{Good work!}