{100}{}{You see surveillance monitors.}
{101}{}{These surveillance monitors show different rooms of the vault.}

{110}{}{You see surveillance monitors displaying different rooms of the vault, corridors and public spaces.}
{111}{}{[Examine 2nd level]}
{112}{}{[Examine 3rd level]}
{113}{}{[Examine 4th level]}
{114}{}{[Leave]}

{120}{}{Second level contains living quarters and recreational areas. The rooms are an incredible mess, apparently not cleaned for years. At the end of the main corridor, near the elevator, the wall collapsed from the explosion.}
{121}{}{There are technical and service rooms on the third level, including the overseer's post and the power station.}
{122}{}{The fourth level is not monitored. The feeling of mystery and malice doesn't leave you.}
