{100}{}{You see a regular domesticated brahmin.}
{101}{}{The reason brahmin has two heads is because of early exposure to radiation on what used to be called a cow.}
{102}{}{You don’t notice anything unusual about the brahmin.}
{103}{}{Brahmin aren't very suitable for conversations.}
{104}{}{Don't you have something better to do than to sit around and talk to cattle?}
{105}{}{It's a brahmin. It has two heads.}

{201}{}{Mooo...}
{202}{}{Mooo Mooo Mooo...}
{203}{}{Mooo...}
{204}{}{Moooooo...}
{205}{}{Mooooooooo...}
{206}{}{::GRUNT::}