{100}{}{You see a caravan merchant.}
{101}{}{You see a caravan merchant. He looks very busy.}

{105}{}{You have failed the task of collecting things for the local caravan merchant - the group has already departed.}
{106}{}{Because of the death of the caravan merchant, completing the task to collect items is now impossible.}
{107}{}{Thanks for the help.}

#Äî êâåñòà
{110}{}{Huh? I don't have time to chat, I still have to run all over town before I can leave.}
{111}{}{If you need some help, I can help you.}
{112}{}{[Leave]}
{113}{}{Would be great. Okay, I've got a whole list of things I need to get before we hit the road. If you find them, I'll pay you a hundred bucks. Deal?}
{114}{}{Deal. Give me the list, I'll scan it with my Pip-Boy.}
{115}{}{No, running around looking for some junk is too boring. Goodbye.}
{116}{}{Great. Here. Try to get it done as quickly as possible. My caravan stays here for just another three days before moving out. If you're late, then we just leave and all your efforts will be for nothing.}
{117}{}{So, three days to collect things. I'll try to remember.}
{118}{}{Why don't you just walk on by? I don't want to have anything to do with people who have a reputation lower than a Brahmin's tail.}
{119}{}{Uh, okay.}

#Âî âðåìÿ êâåñòà
{120}{}{Oh, it's you. How is the mission going?}
{121}{}{Almost done. Only }
{122}{}{ items left to find. Wait a little more.}
{123}{}{I haven't started on it yet, but I keep it in mind. Will come back when I have everything.}
{124}{}{Job is done - here are the things you ordered.}
{125}{}{Okay. But remember - we're going soon. If you don't finish in time, you have only yourself to blame.}
{126}{}{Okay.}
{127}{}{Really? Wonderful! Here is the payment. Thank you, you helped me a lot.}
{128}{}{You're welcome.}

{129}{}{And yet something is missing. Check again.}
{130}{}{Hmm...}
