{100}{}{You see }
{101}{}{.}
{102}{}{You see a stagecoach administrator.}
{103}{}{You see a caravan merchant.}
{104}{}{We are always at your service, my dear!}

#Èìåíà íïñ:
{110}{}{Sentensa}
{111}{}{Blondie}
{112}{}{Tuco}
{113}{}{Tuco? What an unusual name... }
{114}{}{My full name is Tuco Benedicto Pacifico Juan Maria Ramirez. But I don't like to discuss my family.}
{115}{}{I'm sorry. Let's talk about something else.}
{116}{}{Okay, Tuco Bandito something-something, let's talk about something else.}

#Äèàëîã â Ðèíî, êîãäà ñòàë ïðèáëèæåííûì Áîëüøîãî Ëóè
{150}{}{I'm just going to say this: we don't need business from psychopaths like you. And you can tell Big Louie's other dogs the same thing!}
{151}{}{You'd better hope I don't find you out on the road... }
{152}{}{Fine. I don't need you anyway.}
{153}{}{I'll knock those words out of your mouth, along with your teeth! [Punch him in the jaw]}

{154}{}{[The stagecoach administrator falls flat on his back, spitting bloody teeth out onto the ground. Other stagecoach employees draw their guns.]}
{155}{}{[Stare them down.]}
{156}{}{[Attack!]}
{157}{}{}
{158}{}{[The administrator stands up unsteadily, wiping blood from his mouth, and holds up a hand to the others. They reluctantly holster their weapons.] I haven't been hit like that since my days in the ring! I'll let that go... But there's still no place for you on the stagecoach.}
{159}{}{You'd better watch your mouth next time.}

{160}{}{We've got nothing more to say.}
{161}{}{You know, there's respectable jobs for people who can punch like you. Better than being one of Louie's dogs.}
{162}{}{I'd better not see more of your gang up here... }
{163}{}{The Nevada Express doesn't deal with Big Louie or his dogs.}
{164}{}{Where am I going to find a dentist around here?!}

{165}{}{[The caravan merchant dodges the punch and pulls his gun. The others are doing the same. Let's hope that you are better shooter than brawler.]}
{166}{}{[Fight]}

#Ðèíî, êâåñò íà ïîèñê ïðîïàâøåé ïîñûëêè äëÿ ìîðìîíà
{170}{}{Tell me about the package your coach "delivered" to Patrick.}
{171}{}{We upheld the contract. The deal was to take the package to Reno, not to hand-deliver it to his door. The boy living in those slums across the street answered for it. If you want to track it down, look there, not here.}
{172}{}{I'll go check it out.}

#Äèàëîã, ñòàðòîâàÿ âåòêà:
{200}{}{Hello! Our valued customer! What? Not yet? Well, you will be! It's only a matter of time! Now, what can }
{201}{}{ of the Nevada Express help you with?}
{202}{}{Yes, how can I help you?}
{203}{}{What's the matter, buddy?}

{210}{}{Nevada Express? What's that?}
{211}{}{When's the next haul?}
{212}{}{I need to get somewhere.}
{213}{}{No, thank you, just passing by.}

#Ãîëîäèñê
{215}{}{Where do you get your stagecoaches?}
{216}{}{The Nevada Express maintains the wasteland's only fleet of functional intercity buses! Our talented engineers maintain them rigorously both here, in Salt Lake, and at our main depot in Las Vegas.}
{217}{}{I didn't think there were any functional vehicles left.}
{218}{}{I don't blame you! The Nevada Express may have the last working buses in the world. Some people will tell you a technician in Wind of War is fixing up an old pickup truck, but you shouldn't take them seriously. If he had anything, we'd already know.}
{219}{}{I see. Thank you.}

{220}{}{I could give you the full speech, but your time is valuable, am I right? I see you have a Pip-Boy, the mark of someone who has places to go and people to see! I'll give you this holodisk instead, so you can learn everything you need to know at your leisure!}
{221}{}{Well, you're right about one thing: I definitely don't have the time to listen to you. Fine, I'll take the holodisk.}
{222}{}{Thanks! I'll have a look at it later.}

{223}{}{The next sets out in }
{224}{}{ days. We leave on the 1st, 11th and 21st day of each month.}
{225}{}{That's all.}
{226}{}{I have another question... }
{227}{}{Today! But I think we still have a couple of seats left, if you want to buy a ticket!}
{228}{}{The next one's tomorrow! You'd better get your ticket quick, before every seat is sold out!}
{229}{}{ day. We leave on the 1st, 11th and 21st day of each month.}

#Çàêàç ïóòè
{230}{}{We'll get you where you need to go! If our caravans don't go somewhere, then you have nothing to do there.}
{231}{}{Can you drop me at New Reno?}
{232}{}{What about Salt Lake?}
{233}{}{Las Vegas awaits me!}
{234}{}{I need to visit the Cheyenne... }
{235}{}{I have some business in Wind of War... }
{236}{}{I need to get to Wendover.}
{237}{}{Can we make a stop at the Black Rock on the way?}
{238}{}{Will you get me to Gerlach?}
{239}{}{Actually, I have another question.}
{240}{}{Will you go back to Uranium City for me?}

{247}{}{I have a ticket. Let's go.}
{248}{}{Hey, this isn't the normal price! Why is it so expensive?}
{249}{}{Look, the caravaneers talk about you. You should be thankful we're letting you on the bus at all.}

{250}{}{Going to the big city? Just make sure you've got your gun loaded! We wouldn't want anything to happen to our valued customer! Speaking of which, that'll be }
{251}{}{ dollars for a ticket.}
{252}{}{You know, I represent the Nuka-Cola factory. If only your prices were lower, you could make a lot of money off of shipments... }
{253}{}{Oh, that's too bad. I was planning to make a lot of trips - business, you know - but that these prices, I don't know... }
{254}{}{Here's the money.}
{255}{}{I'll be back later.}

{256}{}{Then you're just in time. Take the ticket and climb aboard! We'll be leaving soon.}
{257}{}{Finally, I'm riding in style! Here's the money.}
{258}{}{Actually, never mind. I'll walk.}
{259}{}{I have another question before you set off.}

{260}{}{Hmm, I don't think so. Maybe you have a hole in your pocket!}
{261}{}{Huh, weird. I could have sworn I had it right here... }

{262}{}{You'll have to wait a little longer! We set off every 1st, 11th, and 21st of each month.}
{263}{}{I'll come when the time is right.}
{264}{}{Actually, I changed my mind. I want to go somewhere else.}

{270}{}{Salt Lake is a great place to make a home for yourself... If you don't have any trouble with the sheriff, anyway. That'll be }
{271}{}{ dollars.}
{272}{}{Hmm... Well, the Hawks put in a good word for you, so we'll take you for nothing, but just this once! We have to eat, you know, ha-ha-ha!}
{273}{}{What a pleasant surprise! I'm ready to go.}
{274}{}{Let's go!}
{275}{}{Going to make your fortune in the local casino? I'll keep my fingers crossed for our valued customer! That'll just be }
{276}{}{ dollars for the ticket.}
{277}{}{Really? Why would you - well, you're the valued customer! That'll just be }
{278}{}{ dollars.}
{279}{}{It's on the way, but I suggest you not stay there too long. I don't want our valued customer to have... Trouble... From the local soldiers. Anyway, that'll be }
{280}{}{ dollars!}
{281}{}{Black Rock? I've heard of it. Well, we pass close by there, so we take a detour. That'll just be }
{282}{}{ dollars.}
{283}{}{Sure, that's just on the way. A ticket is just }
{284}{}{ dollars.}
{285}{}{Well, our prices are set by... Ah... I really shouldn't do this, but alright. I can give you a ten percent discount, but that's all!}
{286}{}{Thank you!}
{287}{}{Yeah... Just don't tell anyone, okay?}
{288}{}{Then you're just in time. Take the ticket and climb aboard! We'll be leaving soon.}
{289}{}{You'll have to wait a little longer! We set off every 1st, 11th, and 21st of each month.}
{290}{}{Ah, they're making a name for themselves! It won't take us far out of our way. That will just cost you }
{291}{}{ dollars.}

#Äèàëîã î äåâóøêå ñ ôîòîãðàôèè Òåäà Áàíäè
{300}{}{Do you remember taking the girl in this picture on any of your coaches?}
{301}{}{Oh, I remember her! How could I forget? It's not every day we get to transport such delightful customers!}
{302}{}{Do you remember where she went?}
{303}{}{Hmm... Yes! It was Vegas! I remember, because it was unusual. Normally people plan a trip to Vegas carefully, but she ran up to us at the last moment. Most customers only do that if they're trying to get out without people knowing... Oh. [he suddenly looks alarmed and hands the photo back to you] I - I don't remember anything else.}
{304}{}{Don't worry, Tuco, that's all I need.}
{305}{}{No. [he shakes his head and hands the photo back] You can believe me, because I would have remembered such a beautiful customer.}
{306}{}{Too bad.}

#Íàïàäåíèå íà äèëèæàíñ
{310}{}{How reliable are your coaches?}
{311}{}{You have nothing to worry about, I promise you! In fact, I know what you're thinking of. The biker attack, right? Well, that was the first and last time! Believe me, you're safer on our coaches than you are walking around Reno.}
{312}{}{What biker attack?}
{313}{}{Fine, I believe you. For now.}

{314}{}{Oh, you don't know? One of our coaches was ambushed by bikers. Only two guards survived. But don't worry - they caught us by surprise once, but never again.}

{315}{}{What do you know about bikers?}
{316}{}{They're shiftless outlaws that can't live in the cities. They rob people of old technology whenever they can. I wish I knew where they sleep, so I could rid the wasteland of them!}
{317}{}{}
{318}{}{}
{319}{}{}

{320}{}{Bikers attacked our coach between Lovelock and Black Rock. They took everything and killed everyone but for two guards. They're the ones that told us everything.}
{321}{}{I'd like to know more about this story.}
{322}{}{Good to know. Bye.}

{323}{}{I wasn't on the rescue operation, so I don't know much myself. But I'll tell you what I can!}
{324}{}{Have you sent anyone to investigate?}
{325}{}{Where are the survivors?}
{326}{}{Why are you so sure that you were attacked by bikers?}
{327}{}{Okay, goodbye.}

{328}{}{The coach called for help over the radio, but before our rescue team could even reach the attack site, they ran into survivors running the other way. They told the rescue team everything as they returned to Reno.}
{329}{}{Two of the guards. They're off duty in the Silver Legacy's restaurant now, trying to recover from the shock. It'll be some time before I send them out again. I can't imagine how awful it must have been for them.}
{330}{}{The survivors told us so. We've always known the bikers are troublemakers, but now we know they're thieves and murderers as well! Frankly, it doesn't surprise me. They are the type that can't survive in lawful society.}
{331}{}{Do you have any evidence?}
{332}{}{Well... No, but no ordinary marauders could attack us and live. Each coach is well armored and staffed with a robot and several experienced guards. Only the bikers have the pre-war technology and vehicles to carry out this type of ambush.}
{333}{}{You lost an entire coach and didn't even investigate?!}
{334}{}{My men are professionals! I trust their word! If they say it was bikers, then I believe them, whether or not they have evidence. Now, if you want to convince me they're wrong - THEN I'll need evidence!}
{335}{}{Fine, I'll investigate it myself. I'll find proof one way or the other.}
{336}{}{Really? Well... I know our valued customers have to be sure! It's their discriminating tastes that bring them to the Nevada Express in the first place, after all! You should start with the head of the rescue team. He's on the second floor of the Silver Legacy right now.}
{337}{}{Fine.}

{338}{}{This is a terrible idea. I'm out of here.}
{339}{}{}

{340}{}{Once more about the attack on the stagecoach.}
{341}{}{Alright, but please know, there's no risk of this happening again. Next time, we shoot the bikers on sight. You can trust the Nevada Express with your safety!}
{342}{}{Where do I find the man that led the rescue operation again?}
{343}{}{It's just across the street on the second floor of the Silver Legacy. His room is near the stairs and he's wearing metal armor.}
{344}{}{}
{345}{}{}
{346}{}{Thanks, that's all.}

{347}{}{I know who really attacked the stagecoach.}
{348}{}{Oh?}
{349}{}{This holodisk from the attack site explains it. It wasn't the bikers. It was your people.}
{350}{}{Actually, I don't have the proof with me. Let me get back to you.}
{351}{}{What?! But - let me see. [he takes the holodisk, disappears into the office, and returns in a state of rage] Those scum! Those traitors! Those - those - I can't believe we were betrayed like this! We gave them honest work, status, everything a man could ask for, but it wasn't enough! They stabbed us in the back for - for MONEY! [he slams a fist into the wall] We'll have to respond.}
{352}{}{What are you going to do?}
{353}{}{That's internal business. Don't you worry about it. You... You've done a great service for the Nevada Express. We won't forget it. If you ever need us again, you can expect a substantial discount, as our thanks.}
{354}{}{Thanks. What do I tell the bikers?}
{355}{}{[He sighs] Please send them our apologies. I know it's not enough, but our reputation will suffer enough as it is when I tell my superiors about this. We can't afford anything more.}
{356}{}{I see. Well, good luck.}
{357}{}{Your investigation has earned you a 20% discount on Nevada Express services.}

# Female character
{1252}{}{You know, I represent the Nuka-Cola factory. If only your prices were lower, you could make a lot of money off of shipments... }
{1264}{}{Actually, I changed my mind. I want to go somewhere else.}
