{100}{}{You see an unemployed man.}
{101}{}{You see a restless man with nowhere to go and nothing to do.}
{102}{}{Don't worry about me. I'll be there in no time!}
{103}{}{This man could be useful. You should probably keep him in mind.}

{104}{}{You've found someone to operate the train in Salt Lake.}
{105}{}{You've found someone to operate the train. Now you can continue your mission.}

{110}{}{You need something?}
{111}{}{Who are you and what are you doing here?}
{112}{}{I need someone to help me operate a train. Are you interested?}
{113}{}{No, nothing.}
{114}{}{Right. See you.}
{115}{}{A train? Why not? At this point, I'll do anything, if you pay me. Uh, you will pay me, right?}
{116}{}{I'll pay you 1000 dollars for the whole job. Meet me in Salt Lake and I'll pay you then. Deal?}
{117}{}{Aww, where's your sense of adventure? Oh well, never mind then.}
{118}{}{That's too bad.}
{119}{}{Hey, if you know of anyone that's hiring, can you pass my name along? I'm good with my hands, and I'm not picky.}

{120}{}{}
{121}{}{I was on a caravan until it got raided. Now I'm just another street bum. I'd work for the sheriff, but he doesn't take out-of-towners. I'm just trying to get by, from day to day.}
{122}{}{I used to transport moonshine for one of the local brewers, but business is dangerous in Reno. His competitor smashed his stills and broke his legs. I thought I could make a profit at the casino - and lost everything. Now I'm trying to figure out what to do next. There's not a lot of options.}
{123}{}{Praying for a miracle, that's what. I've got debts to pay and I've just lost my job. I'm hoping to get by betting on the fights, but... Who am I kidding, I'm fucked. It's just a matter of time.}
{124}{}{That's what I'm trying to figure out! I've got no job and no prospects. I've got to do something before I get in over my head in debt, but where can I go? It's hard to get work in Vegas, and I can't live in the desert. I have no idea what to do.}
{125}{}{I've been out of work for weeks. I'm already up to my nuts in debt. I'm just hoping for a jackpot, because if I don't get some cash flowing soon... I don't even know what'll happen.}
{126}{}{First I lost my job. Then I lost my home. Then - my wife and kids... What's next? My mind, probably - I can't stop thinking about the uncertainty of future.}
{127}{}{I'll let you know when I figure that out. I used to do small runs in the ruins for locals, but lately, no one wants to deal with me. It's like they think I'm dangerous! Now I've got no way to support myself! I don't know what to do.}

{140}{}{Deal! Bring the money to the "Sixth Bullet" hotel. I'll be waiting!}
{141}{}{Okay.}
{142}{}{Deal! But how do I get to Salt Lake? I'd need to take the Nevada Express, and I've got no money for a ticket.}
{143}{}{Here's $1000. Go buy yourself a ticket.}
{144}{}{I have a ticket right here. Take it.}
{145}{}{Wait here. I'll think of something.}
{146}{}{I'll pay you 1000 dollars for a two-way trip. Deal?}
{147}{}{Great! When I get to Salt Lake, I'll check into the local hotel. Bring the money to my room. I'll be waiting!}

{1117}{}{Aww, where's your sense of adventure? Oh well, never mind then.}

