{100}{}{You see a caravaneer.}
{101}{}{You see a cute caravaneer girl.}

{110}{}{Hi there! Thanks to you, we decided to occasionally visit the Bridgeport to do some trading. So we'll give you a 5% discount.}
{111}{}{You're welcome.}

{112}{}{Hey! How are you doing, friend?}
{113}{}{Will you be in Bridgeport more often now?}
{114}{}{As long as there are customers. We'll be here every 15th of the month - resting for a couple of days, then hitting the road again. }
{115}{}{Show me your goods.}
{116}{}{That's it? Gee, that wasn't a real trade.}
{117}{}{Alright, I will leave you for now. See you around.}
{118}{}{Let's look at your stuff.}
{119}{}{We don't do business with the likes of you! Get lost!}

#Женские реплики
{1112}{}{Hey! How are you doing, friend?}
