{100}{}{You see a caravan master.}

#Попытка заговорить, когда ГГ стал врагом караванщиков (репутация "Проклинают")
{102}{}{Would you look at that, the death of a caravan merchant himself in front of me. You think I will shit my pants in fear? No. Forget it.}

{103}{}{I don't want anything from you. Bye.}

#Описание для караванщиков разных путей:
#Солт-Вегас:
{104}{}{You see a man with unwashed head. The badge on the shoulder reads: "Salt Lake - Las Vegas"}
#Солт-Рино:
{105}{}{You see a man, covered in road dust. The badge on the shoulder reads: "Salt Lake - New Reno"}
#Рино-Вегас:
{106}{}{You see a man, heavily tanned. The badge on the shoulder reads: "Las Vegas - New Reno"}
#Ветер Войны:
{107}{}{You see a tired man. The emblem on the shoulder identifies him as a master of the caravan.}

###############################################################
#       Случайные приветствия (первая реплика нпс)
###############################################################

{110}{}{Well, hello.}
{111}{}{Yes?}
{112}{}{Oh, a client!? How can I help?}
{113}{}{Did you came to talk business? Or just to waste my time?}
{114}{}{I'm listening... Hmm, who knows, maybe you have something useful to say?}
{115}{}{Can't wait you to tell me something nice. Like for example, something about free money. Ha-ha!}
{116}{}{Hey, I'm busy. So make it fast.}
{117}{}{[Sighs] Well, ok! Ask your stupid question already!}
{118}{}{Hello. What do you want?}
{119}{}{Hello. Wanna make 10 bucks? We don't have anybody to replace a brahmin... HA-HA-HA!!!}
{120}{}{Oh! Just when we need free labor! You're just in time!... HA-HA-HA!!!}

###############################################################
#       Расспросы про текущий город
###############################################################

{150}{}{I wanted to ask something about this city.}

#Ответы для каждого города:
{151}{}{Well there is not much to say? Nothing special. Not the best city in these parts.}

{152}{}{New Reno. City on a par with hell. There is even similar hierarchy here, from demons to devils. Devils are the local gangsters. You'd better stay away from these guys. You make a deal, you leave. Because even the Wasteland is safer then this!}
{153}{}{New Reno. City on a par with hell. Even has its own Devil, despite that not long ago there were two of them. Shortly speaking, you have to be careful here. The times city is having now are not the best. That's for sure.}
{154}{}{New Reno. City on a par with hell. And after someone put down two local bosses, it looks like everybody went nuts. Stay away from dark alleys. You can find big trouble on your ass. Easy!}

{160}{}{Las Vegas. City that is always lively and much safer than the rest. A great place to relax and trade.}
{161}{}{Las Vegas. City that is always lively and much safer than the rest. A great place to relax and trade... Except there is some strange business going on in it. Anyway, that's not our problem for now.}

{170}{}{Salt Lake. A big pile of shit. The filth and poverty is everywhere. Yet there is much more peaceful population, than in New Reno. At least here you can not to be afraid of a knife in the back.}
{171}{}{Salt Lake. Dirty city, yet there is much more peaceful population, than in New Reno. At least here you can not to be afraid of a knife in the back - and you can make a fine trade.}
{172}{}{Salt Lake. The city may be a little dirty, but if not for my work, it would be where I chose to settle down. You can't find a better place to live in the whole region. Everyone has a job and ways to make a living, without worrying about a knife in the back. Good place.}

{175}{}{Wind of War - it's a military settlement. These are people who consider themselves residents of paramount Wastes, blood rulers of this region, and everyone else - a cow for milking, from which they take whatever they want.}

{179}{}{Fine, let's go back a little.}

#Вопросы про город -- Рино:
{180}{}{Have you seen this girl from the photograph?}
{181}{}{[Studies the photograph] Cute... No, I don't think so.}
{182}{}{Okay. Another question.}
{183}{}{Forget it then. Bye.}

{184}{}{And if more detail - where you can go hang out, for example?}
{185}{}{Listen, I don't stay here for long myself, and I'm in no mood for parties after the road. I'm tired. You know, there is one caravan merchant around, retired, so to speak. His name is Ricky - The Musher. He stayed on the third floor in "Rainbow", it's across the street of "El Dorado". Go to him, buy him a drink, and he will tell you everything about the city. He knows a lot, believe me.}
{186}{}{Okay, but I have some other questions.}
{187}{}{I'll go to him then. Bye.}

{188}{}{Listen, did you happened to know a caravan merchant that... Well he looks like a dead man. He has burned skin, and his teeth are exposed...}
{189}{}{Ho-ho! You mean Harold?!! I haven't seen him in a long time. A good guy. Caravan merchants always loved him. Even half-dead, he is very entertaining.}
{190}{}{Does he come here often?}
{191}{}{Forget it. Another question.}
{192}{}{Fine, forget it.}

{193}{}{No, he always travels. They say, he looks for a place to settle down with people like him. Last time I have seen him on his way to Hub. It's very far, don't even ask, where is it.}
{194}{}{Right. Another question.}
{195}{}{Well fine. I think, I'll go now.}

#Вопросы про стоянку байкеров:
{196}{}{Do bikers ever come around here? Perhaps, you have seen them?}
{197}{}{They do come here, but rarely. Never staying for long. Hang out at the bar, beat someone up and leave in the morning. It's easier to meet them on the caravan routes, they like to race on their loud piles of metal there. Really impressive sights, by the way.}
{198}{}{Do you know if they have some regular place to camp? Where can they always be found, if needed to?}
{199}{}{If you would be a stranger, I would say I don't know. Bikers don't want everyone to know about their base. But since it's you asking, I will show it on your map...}
{200}{}{Show me.}
{201}{}{I don't know. Perhaps, someone else knows, someone who uses other trading routes.}
{202}{}{Another question then.}
{203}{}{Right here. This is the old ruins, their camp is somewhere on the outskirts, away from the road.}
{204}{}{Thank you! But I have questions left.}
{205}{}{Thanks, that is all, I needed.}
{206}{}{Even if I knew - I wouldn't tell. Not to just anyone, at least. I don't want any problems with them later.}

{207}{}{Yes! What a surprise. It's a waitress from the "Hard-Rock" cafe. She's a nice girl.}

#Вопросы по город -- Ветер Войны:
{210}{}{What are you doing here then? Why don't you leave?}
{211}{}{Well, they are not generally bloodthirsty. In the west wing of the station there is a doctor, merchant and a mechanic. It's their people. They are very useful, but charge high prices for their service. We, of course, need a mechanic, most of all. It can be hard without him. Although, he is often busy with his rotor friend in the garage.}
{212}{}{Er... "rotor friend"? What the heck is that?}
{213}{}{I don't know myself. But sometimes you can hear some buzzing and roaring from the garage, like sound of a running engine. They say, he is making a plane. Ha! If it is true, then it will be major news for our region!}
{214}{}{Hmm. Very, very interesting! Another question.}
{215}{}{Very interesting, but I have to go.}

#Вопросы про "Скоростного Ястреба" -- Ветер Войны и Вегас:
{216}{}{Have you heard anything about "Speed Hawk"? They say the guys were attacked by the raiders...}
{217}{}{I did. Everyone here already knows this story. Bad luck - to lose the merchandise and their people. Also they themselves scattered around. There was one of them somewhere here, looking for his people.}
{218}{}{There is one of them here? I should look for him...}
{219}{}{Have you seen anyone of the survivors from the "Speed Hawk"?}
{220}{}{I've seen one. The poor guy was wandering somewhere around here. But I think, he already left to Vegas. But you can ask people here, you may learn something.}
{221}{}{Right.}
{222}{}{Have you heard what happened to "Speed Hawk"?}
{223}{}{Yes, the guys were unlucky. It's a shame, it was a good caravan. I don't think they will find the rest of the guys. If they are lost, it means no one survived. Otherwise they would reach Vegas already.}
{224}{}{Yeah, sad story.}

#Вопросы про Лысого Максона -- Вегас:
{225}{}{Remind me, were you accompanied from New Reno to Vegas by a bald weirdo with a scar on his neck?}
{226}{}{No, nothing like this. I would remember.}
{227}{}{Damn, no luck.}
{228}{}{Wait a minute, I think, I've seen someone like this with another caravan. Ask around, you may find something about it.}
{229}{}{Okay!}
{230}{}{Wait a minute! There was a fella. I do not know his name, but he was with us from New Reno to Vegas, and was also bald. Where is he now I do not know. Probably having a good time in Clean City.}
{231}{}{Hmm, thanks! I should look for him there...}

#Вопросы про артезианский чип -- Солт-Лейк:
{232}{}{Do you know, where to get a filter for artesian tower in Salt Lake?}
{233}{}{If I knew, I would be already bathing myself in gold.}
{234}{}{Wow, okay.}

#Вопросы про город вцелом -- Солт-Лейк:
{235}{}{Is there any place here where you can go to relax?}
{236}{}{First have a look at the "Tin Angel". It's always fun there, very nice place. There is also a hotel, where you can rest, and even a trading hall across the street. There are two merchants there, one sells guns, and the other - all kinds of junk.}
{237}{}{What makes the city work anyway?}
{238}{}{The most important thing is a Nuka-Cola factory. If you want to start your own business, to sell this stuff in the Wasteland, then go straight in there. It's to the east from the center. But, in general, there is not much to do around, not many options... And yes, also, Vocas nuts grow here, very nutrient. There are a whole plantations, just outside the city.}
{239}{}{And what is the social situation in the city?}
{240}{}{They have Sheriff's office. The way I see it, they manage to keep the scum away. At least it is a lot safer here, than in New Reno.}
{241}{}{Right. That would be all.}
{242}{}{Wait, there is another place here to avoid. Just a friendly warning, because I see - you are a good person, you help our people. We always value that.}
{243}{}{Huh, tell me.}
{244}{}{Provo - a district to the south of the Salt Lake. We always stay away from it, because all of the scums, that were kicked out by the sheriff, gathered there. Thieves, murderers, maniacs - the whole package. Do not go there.}
{245}{}{Okay!}

{246}{}{Do you know anything about a place called Provo?}
{247}{}{I do. If I didn't, I would be dead a long time ago, because this district lays right on the trading route. All kind of scum lives there, people that have been kicked out by the sheriff. Dangerous bunch, stay away from that region.}
{248}{}{Got it.}

###############################################################
#       Расспросы про Пустошь
###############################################################

{290}{}{What kind of raiders are bothering you on the way?}
{291}{}{Well, first, in Provo region, the raids and ambushes on caravans became more frequent. They say, all kind of criminals gathered there, that ran off from Salt Lake City. Also, you might meet some crazy locals that forgot how to live peacefully. Watch out for them too.}
{292}{}{More?}
{293}{}{Another tough gang is making raids between Vegas and Salt Lake City, around the spot where the road turns to the west. The Bloom brothers are running the gang. There is not many of them, but they are real killers, very well armed and very experienced. Nobody really knows where they came from. Rumors say, it's the ex-soldiers from Wind of War, that took path of robbing and raiding. It must be them, otherwise, it's impossible to explain their top-notch equipment and an excellent understanding of how to fight.}

{294}{}{On the outskirts of Reno and Vegas there is always some small gangs waiting for you. The most famous ones are the Windmill people, the Caverners, the Sanders, the Bighorns and the Scorpions. Besides, to the south of highway there is a tribe of savages, they sometimes come down from the mountains to hunt people. Luckily, they don't have the guts to attack caravans, which can't be said about lone travelers.}
{295}{}{Savages?}
{296}{}{They are called Coyotes tribe, even though nobody know anything about them. We know for sure, that they are cannibals and that they are using weapons custom-made from the old farming technologies. They live high in the mountains, so nobody goes there. Some rare lucky ones happened to see roadblocks and abandoned camps of those animals. That is all that is known. Nobody cares about them, besides, maybe, the slavers.}

{300}{}{Tell me, how is it out there - in the Wasteland?}
{301}{}{It is harsh. We are forced to travel on the pre-war highways, because it's faster and more comfortable then to walk through the desert. But the raiders know about this, that's why when we are approaching gas stations and small settlements we are always on alert.}
{302}{}{Between which cities do you trade?}
{303}{}{So, most travelers are using that highways? I will have to remember that. Bye.}

{304}{}{What settlements have you seen on your travels?}
{305}{}{Right. That is all, I wanted.}

{306}{}{I trade between New Reno and Salt Lake.}
{307}{}{I trade between New Reno and Las Vegas.}
{308}{}{I trade between New Reno and Las Vegas. And here, in the Wind of War, we have a temporary stop.}
{309}{}{I trade between Las Vegas and Salt Lake.}

{310}{}{Can you show me, where is the second city?}
{311}{}{[Caravan merchant indicates location of final destination point of their caravan on the world map] Here.}
{312}{}{Thanks! But I have another question.}
{313}{}{Thanks! That's exactly, what I needed.}

{314}{}{That New Reno. Can you show it on the map?}
{315}{}{I'm interested in Salt Lake. Can you show it on the map?}
{316}{}{Las Vegas? Very interesting, Can you show it on the map?}

{317}{}{The location of New Reno have been marked on your Pip-Boy.}
{318}{}{The location of Salt Lake City have been marked on your Pip-Boy.}
{319}{}{The location of Las Vegas have been marked on your Pip-Boy.}
{320}{}{Can you show me those cities?}
{321}{}{We trade in many places. But for now we are settled here.}

{322}{}{Another question.}
{323}{}{I think, that is everything I wanted to ask.}

{324}{}{Almost all of population is living in cities, not in a desert. Besides caravans and raiders you can rarely meet anyone else on the road.}

{325}{}{On my way you can't find anyone, except some tribe natives.}
{326}{}{Tell me, what tribe?}
{327}{}{Indian tribe. Good people, if you don't mind excessive distrust to outsiders. You can trade a lot of food off them. But honestly, many are afraid to come to them, because the Big Louie gang is also settled there.}
{328}{}{Can you show the location on the map?}
{329}{}{The location of Lovelock have been marked on your Pip-Boy.}
{330}{}{[Caravan merchant indicates the location of the settlement Lovelock on the world map, waypoint on his caravan route] Right here.}

{331}{}{This is pretty active trading route, because Las Vegas and Reno established a good trading relationship. Besides, there is a waypoint in the middle, where you can rest and get some food.}
{332}{}{What waypoint?}
{333}{}{This is pretty active trading route, because Las Vegas and Reno established a good trading relationship. Besides there is a Wind of War on the way, where you can rest from the road.}
{334}{}{Wind of War? A military town. Soldiers are in charge there. To be frank, not the best place for a stop, the locals can be a pain in the ass sometimes. But still, it's better to rest there, than to risk it in the desert.}
{335}{}{Can you show me where is it?}
{336}{}{The location of Wind of War, the settlement, located in the middle of a trading route, have been marked on your Pip-Boy.}
{337}{}{[Caravan merchant indicates the location of the Wind of War on the world map, a waypoint in the middle his trading route] Here.}
{338}{}{This is pretty active trading route, because Las Vegas and Reno established a good trading relationship. You can even meet local population on that way.}
{339}{}{This is pretty boring trading route. When approaching Salt Lake, you have to be careful, because of the acid geckos. But in comparison with other routes it's the safest one. The main problem is, perhaps, the slavers. But raiders are seen very rarely.}

###############################################################
#       Расспросы, куда путь держат
###############################################################

{340}{}{Where are you heading?}

{341}{}{See this badge? Next time, just read it more carefully... We are heading to New Reno, to trade with local dealers, and then we will hang out at "El Dorado", hell yeah!}
{342}{}{See this badge? Next time, just read it more carefully... We are heading to Salt Lake, to restock on merchandise, then back here, to sell it.}
{343}{}{See this badge? Next time, just read it more carefully... We are heading to Las Vegas, to restock on merchandise, then back here, to sell it.}
{344}{}{See this badge? Next time, just read it more carefully... We are heading to New Reno, to trade with local dealers, and then we will hang out at "El Dorado", hell yeah!}
{345}{}{Nowhere for now. We will stay here for a couple of days, to rest. Then we'll head out to Vegas, to restock on merchandise.}
{346}{}{See this badge? Next time, just read it more carefully... We are heading to Las Vegas, to trade. In Vegas is still left some good equipment and the water is clean there, and Salt has less food problems and, of course, Cola!}
{347}{}{See this badge? Next time, just read it more carefully... We are heading to Salt Lake, to trade. In Vegas is still left some good equipment and the water is clean there, and Salt has less food problems and, of course, Cola!}
{348}{}{Nowhere for now. We have to rest, gear up, and then we'll head out.}

{349}{}{Can I accompany your caravan on its travels?}
{350}{}{No, don't even think about it. We are full. And we don't like accepting strangers, it's unsafe.}
{351}{}{Shame. But I have another question.}
{352}{}{That's a shame. I'll go, ask someone else.}
{353}{}{Right, but I would like to ask something about the city.}
{354}{}{Fine, forget it.}

{359}{}{The caravan route to Bridgeport is opened.}
{360}{}{Bridgeport needs some things. Here is the list. Will you take the order?}
{361}{}{Yes, seems like it can be a good deal. It's on our way anyway.}
{362}{}{Great. You can handle this without me from now on.}
{363}{}{I would be interested, if not for your reputation.}
{364}{}{[Leave]}
{365}{}{Honestly speaking, even in this difficult time for us, this contact doesn't looks serious. We will have to go too far, and the payoff is not that much. It may even cost us. Too risky.}
{366}{}{I can promise you a good deal. My reputation among caravan merchants will back that up.}
{367}{}{It's a shame I'm not a caravan merchant, because losing a good caravan route is just stupid.}
{368}{}{Either you risk it, or someone else will. Your call.}
{369}{}{You won't pull that trick on me.}

###############################################################
#       Продажа ядер-колы в Ветре Войны
###############################################################

{400}{}{The wind of War is ready to trade cola, but I need a supplier. Are you up for it?}

{401}{}{Ha! Are you out of your mind?! You want our guys to be involved with that scum?! More likely a radscorpion will bite off its tail, than you'll see one of us working for those bloodsuckers.}
{402}{}{As you wish, but I have another question.}
{403}{}{Wow, I see you have tense relations with them. I will do without you then.}

{404}{}{Wind of War? No, we take a different route.}
{405}{}{Shame, but I have another question.}
{406}{}{Ok, have it your way.}

{407}{}{Admirable. But what this has to do with us? We have a totally different route, we run between Vegas and Salt Lake.}
{408}{}{}
{409}{}{You're out of your mind! How are we going to transfer cola from Salt Lake to such far region?! We don't know those parts anyway, none of us been there before.}
{410}{}{To be honest, it's not a bad idea. Tell me only one thing, who will supply us? Resellers are too expensive - you will lose all customers with such prices, believe me.}
{411}{}{There is a caravan from Salt Lake. Everything has been set with them. Straight delivery from Salt Lake and you will transfer the merchandise from Vegas to Wind of War.}
{412}{}{Can't you transfer it from Salt Lake yourself?}
{413}{}{No, the journey is too long. But we can take it from someone in Vegas, and then, on our way to Reno, we can stop at Wind of War. That would be the best.}
{414}{}{This means, I have to arrange the supply from Salt Lake to Vegas first? Oh my, this is going to be tough.}
{415}{}{Excellent! I like the terms. Who will pay us?}
{416}{}{A merchant in Wind of War, the one you will be supplying.}
{417}{}{Okay. And you... Ehmm, you're saying, that you're an official representative? Can I see the papers?}
{418}{}{No problem! Here's the license. Sighed and sealed. Everything is in order.}
{419}{}{I don't have them on me.}
{420}{}{Okay! We can move out right now.}
{421}{}{Great! Let me tell you the details, and you're on your own after that...}
{422}{}{Well, prove, that you can be trusted, and we will make a deal. I can't risk here.}
{423}{}{Is this so important?! Damn, fine, I'll go look for that paper...}
{424}{}{On the other hand, screw the formalities. [mumbles to himself] Why should we care... [speaks to you] I agree.}
{425}{}{Good! Let me tell you the details, and you're on your own after that...}

{426}{}{You have successfully set Nuka-Cola trading route to Wind of War. The only thing left is to seal the deal with the intendant.}

###############################################################
#       Продажа ядер-колы в Вегасе
###############################################################

{450}{}{I'm establishing a Nuka-Cola trading spot in Vegas, and I need a supplier. Will you take the job?}
{451}{}{Because a caravan is needed, the one that could transfer cola straight to Vegas to another caravan, which would transfer it further to Wind of War. You get the point?}

{452}{}{Our own delivery line? Great idea, if you have a client there. Besides we are moving on that route anyway.}
{453}{}{Our own delivery line? Hmm! Good idea, if you have a client there. But we have another route planned. On unknown route and so far... No. No, guys won't accept such deal.}
{454}{}{Too bad. Another question.}
{455}{}{Too bad. I'll go look for someone else.}

{456}{}{Yes, there is a trading spot, and not a bad one. So? Will you take the job?}
{457}{}{Great idea! Go on, tell me the details, to whom we are taking the merchandise?}
{458}{}{Here's how it goes...}
{459}{}{Great idea, it's just that, err, do you have the papers for it? Can I have a look?}
{460}{}{You can. Here's the license.}
{461}{}{The license is not on me right now. Is this so important?}
{462}{}{Hmm. You know, you're right. Why do I care, the merchandise is merchandise and the buyer is ready on the spot. Go on, tell me the details.}
{463}{}{Okay, now listen...}
{464}{}{The guys must be sure there won't be any set-ups, do you understand? So, prove it first, that you can be trusted, then we can have a deal.}
{465}{}{Oh, what the hell! Even the money doesn't convince him! Urgh, fine, we'll see what we can do here.}
{466}{}{Now that's is a deal! The papers are fine, and the business is thought through! Go on, tell me the details, I'm ready to collaborate.}
{467}{}{Okay, now here's how it goes...}
{468}{}{You organized your own supply line of Nuka-Cola to Las Vegas! The only thing left is to seal the deal with the buyer.}

{469}{}{Sounds tempting. But I will risk only when we discuss the details with the Cola factory and get the guarantees, that you won't set us up. Then I won't even need your license. So, I'll meet you in Salt Lake - then we talk business.}
{470}{}{Hmm. Well, as you wish. But I have a question.}
{471}{}{Okay. Be seeing you in Salt Lake then.}

###############################################################
#       Продажа ядер-колы в Нью-Рино
###############################################################

{480}{}{A supplier of Nuka-Cola from Salt Lake to Reno is needed. Are you in?}

{481}{}{If we would be in Salt Lake, then yes. But until we are here, we can't risk it. There, in Salt Lake, we can go straight to the factory and discuss all the details, to have guarantees from many uncertainties.}
{482}{}{Before I head out to Salt Lake, I would like to ask another question.}
{483}{}{Hmm. This means, the caravans in Salt Lake can take the deal? Great! Then I'll go to Salt Lake.}

{484}{}{Not a bad idea. And the factory is not far from here. I'm already counting the profit.}
{485}{}{So it's a deal?}
{486}{}{Wow, pal, we are taking a different route, we never been in those parts. Sorry.}
{487}{}{Right. Still, I have a question.}
{488}{}{Right. Well, good luck then.}

{489}{}{You organized your own supply line of Nuka-Cola to New Reno! Soon you'll become rich... Maybe.}

###############################################################
#       Продажа ядер-колы
###############################################################

{500}{}{I want to order a delivery to another city.}
{501}{}{Good idea! But, we are moving only on our own route. And, of course, we will charge our percentage for the job.}
{502}{}{How much?}

{503}{}{ percent from the overall amount. Yes, by the way, how much do you have in the warehouse? I don't want to deliver small shipments - more complications, than profit. If you want to trade, let's load the full wagons!}
{504}{}{What?! 15% - or I'll find another caravan.}
{505}{}{You transfer 1000 bottles.}
{506}{}{You transfer 750 bottles.}
{507}{}{You transfer 500 bottles.}
{508}{}{You transfer 300 bottles.}
{509}{}{You transfer 200 bottles.}
{510}{}{You transfer 100 bottles.}
{511}{}{I will think about it.}

{512}{}{Good. Where are we taking it?}
{513}{}{"Cotton" cafe in New Reno.}
{514}{}{"Silver" restaurant in New Reno.}
{515}{}{"Hard Rock" cafe in Vegas.}
{516}{}{Trading store in Wind of War.}
{517}{}{Nowhere yet. I still have to make a deal with the buyer.}

{518}{}{No problem. We will deliver the stuff and take }
{519}{}{ percent from the total amount of bottles. I hope this is not our last deal.}
{520}{}{Good, start working!}

{521}{}{Hey, we are taking another route. I don't think that our team would want to move in completely unknown direction. Ask those, who is heading in Reno.}
{522}{}{Ok, maybe you can take the Cola to another city then?}
{523}{}{Then I don't need your service. Bye.}
{524}{}{Hey, we are taking another route. I don't think that our team will want to move in completely unknown direction. Ask those, who is heading in Vegas.}

{525}{}{ or nothing! No decent caravan is gonna work to less.}
{526}{}{Damn, I wouldn't want to lose such a deal... Fine! }
{527}{}{ percent - and we're in business. This is our final price.}

#Female character:
{1150}{}{I wanted to ask something about this city.}
{1228}{}{Wait a minute, I think I've seen someone like this, with another caravan. Ask around, you may find something about it.}
{1305}{}{Right. That is all I wanted.}
{1323}{}{I think that is everything I wanted to ask.}
{1353}{}{Right, but I would like to ask something about the city.}
{1462}{}{Hmm. You know, actually you're right. Why do I care, the merchandise is merchandise and the buyer is ready on the spot. Go on, tell me the details.}
{1409}{}{You're out of your mind! How are we going to transfer Cola from Salt Lake to such far region?! We don't know those parts anyway, none of us been there before.}
{1486}{}{Wow, gal, we are taking a different route, we never been in those parts. Sorry.}
