{100}{}{You see a caravan merchant.}
{101}{}{You see a leader of the caravan.}

{110}{}{What took you so long? I was starting to think I wouldn't get the chance to thank you. So, uh... Thank you? Hell, I'm no good at this.}
{111}{}{You're welcome.}

{112}{}{Hey, listen. We're gonna stick around for a little while, then head back to Reno. You're welcome to join us, if you're interested - always good to have an extra gun. You'll have to travel light though, we carry enough extra weight as it is.}
{113}{}{Hey there, son! How are you?}
{114}{}{Before you leave, I wanted to ask...}
{115}{}{Can you take me with you to New Reno?}
{116}{}{Did you do any trading on the way to Black Rock?}
{117}{}{I'll leave you alone for now. See you.}
{118}{}{No problem. I know I can trust you.}

{119}{}{We won't stay long before we head back to Reno. You need anything, you'd better tell me now.}

{120}{}{Yeah?}
{121}{}{How often will you come to Black Rock?}
{122}{}{Why did you travel so far?}
{123}{}{How did the raiders trap you?}
{124}{}{I want to ask you something else.}

{125}{}{We come here every 10th of the month, rest up a few days, then move out to the course. It's good, that this place is here - for a long time, there was nowhere decent to rest this far north.}
{126}{}{Gecko skins, that's why! Can't keep wearing pre-war clothing forever, you know. It's time for Nevada to update its wardrobe, and this year it's leather, leather, leather. It's a good time to be a gecko hunter, especially if you can take on the golden ones.}

{127}{}{We were coming up from Reno to pick up some gecko skins. Coming up on the mountains, something didn't feel right. We busted out the binoculars to find, lo and behold, the raiders hadn't even put out their campfires. Pure amateur hour, I said to myself. Fortunately, I knew a cave that cut right through the side of the mountain. We'd just have to take the caravan through it and out the other side, and the raiders'd never even know we were there. Clever me, huh?}
{128}{}{What next?}
{129}{}{Turns out they knew about the cave too. Fuck, I walked right into it! Just after we passed through, they detonated the cave behind us and sealed off the tunnel. I don't know if they planned it that way, or just got lucky, but it doesn't really matter now.}

{130}{}{You seem like a decent man. Why not? But you better travel light - no more than 35 pounds. Anything more than that and you'll slow us down. We're going to Reno, but I can drop you at Lovelock if you want. Ready to go?}
{131}{}{Yes, drop me off at Lovelock.}
{132}{}{Yes, let's go straight to Reno.}
{133}{}{Not right now. I want to ask you something else.}
{134}{}{No problem! Soon we'll finish up here and head back. But we can't let you slow us down. Travel light - no more than 35 pounds.}
{135}{}{Great, let's go.}
{136}{}{I have to take care of something first. I'll be right back.}
{137}{}{I need to dump some weight first. I'll be right back.}
{138}{}{Aw, why are you bringing all that shit for? I told you, we can't let you slow us down dragging that crap around. Cut your equipment down to 35 pounds, then come back.}
{139}{}{Fine.}

{140}{}{Yeah, and it'd be nice to unload some of it. You want to trade?}
{141}{}{Let's see what you've got.}
{142}{}{That's it? Eh.}
{143}{}{Look, I would, but... You have not the best reputation around here. Kind of makes it hard to trust whatever you've got to trade, you know?}
{144}{}{Look, I would, but... There's talk going around the caravans about a guy who just happens to look a lot like you. Bad, BAD talk. That sort of thing makes a man nervous, you know? Like, maybe your deals aren't on the up-and-up.}
{145}{}{Look, I would, but... You've got kind of a reputation, you know? And it's not the kind that makes me want to trust whatever you've got to trade.}

#Поправля'ь здоровье
{150}{}{Sorry for the question, but - what did you eat while you were trapped?}
{151}{}{We had a few supplies left, but those didn't last long. We got water off the walls of the cave and ate any radscorpions or rats we could find in there. You can't be a trader without at least a few survival skills.}
{152}{}{Can you teach this skill to someone? Me, for example?}
{153}{}{Hell yeah, I can. Sit down by the campfire and I'll give you all my favorite wasteland recipes.}
{154}{}{[Sit down by the campfire...]}
{155}{}{The caravaneer taught you how to properly cook food on the campfire.}

#Female character
{1113}{}{Hey there, girl! How are you?}
{1130}{}{You seem like a decent woman. Why not? But you better travel light - no more than 35 pounds. Anything more than that and you'll slow us down. We're going to Reno, but I can drop you at Lovelock if you want. Ready to go?}
{1144}{}{Look, I would, but... There's talk going around the caravans about a girl who just happens to look a lot like you. Bad, BAD talk. That sort of thing makes a man nervous, you know? Like maybe your deals aren't on the up-and-up.}
