{100}{}{Caravaneer.}

#Случайное описание
{101}{}{You see one of the caravaneer.}
{102}{}{You see one of the caravaneer. He's a little on edge.}
{103}{}{You see one of the caravaneer. He's nervous.}
{104}{}{You see one of the caravaneer. It seems that he had not slept for a long time.}

#Попытка заговорить
{110}{}{Hello.}
{111}{}{What do you need? Don't you see I'm busy...}
{112}{}{Look, I'm tired, so find someone else to talk with, alright?}
{113}{}{Find our boss - he makes all the decisions, not me.}
{114}{}{You need to discuss this with our boss.}

#Попытка заговорить при отрицательной репутации у караванщиков
{120}{}{Er... Look, why don't you talk about it with someone else?}
{121}{}{Er... You know, our caravan is all set. So goodbye.}
{122}{}{Er... We don't need the likes of you.}
{123}{}{You asking again?! Trying to provoke us?}
{124}{}{Hey, why don't I just shoot you?}
{125}{}{Listen, could you just leave me be, alright?}

#Караванские фразы:
{200}{}{::whistles::}
{201}{}{I won't go camping this time.}
{202}{}{Time to ditch this job.}
{203}{}{Some said that in Washington locals worship an unexploded bomb. What an idiots!}
{204}{}{Drinking local water is a bad idea. Geiger counter goes wild on it.}
{205}{}{Brahmin traders in Vegas raised prices again.}
{206}{}{Two weeks from Redding - a hard and difficult path.}
{207}{}{A month ago visited San-Francisco. Ruins all over the place.}
{208}{}{Vegas sure as hell will become the new capital of America!}
{209}{}{Salt Lake City - good town, but dirty.}
{210}{}{Reno is, perhaps, the most dangerous city I've ever seen.}
{211}{}{A few of my friends moved to Reno a week ago, and now they feed the worms.}
{212}{}{Reno is a nice city - kill someone, and no one will notice.}
{213}{}{Shouldn't be staying for too long - trade and hit the road again.}
{214}{}{Sometimes roads between towns are less dangerous, than towns themselves.}
{215}{}{I wouldn't want to live here.}
{216}{}{Good thing I'm just passing through.}
{217}{}{New caravan service option - pull the brahmin's tail... Ha-ha-ha!}
{218}{}{Need to collect water supplies. Where is the nearest well?}
{219}{}{Dust storms are malignant. Get knocked off your feet.}
{220}{}{At night, we drove to Reno - looks ominous!}
{221}{}{The Paradise City? The one up the north? A myth, of course.}

#Вегас, плавающие фразы, когда рабы из загона освобождены:
{300}{}{Lots of people running out of city. Who are they?}
{301}{}{Did you notice how much of folk just leaves the city?}
{302}{}{A lot of immigrants recent days...}
{303}{}{There are too many people wanting to accompany caravans these days.}
{304}{}{Who are these migrants? Aren't they runaway slaves?}
{305}{}{Word on a street, that slavers lost their slave consignment.}
{306}{}{So this is what behind people's income...}
{307}{}{Where are all these migrants from?}
{308}{}{Who are all these city fugitives?}
{309}{}{We're don't need more company.}
