{100}{}{You see a caravan master.}

#Ïîïûòêà çàãîâîðèòü, êîãäà ÃÃ ñòàë âðàãîì êàðàâàíùèêîâ (ðåïóòàöèÿ "Ïðîêëèíàþò")
{102}{}{Would you look at that, the death of a caravan merchant himself in front of me. You think I will shit my pants in fear? No. Forget it.}

{103}{}{I don't want anything from you. Bye.}

#Îïèñàíèå äëÿ êàðàâàíùèêîâ ðàçíûõ ïóòåé:
#Ñîëò-Âåãàñ:
{104}{}{You see a man with unwashed head. The badge on the shoulder reads: "Salt Lake - Las Vegas"}
#Ñîëò-Ðèíî:
{105}{}{You see a man covered in road dust. The badge on the shoulder reads: "Salt Lake - New Reno"}
#Ðèíî-Âåãàñ:
{106}{}{You see a heavily tanned man. The badge on the shoulder reads: "Las Vegas - New Reno"}
#Âåòåð Âîéíû:
{107}{}{You see a tired man. The emblem on the shoulder identifies him as a master of the caravan.}

###############################################################
#       Ñëó÷àéíûå ïðèâåòñòâèÿ (ïåðâàÿ ðåïëèêà íïñ)
###############################################################

{110}{}{Well, hello.}
{111}{}{Yes?}
{112}{}{Oh, a client! How can I help?}
{113}{}{Did you come to talk business? Or to just waste my time?}
{114}{}{I'm listening... Hmm, who knows, maybe you'll say something useful.}
{115}{}{Can't wait for you to tell me something nice. Like something about free money, for example. Ha-ha!}
{116}{}{Hey, I'm busy. Make it fast.}
{117}{}{[Sighs] Well, okay! Ask your stupid question!}
{118}{}{Hello. What do you want?}
{119}{}{Hello. Wanna make 10 bucks? We need someone to replace a Brahmin... HA-HA-HA!!!}
{120}{}{Oh! Just in time! We needed some free labor!... HA-HA-HA!!!}

###############################################################
#       Ðàññïðîñû ïðî òåêóùèé ãîðîä
###############################################################

{150}{}{I wanted to ask something about this city.}

#Îòâåòû äëÿ êàæäîãî ãîðîäà:
{151}{}{What's there to say? It's nothing special. Not the best city around these parts.}

{152}{}{New Reno. City on par with hell. There's even a similar hierarchy here, from demons to devils. Devils are the local gangsters. You'd better stay away from these guys. You make a deal, you leave. Even the Wasteland is safer than this!}
{153}{}{New Reno. City on par with hell. Even has its own Devil, despite that not long ago there were two of them. In short, you have to be careful here. Now's not the best time to be in this city, that's for sure.}
{154}{}{New Reno. City on par with hell. And after someone put down two local bosses, it looks like everybody went nuts. Stay away from dark alleys. You can easily get a lot of trouble on your ass.}

{160}{}{Las Vegas. A city that is always lively and much safer than the rest. A great place to relax and do some trading.}
{161}{}{Las Vegas. A city that is always lively and much safer than the rest. A great place to relax and do some trading... Except there are some strange things going on. But that's not our problem.}

{170}{}{Salt Lake. A big pile of shit. The filth and poverty is everywhere. Yet the population is more peaceful than in New Reno. At least you don't have to be afraid of being stabbed in the back.}
{171}{}{Salt Lake. Dirty city, yet the population is more peaceful than in New Reno. At least here you don't have to be afraid of being stabbed in the back - and you can make a fine trade.}
{172}{}{Salt Lake. The city may be a little dirty but, if not for my work, it would be where I'd settle down. You won't find a better place to live in the whole region. Everyone has a job and way to make a living, without worrying about being stabbed in the back. A good place.}

{175}{}{Wind of War. A military settlement. These are people who consider themselves residents of paramount Wastes, blood rulers of this region, and everyone else - a cow for milking, from which they take whatever they want.}

{179}{}{Fine, let's go back a little.}

#Âîïðîñû ïðî ãîðîä -- Ðèíî:
{180}{}{Have you seen the girl in this photograph?}
{181}{}{[Studies the photograph] Cute... No, I don't think so.}
{182}{}{Okay. Another question.}
{183}{}{Forget it then. Bye.}

{184}{}{Let me be more specific - where can you go hang out around here, for example?}
{185}{}{Look, I won't stay for long and I'm in no mood to party after the road - I'm tired. There is one caravan merchant you can ask about all of this. He's... retired, so to speak. His name is Ricky, Ricky The Musher. He rents a room on the third floor at "Rainbow", it's across the street from "El Dorado". Get him something to drink and he'll tell you everything about the city. He knows it better than anyone, believe me.}
{186}{}{Okay, but I have other questions.}
{187}{}{I'll go to him then. Bye.}

{188}{}{Did you happen to know a caravan merchant that... Well... looks like a dead man? He has a burned skin, and his teeth are exposed...}
{189}{}{Ha! You mean Harold?!! I haven't seen him in a long time. He's a good guy, caravan merchants love him. Even half-dead, he is very entertaining.}
{190}{}{Does he come here often?}
{191}{}{Forget it. Another question.}
{192}{}{Fine, forget it.}

{193}{}{No, he always on the road. They say he's looking for a place to settle down with people like him. Last time I saw him, he was on his way to Hub. It's very far, don't even ask where it is.}
{194}{}{Right. Another question.}
{195}{}{Well fine. I think, I'll go now.}

#Âîïðîñû ïðî ñòîÿíêó áàéêåðîâ:
{196}{}{Do bikers ever come around here? Have you met them?}
{197}{}{They do come here, but rarely. Never stay for long. They usually hang out in the bar, beat someone up, then leave in the morning. It's easier to meet them around the caravan routes, where they like to race their loud piles of metal. A real spectacle, by the way.}
{198}{}{Do you know if they have some regular place to stay? Where they can always be found, if someone needs them?}
{199}{}{If you were a stranger, I'd say that I don't know. Bikers don't want everyone to learn about their hideout. But since it's you, I can mark it on your map.}
{200}{}{Show me.}
{201}{}{I don't know. Perhaps, someone else knows, someone who walks other trading routes.}
{202}{}{Another question then.}
{203}{}{Right here. These are old ruins, their camp is somewhere on the outskirts, off the road.}
{204}{}{Thank you! But I have some questions left.}
{205}{}{Thanks, that is all, I needed.}
{206}{}{Even if I knew - I wouldn't tell. Not to just anyone, at least. I don't want any problems with these guys later.}

{207}{}{Yes! What a surprise. It's a waitress from the "Hard-Rock" cafe. She's a nice girl.}

#Âîïðîñû ïî ãîðîä -- Âåòåð Âîéíû:
{210}{}{What are you doing here then? Why don't you leave?}
{211}{}{Well, it's not that they're particularly bloodthirsty. In the west wing of the station there's a doctor, a trader, and a mechanic. They can be of use, but they charge rather high prices for their services. We, of course, mostly need the mechanic. Can't do much without him. Although, he's often busy with his rotor friend in the garage.}
{212}{}{Uhh... "rotor friend"? What the heck is that?}
{213}{}{I don't know exactly. But sometimes you can hear some buzzing and roaring near the garage, similar to the sound of a running engine. Some say he is making a plane. Ha! If this is true, it's gonna be major news around here!}
{214}{}{Hmm. Very, very interesting! Another question.}
{215}{}{Very interesting, but I have to go.}

#Âîïðîñû ïðî "Ñêîðîñòíîãî ßñòðåáà" -- Âåòåð Âîéíû è Âåãàñ:
{216}{}{Have you heard anything about the "Speed Hawk"? Some say the guys were attacked by raiders...}
{217}{}{I did. Everyone here have already heard this story. To lose both product and people at the same time is bad luck. Those who's left must be scattered around. I saw one of them recently, looking for his own.}
{218}{}{One of them is here? I should go look for him...}
{219}{}{Have you seen any survivors of the "Speed Hawk"?}
{220}{}{I saw one. The poor guy was wandering around. I think he's gone to Vegas by now. But you can ask people here, maybe you'll learn something.}
{221}{}{Right. Thanks.}
{222}{}{Have you heard about what happened to "Speed Hawk"?}
{223}{}{Yes, the boys got extremely unlucky. A shame, it was a good caravan. I don't think they'll find the rest of the guys. If they didn't show up by now, that means none of them survived. Otherwise they would have made it to Vegas by now.}
{224}{}{Yeah, sad story.}

#Âîïðîñû ïðî Ëûñîãî Ìàêñîíà -- Âåãàñ:
{225}{}{Remind me, were you accompanied from New Reno to Vegas by a bald weirdo with a scar on his neck?}
{226}{}{No, nothing like this. I would remember.}
{227}{}{Damn, no luck.}
{228}{}{Wait a minute! I think I've seen someone matching this description with another caravan. Ask around, maybe you'll learn something.}
{229}{}{Okay!}
{230}{}{Wait a minute! There was one fella. I do not know his name, but he traveled with us all the way from New Reno to Vegas... And he was definitely bald. But I do not know where he went after that. Probably he's having a good time in Clean City.}
{231}{}{Hmm, thanks! I should look for him there...}

#Âîïðîñû ïðî àðòåçèàíñêèé ÷èï -- Ñîëò-Ëåéê:
{232}{}{Do you know, where to get a filter for artesian tower in Salt Lake?}
{233}{}{If I knew, I would be bathing in gold.}
{234}{}{Wow, okay.}

#Âîïðîñû ïðî ãîðîä âöåëîì -- Ñîëò-Ëåéê:
{235}{}{Is there any place here where you can go to relax?}
{236}{}{First, the Tin Angel. A very nice place, always fun to visit. There's also an inn where you can rest, and even a trading post across the street. There are two vendors there, one selling weapons and the other all kinds of junk.}
{237}{}{What makes the city run?}
{238}{}{The most important thing around here is the Nuka-Cola factory. If you want to start your own business and sell this stuff around the Wasteland, go straight there. It's to the east from the city center. But in general there is not much to do, not many options... Ah, yes, people also grow Vocas nuts. They are very nutritious. You can find whole plantations just outside the city.}
{239}{}{What about the social situation in the city?}
{240}{}{They have a Sheriff's office. As you can see, they manage to keep the scum away. At least it's a lot safer here than in New Reno.}
{241}{}{Okay. That would be all.}
{242}{}{Wait, there is one more place around here you should know about. Just a friendly warning, because I see that you are a good person who helps people. We appreciate such things.}
{243}{}{Huh, okay. Tell me.}
{244}{}{Provo. It's a district to the south of the Salt Lake. We steer clear of it because all the criminals that the Sheriff kicked out are probably gathered there. Thieves, murderers, maniacs - the whole package. Do not go there.}
{245}{}{Okay.}

{246}{}{Do you know anything about a place called Provo?}
{247}{}{I do. If I didn't, I would be dead for a long time already, because most of the trading routes go right through this district. All kinds of scum are gathered there. There are people that have been kicked out by the Sheriff. A dangerous bunch. Stay away from that region.}
{248}{}{Got it.}

###############################################################
#       Ðàññïðîñû ïðî Ïóñòîøü
###############################################################

{290}{}{What kind of raiders are bothering you on the road?}
{291}{}{Well, for one thing, there's been an increase in raids and ambushes on caravans in the Provo area. They say all kinds of criminals from Salt Lake City congregate there. In addition, you may encounter crazy locals who have forgotten how to live peacefully. Be careful with them as well.}
{292}{}{Anything else?}
{293}{}{Another tough gang raids between Vegas and Salt Lake City, about where the road turns west. The Bloom Brothers gang. There aren't many of them, but they are real killers, very well armed and very experienced. No one really knows where they came from. Rumor has it that they are former soldiers from Wind of War, who turned to plundering and raiding. It must be true, otherwise it is impossible to explain their top-notch equipment and excellent understanding of how to fight.}

{294}{}{Around the outskirts of Reno and Vegas there is always some small gang waiting for you. The most famous ones are the Windmill people, the Caverners, the Sanders, the Bighorns and the Scorpions. Besides, to the south of highway there is a tribe of savages. Sometimes they come down from the mountains to hunt people. Luckily, they don't have the guts to attack caravans, which can't be said about lone travelers.}
{295}{}{Savages?}
{296}{}{They are called Coyotes, even though nobody know anything about them. We know for sure that they are cannibals and that they are using custom weapons made from the old agricultural tech. They live high in the mountains, so nobody goes there. Some were lucky to stumble upon abandoned camps of those animals. That is all that is known. Nobody cares about them, besides, maybe, the slavers.}

{300}{}{Tell me, how is it out there - in the Wasteland?}
{301}{}{It is harsh. We are forced to travel on pre-war highways because it is faster and more convenient than walking across the desert. But the raiders know this too, so we are always on guard when approaching gas stations and small settlements.}
{302}{}{Between which cities do you trade?}
{303}{}{So, most travelers are using the highways? I will remember that. Bye.}

{304}{}{What settlements have you seen on your travels?}
{305}{}{Right. That is all, I wanted.}

{306}{}{I trade between New Reno and Salt Lake.}
{307}{}{I trade between New Reno and Las Vegas.}
{308}{}{I trade between New Reno and Las Vegas. And here, in the Wind of War, we have a temporary stopover.}
{309}{}{I trade between Las Vegas and Salt Lake.}

{310}{}{Can you show me, where is the second city?}
{311}{}{[Caravan merchant marks the final destination point of their caravan on the map] Here.}
{312}{}{Thanks! I have another question.}
{313}{}{Thanks! That's exactly what I needed.}

{314}{}{That New Reno. Can you show it on the map?}
{315}{}{I'm interested in Salt Lake. Can you show it on the map?}
{316}{}{Las Vegas? Very interesting. Can you show it on the map?}

{317}{}{The location of New Reno have been marked on your Pip-Boy.}
{318}{}{The location of Salt Lake City have been marked on your Pip-Boy.}
{319}{}{The location of Las Vegas have been marked on your Pip-Boy.}
{320}{}{Can you show me those cities?}
{321}{}{We trade in many places. But for now we are settled here.}

{322}{}{Another question.}
{323}{}{I think, that is everything I wanted to ask.}

{324}{}{Almost all of population is living in cities, not in a desert. Besides caravans and raiders you can rarely meet anyone else on the road.}

{325}{}{On that way you won't find anyone except for some native tribe.}
{326}{}{What tribe?}
{327}{}{Indian tribe. Good people, if you don't mind some excessive distrust to outsiders. You can trade a lot of food off them. But honestly, many are afraid to come to them, because the Big Louie's gang is also settled there.}
{328}{}{Can you show the location on the map?}
{329}{}{The location of Lovelock have been marked on your Pip-Boy.}
{330}{}{[Caravan merchant indicates the location of the settlement Lovelock on the world map, waypoint on his caravan route] Right here.}

{331}{}{This is a pretty active trading route, because Las Vegas and Reno established a good trading relationship. Besides, there is a waypoint where you can rest and get some food.}
{332}{}{What waypoint?}
{333}{}{This is pretty active trading route, because Las Vegas and Reno established a good trading relationship. Besides there is Wind of War on the way. You can rest there.}
{334}{}{Wind of War? A military town. Soldiers are in charge. Honestly, not the best place to camp - the locals can be a pain in the ass sometimes. Still, it's better to rest there than to venture out into the desert.}
{335}{}{Can you show me where it's located?}
{336}{}{The location of Wind of War have been marked on your Pip-Boy.}
{337}{}{[Caravan merchant marks the location of the Wind of War settlement on the world map, a waypoint on his trading route] Here.}
{338}{}{This is a pretty active trading route because Las Vegas and Reno established a good trading relationship. You can even meet the local population on that route.}
{339}{}{This is a pretty boring trading route. You should be careful around Salt Lake, watch out for acid geckos. But compared to other routes, it's the safest one. The main problem is, perhaps, the slavers. But raiders are occasionally around there.}

###############################################################
#       Ðàññïðîñû, êóäà ïóòü äåðæàò
###############################################################

{340}{}{Where are you heading?}

{341}{}{See this badge? Next time read it more carefully... We are heading to New Reno, to trade with the local dealers, and then we will hang out at the "El Dorado". Hell yeah!}
{342}{}{See this badge? Next time read it more carefully... We are heading to Salt Lake, to restock on merchandise, then back here, to sell it.}
{343}{}{See this badge? Next time read it more carefully... We are heading to Las Vegas, to restock on merchandise, then back here, to sell it.}
{344}{}{See this badge? Next time read it more carefully... We are heading to New Reno, to trade with the local dealers, and then we will hang out at the "El Dorado". Hell yeah!}
{345}{}{Nowhere for now. We will stay here for a couple of days, to rest. Then we'll head out to Vegas, to restock on merchandise.}
{346}{}{See this badge? Next time just read it more carefully... We are heading to Las Vegas, to trade. In Vegas there is still some good equipment left and the water is clean there, and Salt Lake has less food problems and, of course, Cola!}
{347}{}{See this badge? Next time just read it more carefully... We are heading to Salt Lake, to trade. In Vegas there is still some good equipment left and the water is clean there, and Salt Lake has less food problems and, of course, Cola!}
{348}{}{Nowhere for now. We have to rest, gear up, and then we'll head out.}

{349}{}{Can I accompany your caravan on its travels?}
{350}{}{No, don't even think about it. We are full. And we don't like accepting strangers, it's unsafe.}
{351}{}{Shame. But I have another question.}
{352}{}{That's a shame. I'll go, ask someone else.}
{353}{}{Right, but I would like to ask something about the city.}
{354}{}{Fine, forget it.}

{359}{}{The caravan route to Bridgeport is opened.}
{360}{}{Bridgeport needs some things. Here is the list. Will you take the order?}
{361}{}{Yes, seems like it can be a good deal. It's on our way anyway.}
{362}{}{Great. You can handle this without me from now on.}
{363}{}{I would be interested, if not for your reputation.}
{364}{}{[Leave]}
{365}{}{Honestly speaking, even in this difficult time for us, this contact doesn't looks serious. We will have to go too far, and the pay is not that good. It may even cost us extra in the end. Too risky.}
{366}{}{I can promise you a good deal. My reputation among caravan merchants will back that up.}
{367}{}{It's a shame I'm not a caravan merchant, because losing a good caravan route is just plain stupid.}
{368}{}{Either you risk it, or someone else will. Your call.}
{369}{}{You won't pull that trick on me.}

###############################################################
#       Ïðîäàæà ÿäåð-êîëû â Âåòðå Âîéíû
###############################################################

{400}{}{The wind of War is ready to trade cola, but I need a supplier. Are you up for it?}

{401}{}{Ha! Are you out of your mind?! You want our guys to get involved with that scum?! More likely a radscorpion will bite off its tail than you'll see one of us working for those bloodsuckers.}
{402}{}{As you wish, but I have another question.}
{403}{}{Wow, I see you have tense relations with them. I will do without you then.}

{404}{}{Wind of War? No, we take a different route.}
{405}{}{A shame. I have another question.}
{406}{}{Okay, have it your way.}

{407}{}{Admirable. But what does this have to do with us? We walk a totally different route, between Vegas and Salt Lake.}
{408}{}{}
{409}{}{You're out of your mind! How are we going to transfer cola from Salt Lake to such a far region?! We don't know those parts anyway, none of us have been there before.}
{410}{}{To be honest, it's not a bad idea. Tell me though, who will supply us? Resellers are too expensive - you will lose all customers with such prices, believe me.}
{411}{}{There is a caravan from Salt Lake. Everything is set. Straight delivery line from Salt Lake. You will transfer the merchandise from Vegas to Wind of War.}
{412}{}{Can't you transfer it from Salt Lake yourself?}
{413}{}{No, the journey would be too long. But we can take it from someone in Vegas and then make a stop at Wind of War on our way to Reno. That would be the best option.}
{414}{}{Does this mean I have to arrange the supply from Salt Lake to Vegas first? Oh my, this is going to be tough.}
{415}{}{Excellent! I like these terms. Who will pay us?}
{416}{}{A merchant in Wind of War, the one you will be supplying.}
{417}{}{Okay. And... Ehmm, you're saying, that you're an official representative, am I right? Can I see the papers?}
{418}{}{No problem! Here's the license. Sighed and sealed. Everything is in order.}
{419}{}{I don't have them on me.}
{420}{}{Okay! We can move out right now.}
{421}{}{Great! Let me tell you the details, and you're on your own after that...}
{422}{}{Well, prove that you can be trusted, and we will make a deal. I can't take a risk here.}
{423}{}{Is this so important?! Damn, fine. I'll go look for that paper...}
{424}{}{On the other hand, screw the formalities. [mumbles] Why should we care... I agree.}
{425}{}{Good! Let me tell you the details, and you're on your own after that...}

{426}{}{You have successfully set a Nuka-Cola trading route to Wind of War. The only thing left is to seal the deal with the intendant.}

###############################################################
#       Ïðîäàæà ÿäåð-êîëû â Âåãàñå
###############################################################

{450}{}{I'm establishing a Nuka-Cola trading spot in Vegas, and I need a supplier. Will you take the job?}
{451}{}{Because a caravan is needed, the one that could transfer cola straight to Vegas, to another caravan, which would transfer it further to Wind of War. Get it?}

{452}{}{Our own delivery line? A great idea, if you have a client there. Besides, we are moving on that route anyway.}
{453}{}{Our own delivery line? Hmm! A good idea, if you have a client there. But we have another route planned. To set out on an unknown path, and quite a long one... No. My guys won't agree to that.}
{454}{}{Too bad. Another question.}
{455}{}{Too bad. I'll go look for someone else.}

{456}{}{Yes, there is a good chance to make some profit. So? Will you take the job?}
{457}{}{Great idea! Go on, tell me the details, where are we taking the merchandise?}
{458}{}{Here's how it goes...}
{459}{}{Great idea, it's just that, err, do you have the papers? Can I have a look?}
{460}{}{You can. Here's the license.}
{461}{}{The license is not on me right now. Is this so important?}
{462}{}{Hmm. You know, you're right. Why do I care, the merchandise is merchandise and the buyer is right there on the spot. Go on, tell me the details.}
{463}{}{Okay, now listen...}
{464}{}{The guys must be sure there won't be any set-ups, do you understand? Prove that you can be trusted first, then we can talk about a deal.}
{465}{}{Oh, what the hell! Even the money doesn't convince him! Urgh, fine, we'll see what we can do here.}
{466}{}{Now that's is a deal! The papers are fine and the business is thought through! Go on, tell me the details, I'm ready to collaborate.}
{467}{}{Okay, now here's how it goes...}
{468}{}{You organized your own supply line of Nuka-Cola to Las Vegas! The only thing left is to seal the deal with the buyer.}

{469}{}{Sounds tempting. But I will consider it only after we discuss the details with the Cola factory and get the guarantee that you won't set us up. Then I won't even need your license. So, I'll meet you in Salt Lake - then we talk business.}
{470}{}{Hmm. As you wish. But I still have some questions.}
{471}{}{Okay. Be seeing you in Salt Lake then.}

###############################################################
#       Ïðîäàæà ÿäåð-êîëû â Íüþ-Ðèíî
###############################################################

{480}{}{A supplier of Nuka-Cola from Salt Lake to Reno is needed. Are you in?}

{481}{}{If we would be in Salt Lake, then yes. But until we are here, we can't risk it. There, in Salt Lake, we can go straight to the factory and discuss all the details, to have guarantees from many uncertainties.}
{482}{}{Before I head out to Salt Lake, I would like to ask another question.}
{483}{}{Hmm. This means, the caravans in Salt Lake can take the deal? Great! Then I'll go to Salt Lake.}

{484}{}{Not a bad idea. And the factory is not far from here. I'm already counting the profit.}
{485}{}{So it's a deal?}
{486}{}{Wow, pal, we are taking a different route, we never been in those parts. Sorry.}
{487}{}{Right. Still, I have a question.}
{488}{}{Right. Well, good luck then.}

{489}{}{You organized your own supply line of Nuka-Cola to New Reno! Soon you'll become rich... Maybe.}

###############################################################
#       Ïðîäàæà ÿäåð-êîëû
###############################################################

{500}{}{I want to order a delivery to another city.}
{501}{}{Good idea! But we will move only on our route. And, of course, we will charge a percentage for the job.}
{502}{}{How much?}

{503}{}{ percent from the overall amount. By the way, how much do you have in the warehouse? I don't want to bother with small shipments - more complications than profit. If you want to trade, let's load full wagons!}
{504}{}{How much?! 15%, or I'll find another caravan.}
{505}{}{Transfer 1000 bottles.}
{506}{}{Transfer 750 bottles.}
{507}{}{Transfer 500 bottles.}
{508}{}{Transfer 300 bottles.}
{509}{}{Transfer 200 bottles.}
{510}{}{Transfer 100 bottles.}
{511}{}{I will think about it.}

{512}{}{Good. Where are we taking it?}
{513}{}{"Cotton" cafe in New Reno.}
{514}{}{"Silver" restaurant in New Reno.}
{515}{}{"Hard Rock" cafe in Vegas.}
{516}{}{Trading store in Wind of War.}
{517}{}{Nowhere. I still have to make a deal with the buyer.}

{518}{}{No problem. We will deliver the stuff and take }
{519}{}{ percent from the total amount of sold bottles. I hope this is not our last deal.}
{520}{}{Good, start working!}

{521}{}{Hey, we are taking another route. I don't think our team wants to go in a completely unknown direction. Ask those who are going to Reno.}
{522}{}{Ok, maybe you can take the Cola to another city then?}
{523}{}{Then I don't need your services. Bye.}
{524}{}{Hey, we are taking another route. I don't think our team wants to go in a completely unknown direction. Ask those who are going to Vegas.}

{525}{}{ or nothing! No decent caravan is gonna work to less.}
{526}{}{Damn, I wouldn't want to lose such a deal... Fine! }
{527}{}{ percent - and we're in business. This is our final price.}

#Female character:
{1150}{}{I want to ask about this city.}
{1228}{}{Wait a minute! I think I've seen someone matching this description with another caravan. Ask around, maybe you'll learn something.}
{1305}{}{Right. That is all I wanted.}
{1323}{}{I think that is everything I wanted to ask.}
{1353}{}{Right, but I would like to ask about the city.}
{1462}{}{Hmm. You know, actually you're right. Why do I care, the merchandise is merchandise and the buyer is right here on the spot. Go on, tell me the details.}
{1409}{}{You're out of your mind! How are we going to transfer Cola from Salt Lake to a region this far?! We don't know those parts anyway, none of us have been there before.}
{1486}{}{Wow, gal, we are taking a different route, we've never been to those parts. Sorry.}
