{100}{}{You see Super 8.}
{101}{}{You see a monster with a frightening look. On his forehead is a scorched inscription "Super 8", and in his eyes you see the hatred for all mankind.}
{102}{}{Deathclaw is embedded in your mind and you succumb to the intimidation.}
{103}{}{ succumbs to the intimidation by the gaze.}

{110}{}{(From the darkness quietly arises a terrible monster; his black eyes pierced you, you immediately catch yourself thinking that you are susceptible to this hypnotizing) W-wait, hu-man! I've been t-tracking you for a long time, to take your b-black heart out!}
{111}{}{Oh no, a talking animal! Be gone! Die!}
{112}{}{Wait, what are you talking about? Why do you have to hunt down and kill me?}
{113}{}{R-revenge! Revenge for my br-rothers and-sisters! They fell from your hand! You will die next!}
{114}{}{You mean those creatures in the vault? But they attacked me and other people!}

{115}{}{Grrr! I can't feel the evil in you, but you will still die! I can't for-rgive!}
{116}{}{Grrr! I can smell your b-black heart! It's poisoned, it destroys all that lives around you! Prepare to d-die!}
{117}{}{Well, you want a fight you got one, like everyone else. Come on, you overgrown turkey! Show me what you got!}
{118}{}{Uh-oh, got to run away from here...}

{119}{}{I'm sorry for what happened. I'm not asking you to forgive or understand. Your feelings... Your hatred... They are just. You have every reason to hate me. Take my life - I deserve it.}
{120}{}{[Surprised, he takes a step back] You're... Willing to give your l-life for justice?}
{121}{}{Yes. Look, I'm unarmed. Take my life as punishment.}
{122}{}{Stupid h-human!!! [waves his claw and abruptly stops it on the verge of your carotid artery] Grrr... [looks into your eyes] This cannot be... [lowers his paw and walks away]}
{123}{}{So, you forgive me?}
{124}{}{[Stops and looks sideways at you] NO! [then slips away like lightning in the darkness]}
{125}{}{Whew... This one will be hard to forget...}

{1120}{}{[Surprised, he takes a step back] You're... Willing to give your l-life for justice?}
