{0}{}{Small weapons}
{1}{}{Big weapons}
{2}{}{Energy weapons}
{3}{}{Unarmed}
{4}{}{Melee weapons}
{5}{}{Throwing}
{6}{}{First aid}
{7}{}{Doctor}
{8}{}{Sneak}
{9}{}{Lockpick}
{10}{}{Steal}
{11}{}{Explosives}
{12}{}{Science}
{13}{}{Repair}
{14}{}{Speech}
{15}{}{Barter}
{16}{}{Gambling}
{17}{}{Outdoorsman}

{18}{}{(Science + Repair + Gambling)}

{20}{}{Strength}
{21}{}{Perception}
{22}{}{Endurance}
{23}{}{Charisma}
{24}{}{Intelligence}
{25}{}{Agility}
{26}{}{Luck}
{27}{}{Max.CW}
{28}{}{Reputation}
{29}{}{Anatomic chemistry}
{30}{}{Karma}
{31}{}{Level}
{32}{}{Kills}
{33}{}{Age}
{34}{}{Fast shot}

{39}{}{Private detective}
{40}{}{Childkiller}
{41}{}{Cheyenne raider}
{42}{}{Grave robber}
{43}{}{Grave robber / Steal }
{44}{}{Caravans: Praised / Barter }
{45}{}{Karma 250 / Charisma 9 / Speech }
{46}{}{Sex appeal / Charisma }
{47}{}{}
{48}{}{Rep:Praised}
{49}{}{Rep:Caravans}

{50}{}{[}
{51}{}{] }
{52}{}{[Required: }
{53}{}{]}
{54}{}{; }
{55}{}{ / }
{56}{}{/}
{57}{}{ and }
{58}{}{[Chances: }

{60}{}{radiation, poison, addiction}
{61}{}{Addiction}
{62}{}{New Reno star}
{63}{}{Level 9 / Any combat skill}

{94}{}{.}
{95}{}{New location revealed on the map: }

{96}{}{ point(s).}
{97}{}{You lose karma }
{98}{}{You gain karma }
{99}{}{You got the coordinates of Area 51.}
