#Короткое описание:
{100}{}{You see a door.}
#Обычное описание:
{101}{}{You see an ordinary door.}
#Описание с подтекстом, возникает когда дверь заминирована:
{102}{}{You see an ordinary door. It almost says: Open me!}

#Получение урона:
{103}{}{The door is too tough to take down.}
{104}{}{The blow was not strong enough to take the door down.}
{105}{}{Door is obliterated.}
{106}{}{Did you really expect to pull this off with muscles like that?}

#Общие реплики при применении термита,
#которые используются у всех типовых сейфов
#(текст берется отсюда для SSRSeif, LISeif, NIEldSlf и пр.)
{107}{}{You don't have anything to light the thermite.}
{108}{}{It's no use}
{109}{}{The incredible heat melts through the locks like butter.}

#Использование двери и навыков
{110}{}{The door is locked.}
{111}{}{Locked.}
{112}{}{Careful, the door is trapped!}
{113}{}{Trap!}
{114}{}{Clear.}
{115}{}{You couldn't disarm the trap. Lucky for you, it didn't blow up.}
{116}{}{You disarmed the trap and placed it in your bag.}
{117}{}{Done}
{118}{}{Good job, you triggered the trap.}
{119}{}{Bad luck - the pin snapped.}

#Взлом двери
{120}{}{You locked the door.}
{121}{}{You unlocked the door.}
{122}{}{ experience points for cracking a tough lock.}
{123}{}{You couldn't unlock this lock.}
{124}{}{You receive }
{125}{}{ experience points.}
{126}{}{This is beyond your abilities.}
{127}{}{You don't have anything to light the thermite.}
{128}{}{It's no use}
{129}{}{The incredible heat melts through the locks like butter.}

#Навыки, сила
{130}{}{An Electronic Lockpick won't help, this is a mechanical lock.}
{131}{}{Lockpicks won't help, this is an electronic lock.}
{132}{}{Wrong lockpicks}
{133}{}{The door crumbles under your strength.}
{134}{}{Did you really expect to pull this off with muscles like that?}
{135}{}{Ugh!}
{136}{}{}
{137}{}{}
{138}{}{You can't just break this door down. You'll need a lot more force than that.}
{139}{}{The laser beam can't pierce through the door.}

#Минирование
{140}{}{No use}
{141}{}{This is pointless.}
{142}{}{This is pointless - the door is already trapped.}
{143}{}{Done}
{144}{}{You've trapped the door. Touching it again is probably a bad idea.}
{145}{}{Trapped}
{146}{}{Bad luck}
{147}{}{You couldn't install the trap.}
{148}{}{Thanks to your lack of expertise, the trap worked prematurely.}

{150}{}{You activated the alarm!}
{151}{}{Hey! What's going on!?}

{152}{}{This key doesn't fit.}
{153}{}{That's not it}
{154}{}{You can't set a trap on an open door.}
{155}{}{You completed Luciano's task.}

#Использование на двери Эрудиции (получение подсказок)
{160}{}{Conclusion: this door has a low level of difficulty.}
{161}{}{Conclusion: this door has a medium level of difficulty.}
{162}{}{Conclusion: this door has a high level of difficulty.}
{163}{}{Conclusion: this door has a super-tough level of difficulty.}
{164}{}{[Lockpicking required >}
{165}{}{]}

#Особые подробные описания
{200}{}{You see a tough warehouse door.}
{201}{}{You see an emergency exit from a pharmacy.}
{202}{}{You see a flimsy warehouse door.}
{203}{}{You see a gate to the slave pens.}
{204}{}{You see an armored door to the reactor.}
{205}{}{You see a strong warehouse door.}
{206}{}{You see hotel room numbered 26.}
{207}{}{You see hotel room numbered 14.}
{208}{}{You see hotel room numbered 7.}
{209}{}{You see a strong, heavy door, reinforced with metal. Breaking it down will be hard, to say the least.}
{210}{}{You see a very tough door reinforced with metal.}
{211}{}{You see a heavy, armored door to a weapon warehouse.}
{212}{}{You see a tough, electronic warehouse door.}
{213}{}{You see a tough garage door.}
{214}{}{You see a very tough gate to a bunker. The lock looks like it was changed recently.}
{215}{}{Hm. There must be some sort of bunker below. The lock is brand new.}
{216}{}{You see a standard Vault door.}
{217}{}{You see a hotel room numbered 15.}
{218}{}{You see a heavy duty hatch with a tough lock. It probably needs a special key.}
{219}{}{This is a *very* tough lock. There's probably a key for it somewhere nearby.}
{220}{}{You see a tough backdoor.}
{221}{}{You see a tough hangar door.}
{222}{}{You see an ordinary door. You can barely make out the number 9 on the surface.}
{223}{}{You see tough gates with electronic locks.}