{100}{}{No use.}
{101}{}{You cannot open this door.}
{102}{}{You must talk to that man over there first.}

#Для дверей в Вегасе на карте работорговцев
{103}{}{You see a boarded-up door.}
{104}{}{This door is firmly nailed to the doorpost.}

#Для дверей лифта на дамбе
{105}{}{You see the service elevator door.}
{106}{}{This elevator leads to the lower levels of the dam. There's nothing for you to do there.}

#Для дверей в Офисе Интерплей
{107}{}{You see an armored door.}
{108}{}{This door is heavily reinforced, it cannot be kicked out. There is a sign hanging above: "Spammers are not allowed!"}

#Для дверей в убежище 8
{109}{}{You see an elevator door.}
{110}{}{This elevator leads to the lower levels of the vault, but you don't have the code for the activation.}
