#Descriptions:
{100}{}{You see a safe.}
{101}{}{This is your personal safe with a code lock.}
{102}{}{You see a reinforced safe which can be used to store items.}
{103}{}{You see your personal safe.}

#Usage:
{104}{}{The safe has a mechanical code lock. It's locked, and you won't be able to open it while you can't hear anything.}
{105}{}{Not in combat!}
{106}{}{You didn't even leave a scratch.}

#Cracking
{107}{}{The safe has a mechanical lock consisting of 5 tumblers, each opened with its own number. You can try and guess the code, but that will take some time.}
{108}{}{[Crack the code.]}
{109}{}{[Not now.]}

{110}{}{[Pick the first digit of the code.]}
{111}{}{[Pick the second digit of the code.]}
{112}{}{[Pick the third digit of the code.]}
{113}{}{[Pick the fourth digit of the code.]}
{114}{}{[Pick the last, fifth, digit of the code.]}
{115}{}{0}
{116}{}{1}
{117}{}{2}
{118}{}{3}
{119}{}{4}
{120}{}{5}
{121}{}{[Leave the lock alone.]}

#Results
{122}{}{As you set the digit, you hear a quiet click.}
{123}{}{As you set the digit, you hear an ordinary click.}
{124}{}{As you set the digit, you hear a clear click.}

{125}{}{[Move on to the next number.]}
{126}{}{[Try to open the safe.]}
{127}{}{[Give up.]}

{128}{}{You've cracked the code! You turn the handle and the door swings open.}
{129}{}{For cracking the safe combination, you receive 500 experience and a personal safe to store your gear.}
{130}{}{Done.}

{131}{}{You turn the handle and }
{132}{}{ tumblers turn before locking back in place. The safe is still locked. It looks like you got }
{133}{}{ digits out of five right.}
{134}{}{[Try again.]}
{135}{}{Not even close. None of your digits were correct.}
{136}{}{You turn the handle and hear one tumbler move before locking back in place. The safe is still locked. It looks like you got 1 digit out of five right.}
{137}{}{For cracking the safe combination so quickly, you receive 700 experience as well as a personal safe to store your gear.}

#When receiving the "Infiltrator" perk
{138}{}{[Carefully examine the numbers for signs of wear.]}
{139}{}{Inspecting the safe lock, you see that the digits }
{140}{}{ and }
{141}{}{ show signs of repeated wear. They probably appear in the safe's combination.}