#Для спуска в канализацию с бассейном в Солте:
{100}{}{You'd better not go down into this muddy water.}
{101}{}{To dive into this cesspool?! No way!}

#Для ящиков на складах в Хоторне:
{102}{}{You have dashingly jumped over the fence using those boxes.}
{103}{}{You climbed on the roof using that big pile of boxes.}

#Для дамбы:
{104}{}{Looking at this huge station from this height, you decide that there is no point in going down for you.}
{105}{}{I have nothing to do there.}

#Для спуска с артезианской башни:
{106}{}{Because of the exhaustion, you couldn't hold it and fell down, breaking your legs.}
{107}{}{Because of your inattention, you stumbled and rolled down the stairs, breaking your legs.}
{108}{}{Because of your clumsiness, you slipped and rolled down like a ball, breaking your legs.}

#Для Ветра Войны:
{109}{}{You climbed to the roof of the building and then jumped to the ground.}
