{100}{}{Chryslus Motors articles were very helpful. You reduced the load on the car and slightly increased the speed and the trunk load limit.}
{101}{}{10 percent is serious!}
{102}{}{Now this magazine is useless.}
{103}{}{With this magazine you could improve your pickup truck quite nicely, but it requires a professional toolkit, which you don't have.}
{104}{}{I need a toolbox.}
{105}{}{With this magazine, you could improve your pickup truck quite nicely, but you need a professional toolbox and... The car itself.}
{106}{}{Your repair skills are not good enough.}
{107}{}{Something's unclear...}