{100}{}{You cannot use that in combat!}
{101}{}{Your repair skill is too low to understand this complex technology.}
{102}{}{The metal detector doesn't detect anything.}

{103}{}{The metal detector beeps, but you cannot determine the source of the metal.}
{104}{}{The metal detector beeps like crazy! But you can't find anything near you.}
{105}{}{For finding the stash you get }
{106}{}{ experience points.}
{107}{}{The metal detector detects something around }
{108}{}{ steps from you.}
{109}{}{}

{110}{}{So, what we have here?!}
{111}{}{Aha! Gotcha!}
{112}{}{Come on, baby, give me something good!}
{113}{}{Where are my millions, Miss Fortune?}
{114}{}{Ha! Now it's all mine!}
{115}{}{What was yours is now mine...}
{116}{}{Ha, the gold rush is back!}
{117}{}{I just hope it's small enough to carry...}
{118}{}{Not exactly a G.E.C.K., but pretty good nonetheless...}
{119}{}{Finders keepers!}
{120}{}{If only I had bigger backpack...}
{121}{}{Contact!}
{122}{}{I need more... MORE!}
{123}{}{What is it now?}
{124}{}{Let's see what's the catch...}
{125}{}{}
{126}{}{}
{127}{}{}
{128}{}{"Someone wants to go to space, but I want only richer face..." }
{129}{}{"You keep a lot of secrets, dirt... Digging you up won't hurt!"}

{130}{}{You have found a trap with the metal detector.}
{131}{}{The metal detector beeps, but you could not find a trap.}
{132}{}{Yes!}
{133}{}{The metal detector beeps like crazy, but you can't find anything.}

#Сообщения при поиске лаза в семейное убежище на Площади возрождения
{200}{}{You get the feeling you've found everything there is to find here.}
{201}{}{Under a thick layer of sand, covered by the time, you find the entrance to a bomb shelter.}
{202}{}{The metal detector beeps like crazy, but you don't see anything. Only a very experienced scavenger could find anything useful here.}
{203}{}{Don't see anything special... What could it be?}
{204}{}{If not for this metal detector, I'd never have found this hatch!}

#Сообщения при поиске спуска в канализацию Рино
{210}{}{Brushing aside the sand, gravel, and debris, you find an entrance into the sewers.}
{211}{}{Ugh! That stench could only be... A sewer!}
{212}{}{The metal detector beeps like crazy, but you don't see anything special.}
