{100}{}{You've already studied this work. Let the life be your teacher now.}

{101}{}{The author must have been mad.}
{102}{}{Scientific literature? Not for you!}
{103}{}{This monograph is aimed at qualified medics, you are unable to understand anything in it.}
{104}{}{This monograph is written in abstract scientific terms. Trying to to understand anything with your level of knowledge would be a bit overoptimistic.}
{105}{}{You lack the scientific knowledge necessary to make sense of this monograph.}

{106}{}{Wow, that was quite a lot of brain work!}
{107}{}{You learn a lot about medical practice, but no professional secrets are revealed by the monograph.}
{108}{}{You learn nothing new.}
{109}{}{To your own surprise you discover some secrets of human and animal anatomy. This would help you both in therapy and in combat.}
{110}{}{To your own surprise you discover some secrets of human and animal anatomy.}
