{100}{}{You cannot use that in combat.}
{101}{}{The radio can only be used from your hands.}

#Common
{110}{}{You hear nothing but static.}
{111}{}{Turn the radio off.}

#Cheating
{112}{}{Select your teleportation point. ( 133 Gerlach; 22 Black Rock; 18 Lovelock; 31 NPP; 54 Reno; 92 Uranium City; 51 Hawthorne; 6 Wind of War; 27 Area 51; 46 Vegas; 137 Salt; 12 Provo; 25 Bikers; 130 Gov. Vault. )}
{113}{}{Next.}
{114}{}{Prev.}
{115}{}{Follow the number on the map }
{116}{}{Next. 10}
{117}{}{Prev. 10}

#Slavers in Vegas
{120}{}{You get no signal through the concrete basement walls.}
{121}{}{Turn the radio off.}
{122}{}{[You hear ordinary slaver chatter, but nothing interesting.]}
{123}{}{Look out, a slave has escaped! He has a weapon!}
{124}{}{[Turn the radio off.]}
{125}{}{[The slavers can see you listening to the radio from here. You will have to leave the building or find somewhere quiet to do this.]}
{126}{}{[Turn the radio off.]}

#Lovelock, Cheyennes village
{130}{}{You hear the weak signal of the local radio station.}
{131}{}{Turn the radio off.}
{132}{}{Suddenly, you pick up a strange signal on an unusual frequency. It is very weak, but it gets stronger, the closer you get to its source.}
{133}{}{Try to locate the source of the transmission.}
{134}{}{The signal is loud and clear here, but it seems to be coded.}

#Wind of War
{140}{}{You hear ordinary patrol chatter, but nothing interesting.}
{141}{}{You get no signal through the thick vault walls.}
{142}{}{The mountain is blocking the signal.}

#Salt Lake, little vaults area
{150}{}{You pick up a weak signal. If you go }

{151}{}{south-west}
{152}{}{west}
{153}{}{north-west}
{154}{}{north-east}
{155}{}{east}
{156}{}{south-east}

{157}{}{, it gets stronger. As you near the source, you realize it's a distress signal.}
{158}{}{This could be interesting.}
{159}{}{You hear a clear signal. It sounds like Morse code. The source must be close by, but you can't see any transmitters.}
{160}{}{Hmm...}
{161}{}{You hear ordinary police chatter, but nothing interesting.}

#Black Rock
{180}{}{You pick up a faint signal through the static. It sounds like raiders.}
{181}{}{Follow the signal.}
{182}{}{Return to where the caravan was ambushed.}
{183}{}{You get no signal through the thick cave walls.}

#Reno, Silver
{200}{}{You can barely hear anything. It seems like the concrete hotel walls are blocking the signal.}
{201}{}{For some reason, the signal is stronger in these sewers.}
{202}{}{The radio signal is very strong. Suddenly, you see its source.}
{203}{}{How unexpected...}

#Nevada rangers outpost
{205}{}{}
{206}{}{}
{207}{}{}
{208}{}{You hear nothing but static.}
{209}{}{[Try to locate any sort of signal]}

{210}{}{[You finally get a voice through the static] This is Ranger Tycho. Who is this? Over.}
{211}{}{Hi, ranger Tycho. I'm a traveler who stumbled into an abandoned outpost in the mountains and found this radio and some codes lying around.}
{212}{}{An outpost in the mountains? That might be one of ours. You're free to use it, just don't break anything. Over.}
{213}{}{Well, I'll try.}
{214}{}{I'll be careful.}
{215}{}{Actually, I don't advise wandering around. There's nothing out here but us rangers. If anything happens, there's no help coming. Over.}
{216}{}{Are you saying it's safer to be close to civilization?}

{217}{}{Heh, you got me. The wastes are hostile and dangerous, even to the wary traveler. Tread with caution, and remember that everything you see and hear is a clue. Radiation and strange creatures will take their toll. But we know everything there is to know about survival. One can always adapt to his environment. Anything else, over?}
{218}{}{Why are you so scared of civilization?}
{219}{}{Can I meet you in person?}
{220}{}{What can you tell me about the rangers?}
{221}{}{Thanks for answering, friend. If we ever meet, the beer's on me.}

{222}{}{Scared? No, we're not easily scared. We just prefer the freedom of the wilds. We can find everything we need and stay independent. Over.}
{223}{}{I don't know. We travel a lot and don't like crowds. If we ever crossed paths, we'd probably keep to ourselves. Nothing personal. Over.}
{224}{}{You're that interested? I'm flattered. We're a small group, but we're well trained to live in the wild. Our ancestors lived here when the world burned to ashes and the cities were doing their best to finish off the survivors. "The war was a testament to human greed and stupidity," as our fathers told us. They lived in the wilds and took only what they need, and they passed it on to us. Sometimes we trade for ammunition, but personally, I depend on myself, not some piece of tech. Anything else, over?}
{225}{}{Heh. I'd prefer a strong stout, or perhaps a Nuka-Cola. Be careful out there. Over and out.}
{226}{}{[Turn the radio off.]}

#Freaks hotel
{230}{}{[You overhear some chatter on the radio.]}
{231}{}{[Listen]}
{232}{}{...What's the situation, over? [...] No incidents. Ghoul activity is very low. Over. [...] Continue surveillance. We have to catch them in the act. Over. [...] Continuing surveillance, over. [...] Boss, I'm starting to think the ghouls had nothing to do with it. What if we don't find anything? [...] Idiot, don't clog the frequency! We'll discuss this later. Davis's orders were clear - prove their guilt by any means necessary. If we don't find evidence, we'll create it. Copy? [...] Yes. Yes, sir. Won't happen again, s- Wait! I see someone near the hotel! They're holding a radio - I think they're listening in on us, sir! I'm abandoning the mission, over and out!}
{233}{}{Heh, stupid jerks.}

#Hoover Dam
{240}{}{[Scan the frequencies for any chatter.]}
{241}{}{Boss, do you hear me? [...] Yeah, what? [...] I don't want to carry all this. What if I leave it here and take it on my way back? [...] Fine, but if anyone finds it, I'm wiping that stupid smile off your face for good. [...] Don't worry, boss. Everything will be fine...}
{242}{}{Lucky for me, someone talks too much...}
{243}{}{[Compare the signal against the data on the drug dealer's holodisk.]}
{244}{}{You have found a secret frequency.}
{245}{}{[Follow the signal]}
{246}{}{}
{247}{}{}
{248}{}{}

#Cheating
{511}{}{Select operation.}
{512}{}{Select the point of teleportation. ( 133 Gerlach; 22 Black Rock; 18 Lovelock; 31 NPP; 54 Reno; 92 Uranium City; 51 Hawthorne; 6 The Wind; 27 Area; 46 Vegas; 137 Salt; 12 Provo; 25 Bikers; 130 Gov. Vault. )}
{513}{}{Next.}
{514}{}{Prev.}
{515}{}{Follow the map by the number }
{516}{}{Next. 10}
{517}{}{Prev. 10}
{518}{}{[Other options]}
{519}{}{}

{520}{}{+50 000$}
{521}{}{+10 000 experience points.}
{522}{}{Change sex.}
{523}{}{+50 infection points.}
{524}{}{Show infection points and etc.}
{525}{}{Give inventory to a car.}
{526}{}{Play 1 game month.}
{527}{}{[To main menu]}
