{100}{}{You see safe.}
{101}{}{You see a strong safe with a code lock.}

#individual description of safes
{102}{}{You see presidential safe.}
{103}{}{You see a wall safe made of a durable alloy with a complex electronic lock.}
{104}{}{You see a safe.}
{105}{}{You see a sturdy wall safe with a powerful lever locks.}

#safe usage
{200}{}{This strong safe easily resisted a powerful strike. It will resist all others.}
{201}{}{Closed}
{202}{}{Opened}
{203}{}{You easily open the safe with the code that the administrator gave you.}
{204}{}{For electronic locks you need a different kind of lockpicks.}
{205}{}{For mechanical locks you need a different kind of lockpicks.}

{206}{}{You've already cracked the safe.}
{207}{}{You did not manage to crack the lock on the safe.}
{208}{}{Done}
{209}{}{You successfully cracked the lock on the safe.}

#Science usage
{210}{}{Conclusion: This case has a lock with low lockpick difficulty.}
{211}{}{Conclusion: This door has a lock with medium lockpick difficulty.}
{212}{}{Conclusion: This door has a lock with high lockpick difficulty.}
{213}{}{Conclusion: This door has a lock with very high lockpick difficulty.}
{214}{}{[The amount of required lockpick skill is >}
{215}{}{]}

{220}{}{This safe is already opened.}