{100}{}{Your lack of skill has resulted in damage to the elements of the device. The lights have gone out - as it seems, for good.}
{101}{}{You successfully repaired this source of light.}
{102}{}{Your skill is insufficient to repair this device.}
{104}{}{Repair not required.}
{105}{}{You gain }
{106}{}{ exp. points.}
{107}{}{You fail to repair that.}
{108}{}{This source of light works impeccably.}
{109}{}{This source of light works irregularly. It can be repaired though.}
{110}{}{This source of light doesn’t work anymore.}
{111}{}{It cannot be repaired.}
