{100}{}{This thing should be used on a person.}
{101}{}{You get }
{102}{}{ experience points for testing mutagenic serum.}
{103}{}{That was... Witty.}
{104}{}{No need to dismember the corpse.}

{105}{}{You shouldn't have been waving a weapon in front of a victim!}
{106}{}{The victim noticed you too early.}
{107}{}{Your luck has left you.}
{108}{}{You can't do this during combat.}
{109}{}{What the hell are you doing!?}
{110}{}{Why are you so eager to die!?}
