{100}{}{A well with muddy water. But it is still cleaner than in most other places.}
{101}{}{Do you want to get something else from it?}
{102}{}{By disinfecting and boiling some dirty water from the well, you get some clean water.}
{103}{}{You already took water today, save some for the tribe!}
{104}{}{Mmm! Water!}
{105}{}{Wait a while, the water has not yet settled and is still muddy.}
{106}{}{The water isn't ready yet.}
{107}{}{I wish I knew how to purify water!}
{108}{}{You purified some water with disinfectant.}

{110}{}{You poisoned this well. Have you forgotten?}
{111}{}{Damn, the water's poisoned...}
{112}{}{You've already poisoned this well, and doing it again won't make any sense for a while.}
{113}{}{The water is already poisoned.}
{114}{}{You have poisoned the well, and now it is dangerous to drink from it. How wicked of you.}
{115}{}{The well is poisoned!}
{116}{}{You can't drink this water, it still has poison in it.}
{117}{}{No! Poisoned!}
{118}{}{A well with cloudy poisoned water. The water will be undrinkable for some time.}
{119}{}{You've poisoned the well of a very small settlement. The consequences of your actions are likely to be fatal.}
{120}{}{You gain experience for a non-violent expunging of an entire settlement.}
{121}{}{You don't have enough outdoorsman skills to purify the water.}
{122}{}{}
{123}{}{You need a container to store water.}
{124}{}{I need a vessel.}
{125}{}{Use containers to store water.}
{126}{}{This well is empty. Perhaps it will be filled sometime in the future.}
{127}{}{This well is dry.}
