{100}{}{}
{101}{}{Perhaps, you can scavenge something useful out of it.}
{102}{}{It is very unlikely you find anything useful in here.}
{103}{}{Damn it!}
{104}{}{This skill is useless here.}
{105}{}{Put it back inside? Oh no, this won't make the car running again.}

{110}{}{You found an intact fuel controller under the hood.}
{111}{}{You already took out everything you could from the Corvega.}
{112}{}{Your skills prevent you from finding anything useful in here.}

{114}{}{You took some leftover fuel out of the gas tank and made some Molotov cocktails.}
{115}{}{You took some scrap metal from under the hood. It will come in handy in repair.}
{116}{}{In a car door you found some forgotten money. }
{117}{}{You surprisingly found some 0.223 ammo in the back seat.}

{118}{}{This will come in handy.}
{119}{}{Yeah!}
{120}{}{Now there is *definitely* nothing useful.}
{121}{}{Hmm...}
{122}{}{You took out a microfusion battery.}
{123}{}{ bucks.}
