#Starting and typical dialogue options
{109}{}{You need both your hands free to use the workbench.}
{110}{}{You cannot use the workbench in battle.}
{111}{}{You can use this workbench to repair or improve items if you have the skills and materials.}
{112}{}{}
{113}{}{Leave.}
{114}{}{Get to work.}
{115}{}{Back to the list.}
{116}{}{End.}
{117}{}{Done.}
{118}{}{> Next list.}
{119}{}{< Previous list.}

#Assembly
{120}{}{Craft }
{121}{}{.}
{122}{}{, }
{123}{}{>=}
{124}{}{}
{125}{}{Materials: }
{126}{}{. Requirements: }
{127}{}{ (}
{128}{}{amount)}
{129}{}{Requirements: }

#Special options for "Savage 410"
{150}{}{What type of leather will you use for the bandolier?}
{151}{}{Use silver gecko pelt (2).}
{152}{}{Use golden gecko pelt (1).}
{153}{}{Use acid gecko pelt (1).}
{154}{}{Use leather jacket (1).}
{155}{}{Use reinforced leather jacket (1).}
{156}{}{Use homemade jacket (1).}
{157}{}{Use tattered raider jacket (1).}
{158}{}{Use silver gecko pelt (1).}

#Additional information to the console
{160}{}{You study the information about the amplifier, but eventually conclude it won't be of any use to you. You already have this ability.}
{161}{}{You've earned the "Empathy" perk.}
{162}{}{You treacherously crack the case and pocket $500, a pack of mentats and a Pip-Boy module. The owner probably wouldn't appreciate it.}
{163}{}{You break the ammunition down into }
{164}{}{ lead and powder components.}
{165}{}{You replace the broken radiometer in your Pip-Boy. Now you will always be able to tell the exact level of your radiation exposure by examining yourself in detail.}
{166}{}{You carefully study the instructions and improve your martial arts skills by } #I wasn't sure if this would be a bonus to Unarmed and Melee or just unarmed, so I kept it vague.

#Special options about repairing tattered jacket
{180}{}{You need more leather to restore this jacket.}

#Name of theassembling product + list of components
#(no comma at the end of list of components)
#(Each first line goes with a capital letter, the second one doesn't)

{200}{}{Upgrade the ammo press.}
{201}{}{ammo press (1), junk (1)}

{202}{}{Clean the rusty machete.}
{203}{}{rusty machete (1), flamer fuel (1), Rot Gut (1)}

{204}{}{Clean the rusty katana.}
{205}{}{rusty katana (1), flamer fuel (1), Rot Gut (1)}

{206}{}{Coin tokens to deceive Nuka-Cola machines (50).}
{207}{}{junk (1)}

{208}{}{Repair the mysterious blaster from Area 51.}
{209}{}{mysterious blaster (1), junk (1)}

{210}{}{Repair the 2043B radio.}
{211}{}{radio (1), junk (1)}

{212}{}{"Mickey's Revenge".}
{213}{}{"Mickey's Revenge" schematics (1), junk (1), toaster (1), slave collar (1)}

{214}{}{Clean the Old "Lucky" pistol.}
{215}{}{"Lucky" pistol (1)}

{216}{}{Bandolier for "Savage" shotgun.}
{217}{}{"Savage 410" shotgun (1), leather}

{218}{}{Disassemble dynamite.}
{219}{}{dynamite (1)}

{220}{}{Restore PLC.}
{221}{}{PLC (1)}

{222}{}{Break down the large-caliber ammunition from Hawthorne.}
{223}{}{ammunition crate (1)}

{224}{}{Gunpowder fuse.}
{225}{}{"Gunpowder fuse" schematic (1), ammunition remains (30), Rot Gut (1), flare (1)}
{225}{}{"Gunpowder fuse" schematic (1), ammunition remains (30), Rot Gut (1), flare (1)}

{226}{}{}
{227}{}{}

{228}{}{Hunting spear.}
{229}{}{knife (1), a wooden stake (1)}

{230}{}{Repair on-board computer of the train.}
{231}{}{on-board computer (1), junk (1)}

{232}{}{Debug and install sonar scanner on metal detector.}
{233}{}{metal detector (1), sonar scanner (1)}

{234}{}{Repair broken pool cue for Bertolini.}
{235}{}{cue (1), Bertolini cue (1)}

{236}{}{Place a bug on Bertolini's cue case.}
{237}{}{bug (1), Bertolini's cue (1)}

{238}{}{Remove the bug from Bertolini's cue case.}
{239}{}{Bertolini's cue (1)}

{240}{}{Repair damaged laser pistol.}
{241}{}{damaged laser pistol (1), junk (1)}

{242}{}{Repair broken microfusion cell.}
{243}{}{broken microfusion cell (1)}

{244}{}{Install empathy amplifier on your Pip-Boy.}
{245}{}{Pip-Boy empathy amplifier (1)}

{246}{}{Break the Hard Rock patron's business case.}
{247}{}{business case (1)}

{248}{}{Install armored plates on bulletproof vest.}
{249}{}{armored plates (1), vest (1). The vest's label reads: "Remove vest before modifying!"}

{250}{}{Repair Nelson's shotgun.}
{251}{}{Nelson's broken shotgun (1), junk (1), weapon parts (1)}

{252}{}{Remove the radiometer from the broken Pip-Boy 2000.}
{253}{}{broken Pip-Boy (1)}

{254}{}{Restore the damaged leather jacket.}
{255}{}{torn jacket (1), leather. The jacket's tag reads: "Remove jacket before modifying!"}

{256}{}{"Kubotan".}
{257}{}{"Kubotan" schematics (1), junk (1), kubotan key (10)}

{258}{}{Kubotan keys preparation: }
{259}{}{keys (1)}

{260}{}{Open the Hard Rock patron's business case.}
{261}{}{business case (1), tools (1)}

{262}{}{Craft armor from the Legendary Scorpion shell.}
{263}{}{Legendary Scorpion shell (1), golden gecko pelt (4)}

{264}{}{Decrypt the old holodisk.}
{265}{}{old holodisk (1)}

{266}{}{Produce 2mm EC ammunition.}
{267}{}{junk (2)}

{268}{}{Assemble 10mm gun out of spare parts.}
{269}{}{weapon parts (5)}
