#Ñòàðòîâûå è òèïîâûå îïöèè äèàëîãà
{110}{}{You cannot do that in combat.}
{111}{}{You can use this campfire to cook food or prepare chems if you have the ingredients and enough skill. Start by choosing a recipe.}
{112}{}{You can use this laboratory workstation to craft useful supplies if you have the ingredients and enough skill. Start by choosing a recipe.}
{113}{}{Leave.}
{114}{}{Get to work.}
{115}{}{Back to the list.}
{116}{}{End.}
{117}{}{I don't know any recipes yet.}

{118}{}{> Next list.}
{119}{}{< Previous list.}

#Èçãîòîâëåíèå
{120}{}{Make }
{121}{}{.}
{122}{}{You'll need: }
{123}{}{Done.}
{124}{}{End.}
{125}{}{The preparation is complete.}
{126}{}{You earn }
{127}{}{ experience points for crafting supplies at the campfire.}
{128}{}{ experience points for crafting supplies with the help of laboratory equipment.}

#Ðåöåïòóðà
{135}{}{To learn this recipe you need: Science }
{136}{}{ infection points.}
{137}{}{You have successfully learned this recipe.}

#Îïöèè öåíòðèôóãè
{140}{}{You need a Science skill of 25 to use this.}
{141}{}{The medical centrifuge is ready to use. What would you like to make?}
{142}{}{You must equip this device in order to use it.}

{148}{}{This bench belongs to its owner. You'll need permission to use it.}
{149}{}{Gather all the necessary vegetables in your backpack.}

##############################################################################
#
#                          Äëÿ Áëýê-Ðîê - êàðòà îñàäû
#
##############################################################################

{150}{}{The raider's pot of stew is still simmering on this fire. You have the opportunity to "fiddle with the spices".}
{151}{}{Use "Horsekiller" poison.}
{152}{}{Use radscorpion venom.}
{153}{}{Done. Now you only have to wait a little...}
{154}{}{End.}
{155}{}{The raiders should have already eaten the poisoned food by now.}
{156}{}{Poison the raiders' food.}
{157}{}{You need something poisonous.}
{158}{}{Radscorpion venom is usually injected, not ingested. You'll need about three tails to get the job done.}
{159}{}{Use three tails with radscorpion venom.}

##############################################################################
#
#                          Ëå÷åíèå ÎÇ
#
##############################################################################

{160}{}{Heal.}
{161}{}{You are already healthy.}
{162}{}{Eat food to heal }
{163}{}{ hit points.}
{164}{}{}
{165}{}{}
{166}{}{}
{167}{}{}
{168}{}{}
{169}{}{}

##############################################################################
#
#                          Ëå÷åíèå îò èíôåêöèè
#
##############################################################################

{170}{}{Treat your infection.}
{171}{}{Choose your treatment. Its effectiveness will be affected by your Doctor skill.}
{172}{}{Blood-purifier.}
{173}{}{Xander root powder.}
{174}{}{Xander root powder and disinfectant.}
{175}{}{Xander root powder, disinfectant and clean water.}
{176}{}{Nightshade berries and booze.}
{177}{}{Nightshade berries and a "Bloody Mary".}
{178}{}{Nightshade berries and an "Atomic Cocktail".}
{179}{}{Back.}

{180}{}{You lack the necessary ingredients.}
{181}{}{You healed }
{182}{}{ points of infection.}

##############################################################################
#
#                          Ñïèñîê ðåöåïòóð
#
##############################################################################

{190}{}{Study the "Root beer" recipe.}
{191}{}{Study the "Atomic Cocktail" recipe.}
{192}{}{Study the "Nuka-Cola Turbo" recipe.}
{193}{}{Study the stimpak recipe.}
{194}{}{Study the "Doctor's Bag" crafting instructions.}
{195}{}{Study the "Molotov Cocktail" crafting instructions.}
{196}{}{Study the "Caravaneer's meal" recipe.}
{197}{}{Study the "Mantis snack" recipe.}
{198}{}{Study the recipe for creating }
{199}{}{Study the recipe for creating }

##############################################################################
#
#                          Ñïèñîê èçãîòîâëåíèÿ
#
##############################################################################

{200}{}{Antidote.}
{201}{}{radscorpion tail (1)}

{202}{}{Healing powder.}
{203}{}{xander root (1), broc flower (1)}

{204}{}{Blood-purifier.}
{205}{}{nightshade berries (2), xander root (1), broc flower (1), clean water (1)}

{206}{}{Horsekiller poison.}
{207}{}{nightshade berries (2), radscorpion tail (2), empty syringe (1)}

{208}{}{Root beer.}
{209}{}{xander root (2), mutfruit (1), clean water (1)}

{210}{}{Vocas nut solution.}
{211}{}{vocas nuts (10), "Bloody Mary" (1), empty syringe (1)}

{212}{}{Atomic Cocktail (5).}
{213}{}{Nuka-Cola (5), booze (5), mentats (1)}

{214}{}{Turbo-Cola (3).}
{215}{}{Nuka-Cola (3), anti-smoking chems (1)}

{216}{}{Poisoned booze for El Dorado patrons (5).}
{217}{}{beer (5), radscorpion tail (1)}

{218}{}{Stimpaks for Stryker's chemicals (10).}
{219}{}{Stryker's chemicals (1), empty syringe (10)}

{220}{}{Stimpak.}
{221}{}{xander root (1), broc flower (1), clean water (1), empty syringe (1)}

{222}{}{Super Stimpak.}
{223}{}{stimpak (1), Nuka-Cola (1), mutfruit (1)}

{224}{}{Homemade RadAway.}
{225}{}{vocas nut solution (1), Blood-purifier (1), clean water (1)}

{226}{}{Doctor's bag.}
{227}{}{scalpel (1), silver gecko pelt (1), empty syringe (1), disinfectant (1), antidote (1), painkiller (1)}

{228}{}{Iguana meal.}
{229}{}{iguana-on-a-stick (2)}

{230}{}{Caravaneer's meal.}
{231}{}{mutfruit (1), jerky (1), brahmin milk (1)}

{232}{}{TV meal (+25 hit points).}
{233}{}{TV meal (1)}

{234}{}{Make noodles (+25 hit points).}
{235}{}{pack of noodles (1), clean water (1)}

{236}{}{Molotov Cocktail.}
{237}{}{Rot Gut (1), flare (1)}

{238}{}{Booze (10).}
{239}{}{molasses (1), clean water (1)}

{240}{}{Mantis snack (2).}
{241}{}{Mantis part (2), beer (1), mutfruit (1)}
