########################################
#
#    Описания крестов и могильных камней. Автор Kerb.
#
########################################

{10}{}{You see a grave cross.}
{11}{}{You see a grave stone.}
{12}{}{You see a grave plate.}

{20}{}{On the cross is written: "}
{21}{}{On the grave plate is written: "}
{22}{}{}
{23}{}{"}
{24}{}{There was a writing here, but it's been erased by time.}
{25}{}{This cross is blank.}

#Кафе Новых надежд
{30}{}{The graveyard of buried ideas.}

#Шайенн
{100}{}{Ahiga the Smashing Blow. In the fields of Eternal Hunt, strike at servants of the Devourer with your spear...}
{101}{}{Mechitehyu the Moonlight Shadow. His spirit still walks with the Night Winds...}
{102}{}{Pouoka the Watcher through Time: 1877 - the Cheyenne's autumn, 2077 - the end of the Old World, 2277 - let the Legion come...}
{103}{}{Otaktay the Torturing Wolf. He favored the war axe over the peace pipe.}

#Прово
{150}{}{Freddie "Gorefiend" Voorhees: They named the "Ripper" after me, baby!}
{151}{}{Dallas "Evil Kitty" Ocasec. A hot little thing that will feel cold even in the depths of hell.}
{152}{}{Nick "Savage" Eckhart. 17 kills, 4 robberies, 9 rapes - and thats in only one week.}
{153}{}{Arkin "Shiz" Fernandez. Hated his family so much that after a week without them blew his brains out to continue torturing them in hell.}
{154}{}{Kevin "The Postman" Brooks. Philanthropist, family man, sadistic cannibal.}
{155}{}{Patrick "Not a day without pain," Bale. Satan sent him, Satan took him back.}
{156}{}{Stephen "Arrow" Travis. He only loved his dog, Lilly... In a good way, asshole!}

#Вегас
{200}{}{Brunson, Phil. Excellent evening - pleasant company - 8 bribes - myocardial infarction.}
{201}{}{Chris Buddy. Rare bitch - folded with three aces.}
{202}{}{Johnny "Zero" Hellmuth. The real player is never too poor to buy chips while he has two kidneys.}
{203}{}{Mordechai Ungar. He was called by the lights of Vegas, and his dreams burned up in them.}
{204}{}{Oscar "Toothy" Manfredi. I'm silent in the ring, because my fists do the talking.}

#Блэк-Рок
{250}{}{Patricia Whitman. My love for you was like a nuclear explosion - beautiful, dazzling and deadly...}
{251}{}{Michael "Runner" Phelps. He ran his last hundred yards without a head on his shoulders.}
{252}{}{Marion Connelly. She died of an overdose - but kept her promise to quit smoking.} #The original line referenced crack here, but I'm not sure if that fits in the Fallout lore so I kept it vague.
{253}{}{Lorenz Tate. In these parts we still shoot the messenger.}
{254}{}{Martin "Nomad" Wallace. The last romantic traveler.}

#Солт-Лейк
{300}{}{Gabriel "Jesuit" Borgia. He did not drink, smoke or swear, but the deathclaw was not impressed.}
{301}{}{Oliver Smith. "I experienced one day of judgment - to rise to the second!"}
{302}{}{Fuzzy, Gourmet and Striped Tail. To kill women, children and the elderly is understandable. But what monster could harm a cat?!}
{303}{}{Oliver Rigdon. That's all that was known about him.}
{304}{}{Vic Allison. Realized too late that "Aqua Regia" was not the new drink at the "Lead Angel".}
{305}{}{Hayley Ross. Her husband had no faith in her immaculate conception.}
{306}{}{Adam "Cleaner" Garner. He did dirty work... And was cleaned himself in the end.}
{307}{}{George "Commie" Glick. Oh, here you will not get me, you greedy dogs of capitalism!}
{308}{}{Johnny Melton. "As man is now, as was the Lord once, as Lord is now, as was the man"}
{309}{}{Joseph Harris. "...And shall put my arms to the grave, in order and at the threshold of death, I tirelessly served our Creator..."}
{310}{}{Unknown. His last words were: "I will wait for you at the gates of hell, sinners!"}

#Ветер Войны
{350}{}{Captain Benjamin Kurtz. Gone to hell to regroup.}
{351}{}{Private First Class Chris "Dull" Lerner. Always smiled while killing.}
{352}{}{Corporal James Hartman. He would have forgotten his mother's name over the serial number of his personal weapon.}
{353}{}{Mayor Alex "Gravedigger" Turchin. Where we pass, for a long time is silence.}
{354}{}{Sergeant Richard "Nuclear" Beckett. Invisible, pervasive and deadly.}

#Рино
{400}{}{Luciano Marin.}
