{100}{}{You see a vending machine.}
{101}{}{You see the Nuka-Cola vending machine - an essential tool for your business.}
{102}{}{This vending machine is broken and robbed.}
{103}{}{Not during combat!}

#Starting conversation:
{110}{}{This machine still works and generates income for you.}
{111}{}{Take your revenue.}
{112}{}{Load the cola bottles.}
{113}{}{Unload the cola bottles.}
{114}{}{How much cola left in stock?}
{115}{}{View estimated profit expectations.}
{116}{}{Leave the machine.}
{117}{}{}
{118}{}{}
{119}{}{}

#Take the revenue:
{120}{}{Your revenue for the past period amounted to $}
{121}{}{.}
{122}{}{Back.}
{123}{}{Close cash register.}
{124}{}{Since the last revenue, no coins appeared in the machine.}
{125}{}{There's no product left in the machine.}

#How many bottles left, and other statistics
{130}{}{There's no product left in stock.}
{131}{}{The machine contains }
{132}{}{ Nuka-Cola bottles.}

{133}{}{Presumably, local consumers are willing to buy about }
{134}{}{ bottles of drink per day, if the city's social situation stays the same.}

#Load cola
{140}{}{Please put the cola in the container.}
{141}{}{5 bottles.}
{142}{}{10 bottles.}
{143}{}{20 bottles.}
{144}{}{30 bottles.}
{145}{}{50 bottles.}
{146}{}{100 bottles.}
{147}{}{[Load all available cola bottles]}
{148}{}{[Leave it]}
{149}{}{[Done]}

#Unload cola
{150}{}{The machine contains }
{151}{}{ Nuka-Cola bottles}
{152}{}{}
{153}{}{Take 5 bottles.}
{154}{}{Take 10 bottles.}
{155}{}{Take 20 bottles.}
{156}{}{Take 30 bottles.}
{157}{}{Take 50 bottles.}
{158}{}{Take 100 bottles.}
{159}{}{[Take all the remaining bottles]}
{160}{}{[Leave it]}
{161}{}{[Done]}
{162}{}{There's no product left in stock.}
{163}{}{Sorry, you can't carry that much.}
{164}{}{[Take as many bottles as I can carry]}
