#Общие реплики
{100}{}{You cannot do that in combat.}
{101}{}{Not bad.}
{102}{}{Nothing useful.}
{103}{}{Your outdoorsman skill allows you to collect more than usual.}

#Строки для паслена
{200}{}{You see a nightshade plant.}
{201}{}{You see a nightshade plant. It has some berries on it.}
{202}{}{You harvest some nightshade berries.}
{203}{}{This nightshade has no berries yet.}

#Строки для цветка брок
{300}{}{You see a broc plant.}
{301}{}{You see a broc plant. You think the flowers can be harvested.}
{302}{}{You harvest some broc flowers.}
{303}{}{This broc plant has no flowers yet.}

#Строки для ксандер
{400}{}{You see some xander.}
{401}{}{You see some xander. You think the roots can be harvested.}
{402}{}{You gather some xander roots.}
{403}{}{There's not enough here to be harvested.}

#Строки для вокас
{500}{}{You see an overgrown mutated water lily.}
{501}{}{You see an overgrown mutated water lily. You can see some ripe nuts on it.}
{502}{}{You gather some ripe nuts.}
{503}{}{This mutated water lily has no nuts on it yet.}
