#Translated by TheChosenOne, corected by Keyboard Gecko
{0}{}{ }

#Use of skills
{90}{}{You disarmed the trap.}
{91}{}{You couldn't disarm the trap.}
{92}{}{That wasn't the best decision.}

#Primitive mind
{100}{}{Ughh!!!}

{101}{}{Whoops! Me trip?!}
{102}{}{You laugh at me?}
{103}{}{Me lucky - not hurt.}
{104}{}{This mine now.}
{105}{}{Ooh! Me nose break!}
{106}{}{What me step on?}
{107}{}{Oooh! This mine now.}
{108}{}{::illegible wordflow::}
{109}{}{::grumbles and swears menacingly::}

#Kids
{110}{}{Dammit!!!}
{111}{}{Aw damn! I tore my pants again. Mom's gonna kill me...}
{112}{}{Oooh weeeell!!!}
{113}{}{I'm so clumsy!}

#Prostitutes
{120}{}{Goddammit!!!}

{121}{}{Ah! Panties are slipping!}
{122}{}{Has anyone seen my panties?}
{123}{}{*adjusts skirt*}
{124}{}{That's not funny!}
{125}{}{They won't pay me for a dirty face.}
{126}{}{Lost all my shit... Again.}
{127}{}{Damn brats! Better hope I don't find you!}
{128}{}{}
{129}{}{}

#Citizens
{130}{}{What the hell?!}

{131}{}{Is this some joke?!}
{132}{}{THIS is why we spank kids!}
{133}{}{This is a very stupid joke, you know...}
{134}{}{This isn't funny!}
{135}{}{Who did that?! WHO THE FUCK DID THAT?!}
{136}{}{Looks like I shouldn't wander around here...}
{137}{}{Damn kids! If I find you - I'll beat your ass!}
{138}{}{Hey! Who's being funny?! I'll kick your ass!}
{139}{}{Ahh, I fell for this stupid trick!}

#Workers
{140}{}{God fucking dammit!!!}

{141}{}{What cretin did that!?}
{142}{}{What a shitty day!}
{143}{}{I need a beer after this.}
{144}{}{Ugh! Gonna have to wash my pants again.}
{145}{}{Ugh... Soles are fucked.}
{146}{}{I'm gonna find this joker - and when I do... Someone's gonna eat dirt!}
{147}{}{Get ready punks! Now I'm *really* pissed!}
{148}{}{Who's this milksop?! Huh?}
{149}{}{Hey! Come out, asshole!!!}

#Farmers
{150}{}{Screw that!!!}

{151}{}{Who did that!?}
{152}{}{Can this day get any worse?!}
{153}{}{Is this a joke?! Not funny!}
{154}{}{I worked all day, and you're fucking with me?!}
{155}{}{Ugh... Soles are fucked.}
{156}{}{I'm gonna find this joker - and when I do... Someone's gonna eat dirt!}
{157}{}{DON'T EVER DO THAT AGAIN!!!}
{158}{}{Are you kidding me?!}
{159}{}{}

#Fallen
{160}{}{Oh!!!}

{161}{}{!?}
{162}{}{Ah... Bad luck...}
{163}{}{Is this a joke?!}
{164}{}{I am... I'm... Do you even know WHO I AM!?}
{165}{}{Ughh...}
{166}{}{::groans, picking himself out of the mud::}
{167}{}{DON'T YOU EVER DO THAT AGAIN!!!}
{168}{}{}
{169}{}{}

#Enclave
{170}{}{GODDAMMIT!!!}
{171}{}{I'm gonna find you and then tear you apart!!!}
{172}{}{ARE YOU KIDDING ME!? COME OUT AND FIGHT YOU LITTLE BITCH!!!}

#Brotherhood
{180}{}{Goddammit!!!}

{181}{}{Is this for me or what?!!!}
{182}{}{You're dead, wise guy!}
{183}{}{That's it! You're done for!}
{184}{}{Who did that?! Who the fuck did that?!!!}
{185}{}{Well, well! What have we here? Another dead man walking?}
{186}{}{Hey, wise guy? Come out, and we'll talk this out like men!}
{187}{}{Not your day, chummer!}

#Soldiers
{190}{}{Goddammit!!!}

{191}{}{Is this for me or what?!!!}
{192}{}{You're dead, fucker!!!}
{193}{}{I'm gonna shove your head so far up your ass!!!}
{194}{}{I'll find you, I swear!}
{195}{}{Who did that?! Who the fuck did that?!!!}
{196}{}{I'm gonna!... I don't even *know*, what I'm gonna do to you!!!}
{197}{}{Hey, wise guy! Come out, and we'll talk this out like men!}

#Mutants 
{200}{}{WAAAAGH!!!}
{201}{}{I'm gonna tear your arms off! and legs!.. and... Dick!}
{202}{}{I'll find you and stomp you to the grave!}
{203}{}{Perfect! One more corpse. Just come out!}

#Ghouls
{210}{}{Ow-ow-ow!!!}
{211}{}{One eye more, one eye less, who cares?}
{212}{}{I think my ear fell off...}
{213}{}{Anyone see where my thumb went?}
{214}{}{I'm not looking half bad!}
{215}{}{Ugh! At least I'm alive!}
{216}{}{People! You can't be this cruel!}

#Punks
{220}{}{Aiee!!!}
{221}{}{Now, whose balls need to be strung up?! Come on!}
{222}{}{Come out! I won't hurt you!}
{223}{}{I saw you, joker! I know who you are! Now come out!}
{224}{}{Who did that?! Hiding, you little pussy?! YOU'RE WEAK! WEAK!!!}
{225}{}{When I find you - you're gonna eat dirt!}

#Hubbologists
{230}{}{Oh!!!}
{231}{}{Hmm... Looks like I fell into a trap.}
{232}{}{Don't think these are kids fooling around.}
{233}{}{I'm not sure, but I think that was an attempt at my life!}
{234}{}{I wonder, who this trap was for?}

#Robots
{270}{}{Obstruction detected.}
{271}{}{Obstruction removed.}
{272}{}{Dangerous device detected. Possible hostiles in the area.}
{273}{}{Running attention protocols.}
{274}{}{WARNING! SABOTAGING DEVICE DETECTED!!!}

{300}{}{Your trap worked, damaging the target.}
{301}{}{Your trap worked, the target falls and drops all their things.}
{302}{}{Your target found and disarmed your trap.}
{303}{}{Your target injured a limb.}
{304}{}{The robot falls into the trap but it's sheer mass goes right through it.}
{305}{}{The animal trips on the rope before quickly rising back from the ground.}
{306}{}{Enraged, your target breaks the trap.}
