#======================================================
#
#      Старые названия локаций из Fallout 1 (не используются?)
#
#======================================================

{100}{}{Desert}
{101}{}{Desert}
{102}{}{Desert}
{103}{}{Vault 8}
{104}{}{Vault 8}
{105}{}{Vault 8}
{106}{}{Wind of War}
{107}{}{Wind of War}
{108}{}{Wind of War}
{109}{}{Base 'Sigma'}
{110}{}{Base 'Sigma'}
{111}{}{Base 'Sigma'}
{112}{}{Base 'Sigma'}
{113}{}{Base 'Sigma'}
{114}{}{Base 'Sigma'}
{115}{}{Vault City}
{116}{}{Vault City}
{117}{}{Vault City}
{118}{}{error:Map Name}
{119}{}{City Ruins}
{120}{}{Coast}
{121}{}{Coast}
{122}{}{Desert}
{123}{}{Desert}
{124}{}{error:Map Name}
{125}{}{error:Map Name}
{126}{}{error:Map Name}
{127}{}{error:Map Name}
{128}{}{error:Map Name}
{129}{}{error:Map Name}
{130}{}{error:Map Name}
{131}{}{error:Map Name}
{132}{}{error:Map Name}
{133}{}{error:Map Name}
{134}{}{error:Map Name}
{135}{}{error:Map Name}
{136}{}{error:Map Name}
{137}{}{Hub}
{138}{}{Hub}
{139}{}{Hub}
{140}{}{Hub}
{141}{}{Hub}
{142}{}{Glow}
{143}{}{Glow}
{144}{}{Boneyard}
{145}{}{Boneyard}
{146}{}{Boneyard}
{147}{}{Cathedral}
{148}{}{Hawthorne Military Base}
{149}{}{Mountains}
{150}{}{Mountains}
{151}{}{Desert}
{152}{}{Desert}
{153}{}{Desert}
{154}{}{Desert}
{155}{}{Brotherhood}
{156}{}{Desert}
{157}{}{Desert}
{158}{}{Mountains}
{159}{}{Mountains}
{160}{}{Viper Camp}
{161}{}{Desert}
{162}{}{Mountains}
{163}{}{Desert}
{164}{}{Mountains}

#======================================================
#
#       Названия уровней карт -- AUTOMAP Names
#
#======================================================

#----------------------------------------
# 00: Desert, DESERT1.MAP
#----------------------------------------
{200}{}{Desert}
{201}{}{}
{202}{}{}
#----------------------------------------
# 01: Desert, DESERT2.MAP
#----------------------------------------
{203}{}{Desert}
{204}{}{}
{205}{}{}
#----------------------------------------
# 02: Desert, DESERT3.MAP
#----------------------------------------
{206}{}{Desert}
{207}{}{}
{208}{}{}
#----------------------------------------
# 03: Vault8 Vault, ARCAVES.MAP
#----------------------------------------
{209}{}{Vault, Level 1}
{210}{}{Vault, Level 2}
{211}{}{Vault, Level 3}
#----------------------------------------
# 04: Vault8 VCity, arvillag.MAP
#----------------------------------------
{212}{}{City}
{213}{}{Vault, Level 1}
{214}{}{}
#----------------------------------------
# 05: Vault8 Desert, arbridge.MAP
#----------------------------------------
{215}{}{Desert}
{216}{}{}
{217}{}{}
#----------------------------------------
# 06: Wind Basa, denbus1.MAP
#----------------------------------------
{218}{}{Railway Station}
{219}{}{Garrison}
{220}{}{Railway Station Basement}
#----------------------------------------
# 07: Wind Minivault, denbus2.MAP
#----------------------------------------
{221}{}{Vault Entrance}
{222}{}{Abandoned Vault}
{223}{}{Cave}
#----------------------------------------
# 08: Wind Desert, denres1.MAP
#----------------------------------------
{224}{}{Destroyed Outskirts}
{225}{}{Secret Basement}
{226}{}{}
#----------------------------------------
# 09: Klamath Downtown, kladwtwn.MAP
#----------------------------------------
{227}{}{Downtown}
{228}{}{}
{229}{}{}
#----------------------------------------
# 10: Klamath Mall, klamall.MAP
#----------------------------------------
{230}{}{Mall}
{231}{}{}
{232}{}{}
#----------------------------------------
# 11: Klamath Rat Caves, klaratcv.MAP
#----------------------------------------
{233}{}{Rat Caves}
{234}{}{}
{235}{}{}
#----------------------------------------
# 12: SL Provo, klatoxcv.MAP
#----------------------------------------
{236}{}{Central Square}
{237}{}{}
{238}{}{}
#----------------------------------------
# 13: Klamath Trapping Caves, klatrap.MAP
#----------------------------------------
{239}{}{Trapping Grounds}
{240}{}{Trapping Grounds}
{241}{}{Trapping Grounds}
#----------------------------------------
# 14: Vault City Laba, VCtyLab.MAP
#----------------------------------------
{242}{}{Incubator Rooms}
{243}{}{}
{244}{}{}
#----------------------------------------
# 15: Vault City Courtyard, vctyctyd.MAP
#----------------------------------------
{245}{}{Courtyard}
{246}{}{}
{247}{}{}
#----------------------------------------
# 16: Special Bomba Encounter, rndBomba.MAP
#----------------------------------------
{248}{}{Wasteland}
{249}{}{}
{250}{}{}
#----------------------------------------
# 17: SaltLakeShadow, vctycocl.MAP
#----------------------------------------
{251}{}{Lethal Zone}
{252}{}{Family Vault}
{253}{}{}
#----------------------------------------
# 18: Shaien Village, modmain.MAP
#----------------------------------------
{254}{}{Tribal Camp}
{255}{}{Canyon}
{256}{}{}
#----------------------------------------
# 19: Shaien Raiders, modinn.MAP
#----------------------------------------
{257}{}{Raiders' base}
{258}{}{Raiders' base, 2nd Flor}
{259}{}{Raiders' base, Basement}
#----------------------------------------
# 20: Shaien Pastures, modbrah.MAP
#----------------------------------------
{260}{}{Plantations}
{261}{}{}
{262}{}{}
#----------------------------------------
# 21: Shaien Radio Outside, modgard.MAP
#----------------------------------------
{263}{}{Radio Station - Ground Level}
{264}{}{Radio Station - Underground Level}
{265}{}{}
#----------------------------------------
# 22: Black Rock, BlckRck.MAP
#----------------------------------------
{266}{}{Settlement}
{267}{}{Desert}
{268}{}{Desert}
#----------------------------------------
# 23: Hawthorne Barracks, MBASE00.MAP
#----------------------------------------
{269}{}{Garrison Territory}
{270}{}{Garrison Territory}
{271}{}{Garrison Territory}
#----------------------------------------
# 24: Baikers: Owl, gstfarm.MAP
#----------------------------------------
{272}{}{Main Street}
{273}{}{}
{274}{}{}
#----------------------------------------
# 25: Bikers: Basa, gstcav1.MAP
#----------------------------------------
{275}{}{Radar Station}
{276}{}{}
{277}{}{}
#----------------------------------------
# 26: Ely Depo, gstcav2.MAP
#----------------------------------------
{278}{}{Railway Junction}
{279}{}{}
{280}{}{}
#----------------------------------------
# 27: Zona Start, depolv1.MAP
#----------------------------------------
{281}{}{Taxiway}
{282}{}{}
{283}{}{}
#----------------------------------------
# 28: Zona Kasarmes, depolva.MAP
#----------------------------------------
{284}{}{Personnel}
{285}{}{Personnel}
{286}{}{Hangar Entrance}
#----------------------------------------
# 29: Hangar Zone, depolvb.MAP
#----------------------------------------
{287}{}{Hangar, Upper Level / Ground Level}
{288}{}{Hangar, Underground Level}
{289}{}{Hangar, Ventilation Shaft}
#----------------------------------------
# 30: Vault City Vault, vctyvlt.MAP
#----------------------------------------
{290}{}{Vault: Level 1}
{291}{}{Vault: Level 2}
{292}{}{Vault: Level 3}
#----------------------------------------
# 31: Gecko Settlement, gecksetl.MAP
#----------------------------------------
{293}{}{Village}
{294}{}{}
{295}{}{}
#----------------------------------------
# 32: Gecko Power Plant, geckpwpl.MAP
#----------------------------------------
{296}{}{Power Plant}
{297}{}{}
{298}{}{}
#----------------------------------------
# 33: Gecko Junkyard, geckjunk.MAP
#----------------------------------------
{299}{}{Outskirts}
{300}{}{Garage Roof}
{301}{}{}
#----------------------------------------
# 34: OldTribeCaves, oldTrbCv.MAP
#----------------------------------------
{302}{}{Gecko's Den Entrance}
{303}{}{Gecko's Den Exit}
{304}{}{Lair}
#----------------------------------------
# 35: Vault8 CityDestr, argarden.MAP
#----------------------------------------
{305}{}{Opal Mine}
{306}{}{Catacombs}
{307}{}{}
#----------------------------------------
# 36: HarrelsonMap, Harelson.MAP
#----------------------------------------
{308}{}{Passage to the Shelter}
{309}{}{Harrelson's Shelter}
{310}{}{}
#----------------------------------------
# 37: New Reno Tommigun, newr6.MAP
#----------------------------------------
{311}{}{City Hall Building}
{312}{}{Service Vault}
{313}{}{}
#----------------------------------------
# 38: New Reno DeadRunch, newr9.MAP
#----------------------------------------
{314}{}{Abandoned farm}
{315}{}{}
{316}{}{}
#----------------------------------------
# 39: BlackRockCave, BlckRck2.MAP
#----------------------------------------
{317}{}{Cave Entrance}
{318}{}{Cave Exit}
{319}{}{Cave}
#----------------------------------------
# 40: New Reno Theater, newRTR.MAP
#----------------------------------------
{320}{}{Outdoor Cinema}
{321}{}{Film Exhibition Event Venue}
{322}{}{}
#----------------------------------------
# 41: Special DesertRanger, slShadow.MAP
#----------------------------------------
{323}{}{Camp}
{324}{}{Cave}
{325}{}{}
#----------------------------------------
# 42: Vegas: The Strip, ncr1.MAP
#----------------------------------------
{326}{}{Clean City}
{327}{}{Clean City, 2nd Floor}
{328}{}{Clean City, 2nd Floor}
#----------------------------------------
# 43: Vegas: HardRock cafe, ncr2.MAP
#----------------------------------------
{329}{}{'Hard Rock' cafe}
{330}{}{}
{331}{}{}
#----------------------------------------
# 44: Vegas: SlaverTown, ncr3.MAP
#----------------------------------------
{332}{}{Slavers' Office}
{333}{}{Slaves' Ring}
{334}{}{}
#----------------------------------------
# 45: Vegas: GhoulTown, ncr4.MAP
#----------------------------------------
{335}{}{Dead Hotel}
{336}{}{Rat Holes}
{337}{}{}
#----------------------------------------
# 46: Vegas: Sign, ncrent.MAP
#----------------------------------------
{338}{}{Parking Lot}
{339}{}{Parking Place for Cars}
{340}{}{Undermining}
#----------------------------------------
# 47: Vegas: Hoover Dam, ncrex.MAP
#----------------------------------------
{341}{}{Dam - Ground Level}
{342}{}{Underground Dam Facilities}
{343}{}{Power Station}
#----------------------------------------
# 48: Hawthorne: Hangar 2, mbaseRA.MAP
#----------------------------------------
{344}{}{Reactor Facilities}
{345}{}{}
{346}{}{}
#----------------------------------------
# 49: Hawthorne Hangar, mbase12.MAP
#----------------------------------------
{347}{}{Army's Warehouses}
{348}{}{Underground Hangar}
{349}{}{Warehouse Roofs}
#----------------------------------------
# 50: Hawthorne Railway Station, mbase34.MAP
#----------------------------------------
{350}{}{Railway Station}
{351}{}{}
{352}{}{}
#----------------------------------------
# 51: Hawthorne ElCapitan, mbclose.MAP
#----------------------------------------
{353}{}{Dead City}
{354}{}{Dead City}
{355}{}{Dead City}
#----------------------------------------
# 52: Wind Run DenRun.MAP
#----------------------------------------
{356}{}{Camp}
{357}{}{Settlement}
{358}{}{Raiders' Base}
#----------------------------------------
# 53: Car Desert out-of-gas, CarDesrt.MAP
#----------------------------------------
{359}{}{Desert}
{360}{}{}
{361}{}{}
#----------------------------------------
# 54: New Reno Silver, newr1.MAP
#----------------------------------------
{362}{}{Hotel 'Silver'}
{363}{}{Sewers}
{364}{}{Hotel 'Silver', 2nd Floor}
#----------------------------------------
# 55: New Reno Eldorado, newr2.MAP
#----------------------------------------
{365}{}{'Eldorado' casino}
{366}{}{'Eldorado' casino, 2nd Floor}
{367}{}{Patrick's Dormitory}
#----------------------------------------
# 56: New Reno Straiker, newr3.MAP
#----------------------------------------
{368}{}{Stadium}
{369}{}{Evacuation Bunker}
{370}{}{Stadium, 2nd Floor}
#----------------------------------------
# 57: New Reno Depo, newr4.MAP
#----------------------------------------
{371}{}{Railway Station}
{372}{}{Railway Station - Basement}
{373}{}{}
#----------------------------------------
# 58: New Reno Oliver, newrcs.MAP
#----------------------------------------
{374}{}{Ranch}
{375}{}{Dealing spot}
{376}{}{}
#----------------------------------------
# 59: PepGaz, newrgo.MAP
#----------------------------------------
{377}{}{Gas station}
{378}{}{}
{379}{}{}
#----------------------------------------
# 60: Vegas Stables, newrst.MAP
#----------------------------------------
{380}{}{Protected Area}
{381}{}{}
{382}{}{}
#----------------------------------------
# 61: New Reno Boxing Arena, newrba.MAP
#----------------------------------------
{383}{}{Boxing Arena}
{384}{}{}
{385}{}{}
#----------------------------------------
# 62: Wendover Angar, RedWame.Map
#----------------------------------------
{386}{}{Workshop}
{387}{}{Roof of the Hangar}
{388}{}{}
#----------------------------------------
# 63: Wendover BigAngar, RedWan1.MAP
#----------------------------------------
{389}{}{Big Hangar, Roof}
{390}{}{Big Hangar, Level 1}
{391}{}{Big Hangar, Level 1}
#----------------------------------------
# 64: Wendover Center, RedDown.MAP
#----------------------------------------
{392}{}{Downtown}
{393}{}{Residential}
{394}{}{Underground Facilities}
#----------------------------------------
# 65: Wendover TrapperTown, RedMEnt.MAP
#----------------------------------------
{395}{}{Trappers Association, Stop}
{396}{}{Trappers Association, 2nd Floor}
{397}{}{Trappers Association, Roof}
#----------------------------------------
# 66: Wendover KislotBog, RedDTun.MAP
#----------------------------------------
{398}{}{Hunter's Lands}
{399}{}{Hunter's Lands}
{400}{}{Hunter's Lands}
#----------------------------------------
# 67: Wendover CityDestroy, redmtun.MAP
#----------------------------------------
{401}{}{Ruins of Wendover}
{402}{}{Ruins of Wendover}
{403}{}{Ruins of Wendover}
#----------------------------------------
# 68: Random Encounter, City 1
{404}{}{City}
{405}{}{City}
{406}{}{City}
# 69: Random Encounter, Cavern 0
{407}{}{Mountain}
{408}{}{Mountain}
{409}{}{Mountain}
# 70: Random Encounter, Cavern 1
{410}{}{Caverns}
{411}{}{Cavern}
{412}{}{Cavern}
# 71: Random Encounter, Cavern 2
{413}{}{Cavern}
{414}{}{Cavern}
{415}{}{Cavern}
# 72: Random Encounter, Cavern 3
{416}{}{Cavern}
{417}{}{Cavern}
{418}{}{Cavern}
# 73: Random Encounter, Cavern 4
{419}{}{Cavern}
{420}{}{Cavern}
{421}{}{Cavern}
# 74: Random Encounter, Mountain 1
{422}{}{Mountain}
{423}{}{Mountain}
{424}{}{Mountain}
# 75: Random Encounter, Mountain 2
{425}{}{Mountain}
{426}{}{Mountain}
{427}{}{Mountain}
# 76: Random Encounter, Coast 1
{428}{}{Coast}
{429}{}{Coast}
{430}{}{Coast}
# 77: Random Encounter, Coast 2
{431}{}{Coast}
{432}{}{Coast}
{433}{}{Coast}
#----------------------------------------
# 78: Ely City, broken1.map
#----------------------------------------
{434}{}{Dormitory / Hostel, 1st Floor}
{435}{}{Dormitory / Hostel, 2nd Floor}
{436}{}{Dormitory / Hostel, 3rd Floor}
#----------------------------------------
# 79: Ely Altar, broken2.map
#----------------------------------------
{437}{}{Catholic church}
{438}{}{Temple's underground}
{439}{}{Upper floors of temple}
#----------------------------------------
# 80: Random Encounter, Cavern 5
{440}{}{Cavern}
{441}{}{Cavern}
{442}{}{Cavern}
# 81: Random Encounter, Desert 4
{443}{}{Desert}
{444}{}{Desert}
{445}{}{Desert}
# 82. Random Encounter, Desert 5
{446}{}{Abandoned Camp}
{447}{}{Abandoned Camp}
{448}{}{Abandoned Camp}
# 83. Random Encounter, Desert 6
{449}{}{Abandoned Farm}
{450}{}{Abandoned Farm}
{451}{}{Abandoned Farm}
# 84. Random Encounter, Desert 7
{452}{}{Cactus Field}
{453}{}{Cactus Field}
{454}{}{Cactus Field}
# 85. Random Encounter, Coast 3
{455}{}{Coast}
{456}{}{Coast}
{457}{}{Coast}
# 86. Random Encounter, Coast 4
{458}{}{Coast}
{459}{}{Coast}
{460}{}{Coast}
# 87. Random Encounter, Coast 5
{461}{}{Highway}
{462}{}{Highway}
{463}{}{Highway}
# 88. Random Encounter, Coast 6
{464}{}{Coast}
{465}{}{Coast}
{466}{}{Coast}
# 89. Random Encounter, Coast 7
{467}{}{Coast}
{468}{}{Coast}
{469}{}{Coast}
# 90. Random Encounter, Coast 8
{470}{}{Highway}
{471}{}{Highway}
{472}{}{Highway}
# 91. Random Encounter, Coast 9
{473}{}{Coast}
{474}{}{Coast}
{475}{}{Coast}
#----------------------------------------
# 92. RejectionCity, Reject.MAP
#----------------------------------------
{476}{}{Workers' Settlement}
{477}{}{Mining Camp}
{478}{}{Mining Tunnel}
#----------------------------------------
# 93. DlzhsDead, DlsDeadMAP
#----------------------------------------
{479}{}{Place of the Attack}
{480}{}{}
{481}{}{}
#----------------------------------------
# 94. Broken Hills, Random Encounter, Desert
#----------------------------------------
{482}{}{Desert}
{483}{}{Desert}
{484}{}{Desert}
#----------------------------------------
# 95. Broken Hills, Random Encounter, Mountain
#----------------------------------------
{485}{}{Mountain}
{486}{}{Mountain}
{487}{}{Mountain}
#----------------------------------------
# 96. Special Encounter: Roads, rndwhale.MAP
#----------------------------------------
{488}{}{Trap Location}
{489}{}{}
{490}{}{}
#----------------------------------------
# 97. Special Encounter: AnalDen, rndtinwd.MAP
#----------------------------------------
{491}{}{Smelly Hole}
{492}{}{Inside the Hole}
{493}{}{}
#----------------------------------------
# 98. Special Encounter: Mina Pole, rndBHead.MAP
#----------------------------------------
{494}{}{Dump's Center}
{495}{}{}
{496}{}{}
#----------------------------------------
# 99. Special Encounter: Tanker, rndShutl.MAP
#----------------------------------------
{497}{}{Tanker's Deck}
{498}{}{Tanker - Upper Level}
{499}{}{Tanker - Lower Level}
#----------------------------------------
# 100. Special Encounter: Unwashed Villagers
#----------------------------------------
{500}{}{Station}
{501}{}{Station - Basement}
{502}{}{Desert}
#----------------------------------------
# 101. Special Encounter: Black Isle Office, rndbridg.MAP
#----------------------------------------
{503}{}{Office - 1st Floor}
{504}{}{Office - 2nd Floor}
{505}{}{Office - 3rd Floor}
#----------------------------------------
# 102. Special Encounter: Cafe of Broken Dreams
#----------------------------------------
{506}{}{Cafe "New Hope"}
{507}{}{Basement Rooms}
{508}{}{}
#----------------------------------------
# 103. Special Encounter: Big Egg
#----------------------------------------
{509}{}{Desert}
{510}{}{}
{511}{}{}
#----------------------------------------
# 104. Special Encounter: Bobby
#----------------------------------------
{512}{}{Desert}
{513}{}{}
{514}{}{}
#----------------------------------------
# 105. Special Encounter: HomeRoad
#----------------------------------------
{515}{}{Temporary Camp}
{516}{}{}
{517}{}{}
#----------------------------------------
# 106. Special Encounter: Toxic Waste Dump
#----------------------------------------
{518}{}{Wasteland}
{519}{}{}
{520}{}{}
#----------------------------------------
# 107. Special Encounter: Cowboy
#----------------------------------------
{521}{}{Highway}
{522}{}{}
{523}{}{}
#----------------------------------------
# 108. Special Encounter: Piknik
#----------------------------------------
{524}{}{Oasis}
{525}{}{Cave}
{526}{}{Cave}
#----------------------------------------
# 109. Old Rubby, Rubby.MAP
#----------------------------------------
{527}{}{Old Rubby's Hut}
{528}{}{}
{529}{}{}
#----------------------------------------
# 110. Coast Encounter 10
{530}{}{Coastline}
{531}{}{Coastline}
{532}{}{Coastline}
# 111. Coast Encounter 11
{533}{}{Highway}
{534}{}{Highway}
{535}{}{Highway}
# 112. Coast Encounter 12
{536}{}{Acid Swamp}
{537}{}{Acid Swamp}
{538}{}{Acid Swamp}
# 113. Desert Encounter 8
{539}{}{Black Forest}
{540}{}{Black Forest}
{541}{}{Black Forest}
# 114. Desert Encounter 9
{542}{}{Black Forest}
{543}{}{Black Forest}
{544}{}{Black Forest}
# 115. Desert Encounter 10
{545}{}{Black Forest}
{546}{}{Black Forest}
{547}{}{Black Forest}
# 116. Desert Encounter 11
{548}{}{Desert}
{549}{}{Desert}
{550}{}{Desert}
# 117. Desert Encounter 12
{551}{}{Desert}
{552}{}{Desert}
{553}{}{Desert}
# 118. Cavern Encounter 5
{554}{}{Cavern}
{555}{}{Cavern}
{556}{}{Cavern}
# 119. PsiFarm
{557}{}{Center of the Settlement}
{558}{}{Underground}
{559}{}{}
# 120. BeattyCity, Beatty.MAP
{560}{}{Main Street}
{561}{}{City Hall}
{562}{}{City Hall, 2nd Floor}
# 121. Mountain Encounter 3
{563}{}{Mountain}
{564}{}{Mountain}
{565}{}{Mountain}
# 122. Mountain Encounter 4
{566}{}{Mountain}
{567}{}{Mountain}
{568}{}{Mountain}
# 123. Mountain Encounter 5
{569}{}{Mountain}
{570}{}{Mountain}
{571}{}{Mountain}
# 124. Mountain Encounter 6
{572}{}{Mountain}
{573}{}{Mountain}
{574}{}{Mountain}
# 125. City Encounter
{575}{}{Abandoned City}
{576}{}{Ruined City}
{577}{}{Ruined City}
#----------------------------------------
# 126. Vault8 FirstStart, artemple.MAP
#----------------------------------------
{578}{}{Year 2091 - Vault}
{579}{}{Year 2091 - Outer World}
{580}{}{Year 2091 - Outer World}
#----------------------------------------
# 127. VaultCityDestroy, ardead.MAP
#----------------------------------------
{581}{}{Destroyed City}
{582}{}{Destroyed City}
{583}{}{Destroyed City}
#----------------------------------------
# 128. Enclave Vault, encdet.MAP
#----------------------------------------
{584}{}{Vault, Level 1}
{585}{}{Vault, Level 2}
{586}{}{Vault, Level 3}
#----------------------------------------
# 129. Enclave Stop, encdock.MAP
#----------------------------------------
{587}{}{Stop}
{588}{}{Camp}
{589}{}{Railway Bridge}
#----------------------------------------
# 130. Enclave Hangar, encfite.MAP
#----------------------------------------
{590}{}{Hangar}
{591}{}{}
{592}{}{}
#----------------------------------------
# 131. Enclave PostStop, encgd.MAP
#----------------------------------------
{593}{}{Temporary Stop}
{594}{}{}
{595}{}{}
#----------------------------------------
# 132. Enclave PresdntHead, encpres.MAP
#----------------------------------------
{596}{}{Vault, Level 4}
{597}{}{}
{598}{}{}
#----------------------------------------
# 133. Old Tribe, oldtribe.MAP
#----------------------------------------
{599}{}{Settlement}
{600}{}{Underground}
{601}{}{Canyon}
#----------------------------------------
# 134. Ely Bunker, enctrp.MAP
#----------------------------------------
{602}{}{Station - Ground Level}
{603}{}{Station - Underground Level}
{604}{}{}
#----------------------------------------
# 135. SL Train, sftanker.MAP
#----------------------------------------
{605}{}{Railroad Depot}
{606}{}{Underground Communications}
{607}{}{Railroads Depot}
#----------------------------------------
# 136. SL Ogden, sfdock.MAP
#----------------------------------------
{608}{}{Renaissance Square}
{609}{}{Family Shelter}
{610}{}{}
#----------------------------------------
# 137. SL Center, sfchina.MAP
#----------------------------------------
{611}{}{Business Center}
{612}{}{}
{613}{}{}
#----------------------------------------
# 138. SL Anal, SFSHUTL1.MAP
#----------------------------------------
{614}{}{Canyon}
{615}{}{Sewerage}
{616}{}{Sewerage}
#----------------------------------------
# 139. SL Mormones, SFSHUTL2.MAP
#----------------------------------------
{617}{}{Temple}
{618}{}{Temple's Roof}
{619}{}{Temple's Underground}
#----------------------------------------
# 140. SL Artesian, sfelronb.MAP
#----------------------------------------
{620}{}{Ghetto}
{621}{}{Artesian Tower}
{622}{}{Family Shelter}
#----------------------------------------
# 141. City Encounter 3
{623}{}{Destroyed City}
{624}{}{Destroyed City}
{625}{}{Destroyed City}
# 142. City Encounter 4
{626}{}{Destroyed City}
{627}{}{Destroyed City}
{628}{}{Destroyed City}
# 143. City Encounter 5
{629}{}{Destroyed City}
{630}{}{Destroyed City}
{631}{}{Destroyed City}
# 144. City Encounter 6
{632}{}{Destroyed City}
{633}{}{Destroyed City}
{634}{}{Destroyed City}
# 145. City Encounter 7
{635}{}{Destroyed City}
{636}{}{Destroyed City}
{637}{}{Destroyed City}
# 146. City Encounter 8
{638}{}{Destroyed City}
{639}{}{Destroyed City}
{640}{}{Destroyed City}
#----------------------------------------
# 147. New Reno Raider, newrvb.MAP
#----------------------------------------
{641}{}{City Ruins}
{642}{}{}
{643}{}{}
#----------------------------------------
# 148. SL NukeCola, sfchina2.MAP
#----------------------------------------
{644}{}{Nuka-Cola Factory}
{645}{}{Nuka-Cola Factory, 2nd Flor}
{646}{}{Nuka-Cola Factory, Basement}
#----------------------------------------
# 149. In Game Movie, gammovie.MAP
#----------------------------------------
{647}{}{Desert}
{648}{}{Desert}
{649}{}{Desert}
#----------------------------------------
# 150. RndBess, rndbess.MAP
#----------------------------------------
{650}{}{Temporary camp}
{651}{}{Desert}
{652}{}{Desert}

#==========================================================
#
#	Названия локаций на карте мира и в мини-карте
#       Нумерация: 1500+Area. Номер area см. в CITY.TXT разделы вида [Area ??]
#
#==========================================================

{1500}{}{Vault City}
{1501}{}{Wind of War}
{1502}{}{The 'Sigma' base}
{1503}{}{Lovelock}
{1504}{}{Baydie}
{1505}{}{Poseidon Oil NPP}
{1506}{}{Ailie}
{1507}{}{New Reno}
{1508}{}{Area 51}
{1509}{}{Bridgeport}
{1510}{}{Las Vegas}
{1511}{}{Provo District}
{1512}{}{Hawthorne Military Base}
{1513}{}{Wendover}
{1514}{}{Salt Lake City}
{1515}{}{Old Rabbi}
{1516}{}{Governmental Vault}
{1517}{}{Gerlach}
{1518}{}{Uranium City}
{1519}{}{The Pound}
{1520}{}{Battle Mountain}
{1521}{}{Car Outta Power}
{1522}{}{Vault City}
{1523}{}{Traffic Jam}
{1524}{}{Operation of Wind of War}
{1525}{}{Black Rock}
{1526}{}{Desert}
{1527}{}{Mountain}
{1528}{}{Ruined City}
{1529}{}{Coast}
{1530}{}{Gas Station}
{1531}{}{Crossroad}
{1532}{}{Big Hole}
{1533}{}{Dump of Tires}
{1534}{}{Tanker in the desert}
{1535}{}{Abnormal place}
{1536}{}{Lost Office}
{1537}{}{'The New Hopes' cafe}
{1538}{}{Giant Egg}
{1539}{}{Bobby's Hut}
{1540}{}{House on Wheels}
{1541}{}{'Furthur'}
{1542}{}{Abandoned Ranger's Station}
{1543}{}{Picnic Area}
{1544}{}{Caravan}
{1545}{}{"Dear John"}
{1546}{}{Harrelson}
{1547}{}{Random Encounter}
{1548}{}{Broken stagecoach}
{1549}{}{Car}
{1550}{}{Vault 8 Surroundings}
{1551}{}{New Reno (2)}
{1552}{}{Total Recall}
