#
# 北北北北北北北北北北北北北北北北北北北北北北北北北北北北北北北北北北北北北北?
#
# Text labels and messages used in PIPBOY.C
#
# (These MUST match "text message" enumeration on the top of PIPBOY.C)
#
# 北北北北北北北北北北北北北北北北北北北北北北北北北北北北北北北北北北北北北北?

#
# Special holiday dates
#
{100}{}{Happy New Year's Day!}      # New years
{101}{}{Happy Valentine's Day!}     # April fools
{102}{}{Happy Fool's Day!}          # April fools
{103}{}{Happy Captain's Day!}       # Shipping day!
{104}{}{Happy Independence Day!}    # Independence day
{105}{}{Happy Halloween!}           # Halloween
{106}{}{Happy Thanksgiving Day!}    # Thanksgiving
{107}{}{Merry Christmas!}           # X-mas

#
# System messages
#
{200}{}{MORE}
{201}{}{BACK}
{202}{}{STATUS}
{203}{}{No current tasks at the moment.}
{204}{}{CLUES}  # clues gone
{205}{}{AUTOMAPS}
{206}{}{VIDEO ARCHIVES}
{207}{}{DATA}
{208}{}{}
{209}{}{}
{210}{}{Status}
{211}{}{DATA}
{212}{}{of}
{213}{}{Page}
{214}{}{DONE}
{215}{}{You cannot rest at this location!}

#
# Alarm clock
#
{300}{}{ALARM CLOCK}
{301}{}{Hit Points}
{302}{}{Rest for ten minutes}
{303}{}{Rest for thirty minutes}
{304}{}{Rest for an hour}
{305}{}{Rest for two hours}
{306}{}{Rest for three hours}
{307}{}{Rest for four hours}
{308}{}{Rest for five hours}
{309}{}{Rest for six hours}
{310}{}{Rest until morning (0800)}
{311}{}{Rest until noon (1200)}
{312}{}{Rest until evening (1800)}
{313}{}{Rest until midnight (0000)}
{314}{}{Rest until healed}
{315}{}{Rest until party is healed}

#
# Holodisk titles
#
{400}{}{Warehouse assignment}
{401}{}{Preliminary report}
{402}{}{Item list}
{403}{}{-empty-}
{404}{}{Report on deserters}
{405}{}{-empty-}
{406}{}{Diary's entries}
{407}{}{Medical report}
{408}{}{Exodus}
{409}{}{Radio station documents}
{410}{}{Jay's message}
{411}{}{History of "Wind of War"}
{412}{}{Memory card analysis}
{413}{}{Newspaper note about Big Louie}
{414}{}{Trapped man's records}
{415}{}{Officer's records}
{416}{}{-empty-}
{417}{}{-empty-}
{418}{}{Criminal case #4783}
{419}{}{Stagecoach advertisement}
{420}{}{-empty-}

#
# Movie archive titles
# Order must match the list (see gmovie.h)
#
{500}{}{Warning}
{501}{}{Intro}
{502}{}{Year 2091}
{503}{}{Year 2140}
{504}{}{Exile}
{505}{}{First time on the surface}
{506}{}{Starting the Car}
{507}{}{Hawthorne panorama}
{508}{}{-empty-}
{509}{}{Departure by train}
{510}{}{-empty-}
{511}{}{Return to Salt Lake}
{512}{}{Reminder 1}
{513}{}{Reminder 2}
{514}{}{Reminder 3}
{515}{}{SOS signal}
{516}{}{Credits}

#
# Things for the Mac version to speak
#
#
{600}{}{Status}
{601}{}{Clues}  # Clues gone
{602}{}{Automaps}
{603}{}{Archives}
{604}{}{Alarm Clock}
{605}{}{Doo da doo da dum dee dee doodly doo dum dum dum doo da doo da doo da doo da doo da doo da doo}
{606}{}{Welcome to the Rob Co. Pipboy 2009.}
{607}{}{So long.}
{608}{}{Wake up.}


#
# Holodisk text
#

# Special assignment VC - list
# GVAR_VC_SUPERBONUS
{1000}{}{Vault 8 warehouse requires to find the following}
{1001}{}{Vault-Tec technology items:}
{1002}{}{}
{1003}{}{  * Ion synthesizer}
{1004}{}{  * Gas analyzer}
{1005}{}{  * Impulse modulator}
{1006}{}{  * Pressure regulator}
{1007}{}{  * Clothing synthesizer chip}
{1008}{}{}
{1009}{}{**END-DISK**}

# Vault 8: Investigator report
# GVAR_HOLODISK_COUNTRY_MSG (GVAR_HOLODISK_MB_OUTSIDE)
{2000}{}{A draft of a report about a criminal prosecution}
{2001}{}{}
{2002}{}{Author - Malcolm Rivers, Sheriff's deputy}
{2003}{}{}
{2004}{}{}
{2005}{}{I started to write this report in case if something}
{2006}{}{happens to us. If you find this}
{2007}{}{notes, send them to Washoe County Sheriff,}
{2008}{}{state of Nevada.}
{2009}{}{}
{2010}{}{Entry 1}
{2011}{}{}
{2012}{}{Ely Gorbinsky - mean son of a bitch. he escaped}
{2013}{}{justice after killing an Afro-American in }
{2014}{}{New Reno streets. The court released him on just a}
{2015}{}{house arrest. And I can't leave like that such a bold}
{2016}{}{act of racism! That's why I started to spy}
{2017}{}{on the criminal, and not in vain. He really left}
{2018}{}{the town, going north, ignoring the court's order.}
{2019}{}{I followed. When he found out he's been chased,}
{2020}{}{Gorbinsky tried to disappear, but I constantly tailed}
{2021}{}{him, until we reached highway.}
{2022}{}{Few miles away from NPP "Poseidon Oil" we caught up,}
{2023}{}{but the criminal tried to ram my car off the road.}
{2024}{}{In the occurred crash both vehicles were shattered.}
{2025}{}{Gorbinsky took a hit in the head and lost}
{2026}{}{consciousness, I got away only with a few bruises}
{2027}{}{(luckily!). While the bastard was coming to his}
{2028}{}{senses, I managed to call for backup on the radio.}
{2029}{}{}
{2030}{}{The truck from NPP arrived, took us to the }
{2031}{}{station. In order to prevent Gorbinsky from }
{2032}{}{trying anything stupid, I handcuffed him to myself}
{2033}{}{and confiscated all his belongings. On the station}
{2034}{}{I couldn't get any help - there was a real mess. }
{2035}{}{It seemed that NPP was getting on lockdown, and }
{2036}{}{people were preparing for an emergency evac. But I }
{2037}{}{had no time to figure things out. My backup never}
{2038}{}{arrived, so I had to take the bus to New Reno }
{2039}{}{in the morning, together with criminal. The driver }
{2040}{}{made a stop at opal mining village property of the }
{2041}{}{Wilsons family. They are decent folks, who made }
{2042}{}{living mining opals in the area, and they accepted}
{2043}{}{us quite hospitably.}
{2044}{}{}
{2045}{}{Sometime around 12:30 Ely Gorbinsky}
{2046}{}{escaped from me. While he was handcuffed}
{2047}{}{to a radiator, I went to a store, and}
{2048}{}{he managed to pick the lock with a piece of wire.}
{2049}{}{When I ran out of the house, he was already}
{2050}{}{driving south, full-speed, on a hijacked bus.}
{2051}{}{What's more, he took passengers with him, who}
{2052}{}{probably didn't even notice anything. The bus driver}
{2053}{}{was later found dead in the restroom.}
{2054}{}{}
{2055}{}{There is no radio here, next bus should come}
{2056}{}{around tomorrow noon. Local truck is in repairs}
{2057}{}{and will be finished only tomorrow morning at best.}
{2058}{}{The only thing left is to hope, that}
{2059}{}{in that time Gorbinsky won't make any more trouble.}
{2060}{}{}
{2061}{}{But, one way or another, I will bring him to justice!}
{2062}{}{Criminals can't walk around freely.}
{2063}{}{Even in remote place that is our quiet county.}
{2064}{}{}
{2065}{}{Entry 2}
{2066}{}{}
{2067}{}{I waited for a bus until 16:00. When I realized, that}
{2068}{}{it won't come, I started to pressure the mechanic}
{2069}{}{to hurry up with the truck. But he was already}
{2070}{}{severely drunk. I'm forced to stick here for another}
{2071}{}{day, while that damned Gorbinsky is on the loose}
{2072}{}{on a stolen vehicle! This is going to be}
{2073}{}{agonizing, I *must* stop him, but instead}
{2074}{}{I sit here, bound by some technical problems.}
{2075}{}{Am I the only one, that cares about justice}
{2076}{}{in this place?..}
{2077}{}{}
{2078}{}{We wrapped up driver's body in a bedsheets}
{2079}{}{and put him in some cold place at the hangar.}
{2080}{}{That bastard! When I get to Gorbinsky, no judge is}
{2081}{}{going to save him!}
{2082}{}{}
{2083}{}{Entry 3}
{2084}{}{}
{2085}{}{It was a rough day today...}
{2086}{}{}
{2087}{}{The bus didn't show up again. By lunch I}
{2088}{}{just forced the mechanic to repair the engine}
{2089}{}{on the truck. We hit the road to Reno,}
{2090}{}{but right in the next valley found the bus,}
{2091}{}{with which Gorbinsky escaped.}
{2092}{}{It was empty. And, for some reason, it was facing }
{2093}{}{the village. Either Gorbinsky came back, or didn't}
{2094}{}{left at all! Using the radio on a bus, I tried to }
{2095}{}{reach my people, then, at least, the bus station in }
{2096}{}{Reno, but all I got was white noise instead of an }
{2097}{}{answer. Did everybody just died in there, goddamn it?!}
{2098}{}{}
{2099}{}{We returned to the village to warn the people}
{2100}{}{about the danger, but were too late - one of the}
{2101}{}{workers already met a violent death in the diner.}
{2102}{}{You wouldn't wish a thing like that to your enemy.}
{2103}{}{}
{2104}{}{I decided to stay, in order to help the locals.}
{2105}{}{Otherwise, why the hell do I wear the badge of a }
{2106}{}{Sheriff's deputy? The hard hand of Themis is exactly}
{2107}{}{what this place needs, what America needed so much}
{2108}{}{in last years... And I was so right to stay.}
{2109}{}{Late at night, Wilsons found another worker's head}
{2110}{}{in the washing machine.}
{2111}{}{}
{2112}{}{That son of a bitch wanders somewhere close!}
{2113}{}{I have to stop him, before anyone else}
{2114}{}{gets hurt...}
{2115}{}{}
{2116}{}{Entry 4}
{2117}{}{}
{2118}{}{...Almost didn't sleep. The truck got set on fire}
{2119}{}{at night. The mechanic was inside. He had been seen}
{2120}{}{drunk beforehand, so Wilsons decided he was the one}
{2121}{}{responsible for the fire.}
{2122}{}{But I know, who's fault is this!}
{2123}{}{}
{2124}{}{Now we have no transport. At all.}
{2125}{}{Those, interfering with my investigation, I locked}
{2126}{}{away in the diner. Let them sit and think a little,}
{2127}{}{while I deal with that filthy scum...}
{2128}{}{}
{2129}{}{Entry 5}
{2130}{}{}
{2131}{}{I'm all alone now.}
{2132}{}{All this time, since my last note, Gorbinsky}
{2133}{}{quietly and cunningly took by one life every day...}
{2134}{}{Bastard! I hope you'll die in hell!!!..}
{2135}{}{Nobody, except me, can stop him now}
{2136}{}{and restore justice.}
{2137}{}{If only... If ONLY that judge condemned him to}
{2138}{}{an electric chair...}
{2139}{}{IF ONLY the patrol would respond on my call}
{2140}{}{in time...}
{2141}{}{But what is happening in the world, damn it?!}
{2142}{}{Why nobody's looking for us?}
{2143}{}{Why there is still no bus?}
{2144}{}{Could it be that a war started?..}
{2145}{}{}
{2146}{}{I'm going to stop the bastard by *any* means}
{2147}{}{necessary. And even if they take away my badge,}
{2148}{}{I won't leave it like this.}
{2149}{}{**END-DISK**}

# Item list
# GVAR_PIPBOY_LIST_CARAVAN_ITEMS
{3000}{}{List of items caravan merchant ordered.}
{3001}{}{}
{3002}{}{  * Sledgehammer}
{3003}{}{  * Gecko pelt (any)}
{3004}{}{  * Shovel}
{3005}{}{  * First Aid Kit}
{3006}{}{  * Flare (3 pcs)}
{3007}{}{  * Rope}
{3008}{}{  * Empty flask (2 pcs)}
{3009}{}{  * Metal Scrap }
{3010}{}{  * Rubber boots}
{3011}{}{  * Wrench}
{3012}{}{  * Weapon parts}
{3013}{}{}
{3014}{}{It is necessary to hurry to collect these,}
{3015}{}{because in three days the caravan will depart.}
{3016}{}{**END-DISK**}

# Free space
{4000}{}{--EMPTY--}
{4001}{}{**END-DISK**}

# Hawthorne: Report on deserters
# GVAR_HOWTHORNE_DSK_DESERTIRES (GVAR_HOLODISK_MB_LEVEL_3)
{5000}{}{}
{5001}{}{This document contains a case report}
{5002}{}{of mass desertion.}
{5003}{}{}
{5004}{}{As the commission established, a group of military}
{5005}{}{employees seized equipment and weapons from }
{5006}{}{Hawthorne warehouses, then fought their way out of }
{5007}{}{the base perimeter. The reason, that pushed the }
{5008}{}{soldiers to commit such a crime, was panic, }
{5009}{}{supposedly caused by declassification of information }
{5010}{}{about the upcoming nuclear war.}
{5011}{}{}
{5012}{}{Deserters took their families and personal belongings}
{5013}{}{with them. It is established that the group took}
{5014}{}{shelter in the vault code-named "Wind of War".}
{5015}{}{That test shelter is located near the city of}
{5016}{}{Pahrump. It was set for purposes of testing building}
{5017}{}{materials, later used in the project of Vault-Tec}
{5018}{}{vaults network, then it was retooled for training}
{5019}{}{purposes of the military base department.}
{5020}{}{Vault coordinates included.}
{5021}{}{}
{5022}{}{The report is dated October 22, 2077.}
{5023}{}{**END-DISK**}

# Free space
{6000}{}{--EMPTY--}
{6001}{}{**END-DISK**}

# Gov. vault: Entries from Stapleton's diary
# GVAR_HOLODISK_ENCLAV_DIARY (GVAR_HOLODISK_SIERRA_EXP_LOG)
{7000}{}{Records from Mr. Stapleton's diary}
{7001}{}{}
{7002}{}{(Records were conducted with variable regularity}
{7003}{}{for several years of residence in the vault. You}
{7004}{}{wrote down the most interesting parts.)}
{7005}{}{}
{7006}{}{**END-PAR**}
{7007}{}{July 9, 2077}
{7008}{}{Doors locked, the vault is sealed. People have mixed}
{7009}{}{feelings. Some are clearly inclined to claustrophobia,}
{7010}{}{seizures and running around the corridors. Our doctor}
{7011}{}{is constantly overwhelmed by work with such idiots.}
{7012}{}{The vice president, after having a mental breakdown,}
{7013}{}{left the dining room with wet pants and for a long}
{7014}{}{time tried to convince everyone that it was spilled}
{7015}{}{Nuka-Cola. By the way, that cola began to eat away}
{7016}{}{his jumpsuit. I wonder, what is it made of?}
{7017}{}{}
{7018}{}{July 15, 2077}
{7019}{}{Things gradually calmed down. The President ordered}
{7020}{}{to turn on the sound of a river in the center of }
{7021}{}{the lawn, opposite dining room. Now it's nice and}
{7022}{}{peaceful there.}
{7023}{}{}
{7024}{}{Aug. 10, 2077}
{7025}{}{All are well accustomed to their rooms and don't}
{7026}{}{want to get out. No one cares about anything, looking}
{7027}{}{only after themselves. The exception is our guards -}
{7028}{}{these poor guys have to endure exercises every}
{7029}{}{day in the gym. They say Private McKinley refused to}
{7030}{}{get out of bed for the training, and for this the}
{7031}{}{sergeant cut his share of Nuka-Cola. Brutal}
{7032}{}{punishment.}
{7033}{}{}
{7034}{}{Sept. 10, 2077}
{7035}{}{Nuka-Cola is causing people to burp more often, makes}
{7036}{}{their tongues colored, but no one is even trying to}
{7037}{}{be remotely worried, because everyone's having kicks}
{7038}{}{with it. A competition began, for the loudest burp}
{7039}{}{possible. Private McKinley is currently in the lead.}
{7040}{}{}
{7041}{}{Sept. 12, 2077. Although the private McKinley}
{7042}{}{got a bit behind in the competition, everyone says}
{7043}{}{that his burp, while not the loudest, is the most}
{7044}{}{resounding. A team of musicians is recruited from}
{7045}{}{the population that will play and sing only with}
{7046}{}{burps of different frequencies. I think I'll}
{7047}{}{fit perfectly for the tenor.}
{7048}{}{}
{7049}{}{Sept. 18, 2077. Damn it! Today a general warning was}
{7050}{}{made that the concerts of burpists are henceforth}
{7051}{}{forbidden, since at this rates of Nuka-Cola}
{7052}{}{consumption it simply won't be any left in the vault.}
{7053}{}{Such a pity. After all, the first concerts of burp-}
{7054}{}{singers were so successful. How would we live now, }
{7055}{}{without their unforgettable compositions?..}
{7056}{}{}
{7057}{}{Sept. 20, 2077. Private McKinley came up with a}
{7058}{}{new competition! Spitting for a long distance! Damn,}
{7059}{}{it is such a great idea! I hope at least this will}
{7060}{}{not be forbidden!}
{7061}{}{}
{7062}{}{Sept. 21, 2077.}
{7063}{}{Private McKinley became a victim of his own idea.}
{7064}{}{While he was trying to spit the cap of a pen, the}
{7065}{}{cap fell into the trachea of the private and}
{7066}{}{he choked to death. The doctor says that the case is}
{7067}{}{unique, and it never happened in his practice.}
{7068}{}{Refused to pull out the cap. Poor cap... I mean,}
{7069}{}{poor private.}
{7070}{}{}
{7071}{}{Sept. 27, 2077. Without the private McKinley it has}
{7072}{}{become boring. Therefore, the overseer ordered}
{7073}{}{to arrange parties in the dining room on Saturdays.}
{7074}{}{Cool. I hope they will give us some Nuka-Cola.}
{7075}{}{}
{7076}{}{Sept. 30, 2077. At the party sergeant had}
{7077}{}{too much cola and beat the vice president. The reason}
{7078}{}{was a dispute about whose burp was cooler - the vice}
{7079}{}{president said that his was more sonorous, and the}
{7080}{}{sergeant claimed that his burp worked best.}
{7081}{}{A fistfight broke out.}
{7082}{}{}
{7083}{}{Sept. 31, 2077. The sergeant and vice-president sat}
{7084}{}{in the dining room at the table, like old friends.}
{7085}{}{Probably, that's how it is.}
{7086}{}{**END-PAR**}
{7087}{}{*********}
{7088}{}{}
{7089}{}{Aug. 5, 2078. There are rumors in the vault that the}
{7090}{}{war did not happen. Of course, ordinary people are}
{7091}{}{not allowed to know this, but what if all this time}
{7092}{}{we were here doing nothing, when outside the world}
{7093}{}{lived just like before? We need to convene a council,}
{7094}{}{so the overseer could explain the whole situation.}
{7095}{}{}
{7096}{}{Aug. 13, 2078. The overseer suddenly announced that}
{7097}{}{the cola synthesizer in the vault broke down, and}
{7098}{}{now we are left without our favorite entertainment.}
{7099}{}{The people are in panic.}
{7100}{}{}
{7101}{}{Aug. 15, 2078. People got tired of waiting, and}
{7102}{}{everyone began to write a petition to the president,}
{7103}{}{so that the cola synthesizer would be quickly fixed.}
{7104}{}{}
{7105}{}{Aug. 20, 2078. Out of nothing to do, residents}
{7106}{}{began to write petitions addressed to the president.}
{7107}{}{I wrote that I want the walls painted in blue, and}
{7108}{}{the neighbor asked for a rope and a piece of soap.}
{7109}{}{I wonder, why he needs them.}
{7110}{}{}
{7111}{}{Aug. 27, 2078.}
{7112}{}{God dammit! Why did my neighbor's request was }
{7113}{}{fulfilled, but not mine? I am so disappointed! What}
{7114}{}{do these damn bureaucrats do in their government}
{7115}{}{office! Maybe I should write another petition?}
{7116}{}{}
{7117}{}{**END-PAR**}
{7118}{}{}
{7119}{}{*********}
{7120}{}{}
{7121}{}{Feb. 5, 2086. The situation is just crappy! The}
{7122}{}{vault is divided into two camps. Some defend the}
{7123}{}{sergeant with his policy of "staying put," while}
{7124}{}{others support the vice president, who calls everyone}
{7125}{}{to leave the vault and help those in need after the}
{7126}{}{war in the outside world. I do not think it's worth}
{7127}{}{sharing our technology with all sorts of radioactive}
{7128}{}{zombies. So far, only the overseer and the president}
{7129}{}{himself remain on the sidelines and are silent about}
{7130}{}{their opinions.}
{7131}{}{}
{7132}{}{March 12, 2086. The fights became so intense that}
{7133}{}{they will soon split the dining room in two!}
{7134}{}{}
{7135}{}{March 13, 2086. It's over. This is the end. Today,}
{7136}{}{after massive drinking of cola, a huge battle between}
{7137}{}{factions broke out. They fought with bare hands, some}
{7138}{}{even with chairs. Why are people so mad? Could it be}
{7139}{}{something in Nuka-Cola, that increases aggression?}
{7140}{}{}
{7141}{}{March 14, 2086. Factions, my ass!}
{7142}{}{They got drunk again! Got in a fight AGAIN!}
{7143}{}{Sergeant hit the president himself, with chair,}
{7144}{}{right in the head! And it fell off!!}
{7145}{}{So, what happens now?..}
{7146}{}{}
{7147}{}{March 15, 2086. Factions made temporary truce to }
{7148}{}{solve the problem of not having the president around.}
{7149}{}{To be precise, the problem is being solved only by}
{7150}{}{the overseer and the doctor. They decided to connect}
{7151}{}{ripped-off head to some cables and try to reanimate}
{7152}{}{it. God knows who needs that, but the idea is}
{7153}{}{quite curious!}
{7154}{}{}
{7155}{}{March 20, 2086. Who would have thought?! Today was }
{7156}{}{held the grand ceremonial turning-on of president's}
{7157}{}{head. And the first words that the head delivered}
{7158}{}{when tumblers switched were: "Goddamn assholes! }
{7159}{}{Where is my doll?!" The doll was found in president's }
{7160}{}{office, then the head calmed down. I say, everyone }
{7161}{}{expected a little different reaction.}
{7162}{}{}
{7163}{}{**END-PAR**}
{7164}{}{April 1, 2087. The head is unbearable!}
{7165}{}{It turns out in all this time it subdued computer}
{7166}{}{systems of the vault. Now we have morbid jokes from }
{7167}{}{loudspeakers, and our donut making machine bakes }
{7168}{}{donuts looking like hangman's noose.}
{7169}{}{It's time to do something! We are too scared to}
{7170}{}{leave our rooms!}
{7171}{}{}
{7172}{}{July 3, 2087. That's it! This hairless bodiless ugly}
{7173}{}{freak annoyed even the overseer! Tomorrow we convene }
{7174}{}{a council meeting to decide what to do with this }
{7175}{}{ripped piece of head.}
{7176}{}{}
{7177}{}{July 4, 2087. Council... doesn't have a decision.}
{7178}{}{As it turns out, we can't just turn the head off.}
{7179}{}{The head became so grown into vault's network} 
{7180}{}{that even somehow manages to control power supply.}
{7181}{}{Long story short, I don't know for how long,} 
{7182}{}{but the question stays opened.}
{7183}{}{}
{7184}{}{Jan. 10, 2090. For the last few years we sat around}
{7185}{}{our rooms, having almost no communications. Head's} 
{7186}{}{stupid jokes had been replaced with straight-up}
{7187}{}{threats. The head complains it hasn't been} 
{7188}{}{listened to, groomed, had its heels combed enough.}
{7189}{}{Place became dangerous. Head has a mental breakdown,} 
{7190}{}{like we all. Some say it even controls security}
{7191}{}{turrets a little. I wonder if it's true.}
{7192}{}{**END-PAR**}
{7193}{}{Jan 15, 2090. We are leaving.}
{7194}{}{Farewell, donut making machine.}
{7195}{}{Farewell, Nuka-Cola.}
{7196}{}{I will never forget you.}
{7197}{}{**END-DISK**}


# Gov. vault: Medical report on the head
# GVAR_HOLODISK_ENCLAV_MED (GVAR_HOLODISK_SIERRA_MED_LOG)
{8000}{}{}
{8001}{}{Report on the mental state of president's head}
{8002}{}{}
{8003}{}{Objective: find out reasons behind head's aggression}
{8004}{}{Chief resident: Solomon M.D.}
{8005}{}{**END-PAR**}
{8006}{}{We performed a conversation with the head of former}
{8007}{}{president. The conclusions are disappointing. For a}
{8008}{}{few years in absence of natural human communications}
{8009}{}{the head lost control of its fantasies}
{8010}{}{and frequently takes its thoughts for reality.}
{8011}{}{The head has a tendency to identify itself with}
{8012}{}{its doll. In addition to long absence of}
{8013}{}{communication, the reasons for aggression lies in}
{8014}{}{initially excessively increased egocentrism.}
{8015}{}{Head demands attention, and, while not provided}
{8016}{}{enough with it, chooses more and more radical and}
{8017}{}{harsh measures to get the desirable.}
{8018}{}{I'm afraid, in a few years, the head is prone to}
{8019}{}{become an uncontrollable psychopath.}
{8020}{}{}
{8021}{}{Long-term psychological treatment is required.}
{8022}{}{}
{8023}{}{**END-DISK**}

# Gov.vault: exodus
# GVAR_HOLODISK_ENCLAV_ISHOD (GVAR_HOLODISK_SIERRA_EVACUATION)
{9000}{}{This disk contains various information}
{9001}{}{from main terminal of government vault,}
{9002}{}{including records about last days before "exodus" -}
{9003}{}{event, which led its habitants to leave the vault.}
{9004}{}{ }
{9005}{}{The main point is that vault was created}
{9006}{}{for government elite of United States}
{9007}{}{including president, his family and service staff.}
{9008}{}{The vault was equipped with the latest technologies,}
{9009}{}{but this still didn't help its dwellers. After}
{9010}{}{sealing the vault, the incident has happened to the}
{9011}{}{president - his head was torn off. The head was then}
{9012}{}{reanimated in laboratory, to preserve the innermost}
{9013}{}{knowledges president had, but with time it became too}
{9014}{}{egocentric, when lacked attention for long, which has}
{9015}{}{also led to its increasingly despotic behavior.}
{9016}{}{Banters and jokes on vault's habitants have been}
{9017}{}{replaced with threats to health and life. }
{9018}{}{Recommendations to turn the head off was overly late-}
{9019}{}{the head somehow managed to subjugate vault's}
{9020}{}{network and robotics, including defense systems. Any}
{9021}{}{further misstep could be vital for vault's residents.}
{9022}{}{In the end, a decision was made - to leave the vault}
{9023}{}{and relocate to governmental reserve base at the oil}
{9024}{}{rig, deep into ocean. However, in the day of}
{9025}{}{departing, the head tried to stop the fugitives.}
{9026}{}{ }
{9027}{}{A group of security guards decided to destroy the} 
{9028}{}{head's storage tank, but when they got into }
{9029}{}{laboratory, the battle with head-controlled}
{9030}{}{automated turrets occurred, which led to all }
{9031}{}{guards being killed. After that, head tried to}
{9032}{}{exterminate everyone turrets could get. Still,}
{9033}{}{most of dwellers made it to safety, including the}
{9034}{}{current president. They managed to take the most }
{9035}{}{valuable equipment and machinery, and get away.}
{9036}{}{ }
{9037}{}{The vault has been abandoned.}
{9038}{}{**END-DISK**}


# Jay Kukish's message
# GVAR_HOWTHORNE_DSK_BAIKER_MSG (GVAR_SIERRA_MISSION_HOLODISK)
{10000}{}{I didn't expect you to come this far.}
{10001}{}{Still, if you did - this is not accidental.}
{10002}{}{You'll have to try hard to get to meet me.}
{10003}{}{Infiltrate military hangar V9 on the north, find the}
{10004}{}{radio signal's jammer. To lower the risks, I suggest}
{10005}{}{you to turn off the power in the underground level.}
{10006}{}{Next, plant the jammer into radar equipment}
{10007}{}{on the second floor of the garrison building}
{10008}{}{and wait for me near the exit.}
{10009}{}{That is all.}
{10010}{}{**END-DISK**}

# Case with docs from radio station
# GVAR_SHAIEN_RADIO_KEISHOLODISK (GVAR_SIERRA_GNN_HOLODISK)
{11000}{}{The case from radio station contains dense pack}
{11001}{}{of documents and disks. They might seem as}
{11002}{}{useless garbage, if not for their secrecy.}
{11003}{}{In addition, the part of information is encrypted,}
{11004}{}{which also leads to some thoughts.}
{11005}{}{}
{11006}{}{Apparently, a radio station in Lovelock was one of}
{11007}{}{key points for military broadcasting. Here, the links}
{11008}{}{were maintained between the General Staff, military}
{11009}{}{bases, a network of vaults and laboratories.}
{11010}{}{If necessary, the channels could also be tapped here.}
{11011}{}{}
{11012}{}{Among the documents you suddenly discover}
{11013}{}{surveillance reports on Vault 8:}
{11014}{}{external and internal communications records,}
{11015}{}{computer systems data interception, etc.}
{11016}{}{The Vault has been under the close supervision of the}
{11017}{}{military - information was transmitted directly into}
{11018}{}{Hawthorne military base.}
{11019}{}{}
{11020}{}{It will take time to decipher all}
{11021}{}{documentation, but it is already clear that it can}
{11022}{}{be of great value to your city.}
{11023}{}{**END-DISK**}

# Wind of War's history
# GVAR_WIND_HISTORY_HOLODISK (GVAR_ELRON_HOLODISK)
{12000}{}{Short history of Wind of War}
{12001}{}{}
{12002}{}{(Audio recorded conversation with military personnel)}
{12003}{}{}
{12004}{}{All of us are the descendants of people who made it}
{12005}{}{through the war in safe vault. Our ancestors were of}
{12006}{}{elite military unit from Hawthorne military base.}
{12007}{}{At least, that's what they told us.}
{12008}{}{When there were no one left to save in Nevada, they}
{12009}{}{took shelter in prototype vault not far from here.}
{12010}{}{The vault had codename "Wind of War",}
{12011}{}{it was built specifically for testing purposes of the}
{12012}{}{materials and technologies of vaults network."}
{12013}{}{}
{12014}{}{}
{12015}{}{Time has passed, then we were born, still sealed}
{12016}{}{inside the vault. When its resources ran out,}
{12017}{}{we had to go outside and start a new life}
{12018}{}{struggling for a place under the sun.}
{12019}{}{General Wesker took the situation under control.}
{12020}{}{We settled in this ruins, rebuilt them,}
{12021}{}{brought some weapons and tech from Hawthorne.}
{12022}{}{Then blew up the vault and started to live here.}
{12023}{}{But, turned out, we are not very much suitable for}
{12024}{}{agricultural farming, yet we needed to survive. So,}
{12025}{}{for the most part, we lived off the hunt. This area}
{12026}{}{is mostly desert, so providing ourselves with}
{12027}{}{food was not that easy. Then the "aliens" came,}
{12028}{}{and it became especially hard.}
{12029}{}{So, general resorted to different source of income -}
{12030}{}{we became protectors for small settlements and}
{12031}{}{transit point for caravans.}
{12032}{}{Albeit slowly, our life started to come together."}
{12033}{}{**END-DISK**}


# robot-stagecoacher memory card
# GVAR_NEW_RENO_DILIZHAS_ROBOTMODUL (GVAR_RESERVED_VAR13)
{13000}{}{}
{13001}{}{}
{13002}{}{Here's gathered important information, deciphered}
{13003}{}{from DVR of guard robot, escorting stagecoach}
{13004}{}{from Salt Lake city to New Reno.}
{13005}{}{}
{13006}{}{As it turns out, bikers didn't attack the stagecoach,}
{13007}{}{this was made by members of the crew - the very same}
{13008}{}{members, who later returned to the city and blamed it}
{13009}{}{on biker gang.}
{13010}{}{}
{13011}{}{This information will definitely gather interest}
{13012}{}{of several people simultaneously.}
{13013}{}{}
{13014}{}{**END-DISK**}

# Armstrong
# GVAR_LIST_ARMSTRONG_PANIHIDA (GVAR_VAULT_CITY_DESIGNER_NOTES)
{14000}{}{Article from "Washington post" newspaper:}
{14001}{}{}
{14002}{}{The death of Louie Armstrong caused genuine flood}
{14003}{}{of the most sincere and deepest condolences.}
{14004}{}{Many newspapers, not only in US, but also in other}
{14005}{}{countries, posted articles about him passing away}
{14006}{}{on their first pages.}
{14007}{}{}
{14008}{}{Funeral service went very commemorative, with the}
{14009}{}{TV broadcasting it everywhere throughout the country.}
{14010}{}{On July 8, the body had been exhibited for ceremonial}
{14011}{}{farewell in the National Guards' training hall,}
{14012}{}{provided for these purposes by personal order by}
{14013}{}{the president of United States.A statement}
{14014}{}{made by President Nixon reads:}
{14015}{}{}
{14016}{}{"Mrs. Nixon and I share the sorrow of millions}
{14017}{}{of Americans at the death of Louis Armstrong.}
{14018}{}{One of the architects of an American art form,}
{14019}{}{a free and individual spirit, and}
{14020}{}{an artist of worldwide fame,}
{14021}{}{his great talents and magnificent spirit}
{14022}{}{added richness and pleasure to all our lives."}
{14023}{}{**END-PAR**}
{14024}{}{**END-DISK**}

# Notes of the trapped man
# Author of text- Kerb (Alexander Agafontsev)
# GVAR_HOLODISK_SALT_MINIVAULT (GVAR_NCR_SPY_HOLO_DOWNLOAD)
{15000}{}{}
{15001}{}{(A plain notebook in a shabby leather cover.}
{15002}{}{The first pages are filled with accurate slim}
{15003}{}{handwriting, but as it goes you can hardly read}
{15004}{}{choppy erratic letters on blood-stained crumpled}
{15005}{}{sheets.)}
{15006}{}{}
{15007}{}{}
{15008}{}{}
{15009}{}{Day 1}
{15010}{}{}
{15011}{}{For the fuck's sake, I did it! Feel free to}
{15012}{}{mince, even eat each other alive -  }
{15013}{}{I'm gonna sit this one out in here. Yeah,}
{15014}{}{I learned my lesson well, I know how to wait...}
{15015}{}{I would very much like you to know that, Watkins!}
{15016}{}{And you, Kurowski, you fucking pshek...}
{15017}{}{That's okay, I won't forget you. All of you.}
{15018}{}{I'm gonna come piss on your graves!}
{15019}{}{Still, never made the last trip for food...}
{15020}{}{Somehow decided not to go outside anymore.}
{15021}{}{For now. I'm not scared. No, just cautious... }
{15022}{}{I got my nerves right, all is going ok,}
{15023}{}{should be only like that, starting now...}
{15024}{}{}
{15025}{}{Day 2}
{15026}{}{}
{15027}{}{Mostly sleeping, stuffing belly.}
{15028}{}{Can't read for long - the light for me is still}
{15029}{}{non-renewable resource.}
{15030}{}{Heard couple of shots outside. Has it started?}
{15031}{}{}
{15032}{}{Day 3}
{15033}{}{}
{15034}{}{Shit! Looks like they got off their chains there!!}
{15035}{}{Shooting and explosions all day long, screams...}
{15036}{}{Heard one of them got dumped right at my door...}
{15037}{}{He yells non-stop, just like cattle in a butchery.}
{15038}{}{Damn it, someone, finish him off already...}
{15039}{}{}
{15040}{}{Day 4}
{15041}{}{}
{15042}{}{At last, he got quiet. Died or just fainted...}
{15043}{}{Interestingly, I kind of got little used to poor}
{15044}{}{fella - even talked something to him...}
{15045}{}{One-sided, of course, hehe...}
{15046}{}{Now it's quiet, so very quiet...}
{15047}{}{}
{15048}{}{Day 5}
{15049}{}{}
{15050}{}{I would have never thought what torture it is - }
{15051}{}{being in complete silence...}
{15052}{}{I talk to myself all the time, clatter with equipment}
{15053}{}{only to get it away from me for another moment...}
{15054}{}{}
{15055}{}{Day 6}
{15056}{}{}
{15057}{}{Woke up at night, because felt}
{15058}{}{someone nearby... Light doesn't drive darkness away,}
{15059}{}{only makes it clog into farther corners...}
{15060}{}{No, that can't be, I'm all alone here...}
{15061}{}{Alone in the dark... Hah-hah...}
{15062}{}{}
{15063}{}{Day 7}
{15064}{}{}
{15065}{}{No more light...}
{15066}{}{Silence drills my brains out, darkness squeezees}
{15067}{}{eyes... Still - no sound! That's exactly what}
{15068}{}{It waits for... Or is it?.. What? I am alone, am I?}
{15069}{}{I'm confused... no sleeping yet...}
{15070}{}{The clock became useless - time has stopped...}
{15071}{}{What's it like - not to sleep for eternity?}
{15072}{}{}
{15073}{}{Day ?}
{15074}{}{}
{15075}{}{Less food, water, life...}
{15076}{}{Silence already inside of me...}
{15077}{}{Starting to devour my innards...}
{15078}{}{Slowly...}
{15079}{}{Keeping myself without sleep, It can't hurt me}
{15080}{}{if I'm not sleeping... Or }
{15081}{}{if I don't make any noise? What if It's not alone?..}
{15082}{}{}
{15083}{}{out of time}
{15084}{}{}
{15085}{}{Out of food...}
{15086}{}{Can't get out - the door is blocked by debris...}
{15087}{}{Or the lock got broken...}
{15088}{}{Or someone is waiting for me there...}
{15089}{}{I can't go out, I can't, shouldn't go out,}
{15090}{}{I should not........... That's my day babe!!!}
{15091}{}{I'm gonna trick'em!!! They can't eat me,}
{15092}{}{if I eat myself!!! Ha-ha!!}
{15093}{}{They didn't expect me to get junked full with}
{15094}{}{painkillers, with loads of them!..}
{15095}{}{They knocked the spirits out of me, but I still}
{15096}{}{managed to gouge my eyes out...}
{15097}{}{Suck on that, darkness!}
{15098}{}{Cut off left hand to the elbow...}
{15099}{}{Only not to forget to drink blood...}
{15100}{}{Silence won't get any, even the slightest drop...}
{15101}{}{Ears and tongue are next in line...}
{15102}{}{...They are surely counts as delicate dish...}
{15103}{}{...So let them bite me!..}
{15104}{}{**END-DISK**}


# Officer's audio logs in Area 51
# Author of text- Kerb (Alexander Agafontsev)
# GVAR_ZONA_SOLDAT_AUDIO_HOLODISK (GVAR_NCR_HISTORY_HOLO_DOWNLOAD)
{16000}{}{Officer's audio logs}
{16001}{}{}
{16002}{}{[Someone's confident, husky voice is heard}
{16003}{}{through noise in the background]}
{16004}{}{}
{16005}{}{**END-PAR**}
{16006}{}{}
{16007}{}{August 3,  2077}
{16008}{}{}
{16009}{}{[Sound of boots rumbling the ground is faintly heard;}
{16010}{}{then goes the order "Atten-Shun! Double time, MARCH!"}
{16011}{}{You can't hear the words well, but looks like}
{16012}{}{the squadrons are singing some kind of army song]}
{16013}{}{}
{16014}{}{So, after the morning drill, our three-starred}
{16015}{}{vicar of god on earth wielding general straps made}
{16016}{}{me happy with the fact that instead of my planned}
{16017}{}{Chinese vacation, keeping company to almost}
{16018}{}{dead-beaten gooks, I'm going to headline the}
{16019}{}{second platoon into "Area 51". Why'd they think it's}
{16020}{}{insufficient to have just local guards is beyond me.}
{16021}{}{And, if it's still not enough, we got some civilian }
{16022}{}{science guys attached to us - what's they called...}
{16023}{}{Zeeno... Shmeeno... -tists, something like that.}
{16024}{}{One of them dickheads asked me to supply them}
{16025}{}{with weapons. I got my laughs. They can't even hold}
{16026}{}{their thing straight by the toilet, what to say about}
{16027}{}{rifles. Well, let's see how it's gonna turn out...}
{16028}{}{}
{16029}{}{**END-PAR**}
{16030}{}{}
{16031}{}{August 14, 2077}
{16032}{}{}
{16033}{}{Long story short - we're fucked. Long story long -}
{16034}{}{we have to guard aliens. And no, I didn't get myself}
{16035}{}{drunk until I could see little green men, although}
{16036}{}{I strongly feel like I want to. That's the nickname}
{16037}{}{locals gave them. If that was somebody's}
{16038}{}{stupid fucking joke, he did it right.}
{16039}{}{When we arrived, head of security ditched any}
{16040}{}{briefings - he just took us to the cells with that}
{16041}{}{creatures. What a brilliant plan of his.}
{16042}{}{I got full pants of experience.} 
{16043}{}{One stare in their pie hole - and you instantly have}
{16044}{}{desire to do heroics deeds somewhere in war zones of}
{16045}{}{China, or storm Anchorage's cliffs for the second time,}
{16046}{}{only let it be many, many miles away from here.}
{16047}{}{Official version says that their ship crash-landed}
{16048}{}{somewhere around here, not far from the Groom lake.}
{16049}{}{Fellow intelligent beings, blah-blah-blah...}
{16050}{}{What kind of bullshit is this?! Ask me, this is all}
{16051}{}{created by experiments of that eggheads, like the}
{16052}{}{ones who got dragged with us here. Just look at them,}
{16053}{}{eyes glued to that cells. Researchers, my ass...}
{16054}{}{}
{16055}{}{**END-PAR**}
{16056}{}{}
{16057}{}{September 2, 2077}
{16058}{}{}
{16059}{}{Already got fed up with the scientists. They are}
{16060}{}{always complaining - about the strict security, about}
{16061}{}{escort... Oh, and also, that assholes - PFC Jones and}
{16062}{}{corporal Sterling - managed to get wasted with}
{16063}{}{booze... Sterling now gets dicks instead of}
{16064}{}{sergeant's skits. McCoy, the head of security,}
{16065}{}{suddenly helped - got us camera footage showing how}
{16066}{}{one of this alien monsters broke loose somewhere}
{16067}{}{around six months ago. While it got dealt with,}
{16068}{}{cornered near the sealed shut rooms in C-sector}
{16069}{}{(by the way, why sealed shut? What a good question),}
{16070}{}{it massacred most of the security guards there.}
{16071}{}{So, everyone's calmed down for a while. How long}
{16072}{}{will it last?..}
{16073}{}{}
{16074}{}{}
{16075}{}{**END-PAR**}
{16076}{}{}
{16077}{}{September 10, 2077}
{16078}{}{}
{16079}{}{Doing our homework. Checking durability of these}
{16080}{}{things. 5mm, 7,62 or even 9 are not much of use -}
{16081}{}{like flies to the elephant, armor-piercing included.}
{16082}{}{Of course, you have some results, but to spend half}
{16083}{}{of squad's ammo on one target is definitely not a}
{16084}{}{good choice. Laser or electricity - all the same.}
{16085}{}{High-foreheads are trying poisons and radiation,}
{16086}{}{but still no visible effects. Well, tomorrow}
{16087}{}{we're gonna get our hands on heavy weaponry.}
{16088}{}{By the way, managed to get some steam off - one of}
{16089}{}{these local snitches tried to break into my tablet.}
{16090}{}{It turned out pretty well for him - any bones can}
{16091}{}{grow back together just in a couple of weeks.}
{16092}{}{}
{16093}{}{**END-PAR**}
{16094}{}{September 12, 2077}
{16095}{}{}
{16096}{}{Things got a little more lively. Couldn't help myself-}
{16097}{}{shot one dead using Bozar. By now, flamethrowers are}
{16098}{}{proven to be the best option. Guys are having much}
{16099}{}{fun, even drew a couple of big-brains to hang around.}
{16100}{}{One said that these creatures see us}
{16101}{}{in infrared, or kind of.}
{16102}{}{Heat fields, thermal waving, all that stuff...}
{16103}{}{That's the only useful information we got from any}
{16104}{}{of these nerds for all our time here, by the way.}
{16105}{}{And all seems normal, but...}
{16106}{}{I am not especially easy to impress or scare, but for}
{16107}{}{some time I have a feeling like somebody tries to}
{16108}{}{rack my brain, or something...}
{16109}{}{Maybe this place weighs on me?}
{16110}{}{}
{16111}{}{**END-PAR**}
{16112}{}{}
{16113}{}{October 3, 2077}
{16114}{}{}
{16115}{}{One of the eggheads - Hubbard - flew off the handle.}
{16116}{}{He started yelling at us, like, we are destroying}
{16117}{}{sentient life form, and, like, we should try to reach}
{16118}{}{some kind of peaceful agreements, then jiggled around}
{16119}{}{with that silly reports of his... he somehow found}
{16120}{}{out about my Russian ancestry and called me a}
{16121}{}{communist pig. After that, he made his best decision}
{16122}{}{to enter into one of the cells. [laughs]}
{16123}{}{I can now make a proud statement, that special forces}
{16124}{}{did not become an obstacle in the way of scientific}
{16125}{}{progress. I believe, that the diplomacy is far more}
{16126}{}{effective nowadays than any weapon. Love and peace}
{16127}{}{and such. Don't mind alien flaying guy's bloody guts}
{16128}{}{all around its cell - these must be, like, some local}
{16129}{}{customs of theirs, you should, like, treat them}
{16130}{}{with understanding and such.}
{16131}{}{----}
{16132}{}{Around flight level 117 UAV detected some kind of}
{16133}{}{suspicious activity in its patrol area.}
{16134}{}{Tomorrow investigating, bringing two units.}
{16135}{}{}
{16136}{}{**END-PAR**}
{16137}{}{}
{16138}{}{October 19, 2077}
{16139}{}{}
{16140}{}{Jones went missing. With one of security guards.}
{16141}{}{This base has some "dead zones" near C-sector,}
{16142}{}{with restricted access. Still, why do they needed to}
{16143}{}{go in there? Now we are walking around in groups of}
{16144}{}{two, patrolling, checking the perimeter...}
{16145}{}{Inside my head is a damn mess... Everyone stays}
{16146}{}{on alert... new order arrived from HQ -}
{16147}{}{await for further instructions...}
{16148}{}{}
{16149}{}{**END-PAR**}
{16150}{}{}
{16151}{}{October 21, 2077}
{16152}{}{}
{16153}{}{Something slipped into security guards barracks and}
{16154}{}{slaughtered all the shifted guys... everything there}
{16155}{}{is a bloodbath, from floor to ceiling, shredded meat}
{16156}{}{and innards everywhere... Communication with HQ}
{16157}{}{is gone... Security systems are constantly failing,}
{16158}{}{we partially lost control over the base... Now we }
{16159}{}{are sweeping the perimeter with two units,}
{16160}{}{the remaining two are holding positions...}
{16161}{}{}
{16162}{}{**END-PAR**}
{16163}{}{}
{16164}{}{October 22, 2077}
{16165}{}{}
{16166}{}{[Shots of large- and small-caliber guns are heard,}
{16167}{}{explosions, screams, alarms wailing. Sometimes}
{16168}{}{some kind of screeches gets past all of this,}
{16169}{}{going over into hissing]}
{16170}{}{}
{16171}{}{So, no more questions left, but the answers are also}
{16172}{}{no joy... That thing, which was murdered half a year}
{16173}{}{ago, turned out to be female of the species...}
{16174}{}{she somehow managed to lay eggs into sealed}
{16175}{}{facilities of the base, before meeting her demise...}
{16176}{}{Once we cracked the doors - all hell broke loose...}
{16177}{}{PFC Irons and lieutenant Parker scorched the first}
{16178}{}{wave with flamethrowers, but then these maggots}
{16179}{}{got us from behind... I kept tearing them with}
{16180}{}{bursts, until one of them caught my hand and }
{16181}{}{chewed it... I got away by stabbing the thing...}
{16182}{}{Hide myself in the warehouse of H-block...}
{16183}{}{}
{16184}{}{**END-PAR**}
{16185}{}{}
{16186}{}{}
{16187}{}{October 25, 2077}
{16188}{}{}
{16189}{}{[For some time, only weak, raspy breathing is heard]}
{16190}{}{}
{16191}{}{I'm the only one left... shootings turned into melee,}
{16192}{}{then I got knocked out... now it's all quiet...}
{16193}{}{Barely holding on my feet, my hand won't obey me...}
{16194}{}{Drugged myself to the point of seeing}
{16195}{}{hallucinations... Can't think straight...}
{16196}{}{I don't hope for the rescue coming - after we skipped}
{16197}{}{response to the status report signal, ERT should've}
{16198}{}{been here already...}
{16199}{}{But there's something even I can do...}
{16200}{}{Put some cordex on myself, as much as I}
{16201}{}{managed to lift...}
{16202}{}{Aiming to get more of these bastards with me,}
{16203}{}{so wish me luck...}
{16204}{}{One of my ancestors destroyed the whole "Tiger" tank}
{16205}{}{in the World War II in a similar way... in the end,}
{16206}{}{even alone, one special forces officer is a capable}
{16207}{}{battle unit in a nutshell...}
{16208}{}{So... Commence the operation!}
{16209}{}{**END-DISK**}


# Free space
{17000}{}{--EMPTY--}
{17001}{}{**END-DISK**}

# Free space
{18000}{}{--EMPTY--}
{18001}{}{**END-DISK**}

# Salt Lake city, criminal case 4783
# GVAR_HOLODISK_SALT_RAPORT
{19000}{}{Criminal case #4783}
{19001}{}{}
{19002}{}{[ A criminal case file, fairly battered by}
{19003}{}{rodents, humid and time. But some of the text}
{19004}{}{could still be comprehended. ]}
{19005}{}{}
{19006}{}{[ Leather-case diary with an elegant religion-themed}
{19007}{}{lettering. ]}
{19008}{}{}
{19009}{}{Day I}
{19010}{}{}
{19011}{}{Today Emily confessed that she took a flower from our}
{19012}{}{neighbor's garden, Mr. Flowers, without allowance.}
{19013}{}{We gave apologies with the whole our family to}
{19014}{}{this worthy man, and he favorably accepted it.}
{19015}{}{As I'm writing this, Emily strenuously prays to our}
{19016}{}{Lord for forgiveness. She does it voluntarily, as}
{19017}{}{the seed of faith made sprouts in her innocent soul,}
{19018}{}{which delights my relentless heart greatly...}
{19019}{}{But back to the point! My flock awaits of its}
{19020}{}{shepherd, as even in meadows of Paradise it is}
{19021}{}{bequeathed to us to toil tenaciously, in the name}
{19022}{}{of Our Lord!}
{19023}{}{}
{19024}{}{Day II}
{19025}{}{}
{19026}{}{Bitter news came to our little town - Mrs. Schultz's}
{19027}{}{son, major Otto Schultz, perished in the Gilan}
{19028}{}{province... I will definitely visit this poor sob}
{19029}{}{by today's evening.}
{19030}{}{Hope I could relieve her sorrows and help to}
{19031}{}{reconcile with our Lord...}
{19032}{}{Why can't people live in peace? After all, we are}
{19033}{}{brothers, in the all-seeing eyes of our Father...}
{19034}{}{}
{19035}{}{Day III}
{19036}{}{}
{19037}{}{Judgment Day has come... All that occurred recently I}
{19038}{}{can only recollect in fragments... Alarm sirens, akin}
{19039}{}{to the Jericho trumpets... My poor Mary and Emily,}
{19040}{}{packing their belongings hastily... Stampede...}
{19041}{}{Elderly couple, trampled by cattle in fear-induced}
{19042}{}{rage... Pavements, covered in blood... Doors to the}
{19043}{}{Mr. Flowers' family shelter, which granted asylum to}
{19044}{}{almost three dozens of refugees... But there is one}
{19045}{}{thing I remember clearly - before security cameras}
{19046}{}{went off, I witnessed the fireball on the}
{19047}{}{horizon, expanding rapidly, greedily consuming}
{19048}{}{souls of the poor lambs of God...}
{19049}{}{And the dazzling flash...}
{19050}{}{Our demise came from the skies, looking like}
{19051}{}{hellfire, breaking out from the ground...}
{19052}{}{}
{19053}{}{Day IV}
{19054}{}{}
{19055}{}{Lord Almighty, give me strength... Mary, my sweet}
{19056}{}{Mary... Mr. Flowers said that shelter doesn't}
{19057}{}{provide enough protection from radiation...}
{19058}{}{Medicines we took made her suffer heavy allergic}
{19059}{}{reactions... Still see her swollen hands, covered}
{19060}{}{with stains, reaching to me...}
{19061}{}{Eyes, blurred with pain...}
{19062}{}{Hear eerie cries...}
{19063}{}{Why Our Lord is so cruel to me?}
{19064}{}{She needs me so much in her last moments, but}
{19065}{}{my strength is ebbing away...}
{19066}{}{}
{19067}{}{Day V}
{19068}{}{}
{19069}{}{Praise our Lord! Oh, why I was so blind...}
{19070}{}{I abstained myself, fostering my spirit through}
{19071}{}{prayers, and the revelation came upon me! All,}
{19072}{}{that happened, is the Greater Plan of our Maker}
{19073}{}{to ascend all suffering souls to heaven! That flash,}
{19074}{}{which nearly blinded me, was the light of Pearly}
{19075}{}{Gates of Heaven, opening for all the righteous}
{19076}{}{and faithful! And we were lured into this purgatory}
{19077}{}{by the servants of Satan, tempting us with}
{19078}{}{false promises of safety, in defiance of}
{19079}{}{Our Father's will... Mary, I know you are}
{19080}{}{waiting for me in Heaven, but I'm the Shepherd}
{19081}{}{of our God's lambs, and I still have unfinished}
{19082}{}{business to do on this wicked, sinful earth... }
{19083}{}{Still, our daughter will join you soon, no matter}
{19084}{}{how much it saddens me to part ways with her...}
{19085}{}{}
{19086}{}{Day VI}
{19087}{}{}
{19088}{}{Today I opened the gates to let the light of our}
{19089}{}{Maker, called "radiation" by ignorant fools, to shine}
{19090}{}{upon this condemned place. Devil's spawn, disguised}
{19091}{}{as Mr. Flowers, tried to stop me, but fire axe in my}
{19092}{}{hands, like a blazing sword of Archangel, chopped}
{19093}{}{squealing messenger of Satan to pieces.}
{19094}{}{Oh yes, many of them died by my hand that day...}
{19095}{}{There is no food left, but with the power of our Lord}
{19096}{}{I communed with their flesh and blood, which tasted}
{19097}{}{better than any wine for me...}
{19098}{}{But Mary, the most important thing! Our sweet and }
{19099}{}{lovely child is on the way to you!}
{19100}{}{For some reason, she resisted stubbornly, when}
{19101}{}{I was squeezing last breath from her mortal flesh...}
{19102}{}{Maybe I should've, cleared blood from my face}
{19103}{}{and cleaned my clothes beforehand?}
{19104}{}{}
{19105}{}{Day VII}
{19106}{}{}
{19107}{}{I'm done here, but there's so much more poor souls}
{19108}{}{left for me to send to the Pearly Gates of Heaven...}
{19109}{}{The flesh of mine is changing under the influence of}
{19110}{}{our Lord, which makes some inconvenience...}
{19111}{}{But I believe - it's all for the best cause!}
{19112}{}{Rejoice, righteous men! Faithless, be frightened!}
{19113}{}{Because I am coming for you...}
{19114}{}{}
{19115}{}{[Fragments of crime scene investigation reports]}
{19116}{}{}
{19117}{}{Examination started: 19:1...}
{19118}{}{Examination ended...}
{19119}{}{}
{19120}{}{...One-storey brick building...}
{19121}{}{Room's size inside: 6.5m X ...}
{19122}{}{Man, Caucasian... Crucified upside-down on the}
{19123}{}{western wall... Left leg partially skinned...}
{19124}{}{Multiple bite marks on face, neck, abdominal areas...}
{19125}{}{Woman... Head missing... Based on the type of wound,}
{19126}{}{it was probably torn off...}
{19127}{}{}
{19128}{}{Examination...}
{19129}{}{}
{19130}{}{...Meadow to the north-west of...}
{19131}{}{Stakes, about 2 meters high... Placed in the}
{19132}{}{shape of cross... Men and women... Impaled...}
{19133}{}{Sex of some victims could not be identified due to}
{19134}{}{heavy damage and body parts missing...}
{19135}{}{Some inscriptions are seen on intact skin...}
{19136}{}{Probably, Latin...}
{19137}{}{}
{19138}{}{Evidence, collected at the crime scene:}
{19139}{}{1. Wooden crucifix...}
{19140}{}{2. Leather-case book...}
{19141}{}{[Surprisingly well-preserved post card picturing}
{19142}{}{not-so-dressed movie star of a particular genre.}
{19143}{}{The other side of it covered with impeccable}
{19144}{}{calligraphic handwriting:]}
{19145}{}{}
{19146}{}{"Good day, Sheriff Crouch! Bringing to your}
{19147}{}{attention, that I, together with detective Hastings,}
{19148}{}{am going on search for our John Doe. Case file}
{19149}{}{records helped us establish his estimated whereabouts}
{19150}{}{and also the fact, that he probably will soon go}
{19151}{}{hunting again; we decided not to wait for your}
{19152}{}{squad to return from the Rotten Crag.}
{19153}{}{I'm assuming you will question loudly:}
{19154}{}{And why would some priest poke into this business?}
{19155}{}{(of course, you will use not so gentle expressions}
{19156}{}{and won't be as elegant at all).} 
{19157}{}{Well, what could I say...}
{19158}{}{That poor man was once my brother-in-faith,}
{19159}{}{quite eager in his duty to help those who suffered.}
{19160}{}{And then, when he himself became the one who}
{19161}{}{needed help... Although late in coming, I}
{19162}{}{still want to help him to rest in peace.}
{19163}{}{}
{19164}{}{}
{19165}{}{}
{19166}{}{"He will wipe every tear from their eyes and then}
{19167}{}{there will be no more death, or mourning, or crying,}
{19168}{}{or pain, as the old order of things passed away".}
{19169}{}{}
{19170}{}{                                  Rev. McClaine}
{19171}{}{}
{19172}{}{P.S. And, for the love of heaven, don't waste all}
{19173}{}{the paper on cigarette roll-ups! Just imagine if}
{19174}{}{you would need to write a letter, probably the last}
{19175}{}{one, on a picture of a sinful damsel (not that}
{19176}{}{attractive too, I must say!) Although, knowing your}
{19177}{}{tastes, I suppose that would be your most}
{19178}{}{preferable option. Therefore, if I shall not return}
{19179}{}{safely, my assistant will impose 10-year penance}
{19180}{}{upon you. So, it's in your best interests to pray}
{19181}{}{for our success."}
{19182}{}{**END-DISK**}


# Commercial holodisk of stagecoach
# GVAR_HOLODISK_DILIZHANS_INFO -- GVAR_HOLODISK_ENCLAVE_WORD
{20000}{}{}
{20001}{}{So, you decided to make some money on the sale of}
{20002}{}{beads and fire water to Cheyenne savages? Or want} 
{20003}{}{to start a new life in Vegas, because of problems}
{20004}{}{with a particular sheriff (everybody knows}
{20005}{}{who I'm talking about), but too afraid to go cross}
{20006}{}{the wasteland, because of the wild beasts and}
{20007}{}{head-frosted raiders?}
{20008}{}{Well, what can I say - you are right, our}
{20009}{}{blessed land is not the best place for a walk. But}
{20010}{}{today is your lucky day, gentlemen! Uncle Joe and}
{20011}{}{the "Nevada Express" will protect your sorry ass from}
{20012}{}{harassment of humans and non-humans of all shades}
{20013}{}{and colors! Have spare 1000 bucks? Just enough!}
{20014}{}{(In addition, we are always ready to negotiate!)}
{20015}{}{}
{20016}{}{1. Who are you guys? What the hell is a stagecoach?}
{20017}{}{}
{20018}{}{We are a team of professionals in logistics and}
{20019}{}{in beating the shit out of those, who wish to do harm}
{20020}{}{to our valued customers. Some companies consider you}
{20021}{}{only as potential content for coffins, but we}
{20022}{}{consider you as a potential member of our strong and}
{20023}{}{solid family!}
{20024}{}{}
{20025}{}{2. Hmm, is it really so safe with you around?}
{20026}{}{}
{20027}{}{Come to any of our offices and see for yourself the}
{20028}{}{bearing and equipment of our guys! We can modestly}
{20029}{}{assume that if Jesus himself were going to go on a}
{20030}{}{voyage in the Wasteland, he would have definitely}
{20031}{}{chosen the "Nevada Express"! Anyone then would be}
{20032}{}{crucified, but not him.}
{20033}{}{}
{20034}{}{3. And how long have you been in this business?}
{20035}{}{}
{20036}{}{Long enough for most of our competitors to turn to}
{20037}{}{dust. As early as 2050, caravans of our founding}
{20038}{}{fathers plowed through the expanses of every state.}
{20039}{}{Of course, the scale of our market now is not quite}
{20040}{}{like that, but quality of services has improved}
{20041}{}{greatly.}
{20042}{}{}
{20043}{}{4. About the scale, by the way. How far and where}
{20044}{}{do your caravans go?}
{20045}{}{}
{20046}{}{We got our offices in the sparkling Vegas, in the}
{20047}{}{city of contrasts - Reno, and in Salt Lake with its}
{20048}{}{inimitable atmosphere of decadence. Our caravans go}
{20049}{}{between them regularly and non-stop, like a clock.}
{20050}{}{And if you ask nicely, then we will stop specially}
{20051}{}{for you at the Wind of War, with its soldiers, or}
{20052}{}{near the settlement of the red-skinned Cheyenne.}
{20053}{}{}
{20054}{}{5. Exactly what I need! But do I have enough money?..}
{20055}{}{}
{20056}{}{You won't find more client-oriented approach in all}
{20057}{}{of Nevada Wasteland - 1000 bucks and ready to go!}
{20058}{}{In addition, we never forget the favors provided}
{20059}{}{to us, and willing to give a good discount}
{20060}{}{to our friends.}
{20061}{}{}
{20062}{}{6. The ball is in - when do we move out?}
{20063}{}{}
{20064}{}{We head out on the 1st, 11th and 21st day of each}
{20065}{}{month. Latecomers are not welcome, regardless of}
{20066}{}{the reasons; stayed in a brothel or in a church -}
{20067}{}{your problems.}
{20068}{}{**END-PAR**}
{20069}{}{**END-DISK**}


# Elron Bible
# GVAR_HOLODISK_ENCLAVE_ATOMIC
{21000}{}{--EMPTY--}
{21001}{}{}
{21002}{}{**END-PAR**}
{21003}{}{**END-DISK**}
