{100}{}{Burning metal barrel}
{101}{}{The barrel contains burning paper and other flaming refuse.}
{200}{}{Wooden door}
{201}{}{A door, made from wood.}
{300}{}{Wooden table}
{301}{}{A table, made from wood.}
{400}{}{Wooden table}
{401}{}{A table, made from wood.}
{500}{}{Metal barrel}
{501}{}{An old barrel, made from steel.}
{600}{}{Metal barrel}
{601}{}{An old barrel, made from steel.}
{700}{}{Stack of Tires}
{701}{}{A stack of ancient rubber tires. They have vulcanized and hardened, probably due to the heat.}
{800}{}{Security door}
{801}{}{This door looks very secure. It provides protection from the outside world elements and dangerous creatures.}
{900}{}{Computer}
{901}{}{A computer terminal, hooked into a mainframe computer.}
{1000}{}{Column}
{1001}{}{A support column, providing stress relief for the entire complex.}
{1100}{}{Computer}
{1101}{}{A computer terminal, hooked into a mainframe computer.}
{1200}{}{Computer}
{1201}{}{A computer terminal, hooked into a mainframe computer.}
{1300}{}{Monitor}
{1301}{}{A green-screen display monitor, showing various bits of data. A few bytes occasionally show up.}
{1400}{}{Monitor}
{1401}{}{A green-screen display monitor, showing various bits of data.}
{1500}{}{Auto-doc}
{1501}{}{This Auto-doc is designed to heal illnesses and administer various drugs.}
{1600}{}{Screens}
{1601}{}{A series of three display monitors, showing various bits of data.}
{1700}{}{Screens}
{1701}{}{A set of three display monitors, showing various bits of data from around the Vault.}
{1800}{}{Door}
{1801}{}{It's still a door after closer examination.}
{1900}{}{Door}
{1901}{}{It's still a door after closer examination.}
{2000}{}{Vent}
{2001}{}{An air vent, supplying processed and cleansed air to the entire complex.}
{2100}{}{Vent}
{2101}{}{An air vent, supplying processed and cleansed air to the entire complex.}
{2200}{}{Door}
{2201}{}{Large sturdy main entrance door.}
{2300}{}{The closet door}
{2400}{}{Pedestal}
{2401}{}{A hydraulic lift, designed to help provide support, power and communication lines to the platform.}
{2500}{}{Monitor}
{2501}{}{If you've seen one monitor, you've seen them all.}
{2600}{}{Monitor}
{2601}{}{A computer monitor, displaying various bits of data.}
{2700}{}{Grating}
{2701}{}{A floor grating.}
{2800}{}{Pipes}
{2801}{}{Some pipes. After closer examination it turns out that they are still pipes.}
{2900}{}{Vent}
{2901}{}{Standard Vault-Tec ventilation system.}
{3000}{}{Column}
{3001}{}{A standard Vault-Tec column support system.}
{3100}{}{Column}
{3101}{}{A standard Vault-Tec column support system.}
{3200}{}{Vent}
{3201}{}{Standard Vault-Tec ventilation system.}
{3300}{}{Vent}
{3301}{}{Standard Vault-Tec ventilation system.}
{3400}{}{Bed}
{3401}{}{A bed, it looks pretty comfortable after what you have been sleeping on.}
{3500}{}{Bed}
{3501}{}{A standard bed. Looks comfy.}
{3600}{}{Bed}
{3601}{}{A standard bed. Looks comfy.}
{3700}{}{Bed}
{3701}{}{A standard bed. Looks comfy.}
{3800}{}{Elevator}
{3801}{}{This is a maintenance elevator.}
{3900}{}{Chair}
{3901}{}{It's a chair. Too bad you don't have time to sit down and relax.}
{4000}{}{Chair}
{4001}{}{It's a chair. Too bad you don't have time to sit down and relax.}
{4100}{}{Chair}
{4101}{}{It's a chair. Too bad you don't have time to sit down and relax.}
{4200}{}{Chair}
{4201}{}{It's a chair. Too bad you don't have time to sit down and relax.}
{4300}{}{Monitor}
{4301}{}{A computer monitor, displaying various bits of data.}
{4400}{}{Monitor}
{4401}{}{A computer monitor, displaying various bits of data.}
{4500}{}{Monitor}
{4501}{}{A computer monitor, displaying various bits of data.}
{4600}{}{Monitor}
{4601}{}{A computer monitor, displaying various bits of data.}
{4700}{}{Monitor}
{4701}{}{A computer monitor, displaying various bits of data.}
{4800}{}{Monitor}
{4801}{}{A computer monitor, displaying various bits of data.}
{4900}{}{Exit Grid Map Marker}
{4901}{}{Exit Grid Map Marker}
{5000}{}{Air Processing Unit}
{5001}{}{An APU cleans the stale air to provide fresh one to the complex. This one is broken.}
{5100}{}{Chair}
{5101}{}{It's a chair. Too bad you don't have time to sit down and relax.}
{5200}{}{Chair}
{5201}{}{It's a chair. Too bad you don't have time to sit down and relax.}
{5300}{}{Chair}
{5301}{}{It's a chair. Too bad you don't have time to sit down and relax.}
{5400}{}{Chair}
{5401}{}{It's a chair. Too bad you don't have time to sit down and relax.}
{5500}{}{VDU}
{5501}{}{This Video Display Unit has a variety of computer monitors and other screens. It looks very, very busy.}
{5600}{}{VDU}
{5601}{}{This Video Display Unit has a variety of computer monitors and other screens. It looks very, very busy.}
{5700}{}{Chair}
{5701}{}{It's a chair. It looks mighty comfortable.}
{5800}{}{Chair}
{5801}{}{It's a chair. It looks mighty comfortable.}
{5900}{}{Chair}
{5901}{}{It's a chair. It looks mighty comfortable.}
{6000}{}{Chair}
{6001}{}{It's a chair. It looks mighty comfortable.}
{6100}{}{Table}
{6101}{}{It's a table. Before tables, people had to keep their stuff on the floor.}
{6200}{}{Table}
{6201}{}{It's definitely a table.}
{6300}{}{Tumbleweed}
{6301}{}{It's a tumbleweed. Of course, you've never seen a real live tumbleweed before. You'd better keep a close eye on it.}
{6400}{}{Cactus}
{6401}{}{You see nothing special about this cactus.}
{6500}{}{Ferocactus}
{6501}{}{You see nothing important about this cactus.}
{6600}{}{Tree}
{6601}{}{A dead tree. Nothing grows well here.}
{6700}{}{Secret Blocking Hex}
{6701}{}{If you can see this, blame the technical designer.}
{6800}{}{Fog}
{6900}{}{Stalagmite}
{6901}{}{A natural extension of the rock floor.}
{7000}{}{Stalagmite}
{7001}{}{A natural extension of the rock floor.}
{7100}{}{Blood stain}
{7101}{}{There is nothing out of the ordinary with this bloody stain. Except, of course, that someone or something died here.}
{7200}{}{Rock column}
{7201}{}{This thick column of rock extends from floor to ceiling.}
{7300}{}{Rock column}
{7301}{}{This thin column of rock extends from floor to ceiling.}
{7400}{}{Rocks}
{7401}{}{You study the rocks for a while, but they never move.}
{7500}{}{Rocks}
{7501}{}{You keep a close eye on these rocks, in case they move to attack you.}
{7600}{}{Boards}
{7601}{}{A stack of neatly folded boards.}
{7700}{}{Gate}
{7701}{}{A wooden gate.}
{7800}{}{Rocks}
{7801}{}{A large pile of rocks. They look indigenous to this region.}
{7900}{}{Rocks}
{7901}{}{A small pile of rocks.}
{8000}{}{Rocks}
{8001}{}{A small pile of rocks.}
{8100}{}{Rocks}
{8101}{}{A large pile of rocks.}
{8200}{}{Bones}
{8201}{}{A large pile of bleached animal bones. At least, you think all the bones are animal...}
{8300}{}{Bones}
{8301}{}{A large pile of bleached animal bones. At least, you think all the bones are animal...}
{8400}{}{Bones}
{8401}{}{A very large pile of bleached bones. You cannot determine the species of the dead critters.}
{8500}{}{Bones}
{8501}{}{You think these might be Horned Kangaroo bones, but you cannot be sure. They are too weathered to make a final determination.}
{8600}{}{Bones}
{8601}{}{You see the bones of a large, two-headed animal.}
{8700}{}{Gate}
{8701}{}{A wooden gate. It opens, and closes, and opens, and closes, and...}
{8800}{}{Gate}
{8801}{}{A wooden gate.}
{8900}{}{Gate}
{8901}{}{A wooden gate.}
{9000}{}{Rocks}
{9001}{}{A very large pile of rocks. They look dangerous just sitting there.}
{9100}{}{Rocks}
{9101}{}{A large pile of rocks. If you look closely, you can see the faces of little old men in the sides of the stones.}
{9200}{}{Rocks}
{9201}{}{Rocks, rocks, rocks! Everywhere you look, rocks!}
{9300}{}{Rocks}
{9301}{}{A small pile of rocks.}
{9400}{}{Bar}
{9401}{}{This bar has a collection of brewed beverages ready to pour.}
{9500}{}{Chair}
{9501}{}{A rotting old chair made out of an ancient car seat.}
{9600}{}{Chair}
{9601}{}{A smelly old chair that used be to a car seat. The springs have lost their spring.}
{9700}{}{Chair}
{9701}{}{A rotting, smelly old chair sitting on bricks for support. Looks pretty uncomfortable.}
{9800}{}{Chair}
{9801}{}{A rotting, smelly old chair sitting on bricks for support. Looks pretty uncomfortable.}
{9900}{}{Couch}
{9901}{}{A very uncomfortable looking sitting device, sometimes known as a couch.}
{10000}{}{Couch}
{10001}{}{A very uncomfortable looking sitting device, sometimes known as a couch.}
{10100}{}{Tire}
{10101}{}{An old rubber tire sitting in the middle of some weeds.}
{10200}{}{Scrub}
{10201}{}{Some sort of desert weed.}
{10300}{}{Scrub}
{10301}{}{Some sort of desert weed.}
{10400}{}{Scrub}
{10401}{}{Some sort of desert weed.}
{10500}{}{Scrub}
{10501}{}{Some sort of desert weed.}
{10600}{}{Junk}
{10601}{}{It's a rusted car door leaning on a rusted metal barrel. A whole lot of rust is going on.}
{10700}{}{Junk}
{10701}{}{A broken toilet, half-buried in the sand. Life's a pisser, then you die.}
{10800}{}{Weeds}
{10801}{}{Some sort of desert scrub. If it was growing in the recent past, it isn't now.}
{10900}{}{Junk}
{10901}{}{A car tire, buried in the sand. Some small pieces of wood are piled up around it.}
{11000}{}{Junk}
{11001}{}{On closer examination, you think these might actually be pieces of petrified wood.}
{11100}{}{Dirt}
{11101}{}{A small pile of dirt, with a dead weed sticking out of it.}
{11200}{}{Dirt}
{11201}{}{A small pile of dirt.}
{11300}{}{Dirt}
{11301}{}{A small pile of dirt.}
{11400}{}{Dirt}
{11401}{}{A small pile of dirt.}
{11500}{}{Weed}
{11501}{}{A small pile of dirt, with a dry weed sticking out of it.}
{11600}{}{Junk}
{11601}{}{A twisted piece of rusted metal.}
{11700}{}{Junk}
{11701}{}{Some broken pieces of wood.}
{11800}{}{Junk}
{11801}{}{A small pile of random junk.}
{11900}{}{Dirt}
{11901}{}{A small pile of dirt.}
{12000}{}{Dirt}
{12001}{}{A small pile of dirt.}
{12100}{}{Dirt}
{12101}{}{A small pile of dirt.}
{12200}{}{Dirt}
{12201}{}{A small pile of dirt.}
{12300}{}{Dirt}
{12301}{}{A small pile of dirt.}
{12400}{}{Dirt}
{12401}{}{A small pile of dirt.}
{12500}{}{Weed}
{12501}{}{A generic desert weed.}
{12600}{}{Weed}
{12601}{}{A generic desert weed.}
{12700}{}{Weed}
{12701}{}{A generic desert weed.}
{12800}{}{Blocking Hex (No light)}
{12900}{}{Tanker}
{13000}{}{Tanker}
{13100}{}{Tanker}
{13200}{}{Tanker}
{13300}{}{Tanker}
{13400}{}{Tanker}
{13500}{}{Tanker}
{13600}{}{Tanker}
{13700}{}{Tanker}
{13800}{}{Tanker}
{13900}{}{Tanker}
{13901}{}{It's an old, fairly rickety ladder.}
{14000}{}{Sewer Hole}
{14001}{}{It looks like an access hole for the underground facilities.}
{14100}{}{Light Source}
{14200}{}{Door}
{14201}{}{This looks like a standard Vault door that has been damaged, perhaps burned. It is still functional, however.}
{14300}{}{Door}
{14301}{}{This looks like a standard Vault door that has been damaged, perhaps burned. It is still functional, however.}
{14400}{}{Cover}
{14401}{}{A heavy man-hole cover. It looks like it is in good shape, and that it was recently moved.}
{14500}{}{Hole}
{14501}{}{A large hole has been blasted through this door.}
{14600}{}{Hole}
{14601}{}{A large hole has been blasted through this door.}
{14700}{}{Bulletproof Glass}
{14701}{}{Completely unbreakable glass. Don't even try.}
{14800}{}{Bulletproof Glass}
{14801}{}{Completely unbreakable glass. Don't even try.}
{14900}{}{Bulletproof Glass}
{14901}{}{Completely unbreakable glass. Don't even try.}
{15000}{}{Bulletproof Glass}
{15001}{}{Completely unbreakable glass. Don't even try.}
{15100}{}{Target}
{15101}{}{This target is carefully painted on the wall.}
{15200}{}{The tail of the plane}
{15300}{}{The tail of the plane}
{15400}{}{Aircraft door}
{15500}{}{Elevator}
{15501}{}{This is the interior of a Vault-Tec elevator. It is squeaky clean!}
{15600}{}{Elevator}
{15601}{}{This is the interior of a Vault-Tec elevator. It is squeaky clean!}
{15700}{}{Dry grass}
{15701}{}{Just dry grass.}
{15800}{}{Monitor}
{15801}{}{You see a computer monitor.}
{15900}{}{Monitor}
{15901}{}{You see a computer monitor.}
{16000}{}{Computer}
{16001}{}{This is a computer memory databank.}
{16100}{}{Computer}
{16101}{}{This is a computer memory databank.}
{16200}{}{Computer}
{16201}{}{A high-tech computer, using modern reel-to-reel storage devices instead of the antiquated punch cards.}
{16300}{}{Computer}
{16301}{}{A high-tech computer, using modern reel-to-reel storage devices instead of the antiquated punch cards.}
{16400}{}{Monitor}
{16401}{}{You see a computer monitor.}
{16500}{}{Monitor}
{16501}{}{You see a computer monitor.}
{16600}{}{Wire}
{16601}{}{Some thick cable.}
{16700}{}{Wire}
{16701}{}{Some thick cable.}
{16800}{}{Wire}
{16801}{}{Some thick cable.}
{16900}{}{Column}
{16901}{}{A support column.}
{17000}{}{Column}
{17001}{}{A support column.}
{17100}{}{Door Entry Computer}
{17101}{}{This computer controls the large vault door. You have to enter a specific access code for the computer to work.}
{17200}{}{Fire}
{17300}{}{Vault 8 Outer door}
{17301}{}{This large door is the link between the vault and the outside world.}
{17400}{}{Vault 8 Outer door}
{17401}{}{This large door is the link between the vault and the outside world.}
{17500}{}{Base}
{17501}{}{Automated basis for the post of overseer.}
{17600}{}{Down Arrow}
{17700}{}{Up Arrow}
{17800}{}{Crate}
{17900}{}{Crate}
{18000}{}{Crate}
{18100}{}{Switch}
{18101}{}{Switch for water pump.}
{18200}{}{Hydraulic pump}
{18201}{}{This is the pump for the pumping of groundwater. A rather rare machinery.}
{18300}{}{Beam}
{18400}{}{Barrier concrete}
{18500}{}{Barrier concrete}
{18600}{}{Valve}
{18700}{}{Switch}
{18800}{}{Barrier concrete}
{18900}{}{Barrier concrete}
{19000}{}{Bunk Bed}
{19001}{}{A military-style bunk bed. Looks very uncomfortable. Also looks like you could bounce a quarter off of these sheets.}
{19100}{}{Bunk Bed}
{19101}{}{A military-style bunk bed. Looks very uncomfortable. Also looks like you could bounce a quarter off of these sheets.}
{19200}{}{Bunk Bed}
{19201}{}{A military-style bunk bed. Looks very uncomfortable. Also looks like you could bounce a quarter off of these sheets.}
{19300}{}{Crate}
{19400}{}{Nuka-Cola Machine}
{19401}{}{The advertising on the side of this machine promotes their popular soda.}
{19500}{}{Wall}
{19600}{}{Trapdoor}
{19601}{}{It looks like a perfectly good trapdoor.}
{19700}{}{Manhole}
{19701}{}{The ladder in this manhole leads down into the darkness below. Ohhh, scary.}
{19800}{}{Vault door}
{19801}{}{It is an external door of your vault. It's closed and can be opened only from within.}
{19900}{}{Robocop}
{19901}{}{Various spare parts needed to build a police robot.}
{20000}{}{Pew}
{20001}{}{This looks just like you would expect it to. Nothing special about this pew.}
{20100}{}{Signpost}
{20101}{}{The sign on this post looks a little rusty.}
{20200}{}{Signpost}
{20201}{}{The sign on this post looks a little rusty.}
{20300}{}{Signpost}
{20301}{}{The sign on this post looks a little rusty.}
{20400}{}{Signpost}
{20401}{}{The sign on this post looks a little rusty.}
{20500}{}{Signpost}
{20501}{}{The sign on this post looks a little rusty.}
{20600}{}{Old Mattress}
{20601}{}{An old, beat-up mattress. You think you see some sort of small bug-like critter infesting it.}
{20700}{}{Old Mattress}
{20701}{}{Even if you were to sleep by yourself on this thing, you would not be sleeping alone.}
{20800}{}{Bed}
{20801}{}{A make-shift bed. The material was scavenged from some other source.}
{20900}{}{Bed}
{20901}{}{A make-shift bed. The material was scavenged from some other source.}
{21000}{}{Bed}
{21001}{}{This bed has seen better days (and probably nights, too.)}
{21100}{}{Bed}
{21101}{}{On closer examination, you determine that the sheets have not been changed in a very, very long time.}
{21200}{}{Bed}
{21201}{}{There are a couple stains of dubious origin on this well-worn sleeping device.}
{21300}{}{Bed}
{21301}{}{This bed has seen a lot of use and wear. Looks like something crawled under the mattress and died there.}
{21400}{}{Dirt}
{21500}{}{Dirt}
{21600}{}{Dirt}
{21700}{}{Dirt}
{21800}{}{Dirt}
{21900}{}{Dirt}
{22000}{}{Boxes}
{22001}{}{These wooden boxes are falling apart from the weather.}
{22100}{}{Boxes}
{22101}{}{You find no details worth mentioning about these wooden boxes.}
{22200}{}{Boxes}
{22201}{}{You have a lot of time on your hands to be looking closely at this rotten junk.}
{22300}{}{Boxes}
{22301}{}{These wooden boxes are falling apart from the weather.}
{22400}{}{Car}
{22401}{}{This automobile is in terrible shape. You cannot think of a way to restore it.}
{22500}{}{Car}
{22501}{}{This rusted piece of scrap-metal cannot be restored.}
{22600}{}{Car}
{22601}{}{You determine that this vehicle will never drive again. Really.}
{22700}{}{Car}
{22701}{}{There is no way that this junkyard wannabe will ever drive again.}
{22800}{}{Car}
{22801}{}{If the Mechanic of the Year suddenly appeared next to you, both of you could not fix this rusty heap.}
{22900}{}{Chair}
{22901}{}{A comfy chair.}
{23000}{}{Chair}
{23001}{}{This chair looks like it has seen better years.}
{23100}{}{Chair}
{23101}{}{This chair is moldy and gross. As you can guess, it stinks, too.}
{23200}{}{Chair}
{23201}{}{This chair is falling apart. Quickly.}
{23300}{}{Chair}
{23301}{}{If someone paid you a lot of money, and if you also had butt made of steel, you could consider the possibility of sitting in this chair.}
{23400}{}{Chair}
{23401}{}{This looks like an old office chair, still in pretty good shape after all these years.}
{23500}{}{Chair}
{23501}{}{This is an old office chair. It might even support the weight of a person.}
{23600}{}{Chair}
{23601}{}{This office chair has seen better days. It's pretty much junk now.}
{23700}{}{Chair}
{23701}{}{This looks like a chair you would see in a mortician's office - dead.}
{23800}{}{Rocks}
{23900}{}{Rocks}
{24000}{}{Ladder}
{24100}{}{Ladder}
{24200}{}{Beam}
{24300}{}{Fire Hydrant}
{24301}{}{This is a fire hydrant. Without Vault ceiling sprinklers, you might need one of these to put out fires.}
{24400}{}{Lamp post}
{24401}{}{This lamp post looks like it is still in working condition. Imagine that, something that works out here.}
{24500}{}{Lamp post}
{24501}{}{This lamp post will never work again.}
{24600}{}{Lamp post}
{24601}{}{This is a working lamp post. At night, it casts a pale, gentle light that reminds you of absolutely nothing.}
{24700}{}{Lamp post}
{24701}{}{This is a broken lamp post. It cannot be fixed.}
{24800}{}{Lamp post}
{24801}{}{This light fixture is operational.}
{24900}{}{Lamp post}
{24901}{}{The light in this lamp post is shattered beyond repair.}
{25000}{}{Lamp post}
{25001}{}{This is a functional lamp post.}
{25100}{}{Smashed door.}
{25101}{}{This door was smashed by explosion, it cannot be opened in an usual way.}
{25200}{}{Junk}
{25201}{}{Definitely useless junk, no doubt about it.}
{25300}{}{Junk}
{25301}{}{Definitely useless junk, no doubt about it.}
{25400}{}{Junk}
{25401}{}{Definitely useless junk, no doubt about it.}
{25500}{}{Junk}
{25501}{}{Definitely useless junk, no doubt about it.}
{25600}{}{Junk}
{25601}{}{Definitely useless junk, no doubt about it.}
{25700}{}{Mailbox}
{25701}{}{The mailbox is empty. You get the feeling it's been that way for a while.}
{25800}{}{Door}
{25801}{}{A nicely crafted wooden door, in good condition.}
{25900}{}{Door}
{25901}{}{A nicely crafted wooden door, in good condition.}
{26000}{}{Door}
{26001}{}{A nicely crafted wooden door, in good condition.}
{26100}{}{Door}
{26101}{}{A nicely crafted wooden door, in good condition.}
{26200}{}{Pew}
{26201}{}{This wooden pew is slowly falling apart.}
{26300}{}{Pew}
{26301}{}{This pew has been neglected, and is showing signs of wear and tear.}
{26400}{}{Pew}
{26401}{}{A wooden pew that has succumbed to the effects of age and abuse.}
{26500}{}{Newspaper Machine}
{26501}{}{The newspaper machine is most likely empty.}
{26600}{}{Newspaper Machine}
{26601}{}{The newspaper machine is most likely empty.}
{26700}{}{Newspaper Machine}
{26701}{}{The newspaper machine is most likely empty.}
{26800}{}{Newspaper Machine}
{26801}{}{The newspaper machine is most likely empty.}
{26900}{}{Newspaper Machine}
{26901}{}{The newspaper machine is most likely empty.}
{27000}{}{Newspaper Machine}
{27001}{}{The newspaper machine is most likely empty. It looks like it once held adult magazines.}
{27100}{}{Junk}
{27101}{}{A bed mattress in terrible condition. Even the rats won't sleep in or on it.}
{27200}{}{Junk}
{27201}{}{A twin bed mattress that has seen many better days than this one.}
{27300}{}{Junk}
{27301}{}{A pile of rotted and weathered wood. Not worth its weight in, well, anything.}
{27400}{}{Junk}
{27401}{}{A pile of wood with some old rusty nails embedded deeply, absolutely useless.}
{27500}{}{Boxes}
{27501}{}{A pile of old, cardboard boxes. You cannot believe that they have survived for this long.}
{27600}{}{Boxes}
{27601}{}{A pile of old, cardboard boxes.}
{27700}{}{Junk}
{27701}{}{Some junk that you think might have been a bed mattress before it was destroyed by the environment.}
{27800}{}{Rocks}
{27900}{}{Rocks}
{28000}{}{Rocks}
{28100}{}{The elevator shaft}
{28200}{}{Sink}
{28201}{}{A porcelain sink that has long lost the ability to function.}
{28300}{}{Sink}
{28301}{}{A broken porcelain sink. There is small puddle of brown water in the basin, with a floating dead rat.}
{28400}{}{Sink}
{28401}{}{This sink is not functional. You can tell this from the large crack down the middle.}
{28500}{}{Sink}
{28501}{}{A broken porcelain sink. There is small puddle of brown water in the basin, with a floating dead rat.}
{28600}{}{Stop sign}
{28601}{}{A red sign with the word STOP written in large block letters.}
{28700}{}{Stop sign}
{28701}{}{A red sign with the word STOP written in large block letters. The bullet hole was added after manufacturing.}
{28800}{}{Stop light}
{28801}{}{This is an ancient automobile traffic control device.}
{28900}{}{Stop light}
{28901}{}{This is an ancient automobile traffic control device.}
{29000}{}{Stop light}
{29001}{}{This is an ancient automobile traffic control device.}
{29100}{}{Street light}
{29101}{}{This street light provides illumination after night falls, or in darkened areas.}
{29200}{}{Street light}
{29201}{}{This street light provides illumination after night falls, or in darkened areas.}
{29300}{}{Street light}
{29301}{}{This street light provides illumination after night falls, or in darkened areas.}
{29400}{}{Street light}
{29401}{}{This street light provides illumination after night falls, or in darkened areas.}
{29500}{}{Street light}
{29501}{}{This street light could provide illumination in darkened areas, if it wasn't completely broken.}
{29600}{}{Street light}
{29601}{}{This street light could provide illumination in darkened areas, if it wasn't completely broken.}
{29700}{}{Street light}
{29701}{}{This street light could provide illumination in darkened areas, if it wasn't completely broken.}
{29800}{}{Signpost}
{29801}{}{This sign should mark what street it is on, but the letters have faded into obscurity.}
{29900}{}{Signpost}
{29901}{}{This sign should mark what street it is on, but the letters have faded into obscurity.}
{30000}{}{Table}
{30001}{}{A wooden table, in fair to middling condition.}
{30100}{}{Table}
{30101}{}{A wooden table, in fair to middling condition.}
{30200}{}{Table}
{30201}{}{A wooden table, in middling to poor condition.}
{30300}{}{Table}
{30301}{}{A wooden table, with plastic surface, that has been broken for a while.}
{30400}{}{Table}
{30401}{}{A wooden table, painted a puke green color, that is beyond repair.}
{30500}{}{Table}
{30501}{}{This looks like an old coffee table, low to the ground for those really short mutants.}
{30600}{}{Table}
{30601}{}{This looks like an old coffee table, low to the ground for those really short mutants.}
{30700}{}{Toilet}
{30701}{}{The sharpened edges around the seat make this a very uncomfortable place to sit.}
{30800}{}{Toilet}
{30801}{}{This toilet is broken.}
{30900}{}{Toilet}
{30901}{}{Yuck! Whoever used this last did not flush!}
{31000}{}{Toilet}
{31001}{}{This toilet is broken and definitely not useable if you're a woman.}
{31100}{}{Trash}
{31101}{}{Some busted pipes half-buried in the dirt. Nothing important to see here. Move along.}
{31200}{}{Trash}
{31201}{}{Some broken pieces of glass and other ruined pieces of junk.}
{31300}{}{Trash}
{31301}{}{Some broken pieces of glass and other ruined pieces of junk.}
{31400}{}{Trash}
{31401}{}{A pipe that has been snapped in half. It looks like it rusted until it collapsed under it's own weight.}
{31500}{}{Trash Can}
{31501}{}{A trash can. You can barely read the label: Keep your city streets clean!}
{31600}{}{Tree}
{31601}{}{It's a dead tree.}
{31700}{}{Tree}
{31701}{}{A stump. Nothing really exciting. In fact, this might be the least exciting thing you have ever laid your eyes on.}
{31800}{}{Tree}
{31801}{}{It's a dead tree.}
{31900}{}{Tree}
{32000}{}{Tree}
{32100}{}{Tree}
{32200}{}{Blockage}
{32300}{}{Truck}
{32301}{}{The ruined remains of a diesel truck. This hunk of metal will never move again.}
{32400}{}{Truck}
{32401}{}{This diesel truck is beyond help. Way beyond help.}
{32500}{}{Bath tub}
{32501}{}{This bath tub is broken and cracked.}
{32600}{}{Bath tub}
{32601}{}{On closer examination, you realize that you won't be taking your bath in this tub after all.}
{32700}{}{Urinal}
{32701}{}{It's just a urinal.}
{32800}{}{Urinal}
{32801}{}{It's just a urinal.}
{32900}{}{Urinal}
{32901}{}{It's just a urinal. Nothing special.}
{33000}{}{Urinal}
{33001}{}{It's just a urinal. Nothing special.}
{33100}{}{Water tank}
{33101}{}{A large tank that holds liquids. In this case, you believe that it was designed to store water.}
{33200}{}{Door}
{33201}{}{A wooden door. Nothing extremely interesting about it.}
{33300}{}{Door}
{33301}{}{A wooden door. It provides an entrance and egress from this building.}
{33400}{}{Wall lamp}
{33401}{}{This lamp looks it is in good working condition.}
{33500}{}{Wall lamp}
{33501}{}{A broken lamp. It is not surprising that it does not work.}
{33600}{}{Wall lamp}
{33601}{}{This lamp looks it is in good working condition.}
{33700}{}{Wall lamp}
{33701}{}{A broken lamp. It is not surprising that it does not work.}
{33800}{}{Wall lamp}
{33801}{}{This lamp looks it is in good working condition.}
{33900}{}{Wall lamp}
{33901}{}{A broken lamp. It is not surprising that it does not work.}
{34000}{}{Wall lamp}
{34001}{}{This lamp looks it is in good working condition.}
{34100}{}{Wall lamp}
{34101}{}{A broken lamp. It is not surprising that it does not work.}
{34200}{}{Yield Sign}
{34201}{}{This was a sign to control the flow of traffic.}
{34300}{}{Yield sign}
{34301}{}{The sign is faded, but you can make out the world YIELD.}
{34400}{}{Block Hex Auto Inviso}
{34401}{}{If you can see this, blame the technical designer.}
{34500}{}{Manhole}
{34600}{}{Door}
{34601}{}{An ornate wooden door. It is obviously made from fine workmanship.}
{34700}{}{Pew}
{34701}{}{This seat is supported by large concrete bricks. That's not important, but you're the one who looked.}
{34800}{}{Staircase}
{34801}{}{This staircase leads up.}
{34900}{}{Dirt}
{35000}{}{Dirt}
{35100}{}{Bridge support}
{35200}{}{Sign}
{35201}{}{Withered road sign. Numbers can still be seen on it "14:6".}
{35300}{}{Truck}
{35301}{}{The remains of a long-range truck.}
{35400}{}{Pointer}
{35401}{}{Tilted road sign.}
{35500}{}{Dirt}
{35600}{}{Staircase}
{35601}{}{This staircase leads down.}
{35700}{}{Bike}
{35701}{}{This motorcycle has a fingerprint security, so it can only be used by the owner.}
{35800}{}{Bike}
{35801}{}{This motorcycle has a fingerprint security, so it can only be used by the owner.}
{35900}{}{Bike}
{35901}{}{This motorcycle has a fingerprint security, so it can only be used by the owner.}
{36000}{}{Bike}
{36001}{}{This motorcycle has a fingerprint security, so it can only be used by the owner.}
{36100}{}{Curtain}
{36101}{}{This curtain looks like it was created by primitive means, but it is very functional.}
{36200}{}{Curtain}
{36201}{}{This curtain looks like it was created by primitive means, but it is very functional.}
{36300}{}{Bowl}
{36301}{}{A finely crafted wooden bowl. This looks like it was designed to crush and separate grains.}
{36400}{}{Bowl}
{36401}{}{A finely crafted wooden bowl.}
{36500}{}{Pot}
{36501}{}{A finely crafted pot.}
{36600}{}{Plant}
{36601}{}{It looks like a mutated cabbage to you. It seems to be thriving in the warm weather.}
{36700}{}{Plant}
{36701}{}{It looks like a mutated cabbage to you. It seems to be thriving in the warm weather.}
{36800}{}{Cart}
{36801}{}{A crude, but effective, agricultural cart.}
{36900}{}{Corn}
{37000}{}{Corn}
{37100}{}{Corn}
{37200}{}{Pot}
{37201}{}{A finely crafted clay pot.}
{37300}{}{Rake}
{37301}{}{This rake is the property of its owners. You can't even conceive of a use for it.}
{37400}{}{Rake}
{37401}{}{This rake is the property of its owners. You can't even conceive of a use for it.}
{37500}{}{Rake}
{37501}{}{This rake is the property of its owners. You can't even conceive of a use for it.}
{37600}{}{Rug}
{37601}{}{A simple rug. The weaver was obviously very talented.}
{37700}{}{Rug}
{37701}{}{A simple rug. The weaver was obviously very talented.}
{37800}{}{Rug}
{37801}{}{A simple rug. The weaver was obviously very talented.}
{37900}{}{Plant}
{37901}{}{Decorative room plant.}
{38000}{}{Plant}
{38001}{}{Decorative room plant.}
{38100}{}{Bike}
{38101}{}{This motorcycle has a fingerprint security, so it can only be used by the owner.}
{38200}{}{Vase}
{38201}{}{A very pretty clay vase.}
{38300}{}{Well}
{38301}{}{A typical well found in the wasteland.}
{38400}{}{Pole}
{38401}{}{This pole helps to support the yurt.}
{38500}{}{Pole}
{38501}{}{This pole helps to support the yurt.}
{38600}{}{Pole}
{38601}{}{This pole helps to support the yurt.}
{38700}{}{Pole}
{38701}{}{This pole helps to support the yurt.}
{38800}{}{Pole}
{38801}{}{This pole helps to support the yurt.}
{38900}{}{Pole}
{38901}{}{This pole helps to support the yurt.}
{39000}{}{Vault door}
{39001}{}{This vault door is now just a heavy piece of scrap-metal.}
{39100}{}{Vault 15 door}
{39101}{}{Identical big door to the vault, like the one located in your city, just rustier.}
{39200}{}{Brace}
{39201}{}{This brace helps to support the defensive wall.}
{39300}{}{Brace}
{39301}{}{This brace helps to support the defensive wall.}
{39400}{}{Brace}
{39401}{}{This brace helps to support the defensive wall.}
{39500}{}{Brace}
{39501}{}{This brace helps to support the defensive wall.}
{39600}{}{Metal barrels}
{39601}{}{A rusty metal barrel. It is empty.}
{39700}{}{Metal barrels}
{39701}{}{This barrel is probably empty, judging by the hollow sound.}
{39800}{}{Metal barrels}
{39801}{}{These barrels are probably empty from their hollow sound.}
{39900}{}{Metal barrels}
{39901}{}{These barrels are probably empty from their hollow sound.}
{40000}{}{Air vent}
{40001}{}{This air vent appears to be for an underground structure.}
{40100}{}{Crate}
{40101}{}{A wooden crate. It doesn't look in that bad of shape.}
{40200}{}{Crate}
{40201}{}{A simple wooden crate. In fairly good condition.}
{40300}{}{Crate}
{40301}{}{This simple wooden crate has collapsed under its own weight.}
{40400}{}{Desk}
{40401}{}{A simple desk with a computer.}
{40500}{}{Desk}
{40501}{}{A simple desk with a computer.}
{40600}{}{Door}
{40601}{}{A wooden door, in fair shape.}
{40700}{}{Cave In}
{40701}{}{A large amount of rock, far more than could ever be moved easily.}
{40800}{}{Car}
{40801}{}{This submerged car cannot be repaired.}
{40900}{}{Car}
{40901}{}{This car is a little wet, and cannot be repaired.}
{41000}{}{Car}
{41001}{}{This car has been poorly parked. Unfortunately, it is beyond repair.}
{41100}{}{Junk}
{41101}{}{This junk has been ruined by the contaminated seawater.}
{41200}{}{Junk}
{41201}{}{This junk has almost washed away.}
{41300}{}{Junk}
{41301}{}{A choice selection of useless junk.}
{41400}{}{Pipes}
{41401}{}{These thick pipes used for pumping fluids in large volumes.}
{41500}{}{Pipe}
{41501}{}{These thick pipes used for pumping fluids in large volumes.}
{41600}{}{Pipes}
{41601}{}{These thick pipes used for pumping fluids in large volumes.}
{41700}{}{Elevator shaft}
{41701}{}{Part of an elevator system.}
{41800}{}{Elevator shaft}
{41801}{}{An elevator shaft that stretches deep into the ground. It has been damaged.}
{41900}{}{Elevator}
{41901}{}{An elevator. Use it to go up and down between levels.}
{42000}{}{Elevator shaft}
{42001}{}{An elevator shaft that stretches deep into the ground. It has been damaged.}
{42100}{}{Electronic door}
{42101}{}{This door has electronic lock and it's powered.}
{42200}{}{Pipe}
{42201}{}{A metal pipe. Further details are not important.}
{42300}{}{Dirt}
{42400}{}{Box}
{42500}{}{Box}
{42600}{}{Box}
{42700}{}{Box}
{42800}{}{Rocks}
{42801}{}{A pile of rocks. Not very interesting.}
{42900}{}{Rocks}
{42901}{}{A pile of rocks. Not very interesting.}
{43000}{}{Rocks}
{43001}{}{A small pile of rocks. Not in the least bit interesting to you.}
{43100}{}{Rocks}
{43101}{}{A very small pile of rocks.}
{43200}{}{Rocks}
{43201}{}{A very small pile of rocks.}
{43300}{}{Rocks}
{43301}{}{A very small pile of rocks.}
{43400}{}{Rocks}
{43401}{}{A very small pile of rocks.}
{43500}{}{Rocks}
{43501}{}{A small pile of rocks.}
{43600}{}{Vault door}
{43601}{}{This vault door is very similar to the one at Vault 8. The door mechanism has been disabled.}
{43700}{}{Door}
{43701}{}{A finely constructed wooden door, reinforced with ornate metal braces of an almost hypnotic design.}
{43800}{}{Door}
{43801}{}{A finely constructed wooden door, reinforced with ornate metal braces of an almost hypnotic design.}
{43900}{}{Shadow}
{44000}{}{Shadow}
{44100}{}{Shadow}
{44200}{}{Shadow}
{44300}{}{Shadow}
{44400}{}{Shadow}
{44500}{}{Pile of metal}
{44600}{}{Junk}
{44601}{}{Pile of garbage, covered in sand and grass. But there is something special about it.}
{44700}{}{Electric panel}
{44800}{}{Grid}
{44801}{}{Dirty sewer gate.}
{44900}{}{Street light}
{45000}{}{Well}
{45001}{}{A typical well found in the wasteland.}
{45100}{}{Craps Table}
{45200}{}{Craps Table}
{45300}{}{Craps Table}
{45400}{}{Craps Table}
{45500}{}{Craps Table}
{45600}{}{Craps Table}
{45700}{}{Craps Table}
{45800}{}{Craps Table}
{45900}{}{Craps Table}
{46000}{}{Craps Table}
{46100}{}{Rock}
{46101}{}{A small rock, completely uninteresting in the context of this story.}
{46200}{}{Rock}
{46300}{}{Rock}
{46400}{}{Rock}
{46500}{}{Slot machine}
{46501}{}{This is a gambling machine.}
{46600}{}{Slot machine}
{46601}{}{This is a gambling machine.}
{46700}{}{Doorway}
{46800}{}{Elevator}
{46900}{}{Elevator}
{47000}{}{Elevator door}
{47100}{}{Window}
{47101}{}{Instead of glass, this window is using wax paper.}
{47200}{}{Window}
{47201}{}{Instead of glass, this window is using wax paper.}
{47300}{}{Window}
{47301}{}{Instead of glass, this window is using wax paper.}
{47400}{}{Window}
{47401}{}{Instead of glass, this window is using wax paper.}
{47500}{}{Door}
{47501}{}{This large metal roll-door has been jammed shut from the inside.}
{47600}{}{Door}
{47601}{}{This large metal roll-door has been jammed shut from the inside.}
{47700}{}{Door}
{47701}{}{This large metal roll-door has been jammed shut from the inside. It reads LOADING ONLY.}
{47800}{}{Door}
{47801}{}{This large metal roll-door has been jammed shut from the inside.}
{47900}{}{Door}
{47901}{}{This large metal roll-door has been jammed shut from the inside.}
{48000}{}{Door}
{48001}{}{This large metal roll-door has been jammed shut from the inside. It reads LOADING ONLY.}
{48100}{}{Door}
{48101}{}{This door suspiciously looks like the one that is installed in the warehouse.}
{48200}{}{Door}
{48201}{}{This door suspiciously looks like the one that is installed in the warehouse.}
{48300}{}{Monitor}
{48301}{}{The device for autonomous monitoring of the environment. Equipped with a 120-pound metal structure for durability.}
{48400}{}{Cable}
{48500}{}{Podium}
{48501}{}{This is a normal podium for public speaking.}
{48600}{}{Altar}
{48700}{}{Monitor}
{48701}{}{A large black and white monitor. Almost like in a movie theater!}
{48800}{}{Cable}
{48900}{}{Forcefield}
{48901}{}{This is a powerful field of energy.}
{49000}{}{Forcefield}
{49001}{}{This is a powerful field of energy.}
{49100}{}{Forcefield}
{49101}{}{This is a powerful field of energy.}
{49200}{}{Forcefield}
{49201}{}{This is a powerful field of energy.}
{49300}{}{Table}
{49301}{}{A fairly ordinary wooden table.}
{49400}{}{Table}
{49401}{}{A fairly ordinary wooden table.}
{49500}{}{Table}
{49501}{}{A fairly ordinary wooden table.}
{49600}{}{Table}
{49601}{}{A fairly ordinary wooden table.}
{49700}{}{Table}
{49701}{}{A fairly ordinary wooden table.}
{49800}{}{Table}
{49801}{}{A fairly ordinary wooden table.}
{49900}{}{Shadow}
{50000}{}{Shadow}
{50100}{}{Shadow}
{50200}{}{Shadow}
{50300}{}{Shadow}
{50400}{}{Shadow}
{50500}{}{Altar}
{50501}{}{A simple altar made from painted wood.}
{50600}{}{Cable}
{50601}{}{Thick high voltage cable.}
{50700}{}{Cable}
{50701}{}{Thick high voltage cable.}
{50800}{}{Altar}
{50801}{}{A simple altar made from painted wood.}
{50900}{}{Ventilation}
{50901}{}{Rusty vent with a broken-down bars. It is possible to get to the other side through it.}
{51000}{}{Shadow}
{51100}{}{Shadow}
{51200}{}{Shadow}
{51300}{}{Shadow}
{51400}{}{Shadow}
{51500}{}{Shadow}
{51600}{}{Traces}
{51601}{}{You see traces of the robot's caterpillar tracks.}
{51700}{}{Traces}
{51701}{}{You see traces of the robot's caterpillar tracks.}
{51800}{}{Traces}
{51801}{}{You see traces of the robot's caterpillar tracks.}
{51900}{}{Traces}
{51901}{}{You see traces of the robot's caterpillar tracks.}
{52000}{}{Cylinders}
{52001}{}{Emergency oxygen reserve cylinders. The word "EXPLOSIVE!" is written on each of them with large letters.}
{52100}{}{Rope}
{52101}{}{The rope is attached to the ground and dropped in the foul smelling hole.}
{52200}{}{Rails}
{52201}{}{Just rails.}
{52300}{}{Opening}
{52301}{}{Very deep opening. Strong smell of excrement.}
{52400}{}{Excrement}
{52401}{}{Excrement, that are tossed to every side.}
{52500}{}{Pew}
{52501}{}{A nicely fashioned, and mighty uncomfortable looking, pew.}
{52600}{}{Shadow}
{52700}{}{Wagon}
{52701}{}{A caravan wagon converted from the wrecked remains of an ancient automobile.}
{52800}{}{Wagon}
{52801}{}{A caravan wagon converted from the wrecked remains of an ancient automobile.}
{52900}{}{Wagon}
{52901}{}{A caravan wagon converted from the wrecked remains of an ancient automobile.}
{53000}{}{Wagon}
{53001}{}{A caravan wagon converted from the wrecked remains of an ancient automobile.}
{53100}{}{Wagon}
{53101}{}{A caravan wagon converted from the wrecked remains of an ancient automobile.}
{53200}{}{Wagon}
{53201}{}{A caravan wagon converted from the wrecked remains of an ancient automobile.}
{53300}{}{Mat}
{53301}{}{A training mat.}
{53400}{}{Mat}
{53401}{}{A training mat.}
{53500}{}{Mat}
{53501}{}{A training mat.}
{53600}{}{Mat}
{53601}{}{A training mat.}
{53700}{}{Punching bag}
{53701}{}{This is a Strongman(tm) Punching bag.}
{53800}{}{Stair stepper}
{53801}{}{An exercise machine.}
{53900}{}{Stair stepper}
{54000}{}{Treadmill}
{54001}{}{An exercise machine.}
{54100}{}{Treadmill}
{54101}{}{An exercise machine.}
{54200}{}{Bench press}
{54201}{}{An exercise machine.}
{54300}{}{Bench press}
{54301}{}{An exercise machine.}
{54400}{}{Wood planks}
{54401}{}{These sturdy wooden planks have been firmly bound together.}
{54500}{}{Wood planks}
{54501}{}{These sturdy wooden planks have been firmly bound together.}
{54600}{}{Roulette table}
{54601}{}{This is a gambling table.}
{54700}{}{Roulette table}
{54701}{}{This is a gambling table.}
{54800}{}{Roulette table}
{54801}{}{This is a gambling table.}
{54900}{}{Roulette table}
{54901}{}{This is a gambling table.}
{55000}{}{Roulette table}
{55001}{}{This is a gambling table.}
{55100}{}{Barrel}
{55101}{}{This empty metal barrel has the nuclear trefoil symbol painted on the side in bright yellow paint.}
{55200}{}{Barrel}
{55201}{}{This barrel contains some green glowing goo. The nuclear trefoil symbol gives a clue to what the goo might be.}
{55300}{}{Computer}
{55301}{}{A very modern looking computer.}
{55400}{}{Computer}
{55401}{}{A very modern looking computer.}
{55500}{}{Suspension tank}
{55501}{}{Some sort of medical or experimental apparatus, it looks as if it could contain a human or larger sized body.}
{55600}{}{Broken Suspension tank}
{55601}{}{A broken piece of equipment. It is beyond repair.}
{55700}{}{Equipment}
{55701}{}{Some important equipment, filled with electronics.}
{55800}{}{Support Platform}
{55801}{}{This platform supports the equipment of the special communications.}
{55900}{}{Don't use}
{56000}{}{Don't use}
{56100}{}{Bed}
{56101}{}{A military-style bunk bed. Looks very uncomfortable. Also looks like you could bounce a quarter off of these sheets.}
{56200}{}{Bed}
{56201}{}{A military-style bunk bed. Looks very uncomfortable. Also looks like you could bounce a quarter off of these sheets.}
{56300}{}{Bed}
{56301}{}{A military-style bunk bed. Looks very uncomfortable. Also looks like you could bounce a quarter off of these sheets.}
{56400}{}{Wire}
{56401}{}{It looks like a serial cable of some sort.}
{56500}{}{Wire}
{56501}{}{It looks like a serial cable of some sort.}
{56600}{}{Sign}
{56601}{}{The sign reads BAR. That should be pretty self-evident.}
{56700}{}{Shadow}
{56800}{}{Flag}
{56801}{}{The flag with the emblem of stagecoach: 4 wagon wheels on the corners and bull head in the center, wearing cowboy hat and a scarf.}
{56900}{}{Shelves}
{56901}{}{You see some metal storage shelves.}
{57000}{}{Shelves}
{57001}{}{You see some metal storage shelves.}
{57100}{}{Shelves}
{57101}{}{You see some metal storage shelves.}
{57200}{}{Shelves}
{57201}{}{You see some metal storage shelves.}
{57300}{}{Bush}
{57400}{}{Bush}
{57500}{}{Bush}
{57600}{}{Rocks}
{57601}{}{Big pile of rocks. By the look of it, they are of local origin.}
{57700}{}{Rocks}
{57701}{}{Small pile of rocks.}
{57800}{}{Rocks}
{57801}{}{Small pile of rocks.}
{57900}{}{Rocks}
{57901}{}{Big pile of rocks.}
{58000}{}{Cliff}
{58100}{}{Door}
{58101}{}{A door that looks perfectly at home in a cell.}
{58200}{}{Bridge support}
{58300}{}{Ladder}
{58301}{}{This ladder leads into the darkness below.}
{58400}{}{Ladder}
{58401}{}{This ladder leads into the darkness below.}
{58500}{}{Machinery}
{58501}{}{It looks like some manufacturing doohikey.}
{58600}{}{Machinery}
{58601}{}{It looks like some manufacturing doohikey.}
{58700}{}{Machinery}
{58701}{}{It looks like some manufacturing doohikey.}
{58800}{}{Machinery}
{58801}{}{It looks like some manufacturing doohikey.}
{58900}{}{Machinery}
{58901}{}{It looks like some manufacturing doohikey.}
{59000}{}{Part}
{59001}{}{It looks like some manufacturing doohikey.}
{59100}{}{Table}
{59101}{}{This metal table looks in good condition. There is a drain in the center of it.}
{59200}{}{Table}
{59201}{}{This metal table looks in good condition. There is a drain in the center of it.}
{59300}{}{Table}
{59301}{}{The metal table is covered by some kind of biomass.}
{59400}{}{Table}
{59401}{}{The metal table is covered by some kind of biomass.}
{59500}{}{Table}
{59501}{}{The metal table is covered by some kind of biomass.}
{59600}{}{Bulletin Board}
{59601}{}{Notices for employment are stapled to the board. It looks well used.}
{59700}{}{Guard Shack}
{59701}{}{This guard shack is over seventy years old, but still in excellent condition.}
{59800}{}{Sign}
{59801}{}{This sign says: General Store.}
{59900}{}{Sign}
{59901}{}{This sign says: General Store.}
{60000}{}{Sign}
{60001}{}{This sign says: Market}
{60100}{}{Slime Pool}
{60101}{}{It looks very unhealthy. You might want to wear armored swim trunks before taking a dip.}
{60200}{}{Slime Pool}
{60201}{}{It looks very unhealthy. You might want to wear armored swim trunks before taking a dip.}
{60300}{}{Slime Pool}
{60301}{}{It looks very unhealthy. You might want to wear armored swim trunks before taking a dip.}
{60400}{}{Table}
{60401}{}{A nice looking metal table.}
{60500}{}{Table}
{60501}{}{A nice looking metal table.}
{60600}{}{Table}
{60601}{}{A nice looking metal table.}
{60700}{}{Table}
{60701}{}{A nice looking metal table.}
{60800}{}{Table}
{60801}{}{This metal table has not been treated well. The rust is very pervasive.}
{60900}{}{Table}
{60901}{}{A good looking metal table, except for the rust.}
{61000}{}{Table}
{61001}{}{A good looking metal table, except for the rust.}
{61100}{}{Table}
{61101}{}{A good looking metal table, except for the rust.}
{61200}{}{Fire Pit}
{61201}{}{The fire is burning.}
{61300}{}{Mirror}
{61301}{}{You look at yourself for a while.}
{61400}{}{Mirror}
{61401}{}{You stare at your image in the mirror for a while.}
{61500}{}{Sink}
{61501}{}{A fully functioning sink. Nice and clean, too.}
{61600}{}{Toilet}
{61601}{}{This toilet is very clean. It works, too.}
{61700}{}{Urinal}
{61701}{}{This urinal is functional.}
{61800}{}{Train door}
{61900}{}{Sink}
{61901}{}{This sink is in perfect condition.}
{62000}{}{Urinal}
{62001}{}{This urinal is in perfect condition.}
{62100}{}{Shower}
{62101}{}{A military-style shower. Not to be used by modest people.}
{62200}{}{Shower}
{62201}{}{A military-style shower. Not to be used by modest people.}
{62300}{}{Shower}
{62301}{}{A military-style shower. Not to be used by modest people.}
{62400}{}{Shower}
{62401}{}{A military-style shower. Not to be used by modest people.}
{62500}{}{Shower}
{62501}{}{A military-style shower. Not to be used by modest people.}
{62600}{}{Shower}
{62601}{}{A military-style shower. Not to be used by modest people.}
{62700}{}{Bed}
{62701}{}{A very comfortable looking bed.}
{62800}{}{Bed}
{62801}{}{A very comfortable looking bed.}
{62900}{}{Bed}
{62901}{}{A structurally-enhanced bunk bed.}
{63000}{}{Bed}
{63001}{}{A structurally-enhanced bunk bed.}
{63100}{}{Bed}
{63101}{}{A structurally-enhanced bunk bed.}
{63200}{}{Wet clothes}
{63201}{}{Someone hung to dry their clothes and left them unattended.}
{63300}{}{Water collector}
{63301}{}{This huge tank stores water.}
{63400}{}{Stand}
{63401}{}{Stand with photographs of some of the people that seem familiar to you. It reads: "Our Heroes"}
{63500}{}{Stand}
{63501}{}{Stand with the collective photo of studio workers.}
{63600}{}{Cooler}
{63601}{}{Usual cooler.}
{63700}{}{Computer}
{63701}{}{A large computer.}
{63800}{}{Computer}
{63801}{}{A large computer.}
{63900}{}{Computer}
{63901}{}{A large computer.}
{64000}{}{Terminal}
{64001}{}{The terminal to a large computer.}
{64100}{}{Dead Body}
{64101}{}{It looks as if this person died very painfully.}
{64200}{}{Dead Body}
{64201}{}{It looks as if this person died very painfully.}
{64300}{}{Dead Body}
{64301}{}{It looks as if this person died very painfully.}
{64400}{}{Dead Body}
{64401}{}{It looks as if this person died very painfully.}
{64500}{}{Door}
{64501}{}{This barred door works well as the door to a jail cell.}
{64600}{}{Terminal}
{64700}{}{Terminal}
{64800}{}{Forklift}
{64801}{}{The forklift is inoperable.}
{64900}{}{Forklift}
{64901}{}{The forklift is inoperable.}
{65000}{}{Auto-doc}
{65001}{}{This Auto-doc is designed to heal illnesses and administer various drugs. Currently inactive.}
{65100}{}{Medical Table}
{65101}{}{This table is very rusty. The drain in the center of the table is clogged.}
{65200}{}{Medical Table}
{65201}{}{This table is very rusty.}
{65300}{}{Gate}
{65301}{}{This gate has a bar that raises and lowers.}
{65400}{}{Pipe}
{65500}{}{Pipe}
{65600}{}{Power Generator}
{65601}{}{A Wattz ElectroBox power generator. Fairly standard as back-up generators before the war.}
{65700}{}{Table with parts}
{65701}{}{Usual table, that is used as a workbench for weapon repair.}
{65800}{}{Express}
{65801}{}{Improvised transport, put together with bus and car parts. It is purposely been set out of order.}
{65900}{}{Table}
{65901}{}{A high-quality table. Hand-made, but it looks much nicer than any table you've seen before.}
{66000}{}{Table}
{66001}{}{A high-quality table. Hand-made, but it looks much nicer than any table you've seen before.}
{66100}{}{Table}
{66101}{}{A high-quality table. Hand-made, but it looks much nicer than any table you've seen before.}
{66200}{}{Chair}
{66201}{}{A very nice looking chair.}
{66300}{}{Chair}
{66301}{}{A very nice looking chair.}
{66400}{}{Chair}
{66401}{}{A very nice looking chair.}
{66500}{}{Chair}
{66501}{}{A very nice looking chair.}
{66600}{}{Chair}
{66601}{}{A very nice looking chair.}
{66700}{}{Chair}
{66701}{}{A very nice looking chair.}
{66800}{}{Chair}
{66801}{}{A very nice looking chair.}
{66900}{}{Chair}
{66901}{}{A very nice looking chair.}
{67000}{}{Chair}
{67001}{}{A very nice looking chair.}
{67100}{}{Chair}
{67101}{}{A very nice looking chair.}
{67200}{}{Chair}
{67201}{}{A very nice looking chair.}
{67300}{}{Chair}
{67301}{}{A very nice looking chair.}
{67400}{}{Chair}
{67401}{}{A very nice looking chair.}
{67500}{}{Chair}
{67501}{}{A very nice looking chair.}
{67600}{}{Chair}
{67601}{}{A very nice looking chair.}
{67700}{}{Chair}
{67701}{}{A very nice looking chair.}
{67800}{}{Bed}
{67801}{}{A very nice looking bed.}
{67900}{}{Bed}
{67901}{}{A very nice looking bed.}
{68000}{}{Bed}
{68001}{}{A very nice looking bed.}
{68100}{}{Bed}
{68101}{}{A very nice looking bed.}
{68200}{}{Stove}
{68201}{}{A functional wood-burning stove.}
{68300}{}{Stove}
{68301}{}{A functional wood-burning stove.}
{68400}{}{Stove}
{68401}{}{A functional wood-burning stove.}
{68500}{}{Stove}
{68501}{}{A functional wood-burning stove.}
{68600}{}{Broken post}
{68700}{}{Bridge support}
{68800}{}{Stage of rocket carrier}
{68801}{}{You see the charred body of some apparatus.}
{68900}{}{Beanbag}
{68901}{}{A bunch of cans and bolts.}
{69000}{}{Toilet}
{69001}{}{A crude, but effective, toilet. There are some leaves dropped into the hole to manage the odor.}
{69100}{}{Mountain}
{69101}{}{These mountain walls look very inaccessible.}
{69200}{}{Mountain}
{69201}{}{These mountain walls look very inaccessible.}
{69300}{}{Mountain}
{69301}{}{These mountain walls look very inaccessible.}
{69400}{}{Mountain}
{69401}{}{These mountain walls look very inaccessible.}
{69500}{}{Mountain}
{69501}{}{These mountain walls look very inaccessible.}
{69600}{}{Mountain}
{69601}{}{These mountain walls look very inaccessible.}
{69700}{}{Bus}
{69701}{}{You see an ordinary bus. It will never be able to transport children to school.}
{69800}{}{Bus}
{69801}{}{You see a badly burned bus. More precisely, a useless piece of rust.}
{69900}{}{Your storage of Nuka-Cola}
{69901}{}{You see boxes with your personal storage of Nuka-Cola.}
{70000}{}{Collapse}
{70001}{}{You see the collapsed walls and ceiling, buried by a layer of sand and concrete.}
{70100}{}{Advertising post}
{70101}{}{Just an old advertising sign on a hefty post. Rusted so much that you cannot read anything on it anymore.}
{70200}{}{Wall}
{70201}{}{Just a dilapidated wall. That's all.}
{70300}{}{Cliff}
{70301}{}{You can't climb up this cliff.}
{70400}{}{Stage of rocket carrier}
{70401}{}{You see the charred body of some apparatus.}
{70500}{}{Stage of rocket carrier}
{70501}{}{You see the charred body of some apparatus.}
{70600}{}{Shadow}
{70601}{}{This is a shadow.}
{70700}{}{Sign}
{70701}{}{The sign requires a lower speed - no more than 20 miles per hour. You don't need it.}
{70800}{}{Express}
{70801}{}{Reconstructed and converted pre-war bus.}
{70900}{}{Street sign}
{71000}{}{Street sign}
{71100}{}{Street sign}
{71200}{}{Street sign}
{71300}{}{Express}
{71301}{}{Reconstructed and refurbished pre-war bus.}
{71400}{}{Cliff}
{71401}{}{You can't climb up this cliff.}
{71500}{}{Cliff}
{71501}{}{You can't climb up this cliff.}
{71600}{}{Cliff}
{71601}{}{You can't climb up this cliff.}
{71700}{}{Cliff}
{71701}{}{You can't climb up this cliff.}
{71800}{}{Installation}
{71801}{}{You see a part of the power station.}
{71900}{}{Installation}
{71901}{}{You see a part of the power station.}
{72000}{}{Ad}
{72001}{}{You see a "screaming" warning that you are in a zone of federal property. It is forbidden to take pictures and, in general, it would be better for you to get out of here as far away as you can.}
{72100}{}{Goo}
{72101}{}{You see some strange noxious biological goo.}
{72200}{}{Goo}
{72201}{}{You see some strange noxious biological goo.}
{72300}{}{Goo}
{72301}{}{You see some strange noxious biological goo.}
{72400}{}{Shadow}
{72500}{}{Cliff}
{72600}{}{Cliff}
{72700}{}{Cliff}
{72800}{}{Cliff}
{72801}{}{You see some strange noxious biological goo.}
{72900}{}{Goo}
{72901}{}{You see some strange noxious biological goo.}
{73000}{}{Goo}
{73001}{}{You see some strange noxious biological goo.}
{73100}{}{Goo}
{73101}{}{You see some strange noxious biological goo.}
{73200}{}{Goo}
{73201}{}{You see some strange noxious biological goo.}
{73300}{}{Goo}
{73301}{}{You see some strange noxious biological goo.}
{73400}{}{Goo}
{73401}{}{You see some strange noxious biological goo.}
{73500}{}{Goo}
{73501}{}{You see some strange noxious biological goo.}
{73600}{}{Goo}
{73601}{}{You see some strange noxious biological goo.}
{73700}{}{Goo}
{73701}{}{You see some strange noxious biological goo.}
{73800}{}{Goo}
{73801}{}{You see some strange noxious biological goo.}
{73900}{}{Goo}
{73901}{}{You see some strange noxious biological goo.}
{74000}{}{Goo}
{74001}{}{You see some strange noxious biological goo.}
{74100}{}{Goo}
{74101}{}{You see some strange noxious biological goo.}
{74200}{}{Goo}
{74201}{}{You see some strange noxious biological goo.}
{74300}{}{Goo}
{74301}{}{You see some strange noxious biological goo.}
{74400}{}{Goo}
{74401}{}{You see some strange noxious biological goo.}
{74500}{}{Goo}
{74501}{}{You see some strange noxious biological goo.}
{74600}{}{Goo}
{74601}{}{You see some strange noxious biological goo.}
{74700}{}{Goo}
{74701}{}{You see some strange noxious biological goo.}
{74800}{}{Goo}
{74801}{}{You see some strange noxious biological goo.}
{74900}{}{Cliff}
{74901}{}{You can't climb up this cliff.}
{75000}{}{Entry}
{75001}{}{Rise to the top terrace.}
{75100}{}{Entry}
{75101}{}{Rise to the top terrace.}
{75200}{}{Cliff}
{75201}{}{You can't climb up this cliff.}
{75300}{}{Entry}
{75301}{}{Rise to the top terrace.}
{75400}{}{Cliff}
{75401}{}{You can't climb up this cliff.}
{75500}{}{Cliff}
{75501}{}{You can't climb up this cliff.}
{75600}{}{Cliff}
{75601}{}{You can't climb up this cliff.}
{75700}{}{Cliff}
{75701}{}{You can't climb up this cliff.}
{75800}{}{Cliff}
{75801}{}{You can't climb up this cliff.}
{75900}{}{Cliff}
{75901}{}{You can't climb up this cliff.}
{76000}{}{Cliff}
{76001}{}{You can't climb up this cliff.}
{76100}{}{Cliff}
{76101}{}{You can't climb up this cliff.}
{76200}{}{Sign}
{76201}{}{The sign requires a lower speed - no more than 20 miles per hour. You do not need this.}
{76300}{}{Ad}
{76301}{}{You see a "screaming" warning that you are in a zone of federal property. It is forbidden to take pictures and, in general, it would be better for you to get out of here as far away as you can.}
{76400}{}{Radar}
{76401}{}{Radar for transmitting and receiving messages over long distances.}
{76500}{}{Device}
{76501}{}{A certain device, covered with tarpaulin and prepared for transportation.}
{76600}{}{Device}
{76601}{}{A certain device, covered with tarpaulin and prepared for transportation.}
{76700}{}{Console}
{76800}{}{Nuclear bomb}
{76900}{}{Support base}
{76901}{}{This base cradles the nuclear bomb that is sitting on it.}
{77000}{}{Ravine}
{77100}{}{Shadow}
{77200}{}{Chair}
{77201}{}{There is nothing unusual about this chair.}
{77300}{}{Chair}
{77301}{}{There is nothing unusual about this chair.}
{77400}{}{Chair}
{77401}{}{There is nothing unusual about this chair.}
{77500}{}{Chair}
{77501}{}{There is nothing unusual about this chair.}
{77600}{}{Chair}
{77601}{}{There is nothing unusual about this chair.}
{77700}{}{Chair}
{77701}{}{There is nothing unusual about this chair.}
{77800}{}{Chair}
{77801}{}{There is nothing unusual about this chair.}
{77900}{}{Chair}
{77901}{}{There is nothing unusual about this chair.}
{78000}{}{Pillar}
{78001}{}{A support pillar.}
{78100}{}{Pillar}
{78101}{}{A support pillar.}
{78200}{}{Pillar}
{78201}{}{A support pillar.}
{78300}{}{Pillar}
{78301}{}{A support pillar.}
{78400}{}{Drier}
{78401}{}{Usual drier for clothing.}
{78500}{}{Bed}
{78501}{}{This bed is in poor condition.}
{78600}{}{Bed}
{78601}{}{This bed is in poor condition.}
{78700}{}{Bed}
{78701}{}{This bed is in pretty bad condition.}
{78800}{}{Monitors}
{78801}{}{These monitors are broken and cannot function.}
{78900}{}{Monitors}
{78901}{}{These monitors are broken and cannot function.}
{79000}{}{Monitors}
{79001}{}{These monitors are broken and cannot function.}
{79100}{}{Monitors}
{79101}{}{These monitors are broken and cannot function.}
{79200}{}{Vent}
{79201}{}{Very little fresh air is coming from this vent.}
{79300}{}{Vent}
{79301}{}{Almost no fresh air is coming from this vent.}
{79400}{}{Vent}
{79401}{}{No fresh air is coming from this vent.}
{79500}{}{Vent}
{79501}{}{Just a tiny amount of fresh air is coming from this vent.}
{79600}{}{Table}
{79601}{}{There is nothing unusual about this table, except that it is almost destroyed.}
{79700}{}{Table}
{79701}{}{This table was badly damaged.}
{79800}{}{Table}
{79801}{}{This table is in very poor condition.}
{79900}{}{Table}
{79901}{}{There is no reason to search this table.}
{80000}{}{VDU}
{80001}{}{This monitor system is currently not working.}
{80100}{}{VDU}
{80101}{}{This monitor system is currently not working.}
{80200}{}{Monitor}
{80201}{}{The monitor screen is cracked and destroyed.}
{80300}{}{Monitor}
{80301}{}{This monitor is worthless with a broken display screen.}
{80400}{}{Computer}
{80401}{}{This computer is broken.}
{80500}{}{Computer}
{80501}{}{This computer is broken.}
{80600}{}{Computer}
{80601}{}{This computer is broken.}
{80700}{}{Chair}
{80701}{}{A chair with damaged sheathing.}
{80800}{}{Chair}
{80801}{}{A chair with damaged sheathing.}
{80900}{}{Chair}
{80901}{}{A chair with damaged sheathing.}
{81000}{}{Chair}
{81001}{}{A chair with damaged sheathing.}
{81100}{}{Vent}
{81101}{}{This vent has been damaged beyond repair.}
{81200}{}{Vent}
{81201}{}{This vent is very damaged, and cannot be repaired.}
{81300}{}{Vent}
{81301}{}{This vent is not functioning at all.}
{81400}{}{Computer}
{81401}{}{This computer looks like it is barely functional.}
{81500}{}{Computer}
{81501}{}{This computer looks like it is barely functional.}
{81600}{}{Monitor}
{81601}{}{The monitor is barely working.}
{81700}{}{Monitor}
{81701}{}{The monitor is barely working.}
{81800}{}{Computer}
{81801}{}{The computer is not functioning.}
{81900}{}{Computer}
{81901}{}{The computer is not functioning.}
{82000}{}{Monitor}
{82001}{}{The monitor is not functioning.}
{82100}{}{Monitor}
{82101}{}{The monitor is not functioning.}
{82200}{}{Doorway}
{82201}{}{It looks like a very nice doorway. It does the job of holding up a door very well.}
{82300}{}{Monitors}
{82301}{}{The monitors are in good condition.}
{82400}{}{Monitors}
{82401}{}{The monitors are in good condition.}
{82500}{}{Wall}
{82600}{}{Armored door}
{82601}{}{A very sturdy door. Holding up after even the explosion.}
{82700}{}{Light}
{82701}{}{A security light.}
{82800}{}{Light}
{82801}{}{A security light.}
{82900}{}{Rope}
{83000}{}{Robot Receptacle}
{83001}{}{This is a robot recharging bay. When not in service, robots will dock here to shut down and recharge.}
{83100}{}{Robot Receptacle}
{83101}{}{This is a robot recharging bay. When not in service, robots will dock here to shut down and recharge.}
{83200}{}{Robot Receptacle}
{83201}{}{This is a robot recharging bay. When not in service, robots will dock here to shut down and recharge.}
{83300}{}{Robot Receptacle}
{83301}{}{This is a robot recharging bay. When not in service, robots will dock here to shut down and recharge.}
{83400}{}{Robot Receptacle}
{83401}{}{This is a robot recharging bay. When not in service, robots will dock here to shut down and recharge.}
{83500}{}{Machine}
{83501}{}{This machine has something to do with the robot service bays. It does not look particular interesting.}
{83600}{}{Machine}
{83601}{}{This machine has something to do with the robot service bays. It does not look very interesting.}
{83700}{}{Stripe}
{83800}{}{Stripe}
{83900}{}{Stripe}
{84000}{}{Stripe}
{84100}{}{Stripe}
{84200}{}{Stripe}
{84300}{}{Stripe}
{84400}{}{Stripe}
{84500}{}{Stripe}
{84600}{}{Stripe}
{84700}{}{Stripe}
{84800}{}{Door}
{84801}{}{A very normal wooden door.}
{84900}{}{Door}
{84901}{}{A very normal wooden door.}
{85000}{}{Door}
{85001}{}{A very normal wooden door.}
{85100}{}{Poster}
{85101}{}{A pre-war poster calling for a blues concert at "Hard Rock" cafe.}
{85200}{}{Poster}
{85201}{}{Pre-war poster calling on the football Olympics at the stadium in Provo.}
{85300}{}{Medical Table}
{85301}{}{This looks like a medical examination table.}
{85400}{}{Rope}
{85500}{}{Cables}
{85501}{}{Bare wires. Be careful!}
{85600}{}{Graffiti}
{85700}{}{Graffiti}
{85800}{}{Graffiti}
{85900}{}{Graffiti}
{86000}{}{Graffiti}
{86100}{}{Graffiti}
{86200}{}{Graffiti}
{86300}{}{Graffiti}
{86400}{}{Graffiti}
{86500}{}{Graffiti}
{86600}{}{Graffiti}
{86700}{}{Graffiti}
{86800}{}{Graffiti}
{86900}{}{Sign}
{86901}{}{It says: GUNS. They might sell guns there.}
{87000}{}{Sign}
{87001}{}{The sign reads: Police.}
{87100}{}{Elevated bridge}
{87200}{}{Poster}
{87300}{}{Poster}
{87301}{}{On this faded poster is seen a desolate track with a mountain ridge in the background, and the inscription "Nevada is a country of entertainment".}
{87400}{}{Stella}
{87500}{}{Sign}
{87501}{}{This is a signboard of the ring, which is located in the basement of the building.}
{87600}{}{Sign}
{87601}{}{The inscription on this unattractive sign says: "The city of caravans".}
{87700}{}{Sign}
{87701}{}{This is the signboard of the slavers guild.}
{87800}{}{Egg shell}
{87801}{}{Pieces of a broken egg shell.}
{87900}{}{Egg shell}
{87901}{}{Pieces of a broken egg shell.}
{88000}{}{Egg shell}
{88001}{}{Pieces of a broken egg shell.}
{88100}{}{Egg shell}
{88101}{}{Pieces of a broken egg shell.}
{88200}{}{Egg shell}
{88201}{}{Pieces of a broken egg shell.}
{88300}{}{Egg shell}
{88301}{}{Pieces of a broken egg shell.}
{88400}{}{Egg shell}
{88401}{}{Pieces of a broken egg shell.}
{88500}{}{Egg shell}
{88501}{}{Pieces of a broken egg shell.}
{88600}{}{Lamp post}
{88601}{}{A lamp post. It looks like it is in good working order.}
{88700}{}{Sign}
{88701}{}{The sign reads: Motel.}
{88800}{}{Mushrooms}
{88801}{}{This table planter has been filled with dung, and mushrooms are happily growing in it.}
{88900}{}{Mushrooms}
{88901}{}{This table planter has been filled with dung, and mushrooms are happily growing in it.}
{89000}{}{Skeleton}
{89100}{}{Barrel}
{89200}{}{Barrel}
{89300}{}{Sign}
{89301}{}{An advertisement for Blades-brand razor blades.}
{89400}{}{Shower}
{89401}{}{A fairly normal shower stall.}
{89500}{}{Shower}
{89501}{}{A fairly normal shower stall.}
{89600}{}{Roof}
{89700}{}{Shadow}
{89800}{}{Shadow}
{89900}{}{Shadow}
{90000}{}{Stella}
{90100}{}{Elevator shaft}
{90101}{}{The shaft has a rope hanging from above.}
{90200}{}{Elevator shaft}
{90201}{}{The shaft has a rope hanging down from the edge.}
{90300}{}{Medical bed}
{90301}{}{This bed has a built-in display for monitoring the patients progress.}
{90400}{}{Water Pump}
{90401}{}{This is a piece of machinery that pumps water up from below.}
{90500}{}{Overseer}
{90501}{}{Overseer. You may not believe your eyes, but it's him.}
{90600}{}{Power Armor Parts}
{90601}{}{These are parts to a suit of Power Armor.}
{90700}{}{Light}
{90701}{}{This security light is currently pulsating a bright red.}
{90800}{}{Light}
{90801}{}{This security light is currently pulsating a bright red.}
{90900}{}{Symbol}
{91000}{}{Symbol}
{91100}{}{Symbol}
{91200}{}{Symbol}
{91300}{}{Symbol}
{91400}{}{Symbol}
{91500}{}{Rope}
{91600}{}{Rope}
{91700}{}{Rope}
{91800}{}{Rope}
{91900}{}{Rope}
{92000}{}{Rope}
{92100}{}{Rope}
{92200}{}{Rope}
{92300}{}{Mountain}
{92400}{}{Mountain}
{92500}{}{Mountain}
{92600}{}{Mountain}
{92700}{}{Panorama}
{92800}{}{Terminal}
{92801}{}{Terminal for remote control of a crane inside the hangar.}
{92900}{}{Mountain}
{93000}{}{Mountain}
{93100}{}{Giant letter}
{93101}{}{This letter fell from the tower. Previously, it was part of "Artesian Water" signboard.}
{93200}{}{Giant letter}
{93201}{}{Where did it came from?}
{93300}{}{Giant letter}
{93301}{}{Where did it came from?}
{93400}{}{Skeletons}
{93401}{}{Apparently, death found these people asleep and did not even allow them to wake up.}
{93500}{}{Torch}
{93501}{}{A lit torch in a wall sconce.}
{93600}{}{Torch}
{93601}{}{A lit torch in a wall sconce.}
{93700}{}{Tank}
{93701}{}{Huge storage for bulk materials.}
{93800}{}{Stone Monument}
{93900}{}{Stone Monument}
{94000}{}{Skull Pole}
{94001}{}{A pole with human skulls attached.}
{94100}{}{Skull Pole}
{94101}{}{A pole with human skulls attached.}
{94200}{}{Skull Pole}
{94201}{}{A pole with human skulls attached.}
{94300}{}{Plant}
{94400}{}{Plant}
{94500}{}{Tree}
{94600}{}{Tree}
{94700}{}{Tree}
{94800}{}{Bed}
{94900}{}{Bed}
{95000}{}{Generator}
{95001}{}{Homemade power station based on car engine.}
{95100}{}{Raised Stone Plate}
{95101}{}{A raised stone plate.}
{95200}{}{Disabled stone plate}
{95201}{}{A Disabled stone plate.}
{95300}{}{Triggered Stone Plate}
{95301}{}{A triggered stone plate.}
{95400}{}{Door}
{95500}{}{Electrical switchboard}
{95501}{}{Just a transformer in the power supply circuit. Nothing interesting.}
{95600}{}{Door}
{95700}{}{Door}
{95800}{}{Door}
{95900}{}{Door}
{96000}{}{Door}
{96100}{}{Door}
{96200}{}{Door}
{96300}{}{Corn}
{96400}{}{Corn}
{96500}{}{Corn}
{96600}{}{Corn}
{96700}{}{Corn}
{96800}{}{Corn}
{96900}{}{Wood support}
{97000}{}{Wood support}
{97100}{}{Wood support}
{97200}{}{Wood support}
{97300}{}{Wood support}
{97400}{}{Wood support}
{97500}{}{Damaged Wood support}
{97501}{}{This support looks like it could collapse if stressed.}
{97600}{}{Collapsed floor}
{97601}{}{The stone floor has collapsed here into the lower level.}
{97700}{}{Ladder Down}
{97701}{}{A man-made hole with a ladder leading down.}
{97800}{}{Door}
{97900}{}{Wall}
{98000}{}{Reactor 5 sign}
{98100}{}{Door}
{98200}{}{Door}
{98300}{}{Door}
{98400}{}{Door}
{98500}{}{Radioactive goo}
{98600}{}{Radioactive goo}
{98700}{}{Radioactive goo}
{98800}{}{Radioactive goo}
{98900}{}{Security door}
{99000}{}{Vault door}
{99100}{}{Utility Crane}
{99200}{}{Strange rocks}
{99201}{}{This collapse seems to came up out of nowhere!}
{99300}{}{Well}
{99400}{}{Billboard}
{99500}{}{Electrical board}
{99600}{}{Hole}
{99601}{}{You can't see the bottom of this pit.}
{99700}{}{Floor Plate}
{99701}{}{You see a floor plate trap.}
{99800}{}{Disabled Floor Plate}
{99801}{}{This floor plate trap has been disabled.}
{99900}{}{Triggered Floor Plate}
{99901}{}{This floor plate trap has been triggered. Oops!}
{100000}{}{Still}
{100001}{}{This looks like a wood-burning alcohol still.}
{100100}{}{Poster}
{100200}{}{Power plant machinery}
{100201}{}{Some sophisticated equipment.}
{100300}{}{Power plant machinery}
{100301}{}{Some sophisticated equipment.}
{100400}{}{Power plant machinery}
{100401}{}{Some sophisticated equipment.}
{100500}{}{Power plant machinery}
{100501}{}{Some sophisticated equipment.}
{100600}{}{Power plant machinery}
{100601}{}{Some sophisticated equipment.}
{100700}{}{Power plant pump Control}
{100701}{}{This is the coolant pumping machine for the reactor.}
{100800}{}{Poster}
{100900}{}{Car}
{101000}{}{Smashed patrol automobile}
{101001}{}{This automobile, obviously, have been in a terrible accident.}
{101100}{}{Car}
{101200}{}{Graveyard}
{101201}{}{A grave is located here.}
{101300}{}{Headstone}
{101301}{}{Headstone}
{101400}{}{Headstone}
{101401}{}{Headstone}
{101500}{}{Headstone}
{101501}{}{Headstone}
{101600}{}{Headstone}
{101601}{}{Headstone}
{101700}{}{Plow}
{101701}{}{This plow is designed to be dragged by a Brahmin.}
{101800}{}{Plow}
{101801}{}{This plow is designed to be dragged by a Brahmin.}
{101900}{}{Water}
{102000}{}{Frame}
{102001}{}{Dilapidated frame of the advertising console.}
{102100}{}{Console}
{102101}{}{Neon advertising console of the cafe-club.}
{102200}{}{Wall}
{102300}{}{Neon advertising}
{102301}{}{Neon advertising console of "The Sixth Bullet" hotel.}
{102400}{}{Frame}
{102401}{}{A half-ruined metal frame holding an advertising console.}
{102500}{}{Disk}
{102501}{}{You have absolutely no idea what it is. One can only guess that sometime this disk could fly.}
{102600}{}{Shadow}
{102700}{}{Nuclear reactor}
{102701}{}{Thanks to nuclear fuel, this reactor will be able to produce energy for many decades.}
{102800}{}{Newspaper machine}
{102801}{}{This ancient restored newspaper machine sells some books and magazines.}
{102900}{}{Graffiti}
{103000}{}{Territory mark}
{103100}{}{Territory mark}
{103200}{}{Territory mark}
{103300}{}{Poster}
{103400}{}{Poster}
{103500}{}{Graffiti}
{103600}{}{Graffiti}
{103700}{}{Graffiti}
{103800}{}{Graffiti}
{103900}{}{Graffiti}
{104000}{}{Graffiti}
{104100}{}{Graffiti}
{104200}{}{Graffiti}
{104300}{}{Graffiti}
{104400}{}{Graffiti}
{104500}{}{Graffiti}
{104600}{}{Graffiti}
{104700}{}{Poster}
{104800}{}{Poster}
{104900}{}{Poster}
{105000}{}{Poster}
{105100}{}{Poster}
{105200}{}{Poster}
{105300}{}{Graffiti}
{105301}{}{This graffiti reads: "Fear and Loathing in Las Vegas".}
{105400}{}{Graffiti}
{105500}{}{Graffiti}
{105600}{}{Graffiti}
{105700}{}{Poster}
{105800}{}{Poster}
{105900}{}{Poster}
{106000}{}{Sign}
{106100}{}{Graffiti}
{106200}{}{Graffiti}
{106300}{}{Graffiti}
{106400}{}{Graffiti}
{106500}{}{Graffiti}
{106600}{}{Graffiti}
{106700}{}{Graffiti}
{106800}{}{Graffiti}
{106900}{}{Graffiti}
{107000}{}{Graffiti}
{107100}{}{Broken glass}
{107200}{}{Broken glass}
{107300}{}{Graffiti}
{107400}{}{Graffiti}
{107500}{}{Graffiti}
{107600}{}{Graffiti}
{107700}{}{Graffiti}
{107800}{}{Graffiti}
{107900}{}{Graffiti}
{108000}{}{Graffiti}
{108100}{}{Graffiti}
{108200}{}{Graffiti}
{108300}{}{Graffiti}
{108400}{}{Graffiti}
{108500}{}{Graffiti}
{108600}{}{Graffiti}
{108700}{}{Broken glass}
{108800}{}{Broken glass}
{108900}{}{Graffiti}
{109000}{}{Graffiti}
{109100}{}{Graffiti}
{109200}{}{Graffiti}
{109300}{}{Graffiti}
{109400}{}{Graffiti}
{109500}{}{Graffiti}
{109600}{}{Graffiti}
{109700}{}{Graffiti}
{109800}{}{Poster}
{109900}{}{Poster}
{110000}{}{Poster}
{110100}{}{Poster}
{110200}{}{Poster}
{110300}{}{Poster}
{110400}{}{Poster}
{110500}{}{Poster}
{110600}{}{USA map}
{110601}{}{For the first time you see a pre-war map of the USA. It was a big country...}
{110700}{}{Poster}
{110800}{}{Poster}
{110900}{}{Poster}
{111000}{}{Sign}
{111100}{}{Sign}
{111200}{}{Sign}
{111300}{}{Sign}
{111400}{}{Sign}
{111500}{}{Sign}
{111600}{}{Sign}
{111700}{}{Sign}
{111800}{}{Wall}
{111900}{}{Wall}
{112000}{}{Wall}
{112100}{}{Wall}
{112200}{}{Wall}
{112300}{}{Wall}
{112400}{}{Winding tube}
{112401}{}{This hefty pipe leads from an underground hangar. Surely you can go down on it.}
{112500}{}{Account book}
{112501}{}{This is an accounting ledger. Reading it will be very tedious.}
{112600}{}{Car}
{112601}{}{It appears that this car stood in the open for more than ten years.}
{112700}{}{Bones}
{112701}{}{Human bones that belonged to a man, woman and child. No traces of violence on them to be seen. Perhaps these people died from radiation or famine.}
{112800}{}{Bones}
{112801}{}{Human bones that belonged to a man, woman and child. No traces of violence on them to be seen. Perhaps these people died from radiation or famine.}
{112900}{}{Road sign}
{113000}{}{Ladder top}
{113100}{}{Ladder bottom}
{113101}{}{This ladder is too high above the ground to reach it.}
{113200}{}{Car}
{113201}{}{A very expensive nuclear-powered car.}
{113300}{}{Car}
{113301}{}{A very expensive nuclear-powered car.}
{113400}{}{Car}
{113401}{}{It used to be a very expensive nuclear-powered car. Now - a heap of rusty metal.}
{113500}{}{Car}
{113501}{}{It used to be a very expensive nuclear-powered car. Now - a heap of rusty metal.}
{113600}{}{Grid}
{113700}{}{Boarded-up box}
{113701}{}{Boarded-up wooden box. Perhaps, it contains something of use.}
{113800}{}{File cabinet}
{113801}{}{Cabinet with drawers for various documents. For a collector of office paper - a real treasure. And for you nothing interesting.}
{113900}{}{Map}
{114000}{}{Old tires}
{114001}{}{This mountain of old tires blocking your way. Need a tractor or five pounds of explosives to clear this place.}
{114100}{}{Movie camera}
{114200}{}{Coffin}
{114300}{}{Coffin}
{114400}{}{Coffin}
{114500}{}{Coffin}
{114600}{}{Steel bars}
{114700}{}{Steel bars}
{114800}{}{Steel window cover}
{114900}{}{Steel window cover}
{115000}{}{Laser tripwire}
{115100}{}{Laser tripwire}
{115200}{}{Shit}
{115201}{}{Incorrigible bastard, tied to the pillory.}
{115300}{}{Ladder}
{115400}{}{Corpse}
{115500}{}{"Out of Business" Sign}
{115600}{}{"Out of Business" Sign}
{115700}{}{Support}
{115800}{}{Support}
{115900}{}{Bridge controls}
{116000}{}{Hanging bridge}
{116100}{}{Retinal scanner}
{116101}{}{This is a security device that scans a person's retinal pattern.}
{116200}{}{Control room sign}
{116300}{}{Control room sign}
{116400}{}{Control room sign}
{116500}{}{Construction zone sign}
{116501}{}{Large and heavy protective sign. So heavy that one person will not be able to move it.}
{116600}{}{Construction zone sign}
{116601}{}{Large and heavy protective sign. So heavy that one person will not be able to move it.}
{116700}{}{Machine}
{116701}{}{A non-functional machine.}
{116800}{}{Machine}
{116801}{}{A non-functional machine.}
{116900}{}{Door}
{117000}{}{Door}
{117100}{}{Pipes}
{117101}{}{A set of pipes going into the reactor.}
{117200}{}{Tank}
{117300}{}{Tanks}
{117400}{}{Tanks}
{117500}{}{Tanks}
{117600}{}{Vent}
{117700}{}{Vent}
{117800}{}{Wall}
{117900}{}{Fence}
{118000}{}{Fence}
{118100}{}{Fence}
{118200}{}{Vent}
{118300}{}{Vent}
{118400}{}{Window with bars}
{118500}{}{Manager's office sign}
{118600}{}{Supply room sign}
{118700}{}{Radiation warning sign}
{118800}{}{Steam}
{118900}{}{Machine}
{118901}{}{A misc. piece of equipment for the power plant.}
{119000}{}{Tank}
{119100}{}{Fire}
{119200}{}{Water}
{119300}{}{Graffiti}
{119400}{}{Graffiti}
{119500}{}{Pallet}
{119501}{}{These boards are piled up somehow unnatural, as if they were covering something.}
{119600}{}{Pipe support}
{119700}{}{Signboard}
{119800}{}{Pipe support}
{119900}{}{Poster}
{120000}{}{Fire pit}
{120100}{}{Cave wall}
{120200}{}{Cave wall}
{120300}{}{Cave wall}
{120400}{}{Cave wall}
{120500}{}{Cave wall}
{120600}{}{Cave wall}
{120700}{}{Cave wall}
{120800}{}{Cave wall}
{120900}{}{Cave wall}
{121000}{}{Cave wall}
{121100}{}{Cave wall}
{121200}{}{Cave wall}
{121300}{}{Cave wall}
{121400}{}{Cave wall}
{121500}{}{Cave wall}
{121600}{}{Stake}
{121601}{}{This stake appears to have a person impaled on the top!}
{121700}{}{Stake}
{121701}{}{This stake appears to have a person impaled on the top!}
{121800}{}{Stake}
{121801}{}{This stake appears to have a person impaled on the top!}
{121900}{}{Stake}
{121901}{}{This stake appears to have a person impaled on the top!}
{122000}{}{Stake}
{122001}{}{This stake appears to have a person impaled on the top!}
{122100}{}{Writing-table}
{122101}{}{Just a table. What differs in this table is only the presence of writing materials.}
{122200}{}{Stake}
{122201}{}{This stake appears to have a human skull placed on the top.}
{122300}{}{Stake}
{122301}{}{This stake appears to have a human skull placed on the top.}
{122400}{}{Stake}
{122401}{}{This empty stake looks ready for an unwilling victim.}
{122500}{}{Stake}
{122501}{}{This empty stake looks ready for an unwilling victim.}
{122600}{}{Stake}
{122601}{}{This empty stake looks ready for an unwilling victim.}
{122700}{}{Stake}
{122701}{}{This empty stake looks ready for an unwilling victim.}
{122800}{}{"Wanted" Sign}
{122801}{}{The picture on this sign looks oddly like you!}
{122900}{}{Floor}
{123000}{}{Poster}
{123100}{}{Howitzer}
{123101}{}{This strange-looking cannon looks like a relic from the pre-war days. You wonder how it ended up here.}
{123200}{}{Lamp}
{123300}{}{Radiation sign}
{123301}{}{"Dangerous! Radiation!"}
{123400}{}{Radiation sign}
{123401}{}{"Dangerous! Radiation!"}
{123500}{}{Poster}
{123600}{}{Switch}
{123700}{}{Cross}
{123800}{}{Cross}
{123900}{}{Cross}
{124000}{}{Cross}
{124100}{}{Cross}
{124200}{}{Cross}
{124300}{}{Gas pump}
{124400}{}{Gas pump}
{124500}{}{Gas pump}
{124600}{}{Pep Gas Sign}
{124700}{}{Sign Shadow}
{124800}{}{Haybed}
{124900}{}{Haybed}
{125000}{}{Haybed}
{125100}{}{Haybed}
{125200}{}{Haybed}
{125300}{}{Haybed}
{125400}{}{Shop signboard}
{125500}{}{A street vendor's stand}
{125600}{}{A street vendor's stand}
{125700}{}{A street vendor's stand}
{125800}{}{A street vendor's stand}
{125900}{}{Welcoming sign}
{125901}{}{Welcome road sign of pre-war Lovelock town.}
{126000}{}{Newspaper clippings}
{126001}{}{Judging by these clippings, the inhabitant of this room is very obsessed with the fear of alien invasion.}
{126100}{}{Sheriff office}
{126200}{}{Poster}
{126201}{}{A poster with some guy holding a camera. His face is familiar to everyone, but now no one will say exactly who it is.}
{126300}{}{Pumpkins}
{126400}{}{Poster}
{126500}{}{Lamps}
{126600}{}{Barricade}
{126700}{}{Dirty water}
{126800}{}{Dirty water}
{126900}{}{Dirty water}
{127000}{}{Dirty water}
{127100}{}{Casino sign}
{127200}{}{Casino sign}
{127300}{}{Pile of rocks}
{127301}{}{These rocks appear to be keeping something in.}
{127400}{}{Beam}
{127500}{}{Beam}
{127600}{}{Beam}
{127700}{}{Beam}
{127800}{}{Beam}
{127900}{}{Beam}
{128000}{}{Beam}
{128100}{}{Beam}
{128200}{}{Beam}
{128300}{}{Beam}
{128400}{}{Shadow}
{128500}{}{Shadow}
{128600}{}{Shadow}
{128700}{}{Shadow}
{128800}{}{Shadow}
{128900}{}{Shadow}
{129000}{}{Shadow}
{129100}{}{Shadow}
{129200}{}{Shadow}
{129300}{}{Elevator stub}
{129400}{}{Gas pump}
{129500}{}{Gas pump}
{129600}{}{Gas pump}
{129700}{}{Rope}
{129800}{}{Window}
{129900}{}{Brahmin meat}
{130000}{}{Brahmin meat}
{130100}{}{Brahmin meat}
{130200}{}{Brahmin meat}
{130300}{}{Brahmin meat}
{130400}{}{Brahmin meat}
{130500}{}{Beam}
{130600}{}{Beam}
{130700}{}{Beam}
{130800}{}{Beam}
{130900}{}{Beam}
{131000}{}{Beam}
{131100}{}{Beam}
{131200}{}{Beam}
{131300}{}{Shadow}
{131400}{}{Shadow}
{131500}{}{Shadow}
{131600}{}{Shadow}
{131700}{}{Shadow}
{131800}{}{Shadow}
{131900}{}{Shadow}
{132000}{}{Shadow}
{132100}{}{Blood}
{132200}{}{Blood}
{132300}{}{Blood}
{132400}{}{Blood}
{132500}{}{Blood}
{132600}{}{Blood}
{132700}{}{Blood with bones}
{132800}{}{Blood with bones}
{132900}{}{Blood with bones}
{133000}{}{Cave Mouth}
{133100}{}{Microphone}
{133200}{}{Spotlight}
{133300}{}{Spotlight}
{133400}{}{Spotlight}
{133500}{}{Computer}
{133501}{}{A Vault computer terminal, hooked into the mainframe.}
{133600}{}{Computer}
{133601}{}{A Vault computer terminal, hooked into the mainframe.}
{133700}{}{Crane}
{133701}{}{Corroded crane. In such condition there's not much to hope for.}
{133800}{}{Big pile of garbage}
{133801}{}{A pile of usual garbage, composed like a ladder.}
{133900}{}{Wall}
{134000}{}{Wall}
{134100}{}{Wall}
{134200}{}{Wall}
{134300}{}{Wall}
{134400}{}{Wall}
{134500}{}{Wall}
{134600}{}{Wall}
{134700}{}{Ventilation}
{134800}{}{Ventilation}
{134900}{}{Shadow}
{135000}{}{Hangar}
{135100}{}{Hangar}
{135200}{}{Hangar}
{135300}{}{Hangar}
{135400}{}{Hangar}
{135500}{}{Hangar}
{135600}{}{Hangar}
{135700}{}{Hangar}
{135800}{}{Door}
{135900}{}{Panorama}
{136000}{}{Panorama}
{136100}{}{Panorama}
{136200}{}{Panorama}
{136300}{}{Panorama}
{136400}{}{Panorama}
{136500}{}{Firepit}
{136600}{}{Firepit}
{136700}{}{Turret control system}
{136701}{}{This is a powerful computer system designed to coordinate the turrets behaviour on the territory of the base.}
{136800}{}{Shadow}
{136900}{}{Panorama}
{137000}{}{Mountain}
{137100}{}{Cavern}
{137200}{}{Shards of glass}
{137300}{}{Torch}
{137301}{}{A lit torch in a wall sconce.}
{137400}{}{Torch}
{137401}{}{A lit torch in a wall sconce.}
{137500}{}{Torch}
{137501}{}{A lit torch in a wall sconce.}
{137600}{}{Torch}
{137601}{}{A lit torch in a wall sconce.}
{137700}{}{Pumpkin with a candle}
{137800}{}{Storage tank}
{137801}{}{Before you see an automated liquid tank.}
{137900}{}{Grave cross}
{137901}{}{It is written: "Eben Byers. That's how the excessive health care ends".}
{138000}{}{Wall}
{138100}{}{Wall}
{138200}{}{Wall}
{138300}{}{Wall}
{138400}{}{Wall}
{138500}{}{Wall}
{138600}{}{Light}
{138700}{}{Door}
{138800}{}{Door}
{138900}{}{Door}
{139000}{}{Door}
{139100}{}{Door}
{139200}{}{Door}
{139300}{}{Banners}
{139400}{}{Post}
{139500}{}{Post}
{139600}{}{Banners}
{139700}{}{Banners}
{139800}{}{Post}
{139900}{}{Post}
{140000}{}{Banners}
{140100}{}{Shadow}
{140200}{}{Shadow}
{140300}{}{Dirty bomb}
{140301}{}{You have trouble determining what it is. But inside, under the shell of this hulk, is clearly something very radioactive.}
{140400}{}{Dirty bomb}
{140401}{}{You have trouble determining what it is. But inside, under the shell of this hulk, is clearly something very radioactive.}
{140500}{}{Promotional streaming}
{140600}{}{Dirty bomb}
{140601}{}{You have trouble determining what it is. But inside, under the shell of this hulk, is clearly something very radioactive.}
{140700}{}{Beam}
{140800}{}{Signboard}
{140801}{}{The inscription on the sign says: "Drug Store"}
{140900}{}{Grid}
{141000}{}{Ring sign}
{141100}{}{Night club lights}
{141200}{}{Graffiti}
{141300}{}{Brand graffiti}
{141301}{}{Advertising graffiti of the hotel. Someone has already managed to spoil it with hooligan inscriptions.}
{141400}{}{Signboard}
{141401}{}{The inscription on the sign says: "Opal Shop"}
{141500}{}{Power distributor}
{141501}{}{This device is designed to control and distribute electricity.}
{141600}{}{Statue}
{141700}{}{Warehouse door}
{141800}{}{Warehouse door}
{141900}{}{Shifts schedule}
{141901}{}{The schedule of works at the plant. Shifts are exclusively during the daytime, apparently, nobody works in the shop at night.}
{142000}{}{Sheriff Sign}
{142100}{}{Study board}
{142101}{}{You see a blackboard with a lot of chalked records and block diagrams.}
{142200}{}{Jay Kukish's remains}
{142201}{}{This corpse is very fresh. Some organs are excised from it by an accurate surgical hand.}
{142300}{}{Note board}
{142301}{}{You see a board with a lot of chalked notes and plans concerning the work of the factory.}
{142400}{}{Schedule}
{142500}{}{Cliff}
{142600}{}{Ruin}
{142601}{}{Ruins were formed out of the hangar's interiors during the explosion. A bit of everything.}
{142700}{}{Remains}
{142701}{}{This skeleton is very old.}
{142800}{}{TV}
{142801}{}{An ancient television device. As expected, there is nothing to watch.}
{142900}{}{Cleaner robot}
{142901}{}{Robot for cleaning the territory from the effects of radioactive contamination. It has not functioned for a long time.}
{143000}{}{Post with loudspeakers}
{143001}{}{Once upon a time these loudspeakers warned local residents of the danger. Apparently, this did not help them.}
{143100}{}{Street light}
{143200}{}{Graffiti}
{143300}{}{Rope}
{143301}{}{You can climb over the wall with this rope.}
{143400}{}{Ravine}
{143500}{}{Ravine}
{143600}{}{Window}
{143700}{}{Window}
{143800}{}{Window}
{143900}{}{Window}
{144000}{}{Window}
{144100}{}{Window}
{144200}{}{Window}
{144300}{}{Window}
{144400}{}{Window}
{144500}{}{Window}
{144600}{}{Window}
{144700}{}{Window}
{144800}{}{Train door}
{144900}{}{Door}
{145000}{}{Arch support}
{145100}{}{Arch support}
{145200}{}{Arch}
{145300}{}{Arch}
{145400}{}{Water}
{145500}{}{Water}
{145600}{}{Water}
{145700}{}{Water}
{145800}{}{Water}
{145900}{}{Water}
{146000}{}{Water}
{146100}{}{Tanker}
{146200}{}{Tanker}
{146300}{}{Tanker}
{146400}{}{Tanker}
{146500}{}{Foliage}
{146600}{}{Fence door}
{146700}{}{Fence door}
{146800}{}{Command seat}
{146801}{}{This is where the Overseer normally sits.}
{146900}{}{Wall}
{147000}{}{Wall}
{147100}{}{Wall}
{147200}{}{Shadow}
{147300}{}{Hotel entrance}
{147400}{}{Hotel entrance}
{147500}{}{Carpet}
{147600}{}{Casino entrance}
{147700}{}{Casino entrance}
{147800}{}{Hotel entrance}
{147900}{}{Casino door}
{148000}{}{Casino door}
{148100}{}{Casino entrance}
{148200}{}{Casino entrance}
{148300}{}{Casino entrance}
{148400}{}{Casino entrance}
{148500}{}{Casino entrance}
{148600}{}{Casino entrance}
{148700}{}{Casino entrance}
{148800}{}{Casino entrance}
{148900}{}{Casino entrance}
{149000}{}{Casino entrance}
{149100}{}{Casino door}
{149200}{}{Casino door}
{149300}{}{Wall light}
{149400}{}{Wall light}
{149500}{}{Wall light}
{149600}{}{Wall light}
{149700}{}{Wall light}
{149800}{}{Wall}
{149900}{}{Wall}
{150000}{}{Fan}
{150100}{}{Fan}
{150200}{}{Fire Ext.}
{150300}{}{Fire Ext.}
{150400}{}{Pipe}
{150500}{}{Power distributor}
{150600}{}{Power distributor}
{150700}{}{Wall}
{150800}{}{Wall}
{150900}{}{Wall}
{151000}{}{Wall}
{151100}{}{Wall}
{151200}{}{Wall}
{151300}{}{Wall}
{151400}{}{Wall}
{151500}{}{Wall}
{151600}{}{Wood paneling}
{151700}{}{Wood paneling}
{151800}{}{Pipe}
{151900}{}{Pipe}
{152000}{}{Pipe}
{152100}{}{Pipe}
{152200}{}{Pipe}
{152300}{}{Pipe}
{152400}{}{Pipe}
{152500}{}{Pipe}
{152600}{}{Pipe}
{152700}{}{Pipe}
{152800}{}{Pipe}
{152900}{}{Air Vent}
{153000}{}{Air Vent}
{153100}{}{Door}
{153200}{}{Door}
{153300}{}{Door}
{153400}{}{Door}
{153500}{}{Door}
{153600}{}{Door}
{153700}{}{Shower}
{153800}{}{Platform}
{153900}{}{Platform}
{154000}{}{Large tank}
{154100}{}{Tanks}
{154200}{}{Boxes}
{154300}{}{Radar installation}
{154400}{}{Radar installation}
{154500}{}{Antenna}
{154600}{}{Antenna}
{154700}{}{Shadow}
{154800}{}{Forcefield}
{154900}{}{Forcefield}
{155000}{}{Toilet}
{155100}{}{Advertising sign}
{155200}{}{Advertising sign}
{155300}{}{Advertising sign}
{155400}{}{Advertising sign}
{155500}{}{Advertising sign}
{155600}{}{Advertising sign}
{155700}{}{Advertising sign}
{155800}{}{Advertising sign}
{155900}{}{Advertising sign}
{156000}{}{Advertising sign}
{156001}{}{Sign "Welcome to the incredible city of Las Vegas".}
{156100}{}{Advertising sign}
{156101}{}{Sign "Welcome to the incredible city of Las Vegas".}
{156200}{}{Advertising sign}
{156201}{}{Sign "Welcome to the incredible city of Las Vegas".}
{156300}{}{City fence}
{156400}{}{City fence}
{156500}{}{City fence}
{156600}{}{Shadow}
{156700}{}{Shadow}
{156800}{}{Shadow}
{156900}{}{Shadow}
{157000}{}{Antenna}
{157100}{}{Shadow}
{157200}{}{Collapsed signboard}
{157300}{}{Block}
{157400}{}{Extractor hood}
{157500}{}{Armored door}
{157501}{}{Armored door, opens with a special key card.}
{157600}{}{Door}
{157601}{}{Skillfully made wooden door in excellent condition.}
{157700}{}{Air Vent}
{157800}{}{Auto-doc}
{157801}{}{This Auto-doc is designed to heal illnesses and administer various drugs.}
{157900}{}{Broken turret}
{157901}{}{This turret does not function.}
{158000}{}{Pile of rocks}
{158100}{}{Forcefield}
{158101}{}{An energy field is blocking your path.}
{158200}{}{Forcefield}
{158201}{}{An energy field is blocking your path.}
{158300}{}{Forcefield}
{158301}{}{An energy field is blocking your path.}
{158400}{}{Forcefield}
{158401}{}{An energy field is blocking your path.}
{158500}{}{Shadow}
{158600}{}{Shadow}
{158700}{}{Shadow}
{158800}{}{Shadow}
{158900}{}{Shadow}
{159000}{}{Shadow}
{159100}{}{Shadow}
{159200}{}{Shadow}
{159300}{}{The base of the radio tower}
{159400}{}{The base of the radio tower}
{159500}{}{Collapse}
{159600}{}{Collapse}
{159700}{}{Hotel architecture}
{159800}{}{Arcade machine}
{159801}{}{Modern Slot machine with computer stuffing. Serves to run arcade game.}
{159900}{}{Arcade machine}
{159901}{}{Modern Slot machine with computer stuffing. Serves to run arcade game.}
{160000}{}{Wall}
{160100}{}{Wall}
{160200}{}{Floor pit}
{160300}{}{Stone Bench}
{160400}{}{Stone Bench}
{160500}{}{Barrel in the sand}
{160600}{}{Gas chamber}
{160601}{}{Installation for gas cylinders.}
{160700}{}{Shadow}
{160800}{}{Shadow}
{160900}{}{Shadow}
{161000}{}{Shadow}
{161100}{}{Shadow}
{161200}{}{Shadow}
{161300}{}{Shadow}
{161400}{}{Beam}
{161500}{}{Shadow}
{161600}{}{Shadow}
{161700}{}{Shadow}
{161800}{}{Shadow}
{161900}{}{Shadow}
{162000}{}{Shelf with figures}
{162001}{}{You see a rack, occupied by a lot of plaster figures and heads.}
{162100}{}{Fuel tank}
{162101}{}{Tank with fuel for transport. And it's definitely not empty.}
{162200}{}{Track}
{162300}{}{Track}
{162400}{}{Track}
{162500}{}{Storage tank}
{162501}{}{A tank filled with biogel, in which a mutated jelly-like body floats.}
{162600}{}{Storage tank}
{162601}{}{A tank filled with biogel, in which a mutated jelly-like body floats.}
{162700}{}{Papers on the table}
{162800}{}{Disassembled robot}
{162900}{}{Mine cart}
{163000}{}{Wall}
{163100}{}{Wall}
{163200}{}{Wall}
{163300}{}{Wall}
{163400}{}{Wall}
{163500}{}{Wall}
{163600}{}{Wall}
{163700}{}{Flag}
{163800}{}{Wall}
{163900}{}{Wall}
{164000}{}{Wall}
{164100}{}{Wall}
{164200}{}{Exhaust port}
{164300}{}{Desk}
{164400}{}{Desk}
{164500}{}{Stairs down}
{164600}{}{Stairs up}
{164700}{}{Tanker}
{164800}{}{Tanker}
{164900}{}{Tanker}
{165000}{}{Tanker}
{165100}{}{Tanker}
{165200}{}{Tanker}
{165300}{}{Tanker}
{165400}{}{Tanker}
{165500}{}{Tanker}
{165600}{}{Tanker}
{165700}{}{Tanker}
{165800}{}{Nightshade bush}
{165900}{}{Vending machine}
{166000}{}{Tanker}
{166100}{}{Tanker}
{166200}{}{Warning sign}
{166201}{}{"Stop! Restricted area!"}
{166300}{}{Hangman}
{166400}{}{Hangman}
{166500}{}{Large boxes}
{166501}{}{A stack of boxes, folded in "ladder". You can climb to the very top.}
{166600}{}{High-tech device}
{166700}{}{Piano}
{166701}{}{A beautiful piano with gold ornaments.}
{166800}{}{Warning sign}
{166801}{}{"Stop! Clozed zone!"}
{166900}{}{Warning sign}
{166901}{}{"Stop! Clozed zone!"}
{167000}{}{Promotional poster}
{167100}{}{Promotional poster}
{167200}{}{Promotional poster}
{167300}{}{Tanker}
{167400}{}{Tanker}
{167500}{}{Signboard of the factory}
{167600}{}{Signboard of the factory}
{167700}{}{Propaganda poster}
{167800}{}{Propaganda poster}
{167900}{}{Propaganda poster}
{168000}{}{Propaganda poster}
{168100}{}{Painting}
{168200}{}{Tanker}
{168300}{}{Poster}
{168400}{}{Robot-flyer}
{168500}{}{Mine elevator}
{168600}{}{Mine elevator}
{168700}{}{Clothing synthesizer}
{168701}{}{Ruined clothing synthesizer from the company Vault-Tec. Although some internal parts seems intact, it is hardly possible to restore it to working condition.}
{168800}{}{Vertibird}
{168900}{}{Vertibird}
{169000}{}{Vertibird}
{169100}{}{Vertibird}
{169200}{}{Vertibird}
{169300}{}{Shadow}
{169400}{}{Shadow}
{169500}{}{Shadow}
{169600}{}{Shadow}
{169700}{}{Tanker}
{169800}{}{Tanker}
{169900}{}{Tanker}
{170000}{}{Tanker}
{170100}{}{Tanker}
{170200}{}{Tanker}
{170300}{}{Tanker}
{170400}{}{Tanker}
{170500}{}{Tanker}
{170600}{}{Tanker}
{170700}{}{Tanker}
{170800}{}{Tanker}
{170900}{}{Door}
{171000}{}{Door}
{171100}{}{Wall}
{171200}{}{Wall}
{171300}{}{Wall}
{171400}{}{Wall}
{171500}{}{Wall}
{171600}{}{Wall}
{171700}{}{Wall}
{171800}{}{Wall}
{171900}{}{Air Vent}
{172000}{}{Air Vent}
{172100}{}{Bulletproof Glass}
{172200}{}{Bulletproof Glass}
{172300}{}{Bulletproof Glass}
{172400}{}{Heavy Laser Turret}
{172500}{}{Heavy Laser Turret}
{172600}{}{Rocks}
{172700}{}{Rocks}
{172800}{}{Rocks}
{172900}{}{Rocks}
{173000}{}{Rocks}
{173100}{}{Rocks}
{173200}{}{Rocks}
{173300}{}{Rocks}
{173400}{}{Rocks}
{173500}{}{Rocks}
{173600}{}{Rocks}
{173700}{}{Road map}
{173800}{}{Poster}
{173900}{}{Warning}
{173901}{}{A warning sign announcing the prohibition of open arms carrying in the territory of the Clean City.}
{174000}{}{Curtain}
{174100}{}{Curtain}
{174200}{}{Wall}
{174300}{}{Grafitti}
{174400}{}{Barricaded door}
{174401}{}{Door with transverse metal inserts that do not allow it to open and even knock over.}
{174500}{}{Jukebox}
{174501}{}{Old jukebox.}
{174600}{}{Fan}
{174700}{}{Fan}
{174800}{}{Manhole}
{174900}{}{Exit sign}
{175000}{}{Lamp}
{175100}{}{Lamp}
{175200}{}{Out of Order Sign}
{175300}{}{Hole in the ground}
{175301}{}{Deep hole in the ground. Below, through the darkness, you can barely see the metal floor.}
{175400}{}{Train doors}
{175500}{}{Head in the tank}
{175600}{}{Cliff}
{175700}{}{Bridge over the canyon}
{175800}{}{Bridge over the canyon}
{175900}{}{Bridge over the canyon}
{176000}{}{Bridge over the canyon}
{176100}{}{Cliff}
{176200}{}{Cliff}
{176300}{}{Cliff}
{176400}{}{Train}
{176500}{}{Train}
{176600}{}{Train}
{176700}{}{Cliff}
{176800}{}{Shadow}
{176900}{}{Bridge over the canyon}
{177000}{}{Entrance}
{177100}{}{Entrance}
{177200}{}{Entrance}
{177300}{}{Entrance}
{177400}{}{Sewerage pipes}
{177500}{}{Sewerage pipes}
{177600}{}{Ravine}
{177700}{}{Gilmore's corpse}
{177701}{}{Justice is done. It's a former criminal Gary Mark Gilmore from Provo. May he burn in hell!}
{177800}{}{Table}
{177900}{}{Old windmill}
{177901}{}{This is the outer part of the wind farm, it is made out of different junk. We can only tap on the shoulder the one who did it.}
{178000}{}{Shadow}
{178100}{}{Shadow}
{178200}{}{Shadow}
{178300}{}{Shadow}
{178400}{}{Shadow}
{178500}{}{Bridge over the ravine}
{178600}{}{Roof}
{178700}{}{Roof}
{178800}{}{Roof}
{178900}{}{Shadow}
{179000}{}{Tower}
{179100}{}{Tower}
{179200}{}{Tower}
{179300}{}{Fountain}
{179400}{}{Fountain}
{179500}{}{Fountain}
{179600}{}{Fountain}
{179700}{}{Fountain}
{179800}{}{Fountain}
{179900}{}{Fountain}
{180000}{}{Fountain}
{180100}{}{Window}
{180200}{}{Wreckage}
{180300}{}{Rocks}
{180400}{}{Rocks}
{180500}{}{Rocks}
{180600}{}{Rocks}
{180700}{}{Poster}
{180800}{}{Poster}
{180900}{}{"Mines!"}
{180901}{}{The sign warns of the danger of mines.}
{181000}{}{"Mines!"}
{181001}{}{The sign warns of the danger of mines.}
{181100}{}{Advertising sign}
{181200}{}{Advertising sign}
{181300}{}{Table}
{181400}{}{Coffin}
{181500}{}{Statue of a warrior}
{181501}{}{A statue depicting a muscular warrior in a beret with grenades on the belt, which tries to escape from the captivity of his chains.}
{181600}{}{Nameplate}
{181700}{}{Table}
{181800}{}{Wooden door}
{181900}{}{Wooden door}
{182000}{}{Refrigerator for drinks}
{182100}{}{Refrigerator for drinks}
{182200}{}{Stove}
{182300}{}{Stove}
{182400}{}{Stove}
{182500}{}{Stove}
{182600}{}{Stuff}
{182700}{}{Stuff}
{182800}{}{Stuff}
{182900}{}{Stuff}
{183000}{}{Stuff}
{183100}{}{Stuff}
{183200}{}{Stuff}
{183300}{}{Stuff}
{183400}{}{President's chair}
{183500}{}{Stairs}
{183600}{}{World map}
{183700}{}{Situation map}
{183800}{}{Ladder}
{183900}{}{Council room table}
{184000}{}{Council room table}
{184100}{}{Support}
{184200}{}{Tree}
{184300}{}{Tree}
{184400}{}{Watch tower}
{184500}{}{Seat}
{184501}{}{Stinky old chair, which was once an automobile seat. Springs have lost their spring.}
{184600}{}{Hangman}
{184700}{}{Conveyor}
{184800}{}{Conveyor}
{184900}{}{Trough}
{185000}{}{Dilapidated boards}
{185001}{}{A section of the wall consisting of old boards. It can be easily disassembled with tools and brute force.}
{185100}{}{Steam}
{185200}{}{Shadow}
{185300}{}{Shadow}
{185400}{}{Shadow}
{185500}{}{Shadow}
{185600}{}{Shadow}
{185700}{}{Shadow}
{185800}{}{Shadow}
{185900}{}{Hole in the ground}
{185901}{}{You see a hole in the ground. The rope is securely attached to the stones.}
{186000}{}{Coffin}
{186100}{}{Sign}
{186101}{}{"The Atomic cafe"}
{186200}{}{Graffiti}
{186300}{}{Graffiti}
{186400}{}{Graffiti}
{186500}{}{Graffiti}
{186600}{}{Graffiti}
{186700}{}{Graffiti}
{186800}{}{Manhole}
{186900}{}{Manhole}
{187000}{}{Old tires}
{187100}{}{Old tires}
{187200}{}{Old tires}
{187300}{}{Old tires}
{187400}{}{Old tires}
{187500}{}{Old tires}
{187600}{}{Old tires}
{187700}{}{Old tires}
{187800}{}{Old tires}
{187900}{}{Photo of an artist}
{188000}{}{Photo of an artist}
{188100}{}{Photo of an artist}
{188200}{}{Transformer}
{188201}{}{Street distribution transformer.}
{188300}{}{Panel}
{188301}{}{Electrical panel with a counter. Serves to supply electricity to the house.}
{188400}{}{Antenna}
{188500}{}{Antenna}
{188600}{}{Antenna}
{188700}{}{Antenna}
{188800}{}{Antenna}
{188900}{}{Metal wire rope}
{189000}{}{Metal wire rope}
{189100}{}{Campfire}
{189200}{}{Laboratory table}
{189300}{}{Workbench}
{189400}{}{Rat-trap}
{189401}{}{There is a rusty trap in front of you. Activated and very dangerous.}
{189500}{}{Lights}
{189600}{}{Human bones}
{189601}{}{A bunch of old gnawed bones, definitely human. On some you can see traces of fractions.}
{189700}{}{Human bones}
{189701}{}{A bunch of old gnawed bones, definitely human. On some you can see traces of fractions.}
{189800}{}{The hood of the van}
{189900}{}{Flag of hope}
{189901}{}{It seems that this flag is made by a child. Very cute.}
{190000}{}{Children's swing}
{190100}{}{Crane for swing}
{190200}{}{Shadow}
{190300}{}{Shadow}
{190400}{}{Shadow}
{190500}{}{Shadow}
{190600}{}{Loose plank}
{190601}{}{You see nothing out of the ordinary. Except that the planks are nailed little askew.}
{190700}{}{Brahmin remains}
{190701}{}{Partially decomposed remains of a brahmin - left head, right head, a little bit of everything. The most delicious parts, apparently, have been eaten long time ago.}
{190800}{}{Hole in the ground}
{190801}{}{Just a hole, which you crawled out from.}
{190900}{}{Note to Milo}
{190901}{}{This letter is addressed to Milo and to those who will meet him.}
{191000}{}{Strange bus}
{191001}{}{This unusual, acid-colored bus looks like it has been specifically left to rest here for the eternity.}
{191100}{}{Egg}
{191101}{}{This heavy egg is stuck in the hole and now will not move anywhere.}
{191200}{}{Dam wall}
{191300}{}{Dam wall}
{191400}{}{Dam wall}
{191500}{}{Dam wall}
{191600}{}{Dam wall}
{191700}{}{Dam wall}
{191800}{}{Dam wall}
{191900}{}{Dam wall}
{192000}{}{Dam wall}
{192100}{}{Dam wall}
{192200}{}{Dam wall}
{192300}{}{Dam wall}
{192400}{}{Dam wall}
{192500}{}{Dam wall}
{192600}{}{Dam wall}
{192700}{}{Dam wall}
{192800}{}{Dam wall}
{192900}{}{Dam wall}
{193000}{}{Dam wall}
{193100}{}{Dam wall}
{193200}{}{Dam wall}
{193300}{}{Dam wall}
{193400}{}{Dam wall}
{193500}{}{Dam wall}
{193600}{}{Dam wall}
{193700}{}{Dam wall}
{193800}{}{Dam wall}
{193900}{}{Dam wall}
{194000}{}{Mountain}
{194100}{}{Mountain}
{194200}{}{Mountain}
{194300}{}{Mountain}
{194400}{}{Two at the table}
{194500}{}{Two at the table}
{194600}{}{Silver screen}
{194601}{}{This advertising Billboard is covered with old sheets and used as the screen of the cinema.}
{194700}{}{Silver screen}
{194701}{}{This advertising Billboard is covered with old sheets and used as the screen of the cinema.}
{194800}{}{Ladder}
{194801}{}{This stair is barricaded so that no one can go to the top floor. However, you have no reasons to.}
{194900}{}{Sign of "Aromas of Marin" ranch}
{195000}{}{Brahmin water supply}
{195001}{}{Here must be drawn water for the brahmin in the pen.}
{195100}{}{Fuel barrel}
{195101}{}{The one who left it there runs the risk of setting a fire.}
{195200}{}{Burned boxes}
{195300}{}{Burned boxes}
{195400}{}{Burned box}
{195500}{}{Burned box}
{195600}{}{Burned box}
{195700}{}{Control panel}
{195701}{}{It's the node of control and synchronization of vault systems. The developer of the device, as usual, was the great Vault-Tec company.}
{195800}{}{Control panel}
{195801}{}{A panel for indoor climate control from the Vault-Tec company. Nothing special. Besides, it's broken.}
{195900}{}{Wall}
{196000}{}{Crack}
{196100}{}{Crack}
{196200}{}{Crack}
{196300}{}{Crack}
{196400}{}{Crack}
{196500}{}{Crack}
{196600}{}{Crack}
{196700}{}{Crack}
{196800}{}{Crack}
{196900}{}{Crack}
{197000}{}{Charred human bones}
{197100}{}{Charred human bones}
{197200}{}{Charred human bones}
{197300}{}{Charred human bones}
{197400}{}{Charred human bones}
{197500}{}{Small generator}
{197501}{}{The standard model of small electric generator made by Watts Electronics.}
{197600}{}{Police barricade}
{197700}{}{Police barricade}
{197800}{}{Police barricade}
{197900}{}{Police barricade}
{198000}{}{Poster}
{198001}{}{This is a vivid propaganda poster.}
{198100}{}{Poster}
{198101}{}{This is a vivid propaganda poster.}
{198200}{}{Riot shields}
{198300}{}{Riot shields}
{198400}{}{Riot shield}
{198500}{}{Riot shield}
{198600}{}{Faded picture}
{198601}{}{The image of a singer. Obviously, a very old picture in felt frame that is still well preserved.}
{198700}{}{Scrap dump}
{198701}{}{Broken appliances and other debris. If you dig through, it is still possible to get something useful.}
{198800}{}{Scrap dump}
{198801}{}{Broken appliances and other debris. If you dig through, it is still possible to get something useful.}
{198900}{}{Thermonuclear bomb}
{199000}{}{Thermonuclear bomb}
{199100}{}{Thermonuclear bomb}
{199200}{}{Thermonuclear bomb}
{199300}{}{Hole}
{199301}{}{Obviously, a hole dug by animals. Hardly you'll fit inside.}
{199400}{}{Promotional poster}
{199401}{}{In this poster one can still see the inscription: "Preiser Incorporated. Protect your family before the bombs start falling!"}
{199500}{}{Promotional poster}
{199501}{}{In this poster one can still see the inscription: "Preiser Incorporated. Protect your family before the bombs start falling!"}
{199600}{}{Promotional poster}
{199601}{}{In this poster one can still see the inscription: "Preiser Incorporated. Protect your family before the bombs start falling!"}
{199700}{}{Bike}
{199701}{}{This motorcycle has completely rusted.}
{199800}{}{Tent}
{199900}{}{Hanged man}
{199901}{}{You can hardly call it something ordinary.}
{200000}{}{Tree}
{200100}{}{Mountain}
{200101}{}{These mountain walls look very unapproachable.}
{200200}{}{Mountain}
{200201}{}{These mountain walls look very unapproachable.}
{200300}{}{Mountain}
{200301}{}{These mountain walls look very unapproachable.}
{200400}{}{Mountain}
{200401}{}{These mountain walls look very unapproachable.}
{200500}{}{Mountain}
{200501}{}{These mountain walls look very unapproachable.}
{200600}{}{Equipment}
{200601}{}{This equipment is marked with company logo of Vault-Tec.}
{200700}{}{Ladder}
{200701}{}{Old, somewhat rickety ladder.}
{200800}{}{Ladder}
{200900}{}{Intermittent spring}
{200901}{}{This spring almost dried up, but it is still possible to get some water.}
{201000}{}{Collapse}
{201001}{}{This terrible rock slide claimed the life of a local hunter.}
{201100}{}{Table}
{201101}{}{This table is polluted with crude organs. You can't figure out if they are of human or not.}
{201200}{}{Manhole}
{201201}{}{Durable metal hatch.}
{201300}{}{Manhole}
{201301}{}{Durable metal hatch.}
{201400}{}{Broc flowers}
{201500}{}{Xander roots}
{201600}{}{Vocas plant}
{201700}{}{Damaged generator}
{201701}{}{Power generator made by Watts Electronics. This particular generator is fried and can not be repaired.}
{201800}{}{Radar equipment}
{201900}{}{Desk}
{201901}{}{The usual office desk.}
{202000}{}{Desk}
{202001}{}{The usual office desk.}
{202100}{}{Desk}
{202101}{}{The usual office desk.}
{202200}{}{Desk}
{202201}{}{The usual office desk.}
