{100}{}{Hero Male}
{101}{}{}
{200}{}{Hero Female}
{201}{}{}
{300}{}{Vault 8 citizen}
{400}{}{Vault 8 citizen}
{500}{}{Radscorpion}
{501}{}{A small mutated scorpion.}
{600}{}{Radscorpion}
{601}{}{A mutated scorpion.}
{700}{}{Deathclaw}
{701}{}{An immature Deathclaw.}
{800}{}{Deathclaw}
{801}{}{An immature Deathclaw.}
{900}{}{Dog}
{901}{}{A canine, probably of a mixed breed.}
{1000}{}{Brahmin}
{1001}{}{A two headed, mutant cow.}
{1100}{}{Rat}
{1101}{}{A typical large rat.}
{1200}{}{Mantis}
{1201}{}{A mutated Mantis.}
{1300}{}{Sergeant Graves}
{1400}{}{Doc}
{1500}{}{Richard Moro}
{1600}{}{Spore Plant}
{1601}{}{A carnivorous plant.}
{1700}{}{Cute slave}
{1800}{}{Handsome slave}
{1900}{}{Healthy slave}
{2000}{}{Healthy slave}
{2100}{}{Strong slave}
{2200}{}{Strong slave}
{2300}{}{Combat slave}
{2400}{}{Combat slave}
{2500}{}{Clever slave}
{2600}{}{Clever slave}
{2700}{}{Generic slave}
{2800}{}{Generic slave}
{2900}{}{Anna}
{3000}{}{Tough thug}
{3100}{}{Tough thug}
{3200}{}{Melee thug}
{3300}{}{Melee thug}
{3400}{}{Agile thug}
{3500}{}{Agile thug}
{3600}{}{Gun thug}
{3700}{}{Gun thug}
{3800}{}{Big gun thug}
{3900}{}{Big gun thug}
{4000}{}{Tough guard}
{4100}{}{Tough guard}
{4200}{}{Melee guard}
{4300}{}{Melee guard}
{4400}{}{Agile guard}
{4500}{}{Agile guard}
{4600}{}{Gun guard}
{4700}{}{Gun guard}
{4800}{}{Big gun guard}
{4900}{}{Big gun guard}
{5000}{}{Orphan (Male)}
{5100}{}{Orphan (Female)}
{5200}{}{Child (Male)}
{5300}{}{Child (Female)}
{5400}{}{Loser}
{5500}{}{Loser}
{5600}{}{Bad merchant}
{5700}{}{Bad merchant}
{5800}{}{Average merchant}
{5900}{}{Average merchant}
{6000}{}{Master trader}
{6100}{}{Master trader}
{6200}{}{Someone}
{6300}{}{Weak peasant}
{6400}{}{Weak peasant}
{6500}{}{Average peasant}
{6600}{}{Average peasant}
{6700}{}{Strong peasant}
{6800}{}{Strong peasant}
{6900}{}{Escaped convict}
{7000}{}{Weak melee guard}
{7100}{}{Weak Gun guard}
{7200}{}{Weak Gun guard}
{7300}{}{Repair Bot}
{7400}{}{Repair Bot Mark II}
{7500}{}{Robobrain}
{7600}{}{Floating Eye Bot}
{7700}{}{Sentry Bot}
{7800}{}{Sentry Bot Mark II}
{7900}{}{Robobrain}
{8000}{}{Little Gecko}
{8100}{}{Tough Lil Gecko}
{8200}{}{Wild Dog}
{8201}{}{A mixed breed feral dog.}
{8300}{}{Golden Gecko}
{8400}{}{Deathclaw}
{8500}{}{Deathclaw Spawn}
{8600}{}{Tough Golden Gecko}
{8700}{}{Usual target}
{8800}{}{Armored target}
{8900}{}{John Cassidy}
{9000}{}{Usual guy}
{9100}{}{Sergeant}
{9200}{}{Citizen}
{9300}{}{Mom}
{9400}{}{Upper-class citizen}
{9500}{}{Trapper}
{9600}{}{Trapper}
{9700}{}{Sulik}
{9800}{}{Redneck}
{9900}{}{Redneck}
{10000}{}{Redneck}
{10100}{}{Glowing Ghoul}
{10200}{}{Reactor Ghoul}
{10300}{}{Reactor guard}
{10400}{}{Eli}
{10500}{}{Dump native}
{10600}{}{The Brain}
{10700}{}{Freak}
{10800}{}{Harrelson}
{10900}{}{Jay Kukish}
{11000}{}{Mole Rat}
{11100}{}{Greater Mole Rat}
{11200}{}{Pig Rat}
{11300}{}{Tough Pig Rat}
{11400}{}{Weak Brahmin}
{11401}{}{A two-headed, mutant animal.}
{11500}{}{A.Pwr.Armor (don't use)}
{11600}{}{Mutated Rat}
{11601}{}{A tough mutant rat.}
{11700}{}{Mutated molerat}
{11701}{}{A tough mutant mole rat.}
{11800}{}{Mutated pigrat}
{11801}{}{A tough mutant pig rat.}
{11900}{}{Mercenary}
{12000}{}{Mercenary}
{12100}{}{Captain of mercenaries}
{12200}{}{Hero Andro (don't use)}
{12300}{}{Hero Andro (don't use)}
{12400}{}{Hero Male (don't use)}
{12500}{}{Hero Female (don't use)}
{12600}{}{Hero Male (don't use)}
{12700}{}{Hero Female (don't use)}
{12800}{}{Hero Male (don't use)}
{12900}{}{Hero Female (don't use)}
{13000}{}{Hero Male (don't use)}
{13100}{}{Hero Female (don't use)}
{13200}{}{Hero Male (don't use)}
{13300}{}{Hero Female (don't use)}
{13400}{}{Vault City guard}
{13500}{}{Vault City guard}
{13600}{}{Cyberdog}
{13700}{}{Police officer}
{13800}{}{Police officer}
{13900}{}{Trainer}
{14000}{}{Slaver guard}
{14100}{}{Fatso Jackson}
{14200}{}{Grandmaster Trader}
{14300}{}{Grandmaster Trader}
{14400}{}{Tamed Deathclaw}
{14500}{}{Tribe Chief}
{14600}{}{Roboeye-protector}
{14700}{}{Hunter of Coyotes}
{14800}{}{Respectable citizen}
{14900}{}{Henchman of the Bloom brothers}
{15000}{}{Shorty}
{15100}{}{One of the Bloom brothers}
{15200}{}{Goris}
{15300}{}{Mercenary}
{15400}{}{Mercenary}
{15500}{}{Captain of mercenaries}
{15600}{}{Mercenary}
{15700}{}{Mercenary}
{15800}{}{Captain of mercenaries}
{15900}{}{Generic Ghoul}
{16000}{}{Myron}
{16100}{}{Marcus}
{16200}{}{Doctor}
{16300}{}{Davin}
{16400}{}{Miria}
{16500}{}{Boy}
{16600}{}{Mechanic}
{16700}{}{Handyman}
{16800}{}{Handyman}
{16900}{}{Handyman}
{17000}{}{Bouncer}
{17100}{}{Big Louie}
{17200}{}{Mr. Handy}
{17300}{}{Hardy}
{17400}{}{Nick Hauer}
{17500}{}{Hardy's guard}
{17600}{}{Burton Hickok}
{17700}{}{test (don't use)}
{17800}{}{Reactor Ghoul}
{17900}{}{Generic Ghoul}
{18000}{}{Mike}
{18100}{}{Riley}
{18200}{}{Bounty Hunter (1-6)}
{18300}{}{B. Hunter Lead (7-12)}
{18400}{}{Private}
{18500}{}{guard}
{18600}{}{B. Hunter Lead (13-18)}
{18700}{}{guard}
{18800}{}{Bounty Hunter (13-18)}
{18900}{}{B. Hunter Lead (19-?)}
{19000}{}{Bounty Hunter (19-?)}
{19100}{}{Bess}
{19101}{}{A two headed, mutant animal.}
{19200}{}{Man in the mantle}
{19300}{}{Niskigvan the Ruffled Feathers}
{19400}{}{Phil}
{19500}{}{"Super 8"}
{19600}{}{Lousy rogue}
{19700}{}{Child}
{19800}{}{Ogima the Black Cloud}
{19900}{}{Cheyenne}
{20000}{}{Makozid the Bear’s Paw}
{20100}{}{Suspicious type}
{20200}{}{Primitive Hunter}
{20300}{}{Primitive Hunter}
{20400}{}{Punk}
{20500}{}{Punk}
{20600}{}{Punk}
{20700}{}{Holy Woman}
{20800}{}{Nomad- Low}
{20900}{}{Nomad- Med}
{21000}{}{Nomad- Low}
{21100}{}{Nomad- Med}
{21200}{}{Bandit}
{21300}{}{Bandit}
{21400}{}{Farmer}
{21500}{}{Farmer}
{21600}{}{Mantis}
{21700}{}{Slaver}
{21800}{}{Slaver}
{21900}{}{Wild Brahmin}
{22000}{}{Villager}
{22100}{}{Villager}
{22200}{}{Patrol}
{22300}{}{Patrol}
{22400}{}{Strong slaver}
{22500}{}{Strong slaver}
{22600}{}{Psycho}
{22700}{}{Scavenger}
{22800}{}{Glowing psycho}
{22900}{}{Glowing scavenger}
{23000}{}{Raider}
{23100}{}{Raider}
{23200}{}{Savage}
{23300}{}{Savage}
{23400}{}{Smuggler}
{23500}{}{Smuggler}
{23600}{}{Prospector}
{23700}{}{Prospector}
{23800}{}{Raider}
{23900}{}{Raider}
{24000}{}{Acid Gecko}
{24100}{}{Tough Acid Gecko}
{24200}{}{Alien}
{24300}{}{Tough Alien}
{24400}{}{Tough Lil Deathclaw}
{24500}{}{Tough Deathclaw}
{24600}{}{Floater}
{24700}{}{Nasty Floater}
{24800}{}{Tarantula}
{24900}{}{Mean Centaur}
{25000}{}{General Wesker}
{25100}{}{Generator}
{25200}{}{Racketeer}
{25300}{}{Racketeer}
{25400}{}{Mercenary}
{25500}{}{Mercenary}
{25600}{}{Nightkin}
{25700}{}{Tough Nightkin}
{25800}{}{Tough Ghoul}
{25900}{}{Mobster}
{26000}{}{Robber}
{26100}{}{Police officer}
{26200}{}{Police officer}
{26300}{}{Marauder}
{26400}{}{Marauder}
{26500}{}{Administrator}
{26600}{}{Vorpal rat}
{26700}{}{Ted Bundy}
{26800}{}{Biker}
{26900}{}{Overseer}
{27000}{}{Mysterious Stranger}
{27100}{}{Mysterious Stranger}
{27200}{}{Terry Deveraux}
{27300}{}{Impudent miner}
{27400}{}{Bodyguard}
{27500}{}{Mother Deathclaw}
{27600}{}{Kings member}
{27700}{}{Stagecoacher}
{27800}{}{Mormon}
{27900}{}{Mormon}
{28000}{}{Mysterious Stranger}
{28100}{}{Mysterious Stranger}
{28200}{}{Mysterious Stranger}
{28300}{}{Mysterious Stranger}
{28400}{}{Mysterious Stranger}
{28500}{}{Mysterious Stranger}
{28600}{}{Mysterious Stranger}
{28700}{}{Mysterious Stranger}
{28800}{}{Pres. bodyguard}
{28900}{}{Deathclaw Egg}
{29000}{}{Biker Phil}
{29100}{}{Stalker}
{29200}{}{Earth dragon}
{29300}{}{Williamson}
{29400}{}{Tom Parker}
{29500}{}{Engineer}
{29600}{}{Vegas courier}
{29700}{}{Lewis Birch}
{29800}{}{Kid}
{29900}{}{Kid}
{30000}{}{Gun merchant}
{30100}{}{Administrative employee}
{30200}{}{Nelson}
{30300}{}{The farmer}
{30400}{}{The farmer}
{30500}{}{Impudent miner}
{30600}{}{Marilyn}
{30700}{}{Impudent miner}
{30800}{}{Vortis}
{30900}{}{Coyote}
{31000}{}{Sulik - Stage 1}
{31100}{}{Sulik - Stage 2}
{31200}{}{Sulik - Stage 3}
{31300}{}{Sulik - Stage 4}
{31400}{}{Sulik - Stage 5}
{31500}{}{Sulik - Stage 6}
{31600}{}{Lenny - Stage 1}
{31700}{}{Lenny - Stage 2}
{31800}{}{Lenny - Stage 3}
{31900}{}{Goris - Stage 1}
{32000}{}{Goris - Stage 2}
{32100}{}{Goris - Stage 3}
{32200}{}{Goris - Stage 4}
{32300}{}{Goris - Stage 5}
{32400}{}{Goris - Stage 6}
{32500}{}{Myron - Stage 1}
{32600}{}{Myron - Stage 2}
{32700}{}{Myron - Stage 3}
{32800}{}{Myron - Stage 4}
{32900}{}{Marcus - Stage 1}
{33000}{}{Marcus - Stage 2}
{33100}{}{Marcus - Stage 3}
{33200}{}{Marcus - Stage 4}
{33300}{}{Marcus - Stage 5}
{33400}{}{Cyberdog - Stage 1}
{33500}{}{Cyberdog - Stage 2}
{33600}{}{Cyberdog - Stage 3}
{33700}{}{Cyberdog - Stage 4}
{33800}{}{Cassidy - Stage 1}
{33900}{}{Cassidy - Stage 2}
{34000}{}{Cassidy - Stage 3}
{34100}{}{Cassidy - Stage 4}
{34200}{}{Dogmeat}
{34300}{}{Dogmeat - Stage 1}
{34400}{}{Dogmeat - Stage 2}
{34500}{}{Dogmeat - Stage 3}
{34600}{}{Dogmeat - Stage 4}
{34700}{}{Dogmeat - Stage 5}
{34800}{}{Dogmeat - Stage 6}
{34900}{}{Robobrain - Stage 1}
{35000}{}{Robobrain - Stage 2}
{35100}{}{Robobrain - Stage 3}
{35200}{}{Robobrain - Stage 4}
{35300}{}{Robobrain - Stage 5}
{35400}{}{Alien Queen}
{35500}{}{Black radscorpion}
{35600}{}{Black radscorpion}
{35700}{}{Legendary scorpion}
{35800}{}{Ripper}
{35900}{}{Raider}
{36000}{}{Raider}
{36100}{}{Fighter}
{36200}{}{Punk}
{36300}{}{Punk}
{36400}{}{Rancho guard}
{36500}{}{Rancho worker}
{36600}{}{Biker}
{36700}{}{Shorty}
{36800}{}{Guide}
{36900}{}{Convoy guard}
{37000}{}{Convoy guard}
{37100}{}{Ricardo Bertolini}
{37200}{}{Respectable citizen}
{37300}{}{Vic - Stage 1}
{37400}{}{Vic - Stage 2}
{37500}{}{Vic - Stage 3}
{37600}{}{Vic - Stage 4}
{37700}{}{Vic - Stage 5}
{37800}{}{Vic - Stage 6}
{37900}{}{RoboBrain - Chimp}
{38000}{}{Robobrain - Abnormal}
{38100}{}{Robobrain - Human}
{38200}{}{Giant ant}
{38300}{}{Tough giant ant}
{38400}{}{Pariah dog}
{38500}{}{Weak fighting slave}
{38600}{}{Healthy fighting slave}
{38700}{}{Strong fighting slave}
{38800}{}{Powerful fighting slave}
{38900}{}{Fighting slave-master}
{39000}{}{The weakest fighter of the ring}
{39100}{}{The strongest fighter of the ring}
{39200}{}{Powerful fighter of the ring}
{39300}{}{The master of the ring}
{39400}{}{Fighter-professional}
{39500}{}{The champion of the ring}
{39600}{}{The champion of the ring}
{39700}{}{Quartermaster}
{39800}{}{The champion of the ring}
{39900}{}{The champion of the ring}
{40000}{}{The absolute champion of the ring}
{40100}{}{Mr. Chase}
{40200}{}{Bob Neil}
{40300}{}{Engineer}
{40400}{}{Angry brahmin}
{40500}{}{Trainer}
{40600}{}{Businessman}
{40700}{}{Redneck}
{40800}{}{Bishop}
{40900}{}{Machete}
{41000}{}{Owner}
{41100}{}{Old Jed}
{41200}{}{Gerlach}
{41300}{}{Mrs. Wright}
{41400}{}{Solomon}
{41500}{}{Maxson}
{41600}{}{Maxson}
{41700}{}{Fighter from the slums}
{41800}{}{Madam}
{41900}{}{Madam}
{42000}{}{Mr. Luciano}
{42100}{}{Bodyguard}
{42200}{}{Casino security}
{42300}{}{guard}
{42400}{}{Plant Manager}
{42500}{}{Generic Bartender}
{42600}{}{Generic Bartender}
{42700}{}{Boxer 1}
{42800}{}{Boxer 2}
{42900}{}{Boxer 3}
{43000}{}{Boxer 4}
{43100}{}{Mike the Masticator}
{43200}{}{Holyfeld}
{43300}{}{McKneely}
{43400}{}{Ringleader of the ring}
{43500}{}{Thompson}
{43600}{}{Colonel Night}
{43700}{}{Reaper of Souls}
{43800}{}{Casino Bouncer}
{43900}{}{Casino Bouncer}
{44000}{}{Casino Girl}
{44100}{}{Drug Dealer}
{44200}{}{Drug Dealer}
{44300}{}{Commander}
{44400}{}{Militia}
{44500}{}{Striker}
{44600}{}{Biker}
{44700}{}{Slut}
{44800}{}{Slut}
{44900}{}{Prospector}
{45000}{}{Apothecary}
{45100}{}{Cook}
{45200}{}{Patrick}
{45300}{}{Cowboy}
{45400}{}{Barton}
{45500}{}{Traveler}
{45600}{}{Traveler}
{45700}{}{Trader 1}
{45800}{}{Trader 2}
{45900}{}{Slaver}
{46000}{}{Slaver}
{46100}{}{Slaver}
{46200}{}{Gilmor}
{46300}{}{Neon Gangster}
{46400}{}{Caravan merchant}
{46500}{}{Soldier 3}
{46600}{}{Soldier 4}
{46700}{}{Reaper of Souls}
{46800}{}{President}
{46900}{}{Bartender}
{47000}{}{Gun turret}
{47001}{}{This is an automated gun turret equipped with a Dual Plasma Cannon.}
{47100}{}{K-9 (base)}
{47200}{}{K-9 (stage 1)}
{47300}{}{K-9 (stage 2)}
{47400}{}{K-9 (stage 3)}
{47500}{}{K-9 (stage 4)}
{47600}{}{Generic markets, cafes and Nightclubs}
{47700}{}{Wanamingo Egg}
{47800}{}{Lo Pan guard}
{47900}{}{Dashing developer}
{48000}{}{Auto-Cannon}
{48100}{}{Gecko Special Critter}
{48200}{}{Grim Reaper}
{48300}{}{President}
{48301}{}{The President's bodyguard}
{48400}{}{Cheyenne's child}
