{100}{}{Leather Armor}
{101}{}{Your basic all leather apparel. Finely crafted from tanned brahmin hide.}
{200}{}{Metal Armor}
{201}{}{Polished metal plates, crudely forming a suit of armor.}
{300}{}{Power Armor}
{301}{}{A self-contained suit of advanced technology armor. Powered by a microfusion reactor, with enough fuel to last a hundred years.}
{400}{}{Knife}
{401}{}{A sharp-bladed cutting and stabbing weapon. Min. ST: 2.}
{500}{}{Club}
{501}{}{Non-lethal melee weapon made out of steel and rubber, was commonly used by law enforcement units. Min. ST: 3.}
{600}{}{Sledgehammer}
{601}{}{A large hammer with big handle. Very popular with the muscular crowd. Min. ST: 6.}
{700}{}{Spear}
{701}{}{A hand-made razor-tipped polearm. The shaft is wooden, and the tip is worked steel. Min. ST: 4.}
{800}{}{10mm Pistol}
{801}{}{A Colt 6520 10mm automatic pistol. Each pull of the trigger will automatically reload the firearm until the magazine is empty. Single shot only, using the powerful 10mm round. Min. ST: 3.}
{900}{}{10mm SMG}
{901}{}{H&K MP9 Submachine gun (10mm caliber). A medium-sized SMG, capable of single shot and burst mode. Min. ST: 4.}
{1000}{}{Hunting Rifle}
{1001}{}{A Colt Rangemaster semi-automatic rifle, in .223 caliber. Single-shot only. Min. ST: 5.}
{1100}{}{Flamer}
{1101}{}{A Flambe-450 model flamethrower, varminter variation. Fires a short spray of extremely hot, flammable liquid. Requires specialized fuel to work properly. Min. ST: 6.}
{1200}{}{Minigun}
{1201}{}{A Rockwell CZ53 Personal Minigun. A multi-barrelled chaingun firing 5mm ammunition at over 60,000 RPM. Min. ST: 7.}
{1300}{}{Rocket Launcher}
{1301}{}{A Rockwell BigBazooka rocket launcher. With the deluxe 3 lb. trigger. Fires AP or Explosive Rockets. Min. ST: 6.}
{1400}{}{Explosive Rocket}
{1401}{}{A rocket with a large explosive warhead.}
{1500}{}{Plasma Rifle}
{1501}{}{A Winchester Model P94 Plasma Rifle. An industrial-grade energy weapon, firing superheated bolts of plasma down a superconducting barrel. Powered by Micro Fusion Cells. Min. ST: 6.}
{1600}{}{Laser Pistol}
{1601}{}{A Wattz 1000 Laser Pistol. Civilian model, so the wattage is lower than military or police versions. Uses small energy cells. Min. ST: 3.}
{1700}{}{Combat Armor}
{1701}{}{High tech armor, made out of advanced defensive polymers.}
{1800}{}{Desert Eagle .44}
{1801}{}{An ancient Desert Eagle pistol, in .44 Magnum. Interest in late 20th century films made this one of the most popular handguns of all times. Min. ST: 5.}
{1900}{}{Rock}
{1901}{}{It's a rock. Looks like Granite. Min. ST: 1.}
{2000}{}{Crowbar}
{2001}{}{A very solid and heavy piece of metal, specifically designed to exert leverage. Or pound heads. Min. ST: 5.}
{2100}{}{Brass Knuckles}
{2101}{}{Hardened knuckle grip that is actually made out of steel. They protect your hand, and do more damage, in unarmed combat. Min. ST: 1.}
{2200}{}{Caravan Carbine}
{2201}{}{An old varmint rifle. The barrel is shortened, and the butt is made as lightweight as possible, which makes the weapon more light and comfortable at the expense of accuracy. Min. ST: 4.}
{2300}{}{Assault Rifle}
{2301}{}{An AK-112 5mm Assault Rifle. An old military model, out of use around the time of the war. Can fire single-shot or burst, using the high velocity 5mm rounds. Min. ST: 5.}
{2400}{}{Plasma Pistol}
{2401}{}{Glock 86 Plasma Pistol. Designed by the Gaston Glock AI. Shoots a small bolt of superheated plasma. Powered by a small energy cell. Min. ST: 4.}
{2500}{}{Grenade (Frag)}
{2501}{}{A generic fragmentation grenade. Contains a small amount of high explosives, the container itself forming most of the damaging fragments. Explodes on contact. Min. ST: 3.}
{2600}{}{Grenade (Plasma)}
{2601}{}{A magnetically sealed plasma delivery unit, with detonating explosives. Creates a blast of superheated plasma on contact. Min. ST: 4.}
{2700}{}{Grenade (Pulse)}
{2701}{}{An electromagnetic pulse grenade, generating an intense magnetic field on detonation. Doesn't affect biological creatures. Contact fuze. Min. ST: 4.}
{2800}{}{Striker}
{2801}{}{A Shotgun-Pistol hybrid, developed by an African engineer. Uses cartridges of 12 caliber, put into a special cylinder. Can be perfectly handled with one hand. Min. ST: 6.}
{2900}{}{10mm JHP}
{2901}{}{Ammunition. Caliber: 10mm, jacketed hollow-points}
{3000}{}{10mm AP}
{3001}{}{Ammunition. Caliber: 10mm, armor piercing.}
{3100}{}{.44 Magnum JHP}
{3101}{}{A brick of ammunition, .44 magnum caliber, hollow-points.}
{3200}{}{Flamethrower Fuel}
{3201}{}{A cylinder containing an extremely flammable liquid fuel for flamethrowers.}
{3300}{}{12 gauge Magnum}
{3301}{}{Type of pre-war production ammunition for shotgun. Equipped with more powerful powder and increased amount of shot than classic cartridges of the same caliber.}
{3400}{}{.223 FMJ}
{3401}{}{A case of ammunition, .223 caliber, Full Metal Jacket.}
{3500}{}{5mm JHP}
{3501}{}{A brick of small, lightweight ammunition. Caliber: 5mm, jacketed hollow-point.}
{3600}{}{5mm AP}
{3601}{}{A brick of small caliber ammunition. 5mm armor piercing.}
{3700}{}{Rocket AP}
{3701}{}{A rocket shell, with a smaller explosive, but designed to pierce armor plating.}
{3800}{}{Small Energy Cell}
{3801}{}{A small, self-contained energy storage unit.}
{3900}{}{Micro Fusion Cell}
{3901}{}{A medium sized energy production unit. Self-contained fusion plant.}
{4000}{}{Stimpak}
{4001}{}{A healing chem. When injected, the chem provides immediate healing of minor wounds.}
{4100}{}{Money}
{4101}{}{Legal tender for the world of the wastes, preserved from pre-war times. For now, Nevada habitants use it in trading, but who knows how long this tradition will last?}
{4200}{}{Fridge}
{4201}{}{A refrigerator. Out of coolant.}
{4300}{}{Ice Chest}
{4301}{}{On old-style ice chest. The hinges are in good working condition.}
{4400}{}{Ice Chest}
{4401}{}{On old-style ice chest. The hinges are in good working condition.}
{4500}{}{Throwing Knife}
{4501}{}{A knife, balanced specifically for throwing. Made of titanium, and laser sharpened. Min. ST: 3.}
{4600}{}{Cheater's Radio}
{4601}{}{This is the radio of Mr. Cheater.}
{4700}{}{First Aid Kit}
{4701}{}{A small kit containing basic medical equipment. Bandages, wraps, antiseptic spray, and more.}
{4800}{}{RadAway}
{4801}{}{A chemical solution that bonds with radiation particles and passes them through your system. Takes time to work.}
{4900}{}{Antidote}
{4901}{}{A bottle containing a home-brewed antidote for poison. A milky liquid with floating pieces of radscorpion flesh.}
{5000}{}{Reserved Item}
{5001}{}{This is a reserved item. DO NOT USE.}
{5100}{}{Dynamite}
{5101}{}{A high explosive, consisting of nitroglycerin mixed with the absorbent substance kiselguhr. Includes a timer.}
{5200}{}{Geiger Counter}
{5201}{}{A Wattz Electronics C-Radz model Geiger Counter. Detects the presence and strength of radiation fields.}
{5300}{}{Ultra-Antidote}
{5301}{}{Package of a powerful antidote. Most likely of military origin.}
{5400}{}{Stealth Boy}
{5401}{}{A RobCo Stealth Boy 3001 personal stealth device. Generates a modulating field that transmits the reflected light from one side of an object to the other.}
{5500}{}{Filter}
{5501}{}{This is a powerful filter for purifying groundwater. Used in some kind of specialized equipment.}
{5600}{}{Anti-smoker}
{5601}{}{Expired a whole century ago, these tablets are used by those who want to quit smoking. The body of the user becomes hyperactive for a short time and the head unusually clears up.}
{5700}{}{---}
{5701}{}{---}
{5800}{}{---}
{5801}{}{---}
{5900}{}{Motion Sensor}
{5901}{}{A Wattz Electronics C-U model motion sensor. Detects the movement of biological material over a distance of meters using a tuned radar device.}
{6000}{}{Bookcase}
{6001}{}{A wooden bookcase.}
{6100}{}{Bookcase}
{6101}{}{A wooden bookcase.}
{6200}{}{Bookcase}
{6201}{}{A wooden bookcase.}
{6300}{}{Bookcase}
{6301}{}{A wooden bookcase.}
{6400}{}{Bookcase}
{6401}{}{A wooden bookcase.}
{6500}{}{Bookcase}
{6501}{}{A wooden bookcase.}
{6600}{}{Desk}
{6601}{}{A wooden desk.}
{6700}{}{Desk}
{6701}{}{A wooden desk.}
{6800}{}{Dresser}
{6801}{}{A wooden dresser.}
{6900}{}{Dresser}
{6901}{}{A wooden dresser.}
{7000}{}{Dresser}
{7001}{}{A wooden dresser.}
{7100}{}{Mutafruit}
{7101}{}{A strange piece of fruit. No preservatives and no additional food coloring added.}
{7200}{}{Bertolini's Case}
{7201}{}{Armored suitcase, covered with leather for solid appearance and locked with a combination lock. There must be untold wealth inside.}
{7300}{}{"A Big Book of Science"}
{7301}{}{A guide to the world of today's scientific wonders.}
{7400}{}{Leather Jacket}
{7401}{}{A black, heavy leather jacket.}
{7500}{}{Tool}
{7501}{}{Classic multi-tool. It is a folding plier with hollow handles, which are hidden away in a number of additional useful tools.}
{7600}{}{Dean's Electronics}
{7601}{}{A study book, in which author consequentially goes from basics of electrical engineering to fundamental principles of building different electrical devices. A note on the cover says that it is for the "budding young electrician in everyone!"}
{7700}{}{Electronic Lockpick}
{7701}{}{A Wattz Electronics Micromanipulator FingerStuff electronic lockpick. For defeating electronic locks and security devices.}
{7800}{}{Fuzzy Painting}
{7801}{}{An image of a singer. Obviously, very old. The image has a felt coating that is still in good condition. Looks like it could be valuable.}
{7900}{}{Flare}
{7901}{}{A flare. Creates light for a short period of time. The paper is a little worn, but otherwise it is in good condition. Twist the top to activate it.}
{8000}{}{First Aid Book}
{8001}{}{A study book on the concepts and practical use of first aid skills.}
{8100}{}{Iguana-on-a-stick}
{8101}{}{A cooked iguana, roasted in its own skin. Tasteless and dense nutrient-poor. In addition, you do not believe that it lived in an ecologically clean environment.}
{8200}{}{Kubotan key}
{8201}{}{Ordinary key, looking nothing significant.}
{8300}{}{Utility room key}
{8301}{}{The key of one of the Quok brothers, to the store room of their shop in Salt Lake City.}
{8400}{}{Lockpicks}
{8401}{}{A set of locksmith tools. Includes all the necessary picks and tension wrenches to open conventional pin and tumbler locks.}
{8500}{}{Plastic Explosives}
{8501}{}{A chunk of Cordex, a military brand of plastic explosives. Highly stable, very destructive. Includes a timer.}
{8600}{}{Scout Handbook}
{8601}{}{A book on the methods and ideals of Scouting. Contains very practical information regarding outdoor life.}
{8700}{}{Buffout}
{8701}{}{Highly advanced steroids. While in effect, they increase strength and reflexes. Very addictive.}
{8800}{}{Watch}
{8801}{}{An expensive watch. Not really working, but it still looks nice.}
{8900}{}{Servomotor}
{8901}{}{Powerful and accurate motor of rotary-step action.}
{9000}{}{Body Care Kit}
{9001}{}{Super-cool set for body care in a branded tin box. It's time to bring it to action!}
{9100}{}{Doctor's Bag}
{9101}{}{This brown bag contains instruments and chems used by doctors for their professional purposes.}
{9200}{}{Scorpion Tail}
{9201}{}{The severed tail of a radscorpion.}
{9300}{}{Bug}
{9301}{}{Ancient device for secret wiretapping.}
{9400}{}{Shotgun}
{9401}{}{A Winchester Widowmaker double-barreled 12-gauge shotgun. Short barrel, with mahogany grip.  Min. ST: 5.}
{9500}{}{12 ga. Shotgun Shells}
{9501}{}{Shotgun ammunition. This particular ammo is marked: "12-gauge shells, not for use by children under the age of 3."}
{9600}{}{Access card}
{9601}{}{A huge access card for a very powerful door.}
{9700}{}{Symbol}
{9701}{}{A piece of polished stone with the symbol of Nevada state. Judging by the pins on the back, the symbol must be inserted somewhere.}
{9800}{}{Junk}
{9801}{}{Pieces of different metals as well as rosins and wires. It is possible that some of this will help with repairs.}
{9900}{}{Gold Locket}
{9901}{}{A valuable gold locket.}
{10000}{}{Radio}
{10001}{}{A camouflage painted model 2043B Radio Communicator, from the fine people at Wattz Electronics. Not operational.}
{10100}{}{Lighter}
{10101}{}{A silver butane lighter. In good condition.}
{10200}{}{"Guns and Bullets"}
{10201}{}{A gun rag. A magazine devoted to the practical use of firearms, and the occasional biased review.}
{10300}{}{Iguana bits}
{10301}{}{Some charred meat and vegetables on a cooking stick. Delicious and nutritious, but youll never know, from what harmful sites can be these iguanas?}
{10400}{}{Birch's Report}
{10401}{}{A lot of encrypted information. The inscription on the label says: "Deliver to the Hub, the Union of Atomic Workers".}
{10500}{}{Ignition key}
{10501}{}{Car ignition key.}
{10600}{}{Nuka-Cola}
{10601}{}{A bottle of Nuka-Cola, the flavored soft-drink of the post-nuclear world. Warm and flat.}
{10700}{}{Wardrobe}
{10701}{}{Wooden wardrobe. In a relatively good condition.}
{10800}{}{Table}
{10801}{}{Wooden table. In a relatively good condition.}
{10900}{}{Rad-X}
{10901}{}{Anti-radiation chems to be taken before exposure. No known side effects.}
{11000}{}{Psycho}
{11001}{}{An unique delivery system filled with strange and unknown chemicals of probably military origin. It is supposed to increase the combat potential of a soldier.}
{11100}{}{.44 magnum FMJ}
{11101}{}{A brick of ammunition, .44 magnum caliber, full metal jacket.}
{11200}{}{Dart}
{11201}{}{Homemade dart that is used to play darts game. Min. ST: 1.}
{11300}{}{---}
{11301}{}{---}
{11400}{}{Pendant}
{11401}{}{Personal named pendant with photo inside.}
{11500}{}{Super Sledge}
{11501}{}{A Super Sledgehammer, manufactured using the finest weapons technology available. Includes a kinetic energy storage device, to increase knockback. Min. ST: 5.}
{11600}{}{Ripper}
{11601}{}{A Ripper(tm) vibroblade. Powered by a small energy cell, the chainblade rips and tears into it's target. Min. ST: 4.}
{11700}{}{Pistol 9mm}
{11701}{}{The pistol is for a 9mm cartridge. In great condition. Ideal accuracy. Min. ST: 2.}
{11800}{}{Laser Rifle}
{11801}{}{A Wattz 2000 Laser Rifle. Uses micro fusion cells for more powerful lasers, and an extended barrel for additional range. Min. ST: 6.}
{11900}{}{Bunker key}
{11901}{}{The key from the gate, leading to the Reno bunker.}
{12000}{}{Pump Shotgun}
{12001}{}{Once a very popular sporting weapon of 12 ga. caliber. Min. ST: 6.}
{12100}{}{9mm ball}
{12101}{}{A collection of ancient 9x19mm rounds. Heavy grease to preserve them from the environment. Standard bullets.}
{12200}{}{9mm pistol}
{12201}{}{A 9mm caliber ammo pistol. Still in working condition, but it could use some minor repairs and cleaning of the mechanisms. Min. ST: 2.}
{12300}{}{Box}
{12301}{}{This box was dug from the ground.}
{12400}{}{Beer}
{12401}{}{Some type of home brewed beer.}
{12500}{}{Booze}
{12501}{}{Homemade alcoholic beverage.}
{12600}{}{Drinking water}
{12601}{}{The life-giving drinking water, purified from dirt and radiation. Used for treatment of diseases, poisoning, first aid and just for drinking.}
{12700}{}{Rope}
{12701}{}{A strong, thick line. About 45 feet in length.}
{12800}{}{Footlocker}
{12801}{}{Your basic footlocker. Holds stuff, sits at foot of bed, can be locked.}
{12900}{}{Footlocker}
{12901}{}{Your basic footlocker. Holds stuff, sits at foot of bed, can be locked.}
{13000}{}{Footlocker}
{13001}{}{Your basic footlocker. Holds stuff, sits at foot of bed, can be locked.}
{13100}{}{Footlocker}
{13101}{}{Your basic footlocker. Holds stuff, sits at foot of bed, can be locked.}
{13200}{}{Locker}
{13201}{}{A storage container.}
{13300}{}{Locker}
{13301}{}{A storage container.}
{13400}{}{Locker}
{13401}{}{A storage container.}
{13500}{}{Locker}
{13501}{}{A storage container.}
{13600}{}{Locker}
{13601}{}{A storage container.}
{13700}{}{Locker}
{13701}{}{A storage container.}
{13800}{}{Locker}
{13801}{}{A storage container.}
{13900}{}{Locker}
{13901}{}{A storage container.}
{14000}{}{---}
{14001}{}{---}
{14100}{}{---}
{14101}{}{---}
{14200}{}{Dynamite stick}
{14201}{}{Small but powerful charge of dynamite with incendiary wick. Have a blast, baby!}
{14300}{}{Sniper Rifle}
{14301}{}{A DKS-501 Sniper Rifle. Excellent long range projectile weapon. Originally .308, this one is chambered in the more common .223 caliber. Min. ST: 5.}
{14400}{}{Super Stimpak}
{14401}{}{An advanced healing chem. Very powerful. Superstims will cause a small amount of damage after a period of time due to powerful nature of the chemicals used.}
{14500}{}{Bookshelf}
{14501}{}{A wooden bookshelf.}
{14600}{}{Bookshelf}
{14601}{}{A wooden bookshelf.}
{14700}{}{Bookshelf}
{14701}{}{A wooden bookshelf.}
{14800}{}{Bookshelf}
{14801}{}{A wooden bookshelf.}
{14900}{}{Bookshelf}
{14901}{}{A wooden bookshelf.}
{15000}{}{Bookshelf}
{15001}{}{A wooden bookshelf.}
{15100}{}{Shelves}
{15101}{}{A set of wooden shelves.}
{15200}{}{Shelves}
{15201}{}{A set of wooden shelves.}
{15300}{}{Shelves}
{15301}{}{A set of wooden shelves.}
{15400}{}{Shelves}
{15401}{}{A set of wooden shelves.}
{15500}{}{Shelves}
{15501}{}{A set of wooden shelves.}
{15600}{}{Shelves}
{15601}{}{A set of wooden shelves.}
{15700}{}{Workbench}
{15701}{}{A workbench. Yep, your standard, old, run-of-the-mill workbench. Looks nice sitting there too.}
{15800}{}{Tool Board}
{15801}{}{This board holds a variety of tools above the popular workbench.}
{15900}{}{Molotov Cocktail}
{15901}{}{A homemade flammable grenade. Min. ST: 3.}
{16000}{}{Cattle Prod}
{16001}{}{A Farmer's Best Friend model cattle prod from Wattz Electronics. Uses small energy cells for power. Min. ST: 4.}
{16100}{}{UD M42}
{16101}{}{The submachine gun, similar in construction to the Thompson's. Equipped with two rounds simultaneously, linked in a "jack" scheme for quick reload. Has not gained popularity, but for some time was actively used by the Office of Strategic Services. Min. ST: 6.}
{16200}{}{Submachine gun 9mm}
{16201}{}{A simple and very reliable police weapon, used in Nevada and California. It has a fairly spacious magazine that is inserted into the handle. Min. ST: 4.}
{16300}{}{12 ga. caliber bullets}
{16301}{}{Ammunition pack for a shotgun. Cartridges are equipped with bullets.}
{16400}{}{Fighting stimulant}
{16401}{}{Doping for fighters in the ring. Pumps the body, increasing short-term resistance to damage and lowering the pain threshold. After some time, it strikes the body due to harmful chemicals that make up its composition.}
{16500}{}{Aircraft hatch}
{16501}{}{You see airplane hatch, torn by blast.}
{16600}{}{Table}
{16601}{}{A generic table. Holds stuff off the ground.}
{16700}{}{Table}
{16701}{}{A generic table. Holds stuff off the ground.}
{16800}{}{Stuff}
{16801}{}{These are miscellaneous items, also known as "stuff".}
{16900}{}{Stuff}
{16901}{}{These are miscellaneous items, also known as "stuff".}
{17000}{}{Stuff}
{17001}{}{These are miscellaneous items, also known as "stuff".}
{17100}{}{Stuff}
{17101}{}{These are miscellaneous items, also known as "stuff".}
{17200}{}{Stuff}
{17201}{}{These are miscellaneous items, also known as "stuff".}
{17300}{}{Stuff}
{17301}{}{These are miscellaneous items, also known as "stuff".}
{17400}{}{Stuff}
{17401}{}{These are miscellaneous items, also known as "stuff".}
{17500}{}{Stuff}
{17501}{}{These are miscellaneous items, also known as "stuff".}
{17600}{}{Stuff}
{17601}{}{These are miscellaneous items, also known as "stuff".}
{17700}{}{Stuff}
{17701}{}{These are miscellaneous items, also known as "stuff".}
{17800}{}{Stuff}
{17801}{}{These are miscellaneous items, also known as "stuff".}
{17900}{}{Stuff}
{17901}{}{These are miscellaneous items, also known as "stuff".}
{18000}{}{Crate}
{18001}{}{A wooden crate filled with generic stuff.}
{18100}{}{Desk}
{18101}{}{A generic desk. Seen one desk, you've seen them all.}
{18200}{}{Desk}
{18201}{}{A generic desk.}
{18300}{}{Desk}
{18301}{}{A generic desk.}
{18400}{}{Desk}
{18401}{}{A generic desk.}
{18500}{}{Desk}
{18501}{}{A generic desk.}
{18600}{}{Desk}
{18601}{}{A generic desk.}
{18700}{}{Desk}
{18701}{}{A generic desk.}
{18800}{}{Locker}
{18801}{}{Old locker used for storage.}
{18900}{}{Locker}
{18901}{}{Old locker used for storage.}
{19000}{}{Criminal case}
{19001}{}{Rather spoiled by rodents, humid and time, this folder contains materials of some old criminal case. Some things in it can still be read.}
{19100}{}{Disk with soundtrack}
{19101}{}{Holographic film with soundtrack to "Fallout: Nevada".}
{19200}{}{Book "Homo Ludens"}
{19201}{}{The pre-war edition of the book "Playing Man" by Johan Huizinga. The book studies nature and significance of playing games in evolution of human civilization.}
{19300}{}{Backup disk of "Fallout Encyclopedia"}
{19301}{}{The disk, filled to the full with various information on the world of Fallout.}
{19400}{}{Nevada Bible}
{19401}{}{A rare prehistoric document. Literally *each* new reading will give you a rush of experience. Though, very little.}
{19500}{}{Sedative}
{19501}{}{This Janet's syringe is filled with an excellent "sedative".}
{19600}{}{Stagecoach advertising}
{19601}{}{This tape contains advertising information about the "Nevada Express". You can copy the data to your Pip-Boy.}
{19700}{}{Box}
{19800}{}{Box}
{19900}{}{Box}
{20000}{}{Box}
{20100}{}{Box}
{20200}{}{Box}
{20300}{}{Box}
{20400}{}{Box}
{20500}{}{Flare}
{20501}{}{A flare. Creates light for a short period of time. The paper is a little worn, but otherwise it is in good condition. It is lit.}
{20600}{}{Dynamite}
{20601}{}{A high explosive, consisting of nitroglycerin mixed with the absorbent substance kiselguhr. Includes a timer, which is ticking.}
{20700}{}{Geiger Counter}
{20701}{}{A Wattz Electronics C-Radz model Geiger Counter. Detects the presence and strength of radiation fields. It is on.}
{20800}{}{Motion Sensor}
{20801}{}{A Wattz Electronics C-U model motion sensor. Detects the movement of biological material over a distance of meters using a tuned radar device. It is on.}
{20900}{}{Plastic Explosives}
{20901}{}{A chunk of Cordex, a military brand of plastic explosives. Highly stable, very destructive. Includes a timer, which is ticking.}
{21000}{}{Stealth Boy}
{21001}{}{A RobCo Stealth Boy 3001 personal stealth device. Generates a modulating field that transmits the reflected light from one side of an object to the other.}
{21100}{}{Bones}
{21101}{}{You see Ed. Ed's dead.}
{21200}{}{Clean water}
{21201}{}{Life-giving drinking water, purified of radiation by filters of Vault 8.}
{21300}{}{Reservoir}
{21301}{}{A reservoir for maintaining the viability of living cells or the body as a whole.}
{21400}{}{Boxes for documents}
{21401}{}{File cabinet for various documents.}
{21500}{}{Laboratory table}
{21501}{}{Table for experiments with chemicals.}
{21600}{}{Laboratory table}
{21601}{}{Table for experiments with chemicals.}
{21700}{}{Laboratory table}
{21701}{}{Table for experiments with chemicals.}
{21800}{}{Ashes of the forefather}
{21801}{}{A nasty mixture of ash, irradiated earth and cadaveric compost.}
{21900}{}{On-board computer}
{21901}{}{An important computer component that controls all the train systems. Currently not working.}
{22000}{}{On-board computer}
{22001}{}{An important computer component that controls all the train systems.}
{22100}{}{Security Card}
{22101}{}{Special key card that gives access to Lovelock radio station bunker.}
{22200}{}{Encoder}
{22201}{}{Old, but well-preserved device. Its main advantage is that it still works.}
{22300}{}{Remote key}
{22301}{}{This is the key for the electronic lock. By pressing the button it produces a radio signal of a certain frequency acting at a short distance.}
{22400}{}{Cable}
{22401}{}{Long high-voltage cable bay.}
{22500}{}{Cat's Paw Magazine}
{22501}{}{An issue of Cat's Paw magazine.}
{22600}{}{Box Of Noodles}
{22601}{}{You have no idea what "Instant Spaghetti" means. But apparently you can cook it.}
{22700}{}{TV Dinner}
{22701}{}{A television dinner. You're not sure what that means, but you are sure it doesn't look edible. You don't know if it ever did.}
{22800}{}{Molasses}
{22801}{}{The brown mass is of rather doubtful origin. Has an unpleasant smell and some incomprehensible impurities.}
{22900}{}{Photon Gun}
{22901}{}{This unusual weapon works on the basis of a quantum generator. Min. ST: 3.}
{23000}{}{Coordinates of a tire dump}
{23001}{}{This holotape contains the coordinates of the tire dump, located near Vegas.}
{23100}{}{Coordinates of a tire dump}
{23101}{}{This holotape contains the coordinates of the tire dump, located near Vegas.}
{23200}{}{Medical pajamas}
{23201}{}{Pajamas made from a special synthetic fiber, which stabilizes the thermal and air regime of the body. Before the war, it was given to patients after chemotherapy.}
{23300}{}{Turbo-plasma Rifle}
{23301}{}{Advanced plasma gun Winchester P94. The plasma chamber is equipped with a thermal winding to accelerate the formation of plasma charge. Min. ST: 6.}
{23400}{}{Spiked Knuckles}
{23401}{}{An improved version of the classic Brass Knuckles. The Spiked Knuckles do more damage, tearing into the flesh of your opponent in unarmed combat. Min. ST: 1.}
{23500}{}{Power Fist}
{23501}{}{A "Big Frigger" Power Fist from BeatCo. Considered by many to be the ultimate weapon to use in unarmed combat. Others are just scared. Powered by small energy cells. Min. ST: 1.}
{23600}{}{Combat Knife}
{23601}{}{A high-quality combat knife, the Stallona is from SharpWit, Inc. The edge of this blade is guaranteed sharp for over a decade of use! Min. ST: 2.}
{23700}{}{Newspapers}
{23701}{}{Several issues of the newspaper "Denver Post". Among the materials - the review of nuclear tests in Nevada, the next evidence of observations of UFOs in 100 km from Las Vegas and the advertising of new products from "Pretty & Glamour".}
{23800}{}{Passwords}
{23801}{}{A piece of paper with passwords written in a hurry.                    One: 153-648-987.         Two: 045-896-509.         Three: 987-469-876.      Four: 013-486-498.}
{23900}{}{Body armor}
{23901}{}{A light army bulletproof vest with elements to quickly unload all sorts of junk. Protects only a part of the torso, since it was meant to be used by Emergency Response Units members. In great condition.}
{24000}{}{Tesla Armor}
{24001}{}{This shining armor provides superior protection against energy attacks. The three Tesla Attraction Coil Rods disperse a large percentage of directed energy attacks.}
{24100}{}{Civilian Rifle}
{24101}{}{This rifle was widely used in various military conflicts long before the Great War. After the renovation of the US Army, surpluses poured into the civilian market, where they quickly became established as an affordable and reliable weapon. Min. ST: 5.}
{24200}{}{Combat Shotgun}
{24201}{}{A Winchester City-Killer 12-gauge combat shotgun, bullpup variant. In excellent condition, it has the optional DesertWarfare environmental sealant modification for extra reliability. Min. ST: 6.}
{24300}{}{Pot}
{24301}{}{A finely crafted clay pot.}
{24400}{}{Pot}
{24401}{}{A finely crafted clay pot.}
{24500}{}{Chest}
{24501}{}{Homemade wooden chest.}
{24600}{}{Shelf}
{24601}{}{Homemade metal shelf, assembled from pipes and bent iron sheets.}
{24700}{}{Shelf}
{24701}{}{Homemade metal shelf, assembled from pipes and bent iron sheets.}
{24800}{}{Pot}
{24801}{}{A finely crafted clay pot.}
{24900}{}{Pot}
{24901}{}{A finely crafted clay pot.}
{25000}{}{Bones}
{25001}{}{A pile of human bones.}
{25100}{}{Beanbag}
{25101}{}{A bunch of cans with screw-nuts inside them. It would seem that there is no use to this garbage anymore...}
{25200}{}{Balaclava}
{25201}{}{A tight headgear almost completely concealing the true face of the wearer. It can be worn with many types of armor, but doing this will surely cause panic of an occasional passerby.}
{25300}{}{Fuel Cell Controller}
{25301}{}{This chip controls the flow of power into a car's electric engines. Many drivers quickly burnt out this chip through frequent rapid acceleration. Still, it's a very valuable part - if you have a car to install it in.}
{25400}{}{Fuel regulator}
{25401}{}{Some drivers installed this regulator, halving fuel consumption, but most drivers did not care how much their cars gobbled up. In the end, fuel is cheap, and there is a lot of it, so why worry?}
{25500}{}{Commander's remains}
{25501}{}{This skeleton lies here a very long time. He wears a decayed military uniform, and a huge hole is gaping in his skull.}
{25600}{}{Crumpled piece of paper}
{25601}{}{There are some complex alphanumeric codes written on this piece of paper, you can't imagine what could those mean.}
{25700}{}{Parade uniform}
{25701}{}{Military uniform for high ranks. Now it's just clothes.}
{25800}{}{Rollbar}
{25801}{}{Mobile trolley for cooking and selling hot food right on the street.}
{25900}{}{Caramel}
{25901}{}{Sweet candy with an unexpected semi-drug stuffing. When you eat it, you feel drowsy, your head becomes heavier, your muscles work slower, but your facial expression becomes softer and your voice - less gruff.}
{26000}{}{Don't use}
{26001}{}{Don't use!}
{26100}{}{"Mickey's revenge"}
{26101}{}{Your personal homemade melee weapon. In some ways it could even compete with factory-made shockers. Min. ST: 3.}
{26200}{}{Rubber Boots}
{26201}{}{An old pair of sturdy rubber work boots. They look durable enough to keep out sludge, at least for a while.}
{26300}{}{Chest}
{26301}{}{Homemade wooden chest.}
{26400}{}{Laying eggs}
{26500}{}{Ranch guard jacket}
{26501}{}{This is a very durable leather jacket, reinforced with inserted metal pieces. Recognition marks on the back and sleeves indicate that the wearer is a guard of the ranch of Oliver Luciano.}
{26600}{}{Flask}
{26601}{}{Empty metal flask with a screw cap for storage and transportation of liquid.}
{26700}{}{Pass}
{26701}{}{Ordinary pass with magnetic stripe.}
{26800}{}{H&K CAWS}
{26801}{}{The CAWS, short for Close Assault Weapons System, shotgun is a useful tool for close-range combat. The bullpup layout makes the weapon compact enough to be easy to handle, while still retaining enough barrel length for its high velocity shells. Min. ST: 6.}
{26900}{}{Heavy bullets}
{26901}{}{A handful of "successfully" shot bullets from 12-caliber cartridges. Specifically this collection can still be used to manufacture new cartridges.}
{27000}{}{Robo Rocket Launcher}
{27001}{}{Only used by rocket equipped robots.}
{27100}{}{Broc Flower}
{27101}{}{Inflorescence sun-loving plants growing on stony ground. It is used in traditional medicine for its medicinal properties.}
{27200}{}{Xander Root}
{27201}{}{Rare root shade-loving plants, growing in loose soil with adequate moisture. It is used in traditional medicine for its medicinal properties.}
{27300}{}{Healing Powder}
{27301}{}{A very powerful healing magic- though it will bring the feeling of sleep to your head.}
{27400}{}{Robo Rocket Ammo}
{27401}{}{Only used by rocket equipped robots.}
{27500}{}{Car}
{27501}{}{It appears that this car stood in the open for more than ten years.}
{27600}{}{Gecko Pelt}
{27601}{}{This is the dried and cured hide of an ordinary Gecko.}
{27700}{}{Golden Gecko Pelt}
{27701}{}{This is the dried and cured hide of a Golden Gecko.}
{27800}{}{Toaster}
{27801}{}{Multi-functional composite device made by Wattz Electronics. It is a hybrid of electric stove, small oven and toaster. Designed for use in cramped trailers.}
{27900}{}{Gilmore's head}
{27901}{}{A severed head in a sack that once belonged to Gary Gilmore. This is a direct proof of his death.}
{28000}{}{Sharpened Spear}
{28001}{}{A razor tipped polearm. The shaft is wooden, and the tip is sharpened steel. Min. ST: 4.}
{28100}{}{Hairpin}
{28101}{}{Easily bends in any shape or form.}
{28200}{}{Welding machine}
{28201}{}{Welding machine with electromagnetic principle of operation. Precautions: Keep away from children and electronic devices. Min. ST: 6.}
{28300}{}{Tommy Gun}
{28301}{}{This Thompson M1928 submachine gun is a sinister looking weapon; every time you hold it, you have an urge to put on a fedora hat and crack your knuckles. The Thompson is well-fed by a large 50 round drum magazine. Min. ST: 5.}
{28400}{}{Meat Jerky}
{28401}{}{These smoked and dried chunks of beast-flesh remain chewy-licious and even somewhat nutritious for years, and years, and years...}
{28500}{}{Stash}
{28501}{}{Strong wooden box, buried in the ground.}
{28600}{}{"White walls"}
{28601}{}{A set for painting car tires. Fashion on white wheels was very common in the US during the Great Depression. Since then, this paint has slowly dried up and eventually turned into a useless stone.}
{28700}{}{Scoped Hunting Rifle}
{28701}{}{Nothing's better than seeing that surprised look on your target's face. The Loophole x20 Scope on this hunting rifle makes it easier than ever before. Accurate from first shot to last, no matter what kind of game you're gunning for. Min. ST: 5.}
{28800}{}{Generator fuel}
{28801}{}{Powerful source of energy used in electrical generators Wattz Electronics. If you find an exhausted generator, then this thing will be irreplaceable.}
{28900}{}{Shovel}
{28901}{}{This is a shovel for digging ditches and stuff.}
{29000}{}{Robo Melee Weapon 1}
{29001}{}{For Floating Eye Robot. Does Electrical Damage.}
{29100}{}{Robo Melee Weapon 2}
{29101}{}{For Floating Eye Robot. Does Electrical damage.}
{29200}{}{Boxing Gloves}
{29201}{}{A pair of boxing gloves that smell faintly of sweat. They look like they have seen a lot of use: many old blood stains still remain.}
{29300}{}{Plated Boxing Gloves}
{29301}{}{Someone has "accidentally" slipped metal plates into these boxing gloves. It could technically be considered cheating, but you prefer to think of it as an increased opportunity to dispense bone-crunching damage.}
{29400}{}{Hunting whistle}
{29401}{}{Homemade hunting whistle for beckoning mutated lizards. It has a very unpleasant sound.}
{29500}{}{Harrelson's attacks}
{29501}{}{Used by sadists and monsters.}
{29600}{}{HK P90c}
{29601}{}{The Heckler & Koch P90c was just coming into use at the time of the war. The weapon's bullpup layout and compact design make it easy to control. The durable P90c is prized for its reliability, and high firepower in a ruggedly-compact package. Min. ST: 4.}
{29700}{}{Advanced Grenade Launcher}
{29701}{}{Rockwell Grenade Launcher "Super-bazooka", equipped with a perfect recoil compensator. Min. ST: 5.}
{29800}{}{Communication key}
{29801}{}{The unusual shape of the key-turntables, which must be opened after placement inside the keyhole.}
{29900}{}{Pipe Rifle}
{29901}{}{This is a hand-made single shot rifle. Min. ST: 5.}
{30000}{}{"Savage"}
{30001}{}{Single-shot shotgun with a shortened barrel. Although this weapon is already very worn and outdated, it has an indisputable advantage - fast recharge. Min. ST: 4.}
{30100}{}{Towel}
{30101}{}{Designed in the laboratory "Pretty & Glamour" towel with a built-in chip that determines the dryness of the skin. Information on the tag prohibits smoking near the towel.}
{30200}{}{Death note}
{30201}{}{"To the one who kills me: I entered the path of robbery because the Clean City annexed my land. The harvest is taken by bastards from Vegas, I have nothing to feed myself with. I can't take it anymore."}
{30300}{}{Empty Holodisk}
{30301}{}{You need to write down the information from all the monitors on the surface on this holodisk.}
{30400}{}{Deck of "Tragic" Cards}
{30401}{}{This is a deck of cards for a collectible card game. Looks like it could be an expensive hobby if you got hooked.}
{30500}{}{The key to the computer}
{30501}{}{Magnetic access key from a computer terminal in the Wind of War.}
{30600}{}{Access card to the laboratory "Alpha"}
{30601}{}{An electronic first-level access card to Area 51 hangar.}
{30700}{}{Ammunition remains}
{30701}{}{Components of old ammunition: cartridges, bullets and gunpowder, carefully assembled piece by piece. Some of this can still be used in the production of new ammunition.}
{30800}{}{Super tool box}
{30801}{}{An impressive set of tools.}
{30900}{}{Old holodisk}
{30901}{}{Holodisk found in the abandoned settlement near Vault City. Information is encrypted with an old code.}
{31000}{}{Pre-war whiskey}
{31001}{}{Strong alcoholic drink of a very decent year. Highly valued in post-nuclear Nevada, compared to other types of alcohol.}
{31100}{}{Vocas}
{31101}{}{Nuts of a mutated water lily growing in salty waters near Salt Lake. Adaptation to local conditions gave nuts a unique property - it removes radiation particles from the body.}
{31200}{}{Tow rope}
{31201}{}{Durable automotive tow rope about 18 feet in length. Hooks are tied at both ends.}
{31300}{}{.44 Magnum Revolver}
{31301}{}{Being that this is the most powerful handgun in the world, and can blow your head clean-off, you've got to ask yourself one question. "Do I feel lucky?" Well, do ya, punk? Min. ST: 5.}
{31400}{}{Condom (Blue Package)}
{31401}{}{This is a Jimmy Hats brand condom, a very reliable brand. This one is ribbed for her pleasure.}
{31500}{}{Condom (Green package)}
{31501}{}{This is a Jimmy Hats brand condom, a very reliable brand. This one contains phosphorous green dye #2 and is slathered in spermicidal lubricant for added protection.}
{31600}{}{Condom (Red Package)}
{31601}{}{This is a Jimmy Hats brand condom, a very reliable brand. This one contains phosphorous red dye #5 and has a yummy cinnamon bun flavor... or so you heard.}
{31700}{}{Cosmetics Case}
{31701}{}{This is a genuine "Mary May" brand cosmetics case.}
{31800}{}{Empty syringe}
{31801}{}{This is an empty syringe for hypodermic injections.}
{31900}{}{Switchblade}
{31901}{}{The blade of this small knife is held by a spring. When a button on the handle is pressed, the blades shoots out with a satisfying "Sssssshk" sound. Min. ST: 1.}
{32000}{}{Sharpened Pole}
{32001}{}{A wood pole sharpened at one end. Min. ST: 4.}
{32100}{}{Torn head}
{32101}{}{The human head in a sack. Previously belonged to a resident of Provo, now it is yours by right.}
{32200}{}{Mysterious device}
{32201}{}{High-tech device of unknown purpose.}
{32300}{}{Signal jammer}
{32301}{}{Any action always has a reaction. This high-tech device is designed to suppress the radio signal and disable the electronic components of its source. Effective within eight miles' radius.}
{32400}{}{Disinfection}
{32401}{}{Tablets that completely destroy various biological contagion in water and similar fluids. With their help you can clean even the water from the sewer and drink it without harm to health.}
{32500}{}{Dice}
{32501}{}{A standard pair of gambling dice. It'd be cool to get a fuzzy pair for your car.}
{32600}{}{Loaded Dice}
{32601}{}{A pair of loaded dice. Don't be flashing these around the casino.}
{32700}{}{Drug-dealer disk}
{32701}{}{This disk contains some radio frequencies. You can't figure out anything more without working radio.}
{32800}{}{DVR records}
{32801}{}{Robot guard's holodisk with records of accompanying a stagecoach from Salt Lake City to New Reno. Perhaps, some information has been preserved here, however, in an encrypted form. Your Pip-Boy could read it.}
{32900}{}{Stranglehold}
{32901}{}{Ordinary silver guitar string, tunable to a note re. However, it has long been not used for its intended purpose.}
{33000}{}{Small chest}
{33001}{}{Old rusted chest, designed for storage.}
{33100}{}{"Super-science"}
{33101}{}{Perhaps the only pre-war magazine, entirely dedicated to the topic of energy weapons. Readers snapped it up like hotcakes, so to find one is a great luck!}
{33200}{}{M3A1 "Grease Gun" SMG}
{33201}{}{This submachine gun filled National Guard arsenals after the Army replaced it with newer weapons. However, the "Grease Gun" was simple and cheap to manufacture so there are still quite a few still in use. Min. ST: 4.}
{33300}{}{Heart Pills}
{33301}{}{These pills are used by people with heart problems.}
{33400}{}{"Horsekiller"}
{33401}{}{A hypodermic syringe with needle, full of powerful poison.}
{33500}{}{Courier's suitcase}
{33501}{}{This suitcase was carried by a secret courier from Vegas to Reno. You couldn't open it. Interesting, what is inside?}
{33600}{}{Maxson's sawed-off shotgun}
{33601}{}{You trade with Maxson for this item.}
{33700}{}{Mentats}
{33701}{}{Tablets from a chemical that expands consciousness. Improves brain functions associated with memory, and speeds up certain mental processes. Its highly addictive.}
{33800}{}{Fruit mentats}
{33801}{}{Tablets from a chemical that expands consciousness. Improves brain functions associated with memory, and speeds up certain mental processes. Doesn't cause addiction.}
{33900}{}{Trapped man notes}
{33901}{}{Diary of a man, trapped in mini-vault in Salt Lake. Very graphical reading material.}
{34000}{}{Remains}
{34001}{}{Decaying remains of a man who died in a relaxed position. Laid here, perhaps, more than a decade.}
{34100}{}{Robot's holodisk}
{34101}{}{This holodisk stores information about the state of the environment, which the robot scout collected during his travels.}
{34200}{}{Useful notes}
{34201}{}{A fast sketch biography of Jedediah Smith. The author describes the way of life in the settlements he visited.}
{34300}{}{Apple pie}
{34301}{}{M-m, a pie! Made of the maize dough and mutafruits.}
{34400}{}{Graveyard}
{34500}{}{Graveyard}
{34600}{}{Graveyard}
{34700}{}{Graveyard}
{34800}{}{Ugly armor}
{34801}{}{Rather ugly armor. The one who made this, apparently, was out of his mind... or counted on intimidating and disgusting effect.}
{34900}{}{Police armor}
{34901}{}{Simplified version of combat armor for the police.}
{35000}{}{Machine gun M2041}
{35001}{}{A manual machine gun with air cooling of the quick-change barrel, it's the reincarnation of the old commercial development under modern requirements. Part of the machine guns left after the release went "under", for sale and trade to the countries of the "third world". Min. ST: 6.}
{35100}{}{Cue}
{35101}{}{Ordinary billiard cue. Nothing special.}
{35200}{}{H&K G11}
{35201}{}{This gun revolutionized assault weapon design. The weapon fires a caseless cartridge consisting of a block of propellant with a bullet buried inside. The resultant weight and space savings allow this weapon to have a very high magazine capacity. Min. ST: 5.}
{35300}{}{Invitation ticket}
{35301}{}{This ticket gives the holder a one-time free pass to the night club of New Reno.}
{35400}{}{Pancor Jackhammer}
{35401}{}{The Jackhammer, despite its name, is an easy to control shotgun, even when fired on full automatic. The popular bullpup design, which places the magazine behind the trigger, makes the weapon well balanced & easy to control. Min. ST: 6.}
{35500}{}{Helical pistol machine gun}
{35501}{}{This unusual weapon is equipped with a screw magazine, which can store a large number of cartridges. Min. ST: 2.}
{35600}{}{CL 3000}
{35601}{}{Portable laboratory equipment, including a centrifuge and a liquid heater. You could use it to make medicines in the field.}
{35700}{}{.45 Caliber}
{35701}{}{Ammunition. .45 Caliber.}
{35800}{}{2mm EC}
{35801}{}{Ammunition.}
{35900}{}{4.7mm Caseless}
{35901}{}{Ammunition. Caliber: 4.7mm, caseless.}
{36000}{}{Energy cell}
{36001}{}{Unusual energy storage unit.}
{36100}{}{---}
{36101}{}{---}
{36200}{}{Grenade 40 mm}
{36201}{}{Cassette with shells for a hand grenade launcher.}
{36300}{}{Cartridges caliber .30}
{36301}{}{Rifle type of ammunition. Caliber: .30.}
{36400}{}{Postmarks}
{36401}{}{Very strange postmarks of the "Pink Elephant" series. Their purpose is as vague, as it is unclear how the absorbent paper remained intact for all these long years.}
{36500}{}{Plant Spike}
{36501}{}{An organic seed-spike that the carnivorous plants spit at potential food or seed carriers.}
{36600}{}{---}
{36601}{}{---}
{36700}{}{Ammo Crate}
{36800}{}{Ammo Crate}
{36900}{}{Ammo Crate}
{37000}{}{Ammo Crate}
{37100}{}{Claw}
{37101}{}{Claw}
{37200}{}{Claw}
{37201}{}{Claw}
{37300}{}{Access card to the bunker}
{37301}{}{An electronic security key from the inside door of the bunker in Reno.}
{37400}{}{Graveyard}
{37500}{}{Graveyard}
{37600}{}{Graveyard}
{37700}{}{Ammo manufacturing tool}
{37701}{}{Portable homemade device for ammo manufacturing. Special relay allows you to adjust the press for different calibers.}
{37800}{}{Ammo manufacturing tool (add.)}
{37801}{}{Portable homemade device for ammo manufacturing. Special relay allows you to adjust the press for different calibers. Supplemented with bits for armor-piercing cartridges.}
{37900}{}{Leather Armor Mark II}
{37901}{}{An enhanced version of the basic leather armor with extra layers of protection. Finely crafted from tanned brahmin hide.}
{38000}{}{Metal Armor Mark II}
{38001}{}{Polished metal plates, finely crafted into a suit of armor.}
{38100}{}{Combat Armor Mark II}
{38101}{}{High tech armor, made out of advanced defensive polymers.}
{38200}{}{Flamethrower Fuel MKII}
{38201}{}{This flamethrower fuel uses an advanced super-burn mix.}
{38300}{}{Don't use}
{38301}{}{Don't use!}
{38400}{}{Wrench}
{38401}{}{A typical wrench used by mechanics. Min. ST: 3.}
{38500}{}{Sawed-Off Shotgun}
{38501}{}{Someone took the time to chop the last few inches off the barrel and stock of this shotgun. Now, the wide spread of this hand-cannon's short-barreled shots makes it perfect for short-range crowd control. Min. ST: 5.}
{38600}{}{Baseball bat}
{38601}{}{This all-American, hardwood, baseball bat. Equipped with spikes to strengthen the impact. Min. ST: 4.}
{38700}{}{M60}
{38701}{}{This relatively light machine gun was prized by militaries around for world for its high rate of fire. This reliable, battlefield-proven design, was used on vehicles and for squad level fire-support. Min. ST: 7.}
{38800}{}{---}
{38801}{}{---}
{38900}{}{"Avenger" Minigun}
{38901}{}{Rockwell designed the Avenger as the replacement for their aging CZ53 Personal Minigun. The Avenger's design improvements include improved, gel-fin, cooling and chromium plated barrel-bores. This gives it a greater range and lethality. Min. ST: 7.}
{39000}{}{Solar Scorcher}
{39001}{}{Without the sun's rays to charge this weapon's capacitors this gun can't light a match. However, in full daylight, the experimental photo-electric cells that power the Scorcher allow it to turn almost anything into a crispy critter. Min. ST: 3.}
{39100}{}{Kelly's Rifle}
{39101}{}{Kelly's personal rifle. Very worn, but still a reliable weapon. Min. ST: 5.}
{39200}{}{M72 Gauss Rifle}
{39201}{}{The M72 rifle is of German design. It uses an electromagnetic field to propel rounds at tremendous speed... and pierce almost any obstacle. Its range, accuracy and stopping power is almost unparalleled. Min. ST: 6.}
{39300}{}{Machine gun .223}
{39301}{}{Hand machine gun for rifle cartridges. Min. ST: 6.}
{39400}{}{PPK12 Gauss Pistol}
{39401}{}{Praised for its range and stopping power, the PPK12 Gauss Pistol is of German design. The pistol uses an electromagnetic field to propel rounds at tremendous speed and punch through almost any armor. Min. ST: 4.}
{39500}{}{M16K}
{39501}{}{Submachine gun, designed by the firm "La France" in San Diego based on the M16. For some time was popular among special forces and police in individual states. Min. ST: 4.}
{39600}{}{YK32 Pulse Pistol}
{39601}{}{The YK32 is an electrical pulse weapon that was developed by the Yuma Flats Energy Consortium. Though powerful, the YK32 was never considered a practical weapon due to its inefficient energy usage and bulky design. Min. ST: 3.}
{39700}{}{YK42B Pulse Rifle}
{39701}{}{The YK42B is an electrical pulse weapon that was developed by the Yuma Flats Energy Consortium. It is considered a far superior weapon to the YK32 pistol, having a greater charge capacity and range. Min. ST: 3.}
{39800}{}{.44 Magnum (Speed Load)}
{39801}{}{A .44 Magnum Revolver with a speed loader. Min. ST: 5.}
{39900}{}{Super Cattle Prod}
{39901}{}{A Farmer's Best Friend model cattle prod from Wattz Electronics. This model has been upgraded to increase the electrical discharge. Min. ST: 4.}
{40000}{}{Improved Flamer}
{40001}{}{A Flambe-450 model flamethrower, varminter variation. Fires a short spray of extremely hot, flammable liquid. Requires specialized fuel to work properly. This model has been modified to fire a hotter mixture which causes greater combustibility. Min. ST: 6.}
{40100}{}{Laser Rifle (Ext. Cap.)}
{40101}{}{This Wattz 2000 laser rifle has had its recharging system upgraded and a special recycling chip installed that reduces the drain on the micro fusion cell by 50%. Min. ST: 6.}
{40200}{}{Magneto-Laser Pistol}
{40201}{}{This Wattz 1000 laser pistol has been upgraded with a magnetic field targeting system that tightens the laser emission, giving this pistol extra penetrating power. Min. ST: 3.}
{40300}{}{Henry's Rifle}
{40301}{}{Old, but still reliable carbine, designed in the era of the "gold rush." Being a popular sports weapon, an object of collectibles and show-off, was made up to the Great War for the civilian population. Min. ST: 4.}
{40400}{}{Desert Eagle (Exp. Mag.)}
{40401}{}{An ancient Desert Eagle pistol, in .44 magnum. Interest in late 20th century films made this one of the most popular handguns of all times. This one has been equipped with an expanded magazine for longer fun and games! Min. ST: 5.}
{40500}{}{Assault Rifle (Exp. Mag.)}
{40501}{}{This Assault Rifle has an extended, military sized, ammunition clip. The expanded magazine capacity makes it more fun than ever to Spray-and-Pray. Min. ST: 5.}
{40600}{}{Plasma Pistol (Ext. Cap.)}
{40601}{}{This Glock 86 Plasma Pistol has had its magnetic housing chamber realigned to reduce the drain on its energy cell. Its efficiency has doubled, allowing it to fire more shots before the battery is expended. Min. ST: 4.}
{40700}{}{Mega Power Fist}
{40701}{}{A "Big Frigger" Power Fist from BeatCo. Considered by many to be the ultimate weapon to use in unarmed combat. This one has upgraded power servos for increased strength. Powered by small energy cells. Min. ST: 1.}
{40800}{}{Field Medic First Aid Kit}
{40801}{}{A small kit containing basic emergency medical equipment. Bandages, wraps, antiseptic spray, and more.}
{40900}{}{Paramedics Bag}
{40901}{}{This bag contains instruments and chems used by paramedics in the field. The tools contained are specifically designed for high trauma and emergency cases.}
{41000}{}{Expanded Lockpick Set}
{41001}{}{A set of locksmith tools. Includes all the necessary picks and tension wrenches to open conventional pin and tumbler locks. This set also includes some special tools for more difficult mechanical locking mechanisms.}
{41100}{}{Electronic Lockpick MKII}
{41101}{}{This is the second generation Wattz Electronics Micromanipulator FingerStuff electronic lockpick. For defeating electronic locks and security devices. This Mark II version includes updated software and interface tools.}
{41200}{}{Weapon parts}
{41201}{}{Parts of the different types of firearm. It can be used for the repair or improvement of other weapons.}
{41300}{}{Photo of a girl}
{41301}{}{Before you is a picture of a naked girl with holes burned in the eyes. It seems that the girl was very beautiful. On the back is written "Virginia Street, 75".}
{41400}{}{Key to the cellar}
{41401}{}{Standard key from the door lock at New Reno station.}
{41500}{}{Gecko egg}
{41501}{}{It could provide a cute and funny animal in the future. But instead goes to feed someone rich.}
{41600}{}{Toll from Stryker}
{41601}{}{A metal diplomat case coated with brahmin skin. Intended for Big Louie. The contents of case are unknown.}
{41700}{}{Laboratory helmet}
{41701}{}{Once this protective helmet was included as a component of hermetic chemical protection suit. Now it's the only remaining part.}
{41800}{}{Rat trap}
{41801}{}{Ancient mechanical device. Excellent against small brainless animals.}
{41900}{}{Mantis snack}
{41901}{}{Mantis leg prepared the right way.}
{42000}{}{"Blind Fury"}
{42001}{}{A worn sword with wooden sheath disguised as a cane. Although the quality of steel leaves much to be desired, this weapon has clearly saved the lives of its owner more than once. Min. ST: 3.}
{42100}{}{Powder grenade}
{42101}{}{Homemade hand grenade with a chemical detonator. Equipped with striking elements around a powerful powder fuse.}
{42200}{}{Shampoo}
{42201}{}{A bottle of shampoo. Before the war it was a fairly well-known brand.}
{42300}{}{Root beer}
{42301}{}{A variety of root beer, cooked in the field. Slightly fogs the head, but has healing properties.}
{42400}{}{Tactical rocket}
{42401}{}{Rare piece of ammunition - a rocket with enriched uranium, for a grenade launcher. Save it for a special occasion.}
{42500}{}{Overseer's post}
{42501}{}{The post of Overseer with a long-disintegrating corpse, from which, throughout the post, a biological contagion has spread.}
{42600}{}{Boxes}
{42601}{}{Two large wooden boxes. The inscriptions on the sides are no longer distinguishable.}
{42700}{}{Flaming Breath}
{42800}{}{Shaman's belongings}
{42801}{}{The personal belongings of the Niskigvan. Among them there are various tools useful in collecting and processing medicinal herbs.}
{42900}{}{Gold Tooth}
{42901}{}{You knocked out that golden tooth from Tuco's jaw. Now it's yours.}
{43000}{}{Mantis limb}
{43001}{}{Crispy limb of giant-sized insect.}
{43100}{}{Pistol part}
{43101}{}{Special butt-holster for 9mm pistol. Inside you'll also find all the necessary parts and tools for cleaning and simple repair.}
{43200}{}{Biker's jacket}
{43201}{}{A worn combat jacket with a patch of bikers. Has a layer of foil and metal, which enhances protection from laser and plasma exposure.}
{43300}{}{Amulet of the Cheyenne}
{43301}{}{The totem amulet of the chief of the Cheyenne tribe. When you hold it in your hands, luck itself smiles at you.}
{43400}{}{Wagon}
{43401}{}{A caravan wagon converted from the wrecked remains of an ancient automobile.}
{43500}{}{Wagon}
{43501}{}{A caravan wagon converted from the wrecked remains of an ancient automobile.}
{43600}{}{Deck of Cards}
{43601}{}{A standard set of playing cards.}
{43700}{}{Pack of Marked Cards}
{43701}{}{A standard set of playing cards, which has special inconspicuous marks on the back.}
{43800}{}{Reactor access card}
{43801}{}{Electronic access card to the reactor level in the hangar V9.}
{43900}{}{Recipe: "Mantis Snack"}
{43901}{}{The cooking recipe for snacks from the foot of a mantis, soaked in beer and fried with pieces of mutafruit.}
{44000}{}{Brahmin milk}
{44001}{}{Nourishing brahmin milk. It contains many nutrients, which are compensated by... radioactivity.}
{44100}{}{Dog's name tag}
{44101}{}{A tag with the name of the dog and his owner.}
{44200}{}{Fuse}
{44201}{}{A thin wire in a vacuum glass envelope, responsible for the safety of the equipment in case of electrical overload.}
{44300}{}{Poisoned moonshine}
{44301}{}{Bottle of moonshine mixed with deadly poison.}
{44400}{}{"Saboteur's case"}
{44401}{}{Popular essays by the old warrior named Maddox, a veteran of subversive and reconnaissance operations. The author reveals the methods of conducting sabotage operations, talks about traps and devices of mass destruction.}
{44500}{}{IOU}
{44501}{}{Receipt for card debts to the "Eldorado" casino.}
{44600}{}{Memory eraser}
{44601}{}{This technology allows you to erase a certain memory of short duration and replace it with another, illusory. So from the enemy you can make a friend. But if it does not succeed, then such jokes will not be forgiven.}
{44700}{}{Contract for the purchase of slaves}
{44701}{}{This is your contract with the Vegas slavers guild about acquiring a large slave party.}
{44800}{}{Letter to Eric}
{44801}{}{"Eric, they want to take you to fight in the ring. You know what this means. Anyway, it's only better for us! When you get out of the pen, a shootout will begin. At this moment run as fast as you can! Do not worry about me. Your brother Gareth".}
{44900}{}{Do not use}
{44901}{}{Do not use!}
{45000}{}{---}
{45001}{}{---}
{45100}{}{Prospector's note}
{45101}{}{This note was on the corpse of a prospector in Hawthorne. It says, "If I die, tell my family in Reno that I love them." Signature: Robert Gate.}
{45200}{}{Lunch token}
{45201}{}{This token with the symbol of Nuka-Cola is made from an old poker chip.}
{45300}{}{Box for bottles}
{45301}{}{This wooden box is designed for safe transportation of glass bottles.}
{45400}{}{Wagon}
{45401}{}{This caravan wagon is specifically prepared for the transportation of bottles.}
{45500}{}{Car Trunk}
{45501}{}{The trunk is a great place to store your stuff.}
{45600}{}{Big Louie's keys}
{45601}{}{A bunch of keys from the raiders base in Lovelock.}
{45700}{}{Voucher for David and Norman}
{45701}{}{The receipt, according to which Norman undertakes to pay David his gambling debts in the form of his own adrenal gland.}
{45800}{}{Ely Gorbinsky's case}
{45801}{}{The label reads: "Ely Gorbinsky's case, preliminary report".}
{45900}{}{---}
{45901}{}{---}
{46000}{}{Jay's message}
{46001}{}{This holodisk contains a message addressed to you personally.}
{46100}{}{Report on deserters}
{46101}{}{Holodisk from Hawthorne with a report on a group of fugitive military personnel.}
{46200}{}{---}
{46201}{}{---}
{46300}{}{Medical report}
{46301}{}{The label reads: "Recommendations for treating the head of the former president".}
{46400}{}{Records of a citizen}
{46401}{}{Diary entries of a resident of a government vault. Pretty interesting reading. This text can be copied to your Pip-Boy.}
{46500}{}{"Exodus"}
{46501}{}{Holodisk with information about the governmental vault project.}
{46600}{}{Remote control}
{46601}{}{Force field remote control. 12 feet coverage area.}
{46700}{}{Hood}
{46800}{}{Sandwich}
{46801}{}{Nutritious sandwich made from brahmin meat under the thick dark-yellow sauce sandwiched on both sides of a delicious soft bun and a piece of some greenery. Delicious.}
{46900}{}{Rot Gut}
{46901}{}{A very strong liquor. Or cleaning fluid, you decide.}
{47000}{}{Crusher}
{47001}{}{A large hammer with a massive handle, equipped with custom-made spikes on the head to increase the damage. It is better to take a smaller hammer for tenderizing meat. Min. ST: 6.}
{47100}{}{The manual on neurosurgery}
{47101}{}{Very rare manual for highly qualified surgeons. It seems that very important information is collected here, but it is so scientific and complex that it will take a lot of time and effort to study.}
{47200}{}{A look in the face of death}
{47201}{}{You are brave, and therefore it is easier for you to orient yourself when there is a mess around.}
{47300}{}{Irradiated Nuka-Cola}
{47301}{}{Amazing pre-war drink in a slightly dirty bottle. Has a wonderful aftertaste and a very questionable glow in the dark.}
{47400}{}{Magnet-laser pistol Ì2}
{47401}{}{This laser gun Wattz 1000 has undergone various improvements, which increased its capacity by 50% at price of range and power consumption. Min. ST: 3.}
{47500}{}{Do not use}
{47501}{}{Do not use!}
{47600}{}{"Bloody Mary"}
{47601}{}{A high-octane alcoholic cocktail. Very useful after a hard day at the end of the week.}
{47700}{}{Case with documents}
{47701}{}{The case contains reports from Lovelock radio station. They are often referred to Vault 8. Unfortunately, most of them are encrypted, but the rest you can input in your Pip-Boy.}
{47800}{}{---}
{47801}{}{---}
{47900}{}{Poisoning gas}
{47901}{}{A high-pressure cylinder with extremely dangerous gas. Designed to destroy all life form in the hangar of Area 51 in case of emergency.}
{48000}{}{Good dream}
{48001}{}{Having slept well at the hotel, you get a +1 bonus to Perception and Intelligence for an hour.}
{48100}{}{Enhanced Perception}
{48101}{}{Visiting places with an excellent overview temporarily enhances your Perception.}
{48200}{}{Turbo-Cola}
{48201}{}{Drug of self-made production. Causes a short burst of adrenaline, after which a powerful pressure on the arteries causes a strong fever.}
{48300}{}{Camera}
{48301}{}{Ancient means of photography from the company "Kodak." To work requires a film of 24 frames.}
{48400}{}{Nelson's key}
{48401}{}{Standard key for the warehouse in the Uranium City tunnel.}
{48500}{}{Locker}
{48501}{}{Automated locker for storing things. Equipped with a system of voice commands, which for some reason does not work.}
{48600}{}{Locker}
{48601}{}{Automated locker for storing things. Equipped with a system of voice commands, which for some reason does not work.}
{48700}{}{"Chryslus Motors" Catalogue}
{48701}{}{The publication of the automobile company "Chryslus Motors". Contains a lot of useful information for both drivers and car mechanics.}
{48800}{}{Anti-personnel mine}
{48801}{}{Pressure-based mine, designed to engage the enemy's manpower.}
{48900}{}{Special Boxer Weapon}
{49000}{}{Records of the officer}
{49001}{}{Holodisk with audiotapes of the soldier.}
{49100}{}{Mr. Nixon Doll}
{49101}{}{You see a small doll with a big red nose. For some reason, you don't trust this seemingly-innocent child's toy.}
{49200}{}{Tanker Fob}
{49201}{}{An encoded passkey that provides access to high security areas.}
{49300}{}{Newspaper clippings}
{49301}{}{A pack of pages torn from various newspapers. All are about the same thing - the great loss of Big Louie.}
{49400}{}{Acid gecko pelt}
{49401}{}{Torn from the corpse of an acid gecko, this skin is valued for its refractory and plasma-resistant qualities.}
{49500}{}{Special pass}
{49501}{}{An electronic access card from many government vault doors.}
{49600}{}{Bo's Pole}
{49601}{}{Very strong and balanced pole with rounded ends, on which soft cushions are fastened. Training version from the company "Hattori Souvenirs". Min. ST: 3.}
{49700}{}{kubotan}
{49701}{}{An ancient non-lethal weapon, originally designed for police needs. It is important to note that it's an excellent helper in a fight, but only for those who have sufficient martial arts skills. Min .ST: 1.}
{49800}{}{Dual Plasma Cannon}
{49801}{}{Only use for Gun Turret critter.}
{49900}{}{Food can}
{49901}{}{In front of you is a can of dog food. And judging by the date on the lid, it is more than 70 years old. If you dare to open it, it is better to wear a gas mask in advance.}
{50000}{}{Old revolver}
{50001}{}{Very old model of once popular revolver. Perhaps the museum exhibit. Min. ST: 1.}
{50100}{}{Wall Safe}
{50200}{}{Floor Safe}
{50300}{}{Blue Memory Module}
{50301}{}{A read only computer memory module containing medical information. This module details charisma enhancements.}
{50400}{}{Green Memory Module}
{50401}{}{A read only computer memory module containing medical information. This module details perception enhancements.}
{50500}{}{Red Memory Module}
{50501}{}{A read only computer memory module containing medical information. This module details strength enhancements.}
{50600}{}{Yellow Memory Module}
{50601}{}{A read only computer memory module containing medical information. This module details intelligence enhancements.}
{50700}{}{Decomposing Body}
{50701}{}{This is a partially decomposed body of a humanoid creature.}
{50800}{}{Pistol 10mm (ext. mag)}
{50801}{}{Self-loading pistol Colt 6520 caliber 10mm with an extended magazine. Min. ST: 3.}
{50900}{}{Maxson's Sawed-off}
{50901}{}{An old shotgun, once owned by raider Maxson. The barrel and butt are trimmed to expand the scatter of the shot. Min. ST: 5.}
{51000}{}{Pool Table}
{51100}{}{Pool Table}
{51200}{}{Pool Table}
{51300}{}{Pool Table}
{51400}{}{Pool Table}
{51500}{}{Pool Table}
{51600}{}{Map of the lake}
{51601}{}{A crumpled pre-war map of the surrounding area of Salt Lake City and its large lake. Throughout the map are scattered various markers, indicating local attractions and institutions. Practically a guide.}
{51700}{}{Cleaver}
{51701}{}{A huge knife designed for cutting meat. Min. ST: 3.}
{51800}{}{Dual Minigun}
{51801}{}{Only use for Auto-Cannon critter.}
{51900}{}{Bottle Caps}
{51901}{}{These are worthless bottle caps used in the Nuka-Cola plant. A legend says that someday their value will be much higher than now. But now it sounds to you like a weird fairy tale.}
{52000}{}{Heavy Dual Minigun}
{52001}{}{Only use for Auto-Cannon Critter.}
{52100}{}{Hunting table}
{52101}{}{Table for cutting a prey.}
{52200}{}{Rusty machete}
{52201}{}{Someone worked the lawnmower blade, sharpening one edge, and tightly wrapped the hilt of the brahmin skin. Min. ST: 5.}
{52300}{}{"Trade" magazine}
{52301}{}{Pre-war weekly magazine, issued for people running their own business. And even while the times has changed, you can still draw useful information about the trade from this edition.}
{52400}{}{Worn jacket}
{52401}{}{This dirty smelly jacket once belonged to a raider. It is so worn out that you can hear how the threads break when you move.}
{52500}{}{Afterburner's gum}
{52501}{}{Methamphetamine gum wrapped in a newspaper stub. According to Afterburner, its use for a short time stimulates the central nervous system.}
{52600}{}{Remains}
{52601}{}{Remains of the vault dweller. The corpse lies here for so long that it is withered to the bone.}
{52700}{}{Remains}
{52701}{}{Remains of the vault dweller. The corpse lies here for so long that it is withered to the bone.}
{52800}{}{Ira Kane}
{52801}{}{This guy seems to have died from methane vapors poisoning.}
{52900}{}{Cooking Stove}
{52901}{}{Ordinary cooking stove for cooking. It hasn't been used for its intended purpose for a long time.}
{53000}{}{Fireplace}
{53001}{}{Once a beautiful decorative fireplace with a photograph of an Indian philosopher.}
{53100}{}{Laser pistol (police.)}
{53101}{}{Laser pistol Wattz 1500, police model. Power higher than civilian models thanks to the use of crystals instead of cheap diodes. Min. ST: 3.}
{53200}{}{---}
{53300}{}{---}
{53400}{}{---}
{53500}{}{---}
{53600}{}{---}
{53700}{}{---}
{53800}{}{---}
{53900}{}{---}
{54000}{}{---}
{54100}{}{---}
{54200}{}{---}
{54300}{}{---}
{54400}{}{---}
{54500}{}{---}
{54600}{}{---}
{54700}{}{---}
{54800}{}{Ammo box}
{54801}{}{Rare large-caliber ammo for very heavy machine guns - so heavy that you don't even have an idea which ones.}
{54900}{}{Zip gun}
{54901}{}{A pitiful semblance of a pistol, known as the Zip gun. The name says it all. Min. ST: 1.}
{55000}{}{Shelf for tools}
{55100}{}{Purse}
{55101}{}{A manly dilapidated purse with various documents and notes of commercial content. For you there is nothing of value, but for the former owner the loss of this thing will certainly leave a mark.}
{55200}{}{License}
{55201}{}{This is your personal sales license, issued by the manufacturer of the famous tonic beverage "Nuka-Cola".}
{55300}{}{Travel ticket}
{55301}{}{One way ticket for stagecoach.}
{55400}{}{Pieces}
{55401}{}{Metal plates the size of an ordinary coin. Theoretically it should be absolutely useless.}
{55500}{}{Indispensable coin}
{55501}{}{This is a fully-fledged jubilee coin ... except for the fact that someone drilled a hole in it and put a strong thread through.}
{55600}{}{Metal detector}
{55601}{}{The device is powered by nuclear batteries. Designed for the detection of metal objects within a radius of no more than 4 meters.}
{55700}{}{Metal detector}
{55701}{}{The device is powered by nuclear batteries. Designed for the detection of metal objects within a radius of no more than 9 meters. Installation of the ultrasound scanner allowed to double the extend of the detection radius.}
{55800}{}{C-4 explosives}
{55801}{}{Box with plastic explosive material for military use.}
{55900}{}{Caravan merchant's suit}
{55901}{}{Special clothes which maximize mobility of movement in conditions of desert. Protective goggles and dust mask are included.}
{56000}{}{Anti-radiation suit}
{56001}{}{Reliable means of personal protection against radioactive exposure.}
{56100}{}{Gas protection suit}
{56101}{}{Protective jumpsuit for workers engaged in dirty and stinky work. It is supplied with a gas mask, rubber boots and removable glasses. Protects  well from harmful fumes in the air and is very uncomfortable to use.}
{56200}{}{"Atomic Blades"}
{56201}{}{Set of razor blades. Manufactured by "Pretty & Glamour" in the city of Knoxville, Tennessee. The box depicts an atomic bomb tests in the Pacific Ocean.}
{56300}{}{Soap scraps}
{56301}{}{Aromatic soap from the company "Pretty & Glamour" with bite marks. Judging by the imprints of teeth, it was bit by an adult.}
{56400}{}{Toothpaste}
{56401}{}{Toothpaste infused with thorium. Produced by the cosmetics company "Pretty & Glamour". Gently polishes the tooth enamel, making it white and shiny. Teeth so glossy you'll see your smile in the dark.}
{56500}{}{Comic book}
{56501}{}{Funny comics about the merry guy Pip-Boy, who was constantly looking for an adventure on his ass.}
{56600}{}{Healing water}
{56601}{}{A small bottle of supposedly healing water "Radium" from the company "Pretty & Glamour".}
{56700}{}{Colt Revolver}
{56701}{}{A very powerful exclusive weapon. The surface is covered in traditional Indian ornaments. When you look at it under the flickering lights of Vegas, you feel like a god. Min. ST: 5.}
{56800}{}{"Black Dynamite"}
{56801}{}{Extremely cool and stylish revolver. Min. ST: 6.}
{56900}{}{Bath salt}
{56901}{}{Salt from the company "Pretty & Glamour" for the enrichment of bathroom water with radon. It is used for nervous disorders, insomnia, loss of strength, arthritis and rheumatism.}
{57000}{}{Burp}
{57001}{}{Stinky burp of an acid gecko. Min. ST: 1.}
{57100}{}{REZ-4}
{57101}{}{A rare electromagnetic gun. You're lucky... If you can handle a weapon of this size. The problem is also in the absence of a way for recharging the battery. When the charge is over, this weapon will become useless. Min. ST: 8.}
{57200}{}{Flail}
{57201}{}{The brutal weapon of bikers is a large-caliber chain with a heavy metal ball at the end. Min. ST: 5.}
{57300}{}{Rusty Katana}
{57301}{}{Sword from the gift set from the company "Hattori Souvenirs". Although the weapon is clearly inferior in quality to its Japanese progenitor, in a strong hand it can permanently eliminate the enemy from the battlefield, even if he is in the armor. Min. ST: 4.}
{57400}{}{Beatnik's glasses}
{57401}{}{Round glasses. Nothing special, but looks stylish.}
{57500}{}{Straight razor}
{57501}{}{Razor with open blade made by "Sharpy wits". Still very sharp. Min. ST: 1.}
{57600}{}{Painkiller}
{57601}{}{This cartridge is filled with a powerful pre-war analgesic. The drug is more than 40 years past it's expiration date, which gives it an even more adverse and irreversible effect on the heart and blood vessels than before.}
{57700}{}{Wet wipes}
{57701}{}{Sealed packaging with sanitary napkins. Can replace a bath when wandering through the wasteland. Production of the company "Pretty & Glamour".}
{57800}{}{Old food can}
{57801}{}{An opened can in which over 70 years old dog food was stored. It seems that guy fooled you! (Everyone is mockingly pointing finger at you, making a lingering "ewwww!" sound)}
{57900}{}{Warehouse pass}
{57901}{}{NPP "Poseidon Oil" electronic access card.}
{58000}{}{Operational staff pass}
{58001}{}{NPP "Poseidon Oil" electronic access card.}
{58100}{}{Pizza}
{58101}{}{Excellent pizza with gecko meat and mushrooms. And a lot of pepper.}
{58200}{}{Shitposter's weed}
{58201}{}{This is all that remains of Shitposter - an unremarkable and seemingly harmless bunch of weed. Do not use in any circumstances.}
{58300}{}{Nuka-Cola (cherry.)}
{58301}{}{A bottle of Nuka-Cola, a flavored non-alcoholic beverage of the post-nuclear world. It is made from the leaves of mutated coca and juice of some fruits. Warm and exhausted. With cherry flavor.}
{58400}{}{Nuka-Cola with flavor}
{58401}{}{Bottle of self-made Nuka-Cola. Someone decided to make money by selling such a low-quality product bypassing the "official" manufacturer.}
{58500}{}{"Desert Eagle"}
{58501}{}{"Desert Eagle" Caliber .44 Magnum. Equipped with a modern accurate sight. Min. ST: 5.}
{58600}{}{Ring}
{58601}{}{A massive metallic ring in the shape of a skull. Quite a brutal piece. It was so grown into skin that you had to tear off a finger with it.}
{58700}{}{Contract with the drug dealer}
{58701}{}{The contract between Fatso and the drug dealer about the acquisition of a batch of chemical raw materials. On the other side is written commitment to a deal - bets on fighters of "Eldorado" ring.}
{58800}{}{Killer's note}
{58801}{}{Evidence, left on the body of the killer in the parking lot in New Vegas. It seems that, that techie from the Wind of War put a hit on you! And used his own people.}
{58900}{}{Emulsifier E30}
{58901}{}{A crumbling yellow substance with an unbearable smell of hundreds of garbage cans. The appearance does not inspire confidence either.}
{59000}{}{Geller's confession}
{59001}{}{Holodisk with a record you made during a conversation with Larry Geller. In the conversation, Larry confessed that he once produced drugs. This will be enough to the police.}
{59100}{}{Slaver's receipt}
{59101}{}{The business memos and notes, maintained by head of the slavers guild. Some information seems interesting to you: "...Boss ordered to wait for the ghouls to be set up with drugs. After that they won't be a problem. We should be ready to sell the necessary amount of slaves to the Dam for a really good price."}
{59200}{}{Suspicious package}
{59201}{}{This drug was given to you by Hal Wallace so you could put it in a freaks' hotel.}
{59300}{}{Compromising evidence on H. Wallace}
{59301}{}{Holodisk with a record you made while talking to Hal Wallace about getting a job on freaks. Police will find it interesting.}
{59400}{}{"Desert Eagle"}
{59401}{}{"Desert Eagle" .44 Magnum, owned by Bob Neil. In addition to its impressive appearance, it has an enhanced mechanism that increases the fire power of this weapon. Min. ST: 5.}
{59500}{}{H. Wallace confession}
{59501}{}{A holodisk with a record you made while talking to Hal Wallace about getting a job on Bob Neil. Direct evidence.}
{59600}{}{O. Davis receipt}
{59601}{}{This document contains the information about unusually high fees from the Las Vegas municipality to O. Davis. The point is to prioritize the police on cases about drugs. The note is signed by T. Parker. But why such costs? And why the mayor's office is so interested in this matter?}
{59700}{}{Tom Parker's Receipt}
{59701}{}{A document of Las Vegas municipality, containing the order about transferring 6% of municipality's shares to the head of the Slavertown. Draft prepared by T. Parker. Fulfillment signature is not present yet.}
{59800}{}{Larry on Phillips}
{59801}{}{Holodisk with a record that you secretly made during a conversation with Larry Geller about Sam Phillips. He testified that Phillips once had contact with drug dealers.}
{59900}{}{Drug dealer about Phillips}
{59901}{}{Holodisk with a record that you secretly made during a conversation with the drug dealer about Sam Phillips. He testified that Phillips once had contact with drug dealers.}
{60000}{}{Notes from The Pound}
{60001}{}{The notes and recordings found in "The Pound" laboratory. They contain information regarding production and shipment of narcotic substanses in large quantities during the last few months. You notice a mention of an unusual buyer among others - the "Three-card Monte" casino.}
{60100}{}{Dirt on Bob Neil}
{60101}{}{Recording of your conversation with Bob Neil, in which Bob Neil openly asks you to eliminate Hal Wallace.}
{60200}{}{Soldier badge}
{60201}{}{This token is engraved with personal information about its owner - name, date of birth, some serial number and other exact data.}
{60300}{}{---}
{60400}{}{---}
{60500}{}{Power Armor}
{60501}{}{This is your personal armor, equipped with autonomous systems that make it similar to the high-tech pre-war armor T-51b.}
{60600}{}{Autonomous system of T-51b armor}
{60601}{}{A complex system of interlinked devices, including a small nuclear reactor, an exoskeleton power module, a cooling unit and other components required in the assembly of T-51b power armor.}
{60700}{}{Central Processing Unit}
{60701}{}{This is the central link of motorized T-51b armor. Without this processor, half of the armor potential, including strength enhancement, can not be used.}
{60800}{}{PLC}
{60801}{}{Programmable logic controller. Does not work.}
{60900}{}{PLC}
{60901}{}{Programmable logic controller. Ready to work.}
{61000}{}{Personal Safe}
{61001}{}{Your personal safe with a combination lock for storing things.}
{61100}{}{Personal Safe}
{61101}{}{Your personal safe with a combination lock for storing things.}
{61200}{}{---}
{61201}{}{---}
{61300}{}{Chest of drawers with mirror}
{61301}{}{Luxury furniture with a large cracked mirror.}
{61400}{}{Chest of drawers with mirror}
{61401}{}{Luxury furniture with a large cracked mirror.}
{61500}{}{Table}
{61501}{}{Slightly stained with fat stains table.}
{61600}{}{Chest of drawers with mirror}
{61601}{}{Luxury furniture with a large cracked mirror.}
{61700}{}{Boxes for documents}
{61701}{}{File cabinet for various documents.}
{61800}{}{Chest of drawers}
{61801}{}{Old chest of drawers with doors.}
{61900}{}{Shelf}
{61901}{}{Glass shelf that is falling apart.}
{62000}{}{Shelf}
{62001}{}{Glass shelf that is falling apart.}
{62100}{}{Book shelf}
{62101}{}{A shelf with some books.}
{62200}{}{Book shelf}
{62201}{}{A shelf with some books.}
{62300}{}{Book shelf}
{62301}{}{A shelf with some books.}
{62400}{}{Book shelf}
{62401}{}{A shelf with some books.}
{62500}{}{Ingram Police}
{62501}{}{American submachine gun produced in the middle of last century. The police version is distinguished by the front handle, partially finned trunk and a fly without a nouvelle. Min. ST: 5.}
{62600}{}{Rocket launcher}
{62601}{}{Unclaimed Rockwell Hand grenade launcher. 40 mm caliber. Simple in handling, but requires considerable strength to use effectively. Min. ST: 5.}
{62700}{}{Grenade launcher 40 mm}
{62701}{}{Hand grenade Rockwell launcher, created in continuation of the ancient models of the Springfield arsenal. Designed for strong soldiers. Min. ST: 6.}
{62800}{}{Grenade launcher 40 mm (ext. mag)}
{62801}{}{Rockwell Hand grenade launcher, created in continuation of the ancient models of the Springfield arsenal. Equipped with a cylinder magazine for 6 shells. Min. ST: 7.}
{62900}{}{Reinforced jacket}
{62901}{}{Black strong leather jacket, reinforced with various armored plates.}
{63000}{}{Hand made jacket}
{63001}{}{Black strong leather jacket, which is fully made for your body. This jacket will be much more comfortable.}
{63100}{}{Concert outfit}
{63101}{}{In this smoking suit you are irresistible! Wear it, if you want to impress your interlocutor.}
{63200}{}{Leather armor M3}
{63201}{}{Leather armor with an additional layer of protection from the skins of acid geckos. The known properties of these skins make the armor more resistant to damage from fire, acid and plasma.}
{63300}{}{Metal armor Ì2 (reinforced.)}
{63301}{}{Armor, skillfully formed from polished metal plates with additional protection for the knees, elbows and other less protected parts of the body.}
{63400}{}{Metal armor Ì2 (reflective.)}
{63401}{}{Armor, skillfully formed from polished metal plates with a mirror surface reflecting light or similar attacks.}
{63500}{}{Metal armor Ì3}
{63501}{}{Armor, skillfully formed from polished metal plates with many fortifications and a mirror surface.}
{63600}{}{Redneck's key}
{63601}{}{Standard key from one of the doors in Provo.}
{63700}{}{A set of a young nuclear scientist}
{63701}{}{Miniature nuclear power plant. A bit of uranium ore is attached.}
{63800}{}{Key to room 26}
{63801}{}{This is the key to one of the rooms in the hotel "Three Card Monte".}
{63900}{}{Key to room 14}
{63901}{}{This is the key to one of the rooms in the hotel "Three Card Monte".}
{64000}{}{Mysterious Blaster (non functional.)}
{64001}{}{Unusual weapons of unknown origin. On the case stands the mark: "Property of Area 51". For some reason it does not work.}
{64100}{}{Mysterious Blaster}
{64101}{}{Unusual weapons of unknown origin. On the case stands the mark: "Property of Area 51". Min. ST: 3.}
{64200}{}{Cache key}
{64201}{}{The standard key to some lock in the Wind of War.}
{64300}{}{House key}
{64301}{}{The standard key to an apartment house in the Wind of War.}
{64400}{}{Pen key}
{64401}{}{A set of old keys from the slave's pen in The Pound.}
{64500}{}{Trash can}
{64501}{}{Trash can. You can hardly make out the inscription on the sticker: "Keep the streets of your city clean!"}
{64600}{}{Key to room 7}
{64601}{}{This is the key to one of the rooms at the "Silver Legacy" hotel.}
{64700}{}{Functional radio}
{64701}{}{Functional radio model 2043B. Reliable and sturdy.}
{64800}{}{Body of a policeman}
{64801}{}{Body of a policeman, killed by an accurate shot in the head.}
{64900}{}{Bob Neil's key card}
{64901}{}{The key card from the door of Bob Neil's private office in the Hoover Dam.}
{65000}{}{Factory keys}
{65001}{}{A bunch of different keys from the Nuka-Cola factory in Salt Lake City.}
{65100}{}{Mom's key}
{65101}{}{The key to the changing room in the nightclub of New Reno.}
{65200}{}{Letter from a Slum Dweller}
{65201}{}{"Sup, brother! Remember, I was talking about the cretin Ted, from whom we bought the house? He moved to the very backyards of Reno - to the railway station, away from people. And I thought, why don't visit this freak? I need money to pay for rent, and I can't find any..."}
{65300}{}{---}
{65301}{}{---}
{65400}{}{Rod}
{65401}{}{Homemade weapon, created from the sewage grate's steel rod. Min. ST: 1.}
{65500}{}{Message to Patrick}
{65501}{}{A letter from the Mormon community to Patrick. Nothing that you would find out of ordinary.}
{65600}{}{Cigarette case}
{65601}{}{Copper case for cigars. Nothing special.}
{65700}{}{Jazz trumpet}
{65701}{}{A simple-looking copper musical instrument of the alto-soprano sound register. Perfect fit to use in some jazz band.}
{65800}{}{"Nuclear Rush"}
{65801}{}{A strategic game for children. It essentially boils down to obtaining loans and exploring the deposits of nuclear fuel on the game map. As a result, the winner is the one who made the most profits. Alas, as in life, the second one remains a loser.}
{65900}{}{Old pendant}
{65901}{}{Someone lost this family pendant, and you found it. Now it is yours by right.}
{66000}{}{Vortis' key}
{66001}{}{Key to the safe box in the Slavertown.}
{66100}{}{Broken armor}
{66101}{}{Remains of damaged power armor. The disintegration of its power module led to rupture of the armored shell and partial destruction of the supporting structure. Now it's impossible even to put this on.}
{66200}{}{Blueprints T-51. Part 1}
{66201}{}{These blueprints describe only the supporting structure of the T-51b power armor. Rare information.}
{66300}{}{Blueprints T-51. Part 2}
{66301}{}{These blueprints describe only internal automatic modules of the T-51b power armor. Rare information.}
{66400}{}{"Bloatfly"}
{66401}{}{A civilian self-defense plasma pistol. Powered by a non-rechargeable battery that lasts only for 4 shots. Min. ST: 1.}
{66500}{}{Your equipment}
{66501}{}{Your personal items are stored here.}
{66600}{}{Delicate scalpel}
{66601}{}{Very sharp medical instrument for tissue dissection. It is necessary to have a rich surgical experience to manage it, otherwise this item can be dangerous for the owner.}
{66700}{}{Delicate scalpel}
{66701}{}{Very sharp medical instrument for tissue dissection. It is necessary to have a rich surgical experience to manage it, otherwise this item can be dangerous for the owner.}
{66800}{}{Tactical survival knife}
{66801}{}{Designed to perform work on the setting up a camp in the field and to ensure the autonomy of human survival in the "wild" nature.}
{66900}{}{"Lucky"}
{66901}{}{Heavily worn defensive action plasma pistol, first-generation civilian model. Such ones went out of fashion long before the War.}
{67000}{}{"Lucky"}
{67001}{}{Heavily worn defensive action plasma pistol, first-generation civilian model. After cleaning and recalibration, its power and range increased by 10%.}
{67100}{}{Nightshade berries}
{67101}{}{Unripe berries of a wild-growing plant. Sweet and bitter taste, very poisonous.}
{67200}{}{Caravan meal}
{67201}{}{A satisfying meal that can be cooked quickly and easily in the field.}
{67300}{}{"Blood purifier"}
{67301}{}{Traditional medicine, based on healing herbs. Able to remove toxins and radionuclides from organisms and even cure some types of infectious diseases.}
{67400}{}{Concert posters}
{67401}{}{These are hand-written posters of your concert, made in black and white colors. They could be put into good hands to spread throughout Reno.}
{67500}{}{Nut solution}
{67501}{}{A popular analogue of RadAway for intravenous use. It takes some time for full effect.}
{67600}{}{Shell}
{67601}{}{Fired shell from cartridge of caliber .223.}
{67700}{}{Katana}
{67701}{}{Sword from a gift set from the company "Hattori Souvenirs". Although the weapon is clearly inferior in quality to its Japanese progenitor, in a strong hand it can permanently eliminate the enemy from the battlefield, even if he is wearing armor. Min. ST: 4.}
{67800}{}{Machete}
{67801}{}{Someone worked the lawnmower's blade, sharpening one edge, and tightly wrapped the hilt of the brahmin's skin. Min. ST: 5.}
{67900}{}{"Mickey's Revenge" schematics}
{67901}{}{Instructions for creating self-made melee weapons. The developer is a certain Mickey. To whom he was going to take revenge is unknown. What is known is that to create this weapons you need a toaster and some other parts.}
{68000}{}{Robot's remains}
{68001}{}{Guard robot covered with road dust. More precisely - what is left of it.}
{68100}{}{Wright's contract}
{68101}{}{A contract between Mark and Wright, in which executor is forced to bring several boxes of explosives to the customer. Harsh conditions, frankly speaking.}
{68200}{}{Car lights}
{68201}{}{Headlights for a car with 65 Watt single-ended halogen lamps.}
{68300}{}{Car lights}
{68301}{}{Headlights for a car with 65 Watt single-ended halogen lamps.}
{68400}{}{Car awning}
{68401}{}{This is a small car awning, used for strengthening the trunk. Just right for a pickup truck.}
{68500}{}{Car awning}
{68501}{}{This is a small car awning, used for strengthening the trunk. Just right for a pickup truck.}
{68600}{}{Fuel regulator}
{68601}{}{Some drivers installed this regulator, halving fuel consumption, but most drivers did not care how much their cars gobbled up. In the end, fuel is cheap, and there is a lot of it, so why worry?}
{68700}{}{"Savage" with a bandolier}
{68701}{}{Single-shot shotgun with a shortened barrel and ammunition belt on the butt. Although this weapon is already very worn and outdated, it has an indisputable advantage - fast recharge. Min. ST: 4.}
{68800}{}{Damaged robot}
{68801}{}{This robot is damaged and cannot be repaired.}
{68900}{}{Eli's key #10}
{68901}{}{Standart key from a door lock.}
{69000}{}{Slave collar}
{69001}{}{Pre-war manufactured tazer in the form of a collar. In former times it has been used in prisons, now it is a great tool for the slave trade and exploitation.}
{69100}{}{Old revolver}
{69101}{}{Very old model of once popular revolver. Perhaps the museum exhibit. Min. ST: 3.}
{69200}{}{Training rifle}
{69201}{}{Sport model of laser rifle, designed for training and competition in accuracy. Has reduced characteristics in comparison with a conventional laser rifle, and slightly inferior to it in range. Min. ST: 5.}
{69300}{}{Crate}
{69301}{}{Old wooden crate.}
{69400}{}{Crate}
{69401}{}{Old wooden crate.}
{69500}{}{Schematics: "Molotov Cocktail"}
{69501}{}{Instructions for creating incendiary grenades in "home" conditions.}
{69600}{}{Parts}
{69601}{}{Different parts of robots, computers and household appliances.}
{69700}{}{Refrigerator for drinks}
{69800}{}{Refrigerator for drinks}
{69900}{}{Torn page}
{69901}{}{Page from the account book of "Monte" casino. These has records about Murphy's winnings and Irwin's debt in the same day.}
{70000}{}{Schematics: "Powder Grenade"}
{70001}{}{Instructions for creating a homemade grenade with gunpowder and a chemical detonator. Only easily available materials are used in manufacturing.}
{70100}{}{---}
{70200}{}{---}
{70300}{}{---}
{70400}{}{---}
{70500}{}{Mrs. Mordino's finger}
{70501}{}{This pinky belonged to Mr. Mordino's wife.}
{70600}{}{Shock knuckle}
{70601}{}{The predecessor of the police force power fist from the "Punch" company. Used together with a rubber glove.}
{70700}{}{Ultrasound scanner}
{70701}{}{Idle scanner for a metal detector echo sounder. Its purpose is to analyze ultrasonic waves for outputting processed information about environment on a circular digital display.}
{70800}{}{Giblets with spices}
{70801}{}{Brahmin giblets, cooked using special recipe. In addition to the obvious brahmin tissue it can contain literally anything.}
{70900}{}{Ion synthesizer}
{70901}{}{Some kind of pre-war device from the Vault-Tec company.}
{71000}{}{Gas analyzer}
{71001}{}{Some kind of pre-war device from the Vault-Tec company.}
{71100}{}{Pulse modulator}
{71101}{}{Some kind of pre-war device from the Vault-Tec company.}
{71200}{}{Pressure regulator}
{71201}{}{Some kind of pre-war device from the Vault-Tec company.}
{71300}{}{Clothing synthesizer chip}
{71301}{}{Some kind of pre-war device from the Vault-Tec company.}
{71400}{}{"Eldorado" keys}
{71401}{}{A bunch of keys from various doors in "Eldorado" casino.}
{71500}{}{Bertolini's cue}
{71501}{}{Folding cue with a royal pattern in a comfortable leather case. Savagely broken in the middle joint.}
{71600}{}{Bertolini's cue}
{71601}{}{Folding cue with a royal pattern in a comfortable leather case. A metal frame on the damaged part allows you to use the cue for its intended purpose, as before.}
{71700}{}{Bertolini's cue}
{71701}{}{Folding cue with a royal pattern in a comfortable leather case with an "unexpected" second bottom. A metal frame on the damaged part allows you to use the cue for its intended purpose, as before.}
{71800}{}{Cadaveric amphetamine}
{71801}{}{The dose of hyperbolizing substance synthesized from the plasma of highly irradiated blood, endorphins and various enzymes of the humanoid organism.}
{71900}{}{Beer with flavor}
{71901}{}{Some sort of homemade beer. Differs a bit by strange burning taste.}
{72000}{}{Broken laser pistol}
{72001}{}{Laser pistol Wattz 1000 civilian model. For some reason it doesn't work.}
{72100}{}{Chemicals}
{72101}{}{A set of chemicals for a wide range of applications. Judging by the label on ampoules and boxes, the package is of military origin.}
{72200}{}{Corrupted micro fusion battery}
{72201}{}{This micro fusion battery has been damaged, so its impossible to use at the moment.}
{72300}{}{Condoms (poison.)}
{72301}{}{These are condoms of "Jimmy Hats" brand. A very reliable brand, but a small hole was somehow discovered on its cover... perhaps from a needle.}
{72400}{}{Thompson Depression}
{72401}{}{This is a kind of depression measuring unit of Thompson's. The poor fella learned of the demise of his top bitch...}
{72500}{}{A Pip-Boy empathy amplifier}
{72501}{}{This amplifier consists of acoustic and optical sensors, a disc with a program and a cord. Its purpose - to analyze the facial expressions and voices of interlocutors for determining their emotional state.}
{72600}{}{Broken Pip-Boy}
{72601}{}{Remains of destroyed Pip-Boy 2000 portable computer. The monitor is broken, the case is crumpled, some buttons fell out. Obviously, this item is not subjected to repair.}
{72700}{}{Tire armor}
{72701}{}{Pretty awkward and disgustingly smelling rubber armor. But is this important when it comes to the impact of electricity or radiation?}
{72800}{}{Electric spear}
{72801}{}{An effective police tool to disperse a mob of rebels. Repeatedly used before the war. Min. ST: 4.}
{72900}{}{Pistol 10mm #80}
{72901}{}{Obsolete model of self-loading pistol Colt 6520 caliber 10mm. Judging by the markings on the body, it was produced in 2051. Min. ST: 3.}
{73000}{}{Pistol 10mm with flashlight}
{73001}{}{Police model of self-loading pistol Colt 6520 caliber 10mm, equipped with a barrel tactical flashlight. Though, sometimes it doesn't work - you need to shake it. Min. ST: 4.}
{73100}{}{Locked case}
{73101}{}{Durable metal case of a business man. There is probably something valuable inside, because it is locked with a combination lock.}
{73200}{}{A Pip-Boy anatomical analyzer}
{73201}{}{This amplifier consists of a disc with a program, a cord and a sensor. Its purpose is to analyze the anatomy of an enemy, determining his most vulnerable spots.}
{73300}{}{Chrome glasses}
{73301}{}{Glasses with chrome plated glasses.}
{73400}{}{Armored plates}
{73401}{}{Protective polymeric plates, made, apparently, from the remains of destroyed combat armor.}
{73500}{}{Body armor Ì2}
{73501}{}{A light army bulletproof vest with elements to quickly unload all sorts of junk. Protects only a part of the torso, since it was meant to be used by Emergency Response Units members. Some of armored plates had been replaced by more sturdy ones.}
{73600}{}{Winchester Pistol}
{73601}{}{This gun is made by analogy with a plasma rifle of the "Winchester Arms" company. Gained no popularity because of competition with plasma pistols from the Gaston Glock AI. Min. ST: 5.}
{73700}{}{Awarded Pistol}
{73701}{}{Nominal pistol Colt 6520 made of alloy steel. The use of more durable hardened alloys makes this weapon shoot with greater lethal force, but also makes it slightly heavier. Min. ST: 4.}
{73800}{}{Heavy Coyote Spear}
{73801}{}{Heavy spear of the Coyotes hunters. Apparently, as a cutting part it uses massive, sharpened blade from some agricultural machinery. Min. ST: 5.}
{73900}{}{Combat knife of Coyotes}
{73901}{}{Blade weapon of the Coyotes hunters. Apparently made from the straightened cultivator blade. Min. ST: 4.}
{74000}{}{Coyote Truncheon}
{74001}{}{Heavy steel arms' weapon of Coyote hunters. Apparently made of a grouser and a metal pipe, bolted together. Min. ST: 5.}
{74100}{}{Ultra-thermal mixture}
{74101}{}{A termite mixture complemented with unknown components. When burning, gives off a staggering amount of heat, thereby silently and smokelessly melting everything around. Do not forget the lighter!}
{74200}{}{Nelson's damaged weapon}
{74201}{}{This pump shotgun was badly damaged. It will take a lot of work to restore it to working condition.}
{74300}{}{Cutlet from the meat of "earth dragon"}
{74301}{}{Stuffed meat of "earth dragons" with greens, wrapped in a tortilla. This food has more protein than a brahmin steak.}
{74400}{}{Road sign}
{74401}{}{The warning for drivers on this rusted sign still barely seen. It has nothing to do with you.}
{74500}{}{Torn leather jacket}
{74501}{}{Leather jacket in a terrible state. It contains many holes, one arm cut off, and the back is torn by claws of small animals. However, it is still possible to repair, if you try hard enough.}
{74600}{}{Emergency exit key}
{74601}{}{Standard key from the emergency exit door at Stryker's headquarters.}
{74700}{}{Hangar key}
{74701}{}{Standard key from the hangar door in the ranch of Oliver Luciano.}
{74800}{}{Schematics: "Kubotan"}
{74801}{}{Pre-war police instructions for assembling and maintaining the kubotan, with a foldout describing the art of its application. This self-defense weapon is not difficult to build, but without the proper skills it will be useless.}
{74900}{}{Eli's key #9}
{74901}{}{Standard door lock key.}
{75000}{}{Mastery of the kubotan}
{75001}{}{Learning to use the kubotan in combat allows you to inflict more damage to the enemy.}
{75100}{}{Remains of Major Kong}
{75101}{}{The withered remains of a man dressed in army vest and clutching a cowboy hat in his hand. Judging by the skits, all this once was Major Kong.}
{75200}{}{Knapsack Flamethrower}
{75201}{}{Flamethrower model Flare-450, equipped with a large knapsack. Shoots a short jet of a flammable mixture. A special fuel is necessary. Min. ST: 6.}
{75300}{}{Poker chip "El Capitan"}
{75400}{}{Poker chip "Eldorado"}
{75500}{}{Poker chip "Silver Legacy"}
{75600}{}{Poker chip "Monte"}
{75700}{}{Gold poker chip}
{75701}{}{Looking at this beautiful thing you strongly assure yourself that now you'll never lose playing poker or roulette!}
{75800}{}{"Atomic cocktail"}
{75801}{}{Strong alcoholic drink, according to the pre-war description, clearly diluted with something special.}
{75900}{}{Recipe: "Atomic Cocktail"}
{75901}{}{The recipe for making an "Atomic cocktail". You won't be able to achieve pre-war quality, but it won't be bad either.}
{76000}{}{Worn minigun}
{76001}{}{Minigun CZ53 Rockwell in very poor condition. Min. ST: 7.}
{76100}{}{Ñompromising evidence on Mordino}
{76101}{}{This is a record of the debate at Stryker's meeting, during which it was decided to remove Mr. Mordino, when the power in Reno will be seized by the Stryker's group. Mordino certainly will love to hear this.}
{76200}{}{"Gonzo style"}
{76201}{}{With this quality combat knife you can easily reveal any pretense and lie, if you have enough skills. Min. ST: 1.}
{76300}{}{Biker's switchblade}
{76301}{}{The knife that was found in the pocket of your jacket. The blade is shot out by a spring if button on the handle is pressed. Min. ST: 1.}
{76400}{}{Hormonal explosion}
{76500}{}{Extraction window}
{76600}{}{Recipe: "Root beer"}
{76601}{}{The recipe for the making of root beer.}
{76700}{}{EMP-glove}
{76701}{}{Power knuckle equipped with a generator of electromagnetic impulse. Min. ST: 2.}
{76800}{}{"Fiery Kiss"}
{76801}{}{Hydraulic fist consisting of a fireproof glove, a gas cylinder and a sprayer with a piston mechanism. Upon impact, the mechanism sprays fuel onto the victim's body and then ignites it. Min. ST: 2.}
{76900}{}{Prospector's corpse}
{76901}{}{Everything says that this man wasn't killed by local rodents.}
{77000}{}{Legendary scorpion's shell}
{77001}{}{Very strong chitinous shell.}
{77100}{}{Chitinous armor}
{77101}{}{Your personal armor, created from the shell of a legendary scorpion.}
{77200}{}{The remains of the worker}
{77201}{}{These remains have been lying here for many years. No traces of violent death.}
{77300}{}{Prospector's remains}
{77301}{}{This is all what's left of the prospector, he wanted to feast on the local treasures. But in the end somebody feasted him.}
{77400}{}{Sink}
{77401}{}{Porcelain sink, which is barely able to cope with its duties.}
{77500}{}{Sink}
{77501}{}{Porcelain sink, which is barely able to cope with its duties.}
{77600}{}{Samples}
{77601}{}{Sterile set for collecting blood samples of mutated animals. Issued by Dr. Willmouth.}
{77700}{}{Corpse}
{77701}{}{Apparently, this corpse will remain lying under the sun, if someone does not bury it, following local customs.}
{77800}{}{Caravan merchant's corpse}
{77900}{}{Gauss pistol PPK5}
{77901}{}{Early model of handgun, based on a principle of electromagnetic acceleration. Shortly after its release, more advanced models were developed, so PPK5 quickly went out of use. Min. ST: 4.}
{78000}{}{Recipe: "Stimpak"}
{78001}{}{Recipe for making stimpak and a super stimpak.}
{78100}{}{Recipe: "Doctor's Bag"}
{78101}{}{Recommendations for putting together a doctor's suitcase in conditions of modern Wasteland.}
{78200}{}{Semi-eaten corpse}
{78201}{}{Remains of a man in a vault suit. Half of the body was eaten by cannibals.}
{78300}{}{Blood analyzer}
{78301}{}{This device measures sample of your blood, showing level of infection and poisoning.}
{78400}{}{Thompson's Plasmogun}
{78401}{}{Impulse weapon prototype by Thompson & Glock. Developed as an assault weapon for army regular forces, but didn't have time to enter mass production. Factory stamp "Lucky Tom 2029". Min. ST: 6}
{78500}{}{The list of Nisckiguan}
{78501}{}{A casually scrawled list of items needed for the operation: 1) pure water; 2) dope herb, alcohol or pain reliever; 3) sharp knife; 4) pliers or pincers ; 5) first aid kit with bandages; 6) öHealing powder or stimpaks.}
