#---------------------------------------------------------
#                QUEST DESCRIPTION IN PIP-BOY
# (каждый новый раздел начинать с 100 и кратных ему чисел)
#---------------------------------------------------------



#---------------------------------------------------------
# Vault 8
#---------------------------------------------------------

{100}{}{Retrieve the device that have been stolen by biker}
{101}{}{Pursue the kidnappers of the Overseer}
{102}{}{Fulfill your mission in the government vault}
{103}{}{}
{104}{}{}
{105}{}{Complete the warehouse's special assignment}
{106}{}{Bring Sam a porn magazine}
{107}{}{Find the missing scout robot}
{108}{}{Decipher deputy Sheriff’s disk}
{109}{}{Learn more about Gerlach's community}
{110}{}{Destroy Gerlach's community}
{111}{}{Spy on a "suspicious citizens" couple}
{112}{}{Collect blood samples of pigrats, coyotes and geckos for doctor Willmouth}

{120}{}{Get up on feet: talk to Graves, Willmouth, take your gear from the warehouse}
{121}{}{Biker chase: learn more about Jay in Black Rock}
{122}{}{Biker chase: learn more about Jay in New Reno}
{123}{}{Biker chase: contact the biker gang}
{124}{}{Biker chase: receive a message in Hawthorne}
{125}{}{Biker chase: find Jay in Hawthorne}
{126}{}{Get a signal jammer in Hawthorne}
{127}{}{Get rid of the tracker inside your Pip-Boy}
{128}{}{Expose doctor Willmouth}
{129}{}{Find information about project Vault 8 in Area 51}
{130}{}{}
{131}{}{}
{132}{}{}
{133}{}{}
{134}{}{Discover the true purpose of Vault 8}
{135}{}{Blow up the government vault}

#---------------------------------------------------------
# Wind of War
#---------------------------------------------------------

{200}{}{Deal with the local thugs that attacked you}
{201}{}{The intendant ordered 30 bottles of beer}
{202}{}{Help the prisoner escape}
{203}{}{Robert and Jessica want to run away from the settlement}
{204}{}{Find memorial information in Hawthorne}
{205}{}{Punish the soldiers, that beat the caravan merchant}
{206}{}{Find survivors from the "Speed Hawk" caravan}
{207}{}{Copy radio frequencies for the spy or tell about him to the Military}
{208}{}{Investigate the incident at the post and report to Wesker}
{209}{}{Regain the farmer's trust}

#---------------------------------------------------------
# Gerlach
#---------------------------------------------------------

{300}{}{Fix the water pump}
{301}{}{Save Steve from execution}
{302}{}{Move to Vault City}
{303}{}{Gecko hunting: the trial}
{304}{}{Gecko hunting: egg collection}
{305}{}{Hunt the Legendary Scorpion}

#---------------------------------------------------------
# Black Rock
#---------------------------------------------------------

{306}{}{Save the community from the "contagion"}
{307}{}{Deal with runaway slaves}
{308}{}{Investigate the brahmin's disappearance}
{309}{}{Investigate the delivery man's disappearance}

#---------------------------------------------------------
# Lovelock
#---------------------------------------------------------

{400}{}{Destroy raiders terrorizing the Cheyenne tribe}
{401}{}{Neutralize Big Louie}
{402}{}{Defeat Makozid in a fistfight}
{403}{}{Ogima requests to fix the water tank}
{404}{}{Clear plantation of carnivorous plants}
{405}{}{"Help" Mold, the drug addict}
{406}{}{Return to Niskigvan his belongings, taken away by a raider named Furiouser}
{407}{}{Acabidab asks to find Gizhiyash in New Reno}
{408}{}{Find a way to cure poor Makkon}

{410}{}{Louie: Find a way to get to Hawthorne}
{411}{}{Louie: Collect and bring the toll from Stryker}
{412}{}{Louie: Kill the traitor named Balder}
{413}{}{Louie: Take revenge on drug dealer Solomon in New Reno}
{414}{}{Louie: Stop the drug courier from Vegas}
{415}{}{Louie: Organize the show in Vegas}

#---------------------------------------------------------
# Помощь при нажатии F1
#---------------------------------------------------------

{500}{}{[ИГРА]}
{501}{}{- Уменьшить яркость}
{502}{}{+ Увеличить яркость}
{503}{}{F1 Помощь}
{504}{}{F2 Уменьшить громкость}
{505}{}{F3 Увеличить громкость}
{506}{}{F4 Сохранить игру}
{507}{}{F5 Загрузить игру}
{508}{}{F6 Быстрое сохранение}
{509}{}{F7 Быстрая загрузка}
{510}{}{F10 Завершить игру}
{511}{}{F12 Сделать скриншот}
{512}{}{Ctrl+P Пауза}
{513}{}{Ctrl+R Тест. режим в гл.меню}

{514}{}{[ИНТЕРФЕЙС]}
{515}{}{М/ПКМ Смена курсора}
{516}{}{О/Esc Настройки}
{517}{}{P Pip-Boy}
{518}{}{Z Часы в Pip-Boy}
{519}{}{I Рюкзак}
{520}{}{Tab Карта местности}

{521}{}{[ДЕЙСТВИЯ]}
{522}{}{A Начать бой}
{523}{}{Space Закончить ход в бою}
{524}{}{Enter Закончить бой}
{525}{}{B Переключить предмет}
{526}{}{N Сменить режим предмета}
{527}{}{< Повернуться по ЧС}
{528}{}{> Повернуться против ЧС}
{529}{}{Home Центрировать экран на герое}

{530}{}{[НАВЫКИ]}
{531}{}{S панель навыков}
{532}{}{1 Скрытность}
{533}{}{2 Взлом}
{534}{}{3 Кража}
{535}{}{4 Диверсия}
{536}{}{5 Первая помощь}
{537}{}{6 Доктор}
{538}{}{7 Эрудиция}
{539}{}{8 Ремонт}

#---------------------------------------------------------
# NPP Poseidon Oil
#---------------------------------------------------------

{600}{}{}

#---------------------------------------------------------
# Ailey settlement
#---------------------------------------------------------

{700}{}{}

#---------------------------------------------------------
# New Reno
#---------------------------------------------------------

{800}{}{Patrick asks to cure Itchie}
{801}{}{Patrick asks to return the package}
{802}{}{Patrick needs help in the organization of film exhibition}
{803}{}{Help Harding with his sufferings}
{804}{}{Deal with the debt of Mrs. Clover}
{805}{}{Find the missing prospectors from the slums}
{806}{}{Find and punish graffiti maker}
{807}{}{Bring Ted Bundy to justice}
{808}{}{Solve the mystery of Ted Bundy's photo}
{809}{}{Punish fake bikers}
{810}{}{Find the source of bad rumors about bikers}
{811}{}{Become a legendary champion of New Reno ring}
{812}{}{Become a star in New Reno}
{813}{}{Carry out the Solomon's dirty task}
{814}{}{Deliver a comedian from Vegas to "Cotton" club}
{815}{}{Meet Nick Hauer at "Silver" hotel}
{816}{}{Arrange the escape of Deveraux family from the city}
{817}{}{Install bugs at the "Eldorado" casino}
{818}{}{Get information about food shipments}

{820}{}{Wright: explore the situation in Uranium City}
{821}{}{Wright: fulfill the C-4 delivery}
{822}{}{Wright: recapture the mine from competitors}
{823}{}{Wright: hunt down a strange guy in the slums}
{824}{}{Wright: have a meeting with Oliver Luciano}
{825}{}{Bertolini: meet with the informant at the ranch}
{826}{}{Bertolini: set the restaurant against the ranch}
{827}{}{Bertolini: put Luciano out of business without killing him}
{828}{}{Bertolini: offer assistance to Luciano}
{829}{}{Bertolini: follow Huey}
{830}{}{Luciano: help Johnny Chase}
{831}{}{Luciano: frame "Eldorado" casino}
{832}{}{Luciano: frame "Eldorado" casino (2)}
{833}{}{Luciano: steal a briefcase with money from Bertolini}
{834}{}{Luciano: provoke a conflict between gangsters}
{835}{}{Luciano: make a secret deal in the outskirts of the city}
{836}{}{Stryker: eliminate Patrick the Mormon}
{837}{}{Stryker: get chemicals from dealer}
{838}{}{Stryker: gather intelligence in the Thompson's headquarters}
{839}{}{Stryker: eliminate Betty Page}
{840}{}{Stryker: prepare the invasion to Thompson's}
{841}{}{Thompson: punish street thugs}
{842}{}{Thompson: investigate the attack on the propaganda team}
{843}{}{Thompson: persuade Mordino to cooperate}
{844}{}{Thompson: sabotage Striker's deal}
{845}{}{Thompson: prepare the invasion to Stryker's}

#---------------------------------------------------------
# Bridgeport
#---------------------------------------------------------

{900}{}{Help Dante to complete challenges (needs gun and painkillers)}
{901}{}{Convince Dante not to join the biker gang}
{902}{}{Get brahmin to the corral}
{903}{}{Cure the child by yourself or bring medical supplies}
{904}{}{Help to equip caravan from New Reno to Bridgeport}
{905}{}{Find the missing resident}
{906}{}{Bring back electricity}
{907}{}{Get the village rid of biker gang}
{908}{}{}
{909}{}{}

#---------------------------------------------------------
# Vegas
#---------------------------------------------------------

{1100}{}{Investigate the latest crimes in the city by the request of mayor}
{1101}{}{Find archivist's missing daughter}
{1102}{}{Sam Phillips is accused of spreading poison}
{1103}{}{Help the police to send Sam Phillips to prison}
{1104}{}{Get proof of freaks innocence}
{1105}{}{Help to exile freaks}
{1106}{}{Secretly plant drugs to the freaks hotel}
{1107}{}{Get Bob Neil's personal gun for Wallace}
{1108}{}{Bob Neil made a counter-offer}
{1109}{}{Solve the problem with workers at the Hoover Dam}
{1110}{}{Investigate the attack on the "Speed Hawk" caravan}
{1111}{}{Help slaves to escape the pen}
{1112}{}{Turn the Black Caravan over to the police}
{1113}{}{Help the police to raid the Pound}
{1114}{}{Become the legendary ring champion in Vegas}
{1115}{}{Get into Vegas drug lab}
{1116}{}{Eric asks to get his brother out of imprisonment}
{1117}{}{Pizza delivery: casino, shop and ring}
{1118}{}{Deal with thief Kevin's debt}
{1119}{}{Orris asked to deal with Murphy's problem}

#---------------------------------------------------------
# Salt Lake
#---------------------------------------------------------

{1500}{}{Fix the on-board computer of the train}
{1501}{}{Machinist is needed for train operation}
{1502}{}{Artesian tower needs water filter}
{1503}{}{Case of missing dog}
{1504}{}{Deal with Mark's problem}
{1505}{}{Execute the "robbery of the century" in Salt Lake}
{1506}{}{Help beggar to get a job}
{1507}{}{Get Nuka-Cola selling license}
{1508}{}{Make a diversion on Nuka-Cola factory}
{1509}{}{Nuka-Cola: get a deal with "Cotton" club}
{1510}{}{Nuka-Cola: get a deal with "Silver" restaurant}
{1511}{}{Nuka-Cola: get a deal with "Hard Rock" cafe}
{1512}{}{Nuka-Cola: get a deal with the Wind of War}
{1513}{}{Fix automated logical controller for Nuka-Cola factory}
{1514}{}{Deal with Nuka-Cola merchant}
{1515}{}{Get Gary Gilmore to justice}
{1516}{}{Slaughter Provo's population}
{1517}{}{Kill Salt Lake City sheriff on Provo's request}
{1518}{}{Return the keys to Nuka-Cola factory}
{1519}{}{By any means take the encoder from caravan merchant}

#---------------------------------------------------------
# Reserv
#---------------------------------------------------------

{1600}{}{}

#---------------------------------------------------------
# Government Vault
#---------------------------------------------------------

{1700}{}{}

#---------------------------------------------------------
# Reserv
#---------------------------------------------------------

{1800}{}{}

#---------------------------------------------------------
# Uranium City
#---------------------------------------------------------

{1900}{}{Get rid of mutants in Uranium City}
{1901}{}{Change the mine owner}
{1902}{}{Return the workers in Uranium City: administrator}
{1903}{}{Return the workers in Uranium City: machine operator}
{1904}{}{Return the workers in Uranium City: supplier}
{1905}{}{Return the workers in Uranium City: cabaret girl}
{1906}{}{Courier delivery of Lewis Birch's report}
{1907}{}{Become Uranium City's sheriff}
{1908}{}{Carl asks to find a fuse}

#---------------------------------------------------------
# Reserv
#---------------------------------------------------------

{2000}{}{}

#---------------------------------------------------------
# Reserv
#---------------------------------------------------------

{2100}{}{}

#---------------------------------------------------------
# Car outta Gas Quests
#---------------------------------------------------------

{2200}{}{}

#---------------------------------------------------------
# Reserv
#---------------------------------------------------------

{2300}{}{}

#---------------------------------------------------------
# Provo
#---------------------------------------------------------

{2400}{}{}

#---------------------------------------------------------
# Reserv
#---------------------------------------------------------

{2500}{}{}

#---------------------------------------------------------
# Reserv
#---------------------------------------------------------

{2600}{}{}

#---------------------------------------------------------
# Desert Encounter Quests
{2700}{}{}

# Mountain Encounter Quests
{2800}{}{}

# Ruined City Encounter Quests
{2900}{}{}

# Coast Encounter Quests
{3000}{}{}

#---------------------------------------------------------
# Reserv
#---------------------------------------------------------
{3200}{}{}

#---------------------------------------------------------
# Car
#---------------------------------------------------------

{3300}{}{Get your own car}
{3301}{}{Improve the pickup with "Chryslus Motors" catalogue upgrades}
{3302}{}{Repaint the pickup's body}
{3303}{}{Expand and reinforce the trunk}
{3304}{}{Install "gravi-plates"}
{3305}{}{Decrease power consumption with fuel regulator}
{3306}{}{Increase pickup's speed capacity with the help of biker in Battle Mountain}
{3307}{}{Restore pickup's headlights}
{3308}{}{Take a hitchhiker to Vegas}
