#
# 北北北北北北北北北北北北北北北北北北北北北北北北北北北北北北北北北北北北北北?
#
# Text labels and messages used by town and world map
#
# 北北北北北北北北北北北北北北北北北北北北北北北北北北北北北北北北北北北北北北?
#

# Vault 8
{200}{}{Wasteland}
{201}{}{Vault City}
{202}{}{Vault Doors}
{203}{}{Opal Mine}
{204}{}{Vault 8}
{205}{}{Laboratory}
#
# Wind of War
{210}{}{Free Parking}
{211}{}{Vault}
{212}{}{Non-residential area}
#
# Sigma base
{220}{}{Error: empty}
{221}{}{Error: empty}
{222}{}{Error: empty}
{223}{}{Error: empty}
{224}{}{(Error: empty)}
{225}{}{(Error: empty)}
#
# Cheyenne
{230}{}{Tribal Camp}
{231}{}{Raiders' Base}
{232}{}{Plantations}
{233}{}{Radio Station}
#
# Fake Vault 13 B
{240}{}{Vault 15}
#
# Gecko
{250}{}{Settlement}
{251}{}{Power Plant}
{252}{}{Junkyard}
{253}{}{Error: empty}
#
# Ailie
{260}{}{Railway Junction}
{261}{}{Residential}
{262}{}{Temple}
{263}{}{Weather Station}
#
# New Reno
{270}{}{Hotel 'Silver'}
{271}{}{Eldorado}
{272}{}{Stadium}
{273}{}{Railway Station}
{274}{}{Luciano's Ranch}
{275}{}{Boxing Arena}
{276}{}{Assault Location}
{277}{}{City Hall}
{278}{}{Outdoor Cinema}
{279}{}{Abandoned Farm}
#
# Area 51
{280}{}{Airplane Landing Area}
{281}{}{Barracks}
{282}{}{Hangar}
#
# Bridgeport
{290}{}{Bridgeport}
#
# New Vegas
{300}{}{Parking Lot}
{301}{}{Hoover Dam}
{302}{}{Clean City}
{303}{}{'Hard Rock' Cafe}
{304}{}{Slavertown}
{305}{}{Dead Hotel}
#
# Provo
{310}{}{Provo District}
#
# Hawthorne
{320}{}{Railway Station}
{321}{}{Dead City}
{322}{}{Garrison Territory}
{323}{}{Hangar V9}
{324}{}{Reactor Facilities}
#
# West Wendover
{330}{}{Downtown}
{331}{}{Workshop}
{332}{}{Big Hangar}
{333}{}{The Association}
{334}{}{Hunting Lands}
{335}{}{Ruins of Wendover}
#
# Salt Lake
{340}{}{Business Center}
{341}{}{Renaissance Square}
{342}{}{Railroad Depot}
{343}{}{Wastewater Canyon}
{344}{}{Temple}
{345}{}{Slums}
{346}{}{Nuka-Cola Factory}
#
# Rabie
{350}{}{Hut}
#
# Vault X
{360}{}{Stop}
{361}{}{Vault}
{362}{}{Vault Entrance}
{363}{}{Temporary Stop}
{364}{}{Presidential Level}
#
# Gerlach
{370}{}{Settlement}
{371}{}{Hunting Grounds}
#
# Uranium-City
{380}{}{Workers' Settlement}
#
# Vegas DrugSet
{390}{}{The Pound}
#
# Battle-Mountain, Radar
{400}{}{Main Street}
{401}{}{Biker Camp}
#
# Car Out of Gas
{410}{}{Car Outta Gas}
#
# Destroyed Vault City
{420}{}{Destroyed City}
#
# ???
{430}{}{Desert}
#
# Wind of War
{440}{}{Ambushes of Patrols}
#
# Black-Rock
{450}{}{Settlement}
{451}{}{Black-Rock Caves}
#
# Random Encounter Desert
{460}{}{Desert}
{461}{}{Desert}
{462}{}{Desert}
{463}{}{Desert}
{464}{}{Abandoned Camp}
{465}{}{Abandoned Farm}
{466}{}{Cactus Field}
{467}{}{Black Forest}
{468}{}{Black Forest}
{469}{}{Black Forest}
#
# Random Encounter Mountain
{470}{}{Mountain}
{471}{}{Cavern}
{472}{}{Mountain}
{473}{}{Cavern}
{474}{}{Cavern}
{475}{}{Cavern}
{476}{}{Cavern}
{477}{}{Cavern}
{478}{}{Mountain}
{479}{}{Mountain}
#
# Random Encounter City
{480}{}{Ruined City}
{481}{}{Ruined City}
{482}{}{Ruined City}
{483}{}{Ruined City}
{484}{}{Ruined City}
{485}{}{Ruined City}
{486}{}{Ruined City}
{487}{}{Ruined City}
{488}{}{Ruined City}
#
# Random Encounter Coast
{490}{}{Coastline}
{491}{}{Coastline}
{492}{}{Coastline}
{493}{}{Coastline}
{494}{}{Coastline}
{495}{}{Coastline}
{496}{}{Coastline}
{497}{}{Coastline}
{498}{}{Coastline}
{499}{}{Coastline}
#
# PepGaz
{500}{}{Gas Station}
#
# Special Encounter: Roads
{510}{}{Crossroads.}
#
# Special Encounter: AnalDen
{520}{}{Big Hole.}
#
# Special Encounter: MineField
{521}{}{Dump of tires.}
#
# Special Encounter: Crashed Federation Shuttle
{530}{}{Tanker in the Desert.}
#
# Special Encounter: Unwashed Villagers
{540}{}{Desert}
#
# Special Encounter: Interplay Office
{550}{}{Lost Office.}
#
# Special Encounter: Cafe
{560}{}{Cafe "New Hope".}
#
# Special Encounter: Big Egg
{570}{}{Desert}
#
# Special Encounter: Bobby
{580}{}{Desert}
#
# Special Encounter: HomeRoad
{590}{}{House on Wheels.}
#
# Special Encounter: Bus Of Ken
{600}{}{"Furthur".}
#
# Rangers post
{610}{}{Abandoned Ranger's Station.}
#
# Special Encounter: Picnic
{620}{}{Picnic Area.}
#
# Caravan Encounters
{630}{}{Desert}
{631}{}{Mountain}
#
# Atomic
{640}{}{"Dear John".}
#
# Harrelson
{650}{}{Harrelson's Shelter}
#
# Shadow Areas (Those which fit nowhere else)
{660}{}{Coastline}
{661}{}{Coastline}
{662}{}{Desert}
{663}{}{Desert}
{664}{}{Desert}
{665}{}{Mountain}
{666}{}{Mountain}
{667}{}{Desert}
{668}{}{Parking Lot}
{669}{}{Frightening Silence}
#
# Environmental Protection Agency
{670}{}{Road}



#
# Terrain type names for world map hover button
#
{1000}{}{Desert}
{1001}{}{Mountains}
{1002}{}{City}
{1003}{}{Coast}
{1004}{}{Unknown}  # Unknown/visited city


# Misc messages
{1500}{}{You gained 10,000 experience points!}
{1501}{}{Ruins}
{1502}{}{The car is out of power.}
{1503}{}{This is a car.  It doesn't look like it's running.}


#
# Worldmap Encounter messages
#

{2998}{}{You encounter:}
{2999}{}{Do you wish to encounter:}

# Encounter Table 0
{3000}{}{A party of raiders.}
{3001}{}{Some radscorpions.}
{3002}{}{Giant rats.}
{3003}{}{A merchant's party.}
{3004}{}{<Special>}

# Encounter Table 1
{3050}{}{A party of raiders.}
{3051}{}{A swarm of mantises.}
{3052}{}{A group of geckos.}
{3053}{}{A group of mole-rats.}
{3054}{}{A group of radscorpions.}
{3055}{}{A group of giant rats.}
{3056}{}{A merchant's party.}
{3057}{}{<Special>}

# Encounter Table 2
{3100}{}{A party of raiders.}
{3101}{}{A group of radscorpions.}
{3102}{}{A group of giant rats.}
{3103}{}{A merchant party.}
{3104}{}{<Special>}

# Encounter Table 3
{3150}{}{A party of raiders.}

# Encounter Table 4
{3200}{}{A party of raiders.}

# Encounter Table 5
{3250}{}{A party of raiders.}

# Encounter Table 6 -- VCTY_M (Mountains around vault 8)
{3300}{}{Group of silver geckos.}
{3301}{}{Flock of geckos.}
{3302}{}{Group of pests.}
{3303}{}{Small group of mole-rats.}
{3304}{}{Small group of radscorpions.}
{3305}{}{Vault City patrol.}
{3306}{}{Vault City patrol fending off A pack of geckos.}
{3307}{}{Vault City patrol fighting with radscorpions.}

# Encounter Table 7 -- VCTY_D (Mountains around vault 8)
{3350}{}{Group of silver geckos.}
{3351}{}{Flock of geckos.}
{3352}{}{Group of pests.}
{3353}{}{Small group of mole-rats.}
{3354}{}{Small group of radscorpions.}
{3355}{}{Herd of brahmin.}
{3356}{}{A pack of coyotes.}
{3357}{}{Herd of brahmin, fending off geckos' attack.}
{3358}{}{Giant Egg.}

# Encounter Table 8 -- BLRCK
{3400}{}{Group of silver geckos.}
{3401}{}{Group of pests.}
{3402}{}{Small group of mole-rats.}
{3403}{}{Small group of radscorpions.}
{3404}{}{Herd of wild brahmin.}
{3405}{}{A pack of coyotes.}
{3406}{}{Herd of brahmin, fending off geckos' attack.}
{3407}{}{Hunter of desert iguanas.}

# Encounter Table 9 -- SGMA_M
{3450}{}{Cleaner robots.}
{3451}{}{Group of pests.}
{3452}{}{Small group of mole-rats.}
{3453}{}{Small group of pig-rats.}
{3454}{}{Small group of radscorpions.}
{3455}{}{Herd of wild brahmin.}
{3456}{}{A pack of wolves.}
{3457}{}{Cafe "New Hope".}
{3458}{}{Crossroads.}
{3459}{}{Big Hole.}
{3460}{}{Picnic Area.}
{3461}{}{House on Wheels.}
{3462}{}{"Furthur".}
{3463}{}{Giant Egg.}

# Encounter Table 10 -- SGMA_D
{3500}{}{Group of carnivorous plants}
{3501}{}{Group of pests.}
{3502}{}{Small group of mole-rats.}
{3503}{}{Small group of pig-rats.}
{3504}{}{Small group of radscorpions.}
{3505}{}{Herd of wild brahmin.}
{3506}{}{A pack of wolves.}
{3507}{}{Hunters' squad.}
{3508}{}{Hunters' squad fighting with radscorpions.}
{3509}{}{Hunters' squad fighting with mole-rats.}
{3510}{}{Hunters' squad repulsing attack of wolves' A pack.}
{3511}{}{Herd of brahmin, fending off wolves.}
{3512}{}{Legendary radscorpion.}
{3513}{}{Lost Office.}
{3514}{}{Crossroads.}
{3515}{}{Cafe "New Hope".}
{3516}{}{Big Hole.}
{3517}{}{Picnic Area.}
{3518}{}{House on Wheels.}
{3519}{}{"Furthur".}
{3520}{}{Giant Egg.}
{3521}{}{"Dear John".}
{3522}{}{A pack of coyotes.}
{3523}{}{Water!}

# Encounter Table 11 -- SGMA_T
{3550}{}{Small group of radscorpions on the road.}
{3551}{}{Herd of brahmin crossing the road.}
{3552}{}{A pack of wild dogs running down the road.}
{3553}{}{Group of fishermen coming back from fishing.}
{3554}{}{Group of immigrants.}
{3555}{}{Group of farmers.}
{3556}{}{Gang of robbers hiding in ambush.}
{3557}{}{Gang of raiders hiding in ambush.}
{3558}{}{Group of hunters, fending off raiders' attack.}
{3559}{}{Group of hunters, fending off robbers' attack.}
{3560}{}{Group of hunters, fending off radscorpions' attack.}
{3561}{}{Group of hunters, fending off robbers' attack.}
{3562}{}{Group of hunters, fending off radscorpions' attack.}
{3563}{}{Caravan, wandering along the road.}
{3564}{}{Crossroads.}
{3565}{}{Lost Office.}
{3566}{}{Big Hole.}
{3567}{}{Cafe "New Hope".}
{3568}{}{House on Wheels.}
{3569}{}{"Furthur".}
{3570}{}{Hitchhiker.}
{3571}{}{Cheerful Bobby.}

# Encounter Table 12 -- SALT_O
{3600}{}{Group of pests.}
{3601}{}{A pack of wild dogs.}
{3602}{}{Herd of wild brahmin.}
{3603}{}{A group of acid geckos.}
{3604}{}{Hunters' squad.}
{3605}{}{Group of hunters fighting against pests.}
{3606}{}{Group of hunters fending off wild dogs' attack.}
{3607}{}{Group of hunters fending off bandits' attack.}
{3608}{}{Group of bandits.}
{3609}{}{Group of bandits fending off wild dogs' attack.}
{3610}{}{Escaped convicts.}
{3611}{}{Punks from Salt Lake City.}

# Encounter Table 13 -- SALT_T
{3650}{}{Small group of pests stuck on the road.}
{3651}{}{Small group of radscorpions on the road.}
{3652}{}{Herd of brahmin wandering along the road.}
{3653}{}{A pack of wild dogs running down the road.}
{3654}{}{Group of hunters heading back to the city.}
{3655}{}{Group of bandits hiding in ambush.}
{3656}{}{Group of marauders hiding in ambush.}
{3657}{}{Group of raiders hiding in ambush.}
{3658}{}{Group of hunters fending off marauders' attack.}
{3659}{}{Group of hunters fending off raiders' attack.}
{3660}{}{Group of hunters fending off robbers' attack.}
{3661}{}{Group of hunters fending off radscorpions' attack.}
{3662}{}{Caravan wandering down the road.}
{3663}{}{Crossroads.}
{3664}{}{Lost Office.}
{3665}{}{Cafe "New Hope".}
{3666}{}{House on Wheels.}
{3667}{}{"Furthur".}
{3668}{}{Hitchhiker.}
{3669}{}{Cheerful Bobby.}
{3670}{}{Bounty hunters from Salt Lake City trying to get bounty on your head.}
{3671}{}{Bounty hunters from Salt Lake City trying to get bounty on your head.}
{3672}{}{Bounty hunters from Salt Lake City trying to get bounty on your head.}
{3673}{}{Crazy mr. Handy.}
{3674}{}{Pile of cars on the way to the city.}
{3675}{}{Tough bandit with a Jackhammer.}
{3676}{}{Escaped convicts.}
{3677}{}{Punks from Salt Lake City.}
{3678}{}{Nomads of the Great Basin.}

# Encounter Table 14 -- RDRS_T
{3700}{}{Small group of pests stuck on the road.}
{3701}{}{Small group of geckos suddenly appeared on the road!}
{3702}{}{Small group of radscorpions on the road.}
{3703}{}{Herd of brahmin wandering along the road.}
{3704}{}{A pack of wild dogs running down the road.}
{3705}{}{Cheyennes returning back from the hunt.}
{3706}{}{Group of immigrants.}
{3707}{}{Group of bandits hiding in ambush.}
{3708}{}{Raiders of Big Louie.}
{3709}{}{Raiders of Big Louie.}
{3710}{}{Group of hunters fending off robbers' attack.}
{3711}{}{Group of hunters fending off bandits' attack.}
{3712}{}{Caravan wandering down the road.}
{3713}{}{Crossroads.}
{3714}{}{Cafe "New Hope".}
{3715}{}{House on Wheels.}
{3716}{}{"Furthur".}
{3717}{}{Hitchhiker.}
{3718}{}{Cheerful Bobby.}

# Encounter Table 15 -- RDRS_D
{3750}{}{Group of carnivorous plants.}
{3751}{}{Group of silver geckos.}
{3752}{}{Flock of geckos.}
{3753}{}{Group of pests.}
{3754}{}{Small group of mole-rats.}
{3755}{}{Small group of pig-rats.}
{3756}{}{Small group of radscorpions.}
{3757}{}{Herd of brahmin.}
{3758}{}{Wild dogs.}
{3759}{}{Cheyennes returning back from the hunt.}
{3760}{}{Group of hunters.}
{3761}{}{Group of bandits}
{3762}{}{Raiders of Big Louie.}
{3763}{}{Raiders of Big Louie.}
{3764}{}{Group of hunters fighting with radscorpions.}
{3765}{}{Group of hunters fighting with wolves.}
{3766}{}{Group of hunters fighting with raiders.}
{3767}{}{Group of hunters fighting with bandits.}
{3768}{}{Crossroads.}
{3769}{}{Cafe "New Hope".}
{3770}{}{Lost Office.}
{3771}{}{Big Hole.}
{3772}{}{Picnic Area.}
{3773}{}{House on Wheels.}
{3774}{}{"Furthur".}
{3775}{}{Giant Egg.}
{3776}{}{Hitchhiker.}
{3777}{}{Cheerful Bobby.}
{3778}{}{"Dear John".}

# Encounter Table 16 -- RDRS_M
{3800}{}{Group of carnivorous plants.}
{3801}{}{Group of silver geckos.}
{3802}{}{Flock of geckos.}
{3803}{}{Group of pests.}
{3804}{}{Small group of mole-rats.}
{3805}{}{Small group of radscorpions.}
{3806}{}{Herd of brahmin.}
{3807}{}{A pack of wolves.}
{3808}{}{Cheyennes returning back from the hunt.}
{3809}{}{Group of hunters.}
{3810}{}{Raiders of Big Louie.}
{3811}{}{Raiders of Big Louie.}
{3812}{}{Group of hunters fighting with radscorpions.}
{3813}{}{Group of hunters fending off wolves' attack.}
{3814}{}{Group of hunters fighting with raiders.}
{3815}{}{Group of Cheyennes fending off wolves' attack.}
{3816}{}{Cafe "New Hope".}
{3817}{}{Big Hole.}
{3818}{}{Picnic Area.}
{3819}{}{House on Wheels.}
{3820}{}{"Furthur".}
{3821}{}{Giant Egg.}
{3822}{}{"Dear John".}

# Encounter Table 17 -- RINO_T
{3850}{}{A pack of wild dogs running down the road.}
{3851}{}{Small group of radscorpions on the road.}
{3852}{}{Small group of pests stuck on the road.}
{3853}{}{Herd of brahmin wandering along the road.}
{3854}{}{Group of slavers with their slaves.}
{3855}{}{Group of slavers attempting to enslave a few people.}
{3856}{}{Gang of slavers and few dogs.}
{3857}{}{City gang.}
{3858}{}{Gang of robbers hiding in ambush.}
{3859}{}{Gang of raiders hiding in ambush.}
{3860}{}{Group of marauders hiding in ambush.}
{3861}{}{Caravan wandering through the ruins.}
{3862}{}{Hitchhiker.}
{3863}{}{Bounty hunters from New Reno trying to get bounty on your head.}
{3864}{}{Bounty hunters from New Reno trying to get bounty on your head.}
{3865}{}{Bounty hunters from New Reno trying to get bounty on your head.}
{3866}{}{Robbers waiting for lonely travelers.}

# Encounter Table 18 -- RED_D
{3900}{}{Group of carnivorous plants.}
{3901}{}{Group of silver geckos.}
{3902}{}{Flock of geckos.}
{3903}{}{Group of golden geckos.}
{3904}{}{Group of pests.}
{3905}{}{Small group of mole-rats.}
{3906}{}{Small group of pig-rats.}
{3907}{}{Small group of radscorpions.}
{3908}{}{A pack of wolves.}
{3909}{}{Nightshade bush guarded by ants.}
{3910}{}{Crossroads.}
{3911}{}{Big Hole.}
{3912}{}{"Dear John".}
{3913}{}{Picnic Area.}
{3914}{}{House on Wheels.}
{3915}{}{"Furthur".}
{3916}{}{Giant Egg.}
{3917}{}{Cheerful Bobby.}
{3918}{}{Mutated tarantools.}

# Encounter Table 19 -- RED_M
{3950}{}{Group of carnivorous plants.}
{3951}{}{Group of silver geckos.}
{3952}{}{Flock of geckos.}
{3953}{}{Group of golden geckos.}
{3954}{}{Group of pests.}
{3955}{}{Small group of mole-rats.}
{3956}{}{Small group of pig-rats.}
{3957}{}{A pack of wolves.}
{3958}{}{Nightshade bush guarded by ants.}
{3959}{}{Body under the landslide.}
{3960}{}{Big Hole.}
{3961}{}{Picnic Area.}
{3962}{}{"Dear John".}
{3963}{}{"Furthur".}
{3964}{}{Giant Egg.}
{3965}{}{Abandoned Nevada rangers' post.}
{3966}{}{Mutated tarantools.}

# Encounter Table 20 -- SALTk_D
{4000}{}{A group of acid geckos.}
{4001}{}{Group of pests.}
{4002}{}{Small group of mole-rats.}
{4003}{}{Small group of pig-rats.}
{4004}{}{Small group of radscorpions.}
{4005}{}{Herd of brahmin.}
{4006}{}{A pack of wild dogs.}
{4007}{}{Group of hunters.}
{4008}{}{Gang of raiders.}
{4009}{}{Group of bandits.}
{4010}{}{Group of bandits sharing their loot with raiders.}
{4011}{}{Group of hunters fending off raiders' attack.}
{4012}{}{Group of hunters fending off bandits' attack.}
{4013}{}{Tanker in the desert.}
{4014}{}{Big Hole.}
{4015}{}{Hitchhiker.}
{4016}{}{Escaped convicts.}
{4017}{}{Punks from Salt Lake City.}
{4018}{}{Filter hunters.}

# Encounter Table 21 -- VGSLT_T
{4050}{}{Small group of pests stuck on the road.}
{4051}{}{Small group of radscorpions on the road.}
{4052}{}{Herd of brahmin wandering along the road.}
{4053}{}{A pack of wild dogs running down the road.}
{4054}{}{Group of hunters returning back to town.}
{4055}{}{Group of bandits hiding in ambush.}
{4056}{}{Group of immigrants.}
{4057}{}{Gang of robbers hiding in ambush.}
{4058}{}{Gang of raiders hiding in ambush.}
{4059}{}{Group of hunters fending off raiders' attack.}
{4060}{}{Group of hunters fending off robbers' attack.}
{4061}{}{Caravan wandering down the road.}
{4062}{}{Locals who chose the path of crime.}
{4063}{}{Crossroads.}
{4064}{}{Lost Office.}
{4065}{}{Cafe "New Hope".}
{4066}{}{House on Wheels.}
{4067}{}{"Furthur".}
{4068}{}{Hitchhiker.}
{4069}{}{Cheerful Bobby.}
{4070}{}{Lynch law.}
{4071}{}{Filter hunters.}
{4072}{}{Nomads of the Great Basin.}

# Encounter Table 22 -- RINO_D
{4100}{}{Group of carnivorous plants.}
{4101}{}{Victims of the apocalypse.}
{4102}{}{Group of pests.}
{4103}{}{Small group of mole-rats.}
{4104}{}{Small group of pig-rats.}
{4105}{}{Small group of radscorpions.}
{4106}{}{Herd of brahmin.}
{4107}{}{Wild angry brahmin.}
{4108}{}{Group of hunters.}
{4109}{}{Gang of raiders.}
{4110}{}{Group of hunters fending off raiders' attack.}
{4111}{}{Cafe "New Hope".}
{4112}{}{Lost Office.}
{4113}{}{Big Hole.}
{4114}{}{Crossroads.}
{4115}{}{Hitchhiker.}
{4116}{}{Picnic Area.}
{4117}{}{House on Wheels.}
{4118}{}{"Furthur".}
{4119}{}{Giant Egg.}
{4120}{}{Cheerful Bobby.}
{4121}{}{"Dear John".}

# Encounter Table 23 -- South_D
{4150}{}{Small group of mole-rats.}
{4151}{}{Small group of radscorpions.}
{4152}{}{A pack of coyotes.}
{4153}{}{A pack of deathclaws.}
{4154}{}{Cafe "New Hope".}
{4155}{}{Lost Office.}
{4156}{}{Big Hole.}
{4157}{}{Crossroads.}
{4158}{}{Picnic Area.}
{4159}{}{House on Wheels.}
{4160}{}{"Furthur".}
{4161}{}{Giant Egg.}
{4162}{}{Hardy's Caravan.}
{4163}{}{"Dear John".}
{4164}{}{Water!}
{4165}{}{Withering spring and mole-rats.}
{4166}{}{Withering spring and radscorpions.}
{4167}{}{Withering spring and carnivorous plants.}
{4168}{}{Withering spring and swarm of mantises.}
{4169}{}{Swarm of mantises.}

# Encounter Table 24 -- South_M
{4200}{}{Group of carnivorous plants.}
{4201}{}{Swarm of mantises.}
{4202}{}{Group of golden geckos.}
{4203}{}{Flock of geckos.}
{4204}{}{Group of pests.}
{4205}{}{Small group of mole-rats.}
{4206}{}{Small group of pig-rats.}
{4207}{}{Small group of radscorpions.}
{4208}{}{Herd of brahmin.}
{4209}{}{A pack of wolves.}
{4210}{}{Coyote hunters, hunting their prey.}
{4211}{}{Leader of the Coyote tribe.}
{4212}{}{Cafe "New Hope".}
{4213}{}{Big Hole.}
{4214}{}{Crossroads.}
{4215}{}{Picnic Area.}
{4216}{}{"Furthur".}
{4217}{}{Giant Egg.}
{4218}{}{Cheerful Bobby.}
{4219}{}{"Dear John".}
{4220}{}{Tribe of cannibals during their lunch time.}

# Encounter Table 25 -- Wind_T
{4250}{}{Small group of pests stuck on the road.}
{4251}{}{Small group of mole-rats stuck on the road.}
{4252}{}{Small group of pig-rats living on the road.}
{4253}{}{Small Group of aliens that accidentally got into this region.}
{4254}{}{Group of silver geckos suddenly appeared on the road!}
{4255}{}{A pack of geckos suddenly appeared on the road!}
{4256}{}{Group of golden geckos suddenly appeared on the road!}
{4257}{}{Swarm of mantises migrating along the road.}
{4258}{}{Small group of radscorpions on the road.}
{4259}{}{Herd of brahmin wandering along the road.}
{4260}{}{A pack of wild dogs running down the road.}
{4261}{}{Group of slavers with their slaves.}
{4262}{}{Group of slavers attempting to enslave a few people.}
{4263}{}{Gang of slavers and few dogs.}
{4264}{}{Group of hunters coming back to town.}
{4265}{}{Group of bandits hiding in ambush.}
{4266}{}{Group of immigrants.}
{4267}{}{Group of farmers wandering on the road.}
{4268}{}{Gang of robbers hiding in ambush.}
{4269}{}{Gang of raiders hiding in ambush.}
{4270}{}{Group of marauders hiding in ambush.}
{4271}{}{Group of hunters fending off marauders attack.}
{4272}{}{Group of hunters fending off raiders' attack.}
{4273}{}{Group of hunters fending off robbers' attack.}
{4274}{}{Group of farmers fending off marauders attack.}
{4275}{}{Group of farmers fending off raiders' attack.}
{4276}{}{Group of farmers fending off robbers' attack.}
{4277}{}{Group of farmers fending off radscorpions' attack.}
{4278}{}{Caravan wandering down the road.}
{4279}{}{Super 8.}
{4280}{}{Crossroads.}
{4281}{}{Lost Office.}
{4282}{}{Cafe "New Hope".}
{4283}{}{House on Wheels.}
{4284}{}{Cheerful Bobby.}
{4285}{}{Desperate newbie that is trying to fend off raiders' attack.}

# Encounter Table 26 -- Wind_D
{4300}{}{Group of carnivorous plants.}
{4301}{}{Group of aliens.}
{4302}{}{Swarm of mantises.}
{4303}{}{Group of golden geckos.}
{4304}{}{Flock of geckos.}
{4305}{}{Group of pests.}
{4306}{}{Small group of mole-rats.}
{4307}{}{Small group of radscorpions.}
{4308}{}{Herd of brahmin.}
{4309}{}{A pack of wild dogs.}
{4310}{}{Group of slavers with their slaves.}
{4311}{}{Group of slavers attempting to enslave a few people.}
{4312}{}{Gang of slavers and a few dogs.}
{4313}{}{Group of hunters.}
{4314}{}{Gang of bandits.}
{4315}{}{Gang of raiders.}
{4316}{}{Group of hunters fending off raiders' attack.}
{4317}{}{Group of hunters fending off bandits' attack.}
{4318}{}{Group of hunters fending off wild dogs' attack.}
{4319}{}{Group of hunters fending off radscorpions' attack.}
{4320}{}{Group of hunters fending off Gecko attack.}
{4321}{}{Group of hunters fending off mantises' attack.}
{4322}{}{Group of hunters fending off aliens' attack.}
{4323}{}{Group of bandits fending off aliens' attack.}
{4324}{}{Gang of raiders fending off aliens' attack.}
{4325}{}{Super 8.}
{4326}{}{Crossroads.}
{4327}{}{Big Hole.}
{4328}{}{Cafe "New Hope".}
{4329}{}{Picnic Area.}
{4330}{}{House on Wheels.}
{4331}{}{"Furthur".}
{4332}{}{Giant Egg.}
{4333}{}{Cheerful Bobby.}
{4334}{}{"Dear John".}
{4335}{}{Desperate newbie that is trying to fend off raiders' attack.}

# Encounter Table 27 -- Wind_M
{4350}{}{Group of carnivorous plants.}
{4351}{}{Swarm of mantises.}
{4352}{}{Group of golden geckos.}
{4353}{}{Flock of geckos.}
{4354}{}{Group of pests.}
{4355}{}{Small group of mole-rats.}
{4356}{}{Small group of radscorpions.}
{4357}{}{Herd of brahmin.}
{4358}{}{A pack of wolves.}
{4359}{}{Group of hunters.}
{4360}{}{Super 8.}
{4361}{}{Big Hole.}
{4362}{}{Cafe "New Hope".}
{4363}{}{Picnic Area.}
{4364}{}{House on Wheels.}
{4365}{}{"Furthur".}
{4366}{}{Giant Egg.}
{4367}{}{Cheerful Bobby.}
{4368}{}{"Dear John".}
{4369}{}{Desperate newbie that is trying to fend off raiders' attack.}

# Encounter Table 28 -- Zona_D
{4400}{}{Group of aliens.}
{4401}{}{Flock of geckos.}
{4402}{}{Group of golden geckos.}
{4403}{}{Small group of radscorpions.}
{4404}{}{Big Hole.}

# Encounter Table 29 -- VGSX_T
{4450}{}{Small group of pests stuck on the road.}
{4451}{}{Small group of radscorpions on the road.}
{4452}{}{Herd of brahmin wandering along the road.}
{4453}{}{Caravan wandering down the road.}
{4454}{}{Locals who chose the path of crime.}
{4455}{}{One of the Bloom Brothers.}
{4456}{}{Crossroads.}
{4457}{}{Lost Office.}
{4458}{}{Cafe "New Hope".}
{4459}{}{House on Wheels.}
{4460}{}{"Furthur".}
{4461}{}{Hitchhiker.}
{4462}{}{Cheerful Bobby.}
{4463}{}{Lynch law.}
{4464}{}{Filter hunters.}
{4465}{}{Nomads of the Great Basin.}

# Encounter Table 30 -- VEGS_T
{4500}{}{Small group of pests stuck on the road.}
{4501}{}{Swarm of mantises migrating along the road.}
{4502}{}{Group of silver geckos suddenly appeared on the road.}
{4503}{}{Small group of radscorpions on the road.}
{4504}{}{Herd of brahmin wandering along the road.}
{4505}{}{A pack of wild dogs running down the road.}
{4506}{}{Group of slavers with their slaves.}
{4507}{}{Group of slavers attempting to enslave a few people.}
{4508}{}{Gang of slavers and a few dogs.}
{4509}{}{Group of bandits hiding in ambush.}
{4510}{}{Group of farmers wandering on the road.}
{4511}{}{Gang of robbers hiding in ambush.}
{4512}{}{Gang of raiders hiding in ambush.}
{4513}{}{Group of farmers fending off marauders attack.}
{4514}{}{Group of farmers fending off raiders' attack.}
{4515}{}{Group of farmers fending off robbers' attack.}
{4516}{}{Group of farmers fending off radscorpions' attack.}
{4517}{}{Caravan wandering through the ruins.}
{4518}{}{Crossroads.}
{4519}{}{Lost Office.}
{4520}{}{Big Hole.}
{4521}{}{Cafe "New Hope".}
{4522}{}{House on Wheels.}
{4523}{}{"Furthur".}
{4524}{}{Cheerful Bobby.}
{4525}{}{Bounty hunters from Las Vegas trying to get bounty on your head.}
{4526}{}{Bounty hunters from Las Vegas trying to get bounty on your head.}
{4527}{}{Bounty hunters from Las Vegas trying to get bounty on your head.}
{4528}{}{Agent from patrol agency gone feral.}
{4529}{}{Neon Gangster and his gang.}
{4530}{}{Filter hunters.}
{4531}{}{The Kings' Gang.}
{4532}{}{Desperate redneck.}
{4533}{}{Pervert with his sex slave.}
{4534}{}{Two members of Kings' gang trying to bury a body.}

# Encounter Table 31 -- VEGS_D
{4550}{}{Group of carnivorous plants.}
{4551}{}{Swarm of mantises.}
{4552}{}{Group of silver geckos.}
{4553}{}{Flock of geckos.}
{4554}{}{Group of pests.}
{4555}{}{Small group of mole-rats.}
{4556}{}{Small group of pig-rats.}
{4557}{}{Small group of radscorpions.}
{4558}{}{Herd of brahmin.}
{4559}{}{A pack of coyotes.}
{4560}{}{A pack of wolves.}
{4561}{}{Group of slavers with their slaves.}
{4562}{}{Group of slavers attempting to enslave a few people.}
{4563}{}{Gang of slavers and a few dogs.}
{4564}{}{Group of hunters.}
{4565}{}{Gang of raiders.}
{4566}{}{Gang of raiders attacking hunters.}
{4567}{}{Gang of raiders fending off radscorpions' attack.}
{4568}{}{Gang of raiders fending off pests attack.}
{4569}{}{Group of hunters fending off mantises' attack.}
{4570}{}{Group of hunters fending off radscorpions' attack.}
{4571}{}{Group of hunters fending off pests attack.}
{4572}{}{Raiders and bandits sharing loot.}
{4573}{}{Crossroads.}
{4574}{}{Big Hole.}
{4575}{}{Cafe "New Hope".}
{4576}{}{Picnic Area.}
{4577}{}{House on Wheels.}
{4578}{}{"Furthur".}
{4579}{}{Giant Egg.}
{4580}{}{Cheerful Bobby.}
{4581}{}{"Dear John".}
{4582}{}{Lynch law.}
{4583}{}{Filter hunters.}

# Encounter Table 32 -- VEGS_M
{4600}{}{Group of carnivorous plants.}
{4601}{}{Group of silver geckos.}
{4602}{}{Flock of geckos.}
{4603}{}{Group of golden geckos.}
{4604}{}{Group of pests.}
{4605}{}{Small group of mole-rats.}
{4606}{}{Small group of pig-rats.}
{4607}{}{Small group of radscorpions.}
{4608}{}{A pack of wolves.}
{4609}{}{Group of hunters.}
{4610}{}{Group of hunters fending off bandits' attack.}
{4611}{}{Group of hunters hunting small animals.}
{4612}{}{Group of hunters hunting small animals.}
{4613}{}{Big Hole.}
{4614}{}{Cafe "New Hope".}
{4615}{}{Picnic Area}
{4616}{}{House on Wheels.}
{4617}{}{"Furthur".}
{4618}{}{Giant Egg.}
{4619}{}{"Dear John".}

# Encounter Table 33 -- VEGS_J
{4650}{}{Group of pests.}
{4651}{}{Dump of tires.}

# Encounter Table 34 -- SALT_Z
{4700}{}{Frightening Silence}

# Encounter Table 35 -- RINW_T
{4750}{}{A pack of Coyotes spying for the road.}
{4751}{}{Small group of radscorpions on the road.}
{4752}{}{Small group of pests stuck on the road.}
{4753}{}{Herd of brahmin wandering along the road.}
{4754}{}{Locals who chose the path of crime.}
{4755}{}{Group of slavers with their slaves.}
{4756}{}{Group of slavers attempting to enslave a few people.}
{4757}{}{Gang of slavers and a few dogs.}
{4758}{}{Group of bandits hiding in ambush.}
{4759}{}{Gang of robbers hiding in ambush.}
{4760}{}{Gang of raiders hiding in ambush.}
{4761}{}{Group of marauders hiding in ambush.}
{4762}{}{Caravan wandering through the ruins.}
{4763}{}{Crossroads.}
{4764}{}{Lost Office.}
{4765}{}{Big Hole.}
{4766}{}{Cafe "New Hope".}
{4767}{}{House on Wheels.}
{4768}{}{"Furthur".}
{4769}{}{Hitchhiker.}
{4770}{}{Cheerful Bobby.}

# Encounter Table 36 -- South_MD
{4800}{}{Group of carnivorous plants.}
{4801}{}{Swarm of mantises.}
{4802}{}{Group of golden geckos.}
{4803}{}{Flock of geckos.}
{4804}{}{Group of pests.}
{4805}{}{Small group of mole-rats.}
{4806}{}{Small group of pig-rats.}
{4807}{}{Small group of radscorpions.}
{4808}{}{Herd of brahmin.}
{4809}{}{A pack of wolves.}
{4810}{}{Cafe "New Hope".}
{4811}{}{Lost Office.}
{4812}{}{Big Hole.}
{4813}{}{Crossroads.}
{4814}{}{Picnic Area}
{4815}{}{"Furthur".}
{4816}{}{Giant Egg.}
{4817}{}{Cheerful Bobby.}
{4818}{}{"Dear John".}

# Encounter Table 37 -- BLCK_B
{4850}{}{Group of silver geckos.}
{4851}{}{Group of pests.}
{4852}{}{Small group of mole-rats.}
{4853}{}{Small group of radscorpions.}
{4854}{}{Herd of wild brahmin.}
{4855}{}{A pack of coyotes.}
{4856}{}{Herd of brahmin attacked by geckos.}
{4857}{}{House on Wheels.}
{4858}{}{Giant Egg.}
{4859}{}{"Dear John".}
{4860}{}{Wild angry brahmin.}

# Encounter Table 38 -- HTRN_D
{4900}{}{Group of pests.}
{4901}{}{Small group of pig-rats.}
{4902}{}{Small group of mole-rats.}
{4903}{}{A pack of coyotes.}
{4904}{}{Several desperate marauders.}
{4905}{}{Hitchhiker.}

# Encounter Table 39
{4950}{}{Group of scared pests.}
  
# Encounter Table 40
{5000}{}{}

# Encounter Table 41
{5050}{}{}

# Encounter Table 42
{5100}{}{}

# Encounter Table 43
{5150}{}{}

# Encounter Table 44
{5200}{}{}

# Encounter Table 45
{5250}{}{}

# Encounter Table 46
{5300}{}{}

# Encounter Table 47
{5350}{}{}

# Encounter Table 48
{5400}{}{}

# Encounter Table 49
{5450}{}{}

# Encounter Table 50
{5500}{}{}

# Encounter Table 51
{5550}{}{}

# Encounter Table 52
{5600}{}{}

# Encounter Table 53
{5650}{}{}

# Encounter Table 54
{5700}{}{}

# Encounter Table 55
{5750}{}{}

# Encounter Table 56
{5800}{}{}

# Encounter Table 57
{5850}{}{}

# Encounter Table 58
{5900}{}{}

# Encounter Table 59
{5950}{}{}

# Encounter Table 60
{6000}{}{}

# Encounter Table 61
{6050}{}{}

# Encounter Table 62
{6100}{}{}

# Encounter Table 63
{6150}{}{}

# Encounter Table 64
{6200}{}{}

# Encounter Table 65
{6250}{}{}

# Encounter Table 66
{6300}{}{}

# Encounter Table 67
{6350}{}{}

# Encounter Table 68
{6400}{}{}

# Encounter Table 69
{6450}{}{}

# Encounter Table 70
{6500}{}{}

# Encounter Table 71
{6550}{}{}

# Encounter Table 72
{6600}{}{}

# Encounter Table 73
{6650}{}{}

# Encounter Table 74
{6700}{}{}

# Encounter Table 75
{6750}{}{}